### ISSUE TITLE
Language Switch isn't compatible with `CookiePolicyOptions` / `ITrackingConsentFeature`

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#10006]
* Your **ABP Framework version**: 4.4.2
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: MVC
* Your database provider(EF Core/MongoDB): /
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem

### Steps to reproduce:

1. Create new template with multiple languages
2. Configure `CookiePolicyOptions`:
```csharp
Configure<CookiePolicyOptions>(options =>
{
    // This lambda determines whether user consent for non-essential 
    // cookies is needed for a given request.
    options.CheckConsentNeeded = context => true;
    options.MinimumSameSitePolicy = SameSiteMode.Lax;
});
```
3. Add the cookie policy middleware by adding `app.UseCookiePolicy();`
4. Launch the application and attempt to change the language, you'll be redirected multiple times until the browser displays a `too much redirects`-error or the language won't be applied (depending on your method of language switching)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/10009
