### ISSUE TITLE
How to configure two separate databases per tenant?

### ISSUE THREAD

**Issue by balessi75** [abpframework/abp#10012]
I'm using ABP 4.4.0 Blazor Server (Commercial)

We've read about the ability for each module to have it's own database connection. We've also read about how to separate different ABP modules into different databases. We've also read about how to create a separate DBContext for a secondary database when dealing with a shared DB multi tenancy model. However, we haven't been able to determine how to allow for access to two databases per tenant in the tenancy model where each tenant has their own databases. 

The tenancy management UI only allows for one tenant specific connection string to be specified. How can we get one module to query two specific databases dedicated to the logged in tenant?

**Comment by johnwanzhi** [comment]
Hello, can you provide the code of how you can configure a single database for each tenant? I searched almost all the documents and didn't introduce the details of this
