### ISSUE TITLE
Downgrade ABP CLI / Install a specific version of ABP CLI

### ISSUE THREAD

**Issue by amsaighi** [abpframework/abp#10016]
I tried to downgrade our project via ABP CLI using  from 4.4.2 to 4.3.1 
`Abp update --nuget --npm --version 4.3.1` it doesn't work

**Comment by ebicoglu** [comment]
use the following commands

```
dotnet tool uninstall -g volo.abp.cli
dotnet tool install -g volo.abp.cli --version 4.3.1
```

**Comment by amsaighi** [comment]
> use the following commands
> 
> ```
> dotnet tool uninstall -g volo.abp.cli
> dotnet tool install -g volo.abp.cli --version 4.3.1
> ```

My scenario we created a new project ( Application ) based in 4.4.2 and it related with our modules 4.3.1 we found some problem.
We have a lot of module developed by 4.3.1 and we are working with. in our case we can't update all of them because it use in dev for others projects.

By the way I know all of ABP and dotnet CLI ( I read docs ) :D

**Comment by yekalkan** [comment]
Hi @amSaighi,

`abp downgrade` command won't be much useful. It will cover very rare cases.

Thank you for your suggestion.

**Comment by amsaighi** [comment]
> Hi @amSaighi,
> 
> `abp downgrade` command won't be much useful. It will cover very rare cases.
> 
> Thank you for your suggestion.

Yep it's rare cases, I did it manually 
Thank you
