### ISSUE TITLE
Cannot handle error in eventbus using Rebus

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#10014]
Hi,

I'm using abp.eventbus.Rebus v4.4.0 but I cannot handle error message by implement `IEventErrorHandler`. I don't know if I do any wrong ?

<img width="396" alt="Screen Shot 2021-09-11 at 11 32 28 AM" src="https://user-images.githubusercontent.com/46510130/132936311-89658b0a-b478-4289-ad64-adf0185eb7cb.png">

I also tried implement the way in Rebus wiki guide `IHandleMessages<IFailed<DoStuff>>` and tried all the ways but nothing enter to the method ErrorHandler

<img width="520" alt="Screen Shot 2021-09-11 at 11 34 17 AM" src="https://user-images.githubusercontent.com/46510130/132936334-d35de0ce-84a0-435e-ade0-f7a8b9e42eac.png">

My rebus configure in module as below

<img width="925" alt="Screen Shot 2021-09-11 at 11 26 50 AM" src="https://user-images.githubusercontent.com/46510130/132936185-36663daf-aaee-436b-98f9-47084ce43c9e.png">

Thanks

**Comment by realLiangshiwei** [comment]
Cloud you share a project to reproduce? thanks.
