### ISSUE TITLE
RemoteService api parameter input with List<> Property cannot be passed to HttpGet method

### ISSUE THREAD

**Issue by Sean-Fang** [abpframework/abp#10025]
### GitHub Issues

- **ABP Framework version**： 4.3.3
- No explicit error message except result from remote service not correct
- Steps needed to **reproduce** the problem: 
    - Create an app service and configure auto api controller 
    - Add app service method with HttpGet type (either by convention or add attribute ) 
    - Add a GetRequestDto - 'input' with a list property e.g. List<Guid> xxxIds {get;set;} 
    - Call the web api using remote service

The parameters in xxxIds cannot be bound on url.

I can see that the issue should be solved here but unfortunately the issue is still there with a bit different scenario. https://github.com/abpframework/abp/issues/4969#issue-673929820

**Comment by maliming** [comment]
We will try to improve the remote call after https://github.com/abpframework/abp/pull/9905

**Comment by maliming** [comment]
> The parameters in xxxIds cannot be bound on url.

Can you share a project?

**Comment by Sean-Fang** [comment]
> > The parameters in xxxIds cannot be bound on url.
> 
> Can you share a project?

Sorry for late reply. I was trying to create a new project for you reproducing the issue however the issue disappeared from that new project. 
Now I am working on targeting the issue from my side. 
Thank you vey much for your time.
You may close the issue now.
