### ISSUE TITLE
EntityCreatedEventData handler not hit after creating IdentityUser (if no tenant is set)

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#10026]
I'm having problem getting `HandleEventAsync` for `IDistributedEventHandler<EntityCreatedEventData<IdentityUser>>` to hit when I register a user without having a tenant (just register from the login page without tenant).

But [my code](https://github.com/sturlath/RolesDemo/blob/ba382da19ea98cc2a7ae2b5ecf675655cee0b73c/src/RolesDemo.Domain/Users/RegisteredIdentityUserHandler.cs#L44) **gets hit** when I create a user when logged-in **as a tenant.**

I´m not immediately seeing what I can do about this... any thoughts?

* Your **ABP Framework version**. 4.4.2
* Your database provider: EF Core

**Comment by sturlath** [comment]
No one? I can’t see what I can do to affect this and there is nothing in the docs. 

How can I get the event if there is no tenant? Should that matter? Is it therefore a bug or am I missing something?

**Comment by maliming** [comment]
hi

Can you share a simple template project?

**Comment by sturlath** [comment]
Hi you must have missed it @maliming but there is a link to my git repo code where you can just get and try out. 

Just add a brakepoint in the line below and register a user without being logged in as a tenant (doesnt get hit) and then create a user when you are logged in as a user and see it get hit

Put brakepoint here https://github.com/sturlath/RolesDemo/blob/ba382da19ea98cc2a7ae2b5ecf675655cee0b73c/src/RolesDemo.Domain/Users/RegisteredIdentityUserHandler.cs#L44

**Comment by sturlath** [comment]
@maliming you tried it? Valid problem?

**Comment by acjh** [comment]
I tried it (register a user without being logged in as a tenant) and the breakpoint gets hit.

# Aside

For distributed events, use `EntityCreatedEto<UserEto>` in place of `EntityCreatedEventData<IdentityUser>`.
https://docs.abp.io/en/abp/4.4/Distributed-Event-Bus#pre-defined-events

`EntityCreatedEventData` is a pre-built event for the local event bus.
https://docs.abp.io/en/abp/latest/Local-Event-Bus#pre-built-events

If you switch to a real distributed event bus (RabbitMQ, Kafka, Rebus), then `EntityCreatedEventData` will not work.

**Comment by sturlath** [comment]
Humm OK are you sure we are doing the same thing @acjh? I just retried this on 3 versions of VS,reboot etc. :-)

There is just no way for me to register a new user and hit the [brake point](https://github.com/sturlath/RolesDemo/blob/ba382da19ea98cc2a7ae2b5ecf675655cee0b73c/src/RolesDemo.Domain/Users/RegisteredIdentityUserHandler.cs#L44) in `RegisteredIdentityUserHandler`.

If I register like this, its just **not hit**
![image](https://user-images.githubusercontent.com/2386572/133883252-849933a3-8346-473c-9886-d9d56dfc600f.png)

but if I´m logged in as admin, and  add a user **it gets hit**
![image](https://user-images.githubusercontent.com/2386572/133883315-bdecdc78-fbec-429f-add6-8b3d1aea12f5.png)

All in the same debugging session so I know the brake point (should) work... 

And about your 'Aside' comments (thanks btw), I was using `IDistributedEventHandler<EntityCreatedEto<UserEto>>` **but** [that's](https://github.com/sturlath/RolesDemo/blob/ba382da19ea98cc2a7ae2b5ecf675655cee0b73c/src/RolesDemo.Domain/Users/RegisteredTenantUserHandler.cs#L51)  **not hit either** when I create the user so I thought that something special was needed so I thought (incorrectly now) that `EntityCreatedEventData<IdentityUser>` was the way to go. Clearly `IDistributedEventHandler` is needed.

But then my **problem is then rather** that `IDistributedEventHandler<EntityCreatedEto<UserEto>>` is not hit for creating `IdentityUser`

Take a look at my `RegisteredTenantUserHandler ` [here](https://github.com/sturlath/RolesDemo/blob/ba382da19ea98cc2a7ae2b5ecf675655cee0b73c/src/RolesDemo.Domain/Users/RegisteredTenantUserHandler.cs#L51) and see that its never hit either when creating the user.

If you are able to hit these brake points I have no idea what is going on, I have even tried to throw exceptions and log in case its some brake point issue but it just doesn't execute the code...

**Comment by acjh** [comment]
Yes, that's also how I do it (register a user without being logged in as a tenant).

Long shot, but can you clone (not copy) your repo to a new folder and run that?

**Comment by sturlath** [comment]
Damn... and you are logged in to identity with admin/1q2w3E* ?

![image](https://user-images.githubusercontent.com/2386572/133885912-cbd32a68-885e-4e89-9f4e-ba55ed9f78fd.png)

Here you can see what I´m doing, all in the same debug session with a newly cloned folder (its 48 sec). First where it doesn´t brake and then when it brakes...
![DoesNotBrake](https://user-images.githubusercontent.com/2386572/133886319-34640568-8752-476f-8038-23c1f280dc50.gif)

And btw I had also brake point in `RegisteredTenantUserHandler.cs` that never got hit either... except when logged in as the admin host..

Now I´m just lost...

**Comment by acjh** [comment]
Ok, I figured it out.

While logged in, creating a user from main app calls `https://localhost:44365/api/identity/users`.
While not logged in, registering from identity server app calls `https://localhost:44315/Account/Register`.

For the latter, the breakpoint gets hit in the `.IdentityServer` debug session.
I suppose you only put a breakpoint in the `.HttpApi.Host` debug session, right?

Btw, it is unrelated to tenant. Your gif also shows that you logged in as host admin.

**Comment by sturlath** [comment]
Humm OK how does that work? Everything that is happening in my gif is in **one and the same** debugging session.

But you are totally correct that the code gets executed, I added a output log statement and if

- I´m creating a user from the main page see the message in the IdentiyServer console
- but if I´m logged in as a tenant I see the output in the Host console

And also how are you able to hit the point and not me?

**Comment by acjh** [comment]
How are you running your `.IdentityServer` instance?

I just run it in Visual Studio and set the same breakpoint.

**Comment by sturlath** [comment]
🙈🙈🙈 feeling like a **total** idiot! I had the identyserver set to no debug!! 😂😅

Sorrt for waisting your time **BUT** I learned few thing along the way.. now closing this “issue”
