### ISSUE TITLE
Permissions UI, not updating the number of permissions selected

### ISSUE THREAD

**Issue by nev-21** [abpframework/abp#10024]
### Abp version 

ABP Framework version: 4.4.0
Angular
EF Core (npgsql)

### Reproduce

Create a group called TESTGROUP and add permissions inside the PermissionDefinitionProvider. 
After that login as admin, and go to roles UI.

 1. select permission for a role and the popup will appear.
 2. select the group you created, the name will be TESTGROUP(0)
 3. enable one permission

###  The issue

After you enable the permission, the name TESTGROUP(0) should change to  TESTGROUP(1) .
But it remains showing (0), even after save.

![image](https://user-images.githubusercontent.com/89469783/133156500-e0b7efd7-7659-412c-aa25-6f5756e69a67.png)

Thanks

**Comment by mehmet-erim** [comment]
Hello @nev-21

There is no problem in v5.0.0-rc.1. Do you consider updating your app?

**Comment by nev-21** [comment]
Hello @mehmet-erim. It is working now. Thanks
