### ISSUE TITLE
Incorrect french translation of "Name" and "Surname" in Account UI

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#10028]
In [fr.json file of Account UI](https://github.com/abpframework/abp/blob/89cec4aaf9587c8cb6e66762f88599232d84765a/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/Resources/fr.json), "Name" and "Surname" should be :

```json
"DisplayName:Name": "Prénom",
"DisplayName:Surname": "Nom"
```

These errors may lead to bad input since initially `"DisplayName:Name"` was translated in `"Nom"`.

ABP 4.4.2.

**Comment by realLiangshiwei** [comment]
HI,

Thanks, we will update it.

**Comment by Stirda** [comment]
@maliming Beware that french short translation of the concept of full name is "Nom", not "Prénom". So if in [this change on ...cation.Contracts/Volo/Docs/Admin/Localization/Resources/Docs/ApplicationContracts/fr.json](https://github.com/abpframework/abp/pull/10030/files/a1fb2274e20d63f855383f4e46361cfe4682dc85#diff-1d6c82fa82befe6c7faeda8cd1adc65975321a37a44caca6fb9c1addeae867a0), `DisplayName:Name` means the full name of a person, then the change should be `"DisplayName:Name": "Nom",` not `"DisplayName:Name": "Prénom",`.

**Comment by Stirda** [comment]
Problem cited on 15 Sep 2021 above is still here : 

- `"DisplayName:Name" : "Prénom"` : translation not appearing in `modules/identity/src/Volo.Abp.Identity.Blazor/Pages/Identity/UserManagement.razor`, probably because `Nom` as, again, two usages in french, and I suppose a translation override another from another resource file: 
  - Besides "Prénom", "Prénom" is the translation of "First name", and "Nom" is the translation of "Last name".
  - But, used alone, "Nom" generally means "Full name".
  - So: "First name" = "Prénom",
  - "Last name" = "Nom" (or, if you want to be absolutely unambiguous : "Nom de famille")
  - "Name" = "Nom".
  - "Fullname" = "Nom".
- `"mot de passe"`: deserves an initial capital letter.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/32323613/156575989-3e69c712-bae9-4633-925d-bcdde8b846b8.png">

**Comment by maliming** [comment]
Please create a new issue.

**Comment by realLiangshiwei** [comment]
@Stirda 
Hi,  Could you send a PR if you have time because we don't know French much.
