### ISSUE TITLE
Custom permissions are not listed in UI

### ISSUE THREAD

**Issue by emilsjog** [abpframework/abp#10023]
UI: **blazor-server**
Migrated from **abp 4.3** to **abp 4.4.1** and cannot see the permissions in the modal. Only the identity permissions are listed. 

![image](https://user-images.githubusercontent.com/6585041/133071965-063c7de0-0817-409d-be4f-5fd1eb83c098.png)

Normally in **abp 4.3** I can see my 20+ custom groups.

Anyone with the same problem?

**Comment by maliming** [comment]
Please try to reproduce this with the brand new **4.4.1** template project.

**Comment by emilsjog** [comment]
Upgraded to **abp 4.4.2** and got it working. Permissions are now displayed correct.
I don't know if there was a bug in **4.4.1** but at least it's working on the latest version.
