### ISSUE TITLE
Question about the eventbus retry logic

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#10034]
With https://github.com/abpframework/abp/pull/8829 we had introduced a retry system. That's fine, but when I investigate it I see that it re-publishes the message when it gets an error from the handler. This may work in some cases, but it can be a problem if the events should be processed by order. When we re-publish the event, it goes to the end of the queue and the event order changes.
Should we cancel this logic? We are introducing inbox pattern, so it will retry on errors. Maybe we don't need that re-publish system at all. What do you think guys?

**Comment by realLiangshiwei** [comment]
I think we don't need the re-publish system anymore, we can remove it.

**Comment by hikalkan** [comment]
OK @realLiangshiwei please work on that ;)

**Comment by GreatGodJackChen** [comment]
How should we solve the problem of wireless retry? Although it is to solve the sequence problem, system stability should be the top priority. From a business perspective, I think consumption should be paused when the consumption error reaches the retry count, and consumption should be resumed after the business is resolved. I don't know if you have any new solutions now, but I haven't seen any in the documentation

**Comment by GreatGodJackChen** [comment]
Can your inbox solve the problem of duplicate consumption? Obviously not, without understanding the real problem, the problem lies in the infinite retry of consumption due to failed consumption
