### ISSUE TITLE
Document: Deployment with multiple instances

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#10031]
When we deploy the application in a clustered environment where multiple instances of the application/service are concurrently running, we should take care of some stuff. We should write a guide to make this explicit. The following topics are the first ones we should include:

* Distributed cache
* BLOB storing
* background workers & jobs
* Configuring distributed lock providers

**Comment by gdlcf88** [comment]
> If you are using an external background job integration (e.g. [Hangfire](https://docs.abp.io/en/abp/latest/Background-Workers-Hangfire) or [Quartz](https://docs.abp.io/en/abp/latest/Background-Workers-Quartz)) instead of the default background job manager, then please refer your provider's documentation to learn how it should be configured for a clustered environment.

Should we add something similar to the above in [Implementing Background Workers](https://docs.abp.io/en/abp/latest/Deployment/Clustered-Environment#implementing-background-workers)?

**Comment by hikalkan** [comment]
@gdlcf88 already added: https://docs.abp.io/en/abp/latest/Deployment/Clustered-Environment#configuring-background-jobs
Thanks.

**Comment by hikalkan** [comment]
@gdlcf88 Background workers have no hangfire or quartz integration. Why do you think it is needed?

**Comment by gdlcf88** [comment]
> @gdlcf88 Background workers have no hangfire or quartz integration. Why do you think it is needed?

![image](https://user-images.githubusercontent.com/30018771/166147283-42bf7a89-98be-4320-b4b9-a14029de50dd.png)

I think it does.

https://docs.abp.io/en/abp/latest/Background-Workers#integrations
