### ISSUE TITLE
Is there a way to extend a regulare propery (not in ExtraProperties) for IdentyUser?

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10043]
I am aware that, in the latest version of vbp, AppUser has been replaced by IdentityUser, and it seems there is no way to refer to a regular property (not in ExtraProperties) for IdentyUser on the server side code. 
e.g. By following [https://docs.abp.io/en/abp/latest/Module-Entity-Extensions](url), it could create a new column "SocialSecurityNumber" in AppUsers table, however, I didn't find any information which tells how to add the extended property to IdentityUser class, so that, I can write some code like,

var user = await _identityUserRepository.FindByNormalizedUserNameAsync("abc");
var ssn = user.SocialSecurityNumber; 
 or 
var ssn = user.GetSocialSecurityNumber(); 

What wold be the possible way to achieve this? 
Thanks

**Comment by maliming** [comment]
https://community.abp.io/articles/unifying-dbcontexts-for-ef-core-removing-the-ef-core-migrations-project-nsyhrtna#using-custom-properties-in-the-application-code

**Comment by lht6** [comment]
Thanks, @maliming

**Comment by lht6** [comment]
The regular property created by following steps in the above link.
