### ISSUE TITLE
Generate dynamic js proxy should excludes existing static js proxy

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#10044]
Related: https://github.com/abpframework/abp/issues/9864

We build a static proxy system, but the dynamic js proxy will generate duplicate scripts, we should exclude the existing static js proxy when generating dynamic js proxy scripts

**Comment by hikalkan** [comment]
I think this is duplicate of https://github.com/abpframework/abp/issues/9955

**Comment by realLiangshiwei** [comment]
right, close.
