### ISSUE TITLE
BLOB Storing container class location

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#10058]
* Your **ABP Framework version**. 4.3.3
* Your **User Interface** angular
* Your database provider(EF Core)

I want to use [Blob Storing System](https://docs.abp.io/en/abp/latest/Blob-Storing) and to create a [container](https://docs.abp.io/en/abp/4.4/Blob-Storing#typed-iblobcontainer) class.  Which layer would be correct location for container class?  (is Domain.Shared appropriate location?)

**Comment by yekalkan** [comment]
Domain layer will be correct.
