### ISSUE TITLE
How can i stay on current page after datatables.ajax.reload()

### ISSUE THREAD

**Issue by mentianyi** [abpframework/abp#10054]
After update some value ,i need to refresh data,but ajax.reload will jump to first page.

when i set stateSave:true in datatables options,page parameter can save state,but reload() not work correct.

**Comment by mentianyi** [comment]
Problem solved.

[_table.ajax.reload(null,false);](https://datatables.net/reference/api/ajax.reload())

**Comment by chaisoftthailand** [comment]
<script type="text/javascript" src="js/plugins/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="js/plugins/dataTables.bootstrap.min.js"></script>
	<script type="text/javascript">$('#sampleTable1').DataTable(
     {
        "columndefs": [ {
          ajax: "data.json",
          "targets": 'no-sort',
          "orderable": false,
         }]

	});
	setInterval(function () {
    table.ajax.reload();
}, 1000 );
     </script>
