### ISSUE TITLE
BusinessException not shown in AppService 

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#10050]
### GitHub Issues

* Your **ABP Framework version**: 4.4
* Your **User Interface** type: Blazor Server
* Your database provider: EF Core

acording to the documentation we use buisness exceptions inside manager ( like you do in the author example ). these exceptions are not shown, just a generic "an internal error happen" message is shown.

when stepping through the code i found that only IUserFriendlyException, IHasValidationErrors or ErrorCodes that start with your prefix / resource name are shown to the user. there is no information about this in the documentation or in the tutorial.

would be nice if you could add these informations and give some advice about what the purpose of BuisnessException and UserFriendlyException are and why only prefixed BuisnessException are shown correctly

**Comment by maliming** [comment]
hi
https://github.com/abpframework/abp/issues/9910#issuecomment-913928509

**Comment by puschie286** [comment]
that is not the problem - the question is if you can add the information about error code formatting and which exceptions are passed to the user to the documentation

**Comment by puschie286** [comment]
@maliming 
we use HandleErrorAsync but it only works under the conditions metioned in the description
