### ISSUE TITLE
Razor Filter Error with Async Task

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#10056]
Hi,
version : last 

i've an error when i tried to trwo exeption from async Task : 

in my Razor index.html.cs ,  i have : 

```csharp
 public async Task OnGetAsync()
        {

          ////

            if (response.IsSuccessStatusCode)
            {
                ////////

              /////////
            }
            else
            {
                throw new Exception("Error Message");
            }
 }
```

when i call my page : 

Exception: Error Message
Myproject.Web.Pages.Clients.IndexModel.OnGetAsync() in Index.cshtml.cs
+
                throw new Exception("Error Message");
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+NonGenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)

**Comment by maliming** [comment]
What is the result of your expectations?

**Comment by aelhadi** [comment]
throwing freindly error message.
