### ISSUE TITLE
Remove the "host/" prefix of blob name when the blob container is set to "IsMultiTenant = false"

### ISSUE THREAD

**Issue by eneskoroglu** [abpframework/abp#10057]
Hi @hikalkan and @maliming ,

As mentioned in #5492 and #5510 we also need this feature for a limited access on an existing directory.

I think you can do it with a parameter like **AppendHostNameToBasePath** as existing parameter **AppendContainerNameToBasePath**. So no one does not have to do any change.

I am trying to access an existing directory and I do not have permission to add a subdirectory with host name and move the files under to that (host) directory. I can only have read permission on them, so doing this request with a parameter would be great.

**Comment by maliming** [comment]
hi @eneskoroglu 

I think you can custom the `IXXXBlobNameCalculator`.
