### ISSUE TITLE
Angular UI: Create new secondary entrypoints and move the related proxies to there

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#10060]
We've decided to create new secondary entry points and move proxy files there for better DX. 
For example:
You can import identity module proxies from the `@abp/ng.identity/proxy` entry point like this:

```ts
import { IdentityUserService } from '@abp/ng.identity/proxy'

@Component({})
export class YourComponent { 
   constructor(private identityUserService: IdentityUserService) {}
}
```

Before, you could import these from directly main entry points (@abp/ng.identity). As of v5.0-preview, you should change your imports like the code example above.

**Comment by bnymncoskuner** [comment]
Following proxies have been affected

- `@abp/ng.account` to `@abp/ng.account.core/proxy` **
- `@abp/ng.feature-management` to `@abp/ng.feature-management/proxy`
- `@abp/ng.identity` to `@abp/ng.identity/proxy`
- `@abp/ng.permission-management` to `@abp/ng.permission-management/proxy`
- `@abp/ng.tenant-management` to `@abp/ng.tenant-management/proxy`
- Profile service is deleted from `@abp/ng.core`. Instead, you can import it from `@abp/ng.identity/proxy`

**: Package is also changed
