### ISSUE TITLE
The way to change password policy

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10072]
Is there a way to change the password policy in identity user creating and updating? like, set the maximum password to 10, and remove Uppercase and Special character requirement.

**Comment by JadynWong** [comment]
docs: https://docs.abp.io/en/abp/latest/Modules/Identity#options

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio#configure-identity-services-1
