### ISSUE TITLE
Disabling tenant filter using IDataFilter does not work in a CrudAppService within CreateFilteredQueryAsync

### ISSUE THREAD

**Issue by mahdighorbanpour** [abpframework/abp#10073]
* Your **ABP Framework version : 4.4.2**.
* Your database provider(EF Core)
* Steps needed to **reproduce** the problem.
- Define an entity with IMultiTenant interface
- Define a CrudAppService for it
- override CreateFilteredQueryAsync and disable the IMultiTenant filter

Hi, I have a entity with IMultiTenant interface, I need to disable the filter for tenantId in the overrided method CreateFilteredQueryAsync. If I define a varriable inside my using statement and use the same query to get the list, it works and I get all the records, however when it goes outside of the CreateFilteredQueryAsync (used in the Get, GetAll by default in the base CrudAppService) it will be reset and I get no records back.
```
public class RestaurantsAppService
        : CrudAppService<
            Restaurant,
            RestaurantDto,
            Guid,
            ListRestaurantRequestDto,
            CreateUpdateRestaurantDto>,
        IRestaurantsAppService
    {
        private IDataFilter _dataFilter;

        public RestaurantsAppService(
            IRepository<Restaurant, Guid> repository ) : base(repository)
        {
            _dataFilter = dataFilter;
        }

        protected override async Task<IQueryable<Restaurant>> CreateFilteredQueryAsync(ListRestaurantRequestDto input)
        {
             Check.NotNull(input, nameof(input));
            using (_dataFilter.Disable<IMultiTenant>())
            {
                return await Repository
                    .GetQueryableAsync(); // filter logic is excluded here
            }
}
```
How can I disable the tenant filter here and do not override the Get and GetAll methods to add the IDataFilter.disable in both places?
Thanks

**Comment by maliming** [comment]
hi

`CreateFilteredQueryAsync` What is returned is `IQueryable`, which has not been queried yet.

**Comment by hitaspdotnet** [comment]
@mahdighorbanpour Do NOT disable it here, override methods you need or create once, 
```CSharp
public virtual async Task<List<RestaurantDto>> GetListAsync(ListRestaurantRequestDto input)
{
     Check.NotNull(input, nameof(input));
     using (_dataFilter.Disable<IMultiTenant>())
     {
         return ObjectMapper.Map<Restaurant, RestaurantDto>(await Repository.GetListAsync())
     }
}
```

**Comment by mahdighorbanpour** [comment]
@hitaspdotnet Thanks, I am doing exactly like that tight now. I was looking for a way to disable it for this service/repository somehow
