### ISSUE TITLE
Replace System.Drawing with ImageSharp in Blogging module

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#10081]
We are using `System.Drawing` library to validate images for Blog Module. See the reference -> [https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.Application/Volo.Blogging.Application.csproj#L14](https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.Application/Volo.Blogging.Application.csproj#L14)

After .NET6 Microsoft announces that  `System.Drawing`  library is being obsolete for non-Windows OS. See [https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=net-5.0#remarks](https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=net-5.0#remarks)

![](https://user-images.githubusercontent.com/9526587/134005864-b3b381a1-cd6e-477c-9dbf-3ae24dcd98ed.png)

We'll replace `System.Drawing` with [https://github.com/SixLabors/ImageSharp](https://github.com/SixLabors/ImageSharp) as suggested in the Microsoft remarks.

**Comment by leonkosak** [comment]
Interesting articles

https://devblogs.microsoft.com/dotnet/net-core-image-processing/
https://photosauce.net/blog/post/5-reasons-you-should-stop-using-systemdrawing-from-aspnet
