### ISSUE TITLE
How to deal with distrubuted transactions?

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#1009]
Considering a situation that service A calls service B and service C in a function, but service C throw an exception, so service A and service B should perform fallback action. But I can not find any documents or codes in ABP that handles this?

**Comment by hikalkan** [comment]
If C throws exception, B gets this exception and throws exception, then A get exception and throws it and rollbacks all transactions.

But this does not solve all issues. Assume that Service C and B run successfully, then A throws exception, it can not rollback B & C.

ABP does not offer a built-in solution for this problem. You can look for Saga, 2 phase commit or other patterns for your application.
