### ISSUE TITLE
Database migration problem in ASP.NET Core MVC Tutorial 

### ISSUE THREAD

**Issue by Webdiyer** [abpframework/abp#1010]
If you add Book entity to the BookStoreDbContext  without config it in the ConfigureBookStore method, run add-migration command against Acme.BookStore.EntityFrameworkCore.DbMigrations project will generate empty up and down methods because BookStoreMigrationsDbContext doesn't know that the new entity has been added to the DBContext.

**Comment by hikalkan** [comment]
You are right. Your solution is good for now. Thanks.
