### ISSUE TITLE
Module template have the necessary files for containerization, but they seem outdated

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#10103]
Related question: https://stackoverflow.com/questions/69281531/running-docker-with-abp-module-template-issue

Here is an example:
https://github.com/abpframework/abp/blob/aac65e9ff95249b7f82647a38cd0193af41497f9/templates/module/aspnet-core/host/MyCompanyName.MyProjectName.IdentityServer/Dockerfile#L1

**Comment by gterdem** [comment]
This is resolved.
