### ISSUE TITLE
abp angular and backend with ipAdress deploy to iis

### ISSUE THREAD

**Issue by elhanda** [abpframework/abp#10116]
hi all  i got this error when i try to publish 
here my appsettings.json
![image](https://user-images.githubusercontent.com/56455161/134472490-c381ab2a-cb56-47d3-a688-947e6ca128b3.png)
and my launch Setting 
![image](https://user-images.githubusercontent.com/56455161/134474193-48f5cbeb-81a7-47f3-84e1-832c38c07742.png)
and angular here my environment
![image](https://user-images.githubusercontent.com/56455161/134472669-c144349f-c3e7-42b5-b911-3ab62f6b5834.png)

when i publish the backend in iis windows server i works fine swagger calls api 
but when i publish the frontend  and click on login button this happened
![image](https://user-images.githubusercontent.com/56455161/134472983-e60a3506-1e49-44d5-8163-0afbc5b2824e.png)
![image](https://user-images.githubusercontent.com/56455161/134474524-77230388-9161-4107-9667-c3d64434d138.png)

and when i modify the url to 
https://192.168.11.101:44311/account/login
login page appeared but no respond 
works fine angular calling api  with localhost from the server backend but changing the ipAdresse error 
in another project i got this error (The required antiforgery header value "RequestVerificationToken" is not present)

please can anyone help me

**Comment by gterdem** [comment]
You are missing **redirect uri for your angular client**. 

Check the database if your **angular client** (AtlasNetWebProject_App) has the **same redirect uri** in environment.ts file  (https://192.168.11.101:4200) in `IdentityServerClientRedirectUri` table as well.

Also share related **identityserver logs** for better diagnose instead of screenshots please.

**Comment by elhanda** [comment]
![image](https://user-images.githubusercontent.com/56455161/134734036-525ea35e-7e1d-48f0-8644-a8db00fcd477.png)

**Comment by elhanda** [comment]
i  update the url and re-create the database  and add the   AbpAntiForgeryOptions  changed the AutoValidate into false from the documentation  https://docs.abp.io/en/abp/3.3/CSRF-Anti-Forgery
and it works thanks
thanks
