### ISSUE TITLE
CLI: abp build suggestion

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#10110]
1. If DependingRepositories has owned abp-build-config.json use it as depended repository's configuration
2. If working directory has abp-build-config.json use it instead of solution OR an option to choice build configuration

**Comment by ismcagdas** [comment]
@hitaspdotnet we started to use `dotnet build` with its /graphBuild parameter and will remove abp build command for the future. Do you use abp build in a case where dotnet build doesn't work well ?

Thanks,

**Comment by hitaspdotnet** [comment]
@ismcagdas abp build has some feature for build faster I like them, depended repos and ignore unwanted directories in build pipe.
We can merge them  to make a wonderful build helper.
