### ISSUE TITLE
how to show ef core sql string in debugger?

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#1012]
public static readonly Microsoft.Extensions.Logging.LoggerFactory _myLoggerFactory =
        new LoggerFactory(new[] {
        new Microsoft.Extensions.Logging.Debug.DebugLoggerProvider()
        });           

 context.Services.PreConfigure<DbContextOptionsBuilder>(o =>
            {
                o.EnableDetailedErrors(true);
                o.EnableSensitiveDataLogging(true);
                o.UseLoggerFactory(_myLoggerFactory);
            });

not work

**Comment by maliming** [comment]
Try adding a code similar to the following when configuring the database.

https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging

```
Configure<AbpDbContextOptions>(options =>
{
	options.Configure(context =>
	{
		context.DbContextOptions.UseLoggerFactory(new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) }));
		context.DbContextOptions.EnableDetailedErrors();
		context.DbContextOptions.EnableSensitiveDataLogging();
		
		//...
	});
	
	//...
});

```

**Comment by BigerXie** [comment]
> Try adding a code similar to the following when configuring the database.
> 
> https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging
> 
> ```
> Configure<AbpDbContextOptions>(options =>
> {
> 	options.Configure(context =>
> 	{
> 		context.DbContextOptions.UseLoggerFactory(new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) }));
> 		context.DbContextOptions.EnableDetailedErrors();
> 		context.DbContextOptions.EnableSensitiveDataLogging();
> 		
> 		//...
> 	});
> 	
> 	//...
> });
> ```

Hi Liming, this code is not working for ABP8.0, can you help me with another code for 8.0?
