### ISSUE TITLE
Should TruncateFromBeginning be renamed to TruncateFromEnd?

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#1014]
https://github.com/abpframework/abp/blob/2a784037f51b352ab784008703292370500db995/framework/src/Volo.Abp.Core/System/AbpStringExtensions.cs#L384

**Comment by hikalkan** [comment]
No it is true because it deletes from the beginning.

**Comment by ebicoglu** [comment]
so the description seems wrong

> /// Gets a substring of a string from Ending of the string if it exceeds maximum length

**Comment by hikalkan** [comment]
>Gets a substring of a string from Ending of the string if it exceeds maximum length

This is true :)

"this is a demo text".TruncateFromBeginning(8) returns "emo text". It deleted (truncated) from beginning and returned the substring from the ending :)
