### ISSUE TITLE
ABP Suite does not generate nullable bool 

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#10155]
Using ABP Suite - Version 4.4.2 Angular MongoDb

When generating a new entity that has bool-fields the Angular template get an error when creating a new instance:
![image](https://user-images.githubusercontent.com/1492596/134920836-dcabc606-5d0e-47b7-82bf-96cd6fda5eeb.png)

The issue is that a bool field cannot be defined as nullable in ABP suite so the create-form cannot be posted if the checkbox for the bool-field is not checked.

Adjusting so that the bool is nullable in the EntityCreateDto fixes the issue.

When a DateTime-field is created there is a checkbox to make it nullable, adding that option for bool-fields also could be a solution.

**Comment by martenw** [comment]
Does the issue becoming stale mean it won't be fixed?

**Comment by ebicoglu** [comment]
commercial support is not available in open-source repository. pls create a new question on the commercial support of abp.io

**Comment by martenw** [comment]
@ebicoglu but shouldn't bugs be reported here on github? Or should bugs on commercial be submitted in the support forum?

**Comment by martenw** [comment]
Moved to support https://support.abp.io/QA/Questions/2202/Bool-fields-generated-by-abp-suite-cannot-be-saved-in-angular-template
