### ISSUE TITLE
Support for external identity providers such as Azure AD, Azure AD B2C, Okta, Auth0 etc

### ISSUE THREAD

**Issue by jimitndiaye** [abpframework/abp#10165]
Please describe the feature need!

As described in the title, it would be great if we could switch from the default identityserver shipped with ABP to using existing cloud identity providers such as those named above. Maybe coupling an OpenID client with some rudimentary but extensible UI components.

**Comment by maliming** [comment]
It is supported by default. You only need to add an external identity provider.
https://identityserver4.readthedocs.io/en/latest/topics/signin_external_providers.html

**Comment by 274188A** [comment]
there are some Community Articles (may be slightly dated):

- [https://community.abp.io/articles/implementing-passwordless-authentication-with-asp.net-core-identity-c25l8koj](https://community.abp.io/articles/implementing-passwordless-authentication-with-asp.net-core-identity-c25l8koj)
- [https://community.abp.io/articles/how-to-use-the-azure-active-directory-authentication-for-mvc-razor-page-applications-4603b9cf](https://community.abp.io/articles/how-to-use-the-azure-active-directory-authentication-for-mvc-razor-page-applications-4603b9cf)
