### ISSUE TITLE
ABP Suite generation of nullable Guid

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#10161]
Version 4.4.2/Angular/MongoDB

As with #10155 this issue is related to how ABP Suite generate fields.

I have a navigation property pointing to another entity with Guid-id, the navigation property is nullable. Setting the property value works fine but if I later remove the value I get the error below.

![image](https://user-images.githubusercontent.com/1492596/135063739-98ade7c6-3a36-49c7-bb8d-125734ca4567.png)

Reason is that on create the field is initialized as null but on removing the link the value is set to empty string that cannot be parsed when posted to the API.

I am currently using the workaround below in my Angular components submitform method, possibly there is a better way to solve this:

```
  submitForm() {
    if (this.form.invalid) return;

    this.form.value.myGuidNavigationProperty = this.form.value.myGuidNavigationProperty ? this.form.value.myGuidNavigationProperty : null;

   ...
```

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/10155#issuecomment-981351189

**Comment by martenw** [comment]
Issue moved to support https://support.abp.io/QA/Questions/2203/Navigation-property-generated-by-abp-suite-cannot-be-saved-in-angular-template
