### ISSUE TITLE
Use abp-form-content  Localiztion enum booktype  to zh-han

### ISSUE THREAD

**Issue by zhangtingwz** [abpframework/abp#10167]
nice to meet you
i am a student
when i use abp-form-content to show model
![Inked捕获_LI](https://user-images.githubusercontent.com/26179617/135218914-cdaeb034-97b7-41a1-ac61-35e0a4e73109.jpg)
 
booktype is all english ，i want it to chinese ，how to do 

this is my zh-Hans.json
![捕获](https://user-images.githubusercontent.com/26179617/135219147-651d6458-661c-49ca-bcf4-246321c6d171.PNG)

**Comment by maliming** [comment]
Please share some code.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Form/AbpSelectTagHelperService.cs#L274

**Comment by enisn** [comment]
> https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Form/AbpSelectTagHelperService.cs#L274

@zhangtingwz you have to use enum name instead of value
