### ISSUE TITLE
One dbcontext to one database, but throw dependency injection expcetion

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#10175]
Hi, there
I followed official docs [Entity-Framework-Core-Migrations](https://docs.abp.io/en/abp/master/Entity-Framework-Core-Migrations) and I registered all dbcontexts in EntityFrameworkCoreModule.
All IRepository<T> throw same exception.
* Your **ABP Framework version**.
4.4.2
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
angular
* Your database provider(EF Core/MongoDB)
EF Core
* Exception message and **stack trace** if available (check the logs).
An exception was thrown while activating Castle.Proxies.CompanyServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.CompanyServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'Castle.Proxies.CompanyServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`1[ZLBAdmin.Companies.Company] companyRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.Domain.Repositories.IRepository`1[ZLBAdmin.Companies.Company], Volo.Abp.Identity.IdentityUserManager, ZLBAdmin.Companies.CompanyManager, Microsoft.Extensions.Configuration.IConfiguration)'.

So, what steps I missed?
Thank-you

**Comment by acjh** [comment]
Did you add `DbSet` properties?

**Comment by trickyrat** [comment]
@acjh sorry for late reply, 
yes, I added required dbset propertity to each module.
I successfully add migration with efcore cli command
>  Add-Migration "Initial" -OutputDir "Migrations/xxxxDbMigrations" -Context xxxxDbContext  

so I don't think there is a problem in dbset properties.  
![屏幕截图 2021-09-30 091521](https://user-images.githubusercontent.com/19605145/135369636-8a23aaa1-21a6-47d9-84e9-0c8e003e0913.png)

**Comment by trickyrat** [comment]
Adding
```
Servvices.AddAbpDbContext<xxxDbContext>(options => 
{
options.AddDefaultRepositories(includeAllEntities: true);
});
```
when register dbcontext in EntityFrameworkCoreModule will fix this issue.
