### ISSUE TITLE
Define custom "per application" setting which is read after app start from DB using appservice. How? SettingDefinitionProvider does not fit here?

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#10174]
ABP 4.3.0 / Angular.

I need to define custom setting for application. In my case it's an _application version_ which is stored in _DB_ and changed manually after next deployment (accessible via _appservice_ method) and needs to be read once ONCE application start and be accessible from **Angular** client.

I can see `SettingDefinitionProvider` inherited class is adviced, where in `Define` method new settings are added. But it's a _transient_ class and besides, `Define` method is _sync_. How to implement my requirement properly? It needs to be something like:

```
public class Program
{
    public static async Task Main(string[] args)
    {
        IWebHost webHost = CreateWebHostBuilder(args).Build();

        // Create a new scope
        using (var scope = webHost.Services.CreateScope())
        {
            // Get the MyVersionAppService instance
            var myVersionAppService = scope.ServiceProvider.GetRequiredService<MyVersionAppService>();

            //Get app version asynchronously
            var actualVersion = await myVersionAppService.GetAppVersionAsync('MY_APP_NAME');

            //TODO: add 'actualVersion' into 'SettingDefinition' somehow...
        }

        // Run the WebHost, and start accepting requests
        // There's an async overload, so we may as well use it
        await webHost.RunAsync();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>();
}
```

**Comment by alexandis** [comment]
Seems like I can use it like that:

```
            try
            {
                Log.Information("Starting AbxEps.Fines.HttpApi.Host.");
                var host = CreateHostBuilder(args).Build();

                using var scope = host.Services.CreateScope();

                var configuration = scope.ServiceProvider.GetRequiredService<IConfiguration>();
                var versionRepository = scope.ServiceProvider.GetRequiredService<IVersionRepository>();
                var version = await versionRepository.GetAsync('MY_APP_NAME');
                configuration["app_version"] = version;

                await host.RunAsync();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly!");
            }
            finally
            {
                Log.CloseAndFlush();
            }
```

**Comment by cotur** [comment]
Hi,

Can you please check the documentation https://docs.abp.io/en/abp/latest/Settings

You don't need to make anything in the `Program.cs`

**Comment by alexandis** [comment]
@cotur Hi - I've already read this part. And that's why I expressed my doubt in the title: "**SettingDefinitionProvider does not fit here?**"
I doubt because:
1) it is not clear when `SettingDefinitionProvider` comes into game. I need to make sure everything happens ONCE on application start;
2) `Define` method is SYNC, as I mentioned. And I need to call the _appservice_ or _repository_ method which is ASYNC. I don't want to wait till _DB_ request finishes.
