### ISSUE TITLE
New Blazor WebAssembly Project returns blank page in browser

### ISSUE THREAD

**Issue by gfo2007** [abpframework/abp#10181]
Hi,
I just created a new Blazor WebAssembly project. When I run the .Blazor project to view the application in the browser, the page keeps loading without showing the login screen.

![abp framework error](https://user-images.githubusercontent.com/14317420/135421362-16c1a3a9-1ef4-4f5a-b7fe-1ee45a327513.PNG)

Please help.

Regards.

**Comment by DonVliet** [comment]
Make sure you have your **.HttpApi.Host** project running first. You should be able to see the Swagger UI page.

**Comment by gfo2007** [comment]
@DonVliet the .HttpApi.Host project runs without a problem. It is the .Blazor project is what displays a blank screen.

**Comment by DonVliet** [comment]
Open the developer tools (F10) and check if you are you getting errors in the Console?

You might also want to add the following to your **appsettings.development.json** file in the Blazor project to receive more detailed errors:

{
  "DetailedErrors": true
}

**Comment by gfo2007** [comment]
@DonVliet below are the console errors.

![abp console error](https://user-images.githubusercontent.com/14317420/135468597-8aec22a9-5b6a-4244-b0b8-7becf7bf38d3.PNG)

**Comment by gfo2007** [comment]
I realized the host project needed to be running before I can the Blazor project.

It's working now. Thanks
