### ISSUE TITLE
Improve email verification routine

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#10192]
When email verification is activated, users see the following page after clicking register button
![image](https://user-images.githubusercontent.com/31216880/135467111-319a2e0f-8e8d-4585-96a2-11876c286309.png)

Replace this page with this:
Email sent icon => https://uxwing.com/email-mail-sent-icon/
![image](https://user-images.githubusercontent.com/9526587/135471119-9110d97b-9602-43e0-b9c2-641738ac801d.png)

```
A verification email has been sent to your email address.
You will need to click the activation link to complete your registration.
If you do not receive your email within 5 minutes, please try these options:

 -  Check your other folders, including spam and junk folder
 -  Resend activation link
```

---

This is the email verification link. We need to add `returnUrl` to this link. And developer should be able to add a returnUrl to this link. This is important because there is generally an ongoing operation before the register/verification step. For example, user adds items to the shopping basket. Clicks purchase button, and register screen comes up, makes registration but email verification email is sent, opens the email and clicks the link but the website redirects to the login screen back. This is not a wanted case. The user should redirect to the `returnUrl`  and **he must be logged in**. No need to login again.

https://localhost:44333/Account/EmailConfirmation?userId=a35389e3-0aae-eaf1-dd4a-39ff4920afa1&__tenant=&confirmationToken=CfDJ8EK%2FmMkJNnFEsDCeZhTrIBPpCokjP5FQO2U5w5%2B2ZrtFQh8Kl%2By0r77lhfwjn3uE7lk8weAryayKs1IgdqjJM8Pes%2B3yFU9p3HtougImX%2BekHYJjDte3dBearpgMZpt96BkS9PXsOG1nOTOB2WAaY6DCnGQ7I9HPaeUnJXYpMA0VEgo4FV5e29uf%2BhfhDVs2EeMEnK8kcQYsgpvren0VkMqADJQD9h0TJzujCgluEWPRDrXjJXLe8cUoEnqSOfkhKQ%3D%3D

---

this is the email verification success page.
change this page and when user clicks CONTINUE button it should redirect to the `returnUrl`
![image](https://user-images.githubusercontent.com/9526587/135472625-5e9604f7-f4bb-4fa1-898e-b39b9f0360b0.png)

**Comment by ebicoglu** [comment]
I think the related page is https://github.com/volosoft/volo/blob/dev/abp/account/src/Volo.Abp.Account.Pro.Public.Web/Pages/Account/ConfirmUser.cshtml

**Comment by ebicoglu** [comment]
moved to https://github.com/volosoft/volo/issues/8399

**Comment by sturlath** [comment]
Hi @ebicoglu was this implemented? What I need is displaying a "check your junk email" message after registering a tenant since some are hitting that problem of their emails ending in the junk...

**Comment by sturlath** [comment]
@ebicoglu ? Just checking on this again.

**Comment by sturlath** [comment]
@ebicoglu was this ever worked on? And if not why? This UI needs update, its way to basic/simple. Just "Check your junk mail " would be an improvement.

**Comment by sturlath** [comment]
@ebicoglu @EngincanV do I have to do something special to get this "check your junk email" for the validation email?
