### ISSUE TITLE
Automate the Second Database Schema Migration may not work

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#10209]
ABP Framework version: 4.4.0
Database provider: EF Core

I try to move ABP* and IdentityServer* to another database, but the DbMigrator don't work.

1. Follow the doc => [create-a-second-dbcontext](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#create-a-second-dbcontext) 
`Add-Migration "Initial" -OutputDir "SecondDbMigrations" -Context BookStoreSecondDbContext`

2. And this doc => [automate-the-second-database-schema-migration](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#automate-the-second-database-schema-migration) 
Then run the DbMigrator, will do nothing about "SecondDbMigrations".

3. Found that PlmAPIDbMigrationService.MigrationsFolderExists will check folder "Migrations".
`return Directory.Exists(Path.Combine(dbMigrationsProjectFolder, "Migrations"));`

4. Must to add migrations to the "Migrations" folder, so the output path like "Migrations\SecondDb".
`dotnet ef migrations add 'Initial' -c BookStoreSecondDbContext -o Migrations\SecondDb`

Then it work, suggest do something to the offical doc for more infomation about this, thanks.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp-samples/tree/master/EfCoreMigrationDemo

**Comment by jakeuj** [comment]
> See https://github.com/abpframework/abp-samples/tree/master/EfCoreMigrationDemo

The demo already have a Migrations folder, so it work.

When someone want to move all (abp & is4) entity to second Db first, then start coding.

In this moment, BookStore.EntityFrameworkCore only has SecondDbMigrations folder.

Migration will not work when BookStore.EntityFrameworkCore.Migrations not exist yet.
