### ISSUE TITLE
Integration Syncfusion MVC Razor Components with ABP Framework

### ISSUE THREAD

**Issue by gfo2007** [abpframework/abp#10206]
Hi,
Does anyone know how syncfusion asp.net core mvc components can be integrated into an abp application using razor pages? I have seen the article on Blazor but I am looking for one on Razor pages.

Regards,

**Comment by maliming** [comment]
Did you get any problems and errors during the integration it?

**Comment by gfo2007** [comment]
@maliming,
I am not sure the best way out. For instance Syncfusion documentation asks for Views/_Layout.cshtml which is not present in AbpFramework pages.

It also appears syncfusion may not need the apb bootstrap helpers like <abp-card>, etc. 
I am not sure how to pass the data from the application service to syncfusion components and vice versa.

I am now learning abp framework with the tutorial.

Any help or code snippet will be appreciated.

Regards,

**Comment by ebicoglu** [comment]
it's asking to add the JavaScript imports I think.
See https://medium.com/volosoft/how-to-add-a-new-javascript-library-to-your-abp-project-62b21545f4cc
