### ISSUE TITLE
Question: Can Dynamic C# API Client Proxies be used in a separate solution?

### ISSUE THREAD

**Issue by pagner** [abpframework/abp#10224]
I have read the documentation of Dynamic C# API Client Proxies but it seems the client needs to be in the same solution in order to share the interfaces and find the assembly. Is this correct?

Can this be used from a different solution or is this not the intention? I was under the impression this would work like the typescript swagger tool chain proxy generator in the old abp framework.

If not I will use this nice example: https://github.com/bartvanhoey/AbpAddCustomClaimToAccessToken

Thanks in advance!

**Comment by gterdem** [comment]
Yes, you can **project reference** from a different solution (though visual studio won't be able to build it afaik, so you will need to use `dotnet build /graphBuild`).
Or you can host on a nuget server and use as **package reference**.

**Comment by pagner** [comment]
@gterdem Thanks for your reply. 

Neither of those scenarios is going to work for me. My client app is a UI application so I need to be able to debug. The second suggestion becomes a maintenance issue.

For what I am trying to achieve here, I think I will use @bartvanhoey example. It's clean and to the point.
