### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by AlismVY** [abpframework/abp#10243]
How to build a Docker that keeps telling you you can't find the file

**Comment by maliming** [comment]
hi

This is nothing to do with ABP.

**Comment by AlismVY** [comment]
Can you provide me with a reference, I can't find information about abp packaging docker， Thank you.

**Comment by gterdem** [comment]
> Can you provide me with a reference, I can't find information about abp packaging docker， Thank you.

You can check this community article: https://community.abp.io/articles/deploy-abp-framework-dotnet-core-tiered-app-to-docker-swarm-kcrjbjec
I don't know exactly what error you get but it is probably related with dockerizing default .net application. You can also refer to [official docs](https://docs.docker.com/samples/dotnetcore/).

**Comment by AlismVY** [comment]
Thank you very much
