### ISSUE TITLE
It now take ages to wait till application configuration is read for Angular app

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#10266]
**4.3.0 / Angular / Separate Identity Server**

I can't figure it out what's going on... But it takes now ages to wait till **Angular** app brings a _login_ page. For some reason, accessing _application configuration_ is stuck for 5-10 minutes!

![image](https://user-images.githubusercontent.com/6149843/136382668-fedc83f0-dfdb-416e-b26e-a5fe53bb1ed8.png)

We don't use **Redis**. So what could be the problem? What log or module configuration would you like to see?

**Comment by maliming** [comment]
Can you check the logs to see time-consuming operations?

**Comment by alexandis** [comment]
This time it was slightly faster, but still very slow. Here what drags my attention:

> [17:05:56 INF] Executing endpoint 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc)'
> [17:05:56 INF] Route matched with {area = "abp", action = "Get", controller = "AbpApplicationConfiguration", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto] GetAsync() on controller Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController (Volo.Abp.AspNetCore.Mvc).
> [17:05:56 DBG] Executing AbpApplicationConfigurationAppService.GetAsync()...

Then I see just ENORMOUS amount of queries to `AbpLanguages` like that:

> info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
>       Entity Framework Core 5.0.5 initialized 'FeatureManagementDbContext' using provider 'Oracle.EntityFrameworkCore' with options: SensitiveDataLoggingEnabled QuerySplittingBehavior=SplitQuery 
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (41ms) [Parameters=[:providerName_0='T' (Size = 64), :providerKey_1='dad16b71-09d3-4b10-ea39-39fe513e7216' (Size = 64)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.Name, a.ProviderKey, a.ProviderName, a.Value
>       FROM AbpFeatureValues a
>       WHERE ((a.ProviderName = :providerName_0) AND (a.ProviderKey = :providerKey_1))
> info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
>       Entity Framework Core 5.0.5 initialized 'LanguageManagementDbContext' using provider 'Oracle.EntityFrameworkCore' with options: SensitiveDataLoggingEnabled QuerySplittingBehavior=SplitQuery 
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (48ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :AuOWajiLK_0='True' (DbType = Byte)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.ConcurrencyStamp, a.CreationTime, a.CreatorId, a.CultureName, a.DeleterId, a.DeletionTime, a.DisplayName, a.ExtraProperties, a.FlagIcon, a.IsDeleted, a.IsEnabled, a.LastModificationTime, a.LastModifierId, a.UiCultureName
>       FROM AbpLanguages a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.IsDeleted = 0))) AND (a.IsEnabled = :AuOWajiLK_0))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (46ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='AbpIdentity' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (42ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='AbpAccount' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (46ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='LanguageManagement' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (42ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='TextTemplateManagement' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (46ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='AbpSettingManagement' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (41ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='AbpIdentityServer' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (41ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='AbpAuditLogging' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))
> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (90ms) [Parameters=[:ef_filter__p_0='False' (DbType = Byte), :i9kSZOyZR_0='CentralTools' (Size = 128), :I9ys2Nd0Y_1='en' (Size = 10)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.CreationTime, a.CreatorId, a.CultureName, a.LastModificationTime, a.LastModifierId, a.Name, a.ResourceName, a.TenantId, a.Value
>       FROM AbpLanguageTexts a
>       WHERE ((((:ef_filter__p_0 <> 0) OR (a.TenantId IS NULL))) AND (((a.ResourceName = :i9kSZOyZR_0) AND (a.CultureName = :I9ys2Nd0Y_1))))

And then:

> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (42ms) [Parameters=[:providerName_1='G' (Size = 64)], CommandType='Text', CommandTimeout='0']
>       SELECT a.Id, a.Name, a.ProviderKey, a.ProviderName, a.Value
>       FROM AbpSettings a
>       WHERE ((((a.Name IN (N'Abp.Localization.DefaultLanguage', N'Abp.Timing.TimeZone', N'AbxEps.CT.EpsilonTheme.Layout.Boxed', N'AbxEps.CT.EpsilonTheme.Layout.MenuStatus', N'AbxEps.CT.EpsilonTheme.Style', N'Abp.Identity.Password.RequiredLength', N'Abp.Identity.Password.RequiredUniqueChars', N'Abp.Identity.Password.RequireNonAlphanumeric', N'Abp.Identity.Password.RequireLowercase', N'Abp.Identity.Password.RequireUppercase', N'Abp.Identity.Password.RequireDigit', N'Abp.Identity.Lockout.AllowedForNewUsers', N'Abp.Identity.Lockout.LockoutDuration', N'Abp.Identity.Lockout.MaxFailedAccessAttempts', N'Abp.Identity.SignIn.RequireConfirmedEmail', N'Abp.Identity.SignIn.EnablePhoneNumberConfirmation', N'Abp.Identity.SignIn.RequireConfirmedPhoneNumber', N'Abp.Identity.User.IsUserNameUpdateEnabled', N'Abp.Identity.User.IsEmailUpdateEnabled', N'Abp.Identity.OrganizationUnit.MaxUserMembershipCount', N'Abp.Identity.TwoFactor.Behaviour', N'Abp.Identity.TwoFactor.UsersCanChange', N'Abp.Account.IsSelfRegistrationEnabled', N'Abp.Account.EnableLocalLogin', N'Abp.Account.TwoFactorLogin.IsRememberBrowserEnabled', N'Abp.Account.EnableLdapLogin', N'Abp.Account.Captcha.UseCaptchaOnLogin', N'Abp.Account.Captcha.UseCaptchaOnRegistration', N'Abp.Account.Captcha.VerifyBaseUrl', N'Abp.Account.Captcha.SiteKey', N'Abp.Account.Captcha.Version', N'Abp.Account.Captcha.Score', N'Abp.Account.ProfilePictureSource', N'App.Version')) AND (a.ProviderName = :providerName_1))) AND (a.ProviderKey IS NULL))
> [17:07:28 DBG] Executed AbpApplicationConfigurationAppService.GetAsync().
> [17:07:28 DBG] Added 0 entity changes to the current audit log
> [17:07:28 DBG] Added 0 entity changes to the current audit log
> [17:07:28 DBG] Added 0 entity changes to the current audit log
> [17:07:28 INF] Executing ObjectResult, writing value of type 'Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto'.

> [17:07:28 INF] Executed action Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc) in **92584.762ms**

- 1.5 mins to retrieve _application configuration_?

**Comment by maliming** [comment]
Can you share the full logs of the request?

**Comment by alexandis** [comment]
Hi. I made a fresh start and here are the logs from [IdentityServer](https://1drv.ms/u/s!AhWdpZddvifTty36oktELPl4JI1-?e=72oUXK) (just in case) and [HttpApi.Host](https://1drv.ms/u/s!AhWdpZddvifTty7Qaus_-pyMNjZN?e=elim6V).

**Comment by maliming** [comment]
The log is incomplete.

```cs
2021-10-08 08:28:32.028 +03:00 [DBG] Executing AbpApplicationConfigurationAppService.GetAsync()...
2021-10-08 08:32:00.730 +03:00 [DBG] Executed AbpApplicationConfigurationAppService.GetAsync().
```

**Comment by alexandis** [comment]
> The log is incomplete.
> 
> ```cs
> 2021-10-08 08:28:32.028 +03:00 [DBG] Executing AbpApplicationConfigurationAppService.GetAsync()...
> 2021-10-08 08:32:00.730 +03:00 [DBG] Executed AbpApplicationConfigurationAppService.GetAsync().
> ```

I don't know why - it's all I have. Don't have idea why there's a gap between those lines, but seems like this is exactly where a lot of time is wasted. What is supposed to be between those two actions? How do I track it? Will a more detailed log level set in _Program_ help?

**Comment by alexandis** [comment]
UPDATE: please see verbose log from [HttpApi.Host](https://1drv.ms/u/s!AhWdpZddvifTty8Q8ugLMgTgVdX3?e=Y4BqHn). Does it shed more light on the issue?
I run another host and the same issue again - I can see there is nothing in the log that could bring the details what is happening in this gap. Any ideas? Probably another log could be initiated somewhere? What is supposed to be running in this gap according to ABP workflow?

> 2021-10-08 13:04:50.847 +03:00 [DBG] Getting not cache granted permissions from the repository for this provider name,key: C,Fines_App
> 2021-10-08 13:04:50.931 +03:00 [DBG] Setting the cache items. Count: 2
> **2021-10-08 13:04:50.931 +03:00 [DBG] Finished setting the cache items. Count: 2**
> **2021-10-08 13:06:11.286 +03:00 [DBG] HttpMessageHandler expired after 120000ms for client** 'IdentityServer:BackChannelLogoutClient'
> 2021-10-08 13:06:21.309 +03:00 [DBG] Starting HttpMessageHandler cleanup cycle with 1 items
> 2021-10-08 13:06:21.312 +03:00 [DBG] Ending HttpMessageHandler cleanup cycle after 0.0748ms - processed: 0 items - remaining: 1 items
> 2021-10-08 13:06:31.323 +03:00 [DBG] Starting HttpMessageHandler cleanup cycle with 1 items
> 2021-10-08 13:06:31.323 +03:00 [DBG] Ending HttpMessageHandler cleanup cycle after 0.0067ms - processed: 0 items - remaining: 1 items
> 2021-10-08 13:06:37.207 +03:00 [DBG] Executed AbpApplicationConfigurationAppService.GetAsync().

**Comment by alexandis** [comment]
Weird, but solution clean and rebuild resolved the issue. I still don't know what was that.

**Comment by alexandis** [comment]
Next recompile of the solution (after small change in one of the projects) got the issue back:

> 2021-10-08 13:06:37.207 +03:00 [INF] Executed action method Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController.GetAsync (Volo.Abp.AspNetCore.Mvc), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 107184.508ms.

**Comment by maliming** [comment]
Can you try another computer/environment?

**Comment by alexandis** [comment]
> Can you try another computer/environment?

I have only one authorized office notebook to work with our projects. So I can't check on other computer. Configuration is powerful, so it's not some kind of performance thing. My colleagues say they don't have this issue. They use the same repository and the same connection to our _Azure_ database. Though, I'd like to find the route of the problem. When I use **SQL Developer** to connect to the DB and execute queries - it's fast as well.

**Comment by maliming** [comment]
No one has reported the same problem yet.

**Comment by alexandis** [comment]
> No one has reported the same problem yet.

Well, so I'm the first :)

Could it have something to do with VS 2022 Preview installed in parallel? I have the described issue when running from both VS 2019 and 2022 Preview...

**Comment by maliming** [comment]
I'm not sure.

**Comment by alexandis** [comment]
Looks like I have found the root of the problem. When I make pause in VS watching application-configuration extraction, I fall into `AddToLanguageDictionary` method execution inside the class written by someone in our team to - obviously support 'per-tenant' resource handling. I don't know why I am the only one having issue with this method performance, but maybe you would suggest a better approach?

```
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IDynamicResourceLocalizer))]
    public class TenantIndependentResourceLocalizer : DynamicResourceLocalizer
    {
        public TenantIndependentResourceLocalizer(
            IServiceScopeFactory serviceScopeFactory,
            IDistributedCache<LanguageTextCacheItem> cache)
            : base(serviceScopeFactory, cache)
        {

        }
        protected override LanguageTextCacheItem CreateCacheItem(LocalizationResource resource, string cultureName)
        {
            var cacheItem = new LanguageTextCacheItem();

            using (var scope = ServiceScopeFactory.CreateScope())
            {
                var currentTenant = scope.ServiceProvider.GetRequiredService<ICurrentTenant>();

                if (currentTenant == null || !currentTenant.IsAvailable)
                    return base.CreateCacheItem(resource, cultureName);

                using (currentTenant.Change(null))
                {

                    var service = scope.ServiceProvider
                        .GetRequiredService<ILanguageTextRepository>();

                    List<LanguageText> texts = AddToLanguageDictionary("AbpIdentity", cultureName, cacheItem, service);
                    texts.AddRange(AddToLanguageDictionary("AbpAccount", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("LanguageManagement", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("TextTemplateManagement", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpSettingManagement", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpIdentityServer", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpAuditLogging", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("CentralTools", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("CentralTools:CommonUI", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("Fines", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("Batches", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("ListSpool", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpUi", cultureName, cacheItem, service));

                    texts.AddRange(AddToLanguageDictionary("AbpLocalization", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpTiming", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpAuthorization", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpValidation", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpExceptionHandling", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpFeatureManagement", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpFeature", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpPermissionManagement", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("Saas", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("TextTemplateManagement", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("EpsilonThemeManagement", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("BlobStoringDatabase", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AuditLog", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("Core", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("Fines:CommonUI", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpDddApplicationContracts", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpGlobalFeature", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpLdap", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpEmailing", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpUiNavigation", cultureName, cacheItem, service));
                    texts.AddRange(AddToLanguageDictionary("AbpUiMultiTenancy", cultureName, cacheItem, service));


                }
            }

            return cacheItem;
        }

        private List<LanguageText> AddToLanguageDictionary(string resourceName, string cultureName, LanguageTextCacheItem cacheItem, ILanguageTextRepository service)
        {
            var texts = service.GetList(resourceName, cultureName);

            foreach (var text in texts)
            {
                cacheItem.Dictionary[text.Name] = text.Value;
            }

            return texts;
        }
    }
```

**Comment by alexandis** [comment]
I have found the route cause. The method below (the approach was suggested by you here: [Is there a way to bypass Tenant for Translations?](https://support.abp.io/QA/Questions/1642/Is-there-a-way-to-bypass-Tenant-for-Translations)).

Our colleague implemented the method, but for some reason I am the only one experiencing the performance issue with it (when I see pending application-configuration request running VS in debug mode - I pause VS and it gets me into `foreach` _loop_ of `AddToLanguageDictionary`). When I comment this class - everything works fast. Do you have suggestion how to change the method to resolve my issue?

```
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IDynamicResourceLocalizer))]
    public class TenantIndependentResourceLocalizer : DynamicResourceLocalizer
    {
        public TenantIndependentResourceLocalizer(
            IServiceScopeFactory serviceScopeFactory,
            IDistributedCache<LanguageTextCacheItem> cache)
            : base(serviceScopeFactory, cache)
        {
        }

        protected override LanguageTextCacheItem CreateCacheItem(LocalizationResource resource, string cultureName)
        {
            var cacheItem = new LanguageTextCacheItem();

            using (var scope = ServiceScopeFactory.CreateScope())
            {
                var currentTenant = scope.ServiceProvider.GetRequiredService<ICurrentTenant>();

                if (currentTenant == null || !currentTenant.IsAvailable)
                    return base.CreateCacheItem(resource, cultureName);

                using (currentTenant.Change(null))
                {
                    var service = scope.ServiceProvider.GetRequiredService<ILanguageTextRepository>();

                    AddToLanguageDictionary("AbpIdentity", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpAccount", cultureName, cacheItem, service);
                    AddToLanguageDictionary("LanguageManagement", cultureName, cacheItem, service);
                    AddToLanguageDictionary("TextTemplateManagement", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpSettingManagement", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpIdentityServer", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpAuditLogging", cultureName, cacheItem, service);
                    AddToLanguageDictionary("CentralTools", cultureName, cacheItem, service);
                    AddToLanguageDictionary("CentralTools:CommonUI", cultureName, cacheItem, service);
                    AddToLanguageDictionary("Fines", cultureName, cacheItem, service);
                    AddToLanguageDictionary("Batches", cultureName, cacheItem, service);
                    AddToLanguageDictionary("ListSpool", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpUi", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpLocalization", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpTiming", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpAuthorization", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpValidation", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpExceptionHandling", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpFeatureManagement", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpFeature", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpPermissionManagement", cultureName, cacheItem, service);
                    AddToLanguageDictionary("Saas", cultureName, cacheItem, service);
                    AddToLanguageDictionary("TextTemplateManagement", cultureName, cacheItem, service);
                    AddToLanguageDictionary("EpsilonThemeManagement", cultureName, cacheItem, service);
                    AddToLanguageDictionary("BlobStoringDatabase", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AuditLog", cultureName, cacheItem, service);
                    AddToLanguageDictionary("Core", cultureName, cacheItem, service);
                    AddToLanguageDictionary("Fines:CommonUI", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpDddApplicationContracts", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpGlobalFeature", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpLdap", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpEmailing", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpUiNavigation", cultureName, cacheItem, service);
                    AddToLanguageDictionary("AbpUiMultiTenancy", cultureName, cacheItem, service);
                }
            }

            return cacheItem;
        }

        private void AddToLanguageDictionary(string resourceName, string cultureName, LanguageTextCacheItem cacheItem, ILanguageTextRepository service)
        {
            var texts = service.GetList(resourceName, cultureName);

            foreach (var text in texts)
            {
                cacheItem.Dictionary[text.Name] = text.Value;
            }
        }
    }
```
