### ISSUE TITLE
Is it right to use custom class which is in Domain.Shared Layer as output class(like DTO) in Application Service

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#10268]
* Your **ABP Framework version**. 4.3.3
A method in Manager Class in Domain Layer returns a custom class like below:

Domain.Shared :
```
public class SellerDashboardInfo
{
    public int TotalProductCount { get; set; }
    public decimal TotalPrice { get; set; }
    ...
}
```

Application Layer :
```
public virtual async Task<SellerDashboardInfo> GetSellerInfoAsync()
{
    return await sellerManager.GetSellerDashboardAsync();
}
```
It is not an entity. So should I generate DTO class or can I use it directly as DTO class in Application Layer?

Note: We can use `enums` which are in Domain.Shared as DTO class property type

**Comment by ebicoglu** [comment]
you can use DTO as input/output objects in your AppService.
see https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L54
