### ISSUE TITLE
Angular: AuthGuard unexpected behavior

### ISSUE THREAD

**Issue by pagner** [abpframework/abp#10278]
Although AuthGuard does it's job, it has a bit of quirky behavior.

If you are logged out and try to navigate to a page that is protected, the page will load half way and then redirect to the login page. This happens with the default abp modules and newly created modules with canActivate: [AuthGuard]

Expected Behavior:
Redirect to login page seamlessly without "flashing" the protected page.

To reproduce log out of the application and navigate to:
http://localhost:4200/account/manage

**Comment by mehmet-erim** [comment]
Hello @pagner

What is the `@abp/ng.core` package version? I can't reproduce it.
There was a problem as you described. But it was resolved 11 months ago.

**Comment by pagner** [comment]
I am using version "@abp/ng.core": "~4.4.2",

I should mention that I have overridden my UI Template using the documented methods.
https://docs.abp.io/en/abp/latest/UI/Angular/Component-Replacement

Could this be the problem?

Thanks

**Comment by mehmet-erim** [comment]
Check routing modules. You may have forgotten to add `canActive: [AuthGuard]`.

**Comment by pagner** [comment]
Nope, that's not it. I have canActivate: [AuthGuard] in both the
app-routing.module and the home-routing.module.

Initially I did not have it in the home-routing.module. I added it there as
well and it did not make a difference.

:-(

**Comment by mehmet-erim** [comment]
Still it cannot be reproduced. I'm closing this issue.
