### ISSUE TITLE
Swagger Authorize redirects from https to http 

### ISSUE THREAD

**Issue by andre-artus** [abpframework/abp#10289]
When I try to authorize/login from the Swagger page (https://[domain]/swagger/index.html) a new page opens 

**http**://[domain]/Account/Login?[etc.]

If I set my server to redirect `http` (port 80) to `https` (on port 443)  the login just loops (it succeeds, but ends up redirecting back to Login).

If I open `https://[domain]/Account/Login` in the browser I get the login page, I can log in, it appears to succeed, redirecting to the Swagger page, but the `Authorize` remains "unlocked" and when trying to execute a feature requiring authorization the result is:

```
{
  "error": {
    "code": "Volo.Authorization:010001",
    "message": "Authorization failed! Given policy has not granted.",
    "details": null,
    "data": {},
    "validationErrors": null
  }
}
```

Only the Antiforgery cookie is set.

I've checked every configuration file, but none of them have `http`, only `https`.

Nowhere in my code is a reference to `http`.

I'm using ABP 4.4.3 (stable).

**Comment by realLiangshiwei** [comment]
Check your app settings : https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Host/appsettings.json#L12

**Comment by andre-artus** [comment]
Thanks

**Comment by andre-artus** [comment]
> 
> 
> Check your app settings : https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Host/appsettings.json#L12

My appsettings.json does not have any entries with `http`, only `https`. I followed the link to "How to fix the Chrome login issue for the IdentityServer4" on the community hub, and decided to see if the issue persists on FireFox. In FF it seems to log in as expected but it does not log out properly, as it seems it does not clear out the necessary data (cookies). If I want to change the tenant I have to clear the cookies manually. Not sure if it also does it in Chrome (as I can not log in using it).

I'm going to see if the api otherwise works with other HTTP clients.


I'm not using IS4, I'm using the built in auth system.
