### ISSUE TITLE
[CmsKit bug] MenuItemPublicAppService return nothing after insert MenuItem datas

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#10288]
* Your **ABP Framework version**.
4.4.3
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
dont care
* Your database provider(EF Core/MongoDB)
dont care
* Exception message and **stack trace** if available (check the logs).
no Exception 
* Steps needed to **reproduce** the problem.
1.create a app-pro with public website(include cmskit module) by abp suite 
2.Create MenuItem by `TemplateName`.Web 
![image](https://user-images.githubusercontent.com/16490084/136890393-66393d25-387e-40eb-8b8e-3a7bd4d8c30e.png)
3. I cant see any MenuItems at `TemplateName`.Web.Public
![image](https://user-images.githubusercontent.com/16490084/136890413-5c11f98f-d8d3-4c37-bc08-070838ddf1a9.png)
4.After tracking source code ,  I think maybe some wrong with `DistributedCache` in `MenuItemPublicAppService`:
I try to replace it like below code comment,It will work fine
``` csharp
namespace Volo.CmsKit.Public.Menus
{
    [Volo.Abp.DependencyInjection.Dependency(ReplaceServices =true)]
    public class FSMenuItemPublicAppService : CmsKitPublicAppServiceBase, IMenuItemPublicAppService
    {
        protected IMenuItemRepository MenuItemRepository { get; }
        protected IDistributedCache<List<MenuItemDto>> DistributedCache { get; }

        public FSMenuItemPublicAppService(
            IMenuItemRepository menuRepository,
            IDistributedCache<List<MenuItemDto>> distributedCache)
        {
            MenuItemRepository = menuRepository;
            DistributedCache = distributedCache;
        }

        public async Task<List<MenuItemDto>> GetListAsync()
        {
            //var menuItems = await MenuItemRepository.GetListAsync();

            //if (menuItems == null)
            //{
            //    return new();
            //}

            //return ObjectMapper.Map<List<MenuItem>, List<MenuItemDto>>(menuItems);

         
            var cachedMenu = await DistributedCache.GetOrAddAsync(
                MenuApplicationConsts.MainMenuCacheKey,
                async () =>
                {
                    var menuItems = await MenuItemRepository.GetListAsync();

                    if (menuItems == null)
                    {
                        return new();
                    }

                    return ObjectMapper.Map<List<MenuItem>, List<MenuItemDto>>(menuItems);
                });

            return cachedMenu;
        }
    }
}
```
Does  missing some Redis config in  `TemplateName`.Web
Please help me to check it,thanks

**Comment by enisn** [comment]
Hi @yinchang0626 

Are you sure both projects are using the same Redis? 
Is Redis connection stable? 

If they use the same distributed cache, `Web` project invalidates menu cache after a change on MenuItems

**Comment by yinchang0626** [comment]
@enisn  Hi:
Thank you for reply.
As you say.I found the answer, 
The  app-pro ` template`  didn't  add `Redis` Module when add `cms-kit` module
So ,I think it will be better if the [document](https://github.com/abpframework/abp/blob/dev/docs/en/Modules/Cms-Kit/Menus.md) mentions it

1. Project `TemplateName.Web` need install `Volo.Abp.Caching.StackExchangeRedis` and `Microsoft.AspNetCore.DataProtection.StackExchangeRedis` packages

2. Modify `TemplateNameWebModule` 
```csharp
        private void ConfigureRedis(
            ServiceConfigurationContext context,
            IConfiguration configuration,
            IWebHostEnvironment hostingEnvironment)
        {
            if (!hostingEnvironment.IsDevelopment())
            {
                var redis = ConnectionMultiplexer.Connect(configuration["Redis:Configuration"]);
                context.Services
                    .AddDataProtection()
                    .PersistKeysToStackExchangeRedis(redis, "TemplateName-Protection-Keys");
            }
        }
        private void ConfigureCache(IConfiguration configuration)
        {
            Configure<AbpDistributedCacheOptions>(options =>
            {
                options.KeyPrefix = "TemplateName:";
            });
        }
```
3.Modify appsettings.json
```json
  "App": {
    "SelfUrl": "https://localhost:44396"
  },
  "Redis": {
    "Configuration": "127.0.0.1"
  },
```
