### ISSUE TITLE
Docs - Cascading error in project-selector (regression)

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#10281]
The bug got introduced with the linked commit, so it's there since rel 4.4.0 and still persists in the current 5.0-beta.
https://github.com/abpframework/abp/commit/e0cb2dbce823b499e7cc539cc62b87be79e217a1

![image](https://user-images.githubusercontent.com/7882753/136756852-08586c55-0dee-4293-bcf7-7425bb155b13.png)

I'll contribute a fix

**Comment by realLiangshiwei** [comment]
Thanks a lot, Looking forward to your PR
