### ISSUE TITLE
ICrudAppService: Inconsistent "GetAll" vs "GetList" naming

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#1028]
IAsyncCrudAppService [uses GetList](https://github.com/abpframework/abp/blob/f62ed01ac24433dcdc0faf02400fc871caa65dbe/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/IAsyncCrudAppService.cs#L33) but ICrudAppService [uses GetAll](https://github.com/abpframework/abp/blob/f62ed01ac24433dcdc0faf02400fc871caa65dbe/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/ICrudAppService.cs#L32) instead.

The example ToDo service  [also uses GetList](https://github.com/abpframework/abp/blob/96ee0b04368bc21fc595554758d1e9a4ca428249/templates/service/src/MyCompanyName.MyProjectName.Application.Contracts/MyCompanyName/MyProjectName/Todos/ITodoAppService.cs#L8).

I also prefer "GetList" to "GetAll" since GetAll might be confusing and indicate that no query filters are applied.

Note: fixing this will result in a breaking change.

Edit: if you are going to change "GetAll" to "GetList", do not forget to update the implementations as well. For example, "GetAllPolicyName" should be named "GetListPolicyName" in CrudAppServiceBase.

**Comment by hikalkan** [comment]
Thank you @Trojaner for indicating it. Since we always use the Async one, the sync one has forgotten.
Will make this change. Yes it is breaking change but this framework is still in preview, so no problem :)
