### ISSUE TITLE
0.15 update to 0.16 Error

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#1029]
“dotnet.exe”(CoreCLR: clrhost): 已加载“C:\Users\www\.nuget\packages\identitymodel\3.10.6\lib\netstandard2.0\IdentityModel.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
引发的异常:“System.IO.FileNotFoundException”(位于 Volo.Abp.Core.dll 中)
“System.IO.FileNotFoundException”类型的异常在 Volo.Abp.Core.dll 中发生，但未在用户代码中进行处理
Could not load file or assembly 'Volo.Abp.MultiTenancy.Abstractions, Version=0.15.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。

**Comment by maliming** [comment]
Please share the full stack error and log.

**Comment by hikalkan** [comment]
``Volo.Abp.MultiTenancy.Abstractions`` is renamed to ``Volo.Abp.MultiTenancy``.

https://github.com/abpframework/abp/issues/911
