### ISSUE TITLE
5.0 Generic Repositories, how to select column?

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#10291]
ABP Framework version: 5.0
Database provider: EF Core

Generic Repositories 4.x select is like below.

return await UserRepository.Select(x=>x.Name).ToListAsync();

How to select in abp 5.0 Generic Repositories？

**Comment by realLiangshiwei** [comment]
Try use `GetQueryableAsync` method.

**Comment by jakeuj** [comment]
> Try use `GetQueryableAsync` method.

return await (await UserRepository.GetQueryableAsync()).Select(x=>x.Name).ToListAsync();

Like this? Thx.

**Comment by realLiangshiwei** [comment]
Right
