### ISSUE TITLE
AccessToken doesn't seem to expire

### ISSUE THREAD

**Issue by pagner** [abpframework/abp#10303]
ABP Version : 4.4.2

I am accessing the API from a console application (no cookies). This works well and I get my data.

I have set AccessTokenLifetime to 120 (2 minutes) in the database.

I go through the OAuth flow the first time and save the returned access token. The token shows an expiration of 2 minutes like it should. (UTC)

For the subsequent requests I set the BearerToken manually with the saved token. 

The "problem" is that I can still gain access to the API well after two minutes.

I even tried deleting all entries in the persisted grants table.

Am I missing something here?  I was expecting to get a 401 unauthorized.

Is there a Cache?

Thanks in advance!

**Comment by pagner** [comment]
Forgot to mention, I am using this code here in my console app.

https://github.com/bartvanhoey/AbpAddCustomClaimToAccessToken

You can grab the access token from here:
httpClient.Value.DefaultRequestHeaders.Authorization.Parameter;

**Comment by realLiangshiwei** [comment]
Can you use ABP CLI to create a new project to reproduce? thanks.

**Comment by pagner** [comment]
@realLiangshiwei 

I have attached a modded version of @bartvanhoey console project. You can point this at your abp API. You have to build the api anyway so you can seed the database and change the AccessTokenLifetime.

There are a couple comments at the top of Program.cs

`
// ######## IMPORTANT Open HttpService in this project (lines  41 & 45). Change ClientId and Scope to reflect your abp project name. In my case it was "io" #########

// Open database dbo.IdentityServerClients and change AccessTokenLifetime to 120 (two minutes). Restart the server! Run this console app.
`

[BookStoreConsole.zip](https://github.com/abpframework/abp/files/7340749/BookStoreConsole.zip)

**Comment by realLiangshiwei** [comment]
It related to Clock skew
See https://stackoverflow.com/questions/47153080/clock-skew-and-tokens
