### ISSUE TITLE
How can I reach AbpFramework core tables in Repository Layer

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#10309]
* Your **ABP Framework version**. 4.3.3
* Your database provider(EF Core)

I want to join SaasTenant with my table in EfCore Repository layer. But SaasTenant(for commercial) is not exists in MyContext

EfCoreSellerRepository:
```
            var query = from seller in (await GetDbSetAsync())
                               join tenant in (await GetDbContextAsync()).SaasTenant on seller.TenantId equals tenant.Id
```

**Comment by maliming** [comment]
You can aggregate the results in memory.
