### ISSUE TITLE
Javascript proxy not generated

### ISSUE THREAD

**Issue by xiangyisheng** [abpframework/abp#10319]
ABP Framework version: 4.4.2

User interface type: MVC

The namespace is: retail.bookstore.books,

Application services are:

public class BookAppService : CrudAppService<Book, BookDto, Guid, PagedAndSortedResultRequestDt, CreateUpdateBookDto>, IBookAppService

Shouldn't running MVC applications generate API proxy scripts for retail.bookstore.books.book? I checked /Abp/ServiceProxyScript and only saw some default agents (tenants, users, etc.) from ABP

Using Tiered, the retail.bookstore.httpapi.host project can normally generate the API proxy script of retail.bookstore.books.book

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

Please write in english. thanks

**Comment by realLiangshiwei** [comment]
Can't reproduce the problem, I don't think it's an issue with ABP, you should double-check your code
