### ISSUE TITLE
Is it possible to give a client API permissions without username/password?

### ISSUE THREAD

**Issue by pagner** [abpframework/abp#10316]
I have a wpf app that I am able to get an access token using ClientId="io_App", ClientSecret="*****" and GrantType = "client_credentials"

But after that I am unable to perform anything meaningful. I get 403 forbidden on every api endpoint.

I can use the api successfully if I include the username and password of a registered user, but I don't want to distribute the app with the credentials in it.

How do I give my wpf app permission to register a new user (/api/account/register)? Or is this not possible?

I am familiar with OAuth but new to Identity Server. Trying to figure this out as I go.

Thanks in Advance!

**Comment by maliming** [comment]
hi

see https://support.abp.io/QA/Questions/1112/How-to-grant-access-to-Identity-Server-Client-on-multi-tenancy#answer-9c1da15b-8264-8fd5-d73a-39fb93d63fd0

**Comment by pagner** [comment]
@maliming 
Thanks for your quick reply! How do I get to that screen? I logged in as Host and don't see anything for clients. Mind you I have overriden the styles for the site extensively.

thanks

**Comment by maliming** [comment]
This is a pro feature, You can grant some permissions to your client.
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/Permissions/ClientPermissionValueProvider.cs#L11

**Comment by pagner** [comment]
Thanks, that's what I figured.

How do I grant the permissions? By PermissionDefenitionProvider/Group or
Database entry in AbpPermissionGrants?

Can you please explain.
Thanks

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Modules/Permission-Management#ipermissionmanager

**Comment by pagner** [comment]
Thanks for your help! I finally got it.
