### ISSUE TITLE
Add Load<T>(id) function into Specifications to load related entities (Feature Request)

### ISSUE THREAD

**Issue by mgochmuradov** [abpframework/abp#10326]
### Feature Request

Wiil it be possible to load related aggregate root items for current entity. It will be useful in situations where no Navigation property is defined.

May be by adding a `Load<T>(id)` function into a base `Specification` class.

Example usage:
```cs
public class VipOrderSpecification : Specification<Order>
{
    public override Expression<Func<Order, bool>> ToExpression()
    {
        return (order) => Load<Customer>(order.CustomerId).IsVip;
    }
}
```

*PS: There is something similar in a RavenDB: [https://ravendb.net/docs/article-page/5.2/csharp/indexes/indexing-related-documents](https://ravendb.net/docs/article-page/5.2/csharp/indexes/indexing-related-documents)*

**Comment by realLiangshiwei** [comment]
Hi,

Thanks,  But I don't think we will add this feature, It sounds like a RavenDB specific feature.
