### ISSUE TITLE
How to do the redundancy of IdentityUser with extra properties

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#10331]
I have extended the IdentityUser to add SocialSecurityNumber property followed the guide of [Module Entity Extensions](https://docs.abp.io/en/abp/latest/Module-Entity-Extensions)

And I would do the redundancy of IdentityUser like Volo.CmsKit module:
![image](https://user-images.githubusercontent.com/6952917/137444087-75e297e1-1fd5-4df2-a603-883c6677f268.png)

But I found I cannot extend UserEto to add extra properties, such as SocialSecurityNumber property.
How to do the redundancy of IdentityUser with extra properties?
I do as follow, but It doesn't work.

I define my DyUserEto like 
```
public class DyUserEto : UserEto, IDyUserData
    {
        public string SocialSecurityNumber { get; set; }
    }
```

And DyUserSynchronizer
```
public class DyUserSynchronizer :
        IDistributedEventHandler<EntityUpdatedEto<DyUserEto>>,
        ITransientDependency
    {
        protected IDyUserRepository UserRepository { get; }

        protected IDyUserLookupService UserLookupService { get; }

        public DyUserSynchronizer(
            IDyUserRepository userRepository,
            IDyUserLookupService userLookupService)
        {
            UserRepository = userRepository;
            UserLookupService = userLookupService;
        }

        public virtual async Task HandleEventAsync(EntityUpdatedEto<DyUserEto> eventData)
        {
            var user = await UserRepository.FindAsync(eventData.Entity.Id);
            if (user == null)
            {
                user = await UserLookupService.FindByIdAsync(eventData.Entity.Id);
                if (user == null)
                {
                    return;
                }
            }

            if (user.Update(eventData.Entity))
            {
                await UserRepository.UpdateAsync(user);
            }
        }
    }
```

Then I do configuration In DybookDomainModule:
```
public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAutoMapperObjectMapper<DybookDomainModule>();
            Configure<AbpAutoMapperOptions>(options =>
            {
                options.AddProfile<DybookDomainAutoMapperProfile>(validate: false);
            });
            Configure<AbpDistributedEntityEventOptions>(options =>
            {
                options.EtoMappings.Add<IdentityUser, DyUserEto>(typeof(DybookDomainModule));
            });

            Configure<AbpMultiTenancyOptions>(options =>
            {
                options.IsEnabled = MultiTenancyConsts.IsEnabled;
            });

#if DEBUG
            context.Services.Replace(ServiceDescriptor.Singleton<IEmailSender, NullEmailSender>());
#endif
        }
```

I have upload the [demo](https://github.com/gerryge/dybook) to my github:
The step I do:
1. abp new Acme.Dybook
2. add SocialSecurityNumber property followed the guide of [Module Entity Extensions](https://docs.abp.io/en/abp/latest/Module-Entity-Extensions)
3. add User redundancy functions in Acme.Dybook.Domain project follow the CmsKit module.
4. Change UseEto to DyUserEto

You can run the Acme.Dybook.DbMigrator to update the database, and then run the Acme.Dybook.Web.
But if you add breakpoint in the HandleEventAsync function of DyUserSynchronizer.cs file, when you edit one user,
It's doesn't trigger this event handler at all.

![image](https://user-images.githubusercontent.com/6952917/137445916-e6d18bb9-dbf8-4c88-b0c7-822f5a005b63.png)

![image](https://user-images.githubusercontent.com/6952917/137445851-b625e416-c369-4635-823d-313ca8d105df.png)

**Comment by maliming** [comment]
```cs
Configure<AbpDistributedEntityEventOptions>(options =>
{
    options.AutoEventSelectors.Add<IdentityUser>();
});
```

https://docs.abp.io/en/abp/4.4/Distributed-Event-Bus#configuration
