### ISSUE TITLE
Abp IdentityServer4 with SAML2P

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#10332]
Hello,

I want to enable SAML 2.0 in Abp IdentityServer (Tiered) by using Rsk.IdentityServer4.Saml and following  (https://www.identityserver.com/articles/saml-20-integration-with-identityserver4) 

i'm facing some difficulties related to conflict between object and builders ....

Any help please?

Best Regards

**Comment by maliming** [comment]
> i'm facing some difficulties related to conflict between object and builders ....

Can you explain it?

**Comment by aelhadi** [comment]
first problem, when i install the Rsk.IdentityServer4.Saml i'm getting error about ambiguity in :

app.UseIdentityServer(); 
![image](https://user-images.githubusercontent.com/5918026/137451583-a8e62c66-07de-4c38-97cf-0df79eac9be5.png)

if you can provide example how to enable SAML with Rsk.IdentityServer4.Saml i'll be thankful.

**Comment by maliming** [comment]
You can use the static method. This is not related to Abp.
