### ISSUE TITLE
all applications return the configuration of the first cached application

### ISSUE THREAD

**Issue by liubin3071** [abpframework/abp#10339]
Because the cache key cannot identify the application, all applications return the configuration of the first cached application, which leads to the wrong result of “RemotePermissionChecker.IsGrantedAsync(string name)”

——Google Translate

```
public async Task<ApplicationConfigurationDto> GetAsync()
        {
            var cacheKey = CreateCacheKey();
            var httpContext = HttpContextAccessor?.HttpContext;

            if (httpContext != null && httpContext.Items[cacheKey] is ApplicationConfigurationDto configuration)
            {
                return configuration;
            }

            configuration = await Cache.GetOrAddAsync(
                cacheKey,
                async () => await Proxy.Service.GetAsync(),
                () => new DistributedCacheEntryOptions
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(300) //TODO: Should be configurable.
                }
            );

            if (httpContext != null)
            {
                httpContext.Items[cacheKey] = configuration;
            }

            return configuration;
        }
```

**Comment by liubin3071** [comment]
Is this a design or a bug?

**Comment by maliming** [comment]
I will check this.

**Comment by maliming** [comment]
hi

> Because the cache key cannot identify the application, all applications return the configuration of the first cached application

This seems to be no problem, can you explain it in detail?

**Comment by liubin3071** [comment]
in abp.sample resp,  MicroserviceDemo

if you login from PublicWebSite.Host first, then open BackendAdminApp.Host fast, you will get a Permission  error.

in BackendAdminApp.Host, you will get ApplicationConfigurationDto cache of publicwebsite.

the cache key for ApplicationConfigurationDto should contain appclientid.

**Comment by maliming** [comment]
There will be `UserId` in the cache key, Please share the full HTTP request logs of this case.

**Comment by liubin3071** [comment]
The ApplicationConfigurationDto of the same user in different applications is different.
RemotePermissionChecker.IsGrantedAsync(string name) checks permissions based on the wrong ApplicationConfigurationDto cache.
I have described it very clearly, if you want to reproduce this bug, please follow the steps to test MicroserviceDemo.
If you think this is not a bug, please close it.
——Google Translate
