### ISSUE TITLE
Repository.InsertAsync returns -2147482647 for Id of entity saved.

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#1034]
Just like the title says, Repository.InsertAsync and Repository.Insert return -2147482647 for Id of entity saved, instead of the actual Id field that was inserted from the database.  I am not sure when this stopped working, but it has to have been in the last few versions.

**Comment by acjh** [comment]
Pass `autoSave = true`.

**Comment by hikalkan** [comment]
>Repository.InsertAsync and Repository.Insert return -2147482647 for Id of entity 

This is how EF Core works. You can save to get the actual Id as @acjh indicated.

**Comment by djlaney3** [comment]
Autosave = true worked.  When did this change?

**Comment by hikalkan** [comment]
It is not changed in ABP. As I said this is behavior of EF Core. I asked it to Microsoft before: https://github.com/aspnet/EntityFrameworkCore/issues/6147
You can read their answers.

**Comment by djlaney3** [comment]
Interesting.  I updated by .net core version last week, I wonder if that changed it.  This was working and passing all my tests up until today.  This is the first time in a few weeks I tested this part.  Thanks!
