### ISSUE TITLE
Could you add a Partially update entity method?

### ISSUE THREAD

**Issue by WuLex** [abpframework/abp#10341]
Hello ,

Could you add a Partially update entity method? 

` var result4 = db.Updateable(updateObj).UpdateColumns(it => new { it.Name, it.CreateTime }).ExecuteCommand();`

ORM:
How can i use  https://github.com/donet5/SqlSugar?

**Comment by realLiangshiwei** [comment]
ABP abstracts the data access repository, you can implement it with SqlSugar.
