### ISSUE TITLE
Feature Request, Option to specify HttpClient timeout for DynamicProxyHttpClient

### ISSUE THREAD

**Issue by abou-emish** [abpframework/abp#10344]
**ABP Framework version 4.4.3**
 
**abp** currently doesn't provide any HttpClient options to pass to DynamicProxyHttpClientFactory

I want to change HttpClient timeout, and I had to replace **DefaultDynamicProxyHttpClientFactory** implementation to achieve that.

Would you consider implementing this feature  :)

**Comment by realLiangshiwei** [comment]
Try:

```CSharp
PreConfigure<AbpHttpClientBuilderOptions>(options =>
{
    options.ProxyClientBuildActions.Add((remoteServiceName, clientBuilder) =>
    {
        clientBuilder.ConfigureHttpClient(httpClient =>
        {
            httpClient.Timeout = TimeSpan.FromSeconds(30);
        });
    });
});
```
