### ISSUE TITLE
How to do the redundancy of IdentityUser with extra properties

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#10357]
After added below code, I can go to the breakpoint, but the extra properties value is null
```cs
Configure<AbpDistributedEntityEventOptions>(options =>
{
    options.AutoEventSelectors.Add<IdentityUser>();
});
```

https://docs.abp.io/en/abp/4.4/Distributed-Event-Bus#configuration

![image](https://user-images.githubusercontent.com/6952917/137836107-8ed6ce9e-8205-4237-bbf3-c0da7081c1f8.png)

Does abp cannot auto map the extra properties?

Another question is that the parameter `IUserData` of `CreateUser` function in  `UserLookupService`  cannot support extend.
```
protected abstract TUser CreateUser(IUserData externalUser);
```
Although I define a IDyUserData interface which include the extra properties, but I should convert it to IUserData which will lose the extra properties.
![image](https://user-images.githubusercontent.com/6952917/137836821-3f2636e0-b285-4cc9-95c6-9e9e419d11fa.png)

My request is clear, I want to to do the redundancy of IdentityUser with extra properties.
Isn't what I did above the right way?
Should I customize the Volo.Users and Volo.Identity modules?

My [demo](https://github.com/gerryge/dybook) has pushed to the github, if you want to debug.

_Originally posted by @maliming in https://github.com/abpframework/abp/issues/10331#issuecomment-945435779_

**Comment by realLiangshiwei** [comment]
The extra properties are store in the `ExtraProperties` property, you need to custom the mapper profile.

**Comment by gerryge** [comment]
Additional information:
https://github.com/abpframework/abp/issues/10331#issue-1027142556
