### ISSUE TITLE
CORS error when request application-configuration through gateway

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10367]
I start the abp service on https://localhost:32001, and use ocelot as gateway to map the requests to https://localhost:30001/test/{path} to  https://localhost:32001/{path}. 
 
When I visit through angular app (http://localhost:4200/), I see CORS error (happened in [zone.js:2863]) in the request to https://localhost:30001/test/api/abp/application-configuration, however, if I request the same url in browser, it works.

If I change the angular app api url to https://localhost:32001 (NOT through gateway), it also works without error.

Does anyone know the reason and possible fixing? Thank you!

**Comment by maliming** [comment]
You should check the CORS configuration of your application.
