### ISSUE TITLE
abp add-module corrupts the solution file.

### ISSUE THREAD

**Issue by antosubash** [abpframework/abp#10362]
* Your **ABP Framework version**. - 4.4.3 
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI. - MVC
* Your database provider(EF Core/MongoDB)- EF Core

**Steps needed to **reproduce** the problem.**

Create a module project

```bash
abp new MainApp -t module
```

Now add the module

```bash
abp add-module MainApp.ModuleOne --new --add-to-solution-file
```

Now open the solution.

Here is the sample Repo: https://github.com/antosubash/abp-add-module-bug

**Comment by realLiangshiwei** [comment]
Hi,

The `add-module` command only supports the app template.

**Comment by antosubash** [comment]
@realLiangshiwei thanks for the update. It is not mentioned in the documentation. 

Does it mean we cannot use `add-module` command to use built in modules as well? like docs and blogging? in the Module template?

**Comment by realLiangshiwei** [comment]
Yes

**Comment by BeiMeng** [comment]
abp add-module corrupts the solution file   Your ABP Framework version. - 4.4.4   user abp add-module Volo.Account --with-source-code --add-to-solution-file --skip-db-migrations

**Comment by realLiangshiwei** [comment]
@BeiMeng  https://github.com/abpframework/abp/issues/10362#issuecomment-946533503

Move to: https://github.com/abpframework/abp/issues/10388
