### ISSUE TITLE
Integration with Isolated (out-of-process) Azure Functions

### ISSUE THREAD

**Issue by lommez** [abpframework/abp#10366]
Is there way or plans to support integration with .Net 5.0 Isolated Azure Functions?

I tried to do something like that:

![image](https://user-images.githubusercontent.com/10900667/137977895-dea04b09-069b-40fe-bdf5-8a02dadca674.png)

![image](https://user-images.githubusercontent.com/10900667/137977936-fcc286fd-1325-44ad-92bf-2c4f5ebe8187.png)

![image](https://user-images.githubusercontent.com/10900667/137977975-95d29f79-5a6b-4622-b7c5-19de9fd66d49.png)

But when the application is initialized, it raises that exception:

```
The requested service 'Volo.Abp.DependencyInjection.ObjectAccessor`1[[Microsoft.AspNetCore.Builder.IApplicationBuilder, Microsoft.AspNetCore.Http.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
```

![image](https://user-images.githubusercontent.com/10900667/137978100-47d20a2f-ce5d-43cc-839a-ec6d644f925b.png)

**Comment by maliming** [comment]
hi

Try to depend on `AbpAspNetCoreModule`.

**Comment by lommez** [comment]
Thanks @maliming !!
Works perfectly!
