### ISSUE TITLE
Tenent DefaultConnectionString length is too short

### ISSUE THREAD

**Issue by Webdiyer** [abpframework/abp#1036]
https://github.com/abpframework/abp/blob/7b3f0cbf8203973712ad35df96dceeb0570ba83c/modules/tenant-management/src/Volo.Abp.TenantManagement.Web/Pages/TenantManagement/Tenants/ConnectionStringsModal.cshtml.cs#L55

Should it be TenantConnectionStringConsts.MaxValueLength?

**Comment by hikalkan** [comment]
You are definitely right.
