### ISSUE TITLE
Blazor UI - abp.js

### ISSUE THREAD

**Issue by Fane276** [abpframework/abp#10377]
I am facing an issue or more like a nice to have feature. Is there any alternative for abp.js in Blazor UI? I mean if features from abp.js are also implemented in .Net for Blazor.
A concrete example is the abp.ui.setBusy() method, I think that it will be nice to have the same method in Blazor something like Abp.Ui.SetBusy(TElement element) so that we don't need to import JSInterop to perform this action.

ABP Framework version: 4.4.2
UI Type: Blazor

**Comment by realLiangshiwei** [comment]
abp.js is not available for Blazor.

You can look for other third-party libraries: https://github.com/search?q=block+blazor

**Comment by Fane276** [comment]
Alright, then I will do this translation with my colleagues and we will be more than glad to come with a pull request.
