### ISSUE TITLE
How to config visualstudio to debug into abp source code

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#1039]
need a setp guide.
I configed source server support in vs，but not worked.
I dont know what is the right step to config it to work.
I had read some article，but it all about the abp old version not vnext.What is the difference?
Does vnext support gitlink now?

**Comment by maliming** [comment]
Abp supports SourceLink

![image](https://user-images.githubusercontent.com/6908465/56625111-5af5ba80-666e-11e9-9238-ff3714403c06.png)

https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx
https://aspnetboilerplate.com/Pages/Documents/Debugging

**Comment by derily** [comment]
![企业微信截图_15785350951581](https://user-images.githubusercontent.com/12644993/72031184-93a1f680-32c6-11ea-99f9-39231a286fb0.png)

**Comment by GerryGe** [comment]
I set as mentioned above, it doesn't work. 
You should do more settings:
1. Enable Symbol Serves
![image](https://user-images.githubusercontent.com/6952917/77402653-f39a3a80-6de9-11ea-8cce-d06a0f62376d.png)

After this, you can debug the asp.net core source code, you can see the  Symbols loaded in output windowb but volo.abo.* symbols cannot be loaded. I don't know why?

2.Copy Volo.Abp.Core.dll and Volo.Abp.Core.pdb to your working debug bin folder.
There are in the nuget install package path, like "C:\Users\[your user name]\.nuget\packages\volo.abp.core\2.3.0\lib\netstandard2.0"

After this I can step into abp source code, see my screenshots:


![image](https://user-images.githubusercontent.com/6952917/77402461-ad44db80-6de9-11ea-9338-81b9762b7f94.png)
![image](https://user-images.githubusercontent.com/6952917/77402491-b635ad00-6de9-11ea-9e46-8539b1429758.png)
