### ISSUE TITLE
TypeLoadException: Method 'AppendIdentityWhereCondition' in type 'Pomelo.EntityFrameworkCore.MySql.Update.Internal.MySqlUpdateSqlGenerator' 

### ISSUE THREAD

**Issue by andylaufzf** [abpframework/abp#10397]
I create a project with abp vnext 5.0 preview,but this is an error when i run it.The flow is the error message:

TypeLoadException: Method 'AppendIdentityWhereCondition' in type 'Pomelo.EntityFrameworkCore.MySql.Update.Internal.MySqlUpdateSqlGenerator' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=6.0.0.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.
Microsoft.Extensions.DependencyInjection.MySqlServiceCollectionExtensions.AddEntityFrameworkMySql(IServiceCollection serviceCollection)

DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1[Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext])' on type 'SettingManagementDbContext'.
Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()

DependencyResolutionException: An exception was thrown while activating Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext.
Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action<ResolveRequestContext> next)

**Comment by maliming** [comment]
Can you try to add the latest package to your project?

https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-preview.7

**Comment by andylaufzf** [comment]
I try it,but the bug remains.

**Comment by andylaufzf** [comment]
> Can you try to add the latest package to your project?
> 
> https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-preview.7

I try it,but the bug remains.

**Comment by maliming** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1510#issuecomment-922244242

**Comment by andylaufzf** [comment]
> See [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1510 (comment)](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1510#issuecomment-922244242)

Entityframeworkcore updated to 6.0.0-rc2.21480.5
pomelo.entityframeworkcore.mysql updated to 6.0.0-preview.7,
but the bug remains.

**Comment by maliming** [comment]
This is related to Pomelo, not abp.
