### ISSUE TITLE
Static JavaScript proxies - with auto generated API.

### ISSUE THREAD

**Issue by adamlonsdale** [abpframework/abp#10411]
I am running the new v5.0.0 beta 2, and I can't see a way with the static JavaScript generator to work with the tiered application architecture. Forgive me if I am raising this before the documentation is ready as I am just getting familiar with the framework. 

The problem I see is that the app-proxy.js uses the abp.AppPath for it's root URL. I believe this is the URL to the web app itself where in my sample I have been following (Book Store API) - my API is an auto generated API in a separate service (HttpApi.Host). I noted a workaround in https://github.com/abpframework/abp/issues/1469#issuecomment-856823638 which suggests changing the abp.AppPath to a new value and this does seemingly work but causes other issues with the application (I'm struggling to get authorization headers to be passed to the HttpApi and it redirects to the swagger when you don't have permission to view a page). 

My hope was that a static proxy generated at dev time would mean I don't have the issue reported relating to Auto API and dynamic proxies.

I think that the abp.AppPath should be a different value when generated from the ABP CLI when generating a static JavaScript proxy.

ABP Version: 5.0.0 beta 2
UI Type: Razor Pages
Database Provider: EF Core

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by adamlonsdale** [comment]
Apologies for not providing the reproduction steps. You can re-create this by following the tutorial on the ABP website when using a tiered app. The steps are as below:

1. Scaffold a new tiered application
1. Add a domain entity
1. Add an application service
1. Confirm the application service is visible in swagger
1. Generate static javascript proxy for the HttpApi.Host project via ABP CLI
1. Add javascript class to Web project
1. Add the following line of code to the ConfigureBundles lambda
 `options.ScriptBundles.Configure(BasicThemeBundles.Scripts.Global, x => x.AddFiles("/client-proxies/app-proxy.js"));`
1. Use static proxy from within a Razor Page and note that whilst the /client-proxies/app-proxy.js does contain a definition for the proxy, it always 404's because it is calling the web project and not the HttpApi.Host

**Comment by maliming** [comment]
hi

We will update the document to explain how to use the static proxy. https://github.com/abpframework/abp/issues/10433

**Comment by adamlonsdale** [comment]
Thanks for this, is there a bullet point list or something I can read to figure out how to proceed with the tutorial? Looking at purchasing a commercial business licence so need to get my sample up and running to demo. I'm happy to update the docs for you with a PR if I figure it out.

**Comment by maliming** [comment]
Please follow https://github.com/abpframework/abp/issues/10433

**Comment by adamlonsdale** [comment]
Hey, sorry for raising this again but I'm still a little confused. I've followed the new documentation and generated a JavaScript proxy for the Http API and placed it in the Host project instead of Web. I then removed the context.ScriptBundles.Configure element and just referenced the httpapi.host/client-proxies/app-proxy.js as per the samples. 

When I do the tutorial in a non-tiered application it all works fine, but in my tiered application it still uses abp.AppPath which is the path of the web endpoint so always 404's 

I asked someone else to follow the tutorial without making them aware of this issue and they ran into the same thing (Although with dynamic proxies).

**Comment by realLiangshiwei** [comment]
You should not generate a JavaScript proxy for the HTTP API project. you should generate a proxy for your client (Web)

**Comment by pavini** [comment]
ABP CLI:  5.0.0-rc.2
ABP Version: 5.0.0-rc.2
UI Type: Razor Pages
Database Provider: EF Core

Dears,

I'm very confused.

After reading some tutorials, I still can't get it to work.

As you can see in the image below, there are controllers in /api/abp/api-definition

![CleanShot 2021-12-09 at 14 15 18@2x](https://user-images.githubusercontent.com/202020/145444325-52d8b78c-a16d-4c1b-95d7-a062b9a7c695.png)

When I try to access my service on the console, I get the error shown in the image below.

![CleanShot 2021-12-09 at 14 18 29@2x](https://user-images.githubusercontent.com/202020/145444691-34144b2a-f363-48fd-b662-237051beb7db.png)

This is my service class

<img width="1190" alt="CleanShot 2021-12-09 at 14 20 08@2x" src="https://user-images.githubusercontent.com/202020/145444856-a9954dce-90a9-4114-a20c-4487a31c562e.png">

**Comment by lemchen** [comment]
#9905 solved this problem , don't forget add web project url to HttpApi.Host CorsOrigins in appsettings.json
