### ISSUE TITLE
Upgrade to Blazorise 0.9.4.7

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#10415]

**Comment by realLiangshiwei** [comment]
When https://github.com/abpframework/abp/pull/9877 is merged, the Blazorise will upgrade to `0.9.5-preview2.1`.

Should we upgrade to Blazorise 0.9.4.7 now?

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/issues/10415#issuecomment-953598925
