### ISSUE TITLE
Documentation French translation: which branch to put on ?

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#1042]
Hi,

I am thankful of all your work since the original ASP.NET Boilerplate framework. Because of that, I would like to contribute to the documentation of ABP vNext by translating to French, my mother language. I read the contribution guide. The last step says :

> Send a pull request (PR) once you translate any document. Please translate documents & send PRs one by one. Don't wait to finish translations for all documents.

I know how to commit & push. But I am new to pull request concept. 

So my questions are:

1. Do I have to apply the "Creating a Topical Branch" section of [this article](https://yangsu.github.io/pull-request-tutorial/) ?
1. Which branch name do you suggest ?
1. Ok so I push to this branch .. then what ? Go to GitHub and hit the "Pull Request" button ?

**Comment by maliming** [comment]
hi @Stirda 
You can:
1. fork abp project on github.
2. Create the **/docs/fr/** directory and copy the **/docs/en/** content to the **/docs/fr/** directory.
3. Create your translation branch based on master. (Example: short name of the document to be translated)
4. Start the translation, submit the code to github after the translation.
5. Open the pull request. Merge your translation.


Before merging branches, you can continue to create new branches to translate other code.

If you encounter any problems, you can tell me directly on Github @maliming, I will help you solve it.




![image](https://user-images.githubusercontent.com/6908465/56655664-03833900-66c6-11e9-8b2d-ab61a758c1b1.png)

![image](https://user-images.githubusercontent.com/6908465/56655717-2b729c80-66c6-11e9-9f4b-6ee40066b85d.png)

![image](https://user-images.githubusercontent.com/6908465/56655750-48a76b00-66c6-11e9-975b-0be65a938476.png)

**Comment by Stirda** [comment]
Thanks for your detailed answer. Very appreciated. If I understood you correctly, you prefer I continue this discussion by writing to you directly. So do I.

**Comment by maliming** [comment]
@Stirda 
You can join abp's slack, we can communicate directly.

https://join.slack.com/t/abpframework/shared_invite/enQtNTI3MDA3NTk1NzQ2LWNkZTM4NjBlZGI1MWZjZmE3MmNmNzdjZTlhYTg2M2QwZTZmOTYzM2Y0MzY3MGM4ZGQ5NmU1YmE2MDVkOGQ4YTc

**Comment by abhishekbhalani** [comment]
> @Stirda
> You can join abp's slack, we can communicate directly.
> 
> https://join.slack.com/t/abpframework/shared_invite/enQtNTI3MDA3NTk1NzQ2LWNkZTM4NjBlZGI1MWZjZmE3MmNmNzdjZTlhYTg2M2QwZTZmOTYzM2Y0MzY3MGM4ZGQ5NmU1YmE2MDVkOGQ4YTc

Link is expired. can you send again.

**Comment by maliming** [comment]
hi @abhishekbhalani 

If you have questions about abp please create an issue.

**Comment by abhishekbhalani** [comment]
@maliming I did it..
