### ISSUE TITLE
Is abp.io suitable for polyglot microservices?

### ISSUE THREAD

**Issue by 1d0n7kn0w** [abpframework/abp#10432]
In our company, we are studying abp.io if it will suit our needs. We have different teams that are using different tech stacks and programming languages. Can we use abp.io in a single microservice? Is that even possible?

**Comment by maliming** [comment]
Of course, abpio is designed for microservices by nature.

https://abp.io/
https://docs.abp.io/en/abp/latest

**Comment by 1d0n7kn0w** [comment]
I don't think that you understood my question, our context is polyglot microservices.
"The polyglot microservices allow developers to pick a programming language of their choice in order to build products in more efficient ways" from https://en.wikipedia.org/wiki/Polyglot_(computing)
From what I saw in the microservices samples, for example the multi-tenancy component is strictly linked to abp.io if we want to develop a service to manage multi-tenancy let's say with spring boot, is a service constructed with abp.io can communicate with the latter and consume it the same way as abp.io does?

**Comment by cotur** [comment]
Hi @1d0n7kn0w 

ABP Framework built on modularity, extensibility and flexibility.
**You can change every component, you can override any part of the packages or modules for your requirements.**

By default, we provide the best implementation for many requirements (For example tenant resolving https://docs.abp.io/en/abp/latest/Multi-Tenancy#tenant-resolvers ) 
But that not means you are depended those, you may change/add the implementation for your business logic. 

For example: We have `Tenant Management Module` that manages the tenants. https://docs.abp.io/en/abp/latest/Modules/Tenant-Management
But you don't have to use it. You may use your module, or third party implementation.

I don't know the `spring boot` so I can't say anything about the implementation with it, but I know that "ABP Framework let us implement anything easily" :)

**Comment by 1d0n7kn0w** [comment]
Thank you very much, it's clear now in my head
