### ISSUE TITLE
[Question] Extending IdentityUser with regular properties

### ISSUE THREAD

**Issue by newacc12** [abpframework/abp#10434]
Is there a way to extend IdentityUser using regular properties? (e.g.: `public string MyProp {get;set;}`)

This [article](https://community.abp.io/articles/unifying-dbcontexts-for-ef-core-removing-the-ef-core-migrations-project-nsyhrtna#using-custom-properties-in-the-application-code) mentions about some ways to extend the entity which I find very not intuitive. I don't want to create a bunch of "Extension" classes with Get's and Set's methods plus repositories.

The same article also mentions:

> We need to remove the AppUser entity, because EF Core can't map two classes to single table without an inheritance relation.

But it never mentions on how to do it with inheritance. Can I do something like:
```
public class AppUser : IdentityUser
{
    public string MyProp { get; set; }
}
```
And use the AppUser through my code?

**Comment by realLiangshiwei** [comment]
Hi,

> But it never mentions on how to do it with inheritance

See https://docs.microsoft.com/en-us/ef/core/modeling/inheritance, but as explained in the article: **EF Core can't map two classes to single table without an inheritance relation**

You can try: 
https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

But using entity expansion system is the recommended way.

**Comment by newacc12** [comment]
Hi @realLiangshiwei Thanks for the answer but that's not what I was talking about. I don't want to map two entities to the same table or do table-splitting. 

If I create a brand new .NET 5 with EF Core app I am able to customize and use my own class for the user like this [https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0#custom-user-data](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0#custom-user-data). 

I was wondering if ABP provides any methods to do so. It doesn't look like I can pass a user type to AbpDbContext or IIdentityDbContext. Maybe there's another way?

**Comment by realLiangshiwei** [comment]
@newacc12 

> I was wondering if ABP provides any methods to do so. It doesn't look like I can pass a user type to AbpDbContext or IIdentityDbContext. Maybe there's another way?

ABP does not provide such a way yet.

**Comment by newacc12** [comment]
@realLiangshiwei 

Gotcha!

Assuming that this is feasible to implement, hopefully it can be considered as a future enhancement. It is not DDD friendly having to search for extensions methods or mapping code on the code base to be able to tell what properties are part of my domain model.

Thanks for getting back to me and for this awesome framework.
