### ISSUE TITLE
Define DataFilter expressions via IoC?

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#1044]
Currently data filters are manually added to the DbContext like defined [here](https://github.com/abpframework/abp/blob/219fba719df982a277dcdb219e17bfea6416d072/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L490). This means that anyone who wants to add custom data filters would have to override this method in all of their AbpDbContext instances.

My suggestion is: Maybe make the expression returned by `IDataFilter<TFilter>`?

e.g.
```cs
public class TenantDataFilter : DataFilterBase<IMultiTenant> // inherits IDataFilter<TFilter>
{
    protected virtual bool IsMultiTenantFilterEnabled => DataFilter.IsEnabled<IMultiTenant>();

    public ICurrentTenant CurrentTenant { get; set; }

    public override Expression<Func<TEntity, bool>> GetFilterExpression() // method defined in the interface, abstract in DataFilterBase
            where TEntity : class 
    {
         return  e => ((IMultiTenant)e).TenantId == CurrentTenantId || (((IMultiTenant)e).TenantId == CurrentTenantId) == IsMultiTenantFilterEnabled;
    }
}
```

After that something like this would be done in `CreateFilterExpression`:
```cs
protected virtual Expression<Func<TEntity, bool>> CreateFilterExpression<TEntity>()
            where TEntity : class
{
    Expression<Func<TEntity, bool>> expression = null;

    foreach(var dataFilter in GetEnabledDataFilters<TEntity>())
    {
         var dataFilterExpression = dataFilter.GetFilterExpression();
         expression = expression == null ? dataFilterExpression : CombineExpressions(expression, dataFilterExpression);
    }

    return expression;
}
```

Of course I do not know how this would work for other ORMs than EF Core. Another way would be to use IEFCoreDataFilter<TFilter> and EFCoreDataFilterBase instead to make it EF Core specific.

**Comment by hikalkan** [comment]
Good suggestion. We will check how it can be implemented.

**Comment by Trojaner** [comment]
Any updates?

**Comment by hikalkan** [comment]
Please check the latest document: https://docs.abp.io/en/abp/7.4/Data-Filtering#entityframework-core

Using DI may not be possible because of technical restrictions. I am closing this since it is too old and no much demand on it.
