### ISSUE TITLE
Change CurrentUser on DB Seed

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#10442]
* Your **ABP Framework version**.
* 4.4.3

Hi, I created new user with IdentityUserManager in Test Project. Yet i can't change currentUser to new created User. How can i do that ? 

Creating new User was easy.
```
IdentityUser identityUser = new IdentityUser(Guid.NewGuid(), "testusername", "test@mailim.com", null);
Microsoft.AspNetCore.Identity.IdentityResult identityResult = await _identityUserManager.CreateAsync(identityUser, "123RandomPassword***");

```

I tried SignInManager but failed becasue of dependency injection.

**Comment by EngincanV** [comment]
You need to mock the `ICurrentUser`. You can do this like below. 

```csharp
public class MyTestAppService_Tests : MyTestApplicationTestBase
{
  private ICurrentUser _currentUser;
  //...

  protected override void AfterAddApplication(IServiceCollection services)
  {
     _currentUser = Substitute.For<ICurrentUser>();
     services.AddSingleton(_currentUser);
  }

  private void Login(Guid userId)
  {
     _currentUser.Id.Returns(userId);
     _currentUser.IsAuthenticated.Returns(true);
  }

  [Fact]
  public async Task MyTestMethodAsync()
  {
     Login(<userId>); //login as 

     //your test logic
  }
}
```

> You can check the [FeatureAppService_Tests](https://github.com/abpframework/abp/blob/dev/modules/feature-management/test/Volo.Abp.FeatureManagement.Application.Tests/Volo/Abp/FeatureManagement/FeatureAppService_Tests.cs#L73-L77).

**Comment by ugurozturk** [comment]
Thank you, it worked
