### ISSUE TITLE
eShopOnAbp: Profile update error

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#10446]
When trying to update profile information, there is an error related with couldn't find end point.
![image](https://user-images.githubusercontent.com/25867/139014118-37622259-5b5a-48bb-a9e1-5de4888fabe9.png)
Missing identity endpoints
![image](https://user-images.githubusercontent.com/25867/139014251-1d52c5af-4492-480a-a412-ff4bd0b56b48.png)

**Comment by enisn** [comment]
We discovered, Account module accessing to Identity module with dynamic proxy instead of static proxy.

I've created an issue about it: https://github.com/abpframework/abp/issues/10449
