### ISSUE TITLE
JS Permissions Shouldnt Be Hard Coded

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#1045]
Why is it that all the permission in the JS files are hard coded strings instead the c# variables?  Makes trying to change things more complex than they have to be, especially if you want to change the groupnames etc.

https://github.com/abpframework/abp/blob/31a2abfae5cb5829c5dd9b684df017ebefbfebb6/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/IdentityPermissions.cs

**Comment by hikalkan** [comment]
>Why
No good reason. We can improve it.

**Comment by bbakermmc** [comment]
Not sure what you mean by no good reason?  In net zero we removed the Page prefix on every permission since it was redundant.  So now every time there is an update we need to make sure all the stupid permissions in js aren’t pages.  If you used the c# variable it would of been better and cause less problems when people don’t like your naming conventions or when you make typos.  This is one reason a lot of people don’t like JS and blazor would be the favored framework for .net developers.  No more of this crappy js.

Sent from my iPhone

On Apr 25, 2019, at 3:03 AM, Halil İbrahim Kalkan <notifications@github.com<mailto:notifications@github.com>> wrote:


Why
No good reason. We can improve it.

**Comment by hikalkan** [comment]
For Blazor, it would be good to share C# constants. For js, tis not easy to share same constants with c#.

>Not sure what you mean by no good reason

You said "Why is it that all the permission in the JS files are hard coded strings instead the c# variables", and I said I don't have a good reason to explain why I did it like that. Maybe it was the straightforward/easiest choice. It is not hard to understand.

BTW, "WHY" is not something people like, especially for such an open source project, if you don't ask it carefully and gently. Instead, you could simply offer a way of improvement, so we consider it and improve the project. Otherwise, it seems a negative critic rather positive suggestion.

**Comment by hikalkan** [comment]
This is an "opinionated" framework, that means we have to make some design decisions and can not make everyone happy. If you don't like our design decisions, you can suggest improvements, surely. But it is not guaranteed that your suggestions will be implemented. But stop to continuously speak ill of it. You don't have to use it. (I am not talking based only this conversation, but in general about your style).

**Comment by bbakermmc** [comment]
@hikalkan You also dont have to have an open source project.  You can keep the code closed and no one will say a word.  But its open, thus I can freely make comments as I choose, you dont have to implement anything as you have said.  Im not here to impress you to make you feel good about your product, Im here to give you honest real feedback, maybe youre not use to people like myselfs.  I write straight to the point feedback so you dont have to read BS.  Maybe where youre from people are different but here in USA - NY we are straight to the point, dont care about feelings, seems like you get hurt pretty easily when people question what you are doing, and because its "not easy" isnt really a valid response, its just the easy way to say we dont know or dont want want to fix it, all cons could be in the same namespace, referenced in the master layout and then you could use the C# variable just fine.

What I wrote initially and what I wrote below convey the same thing, except this is way longer and drawn out.
Hey I noticed all the JS files use hard coded permission names.  Can you tell me why you choose this option.  I think it would be better if you where to reference the c# const name instead, this would give greater flexibility to the developers to change the names and have the JS files be reflected properly w/out having to manually go thru and rename all the permissions after the fact.
