### ISSUE TITLE
 I got an error when I tried to clear all the data in mongoDB

### ISSUE THREAD

**Issue by sofm13** [abpframework/abp#10457]
ABP4.4.3
![image](https://user-images.githubusercontent.com/52565295/139174538-00a9005b-4a6c-4973-954c-036a291ab3d7.png)
- Exceptions:
  - CreateEntitiesFilter is not implemented for MongoDB by default. It should be overriden and implemented by the deriving class!
    System.NotImplementedException: CreateEntitiesFilter is not implemented for MongoDB by default. It should be overriden and implemented by the deriving class!

**Comment by realLiangshiwei** [comment]
I think the error message is clear,  you should implement the `CreateEntitiesFilter` method.

**Comment by sofm13** [comment]
Could you tell me where implement the CreateEntitiesFilter method,plz

**Comment by realLiangshiwei** [comment]
It should be overriden and implemented by the **deriving class**!
