### ISSUE TITLE
Q:How SignalR works in Abp with Blazor UI?

### ISSUE THREAD

**Issue by pp26** [abpframework/abp#10452]
Hi,
I just created a new Blazor UI Abp project. I'm trying a Noticification demo under the guidance of [:](https://community.abp.io/articles/realtime-notifications-via-signalr-in-abp-project-tsp2uqd3)

the guid used razor pages and js file. I tried to rebuild it in Blazor ,but some error appears and I can't handle it .

like set up a HubConnection :
![image](https://user-images.githubusercontent.com/4646703/139037758-8d710ddf-aac5-40dd-b14b-d16bb757908d.png)

Can you give me an example of SignalR in Blazor?

Thanks!

ABP Framework version: Latest
UI type: Blazor
DB provider: EF Core

**Comment by realLiangshiwei** [comment]
I think this is has nothing to do with ABP.

Check: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=server

**Comment by pp26** [comment]
> I think this is has nothing to do with ABP.
> 
> Check: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=server

Thank you ,I'll try it.
