### ISSUE TITLE
TextTemplating.Razor issue

### ISSUE THREAD

**Issue by fnomarkh** [abpframework/abp#10464]
**Version 4.4.0**.

**Issue Description:**
Generated Html from TextTemplating.Razor will duplicate attribute name and value if the value is provided by a razor variable.

**Steps to Reproduce:**
1. Use the [TextTemplating.Razor Sample](https://github.com/abpframework/abp-samples/tree/master/TextTemplateDemo/Razor).
2. Update `Hello.cshtml` to use a variable. Example:
```csharp
@inherits Volo.Abp.TextTemplating.Razor.RazorTemplatePageBase<TextTemplateDemo.Demos.Hello.HelloModel>
@{ 
    var path = System.IO.Path.Combine(System.AppContext.BaseDirectory, "Hello\\test.css");
}
Hello @Model.Name
<link type="text/css" rel="stylesheet" href="@path" />
```
3. Examine the output:
```html
Hello John
<link type="text/css" rel="stylesheet" href=" href="C:\Users\fomar\Source\Repos\abp-samples\TextTemplateDemo\Razor\bin\Debug\net5.0\Hello\test.cssC:\Users\fomar\Source\Repos\abp-samples\TextTemplateDemo\Razor\bin\Debug\net5.0\Hello\test.css" />
```

It seems the issue is in `Volo.Abp.TextTemplating.Razor.RazorTemplatePageBase` class. I played around with the code to fix it as bellow:
- To remove the duplicate attribute name:
```csharp
public virtual void BeginWriteAttribute(string name, string prefix, int prefixOffset, string suffix, int suffixOffset, int attributeValuesCount)
{
   _attributeInfo = new AttributeInfo(name, prefix, prefixOffset, suffix, suffixOffset, attributeValuesCount);
   if (attributeValuesCount != 1) //Added
   {
        WriteLiteral(prefix);
   }
}
```

- To remove duplicate value:
```csharp
public virtual void WriteAttributeValue(string prefix, int prefixOffset, object value, int valueOffset, int valueLength, bool isLiteral)
{
   ..
   ..
   ..
   //commented these two lines
   //_stringBuilder.Append(prefix);
   //_stringBuilder.Append(value);
}
```

I don't know if the update will have a side effect as I didn't study the functionality in detail!

**Update:**
Just noticed that the issue is already in the PasswordResetSample! The sample output:
```html
<a title=" title="ResetMyPasswordTitleResetMyPasswordTitle" href=" href="https://abp.io/example-link?userId=123&token=ABChttps://abp.io/example-link?userId=123&token=ABC">Click here to reset your password</a>
```

**Comment by maliming** [comment]
hi

You can create a subclass to override the method to temporarily solve it.
