### ISSUE TITLE
How to change unit test from InMemorySqlite to Mssql?

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#10462]
# Issue
* **ABP Framework version**
5.0.0-beta2
* **User Interface**
Angular
* database provider
EF Core (MSSQL)
* **stack trace**
```
System.InvalidOperationException: 
Translating this query requires the SQL APPLY operation, which is not supported on SQLite.
```
* **reproduce**
```
Specs.Join(Categories,s => s.Id,c => c.Id, (s, c) => 
new { ParentCategory = c.ParentCategory.Name, c.Name, SpecOptions = c.SpecOptions
.Where(x => s.Desc.Contains("," + x.Code + ","))
.Select(x => new { x.Name, x.Code, x.SpecCategory.Id })
.GroupJoin(ModelSpecDetails, o => new { o.Id, o.Code }, d => new { d.Id, d.Code }, (o, d) => 
new { o, d }).SelectMany(r => r.d.DefaultIfEmpty(), (x, y) => new { x.o.Name, y.Content })})
```
## Problem
Sqlite has many differents with mssql, and it will make unit test failed.
* [SQLite supports AutoIncrement only for column of type INTEGER PRIMARY KEY](https://stackoverflow.com/questions/49592274/how-to-create-autoincrement-column-in-sqlite-using-ef-core)
* System.InvalidOperationException:
Translating this query requires the SQL APPLY operation, which is not supported on SQLite.

I think still have many problem about using sqlite to test mssql service.
So, how to change unit test from InMemorySqlite to Mssql?

Thank for help!

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL

**Comment by jakeuj** [comment]
> https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL

So test is the same doc with src, okay.

That mean there is no InMemoryMsSql, I should use (LocalDb)\MSSQLLocalDB to run test, right?

Thank you very much.

**Comment by maliming** [comment]
See https://docs.microsoft.com/en-us/ef/core/providers/in-memory/

These are related to EF Core and have nothing to do with abp.
