### ISSUE TITLE
Reflect to get values

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#1046]
Reflect over properties to get the values, hard coding is bad.

https://github.com/abpframework/abp/blob/31a2abfae5cb5829c5dd9b684df017ebefbfebb6/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/IdentityPermissions.cs#L30

**Comment by hikalkan** [comment]
Since this code part is not in the framework, we can create a helper method to get all constants recursively from a class and return them as an array. Then we can use that helper method from such classes.
