### ISSUE TITLE
Bug migrating ABP.io to PostgreSQL with schema support table __EFMigrationsHistory

### ISSUE THREAD

**Issue by macw73** [abpframework/abp#10478]
* Your **ABP Framework version**.
4.4.3
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
Blazor (Webassembly)
* Your database provider(EF Core/MongoDB)
EF Core
* Exception message and **stack trace** if available (check the logs):
```
[15:47:44 ERR] Failed executing DbCommand (36ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "MigrationId", "ProductVersion"
FROM "__EFMigrationsHistory"
ORDER BY "MigrationId";
Unhandled exception. Npgsql.PostgresException (0x80004005): 42P01: relation "__EFMigrationsHistory" does not exist

```
* Steps needed to **reproduce** the problem.
1. Create visual studio project
`abp new acme.testproject -u blazor --separate-identity-server --tiered --dbms postgresql --connection-string "User ID = postgres;Password=XXXXXXXXXX;Server=XXX.amazonaws.com;Port=5432;Database=database;Integrated Security=true;Pooling=true;SearchPath=SCHEMA"`
Use schema as search path.
2. if you have created an abp.io project already using a different schema in the same database the error will occur because the checking for the db doesn't respect schemas.
DBLOG:
`SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE c.relname='__EFMigrationsHistory')`
should be 
`SELECT * FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE c.relname='__EFMigrationsHistory' and nspname= 'SCHEMA'`

**Comment by maliming** [comment]
This seems to be related to EF Core rather than ABP.
