### ISSUE TITLE
Dual licensed Consideration

### ISSUE THREAD

**Issue by catwarrior** [abpframework/abp#10477]
if change license is not a good choice for now
https://github.com/abpframework/abp/issues/1988

Propose to change the Licensing of **ABP Commercial** to Commercial License other than LGPL.

and ABP can keep LGPLv3.

That will give the flexiability to buy ABP Commercial.

**Comment by maliming** [comment]
Related to https://github.com/abpframework/abp/issues/2352#issuecomment-953428949
