### ISSUE TITLE
Will it be added IsUnique for AbpSettings index?

### ISSUE THREAD

**Issue by rwecho** [abpframework/abp#10476]
In some situations, AbpSettings has multiple records with the same index constraint. Then the system crashed.
I can not reproduce the scene. But multiple same rows in AbpSettings. 
For example: 

39ffdd0c-d099-1f36-753e-f157848126ae	ScaleMode	1	U	39ffc797-d48a-2efc-adf1-c0fe75e9c384
39ffdd20-d7be-062c-f7dc-e8b4e87c4822	ScaleMode	1	U	39ffc797-d48a-2efc-adf1-c0fe75e9c384

Should this be added unique constraint?
```
 builder.Entity<Setting>(b =>
            {
                b.ToTable(AbpSettingManagementDbProperties.DbTablePrefix + "Settings", AbpSettingManagementDbProperties.DbSchema);
                ...
                b.HasIndex(x => new {x.Name, x.ProviderName, x.ProviderKey}).IsUnique();

                ...
            });
```

https://github.com/abpframework/abp/blob/59851f72ae5b729fa123e0379cfc39e2499c11fc/modules/setting-management/src/Volo.Abp.SettingManagement.EntityFrameworkCore/Volo/Abp/SettingManagement/EntityFrameworkCore/SettingManagementDbContextModelBuilderExtensions.cs#L34

**Comment by maliming** [comment]
Agree.
