### ISSUE TITLE
Swagger API documentation not working

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#1047]
~~Since the HTTP API Module is a separate project which does not copy documentation XML to the host project, Swashbuckle Swagger API XML documentation does not work anymore.~~

~~My suggestion would be to set up some post build step that copies the XMLs to the host project. This would work if the projects are in the same solution. Of course now the question raises how to include such documentation from e.g. IdentityHttpApiModule, which is not in the same solution as the host...~~

Well thanks to @Goxiaoy this is partly solved. I can now include documentation across *my own* modules, but like stated earlier this does not work with external modules like e.g. IdentityHttpApiModule.

**Comment by KidoPlay** [comment]
Why don't we use this
`options.SwaggerEndpoint($"/{module}/swagger.json", module);`

Then we can have them in different specs.

**Comment by hikalkan** [comment]
>Of course now the question raises how to include such documentation from e.g. IdentityHttpApiModule, which is not in the same solution as the host.

I've no idea about that. Swashbuckle somehow should provide a way of this. If someone has experience, it is appreciated.

**Comment by Goxiaoy** [comment]
@Trojaner  You should enable the xml generation  for all the projects where you documented, usually like Application, Application.Contracts, HttpApi. And then include xml comments in SwaggerGenOptions.
And I wrote a  simple function in my case.

Install Package ```Microsoft.Extensions.PlatformAbstractions```

```
        static void AutoScanXmlComments(SwaggerGenOptions options, string pattern)
        {
            var basePath = PlatformServices.Default.Application.ApplicationBasePath;
            //Find XML Comments File In Pattern
            Regex reg = new Regex(WildcardToRegex(pattern));
            var comments = Directory.GetFiles(basePath, "*.*", SearchOption.TopDirectoryOnly)
                .Where(p => reg.IsMatch(Path.GetFileName(p))).ToList();
            foreach (var comment in comments)
            {
                options.IncludeXmlComments(comment);
            }
        }

        public static string WildcardToRegex(string pattern)
        {
            return "^" + Regex.Escape(pattern).Replace("\\*", ".*").Replace("\\?", ".") + "$";

        }

```

```
context.Services.AddSwaggerGen(
                options =>
                {
                    //...
                    AutoScanXmlComments(options, "YourNamespace.*.xml");

                });
```

**Comment by Trojaner** [comment]
Thanks @Goxiaoy . There was also another issue that prevented the HttpAPI module copying it's XML to the host project (the name of the XML file was wrong). This issue can now be considered fixed.
