### ISSUE TITLE
Does Cascade Delete Work for Soft Delete?

### ISSUE THREAD

**Issue by Sean-Fang** [abpframework/abp#10473]
### GitHub Issues

* Your **ABP Framework version**:4.4.0
* Your database provider(EF Core/MongoDB): EF Core, MySQL
* Steps needed to **reproduce** the problem.
  * Entity **A**: implement FullAuditedAggregateRoot(ISoftDelete),
  * Entity **B**: implement FullAuditedAggregateRoot(ISoftDelete)
  * Relation: A.HasMany(x => x.Bs)
                     .WithOne(x => x.A)
                     .HasForeignKey(x => x.AId)
                     .IsRequired()
                     .OnDelete(DeleteBehavior.Cascade);
  * Both implement an **EfCoreRepository<XXXXXXDbContext, A/B, Guid>**
  * Call IRepository.DeleteAsync() for A, A is deleted then B is not.
### Question
Does cascade-delete work for soft delete? If yes, do I miss something in above scenario?

Currently I delete A using below way 
```
 A a = await _aRepository.GetAsync(id,includeDetails:true);
a.Bs.Clear();
await _contractRepository.DeleteAsync(a);
```
I notice that in this issue, https://github.com/abpframework/abp/issues/9366#issue-924032396 , cascade-delete works for soft-delete (IHasDeletionTime). Is it the same as marking the entity/aggregate root with ISoftDelete interface?

Thank you very much.

**Comment by realLiangshiwei** [comment]
> Does cascade-delete work for soft delete

No, You have to manually delete
