### ISSUE TITLE
How to use built-in functions of mvc controller inside auto api controller?

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10481]
Is there a way to use built-in functions of mvc controller inside auto api controler? And, also,
1) how to access http request data  
2) what is the best practice to return specific status code?

https://docs.abp.io/en/abp/latest/API/Auto-API-Controller

e.g. 
public class PersonAppService : ApplicationService
{
       GetAsync(....) {
            return BadRequest();
       }
}

Thanks!

**Comment by realLiangshiwei** [comment]
I think you should use API controller instead of application service.

**Comment by lht6** [comment]
In this case, how can I generate the client code for API controller? It seems that it can generate client code (C# or JS) only from Application service, not API controller, but I could be wrong. Thanks.
