### ISSUE TITLE
Abp io Identity Module Angular How to download Module on my project

### ISSUE THREAD

**Issue by alaawahbah** [abpframework/abp#10487]
Hi folk I need to implement customization on identity module in angular as:

Abp io Identity Module Angular How to download Module on my project to implement my own process. eg. add my own grid or style or custom popup or checkbox?

Please I need all available solutions. like overwrite Css or others.

Thanks.

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/UI/Angular/Customization-User-Interface
