### ISSUE TITLE
How to  generate the client code from API controller instead of Application servcie?

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10482]
It seems that Abp can generate client code (C# or JS) only from Application service, not API controller.
Is there a way to generate the client code for API controller? What could be the best practice in Abp Framework?
Thanks.

**Comment by realLiangshiwei** [comment]
Dynamic client proxies (c# and js) relies on an endpoint on the server that is provided by the ABP Framework: api/abp/api-definition.

You can check the source code to understand how it works: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApiExploring/AbpApiDefinitionController.cs
