### ISSUE TITLE
Microservice sample doesn't merge api definition for Auto API controllers

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10483]
I tried to follow the microservice sample to merge api definition. But it seems that abp only merges definitions for controllers, not for Auto API controller. Is it possible to merge api definition for them as well?

[https://github.com/abpframework/abp/blob/ace4b5526eb00d0ed6429834693fc618dc6c54b2/samples/MicroserviceDemo/gateways/BackendAdminAppGateway.Host/BackendAdminAppGatewayHostModule.cs#L138-L146](url)
 app.MapWhen( 
     ctx => ctx.Request.Path.ToString().StartsWith("/api/abp/") || 
            ctx.Request.Path.ToString().StartsWith("/Abp/"), 
     app2 => 
     { 
         app2.UseRouting(); 
         app2.UseMvcWithDefaultRouteAndArea(); 
     } 
 );

**Comment by realLiangshiwei** [comment]
Please read: https://github.com/abpframework/abp/issues/9405#issue-927954738
