### ISSUE TITLE
Entity Extension property UI and API ignored

### ISSUE THREAD

**Issue by fileman** [abpframework/abp#10480]
* ABP Framework version 4.4.3 & 5.0.0 beta2
* Blazor Server UI

Following this https://docs.abp.io/en/abp/latest/Module-Entity-Extensions I have added a boolean property to IdentityUser.
Then I try to remove it from client UI & API with:
`user.AddOrUpdateProperty<bool>(
                        StaffMemberConsts.IsStaffMember, //property name
                        property =>
                        {
                            property.UI.OnCreateForm.IsVisible = false;
                            property.UI.OnEditForm.IsVisible = false;
                            property.Api.OnCreate.IsAvailable = false;
                            property.Api.OnUpdate.IsAvailable = false;
                        });`

but UI visibility and Api avalability doesn't work as expected, since the property still remain visible in UI and available in API

**Comment by maliming** [comment]
hi

Can you share the project?

**Comment by fileman** [comment]
hi, 
while I'm creating new project to share with same extension code of my solution, I've found that this issue is not present in new project, I have sended you email with projects.

Could the upgrade from 4.3 to 4.4 be the cause?

**Comment by maliming** [comment]
> Could the upgrade from 4.3 to 4.4 be the cause?

I think you can compare the code of your project and the new project.

**Comment by fileman** [comment]
Before open this issue I have created new solution with same name, paste in main solution and compared git difference, I cant find any difference.

The last check I could do is the opposite, which is to paste the current code into the new solution... I'll update when I'm done

**Comment by fileman** [comment]
The reverse check helped, I have found the problem.
I have added the property even to Dto so settings was bypassed.
Thanks
