### ISSUE TITLE
SignalR Hub is registered twice (due to own Module in the same project) - causing unambiguous routing

### ISSUE THREAD

**Issue by davidzwa** [abpframework/abp#10484]
-- **EDIT: see my question on multiple modules in the same project below** --

* Your 4.4.3
* UI irrelevant (tried with HTML, Postman and Angular) - CORS is not an issue
* DB ORM: EF Core
* **Problem description**
I'm not able to prevent `UpdateHub` to register twice (incorrectly) when autoregistering it with the ABP SignalR module
* Exception message:
```
[09:41:21 ERR] (Microsoft.AspNetCore.Server.Kestrel) Connection id "0HMCRF2LD5701", Request id "0HMCRF2LD5701:00000002": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

/signalr-hubs/update/negotiate
/signalr-hubs/update/negotiate
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[09:41:21 INF] (Microsoft.AspNetCore.Hosting.Diagnostics) Request finished HTTP/1.1 OPTIONS http://localhost:5000/signalr-hubs/update/negotiate?negotiateVersion=1 - - - 500 0 - 195.3443ms
```
* Steps needed to **reproduce** the problem.
- Add `AbpAspNetCoreSignalRModule` to my Http API project
- Add hub (`UpdateHub` see it below)
- Call the signalr hub, resulting in correct CORS response on `http://localhost:5000/signalr-hubs/update/negotiate?negotiateVersion=1`
- Get the unambiguous routing error (because 2 instances of the hub are incorrectly registered)

* Example hub
```
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;
using Volo.Abp.AspNetCore.SignalR;

namespace Teamsite.Hubs
{
    public class UpdateHub : AbpHub
    {
        public override async Task OnConnectedAsync()
        {
            await Groups.AddToGroupAsync(Context.ConnectionId, "SignalR Users");
            await base.OnConnectedAsync();
        }

        public override async Task OnDisconnectedAsync(Exception exception)
        {
            await Groups.RemoveFromGroupAsync(Context.ConnectionId, "SignalR Users");
            await base.OnDisconnectedAsync(exception);
        }

        public Task SendMessage(string user, string message)
        {
            return Clients.All.SendAsync("ReceiveMessage", user, message);
        }
    }
}
```

* Additional debugging within the ABP SignalR Module:
What is visible from the next debugging screenshot is that the `UpdateHub` is somehow registered twice in the service collection:
![image](https://user-images.githubusercontent.com/6005355/139525150-caf9bac0-f250-4cf4-b5b8-8173313fd7ca.png)

* Additional debugging on endpoint configuration:
From the following screenshot it is visible that the endpoint is indeed registered twice (resulting in 4 SignalR endpoints, where only 2 are expected)
![image](https://user-images.githubusercontent.com/6005355/139524852-71b57932-7cc2-466d-b573-5617904c39c2.png)

- [x] I have tried running the .NET Core SignalR example **succesfully**
- [x] I have removed all my tenants and disabling multi-tenancy (just to be sure it wasnt a multitenancy issue)

I'm running the API with the problem occurring and these depended modules:
```
    [DependsOn(
        typeof(TeamsiteApplicationModule),
        typeof(TeamsiteApplicationContractsModule), // Should split off to Teamsite.Api and Teamsite.Api.Host
        // typeof(RugbyScraperModule),
        // typeof(TeamsiteBackgroundWorkersModule),
        typeof(TeamsiteEFCoreDbMigrationsModule),
        typeof(AuthenticationModule), // Jwt Bearer & claims
        typeof(AbpAutofacModule),
        typeof(AbpAuthorizationModule),
        typeof(AbpAspNetCoreSerilogModule),        
        // typeof(AbpAspNetCoreMultiTenancyModule),
        // typeof(AbpAspNetCoreMvcUiMultiTenancyModule),
        // typeof(AbpIdentityHttpApiModule),
        // typeof(AbpPermissionManagementHttpApiModule),
        // typeof(AbpTenantManagementHttpApiModule),
        typeof(AbpAspNetCoreSignalRModule)
    )]
```

**Comment by davidzwa** [comment]
I have found that by removing dependency on **my own AuthenticationModule** (which is in the same project as my Http API module) the problem goes away.
Are we not allowed to have multiple modules in the same project?

In any case, feel free to close this issue.

**Comment by maliming** [comment]
> I have found that by removing dependency on my own AuthenticationModule (which is in the same project as my Http API module) the problem goes away.

Can you share the code of this module? I don't know why it causes this problem.

**Comment by davidzwa** [comment]
@maliming I've emptied the `AuthenticationModule` module completely (nothing in the DependsOn array and nothing in the PreConfigureService, ConfigureServices and OnApplicationInitialization methods).

The problem occurred with that situation. So I was able to reproduce it just now with this module:
```
namespace Teamsite.TestModule
{
    [DependsOn()]
    public class TestModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
        }

        public override void ConfigureServices(ServiceConfigurationContext context)
        {
        }

        public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            
        }
    }
}
```

My API module has the following dependson structure:
```
    [DependsOn(
        typeof(TeamsiteApplicationModule),
        typeof(TeamsiteApplicationContractsModule),
        typeof(RugbyScraperModule),
        typeof(TeamsiteBackgroundWorkersModule),
        typeof(TeamsiteEFCoreDbMigrationsModule),
        typeof(AbpAspNetCoreAuthenticationJwtBearerModule),
        typeof(AbpAutofacModule),
        typeof(AbpAuthorizationModule),
        typeof(AbpAspNetCoreMultiTenancyModule),
        typeof(AbpAspNetCoreSerilogModule),
        typeof(AbpAspNetCoreMvcUiMultiTenancyModule),
        typeof(AbpIdentityHttpApiModule),
        typeof(AbpPermissionManagementHttpApiModule),
        typeof(AbpTenantManagementHttpApiModule),
        typeof(TestModule.TestModule),
        typeof(AbpAspNetCoreSignalRModule)
    )]
```

I think there is some duplication happening somewhere in the ABP auto-registration logic.

**Comment by maliming** [comment]
Can you share a simple project?

**Comment by davidzwa** [comment]
Will try!

**Comment by davidzwa** [comment]
@maliming Ive literally reduced my solution to just the http API with a SignalR hub

[Teamsite-private.zip](https://github.com/abpframework/abp/files/7452532/Teamsite-private.zip)
This ZIP contains the project (TeamsiteAPIModule, program.cs, UpdateHub and TestModule)

1) Run it
2) POST to the following (I'd use Postman as I removed CORS)
http://localhost:5000/signalr-hubs/update/?negotiateVersion=1
3) Get the error
```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

/signalr-hubs/update
/signalr-hubs/update
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Host: localhost:5000
Content-Length: 0
Postman-Token: 776844f3-4b06-4607-bd7d-5d4a50bd1954
```

I think this proves that it is somewhere in the ABP modularization/dependency-registration for hubs. It seemed like custom logic anyway, and I did not see any checks/filters for deduplication of AbpHub type instances.
I hope I've given you the simplest example.
