### ISSUE TITLE
ABP.IO CLI: Trying to use create an application from a custom template using templates\app folder from the repo

### ISSUE THREAD

**Issue by radrad** [abpframework/abp#10486]
I cloned https://github.com/abpframework/abp to D:\abp
I am following documentation: https://docs.abp.io/en/abp/latest/CLI-New-Command-Samples

I want to create MVC UI, Entity Framework Core, no mobile app, using the template in D:\abp\templates\app directory.
So I want to use:
-custom template
-local ABP framework references

I wanted to make a simple change inside this page:
D:\abp\templates\app\aspnet-core\src\MyCompanyName.MyProjectName.Web\Pages\Index.cshtml
from:  &lt;h1>Welcome to the Application&lt;/h1> to &lt;h1>Welcome to the MY NEW APPLICATION&lt;/h1>
I issued this command:
D:\TestApps>abp new Acme.BookStore -t app -csf true -u mvc -d ef --tiered -separate-identity-server --no-random-port --connection-string "Server=localhost;Database=Test;Trusted_Connection=True" --template-source 
D:\abp\templates\app --local-framework-ref --abp-path D:\abp

It seems that abp.io cli requires a .specific version of .zip file to be here: D:\abp\templates\app\ and theres folder needs to be zipped in app-4.4.3.zip:
-angular
-aspnet-core
-react-native

Is this intentional? Should the documentation mentioned that we need to zip folder for a particular type of starter template?

My stackoverflow question:
[ABP.IO CLI: Trying to use create an application from a custom template using templates\app folder from the repo](https://stackoverflow.com/questions/69795545/abp-io-cli-trying-to-use-create-an-application-from-a-custom-template-using-tem)

Here is the error:
[05:56:38 INF] ABP CLI (https://abp.io)
[05:56:39 INF] Version 4.4.3 (Stable)
[05:56:40 INF] Creating your project...
[05:56:40 INF] Project name: Acme.BookStore
[05:56:40 INF] Template: app
[05:56:40 INF] Tiered: yes
[05:56:40 INF] Database provider: EntityFrameworkCore
[05:56:40 INF] Connection string: Server=localhost;Database=TestRenaming;Trusted_Connection=True
[05:56:40 INF] UI Framework: Mvc
[05:56:40 INF] GitHub Abp Local Repository Path: D:\abp
[05:56:40 INF] Template Source: D:\abp\templates\app\
[05:56:40 INF] Output folder: D:\TestApps\Acme.BookStore
[05:56:41 INF] Using local template: app, version: 4.4.3
[05:56:41 ERR] Could not find file 'D:\abp\templates\app\app-4.4.3.zip'.
System.IO.FileNotFoundException: Could not find file 'D:\abp\templates\app\app-4.4.3.zip'.

**Comment by realLiangshiwei** [comment]
Yes, you needed. this is the design by CLI

**Comment by radrad** [comment]
@realLiangshiwei I would suggest you to add some explanation to this doc page: 
[ABP CLI - New Solution Sample Commands](https://docs.abp.io/en/abp/latest/CLI-New-Command-Samples) that the command expects at least one .zip with versioning like: app-4.4.3.zip

`abp new Acme.BookStore -t app -u mvc --mobile none --database-provider ef --template-source "c:\MyProjects\templates\app"`

BTW. Does ABP.IO CLI just unzips the the archive and Replaces MyCompanyName and MyProjectName strings withind folder and file names as well as content files with Desired Project name (MyCompany.MyProject or MyCompany.MyProject.MyApp

Is there a way I can debug abp.io cli when creating a new application or module? 
Thanks.

**Comment by realLiangshiwei** [comment]
You can check the source code to understand how it work:https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/NewCommand.cs

＞Is there a way I can debug abp.io cli when creating a new application or module?

You can download the repo and debug the source code.

**Comment by thanhtai9606** [comment]
It not working when I create by custom my template with this row
![2023-03-02_09-35](https://user-images.githubusercontent.com/4544983/222316511-bcd7e54a-7d1a-4f6c-b8aa-d51f436b3860.png)
