### ISSUE TITLE
How can I get source in angular for identity (user and roles)

### ISSUE THREAD

**Issue by alaawahbah** [abpframework/abp#10491]
Hi folks,
How can I get source code in angular project for identity (user and roles)

`abp get-source identity angular`

thanks

**Comment by realLiangshiwei** [comment]
You can download it: https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages/identity

**Comment by alaawahbah** [comment]
OK i know that, you mean i need to get files and put it in my code? then how to use it?
