### ISSUE TITLE
Same file with different names can cause DI error.

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#10504]
Abp version: 4.4.3

I have an IOrderService file in *.Contracts project, and I inject it to other app service.
When I change IOrderService to IOrderAppService (following ABP DOCS best practice) this issue occuered.
I only modified the file name. 
```
public interface IOrderService : IApplicationService {...}

public class OrderService : ApplicationService, IOrderService {...}

public class OtherAppService
{
  public OtherAppService(IOrderService ..) {..}
}
// works well above codes

// but following code throw DI exception
public interface IOrderAppService : IApplicationService {...}

public class OrderService : ApplicationService, IOrderAppService {...}

public class OtherAppService
{
  public OtherAppService(IOrderAppService ..) {..}
}

```
![微信图片_20211103094743](https://user-images.githubusercontent.com/19605145/139999827-31ddb9ce-40b1-436a-b9f9-c967d49a6469.png)

**Comment by realLiangshiwei** [comment]
Change `OrderService ` to `OrderAppService `

**Comment by trickyrat** [comment]
@realLiangshiwei  OrderService implements IOrderAppService  itself works well, this issue cause in injecting into other AppService only. So AppService should be same name as IAppService, if I want inject it into other app servce?

**Comment by gterdem** [comment]
ApplicationServices are automatically [registered by convention](https://docs.abp.io/en/abp/latest/Dependency-Injection#exposed-services-by-convention). 
Your **IOrderAppService** will be resolved to implemented **OrderAppService** by name. If you want to manually register, you can use:

```
public override void ConfigureServices(ServiceConfigurationContext context)
    {
        //Register a factory method that resolves from IServiceProvider
        context.Services.AddTransient<IOrderAppService>(
            sp => sp.GetRequiredService<OrderService>()
        );
    }
```
You can check [Dependency Injection documentation](https://docs.abp.io/en/abp/latest/Dependency-Injection) for more information.
