### ISSUE TITLE
eShopOnAbp: Remove Multi-tenancy

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#10510]
We decided to remove multi-tenancy and related code pieces with it since it will not be required or used for this sample.

**Comment by TronActive** [comment]
I am very interested in this. I went down the road of removing multi-tenancy of ABP Commercial Microservice template and had to back out of it since I had a TON of issues with removing it because it is so baked into ABP.

**Comment by muratyuceer** [comment]
I wish you hadn't removed it. It would be a good example.

**Comment by tungchau** [comment]
What a pity! Without multi-tenancy, this project is just something in the middle of eShopOnContainer and eShopOnDapr.

**Comment by gterdem** [comment]
Maybe this is misunderstood.
The sample had **Tenant-Management** as a microservice (**saas**). This service was providing some sort of **vendor** registration and login for backoffice application and we decided to remove it.
- We're not removing **TenantId** properties from existing modules.
- If you want to add it back, you can check the steps in the PR and add it back to your fork.

Thank you for your interest, I hope it makes sense.

**Comment by dicksonkimeu** [comment]
Hi, multi tenant is the whole essence of abp. eShopOnContainer does the same. Its missing multitenant only
