### ISSUE TITLE
Lazy resolve services in the base classes

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1052]
Currently, base classes (like `ApplicationService`, `AbpController`) property-injects some commonly used services. However, in case of not using them they are being injected unnecessarily. We can lazy resolve them from `IServiceProvider`. 

Example:

Current, in `ApplicationService`:

````csharp
public ICurrentTenant CurrentTenant { get; set; }
````

Suggested:

````csharp
public ICurrentTenant CurrentTenant => LazyGetRequiredService(ref _currentTenant);
private ICurrentTenant _currentTenant;
````

This implementation requires `LazyGetRequiredService` like this (a better naming can be suggested):

````csharp
protected TService LazyGetRequiredService<TService>(ref TService reference)
{
    if (reference != null)
    {
        return reference;
    }

    lock (ServiceProviderLock)
    {
        if (reference != null)
        {
            return reference;
        }

        reference = ServiceProvider.GetRequiredService<TService>();
        return reference;
    }
}
````

And this requires:

````csharp
public IServiceProvider ServiceProvider { get; set; }
protected readonly object ServiceProviderLock = new object();
````

**Comment by acjh** [comment]
Alternative implementation:

```c#
protected TService LazyGetRequiredService<TService>(ref TService reference)
{
    if (reference == null)
    {
        lock (ServiceProviderLock)
        {
            if (reference == null)
            {
                reference = ServiceProvider.GetRequiredService<TService>();
            }
        }
    }

    return reference;
}
```

**Comment by hikalkan** [comment]
@acjh this would be cleaner :)

**Comment by Trojaner** [comment]
I am not sure how feasible it is, but this could be done automatically by runtime patching such properties (you can think of it like invocation interception for properties).

You could then use something like this:
```cs
[LazyServiceResolve]
public ICurrentTenant CurrentTenant { get; set; }
```

This would require less code to be written by the developer.
I am not sure if the current IoC implementations allows you to patch it like this. Worst case, this can be done using libraries like [Harmony](https://github.com/pardeike/Harmony).

**Comment by hikalkan** [comment]
We don't want to make it complicated by using interception (which does not work in some cases and has small performance penalty) or use 3rd party libraries to avoid some small amount of code in a few specific classes.

**Comment by hikalkan** [comment]
Fixed by https://github.com/abpframework/abp/issues/1052
