### ISSUE TITLE
Q: RAM usage

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#10526]
Is this normal, that .HttpApi deployment (with Swagger "visualization") without usage (requests to REST API) uses at least 250/300MB of RAM?
These deployments are inside Kubernetes and all images (containers) are build (Dockerfile) on Alpine Linux - so minimal storage and memory footprint.
My friend also said that deploy of REST API (based on abp.io) uses 250MB+ of RAM on Microsoft IIS 10 without doing any requests to API.

**Comment by maliming** [comment]
You can use a memory analysis tool to check, I think it is normal.
