### ISSUE TITLE
API response 500 internal server error when passing Bearer token

### ISSUE THREAD

**Issue by EddieChinZJ** [abpframework/abp#10529]
* Your **ABP Framework version** 
* 4.4.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Razor/MVC
* Your database provider(EF Core/MongoDB)
* EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Hi,

I deployed my application on AWS beanstalk but I'm facing a problem with APIs.
When I request /api/identity/users or other APIs with the bearer token returned from connect/token, the response is always 500 internal server error.

However, this works perfectly fine with localhost.

Really appreciate if you have some hints for me. 
Thank you.

**Comment by gterdem** [comment]
Share the internal server error logs please. IdentityServer logs as well if you have tiered application. It should be under `Logs` folder in your application or the console logs of your web-server.

**Comment by EddieChinZJ** [comment]
> Share the internal server error logs please. IdentityServer logs as well if you have tiered application. It should be under `Logs` folder in your application or the console logs of your web-server.

Hi @gterdem , Thank for your reply. This is a screenshot of the log.
![image](https://user-images.githubusercontent.com/29214909/140603208-08894d3f-c57c-4887-aae3-c0aeba822046.png)

**Comment by gterdem** [comment]
The problem seems related with reaching identityserver at `localhost:44386`. It is high probably related with your identityserver not running under **https** or invalid https certificate.

To see exact error you can disable PII as shown [here](https://stackoverflow.com/a/55869925).
