### ISSUE TITLE
TransactionBehavior Auto not creating db transaction for ApplicationService methods using Blazor Server

### ISSUE THREAD

**Issue by highshields** [abpframework/abp#10528]
Abp Framework 4.4.2
Blazor Server
EF Core

If an ApplicationService method is called from Blazor Server UI (for example a button click event, in process call, not http api) a db transaction IS NOT CREATED even if AbpUnitOfWorkDefaultOptions.TransactionBehavior is set to Auto and method name doesn't start with "Get".

This seems to be caused by AspNetCoreUnitOfWorkTransactionBehaviourProvider.IsTransactional incorrectly returns false due to HttpContext.Request.Method == "GET" (Request.Path in this case was "/_blazor"). If in process call is made, HttpContext should not be considered at all.

If the method is called using the http api (for example using Swagger UI), the transaction IS CREATED as expected.

The tested method is called ApproveVersion and the class inherits ApplicationService.

**Comment by maliming** [comment]
I will check this.
