### ISSUE TITLE
Don't replace the System.Text.Json with Newtonsoft.Json

### ISSUE THREAD

**Issue by diennttlu** [abpframework/abp#10549]
When I am trying to deserealize data from body json can't convert DateTime
![image](https://user-images.githubusercontent.com/36124566/140686083-07d75ea1-e743-46ec-ae40-13f297ecdad8.png)

![image](https://user-images.githubusercontent.com/36124566/140685544-336adeda-26fe-4118-b9e7-8383a31cda13.png)

I've added  services.AddControllers().AddNewtonsoftJson(); to Startup.cs 
and it doesn't change anything

Abp Framework v4.4.3

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/latest/JSON

**Comment by diennttlu** [comment]
I am creating an Api for Telegram bot to call
WebhookController: 
![image](https://user-images.githubusercontent.com/36124566/140734733-ba6b1b44-ea3a-4b2f-bf81-9e20229a822d.png)

Data form body:
{
    "date": 1636083705,
}

The "date" property has a unixtimestamp data type. When sending request it cannot convert to DateTime data type. I've added services.AddControllers().AddNewtonsoftJson(); to replace the ![System.Text.Json with Newtonsoft.Json](https://github.com/TelegramBots/Telegram.Bot/issues/865). 
I tried it on a simple .net-core web app and it worked fine. On Abp Framework it throws an exception "The JSON value could not be counverted to System.DateTime".

**Comment by qwinmen** [comment]
Возможно кому-либо поможет, столкнулся с этой же проблемой, подружить abp и telegram бота удалось так:
(Maybe i can help someone, get this trouble. My decision: )
```
Configure<AbpSystemTextJsonSerializerOptions>(options =>
{
	//AbpHybridJsonInputFormatter.SystemTextJsonInputFormatter не может обработать атрибуты модели Telegram.Bot.Types.Update, используем NewtonsoftJsonInputFormatter:
	options.UnsupportedTypes.Add(typeof(Update));
});

Configure<MvcNewtonsoftJsonOptions>(options =>
{
	//Используем дефолтную Newtonsoft реализацию вместо AbpMvcJsonContractResolver:
	options.SerializerSettings.ContractResolver = new DefaultContractResolver();
});
```

**Comment by Y2zz** [comment]
If using .NET6 JToken should be changed to JsonNode
https://zhuanlan.zhihu.com/p/388545891
