### ISSUE TITLE
Authorization is working over https but not over http

### ISSUE THREAD

**Issue by AhmadSawalhah** [abpframework/abp#10543]
My auth. policy is working fine if I use Https, but if I use http, the user is logged in but he can't view the page content, it redirects him to the page
http://mydomain/Account/Login?ReturnUrl=%2Fadmin%2F
if I use https, it opens the page successfully

my log file says:
Authorization failed. These requirements were not met:
PermissionRequirement: JobPortal.Admins

where JobPortal.Amins is defined  as:

```
 public static class Admins
        {
            public const string Default = GroupName + ".Admins";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
```
my database role is "admin"
any help

**Comment by maliming** [comment]
hi

Maybe this will help
https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n
