### ISSUE TITLE
Add multitenancy to the "Tenant" entity

### ISSUE THREAD

**Issue by 1d0n7kn0w** [abpframework/abp#10545]
I want to implement IMultiTenant to the "Tenant" entity. Is that possible?
I don't want to add the property "TenantId" by extending the entity, because I will lose all the mechanisms that abp.io does in the background to manage IMultiTenant entities

**Comment by maliming** [comment]
This is not as designed, but you can download the source code of the module to customize it.

**Comment by 1d0n7kn0w** [comment]
@maliming making the "Tenant" class partial can be a solution, what do you think?

**Comment by maliming** [comment]
I am not sure, you can give it a try.
