### ISSUE TITLE
[Angular] Application layout Empty show Navbar a few milliseconds

### ISSUE THREAD

**Issue by begandroide** [abpframework/abp#10544]
Hi! I has an issue with the Navbar:

when I want to use layout of type `ApplicationLayout.Empty`, happens that the Navbar is showed shortly.

* **ABP Framework version**: `4.4.2`
* Angular UI `12.0.0`
* EF Core

## Steps to reproduce the problem

1. Create an empty layout in router provider

How can I prevent this? I don't want to show the Navbar in this page and current behavior is not pretty, thanks in advance.

![navbar-issue](https://user-images.githubusercontent.com/22018004/140628168-3ea5e9fc-b598-4178-a56c-cda6f83c0599.gif)

**Comment by mehmet-erim** [comment]
Hello @begandroide

The problem has been fixed. v4.4.4 will be released soon.
Thanks for the reporting.

**Comment by begandroide** [comment]
wonderfull, thanks you @mehmet-erim !
