### ISSUE TITLE
About TPrimaryKey in CreationAuditedEntityDto<TPrimaryKey>

### ISSUE THREAD

**Issue by Y2zz** [abpframework/abp#1055]
I don't think it has any meaning.

![image](https://user-images.githubusercontent.com/252604/56752688-6d313f00-67bb-11e9-93f2-31e57bded1bb.png)

**Comment by Y2zz** [comment]
If the User ID is of type long, CreatorId will be invalid

**Comment by acjh** [comment]
So don't make it of type long.

**Comment by hikalkan** [comment]
TPrimaryKey is for your entity, not for user entity. User entity's PK should always be Guid.

**Comment by Y2zz** [comment]
@hikalkan   In fact, I prefer to use GUID, but I think it should be more thorough since it provides a generic primary key.
