### ISSUE TITLE
consume twice when published a  message by rabbitMq distributed event bus

### ISSUE THREAD

**Issue by akinix** [abpframework/abp#1056]
# How to reproduce?
- run rabbitmq
```shell
docker run -d --hostname my-rabbitmq --name my-rabbitmq -p 5671:5671 -p 5672:5672 -p 15672:15672 -p 15671:15671 -p 25672:25672 rabbitmq:3-management-alpine
```
- open solution `samples\RabbitMqEventBus\RabbitMqEventBus.sln`
- input `A` in console of `App1`
- output twice in console of `App2`
```shell
************************ INCOMING MESSAGE ****************************
A
**********************************************************************

************************ INCOMING MESSAGE ****************************
A
**********************************************************************
```

# Where is the problem?
- the method `Initialize()` be called twice
  - the method `Initialize()` be called in the constructor of `RabbitMqDistributedEventBus`
  - the method `Initialize()` be called in the `OnApplicationInitialization` of `AbpEventBusRabbitMqModule`
- the method `Subscribe(Type eventType, IEventHandlerFactory factory)` be called twice, the same factory  be add twice
![20190426091351](https://user-images.githubusercontent.com/16933380/56777386-d2a91e00-6803-11e9-962e-0800e0e404f5.png)

# How to fix
## Simple way
remove the `Initialize();` from the constructor of `RabbitMqDistributedEventBus`
i used this way and this bug was fixed.
## Safe Complicated way
check the factory, dot add when same factory.

**Comment by hikalkan** [comment]
I implemented both.
