### ISSUE TITLE
publish the message on specific queue using DistributedEventBus

### ISSUE THREAD

**Issue by umar-daraz-techverx** [abpframework/abp#10576]
If I want to attach _distributedEventBus.PublishAsync to a specific queue, how do I do that?
I have 3 queues running at once: one is for email, one is for in-app notifications, and the third is for document processing.
Does IDistributedEventBus support publishing a message to a specific queue or channel if I have only one console app running in the background?
right now according to the documentation I don't think so is there any support for that

**Comment by maliming** [comment]
You can set custom info in `eventData`, and rewrite the publishing code.
