### ISSUE TITLE
Abp 5.0 beta 3 has an initialization problem when updating to .Net 6.0 

### ISSUE THREAD

**Issue by yupingyong** [abpframework/abp#10587]
* ABP Vnext 5.0 beta 3
* MVC
* EF Core
* Exception message and **stack trace** if available (check the logs).
`Unhandled exception. Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Volo.Abp.Data.AbpDataModule, Volo.Abp.Data, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.InvalidOperationException: Could not find singleton service: Microsoft.Extensions.Configuration.IConfiguration, Microsoft.Extensions.Configuration.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionCommonExtensions.GetSingletonInstance[T](IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionConfigurationExtensions.GetConfiguration(IServiceCollection services)
   at Volo.Abp.Data.AbpDataModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Program.<Main>$(String[] args) in D:\MyProject\gateway\src\Pterosaur.Gateway.Hosting\Program.cs:line 19`
* Steps needed to **reproduce** the problem.
*

**Comment by maliming** [comment]
Steps needed to reproduce the problem.

**Comment by yupingyong** [comment]
@maliming Hello,Here are the steps to start my project.
1. Open the project 
![图片](https://user-images.githubusercontent.com/29831143/141036107-46f825e1-a620-4e7f-8a19-b9e7f5837149.png)
2. F5 start project 
![图片](https://user-images.githubusercontent.com/29831143/141036208-eea44892-cf9a-41db-b1d9-71ba429ce21b.png)

**Comment by yupingyong** [comment]
> 
> 
> Steps needed to reproduce the problem.

**Comment by maliming** [comment]
Try `builder.Services.ReplaceConfiguration(builder.Configuration);`

**Comment by yupingyong** [comment]
@maliming Thank you for your help, my problem has been solved.

**Comment by yupingyong** [comment]
The problem has been resolved.

**Comment by nebula2** [comment]
Am I missing something? I get another exception >.<

```csharp
using MinApiTest;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.ReplaceConfiguration(builder.Configuration);
builder.Services.AddApplication<MinApiTestHttpApiClientModule>();


var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
       new WeatherForecast
       (
           DateTime.Now.AddDays(index),
           Random.Shared.Next(-20, 55),
           summaries[Random.Shared.Next(summaries.Length)]
       ))
        .ToArray();
    return forecast;
});

app.Run();

internal record WeatherForecast(DateTime Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

leads to:
Exception
```
Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Volo.Abp.Http.ProxyScripting.IProxyScriptManager Lifetime: Transient ImplementationType: Volo.Abp.Http.ProxyScripting.ProxyScriptManager': Unable to resolve service for type 'Volo.Abp.Http.Modeling.IApiDescriptionModelProvider' while attempting to activate 'Volo.Abp.Http.ProxyScripting.ProxyScriptManager'.) (Error while validating the service descriptor 'ServiceType: Volo.Abp.Http.ProxyScripting.ProxyScriptManager Lifetime: Transient ImplementationType: Volo.Abp.Http.ProxyScripting.ProxyScriptManager': Unable to resolve service for type 'Volo.Abp.Http.Modeling.IApiDescriptionModelProvider' while attempting to activate 'Volo.Abp.Http.ProxyScripting.ProxyScriptManager'.)
```
Inner:
```
Error while validating the service descriptor 'ServiceType: Volo.Abp.Http.ProxyScripting.IProxyScriptManager Lifetime: Transient ImplementationType: Volo.Abp.Http.ProxyScripting.ProxyScriptManager': Unable to resolve service for type 'Volo.Abp.Http.Modeling.IApiDescriptionModelProvider' while attempting to activate 'Volo.Abp.Http.ProxyScripting.ProxyScriptManager'.
```

**Comment by maliming** [comment]
@nebula2 Try to use `AutoFac`.

**Comment by nebula2** [comment]
> @nebula2 Try to use `AutoFac`.

Sorry for my stupidy :/ can you please explain me how?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/docs/en/Getting-Started-AspNetCore-Application.md

**Comment by nebula2** [comment]
> https://github.com/abpframework/abp/blob/dev/docs/en/Getting-Started-AspNetCore-Application.md

Thank you very much!

this now works:
```csharp
using MinApiTest;

var builder = WebApplication.CreateBuilder(args);


// Add services to the container.
builder.Host.UseAutofac();  //Add this line
builder.Services.ReplaceConfiguration(builder.Configuration);

builder.Services.AddApplication<MinApiTestHttpApiClientModule>();


var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
       new WeatherForecast
       (
           DateTime.Now.AddDays(index),
           Random.Shared.Next(-20, 55),
           summaries[Random.Shared.Next(summaries.Length)]
       ))
        .ToArray();
    return forecast;
});

app.Run();

internal record WeatherForecast(DateTime Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

**Comment by TangFeng** [comment]
`builder.Services.ReplaceConfiguration(builder.Configuration);`
It should be mention at [getting-started-empty-web-project](https://github.com/abpframework/abp/blob/dev/docs/en/Getting-Started-AspNetCore-Application.md) after this issue has been fixed.

@maliming thanks.
