### ISSUE TITLE
Blazor WASM preview template project does not compile

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#10589]
Version="5.0.0-beta.3

Steps: 

1) down-load blazor wasm template (https://abp.io/get-started)
2) build

Errors:
![image](https://user-images.githubusercontent.com/40014477/141044043-1c3e50c7-dac7-48f4-8b7d-e30b652c87a3.png)

**Comment by maliming** [comment]
hi

There should be `NuGet.Config` in your project.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/NuGet.Config

**Comment by 274188A** [comment]
ah - i recently stated to use VS2022 and that nuget source was unchecked - my bad for not catching that
