### ISSUE TITLE
How to set bearer token when calling proxy api?

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10585]
I create a microservice A, and B. In microservice A, it refers to HttpApi.Client project of microservice B, which need authentication. I wonder if there is a way to set bearer token in microservice A, when it calls the HttpApi.Client methods of microservice B?
Thank you!

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/blob/dev/templates/module/aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp/ClientDemoService.cs

**Comment by lht6** [comment]
@realLiangshiwei , thanks for reply. 
It is feasible to set bearer token in HttpClient, and maker a call directly. My question would be how to set bearer token when calling api service. For example, in the above link, inside TestWithDynamicProxiesAsync(), how to set bearer token when calling _sampleAppService.GetAsync(), if it needs authentication.

**Comment by realLiangshiwei** [comment]
Authorization and HTTP request details are handled by the ABP framework
