### ISSUE TITLE
Hangfire Set Retrycount

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#10583]
Is current abstraction support to set job retrycount? How can I set it?

[AutomaticRetry(Attempts = 3)] is not work but

 GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { Attempts = 3 }); working

I need to set work-based

**Comment by realLiangshiwei** [comment]
No, current abstraction does not support to set job retrycount.

You can use hangfire API directly
