### ISSUE TITLE
IAbpMethodInvocation unable to cast object of type

### ISSUE THREAD

**Issue by xsoutline** [abpframework/abp#10592]
https://github.com/abpframework/abp/blob/6051fd4e3886ea05f7f6a04e17d6c0d3fe8471e8/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L66

```C#
public override async Task InterceptAsync(IAbpMethodInvocation invocation)
        {
            var context = new ClientProxyRequestContext(
                await GetActionApiDescriptionModel(invocation),
                invocation.ArgumentsDictionary,
                typeof(TService));

            if (invocation.Method.ReturnType.GenericTypeArguments.IsNullOrEmpty())
            {
                await InterceptorClientProxy.CallRequestAsync(context);
            }
            else
            {
                var returnType = invocation.Method.ReturnType.GenericTypeArguments[0];
                var result = (Task)CallRequestAsyncMethod
                    .MakeGenericMethod(returnType)
                    .Invoke(this, new object[] { context });

                invocation.ReturnValue = await GetResultAsync(result, returnType);
            }
        }
```
`var returnType = invocation.Method.ReturnType.GenericTypeArguments[0];`

This line change the return type,and my project throw error type parsing exception

![image](https://user-images.githubusercontent.com/31274694/141076508-6cb71147-f46e-43e8-99a5-e635f785f903.png)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by xsoutline** [comment]
> * ABP 4.4.3
> * Blazor server and Web API
> * EF Core/SQL Server
> * problem:when return type is generic type,will only return the first generic parameter type.Not expected result.I change the code `var returnType = invocation.Method.ReturnType.GenericTypeArguments[0];` to `var returnType = invocation.Method.ReturnType;`  and then can solve my problem.

source code line is [https://github.com/abpframework/abp/blob/6051fd4e3886ea05f7f6a04e17d6c0d3fe8471e8/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L66](https://github.com/abpframework/abp/blob/6051fd4e3886ea05f7f6a04e17d6c0d3fe8471e8/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L66)
