### ISSUE TITLE
document needs update in Customizing-Application-Modules-Extending-Entities

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#10602]
https://github.com/abpframework/abp/blob/d9504717b25ad6ffd4a24ada0571e1f5b4f19e7e/docs/en/Customizing-Application-Modules-Extending-Entities.md?plain=1#L66

the `AppUser` entity has been removed from `application startup template `, it is better to update this section in the document

**Comment by gterdem** [comment]
Thank you, we'll fix the documentation.
