### ISSUE TITLE
Blazor wasm default template has errors on console

### ISSUE THREAD

**Issue by begandroide** [abpframework/abp#10635]
Hi, recenlty i started to use Blazor UI with abp default template and i has an error and i cant see any logs or issues on console.

* **ABP Framework version**.: 4.4.4
* Blazor webassembly
* EF Core

## Steps to reproduce

Create a default project with Blazor UI using abp.cli

What can be? 

![image](https://user-images.githubusercontent.com/22018004/142062358-3aff78bf-d250-459e-aa95-90a6c200f6ac.png)

**Comment by maliming** [comment]
This is a problem of blazor wasm. If you use Identity Server in the official template project, the same error will also occur, but it does not affect the application, you can ignore it.

![image](https://user-images.githubusercontent.com/6908465/142089459-54400f6b-b5ba-4bd8-87af-1c44d06bb6ea.png)

**Comment by begandroide** [comment]
@maliming thanks you, i didn't test these template first. Did you know that in `5.0.0.rc` the console error is not present? maybe some dependency has solved this.

**Comment by maliming** [comment]
I think this is a design problem of blazor, and this error is still presents in 5.0.
