### ISSUE TITLE
Compile error with angular strictTemplates mode when using value of ABP.Option<T>

### ISSUE THREAD

**Issue by hillin** [abpframework/abp#10639]
* **ABP Framework version**: 4.4.4
* **User Interface**: Angular

```typescript
export enum MyEnum {
  Value0 = 0,
  Value1 = 1
}

export const myEnumOptions = mapEnumToOptions(MyEnum);
```

```html
<select
  id="my-enum-select"
  formControlName="myEnum"
  class="form-select form-control"
  [autofocus]="0">
  <option [ngValue]=""></option>
  <option
    *ngFor="let option of myEnumOptions; trackBy: track.by('key')"
    [ngValue]="option.value"
  >
    {{ '::Enum:MyEnum:' + option.value  | abpLocalization }}
  </option>
</select>
```
(FYI the code above is generated by abp suite CRUD generator)

Creates the following error at compile when `angularCompilerOptions.strictTemplates` is set to `true`:
```
error TS2339: Property 'value' does not exist on type '{ key: any; }'
               [ngValue]="option.value"
                                 ~~~~~
error TS2339: Property 'value' does not exist on type '{ key: any; }'
               {{ '::Enum:MyEnum:' + option.value  | abpLocalization }}
                                            ~~~~~
```

**Comment by hillin** [comment]
For now I can remove the `trackBy: track.by('key')` part as a workaround.

**Comment by mehmet-erim** [comment]
Hello @hillin 

I don't figure out why this happening. But you can use the `trackBy` like follows:

```
trackBy: track.by('value')
```

We will fix the strict mode problems in the next versions. Please follow the issue below:
https://github.com/abpframework/abp/issues/8654

I'm closing this one. If you encounter any other problems, please report them within the issue above.
Thanks!
