### ISSUE TITLE
How to use: Volo.Abp.Ldap

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#10648]
I am wondering how to use Volo.Abp.Ldap module: https://www.nuget.org/packages/Volo.Abp.Ldap/
There is no information in documentation what and where should be configured properly (appsettings.json,....).

I want that users should login via **local** Active Directory (**not Azure AD!**) username and password.
Windows Authentication is not desired.

Thank you for explanations.

P.S.: For MVC UI option

**Comment by maliming** [comment]
You can see https://docs.abp.io/en/commercial/latest/modules/account/ldap

**Comment by leonkosak** [comment]
But this is for commercial abp?

**Comment by maliming** [comment]
Yes.

> The Account PRO module has built-in LdapExternalLoginProvider and OpenLdapManager services. It implements LDAP authentication and gets user info for external login.

https://github.com/abpframework/abp/issues/4977#issuecomment-670006297
