### ISSUE TITLE
[question]how can I use a abp-cli preview version,

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#10642]
I want to use some new option in the cli preview version

for example:
`abp generate-proxy -t csharp -url https://localhost:44302/`

**Comment by xyfy** [comment]
I used it in a solution witch is using abp 5.0-rc1

**Comment by xyfy** [comment]
I used `abp switch-to-preview`  then use `abp generate-proxy -t csharp -url https://localhost:44302/`

**Comment by xyfy** [comment]
![image](https://user-images.githubusercontent.com/7838147/142157219-ad080dd7-2544-499a-b4cc-a129118d3f19.png)

**Comment by xyfy** [comment]
any one can help me ?

**Comment by EngincanV** [comment]
Can you update the CLI version to v5.0.0-rc.1 and re-try it?

```bash
dotnet tool update Volo.Abp.Cli -g --version 5.0.0-rc.1
```

**Comment by xyfy** [comment]
Thanks ,it works !
