### ISSUE TITLE
How to use CosmosDB with Mongo Driver

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#10651]

**Comment by enisn** [comment]
CosmosDB has already Ef Core provider:
https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli

**Comment by enisn** [comment]
Some existing queries from modules may wont work because of https://github.com/dotnet/efcore/issues/16920

**Comment by jhulbertpmn** [comment]
This is most definitely not as easy as switching to the cosmos efcore provider. I spent a tremendous amount of time with this on .net 5 and had issue after issue with queries in the identity server efcore project that would not translate to cosmos without major rework. 
I tried this again with .net 6 and the updated cosmos efcore provider and some of the issues (like defaulting to owned entities) were handled by those updates and did not require the rework of modules that was needed previously. There were still several queries in identity and identity server I had to rewrite but I have a mostly functional instance on cosmos now.

**Comment by enisn** [comment]
New queries and repository operations are able to work properly, but some existing queries from existing modules don't work with Ef Core provider. So Entity Framework provider can wait until being mature SQL API capabilities of Cosmos.

---

So Mongo Driver is the best choice right now.

**Comment by enisn** [comment]
For Build Errors: https://github.com/abpframework/abp/issues/10705
