### ISSUE TITLE
Extend  settings in AbpApplicationConfigurationAppService

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#10654]
Is it possible to extends  AbpApplicationConfigurationAppService and ApplicationConfigurationDto
Explaining more :
we are using settings module to store settings for each country in the system 
where the Provider key is the country Id as below 
![image](https://user-images.githubusercontent.com/78806436/142247681-bfdc0f74-5e68-4d33-9c60-2ae32521b54f.png)

this works fine, it gets the current user setting according to his country, and it fallback to tenant setting if not exists 
and it works also normally in ConfigStateService GetSetting Method  in angular 
but we need to be able to get setting also along with the provider key

is there any way this would be possible to achieve?

**Comment by maliming** [comment]
You can consider rewriting these functions or modules.  They cannot be expanded now.
