### ISSUE TITLE
Abp 5.0.0-rc.1  release source code build error

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#10668]
download version **5.0.0-rc.1**  **zip** source code in [release page](https://github.com/abpframework/abp/releases)

After decompression, enter the `framework` folder

open a terminate in this folder ,run `dotnet build`,got an error **CS0407**

![image](https://user-images.githubusercontent.com/7838147/142390332-6cd58451-0334-4387-9dc2-ce6eb5a2b8d5.png)

![image](https://user-images.githubusercontent.com/7838147/142390475-91c253c1-d790-4f23-8a0a-bec962366235.png)

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/10673
