### ISSUE TITLE
UserFriendlyException not shown if API method return type is "Text"

### ISSUE THREAD

**Issue by GitOPa** [abpframework/abp#10669]
* Your **ABP Framework version**. 4.4.0
* Your **User Interface** type : Angular
* Your database provider EF Core
* Steps needed to **reproduce** the problem.

I had an API that would return a string type value in a normal situation. In a case of exception, I threw an UserFriendlyException. This was visualized as a "Something went wrong" type of message in angular UI. When I wrapped the return value to a Dto object, the message was visualized as expected. The localized string was shown in an error box. I think there might be a bug in the error message interception or is this expected behavior for some reason?

**Comment by maliming** [comment]
hi

Steps needed to reproduce the problem.

**Comment by GitOPa** [comment]
Hi,

- Create an API and AppService method that returns a string type value: public async Task<string> ...
- Make the method throw an UserFriendlyException with some message
- Generate proxies to use the API method
- Create Angular UI -logic that uses the generated proxy service and calls the method that throws the exception
- Expect to see UserFriendlyException's message in an error box but, if there is a bug you should see the generic "Somethin went wrong" message

**Comment by maliming** [comment]
Can you share the response of calling API in PostMan?
