### ISSUE TITLE
Document about UseVirtualFiles Middleware is outdated

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#10667]
https://docs.abp.io/en/abp/5.0/Virtual-File-System#usevirtualfiles-middleware

https://docs.abp.io/en/abp/5.0/Virtual-File-System#static-virtual-file-folders

above two sections about `UseVirtualFiles` is not needed anymore.

**Comment by realLiangshiwei** [comment]
We will update the document, thanks.
