### ISSUE TITLE
How to use Static Proxies?

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#10679]
I created a version `abp 5.0.0-rc1` project from [abp website](https://abp.io/get-started)
![image](https://user-images.githubusercontent.com/7838147/142552603-286bc6d3-b658-44a3-830d-65faab7608d2.png)

it seems using auto proxy , not the new feature  **static proxy**.

![image](https://user-images.githubusercontent.com/7838147/142552950-861e4c39-b466-4ef2-bce9-50e4a02b629c.png)

I want to get a way to use a static proxy document, but I can't find it.

**Comment by realLiangshiwei** [comment]
Hi,

We used dynamic proxy in the template by default because it's out of the box.

Modules use static proxies because we have pre-generated static proxy files. but you are right, we should provide static proxy documentation.

**Comment by xyfy** [comment]
due to #9954, this issue could to be closed
