### ISSUE TITLE
Nodejs 12/14 still recommended as pre-requirement

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#10672]
On the Getting started page (https://docs.abp.io/en/abp/latest/Getting-Started-Setup-Environment) Nodejs 12 or 14 is still recommended but current version of NodeJS is 16 and 17.

Is the documentation in need of update or should we infact use old versions of NodeJS? 

Thanks.

**Comment by maliming** [comment]
If the new version is not breaking, we should be using it.

**Comment by maliming** [comment]
https://support.abp.io/QA/Questions/2130/Angular-app-template-broken#answer-361cf328-e39e-b38a-31f3-3a0035c50686
