### ISSUE TITLE
docs module not work

### ISSUE THREAD

**Issue by dashenxian** [abpframework/abp#1067]
I followed this document to do step 4th, Add-migration Added_Docs_Module and Update-database after the database did not generate DocsProjects table, in Added_Docs_ There is also no code in the Up method in the module file

**Comment by hikalkan** [comment]
Select Acme.MyProject.EntityFrameworkCore.DbMigrations as the default project while running Update-Database

**Comment by dashenxian** [comment]
![QQ截图20190426223758](https://user-images.githubusercontent.com/18696614/56815465-01f77380-6874-11e9-9c76-5501b1269b7f.png)

**Comment by hikalkan** [comment]
Have you added `modelBuilder.ConfigureDocs();` https://cn.abp.io/documents/abp/latest/Modules/Docs#4-1-entity-framework-%E9%9B%86%E6%88%90

**Comment by dashenxian** [comment]
Oh, it's my fault. I'll take builder. ConfigureDoc (); As a builder. ConfigureDocs (); Are they supposed to exist in the OnModelCreating method at the same time, or do they just need builder? ConfigureDocs (); Replace the original builder. ConfigureDoc ();like this
![QQ截图20190427075338](https://user-images.githubusercontent.com/18696614/56841639-96d48e00-68c1-11e9-9d01-8b22b211cf6d.png)

**Comment by dashenxian** [comment]
Now that you have created projects and added a line of records, I fork the ABP project into my account, generate access token, and tick all permissions. However, an error occurred in the run. What does this mistake mean?
![QQ截图20190427083349](https://user-images.githubusercontent.com/18696614/56842745-73aedc00-68cb-11e9-9fac-380a56c3e958.png)
![QQ截图20190427084501](https://user-images.githubusercontent.com/18696614/56842746-77daf980-68cb-11e9-947d-8c220decd653.png)
sql：
INSERT [dbo].[DocsProjects] ([Id], [Name], [ShortName], [Format], [DefaultDocumentName], 
[NavigationDocumentName], [MinimumVersion], [DocumentStoreType], 
[ExtraProperties], [MainWebsiteUrl], [LatestVersionBranchName]) 
VALUES (N'12f21123-e08e-4f15-bedb-ae0b2d939658', N'ABP framework (GitHub)', 
N'abp', N'md', N'Index', N'docs-nav.json', NULL, N'GitHub', 
N'{"GitHubRootUrl":"https://github.com/dashenxian/abp/tree/{version}/docs/zh-Hans/","GitHubAccessToken":"mykey"}', 
N'/', N'master')

**Comment by Webdiyer** [comment]
@dashenxian  sql should be:
INSERT [dbo].[DocsProjects] ([Id], [Name], [ShortName], [Format], [DefaultDocumentName],
[NavigationDocumentName], [MinimumVersion], [DocumentStoreType],
[ExtraProperties], [MainWebsiteUrl], [LatestVersionBranchName])
VALUES (N'12f21123-e08e-4f15-bedb-ae0b2d939658', N'ABP framework (GitHub)',
N'abp', N'md', N'Index', N'docs-nav.json', NULL, N'GitHub',
N'{"GitHubRootUrl":"https://github.com/dashenxian/abp/tree/{version}/docs/zh-Hans/","GitHubUserAgent":"dashenxian","GitHubAccessToken":"mykey"}',
N'/', N'master')
GitHubUserAgent should be your github login name, and replace mykey with your personal access token.

**Comment by dashenxian** [comment]
Thank you very much，It's working
