### ISSUE TITLE
Graph databases support

### ISSUE THREAD

**Issue by 1d0n7kn0w** [abpframework/abp#10688]
Will you support graph databases like Cosmos DB Gremlin API any time soon?

**Comment by realLiangshiwei** [comment]
See:https://github.com/abpframework/abp/issues/10651

**Comment by 1d0n7kn0w** [comment]
EF Core for Cosmos DB supports only SQL API

**Comment by enisn** [comment]
You can use CosmosDB with mongo driver. Most of features will work same as MongoDb

> See:#10651

That article will be about EF Provider of CosmosDb.

**Comment by 1d0n7kn0w** [comment]
There are 5 types of APIs supported by Azure Cosmos DB :
SQL API (Json)
MongoDB API (Bson)
Gremlin API (Graph)
Table API (Key-Value)
Cassandra API (columnar)

SQL API and MongoDB API can be used by abp.io (I guess, I didn't try) but Gremlin API(Graph) and the others are not supported

**Comment by enisn** [comment]
Hi @1d0n7kn0w 
We've published an article about the best way to use Cosmos DB with the ABP Framework. It explains why we can't use SQL API with existing ABP modules:
https://community.abp.io/articles/using-cosmosdb-with-the-abp-framework-via-mongodb-api-x47bjeik


> Will you support graph databases like Cosmos DB Gremlin API any time soon?

In the future, we may create new samples with those databases.
