### ISSUE TITLE
return_url not working in  --tiered blazor-server project

### ISSUE THREAD

**Issue by rwecho** [abpframework/abp#10686]
Created a tiered blazer project. Add a page with the **authorize** attribute, then go to the page in the browser, challenged to the login page. it redirects to the home page.

reproduce:
1. create solution
``` bash
 abp new Acme.BookStore  --dbms mysql --connection-string "Server=localhost;Port=3306;Database=BookStore;Uid=root;Pwd=123456;" -t app --ui blazor-server --tiered
```

2. add authorized razor page, 
``` XML
@page "/test"
@attribute [Authorize]

<h2>Hello test.</h2>
```

3. modify allowed URLs  configuration
```
# appsettings.json in Acme.BookStore.IdentityServer.csproj

    "RedirectAllowedUrls": "http://localhost:4200,https://localhost:44307,http://localhost,https://localhost,https://localhost:44314/"

```
4. run solutions. access https://localhost:44314/test. after login success it won't return /test URL.

Is there anyone in the same situation?

thanks.

**Comment by rwecho** [comment]
It works in the MVC project 

```
abp new Acme.BookStore  --dbms mysql --connection-string "Server=localhost;Port=43306;Database=BookStore;Uid=root;Pwd=123456;" -t app  --tiered 
```

**Comment by maliming** [comment]
I can't reproduce this in v4.4.4
