### ISSUE TITLE
Is the interface "IRepository" after version 5.0.0-rc.1 will not direct support Method "OrderBy" and ”OrderByDescending“

### ISSUE THREAD

**Issue by 32167t** [abpframework/abp#10689]
ABP Framework version
5.0.0-rc.1

User Interface
none

database provider
efcore

question:
My question as same as title, Should I use "IRepository.GetQueryableAsync" instead ?

**Comment by berkansasmaz** [comment]
Yes, that is right.

This article explains along with the reasons => https://github.com/abpframework/abp/blob/dev/docs/en/Blog-Posts/2021-01-14%20v4_2_Preview/POST.md#irepositorygetqueryableasync
