### ISSUE TITLE
Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.

### ISSUE THREAD

**Issue by xiaomazz** [abpframework/abp#10690]
![image](https://user-images.githubusercontent.com/52307384/142716074-08d35caa-36ef-4f98-8092-fa925e24eab0.png)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by xiaomazz** [comment]
EF Core 6.0
AbpVnext 4.4.4

**Comment by xiaomazz** [comment]
为啥同一个版本为啥两个方法不一样(都是abpvnext4.4.4)
![YC29313 S(%XX({`1 {7B J](https://user-images.githubusercontent.com/52307384/142719018-7f298a8b-46c4-4db5-ba0e-17f2b0f17710.jpg)

**Comment by maliming** [comment]
ABP 4.4.4 is targeted to net 5. Please wait for ABP 5.0.
