### ISSUE TITLE
Listservice , how can i accesss sorting,paging filtering without using ngx-datatable

### ISSUE THREAD

**Issue by devilsuraj** [abpframework/abp#10691]
I dont want to use ngx-datatable rather  want to display items more like amazon and sorting , filtering and paging controls will be customized , how can i use listservice to achieve the same , is there any scope for it?

**Comment by mehmet-erim** [comment]
Can you provide more detail?
Did you see [this document](https://docs.abp.io/en/abp/5.0/UI/Angular/List-Service)?

**Comment by devilsuraj** [comment]
> Can you provide more detail? Did you see [this document](https://github.com/abpframework/abp/issues/10691)?

which document , link literally pointing to this question only.

anyways for more details , i can create getlistasync method with paging and sorting parameters and call it anywhere in angular code but since listservice is already doing the same job , i want to use this service rather than writing whole new code for each entity 
e.g. i should be able to bind paging to my custom paging control, sorting to a dropdown or radio butttons etc and list will be shown in div not in table format, or i can use load on scroll kind of thing using same listservice

**Comment by mehmet-erim** [comment]
> which document , link literally pointing to this question only.

Sorry 🤦, I've edited the link.

See a sample:

```ts
import { ListService, PagedResultDto } from '@abp/ng.core';
import { IdentityRoleDto, IdentityRoleService } from '@abp/ng.identity/proxy';
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  template: `
    <div class="container">
      <ul class="list-group">
        <li class="list-group-item">
          <button class="btn" (click)="sort()"><i class="fas fa-sort"></i></button>
        </li>
        <li *ngFor="let role of data.items" class="list-group-item">
          {{ role.name }}
        </li>
      </ul>

      <div id="pagination">
        <ol>
          <button
            *ngFor="let page of [0, 1, 2]"
            class="btn"
            [class.btn-primary]="list.page === page"
            (click)="changePage(page)"
          >
            {{ page + 1 }}
          </button>
        </ol>
      </div>
    </div>
  `,
  providers: [ListService],
})
export class HomeComponent {
  data: PagedResultDto<IdentityRoleDto> = { items: [], totalCount: 0 };

  constructor(public readonly list: ListService, private roleService: IdentityRoleService) {
    // you can change list service defaults here
    this.list.maxResultCount = 5;
  }

  ngOnInit() {
    const streamCreator = query => this.roleService.getList(query);

    this.list.hookToQuery(streamCreator).subscribe(response => {
      this.data = response;
    });
  }

  changePage(page: number) {
    this.list.page = page;
  }

  sort() {
    this.list.sortKey = 'name';
    this.list.sortOrder = this.list.sortOrder === 'desc' ? 'asc' : 'desc';
    this.list.page = 0;
  }
}
```

I hope this helps you.

> If you use ABP Framework v4.x, edit the import path `@abp/ng.identity/proxy` as `@abp/ng.identity`

**Comment by devilsuraj** [comment]
Wow Thanks a lot @mehmet-erim 
I suggest this should be documented on the link you provided

**Comment by nurkmez2** [comment]
@mehmet-erim
Is there any possibility to set page value (For example "this.list.page=5" ) along with the  streamCreator 
const streamCreator = query => this.roleService.getList(query);

Once I set **this.list.page = any number**  it makes another HTTP request, after streamCreator call.
Do you have any advice?
