### ISSUE TITLE
Rest API improvements (2)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#107]
- [ ] Remove version and other assembly specific information from TypeAsString in API description.
- [ ] Consider to pluralize UserAppService (to UsersAppService) and so on... Alternatively, we can consider to pluralize only controller names in url.
- [ ] Return 204 (no content) for void methods on success.

**Comment by neuhausf** [comment]
👍  on pluralization of auto generated (conventional routes). This has always bothered me at aspnetboilerplate.
You can use a method like https://github.com/bricelam/EFCore.Pluralizer/blob/master/EFCore.Pluralizer/Pluralizer.cs
to pluralize your routes. See also https://restfulapi.net/resource-naming/ for proper resource naming.
