### ISSUE TITLE
Why the connection string setting is removed from tenant management

### ISSUE THREAD

**Issue by zhangzunke** [abpframework/abp#10700]
ABP Framework version: 4.4.4
User Interface: Angular
database provider: EF Core

I found that we remove the feature which is the maintenance connection string for a tenant, this is [PR](https://github.com/abpframework/abp/commit/a9d406dbbff68b8693502ceadf1ace42807c681a), so I just wonder to know why the feature is removed, and what I do if I need to configure a connection string, maybe it has another page that can do this. thanks.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/7655#issue-803588821

**Comment by zhangzunke** [comment]
@maliming thanks for your reply, the hikalkan's explanation makes sense, I got it.
