### ISSUE TITLE
In BasicTheme, under the CMS, select2 does not work in the 'Menus'. property for 'Page'

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#10723]
5.0.0-rc.1
MVC
EfCore

![lepton](https://user-images.githubusercontent.com/28866278/143234602-819f2326-230d-4af3-b127-03652a5cea5e.JPG)
![BasicTheme](https://user-images.githubusercontent.com/28866278/143234604-1934a75c-c279-4649-a1be-dc9e479c3047.JPG)

**Comment by enisn** [comment]
Oh, I reproduced the problem. It started to occur after Bootstrap 5 migration

**Comment by enisn** [comment]
It has been fixed with #10729 and will be shipped with next version.
