### ISSUE TITLE
Configure Language for ScriptContributor

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#10721]
* Framework version:4.3.0
* User Interface type:MVC
* Database provider: EF Core

Hi,
I try to set Romanian language` (options.Languages.Add(new LanguageInfo("ro-RO", "ro-RO", "Română", "ro"));`) for `BootstrapDatepicker,Timeago,JQueryValidation` like [here](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Packages/Volo/Abp/AspNetCore/Mvc/UI/Packages/AbpAspNetCoreMvcUiPackagesModule.cs)

In my `ConfigureLocalizationServices `I have set this:
```
Configure<AbpLocalizationOptions>(options =>
	{
		options.AddLanguagesMapOrUpdate(BootstrapDatepickerScriptContributor.PackageName,
				new NameValue("ro-RO", "ro"));
	...

```

Buth here the [GetCurrentUICultureLanguageFilesMap ](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Packages/Volo/Abp/AspNetCore/Mvc/UI/Packages/BootstrapDatepicker/BootstrapDatepickerScriptContributor.cs#L22) method return "ro-RO" code because is use [CultureInfo.CurrentUICulture.Name](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Localization/Volo/Abp/Localization/AbpLocalizationOptionsExtensions.cs#L30)

The problem is that the `libs=>bootstrap-datepicker=>locale` romanian file name is `bootstrap-datepicker.ro.min.js` with the code "**ro**" not "**ro-RO**" like the `GetCurrentUICultureLanguageFilesMap `method return;
The same file code name is for `Timeago,JQueryValidation, Select2...`. (some libraries provide the "ro" code other "ro-RO")
If I rename the `bootstrap-datepicker.ro.min.js` to `bootstrap-datepicker.ro-RO.min.js` is other problem [here ](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/dom-event-handlers.js#L135) because `var language = abp.localization.getLanguagesMap(this.packageName);` return "ro" and this language file is not added in the `BootstrapDatepickerScriptContributor`

How to hendle this case?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Packages/Volo/Abp/AspNetCore/Mvc/UI/Packages/AbpAspNetCoreMvcUiPackagesModule.cs#L21

I don't think there is a problem here.
* Steps needed to **reproduce** the problem.

**Comment by totpero** [comment]
On this [commit](https://github.com/abpframework/abp/commit/6b6e39691f2221cd6971c36602bde82c095aab97) I add Romanian Language with "ro-RO" code, but I see that exists "ro" and "ro-RO" [codes](http://www.lingoes.net/en/translator/langcode.htm) `ro = Romanian` and `ro-RO = Romanian (Romania)`.
If I set abp project to Romanian Language, [here](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Localization/Volo/Abp/Localization/AbpLocalizationOptionsExtensions.cs#L30) the `CultureInfo.CurrentUICulture.Name` return "ro-RO" code but in `libs=>bootstrap-datepicker=>locale` Romanian file name is `bootstrap-datepicker.ro.min.js `with the code "ro" not  `bootstrap-datepicker.ro-RO.min.js `.
We need to rename on this [commit ](https://github.com/abpframework/abp/commit/6b6e39691f2221cd6971c36602bde82c095aab97) in all localization file the code from "culture": "ro-RO" to "culture": "ro".

**Comment by totpero** [comment]
Summernote Romanian Language code is "ro-RO" => https://github.com/summernote/summernote/blob/develop/src/lang/summernote-ro-RO.js

**Comment by maliming** [comment]
Can you share a template project? Thanks

**Comment by totpero** [comment]
Steps to reproduce the problem:

1. Create new abp project and check Preview: 
![image](https://user-images.githubusercontent.com/1710257/143570440-90604b81-99e7-425e-a752-eb6c7fb009c7.png)
2. Change language to Romanian:
![image](https://user-images.githubusercontent.com/1710257/143570689-b4727943-af90-4cee-b5fb-29b6340326b9.png)
3. Check the console if the localization is added:
![image](https://user-images.githubusercontent.com/1710257/143570893-b16bd946-a810-4f1c-9104-f96d0294b52f.png)
4.If you change to zh-Hant Language you see the localization file:
![image](https://user-images.githubusercontent.com/1710257/143573765-143fa8b3-ef7a-4a34-8dfc-3f988660e382.png)

**Comment by maliming** [comment]
Please try to use `AddLanguageFilesMapOrUpdate`.

```cs
  Configure<AbpLocalizationOptions>(options =>
  {
      options.AddLanguageFilesMapOrUpdate(BootstrapDatepickerScriptContributor.PackageName, new NameValue("ro-RO", "ro"));
      options.AddLanguageFilesMapOrUpdate(JQueryValidationScriptContributor.PackageName, new NameValue("ro-RO", "ro"));
      options.AddLanguageFilesMapOrUpdate(TimeagoScriptContributor.PackageName, new NameValue("ro-RO", "ro"));
  });
```
