### ISSUE TITLE
Unable to have custom validation on features

### ISSUE THREAD

**Issue by alexandru-bagu** [abpframework/abp#10724]
Project: Volo.Abp.FeatureManagement
https://github.com/abpframework/abp/blob/56157b3e60540adc0c0ccc7fe00b8005ae02044f/modules/feature-management/src/Volo.Abp.FeatureManagement.Application.Contracts/Volo/Abp/FeatureManagement/JsonConverters/StringValueTypeJsonConverter.cs#L20
https://github.com/abpframework/abp/blob/56157b3e60540adc0c0ccc7fe00b8005ae02044f/modules/feature-management/src/Volo.Abp.FeatureManagement.Application.Contracts/Volo/Abp/FeatureManagement/JsonConverters/ValueValidatorJsonConverter.cs#L48

This implementation does not allow users to add custom `IValueValidator` implementation as they would never be used. The only way to force the system to use the new validators is to replace the instance of `StringValueTypeJsonConverter` like so:

```
Configure<AbpSystemTextJsonSerializerOptions>(jsonSerializerOptions =>
{
    var valueConvertor = jsonSerializerOptions.JsonSerializerOptions.Converters.First(p => p.GetType() == typeof(StringValueTypeJsonConverter));
    jsonSerializerOptions.JsonSerializerOptions.Converters.Remove(valueConvertor);
    jsonSerializerOptions.JsonSerializerOptions.Converters.Add(new CustomStringValueTypeJsonConverter());
});
```

**Comment by maliming** [comment]
> This implementation does not allow users to add custom IValueValidator implementation as they would never be used. 

How do you expect it to work?

**Comment by alexandru-bagu** [comment]
In my specific case I wanted to be able to add a feature that asks the user for a hostname. 
My first issue was that even though I provided a instance of a `IValueValidator ` it was not used. Instead of the name taken from the name attribute was being used to then create another instance.

The easiest way to allow users to have custom validators would be to make it something like this:
```
public class SomeFeatureDefeinitionProvider : FeatureDefinitionProvider
{
    public override void Define(IFeatureDefinitionContext context)
    {
        var webGroup = context.AddGroup("Web");

        webGroup.AddFeature("SomeDomainName",
            defaultValue: "",
            displayName: LocalizableString.Create<SomeResource>("Web.Domain"),
            description: LocalizableString.Create<SomeResource>("Web.Domain.Description"),
            valueType: new FreeTextStringValueType(() => new UrlValueValidator()));
    }
}
```
And this factory would be then used at a later point to create the instance used. I am actually not sure why an instance is being even requested (` new FreeTextStringValueType(new UrlValueValidator())`) when its not going to be used at all.
Or make it so I can inject other validators. I am sure there are many ways to allow users to extend validators.
