### ISSUE TITLE
GetAllBytesAsync returns an empty byte array

### ISSUE THREAD

**Issue by charleszh-dev** [abpframework/abp#10726]
abp version: 5.0-rc1
blob provider: minio
In the file system, it's okay.

**Comment by charleszh-dev** [comment]
step to reproduce:
1. Create  project by abp cli
2. Add the package `Volo.Abp.BlobStoring.Minio` to the *.Host project and add the module dependency
3. Configure AbpBlobStoringOptions to use my Minio
4. Add the package `Volo.Abp.BlobStoring` to the *.Application project and add the module dependency
5. Create an `AppService`, save the file and get bytes through `GetAllBytesAsync`

The file was saved successfully, but an empty Byte array was read, and the `ExistsAsyncmethod` returns true. I think it is the `TryCopyToMemoryStreamAsync` method in the `BlobProviderBase` class that caused this problem

**Comment by JadynWong** [comment]
Sorry, my PR(#10445) caused the problem. I'll fix it.

**Comment by maliming** [comment]
hi @realZhangChi 

Can you check https://github.com/abpframework/abp/pull/10727

**Comment by charleszh-dev** [comment]
> hi @realZhangChi
> 
> Can you check #10727

Ok of course
