### ISSUE TITLE
Blazor WASM load time

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#10725]
* Your **ABP Framework version**. 5.0 beta 3
* Your **User Interface** type Blazor wasm
* Your database provider EF Core

Before I get into the explanation of the behavior I am seeing I would just add up front that I know Blazor WASM's initial load for a site is going to have a minor performance hit because it has to download the necessary framework and application files to the client, so I am not expecting to do away with that entirely of course. 

I have been experimenting with different ways of hosting/deploying my blazor wasm app and associated api on Azure and am comparing performance among 3 options right now. The API in all cases is hosted on Azure App Services and this works very well.

I am hosting the Blazor client app on Azure App Services, Azure Static Web Apps and an Azure CDN endpoint. The App Services case performs the best of the 3 right now (although still seems excessive), which is a little surprising. I've been running some Lighthouse tests through Chrome Dev Tools to see what I can do to improve the load time and wanted to check here before i dig in too far.

In the results below the API is hosted on Azure App Services in all cases (same instance of the api application hit by all Blazor clients).

Blazor Client on Azure App Services
- First contentful paint 1.9s
- Time to interactive 23.7s
- Speed index 13.5s
- Total blocking time 950ms
- Largest contentful paint 24.8s

Blazor Client on Azure Static Web Apps
- First contentful paint 5s
- Time to interactive 22.4s
- Speed index 20s
- Total blocking time 1100ms
- Largest contentful paint 21.2s

Blazor Client on Azure CDN
- First contentful paint 3s
- Time to interactive 22.3s
- Speed index 23s
- Total blocking time 1880ms
- Largest contentful paint 20.7s

I am working with Azure on possible custom settings for caching and compression on the CDN. There aren't many levers on the static web app service itself. I am also considering trying out some lazy assembly loading.

Has anyone dealt with startup performance on blazor wasm? Any tips or suggestions?

**Comment by maliming** [comment]
> I tested the latest (5.0-rc.1) app-pro template by creating a new solution with the blazor WEBASSEMBLY UI. In development, first page load time is ~5 seconds. Most of this duration is related to "dotnet compile on browser" (2+ seconds) and authentication (~2 seconds - talking to the auth server). I could simple remove authentication, it reduces to ~3 seconds. Also, hot reload connection and other development time and blazor-related stuff occurs (tested with visual studio 2022)

>I published with release and hosted under IIS. The initial load time is about ~4 seconds. I published with AOT enabled. Initial load time remains same (or slightly faster), but the application size grows 3 times (Microsoft already says that).

>Also, with the latest template, all modules are using static c# proxies and this eliminates the call to the "api-definition" endpoint. I think it also gains time.

> Finally, I think that's reasonable. Empty microsoft blazor wasm template works much faster, but if someone make a large app as ours, it will be same. I give up blazor performance optimization.

**Comment by jhulbertpmn** [comment]
Certainly the auth calls do take some time, but are necessary. 
The size of the app published with AOT is indeed a trade off. I have not experimented much with that yet. 
I wonder if the static proxies may be worth a try for me. I do see the calls to the api-definition endpoint and they account for about 1.5-2s of the load time between the preflight and actual fetch. I am still running on 5.0 beta 3  so I will try updating to the latest and using static proxies. 
Of course an empty template (or nearly empty) will be very fast and adding actual functionality to it will increase size and load time. ~5 seconds for initial load seems perfectly reasonable. 15+ seconds is not so reasonable. 
I was also considering setting up a separate layout for unauthenticated requests which will load minimal resources for getting the user to the login page (since all of the functionality of our app requires the user to be logged in). Looks like I could make use of lazy loading assemblies that way and get the user to an interactive page more quickly. 
Thanks for the feedback and ideas

**Comment by mandeep-sps** [comment]
Hi Team,

I have a .Net 6 Blazor WASM app with Server Hosted Code. Before Publishing the APP I have added some few Config lines in the project file like this

1. <PropertyGroup>
2.     <TargetFramework>net6.0</TargetFramework>
3.     <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
4.     <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
5.     <PublishTrimmed>true</PublishTrimmed>
6.     <BlazorEnableCompression>true</BlazorEnableCompression>
7.     <InvariantGlobalization>true</InvariantGlobalization>
8.     <TrimMode>link</TrimMode>
9.     
10.   </PropertyGroup>

and Added the Brotli Compression Decoce.js file and some code on the Index.html Page. Now my APP downloads only 1.5 MB of resources and Its loads into 1.5 Secs. SO I have Optimized my app using these settings.

![image](https://user-images.githubusercontent.com/25770082/176853070-bb4cb801-bcc9-4870-b251-a2e571031013.png)

If I am anything missing Please suggest me.

Thanks

**Comment by VivienMAN** [comment]
@mandeep-sps hello,
Do you use the abp Framework ?
Because the loading problem is present only with this framework. This is a consequence of a heavy application with blazor.

An empty project is within the time you give.

**Comment by mandeep-sps** [comment]
Hi, @VivienMAN I am not using ABP Framework for Creating the application. I am using Blazor WASM, .Net 6, and mud Blazor components. For Optimized the Speed of the APP, I added Brotli Compression and some properties in the Proj file.
