### ISSUE TITLE
Recommended approach for removing Blazorise

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#10749]
Your ABP Framework version: 5.0 rc1
Your User Interface: blazor wasm
Your database provider: EF Core

Is there a recommended/best-practice approach to removing/replacing blazorise in the theme? I like the blazorise library a lot, but we also have a commercial license of telerik's blazor component package and are using the grid and several other controls from it, so keeping blazorise creates some redundant functionality and also more resources to load be just using telerik for everything.

**Comment by leonkosak** [comment]
You should rewrite all abp modules (frontend) using Telerik components.
