### ISSUE TITLE
bug:abp-add-new-module-with-seperate-db ,when use different dbms

### ISSUE THREAD

**Issue by lxt2004** [abpframework/abp#10758]
https://blog.antosubash.com/posts/abp-add-new-module-with-seperate-db

where the two dbms is both SqlServer or SQLite it is no problem,
but ,when one is SQLite another is SqlServer post can not work welll.

[12:41:08 ERR] An error occurred using the connection to database '' on server 'D:\t\Ncys\Wireless.db'.
[12:41:08 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
  "details": null,
  "data": {
    "HelpLink.ProdName": "Microsoft SQL Server",
    "HelpLink.EvtSrc": "MSSQLServer",
    "HelpLink.EvtID": "-1",
    "HelpLink.BaseHelpUrl": "http://go.microsoft.com/fwlink",
    "HelpLink.LinkId": "20476"
  },
  "validationErrors": null
}

**Comment by antosubash** [comment]
I think you are using the SqlServer provider to connect to SqlLite db.  I susspect this because of this `"HelpLink.EvtSrc": "MSSQLServer",` Changing the Ef core provider to SqlLite in your module should fix this.

Check here : https://docs.abp.io/en/abp/latest/Entity-Framework-Core-SQLite

**Comment by berkansasmaz** [comment]
Thanks for the comment @antosubash.

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
