### ISSUE TITLE
Tenant per database: cannot get data from tenant database

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#10757]
* Your **ABP Framework version: 4.4
* Your **User Interface** type: Angular
* Your database provider: EF Core

I am using 3.x in a project(tenant per database) and all works fine. 
recently, I want to upgrade to 4.4,  so i used CLI upgrade all the stuff, and created new migrations, everything looks good until i run some case for data testing, I found all the legacy database related API return null. 

In my case, there is a legacy database for each tenant and no tenant id in entity , so I used tenant per database as an option from the beginning, when debugging in 4.4, I found the repository always get data from host database, even the tenant Id is right.

To double confirm, I used a newest template for testing, seems it cannot work too.

is it a bug in 4.4 or we make some changes for tenant per database, do we have a workaround to fix the issue?

[tenant_per_database.zip](https://github.com/abpframework/abp/files/7611511/tenant_per_database.zip)
A testing project is attached.
please insert a record to AppBooks in SmartScanTenant1 database after running migratior
INSERT INTO AppBooks VALUES(NEWID(),'Book1',10.0,'{}',NEWID(),GETDATE(),null,null,null)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/7509

**Comment by evenlee** [comment]
Thanks @maliming, but my goal is to use tenant database, I did not add [IgnoreMultiTenancy] attribute to my dbcontext, why it still get data from host database?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/7509/commits/3f8bf4a2be9cc0aeccfe7605233948de72d78ad9#diff-044d3a88932b37b24a8aebf572e09b7c18be235afcde64e37c2970c78731169eR50-R60

**Comment by evenlee** [comment]
Hmm, it looks like I have to create too much repos which will  inherit my own parent repo which only overrides one method,  @maliming, do we have an elegant way like just replacing the EfCoreRepository  or some magic just change several lines of code?
