### ISSUE TITLE
Create a RemoteStreamContent from a MemoryStream SpreadsheetDocument stay empty

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#10751]
ABP Framework version: 5.0.0-rc1
User Interface: Angular
database provider: EF Core

**1- created a MemoryStream with DocumentFormat.OpenXml SpreadsheetDocument:**

`using var document = SpreadsheetDocument.Create(memoryStream, SpreadsheetDocumentType.Workbook);`

And add my WorkBook, WorkShhet and whatever needed.

**2- Put this MemoryStream on a RemoteStreamContent**

```
document.Save();
document.Close();
var streamContent = new RemoteStreamContent(memoryStream);
```

**Issue:**
The streamContent is empty (ContentLength = 0).

**Note:**
This issue happens after a migration to 5.0.0-rc1, before, with ABP 4.4.3 it was working fine.

**Comment by maliming** [comment]
Can you use other streams to reproduce it?

**Comment by cbaille** [comment]
I try using a file and it works well:
`var memoryStream = new MemoryStream(File.ReadAllBytes("appSettings.json"));`

I even tried using a file I generated by my previous code using SpreadsheetDocument  and RemoteStreamContent on ABP4.4.3 and it works...

`var memoryStream = new MemoryStream(File.ReadAllBytes("WorkReports.xls"));`

**Comment by maliming** [comment]
Can you use other streams to reproduce it in 5.0?

**Comment by cbaille** [comment]
I don't know what other stream I can use actually, let me search more

**Comment by cbaille** [comment]
![image](https://user-images.githubusercontent.com/27866600/143814169-8ccfa91e-32c7-48d6-ae2f-623d2ae56f0d.png)

**Comment by maliming** [comment]
Please share code to reproduce.

**Comment by cbaille** [comment]
```
            var memoryStreamTest = new MemoryStream();
            using var documentTest = SpreadsheetDocument.Create(memoryStreamTest, SpreadsheetDocumentType.Workbook);
            var workbookPartTest = documentTest.AddWorkbookPart();
            workbookPartTest.Workbook = new Workbook();

            var worksheetPartTest = workbookPartTest.AddNewPart<WorksheetPart>();
            worksheetPartTest.Worksheet = new Worksheet(new SheetData());

            var sheetsTest = workbookPartTest.Workbook.AppendChild(new Sheets());
            sheetsTest.AppendChild(new Sheet
            {
                Id = workbookPartTest.GetIdOfPart(worksheetPartTest),
                SheetId = 1,
                Name = "Sheet 1"
            });

            var sheetDataTest = worksheetPartTest.Worksheet.GetFirstChild<SheetData>();
            var headerTest = new Row();
            headerTest.AppendChild(
                new Cell
                {
                    CellValue = new CellValue(_localizer.GetString("Worker")),
                    DataType = CellValues.String
                }
            );
            sheetDataTest.AppendChild(headerTest);

            documentTest.Save();
            documentTest.Close();

            var streamContent = new RemoteStreamContent(memoryStreamTest);
            return streamContent;
```

**Comment by maliming** [comment]
The change of `RemoteStreamContent` is added `disposeStream` paramter.

You can try to set it to `false`.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/Volo/Abp/Content/RemoteStreamContent.cs#L17

**Comment by cbaille** [comment]
I just tried this:

`var streamContent = new RemoteStreamContent(memoryStreamTest, null, null, null, false);`

but still the same issue

**Comment by maliming** [comment]
Please share a project and steps, thanks.

**Comment by cbaille** [comment]
Sure, how can I share it to you?

**Comment by maliming** [comment]
You can share a simple project on GitHub.

**Comment by cbaille** [comment]
run the project, log as admin, then click on MyEntitySet main menu. I put the code which is wrong on the GetListAsync method of MyEntitySetAppService class, at line 65

**Comment by maliming** [comment]
Please make it private.

**Comment by JadynWong** [comment]
You can try set the `memoryStreamTest.Position` to 0 or `memoryStreamTest.Seek(0, SeekOrigin.Begin)`.

**Comment by maliming** [comment]
```cs
memoryStreamTest.Position = 0;
var streamContent = new RemoteStreamContent(memoryStreamTest);
```

![image](https://user-images.githubusercontent.com/6908465/143967679-7206581a-a456-483e-9644-febea1e65080.png)

**Comment by cbaille** [comment]
memoryStreamTest.Position = 0;

It works yes, thanks
