### ISSUE TITLE
Identity management / roles: Add/remove permission do not work properly

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#10774]
ABP Framework version: 5.0.0-rc1
User Interface: Angular
database provider: EF Core

1- Create a new solution
2- Create an entity
3- Go to Administration / Identity Management / Roles and create a new role
3- Add  permission to the role just created and save.
4- Open the permission view again

Result:
If you select/unselect "individual permission", changes are not saved. However, if you select/unselect "Select All" it does work.
This happens to all kind of permission (Audit Logging, Account, ...)

![image](https://user-images.githubusercontent.com/27866600/143835249-18aeca29-90a5-4355-ae8d-ba94e08ba9dd.png)

**Comment by mehmet-erim** [comment]
Hello @cbaille 
I can't reproduce it. Did you check the console, were there any errors? It may be related to that

**Comment by cbaille** [comment]
Nothing on browser console and nothing on the output of VS. I do not see anything special on the log file neither

**Comment by muhammedaltug** [comment]
Hello @cbaille 

Thanks for reporting this issue.  Bugfix will available in the next version.
