### ISSUE TITLE
error on build CustomAngularAppWithIdentityServer/aspnet-core in VS 2022

### ISSUE THREAD

**Issue by hamed-lohi** [abpframework/abp#10779]
when I build 
https://github.com/abpframework/abp-samples/tree/master/CustomAngularAppWithIdentityServer/aspnet-core
projects in VS 2022 get this error :

Error	MSB3491	Could not write lines to file "obj\Debug\net5.0\CustomAngularAppWithIdentityServer.EntityFrameworkCore.DbMigrations.AssemblyInfoInputs.cache". Path: obj\Debug\net5.0\CustomAngularAppWithIdentityServer.EntityFrameworkCore.DbMigrations.AssemblyInfoInputs.cache exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.	CustomAngularAppWithIdentityServer.EntityFrameworkCore.DbMigrations	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets

and has like this error for other projects.

**Comment by maliming** [comment]
> The fully qualified file name must be less than 260 characters.

This is not related to ABP. You can check
https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html

**Comment by hamed-lohi** [comment]
Thank you very much for your attention.
