### ISSUE TITLE
update-database  Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by billpeace** [abpframework/abp#10782]
### Documentation

update-database
Build started...
Build succeeded.
An error occurred using the connection to database '' on server 'localhost'.
MySqlConnector.MySqlException (0x80004005): Access denied for user 'root'@'localhost' (using password: YES)

But 
mysql -u root -p
Enter password:   *****    is  OK
navicat open it       is  OK

### GitHub Issues

https://abp.io/get-started
project is new project   with angular  mysql   

Connection id:          8
Current database:
Current user:           root@localhost
SSL:                    Cipher in use is TLS_AES_256_GCM_SHA384
Using delimiter:        ;
Server version:         8.0.27 MySQL Community Server - GPL
Protocol version:       10
Connection:             localhost via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4
TCP port:               3306
Binary data as:         Hexadecimal
Uptime:                 4 min 52 sec

mysql> select user,host,plugin,authentication_string from user;
+------------------+-----------+-----------------------+------------------------------------------------------------------------+
| user             | host      | plugin                | authentication_string                                                  |
+------------------+-----------+-----------------------+------------------------------------------------------------------------+
| mysql.infoschema | localhost | caching_sha2_password | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED |
| mysql.session    | localhost | caching_sha2_password | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED |
| mysql.sys        | localhost | caching_sha2_password | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED |
| root             | localhost | mysql_native_password | *1D579DCECC9E215CCDF1BBD016681026E9AF5D4A                              |
+------------------+-----------+-----------------------+------------------------------------------------------------------------+
4 rows in set (0.00 sec)

**Comment by billpeace** [comment]
mysql  Ver 8.0.27 for Win64 on x86_64 (MySQL Community Server - GPL)

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Getting-Started-Running-Solution?UI=MVC&DB=EF&Tiered=No#the-initial-migration

**Comment by billpeace** [comment]
I using Visual Studio
Hit F5 (or Ctrl+F5) to run the application  .DbMigrator project 

[10:26:25 INF] Creating initial migration...
'abp' is not an internal or external command, nor is it an executable program
Or batch file.

E:\Project\FirstProject\aspnet-core\src\FirstProject.DbMigrator\bin\Debug\net5.0\FirstProject.DbMigrator.exe (process 19784) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

[https://www.dropbox.com/s/3zyjjg1i8b2yaed/yMfhG1xPwq.png?dl=0](url)

**Comment by maliming** [comment]
> 'abp' is not an internal or external command, nor is it an executable program

```ps
dotnet tool install -g Volo.Abp.Cli
```

**Comment by billpeace** [comment]
I have solved it

the  appsettings.json  in FirstProject.DbMigrator project  Need to be modified
