### ISSUE TITLE
Configurable default MaxResultCount for DTOs

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#1079]
Currently [LimitedResultRequestDto.MaxResultCount](https://github.com/abpframework/abp/blob/f62ed01ac24433dcdc0faf02400fc871caa65dbe/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Dtos/LimitedResultRequestDto.cs#L13) is hardcoded to be 10.
It would be great if this limit would be moved to a static field so it can be configured to application needs.

**Comment by acjh** [comment]
You can already override it.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/a935a52ef54780b2063b2fbc8f10ceb5db7db9fe/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/CrudAppService.cs#L20

You can pass your custom  `TGetListInput(PagedAndSortedResultRequestDto)`

**Comment by Trojaner** [comment]
@acjh  this would mean that I would have to recreate all classes that implement it myself, which means more duplicate code... (currently these classes are LimitedResultRequestDto, PagedAndSortedResultRequestDto, PagedResultRequestDto).

@maliming this means I would either have to write my own CrudAppService base (which means I would also need a reimpementation of AsyncCrudAppService) or that I have to override it in every CRUD app service.

Also both proposed fixed do not make it application wide, e.g. for external modules.

Considering the very small effort for implementing my proposal, I think its not a bad idea.

**Comment by acjh** [comment]
Show your proposed implementation and usage.

**Comment by hikalkan** [comment]
@Trojaner I implemented it. Now, you can just do it at the beginning of your application:

````csharp
LimitedResultRequestDto.DefaultMaxResultCount = 1000;
````

BTW, this parameter is expected to be sent by clients. Because, clients only know the proper page size. This is just a fallback when client doesn't send it.
