### ISSUE TITLE
[MultiTenancy] attribute for DBContext

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#10807]
I am planning to upgrade to 4.4, but found multi-tenant cannot work properly.

We have a case that each tenant has a legacy database and impossible to implement IMultiTenancy interface, we need the legacy dbContext access tenant database but not host by default.  

Thanks @maliming  for explaining the reason  in #10757 ,  with my investigation, the fix requires too much code changes, and I think which is not elegant too.

IMHO,  a [MultiTenancy] attribute on DbContext may solve the issue smoothly, could we please add it? 

And I think there still are much more projects will leverage existing database which cannot implement IMultiTenancy interface, the change will make apb more flexible for some cases.

**Comment by maliming** [comment]
>  cannot implement IMultiTenancy interface

This is by design. You can change or overwrite in your own project.

**Comment by evenlee** [comment]
Thanks @maliming , is it possible to replace EfCoreRepository?

**Comment by maliming** [comment]
Check documents https://docs.abp.io/en/abp/latest/Entity-Framework-Core
