### ISSUE TITLE
Styling problem of dropdowns of docs module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#10802]
See on https://docs.abp.io/

![image](https://user-images.githubusercontent.com/1210527/144178965-5d5359bc-e170-4517-814e-f26a1c2eb0c0.png)

Version and language dropdowns have no down arrow.

**Comment by rqx110** [comment]
![image](https://user-images.githubusercontent.com/1829209/144186580-6ff3cb3b-0031-4f33-90b6-45785ed88751.png)

**Comment by rqx110** [comment]
@EngincanV 
the Version and language dropdowns still have no down arrow!!!

![image](https://user-images.githubusercontent.com/1829209/146291812-4e86f960-f0fd-492c-8cd3-1d64d9124e36.png)
