### ISSUE TITLE
Storage of ExtraProperties in CosmosDB

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#10818]
* Your **ABP Framework version**. 5.0 rc1
* Your **User Interface** blazor wasm
* Your database provider ef core 

I created a few extra user properties following the instructions at https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#more and that all worked as expected.
When I look in my Cosmos DB at a user with some values saved for the extra properties I see the data there though the contents are stored as a string (makes sense for the default behavior of saving to sql or another relational db). Here is an example of the document from Cosmos (I removed some content for privacy and brevity):

{
    "Id": "3a0034df-dc22-1997-2051-dc32bcc6469d",
    "ExtraProperties": "{\"Timezone\":\"America/Los_Angeles\",\"Timezone_Text\":\"America/Los_Angeles\"}", 
    "UserName": "admin", 
    "Claims": [],
    "Logins": [],
    "OrganizationUnits": [],
    "Roles": [
        {
            "RoleId": "3a0034df-e045-20ba-1f20-9d87b9b59359",
            "TenantId": null,
            "UserId": "3a0034df-dc22-1997-2051-dc32bcc6469d"
        }
    ],
    "Tokens": [], 
    "_attachments": "attachments/",
    "_ts": 1638395109
}

Ideally I would like to have ExtraProperties be a json object similar to Roles. It appears I could do this in my ef core configuration (implementing my own TryConfigureExtraProperties extension for the builder) but wasn't sure what the implications might be throughout the application and modules. Would that be the right approach?

**Comment by maliming** [comment]
This is controlled by `ExtraPropertiesValueConverter`.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/ValueConverters/ExtraPropertiesValueConverter.cs#L12

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs#L65
