### ISSUE TITLE
Unit test error: Volo.Abp.AbpException : Undefined feature: Identity.MaxUserCount0

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#10822]
ABP Framework version: 5.0.0-rc1
User Interface: Angular
database provider: EF Core

1- Create a new solution
2- Create an entity
3- Open Test explorer

When I right click on EntityFrameworkCore project and select run, all tests fails with the message

`Volo.Abp.AbpInitializationException : An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module AppRC.AppRCTestBaseModule, AppRC.TestBase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: Undefined feature: Identity.MaxUserCount0`
`---- Volo.Abp.AbpException : Undefined feature: Identity.MaxUserCount0`

NOTE:
This is not every times, but often enoug. It can happens when click on "Run All Tests in View" too.  
I met the issue now that "Run All Tests in View" do not run all tests anymore too, it skip projects...
If run tests one by one, it works well.

I got the error when run on Microsoft DevOps pipeline too

---- Volo.Abp.AbpException : Undefined feature: Identity.MaxUser�

![image](https://user-images.githubusercontent.com/27866600/144374121-155cd9e0-0746-4a2e-ab6d-cdc914b2c219.png)

**Comment by maliming** [comment]
Is it belong ABP commercial?

**Comment by cbaille** [comment]
Yes it does

**Comment by maliming** [comment]
Please get help on https://support.abp.io/

**Comment by sturlath** [comment]
@cbaille can you add the ticket in the support because I'm hitting this and can't find anything with OnApplicationInitializationModuleLifecycleContributor

My error is slightly different

```xml
 Volo.Abp.AbpInitializationException : An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module MyTestBaseModule, My.TestBase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: String reference not set to an instance of a String. (Parameter 's'). See the inner exception for details.
---- System.ArgumentNullException : String reference not set to an instance of a String. (Parameter 's')
```

I added a comment on the 5.0 release [here ](https://support.abp.io/QA/Questions/2209/Bugs--Issues-v5X#answer-d1bca7e8-ce4e-1506-81c0-3a0104baf8df) for interested.

**Comment by cbaille** [comment]
The issue did not happen anymore after I updated to the rc2
