### ISSUE TITLE
Can update  angular project  Created by https://abp.io/get-started

### ISSUE THREAD

**Issue by billpeace** [abpframework/abp#10835]
### Documentation

From https://abp.io/get-started, Create an angular-based project， But angular project cannot install by npm i or yarn

Can update  angular project 

thanks

### GitHub Issues

While resolving: FirstProject@0.0.0
npm ERR! Found: @angular/compiler@12.0.5
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~12.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"12.2.14" from @angular/localize@12.2.14
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^12.0.0" from @ng-bootstrap/ng-bootstrap@10.0.0
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     peer @ng-bootstrap/ng-bootstrap@">=6.0.0" from @abp/ng.components@4.4.4
npm ERR!     node_modules/@abp/ng.components
npm ERR!       @abp/ng.components@"~4.4.4" from the root project

While resolving: @swimlane/ngx-datatable@17.1.0
npm WARN Found: tslib@2.3.1
npm WARN node_modules/tslib
npm WARN   tslib@"^2.1.0" from the root project
npm WARN   46 more (@abp/ng.account, @abp/ng.components, @abp/ng.core, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer tslib@"^1.10.0" from @swimlane/ngx-datatable@17.1.0
npm WARN node_modules/@abp/ng.theme.shared/node_modules/@swimlane/ngx-datatable
npm WARN   @swimlane/ngx-datatable@"^17.1.0" from @abp/ng.theme.shared@4.4.4
npm WARN   node_modules/@abp/ng.theme.shared
npm WARN
npm WARN Conflicting peer dependency: tslib@1.14.1
npm WARN node_modules/tslib
npm WARN   peer tslib@"^1.10.0" from @swimlane/ngx-datatable@17.1.0
npm WARN   node_modules/@abp/ng.theme.shared/node_modules/@swimlane/ngx-datatable
npm WARN     @swimlane/ngx-datatable@"^17.1.0" from @abp/ng.theme.shared@4.4.4
npm WARN     node_modules/@abp/ng.theme.shared

**Comment by bnymncoskuner** [comment]
Hello, 

What is your npm version?

**Comment by billpeace** [comment]
npm version 8.1.4

**Comment by mattdeacon** [comment]
Similar issue here too same version of npm - it just started happening this week out of the blue! Any further thoughts?

**Comment by bnymncoskuner** [comment]
Angular v12.x works with node v14 and npm v6. We haven't updated to angular v13 yet.

**Comment by billpeace** [comment]
I did not  updated to angular v13

**Comment by billpeace** [comment]
I have tested， npm install  is ok works with node v14 and npm v6
