### ISSUE TITLE
How to migrate the database according to the connection string of each tenant?

### ISSUE THREAD

**Issue by afresh** [abpframework/abp#10837]
**ABP Framework version:** 4.4.3.
**Database provider:** EF Core.

**Problem:**
I use the microservice demo. I want to configure each tenant with its own connection string. When I call the API with the tenant, it reports an error that the relationship "AbpUsers" does not exist. I know it is because I did not migrate the database. I want ABP to automatically migrate the database according to the connection string of each tenant at startup. How can I implement it in the microservice demo?

**Comment by realLiangshiwei** [comment]
You can check: https://github.com/abpframework/eShopOnAbp

**Comment by afresh** [comment]
@realLiangshiwei Thanks! Could you be more specific? I didn't find the multi tenant configuration in the eShopOnAbp project.

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/eShopOnAbp/blob/main/services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/DbMigrations/AdministrationServiceDatabaseMigrationEventHandler.cs

**Comment by afresh** [comment]
@realLiangshiwei Thank you very much! I seem to understand.
