### ISSUE TITLE
Blazor server page progress is not working

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#10833]
To test it:

````
@inject IUiPageProgressService pageProgressService

...

<Button Clicked="@StartIntedermine" Color="Color.Primary">Intedermine start</Button>

...

@code
{
    private async Task StartIntedermine()
    {
        await pageProgressService.Go(null);
    }
}
````

See doc: https://docs.abp.io/en/abp/latest/UI/Blazor/Page-Progress

Nothing happens.

**Comment by realLiangshiwei** [comment]
The open-source is no problem but not app pro. I will fix it in the volo repo.

The default color is black, try 

```csharp
await PageProgressService.Go(null, options =>
{
    options.Type = UiPageProgressType.Success;
});
```

![image](https://user-images.githubusercontent.com/16813853/144572987-ddd49334-d37d-4a58-9961-892d6d335109.png)
