### ISSUE TITLE
how to get source of angular project of Create New Project in  https://abp.io/get-started 

### ISSUE THREAD

**Issue by hamed-lohi** [abpframework/abp#10832]
excuse me, i don't find way to ask my question and here asked.
how to get source of angular project of Create New Project in  https://abp.io/get-started ?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/tree/dev/templates/app/angular

**Comment by hamed-lohi** [comment]
Thanks ,
I have one other question, is abp framework seo friendly, specially with angular ?

**Comment by maliming** [comment]
Yes

**Comment by hamed-lohi** [comment]
What method did you use for SEO in Angular?
