### ISSUE TITLE
How to implement a Webhook system

### ISSUE THREAD

**Issue by AlexanderPilhar** [abpframework/abp#10842]
Community Article Request

I'd like to have some guidence about how to implement a proper webhook system in abp.
I want two or more separate abp installations to be able to communicate via webhooks.

I'd really appriciate your help!

**Comment by ebicoglu** [comment]
see https://github.com/abpframework/abp/issues/10844

**Comment by albutta** [comment]
Is this still going to happen :)

**Comment by andmattia** [comment]
@albutta I'm working on this module porting from ABP Bolierplate. @ebicoglu let me know how can I share it

**Comment by albutta** [comment]
This is fantastic news. I would like to see how to implement your into the framework, so that I can share what I have developing a dynamic state machine that can be edited within the web browser.

**Comment by albutta** [comment]
Hello Alper

Thanks for this message, I have been looking forward to this being
implemented into the framework.

Every few weeks I check, and see that it is still in the pipeline, but not
implemented yet.
It's been 4 months now, and can't wait any longer 🤣

How can I get a copy of your code that you used to implement webhooks?
This would me much appreciated

All the best

Regards
Tony
