### ISSUE TITLE
How can i install the blog module?

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1084]
What are the steps to install the blog module? i read somwhere there is a abp cli?

**Comment by hitaspdotnet** [comment]
Use [Docs module installation](https://github.com/abpframework/abp/blob/master/docs/en/Modules/Docs.md)
Blog's installation isn't ready yet.

**Comment by maliming** [comment]
There is no detailed introduction at the moment.

You can run the [Volo.BloggingTestApp](https://github.com/abpframework/abp/blob/master/modules/blogging/app/Volo.BloggingTestApp/BloggingTestAppModule.cs) project launch the blog module locally, and the blog module can also be published. Just like the abp blog: https://abp.io/blog/abp/

Related documentation is (currently not perfect) https://abp.io/documents/

The [CLI](https://github.com/abpframework/abp/blob/master/framework/src/Volo.Abp.Cli/Program.cs) is still under development..

**Comment by hikalkan** [comment]
This is pre-deployed installation document: https://abp.io/documents/abp/latest/Apps/VoloDocs

Closing this issue.

**Comment by hikalkan** [comment]
Sorry, I answered for the docs module. In anyway, CLI will help to install modules. We also will document each module.

**Comment by vnetonline** [comment]
@maliming 

I am not sure what you mean how can I run this app locally ??

**Comment by maliming** [comment]
@vnetonline 
Clone the code then:
```
d:\Github\abp\modules\blogging\app\Volo.BloggingTestApp.EntityFrameworkCore>dotnet ef database update -s ..\Volo.BloggingTestApp
Applying migration '20180621080811_Added_Blog_And_Post'.
....................
Applying migration '20181211141402_AggregateRoot_Changes'.
Done.


d:\Github\abp\modules\blogging\app\Volo.BloggingTestApp>dotnet run
Hosting environment: Development
Content root path: d:\Github\abp\modules\blogging\app\Volo.BloggingTestApp
Now listening on: http://localhost:50017
Application started. Press Ctrl+C to shut down.

http://localhost:50017/account/login
username:admin
password:1q2w3E*

```

![image](https://user-images.githubusercontent.com/6908465/57067019-6e54f580-6d00-11e9-9055-1b5c6c22943d.png)


For some details of the framework you can view the documentation: https://abp.io/documents/

**Comment by vnetonline** [comment]
@maliming sorry to be a pest when you say clone the code you mean the whole repository from the root using the following ?

https://github.com/abpframework/abp.git

**Comment by maliming** [comment]
You can also download the zip file.
https://github.com/abpframework/abp/archive/master.zip

**Comment by vnetonline** [comment]
Just for those reading this thread I used the following document to help me clone the repository on my Mac 

https://help.github.com/en/articles/cloning-a-repository

Thanks for you help @maliming
