### ISSUE TITLE
Host project from Blazor template do not run after upgrade to 5.0.0-rc1

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#10840]
ABP Framework version: 5.0.0-rc1
User Interface: Angular
database provider: EF Core

1- Create a new solution
2- Upgrade to prerelease packages
3- Make this packages changes about being able to build the solution:

     Domain.Shared project:
     Microsoft.Extensions.FileProviders.Embedded 5 to 6

     Replace Framework target Core 5 to 6 to projects who needs

     Blazor: 
     Blazorise.Components 0.9.4.1 to 0.9.5-preview2.1
     Microsoft.AspNetCore.Components.WebAssembly 5 to 6

     ClientDemoService → add reference “using Volo.Abp.Account;”

4- try to run the host project.

I get the error `HTTP Error 500.30 - ASP.NET Core app failed to start`

I see this error on the log file:

```
2021-12-03 15:18:26.656 +07:00 [FTL] Host terminated unexpectedly!
Autofac.Core.DependencyResolutionException: An exception was thrown while activating HealthChecks.UI.Core.Data.HealthChecksDb.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1[HealthChecks.UI.Core.Data.HealthChecksDb])' on type 'HealthChecksDb'.
 ---> System.TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'Microsoft.EntityFrameworkCore.InMemory, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.EntityFrameworkCore.InMemory.Infrastructure.Internal.InMemoryOptionsExtension.get_Info()
   at Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at lambda_method21(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
```

I then updated

EntityFramework: Microsoft.EntityFrameworkCore.Tools 5 to 6 on EntityFrameworkCore project but still remain the same

**Comment by ebicoglu** [comment]
1. stop your running projects
2. reference the https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.InMemory the latest version
3. delete all bin & obj folders 
4. try running again

**Comment by cbaille** [comment]
I added this line to EntityFrameworkCore.csproj, even if I do not have any reference anywhere about Microsoft.EntityFrameworkCore.InMemory before:

    `<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.*" />`

Now I got another error:

```
System.MissingMethodException: Method not found: 'Void Microsoft.EntityFrameworkCore.MutablePropertyExtensions.SetValueComparer(Microsoft.EntityFrameworkCore.Metadata.IMutableProperty, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer)'.
   at HealthChecks.UI.Core.Data.Configuration.HealthCheckExecutionEntryMap.Configure(EntityTypeBuilder`1 builder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.ApplyConfiguration[TEntity](IEntityTypeConfiguration`1 configuration)
   at HealthChecks.UI.Core.Data.HealthChecksDb.OnModelCreating(ModelBuilder modelBuilder)
....
```

**Comment by cbaille** [comment]
I shared you the solution

**Comment by JoseMaZ530** [comment]
any response?..

**Comment by cbaille** [comment]
I made the project running by commenting the line about HealthCheck on HttpApiHostModule class:

ConfigureHealthChecks(context);

So the upgrade might affect that part?

**Comment by maliming** [comment]
hi

Try to use the RC packages of `HealthChecks`.

```
<PackageReference Include="AspNetCore.HealthChecks.UI" Version="6.0.1-rc2.4" />
<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="6.0.1-rc2.4" />
<PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="6.0.1-rc2.4" />
```

**Comment by cbaille** [comment]
It runs well now thanks :)
As it is RC packages, should it be used temporarily only?

**Comment by maliming** [comment]
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/845#issuecomment-965587546
