### ISSUE TITLE
Installer of the `Volo.Users` module is faulty

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#10845]
https://github.com/abpframework/abp/blob/ee23e33cb39f336ef0655476e2c3a3246b83b3fe/modules/users/src/Volo.Abp.Users.Installer/Volo/Abp/Users/UsersInstallerPipelineBuilder.cs#L14-L17

The above line of code adds the following line of code to the `MyProjectName.EntityFrameworkCore` project.

`            builder.ConfigureAbpUser();
`

However, `ConfigureAbpUser` method can be used with `EntityTypeBuilder<TUser>` so build error occurs.

<img width="1680" alt="Screen Shot 2021-12-03 at 14 08 20" src="https://user-images.githubusercontent.com/31216880/144592705-ac631dca-c1a6-40af-9c51-00facc427458.png">

```text
Build failed. Use dotnet build to see the errors.
/Users/berkan/Desktop/Tests/rc-1/Acme2.BookStore/src/Acme2.BookStore.EntityFrameworkCore/EntityFrameworkCore/BookStoreDbContext.cs(95,21): error CS1061: 'ModelBuilder' does not contain a definition for 'ConfigureAbpUser' and no accessible extension method 'ConfigureAbpUser' accepting a first argument of type 'ModelBuilder' could be found (are you missing a using directive or an assembly reference?) [/Users/berkan/Desktop/Tests/rc-1/Acme2.BookStore/src/Acme2.BookStore.EntityFrameworkCore/Acme2.BookStore.EntityFrameworkCore.csproj]

The build failed. Fix the build errors and run again.
```

**PS:** I tested the CLI by compiling it on my own computer.

**Comment by maliming** [comment]
@cotur Can you check this?
