### ISSUE TITLE
Quote block bottom padding problem in docs module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#10850]
See this:

![image](https://user-images.githubusercontent.com/1210527/144753203-718b76eb-b511-4f92-acfa-f7cdcaf8329d.png)

Taken from https://docs.abp.io/en/abp/latest/UI/Blazor/Error-Handling

I suppose this is related to BS 5.x upgrage. Please fix it in rel-5.0 branch.

**Comment by EngincanV** [comment]
Blockquote styling problem will be fixed with https://github.com/abpframework/abp/pull/10808
