### ISSUE TITLE
How to use volo.abp.cli in Ubuntu?

### ISSUE THREAD

**Issue by qaniqani** [abpframework/abp#10851]
Hello, I am using Linux Ubuntu 20.04.

I installed the CLI with the command "sudo dotnet tool install -g Volo.Abp.Cli".

But I couldn't find how to run "abp login email@address.com" command. When I looked with the "dotnet tool list", I couldn't find it in the downloads.

![image](https://user-images.githubusercontent.com/19714568/144756016-07c392a5-f4f4-4a70-b4e8-9faa5abd0a1c.png)

"dotnet tool list" image as in the picture.
![image](https://user-images.githubusercontent.com/19714568/144756045-bffbdf5d-4573-45e9-92c6-4d753c553a05.png)

We can't run our app because I can't log in.
Is there a solution to this problem or another way we can log in?

![image](https://user-images.githubusercontent.com/19714568/144756167-83b0acc1-0227-412a-a81f-b23c99141933.png)

Regards.

**Comment by maliming** [comment]
hi

![image](https://user-images.githubusercontent.com/6908465/144771539-ed331633-da17-49ba-9eaf-21201abfa754.png)
```
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"
```

**Comment by qaniqani** [comment]
Thnx dude, that's exactly what I needed!
It works perfectly.

**Comment by a0m0rajab** [comment]
We had a similar issue when we used dotnet from snap, we removed the snap version and redownloaded dotnet to solve our issue by following the next steps: 

https://github.com/dotnet/sdk/issues/34590#issuecomment-1910808405
