### ISSUE TITLE
[Document Translation] getting started web translation - Chinese

### ISSUE THREAD

**Issue by Gsonovb** [abpframework/abp#10852]
hello everyone

I updated the "getting started web application" document translation  at https://github.com/Gsonovb/abp/commit/8027c4691d045291b19ec5b77dc64273b47bbaba

Where do I post it? thank you.

**Comment by realLiangshiwei** [comment]
Hi,

Thanks, you can send a PR.

**Comment by Gsonovb** [comment]
HI,

I send PR  https://github.com/abpframework/abp/pull/10853

Please check, thank you
