### ISSUE TITLE
Cannot find module '@abp/ng.core'

### ISSUE THREAD

**Issue by mkydouglas** [abpframework/abp#10868]
Hello guys!

My Angular Abp project isn't find the module '@abp/ng.core'. I'm trying to access it to use the PermissionService.

The project is up to date.

Look the image.

![image](https://user-images.githubusercontent.com/40704841/144861004-280bd10e-995c-4eb6-a271-fc970a490ba4.png)

Thanks!

**Comment by mehmet-erim** [comment]
Hello @mkydouglas

If you run the following command, your problem probably be resolved:

```
yarn add @abp/ng.core
```

I'd like to learn installed packages in your app to understand is there any problem. Can you run the following command and share the result?

```
yarn list --pattern abp
```

Thanks!

**Comment by mkydouglas** [comment]
Hello @mehmet-erim 

Thanks for your help!

The results from your request is:
![image](https://user-images.githubusercontent.com/40704841/145214779-8ce1bbb7-7ccd-49c7-8653-11a87e69c76e.png)

**Comment by mehmet-erim** [comment]
I assume your problem is resolved. I am closing this one. If you will encounter any problems, feel free to create a new issue or ask a question on the [StackOverflow](https://stackoverflow.com/questions/tagged/abp).
