### ISSUE TITLE
How to insert and query across services in microservices?

### ISSUE THREAD

**Issue by afresh** [abpframework/abp#10862]
**ABP Framework version: 4.4.4**
**Database provider: EF Core**

**Questions:**
In the `EShopOnAbp` project, I want to insert an order when ensuring the existence of user A, and query the order by the name of user A. And I want to update the order when I inserting a payment. If it's a single application, I know how to implement it. How to implement it in microservices?

**Comment by maliming** [comment]
hi

https://docs.abp.io/en/commercial/latest/startup-templates/microservice/interservice-communication

**Comment by afresh** [comment]
@maliming Thank you for sharing the link. it solves my problem.
