### ISSUE TITLE
SignInManager does not work

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#1087]
I have tried both, SignInManager\<IdentityUser\> and SignInManager\<AppUser\> but both can not be resolved when using via dependency injection.

Example:
```cs
public XXXXController(SignInManager<IdentityUser> signInManager)
{
      ...
}
```

If you ask why I need SignInManager, I need it for [external authentication via OpenIddict](https://github.com/openiddict/openiddict-core/blob/7bb2cd9522a0669de64629546a598d7f53854b51/samples/Mvc.Server/Controllers/AuthorizationController.cs).

**Comment by hikalkan** [comment]
It is resolved in the account module, for example: https://github.com/abpframework/abp/blob/master/modules/account/src/Volo.Abp.Account.Web/Pages/Account/AccountPageModel.cs#L15
(used property injection here, but constructor injection also works).

How can we reproduce it, from a new MVC application template?

**Comment by Trojaner** [comment]
I will try to make a minimal reproduction.
