### ISSUE TITLE
Overriding GetDbContextAsync method can't work

### ISSUE THREAD

**Issue by zhangzunke** [abpframework/abp#10876]
**ABP Framework version: 4.4.4**
**Database provider: EF Core**

I want to get data from the Tenant database instead of the Host database since the Book entity doesn't inherit the IMustTenant interface, so I need to override the method to ensure that always get data from the Tenant database.

I create an EfCoreBookRepository class to override it, the weird thing is that I can't override the method successfully when I use the below code, the following code always get data from the Host database, and the method which I override is never executed.
```
var booksQuery = _bookRepository.Where(x => x.CreationTime >= DateTime.Now.AddDays(-180));
var queryResult1 = await AsyncExecuter.ToListAsync(booksQuery);
```
But the following code works well and the overriding method can be executed.
```
var queryable = await _bookRepository.GetQueryableAsync();
var query = queryable.Where(x => x.CreationTime >= DateTime.Now.AddDays(-180));
var queryResult = await AsyncExecuter.ToListAsync(query);
```

My question is why the first method can't work, maybe it isn't good practice.

```
public class EfCoreBookRepository
        : EfCoreRepository<SmartScanDbContext, Book, Guid>, IBookRepository
    {
        private readonly IDbContextProvider<SmartScanDbContext> _dbContextProvider;

        public EfCoreBookRepository(
            IDbContextProvider<SmartScanDbContext> dbContextProvider)
            : base(dbContextProvider)
        {
            _dbContextProvider = dbContextProvider;
        }

        protected override Task<SmartScanDbContext> GetDbContextAsync()
        {
            return _dbContextProvider.GetDbContextAsync();
        }
    }
```

**Comment by maliming** [comment]
You also need to override the methods and properties of `IQueryable`

See https://github.com/abpframework/abp/pull/10136/

**Comment by zhangzunke** [comment]
@maliming Thanks for your suggestion, I try to find the IQueryale properties, I found there is a property named **Provider** ,  the code as below:
```
[Obsolete("This method will be removed in future versions.")]
public virtual IQueryProvider Provider => GetQueryable().Provider;
```
So I try to override the **GetQueryable** method, the code as below:
```
[Obsolete]
protected override IQueryable<Book> GetQueryable()
{
    var dbContext = _dbContextProvider.GetDbContext();
    return dbContext.Books.AsQueryable();
}
```
Now I can get the Tenant data through the first method, however, it seems like the method will be removed in the coming version, maybe I need to use the second approach to get data, it should be a suggested pattern.
