### ISSUE TITLE
abp add-package Template is empty

### ISSUE THREAD

**Issue by BeiMeng** [abpframework/abp#10872]
ABP Framework version 4.4.4.

ABP Cli version 4.4.4.  also update current new

abp add-package Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic --with-source-code --add-to-solution-file 
Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic Template download is empty

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by BeiMeng** [comment]
use abp cli
1.run abp new Acme.BookStore -t app -u angular -m none --separate-identity-server
2. to Acme.BookStore.IdentityServer.csproj folder
3. run abp add-package Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic --with-source-code --add-to-solution-file
4. Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic project is empty, because Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic Template download is empty

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/144998389-832c9538-cf30-4de7-84d6-7a995420c228.png)

**Comment by maliming** [comment]
hi
You can use `abp get-source Volo.BasicTheme` command to get source code of the module.
