### ISSUE TITLE
How to configure WrapResult in Abp IO

### ISSUE THREAD

**Issue by stousmand** [abpframework/abp#10874]
Hi I'm currently using Abp IO v4.4.4. And I managed to follow the documentation and examples to use Abp IO for a backend service application. I've seen that there is an attribute called WrapResult where the response of a REST api is wrapped with some additional fields that are used for error and paging etc. (could find StackOverflow questions about previous Abp versions on this). Is there a way to configure this in Abp IO? if so where and how could it be done? Thanks.

**Comment by maliming** [comment]
hi

There is no `WrapResult` exist in ABP IO.  Your results will not be wrapped by default, you can implement it yourself in the MVC filter.

**Comment by stousmand** [comment]
Okay, thank you @maliming. I'll check
