### ISSUE TITLE
Authorization between different modules

### ISSUE THREAD

**Issue by zhangzunke** [abpframework/abp#10897]
**ABP Framework version : 4.4.4**
 **Your database provider: EF Core**

I have a monolith structure with two modules Module A and Module B, each module can be consumed by SAP,  Module A and Module B  have their own application services AppServiceA and AppServiceB, they need different permission.

The scenario is if I want to access the AppServiceB method in the AppServiceA, there is a permission issue since the current user only has the AppServiceA service permission. 

The question how can I ignore the permission check for AppServiceB when the request comes to AppServiceA, I don't want to check the permission in the scenario.

I know we can use the in-process events to do that, maybe we have a best practice for the scenario.

**Comment by afresh** [comment]
See https://github.com/abpframework/abp/issues/9322#issuecomment-861487841 .
I haven't tried yet. Can you try it?

**Comment by zhangzunke** [comment]
@afresh  Maybe the solution can't meet my requirements, AppServiceB still needs to be added permission checked since it will be consumed by SAP, so I can't create a subclass to replace it and add the AllowAnonymous attribute.

I just want to ignore the permission check when it is used by another module service, add still keep the permission check when it is used as restful API by a client, maybe the requirment is weird.
