### ISSUE TITLE
returnUrl Not Working After Successful Login

### ISSUE THREAD

**Issue by wjamieson** [abpframework/abp#10899]
ABP Version: 4.4.0
UI: Blazor Server
Browser: Tested on Firefox and Chrome

Scenario: A user tries to access an Authorized page when not logged in, and are correctly redirected to the login page. However when they enter correct credentials with valid permissions, they are taken to the standard index.razor page, not the original page they tried to access. The returnUrl query parameter is automatically populated when they are taken to the login screen, so if working correctly they should be taken back to that URL.

Steps to recreate:
1. Create and deploy a new Blazor Server ABP solution.
2. Navigate to an Authorized page, i.e "[domain]/identity/users"
    - User is redirected to Login page, note returnUrl is present in query params
4. Login
   - User is taken to the standard index.razor page, not back to /identity/users.

Am I missing some configuration or is this a bug?

Any help would be greatly appreciated!

**Comment by realLiangshiwei** [comment]
Hi,

I will check it.

**Comment by realLiangshiwei** [comment]
It's a problem, we will fix it.

For now, you can try:

`appsettings.json`
```json
  "App": {
    "SelfUrl": "https://localhost:44313",
    "RedirectAllowedUrls": "https://localhost:44313" // add this line
  },
```

```csharp
Configure<AppUrlOptions>(options =>
{
     //.......
    options.RedirectAllowedUrls.AddRange(configuration["App:RedirectAllowedUrls"].Split(','));
});
```

**Comment by wjamieson** [comment]
@realLiangshiwei I'll try this. Thanks for replying so quickly!
