### ISSUE TITLE
How to create your own claim principals to populate CreatorId, LastModifierId, DeleterId

### ISSUE THREAD

**Issue by stousmand** [abpframework/abp#10895]
Hi currently I'm using Abp IO 4.4.4 and I've configured it to use an auth (OIDC) server that is not the Identity server that comes with Abp IO. The gap I have to bridge here is I need to get the User from a custom data sources that I've created instead of AbpUser and once the Bearer token introspection is done a principal is created (please correct me if I'm wrong). My goal is to set the audit fields such as CreatorId etc. which at the moment would not populate in my custom entities.

Is there a way to do a custom implementation of the principal creation where I could use my own user data sources to get this working

I've tried these
1. https://github.com/abpframework/abp/issues/42#issuecomment-576025862
2. [Claims Principal Factory](https://docs.abp.io/en/abp/4.4/Authorization)

Most of them are suggestions on adding claims to an existing principal or there was one where you could change the principal. But seems like none of them work. Appreciate the help.

**Comment by maliming** [comment]
This is more related to your `auth (OIDC) server`. It controls the content in claims(tokens)

**Comment by stousmand** [comment]
@maliming thanks, I understand that but my question is, the claims that are sent from the auth are mapped to a principal object on Abp IO right? So I'm asking is there some kind of extension or handler or some other method where we could customize that mapping... or implement a custom Principal creation on Abp?

**Comment by maliming** [comment]
ABP uses Microsoft's `UseAuthentication` middleware. You can check its document. 

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-6.0
