### ISSUE TITLE
eShopOnAbp: web application api-configuration dependency

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#10905]
Angular app needs to get `localization` and `permission` information from api-configuration end-point. 
This request is re-routed to administration service (https://github.com/abpframework/eShopOnAbp/blob/d6ba98c098e2158933da2ede06370f846b871a64/gateways/web/src/EShopOnAbp.WebGateway/appsettings.json#L49).

Since AdministrationService doesn't have reference to other microservices' `Application.Contracts` module, it can not obtain related localization/permission info.

We can:
- reference to all other microservice application contracts from **AdministrationService** but this will tightly couple AdministrationService to all other services
- reference to all other microservice application contracts from **WebGateway** but it will also make it harder to replace gateways with different tech stack.
- try to find a static way for api-configurations just like api-proxy

**Comment by NecatiMeral** [comment]
Couldn't you just use the [Request Aggregation](https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html) feature of ocelot to merge the `localization` and `permission` informations?

**Comment by gterdem** [comment]
> Couldn't you just use the [Request Aggregation](https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html) feature of ocelot to merge the `localization` and `permission` informations?

We can take a look at that. However we will need to do the same if we decide to change the gateway to envoy (or something else).

Thanks for the suggestion, I'll check if we can deep-merge the api-configuration.json files in various api gateways.

**Comment by NecatiMeral** [comment]
Since we're aiming for a microservice architecture, this is currently a show-stopper for us.
We would be happy if we could support you in any way to find a solution for a proper microservice architecture.

**Comment by gterdem** [comment]
> Since we're aiming for a microservice architecture, this is currently a show-stopper for us. We would be happy if we could support you in any way to find a solution for a proper microservice architecture.

Hello,
This shouldn't be a blocker issue since you can reference to `Application.Contract` layers of other microservices from `AdministrationService`. 
We'll think about this since localization is not the only _resource_ to obtain, we also need to consider permissions.

**Comment by NecatiMeral** [comment]
Hi @gterdem,

yeah, the described approach would work. We initially wanted not to couple the administration service with other parts of the application ecosystem. 

Thanks :-)

**Comment by gterdem** [comment]
Moved to https://github.com/abpframework/eShopOnAbp/issues/152
