### ISSUE TITLE
Failed to initialize seed data with SQLite

### ISSUE THREAD

**Issue by yhdkzy** [abpframework/abp#10910]
version：4.4.4
database provider(EF Core/Sqlite)
![image](https://user-images.githubusercontent.com/1321058/145575583-1d6907bb-c865-4de2-82e8-14d98704459a.png)

Steps:
1.

![image](https://user-images.githubusercontent.com/1321058/145575689-d7559e5a-3bb7-47bf-9c49-90b16a0dcf1f.png)

2.
![image](https://user-images.githubusercontent.com/1321058/145575749-da27cb90-b52b-4dd0-9de4-a2e9d646840e.png)

result:
![image](https://user-images.githubusercontent.com/1321058/145576031-87969ab6-9ecf-4e7f-a623-726b8c60f377.png)

hope resutl:
The result I expect is to be able to insert seed data into the database when using SQLite.

**Comment by maliming** [comment]
I can't reproduce the problem.
