### ISSUE TITLE
Problem uploading a file using MultipartReader

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#10916]
I´m trying to upload a big file using multipart request but using this framework I´m getting the following error

> "Unexpected end of Stream, the content may have already been read by another component."

There is like something in Abp is "messing with" the communication and I can´t find out what.

I updated [this repository](https://github.com/sturlath/RolesDemo) with code to try it out.  Just run it and upload a  file and see it fail.

The error happens in [this code](https://github.com/sturlath/RolesDemo/blob/2363a33decbbc249ec62cffedd941722193a8896/src/RolesDemo.HttpApi/Controllers/FileStreamingHelper.cs#L38)

```csharp
var reader = new MultipartReader(boundary, request.Body);
var section = await reader.ReadNextSectionAsync(); //<-- Exception thrown here --> "Unexpected end of Stream, the content may have already been read by another component."
```

My Blazor [file upload code](https://github.com/sturlath/RolesDemo/blob/2363a33decbbc249ec62cffedd941722193a8896/src/RolesDemo.Blazor/Pages/Index.razor.cs#L28)

```csharp
private async Task OnFileUploadChanged(FileChangedEventArgs e)
{
    if (e.Files != null && e.Files.Length == 1)
    {
        var file = e.Files[0];

        using (var ms = file.OpenReadStream(long.MaxValue))
        {
            var content = new MultipartFormDataContent();
            content.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data");
            content.Add(new StreamContent(ms, Convert.ToInt32(ms.Length)), "image", "filename");
            using var client = new HttpClient();
            //post the file like this since I had problems with passing MultipartFormDataContent to AppService
            var postResult = await client.PostAsync("https://localhost:44365/api/app/bigfile/upload", content);
        }
    }
}
```

 My [controller code](https://github.com/sturlath/RolesDemo/blob/2363a33decbbc249ec62cffedd941722193a8896/src/RolesDemo.HttpApi/Controllers/BigFileUploadControllerc.cs#L19)

```csharp
[RemoteService]
[Area("app")]
[ControllerName("BigFileUpload")]
[Route("api/app/bigfile")]
public class BigFileUploadControllerc : RolesDemoController
{
    [IgnoreAntiforgeryToken]
    [DisableFormValueModelBinding]
    [DisableRequestSizeLimit]
    [HttpPost("upload")]
    public async Task UploadFileAsync()
    {
        if (Request.ContentLength == 0)
            BadRequest();

        try
        {
            var filePath = Path.GetTempFileName();

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await Request.StreamFile(stream);
            }
          
            //...upload to blob storage
        }
        catch (Exception ex)
        {
            //Always end here with "Unexpected end of Stream, the content may have already been read by another component."
        }
    }
}
```

**Any idea what this might be causing this and how I can solve it?**

### Works in none-abp Blazor/API

I created a Blazor/API without abp.io in the demo repo to show that it works without it. [Here is the controller that works](https://github.com/sturlath/RolesDemo/blob/bc8565f992283d2b8e12406f97f5c924f81c5b42/WorkingApi/Controllers/BigFileUploadControllerc.cs#L29) and the [Blazor counterpart](https://github.com/sturlath/RolesDemo/blob/bc8565f992283d2b8e12406f97f5c924f81c5b42/ThisWorksBlazor/Pages/Index.razor.cs#L28). **Run it and see the same code working without abp.io**.

This is probably some configuration issue but I have no idea where to look for it.

* Your **ABP Framework version** : 4.4 (also in my 4.4.4 commercial project)
* Your **User Interface** : Blazor
* Your database provider : EF Core

**Comment by maliming** [comment]
You can try to use [IRemoteStreamContent](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/Volo/Abp/Content/IRemoteStreamContent.cs#L6) in the tiered project.

**Comment by sturlath** [comment]
Ok it worked (see code below) if I just skip using these helpers (it does throw if they are used) but I haven't tried this with large (2-5GB) files so I don't know if it will work with that. The stream comes over as multipart so I recon it should

I'll give larger files try later and give feedback if it didn´t.

```csharp
FileEntry file = ...file from Blazorise;
using var stream = new MemoryStream();
await file.WriteToStreamAsync(stream);
await UploadAppService.UploadBigFileAsync(new RemoteStreamContent(stream, file.Name));
```

the controller

```csharp
[HttpPost("recording-upload")]
[IgnoreAntiforgeryToken]
[DisableFormValueModelBinding]
[DisableRequestSizeLimit]
public virtual async Task UploadBigFileAsync(IRemoteStreamContent streamContent)
{
    if (Request.ContentLength == 0)
        BadRequest();

    using (var fs = new FileStream($"C:\\temp\\{ streamContent.FileName}].blob", FileMode.Create))
    {
        await streamContent.GetStream().CopyToAsync(fs);
        await fs.FlushAsync();
    }
}
```

**Comment by sturlath** [comment]
As you can see from my comment [here](https://support.abp.io/QA/Questions/2267/Problem-uploading-a-file-using-MultipartReader#answer-f6d20abb-ef78-26e6-3cc8-3a00e1f2db21) @maliming I need another approach because Blazor WASM doesn't seem to support >2GB files.

Now I'm thinking I should just upload the files directly from Blazor to [Blob storage](https://docs.abp.io/en/abp/5.0/Blob-Storing). 

**Can I use it in Blazor like that?** 

I´ll give it a try and let you know.

**Comment by maliming** [comment]
Lets discuss in support website.
