### ISSUE TITLE
Add claims from external login

### ISSUE THREAD

**Issue by ArneCools** [abpframework/abp#10913]
* Your **ABP Framework version**.
4.3.3
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
Blazor server
* Your database provider(EF Core/MongoDB)
EF Core
* Exception message and **stack trace** if available (check the logs).
None
* Steps needed to **reproduce** the problem.
1. Add external login
2. Add claims from external login in implementation of iAbpClaimsPrincipalContributor
3. Claims are not added to User

I'm trying to add claims provided by my Saml2 external login provider. I'm using the package Systainsys.Saml2.AspNetCore2 (https://github.com/Sustainsys/Saml2)

```
public async Task ContributeAsync(AbpClaimsPrincipalContributorContext context)
{
var identity = context.ClaimsPrincipal.Identities.FirstOrDefault();
var signInManager = context.ServiceProvider.GetRequiredService<SignInManager<Volo.Abp.Identity.IdentityUser>>();
var info = await signInManager.GetExternalLoginInfoAsync();
if (info != null)
{
    var group = info.Principal.FindFirstValue("http://schemas.xmlsoap.org/claims/Group");
    if (group != null)
    {
        identity.AddClaim(new Claim("http://schemas.xmlsoap.org/claims/Group", group));
    }
    var sessionIndex = info.Principal.FindFirst(Saml2ClaimTypes.SessionIndex);
    var logoutNameIdentifier = info.Principal.FindFirst(Saml2ClaimTypes.LogoutNameIdentifier);
    if (sessionIndex != null && logoutNameIdentifier != null)
    {
        identity.AddClaim(sessionIndex);
        identity.AddClaim(logoutNameIdentifier);
    }
}

Configure<AbpClaimsServiceOptions>(options =>
{
    options.RequestedClaims.Add("http://schemas.xmlsoap.org/claims/Group");
    options.RequestedClaims.Add(Saml2ClaimTypes.SessionIndex);
    options.RequestedClaims.Add(Saml2ClaimTypes.LogoutNameIdentifier);
});
```

I noticed the ContributeAsync method is called multiple times. The first time the "externalLoginInfo" is available. But the 2nd, 3nd, 4nd... time that method is called the external info is null. The 2nd time that method is called I notice the claims I added were still visible under signInManager.Context.User. The 3rd time that method was called those claims where gone too. What is the reason it gets called so many times when logging in?

Anyway: what is the correct way of getting claims from an external provider?

**Comment by maliming** [comment]
> what is the correct way of getting claims from an external provider?

`iAbpClaimsPrincipalContributor` is not designed for external logins. The claims should be provided by external authentication scheme.

**Comment by ArneCools** [comment]
I believe the claims are added after login by the authenticationScheme. I can get them using 
`await signInManager.GetExternalLoginInfoAsync()`

I work in a Tiered solution:
And i'm able to add them to the claims in the IdentityServer project (with iAbpClaimsPrincipalContributor ) . But how to I add the claims to the user in the Host project?

**Comment by maliming** [comment]
> But how to I add the claims to the user in the Host project?

What's the Host project? Web?
