### ISSUE TITLE
HttpApi.Client Null object reference exception

### ISSUE THREAD

**Issue by CristWu** [abpframework/abp#10929]
I am learning how to use httpApi.Client module by  the official webside(https://docs.abp.io/en/abp/5.0/API/Dynamic-CSharp-API-Clients#service-interface) with abp veriosn 5.0 rc2

the remote service is injected but it runs wtih an exception  null reference exception in volo.abp.http.client
 
the statcktrace is 

   在 Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.get_ClientOptions()
   在 Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__32.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.<RequestAsync>d__31`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptorClientProxy`1.<CallRequestAsync>d__0`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<CallRequestAsync>d__26`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<GetResultAsync>d__27.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<InterceptAsync>d__24.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__3`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__14`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.<ProceedAsync>d__7.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Validation.ValidationInterceptor.<InterceptAsync>d__2.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   在 Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__3`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Sample.HttpApi.Client.Test.ClientDemoService.<RunAsync>d__2.MoveNext() 在 E:\OpenSource\AbpSample\SampleAbp\Sample.HttpApi.Client.Test\ClientDemoService.cs 中: 第 22 行
how can i fix this problem?

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by CristWu** [comment]
> * Steps needed to **reproduce** the problem.
first, fowllowing the website tutorial to buid up a httpApi.Client module depends on contracts module and volo.abp.http module
second, create a testmodule depends on  client module ,create a test service  inject the service defined in contracts module
then,start up the web module in order to start the remote service
finally  run the test service
the remote service was run ok by using swagger pages but excepted by testservice

**Comment by realLiangshiwei** [comment]
Can't reproduce the problem.

**Comment by CristWu** [comment]
> Can't reproduce the problem.
here is my code 
[code](https://github.com/CristWu/MyAbpLearn)
 just run the web module  then run the client test module

**Comment by realLiangshiwei** [comment]
Try

`typeof(AbpAutofacModule)`

**Comment by CristWu** [comment]
> 

added  but still got the exception
![图片](https://user-images.githubusercontent.com/27179054/145948610-a87ccc99-b127-437d-b3c7-5c7922953a06.png)

**Comment by CristWu** [comment]
> Try
> 
> `typeof(AbpAutofacModule)`

it works ! but why the sample project(Acme.BookStore) dose not having abpautofac depenency in client test module?
![图片](https://user-images.githubusercontent.com/27179054/145949635-8e9fd0fa-5de4-4c10-9d04-1afc7a1bcbe4.png)

**Comment by realLiangshiwei** [comment]
The sample project uses ABP v4.4.0, we will update it when the 5.0.0 stable version is released.
