### ISSUE TITLE
Blazor Server .net _Host Ambiguous Exception

### ISSUE THREAD

**Issue by NicolasEhrhard** [abpframework/abp#10924]
ABP Framework version : 5.0.0-rc.2
Blazor Server
EF Core
.Net 6

AmbiguousMatchException: The request matched multiple endpoints. Matches:
/_Host
/_Host
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)

To reproduce this : 
Create new Blazor Server .net 6 app.
Add module who inherit from AppModule, register it and add depend to AbpAspNetCoreMvcModule

Every time i add " DependOn(typeof(AbpAspNetCoreMvcModule))] , i can navigate on my app using navlink, for exemple click on the menu and go to /counter page, but when i press F5, i've got this error. If i press F5 when url is "/", everything is ok, only when url is "/..."

Thanks for your help.

**Comment by maliming** [comment]
Can you share a project?

**Comment by NicolasEhrhard** [comment]
I create a repository with a sample project : 
https://github.com/NicolasEhrhard/AbpIssue

**Comment by maliming** [comment]
Maybe related to https://github.com/dotnet/aspnetcore/issues/38566


https://github.com/abpframework/abp/pull/10947

**Comment by maliming** [comment]
S
