### ISSUE TITLE
DomainTenantResolver needs SSL certificate update (each 3 months...)

### ISSUE THREAD

**Issue by Francois-La** [abpframework/abp#10939]
The sample application, https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver, needs update for the getabp.net.pfx file.

This file is a let's encrypt certificate and these need to be renewed each 90 days.  The one actually there expired yesterday (December 13th, 2021)

Thanks

**Comment by maliming** [comment]
Done https://github.com/abpframework/abp-samples/commit/5e08f43d89097da46a9aa01b56c075c99f637611

**Comment by maliming** [comment]
I will consider creating an automated program to update it each 3 months.
