### ISSUE TITLE
Configuration redesign

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1094]
- [x] Remove `IConfigurationAccessor`. Use `IConfiguration` instead. This requires to use the generic host on host builder instead of old style coding #391
- [x] Crate & Register `IConfiguration` if not registered before.
- [x] Update all usages in all projects

**Comment by maliming** [comment]
Can we provide a `WebHostBuilder `extension method to initialize `IConfiguration`?

**Comment by hikalkan** [comment]
I am reopening since we haven't removed IConfigurationAccessor yet.
