### ISSUE TITLE
Runtime problem CrudAppService  when interface and class does not match exactly

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#10946]
* Your **ABP Framework version**.: 5.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: Blazor Server
* Your database provider(EF Core/MongoDB): EF

Not sure if this is a bug or not but I just noticed that when using the ICrudAppService/CrudAppService the interface and the class needs to be named exactly the same or you will get an error:

`System.InvalidOperationException: Cannot provide a value for property 'AppService' on type 'MIBS.Blazor.Pages.CompanyTypes'. There is no registered service of type 'MIBS.CompanyTypes.ICompanyTypesAppService'.`

In our case, we had by mistake named the interface ICompanyType**s**AppService instead of ICompanyTypeAppService which was the naming used in the class implementation (singular/plural of Types). The code compiled as it should be the error message was runtime. When we removed the s from Types in the interface and updated the rest of the code it started to work fine runtime also. 

Code that caused the problem:

```
    public interface ICompanyTypesAppService :
        ICrudAppService< 
            CompanyTypeDto, 
            int, 
            PagedAndSortedResultRequestDto, 
            CreateUpdateCompanyTypeDto> 
    {


    }

***

    public class CompanyTypeAppService :
        CrudAppService<
            CompanyType, 
            CompanyTypeDto, 
            int, 
            PagedAndSortedResultRequestDto, 
            CreateUpdateCompanyTypeDto>, 
        ICompanyTypesAppService 
    {
        public CompanyTypeAppService(IRepository<CompanyType, int> repository)
            : base(repository)
        {

        }

***

@inherits AbpCrudPageBase<ICompanyTypesAppService, CompanyTypeDto, int, PagedAndSortedResultRequestDto, CreateUpdateCompanyTypeDto>
```

Of course, this was a typo on our end but not sure if that is supposed to cause this problem as the code itself did not cause any design time errors.

**Comment by realLiangshiwei** [comment]
ABP uses a naming convention, see https://docs.abp.io/en/abp/4.4/Dependency-Injection#exposed-services-by-convention
