### ISSUE TITLE
Issue in abp EFCore oracle

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#10957]
Hi,
There is problem in oracle driver in abp v5 i am using commercial version.
Thanks

![image](https://user-images.githubusercontent.com/96010802/146313283-18e09e34-1a0d-4d40-8e70-f189f58f6cce.png)

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/10513

**Comment by realLiangshiwei** [comment]
Because Oracle driver did not support NET 6 before, but I saw the official oracle driver supports NET 6 now, we will update it.

**Comment by awahbahplana** [comment]
OK Dear thanks for your fast and great support.

**Comment by awahbahplana** [comment]
When Can I Use it @realLiangshiwei ?

On Witch Version (Pre release or nightly prebuild)
