### ISSUE TITLE
Getting 500 error when setting the ASPNETCORE_ENVIRONMENT to production

### ISSUE THREAD

**Issue by emilsjog** [abpframework/abp#10955]
I'm getting 500 error code when setting the ASPNETCORE_ENVIRONMENT to production. 

Created a new ABP project based on version 5. Then I changed the variable in the `launchsetting.json`
Attached is the standard logfile.

* **5.0**
* **Blazor-server** 
* Ef
```
An unhandled exception has occurred while executing the request.
Volo.Abp.AbpException: Could not find file '/_content/Blazorise/blazorise.css'
```
Reproduce:
* Set `"ASPNETCORE_ENVIRONMENT": "Production"` in the Blazor project

[logs.txt](https://github.com/abpframework/abp/files/7719165/logs.txt)

**Comment by emilsjog** [comment]
Tested out the suggestion from [SO](https://stackoverflow.com/questions/58862932/blazor-server-static-files-dont-link-in-non-dev-environments) and got it working.

Any thoughts on this issue? I'm not up to date on the actual problem or the suggested solution.

**Comment by realLiangshiwei** [comment]
> Calling UseStaticWebAssets isn't required when running an app from published output (dotnet publish).

If you really need it, you can always call the `UseStaticWebAssets` method

See https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-6.0&tabs=visual-studio#consume-content-from-a-referenced-rcl-1

![image](https://user-images.githubusercontent.com/16813853/146191017-a7858ac6-ff4f-4125-985e-5d72c0c853b6.png)
