### ISSUE TITLE
Notification Bell Angular

### ISSUE THREAD

**Issue by Bongmusa** [abpframework/abp#10952]
We've gone through the community articles regarding the Signal R notifications and looked at the toaster service. However this doesn't fulfil the standard notification bell that we see on many web applications.

Suggestion : Can you add  notification bell and panel in the Angular template for the upcoming releases.

**Comment by mehmet-erim** [comment]
Hi @Bongmusa 

We have no plans for this in the near future. But you can implement it in your project, there is nothing to block you.

Thanks!
