### ISSUE TITLE
How to migrate database when application start?

### ISSUE THREAD

**Issue by Edward-Zhou** [abpframework/abp#10968]
I am using asp.net core abp, and I am trying to create database while application start.

Is there any way to achieve this?

I have tried to resolve DbContext from `Configure`, but it could not get this service.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/EntityFrameworkCoreMyProjectNameDbSchemaMigrator.cs#L21

This is not related to ABP but EF Core.

**Comment by Edward-Zhou** [comment]
Why this is closed? I know how to use `Database.MigrateAsync()`. But how can I get the dbcontext while application start? I can't resolve it anywhere.

**Comment by Edward-Zhou** [comment]
@maliming Do you mean I need to create my own `EntityFrameworkCoreMyProjectNameDbSchemaMigrator`?
