### ISSUE TITLE
[Suggestion] Can add a feature in RemoteService for transpond costom headers

### ISSUE THREAD

**Issue by fanslead** [abpframework/abp#10973]
When I use RemoteService to request the orther service, Some headers data they need can not  get.
Like the X-Forwarded-host,X-Forwarded-for and orther custom header.

would you add some feature for configure the http client headers?
just like
```
AddHttpClientProxies(
                typeof(Module).Assembly,
                RemoteServiceName,
                needTranspondHeaders => {
               //needTranspondHeaders.Add("X-Forwarded-host")
}
            );
```

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/5.0/API/Dynamic-CSharp-API-Clients#retry-failure-logic-polly-integration
