### ISSUE TITLE
Organizational Units and Roles - Creating a hierarchical structure of users with ABP

### ISSUE THREAD

**Issue by jlavallet** [abpframework/abp#10979]
This is a request for a community article to be written demonstrating the use of Organizational Units and Roles to develop an elegant hierarchy of managing users and managed users. I have made a request for information on this topic here: https://stackoverflow.com/questions/70297404/filtering-queries-by-by-user-and-role-scoping-data. I have yet to find an example of how the  Organizational Unit feature is used.

**Comment by maliming** [comment]
> I am using ABP Commercial

You can get help on https://support.abp.io/
