### ISSUE TITLE
the Localization didn't work, just show default language

### ISSUE THREAD

**Issue by davidnasar** [abpframework/abp#10986]
* Your **ABP Framework version**.
5.0.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
MVC
* Your database provider(EF Core/MongoDB)
EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
1. use CLI to create a app like: abp new MyTodo -t app
2. Login with default admin account, change language to other language, eg: Chinese
3. go to Administration/Identity management/Roles, click the action/**Permissions**  in the list.
4. Then popup a window, **uncheck** the checkbox named **Grant all permissions**, but don't save, click Cancel button, then popup another window with question: Are you sure? 
5. The text in the button just show text in English as the screenshot P-1, not the chosen language. It should display the language I chosen. But in version 4.4.4, it just shows fine as the screenshot P-2.

P-1(v5.0.0)
![image](https://user-images.githubusercontent.com/6254752/146677426-4e986afb-5009-479b-8cc7-ecacd1f11ab1.png)
P-2(v4.4.4)
![image](https://user-images.githubusercontent.com/6254752/146677770-1304ad27-74c7-4c76-b11e-bc6c3b1c78b4.png)

6. By the way, the **margin** among lines seems too large somehow as the screenshot P-3, but in version 4.4.4, it's just perfect as the screenshot P-4, can make some adjustment?
P-3(v5.0.0)
![image](https://user-images.githubusercontent.com/6254752/146677876-da8f1779-de12-4834-891d-a64fa1ec52a4.png)
P-4(v4.4.4)
![image](https://user-images.githubusercontent.com/6254752/146678128-4d2b7778-8d6b-42ed-a333-c8a4b4235cab.png)

**Comment by davidnasar** [comment]
same button text situation when deleting record in the list

**Comment by iyilm4z** [comment]
@davidnasar i created a pr for the localization issue, thanks for your feedback.

**The permissions dialog:**
![image](https://user-images.githubusercontent.com/9105939/146696107-ab63f218-f658-4e60-9f6e-e35e05bcab20.png)

**The delete dialog:**
![image](https://user-images.githubusercontent.com/9105939/146696125-7bd686dd-c06e-4654-b85a-a0ed2e64f65f.png)
