### ISSUE TITLE
override IQuerayble for all select query

### ISSUE THREAD

**Issue by FuatCetinkaya** [abpframework/abp#10980]
Hi,

Is there an IQuerayble method that I can override on all select queries for all entities?

**Comment by maliming** [comment]
Can you explain it in detail? Thanks

**Comment by FuatCetinkaya** [comment]
Hi @maliming,

I have a table where I keep user based rules ( Conditional Entity)

Conditional Entity
TableName (string)
PropertyName (string)
Value (string)
UserId (Guid)

Data;
TableName                   PropertyName               Value             UserId
Organization                 Code                             0001              xxx
Employee                      Age                               18                  xxx
Organization                 Code                             0005              yyy

I want to add where expression according to this table in all Select queries

For Example;
protected override IQueryable<TEntity> GetQueryable()
        {
           // If there is a record of the relevant user in the Conditional Table, I will add an expression
        }

But I couldn't find a method where all select queries can be overridden in common.

Thanks.

**Comment by maliming** [comment]
Maybe the `Global Query Filters` is more suitable for you.

https://docs.microsoft.com/en-us/ef/core/querying/filters

https://github.com/abpframework/abp/issues/10876#issuecomment-987964175

**Comment by FuatCetinkaya** [comment]
Hi @maliming,

I don't want to do it with the Global Query Filters method. Because it is created instantly onModelCreating. I have to load all the data in my Conditional table in the DbSet instant.

ForExample; (Imagine there are more than a thousand such data in this table)
Select * from Organization Where 
(Code = Code001 and UserId=xxx) or 
(Code = Code005 and UserId=yyy) or 
(Code = Code003 and Name = qwe and UserId=ccc ) // bla bla bla

Therefore, it is not an effective solution for me.


As you know, abp tools generates code like below

        protected virtual async Task<IQueryable<XyzWithNavigationProperties>> GetQueryForNavigationPropertiesAsync()
        {
            return from test in (await GetDbSetAsync())
                   join employeeTitle in (await GetDbContextAsync()).EmployeeTitles 
			on test.EmployeeTitleId equals employeeTitle.Id

                   select new XyzWithNavigationProperties
                   {
                       Test = test,
                       EmployeeTitle = employeeTitle
                   };
        }

I couldn't find a method that the above query has in common. If there is such a method, I will override that method and add a user-based expression.

https://www.codeproject.com/Articles/1114913/Row-level-security-in-Entity-framework

https://oncodedesign.com/row-level-authorization/

I hope I was able to explain my problem
Thanks

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/10876#issuecomment-987964175
