### ISSUE TITLE
_repository.AsQueryable() gets error in v5.0.0

### ISSUE THREAD

**Issue by davidnasar** [abpframework/abp#10982]
* Your **ABP Framework version**.
version 5.0.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
MVC
* Your database provider(EF Core/MongoDB)
EF Core
* Exception message and **stack trace** if available (check the logs).
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1929	'IStoreRepository' does not contain a definition for 'AsQueryable' and the best extension method overload 'Queryable.AsQueryable(IEnumerable)' requires a receiver of type 'IEnumerable'	MyTodo.Application	C:\Programs\Projects\MyTodo\src\MyTodo.Application\Stores\StoreAppService.cs	31	Active
* Steps needed to **reproduce** the problem.
1. use CLI : abp new MyTodo -t app
2. Create a StoreAppService in XX.Application
3. Create a method and put a code like this: _repository.AsQueryable();
4. it gets error, like this screenshot below, but in version 4.4.4, same code no error.
![image](https://user-images.githubusercontent.com/6254752/146640367-03ca04dd-341c-4519-a260-0735a87ee724.png)

**Comment by realLiangshiwei** [comment]
Use `GetQueryableAsync` instead of `AsQueryable`
