### ISSUE TITLE
Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.

### ISSUE THREAD

**Issue by imxiongstu** [abpframework/abp#10987]
Hello,every one:
    I from china,i trying to extension AbpRoles table，but error,such as：

Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.

  Is there a friend who can take a look? thinks!!!!!!!!!!

**Comment by imxiongstu** [comment]
builder.ConfigureIdentity() in    builder.ConfigureIdentity();
cuz up code error;

**Comment by maliming** [comment]
Please try to search for issues and code and documents.

**Comment by imxiongstu** [comment]
您的邮件我已经收到，请耐心等待回复熊www.imxiongstu.cn

**Comment by imxiongstu** [comment]
> Please try to search for issues and code and documents.

hi,thinks,but me one to one office the official cocuments,already ask a lot of pepole,
