### ISSUE TITLE
Replacing Extensible Table Component

### ISSUE THREAD

**Issue by jackcmac** [abpframework/abp#10984]
UI Framework: Angular

In my ABP projects I use PrimeNG tables instead of `ngx-datatable`. I've written a table-list directive for the PrimeNG tables that uses the ABP `ListService` and now I want to replace the `ExtensibleTableComponent` so the built-in tables look the same. My custom `ExtensibleTableComponent` has all the same `@Inputs` and component code as the original, but with a different template.

Is this something that is currently supported? If so, what is the key replace it on the `ReplaceableComponentsService`?

```
this.replaceableComponents.add({
      component: ExtensibleTableComponent, // my custom extensible table component
      key: ???
});
```

**Comment by mehmet-erim** [comment]
Hello @jackcmac,

`ExtensibleTableComponent` is not replaceable now. We'll consider this.
Thanks for creating this issue.
