### ISSUE TITLE
[question]what's the abppkg.json used for?

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#11013]
* Abp 5.0.
* Steps needed to **reproduce** the problem
  - `abp new Yun.FileManagement -t module --no-ui -o src/modules/filemanagement -cs "Server=(LocalDb)\\MSSQLLocalDB;Database=filemanagement;Trusted_Connection=True"`
  - in the **filemanagement** folder contains `Yun.FileManagement.abpmdl.json` and `Yun.FileManagement.abpsln.json`
  - in each project folder contains a json file named  as `XXX.abppkg.json`
 I can't understand these json file used for what

**Comment by yekalkan** [comment]
Hi @xyfy,

They keep info about your module & packages but they have no use for now. You can delete them if you want.

**Comment by xyfy** [comment]
dou you mean that they is used for the **abp** source manage ,but no effect for abp users?


if they have no use for now ,may it removed in code generate?


manual remove it after every code generate is&nbsp; complex？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yunus Emre ***@***.***&gt;; 
发送时间: 2021年12月21日(星期二) 晚上6:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [abpframework/abp] [question]what's the abppkg.json used for? (Issue #11013)





 
Closed #11013.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
