### ISSUE TITLE
abp-input checkboxes add too much extra margin at bottom

### ISSUE THREAD

**Issue by ejohnson-dotnet** [abpframework/abp#11020]
ABP Framework: 5.0.0
UI: MVC
DB: EF Core

In the new version of ABP 5.0.0, the checkboxes created by the tag helper "apb-input" create too large of a margin at the bottom of the control.

This can easily be seen in the default Permissions page for a role.
This is from ABP 5.0.0:
![Role permission v5](https://user-images.githubusercontent.com/2363596/146992962-bf2de0e4-1ab4-4d81-bcbb-26d5df6a5502.PNG)

Here is the same page from ABP 4.4.4:
![Role permission v4](https://user-images.githubusercontent.com/2363596/146993033-0c5aa665-9ca8-487d-8410-dd1414f5acf4.PNG)

The 4.4.4 version seems much more natural and better spacing.

**Comment by maliming** [comment]
Resolved by #10990
