### ISSUE TITLE
UseHangfireDashboard() not working when executed before app.UseConfiguredEndpoints()

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11021]
* Your **ABP Framework version**: 5.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: Blazor Server 
* Your database provider(EF Core/MongoDB): EF
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

It seems like if you put app.UseHangfireDashboard() after app.UseConfiguredEndpoints() the /hangfire page won't work, but if you move it ahead of that line, it will. Not sure if this is a bug or not but if it isn't, documentation should probably be updated about this. 

https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire

This is with HangFire 1.7.27.

**Comment by maliming** [comment]
hi

`UseConfiguredEndpoints` must be the last.
