### ISSUE TITLE
Does Volo.Abp.BackgroundJobs support recurring jobs?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11034]
It seems like Volo.Abp.BackgroundJobs implements IBackgroundJobManager but I can't find anything for recurring jobs, IRecurringJobManager in case of HangFire. Is this something that is implemented and if so, how do we use it? If not, what is the best was to solve it without skipping on Volo.Abp.BackgroundJobs and do a direct implementation? If it is not supported today, are there plans to implement support for recurring jobs as well? Thanks.

**Comment by improwise** [comment]
Some related info:

https://stackoverflow.com/questions/59544062/how-and-where-do-i-implement-my-recurring-hangfire-job-in-the-solution-structure

https://docs.abp.io/en/abp/latest/Background-Jobs

**Comment by iyilm4z** [comment]
Hi @improwise, abp has Hangfire module and Hangfire supports recurring jobs. [Here](https://docs.abp.io/en/abp/latest/Background-Workers-Hangfire) is the related for integration.

After integrating your app with Hangfire module, you can inject **IBackgroundWorkerManager** and use it's **[Add](https://github.com/abpframework/abp/blob/ab6eedd52a662d430615ed7c80b12aa976594f55/framework/src/Volo.Abp.BackgroundWorkers.Hangfire/Volo/Abp/BackgroundWorkers/Hangfire/HangfireBackgroundWorkerManager.cs#L24)** method to add a recurring job. If you set correct cron expession for the job, you will get the result you want.

**Comment by improwise** [comment]
Thanks, will have a look at that! So the BackgroundWorkerManager is for reccuring tasks then as the BackgroundJobManager does not seem to support that? I find that the documentation is a bit confusing here, but that could just as well be due to my own lack of understanding.

**Comment by iyilm4z** [comment]
> So the BackgroundWorkerManager is for reccuring tasks then as the BackgroundJobManager does not seem to support that? 

Yes. 

According to source code of [BackgroundJobManager](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BackgroundJobs.HangFire/Volo/Abp/BackgroundJobs/Hangfire/HangfireBackgroundJobManager.cs), it's for running a job one time at backround. Because there is no cron related code there.

**Comment by realLiangshiwei** [comment]
As @iyilm4z said, Background job used for jobs that are executed only once, 

Background worker is more suitable for you.

**Comment by berkansasmaz** [comment]
Thanks for the answers @iyilm4z 

Background worker:

> [Background workers are simple independent threads in the application running in the background. Generally, they run **periodically** to perform some tasks.](https://docs.abp.io/en/abp/latest/Background-Workers)

Cron:

> [Users who set up and maintain software environments use cron to schedule jobs (commands or shell scripts) to run **periodically** at fixed times, dates, or intervals.](https://en.wikipedia.org/wiki/Cron)

So, I agree with @realLiangshiwei and @iyilm4z.

**Comment by improwise** [comment]
Thanks for all helpful answers. 

Are there any recommendations on where to implement this logic, ie which layer, in a typical server side application like Blazor Server or MVC? Ideally you don't want to configure workers and background jobs in the presentation layer but at the same time you need to have it running in the website project and also want to something like the Hangfire Dashboard to work

**Comment by berkansasmaz** [comment]
> Are there any recommendations on where to implement this logic, ie which layer, in a typical server side application like  Blazor Server or MVC? Ideally you don't want to configure workers and background jobs in the presentation layer but at the same time you need to have it running in the website project and also want to something like the Hangfire Dashboard to work

[Hangfire/Background Job - Which layer do I implement it in?](https://github.com/abpframework/abp/issues/4174)

**Comment by improwise** [comment]
> > Are there any recommendations on where to implement this logic, ie which layer, in a typical server side application like  Blazor Server or MVC? Ideally you don't want to configure workers and background jobs in the presentation layer but at the same time you need to have it running in the website project and also want to something like the Hangfire Dashboard to work
> 
> [Hangfire/Background Job - Which layer do I implement it in?](https://github.com/abpframework/abp/issues/4174)

Thanks for all the helpful answers!

Is there perhaps a sample application available with a running example of how to implement a BackgroundJob and BackgroundWorker in ABP? Ideally also one using HangFire/RabbitMQ etc but I guess you can't ask for everything :)

**Comment by berkansasmaz** [comment]
As far as I know, there is no specific application for both RabbitMQ and Hangfire samples.

However, looking at the resources below may be helpful.
- https://github.com/realLiangshiwei/Lsw.Abp.BackgroundWorkers.Hangfire
- https://github.com/abpframework/abp-samples/tree/master/RabbitMqEventBus
- https://community.abp.io/articles/real-time-messaging-in-a-distributed-architecture-using-abp-framework-singalr-rabbitmq-daf47e17

**Comment by improwise** [comment]
Thanks again!
