### ISSUE TITLE
[Enhancement] Replace EventBus Reflection with compiled Expression

### ISSUE THREAD

**Issue by zeinali0** [abpframework/abp#11030]
EventBus module used Reflection to [trigger event-handlers](https://github.com/abpframework/abp/blob/ab6eedd52a662d430615ed7c80b12aa976594f55/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/EventBusBase.cs#L196)

In an event-driven system a single user request can cause multiple event invocation and each event can have multiple handler so it can lead to a considerable number of reflection calls per request which can impact performance of application.

I just wanted to know can I work on replacing event-bus reflections codes with compiled expression?

**Comment by maliming** [comment]
You can share some code here, Then work on the replacement.

**Comment by zeinali0** [comment]
We can create an instance of a `HandlerExecutor` per each pair of an event and a handler once on first invocation and store it in memory for next invocations of handler.
The `HandlerExecutor` class would be something like this [ObjectMethodExecutor](https://github.com/dotnet/aspnetcore/blob/main/src/Shared/ObjectMethodExecutor/ObjectMethodExecutor.cs) and would create a compiled expression to execut handler( [like this](https://github.com/dotnet/aspnetcore/blob/73c1a8d8aa890625b9a627cc12da278049ac362a/src/Shared/ObjectMethodExecutor/ObjectMethodExecutor.cs#L156)). But we can write a simpler one since we know we only have just 1 `HandleAsync` method and it would always get 1 argument.

Then the [TriggerHandlerAsync](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/EventBusBase.cs#L196) would change to somethige like this: 


```
protected virtual async Task TriggerHandlerAsync(IEventHandlerFactory asyncHandlerFactory, Type eventType,
        object eventData, List<Exception> exceptions, InboxConfig inboxConfig = null)
    {
        using (var eventHandlerWrapper = asyncHandlerFactory.GetHandler())
        {
            try
            {
                var handlerType = eventHandlerWrapper.EventHandler.GetType();

                if (inboxConfig?.HandlerSelector != null &&
                    !inboxConfig.HandlerSelector(handlerType))
                {
                    return;
                }

                using (CurrentTenant.Change(GetEventDataTenantId(eventData)))
                {
                    if (ReflectionHelper.IsAssignableToGenericType(handlerType, typeof(ILocalEventHandler<>)) || ReflectionHelper.IsAssignableToGenericType(handlerType, typeof(IDistributedEventHandler<>)))
                    {
                      //an instance of HandlerExecutor
                       var handlerExecutor = ExecutorStore.GetOrCreateExecutor(handlerType, eventType)
                       await handlerExecutor.Execute(eventHandlerWrapper.EventHandler, eventData)
                    }
                    else
                    {
                        throw new AbpException("The object instance is not an event handler. Object type: " + handlerType.AssemblyQualifiedName);
                    }
                }
            }
            catch (TargetInvocationException ex)
            {
                exceptions.Add(ex.InnerException);
            }
            catch (Exception ex)
            {
                exceptions.Add(ex);
            }
        }
    }

```
the change would be almost very low.
The ` ObjectMethodExecutor` is a well tested class. SignalR is using it to invoke hub methods. we can use it without change or as i said we can chanage it and make it less complex

**Comment by maliming** [comment]
`ObjectMethodExecutor` looks good.

**Comment by zeinali0** [comment]
So Should I prepare a pull request?

**Comment by maliming** [comment]
Please.

**Comment by maliming** [comment]
@zeinali0 If you don't have time we can handle it.

**Comment by zeinali0** [comment]
@maliming  Sorry I late, I got a little bit busy, I can send it in next 3 day.
But you can handle it if you are near release and need it sooner

**Comment by realLiangshiwei** [comment]
@zeinali0 
I will check it out.
