### ISSUE TITLE
DistEventsDemo Project Reference issue

### ISSUE THREAD

**Issue by CooperLiu** [abpframework/abp#11036]
Version abp 5.0.0

The `DistDemoApp.Shared` missed [`Volo.Abp.EventBus.Boxes` ](https://github.com/abpframework/abp/blob/dev/test/DistEvents/DistDemoApp.Shared/DistDemoApp.Shared.csproj#L20)project reference. it should be removed since Abp framework does not have it.

Demo project was worked after removed the reference of `Volo.Abp.EventBus.Boxes`.

**Comment by realLiangshiwei** [comment]
Thank you, we will update it.
