### ISSUE TITLE
Add OAuth External Login

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#11032]
Hi 
How to add Oauth2 auhentication for back end and display button in front end angular and MVC and other client app in commercial Version???

I add this in domain module
`` 
 context.Services.AddAuthentication().AddOAuth("GitHub", options => {
                options.ClientId = "8de23516870d7145b84e";
                options.ClientSecret = "0e3fd9808072907d1aa01df7e547ddbb6f6ec2fb";
                options.CallbackPath = new PathString("/signin-github");
                options.AuthorizationEndpoint = "https://github.com/login/oauth/authorize";
                options.TokenEndpoint = "https://github.com/login/oauth/access_token";
            });
``

what is the next step???
I want to register this user in abp database to grant permission to him
thanks

**Comment by maliming** [comment]
You can get help about ABP commercial at https://support.abp.io/

**Comment by awahbahplana** [comment]
> You can get help about ABP commercial at https://support.abp.io/

Dear I am wating your answer on [Support](https://support.abp.io/QA/Questions/2316/Add-OAuth2-as-external-login) for 4 days ago
your support on git hub is faster than there

thanks in advance
