### ISSUE TITLE
I found a bug in my development，PermissionManager

### ISSUE THREAD

**Issue by imxiongstu** [abpframework/abp#11050]
Hi,Every one.
      I found a bug in my development，such as:
                await _permissionManager.GetAllAsync("R", roleName)  and  await _permissionManager.GetAllForRoleAsync(roleName);

The above two，They all return，roleName filter invalid，

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by imxiongstu** [comment]
Abp version:5.0
code：
            var permissions = await _permissionManager.GetAllForRoleAsync(roleName);
            return permissions.Select(o => o.Name).ToList();
purpose： Find all permissions for this role

**Comment by imxiongstu** [comment]
Abp version:5.0
code：
            var permissions = await _permissionManager.GetAllForRoleAsync(roleName);
            return permissions.Select(o => o.Name).ToList();
purpose： Find all permissions for this role

**Comment by xyfy** [comment]
What's your **roleName** value pass in the method?

**Comment by CalvinWan0101** [comment]
> [imxiongstu](/imxiongstu)

Sorry to bother you, but I wanted to ask if this issue has been resolved? I'm encountering the same problem.

**Comment by imxiongstu** [comment]
您的邮件我已经收到，请耐心等待回复熊www.imxiongstu.cn
