### ISSUE TITLE
Problems with Microsoft Edge and Opera in SignalR using Hub.Context

### ISSUE THREAD

**Issue by mankoNm** [abpframework/abp#11067]
We add SignalR communication in our project. We use information about user in method MyHub.OnConnectedAsync() using 2 different way:

var ContextUserRole = Context.User.FindFirstValue(ClaimTypes.Role);			
var userRole = _currentUser.Roles;

We expect name of role here.
We have all information, when we use Mozilla and Google Chrome browsers. 
![image](https://user-images.githubusercontent.com/64478264/147360843-edb2bf53-4f16-46e0-a804-63db76b4c3ae.png)

But when we use Opera or Microsoft Edge and I am Log in before, our  MyHub.Context or CurrentUser is null.
[](url)
![image](https://user-images.githubusercontent.com/64478264/147361376-7adfcad0-b44d-4c3c-aeaf-b0d68491bbd6.png)

If I use Opera or Microsoft Edge, but have my first login or do log out than log in, it work correctly.

ABP veersion 4.4.4

**Comment by maliming** [comment]
hi

See https://github.com/abpframework/abp/pull/10508
