### ISSUE TITLE
Use Volo.Abp.BackgroundWorkers.Hangfire ERROR 

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#11069]
abp: 5.0

JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API

https://github.com/Nokecy/AbpHangfireTest  @realLiangshiwei

**Comment by berkansasmaz** [comment]
Please try the code below.

```csharp
private void ConfigureHangfire()
{
   GlobalConfiguration.Configuration.UseMemoryStorage();
}
```

**Comment by Nokecy** [comment]
Maybe the documentation should be updated ？https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire#configuration @berkansasmaz

**Comment by berkansasmaz** [comment]
Thank you for your suggestion, but I think the configuration part of this document is sufficient for now. After all, I think you will understand that we will not document every case supported by Hangfire or all other packages, for this you should visit the documentation of the relevant package.

**Comment by maxrizwork** [comment]
I had the same problem using abp ver5.1.3
I'm trying to use both modules: AbpBackgroundJobsHangfireModule and AbpBackgroundWorkersHangfireModule

If I configure Hangfire with SQL Server storage using:

`context.Services.AddHangfire(config =>
        {
            config.UseSqlServerStorage(configuration.GetConnectionString("Default"));
        });
`
it doesn't work.

If I use instead:
`
Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage(configuration.GetConnectionString("Default"));
`
it works.

**Comment by apt-dev** [comment]
For me, I had to install a NuGet package by inserting this line to proj.sc file `<PackageReference Include="Hangfire.SqlServer" Version="1.7.28" />` then in my ConfigureServices method in my module.cs I will then resolve these two lines:
`var configuration = context.Services.GetConfiguration();
        Hangfire.GlobalConfiguration.Configuration.UseSqlServerStorage(configuration.GetConnectionString("Default"));`
