### ISSUE TITLE
Abp Deployment

### ISSUE THREAD

**Issue by KaungZawHtet** [abpframework/abp#11063]
Is there any official article about abp deployment onto linux with best practices ?

**Comment by maliming** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-6.0
https://community.abp.io/articles/deploy-abp-framework-dotnet-core-tiered-app-to-docker-swarm-kcrjbjec
https://community.abp.io/articles/deploying-abp-applications-to-azure-ztvp6p57
