### ISSUE TITLE
Are nightly builds stopped during xmas?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11094]
Are nightly builds stopped during xmas? Looking to try out the fix for #11035 but latest build I can find is from 2021-12-22. Not sure why there seems to be a manual process to produce the nightly builds but I guess there are good reasons for it (have not been able to find any more info about nightly builds than https://docs.abp.io/en/abp/latest/Nightly-Builds). Thanks.

**Comment by enisn** [comment]
We're working on it right now. It'll be available soon as possible

**Comment by enisn** [comment]
They're working currently, so I'm closing this issue
