### ISSUE TITLE
Question: How to publish an outbox-using distributed event that is compatible with the local event bus provider.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#11100]
**Assume I am deleting a Book entity, and I want to send a notification email to the author if the deletion success.**

After https://github.com/abpframework/abp/pull/10008, using the distributed event bus with outbox may be a good way since it ensures the UOW completion success and then publishes the domain events. When the `IDistributedEventHandler<EntityDeletedEto<BookEto>>` executes, the book entity must have been deleted.

But the question is, I noticed that the [LocalDistributedEventBus](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/Distributed/LocalDistributedEventBus.cs) does not handle the param `useOutbox = true`:
https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/Distributed/LocalDistributedEventBus.cs#L136-L144

This presents a problem because it invokes the handlers as a local event before the UOW saves changes. The book has not been deleted or even will fail to delete.

If the above business is in a module, I don't know whether the app developers are using a real distributed event bus provider or not. So what should I do as a module developer? Or, is there any deviation in my understanding of this design?

Thanks.

:)

**Comment by maliming** [comment]
The local handler is run on the same UOW and will publish `onUnitOfWorkComplete`.

**Comment by gdlcf88** [comment]
Take the above example `IDistributedEventHandler<EntityDeletedEto<BookEto>>`.

![image](https://user-images.githubusercontent.com/30018771/147664839-bb571479-b57d-42be-8203-c6492f12c3f2.png)
![image](https://user-images.githubusercontent.com/30018771/147624320-ede57e32-7a2d-4c8c-b08f-8fb877aa2350.png)

If I send the email in this event handler (after ABP 5.0), I cannot ensure that the DB transaction commits success (since the app developers may use the LocalDistributedEventBus).

**Comment by gdlcf88** [comment]
Thank you @maliming for https://github.com/abpframework/abp/commit/eae8d6340fe2a63cc6ccb78cf3675044d02edd02.

The local distributed event bus has the same behavior now:
![image](https://user-images.githubusercontent.com/30018771/148355475-01565e9c-36f4-4293-823a-6dbbbd2c1cdb.png)

**Comment by jortygu** [comment]
@maliming commit:https://github.com/abpframework/abp/commit/eae8d6340fe2a63cc6ccb78cf3675044d02edd02 canceled? [latest ](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/Distributed/LocalDistributedEventBus.cs)code don't contain commit content.

**Comment by maliming** [comment]
hi @jortygu 

https://github.com/abpframework/abp/pull/12385#issue-1217427480

**Comment by jortygu** [comment]
@maliming is there any chance use outbox pattern in local event，i want to save data and event in same  transaction and then trigger event by background worker (with retry system)，i don't want to use real distributed event bus.
