### ISSUE TITLE
Should we remove Castle.Core dependency

### ISSUE THREAD

**Issue by hcqhuy** [abpframework/abp#1110]
I'm looking to framework code and found that we already using Autofac and Autofac.Extras.DynamicProxy in dependency injection. All the codes in module Volo.Abp.Castle.Core only use some interfaces of Castle.Core like IInterceptor, IInvocation but have to reference whole Castle.Core library (logging, Core, DynamicProxy).
Can we just create IInterceptor, IInvocation by our own then remove Castle.Core dependency? Does it have side effect in abp framework?

**Comment by hikalkan** [comment]
Do you say that we implement dynamic proxying in the ABP framework? It is not easy. Even Microsoft is using Castle.Core for dynamic proxying: https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Proxies/EFCore.Proxies.csproj#L19

**Comment by hcqhuy** [comment]
Understood. Thanks.
