### ISSUE TITLE
`AddObjectAccessor` error `Cannot modify ServiceCollection after application is built.`

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#11101]
Related to #10928 

https://github.com/dotnet/aspnetcore/pull/34981/files

The **AddHangfire configuration action** will exec after the application starts, and the **ServiceCollection** is read-only at this time.

```cs
public override void ConfigureServices(ServiceConfigurationContext context)
{
    context.Services.AddHangfire(configuration =>
    {
        context.Services.ExecutePreConfiguredActions(configuration);
    });
}
```

**Comment by maliming** [comment]
Use https://github.com/abpframework/abp/pull/11130 instead.

**Comment by MouadAmzil** [comment]
check you don't build anything after **`builder.Build()`**  .

**Comment by Trkrkrl** [comment]
> check you don't build anything after **`builder.Build()`** .

Yes , that's worked. Thank You
