### ISSUE TITLE
ISoftDelete Claims

### ISSUE THREAD

**Issue by anaya-upadhyay** [abpframework/abp#11116]
* **ABP Framework 4.4.4**.
* Database provider (EF Core / MySQL)
* **Reference to ISoftDelete claims it is defined in Volo.Abp.Data but it could not be found**

* Steps 
 - Downloaded a new Abp Project.
 - Downgraded .NET version from 6.0 to 5.0
 - Updated all the references from the project that this new project is shared from.
 - Build Succeeded
 - Created an Interface inheriting IApplicationService.
 - Created an implementation service for the interface.
 - Creating a readonly IRepository for the entity gives me this error.

![image](https://user-images.githubusercontent.com/16795691/147656980-843c9362-1f36-407f-998a-0fa3eed79eaf.png)

**Comment by maliming** [comment]
> Downgraded .NET version from 6.0 to 5.0

You can use CLI to create old version project.

```cs
abp new BookStore -v 4.4.4
```

**Comment by anaya-upadhyay** [comment]
I created a modular application using the cli as you suggested with `--no-ui`  and `MySql` as the parameter

**abp new UtilityServiceBackEnd -t module --no-ui --database-management-system MySQL --database-provider ef -v 4.4.4**

![image](https://user-images.githubusercontent.com/16795691/147660780-a7420174-474d-44f5-b18b-19076b2f535a.png)

This got created:
![image](https://user-images.githubusercontent.com/16795691/147660891-1821a75c-9064-4e3f-9419-3db049f8e80a.png)

Inside src folder:
![image](https://user-images.githubusercontent.com/16795691/147660927-e61330e3-db3e-456f-8cb5-8939f3dd8ed3.png)

How did the Cli ended up creating MongoDB?
