### ISSUE TITLE
refresh token - tired app -mvc ui 

### ISSUE THREAD

**Issue by abu7midan** [abpframework/abp#11122]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**. 4.4
* Your **User Interface** MVC
* Your database provider(EF Core

* Steps needed to **reproduce** the problem.

1- assume that i have 3ird party identity server 
2- web app use identity using OpenID
3- when i have 2 min expiry of token from 3rid part identity
i have page with 3 requests on click button 

the scenario is the first request will refresh the token with identity authenticator with success.
second with send old token for refresh then the identity will exception that

**Comment by maliming** [comment]
hi

This is more related to IDS, not ABP. You can search it in Google.

**Comment by abu7midan** [comment]
maliming

Hello thanks for replying. Actually  this is rated to update token in http of abp client after success the first one 

We are using tired abp but with other ids .. i saw abp.js 

And abo jquery not supported refresh token without refresh the page it self
