### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by klapatyivasyl** [abpframework/abp#11138]
How to configure the test project to use the existing database and real db connection there?

**Comment by maliming** [comment]
Please check this class.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.EntityFrameworkCore.Tests/EntityFrameworkCore/MyProjectNameEntityFrameworkCoreTestModule.cs#L18

**Comment by klapatyivasyl** [comment]
@maliming I use the version of ABP 6.4.0 so there is no methods to override like in the case from the link.
By the way, I tried another ways to use the real database like instantiating the DbContext with configs of real database, and it works properly. But the repositories are still using the inmemory db. So,the next question is: how can I replace the db context or it's configs which is used in repositories?
Thank you in advance.

**Comment by klapatyivasyl** [comment]
Thanks!
