### ISSUE TITLE
official abp helper on vs code

### ISSUE THREAD

**Issue by KaungZawHtet** [abpframework/abp#11140]
It's better to have an abp helper extension on vs code.

**Comment by berkansasmaz** [comment]
Unfortunately, we have no such plans at the moment.

However, you can use the tool mentioned[ in this article](https://community.abp.io/posts/code-faster-with-abpx-in-visual-studio-code-f0pzw9h4).


<hr> 

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
