### ISSUE TITLE
An ERR " http status 400"  occurred after  upgraded to 5.0

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#11146]
the parameters don't match:
- http url parameter join by ','
![234](https://user-images.githubusercontent.com/30622318/147814650-7c52df12-d08c-4082-96d3-30c33135fc44.png)

- swagger parameter 
![2021-12-31_160438](https://user-images.githubusercontent.com/30622318/147811275-b219f6be-e6ce-4c88-b63c-b58c8ed4c639.png)
![2021-12-31_155211](https://user-images.githubusercontent.com/30622318/147811026-05ee1a51-cd2e-4347-ad0a-e7b248435ca8.png)

- This is a service generated by proxy
![2022-01-03_093253](https://user-images.githubusercontent.com/30622318/147894680-2744f198-5292-4ca5-9ad7-8e662cf710fa.png)

**Comment by iyilm4z** [comment]
@hexianggui could you please share **the har file** with us to investigate better on the issue by looking at your network traffic. Please do it on **an incognito window** to prevent saving sensitive data. 

Here is how to save it: 

![image](https://user-images.githubusercontent.com/9105939/147836129-f1e0a9db-1354-4983-befc-62cd68668758.png)
