### ISSUE TITLE
How do we hide pages in menu for user with no permission?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11141]
* Your **ABP Framework version**. 5.0.1
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: Blazor Server
* Your database provider(EF Core/MongoDB): EF
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Have not been able to find this in the documentation. How do we hide menu items for pages that the current user (if any) does not have access to in the menu? 

We have a start page that does not require authentication and on that all menu items are displayed even if the current user (if any) doesn't have permission to use it. If they try to visit the pages, they won't be able to as they don't have permission for it, but we don't want them to see pages which they can't access. Thanks.

**Comment by improwise** [comment]
A special use case here can also be that you have created a submeny, like "BackOffice", containing three pages and we want to either hide the entire submenu if the current user lacks backoffice permissions (permission set on BackOffice menu) or perhaps hide it in case the user does not have access to any of the pages in it (permissions set only on the subpages). 

How would you go about implementing something like this in ABP? Thanks.

**Comment by maliming** [comment]
Doesn't it work for you?

https://docs.abp.io/en/abp/latest/UI/Blazor/Navigation-Menu#authorization

**Comment by improwise** [comment]
> Doesn't it work for you?
> 
> https://docs.abp.io/en/abp/latest/UI/Blazor/Navigation-Menu#authorization

Ah, I had missed that. It should probably be referenced somehow from the authorization and authentication pages that is also available in the same section (even though it is perhaps indirectly referenced via AuthorizationService.IsGrantedAsync).

But how are we supposed to use this, surround every page (menu item) with something like:

```
if (await context.IsGrantedAsync("BackOffice"))
{
}
```

and then reuse the policy created for each page? Ideally you would want to connect something like that to being a member of a role instead of each page having their own unique security settings. Or perhaps the general idea is that it is up to each implementation to solve this in whatever way seems most appropriate for that implementation?

I guess you could always create a permission like "BackOfficePermission" and then assign that to the role BackOffice but I am afraid that might be a bit confusing to maintain for non developers with page and group/role permissions being side by side. I guess we could always do something like inject ICurrentUser and check if CurrentUser.IsInRole(...) but not sure if that might have unintentional consequences?

**Comment by maliming** [comment]
You can get some services like `ICurrentUser` from `context`.

**Comment by improwise** [comment]
> You can get some services like `ICurrentUser` from `context`.

Thanks. Is the ICurrentUser.IsInRole() the recommended solution to this scenario? I saw some previous replies along the line "always use permissions" but for this use case, that seems a bit off compared to just checking if user is member of a role.

**Comment by maliming** [comment]
> Is the ICurrentUser.IsInRole() the recommended solution to this scenario? 

If you want to check the role of the current user, yes, you can use it, and you can also check whether the current user is authenticated.

You can resolve other services from the context to check.

**Comment by improwise** [comment]
> > Is the ICurrentUser.IsInRole() the recommended solution to this scenario?
> 
> If you want to check the role of the current user, yes, you can use it, and you can also check whether the current user is authenticated.
> 
> You can resolve other services from the context to check.

Thanks. We used:

`var currentUser = context.ServiceProvider.GetRequiredService<ICurrentUser>();
`
which seems to work. 

One thing we noticed is that admin users does not seem to list more roles than Admin even though the have access to all the roles AFAIK. This is probably correct unless you actually add them to those roles or just include an admin-check when generating the menu. 

I
