### ISSUE TITLE
Problem with AbpIdenity permission

### ISSUE THREAD

**Issue by chaouanabil** [abpframework/abp#11154]
### Question / issue

We are using abp version 4.3.1.
We have two projects (created as application template). solution A and B, HttHost project from solution A references HttpProject from solution B.
the project run without problem, but when trying to call Application-Configuration endpoint from project, we get the following error:

![image](https://user-images.githubusercontent.com/19364848/147878881-bf1bef22-39bc-4538-8908-23f5b700a997.png)

we have tried to remove all references to abp.Identity module in project B, but the problem persists.

Please, do you have any idea how we can solve this prolem.

Thank you.

**Comment by maliming** [comment]
Can you share a simple project and steps to reproduce the problem?

**Comment by afresh** [comment]
You maybe added 2 same permission groups.
Check your permissions which use the function `AddGroup`.

**Comment by chaouanabil** [comment]
Thank you for your answers.
we have fixed the issue, this issue is caused because we had reference to two versions of Volo.Abp.Identity  (community and commercial version as shown here ).

![image](https://user-images.githubusercontent.com/19364848/148084322-fcfe86cf-dcba-4b09-984d-66d0dd5bd04a.png)

At the begining, we have removed the reference to Volo.Abp.Identy.HttpApi in HttpApi Project , but the issue persisted because we haven't removed it from ApplicationContracts (where PermissionDefinitionProvider are defined) project. 
After removing it from all the project and keep just the pro version the issue is solved.

**Comment by chaouanabil** [comment]
> You maybe added 2 same permission groups. Check your permissions which use the function `AddGroup`.

yes it is caused by trying at add a permissionsGroup with the same name, but it wasn't our permissions group. it was AbpIdenity which is defined in Abp.Identity Module.
the idea that Abp framework auto-discover all the permissionProviders by reflection and call the define method of those providers. in our case it discovered two that define the same permission group name "AbpIdentity", one from community version and the another from pro/commercial version.
