### ISSUE TITLE
ConfigureMainMenuAsync() isn't async

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11155]
* Your **ABP Framework version**. 5.0.1
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI Blazor Server UI

(This could be an ABP Suite problem as we have used that to generate the solution)

Just noticed that:

`private Task ConfigureMainMenuAsync(MenuConfigurationContext context)`

while being named async seems to lack the "async" declaration so code like:

```
if (await context.IsGrantedAsync("MyPermissionName"))
{
    //...add menu items
}
```

won't work. 

Not sure if this is intentional in some way and we are supposed to drop await instead or if it is a bug.

**Comment by improwise** [comment]
This might be related to https://github.com/EasyAbp/AbpHelper.CLI/pull/154

**Comment by maliming** [comment]
Are you using ABP Suite?

**Comment by improwise** [comment]
> Are you using ABP Suite?

Yes, as mentioned in OP.

**Comment by maliming** [comment]
ok. Please feedback on https://support.abp.io

**Comment by improwise** [comment]
What I can see the same problem exists also in the non ABP Suite generated applications this is why I initially reported it here instead of the ABP Commercial specific area.

**Comment by improwise** [comment]
> ok. Please feedback on https://support.abp.io

What I can see the same problem exists also in the non ABP Suite generated applications this is why I initially reported it here instead of the ABP Commercial specific area.
