### ISSUE TITLE
Delete the database after adding properties in mongodb

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#1117]
I am using mongoDb. Every time you add or delete attributes, you must delete the database. How do I fix this?

![Capture](https://user-images.githubusercontent.com/10234503/57665977-606c7200-7628-11e9-9011-526e30c16ff0.PNG)

**Comment by hikalkan** [comment]
Are you adding property to IdentityUser? How?

**Comment by nguyendev** [comment]
I cannot use appUser in mongodb, so I have custom IdentityUser at
https://github.com/abpframework/abp/tree/master/modules/identity/src/Volo.Abp.Identity.Domain and It's working but every time I add or delete attributes, I must delete the database

**Comment by hikalkan** [comment]
Can you share your custom IdentityUser ?

**Comment by nguyendev** [comment]
Yes, It's here
[Volo.Abp.Identity.Domain.zip](https://github.com/abpframework/abp/files/3178645/Volo.Abp.Identity.Domain.zip)

**Comment by hikalkan** [comment]
So, you have copied this module's source code to your application and customized it?

**Comment by nguyendev** [comment]
yes it is.

**Comment by nguyendev** [comment]
Can you help me solve this problem. I need it to finish the project this month

**Comment by maliming** [comment]
@nguyendev 
Can you provide a project to reproduce the problem?

**Comment by nguyendev** [comment]
It's here:
https://drive.google.com/file/d/1MFiEamiYaaKB_lgVk7iV6KpjY0aQtVOg/view?usp=sharing

**Comment by maliming** [comment]
Thanks, I will check it out.

**Comment by maliming** [comment]
@nguyendev 

I think this problem has nothing to do with abp.
Please refer to: http://mongodb.github.io/mongo-csharp-driver/2.7/reference/bson/mapping/schema_changes/#a-member-has-been-removed

**Comment by nguyendev** [comment]
Thanks, I will try

**Comment by hikalkan** [comment]
Try this on your ConfigureServices:

````csharp
if (!BsonClassMap.IsClassMapRegistered(typeof(AggregateRoot<Guid>)))
{
    BsonClassMap.RegisterClassMap<AggregateRoot<Guid>>(map =>
    {
        map.AutoMap();
        map.MapExtraElementsProperty(
            "ExtraProperties"
        );
    });
}
````

**Comment by hikalkan** [comment]
This should be fixed with the map I defined. It will not be needed after v0.18 release.
