### ISSUE TITLE
Errors thrown in ApplicationService are not parsed on the client

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#11186]
* Your **ABP Framework version**: 5.0.1 (edited: had wrong version here first)
* Your **User Interface**: Razor pages
* Your database provider(EF Core/MongoDB) : EF Core

I have created a custom appservice that implement `IApplicationService`. It has one method that when it fails throw a `UserFriendlyException`. Endpoint is generated using [Auto API Controllers](https://docs.abp.io/en/abp/4.4/API/Auto-API-Controllers) and is called from javascript with:

```JavaScript
path.to.service.bookShipment(shipment)
            .then(function(result) {
                console.log('book shipment done', result);
                abp.notify.info('Shipment created!');
            });
```

It properly returns a 403 with my message in the response:
![image](https://user-images.githubusercontent.com/1492596/148181537-bc65382b-0e86-4cf6-988a-0f48ada3fd2e.png)

But that error is not parsed properly on the client, jqXHR.responseJSON is undefined
![image](https://user-images.githubusercontent.com/1492596/148181698-d9d0f0ea-f204-4a30-99d5-f52d83bf4362.png)

So all I get on the client is an unhandeled response:
![image](https://user-images.githubusercontent.com/1492596/148181802-63fa4a57-e529-4c22-93e1-d7e08b968db5.png)

Any clue to what I may be missing or is this a bug?

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by martenw** [comment]
> * Steps needed to **reproduce** the problem.

To test I have set up a clean new appservice that work as expected, will try to isolate what the issue is but most likely it is in my own project code.

**Comment by martenw** [comment]
The error was caused by my method returning a string, how can i return a string as response to the client?

```C#
public async Task WorkingWithEmptyResponse()
{
    throw new UserFriendlyException("My friendly error message");
}
public async Task<string> NotWorkingWithStringResponse()
{
    throw new UserFriendlyException("My friendly error message");
}
```

**Comment by martenw** [comment]
Ok, so it was just string that was the issue, switching to a Dto in the response works fine:

```C#
public async Task<SomeRandomDto> TryClientErrorAsync()
{
    throw new UserFriendlyException("My friendly error message");
}
```

Guessing that you are extending the class in some way that is not working if it is just a string. Is this limitation somewhere in the docs that I have missed? Otherwise I think that would be useful.

**Comment by realLiangshiwei** [comment]
Hi,

This is a problem when the return type is a string,  we can enhance the client-side error handling code.

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Http/Volo/Abp/Http/ProxyScripting/Generators/JQuery/JQueryProxyScriptGenerator.cs#L126

**Comment by martenw** [comment]
Really impressive how quickly you resolve reported issues, thank you @realLiangshiwei!
