### ISSUE TITLE
Adding endpoint descriptions in swagger for services from separate modules

### ISSUE THREAD

**Issue by dkaczor97** [abpframework/abp#11194]
* **ABP Framework version**. 5.0.1

I am trying to create a better documentation for my API by adding a ///summary for every public method. I want it to be visible in my swagger. I already know that I cannot add summary in AppServices, I have to create Controllers and add summaries there. I also configured the project following [this document](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-5.0&tabs=visual-studio).
What should I do to see summaries of methods defined in separate modules? When I added Controllers in .HttpApi projects their descriptions were not visible in swagger. Is this even possible to achieve that?

**Comment by xyfy** [comment]
I think now swagger is reading a xml to load summary ,set  **GenerateDocumentationFile** to true in project file will help you?

**Comment by sanghel-payoff** [comment]
bump? am also interested in enabling SwaggerUI description from xmldoc comments

there seems to be no extension point to enable xmldocs as described in the Microsoft docs...

```
public override void OnApplicationInitialization(ApplicationInitializationContext context)
{
       ....
        app.UseSwagger();
        app.UseAbpSwaggerUI(options =>
        {
            options.SwaggerEndpoint("/swagger/v1/swagger.json", "Blox API");

            var configuration = context.ServiceProvider.GetRequiredService<IConfiguration>();
            options.OAuthClientId(configuration["AuthServer:SwaggerClientId"]);
            options.OAuthClientSecret(configuration["AuthServer:SwaggerClientSecret"]);

            options.DocExpansion(DocExpansion.None);
        });
       ....
}
```

**Comment by sanghel-payoff** [comment]
Never mind, I've found that SwaggerGen is already setup in the `...HttpApiHostModule.ConfigureSwagger` method..

Still, I've tried adding the xml doc files, as described below

```csharp
private static void ConfigureSwagger(ServiceConfigurationContext context, IConfiguration configuration)
{
    context.Services.AddAbpSwaggerGenWithOAuth(
        configuration["AuthServer:Authority"],
        new Dictionary<string, string>
        {
            {"Project", "Project API"}
        },
        options =>
        {
            //options.SwaggerDoc("v1", new OpenApiInfo {Title = "Project API", Version = "v1"});
            options.DocInclusionPredicate((docName, description) => true);
            options.CustomSchemaIds(type => type.FullName);

            options.SwaggerDoc("v1", new OpenApiInfo {
                Title = "Project API",
                Version = "v1",
                TermsOfService = null,
                Description = null,
                License = new OpenApiLicense { Name = "Proprietary" }
            });
            IncludeXmlDocFiles(options, $"Project.Namespace.*.xml");
        });
}

private static void IncludeXmlDocFiles(SwaggerGenOptions options, string pattern)
{
    string WildcardToRegex(string wildcardPattern)
    {
        return $"^{Regex.Escape(wildcardPattern).Replace("\\*", ".*").Replace("\\?", ".")}$";
    }

    //Find XML Comments File In Pattern
    var basePath = AppContext.BaseDirectory;
    var regex = new Regex(WildcardToRegex(pattern));

    var allDirectoryFiles = Directory.GetFiles(basePath, "*.*", SearchOption.TopDirectoryOnly).ToList();

    var xmlDocFiles = allDirectoryFiles.Where(p => regex.IsMatch(Path.GetFileName(p))).ToList();
    foreach (var xmlDocFilePath in xmlDocFiles)
    {
        options.IncludeXmlComments(xmlDocFilePath, true);
    }
}
```

Xml files are generated, found and included via `IncludeXmlComments`, but still, APIService Actions that do have comments (visible in the xml files also) DO NOT show up on the Swagger UI...

What am I missing?

@maliming any ideas ?

**Comment by maliming** [comment]
> but still, APIService Actions that do have comments (visible in the xml files also) DO NOT show up on the Swagger UI...

Can you share a simple project?
