### ISSUE TITLE
Data annotation with ABP base clases  like AuditedEntityDto?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11196]
Is it possible to use data annotation for the properties defined in ABPs base classes like AuditedEntityDto?

Lets say we have something like

```
    public class CustomerNoteDto : AuditedEntityDto<int>
    {
        [Required]
        public int CustomerId { get; set; }

        [Display(Name = "Anteckning")]
        [Required(ErrorMessage = "{0}: Detta fält måste anges.")]
        public string Note { get; set; }

    }
```

and we would like to set a DisplayName like "Skapad" for something like CreationTime which is inherited from the base class?

That's Swedish  BTW :)

**Comment by improwise** [comment]
Is the recommended approach in this case just do do something like this and just define the property yourself and then use Data Annotation on that? Any obvious drawbacks?

```
        [Display(Name = "Skapad")]
        public new DateTime CreationTime { get; set; }

```

**Comment by maliming** [comment]
You can create your own `AuditedEntityDto` class, and add attributes to the properties.

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Ddd.Application.Contracts/Volo/Abp/Application/Dtos/AuditedEntityDto.cs#L10-L17

**Comment by improwise** [comment]
Thanks. Ideally, we would try to stay away from changing the ABP "framework code" if possible, but I guess your solution has the big advantage of applying to all DTOs using the same base class all in once.

**Comment by improwise** [comment]
Thanks. Ideally, we would try to stay away from changing the ABP "framework code" if possible, but I guess your solution has the big advantage of applying to all DTOs using the same base class all in once.
