### ISSUE TITLE
Problem with Localization

### ISSUE THREAD

**Issue by 358172541** [abpframework/abp#11217]
* ABP Framework version: 
5.0.1

* User Interface: 
Angular

* Database provider: 
EF Core

* Steps to reproduce the problem: 
Generates a new solution based on the ABP startup templates like: abp new Demo -u angular -csf.
In angular app, click login button and redirect to oidc login page, change language to another language, like: "en" to "zh-Hans".
Login with default admin account and it jump back to angular app.

But the angular app is still "en".

**Comment by maliming** [comment]
This is expected, you need to implement it yourself. We have similar implementation in the commercial.

**Comment by 358172541** [comment]
Ok, thanks.

**Comment by 358172541** [comment]
> This is expected, you need to implement it yourself. We have similar implementation in the commercial.

Ok, thanks.
