### ISSUE TITLE
An error occurred when the host started.

### ISSUE THREAD

**Issue by xiaomazz** [abpframework/abp#11218]
![image](https://user-images.githubusercontent.com/52307384/148405964-6a7434c5-5f2d-4a52-bf46-142ad2d45dce.png)

**Comment by gdlcf88** [comment]
Maybe you should double-check whether all packages are upgraded to ABP 5.0.1.

**Comment by xiaomazz** [comment]
我确定所有的包都升级到了5.0.1

**Comment by maliming** [comment]
Use AutoMapper `10.1.1` to solve.

```
<PackageReference Include="AutoMapper" Version="10.1.1" />
```
