### ISSUE TITLE
how can generated dbset automatically

### ISSUE THREAD

**Issue by zyy314680012** [abpframework/abp#11227]
my project has hundred of entities
in ef core we can use 
`
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	base.OnModelCreating(modelBuilder);

	var baseType = typeof(Entity);
	baseType.Assembly.GetTypes().Where(p => p.IsClass && !p.IsAbstract && baseType.IsAssignableFrom(p))
		.ToList().ForEach(p =>
		{
			modelBuilder.Entity(p);
		});
}
`

but in abp project .
this code not work.

Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2

**Comment by maliming** [comment]
Please refer to https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L97-L117

**Comment by zyy314680012** [comment]
> Please refer to https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L97-L117

TKS
