### ISSUE TITLE
set redis cache fail without any error when cache key length greater than 17

### ISSUE THREAD

**Issue by adeewu** [abpframework/abp#11235]
set redis cache fail without any error when cache key length greater than 17

```
IDistributedCache<TemplateCacheItem> cache;

await cache.SetAsync("abcdefghiabcdefgh", new TemplateCacheItem())
```

- ABP version：5.0.1
- Microsoft.AspNetCore.SignalR.StackExchangeRedis：6.0.1

**Comment by realLiangshiwei** [comment]
Cannot be reproduced

![image](https://user-images.githubusercontent.com/16813853/148629812-f315af74-feb3-4dec-b3de-ea2f2d680d44.png)

**Comment by adeewu** [comment]
ok, i will double check with redis instance, may be wrong with redis version

**Comment by adeewu** [comment]
check result:
use docker of redis:alpine will be reproduced, change to redis:5.0-alpine save success
