### ISSUE TITLE
Hotreload (Abp v5.0.1) in module not working?

### ISSUE THREAD

**Issue by visuellsoft** [abpframework/abp#11237]
Hello,

is hotreload only work in the main project?
When I change something in a module HOTRELOAD does not work - is this correct?

Thanks
BR Thomas

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/10947#issue-1080459089

Since hot reload does not work well for **ProjectReference**, we add an option(**EnableRazorRuntimeCompilationOnDevelopment**) to enable it during development.
