### ISSUE TITLE
Database Seed problem

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1123]
For current templates, samples & applications for ABP, we seed initial data on application initialization. This has a few problems;

1. In a clustered environment, multiple app instances can seed db concurrently which may cause multiple-insert of a seed data.
2. Checking seed data on app initialization makes the initialization slower.

We should find a better way. Examples;

* We may think to create a distributed lock system. Using such a lock, we can ensure that only one instance writes the seed data in a time. However, this is a little complex. And also it only solves the problem 1, not solves the 2nd problem (even makes it worse).
* We may always use an external console application that runs migrations and seeds database. This solves both problems, however it brings an additional application.

**Comment by dejancg** [comment]
What's the problem with seeding data with migration, using OnModelCreating?

**Comment by hikalkan** [comment]
It has a few restrictions;

1. It can not work with service dependency injection since DI is not available with EF Core tooling (update-database command).
2. This couples db seed code to EF core. With our current design, we use same code for mongodb too.
3. We may want to change or add new seed code without adding a new database migration.

**Comment by marcelo-maciel** [comment]
On another system, to solve these problems, i did:
1. A parameter called dbseed (0/1), default 0. The unique migration that run with the application.
2. A url that when called, execute the databae seed if parameter enableseed is 0
  If 0, dbseed is changed to 1 and starts seeding the app. If one exception occours, dbseed changed again to 0.

**Comment by hikalkan** [comment]
We may need some initial data on application startup (like a list of supported languages).

**Comment by hikalkan** [comment]
Created an external console application that runs migrations and seeds database.
Application name is MyCompanyName.MyProjectName.DbMigrator.
It can also available if you choice MongoDB. Schema migration is not available for mongodb, but data seed is still available.

So, when you run MyCompanyName.MyProjectName.DbMigrator, you are sure that your db is up to date. You can still use EF Core's `Update-Database` on development, but it only migrates db schema. So, I suggest to always use MyCompanyName.MyProjectName.DbMigrator.

With this new app, I removed db seed code from app initialization which also improved startup performance.

**Comment by AIexandr** [comment]
Thank you for great work! But it will be a bit better if the templated project will say "Please run  the DbMigrator tool" if it find no seed data. It could save couple hours:)
