### ISSUE TITLE
configureawait.props build error in Abp 5.0.1 when add a module

### ISSUE THREAD

**Issue by visuellsoft** [abpframework/abp#11233]
Hello,

I'm currently testing Abp 5.0.1, but I get an error after I build the solution when I add a module.

`abp new Test`
`cd Test`
`abp add-module ModuleA --new --add-to-solution-file`

The I open VisualStudio 2022 and build the solution. I get the error message:
Project "C:\temp\configureawait.props" was not imported by "C:\temp\TestAbp2\modules\ModuleA\src\ModuleA.Installer\ModuleA.Installer.csproj" at (3,5), due to the file not existing
Project "C:\temp\common.props" was not imported by "C:\temp\TestAbp2\modules\ModuleA\src\ModuleA.Installer\ModuleA.Installer.csproj" at (4,5), due to the file not existing.
The imported project "C:\temp\configureawait.props" was not found. Confirm that the expression in the Import declaration "..\..\..\..\..\configureawait.props" is correct, and that the file exists on disk.

When I open the file: C:\temp\TestAbp2\modules\ModuleA\src\ModuleA.Installer\ModuleA.Installer.csproj I found the lines:
    <Import Project="..\..\..\..\..\configureawait.props" />
    <Import Project="..\..\..\..\..\common.props" />

configureawait.props I can't find on the filesystem and the common.props is one folder above
    <Import Project="..\..\..\..\common.props" />

I comment the first line out and the second I change the line like above

BR Thomas

**Comment by xyfy** [comment]
pay attention to **C:\temp\common.props**  not **configureawait**

**Comment by gdlcf88** [comment]
https://github.com/abpframework/abp/pull/11082
