### ISSUE TITLE
eShopOnAbp: Missing static proxy - profile update error

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#11238]
Account Manage in AuthServer(localhost:44330) resulting in **endpoint not found** when updating profile.

**Comment by maliming** [comment]
Maybe we should move the HttpApi and HttpApi.Client.

![image](https://user-images.githubusercontent.com/6908465/148667055-d2baa2f4-86a6-4a83-b533-85521e4a15bb.png)
