### ISSUE TITLE
Update entity every time CreationTime change.

### ISSUE THREAD

**Issue by mehmetuken** [abpframework/abp#11230]
CreationTime change every update entity.  I try CrudAppService.

Abp Version: 5.0.1 Database: PostgreSQL

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by mehmetuken** [comment]
Test Repo: https://github.com/mehmetuken/Demo.Issue11230

Create Entity:
![create entity](https://user-images.githubusercontent.com/9348193/148528356-d80db06a-a6d6-46fd-bcef-247986d88f32.png)

Update Entity:
![update entity](https://user-images.githubusercontent.com/9348193/148528370-22cc5c2b-dda8-4bad-be92-71280d981f46.png)

Sql Before:
![Screen Shot 2022-01-07 at 13 12 01](https://user-images.githubusercontent.com/9348193/148528773-422c0b6b-c780-4a0b-8c67-e2411165b3f0.png)

Sql After:
![Screen Shot 2022-01-07 at 13 12 36](https://user-images.githubusercontent.com/9348193/148528810-cede7b01-ac33-4f87-82f6-2c6315a8db38.png)

**Comment by maliming** [comment]
Please try to reproduce in the unit test.

**Comment by mehmetuken** [comment]
> Please try to reproduce in the unit test.

I create unit test. Test not failing. Is this PostgreSQL special problem?

**Comment by JadynWong** [comment]
> > Please try to reproduce in the unit test.
> 
> I create unit test. Test not failing. Is this PostgreSQL special problem?

Did you generate ef migrations before adding the `AbpEntityFrameworkCorePostgreSqlModule`?
The type of the DateTime column should be `timestamp without time zone`.

https://www.npgsql.org/efcore/release-notes/6.0.html#opting-out-of-the-new-timestamp-mapping-logic

https://github.com/abpframework/abp/pull/10314
https://github.com/abpframework/abp/issues/10273

![image](https://user-images.githubusercontent.com/13699353/149075483-3bec502f-00e9-416d-98dd-098acab09a40.png)

**Comment by mehmetuken** [comment]
Hi @JadynWong ,
I create project beginning with PostgreSQL
 abp new Demo.Issue11230 -t app -u none -dbms PostgreSQL  

but my datetime's:
![Screen Shot 2022-01-12 at 09 45 35](https://user-images.githubusercontent.com/9348193/149077615-afedbd2a-a925-46e3-b331-288e64cd254c.png)

**Comment by JadynWong** [comment]
When the `Host project` is set up as a startup project, the generated type is `timestamp without time zone`. 
Run `Add-Migration Inital` with VS Package Manager Console.

OR

Run `dotnet ef migrations add Inital -s ..\Demo.Issue11230.HttpApi.Host\Demo.Issue11230.HttpApi.Host.csproj` with dotnet ef tool.

The reason is not yet known.

**Comment by maliming** [comment]
Try to add `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);` to https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContextFactory.cs#L13

**Comment by mehmetuken** [comment]
> Try to add `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);` to https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContextFactory.cs#L13

It's work. Thanks.
