### ISSUE TITLE
Align module & class names

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1124]
For example, `AbpAuditLoggingDomainModule` uses the `Abp` prefix, but `BackgroundJobsDomainModule` does not use it.
We will add prefix for standard Abp modules.

**Comment by wayneboyles** [comment]
#1175 has been submitted for review.  Please let me know if there's anything you see that I missed and I'll be happy to continue to work on it.

**Comment by tuyndv** [comment]
Dear @hikalkan,

Please don't use Abp prefix. Because these classes are already under Abp namespace.

Thanks
