### ISSUE TITLE
About ABP & Docker & Kubernetes.

### ISSUE THREAD

**Issue by afresh** [abpframework/abp#11248]
About `Docker` & `Kubernetes`, are there any relevant documents on how to deploy the `eShopOnAbp` project or the `MicroserviceDemo` project to production environment?

**Comment by antosubash** [comment]
Take a look here https://github.com/abpframework/eShopOnAbp/tree/main/etc you have everything you need to deploy.

**Comment by afresh** [comment]
Sorry, I haven't had time to practice yet. Please extend it a little longer.
