### ISSUE TITLE
Error upgrading to ABP 5.1,  Extended data error

### ISSUE THREAD

**Issue by justlucky** [abpframework/abp#11240]
![微信图片_20220109103911](https://user-images.githubusercontent.com/247791/148667064-573c031b-0ed5-4b0e-a098-256fdbe56f65.png)
![微信图片_20220109103919](https://user-images.githubusercontent.com/247791/148667066-5a726d04-e88c-452e-b674-bfb229e28838.png)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by justlucky** [comment]
Resolved, modify extrapropertiesvalueconverter to support JSON net
