### ISSUE TITLE
Always create seperate AppServices for DomainServices or combine?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11252]
Is it recommended in ABP to create a separate AppService for each DomainService or is it recommended to instead combine several DomainServices in one AppServices where the alternative would be AppServiecs that are very "bare bone". Like for stuff like lookup values etc. 

Assume something like having a DocumentsAppService to handle CRUD for Documents and that each Document has a DocumentType property which is just a lookup value that is only used for this purpose. Would it then make sense to create both an DocumentAppService and a DocumentTypeAppService and use both in the Presentation-layer or just  include an extra GetDocumentTypeListAsync() method in the main DocumentAppService? Combining them would also mean that you avoid getting DocumentTypeAppService exposed in Swagger etc which is probably a good thing since it doesn't have any real value by itself. 

Or would it perhaps be better to have each returned Entity from the DomainLayer include a "DocumentTypes" list in a more complex Entity including both a list of the Documents and all available DocumentTypes for dropdowns etc?

I realize that this might be a quite opinionated topic so I guess what I am asking for here is mainly if ABP as a framework has any recommendations here and what might be possible advantages/disadvantages of each?

**Comment by improwise** [comment]
Did have a look at "Application Services Best Practices & Conventions" but found it didn't really answer this particular question

_Using Other Application Services
Do not use other application services of the same module/application. Instead;
Use domain layer to perform the required task.
Extract a new class and share between the application services to accomplish the code reuse when necessary. But be careful to don't couple two use cases. They may seem similar at the beginning, but may evolve to different directions by time. So, use code sharing carefully.
Can use application services of others only if;
They are parts of another module / microservice.
The current module has only reference to the application contracts of the used module._

https://docs.abp.io/en/abp/4.4/Best-Practices/Application-Services#using-other-application-services

**Comment by gterdem** [comment]
Domain service is an exposure of _encapsulated functionality of your domain_. If your application logic requires functionality of different domains, there is no problem with using multiple domain services in an application service.
