### ISSUE TITLE
Cannot localize text on login page

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#11255]
* Your **ABP Framework version**: 5.0.1

I have tried to localize the string _"Not a member yet?"_ found at the bottom of the login screen. The other strings of the login page could be translated just by adding a new translation for the Account-module but I have not been able to find this string at all in the repository? 

![image](https://user-images.githubusercontent.com/1492596/148834237-aa7e6e93-b352-4f0a-ad90-10aab843461d.png)

**Comment by maliming** [comment]
hi

This is the Account Pro module.

```cs
account/src/Volo.Abp.Account.Pro.Shared.Application.Contracts/Volo/Abp/Account/Localization/Resources/en.json

NotAMemberYet

```

**Comment by martenw** [comment]
Thank you @maliming that worked. 

That text was missing from my source file, I have based my translation on: https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/Resources/en.json

Are there more texts used from the document you referenced? I do not have the source of the pro modules.

**Comment by maliming** [comment]
You can manage it in the language management module.
