### ISSUE TITLE
How can I prioritize DataSeedContributor classes working

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#11274]
* Your **ABP Framework version**. 4.3.3
* Your database provider* EF Core

I have several entities :  Product, ProductCategory ,  and Order. 
I override SeedAsync method in DataSeedContributor classes for per entities in TestBase project. I want to run them with priority.

sample order:
1. ProductCategoryDataSeedContributor 
2. ProductDataSeedContributor 
3. OrderDataSeedContributor

How can I prioritize DataSeedContributor working?

**Comment by berkansasmaz** [comment]
You can check it [here](https://github.com/abpframework/abp/issues/2417#issuecomment-566963849).


That's why I'm closing this issue. Feel free to re-open or create a new issue if you have further questions.
