### ISSUE TITLE
Generate code error when add package Volo.Abp.BackgroundWorkers.Hangfire

### ISSUE THREAD

**Issue by wangbin1989** [abpframework/abp#11282]
Abp Version: 5.1.0

`abp add-package Volo.Abp.BackgroundWorkers.Hangfire` generate code `[DependsOn(typeof(AbpBackgroundWorkerHangfireModule))]`

This code lost a letter ‘s’ in works.

The right code is `AbpBackgroundWorkersHangfireModule`.

**Comment by maliming** [comment]
Thanks, It works now.
