### ISSUE TITLE
How to use dependency injection in Elsa workflow

### ISSUE THREAD

**Issue by zhangtingwz** [abpframework/abp#11305]
nice to meet u,
I`m a student
I have an idea to add Elsa workflow in ABP

Then, the user-defined action in the workflow relies on the ibookapplication injected into the teaching to operate the database, but an error is reported directly

**Comment by realLiangshiwei** [comment]
See https://community.abp.io/articles/using-elsa-workflow-with-the-abp-framework-773siqi9
