### ISSUE TITLE
AbpV5.1.1 abp generate-proxy error with Angular 13

### ISSUE THREAD

**Issue by duanzlin** [abpframework/abp#11302]
Run abp generate-proxy with follow errors:
`An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID`

and when downgrade @angular/cli to 12.2.13，the command work fine

**Comment by rqx110** [comment]
duplicate #11075

**Comment by duanzlin** [comment]
> duplicate #11075

My problem happened when project upgraded to latest version and it worked fine  before

**Comment by duanzlin** [comment]
Upgrade abp cli to latest version,  create a new abp solution with command  abp new MyCompany.test -u angular，then run  abp generate-proxy command , and got the same error.
