### ISSUE TITLE
abp new console template bug

### ISSUE THREAD

**Issue by wangbin1989** [abpframework/abp#11304]
abp version: 5.1.1

steps:
```cmd
abp new Sample -t console
cd src/Sample
dotnet run
```

console output:
```C#
[14:41:37 INF] Starting console host.
[14:41:37 INF] Loaded ABP modules:
[14:41:37 INF] - Sample.SampleModule
[14:41:37 INF]   - Volo.Abp.Autofac.AbpAutofacModule
[14:41:37 INF]     - Volo.Abp.Castle.AbpCastleCoreModule
[14:41:37 INF] MySettingName => MySettingValue
[14:41:37 INF] EnvironmentName => Production
[14:41:37 INF] Initialized all ABP modules.
[14:41:37 INF] Hello World!
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Computer\Learn\sample2\src\Sample
```
It looks like there are some bugs with log.

**Comment by maliming** [comment]
> It looks like there are some bugs with log.

eg?

**Comment by wangbin1989** [comment]
The console does not use serilog to output all logs.
![capture_20220113144835292](https://user-images.githubusercontent.com/5661954/149279838-f2e1648d-6e60-4822-93ae-a537e33f2c4a.jpg)

**Comment by rqx110** [comment]
It looks like missing `UseSerilog()`
![image](https://user-images.githubusercontent.com/1829209/149283070-dfffdd74-9827-4d85-a665-2c1b347a8326.png)

**Comment by wangbin1989** [comment]
Serilog add twice?
![2](https://user-images.githubusercontent.com/5661954/149284446-171b9ff8-f616-4f5f-b281-941ff7e414f7.jpg)
