### ISSUE TITLE
Test with In-Process hosting model

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1132]
I haven't tested well, but it seems there is a problem with that.
So, we should test, understand and fix the problem.

1. We can try with a startup template created from https://abp.io/Templates
2. We can start with an empty web project, see if it works, then install ABP manually like https://abp.io/documents/abp/latest/Getting-Started-AspNetCore-Application

**Comment by leonkosak** [comment]
Thank you. :)

**Comment by maliming** [comment]
I found that if I use InProcess mode, I need to add `.UseIIS()` to `BuildWebHostInternal`, Other than that, no changes are required.

```
public static IWebHost BuildWebHostInternal(string[] args) =>
	new WebHostBuilder()
		.UseKestrel()
		.UseContentRoot(Directory.GetCurrentDirectory())
		.UseIIS()
		.UseIISIntegration()
		.UseStartup<Startup>()
		.UseSerilog()
		.Build();
```

**Comment by leonkosak** [comment]
@maliming thank you :)

After this change, have you tried:

1) That Out-of-Process mode is still working
2) That abp.io is still working inside Linux environment (Nginx,..)
3) That temp folders (and other "file system locations") are still working when In-Process mode is in use.

**Comment by maliming** [comment]
@leonkosak Thanks. I will continue to test more details.

**Comment by maliming** [comment]
closed by https://github.com/abpframework/abp/issues/1269
