### ISSUE TITLE
Back ground job

### ISSUE THREAD

**Issue by alaawahbah** [abpframework/abp#11328]
I try this doc https://docs.abp.io/en/abp/4.4/Background-Jobs
but it runs always even i have one record and previous run success
is this right behavior ?

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by alaawahbah** [comment]
there is an error thrown from my code thank you
