### ISSUE TITLE
Postgres timestamp with time zone after updating to the 5.1.1 packages

### ISSUE THREAD

**Issue by GeertVeenstra** [abpframework/abp#11357]
Hello,

After updating my project to the latest packages and creating a new migration, all the datetime columns in my PostGres database are converted to "timestamp with time zone" (previously they were "timestamp without time zone").

I assume this is because the new npgsql 6.0 is used, but I see no  mentioning in the release notes about this breaking change?

Geert Veenstra

**Comment by maliming** [comment]
See 
https://www.npgsql.org/doc/types/datetime.html#timestamps-and-timezones
https://github.com/abpframework/abp/issues/11230#issuecomment-1010746763
https://github.com/abpframework/abp/pull/11284

**Comment by GeertVeenstra** [comment]
I am aware of that, thanks.

When I add 

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

to the EntityFrameworkCoreModule PreconfigureServices of my project then I have no problem (the column changes do not appear in the Migration).

I see for 5.1.1 this was moved to the AbpDbContext.
Any chance this is causing the issue now?

**Comment by maliming** [comment]
How do you add new migrations? `dotnet ef` command?

**Comment by GeertVeenstra** [comment]
Within visual studio Package Manager console --> Add-Migration "Update_To_Abp_5.1.1"

**Comment by maliming** [comment]
Can you try to use dotnet ef command?

**Comment by xxvolvo** [comment]
> AbpDbContext
@maliming 
the same problem both withint  `dotnet ef` and  `visual studio Package Manager console`

**Comment by sanghel-payoff** [comment]
Can definitely confirm this issue, while not even using 5.1.1.

I've started a new solution with AbpSuite 5.0.1 a week ago.
I've subsequently added the initial migration from PackageManagerConsole. This defined all DateTime entity props as `timestamp with timezone`, which is my desired config.

**Without having made any change whatsoever to the sources, and no Nuget package upgrade**, running an Add-Migration today yields a migration that changes the pgsql data type of all DateTime props from `timestamp with timezone` to `timestamp without timezone`.

I have no idea what is causing this change....
I've tried setting

```
Configure<AbpClockOptions>(options =>
            {
                options.Kind = DateTimeKind.Utc;
            });
```

in `ConfigureServices()` of all these modules:

- _*EntityFrameworkCoreModule_
- _*ApplicationModule_
- _*DomainModule_

but the undesired migration is still being generated.


Where is the behaviour for DateTime prop configured during entity configuration, in particular for Npgsql?


This is a really blocking, correctly storing datetimes with timezone information is crucial for a Saas app...

**Comment by xxvolvo** [comment]
> Can definitely confirm this issue, while not even using 5.1.1.
> 
> I've started a new solution with AbpSuite 5.0.1 a week ago. I've subsequently added the initial migration from PackageManagerConsole. This defined all DateTime entity props as `timestamp with timezone`, which is my desired config.
> 
> **Without having made any change whatsoever to the sources, and no Nuget package upgrade**, running an Add-Migration today yields a migration that changes the pgsql data type of all DateTime props from `timestamp with timezone` to `timestamp without timezone`.
> 
> I have no idea what is causing this change.... I've tried setting
> 
> ```
> Configure<AbpClockOptions>(options =>
>             {
>                 options.Kind = DateTimeKind.Utc;
>             });
> ```
> 
> in `ConfigureServices()` of all these modules:
> 
> * _*EntityFrameworkCoreModule_
> * _*ApplicationModule_
> * _*DomainModule_
> 
> but the undesired migration is still being generated.
> 
> Where is the behaviour for DateTime prop configured during entity configuration, in particular for Npgsql?
> 
> This is a really blocking, correctly storing datetimes with timezone information is crucial for a Saas app...

Also add `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);` in `EntityFrameworkCoreModule` `PreConfigureServices`

**Comment by sanghel-payoff** [comment]
@xxvolvo I **DO NOT** require the legacy behaviour, but the new Npgsql 6+ one.

> Starting with 6.0, Npgsql maps UTC DateTime to timestamp with time zone, and Local/Unspecified DateTime to timestamp without time zone; trying to send a non-UTC DateTime as timestamptz will throw an exception, etc.

It is obviously the path forward with Npgsql, and also a better default behaviour.

So the question is, how do I instruct abp to correctly configure DateTime props to `timestamp with timezone`, in all referenced framework modules, and in the abp suite generated modules ?

**Comment by sanghel-payoff** [comment]
I'm not sure if Volosoft is giving the adequate attention to this issue.

Correctly writing / reading DateTime props via EFCore has some non trivial issues, see https://stackoverflow.com/questions/4648540/entity-framework-datetime-and-utc

I'm unsure if / how these aspects are correctly handled by the abpframework.

Tightly related to this, I would consider prioritizing to maximum level the usage of NodaTime in the base framework, as requested by https://github.com/abpframework/abp/issues/263

I cannot wholeheartedly continue using ABP Commercial until solid handling of timezone-rich DateTime information is implemented and documented...

**Comment by nebula2** [comment]
I can confirm that doing the following to ..EntityFrameworkCore -> ..EntityFrameworkCoreModule solves it on Version `5.1.3`.

```cs
public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        // https://github.com/abpframework/abp/issues/11357#issuecomment-1018585181
        Configure<AbpClockOptions>(options =>
        {
            options.Kind = DateTimeKind.Utc;
        });

        // ...
    }
```

Would however be more intuitive if that three lines of code would already be included (in case postgre sql is set as db provider when creating the solution with cli)

**Comment by VAllens** [comment]
Add two lines of code to the `Main` method: 
```C#
 AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
 AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", true);
```
The problem is gone.

**Comment by nebula2** [comment]
@VAllens can you please help me by specifying where this `Main` is? having the same issue and I do not know where to set the options >.<
