### ISSUE TITLE
Exception when starting blazor web site

### ISSUE THREAD

**Issue by GillesFr06** [abpframework/abp#11364]
**ABP Framework version** 5.1.1
**User Interface** Blazor Server
EF Core, MySQL

When I launch the blazor project in IIS Express, I have the exception below in the console.
I only give the first one, as the others following that one are probably caused by that first one.

global.js?_v=637728566121956479:8 
 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: WebAssemblyCachedApplicationConfigurationClient should be initialized before using it.
Volo.Abp.AbpException: WebAssemblyCachedApplicationConfigurationClient should be initialized before using it.
   at Volo.Abp.AspNetCore.Components.WebAssembly.WebAssemblyCachedApplicationConfigurationClient.GetConfigurationByChecking()
   at Volo.Abp.AspNetCore.Components.WebAssembly.WebAssemblyCachedApplicationConfigurationClient.Get()
   at Volo.Abp.AspNetCore.Mvc.Client.RemoteLocalizationContributor.GetResourceOrNull()
   at Volo.Abp.AspNetCore.Mvc.Client.RemoteLocalizationContributor.GetOrNull(String cultureName, String name)
   at Volo.Abp.Localization.LocalizationResourceContributorList.GetOrNull(String cultureName, String name)
   at Volo.Abp.Localization.AbpDictionaryBasedStringLocalizer.GetLocalizedStringOrNull(String name, String cultureName, Boolean tryDefaults)
   at Volo.Abp.Localization.AbpDictionaryBasedStringLocalizer.GetLocalizedString(String name, String cultureName)
   at Volo.Abp.Localization.AbpDictionaryBasedStringLocalizer.GetLocalizedString(String name)
   at Volo.Abp.Localization.AbpDictionaryBasedStringLocalizer.get_Item(String name)
   at Volo.Abp.UI.Navigation.DefaultMenuContributor.Configure(MenuConfigurationContext context)
   at Volo.Abp.UI.Navigation.DefaultMenuContributor.ConfigureMenuAsync(MenuConfigurationContext context)
   at Volo.Abp.UI.Navigation.MenuManager.GetInternalAsync(String name)
   at Volo.Abp.UI.Navigation.MenuManager.GetAsync(String[] menuNames)
   at Volo.Abp.AspNetCore.Components.Web.BasicTheme.Themes.Basic.NavMenu.OnInitializedAsync() in C:\Users\Administrateur\source\repos\MyProject\modules\Volo.BasicTheme\src\Volo.Abp.AspNetCore.Components.Web.BasicTheme\Themes\Basic\NavMenu.razor.cs:line 21
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

So the web page is empty, with the grey circle moving.

How to correct that problem ?

Thanks,
Gilles

**Comment by realLiangshiwei** [comment]
I will check it.

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem.

Please provide full steps to reproduce.

**Comment by GillesFr06** [comment]
The complete trace in the Edge console 👍 
global.js?_v=637728566121956479:8 Debugging hotkey: Shift+Alt+D (when application has focus)
global.js?_v=637728566121956479:8 blazor Loaded 17.45 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
      Loaded ABP modules:
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
      - MyProject.Blazor.MyProjectBlazorModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.Autofac.WebAssembly.AbpAutofacWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Autofac.AbpAutofacModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.Castle.AbpCastleCoreModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.AspNetCore.Components.WebAssembly.AbpAspNetCoreComponentsWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AspNetCore.Mvc.Client.AbpAspNetCoreMvcClientCommonModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Http.Client.AbpHttpClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Http.AbpHttpModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Http.AbpHttpAbstractionsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Json.AbpJsonModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                    - Volo.Abp.Timing.AbpTimingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                      - Volo.Abp.Localization.AbpLocalizationModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                        - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                        - Volo.Abp.Settings.AbpSettingsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                          - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                          - Volo.Abp.Security.AbpSecurityModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                          - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                            - Volo.Abp.Data.AbpDataModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                              - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                                - Volo.Abp.Validation.AbpValidationAbstractionsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                              - Volo.Abp.Uow.AbpUnitOfWorkModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                              - Volo.Abp.EventBus.Abstractions.AbpEventBusAbstractionsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Minify.AbpMinifyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Threading.AbpThreadingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Validation.AbpValidationModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Application.AbpDddApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Auditing.AbpAuditingContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Caching.AbpCachingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Serialization.AbpSerializationModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Authorization.AbpAuthorizationModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Authorization.AbpAuthorizationAbstractionsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Features.AbpFeaturesModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.UI.AbpUiModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AspNetCore.Components.Web.AbpAspNetCoreComponentsWebModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.AspNetCore.Components.AbpAspNetCoreComponentsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.ObjectMapping.AbpObjectMappingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
        - MyProject.MyProjectHttpApiClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - MyProject.MyProjectApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - MyProject.MyProjectDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Identity.AbpIdentityDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Users.AbpUsersDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.IdentityServer.AbpIdentityServerDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.Account.AbpAccountApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Users.AbpUsersAbstractionModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.EventBus.AbpEventBusModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                    - Volo.Abp.Guids.AbpGuidsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                    - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                    - Volo.Abp.DistributedLocking.AbpDistributedLockingAbstractionsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.SettingManagement.AbpSettingManagementApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.TenantManagement.AbpTenantManagementApplicationContractsModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Account.AbpAccountHttpApiClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Identity.AbpIdentityHttpApiClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.PermissionManagement.AbpPermissionManagementHttpApiClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.TenantManagement.AbpTenantManagementHttpApiClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.FeatureManagement.AbpFeatureManagementHttpApiClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.SettingManagement.AbpSettingManagementHttpApiClientModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme.AbpAspNetCoreComponentsWebAssemblyBasicThemeModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.AspNetCore.Components.Web.BasicTheme.AbpAspNetCoreComponentsWebBasicThemeModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AspNetCore.Components.Web.Theming.AbpAspNetCoreComponentsWebThemingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.BlazoriseUI.AbpBlazoriseUIModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.UI.Navigation.AbpUiNavigationModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.AspNetCore.Components.WebAssembly.Theming.AbpAspNetCoreComponentsWebAssemblyThemingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Http.Client.IdentityModel.WebAssembly.AbpHttpClientIdentityModelWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.Http.Client.IdentityModel.AbpHttpClientIdentityModelModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.IdentityModel.AbpIdentityModelModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.Identity.Blazor.WebAssembly.AbpIdentityBlazorWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Identity.Blazor.AbpIdentityBlazorModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AutoMapper.AbpAutoMapperModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Auditing.AbpAuditingModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.PermissionManagement.Blazor.AbpPermissionManagementBlazorModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.PermissionManagement.Blazor.WebAssembly.AbpPermissionManagementBlazorWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.TenantManagement.Blazor.WebAssembly.AbpTenantManagementBlazorWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.TenantManagement.Blazor.AbpTenantManagementBlazorModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.FeatureManagement.Blazor.AbpFeatureManagementBlazorModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.FeatureManagement.Blazor.WebAssembly.AbpFeatureManagementBlazorWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.SettingManagement.Blazor.WebAssembly.AbpSettingManagementBlazorWebAssemblyModule
global.js?_v=637728566121956479:8 info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.SettingManagement.Blazor.AbpSettingManagementBlazorModule
global.js?_v=637728566121956479:8 info: Volo.Abp.Modularity.ModuleManager[0]
      Initialized all ABP modules.
global.js?_v=637728566121956479:8 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: WebAssemblyCachedApplicationConfigurationClient should be initialized before using it.

**Comment by realLiangshiwei** [comment]
@GillesFr06 

Can you share the `Program` class code?

**Comment by GillesFr06** [comment]
```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Syncfusion.Blazor;

namespace Courtisan.Blazor
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);

            var application = builder.AddApplication<CourtisanBlazorModule>(options =>
            {
                options.UseAutofac();
            });

            var host = builder.Build();

            await application.InitializeAsync(host.Services);

            await host.RunAsync();
        }
    }
}
```

**Comment by GillesFr06** [comment]
It's a new project created with the application generator on the web site abp.io on 23 dec 2021
I modify very few things.
I updated all Nuget packages
I can't run the project anymore

**Comment by realLiangshiwei** [comment]
Try replace `InitializeAsync` with `InitializeApplicationAsync`

**Comment by GillesFr06** [comment]
It goes a little further.


... all modules init ...

info: Volo.Abp.Modularity.ModuleManager[0]
      Initialized all ABP modules.

**Comment by GillesFr06** [comment]
Sorry for the so long paste, I didn't see before posting.

I've added Syncfusion nuget packages.
If I remove them, it works now.

If I use again "InitializeAsync" in program.cs, I have the same pb as before, even without Syncfusion.

So what difference between InitializeAsync and InitializeApplicationAsync ?

**Comment by realLiangshiwei** [comment]
Please refer to the template program class: https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Blazor.Server/Program.cs

**Comment by GillesFr06** [comment]
Ok, I will have a look.
It works now. So MANY THANKS to you.
I was looking about this error for 4 days ...
I'm very impressed with your response time.
