### ISSUE TITLE
Single layer startup template

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#11361]
I've created a simple startup template with single layer, located here: https://github.com/abpframework/abp/tree/rel-5.1/templates/app-nolayers

Here the solution screenshot:

![image](https://user-images.githubusercontent.com/1210527/149932333-6e9cef45-62fb-4f36-9d3d-d2af10c20ca8.png)

We are releasing this as an experimental work for now. It currently only supports MVC UI and EF Core with SQL Server (you can definitely change them after download).

Remaining work:

- [x] Develop the ABP CLI to support this new template with name `app-nolayers`.
- [x] Upgrade the template to work with local ABP packages (those will be replaced with nuget packages on the solution creation)
- [x] Remove `Startup.cs` and switch to the new minimal hosting style.
- [x] Add all available languages. Currently, there are two languages in MyProjectNameModule.ConfigureLocalization method. We can add all like the `app` startup template.

**Comment by liquehuo** [comment]
when i publish to docker Linux services then is can running ，but Localization>> zh-Hans.json is not loaded ?，”Menu:Home“ ，”Welcome_Text“， ”Welcome_Title“  value not exists! local docker not have this problem

**Comment by maliming** [comment]
> when i publish to docker Linux services then is can running ，but Localization>> zh-Hans.json is not loaded ?，”Menu:Home“ ，”Welcome_Text“， ”Welcome_Title“ value not exists! local docker not have this problem

https://github.com/abpframework/abp/pull/12401
