### ISSUE TITLE
Rows per page option dropdown using Abp Suite (ngx-datatable)

### ISSUE THREAD

**Issue by Foram0312** [abpframework/abp#11369]
How can I add Rows Per Page Option dropdown in Footer using ngx-datatable from Abp Suite. When I generate crud page using Abp suite, this option do not get generated from the template. I do not want to add a custom footer inside the template. Is there any other property which is missing to add in the template?
![image](https://user-images.githubusercontent.com/87792287/150058150-b5b802ac-d22f-495e-a254-b66f55c7c9f9.png)

**Abp Version : 5.0.1
UI: Angular
Provider: EfCore**
**abp**

Can someone help me out please?

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io/
