### ISSUE TITLE
Abp Suite is Breaking the DbContext on Entity Generation

### ISSUE THREAD

**Issue by kfrancis** [abpframework/abp#11379]
* Your **ABP Framework version**: v5.1.1
* Your **ABP Suite version**: v5.1.1
* Your **ABP CLI version**: v5.1.2
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: MVC Layered
* Your database provider(EF Core/MongoDB), EFCore

## Repro Steps
- Create new app `abp new MyProject`
- Change connection strings to use `(localdb)\\mssqllocaldb` adding `TrustServerCertificate=True` to the end in both .Web and .DbMigrator projects
- Build and migrate to ensure it's running (sanity checking)
- Run the suite with `abp suite`
- Select the solution created
- Create a simple entity with at least one property and Save

Expected: The suite should create the entity and it should complete normally.
Actual: The generating process fails and does this to the DbContext class

![22-01-slkth-1642604559](https://user-images.githubusercontent.com/67574/150158157-9d758938-19b0-4891-9270-d64373bc869b.png)

When it should look like this:
![22-01-hqt9b-1642604576](https://user-images.githubusercontent.com/67574/150158189-85b134b7-f157-496d-a451-62bf713e31ae.png)

It's inserting the DbSet inside the get/set of the first property which then causes a build failure.

## Workaround
- Go fix DbContext
- Go back to suite and save again, no problem completing this time.

**Comment by Francois-La** [comment]
I confirm the same behavior using the same version.  The bug is clearly repeatable.

**Comment by maliming** [comment]
See https://support.abp.io/QA/Questions/2428/ABP-Suite-511-Generating-Entity---DbSet-position-in-DbContextcs-error

**Comment by yekalkan** [comment]
Suite v5.1.2 have solved the issue.
