### ISSUE TITLE
eShopOnAbp: Gateway multiple api definition authorization

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#11389]
Gateway using multiple api definitions based on ocelot configuration:
![gw1](https://user-images.githubusercontent.com/25867/150318022-494db3ad-2f3a-43f8-a7d1-4e0c5f074c77.png)

However, Authorize **client_id** and **client_secret** can not be set.
![image](https://user-images.githubusercontent.com/25867/150317953-3eee36ee-13b2-43bb-88e4-90be166f0245.png)

Need to find a way to configure auto prompting client_id and client_secret for multiple api definitions.

**Comment by hikalkan** [comment]
We can define clients only for gateways. We can use these gateway clients for individual microservices too.
