### ISSUE TITLE
Exception not auto handle in blazor-server project

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#11396]
* Your **ABP Framework version** : 5.1.2.
* Your **User Interface** type (Angular/MVC/React... etc.) : blazor-server
* Your database provider(EF Core/MongoDB): EF Core
* Steps needed to **reproduce** the problem:
1. `abp new Acme.BookStore -u blazor-server -csf`
2. run `migrator` project
3. add throw `UserFriendlyException` code from https://docs.abp.io/en/abp/latest/UI/Blazor/Error-Handling#userfriendlyexception
4. run blazor project, and click `Throw test exception` button
5. it will show blazor yellow banner on the bottom of page, it does not show a exception modal as the document,

![image](https://user-images.githubusercontent.com/1829209/150460251-f6643f73-0a18-4c36-9823-62359973ae7d.png)

remark: I am not test other project type

**Comment by EngincanV** [comment]
Hi @rqx110, can you change your method as below:

```cs
private async Task TestException()
{
    try {
       throw new UserFriendlyException(message: "A user friendly error message!");
    }
    catch(UserFriendlyException ex) {
       await HandleErrorAsync(ex); 
    }
}
```

> We'd implemented a custom logger to show errors for Blazor WASM. For server side, global exception handling is not possible yet (see dotnet/aspnetcore#30940). 
https://github.com/abpframework/abp/issues/8195

**Comment by rqx110** [comment]
OK!
