### ISSUE TITLE
[Question] Guidelines for concurrency check usage ?

### ISSUE THREAD

**Issue by sanghel-payoff** [abpframework/abp#11393]
ABP Commercial 5.0, Angular, EFCore with PGSQL

The official documentation is in a TODO state... https://docs.abp.io/en/abp/5.1/Concurrency-Check

Npgsql offers a "native" extensions for using a shadow property **xmin** as the concurrency token for EFCore ( see [here](https://www.npgsql.org/efcore/modeling/concurrency.html) )

Q1: Is the infrastructure around the _IHasConcurrencyStamp_ interface aware of this Npgsql special case, or the "recommended" way for Abp is to use this interface only?

Q2: If using _IHasConcurrencyStamp_ is the recommended way, is [this](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/AggregateRoot.cs#L22) the correct way to value it? Any suggestion for when / how to set it for an _Entity_ (**not** an _AggregateRoot_ )?

**Comment by maliming** [comment]
ABP doesn't use Npgsql's special case, it uses EF Core's general rules. You can refer to this PR to learn how to use it.

https://github.com/abpframework/abp/pull/9838
https://github.com/abpframework/abp/pull/9838/commits/603f094b1e90d65cf999a1f9ecd5ba06636a555f

**Comment by sanghel-payoff** [comment]
@hikalkan The [official documentation](https://docs.abp.io/en/abp/5.1/Concurrency-Check) should at least illustrate some usage patterns...

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/12026
