### ISSUE TITLE
[Question] Full ABP CLI parameters ?

### ISSUE THREAD

**Issue by sanghel-payoff** [abpframework/abp#11409]
I am updating from 5.0.1 to 5.1.2.

I am following the [startup template update guide](https://docs.abp.io/en/abp/latest/Migration-Guides/Upgrading-Startup-Template), and I need to recreate my original solution via the ABP CLI with adequate arguments.

The [official ABP CLI documentation](https://docs.abp.io/en/abp/latest/CLI) does not document all available parameters, and neither does running `abp new --help`.

I've "discovered" the undocumented `--with-public-website` flag on [this issue](https://github.com/abpframework/abp/issues/8772), but using that flag also adds the CMSKit module, which I do not require.

The ABP Suite web UI allows creating a solution with a Public website, but without the CMSKit module.
![image](https://user-images.githubusercontent.com/77339756/150589501-d85d92c7-9f7e-441a-84c8-2c5b263b763c.png)

How do I specify the same arguments to the ABP CLI ?

Could you document all arguments / flags / switches of the ABP CLI in the official docs?

**Comment by maliming** [comment]
You can check and search the source code for more info.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/ProjectCreationCommandBase.cs#L381

**Comment by sanghel-payoff** [comment]
there is no option that generates the solution with a public website, but without the CMSKit module !

so ABP CLI does not 100% overlap ABP Suite functionality...

**Comment by sanghel-payoff** [comment]
@maliming my question still stands...

How do I create a new solution with ABP CLI that has the public website but without the CMS-Kit module?


This is required in order to correctly follow the official guide for upgrading the startup template.

The ABP Suite web UI does not allow creating a new solution with a specific version, as the ABP CLI does.

**Comment by sanghel-payoff** [comment]
@maliming sources of ABP Suite are not public as far I can tell, so I cannot "search the code" for what it does for the two checkboxes...

@demirmusa  ...there should be documentation though, "search the code" is not exactly supporting a paid product..

**Comment by yekalkan** [comment]
> ABP CLI does not 100% overlap ABP Suite functionality

It does, excluding code-generation. However, some of the suite functionalities are related with commercial templates/modules. So we didn't document some options in CLI documentation, even though they exist & work. Because CLI is free & open-source.

Free template doesn't have a Public web site project and doesn't include CmsKit module at all. So it would be confusing to show these options in a non-commercial document. But they are still valid : `without-cms-kit` & `with-public-website`

> How do I create a new solution with ABP CLI that has the public website but without the CMS-Kit module?

`abp new Acme.BookStore --without-cms-kit --with-public-website`

**Comment by sanghel-payoff** [comment]
@yekalkan thank you for the info

I understand the documentation distinction, but still, a company should prioritize documentation **for the paid product** !

is there a separate documentation for ABP Commercial, that does document all relevant parameters?
