### ISSUE TITLE
5.1.2 macOS build has 147 errors but windows successful

### ISSUE THREAD

**Issue by ysozbek** [abpframework/abp#11407]
**ABP Framework version** 5.1.2.
 **User Interface** Angular
* database provider(EF Core)
* MACOS version : MACOS Monterey version 12.1 (21C52) (Intel)
* IDE : Rider , Visual Studio For Mac

I have problem abp  commercial 5.1.2:

When I create agular project with abp suite in windows it restores and builds project successfully, but when I create project with abi suite on macOS or I restore and build created project (with windows) in macOS with 5.1.2 abi cli  there is 147 errors in 13 files. some errors are like these:

Cannot resolve symbol 'AbpIdentityProDomainSharedModule'
Cannot resolve symbol 'LanguageManagementDomainSharedModule'
Cannot resolve symbol 'SaasDomainSharedModule',
Cannot resolve symbol 'LanguageManagement'
Cannot resolve symbol 'AbpIdentityApplicationContractsModule'
Cannot resolve symbol 'TextTemplateManagementApplicationContractsModule'

For example When I take Volo.Abp.Identity.Pro.Domain.Shared 5.1.2 to 5.1.1 Cannot resolve symbol 'AbpIdentityProDomainSharedModule' error gone. and the others.

Sample image:

<img width="1729" alt="Screen Shot 2022-01-21 at 17 51 28" src="https://user-images.githubusercontent.com/50448937/150547805-8992734a-d58e-474f-94c9-a0bf3bec6f4b.png">

**Comment by berkansasmaz** [comment]
Yes, I am having the same problem. We will solve the problem

Thanks for the report.

**Comment by berkansasmaz** [comment]
The problem has been solved with `5.1.3`. You can update the ABP CLI and try 😊

`dotnet tool update -g Volo.Abp.Cli`

**Comment by ysozbek** [comment]
windows abp cli update to 5.1.3. But on macos when i run update volo.abp.cli command it says "Tool 'volo.abp.cli' was reinstalled with the latest stable version (version '5.1.2')'."

**Comment by enisn** [comment]
The version [v5.1.3](https://www.nuget.org/packages/Volo.Abp.Cli/5.1.3) is already published. You can try removing it completely and reinstalling again.

`dotnet tool uninstall -g Volo.Abp.Cli`
`dotnet tool install -g Volo.Abp.Cli`

or you can just specify the version:
`dotnet tool update -g Volo.Abp.Cli --version 5.1.3`

**Comment by ysozbek** [comment]
ysozbek@*** ~ % dotnet tool install -g Volo.Abp.Cli  
You can invoke the tool using the following command: abp
Tool 'volo.abp.cli' (version '5.1.2') was successfully installed.
ysozbek@*** ~ % dotnet tool update -g Volo.Abp.Cli --version 5.1.3
/var/folders/2_/53j0y8kj55q571_cgl6bzn6r0000gn/T/xbe1ezo0.21g/restore.csproj : error NU1102: Unable to find package volo.abp.cli with version (>= 5.1.3)
/var/folders/2_/53j0y8kj55q571_cgl6bzn6r0000gn/T/xbe1ezo0.21g/restore.csproj : error NU1102:   - Found 94 version(s) in nuget.org [ Nearest version: 5.1.2 ]
Tool 'volo.abp.cli' failed to update due to the following:
The tool package could not be restored.
Tool 'volo.abp.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by enisn** [comment]
It's available on nuget.org currently
https://www.nuget.org/packages/Volo.Abp.Cli/5.1.3

You can try to clear nuget cache

**Comment by ysozbek** [comment]
Thanks after nuget locals all -clear command 'volo.abp.cli' was successfully updated from version '5.1.2' to version '5.1.3'.
