### ISSUE TITLE
[Volo.Abp.BlobStoring.FileSystem] Get File Path

### ISSUE THREAD

**Issue by magicjar** [abpframework/abp#11414]
I'm building an image upload system for my site using Blob FileSystem. I store the image file in `hostingEnvironment.WebRootPath;`.

How can I get the image path so I can store the path into DB right after upload.

I know there is method to calculate path inside `DefaultBlobFilePathCalculator` class, but I dont know how to used it.

**Comment by rqx110** [comment]
you do not need store the full path, just store your file name to your DB, and when you want to get the file, the blob storage system will handle to get the file by the name. 
```cs
await _blobContainer.SaveAsync('your_file_name', ....)
await _blobContainer.GetAsync('your_file_name')
```

**Comment by magicjar** [comment]
Well, I'm using another library (ImageSharp.Web) to generate image cache, so I need the full path.

**Comment by journey191** [comment]
In my project,I really need to get the real path.
Here my solution:
```
//Dependency Inject
private readonly DefaultBlobContainerConfigurationProvider _blobContainerConfigurationProvider;
private readonly DefaultBlobFilePathCalculator _blobFilePathCalculator;

var containerName = BlobContainerNameAttribute.GetContainerName<DefaultContainer>();
var blobContainerConfiguration = _blobContainerConfigurationProvider.Get(containerName);
var realPath = _blobFilePathCalculator.Calculate(new BlobProviderGetArgs(containerName,blobContainerConfiguration, "YourBlobName"));
```
