### ISSUE TITLE
`IUserData` - Supporting new `IsActive` property

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#11416]
Hey folks,

I've been messing around with the lastest release. 
I very like the `IsActive` property but modules cannot make use of the `IsActive` property yet since `IUserData` doesn't provide this value (yet).

Is this by design, so you can tell a alternative way of getting this information in modules or can it be added from your perspective?

I'm open for implementing and contributing this change if desired.

* Your **ABP Framework version**: 5.1.2
* ~Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI~
* ~Your database provider(EF Core/MongoDB)~
* ~Exception message and **stack trace** if available (check the logs).~
* ~Steps needed to **reproduce** the problem.~

**Comment by maliming** [comment]
@hikalkan What do you think?

**Comment by enisn** [comment]
This is related to https://github.com/abpframework/abp/pull/11417
