### ISSUE TITLE
Documentation search shows only first page

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#11436]
* Documentation 5.1

The documentation search shows only the first page.

Example: https://docs.abp.io/search/en/abp/5.1/?keyword=manager

[Domain Service](https://docs.abp.io/en/abp/latest/Domain-Services) contain 15x"manager" but its not in the search result

can be found by [site google serach](https://www.google.com/search?q=site%3Adocs.abp.io+manager) ( on page 3 )

**Comment by salihozkara** [comment]
This situation has been corrected.
