### ISSUE TITLE
Guid Generator is not sequential generating multiple call in one request

### ISSUE THREAD

**Issue by ahmetfarukulu** [abpframework/abp#11453]
*  ABP Framework version 5.0.0.
*  User Interface Blazor
*  Database provider EF Core (MsSQL)

I use [BookStore](https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore) sample and change the only [BookStoreDataSeederContributor](https://github.com/abpframework/abp/files/7934976/BookStoreDataSeederContributor.txt)

Problem 
- We insert to database one by one with autosave:true its generate sequential id 🟢 
- We insert to database one by one with autosave:false its not generate sequential id 🔴 
- Create list use InsertManyAsync method its not generate sequential id 🔴 

![image](https://user-images.githubusercontent.com/35758317/150995832-0f7ec372-8a06-41db-8016-71488645736d.png)
1-5 use InsertOneByOneWithAutoSaveTrueAsync,10-50 use InsertOneByOneWithAutoSaveFalseAsync, 100-500 use InsertByManyAsync
Result;
![image](https://user-images.githubusercontent.com/35758317/150996237-27d121c9-5f99-481e-8423-aca081badbb2.png)

**Comment by Wiblox** [comment]
I'm not sure, but I think that the Guid is generated in a sequential way but it's only the insertion that is done randomly. (maybe because it's asyncrone)

**Comment by ahmetfarukulu** [comment]
No it can't, Id field has clustered index so data will be sorted on sql side even asynchronously insert. The problem is because [guid generator](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Guids/Volo/Abp/Guids/SequentialGuidGenerator.cs) use [timestamp](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=net-6.0) for sequential id. Multiple generate in single request getting same millisecond and after that part generates the rest randomly.

**Comment by ahmetfarukulu** [comment]
I've found a solution but only works on windows  [stackoverflow reference](https://stackoverflow.com/questions/211498/is-there-a-net-equivalent-to-sql-servers-newsequentialid)
```csharp
    [Dependency(ReplaceServices = true)]
    public class MsSqlSequentialGuidGenerator : IGuidGenerator, ITransientDependency 
    {
        public AbpSequentialGuidGeneratorOptions Options { get; }

        public IAbpLazyServiceProvider LazyServiceProvider { get; set; }

        protected SequentialGuidGenerator SequentialGuidGenerator => LazyServiceProvider.LazyGetRequiredService<SequentialGuidGenerator>();

        public MsSqlSequentialGuidGenerator(IOptions<AbpSequentialGuidGeneratorOptions> options)
        {
            Options = options.Value;
        }

        public virtual Guid Create()
        {
            return Create(Options.GetDefaultSequentialGuidType());
        }

        public virtual Guid Create(SequentialGuidType guidType)
        {
            switch (guidType)
            {
                case SequentialGuidType.SequentialAsString:
                case SequentialGuidType.SequentialAsBinary:
                default:
                    return SequentialGuidGenerator.Create(guidType);
                case SequentialGuidType.SequentialAtEnd:
                    UuidCreateSequential(out Guid guid);
                    return ReOrderBytes(guid);
            }
        }

        [DllImport("rpcrt4.dll", SetLastError = true)]
        static extern int UuidCreateSequential(out Guid guid);

        public static Guid ReOrderBytes(Guid guid)
        {
            var s = guid.ToByteArray();
            var t = new byte[16];

            t[3] = s[0];
            t[2] = s[1];
            t[1] = s[2];
            t[0] = s[3];

            t[5] = s[4];
            t[4] = s[5];
            t[7] = s[6];
            t[6] = s[7];
            t[8] = s[8];
            t[9] = s[9];
            t[10] = s[10];
            t[11] = s[11];
            t[12] = s[12];
            t[13] = s[13];
            t[14] = s[14];
            t[15] = s[15];

            return new Guid(t);
        }
    }
```

**Comment by lisheng741** [comment]
I also encountered this problem.  Abp's algorithm fininshes in milliseconds and the timestamp generated in the case of high concurrency may be the same, resulting in the Guid generated at the same time not being sequential.

```csharp
// path: abp\framework\src\Volo.Abp.Guids\Volo\Abp\Guids\SequentialGuidGenerator.cs

// Using millisecond resolution for our 48-bit timestamp gives us
// about 5900 years before the timestamp overflows and cycles.
// Hopefully this should be sufficient for most purposes. :)
long timestamp = DateTime.UtcNow.Ticks / 10000L;
```

see [DateTime.Ticks Property Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=net-6.0#remarks)
> A single tick represents one hundred nanoseconds or one ten-millionth of a second. There are 10,000 ticks in a millisecond (see [TicksPerMillisecond](https://docs.microsoft.com/en-us/dotnet/api/system.timespan.tickspermillisecond?view=net-6.0)) and 10 million ticks in a second.
