### ISSUE TITLE
Blaozr UI: User menu dropdown is partially invisible

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#11459]
abp: 5.1.2
ui: blazor-server 
the user menu dorpdown out of screen:
![image](https://user-images.githubusercontent.com/1829209/151096822-17c91f0d-61bb-405a-9798-3f79e8008d62.png)
we can fix this issue by add `RightAligned="true"` to https://github.com/abpframework/abp/blob/c7e0fca8de9f87779216476299c7ddd9de1e6eb5/modules/basic-theme/src/Volo.Abp.AspNetCore.Components.Server.BasicTheme/Themes/Basic/LoginDisplay.razor#L24

also fix in wasm
https://github.com/abpframework/abp/blob/c7e0fca8de9f87779216476299c7ddd9de1e6eb5/modules/basic-theme/src/Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme/Themes/Basic/LoginDisplay.razor#L24

**Comment by realLiangshiwei** [comment]
Thanks @rqx110
