### ISSUE TITLE
how to use mongodb in application test

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#1145]
```
public abstract class GroupApplicationTestBase : GroupTestBase<GroupApplicationTestModule>
    {
        protected virtual void UsingDbContext(Action<ICoreGroupMongoDbContext> action)
        {
            using (var dbContext = GetRequiredService<ICoreGroupMongoDbContext>().Collection<Group>)
            {
                action.Invoke(dbContext);
            }
            
        }

        protected virtual T UsingDbContext<T>(Func<ICoreGroupMongoDbContext, T> action)
        {
            using (var dbContext = GetRequiredService<ICoreGroupMongoDbContext>())
            {
                return action.Invoke(dbContext);
            }
        }
    }
```

**Comment by maliming** [comment]
try Depends on `XXXMongoDbTestModule` in `XXXApplicationTestModule`

However, unit testing of application services has nothing to do with EF and MongoDb.
It is more convenient to use EF.

**Comment by nguyendev** [comment]
I tried, but  I received a error: 
'ICoreGroupMongoDbContext': type used in a using statement must be implicitly convertible to 'System.IDisposable'

**Comment by maliming** [comment]
Try remove `using (var dbContext ....`.

**Comment by nguyendev** [comment]
`protected virtual void UsingDbContext(Action<ICoreGroupMongoDbContext> action)
        {
           
            
        }

        protected virtual T UsingDbContext<T>(Func<ICoreGroupMongoDbContext, T> action)
        {
            
        }`
I received a new error:
CS0161	'GroupApplicationTestBase.UsingDbContext<T>(Func<ICoreGroupMongoDbContext, T>)': not all code paths return a value

**Comment by maliming** [comment]
```
public abstract class GroupApplicationTestBase : GroupTestBase<GroupApplicationTestModule>
{
	protected virtual void UsingDbContext(Action<ICoreGroupMongoDbContext> action)
	{
		var dbContext = GetRequiredService<ICoreGroupMongoDbContext>();
		action.Invoke(dbContext);
	}

	protected virtual T UsingDbContext<T>(Func<ICoreGroupMongoDbContext, T> action)
	{
		var dbContext = GetRequiredService<ICoreGroupMongoDbContext>();
		return action.Invoke(dbContext);
	}
}
```

**Comment by nguyendev** [comment]
I tried and succeeded. Thank you so much

**Comment by nguyendev** [comment]
It is null. I think, we need a best solution
![image](https://user-images.githubusercontent.com/10234503/58258626-43a90a80-7d9d-11e9-872a-a6381c730271.png)

**Comment by maliming** [comment]
I will try.
