### ISSUE TITLE
Lazy-loading abp suite

### ISSUE THREAD

**Issue by Wiblox** [abpframework/abp#11456]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

ABP 5.1.2
Blazor
EF Core

"No backing field was found for property 'Plan.GatewayPlans'. Lazy-loaded navigations must have backing fields. Either name the backing field so that it is discovered by convention or configure the backing field to use."

Create a blank project with abp suite, set it to use lazy-loading in entityframeworkcore.

        Configure<AbpDbContextOptions>(options =>
        {
            options.PreConfigure<ManulocDbContext>(opts =>
            {
                opts.DbContextOptions.UseLazyLoadingProxies(); //Enable lazy loading
            });

            options.UseSqlServer();
        });
        
        And after another migration we get the above error.
        
        Yet no problem with non-commercial abp

**Comment by realLiangshiwei** [comment]
Hi,

We don't recommend you use lazy loading: https://docs.microsoft.com/en-us/ef/core/performance/efficient-querying#beware-of-lazy-loading

See: https://github.com/abpframework/abp/issues/2935

**Comment by Wiblox** [comment]
Thanks.
