### ISSUE TITLE
Audit Log: Consider removal of 256 char Comments field limit

### ISSUE THREAD

**Issue by gdunit** [abpframework/abp#11455]
Hi, using the Audit Module as base, I'm trying to store a human-readable representation of each audit log which is stored at the time of the event, so that this can be easily displayed in an an audit trail UI later on.

I figured it was best to store at the time of the transaction because then all the entity properties would be stored "as was" at the time of the change, we do not need to worry about entities that were since deleted, and also I would be concerned that dynamically looking up human-readable properties from many separate tables at the time of the audit trail being requested by the user would be too expensive.

To do this I created a custom Audit Log Contributor which uses a custom AuditTrailResolver class per entity class to store the relevant data via its PostContribute() method.

The Comments field in the audit log contributor seemed like a natural place to store this info, but I noticed it was truncating data over 256 chars.

I created a custom AuditLoggingDbContextModelExtensions class and called this from the EF core project, removing the limit on the DB column length:

`                // Max value
                b.Property(x => x.Comments).HasColumnName(nameof(AuditLog.Comments));
`

However the content is still truncated, reading through the code I realised that the line below was the culprit:
https://github.com/abpframework/abp/blob/46de78b1b8bd1d7dff06e808179d08c0c3c958ca/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain/Volo/Abp/AuditLogging/AuditLog.cs#L117

Would you consider removing this truncation, or making the limit configurable?
Alternatively is there a better or more supported way to achieve this?

**Comment by realLiangshiwei** [comment]
Hi,

https://github.com/abpframework/abp/blob/46de78b1b8/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain.Shared/Volo/Abp/AuditLogging/AuditLogConsts.cs#L38

The `AuditLogConsts.MaxCommentsLength` is static, you can change it.

**Comment by gdunit** [comment]
Thank you @realLiangshiwei . I can confirm that setting this variable in the domain module's ConfigureServices() method resolves the issue.
