### ISSUE TITLE
No-Layers project template: Support different UI and DB options

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#11454]
Currently it only supports MVC / Razor Pages UI with EF Core. We should work on the template to support the others, and develop the  ABP CLI based on these changes.

Please think how it can be more practical to develop and generate the template. Use the same parameter names/values with the app template wherever possible.

### UI options

- [x] MVC / Razor Pages
- [x] Blazor Server
- [ ] Blazor WASM
- [x] Angular
- [x] None (No UI, for HTTP API development)

### DB options

- [x] EF Core
- [x] MongoDB

### Other options

- [x] `--preview`
- [x] `--output-folder`
- [x] `--create-solution-folder`
- [x] `--connection-string`
- [x] `-dbms`

**Comment by yinchang0626** [comment]
Please consider the commercial version,I love it,
thanks

**Comment by maliming** [comment]
@yinchang0626 It's on the plan.

**Comment by maliming** [comment]
If we support the `Blazor WASM`, three projects are needed.

1. Api Host
2. Blazor WASM
3. Shared Project(**Localization**).

**Comment by hikalkan** [comment]
For blazor wasm, yes, we need to three projects (only for blazor wasm)

**Comment by mehmetuken** [comment]
> If we support the `Blazor WASM`, three projects are needed.
> 
> 1. Api Host
> 2. Blazor WASM
> 3. Shared Project(**Localization**).

All in one host option can be consider?
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#hosted-deployment-with-aspnet-core

**Comment by maliming** [comment]
Supporting blazor wasm would be a tiered project structure. This would be similar to the default app. I think we can exclude the balzor wasm type.
