### ISSUE TITLE
Can not start new downloaded template from abp site

### ISSUE THREAD

**Issue by amira133** [abpframework/abp#11472]
* Your **User Interface** type = Angular , MVC
* Your database provider = EF Core/MongoDB
* Steps needed to **reproduce** the problem:
* 1- create new project from [abp](https://abp.io/get-started)
*  2- run aspnet-core project to see problems.

![image](https://user-images.githubusercontent.com/27830573/151125153-167ef801-ac4a-4ddc-b335-53b96440a116.png)

I have installed .net6 SDK and .netstandard2.

**Comment by rqx110** [comment]
vs2022 is required!

**Comment by maliming** [comment]
> .NET 6 is supported with Visual Studio 2022 and Visual Studio 2022 for Mac. It is not supported with Visual Studio 2019, Visual Studio for Mac 8, or MSBuild 16. If you want to use .NET 6, you will need to upgrade to Visual Studio 2022 (which is also now 64-bit). .NET 6 is supported with the Visual Studio Code C# extension.
