### ISSUE TITLE
Bug in the feature selection section in abp.io website

### ISSUE THREAD

**Issue by antosubash** [abpframework/abp#11474]
When i Click on the side menu the navigation happens but the selection is wrong.

<img width="1920" alt="abpbug" src="https://user-images.githubusercontent.com/1304254/151152073-3bf3b872-103e-42d9-9556-7d0d01f6d346.png">

**Comment by berkansasmaz** [comment]
Thanks for the report @antosubash  🎉

We fixed this issue, it will be deployed soon.

---

That's why I'm closing the issue. Feel free to re-open or create a new issue if you have further questions.
