### ISSUE TITLE
Problem extending AbpUser

### ISSUE THREAD

**Issue by garsiv1932** [abpframework/abp#11483]
* Your **ABP Framework version: 5.1.3, 4.4.
* Your **User Interface: Angular
* Your database provider: EF Core

I want to extend the abp user entity, i followed all the tutorials, and i cant to extend the entity, how does it works?????

Does someone knows? I dont find the information anywhere and the official info looks like its imposible to make it works. I want to make a one to many bidirectional relationtip from identity to my domain entities and is impossible. Please, can someone from ABP share a clear documentation that works!!!!!!!!!!!!!!!!!

Thanks.

**Comment by realLiangshiwei** [comment]
Hi,

* Steps needed to **reproduce** the problem.

**Comment by garsiv1932** [comment]
I am trying to focus on the error, but i am exausted. I am Linux user. I started a projects with the command

abp new LandRest -t app -u angular -m react-native -d ef -o LandRest -v 4.2.0 --separate-identity-server

I tried the versions 4.1.0, 4.2.0, 4.3.0, 4.4.4 and the latest version 5.1.3. From the version 4.3.0 to 4.4.0 you changed the way the Abp User is extended. In template 4.3.0 you have an AppUser on the Domain project, and in the version 4.4 adn newer dont.
In the version 4.3 and older i needed to install Microsoft.EntityFrameworkCore.Design so the migrations can detect my framework, but when i run the migration it says: 

Unable to create an object of type 'LandRestDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

In the 4.4.0 and newer didn't have the problem with the nugget, but i followed the documentation in the link

https://docs.abp.io/en/abp/4.4/Object-Extensions

But the documentation is horrible, it asumes that the reader know where need the code to be introduced and i never used ABP before (and really, i am making this effort only because ABP is used on my work, because it can be a very good tool, but is so hard to start if you come from a plain .net projects).

I created the entity public class AppUser:FullAuditedAggregateRoot<Guid>, IUser and i made the 
and i put this configuration in the OnModelCreating method on the context but didnt work too

            builder.Entity<AppUser>(entity =>
            {
                entity.ToTable(AbpIdentityDbProperties.DbTablePrefix + "Users");
                entity.ConfigureByConvention();
                entity.ConfigureAbpUser();
            });

I tried, i researched the problem, and, like you see, i found like three ways to make the same but anyone works.
So PLEASE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!, can you share a documentation that dont asume anything and fix this problem? 

PLEASE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by realLiangshiwei** [comment]
This is not an ABP problem, you should check the documents and samples.

Can you check this? 

https://github.com/abpframework/abp-samples/tree/master/DocumentationSamples/CustomApplicationModules

https://github.com/abpframework/abp/issues/1414

For version 5.x: 

See: https://support.abp.io/QA/Questions/2151/Add-relation-between-AbpUser-to-My-Table-in-50

**Comment by garsiv1932** [comment]
https://docs.abp.io/en/abp/latest/Module-Entity-Extensions

I am following this manual right now.

Why you have two or three documents abouth the same shit and anyone make the job done, explain me, why?

**Comment by garsiv1932** [comment]
![image](https://user-images.githubusercontent.com/65036539/151285154-1d1262fc-89ca-43df-833d-3d4516c9c96c.png)

i copy pasted this code on the extension configurator

 OneTimeRunner.Run(() =>
        {
            ObjectExtensionManager.Instance.Modules()
                .ConfigureIdentity(identity =>
                {
                    identity.ConfigureUser(user =>
                    {
                        user.AddOrUpdateProperty<string>( //property type: string
                            "SocialSecurityNumber", //property name
                            property =>
                            {
                                //validation rules
                                property.Attributes.Add(new RequiredAttribute());
                                property.Attributes.Add(
                                    new StringLengthAttribute(64) {
                                        MinimumLength = 4
                                    }
                                );

                                //...other configurations for this property
                            }
                        );
                    });
                });
        });
        
i created the migration and applied it, so.....explain me, where is the fucking security number¿?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by garsiv1932** [comment]
@realLiangshiwei 

I followed those stupid tutorials and i get this error

![image](https://user-images.githubusercontent.com/65036539/151290963-7fecd2dc-37a0-463a-a1f3-ea4422b1b448.png)


Nothing works in this sheet.....piece of crap.
