### ISSUE TITLE
abp.RabbitMq how to connect to existing exchange (type : topic)

### ISSUE THREAD

**Issue by suravi999** [abpframework/abp#11487]
1) abp.RabbitMq how to connect to already existing exchange (type: topic)?

2) is there any way to connect without a `dead-letter` exchange?

**Comment by realLiangshiwei** [comment]
Hi,

> 1

  See: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/IRabbitMqMessageConsumerFactory.cs#L14
  
  You can pass the `ExchangeDeclareConfiguration` parameter
  ![image](https://user-images.githubusercontent.com/16813853/151300216-8bd617b1-31da-4b8d-815b-1b5a63a1c799.png)

> 2

I didn't get it.

**Comment by suravi999** [comment]
HI @realLiangshiwei, 
1) here I can see exchange type hardcoded in the framework: https://github.com/abpframework/abp/blob/9cbb244efe520997cda82ea0cdf97a5700889dcf/framework/src/Volo.Abp.EventBus.RabbitMQ/Volo/Abp/EventBus/RabbitMq/RabbitMqDistributedEventBus.cs#L72

2) when I add the existing exchange name in the project configuration (appsettings.json)
it gives the following error message
![image](https://user-images.githubusercontent.com/10302737/151300752-19b80e3e-19d4-4abd-bd8f-489580bc941a.png)

**Comment by realLiangshiwei** [comment]
Hi,

This is the design, you can replace the `RabbitMqDistributedEventBus` with your implementation if you want to change it.

> 2

We canceled the dead-letter feature in 5.0, you can upgrade to 5.x

**Comment by suravi999** [comment]
Hi @realLiangshiwei,
implemented and replaced the `RabbitMqDistributedEventBus` as follows,
![image](https://user-images.githubusercontent.com/10302737/151370645-8596b8fe-914e-473a-b56f-34631a8067b7.png)

but still not executing `Initialize` function of new `AbcRabbitMqDistributedEventBus`

please let me know if I have missed anything?

**Comment by realLiangshiwei** [comment]
Hi,

Try

```csharp
....
[ExpostService(......, typeof(RabbitMqDistributedEventBus))]
```

**Comment by wr404274848** [comment]
> 

can you share your AbcRabbitMqDistributedEventBus.cs file,very appreciated
