### ISSUE TITLE
Blazor Components in Razor Pages

### ISSUE THREAD

**Issue by magicjar** [abpframework/abp#11489]
Are there any tutorials to implement blazor/razor component in ABP razor pages? I have followed "counter" component tutorial from MS, register `AddServerSideBlazor();`, `MapBlazorHub()`, add `_framework/blazor.server.js`, but no luck. The counter was rendered but the increment button just did not work, no error.

**Comment by realLiangshiwei** [comment]
Hi,

You can use the blazor-server template directly

**Comment by magicjar** [comment]
Are there any performance impact of switching from MVC/Razor to Blazor server on the server? Well I read a lot of posts that SPA (React, Angular) SSR put a lot of work on server CPU, this question is what keep me away from moving to blazor server.

**Comment by realLiangshiwei** [comment]
Hi,

Blazor is optimized for high performance, but it depends on your correct use of it,  you can read the Blazor High Performance Best Practices document
See: https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-6.0

**Comment by magicjar** [comment]
Ok, I had tried blazor server template and I got razor component working in razor pages.
But when I change the razor pages route from `@page "/page"` to nested route `@page "/page/post"`, it give me an error `Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 2` and increment function is not working.

Am I missing something?

/Pages/Pages.cshtml
``` razor
@page "/page/post"
@using Demo.Blazor.Components
@model Demo.Blazor.Pages.PagesModel
@using Microsoft.AspNetCore.Mvc.Localization
@using Demo.Localization
@inject IHtmlLocalizer<DemoResource> L
@section scripts {
<abp-script src="/_framework/blazor.server.js" />
}

@{
}

<div class="jumbotron text-center">
    <h1>Welcome</h1>
</div>

<component type="typeof(Counter)" render-mode="ServerPrerendered" />
```

/Pages/Pages.cshtml.cs
``` c#
using Volo.Abp.AspNetCore.Mvc.UI.RazorPages;

namespace Demo.Blazor.Pages
{
    public class PagesModel : AbpPageModel
    {
        public void OnGet()
        {
        }
    }
}
```

/Components/Counter.razor
``` razor
<PageTitle>Counter</PageTitle>

<h1>Counter</h1>
<p role="status">Current count: @currentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;
    private void IncrementCount()
    {
        currentCount++;
    }
}
```

**Comment by magicjar** [comment]
@realLiangshiwei  Ok, I got it to work now.

Just override theme layout "Application.cshtml" and add `<base href="~/" />` inside head tag.
I think the missing base caused this issue.
