### ISSUE TITLE
Extend Entities with Mongo

### ISSUE THREAD

**Issue by BZhong303** [abpframework/abp#11493]
Hi,

I am trying to expend the entity(like IdentityUser), when I follow the document.
I have some problem, can u help me?

Question 1,

I try to add extra properties with IdentityUser entity,
I used Application.Contracts - MyprojectNameAppDtoExtensions 

    public static void Configure()
    {
        OneTimeRunner.Run(() =>
        {
            ObjectExtensionManager.Instance
                 .AddOrUpdateProperty<IdentityUserDto, string>("UserPropertiesTest");
         }
     }

and  Domain.Shared - MyprojectNameAppModuleExtensionConfigurator

    private static void ConfigureExtraProperties()
    {
        OneTimeRunner.Run(() =>
        {
            ObjectExtensionManager.Instance.Modules()
                .ConfigureIdentity(identity =>
                {
                    identity.ConfigureUser(user =>
                    {
                        user.AddOrUpdateProperty<string>("UserPropertiesTest");
                    });
                });
        });
    }

When I use the register API，I can see the return info have the extra property，but I didn't see the extra info in mongodb with abpuser collection.

How can I add  the extra properties entities with mongo?
Could u help me to solve this problem?
Are there any example or sample code like this?

Question 2,

If I want to add the properties in request body

Like this
/api/account/register

Input info
{
  "userName": "string",
  "emailAddress": "user@example.com",
  "password": "string",
  "appName": "string"
}

I want to add the extra info in request body, How can I do this?
I didn't find the document or example,
Can someone please help me?

I will be grateful for any help you can provide.
Thank a lot.

**Comment by realLiangshiwei** [comment]
Hi,

You can check the document to know how it works: https://docs.abp.io/en/abp/latest/Entities#how-is-it-stored

>I want to add the extra info in request body, How can I do this?

```csharp
{
  "userName": "string",
  "emailAddress": "user@example.com",
  "password": "string",
  "appName": "string",
  "extraProperties": {
        "propertyName": "value...."
   }
}
```

**Comment by BZhong303** [comment]
Thank you so much for responding to my question.

Is this document mean I shouldn't add properties, and I need to add new entities for extra properties?

I need to ask, where can I set this?
{
  "userName": "string",
  "emailAddress": "user@example.com",
  "password": "string",
  "appName": "string",
  "extraProperties": {
        "propertyName": "value...."
   }
}

Thanks a lot for ur helping.

**Comment by realLiangshiwei** [comment]
Hi,

> Is this document mean I shouldn't add properties, and I need to add new entities for extra properties?

Sorry, I didn't get it, 

> I need to ask, where can I set this?

Usually, the UI will do this automatically

See: https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Web/Pages/Identity/Users/CreateModal.cshtml#L34

But for register page, you need to customize your own page.

See: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface
