### ISSUE TITLE
Abp error handling popup editing

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#11491]
Hi I want to change error messages 
![image](https://user-images.githubusercontent.com/96010802/151353630-fabb2b91-9b18-4f60-be4a-2cb0149f2fcc.png)
To my custom design and message sent from server
How??

**Comment by awahbahplana** [comment]
It is show the same popup without any exception message that sent from server
I need to change the layout from where?
I need the Abp commercial source for angular and dot net How?

**Comment by realLiangshiwei** [comment]
Hi,

Can you check this: https://docs.abp.io/en/abp/latest/UI/Angular/HTTP-Requests#http-error-handling ?

**Comment by awahbahplana** [comment]
Thanks @realLiangshiwei
