### ISSUE TITLE
is abp.io website running on Azure?

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1150]
I was wondering if abp.io is working on azure?

I am trying to get my apbcentral.com site up and running and was wondering which hosting provider should i use?

**Comment by ismcagdas** [comment]
Currently we are using a dedicated server.

**Comment by vnetonline** [comment]
which hosting provider?

**Comment by maliming** [comment]
@vnetonline 
I guess it is: https://www.natro.com/sunucu-kiralama/dedicated-server

But these depend on your country and region.
In fact, any provider that supports asp net core can. Of course, it is best to expand it easily.
