### ISSUE TITLE
Typeahead Error Blazor Webasembly

### ISSUE THREAD

**Issue by Wiblox** [abpframework/abp#11505]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

ABP 5.1.2
Blazor
EF Core

![image](https://user-images.githubusercontent.com/33899359/151706546-7ef7b5d6-8625-4dd3-8635-9818d0962cad.png)

The typehead field has a problem.
To reproduce the bug, go to the field for the modal to enter it, then select an autocomplter value.
Do not click on validate but cancel.
Then click again on the modal to create.

![image](https://user-images.githubusercontent.com/33899359/151706642-55d120f3-e3f4-460c-85ae-45cdd02e1d7a.png)
And cancel and go again
![image](https://user-images.githubusercontent.com/33899359/151706680-64e616d3-c3f1-4ff6-9c3a-8aee6e52e64e.png)

I think the error is in :
![image](https://user-images.githubusercontent.com/33899359/151706705-5c2fefd9-f47a-4a97-bcfc-870eebf732b2.png)

**Comment by Wiblox** [comment]
I have only used abp suite so far.

**Comment by Wiblox** [comment]
Tomorrow I will try by creating a new project and try to test the bug.

**Comment by Wiblox** [comment]
![image](https://user-images.githubusercontent.com/33899359/152114513-5959a62a-bbea-4cf5-bc26-1205d1387948.png)
There is an error loading the value

**Comment by enisn** [comment]
Hi @Wiblox 

Thank you for your feedback, We've solved that issue and it'll be shipped in the next v5.1 patch version

**Comment by Wiblox** [comment]
Hi @enisn 

Will there be a manual correction to be made for the existing UI ?

**Comment by enisn** [comment]
Yeah, currently you can solve with adding a null check using `?` operator for **item**.

in your case: 
`item?.DisplayName`
and
`item?.Id` or `item?.Id ?? default`

**Comment by johan-developer** [comment]
Hello enisn,

This found for the exception, but not show editing data.

Thank you,

**Comment by Wiblox** [comment]
Yes, i dont see the data.
