### ISSUE TITLE
unwanted semi-colon in the source code

### ISSUE THREAD

**Issue by hellorms** [abpframework/abp#11506]
Line 325 has an unwanted semi-colon in the source for:

Volo.Abp.Account.Pro.Public.Web.IdentityServer\ExtensionGrantValidators\ImpersonationExtensionGrantValidator.cs(325,47,325,48): warning CS0642: Possible mistaken empty statement

**if (Guid.TryParse(str, out var guid)) ;**

**Comment by maliming** [comment]
https://github.com/volosoft/volo/pull/9010

**Comment by maliming** [comment]
Thanks. We fixed it in the next version.
