### ISSUE TITLE
ABP Documentation with English is different from other’ language，these documents are not Asynchrony

### ISSUE THREAD

**Issue by tjubuntu** [abpframework/abp#11501]
Obviously ABP Documentation with English is updated frequency，but the other's documents is not Matched。
It‘s a problem that when the English document is updated by new version，the other language documents is translated by the old version，its can't Keep on the English‘s version。this problem must be solved。

**Comment by tjubuntu** [comment]
Obviously ABP Documentation with English is updated frequency，but the other's documents is not Matched。
It‘s a problem that when the English document is updated by new version，the other language documents is translated by the old version，its can't Keep on the English‘s version。this problem must be solved。

**Comment by maliming** [comment]
You can try contributing documentation in other languages. We will also improve it.
