### ISSUE TITLE
Timezone retrieval issue

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#11510]
We are experiencing problems with retrieval of Tenant Settings, specifically Abp.Timing.Timezone, from the database. Our application is running on v4.3. with Multitenancy and separate postgres databases for each Tenant. 
In the modules, where the timezone settings are needed, we have defined the ModuleSettingDefinitionProvider as the documentation instructs.

```
public class ModuleSettingDefinitionProvider : SettingDefinitionProvider
    {
        public override void Define(ISettingDefinitionContext context)
        {

            context.Add(
                    new SettingDefinition("Abp.Timing.Timezone", "UTC")
                );
        }
    }
```

In the AppServices we are using the _settingProvider.GetOrNullAsync("Abp.Timing.Timezone");

On our development enviroment we run into no problems and the correct database defined setting is retrieved and used without problems, whereas on our production we run into the issue, that the correct setting is not retrieved and the default »UTC« Timezone from the SettingDefinitionProvider is used in further operations. We have tried defining the settings:
-	In the host database (public/AbpSettings) where the Theme settings are also defined and are working fine (first row is an example of table entry working fine, other rows are the combinations we have tried to use)
![image](https://user-images.githubusercontent.com/39346964/151804033-a177615e-54ba-4a93-833d-05d940709d20.png)

-	In the tenant database (public/AbpSettings) which initially was empty
![image](https://user-images.githubusercontent.com/39346964/151804117-d1cc724c-c1e3-4b35-964b-91652f7cf11f.png)

We are aware, that with the ProviderKey value »null« in the row with the ProviderName »T« (Tenant) is incorrect, but tried it anyway. We have also tried a combination of the above variants (Default, Global, Tenant).

**Comment by tinonetic** [comment]
@leonkosak Did you manage to resolve this?
