### ISSUE TITLE
Custom client side validation

### ISSUE THREAD

**Issue by Fane276** [abpframework/abp#11512]
I am looking for an method to used custom validations for abp-input on the client side. The problem I am facing is that I could not find a way or a workaround to initialize jQuery.validate by my self. Searching in the source code I found that `$.validator.unobtrusive.parse($form);` is initialized for each form and because of that I think I can not also use jQuery.validate method. I have also tried to add `[DisableValidation]`  to my Dto but it does not allow me initialize jQuery Validator by my self. Is there any way to get this done? Is it possible to create custom validation rules over the abp ones?

In addition, I will also describe my case maybe I am going in a wrong direction and there is another approach available. I use in my form this radio input for an attribute declared as enum. `<abp-radio asp-for="@Model.Condition" inline="true"></abp-radio>`
And my desire is if the radio input has the value 0 (first element of the enum) this input of type text to be required: `<abp-input asp-for="MyDto.Input1"/>` and if the radio button has the value 1 (second element of the enum) the first input for "MyDto.Input1" to be not required and another input of type string `<abp-input asp-for="MyDto.Input2"/>` to be required instead.

ABP Framework version: 5.1.3
User Interface: MVC

**Comment by maliming** [comment]
How do you implement this in ASP NET Core without ABP?

**Comment by Fane276** [comment]
For the js file:
```
var $form = $("form#MyForm");
$form.validate({
	errorClass: "is-invalid",
	rules: {
		'Total': {
			required: true
		}
	},
	ignore: ".ignore-validation"
});

$(document).on("click",
	".trigger-ignore-validation",
	function() {
		$("#Total").addClass("ignore-validation");
	});
```
For the cshtml file:
```
<form id="MyForm">
	<label for="Total">Total</label>
	<input class="form-control" asp-for="Total"/>
	<a class="btn btn-primary trigger-ignore-validation">Ignore validation</a>
	<input class="btn btn-outline-primary" type="submit"/>
</form>
```

For this case, at first I have an input named "Total" required because of 
```
rules: {
     'Total': {
	required: true
     }
}
```
object form the js. And when I click "Ignore validation" it adds class ignore-validation and because of  `ignore: ".ignore-validation"` form can be submitted without validating the input.
