### ISSUE TITLE
Can we use [RemoteService] on ApplicationService's method

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#11527]
ABP Framework: 5.1, EF Core

We have appService with 3 methods:

```
        [Authorize]
        public async Task<LabelDto> CreateOrUpdateLabel([FromBody] LabelEditDto input)
        {
            if ((input.Id ?? 0) <= 0)            
            {
                return (await LabelCreateAsync(new LabelEditDto[] { input }))[0];
            }
            else
            {
                return await LabelUpdateAsync(input);
            }
        }

        [Authorize]
        [RemoteService(false)]
        public async Task<List<LabelDto>> LabelCreateAsync( LabelEditDto[] input)
        {
        }

        [Authorize]
        [RemoteService(false)]
        public async Task<NalepkaDto> LabelUpdateAsync(LabelEditDto input)
        {
        }

```
When running server we get error:

**Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints**

Why is that ?

I noticed if i remove "RemoteService" attribute i got another error as expected:

**Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action** 

So [RemoteService(false)] removes method from swashbucle definitions but not from MVC routing.

How we can solve this without define faik bind attribute (for example [HttpPost("Faik")] ?

**Comment by maliming** [comment]
hi

The `AbpServiceConvention` will change the controller.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Conventions/AbpServiceConvention.cs#L248

You should use `HttpPost` in your HTTP.API project.

eg https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.HttpApi/Volo/Abp/Identity/IdentityRoleController.cs#L13

**Comment by sebitsi** [comment]
Sorry @maliming i don't understand.

Shouldn't [RemoteService(false)] attribute remove method from API route and swagger spec by default ?

By [Docks](https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers)  [RemoteService(false)] should remove whole class. I test it and it works like that. But If i add RemoteService attribute to method it is not working without (for example) [HttpPost].

If I ask the question differently:

Can i use [RemoteService(false)] to hide method without specifying [Http___] attribute ?
Not just for remove from swagger, but from route binding too.

Regards.

Edvin
