### ISSUE TITLE
[Question] Is there an example on how to use GetOrAddManyAsync for the IDistributedCache

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#11539]
### Question

Is there an example on how to use GetOrAddManyAsync for the IDistributedCache?

I am having a problem when using the "GetOrAddManyAsync", How to set the keys
     
        List<string> keys = new List<string>();
        keys.Add("Persons");

        var cachedItems = await _cache.GetOrAddManyAsync(
                keys, //Cache key
                async (missingkeys) => await GetPersonsFromDatabaseAsync(),
                () => new DistributedCacheEntryOptions
                {
                    AbsoluteExpiration = DateTimeOffset.Now.AddDays(7)
                }
            );

Also will the GetPersonsFromDatabaseAsync be called everytime?

**Comment by ZouZou** [comment]
For now I did a bit of a turnaround
`        
            var cachedItems = await _cache.GetOrAddAsync(
                "Persons",
                async () => await GetPersonsFromDatabaseAsync(),
                () => new DistributedCacheEntryOptions
                {
                    AbsoluteExpiration = DateTimeOffset.Now.AddDays(7)
                }
            );`

I created on key "Persons" and the value is a list of Persons.

**Comment by maliming** [comment]
hi

See https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/test/Volo.Abp.Caching.Tests/Volo/Abp/Caching/DistributedCache_Tests.cs#L717

**Comment by ZouZou** [comment]
I did check it but it seems that I need to know the length of the keys in advance?
In my example GetPersonsFromDatabaseAsync(), will get several records (Id, Name)
Is it better if I use the GetOrAddAsync and load everything (List) into a single entry in the cache?
