### ISSUE TITLE
Use IEntityTypeConfiguration

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#11534]
Hi,
In ef-core-6.0 release is new feature EntityTypeConfiguration:  https://github.com/dotnet/efcore/issues/23163
You can read more here https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#entitytypeconfigurationattribute
For more clean code you can use for example instead of [this](https://github.com/abpframework/abp/blob/dev/modules/audit-logging/src/Volo.Abp.AuditLogging.EntityFrameworkCore/Volo/Abp/AuditLogging/EntityFrameworkCore/AbpAuditLoggingDbContextModelBuilderExtensions.cs) like this:

```
public class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog>
{
    public void Configure(EntityTypeBuilder<AuditLog> builder)
    {
           builder.ToTable(AbpAuditLoggingDbProperties.DbTablePrefix + "AuditLogs", AbpAuditLoggingDbProperties.DbSchema);

            builder.ConfigureByConvention();

            builder.Property(x => x.ApplicationName)......
           .......
    }
}

```
And you can call this [here](https://github.com/abpframework/abp/blob/dev/modules/audit-logging/src/Volo.Abp.AuditLogging.EntityFrameworkCore/Volo/Abp/AuditLogging/EntityFrameworkCore/AbpAuditLoggingDbContext.cs#L22)
like this:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
   new AuditLogConfiguration().Configure(modelBuilder.Entity<AuditLog>());
  //or:
  builder.ApplyConfiguration(new AuditLogConfiguration());
}
```

And like this example you can replace all code in all abp modules.
I think is more clean code like this.

**Comment by maliming** [comment]
hi

Thanks, @totpero I will investigate it.

**Comment by maliming** [comment]
This feature is temporarily unavailable in frameworks and modules, Thanks again.
