### ISSUE TITLE
Test with another DBContext

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#1153]
How to adapt `templates\mvc\test\MyCompanyName.MyProjectName.Application.Tests` to be able to query an entity tied to another `DbContext` ? This another context is not Abp-related. Should I modify `MyProjectNameApplicationTestModule` ? Manage another `SqliteConnection` instance ? Call another `context.DbContextOptions.UseSqlite` ? How ? I'm a bit lost in the service configuration bits in `MyProjectNameApplicationTestModule` ...

**Comment by Stirda** [comment]
I finally found how to do it. The missing piece was how to adapt the `ConfigureInMemorySqlite` method. Here's how I done it :

```
private void ConfigureInMemorySqlite(IServiceCollection services)
{
	_primarySqliteConnection 
		= CreateDatabaseAndGetConnection<PrimaryMigrationsDbContext>(
			options => new PrimaryMigrationsDbContext(options));
	_secondarySqliteConnection
		= CreateDatabaseAndGetConnection<SecondaryMigrationsDbContext>(
			options => new SecondaryMigrationsDbContext(options));

	services.Configure<AbpDbContextOptions>(options =>
	{
		options.Configure(context => { context.DbContextOptions
			.UseSqlite(
				context.ConnectionStringName == MyAppConsts.SecondaryConnectionStringName 
					? _secondarySqliteConnection
					: _primarySqliteConnection ); });
	});
}
```

**Comment by hikalkan** [comment]
Thank you for sharing your solution.

**Comment by Stirda** [comment]
Since I want to upgrade my Visual Studio solution to ABP 2.2.1 from 0.17, I restarted from the ground by downloading the new MVC template with abp-cli. Then I re-applied carefully my commits. Now, the problem is that I encounter the following exception: `System.InvalidOperationException : The specified transaction is not associated with the current connection. Only transactions associated with the current connection may be used.`. And in DbMigrator. And I would not be surprised to get this in the other projects of my solution too. For example, in tests, `MyProjectTestBase.WithUnitOfWorkAsync(Func<Task> func)` cannot handle entities linked to different DbContexts ?

**Comment by Wello86** [comment]
Hi all,

This solution helped me a little but still after am seeding data in the second database in memory, the injected context in AppServices or Repositories can not find data and DB in memory is empty!!. It seems that DI is injecting a new object of context not the same one used to seed data, any help ??

Thanks.

**Comment by Stirda** [comment]
@Wello86 Did you try to build your in-memory test database inside a file instead? I used this approach several times to investigate sqlite db content.

Also, did you implement an `IDataSeedContributor` in your `TestBase` project? Is this the way you seed your additional seed data for test runs ?

**Comment by Wello86** [comment]
Yes I used a file instead and found my content inside so this means insert is working. In test method itself the repository can not find the data. It is empty

**Comment by Wello86** [comment]
I am just doing this in my class of testing

    private readonly IRepository<MyEntity, Guid> _repository;

 _repository= GetRequiredService<IRepository<MyEntity, Guid>>();

      var result = await _repository.GetListAsync();
                result.Count.ShouldBeGreaterThan(0);

**Comment by Stirda** [comment]
@Wello86 Maybe your UOW is not aware of new data. Did you try surrounding test code calling secondary DbContext with `using (var uow = _unitOfWorkManager.Begin(requiresNew: true))`?

**Comment by Wello86** [comment]
@Stirda I used this but still not working and also I did not find this option u mentioned "requiresNew"

 await WithUnitOfWorkAsync(async () =>
            {
                var result = await _repository.GetListAsync();
                result.Count.ShouldBeGreaterThan(0);
            });

**Comment by Wello86** [comment]
@Stirda I have tried it but still not working, the sample of ABP on the first database only is working. What could be possible reasons for this to not work ?!

**Comment by Stirda** [comment]
@Wello86 
1. Is this working out of tests?
2. Did you write `context.Services.AddAbpDbContext<MySecondDbContext>(options => options.AddDefaultRepositories(); });` in `MyAppEntityFrameworkCoreModule.ConfigureServices`?
3. Did you apply https://github.com/abpframework/abp/issues/1153#issuecomment-496928705 ?

**Comment by Wello86** [comment]
@Stirda Yes the application is working properly and I am using the default repositories every where. It is just the unit testing problem

**Comment by Wello86** [comment]
@Stirda  I wrote this in my code not in different module like this post

https://github.com/abpframework/abp/blob/4228ce096ee3d9ab063f3a9799e9137ae82f2556/framework/test/Volo.Abp.EntityFrameworkCore.Tests.SecondContext/Volo/Abp/EntityFrameworkCore/TestApp/SecondContext/AbpEfCoreTestSecondContextModule.cs

 but still not working

**Comment by Wello86** [comment]
@Stirda Could you please tell me your steps for two databases unit testing to compare with mine and try to discover what is missing. I made these 
https://github.com/abpframework/abp/issues/1153#issuecomment-664030481

**Comment by Wello86** [comment]
Hi @Stirda I have made a new project with Latest ABP 3.0.5 and in this version seeding failed with this error "System.InvalidOperationException : The specified transaction is not associated with the current connection. Only transactions associated with the current connection may be used.". You have this error before as per your previous comments. Do u have the same error on insert also or just Facts ?

**Comment by Stirda** [comment]
@Wello86 Sorry for late answer but I am quite busy. To answer you I would have to dig deeper in my old project. Maybe I will find time in next days but I am afraid not this week.

**Comment by Stirda** [comment]
I see you asked Volosoft (https://github.com/abpframework/abp/issues/4955). I subscribed to your issue to be notified of the diagnosis.

**Comment by Wello86** [comment]
Hi @Stirda, It seems that your solution worked it out in version 3.0.1 in insert seed data but in version 2.3.0 not needed however it fixed my problem in test method itself, however in other methods it worked without unitofworkmanager, so now it is working. Thnx a lot for you support.

**Comment by ol964614088** [comment]
maybe there is a advice.
https://blog.csdn.net/qq_29621089/article/details/110229881
