### ISSUE TITLE
Count and ToList return difference data when has inner join

### ISSUE THREAD

**Issue by tungphien** [abpframework/abp#11542]
Count() => not include (inner join) => return number 10
ToList() => executing inner join => return 2 record

Any ideal for this issue

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)
* Steps needed to **reproduce** the problem.

**Comment by tungphien** [comment]
Thanks @maliming answer

Abp Version="6.4.0"
Database: MSSQL SERVER

I have tables:
-  User(Id, CustomerId, etc,)(10 records) and I use Data Filter(IMayHaveCustomer) https://docs.abp.io/en/abp/4.4/Data-Filtering#entityframework-core to filter by login User(only 2 records)
- Customer(Id, Name, CreatorUserId, etc,)(10 records)
- Now I Query Cusomer: Count() => return 10 and ToList() will be return 2 records

**Comment by maliming** [comment]
hi

I think this is limit of EF Core Global Query Filters

https://docs.microsoft.com/en-us/ef/core/querying/filters

**Comment by tungphien** [comment]
Thanks so much @maliming
