### ISSUE TITLE
Dynamic C# Api Clients Timeout

### ISSUE THREAD

**Issue by mehmetuken** [abpframework/abp#11545]
Hi, dynamic c# api client getting timeout error 100seconds. Any configuration options change timeout?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/rel-4.4/modules/identity/src/Volo.Abp.Identity.HttpApi.Client/Volo/Abp/Identity/AbpIdentityHttpApiClientModule.cs#L16

https://github.com/abpframework/abp/blob/rel-4.4/framework/src/Volo.Abp.Http.Client/Microsoft/Extensions/DependencyInjection/ServiceCollectionDynamicHttpClientProxyExtensions.cs#L159

https://github.com/abpframework/abp/issues/5304

**Comment by mehmetuken** [comment]
Thanks, I solved this way maybe help someone.

```cs
PreConfigure<AbpHttpClientBuilderOptions>(options =>
{
    options.ProxyClientActions.Add((remoteServiceName, clientBuilder, client) =>
    {
        client.Timeout = TimeSpan.FromMinutes(60);
    });
});
```
