### ISSUE TITLE
Tenant information should be purged from redis after deletion of a tenant

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#11549]
Originally posted here: https://support.abp.io/QA/Questions/2522/Tenant-not-found-There-is-no-tenant-with-the-tenant-id-or-name-00bbbd7e-953d-7c7d-3842-3a01cc9219ec

**Comment by righen** [comment]
@enisn @hikalkan Can you assign the issue to me?

**Comment by enisn** [comment]
I've assigned to you @righen , make sure you've read the contribution guide before sending a pull request. Good luck 🤞

**Comment by sturlath** [comment]
Was this fixed somewhere else? My test users hit this regularly on our dev environment when they create a new tenant and the old one is in the way. Nothing critical but anoying..

**Comment by enisn** [comment]
I just moved this issue to internal issue tracking system. It's solved and shipped in v5.2.1
