### ISSUE TITLE
Is here  a bug?

### ISSUE THREAD

**Issue by yilianhuaixiao** [abpframework/abp#1155]
https://github.com/abpframework/abp/blob/21f8edaf13b0a00cf10471dd8d53b1c3c6dd6f92/framework/src/Volo.Abp.Core/Microsoft/Extensions/DependencyInjection/ServiceCollectionCommonExtensions.cs#L48

Is there  a bug?  
 Shoudn't it be
```
  i.GetTypeInfo().IsGenericType==false
```

**Comment by maliming** [comment]
It doesn't look like a bug. What problem have you encountered?

**Comment by yilianhuaixiao** [comment]
if factoryInterface is a generic type definition ,  factoryInterface.GenericTypeArguments  may  return blank array.  factoryInterface.GenericTypeArguments[0]  may throw exception.
In  ServiceCollectionExtensions.cs , i saw the  follows use.
`services.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(new AutofacServiceProviderFactory(configurationAction))`

**Comment by maliming** [comment]
You are right, I will try to fix it.

**Comment by maliming** [comment]
@yilianhuaixiao
Can you share the code for the above problem?

**Comment by yilianhuaixiao** [comment]
OK. I pushed a request first time in my github life.

**Comment by maliming** [comment]
I mean, did you use the IServiceProviderFactory interface or did your other code cause this problem?

Please share the relevant code.

**Comment by yilianhuaixiao** [comment]
PersonAppService_Tests.cs cannot pass the test. Is this the reason?

**Comment by maliming** [comment]
But the construction and testing in the CI have passed.
Did your local test fail? If yes, please share the failure information (including the stack)

**Comment by yilianhuaixiao** [comment]
After debugging I get it. the code is right.

Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[Autofac.ContainerBuilder]  

IsGenericType  is true
