### ISSUE TITLE
Add where condition on ExtraProperty column value

### ISSUE THREAD

**Issue by eneskoroglu** [abpframework/abp#11566]
* Your **ABP Framework version**. 4.4.4
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: Angular
* Your database provider(EF Core/MongoDB) EF Core

We store some values on ExtraProperty column and we need to filter data by this info.  We tried to add our info which is stored in ExtraProperty as property (for ex. HasFifo) and add a condition on this column we get below error.

.Where(p => p.HasFifo == (Nullable<bool>)True)' could not be translated. Additional information: Translation of member 'HasFifo' on entity type 'Product' failed. This commonly occurs when the specified member is unmapped. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'.

**Comment by berkansasmaz** [comment]
Hi,

See: https://github.com/abpframework/abp/issues/10662#issuecomment-972765041

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
