### ISSUE TITLE
UOW Default Options not been respected

### ISSUE THREAD

**Issue by lommez** [abpframework/abp#11567]
I've created a simple console application with Dapper.

In my module i've changed the default behavior, just like this:

![image](https://user-images.githubusercontent.com/10900667/153627902-a67e278e-59ed-4a22-ad65-ab32566773c1.png)

If the UnitOfManager.Begin method is called without passing values just like that:

![image](https://user-images.githubusercontent.com/10900667/153628383-bc6f44c8-8326-4220-8905-52756796441e.png)

In the Dapper Repository, after calling to get DbTransaction, the variable is null:

![image](https://user-images.githubusercontent.com/10900667/153628760-45ac708b-ff60-4d03-93b3-22ca0daa04d3.png)

I got two questions:

1) The UOW shouldn't be transactional?

2) Even passing some parameter values to the Begin method just like that:

![image](https://user-images.githubusercontent.com/10900667/153629568-c58a99b6-dcde-4f18-9b50-cd54166e000b.png)

The timeout value is not set in the DbConnection as a new value. Is that also a bug?

thanks

**Comment by maliming** [comment]
The `Begin` method is the extension method.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkManagerExtensions.cs#L10

**Comment by lommez** [comment]
thanks @maliming 
but according to the [https://docs.abp.io/en/abp/latest/Unit-Of-Work#default-options](https://docs.abp.io/en/abp/latest/Unit-Of-Work#default-options) this shouldn't be respecting what have been defined in the module configure method? Instead of creating a new AbpUnitOfWorkOptions instance?

**Comment by maliming** [comment]
You can call this method.
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/IUnitOfWorkManager.cs#L11
