### ISSUE TITLE
Is there a problem with Users page search/filter?

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#11568]
5.1.3 - MVC - EF Core

After we upgrade from 4 to 5.1.3 we realized filter not working on users page.

When I compare this file [https://github.com/abpframework/abp/blob/bc87382d2fb789ac11d54a45ff829edf42b9f7f3/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js]  with the one in the  theme-shared dll they are different. Especially around [//Text filter] line 368.

The one in the formal bundle is not working. When I put the one under the above link it works. Am I doing something wrong? 

Btw: We have our own theme-basic project, copied from the code and changed a little bit.

**Comment by maliming** [comment]
Thanks. I will check that.

**Comment by maliming** [comment]
They are the same. You can copy the latest code to your project(`datatables-extensions.js`).

![image](https://user-images.githubusercontent.com/6908465/153734237-54a84b4d-208e-44b0-9178-a2c1e6648848.png)
