### ISSUE TITLE
Log in user in ABP automatically? 

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11561]
* Your **ABP Framework version**. 5.1.3
* Your **User Interface** type: Blazor Server

For a quite specific use case, we would need to have a user authenticated even though they themselves don't actually log in or even notice it. Is it possible in ABP to do some kind of scripted login like redirecting to a URL like "https://www.mysite.com/Account/Login?username=username&password=password? Think something like having a Contact form that is perceived to be on a website but is actually hosted in an ABP solution. 

This account will have very limited permissions so we don't see a risk in it being "hacked". And yes, we know that it would probably be better to do something with Angular against the API but this is more of a temporary solution. 

Thanks.

**Comment by DonVliet** [comment]
Have a look at the  **SignInManager.PasswordSignInAsync** and  **GetAbpLoginResult** methods e.g.

var signInResult = await SignInManager.PasswordSignInAsync(
    login.UserNameOrEmailAddress,
    login.Password,
    login.RememberMe,
    true
);

var result = GetAbpLoginResult(signInResult);

as used in the following controller:

/modules/account/src/Volo.Abp.Account.Web/Areas/Account/Controllers)/AccountController.cs
