### ISSUE TITLE
EfCore SplitQuery consistency 

### ISSUE THREAD

**Issue by nev-21** [abpframework/abp#11569]
### Discussion about the framework (Consistency)

* ABP Framework version **5.1.3**.
* EfCore Npgsql

### Data Consistency
https://docs.microsoft.com/en-us/ef/core/querying/single-split-queries#characteristics-of-split-queries
```
While most databases guarantee data consistency for single queries, no such guarantees exist for multiple queries.
If the database is updated concurrently when executing your queries, resulting data may not be consistent.
You can mitigate it by wrapping the queries in a serializable or snapshot transaction, although doing so
may create performance issues of its own. For more information, see your database's documentation.
```

When I use the framework to make a DDD solution:

- If I use GetAsync of IBasicRepository, with an AggregateRoot that has related Entities (with reference properties), I understand that the Aggregate coudl be loaded in an invalid state. Is this posible? Should I worry about this?
- If that is the case. Is there a way, to turnoff SplitQuery only for GetAsync(or similar methods) while it is enabled globally? Should all ReadOnlyRepository methods has AsSingleQuery() by default?

**Comment by maliming** [comment]
You can use a custom action to configure `UseQuerySplittingBehavior`.

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.EntityFrameworkCore.PostgreSql/Volo/Abp/EntityFrameworkCore/AbpDbContextConfigurationContextPostgreSqlExtensions.cs#L27-L28

**Comment by nev-21** [comment]
Thanks @maliming, there is something similar in the docs:
https://docs.abp.io/en/abp/latest/Entity-Framework-Core#split-queries

But it disable the Splitting globally. Is there a way to disable just for ReadOnlyRepository methods?  in order to avoid invalid state Aggregates.
