### ISSUE TITLE
easy crm demo broke

### ISSUE THREAD

**Issue by nebula2** [abpframework/abp#11571]
When logging in to [easy crm demo](http://easycrm.samples.commercial.abp.io/ ) with the credentials provided there it throws an error message
![image](https://user-images.githubusercontent.com/5841525/153761524-19372b88-2eaa-4f73-ae71-1db21189bb6d.png)

Clicking it away just shows this here for infinity
![image](https://user-images.githubusercontent.com/5841525/153761544-09787132-9ff1-4f30-bd13-c0600b1fcdea.png)

![image](https://user-images.githubusercontent.com/5841525/153761611-22a13931-8058-483c-828c-b8442fdb1e38.png)

**Comment by realLiangshiwei** [comment]
@nebula2 

Can you try opening an InPrivate window or clear cookies and try again?

**Comment by nebula2** [comment]
sorry to waste your time... that was it
