### ISSUE TITLE
Run IdentityService.Host returns NullReferenceException

### ISSUE THREAD

**Issue by GotzeWong** [abpframework/abp#11572]
* ABP  4.4.2
* MVC
* Database provider(EF Core)
* Steps: 
   1. Download the Microservice Demo Solution
   2. Build all sub-projects and DB
   3. Running Microservice return 500, it shows exception as below

![image](https://user-images.githubusercontent.com/7664030/153769861-8ca83e95-0d43-46d9-bcb6-d006dd7bba26.png)

 The solution works before and I have no idea why this happened?

**Comment by maliming** [comment]
Microservice Demo is no longer active, You can check the [eShopOnAbp](https://github.com/abpframework/eShopOnAbp) now.
