### ISSUE TITLE
Custom tenant resolver doesnt seem to resolve tenant

### ISSUE THREAD

**Issue by stousmand** [abpframework/abp#11577]
Hi, I'm trying to implement a custom tenant resolver as mentioned in the [documentation](https://github.com/abpframework/abp/blob/dev/docs/en/Multi-Tenancy.md) which is similar to this [documentation](https://docs.abp.io/en/abp/4.4/Multi-Tenancy). Initially I run the program before the Swagger is generated, then the ResolveAsync method in my custom tenant resolver is executed. Next I tried making a call using postman to an app service but the tenant resolver ResolveAsync method is not executed. Anything I should know about custom resolver implementation? other than whats mentioned in the document?

Thanks, appreciate the help.

I'm using these : 
1. ABP Framework version : 4.4
2. User Interface type : None
3. Database provider : EF Core

**Comment by realLiangshiwei** [comment]
Hi,

The documentation covers all points.

You can also see the pre-built tenant resolver:https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.AspNetCore.MultiTenancy/Volo/Abp/AspNetCore/MultiTenancy/AbpAspNetCoreMultiTenancyModule.cs#L15

**Comment by stousmand** [comment]
Hi, @realLiangshiwei thanks for the reply. Okay I've done whats mentioned in the documentation. Any clue or idea why the custom tenant resolver isn't called when a service call is made? it should right? resolving should be done for each and every call? or am I missing something?

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by stousmand** [comment]
@realLiangshiwei Oh sorry about that

1. Implemented custom resolver
![image](https://user-images.githubusercontent.com/29155859/153986490-ca159ad5-4541-4a7b-b621-aa7ff47a5e50.png)

```
 var _principalAccessor = context.ServiceProvider.GetRequiredService<ICurrentPrincipalAccessor>();
```
Used to get the Bearer token details
```
var _tenantRepository = context.ServiceProvider.GetRequiredService<ICommTenantRepository>();
```
Used to read a remote DB where tenant data is at (another DBContext is setup for this, it connects to the DB and queries necessary data when debugged)

2. The above source is placed in ```*.Domain``` module. And the configuration was added

![image](https://user-images.githubusercontent.com/29155859/153987193-fa8dc3fa-23c0-4097-b0f3-a7e733f9b62d.png)

3. Place debug point in **ResolveAsync** method
4. Startup the server in IDE (here used VisualStudio)
5. ResolveAsync method in my custom tenant resolver is executed, debug point hit, no exceptions thrown in console.
6. Opened _Postman_, make a call to a custom REST service to an endpoint created in `*.HttpApi`
7. The tenant resolver **ResolveAsync**  isn't executed

**Comment by realLiangshiwei** [comment]
Hi,

Can you try this?

```csharp
Configure<AbpTenantResolveOptions>(options =>
{
    options.TenantResolvers.Insert(0, new xxx());
});
```

**Comment by stousmand** [comment]
@realLiangshiwei, thanks for the tip. Seems to work now. 👍🏾
