### ISSUE TITLE
Documentation Filter not working on mobile (ios)

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#11585]
the filter ( not the search ) function doesnt work on ios. it shows everything regardless of what you enter

tested with 15.3

**Comment by realLiangshiwei** [comment]
Hi,

Can you share some screenshots? thanks.

**Comment by puschie286** [comment]
![7D92B2BD-1643-4138-8DF9-BE2FAA004EA9](https://user-images.githubusercontent.com/2429036/154213845-26cc7d7c-ce5d-4e44-9743-b7d56b42cf40.jpeg)

tried to filter on localization

**Comment by realLiangshiwei** [comment]
I will check it.
