### ISSUE TITLE
ABP & CMS

### ISSUE THREAD

**Issue by Eliakos** [abpframework/abp#11592]
Hello, 

Can ABP work with a .NET CMS such as Orchard or Squidex?
Any example of a supported CMS or a CMS using ABP ?

**Comment by realLiangshiwei** [comment]
Duplicate of https://github.com/abpframework/abp/issues/11593

**Comment by realLiangshiwei** [comment]
By the way ,we have a cms-kit module: https://github.com/abpframework/abp/tree/dev/modules/cms-kit

**Comment by Eliakos** [comment]
> Duplicate of #11593

Orleans and CMS are 2 different universes, having nothing in common, so no duplicate here
