### ISSUE TITLE
Orleans as a backend technology?

### ISSUE THREAD

**Issue by Eliakos** [abpframework/abp#11593]
Hi,

Can Orleans be used with ABP? For the benefit of :

- automatic clustering
- no caching needed
- easy deplyment (no need to setup a dedicated machine for the background jobs.)
- Performance

**Comment by realLiangshiwei** [comment]
It is in the backlog, but we have no plan to do it yet. you can try to implement it yourself and welcome to share your experience

See: https://github.com/abpframework/abp/issues/8750
