### ISSUE TITLE
How do I create a second Angular App inside Angular project and make IdentityServer work?

### ISSUE THREAD

**Issue by idreeshaddad** [abpframework/abp#11598]
**ABP Framework version**: v4.3.0
**User Interface**: Angular v11.2.11
**Database provider**: EF Core

How do I create a second Angular App inside Angular project, in a way that allows me to consume the same C# proxy, and also use the same IdentityServer?

**What I've tried so far**:
- Made the second app via angular command `ng generate application exampleApp` and started moving dependencies from ABP Angular project app.module.
- The second app runs on port `4300` so `http://localhost:4300` was added to `CorsOrigins` in `appsettings`
- Under appsettings in DbMigrator project and under IdentityServer:Clients added the following:
```JSON
"exampleApp": {
    "ClientId": "exampleApp",
    "ClientSecret": "1q2w3e*",
    "RootUrl": "http://localhost:4300"
}
```
- In the exampleApp environment.ts the following was added:
```
const baseUrl = 'http://localhost:4300';

export const environment = {
  production: false,
  application: {
    baseUrl,
    name: 'exampleApp',
    logoUrl: '',
  },
  oAuthConfig: {
    issuer: 'https://localhost:44350', 
    redirectUri: baseUrl,
    clientId: 'exampleApp',
    responseType: 'code',
    scope: 'offline_access exampleApp'
  },
  apis: {
    default: {
      url: 'https://localhost:44350',
      rootNamespace: 'AB.XYZ',
    },
  },
} as Environment;
``` 

When I serve exampleApp on port `4300` then try to login it redirects me to the primary app on port `4200`.

Could you please provide me with guidance? 

[Question on Stackoverflow](https://stackoverflow.com/questions/71140696/how-do-i-create-a-second-angular-app-inside-angular-project-in-abp-io)

**Comment by gterdem** [comment]
Basically, you need to create different client with different redirect uri in authentication server (identityserver).

There **can not be** an application inside an other application. They are different applications.

**Comment by idreeshaddad** [comment]
It's not an application inside another application. They are two applications under the same Angular workspace.
They are working separately on different ports and they consume the ABP generated proxy just fine.

The question is, how to make both apps work with IdentityServer. I believe you touched on that in the first line of your response, can you please elaborate?

**Comment by gterdem** [comment]
I have written a detailed explanation to your [stackoverflow question](https://stackoverflow.com/a/71153951/2594735). Feel free to ask or create issue if you come across any problems.
