### ISSUE TITLE
Conflict 409 Http return values are not handled in Angular UI

### ISSUE THREAD

**Issue by GitOPa** [abpframework/abp#11602]
* Your **ABP Framework version**. 5.1.2
* Your **User Interface** type Angular
* Your database provider EF Core

Why is the return value 409 (Conflict) not handled separately in Angular side? https://github.com/abpframework/abp/blob/87a7482d08a679b002ebece0b84c8aaba15d9c89/npm/ng-packs/packages/theme-shared/src/lib/handlers/error.handler.ts#L321

Is there a way to configure a common handling for 409 error so we don't need to change every request error handling?

**Comment by realLiangshiwei** [comment]
Can you check this? https://docs.abp.io/en/abp/latest/UI/Angular/HTTP-Requests#http-error-handling

**Comment by GitOPa** [comment]
Ok, thanks. 
We ended up making a custom error handler as the documentation suggested. However, there seems to be some problem specifically in 409 handlings. At first, the 409 error is visualized correctly in dev tools
![image](https://user-images.githubusercontent.com/10799974/154636529-86f7c59e-d29d-4f84-9163-7244f1e0a47e.png)

After this, our custom error handling sees incorrect error code 0 
![image](https://user-images.githubusercontent.com/10799974/154636701-f1ba53d4-290e-4080-90d9-7f8c575853df.png)

And after that the code is wrong in dev tools as well
![image](https://user-images.githubusercontent.com/10799974/154636798-3c7d4201-89f6-4cc1-b43f-c391a4564b09.png)

All other error codes come correctly to our custom error handler

**Comment by GitOPa** [comment]
Any news on this?
