### ISSUE TITLE
localize login or logout state messages

### ISSUE THREAD

**Issue by arminfarzam** [abpframework/abp#11600]
in blazor authorized pages abp identity server check authentication and show *...checking login state* message 
before redirect to identity server login page or when  logging out show the *processing logout* message. how we can localize this messages?

**Comment by realLiangshiwei** [comment]
Hi,

I didn't get it, can you share some screenshots?

**Comment by arminfarzam** [comment]
![image](https://user-images.githubusercontent.com/59694737/154418698-4418d3a0-b659-4176-9f90-84878717eaae.png)

![Screenshot (13)](https://user-images.githubusercontent.com/59694737/154418912-94fd581e-c1fd-432c-beb6-773c03e94214.png)

![Screenshot (14)](https://user-images.githubusercontent.com/59694737/154418943-e2a06263-68b6-404e-8525-73dbbb7b4903.png)

i need localize this messages. thank you

**Comment by maliming** [comment]
This is an ASP NET Core problem, they don't consider localization.

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L403

**Comment by arminfarzam** [comment]
thank you, overriding this class probably will solve my problem.

**Comment by ParsaGachkar** [comment]
@arminfrzm72 I think you need the basic theme source code for this. add basic theme module with source code to your project [Abp cli add-module doc](https://docs.abp.io/en/abp/latest/CLI#add-module); then edit this component `modules\Volo.BasicTheme\src\Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme\Pages\Authentication.razor`
here is a [link](https://code-maze.com/authentication-in-blazor-webassembly-hosted-applications/) for reference. i'm assuming you are working with blazor-wasm template.

**Comment by realLiangshiwei** [comment]
You can try:

MyAuthentication.razor
```csharp
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@inherits Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme.Pages.Authentication
<RemoteAuthenticatorView Action="@Action">
    <LoggingIn>
        my custom login message....
    </LoggingIn>
</RemoteAuthenticatorView>
```
MyAuthentication.razor.cs
```csharp
[ExposeServices(typeof(Authentication))]
[Dependency(ReplaceServices = true)]
public partial class MyAuthentication
{
    
}
```

More actions , see: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0#customize-the-authentication-user-interface
