### ISSUE TITLE
"Blazor UI: Error Handling" not working

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11608]
* Your **ABP Framework version**. **5.1.3**
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: **Blazor Server**

It seems the "Blazor UI: Error Handling" (https://docs.abp.io/en/abp/latest/UI/Blazor/Error-Handling) isn't working as intended. To verify, we created a fresh ABP solution and just used the sample code provided. 

`@page "/"
@using Volo.Abp

<Button Clicked="TestException">Throw test exception</Button>

@code
{
    private void TestException()
    {
        throw new UserFriendlyException("A user friendly error message!");
    }
}`

This should produce this

![image](https://user-images.githubusercontent.com/2812422/154312272-a7308550-d7ea-43f2-a127-b59182c461d1.png)

but instead you get the normal Blazor Yellow exception bar. 

![image](https://user-images.githubusercontent.com/2812422/154312414-ed40889f-f93b-499c-bfbd-d24a9c7520d3.png)

In the log file you get expected result:

2022-02-16 17:33:07.282 +01:00 [WRN] Unhandled exception rendering component: A user friendly error message!
Volo.Abp.UserFriendlyException: A user friendly error message!

**Comment by EngincanV** [comment]
Hi @improwise, see https://github.com/abpframework/abp/issues/11396#issuecomment-1018197353

**Comment by improwise** [comment]
Thanks. It would probably be a good idea to highlight this in the documentation.

**Comment by improwise** [comment]
> Hi @improwise, see [#11396 (comment)](https://github.com/abpframework/abp/issues/11396#issuecomment-1018197353)

Thanks. It would probably be a good idea to highlight this in the documentation.
