### ISSUE TITLE
generate-proxy: compile error

### ISSUE THREAD

**Issue by lgadola** [abpframework/abp#11616]
* Your **ABP Framework version: 5.1.3.
* Your **User Interface** Angular
* Your database provider: EF Core
* Exception message:
 Error: src/app/proxy/microsoft/extensions/primitives/models.ts:2:40 - error TS2693: 'any' only refers to a type, but is being used as a value here.

2 export interface StringSegment extends any {
                                         ~~~

This error is thrown after abp generate-proxy. When I remove "extends any" it compiles. Could that be removed from generation?

**Comment by maliming** [comment]
Please share more info to reproduce that problem.
