### ISSUE TITLE
Angular generate-proxy - (Dto missing)

### ISSUE THREAD

**Issue by nev-21** [abpframework/abp#11618]
* ABP Framework **5.1.3**.
* User Interface **Angular** 13

### Issue Description

The issue occurs if there are two or more abp backend modules, and 1 angular project. 
Angular proxy folder contains "models.ts" with missing Dtos.

 
### Steps to reproduce

Create two **abp modules**(with no ui), both has a reference to a dotnet csproj (not abp) which has few Dtos. 

- Simple dotnet class library project: Dto1, Dto2, Dto3 ( all Dtos in the same namespace "**SimpleDtos**")
- Module A has AppService methods that return Dto1 and Dto2.
- Module B has AppService methods that return Dto3. 

Create an **Abp App with angular UI**, and register the modules in Conventional Controllers (HttpApiHostModule). Run Host.

Run the cli commands in angular folder:

1.  abp generate-proxy -t ng
2. abp generate-proxy -t ng -m modulea
3. abp generate-proxy -t ng -m moduleb

Check the proxy folder, inside the **simple-dtos** folder, the models.ts file: 

- Only the Dto3 is present

**Comment by czart8** [comment]
I have the same problem. This problem also occured in a 4.x versions.

**Comment by muhammedaltug** [comment]
Hello,

We will work on this. You can follow the steps below to avoid this problem right now:
 - Create an angular package with `ng g library module-a`
 - Update tsconfig paths for module-a with the following in `tsconfig.json`
 ```json
 "paths": {
      // other paths
      "module-a": ["projects/module-a/src/public-api.ts"]
    }
```
- Update your environment file for module-a with the following in `environment.ts`
```typescript
apis: {
    // other apis 
    ModuleA: {
      rootNamespace: 'ModuleA',
    },
  }
```
- Run the generate proxy command in `angular` folder. `abp generate-proxy -t ng -m modulea --target module-a -a ModuleA`
- Update `public-api.ts` in `packages/module-a/src/public-api.ts` with following code
```typescript
// other exports
export * from './lib/proxy';
```
- Repeat these steps for module-b 

You can look [example project](https://github.com/enisn/abp-11618)

**Comment by mrsleepman** [comment]
same problem

abp generate-proxy -t ng

ABP CLI 8.1.3
UPDATE src/app/proxy/generate-proxy.json (355829 bytes)
UPDATE src/app/proxy/README.md (1000 bytes)
UPDATE src/app/proxy/metric.service.ts (2029 bytes)
UPDATE src/app/proxy/metric-type.service.ts (1689 bytes)
UPDATE src/app/proxy/server-info.service.ts (1938 bytes)
UPDATE src/app/proxy/index.ts (112 bytes)
