### ISSUE TITLE
LocalEvent how to response exception message

### ISSUE THREAD

**Issue by qinxh** [abpframework/abp#11619]
use `AddLocalEvent` in `AggregateRoot`.
how to response exception message?
i get warning log "An exception occurred, but response has already started!".
but http status code is 200

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)
* **Steps needed to **reproduce** the problem**.

**Comment by qinxh** [comment]
- version: 5.1.3
- database provider: EF Core
- reproduce
1. create application: 'abp new Acme.BookStore'
2. create entity
```
public class Book : AuditedAggregateRoot<Guid>
    {
        public string Name { get; set; }

        public BookType Type { get; set; }

        public DateTime PublishDate { get; set; }

        public float Price { get; set; }
    }
```
3. create application service
```
public class BookHandler
        : ILocalEventHandler<EntityUpdatedEventData<Book>>,
          ITransientDependency
    {
        public virtual async Task HandleEventAsync(
            EntityUpdatedEventData<Book> eventData)
        {
            var name = eventData.Entity.Name;
            Console.WriteLine("book-name: " + name);
            throw new Exception("BookHandler Exception");
        }
    }
````
4. create simple LocalEventHandler
```
public class BookHandler
        : ILocalEventHandler<EntityUpdatedEventData<Book>>,
          ITransientDependency
    {
        public virtual async Task HandleEventAsync(
            EntityUpdatedEventData<Book> eventData)
        {
            var name = eventData.Entity.Name;
            Console.WriteLine("book-name: " + name);
            throw new Exception("BookHandler Exception");
        }
    }
```
5. request http api
```
curl --location --request PUT 'https://localhost:44389/api/app/book/364EAAFF-CD0C-54E6-BA7C-3A020E9F52A9' \
--header 'User-Agent: Apipost client Runtime/+https://www.apipost.cn/' \
--header 'Content-Type: application/json' \
--data '{
  "name": "test123",
  "type": 1,
  "publishDate": "2022-02-18",
  "price": 0
}'
```
response code is 200.
response content
```
{
	"name": "test123",
	"type": 1,
	"publishDate": "2022-02-18T00:00:00",
	"price": 0,
	"lastModificationTime": "2022-02-18T13:57:28.5881135+08:00",
	"lastModifierId": null,
	"creationTime": "2022-02-15T16:14:28.0248192",
	"creatorId": null,
	"id": "364eaaff-cd0c-54e6-ba7c-3a020e9f52a9"
}
````
6. i get BookHandler Exception in log. but there is no exception message in the responsed.
@realLiangshiwei

**Comment by realLiangshiwei** [comment]
I will check it

**Comment by realLiangshiwei** [comment]
@qinxh 

The step 3 same with 4

![image](https://user-images.githubusercontent.com/16813853/154642942-b3e66641-f820-4e49-9fa2-4b5f19f4d05a.png)

**Comment by qinxh** [comment]
@realLiangshiwei setp 3
```
public interface IBookAppService:
        ICrudAppService< //Defines CRUD methods
            BookDto, //Used to show books
            Guid, //Primary key of the book entity
            PagedAndSortedResultRequestDto, //Used for paging/sorting
            CreateUpdateBookDto> //Used to create/update a book
    {

    }

public class BookAppService :
        CrudAppService<
            Book, //The Book entity
            BookDto, //Used to show books
            Guid, //Primary key of the book entity
            PagedAndSortedResultRequestDto, //Used for paging/sorting
            CreateUpdateBookDto>, //Used to create/update a book
        IBookAppService //implement the IBookAppService
    {
        public BookAppService(IRepository<Book, Guid> repository)
           : base(repository)
        {

        }

    }
```

**Comment by realLiangshiwei** [comment]
> for now, just remove app.UseUnitOfWork() from the ASP.NET Core pipeline, your problem should be solved.

See: https://github.com/abpframework/abp/issues/8740#issuecomment-825637586

We will implement it: https://github.com/abpframework/abp/issues/10568#issue-1048233070

**Comment by steffbeckers** [comment]
I have the same issue here. In an API request scope, throwing an exception in a ILocalEventHandler<...> results in a 200 response code without any data in the response.

![image](https://github.com/abpframework/abp/assets/7551394/ef57bdf5-d5c8-437b-9fde-f29e75925a4c)

![image](https://github.com/abpframework/abp/assets/7551394/56dc334b-0e2d-4000-9bc2-e20293ce7ae4)

![image](https://github.com/abpframework/abp/assets/7551394/87c5c684-aa73-4296-9434-d3bc265f0801)
