### ISSUE TITLE
list.isLoading$ is not refreshed when re-calling list.get()

### ISSUE THREAD

**Issue by bodeg** [abpframework/abp#11620]
* **ABP Framework version** 5.1.3.
* **User Interface** Angular
* **database provider** EF Core
* Steps needed to **reproduce** the problem.

```
ngOnInit() {
    this.hookToQuery();
 }

hookToQuery() {
    const streamCreator = (query) => this.dataService.getList(query);

    this.list.hookToQuery(streamCreator)
      .subscribe((response) => {
        this.pagedResultDto = response;
      });
}

```
when loading on the first time 
`list.isLoading$ | async // is true when on loading`

then I call again to 
`this.list.get()`
for example after creating a new entity

`list.isLoading$ | async // stays false`

I am using list.isLoading$ with ngx-datatable

```
<ngx-datatable
      [rows]='pagedResultDto.items'
      [count]='pagedResultDto.totalCount'
      [list]='list'
      [abpLoading]='list.isLoading$ | async'
      default
 >
```

**Comment by muhammedaltug** [comment]
Hello thanks for reporting the issue, It will be fixed when https://github.com/abpframework/abp/pull/12973 is released
