### ISSUE TITLE
Remove permissions in especific test.

### ISSUE THREAD

**Issue by firminoeducbank** [abpframework/abp#11626]
We using this setting in tests application module 

```c#
public override void ConfigureServices(ServiceConfigurationContext context)
{
    context.Services.AddAlwaysAllowAuthorization();
}
```

How can I change this configuration for a unique test ?

**Comment by NecatiMeral** [comment]
You could create a own module for this specific test, which reconfigures your defaults.

Another way of solving this could be this over here. You can move your test to another testing class and override [the SetAbpApplicationCreationOptions method](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.TestBase/Volo/Abp/Testing/AbpIntegratedTest.cs#L44).
