### ISSUE TITLE
How to disable query Volo.Abp.LanguageManagement.Texts for app service?

### ISSUE THREAD

**Issue by rwecho** [abpframework/abp#11647]
Hi: 
I have a project using a commercial version without source code.
In the project, there is some APIs need to be called very frequently. And it throws exceptions like below:

![image](https://user-images.githubusercontent.com/8048753/154896056-7107c018-20c8-4a4d-bbe3-b004a4c335be.png)

This is an interface for getting image data. So I do not think it needs Redis every time.

Thanks in advance.

**Comment by maliming** [comment]
HI

Please create question here: https://support.abp.io/QA/Questions/New  include Steps needed to **reproduce** the problem.
