### ISSUE TITLE
ABP localization is slow for untranslated entries

### ISSUE THREAD

**Issue by fokkog** [abpframework/abp#11641]
* **ABP Framework version**: 4.4.4
* **User Interface**: MVC UI with Razor Pages (not that it matters)
* **Database provider**: EF Core (not that it matters)
* **Exception message/stack trace**: not applicable
* **Steps to reproduce**: see below

The following page takes 6 seconds to render on my laptop:
```
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using Volo.Abp.TenantManagement.Localization
@inject IHtmlLocalizer<AbpTenantManagementResource> L

<span>START: @DateTime.Now</span>
<br>
@for (var i = 0; i < 1000; i++)
{
    @L["Permission:Create"].Value
}
<br><span>END: @DateTime.Now</span>
<br>
<span>START: @DateTime.Now</span>
<br>
@for (var i = 0; i < 1000; i++)
{
    @L["NotExist"].Value
}
<br><span>END: @DateTime.Now</span>
<br>
```

The first loop is fast, the second loop is slow. 1000 lookups may seem like a lot, but we have dynamic forms that can have that many input fields. The HTML rendering of such a form was unbearably slow. I suspected the Razor engine, but after profiling it became clear that 60% of the time was spent in label lookups. After overriding AbpDictionaryBasedStringLocalizer with a caching version, this 60% was eliminated (and the above page takes milliseconds to render as expected).

**Comment by maliming** [comment]
hi

Can you test it in console or unit test project and share it?

**Comment by fokkog** [comment]
The provided code snippet was already intended as an isolated and effective reproducer. It can be copy/pasted to any existing page to see it in action. Does a console app/test project really add value and if so, how should i share it?

**Comment by maliming** [comment]
You can share it on Github.

**Comment by maliming** [comment]
hi

I will check this, Thanks.

**Comment by fokkog** [comment]
Thanks!
