### ISSUE TITLE
When using a complex form model (with nesting and repetitions) it's possible to accidentally lose form edits

### ISSUE THREAD

**Issue by fokkog** [abpframework/abp#11640]
* **ABP Framework version**: 4.4.4
* **User Interface**: MVC UI with Razor Pages
* **Database provider**: EF Core (not that it matters)
* **Exception message/stack trace**: not applicable
* **Steps to reproduce**: see below

Our abp.io-based application has multiple CRUD screens, one of them large and dynamic. We use the [partial tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper) to share the Razor code between the Create and Edit screens. Then inside the partial CSHTML, nested/repeated form elements get rendered. As a result, the form contains HTML elements with names such as:
1. Decl.OwnRef
2. Decl.Seller.Name
3. Decl.Docs[0].Id
4. Decl.Items[0].Descr
5. Decl.Items[0].Infos[1].Code

This mostly works fine, except for one mostly cosmetic/sometimes disturbing issue: many form elements are skipped by the "dirty checking" which decides whether a "You have unsaved changes. Are you sure?" warning needs to be presented on form cancel/modal close. After debugging the culprit seems the jQuery extension method `serializeFormToObject()`, specifically this snippet:
```
data.map(function (x) {
    //TODO: improve mapping. it only supports one level deep object.
    var names = x.name.split(".");
    if (names.length === 1 && !obj[names[0]]) {
        obj[names[0]] = x.value;
    }
    else if (names.length === 2) {
        if (!obj[names[0]]) {
            obj[names[0]] = {};
        }
        if (!obj[names[0]][names[1]]) {
            obj[names[0]][names[1]] = x.value;
        }
    }
});
```

As suggested by the TODO, this mapping is too simple. In our context it drops the vast majority of form elements (all but the 1st of the 5 listed above). This means it's all too easy for `needConfirmationOnUnsavedClose()` to see identical values for unEditedForm and currentForm.

To work around this we have overridden quoted code with a simplified version that creates a flat object (sufficient for our purposes). A generic solution could leverage https://github.com/maxatwork/form2js or https://github.com/marioizquierdo/jquery.serializeJSON.

**Comment by maliming** [comment]
Thanks, I will research the https://github.com/maxatwork/form2js and https://github.com/marioizquierdo/jquery.serializeJSON.

**Comment by maliming** [comment]
hi @fokkog 

Can you test this PR? https://github.com/abpframework/abp/pull/11659

**Comment by fokkog** [comment]
Thanks, this solution works well enough from my perspective. The object now captures all form elements in a multi-level hierarchy, and the "dirty checking" is fixed.

Having said that, if the intent is to create a clean JSON structure:
- repeating form sections (having elements with '[...]' in their names) should be serialized into arrays
- form elements whose names end in 'Index' can be excluded from serialization (e.g. see 'Non-Sequential Indices' section of http://haacked.com/archive/2008/10/23/model-binding-to-a-list.aspx/)
