### ISSUE TITLE
Blazor: override Razor component

### ISSUE THREAD

**Issue by ArneCools** [abpframework/abp#11654]
* Your **ABP Framework version**. **5.0.0**
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI **Blazor Server**

The documention explains that you can override Blazor components from the basic theme to customize. This works, however I'm forced to also override the Code Behind File since certain properties are private on the component in the basic theme.

In this example I'm trying to override the MainLayout component:

![image](https://user-images.githubusercontent.com/1440244/155013843-7f7f1b36-fbe4-4c0f-a6fc-a345d5de1eb9.png)

In the source code I can see certain methods are private, shouldn't they be protected or public? 
https://github.com/abpframework/abp/blob/dev/modules/basic-theme/src/Volo.Abp.AspNetCore.Components.Web.BasicTheme/Themes/Basic/MainLayout.razor.cs

Best regards
Arne

**Comment by maliming** [comment]
hi

You can send a PR to make them protected or public.

**Comment by ArneCools** [comment]
Ok, will do that. To and from which branch do I need to make one? dev -> 5.1-patch? rel-5.1 -> 5.1-patch?

**Comment by maliming** [comment]
`dev `
