### ISSUE TITLE
How to extend the fields of an organizationunit entity

### ISSUE THREAD

**Issue by lifeXHY** [abpframework/abp#11678]
- ABP Version:  5.1.3

- I want to expand some business fields based on **OrganizationUnit**  Entities, but the interface **IIdentityDbContext** in the **DbContext** of the new version of ABP framework prevents me.
- Is there a best practice for my needs.
- Tips: I have used the **Extra Properties** to realize this requirement, but I prefer to **Creating a New Entity Maps to the Same Database Table/Collection**

**Comment by maliming** [comment]
You can add the Identity module source code to your solution.
