### ISSUE TITLE
How to send mail with MailKit?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11680]
* Your **ABP Framework version**. **5.1.2**
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: **Blazor Server**

We are trying to implement MailKit in ABP, using the information displayed here:

- https://docs.abp.io/en/abp/latest/MailKit
- https://docs.abp.io/en/abp/latest/Emailing

But we are unsure how to actually send the emails? 

the _emailSender.SendAsync method seems to only accept MailMessage in it's constructor, but MailKit uses MimeMessage and we have not been able to find a cast from MimeMessage to MailMessage (but there is supposed to be one the other way).

If we instead try to inject IMailKitSmtpEmailSender to use 

`_mailKitSmtpEmailSender.BuildClientAsync();`

It seems that for an unknown reason, the constructor to that class will no longer run, with no errors in the ABP logfile. Remove that service from being injected, and the constructor will work fine again. 

We are quite confused about this. Any ideas?

(Please note that this isn't about NullEmailSender being used instead of actual emails when in debug mode. Or at least not the "Where are my emails?" typical question :) )

**Comment by berkansasmaz** [comment]
Can you check the sample code [here](https://github.com/abpframework/abp-samples/blob/master/EmailSendDemo/src/EmailSendDemo/AbpEmailingServices/MailKitSmtpEmailSender.cs)?

If the sample is not sufficient, please let us know.

**Comment by davidzwa** [comment]
Also note that with `services.AddSingleton<ISmtpClient, SmtpClient>();` you dont have to construct a client each time.
I didnt follow the example and directly constructed IMimeMessage to send with the SmtpClient from MailKit. This ended up in the same code as linked above.

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Comment by improwise** [comment]
Sorry for the delay in answering this. As the SmtpClient had what we needed, we decided to go with the default ABP implementation for the time being, so we have not yet tried the suggested solution. Thanks for all input and suggestions though, will check it out soon.
