### ISSUE TITLE
[mvc]dynamic remove meta tags

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#11696]
Example:
remove `<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">` in application layout.

Add Meta Hook?

**Comment by realLiangshiwei** [comment]
[`LayoutHooks.Head.First`](https://github.com/abpframework/abp/blob/dev/modules/basic-theme/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Application.cshtml#L36) should be working for you.

**Comment by snowchenlei** [comment]
> [`LayoutHooks.Head.First`](https://github.com/abpframework/abp/blob/dev/modules/basic-theme/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Application.cshtml#L36) should be working for you.

sorry, this cannot be achieved!
meta is hardcoded.
look [source](https://github.com/abpframework/abp/blob/fb62cddfa63ae9f3c91dff32d27409317a5c7a7f/modules/basic-theme/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Application.cshtml#L39)

**Comment by realLiangshiwei** [comment]
Hi,

This is not a common scenario, you can replace the layout page.

**Comment by snowchenlei** [comment]
yes.
Thanks!
