### ISSUE TITLE
Strange behavior about request size limit in Abp web api

### ISSUE THREAD

**Issue by GSSBilly** [abpframework/abp#11702]
Please help

* ABP Framework version: abp.io v4.3.0
* Framework version: .Net 5

already post a question on stackoverflow
https://stackoverflow.com/questions/71256014/strange-behavior-about-request-size-limit-in-abp-web-api

thanks

**Comment by maliming** [comment]
Move to https://stackoverflow.com/questions/71256014/strange-behavior-about-request-size-limit-in-abp-web-api

**Comment by GSSBilly** [comment]
hi @maliming 
i have made a reply on this issue
any good idea?
