### ISSUE TITLE
Integration Events fires before UOW commits

### ISSUE THREAD

**Issue by alicihad** [abpframework/abp#11704]
Hello,

I had a question about the unit of work process. If the Commit process fails after the integration event is fired, wouldn't we throw the event unnecessarily? My second question is should we call the SaveChangesAsync method once after domain events and also I couldn't understand why it is in a while statement. 

Link : https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWork.cs  

![image](https://user-images.githubusercontent.com/45819749/155674579-72b36809-9233-4a2f-82b8-53aa968b94d4.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/10008

**Comment by alicihad** [comment]
Hi,
But we don't want to continue to the transaction if any error occurs on db side. I'm sure Outbox pattern is used for securing events. But in case of any error during commit, should we still continue to the transaction?


And also in Eshop On Containers integration events fire after committing.

![image](https://user-images.githubusercontent.com/45819749/156119885-84e5ba66-1f1f-4bf0-a46a-acd5fa546a1f.png)
