### ISSUE TITLE
MVC datatables searching/filtering broken in v5.x

### ISSUE THREAD

**Issue by fokkog** [abpframework/abp#11715]
* **ABP Framework version**: 5.1.3
* **User Interface**: MVC UI with Razor Pages
* **Database provider**: EF Core (not that it matters)
* **Exception message/stack trace**: not applicable
* **Steps to reproduce**: see below

After a trial upgrade from ABP Framework 4.4.4 to 5.1.3, all datatables search boxes stop working. Any values entered are no longer appended to the Ajax request URL (as query string parameter 'filter'). Debugging shows it's caused by this code snippet in datatables-extensions.js:
```
//Text filter
if(settings.oInit.searching){
    if (requestData.search && requestData.search.value !== "") {
        input.filter = requestData.search.value;
    } else {
        input.filter = null;
    }
}
```

The condition `settings.oInit.searching` evaluates to undefined, hence false. Maybe (not sure) `settings.oInit.oFeatures.bFilter` is intended? See also #10798 and #11568.

**Comment by maliming** [comment]
hi

Please provide a demo project to reproduce this.

**Comment by fokkog** [comment]
https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore

**Comment by maliming** [comment]
Please upgrade to latest and re-install libs.

https://github.com/abpframework/abp-samples/blob/master/BookStore-Mvc-EfCore/src/Acme.BookStore.Web/package.json#L6

**Comment by fokkog** [comment]
Is the datatables search working for you in this sample project?

**Comment by EngincanV** [comment]
Hi @fokkog, I'll try and write back asap.

**Comment by EngincanV** [comment]
> Is the datatables search working for you in this sample project?

![filter](https://user-images.githubusercontent.com/43685404/155978299-2cfdda09-dc8e-4cd0-b801-8623079b6a94.gif)

I've tried just before and it works as expected. Please ensure you've set `serverSide` option as **false** and `searching` option as **true** if you want to filter on the client-side.

> Client-side processing - where filtering, paging and sorting calculations are all performed in the web-browser. (serverSide = false) https://datatables.net/reference/option/serverSide

If you want to filter on the server-side, you need to handle it yourself.

**Comment by fokkog** [comment]
Can you try the users/tenants search?

**Comment by EngincanV** [comment]
> Can you try the users/tenants search?

Thanks for reporting @fokkog, there is a problem indeed. I've created a separate issue (#11745 ) for that, thanks again.

**Comment by realLiangshiwei** [comment]
Move to https://github.com/abpframework/abp/issues/11715

**Comment by fokkog** [comment]
Thanks, that should fix it.

Let me add that this was the main regression we ran into during the 4.x to 5.x upgrade. Overall the upgrade was pretty smooth and it's already deployed to production.
