### ISSUE TITLE
new abp namespace brackets

### ISSUE THREAD

**Issue by Majed-404** [abpframework/abp#11719]
* latest
![Capture](https://user-images.githubusercontent.com/33943617/155849112-ff00712d-c043-447c-becd-2d3ef42b5565.PNG)

* MVC
* EF Core
* { expected

i just downloaded latest version and i found the project have many errors and not able to run without fixing them,
so the issues in each class namespace ends with ;

**Comment by berkansasmaz** [comment]
> I just want to put a huge caveat when using this feature. For a couple of months now, I tried this feature out in every .NET 6 preview SDK release. And each time I couldn’t get it to work, but I kept seeing people talk about it.
>
> As it turns out, for whatever reason, I could not get this feature to work in Visual Studio 2019 (And actually, [Minimal APIs in .NET 6](https://dotnetcoretutorials.com/2021/07/16/building-minimal-apis-in-net-6/) had similar issues), but it worked first try in Visual Studio 2022. So if you are getting errors such as :
>
> { expected
>
> Then you probably need to try it inside Visual Studio 2022.

https://dotnetcoretutorials.com/2021/09/20/file-scoped-namespaces-in-c-10/
