### ISSUE TITLE
API Result can  ignore Null properties as set  by  the [JsonProperty(NullValueHandling = NullValueHandling.Ignore)] attribue?

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#11716]
Dto:
```
 public class VueRouterMetaDto
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int? OrderNo { get; set; }
        public string Title { get; set; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int? DynamicLevel { get; set; }
  ....
  }

```

WHEN:
```
new VueRouterMetaDto(){
   OrderNo =1,
   Title="Dashboard"
}

```
expectations:
```
{
                "orderNo": 0,
                "title": "仪表盘",
}
```
and not:
```
{
                "orderNo": 0,
                "title": "仪表盘",
                "dynamicLevel": null
}
```

**Comment by berkansasmaz** [comment]
> ABP Framework uses the `System.Text.Json` by default as the JSON serialization library. It, actually, using a hybrid approach: Continues to use the `Newtonsoft.Json` when it needs to use features not supported by the `System.Text.Json`. https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#moved-to-system-text-json

So, maybe you can solve your problem using [`JsonIgnore` ](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-ignore-properties?pivots=dotnet-6-0#ignore-individual-properties) attribute from `System.Text.Json`.

`[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]`

Or [always use the `Newtonsoft.Json`](https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#always-use-the-newtonsoft-json)

```csharp
PreConfigure<AbpJsonOptions>(options =>
{
    options.UseHybridSerializer = false;
});
```

**Comment by hexianggui** [comment]
> > ABP 框架`System.Text.Json`默认使用 JSON 序列化库。实际上，它使用了一种混合方法：`Newtonsoft.Json`在需要使用`System.Text.Json`. https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#moved-to-system-text-json
> 
> [`JsonIgnore` ](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-ignore-properties?pivots=dotnet-6-0#ignore-individual-properties)所以，也许你可以使用属性来解决你的问题`System.Text.Json`。
> 
> `[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]`
> 
> 或者[总是使用`Newtonsoft.Json`](https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#always-use-the-newtonsoft-json)
> 
> ```cs
> PreConfigure < AbpJsonOptions >(选项 =>
> {
>     选项。UseHybridSerializer  =  false ;
> });
> ```
You are right。
Thank you very much！

**Comment by hexianggui** [comment]
> > ABP Framework uses the `System.Text.Json` by default as the JSON serialization library. It, actually, using a hybrid approach: Continues to use the `Newtonsoft.Json` when it needs to use features not supported by the `System.Text.Json`. https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#moved-to-system-text-json
> 
> So, maybe you can solve your problem using [`JsonIgnore` ](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-ignore-properties?pivots=dotnet-6-0#ignore-individual-properties) attribute from `System.Text.Json`.
> 
> `[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]`
> 
> Or [always use the `Newtonsoft.Json`](https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#always-use-the-newtonsoft-json)
> 
> ```cs
> PreConfigure<AbpJsonOptions>(options =>
> {
>     options.UseHybridSerializer = false;
> });
> ```

You are right。
Thank you very much！
