### ISSUE TITLE
CMS kit /Cms/BlogPosts/Create's throw a exception "editor.getHtml is not a function" when do anything in tui editor

### ISSUE THREAD

**Issue by wallee85** [abpframework/abp#11723]
module name:CMS kit
ABP Framework version:5.1.3
user interface : razor
exception message: js:editor.getHtml is not a function.

it's about tui-editor.

The tui editor has a method named "getHTML". but volo.cmskit.admin.web project's  /pages/cmskit/blogposts/create.js  misspelled "getHTML" as "getHtml"。that cause a error "getHtml is not a function"

**Comment by enisn** [comment]
I couldn't reproduce the problem, Maybe you're using a different version on your local, can you try to execute `abp install-libs` command under your **Web** project and re-run again?
