### ISSUE TITLE
What about create a slackware channel for a real time communication among abp developers?

### ISSUE THREAD

**Issue by rodrigomarcell** [abpframework/abp#11724]
Wouldn't be cool if we have a real time communication channel for the dev community so, issues resolutions, doubts and discussions, etc would have progress way faster? I suggest slackware. What about it?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/5935#issuecomment-723124761

**Comment by rodrigomarcell** [comment]
but  nothing like instant messaging then?
