### ISSUE TITLE
How to localize password validation description ?

### ISSUE THREAD

**Issue by begandroide** [abpframework/abp#11729]
Hi! I'm facing some issues with password validation translate with abpLocalization pipe. 

Happens that the password message error of validation is not being translated and I can't figure out how to make the translation (since the params change, because: number, special character, etc)

By the moments i figure out using all tags possibles (like in attached image), but I found that is not a pretty way. How I can do it in a faster way?

<img width="1535" alt="Captura de Pantalla 2022-02-27 a la(s) 20 52 20" src="https://user-images.githubusercontent.com/22018004/155905590-c62cb4fa-3700-42c8-b404-080907b12b45.png">

### Stack

* **ABP Framework version**.: 5.1
* **Angular 12** 
* EF Core

### Steps to repro

1. Change lang from "en" to "es" (or another).
2. In Angular UI go to user administration in default theme.
3. Open de modal to create a new user.
4. Add any character to password field. 
5. You can see that error is not localized.

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/Localization/es.json#L52

**Comment by begandroide** [comment]
thanks for you response @maliming .

But how I can map multiple args for the blueprints? happens that `ngx-validate` for password rules validation has two properties:
```ts
interface passwordRulesValidation {
 description: string;
 args: string[];
}
```

where `description` is any case described in the issue screenshot and args is any rule that is not valid. 

So I had modified blueprint: `invalidPassword: '::Password should include {{ description }}.',`. but there are many cases that is easy lost one.

So, how I can map these errors fine? 

pd: actual localization is working fine but I'm looking for a change there

**Comment by maliming** [comment]
Sorry, I'm not familiar with Angular. 

@bnymncoskuner Do you have any idea?
