### ISSUE TITLE
Optional PWA support on new solutions with Blazor WASM

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#11741]
Add an option to `abp new` command: `--pwa` and create the solution as PWA enabled.

- [x] Blazor WASM ( https://github.com/abpframework/abp/pull/12179 )
- [x] ABP CLI changes ( https://github.com/abpframework/abp/pull/12179 )

**Comment by enisn** [comment]
I'm not sure Angular caching. In Microsoft's blazor pwa template, microsoft generate `service-worker-assets.js` automatically, and that file contains all required assets to be cached.

We need to find out what we can cache?
