### ISSUE TITLE
Updated version of "How to Customize the SignIn Manager for ABP Applications"?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#11746]
Is there an updated version of this document/page, "How to Customize the SignIn Manager for ABP Applications"?

https://docs.abp.io/en/abp/2.8/How-To/Customize-SignIn-Manager

**Comment by EngincanV** [comment]
Hi, We've moved the "how-to" guides to community.abp.io. You can see the related Community Post from [here](https://community.abp.io/posts/how-to-customize-the-signin-manager-3e858753).

> Content of the documentation in v2.8 same as the Community Post. So you can read either one of them.
