### ISSUE TITLE
DevExtreme (DevExpress) - localization for Components and Reporting

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#11750]
Hello,

Please, add code how to "connect" abp localization with DevExpress localization - so if user changes language in abp (dropdown), that corresponding language resource file for DevExpress is also taken.
Using Intl is preferred (for components): https://docs.devexpress.com/AspNetCore/400577/devextreme-based-controls/concepts/localization#intl

What do you think @gterdem and @cotur?

Components: https://community.abp.io/posts/using-devextreme-components-with-the-abp-framework-zb8z7yqv
Reporting: https://community.abp.io/posts/integrating-devexpress-reporting-to-abp-mvc-application-0t99j3cz

**Comment by maliming** [comment]
You can set the language of `DevExpress` according to the culture of the current page.

**Comment by leonkosak** [comment]
@maliming, wouldn't be better to solve (set language) system-wide and not on each .cshtml file separately?

**Comment by maliming** [comment]
Yes, it's better to set it in the layout page, it's just a solution.

**Comment by leonkosak** [comment]
Well, the problem is that I tried to add code in _ViewImports.cshtml and it works only in development mode. When I make a release and deploy, DX components stays in English when language is changed.

**Comment by maliming** [comment]
Can you share your code?

**Comment by leonkosak** [comment]
Sorry for activating this theme again.
I still haven't found where to put the following code in abp MVC project GLOBALLY in javascript:

`DevExpress.localization.locale(abp.localization.currentCulture.twoLetterIsoLanguageName);`

Currently, each .cshtml page has this line of code (which is not ideal - but at least works that DevExtreme components have the same language as abp application).
Thank you.
