### ISSUE TITLE
AbpDbContext filter expression optimization

### ISSUE THREAD

**Issue by ahmetfarukulu** [abpframework/abp#11751]
Hi, 

When we set `DataFilter.Disable<ISoftDelete>()` [AbpDbContext](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs) filter query create (@__ef_filter__p_0)1 = 1 or [a1].[IsDeleted] = CAST(0 AS bit) but we don't need this clause we already want to get all records. Can we change this condition like [Mongo data filter ](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.MongoDB/Volo/Abp/Domain/Repositories/MongoDB/MongoDbRepositoryFilterer.cs)

- Check entity assignable from ISoftDelete **and IsSoftDeleteFilterEnabled == true**
```csharp
    protected virtual Expression<Func<TEntity, bool>> CreateFilterExpression<TEntity>()
        where TEntity : class
    {
        Expression<Func<TEntity, bool>> expression = null;

        if (typeof(ISoftDelete).IsAssignableFrom(typeof(TEntity)) && IsSoftDeleteFilterEnabled)
        {
            expression = e => !EF.Property<bool>(e, "IsDeleted");
        }

        if (typeof(IMultiTenant).IsAssignableFrom(typeof(TEntity)) && IsMultiTenantFilterEnabled)
        {
            Expression<Func<TEntity, bool>> multiTenantFilter = e =>  EF.Property<Guid>(e, "TenantId") == CurrentTenantId;
            expression = expression == null ? multiTenantFilter : CombineExpressions(expression, multiTenantFilter);
        }

        return expression;
    }
```

**Comment by berkansasmaz** [comment]
Thanks for the report @ahmetfarukulu 🎉

We will fix this issue as soon as possible.

**Comment by berkansasmaz** [comment]
After a little research, we found that `CreateFilterExpression` is already running once, so `IsSoftDeleteFilterEnabled` must be in the expression.
As a result, we think the current code is fine and doesn't need to be optimized.

<hr>

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
