### ISSUE TITLE
The Page of "https://docs.abp.io/zh-Hans/abp/latest/Tutorials/Part-2" is Not found

### ISSUE THREAD

**Issue by Cyril-hcj** [abpframework/abp#11754]
![image](https://user-images.githubusercontent.com/31679398/156175221-981d6b5f-d8da-45ed-bd30-2252c466bf66.png)
> https://docs.abp.io/zh-Hans/abp/latest/Tutorials/Part-2

**Comment by EngincanV** [comment]
Thanks for reporting, we'll fix the problem. In meantime, you can read the article from [here](https://docs.abp.io/zh-Hans/abp/5.0/Tutorials/Part-2?UI=MVC&DB=EF).

**Comment by EngincanV** [comment]
It's working right now, thanks again for reporting.

![image](https://user-images.githubusercontent.com/43685404/156230352-6bc814a0-de89-4a88-9994-06b5d607e7fe.png)

> https://docs.abp.io/zh-Hans/abp/latest/Tutorials/Part-2?UI=MVC&DB=EF
