### ISSUE TITLE
Returns meaningless value in permission setting on User management page in ABP Free Templates

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#11772]
### App: Angular UI (MongoDB), Blazor-Server (EF Core), Blazor-WASM (PostgreSQL), Modules (Blazor-Server,Blazor-WASM,Angular)

**Problem Definition:** Returns meaningless value in permission setting on User management page in ABP Free Templates.

![image](https://user-images.githubusercontent.com/99716457/156348557-80140077-3fbf-4a89-925e-7ac0805b6fff.png)

**Comment by maliming** [comment]
Actually, we are setting the value for the **user id**. But I think we can use the **user name(user id)** to display.

**Comment by hikalkan** [comment]
@maliming can you take the main responsibility of this work?

**Comment by gizemmutukurt** [comment]
The same problem exists in pro templates.

**App Pro:** Angular UI (MongoDB), Blazor-Server (EF Core), Blazor-WASM (PostgreSQL), Modules (Blazor-Server,Blazor-WASM,Angular)

![image](https://user-images.githubusercontent.com/99716457/157620704-4d3a81cc-061e-48b4-b774-7788ded095ae.png)
