### ISSUE TITLE
Why define ConnectionStringName as a constant? 

### ISSUE THREAD

**Issue by shuangbaojun** [abpframework/abp#11774]
Why define ConnectionStringName as a constant? Sometimes you need to customize this name, as shown in the following figure:

![image](https://user-images.githubusercontent.com/64063254/156364807-640374bb-a7f7-4808-a8e9-1816e0dd9372.png)

**Comment by JadynWong** [comment]
https://github.com/abpframework/abp/blob/c0a26e70c6dbbcc5ab074097f9eb255c658bcc77/modules/audit-logging/src/Volo.Abp.AuditLogging.EntityFrameworkCore/Volo/Abp/AuditLogging/EntityFrameworkCore/AbpAuditLoggingDbContext.cs#L7

`attribute` need constant value.

**Comment by berkansasmaz** [comment]
I think you can do what you want by following [this document](https://docs.abp.io/en/abp/latest/Connection-Strings#configuring-the-database-structures).

For instance:

```csharp
Configure<AbpDbConnectionOptions>(options =>
{
    options.Databases.Configure("MyCustomIdentityServerDb", db =>
    {
        db.MappedConnections.Add("AbpIdentityServer");
    });
});
```
