### ISSUE TITLE
ABP Free Templates - Tenant user is unable to view the Settings tab.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#11775]
**App:** ABP Free Templates

**Problem Definition:** "Allow tenants to change email settings." when the feature is not checked, the Tenant user does not display the Settings tab.
![0fb765f4-5320-447d-a268-971d8ac7d003](https://user-images.githubusercontent.com/99716457/156365652-bc885288-a89e-4d07-9661-f0831430330a.gif)

**Comment by realLiangshiwei** [comment]
This is by design: https://github.com/abpframework/abp/issues/958
