### ISSUE TITLE
App: MVC (EF Core) - "Search" field not working

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#11784]
**App:** MVC (EF Core)

**Problem Definition:** Search field does not work on User management page.

### ScreenShot:
![9738ff2d-baab-41e7-b6c2-fa6172fc0f8a](https://user-images.githubusercontent.com/99716457/156502304-e0cc6722-3daf-4fd8-ba08-3384996699e7.gif)

**Comment by realLiangshiwei** [comment]
Fixed by https://github.com/abpframework/abp/pull/11747
