### ISSUE TITLE
Audited attribute on GET request does not work when auditing is not enabled for all GET requests

### ISSUE THREAD

**Issue by koapeadu** [abpframework/abp#11794]
When ` IsEnabledForGetRequests` in the audit options is `false` and there is an action method with the `[Audited]` attribute on it, we expect it to be logged to the audit log store.

However, it does not log the action to the audit log store. Turning on ` IsEnabledForGetRequests` is not a viable solution for us since we are only interested in logging specific GET requests.

I don't know which of these 2 snippets are responsible but I think it would be useful to add a check to determine if the method does not have the `[Audited]` attribute on it. This way, specific GET requests with the `[Audited]` attribute will be logged to the audit log even when ` IsEnabledForGetRequests` is false.

https://github.com/abpframework/abp/blob/84bf31b68fa01a013d0b6d9f0bd4d03b705a88e8/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAuditingMiddleware.cs#L113-L117
https://github.com/abpframework/abp/blob/3266d15c1e517a5c5ae920ccfc4662312ed52901/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingInterceptor.cs#L172-L176

**Comment by maliming** [comment]
I agree with you, I will check out.

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/pull/11797

**Comment by koapeadu** [comment]
I'd like to leverage the `[Audited]` attribute.  I don't know if #11797 can handle that.

But can this check for example be changed from
https://github.com/abpframework/abp/blob/3266d15c1e517a5c5ae920ccfc4662312ed52901/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingInterceptor.cs#L172-L176
to something like this?
```csharp
if (!options.IsEnabledForGetRequests && 
    !invocation.Method.GetCustomAttributes(typeof(AuditedAttribute), false).Any() &&
     invocation.Method.Name.StartsWith("Get", StringComparison.OrdinalIgnoreCase)) 
 { 
     return false; 
 } 
```
And can the same be applied to the the following as well?
I think that will keep it simple.
https://github.com/abpframework/abp/blob/84bf31b68fa01a013d0b6d9f0bd4d03b705a88e8/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAuditingMiddleware.cs#L113-L117

**Comment by maliming** [comment]
We can only get info about methods and parameters in interceptors.
