### ISSUE TITLE
On the permission page, "An internal error occurred during your request!" error message is received.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#11802]
**Module:** Blazor-Server
**Version:** `5.1.4`

**Problem Definition:** Getting an error while opening the permission page. Error message: An internal error occurred during your request!

### **ScreenShot:**

![f24d0cae-dfe9-4af2-b9c7-db658524d782](https://user-images.githubusercontent.com/99716457/156705033-4ee73cd2-7012-464e-a5b3-9306a5bfcbc1.gif)

**Comment by maliming** [comment]
hi @gizemmutukurt 

> Error message: An internal error occurred during your request!

Can you share the error logs?
