### ISSUE TITLE
Unable to find obj variable when uglify `serializeFormToObject`

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#11809]
https://github.com/abpframework/abp/blob/441d17567fad8b94665c8897361995400f861d3b/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery/jquery-extensions.js#L121

https://github.com/abpframework/abp/blob/441d17567fad8b94665c8897361995400f861d3b/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery/jquery-extensions.js#L144

After the `obj` variable is uglified, it is converted to a single digit variable name such as `r`.
However, `obj` between quotation marks is not translated and remains as `obj`.
As a result, we get the error `obj is not defined` in the production environment.

You can test it [here](https://dotnetfiddle.net/m99aSQ)

Related PR: https://github.com/abpframework/abp/pull/11659

Also, I guess `eval` is not a recommended method. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval?retiredLocale=tr#never_use_eval!

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/11811
