### ISSUE TITLE
Update to blazorise 1.0.0

### ISSUE THREAD

**Issue by nebula2** [abpframework/abp#11810]
I know it's just came out today - but I just found out that blazorise released v1.0.0 which comes with a ton of stuff:

https://blazorise.com/news/release-notes/100

I just wanted to implement drag & drop for a project and was wondering why I it's not usable - until I found out that it was just released a few hours ago 🤣 - that's how I found out.

Thought I just raise an issue for upgrading.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/11649
