### ISSUE TITLE
GetAsyc(id,true) no detail ,,     but   include(c=>c.list)  have detail

### ISSUE THREAD

**Issue by zengnanhua** [abpframework/abp#11825]
![image](https://user-images.githubusercontent.com/22017107/157045971-7e62a280-3698-44bf-921f-7859afe0afd6.png)

**Comment by EngincanV** [comment]
You need to override the `WithDetailsAsync` method as follows:

```csharp
public override Task<IQueryable<Desk>> WithDetailsAsync()
{
   return base.WithDetailsAsync(x => x.PersonTotalScores);
}
```

Then when you set `includeDetails` parameter as **true** all your related repository methods will include this entity.

> You can read the ["Loading Related Entities"](https://docs.abp.io/en/abp/latest/Entity-Framework-Core#loading-related-entities) section for details.
