### ISSUE TITLE
Fix broken links on docs.abp.io

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#11827]
![image](https://user-images.githubusercontent.com/9526587/157064071-9b25b922-a6b0-464a-95fe-78c5b4ab2872.png)

	
404 Not found	
https://docs.nativebase.io/Customize.html<a href>Outbound
Linked from: https://docs.abp.io/en/abp/latest/Startup-Templates/Application
	
Host not found	
https://https//www.hangfire.io/<a href>Outbound
Linked from: https://docs.abp.io/en/abp/latest/Background-Workers-Hangfire
	
404 Not found	
https://docs.abp.io/en/abp/latest/API/CLI<a href>
Linked from: https://docs.abp.io/en/abp/latest/API/Swagger-Integration
	
404 Not found	
https://docs.abp.io/en/abp/latest/API/Modules/IdentityServer<a href>
Linked from: https://docs.abp.io/en/abp/latest/API/Swagger-Integration
	
404 Not found	
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/models/config.ts<a href>Outbound
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Environment
	
404 Not found	
https://github.com/testing-library/angular-testing-library/tree/master/apps/example-app/app/examples<a href>OutboundRedirected
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Testing
	
404 Not found	
https://github.com/vercel/ng-deploy-vercel<a href>Outbound
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Quick-Start
	
404 Not found	
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/models/application-configuration.ts<a href>Outbound
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Config-State-Service

**Comment by braim23** [comment]
1. 404 Not found
https://docs.nativebase.io/Customize.htmlOutbound
Linked from: https://docs.abp.io/en/abp/latest/Startup-Templates/Application
FIXED: https://docs.nativebase.io/3.1.x/customizing-components

2. Host not found
https://https//www.hangfire.io/Outbound
Linked from: https://docs.abp.io/en/abp/latest/Background-Workers-Hangfire
FIXED: https://www.hangfire.io/

3. 404 Not found
https://docs.abp.io/en/abp/latest/API/CLI
[Linked from: ](https://github.com/abpframework/abp/issues/11827)https://docs.abp.io/en/abp/latest/API/Swagger-Integration
FIXED: https://docs.abp.io/en/abp/latest/CLI

4. 404 Not found
https://docs.abp.io/en/abp/latest/API/Modules/IdentityServer
[Linked from: ](https://github.com/abpframework/abp/issues/11827)https://docs.abp.io/en/abp/latest/API/Swagger-Integration
FIXED: https://docs.abp.io/en/abp/latest/Modules/IdentityServer

5. 404 Not found
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/models/config.tsOutbound
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Environment
 NOT FIXED: Waiting for Muhammed to answer

6. 404 Not found
https://github.com/testing-library/angular-testing-library/tree/master/apps/example-app/app/examplesOutboundRedirected
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Testing
ALMOST FIXED: I found this link it should cover it but I'm waiting for the confirmation of the only contributor I found in the page: Halil abi
https://github.com/testing-library/angular-testing-library/tree/main/apps/example-app/src/app/examples

7. 404 Not found
https://github.com/vercel/ng-deploy-vercelOutbound
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Quick-Start
NOT FIXED: Found the GitHub page of Vercel but there is no sign of Angular... only found the website, can I use this link instead? https://vercel.com/solutions/angular

8. 404 Not found
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/models/application-configuration.tsOutbound
Linked from: https://docs.abp.io/en/abp/latest/UI/Angular/Config-State-Service
NOT FIXED: asked Muhammed about the missing ts file.

**Comment by braim23** [comment]
https://github.com/abpframework/abp/pull/11850 Fixed the first 4 and left Angular

**Comment by hikalkan** [comment]
I suppose we can close this.
