### ISSUE TITLE
Azure Databricks integration with EF Core

### ISSUE THREAD

**Issue by TronActive** [abpframework/abp#11826]
I would like to post a feature request for entity framework core integration with Azure Databricks. Not as a complete replacement of SQL or MongoDB. More to work alongside it for analytics and machine learning. It's performance is around 10X faster than doing analytics with SQL Server.

Azure Databricks is mostly for analytics and machine learning. It does integrate with SQL. It provides an end-to-end solution for all types of data, analytics and build artificial intelligence (AI).

For my immediate need, I am going to use these three articles to come up with a solution for myself. 
https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/jdbc-odbc-bi
https://www.cdata.com/kb/tech/spark-ado-codefirst.rst
https://www.c-sharpcorner.com/article/azure-databricks/

**Comment by enisn** [comment]
You can use any provider that implemented Entity Framework Core

See list below: https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli

Even we don't have an official package, you can configure any Entity Framework Core provider for your DbContext.

---

But as I see there is no Entity Framework implementation for Databricks.

We develop a framework, database providers are not in our profession, so we don't implement an entity framework provider. If it's already implemented, you can use it. It's related to Entity Framework, not related to ABP.

**Comment by enisn** [comment]
https://stackoverflow.com/questions/67426831/connect-ef-core-to-azure-databricks

You have to use Drivers, there is no EF support.

If you want to use it for our existing modules, you have to implement repositories. Existing modules already inject repositories.
