### ISSUE TITLE
Documentation not clear. Do I have to create separate projects to correctly register multiple Dynamic C# API Clients?

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#11824]
* ABP Framework version: 4.4
* Database provider: EF Core

Hi,

I have read [the documentation on Dynamic C# API Client Proxies](https://docs.abp.io/en/abp/4.4/API/Dynamic-CSharp-API-Clients) on the ABP.

**What isn't clear is how `context.Services.AddHttpClientProxies` will look like  if you want to consume more than one service,** **Does it mean we create multiple HttpClient projects?**

It does mention that you can have [Multiple Remote Service Endpoints](https://docs.abp.io/en/abp/4.4/API/Dynamic-CSharp-API-Clients#multiple-remote-service-endpoints)

It shows the `appsettings.json` example as below:

```json
{
  "RemoteServices": {
    "Default": {
      "BaseUrl": "http://localhost:53929/"
    },
    "BookStore": {
      "BaseUrl": "http://localhost:48392/"
    } 
  } 
}
```
It doesn't show how that will look like in the ConfigureServices call with multiple remote services. It only shows configuration of one remote service as below:

```
context.Services.AddHttpClientProxies(
    typeof(BookStoreApplicationContractsModule).Assembly,
    remoteServiceConfigurationName: "BookStore"
);
```

1. **What happens to "Default" in this case? Is it ignored?** 
2. **How does it look like when I add a third/fourth or more services?**
3. **Does it mean for every client, I will have to create an HttpClient project with it's own module, set up etc?**

It **would be nice if we can add multiple client proxies in a single** `AddHttpClientProxies` call in the same default `HttpClient` project generated by the client.

**Comment by enisn** [comment]
Hi @tinonetic ,

1. What happens to "Default" in this case? Is it ignored?
> If you don't set **remoteServiceConfigurationName**, it'll fallback to **Default** and use  `http://localhost:53929` in your case. Mostly you don't need to define each service name if they're provided by the same API.

2. How does it look like when I add a third/fourth or more services?
> If you need to send requests to different APIs, you should define each one of them. But if the base URL of services are the same, you don't have to define each one of them, they'll fallback to **Default**.
 
3. Does it mean for every client, I will have to create an HttpClient project with its own module, set up, etc?
> As a best practice, you should do. So you can separate your modules easily or extract one of your modules as a micro-service. It's strongly recommended to create HttpApi.Client project. Also, it's not hard to maintain those projects.

**Comment by enisn** [comment]
As an addition:

```csharp
context.Services.AddHttpClientProxies(
    typeof(BookStoreApplicationContractsModule).Assembly,
    remoteServiceConfigurationName: "BookStore"
);
```
You should always set **remoteServiceConfigurationName** in here, but in the appsettings.json, no need to create another section for **BookStore**, it'll use Default if you don't define in appsettings.json

**Comment by tinonetic** [comment]
Thanks @enisn 

You've answered one part by recommending the creation of separate HttpClient project.

My scenario is actually **for projects in different solutions,**.  Will it still work and dynamically generate a client? Or it only works where the projects are in the same solution?
