### ISSUE TITLE
Some enhancements for Blazor UI

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#11838]
Related: #11742

The suggestions [here](https://github.com/abpframework/abp/issues/11837) should be made.

Also, 

- [x] User page does not have "search" field.

![156501987-ab44544a-c653-4460-855b-6b42fcd4286f](https://user-images.githubusercontent.com/31216880/157187967-551d8004-c0c7-4908-bc10-52bf848d539c.png)

- [x] The same input fields must be qualified with the same label. This is important for consistency. Related QA questions: https://support.abp.io/QA/Questions/2482

<img width="1440" alt="Screen Shot 2022-03-08 at 13 43 28" src="https://user-images.githubusercontent.com/31216880/157223253-73f72d67-4e30-46d1-a2e7-ecf2dde25090.png">

- [x] Validation of password fields should be done on the client-side (without sending a request). Related QA Question: https://support.abp.io/QA/Questions/2486

**Comment by rqx110** [comment]
please also consider enhance the blazor ui experience different than others(mvc, angular). e.g. 
* The card header is so larger than others
* The table has black divider line
