### ISSUE TITLE
Some enhancements for MVC UI

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#11839]
Related: #11742

The suggestions [here](https://github.com/abpframework/abp/issues/11837) should be made.

Also, 

- [x] The same input fields must be qualified with the same label. This is important for consistency. Related QA questions: https://support.abp.io/QA/Questions/2482

![ff9c26d2a466c607d7f43a01a35bb2a7](https://user-images.githubusercontent.com/31216880/157220300-ccaee9e2-4db7-4891-a58d-a86a299727ff.png)

- [x] Validation of password fields should be done on the client-side (without sending a request). Related QA Question: https://support.abp.io/QA/Questions/2486

**Comment by EngincanV** [comment]
> * [x]  Validation of password fields should be done on the client-side (without sending a request). Related QA Question: https://support.abp.io/QA/Questions/2486

It's already done. (https://github.com/volosoft/volo/pull/8791)

![image](https://user-images.githubusercontent.com/43685404/160410056-89446552-73cc-4804-9497-875cc0f8bed8.png)
