### ISSUE TITLE
Document the distributed lock

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#11836]
The document should explain the following topics:

* What is distributed locking, why we may need it, in brief.
* ABP's distributed locking abstraction package and its usage.
* Explanation and usage of the current implementation (https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.DistributedLocking), how to use redis provider for this implementation, give link to its original documents for more

Note: This is a shipped feature, so document it in `rel-5.2` branch please.

**Comment by malikmasis** [comment]
@hikalkan made the last changes and completed it.
