### ISSUE TITLE
Blogging: `Continue reading` button appearance

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#11842]
moved from https://github.com/abpframework/abp/issues/11699

@gizemmutukurt says:

Detail can be written instead of continiue reading and button appearance can be beautified.
![image](https://user-images.githubusercontent.com/99716457/155674296-60d5c8ff-66ce-4be8-b322-5e3454870f87.png)

**Comment by melisplatin** [comment]
Design File: https://www.figma.com/file/1mXESoeknrrYhnhA4erXhe/New-ABP.io?node-id=3724%3A9037

![Framework - Blog](https://user-images.githubusercontent.com/79847445/179536567-9436a030-62bd-4ea0-88cd-1c1e6f9b4fe0.png)
