### ISSUE TITLE
How to correctly configure RouteTenantResolveContributor

### ISSUE THREAD

**Issue by sanghel-payoff** [abpframework/abp#11855]
ABP Commercial 5.1.2, UI Angular, EFCore Postgresql

**What configuration is required in order to correctly use the RouteTenantResolveContributor for all ApplicationService routes?**

#7624 was left unaswered

Following some hints on #8806, it seems that it might be possibile to configure a base route path for all actions in the _HttpApiHostModule_, something like:

```
private void ConfigureConventionalControllers()
    {
        Configure<AbpAspNetCoreMvcOptions>(options =>
        {
            // default template sources
            //  options.ConventionalControllers.Create(typeof(ApplicationModule).Assembly);

            // route root with tenant for RouteTenantResolveContributor 
            options.ConventionalControllers.Create(typeof(ApplicationModule).Assembly,  options => {  options.RootPath = "__tenant}/app"; });
        });
    }
```

Is this sufficient in order to configure the RouteTenantResolveContributor ?

Are modifications necessary on the frontent Angular code to allow client proxy generation to continue working correctly?

**Comment by sanghel-payoff** [comment]
bump ?

**Comment by sanghel-payoff** [comment]
bump?

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io/QA/Questions for ABP Commercial.
