### ISSUE TITLE
Write available commands on CLI help command

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1186]
For `abp help`, write a list of available commands.

**Comment by wayneboyles** [comment]
Would you be opposed to implementing an external library called Mono.Options?

https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mono.Options/GettingStarted.md

It works really well as a command line parser but also includes the ability to spit out the available options.

Just a thought as I used it recently.

**Comment by hikalkan** [comment]
Thanks @wayneboyles for sharing this. We already implemented the parsing & command matching stuff. If I knew that before, I might be using it :) However, we may check it for later versions.
