### ISSUE TITLE
Is there a spelling mistake in eShopOnAbp

### ISSUE THREAD

**Issue by hpstory** [abpframework/abp#11888]
In the [CatalogServiceMongoDbContext.cs](https://github.com/abpframework/eShopOnAbp/blob/main/services/catalog/src/EShopOnAbp.CatalogService.MongoDB/MongoDB/CatalogServiceMongoDbContext.cs)

Questions maybe it should be spelled as Products
`public IMongoCollection<Product> Questions => Collection<Product>();`

**Comment by enisn** [comment]
It should be `Products` instead of `Questions`
