### ISSUE TITLE
Dto with Required Attribute slow respond

### ISSUE THREAD

**Issue by ahmetfarukulu** [abpframework/abp#11887]
- ABP Framework version 5.1.4
- User Interface None
- Database provider EF Core (MsSQL)

I use abp template solution created this command `abp new Sample --ui none -csf`

### Problem

- I have two sample model only difference required attribute, when i request 100 list required one is returning very slow
- Same code with aspnetcore empty project, both response fast
```csharp
public class HomeController : AbpController
{
    public ActionResult Index()
    {
        return Redirect("~/swagger");
    }
    
    [HttpPost("create-samples")]
    public IActionResult CreateSamples([FromBody] List<SampleModel> sampleModels)
    {
        return Ok(sampleModels);
    }

    [HttpPost("create-samples-with-required")]
    public IActionResult CreateSamples([FromBody] List<SampleModelWithRequired> sampleModels)
    {
        return Ok(sampleModels);
    }
}

public class SampleModel
{
    public string Code { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public class SampleModelWithRequired
{
    [Required]
    public string Code { get; set; }
    [Required]
    public string Name { get; set; }
    [Required]
    public string Description { get; set; }
}
```
- Sample request (doesn't have required attribute)

![image](https://user-images.githubusercontent.com/35758317/157611759-ae1eb3e7-4787-4090-9518-dff705e463b6.png)
- Sample request (has required attribute)

![image](https://user-images.githubusercontent.com/35758317/157612018-21b13053-3f7b-4bc9-9333-b1eaae2b3815.png)

**Comment by ahmetfarukulu** [comment]
I've found problem reason is [AbpDataAnnotationAutoLocalizationMetadataDetailsProvider](https://github.com/abpframework/abp/blob/fe160bfb96bba5d5e36d059f76a7eb7857762e7b/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AbpDataAnnotationAutoLocalizationMetadataDetailsProvider.cs#L55) class but i don't have solution yet 😄

**Comment by maliming** [comment]
hi

I will check this.

**Comment by maliming** [comment]
Can you try this?

```cs
Configure<MvcOptions>(options =>
{
    options.ModelMetadataDetailsProviders.RemoveAll(x => x.GetType() == typeof(AbpDataAnnotationAutoLocalizationMetadataDetailsProvider));
});
```

**Comment by ahmetfarukulu** [comment]
It seems works but this time doesn't localize property i guess main problem `IDisplayMetadataProvider` way of working
- If model state is true why it run DisplayName func
- If list of same model type why it run DisplayName func many times, run for each request by type work too

**Comment by maliming** [comment]
> It seems works

Is the response time looks same?

**Comment by ahmetfarukulu** [comment]
Response time fixed

![image](https://user-images.githubusercontent.com/35758317/158111046-85332946-95aa-4bd0-a80d-d8d496fe9db8.png)
