### ISSUE TITLE
Updating existing IdentityUser triggers MaxUserCountValidator

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#11898]
ABP Framework version: 5.1.1
User Interface: Angular
database provider: EF Core

When using the IdentityUserController and MaxUserCount has been set, the tenant is at the maximum number of users. Updating the details of an existing user is not possible.

If there a way to bypass this quickly?

Thanks in advance :)

[INF] Route matched with {area = "identity", controller = "User", action = "Update", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Identity.IdentityUserDto] UpdateAsync(System.Guid, Volo.Abp.Identity.IdentityUserUpdateDto) on controller Volo.Abp.Identity.IdentityUserController (Volo.Abp.Identity.Pro.HttpApi).
[WRN] ---------- RemoteServiceErrorInfo ----------
Reached maximum allowed user count! This tenant is allowed to have a maximum of 3 users.
[WRN] Exception of type 'Volo.Abp.BusinessException' was thrown.
Volo.Abp.BusinessException: Exception of type 'Volo.Abp.BusinessException' was thrown.
   at Volo.Abp.Identity.MaxUserCountValidator.CheckMaxUserCountAsync()
   at Volo.Abp.Identity.MaxUserCountValidator.ValidateAsync(UserManager`1 manager, IdentityUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)

**Comment by maliming** [comment]
hi @lukebooroo 

Please get help on https://support.abp.io/

Thanks.

**Comment by lukebooroo** [comment]
Are you telling me that this is not a bug, and the intended behaviour?

**Comment by maliming** [comment]
hi

You are using the ABP commercial, we don't discuss it in this Github repo.

Please get help on https://support.abp.io/

**Comment by lukebooroo** [comment]
![image](https://user-images.githubusercontent.com/3911526/157839884-8b26d185-93c9-408a-849d-9b98aabd0465.png)

I'm getting this error on submit of a support request

**Comment by maliming** [comment]
What's your `username`?

**Comment by lukebooroo** [comment]
Username is: luke

**Comment by maliming** [comment]
> You are a member of an organization but no organization is selected for your question

**Comment by lukebooroo** [comment]
![image](https://user-images.githubusercontent.com/3911526/157887768-507d854a-af81-4382-a1c9-47ac52cc39c2.png)

There's no field to select the organization.

**Comment by maliming** [comment]
Can you try logging out and re-logging in?
