### ISSUE TITLE
Module For LDAP

### ISSUE THREAD

**Issue by akinix** [abpframework/abp#1189]
**Source** [Volo.Abp.Ldap](https://github.com/akinix/abp/tree/akinix/ldap/framework/src/Volo.Abp.Ldap)
**UnitTest** [Volo.Abp.Ldap.Tests](https://github.com/akinix/abp/tree/akinix/ldap/framework/test/Volo.Abp.Ldap.Tests)
Because the unit test requires  environment for AD. 
I have skipped all the tests when I submitted the code. 
I have passed all the tests in the local.
![image](https://user-images.githubusercontent.com/16933380/58702596-c1da6200-83d8-11e9-9e6f-94715c08adaa.png)

# Volo.Abp.Ldap

# Only Authenticate(not read/write AD)

## Configure

add section in `appsettings.json`

### use SSL

```json
"LDAP": {
    "ServerHost": "192.168.101.54", 
    "ServerPort": 636,
    "UseSSL": true
}
```

### not use SSL

```json
"LDAP": {
    "ServerHost": "192.168.101.54", 
    "ServerPort": 389,
    "UseSSL": false
}
```

## Authenticate

 Injecting `ILdapManager` into a class. For example:

```csharp
public class TaxAppService : ApplicationService
{
    private readonly ILdapManager _ldapManager;

    public TaxAppService(ILdapManager ldapManager)
    {
        _ldapManager = ldapManager;
    }

    public void Authenticate(string userName, string password)
    { 
        var result = _ldapManager.Authenticate(userName, password);
    }
}
```

- `userName` must be full domain name. E.g abc@abc.com 

# Read/Write AD

### use SSL

```json
"LDAP": {
    "ServerHost": "192.168.101.54",
    "ServerPort": 636,
    "UseSSL": true,
    "Credentials": {
        "DomainUserName": "administrator@yourdomain.com.cn",
        "Password": "yH.20190528"
    },
    "SearchBase": "DC=yourdomain,DC=com,DC=cn",
    "DomainName": "yourdomain.com.cn",
    "DomainDistinguishedName": "DC=yourdomain,DC=com,DC=cn"
}
```

### not use SSL

```json
"LDAP": {
    "ServerHost": "192.168.101.54",
    "ServerPort": 389,
    "UseSSL": false,
    "Credentials": {
        "DomainUserName": "administrator@yourdomain.com.cn",
        "Password": "yH.20190528"
    },
    "SearchBase": "DC=yourdomain,DC=com,DC=cn",
    "DomainName": "yourdomain.com.cn",
    "DomainDistinguishedName": "DC=yourdomain,DC=com,DC=cn"
}
```

- `Credentials:DomainUserName` a administrator of AD.

- `Credentials:Password` the password for the administrator.
- `SearchBase`:  where search from AD.
- `DomainName`: name of you domain. no need `www`.
- `DomainDistinguishedName`: distinguished name of root domain.

## Query Organizations

```cs
// query all organizations
// filter: (&(objectClass=organizationalUnit)) 
_ldapManager.GetOrganizations();

// query organizations by name
// filter: (&(name=abc)(objectClass=organizationalUnit))
_ldapManager.GetOrganizations("abc");

```

## Query Organization

```csharp
// query organization by distinguished name
// filter: (&(distinguishedName=abc)(objectClass=organizationalUnit))
_ldapManager.GetOrganization("abc");

```

## Add Organization

```csharp
// use LdapOrganization
_ldapManager.AddSubOrganization("nameA", parentOrganization);

// or use OrganizationDistinguishedName
_ldapManager.AddSubOrganization("nameA", "OU=Domain Controllers,DC=yourdomain,DC=com,DC=cn");
```

## Query Users

```cs
// query all users
// filter: (&(objectCategory=person)(objectClass=user))
_ldapManager.GetUsers();

// query organizations by name
// filter: (&(name=abc)(objectCategory=person)(objectClass=user))
_ldapManager.GetUsers(name : "abc");

// query organizations by displayName
// filter: (&(displayName=abc)(objectCategory=person)(objectClass=user))
_ldapManager.GetUsers(displayName : "abc");

// query organization by commonName
// filter: (&(cn=abc)(objectCategory=person)(objectClass=user))
_ldapManager.GetUsers(commonName : "abc");

```

## Query User

```csharp
// query a user by distinguished name
// filter: (&(distinguishedName=abc)(objectCategory=person)(objectClass=user))
_ldapManager.GetUser("abc");

```

## Add User

```csharp
// use LdapOrganization
_ldapManager.AddUserToOrganization("nameA", "passwordA", parentOrganization);

// or use OrganizationDistinguishedName
_ldapManager.AddUserToOrganization("nameA", "passwordA", "OU=Domain Controllers,DC=yourdomain,DC=com,DC=cn");
```

**Comment by akinix** [comment]
`<PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="2.3.8" />`

used `Novell.Directory.Ldap.NETStandard` for `NETStandard`

Source [Novell.Directory.Ldap.NETStandard](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard)

**Comment by akinix** [comment]
how to test?
- prepare LDAP environment. run a openldap in docker.
 > dockerhub : [osixia/openldap](https://hub.docker.com/r/osixia/openldap)
 > source [https://github.com/osixia/docker-openldap](https://github.com/osixia/docker-openldap)
- pull image
 ```shell
 docker pull osixia/openldap
 ```
- run ldap
 ```shell
 docker run --name ldap -d --env LDAP_ORGANISATION="abp" --env LDAP_DOMAIN="abp.com" --env LDAP_ADMIN_PASSWORD="123456" -p 389:389 -p 636:639 --detach osixia/openldap
 ```
- configure
```json
"LDAP": {
    "ServerHost": "127.0.0.1",
    "ServerPort": 636,
    "UseSSL": true,
    "Credentials": {
        "DomainUserName": "admin@abp.com", // or cn=admin,dc=abp,dc=com
        "Password": "123456"
    },
    "SearchBase": "DC=abp,DC=com",
    "DomainName": "abp.com",
    "DomainDistinguishedName": "DC=abp,DC=com"
}
```

**Comment by hikalkan** [comment]
Great! Would you like to send a PR? I can copy it, but I like that you have a contribution in the [contributors list](https://github.com/abpframework/abp/graphs/contributors).

**Comment by leonkosak** [comment]
Does LDAP authentication in abp.io work in multitenant environment (for instance in ANZ you have to disable multitenancy if you want using LDAP)?

**Comment by maliming** [comment]
hi @leonkosak  We will make it support multi-tenancy.  : ) https://github.com/abpframework/abp/issues/4983

**Comment by leonkosak** [comment]
@maliming I have scenario to authenticate via local Active Directory (AD). I am confused how to properly implement this external login.
Probably, when one user login to application for the first time, should we create new external user (AbpUsers table) and then when we have a record for new user in AbpUsers table add permissions and roles to this user?
User would always manually make login with his/her AD user.

Could you please describe steps how to **properly implement** this integration (robust and secure)?
Thank you.

**Comment by maliming** [comment]
hi @leonkosak 

Please create a new issue.
