### ISSUE TITLE
RemoteServices URLs are not being used 

### ISSUE THREAD

**Issue by ahmadmasoum** [abpframework/abp#11894]
**ABP Framework version: 4.1.3**.
 **User Interface: MVC**
** Your database provider: EF Core**
* Steps needed to **reproduce** the problem.

I have Tired MVC Application, I Published all the projects under one website
![image](https://user-images.githubusercontent.com/72628109/157618752-48c99824-77e1-49b3-9620-c279e4d09435.png)

the URLs

```
https://www.carsharingmvc.com/identityserver
https://www.carsharingmvc.com/HttpApiHost
https://www.carsharingmvc.com/web
https://www.carsharingmvc.com/WebPublic
```

When I make a request to `identityserver` or `HttpApiHost` it goes with the wrong URL
For example, the outgoing request from web project is 
`https://www.carsharingmvc.com/api/identity/users`
it should be 
`https://www.carsharingmvc.com/HttpApiHost/api/identity/users`

and when I open components for example cms it goes to 
`https://www.carsharingmvc.com/Cms/Pages`
it should go to 
`https://www.carsharingmvc.com/web/Cms/Pages`

in Web appsettings there are URLs configured but they are not being used WebModule
```
"RemoteServices": {
    "Default": {
      "BaseUrl": "https://www.carsharingmvc.com/HttpApiHost/"
    },
    "AbpAccountPublic": {
      "BaseUrl": "https://www.carsharingMVC.com/IdentityServer/"
    }
  },
```
How can i configure the root URL from API requests?

**Comment by maliming** [comment]
> For example, the outgoing request from web project is
https://www.carsharingmvc.com/api/identity/users

JavaScript or Application Server call?

**Comment by ahmadmasoum** [comment]
> > For example, the outgoing request from web project is
> > https://www.carsharingmvc.com/api/identity/users
> 
> JavaScript or Application Server call?

JavaScript

**Comment by maliming** [comment]
I tested it, it works.

![image](https://user-images.githubusercontent.com/6908465/158088882-8355d1ec-4651-4011-95e2-a8491802bf87.png)


![image](https://user-images.githubusercontent.com/6908465/158088873-733ba071-fe2f-4d48-a905-73922738abaa.png)
