### ISSUE TITLE
Is there any procedure for updating existing application to the latest abp framework version ?

### ISSUE THREAD

**Issue by MROALI** [abpframework/abp#11900]
Hello, 

I want to know if there exists any procedure for upgrading an existing application  (5..1.3 )to latest preview version (5.2) of  abp 
framework.

Updating all packages in the solutions, etc...

Thankyou in advance

**Comment by DonVliet** [comment]
You can run the following command from a terminal window while you are in the root folder of your solution. This will  update all the ABP related NuGet and NPM packages in your solution to the latest preview version:

**abp  switch-to-preview**

Also, check out the upgrade documentation here

https://docs.abp.io/en/abp/5.2/Upgrading

Don
