### ISSUE TITLE
Introducing the ABP Community Discord Server

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#11916]
We've created a discord server for the ABP Community.

You can use this link to join the server: https://discord.gg/abp

Our purpose is to provide an interactive environment to talk about ABP and .NET. You can ask your questions and discuss ideas here, but this is not a technical support platform. For deep technical issues, you should use GitHub issues or ABP Commercial support website if you are an ABP Commercial customer.

**Comment by Enissay** [comment]
Amazing idea, sadly I am getting this:
![zz](https://user-images.githubusercontent.com/794673/158080420-447cfbc6-38bb-4769-9228-37baa50363c8.png)

**Comment by enisn** [comment]
Hi @Enissay

Try this one: https://discord.gg/VSC7ZkjZpN

**Comment by ttpp123** [comment]
Hi 

I tried to join ABP Community in discord. But I got "Unable to accept invite".  Can someone provide a valid link? Thanks

![image](https://user-images.githubusercontent.com/6539279/159598213-442268c0-5a96-4860-83e7-4a47c4a8e7f3.png)

**Comment by enisn** [comment]
![image](https://user-images.githubusercontent.com/23705418/159634626-2511e1f9-d9fc-42a1-8c36-b54a7cda7853.png)
Links shouldn't be expired, but I'm creating new one since you can't join

Try this one: https://discord.gg/VSC7ZkjZpN

**Comment by ebicoglu** [comment]
https://community.abp.io/discord
[![image](https://user-images.githubusercontent.com/9526587/168016636-cde7deb6-6088-4b15-806a-59780efc8b35.png)
](![image](https://user-images.githubusercontent.com/9526587/168016612-e1975c30-9579-4217-a757-307988f7caee.png))
