### ISSUE TITLE
Help with virtual file system and c# concepts

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1191]
I would like to learn more about embedded files and the virtual file system and it’s structure and how I can override files can someone point me to any resources which I can read and learn?

I have read the docs on app.io regarding virtual file system but I need more detail and then I can create a video tutorial which can help others how to override files.

It’s been a long time since I had my hands on the c# I think I need a refresher course any resources which you think can help me would be great.

Any idea when version 18 featuring the new cli will be out waiting to complete the videos which I have been recording.

**Comment by hikalkan** [comment]
In addition to the source code, you should dig in to the source code. Unfortunately, there is no additional resource.

>how I can override files

Actually, it is very easy. Virtual file system is just like a real file system consists of folders and files. Each module contributes to this file system by adding folders/files. If module B depends on module A and they both adds a file to the same path, module B's file overrides module A's.

>when version 18 featuring

In the next week. CLI become very handy, we are rewriting the related documents based on it. Examples:
https://github.com/abpframework/abp/blob/master/docs/en/CLI.md and https://github.com/abpframework/abp/blob/master/docs/en/Getting-Started-AspNetCore-MVC-Template.md

Also, the startup templates are completely changed. See new structure: https://github.com/abpframework/abp/blob/master/docs/en/Startup-Templates/Mvc.md

So, worth to wait 8-9 days more :)
