### ISSUE TITLE
why abp cli generate-proxy need url?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#11924]
when in module develpment, if I want to use cmd to generate a js proxy for my module, I use cmd like
` abp generate-proxy -t js -m mymodulename ` 
but I get the wrong msg:
`Value cannot be null. (Parameter 'Url')`
why I must use prarmeter Url? I think in module generate proxy,no need use Url Parameter.

**Comment by JadynWong** [comment]
To generate a static proxy, it need to get the definition from the `/api/abp/api-definition` API.

https://docs.abp.io/en/abp/latest/CLI#generate-proxy
> --url or -u: API definition URL from. For csharp and js client types.

https://github.com/abpframework/abp/blob/3853e1464f7dadcbcf385aafee27540b4c3fd64c/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ServiceProxying/ServiceProxyGeneratorBase.cs#L30-L49

**Comment by maliming** [comment]
Thanks @JadynWong
