### ISSUE TITLE
File Systems depend to the Public web project; It may be a separate service

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#11949]
File Systems depend on the Public web project; It may be a separate service or any solution. 
The problem is: Catalog or Ordering service returns the file name. The file host in eShopOnAbp.Public root (under the wwwRoot/product-images).
 
If it stays like that, the Angular Backoffice app depends on Public Web Project.

**Comment by gterdem** [comment]
We can implement file system in the next milestones. For now, we can move these demo product image files to related _CatalogService_ and expose through CatalogService api.

@malikmasis Can you handle that please?
