### ISSUE TITLE
Move the build folder inside `etc`

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#11947]
To keep the root folder cleaner, we can move https://github.com/abpframework/eShopOnAbp/tree/main/build to the `etc` folder (may not be directly in `etc/build`, but a proper folder).

**Comment by gterdem** [comment]
Moving this issue to the next milestone to discuss the reasoning and the proper directory structure for this folder.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/eShopOnAbp/issues/148
