### ISSUE TITLE
Table of AbpEntityPropertyChanges

### ISSUE THREAD

**Issue by md-yilmaz** [abpframework/abp#11956]
Hello,
the change I made to the data is reflected in the table called [AbpEntityPropertyChanges], there is no problem here.
But even if I make more than 1 different different update to the same data [AbpEntityPropertyChanges], this table only looks like the update I made first, other updates are not reflected
I would like your help in this matter.

**Comment by md-yilmaz** [comment]
Is there anyone who can help? friends

**Comment by gterdem** [comment]
Can you please create a public repository with related reproduction steps/unit tests that we can check?

**Comment by md-yilmaz** [comment]
you can look at github to solve my problem.
[](https://github.com/Lustral11/Audit.git)

**Comment by md-yilmaz** [comment]
https://github.com/Lustral11/Audit.git

**Comment by gterdem** [comment]
duplicate, moved to https://github.com/abpframework/abp/issues/12055

**Comment by md-yilmaz** [comment]
https://github.com/Lustral11/Audit.git
