### ISSUE TITLE
[AbpEntityPropertyChanges] Tablosu

### ISSUE THREAD

**Issue by md-yilmaz** [abpframework/abp#11955]
Merhabalar,
veri üzerinde yaptıgım degişiklik [AbpEntityPropertyChanges] isimli tabloya yansıyor burda sıkıntı yok.
Ancak aynı veriye 1 den fazla farklı farklı update yapsam bile [AbpEntityPropertyChanges] bu tabloya sadece il yaptıgım update gözüküyor diger update ler yansımıyor 
Bu konuda yardımınızı rica ederim.

**Comment by EngincanV** [comment]
Duplicate of #11956

**Comment by md-yilmaz** [comment]
i've solved the problem, friends.

The module is in the Presentation Layer.the cs folder is named after me : SampleBlazorModule.cs is in this 

the problem was solved by adding the following lines to the public override void ConfigureServices (ServiceConfigurationContext context) method.

 Configure<AbpAuditingOptions>(options =>
 {
 options.IsEnabled = true;
 options.EntityHistorySelectors.AddAllEntities();
 });
