### ISSUE TITLE
As for 'onUnitOfWorkComplete' in the EventBus Module, I have a suggestion to make it globally configurable

### ISSUE THREAD

**Issue by MapleWithoutWords** [abpframework/abp#11959]
Use Abp Version : 5.1.4

When I unit tested the project, I found that the event bus would not be executed immediately, causing some of my tests to fail. I looked through the documentation and found that this was due to the inclusion of the property onUnitOfWorkComplete, which by default will publish the event after the UOW completes. But I wanted to get Jie 'Guo immediately when I did the unit tests

**Comment by hikalkan** [comment]
Globally configuring the default value is a good idea. I will think about side effects on that.

**Comment by hikalkan** [comment]
Hi @MapleWithoutWords we won't do that. Unit tests should behave as the real application.  I suggest you to revisit your unit tests to handle that scenario.
Making such logics as optional make the framework codebase complicated. Also, it restricts us when we want to make further development on the framework (we will have to make both options properly working in every scenario).
