### ISSUE TITLE
5.2 Preview Errors in Template Of Application Template and Single Layer Template

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#11968]
the error was in application template in AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Lepton.Global'!

and same error in single layer application 
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Lepton.Global'!
and errror when creating application with suite
and secret key not created

thanks

**Comment by berkansasmaz** [comment]
Can you try again after running the `abp install-libs` command where the project(`*.csproj` file) is located?

**Comment by berkansasmaz** [comment]
https://github.com/abpframework/abp/blob/dev/docs/en/Blog-Posts/2022-03-08%20v5_2_Preview/POST.md#libs-folder-has-been-removed-from-source-control

> When you create a new solution with ABP CLI, abp install-libs command is automatically executed, so your application directly works. 

@yekalkan when I download template with version `5.2.0-rc.1` the `abp install-libs` command does not automatically execute, FYI.

**Comment by berkansasmaz** [comment]
@awahbahplana can you write the operating system you are using?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/5.2.0-rc.1/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/ProjectCreationCommandBase.cs#L314

**Comment by berkansasmaz** [comment]
The reason for the problem we are having is the version of the project we downloaded is `5.2.0-rc-1`, but the version of the ABP CLI is `5.1.4`, so the `abp install-libs` command does not automatically execute during the create a new solution.

**Solution:**
For `*.*.*-rc-*` versions, download the pre-release version of the ABP CLI

`dotnet tool update -g Volo.Abp.Cli --prerelease`


--- 

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
