### ISSUE TITLE
Prefix of component should be changed on EshopOnABP

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#11970]
the prefix of components on the library is 'lib. I think it should be changed.
![image](https://user-images.githubusercontent.com/2217899/158362218-6ecc9d95-5a47-4c28-968b-70085c48a19a.png)

**Comment by BekAllaev** [comment]
Hello. Can I take this issue?

**Comment by mahmut-gundogdu** [comment]
> Hello. Can I take this issue?

Sure, I would be glad

**Comment by mahmut-gundogdu** [comment]
hi @Allaev1  what is the status of the issue? I can implement the task if you don't want to implement

**Comment by BekAllaev** [comment]
Hello Mahmut. Yes, can you please take this issue I don't have enough time to implement it

Получите Outlook для Android<https://aka.ms/AAb9ysg>
________________________________
