### ISSUE TITLE
AbpHub cache bug

### ISSUE THREAD

**Issue by 312977** [abpframework/abp#11976]
abp version 5.0  
Volo.Abp.AspNetCore.SignalR  version 5.1.4
use  AbpHub  signalR and rediscache

OnConnectedAsync  set  an  rediscache, but in OnDisconnectedAsync  get null
and the cache can be get   in api method, only in OnDisconnectedAsync get is null
cache alway exsit        
code bylow 
````
public override async Task OnConnectedAsync()
        {
            using (_dataFilter.Disable<IMultiTenant>())
            {
                var cache = await _carClientCache.GetAsync('aaa');
                await _carClientCache.SetAsync("aaa", new Dictionary<string, int>
                {
                    { Context.ConnectionId, 555 }
                }, new DistributedCacheEntryOptions
                {
                    AbsoluteExpiration = DateTimeOffset.Now.AddHours(12)
                });
            }
}
````

````
public override async Task OnDisconnectedAsync(Exception ex)
        {
            using (_dataFilter.Disable<IMultiTenant>())
            {
                var cache = await _carClientCache.GetAsync("aaa");
                var a = 1;
            }
}
````
OnConnectedAsync()   var cache = await _carClientCache.GetAsync('aaa'); cache  is not null
OnDisconnectedAsync   var cache = await _carClientCache.GetAsync('aaa'); cache  is  null

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by 312977** [comment]
i  changed the information

**Comment by realLiangshiwei** [comment]
There is no problem

![image](https://user-images.githubusercontent.com/16813853/158526744-5dca8317-f95a-4866-9710-b504dfe603a9.png)

**Comment by 312977** [comment]
this problem  only in  winform  Microsoft.AspNetCore.SignalR.Client,
my version is  6.0.2   ,
im try change the  SignalR.Client version to fix this  problem

**Comment by 312977** [comment]
i am tryed  the other Microsoft.AspNetCore.SignalR.Client,  versions  ,  but the problem still in

**Comment by 312977** [comment]
const string ServerUri = "https://localhost:44344/signalr/carcommunication";

            var hubConnection = new HubConnectionBuilder()
                 .WithUrl(ServerUri)
                 .WithAutomaticReconnect()

                 .Build();

hubConnection.StartAsync().ConfigureAwait(true);

**Comment by 312977** [comment]
[[](url)](https://siyuan.dongxiweilai.com/signalr.rar)
this  is  my code ,you can download ;
start up   product.host  and then ,start winform  , click  connect button 
in swagger   api  ,test  and test2, will get the right  cache vue  ,
but  in OnDisconnectedAsync  ,the cache  is null

**Comment by colinin** [comment]
Multi-tenant filters are only used when querying a database, **CurrentTenant.Change(null)** should be used to ignore multi-tenant in the cache

**Comment by 312977** [comment]
i   fixed  this problem ,because  the token

ar token = new CancellationTokenSource().Token;
var a = await _distributedCache.GetAsync("test", token: token);
