### ISSUE TITLE
Audit-Logging event enhancements

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#11982]
In distributed system cases where Audit-Logging needs to be written by using events instead of direct database connection, there is a huge overhaul about mapping AuditLogInfo to an Eto. We can simplify this process.

**Comment by Trojaner** [comment]
Solves the issue I was just facing [here](https://github.com/Trojaner/AbpZeroTrustArchitecture/blob/main/modules/remoting/src/Sample.Remoting/SampleAuditingStore.cs#L14).

While at it, can you make AuditLog and its property setters public in case we want to add custom audit logs like [here](https://github.com/Trojaner/AbpZeroTrustArchitecture/blob/main/services/Sample.Auditing/src/Sample.Auditing.Application/AuditLogAppService.cs#L68)?

**Comment by gterdem** [comment]
> Solves the issue I was just facing [here](https://github.com/Trojaner/AbpZeroTrustArchitecture/blob/main/modules/remoting/src/Sample.Remoting/SampleAuditingStore.cs#L14).
> 
> While at it, can you make AuditLog and its property setters public in case we want to add custom audit logs like [here](https://github.com/Trojaner/AbpZeroTrustArchitecture/blob/main/services/Sample.Auditing/src/Sample.Auditing.Application/AuditLogAppService.cs#L68)?

Instead of adding property directly to AuditLog aggregate-root, I would suggest using `ExtraPropertyDictionary`. Do you have use cases where object-extension doesn't work for you?

I also made [AuditLogInfo collections with public setters](https://github.com/abpframework/abp/pull/11983/commits/b5a0c99f500c41fa926666f543249f705603e08a) so it will be available to be mapped fully with extra properties.

**Comment by gterdem** [comment]
This improvement is canceled. See https://github.com/abpframework/abp/pull/11983#issuecomment-1099123609.
