### ISSUE TITLE
Publish and subscribe event with Distributed Event Bus Azure Integration.

### ISSUE THREAD

**Issue by GerardoGrecoPorini** [abpframework/abp#11988]
We're trying your framework especially the Distributed Event Bus Azure Integration. I created two projects: the first one publish an event throught the `PublishAsync` Method; the second one subscribes to the event via the `IDistributedEventHandler<TEvent>` interface.

When an event is published from the first project, it is consumed by the second project, but also by the first project.
I'd like to prevent the first project from consuming the event that it published. Is there a raccomanded way to avoid this behaviour?

**Comment by gterdem** [comment]
The event handling point is `IDistributedEventHandler<TEvent>`. Does your first application implement `IDistributedEventHandler<TEvent>`? If not, it shouldn't be handling the published event.

If this behavior occurs, can you create a public repository that reproduces this behavior and share it with us so we can examine it?

**Comment by GerardoGrecoPorini** [comment]
The application did not implement `IDistributedEventHandler<TEvent>`.

I created a repo with an example: https://github.com/GerardoGrecoPorini/ABP.DistributeEventBusTest. 
In this example I have one topic (topic-1) with two subscribers (pub-1 and sub-1). The application have this configuration:

```
Configure<AbpAzureEventBusOptions>(options =>
{
    options.ConnectionName = "Default";
    options.SubscriberName = "pub-1";
    options.TopicName = "topic-1";
});
```

When send message from the application the message is delivered on Azure Service Bus in subscription `sub-1` but not in subscription `pub-1`, because the application read the message.

**Comment by Prathamshetty43** [comment]
is it possible to to publish and subscribe events from basic tier subscription?

**Comment by ahmadalmunajjed** [comment]
> is it possible to to publish and subscribe events from basic tier subscription?

+1

**Comment by ahmadalmunajjed** [comment]
Seems it's not supported by Azure Event Bus itself because basic tier does not support topics and without topic you need to use queue which support one sender and one receiver only for each message.
