### ISSUE TITLE
5.2.0-rc.1 bug Can not run Blazor Server in preview version

### ISSUE THREAD

**Issue by cuno92** [abpframework/abp#11984]
5.2.0-rc.1
blazor-server
postgresql

step:
run DbMigrator
run Blazor project then get AbpException : Could not find the bundle file '/libs/bootstrap/css/bootstrap.css' for the bundle 'Blazor.BasicTheme.Global'!

Stacktrace
`Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List<BundleTagHelperItem> bundleItems, string bundleName)
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService<TTagHelper, TService>.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
GoEx.CargoBooking.Blazor.Pages._Pages__Host.<ExecuteAsync>b__16_0() in _Host.cshtml
<abp-style-bundle name="@BlazorBasicThemeBundles.Styles.Global" />`

**Comment by realLiangshiwei** [comment]
Try:
`abp install-libs`

May I ask, what version is your ABP CLI?

**Comment by cuno92** [comment]
> Try: `abp install-libs`
> 
> May I ask, what version is your ABP CLI?

Thanks this works, My ABP CLI version is **5.2.0-rc.1 (Prerelease)**, I think stable version automatically run this command but preview does not

**Comment by realLiangshiwei** [comment]
After my check, it works fine.

![image](https://user-images.githubusercontent.com/16813853/158725017-f61d533a-5f3a-4a89-bcf8-0e8ea57ff05a.png)
