### ISSUE TITLE
MinIO API request https not working

### ISSUE THREAD

**Issue by thanhtai9606** [abpframework/abp#11995]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **5.1*.
* Your **Angular** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider EF
* Exception message and **MinIO API responded with message=The request signature we calculated does not match the signature you provided** if available (check the logs).
* Steps needed to **reproduce** the problem.

It cannot working with ssl port in our minio on kubernetes . I tried port when use port forward in kubernete http://localhost:9000 is working. But when I use https://minio.xx it not working. 
```
        "EndPoint": "minio.xxx",
        "AccessKey": "admin",
        "SecretKey": "admin1234",
        "BucketName": "abc",
        "WithSSL": true,
        "CreateBucketIfNotExists": true

```
Please help me

**Comment by maliming** [comment]
hi

> The request signature we calculated does not match the signature you provided

This doesn't seem to be related to abp?

**Comment by thanhtai9606** [comment]
No, I not think it. When I used it working


```
            var endPoint = "minio.xx";
            var accessKey = "admin";
            var secretKey = "admin1234";
            try
            {
                var minio = new MinioClient()
                                        .WithEndpoint(endPoint)
                                        .WithCredentials(accessKey, secretKey)
                                        .WithSSL()
                                        .Build();

```
But default Volo.Minioxx. It not working
 [https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BlobStoring.Minio/Volo/Abp/BlobStoring/Minio/MinioBlobProvider.cs](url)
```
 var client = new MinioClient(configuration.EndPoint, configuration.AccessKey, configuration.SecretKey);

        if (configuration.WithSSL)
        {
            client.WithSSL();
        }
```

**Comment by thanhtai9606** [comment]
How can I modify it??

**Comment by maliming** [comment]
You can try to override the `GetMinioClient` method.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BlobStoring.Minio/Volo/Abp/BlobStoring/Minio/MinioBlobProvider.cs#L95

**Comment by thanhtai9606** [comment]
I already tried override minio and update new Minio latest. But I get this error
```
System.InvalidOperationException: There is an error in XML document (1, 2).     
 ---> System.InvalidOperationException: <html xmlns=''> was not expected.       
```
I think error is minio already installed in Volo.Abp.BlobStoring.Minio
in package 
```
 <PackageReference Include="Minio" Version="3.1.13" />
```
But still not working too!!

**Comment by thanhtai9606** [comment]
```
using Minio;
using Volo.Abp.BlobStoring;
using Volo.Abp.BlobStoring.Minio;
using Volo.Abp.DependencyInjection;
namespace Becamex.ArchiveCenter
{
    [Dependency(ReplaceServices = true)]
    public class MyMinioBlobProvider : MinioBlobProvider
    {
        public MyMinioBlobProvider(IMinioBlobNameCalculator minioBlobNameCalculator, IBlobNormalizeNamingService blobNormalizeNamingService) : base(minioBlobNameCalculator, blobNormalizeNamingService)
        {
        }
        protected override MinioClient GetMinioClient(BlobProviderArgs args)
        {
            var configuration = args.Configuration.GetMinioConfiguration();
            // var client = new MinioClient(configuration.EndPoint, configuration.AccessKey, configuration.SecretKey);

                var client = new MinioClient()
                                        .WithEndpoint(configuration.EndPoint)
                                        .WithCredentials(configuration.AccessKey, configuration.SecretKey)
                                        .WithSSL()
                                        .Build();
            // if (configuration.WithSSL)
            // {
            //     client.WithSSL();
            // }

            return client;
        }
    }
}
```
this is override GetMinioClient with latest Minio in Domain project but get error above??

**Comment by maliming** [comment]
Can you set the breakpoint to confirm your `MyMinioBlobProvider` is working?

**Comment by thanhtai9606** [comment]
Yes it working fine. I passed to return client. But still error!
I already tried it with sample Minio in 3.11.3 error too.
But when move to higher 4.0.0 it sample working
[https://i.imgur.com/r57OOxl.png](url)

**Comment by maliming** [comment]
ok, You can use the higher version in your project.
We will upgrade it later.

https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.BlobStoring.Minio/Volo.Abp.BlobStoring.Minio.csproj#L18

**Comment by thanhtai9606** [comment]
I think, I will create minio with no SSL to use this feature. Thank for your help!!
