### ISSUE TITLE
Datatables localization problem

### ISSUE THREAD

**Issue by Webdiyer** [abpframework/abp#1199]
https://github.com/abpframework/abp/blob/026c9898f5882ba89da6ab98f6c0337df5cd9a99/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L54
I'd like to override the default localization text and use my own localization resource in the current project, should the resource name here be passed as parameter instead of hard coded value?

**Comment by maliming** [comment]
You can extending existing resource.
see: https://abp.io/documents/abp/latest/Localization#extending-existing-resource
