### ISSUE TITLE
API with inheritance in the model

### ISSUE THREAD

**Issue by GerardoGrecoPorini** [abpframework/abp#12016]
We're trying to create a new API with inheritance in the model. The standard OpenApi supports this scenario using a discriminator, it can possible to achieve this result with ABP framework?

**Comment by gterdem** [comment]
Can you explain more? What inheritance is in the model? What exactly does OpenApi support? Do you mean **swagger**?

**Comment by GerardoGrecoPorini** [comment]
I try to explain with a semplification of our model:

```
public class PatientDto
{
     public string Name { get; set;}
     public IList<ExamBaseDto> Exams {get; set;}
}
```

```
public class ExamBaseDto
{
     public string Code {get; set;}
}
```

```
public class ExamUsDto : ExamBaseDto
{
     public bool Lossy {get; set;}
}
```

```
public class ExamMrDto: ExamBaseDto
{

     public bool FullBody {get; set;}
}
```

We implement a PatientAppService who extend ABP CrudAppService.
In PatientAppService we create a new method with this signature: `public async Task<IEnumerable<ExamBaseDto>> AppendExamAsync(Guid id, IEnumerable<ExamBaseDto> newExams)`.
When the generated API was called (we call the API with a payload which contains mixed Exam types in newExams) , the specific properties of ExamUsDto and ExamMrDto are missing, both for CRUD post method and our custom method.

The OpenApi standard handles this case with a discriminator; you can find more details in the following page: 
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

We're trying to figure out if this case is supported by ABP.
