### ISSUE TITLE
Unable to run the project after the Project is created with PostgreSQL 

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#12014]
**Version:** `5.2.0-rc.1`
**Problem Definition:**  The project was created by selecting the database PostgreSQL and the project was tried to be run and an error was given when DbMigrator was run.

![image](https://user-images.githubusercontent.com/99716457/158984509-164dfa83-b1a9-40e8-80fc-166efbda8179.png)

**Comment by maliming** [comment]
This should be working in rc2.

https://github.com/abpframework/abp/pull/11871
