### ISSUE TITLE
KeyCloak Integration for eShopOnAbp project

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12021]

**Comment by gterdem** [comment]
I would propose integrating [Keycloak](https://www.keycloak.org/) for eShopOnAbp as a demonstration since we already have OpenIddict integrated in microservice templates.
@enisn what do you think?

**Comment by enisn** [comment]
Yes, I agreed. That would be a great example of building a micro-service solution using keycloak with ABP Framework.
