### ISSUE TITLE
Request: DistributedEventHander.PublishAsync - automatically add CurrentTenant.Id if Eto implements IMultiTenant

### ISSUE THREAD

**Issue by clinically-au** [abpframework/abp#12025]
Currently, if an ETO implements IMultiTenant, the tenant is automatically changed to the specified tenant when HandleAsync is called. This is very helpful.

At the moment, the TenantId needs to be set manually for the Eto.

Would you consider the distributed event bus automatically adding the CurrentTenant ID if the ETO implements IMultiTenant? 

I suppose the other option would be for me to implement an ETO factory that does it for me?

**Comment by maliming** [comment]
Seems reasonable.

**Comment by maliming** [comment]
hi

This conflicts with `GetEventDataTenantId` feature.


https://github.com/abpframework/abp/blob/9cbb244efe520997cda82ea0cdf97a5700889dcf/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/EventBusBase.cs#L215

https://github.com/abpframework/abp/blob/9cbb244efe520997cda82ea0cdf97a5700889dcf/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/EventBusBase.cs#L231
