### ISSUE TITLE
Use OpenIdDict within the single-layer and module startup templates (instead of IDS)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12022]
- [x] Single-layer https://github.com/abpframework/abp/pull/12624/commits/a86187393554d4b73617a2a698a5440e3b3bfa30
- [x] Module https://github.com/abpframework/abp/pull/12624/commits/a86187393554d4b73617a2a698a5440e3b3bfa30

**Comment by enisn** [comment]
This issue will be able to be done after [#9448](https://github.com/volosoft/volo/issues/9448)

**Comment by hikalkan** [comment]
I am taking this to 5.4 milestone to work on it in this milestone. However, we may not merge the work in version 5.4.

**Comment by maliming** [comment]
Move to https://github.com/abpframework/abp/pull/12624

https://github.com/abpframework/abp/pull/12624/commits/a86187393554d4b73617a2a698a5440e3b3bfa30
