### ISSUE TITLE
Feature Setting UI will not display the description text while the ValueType is ToggleStringValueType

### ISSUE THREAD

**Issue by zhongfang2018** [abpframework/abp#12037]
* Your **ABP Framework version**. 5.1.4.
* Your **User Interface** type Blazor.Server
* Your database provider(EF Core)
* Exception message and **stack trace** if available (check the logs).
only display a checkbox with the text of L("IsEnabled"),
but L("Change.PointPay.Desc") is missing.
* Steps needed to **reproduce** the problem.
~~~
group.AddFeature(
                PointPayFeature.IsEnabled,
                "false",
                L("IsEnabled"),
                L("Change.PointPay.Desc"),
                valueType: new ToggleStringValueType(new BooleanValueValidator()));
~~~

**Comment by zhongfang2018** [comment]
Oh, no. I am a commercial user. I created application with ABP suite.
I need't to do something to setting ui.

**Comment by zhongfang2018** [comment]
Oh, no. I am a commercial user. I created application with ABP suite.
I need't to do something to setting ui.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/pull/12040

**Comment by zhongfang2018** [comment]
If I use FreeTextStringValueType, I can see the description in blazor ui.
If I use ToggleStringValueType. I can not see the description in blazor ui.

Is it not a bug for ToggleStringValueType?

**Comment by maliming** [comment]
It will fixed in the next version.
