### ISSUE TITLE
How to Add Custom Claim to Jwt

### ISSUE THREAD

**Issue by CaglarMacha** [abpframework/abp#12035]
Hello,
First of all, I would like to state that I am inexperienced in the Abp framework. In addition that I am a freshman in the software world. Taking everything into account my problem may be easy, unnecessary, or top-hamper for you. Coming to the matter,  I would like to add a new claim to the payload of the jwt token. Can you help me with how to do it? Can you share documents or examples?

**Comment by Trojaner** [comment]
See https://github.com/abpframework/abp/issues/8073#issuecomment-799999030

**Comment by CaglarMacha** [comment]
> See [#8073 (comment)](https://github.com/abpframework/abp/issues/8073#issuecomment-799999030)

Thank you so much. It's worked. My problem was solved thanks to your support.
