### ISSUE TITLE
FeatureDefinitionProvider: Exception Message has a wrong word

### ISSUE THREAD

**Issue by zhongfang2018** [abpframework/abp#12036]
* Your **ABP Framework version**.  5.1.4
* Your **User Interface** type Blazor.Server
* Your database provider(EF Core)
* Exception message and **stack trace** if available (check the logs).
~~~
Volo.Abp.AbpException: There is already an existing permission group with name: Change.Bazi
   at Volo.Abp.Features.FeatureDefinitionContext.AddGroup(String name, ILocalizableString displayName)
   at Yee.Change.PointPay.Features.PointPayFeatureDefinitionProvider.Define(IFeatureDefinitionContext context)
   at Volo.Abp.Features.FeatureDefinitionManager.CreateFeatureGroupDefinitions()
~~~
* Steps needed to **reproduce** the problem.
It es feature group conflit, not permission.

**Comment by zhongfang2018** [comment]
the same error in [https://docs.abp.io/en/abp/latest/Features](url)

Changing Features Definitions of a Depended Module
A class deriving from the FeatureDefinitionProvider (just like the example above) can also get the existing permission definitions (defined by the depended [modules](https://docs.abp.io/en/abp/latest/Module-Development-Basics)) and change their definitions.

Example: Manipulate an existing feature definition

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/11932
