### ISSUE TITLE
How to use application configuration object extensions

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#12030]
I have noticed there is a objectExtensions field in the application-configuration API returns. I want to have some extraproperties such as tenant phone number or tenant address in the application-configuration API. How can I achieve that?
![image](https://user-images.githubusercontent.com/7014849/159220255-359aa73d-d775-4866-b86f-f2bfe0f12ee0.png)

**Comment by gterdem** [comment]
See [Object Extensions docs](https://docs.abp.io/en/abp/latest/Object-Extensions).
