### ISSUE TITLE
Error after Update To 5.1.4

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#12047]
An exception was thrown while activating Volo.Abp.ObjectMapping.DefaultObjectMapper`1[[Volo.Abp.Identity.AbpIdentityDomainModule, Volo.Abp.Identity.Domain, Version=5.1.4.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider`1[[Volo.Abp.Identity.AbpIdentityDomainModule, Volo.Abp.Identity.Domain, Version=5.1.4.0, Culture=neutral, PublicKeyToken=null]] -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor.

**Comment by gterdem** [comment]
In what version did you update your application to 5.1.4? Did you follow the [migration guide](https://docs.abp.io/en/abp/5.0/Migration-Guides/Abp-5_0) if you have updated from 4.x.x?

**Comment by awahbahplana** [comment]
it was V 5 there is no change I need to add.
Now I Update 5.1.3 to 5.1.4

**Comment by awahbahplana** [comment]
It Causes From seeding On First Migration

**Comment by OzgulEzgin** [comment]
Hello, I have the same issue. When I try to access application service for a simple list I get this... 
An exception was thrown while activating Volo.Abp.ObjectMapping.DefaultObjectMapper -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor.  
![ErrorOnVolo](https://user-images.githubusercontent.com/10051037/160212409-c95a4efc-b521-4c9d-8b6c-e4d1a0e68225.PNG)

**Comment by lgadola** [comment]
Did you check exception details/inner exception? If it is a mapping error it will tell you which properties in which DTO's can't be mapped.

**Comment by tunechr** [comment]
Hi We also get this due to a dependency on ELSA which uses automapper 11.

**Comment by awahbahplana** [comment]
Hello this issue happen because i am using elsa workflow so this error happen with elsa V2.6.0

**Comment by awahbahplana** [comment]
> Hello, I have the same issue. When I try to access application service for a simple list I get this... An exception was thrown while activating Volo.Abp.ObjectMapping.DefaultObjectMapper -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor. ![ErrorOnVolo](https://user-images.githubusercontent.com/10051037/160212409-c95a4efc-b521-4c9d-8b6c-e4d1a0e68225.PNG)

Hello did you using elsa workflow in your application?

**Comment by EngincanV** [comment]
It seems with [v2.6.0](https://github.com/elsa-workflows/elsa-core/discussions/2858) Elsa updated the AutoMapper version to 11. This problem might be related to that. 
Can you try to downgrade the version of Elsa?

**Comment by OzgulEzgin** [comment]
> > Hello, I have the same issue. When I try to access application service for a simple list I get this... An exception was thrown while activating Volo.Abp.ObjectMapping.DefaultObjectMapper -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor. ![ErrorOnVolo](https://user-images.githubusercontent.com/10051037/160212409-c95a4efc-b521-4c9d-8b6c-e4d1a0e68225.PNG)
> 
> Hello did you using elsa workflow in your application?

No, I did not. I just added the AutoMapper to my Program file and it solved my problem. You can see the line below.. I hope it helps. 
![ABP](https://user-images.githubusercontent.com/10051037/162266867-7cb52368-df14-46c8-8e07-bff5a4134d53.PNG)
