### ISSUE TITLE
Set 'data-check-form-on-close' after modalClass init

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#12044]
Hi,
I have this scenario:

1.  I use modal with script files like [this](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Modals#modals-with-script-files)
2. In this modal I use `Select2 `input;
3. In this modal I do some logic and I append value to `Select2`:
```
if(true){ //some condition
	var newOption = new Option("Something", "100", true, true);
	// Append it to the select
	$myeSelect2.append(newOption);
	$myeSelect2.val("100");
	$myeSelect2.trigger('change');
}
```
4. But because the check  [data-check-form-on-close](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L76)  is set before the script is loaded/executed, when I try to close the modal without any modification the [AreYouSureYouWantToCancelEditingWarningMessage](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery/jquery-extensions.js#L188) is showed;

I think the  `data-check-form-on-close` check need to be moved after [_modalObject.init](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L122)

The same scenario is happened if I have `datatables` into modal because the `datatables` after load have pagination inputs.

**Comment by maliming** [comment]
hi

Can you share a template project to reproduce this?

**Comment by totpero** [comment]
Ok

**Comment by totpero** [comment]
Hi @maliming . I have created one demo project with this scenario: https://github.com/totpero/abp-test.
On the first page you have Test button.
Press the button and one modal will show.
After no modification in interface, if you press Cancel button you will see the [AreYouSureYouWantToCancelEditingWarningMessage](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery/jquery-extensions.js#L188).

**Comment by maliming** [comment]
After dynamically creating select2, the check here fails, you can customize `$.fn.needConfirmationOnUnsavedClose`

https://github.com/abpframework/abp/blob/309865135a0187bd9a99f77ddea2b6e50bd615ff/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery/jquery-extensions.js#L184

**Comment by totpero** [comment]
This is happen because  the function [$.fn.needConfirmationOnUnsavedClose](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L77 ) is loaded before all modal components is loaded [here](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L117).
The form/modal is loaded only after [modalclass is loaded](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L117), I'm right? 
Then the:
```
 if (_$form.attr('data-check-form-on-close') !== 'false') {
       _$form.needConfirmationOnUnsavedClose(_$modal);
 }
```
I think this need to be moved after the  [modalclass is loaded](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L117)

How can I customize `$.fn.needConfirmationOnUnsavedClose` if I dynamically creating select2 in  [modalclass script](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L117)?

Other solution is to disable the default `data-check-form-on-close` and create my custom modal event and catch on `modalclass is loaded` event and there apply the `_$form.needConfirmationOnUnsavedClose(_$modal);` or not modify the inputs dynamically.

I think the move of the ` _$form.needConfirmationOnUnsavedClose(_$modal);` check after the modalclass is loaded is the best solution.
