### ISSUE TITLE
MVC template virtual file enhancement.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1206]
See: https://github.com/abpframework/abp/issues/1204#issuecomment-499449619

**Comment by 274188A** [comment]
hmm, so is the previous fix no good?

**Comment by ismcagdas** [comment]
@274188A yes, it seems like it didn't fix the problem fully.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/commit/05a8d5a4c9997db953cde45caf6cf4cd27e337e8
