### ISSUE TITLE
Error with tutorial creating BOOK 

### ISSUE THREAD

**Issue by punkouter2018** [abpframework/abp#1208]
````
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'EntityTypeBuilder<Book>' does not contain a definition for 'ConfigureExtraProperties' and no accessible extension method 'ConfigureExtraProperties' accepting a first argument of type 'EntityTypeBuilder<Book>' could be found (are you missing a using directive or an assembly reference?)	abp.EntityFrameworkCore	C:\Users\m3mah02\Downloads\abp\src\abp.EntityFrameworkCore\EntityFrameworkCore\abpDbContextModelCreatingExtensions.cs	27	Active
````

**Comment by hikalkan** [comment]
Try to add `using Volo.Abp.EntityFrameworkCore.Modeling;` to your code file.

**Comment by punkouter2018** [comment]
oops. Put it in CreateingExtensions class instead of the regular dbcontext I realized.

**Comment by punkouter2018** [comment]
Now it runs but the migration strict is empty and it did not add the book table.. :\ 

  public partial class test1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }

**Comment by hikalkan** [comment]
Please share your code. Where did you added your configuration. Are you sure that your migration dbcontext is using the code you have written.

**Comment by punkouter2018** [comment]
I went back and added it to the extensions file but then later ran into another problem getting the datatable to show any data. I will start from scratch and try again tomorrow
