### ISSUE TITLE
Mails from abp.io go to spam

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#12089]
![image](https://user-images.githubusercontent.com/1809172/160178283-0253fe05-b79e-41a3-b1e0-41f3b87c3273.png)
(Outlook)

**Comment by maliming** [comment]
@ismcagdas  Our previous emails to the developers were also marked as spam.

**Comment by ismcagdas** [comment]
@maliming do you have a clue why those emails are marked as spam ? As far as I can check, there is no misconfiguration on email sending side. Even if we do everything propertly, an email can be marked as spam.

**Comment by maliming** [comment]
Different countries or mail providers have different policies. For example, receiving foreign language mail may be considered spam. We can recommend developers set `abp.io` to allowlist.

**Comment by ismcagdas** [comment]
Closing for now since we don't have a clear solution to this. I will track this item internally.
