### ISSUE TITLE
How to set timezone in Hangfire background worker

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#12095]
Currently I don't see any document in docs.abp.io about setting Timezone in BackgroundWorker Hangfire. How can I do that in abp project ?

Thanks

**Comment by maliming** [comment]
hi

I think this is related to `Hangfire`, You can direct use its API.

**Comment by volethanh** [comment]
Hi @maliming ,

I think it is related to Abp because `Hangfire` set the Timezone when we call method `RecurringJob.AddOrUpdate`

<img width="796" alt="Screen Shot 2022-03-28 at 1 51 08 PM" src="https://user-images.githubusercontent.com/46510130/160342483-9f35a29a-a07d-4864-b109-aa983af342bf.png">

But when I looking for it in the sourcecode Abp framework, I only see this

<img width="1154" alt="Screen Shot 2022-03-28 at 1 52 42 PM" src="https://user-images.githubusercontent.com/46510130/160342659-8dd73df5-8c29-43b0-bdbc-3f8f70a366ac.png">

Thanks

**Comment by maliming** [comment]
ok, I see, I will add some options to handle this.
