### ISSUE TITLE
Rabbitmq Disposed connect

### ISSUE THREAD

**Issue by firminoeducbank** [abpframework/abp#12113]
Hi, we have a application have many itens in queue, after many itens in queue and past one hour (+/-) this error ocurred

{
  "Depth": 0,
  "ClassName": "System.ObjectDisposedException",
  "Message": "Cannot access a disposed object.\nObject name: 'RabbitMQ.Client.Impl.AutorecoveringModel'.",
  "Source": "RabbitMQ.Client",
  "StackTraceString": "   at RabbitMQ.Client.Impl.AutorecoveringModel.BasicAck(UInt64 deliveryTag, Boolean multiple)\n   at Volo.Abp.RabbitMQ.RabbitMqMessageConsumer.HandleIncomingMessageAsync(Object sender, BasicDeliverEventArgs basicDeliverEventArgs)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "HResult": -2146232798,
  "HelpURL": null
}

**Comment by maliming** [comment]
hi

Can you share the full error stack?
