### ISSUE TITLE
ExternalLdapLogin

### ISSUE THREAD

**Issue by thanhtai9606** [abpframework/abp#12116]
I already created external Ldap login working fine but
It just working with only first person. Second person get error here!

`AbpIdentityResultException: A user with this login already exists.`
this my set up code

```
`public async override Task<bool> TryAuthenticateAsync(string userName, string plainPassword)
        {
            bool result = false;

            string user_dn = string.Format("becamex\\{0}", userName);
            _connection.Connect(_configuration["LDAP:host"], int.Parse(_configuration["LDAP:port"]));
            _connection.Bind(user_dn, plainPassword);
            result = _connection.Bound;
            if (result)
                _currentUserInfo = GetPersonalInfo(userName, plainPassword);
            _connection.Dispose();
            return await Task.FromResult(result);
        }

        protected override Task<ExternalLoginUserInfo> GetUserInfoAsync(string userName)
        {

            return Task.FromResult(
                new ExternalLoginUserInfo(_currentUserInfo.Username + "@becamex.com.vn")
                {
                    Name = _currentUserInfo.DisplayName, //optional, if the provider knows it
                    Surname = "", //optional, if the provider knows it
                    EmailConfirmed = true, //optional, if the provider knows it
                    TwoFactorEnabled = false, //optional, if the provider knows it
                    PhoneNumber = "0000-000-000", //optional, if the provider knows it
                    PhoneNumberConfirmed = false, //optional, if the provider knows it
                    ProviderKey = "123" //The id of the user on the provider side
                }
              );
        }
        private CurrentUserInfo GetPersonalInfo(string userName, string plainPassword)
        {
            var searchFilter = string.Format(_configuration["LDAP:search_filter"], userName);
            var result = _connection.Search(
                _configuration["LDAP:base_dn"],
                LdapConnection.ScopeSub,
                searchFilter,
                new[] { MemberOfAttribute, DisplayNameAttribute, SAMAccountNameAttribute },
                false
            );
            var user = result.Next();
            if (user != null)

                _currentUserInfo = new CurrentUserInfo
                {
                    DisplayName = user.GetAttribute(DisplayNameAttribute).StringValue,
                    Username = user.GetAttribute(SAMAccountNameAttribute).StringValue
                };
            _connection.Disconnect();
            return _currentUserInfo;
        }
    }
`
```

**Comment by realLiangshiwei** [comment]
Can you provide a project to reproduce?

**Comment by thanhtai9606** [comment]
> Can you provide a project to reproduce?

It just a basic project this is my code in httpHostModule
` Configure<AbpIdentityOptions>(options =>
        {
            options.ExternalLoginProviders.Add<ExternalLoginLdapProvider>(ExternalLoginLdapProvider.Name);
        });
`

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem

**Comment by thanhtai9606** [comment]
> I can't reproduce the problem

This is my code. I just added with first user ldap login, But second user not working, it show error
**AbpIdentityResultException: A user with this login already exists.**
`https://github.com/thanhtai9606/demo_ldap_abp.git`
help me! please

**Comment by realLiangshiwei** [comment]
Hi,

For testing I used the following code and is works fine.

```csharp
    public async override Task<bool> TryAuthenticateAsync(string userName, string plainPassword)
    {
       // always true
        bool result = true;
        
        return await Task.FromResult(result);
    }

    protected override Task<ExternalLoginUserInfo> GetUserInfoAsync(string userName)
    {
        return Task.FromResult(
            new ExternalLoginUserInfo(userName + "@becamex.com.vn")
            {
                Name = userName, //optional, if the provider knows it
                Surname = "", //optional, if the provider knows it
                EmailConfirmed = true, //optional, if the provider knows it
                TwoFactorEnabled = false, //optional, if the provider knows it
                PhoneNumber = "0000-000-000", //optional, if the provider knows it
                PhoneNumberConfirmed = false, //optional, if the provider knows it
               ProviderKey =  Guid.NewGuid().ToString() //The id of the user on the provider side
            }
          );
    }
```

I think there is nothing to do with ABP, you can debug the code to check what is happening.

**Comment by thanhtai9606** [comment]
Please try with 3-4 accounts. It happens with second account over! 🙄

**Comment by realLiangshiwei** [comment]
The id of the user on the provider side, it **should be unique**

Replace `ProviderKey =  "123"` with `ProviderKey =  Guid.NewGuid().ToString()`

**Comment by thanhtai9606** [comment]
Oh. Thank you so much 😍😍😍😍

**Comment by leonkosak** [comment]
@thanhtai9606, would you share your solution (or at least files and configuration) how you implemented External LDAP Login?
Thank you.

**Comment by thanhtai9606** [comment]
> https://github.com/thanhtai9606/demo_ldap_abp.git

sorry, I did not read notify
this is my demo
`https://github.com/thanhtai9606/demo_ldap_abp.git`

**Comment by ShzNet** [comment]
> > https://github.com/thanhtai9606/demo_ldap_abp.git
> 
> sorry, I did not read notify this is my demo `https://github.com/thanhtai9606/demo_ldap_abp.git`

Can you re-up this repo

**Comment by thanhtai9606** [comment]
> > > https://github.com/thanhtai9606/demo_ldap_abp.git
> > 
> > 
> > sorry, I did not read notify this is my demo `https://github.com/thanhtai9606/demo_ldap_abp.git`
> 
> Can you re-up this repo

Sorry I closed it, this is demo code in my project ;
`using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Options;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Guids;
using Volo.Abp.MultiTenancy;
using Microsoft.Extensions.Configuration;
using Volo.Abp.Identity;
using Novell.Directory.Ldap;
using System;

namespace Becamex.ArchiveCenter
{
    public class ExternalLoginLdapProvider : ExternalLoginProviderBase, ITransientDependency
    {
        public const string Name = "Ldap";
        private readonly LdapConnection _connection;
        private readonly IConfiguration _configuration;
        private const string MemberOfAttribute = "memberOf";
        private const string DisplayNameAttribute = "displayName";
        private const string SAMAccountNameAttribute = "sAMAccountName";
        private CurrentUserInfo _currentUserInfo = new CurrentUserInfo();
        public ExternalLoginLdapProvider(IGuidGenerator guidGenerator, ICurrentTenant currentTenant, IdentityUserManager userManager, IIdentityUserRepository identityUserRepository, IOptions<IdentityOptions> identityOptions, IConfiguration configuration)
          : base(guidGenerator, currentTenant, userManager, identityUserRepository, identityOptions)
        {
            _configuration = configuration;
            _connection = new LdapConnection
            {
                SecureSocketLayer = bool.Parse(_configuration["LDAP:ssl"])
            };

        }

        public async override Task<bool> TryAuthenticateAsync(string userName, string plainPassword)
        {

            try
            {
                bool result = false;
                string user_dn = string.Format("demo\\{0}", userName);
                _connection.Connect(_configuration["LDAP:host"], int.Parse(_configuration["LDAP:port"]));
                _connection.Bind(user_dn, plainPassword);
                result = _connection.Bound;
                if (result)
                    _currentUserInfo = GetPersonalInfo(userName, plainPassword);
                _connection.Dispose();
                return await Task.FromResult(result);
            }
            catch (System.Exception)
            {

                return false;
            }
        }

        protected override Task<ExternalLoginUserInfo> GetUserInfoAsync(string userName)
        {

            return Task.FromResult(
                new ExternalLoginUserInfo(_currentUserInfo.Username + "@demo.com.vn")
                {
                    Name = _currentUserInfo.DisplayName, //optional, if the provider knows it
                    Surname = "", //optional, if the provider knows it
                    EmailConfirmed = true, //optional, if the provider knows it
                    TwoFactorEnabled = false, //optional, if the provider knows it
                    PhoneNumber = "0000-000-000", //optional, if the provider knows it
                    PhoneNumberConfirmed = false, //optional, if the provider knows it
                    ProviderKey = Guid.NewGuid().ToString() //The id of the user on the provider side
                }
              );
        }
        private CurrentUserInfo GetPersonalInfo(string userName, string plainPassword)
        {
            var searchFilter = string.Format(_configuration["LDAP:search_filter"], userName);
            var result = _connection.Search(
                _configuration["LDAP:base_dn"],
                LdapConnection.ScopeSub,
                searchFilter,
                new[] { MemberOfAttribute, DisplayNameAttribute, SAMAccountNameAttribute },
                false
            );
            var user = result.Next();
            if (user != null)

                _currentUserInfo = new CurrentUserInfo
                {
                    DisplayName = user.GetAttribute(DisplayNameAttribute).StringValue,
                    Username = user.GetAttribute(SAMAccountNameAttribute).StringValue
                };
            _connection.Disconnect();
            return _currentUserInfo;
        }

        public override Task<bool> IsEnabledAsync()
        {
            return Task.FromResult(true);
        }
    }
    public class CurrentUserInfo
    {
        public string DisplayName { get; set; }
        public string Username { get; set; }
    }
}


`
![2023-04-04_14-26](https://user-images.githubusercontent.com/4544983/229718938-6e6ecbeb-d6cb-4640-a51f-a7836d74ee3a.png)
