### ISSUE TITLE
Provide a proper way to update menu in Blazor without refreshing

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#12118]
Blazor menu can't be updated until the page is refreshed. 

We can provide an API to update it or just register MenuViewModel into the dependency container and it can be replaced and changes will be applied to ui easily.

---

_Originally posted here: https://support.abp.io/QA/Questions/2778/Blazor-Change-Menu-Display-Name-dynamically_

**Comment by sturlath** [comment]
@enisn just saw this issue that is similar to [my issue ](https://support.abp.io/QA/Questions/4144/Blazor-WASM-needs-two-loads-F5-to-show-side-menus) except that ours just happens when logging in for the first time and no dynamic loading going on. Was some change done regarding this to prepare for this task that we missed in the update?

**Comment by sturlath** [comment]
@enisn can I understand you 👍 as there is an issue with 6.0.1?

**Comment by enisn** [comment]
It might be related to `IsExpandedPropertyName` bindable property.

If the node binding context (nodes in viewmodel) doesn't have a property named `IsExpanded`, expand state couldn't be kept.

Can you provide a simple code example to reproduce the issue?

**Comment by tvddev** [comment]
@hikalkan - is it possible to get this in 7.1 it has been open almost 1 year and is really core for a modern broswer app.

**Comment by RelevanceRo** [comment]
@sturlath how did you solve your problem with the menu not rendering when logging in, only after a refresh? Mine still raging. Wasn't able to solve it even with a support from ABP. Same config as you: Blazor WASM.

Thanks a bunch for any tips!

Catalin

**Comment by enisn** [comment]
There is an API for each theme that allows you replace one single menu item with your custom component:
https://github.com/abpframework/abp/blob/dev/docs/en/UI/Blazor/Basic-Theme.md#overriding-the-menu-item

---

```csharp
context.Menu.Items.Add(
  new ApplicationMenuItem("Custom.1", "My Custom Menu", "#")
    .UseComponent(typeof(MyMenuItemComponent)));
```
