### ISSUE TITLE
Support efcore 6 compilation model startup

### ISSUE THREAD

**Issue by zr53722** [abpframework/abp#12117]
https://docs.microsoft.com/zh-cn/ef/core/what-is-new/ef-core-6.0/whatsnew#compiled-models

The latest version does not support compiled models

Extraproperties will report an error

When the entity reaches 200, the first access becomes particularly slow

**Comment by realLiangshiwei** [comment]
> [Global query filters are not supported](https://github.com/dotnet/efcore/issues/24897).

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#limitations

ABP uses global query filters, and it's only the first time slow, I don't think it's necessary.

**Comment by zr53722** [comment]
> > [Global query filters are not supported](https://github.com/dotnet/efcore/issues/24897).
> 
> https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#limitations
> 
> ABP uses global query filters, and it's only the first time slow, I don't think it's necessary.

我当时也认为没必要，但是当项目规模到达以后，每次CI/CD的第一次访问都将变得很慢，这在团队中造成了很不好的影响，特别是测试一直认为就是有问题的，微软也已经认识到了这个问题，在EFCORE6.0的版本，提出了解决方案，只是在ABP支持的不是特别好，我还是希望ABP 在后面的版本解决这个问题

**Comment by zr53722** [comment]
abp中对这个支持不太友好，主要是提现在扩展属性和时间类型上，不过扩展属性可以忽略搞定，但是时间类型需要不管时区才能进行下去，这对一些需要管理时区的应用不太友好，并且还需要一些特殊的处理才能达到优化的需求，总之条件限制比较多，有兴趣可以和我沟通
