### ISSUE TITLE
ElasticSearch & LogStash docker-compose errors

### ISSUE THREAD

**Issue by dcagnetta** [abpframework/abp#1211]
Error when running ` docker-compose up -d` in `Microservices Demo` sample. 

_`Docker Version:           18.09.2`_

`ERROR: for logstash  Cannot start service logstash: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/Samples/abp/samples/MicroserviceDemo/elk/logstash/config/logstash.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/65a820a2d9675047469afeb49bd25a5b325d7da96daa0fe057198ef8f0add248/merged\\\" at \\\"/var/lib/docker/overlay2/65a820a2d9675047469afeb49bd25a5b325d7da96daa0fe057198ef8f0add248/merged/usr/share/logstash/config/logstash.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is`

`
ERROR: for elasticsearch  Cannot start service elasticsearch: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/Samples/abp/samples/MicroserviceDemo/elk/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/c4e416a2842d5b398f25d9befaec1358182f83d694785e2e2b0196d9248af826/merged\\\" at \\\"/var/lib/docker/overlay2/c4e416a2842d5b398f25d9befaec1358182f83d694785e2e2b0196d9248af826/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
`

**Solution**
in `docker-compose.override.yml` update to remove filenames:
`- ./elk/elasticsearch/config/:/usr/share/elasticsearch/config/elasticsearch.yml:ro` 
becomes
`- ./elk/elasticsearch/config/:/usr/share/elasticsearch/config:ro`

more than happy to submit the PR

**Comment by ismcagdas** [comment]
@dcagnetta PR would be great 😄

**Comment by dcagnetta** [comment]
Apologies, this is not a problem

[Solution here](https://github.com/docker/for-win/issues/1560#issuecomment-380393488)

**Comment by johnnba** [comment]
I got the same error as you encountered, however i worked with the docker tool box. 
but the solution you referenced above couldn't solve my problem.
so it should be a problem.  can you tell me how do you solve the problem finally?

`ERROR: for elasticsearch  Cannot start service elasticsearch: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \
\\"/e/Projects/Makop/abp/samples/MicroserviceDemo/elk/elasticsearch/config/elasticsearch.yml\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/d4e74828aefa463eb328461e73e62512e8143a4a97553e927ed29c5cc33a7880/merg
ed\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/d4e74828aefa463eb328461e73e62512e8143a4a97553e927ed29c5cc33a7880/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you
 trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`
