### ISSUE TITLE
AbpCachingStackExchangeRedisModule not working

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#12125]
- ABP Framework Version: 5.1.4
- User Interface:Angular
- Database Provider: EF Core

I followed [official doc](https://docs.abp.io/en/abp/latest/Redis-Cache)
I configured redis, in appsettings.json like
"Redis": { "IsEnabled": "true", "Configuration": "server ip,password=*******" }
and add nuget package Volo.Abp.Caching.StackExchangeRedis into my module.

![1111](https://user-images.githubusercontent.com/35516482/160732820-c38981b3-cc5f-4ecf-9f52-e4ca3b6f9d36.png)

I use IDistributedCache interface to set/get value from redis, but I get null and the error. Could you help me?
```
ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)
   at Volo.Abp.Caching.DistributedCache`2.<>c__DisplayClass51_0.<<SetAsync>g__SetRealCache|0>d.MoveNext()
```

**Comment by realLiangshiwei** [comment]
What Redis version are you using?

Please provide full steps to reproduce, thanks.

**Comment by realLiangshiwei** [comment]
Also, can you try using a simple project without ABP to test?

**Comment by wangyue20075** [comment]
I also encountered this problem. Can you solve this problem ?

**Comment by ArcherTrister** [comment]
> Also, can you try using a simple project without ABP to test?

Yes, I've already done it and it works

simple project: [RedisCache](https://cdn-1255895673.cos.ap-chengdu.myqcloud.com/GithubDemo/RedisCache.rar)

abp project: [AbpRedisCache](https://cdn-1255895673.cos.ap-chengdu.myqcloud.com/GithubDemo/AbpRedisCache.rar)

**Comment by ArcherTrister** [comment]
> What Redis version are you using?
> 
> Please provide full steps to reproduce, thanks.

@realLiangshiwei 

Redis version:
![image](https://user-images.githubusercontent.com/35516482/160745850-b249ed92-def3-4c44-afe0-35af09e41e84.png)
![image](https://user-images.githubusercontent.com/35516482/160745883-017785af-dbc8-43a1-9a67-1c13d6f66571.png)

**Comment by realLiangshiwei** [comment]
Please use the latest version of Redis

**Comment by ArcherTrister** [comment]
> Please use the latest version of Redis

thanks you, when i use redis6, it's ok

**Comment by wangyue20075** [comment]
This is a problem with the Windows version redis . Linux is ok , thanks !
