### ISSUE TITLE
extraProperties not saved as expected

### ISSUE THREAD

**Issue by lgadola** [abpframework/abp#12122]
**abp** 5.1.4
EFCore/Angular

Trying to save extraProperties in an extensible Object. This test fails:
```
       [Fact]
        public async Task InsertAndFetchEventType()
        {
            var evt = await _eventTypeAppService.CreateAsync(new EventTypeDto
            {
                OrganizationUnitId = _testData.OU1Id,
                Title = "Event Type 1",
                Key = "Type1",
                MinParticipants = 1,
                MaxParticipants = 10
            });
            evt.SetProperty("AdditionalData", "Test");
            evt = await _eventTypeAppService.UpdateAsync(evt.Id, evt);
            evt.ShouldNotBeNull();
            evt.GetProperty<string>("AdditionalData").ShouldBe("Test");
        }
```

 Message: 
Shouldly.ShouldAssertException : evt.GetProperty<string>("AdditionalData")
    should be
"Test"
    but was
null

Domain Object EventType implements IHasExtraProperties
EventTypeDto is ExtensibleEntityDto
_eventTypeAppService is standard CrudAppService<...>

Am I doing anything wrong?

**Comment by realLiangshiwei** [comment]
Can you check this? https://docs.abp.io/en/abp/latest/Object-Extensions#automapper-integration

**Comment by lgadola** [comment]
I have a mapping like this:

`
        CreateMap<EventType, EventTypeDto>()
            .MapExtraProperties();
        CreateMap<EventTypeDto, EventType>()
             .ForMember(dest => dest.TenantId, opts => opts.Ignore())
             .ForMember(dest => dest.LastModificationTime, opts => opts.Ignore())
             .ForMember(dest => dest.LastModifierId, opts => opts.Ignore())
             .ForMember(dest => dest.CreationTime, opts => opts.Ignore())
             .ForMember(dest => dest.CreatorId, opts => opts.Ignore())
             .MapExtraProperties();
`

repository is [here](https://github.com/lgadola/Abp.Test)

**Comment by realLiangshiwei** [comment]
I will check it

**Comment by realLiangshiwei** [comment]
Hi,

Because you missed the `Object Extension Manager` configure  https://docs.abp.io/en/abp/latest/Object-Extensions#object-extension-manager.

If you want to dynamically set extra properties, you can remove the `MapExtraProperties()`

![image](https://user-images.githubusercontent.com/16813853/160961057-155354fc-f841-4123-bd02-d7ab7817b9bc.png)

![image](https://user-images.githubusercontent.com/16813853/160961125-97b15502-9793-4b75-98df-320b80c8b75b.png)
