### ISSUE TITLE
Making an Non-Table Ajax call - Is there an Abp helper function?

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#1212]
I request json data for a chart (Chart.js).  

Here is my url

`https://locahostl:449/api/app/measurementGroup/Value1Chart',`

I'm looking for a way to make this call  so i do not have to hard code the server & port.

I see there is already a `abp` helper function used for populating **Tables**:

```
 ajax: abp.libs.datatables.createAjax(ticToc.sites.site.getList),
```

Is there a hep or similar for other data?

Thanks!

**Comment by 274188A** [comment]
for now i'm getting by with:

 ```
 var baseUrl = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ":" + window.location.port : "");
        var serviceUrl = "/api/app/measurementGroup/Value1Chart";



        $.ajax({
            url: baseUrl + serviceUrl,
            method: "GET",
            dataType: "json",
            success: function (data) {

<snipped/>

```

**Comment by hikalkan** [comment]
Did you try `abp.ajax`? https://github.com/abpframework/abp/blob/master/npm/packs/jquery/src/abp.jquery.js#L92

It also handles errors. Simple usage:

````js
abp.ajax({
  url: abp.appPath + "api/app/measurementGroup/Value1Chart"
}).done(function(result) { 
  //...
});
````

BTW, I think no need to calculate a baseUrl.
