### ISSUE TITLE
Multitenancy: When switching tenant in frontend, ICurrentTenant in backend is not currrent

### ISSUE THREAD

**Issue by lgadola** [abpframework/abp#12139]
**abp** Version 5.1.4
Angular/efCore

In a multitenancy application, I switch the tenant client-side using TypeScript:
SessionStateService.setTenant()

Network requests to the application service then correctly send new tenant id in request header:
__tenant: 5a947ffc-e363-e204-aa0d-3a0294c68d1a

In application service, however ICurrentTenant shows old tenant (from requests beforehand), therefore not returning correct data.

`    public class EventTypeAppService : CrudAppService<EventType, EventTypeDto, Guid, EventTypeRequestDto, EventTypeDto, EventTypeDto>, IEventTypeAppService
    {
        public EventTypeAppService(IEventTypeRepository repository, 
            ICurrentTenant tenant)
            : base(repository)
        {
            Console.WriteLine($"tenant Id: {tenant.Id}, name: {tenant.Name}");
        }
`

**Comment by maliming** [comment]
hi

Is the current user logged in?

**Comment by lgadola** [comment]
Yes it is

**Comment by maliming** [comment]
> CurrentUserTenantResolveContributor: Gets the tenant id from claims of the current user, if the current user has logged in. **This should always be the first contributor for the security.**

https://docs.abp.io/en/abp/latest/Multi-Tenancy#default-tenant-resolvers


You can change the tenant manually.

https://docs.abp.io/en/abp/latest/Multi-Tenancy#change-the-current-tenant

**Comment by lgadola** [comment]
yes but I would expect CurrentUserTenantResolveContributor to set the tenant automatically to what is in the request header under __tenant so that tenant filter is applied correctly for out-of-the-box application services

**Comment by maliming** [comment]
This is by design, You can change it to your needs.

**Comment by hikalkan** [comment]
CurrentUserTenantResolveContributor has always priority for security reasons. otherwise, any authenticated user can send a different tenantid to read/write other tenant's data even with authorized endpoints.
