### ISSUE TITLE
An error occurred while generating the client proxy for microservice/angular

### ISSUE THREAD

**Issue by bmzhe** [abpframework/abp#12132]
step:

1. abp suite
2. create new microservice solution
3. ./run-tye.ps1
4. ./apps/angular/ run abp generate-proxy -t ng 

No changes have been made to the generated code。

error: **[Invalid Module] Backend module "productService" does not exist in API definition.**

env:
mac os/ abp commercial / abp cli: 5.2.0-RC.2/ abp suite: 5.2.0-RC.2

**Comment by gterdem** [comment]
Please use https://support.abp.io for commercial module and template questions.

Thank you.
