### ISSUE TITLE
Updating AutoMapper to v11

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#12144]
Staying v10 can create some compatibility issues such as [this issue](https://support.abp.io/QA/Questions/2813/Automapper-version-11-compatibility)

**Comment by maliming** [comment]
https://docs.automapper.org/en/latest/11.0-Upgrade-Guide.html

**Comment by maliming** [comment]
These are big break changes, and many projects have to be changed to `Net Standard 2.1`.

**Comment by enisn** [comment]
> These are big break changes, and many projects have to be changed to `Net Standard 2.1`.

What do you think @hikalkan ?

**Comment by hikalkan** [comment]
@maliming I've assigned this to @realLiangshiwei 

I think we can change only the necessary projects to .netstandard2.1 and leave others with .netstandard2.0. We can change application layers of modules to .net6, if they are .netstandard.
