### ISSUE TITLE
Scroll not visible

### ISSUE THREAD

**Issue by marcelo-maciel** [abpframework/abp#1214]
On docs module if the page have vertical scroll and content have horizontal scroll, the horizontal scroll initially not visible.

Sample:
https://abp.io/documents/abp/latest/Contribution/Localization-Text-Files

![image](https://user-images.githubusercontent.com/4993482/59084190-9839a300-88d0-11e9-8cdd-9145498e62ba.png)

Only after scrolling vertical the horizontal scroll is visible.
![image](https://user-images.githubusercontent.com/4993482/59084168-83f5a600-88d0-11e9-9112-01fd4b32f67c.png)

**Comment by hikalkan** [comment]
You're right. Actually this is an edge case. We normally shouldn't have such long single line texts.
We will look that what we can do. Thanks.
