### ISSUE TITLE
How do I set RabbitMQ max retry attempts to prevent an unhandled exception infinite loop?

### ISSUE THREAD

**Issue by JeffreyMcJeffFace** [abpframework/abp#12140]
ABP 5.1.3
.NET Core

To Reproduce:
1. Configure ABP to use the distributed event BUS
2. In an event handler, throw an unhandled exception
3. Message will automatically return NACK to RabbitMQ and message will requeue
4. Handler consumes message and throws same exception endlessly.

Background:
- [#7657](https://github.com/abpframework/abp/issues/7657) discussed this exact situation. 
- [#8829](https://github.com/abpframework/abp/pull/8829) introduced an event bus error handler and n AbpEventBusOptions retry strategy. Presumably after x number of NACKs, a message would move to the dead letter queue.
- [#10034](https://github.com/abpframework/abp/issues/10034) appears to have removed this retry system.

I am aware that the infinite exception loop described can be corrected with proper exception handling. In our case, a dev did not have the handling properly setup, and the infinite loop occurred subsequently crashing our dev environment when at least 2.5 million loops occurred before we hit some log storage limits. 

RabbitMQ supports max retry attempts. Is there a way for this to be configured in ABP? Ideally after x number of NACKs, the message would move a dead letter queue and no longer attempt delivery. (We assumed this configuration option existed, and then we would implement a consumer on the dead letter queue to consume failed messages and create logs and/or raise alerts.)

Again, we definitely screwed up here by not having correct exception handling, but is there some ABP-level configuration of RabbitMQ to prevent this relatively easy situation from occurring?

**Comment by realLiangshiwei** [comment]
Hi,

You can use policy to bind a dead exchange & queue: https://www.rabbitmq.com/parameters.html

Then replace the RabbitMqMessageConsumer, the message will be forwarded to the dead letter queue.

```csharp
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(RabbitMqMessageConsumer), typeof(IRabbitMqMessageConsumer))]
public class MyRabbitMqMessageConsumer : RabbitMqMessageConsumer
{ 
    //....

    protected async override Task HandleIncomingMessageAsync(object sender, BasicDeliverEventArgs basicDeliverEventArgs)
    {
        try
        {
            foreach (var callback in Callbacks)
            {
                await callback(Channel, basicDeliverEventArgs);
            }

            Channel.BasicAck(basicDeliverEventArgs.DeliveryTag, multiple: false);
        }
        catch (Exception ex)
        {
            try
            { 
               // to dead queue
                Channel.BasicNack(
                    basicDeliverEventArgs.DeliveryTag,
                    multiple: false,
                    requeue: false
                );
            }
            // ReSharper disable once EmptyGeneralCatchClause
            catch { }

            Logger.LogException(ex);
            await ExceptionNotifier.NotifyAsync(ex);
        }
    }
}
```
