### ISSUE TITLE
About to launch Free Course on abp

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1215]
So I have been playing with abp.io and I know its in preview. I have been working on courses and tutorials based on the docs. I have learnt heaps over the last one month, If you are interested head to https://amazingsolutions.teachable.com/ and signup to get notified when it is live.

**Comment by hikalkan** [comment]
I registered :)

I suggest you to wait for v0.18 which will be released ~14th Jun, because we will have changes on the startup template, it will be completely different and ABP CLI will be the default way to create a new project.

However, if you want to try new template today, I can create a new project for you in my local. Just send me an email over `info @ abp.io`

**Comment by vnetonline** [comment]
I have sent you an email Halil thanks for reaching out

**Comment by hikalkan** [comment]
Haven't got your email. Can you try to forward it to `info@volosoft.com`? Thanks.

**Comment by vnetonline** [comment]
Okay just sent it again

Vineet Belani
+61 402 263 321

________________________________

**Comment by hikalkan** [comment]
Got it, thanks :)

**Comment by vnetonline** [comment]
Dear @hikalkan 

Did you get my last email regarding redis ?

Also the source doesn't build I have commented out the localization line as suggested in your medical but I can't run the solution.

An you please kindly reply to my email I need your help to finalise this course and launch it

**Comment by vnetonline** [comment]
Guys i have just published the first Tutorial at https://amazingsolutions.teachable.com

Okay go easy on me this is my first time I have done something like this and published a recording in public domain

- **How to get a free Azure Account and login to Azure Portal**

More videos to be uploaded over the weekend. Be sure to signup and enroll to be notified of courses and tutorials as I release them.

**Comment by vnetonline** [comment]
Okay guys I just uploaded the second tutorial at https://amazingsolutions.teachable.com this one is not scripted. I have recorded this one wart's and all, meaning it is done one the fly.

Let me know which one you prefer.

- **Configuring your Windows 10 Free Virtual Machine**

More videos to be uploaded over the weekend. Be sure to signup and enroll to be notified of courses and tutorials as I release them

**Comment by hikalkan** [comment]
Sorry for my late response, was working on the [ABP v0.18 release](https://blog.abp.io/abp/Abp-CLI-Templates-v0_18_0-Release).

>Did you get my last email regarding redis

No, please send it to info@volosoft.com again.

Viodes seem nice, while I haven't watched them yet.

**Comment by vnetonline** [comment]
I just uploaded the third tutorial at https://amazingsolutions.teachable.com. You will have to enroll in the course to access the third tutorial

- **Connecting to your Azure Virtual Machine and installing Chrome**

This third video complete the 1st Section "Getting Started" in the next section we will install the rest of the tools needed to build Amazing Solutions with the abp Framework.

**Comment by vnetonline** [comment]
I just uploaded three more tutorials at https://amazingsolutions.teachable.com. 

- **Installing the Visual Studio Community Edition 2019**
- **Installing of Java JRE 8u212 & SQL Server 2017 Developer Edition**
- **Installing Github Desktop**

You will have to enroll in the course to access the these tutorial. Two more tools to go and then we will shift gears and learn how to spin up a New Project using the ABP CLI which was released in 0.18.0.0

**Comment by vnetonline** [comment]
I just completed the second section "Installing the developer tools" 
 check it out at https://amazingsolutions.teachable.com.

- **Installing the Visual Studio Community Edition 2019**
- **Installing of Java JRE 8u212 & SQL Server 2017 Developer Edition**
- **Installing Github Desktop**
- **Installing Node.js v10.16.0 LTS Version**
- **Installing Yarn**
- **Installing Visual Studio Cod**e
- **Installing FileZilla Client**
- **Installing Postman**

You will have to enroll in the course to access the these tutorials. Now I am going to shift gears and record how to spin up a New Project using the ABP CLI which was released in 0.18.0.0

**Comment by vnetonline** [comment]
I just published the first tutorial which shows you how to use the ABP CLI to create a new ABP web application project and then goes through the structure of the project 
check it out at https://amazingsolutions.teachable.com/p/setting-up-your-development-environment-for-abp

- **Creating a new ABP Web Application project using the ABP CLI**

You will have to enroll in the course to access the these tutorials. Let me know your thoughts i am not the type of instructor to use power point slides. let me know if you prefer the explanation using slides.

**Comment by vnetonline** [comment]
Guys I have unpublished the following tutorial because some videos were not in sync and I wasn’t entirely happy with the video content so recording the video to be much more relevant to the voice over 

- **Creating a new ABP Web Application project using the ABP CLI**

Just want to apologise for the inconvenience caused

**Comment by vnetonline** [comment]
Guys its back published the the video is now in sync with the audio check it out at https://amazingsolutions.teachable.com/p/setting-up-your-development-environment-for-abp

- **Creating a new ABP Web Application project using the ABP CLI**

Tomorrow i will be recording "Creating a new tiered ABP Web Application project using the ABP CLI"

**Comment by vnetonline** [comment]
Guys I have published the following tutorials today we are almost at the end of this course.

Enroll now at https://amazingsolutions.teachable.com/p/setting-up-your-development-environment-for-abp

- **Creating a new ABP Web Application project using the ABP CLI**
- **Building and running the default ABP Web Application project using ABP CLI**
- **Creating building and running ABP Web Application tiered project using ABP CLI**

Tomorrow I will be recording "Creating a new ABP module template using the ABP CLI"

**Comment by vnetonline** [comment]
Guys I have published the Final tutorial in the course "Setting up your development environment for ABP vNext Framework"

Enroll now at https://amazingsolutions.teachable.com/p/setting-up-your-development-environment-for-abp

- **Summary and the ABP Architecture Explained**
