### ISSUE TITLE
Bug: Minor spelling mistake

### ISSUE THREAD

**Issue by kfrancis** [abpframework/abp#12152]
https://github.com/abpframework/abp/blob/fd0ce7f556d873e16bd2959172d18f51dd59100c/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectModification/SolutionModuleAdder.cs#L103

Should be "retrieving"

![22-04-vkw2y-1648831424](https://user-images.githubusercontent.com/67574/161306815-ff61ecfd-2492-42b8-bf54-364600b026c9.png)

**Comment by braim23** [comment]
https://github.com/abpframework/abp/pull/12156
