### ISSUE TITLE
make method `OnMessageReceived` in `UiMessageAlert` component virtual

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#12151]
In order to replace blazor default message alert component with others(e.g. SweetAlert), I have to inherit the `UiMessageAlert` component and override the `OnMessageReceived`, but it is not virtual currently.

can we make bellow method virtual?
https://github.com/abpframework/abp/blob/af16644159e01c7cb2154ba40b0cb58e6f8d8674/framework/src/Volo.Abp.BlazoriseUI/Components/UiMessageAlert.razor.cs#L89-L98
or add a virtual method to show the message alert, and we can override it in the future, like:
```cs
private async void OnMessageReceived(object sender, UiMessageEventArgs e)
{
    MessageType = e.MessageType;
    Message = e.Message;
    Title = e.Title;
    Options = e.Options;
    Callback = e.Callback;

    await ShowMessage();
}

protected virtual Task ShowMessage()
{
    return InvokeAsync(ModalRef.Show);
}
```

Personally, I like the second option

**Comment by maliming** [comment]
hi

You can open the PR. :)
