### ISSUE TITLE
URL Params "code" or "state" auto redirect

### ISSUE THREAD

**Issue by gihnih** [abpframework/abp#12178]
ABP version = 5.1.4
User Interface = Angular
DB = EF Core

I have an angular application and trying to get code from other applications.
Redirect from other applications with two-parameter in URL. --> http://localhost:4200/getKey?state=1&code=<Guid>
Angular application redirect to original URL ---> http://localhost:4200/getKey

How do I want to get the value "state" and "code"?

Thanks

**Comment by 543787366** [comment]
@gihnih Maybe this can help

**Comment by 543787366** [comment]
https://stackoverflow.com/questions/69181162/angular-how-to-grab-query-params-from-redirect-url?msclkid=704d95f1cee411ec939149d09c08f1d8
@gihnih Maybe this can help

**Comment by Joncyzx** [comment]
I have the same problem
