### ISSUE TITLE
VoloDocs combobox for language in conflict with site culture

### ISSUE THREAD

**Issue by Xeevis** [abpframework/abp#1217]
New combobox on VoloDocs for changing documentation language won't change the site culture. This is causing differences in JSON vs markdown files where each is a different language.

![image](https://user-images.githubusercontent.com/5835044/59161364-1ae57c80-8ae2-11e9-8dc9-57cebc72f1a0.png)

**Comment by maliming** [comment]
If this is reasonable, I have already implemented it simply.
https://github.com/abpframework/abp/commit/a4eb1f06ccc4c129bc548c325b5fc5a2794e5110#diff-900315eaf275f047924828bf286a7fbfL110

**Comment by Xeevis** [comment]
Ideally culture should be determined from selected docs language so it stays in sync, proposed solution still has 2 problems:
1) If Chinese is set by main website on same domain `http://localhost:55019/` and docs have English as default `http://localhost:55019/abp` it will result in same problem where docs are English, but JSON files are Chinese.
2) Same desync would happen with browser back button after language is changed
