### ISSUE TITLE
Feature Request: Audit Log Info Separation per Unit Of Work

### ISSUE THREAD

**Issue by gdunit** [abpframework/abp#12184]
I have a use case where I will update multiple root entities together in a batch.

Each entity needs to have its own separate audit trail records, which are retrieved by taking each AuditLogInfo where at least one entity change record matches the identity and type name of the item in question before displaying the records to the user.
This is necessary because there may be separate child entities which are also audited for changes and belong to the root, but are returned in the query for the parent's AuditLogInfo.

The problem is that changing in bulk includes all root entities that were created or updated in the transaction and their audited children in the same AuditLogInfo, so the user sees records which are not relevant to the one they are viewing.

In the previous ASP.Net Boilerplate, I could create a separate unit of work for each individual entity that is changed and this, while perhaps inefficient from an I/O perspective, would isolate the audit records when created or updated in bulk.

However in abp.io I cannot seem to use the UnitOfWork(requiresNew: true) to achieve this.
The documentation states that "An audit log object is created for each web request by default". However I cannot see a way to override this.

Could this be considered as a feature request in the future?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAuditingMiddleware.cs#L46

**Comment by gdunit** [comment]
Thank you very much @maliming  - for future reference if it is useful to anyone, it was only a case of:
- Injecting the AuditManager into the app service
- Creating a scope within the loop of each item is to be created:

``` 
foreach (var item in itemsToUpdate)
  {
  using (var saveHandle = _auditingManager.BeginScope())
    {
        try
        {
            await UpdateAsync(item.Id, item);
        }
        catch (Exception ex)
        {
            _auditingManager.Current.Log.Exceptions.Add(ex);
            throw;
        }
        finally
        {
            await saveHandle.SaveAsync();
        }
    }
}
```
