### ISSUE TITLE
Bulk operations and optimistic concurrency

### ISSUE THREAD

**Issue by nev-21** [abpframework/abp#12185]
### Discussion about the framework (Bulk & concurrency)
ABP Framework version 5.1.3.
EfCore Npgsql

### Bulk operations and optimistic concurrency

https://docs.abp.io/en/abp/latest/Repositories#bulk-operations 

> Optimistic concurrency control may not be possible when you use UpdateManyAsync and DeleteManyAsync methods.

I have a few questions about that.

**1. Considering the following UpdateManyAsync method:**

https://github.com/abpframework/abp/blob/5.1.3/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/EfCoreRepository.cs#L160
- When BulkOperationProvider is null, UpdateRange just change the entities state to Modified, so, in this case the optimistic concurrency would not be affected at all, right? 
- I think it will not be affected, because UpdateConcurrencyStamp method is still called. Am I right?
https://github.com/abpframework/abp/blob/5.1.3/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L329

**2. The BulkOperationProvider:**
https://github.com/abpframework/abp/blob/5.1.3/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/EfCoreRepository.cs#L84

- The docs say that the developer "can override the logic via implementing IEfCoreBulkOperationProvider", that makes me think that a default implementation exist.  https://docs.abp.io/en/abp/latest/Entity-Framework-Core#customize-bulk-operations
- A default implementation exist? 
- or "override the logic" refers to the `if (BulkOperationProvider != null)` in the UpdateManyAsync  method?

**3. Optimistic concurrency not possible**

- So, when the optimistic concurrency is not possible with UpdateManyAsync or DeleteManyAsync?

**Comment by maliming** [comment]
> A default implementation exist?

No, You need to add such service like `MyCustomEfCoreBulkOperationProvider`

> When BulkOperationProvider is null, UpdateRange just change the entities state to Modified, so, in this case the optimistic concurrency would not be affected at all, right?
I think it will not be affected, because UpdateConcurrencyStamp method is still called. Am I right?

Can you use a unit test to reproduce this problem?

**Comment by nev-21** [comment]
Thanks @maliming

Since BulkOperationProvider doesn't have a default implementation, the UpdateRange put all entries state as Modified, so concurrency will work.
I will try to find free time to do the test.
