### ISSUE TITLE
Hello when I update from 5.2 preview to 5.2 release in angular

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#12193]
ERROR Error: Uncaught (in promise): Error: Type NgxValidateCoreModule does not have 'ɵmod' property.

**Comment by muhammedaltug** [comment]
Have,

Do you still have this error? Can you try removing the node_modules folder and reinstall it with `yarn install`?

**Comment by xiongjx** [comment]
Me Too!
5.2.2
Angular
Commercial Version
