### ISSUE TITLE
Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'

### ISSUE THREAD

**Issue by Sinodon** [abpframework/abp#12190]
IdentityServer
An unhandled exception occurred while processing the request.
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'!
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List<BundleTagHelperItem> bundleItems, string bundleName)

**Comment by maliming** [comment]
Run `abp install-libs` in your project folder.

**Comment by brunobertechini** [comment]
Could you please provide more info on what it does? We are having this exception when we publish our solution using docker.

Is this `abp install-libs` command required as part of CI to actually build an usable docker image?

**Comment by maliming** [comment]
Install NPM Packages for MVC / Razor Pages and Blazor Server UI types.

It will run automatically after creating a project by CLI.

You can build a docker image after this command. only need onece.

**Comment by 9200237** [comment]
An unhandled exception occurred while processing the request.
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'!
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List<BundleTagHelperItem> bundleItems, string bundleName)

In 5.3.1, I solved it. 
1.It is possible that after you run abp install-libs, the liBS package already exists, which can be found in the xxx.web project and xxx.httpapi.Host project. If you can't find it, you can manually copy the LIBS folder in the ABP project downloaded from the official website.
2. Once you have found the libs.zip or libs folder, copy the libs folder into the wwwroot folder of the xxx. Web project and rerunce the project. As of 5.3.1, the wwwroot folder is no longer available under the xxx. httpapi. Host project. If you have an older version, you may be able to put it under this project.
So run abp install-libs is not a cure-all. Sometimes you may need to manually copy the libs folder. Sometimes run abp install-libs gives you libs.zip, which you need to unzip.

**Comment by 9200237** [comment]
本人实验时用的abp5.3.1

关于ABP新建项目初始运行提示错误：Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'!  的解决方案。
1、网上通常说的解决方案是 在项目根目录CMD运行  abp install-libs  命令安装最小依赖。这种方法可能在以前的版本管用，但是在我这里不管用。 
2.可能是你运行abp install-libs后，libs包已经存在，可以在xxx.web项目和xxx.httpapi.Host项目中找到。如果找不到，可以手动复制官网下载的ABP项目中的LIBS文件夹。
3. 找到 libs 文件夹后，将 libs 文件夹复制到 xxx.Web项目的 wwwroot 文件夹中，重新运行该项目。在5.3.1中，wwwroot 文件夹在 XXX.HttpApi.Host项目中没有了，如果你是旧版本，你也许可以把它放在这个项目下。
所以运行 abp install-libs 并不是万能的。有时您可能需要手动复制 libs 文件夹。
