### ISSUE TITLE
Some pages we developed with .net core 5.0 do not open

### ISSUE THREAD

**Issue by ilkertastan** [abpframework/abp#12204]
Abp framework 5.0
MVC
EF CORE

Hello, when we run the project through visual studio, all links and localization work smoothly, but when we run the project over the domain, some links give 404.  it also does not define the localization to the abp script.  Can you help with this issue?  what should i do?

**Comment by gterdem** [comment]
Some of the Razor/MVC pages are working correctly on the development environment (kestrel) but not working when you have published? Do I understand correctly?

If that's the case, it may be related to nginx, ingress, load balancer, etc.

Please share your production environment and also **related application logs** when you make the request and received 404.

**Comment by ilkertastan** [comment]
@gterdem  Let me tell you this. All pages are working when debugging with visual studio. When I run it over the domain, some links work and some give 404. For example ; "/Definitions/Cities" this page works fine, while "/Definitions/Currencies" this page does not.
