### ISSUE TITLE
Abp Suite

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#12201]
Abp Suite in V5.2
Generate Api of get list with navigation properties if entity has, but the generated proxy in angular generate service using EntityDto
`XXXXService.getList()` it should return EntityWithNavigationPropertiesDto. it sollved by Generate Proxy Manulally and update the front end component   html and ts.
Regards

**Comment by EngincanV** [comment]
For Commercial Support, please use the [support website](https://support.abp.io/QA/Questions).

**Comment by awahbahplana** [comment]
I just highlight the bug for you! 

if I post any bug there it is from my supporting tickets, and its general bug.

**Comment by yekalkan** [comment]
@awahbahplana We refund your ticket credit if it is a general bug.
