### ISSUE TITLE
OnGetExternalLoginCallbackAsync - never creates a user for external login

### ISSUE THREAD

**Issue by pjkeukens** [abpframework/abp#12217]
* Version: 5.2.
* MVC
* EF Core
* OnGetExternalLoginCallbackAsync (modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs)
* Never creates a new user

After signing in a user by using external login (in this case to AzureAD using openid connect) and the result is a succes and it's a new user the code never creates a new user. On success the code after the if(result.Succeeded) is never called becuase it redirects to return url.

Looks like the if(result.Succeeded) and the redirect should just be removed.

            ```

            if (result.Succeeded)
            {
                return RedirectSafely(returnUrl, returnUrlHash);
            }

            var email = loginInfo.Principal.FindFirstValue(AbpClaimTypes.Email);
            if (email.IsNullOrWhiteSpace())
            {
                return RedirectToPage("./Register", new
                {
                    IsExternalLogin = true,
                    ExternalLoginAuthSchema = loginInfo.LoginProvider,
                    ReturnUrl = returnUrl
                });
            }

            var user = await UserManager.FindByEmailAsync(email);
            if (user == null)
            {
                user = await CreateExternalUserAsync(loginInfo);
            }
            else
            {
                if (await UserManager.FindByLoginAsync(loginInfo.LoginProvider, loginInfo.ProviderKey) == null)
                {
                    CheckIdentityErrors(await UserManager.AddLoginAsync(user, loginInfo));
                }
            }
```

**Comment by maliming** [comment]
hi

If `Succeeded` means there is an existing user. Why needs to create again?

**Comment by pjkeukens** [comment]
@maliming result.Succeeded is for the external authentication in the Azure AD but if it's a new user the user is not yet in AbpUsers table, because of the if the user is not created in AbpUsers which is done in the code below the if statement where it checks if the user already exists in AbpUsers and if not create the user.

**Comment by JadynWong** [comment]
`SignInResult.Succeeded` means that this user exists in AbpUsers.
When the user cannot be found from the `AbpUserLogins` table by `LoginProvider` and `ProviderKey`, it will return SignInResult.Failed.

`SignInManager.ExternalLoginSignInAsync`
https://github.com/dotnet/aspnetcore/blob/70d7f5f9e02c84084daec2f6666decd343e56b46/src/Identity/Core/src/SignInManager.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L610-L633

`IdentityUserStore.FindByLoginAsync`
https://github.com/abpframework/abp/blob/f4d33dd99454e1d33e4874a72273ea49d4da7bab/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserStore.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L541-L558

`IdentityUserLogin`
https://github.com/abpframework/abp/blob/f4d33dd99454e1d33e4874a72273ea49d4da7bab/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserLogin.cs#L9-L34

**Comment by pjkeukens** [comment]
@JadynWong I think you are right, I must have checked the wrong user database or something... Sorry, I will close this now.
