### ISSUE TITLE
Replacing free Font Awesome with Pro

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#12215]
* Your **ABP Framework version**. 5.2
* Your **User Interface** type Blazor Server
* Your database provider(EF Core/MongoDB) EFCore 

I have a subscription to Font Awesome pro and would like to replace the library included in abp with the kit created in my FontAwesome account.  When the kit is created a url is generated (hosting on the FontAwesome CDN) similar to this:

<script src="https://kit.fontawesome.com/<uniquekitid>.js" crossorigin="anonymous"></script>

I'm familiar with the script and style contributors and have used those to include css/js contained as part of my modules, but I am not clear on the correct approach for removing the included FA library and using the resource from the CDN instead. Any guidance is appreciated!

**Comment by JadynWong** [comment]
You can try to remove `FontAwesomeStyleContributor` by configuring `AbpBundlingOptions.StyleBundles`.

I create a demo.
https://github.com/JadynWong/abp-blazor-server-cdn-demo/commit/0a6324c5202fa9f0cf2917a491d494e9ad173c3a

**Comment by jhulbertpmn** [comment]
Very cool - thank you!
