### ISSUE TITLE
Hello, can the document support global retrieval? 

### ISSUE THREAD

**Issue by applebananamilk** [abpframework/abp#12228]
Sometimes to find documents according to the source code, you need to click one by one. I can't find a place for feedback on the official website, so I can only come here to ask questions.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/162869179-87b12acf-1dd2-492c-b2b4-bf6d72b2effb.png)

**Comment by applebananamilk** [comment]
Thank you, I searched several times before but no results came back, I thought it was not working. .  😄
