### ISSUE TITLE
Inconsistent Abp Prefix on DbProperties classes

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#12232]
For example: 
Some modules have the Abp prefix:
* AbpTenantManagementDbProperties
* AbpAuditLoggingDbProperties

while others do not:
* BackgroundJobsDbProperties instead of AbpBackgroundJobsDbProperties
* FeatureManagementDbProperties instead of AbpFeatureManagementProperties

**Comment by hikalkan** [comment]
@maliming we can add Abp prefix to others. This will be a breaking change, but easy to fix for existing applications.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/13400
