### ISSUE TITLE
Test - Cli: Allow to generate code with Suite

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#12236]
Releated with https://github.com/abpframework/abp/pull/12231

**Comment by yekalkan** [comment]
You can ask me how to test this.

**Comment by gizemmutukurt** [comment]
Test is OK.

Json can be generated with Cli: Suite.
When the project is run, the entities are displayed and the CRUD operations work fine.
![image](https://user-images.githubusercontent.com/99716457/163165811-b72f2656-0860-4ab3-9d93-31b7ea999331.png)
