### ISSUE TITLE
Account summary always shows 'lockout' status.

### ISSUE THREAD

**Issue by marcoiwell** [abpframework/abp#12241]
ABP Version: 5.1
Tiered solution: .Net Core, EFCore, Angular

# Problem description
The Users UI (Administration -> Identity Management -> Users) always shows a red cross icon on the 'Account Lockout' column. It doesn't seem to reflect the underlying data.

## Expected behaviour
When a user has a locked out account, the red cross icon should be visible.
When a user has an active (not locked out) account, the green check icon should be visible.
(or just the way a-round.. depends on how you look at it ;))

## Images
![edit1](https://user-images.githubusercontent.com/100137119/163131175-733daa33-6a56-43f1-ae2d-fd2ced102e87.png)
![edit2](https://user-images.githubusercontent.com/100137119/163131181-5f6441e2-dcb1-4449-84fc-ba4908e356af.png)
![overview](https://user-images.githubusercontent.com/100137119/163131182-e67bc8b7-1007-48ec-a8de-3e13a6a3fde6.png)

**Comment by muhammedaltug** [comment]
Hello,

It will be fixed in the next 5.2 version. Thanks for reporting the issue
