### ISSUE TITLE
Allow Setting Extended Property as ReadOnly on the UI

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#12249]
Related support question: https://support.abp.io/QA/Questions/2908/Setting-Extended-Property-as-ReadOnly-on-the-UI

---

We can allow users to make their extended property as readonly on both create and edit forms.

```csharp
user.AddOrUpdateProperty( 
   "FullName", 
   property =>
   {
       property.UI.OnCreateForm.IsReadOnly = true;
       property.UI.OnEditForm.IsReadOnly = false;
   }
);
```

**Comment by balessi75** [comment]
Hi @EngincanV 

Bumping this feature request as it's been over a year now.

Thank you.

**Comment by EngincanV** [comment]
> Hi @EngincanV
> 
> Bumping this feature request as it's been over a year now.
> 
> Thank you.

Hi @balessi75, sorry I could not prioritize the issue, therefore it was in the backlog. I will try to implement this feature in the next version.
