### ISSUE TITLE
EShopOnAbp.WebPublicGateway use same TCP ports of EShopOnAbp.CatalogService.HttpApi.Host

### ISSUE THREAD

**Issue by antonio-campagnaro** [abpframework/abp#12243]
In https://github.com/abpframework/eShopOnAbp WebPublicGateway and CatalogService are using the same ports configured in appsettings.Development.json

**Comment by gterdem** [comment]
> In https://github.com/abpframework/eShopOnAbp WebPublicGateway and CatalogService are using the same ports configured in appsettings.Development.json

Thank you. We've fixed this issue.
