### ISSUE TITLE
Add FindByPhoneNumberAsync

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#12247]
Hello,
I'm using ABP Framework version 5.1.4
User Interface: Mvc.
I suggest to add Add FindByPhoneNumberAsync method

**Comment by maliming** [comment]
See https://github.com/dotnet/aspnetcore/issues/25368#issuecomment-683153614

**Comment by ArcherTrister** [comment]
@maliming  Sorry, maybe I didn't express clearly, it has nothing to do with identity, I hope to add FindByPhoneNumberAsync  method in IIdentityUserRepository

See [Repositories.md](https://github.com/abpframework/abp/blob/dev/docs/en/Best-Practices/Repositories.md) , There are a lot of not do
