### ISSUE TITLE
Please support 'Light Mode' for ABP CLI in terminal

### ISSUE THREAD

**Issue by ghost** [abpframework/abp#12256]
![ABP CLI](https://i.imgur.com/9qToiga.png)

**Comment by maliming** [comment]
How to do this? windows and mac?

**Comment by ghost** [comment]
> How to do this? windows and mac?

I have a good idea: Cancel the ABP CLI customize terminal color

**Comment by roc916** [comment]
Related with https://github.com/serilog/serilog-sinks-console/issues/123
