### ISSUE TITLE
Background Worker in continuous mode is blocking the services

### ISSUE THREAD

**Issue by damien-r** [abpframework/abp#12255]
# Context

Hello,

I want to use a background worker to write an UDP server specific to our application. However, I have faced 2 issues during the implementation. I will write here a minimal example of code to illustrate it.

# Preparation

Download a template from https://abp.io/get-started. Options: Application / Angular / Entity Framework Core / SQL Server None.
The actual version is 5.2.
Open the `aspnet-core` solution
In Domain, create a dummy continuous Background Worker class
```
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Volo.Abp.BackgroundWorkers;

namespace TestBackgroundWorker;

public class DummyUdpServerBackgroundWorker : BackgroundWorkerBase
{
    public override async Task StartAsync(CancellationToken cancellationToken = default)
    {
        using var udpServer = new UdpClient();
        var destinationIp = IPAddress.Any;
        var serverPort = 5151;
        var endPoint = new IPEndPoint(destinationIp, serverPort);
        udpServer.Client.Bind(endPoint);


        while (!StoppingToken.IsCancellationRequested)
        {
            var result = await udpServer.ReceiveAsync(StoppingToken);
            Logger.LogDebug($"{result.Buffer.Length} bytes received");
        }
    }

}
```

Open `DomainModule.cs`
Add code from https://docs.abp.io/en/abp/latest/Background-Workers#register-background-worker
```
[DependsOn(typeof(AbpBackgroundWorkersModule))]
public class MyModule : AbpModule
{
    public override Task OnApplicationInitializationAsync(
        ApplicationInitializationContext context)
    {
        context.AddBackgroundWorkerAsync<DummyUdpServerBackgroundWorker >();
    }
}
```

Here is the first issue: the code does not compile, because there is an error in the documentation of version 5.2
```
not all code paths return a value
```

`OnApplicationInitializationAsync` is not declared as aync in code, and therefore should return a `Task`.

Now, change the code a little bit:
```
[DependsOn(typeof(AbpBackgroundWorkersModule))]
public class MyModule : AbpModule
{
    public override async Task OnApplicationInitializationAsync(
        ApplicationInitializationContext context)
    {
        await context.AddBackgroundWorkerAsync<DummyUdpServerBackgroundWorker >();
    }
}
```
Add `async` and `await`.

# Reproduce issue

Now run the `.HttpApi.Host` project. The Background Job runs, but the API does not answer to REST requests.

**Comment by damien-r** [comment]
This is not specific to UDP server. You can replace the loop with a `Sleep`

```
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Volo.Abp.BackgroundWorkers;

namespace TestBackgroundWorker;

public class DummyUdpServerBackgroundWorker : BackgroundWorkerBase
{
    public override async Task StartAsync(CancellationToken cancellationToken = default)
    {
        while (!StoppingToken.IsCancellationRequested)
        {
           Thread.Sleep(5000);
           Logger.LogInformation("Time passes...");
        }
    }

}
```

**Comment by maliming** [comment]
You can try to use https://docs.abp.io/en/abp/latest/Background-Jobs

Or Quartz and Hangfire.

**Comment by dicksonkimeu** [comment]
Whats the advantage of using hangfire ? Whats the challenge if not using it ?

**Comment by ArcherTrister** [comment]
@damien-r 

like this

```
[DependsOn(typeof(AbpBackgroundWorkersModule))]
public class MyModule : AbpModule
{
    public override async Task OnApplicationInitializationAsync(
        ApplicationInitializationContext context)
    {
        await context.AddBackgroundWorkerAsync<DummyUdpServerBackgroundWorker>();
        await base.OnApplicationInitializationAsync(context);
    }
}
```

Now run the .HttpApi.Host project. The Background Job runs and the API can respond to REST requests.

**Comment by hikalkan** [comment]
https://github.com/abpframework/abp/pull/12268#issuecomment-1110952180

Background worker's StartAsync method should not block the caller. If you need, create a separate thread and stop it in the StopAsync method.
