### ISSUE TITLE
Concurrent Virtual User Load Testing for all the templates

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#12266]
Make a performance test with Jmeter for Angular, Blazor WASM, Blazor Server and MVC.
The database should be the same for all the templates (eg: MS-SQL)
The test scenario should be run with 1 user, 100 concurrent users, and 500 concurrent users ( we can increase according to the results).
Show the output as line charts.
Show the total execution time for all UI types so that we can see the slowest and fastest UI templates. 
The test scenarios must be saved and ready to use for Jenkins.

**Comment by hikalkan** [comment]
Will be tracked internally
