### ISSUE TITLE
Abpdbcurrencyexception is used to handle concurrent operations, but the latest database value cannot be obtained

### ISSUE THREAD

**Issue by l2999019** [abpframework/abp#12271]
The code is as follows:
` if (inner is AbpDbConcurrencyException)
{

                                var exx = inner.InnerException as DbUpdateConcurrencyException;
                                foreach (var entry in exx.Entries)
                                {
                                    entry.Context.ChangeTracker.QueryTrackingBehavior = Microsoft.EntityFrameworkCore.QueryTrackingBehavior.NoTracking;
                                    var proposedValues = entry.CurrentValues;
                                    entry.State = EntityState.Detached;
                                    //The latest value of the database cannot be obtained here
                                     var databaseValues = entry.GetDatabaseValues();
                                    foreach (var property in proposedValues.Properties)
                                    {
                                        var proposedValue = proposedValues[property];
                                        var databaseValue = databaseValues[property];
                                        proposedValues[property] = databaseValue;
                                    }
                                    entry.OriginalValues.SetValues(databaseValues);

                                }`

ABP 4.4 version

ORM:EF Core
SQL: Mysql

The latest value of the database cannot be obtained here
var databaseValues = entry.GetDatabaseValues();

**Comment by maliming** [comment]
You can try that without ABP, just use EF Core.

**Comment by l2999019** [comment]
> You can try that without ABP, just use EF Core.


I tried to use "pomelo. Entityframeworkcore. MySQL" directly
like this  "Databasevalues" can be obtained normally:

![image](https://user-images.githubusercontent.com/10385855/163914461-bb441f28-eeff-4c2a-8bf1-ce4f69ea79d1.png)
