### ISSUE TITLE
Quick start tutorial with the single layer startup template

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12273]
Create [the same TODO application](https://docs.abp.io/en/abp/latest/Tutorials/Todo/Index) with the single layer startup template. We can talk before you start this.

**Comment by EngincanV** [comment]
Also, add the quick start tutorial link to the **Application (Single Layer) documentation**(https://github.com/abpframework/abp/issues/12272) when the documentation is done (under the "Introduction" section).
