### ISSUE TITLE
Job gets unregistered task execution

### ISSUE THREAD

**Issue by haptear** [abpframework/abp#12285]
ABP Framework version: v5.2.0
UI type: MVC
DB provider: EF Core

Microservice mode has A, B 2 services, both connected to the same mysql database.
Service A only has job for sending emails.
Service B only has job for sending SMS.
During the actual operation A and B will execute each other's tasks, which leads to errors

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/latest/Background-Workers#running-on-a-cluster
