### ISSUE TITLE
[Feature Request] abp generate-proxy: also generate DTO constraint constants

### ISSUE THREAD

**Issue by hillin** [abpframework/abp#12282]
It would be great if `abp generate-proxy` (`-t ng` in my case) also generates DTO constraint constants, such as max length of string fields, so we don't have to defined them in two different places.

**Comment by hikalkan** [comment]
Thanks for your suggestion. We will think on that in the next version.

**Comment by hillin** [comment]
Per #12288 : it would also be nice if it could generate the permission name constants as well, preferably in a structured manner.

**Comment by maliming** [comment]
MVC part is done: https://github.com/abpframework/abp/pull/12377

**Comment by hikalkan** [comment]
@maliming & @muhammedaltug please open another issue for Angular UI (typescript).
