### ISSUE TITLE
None of the constructors found

### ISSUE THREAD

**Issue by teacher-zhou** [abpframework/abp#12290]
* Version **5.2**.
* Blazor server
* EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

I'm using Volo.Abp.BlazoriseUI for blazor, and using the `AbpCrudComponentBase` for razor page, when I click edit in list，one exception exception throw as below
-----------------------------------------
```
DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Volo.Abp.ObjectMapping.DefaultObjectMapper`1[Boloni.Web.BoloniBlazorModule]' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.ObjectMapping.IAutoObjectMappingProvider`1[Boloni.Web.BoloniBlazorModule] autoObjectMappingProvider' of constructor 'Void .ctor(System.IServiceProvider, Volo.Abp.ObjectMapping.IAutoObjectMappingProvider`1[Boloni.Web.BoloniBlazorModule])'.
```
![image](https://user-images.githubusercontent.com/52902266/163780689-16910e09-92e6-42cf-9dba-136125589972.png)

But I have add the `AbpAutoMapperModule`
![image](https://user-images.githubusercontent.com/52902266/163780804-5d4be689-6f8d-41df-be3b-40ccf8ab297a.png)

**Comment by maliming** [comment]
`context.Services.AddAutoMapperObjectMapper<BoloniBlazorModule>();`

**Comment by AchievedOwner** [comment]
> `context.Services.AddAutoMapperObjectMapper<BoloniBlazorModule>();`

I did it, but still has error
