### ISSUE TITLE
ABP BackgroundJobManager -> protected override void DoWork() not being called after backgroundJobManager.EnqueueAsync

### ISSUE THREAD

**Issue by sohaibameenpk007** [abpframework/abp#12309]
Hello everyone, 

I am using ABP framework 5 and enqueuing object with the help of a background job. It seems to be working fine for us on stage environment for the same code but its not working on production. 

await _backgroundJobManager.EnqueueAsync<CreateDomainJob, CreateDomainJobArgs>(
                        new CreateDomainJobArgs
                        {
                            DomainName = model.AccountInformation.TenancyName + AwsDefines.AwsDomain + ".",
                            TenantName = model.AccountInformation.TenancyName,
                            TenantId = tenantInfo.Id,
                            AccountName = model.AccountInformation.AccountName,
                            SendToEmail = model.UserInformation.EmailAddress,
                            KeyActive = keyActive,
                            IsCreatedByEpilogueAdmin = true,
                            Password = model.UserInformation.Password,
                            FullName = tenant.Owner.FullName,
                        });

I have also checked the **BackgroundJobs** table where entries in prod DB are persisting because **Execute(CreateDomainJobArgs args)** is not being called to dequeue data and delete the records from database. 

I want to confirm if there is any limitation? 

The code is similar on both ends but I don't understand why it stopped working all of a sudden. Please provide your valuable feedback on this. 

Thanks,
Sohaib

**Comment by maliming** [comment]
Are there any error logs?

**Comment by sohaibameenpk007** [comment]
No, there are not any error logs just different data with records which meet the condition.

**Comment by maliming** [comment]
Please try to reproduce the problem.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-6.0

**Comment by sohaibameenpk007** [comment]
@maliming I shared the LINQ query with the database query so If you can review that and provide your feedback on it then It would resolve the issue I am having. I don't understand why you are asking to reproduce the problem when its already here.

**Comment by sohaibameenpk007** [comment]
DoWork method is not being called.

protected override void DoWork()
{
    var waitingJobs = AsyncHelper.RunSync(() => _store.GetWaitingJobsAsync(1000));

    foreach (var job in waitingJobs)
    {
        TryProcessJob(job);
    }
}

@maliming 

Same code is running on stage environment with one pod but its not working on production where we have two pods.

**Comment by maliming** [comment]
The default implementation is simple and you can try Hangfire.

https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire
