### ISSUE TITLE
When I use in-process hosting, I can't add data to the database

### ISSUE THREAD

**Issue by zhangtingwz** [abpframework/abp#12311]
Hello I am a newbie and would like to ask a question. When the iis are released, I set up the in-process hosting in the web.config, I call the saved method, sqlserver can not add any records, but I use out-of-process hosting is OK, please ask what is the reason for this, and I use .net core as if the process can modify the database.

**Comment by maliming** [comment]
hi

This has nothing to do with ABP, but with IIS.

**Comment by JadynWong** [comment]
Any error info?

**Comment by zhangtingwz** [comment]
Yes, there are no errors, only when I check the data in my database, I find that there is no data in the database, and the whole process is not reported errors

**Comment by zhangtingwz** [comment]
Here I say, if I run directly with vs and then access the API interface through IP, I can't save it, but if I use postman access, it is possible.
