### ISSUE TITLE
[Feature Request] abp generate-proxy: headers and skipHandleErrors support

### ISSUE THREAD

**Issue by cbbuild** [abpframework/abp#12310]
Hello,

It would be great if an angular generated proxy would support some additional method parameters for sending headers, or changing skipHandleErrors.

for example:
  deleteCustomerById = (id: number, **headers: any = {}, skipHandleError: boolean = null**) =>
    this.restService.request<any, NoContentResult>({
      method: 'DELETE',
      url: `/api/customer/${id}`,
      **headers: headers**
    },
    { apiName: this.apiName, **skipHandleError: skipHandleError**});

**Comment by mahmut-gundogdu** [comment]
in the V7.2 preview, this functionalty will be implemented like that

deleteCustomerById = (id: number, additionalOptions?: ProxyAdditionalOptions = {}) => { }
