### ISSUE TITLE
Can´t add Volo.Abp.AspNetCore.SignalR to Blazor WASM

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#12313]
I was starting to follow the [SignalR integration guide](https://docs.abp.io/en/abp/5.2/SignalR-Integration) and when I try to install `Volo.Abp.AspNetCore.SignalR` I get the following error

> There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.	

that of course means no `typeof(AbpAspNetCoreSignalRModule)` etc.

So is abp SignalR with Blazor WASM setup somehow different? You might want to mention that in the docs then...

SignalR and Blazor WASM [are at least supported from Microsoft.](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=webassembly) and I´ll look into just using that directly but it would be nice to have it pre-configured with abp.

* Your **ABP Framework version**. **5.2.1**
* Your **User Interface** type: **Blazor**
* Your database provider: **EF Core**

**Comment by maliming** [comment]
I think you need using the `Microsoft.AspNetCore.SignalR.Client` package for blazor wasm.

**Comment by sturlath** [comment]
So no  `typeof(AbpAspNetCoreSignalRModule) `  and I have to manually configure` services.AddSignalR() `and `app.UseEndpoints(...)`?

I will play with this today and see how far I can get (I´ll report back)

Btw I found this example, [SignalRTieredDemo](https://github.com/abpframework/abp-samples/tree/master/SignalRTieredDemo) that is much better (for my use case) than [the one mention in the guide](https://github.com/abpframework/abp-samples/tree/master/SignalRDemo). You might want to add that to the docs.

**Comment by sturlath** [comment]
I got this to work [here ](https://github.com/sturlath/ReplyBackSeparateIdentityServer) @maliming (but only for open source abp)

The Blazor UI sends a message to Host and the Host replies **BUT** I´m having massive problem getting this to work in my (commercial) project. 

If I just keep the Index file 100% like in the working example (pointing to the correct url and port) I get this error (in my 5.2.1 project)

![image](https://user-images.githubusercontent.com/2386572/164553464-89c7d27f-12c8-4ba0-be74-9b8301c8e9da.png)

and this in the logs
![image](https://user-images.githubusercontent.com/2386572/164553997-96bcf83b-a881-4f15-a94c-b6995ac629be.png)

If I create a brand new commercial project and add the code I get a slightly different looking error
![image](https://user-images.githubusercontent.com/2386572/164558562-cebdc78e-28c1-4b9c-afdf-b9c42a32bbd8.png)

Any idea what this might be? 

p.s
I'll also created a [support ticket ](https://support.abp.io/QA/Questions/2962/Authentication-issue-with-Blazor-WASM-SignalR-in-Commercial-not-in-opensource)

**Comment by maliming** [comment]
ok, Move to the support website.
