### ISSUE TITLE
Abp Permission auth entity not filter by scope (/api/abp/application-configuration) 

### ISSUE THREAD

**Issue by vijay2358** [abpframework/abp#12320]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**. 5.14 or 5.2.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI : Microservice 
* Your database provider(EF Core/MongoDB) : EFCore
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Please **write in English**.
#1543 
@hikalkan  - we are using micro service in applications like you mentioned above  (Blog, Product, Identity)

Here our solution was designed 
1.	Identity API Service  scope as “Identity”
2.	Blog API Service  scope as “Blog”
3.	Product API Service  scope as “Product”

On top it – Gateway API  included all  scopes ((Blog, Product, Identity)  by referring adding .ApplicationContracts nuget

Now All WEBUI  calling Gateway API along with scope (Blog, Product, Identity),

Issue  permissions grants showing in all applications API.  we are expecting to see each permission should be filter by scope/resource but it is coming all permissions from all three modules even though calling by scope..

Gateway --> API – same data coming from all UI apps 

"auth": {
    "policies": {
      "AbpIdentity.Roles": true,
      "AbpIdentity.Roles.Create": true,
      "AbpIdentity.Roles.Update": true,
      "AbpIdentity.Roles.Delete": true,      
      "Blog.Business": true,
      "Blog.Business.Edit": true,      
      "Product.Test": true,
      "Product.Test.Create": true
    },
    "grantedPolicies": {}
  }
-----------------------------This should be filter if calling GATEWAY API from Blog UI 
****Blog**********
"auth": {
    "policies": {     
      "Blog.Business": true,
      "Blog.Business.Edit": true   
    },
    "grantedPolicies": {}
  }
-----------------------------This should be filter if calling GATEWAY API from Product UI
****Product**********
"auth": {
    "policies": {
      "Product.Test": true,
      "Product.Test.Create": true
    },
    "grantedPolicies": {}
  }
-----------------------------This should be filter if calling GATEWAY API from AbpIdentityUI
****AbpIdentity**********
"auth": {
    "policies": {
      "AbpIdentity.Roles": true,
      "AbpIdentity.Roles.Create": true,
      "AbpIdentity.Roles.Update": true,
      "AbpIdentity.Roles.Delete": true
    },
    "grantedPolicies": {}
  }
------------------------------------
	
Please let me know if you need more info.

**Comment by maliming** [comment]
hi

The default design does not check api scope. You can customize the implementation.

https://docs.abp.io/en/abp/latest/Authorization#overriding-a-permission-by-a-custom-policy
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0
