### ISSUE TITLE
Custom login Angular

### ISSUE THREAD

**Issue by Majed-404** [abpframework/abp#12322]
When i use AuthService to get login from my angular project it redirect me to identity server ui page in different port insert username and password then redirect again to 4200 port 

I want to be able to call an api for getting the token without redirect to another port

**Comment by mahmut-gundogdu** [comment]
It can be available by changing the config in Environment.ts. You can use `Resource Owner Password Flow`.


Resource: https://docs.abp.io/en/abp/5.2/UI/Angular/Authorization#resource-owner-password-flow
