### ISSUE TITLE
Allow abp suite to handle byte[] type

### ISSUE THREAD

**Issue by kfrancis** [abpframework/abp#12324]
Right now, abp suite has mainly primitive types but if there's one non-primitive that would be useful it would be byte[] as it's very common that entities might want to be used for files.

![22-04-nbkp6-1650569045](https://user-images.githubusercontent.com/67574/164537695-68ba9492-9dc9-4e25-a992-50cda6ec049f.png)

Bonus: Make it use the binary object manager by default.
Double bonus: Make it use the file upload input for the UI.

**Comment by hikalkan** [comment]
This issue is moved to out private repository for ABP Commercial.
