### ISSUE TITLE
The Logger object is null

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#12339]
- ABP Framework Version: 5.1.4
- User Interface:Angular
- Database Provider: EF Core

I followed [official doc](https://docs.abp.io/zh-Hans/abp/latest/Background-Workers-Hangfire)

and add nuget package Volo.Abp.BackgroundWorkers.Hangfire into my module.

![1122](https://user-images.githubusercontent.com/35516482/164957851-ca78bb0e-901a-4d26-b540-11549852503e.png)

**Comment by maliming** [comment]
Add [Autofac ](https://docs.abp.io/zh-Hans/abp/latest/Autofac-Integration) module to your project.

**Comment by ArcherTrister** [comment]
I'm using the template project, which comes with this module

![image](https://user-images.githubusercontent.com/35516482/164969654-3ee15bb7-3086-4461-9fdd-3e2a51e85c48.png)
![image](https://user-images.githubusercontent.com/35516482/164969662-b1ded8ba-52b5-4f01-a7ef-534022349345.png)

**Comment by maliming** [comment]
If the `Logger` is your property you need to init it from DI(constructor or property inject).

**Comment by ArcherTrister** [comment]
This `Logger` is a property of BackgroundWorkerBase.

abp project: [aspnet-core](https://cdn-1255895673.cos.ap-chengdu.myqcloud.com/GithubDemo/aspnet-core.rar)

**Comment by rqx110** [comment]
The error only occurred in defined a interface(IMyLogWorker).

it works if we not use the interface(IMyLogWorker) style.
```cs
public class MyLogWorker : HangfireBackgroundWorkerBase
{
    // ... 
}
```
```cs
public override Task OnApplicationInitializationAsync(ApplicationInitializationContext context)
{
    await context.AddBackgroundWorkerAsync<MyLogWorker>();
}
```

**Comment by ArcherTrister** [comment]
@rqx110  My code involves database operations and needs to use `UnitOfWorkAttribute`, I follow [the documentation](https://docs.abp.io/en/abp/latest/Background-Workers-Hangfire), is it okay if I don't use the interface(IMyLogWorker) style?

**Comment by rqx110** [comment]
@ArcherTrister I just pointed out the real problem is. And I agree it is a problem of abp

**Comment by ArcherTrister** [comment]
@rqx110 OK, thanks!

**Comment by maliming** [comment]
```cs
[ExposeServices(typeof(IMyLogWorker), typeof(MyLogWorker))]
public class MyLogWorker : HangfireBackgroundWorkerBase, IMyLogWorker
{
    public MyLogWorker()
    {
        RecurringJobId = nameof(MyLogWorker);
        CronExpression = "* * * * * ?";
    }

    public override Task DoWorkAsync()
    {
        using (var uow = LazyServiceProvider.LazyGetRequiredService<IUnitOfWorkManager>().Begin())
        {
            Logger.LogInformation("Executed MyLogWorker..!");
            return Task.CompletedTask;
        }
    }
}
```

**Comment by rqx110** [comment]
@maliming so the document about `UnitOfWorkAttribute` will update? 
https://docs.abp.io/en/abp/latest/Background-Workers-Hangfire#unitofwork

**Comment by maliming** [comment]
Yes, WE WILL.

**Comment by rqx110** [comment]
Thanks @maliming

**Comment by maliming** [comment]
Resolve by https://github.com/abpframework/abp/pull/11591

**Comment by Sunzhuokai** [comment]
@maliming 
 when add  `[ExposeServices(typeof(IMyLogWorker), typeof(MyLogWorker))]`
![image](https://user-images.githubusercontent.com/8599906/168243038-284f030b-3fca-4692-914e-00f748b3a964.png)

**Comment by jakeuj** [comment]
@maliming

> Yes, WE WILL.

The document about UnitOfWorkAttribute is still not update yet.

@Sunzhuokai

> @maliming when add `[ExposeServices(typeof(IMyLogWorker), typeof(MyLogWorker))]` ![image](https://user-images.githubusercontent.com/8599906/168243038-284f030b-3fca-4692-914e-00f748b3a964.png)

Module.cs
``` C#
public override async Task OnApplicationInitializationAsync(
    ApplicationInitializationContext context)
{
    await base.OnApplicationInitializationAsync(context);

    //If the interface is defined
    await context.AddBackgroundWorkerAsync<IUowModifiedWorker>();
}
```

Worker.cs
``` C#
using Hangfire;
using Volo.Abp.BackgroundWorkers.Hangfire;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Uow;

namespace T89NoUi.Workers;

public interface IUowModifiedWorker : IHangfireBackgroundWorker
{
}

[ExposeServices(typeof(IUowModifiedWorker), typeof(UowModifiedWorker))]
public class UowModifiedWorker : HangfireBackgroundWorkerBase, IUowModifiedWorker
{
    public UowModifiedWorker()
    {
        RecurringJobId = nameof(UowModifiedWorker);
        CronExpression = Cron.Minutely();
    }

    public override Task DoWorkAsync(CancellationToken cancellationToken = new CancellationToken())
    {
        using var uow = LazyServiceProvider.LazyGetRequiredService<IUnitOfWorkManager>().Begin();
        Logger.LogInformation($"Executed {nameof(UowModifiedWorker)} ..!");
        return Task.CompletedTask;
    }
}
```

![image](https://user-images.githubusercontent.com/834156/185554747-f5091008-8fbd-4eb3-ad0a-be47dbb09133.png)

**Comment by maxrizwork** [comment]
I had a similar problem with a project 
- ABP Framework Version: 6.0.1
- User Interface: ASP.NET Core
- Database Provider: EF Core with SQL Server
and I solved in this way without the attribute [UnitOfWork] and creating manually a new uow

```
public override async Task DoWorkAsync(CancellationToken cancellationToken = default)
    {
        await using (var handle = await _distributedLock.TryAcquireAsync(nameof(CreditRequestExpirationJob)))
        {
            if (handle is null)
            {
                Logger.LogWarning("CreditRequestExpirationJob process skipped because job was LOCKED");
                return;
            }

            using (var uow = LazyServiceProvider.LazyGetRequiredService<IUnitOfWorkManager>().Begin())
            {
                Logger.LogDebug("CreditRequestExpirationJob LOCK ACQUIRED");
                Logger.LogInformation("CreditRequestExpirationJob job STARTED");

                var crManager = LazyServiceProvider.LazyGetRequiredService<CreditRequestManager>();
                var crAffected = await crManager.UpdateNewExpiredCreditRequestsAsync();

                await uow.CompleteAsync();

                Logger.LogWarning($"CreditRequestExpirationJob job FINISHED successfully with {crAffected} new expired credit requests affected");
                Logger.LogDebug("CreditRequestExpirationJob LOCK RELEASED");
            }
        } // lock section
    }
```

**Comment by ahmetfarukulu** [comment]
https://github.com/abpframework/abp/issues/12339#issuecomment-1323712406

> LazyServiceProvider.LazyGetRequiredService<IUnitOfWorkManager>().Begin()

If you want to rollback on exception don't forget the `isTransactional: true` parameter

**Comment by jakeuj** [comment]
> 我在專案中遇到了類似的問題
> 
> * ABP框架版本： 6.0.1
> * 用戶介面：ASP.NET 核心
> * 資料庫提供程式：帶有SQL Server的EF Core，我以這種方式解決了沒有屬性[UnitOfWork]並手動創建一個新的uow
> 
> ```
> public override async Task DoWorkAsync(CancellationToken cancellationToken = default)
>     {
>         await using (var handle = await _distributedLock.TryAcquireAsync(nameof(CreditRequestExpirationJob)))
>         {
>             if (handle is null)
>             {
>                 Logger.LogWarning("CreditRequestExpirationJob process skipped because job was LOCKED");
>                 return;
>             }
> 
>             using (var uow = LazyServiceProvider.LazyGetRequiredService<IUnitOfWorkManager>().Begin())
>             {
>                 Logger.LogDebug("CreditRequestExpirationJob LOCK ACQUIRED");
>                 Logger.LogInformation("CreditRequestExpirationJob job STARTED");
> 
>                 var crManager = LazyServiceProvider.LazyGetRequiredService<CreditRequestManager>();
>                 var crAffected = await crManager.UpdateNewExpiredCreditRequestsAsync();
> 
>                 await uow.CompleteAsync();
> 
>                 Logger.LogWarning($"CreditRequestExpirationJob job FINISHED successfully with {crAffected} new expired credit requests affected");
>                 Logger.LogDebug("CreditRequestExpirationJob LOCK RELEASED");
>             }
>         } // lock section
>     }
> ```

Finally same. (7.0.0)

```
public override async Task DoWorkAsync(CancellationToken cancellationToken = new CancellationToken())
{
    await using var handle =
        await DistributedLock.TryAcquireAsync(nameof(UpdateOrdersWorker), cancellationToken: cancellationToken);
    Logger.LogInformation($"Lock is acquired for {nameof(UpdateOrdersWorker)}");

    if (handle != null)
    {
        using var uow = _uowManager.Begin();
        await _orderManager.SyncBizViewAsync();
        await uow.SaveChangesAsync(cancellationToken);

        Logger.LogInformation($"Lock is released for {nameof(UpdateOrdersWorker)}");
        return;
    }

    Logger.LogInformation($"Handle is null because of the locking for : {nameof(UpdateOrdersWorker)}");
}
```
