### ISSUE TITLE
Adding n-n navigation via abp suite there is typehead without select option with add button, only adds typehead input with add button.

### ISSUE THREAD

**Issue by ysozbek** [abpframework/abp#12331]
* Your **5.2.1**.
* Your **Angular
* Your database provide rEF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

When adding n-n navigation property lookup element is being <abp-lookup-typeahead-mtm> component not having select element with add button. It becomes only typeahead input element with add button.

<img width="466" alt="Capture" src="https://user-images.githubusercontent.com/50448937/164731479-b5ee43f3-34bd-46a7-92a8-7cc79a405437.PNG">

**Comment by ysozbek** [comment]
Will anything be done about this issue?

**Comment by yekalkan** [comment]
> When adding n-n navigation property lookup element is being component not having select element with add button. It becomes only typeahead input element with add button.

It is hard to understand what you mean. I guess you want a simple dropdown instead of typeahead. We may consider this in next releases.

I'm closing this issue because Abp suite is a commercial product and not related with this repository. Please use support.abp.io for tickets.
