### ISSUE TITLE
Number of interfaces

### ISSUE THREAD

**Issue by baiguogang** [abpframework/abp#12337]
When running a project with ABP version 5.2, is there a limit to the number of interfaces? For example, no more than 500 interfaces on a Swagger page, etc.? Because I have a project ready to use ABP5.2, and the estimated number of interfaces is around 2000 ......

**Comment by maliming** [comment]
Hi

There's not such limited.

**Comment by baiguogang** [comment]
> 



> Hi
> 
> There's not such limited.

Thank you for your information......
