### ISSUE TITLE
What is the right ABP template for creating a new microservice?

### ISSUE THREAD

**Issue by antonio-campagnaro** [abpframework/abp#12333]
I have created a new solution with the ABP CLI using the Microservice Template. What is the right template for creating a new single microservice (like ProductService)?

If the template doesn't exists, what is the suggested and faster way to have a working microservice in Abp?

**Comment by gterdem** [comment]
Try `abp new microserviceName -t microservice-service-pro`.

Here is the [Adding new Microservices to the Solution guide](https://docs.abp.io/en/commercial/latest/startup-templates/microservice/add-microservice).

This is also a commercial template. So, please ask your commercial template related questions at https://support.abp.io

Thank you.
