### ISSUE TITLE
latest version abp mircoserivce demo cannot load user api

### ISSUE THREAD

**Issue by matthewLin0520** [abpframework/abp#12346]
![image](https://user-images.githubusercontent.com/39901947/165017159-81c75257-24a6-436b-a90c-8a06a06b9cfb.png)

![image](https://user-images.githubusercontent.com/39901947/165017117-73bbf99e-33cf-41bd-b544-304ccccc344d.png)

**Comment by maliming** [comment]
Please check the new ms demo: https://github.com/abpframework/eShopOnAbp

**Comment by matthewLin0520** [comment]
![image](https://user-images.githubusercontent.com/39901947/165017381-508162ae-a032-4fd7-bc84-ac78a704493d.png)
