### ISSUE TITLE
[angular] UI Localizations  breaks angular-oauth2-oidc 

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#12342]
* Your **ABP Framework version**.
[ rel-5.2  (I created a branch to reproduce this problem)](https://github.com/yinchang0626/abp/tree/feature/angular-localizations-bug)
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
angular
* Your database provider(EF Core/MongoDB)
dont'care
* Exception message and **stack trace** if available (check the logs).
no
* Steps needed to **reproduce** the problem.

 when I  use `UI Localizations` feature of angular,
 follow [abp document ](https://docs.abp.io/en/abp/latest/UI/Angular/Localization#ui-localizations) 
1.add `localizations` to `CoreModule` by forChild:
```typescript
@NgModule({
  declarations: [HomeComponent],
  imports: [
    SharedModule,
    HomeRoutingModule,
    CoreModule.forChild({
      localizations: [
        {
          culture: 'en',
          resources: [
            {
              resourceName: 'MyProjectName',
              texts: {
                Administration: 'Administration',
                HomePage: 'Home',
              },
            },
          ],
        },
        {
          culture: 'de-DE',
          resources: [
            {
              resourceName: 'MyProjectName',
              texts: {
                Administration: 'Verwaltung',
                HomePage: 'Startseite',
              },
            },
          ],
        },
      ],
    }),
  ],
})
export class HomeModule {}
```
2. Use angular Ui to Login in app by `code` or `password` flow
3. `angular-oauth2-oidc`  will broke,you will see `Login` button on home page
![image](https://user-images.githubusercontent.com/16490084/164974397-4abd47ea-40a7-4baf-ab88-c463d91da793.png)

**Comment by muhammedaltug** [comment]
Hello, thanks for the reporting issue.  I fixed with https://github.com/abpframework/abp/pull/12967
