### ISSUE TITLE
context.Services.OnRegistred in PreConfigureServices is not triggered for Manually Registered services

### ISSUE THREAD

**Issue by mannok** [abpframework/abp#12359]
### Documentation

Have checked for documentation at https://docs.abp.io/en/abp/4.4/Dependency-Injection, [**Manual Registration** and **OnRegistred section**]

### GitHub Issues

* Your **ABP Framework version**: **Version 5.1.4 (Stable)**
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: **Console**
* Your database provider(EF Core/MongoDB): **N/A**
* Exception message and **stack trace** if available (check the logs): **No stacktrace as it was not triggered**
* Steps needed to **reproduce** the problem.

![image](https://user-images.githubusercontent.com/458220/165212850-65985355-30a7-4677-b719-2388eb3205ca.png)

As you see, I manually registered a service `CamundaWorkerService` for `ICamundaWorkerService` in `ConfigureServices`. However, in `PreConfigureServices` -> `context.Services.OnRegistred`, no callback have `ctx` with `ctx.ImplementationType.Name.Contains("CamundaWorker")`. Meanwhile, if I implement an interface in `CamundaWorkerService`, the `ctx.ImplementationType.Name.Contains("CamundaWorker")` could be matched. 

It is expected that no matter the service is registered manually or not (by implementing dependency interface), it could be passed into `context.Services.OnRegistred` while the current situation is not work like that.

**Comment by maliming** [comment]
hi

You can try to register your service without using **ImplementationFactory**.

**Comment by mannok** [comment]
@maliming Could you elaborate more? Don't quite understand

**Comment by maliming** [comment]
Instead of using lambdas to create services, you can use: `services.AddTransient<IService, Service>();` or
```cs
var server = new Service();
services.AddTransient<IService>(server);
```

**Comment by mannok** [comment]
@maliming Thanks for helping. However, I cannot find the method signature as you described.
```
var server = new Service();
services.AddTransient<IService>(server);
```
![image](https://user-images.githubusercontent.com/458220/165237503-c725132a-24bc-4b46-abc8-d918b3d45301.png)



No overload can let me do it like `services.AddTransient<IService>(server);`. For my case, I couldn't use `services.AddTransient<IService, Service>();` as I have custom initialization logic for my registration

**Comment by maliming** [comment]
>  I have custom initialization logic for my registration

You can custom the `AbpAutofacServiceProviderFactory`

[AbpAutofacServiceProviderFactory](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Autofac/Volo/Abp/Autofac/AbpAutofacServiceProviderFactory.cs#L30)  and [AbpAutofacHostBuilderExtensions](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Autofac/Microsoft/Extensions/Hosting/AbpAutofacHostBuilderExtensions.cs#L17)

**Comment by mannok** [comment]
@maliming Am I getting lost? Originally, I have customized my service using `context.Services.AddTransient<>()`. However, this registration doesn't trigger `context.Services.OnRegistred`. You suggest me to register without `ImplementationFactory`. However, I find that there is no way to register a transient service without using `ImplementationFactory`

Sorry for getting lost

btw, seems this is a bug? I can expect this will occur in web project as well. Manual Registration is a common operation in ABP DI. `OnRegistered` Event should not omit manual registration

**Comment by rqx110** [comment]
you can see, it has not implement yet: (mark as `TODO`)
https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Autofac/Autofac/Extensions/DependencyInjection/AutofacRegistration.cs#L201-L213

**Comment by mannok** [comment]
@rqx110 so this means ABP doesn't support `OnRegistered` event for manually registered service at the moment? right?

**Comment by maliming** [comment]
ABP doesn't support OnRegistered events for `use Factory to create the services`

https://medium.com/null-exception/factory-pattern-using-built-in-dependency-injection-of-asp-net-core-f91bd3b58665

**Comment by mannok** [comment]
@maliming Is there any simple workaround for this? The reason I don't implement `ITransientDependency` in Implementation class is because its constructor has dynamic input params value. I cannot simply implement `ITransientDependency` to let the engine create the service for me.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/12359#issuecomment-1109420604

**Comment by mannok** [comment]
@maliming I think this cannot address my problem. The `AbpAutofacServiceProviderFactory` and `AbpAutofacHostBuilderExtensions` only responsible for how the implementation is created for some interface. The problem now is that the Castle Proxy is not created for some implementation. There is no way for me to achieve that in `AbpAutofacServiceProviderFactory` nor`AbpAutofacHostBuilderExtensions` 

I think what I should do is to create a proxy of a service and register it for some interface, i.e.
```
var service = new AbpProxy<IService>(new Service(), new AnInterceptor());
services.AddTransient(service);
```
