### ISSUE TITLE
AbpDecimalConverter

### ISSUE THREAD

**Issue by George-Vlad** [abpframework/abp#12360]
Hi,

If I use GET ajax in API Module the breakpoint hit my Write method.
But if I POST the model with the decimal property in, the ajax POST not hit my WriteorRead` or method and the result is not that I aspect.
This is happened with Romanian language selected.

```
public class AbpDecimalConverter: JsonConverter<decimal>
{
    public override decimal Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.String)
        {
            var s = reader.GetDecimal();
        }

        throw new JsonException("Reader's TokenType is not String!");
    }

    public override void Write(Utf8JsonWriter writer, decimal value, JsonSerializerOptions options)
    {
        writer.WriteNumberValue(value);
    }
}
```
// my ApiHostModule
```
context.Services.Configure<JsonOptions>(options =>
{
    options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals;

    options.JsonSerializerOptions.Converters.Add(new AbpDecimalConverter());
});
```
I also try with [JsonConverter(typeof(AbpDecimalConverter))] on my decimal property.

I find something similar https://github.com/abpframework/abp/issues/10566.

Also @totpero posted [here](https://github.com/abpframework/abp/issues/11334) the same issue but no answers

**Comment by maliming** [comment]
hi

You can try this without ABP.

**Comment by George-Vlad** [comment]
Had the same problem on aspboilerplate, solved with CustomBinder but there we have newtonjson

**Comment by George-Vlad** [comment]
@maliming why the issue was closed? Is there any solution for this?

**Comment by maliming** [comment]
You can try to add the convert to [AbpJsonOptions](https://docs.abp.io/en/abp/latest/JSON#configuration)
