### ISSUE TITLE
Add Enum for Volo.Abp.EntityFrameworkCore. EfCoreDatabaseProvider

### ISSUE THREAD

**Issue by SarcoZ** [abpframework/abp#12399]
My project need supper for DM datatbase, but enum EfCoreDatabaseProvider on this,I can not extend

`public enum EfCoreDatabaseProvider
{
    SqlServer,
    MySql,
    Oracle,
    PostgreSql,
    Sqlite,
    InMemory,
    Cosmos,
    Firebird,
}
`
Can add Dm after Firebird

**Comment by JadynWong** [comment]
I don't think it prevents you from using other EFCore providers. Or if you have any exception info?

It looks like it is prepared for the following.
https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/docs/en/Blog-Posts/2020-06-05%20v2_9_Release/Post.md#automatically-determining-the-database-provider

**Comment by realLiangshiwei** [comment]
This is not related to ABP but EF Core.

You can check the database providers of EF Core: https://docs.microsoft.com/en-us/ef/core/providers/
