### ISSUE TITLE
Switch to YARP in microservice-pro template

### ISSUE THREAD

**Issue by barnybadzoo** [abpframework/abp#12429]
It would be great if you could switch to YARP in your microservice-pro template instead ocelot/envoy..

**Comment by barnybadzoo** [comment]
You 've done it in eshoponabp, hope you also will do it in microservice-pro

**Comment by gterdem** [comment]
Yarp is a reverse proxy instead of a gateway. We are planning easier ways to switch gateways. But for now, we decided to keep ocelot.

**Comment by leonkosak** [comment]
@gterdem any status update on this? Ocelot is basically dead. gRPC functionality for API gateway is probably one of the most desired features to go away from Ocelot.

**Comment by gterdem** [comment]
@leonkosak Thank you.

l will discuss this with the team.

**Comment by leonkosak** [comment]
@gterdem any updates on this feature?
