### ISSUE TITLE
abp cli auto switch to dev and cmd abp switch-to-stable error

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#12426]
* Your **ABP Framework version**.
   v5.2.1

Question 1:
After I run abp suite update then abp suite my abp cli auto swith from Stable to Development version, please see screenshot 1

Question 2:
I run abp switch-to-stable occured  **"Access to the path C:\Users\GerryGe\Application Data' is denied."**  error.
I would like to know why need access this folder? I have tried two computers and both cannot access this folder even I am the administrator role.
By the way, my pc one is win10 enterprise and I can find the "Application Data" foleder, but I cannot access it.
the other one pc is win 11 enterprise and I cannot find the folder even I have showed the hidden folders. I try to create the folder with error the same same file have existed. So actully it exist, just I cannot see it, please see screenshot 3.

![image](https://user-images.githubusercontent.com/6952917/166623572-8324bbb7-7b63-4ee5-b5f2-9ef376cabd46.png)

![image](https://user-images.githubusercontent.com/6952917/166623632-d784f463-82b3-4128-be7c-2fece62a4aac.png)

![image](https://user-images.githubusercontent.com/6952917/166624761-2f0b51a7-def5-47c7-ba0c-2545658ef5ee.png)

**Comment by realLiangshiwei** [comment]
Hi,

What is the result when you run `dotnet tool list -g` command

**Comment by gerryge** [comment]
@realLiangshiwei Please see my screenshot.

![image](https://user-images.githubusercontent.com/6952917/166655182-b19c0977-e1a9-4085-8973-3fee0545cebf.png)

**Comment by realLiangshiwei** [comment]
I'm not sure the reason, maybe there is something wrong with your environment.

>   // If not a tool executable, fallback to assembly version and treat as dev without updates

See the logic: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/CliService.cs#L205

You can download the source code to debug.

**Comment by gerryge** [comment]
I cannot agree because my two pcs occured this issue.  And why use "Application Data" folder?

**Comment by realLiangshiwei** [comment]
> And why use "Application Data" folder?

`abp switch-to-stable` is used to **change the Nuget package reference of the solution**, it will find a solution in the current directory(including subdirectories).

**Comment by gerryge** [comment]
The second question is because I use my profile folder, I should use the abp project root folder.
But the first question why after I run abp suite cmd, the abp version changed?

**Comment by camping89** [comment]
same issue for me as of 2023.02.09. still happening

**Comment by realLiangshiwei** [comment]
@camping89 
Please create a new issue, thanks.
