### ISSUE TITLE
Openiddict status

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#12425]
I've been following the commits on the openiddict module branch and it looks like things are pretty complete. Should it be usable at this point (at least for initial testing)? Any docs/instructions available (even if rough at this point)? Thanks!

**Comment by maliming** [comment]
Hi

We **plan** to release stable `Openiddict` packages in 5.4. Update the templates in 6.0.


https://github.com/abpframework/abp/blob/Module-OpenIddict/docs/en/Modules/OpenIddict.md

ABP commercial

![image](https://user-images.githubusercontent.com/6908465/165052353-b3925a40-8575-4cf8-8626-e06f182adc60.png)

![image](https://user-images.githubusercontent.com/6908465/165052334-94371132-d9c8-407d-85bb-37ec5ebc09bb.png)

![image](https://user-images.githubusercontent.com/6908465/165052376-56370d47-6344-4e15-8fd4-bc64bbfeda20.png)


![image](https://user-images.githubusercontent.com/6908465/165052862-12fb08df-fae1-454d-93c0-d5cfe88f5cc4.png)

![image](https://user-images.githubusercontent.com/6908465/165052884-044e1463-3749-4e7f-95eb-cd681c2b53eb.png)

**Comment by parasdaryanani** [comment]
Will there be an migration path to openiddict from identityserver4?

**Comment by maliming** [comment]
of course, we will prepare it.
