### ISSUE TITLE
String encryption issue with input string not divisible by 16

### ISSUE THREAD

**Issue by parasdaryanani** [abpframework/abp#12424]
GET: `/api/setting-management/emailing` only returns the first 32 chars of the SMTP password. In reality my SMTP password string is 40 characters.

It looks like string encryption does not work for strings that are not divisible by 16. If I supply a 32 char string, it encrypts / decrypts just fine. Same for a 48 char string. But with a 40 char string (in this case an AWS SES secret access key), it encrypts / decrypts only the first 32 chars of the string.

Is there an acceptable way to pad this 40 char string to a length that is divisible by 16 (e.g. 48 chars)? Or does the encryption algorithm need to be changed?

### Example with a 32 char smtp password string, encrypting/decrypting correctly:

POST: `/api/setting-management/emailing`
```json
{
  "smtpPassword": "ThisStringIsThirtyTwoCharsInLeng"
}
```
GET: `/api/setting-management/emailing`
```json
{
  "smtpPassword": "ThisStringIsThirtyTwoCharsInLeng"
}
```

### Example with a 40 char smtp password string, truncating string to 32 chars:

POST: `/api/setting-management/emailing`
```json
{
  "smtpPassword": "ThisStringIs40CharsInLengthRandomText123"
}
```
GET: `/api/setting-management/emailing`
```json
{
  "smtpPassword": "ThisStringIs40CharsInLengthRando"
}
```

* ABP version 4.4.4
* Headless (No UI)
* EF Core MySQL

**Comment by parasdaryanani** [comment]
Update: I cannot reproduce this locally, it only occurs in production...which is worse.

I have tried:
- padding the password string with multiple '=' to get it to 48 chars.
- checking the db column max length to check if that's the issue
- setting the password encrypted value in appsettings.json directly, but this also doesn't not work.

**Comment by parasdaryanani** [comment]
Update: I believe it may be due to a breaking change in .NET 6:

> Starting in .NET 6, when Stream.Read or Stream.ReadAsync is called on one of the affected stream types with a buffer of length N, the operation completes when:
> 
> At least one byte has been read from the stream, or The underlying stream they wrap returns 0 from a call to its read, indicating no more data is available.

Ref: https://stackoverflow.com/a/69911546/3772543

**Comment by realLiangshiwei** [comment]
Hi,
> ABP version 4.4.4
> Update: I believe it may be due to a breaking change in .NET 6:

We upgraded to NET 6.0 in ABP version 5.0: https://github.com/abpframework/abp/blob/dev/docs/en/Blog-Posts/2021-11-18%20v5_0_Preview/POST.md#migration-notes--breaking-changes

And I could not reproduce the problem:

![image](https://user-images.githubusercontent.com/16813853/166449367-ec18606a-e819-4eb0-9dfa-25a53f104c43.png)

Can you provide a repo?

**Comment by parasdaryanani** [comment]
The issue occurred due to running ABP 4.4.4 on .NET 6.0. using the .NET version `rollForward` property.
I fixed the issue by upgrading the project to ABP 5.2.1.
