### ISSUE TITLE
Suggestion: Better exceptions when accessing repositories outside Uow Scope

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#12440]
Currently an ObjectDisposedException is thrown when accessing repository methods outside a unit of work scope. This is a confusing exception as it doesn't clearly state what the issue is. My suggestion is to throw a custom exception that clearly communicates why this happens.

**Comment by maliming** [comment]
I will check this exception. :)

**Comment by maliming** [comment]
Hi

As mentioned in the documentation, it is difficult for us to catch this exception.

https://docs.abp.io/en/abp/latest/Testing#dealing-with-unit-of-work-in-integration-tests
