### ISSUE TITLE
eShopOnAbp: Consider deploying reference to artifact hub

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#12445]
We can publish the eShopOnAbp helm chart on https://artifacthub.io as reference.

**Comment by skoc10** [comment]
https://leeyoongti.medium.com/helm-in-kubernetes-part-4-publish-helm-chart-to-artifact-hub-using-github-pages-ab7f55904faa

**Comment by skoc10** [comment]
https://artifacthub.io/packages/helm/abp-charts/eshoponabp

**Comment by gterdem** [comment]
It seems to be deployed at: https://artifacthub.io/packages/helm/eshoponabp/eshoponabp

@skoc10,
Can we deploy it to `abp-charts/eshoponabp` as linked?

**Comment by skoc10** [comment]
> @skoc10, Can we deploy it to `abp-charts/eshoponabp` as linked?

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/64414348/185556043-ae792871-c6d1-40f1-9475-b24d0f4f92df.png">
https://artifacthub.io/packages/helm/abp-charts/eshoponabp?modal=install

**Comment by gterdem** [comment]
Deployed to https://artifacthub.io/packages/helm/abp-charts/eshoponabp
Closing the issue.
