### ISSUE TITLE
Returns meaningless value in permission setting on User management page

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#12450]
**Version:** `5.3.0`
**App:** Angular - MAngo DB

Releated https://github.com/abpframework/abp/issues/11821
Releated  https://github.com/volosoft/volo/issues/9581

![image](https://user-images.githubusercontent.com/99716457/167075600-8258bb84-7615-4a31-94d9-4f372ffa247b.png)

**Comment by mahmut-gundogdu** [comment]
I couldn't produce.

![image](https://user-images.githubusercontent.com/2217899/167503586-aa56278d-6bf1-43d1-b782-577808ae2a17.png)


![image](https://user-images.githubusercontent.com/2217899/167503651-eadc3efd-3e11-4de1-a4ca-3c6b6a8ce2a3.png)

**Comment by mahmut-gundogdu** [comment]
![image](https://user-images.githubusercontent.com/2217899/167503846-ede2b891-a2c9-476d-a754-87a7bcf3ab9b.png)
I've checked roles and users. Still, I couldn't produce

**Comment by gizemmutukurt** [comment]
I ran it with the following command and tried again and repeated the error. Can you try to run it with this command?
`abp new Angular.MoongoSeperated220509  -t app -u angular -m none --separate-identity-server --database-provider mongodb -csf --preview`

![image](https://user-images.githubusercontent.com/99716457/167613696-dd72be79-bade-49ef-a617-9e5aa2a84ba1.png)

**Comment by ebicoglu** [comment]
@gizemmutukurt this is PRO template not open-source

**Comment by gizemmutukurt** [comment]
> @gizemmutukurt this is PRO template not open-source

Sorry, I ran it by removing the -pro statement from the command while I was running it, but I skipped it while copying, but Mahmut corrected the error by executing the command properly.
