### ISSUE TITLE
Can't create 5.3.0-rc.1 project

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#12457]
ABP Framework version: 5.3.0-rc.1

If I create a new project from the Getting Started and check the "Use latest pre-release version (5.3.0-rc.1)" The project created is version 5.2.1 (see project references in the screenshot)

![2022-05-06_10-41-51](https://user-images.githubusercontent.com/69393775/167108714-2c9826fb-9927-4e9a-9fa2-b10936a94320.png)

![2022-05-06_10-44-05](https://user-images.githubusercontent.com/69393775/167108896-80e8df21-ed3a-40a1-8d7e-fe9ba4a696fa.png)

**Comment by yekalkan** [comment]
Thanks for the reporting. We're currently working on it.
