### ISSUE TITLE
ApplicationLayer Insert or DomainService Insert？

### ISSUE THREAD

**Issue by imxiongstu** [abpframework/abp#12466]
Hi,Everyone. I am developer from china,I have a question about Abp，Hope everybody can give directions

### Question
Why are books different from reality？

>official documentation demo similar to the:
```cs
public class IssueManager : DomainService
{
    private readonly IRepository<Issue, Guid> _issueRepository;

    public IssueManager(IRepository<Issue, Guid> issueRepository)
    {
        _issueRepository = issueRepository;
    }
    
    public async Task<Issue> CreateAsync(Issue issue)
    {
        //TODO:xxxxx
        return issue;
    }    
}
```
But I see abb source code most of such:
```cs
public class IssueManager : DomainService
{
    private readonly IRepository<Issue, Guid> _issueRepository;

    public IssueManager(IRepository<Issue, Guid> issueRepository)
    {
        _issueRepository = issueRepository;
    }
    
    public async Task<Issue> CreateAsync(Issue issue)
    {
        //TODO:xxxxx
       await respository.insertasync(issue);
        return issue;
    }    
}
```

so,I wonder why，Shouldn't it be in `Application Layer` InsertAsync? 

end，Thank you again for

**Comment by maliming** [comment]
hi

If the `Create` is just a simple `insert` you can directly use the `_issueRepository ` in `Application Layer` otherwise do it in `Domain Layer` for some business logic.

**Comment by imxiongstu** [comment]
您的邮件我已经收到，请耐心等待回复熊www.imxiongstu.cn

**Comment by imxiongstu** [comment]
> hi
> 
> If the `Create` is just a simple `insert` you can directly use the `_issueRepository ` in `Application Layer` otherwise do it in `Domain Layer` for some business logic.

thanks,
so，Either way, right?  The official recommendation ApplicationLayer Insert ，DomainService It just returns the instance object。Still confused.

**Comment by imxiongstu** [comment]
why abp sourcecode in `DomainService` insert persistence?

**Comment by imxiongstu** [comment]
您的邮件我已经收到，请耐心等待回复熊www.imxiongstu.cn
