### ISSUE TITLE
repository.UpdateAsync failed if don't return data

### ISSUE THREAD

**Issue by wensaint** [abpframework/abp#12464]
ABP version: v5.2.1
db provider: EF Core

in domain service, i inject repository, but failed on updateAsync if throw exception or return null other than return data

error Code:
``` 
  if (!VerifyHashedPassword(data, password))
  {
      Admin.UpdateLoginErrorInfo(data, minute < minLoginPeriod);
     // update will fail if throw exception or return null;
      await _repository.UpdateAsync(data, autoSave: true);
     // if return data, then the update action will succeed
     // return data;
      throw new AdminAccountOrPasswordNotMatchException(account);
  }
  //更新登录记录
  Admin.UpdateLoginInfo(data);
  // this will succeed
  return await _repository.UpdateAsync(data, autoSave: true);
```

can anyone tell me why?

**Comment by maliming** [comment]
Try to remove `app.UseUnitOfWork()` from the ASP.NET Core pipeline.

**Comment by wensaint** [comment]
Thanks @maliming

Inspired by https://support.aspnetzero.com/QA/Questions/1797/SaveChanges-not-saving-data-to-db-immediately

Add [UnitOfWork(false)] to my controller action, everything works fine.

So i close this issue.

**Comment by wensaint** [comment]
Thanks @maliming

Inspired by https://support.aspnetzero.com/QA/Questions/1797/SaveChanges-not-saving-data-to-db-immediately

Add [UnitOfWork(false)] to my controller action, everything works fine.

So i close this issue.

**Comment by maliming** [comment]
Don't do that. UOW is a important feature.
