### ISSUE TITLE
Data is not stored to respective tenant database 

### ISSUE THREAD

**Issue by saitejkuralla** [abpframework/abp#12475]
ABP Framework version 5.0

User Interface:MVC

database provider: EF Core

**Steps needed to reproduce**:  I have followed the step-by-step process of: https://docs.abp.io/en/abp/latest/Multi-Tenancy and I have added the connection string details of each tenant in **"AbpTenantConnectionStrings"** and created databases of each tenant( Tenant1 & Tenant2 ) as TODOAPP1 & TODOAPP2 but when I save the data to database the data is stored in the default database (TODOAPP) but not in the tenant-specific database. 
am I missing anything here?
How to configure Per tenant one database?

![image](https://user-images.githubusercontent.com/11627655/167299129-9e291aa4-ac32-4af5-94b9-3a99ef65bb9e.png)

![image](https://user-images.githubusercontent.com/11627655/167298713-4abe4b18-1e65-4bc3-a04c-8ca4c0cc2c11.png)

**Comment by JadynWong** [comment]
`Name` is the name of the connectionstring. You can set `Default` for it.

**Comment by saitejkuralla** [comment]
yes it is set to default only but the data is getting stored in the default connection/Database, not in the newly created databases (TODOAPP1 & TODOAPP2)
![image](https://user-images.githubusercontent.com/11627655/167343069-ac4bfff3-fc39-480f-b67f-3c3fb7608329.png)

**Comment by JadynWong** [comment]
![image](https://user-images.githubusercontent.com/13699353/167348700-4388b5bd-2d16-48f5-8c0d-b5cb7661f238.png)

**Comment by saitejkuralla** [comment]
Nope, I have changed it accordingly. it didn't work, data is not stored with the tenant-specific database.
![image](https://user-images.githubusercontent.com/11627655/167354204-63a512ea-e22f-4377-8f81-e7d6706b21c8.png)

**Comment by JadynWong** [comment]
I can not reproduce. Can you provide a simple project to reproduce it?

**Comment by saitejkuralla** [comment]
sample code: https://github.com/saitejkuralla/TodoApp_Multitenancy

Below is the recent change in my code 
![image](https://user-images.githubusercontent.com/11627655/167435602-2aa7dab0-48b2-431f-a69a-a94dc4a2254f.png)

**Comment by JadynWong** [comment]
> sample code: https://github.com/saitejkuralla/TodoApp_Multitenancy

404
![image](https://user-images.githubusercontent.com/13699353/167437637-5c3107a4-76bf-4ed8-aec6-d5041b6e83c4.png)


> Below is the recent change in my code ![image](https://user-images.githubusercontent.com/11627655/167435602-2aa7dab0-48b2-431f-a69a-a94dc4a2254f.png)

You don't need to modify AbpDbContext. Multi-Tenancy connectionstring switching in abp is out-of-the-box.

**Comment by saitejkuralla** [comment]
updated the repo to "public" but without switching that I am unable to do that, could you help me out with that. the final requirement is to save the data in tenant specific database.
By doing the above change the login credentials are part of the default database and I was unable to login now.
**Note** : if there is any sample code for per tenant database that would be great

**Comment by JadynWong** [comment]
- Remove the changes you have made to AbpDbContext.

- Please submit todo content after select a tenant.It is best to be able to login to the tenant user. Or use other ways of switching tenants (querystring, cookies, header, ...).  https://docs.abp.io/en/abp/latest/Multi-Tenancy#tenant-resolvers


![image](https://user-images.githubusercontent.com/13699353/167451530-3a86d164-5c64-4e94-a4f0-180326b2f793.png)

**Host**

![image](https://user-images.githubusercontent.com/13699353/167451300-db885389-beeb-4cf8-bba6-c8dfff5398c9.png)

**Tenant1**

![image](https://user-images.githubusercontent.com/13699353/167451688-844e30c3-ea8f-4a5e-8279-521249436fa3.png)

#### querystring switch tenant

![GIF](https://user-images.githubusercontent.com/13699353/167452878-0fc318e6-6128-4ade-81d9-a8f83d41291c.gif)

![image](https://user-images.githubusercontent.com/13699353/167454253-da5b549b-3e0d-4695-b767-f91a5d8539c8.png)

**Comment by saitejkuralla** [comment]
sorry for this again the data is saved only in Default Database (TODOAPP) as tenant-specific.
Yes using query string and switching the tenant I have submitted the data 
Am I missing anything here 
![image](https://user-images.githubusercontent.com/11627655/167458032-96e1d51e-e1e9-4f2f-9441-1ce203aa53f7.png)

**Comment by JadynWong** [comment]
I only removed your changes to AbpDbContext.

![image](https://user-images.githubusercontent.com/13699353/167523031-9158629e-96a8-45b4-b902-cbd3dbda1dcc.png)


```SQL
select AbpTenants.Id, AbpTenants.Name, AbpTenantConnectionStrings.Name, AbpTenantConnectionStrings.Value
from AbpTenants 
left join AbpTenantConnectionStrings on AbpTenants.Id = AbpTenantConnectionStrings.TenantId
```

![image](https://user-images.githubusercontent.com/13699353/167522791-1f5db8d2-127b-4bf5-85c2-0adc46b6d9d7.png)

**Comment by saitejkuralla** [comment]
If the same code is not working for me hope it should be a bug .is that an environment issue?
