### ISSUE TITLE
Abp Blazor Server Audit Not Working

### ISSUE THREAD

**Issue by coskunkula** [abpframework/abp#12476]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* 5.2.1.
* Blazor Server
* EF Core

I am using abp framework 5.2.1 version. I am running an application as a Blazor server. I need to use audit features. When I update any record, log and audit log are not kept. As a result of my long research, I ran the SaveChangesAsync method in DbContext.cs class by overrride and
var auditLog = AuditingManager?.Current?.Log; On line Current comes as null. I'm guessing it might be because of that. 
but when I update using swagger, audit logs are working. When I do it using blazor it doesn't work.
How can I do it?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/11682#issuecomment-1066064249
