### ISSUE TITLE
Update AuthServer UI

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#12478]
_Original Title as "When the user looks at the login button after logging out, it redirects to the Identity Server page and template login is blocked."_

**App:** Blazor WASM, Blazor Server, MVC
**Version:** `5.3.0-rc.1`
**Problem Definition:**  When the user looks at the login button after logging out, it redirects to the Identity Server page and template login is blocked.

### Screenshot
![4bdbd9cc-278c-415e-9019-f77fc560d8d5](https://user-images.githubusercontent.com/99716457/167340552-16bd8f58-c148-4946-b196-69ff4435e97e.gif)

**Comment by gterdem** [comment]
When you are logged out, signed out page is shown at IdentityServer. You are in the IdentityServer application when you are trying to login back. So, there is no return URL to return to after login.

This confusion is happening because IdentityServer and the application is sharing the same top menu, making user to think they are in the same application.

**Comment by ebicoglu** [comment]
how about changing this page as below
![image](https://user-images.githubusercontent.com/9526587/168597046-66da545f-fcbe-49b3-bc7c-84fffb207572.png)

**Comment by ebicoglu** [comment]
Real world example: 
When you sign in from drive.google.com it redirects you to the account.google.com . you sign out from drive.google.com , then it redirects you back to  account.google.com . finally you sign in from account.google.com  but it redirects you to drive.google.com . it doesn't stay on account.google.com.
so we should keep the main application url in returnUrl and redirect back to it.

**Comment by gterdem** [comment]
> Real world example: When you sign in from drive.google.com it redirects you to the account.google.com . you sign out from drive.google.com , then it redirects you back to account.google.com . finally you sign in from account.google.com but it redirects you to drive.google.com . it doesn't stay on account.google.com. so we should keep the main application url in returnUrl and redirect back to it.

Is creating different layout for identityserver templates (like account.abp.io) the final decision to proceed with this issue? 
@ebicoglu Can you confirm?

**Comment by ebicoglu** [comment]
we'll change the IDS design like this https://github.com/abpframework/abp/issues/12478#issuecomment-1127636806

**Comment by enisn** [comment]
Progress:
- [x] https://github.com/abpframework/abp/pull/13026
- [x] https://github.com/volosoft/volo/pull/10778
- [x] https://github.com/volosoft/volo/pull/10820
- [x] https://github.com/abpframework/abp/pull/13075
