### ISSUE TITLE
Integration Services

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12470]
Application Services are ideal to be consumed by UI and other clients. We, sometimes, are also using an application service of a module X from a module Y to integrate these modules (or microservices).

There are some problems of using application services for inter-module (or inter-microservice) calls:

* They are specifically designed for UI scenarios (use cases), but inter-module calls have different requirements (different data (DTO) needs, different use cases, they differently evolve by the time, etc).
* We generally don't want to apply authorization for inter-module/service calls. But, if we use an existing authorized app service endpoint, we have to disable authorization conditionally (ugly) or have to authenticate microservices as clients.
* We may need different level of caching and other cross-cutting concerns.
* Most app services might be designed to be used by a user (`ICurrentUser.Id` is available), so requires a kind of user-session, so it becomes problem while consuming from a client without an active user interaction.

You may find other reasons too...

So, my offer is to introduce `IIntegrationService` (implemented by the integration service classes) that is specifically designed for inter-module/service calls. They will have similar defaults with app services (like auto [unitofwork](https://docs.abp.io/en/abp/latest/Unit-Of-Work), validation, and authorization if you want) and they can also be exposed as [conventional API controllers](https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers).

Default HTTP API URL prefix for such services can be `/internal-api/` or `/integration-api/` instead of `/api/`. In this way, we can easily block request against these endpoints and safely consume them internally in our microservice cluster for inter-microservice calls.

Integration service classes can be located inside the `YourProject.Application` project of your solution (and their contracts in `YourProject.Application.Contracts`), if you don't want to create additional .NET projects in your solution. But, if you want (I think it would be much better for maintainability), you can create `YourProject.IntegrationServices` and `YourProject.IntegrationServices.Contracts` projects in the solution.

**Comment by nebula2** [comment]
One may also have clients/ customers/ end users interacting with the api which would fit into the term of integration. for example when you sync data bidirectional from client system to abp application. 

If you expose controllers for the users to write their own integrations, it is common to have some throttling - which is something I do not see in the integration context you're referring to. It may well be that inter-microservice-services differ from the client-services in functionality. 

- Do my thoughts even make sense?
- Does it mean, this should be further specified to reduce confusion on terminology (or am I just wrong)
- Does it mean there may be further separation in future?

**Comment by hikalkan** [comment]
@nebula2
I don't know. But you gave me an idea :) Instead of separation, we may just define an `[IntegrationService]` attribute to put on top of application services to set defaults/conventions for these kind of services. In this way, we don't create a parallel system for similar purposes.

**Comment by gdlcf88** [comment]
Please also consider the possibility of integrating Dapr. The relevant designs should not conflict when using Dapr to replace the default implementation.

**Comment by dicksonkimeu** [comment]
Best idea

we may just define an [IntegrationService] attribute to put on top of application services to set defaults/conventions for these kind of services. In this way, we don't create a parallel system for similar purposes.

**Comment by muratyuceer** [comment]
Actually, we are using application services for intercommunication default.
For UI/users we are creating BFF (backend for frontend) services (separated API projects). There are designed for use by UI/user and communication with application services according to need (for admin panel and mobile application you could create two bff).

**Comment by git102347501** [comment]
In fact, for this kind of behavior, my usual approach is to allow open non session access, and then logically judge whether permissions and current session information conform to the business scenario in the App layer, which makes the verification logic of the App more and more complex...
