### ISSUE TITLE
Method not found : GetOrAddController

### ISSUE THREAD

**Issue by saitejkuralla** [abpframework/abp#12473]
* ABP Framework version 5.0
* User Interface MVC
* database provider: EF Core
*** Exception message and **stack trace** 
Method not found: 'Volo.Abp.Http.Modeling.ControllerApiDescriptionModel Volo.Abp.Http.Modeling.ModuleApiDescriptionModel.GetOrAddController(System.String, System.String, System.Type,** 

* Steps needed to **reproduce**
I Have added the todo application to the main library code to debug my todo application and when I try to run the application I am getting the error 

![image](https://user-images.githubusercontent.com/11627655/167297585-e90f6de5-1fc6-48c2-b05d-cd6a2f741e65.png)

**Comment by realLiangshiwei** [comment]
> Steps needed to reproduce
> I Have added the todo application to the main library code to debug my todo application and when I try to run the application I am getting the error

These steps are not enough to reproduce, can you provide all steps or a simple project to reproduce?

**Comment by saitejkuralla** [comment]
I have added the TODO sample application and referenced  "Volo.Abp.AspNetCore.MultiTenancy" project and ran the application then I am ending up with the above error.
![image](https://user-images.githubusercontent.com/11627655/167381902-769b4de2-e562-42bb-939c-0c123d7f7162.png)

**Comment by realLiangshiwei** [comment]
I guess you are mixing Nuget and local packages.

The Todo App uses Nuget package references:

https://github.com/abpframework/abp-samples/blob/master/TodoApp/Mvc-EfCore/src/TodoApp.Web/TodoApp.Web.csproj#L44-L52

You should only use NuGet packages or local references, don't mix.
