### ISSUE TITLE
Configuration Data Store of tenants as appsettings.json instead of tenant management

### ISSUE THREAD

**Issue by saitejkuralla** [abpframework/abp#12474]
ABP Framework version 5.0

User Interface MVC

database provider: EF Core

Steps needed to reproduce: I have followed the step-by-step process of: https://docs.abp.io/en/abp/latest/Multi-Tenancy and configured the datastore in appsettings.json instead of using tenant management but unfortunately, the application is not picking the information of tenants from appsettings.json file of TodoApp.Web am I missing something here?

Do I need to remove any references for tenant management? 

![image](https://user-images.githubusercontent.com/11627655/167298394-4e472f95-3ce7-4500-9566-d6ada26c06f9.png)

**Comment by JadynWong** [comment]
It is the default implementation. Yes, you should uninstall the tenant management module (remove `Volo.Abp.TenantManagement.*` nuget references).
 https://docs.abp.io/en/abp/latest/Multi-Tenancy#configuration-data-store
