### ISSUE TITLE
abp and dx components: UTF-8 encoding for styles

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#12495]
How to properly enable UTF-8 charset in abp framework (MVC frontend) using BundleContributor?
Official announcement: https://supportcenter.devexpress.com/ticket/details/t977747/theme-files-are-shipped-with-the-utf-8-encoding-starting-with-v20-2

I follow this article, but there is no mention of UTF-8 charset, because it is too old (dx v20.2 was released in November 2020, this article is from August 2020): https://community.abp.io/posts/using-devextreme-components-with-the-abp-framework-zb8z7yqv

@maliming, do you have suggestion for resolving this issue? It is annoying to have incorrect symbols inside dx components.
Thank you.

**Comment by maliming** [comment]
hi

https://docs.abp.io/en/abp/latest/UI/AspNetCore/Bundling-Minification#configuring-an-existing-bundle
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Bundling-Minification#contributor-extensions

**Comment by leonkosak** [comment]
I know this, but there is no mention about setting charset.

**Comment by maliming** [comment]
You can add some custom CSS to the global binding, or change some file contents.
