### ISSUE TITLE
How do I add custom environment variables in Angular?

### ISSUE THREAD

**Issue by idreeshaddad** [abpframework/abp#12497]
**ABP Framework version:** v4.3.0

**User Interface** Angular v11.2.11

How do I add custom environment variables to environment.ts?
If I add say `customVar` and try to read it in a component it I get the error `Property 'customVar' does not exist on type 'Environment'`.

[Question on Stackoverflow](https://stackoverflow.com/questions/72178442/how-do-i-add-custom-environment-variables-to-abp-io-angular)

**Comment by realLiangshiwei** [comment]
You can check this: https://docs.abp.io/en/abp/latest/UI/Angular/Environment

**Comment by rqx110** [comment]
you can extend the `Environment` after v5.2, see https://github.com/abpframework/abp/pull/11951

**Comment by idreeshaddad** [comment]
> you can extend the `Environment` after v5.2, see #11951

Is there a way on v4.3 though?

**Comment by muhammedaltug** [comment]
Can you share your environment.ts and component.ts file

**Comment by idreeshaddad** [comment]
Sure.

- Setting it up in environment:
![image](https://user-images.githubusercontent.com/2285974/167657049-6acfb7dd-0789-4b0f-8e6c-6a04d5020b27.png)


- Trying to read it in the component:
![image](https://user-images.githubusercontent.com/2285974/167657323-31eb9a28-e6ac-4a50-b956-7ceaf0be8a4f.png)

**Comment by idreeshaddad** [comment]
Since I cannot upgrade to v5, I extended Environment interface like this #11950
