### ISSUE TITLE
Extended generic repository dependency injection error

### ISSUE THREAD

**Issue by mrcarl79** [abpframework/abp#12503]
I have read https://docs.abp.io/en/abp/latest/Repositories#custom-repositories FYI but this does not cover my issue which is extending the generic repository 

I have implemented the following code in my domain project:

```
public interface ICustomRepository<TEntity> : IRepository<TEntity, Guid>
    where TEntity : class, IEntity<Guid>
{
    bool Test(string name);
}
```

```
[Dependency(ReplaceServices = true)]
public abstract class CustomRepository<TEntity> : RepositoryBase<TEntity, Guid>, ICustomRepository<TEntity>, ITransientDependency
    where TEntity : class, IEntity<Guid>
{
    public CustomRepository()
    {
    }

    public bool Test(string name)
    {
        return true;
    }
}
```

But we get an error like this if we try to use it in an AppService:

Autofac.Core.DependencyResolutionException
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.CustomAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'XXX.Domain.Repositories.CustomRepository`1[CustomModel] customRepository' of constructor 'Void 

Wondering why is it not registering it for DI?

Thanks

**Comment by maliming** [comment]
hi

You need to register/replace the general type class manually.

```cs
context.Services.TryAddTransient(typeof(ICustomRepository<>), typeof(CustomRepository<>));
```
