### ISSUE TITLE
PWA Blazor app fetches most only .dll's (missing lot of other files)

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#12519]
Hi, we have been trying to get PWA to work with Blazor but are having a **partial success**. Dll´s are being downloaded but lots of other files are not downloaded (js,png, css, html etc)

As you can see .dll are being fetched by service worker but there are errors in other request.
![pwa](https://user-images.githubusercontent.com/2386572/167620903-bcc75d72-fb16-4e86-8095-d21146434096.png)

here are more failing files

![image](https://user-images.githubusercontent.com/2386572/167640842-2812103f-c578-4835-9d3a-20d78684861b.png)

And (probably) because of this we **don´t** get the Install button mechanism so no offline capability. But things sure load faster than before in the next refresh.

We have followed all instructions and gone over everything so we think its setup correctly.

**Any recommendations for us?**  

* Your **ABP Framework version**. 5.1.2
* Your **User Interface** type Blazor
* Your database provider: EF Core

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.
