### ISSUE TITLE
Build circular dependency involving EntityFrameworkCore and Domain

### ISSUE THREAD

**Issue by mrcarl79** [abpframework/abp#12525]
Following the docs I've created my own repository implementation like this:

https://docs.abp.io/en/abp/latest/Best-Practices/Entity-Framework-Core-Integration#repository-implementation

The "MyEfCoreRepository" is stored in EntityFrameworkCore project.

To access MyEfCoreRepository from our AppServices in the Application project I add a project reference to EntityFrameworkCore  which works fine.

But if I want to access MyEfCoreRepository in a DomainService in the Domain project I can't unless I added a reference to EntityFrameworkCore in that also. But if I do that I get a circular dependency error trying to build between Domain and EntityFrameworkCore.

What would the solution be here as can't find it in docs?

- If you create your own extended repository can you not use this in domain services?
- Or is there a way to create an extended repository that is not inherited from EfCoreRepository so can be kept in the domain project? (I tried this previously inheriting from RepositoryBase but could never get DI working)

**Comment by realLiangshiwei** [comment]
You need to create an `IMyRepository` interface for `MyEfCoreRepository`, and use it in the Domain project.
 
Like `IRepository`: https://docs.abp.io/en/abp/latest/Repositories#generic-repositories

The interface should be defined in the domain project
