### ISSUE TITLE
Localization not all translations showing after adding a language

### ISSUE THREAD

**Issue by pjkeukens** [abpframework/abp#12520]
* Your **ABP Framework version**. : 5.2.1 (commercial)
* User Interface: MVC
* Database provider: EF Core
* Steps needed to reproduce the problem.
*  1. Create a new application using ABP suite
*  2. Run appliation and login as admin
*  3. Go to language management
*  4. Add dutch language
*  5. run application, change language to dutch and go to login page
*  6. half of the resources are not translated (for example the resource UserNameOrEmailAddress)

This is weird as:
-> modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/Resources/nl.json 
has all the translated items.

but in Volo.Abp.Account.Pro.Shared.Application.Contracts\Volo\Abp\Account\Localization\Resources
nl.json is missing

![login_localization](https://user-images.githubusercontent.com/16360696/167645550-df2d07ae-8ef8-4101-b491-aa408d001ceb.JPG)

**Comment by realLiangshiwei** [comment]
Hi,

Dutch localization from ABP community contributions, we are not Dutch experts : )

You can translate missing text on page Language texts:

![image](https://user-images.githubusercontent.com/16813853/167744912-5d858fb5-9179-42c9-a41d-790c944f030f.png)

It will be great if you can contribute translations.

**Comment by pjkeukens** [comment]
@realLiangshiwei that's why you have translation agencies. It's a bit weird that the commercial version of your product is half translated. Is there a way that I can add the nl.json to my project and add it to the pro resource package in code? Adding all translations using the language texts will take forever.
Volo.Abp.Account.**Pro**.Shared.Application.Contracts\Volo\Abp\Account\Localization\Resources

**Comment by realLiangshiwei** [comment]
Hi

Yes, you can. see: https://docs.abp.io/en/abp/latest/Localization#extending-existing-resource
