### ISSUE TITLE
"Host terminated unexpectedly!" when running 'dotnet ef database update' for module template getting error

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#12532]
**Version:** `5.3.0-rc.1`
**App:** Module Template
**Problem Definition:**  "Host terminated unexpectedly!" when running 'dotnet ef database update' for module template getting error

![image](https://user-images.githubusercontent.com/99716457/167796471-ec0bb4a1-7f9e-457c-a192-d26ff50ac286.png)

**Comment by maliming** [comment]
This is ms issue.

See https://github.com/volosoft/volo/issues/9874

**Comment by weiwxg** [comment]
> This is ms issue.
> 
> See https://github.com/volosoft/volo/issues/9874

The link is broken!
