### ISSUE TITLE
Request localization behaving unexpectedly

### ISSUE THREAD

**Issue by duard-sf** [abpframework/abp#12531]
* Your **ABP Framework version**.
  * 5.2.1
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
  * MVC, but Razor not used at all. We are using JWTs for authentication with the ABP backend from a Flutter app.
* Your database provider(EF Core/MongoDB)
  * EF Core

**Steps needed to **reproduce** the problem**

1 - Download a project template from the abp.io website with the following options:
  * Project type: Application
  * UI Framework: MVC
  * Database provider: Entity Framework Core
  * Database management system: SQL Server
  * Mobile: None
  * Tiered: Yes

2 - Create an endpoint like the following:
```c#
public class LocalizationAppService : ApplicationService
{
    private readonly IStringLocalizer<AbpL10nTestResource> _localizer;
        
    public LocalizationAppService(IStringLocalizer<AbpL10nTestResource> localizer)
    {
        _localizer = localizer;
    }

    public Dictionary<string, string> Get()
    {
        return new Dictionary<string, string>
        {
            { "currentCulture", CultureInfo.CurrentCulture.Name },
            { "currentUICulture", CultureInfo.CurrentUICulture.Name },
            { "language", _localizer["Language"] }
        };
    }
}
```

**Also note:** when using the available `IStringLocalizer L` property exposed by `ApplicationService`, the localized value will never be returned.

3 - Define a localized string in en.json:
```json
{
  "culture": "en",
    "texts": {
      "Language": "English"
    }
}
```

4 - Define a localized string in nl.json:
```json
{
  "culture": "nl",
    "texts": {
      "Language": "Nederlands"
    }
}
```

5 - Run the solution and execute the endpoint at `/api/app/localization` with the Accept-Language header value `nl`
Notice that the current culture remains `en`, example response:
```json
{
  "currentCulture": "en",
  "currentUICulture": "en",
  "language": "English*"
}
```
You can request a different culture with the `culture` query parameter too and you will see the same result.

**Conclusion**

I expect when sending a request with the Accept-Language header or `culture` query string parameter. that the culture will be set appropriately for the request.
Am I misunderstanding how the request localization process works?

**Comment by realLiangshiwei** [comment]
Can you try this?

```csharp
Configure<AbpLocalizationOptions>(options =>
{
    .........
    options.Languages.Add(new LanguageInfo("nl", "nl", "Dutch"));
});
```

**Comment by duard-sf** [comment]
This solved the issue!

I assumed it would have been configured already since the localization JSON is present in the default template.
