### ISSUE TITLE
Document how to check global features in UI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12546]
Related to https://github.com/abpframework/abp/pull/12043

- [x] MVC UI ([like these](https://docs.abp.io/en/abp/5.3/UI/AspNetCore/JavaScript-API/Index)) / @maliming https://github.com/abpframework/abp/pull/12553
- [x] Blazor UI / @enisn  - (https://github.com/abpframework/abp/pull/12773)
- [x] Angular UI / @mahmut-gundogdu 

Notice that if we don't have API for these, we should first develop it.

Please write docs in `rel-5.3` branch. Send to me & @braim23 for review.

**Comment by maliming** [comment]
I will make some changes, @mahmut-gundogdu  please wait for my new PR.

**Comment by maliming** [comment]
@mahmut-gundogdu  https://github.com/abpframework/abp/pull/12553#issuecomment-1128336329

**Comment by enisn** [comment]
There is nothing specific to blazor. Global Features are defined in **Domain.Shared** and they're shipped to blazor wasm & server.

It's same with this section: https://docs.abp.io/en/abp/5.3/Global-Features#check-for-a-global-feature

Should we share a reference to this section?
