### ISSUE TITLE
Document abpLoading directive

### ISSUE THREAD

**Issue by muhammedaltug** [abpframework/abp#12540]
Document how to use this directive

**Comment by mahmut-gundogdu** [comment]
I can do that

**Comment by mahmut-gundogdu** [comment]
I have created but I think we should change loading animation like this"https://codepen.io/fromwireframes/details/Nwjjmz"
Maybe @armgnunlu  can give a better idea.

**Comment by mahmut-gundogdu** [comment]
resolves https://github.com/abpframework/abp/pull/12663
