### ISSUE TITLE
Non primitive ExtraProperties issue

### ISSUE THREAD

**Issue by Ultre00** [abpframework/abp#12547]
* Version: 5.1.4
* Database: EF Core

### Situation:
The Client entity has an int[] as an ExtraProperty. This is registered like this:
```c#
ObjectExtensionManager.Instance.AddOrUpdateProperty<Client, int[]>("Numbers")
```
The same is done for a custom CreateUpdateClientDto. And the automapper has the MapExtraProperties().

This is all working fine when creating a new Client from the front-end. The only problem is that when I inspect the Client.ExtraProperties i see that the key `Numbers` is of type JArray when using NewtonSoft and JsonElement when using System.Text. So when I try and save this to the database the Client is actually created, but the ExtraProperties looks like this: `{"Numbers":[[]]}`.

I also have the following 2 helpers:
```c#
        public static void SetNumbers(this Client client, IEnumerable<int> numbers)
        {
            client.SetProperty("Numbers", numbers);
        }

        public static int[] GetNumbers(this Client client)
        {
            var value = client.GetProperty("Numbers");

            if (value == null)
            {
                return null;
            }

            return value switch
            {
                JsonElement jsonElement => jsonElement.EnumerateArray().Select(m => m.GetInt32()).ToArray(),
                JArray jArray => jArray.Select(m => (int)m).ToArray(),
                _ => (int[])value
            };
        }
```
I got around this by calling `client.SetNumbers(client.GetNumbers())` after mapping but this issue was not there in ABP version 3.3.2.

Is this working as intended?

**Comment by gdlcf88** [comment]
Try

```c#
ObjectExtensionManager.Instance.AddOrUpdateProperty<Client, string>("Numbers");
```

and convert the value in `SetNumbers` and `GetNumbers` methods.

**Comment by Ultre00** [comment]
This didn't work since the API still serializes the array as a JArray type
