### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#12548]
I merged the following PRs but these should be tested.

- [x] https://github.com/volosoft/volo/pull/10194
- [x] https://github.com/volosoft/volo/pull/10178
- [x] https://github.com/volosoft/volo/pull/10197

You can ask what to test to @yekalkan or me

**Comment by gizemmutukurt** [comment]
Voting field gets a negative (-) number. #10239

**Comment by gizemmutukurt** [comment]
Test is Ok.
