### ISSUE TITLE
Testing Ordering Service on Eshop

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#12542]
Ordering service and UI added on EShop project. We should test it.

Related abpframework/abp#11427  and  abpframework/abp#11426

**Comment by gizemmutukurt** [comment]
- Default or public seems too adjacent to the role name.

![image](https://user-images.githubusercontent.com/99716457/169475099-191141bb-0d78-48e6-bd63-b84ee497d10b.png)

- There is no need for scroll in this part

![image](https://user-images.githubusercontent.com/99716457/169475714-68e71199-c6f5-45f4-b35c-a84fa08d27b3.png)

- Action text too close to icon. In general, all icons seem to have this situation.

![image](https://user-images.githubusercontent.com/99716457/169479333-b24847e9-061f-4aa6-857c-904ba0c2a020.png)

- must be updated with the user name

![image](https://user-images.githubusercontent.com/99716457/169480648-7b2d4307-86a6-4322-bd02-395839e13dd7.png)

- In the setting page, a specification has been made above for this field, and it does not seem necessary to display it in this section.

![image](https://user-images.githubusercontent.com/99716457/169488662-80b8bd38-f62f-4dde-b992-40363157a317.png)


- button name looks wrong

![image](https://user-images.githubusercontent.com/99716457/169511396-5eccaadd-0d5e-476e-9aae-e12a2406b61c.png)

- description text should be updated
![image](https://user-images.githubusercontent.com/99716457/169511868-1ba9bf07-93a5-41c0-b751-107fe8f2e281.png)
![image](https://user-images.githubusercontent.com/99716457/169513766-660efb29-8951-4a9c-b9cb-bf474fb0ece0.png)
![image](https://user-images.githubusercontent.com/99716457/169513862-a0ba9a6f-bfda-4ce4-8477-8a3430464245.png)



- dropdown looks clickable but has no action when clicked

![e3ffc16d-33bf-47f3-a8f9-016eeb56164e](https://user-images.githubusercontent.com/99716457/169512321-28025e9f-1dec-4982-bafd-e895af34024b.gif)


- It seems more appropriate to display the same products in the top selling list, not with separate names, but with their total in a single line.

![image](https://user-images.githubusercontent.com/99716457/169742396-cec222b8-8497-468b-9990-19e8da29a06e.png)

- It would be nice to display how many products were purchased in a single order.

![image](https://user-images.githubusercontent.com/99716457/169746027-29f49f7b-3ddc-4285-b947-26ed6fe21c93.png)

- It would be nice to write separately the purchased prices next to the products in the order list.

![image](https://user-images.githubusercontent.com/99716457/169748737-617f6ac7-a813-481d-880a-d5de2de3fd99.png)

**Comment by gizemmutukurt** [comment]
**Bugs:**

- Order payment is made and there is no change in the number of products. abpframework/eShopOnAbp#162
- On the user page, the Admin user does not have the authority to update the passwords of other users. This feature should be done in this template as in our other templates. abpframework/abp#12680
- Findings about the Eshop abpframework/eShopOnAbp#165
