### ISSUE TITLE
ValueEquals doesn't work when returning ValueObject's in GetAtomicValues

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#12541]
When a ValueObject contains another child ValueObject, returning the child ValueObject in GetAtomicValues causes ValueEquals to fail.

Assume the following classes:
```cs
public class GeoCoordinates : ValueObject
{
    public float Latitude { get;  }

    public float Longitude { get; }

    public GeoCoordinates(float longitude, float latitude)
    {
        Latitude = latitude;
        Longitude = longitude;
    }

    protected override IEnumerable<object> GetAtomicValues()
    {
        yield return Latitude;
        yield return Longitude;
    }
}
```

```cs
public class AddressDetails : ValueObject
{
    public GeoCoordinates Coordinates { get;  }

    public string Address { get; }

    public AddressDetails(string address, GeoCoordinates coordinates)
    {
        Address = address;
        Coordinates = coordinates;
    }

    protected override IEnumerable<object> GetAtomicValues()
    {
        yield return Address;
        yield return Coordinates;
    }
}
```

In this case AddressDetails.ValueEquals will return false for two equal addresses:
```cs
var address1 = new AddressDetails("test", new GeoCoordinates(10f, 20f));
var address2 = new AddressDetails("test", new GeoCoordinates(10f, 20f));

return address1.ValueEquals(address2); // false
```
A workaround is to explicitly return child ValueObject properties:
```cs
    protected override IEnumerable<object> GetAtomicValues()
    {
        yield return Address;
        yield return Coordinates?.Longitude;
        yield return Coordinates?.Latitude;
    }
```

**Comment by maliming** [comment]
hi
These two objects are not equal. unless `yield return Coordinates?.Longitude; yield return Coordinates?.Latitude;`. This is by design.


![image](https://user-images.githubusercontent.com/6908465/168013031-fbf3e540-0ee5-4d05-8a83-1b290b791568.png)

**Comment by Trojaner** [comment]
The objects are not equal by reference, but same by value. There shouldn't be a difference between two GeoCoordinates with the same values as its a ValueObject.

**Comment by maliming** [comment]
> but same by value.

That means you need to return the same values manually. 


![image](https://user-images.githubusercontent.com/6908465/168015204-c411ab7c-7f21-4da0-abbd-07049eddd058.png)

**Comment by Trojaner** [comment]
I think this is against the DDD principle of ValueObjects where they only represent a value. It shouldn't do reference comparison.

From Eric Evan:
> When a child is drawing, he cares about the color of the marker he chooses, and he may care about the sharpness of the tip. But if there are two markers of the same color and shape, he probably won’t care which one he uses. If a marker is lost and replaced by another of the same color from a new pack, he can resume his work unconcerned about the switch.

**Comment by maliming** [comment]
I think you can also call the `GetAtomicValues` method of the child object. Anyway, this can't be implemented by our code, the developer has to do something manually.
