### ISSUE TITLE
Blazor Server: override configuration to only use Websockets and SkipNegotiation

### ISSUE THREAD

**Issue by ArneCools** [abpframework/abp#12549]
* Version 4.3.3
* Blazor Server
* Exception message and **stack trace** if available (check the logs).

I'm trying to override the Blazor Server configuration to only use Websockets and enable SkipNegotiation to avoid using Sticky Sessions.

I tried using Configure, to set the options, but this gave me an error regarding duplicate endoints:
```
Configure<AbpEndpointRouterOptions>(options =>
            {
                options.EndpointConfigureActions.Add(endpointContext =>
                {
                    endpointContext.Endpoints.MapBlazorHub(options => options.Transports = HttpTransportType.WebSockets);
                    endpointContext.Endpoints.MapFallbackToPage("/_Host");
                });
            }); 
```
`System.InvalidOperationException: Using ExpandEndpoint requires that the replaced endpoint have a unique priority. The following endpoints were found with the same priority.`
I "fixed" is using a dirty workaround:
`options.EndpointConfigureActions.RemoveAt(2);`

How do I properly override those options?

Then
In _Host.cshtml I tried starting Blazor with extra configuration:
```
Blazor.start({
        configureSignalR: function (builder) {
            builder.withUrl("/_blazor", {
                skipNegotiation: true,
                transport: 1
            });
        }
    });
```
`blazor.server.js Error: Blazor has already started`
I searched the source code for "Blazor.Start" and "ConfigureSignalR", but can't find the location where the Blazor service is started

**Comment by realLiangshiwei** [comment]
> How do I properly override those options?

There is no good way.

> In _Host.cshtml I tried starting Blazor with extra configuration:

```csharp
public class MyBundleScriptContributor : BundleContributor
{
    public override void ConfigureBundle(BundleConfigurationContext context)
    {
        context.Files.RemoveAll(x => x == "/_framework/blazor.server.js");
    }
}

Configure<AbpBundlingOptions>(options =>
{
    options
        .ScriptBundles
        .Add(BlazorStandardBundles.Scripts.Global, bundle =>
        {
            bundle.AddContributors(typeof(MyBundleScriptContributor));
        });
});
```

_Host.cshtml
```cshtml
......
<script src="_framework/blazor.server.js" autostart="false"></script>
<script>
   Blazor.start({
        configureSignalR: function (builder) {
            builder.withUrl("/_blazor", {
                skipNegotiation: true,
                transport: 1
            });
        }
    });
</script>
<abp-style-bundle name="@BlazorLeptonThemeBundles.Styles.Global" />
```
