### ISSUE TITLE
abp docker wwwroot/libs How to Config Dockerfile?

### ISSUE THREAD

**Issue by YoChen** [abpframework/abp#12589]
Now I found no wwwroot/libs in AuthServer for eShopOnAbp When I Published the apps/auth-server proj

dev, I can use `abp install-libs`

but when publish docker ,how to config the Dockerfile? please help.

**Comment by maliming** [comment]
The `wwwroot/libs` will exist in the `publish` folder.


https://github.com/abpframework/eShopOnAbp/blob/main/apps/auth-server/src/EShopOnAbp.AuthServer/Dockerfile

**Comment by YoChen** [comment]
thanks, I 'll rry it again.

**Comment by Jesn** [comment]
The 'wwwroot/libs' configuration is excluded from git. If Docker Build is executed on the CICD server, the generated docker image relevant npm dependency packages，

We rarely find similar problems online, have we never encountered similar situations? Here is a solution provided

https://blog.antosubash.com/posts/abp-docker-file

**Comment by dongfo** [comment]
> The 'wwwroot/libs' configuration is excluded from git. If Docker Build is executed on the CICD server, the generated docker image relevant npm dependency packages，
> 
> We rarely find similar problems online, have we never encountered similar situations? Here is a solution provided
> 
> https://blog.antosubash.com/posts/abp-docker-file

thx，it's the right way。abp need "RUN abp install-libs" .
by the way  RUN apt update && apt -y install gnupg is too slowly
