### ISSUE TITLE
ABP Framework do not serialize the datetime based on AbpClockOptions in nested document Mongodb

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#12584]
Hi,

I'm using Abp framework version 5.1.2 and now I've got a problem with a datetime in Mongodb. As I know, abp has released the feature that will serialize datetime based on AbpClockOptions from version 5.x.

Whenever I upsert data to Mongodb, the Datetime field is serialized but the datetime field in nested document will not be serialized . I hope this problem will be fixed soon in version 5.3

thanks

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by volethanh** [comment]
> hi
> 
> * Steps needed to **reproduce** the problem.

Hi @maliming ,

Just create an entity with a List of another entity then just call repository.InsertAsync to insert it to database.
