### ISSUE TITLE
React UI updates / news for 2022?

### ISSUE THREAD

**Issue by mrcarl79** [abpframework/abp#12596]
Hi,

In issue #1638 over 2 years ago this was the latest news "It is on our road map, but haven't started yet. BlazorUI has more priority to be honest, but fortunately we have a dedicated frontend team can work on the React in parallel."

I did try and ask more info in there 3 months ago but I don't think anyone is watching that issue.

I was just wondering, is there an update? has the front end team started?

Thanks

**Comment by DonVliet** [comment]
There already is a React UI - Just select "React Native" as the mobile option on the Getting Started page here:

https://abp.io/get-started

Documentation is also here:

https://docs.abp.io/en/abp/latest/Getting-Started-React-Native?Tiered=No

Don

**Comment by EngincanV** [comment]
Hi, currently we don't have a plan for supporting React. There is an open issue ([#1638](https://github.com/abpframework/abp/issues/1638)) as you mentioned and it's in the **backlog**.

---

You can check the following resources for React UI with ABP Framework:
* https://github.com/potatoabp/abp-vnext-react (An open-source React boilerplate)
* https://github.com/antosubash/AbpReact

---

Also, you can create a template with **mobile** support (React Native project) and use a similar approach for your React application.

**Comment by mrcarl79** [comment]
> Hi, currently we don't have a plan for supporting React. There is an open issue ([#1638](https://github.com/abpframework/abp/issues/1638)) as you mentioned and it's in the **backlog**.
> 
> You can check the following resources for React UI with ABP Framework:
> 
> * https://github.com/potatoabp/abp-vnext-react (An open-source React boilerplate)
> * https://github.com/antosubash/AbpReact
> 
> Also, you can create a template with **mobile** support (React Native project) and use a similar approach for your React application.

Thanks, just needed an update as the other open issue was not being monitored. This reply should help anyone more recently trying. I do think it's odd you Abp supports things like MVC which has jQuery in it last time I looked and blazor which will probably gain little traction.
