### ISSUE TITLE
Identity Entity Extension property UI and API visibility ignored

### ISSUE THREAD

**Issue by fileman** [abpframework/abp#12593]
This follow the #10480 .
If I remove the extended property from Dto, it is hidden in the OnCreate/OnEditForm, but the value is not updated in the database.

I have attached two demo:
[Property always show but update DB value](https://github.com/abpframework/abp/files/8695252/IdentityUIExtend_demo.zip)
[Property hidden but update DB issue](https://github.com/abpframework/abp/files/8695271/IdentityUIExtend_demo_db_issue.zip)

**Comment by fileman** [comment]
I'm waiting a reply from staff

**Comment by maliming** [comment]
> but the value is not updated in the database.

hi

Can you share some code or screenshots?

**Comment by fileman** [comment]
I have attached 2 demo proj with and without issue

**Comment by fileman** [comment]
I'm waiting a reply from the team

**Comment by fileman** [comment]
I'm waiting a reply from the team

**Comment by maliming** [comment]
hi

Can you try the latest project template?
