### ISSUE TITLE
How to get All the Data if the entity is multiTenant?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#12600]
I have a entity with multiTenant  like this:
` public class AllFight : Entity<Guid>, IMultiTenant

right now,when I use AllFightService
`   public virtual async Task<PagedResultDto<AllFightDto>> GetListAsync(GetAllFightsInput input)
        {
            var totalCount = await _allFightRepository.GetCountAsync( input.StaticMonthMin, input.StaticMonthMax);
            var items = await _allFightRepository.GetListAsync( input.StaticMonthMin, input.StaticMonthMax, input.Sorting, input.MaxResultCount, input.SkipCount);

            return new PagedResultDto<AllFightDto>
            {
                TotalCount = totalCount,
                Items = ObjectMapper.Map<List<AllFight>, List<AllFightDto>>(items)
            };
        }`
if I login with a tenant,I only get the CurrentTenant AllFights, that's all right. But if in login with host, I want get all the tentant's AllFights in AllFightService? what can I do? thanks

**Comment by rqx110** [comment]
see https://docs.abp.io/en/abp/latest/Multi-Tenancy#data-filtering-disable-the-multi-tenancy-filter

**Comment by realLiangshiwei** [comment]
Also see: https://docs.abp.io/en/abp/latest/Multi-Tenancy#change-the-current-tenant
