### ISSUE TITLE
AbpJsonOptions DefaultDateTimeFormat not applied

### ISSUE THREAD

**Issue by Ultre00** [abpframework/abp#12604]
* Version 5.2.1

Created a a new ABP project with the cli. In the HttpApiHost Module I added this:
```c#
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<AbpJsonOptions>(options =>
    {
        options.UseHybridSerializer = false;
        options.DefaultDateTimeFormat = "yyyy/MM/dd HH:mm:ss";
    });
}
```
Added a simple application service:
```c#
public class DemoDto
{
    public DateTime DateTest { get; set; }
}

public class DemoAppService : BookStoreAppService
{        
        
    public DemoDto GetDemo()
    {
        return new DemoDto()
        {
            DateTest = DateTime.UtcNow
        };
    } 
}
```
When testing the endpoint the result was:
```
{
  "dateTest": "2022-05-16T08:27:48.6620871Z"
}
```
How can I get the datetime to serialize as the provided AbpJsonOptions.DefaultDateTimeFormat  ?

The actual issue I am facing in my original project is that the 'Z' is missing in the end. So when a datetime is serialized it shows as 2022-05-12T22:22:08.8273489 instead of 2022-05-12T22:22:08.8273489Z

**Comment by maliming** [comment]
> The actual issue I am facing in my original project is that the 'Z' is missing in the end. So when a datetime is serialized it shows as 2022-05-12T22:22:08.8273489 instead of 2022-05-12T22:22:08.8273489Z

This is a typical XY problem, please describe your original problem in detail.

https://xyproblem.info/

**Comment by Ultre00** [comment]
@maliming The original problem is that an entity has a DateTime property. I am using Entity Framework as the database provider. When the entity is retrieved from the database the DateTime kind is set to unspecified. Because of this the serializer is not adding the 'Z' in the end because it doesn't know it is a UTC kind. That's why I wanted to specify the format myself since all the datetimes are always UTC.

I am also configuring the clock:
```c#
Configure<AbpClockOptions>(options => options.Kind = DateTimeKind.Utc); 
```

**Comment by maliming** [comment]
Our framework has unit tests ensure that the problem you mentioned do not happen.

Can you reproduce it with unit tests or a template project?

**Comment by Ultre00** [comment]
After a lot of debugging I found the issue. It was because I am using a custom serializer that I forgot about. This serializer is set as an attribute on the Dto and it is only used in inheritance so the discriminator property is automatically serialized. However because this is a custom serializer the other serializers are not being applied anymore 🤦‍♂️
