### ISSUE TITLE
Abp.js throws exception on abp.ui.clearBusy calls (block/unclock) on modal

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#12635]
* Your **ABP Framework version** >  5.2
* Your **User Interface** type > MVC
* Your database provider > EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

I am doing something like this in the js file:

```
abp.ui.setBusy("#CommentForm");
abp.ajax({
    url: "/api/app/xyz/getXyz/" + id + "?type=" + type,
    method: "GET",
  }).done(function (items) {
    // do something with items
    abp.ui.clearBusy();
  })
  .fail(function (e) {
    abp.ui.clearBusy();
    console.error(e);
  });
```

When code hits clearBusy lines I see error on developer tools console:

```
abp.js?_v=637866657422553712:375 Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at abp.js?_v=637866657422553712:375:43
(anonymous) @ abp.js?_v=637866657422553712:375
setTimeout (async)
abp.ui.unblock @ abp.js?_v=637866657422553712:372
abp.ui.clearBusy @ abp.js?_v=637866657422553712:400
```

It is showing this line in abp.js:

   ```
 abp.ui.unblock = function (opts) {
        var element = document.querySelector('.abp-block-area');
        if (element) {
            element.classList.add('abp-block-area-disappearing');
            setTimeout(function () {
                if (element) {
                    element.classList.remove('abp-block-area-disappearing');
             >>>>   element.parentElement.removeChild(element);
                }
            }, 250);
        }
    };
```

**One important detail:** This is happening on a modal.

**Comment by berkansasmaz** [comment]
Sorry, I couldn't reproduce it despite all the details you provided.

Here is my test code:

```js
        abp.ui.setBusy('.modal-content');

        setTimeout(function () {
            abp.ui.clearBusy()
        }, 2000)
```

Is there something I missed? Can you please help me to reproduce the problem?

**Comment by espindl** [comment]
I found my problem. It was happening because this ajax call is in a function and that function is called twice one after the other. I guess the code in abp.js is failing because clearBusy is called twice very fast. I don't think it is a problem with the framework. But it might be considered an edge case.
