### ISSUE TITLE
How to reference external NgModule components in the replaced component?

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#12648]
**ABP 5.1.2 / Angular**

I've replaced the **ABP** _Tenant_ component:

```
      this.replaceableComponents.add({
        component: TenantsComponent,
        key: eSaasComponents.Tenants,
      }),

```
Since this component does not have its own module (it reuses `TenantManagementModule`) - I cannot make use of `declarations` property of _NgModule_ to add some additional components which I am gonna use in my `TenantsComponent`.
How to resolve this?

NOTE: those additional components are from another project which are exported via its _NgModule_.

I've tried to import this external _NgModule_ in `app.module.ts`, but then I get page loop reload. And besides I'm not sure it's correct - I need this module only for specific pages including Tenant page.

**Comment by mahmut-gundogdu** [comment]
You should add your `TenantsComponent`  and its own dependencies to `app.module.ts` then it will work with any issue. Here I have created an example. You can check the `app.module.ts`

https://github.com/mahmut-gundogdu/abp-io-replacable-component-with-3party-deps.

**Comment by alexandis** [comment]
Isn't it a problem, if I use `replaceableComponentsService` in App.component, not Home.component?
Unfortunately, now our requirements have changed and I cannot check your solution right away.
