### ISSUE TITLE
Blazor Server Account Module Error

### ISSUE THREAD

**Issue by BogdanJak** [abpframework/abp#12643]
ABP Framework 5.3.0
User Interface type Blazor server
Database provider EF Core, MS SqlServer
Windows 11

Hi 
I create new ABP application with command

abp new OrganizerPRO3 -t app -u blazor-server --mobile none

Next open application in Visual Studio 2022, run migration and add module Account with command

 abp add-module Volo.Account --with-source-code True --add-to-solution-file

When I launch the application, I am getting the following error 

`Autofac.Core.DependencyResolutionException: „An exception was thrown while activating Volo.Abp.IdentityServer.Grants.PersistedGrantStore -> Volo.Abp.ObjectMapping.DefaultObjectMapper`1[[Volo.Abp.IdentityServer.AbpIdentityServerDomainModule, Volo.Abp.IdentityServer.Domain, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider`1[[Volo.Abp.IdentityServer.AbpIdentityServerDomainModule, Volo.Abp.IdentityServer.Domain, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null]] -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor.”`

When I launch the application, I am getting the following error

What is the cause of such an error?
In version 5.2.2, with the same queue of activities - the same error occurs

Bogdan

**Comment by maliming** [comment]
Without `abp add-module Volo.Account --with-source-code True --add-to-solution-file` works?

**Comment by BogdanJak** [comment]
It doesn't work properly. Entries are added to the runtime
[DependsOn (typeof (AbpAccountWebModule))]
     [DependsOn (typeof (AbpAccountBlazorModule))]

Today I ran the entire procedure all over again and the same error again.
Enclosed my sample code.
Thank you in advance for any help
[OrganizerPRO3.zip](https://github.com/abpframework/abp/files/8713966/OrganizerPRO3.zip)
.

**Comment by BogdanJak** [comment]
The generated application, without adding the Account module, works correctly.
The problem starts after adding the module.

**Comment by maliming** [comment]
Add `ConcurrencyStamp` property to `PersonalInfoModel` class.

`modules\Volo.Account\src\Volo.Abp.Account.Blazor\Pages\Account\AccountManage.razor.cs`

![image](https://user-images.githubusercontent.com/6908465/168982402-5f6f7885-1a43-4c95-bd82-18be821b0d50.png)
