### ISSUE TITLE
Rebus: Triggers events twice (handler is invoked twice)

### ISSUE THREAD

**Issue by brunobertechini** [abpframework/abp#12659]
* Your **ABP Framework version**.: 5.2.2
```
<PackageReference Include="Volo.Abp.EventBus.Rebus" Version="5.2.2" />
<PackageReference Include="Rebus.RabbitMq" Version="7.3.5" />
```

Hello there, I just created a new solution (5.2.2) and added the configuration for Rebus.RabbitMq to test the integration. 

I believe I am facing the same problem of https://github.com/abpframework/abp/issues/11431 (although not sure it is because of the same reason) of my handler being called twice when using Rebus+RabbitMq.

I have no special configuration. A simple event and a simple handler:

```
PreConfigure<AbpRebusEventBusOptions>(options =>
        {
            var queueName = "eventbus";
            options.InputQueueName = queueName;
            options.Configurer = rebusConfigurer =>
            {
                rebusConfigurer.Transport(t => t.UseRabbitMq("amqp://localhost", queueName));
                // rebusConfigurer.Subscriptions(s => s.UseJsonFile(@"subscriptions.json"));
            };
        });
```

```
public class SampleEvent1 : IEvent
{
    [Required]
    public string MyStringProp { get; set; }
    
    [Required]
    public int? MyIntProp { get; set; }
    
    [Required]
    public bool? MyBoolProp { get; set; }
    
    [Required]
    public DateTime? MyDateTimeProp { get; set; }
}
```

```
public class SampleEvent1Handler : IDistributedEventHandler<SampleEvent1>, ITransientDependency
{
    private readonly ILogger<SampleEvent1Handler> _logger;

    public SampleEvent1Handler(ILogger<SampleEvent1Handler> logger)
    {
        _logger = logger;
    }    
    
    public Task HandleEventAsync(SampleEvent1 eventData)
    {
        _logger.LogInformation($"Received Event {eventData.GetType().FullName}");
        
        Thread.Sleep(10000);
        
        _logger.LogInformation($"Finished processing Event {eventData.GetType().FullName}");
        
        return Task.CompletedTask;
    }
}
```

**Comment by brunobertechini** [comment]
I have tested the same handler with `Volo.Abp.RabbitMQ` (`AbpEventBusRabbitMqModule`) only, and it works perfectly fine (handler is invoked only once).

**Comment by realLiangshiwei** [comment]
Hi, @brunobertechini 

I could not reproduce the problem, can you provide a project?

![gif](https://user-images.githubusercontent.com/16813853/169264288-6d64fffb-2d9d-458d-a93d-5251ceebc036.gif)

**Comment by brunobertechini** [comment]
Have you used the SampleEvent1 implementing an empty interface (in my example I am implementing `IEvent`)?

I have created a project to reproduce, and while doing that, I think I've found the reason why it is being called twice, not sure if it is by design or not:

If my event implements the IEvent interface it gets called twice (I believe once for the interface and another for the implementation). I believe it should be called just once, as my handler is not configured to handle `IEvent` specifically.

Project: https://github.com/brunobertechini/abprebussample-12659

Steps:
1. Clone the project
2. Run docker compose (docker compose up -d)
3. Update databases `dotnet ef database update` under EF Core project
4. Run the application
5. Call app service "SampleAppService.PublishEvent"

**Comment by realLiangshiwei** [comment]
@brunobertechini 

I've reproduced the problem and will fix it.

For now, you can try:

```csharp
public class MyAbpRebusEventHandlerStep: IIncomingStep
{
    public Task Process(IncomingStepContext context, Func<Task> next)
    {
        var message = context.Load<Message>();
        var handlerInvokers = context.Load<HandlerInvokers>().ToList();

        handlerInvokers = new List<HandlerInvoker> {handlerInvokers.Last()};
        context.Save(new HandlerInvokers(message, handlerInvokers));

        return next();
    }
}

options.Configurer = configure =>
{
    //.....
    configure.Options(o =>
    {
        o.Decorate<IPipeline>(d =>
        {
            var step = new MyAbpRebusEventHandlerStep();
            var pipeline = d.Get<IPipeline>();

            return new PipelineStepInjector(pipeline).OnReceive(step, PipelineRelativePosition.After,
                typeof(ActivateHandlersStep));
        });
    });
   };
});
```
