### ISSUE TITLE
Allow to use LeptonX lite as the UI theme

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12650]
With the ABP 5.4, we are planning to allow us to select the UI theme while creating a new application.

- [x] Should work for Application and Application (Single-Layer) startup templates with all UI options (MVC, Angular, Blazor WASM and Blazor Server)
- [x] Add `--theme` parameter to ABP CLI. Default value will be `leptonx-lite`. Possible values: `leptonx-lite` and `basic`.
- [x] Add a "Select UI Theme" section to the https://abp.io/get-started page to allow to choose one of the theme options (LeptonX-Lite (selected by default and in the first order) and Basic). Show screenshots of the themes side by side and allow to select by clicking the image. Write explanations under the themes, for leptonx-lite: "A modern and stylish Bootstrap UI theme. Ideal if you want to have a production ready UI theme.", for basic theme "Minimalist UI theme with plain Bootstrap colors and styles. Ideal if you will build your own UI theme."

**Comment by EngincanV** [comment]
> - [x] Should work for Application and Application (Single-Layer) startup templates with all UI options (MVC, Angular, Blazor WASM and Blazor Server)

- [x] app
   - [x] mvc
   - [x] blazor wasm
   - [x] blazor-server
   - [x] angular 
- [x] app-nolayers
   - [x] mvc
   - [x] blazor-server 
   - [x] angular
