### ISSUE TITLE
Add "Project" filter to Docs module admin UI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12661]
Add "Project" filter (optional) as the first filter item:

![image](https://user-images.githubusercontent.com/1210527/169268590-13284989-8e04-4a47-b59e-0f11b9b83a37.png)

Also;

- File name filter is unnecessary since Name does a similar thing with full path support. Remove this filter.
- Move these filters under to "Advanced filters" just like we do for other pages: Format, creation time, Last update, Last significant update, Cache time.
- Version, Format and language code textboxes can be smaller (they are too long, but the data is mostly very short, like `en` for language).

**Comment by malikmasis** [comment]
![image](https://user-images.githubusercontent.com/13196534/182887790-84d578f7-2bc8-4b7e-a99b-76866da8abf0.png)
