### ISSUE TITLE
Couldn't determinate version of "@abp/ng.schematics" package.

### ISSUE THREAD

**Issue by mustafaekicics** [abpframework/abp#12664]
* My UI : Angular
* My database provider : Ef Core
*Exception Message : 
[21:01:45 INF] ABP CLI (https://abp.io)
[21:01:45 INF] Version 5.2.2 (Stable)
[21:01:47 WRN] Couldn't determinate version of "@abp/ng.schematics" package.
[API Not Available] Request to ''/api/abp/api-definition is unsuccessful. Please double-check the URL in the source project environment and make sure your application is up and running.

Looked at some solutions but couldn't figure out how to solve it.

Steps to reproduce the error: Before I post here I have downloaded both tiered and non-tiered angular apps and added the Books entity. Through swagger, I can add data to the database but fail at generating a proxy. 
As I see one of the solutions from past issues I have uninstalled node.js and reinstalled it again this also didn't work. Also searched for submitted issues before but couldn't be figured it out yet. 

I tried from CLI those below but no luck.
abp generate-proxy -t ng
abp generate-proxy -t ng -url https://localhost:44***/
abp generate-proxy -t ng -m application
abp generate-proxy -t ng -m app

I am trying to learn the framework and any suggestions or solutions to solve this issue will improve my motivation on this path. Thanks in advance.

**Comment by captainkout** [comment]
I am also experiencing this problem. I was experiencing an error previously that stated 
`Unknown option: ''`

I ran the cli from source which gave me this command.

`$ npx ng g @abp/ng.schematics:proxy-add --module app --api-name __default --source __default --target __default --url https://localhost:44393/
[API Not Available] Request to https://localhost:44393//api/abp/api-definition is unsuccessful. Please double-check the URL in the source project environment and make sure your application is up and running.`

**Comment by captainkout** [comment]
There was a support post here. https://support.abp.io/QA/Questions/3092/Error-when-trying-to-use-abp-generateproxy--t-ng--m-identity

And associated github issue https://github.com/abpframework/abp/issues/12618

The forum post states that the message `[21:01:47 WRN] Couldn't determinate version of "@abp/ng.schematics" package.` is not an issue. I know from other apps which are running successfully on version 4.x that this message does not appear to effect the generation of ts.

**Comment by mustafaekicics** [comment]
abp generate-proxy -t ng -m app -u https://localhost:44***

This worked for me. Thanks for helping.
