### ISSUE TITLE
On the user page, the Admin user does not have the authority to update the passwords of other users. This feature should be done in this template as in our other templates.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#12680]
On the user page, the Admin user does not have the authority to update the passwords of other users. This feature should be done in this template as in our other templates.

![image](https://user-images.githubusercontent.com/99716457/169520707-8a917916-fb8a-44b8-9eac-c87d2001c986.png)
![image](https://user-images.githubusercontent.com/99716457/169520752-f6525433-816c-475e-bda0-b10091536644.png)

**Comment by mahmut-gundogdu** [comment]
I think that closed by developer hand for a good reason. I asked the why. I will updated.

**Comment by sturlath** [comment]
Will this enable host to reset passwords (emails) for tenants also (in Blazor)? If a email account gets comprimised and the tenant cant get to his email he is just locked out.

**Comment by mahmut-gundogdu** [comment]
> Will this enable host to reset passwords (emails) for tenants also (in Blazor)? If a email account gets comprimised and the tenant cant get to his email he is just locked out.


We created a functionality that allows the administrator to change the tenant's password without sending an email or other communication. However, that function on the ABP app. this issue is related to the EShopOnABP sample app. that app does not need reset feature.

**Comment by sturlath** [comment]
> We created a functionality that allows the administrator to change the tenant's password without sending an email or other communication

That functionlity isnt eneough for me since my setup is that the host controls a lot of functionality and the if a tennant is created and needs help they are just locked in. Hopefully you can add the password reset for tenants to the host.

But yes sorry this is abput the Eshop example.

**Comment by mahmut-gundogdu** [comment]
> > We created a functionality that allows the administrator to change the tenant's password without sending an email or other communication
> 
> That functionlity isnt eneough for me since my setup is that the host controls a lot of functionality and the if a tennant is created and needs help they are just locked in. Hopefully you can add the password reset for tenants to the host.
> 
> But yes sorry this is abput the Eshop example.


We have added a reset tenant password feature. The feature has been released in v7.0.0-RC6 . You can test with new v7.0.0-RC6 app or update your app to v7.0.0-RC6.  But that ui package avaible on ABP commercial. I've asked my teammate about that is available on abp. I'll let you know..


<img width="1295" alt="image" src="https://user-images.githubusercontent.com/2217899/209927352-ef4de235-91ee-4adf-9230-7cf2ad66a141.png">

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/2217899/209927397-38e26f54-3007-496f-ad13-4f55136054e5.png">

**Comment by sturlath** [comment]
Thats awesome! Can’t wait to update!

**Comment by mahmut-gundogdu** [comment]
I have tested now, we have change password. feature
@gizemmutukurt 

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/2217899/210548520-720cb162-d780-4779-9517-7ed919d53261.png">
