### ISSUE TITLE
Swagger UI Request Interceptor Not Adapted But Overridden 

### ISSUE THREAD

**Issue by ikappas** [abpframework/abp#12685]
### Description

In `Volo.Abp.Swashbuckle` package the `UseAbpSwaggerUI` extension method command in [AbpSwaggerUIBuilderExtensions](https://github.com/abpframework/abp/blob/99a6d5bf65c21776e0c91592558d7b09faebd159/framework/src/Volo.Abp.Swashbuckle/Microsoft/AspNetCore/Builder/AbpSwaggerUIBuilderExtensions.cs) injects the [ui/abp.swagger.js](https://github.com/abpframework/abp/blob/99a6d5bf65c21776e0c91592558d7b09faebd159/framework/src/Volo.Abp.Swashbuckle/wwwroot/swagger/ui/abp.swagger.js) in which any configured `SwaggerUI.Interceptors.RequestInterceptorFunction` set from C# configuration is overridden and discarded.

### How to Reproduce
```csharp
app.UseAbpSwaggerUI(options =>
{
   // Third party OAuth2 Server rejects requests with RequestVerificationToken with CORS preflight error
    var authority = configuration["AuthServer:Authority"]; 
    options.Interceptors.RequestInterceptorFunction = @"function(request){if(request.url.indexOf('" + authority + "') == 00){delete request.headers[abp.security.antiForgery.tokenHeaderName];}}";
});
```
### Expected Behavior

Any configured JavaScript function in `configObject.requestInterceptor`  should probably be adapted and executed after injected code.

### Info

* ABP Framework 5.2.2
* MVC/React... etc.) if the issue is related to a specific UI
* EF Core

**Comment by realLiangshiwei** [comment]
Hi,

We will fix it. for now, you can try:

Put `abp.swagger.js` file in the `wwwroot/swagger/ui` folder

```js
var abp = abp || {};

(function () {

    abp.SwaggerUIBundle = function (configObject) {

        var excludeUrl = ["swagger.json", "connect/token"]
        var firstRequest = true;
        abp.appPath = configObject.baseUrl || abp.appPath;

        var requestInterceptor = configObject.requestInterceptor;
        
        configObject.requestInterceptor = async function (request) {

            if(request.url.includes(excludeUrl[1])){
                firstRequest = true;
            }

            if(firstRequest && !excludeUrl.some(url => request.url.includes(url)))
            {
                await fetch(`${abp.appPath}abp/Swashbuckle/SetCsrfCookie`,{
                    headers: request.headers
                });
                firstRequest = false;
            }

            var antiForgeryToken = abp.security.antiForgery.getToken();
            if (antiForgeryToken) {
                request.headers[abp.security.antiForgery.tokenHeaderName] = antiForgeryToken;
            }
            
            if(requestInterceptor){
                requestInterceptor(request);
            }
            return request;
        };

        return SwaggerUIBundle(configObject);
    }
})();

```

**Comment by ikappas** [comment]
@realLiangshiwei Thank you for the swift resolution
