### ISSUE TITLE
Make web projects InProcess for AspNetCoreHostingModel

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1269]
For all templates & samples;

- [ ] Add `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` to .csproj files.
- [ ] Add `.UseIIS()` to `Program.cs` files.

Like I done for the BookStore: https://github.com/abpframework/abp/commit/64352b6df35986e95713855ef7b0bdb5bbdf6d75

In addition;

- [ ] Update this document: https://github.com/abpframework/abp/blob/master/docs/en/Getting-Started-AspNetCore-Application.md#using-autofac-as-the-dependency-injection-framework (for .UseIIS()).

**Comment by maliming** [comment]
https://github.com/aspnetzero/aspnet-zero-core/issues/2019#issuecomment-501112700

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/1132
