### ISSUE TITLE
/api/abp/application-configuration  why api return not  grantedPolicies value

### ISSUE THREAD

**Issue by zengnanhua** [abpframework/abp#12700]
![image](https://user-images.githubusercontent.com/22017107/169739009-dc347464-c1bb-4769-9793-de8a21645bec.png)

**Comment by maliming** [comment]
Please explain it in detail including the steps needed to **reproduce** the problem.

**Comment by litiansky** [comment]
I also encountered this problem after using 6.0, how do you solve it?

**Comment by wnumwwfpps** [comment]
In our case, when the user is still in the operating system, the menu function will be lost at an indeterminate time. The reason is that the grantPolicies is empty, but the login cookie is still there.

**Comment by luy710** [comment]
I also encountered this problem after using 5.0, how do you solve it?
