### ISSUE TITLE
How to disable filtering only for associated data？

### ISSUE THREAD

**Issue by luy710** [abpframework/abp#12704]
How to disable filtering only for associated data

GroupJoin or Include

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)

For EF Core https://github.com/dotnet/efcore/issues/11853

**Comment by luy710** [comment]
> * Your **ABP Framework version**.
> * Your database provider(EF Core/MongoDB)
> 
> For EF Core [dotnet/efcore#11853](https://github.com/dotnet/efcore/issues/11853)

ABP Framework version：5.1.4
EF Core

The entity inherits the interface isoftdelete,

Turn off filtering through using (datafilter. Disable < isoftdelete > ()

Does this work only when the data is finally read?



How can I make some entities I query effective and soft delete, while some do not

**Comment by maliming** [comment]
Query the final result in the using statement.

**Comment by luy710** [comment]
> Query the final result in the using statement.


           var queryable =  (await GetQueryableAsync()).Where(p=>p.Name != null);
           IQueryable<Test> queryableWithIncludeOther;
            using (DataFilter.Disable<ISoftDelete>())
            {
                queryableWithIncludeOther = queryable.Include(p => p.TestOthers).Where(p=>p.Price!=0);
            }
            var  list = await queryableWithIncludeOther.ToListAsync();

            IQueryable<TestU> queryableWithGroupJoinOther;
            using (DataFilter.Disable<ISoftDelete>())
            {
                queryableWithGroupJoinOther = queryable.GroupJoin((await GetDbContextAsync()).TestOthers, 
                    m => m.Id, n => n.TestId, (m, n) => new TestU
                {
                    Test = m,
                    TestOther = n
                });
            }
            var withIncludeOtherList = await queryableWithIncludeOther.ToListAsync();
            var withGroupJoinOtherList = await queryableWithGroupJoinOther.ToListAsync();

I want Test to be filtered and TestOther not

But it's all filtered

**Comment by maliming** [comment]
> Query the final result 

```cs
using (DataFilter.Disable<ISoftDelete>())
{
    queryableWithIncludeOther = queryable.Include(p => p.TestOthers).Where(p=>p.Price!=0);
    var  list = await queryableWithIncludeOther.ToListAsync();
}
```

**Comment by luy710** [comment]
> Test

In this way, Test will also be disabled filtering

**Comment by maliming** [comment]
This is the current design.

**Comment by luy710** [comment]
> > Query the final result
> 
> ```cs
> using (DataFilter.Disable<ISoftDelete>())
> {
>     queryableWithIncludeOther = queryable.Include(p => p.TestOthers).Where(p=>p.Price!=0);
>     var  list = await queryableWithIncludeOther.ToListAsync();
> }
> ```




> This is the current design.

ok  thank you
