### ISSUE TITLE
Unit of work documentation

### ISSUE THREAD

**Issue by fk-inspirit-tech** [abpframework/abp#12717]
The documentation is not very clear on the difference between SaveChangesAsync and CompleteAsync.

For example, using **isTransactional:true**
`using (var uow = _unitOfWorkManager.Begin(requiresNew: false, isTransactional: true))`

will require CompleteAsync to commit the transaction.

SaveChangesAsync does not commit the transaction.

Thanks

**Comment by maliming** [comment]
hi, Thanks, We will always enhance our documents.

**Comment by AlanLaiTw** [comment]
@maliming 

The current ABP official documentation still lacks sufficient explanation regarding `uow.CompleteAsync`, which has caused a lot of confusion during development.

It would be greatly beneficial for all developers if the documentation could provide detailed explanations or examples about the effects of `SaveChangesAsync`, `autoSave` behavior of repositories, `uow.CompleteAsync`, etc., when `uow.isTransactional` is set to either true or false.

Thank you to the ABP official team for your efforts.

(By the way, I am a ABP Commercial user. Should suggestions like this be posted here or in the official support forum?)

**Comment by maliming** [comment]
Hi @AlanLaiTw 

I will add more explanation.

**Comment by maliming** [comment]
hi @AlanLaiTw 

https://github.com/abpframework/abp/blob/Understanding-Transactions-in-ABP-Unit-Of-Work/docs/en/Community-Articles/2025-01-24-Understanding-Transactions-in-ABP-Unit-Of-Work/POST.md
