### ISSUE TITLE
call an action without Authorization   status code  error 

### ISSUE THREAD

**Issue by AliNemati22** [abpframework/abp#12726]
hello
when I try to call an action but i didn't authorized . Action returns 200 status code 

who i can manage this error  and get relevant status code like 401,403

![XC](https://user-images.githubusercontent.com/30621563/169965882-5b1262b6-ebc2-455b-98f0-b21610eccf91.jpg)

**Comment by maliming** [comment]
* Your **ABP Framework version**.

**Comment by memhi** [comment]
i also have this problem with version 6

**Comment by ikappas** [comment]
@maliming I get the same error on ABP Framework 5.2.2

I reproduced the issue in the default MVC project template where the HttpAPI is hosted on the same port with the Web and the user is not authorized to have access to the called API resource. 

Calling the API method gets a response status 200 with a body of the rendered HTML page with an `Access Denied!` error message with a `You do not have access to this resource.` short description (see below).

<img width="448" alt="image" src="https://user-images.githubusercontent.com/7887523/170090377-8b4a15a9-3170-46a3-a02b-daadb81426af.png">

**Comment by maliming** [comment]
hi all

See https://github.com/abpframework/abp/issues/9926

**Comment by sahvey** [comment]
```
context.Services.ConfigureApplicationCookie(options =>
{
    // Forward any requests that start with /api to the JWT scheme.
    options.ForwardDefaultSelector = ctx =>
    {
        return ctx.Request.Path.StartsWithSegments("/api") ? JwtBearerDefaults.AuthenticationScheme : null;
    };
});

context.Services.AddAuthentication()
    .AddJwtBearer(options =>
    {
        options.Authority = configuration["AuthServer:Authority"];
        //...
    });
```

When i set it as above, when i use postman or swaggere, only Error codes such as 401 or 403 are returned as seen below. 
![Error2](https://user-images.githubusercontent.com/46441777/170256697-154bb1f6-8603-4100-8c5c-3c8ed2c76382.png)

However, as seen below, an error should be returned according to the 401 or 403 error message template. 
![Error1](https://user-images.githubusercontent.com/46441777/170256615-11539ab6-1b14-4e09-9dcd-e05d839c930b.png)

@maliming In other words, the solution you specified does not completely solve our problem.

**Comment by maliming** [comment]
This is JWT Bearer authentication behavior. It's by design.

https://github.com/dotnet/aspnetcore/blob/fd1891536f27e959d14a140ff9307b6a21191de9/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L214
https://github.com/dotnet/aspnetcore/blob/fd1891536f27e959d14a140ff9307b6a21191de9/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L288

**Comment by AliNemati22** [comment]
> ```
> context.Services.ConfigureApplicationCookie(options =>
> {
>     // Forward any requests that start with /api to the JWT scheme.
>     options.ForwardDefaultSelector = ctx =>
>     {
>         return ctx.Request.Path.StartsWithSegments("/api") ? JwtBearerDefaults.AuthenticationScheme : null;
>     };
> });
> 
> context.Services.AddAuthentication()
>     .AddJwtBearer(options =>
>     {
>         options.Authority = configuration["AuthServer:Authority"];
>         //...
>     });
> ```
> 
> When i set it as above, when i use postman or swaggere, only Error codes such as 401 or 403 are returned as seen below. ![Error2](https://user-images.githubusercontent.com/46441777/170256697-154bb1f6-8603-4100-8c5c-3c8ed2c76382.png)
> 
> However, as seen below, an error should be returned according to the 401 or 403 error message template. ![Error1](https://user-images.githubusercontent.com/46441777/170256615-11539ab6-1b14-4e09-9dcd-e05d839c930b.png)
> 
> @maliming In other words, the solution you specified does not completely solve our problem.

hi 
in which file i must put this code?

**Comment by maliming** [comment]
hi

In your startup project(`Web`).
