### ISSUE TITLE
samples MicroserviceDemo  Unable to run directly

### ISSUE THREAD

**Issue by JackGMChen1988** [abpframework/abp#1273]
MicroserviceDemo Unable to run directly,There's a lack of CreateMap? This can be confusing for beginners，! Is this a test?
![image](https://user-images.githubusercontent.com/45810364/59403712-53cd6c00-8dd6-11e9-90f9-d4ef8dd2e5be.png)

**Comment by yekalkan** [comment]
Hi,

Thanks for reporting. This is an unintended issue of course.
