### ISSUE TITLE
Consider implementing `ISO 8601` DateTime Standard

### ISSUE THREAD

**Issue by j0nimost** [abpframework/abp#12731]
Looking at `IClock` implementation https://github.com/abpframework/abp/blob/04b4019263c61349a69a7f5e1987829c801bd205/framework/src/Volo.Abp.Timing/Volo/Abp/Timing/Clock.cs#L16-L40
The DateTime generated lacks timezone designators. Considering that this interface is used to set `IHasCreationTime` and others. My proposals include;
- Either we have an extra set of interfaces that use `DateTimeOffset` instead; (**NOTE**: NpgSQL 6.0 introduced a breaking change)
- Implement an abstraction layer that converts DateTime to `ISO 8601` standards. (Since we already have DateTime.Kind)

**Comment by maliming** [comment]
hi

We have no plans to refactor this class. It works fine so far, if you have problems please share details and steps to reproduce.


For NpgSQL DateTime problem see https://github.com/abpframework/abp/issues/11357

**Comment by j0nimost** [comment]
the link to https://github.com/abpframework/abp/issues/11357 answered my question.
