### ISSUE TITLE
how to disable audit logging for appservices by type or name selectors

### ISSUE THREAD

**Issue by journey191** [abpframework/abp#12747]
I want to disable audit logging for  some appservice from diffrent modules,can I make it by type(or name) selector instead of overriding appservice (add `[DisableAuditing]` attribute) 1 by 1?

**Comment by maliming** [comment]
Try to override the [AuditingHelper](https://github.com/abpframework/abp/blob/46de78b1b8bd1d7dff06e808179d08c0c3c958ca/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingHelper.cs#L55)

**Comment by journey191** [comment]
OK,then
