### ISSUE TITLE
ABP version 5.4 has been changed to version 6.0

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12757]
We had planned to release the version 5.4.0-rc.1 on June 28. However, we've decided to skip the 5.4 version and release it as 6.0 at the same date. There are a few reasons for that, including;

* We've completed the OpenIddict integration earlier than we expect. With the next version, startup templates will come with OpenIddict instead of IdentityServer. This won't be a breaking change for existing applications when you upgrade to 6.0, because we will continue to ship the IdentityServer module packages. However, we see this is a major change for new solutions, big change in examples and documentation. So, a major version change will better reflect it. BTW, we became a main sponsor to the [OpenIddict project](https://github.com/openiddict/openiddict-core) to help the project to survive, so we won't need to change it in the future. We will announce the details soon.
* We are planning to release the LeptonX theme's 1.0 version which will be compatible with ABP's 6.0. We see this work as a part of ABP's next release. Our goal to make the LeptonX as the default theme and allow us to select the basic theme if we want.
* We are planning to align with .NET's 7.0 version (ABP 7.0 runs on .NET 7.0 and will be release just after it).

You can see https://github.com/abpframework/abp/milestones for our release planning.

**Comment by leonkosak** [comment]
Great! Seems logical to me.
Will be able to upgrade (make transition) from IdentityServer to OpenIddict for existing solutions?

**Comment by hikalkan** [comment]
@leonkosak yes, we will be preparing a migration guide.
