### ISSUE TITLE
How to set LogoUrl in a multi page application

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#12764]
I set LogoUrl in my BrandingProvider as bellow
```
public override string LogoUrl = "logo.ico"
```
It works fine on the Home page, but cannot worked on the identity management page which points to the path: /identity/logo.ico

how should i set LogoUrl in this scenario

**Comment by roc916** [comment]
Try add '/' 
`public override string LogoUrl = "/logo.ico"`
