### ISSUE TITLE
Unable to display DataTable

### ISSUE THREAD

**Issue by ozdemiribrahim07** [abpframework/abp#12776]
I am doing as written in the documentation but the javascript file is giving this error every time. 
What change do I need to make in the js file?

"DataTables warning: table id=BooksTable - Requested unknown parameter 'name' for row 0, column 0."

![fffff](https://user-images.githubusercontent.com/60386171/170524735-f1e3ade6-ae17-4ded-b077-ffec1ef1911b.PNG)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
