### ISSUE TITLE
Cannot resolve section 'styles' and section 'scripts' in template

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#12771]
Mvc project throw Cannot resolve section 'styles' and section 'scripts' while open solution in Jetbrains Rider 2022.1.1

![G_HB91B8V% IP2%OGFGCTYX](https://user-images.githubusercontent.com/24971860/170489556-58c4df05-9cef-4788-8c84-5f5b717c60a8.png)

**Comment by maliming** [comment]
It's a Rider problem and there's nothing we can do about it.
