### ISSUE TITLE
Commercial Live Demo returns a 500 error

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#12787]
https://commercial.abp.io/demo

![image](https://user-images.githubusercontent.com/69393775/170654139-511af981-c4da-41fc-93e6-97cb951db903.png)

**Comment by maliming** [comment]
hi

You can try it in Chrome incognito mode.

**Comment by DonVliet** [comment]
> hi
> 
> You can try it in Chrome incognito mode.

Thanks, I just wanted to make you aware of it :-)
