### ISSUE TITLE
ICurrentUser value where is from? Why Id is always empty IsAuthenticated is always false

### ISSUE THREAD

**Issue by xuanhe168** [abpframework/abp#12795]
![87a785af2d8ef92302ab83939253de4](https://user-images.githubusercontent.com/37821420/170838467-a4fbf057-27a7-49be-aa8b-fbe265897230.png)

**Comment by realLiangshiwei** [comment]
See: https://github.com/abpframework/abp/blob/dev/docs/en/CurrentUser.md#changing-the-current-principal

`UserId` must be GUID value.

> I need to actually change the value in CurrentUser instead of short-term mocking how to do it?

You can change it in custom middleware
