### ISSUE TITLE
modules  web razor hot reload not work

### ISSUE THREAD

**Issue by Kastrcn** [abpframework/abp#12796]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/19508899/170853404-d99cf1ad-22c1-4ab8-a8d8-15754bfb11df.png">

modules  web razor hot reload not work
src web razor hot reload work

hot to  modules hot reload  work?

**Comment by maliming** [comment]
hi

You can try the same project structure without ABP in asp net core.

**Comment by Kastrcn** [comment]
> hi
> 
> You can try the same project structure without ABP in asp net core.

AbpVirtualFileSystemOptions not config  
hot reload not work    
config filepath   is work
thinks!
