### ISSUE TITLE
Embedded file system with special chars

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#128]
Try https://github.com/aspnet/FileSystem/issues/184#issuecomment-352907578 when Microsoft releases it. This will save us to change file/folder names while embedding.

Also see https://github.com/abpframework/abp/issues/2885#issue-569307163

**Comment by yshulin** [comment]
aspnet/FileSystem#184 (comment)
It seems that this bug was fixed by ASP.NET Core, but ABP team have not fixed it.
waiting...

**Comment by hikalkan** [comment]
duplicate of https://github.com/abpframework/abp/issues/4248
