### ISSUE TITLE
Test docs module while offline

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#12801]
It will be test how we get results when GitHub is inaccessible and there is relevant data in the database.

**Comment by EngincanV** [comment]
Map a dummy IP address with Github.com while testing. 
Make this mapping in the hosts file (c:\Windows\System32\Drivers\etc\hosts).

**Comment by EngincanV** [comment]
I've changed the host addresses in my "C:\Windows\System32\drivers\etc\hosts" file and when github.com and raw.githubusercontent.com are offline the content of the documentation is not seen. I'll create an issue for this problem.

---

Here are my host address mappings for testing:

```text
# github.com
  127.0.0.1  github.com
  127.0.0.1  raw.githubusercontent.com
```
