### ISSUE TITLE
Abp-cli switch command doesn't update projects in subfolders, doesn't use the sln file

### ISSUE THREAD

**Issue by barnybadzoo** [abpframework/abp#12808]
* Abp 5.3 RC *.
* Blazor Server*
* EFCore and MongoDB*

We have organizied our projects in the folder structure besides the src and test folder in subfolders like "projectx". If we use abp switch command it only updates the projects in the root of src and test, and skips subfolders. It doesn't seam to use the Visual Studio sln Project File to find the correct locations of the subprojects to update them also. If abp would use the sln file, also locations outside of src/test should work too.

**Comment by yekalkan** [comment]
https://github.com/abpframework/abp/issues/13050

**Comment by yekalkan** [comment]
https://github.com/abpframework/abp/pull/13051
