### ISSUE TITLE
There is an overlaps problem in the options of the document

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#12802]
<img width="1680" alt="Screen Shot 2022-05-30 at 09 47 05" src="https://user-images.githubusercontent.com/31216880/170933261-7599ef28-448a-44fe-9351-6b4f9ed1b943.png">

**Comment by halimekarayay** [comment]
This issue will be fixed when this issue is closed
(https://github.com/volosoft/volo/issues/9869)
