### ISSUE TITLE
Parameter is not passed when I try to access the value of localization.

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#12829]
**Expectation:** I expect the following two cases to pass the parameter in the same way.

### Case-1:
**Code**
```html
<head>
    <title>@L["AbpCommercialMetaTitle", "Test"]</title>
     ....
</head>
```
**Output:**
`<title>ABP Complete Web Development Platform : Test</title>`

### Case-2:
**Code**
```html
<head>
    <title>@L["AbpCommercialMetaTitle", "Test"].Value</title>
     ....
</head>
```
**Output:**
`<title>ABP - Complete Web Development Platform : {0}</title>`

**Note:** You can use [this](https://commercial.abp.io/startup-templates) page to reproduce the problem.

**Comment by maliming** [comment]
`@L["AbpCommercialMetaTitle", "Test"].Value`

The `Value` means `The original resource string, prior to formatting with any constructor arguments.`
