### ISSUE TITLE
Single-project startup template should not depend on Redis by default

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#12842]
I've created a new project with 5.3.0-rc.3:

````bash
abp new Acme.BookStore -t app-nolayers -u none --preview
````

When I run `migrate-database.ps1` it, I am getting error:

![image](https://user-images.githubusercontent.com/1210527/171398330-d99bc34c-c4e7-444d-9f36-1c3017eef294.png)

There are two problems here:

- First of all, even if we install redis, there is no need to use it for migration phase.
- Also, single-layer startup is thought for simplicity and we don't want to make it depending redis. This makes hard to start with it.

Please also check if other UI options depends on Redis? Also, check & fix all these for the ABP Commercial no-layers template.

**Comment by EngincanV** [comment]
Redis is removed from `app-nolayers` template for both abp and commercial sides.

**Comment by snoozemo** [comment]
> Redis 已从 abp 和商业端的模板中删除。`app-nolayers`

How can I obtain a template with Redis? It seems that there is no such option in ABP Studio, or what parameters should I use in the CLI?
