### ISSUE TITLE
Hangfire Work job not Auto delete

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#12856]

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by Nokecy** [comment]
1、use hangfire module
2、inherit  AsyncPeriodicBackgroundWorkerBase Implement a background worker
3、run for a while
4、remove background worker
Hangfire  job not remove

**Comment by Nokecy** [comment]
abp 5.3.0-rc.2

**Comment by realLiangshiwei** [comment]
The job is persisted by Hangfire, you need to remove the job in the Hangfire dashboard.
