### ISSUE TITLE
App settings with periods and Azure app service config incompatible

### ISSUE THREAD

**Issue by tellaconz** [abpframework/abp#12855]
Any ideas or alternatives here?

Settings in Abp use periods eg https://docs.abp.io/en/abp/latest/Emailing#email-settings

But Azure App Services configuration system doesn't allow them

"App setting names can't contain periods (.). If an app setting contains a period, the period is replaced with an underscore in the container."

https://docs.microsoft.com/en-gb/azure/app-service/configure-common?tabs=portal

The dev ops pipeline I'm using utilises the AzureAppServiceSettings@1 task which uses this, so I've hit a speed bump.

Thanks

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/6272
