### ISSUE TITLE
Remember me doesn't work 

### ISSUE THREAD

**Issue by tarikdevapp** [abpframework/abp#12854]
Using Abp 3.3.2 in the backend with Angular.
Im using the Account module, the same one in the docs. 

Leaving remember me unchecked and closing the broswer and reopening it just to finds that I am still logged in.

I even used the latest version of abp to create a new app with angular ui and the same problem is still there!

I'd appreciate any help

**Comment by maliming** [comment]
The `Remember me` is work for MVC application. Can you check it?

**Comment by tarikdevapp** [comment]
@maliming yes but not for angular, the access token is always set in localstorage even when remember me is unchecked. I'd like a way to set the token in session when remember is unchecked so that when the browser is closed the token would get deleted.

**Comment by TarikElHajjam** [comment]
!

**Comment by TarikElHajjam** [comment]
!

**Comment by TarikElHajjam** [comment]
!
