### ISSUE TITLE
Problem in Angular : subscribe(next: null | undefined, error: (error: any) => void, complete?: () => void): Subscription;

### ISSUE THREAD

**Issue by mustafaekicics** [abpframework/abp#12870]
ABP Framework version : 5.2.2
User Interface : Angular
Your database provider : Ef Core
Exception message : 

src/app/library/library.component.ts:58:13 - error TS2554: Expected 2-3 arguments, but got 1.

 58     request.subscribe(() => {
                ~~~~~~~~~~~~~~~~~
 59       this.isModalOpen = false;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 61       this.list.get();
    ~~~~~~~~~~~~~~~~~~~~~~
 62     });
    ~~~~~~

  node_modules/rxjs/internal/Observable.d.ts:51:39
    51     subscribe(next: null | undefined, error: (error: any) => void, complete?: () => void): Subscription;
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'error' was not provided.

Steps needed to **reproduce** the problem : https://docs.abp.io/en/abp/latest/Tutorials/Part-3?UI=NG&DB=EF 
I was following tutorial. I get stuck on update section. 

 const request = this.selectedLibrary.id
    ? this.libraryService.update(this.selectedLibrary.id, this.form.value)
    : this.libraryService.create(this.form.value);

    request.subscribe(() => {
      this.isModalOpen = false;
      this.form.reset();
      this.list.get();
    });
  }
}

I couldn't figure out what to do. I was simply trying to do what tutorial shows. Any thoughts where I am doing mistake?

![image](https://user-images.githubusercontent.com/60320671/171848128-76dba0a3-7073-4bb4-b509-e6c9707524f7.png)

**Comment by mustafaekicics** [comment]
![image](https://user-images.githubusercontent.com/60320671/171848774-e83b2411-e868-42ba-8f6a-5f25950c6f40.png)
In addition before that step there was no problem. Creating was working but at update step I faced with this issue.

**Comment by mustafaekicics** [comment]
![error popup](https://user-images.githubusercontent.com/60320671/171882997-82f7462c-c117-4807-b38e-da9f3ee389e4.jpg)
Error pops up like this

**Comment by realLiangshiwei** [comment]
You can check the source code: https://github.com/abpframework/abp-samples/tree/master/BookStore-Angular-MongoDb
