### ISSUE TITLE
Dynamic plugin loader

### ISSUE THREAD

**Issue by efeker** [abpframework/abp#1288]
Is there a way to load plugins from a directory instead of having hard references?

**Comment by hikalkan** [comment]
Find `services.AddApplication` in your `Startup` file. Use `options.PlugInSources` to add plugin files/folders. Example:

````csharp
services.AddApplication<AbpAspNetCoreMvcUiBootstrapDemoModule>(options =>
{
    options.UseAutofac();
    options.PlugInSources.AddFolder("C:\\MyPlugIns");
});
````

Will be documented soon.

**Comment by Nongzhsh** [comment]
@hikalkan Hi, I'm also trying plug-in development. I have a problem, that Main module cannot load plugin module's dependency assemblies. We should enhance this plug-in mechanism. 😁

Reference article: 
https://natemcmaster.com/blog/2018/07/25/netcore-plugins/   by: Nate McMaster

**Comment by hikalkan** [comment]
You're right @Nongzhsh. Please create a new issue to track this.
