### ISSUE TITLE
Get PermissionGrants

### ISSUE THREAD

**Issue by sahvey** [abpframework/abp#12895]
I have a Winform client project using Abp Framework. I'm logging in using OidcClient without any problems. But I can't get the list of permissions I've assigned roles or users. I need this list. Because I need to hide or show some buttons in the form based on the permissions of the logged in user.

I used the PermissionChecker class to get the list of permissions, but without success. What path should I follow?
I am able to login without any problem using AccessTokenHttpMessageHandler as seen below.

```
public class AccessTokenHttpMessageHandler : DelegatingHandler
    {
        protected OidcClient OidcClient { get; }
        public Token Token { get; }

        public AccessTokenHttpMessageHandler(OidcClient oidcClient, Token token) : base(new HttpClientHandler())
        {
            OidcClient = oidcClient;
            Token = token;
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var result = await OidcClient.LoginAsync(new LoginRequest());
            request.SetBearerToken(result.AccessToken);

            Token.User = result.User;
            Token.AccessToken = result.AccessToken;
            Token.RefreshToken = result.RefreshToken;
            request.SetBearerToken(result.AccessToken);

            return await base.SendAsync(request, cancellationToken);
        }
    }
```

**Comment by maliming** [comment]
hi

You can get auth info from `api/abp/application-configuration` endpoint. or integration remote services like [AbpAspNetCoreMvcClientCommonModule](https://github.com/abpframework/abp/tree/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.AspNetCore.Mvc.Client.Common/Volo/Abp/AspNetCore/Mvc/Client)

https://github.com/abpframework/abp/blob/11acd2fe5250d01fad78b86ee177ee237c31ec44/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationController.cs#L10

https://github.com/abpframework/abp/blob/11acd2fe5250d01fad78b86ee177ee237c31ec44/framework/src/Volo.Abp.AspNetCore.Mvc.Contracts/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/ApplicationConfigurationDto.cs#L12

https://github.com/abpframework/abp/blob/11acd2fe5250d01fad78b86ee177ee237c31ec44/framework/src/Volo.Abp.AspNetCore.Mvc.Contracts/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/ApplicationAuthConfigurationDto.cs#L11

**Comment by rushasdev** [comment]
Looks like `api/abp/application-configuration` endpoint doesn't provide the permission list anymore. Is there any other way to retrieve permission list for user using REST?
