### ISSUE TITLE
filter syntax in list services

### ISSUE THREAD

**Issue by lgadola** [abpframework/abp#12904]
There is a filter property (string) in CRUD list services.
I have not found any description of the syntax to use here.
Could somebody please elaborate on these filtering possibilities?
Thank you

**Comment by maliming** [comment]
> There is a filter property (string) in CRUD list services.

Can you share the code?

**Comment by lgadola** [comment]
sorry, I was mistaken.
Thought 'filter' was a standard property, but it is specific to IdentityUserAppService .
Thanks for your help.
