### ISSUE TITLE
What would be the correct way to implement the Microsoft.Graph package into ABP app? InvalidOperationException: IDW10503

### ISSUE THREAD

**Issue by yangl1n** [abpframework/abp#12911]
- **ABP Framework version:** v5.2.2
- **UI type**: MVC
- **DB provider**: EF Core
- **Tiered (MVC) or Identity Server Separated (Angular)**: no

We are attempting to incorporate support for calling Microsoft Graph APIs in our ABP application, using the Microsoft.Graph package. We've already successfully implemented authentication using Azure AD accounts according to the directions in this post: [https://community.abp.io/posts/how-to-use-the-azure-active-directory-authentication-for-mvc-razor-page-applications-4603b9cf](https://community.abp.io/posts/how-to-use-the-azure-active-directory-authentication-for-mvc-razor-page-applications-4603b9cf?_ga=2.127396239.30640937.1654437454-1022470144.1653083631) (we used the second approach, using AddMicrosoftIdentityWebApp).

However, when attempting to add lines to set up the Microsoft Graph client, login with Azure AD no longer works (when Azure AD is selected as the login option, the login page reloads without logging in). Here is the code for our ConfigureAuthentication function in the WebModule.cs file:

```c#
private void ConfigureAuthentication(ServiceConfigurationContext context, IConfiguration configuration)
    {
        context.Services.AddAuthentication()
            .AddJwtBearer(options =>
            {
                options.Authority = configuration["AuthServer:Authority"];
                options.RequireHttpsMetadata = Convert.ToBoolean(configuration["AuthServer:RequireHttpsMetadata"]);
                options.Audience = "Portal";
            })
            .AddMicrosoftIdentityWebApp(configuration.GetSection("AzureAd"));
			// Login only succeeds when these three lines are commented out:
            .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
            .AddMicrosoftGraph(configuration.GetSection("DownstreamApi"))
            .AddInMemoryTokenCaches();
            
            context.Services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                options.Authority = "https://login.microsoftonline.com/" + configuration["AzureAd:TenantId"] + "/v2.0/";
                options.ClientId = configuration["AzureAd:ClientId"];
                options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                options.CallbackPath = configuration["AzureAd:CallbackPath"];
                options.ClientSecret = configuration["AzureAd:ClientSecret"];
                options.RequireHttpsMetadata = false;
                options.SaveTokens = false;
                options.GetClaimsFromUserInfoEndpoint = true;

                options.SignInScheme = IdentityConstants.ExternalScheme;

                options.ClaimActions.MapJsonKey(ClaimTypes.NameIdentifier, "sub");
            });
    }
```

In ABP, logins using OpenIdConnect stop going through after adding these three lines of code to initialize the Graph client component:

```c#
// Login only succeeds when these three lines are commented out:
            .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
            .AddMicrosoftGraph(configuration.GetSection("DownstreamApi"))
            .AddInMemoryTokenCaches();
```

When they're commented out, OpenIdConnect logins start working again. User can login and their email will display in right corner.

> And I check the log. Find problem is in ExternalLoginCallback, I trace the source code and found that the function try to call SignInManager.GetExternalLoginInfo() and this function return null.
>
> The log is here.

```
2022-06-06 19:29:46.976 +08:00 [INF] Request starting HTTP/2 GET https://localhost:44322/Account/Login?handler=ExternalLoginCallback - -
2022-06-06 19:29:46.978 +08:00 [INF] Executing endpoint '/Account/Login'
2022-06-06 19:29:46.978 +08:00 [INF] Route matched with {page = "/Account/Login", area = "", action = "", controller = ""}. Executing page /Account/Login
2022-06-06 19:29:46.978 +08:00 [INF] Skipping the execution of current filter as its not the most effective filter implementing the policy Microsoft.AspNetCore.Mvc.ViewFeatures.IAntiforgeryPolicy
2022-06-06 19:29:46.981 +08:00 [INF] Executing handler method Volo.Abp.Account.Web.Pages.Account.LoginModel.OnGetExternalLoginCallbackAsync - ModelState is "Valid"
2022-06-06 19:29:46.986 +08:00 [WRN] External login info is not available
2022-06-06 19:29:46.986 +08:00 [INF] Executed handler method OnGetExternalLoginCallbackAsync, returned result Microsoft.AspNetCore.Mvc.RedirectToPageResult.
2022-06-06 19:29:46.986 +08:00 [INF] Executing RedirectToPageResult, redirecting to ./Login.
2022-06-06 19:29:46.986 +08:00 [INF] Executed page /Account/Login in 8.6479ms
2022-06-06 19:29:46.986 +08:00 [INF] Executed endpoint '/Account/Login'
2022-06-06 19:29:46.987 +08:00 [INF] Request finished HTTP/2 GET https://localhost:44322/Account/Login?handler=ExternalLoginCallback - - - 302 - - 11.1769ms
```

Why would this happen?

> It seems like problem is happening in GetExternalLoginInfo(), I try to override that function of SignInManager follow by the guide.
>
> https://docs.abp.io/en/abp/2.8/How-To/Customize-SignIn-Manager 
>
> And find if I replace `ClaimTypes.NameIdentifier` in the following code to `"sub"`, the login works.

`var providerKey = auth.Principal.FindFirstValue(ClaimTypes.NameIdentifier);`

> In configuration, the following line has set up a map. However, it doesn't work when adding those three lines above. Need to change it explicitly to "sub" in GetExternalLoginInfo().

`options.ClaimActions.MapJsonKey(ClaimTypes.NameIdentifier, "sub");`

> That is after adding those three lines, somehow the map above doesn't work?

**The Source Code**

You can find the reproduce [code](https://github.com/mayiIG/Portal) here.

**Comment by gterdem** [comment]
I don't think OpenIdConnect integration is related to Microsoft Graph API. You should be able to request Microsoft Graph API from an empty .NET application without any 3rd party login or user management right?

Sorry, I have no experience on Microsoft.Graph API.

**Comment by yangl1n** [comment]
@gterdem 
Hi, sorry for the question again. I found some new things today and edited the question. Hope it will be more clear. The issue begins in 3rd party login steps and progresses to graph client.

**Comment by ScottRJones** [comment]
@yangl1n - Hi, did you ever find a solution to this? We are also trying to implement Graph in ABP and having difficulties. Thank you

**Comment by nitrovent** [comment]
@yangl1n @ScottRJones I'm facing the same issue. Both with `AddMicrosoftIdentityWebApp()` as well as with `AddOpenIdConnect`. Have you found a solution?

**Comment by ScottRJones** [comment]
Hi @nitrovent 

Yes, after alot of trial and error, we have now successfully configured ABP with Microsoft Graph. I've included our setup from the **Configure** method of **AuthConfigurer** below. I hope this helps! Please let me know if not and I can try to help if I can. 
```

var initialScopes = configuration.GetValue<string>("Authentication:DownstreamApi:Scopes")?.Split(' ');

var authenticationBuilder = services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme);

authenticationBuilder.AddMicrosoftIdentityWebApp(configuration.GetSection("Authentication:AzureAd"), OpenIdConnectDefaults.AuthenticationScheme)

.EnableTokenAcquisitionToCallDownstreamApi(options =>
{
    configuration.Bind("Authentication:AzureAd", options);
}, initialScopes)    
.AddMicrosoftGraph(configuration.GetSection("Authentication:DownstreamApi"))
.AddDistributedTokenCaches();

services.AddDistributedSqlServerCache(options =>
{
    options.ConnectionString = configuration["ConnectionStrings:Default"];
    options.SchemaName = "dbo";
    options.TableName = "TokenCache";
    options.DefaultSlidingExpiration = TimeSpan.FromMinutes(90);
});

services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
    options.Authority = "https://login.microsoftonline.com/" + configuration["Authentication:AzureAd:TenantId"] + "/v2.0/";
    options.ClientId = configuration["Authentication:AzureAd:ClientId"];
    options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
    options.CallbackPath = configuration["Authentication:AzureAd:CallbackPath"];
    options.ClientSecret = configuration["Authentication:AzureAd:ClientSecret"];
    options.RequireHttpsMetadata = false;
    options.SaveTokens = false;
    options.GetClaimsFromUserInfoEndpoint = true;
    options.SignInScheme = IdentityConstants.ExternalScheme;                
    options.ClaimActions.MapJsonKey(ClaimTypes.NameIdentifier, "sub");
});
```

**Comment by nitrovent** [comment]
Thank you very much for your reply, @ScottRJones.
I will try this!

Edit: Worked on the first try!
I had to use Community.Microsoft.Extensions.Caching.PostgreSQL for the distributed token cache because we do not use SQL Server but other than that no problems. Now I will try to find if the cache was the only thing missing from our attempts.
Thank you again, spared me many potential head aches.
