### ISSUE TITLE
File chunking endpoint creates huge amounts of audit logging

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#12916]
Hi I have a controller action that is uploading files using chunking. For a 1.7 GB file with my current chunk size that means 500 entries into the ~~AbpAuditLogActions~~ AbpAuditLogs table. The table becomes useless. 

I need to be able to disable auditing on that particular action method but [DisableAuditing]  doesn´t  do that.

What is the best approach to accomplish this?

**ABP Framework version**. 4.2.2
**User Interface**: MVC/Blazor
**Your database provider**: EF Core

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by sturlath** [comment]
Upload a file with chunk uploading using [Syncfusion Blazor File Upload Component](https://blazor.syncfusion.com/documentation/file-upload/chunk-upload) (or any other chunk upload library you can find) and see every call being saved to the ~~AbpAuditLogActions~~ AbpAuditLogs table.

Basically like the Syncfustion code 
```csharp
[HttpPost("[action]")]
public void Save(IList<IFormFile> chunkFile, IList<IFormFile> UploadFiles)
{

}
```

Mine is like this (because of various reasons)

```csharp
[DisableAuditing]  // Doesn´t work!
[HttpPost("[action]")]
[IgnoreAntiforgeryToken]
[DisableFormValueModelBinding] 
[DisableRequestSizeLimit] 
public virtual async Task Save(IList<IFormFile> chunkFile)
{
}
```

Since its called many (500x) times for each big file upload it logs 500x.

**Comment by maliming** [comment]
Full steps or code. Thanks

**Comment by sturlath** [comment]
Here you go @maliming [FileChunkingAuditLog repo](https://github.com/sturlath/FileChunkingAuditLog)

try "uploading" any file larger than c.a 2.5 MB and see it being split up (chunked) and with each upload an audit is made (making that table useles). It must be an easy way to turn it off, right?

**Comment by maliming** [comment]
I tested, `DisableAuditing` works.

**Comment by sturlath** [comment]
Wrong table @maliming, I don´t know why I was pointing to the AbpAuditLogActions  table... its the **AbpAuditLogs** one that gets filled up

Here is a screenshot of my uploading c.a 960 MB and I have 332 new rows in the table just from that upload...
![image](https://user-images.githubusercontent.com/2386572/173507414-f2e80c63-5037-486f-9e45-9805d64428a8.png)

**Comment by KevinBassaDevelopment** [comment]
We have the same issue, a simple HttpPost endpoint, DisableAuditing is not working.
DisableAuditing is also not working for this endpoint when put on the whole controller.

```
[DisableAuditing]  // Doesn´t work!!
[HttpPost("custom-log")]
public virtual async Task CustomLog(IList<CustomLogDto> customLogsDto)
{
     // logs DTO to a custom DB Table basically just a mapping and a DB insert (to another simple db Entity)
     // for every log here the auditlog also creates an entry for httppost - api/path/custom-log
} 
```

**Comment by maliming** [comment]
@KevinBassaDevelopment 

Full steps to reproduce.

**Comment by sturlath** [comment]
Do you need that from @KevinBassaDevelopment if you have my code? Did you try it again @maliming ?

**Comment by KevinBassaDevelopment** [comment]
@maliming  I dont know why you need a second example that again shows the bug, but here you go:
https://github.com/KevinBassaDevelopment/abp.io-buggy-auditlog

Steps:
 1) Downloaded ABP Startup template (blazor/sqlserver)
 2) Added BuggyController.cs to HttpApi project containing just 1 endpoint with [DisableAuditing] .
 3) Send something to this endpoint via swagger. Call will be added to auditlogs (but should not!)

**Comment by maliming** [comment]
```cs
[AllowAnonymous]
[Route("api/buggy-again")]
public class BuggyController : DisableAuditingBugController
{
    [HttpPost("disable-log-something")]
    [DisableAuditing]
    public async Task DisableLogSomething([FromBody] SeriLogDto[] body)
    {
        // DisableAuditing is ignored. Each call of "api/buggy-again/log-something" is logged in auditlogs
    }

    [HttpPost("log-something")]
    public async Task LogSomething([FromBody] SeriLogDto[] body)
    {
        // DisableAuditing is ignored. Each call of "api/buggy-again/log-something" is logged in auditlogs
    }
}
```

### LogSomething
![image](https://user-images.githubusercontent.com/6908465/174231214-717ff3a0-1c18-40e4-bc04-d645595260e8.png)


### DisableLogSomething
![image](https://user-images.githubusercontent.com/6908465/174231260-8019a17c-afea-4a12-9e87-16ebb545e5ef.png)


---

> Send something to this endpoint via swagger. Call will be added to auditlogs (but should not!)

If you do not want the request to be logged.

```cs
public override void ConfigureServices(ServiceConfigurationContext context)
{
    Configure<AbpAspNetCoreAuditingOptions>(options =>
    {
        options.IgnoredUrls.Add("/api/buggy-again");
    });
}
```

**Comment by KevinBassaDevelopment** [comment]
Thank you for the solution!
It would be really helpful if this was added to the audit logging documentation: https://docs.abp.io/en/abp/latest/Audit-Logging
