### ISSUE TITLE
AuditedAggregateRootDto

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1292]
public class AuditedAggregateRootDto<TPrimaryKey> : AuditedEntityDto<TPrimaryKey>, IHasExtraProperties, IHasConcurrencyStamp
    {
        public virtual Dictionary<string, object> ExtraProperties { get; set; }

        public virtual string ConcurrencyStamp { get; set; }
    }

Could you please add it in? thx.

**Comment by hikalkan** [comment]
Hi,

`ExtraProperties` may not be always shared to clients. We should be careful about that. If you want, please explicitly implement `IHasExtraProperties` for your DTO.

`ConcurrencyStamp` is also not implemented in most scenarios. Implement `IHasConcurrencyStamp` for your DTO if you want to implement it.

We won't implement this. But you can create such a class in your project if you like.

Thanks for your suggestion.

**Comment by gdlcf88** [comment]
I understand now.
