### ISSUE TITLE
Using rebus event handlers are fired twice

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#12925]
* Your 5.2.2
* Your database provider(EF Core)

When using an ETO which extends from a base class like below: 

`[EventName("TestEvent")]
public class TestEventEto : BaseEvent
{
    
}`

Event handlers are called twice.

Thanks in advance :)

**Comment by realLiangshiwei** [comment]
Can you check this:https://github.com/abpframework/abp/issues/12659
