### ISSUE TITLE
Create my own general exception handler middleware

### ISSUE THREAD

**Issue by Osama94** [abpframework/abp#12929]
When creating our own global exception handler middleware instead of AbpExceptionHandlingMiddleware and AbpExceptionFilter

- the behavior still as default and didn't hit my own handler.
-tried to remove AbpExceptionFilter from filters but I couldn't.

Is there any way to override the default exception handler?

Thanks in advance

@ABP #ABP #abp

**Comment by realLiangshiwei** [comment]
You can add your own exception middleware after `app.UseUnitOfWork();`

> tried to remove AbpExceptionFilter from filters but I couldn't.

You can try to replace the service from the dependency container. for example:

```csharp
[ExposeServices(typeof(AbpExceptionFilter), typeof(IAsyncExceptionFilter))]
public class MyAbpExceptionFilter : AbpExceptionFilter , ITransientDependency
```

**Comment by realmingliang** [comment]
`  app.Properties["_AbpExceptionHandlingMiddleware_Added"] = true;
     app.UseMiddleware<MyExceptionHandlingMiddleware>();`

**Comment by diennttlu** [comment]
I have a middleware ExceptionMiddleware. When calling api from PostMan and getting an error I can try/catch in the middleware's Invoke. But calling api from abp angular and getting an error the code runs into AbpExceptionMiddleware, which is not what I want. I want to catch the exception from the middleware.
