### ISSUE TITLE
Blazor wasm AddHttpMessageHandler not working

### ISSUE THREAD

**Issue by xuanhe168** [abpframework/abp#12931]
![image](https://user-images.githubusercontent.com/37821420/172536313-df2d468c-7438-4cc9-8063-dc1fead9d777.png)

the SendAsync method not working
![image](https://user-images.githubusercontent.com/37821420/172536343-1b5a20b0-7e58-42c9-b061-37ba7ae399f6.png)

**Comment by xuanhe168** [comment]
I need to intercept every request information, am I wrong or is there a way

**Comment by maliming** [comment]
Try to custom http client here.

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/Proxying/DefaultProxyHttpClientFactory.cs#L6

**Comment by mingyouzhu** [comment]
Perfect!!! it's works for me thank you big bro
![image](https://user-images.githubusercontent.com/37821420/172551900-a4a6d98a-d0ce-4599-a738-def9021130d2.png)

**Comment by xuanhe168** [comment]
Perfect!!! it's works for me thank you big bro
![image](https://user-images.githubusercontent.com/37821420/172551900-a4a6d98a-d0ce-4599-a738-def9021130d2.png) @
