### ISSUE TITLE
Create tenant with id

### ISSUE THREAD

**Issue by eneskoroglu** [abpframework/abp#12965]
I have multiple ABP projects. And I want to create same tenant under some of them with same id. When i look at `tenantManager` or `tenantRepository`, i cannot create a tenant with a specific id. How can i do this? Or can you change tenantId from protected to public or add a parameter to `tenantManager.createAsync` method for tenantId.

* Your **ABP Framework version**. : 4.4.4

**Comment by realLiangshiwei** [comment]
> And I want to create same tenant under some of them with same id

Why not make tenant management a separate application? you can share it in multiple projects.

**Comment by eneskoroglu** [comment]
Hi [realLiangshiwei](https://github.com/realLiangshiwei)

There is two scenarios:

1. If i create all tenants (SassTenants data) on a seperate database, i will have problem to understand which records related to which tenant?
2. If i create all tenants in every project, then every application gives different id to sameTenant and when i try to combine data for ex. on a datawarehouse, i cannot match data via tenantId for same tenant.

**Comment by realLiangshiwei** [comment]
All right.

>  i cannot create a tenant with a specific id. How can i do this?

This is by design, you can't do it

In fact, you don't need to create a tenant with the same id, since the `Tenant` entity is extensible, you can use the same business id, see: https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities#entity-extensions-ef-core

For example:

```csharp
var tenant = TenantManager.CreateAsync("test");
tenant.SetProperty("BusinessId", Guid.NewGuid());
```
