### ISSUE TITLE
LeptonX Lite RTL Wrong

### ISSUE THREAD

**Issue by khaledpro2012** [abpframework/abp#12979]
LeptonX Lite Wrong RTL  direction
Not Redirect Page correctly

**Comment by maliming** [comment]
Please send some screenshots?

**Comment by ismcagdas** [comment]
@khaledpro2012 LeptonX has some problems with RTL and we are aware of that. We are planning to release 1.0 version of LeptonX with RTL support. We are tracking the issue internally, but I will also keep this issue open and inform you once LeptonX RTL support is done and released.

**Comment by yasinhallak** [comment]
hello there ...
Has this issue been fixed in new version 6.0 rc ?

**Comment by yasinhallak** [comment]
hi there ...
we need RTL leptonX ...
when will solve this Issue in Commercial Abp ??

**Comment by ismcagdas** [comment]
@yasinhallak our expectation is to release it with LeptonX 1.0. The plan is to release it in 2-3 weeks.

**Comment by yasinhallak** [comment]
> @yasinhallak our expectation is to release it with LeptonX 1.0. The plan is to release it in 2-3 weeks.

Hi There . 
We need RTL leptonX commercial app 
 will you  solve this issue in version 6.0.0 ??

**Comment by ismcagdas** [comment]
We are planning to release ABP Commercial 6.0 in 1-2 days but as I said, LeptonX 1.0 will be released a bit later. Our expectation is 2-3 weeks from now. When LeptonX 1.0 is released, you will be able to update your NuGet and NPM packages and you will get the RTL feature on your app.
