### ISSUE TITLE
LeptonX Lite: bug of menu item auto selected

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#12978]
![1655030999018](https://user-images.githubusercontent.com/30018771/173229596-d70d2b88-5fa1-4bf4-8d38-034274a66197.jpg)
![1655030904964](https://user-images.githubusercontent.com/30018771/173229599-fdcd82ec-6555-48ad-a057-ba49d78e99df.jpg)

**Comment by enisn** [comment]
This will be implemented after ABP 5.3 release to LeptonX.
https://github.com/abpframework/abp/pull/12840

Selected menu item name can be set in PageLayout. If you project will set selected menu item name after v5.3, everything will work fine

**Comment by enisn** [comment]
You can implement in your project according to this documentation:
https://github.com/abpframework/abp/blob/1a6c44d3abe2a9165b598ed0aa68d780c6f680b5/docs/en/UI/Blazor/Page-Layout.md#menuitemname

**Comment by enisn** [comment]
I assume that is Blazor UI right?

**Comment by gdlcf88** [comment]
> I assume that is Blazor UI right?

No, it's MVC.

**Comment by enisn** [comment]
@gdlcf88 

Can you try implementing this one in your application?
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Page-Header#the-selected-menu-item
If you inject `IPageLayout` to your page model and set menuitemname like below, it'll directly select that menuitem without any url check.

```csharp
PageLayout.Content.MenuItemName = "BookStore.Books";
```

**Comment by gdlcf88** [comment]
@enisn - It had been set.

https://github.com/EasyAbp/EShop/blob/dev/modules/EasyAbp.EShop.Stores/src/EasyAbp.EShop.Stores.Web/Pages/EShop/Stores/Transactions/Transaction/Index.cshtml#L15

**Comment by enisn** [comment]
So it seems there is a bug, I'll figure it out

**Comment by enisn** [comment]
I've found and fixed the issue. It wasn't working recursively. So if your menuitem is in the root, yes it works but if it's under a menuitem it doesn't work. It'll be included in the next release of LeptonX

You can override `MenuViewModelProvider` to fix it immediately in your project like below:


```csharp
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(MenuViewModelProvider))]
public class MyMenuViewModelProvider : MenuViewModelProvider
{
  protected override bool SetActiveMenuItems(IList<MenuItemViewModel> items, string activeMenuItemName)
  {
    foreach (var item in items)
    {
      if(SetActiveMenuItems(item.Items, activeMenuItemName) || item.MenuItem.Name == activeMenuItemName)
      {
        item.IsActive = true;
        return true;
      }
    }
    
    return false;
  }
}
```

**Comment by gdlcf88** [comment]
@enisn - It works now. Thanks for your time.

![image](https://user-images.githubusercontent.com/30018771/173578826-7a6f1ed7-f316-4dfe-9995-38b68c540c83.png)

**Comment by berkansasmaz** [comment]
Thanks for the help @enisn 😊

---
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
