### ISSUE TITLE
The repository supports the functionality of EFCore.BulkExtensions

### ISSUE THREAD

**Issue by ChengYen-Tang** [abpframework/abp#12976]
Can the repository support the functionality of [EFCore.BulkExtensions](https://github.com/borisdj/EFCore.BulkExtensions)?
Likes: Batch, BulkInsertOrUpdateOrDelete... others

**Comment by realLiangshiwei** [comment]
See: https://github.com/abpframework/abp/pull/6676

ABP provides basic batch methods and abstract [`IEfCoreBulkOperationProvider`](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/IEfCoreBulkOperationProvider.cs) interface

You can create your own class implementing the `IEfCoreBulkOperationProvider` interface to integrate the EFCore.BulkExtensions

**Comment by ChengYen-Tang** [comment]
Can I add InsertOrUpdate and InsertOrUpdateOrDelete functions to the repository and then open PR?
I think this feature is useful.

**Comment by realLiangshiwei** [comment]
Thanks, see: https://github.com/abpframework/abp/pull/6679#issuecomment-747249051

**Comment by puschie286** [comment]
@ChengYen-Tang 
we use it with the abp repository "Many" methods ( [Gist Ref](https://gist.github.com/puschie286/abda9724e3ef16cc98c68089b96755ea) ).
because its not tracking by default, you need to enable tracking or manually call PublishEntityEvent for each entity to trigger registered events
