### ISSUE TITLE
the problem of enum converter in list  page of sample project bookstore

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#1298]
in the sample project of bookstore; the booktype is shown as below:
![image](https://user-images.githubusercontent.com/2950822/59660534-616e6180-91db-11e9-945b-26498f5f4050.png)
I can write a switch transforming the value, however is there a more efficient (briefer) way of casting an int to enum? 
![image](https://user-images.githubusercontent.com/2950822/59660473-3126c300-91db-11e9-9023-21273e10d18d.png)
One reason is, I don't want to constantly have to change the switch, in case I change the enum. I guess I could use an array with the enum names and construct an identifier to index into the enum, however again, I would need to change the array every time the enum is changed. I guess what I am looking for is a transparent method, that doesn't require beforehand knowledge of the enum.
thanks a bunch!

**Comment by maliming** [comment]
Try use `datatables columns render` https://datatables.net/reference/option/columns.render
```
$('#example').dataTable( {
  "columnDefs": [ {
    "targets": 0,
    "data": "download_link",
    "render": function ( data, type, row, meta ) {
      return '<a href="'+data+'">Download</a>';
    }
  } ]
} );
```

**Comment by johnnba** [comment]
> Try use `datatables columns render` https://datatables.net/reference/option/columns.render
> 
> ```
> $('#example').dataTable( {
>   "columnDefs": [ {
>     "targets": 0,
>     "data": "download_link",
>     "render": function ( data, type, row, meta ) {
>       return '<a href="'+data+'">Download</a>';
>     }
>   } ]
> } );
> ```

that's what i have done to get the 2nd picture for illustration. 
Is there a more efficient (briefer) way of casting an int to enum? 

{
//                title: "booktype",
                data: "type",
                render: function (data, type, full) {
//                    console.log(data);
 
                    if (data == 0)
                        return "Undefined";
                    if (data == 1)
                        return "Advanture";
                    else if (data == 2)
                        return "Biography";
                    else if (data == 3)
                        return "Dystopia";
                    else if (data == 4)
                        return "Fantastic";
                    else if (data == 5)
                        return "Horror";
                    else if (data ==6)
                        return "Science";
                    else if (data == 7)
                        return "ScienceFiction";
                    else if (data == 8)
                        return "Poetry";
                },
            },

**Comment by maliming** [comment]
You can consider converting on the back end and then returning to the front end via DTO.
There seems to be no good way to convert in the front end.

**Comment by johnnba** [comment]
however  in the abp framework, the create and update modal page , the enum is got transformed nice in the dropdownlist without any extra code by front end.
![image](https://user-images.githubusercontent.com/2950822/59662013-a5af3100-91de-11e9-8a30-4013dea616fd.png)
i'mnot  familiar with abp framework , i guess there should be some cute work have be done before i find it.

**Comment by yekalkan** [comment]
You can send it as string to front-end, if you are using it for view only. That's what we do for now.

> however in the abp framework, the create and update modal page , the enum is got transformed nice in the dropdownlist without any extra code by front end.

AbpSelectTagHelper handles it in back-end.

**Comment by johnnba** [comment]
yeah, got it. sincerely thanks. the issue can be closed. 
Is  there any improvements  to solve the issue in the future if you think it deserved.
