### ISSUE TITLE
It warns NPM is not installed when run abp install-libs,but I have installed .

### ISSUE THREAD

**Issue by xiaoyc** [abpframework/abp#12995]
Your ABP Framework version: 5.2.2 (Stable)
Your User Interface: MVC
Your database provider(EF Core/MongoDB): EF Core

The start template throw AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'! error .

when I try to run the abp install-libs, it warns the NPM is not installed ,but I have installed it .

I saw there maybe some defects  for the yarn detection .  #12970  ,is there any way to workaround ,Thanks . 

![image](https://user-images.githubusercontent.com/15319947/173512022-54ed085a-a088-4a9f-a44c-00ca9174b3bd.png)

![image](https://user-images.githubusercontent.com/15319947/173511771-0b79b320-3a7b-4461-87cc-8cc1f01c5bd9.png)

**Comment by enisn** [comment]
Can you check [Setup Environment Steps](https://docs.abp.io/en/commercial/latest/getting-started-setup-environment?UI=MVC&DB=EF&Tiered=No)?

It seems you missed node & yarn steps.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/173515512-f200b762-d2a6-4d3a-b204-40fbc3ebdea7.png)


See https://github.com/npm/cli/issues/4980#issuecomment-1145524555

**Comment by enisn** [comment]
You should run `abp install-libs` after successfull installation in your project folder to restore client-packages before running your project.

**Comment by xiaoyc** [comment]
It was solved by running the below commands .

Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
npm install -g npm-windows-upgrade
npm-windows-upgrade

Thanks all .
