### ISSUE TITLE
Auto generated repository giving strange behaviour with IQueryable

### ISSUE THREAD

**Issue by ARGibson** [abpframework/abp#1300]
I must be missing something here but I can't see it. I am using ABP 17.0, EF Core and AutoFac in a console application. I only need to read data from the database and am not using an Aggregate Root so I have my entity:

```csharp
[Table("Info")]
public class Info : Entity<int>
{
    public string FileId { get; set; }
    // ... Other fields
}
```

My context

```csharp
[ConnectionStringName(("SomeConnectionString"))]
public class SomeContext: AbpDbContext<SomeContext>
{
    public DbSet<Info> Info { get; set; }
    
    public SomeContext(DbContextOptions<SomeContext> options) : base(options)
    {
    }
}
```

And then in my service I am using the repository and ultimately I want to query against it not just find by ID. However for the purposes of this demonstration I am just fetching by ID to highlight my issue. 

```csharp
public class SomeService: ApplicationService
{
    private readonly IReadOnlyRepository<Info, int> repository;

    public SomeService(IReadOnlyRepository<Info, int> repository)
    {
        this.repository = repository;
    }
    
    public Info GetExperimentFile(string fileId)
    {
        // Works
        var exp1 = repository.Get(1);

        // Fails with ObjectDisposedException on DbContext
        var exp2 = repository.FirstOrDefault(f => f.Id == 1);

        // Fails with ObjectDisposedException on DbContext
        var exp3 = repository.WithDetails().FirstOrDefault(f => f.Id == 1); 

        // Fails with ObjectDisposedException on DbContext
        var exp4 = repository.AsQueryable().Single(f => f.Id == 1); 

        return exp1;
    }
}
```
Get and Find work just fine, they return the record. However as soon as I try to use LINQ against the repository I get a `ObjectDisposedException` from the DbContext. 

To be clear my goal is to query non-ID fields so Get and Find methods are not an option. I know I must be missing something but have spent a number of hours now trying to figure it out, even looking through the ABP source code to see what the EF Repository does and I can't see why Get and Find work but querying does not.

Any help would be greatly appreciated.

**Comment by maliming** [comment]
hi @ARGibson 
Try changing `GetExperimentFile` to a `virtual `method?

`public virtual  Info GetExperimentFile(string fileId)`

**Comment by ARGibson** [comment]
Now I feel stupid, yep, that fixed it, thank you :)
