### ISSUE TITLE
OpenIddict Template Tests

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#13005]
It is already integrated in https://github.com/abpframework/abp/issues/12601

- [x] Console test application (@enisn)
- [x] Single-layer (@gizemmutukurt)
- [x] Tiered & Non-tiered MVC (@gizemmutukurt)
- [x] Tiered & Non-tiered Blazor WASM (@enisn)
- [x] Tiered & Non-tiered Blazor Server (@gterdem)
- [x] Angular (with code and resource owner flows) with & without separate identityserver (@gterdem)

Test login and logout flows.

**Comment by gterdem** [comment]
Angular logout error:

![angular-logout-error](https://user-images.githubusercontent.com/25867/174121651-71676593-cf0f-4520-a5ef-4274d484b798.png)

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/174203688-fe517aee-340c-433e-9ace-c2dd91a5ee0f.png)

I will handle this.

**Comment by enisn** [comment]
**Console test application** and **Tiered & Non-tiered Blazor WASM** work well ✅

**Comment by gterdem** [comment]
Thank you.
Closing the issue.
