### ISSUE TITLE
ABP CLI - List available templates to be created

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#13008]
Currently, users should check the documentation to see the available template names.
Implement the parameter `list-templates` so that users can easily see all available templates to create.
For the users who are signed in as commercial, you need to include the PRO templates as well.
Templates are at https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/Templates

Documentation links:
- Free templates: https://docs.abp.io/en/abp/6.0/Startup-Templates
- Commercial templates : https://docs.abp.io/en/commercial/latest/startup-templates/index

---

See the Microsoft's template list feature: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new-list
![image](https://user-images.githubusercontent.com/9526587/173777577-c919fe2b-4c55-4061-9aeb-4921fea8f073.png)

---

The final look of the command should be as below
![image](https://user-images.githubusercontent.com/9526587/173780845-e3b1002a-b12a-437e-bc3e-ad25a83fde81.png)

**Comment by leonkosak** [comment]
@ebicoglu where is module-pro template?
