### ISSUE TITLE
Howto use custom templates ? Please add a documentation

### ISSUE THREAD

**Issue by barnybadzoo** [abpframework/abp#13004]
**ABP Framework 5.2.2**.

If i currently use the abp new parameter the standard-template (pro) and microservice-template-pro a used.
In your documentation is mentioned that a custom template can be used.

Please provide a documentation howto adopt a standard-template-pro / microservice-template-pro  and generate a custom template from it.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/2948
