### ISSUE TITLE
Angular Reactive Form Min/Max Validation

### ISSUE THREAD

**Issue by eneskoroglu** [abpframework/abp#13006]
* Your **ABP Framework version**. 5.2.1
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: Angular
* Your database provider(EF Core/MongoDB): EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

We are having same problem with [this bug report](https://support.abp.io/QA/Questions/2156/Angular-Reactive-Form-MinMax-Validation).
Can you please share created issue link (from @bnymncoskuner), or what is the last situation?

**Comment by berkansasmaz** [comment]
Can you check the latest situation @mahmut-gundogdu?
