### ISSUE TITLE
Commercial Suite - Generator Removed digits from class names

### ISSUE THREAD

**Issue by johnhbarrett** [abpframework/abp#13007]
v5.2.2, v5.3.0
If a Class has a property with a digit in it, then the digit get removed by the code generator.  
This should not happed.  Property Names with digits _within_ the name are legitimate.

screen shot from GitHib desktop showing properties with digits being incorrectly generated (ie removing the digits) after they had been fixed already.

![image](https://user-images.githubusercontent.com/106383851/173764304-99bc3966-afe2-4000-9c84-16ffc77975f3.png)

Shows CRUS generator and properties
![image](https://user-images.githubusercontent.com/106383851/173763674-8f208d54-f601-4aa7-9024-d03e298631b6.png)

**Comment by EngincanV** [comment]
Hi, please ask your questions about ABP Commercial on the [support.abp.io](https://support.abp.io/) website.
