### ISSUE TITLE
[Commercial] LeptonX Left Menu doesn't scroll when expanding menu items

### ISSUE THREAD

**Issue by hellorms** [abpframework/abp#13023]
* Your **ABP Framework version** : 5.3.0 Commercial
* Your **User Interface** type: MVC - LeptonX Theme 1.0.0-beta.2
* Microsoft Edge Version 102.0.1245.41 (Official build) (64-bit)
* Your database provider: EF Core

When expanding the left side menu items the menu doesn't allow user to scroll to hidden menu items.

![image](https://user-images.githubusercontent.com/93287086/174050316-747818dc-f906-4dcd-b224-721f34b33006.png)

**Comment by ismcagdas** [comment]
@demirmusa @enisn could you test this on MVC template together ? We just released beta3 for LeptonX, you can use that version.

**Comment by enisn** [comment]
Reproduced with LeptonX beta.3 for each UI type. It seems it's a core styling issue independent of UI type.
@muhammedaltug

**Comment by enisn** [comment]
This issue has been resolved and will be shipped in next leptonx release
