### ISSUE TITLE
[Commercial] LeptonX Login Page missing Tenant Selection

### ISSUE THREAD

**Issue by hellorms** [abpframework/abp#13022]
Your **ABP Framework version: 5.3.0
Your **User Interface** type: MVC
Your database provider: EF Core

1. The Login Page doesn't allow the user to select the Tenant
2. Also, there's no option to select the Language

![image](https://user-images.githubusercontent.com/93287086/174047870-756f239c-3b3c-4153-af3d-193156e2cf2a.png)

**Comment by ismcagdas** [comment]
@hellorms this is implemented and we just released beta3 for LeptonX, could you try with that version ?

**Comment by enisn** [comment]
It has been added with beta.3. So, I'm closing this issue. Try it with the new version and feel free to re-open this issue if your problem continues.
