### ISSUE TITLE
[Commercial] LeptonX Language selection suggestion

### ISSUE THREAD

**Issue by hellorms** [abpframework/abp#13024]
* Your **ABP Framework version** : 5.3.0
* Your **User Interface** type: MVC LeptonX theme beta-2
* Your database provider: EF Core

The LeptonX theme looks great. This is just a suggestion not an issue.

The languages drop down selector have the culture code shown e.g. **Espanol / ES** which is ok for developers but doesn't really mean anything to end users. For example, I showed this to a couple of of users and they didn't understand what **ES** meant, so it might be better to just show **Espanol** ?

Also, for example, the right sidebar shows **ES** which also doesn't mean anything to most users. Would it not be better to display the flag here?

Just a suggestion :-)

![image](https://user-images.githubusercontent.com/93287086/174055663-c8ac9697-1ac1-45aa-bcb6-760db4b397d6.png)

**Comment by ismcagdas** [comment]
@hellorms thank you for your suggestion. Removing the flag icons was a rough decision and we will not add it back at least for now :). We may reconsider it in the future.

By the way, thank you for trying LeptonX and providing valuable feedbacks 🙂
