### ISSUE TITLE
Automatically add roles when using external login

### ISSUE THREAD

**Issue by ChengYen-Tang** [abpframework/abp#13030]
I have a requirement, when I login using AD or LDAP, I want to sync external user groups as roles.
I have completed a prototype version by copying the ExternalLoginProviderBase and modifying some parts.
Maybe I can open PR, then discuss and optimize?

**Comment by berkansasmaz** [comment]
@maliming and @hikalkan 
What do you think about this?

**Comment by maliming** [comment]
hi

Let's leave this to the developer. Thanks @ChengYen-Tang

**Comment by ChengYen-Tang** [comment]
Hi @maliming ,

You mean abp team? abp user?
Also, I found that the official documentation doesn't seem to mention external login.
I spent a long time to find the ExternalLoginProviderBase in the github issue.
