### ISSUE TITLE
Domain Drive Design - How to treat consume external API as bussiness logic

### ISSUE THREAD

**Issue by yangl1n** [abpframework/abp#13032]
# Question
Hi, we have already created external APIs and my web app which use abp framework with razor page need to consume these external API.I currently write a big class which contains subclasses and send http request to fetch these external datas in UI layer. And in the future, there will be more datas coming from external system. And need to perform some operation via external API also(add calendar event...).
And when we are considering DDD,  I want to ask where should I put these codes. In application layer or in UI layer?How can I design it better. 
I read the book that introduce DDD in abp, it says bussiness logic are splited into domain layer and application layer. I think external data and its operations is also part of business logic. So there is a better design, right?

**Comment by gterdem** [comment]
It depends;

- If you will use the external service to combine with your application service dtos to show some view data, add external API to the `Web` layer. This will make your **presentation layer dependent on external service.**
- If you want to use the external service in your application logic and call external service in application services, then  add external API to the `Application` layer. This will make your **application and presentation layers dependent on external service.**
- If you want to use the external service in your domain logic and call external services in the domain services, then add external API to the `Domain` layer.  This will make your **domain, application, and presentation layers dependent on external service.**

You need to decide the dependency level for your application to an external service.

**Comment by zhutoutou** [comment]
> It depends;
> 
> * If you will use the external service to combine with your application service dtos to show some view data, add external API to the `Web` layer. This will make your **presentation layer dependent on external service.**
> * If you want to use the external service in your application logic and call external service in application services, then  add external API to the `Application` layer. This will make your **application and presentation layers dependent on external service.**
> * If you want to use the external service in your domain logic and call external services in the domain services, then add external API to the `Domain` layer.  This will make your **domain, application, and presentation layers dependent on external service.**
> 
> You need to decide the dependency level for your application to an external service.

I agree with you. we should distinct that which logic type the external service was be referenced. But I have another problem. If the domain logic relates to external service, I should implement it in domain layer or only define interface and implement it in infrastructure layer? Such like a http implement.
