### ISSUE TITLE
Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'!

### ISSUE THREAD

**Issue by amiramirifar2** [abpframework/abp#13046]
raise warning on `abp install-libs`  when Nodejs version is 16.x
NPM is not installed, visit https://nodejs.org/en/download/ and install NPM

**Comment by realLiangshiwei** [comment]
What is the output when you run `npm -v` command?

**Comment by xiaoyc** [comment]
refer to #12995  ,  I also met this error before .
