### ISSUE TITLE
Cannot find AccountLogout API

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1304]
![image](https://user-images.githubusercontent.com/30018771/59706030-2ba89780-9232-11e9-967a-ee73f1f6980e.png)

**Comment by gdlcf88** [comment]
I found /account/logout, but it is hard to use in swagger, I think.

**Comment by maliming** [comment]
Please elaborate on your situation and share some code.

Otherwise it is difficult to understand.

**Comment by gdlcf88** [comment]
It is a situation built from abp.io/Templates, and now it has these projects: Web, Application, Domain, Application Contracts and Domain Shared.
I didn't edit the controller, it's original.

**Comment by maliming** [comment]
@ebicoglu What do you think?

https://github.com/abpframework/abp/blob/6c024d6f7561a5fe6d97300334a8079d29970192/modules/account/src/Volo.Abp.Account.Web/Areas/Account/Controllers/LogoutController.cs#L19-L26

**Comment by gdlcf88** [comment]
In new patch of Abp vNext, we adopted ids4, dont care about this anymore.

**Comment by johnnba** [comment]
@gdlcf88 @maliming  so is there any possible to use the existing api such as /account/logout that can be called freely by any clien via the http protocol ? sincerely thanks.
