### ISSUE TITLE
ABP 5.3 (angular) LeptonX-lite issue

### ISSUE THREAD

**Issue by dominiclapointe** [abpframework/abp#13040]
ABP:          5.3 (community)
UI:             Angular
Tiered:       Yes

Hi all,

Ive just created a new project and migrate to leptonX theme. The theme does shows up but there is 4 bugs so far:
1. The z-index of the ngb-modal-backdrop.modal-backdrop.show.fade is too high, it does come over the modal when creating tenant or other creation popup. Ive managed to fix it with the current CSS in style.css
```
body > ngb-modal-backdrop.modal-backdrop.show.fade {
  z-index: 1050 !important;
}
```
2. When you open the app, the Administration button is shown, even if not logged in
<img width="1865" alt="image" src="https://user-images.githubusercontent.com/47004797/174389123-236973a2-4202-44c5-a30f-5c14b24cdedd.png">

3. The close button of the modal doesnt shows up
<img width="382" alt="image" src="https://user-images.githubusercontent.com/47004797/174389415-e3f2d92b-8e93-4cad-b7b5-ae475ab06f39.png">

4. When on mobile view, the 2 buttons of the tenant page are missing some margin / padding
<img width="492" alt="image" src="https://user-images.githubusercontent.com/47004797/174389654-c3b54490-fbe9-43d9-8ce7-10850a2190e2.png">

5. Home menu stays always highlighted, even when we are on a different route 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/47004797/174414891-919f6d5c-ad0f-44e1-b963-60b59f2c24cd.png">

Thank you

**Comment by joernz** [comment]
You might be using the alpha version? 
I don't see 2, 3 and 5 anymore with beta2 version (@abp/ng.theme.lepton-x@preview)

follow the new [document](https://docs.abp.io/en/abp/latest/Themes/LeptonXLite/angular)
Could you please check if you are able to change the logo and brand color with this new version? (`:root {}`) [I can't somehow](https://github.com/abpframework/abp/issues/13016)

**Comment by ismcagdas** [comment]
Thank you @joernz 
@dominiclapointe we just released beta3 verison, could you try with that one and share the final results ?
