### ISSUE TITLE
Fix Null Exception Problem on Minio Blog Provider

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#13052]
Related with https://support.abp.io/QA/Questions/3267/Minio-----------------SystemNullReferenceException--%27Object-reference-not-set-to-an-instance-of-an-object%27

**Comment by EngincanV** [comment]
It seems the problem is related to not configuring the `MinioBlobProviderConfiguration`, so I close the issue.

**Comment by VivienMAN** [comment]
@EngincanV  Can you recheck the issue, I think there is a problem

**Comment by EngincanV** [comment]
> @EngincanV Can you recheck the issue, I think there is a problem

Please see the https://github.com/abpframework/abp/pull/13054
