### ISSUE TITLE
Revision to Startup Template Docs

### ISSUE THREAD

**Issue by omer-repo** [abpframework/abp#13057]
There should be some revisions to the documents of Startup Template to clear up some possible confusions. (https://docs.abp.io/en/abp/latest/Startup-Templates/Application)

1) Under "Pre-requirements", it says: 
> The applications use Redis as a distributed cache. So, you need to have Redis installed & running.
* I created some applications but I think it is not required to install Redis in monolith solutions.

2) Under "How to Run?", 
> First, run the .IdentityServer since other applications depend on it.
* It points to run .IdentityServer firstly. But CLI doesn't generate .IdentitityServer project seperately as default.  (I tried with angular, blazor and web templates)

3) Blazor-server UI option is missing under "Specify the UI Framework" subject.
![Specify the UI Framework](https://i.imgur.com/rWdQr1I.png)

**Comment by EngincanV** [comment]
Hi @omer-repo, thanks for your suggestions. I will update the documentation.

**Comment by EngincanV** [comment]
> 1\. Under "Pre-requirements", it says:
> The applications use Redis as a distributed cache. So, you need to have Redis installed & running.

> I created some applications but I think it is not required to install Redis in monolith solutions.

The application startup template comes with Redis configured and Redis should be up and running to speed up the application.

> 2\. Under "How to Run?",
> 
> > First, run the .IdentityServer since other applications depend on it.
> 
> * It points to run .IdentityServer firstly. But CLI doesn't generate .IdentitityServer project seperately as default.  (I tried with angular, blazor and web templates)

This section is under the **Tiered Structure** section, so if you create an application as tiered, you need to run them in the given order.
