### ISSUE TITLE
app.UseMultiTenancy()  Tips: An exception was thrown while activating  Volo.Abp.AutoMapper.MapperAccessor 

### ISSUE THREAD

**Issue by qq8311065** [abpframework/abp#13055]
When I use multi tenant middleware, the following errors occur

![image](https://user-images.githubusercontent.com/40285933/174570313-d992384f-ef9b-461a-b93e-b26d389825e4.png)

An error has occurred

"An exception was thrown while activating OLD.Web.Infrastructure.MultiTenancy.CustomizeMultiTenancyMiddleware -> Volo.Abp.MultiTenancy.TenantConfigurationProvider -> Volo.Abp.TenantManagement.TenantStore -> Volo.Abp.ObjectMapping.DefaultObjectMapper`1[[Volo.Abp.TenantManagement.AbpTenantManagementDomainModule, Volo.Abp.TenantManagement.Domain, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.AutoMapper.AutoMapperAutoObjectMappingProvider`1[[Volo.Abp.TenantManagement.AbpTenantManagementDomainModule, Volo.Abp.TenantManagement.Domain, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null]] -> λ:Volo.Abp.AutoMapper.IMapperAccessor -> λ:Volo.Abp.AutoMapper.MapperAccessor"

Finally, it was found that MapperAccessor acquisition failed

Inadvertently annotating a line of code can make the program run normally
![image](https://user-images.githubusercontent.com/40285933/174570631-ec3ffca8-efcf-495c-a9a4-5b4d20247708.png)
I want to know why, because this code is useful to me, and I don't want to annotating

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by qq8311065** [comment]
> * 您的**ABP 框架版本**。
> * **重现**问题所需的步骤。

version:5.3.0
I ran it directly and the error occurred
