### ISSUE TITLE
ABP Suite: Inconsistent naming of navigation properties

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#13061]
Your ABP Framework version: 5.3.0 (Stable)
Your User Interface: Blazor-Server
Your database provider(EF Core/MongoDB): EF Core

**To reproduce:**
1. Use ABP Suite to generate entities
2. Create 2 navigation properties to the same entity
3. Go to "Advanced" and change "Property Name" in section "3 Others" to a meaningful name
4. Save and generate the code

**My expectation:**
In all classes where this property is used, my chosen name will be used as property name.

**Current result:**
The properties with the foreign key (Guid) are generated correctly with my specified name. But in the classes with postfix "...WithNavigationProperties" the entity name is used and numbered. It would be desirable that the chosen name would be used there as well (simply without postfix "Id").

**Example:**
The class "Book.cs" should have two navigation properties to "Author.cs": MainAuthorId & CoAuthorId

Result in BookDto.cs, Book.cs, ...
`
public Guid? MainAuthorId { get; set; }
public Guid? CoAuthorId { get; set; }
`

Result in BookWithNavigationPropertiesDto.cs / BookWithNavigationProperties.cs:
`
        public Author Author { get; set; }
        public Author Author1 { get; set; }
`

I hope my concern has been explained in an understandable way. 

Thanks,
Adrian

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io/
