### ISSUE TITLE
Will there be a default theme/template for paid version?

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#1306]
I understand how to create my own layout and theme for abp.io, but before I get started on that, I wanted to know if there will be a theme/template layout included in the paid version?  Similar to the aspnetzero dashboard layouts.

**Comment by ismcagdas** [comment]
@djlaney3 yes, we will provide a bootstrap 4 based theme (which is developed by our company) with the paid version.

**Comment by djlaney3** [comment]
Will this be available in the first release, or will it come later?

**Comment by yekalkan** [comment]
Will be available in the first release.
