### ISSUE TITLE
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'! for WebAss app

### ISSUE THREAD

**Issue by P9avel** [abpframework/abp#13066]
Hi, i am created new app on site https://abp.io/ but when running i am get error
![image](https://user-images.githubusercontent.com/95086762/174666870-040cbc81-0dc2-4e8c-8a14-b37983f916cf.png)

**Comment by P9avel** [comment]
Here full project
[Uploading Test (1).zip…]()

**Comment by P9avel** [comment]
[Test (1).zip](https://github.com/abpframework/abp/files/8943201/Test.1.zip)

**Comment by maliming** [comment]
Run `abp install-libs` command on your project folder.

**Comment by P9avel** [comment]
Not works for me. Wrote Not install npm, but npm works on computer. please look image

![image](https://user-images.githubusercontent.com/95086762/174738139-56b7f157-50e4-4d9b-8923-ce473c2b55db.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/12995#issuecomment-1154802030

**Comment by P9avel** [comment]
Many thx, all works now!

**Comment by anurag-044** [comment]
I use angular UI and I face the same problem then I use ABP install-libs command but it shows that that command is doesn't exist.
What should I do now?
![Screenshot 2022-09-08 102600](https://user-images.githubusercontent.com/55396959/189037678-85326069-a58f-40c2-a2b6-d3de69f64d25.png)

**Comment by ALVSoft** [comment]
> Run `abp install-libs` command on your project folder.

Work for me. Thanks

**Comment by nachocruel** [comment]
if the comando above: abp  install-libs is not working. Add a file .yarnrc.yml in the project Acme.BookStore.HttpApi.Host with the content: nodeLinker: node-modules
