### ISSUE TITLE
Blazorise error

### ISSUE THREAD

**Issue by BogdanJak** [abpframework/abp#13067]
ABP Framework version - 5.3.0.
Blazor Server, Ef Core, 

After updating all nuget packages, I am getting an error like below

![image](https://user-images.githubusercontent.com/54505464/174670263-9c36e4f7-15f4-4e89-a3ce-e4ddcfe549bd.png)

**Comment by realLiangshiwei** [comment]
Update all `Blazorise.*` packages to 1.0.4
