### ISSUE TITLE
layout: eLayoutType.empty content empty 

### ISSUE THREAD

**Issue by DreamlessRaw** [abpframework/abp#13077]
ABP Vnext 5.2.1
Angular
EF Core

![image](https://user-images.githubusercontent.com/47837339/174761451-850cb04f-7a06-4ffa-995e-ce1ae25c7075.png)
![image](https://user-images.githubusercontent.com/47837339/174761914-3754d53e-f98b-4dae-af6a-9692d6726ec1.png)
![image](https://user-images.githubusercontent.com/47837339/174761945-9d7cdc4a-9cc0-4e5e-ab59-f85abc35ab0e.png)

Why not show the content

**Comment by DreamlessRaw** [comment]
I found out because @abp/ng.theme.lepton-x

**Comment by zsyy94** [comment]
Hello, I also encountered the same problem, how to solve it
