### ISSUE TITLE
How to make error messages wrap?

### ISSUE THREAD

**Issue by roc916** [abpframework/abp#13079]
ABP Framework version: 5.3.0
User Interface: Mvc
Error messages are separated by `, `, how to replace it with new line?

Screenshot:
![image](https://user-images.githubusercontent.com/12685126/174792690-0a85fa5f-a0ef-4f1d-b8c2-558dbb4fc6e2.png)

**Comment by maliming** [comment]
This is hard-code now. 
https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpIdentityResultException.cs#L22
