### ISSUE TITLE
ABP Suite: Duplication of usings in ...WithNavigationProperty classes

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#13076]
ABP Framework version: 5.3.0 (Stable)
ABP Suite version: 5.3.0
User Interface: Blazor-Server
Database provider (EF Core/MongoDB): EF Core

**To reproduce:**

If multiple navigation properties are created via the ABP Suite that reference the same entity, then the "using" will be added to that entity namespace multiple times.

Example: I create two navigation properties on the entity "Person" to the entity "Item" (GenderItemId, FunctionItemId). After that I have in PersonWithNavigationProperty.cs & PersonWithNavigationPropertyDto.cs a double "using" on MySolution.Items.

Of course, this just generates a warning and can be easily fixed. But it would be better if there would be a check if a using already exists.

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io/

**Comment by ageiter** [comment]
Why do I have to spend a paid support request for this bug report if I don't have a question, but just wanted to report this bug so you can improve the product?

**Comment by maliming** [comment]
We will refund your question credits if it is a bug.
