### ISSUE TITLE
[Commercial]Style problem  in DataTeble  RTL

### ISSUE THREAD

**Issue by yasinhallak** [abpframework/abp#13088]
ABP Framework version: v5.3.0
UI type: MVC
Tiered (MVC) or Identity Server Separated (Angular): no
DB provider: EF Core

hi everyone .
there is bugs in DataTeble style  RTL 

![image](https://user-images.githubusercontent.com/41200731/175196723-d6a91c8f-8024-46e1-9e8b-1dff15fa732c.png)

**Comment by naderjavid** [comment]
just add this rule to your global_style
.rtl table.dataTable thead th, table.dataTable thead td, table.dataTable tfoot th, table.dataTable tfoot td {
    text-align: right;
}
