### ISSUE TITLE
style problem in leptonX MVC for rtl languages

### ISSUE THREAD

**Issue by naderjavid** [abpframework/abp#13087]
ABP Framework version: 5.3.0 preview
User Interface: MVC
EF Core
reproduce: 
1. bootstrap-dim.css not loaded in rtl langauges
![bug](https://user-images.githubusercontent.com/30950912/175115421-2ebdd04f-a9b5-45db-a45a-f81ada3af97a.jpg)
2. need to add this rules for rtl languages
.rtl .lpx-content-container {
    margin-left: 0;
    margin-right: 280px
}

.rtl .lpx-topbar {
    border-radius: 0 16px 0 0;
}
.rtl .lpx-brand-logo {
    background-position: right 0px !important;
}
.rtl .lpx-sidebar .lpx-logo-container .menu-collapse-icon {
    left: 30px;
    right: unset;
}
.rtl .lpx-sidebar-container {
    overflow-y: unset;
}
.rtl div.dataTables_wrapper div.dataTables_filter input {
    margin-right: 0.5em;
    margin-left: unset;
}
@media only screen and (min-width: 1200px) {
    .rtl #lpx-wrapper.hover-trigger .lpx-content-container {
        margin-right: 72px;
        margin-left: unset;
    }
}
.rtl .lpx-topbar-content {
    margin-left: 10px;
    margin-right: unset;
}
.rtl .dataTables_wrapper .dataTables_length select {
    padding: 0.375rem 0.75rem 0.375rem 3rem !important;
}
.rtl div.dataTables_wrapper div.dataTables_filter {
    text-align: left;
}

**Comment by naderjavid** [comment]
add this rules too, please

.rtl div.dataTables_wrapper div.dataTables_filter input {
    margin-right: 0.5em;
    margin-left: unset;
}
@media only screen and (min-width: 1200px) {
    .rtl #lpx-wrapper.hover-trigger .lpx-content-container {
        margin-right: 72px;
        margin-left: unset;
    }
}
.rtl .lpx-topbar-content {
    margin-left: 10px;
    margin-right: unset;
}
.rtl .dataTables_wrapper .dataTables_length select {
    padding: 0.375rem 0.75rem 0.375rem 3rem !important;
}
.rtl div.dataTables_wrapper div.dataTables_filter {
    text-align: left;
}
.rtl .lpx-nav-menu .lpx-menu-item-link .dd-icon {
    left: 24px;
    right: unset;
}
.rtl .lpx-nav-menu .lpx-inner-menu-item .lpx-menu-item-icon {
    margin-left: 8px;
    margin-right: unset;
}
.rtl .lpx-nav-menu .lpx-inner-menu-item .lpx-menu-item-link {
    padding-right: 60px;
    padding-left: unset;
}
.rtl .lpx-nav-menu .lpx-inner-menu .lpx-inner-menu .lpx-menu-item-link {
    padding-right: 84px;
    padding-left: unset;
}

**Comment by naderjavid** [comment]
.rtl .text-end {
    text-align: left !important;
}
.rtl .modal-header .btn-close {
    margin: -0.75rem auto -0.75rem -0.75rem;
}
.rtl .form-select {
    background-position: left 0.75rem center;
}

**Comment by realLiangshiwei** [comment]
Hi,
> LeptonX has some problems with RTL and we are aware of that. We are planning to release 1.0 version of LeptonX with RTL support. We are tracking the issue internally, but I will also keep this issue open and inform you once LeptonX RTL support is done and released.

Please follow: https://github.com/abpframework/abp/issues/12979
