### ISSUE TITLE
Failed to load API definition when ABP deployed to IIS virtual directory.

### ISSUE THREAD

**Issue by RobersonLuo** [abpframework/abp#13084]
### Issue description:
* First, I created an Angular App using ABP CLI (abp new  XXX) and generated the database and run the XXX app and everything is ok.
* Second, I deployed the API project "XXX.HttpApi.Host" to a remote Server ( IP 23.452.999.178) IIS  virtual directory (**demo**) and the website alias is '**services**'.
So, the API website url is changed to this: http://23.452.999.178/demo/services
* Third, access the website http://23.452.999.178/demo/services from the browser,  and it will swith to http://23.452.999.178/demo/services/swagger/index.html, but met error below:

![image](https://user-images.githubusercontent.com/7013492/174975082-988ddc00-afb3-43c8-84a8-a35621ff7567.png)

*  But access the API json URL is ok:

![image](https://user-images.githubusercontent.com/7013492/174978222-c98e8944-f07f-4133-ab8c-f6901a67cfa5.png)

### Question
* How to change the API url from  **/swagger/v1/swagger.json** to **/demo/services/swagger/v1/swagger.json** as shown in the image above?  
Because  I can't find the **swagger index.html**!  ( I think this is the solution.)
But in **asp.net boilerplate**,  I can find this file and change there (wwwroot/swagger/ui/index.html)!

![image](https://user-images.githubusercontent.com/7013492/174980394-519b5717-39fa-421b-8614-ddd2ab96ff8c.png)

#### Note:
* I had already updated the datebase url in tables ( IdentityServerClientRedirectUris、IdentityServerClientCorsOrigins、IdentityServerClientPostLogoutRedirectUris) with  http://23.452.999.178/demo/services

Please help and any detail info will be appreciated!
Thansk a lot.

**Comment by realLiangshiwei** [comment]
Replace `c.SwaggerEndpoint("/swagger/v1/swagger.json", ....);` with `c.SwaggerEndpoint("swagger/v1/swagger.json", ....);`

**Comment by RobersonLuo** [comment]
> Replace `c.SwaggerEndpoint("/swagger/v1/swagger.json", ....);` with `c.SwaggerEndpoint("swagger/v1/swagger.json", ....);`

I had already tried this method, but it's hard-coded, not flex,  can't meet my real case . 
I want to **build once, and deploy it to many place, just change the url (virtual directory)**.
Thanks very much.
