### ISSUE TITLE
`serializeFormToObject` function should serialize empty input to `null`

### ISSUE THREAD

**Issue by roc916** [abpframework/abp#13085]
**ABP Framework version: 5.3.0**
**User Interface: Mvc** 

Looking at the screenshot, if the `phoneNumber` is an empty string, data validation(EmailAddressAttribute, PhoneAttribute...) will fail.
If the value of the `phoneNumber` is null, it will work fine.

Screenshots:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/12685126/175044054-1ad9fea8-804b-4467-a7e0-9b8af0f2a0d2.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/12685126/175045992-290b9b66-87ad-4ebc-af50-67db5fff732e.png">

<img width="750" alt="image" src="https://user-images.githubusercontent.com/12685126/175047038-480340ed-b0d0-4002-a1b0-0edb16ad071e.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/12685126/175047669-ef9e3db3-704b-45d2-82aa-80543df87e11.png">

**Comment by maliming** [comment]
You can change its logic yourself. If we change it will break the apps.
