### ISSUE TITLE
Problems in creating new project with Get Started page

### ISSUE THREAD

**Issue by omer-repo** [abpframework/abp#13086]
I created a new Blazor application with these configurations in GetStarted page (https://abp.io/get-started)

![Get Started](https://i.imgur.com/cxbkkHm.png)

Although I didn't select "Separate Identity Server" option, it created .IdentityServer project seperately.
![Project.zip](https://i.imgur.com/rglkXcX.png)

Also it didn't generate libs folder in .Host project. I think new Abp Cli generates it, but GetStarted page doesn't.
![Host project](https://i.imgur.com/h6pFnjc.png)

**Comment by roc916** [comment]
`Mvc` application also have the same problem.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/12685126/175049098-04076f87-ae37-47f8-9d6f-98f910211e1d.png">

**Comment by EngincanV** [comment]
Thanks for reporting these problems. I'll be working on it.

**Comment by roc916** [comment]
Looks like https://abp.io uses version `6.0` of `Volo.Abp.Cli.Core`...  🤣

**Comment by roc916** [comment]
<img width="989" alt="image" src="https://user-images.githubusercontent.com/12685126/175053033-c88ebd79-4602-44d9-8a78-01d8e810bad6.png">

**Comment by ebicoglu** [comment]
are you using nightly build of ABP CLI?

**Comment by roc916** [comment]
> are you using nightly build of ABP CLI?

Yes, https://abp.io/get-started have the same problem
