### ISSUE TITLE
In LeptonXLite Theme,under the CMS,cms pages throw InvalidOperationException

### ISSUE THREAD

**Issue by Joncyzx** [abpframework/abp#13091]
5.3.0
MVC
Ef Core
LeptonXLite

![image](https://user-images.githubusercontent.com/20852007/175231778-89b72756-7741-481b-bafe-d7b2a48da99c.png)
![image](https://user-images.githubusercontent.com/20852007/175231834-be48925a-9b3a-404a-8678-15b9cdde46c8.png)

**Comment by enisn** [comment]
Confirmed the issue. 

We'll make that section optional in LeptonX Theme

**Comment by enisn** [comment]
This problem has been solved and it'll be shipped in next release of LeptonX
