### ISSUE TITLE
[Commercial] LeptonX does not work well in RTL

### ISSUE THREAD

**Issue by yasinhallak** [abpframework/abp#13096]
there are a collection of bugs

**Comment by realLiangshiwei** [comment]
Hi,
> LeptonX has some problems with RTL and we are aware of that. We are planning to release 1.0 version of LeptonX with RTL support. We are tracking the issue internally, but I will also keep this issue open and inform you once LeptonX RTL support is done and released.

Please follow: https://github.com/abpframework/abp/issues/12979

**Comment by yasinhallak** [comment]
hi there ...
we need RTL leptonX  ...
when will solve this Issue ??
