### ISSUE TITLE
Alerts should be deleted if the user click dismiss or shown one time

### ISSUE THREAD

**Issue by gaojianzhuang** [abpframework/abp#13092]
### GitHub Issues
AlertManager.Alerts

If the alert show one time then the user refresh page, the alert information should not display again. Or if the user click the disimiss button, we should remove this alert from backend.

If you're creating a bug/problem report, please include followings:

* ABP 5.3.0.
* MVC
* EF Core

Currently, if the user refresh page, the alert message always display there.

**Comment by maliming** [comment]
>  if the user refresh page

In this case, the previous steps are repeated again. So it will be displayed again.

**Comment by gaojianzhuang** [comment]
> > if the user refresh page
> 
> In this case, the previous steps are repeated again. So it will be displayed again.

If the user submit the form but not redirect to another page, the refresh page will awalys display.

**Comment by maliming** [comment]
This is the browser's behavior.
