### ISSUE TITLE
how to Limit the number of selections in Auto-Complete Select？

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#13101]

**Comment by naderjavid** [comment]
Hi, you must do it like this
<select data-maximumSelectionLength="2"

**Comment by weiwxg** [comment]
> Hi, you must do it like this <select data-maximumSelectionLength="2"

Not work under v5.3

**Comment by naderjavid** [comment]
Sorry, you must change it to kebab case
<select data-maximum-selection-length="2"

**Comment by naderjavid** [comment]
https://select2.org/configuration/data-attributes

**Comment by weiwxg** [comment]
> Sorry, you must change it to kebab case <select data-maximum-selection-length="2"

thx!
