### ISSUE TITLE
Improve styling on AuthServer page for LeptonX-Lite Theme

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#13109]
We need to improve the styling of the homepage of the AuthServer page. If the theme is lepton-x lite, it seems as below.

![image](https://user-images.githubusercontent.com/43685404/175522164-048df787-ae39-44d7-977e-59b7d26529cb.png)

**Comment by hikalkan** [comment]
Also change the dataseeder (in the startup template) so it doesn't create the unrelated clients. For example, if we use angular, no need to create blazor clients.

**Comment by hikalkan** [comment]
@EngincanV you can get help from @armgnunlu on the design. But keep it simple. This page is probably will be changed by the company using it. It is designed for the initial development time. Also consider my previous note if possible.

**Comment by buntysaraswat** [comment]
> We need to improve the styling of the homepage of the AuthServer page. If the theme is lepton-x lite, it seems as below.
> 
> ![image](https://user-images.githubusercontent.com/43685404/175522164-048df787-ae39-44d7-977e-59b7d26529cb.png)

Does the current commercial 7.3.2 allow us to view the applications added or seeded in above dashboard?

**Comment by EngincanV** [comment]
> > We need to improve the styling of the homepage of the AuthServer page. If the theme is lepton-x lite, it seems as below.
> > ![image](https://user-images.githubusercontent.com/43685404/175522164-048df787-ae39-44d7-977e-59b7d26529cb.png)
> 
> Does the current commercial 7.3.2 allow us to view the applications added or seeded in above dashboard?

Yes, it is. You should select a "separate auth server" option while creating the template.

**Comment by buntysaraswat** [comment]
Hi @EngincanV , thanks for your reply, I created solution as suggested and realised that it just dashboard with URL, after log in, it doesn’t work like SSO and doesn’t redirect to apps as pre-authenticated.

after redirect you have to click on login on landed app?
