### ISSUE TITLE
UseQueryTrackingBehavior has no effect | Not able to update data

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#13110]
Documentation Ref: https://docs.abp.io/en/abp/latest/Entity-Framework-Core#abpdbcontextoptions

* Your **ABP Framework version**: 5.3
* Your database provider(EF Core/MongoDB): EF Core
* Exception message and **stack trace** if available (check the logs):
`The instance of entity type 'Setting' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.` for global
and
`No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.` for specific
* Steps needed to **reproduce** the problem:
1. Copy BookStore [example](https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore)
2. Add AuthorRepository_Tests to Acme.BookStore.EntityFrameworkCore.Tests
3. Follow documentation to disable tracking ( try global or context specific ( SettingManagementDbContext ), both doesnt work )
4. Run Test
5. See exception

SettingsRepository_Tests.cs:
```
using System;
using System.Threading.Tasks;
using Shouldly;
using Volo.Abp.SettingManagement;
using Xunit;

namespace Acme.BookStore.EntityFrameworkCore.Samples;

public sealed class AuthorRepository_Tests : BookStoreEntityFrameworkCoreTestBase
{
	private readonly ISettingRepository _settingRepository;

	public AuthorRepository_Tests()
	{
		_settingRepository = GetRequiredService<ISettingRepository>();
	}
	
	[Fact]
	public async Task Should_Not_Track()
	{
		const string name1 = "Settings1";
		const string name2 = "Settings2";
		const string value = "A";
	        
		await WithUnitOfWorkAsync( async () =>
		{
			// Arrange
			Guid settingId = Guid.NewGuid();
			Setting setting1 = new( settingId, name1, value );
			Setting setting2 = new( settingId, name2, value );
		        
			// Act
			await _settingRepository.InsertAsync( setting1, true );
			Setting resultSetting1 = await _settingRepository.GetAsync( settingId );
			await _settingRepository.UpdateAsync( setting2, true );
			Setting resultSetting2 = await _settingRepository.GetAsync( settingId );
		        
			// Assert
			resultSetting1.ShouldNotBeNull();
			resultSetting2.ShouldNotBeNull();
			resultSetting1.Name.ShouldBe( name1 );
			resultSetting2.Name.ShouldBe( name2 );
		} );
	}
}
```

Because the documentation is very unspecific, i tried to add it before `options.UseSqlServer`, after that and Pre- and PostConfigurationService to call the UseQueryTrackingBehavior function - it still tracks all objects.

Beside that, i found a related [question](https://support.abp.io/QA/Questions/1971/cannot-be-tracked-because-another-instance-with-the-same-key-value-for-%27Id%27-is-already-being-tracked-When-attaching-existing-entities-ensure-that-only-one-entity-instance-with-a-given-key-value-is-attached) where you mentioned to use .AsNoTracking() but not how to use it. 
Couldnt find a way to use it with IRepository ( or any specific Repository ) Insert, Update, Find, Get or GetList.

Tests are using sqlite (memory) as database provider - but even if you add `context.UseQueryTrackingBehavior( QueryTrackingBehavior.NoTracking );` after [UseSqlite](https://github.com/abpframework/abp-samples/blob/18759373c3a41a3e534437ef93d1fae9182d5952/BookStore-Blazor-EfCore/test/Acme.BookStore.EntityFrameworkCore.Tests/EntityFrameworkCore/BookStoreEntityFrameworkCoreTestModule.cs#L35) it has still no effect

**Comment by maliming** [comment]
hi

I will do some tests. Your questions credits is refunded.

**Comment by maliming** [comment]
Because of the design of EF Core, if you need to update the entity, please use the previously queried entity.

```cs
await _settingRepository.InsertAsync( setting1, true );
Setting resultSetting1 = await _settingRepository.GetAsync( settingId );
resultSetting1.property = newValue;
await _settingRepository.UpdateAsync( resultSetting1, true );
```

> you mentioned to use .AsNoTracking() but not how to use it.

You can use it as needed in your EF Core repository implementation. It only exists at the EF Core layer.

**Comment by puschie286** [comment]
thanks for pointing out. now the whole manager / dto concept makes sense ^^.

we tested to use readonly objects as entities ( ef core always return the same reference which can result in invalid states for this request / dbcontext lifecycle ) but looks like we have to stick to the "classic" flow.

**Comment by puschie286** [comment]
@maliming
we have still some unwanted behaviour.

If you change setting1 right after inserting and call GetAsync after that, you get the changed setting object not the original that was inserted into the database. ( which makes it impossible to discard changes or compare the original object with the changed one )

I thought UseQueryTrackingBehavior( NoTracking ) would fix that - do you have any idea how to discard entity changes ?

**Comment by puschie286** [comment]
never mind - test configuration has overwritten some options ( all UseXXX calls reset the DbContextOptions )
