### ISSUE TITLE
Custom theme support avatar

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#1311]
I can't add a avatar in the theme. How do I do it
![image](https://user-images.githubusercontent.com/10234503/59754806-05760c80-92b1-11e9-89c7-065fc1fc784a.png)

**Comment by hikalkan** [comment]
Can not help you with only this info. You should write more specific.

**Comment by sunedp** [comment]
I need to change the default avatar in the abp framework commercial version for the logged-in user from this image 
![image](https://user-images.githubusercontent.com/8393468/100609973-8f842a80-3317-11eb-8a7d-c68c965aa62f.png)

to this image:
![image](https://user-images.githubusercontent.com/8393468/100610253-091c1880-3318-11eb-851b-5fd135e9d908.png)

Can someone please help me and tell me where in the framework, in which file and how to do it? @hikalkan Can you perhaps assist me, please let me know if you need more information from my side. Much appreciated.

**Comment by maliming** [comment]
hi @sunedp  

Please create a question on https://support.abp.io/

**Comment by sunedp** [comment]
hi @maliming I tried to create this question on  https://support.abp.io/ but I can only log in and can not add a question there.
