### ISSUE TITLE
How to get edition features with Application Configuration Endpoint?

### ISSUE THREAD

**Issue by PioneerOfProgramming** [abpframework/abp#13125]
I implement edition features by adding editionId in the tenant table and following this documentation:
https://docs.abp.io/en/abp/latest/Features 
but when I add features to an edition I don't get it with /api/abp/application-configuration API as tenant features
Could you help me to deal with it?

**Comment by maliming** [comment]
hi

You can customise the endpoint response now.

https://github.com/abpframework/abp/pull/13100
