### ISSUE TITLE
Use Volo.Abp.Hangfire Module ERROR

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#1313]
JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API

**Comment by maliming** [comment]
Stack information and related code?

**Comment by Nokecy** [comment]
see https://github.com/Nokecy/HangfireTest.git  @maliming

**Comment by Nokecy** [comment]
![QQ截图20190620100524](https://user-images.githubusercontent.com/12318131/59813239-63ebcb00-9343-11e9-816b-3e787f51b9a3.jpg)

**Comment by Nokecy** [comment]
i get it!! 
```
PreConfigure<IGlobalConfiguration>(option =>
            {
                option.SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                   .UseSimpleAssemblyNameTypeSerializer()
                   .UseRecommendedSerializerSettings()
                   .UseSqlServerStorage(configuration.GetConnectionString("Default"));
            });
```

**Comment by maliming** [comment]
You may need to study it yourself before you have the documentation. 😊
