### ISSUE TITLE
Update VoloDocs standalone deployments (self-contained)

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#13144]
1- Update zip files here https://docs.abp.io/en/abp/latest/Apps/VoloDocs#download

> https://github.com/abpframework/abp/blob/dev/modules/docs/app/VoloDocs.Web/publish.bat

**Comment by skoc10** [comment]
C:\inetpub\wwwroot\apps_abp_io\VoloDocs

**Comment by EngincanV** [comment]
VoloDocs self-contained deployments are updated.
