### ISSUE TITLE
how to set request header while submit modal？

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#13177]
v5.3 MVC

**Comment by weiwxg** [comment]
```csharp
$.ajax({
    type: 'POST',
    url: _url,
    xhrFields: {
        responseType: "blob"
    },
    ...
})
```

For example, how to set the `xhrFields` required by the above code while `modal` submit?

**Comment by realLiangshiwei** [comment]
This has nothing to do with ABP

**Comment by weiwxg** [comment]
> This has nothing to do with ABP

This is about how to set extra params in `ModalManager` !!! Does this have anything to do with `ABP` ？？？

**Comment by realLiangshiwei** [comment]
You can get the form element to do anything you want.

https://docs.abp.io/en/abp/latest/UI/AspNetCore/Modals#functions

![image](https://user-images.githubusercontent.com/16813853/176569312-3df19a1b-eb51-4966-a71b-38887fbb4bb7.png)
