### ISSUE TITLE
Community Article: How to use ml.net in an ABP based application

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#13202]
We can create a sample application that shows how to use [ml.net](https://github.com/dotnet/machinelearning) in an ABP-based application. (Explain "Where is the right place for the machine learning code", "is it good to mix with the business code" etc.)

In the sample application we can use, one of the following topics:
- Sentiment Analysis
- Product Price Prediction
- Product Recommendations etc.

> Some ML.NET Samples: https://github.com/dotnet/machinelearning-samples

**Comment by recruitans** [comment]
wow. Waiting Impatiently.

**Comment by EngincanV** [comment]
Here are the articles:

* https://community.abp.io/posts/sentiment-analysis-within-abpbased-application-lbsfkoxq
* https://engincanv.github.io/machine-learning/sentiment-analysis/best-practises/2024/05/16/reusing-and-optimizing-machine-learning-models-in-dotnet.html
