### ISSUE TITLE
ABP Framework version 5.3 No K8S Chart for Blazor

### ISSUE THREAD

**Issue by tobimax** [abpframework/abp#13203]
**ABP Framework version** 5.3.1
**User Interface** Blazor Server
**Database Provider** EF Core & MongoDB

Create a new a project to 5.3.x using ABP suite

**Observed in etc\k8s**

No Blazor Server & Blazor (WASM) helm chart is created. 
No chart values are created for Blazor Server & Blazor (WASM) 

**Expected**

- Blazor Server & Blazor (WASM) helm chart is created along with Web & Angular.
- Chart values are created.

**Comment by maliming** [comment]
hi

Please create a question on https://support.abp.io/
