### ISSUE TITLE
MVC and Application Services

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1321]
If im developing a MVC website, should MVC Controllers/Pages call the domain services/repositories directly?  or should they only talk to Application Services?

**Comment by maliming** [comment]
Based on previous experience, the UI should interact with the application service and should not use domain services and repositories directly.

**Comment by yekalkan** [comment]
![image](https://user-images.githubusercontent.com/5793291/59826376-defeb280-933e-11e9-96b9-ff35d1c61d56.png)


https://abp.io/documents/abp/latest/Application-Services

**Comment by wocar** [comment]
Thank you
