### ISSUE TITLE
How to use different connection create each db  for XXXDbContext

### ISSUE THREAD

**Issue by Fisher-Joe** [abpframework/abp#1322]
```json
"Default": "...database=Saas_MainDb",
"AbpIdentityServer": "...database=Saas_AbpIdentityServerDb",
"AbpAuditLogging": "...database=Saas_AbpAuditLogDb",
"AbpPermissionManagement": "...database=Saas_AbpPermissionDb",
"AbpSettingManagement": "...database=Saas_AbpSettingDb",
"AbpTenantManagement": "...database=Saas_AbpTenantDb"
```
When I use different mysql connection to crate each db. I found only use 1 Db of Saas_MainDb

**Comment by maliming** [comment]
@hikalkan Do we need to add the `ConnectionStringName` attribute to the module's DbContext interface and class?

**Comment by Fisher-Joe** [comment]
It already exists, such as:
https://github.com/abpframework/abp/blob/0fc9238218fbfe10fff41c1ff5fb0f275f0cb2a3/modules/identityserver/src/Volo.Abp.IdentityServer.EntityFrameworkCore/Volo/Abp/IdentityServer/EntityFrameworkCore/IdentityServerDbContext.cs#L11

https://github.com/abpframework/abp/blob/0fc9238218fbfe10fff41c1ff5fb0f275f0cb2a3/modules/identityserver/src/Volo.Abp.IdentityServer.EntityFrameworkCore/Volo/Abp/IdentityServer/EntityFrameworkCore/IIdentityServerDbContext.cs#L11

The other is the same, there is already [ConnectionStringName(" XXX")]
Is it a bug? or need to config in  ConfigureServices(ServiceConfigurationContext context) at 
 SaasAppModule

**Comment by maliming** [comment]
Excuse me, I just read it wrong, I will check it now.

**Comment by maliming** [comment]
@Fisher-Joe

The code has no bugs. Do the above databases exist? And do they have corresponding tables?

**Comment by Fisher-Joe** [comment]
yes ,the database all exist. I run update-database then only Default connnection is add tables.

**Comment by maliming** [comment]
Try to perform migrations to other databases (update-database)

I guess there should be an error log in the application's log.

**Comment by Fisher-Joe** [comment]
I will do it later

**Comment by Fisher-Joe** [comment]
I re-created a ASP.NET Core Mvc Application project at https://abp.io/Templates.
add appsettings.json in xxx.EntityFrameworkCore.DbMigrations 
```json
{
  "ConnectionStrings": {
    //"Default": "Server=localhost;Database=Saas;Trusted_Connection=True;MultipleActiveResultSets=true"
    "Default": "Data Source=..\\Aiwosoft.Saas.Web\\App_Data\\Saas_MainDb.db;",

    "AbpIdentityServer": "..\\Aiwosoft.Saas.Web\\App_Data\\Saas_AbpIdentityServerDb.db",
    "AbpAuditLogging": "..\\Aiwosoft.Saas.Web\\App_Data\\Saas_AbpAuditLogDb.db",
    "AbpPermissionManagement": "..\\Aiwosoft.Saas.Web\\App_Data\\Saas_AbpPermissionDb.db",
    "AbpSettingManagement": "..\\Aiwosoft.Saas.Web\\App_Data\\Saas_AbpSettingDb.db",
    "AbpTenantManagement": "..\\Aiwosoft.Saas.Web\\App_Data\\Saas_AbpTenantDb.db"

  }
}
```
Use the SqLite.
```C#
 public class SaasMigrationsDbContextFactory : IDesignTimeDbContextFactory<SaasMigrationsDbContext>
    {
        public SaasMigrationsDbContext CreateDbContext(string[] args)
        {
            var configuration = BuildConfiguration();

            var builder = new DbContextOptionsBuilder<SaasMigrationsDbContext>()
                //.UseSqlServer(configuration.GetConnectionString("Default"));
                .UseSqlite(configuration.GetConnectionString("Default"));
                ;
            return new SaasMigrationsDbContext(builder.Options);
        }
```
Run the migration:
```shell
PM> add-migration InitForSqlite
To undo this action, use Remove-Migration.
PM> update-database
Applying migration '20190621050122_InitForSqlite'.
Done.
PM> 
```
The result is that all XXDbContexts are generated in a Saas_MainDb.Db .

![image](https://user-images.githubusercontent.com/12068896/59898963-94a43100-9425-11e9-8a37-657b557ff0d8.png)

**Comment by maliming** [comment]
The migration will only use the Default connection string. Try to modify the contents of the Default connection string.

**Comment by Fisher-Joe** [comment]
How to modify?
Change every time I migrate XXDbContext?

**Comment by maliming** [comment]
Perform migrations for other databases.
```
"Default": "Data Source=..\\Aiwosoft.Saas.Web\\App_Data\\Saas_MainDb.db;",
"Default": "Data Source=..\\Aiwosoft.Saas.Web\\App_Data\\Saas_AbpIdentityServerDb.db;",
....
```

**Comment by Fisher-Joe** [comment]
I confused, same connection name?

**Comment by maliming** [comment]
I mean you need to migrate for each database. Make it have a table structure.

**Comment by Fisher-Joe** [comment]
In this case, isn't  each Db  the same tables?
I think this is not the best practice.

**Comment by Fisher-Joe** [comment]
Use the following code to migrate separately.

```shell
add-migration InitForPermission -Context PermissionMigrationDbContext
```
I am writing a separate code for the migration.Wait a moment.
