### ISSUE TITLE
Refine user edit permission.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#13239]
```
User management -> Edit -> Edit roles
User management -> Edit -> Edit orgs
```

Avoid users changing their roles to get more permissions.

**Comment by maliming** [comment]
From https://support.abp.io/QA/Questions/3369/

**Comment by sturlath** [comment]
Can this be a host setting also? So when a tenant is created he does not have access to permissions and only roles?

Just today I was restricting new tenants from having access but just when seeding

![image](https://user-images.githubusercontent.com/2386572/180052352-3208cc4e-00f6-4bbb-8e31-92b03262e1fd.png)

**Comment by maliming** [comment]
Your case is about seeding, not permissions.

**Comment by maliming** [comment]
We implemented this in the Identity Pro module, The open source remains the same.
