### ISSUE TITLE
Add Linux Support in the MAUI template

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [abpframework/abp#13238]
* **ABP Framework version:** dev branch.
* **User Interface:** MAUI

Please, add in the MAUI Template Linux Support. I will have free time to collaborate after August. There is AvaloniaUI as a multiplatform mobile/all in one  solution too.

**Comment by berkansasmaz** [comment]
https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms

I don't think there is a problem with ABP, could you please give some more details about the problem you are having?

**Comment by beriniwlew** [comment]
Unless I'm missing something, this is what I could find for MAUI support for Linux.
https://github.com/jsuarezruiz/maui-linux

It's all community supported.
