### ISSUE TITLE
Suggestion: Automatically stop all classes that inherit from IRunable

### ISSUE THREAD

**Issue by virtualcca** [abpframework/abp#13233]
If a class that inherits from IRunable (such as BackgroundWorkerManager) is also used as IRunable when it is registered for dependency injection
is it possible to uniformly obtain IEnumerable<IRunable> from ServiceProvider in the Shutdown method of Thread's Module and then execute StopAsync uniformly

For example
 in the Module, through context.Service.OnRegistered, if the Type is IRunable, the implementation class is registered with IRunable as TService (<IRunable, TImplementation>)

Then
```csharp
    public override void OnApplicationShutdown(ApplicationShutdownContext context)
    {
           //Gives a 5 second stop time
            var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
            var runableList = context.ServiceProvider.GetService<IEnumerable<IRunnable>>();
            if (runableList != null)
                AsyncHelper.RunSync(() =>
                    Task.WhenAll(runableList.Select(a => a.StopAsync(cts.Token))));
     }
```

**Comment by maliming** [comment]
This doesn't seem to fit the current design.

**Comment by virtualcca** [comment]
This approach can unify the Stop behavior of IRunable to the Thread module for processing
without requiring each module to remember to process stop during shutdown

Although there are not many IRunables currently

**Comment by maliming** [comment]
It is up to the module implementing `IRunable ` to control it.

**Comment by virtualcca** [comment]
Ok, if you think that stop should be handled by each module, then I will close this issus
