### ISSUE TITLE
LeptonX Lite - Blazor Server MainLayout background and width

### ISSUE THREAD

**Issue by BogdanJak** [abpframework/abp#13244]
ABP Framework version - 5.3.1
User Interface - Blazor server
Your database provider - EF Core

Hello

1. How to set the full width of opened pages to 100% MainLayout width? (picture)
2. is it possible to set the background MainLayout color to e.g. black?

![image](https://user-images.githubusercontent.com/54505464/177386473-c5791924-23c0-4f65-89a9-11f27b205018.png)

**Comment by BogdanJak** [comment]
?

**Comment by BogdanJak** [comment]
What a great help - exemplary support.

**Comment by yekalkan** [comment]
duplicate of https://github.com/abpframework/abp/issues/13803
