### ISSUE TITLE
Update from suite scan whole folder

### ISSUE THREAD

**Issue by andmattia** [abpframework/abp#13240]
ABP Suite 5.3.1

I try to update a module created with suite and update command try to update the whole folder.

\Repos
--\Module1
--\Module2

I update my module1 and suite update command update Module1 & Module2

**Comment by maliming** [comment]
hi

You can cd to the `Module2` and run the `update` command.

**Comment by andmattia** [comment]
@maliming 

can you explain what does you mean with "can cd to Module2".

I do this from abp suite UI not via cmd line

**Comment by maliming** [comment]
> I do this from abp suite UI not via cmd line

Can you share a screenshot? Thanks

**Comment by andmattia** [comment]
It's simple to reproduce:
1. open suite 
2. create project1 in folder \repos\project1
3. create second project -> project2 (with abp version lower than lastest)
4. go to suite ui and click on update botton
![Immagine 2022-07-13 131724](https://user-images.githubusercontent.com/8192217/178721614-e69cd7c8-c3b3-4d2a-8910-f28b6957254c.jpg)
5. look the logs and see the suite try to update all project (1 and 2)

**Comment by hikalkan** [comment]
@yekalkan with 7.0, we'd changed `abp update` command to update all the sub-solutions in a folder. Right? If so, we can close this issue. Otherwise, please move this to 7.0-preview milestone since we don't have time for 7.0 version anymore.
