### ISSUE TITLE
[Commercial] Button in Suite generated code needs padding 

### ISSUE THREAD

**Issue by hellorms** [abpframework/abp#13259]
**Version** 5.3.1 Commercial
**User Interface** MVC
**Database** EF Core
**LeptonX Version** 1.0.0-beta.3

After creating new CRUD pages using Suite, on the index.cshtml page there is no space between the **New XXX** button and the html card below.

Possible solution: The AbpContentToolbar div should have some padding below it to separate it from the card.

![image](https://user-images.githubusercontent.com/93287086/177648429-6526c4ac-4b78-4b89-9b9f-d28c89d3fd95.png)

**Comment by maliming** [comment]
hi

Please discuss the commercial on https://support.abp.io/
