### ISSUE TITLE
Volo.Abp.FluentValidation - Documentation not clear on at what point ABP calls the Validate() method

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#13255]
Hi,

I would like to use FluentValidation and I followed the ABP documentation on the topic: https://docs.abp.io/en/abp/latest/FluentValidation

1. I would like to know, at which point does ABP call the Validate() method?
    It's not clear in [the documentation](https://docs.abp.io/en/abp/latest/FluentValidation)
2. Does it happen when the object is passed to a method?
3. **With the library,** **can I explicitly call the Validate()** method i**n ABP**, similar to how it's [described in the documentation](https://docs.fluentvalidation.net/en/latest/start.html#creating-your-first-validator)?
4. Any examples of how the full code will look like?

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.FluentValidation/Volo/Abp/FluentValidation/FluentObjectValidationContributor.cs#L30

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/ObjectValidator.cs#L62

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/MethodInvocationValidator.cs#L101

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/ValidationInterceptor.cs#L24

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/test/Volo.Abp.FluentValidation.Tests/Volo/Abp/FluentValidation/ApplicationService_FluentValidation_Tests.cs

**Comment by tinonetic** [comment]
Thanks for the response. I tried to understand the tests.

Could you explain exactly what happens?

Does the validation only happen when the object in question is passed as a parameter to the method?

**Comment by maliming** [comment]
The interceptor or filter validates the parameter before the method is called.

https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/ValidationInterceptor.cs#L16

**Comment by tinonetic** [comment]
I failed to get it working with a `DomainService`, so I abandoned this approach and used the DI approach as [documented by the FluentValidation team](https://docs.fluentvalidation.net/en/latest/di.html#dependency-injection).

When I have time, I will try to create a sample project to show this behaviour.

Thanks

**Comment by maliming** [comment]
OK, No problem.

**Comment by WhThree** [comment]
> The interceptor or filter validates the parameter before the method is called.
> 
> https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/ValidationInterceptor.cs#L16

Hi @maliming , I meet an issue that Fluent Validation was NOT automatically called when not explicitly write a controller

Not automatically validate in this case:
```
       //config controller
        Configure<AbpAspNetCoreMvcOptions>(options =>
        {
            options.ConventionalControllers.Create(typeof(ABPDemo2ApplicationModule).Assembly);
        });

```
```
        // service
	public class TestAppService : ApplicationService, ITestAppService{

		public TestAppService() {
		}

		public Task TempCall([FromBody] TestDto1 data) {
                        //no validation works
			return Task.CompletedTask;

		}

		public class TestDtoValidation : AbstractValidator<TestDto1>, ITransientDependency {

			public TestDtoValidation() {
				RuleFor(x => x.Name).NotEmpty().WithMessage("error");
			}
		}

	}

```

Only when I write a controller manually without the configuration above, and get a service by DI, then the auto-validation works:

```
	public class TestController : Controller {
		private readonly ITestAppService testAppService;

		public TestController(ITestAppService testAppService) {
			this.testAppService = testAppService;
		}
		[HttpPost]
		public async Task<IActionResult> MyTest(TestDto1 data) {
			await testAppService.TempCall(data); //here I can get exception from fluent validation
			return Ok("123");
		}
	}

```

Could you please tell me why, looks like InvocationValidator not work when method is called as an API?
