### ISSUE TITLE
Property Injection

### ISSUE THREAD

**Issue by BlackNinja1903** [abpframework/abp#13252]
Hi,

 I need to inject a property like AbpDbContext's LazyServiceProvider. 

[Volo.Abp.EntityFrameworkCore.AbpDbContext.cs](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs)

```cs
public abstract class AbpDbContext<TDbContext> : DbContext, IAbpEfCoreDbContext, ITransientDependency
    where TDbContext : DbContext
{
    public IAbpLazyServiceProvider LazyServiceProvider { get; set; }
...
...
```

So I searched a place to get how abp injects LazyServiceProvider property but couldn't find any. Could you help me please.

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Dependency-Injection#property-injection
