### ISSUE TITLE
Replacing razor pages not working

### ISSUE THREAD

**Issue by Webdiyer** [abpframework/abp#1326]
I've read the [Virtual File System](https://abp.io/documents/abp/latest/Virtual-File-System) document and issue #873 carefully, what I want to do is customize index page of users management of the identity module, This is what I have done:

- Created a new abp project by using abp new command;
- Run update-database command to generate database;
- Created the pages\identity\users folder and added an empty index.cshtml in the Web project and set it property as embedded resource;
- Added a modified version of index.js to the same folder;
- Register XXXWebModule to the virual file system In XXXWebModule.cs file as following:
`
Configure<VirtualFileSystemOptions>(options =>
            {
                options.FileSets.AddEmbedded<AbpTestWebModule>();
            });
`
Run project and I can see that replaced index.js has took affect immediately, but the new razor page does not work. I've aost tested with the lasted version 0.18.0-preview20190619 with the same result. The document says "An embedded view/page can be overrided if a module/application locates a new file into the same location as mentioned above",  Is this a bug or I missed something? Thanks!

**Comment by maliming** [comment]
I have not reproduced your problem, the application is performing as expected.

![image](https://user-images.githubusercontent.com/6908465/59841586-36c10c00-9387-11e9-9576-b1e7e2b8f5bc.png)

You can provide a recurring project. The project name is changed to: Acme.BookStore

**Comment by Nongzhsh** [comment]
Hey, have you tried  providing ‘BaseNamespace’ parameter when you registed the module to the virtual system. like:
`Configure<VirtualFileSystemOptions>(options => { options.FileSets.AddEmbedded<AbpTestWebModule>("AbpTest"); });`

**Comment by Webdiyer** [comment]
@Nongzhsh Thank you very much, it works!

**Comment by Nongzhsh** [comment]
I think it's a bug. @maliming

**Comment by maliming** [comment]
@Nongzhsh The 0.18.0 version will be released soon, after which you can try again.
