### ISSUE TITLE
Enum Localization

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#13264]
Hi

Im trying to localize enums in abp-select tag helper. I looked over below documentation and it doesn't work.
https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=MVC&DB=EF#localization

But the proper way is explained below.
https://docs.abp.io/en/abp/5.3/UI/AspNetCore/Tag-Helpers/Form-elements#label-localization-1

So can you please resolve the conflict between these pages? Or am i missing something?

**Comment by maliming** [comment]
Did you try this demo?

https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore

**Comment by naderjavid** [comment]
hi, you must use it this way
assume we have below enum 
    public enum UnitType
    {
        Undefined,
        Ceo,
        Deputy,
        Management,
        RegionManagement,
        Expert
    }

for the English localization we have this
{
    "Enum:UnitType:0": "Undefined",
    "Enum:UnitType:1": "Ceo",
    "Enum:UnitType:2": "Deputy",
    "Enum:UnitType:3": "Management",
    "Enum:UnitType:4": "RegionManagement",
    "Enum:UnitType:5": "Expert",
}

for Persian localization you must do this way
{
    "Enum:UnitType:0": "انتخاب نشده",
    "Enum:UnitType:1": "مدیرعامل",
    "Enum:UnitType:2": "معاون",
    "Enum:UnitType:3": "مدیر",
    "Enum:UnitType:4": "مدیر منطقه",
    "Enum:UnitType:5": "کارشناس",
    "UnitType.Undefined": "انتخاب نشده",
    "UnitType.Ceo": "مدیرعامل",
    "UnitType.Deputy": "معاونت",
    "UnitType.Management": "مدیریت",
    "UnitType.RegionManagement": "مدیریت منطقه",
    "UnitType.Expert": "کارشناس",
}

**Comment by muhlisatac** [comment]
@naderjavid  why do you have to localize same thing twice? @maliming I didn't downloaded the demo but i followed the tutorial.

**Comment by muhlisatac** [comment]
https://github.com/abpframework/abp/pull/13451 this one solves this issue i think. So im closing it.
