### ISSUE TITLE
Abp.Timing.Timezone - setting ignored

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#13276]
We are experiencing problems with retrieval of Tenant Settings, specifically Abp.Timing.Timezone, from the database. Our application is running on v4.3. with Multitenancy and separate postgres databases for each Tenant. 
In the modules, where the timezone settings are needed, we have defined the ModuleSettingDefinitionProvider as the [documentation](https://docs.abp.io/en/abp/4.3/Settings) instructs.

```
public class ModuleSettingDefinitionProvider : SettingDefinitionProvider
    {
        public override void Define(ISettingDefinitionContext context)
        {
            /* Define module settings here.
             * Use names from ModuleSettings class.
             */

            context.Add(
                    new SettingDefinition("Abp.Timing.Timezone", "UTC")
                );
        }
    }
```
In the AppServices we are using the `_settingProvider.GetOrNullAsync("Abp.Timing.Timezone");`

On our development enviroment we run into no problems and the correct database defined setting is retrieved and used without problems, whereas on our production we run into the issue, that the correct setting is not retrieved and the default »UTC« Timezone from the SettingDefinitionProvider is used in further operations. We have tried defining the settings:

- 	In the host database (public/AbpSettings) where the Theme settings are also defined and are working fine (first row is an example of table entry working fine, other rows are the combinations we have tried to use)
![image](https://user-images.githubusercontent.com/39346964/177936807-9deff617-5a37-4325-a409-96edb11e54c2.png)

-	In the tenant database (public/AbpSettings) which initially was empty
![image](https://user-images.githubusercontent.com/39346964/177936969-e5cb0aa4-7782-4244-8ce0-c94c36fcc28e.png)

We are aware, that with the ProviderKey value »null« in the row with the ProviderName »T« (Tenant) is incorrect, but tried it anyway. We have also tried a combination of the above variants (Default, Global, Tenant).

**Comment by maliming** [comment]
Can you provide steps or code to reproduce the problem?

**Comment by luks104** [comment]
> Can you provide steps or code to reproduce the problem?

1. Define Abp.Timing.Timezone SettingDefinition in the SettingDefinitionProvider:
```
public class ExampleApplicationSettingDefinitionProvider : SettingDefinitionProvider
    {
        public override void Define(ISettingDefinitionContext context)
        {
            /* Define module settings here.
             * Use names from ModuleSettings class.
             */

            context.Add(
                    new SettingDefinition("Abp.Timing.Timezone", "UTC")
                );
        }
    }
```

2. In the AppService, use the ISettingProvider to retrieve the setting
```
public ProductAppService : ExampleApplicationAppService, IProductAppService
{
     ...
     private readonly ISettingProvider _settingProvider;
     ...
     public ProductAppService(..., ISettingProvider settingProvider, ...)
     {
          ...
          _settingProvider = settingProvider;
          ...
     }

     public string GetTenantTimezone()
     {
          string timezone = await _settingProvider.GetOrNullAsync("Abp.Timing.Timezone");
          return timezone;
     }
}
```

This example works on development enviroment, but doesn't work on the production one. The different database entries, that we tried, are defined in the original post.

**Comment by maliming** [comment]
> but doesn't work on the production one.

I can't reproduce the problem in this case.
