### ISSUE TITLE
An error in ServiceCollectionCommonExtensions. GetRequiredService<T>

### ISSUE THREAD

**Issue by tianxin8206** [abpframework/abp#13281]
abp version: 5.3.2

error:
![image](https://user-images.githubusercontent.com/32237514/178217661-f9936cc2-201b-44d0-b929-29a3da1f7520.png)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by tianxin8206** [comment]
This is a startup error.
![image](https://user-images.githubusercontent.com/32237514/178220834-a335a505-7422-46d4-8805-4ddf0ee0d0fd.png)

**Comment by JadynWong** [comment]
`Services.GetService` cannot be used when configuring services.  It depend on `IServiceProvider` to exist only after start initialization.

If you want to use logging, you can try `var logger = context.Services.GetInitLogger<TModule>()`.

**Comment by tianxin8206** [comment]
Thank you for your help. @JadynWong
