### ISSUE TITLE
DistributedCache

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#1328]
`IDistributedCache<List<TenantConfiguration>> _tenantIdsCache`
this is my code

I've defined a distributed cache object, it's fine to use locally but I can't get the value once I publish it to the server environment. Why? can i use list type?

**Comment by SmallShrimp** [comment]
I've defined a distributed cache object, it's fine to use locally but I can't get the value once I publish it to the server environment. Why? can i use list type?

**Comment by hikalkan** [comment]
You should be able to use `List<TenantConfiguration>` as the cache item, while I suggest to create a specific class for it.

Are you using Redis? Also, what exception are you getting?

**Comment by SmallShrimp** [comment]
no exception!i use sqlserver.
yes! a specific class can solve it.
and I think you should create a `getAll` method for IDistributedCache

**Comment by hikalkan** [comment]
GetAll method is not supported by Micrsoft's IDistributedCache interface. ABP's `IDistributedCache<T>` only is a shortcut for it. So, we can not add GetAll.

>yes! a specific class can solve it.

Id you are sure, we can close this issue.

**Comment by SmallShrimp** [comment]
ok
