### ISSUE TITLE
How about using ABP to monitor industrial signals in real time

### ISSUE THREAD

**Issue by luy710** [abpframework/abp#13280]
How about using ABP to monitor industrial signals in real time? Is this framework competent for TCP high concurrency monitoring? Will it be bloated?

**Comment by leonkosak** [comment]
Please describe "industrial signals in real time".
I would say that db design is one of the crucial factors.

**Comment by luy710** [comment]
Indeed, db design is very important aspect. 
For example, collect the success signal of electric hand drill in real time, and control whether the pipeline enters the next process through counting

**Comment by luy710** [comment]
> 

Indeed, db design is very important aspect.
For example, collect the success signal of electric hand drill in real time, and control whether the pipeline enters the next process through counting

**Comment by luy710** [comment]
> Please describe "industrial signals in real time".
> I would say that db design is one of the crucial factors.

Indeed, db design is very important aspect.
For example, collect the success signal of electric hand drill in real time, and control whether the pipeline enters the next process through counting

**Comment by tinonetic** [comment]
Absolutely possible through TCP. That's more of a .NET capability than it is an ABP capability.

It can be "real" realtime or near-realtime, depending on the whole signalling pipeline & the components you choose to use

You can definitely do it and build ABP around it.

Good luck!

**Comment by leonkosak** [comment]
I can confirm that abp framework (abp and Commercial version) are so very polished nowadays (backend code) that nearly all performance-related issues are gone. There were some issues in 2019 and 2020.
