### ISSUE TITLE
when update from 4.4.2 to 5.3.2 TargetFramework not changing

### ISSUE THREAD

**Issue by naderjavid** [abpframework/abp#13294]
ABP Framework version: 5.3.2
User Interface: MVC

reproduce: I had project by abp version 4.4.2 when exec command "abp update" everything is ok except two ones:
1. TargetFramework not changed still same "<TargetFramework>net5.0</TargetFramework>"
2. and modules folder not affected by command

**Comment by maliming** [comment]
hi

Please update the TargetFramework manual. `update` command only update the package version.

**Comment by realLiangshiwei** [comment]
Check the Migration Guides https://docs.abp.io/en/abp/latest/Migration-Guides/Index

**Comment by leonkosak** [comment]
Some things should be changed manually.
