### ISSUE TITLE
Update samples to 6.0 RC

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#13299]
When the 6.0 RC version is released.

**Comment by ebicoglu** [comment]
@realLiangshiwei tells to @salihozkara which samples he will update.
you shouldn't work on the same templates.

**Comment by salihozkara** [comment]
I am updating the examples used in our tutorials like Acme.BookStore and TodoApp.

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/issues/13299#issuecomment-1217518588
