### ISSUE TITLE
Authorisation in ABP --> ABP.io....

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1329]
Hi,

I need to consolidate authorisation between WebForms (using APB), MVC 5 (using ABP), MVC Core (using ABP) as per my [SO post](https://stackoverflow.com/questions/56697777/consolidating-asp-net-membership-asp-net-identity-asp-net-identity-core).

We plan to use abp.io .NET Core 3.x (.NET 5) moving forward. Is there anything else I should know/consider wrt to abp.io based on what is known now? I realise abp.io is still a work in progress, but I am looking for any suggestions on how I can make my life easier in terms of authentication moving forward. Am I "safe" sticking with ASP.NET Core Identity? Or should I do something else?

Cheers,

**Comment by hikalkan** [comment]
>Am I "safe" sticking with ASP.NET Core Identity? Or should I do something else?

Yes, we are also using it. For single sign on, we are using identityserver4 with standard OpenId Connect protocol.

**Comment by natiki** [comment]
Thanks @hikalkan
