### ISSUE TITLE
Prevent multiple reactions for the same entity

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#13313]
Also remove underlines for anchors
![image](https://user-images.githubusercontent.com/58659931/178971139-326524e0-9ab6-4946-af85-957f6b6f88ea.png)
![image](https://user-images.githubusercontent.com/58659931/178971247-618042f1-81c4-4b18-aaab-b82859351555.png)

**Comment by enisn** [comment]
Next step of https://github.com/abpframework/abp/issues/10801

**Comment by malikmasis** [comment]
It seems okay. @salihozkara approved as well.

**Comment by enisn** [comment]
Still possible. When you hit the reaction button before the first reaction request is completed, the second reaction will be added.

![multiple-reactions](https://user-images.githubusercontent.com/23705418/182357276-a5cbe7b8-4242-4c74-94be-25b854f91ecd.gif)
