### ISSUE TITLE
Custom Filter based upon Property (How to Question)

### ISSUE THREAD

**Issue by biomade** [abpframework/abp#13315]
version: 5.3
interface: mvc
database: ef core

I am creating a  custom filter so I can filter data based upon a user (user id), following the example in the documentation. [DataFiltering](https://docs.abp.io/en/abp/latest/Data-Filtering) but the example deals with a bool and the userID is a GUID

my interface is:

```
public interface IHasPerson
{
    Guid PersonId { get; }
}
```
My issue is when I get to the adding the filter to the dbContext show do I test for the   filter and then apply it? 
I modified the code from the example to use my object names.  What should the Expression<> line be?? 

```
protected override Expression<Func<TEntity, Guid>> CreateFilterExpression<TEntity>()
{
    var expression = base.CreateFilterExpression<TEntity>();
    if (typeof(IIsActive).IsAssignableFrom(typeof(TEntity)))
    {
        Expression<Func<TEntity, Guid>> hasPersonFilter =
            e => !hasPersonFilter || EF.Property<Guid>(e, "PersonId");  <==This line should be what??
       
          expression = expression == null 
            ? hasPersonFiler 
            : CombineExpressions(expression, hasPersonFilter);
    }
    return expression;
}
```

**Comment by realLiangshiwei** [comment]
You can refer this: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L687

**Comment by biomade** [comment]
In the documents on filters there is this line to enable/disable where is this done??
```
Configure<AbpDataFilterOptions>(options =>
{
    options.DefaultStates[typeof(ISoftDelete)] = new DataFilterState(isEnabled: false);
});
```

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L45
