### ISSUE TITLE
Move connection string names to constants for modules.

### ISSUE THREAD

**Issue by Fisher-Joe** [abpframework/abp#1332]
Add ConnectionName in AbpXXXManagementConsts.cs and use it at IXXManagementDbContext and XXManagementDbContext

**Comment by hikalkan** [comment]
Thanks for the suggestion, will do it. It is appreciated if you send a PR.

**Comment by Fisher-Joe** [comment]
Ok, I do it.

**Comment by maliming** [comment]
fixed by https://github.com/abpframework/abp/pull/1351
