### ISSUE TITLE
Upgrade to .NET 7.0

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#13336]
We will upgrade the framework, modules and all other components to .NET 7.0. Current latest preview is [Preview 7](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-6/). However, we don't have to use this. I think we can wait for the next preview (probably will be released in August). We should be sure that all our dependencies can properly work with .NET 7.0.

**Comment by maliming** [comment]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/7.0

https://devblogs.microsoft.com/dotnet/announcing-net-7-preview-1/
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-2/
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-3/
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-4/
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-5/
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-6/
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-7/

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-5/
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/

https://devblogs.microsoft.com/dotnet/announcing-entity-framework-7-preview-1/
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-7-preview-3/
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-7-preview-4/
https://devblogs.microsoft.com/dotnet/announcing-ef7-preview5/
https://devblogs.microsoft.com/dotnet/announcing-ef7-preview6/
https://devblogs.microsoft.com/dotnet/announcing-ef7-preview7/

**Comment by maliming** [comment]
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-6/#json-contract-customization

**Comment by maliming** [comment]
https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql (https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557)
https://www.nuget.org/packages/Oracle.EntityFrameworkCore
https://www.nuget.org/packages/Devart.Data.Oracle.EFCore
