### ISSUE TITLE
ABP Dapr EventBus integration (For Publish & subscribe messaging)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#13338]
## Requirements / Definition

* I've created `Volo.Abp.EventBus.Dapr` package for the integration.
* When we use this package, events are auto-published using [Dapr's pub-sub API](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/publish-subscribe).
* We may use Dapr's way to subscribe events, like using the `Topic` attribute on an MVC Controller's action. Or we can use the declarative way by configuring it out of the application code (declarative way) (see [subscription methods](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/))
* We should also be able to use ABP's standard event subscription system, with IDistributedEventHandler (see [subscription methods](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/)). I suppose we can use app.MapPost to auto-subscribe the event and forward the received events to the event handler.
* Check if we need (and can) use ABP's outbox and inbox patterns alongside Dapr (maybe dapr has a similar system already and we don't need it).

## Development notes

* Branch to work on: https://github.com/abpframework/abp/tree/dapr-integration

**Comment by geffzhang** [comment]
is it possible for the ABP team to use  https://github.com/EasyAbp/Abp.EventBus.Dapr, If so, I will archive the [Abp.EventBus.Dapr](https://github.com/EasyAbp/Abp.EventBus.Dapr) module and wait for Volosoft's implementation.

**Comment by hikalkan** [comment]
Thanks @geffzhang for sharing. We will inspire from it.
