### ISSUE TITLE
ABP Dapr HTTP Client integration (For Service invocation)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#13339]
## Requirements / Definition

* I've created `Volo.Abp.Http.Client.Dapr` as a starting point.
* Basically, we will implement the integration over the [HttpClient approach of Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/service-invocation#invoke-http-services-using-httpclient).
* I see the most important integration point is to implement our `IProxyHttpClientFactory` interface using Dapr's `DaprClient.CreateInvokeHttpClient()` (I mean we will replace the `DefaultProxyHttpClientFactory` service). In this way, ABP's static & dynamic client system with all its features will continue working as before. All we do is to make requests are passign through Dapr, so it can intercept the request, implement DNS resolving, encryption, tracing and all other its features.
* Also investigate consuming gRPC services. We may not make an integration within this issue, but try to understand what we can do on that.

## Development notes

* Branch to work on: https://github.com/abpframework/abp/tree/dapr-integration

**Comment by geffzhang** [comment]
is it possible for the ABP team to use https://github.com/geffzhang/EasyAbp.Abp.Dapr  , If so, I will archive the [EasyAbp.Abp.Dapr ](https://github.com/geffzhang/EasyAbp.Abp.Dapr  ) module and wait for Volosoft's implementation.

**Comment by hikalkan** [comment]
Thanks @geffzhang for sharing. We will inspire from it.

**Comment by realLiangshiwei** [comment]
Dapr support gRPC proxying : [`DaprClient.CreateInvocationInvoker`](https://github.com/dapr/dotnet-sdk/blob/0c9d6a45c8d3792a92d7141056c390bea098d02b/test/Dapr.E2E.Test/ServiceInvocation/E2ETests.GrpcProxyInvocationTests.cs#L40) . so we can use it with the standard gRPC service
