### ISSUE TITLE
Abp.io visual problems

### ISSUE THREAD

**Issue by armgnunlu** [abpframework/abp#1334]
1. Do not open the blog in a new tab. (already the site header is coming)
2. Edit blog page padding. (looks short black bg at the bottom of the page)
3. Login page 767px and 992px are very narrow. Edit.
4. The login page looks strange when changing the language.
5. The "see documents" button on the footer will open the "Docs" page in the new tab.
6. Reduce the "modular section" paragraph padding on mobile.
7. There should be a line between the "modular section" items on mobile.

**Comment by lanpin** [comment]
I can't register at abp.io

**Comment by hikalkan** [comment]
@lanpin, I create https://github.com/abpframework/abp/issues/1340 for the register problem.

**Comment by Xeevis** [comment]
Logout from Menu also opens new tab

```html
<a class="dropdown-item" href="/Account/Logout?returnUrl=/" target="_blank">Log out</a>
```

**Comment by armgnunlu** [comment]
@Xeevis, visual problems were fixed, logout included. Thank you.
