### ISSUE TITLE
CMS Kit: Set a page as the "home page"

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#13350]
We can be able to set a page (in the admin UI) as the "home page". Home page should be shown when developer hasn't created a home page in the application. I mean the developer can create a regular, development-time home page (like `/Pages/Index.cshtml`). In this case, the development-time home page is shown.

**Comment by ebicoglu** [comment]
Users should also be able to select an unauthenticated page so that we can show an info landing page without login.
