### ISSUE TITLE
ReplaceService conflict with event handling

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#13352]
Publishing an event instantiate all related classes that have the correct IDistributedEventHandler on it.

If you replace an service with IDistributedEventHandler by ReplaceService = true, it will still instantiate both services.

We thought that if you only expose the services by interface it should fix it but these classes are instantiate by the class name, so you get an exception in this case.

Here are example files for testing purpose:

```csharp
public interface IExample : ITransientDependency { }
```

```csharp
[ExposeServices( typeof( IExample ), typeof( ExampleService ) )]
public class ExampleService : IExample,
	IDistributedEventHandler<TestEvent>
{
	public Task HandleEventAsync( TestEvent eventData )
	{
		eventData.Data += $"{GetType()}";
		
		return Task.CompletedTask;
	}
}
```
```csharp
[Dependency( ReplaceServices = true )]
[ExposeServices( typeof( ReplaceService ), typeof( IExample ) )]
public class ReplaceService : IExample, IDistributedEventHandler<TestEvent>
{
	public Task HandleEventAsync( TestEvent eventData )
	{
		eventData.Data += $"{GetType()}";
		
		return Task.CompletedTask;
	}
}
```
```csharp
public class TestEvent
{
	public string Data = string.Empty;
}
```

```csharp
public sealed class Example_Tests : BookStoreDomainTestBase
{
	private readonly IExample _example;
	private readonly IDistributedEventBus _eventBus;
	
	public Example_Tests()
	{
		_eventBus = GetRequiredService<IDistributedEventBus>();
		_example = GetRequiredService<IExample>();
	}

	[Fact]
	public void ReplaceService()
	{
		// Assert
		_example.ShouldBeOfType<ReplaceService>();
	}

	[Fact]
	public async Task EventHandling()
	{
		// Arrange
		TestEvent exampleEvent = new();
		
		// Act
		await _eventBus.PublishAsync( exampleEvent );
		
		// Assert
		exampleEvent.Data.ShouldBe( $"{typeof( ReplaceService )}" );
	}
}
```

We also tried to inherit from the original service but it has the same output.

**Comment by realLiangshiwei** [comment]
> Publishing an event instantiate all related classes that have the correct IDistributedEventHandler on it.
> If you replace an service with IDistributedEventHandler by ReplaceService = true, it will still instantiate both services.

This is designed by the `EventBus` system, you should use `_eventBus.Unsubscribe<ExampleService>` to unsubscribe an event handler.

**Comment by puschie286** [comment]
@realLiangshiwei 
how do you unsubscribe events from service if you only know the service interface ? 
( there is no information about unsubscribe in the documentation - [see search](https://docs.abp.io/search/en/abp/6.0/?keyword=Unsubscribe) )

the purpose of creating an service interface is to hide the implementation details and make it replaceable, right ?
if having an event on an service implementation makes it unable to be replaced ( or requires you to know the implementation details to be able to replace it ), than there is no reason to have an service interface in the first place

so could you unsubscribe all event from a service that is replaced on the registering process ? ( or add a new parameter to the dependency attribute for that ).

**Comment by realLiangshiwei** [comment]
As I said, this is by design.

**An event can be subscribed to by multiple handlers.**

Consider the following scenario:

```csharp
public interface IMyEventHandler
{
}

public class MyEventHandlerA : IMyEventHandler, IDistributedEventHandler....
{ 
     ........
}


public class MyEventHandlerB : IMyEventHandler, IDistributedEventHandler....
{ 
     ........
}
```

We have two event handlers `MyEventHandlerA` and `MyEventHandlerB` , if we use the `IMyEventHandler` interface instead of the real type, what happens, `MyEventHandlerB` will be executed twice(), because we can only get the last registered type from IOC.

> how do you unsubscribe events from service **if you only know the service interface**?

This is why we do not recommend creating an interface for an event handler.

If you want to override an event handler, you just need to unsubscribe, no big deal

**Comment by puschie286** [comment]
i dont want to override an event handler, i want to replace a service ( anything that is registered to DI ) - the user cant know if the service implementation use an event handler or not ( so he cant know if he need to unsubscribe or not ) - he only has access to the interface not to the implementation ( so even if he know that he has to unsubscribe, he cant because he doesnt know the real type of the original service implementation )

i think this is an flaw of the service replacement functionality ( and NOT the event system ) - thats why i ask if you could handle this in your dependency registration process ( [DefaultConventionalRegistrar](https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Core/Volo/Abp/DependencyInjection/DefaultConventionalRegistrar.cs#L40) )

edit: tested a few approaches but none of them handled all cases, so i cant provide any working PR for this, i was hoping some one of the abp team might have an idea of how to clean up replaced DI classes from AbpEventBusOptions ( distributed + local )

**Comment by puschie286** [comment]
i did serveral test and one solution would be:

1. get the "implementation type" from replaced service descriptor
2. remove "implementation type" from "Handlers" in AbpDistributedEventBusOptions and AbpLocalEventBusOptions

**Comment by puschie286** [comment]
@realLiangshiwei tried unsubscribe approach but first of all it is async ( so not useable in constructor ) and there is no method to unsubscribe all event from a specific type - so there is no way to unsubscribe the replaced type.
