### ISSUE TITLE
Login doesn't work on tiered template

### ISSUE THREAD

**Issue by ismcagdas** [abpframework/abp#1335]
If you download a tiered template from https://abp.io/get-started, login doesn't work on main app.
To fix this, replace the URL in IdentityServerClientRedirectUris table with the URL of main web app.

**Comment by maliming** [comment]
There are three Urls in the MVC template that need to be replaced.

https://github.com/abpframework/abp/blob/7df2051345c6882db6b9e29a81031107cad15287/templates/mvc/src/MyCompanyName.MyProjectName.DbMigrator/appsettings.json#L9

https://github.com/abpframework/abp/blob/7df2051345c6882db6b9e29a81031107cad15287/templates/mvc/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp/appsettings.json#L4

https://github.com/abpframework/abp/blob/7df2051345c6882db6b9e29a81031107cad15287/templates/mvc/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp/appsettings.json#L14
