### ISSUE TITLE
Make obfuscated dll´s trim friendly

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#13373]
I was trying to trim the Blazor project with ` <PublishTrimmed>true</PublishTrimmed>` but hit this issue with the linker on abp.io dll´s , [Blazor linking throws "Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object."](https://github.com/dotnet/linker/issues/2896) 
 
Can you try to make it[ trim friendly](https://github.com/dotnet/linker/issues/2896#issuecomment-1192329030)?

Version: 5.3.2 Commercial

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem, could you provide steps to reproduce?

![image](https://user-images.githubusercontent.com/16813853/180411940-e51b53b0-2799-4e39-89fc-d0ca94c011bc.png)

**Comment by sturlath** [comment]
@realLiangshiwei  I sent you an email with the code to test

**Comment by realLiangshiwei** [comment]
Hi,

The project you provided has many other package references, I think it might unelated to ABP, can you use CLI to create a new project to reproduce?

**Comment by sturlath** [comment]
I just removed every package reference except for

- Microsoft
- Volo 
- Blazorise

and still get this error.

**Comment by sturlath** [comment]
@realLiangshiwei this seems to be volo https://github.com/dotnet/linker/issues/2896#issuecomment-1192492522

**Comment by realLiangshiwei** [comment]
We will check it

**Comment by sturlath** [comment]
Just checking @realLiangshiwei  will this be check within version 6.0 or later? I´m trying everything to speed up my Blazor backend so possibly getting the size down within 6.0 would be great until  [Can abp Blazor be this fast](https://github.com/abpframework/abp/issues/13114) will be looked at in the version 7 timeframe.

**Comment by realLiangshiwei** [comment]
Hi,

It's in the 7.0 milestone

**Comment by sturlath** [comment]
@realLiangshiwei will this be in 7.0? Just making sure it's not forgotten about

**Comment by realLiangshiwei** [comment]
Yes,  it will include in the 7.0 version.

**Comment by sturlath** [comment]
@realLiangshiwei we tried this again in 7.0.1 as still have this issue

![image](https://user-images.githubusercontent.com/2386572/219945903-6db81f28-392b-4911-b4af-01c46921e2ab.png)

**Comment by realLiangshiwei** [comment]
Hi @sturlath 

We noticed and fixed this issue, you can waiting to the 7.0.2
