### ISSUE TITLE
Use ABP Logo instead of Lepton Logo on templates

### ISSUE THREAD

**Issue by ismcagdas** [abpframework/abp#13408]
- [x] Blazor @enisn 
- [x] Angular @fatihskilic 
- [x] MVC @EngincanV 

At the moment, LeptonX logo is used, see 

https://github.com/abpframework/abp/pull/13345#issuecomment-1190000638

**Comment by EngincanV** [comment]
MVC & Blazor: https://github.com/abpframework/abp/pull/13818
Angular: https://github.com/abpframework/abp/pull/13997
