### ISSUE TITLE
PageBase has been changed to just Page - Documentation is misleading

### ISSUE THREAD

**Issue by StevenOwenNell** [abpframework/abp#1341]
When following along documentation, under the "Create the Books Page" section [https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I#create-the-books-page](url) it is suggested that line 3 should be `@inherits Acme.BookStore.Web.Pages.BookStorePageBase`

Class fails to compile and I could not find anything in the project that matches 'PageBase'.
The following change that works is the following:
`@inherits Acme.BookStore.Web.Pages.BookStorePage`

**Comment by maliming** [comment]
The class name in the template has been modified. I will update the documentation.

**Comment by StevenOwenNell** [comment]
Pull request created @maliming @hikalkan

**Comment by StevenOwenNell** [comment]
Closed by #1346
