### ISSUE TITLE
Recommand setting the AbpExceptionFilter entry method OnExceptionAsync as a virtual method

### ISSUE THREAD

**Issue by Hopcos** [abpframework/abp#13418]
Whether OnExceptionAsync can be changed as a virtual method? Because then I can just overriding it.

![9092e3b805e4a64f8b097f39e502df9](https://user-images.githubusercontent.com/8747775/180946347-0adc6398-2242-4c57-b10c-f61447981402.jpg)

**Comment by maliming** [comment]
No problem, We will add it in the next version.
