### ISSUE TITLE
Namespace incorrect - change to documentation.

### ISSUE THREAD

**Issue by StevenOwenNell** [abpframework/abp#1342]
When following along documentation, under the "Create the Books Page" section https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I#create-the-books-page

> Ensure that the IndexModel (Index.cshtml.cs) has the Acme.BookStore.Pages.Books namespace, or update it in the Index.cshtml.

This should rather be  `Acme.BookStore.Web.Pages.Books`

**Comment by maliming** [comment]
Thanks, I will update the documentation.

**Comment by StevenNell** [comment]
Would you prefer I create a pull request for all the documentation bugs I find?

**Comment by hikalkan** [comment]
It would be very appreciated. Otherwise, we will handle it.

**Comment by StevenOwenNell** [comment]
@maliming @hikalkan fixed on Pull Request #1346

**Comment by hikalkan** [comment]
Closed by https://github.com/abpframework/abp/pull/1346
