### ISSUE TITLE
Angular dependencies has Conflicting peer dependency. 

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#13426]
When the user runs "npm install", npm throw warnings.

 We need to upgrade some angular dependencies. 

- [x] @swimlane/ngx-datatable

Optional
- [ ] ng-zorro
- [ ] bootstrap
- [ ] ng-bootstrap

 
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/2217899/181016190-ba0de0c8-8f1b-4660-912e-3e695924ccc6.png">

if you want to fix this issue but don't know how to setup env, maybe you can read these  https://github.com/abpframework/abp/blob/dev/docs/en/Contribution/How-to-Contribute-abp.io-as-a-frontend-developer.md

**Comment by ismcagdas** [comment]
@bariscanyilmaz can you work on this issue ? You can get help from @mahmut-gundogdu if needed.
