### ISSUE TITLE
Consistent enum value localization resolving 

### ISSUE THREAD

**Issue by tntwist** [abpframework/abp#13427]
Abp-Version: 5.2.3 (could reproduce on lates version)
UI-Framework: Asp.Net MVC

Hi there,
I noticed that my enums were not localized when using the abp-select helper tag for an enum property.

After checking the docs and code of the select helper tag it seems that the tag helper does resolving of the localization with "Enum:{EnumName}.{EnumStringValue}" (eg. "Enum:Fruit.Apple") as key. 
Doc:
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Tag-Helpers/Form-elements

Code:
https://github.com/abpframework/abp/blob/3d332ed6f1ad6dd71683a0722033fede88db0478/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Form/AbpSelectTagHelperService.cs#L266-L279

When checking the other docs (like the tutorial) the localization resolving happens with the key "Enum:{EnumName}:{EnumIntValue}" (eg "Enum:Fruit.1").

It would be great if you could use a consistent key for resolving enum value localizations over the whole framework.
It reduces the amount of entries within the localization resources and saves some devs times of wondering why their enums wont be localized.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/13451
https://github.com/abpframework/abp-samples/pull/192
