### ISSUE TITLE
MVC UI: Wrong login page

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#13437]
It's looks like use `application` instead of `account` layout

![image](https://user-images.githubusercontent.com/16813853/181208489-85ee3ac6-60da-4fcf-b42b-8ae4739d08a0.png)

**Comment by enisn** [comment]
This will be fixed in the next lepton release,

Account layout seems as fixed:
![image](https://user-images.githubusercontent.com/23705418/182800555-2a656e00-4e70-4b92-b064-5015d01ac6a1.png)
