### ISSUE TITLE
Angular Separate IdentityServer has IdentityServer project

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#13442]
run `abp new MyApplication -t app --ui angular --separate-identity-server --version 6.0.0-rc.1`

contains **MyApplication.IdentityServer** folder with empty `package.json` file:

![image](https://user-images.githubusercontent.com/25867/181349214-e44b01f4-7fb8-4282-a577-4d52d51a159d.png)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/13432
