### ISSUE TITLE
Enable Czech translations for abp documentation

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1345]

**Comment by hikalkan** [comment]
@Xeevis we will publish your translations in the next release. But, we thought that some minimum documentation should be completed in order to publish a new language. We want to keep the quality of the documentation.

Can you complete the following documents:

* Getting Started documents
* Tutorials
* CLI

Thanks for your valuable work.

**Comment by Xeevis** [comment]
@hikalkan Sure. I'll get on it right away.

**Comment by hikalkan** [comment]
Thank you very much.

**Comment by yekalkan** [comment]
it's on live.

https://docs.abp.io/cs/abp/master/

**Comment by yekalkan** [comment]
Mysteriously it is gone.

**Comment by yekalkan** [comment]
> Mysteriously it is gone.

Fixed.
