### ISSUE TITLE
when using LetonXLite theme CmsKit breaks beucase it uses the content_toolbar 

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#13453]
![image](https://user-images.githubusercontent.com/15242923/181474027-979624f5-28fa-4df5-8abc-05a4e4c2ff85.png)

**Comment by EngincanV** [comment]
Hi, I guess your LeptonX Lite theme package version is in an earlier version than **1.0.0-RC.1**. Can you upgrade the package to **1.0.0-RC.1**?

**Comment by vnetonline** [comment]
1.0.0-rc.2 is not found and looking at the docs it says `toolbar` is not included in LeptonX Lite see below table on the commercial site.

![image](https://user-images.githubusercontent.com/15242923/181482903-6d17b4f6-32dc-4a1e-95da-1670f558f58f.png)

**Comment by EngincanV** [comment]
> 1.0.0-rc.2 is not found and looking at the docs it says `toolbar` is not included in LeptonX Lite see below table on the commercial site.
> 
> ![image](https://user-images.githubusercontent.com/15242923/181482903-6d17b4f6-32dc-4a1e-95da-1670f558f58f.png)

I'm sorry, I've mistyped the package version it should be [**1.0.0-rc.1**](https://www.nuget.org/packages/Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite/1.0.0-rc.1). `content_toolbar` section has been added to the layout in the **v1.0.0-rc.1**.

![image](https://user-images.githubusercontent.com/43685404/181485199-98f1dc54-962a-4342-a799-61971f1425a3.png)

**Comment by vnetonline** [comment]
Tried that but it is dependant on 6.0.0.preview and doesn't play nice crashes the whole app

**Comment by EngincanV** [comment]
> Tried that but it is dependant on 6.0.0.preview and doesn't play nice crashes the whole app

Yes, v1.0.0-RC.1 is dependent on the nightly preview version of the ABP Framework. We'll fix this dependency problem with v1.0 for LeptonX Lite Theme.
