### ISSUE TITLE
Extending Organization Unit Entity

### ISSUE THREAD

**Issue by elijahgsh1010** [abpframework/abp#13456]
* ABP version: 5.2.2.
* User interface: Angular
* database provider: ef core
* Steps needed to **reproduce** the problem.
    - extend organization module entity
    - add new org unit (works fine)
    - edit org unit
    - save (error, extra properties not passed to server)
 
![image](https://user-images.githubusercontent.com/87971779/181487113-95bf98aa-069d-46ce-b9b4-acdefba551db.png)

![image](https://user-images.githubusercontent.com/87971779/181487685-f8b169d0-6f66-43bd-80be-fcf14aba4c89.png)

![image](https://user-images.githubusercontent.com/87971779/181487337-4d731557-f3eb-4de0-83ba-fdde5f446b2d.png)

![image](https://user-images.githubusercontent.com/87971779/181487819-cdab5c43-1fb9-4666-8f8d-ef87ff08eacf.png)

api/identity/organization-units/4fdbe5c1-3ea7-8f89-6578-3a053248d76b

![image](https://user-images.githubusercontent.com/87971779/181487980-26fa64ef-2b22-4ec2-a9de-7d0cb6c8a57e.png)

Creating new organization unit is totally fine, all the extra properties are there. Problem only occur for update.

Done the same for identity user and it works perfectly fine.

**Comment by berkansasmaz** [comment]
Hello, thanks for the report. 

I was able to reproduce the problem.

**Comment by mahmut-gundogdu** [comment]
The ABP Commercial edition is affected by the bug. It has been fixed. The final patches for 5.3 will have it.
