### ISSUE TITLE
Distributed Eventbus Infinite Loop

### ISSUE THREAD

**Issue by eneskoroglu** [abpframework/abp#13477]
* Your **ABP Framework version**.: 53.3
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: Angular
* Your database provider(EF Core/MongoDB): EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

We have an event handler (inbox) which contains business logic. When an error occured an infinite loop occurs (tries successive without any wait) and log size dramatically increases for only one error. As you know background job tries with a time delay with a limited count, after limit exceed job status changes to Failed. 

1. Is it possible for you, to add a system for Distributed Eventbus inbox like background system. 
2. Is it a mistake add business code to eventhandler? Should we get ETO message via eventhandler and enqueue it to background job?

**Comment by maliming** [comment]
hi 

Steps needed to reproduce the problem.

**Comment by eneskoroglu** [comment]
1. Create two seperate application and configure distributed event handler (RabbitMQ) with same exchange name.
2. Enable inbox and outbox event handler for both applications.
3. Publish an event from first application. 
4. On second application create an event handler and throw exception in it. It writes logs without any delay or trycount until server storage exceed.

**Comment by realLiangshiwei** [comment]
See: https://github.com/abpframework/abp/pull/11216#issuecomment-1006843999
