### ISSUE TITLE
ModalManager custom input focus

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#13488]
Hi,

I want to add focus to custom modal input not to first modal element.

I suggest to add skip custom class name [here ](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L100) like this:
`var $firstVisibleInput = _$modal.find('input:not([type=hidden]):not(.skipfocus):first')`

I also have my custom class for datepicker control, I can't use [datepicker class](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L104) to skip focus because it will initialize also the standard datepicker.

Other issue is select2 control focus.

Thanks

**Comment by maliming** [comment]
I think we can add an option `options.focusElement`.

**Comment by totpero** [comment]
@maliming this will be much better. `options.focusElement` can be element or function that return element.
