### ISSUE TITLE
Using a custom certificate for encryption/signing in OpenIdDict

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#13507]
* Your **ABP Framework version**. 6.0 rc1
* Your **User Interface** Blazor Server
* Your database provider EF Core

When I tried to deploy my solution to Azure App Services I received some access denied errors on application startup, which led me to https://github.com/openiddict/openiddict-core/issues/976.

I was able to turn off the developer signing credential using 

 PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>  
            options.AddDevelopmentEncryptionAndSigningCertificate = false);

I have a self-signed certificate I would like to use instead, but I can't seem to get it picked up. I tried       

PreConfigure<OpenIddictServerOptions>(options => options.SigningCredentials.Add(new SigningCredentials(KeyVaultHelper.GetSigningKey(),SecurityAlgorithms.RsaSha256)));

where KeyVaultHelper connects to a KV instance and gets the necessary items to build the RSA instance. However, I still receive this message at runtime:

InvalidOperationException: At least one encryption key must be registered in the OpenIddict server options.
Consider registering a certificate using 'services.AddOpenIddict().AddServer().AddEncryptionCertificate()' or 'services.AddOpenIddict().AddServer().AddDevelopmentEncryptionCertificate()' or call 'services.AddOpenIddict().AddServer().AddEphemeralEncryptionKey()' to use an ephemeral key.

What is the correct approach to specify an alternate certificate once the development certificate has been disabled?

**Comment by maliming** [comment]
hi

Try to add `EncryptionKey` together.

https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html

```cs
PreConfigure<OpenIddictServerBuilder>(builder =>
{
    builder.AddSigningKey(new SymmetricSecurityKey();
    builder.AddEncryptionKey(new SymmetricSecurityKey();
});
```

**Comment by jhulbertpmn** [comment]
> hi
> 
> Try to add `EncryptionKey` together.
> 
> https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html
> 
> ```cs
> PreConfigure<OpenIddictServerBuilder>(builder =>
> {
>     builder.AddSigningKey(new SymmetricSecurityKey();
>     builder.AddEncryptionKey(new SymmetricSecurityKey();
> });
> ```

Looks like that worked - thank you!

**Comment by lprichar** [comment]
Also for posterity Brian Meeker has an awesome write-up on this topic: [Setting Up ABP With OpenIddict on Azure App Services](https://brianmeeker.me/2022/08/29/setting-up-abp-with-openiddict-on-azure-app-services/)
