### ISSUE TITLE
LeptonX Lite Theme Source

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#13505]
* Your **ABP Framework version**. 6 RC1
* Your **User Interface** type Blazor Server
* Your database provider EF Core 

Is it possible to add source for the lepton x lite theme to a solution similar to what is described in https://community.abp.io/posts/customize-abp-blazor-application-ui-with-mudblazor-wscmpu3w, using the abp cli's add-package command? I explored downloading and adding it to my solution manually and replacing the package references with project references - and I may not be looking in the correct place - but I was not finding the source for the lepton x lite theme in the repo.

**Comment by maliming** [comment]
hi

https://github.com/volosoft/lepton-theme

**Comment by jhulbertpmn** [comment]
> hi
> 
> 
> 
> https://github.com/volosoft/lepton-theme

Thanks! I'm only seeing a readme file there in both branches though 
. Is there source to Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite available somewhere?

**Comment by BogdanJak** [comment]
And that's all about it? Inquiry from Blazor Server - link leads to angular - all clear.
Poor support. 
More answers will not be  :-(

**Comment by jhulbertpmn** [comment]
If the source for the lite version of this isn't available yet that is fine - just need to know one way or another for a project I'm starting

**Comment by EngincanV** [comment]
> If the source for the lite version of this isn't available yet that is fine - just need to know one way or another for a project I'm starting

Hi, we haven't provided the source code of the **LeptonX Lite Theme** yet. We are currently still working on it and trying to make it more mature. We'll try to make it available asap.

**Comment by enisn** [comment]
The LeptonX Lite source code isn't available right now. We're working on it but I can surely say, we can't publish the source code at least v1.0 stable.

LeptonX & LeptonXLite share same code-base. LeptonX Lite isn't a different theme than LeptonX. The lite one is only one style of the original theme. The original theme supports various different styles and features but the lite one hasn't most of the features and has only one style. 

Since they have a single code base, we can't share the source code. But, at least we can share MVC and blazor csharp libraries like Basic Theme in the next versions.

**Comment by jhulbertpmn** [comment]
> The LeptonX Lite source code isn't available right now. We're working on it but I can surely say, we can't publish the source code at least v1.0 stable.
> 
> LeptonX & LeptonXLite share same code-base. LeptonX Lite isn't a different theme than LeptonX. The lite one is only one style of the original theme. The original theme supports various different styles and features but the lite one hasn't most of the features and has only one style.
> 
> Since they have a single code base, we can't share the source code. But, at least we can share MVC and blazor csharp libraries like Basic Theme in the next versions.

Thanks! That clears up my question for now. Appreciate it.

**Comment by mohammadeunus** [comment]
do we have any update on it? need the leptonX Lite source code

**Comment by ziasam** [comment]
Is there any update on publishing the source code?

**Comment by enisn** [comment]
LeptonX Lite is available to download currently,

Have you tried the following command?
```
abp get-source Volo.Abp.LeptonXTheme.Lite --old
```

**Comment by mohammadeunus** [comment]
@enisn It works perfectly. Thanks a bunch!
