### ISSUE TITLE
Getting Started Tutorial: Web Application 

### ISSUE THREAD

**Issue by BartVHoey** [abpframework/abp#13502]
Hello,

When you start the tutorial Web Application Development:

Tutorials -> Web Application Development -> 1. Creating the Server Side you first send the user to the **getting started tutorial**
to create a new solution.

In Getting Started:
2. Creating a new solution 

In this section, the reader needs to run the following command to create a new solution

´´´bash
   abp new Acme.BookStore -u blazor --separate-identity-server
´´´

It creates a new solution with a separate identity server configured, but in the Web Application tutorial the reader needs 
a solution with identity server included not separated.  

Instead of the command above in the docs it should be

´´´bash
   abp new Acme.BookStore -u blazor
´´´

**Comment by maliming** [comment]
hi

> In this section, the reader needs to run the following command to create a new solution

Can you share the full URL?

**Comment by BartVHoey** [comment]
https://docs.abp.io/en/abp/latest/Getting-Started-Create-Solution?UI=Blazor&DB=EF&Tiered=Yes

**Comment by maliming** [comment]
hi

The no-tiered will be correct.

https://docs.abp.io/en/abp/latest/Getting-Started-Create-Solution?UI=Blazor&DB=EF&Tiered=No

**Comment by BartVHoey** [comment]
:-) Correct ... but I think for a new user it can be confusing ...  ciao
