### ISSUE TITLE
Allow ability to choose whether or not to generate MAUI project in ABP Suite

### ISSUE THREAD

**Issue by beriniwlew** [abpframework/abp#13529]
**ABP Commercial/Suite - 6.0.0 rc1**

There should be an option in ABP Suite to ignore the generation of the MAUI project, similar to how you can choose to create a React project, or not.

**Comment by enisn** [comment]
We are aware of the problem, it won't be included until you pass `-u maui` parameter like blazor. In the next release it'll be fixed

**Comment by enisn** [comment]
This problem has been solved with https://github.com/abpframework/abp/pull/13445
