### ISSUE TITLE
New Microservice running issue

### ISSUE THREAD

**Issue by Anuradha1999** [abpframework/abp#13525]
* Your **ABP Framework version**.
5.3.3

* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* MVC
* 
* Your database provider(EF Core/MongoDB)
*EF Core

*** Exception message and **stack trace** if available (check the logs).**

Javascript error
* Cannot read properties of undefined (reading 'orders') 
* TypeError: Cannot read properties of undefined (reading 'orders')

**Step to reproduce**

I have just created a new microservice and added its reference to my microservice project as well,.
I have also added a new entity for my service, I can see that service in left menu along with my newly added entity
now trying to add new record , but it is not opening the entry form
when I saw the screen carefully I found that Window.ProjectName.  this not loading my newly created microservice.

I am attaching my screenshot
You can see I have created the orderService, also added entity called order, when I clicked on -New Order , this button is doing nothing.
It is only show the productservice.

Can anyone help me in this regard?
![unknown](https://user-images.githubusercontent.com/18265044/182361498-6c330b61-e912-46c3-a902-a08c66257f64.png)

**Comment by maliming** [comment]
hi

Please create a question on https://support.abp.io/QA/Questions/New

Thanks
