### ISSUE TITLE
How do you configure TextTemplating to use Include files.

### ISSUE THREAD

**Issue by Joebeazelman** [abpframework/abp#13534]
There's no documentation on how to configure templates to use include files. Scriban's documentation says TemplateContext needs to implement ITemplateLoader:

[ITemplateLoader](https://github.com/scriban/scriban/blob/master/doc/runtime.md#runtime)

Does this framework support it, or does it require some serious workaround?

**Comment by maliming** [comment]
hi

How do you use `ITemplateLoader` without abp?

**Comment by Joebeazelman** [comment]
I prefer to use apb to load the include file. I looked through the source and it doesn't implement ITemplateLoader anywhere. Does the framework support **include** through other means, or is it not supported at all? 

How and where would I implement ITemplateLoader into apb? I could implement it in isolation, but it would be better to integrate it with apb since it already has the file handling infrastructure already in place.

**Comment by maliming** [comment]
hi

Do you have an example that using the `ITemplateLoader `?
