### ISSUE TITLE
Angular InternalStore's subscribe callback fires repeatedly.

### ISSUE THREAD

**Issue by qq362220083** [abpframework/abp#13533]
* abp Angular UI version: 5.3.2

When using the `sliceState` and `subscribe` methods of `InternalStore`, using the `patch` method in the `subscribe` method to modify another property of itself will cause the subscribe method of the other property to be called twice, and 2nd, **the value is old**.

**test-state.component.ts:**
``` ts
import { InternalStore } from '@abp/ng.core';
import { Component } from '@angular/core';

type TempState = {
  prop1: string,
  prop2: string,
}

@Component({
  selector: 'app-test',
  template: `
    <button type="button" (click)="testClick()">TestState</button>
  `,
})
export class TestStateComponent {

  private state = new InternalStore({} as TempState);

  constructor() {
    this.state.sliceState(x => x.prop1)
      .subscribe(prop1 => {
        this.state.patch({ prop2: `${(new Date()).toString()}` });
      });
    this.state.sliceState(x => x.prop2)
      .subscribe(prop2 => {
        console.log(`prop2=${prop2}`);
      });
  }

  testClick() {
    this.state.patch({ prop1: 'prop1' });
  }

}
```

Initialize, the output like is:
```
prop2=Wed Aug 03 2022 11:28:26 GMT+0800 (China Standard Time)
```
After clicking the button, the output like is:
```
prop2=Wed Aug 03 2022 11:28:38 GMT+0800 (China Standard Time)
prop2=Wed Aug 03 2022 11:28:26 GMT+0800 (China Standard Time)
```

**Why is the subscribe callback fired twice after the button is clicked?**

Please help us, thanks.

**Comment by qq362220083** [comment]
:worried:Please help me.

**Comment by mahmut-gundogdu** [comment]
I have produce the issue. InternalStorage is simple state manager tool. we are using only simple tasks. I am looking "why?" but  flux way says. your reducer make change one time per action. 
![image](https://user-images.githubusercontent.com/2217899/195125547-85441b11-ffc8-4ca0-b008-dc25c26d4d25.png)

I would do the task like that 
 
![image](https://user-images.githubusercontent.com/2217899/195126870-60da28b4-372c-454e-a351-bde8b0aa0b68.png)

**Comment by mahmut-gundogdu** [comment]
but the main reason is the order of subscriptions.  if you change like that, It works as expected.
![image](https://user-images.githubusercontent.com/2217899/195144582-5ee22f1b-b277-45f8-8044-9d75c78ab4ca.png)
