### ISSUE TITLE
When will the final version 6.0.0 OR 7.0.0 arrive?

### ISSUE THREAD

**Issue by vioKamran** [abpframework/abp#13531]
When will the final version 6.0.0 OR 7.0.0 arrive?
Please update as soon as possible

**Comment by EngincanV** [comment]
The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.

**Comment by vioKamran** [comment]
> The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.

Thankyou

**Comment by vioKamran** [comment]
> The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.

Hello
I have a question for you.
Which main framework are used under the supervision of all projects?
  "ASP.NET Boilerplate" under the main ABP framework
or "ABP" under the ASP.NET Boilerplate main framework.

Which is the main and more complete framework?
Please answer .

**Comment by vioKamran** [comment]
> The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.

Hello
I have a question for you.
Which main framework are used under the supervision of all projects?
"ASP.NET Boilerplate" under the main ABP framework OR "ABP" under the ASP.NET Boilerplate main framework.

Which is the main and more complete framework?
Please answer .

**Comment by EngincanV** [comment]
> > The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.
> 
> Hello I have a question for you. Which main framework are used under the supervision of all projects? "ASP.NET Boilerplate" under the main ABP framework OR "ABP" under the ASP.NET Boilerplate main framework.
> 
> Which is the main and more complete framework? Please answer .

Hi, please follow [this issue](https://github.com/abpframework/abp/issues/13629#issuecomment-1210485195) for a possible answer.

**Comment by enisn** [comment]
Hi @vioKamran 

You can follow ABP Milestones for release dates:

https://github.com/abpframework/abp/milestones

_preview milestones represents **rc**(release candidate) versions and **final** milestones represents stable versions_

**Comment by vioKamran** [comment]
> > > The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.
> > 
> > 
> > Hello I have a question for you. Which main framework are used under the supervision of all projects? "ASP.NET Boilerplate" under the main ABP framework OR "ABP" under the ASP.NET Boilerplate main framework.
> > Which is the main and more complete framework? Please answer .
> 
> Hi, please follow [this issue](https://github.com/abpframework/abp/issues/13629#issuecomment-1210485195) for a possible answer.

Thankyou

**Comment by vioKamran** [comment]
> Hi @vioKamran
> 
> You can follow ABP Milestones for release dates:
> 
> https://github.com/abpframework/abp/milestones
> 
> _preview milestones represents **rc**(release candidate) versions and **final** milestones represents stable versions_

Thankyou

**Comment by vioKamran** [comment]
> The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.

Hello
**Well, today is September 6.**
What time do you update today?

**Comment by EngincanV** [comment]
> > The planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version is September 06, 2022.
> 
> Hello **Well, today is September 6.** What time do you update today?

Hi, the planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version changed to **September 13, 2022**.
