### ISSUE TITLE
Abp Suite: allow to set 'presision' and 'scale' to the propery of type "Decimal".

### ISSUE THREAD

**Issue by RobersonLuo** [abpframework/abp#13544]
### Issue: 
It seems that I can not set the 'precision' and 'scale' for the property of type 'Decimal' in the UI when using Abp Suite:

DECIMAL [ ( precision [ , scale ] ) ]

![image](https://user-images.githubusercontent.com/7013492/182551388-6c4b2484-bedc-40d6-8d2a-927c230023ad.png)

Now I need to set it in code like below and it's not convenient!
**modelBuilder.Entity<PayPay>().Property(p => p.Money).HasColumnType("decimal(18,3)");**

Please fix it.
Thanks a lot.

**Comment by yekalkan** [comment]
Hi @RobersonLuo 

I've created an internal issue. So i'm closing this one.
