### ISSUE TITLE
*.Web Can't run

### ISSUE THREAD

**Issue by thk-liu** [abpframework/abp#1354]
When I started learning ABP 0.18，Using the command "$ dotnet run "under mac, you receive the following error:
Application startup exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)

Among them, *. HttpApi. Host, *. Identity Server successfully run；
What should I do?

**Comment by maliming** [comment]
@thk-liu 
Is it related to this?
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos

**Comment by thk-liu** [comment]
tks,i geted it

**Comment by ClementeGao** [comment]
> tks,i geted it

Have you solved it?
