### ISSUE TITLE
What is the recommended version of NodeJS for ABP? Still v14?

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#13550]
According to the documentation, ABP requires either NodeJS v12 (which I believe is no longer supported) or v14 (which is supported for a few months more). Is this still true or is the documentation out of date? Is it mandatory to have NodeJS v14 installed as of today to use ABP and it won't work with v16 nor v18 only?

Is it safe to have multiple versions of NodeJS installed at the same time on Windows as other tooling might need a more recent version of NodeJS? I know it is supposed to work but not sure if it actually does. 

Finally, are there any differences here when it comes to ABP and ABP Commercial as we have found in the past that the documentation seems to focus mainly on the none commercial version and what's in there might not necessarily be true for ABP Commercial, or at least solutions generated by ABP Suite which often lag behind?

Since NodeJS v12 isn't supported anymore AFAIK, it should probably be removed from the docs altogether. 

Thanks.

**Comment by MichelZ** [comment]
#13053

**Comment by improwise** [comment]
This problem seems like it still remains.

**Comment by improwise** [comment]
@realLiangshiwei Please note that this needs to be updated for the Commercial documentation as well which still seem to have v12 and v14.

**Comment by realLiangshiwei** [comment]
@improwise 
we will. thanks.
