### ISSUE TITLE
After switching tenants, return to the host and log in to admin, and "response status code does not indicate success: 401 (unauthorized)" appears

### ISSUE THREAD

**Issue by EricChenZW** [abpframework/abp#13567]
After switching tenants, return to the host and log in to admin, and "response status code does not indicate success: 401 (unauthorized)" appears

![image](https://user-images.githubusercontent.com/37535753/182890444-5d214c0a-7583-43b6-936e-b93442665d98.png)

User Interface type: MVC
database provider:  EF Core
ABP Framework version: 6.0.0-rc.1

1. Download template
2. Ru
3. Login
4. Create a tenant
5. Exit host account
6. Switch to the tenant and log in with the tenant account
7. Exit tenant account
8. Switch to the host and log in with the host account
9. Something went wrong

**Comment by maliming** [comment]
I can't reproduce.

**Comment by maliming** [comment]
Move to https://github.com/abpframework/abp/issues/13574
