### ISSUE TITLE
HTTP 400 on connect/token when hosting Blazor in HttpApi.Host

### ISSUE THREAD

**Issue by BenWhite27** [abpframework/abp#13568]
* ABP 6.0.0-rc.1
* Blazor Web Assembly
* EFCore
* OpenIddict

After modifying the start-up template to host/deploy the .Blazor project in the .HttpApi.Host web server I receive the following error after logging in on the Blazor UI.
`There was an error trying to log you in: ''`.  The F12 browser tools indicate an http 400 response for the connect/token controller.
Upon looking at the logs for HttpApi.Host I can see the following
```
[23:13:01 INF] Route matched with {action = "Handle", controller = "Token", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] HandleAsync() on controller Volo.Abp.OpenIddict.Controllers.TokenController (Volo.Abp.OpenIddict.AspNetCore).
[23:13:01 ERR] The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
[23:13:01 INF] Authorization failed for the request at filter 'Volo.Abp.AspNetCore.Mvc.AntiForgery.AbpAutoValidateAntiforgeryTokenAuthorizationFilter'.
[23:13:01 INF] Executing StatusCodeResult, setting HTTP status code 400
```

Should the token controller skip CSRF checks?  Or is there something else I'm missing.  Hosting/Deploying the Blazor project in the HttpApi.Host project worked fine in v5.3.3.

For completeness I followed the following steps to modify hosting of the Blazor project.
**Host Project**
* Add project reference to Blazor project.
* Add Nuget Package reference to `Microsoft.AspNetCore.Components.WebAssembly.Server`
* Remove the HomeController
* add `app.UseBlazorFrameworkFiles();` and `app.UseConfiguredEndpoints(config => config.MapFallbackToFile("index.html"));`to Host Module File.
* Updated appsettings.json CorsOrigins and RedirectAllowedUrls with new Host port numbers.

**Blazor Project**
* Updated appsettings.json with new SelfUrl

**Misc**
* Updated database OpenIddictApplications table for Blazor row with host port numbers.
* Updated dbmigrator appsettings.json etc.

**Comment by maliming** [comment]
This seems to be related to request cookies.

**Comment by BenWhite27** [comment]
Perhaps, this is a little above my head, but in case it helps, here's a screen snip of the request headers for the POST to connect/token.
![image](https://user-images.githubusercontent.com/7678016/183082651-2f0a0940-f1d6-4fae-875c-8f6520021d59.png)

It would appear that the 3 cookies are being sent along with the request including one for CSRF/XSRF but the error in the logs above would indicate `AbpAutoValidateAntiforgeryTokenAuthorizationFilter` is only expecting a dedicated header or form field in the POST.

EDIT: I migrated from OpenIddict to IdentityServer by following reverse of the migration guide and can confirm that login now works again so whatever causes this issue seems to be directly related to the OpenIddict modules.
