### ISSUE TITLE
OpenIddict user-interface: Redirect Uris do not change

### ISSUE THREAD

**Issue by merijng** [abpframework/abp#13563]
**ABP Framework version** 6.0.0-rc.1
**User Interface**: MVC
EF Core

**Reproduction steps:**
- `dotnet tool install Volo.Abp.Cli -g --version 6.0.0-rc.1`
- `abp new BookStore --preview`
- Run migrator & Open application & login with admin user
- Go to Administration => OpenId => Applications => Edit a application, Public_Tiered for example
- Change **Redirect Uris**
- Save
- Edit once again and see **it did not change at all**
- no errors in Audit log, or the /Logs folder

**Comment by maliming** [comment]
hi

This will be fixed in rc2.
