### ISSUE TITLE
There are some configurations in the generated template that are not used.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1356]
Consider removing, or there are other better ways to solve problems in different types of templates.

**Comment by maliming** [comment]
In fact, mainly `appsettings.json` (and possibly `Startup.cs`) will have some changes.

We can consider creating different configuration files.
Such as:
`appsettings.default.json`
`appsettings.tiered.json`
`appsettings.noui.json`

First perform the configuration file replacement, then replace the port.

**Comment by hikalkan** [comment]
Can you write details. Which configuration?

**Comment by maliming** [comment]
It seems that this problem does not exist after 0.19, I will confirm it.
