### ISSUE TITLE
Support EditorConfig for consistent and clean code

### ISSUE THREAD

**Issue by Xeevis** [abpframework/abp#1357]
There are lots of minor problems in ABP when it comes to whitespace and coding style consistency. This would easily be solved by including **.editorconfig** file which **automatically configures and overrides formatting and refactoring tools** in IDEs including native support in Visual Studio which extends it to control just about everything for everyone working on the solution.

DOCS: [Create portable, custom editor settings with EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options)

For baseline we can use .NET generic [RehanSaeed's EditorConfig](https://github.com/RehanSaeed/EditorConfig) which is consistent with StyleCop default styles and .NET Framework Design Guideline's Naming Guide. Can also be easily switched to SX rules to enforce underscored member fields or it can remove redundant qualifiers, insert/remove trailing new line etc.

- [ ] Create strict & consistent .editorconfig that fits ABP coding style
- [ ] Add this .editorconfig to all solutions
- [ ] Cleanup code using in-built Visual Studio 2019 code cleanup and refactor tools

In the long run this should also reduce whitespace noise in commits:

![image](https://user-images.githubusercontent.com/5835044/60016340-3aee7180-9686-11e9-920a-efc0de868abd.png)

**Comment by hikalkan** [comment]
Thanks @Xeevis for the suggestion.
