### ISSUE TITLE
Docs module improvements discussion

### ISSUE THREAD

**Issue by malikmasis** [abpframework/abp#13585]
Should we change the documentation filter according to the user filter page?
![image](https://user-images.githubusercontent.com/13196534/183088310-9c35d390-02e3-4888-8402-d4b6dfd478c6.png)
![image](https://user-images.githubusercontent.com/13196534/183088366-f2c27752-6d9f-4086-86b1-6deca2ddb312.png)

**Comment by ebicoglu** [comment]
![image](https://user-images.githubusercontent.com/9526587/185319526-8fa55aba-b578-4804-b57f-2bd1c4762e62.png)
