### ISSUE TITLE
Manually generated ConcurrencyTimestamp

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#13588]
Is there built-in mechanism in abp to generate ConcurrencyTimestamp value for database?
I need to generate it, because in one scenario we have sql string for dbContext.Database.FromSqlInteepolated("...");

Thank you.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/AggregateRoot.cs#L22

**Comment by leonkosak** [comment]
Thank you. :)
