### ISSUE TITLE
Cannot resolve symbol '__builder' in ExtensionProperties.razor

### ISSUE THREAD

**Issue by beriniwlew** [abpframework/abp#13596]
Check the ExtensionProperties.razor file in the Volo.Abp.BlazoriseUI project.

`__builder` is incorrectly referenced, it should be `builder`

**Comment by hikalkan** [comment]
@realLiangshiwei can you check this please. Add `bug` label if that's true.

**Comment by beriniwlew** [comment]
https://github.com/abpframework/abp/commit/7597f4203d6bacd9ca933f9ef8f927a647979924

**Comment by realLiangshiwei** [comment]
Did you run the `dotnet build` command when change to `builder`

![image](https://user-images.githubusercontent.com/16813853/183328707-e399bbc5-21b2-418e-b264-e48b6a05c394.png)
