### ISSUE TITLE
Permissions Modal No Scroll - Can't click Save.

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#1359]
In v .18, similar to earlier versions, the permissions modal window does not expand to include all permission groups.  The permissions just run off the bottom of the modal window.  There is no scroll either, which appears to have been an issue before.  You also cannot click the Cancel or Save button.  The only way to exit the screen is to click the upper right hand X button.

**Comment by maliming** [comment]
It seems that the 0.18.0 version has been resolved.
see: https://github.com/abpframework/abp/pull/1308#issuecomment-503430612 https://github.com/abpframework/abp/pull/1310

Are you using a new template of 0.18? Can you share screenshots?

**Comment by djlaney3** [comment]
No, my project was built on the old templates, just updated the underlying bits to .18.
![image](https://user-images.githubusercontent.com/18035126/60023893-5a70a480-965c-11e9-8ad1-f2bd5e3e2daa.png)

**Comment by maliming** [comment]
Try upgrading the `@abp/aspnetcore.mvc.ui.theme.basic@0.6.6` package.

**Comment by djlaney3** [comment]
How do I do that?  It appears to be updated in my solution, but the result is the same.  I updated the package.json file manually, and removed the package-lock.json file.  All npm issues resolved and it shows 0.6.6 as the version, but results haven't changed.

**Comment by maliming** [comment]
Try to execute the `gulp `command after the upgrade.

**Comment by djlaney3** [comment]
I don't know how to use gulp correctly, but I copied the /libs contents from a new template into my project, and that worked.
