### ISSUE TITLE
How to avoid generate so many language resource folders after publish

### ISSUE THREAD

**Issue by gaojianzhuang** [abpframework/abp#13592]
### GitHub Issues

After publish the site, we can get so many resource folders, how to avoid generate so many language resource folders.

If you're creating a bug/problem report, please include followings:

* Version: 5.3.2.
* Asp.net Core Razor Page
* EF Core

![image](https://user-images.githubusercontent.com/1866009/183287602-1fc9e754-71db-4794-bfc9-db74c0a0b7d6.png)

**Comment by JadynWong** [comment]
https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#satelliteresourcelanguages
https://stackoverflow.com/questions/60330650/asp-net-core-exclude-published-language-directories-other-than-english

**Comment by gaojianzhuang** [comment]
> https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#satelliteresourcelanguages https://stackoverflow.com/questions/60330650/asp-net-core-exclude-published-language-directories-other-than-english

I have already added it in my project file, but not work.
```
<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<RootNamespace>XXX.Web</RootNamespace>
		<AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
		<PreserveCompilationReferences>true</PreserveCompilationReferences>
		<SatelliteResourceLanguages>en-US;zh-CN</SatelliteResourceLanguages>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>
```
