### ISSUE TITLE
CreatorId and TenantId not autofilled on creation in tenants

### ISSUE THREAD

**Issue by Silthus** [abpframework/abp#1360]
I followed the [tutorial](https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I) and created my first own `FullAuditedAggregateRoot` entity named `Parkingplace`. The entity also implements `IMultiTenant` to provide multi tenant support.

```cs
public class Parkingplace : FullAuditedAggregateRoot<Guid>, IMultiTenant
    {
        public const int MaxParkingplaceName = 128;

        public Guid? TenantId { get; set; }

        public string Name { get; protected set; }

        public ParkingplaceType Type { get; protected set; }

        public Guid OwnerId { get; protected set; }

        protected Parkingplace()
        {
        }

        public Parkingplace(string name, ParkingplaceType type)
        {
            Name = name;
            Type = type;
        }
    }
```

```cs
        public static void ConfigureParkSucht(this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            /* Configure your own tables/entities inside here */
            builder.Entity<Parkingplace>(b =>
            {
                b.ToTable(ParkSuchtConsts.DbTablePrefix + "Parkingplaces", ParkSuchtConsts.DbSchema);
                b.ConfigureFullAuditedAggregateRoot();
                b.ConfigureMultiTenant();

                b.Property(parkingplace => parkingplace.Name)
                    .IsRequired()
                    .HasMaxLength(Parkingplace.MaxParkingplaceName);
                b.HasIndex(parkingplace => parkingplace.Name);
            });
        }
```

I went ahead and created the matching Dtos and an AppService for the entity. But I have the problem that the `CreatorId` and `TenantId` are not set automatically when I create the entity in a tenant.

If I use the host (default) tenant the `CreatorId` ist set correctly. The `TenantId` remains `null` which is expected.

![image](https://user-images.githubusercontent.com/755327/60023939-1d75d380-9697-11e9-98f3-1126eb4afc08.png)

Do I need to configure the entity somewhere else?

**Comment by maliming** [comment]
You need to manually set the TenantId for your entity.

**Comment by Silthus** [comment]
Ok, but why?

There is code in the `AsyncCrudAppService` base class that should try to set the `TenantId`: https://github.com/abpframework/abp/blob/c621e7a7a42028ac79c8c21d51b730d20eaeeaca/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/AsyncCrudAppService.cs#L112

And here the `TryToSetTenantId`: https://github.com/abpframework/abp/blob/c621e7a7a42028ac79c8c21d51b730d20eaeeaca/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/CrudAppServiceBase.cs#L166

For debugging purposes I also checked if CurrentTenant is set and if the conditions inside the `TryToSetTenantId` are met. And to me it seems like everything should work and the tenant id should be set.

But it isn't.

**Comment by hikalkan** [comment]
Did you inherit from AsyncCrudAppService.cs? If not, you should set it yourself. If you inherited, try to override TryToSetTenantId and debug to see it.

````csharp
protected override void TryToSetTenantId(TEntity entity)
        {
            var tenantId = CurrentTenant.Id;

            if (!tenantId.HasValue)
            {
                return;
            }

            var propertyInfo = entity.GetType().GetProperty(nameof(IMultiTenant.TenantId));

            if (propertyInfo != null && propertyInfo.GetSetMethod() != null)
            {
                propertyInfo.SetValue(entity, tenantId, null);
            }
        }

````

**Comment by Silthus** [comment]
I found the issue:

`if (entity is IMultiTenant && !HasTenantIdProperty(entity))` should be `if (entity is IMultiTenant && HasTenantIdProperty(entity))`

If it is ok I will create a PR with a test checking the bug and then fix it.

**Comment by maliming** [comment]
@Silthus You are correct, welcome to contribute PR.
