### ISSUE TITLE
Couldn't Create MAUI Template (template with the name "maui" not found)

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#13619]
![image](https://user-images.githubusercontent.com/43685404/183821016-8b9f17bd-0a2c-4b6b-84ea-740f43e6b7cd.png)

**Comment by realLiangshiwei** [comment]
@yekalkan  I think we should add the MAUI template to abp.io platform right?

**Comment by yekalkan** [comment]
>  I think we should add the MAUI template to abp.io platform right?

right.

**Comment by ebicoglu** [comment]
I added the template record to the live database manually.
![image](https://user-images.githubusercontent.com/9526587/184828037-4957d49b-4e7b-4ce1-8f93-7bf1863ea69c.png)
