### ISSUE TITLE
Enum is not a supported dictionary key using converter of type 'Volo.Abp.Json.SystemTextJson.JsonConverters.AbpStringToEnumConverter

### ISSUE THREAD

**Issue by 2501272126** [abpframework/abp#13615]
I know this is a bug and it resolved.
However, it has not been released yet.
I want to know how to use it in 5.3.3
such as replace Volo.Abp.Json.SystemTextJson.JsonConverters.AbpStringToEnumConverter or other methods

Thanks !!

**Comment by maliming** [comment]
Configure the options
https://github.com/abpframework/abp/blob/c620c3c4db4ba40357d24761a583985834755525/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Json/AbpJsonOptionsSetup.cs

https://github.com/abpframework/abp/blob/c620c3c4db4ba40357d24761a583985834755525/framework/src/Volo.Abp.Json/Volo/Abp/Json/SystemTextJson/AbpSystemTextJsonSerializerOptionsSetup.cs
