### ISSUE TITLE
Allow to extend AbpPermissionManagement js logic

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#13612]
Hi,

I want to extend [permission-management-modal.js](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Web/Pages/AbpPermissionManagement/permission-management-modal.js) and add check all children when parent is checked. 
Now when I check child the parent is checked and when I uncheck parent all children.
It will be helpful if you can trigger event like this:
`abp.event.trigger("abp.module.permission-management.onCheckChange", { checked: $checkBox.is(':checked'), tab: $tab, checkbox: $checkBox });` before [this line](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Web/Pages/AbpPermissionManagement/permission-management-modal.js#L208);
Or if is other solution but not override all module in my project :).

Thanks.

**Comment by totpero** [comment]
Hi,
Any update on this?

Thanks

**Comment by realLiangshiwei** [comment]
See: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#overriding-static-resources
