### ISSUE TITLE
`abp clean` shouldn't delete bin folders under `node_modules` folder

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#13614]
We can completely ignore `node_modules` folder or we can delete entire `node_modules` folder with `abp clean` command

**Comment by maliming** [comment]
How to reproduce?

https://github.com/abpframework/abp/blob/db05c4a4a37825ba56acbf53331f83a5076cd8a4/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/CleanCommand.cs#L31

**Comment by enisn** [comment]
Ok, it doesn't delete. We'd seen it wrong with @muhammedaltug
