### ISSUE TITLE
widget:depended js\css on modal

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#13623]
- ABP Framework version: 5.2.0

- User Interface: MVC

[Widgets: depended JS not loaded in popups](https://github.com/abpframework/abp/issues/5605)
how load widget depended js\css on modal?
``` csharp
[Widget(ScriptFiles = new[] { "/Pages/Components/Demo/default.js" })] // Invalid
```

**Comment by snowchenlei** [comment]
https://github.com/abpframework/abp/issues/5605

**Comment by dlboutwe** [comment]
I am also running into this issue in 5.3.4.

**Comment by EngincanV** [comment]
@snowchenlei Can you ensure the `default.js` is marked as embedded resource?

**Comment by snowchenlei** [comment]
> @snowchenlei Can you ensure the `default.js` is marked as embedded resource?

how set?*.js file attribute set?
If yes, I tried, but it still doesn't work

**Comment by EngincanV** [comment]
> > @snowchenlei Can you ensure the `default.js` is marked as embedded resource?
> 
> how set?*.js file attribute set? If yes, I tried, but it still doesn't work

You can mark your js file as embedded resource as follow (add the below code block to your *.csproj file):

```xml
<ItemGroup>
    <EmbeddedResource Include="Pages\Components\Demo\Default.js" />
</ItemGroup>
```

**Comment by snowchenlei** [comment]
> > > @snowchenlei Can you ensure the `default.js` is marked as embedded resource?
> > 
> > 
> > how set?*.js file attribute set? If yes, I tried, but it still doesn't work
> 
> You can mark your js file as embedded resource as follow (add the below code block to your *.csproj file):
> 
> ```
> <ItemGroup>
>     <EmbeddedResource Include="Pages\Components\Demo\Default.js" />
> </ItemGroup>
> ```
 I tried, but it still doesn't work
[modal-widget.zip](https://github.com/abpframework/abp/files/9643619/modal-widget.zip)

**Comment by dlboutwe** [comment]
My use case was: I was creating a modal via the modalManager system from a separated CSHTML file, and my widget code was invoked on the modals' specific CSHTML file. According to this, you need to include the scripts for the modal on the page where you define and open the modal, so I had to find a way to surface the component JS to that page: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Modals#modals-with-script-files.


I ended up creating a bundle (https://docs.abp.io/en/abp/latest/UI/AspNetCore/Bundling-Minification) and then adding an `<abp-script` tag to the main index page where I am creating and opening the Modal and then everything worked for me as expected.

```
@section styles{
    <abp-style-bundle name="MyWidgetBundle" />
}
@section scripts {
    <abp-script-bundle name="MyWidgetBundle" />    
}
```
