### ISSUE TITLE
Review OpenIddict Module Documentation

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#13625]
@maliming Can you review the [OpenIddict Module](https://docs.abp.io/en/abp/6.0/Modules/OpenIddict) documentation?

I think we can add the "how to install" section to the document and also add the links of migration guides (IdentityServer to OpenIddict docs) to help developers to easily reach the migrations guides..

**Comment by maliming** [comment]
Migration guides exist in the sub section.

![image](https://user-images.githubusercontent.com/6908465/184049894-c3c82516-94eb-47b5-b8c2-8d9e3224c9d3.png)
