### ISSUE TITLE
DataExporting Excel Module  - Feature

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#13628]
Hi,

Related to this #6987 I already have implemented Excel data exporting module for this excel providers: [Npoi](https://github.com/nissl-lab/npoi), [EPPlus](https://github.com/JanKallman/EPPlus) and [ClosedXML](https://github.com/ClosedXML/ClosedXML)

Can I create pull request to add this feature to the abp framework?
Thanks

**Comment by XuJin186** [comment]
Can PR, and then wait for the official reply of ABP
