### ISSUE TITLE
Which is the main and more complete framework?

### ISSUE THREAD

**Issue by vioKamran** [abpframework/abp#13629]
Hello
I have a question for you.
Which main framework are used under the supervision of all projects?
"ASP.NET Boilerplate" under the main ABP framework OR "ABP" under the ASP.NET Boilerplate main framework.

Which is the main and more complete framework?
Please answer .

**Comment by hikalkan** [comment]
I would suggest the ABP Framework as the main framework. The team is mostly focused on it.

**Comment by vioKamran** [comment]
> I would suggest the ABP Framework as the main framework. The team is mostly focused on it.

Thankyou 😊🙏

**Comment by ebicoglu** [comment]
it's like asking .NET Framework 4x or .NET Core.
go with the latest one 👉 ABP Framework

**Comment by vioKamran** [comment]
> it's like asking .NET Framework 4x or .NET Core. go with the latest one 👉 ABP Framework

Yes absolutely right .
Thanks 🙏
