### ISSUE TITLE
How to show 'Linked accounts' modal of ABP commercial

### ISSUE THREAD

**Issue by jalalh14** [abpframework/abp#13632]
I use ABP commercial framework, but in front side I use my own template and menu, so I want to put its linked account menu in my menu. The problem here is that when I click on 'Linked accounts' menu, it shows a modal and does not route to another address. If it was routing, I could use its route but I must show that modal, but I could not see anything in angular code about that menu. So how can I show that 'Linked accouts' modal in my custom template?
abp version 5.3.3
ng version 14.0.3

![abp linked acc](https://user-images.githubusercontent.com/18516979/183902600-88bb52f6-993e-4a1b-b190-effd56ced849.JPG)

![abp linked acc1](https://user-images.githubusercontent.com/18516979/183902627-219e9d17-2faa-42b1-a064-f60f930c2d2d.JPG)

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io/QA/Questions/New for commercial product.

Thanks.

**Comment by jalalh14** [comment]
> hi
> 
> Please get help on https://support.abp.io/QA/Questions/New for commercial product.
> 
> Thanks.

https://support.abp.io/QA/Questions/3553/How-to-show-%27Linked-accounts%27-modal-of-ABP-commercial-in-my-custom-template

I asked in abp commercial panel but after passing 7 days, there is no answer! So what is the problem? Should be a commercial project like this?!
