### ISSUE TITLE
The PermissionValueProviderManager class is ISingletonDependency, this will cause a concurrency error.

### ISSUE THREAD

**Issue by animitta** [abpframework/abp#13639]
- Issue references
    - #7275
    - #9404
    - #11088
- Source code
https://github.com/abpframework/abp/blob/030702e266dc372c07af10a9ca077ab664b3ca92/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/Permissions/PermissionValueProviderManager.cs

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by animitta** [comment]
@maliming All versions. I test on 5.3.3 version. This is test repository: [Test Repository](https://github.com/animitta/abp-bug-tester)

**Comment by maliming** [comment]
Please find a way to reproduce that in unit test.

**Comment by animitta** [comment]
Okay, I'll do it this weekend.

**Comment by animitta** [comment]
@maliming It is almost impossible to reproduce the problem in unit test, it requires integration testing. I used the source link to debug the ABP framework modules, but I didn't succeed. I updated the before test repository. I can only prove that all type IPermissionValueProvider are singleton, there will be concurrency issues.
