### ISSUE TITLE
Best Net core framework

### ISSUE THREAD

**Issue by vioKamran** [abpframework/abp#13634]
it's very interesting .
I searched the word "The best Net core framework" on the Google site, and the result showed none of the frameworks and only the ABP framework.

It is very strange and I feel that this ABP framework is the best in the world and six million people downloaded it on GitHup.

God bless all dear teams.
I hope they will develop this framework in the ERP phase.

Thanyou dear teams 😊🙏

**Comment by EngincanV** [comment]
Thanks @vioKamran :pray:

**Comment by vioKamran** [comment]
> Thanks @vioKamran 🙏

you're welcome
God bless all dear teams.
I like to work with your teams, not remotely.

**Comment by vioKamran** [comment]
> Thanks @vioKamran 🙏

I hope this framework will be the best in the world like [odoo](https://www.odoo.com/) .
