### ISSUE TITLE
How to inject AppService in BackgroundWorker?

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#13643]

**Comment by animitta** [comment]
Don't do it, using context.ServiceProvider.GetRequiredService, and manage UnitOfWork manually.

**Comment by animitta** [comment]
@weiwxg Don't do it. using context.ServiceProvider.GetRequiredService, and manage UnitOfWork manually.

**Comment by weiwxg** [comment]
> 

But i can't get instance with `ServiceProvider.GetRequiredService`

**Comment by animitta** [comment]
using AsyncPeriodicBackgroundWorkerBase
```csharp
    public class CleanRealTimeWork : AsyncPeriodicBackgroundWorkerBase
    {
        public CleanRealTimeWork(AbpAsyncTimer timer, IServiceScopeFactory serviceScopeFactory)
            : base(timer, serviceScopeFactory)
        {
            Timer.Period = 30.ToMilliseconds();
        }

        protected override async Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
        {
                var repository = workerContext.ServiceProvider
                    .GetRequiredService<IDataHistoryRepository>();
        }
}
```

**Comment by weiwxg** [comment]
> using AsyncPeriodicBackgroundWorkerBase
> 
> ```cs
>     public class CleanRealTimeWork : AsyncPeriodicBackgroundWorkerBase
>     {
>         public CleanRealTimeWork(AbpAsyncTimer timer, IServiceScopeFactory serviceScopeFactory)
>             : base(timer, serviceScopeFactory)
>         {
>             Timer.Period = 30.ToMilliseconds();
>         }
> 
>         protected override async Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
>         {
>                 var repository = workerContext.ServiceProvider
>                     .GetRequiredService<IDataHistoryRepository>();
>         }
> }
> ```

If the worker is not a period task, such as consume kafka message, how to specify `Timer.Period`?

**Comment by animitta** [comment]
@weiwxg using BackgroundJob, not BackgroundWorker, and Timer. Period is modifiable.
