### ISSUE TITLE
I want to rewrite RabbitMqDistributedEventBus, because I need to put the durable set to false by default.

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#13668]
1, I want to rewrite RabbitMqDistributedEventBus, because I need to put the durable set to false by default.

2, I try to rewrite RabbitMqDistributedEventBus Initialize, but Consumer is private, what should I do?

@realLiangshiwei

**Comment by realLiangshiwei** [comment]
You can refer this: https://support.abp.io/QA/Questions/3412/Kafka-subscribe-into-multiple-topics#answer-7b978c65-e340-67e9-dcd9-3a0508b832b4
