### ISSUE TITLE
Actions subscribed to ServiceCollectionRegistrationActionExtensions.OnRegistred are not invoked.

### ISSUE THREAD

**Issue by rwoznicki** [abpframework/abp#1367]
Actions subscribed to ServiceCollectionRegistrationActionExtensions.OnRegistred are not invoked in case of MVC app. It works correctly for console app because it uses empty service collection for creation abp application.

In order to subscribe actions we use following in one of our modules:
```
 public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            var localHandlers = new List<Type>();
            var distributedHandlers = new List<Type>();

            context.Services.OnRegistred(onServiceRegistredContext =>
            {
                if (ReflectionHelper.IsAssignableToGenericType(onServiceRegistredContext.ImplementationType, typeof(ILocalEventHandler<>)))
                {
                    localHandlers.AddIfNotContains(onServiceRegistredContext.ImplementationType);
                }
                else if (ReflectionHelper.IsAssignableToGenericType(onServiceRegistredContext.ImplementationType, typeof(IDistributedEventHandler<>)))
                {
                    distributedHandlers.AddIfNotContains(onServiceRegistredContext.ImplementationType);
                }
            });
```

In order to setup ABP application there is need to call (following by MicroserviceDemo sample) :
```
public virtual IServiceProvider ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddApplication<SampleMicroserviceHostModule>(options =>
            {
                options.UseAutofac();
                options.Configuration.UserSecretsAssembly = typeof(Startup).Assembly;
            });
            return services.BuildServiceProviderFromFactory();
        }
```
AddApplication method takes current service collection  and adds other dependecies to it, but collection already contains default implementation of IServiceProviderFactory<> (Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory) so after UseAutofac there are registered two IServiceProviderFactory<> 

In the next step there is called services.BuildServiceProviderFromFactory(). It takes firstly registered IServiceProviderFactory<> so it takes DefaultServiceProviderFactory instead of AutofacServiceProviderFactory
 
Finally actions subscribed to OnRegistered are not invoked as this is part of AutofacRegistration

**Comment by hikalkan** [comment]
I removed existing service provider factories before adding Autofac.

**Comment by acid12** [comment]
> I removed existing service provider factories before adding Autofac.

Thanks for fast fix, our teem will be awating this released, great response.

**Comment by hikalkan** [comment]
We'll publish it on tomorrow.
