### ISSUE TITLE
Do not generate specific modules in the generated project

### ISSUE THREAD

**Issue by Fisher-Joe** [abpframework/abp#1368]
CLI recommendation: Do not generate specific modules in the generated project, and the required modules are generated by CLI into another module/ModuleName directory in the form.

1. The generated project is an empty project that only contains ABP related modules.
2. Other modules are added via like: CLI add-moules bloging.
3. So other people can develop their own modules and open source.

**Comment by hikalkan** [comment]
We thought to create a most empty template, then add modules using CLI. However, adding some modules are not easy to be done with CLI. Especially Identity module requires changes in the Startup configuration. In the end, we decided to add most used fundamental modules by default. Developers can remove them if they want.

>So other people can develop their own modules and open source

No restriction on that, they can still do this.
