### ISSUE TITLE
Bundling of blazor.webassembly.js conflicts with asp.net hosting behaviour

### ISSUE THREAD

**Issue by BenWhite27** [abpframework/abp#13684]
* 6.0.0-rc.2
* Blazor WebAssembly
* EF Core

When a Blazor app is hosted via asp.net core, a middleware is used to host the framework files (`app.UseBlazorFrameworkFiles()`).  This middleware relies on an HTTP request to `_framework\blazor.webassembly.js` to set some response headers that communicate the environment to the Blazor runtime as well as some other headers for hot reload.
See: [ComponentsWebAssemblyApplicationBuilderExtensions.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/Server/src/ComponentsWebAssemblyApplicationBuilderExtensions.cs#L40)

As the `abp bundle` command injects the blazor.webassembly.js BundleDefinition after all contributors have been evaluated there doesn't appear to be an opportunity to override this behaviour and exclude this particular JS file from the bundle.

I believe a better design would be to have the script added in the startup template bundle contributor instead of the abp cli.  It would also be useful if the docs indicated that when hosting the Blazor UI project in an asp.net core host the script should be removed and obtained from the server.

**Comment by enisn** [comment]
We can add an option for that.

Until we do, you can remove it from application bundle in a BundleContributor
https://docs.abp.io/en/abp/latest/UI/Blazor/Global-Scripts-Styles#bundling-and-minification

**Comment by BenWhite27** [comment]
> Until we do, you can remove it from application bundle in a BundleContributor https://docs.abp.io/en/abp/latest/UI/Blazor/Global-Scripts-Styles#bundling-and-minification

@enisn I'm not sure that'd work.  Apologies if I'm wrong but my understanding of the code is that `_framework\blazor.webassembly.js` is added to the bundle if it is not found in the bundle definitions (as of 22nd Aug) https://github.com/abpframework/abp/blob/40fda190e37a417956282685fb3e6c4c4e21db06/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Bundling/BundlingService.cs#L117

So even if there was an entry for me to do something like `context.Remove(...)` the abp cli bundle command would add it back in?

**Comment by enisn** [comment]
I'm closing this issue since removing is possible in v6.0 after PR #14375

**Comment by sturlath** [comment]
Is this by any change connected to this here not working https://github.com/abpframework/abp/pull/13772#issuecomment-1319968310 @enisn? I´m btw trying to[ get Blazor WASM to use .br files and not the huge .dll](https://support.abp.io/QA/Questions/3577 )
