### ISSUE TITLE
ExtraProperties Doesn't work with Profile Service

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#13706]
The version is  Rel-6.0.

I have added extra properties. it works on the user page. I can update the value but

<img width="1756" alt="image" src="https://user-images.githubusercontent.com/2217899/184870327-96d6c4a8-7c0a-4b68-a75f-5bb1462cc7d9.png">

when I go to my profile page. It doesn't return extra-properties.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/2217899/184870678-9b679f4d-bbe3-430e-b9f7-4b82873c9e5d.png">

Also Enis and I have checked AutoMapper profile. MapExtraProperties was added.
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/2217899/184871134-b8b66c26-fd35-4380-80fd-3fe3f2a9f029.png">

**Comment by enisn** [comment]
@maliming do you have any idea about this?

**Comment by realLiangshiwei** [comment]
We did not implement extension ui for profie page
https://support.abp.io/QA/Questions/3517/Add-IdentityUser-Entity-Extensions-to-Profile-Management-Screen
