### ISSUE TITLE
Get ClientSecret from appsettings.json for MVC template DbMigration application

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1370]
```
{
  "ConnectionStrings": {
    "Default": "Server=localhost;Database=MyProject;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "IdentityServer": {
    "Clients": {
      "MyProject_AdministrationCenter": {
        "ClientId": "MyProject_AdministrationCenter",
        "RootUrl": "https://localhost:44347/",
        "ClientSecret": "1q2w3e*"
      },
      "MyProject_ConsoleTestApp": {
        "ClientId": "MyProject_ConsoleTestApp"
      }
    }
  }
}
```
"AdministrationCenter" is a new name to replace "Web".
The problem is: No matter what `ClientSecret` I give, it only produces `E5Xd4yMqjP5kjWFKrYgySBju6JVfCzMyFp7n2QmMrME=` in the table "IdentityServerClientSecrets".
![image](https://user-images.githubusercontent.com/30018771/60089055-4f0f9d00-9772-11e9-9eff-b3c996ca4a66.png)

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/60089072-58990500-9772-11e9-81cf-4f4d44eb5810.png)

**Comment by hikalkan** [comment]
ClientSecret is not in the startup template. I think you added it to appsettings.json. The code (`IdentityServerDataSeedContributor`) doesn't know such a config, it uses hard-coded value.

I will take it to the configuration.

**Comment by gdlcf88** [comment]
> ClientSecret is not in the startup template. I think you added it to appsettings.json. The code (`IdentityServerDataSeedContributor`) doesn't know such a config, it uses hard-coded value.
> 
> I will take it to the configuration.

Thanks.
By the way, are there any feasible ways to generate a customized ClientSecret at 0.18?

**Comment by hikalkan** [comment]
`.Sha256()` ([see](https://github.com/abpframework/abp/commit/2f39d2a15bc5bd2e6ac7b945c6c0c87f728cd457#diff-0e72feef8e800340355d471ae3f12265L121))

**Comment by xyfy** [comment]
When using `volo.abp.identityserver` , I do not find a method of sha256 to encrypt the plaintext secret exposed, like  `IdentityServer4.Models.HashExtensions` in  nuget package `IdentityServer4`, it provider some extenstion method which named `Sha256` `Sha512` ,when in my project ,I need to use the third party nuget ,but not only `Volo.Abp`?
 
Will you like to add it to `volo.abp.identityserver`?

**Comment by maliming** [comment]
@xyfy 

https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/IdentityServer4/src/Extensions/HashExtensions.cs#L22

**Comment by xyfy** [comment]
yes,I finded this method, abp has wrap the identyserver4 in `volo.abp.identityserver`,many same name class in this project. like `client` ,`apiresource`.so if I use this extesions  I must add namespace before class name,or  used like this `IdentityServer4.Model.HashExtensions.Sha256(value)`.  so I think why `volo.abp.identityserver` expose a same extesion. hide the third part nuget for me?

**Comment by maliming** [comment]
This doesn't seem to be a good way, since ʻIdentityServer4.Model` already provides many methods, we should not implement it again. 

You can use namespace alias.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive
