### ISSUE TITLE
Creating new/updating project to preview throws error

### ISSUE THREAD

**Issue by roos-robert** [abpframework/abp#13709]
### Documentation

Following the documentation here for creating a new project based on the latest preview:
[https://docs.abp.io/en/abp/latest/Previews](url)

### GitHub Issues

Tested on an existing project: ABP 5.3.3 to upgrade to latest preview, MVC interface, EF Core: `abp switch-to-preview`
Tested on new project using: `abp new MyApp -t app-pro --preview`
Tested upgrade on existing/creating new through Suite

Getting the following error: `Object reference not set to an instance of an object.` whereas the creation/upgrade fails.

![bild](https://user-images.githubusercontent.com/5381910/184985684-91ebd96e-3154-4510-8286-a70dac3771ce.png)

To reproduce, open terminal, try to create project with:  `abp new MyApp -t app-pro --preview`

**Comment by maliming** [comment]
`dotnet tool install --global Volo.Abp.Cli --version 6.0.0-rc.2`
