### ISSUE TITLE
How to write custom controller implementations for methods of ApplicationService

### ISSUE THREAD

**Issue by LiangZugeng** [abpframework/abp#13712]
This is a question.

I'm writing code in the application service and I need to enable http request buffering to read the request body multiple times, I tried to inject IHttpContextAccessor into the application service but found the EnableBuffering method cannot be found.

Previously we enable the http request buffering at the first line in the web API controller method.
```
// In Web API Controller class
public async Task SomeMethod()
{
  Request.EnableBuffering();
  // access http request body here
}
```

I want to add some code in the controller method ABP automatically generated to enable http request buffering, how can I do that?

**Comment by maliming** [comment]
You can add custom middleware.

**Comment by LiangZugeng** [comment]
@maliming Thanks for your reply.

Middleware came to my mind but I considered it as a last resort, the reason is that I only need to enable http request buffering for a single method in an application service, in order to do that in a middleware I need to filter the request using its url and I would like not to hard code the url.

Being more specific, my questions are: 1) Is it possible to enable http request buffering in application service methods? if not 2) can I provide my own implementation of the web api controller methods instead of using the automagically generated controller methods (please kindly point me to some sample code for this).

Please suggest, thank you.

**Comment by maliming** [comment]
You can also consider using a filter to `EnableBuffering` based on a custom `Attribute`.

 `EnableBufferingAttribute` on controller or methods.
