### ISSUE TITLE
Add multi tenant migrations to the migrator console application

### ISSUE THREAD

**Issue by Silthus** [abpframework/abp#1371]
In the `aspnetboilerplate` framework running the `Migrator` app would migrate the host database and all tenant databases that had a separate connection string.

Currently the migrator tool only migrates the host database and ignores tenants with own databases and connection strings.

Also the connection string is currently not stored encrypted.

**Comment by hikalkan** [comment]
This was in the plan, but was not created an issue. It is good that you opened this. Thanks.

**Comment by leonkosak** [comment]
@hikalkan: This functionality creates identical databases (schema) for host and tenant?
If my statement is true, the only way for having different schemas for host and tenants is to create two different migrators?

**Comment by gterdem** [comment]
@leonkosak Yes, that is correct. Currently schemas for both host and tenants are identical.
To create specific schemas for both host and tenants is a point we can discuss.

**Comment by leonkosak** [comment]
Well, having only one migrator (calling with parameter -host or -tenant) would be a great benefit in my opinion.
Most of aplications are using host only for managing tenants (possible with additional custom logic), but all application-related logic is "inside" (protected with permissions) for tenant.
