### ISSUE TITLE
How to custom Id type for AuditLog

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#13714]
I import the `Audit Logging`module into my project, but i want to specify the `Id` to `long` type, how should i do?

**Comment by iyilm4z** [comment]
@weiwxg AFAIK, It's **not** possible with the current design. The [AuditLog](https://github.com/abpframework/abp/blob/dev/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain/Volo/Abp/AuditLogging/AuditLog.cs) entity has no extension/overriding point for it's Id property.

But, you can extend a module entity by adding extra properties with [Module Entity Extensions](https://docs.abp.io/en/abp/latest/Module-Entity-Extensions) feature.
