### ISSUE TITLE
Toolbar LanguageSwitch namespace wrong with LeptonXLite?

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#13725]
For example main toolbar namespace:
`using Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite.Toolbars`

But the LanguageSwitch namespace is this:
> using Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite.**Themes.LeptonXLite**.Components.Toolbar.LanguageSwitch

Should it be this instead?
> using Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite.Components.Toolbar.LanguageSwitch

**Comment by olicooper** [comment]
It seems this is actually a purposeful and based on the theme folder structure. Closing.

**Comment by enisn** [comment]
> It seems this is actually a purposeful and based on the theme folder structure. Closing.

You're right, we didn't use **Rootnamespace** for leptonx projects, that's why this happens. Changing it will be breaking change, so we won't change it without a major version
