### ISSUE TITLE
sqlite databse is locked

### ISSUE THREAD

**Issue by comeonwuzhiliang** [abpframework/abp#13738]
The SQLite database is used and the entityframeworkcore is used to generate the application. Click the login button after running the application .The database  is locked exception occurs.
<img width="689" alt="mmexport1660821207716" src="https://user-images.githubusercontent.com/85801061/185382084-261516c2-d681-4b25-914b-35db073f88b4.png">

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/12248#issuecomment-1106489177

**Comment by comeonwuzhiliang** [comment]
Can you update the template of sqlite?

**Comment by maliming** [comment]
ok, I will do that.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/13801
