### ISSUE TITLE
[Cli] Support system proxy for http client requests

### ISSUE THREAD

**Issue by Silthus** [abpframework/abp#1373]
The cli currently uses the default `HttpClient` to make web requests. By doing this system proxies from corporate environments are ignored.

The cli should try to use the default proxy credentials when doing web requests.

I can create a PR for this and also refactor the cli usages of `HttpClient` into a central configured client. This would reduce the duplicate setup of JWT authentication and timeout settings. Also the http client of the cli would be more flexible to future changes.

Should I go ahead with this?

**Comment by hikalkan** [comment]
It is appreciated. You can send a PR. Thanks.

**Comment by Silthus** [comment]
How can I install and test the cli from by local `dev` branch?

**Comment by yekalkan** [comment]
build abp and run "dotnet {YourLocalGithubRoot}\abp\framework\src\Volo.Abp.Cli\bin\Debug\netcoreapp2.2\Volo.Abp.C
li.dll add-module Volo.Blogging" for example.

**Comment by maliming** [comment]
@Silthus 
Or you can debug the Volo.Abp.Cli project directly after setting the application parameters.
![image](https://user-images.githubusercontent.com/6908465/60101834-0dd9b600-978f-11e9-8284-e68b8fcf0845.png)

![image](https://user-images.githubusercontent.com/6908465/60101939-42e60880-978f-11e9-91d9-19f1be871bd9.png)
