### ISSUE TITLE
Blazor Server template with tiered seems broken. 

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#13742]
* Your **ABP Framework version**.
5.3.3

* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI

Blazor Server - Tiered

* Your database provider(EF Core/MongoDB)
EF

The Tiered option for Blazor server seems to be broken. The identity server project takes forever to start (several minutes) and seems very slow even then. It also seem to have a link to "ProjectName_App http://localhost:4200" even though this is a Blazor Server project.

Have tried both with the Community version and the Commercial (via ABP Suite) and both have the same problems. Non tiered seem to work fine. Swagger project as well as DBMigrator seem to work for tiered as well. 

Blazor UI reports exception below, even when the Identity Server projects finally gets up and running. 

```

An unhandled exception occurred while processing the request.
SocketException: The I/O operation has been aborted because of either a thread exit or an application request.
Unknown location

IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

TaskCanceledException: The operation was canceled.
System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, bool async, CancellationToken cancellationToken)

TimeoutException: The operation was canceled.
System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, bool async, CancellationToken cancellationToken)

TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Net.Http.HttpClient.HandleFailure(Exception e, bool telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

AbpRemoteCallException: An error occurred during the ABP remote HTTP request. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.) See the inner exception for details.
```

**Comment by improwise** [comment]
It seems this could be related to the Redis server, which it seems to be trying to use but can't find (not installed so that in itself is fine). No problems with non tiered projects/templates though?

**Comment by maliming** [comment]
hi

Please check all websites log.

**Comment by improwise** [comment]
I'll close this and create a new issue instead. Thanks.
