### ISSUE TITLE
[Discussion/request for info] Redis is a requirement of ABP, yet not supported on Windows 

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#13747]
[Redis](https://redis.io/docs/getting-started/installation/install-redis-on-windows/) is a requirement of ABP (although not  need in all scenarios), but yet it isn't officially supported on Windows:

_Redis is not officially supported on Windows. However, you can install Redis on Windows for development by following the instructions below._

While it is possible to get it running on Windows as well, (using Docker or other solutions) this is causing a bit of headache and there are quite a few Redis related tickets here and on the support forum. I can also be hard to explain to customers of commercial applications why the project relies on something that is said to not be supported on Window, especially in Enterprise projects.

I don't doubt that there were and are valid reasons for going with Redis but considering the above, it would be nice to know the reasoning behind it and also making it a requirement even in cases where I assume it isn't really needed. It would also be nice with some recommendations on the best strategy to implement and host it.

The closest I've been able to find is this:

https://docs.abp.io/en/abp/latest/Redis-Cache

but that doesn't really answer the questions above. 

Some related links:

https://github.com/abpframework/abp/issues/3487

https://support.abp.io/QA/Questions/1774/Redis--help-me-understand-why-it-is-needed

I should add that I don't know if there are any better solutions or if Redis is the best there is, but I still feel it would be nice with some more documentation etc. about this, both for knowledge but also to avoid possible problems etc. That Redis in itself is a very capable and good solution is probably undisputed, so it is more the fact that it isn't well supported on Windows that is the main issue here. So this is mostly intended as a topic of discussion and not really a complaint as such. 

Would also be nice to get some feedback how others handle this, perhaps mostly with regards to hosting, production environments etc. Most people in here will probably get it working locally once you realize it is needed and why certain problems occur (like with tiered projects don't work etc).

Thanks :)

**Comment by improwise** [comment]
This issue is also related to this:

https://support.abp.io/QA/Questions/848/Unable-to-connect-to-redis-serverS

For those running Windows (as I would imagine that most ABP users are), I can also recommend looking at 

https://www.memurai.com/

Which seem to work fine and does not require WSL , Docker etc. Have only used it in development though, not production. Just by installing it, the ABP tiered projects  will start working. Can also be configured as a service for easier maintenance it seems.

**Comment by maliming** [comment]
Thanks for your share @improwise
