### ISSUE TITLE
Auto  API  ApplicationService as API not working in Plugins

### ISSUE THREAD

**Issue by rajenderreddyk** [abpframework/abp#13752]
If you're creating a bug/problem report, please include the followings:
ABP V 5.3.3 
swagger API  
database : EF Core (MSSQL)
API Endpoint is not rendering if we expose the Application service as API.

Steps 
1) created a full web app (https://abp.io/get-started)
2) created sample module  (https://abp.io/get-started)
3) added book service application layer in MODULE and run the application.
4) now create a **MYPLUGIN** folder in **FULL WEB APP** and add the compiled MODULE DLLS (sample module which we created in  step 2)
5) run the web app and go to swagger you will never see the API endpoint which was exposed in STEP 2 (MODULE)

sample screens
 Module screenshot
![image](https://user-images.githubusercontent.com/61243747/185751826-53af4408-378f-4ca8-9c58-5b990f280bbe.png)

Main web app after copying the Module to PLUGIN folder 
![image](https://user-images.githubusercontent.com/61243747/185751799-f38c687f-a275-457e-9782-dee3a48e9e3a.png)

the reason is we need to add the following code in HOST project **HostModule** for that we need to add the project reference.  Is there any other way we can activate the Application Layer as  Automagic API?
 Configure<AbpAspNetCoreMvcOptions>(options =>
        {
            options.ConventionalControllers.Create(typeof(PluginAApplicationModule).Assembly, options =>
            {
                options.RootPath = "test";
            }); 
        });

**Comment by ugurozturk** [comment]
ConfigureConventionalControllers add PluginApplicationModule
