### ISSUE TITLE
OpenIddict UserInfoController not virtual

### ISSUE THREAD

**Issue by merijng** [abpframework/abp#13778]
See pull request #13779

About class [UserInfoController.cs](https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/UserInfoController.cs) in dev branch

The class is not marked as virtual. Therefor it is not possible to override the Userinfo() endpoint. See [the documentation about overriding](https://docs.abp.io/en/abp/6.0/Customizing-Application-Modules-Overriding-Services)

**Comment by merijng** [comment]
See pull request #13779

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/13782
