### ISSUE TITLE
The additionally added mandatory propertie is functionally different from other mandatory fields and  localization seems broken.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#13785]
**App:** Angular

- The additionally added mandatory propertie is functionally different from other mandatory fields

![image](https://user-images.githubusercontent.com/99716457/186068384-fe12047d-2f3f-4471-b674-bbd2654697b1.png)

- The localization of the additionally added property on the User page appears broken.
![image](https://user-images.githubusercontent.com/99716457/186068778-1a51b30e-c0d3-446e-81f0-d5864a8c6053.png)

**Comment by mahmut-gundogdu** [comment]
the validation message error fixed.
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/2217899/186450657-6f7a11bb-22d8-4568-b279-c9a232f33e9f.png">
