### ISSUE TITLE
Hangfire background job unable specific queues

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#13789]
* Your **ABP Framework version**.
* 6.0.0-rc2
* Your database provider(EF Core/MongoDB)
* EF Core
* Steps needed to **reproduce** the problem.

Configure server's queue list `{ "alpha", "beta", "default" }`.
``` c#
private void ConfigureBackgroundJobServer()
{
    Configure<BackgroundJobServerOptions>(options =>
    {
        options.Queues = new[] { "alpha", "beta", "default" };
    });
}
```
Specific job run in `queue1`.
``` c#
public class TestJob
    : AsyncBackgroundJob<TestArgs>, ITransientDependency
{
    [Queue("queue1")]
    public override Task ExecuteAsync(EdiTestArgs args)
    {
        Logger.LogInformation("Do something...");
        return Task.CompletedTask;
    }
}
```
Enqueue the job.
``` c#
public class TestService : ApplicationService
{
    private readonly IBackgroundJobManager _backgroundJobManager;

    public EdiTestService(IBackgroundJobManager backgroundJobManager)
    {
        _backgroundJobManager = backgroundJobManager;
    }

    public async Task GetAsync()
    {
        await _backgroundJobManager.EnqueueAsync(
            new TestArgs { }
        );
    }
}
```

Excpect: Job will not be excuted.
(`queue1` is not in the server queue list `{ "alpha", "beta", "default" }`)

Acutal: Job will still be excuted.

So, how to configure according to the ABP?

**Comment by Likhon-Roy** [comment]
public interface IAlphaHangfireJob<in TArgs>
{
    [Queue("alpha")]
    Task ExecuteAsync(TArgs args);
}

public interface IEmailSendingJob<TArgs> : IAlphaHangfireJob<TArgs>
{

}

public class EmailSendingJob : IEmailSendingJob<EmailSendingArgs>, ITransientDependency
{
    public async Task ExecuteAsync(EmailSendingArgs args)
    { }
}

// call like this.
                    BackgroundJob.Enqueue<IImportEventUserJob<EmailSendingArgs>>(x => x.ExecuteAsync(
                        new EmailSendingArgs
                        {
                        }));

**Comment by Likhon-Roy** [comment]
This worked for me.

**Comment by jakeuj** [comment]
> This worked for me.

This is a bug in version 6.x, fixed in version 7.x.
