### ISSUE TITLE
Upgrading to 6.0.0-rc.3 fails

### ISSUE THREAD

**Issue by Domitnator** [abpframework/abp#13796]
We just upgraded our 6.0.0-rc.2 project to version 6.0.0-rc.3 but now we are getting nuget errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Volo.Abp.FeatureManagement.Domain from 7.0.0-preview20220723 to 6.0.0-rc.3. Reference the package directly from the project to select a different version. 
 ABP_Beheer.Domain -> Volo.Saas.Domain 7.0.0-preview20220723 -> Volo.Abp.FeatureManagement.Domain (>= 7.0.0-preview20220723) 
 ABP_Beheer.Domain -> Volo.Abp.FeatureManagement.Domain (>= 6.0.0-rc.3)	ABP_Beheer.Domain	P:\Development\ABP_Beheer\src\ABP_Beheer.Domain\ABP_Beheer.Domain.csproj	1	
````
![image](https://user-images.githubusercontent.com/13468638/186171057-2c634317-63e9-4ed0-a6e0-182e635c3607.png)

Also:

During the upgrade, the process gave a warning that it could not find the leptonx theme nuget package:

![image](https://user-images.githubusercontent.com/13468638/186171720-05410ef7-9b31-4bc0-a119-a55c95db89e7.png)

To reproduce:

1. Update the CLI: dotnet tool update -g Volo.Abp.Cli --prerelease
2. Update the Suite: abp suite update --prerelease
3. Clean the project: abp clean
4. Update the project: abp update
5. Try to build the project, but notice that nuget errors occur.
6. Also notice that the upgrade has added 7.0.0-preview packages:

![image](https://user-images.githubusercontent.com/13468638/186172782-6dc7d489-954e-460b-a7ba-8a48c718bf60.png)

I also tried cleaning the project/solution AFTER the upgrade, but that didnt help either

**Comment by vioKamran** [comment]
Please click link  #13531.

This version is not complete and trial version 6.0.0

**Comment by Domitnator** [comment]
Hi @vioKamran , I don't see what your link has to do with this issue? But maybe I am missing something? I understand that there are milestones and different versions. But I dont see how my upgrade issue has something to do with that. 

Upgrading from 6.0.0.0-rc-1 to 6.0.0.0-rc-2 worked without any problems, but upgrading from 6.0.0.0-rc-2 to 6.0.0.0-rc-3 simply does not work.

**Comment by Domitnator** [comment]
Running abp update with the specific version solves the problem:

```
abp update --version 6.0.0-rc.3
```
