### ISSUE TITLE
Volo.Abp.Account.Pro.Public.Application - AccountAppService class

### ISSUE THREAD

**Issue by spospisil** [abpframework/abp#13799]
### Discussed in https://github.com/abpframework/abp/discussions/13798

<div type='discussions-op-text'>

<sup>Originally posted by **spospisil** August 23, 2022</sup>
Hi,

There are two public methods (SendPhoneNumberConfirmationTokenAsync and  GetConfirmationStateAsync) in this class that are not marked as 'virtual' resulting in developers not being able to inherit or override them according to the ABP Best Practices link ([https://docs.abp.io/en/abp/latest/Best-Practices/Application-Services) for Application Services.

Could this be addressed/fixed?

Steve</div>

**Comment by maliming** [comment]
ok, I will fix that.

**Comment by maliming** [comment]
hi

It will available in next RC of 6.0
