### ISSUE TITLE
https://account.abp.io/Account/Register returns Internal Server Error 500...

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1380]
Hi,

I wanted to comment on "https://blog.abp.io/abp/Abp-CLI-Templates-v0_18_0-Release" but when I registered I got an internal server error.

However my actual question is about this statement in the blog post:

"As a big breaking change, it will only run on .NET Core (dropping .net standard support)"

a) It is however still possible to reference .NET Standard 2.0 assemblies in .NET Core 3?
b) Moving forward how does Volosoft propose common code should be managed for .NET 5 and abp.io moving forward? Still as .NET Standard 2.0 assemblies?

**Comment by hikalkan** [comment]
> a) It is however still possible to reference .NET Standard 2.0 assemblies in .NET Core 3?

Yes.

> b) Moving forward how does Volosoft propose common code should be managed for .NET 5 and abp.io moving forward? Still as .NET Standard 2.0 assemblies?

We will make packages .net standard compatible as much as possible. For asp.net core depended packages, they will be .net core because asp.net core will not be .net standard.

**Comment by hikalkan** [comment]
The error is related to your password complexity. Use numbers, letters, upper and lower case chars and a special chat (like *) in your password.
We will fix it to show a better error message.

**Comment by gdlcf88** [comment]
> The error is related to your password complexity. Use numbers, letters, upper and lower case chars and a special chat (like *) in your password.
> We will fix it to show a better error message.

Will abp template provides a default error handle in the future?

**Comment by hikalkan** [comment]
Definitely, yes. It will be a good error page and will be working :D
