### ISSUE TITLE
RFC 7807 -  Problem Details for HTTP APIs

### ISSUE THREAD

**Issue by gentledepp** [abpframework/abp#13807]
Since this is a standard now and aspnet core supports this via `IProblemDetailsService`

I remember you stated this was not supported.
But is there some guidance in how abp can be reconfigured to return those error responses.

This could be very useful

**Comment by maliming** [comment]
hi

I guess `IProblemDetailsService` was introduced by net 7. I will check this in https://github.com/abpframework/abp/pull/13626
