### ISSUE TITLE
LeptonX Lite - Blazor Server MainLayout background and width

### ISSUE THREAD

**Issue by BogdanJak** [abpframework/abp#13803]
ABP Framework version - 6.0 - rc3
User Interface - Blazor server
Your database provider - EF Core

Hello

How to set the full width of opened pages to 100% MainLayout width? (picture)
is it possible to set the background MainLayout color to e.g. black?
![image](https://user-images.githubusercontent.com/54505464/186374801-15e9825a-a166-4c6e-87ee-e210b277be24.png)

**Comment by BogdanJak** [comment]
Can I count on any answer?

**Comment by BogdanJak** [comment]
Your support - it's a failure. The second time the same question was asked and no response, no answer.

**Comment by armgnunlu** [comment]
Hi @BogdanJak,

You can make the content field full-width using the code below.
``` 
.lpx-content-container .lpx-content {
     max-width: 100%;
}
```

You can also change the backgroud-color using the code below.
``` 
.lpx-content-container {
     background-color: #000000;
}
```

You may want to change the topbar background color when you change the main background color. To do this, the following css codes will work.
``` 
.lpx-topbar-container .lpx-topbar {
     background-color: #000000;
}
```
 
Thank you for your patience.

**Comment by BogdanJak** [comment]
Sorry for saying that, but I have been working with Syncfusion for several years. There, even the strangest or the simplest questions do not go unanswered. They always try to help.
Thanks for the help.
