### ISSUE TITLE
I can't login at web project

### ISSUE THREAD

**Issue by Fisher-Joe** [abpframework/abp#1381]
At Web project I login ,but the IdentityServer4 tell me the error:

```
IdentityServer4.Validation.AuthorizeRequestValidator : Invalid redirect_uri:
... 
 "Raw": {
    "client_id": "Saas_Web",
    "redirect_uri": "https://localhost:44351/signin-oidc",
...
```

Need to set the value of the table of the IdentityServerClient ?

**Comment by maliming** [comment]
For possible reasons https://github.com/abpframework/abp/issues/1335. 
Change the RootUrl in the DbMigrator project to the url of the web project, and then re-migrate the database.

**Comment by Fisher-Joe** [comment]
at the login form , I use admin and 1q2w3e*  the tip:  Invalid username or password!
Need to register?
![image](https://user-images.githubusercontent.com/12068896/60159884-b71fbb00-9826-11e9-8e68-140199581d17.png)

**Comment by maliming** [comment]
password is `1q2w3E*`

**Comment by gdlcf88** [comment]
`1q2w3e*` is a default IdentityServer ClientSecret for project "Web".
`1q2w3E*` is the admin account's defalut password.

**Comment by Fisher-Joe** [comment]
Thank you , it worked.
