### ISSUE TITLE
How can I login on Swagger UI page?

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1383]
I've logged in on IdentityServer, but when I try out my api on swagger, it hint me that I have not logged in.
![image](https://user-images.githubusercontent.com/30018771/60189708-f8828b80-9863-11e9-9935-a6ff1bb166f3.png)

**Comment by Fisher-Joe** [comment]
I think what you should ask is how do I get Jwt's AccessToken on WebAPI(Swagger UI).

**Comment by CooperLiu** [comment]
@gdlcf88 FYI, [swagger official doc for security definition](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements)

**Comment by gdlcf88** [comment]
Using ·/connect/token· in ids4 host(not http api host)
