### ISSUE TITLE
Abp 6.0.0-rc3 Error InvalidOperationException: No database provider has been configured for this DbContext

### ISSUE THREAD

**Issue by element-dlapointe** [abpframework/abp#13848]
ABP 6.0.0-rc3
EF Core with MySQL
`InvalidOperationException: No database provider has been configured for this DbContext.`

Hi all, ive just started using ABP (6.0.0-rc3) and after setting up my domain, i wanted to run the application but each layers (*.web, the *.HttpApi.Host, *.IdentityServer and *.DbMigrator) does throw this exception.

Here is the full message :
`[22:55:56 ERR] No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.`

I did check and everything seems good in the DbContextFactory (except there is 0 reference?) :
```
public SchedulerDbContext CreateDbContext(string[] args)
    {
        SchedulerEfCoreEntityExtensionMappings.Configure();

        var configuration = BuildConfiguration();

        var builder = new DbContextOptionsBuilder<SchedulerDbContext>()
            .UseMySql(configuration.GetConnectionString("Default"), MySqlServerVersion.LatestSupportedServerVersion);

        return new SchedulerDbContext(builder.Options);
    }
```

the DbContext also have a public construction which receives a DbContextOptions and pass it to its base :
```
public SchedulerDbContext(DbContextOptions<SchedulerDbContext> options)
        : base(options)
    {

    }
```

So far, ive mostly only worked on the Domain layers, and havent really touched (except configs) anything on the different layers.

I did create the project using abp new command and then move to 6 using abp --swtich-to-preview. 

Another weird thing is that i manage to run the migration (both `dotnet ef migrations add Initial` and `dotnet ef database update` successfully but not using the DbMigrator.

Thank you.

**Comment by element-dlapointe** [comment]
A few minutes after posting (even tough ive been debugging it for hours!!!), ive managed to get it to work, but seem like there might be a bug...

In *.EntityFrameworkCore.EntityFrameworkCoreModule
```
public class SchedulerEntityFrameworkCoreModule : AbpModule
{
    public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        SchedulerEfCoreEntityExtensionMappings.Configure();
    }

    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddAbpDbContext<SchedulerDbContext>(options =>
        {
                /* Remove "includeAllEntities: true" to create
                 * default repositories only for aggregate roots */
            options.AddDefaultRepositories(includeAllEntities: true);
        });

        Configure<AbpDbContextOptions>(options =>
        {
                /* The main point to change your DBMS.
                 * See also SchedulerMigrationsDbContextFactory for EF Core tooling. */
            options.UseMySQL();

            //options.Configure(opts =>
            //{
            //    opts.DbContextOptions.UseQueryTrackingBehavior(Microsoft.EntityFrameworkCore.QueryTrackingBehavior.NoTracking);
            //});
        });
    }
}
```

If i uncomment the UseQueryTrackingBehavior, the error is back. At the moment, i guess i can live without this option, but in term of performance, this would have to be set to NoTracking at some point.

Thank you

**Comment by maliming** [comment]
hi

How about the `abp new BookStore --preview` instead of `--swtich-to-preview`?

**Comment by element-dlapointe** [comment]
I couldnt find documenation on how to install the preview version of the CLI as dotnet tool doesnt allow --preview. Ive managed to do it and recreated the project from scratch and its all good now.

Sorry about it :D

**Comment by element-dlapointe** [comment]
Oups reopening, the bug is still present even on a new project created using --preview 

```
public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddAbpDbContext<SchedulerDbContext>(options =>
        {
                /* Remove "includeAllEntities: true" to create
                 * default repositories only for aggregate roots */
            options.AddDefaultRepositories(includeAllEntities: true);
        });

        Configure<AbpDbContextOptions>(options =>
        {
                /* The main point to change your DBMS.
                 * See also SchedulerMigrationsDbContextFactory for EF Core tooling. */
            options.UseMySQL();

            options.Configure(opts =>
            {
                opts.DbContextOptions.UseQueryTrackingBehavior(Microsoft.EntityFrameworkCore.QueryTrackingBehavior.NoTracking);
            });
        });
    }
```

![image](https://user-images.githubusercontent.com/63807551/187283046-e784d80f-2213-48f7-b5c6-f62682ad4e56.png)

If i comment out the setting of the QueryTrackingBehavior, its working fine...
