### ISSUE TITLE
How to perform integration testing for database-per-tenant multi tenancy style?

### ISSUE THREAD

**Issue by dejancg** [abpframework/abp#13846]
Using ABP 4.4.4
Basically what's in the title.

In the test setup, we use
```
var connection = new SqliteConnection("Data Source=:memory:");
```

and then we Open this connection and use it like

```
services.Configure<AbpDbContextOptions>(options =>
{
    options.Configure(context =>
    {
        context.DbContextOptions.UseSqlite(_sqliteConnection);
     });
});
```

It seems like the only supported database style when performing integration tests is `MultiTenancyDatabaseStyle.Shared` ?
Is there no love for `PerTenant` database style? If I am mistaken, is there any documentation on how to set this up?

**Comment by maliming** [comment]
it is not supported now, however, I will research this case.

**Comment by maliming** [comment]
There is nothing we can do.
