### ISSUE TITLE
How to Configure AbpOpenIddictExtensionGrantsOptions?

### ISSUE THREAD

**Issue by wulienen** [abpframework/abp#13857]
ABP Framework version：6.0.0-rc.2
I can't get ImplementationInstance of IExtensionGrant in ConfigureServices method

![image](https://user-images.githubusercontent.com/26619474/187160238-ee1786e0-449b-4891-bc8a-3ded271f31dd.png)

**Comment by roc916** [comment]
Try add class?
```csharp
public class YourExtensionGrant : IExtensionGrant // ITokenExtensionGrant?
{
    public string Name => "YourExtensionGrant";

    public async Task<IActionResult> HandleAsync(ExtensionGrantContext context)
    {
        // TODO:
    }
}
```

**Comment by wulienen** [comment]
> Try add class?
> 
> ```cs
> public class YourExtensionGrant : IExtensionGrant // ITokenExtensionGrant?
> {
>     public string Name => "YourExtensionGrant";
> 
>     public async Task<IActionResult> HandleAsync(ExtensionGrantContext context)
>     {
>         // TODO:
>     }
> }
> ```

My ExtensionGrant  has many Constructor Injection ，so i can't  add   My ExtensionGrant  to the options's grants

**Comment by wulienen** [comment]
![image](https://user-images.githubusercontent.com/26619474/187172534-ac22b1a3-6453-45bb-a732-ee847d762696.png)
like this，how to add my ExtensionGrant?

**Comment by roc916** [comment]
> ![image](https://user-images.githubusercontent.com/26619474/187172534-ac22b1a3-6453-45bb-a732-ee847d762696.png) like this，how to add my ExtensionGrant?

You can use`context.HttpContext.RequestServices.GetRequiredService` in `HandleAsync` method.

**Comment by wulienen** [comment]
> 

so must override  TokenController's HandleAsync ?  and  AbpOpenIddictExtensionGrantsOptions  is useless ？

**Comment by wulienen** [comment]
> > ![image](https://user-images.githubusercontent.com/26619474/187172534-ac22b1a3-6453-45bb-a732-ee847d762696.png) like this，how to add my ExtensionGrant?
> 
> You can use`context.HttpContext.RequestServices.GetRequiredService` in `HandleAsync` method.

so must override TokenController's HandleAsync ? and AbpOpenIddictExtensionGrantsOptions is useless ？

**Comment by roc916** [comment]
> > > ![image](https://user-images.githubusercontent.com/26619474/187172534-ac22b1a3-6453-45bb-a732-ee847d762696.png) like this，how to add my ExtensionGrant?
> > 
> > 
> > You can use`context.HttpContext.RequestServices.GetRequiredService` in `HandleAsync` method.
> 
> so must override TokenController's HandleAsync ? and AbpOpenIddictExtensionGrantsOptions is useless ？

No, see [TokenController.cs#L45-L50](https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.cs#L45-L50)
```csharp
public class YourExtensionGrant : IExtensionGrant // ITokenExtensionGrant?
{
    public string Name => "YourExtensionGrant";

    public async Task<IActionResult> HandleAsync(ExtensionGrantContext context)
    {
        // TODO:
        // context.HttpContext.RequestServices.GetRequiredService ...
    }
}
```

**Comment by wulienen** [comment]
> 

i  mean my ExtensionGrant can't add to AbpOpenIddictExtensionGrantsOptions,  if AbpOpenIddictExtensionGrantsOptions has not my  ExtensionGrant,  how could [TokenController.cs#L45-L50](https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.cs#L45-L50) find my ExtensionGrant ？

**Comment by wulienen** [comment]
> > > > ![image](https://user-images.githubusercontent.com/26619474/187172534-ac22b1a3-6453-45bb-a732-ee847d762696.png) like this，how to add my ExtensionGrant?
> > > 
> > > 
> > > You can use`context.HttpContext.RequestServices.GetRequiredService` in `HandleAsync` method.
> > 
> > 
> > so must override TokenController's HandleAsync ? and AbpOpenIddictExtensionGrantsOptions is useless ？
> 
> No, see [TokenController.cs#L45-L50](https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.cs#L45-L50)
> 
> ```cs
> public class YourExtensionGrant : IExtensionGrant // ITokenExtensionGrant?
> {
>     public string Name => "YourExtensionGrant";
> 
>     public async Task<IActionResult> HandleAsync(ExtensionGrantContext context)
>     {
>         // TODO:
>         // context.HttpContext.RequestServices.GetRequiredService ...
>     }
> }
> ```

i mean my ExtensionGrant can't add to AbpOpenIddictExtensionGrantsOptions, if AbpOpenIddictExtensionGrantsOptions has not my ExtensionGrant, how could [TokenController.cs#L45-L50](https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.cs#L45-L50) find my ExtensionGrant ？

**Comment by realLiangshiwei** [comment]
**Do not** use constructor Injection, try use the `context.HttpContext.RequestServices.GetRequiredService` to resolve the service.

If you really want to use constructor Injection, you can try `IConfigureOptions`, for example: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Json/AbpMvcNewtonsoftJsonOptionsSetup.cs
