### ISSUE TITLE
ISettingValueProviderManager

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#13850]
Hello, 
SettingValueProviderManager look like ISingletonDependency
but ISettingValueProvider implemented classes look like ITransientDependency
Isn't there a design problem here?

**Comment by maliming** [comment]
We will check this design.

**Comment by maliming** [comment]
Other modules are designed this way, I don't think this could cause any problems.

**Comment by muratyuceer** [comment]
> Other modules are designed this way, I don't think this could cause any problems.

yes, it's fine as long as the creator of the custom settingvalue provider knows that it will work as a singleton, it's just misleading
