### ISSUE TITLE
Blazor UI Breadcrums not working well

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#13869]
I need to click a second time to show the breadcrums.

Steps:
  Run the app template's Blazor Server project.

![2022-08-30 10 03 45](https://user-images.githubusercontent.com/16813853/187332234-57de78ae-b7e2-4510-8230-d8fce98a7e6f.gif)

**Comment by realLiangshiwei** [comment]
@enisn  Is this was sovled by https://github.com/volosoft/lepton/pull/618?

**Comment by enisn** [comment]
Yes
