### ISSUE TITLE
Duplicate SignInResult.RequiresTwoFactor check code in account module

### ISSUE THREAD

**Issue by Webdiyer** [abpframework/abp#1386]
Does the second check has special meaning? or it should be removed? 

https://github.com/abpframework/abp/blob/c475f25539462d581632313cd1b74658fb87618c/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L100

https://github.com/abpframework/abp/blob/c475f25539462d581632313cd1b74658fb87618c/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L116

**Comment by hikalkan** [comment]
We should remove the second usage. Thanks.
