### ISSUE TITLE
HideAbpEndpoints() and schemas

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#13874]
Calling method HideAbpEndpoints() hides ABP endpoints.

What about ABP schemas ? There is a lot of them. 

How to hide them too ?

**Comment by realLiangshiwei** [comment]
Please explain in detail.

**Comment by sebitsi** [comment]
Look. 
I have 2 custom methods.
In schema section there are ABP schemas.

![Example](https://user-images.githubusercontent.com/2194876/187403259-24207b79-559b-4fc5-ae98-e587aaaf41fe.jpg)

**Comment by realLiangshiwei** [comment]
I will check it

**Comment by sebitsi** [comment]
@realLiangshiwei 

It will be nice if HideAbpEndpoints method could accept boolean parameter like "hideABPSchemas".

Or better: Expression parameter -> we could define logical expression what to hide.

**Comment by realLiangshiwei** [comment]
I think we also should hide ABP schemas when calling `HideAbpEndpoints()`, it's reasonable.

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/pull/13876#issuecomment-1232321779

**Comment by sebitsi** [comment]
@realLiangshiwei 
I am sorry that you have decided not to implement this improvement.

I still think that you should. 
With some expression like 

`HideAbpEndpoints(key => !(key.StartsWith("jep") || key == "RemoteServiceErrorResponse" || key == "RemoteServiceErrorInfo" || key == "RemoteServiceValidationErrorInfo"));  
`

From user (my) point of view method HideAbpEndpoints is not fully functional because it doesn't hide ABP schemas.
If some of them are required you should unhide them like i did in upper expression. 

Regards.

**Comment by realLiangshiwei** [comment]
Hi,

It's not possible to implement, maybe the developer will return ABP DTOs, for example:

```csharp
public class MyUserAppService : ...
{
      public async Task<IdentityUserDto> GetAllUsersAsync()
      {
           //... 
      }
}
```

it can cause other problems, so It's better for developers to control themselves

**Comment by sebitsi** [comment]
I understand your point.

But, if someone use HidedAbpEnpoint - it will be nice if there is possibility to inject expression.
If there is no expression (default), schema is not filtered.

What do you think ?
