### ISSUE TITLE
Isolating ABP database structure requirements....

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1387]
Hi,

I am looking to use abp.io with an existing SQL Server database. We don't use EF Migrations (and don't plan to) preferring [DbUp](https://dbup.readthedocs.io/en/latest/).

I am happy to "pollute" the database with the EF Migrations table and use the [CLI DbMigrator](https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-MVC-Template#using-the-dbmigrator-application). 

However I want to "know" which tables belong to ABP so that we don't have to worry about them from a DBA point of view. So while most of them are in the format:

`Abp<TableName>` I then note that we also have `IdentityServer<TableName>`. So is it possible to either:

a) Put all the ABP tables in their own schema via `Abp.AbpUserRoles`, `Abp.IdentityServerClientGrantTypes`
b) Prefix the IdentityServer tables with Abp so that we end up with AbpIdentityServerClientGrantTypes

1) I would prefer that both a) and b) are implemented but my preference is at least a).
2) Also unless I am using IdentityServer for auth why do I need to have those tables (if the idea is to keep things simple that we create all the tables irrespective of what features are used then I am good with that, but that makes 1 more of a must)

**Comment by hikalkan** [comment]
Hi,

1. Every module has option to change schema & table prefix. Examples:

````csharp
IdentityServerDbContext.TablePrefix = "AbpIdentityServer";
IdentityServerDbContext.Schema = "Abp";
````

Run this code in the beginning of your application. They are static properties. You can add this code to Program.cs for all db-using applications (migrator, web... etc.).

2. If you don't use IDS4, you can remove the related module packages, remove ConfigureIdentityServer in your migration dbcontext and add a new migration which will delete the tables.
IDS4 modules are added in the startup template since most applications may need it and it is a bit hard to configure it :)

**Comment by natiki** [comment]
@hikalkan Thanks for that. However it would be better if ABP defaulted to xxxx.Schema = "Abp" by default. DBA's would definitely appreciate that.

**Comment by hikalkan** [comment]
>However it would be better if ABP defaulted to xxxx.Schema = "Abp" by default

I personally don't like schemas :grin:
However, we can consider make it easier for all modules with a single point configuration. Created an issue for it: https://github.com/abpframework/abp/issues/1429

**Comment by natiki** [comment]
Thanks for #1429. This will be beneficial as it makes the database side of things very self contained. It is a lot easier to lock down an entire schema once for security and never have to worry about having to keep doing it each time the data structure changes as ABP evolves ;-)

**Comment by SphinxGraph** [comment]
While fiddling around with the microservices-demo, I came across the schema issue.
I had to set the schemas at the following points, which is pretty ugly:

```csharp
public class Program {
	public static int Main( string[] args ) {
		IdentityDbContext.TablePrefix = string.Empty;
		IdentityDbContext.Schema = "Identity";

		IdentityServerDbContext.TablePrefix = string.Empty;
		IdentityServerDbContext.Schema = "IdentityServer";

		SettingManagementDbContext.TablePrefix = string.Empty;
		SettingManagementDbContext.Schema = "SettingManagement";

		PermissionManagementDbContext.TablePrefix = string.Empty;
		PermissionManagementDbContext.Schema = "PermissionManagement";
	}
}

public class AuthServerDbContext : AbpDbContext<AuthServerDbContext> {
	public AuthServerDbContext( DbContextOptions<AuthServerDbContext> options )
		: base( options ) {
		}

	protected override void OnModelCreating( ModelBuilder modelBuilder ) {
		base.OnModelCreating( modelBuilder );
			modelBuilder.ConfigureIdentity( options => {
			options.TablePrefix = string.Empty;
			options.Schema = "Identity";
		} );
		modelBuilder.ConfigureIdentityServer( string.Empty, "IdentityServer" );
		modelBuilder.ConfigureAuditLogging( string.Empty, "AuditLogging" );
		modelBuilder.ConfigurePermissionManagement( string.Empty, "PermissionManagement" );
		modelBuilder.ConfigureSettingManagement( string.Empty, "SettingManagement" );
	}
}
```

There must be a easier way to configure this.

**Comment by hikalkan** [comment]
See https://github.com/abpframework/abp/issues/1429#issuecomment-541096039
