### ISSUE TITLE
Cannot run Blazor Server project using LeptonX Lite theme on the preview version (6.0.0-rc.3)

### ISSUE THREAD

**Issue by huytnd** [abpframework/abp#13883]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* ABP Framework version: 6.0.0-rc.3
* User Interface: Blazor Server
* Database provider: EF Core/MS SQL Server
* npm version: 8.18.0
* ABP CLI version: 6.0.0-rc.3
* Exception message: AbpException: Could not find the bundle file '/libs/bootstrap/css/bootstrap.css' for the bundle 'Blazor.LeptonXLiteTheme.Global'!
* Steps needed to **reproduce** the problem:
1. Rebuild the whole solution.
2. Run ``npm install`` on ABP01.Blazor project.
3. Run ``abp install-libs`` on ABP01.Blazor project.
4. Run 3 projects: ABP01.AuthServer, ABP01.Blazor, and ABP01.HttpApi.Host using ``dotnet run`` command.

![image](https://user-images.githubusercontent.com/2102905/187630577-e59684ab-722f-4617-9a34-cacce9a04462.png)
![image](https://user-images.githubusercontent.com/2102905/187630929-a3e159d6-7acd-4ac6-8880-ec06531ab4c9.png)

**Comment by enisn** [comment]
Are you getting that error while trying to login?
Can you try executing `abp install-libs` command in your **ABP01.AuthServer** project too?

**Comment by huytnd** [comment]
Yes, I did, the ABP01.AuthServer project worked, only ABP01.Blazor had that issue.

**Comment by enisn** [comment]
Can you try removing `yarn.lock` file and make sure all abp packages are `6.0.0-rc.3` in `package.json` _(except LeptonXLite, it should be `1.0.0-rc.4`)_

Then try running `abp install-libs` command.

If there is a problem in `package.json` in newly created projects let us know.

**Comment by huytnd** [comment]
The original package.json content:
![image](https://user-images.githubusercontent.com/2102905/187640772-de8dc898-b28c-4489-82fd-5e89136e3df0.png)
After modified follow your guide:
![image](https://user-images.githubusercontent.com/2102905/187641056-1140693c-746b-4b96-98cb-d6ce84c09253.png)
Result: the issue still appears.
![image](https://user-images.githubusercontent.com/2102905/187642295-f527fb7d-7623-4968-97da-bc1a2594e8f8.png)

**Comment by huytnd** [comment]
The package.json content after modified:
![image](https://user-images.githubusercontent.com/2102905/187642904-26a0abe3-3d6c-4daf-bd06-fdf857e27764.png)
The result is the same.
![image](https://user-images.githubusercontent.com/2102905/187643102-47f0d31c-be65-4d2e-b10f-2a4ea335b649.png)
Only the AuthServer worked.
![image](https://user-images.githubusercontent.com/2102905/187643251-a0e495d9-3b95-4649-a4c3-fbc1ddf7eb93.png)
![image](https://user-images.githubusercontent.com/2102905/187643314-06fac29d-1b85-4624-a587-e1231a69d9ef.png)

**Comment by ILAOHE** [comment]
Has this problem been solved?

> 修改后的 package.json 内容：![image](https://user-images.githubusercontent.com/2102905/187642904-26a0abe3-3d6c-4daf-bd06-fdf857e27764.png)结果是相同的。 ![image](https://user-images.githubusercontent.com/2102905/187643102-47f0d31c-be65-4d2e-b10f-2a4ea335b649.png)只有AuthServer工作。 ![图像](https://user-images.githubusercontent.com/2102905/187643251-a0e495d9-3b95-4649-a4c3-fbc1ddf7eb93.png) ![图像](https://user-images.githubusercontent.com/2102905/187643314-06fac29d-1b85-4624-a587-e1231a69d9ef.png)

Has this problem been solved?

**Comment by huytnd** [comment]
@ILAOHE not yet.

**Comment by ILAOHE** [comment]
@enisn  
What should we do?

**Comment by ILAOHE** [comment]
@huytnd 
I have solved this problem. You need to download and install the Yarn client, and then execute abp install libs
