### ISSUE TITLE
How to use EntityHistoryHelper functionality 

### ISSUE THREAD

**Issue by surendrakandira93** [abpframework/abp#13887]
I want to use entity change functionality and enabled it from .Application section
but it's not working.

When I download github repo and check in .NetCore EntityFramwork IEntityHistoryHelper class. but this using in commonDBContext but object not created.

Can you please explain how to resolve dependency or user IEntityHistoryHelper in application.   
   

* Your **ABP Framework version**.= 7.3.0.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI = MVC
* Your database provider(EF Core/MongoDB)=EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by ebicoglu** [comment]
We got a community post that redirects to this issue.  Why did you create a community post request to ask a question?
