### ISSUE TITLE
MVC Getting Started: InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.

### ISSUE THREAD

**Issue by JesseTrains** [abpframework/abp#13892]
Just following the Getting Started tutorial to the letter here, with MVC/Razor Pages UI on EntityFramework Core and Tiered architectuire.

https://docs.abp.io/en/abp/latest/Getting-Started-Running-Solution?UI=MVC&DB=EF&Tiered=Yes

Tried the tutorial multiple times, Same issue. 

"InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'."

after clicking the Login button on the BookStore app. Swagger, identity and the app load up fine, but the app is unusable due to inability to load the login page. Can't proceed further with the other tutorials or demo different ideas before purchasing if I can't get past Getting Started. This issue is only happening with MVC/Razor pages version (it worked in angular version of the tutorial, but we prefer MVC/Razor pages).  ABP and all versions are up to date.

**Comment by realLiangshiwei** [comment]
Please check https://github.com/abpframework/abp/issues?q=Unable+to+obtain+configuration+from%3A+%27System.String%27

**Comment by JesseTrains** [comment]
> Please check https://github.com/abpframework/abp/issues?q=Unable+to+obtain+configuration+from%3A+%27System.String%27

Didn't find the answer in those topics, but apparently the solution was getting Redis up and running properly in the windows subsystem for linux.
