### ISSUE TITLE
ABP Samples update

### ISSUE THREAD

**Issue by element-dlapointe** [abpframework/abp#13894]
ABP Commercial 6.0.0-rc.3
EfCore / Mysql
Not Layered (create from ABP Suite)

Hi,

Could it be possible to update the sample [Sample Login With No Tenant](https://github.com/abpframework/abp-samples/tree/master/SignInWithoutSpecifyingTenant) with the new openiddict? 

As the current example does extends `IdentityServerSupportedLoginModel` i would expect it wont work for the new version without identityServer.

Thank you

**Comment by maliming** [comment]
OK, I will update the sample.

**Comment by element-dlapointe** [comment]
Wow, thats reactive! 

Thank you
