### ISSUE TITLE
Abp Commercial Leption 'style' config not working

### ISSUE THREAD

**Issue by element-dlapointe** [abpframework/abp#13905]
ABP Commercial 6.0.0-rc.3
Razor (no tiered) created from ABP Suite
Ef core / MySql

Hi all,

Im trying to change the 'style' of the lepton theme using the config in the *.web modules but it has no effect (tried style1 to style6 and even the MenuPlacement.Top). Actually, im not even sure the lepton theme does load correctly.

Here is the appsettings.json from the web module :
```
"Settings": {
    "Volo.Abp.LeptonTheme.Style": "Style4", /* Options: Style1, Style2... Style6 */
    "Volo.Abp.LeptonTheme.Layout.MenuPlacement": "Top", /* Options: Left, Top */
    "Volo.Abp.LeptonTheme.Layout.MenuStatus": "AlwaysOpened", /* Options: AlwaysOpened, OpenOnHover */
    "Volo.Abp.LeptonTheme.Layout.Boxed": "False" /* Options: True, False */
  }
```

This is what i have, whatever setting in appsettings 
![image](https://user-images.githubusercontent.com/63807551/187995349-07a00404-4759-407f-a79a-676c09be27b9.png)

Im using Edge v104 on Windows 10.
![image](https://user-images.githubusercontent.com/63807551/187995917-6f83ea76-6388-410a-9b9b-a16811a3431a.png)

Thank you

**Comment by element-dlapointe** [comment]
Ive made some progress. For some reason, ABP Suite did install LetponX instead of Lepton. I manually replaced all the LeptonX packages (all the nugget and @volo/abp.aspnetcore.mvc.ui.theme.leptonx) and then changed all the references (in the code) from LeptonX to Lepton.

Now here is what i have :
![image](https://user-images.githubusercontent.com/63807551/188001418-93b95afa-2530-4d01-a28d-05c67c24855f.png)

But, as you can see, the menu is still on left and not on top (if i use the 'style selector / cog' and select top, the menu moves but its not setting it on top as default like.

The 'style selector' also doesnt change the style, whatever i click the page reload with the same 'style'. If i change in the appsettings tough, the style is applied but with the same problems.

Also, my menu doesnt open anymore (the parent menu Saas, Admin and Setup). Nothing happens when i click on it. There aint no JS error at all.

One thing i noticed, in the *.Web modules/Themes/ there is still a folder LeptonX, i guess thats what is missing?! But not sure where to find the proper code to replace it?
![image](https://user-images.githubusercontent.com/63807551/188001764-45462d77-e949-4094-b164-d829a5b1f1b9.png)

Thank you

**Comment by element-dlapointe** [comment]
Ok, i think i am a bit confused. LeptonX seems to be the lastest version of ABP theme. (i was expecting the opposite) I rolled back all the change to get to Lepton but i am back at the same point, i cant change the style nor the position of the header.

**Comment by element-dlapointe** [comment]
Ill be clossing this issue, i kind of sorted out but i think docs should be a bit more clear about it, i guess im not the only one getting confused.

- LeptonX is the brand new theme shipped with v6+
- LeptonX comes in 2 flavor, commercial and lite
- LeptonX  has no 'style' like the previous Lepton but you can pick between dim, light, dark.
- LeptonX  has no options to put the menu on top
- Lepton is the original theme shipped with previous versions
- Lepton  has multiple different styles
- Lepton  has options to put the menu on top or on the left

What really confused me, is that when you create with ABP Suite a new project and select LeptonX, in the appsettings, you forgot to remove the config for Lepton (Styles, MenuPostion etc..) so i was expecting to be able to pick between the 6 differents style mentioned on ABP commercial website. (mostly lost half a day trying to understand why those config was not reflecting on the UI)

Before closing, can i ask the following ? 
1. Is there a LTS plan for Lepton? Our specific use case requires a top menu so we would probably switch back to Lepton so we have this option out of the box
2. Why releasing a new Theme which doesnt cover the feature set of the previous one? Multiple color scheme, Menu position, full screen button...

Thank you

**Comment by realLiangshiwei** [comment]
Thanks for your feedback, we will consider this.

When you create a new project via Suite, you can select the UI theme with `Lepton` instead of `LeptonX`.

**Comment by element-dlapointe** [comment]
Hi @realLiangshiwei, do you know about the support plan (we are on commercial)? I just want to make sure Lepton support wont be drop anytime soon if we are to create our new projects with this theme.

Thank you

**Comment by element-dlapointe** [comment]
im closing as i dont want to add noise but i would like to get the information :D

**Comment by element-dlapointe** [comment]
Is it possible to get an answer to the first question at least, what’s the support plan for Lepton theme (not leptonx) as if we decide to move forward with this one, we need to make sure there is a long term support plan around it.

Thank you
***@***.***


Dominic Lapointe​




Global IT Development Director

Element Materials Technology


No. 60, 1175 Avenue Lavigerie

Quebec City

,

Quebec


G1V 4P1

,

Canada



M +1 418 569 4753<tel:+1%20418%20569%204753>

O +1 418 914 4340<tel:+1%20418%20914%204340>


ext. 23315


***@***.******@***.***>

www.element.com<http://www.element.com/>


***@***.***<https://www.linkedin.com/organization-guest/company/element-materials-technology?challengeId=AQFf9AemZ4SobwAAAXOQwivOsnkHiTt2ByoCkOxVQjOGOjRlivicVgYlN1dz5QXjId9bpa0keWzfVxhl8KPj78uD6-S6nfqRsg&submissionId=e49e0dc0-96a3-2516-27fa-ee2e8c42b177>


***@***.***<https://twitter.com/ElementTesting/>

***@***.***<https://www.instagram.com/elementtesting/>

***@***.***<https://www.youtube.com/c/ElementTesting>
        ***@***.*** <https://elementmaterials.eu.qualtrics.com/jfe/form/SV_3xQqm84s6IydI5D>




________________________________

**Comment by realLiangshiwei** [comment]
Could you create a question on the support website?  thanks.

**Comment by element-dlapointe** [comment]
will do, thanks
