### ISSUE TITLE
Questions about obtaining MultiTenancySides in the process of obtaining permissions

### ISSUE THREAD

**Issue by LFeYls** [abpframework/abp#13919]
* ABP Framework version 5.3.1

When I designed the extended user system, I did not use IdentityUser, but created a new table that did not use IMutiTenant, but I used IMutiTenant when extending permissions and roles, because I want these users to have different permissions in different tenants. Authentication is implemented by the IExtensionGrantValidator extension to IdentityServer4.
After get the token without passing in the TenantId from identity auth server, then get the permission (tenant specified in the Url: api/abp/application-configuration?__tenant=default) by parsing the tenant through the Url. I found that I could not get the permission defined by MultiTenancySides.Tenant, and finally found the cause of the problem through the source code , because in the PermissionChecker class
`MultiTenancySides multiTenancySide = principal != null ? principal.GetMultiTenancySide() : this.CurrentTenant.GetMultiTenancySide();`
The  MultiTenancySides parsing method here is based on the principle as the preferred parsing method. I am thinking, why not use CurrentTenant directly for parsing, because the first parsing of CurrentTenant parsing is also performed through principal. 
Or is there a more rigorous security logic in the design in the source code?
Thanks!

**Comment by maliming** [comment]
The `claimsPrincipal` is a parameter of `IsGrantedAsync`, It can be custom instead of using `CurrentTenant`.
