### ISSUE TITLE
ABP.IO register user error

### ISSUE THREAD

**Issue by marcelo-maciel** [abpframework/abp#1392]
When I tried register my user "marcelo-maciel" at abp.io i got an HTTP ERROR 500

**Comment by hikalkan** [comment]
Have you tried this: https://github.com/abpframework/abp/issues/1380#issuecomment-505755687

**Comment by marcelo-maciel** [comment]
Yes. After your link I tried P@$$w0rd as sample and the same problem occours.

**Comment by hikalkan** [comment]
@maliming can you try to repeat this?

**Comment by maliming** [comment]
@marcelo-maciel Can you try another username?

**Comment by marcelo-maciel** [comment]
Now I log in OK with "marcelo-maciel", but when I log off and click the login button at the top right of the site to add new user, an auto login with the user "marcelo-maciel" occurs. If I wanted to login with another user or create a new user, I could not.

**Comment by maliming** [comment]
You can try it in chrome's incognito window.

**Comment by marcelo-maciel** [comment]
I logged with marcelo-maciel on chrome incognito and not selected "remember me" flag.
![image](https://user-images.githubusercontent.com/4993482/60315731-37850f80-993e-11e9-8118-089f606522d6.png)

Logged out
![image](https://user-images.githubusercontent.com/4993482/60315784-761aca00-993e-11e9-9ebe-c1931aff437a.png)

And click again on Login
![image](https://user-images.githubusercontent.com/4993482/60315807-8af75d80-993e-11e9-907e-100ad16771f6.png)

Auto login with marcelo-maciel
![image](https://user-images.githubusercontent.com/4993482/60315830-9d719700-993e-11e9-98fc-586ab5f46a73.png)

**Comment by maliming** [comment]
@marcelo-maciel Because you are still logged in to account.abp.io. You just logged out of the abp.io website.

**Comment by marcelo-maciel** [comment]
@maliming So what is this log off for if I can not sign in with another account?
