### ISSUE TITLE
invalid token error

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#13932]
If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**. 5.3.3
* Your **User Interface**  Angular
* Your database provider: EF Core

We send to user custom password reset link.  On Abp 4.4.4 with "Authorization Code Flow" generated link was working successfully after upgrading to 5.3.3 and switching Resource owner password we started to get error.

```
var user = new IdentityUser(GuidGenerator.Create(), input.Email, input.Email, tenant.Id);
var resetToken = await userManager.GeneratePasswordResetTokenAsync(user);
                var angularUrl = configuration.GetValue<string>("App:AngularUrl");
                resetLink = 
                    $"{angularUrl}/account/reset-password?userId={user.Id}&{TenantResolverConsts.DefaultTenantKey}={user.TenantId}&resetToken={UrlEncoder.Default.Encode(resetToken)}";
await emailSender.SendAsync(...)
```

User gets error "Invalid token" after clicked submit button(tenant selector does not appear although we create link for a tenant:

![image](https://user-images.githubusercontent.com/13360669/188647809-8cf08a66-47d9-4128-9af7-d48b6ae17a7d.png)
![image](https://user-images.githubusercontent.com/13360669/188647943-ac66dee0-7bd6-4ea6-b882-6466342ce3c5.png)

 If I use "forgot password" link it works correctly.

generated from login page(forgot password link)
```
https://test-services.mycompany.com/account/reset-password?userId=3a0623d9-143b-1ada-20b5-2c1f8a01bf39&__tenant=3a0623d9-1033-160e-8473-4caba3018f69&resetToken=CfDJ8PzoKQY46uFFnVXG%2BqnX%2F1khAaI8OaXEDm6Si%2FnLyp%2FsbF0KPVKH%2B0Kqa4X9iboa2HJ%2BAqP0JaoZNBt2kmfx2ovczrxN8NsIwTNhsKXtxMa0ZszF2arBtapbFcBKd%2B%2FRKUmwA7FX9pfi4Nylq5d1PcjKLJPWRkyC%2FZL%2B2BsdQegEnIjfWoHzfrpypTMpmh0Pzn%2B3b6YwqteABZhJxd4aHaGNw91GpXvUpKb8mCvuOxvf

```
generated from code:
```
https://test-services.mycompany.com/account/reset-password?userId=3a062416-4b25-ccde-e983-cd31cc114aa9&__tenant=3a062416-448a-59ab-1556-11997bc2af62&resetToken=CfDJ8PzoKQY46uFFnVXG%2BqnX%2F1nL0c5eE23xgBp6jvvbZ8%2F6GiD1%2F%2BCwdxxTp3FiS%2BE3tMourKnxjjfgkBlmUEVTMPI43Sbsc2E%2FowAUqHRAPMDaROLrVW7d3PhplB4Ah27TwF0JJlc73MNP2uo8Pxf6h9NWBjRpownhb%2B7DS1z5yqNH9%2BnlsZ02Pb1wIou2AX1S%2BySuk%2B60ZQQh9dKU0UtcNLNlgh9Jt9V2DII%2F6KdtFPXW
```

**Comment by AdemAygun** [comment]
do you have any suggestions

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by AdemAygun** [comment]
- Create a new project (Angular-EF Core -  IDS no seperate)
- Convert to [Resource owner password](https://docs.abp.io/en/abp/latest/UI/Angular/Authorization#resource-owner-password-flow)
- Write a method in a appservice like below:
```
public async virtual Task<string> GetResetLinkAsync()
        {
            var user = await userManager.GetByIdAsync(CurrentUser.Id.Value);
            var resetToken = await userManager.GeneratePasswordResetTokenAsync(user);
            var resetLink =$"http://localhost:4200/account/reset-password?userId={user.Id}&{TenantResolverConsts.DefaultTenantKey}={user.TenantId}&resetToken={UrlEncoder.Default.Encode(resetToken)}";
            return resetLink;
        }
```

- Run application and try reset link

I have reproduced but could not catch same issue. Reset link has worked successfully

**Comment by AdemAygun** [comment]
we solved via this [solution](https://stackoverflow.com/a/44168033/4458106). This problem is not related to ABP :)
