### ISSUE TITLE
The planned release date for the 6.0.0 Stable version is September 06, 2022.

### ISSUE THREAD

**Issue by vioKamran** [abpframework/abp#13931]
Hi Guys
**Well, today is September 6.**
What time do you update today?

**Comment by EngincanV** [comment]
Hi, the planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version changed to **September 13, 2022**.

**Comment by vioKamran** [comment]
> Hi, the planned release date for the [6.0.0 Stable](https://github.com/abpframework/abp/milestone/71) version changed to **September 13, 2022**.

Ok .
Thankyou .
