### ISSUE TITLE
ABP 6.0.0-rc.3 cannot load Volo.Abp.Identity.Domain after importing Volo.Identity module with source

### ISSUE THREAD

**Issue by dirraj** [abpframework/abp#13936]
Try:

`abp new Bookshop -t app -u blazor --preview --no-random-port`

Now move into solution folder (aspnet-core folder) if necessary.

Then:

`abp add-module Volo.Identity --with-source-code --add-to-solution-file`

On the final step after the empty EF migration is created, the following exception is thrown.

`System.IO.FileLoadException: Could not load file or assembly 'Volo.Abp.Identity.Domain, Version=6.0.0.0'`

This exception occurs whether or not you add the module immediately. For example you can instead run Initial migration, compile, and run the application (HttpApi.Host). 

Either way when the module is added, with source, the System.IO.FileLoadException is thrown.

And now HttpApi.Host can no longer be started without a HTTP 500.30 error.

**Comment by maliming** [comment]
hi

Can you try to add Account module source code as well?

**Comment by dirraj** [comment]
The Account module is a dependency of Identity and is added automatically.

Adding it manually has not resolved the issue.

Unrelated, but a problem seen with the Account module is that the Volo.Abp.Account.Web.OpenIddict project is not added to HttpApi.Host to replace the NuGet Package. The package must be removed manually and the project reference added manually. The FileLoadException occurs both before before and after correcting this dependency issue.

**Comment by maliming** [comment]
> The FileLoadException occurs both before before and after correcting this dependency issue.

please share your project to liming.ma@volosoft.com

**Comment by dirraj** [comment]
Shared with you now.

[Screen capture of exception thrown by DbMigrator during initial database generation](https://pasteboard.co/WJFU7ilXkTZO.png)

Note that a fix has been applied to this project after the Account module was installed by Identity module. This is to resolve a dependency issue.  I remove Volo.Abp.Account.Web.OpenIddict nuget package from Bookshop.HttpApi.Host and replace it with the correct project reference.

**Comment by maliming** [comment]
hi

Please try to download the OpenIddict module source code and add to your project.

`abp get-source Volo.OpenIddict --preview`

**Comment by dirraj** [comment]
Yes, adding Volo.OpenIddict resolves this issue.

This works even using add-module without having to update all references manually.

So to avoid errors the order is as follows:

abp new Bookshop -t app -u blazor --no-random-port **-v 6.0.0-rc.3**
abp add-module Volo.OpenIddict --with-source-code --add-to-solution-file
abp add-module Volo.Identity --with-source-code --add-to-solution-file

The first add-module manages to run the initial EF migration on the database, whereas using Identity first would cause the FileIOException before this can happen.

I still had to manually replace the NuGet reference in HttpApi.Host with the project reference (Volo.Abp.Account.Web.OpenIddict).

Note that given the release of 6.0.0-rc4 there was now downgraded reference error on Volo.Abp.AspNetCore.MultiTenancy in HttpApi.Host asking for rc4 where rc3 is used. This is despite being sure to use rc3 everywhere and using rc3 CLI.

Having upgraded CLI to rc4 and using --preview, this is no longer an issue of course.

**Overall I've found the OpenIddict module source is still required to avoid the FileIOException in 6.0.0-rc4.**

Thank you ma.
