### ISSUE TITLE
Reduce cache durations for development environment

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#13952]
In development environment, we can consider to disable caching or reducing cache durations for some points, like the `MvcCachedApplicationConfigurationClient` class. Such caches are good for production, but may confuse developers (they may not see result of some changes immediately). Create a list of such points we can change, then implement it.

**Comment by maliming** [comment]
- `IDistributedCache<IdentityModelTokenCacheItem>`  
  Absolute expiration duration (as seconds) for the access token cache. Default: 1800 seconds (30 minutes)
- `IDistributedCache<IdentityModelDiscoveryDocumentCacheItem>`
   Absolute expiration duration (as seconds) for the DiscoveryDocument cache. Default: 1800 seconds (30 minutes)

- `IDistributedCache<TenantConfiguration>` Absolute expiration relative to now.  Default: 5 minutes
- `IDistributedCache<ApplicationConfigurationDto>` Absolute expiration relative to now.  Default: 5 minutes

**Comment by maliming** [comment]
We can disable caching in the module, but some modules are class libraries, they currently cannot use `IWebHostEnvironment`. We can consider introducing an `IAbpEnvironment`.

Or caching can also be disabled in the startup templates.

**Comment by hikalkan** [comment]
`IAbpHostEnvironment` is a good idea (Not `IAbpEnvironment`, but `IAbpHostEnvironment` as naming). Default value can be `Production` and we get it from the .net's hosting system wherever possible. We should also allow developer to override it while creating/adding the abp application (you can add `Environment` property to https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/Volo/Abp/AbpApplicationCreationOptions.cs).
