### ISSUE TITLE
MVC - Add active page name to all pages 

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#13964]
**App:** MVC - EfCore
**Version -Theme:** 6.0.0-rc.3 - Basic Theme
**Problem:**  For all pages, the page name should be placed at the beginning of the page. Because we can't understand which page I am on

**Note:** This should be fixed on all pages

![image](https://user-images.githubusercontent.com/99716457/187850171-72af8672-1dec-4812-8e38-f92966d97aaa.png)

**Comment by maliming** [comment]
This is not related to the basic theme but instead to pro moduels.
