### ISSUE TITLE
Calling SetCsrfCookie in SwaggerUI using reverse-proxy is not working

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#13961]
I'm using ABP 5.3.3.

If project is deployed behind proxy calling SetCsrfCookie is not working.

I noticed that there is no property baseUrl in configObject passed to abp.SwaggerUIBundle function.

I have some workaround:

```
app.UseAbpSwaggerUI(options =>    {
    var pathBase = configuration.GetValue<string>("App:PathBase", "");
    if (!String.IsNullOrEmpty(pathBase))
    {
        options.ConfigObject.AdditionalItems.Add("baseUrl", pathBase.EnsureEndsWith('/'));
    }
});
```
But it will be nice if you can integrate this in your module.
It will be better solution if you can read httpContext: http.Request.PathBase

Regards

**Comment by realLiangshiwei** [comment]
ABP doesn't know your deployment environment, It might be a little weird to add these configs to the template.

https://github.com/abpframework/abp/blob/69ba1aebb71157512b0ccd33392029b2ed27a3bc/framework/src/Volo.Abp.Swashbuckle/wwwroot/swagger/ui/abp.swagger.js#L9

But ABP allows you to add baseUrl, I think that's enough

**Comment by sebitsi** [comment]
@realLiangshiwei 

I'm sorry i don't understand your point.

Does ABP swagger module support deploy behind reverse-proxy ?
If it does, please point me to example or docs how i can configure it.

I follow swashbucle's [Support and Guidance for Reverse Proxy / Virtual Dir Environments](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1953) post.
As you can see - from version 6 - swashhbucle has no internal logic anymore.
I takes all that it needs from [UseForwardHeaders Middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1).

So if i put 
```
app.UsePathBase(pathBase);
app.UseForwardedHeaders();
```
in pipeline, swagger is working perfect with or without proxy.

Except ABP part. ABP swagger module doesn't  follow same guidance. I can't see where in code abp.appPath or configObject.baseUrl is set.

So my suggestion is in that i think you should implement same without any additional configuration.

My code is only workaround not code you put in swagger module.

If i missed something please let me know.

Regards.

Edvin
