### ISSUE TITLE
Upgrade to ASP.NET Core 3.0 RC

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1396]
Once Microsoft release it, we will work on the upgrade.

**Comment by wocar** [comment]
Im trying to use Abp with Blazor (server side) and it doesnt seem to work because Abp references the 2.2.* packages. I was just curious, is there a way I can do a workaround for this? Thank you

**Comment by hikalkan** [comment]
I don't know a way of it. I think MS will release RC in a few weeks, then we will upgrade to it.

If anyone knows a way, it is appreciated.

**Comment by geffzhang** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/ preview-7 has go live

**Comment by hikalkan** [comment]
It is not RC yet :) However, we will start to upgrade it in the next weeks.

**Comment by maliming** [comment]
>karelz: Preview 7 is RC. It is go-live license.

https://github.com/dotnet/core/issues/3079#issuecomment-516986501

**Comment by xyfy** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/
![{ACEB83AB-3D8B-490B-A295-9ADA6D1099A0}_20190808175723](https://user-images.githubusercontent.com/7838147/62757298-7d8cd180-baad-11e9-99c5-359595ec863e.jpg)

**Comment by xyfy** [comment]
it is RC now.
![{604B5D08-515A-45D7-9EE1-91943531B20E}_20190809135525](https://user-images.githubusercontent.com/7838147/62757324-8e3d4780-baad-11e9-8406-63c6d085d767.jpg)

**Comment by hikalkan** [comment]
Started to working on this (https://github.com/abpframework/abp/tree/aspnetcore-3.0). The progress until now is fine. I am getting weird errors but fixing one by one :)

**Comment by maliming** [comment]
IdentityServer already supports Net Core 3.0

https://github.com/IdentityServer/IdentityServer4/releases/tag/3.0.0
https://leastprivilege.com/2019/09/08/identityserver-for-asp-net-core-3/

**Comment by hikalkan** [comment]
Thanks @maliming already upgraded: https://github.com/abpframework/abp/commit/29cb4a676b1d53cc0aef19eafb164e287a03d9f8
:)

**Comment by maliming** [comment]
.NET Core 3.0 Release Candidate 1

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-release-candidate-1/

**Comment by KevinFarrow** [comment]
.Net Core 3.0 will be release on Monday 23rd September as part of the online .Net Conf

**_"We intend to release the final version on September 23 at .NET Conf."_**

https://www.dotnetconf.net/?utm_source=dotnet&utm_medium=blog&utm_campaign=savedate

**Comment by hikalkan** [comment]
I know it will be released on .NET Conf. I will also talk in this conference about ABP framework :) 

![image](https://user-images.githubusercontent.com/1210527/65333244-ca91b680-dbc8-11e9-8987-0f639008b2e4.png)

https://www.dotnetconf.net/speakers

**Comment by wocar** [comment]
👏🏽👏🏽👏🏽👏🏽👏🏽👏🏽👏🏽 Will be there!! Excelente speaker 👌🏽👏🏽

**Comment by hikalkan** [comment]
Done! Used AspNet Core 3.0 preview9. Microsoft will release the final release today/tomorrow. We will then upgrade it and release again.
