### ISSUE TITLE
.NET 7 performance improvements and new features

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#13977]
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/

- Output Cache: https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#output-caching-middleware
Also mentioned here: https://github.com/abpframework/abp/issues/13951#issuecomment-1240292018

- Request decompression middleware: https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#request-decompression-middleware

Are they usefull for abp?

**Comment by maliming** [comment]
I think developers can enable the above features by themselves.
