### ISSUE TITLE
Suggestion: Graceful handling if Tenant not found

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#13976]
This not so graceful behavior exists at least on MVC client.
During development time when databases are deleted and re-created, browsers remember TenantId.
When application is launched and tenant does not exist anymore, "technical error" shows with information that tenant is not found.

Wouldn't be nice that login screen appears and maybe with javascript alert message that tenant is not found and therefore tenant should be set again during login process?

What do you think?

**Comment by sturlath** [comment]
This will come in version 6.0 https://github.com/abpframework/abp/issues/13146

**Comment by leonkosak** [comment]
Thank you!
