### ISSUE TITLE
Loading modules dynamically/conditionally.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#13983]
Is it possible to load module(s) at runtime instead of adding them using "DependsOnAttribute"? Or can you suggest a reasonable workaround compatible with Abp framework?

For example;

```cs
public class ModuleA : AbpModule 
{
    public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        if (...)
        {
            context.Services.AddDependentModule(typeof(ModuleX));
        }
        else 
        {            
            context.Services.AddDependentModule(typeof(ModuleY));
        }
    }
}

```

Instead of

```cs
[DependsOn(typeof(ModuleX))]
[DependsOn(typeof(ModuleY))]
public class ModuleA : AbpModule
...
```

**Comment by maliming** [comment]
When the `PreConfigureServices` method is executed, the dependencies of the modules have been determined, at this time we can't add new modules and their dependencies.

**Comment by y7MZ** [comment]
PreConfigureServices is just an example.

[Related Answer](https://support.abp.io/QA/Questions/3660/Loading-modules-dynamicallyconditionally#answer-0e8c7865-db4e-03e8-67ee-3a062e3c6b4d)

**Comment by jrocha** [comment]
I would like to have something like this as well. I'm having issues due the following block does not honor "Redis:IsEnabled" flag.

```
            context.Services.AddSingleton<IDistributedLockProvider>(sp =>
            {
                var connection = ConnectionMultiplexer
                    .Connect(configuration["Redis:Configuration"]);
                return new 
                    RedisDistributedSynchronizationProvider(connection.GetDatabase());
            });
```

**Comment by maliming** [comment]
hi @jrocha 

Please create a new issue to discuss your case.

Thanks.

**Comment by puschie286** [comment]
We came across the same problem / requirement and extended the module loader to support dynamic dependencies.
[Implementation (Gist)](https://gist.github.com/puschie286/13874f7a15eb4b2f8200bbb7aa38e346)

Its integrated into the regular abp module lifecycle
