### ISSUE TITLE
Tiered architecture - login animation or image

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#13991]
This UX behavior is noticeable the most for tiered architecture (separated identity server, api, web) at least for MVC GUI.
When tiered MVC (maybe even Blazor WASM and SS) is deployed and user go through login process, there is relatively long white (blank) page between login mask and first dashboard page inside abp app.

Is it possible to add simple, replaceable animation or image during described time period?
Let's say Google has such animation when you login to Gmail through accounts.google.com.

**Comment by sturlath** [comment]
Could this loading time also be related to this https://github.com/abpframework/abp/issues/13114#issuecomment-1222380803 ?

**Comment by leonkosak** [comment]
I know that Blazor WASM is really slow. :) But I am not interested only for Blazor WASM but also for tiered architecture animation (or static image) during login for MVC for instance.
This suggestion has also nothing regarding pre-rendering for Blazor projects.
