### ISSUE TITLE
ExtraProperties `AllowUserToEdit` parameter implementation [MVC/Blazor]

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#13999]
### Use-Case Example

(1) add custom configuration to a property of user
![image](https://user-images.githubusercontent.com/23705418/189637239-70269d69-c0c4-44a8-97dd-770c60158ba8.png)

(2) check it on the profile management page

![image](https://user-images.githubusercontent.com/23705418/189637278-8eebc39e-ccaa-4457-9bab-8dc8e4387d77.png)

**Comment by hikalkan** [comment]
It will be disabled by default.

**Comment by enisn** [comment]
awaiting blazor implementation

**Comment by cbogner85** [comment]
Hello, 

I just updated to ABP 6.0 final (MVC) and added 
` options =>
                        {
                           options.Configuration["AllowUserToEdit"] = false;
                        }`
to my ExtraProperties - however, they are still editable from the user's Account Manage Page. What am I doing wrong?

**Comment by enisn** [comment]
> Hello,
> 
> I just updated to ABP 6.0 final (MVC) and added ` options => { options.Configuration["AllowUserToEdit"] = false; }` to my ExtraProperties - however, they are still editable from the user's Account Manage Page. What am I doing wrong?

Which UI Type are you using?

**Comment by cbogner85** [comment]
Hi @enisn 

I'm using LeptonX Commercial 1.0.0-rc.7 for MVC

**Comment by cbogner85** [comment]
Hello  @enisn, 

it's easy to reproduce:

- create new solution with 6.0.0 final
- UI Framework: MVC
- Theme: LeptonX

Add to MyProjectModuleExtensionConfigurator:

![image](https://user-images.githubusercontent.com/49239838/194871994-e2f5ba20-01af-44ef-905f-084758c13a2c.png)

Run project, create a user and login as this user, go to My Account > Personal info:

![image](https://user-images.githubusercontent.com/49239838/194873440-edb79aa7-1342-4ea2-9f77-0a43976606a9.png)

As you see, it is editable.

Please reopen this issue and fix it. Thanks!

**Comment by enisn** [comment]
Hi @cbogner85 ,
It seems you're using commercial template.

I realized the issue and we've fixed it. It'll be released in patch version 6.0.1 as soon as possible.
