### ISSUE TITLE
Returned value of audit logs

### ISSUE THREAD

**Issue by XuJin186** [abpframework/abp#14002]
https://github.com/abpframework/abp/blob/664f8799a4d6f638a24483958cc0e98548eb76a2/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingHelper.cs#L176

Is there any plan to implement this TODO?
I want the implementation to record the return value of a method

**Comment by maliming** [comment]
hi

> I want the implementation to record the return value of a method


I think you can do this on the `PostContribute` method. Executing the `PreContribute` method multiple times is not a good way.
