### ISSUE TITLE
CORS issue on client side AJAX request

### ISSUE THREAD

**Issue by ertugrulbakidal** [abpframework/abp#14018]
* ABP Framework version: 6.0.0-rc.1
* User Interface: MVC
* Database provider: EF Core

Hi, I have 3 MVC Apps:
1) AuthServer (using OpenIddictModule)                                         => https://localhost:44395
2) Admin app (Web and API layers together in one project)            => https://localhost:44319
3) Client Web App                                                                             => https://localhost:44384

My AuthServer is separated so that I can authenticate users from both apps (Admin and Client). 
I can make API requests from https://localhost:44384 to https://localhost:44319  on the server side it works well. But When I make an API request on the client side I've got a CORS error. 

![abp_auth_issue](https://user-images.githubusercontent.com/40223108/190253341-560c0b3d-4724-4f7a-adeb-d88214268e44.png)
![abp_auth_issue1](https://user-images.githubusercontent.com/40223108/190253343-954bf4d6-ef09-4a76-8442-dc08ff163304.png)
![abp_auth_issue2](https://user-images.githubusercontent.com/40223108/190253345-8ec2a3b3-a7b4-43ea-b690-b45d0726cbf7.png)

**Comment by maliming** [comment]
hi

Please check your backend logs.

**Comment by ertugrulbakidal** [comment]
I've checked and the error message is **CORS policy execution failed, Request origin null does not have permission to access the resource.**.
[AdminAppLogs.txt](https://github.com/abpframework/abp/files/9575114/AdminAppLogs.txt)
[AuthServerLogs.txt](https://github.com/abpframework/abp/files/9575115/AuthServerLogs.txt)

**Comment by ertugrulbakidal** [comment]
Hi @maliming , 
Any ideas why I've got that issue?

**Comment by aelhadi** [comment]
If your code is Ok. try to clean your bowser cache.
delete all history and cookies...
