### ISSUE TITLE
CLI: Update ChangeThemeSelection.cs

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#14014]
We're considering using the Lepton Theme in templates for the **dev** branch. But while a user creating an application, LeptonX should be the default theme, change the CLI according to this change.

> Talk with @enisn, before starting the issue.

**Comment by hikalkan** [comment]
What is the status of this issue @EngincanV @enisn

**Comment by enisn** [comment]
We decided to move it to 7.1 milestone
