### ISSUE TITLE
Add ABP & authorization headers to HttpClient objects created using IAbpDaprClientFactory

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14026]
`IAbpDaprClientFactory.CreateHttpClient` is used to create `HttpClient` that communicates to other applications through Dapr.
If the target application is an ABP application, we typically want to add authorization and other standard headers to the request. We should provide a way to automate that or make it easy.

* Bearer authorization header (we may reuse `IRemoteServiceHttpClientAuthenticator` here)
* Other headers: CorrelationId, TenantId, Culture, X-Requested-With

**Comment by maliming** [comment]
> Other headers: CorrelationId, TenantId, Culture, X-Requested-With

There is no problem.

> Bearer authorization header (we may reuse IRemoteServiceHttpClientAuthenticator here)

The design of IRemoteServiceHttpClientAuthenticator requires `HttpRequestMessage` and `RemoteServiceConfiguration` which may not be reusable for Dapr.

**Comment by hikalkan** [comment]
>There is no problem.

OK, you can start from here.

>The design of IRemoteServiceHttpClientAuthenticator requires HttpRequestMessage and RemoteServiceConfiguration which may not be reusable for Dapr.

What we can do, so?

**Comment by maliming** [comment]
I will try to find a way.

**Comment by maliming** [comment]
Another problem is that `IRemoteServiceHttpClientAuthenticator` is **async** but `IAbpDaprClientFactory` is **sync**.
