### ISSUE TITLE
"Active" and "Lock..." should be selected when we open the "new user" dialog

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14032]
Because they will be checked in most cases.

I testes with the open-source app template with Blazor WASM UI. We should also check and apply for other UI types too.

![image](https://user-images.githubusercontent.com/1210527/190405464-a30fc74e-b648-407a-a55e-abd44658e55d.png)

For Angular, can you check @fatihskilic ?

**Comment by fatihskilic** [comment]
I checked for Angular UI. "Active" and "Lock..." is selected when we open the "new user" dialog.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/27730155/191181003-26900a9a-6dbb-45f1-b246-b46378616ff9.png">

**Comment by realLiangshiwei** [comment]
MVC UI works fine.
