### ISSUE TITLE
Test - ABP Templates 

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#14049]
We've already done this kind of general testing with [this issue](https://github.com/abpframework/abp/issues/11742) before and shared the results [here](https://github.com/abpframework/abp/issues/11742#issuecomment-1056643371).

Based on these results, issues were created for all supported interfaces and they were followed up with a [main issue](https://github.com/abpframework/abp/issues/11837).

As a result these desired changes need to be checked for all UI types.

- [x] Angular (#11840)
- [x] MVC (#11839)
- [x] Blazor ( #11838)

**Comment by gizemmutukurt** [comment]
There is no hide-show password option in Password field in Angular project

![image](https://user-images.githubusercontent.com/99716457/191896106-ef1972fb-10bb-4ff1-be27-7db082b444e1.png)
