### ISSUE TITLE
【feature】openIddict how to custom validation & token

### ISSUE THREAD

**Issue by xiexingen** [abpframework/abp#14057]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

i want to add custom generate token when generate token, and custom validation token when use token request.

background:
after generate token ,add this token to cache(user-token is 1-1,after added token replace previous token), when user access  check this token is in cache.(avoid user at the same time login in different browser)

abp 6.0.0.rc4

**Comment by realLiangshiwei** [comment]
I see that you created a [ticket](https://support.abp.io/QA/Questions/3709/Handling-login-mutex-with-OpenIDDict) for this, so I close this.
