### ISSUE TITLE
Enable OAuth External login Provider (Azure Ad) on ABP Framework(6.0)

### ISSUE THREAD

**Issue by element-cstudart** [abpframework/abp#14067]
_ABP Commercial v6.0.0-rc.4._

- MVC Not tiered
- EF Core MySQL

Hi all,

I am trying to enable OAuth external login via ABP Framework in order to be able to import users.

I followed the documentation https://docs.abp.io/en/commercial/latest/modules/identity/oauth-login to a enable OAuth. See my configuration below:
![image](https://user-images.githubusercontent.com/111079434/191067810-a30aef93-6a71-4167-90ed-c7b04b3d618a.png)

When I try to login using or when I try import users I am getting "External provider authentication failed".
![image](https://user-images.githubusercontent.com/111079434/191067676-f7072548-816d-49c0-b00a-522910495814.png)

**Comment by realLiangshiwei** [comment]
Hi,

We're not discussing commercials here, you can get support on https://support.abp.io.

BTW, you can see the error message is `Get discovery error`. so, I think your settings is incorrect, you can test your settings in other tools, like `postman` to check if it is work

**Comment by element-dlapointe** [comment]
So if we are commercial and out of ticket, its impossible to get any kind of help or submit issues?

**Comment by element-dlapointe** [comment]
@realLiangshiwei how can we submit a bug if we are out of ticket? We aint asking for help here but are facing a bug on ABP. The configs works pretty well in postman. 

We think it might be missing some parameter when sending the command, most probably the grant type.

Thank you

**Comment by realLiangshiwei** [comment]
Hi,

We always create a question for the current commercial version.

![image](https://user-images.githubusercontent.com/16813853/191264145-103a71f1-4b3d-4762-8fb9-0f7c7322c60d.png)

If you face a bug on the ABP commercial, you can write here. for example: we only provide `OAuth External login` feature for commercials, If we discuss it here, it will be a little strange. thanks for your understanding

If it's an ABP framework bug, you can open an issue on ABP repo,

**Comment by element-dlapointe** [comment]
Oh ok, that make sense then 👍
