### ISSUE TITLE
The SettingManagement module reported error 400 under HTTP

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#14089]
the server responded with a status of 400 (Bad Request)

No error is reported for HTTPS
HTTP complains

Step1:
Login 

Step2:
Click Settings Menu

My Local Environment:
Abp 6.0.0 - rc. 2
MVC
EF core

![22a151b6fcfe8ff4a83312f6ff66e70](https://user-images.githubusercontent.com/22017199/191475620-6002d4de-c0c5-41d4-821c-f3fc3b16d064.jpg)

Test Code：
https://github.com/344089386/AbpCSRFTest
 
@realLiangshiwei

**Comment by realLiangshiwei** [comment]
Try this if you want use HTTP

```csharp
Configure<AbpAntiForgeryOptions>(options =>
{
    options.TokenCookie.SameSite = SameSiteMode.Unspecified;
});
```
