### ISSUE TITLE
Extended AuditLog Module

### ISSUE THREAD

**Issue by totpero** [abpframework/abp#14080]
Hi,

I have next scenario:

- I have list of products (like eShopOnAbp https://www.eshoponabp.com);
- When I access one specific product (like this https://www.eshoponabp.com/products/3a044b27-9b1a-0e9c-25eb-c8441351f186), I have multiple product regions/boxes/panels';
- Every panel has a specific Entity linked to ProducEntity (Creator person details, Contact details, shipping details, characteristics, description details, reviews, FAQ product zone, etc. ) (Nr. 1 from the diagram.) 
- I want to use the audit logging module https://docs.abp.io/en/abp/latest/Modules/Audit-Logging , https://docs.abp.io/en/abp/latest/Audit-Logging;
- I want every panel to have its own history zone (Nr. 2 from the diagram.) 

Problem:
How can I identify  the history log for each table tied to product with a unique id (https://www.eshoponabp.com/products/3a044b27-9b1a-0e9c-25eb-c8441351f186) by using: AbpEntityPropertyChanges, AbpEntityChanges, AbpAuditLogs  (Nr. 3 from the diagram.) .

This is just an example, I want to make this history log module dynamically for the entire  application for different entities not just products (For example: persons, tenants, users, invoices)

![image](https://user-images.githubusercontent.com/1710257/191243039-3701072e-9b41-43d6-8842-497408eb54d3.png)

**Comment by gterdem** [comment]
Audit logging doesn't work entity-wise but you can enable auditing for all the entities and extend the Audit logging module and customize the UI to provide entity history for each entity in a segmented way.
