### ISSUE TITLE
Help wanted : OpenIddict External authentification (Google...)

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#14097]
Hello,

How to add external login (google, facebook....) to Abp OpenIddict? any documentation?

Best Regards

**Comment by aelhadi** [comment]
context.Services.AddAuthentication().AddGoogle(googleOptions =>
        {
            googleOptions.ClientId = configuration["Authentication:Google:ClientId"];
            googleOptions.ClientSecret =  configuration["Authentication:Google:ClientSecret"];
        });

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/Abp.LoginUi#external-login-ui
