### ISSUE TITLE
What documentation is being worked on this sprint?

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1409]
I was wondering what documentation is being worked on this sprint?

Any chance themeing documentation will be worked on?

**Comment by hikalkan** [comment]
I can't promise, sorry. But I can say that, we'll complete most of the documentation in July, this probably include theming.

However, I believe, investigating [the basic theme](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic) helps much more than reading a documentation. Just copy it & change.

**Comment by hikalkan** [comment]
Follow https://github.com/abpframework/abp/issues/631
