### ISSUE TITLE
Guid Id not set on 2 of more entities in Navigation Property

### ISSUE THREAD

**Issue by mat-guthrie-loupa** [abpframework/abp#14099]
ABP Framework version: 5.3.4.
User Interface: MVC
EF Core / SQL Server
Tiered architecture

I'm using EF Core with SQL Server and have entities will List Navigation Properties. When there are 2 or more entities in a collection I'm getting the following exception:

_System.InvalidOperationException: 'The instance of entity type 'Address' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'_

I'm also seeing odd, unreliable behaviour setting the TenantId for Entities implementing IMultiTenant

I’ve gone through the following testing steps.
 

**Background**
I have 2 entities: Customer and Address.
A customer can have many addresses (Shipping, Billing etc)
Customer : AuditedAggregateRoot<Guid>, IMultiTenant
Address : AuditedEntity<Guid>, IMultiTenant, IHasConcurrencyStamp
Customer has a Navigation Property: List<Address> Addresses

 

**Attempted Solution 1:** 

Use ObjectMapper to Map CustomerCreateDto to Customer (including the child address entities)

Rely on the ABP framework to set the Guid IDs on all entities

Rely on the ABP framework to set the TenantId by calling within the ApplicationService:

```
            using (CurrentTenant.Change(input.TenantId))
            {
                var customer = await _customerManager.CreateAsync(newCustomer);
                return ObjectMapper.Map<Customer, CustomerDto>(customer);
            }
```

 

_Problem 1:_

The TenantId is set on the Customer but not on any child address entities 

_Problem 2:_

If the customer only has a single address the AbpDbCOntext appears to correctly create the Guid identities of both the new Customer and the new Address. 

However, if the Customer has 2 addresses I get the following error: 

System.InvalidOperationException: 'The instance of entity type 'Address' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.'

 

**Attempted Solution 2:** 

Manually create the Customer and Address entities (don’t use ObjectMapper).

Save within a using (CurrentTenant.Change(input.TenantId)) statement

Rely upon ABP Framework to set the Guid Ids and the TenantId 

_Problem 1:_

TenantIds not set on any entities (Customer or Addresses) 

_Problem 2: (Same as before)_

If the customer only has a single address the AbpDbContext appears to correctly create the Guid identities of both the new Customer and the new Address. 

However, if the Customer has 2 addresses it generates the System.InvalidOperationException shown above.
 

**Attempted Solution 3:** 

Manually create all entities with Guid Ids using GuidGenerator.Create().

Save within a using (CurrentTenant.Change(input.TenantId)) statement

Rely upon ABP Framework to set the TenantId

_Problem 1:_

Tenant Id set on Customer Entity but not child address entities
 

**Attempted Solution 4:** 

Manually create all entities with Guid Ids using GuidGenerator.Create().

Manually set TenantIds on all entities

This actually worked. However, I’m not really using the ABP Frameworks Multi-tenant features and this concerns me.  It also makes it far more cumbersome to actually create complex entity structures, for instance an Order that might have multiple lineItems, a customer, multiple addresses, discount codes, financial transactions etc etc, all in one AggregateRoot that needs to be persisted together in a transaction.

**Comment by gdlcf88** [comment]
The entity Address doesn't need to implement `IMultiTenant` since it can only be attained with its aggregate root Customer.

**Comment by matguthrie** [comment]
My understanding was that every entity owned by a tenant in a sharded DB environment should have a tenantId to facilitate tenant migration from one shard to another. Is that not correct?

**Comment by matguthrie** [comment]
Similarly, having a tenantId on every entity owned by the tenant enables filtering and data security.

**Comment by realLiangshiwei** [comment]
Question 1:

You should add navigation property from the aggregate root,

For example:

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUser.cs#L172-L181

Qustion 2:

EF Core treats GUID defaults as valid values, so they are treated as the same entity tracking

![image](https://user-images.githubusercontent.com/16813853/191890231-90a2e8b6-6a74-439d-a176-972d196d098f.png)

Here are some solutions you can follow: 
https://github.com/abpframework/abp/issues/1931
https://github.com/abpframework/abp/issues/3795

**Comment by matguthrie** [comment]
> The entity Address doesn't need to implement `IMultiTenant` since it can only be attained with its aggregate root Customer.

Hi, I posted the question on a Microsoft Q&A forum. "Should every entity owned by the tenant in a sharded DB have a shard key"  (in a hybrid DB setup)

This is the response from a Microsoft Employee and "Community Expert".

> The best recommendation is to not go there but rather adopt a “db x tenant” If you really want to go there, an in-row tenant id column would be recommended for all sharded entities in your database model for a number of good reasons (not just split/merge, which is going to be painful anyway).

Here's the [link ](https://learn.microsoft.com/en-us/answers/questions/1020007/should-every-entity-owned-by-the-tenant-in-a-shard.html)

Thoughts?
