### ISSUE TITLE
autocomplete attribute for the abp-input tag helper not working

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#14105]
* Your **ABP Framework version**. **5.3.4**
* Your **User Interface** type  **MVC**
* Your database provider(EF Core/MongoDB) **EF Core**
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

 `<abp-input asp-for="UserInfo.UserName" autocomplete="off" />`, the autocomplete attribute is removed after generated html.

**Comment by maliming** [comment]
It works for me.

```html
<abp-input asp-for="Type" autocomplete="off" />

<div class="mb-3">
  <label class="form-label" for="Type">Type</label>
  <input autocomplete="off" type="text" id="Type" name="Type" value="test" class="form-control " />
  <span class="text-danger field-validation-valid" data-valmsg-for="Type" data-valmsg-replace="true"></span>
</div>
 

```
