### ISSUE TITLE
Update LastmodifierId

### ISSUE THREAD

**Issue by TuyenDinh1205** [abpframework/abp#14117]
**ABP Framework version**: 5.3.1
**User Interface** type :Angular
* database provider: MongoDB
Hi all
I want to change LastmodifierId to another one. Currently, record update in my database is current login user id. How to change it?

**Comment by maliming** [comment]
hi

You can override this method.
https://github.com/abpframework/abp/blob/8913e42327ed4148a3fba6ff79d63318eb8ef344/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditPropertySetter.cs#L106
