### ISSUE TITLE
Nuget Path Issue

### ISSUE THREAD

**Issue by xuyae573** [abpframework/abp#1411]
I have used the abp cli to generate a tierd project, but all of the projects are using the relative path to load the nuget package as below image

<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Acme.BookStore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Acme.BookStore.Domain.Shared\Acme.BookStore.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="..\..\..\..\modules\identity\src\Volo.Abp.Identity.Application.Contracts\Volo.Abp.Identity.Application.Contracts" Version="0.18.1" />
    <PackageReference Include="..\..\..\..\modules\permission-management\src\Volo.Abp.PermissionManagement.Application.Contracts\Volo.Abp.PermissionManagement.Application.Contracts" Version="0.18.1" />
    <PackageReference Include="..\..\..\..\modules\tenant-management\src\Volo.Abp.TenantManagement.Application.Contracts\Volo.Abp.TenantManagement.Application.Contracts" Version="0.18.1" />
    <PackageReference Include="..\..\..\..\modules\feature-management\src\Volo.Abp.FeatureManagement.Application.Contracts\Volo.Abp.FeatureManagement.Application.Contracts" Version="0.18.1" />
  </ItemGroup>

</Project>

![image](https://user-images.githubusercontent.com/1418798/60398215-5e368680-9b88-11e9-8fd9-95c455fdb571.png)

**Comment by xuyae573** [comment]
![image](https://user-images.githubusercontent.com/1418798/60398403-10228280-9b8a-11e9-959b-cdd18fa645de.png)

**Comment by maliming** [comment]
see: https://github.com/abpframework/abp/issues/1408#issuecomment-507035711
