### ISSUE TITLE
[Branch 6.0] debug codes need delete

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#14128]
below debug codes added from PR #14103, may forget delete:
https://github.com/abpframework/abp/blob/398588dda04e84f859d2a33b8c8cc8a636e75232/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain.Shared/MyProjectNameModuleExtensionConfigurator.cs#L40-L58

**Comment by enisn** [comment]
https://github.com/abpframework/abp/pull/14129
