### ISSUE TITLE
Spanish localization / documentation

### ISSUE THREAD

**Issue by miguelgimenez** [abpframework/abp#1413]
Hi,

Thank you for all your work in this project!

I would like to help adding support of spanish in this framework.

Even though I understand both are important, do you prefer I focus first on localization or on basic documentation?

Regards!

**Comment by hikalkan** [comment]
Hi,

Thank you very much for your contribution request.

I suggest you to start by translating these documents:

* Getting Started documents
* Tutorials
* CLI

When you complete these, we will publish it on https://docs.abp.io
Later, you can translate other docs whenever you have time in the future.

See https://github.com/abpframework/abp/blob/dev/docs/en/Contribution/Index.md#document-translation

After that, you can work on the resource localizations (https://github.com/abpframework/abp/blob/dev/docs/en/Contribution/Index.md#resource-localization).

Then if you want to continue, we can discuss again what we can do. Thanks a lot :)

**Comment by wocar** [comment]
If you want @miguelgimenez I can help you to review, double check or translate part of the document.

**Comment by hikalkan** [comment]
>If you want @miguelgimenez I can help you to review, double check or translate part of the document.

It is appreciated. Because I can't review it :D

**Comment by miguelgimenez** [comment]
Hi,

Thank you @wocar for your offer, I will push some updates soon.

Regards

**Comment by LuisPignataro** [comment]
Hi, a submited a  #2377 pull request with spanish traslation of resources!
