### ISSUE TITLE
in abp 6.0 openiddict how to SetAccessTokenLifetime

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#14132]

**Comment by aelhadi** [comment]
public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        PreConfigure<OpenIddictBuilder>(builder =>
        {
            builder.AddServer(options =>
            {
                options.SetAccessTokenLifetime(new TimeSpan(0, 0, 30, 0));
            });
////
///

///
