### ISSUE TITLE
No Feature Option in UI.

### ISSUE THREAD

**Issue by VivienMAN** [abpframework/abp#14144]
* Your **ABP Framework version**. => 6.0.0 RC4
* Your **User Interface** type (Angular/MVC/React... etc.) => Blazor Servezr
* Your database provider(EF Core/MongoDB) => EfCore
* Steps needed to **reproduce** the problem.

I followed the documentation to create a feature but I don't see it in the ui, nor in the tenants.
https://docs.abp.io/en/abp/latest/Features
But if I use the function `await _featureChecker.IsEnabledAsync("ClicClac.BlueWay")` , it works fine.
![image](https://user-images.githubusercontent.com/103559756/192361590-bc85f31d-99ec-471f-a353-1c231324a5dc.png)

**Comment by realLiangshiwei** [comment]
You need to set `ValueType`
https://docs.abp.io/en/abp/latest/Features#other-feature-properties
