### ISSUE TITLE
[AbpEntityFrameworkCoreModule] Can I use encrypted connection string?

### ISSUE THREAD

**Issue by holyrong** [abpframework/abp#1416]
I'm working with abp vnext 0.18.0, and I want to encrypt my database connection string,but I can't post my connection string to the method "options.UseSqlServer();"。
so how can i use my encrypted connection string?

**Comment by Xeevis** [comment]
Try with

```csharp
using Microsoft.EntityFrameworkCore;

(...)

Configure<AbpDbContextOptions>(options =>
{
    options.Configure(c =>
    {
        if (c.ExistingConnection != null)
        {
            c.DbContextOptions.UseSqlServer(c.ExistingConnection);
        }
        else
        {
            c.DbContextOptions.UseSqlServer("/* Your connection string */");
        }
    });
 });
```

**Comment by ebicoglu** [comment]
how about storing connection string in Environment Variable!

**YourAppDbContextFactory.cs**

```
  private static IConfigurationRoot BuildConfiguration()
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false)
                .AddEnvironmentVariables();

            return builder.Build();
        }
```

**Comment by holyrong** [comment]
> Try with
> using Microsoft.EntityFrameworkCore;
> 
> (...)
> 
> Configure<AbpDbContextOptions>(options =>
> {
>     options.Configure(c =>
>     {
>         if (c.ExistingConnection != null)
>         {
>             c.DbContextOptions.UseSqlServer(c.ExistingConnection);
>         }
>         else
>         {
>             c.DbContextOptions.UseSqlServer("/* Your connection string */");
>         }
>     });
>  });

 c.DbContextOptions.UseSqlServer(c.ExistingConnection);
**DbContextOptions doesn't has a definition of UseSqlServer.**
my abp vnext version is 0.18.1

**Comment by Xeevis** [comment]
You are missing the using

    using Microsoft.EntityFrameworkCore;

**Comment by holyrong** [comment]
> You are missing the using
> using Microsoft.EntityFrameworkCore;

OK,Thanks!

**Comment by holyrong** [comment]
> how about storing connection string in Environment Variable!
> YourAppDbContextFactory.cs
>   private static IConfigurationRoot BuildConfiguration()
>         {
>             var builder = new ConfigurationBuilder()
>                 .SetBasePath(Directory.GetCurrentDirectory())
>                 .AddJsonFile("appsettings.json", optional: false)
>                 .AddEnvironmentVariables();
> 
>             return builder.Build();
>         }

Are you mean storing the connection string in OS's Environment Variable?
Can i protect my connection string?

**Comment by maliming** [comment]
@holyrong 
see: https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows

**Comment by hieutns96** [comment]
Hi @maliming I also have an issue when storing connectionString in a user-secrets json file. In a Class DbContextFactory it cannot get the connectionString, so i can't not update-database or run migration. Also in CRUD  if i'm not add The DefaultConnectionString in StartupClass, it's also not working either .

**Comment by maliming** [comment]
Do you follow the instructions in the documentation,
Use UserSecretsId in csproj file, and call AddUserSecrets etc?

**Comment by hieutns96** [comment]
@maliming  Yes, all field in UserSecrets work fine except the connectionstring, not sure why ? but seems DbConnection just looks for ApplicationSetting.Json not in UserSecrets file

**Comment by maliming** [comment]
@hieutns96
Can you create a project with the above problem using the CLI and share it?

**Comment by hieutns96** [comment]
@maliming Hello maliming. Below is the screenshot for that, as you can see in the project test.EntityFrameworkCore.DbMigration I don't have the Startup class, so how can i initialize the user secret file to this method. 
  
![Capture](https://user-images.githubusercontent.com/28976584/60635532-55220f80-9e3d-11e9-832b-837e41a13a67.PNG)

**Comment by maliming** [comment]
You can refer to the similar code of aspnetboilerplate.
https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/aspnet-core/src/AbpCompanyName.AbpProjectName.EntityFrameworkCore/EntityFrameworkCore/AbpProjectNameDbContextFactory.cs#L10

**Comment by hieutns96** [comment]
@maliming  Hey maliming I've clone the source code and try adding the user secrects file with connections string fields, but still no luck even though the appConfiguration can get the value from the secret file

**Comment by softwareguy74** [comment]
Why would you need to encrypt a connection string?  You're not exposing it to the client are you?
