### ISSUE TITLE
PropertyNamingPolicy Property configuration of the ABP dynamic proxy

### ISSUE THREAD

**Issue by l494422810** [abpframework/abp#14165]
**abp** Framework version 5.3.4.
Use volo.abp.http.client to develop abp dynamic C# api clients
On the server Module file matching JsonSerializerOptions. PropertyNamingPolicy is null, the client proxy fails.
An error message is displayed. Object Reference not set to an instance of an Object.
If annotate the PropertyNamingPolicy code  can access it correctly

The configuration code is as follows
**public override void ConfigureServices(ServiceConfigurationContext context)
 {
      context.Services.AddControllers()
      .AddJsonOptions(options =>
      {
          options.JsonSerializerOptions.Encoder = JavaScriptEncoder.Create(UnicodeRanges.All);
          options.JsonSerializerOptions.PropertyNamingPolicy = null;
      });
}**

 
   在 Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder.<FindActionAsync>d__17.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<GetActionApiDescriptionModel>d__25.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<InterceptAsync>d__24.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__3`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Castle.DynamicProxy.AsyncInterceptorBase.<ProceedAsynchronous>d__14`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.<ProceedAsync>d__7.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Volo.Abp.Validation.ValidationInterceptor.<InterceptAsync>d__2.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.<InterceptAsync>d__3`1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Abp.Core.Eempty.Conterollers.HomeController.<Index>d__9.MoveNext() 在 D:\Projects\SKPCP027\DefaultCollection\SoftwareFactory\MOM.Framework\Abp.Training\Abp.Core.Eempty\Conterollers\HomeController.cs 中: 第 20 行

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by l494422810** [comment]
when i set the JsonOptions JsonSerializerOptions.PropertyNamingPolicy = null in mvc
the remote service request throw an exception Object reference not set to an instance of an object.

**Comment by maliming** [comment]
You can try to override this method.

https://github.com/abpframework/abp/blob/ed8045408b84d079265e66d235634d208e81ce3b/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/ApiDescriptionFinder.cs#L121
