### ISSUE TITLE
`x-frame-options` header is not added to the response | penetration test

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14175]
**Penetration test reports:**
The response does not include either Content-Security-Policy with 'frame-ancestors' directive or X-Frame-Options to protect against 'ClickJacking' attacks.

When I filter the header `x-frame-options` I don't see it in the response headers
![image](https://user-images.githubusercontent.com/9526587/192869579-3347b4b1-c0b9-40c9-8f2e-b38339a146b9.png)

But this should be added within the following middleware
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Security/AbpSecurityHeadersMiddleware.cs#L20

Check that why this header is not added.
I made the pen test in the `v5.3.2 ABP Commercial app-pro` template.

This header is missing in the following URLs:

- GET: https://localhost:44378
- GET: https://localhost:44378/Abp/MultiTenancy/TenantSwitchModal
- GET: https://localhost:44378/Account/ForgotPassword
- GET: https://localhost:44378/Account/Login
- GET: https://localhost:44378/Account/Manage
- GET: https://localhost:44378/Account/Manage?Picture=test_file.txt&pptype=use-default
- GET: https://localhost:44378/Account/Register
- GET: https://localhost:44378/Account/SecurityLogs
- GET: https://localhost:44378/AuditLogs
- GET: https://localhost:44378/FeatureManagement/FeatureManagementModal?providerName=E&providerKey=b53ddd44-9c1b-5a3a-5ffc-3a047ee12347
- GET: https://localhost:44378/FeatureManagement/FeatureManagementModal?providerName=T
- GET: https://localhost:44378/Gdpr/PersonalData
- GET: https://localhost:44378/HostDashboard
- GET: https://localhost:44378/Identity/ClaimTypes
- GET: https://localhost:44378/Identity/OrganizationUnits
- GET: https://localhost:44378/Identity/OrganizationUnits/AddMemberModal
- GET: https://localhost:44378/Identity/OrganizationUnits/AddRoleModal?organizationUnitId=7cd51042-f8e4-3a4f-35a1-3a047edd3205
- GET: https://localhost:44378/Identity/OrganizationUnits/CreateModal
- GET: https://localhost:44378/Identity/OrganizationUnits/EditModal
- GET: https://localhost:44378/Identity/Roles
- GET: https://localhost:44378/Identity/SecurityLogs
- GET: https://localhost:44378/Identity/Users
- GET: https://localhost:44378/Identity/Users/CreateModal
- GET: https://localhost:44378/Identity/Users/EditModal
- GET: https://localhost:44378/IdentityServer/ApiResources
- GET: https://localhost:44378/IdentityServer/ApiResources/Create
- GET: https://localhost:44378/IdentityServer/ApiResources/Edit
- GET: https://localhost:44378/IdentityServer/ApiScopes
- GET: https://localhost:44378/IdentityServer/ApiScopes/Create
- GET: https://localhost:44378/IdentityServer/ApiScopes/Edit
- GET: https://localhost:44378/IdentityServer/Clients
- GET: https://localhost:44378/IdentityServer/Clients/Create
- GET: https://localhost:44378/IdentityServer/Clients/Edit
- GET: https://localhost:44378/IdentityServer/IdentityResources
- GET: https://localhost:44378/IdentityServer/IdentityResources/Create
- GET: https://localhost:44378/IdentityServer/IdentityResources/Edit
- GET: https://localhost:44378/LanguageManagement
- GET: https://localhost:44378/LanguageManagement/Create
- GET: https://localhost:44378/LanguageManagement/Texts
- GET: https://localhost:44378/LanguageManagement/Texts/Edit
- GET: https://localhost:44378/Saas/Host/Editions
- GET: https://localhost:44378/Saas/Host/Editions/CreateModal
- GET: https://localhost:44378/Saas/Host/Editions/EditModal
- GET: https://localhost:44378/Saas/Host/Tenants
- GET: https://localhost:44378/Saas/Host/Tenants/CreateModal
- GET: https://localhost:44378/Saas/Host/Tenants/EditModal
- GET: https://localhost:44378/SaasWidgets/LatestTenants
- GET: https://localhost:44378/SettingManagement
- GET: https://localhost:44378/SettingManagement?AccountRecaptchaSettings.UseCaptchaOnLogin=false&AccountRecaptchaSettings.UseCaptchaOnRegistration=false&AccountSettings.EnableLocalLogin=false&AccountSettings.IsSelfRegistrationEnabled=false&AccountTwoFactorSettings.IsRememberBrowserEnabled=false&AccountTwoFactorSettings.UsersCanChange=false&BoxedLayout=true&EnableLocalLogin=true&IsRememberBrowserEnabled=true&IsSelfRegistrationEnabled=true&MenuPlacement=Left&MenuStatus=AlwaysOpened&PublicLayoutStyle=Style1&Score=0%2C5&SiteKey=ZAP&SiteSecret=ZAP&Style=Style6&TwoFactorBehaviour=Optional&UseCaptchaOnLogin=true&UseCaptchaOnRegistration=true&UsersCanChange=true&VerifyBaseUrl=https%3A%2F%2Fwww.google.com%2F&Version=3
- GET: https://localhost:44378/TextTemplates
- GET: https://localhost:44378/TextTemplates/Contents/InlineContent/Abp.StandardEmailTemplates.Layout
- POST: https://localhost:44378/Account/ForgotPassword
- POST: https://localhost:44378/Account/Login
- POST: https://localhost:44378/Account/Register

**Comment by maliming** [comment]
The `x-frame-options` header is added on response headers.

![image](https://user-images.githubusercontent.com/6908465/192954777-681c3d97-bbcf-4a90-adc1-26bdd6a2f3e5.png)
![image](https://user-images.githubusercontent.com/6908465/192955064-b72670c3-33af-4c7b-952b-5998a7f5b8fa.png)

**Comment by ebicoglu** [comment]
I can also see it, but the tool reported this as a missing header.
I think it's because of the Debug mode.
Closing the issue since it's a false-positive alert.

![image](https://user-images.githubusercontent.com/9526587/193043831-3cb17ecb-7233-4282-a9b0-cd2e29e3f190.png)
