### ISSUE TITLE
The WebAPI Routing with optional query parameter is not supported by HideAbpEndpoints method.

### ISSUE THREAD

**Issue by animitta** [abpframework/abp#14172]
## Environment

- ABP Framework version: 5.3.4

## Explains

The AbpSwashbuckleDocumentFilter  implementation has an error, because the key of OpenApiPaths is not contains `?` character.

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by animitta** [comment]
#  Reproduce this steps
- Create a new web project.
- Create a FileController
    ```csharp
    [ApiController]
    public class FileController : AbpControllerBase
    {
        [HttpGet]
        [Route("file/{providerName?}")]
        public async Task<string> GetAsync(string providerName = null)
        {
            return await Task.FromResult(providerName??string.Empty);
        }

        [HttpGet]
        [Route("file/info")]
        public async Task<string> GetInfoAsync()
        {
            return await Task.FromResult(string.Empty);
        }
    }
    ```
- Add `options.HideAbpEndpoints()` to the ConfigureSwaggerServices method of HttpApiHostModule class.

This is demo code [reproduce](https://github.com/animitta/reproduce)

**Comment by EngincanV** [comment]
Thanks @animitta, I will check.
