### ISSUE TITLE
Error on dismissing Edition Edit dialog

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#14170]
ABP 5.1.2
Angular
EF Core

On dismissing the dialog:
![image](https://user-images.githubusercontent.com/6149843/192776159-62cde528-198d-4476-851e-25ba749e7f4a.png)

I'm getting this:
![image](https://user-images.githubusercontent.com/6149843/192776249-e91b75b0-2f3b-40ae-9b04-7842b1e9b1f1.png)

**Comment by mahmut-gundogdu** [comment]
We have fixed the issue newer version of ABP. I have tested ABP 5.3. It works well. Now we are not supporting the 5.2 or less version of the app. My advice is, "you should update your app".
