### ISSUE TITLE
Unit Of Work - Collection was modified enumeration operation may not execute

### ISSUE THREAD

**Issue by hieutns96** [abpframework/abp#1417]
Hi,
I have a problem while handling CRUD event of an entity whenever I try to read objects on the different DbContext it gives me this error:

![Capture1](https://user-images.githubusercontent.com/28976584/60432099-9e027a00-9c2b-11e9-81fa-b797d8f88da1.PNG)

After look up the code in Uow I found this : 
![Capture](https://user-images.githubusercontent.com/28976584/60432131-aeb2f000-9c2b-11e9-9397-6e3ea9ce38b4.PNG)

Should _databaseApis.Values  be _databaseApis.Values.ToImmutableList(). 

Many thanks for your help .

**Comment by maliming** [comment]
ToImmutableList doesn't seem to solve the underlying problem. Can you share some code to reproduce this problem?

**Comment by hieutns96** [comment]
Sure. I have custom the AbpAuditPropertySetter to use int instead of GUID so i override the SetCreationAuditProperties to use my CustomAuditPropertySetter.  
![Capture3](https://user-images.githubusercontent.com/28976584/60439068-43bde500-9c3c-11e9-9d57-30765a668c92.PNG)

The id is get by query the database by another DbContext 

![Capture4](https://user-images.githubusercontent.com/28976584/60439173-88498080-9c3c-11e9-971d-ff85f7d8db22.PNG)
![Capture5](https://user-images.githubusercontent.com/28976584/60439175-88e21700-9c3c-11e9-8026-86e8cf203bc8.PNG)
![Capture6](https://user-images.githubusercontent.com/28976584/60439177-88e21700-9c3c-11e9-9ea2-0fe7dbb48efd.PNG)

**Comment by hieutns96** [comment]
> ToImmutableList doesn't seem to solve the underlying problem. Can you share some code to reproduce this problem?

**Comment by hieutns96** [comment]
Sorry I click wrong button on closed :)

**Comment by maliming** [comment]
@hieutns96 Can you share the complete project code? You can create a project using cli. : )

**Comment by hieutns96** [comment]
@maliming i affraid i cannot share the complete project but I found this issue on the old project ASP Boiplerplate that have same issue with me.  https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1860

I belive the _databaseApis.Values has been change during the transaction of SaveChangeAsync :)

**Comment by maliming** [comment]
Thank you very much, we will confirm this.

**Comment by hieutns96** [comment]
@maliming Thank you very much, I really appreciate your help. If it is possible when you find the issue, please share with me work around for this to work :)

**Comment by hungitk46** [comment]
I have the same issue, looking ahead to meet the fix it right now.

**Comment by maliming** [comment]
I already open the PR.
https://github.com/abpframework/abp/pull/1422

**Comment by hungitk46** [comment]
when do you deployment new version 0.19.0? it's an urgent issue with my project.

**Comment by maliming** [comment]
hi @hieutns96 
You can temporarily create the MyUnitOfWork class with the latest code and then replace the built-in UnitOfWork.

**Comment by hungitk46** [comment]
@maliming How to replace the built-in UnitOfWork. I'm using the Volvo abp.core from Nuget, and have the abp source code from the GitHub.

**Comment by maliming** [comment]
Use dependency injection to replace built-in components. 

> ReplaceServices: Set true to replace services if they are already registered before. Uses Replace extension method of IServiceCollection.

https://docs.abp.io/en/abp/latest/Dependency-Injection#dependency-attribute
