### ISSUE TITLE
Add Content Security Policy (CSP) Header  | penetration test

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14173]
**Penetration test reports** :
> Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.

![image](https://user-images.githubusercontent.com/9526587/192863224-0dced8bd-8361-4823-8c9d-9ccbe27e667c.png)

**Solution:**
> Ensure that your web server, application server, load balancer, etc. is configured to set the Content-Security-Policy header, to achieve optimal browser support: "Content-Security-Policy" for Chrome 25+, Firefox 23+ and Safari 7+, "X-Content-Security-Policy" for Firefox 4.0+ and Internet Explorer 10+, and "X-WebKit-CSP" for Chrome 14+ and Safari 6+.

We should add the `Content-Security-Policy` response header to the following middleware
- https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Security/AbpSecurityHeadersMiddleware.cs

For the Blazor:
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-6.0

**References:**

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
- http://www.html5rocks.com/en/tutorials/security/content-security-policy/
- http://caniuse.com/#feat=contentsecuritypolicy
- http://content-security-policy.com/

Also, check whether this header makes any unwanted behaviors in the templates.

**Comment by maliming** [comment]
This is a complex feature, I recommend developers set it up according to the situation.

**Comment by ebicoglu** [comment]
> This is a complex feature, I recommend developers set it up according to the situation.

why do you think it's complex? what kind of inappropriate behavior will happen?

**Comment by rqx110** [comment]
there is an repo https://github.com/andrewlock/NetEscapades.AspNetCore.SecurityHeaders may help

**Comment by maliming** [comment]
CDN fonts and images may be used in the project. We cannot predict which URL resources will be used by customers, so we cannot set a default policy URL.

```
Content-Security-Policy: default-src 'self'; script-src https://script.com; img-src https://images.com;
```

**Comment by ebicoglu** [comment]
according to [this repo](https://github.com/andrewlock/NetEscapades.AspNetCore.SecurityHeaders), they are adding the following header 

```
Content-Security-Policy: object-src 'none'; form-action 'self'; frame-ancestors 'none' - only applied to text/html responses
```


and this is from GitHub.com
![image](https://user-images.githubusercontent.com/9526587/194029705-2148d8fb-51aa-4924-9421-21b5864873b5.png)

**Comment by ebicoglu** [comment]
I'm not sure if we should add this header by default, but at least we should make it optional.
You can add this header to the middleware if the developer passes `UseContentSecurityPolicyHeader: true` to [this method ](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/Builder/AbpApplicationBuilderExtensions.cs#L110)
