### ISSUE TITLE
abp windows service  template has a bug? , It  can not start it when installed as a window service .

### ISSUE THREAD

**Issue by FisherMS** [abpframework/abp#14181]
1. create abp windows service solution.
```powershell 
abp new AbpWinService -t console -csf
```
2. build it.
3. use bat install the service .
```command
  set current=%~dp0
  set bin="%current%AbpWinService.exe"
  set serviceName=".NET AbpWinService"
  echo Creating service with the name %serviceName%
  sc create %serviceName% binPath=%bin%
```
5. start it in mmc and it will be take a long time to start but return a error.

![0002](https://user-images.githubusercontent.com/12068896/192978078-8d8b231e-aaa3-44e0-a0b2-f9c9a20d0d5d.png)

**Comment by maliming** [comment]
What is the error?

**Comment by FisherMS** [comment]
> 

![0002](https://user-images.githubusercontent.com/12068896/192978078-8d8b231e-aaa3-44e0-a0b2-f9c9a20d0d5d.png)

**Comment by maliming** [comment]
> Terminates this process and returns an exit code to the operating system.

The console app will not exit.
