### ISSUE TITLE
Null Reference Exception When LazyServiceProvider.LazyGetRequiredService<***>

### ISSUE THREAD

**Issue by leaortiz** [abpframework/abp#14190]
Hi guys,

I am getting a nulll reference exception on properties derived from DomainService (Clock, GuidGenerator, and so on) on my brand new module. 
It was created using the following command:  abp add-module ProductManagement --new --add-to-solution-file

Steps to reproduce:
Create a new app using the get started page, then add a new module.
Write the following code:

![image](https://user-images.githubusercontent.com/67666980/193137727-a79b58d2-ec1b-4a4e-9a93-22eae1a3b582.png)

**Comment by maliming** [comment]
hi

The properties of `DomainService` will be set after the constructor method.

**Comment by realLiangshiwei** [comment]
Or you can use the constructor injection.

**Comment by leaortiz** [comment]
They came from lazyServiceProvider, on the screenshot was a quick test, they also fail on methods after constructor was called.

**Comment by maliming** [comment]
hi

Please share code to reproduce.

**Comment by leaortiz** [comment]
Repo: https://github.com/leaortiz/Mainumbi.Survival
Failing Code: https://github.com/leaortiz/Mainumbi.Survival/blob/master/modules/Mainumbi.Pool/src/Mainumbi.Pool.Domain/BookManager.cs

You can run the tests to find the failing code also

**Comment by JadynWong** [comment]
Hi @leaortiz,

For `PoolManager_Tests.Will_Add_New_Ticket` error. The correct usage is as follows. But your code has some other errors that need to be changed. `PoolDbContext` should add `DbSet<TEntity>` properties.

I think you can read [tutorial](https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=MVC&DB=EF).

![image](https://user-images.githubusercontent.com/13699353/193456860-b5884e00-6444-45aa-ba54-57232191db33.png)
![image](https://user-images.githubusercontent.com/13699353/193457130-67ea4e4b-bdf4-4496-87bf-ce9f49ea511e.png)
![image](https://user-images.githubusercontent.com/13699353/193457141-3fe17507-b9df-4fe4-93d7-0a6fbaac6dbf.png)
![image](https://user-images.githubusercontent.com/13699353/193457398-1002317f-4614-40bf-b828-54b5dc705b08.png)
![image](https://user-images.githubusercontent.com/13699353/193457323-ca766451-835a-48ce-b192-3eb4b7c3aef9.png)

**Comment by leaortiz** [comment]
Wow thanks a lot for your time!
