### ISSUE TITLE
AsyncCrudAppService  can't filter and get navigate property detail

### ISSUE THREAD

**Issue by holyrong** [abpframework/abp#1420]
I'm working with 0.18.1
1)I want to get a paged list,and the list should be filtered by some 'like-operator',but the AsyncCrudAppService.GetListAsync(PagedAndSortedResultRequestDto) only support PagedAndSortedResultRequestDto parameter。
can we add another Filter Parameters?
2)How can I Include a navigate property in my GetListAsync method? 
for example,I want to get User.Department using UserAppService.GetListAsync(),but the Department property is null。

**Comment by holyrong** [comment]
This code is copied from CrudAppServiceBase,how can we filter data:
protected virtual IQueryable<TEntity> CreateFilteredQuery(TGetListInput input)
        {
            return Repository;
        }

**Comment by maliming** [comment]
```
protected virtual IQueryable CreateFilteredQuery(TGetListInput input)
{
    return Repository.Where()......;
}
```

**Comment by holyrong** [comment]
> reateFilteredQuery(TGetListInput input)

But this is the code from abp framework ,I can't modify the code.

**Comment by maliming** [comment]
It is a virtual method, you can override it in a derived class.

**Comment by holyrong** [comment]
> It is a virtual method, you can override it in a derived class.

Thank you!I've got it.

The second question: How can I using IQueryable.Include() to get the navigate property？or is there any way else?
such as the Blogs of Author
public class Author
{
  public  IList<Blog> Blogs {get;set;}
}
or the Author of Blog
public class Blog
{
    public Author Author {get;set;}
}

**Comment by maliming** [comment]
Do not use IQueryable<TEntity> features in the application code (domain, application... layers).
Use the includeDetails of the Repository.
See the documentation for more information: https://docs.abp.io/en/abp

**Comment by holyrong** [comment]
> Do not use IQueryable features in the application code (domain, application... layers).
> Use the includeDetails of the Repository.
> See the documentation for more information: https://docs.abp.io/en/abp

OK,Thanks!
