### ISSUE TITLE
The cookie `XSRF-TOKEN` is not HttpOnly

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14214]
Set the following cookies as `HttpOnly`

- [x] `XSRF-TOKEN`  
- [x] `AspNetCore.Culture` 
- [x] `idsrv.session`  (Identity Server cookie)

> A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page, then the cookie will be accessible and can be transmitted to another site. If this is a session cookie, then session hijacking may be possible.

![image](https://user-images.githubusercontent.com/9526587/193634619-7c8a61ae-f892-4068-933a-13d3296256b5.png)
![image](https://user-images.githubusercontent.com/9526587/193646779-ffbd0428-a65d-4600-9bf6-9bb28509bdeb.png)
 

![image](https://user-images.githubusercontent.com/9526587/193650289-2f2842ac-b169-4a64-ab7d-f30d36138751.png)

![image](https://user-images.githubusercontent.com/9526587/193649428-b755f63e-a973-4102-b55a-7c8a7c6fba74.png)

**Comment by maliming** [comment]
### `XSRF-TOKEN` `AspNetCore.Culture`

We need to use `XSRF-TOKEN` and `AspNetCore.Culture` in JavaScript(angular).

### `idsrv.session`

It's by Identity Server design. 
https://github.com/IdentityServer/IdentityServer3/issues/3512

**Comment by ebicoglu** [comment]
All the pages that are setting `XSRF-TOKEN` , `.AspNetCore.Culture` and `idsrv.session` in the HTTP response are reported as "No `HttpOnly` Flag" vulnerability. This is a positive alert. `idsrv.session` cookie is being used in IDS4 and after ABP 6.x the support for IDS will be dropped therefore this cookie will not be used anymore. Also, there is an issue related to the `idsrv.session` cookie cannot be set as `HttpOnly`; you can see the related thread at its own repository https://github.com/IdentityServer/IdentityServer4/issues/3873. 

On the other hand, the cookies `.AspNetCore.Culture` and `XSRF-TOKEN` are being retrieved via JavaScript in ABP Angular, MVC and Blazor WASM projects. Therefore cannot be set as `HttpOnly`. You can check out the following modules that retrieve these cookies via JavaScript:

* https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Swashbuckle/wwwroot/swagger/ui/abp.swagger.js#L28
* https://github.com/abpframework/abp/blob/dev/modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/Pages/update.js#L54
* https://github.com/abpframework/abp/blob/dev/modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/Pages/create.js#L84
* https://github.com/abpframework/abp/blob/392beb897bb2d7214db8facba7a2022be7aa837c/modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/BlogPosts/update.js#L91
* https://github.com/abpframework/abp/blob/dev/modules/cms-kit/src/Volo.CmsKit.Admin.Web/Pages/CmsKit/BlogPosts/create.js#L127
* https://github.com/abpframework/abp/blob/dev/modules/docs/app/VoloDocs.Web/wwwroot/libs/abp/jquery/abp.jquery.js#L261
* https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Components.Web/Volo/Abp/AspNetCore/Components/Web/AbpBlazorClientHttpMessageHandler.cs#L94

**Setting `XSRF-TOKEN` cookie as `HttpOnly`:**
If you want to set you can do it in [AbpAntiForgeryOptions](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AntiForgery/AbpAntiForgeryOptions.cs#L56) class.

**Setting `.AspNetCore.Culture` cookie as `HttpOnly`:**
If you want to set you can do it in [AbpRequestCultureCookieHelper](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/RequestLocalization/AbpRequestCultureCookieHelper.cs#L16) class. Set the option `HttpOnly = true`.

Closing this issue because no need a fix right now.
