### ISSUE TITLE
Remove `X-Powered-By` response header

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14216]
**Description:**  The web/application server leaks information via one or more "X-Powered-By" HTTP response headers. Access to such information may facilitate attackers identifying other frameworks/components your web application relies on and the vulnerabilities such components may be subject to.

The `X-Powered-By` header is provided by ASP.NET Core.
The following URLs return HTTP responses with `X-Powered-By` header

* *[GET] —* https://localhost:44378/Account/Login?ReturnUrl=%2FLanguageManagement%2FTexts 
* *[POST] —* https://localhost:44378/LanguageManagement/Texts 

**Screenshots** 
![image](https://user-images.githubusercontent.com/9526587/193667330-0c22f70b-2b41-45df-ac1d-70c7e1140772.png)

**Solution:** Remove the `X-Powered-By` header from all HTTP responses.

**Comment by maliming** [comment]
I think the header add by IIS Express, You can try to use `dotnet run` command to check.

https://github.com/dotnet/aspnetcore/issues/27192#issuecomment-715909444

**Comment by ebicoglu** [comment]
This happens when the application runs on IIS or IIS Express.
For those who want to remove this header automatically from all the responses, add the following code to the `web.config` file.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer> 
    <httpProtocol>
      <customHeaders>
        <remove name="x-powered-by" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
</configuration>
```

![image](https://user-images.githubusercontent.com/9526587/194077224-f52f52fc-38fb-43be-b59e-15bd792b6799.png)

**Comment by ebicoglu** [comment]
We'll add `web.config` to have this configuration out of the box with the new project templates.
See https://github.com/abpframework/abp/issues/14236
