### ISSUE TITLE
Set cookie `SameSite` attribute to `strict`

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14215]
The `SameSite` attributes of the cookies should be set to  `strict` or `lax`. 
But some of our cookies are set to `None `or there's no `SameSite `attribute.

The following cookies' `SameSite` attributes are set as `None` and ideally, it should be `strict` or `lax`.

![image](https://user-images.githubusercontent.com/9526587/193657905-06d318d7-3007-4042-ac29-053a0e27b47f.png)

![image](https://user-images.githubusercontent.com/9526587/193658082-96f7977b-e34b-4536-8ba2-235904ed4ee8.png)

---

The following URL has no `SameSite` attribute. It should set the  `SameSite` attribute to `strict` or `lax`.

- https://localhost:44378/Abp/Languages/Switch?culture=ar&returnUrl=%2F&uiCulture=ar

**Comment by maliming** [comment]
`idsrv.session` and `.AspNetCore.Identity.Application` is control/changed by Identity Server.

https://github.com/IdentityServer/IdentityServer4/blob/3ff3b46698f48f164ab1b54d124125d63439f9d0/src/AspNetIdentity/src/IdentityServerBuilderExtensions.cs#L51


`XSRF-TOKEN` is `none` https://github.com/abpframework/abp/commit/9aec4f3ce35216731db05a4b462a57d64b2adf8b

`.AspNetCore.Culture` is `Unspecified`, meaning no `SameSite` attribute added to the cookie and the client will use its default behavior (Lax for new browsers, None for old ones).

**Comment by ebicoglu** [comment]
Setting `SameSite` attribute to `strict` may occur problems when an ABP website integrates with other 3rd party websites like payment gateways. We can leave this change to the final developer.
You can see the amazon.com website `SameSite` cookie attribute policy:

![image](https://user-images.githubusercontent.com/9526587/194098270-cf1f7125-1b11-40e8-b216-0d180aaa7f73.png)
