### ISSUE TITLE
Blazor LeptonXLite logo link tag is linking to "~/" instead of "/"

### ISSUE THREAD

**Issue by StlobyAdmin** [abpframework/abp#14210]
The blazor wasm lpx-brand-logo picture link is broken "a href="~/" please fix to "a href="/"

* ABP Framework version 6.0.0RC4*.
* Blazor App*
* Steps needed to **reproduce** the problem - default wasm template of RC4 or 5, then click logo.*

**Comment by enisn** [comment]
Thanks for your feedback, this issue was solved and it'll be released in next LeptonX release
