### ISSUE TITLE
In GetListAsync, the totalCount is 0, and the result is returned directly

### ISSUE THREAD

**Issue by applebananamilk** [abpframework/abp#14228]
[https://github.com/abpframework/abp/blob/71074d74381d71adfe054c7c8071af8f936c1000/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/AbstractKeyReadOnlyAppService.cs#L61](url)

![image](https://user-images.githubusercontent.com/37533208/193826983-be87a671-1131-4836-a41d-4f5acbaf9696.png)

Can it be optimized here?

**Comment by maliming** [comment]
What's your expectd?

**Comment by applebananamilk** [comment]
I think this will save one SQL execution, especially when there are filter conditions（百度翻译，不好意思）
