### ISSUE TITLE
Error in Single-layered Template (migration problem )

### ISSUE THREAD

**Issue by KaungZawHtet** [abpframework/abp#14237]
I did these steps and found error

1. Get the template from the website with these options (Single-layered Application , MVC, EF Core, MySQL) 
2.  run the command from **migrate-database.ps1** file at Proj Directory.
3.  Found this err : 

<img width="983" alt="Screen Shot 2022-10-06 at 2 58 51 AM" src="https://user-images.githubusercontent.com/15225530/194157538-7b94940f-97d7-4f2f-926e-50fc6fd0426c.png">

OS : Mac
Abp version : 6
.net version : 6

**Comment by maliming** [comment]
I tried it in Win and it works. @realLiangshiwei Can you test it in MAC?

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem

**Comment by realLiangshiwei** [comment]
We will fix it, you can add the `DbContextFactory` class to your project.

**Comment by KaungZawHtet** [comment]
cli tool and website's generation button are the same ? Website's generation button give same err while cli not
