### ISSUE TITLE
Add web.config file to the application templates

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14236]
This issue is started from the following issue https://github.com/abpframework/abp/issues/14216 .

For some configuration, we add `web.config` file to our templates (_app, app-nolayers, maui, wpf_)

First configuration is to remove `x-powered-by` header.
You can add other information to run the project on IIS like this https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/test/aspnet-core-demo/AbpAspNetCoreDemo/web.config

This issue is for the open-source and PRO templates.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer> 
    <httpProtocol>
      <customHeaders>
        <remove name="x-powered-by" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
</configuration>
```

**Comment by maliming** [comment]
https://discord.com/channels/687243951924838430/813771137933901825/1028605482111340605
