### ISSUE TITLE
Deploying to Azure. Missing js files? 

### ISSUE THREAD

**Issue by punkouter2018** [abpframework/abp#1424]
I followed the sample and it works and wanted to deploy to Azure to an App service. But it seems it can't find the js files.. Is there some procedure I am missing to have it copying them over ?  Or perhaps bundle them somehow ? 

Could not find file '/Pages/EnfActs/index.js' using IWebContentFileProvider

**Comment by maliming** [comment]
Try copy js/css files to the output directory under the Pages folder. https://github.com/abpframework/abp/pull/1281

Related issue: https://github.com/abpframework/abp/issues/1204

**Comment by hikalkan** [comment]
@punkouter2018 can you close this issue if it is fixed with the related issues.

**Comment by punkouter2018** [comment]
How do I automatically do this ? I noticed in the Books sample in GitHub the BOOKS folder is in the bin directory but the project I created does not have it. I checked the csproj and both projects have

<ItemGroup>
    <None Update="Pages\**\*.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

So what am I missing  ?

**Comment by hikalkan** [comment]
It should not be a problem for the latest startup templates. If it is, we should fix it.

**Comment by punkouter2018** [comment]
I noticed that this was in the csproj and I removed and recompiled and it seems it put the .js file in bin now.. dunno why this was put there though.. Ill try deploying to azure again..

**Comment by punkouter2018** [comment]
works in azure... will contune going through tutorial . closing
