### ISSUE TITLE
eShop: LeptonX theme change needs

### ISSUE THREAD

**Issue by malikmasis** [abpframework/abp#14247]
- [ ] ![image](https://user-images.githubusercontent.com/13196534/194500036-222b0b97-cc11-4bbe-99af-e34b1266bde9.png)
- [ ] ![image](https://user-images.githubusercontent.com/13196534/194500299-f48ac09e-fc23-47e8-aaec-97917a5180fe.png)
- [ ] ![image](https://user-images.githubusercontent.com/13196534/194500491-2041e315-5daf-44fa-8e9e-5901f8e2b44f.png)
- [ ] ![image](https://user-images.githubusercontent.com/13196534/194500603-3d73c349-9302-4cd3-a62e-2ba34bd88cd7.png)
- [ ] ![image](https://user-images.githubusercontent.com/13196534/194501154-0f8f3fad-2f7a-4abe-bc18-0c9aba035ef2.png)
- [ ] ![image](https://user-images.githubusercontent.com/13196534/194501325-0061edc4-8808-4aa1-9c5e-e24370ff60fc.png)

**Comment by gterdem** [comment]
Moved to https://github.com/abpframework/eShopOnAbp/issues/155
