### ISSUE TITLE
Exception handling from within LocalEventBus Event

### ISSUE THREAD

**Issue by phil-enfom** [abpframework/abp#14246]
* Your 6.0 RC4
* Your Angular
* (EF Core)

When throwing a UserFriendly Exception from within an EntityUpdatedEventData<T> event a Unhandled exception is logged to the console and the UserFriendlyException is not shown to the user.

When throwing a UserFriendlyException from an EntityCreatedEventData<T> event the exception is handled and shown to the user in the angular interface.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/194532648-dff8e0d8-70a9-4fd0-83c4-dc6ba5f250b1.png)
![image](https://user-images.githubusercontent.com/30018771/194532424-45282af4-83bf-448f-87fe-85cced9af60b.png)

It returned 403 with the message "Hello World" as expected.

**Comment by phil-enfom** [comment]
Ok done some more looking into the issue, have created a new project and added the following:
![image](https://user-images.githubusercontent.com/63820281/194697362-7f723af7-d7df-4bb2-9065-bf42cc376790.png)

The exception fires but the error is not returned to the page, Fiddler reports
![image](https://user-images.githubusercontent.com/63820281/194697400-2f21fd4c-666e-4c42-827c-77e0925f1aa3.png)

And in the CLI:
![image](https://user-images.githubusercontent.com/63820281/194697429-323c8b46-c0c6-476a-8687-5474c853436b.png)

It seems that the logic that fires in the EntityUpdatedEventData and EntityCreatedEventData can't throw exceptions
