### ISSUE TITLE
Automapper will remove static API.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1425]
> It'll break some folks, but I'm tired of supporting an API that no one should use anymore.
> * Version 8.1.1 - Obsolete Mapper.Initialize https://github.com/AutoMapper/AutoMapper/pull/3082
> * Version 9.0 - Removing static API https://github.com/AutoMapper/AutoMapper/pull/3136

see: https://github.com/AutoMapper/AutoMapper/issues/3135

**Comment by hikalkan** [comment]
I am happy for it. .MapTo extension methods are using it. Since we haven't release ABP v1.0 yet, we can remove static API support.

**Comment by hikalkan** [comment]
@maliming can you check what to do and implement if you can handle it. Thanks.
