### ISSUE TITLE
Missing required indicators

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14252]
This is just a minor thing but there is no * for required fields in the UI (when creating a user)  so you discover it only after pressing save

![image](https://user-images.githubusercontent.com/2386572/194535798-3ea02024-ccdc-469b-9b64-9c106c74683c.png)

and the phone number and email have have no validation and accept what ever value (is this intended?)
![image](https://user-images.githubusercontent.com/2386572/194537666-98fbdd50-34eb-40fc-9769-edf347e76615.png)

Commercial version (don´t know if its in OSS)

**Comment by realLiangshiwei** [comment]
We will improve it.

**Comment by realLiangshiwei** [comment]
>and the phone number and email have no validation and accept what ever value (is this intended?)

It actually has,  see: https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/IdentityUserCreateOrUpdateDtoBase.cs#L26

**Comment by sturlath** [comment]
> > and the phone number and email have no validation and accept what ever value (is this intended?)
> 
> It actually has, see: https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/IdentityUserCreateOrUpdateDtoBase.cs#L26

But only length, but no phone number I know of are letters and 92385@$$%$ is not a valid email....
