### ISSUE TITLE
Two different logout pages

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14254]
Following the steps here below its random on what type of page we end up on after logging out. 

**Steps:**
Log in with tenant user credentials
Click on tenant username displayed on homepage (MVC).
Select log out option

**Expected Result:**
Only one type of window should display when a team user logs out of the system.

**Actual Result:**
We can see there are two types of windows displays when a tenant user logs out of the system. 

![image](https://user-images.githubusercontent.com/2386572/194541300-2b527770-05d5-43af-a810-b0d6e15a8470.png)

and 

![image](https://user-images.githubusercontent.com/2386572/194541354-74565e0e-8973-4d36-8320-437ce184e4ca.png)

* Your **ABP Framework version**. 5.3.3
* Your **User Interface** Blazor/MCV
* **Separate IdentiyServer**

**Comment by realLiangshiwei** [comment]
![image](https://user-images.githubusercontent.com/16813853/194834437-babf437f-0bf5-41e9-8de2-0d24d8e04554.png)

The image 1 is auth server logged out page, and it will redirect to your client, (image 2)

**Comment by sturlath** [comment]
The thing is that the first page doesn´t redirect (at least not consistently) and the later one still shows the user logged in.

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem.

BTW, if you don't want to see the auth server logged out page, you can customize the logged out page.

I don't think it has anything to do with open source, so I closed the issue. : )
