### ISSUE TITLE
Bug In Abp6.0 when add-module Volo.Account --with-source-code

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#14269]
when I use cmd ` abp add-module Volo.Account --with-source-code --add-to-solution-file`
I can't run the application,the logs show 
`System.IO.FileNotFoundException: Could not load file or assembly 'Volo.Abp.Account.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
File name: 'Volo.Abp.Account.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'`

finally, I resolve the bug by change some code ，
first , change the xxxWebModule 
`   // typeof(AbpAccountWebOpenIddictModule),`
then ,add the code as follow:
`[DependsOn(typeof(AbpAccountWebModule))]
[DependsOn(typeof(AbpAccountWebOpenIddictModule))]
[DependsOn(typeof(AbpAccountWebIdentityServerModule))]
`
finally, add the "Volo.Abp.Account.Web.OpenIddict.dll" to the dependicy

**Comment by yekalkan** [comment]
I think this is resolved now. I've added some missing configuration for account module.
