### ISSUE TITLE
Entity Extensions Issue

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#14267]
When I upgrade to 6.0.0，the ExtraProperties do not read or write from the specific fields，but from the ExtraProperties.
I have configure the ModuleExtensionConfigurator both in Domain.Shared and EntityFrameworkCore.
It works well in 6.0.0-rc

**Comment by maliming** [comment]
> It works well in 6.0.0-rc

What is the version of rc?

**Comment by xxvolvo** [comment]
6.0.0-rc.4

**Comment by maliming** [comment]
Please share a GitHub repository to reproduce the problem, Thanks.

**Comment by xxvolvo** [comment]
https://github.com/xxvolvo/TestExtraProperties
The demo use PostgreSQL.
I add a new field --"LineManagerId" and u can post "api/app/test/test" directly.
The result like this 
![image](https://user-images.githubusercontent.com/16984534/194796351-fca04f93-1d6f-409c-a218-9d6a4df4459c.png)
but in 6.0.0.-rc4 it will be like this
![image](https://user-images.githubusercontent.com/16984534/194796462-2621cd99-3836-4fce-9633-458ddcc415cb.png)
(this demo has an other ExtraPropertie)

**Comment by iamsedatozturk** [comment]
Can confirm, its this line causing to remove all Extending configuration to be removed.
https://github.com/abpframework/abp/blob/ccbdfa58212d64e0ca624058acede03002a4aeb6/framework/src/Volo.Abp.ObjectExtending/Volo/Abp/ObjectExtending/Modularity/ModuleExtensionConfigurationHelper.cs#L177

When I remove it, I can get my ExtraProperties successfully.
Before:
![1](https://user-images.githubusercontent.com/76204082/194859402-44a8447a-3874-4165-9a51-c6644444017d.PNG)

After:
![2](https://user-images.githubusercontent.com/76204082/194859412-dd65ef80-ba50-44e5-9925-63321d11485e.JPG)
![3](https://user-images.githubusercontent.com/76204082/194859408-b3cf1ecf-c385-4e8b-8ec6-9e3b7a822381.JPG)

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/pull/14306
