### ISSUE TITLE
Openiddict Migration - CurrentUser.Name is null

### ISSUE THREAD

**Issue by aicreed** [abpframework/abp#14260]
Framework: 6.0.0
UI: Blazor WASM.
Database: EF Core.

Reproduce: Attempt to migrate from Identity Server to Openiddict using official guide.

Issue: Calling CurrentUser.Name and CurrentUser.Surname inside the Blazor WASM project following the migration to Openiddict results in a null reference exception, despite data existing in the database. This issue was not present under Identity Server.

**Comment by maliming** [comment]
hi

Can you try with the 6.0 template project?

**Comment by aicreed** [comment]
Hi,

I have just tried this, and can confirm it works as intended on the WASM 6.0 template. To attempt to remove any kind of mistakes I may have made, I also took a fresh branch off our code and redid the migration, however the issue still persists. The user guides I have used are as follows:

https://docs.abp.io/en/abp/latest/Migration-Guides/OpenIddict-Step-by-Step
and
https://docs.abp.io/en/abp/6.0/Migration-Guides/OpenIddict-Blazor

Thanks

**Comment by maliming** [comment]
Please try to compare the startup(web) module code.

**Comment by aicreed** [comment]
Hi,

I have compared the Blazor Module code to the test template project I made and it appears to be identical, including the ConfigureAuthentication method which adds the OpenIddict claims.

Thanks.

**Comment by aicreed** [comment]
I've done some more testing and I have discovered that instead of using CurrentUser, calling GetAsync on the IProfileAppService returns all properties including name and surname. This will suffice as a fix for now, but I am still unsure of the root cause of the issue with CurrentUser.Name. 

I should also note all other properties (Surname, email, GUID, username) all appear to be present.
