### ISSUE TITLE
blog doesn't render preview text good 

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14272]
I texted the below message. And as you see, medium.com preview is good, but our blog module renders HTML text.

https://discord.com/channels/687243951924838430/687243952365371447/1028686289471557744

![image](https://user-images.githubusercontent.com/9526587/194764705-41233564-47e7-4e28-9ed9-891215c94765.png)

**Comment by ebicoglu** [comment]
write only informational text that people can write there HTML to be as preview in instant messaging tools

**Comment by braim23** [comment]
Closed by https://github.com/abpframework/abp/pull/14330
