### ISSUE TITLE
Docs translating Turkish

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#1427]
I wanted to see anybody has already translating the docs to Turkish. I can do as much as i can if none does. 

`Will wait 1 week as the issue open, then i will start it`

**Comment by hikalkan** [comment]
Thank you @ugurozturk. We don't think to work on this. However, if you or anybody else want to contribute, it is appreciated.

Read my this comment: https://github.com/abpframework/abp/issues/1413#issuecomment-507722987
