### ISSUE TITLE
[Text templating Scriban] How can I pass a raw string instead of template name?

### ISSUE THREAD

**Issue by phongphongg** [abpframework/abp#14271]
- ABP Framework Version: 6.0
- Text templating Scriban

How can I pass a raw string instead of template name? If yes, how should I do it?

Example:
```cs
public class Controller {
  private readonly ITemplateRenderer _templateRenderer;

  // ...

  _templateRenderer.RenderAsync("Hello {{ name }}", new { Name = "World" });
}

```

Thanks

**Comment by maliming** [comment]
You can use `Scriban` API instead of `ITemplateRenderer`.
