### ISSUE TITLE
The abp framework integrated with another microservice has a built-in identity server

### ISSUE THREAD

**Issue by abdullahshaqaliah** [abpframework/abp#14281]
ABP Framework version is 6
User Interface mvc

Hi
I have microservice not based on abp framework but shared with the same identity server how i can send request from abp to the microservice with authitication header  and return the result to application based on abp framework.

**Comment by maliming** [comment]
hi

abp uses claims-based authentication. So your IDS only needs to return standard claims to the abp client.

**Comment by abdullahshaqaliah** [comment]
Thank you for reply
There  any code how i can sent http request from abp framework built in to different microservice  or just i used normal httpclient with asp.net?

**Comment by abdullahshaqaliah** [comment]
@maliming ??

**Comment by maliming** [comment]
I'm not familiar with your microservices and don't have much advice.

**Comment by abdullahshaqaliah** [comment]
My microservice has one api just i want call the api from application based on abp feamework to return some result how i can by abp sent http call ,I know i can by httpclient do that just i ask if there libary in abp bulit in do the same httpclient to send request and get the response.
