### ISSUE TITLE
Property Extension Mapping not getting value on Abp 6.0

### ISSUE THREAD

**Issue by fireheadbr** [abpframework/abp#14296]
On the last version of ABP (6.0) property extension mapping not getting value from property (worked on 5.3 version)

```csharp
 ObjectExtensionManager.Instance
      .MapEfCoreProperty<IdentityUser, Guid?>(
          "CustomerId",
          (entityBuilder, propertyBuilder) =>
          {
          }
      );
      --------------------------------
      user.GetProperty<Guid?>("CustomerId");
```
 or getting from ExtraProperties... found the key but the value is always null

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem. 

Thanks.

**Comment by realLiangshiwei** [comment]
Will solved by https://github.com/abpframework/abp/pull/14306
