### ISSUE TITLE
An error occurred when an embedded resource was loaded after publication

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#14303]
I tried the monaco-editor and it worked well in the development environment, but it started loading problems after release. Please help me take a look.

![image](https://user-images.githubusercontent.com/22017199/195236221-f7e860d3-d0af-48c4-9fa6-cc4bb56b79fe.png)

development environment: Abp 6.0   Razor  EFCore

The difference between publish1 and publish2: I copy monaco-editor and requirejs into the wwwroot directory.

publish1 Run error.
publish2 works well.

Repeat steps:
1、cd publish1 
2、dotnet Acme.BookStore.Web.dll
3、open http://localhost:5000
4、click menu  CodeEditor
5、F12  View log

Repeat the code link : https://github.com/344089386/AbpJavaScriptTest

**Comment by realLiangshiwei** [comment]
Will it work if you try it without ABP?

**Comment by 344089386** [comment]
Normal use is OK, I suspect it is the embedded resource problem, this js library is a bit special, it is loaded through requirejs, I don't know if this is the reason?

**Comment by 344089386** [comment]
No error will be reported when running directly, but only after publishing

**Comment by realLiangshiwei** [comment]
This is a known limitation of EmbeddedFileProvider and microsoft don't plan to address.

See: https://github.com/dotnet/aspnetcore/issues/24314

![image](https://user-images.githubusercontent.com/16813853/195486801-7d739b43-8d13-4333-959c-f6cb8852aa0b.png)


So, you need to use physical files
