### ISSUE TITLE
Id´s in top menu not being created (hard to do Playwright tests)

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14300]
We are trying to add Playwright tests and need id´s on the top menu

This is my menu 
![image](https://user-images.githubusercontent.com/2386572/195194720-fc40f508-7192-4b13-add5-0a1af8103af2.png)

Adding elementId doesn´t change anything.
![image](https://user-images.githubusercontent.com/2386572/195194769-a1331e22-88f8-48ea-9b91-a58d000a8779.png)

There is also no id´s on the login button or after the user is logged in

![image](https://user-images.githubusercontent.com/2386572/195195811-2dd2bbd7-33aa-45cf-83fe-f715d8bd8650.png)

* Your **ABP Framework version**. 6.0
* Your **User Interface** MVC

**Comment by realLiangshiwei** [comment]
We will enhance the Theme next version.

You can customize the menu page now.
