### ISSUE TITLE
Volo.Abp.IdentityServer was not work on Implicit mode

### ISSUE THREAD

**Issue by CooperLiu** [abpframework/abp#1431]
Try to test IdentityServer workflow using Volo.Abp.IdentityServer module.

[SPA client](https://github.com/CooperLiu/vuejsOidcClient)
[MicroserviceDemo->applications->AuthServer.Host](https://github.com/abpframework/abp/tree/dev/samples/MicroserviceDemo/applications/AuthServer.Host)

steps:
1.run [SPA client](https://github.com/CooperLiu/vuejsOidcClient)

- open cmd ,then run `yarn` for restore spa dependency packages.
- type command `npm run dev` for run spa app.
- modify [SecurityService.js](https://github.com/CooperLiu/vuejsOidcClient/blob/master/src/services/SecurityService.js) `authority` instead of your auth server .
  

2. add client into AuthServer.Host
```
 //vue client
            var vueClientId = configurationSection["AuthCenter_Vue:ClientId"];
            if (!vueClientId.IsNullOrWhiteSpace())
            {
                var rootUrl = configurationSection["AuthCenter_Vue:RootUrl"].EnsureEndsWith('/');
                await CreateClientAsync(
                vueClientId,
                commonScopes,
                IdentityServer4.Models.GrantTypes.Implicit,
                commonSecret,
                new[]
                {
                    $"{rootUrl}static/callback.html"
                   // $"{rootUrl}static/silent-renew.html"
                },
                $"{rootUrl}index.html",
                new[] { rootUrl.RemovePostFix("/") },
                setClient: c =>
                {
                    c.AllowAccessTokensViaBrowser = true;
                    //c.AlwaysIncludeUserClaimsInIdToken = true;
                    //c.AccessTokenType = (int)IdentityServer4.Models.AccessTokenType.Jwt;
                }
            );
            }
```
appsettings.json
```
 "AuthCenter_Vue": {
        "ClientId": "vuejsclient",
        "RootUrl": "http://localhost:8080/"
      }
```

issues description:

the auth server host web site was crash, so please check it once, and it's free for communication

**Comment by hikalkan** [comment]
Can you share the application logs (Logs/logs.txt)?

**Comment by CooperLiu** [comment]
[logs.txt](https://github.com/abpframework/abp/files/3359086/logs.txt)
Actually, the auth server app was created by Abp CLI using mvc-module template.  we also tested with MicroserviceDemo `AuthServer.Host` with same issue.

**Comment by CooperLiu** [comment]
Actually, the auth server app was created by Abp CLI using mvc-module template. we also tested with MicroserviceDemo`AuthServer.Host` with same issue.
[logs.txt](https://github.com/abpframework/abp/files/3359113/logs.txt)

**Comment by CooperLiu** [comment]
@hikalkan

**Comment by CooperLiu** [comment]
@hikalkan 
after a long test, this issue was solved at last, [the `AbpCorsPolicyService` cache](https://github.com/abpframework/abp/blob/dev/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AbpCorsPolicyService.cs#L31) had some issue with redis cache integration.

1. we tied to remove ` context.Services.AddDistributedRedisCache` , it was work.
2. I wrote customized implement of `ICorsPolicyService` for replaced default without remove distributed redis cache.

 FYI,[CorsMiddleware should resolve dependencies dynamically](https://github.com/aspnet/AspNetCore/issues/2377)

**Comment by Goxiaoy** [comment]
In my case,  I am using redis as distributed redis cache and client  get infinite hang when acquiring  discovery docs (.well-known/openid-configuration), and seems after that all requests to identity host hangs. It seems that ICorsPolicyService will be resolved as singleton so everything related to this object will be singleton. But it's will be changed to transist in .net core 3.0 from this [link](https://github.com/aspnet/AspNetCore/issues/2377#issuecomment-425179476)

I am not sure whether abp will target to lower than .net core 3.0. but this is the issue stucks me several hours.

This is a work around.

```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IdentityServer4.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Volo.Abp.Caching;
using Volo.Abp.IdentityServer.Clients;

namespace Volo.Abp.IdentityServer
{

    /// <summary>
    /// Implementation of ICorsPolicyService that consults the client configuration in the database for allowed CORS origins.
    /// </summary>
    /// <seealso cref="IdentityServer4.Services.ICorsPolicyService" />
    public class CorsPolicyService : ICorsPolicyService
    {
        private readonly IHttpContextAccessor _context;
        private readonly ILogger<CorsPolicyService> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="CorsPolicyService"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        /// <param name="logger">The logger.</param>
        /// <exception cref="ArgumentNullException">context</exception>
        public CorsPolicyService(IHttpContextAccessor context, ILogger<CorsPolicyService> logger)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = logger;
        }

        /// <summary>
        /// Determines whether origin is allowed.
        /// </summary>
        /// <param name="origin">The origin.</param>
        /// <returns></returns>
        public async Task<bool> IsOriginAllowedAsync(string origin)
        {
            // doing this here and not in the ctor because: https://github.com/aspnet/CORS/issues/105
            var clientRepository = _context.HttpContext.RequestServices
                .GetRequiredService<IClientRepository>();

            var allowedOrigins = (await clientRepository.GetAllDistinctAllowedCorsOriginsAsync()).ToArray();

            var isAllowed = allowedOrigins.Contains(origin, StringComparer.OrdinalIgnoreCase);

            _logger.LogDebug("Origin {origin} is allowed: {originAllowed}", origin, isAllowed);

            return isAllowed;
        }



    }
}


```

```
            context.Services.Replace(ServiceDescriptor
                .Transient<ICorsPolicyService, CorsPolicyService>());
```

**Comment by Goxiaoy** [comment]
#1546
