### ISSUE TITLE
EventBus - Error Handling

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#14315]
I think a error handling feature for event bus handlers could improve the framework.

I think of a configurable exponential back-off for event handlers, so the host doesn't hammers the infrastructure on recurring errors.

I'm willing to contribute this change, but I think it should be discussed first.

**Comment by realLiangshiwei** [comment]
We used to introduce error handling,  but after we introduce the inbox pattern, it's no longer necessary
https://github.com/abpframework/abp/issues/10034

Some discussion here: https://github.com/abpframework/abp/issues/11210, 
 https://github.com/abpframework/abp/pull/11216#issuecomment-1006843999

We welcome your ideas
