### ISSUE TITLE
Create new user translation 

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14329]
This is confusing like it is.

Name should be changed to **First Name** and Surname to **Last Name**
![image](https://user-images.githubusercontent.com/2386572/195831126-c1442cb9-f062-4fbd-884d-7589674e7b6b.png)

**Comment by DonVliet** [comment]
Hi @sturlath - in English we do use Name and Surname, but if you prefer not to use those words, abp lets you edit the language files (.json) in the following folder:

/src/[MyCompanyName.MyProjectName.Domain.Shared/[Localization]/[MyProjectName]

From the following file:

/abp/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/Localization/

    "Surname":"Surname",
    "DisplayName:Name": "Name",
    "DisplayName:Surname": "Surname",

Hope that helps,
Don

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
