### ISSUE TITLE
Suggestion of `LeptonX-lite` theme

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#14326]
* Your **ABP Framework version**: 6.0.0
* Your **User Interface** type (Angular/MVC/React... etc.) : MVC

on `Account/Login` page:
1. The login form is too wide
2. Hide `login` button on `Account/Login` page?
![image](https://user-images.githubusercontent.com/1829209/195791115-70b7cab7-3b8d-4557-aebe-401733ab95e5.png)

others:
1. button on card title missing `btn-primary` style, by design?
![image](https://user-images.githubusercontent.com/1829209/195791504-05aa7fb9-230b-4bcc-bc91-e3869f3d5803.png)

**Comment by realLiangshiwei** [comment]
What do you think? @armgnunlu

**Comment by rqx110** [comment]
@realLiangshiwei @armgnunlu, I real think it can be improved
