### ISSUE TITLE
UI updates needed for the reset password window

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14328]
Cancel is usually at the right not let.

![image](https://user-images.githubusercontent.com/2386572/195810643-2da78683-e639-406d-8450-a73313600c28.png)

and simplify the message. It should be simple and clear e.g., Confirm Password
![image](https://user-images.githubusercontent.com/2386572/195811300-5e368154-da0a-477f-b034-988d7ae5fa88.png)

and message should be changed to Passwords do not match
![image](https://user-images.githubusercontent.com/2386572/195812053-2665ef24-dd77-4432-ba7d-99abf28b6733.png)

missing space after ":" and re-try is one word
![image](https://user-images.githubusercontent.com/2386572/195816674-043f9faa-c094-4969-9586-7ac745dc5554.png)

Can we try to fit this text on the next line in one single line? Also, the close message button is bigger than the Ok button. Because the close message button is capturing the attention rather than the Ok button. 
![image](https://user-images.githubusercontent.com/2386572/195832717-ec43e580-7d88-4ed0-9b49-37a8b346cf8f.png)

**Comment by sturlath** [comment]
@EngincanV  just checking if these suggestions were addressed or just forgotten? This UI is a hot mess :-)

**Comment by sturlath** [comment]
@maliming or somebody, has any of these issues been considered internally?

**Comment by EngincanV** [comment]
Hi @sturlath, I've assigned this issue to myself and will take care of it. Thanks for the suggestions.
