### ISSUE TITLE
Azure Deployment issue - Authorization Service does not return any permissions on initial app load

### ISSUE THREAD

**Issue by aicreed** [abpframework/abp#14320]
Database: Entity Framework
UI: Blazor WASM
Version: ABP 6.0

Hi,
This is an issue I have only been able to replicate in our deployed Azure environment, and not in my local development environment. 

When I open our app in a new tab and fully reload it, none of my UI elements load and I get the following in the Chrome dev console: 
![image](https://user-images.githubusercontent.com/47678215/195620463-66e66795-7cbd-4936-8225-a4a9d2adc91e.png)

If I refresh, the error message disappears and my content reloads. I suspect that when the initial WASM load is initiated, it redirects to the API and that somehow causes the authorization service to fail to load any kind of permission. I have conducted tests, and written the state of the permissions to console upon load, and they all seem to be false, until I refresh and it loads the permissions correctly.

Could someone point me in the right direction here?

Thanks.

**Comment by maliming** [comment]
hi

Is WebSocket enabled on your Azure server?

**Comment by aicreed** [comment]
Hi,

I checked and websockets were disabled on both my API and Blazor host. I enabled it however I am still seeing the same issue.

**Comment by maliming** [comment]
Please check the response  of `Signalr's negotiation`.

**Comment by aicreed** [comment]
Hi,

How would I go about doing that? Thanks.

**Comment by maliming** [comment]
What's your app url?

**Comment by aicreed** [comment]
Hi,
Do you have a private way of sharing that with you? I do not want to make our URL public yet as we have not yet released our app.

Thanks

**Comment by maliming** [comment]
hi liming.ma#volosoft.com

**Comment by maliming** [comment]
hi

It seems your website works for me.

![image](https://user-images.githubusercontent.com/6908465/196686129-4b8086b7-cce9-4ae9-acb6-56580099711f.png)


![image](https://user-images.githubusercontent.com/6908465/196686004-e567b349-31e6-4ff3-84e7-f12717f9eea8.png)
![image](https://user-images.githubusercontent.com/6908465/196686069-06069960-f4b8-4ddd-9db5-410e3fe37a68.png)

**Comment by aicreed** [comment]
It's also working fine for me now, which is very strange. However it does not work in incognito mode. 

I haven't changed anything, only left the app deployed for a few days.
