### ISSUE TITLE
No UI Angular 

### ISSUE THREAD

**Issue by thanhtai9606** [abpframework/abp#14325]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Abp Version **6.0.0**.
* ui **Angular**
* EF Core

After Create with cli in abp 6.0.0 angular not working, It just show loading bar only?? It also loading bar only in angular in 5.3.4
Please help me??

**Comment by KobusPost** [comment]
Are you using the new Lepton X Lite theme?
Lost UI when I upgraded from the basic Theme to Lepton X theme

**Comment by thanhtai9606** [comment]
> Are you using the new Lepton X Lite theme? Lost UI when I upgraded from the basic Theme to Lepton X theme

default it use lepton-x

**Comment by thanhtai9606** [comment]
How can I use a basic theme ?? Because I show loading icon only on screen

**Comment by htaki** [comment]
Hello, I have the same issue, and there is no errors messages in the console .

I tried using many browser including Edge and Chrome.

I saw that the develop branche of the framework is referencing a version 2.0.0 in preview, I tried to use it but it is not found on npm.

Any help is appreciated.

Thank's

**Comment by KobusPost** [comment]
I managed to make it work, but now it won't load the ABP module's. Cannot access setting/permission/feature/account management. Also login/logout actions are bugged and authentication is not kept on reload.

I had a 5.x version which I updated to 6.0. No problems with MVC, but angular has been a pain.
Console does show no errors.

**Comment by thanhtai9606** [comment]
> I managed to make it work, but now it won't load the ABP module's. Cannot access setting/permission/feature/account management. Also login/logout actions are bugged and authentication is not kept on reload.
> 
> I had a 5.x version which I updated to 6.0. No problems with MVC, but angular has been a pain. Console does show no errors.

That error because lepton-x theme layout. You can remove it and install basic-theme layout, it's working now!!
