### ISSUE TITLE
StackExchange.Redis.RedisConnectionException on new project

### ISSUE THREAD

**Issue by reminvestor** [abpframework/abp#14331]
I followed the official documentation on development environment setup. I didn't see anywhere where I need to install Redis Server.

Abp version 6
Blazor Server Side
EF Core

Exception: 
MM.Portal.HttpApi.Host.dll!MM.Portal.PortalHttpApiHostModule.ConfigureDistributedLocking.AnonymousMethod__0(System.IServiceProvider sp) Line 173	C#

StackExchange.Redis.RedisConnectionException: 'It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 4s ago, v: 2.2.4.27433'

Steps to reproduce:
Create new Blazor server side application with most recent CLI.
Run migrations with dbmigrator project as start up. 
Start the application.

**Comment by maliming** [comment]
hi

Can you share full error logs?
