### ISSUE TITLE
Volo.Abp.UI.Navigation Namespace Issues

### ISSUE THREAD

**Issue by wayneboyles** [abpframework/abp#1433]
I have created a PR #1432 which fixes a namespace issue in **Volo.Abp.UI.Navigation**

I found that some of the classes were actually under the namespace Volo.Abp.**Ui** (lower case I) and the rest were in the correct namespace of Volo.Abp.**UI** (all uppercase).  This may be intended but just in case it wasn't I wanted to send in this PR to resolve the issue.

Example file: [ApplicationMenuItemList.cs](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.UI.Navigation/Volo/Abp/Ui/Navigation/ApplicationMenuItemList.cs)

**Comment by hikalkan** [comment]
Fixed by https://github.com/abpframework/abp/pull/1432
