### ISSUE TITLE
OpenIddict：In application-configuration，The currentUser under the Token requested by the password mode is null

### ISSUE THREAD

**Issue by aneasycat** [abpframework/abp#14345]
ABP Framework version：6.0
IdentityServer：OpenIddict

Token Request Url：/connect/token/grant_type=password&client_id=app&username=admin&password=*

CurrentUser is null in the request （api/abp/application-configuration）

`"currentUser": {
        "isAuthenticated": false,
        "id": null,
        "tenantId": null,
        "impersonatorUserId": null,
        "impersonatorTenantId": null,
        "impersonatorUserName": null,
        "impersonatorTenantName": null,
        "userName": null,
        "name": null,
        "surName": null,
        "email": null,
        "emailVerified": false,
        "phoneNumber": null,
        "phoneNumberVerified": false,
        "roles": []
    },`

currentUser is normal in the code mode request token

**Comment by realLiangshiwei** [comment]
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Steps needed to **reproduce** the problem.

**Comment by aneasycat** [comment]
the issue not  is  related to a specific UI。

Steps:
1.Request url：/connect/token/grant_type=password&client_id=app&username=admin&password=*
2.Request url：/api/abp/application-configuration（Auth：Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkY0NTI4NkJBMEZBOTlB...）

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem.

![image](https://user-images.githubusercontent.com/16813853/196134442-2cdb466b-e385-4207-8adc-adc5b818ba33.png)

**Comment by aneasycat** [comment]
The password mode still doesn't work.
（T_T）why？
![360截图20221017204402413](https://user-images.githubusercontent.com/48110648/196183993-8b7abc47-386b-4e2a-b66a-0114b34ac7c1.jpg)
![屏幕截图 2022-10-17 210506](https://user-images.githubusercontent.com/48110648/196184667-c405ae39-f6df-459e-9168-93af4e344039.png)

**Comment by realLiangshiwei** [comment]
What's the result if you login to the application(Angular UI), and see the network tab to check the `/api/abp/application-configuration` request?

**Comment by aneasycat** [comment]
Code mode request token
![微信截图_20221018084544](https://user-images.githubusercontent.com/48110648/196309461-870e1048-4308-4ed2-afd9-d30ab1e0b5bf.png)

**Comment by aneasycat** [comment]
The password mode still doesn't work.
Do I need other parameters for the token request?

**Comment by realLiangshiwei** [comment]
Make sure that the `scope` parameter is right.
`scope: offline_access ...etc`

**Comment by aneasycat** [comment]
Thank you！

**Comment by usoftadmin** [comment]
I also met the same problem as you, may I ask how you solved it? I haven't seen the solution mentioned above, thank you very much @aneasycat @realLiangshiwei

**Comment by usoftadmin** [comment]
Thank you very much. I understand what you mean. It is ok to add this scope parameter when applying for token
![image](https://github.com/abpframework/abp/assets/149404751/324b6003-8f19-44a6-b879-20acfb529263)
