### ISSUE TITLE
Suggestion for templates to include common and most used external login flows like Azure B2C

### ISSUE THREAD

**Issue by RelevanceRo** [abpframework/abp#14358]
Version: **ABP Framework 6.0**
Interface: **Blazor / MVC / Angular**

Would be nice to have the possibility to chose at template creating interface or by cli, for applications, between most common external providers, like Azure B2C, Google, Facebook for the login. And to add the authentication logic in the code and a section in appsettings.json with the properties needed for the login with dummy values.

**Comment by realLiangshiwei** [comment]
Hi,

It is included in [ABP commercial](https://commercial.abp.io/) : )
