### ISSUE TITLE
The leptonX theme, when the side menu closed the logo icon is not specified by branding provider

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#14359]
* Your **ABP Framework version**. abp 6.0.0
* Your **User Interface** type (Angular/MVC/React... etc.) MVC

With the leptonX theme, when the side menu closed the logo icon not specified.

Current the logo in the side menu already specified by branding provider, the logo icon (displaying when the side menu closed) should also could be specified via branding provider.

**Comment by TheObliterator** [comment]
Is it possible to re-open this issue? This still seems to be a limitation today despite recent improvements in #19782.
The DefaultBrandingProvider lacks support to specify the Logo **Icon** (for light and dark themes).

It seems it is possible to override the logo in the CSS but we really need a method to override this per tenant at runtime via the IBrandingProvider interface.

Workaround in blazor-global-style.css (for anyone searching) - but this is fixed for all tenants:

```
/* for dim and dark theme styles */
:root .lpx-theme-dim, :root .lpx-theme-dark {
    --lpx-logo: url('/images/logo/logo-light.png');
    --lpx-logo-icon: url('/images/logo/logo-light-thumbnail.png');
}

/* for light theme style */
:root .lpx-theme-light, :root .lpx-brand-logo {
    --lpx-logo: url('/images/logo/logo-dark.png');
    --lpx-logo-icon: url('/images/logo/logo-dark-thumbnail.png');
}
```
