### ISSUE TITLE
How can I use the same extra properties system defined in the previous section on separate field in datatable?

### ISSUE THREAD

**Issue by yangl1n** [abpframework/abp#14367]
I want to extend IdentityUser with an employeeId field, this field will be used to write querable. I followed this [method](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities#entity-extensions-ef-core), it works that create new columns in my datatable, but how can I save value into it? I try to use setProperty, but in database, it is stored in extraproperty instead of inserting value in my extended columns. The article said that it overcome this difficulties, but I still can not use this separate field.

**Comment by ahmadmasoum** [comment]
Try This 
https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#database-mapping

**Comment by yangl1n** [comment]
> Try This https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#database-mapping

Thank you and I have try this. It indeed create an extra field in database table. But how can I store value in it. For example, I want to store employeeId when user first time login, the employeeId is returned from ExternalLogin Provider(Auzre AD). Using user.setProperty("employeeId", "0000000"), and CreateExternalAsync() will call the UserManager.UpdateAsync(user) to store as json in extra property which I want to avoid

**Comment by cbogner85** [comment]
I think it's a bug. After upgrading to 6.0.0 my ExtraProperties that had always been dedicated table columns didn't work anymore. I had to move them to the the ExtraProperties column to make it work again.

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/pull/14306
