### ISSUE TITLE
Cannot access setting in web project

### ISSUE THREAD

**Issue by Cway14** [abpframework/abp#14369]
Setting returns null when accessed through the web project but returns with valid value when accessed in other projects.

**ABP Version**: 5.3.4
**Database provider**: EF Core

**Steps to reproduce:** 
1. Create settings definition provider in Web project
![Screen Shot 2022-10-18 at 12 23 05 PM](https://user-images.githubusercontent.com/21322069/196524692-4261167b-4ec1-445c-8599-7c7c473ef43e.png)

2. Attempt to access using ISettingProvider within Razor Page Model (index.cshtml.cs)
![Screen Shot 2022-10-18 at 12 31 38 PM](https://user-images.githubusercontent.com/21322069/196526315-861f1342-ecfc-4fc6-bd08-aa09c5df191c.png)
![Screen Shot 2022-10-18 at 12 35 40 PM](https://user-images.githubusercontent.com/21322069/196527053-a75a36fc-aaac-4ed7-80c2-42d54cb31577.png)

**Notes:**
- The setting does not propagate in the AbpSettings table so I manually created the entry
![Screen Shot 2022-10-18 at 12 28 26 PM](https://user-images.githubusercontent.com/21322069/196525765-643df3e8-859d-4543-9f9b-4f562ed9b5d4.png)
- Setting definition exists:
![Screen Shot 2022-10-18 at 12 32 36 PM](https://user-images.githubusercontent.com/21322069/196526493-c49b5da2-09b1-4a68-a964-32b84b14c9be.png)
![Screen Shot 2022-10-18 at 12 33 05 PM](https://user-images.githubusercontent.com/21322069/196526589-b4975e32-f78f-4e29-bf74-2b2fe63a9a4c.png)

**Comment by maliming** [comment]
hi

Please share a minimum project to reproduce. Thanks

**Comment by ahmadmasoum** [comment]
#12283
This might help you

**Comment by Cway14** [comment]
Thanks, it seems I get a NullSettingStore when injecting into the Web Project. I was able to work around this by injecting the ISettingProvider into an App Service, and using a method to get the value.
