### ISSUE TITLE
 ABP Framework v6.0 - OpenIdDict

### ISSUE THREAD

**Issue by drhikmetyz** [abpframework/abp#14379]
bp 6.0 ile çalışmalarımı yapıyorum. abp blazor server uygulaması yazdım. Kendi bilgisayarımda sorunsuz çalışıyor. Fakat hosting hizmeti aldığım server' yükleme yaptığımda hata veriyor.
çalışan abp 5.3 ile [www.mesyaz.com](http://www.mesyaz.com/)
abp 6.0 ile yazdığım uygulama [esen.mesyaz.com](http://esen.mesyaz.com/) hata veriyor. Hosting firması ile görüştüm.  sorunu çözemediler.
[esen.mesyaz.com](http://esen.mesyaz.com/) sitemde
ben abp 6.0 platform kullanıyorum visual Studio 2022 c# ve OpenIddict kütüphane kullanıyorum.
log dosyalarına baktım
OpenIddict.Abstractions.dll
OpenIddict.Core.dll
OpenIddict.Server.AspNetCore.dll
OpenIddict.Server.dll
OpenIddict.Validation.AspNetCore.dll
OpenIddict.Validation.dll
OpenIddict.Validation.ServerIntegration
hatalarını alıyorum.
Çözüm için ne yapmam gerekiyoruz.
Dr. Hikmet MARAŞLI

**Comment by enisn** [comment]
Can you find & share logs after a failed request? You can see logs in the terminal or if you can access it, it writes to `Logs/logs.txt` by default.
Without logs, we can't say anything clearly.

According to my experience after clicking your link, it seems your application can't be initialized. Please check your database connections are available or make sure a Redis instance is running if you're using distributed cache.
