### ISSUE TITLE
deploy abp without ssl behind cloudflare

### ISSUE THREAD

**Issue by mesuttascic** [abpframework/abp#14370]
I downloaded a clean project with mvc, postgresql. then immediately deployed it to IIS.
I am using cloudflare, I am not used to prepare ssl certificate on server for development projects
Everything is fine on web ui. But when I post credential to "/connect/token" path it return "This server only accepts HTTPS requests."

  "App": {
    "SelfUrl": "http://abp2.elveri.com"
  },
It is not https .

I did some search and found DisableTransportSecurityRequirement or EnableTokenEndpointPassthrough.
OpenIddictServerBuilder has this options so I added it above PreConfigure<OpenIddictBuilder>

        PreConfigure<OpenIddictServerBuilder>(options =>
        {
            options
                .UseAspNetCore()
                .EnableTokenEndpointPassthrough()
                .DisableTransportSecurityRequirement();
            options
                .AddDevelopmentEncryptionCertificate()
                .AddDevelopmentSigningCertificate();
        });
        PreConfigure<OpenIddictBuilder>(builder =>
        {
            builder.AddValidation(options =>
            {
                options.AddAudiences("IkinciElVeri");
                options.UseLocalServer();
                options.UseAspNetCore();
            });
        });

Of course I will not recommend for production, just use it development.

**Comment by maliming** [comment]
hi

I guess the `DisableTransportSecurityRequirement` solve your problem, right?

**Comment by mesuttascic** [comment]
Yes,
"DisableTransportSecurityRequirement" solves the restriction "This server only accepts HTTPS requests." .
