### ISSUE TITLE
Blazorise ModalProvider

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#14397]
Can you add the providers like <MessageProvider /> , <ModalProvider /> , <NotificationProvider /> , <PageProgressProvider />

https://blazorise.com/docs/services/modal-provider

We need it for use the full power of blazorise.

(The version 1.1.2 is avaible.)

_Originally posted by @VivienMAN in https://github.com/abpframework/abp/issues/14366#issuecomment-1285259307_

**Comment by enisn** [comment]
@realLiangshiwei can you check and if it's compatible can you add it?

**Comment by realLiangshiwei** [comment]
ok, I will check it.

**Comment by VivienMAN** [comment]
For information there are four, in total
![image](https://user-images.githubusercontent.com/103559756/197190258-7f0f8f1d-d6ff-4d50-90c7-55d7b64667f9.png)

**Comment by VivienMAN** [comment]
Hello @realLiangshiwei ,
Do you think you can update blazorise to abp version 7.0?

**Comment by realLiangshiwei** [comment]
yes, it will include in the 7.0

**Comment by realLiangshiwei** [comment]
Hi,

After my check, ABP has abstracted such services: https://docs.abp.io/en/abp/latest/UI/Blazor/Notification

![image](https://user-images.githubusercontent.com/16813853/202340607-72053b8e-87d7-459b-ab0e-87522654b4da.png)

So, we won't add these providers.

But if you like, you can easy to do it:

Create a component named `BlazoriseServiceProviders`

```csharp
<ModalProvider/>
<MessageProvider/>
<PageProgressProvider/>
<NotificationProvider />
```

Configure the `AbpDynamicLayoutComponentOptions`

```csharp
Configure<AbpDynamicLayoutComponentOptions>(options =>
{
    options.Components.Add(typeof(BlazoriseServiceProviders), new Dictionary<string, object>());
});
```

**Comment by VivienMAN** [comment]
Thanks for solution, but in abp they dont have <ModalProvider/>.

**Comment by VivienMAN** [comment]
@realLiangshiwei  @enisn  Thanks for  solution.
On the other hand I am not completely satisfied, the ModalProvider does not exist in abp and is however an important novelty of Blazorise.
I think the ModalProvider should be included as standard in the Blazor version.
