### ISSUE TITLE
Decrease log level for `Resource temporarily unavailable`  to `Warning`

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#14394]
[GetFileCommitsAsync](https://github.com/abpframework/abp/blob/8d87d539d7c701831a27d4667df9f11c66a38803/modules/docs/src/Volo.Docs.Domain/Volo/Docs/GitHub/Documents/GithubRepositoryManager.cs#L52) method in `GithubRepositoryManager` class brings commits with Octokit. If GitHub cannot reach the source temporarily, Octokit throws an exception. This is not an unhandled exception and can be ignored by a writing log. We will update the log level to Warning to sanitize the logs and see the real unhandled errors.

Finally, the developers will see their real exceptions in their monitoring tools like Kibana:
![image](https://user-images.githubusercontent.com/64414348/195097377-7e170239-f9cd-40df-88eb-85f68f29adcb.png)

**Comment by ebicoglu** [comment]
should be fixed on 2022-11-11.
