### ISSUE TITLE
Could not load type 'Volo.Abp.Auditing.DisableAuditingAttribute'

### ISSUE THREAD

**Issue by HoboCY** [abpframework/abp#14404]
When i upgrade to version 5.3.4
Start host got an error:
Could not load type 'Volo.Abp.Auditing.DisableAuditingAttribute' from assembly 'Volo.Abp.Auditing, Version=5.3.4.0, Culture=neutral, PublicKeyToken=null'
My project use audit log without database，how to
resolve this error？

**Comment by maliming** [comment]
Try to clear your project and rebuild.

`abp clean`

**Comment by HoboCY** [comment]
Thank you. I succeeded after a few tries

**Comment by AlishMekliov931** [comment]
I have the same issue with version 7.0.1, how you resolved it?

**Comment by flvy** [comment]
I have the same issue with version 7.0.1, how you resolved it?
