### ISSUE TITLE
Localization of cookie Accept message

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14417]
I can find out how to localize this message "ThisWebsiteUsesCookieCookieConsentAgreePolicies". And should it also not be something like "_This website uses cookie consent policies_" in english?

![image](https://user-images.githubusercontent.com/2386572/197177589-d0b34953-2108-4cc5-a78e-cccd68a3e431.png)

* Your **ABP Framework version**. 6.0.0 (commercial)
* Your **User Interface** Blazor

**Comment by EngincanV** [comment]
Hi, I'll check this.

**Comment by EngincanV** [comment]
I could not reproduce it. (Blazor - 6.0.0)

![image](https://user-images.githubusercontent.com/43685404/197191472-5f0e2f46-0360-469d-9fda-750b72e63672.png)

---

Can you try with a new template or provide me with steps to reproduce the problem?

**Comment by sturlath** [comment]
I have not updated to LeptonX at this time since we will do that with the 7.0 version (too much custom stuff).

Could that be the issue? But I can´t see this text in the language texts. Shouldn´t it be in there?

**Comment by EngincanV** [comment]
> I have not updated to LeptonX at this time since we will do that with the 7.0 version (too much custom stuff).
> 
> Could that be the issue? But I can´t see this text in the language texts. Shouldn´t it be in there?

No, Cookie Consent Feature is a part of the GDPR Module, so it's normal to not seeing it there.

Can you check if your project has a reference to the `Volo.Abp.Gdpr.Domain.Shared` package?

**Comment by sturlath** [comment]
Ok that was it! I ran `abp add-module Volo.Gdpr` and got it. I had tried the Gdpr when it came out. I would have thought the update progress should re-install it. But I´m good. Thank you so much!

**Comment by sturlath** [comment]
Maybe one thing more @EngincanV! Can you give me the localization strings for me to override in Icelandic? 

Can´t you make all these strings open source, so we don´t have to ask all the time?

**Comment by EngincanV** [comment]
> Maybe one thing more @EngincanV! Can you give me the localization strings for me to override in Icelandic?

Here it is:

```json
{
  "culture": "en",
  "texts": {
    "Volo.Abp.Gdpr:010001": "There is a personal data download request you have made before. You cannot make a new one until this request is fulfilled.",
    "Volo.Abp.Gdpr:010002": "Your personal data is still being prepared. You can download it at {GdprDataReadyTime}.",
    "PersonalData": "Personal Data",
    "Menu:PersonalData": "Personal data",
    "PersonalDataDescription": "Your account contains the personal data that you have given us. This page allows you to download or delete that data.",
    "RequestPersonalData": "Request Personal Data",
    "DeletePersonalData": "Delete Personal Data",
    "CreationTime": "Creation Time",
    "Action": "Action",
    "Preparing": "Preparing",
    "Download": "Download",
    "ReadyTime": "Ready Time",
    "DeletePersonalDataWarning": "Deleting this data will remove your account and you will no longer log in to the application! Are you sure you want to proceed?",
    "PersonalDataDeleteRequestReceived": "Your personal data delete request is being processed... At the end of the data deletion process, your account will be deleted and you will no longer be able to use it.",
    "PersonalDataPrepareRequestReceived": "Your personal data request is being processed. You can download it from this page, once it's ready!",
    "NoDataAvailable": "No data is available.",
    "Accept": "Accept",
    "CookiePolicy": "Cookie Policy",
    "PrivacyPolicy": "Privacy Policy",
    "ThisWebsiteUsesCookie": "This website uses cookies to ensure you get the best experience on the website.",
    "CookieConsentAgreePolicies": "If you continue to browse, then you agree to our {0} and {1}.",
    "CookieConsentAgreePolicy": "If you continue to browse, then you agree to our {0}."
  }
}
```

> Can´t you make all these strings open source, so we don´t have to ask all the time?

I'll share your suggestion with the team. In meantime, you can send a request to the `/api/abp/application-configuration` route to see all localization values by modules.
