### ISSUE TITLE
Use EF 7 compatible `Devart.Data.Oracle.EFCore` package.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#14412]
**We have to wait for `Devart.Data.Oracle.EFCore` to support NET 7.**

https://www.nuget.org/packages/Devart.Data.Oracle.EFCore

**Comment by maliming** [comment]
Oracle released the new package.

https://www.nuget.org/packages/Oracle.EntityFrameworkCore/7.21.8

https://github.com/abpframework/abp/pull/15172

**Comment by alexandis** [comment]
What is a state of this? Seems like I am stuck with ABP upgrade to 7.0.1: DB migration produces the error, probably because the migration project relies on Devart driver which does not work??

**Comment by maliming** [comment]
They haven't released the new EF Core 7 package yet.

**Comment by alexandis** [comment]
> They haven't released the new EF Core 7 package yet.

Is it possible to make migration without Devart? The problem is I need to omit quotes for object names and try to use `DbCommandInterceptor`, but for some reason the quotes are always generated.

**Comment by maliming** [comment]
I think we have to wait for the new package.
