### ISSUE TITLE
Suggestion: Email verification when user changes his/hers email?

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14422]
User needs to an email address to be validated when they sign up but not if they change their email. 

Does it make sense to have them validate the new one also? Or have the option of that step in settings?

**Comment by maliming** [comment]
hi

You can customize the business logic yourself.

**Comment by sturlath** [comment]
I know @maliming but isn´t this same as https://support.abp.io/QA/Questions/4469/Entering-invalid-phone-number-locks-you-out-of-the-system#answer-e1ededc6-2ed4-c0e9-61dd-3a09383bd39e ?

I know its commercial but the issue is locked so I can´t comment there.

Feels like this should be built in...
