### ISSUE TITLE
Identity UI Customization 

### ISSUE THREAD

**Issue by osama9** [abpframework/abp#1443]
How can I change the register and login views? I want to add additional fields.

**Comment by wayneboyles** [comment]
Simply create the corrosponding view in your web project. So for example Pages\Account\Login.cshtml

You can view the source for those files here so you can see how it's wired up.

https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml

**Comment by devjaw** [comment]
i create corrosponding view in my project but nothing changed when i run the project. should i remove all account module and make a new one ?

**Comment by juicycleff** [comment]
The same thing I'm wondering too. I think creating a new one will be best I guess

**Comment by maliming** [comment]
Please check the documentation: https://docs.abp.io/en/abp/latest/Virtual-File-System#views-pages
