### ISSUE TITLE
why extra properties not show in profile page?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#14438]
I add some extra properties like this:
` ObjectExtensionManager.Instance.Modules()
                 .ConfigureIdentity(identity =>
                 {
                     identity.ConfigureUser(user =>
                     {
                         user.AddOrUpdateProperty<string>( //property type: string
                             "PersonIdentityNumber", //property name
                             property =>
                             {
                                 //validation rules
                                 property.Attributes.Add(new RequiredAttribute());
                                 property.Attributes.Add(new StringLengthAttribute(64) { MinimumLength = 4 });

                                 //...other configurations for this property
                             }
                         );

                         user.AddOrUpdateProperty<DateTime>(
                             "WorkDate",
                             property =>
                             {
                                 property.DefaultValueFactory =() => Convert.ToDateTime(DateTime.Now.ToString("yyyy-MM") + "-01");

                             }
                             );
                     });
}`

It work well when I add/Edit User
![image](https://user-images.githubusercontent.com/5259153/197720879-834f6725-93ad-46ad-a4a1-22f30a8accbd.png)
but I can't see any Info in User Profile page:
![image](https://user-images.githubusercontent.com/5259153/197721302-45667193-45ca-40c2-9d6d-6e02e7cd1ecf.png)

how to show the extra properties in user Profile page?

**Comment by rqx110** [comment]
see https://github.com/abpframework/abp/issues/13999
