### ISSUE TITLE
Multiple database connectstring problem with DbMigrator

### ISSUE THREAD

**Issue by indexlang** [abpframework/abp#14440]
abp :V6.0
I want change the AbpSettingManagement module to an single db.
just create a new start project: abp new Acme.BookStore
change the DbMigrator project appsetting file：
change the ConnectionStrings to:
```
  "ConnectionStrings": {
    "Default": "Server=localhost;Database=BookStore;Trusted_Connection=True;MultipleActiveResultSets=true",
        "AbpSettingManagement": "Server=localhost;Database=App_setting;Trusted_Connection=True"

  },
```
then run the DbMigrator project and get a error,cannot generate database App_setting,what's the reason?

**Comment by berkansasmaz** [comment]
Hello, I did it for an application running in version 4.2.2 for AuditLog module, you can do it very similarly.

v4.2.2 sample code: https://support.abp.io/QA/Questions/3212/Seperate-DB-for-Audit-tables#answer-f65e1169-f613-dccd-f83b-3a0460775c28

Although the code logic is very similar to version 6.0.0, if you have trouble, I recommend you to review the [this sample](https://github.com/abpframework/abp-samples/tree/master/EfCoreMigrationDemo). With this demo, a separate database for AbpPermissionManagement, AbpSettingManagement and AbpAuditLogging modules has been used and is up to date.

![22d3afd08d318700a28e3a0351ac75e0](https://user-images.githubusercontent.com/31216880/197854837-a5346ce5-957e-413b-91c7-9b14272f402b.png)
