### ISSUE TITLE
BoldReports

### ISSUE THREAD

**Issue by BogdanJak** [abpframework/abp#14449]
ABP Framework version - 6.0
Blazor Server, MS SQL Server, 

Anyone have an idea how to integrate BoldReport with Syncfusion with the ABP Blazor server application?

**Comment by fileman** [comment]
I taked a look at this integration this summer, the main issue was to UI/css between syncfusion controls and bold reports

**Comment by BogdanJak** [comment]
> Przyjrzałem się tej integracji tego lata, głównym problemem było UI / css między kontrolkami synchronizacji a odważnymi raportami

Hi fileman

Have you managed to run BoldReports on the ABP framework?
I think I've overcome the css/theme issues but I get an empty report viewer. The browser console shows an error in the PostReportAction section of the API controller.
Maybe you have an idea how to bypass this error?

**Comment by fileman** [comment]
Hi, 
try to add [IgnoreAntiforgeryToken] to Controller

**Comment by BogdanJak** [comment]
Hi Fileman

Thank you very much. Your help has worked - everything works fine.
Support BoldReports fell for this error.
Thanks.

**Comment by fileman** [comment]
@BogdanJak are you still using BoldReport ?
