### ISSUE TITLE
Dynamic C# Client Proxy

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1444]
First let me thank you for this amazing well-designed framework.

Regarding https://docs.abp.io/en/abp/latest/AspNetCore/Dynamic-CSharp-API-Clients
```
[DependsOn(
    typeof(AbpHttpClientModule), 
    typeof(BookStoreApplicationModule) //contains the application service interfaces <--- (this)
    )]
```

Let's say I need a C# client in a desktop application, from an architectural point of view what can i do so that I dont have to share the actual implementation of the interfaces and business logic. 

Would it be appropiate to split the project as follows? Or what would be the best way to do it?

MyProject.Application.Contracts? / Common? / Core
MyProject.Application.Dtos // Dtos go here
MyProject.Application.Core //Implementation goes here

**Comment by hikalkan** [comment]
Hi,

Have you checked the latest MVC application template which addresses the problem you have: https://docs.abp.io/en/abp/latest/Startup-Templates/Mvc#solution-structure

Application.Contracts -> App service interfaces and DTOs (no point to split them)
Application -> Implementation of the app service interfaces.

**Comment by wocar** [comment]
Thank you!
