### ISSUE TITLE
Volo.Abp.LeptonXTheme.Pro version 1.0.0, not 6.0.0

### ISSUE THREAD

**Issue by merijng** [abpframework/abp#14444]
* Your **ABP Framework version**: 6.0.0
* Suite version: 6.0.0

See image below.

I think its better to align this with all other nuget package versions (version 6.0.0 in this case)?

In addition, we had a hard time pressing the "Ok" button (see image) in the suite: it is often disabled, even after filling in all fields. Is this a related issue, maybe?

![image](https://user-images.githubusercontent.com/6886678/197951472-9e239f70-4630-4b53-9c40-1fd40ea0510c.png)

**Comment by maliming** [comment]
hi

Please discuss the suite on https://support.abp.io/QA/Questions/New

Thanks.

**Comment by merijng** [comment]
Dear @maliming,

What about the versioning? That's not a Suite issue. I was just wondering if the disabled "Ok" button was related to the versioning. That's why i used a screenshot, of the Suite.

**Comment by ebicoglu** [comment]
we'll check the button disabled issue.
for the versioning, LeptonX is another project that has a different repo and we release LeptonX frequently (not like the other ABP packages). this gives us to release new versions very fast. if we align with other ABP packages, you'll have to wait 1.5 months to get a new LeptonX version.

**Comment by merijng** [comment]
@ebicoglu Seems legit!
