### ISSUE TITLE
CLI: Make related configurations for theme selection (Angular UI)

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#14446]
After https://github.com/abpframework/abp/pull/14445 is merged, we need to update the [`ChangeThemeStep.cs`](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/Building/Steps/ChangeThemeStep.cs) to support changing related lines on **angular.json** file.

**Comment by ebicoglu** [comment]
we'll implement this in 6.0.2
