### ISSUE TITLE
IRemoteStreamContent returns with default value instead of null when 204 is returned in the API.

### ISSUE THREAD

**Issue by rwecho** [abpframework/abp#14443]
Hi 

We defined an API for image files in the application services layer, like this:

``` C#
// contracts:
Task<IRemoteStreamContent?> GetNamedImageAsync(Guid id);

// ApplicationService

public Task<IRemoteStreamContent?> GetNamedImageAsync(Guid id)
{
      var imageName = GetImageName(id);

      if(!File.Exist(imageName))
      {
           return null;
      }

     //  construct RemoteStreamContent
}
```
Then consume the API in the client by proxy to the contract layer, like this:

``` C#

var imageContent = this.ImageStorageAppService.GetNamedImageAsync(id);

if(imageContent == null)
{
   // handle UI with 
}

// xxxx
```

It works if the image exists. But when the image is not found, the API return 204 HttpStatus. And the client can not deserialize API with the null value.

![image](https://user-images.githubusercontent.com/8048753/197946789-b5e35548-51eb-4a4b-a79e-883643a7800b.png)

**Comment by maliming** [comment]
You can consider throwing an exception if the file does not exist. `IRemoteStreamContent `represents a stream. It should not be null

**Comment by rwecho** [comment]
thanks.
