### ISSUE TITLE
[Suggestion] Accept donations

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1445]
Would be nice to be able to donate every now and then. Love this framework thank you.

**Comment by hikalkan** [comment]
Thank you very much for your kindly approach. But we don't want to get donations, because we have already created a business model around this project :)
Thank you again.

**Comment by wocar** [comment]
I know you have a business module in place, just wanted to contribute. Thank you!!

**Comment by maliming** [comment]
Github previously launched the GitHub Sponsors feature.
https://github.com/sponsors
