### ISSUE TITLE
docs module - scroll area is too short.

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#14464]
In this case, it seems there are no more items on the menu, but there are.
<img align="left" src="https://user-images.githubusercontent.com/23705418/198240601-26d419d5-1353-428c-a245-4dfbeb8ec80b.png" />

![image](https://user-images.githubusercontent.com/23705418/198240332-568b9c57-4bcc-47d7-9fde-e1cfa9172bc6.png)

The scroll area is finished at that line and seems like there is no more element in the menu

**Comment by rqx110** [comment]
Others can be improved in doc module:
1. hide or auto display the scroll bar in breadcrumb
![image](https://user-images.githubusercontent.com/1829209/198421660-ec6c8465-8315-457d-8e8b-1b2941e946b7.png)
2. the height between version select and language select are not equal
![image](https://user-images.githubusercontent.com/1829209/198421815-7d6c11ff-1228-474a-a44f-25d182188369.png)
3. the left padding of language select is different than the version select
![image](https://user-images.githubusercontent.com/1829209/198421924-af519f1b-7568-45c0-aaea-28b839100195.png)

**Comment by ram16g** [comment]
![image](https://user-images.githubusercontent.com/11473136/201248671-042821ed-5a31-443c-b2d9-43c46e9eccb5.png)

**Comment by EngincanV** [comment]
resolved with https://github.com/abpframework/abp/pull/15046
