### ISSUE TITLE
Put a button to the feature management dialog reset features

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#14470]
Place a button to the feature management dialog reset tenant features (techically, delete the tenant's feature values in database)

Button's name: "Reset to defaults"

**Comment by sturlath** [comment]
Would it also be possible to export them so they can be reset and then imported again? Just a thought?

**Comment by muhammedaltug** [comment]
Assigned myself for angular implementation

**Comment by enisn** [comment]
> Would it also be possible to export them so they can be reset and then imported again? Just a thought?

Thanks @sturlath 

We'll consider it later in future versions. Currently, they can't be removed from the UI. The first step is making them able to remove from database_(Or any other datastore)_. We'll use your feedback in the future to improve feature management.

**Comment by malikmasis** [comment]
@muhammedaltug blazor and razor side was completed. FYI.

**Comment by malikmasis** [comment]
have you look at https://github.com/abpframework/abp/pull/14547, please?

**Comment by fatihskilic** [comment]
Angular complated. https://github.com/abpframework/abp/pull/15129
