### ISSUE TITLE
Dynamic Proxy URL Conflict

### ISSUE THREAD

**Issue by omer-repo** [abpframework/abp#14489]
* Your **ABP Framework version**. 5.2.2
* Your **User Interface** Blazor Wasm
* Your database provider(EF Core/MongoDB) EF Core

Hi,
ABP Dynamix Proxy feature generates URLs between backend and Blazor well. I realized there is a bug when I created a new method in application service with the name GetList**2**Async. (GetList2Async is a clone method from GetListAsync. I didn't want to override existing one and created a new method for customization)

Actually there wasn't a problem when application service depends on a domain class with Guid. But when domain class is created with integer type for Id, it occurs a conflict between two different methods.

Domain class(Category.cs): 
`public class Category: Volo.Abp.Domain.Entities.Auditing.FullAuditedAggregateRoot<int>`

Interface (ICategoryAppService.cs):
`Task<PagedResultDto<CategoryDto>> GetList2Async(PagedAndSortedResultRequestDto input);`

Generated URL for GetList**2**Async:
https://localhost:44338/api/app/category/2?SkipCount=0&MaxResultCount=1000&api-version=1.0

Generated URL for GetAsync (Id=2)
https://localhost:44338/api/app/category/2?api-version=1.0

As you can see, both URLs are pointing to the same endpoint when I want to get details of category with the Id =2. There is no problem for the other categories.

Now I changed the name of GetList2Async to another name and problem is solved. But, it may be necessary to change the naming process in dynamix proxy URL generation in case of this possibility.

**Comment by maliming** [comment]
I don't recommend that you use numbers as the method names.

`Task<PagedResultDto<CategoryDto>> GetListTwoAsync(PagedAndSortedResultRequestDto input);`
