### ISSUE TITLE
AbpException: Could not find the bundle file '/libs/bootstrap/css/bootstrap.css' for the bundle 'Blazor.LeptonXLiteTheme.Global'!

### ISSUE THREAD

**Issue by IbrahimTimimi** [abpframework/abp#14487]
I followed these steps to create my ABP Blazor Server project:
1. Downloaded project from [Get Started](https://abp.io/get-started)
2. Run `dotnet restore` at project solution folder.
3. Updated connection string at both `DbMigrator` and `EntityFrameworkCore` projects.
4. Run the `DbMigrator` console project to create migration and seed data. (db was created with seeded tables)
5. Run `abp install-libs` at Blazor project folder.
6. Run `dotnet run` at Blazor project folder.

Result:

![Capture2](https://user-images.githubusercontent.com/53964046/198826165-ad591976-0d26-4337-88be-96e5653945b4.PNG)

Why are some libs missing at folder `ABP.Server.Blazor\wwwroot\libs`? 
For example, `bootstrap` and `abp` libraries not found.

![Capture](https://user-images.githubusercontent.com/53964046/198826059-07fd1e18-a9e6-43bf-b4c6-112b4712041d.PNG)

**Comment by realLiangshiwei** [comment]
What's the result when you run the `abp install-libs`

**Comment by IbrahimTimimi** [comment]
I found out that I needed to install `yarn`

```
npm install --global yarn
```

And then run again

```
abp install-libs
```

**Comment by mahmutcogaltay** [comment]
aynı hatayı alıyorum yardımcı olabilecek birileri var mı
