### ISSUE TITLE
VueJs Startup template

### ISSUE THREAD

**Issue by softwareguy74** [abpframework/abp#1448]
Vue JS has become very popular.  It would be nice if your automatic UI generation would have a Vue JS option as well,  I'm sure others would agree.

**Comment by hikalkan** [comment]
First SPA will probably be Angular. We are actively working on it. After publishing it, we will work on React or Vue.js.

**Comment by hikalkan** [comment]
duplicate of https://github.com/abpframework/abp/issues/1168
