### ISSUE TITLE
Setting a language should flow from that service to the other ones (and not be the default one).

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14481]
**Scenario:**
If you have these services setup (different URLs/serices)

- PublicPage service
- Identity service
- Backend service

and you change the language for the public page and then hit the login button and are taken to the identity page you get the default language and not the language you just set.

Shouldn´t this language information flow from the service you are on over to the other ones? I´m guessing you could set this as a parameter and do some custom programming but shouldn´t this be the default functionality?

**Comment by maliming** [comment]
You can change the `domain` of the ` CookieRequestCultureProvider.DefaultCookieName` to share the language across multiple domains.

**Comment by sturlath** [comment]
Could you elaborate a little more on this @maliming? 

Any code example you could point me to? I really can´t be the only one wanting this language flow, can it?

**Comment by sturlath** [comment]
@maliming I did try to figure this out but did not manage to use your answer to do this. Could you give little more details on what you were thinking there?
