### ISSUE TITLE
Better isolation between tenants

### ISSUE THREAD

**Issue by softwareguy74** [abpframework/abp#1449]
Since we're doing a complete rewrite, I figured it would be nice to throw this suggestion out there since it is a frustration of the current framework.

It would be really nice if tenant specific artifacts such as Entities, Modules, Applications, etc, would only show up in the specific tenant database.  Currently, for example if you create a "Product" Entity, it will reside in both the Host and Tenant databases, even if I only want "Tenant 1" to have this specific Entity.  This is because it's very likely that we want to create a "Product" for Tenant 1 that is different for Tenant 2.  So why have this in the Host database if it is specific to a particular tenant?

I would also ask for this to extend to other things like Modules.  Just like with Entities, it's possible we want to create tenant specific Modules.

**Comment by hikalkan** [comment]
Hi,

Actually, this was a problem in [ASP.NET Boilerplate](https://aspnetboilerplate.com/). It doesn't exists for this new ABP framework. We will need to create a sample and documentation for this. I am adding it to backlog.

**Comment by a-patel** [comment]
Any update on this?

**Comment by rreitbauer** [comment]
> 
> 
> Hi,
> 
> Actually, this was a problem in [ASP.NET Boilerplate](https://aspnetboilerplate.com/). It doesn't exists for this new ABP framework. We will need to create a sample and documentation for this. I am adding it to backlog.

Does this mean this problem does not exist in ABP.IO?

Is is possible to have different entities only on host or only on tenants?

**Comment by hikalkan** [comment]
Startup template comes with a single dbcontext. So, all tables will be in all databases.
You need to separate the context and migrations. When you have 2 migrations dbcontexts, you can add host related tables to only one of them. https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations may help you to understand the database migration system and separate contexts for your application.
