### ISSUE TITLE
How can I assign extended properties to a new instance of RegisterDto when registering a new user?

### ISSUE THREAD

**Issue by RelevanceRo** [abpframework/abp#14490]
* ABP **6.0**.
* Blazor **WASM**
* SQL Server

I added the following properties to the RegisterDto ( extended it ):
![image](https://user-images.githubusercontent.com/53852553/198904405-467749e1-3300-45ca-8bb0-f5e13129f450.png)

How can I assign the Gender property here:

![image](https://user-images.githubusercontent.com/53852553/198904432-cd29752d-84ae-4ed3-87ac-05bf0c8aebc7.png)

**Comment by realLiangshiwei** [comment]
See: https://docs.abp.io/en/abp/latest/Object-Extensions#setproperty

**Comment by RelevanceRo** [comment]
Hi.

I set the properties, but unfortunately they don't map to the Users table. Only one property gets mapped. For example: Name, Surname don't get mapped, although they are present in the ExtraProperties of RegisterDto.

![image](https://user-images.githubusercontent.com/53852553/199359602-d90ff83c-441c-46f7-9886-9540100f407c.png)


and in DB, table Users:

![image](https://user-images.githubusercontent.com/53852553/199359892-4f8a88e7-b7ef-42e4-8757-54bfe92c0912.png)

What I don't get: why property gender is mapped and the rest are not?!

**Comment by xyfy** [comment]
You must to know ,  you current is only set value to `DTO`, You should map it to the **entity**.

<https://docs.abp.io/en/abp/latest/Object-Extensions#mapextrapropertiesto>
