### ISSUE TITLE
.Net 7 breaks minimal module creation

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#14493]
After https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/default-authentication-scheme breaking change, minimal module creations or core integrations like [Autofac integration](https://docs.abp.io/en/abp/latest/Autofac-Integration) requires explicit schema for authentication.
This may be configured in [Volo.Abp.AspNetCore](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.AspNetCore).

Sample blog post: <strike>https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-5/#simplified-authentication-configuration.</strike> They removed this feature at [7.0.0-rc1](https://github.com/dotnet/aspnetcore/issues/42577).

Basic module:

```cs
[DependsOn(
        typeof(AbpAspNetCoreModule),
        typeof(AbpAutofacModule)
    )]
public class MyFirstModule : AbpModule
{
}
```
Program.cs:
```cs
using MyFirstModule;

var builder = WebApplication.CreateBuilder(args);
builder.Host.UseAutofac();

builder.Services.AddAuthorization();  // .Net7 breaking change

builder.Services.AddApplication<MyFirstModule>(); 
// builder.Authentication.AddJwtBearer();  -> This is added at .NET 7 preview but removed at .NET 7 RC

var app = builder.Build();
app.MapGet("/", () => "Hello World!");

app.InitializeApplication();

app.Run();
```

**Comment by maliming** [comment]
Cause by https://github.com/abpframework/abp/blob/e3e1779de6df5d26f01cdc8e99ac9cbcb3d24d3c/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/AbpAuthorizationModule.cs#L31

**Comment by hikalkan** [comment]
What are the solution offers, their pros and cons?

**Comment by maliming** [comment]
> What are the solution offers, their pros and cons?

I think we can call `context.Services.AddAuthorization()` before call ` context.Services.AddAuthorizationCore(); ` 

The problem can be solved by `AddAuthorization`

**Comment by hikalkan** [comment]
I suppose `AddAuthorization()` already does what `AddAuthorizationCore()` does. If no side effect, we can do that.
