### ISSUE TITLE
Abp.Account Module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#145]
- [x] Login
- [x] Remember me
- [x] User lockout
- [x] Logout
- [x] Register
- [x] Tenant-based Identity Options

**Comment by dcagnetta** [comment]
Does this work on IdentityServer?

**Comment by hikalkan** [comment]
There are two packages:

* Volo.Abp.Account.Web
* Volo.Abp.Account.Web.IdentityServer	

See https://github.com/abpframework/abp/tree/master/modules/account/src
