### ISSUE TITLE
Theme Bug

### ISSUE THREAD

**Issue by KaungZawHtet** [abpframework/abp#14506]
Abp Version : `6.0.1`
Creation Cmd `abp new TodoApp -t app-nolayers -dbms MySQL`

When I click this button, only main page change, not drawer
<img width="86" alt="Screenshot 2022-11-01 at 3 15 32 PM" src="https://user-images.githubusercontent.com/15225530/199194218-2e06b32c-8874-4604-8fd4-4949bc65d686.png">

https://user-images.githubusercontent.com/15225530/199194042-c350f4e7-cd92-48fc-b4b6-b3f0702473fe.mov

**Comment by EngincanV** [comment]
Hi, after clicking the menu collapse button you should hover out from the menu section to make it collapse.

![header](https://user-images.githubusercontent.com/43685404/199199598-f1179bb7-82d4-4d87-917e-2ac9c8902c9a.gif)

**Comment by KaungZawHtet** [comment]
I see. If so, this is not a bug, this is feature 👍

**Comment by 274188A** [comment]
describe the feature for me please?  - sorry if you're just joking...

**Comment by 274188A** [comment]
ah, I see - happy to close this - a little unintuitive but it works well.
