### ISSUE TITLE
Dynamic C# API Client Proxies Unable to get jwt in header

### ISSUE THREAD

**Issue by XuMengEnEli** [abpframework/abp#14509]
![image](https://user-images.githubusercontent.com/37646958/199233148-87265bf4-54a7-413e-bd5e-014b453167cd.png)

Hello, I cannot get the content in the header in the called method when using **Volo.Abp.Http.Client  5.3.3**,How to automatically forward the jwt in the current request to the target service?

**Comment by realLiangshiwei** [comment]
If you want to know the implementation details, you need to view the source code.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Http.Client.IdentityModel/Volo/Abp/Http/Client/IdentityModel/IdentityModelRemoteServiceHttpClientAuthenticator.cs

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Http.Client.IdentityModel.Web/Volo/Abp/Http/Client/IdentityModel/Web/HttpContextIdentityModelRemoteServiceHttpClientAuthenticator.cs
