### ISSUE TITLE
Make _container in BlobContainer protected and methods virtual.

### ISSUE THREAD

**Issue by CrazyBaran** [abpframework/abp#14517]
https://github.com/abpframework/abp/blob/3427ba632fd8f3947ca65db40a0119674d05e5fc/framework/src/Volo.Abp.BlobStoring/Volo/Abp/BlobStoring/BlobContainer.cs#L13

Right now I made custom BlobProvider for Azure to had possibility to create SasToken rather to push all file throw application. From documentation we had information that if we like to Customize we should override AzureBlobProvider.
https://docs.abp.io/en/abp/latest/Blob-Storing-Azure#other-services
but cause this _container is private we cannot really Customize BlobContainer, after customization of Provider, so it is hard to reuse code and add new methods to BlobContainer. Let me know if my understanding is proper.  tl;dr; I would like to extend BlobContainer with new methods.
Walkaround is of course again use blobContainerFactory.Create<TContainer>(); in constructor of custom blob, but as you could understand it is little weird solution.

**Comment by CrazyBaran** [comment]
Oh I see that would be more problematic to Customize... blobContainerFactory.Create(); didnt use any ServiceProvider so it would be impossible to Replace internal _container...

**Comment by CrazyBaran** [comment]
Ok it could be potencially possible to inject CustomBlobContainer with customization of Factory and replace factory, but this private property is still issue.

**Comment by CrazyBaran** [comment]
I tested, it is quite straight forward to replace standard BlobContainer with customized one. So this is only one disadvantage of this class that it is hard to extend. If nobody had problem with that, I would open PR for it.

**Comment by maliming** [comment]
hi

Welcome to contribute the code.
