### ISSUE TITLE
Active elements are not clickable

### ISSUE THREAD

**Issue by Aarnihauta** [abpframework/abp#14529]
Abp versions: 5.2.2, 6.0.1
UI: MVC

For some users, popoverjs adds this style to the body tag, which makes it impossible to click on active elements

![image](https://user-images.githubusercontent.com/62142248/199692328-e5f727e2-5d3c-44c7-b427-d7f3efa2ed1e.png)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.
