### ISSUE TITLE
Shouldn't SettingManagentStore be in <ProjectName>.EntityFrameworkCore?

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1453]
Hi,

The default template generates the following:

![image](https://user-images.githubusercontent.com/4738140/60786745-f93beb80-a19a-11e9-99b8-9acdb00854e4.png)

Seems to me this should:

a) Not be in the migrations project
b) Be in a file called SettingManagementStore

as it is not a module.

**Comment by yekalkan** [comment]
![image](https://user-images.githubusercontent.com/5793291/60787350-33d56200-a162-11e9-9ea6-6602f6668a22.png)

Am i missing something?

**Comment by natiki** [comment]
@yekalkan it is my bad.... I was actually inside a Volosoft assembly. I am closing. Sorry about that.
