### ISSUE TITLE
[Angular] Service Proxy generation changes for integration services.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#14540]
> JavaScript / Angular code generation should generate proxy only for application services by default, but can specify --service-type all or integration to override it.

Continue with https://github.com/abpframework/abp/pull/14288

A new parameter `--service-type(application, integration, all)` passed to `@abp/ng.schematics proxy-add`.

There is a new property `isIntegrationService` added to the `generate-proxy.json`.

![image](https://user-images.githubusercontent.com/6908465/199903139-f74c6b45-b558-4d66-847b-56fa1cb2829c.png)

**Comment by hikalkan** [comment]
done by https://github.com/abpframework/abp/pull/14968
