### ISSUE TITLE
I wanna custom my own granttype in openiddict, what should i do?

### ISSUE THREAD

**Issue by hangyejiadao** [abpframework/abp#14542]

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Modules/OpenIddict

Please get more help from openiddict.

https://github.com/openiddict/openiddict-core/issues/new/choose

**Comment by hangyejiadao** [comment]
https://docs.abp.io/en/abp/latest/Modules/OpenIddict 
from here i cant find what can solve  my problem   ,abp encapsulated openiddict Seriously ,i have tried many methods but  these doesnt work
