### ISSUE TITLE
When I use reverse engineering for entities, When an update is taken BasicAggregateRoot will be missing. Forcing to update entities in all sql updates.

### ISSUE THREAD

**Issue by Mahesh3677** [abpframework/abp#14550]
public partial class EntityClass : BasicAggregateRoot<Guid>
    {

}

**Comment by maliming** [comment]
hi

* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by Mahesh3677** [comment]
I am using version 6.0.
Added domain classes by reverse engineering using EF core power tools.
inherited entities with BasicAggregateRoot.
When I use  EF core power tools again for updating the entities , BasicAggregateRoot will be missing from entity class.

**Comment by maliming** [comment]
>  using EF core power tools.

I think this is not abp problem.
