### ISSUE TITLE
Adding EnableRetryOnFailure for SQL fails migration.

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I´m getting this exception 

> An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call." - [explained here in more details.](https://www.thecodebuzz.com/enabling-transient-error-resiliency-enableretryonfailure/)

But if I try to update the code with

`builder => builder.EnableRetryOnFailure()`

I get a migration error 

```
2022-11-07T12:30:03.3341226Z [12:30:03 INF] Migrating schema for host database...
2022-11-07T12:30:04.1373400Z [12:30:04 ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext'.
2022-11-07T12:30:04.1375224Z System.InvalidOperationException: The configured execution strategy 'SqlServerRetryingExecutionStrategy' does not support user-initiated transactions. Use the execution strategy returned by 'DbContext.Database.CreateExecutionStrategy()' to execute all the operations in the transaction as a retriable unit.
2022-11-07T12:30:04.1376536Z    at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.OnFirstExecution()
```

And if I try to look that up there is an [old comment that says that abp.io doesn´t support it](https://github.com/abpframework/abp/issues/10183). 

Is that still the case? And if so, why?

### Reproduction Steps

Add  `builder => builder.EnableRetryOnFailure()` to UseSqlServer in EntityFrameworkCoreModule and DbContextFactory and run migration and get error.

### Expected behavior

Retry mechanism working

### Actual behavior

Error in migration

### Version

6.0.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by sturlath** [comment]
Should this maybe only be set in the `DbContextFactory` class? The [comment about it not being supported](https://github.com/abpframework/abp/issues/10183#issuecomment-1007100767) in abp.io is making me usure because the code seems to be working fine.

OK found an answer since I month ago about it [**not** being supported](https://support.abp.io/QA/Questions/3781/EnableRetryOnFailure#answer-8204fe23-ae85-c563-7196-3a069adb4f50). 

Why?

Btw it looks like my issues are not some deadlock stuff but probably shared dev environment in Azure. "An application using shared resources in a shared environment, especially in the cloud environment is more sensitive to transient faults."

**Comment by maliming** [comment]
hi

We are using `BeginTransaction` in the unit of work now.

https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#execution-strategies-and-transactions

**Comment by sturlath** [comment]
@maliming does that mean you are handling the retry or do I need to implement it (as in the code example)?

**Comment by maliming** [comment]
hi

You can try to implement it your self.
