### ISSUE TITLE
is abp.io website no longer open source?

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1457]
It was good to have a look at how the abp.io has been put together to learn from. is it no longer open source?

**Comment by maliming** [comment]
Because it is no longer a simple framework introduction and template download, it contains more features, etc., not suitable for open source.

**Comment by hikalkan** [comment]
In addition to @maliming's comment, actually nothing special to learn from abp.io web site code. There are many more sophisticated source code already open based on ABP: samples, modules, the framework itself...
