### ISSUE TITLE
docs - Add the "Edit" button

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14577]
There was an edit before the update, but now it's gone.
Add the button again.
![image](https://user-images.githubusercontent.com/9526587/200486439-376f83ae-e20d-4ad1-b016-9ec4e218797e.png)

**Comment by EngincanV** [comment]
It's already done (with [this commit](https://github.com/abpframework/abp/commit/3a5fa78a967fa0810e3758b9cc4bdd1af290420b#diff-26c8b64a32e19b8f3eff2d33869f1658dc85b0f2a222ae62f9b19af9a2704455L252)), but i'll check it.
