### ISSUE TITLE
Couldn't find any versions for "@abp/ng.theme.lepton-x" that matches "^1.0.0"

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#14586]
abp version 6.0.1
ui: angular

using command `abp new Acme.BookStore -csf -u angular` to create project:
![image](https://user-images.githubusercontent.com/1829209/200736334-b246894c-5d5f-4fb7-af04-7895a902c1d3.png)

I think it relate the tag of @abp/ng.theme.lepton-x package on `nmpjs.com`.  version `1.0.0` is tagged with `preview`
![image](https://user-images.githubusercontent.com/1829209/200736649-2531f4a3-3997-4db6-8857-d0f37f52c5a1.png)

**Comment by enisn** [comment]
It seems there is confusion on version tags. We'll work on it.
