### ISSUE TITLE
Upgrade to Blazorise 1.1.3

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#14589]
https://blazorise.com/news/release-notes/113

From Blazorise 1.1.3, Blazorise now fully supports the final .NET 7 version

**Comment by sturlath** [comment]
Can we update to 1.1.4.1 please?

> Blazorise 1.1.4 is a recommended upgrade for all Blazorise 1.1 and Blazorise 1.1.3 users.

[See]( https://blazorise.com/news/release-notes/114 )

**Comment by realLiangshiwei** [comment]
Yes, we will : https://github.com/abpframework/abp/issues/14833
