### ISSUE TITLE
Using CSRF Anti Forgery System in microservices scene

### ISSUE THREAD

**Issue by journey191** [abpframework/abp#14591]
[Please check the official documentation before asking questions: https://docs.abp.io](https://docs.abp.io/en/abp/latest/CSRF-Anti-Forgery)

* Your **ABP Framework version**:4.3.0.
* Your **User Interface** type:VUE

After proxy,my webapp and backend microservices run on same domain,therefore,each service will validate XSRF-TOKEN for requests from webapp.
**There are 3 questions confused me:**

- **1.webapp should send requests to abpconfiguration endpoint of all services?if there are 10 services,webapp should send 10 request?**
like this?

![image](https://user-images.githubusercontent.com/11626700/200804701-f49241e1-9313-4c43-9d2d-5cbce218a045.png)

![image](https://user-images.githubusercontent.com/11626700/200805291-0461d779-ed8c-4abb-82b1-258f13551e14.png)

- **2.each service has its own XSRF-TOKEN value,but use  same cookie named `XSRF-TOKEN`.how to avoid overridding?**
- 
- **3.what should webapp do to access diffrent CSRF validation from diffrent service?**

**Comment by realLiangshiwei** [comment]
I think it is not related to ABP, this is browser behavior.

**Comment by junyuan** [comment]
In my opinion, the anti-forgery validation should be performed in gateway in this scenario. the problem here is the configuration end point always set an xsrf token in cookie which we don't want to. there should no anti forgery validation between the gateway and the Api.

I remove the filter to disable it
``` C#
Configure<MvcOptions>(mvcOptions =>
{
    mvcOptions.Filters.Remove(new AbpAutoValidateAntiforgeryTokenAttribute());
});
```
