### ISSUE TITLE
The AppService reported an error using the user-defined route

### ISSUE THREAD

**Issue by chenyigg** [abpframework/abp#14596]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When I created the AppService and inherited from **ReadOnlyAppService**, I wanted to change the route, So on AppService added features **[Microsoft. AspNetCore. Mvc.Route (" / API/XX/XX ")]**, but if you add the feature, inherited GetAsync method cannot automatically parse in Swagger, I need to manually add [HttpGet],[HttpPost] and other features to each method.
An unhandled exception has occurred while executing the request. An unhandled exception has occurred while executing the request.
> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException:  Ambiguous HTTP method for action - Decision.Application.Business.Record.LoginRecordAppService.GetAsync  (Decision.Application). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0

Is there any corresponding solution

### Reproduction Steps

```
[Route("/api/Record/Login")]
    public class LoginRecordAppService : ReadOnlyAppService<IdentitySecurityLog, IdentitySecurityLogDto, Guid, IdentitySecurityLogListInput>
    {
        public LoginRecordAppService(IRepository<IdentitySecurityLog, Guid> repository) : base(repository)
        {
        }
        public override Task<IdentitySecurityLogDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
    }
```

### Version

6.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0

**Comment by chenyigg** [comment]
> 操作需要为 Swagger/OpenAPI 3.0 显式绑定 HttpMethod

GetAsync or CreateAsync will automatically recognize a Get or Post request by default.

**Comment by chenyigg** [comment]
> 



> 操作需要为 Swagger/OpenAPI 3.0 显式绑定 HttpMethod

But now that you've added the Route feature, you can't automatically recognize it

**Comment by maliming** [comment]
This is related to `Swashbuckle` instead of abp.
