### ISSUE TITLE
Why we changed the enum localization keys, when the ajax return the enum as int,not string?

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#14598]
as mentioned in the issue  #13264

we changed the enum localizatiion key in #13451

But I got some thing conflict in <https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=MVC&DB=EF#localization>

the ajax  call `acme.bookStore.books.book.getList` return type as int ,not string

Why we change the localization keys to string?

If you're creating a bug/problem report, please include the followings:

*  ABP 6.0.1
*  MVC
*  EF Core
![WX20221110-165403@2x](https://user-images.githubusercontent.com/7838147/201045319-5dc46ea8-8b29-4eba-a11a-923a737eafe8.png)

**Comment by SergeySorokin** [comment]
@xyfy, while ABP team is working on the fix, the issue could be temporary resolved by adding redundant text in the localization file, i.e. you need to localize the each enum method name twice with the same localization text like this: 

{
"Enum:BookType:0": "Undefined",
"Enum:BookType.Undefined": "Undefined"
}

**Comment by xyfy** [comment]
so when  you fixed，abp will return enum as string？发自我的手机-------- 原始邮件 --------发件人： Sergey Sorokin ***@***.***>日期： 2022年11月24日周四 11:47收件人： abpframework/abp ***@***.***>抄送： xyfy ***@***.***>, Mention ***@***.***>主    题： Re: [abpframework/abp] Why we changed the enum localization keys, when the ajax return the enum as int,not string? (Issue #14598)
@xyfy, while ABP team is working at the fix, the issue could be temporary resolved by adding redundant text in the localization file, i.e. you need to localize the each enum method name twice with the same localization text like this:
{
"Enum:BookType:0": "Undefined",
"Enum:BookType.Undefined": "Undefined"
}

**Comment by xyfy** [comment]
@SergeySorokin  Which issue can track progress?
