### ISSUE TITLE
An error occurred during the ABP remote HTTP request. (No connection could be made because the target machine actively refused it. (localhost:44357))

### ISSUE THREAD

**Issue by kgrontis** [abpframework/abp#14604]
### Description

Hello. I just started using the framework. After following the Getting Started  - Running the Solution step, i stumbled below error.
Attached you will find the logs.txt

![image](https://user-images.githubusercontent.com/7747808/201216775-5f4f511f-0224-491f-90c2-72137cd8d767.png)
[logs.txt](https://github.com/abpframework/abp/files/9984957/logs.txt)

### Reproduction Steps

- Created new solution with cli by using: abp new Name -u blazor-server --tiered
- Followed all instructions up until Getting Started -> Running the Solution.
   [https://docs.abp.io/en/abp/latest/Getting-Started-Running-Solution?UI=BlazorServer&DB=EF&Tiered=Yes](url)
- Error appeared after following the third step which says `Lastly, ensure that the .Blazor project is the startup project and run the application which will open a welcome page in your browser` , 

### Expected behavior

When setting as startup the Blazor page and run the application, the welcome page should appear.

### Actual behavior

When setting as startup the Blazor page and run the application, an error appears.

### Version

6.0.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Is the `localhost:44357` project running?

**Comment by kgrontis** [comment]
No it wasn't running, there was an issue on .HttpApi.Host i havent noticed. Thanks a lot!
