### ISSUE TITLE
Blazor profile image pointing to localhost

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The image for logged in user is broken because its pointing to localhost
![image](https://user-images.githubusercontent.com/2386572/201370400-d40ee9dc-40ec-47f2-bc4d-e9142037f231.png)

![image](https://user-images.githubusercontent.com/2386572/201370469-e96f47e5-c791-455a-9717-6cf0b5f36c1b.png)

There are no special settings for this and nothing in my config pointing to localhost. This works fine for the public page

![image](https://user-images.githubusercontent.com/2386572/201370825-3bee8b62-5377-4f6e-93c7-d99df2c79381.png)

Or is this connected to the appsettings.json in my Blazor (that up until now hasn´t been configured specially by me and has just stayed default)
![image](https://user-images.githubusercontent.com/2386572/201372599-3e70b9f6-35ef-432d-9132-8f912e8e23e3.png)

### Reproduction Steps

Update to 6.0.1 and see Blazor profile image broken because its pointing to localhost

### Expected behavior

Show the correct profile image

### Actual behavior

broken image and console log error

### Regression?

Yes

### Known Workarounds

n/a

### Version

6.0.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by sturlath** [comment]
@EngincanV since this is only now happening for me in Blazor WASM I just want to make sure this isn´t missed. Nothing has changed for me, so I don´t know why it's happening now.

![image](https://user-images.githubusercontent.com/2386572/202671011-135ba693-5507-4aeb-b95f-4f78383291f6.png)

**Comment by EngincanV** [comment]
> @EngincanV since this is only now happening for me in Blazor WASM I just want to make sure this isn´t missed. Nothing has changed for me, so I don´t know why it's happening now.
> 
> ![image](https://user-images.githubusercontent.com/2386572/202671011-135ba693-5507-4aeb-b95f-4f78383291f6.png)

Hi, can you check the `appsettings.json` file for the "RemoteServices" section? It should something like below:

```json
  "RemoteServices": {
    "Default": {
      "BaseUrl": "<your-app-url>"
    },
    "AbpAccountPublic": {
      "BaseUrl": "<your-account-project-url>"
    }
  },
```

Please change the `BaseUrl` for "AbpAccountPublic". Then it should work as expected.

**Comment by sturlath** [comment]
Yes they are all just set to localhost like you see in the image of the first question. This has just been like this for ever so strange its starting to behave like this now.

Should I have appsettings.json files for all my environments and swap between them base on where I´m am? appsettings.development.json for my azure dev and appsettings.production.json for my prod one?

**Comment by EngincanV** [comment]
Since you use a tiered application, you should set the `AbpAccountPublic:BaseUrl` to let the account module get the URL for the profile picture.

> Should I have appsettings.json files for all my environments and swap between them base on where I´m am? appsettings.development.json for my azure dev and appsettings.production.json for my prod one?

Yes, you should change the base URL on production and should point to your identity server, so it can be good to have the **appsettings.production.json**.

**Comment by EngincanV** [comment]
I close the issue, since your problem should be fixed. Feel free to reopen it.

**Comment by sturlath** [comment]
This solved my issue! Thank you for your assistance, really appreciated!
