### ISSUE TITLE
404 error on Lepton.Global bundle (that then shows up)

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I´m getting a 404 error on this bundle even though its clearly there `https://eventstreamingpublicwebdev.azurewebsites.net/__bundles/Lepton.Global.D5BC28C7C804D6CD94CEB89FA20EFA24.css?_v=638037469341657181`

The error
![image](https://user-images.githubusercontent.com/2386572/201329680-e69c9fd5-2efb-4289-a4c3-7508b5c6bb70.png)

But its there
![image](https://user-images.githubusercontent.com/2386572/201330442-1e6a3c9a-4093-4cd8-ab4f-2130d6967dd9.png)

and the code is setup just like the [docs state](https://docs.abp.io/en/abp/6.0/UI/AspNetCore/Theming#abp-scripts)

![image](https://user-images.githubusercontent.com/2386572/201330266-2893a51e-d474-4048-b1fd-1aa7624fe5b1.png)

You can try it out [here](https://eventstreamingpublicwebdev.azurewebsites.net/LoginSelector), you might need to refresh the page few times to get it. Sometimes it's just fine. 

**Update**
Could this be related to this images/logo/lepton/logo-light.png? I didn´t have any lepton folder there. The logo-light.png was folder up.

![image](https://user-images.githubusercontent.com/2386572/201334665-3e9c1876-680a-4c4d-a6d6-fc1111d34c9b.png)

### Reproduction Steps

Add the code like I did above

### Expected behavior

no error in console

### Actual behavior

404 error in console

### Regression?

I think so

### Version

6.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by sturlath** [comment]
OK creating a lepton folder under images and placing logo-light.png file in it seems to have **solved both errors**. I´m not closing this since you probably want to do some update on your part.

`wwwroot\images\logo\lepton\logo-light.png` (note that I have never had this lepton folder there and never an error)

**Comment by EngincanV** [comment]
Hi @sturlath, thanks for reporting.

---

A quick note for who might face this problem: Existing Lepton theme users should move their logos from **wwwroot/images/logo/** to **wwwroot/images/logo/lepton/** folder.
