### ISSUE TITLE
Unable to Authorize Swagger API pages : "The 'client_secret' parameter is not valid for this client application."

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#14617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We updated from using IdentiyServer to Opendict and everything seems to be working just fine with the exception that I can´t Authorize in the Swagger API

> Auth ErrorError: Unauthorized, error: invalid_client, description: The 'client_secret' parameter is not valid for this client application.

![image](https://user-images.githubusercontent.com/2386572/201364959-842cd69f-b396-4af5-a717-433a3768d2cb.png)

Are there some steps missing in the migration information we need to do?

### Reproduction Steps

Update IdentityService to Opendict and try to Authorize in the Swagger UI

### Expected behavior

Being able to Authorize

### Actual behavior

Get this error

`Auth` ErrorError: Unauthorized, error: invalid_client, description: The 'client_secret' parameter is not valid for this client application.

### Regression?

Yes

### Version

6.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
**The 'client_secret' parameter is not valid for this client application.**

Please remove the secret for the swagger client.

**Comment by sturlath** [comment]
And how should I do that @maliming? There is no `ClientSecret` in the config for my Swagger anywhere and the migration docs don´t mention this at all

These are basically my configs and I can´t see anything in the db

```json
  "My_Swagger": {
    "ClientId": "My_Swagger",
    "RootUrl": "https://localhost:44353"
  }
```
