### ISSUE TITLE
Tenant user fail to login

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1462]
1. Build a new abp mvc tiered solution and run it.
2. Log on to "MyProject.Web" as Host user "admin".
3. Create a new tenant "A".
4. Log out form Host.
5. Log on to "MyProject.Web" as tenant "A" user "admin". (By changing tenant at login page)
6. Current user's tenantId is null.
7. Log out form Host.
8. Log on to "MyProject.IdentityServer" as tenant "A" user "admin". (By changing tenant at login page)
9. Open home page of "MyProject.Web" and click "Login" button.
10. See this error:
![image](https://user-images.githubusercontent.com/30018771/60870349-408daf00-a263-11e9-8b7b-6d67390fb719.png)

**Comment by maliming** [comment]
This is because the MyProject.Web project does not reference the Domain module.

**Comment by gdlcf88** [comment]
Hi @hikalkan 
This is a tough question. Do you have any good ideas? thx.

**Comment by hikalkan** [comment]
This may not be a problem in production where you normally use tenant id as a subdomain. I should try this and understand if there is a problem and we can solve it.

**Comment by maliming** [comment]
There is no indirect reference to `AbpTenantManagementDomainModule `in the `MyProject.Web` project.

Causes ITenantStore in `MultiTenancyMiddleware `to be `DefaultTenantStore `instead of `TenantStore`

**Comment by hikalkan** [comment]
Thanks @maliming finding this. So, it will get time to find a good solution to this issue. I moved to the next milestone since we want to release 0.19 tomorrow.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/63251252-eb03e380-c29f-11e9-8333-0bc728c65c4c.png)
Try to make Web depends on Domain, but it thorw an new error.
I need some guide to make it work temporary.

**Comment by gdlcf88** [comment]
After depends on `EntityFrameworkCoreDbMigrationsModule`, it works.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/63264742-65dbf700-c2be-11e9-9052-b6b17fb0e4c1.png)
Many other problems bother me >_<

**Comment by gdlcf88** [comment]
A new problem:
1. Web depends on `AbpTenantManagementDomainModule`.
2. Click "Login" link on Web home page, it dumps to ids4 /account/login page.
3. Select a tenant.
4. Input username(admin) and password(1q2w3E*), click Login button.
5. It dumps back to Web home page.
6. Current user is admin in host(not atenant user).

@hikalkan

**Comment by hikalkan** [comment]
Fixed this. You can try after v0.20 release.
