### ISSUE TITLE
abp/aspnetcore.mvc.ui.theme.leptonxlite version not found~2.0.0-preview20221014

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#14647]
Im getting below warning when ı execute abp install-libs with newly created abp mvc project.
Couldn't find any versions for "@abp/aspnetcore.mvc.ui.theme.leptonxlite" that matches "~2.0.0-preview20221014".
My abp cli version is '7.0.0-rc.1'.

**Comment by muhlisatac** [comment]
Now i can be able to change it to "@abp/aspnetcore.mvc.ui.theme.leptonxlite": "2.0.0-rc.1".

**Comment by muhlisatac** [comment]
Project templates still downloads like "@abp/aspnetcore.mvc.ui.theme.leptonxlite": "~2.0.0-preview20221014". I think this line should be changed to "@abp/aspnetcore.mvc.ui.theme.leptonxlite": "2.0.0-rc.1".

**Comment by maliming** [comment]
Yes, We will update the templates.
