### ISSUE TITLE
Is it possible to apply request reply pattern to administrion service on EshopOnAbp?

### ISSUE THREAD

**Issue by cangunaydin** [abpframework/abp#14652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

While i am looking at EshopOnAbp microservice solution, i have seen that as a design administration service (permission management) needs to call identity service (because it needs the user list or id not sure) through http. Because of that there is a need to add administration service as a client to auth-server. And this makes administration service coupled to identityservice. Also you need to add extra appsettings config and extra modules.

### Describe the solution you'd like

Is it possible to use Request/Reply Pattern from rabbitmq so this doesn't go through http but through the event bus. So we don't need to define administration service as a client and we can loosely couple it to identity service?
For ex: with masstransit you can easily apply this pattern or with dapr.

https://learn.microsoft.com/en-us/dotnet/architecture/cloud-native/service-to-service-communication#requestreply-pattern

### Additional context

Also can you please direct me when the permission-management module is requesting user(s)? Cause i couldn't find any http call through when i look at the source code of permission-management module. Obviously i am missing sth.

**Comment by cangunaydin** [comment]
Hello,
I think i have found the part that i am looking for.

```
[Dependency(TryRegister = true)]
public class HttpClientUserRoleFinder : IUserRoleFinder, ITransientDependency
{
    protected IIdentityUserAppService _userAppService { get; }

    public HttpClientUserRoleFinder(IIdentityUserAppService userAppService)
    {
        _userAppService = userAppService;
    }

    public virtual async Task<string[]> GetRolesAsync(Guid userId)
    {
        var output = await _userAppService.GetRolesAsync(userId);
        return output.Items.Select(r => r.Name).ToArray();
    }
}
```

here in GetRolesAsync, i think request reply pattern can be implemented. So it doesn't have to deal with authentication anymore or to depend on extra identityclient module.

**Comment by gterdem** [comment]
We have lots of improvements about separating the coupling between services for microservices. You can check https://github.com/abpframework/abp/pull/13644 for permission related changes
