### ISSUE TITLE
Blazor Server 7rc1

### ISSUE THREAD

**Issue by BogdanJak** [abpframework/abp#14668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

New Blazor Server project generated with version 7 preview.
Run abp install-libs command.
The app is launched and when I click on the Login button I get an error

![image](https://user-images.githubusercontent.com/54505464/201858465-39483dfd-55f6-4654-b2a0-6bd2228b2596.png)

### Version

7.0.0-rc.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
We will fix it: https://github.com/abpframework/abp/pull/14664

You can add them manually now

**Comment by BogdanJak** [comment]
How to do it? Sorry but I have no experience.

**Comment by muhlisatac** [comment]
You can add below 2 lines to package.json in web project and then run abp install-libs.
    "@abp/bootstrap-daterangepicker": "~7.0.0-rc.1",
    "@abp/moment":"~7.0.0-rc.1",
