### ISSUE TITLE
AbpRedisCache maybe should set `CommandFlags.DemandMaster` on every mutation operation to redis master-slave cluster

### ISSUE THREAD

**Issue by personball** [abpframework/abp#14667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

From two years ago,  in my team projects with Volo.Abp v3.1.2, we customize  `AbpRedisCache` to set `CommandFlags.DemandMaster` for master-slave redis cluster, as the default Impl in abp or Microsoft.Extensions.Caching.StackExchangeRedis not set it. It cause write fail when the operation send to a readonly slave node.

```
  var result = _cache.ScriptEvaluate(SetScript, new RedisKey[] { _instance + key },
                new RedisValue[]
                {
                        absoluteExpiration?.Ticks ?? NotPresent,
                        options.SlidingExpiration?.Ticks ?? NotPresent,
                        GetExpirationInSeconds(creationTime, absoluteExpiration, options) ?? NotPresent,
                        value
                }, CommandFlags.DemandMaster); // here
```

And, now I Checked Latest Code below:

https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Caching.StackExchangeRedis/Volo/Abp/Caching/StackExchangeRedis/AbpRedisCache.cs

Maybe there should has an option to control it.

### Describe the solution you'd like

An Configurable Property in `RedisCacheOptions`  to deal with it.

**Comment by realLiangshiwei** [comment]
After my check, this feature cannot be implemented.

let me explain:

We can't change the methods from Microsoft's [`RedisCache`](https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs). It will cause inconsistent behavior between methods, like `SetManyAsync` and `SetAsync`

**Comment by personball** [comment]
> After my check, this feature cannot be implemented.
> 
> let me explain:
> 
> We can't change the methods from Microsoft's [`RedisCache`](https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs). It will cause inconsistent behavior between methods, like `SetManyAsync` and `SetAsync`

tks for your reply. I'll track this https://github.com/dotnet/aspnetcore/issues/41948
