### ISSUE TITLE
Fore color in Blazor Server 7.0.0.rc-1

### ISSUE THREAD

**Issue by BogdanJak** [abpframework/abp#14682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Below is a photo of the form of adding a new user.
How to change the color of the letters so that they are visible?

![image](https://user-images.githubusercontent.com/54505464/201977539-93ed8b9e-3f91-4279-bd33-dd9187a0d46d.png)

### Version

7.0.0.rc-1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
Hi @BogdanJak, thanks for reporting. We are aware of this problem and will fix it soon.

**Comment by enisn** [comment]
Can you try updating LeptonX package to `2.0.0-rc.1` in your package.json and run `abp install-libs` command?

**Comment by enisn** [comment]
Sorry, my bad, please try to downgrade to `1.0.0`  only npm package until we fix it

**Comment by BogdanJak** [comment]
After changing LeptonX to version 1.0.0, I get an error with the content

`Autofac.Core.DependencyResolutionException: „An exception was thrown while activating Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionEndpointDataSourceFactory -> Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider -> λ:Microsoft.AspNetCore.Mvc.Abstractions.IActionDescriptorProvider[] -> Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider -> Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory -> λ:Microsoft.AspNetCore.Mvc.ApplicationModels.IApplicationModelProvider[] -> Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider -> Microsoft.Extensions.Options.UnnamedOptionsManager`1[[Microsoft.AspNetCore.Mvc.MvcOptions, Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] -> Microsoft.Extensions.Options.OptionsFactory`1[[Microsoft.AspNetCore.Mvc.MvcOptions, Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]] -> λ:Microsoft.Extensions.Options.IConfigureOptions`1[[Microsoft.AspNetCore.Mvc.MvcOptions, Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]][] -> Microsoft.Extensions.DependencyInjection.MvcDataAnnotationsMvcOptionsSetup -> Volo.Abp.Localization.AbpStringLocalizerFactory.”
`

**Comment by enisn** [comment]
No, I mean downgrade only **NPM** verisons in `package.json` file

**Comment by BogdanJak** [comment]
Changing the package version in package.json to 1.0.0 changes nothing. Below is the contents of my package.json

`{
  "version": "1.0.0",
  "name": "my-app",
  "private": true,
  "dependencies": {
    "@abp/aspnetcore.mvc.ui.theme.leptonxlite": "1.0.0",
    "@abp/aspnetcore.components.server.leptonxlitetheme": "1.0.0",
    "@abp/bootstrap-daterangepicker": "~7.0.0-rc.1",
    "@abp/moment": "~7.0.0-rc.1"
  }
}`
