### ISSUE TITLE
Blazor WASM - console error is received.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#14688]
**Problem:** Blazor wasm console error is received.

![image](https://user-images.githubusercontent.com/99716457/202103877-89f1d82d-9826-411e-b906-9d711de60190.png)
![image](https://user-images.githubusercontent.com/99716457/202116234-c7b14d1b-441c-47e5-a77f-6ad8048c4b78.png)

**Comment by realLiangshiwei** [comment]
I think you should run the `.HttpApi.HostWithIds` project first
