### ISSUE TITLE
ISoftDelete not working in a modular App

### ISSUE THREAD

**Issue by leaortiz** [abpframework/abp#14699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After deliting an Entity it is marked as IsDeleted = true on the database but when querying data I do get those entities.

### Reproduction Steps

Create a new ABP app (5.3.4) add a module to it using abp add-module YourModuleName –new –add-to-solution-file
    private void ConfigureConventionalControllers()
    {
        Configure<AbpAspNetCoreMvcOptions>(options =>
        {
            options.ConventionalControllers.Create(typeof(YourModuleName ).Assembly);
        });
    }

add an entity derived from FullAuditedEntity<Guid>  and an app services derived from CrudAppService

### Expected behavior

The deleted entity should't be retrived when querying

### Actual behavior

The entity is returned

### Known Workarounds

manually filter it using 
    using (_dataFilter.Disable<ISoftDelete>())
            {
                return ...
            }
            
**Adding: 
```

Configure<AbpDataFilterOptions>(options =>
{
    options.DefaultStates[typeof(ISoftDelete)] = new DataFilterState(isEnabled: true);
}); 

```
is not working**

### Version

5.3.4

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Can you share a simple project?
