### ISSUE TITLE
Deployment to containarized environment (k8s) with reverse-proxy - auth server issue

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#14704]
@gterdem as I can see, you are "k8s guy" and I have a problem how to properly deploy basic abp application (tiered, mvc - opensource or commercial) inside k8s environment and then expose to the internet (where there is reverse-proxy between k8s environment and internet).
https://stackoverflow.com/questions/74457621/openiddict-in-abp-framework-deploy-in-containerized-environment-k8s

I do not want to manually add additional code in c# middleware, but only configure appsettings.json files and k8s network, reverse proxy correctly.

It is important that is possible to achieve deploy abp project in such an environment by only configuring things properly and not changing/adding c# code to middleware.

I think that this should be documented as one of deployment methods.
What do you think? :)

**Comment by leonkosak** [comment]
Ok, I found this: https://docs.abp.io/en/commercial/latest/guides/identityserver-deployment
Is still relevant for OpenIddict?

**Comment by gterdem** [comment]
@leonkosak apart from configuration aspect, it is relevant for OpenIddict aswell but we're planning to create a new guide for OpenIddict deployment.

I have written a detailed answer for your question at [stackoverflow](https://stackoverflow.com/a/74473105/2594735). Let me know if you have any further questions.
