### ISSUE TITLE
ASP.NET Core MVC Tutorial - Part I UI mismatch

### ISSUE THREAD

**Issue by GerryGe** [abpframework/abp#1470]
I followed below doc:
https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I

and find one UI screenshot mismatch with my debug(both from my code and the abp github samples code)

Detail screenshot is 
From Doc:
![image](https://user-images.githubusercontent.com/6952917/61041588-2ab7ef80-a405-11e9-81f8-ceeb2347bc91.png)

From my debug:
![image](https://user-images.githubusercontent.com/6952917/61041738-6d79c780-a405-11e9-9a9c-2732cba41ba0.png)

I would like to know why occurred this mismatch and how can I to fix this problem.
Thanks.

**Comment by yekalkan** [comment]
Screenshot on document is old. You have done nothing wrong.

**Comment by vnetonline** [comment]
Check the table on the database how many records does it have ??

**Comment by GerryGe** [comment]
> Check the table on the database how many records does it have ??

There are more than 10 records, but the DefaultMaxResultCount (`LimitedResultRequestDto`)=10 and I haven't done paging, so my screenshot only show 10 records.

**Comment by GerryGe** [comment]
> Screenshot on document is old. You have done nothing wrong.

Thank you very much. Could you possible tell me where can I edit the DataTables css styles backward to your old screenshot.

**Comment by maliming** [comment]
@GerryGe Please refer to :https://datatables.net/examples/basic_init/dom.html

**Comment by GerryGe** [comment]
Add another mismatch screenshot in Part II
![image](https://user-images.githubusercontent.com/6952917/61115958-391a1000-a4c6-11e9-8c8c-7f4bdbbba8ac.png)
