### ISSUE TITLE
Use EF Core 7 ExecuteDelete for IRepository.DeleteAsync with predicate

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14716]
EF Core 7 has a new `ExecuteDeleteAsync` extension method: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#basic-executedelete-examples

We can use it in `EfCoreRepository.DeleteAsync` method:

````csharp
    Task DeleteAsync(
        [NotNull] Expression<Func<TEntity, bool>> predicate,
        bool autoSave = false,
        CancellationToken cancellationToken = default
    );
````

Here: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/EfCoreRepository.cs#L290-L305

This can be a breaking change for some applications (because it won't track the deleted entities in change tracker anymore).
 So, it would be better to implement it with ABP 7.0.

**Comment by maliming** [comment]
> because it won't track the deleted entities in change tracker anymore

This breaks the soft delete and auditing...

**Comment by hikalkan** [comment]
Hmmm.. OK, then it would be better to introduce a new method that explicitly explains it breaks these. I will create another issue.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/14725
