### ISSUE TITLE
Nightly packages lost : Volo.Abp.Account.HttpApi

### ISSUE THREAD

**Issue by Nongzhsh** [abpframework/abp#1471]
Hi, I am trying to use nightly builds, but when I restore the packages I got an error: Cannot find Volo.Abp.Account.HttpApi (0.19.0-preview20190711). I think it's missing. (●'◡'●)

**Comment by maliming** [comment]
It looks like we need to update [nupkg/common.ps1](https://github.com/abpframework/abp/blob/dev/nupkg/common.ps1)
