### ISSUE TITLE
custom account pages in development working (vsc launch),but on click application not working  

### ISSUE THREAD

**Issue by wxyer** [abpframework/abp#14712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

custom account pages in development working (vsc launch),but on click application not working 
![QQ截图20221117175241](https://user-images.githubusercontent.com/11608947/202414357-9d5fe4d7-65b7-4a76-b779-71594eec2800.png)
custom folder in *.HostApi.Host solution
i dont know the reason with much time elapsed,

### Expected behavior

page such as account/login can open with replaced content;

### Actual behavior

still with old page

### Version

5.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by wxyer** [comment]
![QQ截图20221117180844](https://user-images.githubusercontent.com/11608947/202418156-69c4fd15-420e-4cac-b5b4-e21f9dd7ca1c.png)
![QQ截图20221117180816](https://user-images.githubusercontent.com/11608947/202418162-c2918a05-7d4c-44ee-978d-d8c4e4b8b460.png)
task.json and launch.json

**Comment by wxyer** [comment]
i create a new razor page in accout folder,in production mode the pages not found but in development can found,who knoe the key is

**Comment by maliming** [comment]
You can try to disable `ConfigureVirtualFileSystem` method.

https://github.com/abpframework/abp/blob/30ec6d1129626cd01dad45e64ba44a8fdfe10f58/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.HostWithIds/MyProjectNameHttpApiHostModule.cs#L105

**Comment by wxyer** [comment]
> You can try to disable `ConfigureVirtualFileSystem` method.
> 
> https://github.com/abpframework/abp/blob/30ec6d1129626cd01dad45e64ba44a8fdfe10f58/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.HostWithIds/MyProjectNameHttpApiHostModule.cs#L105

i  have try this, still no working 
i print all the routes and found add the line below
`context.Services.AddControllersWithViews().AddRazorRuntimeCompilation();`
and copy to folder
` <None Include="Pages\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>`
