### ISSUE TITLE
Introduce DeleteDirectAsync method for IRepository

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14725]
EF Core 7 has a new `ExecuteDeleteAsync` extension method: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#basic-executedelete-examples

We can create a new method on the `IRepository<TEntity>` interface and implement it for EF Core and MongoDB.

````csharp
    Task DeleteDirectAsync(
        [NotNull] Expression<Func<TEntity, bool>> predicate,
        CancellationToken cancellationToken = default
    );
````

Add a summary on top of the method like:

>Deletes all entities those fit to the given predicate. It directly deletes entities from database, without fetching them. Some features (like soft-delete, multi-tenancy and audit logging) won't work, so use this method carefully when you need it. Use the `DeleteAsync` method if you need to these features.

Note that: For the ORMs doesn't support direct delete, we can fallback to the [existing DeleteAsync method](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Repositories/IRepository.cs#L66) (set `autoSave` to true if you fallback).

**Comment by rqx110** [comment]
what's difference between `HardDelete` and `DeleteDirect`?

**Comment by EngincanV** [comment]
> what's difference between `HardDelete` and `DeleteDirect`?

`DeleteDirect` doesn't involve the change tracker into the process by using the new `ExecuteDeleteAsync` method of EF 7.
