### ISSUE TITLE
Doc Menu Not Displaying correctly

### ISSUE THREAD

**Issue by MuratTopcu** [abpframework/abp#14729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm having the same problem #4185, is there a solution? 

![resim](https://user-images.githubusercontent.com/2551727/202666846-e699eeec-e297-4f07-9a20-ea6a0ede776c.png)

### Reproduction Steps

https://docs.abp.io/en/abp/latest/Apps/VoloDocs download https://apps.abp.io/VoloDocs/VoloDocs.win-x64.zip and install windows server 2022. 

Insert sample project to db
`INSERT [dbo].[DocsProjects] ([Id], [Name], [ShortName], [Format], [DefaultDocumentName], [NavigationDocumentName], [MinimumVersion], [DocumentStoreType], [ExtraProperties], [MainWebsiteUrl], [LatestVersionBranchName], [ParametersDocumentName]) VALUES (N'12f21123-e08e-4f15-bedb-ae0b2d939658', N'ABP framework (GitHub)', N'abp', N'md', N'Index', N'docs-nav.json', NULL, N'GitHub', N'{"GitHubRootUrl":"https://github.com/abpframework/abp/tree/{version}/docs","GitHubAccessToken":"***","GitHubUserAgent":""}', N'/', N'dev', N'')
`

### Version

6.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by ebicoglu** [comment]
also mentioned here https://support.abp.io/QA/Questions/6660/VoloDocs--Windows

**Comment by EngincanV** [comment]
Hi @MuratTopcu, thanks for reporting. Indeed, there are some styling problems on the Docs Module. I have created an issue to fix this problem, which you can follow at https://github.com/abpframework/abp/issues/19024.

**Comment by EngincanV** [comment]
VoloDocs download links are updated: https://docs.abp.io/en/abp/latest/Apps/VoloDocs#download

I am closing the issue, it should fix the problem. Please don't hesitate to reopen it, if it's not work for you.
