### ISSUE TITLE
SqlException: Invalid object name 'AbpSettings'.

### ISSUE THREAD

**Issue by bingzhizhi** [abpframework/abp#14730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to use defalut TablePrefix in some part of tables ,and other tables use another TablePrefix,
example: Table Users use "aaa" Table tenant use "bbb",
but 
Result: database table name changed as I want, but when I tried to run my site, i get error:

SqlException: Invalid object name 'AbpSettings'.
System.Data.SqlClient.SqlCommand+<>c.b__122_0(Task result)

SqlException: Invalid object name 'AbpSettings'.  what can i do

### Version

vnext

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

![image](https://user-images.githubusercontent.com/54054078/202671138-ebb1593d-8cd7-4248-8ded-de6f3ba852b9.png)

**Comment by bingzhizhi** [comment]
I just want to use defalut TablePrefix in users and tenants,what should i do

**Comment by bingzhizhi** [comment]
https://github.com/abpframework/abp/issues/1387#issuecomment-506645119    Can't help me

**Comment by maliming** [comment]
Reproduction Steps

**Comment by bingzhizhi** [comment]
1.change all TablePrefix except users and tenants in OnModelCreating
2.remove all migration 
3.add migration.Table AbpSettings has changed name to ShadowAbpsetting right now
4.Start project   ====>Invalid object name 'AbpSettings'.

**Comment by bingzhizhi** [comment]
I changed the tables name one by one in OnModelCreating

**Comment by maliming** [comment]
> 1.change all TablePrefix except users and tenants in OnModelCreating

Please change the prefix in the `Program` class.(`Host`, `Migrator`)

**Comment by bingzhizhi** [comment]
I want to use different prefix in database,if i change it in program it will be same.
I have changed ConfigureTenantManagement
![image](https://user-images.githubusercontent.com/54054078/202979351-1423c567-a6ae-4c77-9b1b-5ae67efb2147.png)

**Comment by bingzhizhi** [comment]
forexample I want to use diffrent AbpIdentityDbProperties.DbTablePrefix.what should i do

**Comment by bingzhizhi** [comment]
a part of tables use prefix 'a; ,the others use prefix 'B', In AbpIdentity Database

**Comment by maliming** [comment]
This belongs to EF Core instead of ABP.

**Comment by bingzhizhi** [comment]
![image](https://user-images.githubusercontent.com/54054078/202993760-1f5815cd-aa87-461c-a436-9b99a15edb00.png)
![image](https://user-images.githubusercontent.com/54054078/202993842-4d1039a1-63fe-45a7-a29e-ac68aea366e3.png)
![image](https://user-images.githubusercontent.com/54054078/202993999-9bac7e30-d1d2-43ff-9ed3-8b15f36f1ef6.png)
I changed the prefix in the Program class.(Host, Migrator)  Dosnt work
![image](https://user-images.githubusercontent.com/54054078/202994238-c3d7530c-d3a6-4ef0-afb9-92f97b4d91ac.png)

**Comment by bingzhizhi** [comment]
Finally ,The table name is ShadowSettings,but abp try to find the table AbpSettings,  sad

**Comment by bingzhizhi** [comment]
Is it possible to use a different prefix between table UserClaims and UserRoles?
I think its not possible because in abp they have the same prefix =====>AbpIdentityDbProperties.DbTablePrefix

**Comment by bingzhizhi** [comment]
abp sucks

**Comment by bingzhizhi** [comment]
How to change the name of user table 
I changed the table name to AbpUserNew and readd migration .but abp still try to find the table AbpUser

**Comment by bingzhizhi** [comment]
![image](https://user-images.githubusercontent.com/54054078/203505208-e1466b94-3045-42c9-aed1-628aca6d565e.png)
