### ISSUE TITLE
Login with GrantTypes.Password mode is ignoring tenant

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1474]
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.IdentityModel/Volo/Abp/IdentityModel/IdentityModelAuthenticationService.cs#L130

I made a account controller like this:
```
        [HttpPost("getAccessToken")]
        public async Task<IActionResult> GetAccessToken(UserLoginInfo login)
        {
            await ReplaceEmailToUsernameOfInputIfNeeds(login);

            var config = new IdentityClientConfiguration
            {
                Authority = _configuration["AuthServer:Authority"],
                ClientId = _configuration["AuthServer:ClientId"],
                ClientSecret = _configuration["AuthServer:ClientSecret"],
                GrantType = GrantType.ResourceOwnerPassword,
                UserName = login.UserNameOrEmailAddress,
                UserPassword = login.Password,
                Scope = "DentureMaster"
            };

            var token = await _authenticator.GetAccessTokenAsync(config);

            return Json(new { code = 1, data = token });
        }
```
And then I try to login as a tenant user, but it always returns:
invalid_username_or_password

Only host user can login.

Is there any way to solve it?

**Comment by hikalkan** [comment]
Identityserver has already an endpoint to get the access token. It support multi-tenancy (by the help of the code we've written). So, do you really need to do this manually?

**Comment by gdlcf88** [comment]
Hi @hikalkan 
Actually, I don't care what method to use, just hope to login as a tennat host(by a token), and I can use it in swagger and web app, could you please give me some more detailed tips?
