### ISSUE TITLE
 Blazor Webassembly appsettings.json

### ISSUE THREAD

**Issue by laiwang233** [abpframework/abp#14743]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/43662175/202953558-52738b0b-81d8-4317-860f-fb14163238fc.png)
![image](https://user-images.githubusercontent.com/43662175/202953604-a56f053c-74cf-40bd-b64c-c5a46cb4cee9.png)

### Reproduction Steps

Use abp new Dog -u blazor -dbms MySQL --theme basic generation 

### Version

6.0.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/14395
