### ISSUE TITLE
Localization of ABP modules (identity management, setting management, UI) not working after deployment to IIS

### ISSUE THREAD

**Issue by lukagalovic** [abpframework/abp#14753]
* Your **ABP Framework version**: 6.0.1
* Your **User Interface**: Angular
* Your database provider: EF Core

I have problem with custom localization of ABP modules. Everything is working fine on localhost but after I deploy to IIS, ABP modules are not localized, while modules I made are.

I did everything following tutorial on official ABP site but I can't find anyone had similar problem.

I am using ABP community edition.

Configuration: 

`            options.Resources
                .Add<LicGenResource>("en")
                .AddVirtualJson("/Localization/LicGen")
                .AddBaseTypes(typeof(AbpValidationResource));

            options.Resources
                .Get<AbpUiResource>()
                .AddVirtualJson("/Localization/AbpUi");

            options.Resources
                .Get<AbpUiNavigationResource>()
                .AddVirtualJson("/Localization/AbpUiNavigation");
                
            options.Resources
                .Get<AbpTenantManagementResource>()
                .AddVirtualJson("/Localization/TenantManagement");

            options.Resources
                .Get<IdentityResource>()
                .AddVirtualJson("/Localization/IdentityManagement");

            options.Resources
                .Get<AbpSettingManagementResource>()
                .AddVirtualJson("/Localization/SettingManagement");

            options.Resources
                .Get<AbpPermissionManagementResource>()
                .AddVirtualJson("/Localization/PermissionManagement");

            options.Resources
                .Get<AbpFeatureManagementResource>()
                .AddVirtualJson("/Localization/FeatureManagement");

            options.Resources
                .Get<AccountResource>()
                .AddVirtualJson("/Localization/Account");

            options.DefaultResourceType = typeof(LicGenResource);
`

I created localization files (e.g. IdentityManagement) under `*.Domain.Shared/Localization/IdentityManagement/` and I named files `en.json` and `hr.json`

**Comment by maliming** [comment]
What's `csproj` file content of `*.Domain.Shared` project?

**Comment by ipcheGevara** [comment]
`<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>LicGen</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <UserSecretsId>714db7e0-03a1-42d7-95de-4bed64cb592a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application.Contracts" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.Identity.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.OpenIddict.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.BackgroundJobs.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.AuditLogging.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.TenantManagement.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.SettingManagement.Domain.Shared" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\LicGen\*.json" />
    <Content Remove="Localization\LicGen\*.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Localization\LicGen\hr.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="7.0.0" />
    <PackageReference Include="Volo.Abp.UI" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.UI.Navigation" Version="6.0.1" />
  </ItemGroup>

</Project>
`

**Comment by ipcheGevara** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>LicGen</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <UserSecretsId>714db7e0-03a1-42d7-95de-4bed64cb592a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Application.Contracts" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.Identity.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.OpenIddict.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.BackgroundJobs.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.AuditLogging.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.TenantManagement.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Domain.Shared" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.SettingManagement.Domain.Shared" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\LicGen\*.json" />
    <Content Remove="Localization\LicGen\*.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Localization\LicGen\hr.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="7.0.0" />
    <PackageReference Include="Volo.Abp.UI" Version="6.0.1" />
    <PackageReference Include="Volo.Abp.UI.Navigation" Version="6.0.1" />
  </ItemGroup>

</Project>

**Comment by lukagalovic** [comment]
![csproj](https://user-images.githubusercontent.com/84729436/203029973-cdce8581-a13c-471d-88bd-f0fa07e0ea58.png)

**Comment by maliming** [comment]
hi

Try to include `Localization/IdentityManagement` as embedded resource.

**Comment by lukagalovic** [comment]
Working now, thank you very much!

![working](https://user-images.githubusercontent.com/84729436/203261120-cd0d5f18-744c-4320-a21c-3477d15eb8f3.png)
