### ISSUE TITLE
Using MapperConfiguration.ConstructServicesUsing may cause problems

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14766]
See the usage:

https://github.com/abpframework/abp/blob/e26d5ba0d3d6d32beb89bb609c03de5e2404070c/framework/src/Volo.Abp.AutoMapper/Volo/Abp/AutoMapper/AbpAutoMapperModule.cs#L47

Here, it seems we've used the global service provider. How these resolved services will be released? Also, I want to ask how AutoMapper uses that? Can we resolve services while mapping objects? If so, how? Is is documented?

Can you please check these and try to understand and explain it.

**Comment by maliming** [comment]
> How these resolved services will be released? 

These services will not be released. 

**This is a problem**, I'm checking [AutoMapper.Extensions.Microsoft.DependencyInjection](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection)

> How AutoMapper uses that? 

Automapper will create services in a static method, but not dispose of them.

> Can we resolve services while mapping objects? If so, how? Is is documented?

We can use inject services in `Before and After Map Action`, I will update the document after fixing this issue.

https://docs.automapper.org/en/stable/Before-and-after-map-actions.html#asp-net-core-and-automapper-extensions-microsoft-dependencyinjection
