### ISSUE TITLE
Cannot start Angular app (abp version: 6.0.1)

### ISSUE THREAD

**Issue by huytnd** [abpframework/abp#14768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Generating browser application bundles (phase: setup)... An unhandled exception occurred: ENOENT: no such file or directory, lstat 'D:\SrcRepos\Local\ABP_Templates\Angular\Angular01\angular\node_modules\@volo'

### Reproduction Steps

1. Create a new project using Angular as front-end with this command
`abp new Angular01 -u angular --separate-identity-server --theme basic`
2. Using `npm install` to install packages.
3. Using `npm start` to start up the web server. 

### Version

6.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

npm version: tried both 16.17.1 & 18.12.1
angular version: 14.2.1

**Comment by realLiangshiwei** [comment]
You can try use `yarn` to restore packages.

**Comment by kenan0122** [comment]
I also cannot start Angular app (abp version: 6.0.1)

**Comment by kenan0122** [comment]
> You can try use `yarn` to restore packages.
be not allowed

**Comment by huytnd** [comment]
I tried with a new Angular template tiered solution, and successfully run the angular app using `yarn` for restoring packages, then `npm start` for serving the app.
