### ISSUE TITLE
XHR requests sometimes hang when hosted under IIS

### ISSUE THREAD

**Issue by 4nonym0us** [abpframework/abp#1478]
**Application**: basic template (non-tiered, MVC app), downloaded from abp.io.
**DB**: MS SQL 2017 Express (hosted on the same server, tcp connection, MARS enabled)
**Web server**: IIS 10 with latest ASP.NET Core Hosting Bundle installed.
**OS**: Windows Server 2016 Standard, up-to-date, plenty of free CPU\RAM, no other roles\tasks except 'Web-Server' are added.

**Prerequisites**:
Change the connection string and run DbMigrator.

**Repro** (GIF: https://imgur.com/a/BmsPPEf):
1. Open any page, which makes ant XHR call (I tested on http://abp-test/Identity/Users).
2. Refresh the page (F5) couple of times (usually it takes from 2 to 10 retries to trigger the bug).
3. As you can see, occasional XHR request stays 'Pending' and is never finished succesfully. IIS will return HTTP 502 back to the client when timeout (default: 120 seconds) is exceeded.

After the bug occurred, you can refresh the page once more and everything will work fine without restarting the Application Pool or Web Site in IIS. Restarting the Pool\Site has no affect on the issue.

According to [logs.txt](https://github.com/abpframework/abp/files/3389054/logs.txt), in this particular case, request enters to `Volo.Abp.Identity.IdentityUserController.GetListAsync` and then never leaves it. At first I thought that GetListAsync is bugged, but it's not the case and the issue lies deeper (could be either UOW or Middleware, related to abp).

**Comment by maliming** [comment]
Thanks for the feedback. I will try to reproduce it.

**Comment by maliming** [comment]
Did not successfully reproduce your problem.

Can you try it directly using the net core process instead of iis express?

![image](https://user-images.githubusercontent.com/6908465/61197532-052e2d00-a708-11e9-8e2e-0a834943f56d.png)

**Comment by 4nonym0us** [comment]
I've tried to repro it locally (regural configuration in Windows and IIS Express) but couldn't do that as well. The issue occurs only when hosted under IIS 10 on my VPS. (I thought that I could be some IIS configuration issue, but I've double checked every option, made IISRESET, reinstalled ASPNET Core hosting bundle)
Are you aware of any other IIS-related issues or options, which could lead to such an bug?

**Comment by maliming** [comment]
You can look at IIS and other related logs on the VPS.

**Comment by 4nonym0us** [comment]
What "other related logs"? Apparently I have other web-sites running perfectly on the same server\IIS and application logs (which are attached above) say that request is never finished on ABP side. It's nothing to do with how IIS works in reverse-proxy mode.

**Comment by 4nonym0us** [comment]
After trying different hosting modes (InProcess\OutOfProcess) decided to run it via CLI and replicated the issue without using IIS at all (.NET\ASP.NET 2.2.6).

![image](https://user-images.githubusercontent.com/2701409/61204468-e9ba2680-a6f5-11e9-8012-d6d2a79a42d8.png)

```
C:\Users\Administrator>dotnet --info

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\Administrator>
```

**Comment by eismontt** [comment]
Hello, we have faced the same issue maybe @4nonym0us can tell how this issue was solved?

**Comment by 4nonym0us** [comment]
@eismontt 
First of all, there is actually no issues with ABP indeed and to there is a simple way to test it: create Windows Server VM on your computer or server (which is known to have a good performance). set up IIS, add ABP site to the pool, and ensure that there are no deadlocking issues.

I solved thee issue by changing my hosting provider. Some cheap VPS/VDS providers offer poor quality services which might affect apps in your IIS app pool. My old server had 8-core CPU and tons of RAM, but it was performing worse (aka. requests were hanging) then my current server, which currently has much less CPU-cores\RAM available (both servers were configured exactly the same, and they were running only IIS with a single ABP site in a pool).

If you want to find out if hosting provider is the issue, I'd suggest deploying blank ABP template and testing it. If the issue reoccurs, then you can be sure that hosting provider is terrible and you need to change it just like I did. If you are unable to reproduce the bug using blank ABP template, then you need to find out what is causing deadlocking or thread pool starvation in your code.
