### ISSUE TITLE
All Templates - Only button is displayed for "feature management" 

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#14780]
**Version:** `7.0.0-rc.2`
**App:** Mvc - Blazor Server - Blazor WASM - Angular
**Problem:** Only button is displayed for "feature management" . It might look better if there is a description when the tab is opened

**Note:** The same problem exists in pro templates.

![image](https://user-images.githubusercontent.com/99716457/203307384-c2e95a5a-c41d-430b-ae7f-0279ed80c616.png)

**Comment by gizemmutukurt** [comment]
Fixed issue for Blazor and mvc projects. Continue for Angular.

**Comment by ebicoglu** [comment]
In this case we can write a description as below
![image](https://user-images.githubusercontent.com/9526587/205989839-d398d42e-30f1-429f-8742-5eeabfc4e40d.png)
