### ISSUE TITLE
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'!

### ISSUE THREAD

**Issue by YangYang1082** [abpframework/abp#14784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i have got the AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'! when i visited the authserver.
and it is also exist after i run ABP install-libs command.

### Reproduction Steps

1. use  `abp new tutorial -u blazor -dbms PostgreSQL --separate-identity-server --theme basic --pwa ` command generate the project. (abp cli version is 6.0.1).
2. run `abp install-libs` command in project folder.
3. start project and got the exception descripted above.

### Version

6.0

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> run abp install-libs command in project folder.

What's the output of this command?

**Comment by YangYang1082** [comment]
> 

![image](https://user-images.githubusercontent.com/95226197/203451902-49d18b14-eac3-4d6a-932f-5c1443f0169a.png)

above is the output of abp install-libs command

**Comment by maliming** [comment]
> Some peer dependencies are incorrectly met; run yarn explain peer-requirements<hash> for details， where <hash> is the six-letter p-prefixed code

**Comment by YangYang1082** [comment]
> > Some peer dependencies are incorrectly met; run yarn explain peer-requirements for details， where  is the six-letter p-prefixed code

![image](https://user-images.githubusercontent.com/95226197/203454844-1514a8c9-4499-40e8-abcc-436bb0008719.png)

this is the output of `yarn explain peer-requirements` command, i also have searched for this, iseems like it will not stop my code from running, and how can i solve this problem?

**Comment by maliming** [comment]
This seems like a `Yarn` issue, I have no ideas.

**Comment by YangYang1082** [comment]
> This seems like a `Yarn` issue, I have no ideas.

i have solved this problem after downgrade my yarn from 3.2.4 to 1.22.19
