### ISSUE TITLE
Show warning instead of crashing the application when a bundle script/style file not found

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14795]
We should think about the implementation details.
One way can be writing error logs to browser console and application logs, and allow the application to continue running correctly.

**Comment by ebicoglu** [comment]
if there's a bundle problem, we can also show it in the Health Check endpoint.

**Comment by hikalkan** [comment]
@ebicoglu healtcheck is another story. If we want to do it in framework level (in the bundling package) we would need to have a healtcheck abstraction which is not currently available.
