### ISSUE TITLE
Throwing UserFriendlyException in Razor page not auto handled.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#1480]
I throw an UserFriendlyException in `OnGet()` method of my PageModel like this:

``` csharp
        public async Task<IActionResult> OnGet()
        {
            throw new UserFriendlyException("Error!")
        }
```

I expected abp would show a sweetalert dialog, but it just showed a exception page with stacktrace.

So how should I do that like the ASPNETBOILERPLATE did before?

**Comment by hikalkan** [comment]
Action results are not handled by ABP. It should be done with the [UseErrorPage](https://github.com/abpframework/abp/blob/dev/templates/mvc/src/MyCompanyName.MyProjectName.Web/MyProjectNameWebModule.cs#L192) middleware.
If you are using the startup template, it uses UseDeveloperExceptionPage in the development environment which shows stacktrace.

Also, it is not easy to show a sweetalert unless you make an AJAX request.

**Comment by wakuflair** [comment]
@hikalkan I noticed there's a [Alerts](https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.AspNetCore.Mvc.UI/Volo/Abp/AspNetCore/Mvc/UI/RazorPages/AbpPageModel.cs#L46) property in the AbpPageModel. Maybe I could use it to show error message? But I didn't find documents about it.

**Comment by hikalkan** [comment]
>Maybe I could use it to show error message?

Definitely, yes. It is for that purpose.

See https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L112 for a usage.

Instead of throwing exceptions, use Alerts to show alerts on UI.

Also, you can use Try/Catch and write an alert in the cache if the exception is thrown by a code inside a service you're using.

**Comment by wakuflair** [comment]
Thanks @hikalkan! It works as I expected.

**Comment by wakuflair** [comment]
Thanks @hikalkan! It works as I expected.
