### ISSUE TITLE
openiddict connect/token got token,but is not valid

### ISSUE THREAD

**Issue by zyknow** [abpframework/abp#14809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i create new abp template project,got token form `/connect/token`
![image](https://user-images.githubusercontent.com/49929368/203730343-8d82b543-7d31-4b1c-92ba-f280a50c5cb1.png)

when i use this token request other api,the response is 401
![image](https://user-images.githubusercontent.com/49929368/203730843-265d2940-0248-422e-969a-9face76dfe35.png)

### Version

6.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Add **scope** to request.

![image](https://user-images.githubusercontent.com/6908465/203734164-a331a040-2d83-4087-8bd4-b139c437e1b2.png)

**Comment by zyknow** [comment]
> Add **scope** to request.
> 
> ![image](https://user-images.githubusercontent.com/6908465/203734164-a331a040-2d83-4087-8bd4-b139c437e1b2.png)

i create same now project,and set the scope,and i got the token ,but it's same error

![image](https://user-images.githubusercontent.com/49929368/203745354-5b1aa3c7-c176-49cc-8b88-5ebb6b5b0daa.png)
![image](https://user-images.githubusercontent.com/49929368/203745444-28f5155b-a47d-4587-a30c-f5fc2f1469ac.png)

**Comment by maliming** [comment]
We have a test project. 
https://github.com/abpframework/abp/blob/dev/modules/openiddict/app/OpenIddict.Demo.Client.Console/Program.cs#L130

**Comment by zyknow** [comment]
ok,this problem is i generate token by localhost,but i request on 127.0.0.1


i same test on the cli 7 rc2 and same request, it;'s success


cli rc2 template allow localhost generate token ,to request 127.0.0.1, but 6.0.1 can not

i think rc2 it's optimize openiddict ?

**Comment by maliming** [comment]
You can check the changes from openiddict 4.0 rc

https://github.com/openiddict/openiddict-core/releases
