### ISSUE TITLE
Update vulnerable packages to the latest version.

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#14811]
Update vulnerable packages to the latest version. Check if there's a breaking change and test the UI after updating.

Eg:
lodash — https://github.com/abpframework/abp/blob/dev/npm/packs/lodash/package.json
jquery-form — https://github.com/abpframework/abp/blob/dev/npm/packs/jquery-form/package.json

![image](https://user-images.githubusercontent.com/9526587/203736319-68b5879a-0221-47f0-9fc5-e2443dc74a28.png)
![image](https://user-images.githubusercontent.com/9526587/203736696-1909a427-1e49-41f8-8dae-104113b9b1d6.png)

---

reported at https://support.abp.io/QA/Questions/4070

**Comment by realLiangshiwei** [comment]
- [x] lodash
- [x] jquery-form
- [x] ansi-regex
- [x] chart.js
- [x] system.security.cryptography.xml
