### ISSUE TITLE
asp.net zero or abp.io

### ISSUE THREAD

**Issue by mdissel** [abpframework/abp#1481]
We are investigating the apb framework features for a new project (asp.net core). Is the advice (at this moment) to use the mature asp.net zero framework or the new abp.io framework? Is there a feature overview between the two frameworks?

**Comment by maliming** [comment]
See https://blog.abp.io/abp/Abp-vNext-Announcement

**Comment by mdissel** [comment]
Yes, i've read the blog post (a long time ago), but it's 9 month old, is the advice still to use the mature asp.net zero framework?

**Comment by maliming** [comment]
I recommend you to use Zero.

**Comment by cxs-mahendra** [comment]
I am already using ASPNetBoilerplate and am very excited to know the release of abp.io.
I am looking for a sample code to develop plug-in module using abp.io. 
Basically the requirment is something below.
1. There is a multi-tenant application developed using abp.io
2. A tenant subscribe to our application and running their business happily.
3. Now the tenant wanted to make some business logical changes to the existing screen and also wanted to add a new screen.
4. I am sure this can be achieved using extensibility feature that abp.io provides.
5. Can you direct me to a link where I can find some help on how to modify/extend existing application.

**Comment by ismcagdas** [comment]
@cxs-mahendra would you like to make changes on specific pages or would you like to create a new module ?

**Comment by KevinFarrow** [comment]
Similar to this question https://github.com/abpframework/abp/issues/2006

**Comment by cxs-mahendra** [comment]
> @cxs-mahendra would you like to make changes on specific pages or would you like to create a new module ?

Actually Both....

**Comment by bobingham** [comment]
@cxs-mahendra , use Zero.  It's great and you can change things, it's not monolithic like _abp.io_.

**Comment by cxs-mahendra** [comment]
Thanks for your recommendation. 
I know new modules can be added using IPlugInSource interface.
But how can I change the business logic of existing module. 
Let's say there is a button in a form on my main application. 
How can I write my custom code on button click event.
The code execution of button click could be 
My Custom Code Execution (i.e. Before Event)
My main application click code execution
My Customer Code Execution (i.e. After Event)

**Comment by ismcagdas** [comment]
@cxs-mahendra both ABP.IO and AspNet Boilerplate doesn't provide any built in feature for that. So, you have to implement it yourself.

**Comment by cxs-mahendra** [comment]
Hi,

I am referring to the following link : https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1476#issuecomment-277330004

I downloaded the project from GitHub, Compile and rum, it runs successfully..

Now I am trying to run  this as a plugin. 
So in the main application I did something like below: I removed the dependency of TodoModuleWebModule

    [DependsOn(typeof(ModularTodoAppWebCoreModule))]
    public class ModularTodoAppWebMvcModule : AbpModule
    {
      ......
      .......

And in the Startup.cs file, I did the following:
            services.AddAbp<ModularTodoAppWebMvcModule>(options =>
            {
                options.PlugInSources.AddFolder(@"C:\MyPlugIns");
            });

And in the folder C:\MyPlugIns, I put in all the compiled dll of ToDo Module.

When i tried to run this application now, it throws me the attached error.
Could you please help me what is wrong that I am doing.



[Error.docx](https://github.com/abpframework/abp/files/3812759/Error.docx)

**Comment by cxs-mahendra** [comment]
can anyone please help me resolving issue in my above post.
Many thanks

**Comment by maliming** [comment]
hi @cxs-mahendra 
Can you create a new issue here? https://github.com/aspnetboilerplate/aspnetboilerplate/issues/new
If possible, please provide the code or project to reproduce the problem, thank you
