### ISSUE TITLE
abp Commercial - microservice template and other databases (Postgres)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#14814]
I can't open a new topic on support.abp.io.

Based on:
https://docs.abp.io/en/commercial/latest/startup-templates/microservice/infrastructure
and
https://docs.abp.io/en/commercial/latest/startup-templates/microservice/database-migrations

Is somehow possible to change EF Core provider for microservice-pro template to Postgres (or other SQL engines)?
I can't find EntityFrameworkCore projects where would replace .UseSqlServer with .UseNpgsql.

The best solution would be something similar to this:https://blog.jetbrains.com/dotnet/2022/08/24/entity-framework-core-and-multiple-database-providers/

But in abp documentation is only "Running SQL-Server infrastructural service is required...".

**Comment by maliming** [comment]
We use `UseNpgsql` in the eShopOnAbp microservice project.

https://github.com/abpframework/eShopOnAbp/search?q=UseNpgsql

**Comment by leonkosak** [comment]
Thank you @maliming, but what for microservice-pro template?
Searching for "UseNpgsql" or "UseSqlServer" in Visual Studio results in 0 matches.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/204739335-0ed2d617-8b9f-474d-873e-bf347ea7983d.png)

**Comment by leonkosak** [comment]
That's strange.
Are these lines of code in microservice-**pro** template inside dll library files?

**Comment by maliming** [comment]
What's content of `AdministrationServiceEntityFrameworkCoreModule`?

**Comment by leonkosak** [comment]
I realized that .EntityFrameworkCore projects are not loaded in microservice .sln and are only present on filesystem.
My mistake. :)
@maliming, would "template" for supporting multiple database migrations (for EF Core only of course) via parameter [described in this article](https://blog.jetbrains.com/dotnet/2022/08/24/entity-framework-core-and-multiple-database-providers/) be beneficial for abp microservice template?

**Comment by maliming** [comment]
Yes, I think you can switch the EF Core provider in abp.
