### ISSUE TITLE
Cannot find a way to change color of select fields and remove breadcrumb from top bar in LeptonX Lite theme

### ISSUE THREAD

**Issue by lukagalovic** [abpframework/abp#14825]
ABP Framework version: 6.0.1 Community
UI: Angular
DbProvider: Ef Core

Is there any way to change pink color on select fields on first image below and remove breadcrumb from top bar on second image?
I tried changing  `--lpx-brand` but it does not change select fields nor checkboxes.

![SelectColor](https://user-images.githubusercontent.com/84729436/203939065-c44ea093-72ef-4c61-884a-5e5cf3ef3f57.png)

![BreadCrumb](https://user-images.githubusercontent.com/84729436/203939107-750e23a0-e14b-4ad8-a5fc-a33d28207864.png)

**Comment by fatihskilic** [comment]
1. You can replace breadcrumb with your new component. 

```ts
import { ReplaceableComponentsService } from '@abp/ng.core';
import { eThemeLeptonXComponents } from '@abp/ng.theme.lepton-x';

export const APP_BREADCRUMB_PROVIDER = [
  {
    provide: APP_INITIALIZER,
    useFactory: switchBreadCrumb,
    multi: true,
    deps: [ReplaceableComponentsService],
  },
];
export function switchBreadCrumb(replaceableComponents: ReplaceableComponentsService) {
  return () => {
   
    replaceableComponents.add({
      component: YourComponent,
      key: eThemeLeptonXComponents.Breadcrumb,
    });
  };
}  
````

Declare APP_BREADCRUMB_PROVIDER  provider Array in Module. 

2. Using style.scss you can assign a new color to the class giving the color code.

**Comment by lukagalovic** [comment]
Thank you very much, I managed to solve it.
