### ISSUE TITLE
Disable MultiTenant of Role entity

### ISSUE THREAD

**Issue by hubo0831** [abpframework/abp#1482]
I use multitenant of user,but i don't use multitenant of role, can i disable multitenant of role?
I hope have a options to disable multitenant of some entity?

**Comment by hikalkan** [comment]
I haven't thought that before. It may be done with some workarounds but haven't created a system for this case.

Normally, multi-tenancy should be used as a whole and you should completely separate data of two tenants. Think "database per tenant" scenario. Where this "shared" roles should be located? In the host db or a shared db? How to maintain foreign key relations in this case? So, it is hard to write a solution without trying it and see the problems.

**Comment by hubo0831** [comment]
My system is small, only use one shared db, so multitenant of role entity is a problem.

**Comment by hikalkan** [comment]
Yes, but it can be a problem for others. So, we can not add such a feature without thinking all use cases.

**Comment by hubo0831** [comment]
In "database per tenant" scenario, data filter of multitenant is redundant.
