### ISSUE TITLE
Hope can control transaction of uow

### ISSUE THREAD

**Issue by hubo0831** [abpframework/abp#1483]
transaction of uow is auto begin, hope can IUnitOfWork add BeginTransaction method,can support distributed transaction

**Comment by fangqifan** [comment]
Maybe you can use`[UnitOfWork(IsDisabled=true)]`,then manual begin transaction like this:

        [UnitOfWork(IsDisabled=true)]
        public async Task AnyMethod()
        {
            //do something

            //set options your need
            var options = new UnitOfWorkOptions();

            using (var uow = unitOfWorkManager.Begin(options))
            {
                //do something
                await uow.CompleteAsync();
            }
        }

the `unitOfWorkManager` is comes from dependency injection
