### ISSUE TITLE
IObjectMapper should support adding parameters (Dictionary<string, object>) like AutoMapper

### ISSUE THREAD

**Issue by ahmednfwela** [abpframework/abp#14834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

with AutoMapper `IMapper` you can add elements to an `Items` dictionary in the options, e.g.:
```cs
_mapper.Map<Entity, EntityDto>(entity, options =>
{
    //pass any parameters to `options.Items`
    options.Items["MyItems"] = new Dictionary<Guid, OtherEntity>(); 
    options.Items["CurrentUser"] = currentUser; 
});
```

### Describe the solution you'd like

IObjectMapper should add an extra parameter `Items` to the `Map` methods, or even better, add a new `IObjectMapperOptions<TSource,TDestination>` interface which can be used like this:
```cs
TDestination Map<TSource, TDestination>(TSource source, Action<IObjectMapperOptions<TSource,TDestination>> options);
```
similar to AutoMapper

### Additional context

Current workaround is to use `IMapperAccessor` to get the `IMapper` instance directly

**Comment by maliming** [comment]
I think this is not a common case.

**Comment by ahmednfwela** [comment]
> I think this is not a common case.

It isn't because most developers call ObjectMapper.Map to get most of the properties, and then manually assign the missing ones.

but I like to have all my mappings in one place

**Comment by ahmednfwela** [comment]
if there is an agreement on this I can make a PR to address it
