### ISSUE TITLE
In blazor webassembly mode, localization does not take effect, such as Cancel, Save, Actions, Edit

### ISSUE THREAD

**Issue by wangj90** [abpframework/abp#14832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In blazor webassembly mode, localization does not take effect, such as Cancel, Save, Actions, Edit

### Version

7.0.0-rc.2

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Can't reproduce.
![image](https://user-images.githubusercontent.com/16813853/204114973-4e7da9a0-c4ff-4340-a796-382e8b774e87.png)
![image](https://user-images.githubusercontent.com/16813853/204114980-12b904e4-34bb-4893-bd0e-aba0bd7fe34b.png)

**Comment by wangj90** [comment]
such as
![image](https://user-images.githubusercontent.com/25636510/204116060-6c930e40-177e-47dc-a93d-556528afa1fe.png)
![image](https://user-images.githubusercontent.com/25636510/204116068-57937ab8-1d82-4472-b280-3cfd1a340d5e.png)
![image](https://user-images.githubusercontent.com/25636510/204116140-c05338dd-8724-423a-b933-05042aa1bc01.png)
![image](https://user-images.githubusercontent.com/25636510/204116078-4071739b-91f0-48c3-847c-777b9a58bd7e.png)

**Comment by realLiangshiwei** [comment]
I will check it
