### ISSUE TITLE
Upgrade to Blazorise 1.1.4

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#14833]
> This new Blazorise 1.1.4 is a hotfix release to solve this and a few other minor issues that were fixed in the meantime. Blazorise 1.1.4 is a recommended upgrade for all Blazorise 1.1 and Blazorise 1.1.3 users.

https://blazorise.com/news/release-notes/114

**Comment by sturlath** [comment]
@realLiangshiwei https://blazorise.com/news/release-notes/115 

> This release fixes some nasty bugs, particularly with the NumericPicker and Drag and Drop components.
