### ISSUE TITLE
The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot

### ISSUE THREAD

**Issue by xiazx** [abpframework/abp#14846]
![image](https://user-images.githubusercontent.com/14884620/204220833-a0562f84-1c6f-4b4b-8015-eae3ca228952.png)
![image](https://user-images.githubusercontent.com/14884620/204221018-472a6032-d71f-4dec-8d81-03fe0b253abf.png)

How can I solve the development environment certificate problem? Is there any relevant setting document?

**Comment by maliming** [comment]
`dotnet  dev-certs https -t`

**Comment by xiazx** [comment]
The answer has been found：https://blog.csdn.net/GongMeiyan/article/details/104030780
