### ISSUE TITLE
Windows virus & threat protection detects Volo.Abp.Specifications.dll 

### ISSUE THREAD

**Issue by shnoru1** [abpframework/abp#14848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, 
since the last update of the Windows 10 defender (up to version 1.379.1077.0), I've figured out that "Virus & threat protection" detected `Volo.Abp.Specifications.dll` and immediately removed it.

Current version of the abp that I'm using was 5.2.0.

It seems like Windows' problem, not ABP, but I'm reporting the case just in case and hopefully looking for the solution.

### Reproduction Steps

1. Update windows defender (to version 1.379.1077.0)
2. Download or install `Volo.Abp.Specifications.dll`

### Expected behavior

Installation finished normally.

### Actual behavior

`Volo.Abp.Specifications.dll` is removed.

### Version

5.2.0

### User Interface

Common (Default)

### Database Provider

None/Others

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
Thanks for the report. I did a little research, but it doesn't seem to be related to ABP as you said. So I'll close this topic, but if anyone else in the community has the same problem, please report it here so we can investigate further.
