### ISSUE TITLE
Where is the initial data seed method which populates the data tables with data 

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1485]

**Comment by maliming** [comment]
Implement the IDataSeedContributor interface, which will be automatically scanned by the AbpDataModule. These components will then be called by IDataSeeder.

**Comment by vnetonline** [comment]
@maliming i am trying to look for the code which adds admin and password for the same when the initial seed is run

**Comment by maliming** [comment]
`modules\identity\src\Volo.Abp.Identity.Domain\Volo\Abp\Identity\IdentityDataSeedContributor.cs`

![image](https://user-images.githubusercontent.com/6908465/61198714-cb602500-a70d-11e9-8353-f674fa61ac52.png)

**Comment by vnetonline** [comment]
thanks @maliming 

can you explain why the DbMigrator is a dll and not exe? 

how do i run this from the command line need to demonstrate it in the video I am creating

**Comment by maliming** [comment]
See: https://stackoverflow.com/questions/44074121/build-net-core-console-application-to-output-an-exe?answertab=active#tab-top
