### ISSUE TITLE
I am getting the following error when I try the MVC tiered template

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1488]
I have created a MVC Tiered template using the ABP CLI 0.18.1.0 I am getting the following error when I run the .Web Project 

The host project and the Http.Api project are running I only get the below error once I click on Login button which is not styled in the blue bootstrap theme the page

<img width="841" alt="Screen Shot 2019-07-16 at 4 07 50 pm" src="https://user-images.githubusercontent.com/15242923/61270104-fa48ca80-a7e3-11e9-8248-5361901e8761.png">

<img width="1650" alt="Screen Shot 2019-07-16 at 4 01 28 pm" src="https://user-images.githubusercontent.com/15242923/61269962-89091780-a7e3-11e9-8e47-a30f29c3bde4.png">

**Comment by hikalkan** [comment]
Let us try this again.

**Comment by maliming** [comment]
@vnetonline 
Has the problem been solved?
Did you start the .IdentityServer in order, then the .HttpApi.Host project, and finally the .Web project?

**Comment by yekalkan** [comment]
Updating the database fixed this for me. (Or re-creating)

If this doesn't work for you, you can re-open the issue.
