### ISSUE TITLE
HangfireBackgroundWorkerBase base properties(Logger, ServiceProvider ...) is null and interceptions not work

### ISSUE THREAD

**Issue by ahmetfarukulu** [abpframework/abp#14893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i create a background worker inherited by HangfireBackgroundWorkerBase all base properties is null and UnitOfWork and other interceptions not working

### Reproduction Steps

- I made a simple background worker same as [docs](https://docs.abp.io/en/abp/latest/Background-Workers-Hangfire) 
- Register OnApplicationInitializationAsync `await context.AddBackgroundWorkerAsync<IMyLogWorker>();`

![image](https://user-images.githubusercontent.com/35758317/204884028-f70869d8-3e1d-49b7-8a4f-0374513380ad.png)

### Expected behavior

- Base properties shouldn't null
- UnitOfWork interception should work(UnitOfWorkManager.Current property shouldn't null)

### Actual behavior

- Interceptions not working and base properties is null

### Version

7.0.0-rc.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

When background worker [added](https://github.com/abpframework/abp/blob/0464dfe7eda36b811a7d8e1946df0970edff7d69/framework/src/Volo.Abp.BackgroundWorkers.Hangfire/Volo/Abp/BackgroundWorkers/Hangfire/HangfireBackgroundWorkerManager.cs#L37) it's saving concrete class on Hangfire.Hash table 

![image](https://user-images.githubusercontent.com/35758317/204892725-32c25b4d-5708-4d06-abf9-cd35365498f9.png)

**Comment by rqx110** [comment]
see https://github.com/abpframework/abp/issues/12339#issuecomment-1108341705
and the document **need to update**

**Comment by ahmetfarukulu** [comment]
⚠️**Interception not work** (When you use interception it's causes [runtime error](https://github.com/abpframework/abp/issues/12339#issuecomment-1125789206))

In this case we don't need IMyLogWorker interface anymore cause we create for interception but interception doesn't work. We can simply use
```csharp
public class MyLogWorker : HangfireBackgroundWorkerBase 
{
    public MyLogWorker()
    {
        RecurringJobId = nameof(MyLogWorker);
        CronExpression = Cron.Daily();
    }

    public override Task DoWorkAsync(CancellationToken cancellationToken = default)
    {
        Logger.LogInformation("Executed MyLogWorker..!");
        return Task.CompletedTask;
    }
}
