### ISSUE TITLE
New document: Optimization notes for production deployment

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#14891]
* Configuring for CDN (localzation endpoint, bundles, static files, etc.)
* Bundling & Minification
* ...more?

**Comment by gdlcf88** [comment]
Create and register certificates for OpenIddict:

https://github.com/abpframework/abp/blob/08034310b15e9056c019403f500a507e2b4efbdd/modules/openiddict/app/OpenIddict.Demo.Server/OpenIddictServerModule.cs#L91-L108

https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html#registering-a-certificate-recommended-for-production-ready-scenarios

**Comment by leonkosak** [comment]
@hikalkan would this documentation cover also specifics for production deployment inside container environment (Docker, k8s)?

**Comment by hikalkan** [comment]
done by https://github.com/abpframework/abp/pull/14903

**Comment by hikalkan** [comment]
>would this documentation cover also specifics for production deployment inside container environment (Docker, k8s)?

No, not currently. These notes are for the framework. K8s configuration is different for each startup template (and for each combination of UI and DB selections, and also for your customizations after creating your solution). We've created some community articles for some use cases and will continue to write more in the future.
