### ISSUE TITLE
AbpException: Could not find the bundle file '/libs/bootstrap-daterangepicker/daterangepicker.css' for the bundle 'Basic.Global'!

### ISSUE THREAD

**Issue by choby** [abpframework/abp#14907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I upgraded my application from abp6.0 to abp7.0 -rc2, and abp install-libs is executed, abp install-libs is executed

![image](https://user-images.githubusercontent.com/13461239/205032018-1805b343-7a9a-4131-b5aa-d08af8f5e6b3.png)

### Version

7.0-rc2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
Hi, the problem will be solved with `rc-3`, but as a workaround, when you extract the attached zip files and put the inside folder in the `wwwroot/libs` folder of your application, it should work if there are no other missing packages.


[bootstrap-daterangepicker.zip](https://github.com/abpframework/abp/files/10138734/bootstrap-daterangepicker.zip)
[moment.zip](https://github.com/abpframework/abp/files/10138864/moment.zip)

**Comment by zaktecs** [comment]
Hi @berkansasmaz I think still exist in 7.0.0-rc.4 , I've installed 7.0.0-rc.4 and run into the same issue

AbpException: Could not find the bundle file '/libs/bootstrap-daterangepicker/daterangepicker.css' for the bundle 'Basic.Global'!.

I will use your workaround to resolve it.

Thanks

**Comment by LuisPignataro** [comment]
Hi @berkansasmaz, Still exists in 7.0.1 release? Same problem after upgrade to 7.0.1

Abp cli set to "@abp/aspnetcore.mvc.ui.theme.basic": "~7.0.1",

**Comment by xorinzor** [comment]
@berkansasmaz  any updates on this? Still happening on 7.0.3 with `"@abp/aspnetcore.mvc.ui.theme.leptonxlite": "~2.0.4"` too.

The package does show in my `package-lock.json` and it's also showing in `node_modules` however it only contains a js file. No css files are present in `node_modules/@abp/bootstrap-daterangepicker`.  I believe this to be the main reason the bundle throws this error.

**Comment by berkansasmaz** [comment]
Oops! I've overlooked the activity here for a long time. Sorry about that.

I created a new project with `v7.0.3` and tested it, but I couldn't see a problem.

In your case the problem might be that you didn't delete the `node_modules`.

1. `yarn cache clean`
2. `rm -rf node_modules`
3. `abp install-libs`
4. Check the folder: `**/node_modules/@abp/bootstrap-daterangepicker`

**Comment by xorinzor** [comment]
Thanks, that worked!

In my case I upgraded from 6.x to 7.x, so perhaps it might be worth mentioning these steps in the upgrade guide for anyone else who could possibly run into this problem.

**Comment by GregoryFr74** [comment]
I had the same pb after migrating
Libs were missing in HttpApi.Host\wwwroot\libs
And Yarn.lock still referencing the libs in 6.*
I copy libs and yarn.start from a scratch project. everything works

**Comment by JOIN1277** [comment]
niu X
