### ISSUE TITLE
EntityCreatingEventData过时后的统一数据验证

### ISSUE THREAD

**Issue by ygr757326** [abpframework/abp#14904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

EntityCreatingEventData 已过时，现在我应如何在实体创建中 统一进行数据验证

### Version

6.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
Hello, is it possible for you to ask your question in English and in a little more detail?

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
