### ISSUE TITLE
Dapr Actor Integration with ABP v7

### ISSUE THREAD

**Issue by abineshamatya** [abpframework/abp#14908]
Are there any documents related to Dapr Actor using ABP v7? 

If we want to use the Dapr Actor feature, do we need to install the **Dapr.Actors** package from the **Dapr** separately or can we use it with the **Volvo.Abp.Dapr** package? I couldn't find one when I looked at the new Dapr integration document for Abp v7.0. 

What is the right way to proceed? If you could point me in the right direction, I would appreciate your assistance.

**Comment by maliming** [comment]
hi

There is no `Dapr Actor` feature in 7.0

**Comment by abineshamatya** [comment]
Hi @maliming,

Thanks for the prompt response. 

Is there any plan regarding the Dapr Actor release?

**Comment by gdlcf88** [comment]
I think it is nothing to do with the ABP framework. You can use the Dapr Actor yourself. FYI https://github.com/EasyAbp/EShop/tree/dev/plugins/Inventories/DaprActors.

**Comment by abineshamatya** [comment]
Thank you for your response. I'll give it a try.
