### ISSUE TITLE
OnPostApplicationInitializationAsync is not executed during initialization

### ISSUE THREAD

**Issue by feigaogit** [abpframework/abp#14912]
abp 5.1.3

![image](https://user-images.githubusercontent.com/18181270/205222965-9a9693ba-98ce-4d65-ae2e-639b2a09785f.png)

OnPostApplicationInitialization is not executed during initialization

but

OnPostApplicationInitializationAsync is not executed during initialization

What should I do

**Comment by jakeuj** [comment]
How about `OnApplicationInitializationAsync` ?

**Comment by feigaogit** [comment]
> 
hi ，`OnApplicationInitializationAsync`  Do not execute，I don't know why

**Comment by feigaogit** [comment]
> How about `OnApplicationInitializationAsync` ?

hi， `OnApplicationInitializationAsync` Do not execute，I don't know why

**Comment by leeveney** [comment]
you should make your main method async in program.cs,
like this

![mmexport1670298204028](https://user-images.githubusercontent.com/11975191/205807657-f1a07b1f-93e0-476a-b57a-059671545ef6.png)

**Comment by feigaogit** [comment]
> 你应该在 program.cs 中使你的主要方法异步， 就像这样
> 
> ![mmexport1670298204028](https://user-images.githubusercontent.com/11975191/205807657-f1a07b1f-93e0-476a-b57a-059671545ef6.png)

You're right thanks
