### ISSUE TITLE
Created single layer application + Blazor + basic theme depends on LeptonXLite modules

### ISSUE THREAD

**Issue by bodeg** [abpframework/abp#14928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`abp new My.App -t app-nolayers -u blazor-server -dbms SQLite --theme basic `

The created project depends and loading LeptonXLite and  is not building.
I had to change `DependsOn`, `ConfigureBundles` and to add the relevant references

### Version

6.01

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
What's your CLI version?

**Comment by bodeg** [comment]
CLI version: Version 6.0.1 (Stable)

and.. I also tried the `abp new ... --pwa` 
although the option is not documented, it was supported by version 5, the CLI prompted 
`Progressive Web Apps = True`

I think nothing happened, and I did it manually

**Comment by maliming** [comment]
ok, We've fixed in 6.0.2, Please wait to released.
