### ISSUE TITLE
How to add a custom grant type in OpenIddict ?

### ISSUE THREAD

**Issue by liquehuo** [abpframework/abp#14929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

hi
I created  my solution by ： `abp new Acme.BookStore -t app-nolayers -dbms MySQL `
the version is 6.0.1

I see the post article ：https://community.abp.io/posts/how-to-add-a-custom-grant-type-in-openiddict.-6v0df94z

I copy the source code，but an error was reported，Please see the screenshot below

![image](https://user-images.githubusercontent.com/40256444/205431618-c497cff0-be84-45b5-a9b5-885022240399.png)

### Describe the solution you'd like

can you help me ?

**Comment by maliming** [comment]
hi

The `GenericTokenProncipal` come from OpenIddict 4.0 RC.

For 3.x you can use `Principal`
