### ISSUE TITLE
Add required reference for List during static c# proxy generation

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#14951]
There are unused references and missing references when files are created with a static c# proxy
![image](https://user-images.githubusercontent.com/58659931/205895370-b25c55d0-864c-44af-8ced-59ac9990946e.png)

**Comment by maliming** [comment]
hi

How to reproduce?

**Comment by salihozkara** [comment]
Hi, I came across it when I deleted the proxy in the blog module and generated it again.

**Comment by maliming** [comment]
ok

**Comment by maliming** [comment]
hi @salihozkara 

Please use `without-contracts` when generating proxies of build-in modules.

`abp generate-proxy -t csharp --without-contracts`
