### ISSUE TITLE
CmsKit: Some suggestions about Homepage middleware

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#14950]
1. Adding middleware should be a responsibility of the final application. If you do that here, `HomePageDefaultMiddleware` is added as the first middleware, before auditing, uow, https redirection, authentication and all other middlewares. Which may not be the app-developer wants. So, leave it to the final application and document it.

https://github.com/abpframework/abp/blob/b599d8a19c960d8bfd5e70322d4758bd9e4c41c1/modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs#L116-L124

2. Resolve `IPagePublicAppService` from `context.RequestServices` here (inside the if), instead of ctor-injection. In this way, DI will be faster if the result is not 404 (which is the %99 of cases for many application).

https://github.com/abpframework/abp/blob/b599d8a19c960d8bfd5e70322d4758bd9e4c41c1/modules/cms-kit/src/Volo.CmsKit.Public.Web/DefaultHomePageMiddleware.cs#L11

For more, please check [this PR](https://github.com/volosoft/volo/pull/8545).

**Note:** I am not familiar with context so if you think there are wrong suggestions please let me know.

**Comment by malikmasis** [comment]
@berkansasmaz thanks for your good suggestions.
For the first case, the logic should work in every case that's why I didn't touch it however for the second case I've applied your suggestion.
Regards / FYI.
