### ISSUE TITLE
Breaking changes in OpenIddict 4.0 impacting how URIs are handled 

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#14972]
https://github.com/openiddict/openiddict-core/issues/1613

**Comment by kevinchalet** [comment]
Hey @maliming,

`4.0.0-rc1.22607.41` was just pushed to NuGet.org. You can find the main changes in the release notes: https://github.com/openiddict/openiddict-core/releases/tag/4.0.0-rc1 (don't miss the last point, as you may want to also update your stores).

Do you guys have an idea of what will be the release date of ABP 7.0 RTM? Just to make sure OpenIddict 4.0 RTM ships at the right time 😄

As always, let me know if you have any question.

Cheers.

**Comment by maliming** [comment]
hi @kevinchalet 

We plan to release 7.0 on December 13, 2022.

https://github.com/abpframework/abp/milestone/76

**Comment by kevinchalet** [comment]
Thanks @maliming! I'll schedule a release on Monday, then 😃
Please let me know if the exact date changes at some point.

**Comment by maliming** [comment]
no problem.

**Comment by kevinchalet** [comment]
It seems the date associated to https://github.com/abpframework/abp/milestone/76 changed. Do you confirm 7.0 was postponed?

(OpenIddict 4.0 RTM is almost ready but I had to fix a last-minute bug discovered during canary testing, so it's not available yet on NuGet.org)
