### ISSUE TITLE
[BUG] Authorization failed! User has not logged in.

### ISSUE THREAD

**Issue by haptear** [abpframework/abp#1497]
I have baseController this controler need ‘Authorize“
```csharp
   [Authorize]
    public class BaseController : AbpController
    {
        public override void OnActionExecuted(ActionExecutedContext context)
        {          
            base.OnActionExecuted(context);
        }
    }
```
TestContorller
```csharp
    public class TestController : BaseController 
    {
         [AllowAnonymous]
        public async Task<IActionResult> Test()
        {
             return ok();
         }
    }
```

when i call this api http://127.0.0.1/test/test  will get the exception  "Authorization failed! User has not logged in."   because of the function "CheckAsync(IAuthorizeData authorizationAttribute)" in the file  "MethodInvocationAuthorizationService.cs" throw the exception.

**Comment by maliming** [comment]
Very strange, I will check it, thank you.

**Comment by maliming** [comment]
similar https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4296

**Comment by maliming** [comment]
In the Boilerplate we skip the authorization check of the non-public method.

However, as in the case of issue, we cannot modify the definition of the `OnActionExecuted` method. It must be Public.

I also found a phenomenon:
When the service intercepted in the Boilerplate calls other methods in this class, the interceptor continues to intercept the called method. For example: `CheckError()` method.

But this is not the case in the new abp. Similar to this link: https://stackoverflow.com/questions/35416279/castle-windsor-intercept-method-call-from-within-the-class/35685619

**Comment by hikalkan** [comment]
Add `[AllowAnonymous]` to the `OnActionExecuted` method in your `BaseController` class.
