### ISSUE TITLE
The search location does not seem appropriate

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#14973]
**Version:** 6.0.2
Template: Blazor Server/WASM

The search location does not seem appropriate. Must be right aligned

![image](https://user-images.githubusercontent.com/99716457/206095479-a39604cd-ebdd-4c9d-91b4-b2079344f2b9.png)

**Comment by enisn** [comment]
It'll be on the right with RTL. It's placed at left with LTR language

**Comment by gizemmutukurt** [comment]
The search appears to have slipped.
![image](https://user-images.githubusercontent.com/99716457/210067038-0a12ae3f-8e5f-402e-923e-0af03cd559cb.png)

mvc example:
![image](https://user-images.githubusercontent.com/99716457/210067817-189edc4b-ab72-40b5-90f9-cc290f1a128c.png)
