### ISSUE TITLE
MVC tutorial improvement suggestions

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#1500]
I just completed the [ASP.NET Core MVC Tutorial](https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I).  The tutorial was very informative and easy to follow!  However, I do have a couple suggestions.

As I read through the tutorial, I noticed I keep re-reading the instructions because the `todo task` was given prior to the `project/location`.  I would suggest flipping things around a bit.  (At least in English)

**Example 1**

**From:** Create a class, named `Book`, in the `Acme.BookStore.Domain` project as shown below:

**To:** In the `Acme.BookStore.Domain` project, create a new Book class `(Book.cs)` as shown below:

**Example 2**

**From:** Injected `IRepository<Book, Guid>` and used it in the `SeedAsync` to create two book entities as the test data.

**To:** The `SeedAsync` method uses the injected `IRepository<Book, Guid>` to create two book entities for testing.

**Or:** The injected `IRepository<Book, Guid>` is used by `SeedAsync` to create two book entities for testing.

**Reference Links**

I'd also recommend using a link for **_all_** references.  I got stuck on the following instruction for several minutes. (Note, it make perfect sense now.)

"Like done for the BookDto above, create a mapping from the CreateUpdateBookDto object to the Book entity:"

A link back to the previous step would have saved me several minutes of scratching my head.

These are just a few suggestion I had as a new comer.  All in all, the tutorial was great!  I'd be happy to assist in rewording the tutorial, and word-smiting the rest of the documentation as I read through it.

**Comment by hikalkan** [comment]
Thanks a lot for your suggestions. It is appreciated if you send a PR :)
