### ISSUE TITLE
After upgrading from core3.1 to net6, json's properties JsonIgnore and JsonProperty are invalid.

### ISSUE THREAD

**Issue by Linsan925** [abpframework/abp#15018]
### After upgrading from 3.1 to 6, json's properties JsonIgnore and JsonProperty are invalid.

Referring to the latest version 13.2 of Newtonsoft.Json, and upgrading the previous abp3.2 to the latest version of net6, it is found that json attributes JsonIgnore and JsonProperty are invalid, the returned api data cannot display the Name specified by JsonProperty, and the attribute identified by JsonIgnore cannot be hidden. Looking at the official document and trying to add. AddControllersWithViews and. AddNewtonsoftJson will not work. Configuring AbpJsonOptions can only ensure the successful time formatting; How should I operate it? thank you

**Comment by Linsan925** [comment]
`var configuration = context.Services.GetConfiguration();
            Configure<MvcOptions>(options =>
            {
                var filterMetadata = options.Filters.FirstOrDefault(x => x is ServiceFilterAttribute attribute && attribute.ServiceType.Equals(typeof(AbpExceptionFilter)));

                // 移除 AbpExceptionFilter
                options.Filters.Remove(filterMetadata);

                // 添加自己实现的 MeowvBlogExceptionFilter
                options.Filters.Add(typeof(PwcExceptionFilter));
                //options.Filters.Add(typeof(DigitalProcurementExceptionFilter));
            });

            //context.Services.Configure<MvcNewtonsoftJsonOptions>(options =>
            //{
            //    options.SerializerSettings.ContractResolver = new DefaultContractResolver();
            //    options.SerializerSettings.DateFormatString = "yyyy-MM-dd HH:mm:ss";
            //    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            //});
            context.Services.Configure<AbpJsonOptions>(options =>
            {
                options.UseHybridSerializer = false;
                options.DefaultDateTimeFormat = "yyyy-MM-dd HH:mm:ss";
            });
            // 跨域配置
            context.Services.AddCors(options =>
            {
                options.AddPolicy(DefaultCorsPolicyName,
                builder =>
                {
                    builder
                        .WithOrigins(
                            configuration["Cors:Origins"]
                                .Split(",", StringSplitOptions.RemoveEmptyEntries)
                                .Select(o => o.RemovePostFix("/"))
                                .ToArray()
                        )
                        .SetIsOriginAllowedToAllowWildcardSubdomains()
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials();
                });
            });

            // 路由配置
            context.Services.AddRouting(options =>
            {
                // 设置URL为小写
                options.LowercaseUrls = true;
                // 在生成的URL后面添加斜杠
                options.AppendTrailingSlash = true;
            });

            // 身份验证之JWT
            context.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                   .AddJwtBearer(options =>
                   {
                       options.TokenValidationParameters = new TokenValidationParameters
                       {
                           // 是否验证颁发者
                           ValidateIssuer = true,
                           // 是否验证访问群体
                           ValidateAudience = true,
                           // 是否验证生存期
                           ValidateLifetime = true,
                           // 验证Token的时间偏移量
                           ClockSkew = TimeSpan.FromSeconds(30),
                           // 是否验证安全密钥
                           ValidateIssuerSigningKey = true,
                           // 访问群体
                           ValidAudience = AppSettings.JWT.ValidAudience,
                           // 颁发者
                           ValidIssuer = AppSettings.JWT.ValidIssuer,
                           // 安全密钥
                           IssuerSigningKey = new SymmetricSecurityKey(AppSettings.JWT.IssuerSigningKey.GetBytes())
                       };

                       // 应用程序提供的对象，用于处理承载引发的事件，身份验证处理程序
                       options.Events = new JwtBearerEvents
                       {
                           OnChallenge = async context =>
                           {
                               // 跳过默认的处理逻辑，返回下面的模型数据
                               context.HandleResponse();

                               context.Response.ContentType = "application/json;charset=utf-8";
                               context.Response.StatusCode = StatusCodes.Status401Unauthorized;

                               var result = new ServiceResult();
                               result.IsFailed("UnAuthorized");

                               await context.Response.WriteAsync(result.ToJson());
                           }
                       };
                   });

            // 认证授权
            context.Services.AddAuthorization();

            // Http请求
            context.Services.AddHttpClient();

            // 添加workflow数据库链接
            //context.Services.AddWorkflow(x => x.UseSqlServer(AppSettings.ConnectionString, true, true));

            context.Services
                .AddControllersWithViews()
                .AddNewtonsoftJson(options =>
                {
                    // 首字母小写(驼峰样式)
                    options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                    // 时间格式化
                    options.SerializerSettings.DateFormatString = "yyyy-MM-dd HH:mm:ss";
                    // 忽略循环引用
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    // 忽略空值
                    // options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                })
                .AddMvcOptions(options =>
                {
                    options.Filters.Add<MyResultFilter>();
                });`

**Comment by maliming** [comment]
Your ABP Framework version.
Your User Interface type (Angular/MVC/React... etc.) if the issue is related to a specific UI
Your database provider(EF Core/MongoDB)
Exception message and stack trace if available (check the logs).
Steps needed to reproduce the problem.

**Comment by Linsan925** [comment]
> Your ABP Framework version. Your User Interface type (Angular/MVC/React... etc.) if the issue is related to a specific UI Your database provider(EF Core/MongoDB) Exception message and stack trace if available (check the logs). Steps needed to reproduce the problem.

ABP Framework 6.0.1
Newtonsoft.Json 13.0.2

The webapi returns dto to add json attributes JsonProperty and JsonIgnore, The data can be returned normally, but the features are invalid.

API Result DTO:
`
 public class ProjectOverallListDto : DataSyncBaseDto
    {
        [JsonProperty("Id")]
        public Guid Id { get; set; }

        [JsonProperty("ProjectCode")]
        public string RequestNo { get; set; }

        [JsonProperty("ProjectUrl")]
        public override string ProjectDetailUrl { get; set; }

        [JsonProperty("ProjectName")]
        public string ProjectName { get; set; }

        [JsonProperty("RequestStatus")]
        public string RequestStatus { get; set; }

        [JsonIgnore]
        public decimal? BudgetToRate { get; set; }
}
`
API Result Data:
`
[
  {
    "id": "10680efc-1572-423a-8d2b-2edd3203398a",
    "requestNo": "A20221009WSXC1",
    "projectDetailUrl": "",
    "projectName": "We all have a brilliant future",
    "requestStatus": "Approved",
    "budgetToRate": 0.83
}]
`
The return property **projectDetailUrl** is not changed to the **ProjectUrl** of the property, and the property **BudgetToRate** corresponding to the hidden property JsonIgnore is not hidden.

**Comment by maliming** [comment]
Set `UseHybridSerializer` to `false` or use the `System.Text.Json` attributes.

https://docs.abp.io/en/abp/latest/JSON#abpjsonoptions

**Comment by Linsan925** [comment]
> Set `UseHybridSerializer` to `false` or use the `System.Text.Json` attributes.
> 
> https://docs.abp.io/en/abp/latest/JSON#abpjsonoptions

I set up `UseHybridSerializer` in host module, but the ignore feature didn't take effect.

![image](https://user-images.githubusercontent.com/59075706/209096322-8b832520-aa2f-4f81-8929-850a5d1d67a9.png)

![image](https://user-images.githubusercontent.com/59075706/209096409-5f0d86cf-6cc5-4d9f-a9c0-942eb607d648.png)
