### ISSUE TITLE
appsettings.json was not found when dotnet ef migrations add

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#1502]
When I add migration, I got an error about appsettings.json

* Cmd

> PS \src\Wow.OBMan.EntityFrameworkCore.DbMigrations> dotnet ef migrations add Init

* Error

> The configuration file 'appsettings.json' was not found and is not optional. 
> The physical path is '\src\Wow.OBMan.EntityFrameworkCore.DbMigrations\appsettings.json'

ABP is use WebContentDirectoryFinder to get the path, 
but Volo is use Directory.GetCurrentDirectory()

I copy ABP's CalculateContentRootFolder to Volo Project, and work fine now.

```
public static string CalculateContentRootFolder()
{
    var coreAssemblyDirectoryPath = 
        Path.GetDirectoryName(typeof(OBManDomainModule).GetTypeInfo().Assembly.Location);

    if (coreAssemblyDirectoryPath == null)
    {
        throw new Exception("Could not find location of Wow.OBMan.Core assembly!");
    }

    var directoryInfo = new DirectoryInfo(coreAssemblyDirectoryPath);
    while (!DirectoryContains(directoryInfo.FullName, "Wow.OBMan.sln"))
    {
        if (directoryInfo.Parent == null)
        {
            throw new Exception("Could not find content root folder!");
        }

        directoryInfo = directoryInfo.Parent;
    }

    var dbMigratorFolder = Path.Combine(directoryInfo.FullName, "src", "Wow.OBMan.DbMigrator");
    if (Directory.Exists(dbMigratorFolder))
    {
        return dbMigratorFolder;
    }

    var webHostFolder = Path.Combine(directoryInfo.FullName, "src", "Wow.OBMan.Web");
    if (Directory.Exists(webHostFolder))
    {
        return webHostFolder;
    }

    throw new Exception("Could not find root folder of the web project!");
}
```

BTW, dotnet ef need Microsoft.EntityFrameworkCore.Design package.

* UseMySQL
* Rider 2019

**Comment by maliming** [comment]
You can run [MyProjectName.DbMigrator](https://github.com/abpframework/abp/blob/dev/templates/mvc/src/MyCompanyName.MyProjectName.DbMigrator/appsettings.json)

**Comment by Nongzhsh** [comment]
@maliming Hi, currently, can use user secrets in MyProjectName.DbMigrator project?

**Comment by maliming** [comment]
@Nongzhsh I have not tried it, there should be no problem, you can give it a try.

**Comment by jakeuj** [comment]
> Add `Microsoft.EntityFrameworkCore.Design` to `xxx.EntityFrameworkCore.DbMigrations`
> 
> ```postscript
> PS src\xxx.EntityFrameworkCore.DbMigrations> dotnet ef database update -s ..\xxx.Web\xxx.Web.csproj
> ```
> 
> Also you can run [MyProjectName.DbMigrator](https://github.com/abpframework/abp/blob/dev/templates/mvc/src/MyCompanyName.MyProjectName.DbMigrator/appsettings.json)

I add [Microsoft.EntityFrameworkCore.Design] already, so I can run "dotnet ef migrations add".

The problem is when I add migrations, I got an error "appsettings.json was not found" .

[MyProjectName.DbMigrator] will not add my new table when I can't add any migrations.
