### ISSUE TITLE
Annoying scroll effect on docs.abp.io

### ISSUE THREAD

**Issue by minhtaile2712** [abpframework/abp#15033]
I find it nowhere to submit a suggestion for the documentation website, so I create an issue here.

Can you remove the scrolling effect of the navigating menu in the left panel?

Please make it simple, allow us scrolling line by line and quickly instead of scrolling a full block of links with slow animation. I feel like I have to wait forever just to wait for the animation to finish and it will always over-scroll the menu items I need to see.

**Comment by maliming** [comment]
@armgnunlu What do you think?
