### ISSUE TITLE
[BUG]may be a bug,the table abpentitychanges‘s  ExtraProperties column allways empty

### ISSUE THREAD

**Issue by haptear** [abpframework/abp#1504]
may be is a bug or my way of use is not correct.
i want the chang detail 'propertyChanges'  can be record to table

I define a entity
```csharp
 [Audited]
    public class TestEntity : CreationAuditedEntity<long>
   {
        public string Name{get;set;}
       public string TraceId{get;set;}
  }
```
then I changed the  fields value and save,Table ‘abpentitychanges’ added a data, but ‘ExtraProperties’ field is empty

debug screenshot
![image](https://user-images.githubusercontent.com/16282949/61504999-fa2d1280-aa0f-11e9-85bf-28f75b1886fd.png)

**Comment by maliming** [comment]
Please share a screenshot of the abpentitychanges table data.

**Comment by haptear** [comment]
![image](https://user-images.githubusercontent.com/16282949/61505572-dec30700-aa11-11e9-8178-62e0151096e5.png)

**Comment by maliming** [comment]
This seems to be no bugs.

ExtraProperties is just a property.

**Comment by haptear** [comment]
how can save "propertyChanges" to db, i want save the entity changes detail to db.

**Comment by haptear** [comment]
@maliming  thank you for answer
I find it, the chang detail save to "abpentitypropertychanges“ table,  
![image](https://user-images.githubusercontent.com/16282949/61509537-9a3f6780-aa21-11e9-84bd-4dea5cf603e1.png)
