### ISSUE TITLE
abp Suite updates .cs files containing Chinese, there will be garbled code

### ISSUE THREAD

**Issue by cicna** [abpframework/abp#15054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

abp Suite updates .cs files containing Chinese, there will be garbled code.
  
 for example：
ʹ��httpЭ�鷽ʽ������cookie���⣩

### Version

6.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please get help from  https://support.abp.io/
