### ISSUE TITLE
IDX20807: Unable to retrieve document from: 'System.String'.  HttpResponseMessage

### ISSUE THREAD

**Issue by cicna** [abpframework/abp#15055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1、Login is not possible from the public site.
2、Deleting \r will also prevent you from logging in

![1670682889093](https://user-images.githubusercontent.com/18661156/206860889-1756223c-8a54-4568-9beb-c709f5dc342e.png)

![1670682949528](https://user-images.githubusercontent.com/18661156/206860893-cae524ad-3387-40dc-902b-914c5ade407a.png)

![image](https://user-images.githubusercontent.com/18661156/206860926-d75786d5-8055-464f-8f78-182d449b45b3.png)

![1670683070781](https://user-images.githubusercontent.com/18661156/206860935-edae1488-be0c-4a0e-bbb6-085f4eef58f5.png)

### Version

6.0.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

**Comment by maliming** [comment]
hi

Please get help from https://support.abp.io/
