### ISSUE TITLE
Angular UI Modal should expose NgbModalOptions options

### ISSUE THREAD

**Issue by jtoniolo** [abpframework/abp#15058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The Angular UI modal no longer provides size, centered or class.

These are all available in ng-bootstrap's modal API

### Describe the solution you'd like

Expose NgbModalOptions options through your API.

At a minimum, please bring back size, centered and class.

These should all be relatively easy to implement.

https://ng-bootstrap.github.io/#/components/modal/api#NgbModalOptions

**Comment by mahmut-gundogdu** [comment]
we are already exposed the ngb-options https://github.com/abpframework/abp/blob/fb44a47222eaf3ebf4e2a339ec4ccb128c9747d6/npm/ng-packs/packages/theme-shared/src/lib/components/modal/modal.component.ts#L54
you can use options input.
