### ISSUE TITLE
Support for the JsonSerializerSettings property of the custom NewtonsoftJsonSerializer component.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1506]
Related discussion: https://github.com/abpframework/abp/commit/76ed33a910b605aba39ad6f2f708f94203af94fc#r34367167

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/08fd42e1d45dde67e842eb2487f912259b39a134/framework/src/Volo.Abp.Json/Volo/Abp/Json/Newtonsoft/NewtonsoftJsonSerializer.cs#L32

**Comment by maliming** [comment]
If we use the built-in Json component after NET Core 3.0, this issue will have no meaning.

**Comment by hikalkan** [comment]
We will use it. So, we take it backlog with low priority.

**Comment by xyfy** [comment]
does the AbpJsonOptions has released in version 0.18.1?

**Comment by maliming** [comment]
`AbpJsonOptions` This feature has been removed. Please see the discussion: https://github.com/abpframework/abp/commit/76ed33a910b605aba39ad6f2f708f94203af94fc#r34367167

**Comment by xyfy** [comment]
How can I changed the json format setting in  0.18.1

I use below code in [XXXWebModule]
```
private void ConfigurationJson(IServiceCollection services)
        {
            services.AddMvc().AddJsonOptions(options => { options.SerializerSettings.DateFormatString = "yyyy-MM-dd HH:mm:ss"; });
        }
``
but it not worked!

**Comment by maliming** [comment]
Now you can replace the `NewtonsoftJsonSerializer `component.

Reference Code:
Https://github.com/abpframework/abp/commit/08fd42e1d45dde67e842eb2487f912259b39a134

For the next version you can use `AbpJsonOptions.DefaultDateTimeFormat`
https://github.com/abpframework/abp/blob/08fd42e1d45dde67e842eb2487f912259b39a134/framework/src/Volo.Abp.Json/Volo/Abp/Json/AbpJsonOptions.cs#L8

Or you can use abp's Nightly Builds
https://docs.abp.io/en/abp/latest/Nightly-Builds

**Comment by xyfy** [comment]
I used abp's Nightly Builds

but where I updated ,I got an err  , IAsyncCrudAppService can not found
it work fine before,  does it chang nuget package in 0.19?

```
using Volo.Abp.Application.Services;
 public interface IBookAppService : IAsyncCrudAppService<
            BookDto, 
            Guid,
            PagedAndSortedResultRequestDto, 
            CreateUpdateBookDto, 
            CreateUpdateBookDto> 
    {
    }
```

**Comment by maliming** [comment]
@xyfy 
It has been refactored.

see: https://github.com/abpframework/abp/issues/1456

**Comment by xyfy** [comment]
it now only provide a datetimeformat in  v0.19
but I also want to change the json result to return Enum Type  as string , not integer

**Comment by Goxiaoy** [comment]
> it now only provide a datetimeformat in v0.19
> but I also want to change the json result to return Enum Type as string , not integer

```
            Configure<MvcJsonOptions>(options =>
            {
                options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
            });
```

**Comment by yinchang0626** [comment]
@maliming  @Goxiaoy 
Just a little confuse,Is the `AbpJsonOptions` of  `AbpJsonModule` just can config `DefaultDateTimeFormat` param?
If I have others settings of SerializerSettings to config, like @Goxiaoy said
Is in v1.1.2 ,better way to configure is below code,because `Microsoft.AspNetCore.Mvc.MvcNewtonsoftJsonOptions` is from `Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll` and `Volo.Abp.AspNetCore.Mvc.dll` already ref it??
```csharp
            Configure<Microsoft.AspNetCore.Mvc.MvcNewtonsoftJsonOptions>(options =>
            {
                options.SerializerSettings.TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Objects;
            });
```

**Comment by realLiangshiwei** [comment]
Related https://github.com/abpframework/abp/pull/5952
