### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#1507]
Does aspnetboilerplate or abo.io have a Slack channel for team collaboration?

As a read through the documentation I'm starting to have questions.  

Where is the best place to collaborate with the team?  Post and help answer questions?  (stackoverflow)

**Comment by yekalkan** [comment]
Please use github issues for questions and to collaborating with the team.

There is a slack channel for community but not much active: https://join.slack.com/t/abpframework/shared_invite/enQtNTI3MDA3NTk1NzQ2LTZhN2JiNjhiYWY4YmNjMjBmN2EyNjc4MmE4Y2ViOGI0YWE4ZWNjZjVhNzBlZmNhN2JiMjQwYjgxYTA1YjY2NjA
