### ISSUE TITLE
Problem of Deleting a table row (Running in IIS10 server)

### ISSUE THREAD

**Issue by xiaoyuer1015** [abpframework/abp#15086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I delete a table row, it runs well in Create or update.
The error code: 
Authorization failed for the request at filter 'Volo.Abp.AspNetCore.Mvc.AntiForgery.AbpAutoValidateAntiforgeryTokenAuthorizationFilter
But it is running well in VS developing enviroment.

### Version

6.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by BogdanJak** [comment]
For me in the Blazor server with Ms SQLServer application, the use of the function

`await MailDataAppService.DeleteAsync(mailid);`

it doesn't cause any error, but it also doesn't delete the record from the database.

**Comment by maliming** [comment]
This seems like an `AntiForgery` problem. You can try to clear cookies and try again.
