### ISSUE TITLE
CMSKit- Findings on the Cms Kit blog post

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#15088]
- [x] When you reply to the comment written on the blog page, the cansel button slides.
![image](https://user-images.githubusercontent.com/99716457/207239070-694eeca7-413e-4837-82c8-d732b90a0c8f.png)

- [ ] The text looks unified, the key may not be added, it should be checked.
![image](https://user-images.githubusercontent.com/99716457/207239810-a950005a-0067-4083-9e9e-8968e39a6f7a.png)

**Comment by malikmasis** [comment]
solved https://github.com/abpframework/abp/issues/15107 via this branch @salihozkara
