### ISSUE TITLE
How to run MVC Module Template 

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1509]
I am trying to record the last video in the course "Setting up your development Environment for abp"

The documentation is not clear ....  how can run the project. The 'src' folder doesn't have the 'DbMigrator' Project and doest have the 'EF Core DbMigrations' Project 

Can you explain how to run the project, should I have a database all ready created using the mvc project and then change the appsetting.json in the Unified project to point to that database?

**Comment by vnetonline** [comment]
I think I have figured out how to run the MVC Module Template, I have published a tutorial at the here

- **[Creating building and running ABP Web Application Module project](https://amazingsolutions.teachable.com/courses/setting-up-your-development-environment-for-abp/lectures/11057429)**

You will need to enroll in the course "Setting up your development environment for abp". Enrollment is free

**Comment by hikalkan** [comment]
Thanks @vnetonline  :)
