### ISSUE TITLE
Test & Document IAbpHostEnvironment

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#15104]
See https://github.com/abpframework/abp/pull/14842
We have integration tests in the PR. We should also perform manuel tests. You can use the app startup template too see what's coming from the IAbpHostEnvironment in development mode, release and in production and prove that it works as expected.

After your tests, please open a section in this document and explain how to use it and how it works: https://docs.abp.io/en/abp/7.0/Application-Startup (after the IAbpApplication section).

**Comment by EngincanV** [comment]
Tests:

- [x] Getting the environment if the `AbpApplicationCreationOptions.Environment` is not set, by using the `IWebHostEnvironment` or `IWebAssemblyHostEnvironment`.
- [x] Set the `AbpApplicationCreationOptions.Environment` and ensure it always read from it.
- [x] Use `IAbpHostEnvironment` in a class library, it should be **Production** if the `AbpApplicationCreationOptions.Environment` is not set.
