### ISSUE TITLE
Tenant admin password not validated

### ISSUE THREAD

**Issue by Mirza233** [abpframework/abp#15106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating/updating a regular user, the password is validated e.g. to have at least 6 characters, one special character, etc. 
However, when creating a new tenant, we can set the tenant admin password to practically anything, as it is not validated.

### Reproduction Steps

- Log in as global administrator
- In the main menu select **Administration/Tenant Management/Tenants**.
- Click **New Tenant** button.
- Fill in **Tenant name** and **Admin Email Address** fields as you normally would.
- In **Admin Password** field enter **123** and click save

### Expected behavior

User is notified that the password is too weak and made aware of the constraints that password has to fulfil to be valid.

### Actual behavior

Tenant is created with admin that has weak password.

### Version

latest (6.0.2)

### User Interface

Common (Default)

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
It is currently not possible to implement. 
Mainly the tenant and identity modules are independent. You can try to implement it in your own application.
