### ISSUE TITLE
How to visit the swagger api by token

### ISSUE THREAD

**Issue by xiaoyuer1015** [abpframework/abp#15115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, I am beginner. I can not visit the permission API ant want to visit them by token. My problem is: how to set token to the swagger? Thank you

### Version

6.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by Marjani** [comment]
abp use openiddict as Authority Server in AuthServer project. if you use default source or configure correctly authority url on appsettings you can use Authorize bottom to get token from authority.

 
![abp](https://user-images.githubusercontent.com/433382/215161580-9048c412-11e7-4059-bb61-4ed53f229259.JPG)
