### ISSUE TITLE
Authorization failed! Given policy has not granted!What is the cause？

### ISSUE THREAD

**Issue by xiaoyuer1015** [abpframework/abp#15121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

When I  Post  "wx.request({          url: 'https://localhost/api/app/digital-first',          header:{            'Content-Type':'application/json',            'Authorization':'Bearer '+token,          },          success (res2) {            console.log(res2.data)          }        });"

The feedback information as following:
RemoteServiceErrorInfo ----------
{
  "code": "Volo.Authorization:010002",
  "message": "Authorization failed! Given policy has not granted: digital-first",
  "details": null,
  "data": {
    "PolicyName": "digital-first"
  },
  "validationErrors": null
}

**Comment by maliming** [comment]
Please check the current identity after the authentication middleware.

**Comment by tuyen-vuduc** [comment]
@maliming Do you have a sample code?

**Comment by maliming** [comment]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/6908465/209596317-77e74c33-3429-4462-ba1e-b5f6f16b25e2.png">

**Comment by tuyen-vuduc** [comment]
Thanks @maliming .

Finally, I found that I didn't pass `scope` when calling `connect/token` . The message is really mis-leading.

We should fix it. Either within ABP or a PR to OpenIDDict

**Comment by maliming** [comment]
We can't know if your scope is missing or not
