### ISSUE TITLE
Can not overring TokenController in separate identity server

### ISSUE THREAD

**Issue by YangYang1082** [abpframework/abp#15120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to overriding the TokenController in auth server follow #7766, but it doesn't work.

### Reproduction Steps

1. Use `abp new Tutorial -u angular -dbms PostgreSQL --separate-identity-server` initialize a project.
2. Overrding TokenController in auth server project:
``` C#
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(TokenController))]
    public class MyTokenController : TokenController
    {
        public override Task<IActionResult> HandleAsync()
        {
            throw new UserFriendlyException("This done not work!");
            //return base.HandleAsync();
        }
    }
```
3. Run auth server and post {auth_server_url}/connect/token , will not throw UserFriendlyException.

### Expected behavior

Run auth server and post {auth_server_url}/connect/token , it will enter the overrid method.

### Version

6.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> Run auth server and post {auth_server_url}/connect/token , will not throw UserFriendlyException.

https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.Password.cs#L32
