### ISSUE TITLE
Learn how to build the BookStore Application by watching video tutorial

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1513]
I have just release the second Course "Learn How to Build the Book Store Application" at 

https://amazingsolutions.teachable.com/p/lets-build-the-bookstore-application

Just released the First Tutorial, don't forget to enroll and register to get updates when i release new Tutorials in this Course.

- **Creating a new project using ABP Cli and implementing our Book entity & enum**

Let me now if you have any comments

**Comment by mkmita** [comment]
Hi, appreciate your input. Maybe you can provide some direction how to extend book store application with new module and ui? :)

**Comment by vnetonline** [comment]
> Hi, appreciate your input. Maybe you can provide some direction how to extend book store application with new module and ui? :)

@mkmita I plan on using Ionic, ReactNative and Xamarin once I have completed the "Building BookStore Application" Course. these are planned course and will be released over the next few weeks.

Let me know if you have a UI layer which you prefer and i will add it to the list.

**Comment by vnetonline** [comment]
Guys I have just released the second Tutorial in the course "Building "

**Working in the Data Layer which shows how to** 
- **Adding Book Entity to DbContext**
- **Configuring Book Entity,** 
- **Adding a Migration**
- **Updating the Database and** 
- **Seeding Sample Data**

You will need to enroll in the course to be able to access this video.

let me know if you have any comments

**Comment by mkmita** [comment]
@vnetonline  i mean how to extend bookstore app with other module?

For example i want to have bookstore visitors module with its own ui.

As i understand i should generate new mvc module with ui right? But do you know how to integrate UI together with existing bookstore UI ?

**Comment by vnetonline** [comment]
@mkmita you are correct you should generate an mvc-module template inorder to develop several modules which have their own UI. I am yet to figure out how to do this becuase of the lack of documentation. 

I plan to have a course which will show how to interact with several modules once I know how ..... I shall post back here and update you

**Comment by seanalford** [comment]
@vnetonline great job!  A high level abp intro video would be great too. One that defines the basic building blocks, and the explains topology of the framework in general.  As a new comer even after reading all of the documents I still find myself struggling with framework definitions.

**Comment by vnetonline** [comment]
@seanalford Thanks for the feed back, I will add it to the list

**Comment by vnetonline** [comment]
Guys I have just released the third tutorial "**[Working on the Application Layer](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11059123)**" in the course "Lets Build the BookStore Application with ABP vNext Framework" which shows how to:

- **Create a Application Service**
- **Create the BookDto and the CreateUpdateDto**
- **Define a Interface IBookAppService**
- **Implement the BookAppService**
- **How to use SqaggerUI to test the AppService endpoints**
- **How to use the Dynamic Javascript Proxies to call the getList and create API endpoints using the your Chrome developer tools**

You will need to enroll in the course to be able to access this video.

let me know if you have any comments

**Comment by seanalford** [comment]
@vnetonline Creating building and running ABP Web Application Module project isn't showing up in my browser.  All I see is a Discussion tab.

![image](https://user-images.githubusercontent.com/8544833/61634695-e0820a00-ac5f-11e9-8c33-37caa6368208.png)

**Comment by vnetonline** [comment]
@seanalford apologies i have just re-uploaded the video tutorial my internet connection is very flaky
hoping for a better connection when they rollout "Optic Fiber to the curb" in my area hopefully next year

<img width="897" alt="Screen Shot 2019-07-23 at 11 05 48 am" src="https://user-images.githubusercontent.com/15242923/61675057-0ed41800-ad3a-11e9-86d6-197ea2968cb2.png">

**Comment by seanalford** [comment]
@vnetoline great job!

**Comment by vnetonline** [comment]
Guys I have just released the third tutorial "[Working on the Presentation Layer to display the Book List](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11112023)" in the course "[Lets Build the BookStore Application with ABP vNext Framework](https://amazingsolutions.teachable.com/p/lets-build-the-bookstore-application)" which shows how to:

- **Create the Books Page**
- **Add Books Page to the Main Menu**
- **Localizing the Menu Items**
- **Displaying the Book List**
- **Adding a Script File to call the GetLIst HttpApi end point**

You will need to enroll in the course to be able to access this video.

let me know if you have any comments

**Comment by vnetonline** [comment]
Guys I have just released the third tutorial "[Creating a new Book](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11112168)" in the course "[Lets Build the BookStore Application with ABP vNext Framework](https://amazingsolutions.teachable.com/p/lets-build-the-bookstore-application)" which shows how to:

- **Create the the Modal Form using the Dynamic Form TagHelper of ABP** 
- **Implement the CreateModalModel with Bing Property for the Dynamic Form**
- **Add the New Book Button**
- **Add client side code to index.js to pop open the Modal**
- **Debug Build errors**
- **Troubleshoot why the book button doest work using the Chrome Developer Tools**

You will need to enroll in the course to be able to access this video.

let me know if you have any comments

**Comment by vnetonline** [comment]
Guys I have just released the 6th tutorial "[Updating an Existing Book](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11123133)" in the course "[Lets Build the BookStore Application with ABP vNext Framework](https://amazingsolutions.teachable.com/p/lets-build-the-bookstore-application)" which shows you how to:

- **Create the the EditModal using the Dynamic Form TagHelper of ABP**
- **Implement the EditModalModel with BindProperty attribute and hidden input for the Id**
- **Add the Edit menu item to the Actions Button on the Book List Page**
- **Add client side code to index.js to pop open the EditModal**
- **Troubleshoot why the EditModal is not opening using the Chrome Developer Tools**

You will need to enroll in the course to be able to access this video.

let me know if you have any comments

**Comment by vnetonline** [comment]
Guys I have just released the 7th tutorial "[Deleting a Book](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11131525)" in the course "[Lets Build the BookStore Application with ABP vNext Framework](https://amazingsolutions.teachable.com/p/lets-build-the-bookstore-application)" which shows you how to:

- **Add client side code to index.js to be able to Delete a Book**
- **Add the Delete menu item to the Actions Button on the Book List Page**
- **Localize the texts Delete, BookDeletionConfirmationMessage and SuccessfullyDeleted**

You will need to enroll in the course to be able to access this video.

let me know if you have any comments

**Comment by vnetonline** [comment]
Guys I have just released the final section which explains and shows you how to build integration tests using the ABP Testing infrastructure in the course "[Lets Build the BookStore Application with ABP vNext Framework](https://amazingsolutions.teachable.com/p/lets-build-the-bookstore-application)" t his section has the following tutorials:

- [Adding Test Data to the SqliteInMemory Database](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11138681)
- [Creating the Should_Get_List_Of_Books test](https://amazingsolutions.teachable.com/courses/577537/lectures/11181592)
- [Creating the Should_Create_A_Valid_Book test](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11181600)
- [Creating the Should_Not_Create_A_Book_Without_Name test](https://amazingsolutions.teachable.com/courses/lets-build-the-bookstore-application/lectures/11181607)

We are not all perfect so the tutorials also show you how to debug and troubleshoot when we make silly mistakes and encounter errors.

This final section finalises this course. 

You will need to enroll in the course to be able to access this video, it is free.

let me know if you have any comments
