### ISSUE TITLE
Implement `IHasEntityVersion` for some entities of some modules

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#15135]
We will implement the new `IHasEntityVersion` interface for some of the entities in the application modules (and also their corresponding ETO classes). Both for open source and commercial modules.

#### CMS Kit

* Page
* Blog Post (only posts, not blogs)

#### Identity

* IdentityUser
* IdentityRole
* OrganizationUnit

#### Tenant Management

* Tenant

#### SaaS

* Tenant
* Edition

**Comment by JadynWong** [comment]
I noticed that `EntityVersion` is of type `int`. EntityVersion will always be self-incrementing on updating. Would it be better to use the `long` type? 
```
int.MaxValue: 2147483647
long.MaxValue: 9223372036854775807
```

`int.MaxValue` is enough to handle most types of business. Maybe I'm overthinking it and want to see what you think.

**Comment by malikmasis** [comment]
> I noticed that `EntityVersion` is of type `int`. EntityVersion will always be self-incrementing on updating. Would it be better to use the `long` type?
> 
> ```
> int.MaxValue: 2147483647
> long.MaxValue: 9223372036854775807
> ```
> 
> `int.MaxValue` is enough to handle most types of business. Maybe I'm overthinking it and want to see what you think.

Hi,
That's right but I think the `long` type will be unnecessary for that. It doesn't seem possible to change the same line that many times.
