### ISSUE TITLE
GetPagedListAsync with filter

### ISSUE THREAD

**Issue by mario-madrid** [abpframework/abp#15133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to get paginated filtered results from database, but I cannot find a way to do this with the framework.

I can do filtered request and I can do paged request to the database but I can't mix both functionalities together.

### Describe the solution you'd like

I think the best solution is to add an overload for GetPagedListAsync accepting an expression, like the GetListAsync does.

**Comment by maliming** [comment]
How about this?

https://github.com/abpframework/abp/blob/2c37e56751a3ff9a7e4c0cd44541e6a1a33f031d/framework/src/Volo.Abp.MemoryDb/Volo/Abp/Domain/Repositories/MemoryDb/MemoryDbRepository.cs#L297

**Comment by mario-madrid** [comment]
Is good, but then I would suggest to add two parameters to the overloaded version of GetPagedListAsync accepting:

1.- A predicate for ordering (we need order if we want to page the results).
2.- A predicate for filtering.

**Comment by maliming** [comment]
hi

You can implement it by yourself.
