### ISSUE TITLE
How to create monolithic application with several separated modules?

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#1514]
Hello,

Can't find any docs about how to create monolithic app with separated modules.
What i want to build is monolithic modular app with separated modules and ui.
I understand starter template, but i do not find any docs how to extend ui and functionally with modules?
Is it possible to add modules with separate UI this way? How to combine all modules uis into one system?
Maybe somebody could give some direction on this?

Thank you in advance for insights and help.

**Comment by seanalford** [comment]
I’m confused about this also. 

Does abp add-module Acme.Catalog scaffold a new module into an existing project/solution?  When I try this it say Acme.Catalog module cannot be found.  I thought add-module would scaffold a new module into my Acme.BookStore project. Which is a bit confusing because BookStore is a module. 

Would be great to see a breakdown of the typology. It’s my understanding that abp add-package will add an existing module from a NuGet package.  I’ve read the documentation, but I’m still confused between a module and a package.

**Comment by vnetonline** [comment]
Guys I have just public the video on Creating building and running ABP Web Application Module project in my course "Setting up Development Environment for abp" This might help answer your questions. Check out the other videos in this course to lean about the solution structure

**[Creating building and running ABP Web Application Module project](https://amazingsolutions.teachable.com/courses/setting-up-your-development-environment-for-abp/lectures/11057429)**

You will have to enroll in the course enrolment is free

**Comment by hikalkan** [comment]
@mkmita:
>What i want to build is monolithic modular app with separated modules and ui.

The startup template does exactly what you want to do. It has no functionality its own, but just adds identity, account and tenant-management modules which have their own UI, API, entity, database and so on... There is no a complete document that explains it, but there are pre-built modules where you can inspire from, for now.

@seanalford:

>Does abp add-module Acme.Catalog scaffold a new module into an existing project/solution?

No. add-module adds an existing module as package (NuGet/NPM). Currently, it only works with the official modules ([see a list of them](https://docs.abp.io/en/abp/latest/Modules/Index)).

We normally suggest to create modules in their own solutions, to make them re-usable across different applications. However, if you want to use modularity only to split a large apps into smaller modules, you may have a single solutions with sub-folders. In that case, for now, you should create modules separately (`abp new Acme.BookStore.Payment -t mvc-module`) and add to your solution manually. Then reference to the layers of the module from the relates layers of the main application and add DependsOn attributes.
I created https://github.com/abpframework/abp/issues/1576 and https://github.com/abpframework/abp/issues/1575.
