### ISSUE TITLE
AspnetZero upgrade to Abp.io

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#1515]
@hikalkan I need to start a new project very soon.  I want to recommend to management that we use ASPNET Zero.  However, I will want to upgrade to ASP.IO as soon as it releases. Before, I recommend this path I want to make sure we can upgrade to the newer framework without purchasing a new license.  If you would prefer to discuss this offline you can message me on Twitter.

**Comment by hikalkan** [comment]
Yes, an email would be better for commercial usage questions since this is an open source project.
Send to info@volosoft.com please. Thanks.
