### ISSUE TITLE
`serializeFormToObject` function, cannot correct handling `<input type="checkbox" ...`

### ISSUE THREAD

**Issue by roc916** [abpframework/abp#15151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`serializeFormToObject` function, cannot correct handling `<input type="checkbox" ...`

https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Web/Pages/SettingManagement/Components/EmailSettingGroup/Default.js#L18

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/12685126/208403096-33e98e40-a2d8-412b-aa69-0bb09ade2cf0.png">

### Version

7.0.0-rc.4

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

**Comment by enisn** [comment]
This should work. It's strange, might be checkbox component code is different.

https://github.com/abpframework/abp/blob/2e7a833dbf90f4f621f86a8ae3f802599e14251b/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery/jquery-extensions.js#L99-L104

**Comment by roc916** [comment]
`// add unchecked checkboxes because serializeArray ignores them `

**Comment by maliming** [comment]
Related to https://github.com/abpframework/abp/pull/14194/
