### ISSUE TITLE
Add [Microsoft.EntityFrameworkCore.Design] can't resolve appsettings.json was not found

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#1516]
> Add `Microsoft.EntityFrameworkCore.Design` to `xxx.EntityFrameworkCore.DbMigrations`
> 
> ```postscript
> PS src\xxx.EntityFrameworkCore.DbMigrations> dotnet ef database update -s ..\xxx.Web\xxx.Web.csproj
> ```
> 
> Also you can run [MyProjectName.DbMigrator](https://github.com/abpframework/abp/blob/dev/templates/mvc/src/MyCompanyName.MyProjectName.DbMigrator/appsettings.json)

I add [Microsoft.EntityFrameworkCore.Design] already, so I can run "dotnet ef migrations add".

But my problem is when I add migrations, I got an error "appsettings.json was not found".

[MyProjectName.DbMigrator] will not add my new table when I can't add any migrations.

_Originally posted by @jakeuj in https://github.com/abpframework/abp/issues/1502#issuecomment-513638264_

**Comment by seanalford** [comment]
You shouldn’t need to add any packages.  I’m assuming you’ve successfully deployed the initial migration. Just make sure you have the EntityFrameworkCore project set as your default project. Then enter add-migration <migration-name> in package console.  Then update-database to deploy.

**Comment by maliming** [comment]
You still need to specify the startup project with the` -s` parameter.

` -s|--startup-project <PROJECT>         The startup project to use.`

**Comment by jakeuj** [comment]
> You still need to specify the startup project with the` -s` parameter.
> 
> ` -s|--startup-project <PROJECT> The startup project to use.`

Thank you very much.

**Comment by viewtance** [comment]
I tried follow the steps, it still failed, the error is cannot found the specified startup project
