### ISSUE TITLE
Angular  - Settings management cannot be activated.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#15177]
**App:** Angular `7.0.0-rc.5`

Settings management cannot be activated.
https://github.com/abpframework/abp/issues/15176 The error might be caused by this.

![b8cf7293-ca6a-4736-bda1-2df5efe82898](https://user-images.githubusercontent.com/99716457/208830875-0a3302db-6f19-4243-9b94-973236145ae6.gif)

**Comment by fatihskilic** [comment]
Does not reproduce
