### ISSUE TITLE
IDS4 Issue when set client EnableLocalLogin=false

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#15182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Version is 5.3.0 and use IDS4.
I have integrated AAD in my project with `Microsoft.AspNetCore.Authentication.MicrosoftAccount`，when I Set a client EnableLocalLogin=false in database. Then error `ERR_TOO_MANY_REDIRECTS` show in brower and the error log is `Showing login: User logged in locally, but client does not allow local logins`.
I find  this log in ID4 Repository :
![image](https://user-images.githubusercontent.com/16984534/208852112-47eb6b1b-f72a-4772-9267-e9001fc69a76.png)
If set EnableLocalLogin=true everything is ok.
So,did I miss the configuration? And I don't understand why IDP is Local here.
I know that ID4 has been archived.

### Version

5.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

**Comment by maliming** [comment]
**Reproduction Steps**

**Comment by xxvolvo** [comment]
It's my override  fault.
Sorry,closed.
