### ISSUE TITLE
How to remove tenant UI part in permission session?

### ISSUE THREAD

**Issue by KaungZawHtet** [abpframework/abp#15197]
I disable the tenant in `Configure<AbpMultiTenancyOptions>` but the tenant is still shown. How can I remove the tenant permission provider?
<img width="773" alt="Screenshot 2022-12-21 at 9 51 27 PM" src="https://user-images.githubusercontent.com/15225530/208940775-a19403f1-3ff2-404d-b5f8-a194d2a87564.png">

**Comment by maliming** [comment]
You can remove `tenantManagementGroup` via your custom `PermissionDefinitionProvider`.

https://github.com/abpframework/abp/blob/dev/modules/tenant-management/src/Volo.Abp.TenantManagement.Application.Contracts/Volo/Abp/TenantManagement/AbpTenantManagementPermissionDefinitionProvider.cs#L12

**Comment by KaungZawHtet** [comment]
I see. My solution was removing the tenant-related modules and the record from AbpPermissionGroups. Btw, Default GroupName for PermissionDefinaitonProvider should be in docs. I tried to find it but didn't get it.
