### ISSUE TITLE
LinkedIn account login & add to social accounts

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#15204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Abp'nin standardına LinkedIn accountu ile register/login eklesek güzel olur.

**Comment by maliming** [comment]
hi

You can consider using `AspNet.Security.OAuth.Providers`. 

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers
