### ISSUE TITLE
How to get all user names by what?

### ISSUE THREAD

**Issue by xiaoyuer1015** [abpframework/abp#15214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I would like to get all abpusers; names. But I don't know how to get them. Thanks!

**Comment by maliming** [comment]
You can get data by [Repositories](https://docs.abp.io/en/abp/latest/Repositories) .

Please start with https://docs.abp.io

**Comment by xiaoyuer1015** [comment]
[maliming](https://github.com/maliming), My problem is more. The above question is not soleve. I tried, but some new problems occurred.
I want to get the APBUsers user ID and UserName in web. Is there any other way?

**Comment by mahmut-gundogdu** [comment]
> [maliming](https://github.com/maliming), My problem is more. The above question is not soleve. I tried, but some new problems occurred. I want to get the APBUsers user ID and UserName in web. Is there any other way?

you can inject user Repository in your application and query it them. Then return what you want.
