### ISSUE TITLE
Failed to minify `bootstrap-dim.css` in LeptonX Lite theme

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#15222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/30018771/209545810-710d6772-e104-420e-aa4f-8de22d5d06f6.png">

ABP 6.0.1
LeptonX Lite 1.0.2

### Version

6.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi @muhammedaltug 

If some js or css files don't need to be minified, you can configure them like this


<img width="622" alt="image" src="https://user-images.githubusercontent.com/6908465/209646728-aea66efd-4251-40f4-9e73-33c9906f16f9.png">

**Comment by enisn** [comment]
It seems it's working right now

<img width="773" alt="image" src="https://user-images.githubusercontent.com/23705418/229461009-f17bace3-f1ba-4276-8a72-bef687069665.png">

do you still getting this error on v1.0.5 ?

**Comment by gdlcf88** [comment]
Maybe fixed. I will reopen this issue if it happens again.
