### ISSUE TITLE
Custom WarpResult, HttpApi Client return null

### ISSUE THREAD

**Issue by Guili95** [abpframework/abp#15220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Custom WarpResult, HttpApi Client return null

### Version

All

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Reproduction Steps

**Comment by Guili95** [comment]
Custom WarpResult，Calling another service interface in one service returns an unexpected result. Normal if disabled
![FB173G}_MSG5X@7DTLF KYS](https://user-images.githubusercontent.com/15993468/209541241-1eab6c97-0741-4390-88d2-ab17b9ede97b.png)
![image](https://user-images.githubusercontent.com/15993468/209541430-7c861ef4-2288-42d2-98c9-4f46bf5a728b.png)
![Y0N1)8EBKK2F_HTQ)VM7ARC](https://user-images.githubusercontent.com/15993468/209541454-0f38035c-9fff-453c-b4ac-95c13450312c.png)

**Comment by maliming** [comment]
Please share the full steps and code, Thanks.

**Comment by colinin** [comment]
It is possible that the server wrapped the returned result and the client proxy call was not unpacked, causing the deserialization to fail

**Comment by samxxxxx** [comment]
@maliming I have the code to reproduce this issue. Please check the GitHub repository: https://github.com/samxxxxx/voloabpwinformwrap

```git
git clone https://github.com/samxxxxx/voloabpwinformwrap.git
```
