### ISSUE TITLE
CLI: Use created project's angular cli instead of the global ng cli

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#15247]
**UI:** Angular- MongoDB `7.0.0-rc.6 `
**Command:**  `abp new Angular.MoongoSeperate221228Free   -t app -u angular -m none --separate-identity-server --database-provider mongodb -csf --version 7.0.0-rc.6`
An error was encountered while creating the project.
**Note:** But the project is created and works fine.

![image](https://user-images.githubusercontent.com/99716457/209789243-65713125-9fe7-4565-90fe-b1758c0e41db.png)

**Comment by ebicoglu** [comment]
this is the real error 
![image](https://user-images.githubusercontent.com/9526587/209811093-8dd6ca95-1007-46e9-b2f2-21a155aeca79.png)

**Comment by muhammedaltug** [comment]
We shouldn't use global angular cli. we should use created project's angular cli

**Comment by EngincanV** [comment]
> We shouldn't use global angular cli. we should use created project's angular cli

https://github.com/abpframework/abp/blob/8236b83268228a8d1a2c1c90cc483b55c00a9d53/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectModification/AngularThemeConfigurer.cs#L24
