### ISSUE TITLE
Angular -  Modal design should be improved

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#15246]
**UI:** Angular- MongoDB `7.0.0-rc.6 `

Modal design should be improved, Reset button not needed
![image](https://user-images.githubusercontent.com/99716457/209788993-be9b939a-effd-419a-81fd-a0cd78c2e2b6.png)

**Comment by ebicoglu** [comment]
hide "horizontal scroll bar" and "Reset to default" button if there's no data.
