### ISSUE TITLE
Query after InsertAsync returns null

### ISSUE THREAD

**Issue by ghulamostafa** [abpframework/abp#15255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After calling InsertAsync from the repository, I am making a query to retrieve the data that was just inserted with details and it is returning null and when I check the database, it is not inserted.

```
var myEntityObject = await _repository.InsertAsync(new myEntity()
        {
            MerchantId = businessId,
            Address = branch.Address,
            AddressAr = branch.AddressAr,
            Latitude = branch.Latitude,
            Longitude = branch.Longitude,
            CityId = branch.CityId,
            Status = Enums.MerchantBranchStatus.Open
        });

        var queryable = await _repository.WithDetailsAsync(x => x.City);
        var query = queryable.Where(x => x.Id == myEntityObject .Id).AsQueryable();
        var myEntityOutput = await AsyncExecuter.FirstOrDefaultAsync(query);
```

But when I do the insert without querying, it works fine and I query in another API call.

What mistake could I be doing here?

### Version

5

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

> Set true to automatically save changes to database.
This is useful for ORMs / database APIs those only save changes with an explicit method call, but you need to immediately save changes to the database.



```cs
var myEntityObject = await _repository.InsertAsync(new myEntity()
        {
            MerchantId = businessId,
            Address = branch.Address,
            AddressAr = branch.AddressAr,
            Latitude = branch.Latitude,
            Longitude = branch.Longitude,
            CityId = branch.CityId,
            Status = Enums.MerchantBranchStatus.Open
        }, autoSave: true);
```

**Comment by ghulamostafa** [comment]
Thank you. It works now.
