### ISSUE TITLE
Update the Todo sample and tutorial for ABP 7.0-rc.6

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#15253]
Our purposes are:

* Re-create all the samples based on ABP 7.0-rc.6
* Update/fix the tutorial content for ABP 7.0-rc.6. Especially, screenshoots will change since we use LeptonX-Lite anymore.

### Single Layer

- [x] Angular-EfCore
- [x] Angular-Mongo
- [x] BlazorServer-EfCore
- [x] BlazorServer-Mongo
- [x] Mvc-EfCore
- [x] Mvc-Mongo

Location: https://github.com/abpframework/abp-samples/tree/master/TodoApp-SingleLayer

### Multi-Layer

- [x] Angular-EfCore
- [x] Angular-Mongo
- [x] BlazorServer-EfCore
- [x] BlazorServer-Mongo
- [x] BlazorWebAssembly-EfCore
- [x] BlazorWebAssembly-Mongo
- [x] Mvc-EfCore
- [x] Mvc-Mongo

Location: https://github.com/abpframework/abp-samples/tree/master/TodoApp

## Tutorials

- [x] Single layer: https://docs.abp.io/en/abp/7.0/Tutorials/Todo/Single-Layer/Index
- [x] Multi-layer: https://docs.abp.io/en/abp/7.0/Tutorials/Todo/Overall

Please consider all the DB / UI combinations.

**Comment by ebicoglu** [comment]
- https://docs.abp.io/en/abp/7.0/Migration-Guides/Abp-7_0
- https://docs.abp.io/en/commercial/7.0/migration-guides/v7_0

**Comment by ebicoglu** [comment]
@braim23 we can close this issue if all is completed.
