### ISSUE TITLE
Add loading button that on the home page.

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#15263]
When user click the Login button that on the home page (when the user did not authenticated), the button should be disabled and it shown a loading indicator. the process are finished. Loading will be removed.

The base branch should be rel-7.0 but if you solve the issue with another branch, we can fix that. No problem. just do it  :)

here  the code.
https://github.com/abpframework/abp/blob/e04173c8dbc81b80f9af06d05a15862464680b43/templates/app/angular/src/app/home/home.component.html#L13

also it will add another templates. after the feature is work as well.

You can use  AbpLoading directive
https://docs.abp.io/en/abp/latest/UI/Angular/Loading-Directive

Docs to how to install development env. 
https://github.com/abpframework/abp/blob/dev/docs/en/Contribution/How-to-Contribute-abp.io-as-a-frontend-developer.md

If you have any question about the issue. Please contact to me.

**Comment by furkangunduz** [comment]
if it is still open can ı work on it ?

**Comment by mahmut-gundogdu** [comment]
> if it is still open can ı work on it ?

yes still open.  You should fork the pr
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/2217899/209952069-6191d56c-a155-4900-a055-6f3bea3e44ed.png">
 implement the issue. And Open a pr. If you open a Pull Request, I will assign to you.
