### ISSUE TITLE
OpenIdDict extension grants got "unauthorized_client"

### ISSUE THREAD

**Issue by holyrong** [abpframework/abp#15260]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests, and other discussions about the framework.

If you're creating a bug/problem report, please include the followings:

* Your **ABP Framework version**.
7.0-rc5
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
Angular
* Your database provider(EF Core/MongoDB)
* EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

create a custom extension grant type fllow the post:https://community.abp.io/posts/how-to-add-a-custom-grant-type-in-openiddict.-6v0df94z

change the dataseed like this:
![1672309123408](https://user-images.githubusercontent.com/8318475/209937632-c5faf61e-5d2a-48a4-8e8f-35f9c941d92b.png)

when I test the /connect/token with postman,I got the error like below:
`{
  "error": "unauthorized_client",
  "error_description": "This client application is not allowed to use the specified grant type.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2064"
}
`

please help me to analysis the reason.

also,I can't find the grant type I've defined from database,where is it store?

**Comment by maliming** [comment]
`application.Permissions.Add(OpenIddictConstants.Permissions.Prefixes.GrantType + "my_union");`

**Comment by snowchenlei** [comment]
> OpenIddictConstants.Permissions

add in where?

**Comment by snowchenlei** [comment]
> `application.Permissions.Add(OpenIddictConstants.Permissions.Prefixes.GrantType + "my_union");`

add in where?

**Comment by maliming** [comment]
`OpenIddictDataSeedContributor.cs`
