### ISSUE TITLE
Application CLI

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#1526]
Are there any plans to add a console application to the ABP mvc template?  The console would basically be a simple http client that would allow users to make API calls via CLI.  It would be nice it the CLI could process a simple scripting too.  This would allow users to build scripts to automate common repetitive tasks.  As task scheduler would be nice too.

**Comment by hikalkan** [comment]
Isn't this what you want: https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp
