### ISSUE TITLE
Exception prevent disconnect

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#15274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

we notice that unhandled exception inside a component cause the connection to be stuck. normaly it should be disconnected right away but this doesnt happen with abp.

the connection is cleaned up only after the timeout - in the mean time, all references are valid and can cause a lot of unexspected exceptions because of the invalid state of the component.

### Reproduction Steps

[AbpDisconnectStuck.zip](https://github.com/abpframework/abp/files/10325178/AbpDisconnectStuck.zip)

-2. update connection string for your enviroment
-1. call abp install-libs
0. execute dbmigration

1. execute blazor
2. open /cleanup and close tab
3. open /exception and close tab

### Expected behavior

after 2. and 3. you should see the "clean up" log entry immidetly

### Actual behavior

after 2. you can see the "clean up" log entry immidetly
after 3. no disconnect happen - you need to wait for timeout ( about 2min ) until you see the "clean up" log entry

### Known Workarounds

its not a workaround but you can call GC.Collect() and free up the components memory if you dont have any strong references to it ( only works if you use weak references for all outside references like callbacks ), but it doesnt call Dispose or destructor/Finalize ( so unmanaged memory is not freed and other states are not updated correctly )

### Version

6.0.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

[NoDisconnectStuck.zip](https://github.com/abpframework/abp/files/10325244/NoDisconnectStuck.zip)

here is the same without abp ( default blazor-server template )
as you see it is disconnected right after the exception and cleaned up

**Comment by realLiangshiwei** [comment]
Fixed by https://github.com/abpframework/abp/issues/14734

**Comment by puschie286** [comment]
@realLiangshiwei its in the blazorise v1.1 update right - is it possible to update abp v6 to blazorise v1.1 ?

**Comment by realLiangshiwei** [comment]
The Blazorise 1.x is based on NET 7

**Comment by puschie286** [comment]
ok thanks
