### ISSUE TITLE
I am getting the following error when I try the MVC tiered template

### ISSUE THREAD

**Issue by ClementeGao** [abpframework/abp#1527]
![image](https://user-images.githubusercontent.com/16145998/61840743-bf6e2300-aec4-11e9-8e76-cfb7961b1bc7.png)

**Comment by maliming** [comment]
Please share the error log of your application.

**Comment by ClementeGao** [comment]
![image](https://user-images.githubusercontent.com/16145998/61841545-b92d7600-aec7-11e9-86f9-eb0471f2d355.png)

**Comment by maliming** [comment]
I mean the log of the exception occurred. The screenshot you shared does not have any error logs.

**Comment by ClementeGao** [comment]
There is really no log of any error level in the log.

**Comment by ClementeGao** [comment]
must run the xxx.host project with xxx.identityserver before running the mvc project.  is it ?

**Comment by vnetonline** [comment]
@ClementeGao you can watch the following video tutorial to see how you can run the solution 

https://amazingsolutions.teachable.com/courses/setting-up-your-development-environment-for-abp/lectures/10995086

You will need to enroll it is free

**Comment by maliming** [comment]
> must run the xxx.host project with xxx.identityserver before running the mvc project. is it ?

You should run the application with the given order:

First, run the .IdentityServer since other applications depends on it.
Then run the .HttpApi.Host since it is used by the .Web application.
Finally, you can run the .Web project and login to the application (using admin as the username and 1q2w3E* as the password).

see: https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Mvc.md#how-to-run-1

**Comment by ClementeGao** [comment]
can you tell me What is the difference between these two templates?
There is a template that only runs mvc and it is successful
![image](https://user-images.githubusercontent.com/16145998/61844497-3c53c980-aed2-11e9-87c7-526ab49b21a6.png)

**Comment by ClementeGao** [comment]
@vnetonline thank you  Is there a Chinese version of the video tutorial?

**Comment by vnetonline** [comment]
@maliming I can give you captions in English are you interested in translating them to Chinese version ?

**Comment by maliming** [comment]
@vnetonline  If your course is very popular, I would be happy to add subtitles to it.

**Comment by vnetonline** [comment]
@maliming I have 37 students who have enrolled in the courses

**Comment by ClementeGao** [comment]
I can't choose which template to use. Can you recommend one?

**Comment by maliming** [comment]
@ClementeGao see: https://github.com/abpframework/abp/blob/dev/docs/zh-Hans/Startup-Templates/Index.md

**Comment by ClementeGao** [comment]
@maliming  ok thank you

**Comment by vnetonline** [comment]
I would start off with the default MVC template and then later convert it to tiered by copying projects over to the tiered layered solution structure

Vineet Belani
+61 402 263 321
________________________________

**Comment by ClementeGao** [comment]
@vnetonline +61 402 263 321 is  wahtsApp account?

**Comment by vnetonline** [comment]
Yes

Vineet Belani
+61 402 263 321
________________________________

**Comment by ClementeGao** [comment]
@vnetonline  I can't find you in whatsApp

**Comment by ClementeGao** [comment]
@maliming  Do you have any other contact information?

**Comment by vnetonline** [comment]
@ClementeGao can you please delete the post with my mobile number please

**Comment by ClementeGao** [comment]
ok Already deleted
