### ISSUE TITLE
PackageReference Volo.Abp.RemoteServices Missing in Blazor Microservice

### ISSUE THREAD

**Issue by tobimax** [abpframework/abp#15286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP Framework version - ABP CLI 7.0.0-rc.6
User Interface type - Blazor Server / Microservices Template
Database provider - EF Core - SQL Server

### Reproduction Steps

Generate a new microservice entity
Build solution fails with missing <PackageReference Include="Volo.Abp.RemoteServices" Version="7.0.0-rc.6" />

### Expected behavior

Template should add reference

<PackageReference Include="Volo.Abp.RemoteServices" Version="7.0.0-rc.6" />

### Actual behavior

Template does not add reference to <PackageReference Include="Volo.Abp.RemoteServices" Version="7.0.0-rc.6" />

### Regression?

n/a

### Known Workarounds

n/a

### Version

7.0.0-rc.6

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/issues/15296#issuecomment-1369311702
