### ISSUE TITLE
Adding New Service to Microservice defaults to HttpClientProxies which do not work

### ISSUE THREAD

**Issue by tobimax** [abpframework/abp#15296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP Framework version - ABP CLI 7.0.0-rc.6
User Interface type - Blazor Server / Microservices Template
Database provider - EF Core - SQL Server

### Reproduction Steps

Adding New Service to Microservice defaults to AddHttpClientProxies which do not work in a microservices environment. Even though the correct proxy code is already generated.

There is no warning that this will not work in a microservices environment.

### Expected behavior

Adding New Service to a Microservice templates defaults to AddHttpClientProxies which do not work in a microservices environment.

### Actual behavior

In  MyCompany. MyNewService.HttpApi.Client MyNewServiceHttpApiClientModule.cs the following code is generated.

```csharp

public class MyNewServiceHttpApiClientModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddHttpClientProxies(typeof(MyNewServiceApplicationContractsModule).Assembly,
             MyNewServiceRemoteServiceConsts.RemoteServiceName);

        Configure<AbpVirtualFileSystemOptions>(options =>
        {
            options.FileSets.AddEmbedded<MyNewServiceHttpApiClientModule>();
        });
    }
}
```

### Regression?

don't know.

### Known Workarounds

Change AddHttpClientProxies to AddStaticHttpClientProxies

```csharp

public class MyNewServiceHttpApiClientModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddStaticHttpClientProxies(typeof(NetworkSecurityServiceApplicationContractsModule).Assembly,
              NetworkSecurityServiceRemoteServiceConsts.RemoteServiceName);

        Configure<AbpVirtualFileSystemOptions>(options =>
        {
            options.FileSets.AddEmbedded<MyNewServiceHttpApiClientModule>();
        });
    }
}
```

### Version

7.0.0-rc.6

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi,

We don't discuss commercial versions in the community. could you open a ticket on the support website https://support.abp.io/QA/Questions? thanks.

> We will refund your ticket if it's a bug.
