### ISSUE TITLE
Adding New Entity to Microservice creates incorrect route on Menu Item

### ISSUE THREAD

**Issue by tobimax** [abpframework/abp#15294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP Framework version - ABP CLI 7.0.0-rc.6
User Interface type - Blazor Server / Microservices Template
Database provider - EF Core - SQL Server

### Reproduction Steps

Add a new Entity i.e. MyNewService

The route created for the Page would be 

`
@page "/my-new-service"
`

However the menu item is added as /MyNewService in the MyNewServiceMenuContributor class.

### Expected behavior

MyNewServiceMenuContributor.cs should have the correct route.

### Actual behavior

MyNewServiceMenuContributor.cs does not have the correct route.

### Regression?

No

### Known Workarounds

Manual fix.

### Version

7.0.0-rc.6

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi,

https://github.com/abpframework/abp/issues/15296#issuecomment-1369311702
