### ISSUE TITLE
Ability to retrieve resource from specific file for a supplied culture

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#15292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The injected service `IStringLocalizer<CommonUIResource> commonResource` allows to retrieve data only for the current culture like this: `commonStringLocalizer.GetString("resource_name")`

### Describe the solution you'd like

It is not enough. Sometimes it is required to retrieve the resource for the given culture: `commonStringLocalizer.GetString("resource_name", cultureInfo)`

**Comment by alexandis** [comment]
Seems I have found the way to do that:

```
            var languages = await _languageProvider.GetLanguagesAsync();
            foreach (var language in languages)
            {
                using (CultureHelper.Use(language.CultureName))
                {
                    var localizedCompanyNotFoundString = _stringLocalizer.GetString("Companies:CompanyNotFound");
                    ...
                }
            }
```

**Comment by maliming** [comment]
You're right. `CultureHelper` is the right way.
