### ISSUE TITLE
AbpCommonDbProperties not working on XXX.DbMigrator

### ISSUE THREAD

**Issue by alva-lin** [abpframework/abp#15310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`AbpCommonDbProperties` not working on XXX.DbMigrator

When I set `AbpCommonDbProperties.DbSchema="abp";` in the Main method of the  `src/XXX.DbMigrator/Program.cs` file, then run `XXX.DbMigrator` project, the relevant settings will not be included in the generated migration files.

### Reproduction Steps

> the Volo.Abp.Cli version is 6.0.2

## Steps

1. Create project from default template

```
abp new TodoApp
```

2. Add the following code to the main method in the `src/TodoApp.DbMigrator/Program.cs`

```csharp
static async Task Main(string[] args) 
{
    // added code
    AbpCommonDbProperties.DbSchema = "abp";

    // ...
}
```

3. Run the TodoApp.DbMigrator project
4. Check the generated Migrations folder in `src/TodoApp.EntityFrameworkCore`
5. About line 144 of the `Migrations/TodoAppDbContextModelSnapshot.cs` file

```csharp
// the generated code
b.ToTable("AbpAuditLogs", (string)null);

// what I want
b.ToTable("AbpAuditLogs", "abp");
```

## Use 'ef migrations' command

When I use 'ef migrations add ...' command, its will produce different results if I choose different startup project.

### Use `XXX.DbMigrator` project as the startup project

> The following commands are run in the powershell environment, and the running directory is in the solution root directory.

```powershell
# TodoApp.DbMigrator as the startup project
dotnet ef migrations add `
	--startup-project src\TodoApp.DbMigrator\TodoApp.DbMigrator.csproj `
	--project src\TodoApp.EntityFrameworkCore\TodoApp.EntityFrameworkCore.csproj `
	--context TodoApp.EntityFrameworkCore.TodoAppDbContext `
	--configuration Debug `
	--output-dir Migrations `
	Initial
```

the generated Migrations folder is the same as the previously generated folder.

### Use `XXX.Web` project as the startup project

1. Add the following code to the main method in the `src/TodoApp.Web/Program.cs`

```csharp
public static async Task<int> Main(string[] args)
{
    // added code
    AbpCommonDbProperties.DbSchema = "abp";

    // ...
}
```
2. Run command 

```powershell
# TodoApp.Web as the startup project
dotnet ef migrations add \
	--startup-project src\TodoApp.Web\TodoApp.Web.csproj \
	--project src\TodoApp.EntityFrameworkCore\TodoApp.EntityFrameworkCore.csproj \
	--context TodoApp.EntityFrameworkCore.TodoAppDbContext \
	--configuration Debug \
	--output-dir Migrations \
	Initial
```

3. Check the generated Migrations folder in `src/TodoApp.EntityFrameworkCore`

    > the generated Migrations folder is correct content.

4. About line 144 of the `Migrations/TodoAppDbContextModelSnapshot.cs` file

```csharp
// the generated code
// what I want
b.ToTable("AbpAuditLogs", "abp");
```

5. About Initial.Up method of the `Migrations/XXXX_Initial.cs`

```csharp
  public partial class Initial : Migration
  {
      protected override void Up(MigrationBuilder migrationBuilder)
      {
          // what I want
          migrationBuilder.EnsureSchema(
              name: "abp");

          migrationBuilder.CreateTable(
              name: "AbpApplications",
              schema: "abp",
              // ...
              );
```

### Version

6.0.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

You need to set `AbpCommonDbProperties.DbSchema="abp";` in all `Program.cs` files and `MyProjectNameDbContextFactory`.

**Comment by alva-lin** [comment]
> hi
> 
> You need to set `AbpCommonDbProperties.DbSchema="abp";` in all `Program.cs` files and `MyProjectNameDbContextFactory`.

it works, thanks
