### ISSUE TITLE
Angular -  "The target project does not selected" error is received when creating the project.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#15322]
**App:** Angular - MongoDB `7.0.0`

"The target project does not selected" error is received when creating the project.
![image](https://user-images.githubusercontent.com/99716457/210544518-23291ed3-d407-47e9-957a-85b893241a51.png)

**Comment by EngincanV** [comment]
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/schematics/src/commands/change-theme/index.ts#L31

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectModification/AngularThemeConfigurer.cs#L26
