### ISSUE TITLE
Error using new Lepton-x-lite - Element.closest: '*:has(> .form-control)' is not a valid selector

### ISSUE THREAD

**Issue by NicoFrLy** [abpframework/abp#15339]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Hello,

After migrating to Lepton-X-Lite Theme, we have the following error in any different pages (seems to occured in abp-modal where there is is form).

We have the error in console log : ERROR DOMException: Element.closest: '*:has(> .form-control)' is not a valid selector as soon as we open the modal.
![image](https://user-images.githubusercontent.com/122021499/210770621-712387b6-dd3a-4ccb-b4c5-67421655b962.png)

### Reproduction Steps

Create a new solution abp new Acme.BookStore -u angular -dbms MySQL

Try to edit admin user and try to click to Role Tab. Cannot access it and the error appears in console logs.

### Expected behavior

No error in console et access role tab.

### Actual behavior

Cannot create or edit role for users.

### Regression?

Work fine in Basic theme.

### Known Workarounds

None.

### Version

7.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

Tested on Abp 6.0.1 and 7.0, same behavior.
Tested on Lepton-x-lite 2.0.0, 2.0.0-rc4 to 5, and 1.0.0.

**Comment by mahmut-gundogdu** [comment]
What is your browser and browser version ?

**Comment by NicoFrLy** [comment]
The issue happens with Firefox 64 bits 102.6.0esr.
I will test with Firefox 108.0.2 and get back to you.

This is working fine (no console error and role tab is ok) with Chrome Browser (108.0.5359.125 (Build officiel) (64 bits)) or Edge Browser.

**Comment by NicoFrLy** [comment]
This issue is also hit with Firefox 108.0.2 (64-bit).

**Comment by mahmut-gundogdu** [comment]
I have testedm I couldn't produce. But doesn't matter. I think your browser did not support the selector. We can change/override that with a provider.

The current 
`   {
          provide: VALIDATION_TARGET_SELECTOR,
          useValue: '*:has(> .form-control)',
        },
` 
add this provides in your app.module.ts

`
   {
          provide: VALIDATION_TARGET_SELECTOR,
          useValue: '.form-control',//or what do you want. that only a selector for specify error container.
        },
`

My test case
Can I use https://caniuse.com/css-has . 
Maybe we should change the experimental selector. But I couldn't better way for this. I will re-considered that selector.


https://user-images.githubusercontent.com/2217899/211034442-79a86bf1-c46a-4bb4-9b4a-91a987e961d0.mov

**Comment by NicoFrLy** [comment]
Indeed, if I enable the flag layout.css.has-selector.enabled in Firefox, I do not have any issue anymore. It seems that this feature is not yet implemented in Gecko, so it would not be enabled soon on Firefox browser. :(
https://bugzilla.mozilla.org/show_bug.cgi?id=418039

I will apply your workaround as we would not ask our users to change their Firefox settings.

Thank you for your quick answer and workaround! :)

**Comment by NicoFrLy** [comment]
The workaround is working fine. Just for other users, we just need to import VALIDATION_TARGET_SELECTOR from @ngx-validate/core :
`import {
  VALIDATION_TARGET_SELECTOR,
} from '@ngx-validate/core';
`
`providers: [
    APP_ROUTE_PROVIDER,
    { 
      provide: VALIDATION_TARGET_SELECTOR, 
      useValue: '.form-control',
    },
  ],`

Thanks again for your great work on this framework !
