### ISSUE TITLE
Docs: Redirect to index page of the current project not the default one

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#15349]
If a document is not found or not successfully rendered on a page, a 404 error page is shown and 5 seconds later redirects back to the index page. The redirect URL, should be respected to the project name and redirected according to the project name rather than the default project.

For example: https://docs.abp.io/en/commercial/latest/tutorials/book-store/part-10 if this document is not found, it should redirect to https://docs.abp.io/en/commercial/latest/ not to the https://docs.abp.io/en/abp/latest/.

**Comment by salihozkara** [comment]
could not reproduce
