### ISSUE TITLE
CLI not working on version 0.181.0

### ISSUE THREAD

**Issue by hungitk46** [abpframework/abp#1535]
I just installed ABP CLI on my computer and try to create a new project with the ABP CLI command but I can't do it. I've got an error:
![image](https://user-images.githubusercontent.com/6505814/61957977-a65f9200-afea-11e9-97d3-08e22e087730.png).

**Comment by maliming** [comment]
This is a network problem, your computer can't connect to the abp server very well. You can try again or download it at the abo.io website.
