### ISSUE TITLE
Replace Component Issue in LeptonX Lite Angular UI

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#15357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The theme is LeptonX Lite Angular UI.

When Update to 7.0.0,I find that replace `User Menu Component` is invalid.But replace other component is ok (eg:Breadcrumb Component) with the same custom component.

Replace `User Menu Component` works fine in 6.0.1 with same code.

The code likes below:
` this.replaceableComponents.add({ component: MyCurrentUserComponent, key: eThemeLeptonXComponents.CurrentUser });`
and  the [doc](https://docs.abp.io/en/abp/latest/Themes/LeptonXLite/Angular) I have read.

### Reproduction Steps

1、Customize a component
2、Import in `app.module.ts`
3、Replace in `app.component.ts`

### Version

7.0.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by bariscanyilmaz** [comment]
Problem fixed
