### ISSUE TITLE
ABP CLI New Project Download Issue

### ISSUE THREAD

**Issue by shmoulana** [abpframework/abp#15355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/2368211/211197107-7717316f-92c9-47ed-9d53-0e8aab7a7158.png)

### Version

7

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by gterdem** [comment]
Can you try again? We had maintenance, it should be working now.
