### ISSUE TITLE
OpenIdDict Integration - The specified 'redirect_uri' is not valid for this client application

### ISSUE THREAD

**Issue by mannok** [abpframework/abp#15356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I cannot validate my public user flow against OpenIdDict Server as server prompted as following. May I know if there any misconfiguration from my side? Thanks
```
error:invalid_request
error_description:The specified 'redirect_uri' is not valid for this client application.
error_uri:https://documentation.openiddict.com/errors/ID2043
```

### Reproduction Steps

1. Update Database Table `OpenIddictApplications` to configure valid `RedirectUris` for `DNS_Swagger` as `["http://localhost:8001/swagger/oauth2-redirect.html"]`
![image](https://user-images.githubusercontent.com/458220/211230564-3af20b47-8a17-4bfd-9538-968a5a0aacc8.png)

2. Request the `http://localhost:8002/connect/authorize?response_type=code&client_id=DNS_Swagger&redirect_uri=http%3A%2F%2Flocalhost%3A8001%2Fswagger%2Foauth2-redirect.html&state=TW9uIEphbiAwOSAyMDIzIDA5OjUxOjAyIEdNVCswODAwIChIb25nIEtvbmcgU3RhbmRhcmQgVGltZSk%3D` , FYR: redirect_uri is decoded as `http://localhost:8001/swagger/oauth2-redirect.html`
![image](https://user-images.githubusercontent.com/458220/211230600-bed6fbdd-1b68-4bf5-9a69-9f91b84dfcd5.png)

### Version

Version 5.0.0 (Stable)

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> Update Database Table

Please try to clear your Redis.
