### ISSUE TITLE
Use minified version of the script/style instead of minification process

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1536]
* This will increase bundling performance
* Also some scripts has problems with minification (https://github.com/abpframework/abp/issues/1279), so we can directly use the minified version.

This works only if there is a min.css/min.js in the same folder with the normal script file.

**Comment by lanpin** [comment]
In the online version, I usually use CDN.

**Comment by hikalkan** [comment]
CDN support is also planned (https://github.com/abpframework/abp/issues/294).
