### ISSUE TITLE
Move npm packs and their contributors together

### ISSUE THREAD

**Issue by Xeevis** [abpframework/abp#1537]
The Problem:
---
Currently all `@abp` npm packs reside in 
> \abp\npm\packs

while their contributors are in

>\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Packages\Volo\Abp\AspNetCore\Mvc\UI\Packages

Yet they are supposed to go hand-in-hand. Wouldn't it make more sense to join them together like this?

![image](https://user-images.githubusercontent.com/5835044/61966629-5f19d700-afd3-11e9-95d6-6908b8e500ec.png)

---
The Solution:
---
Since we are already using **Yarn + Lerna** it's just tiny change to add **Yarn Workspaces** that will do the trick simply and effectively.

lerna.json:
```json
{
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "0.6.6"
}
```
project.json:
```json
{
  "private": true,
  "workspaces": [
    "*/npm"
  ],
  "devDependencies": {
    "lerna": "^3.16.4"
  }
}
```
`lerna publish` and other commands will work the same and the added benefit is that we also gain yarn commands like `yarn outdated` or `yarn upgrade-interactive --latest` to quickly update any out of date packages from all the workspaces with a single command.

![image](https://user-images.githubusercontent.com/5835044/61966525-17934b00-afd3-11e9-9902-7ff99b43db0b.png)

Thoughts?

**Comment by hikalkan** [comment]
It seems a good idea. I didn't think it can be possible. Will check it deeper and apply if not have a side problem.
