### ISSUE TITLE
Debug Crashes: Blazor WASM

### ISSUE THREAD

**Issue by ghost** [abpframework/abp#15376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Blazor WASM: Debug crashes and unable to debug application. Will run fine if I select to run without debugging. The UI to log into the app tries to load, however, it then crashes. There's not any error message that I'm able to find.

### Reproduction Steps

Basically, just create a new Blazor WASM application. After a while of making code changes, either backend or front one will not be able to debug the application regularly. Sometimes clearing browser cache and bin / obj directories helps, but most of the time it does not.

### Expected behavior

To debug my application consistently without having to spend 45 minutes trying to get the debug to work correctly.

### Actual behavior

Application launches in debug; Swagger loads up and then the frontend UI starts to load. Before the page finishes, the debug functionality is halted (crashes).

### Regression?

I'm not sure as this is my default project version.

### Known Workarounds

One may choose to run without debugging or in release mode and the application works as expected.

### Version

7.0

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Can you share a minimal project that can reproduce the problem?

**Comment by sturlath** [comment]
This happens to me in Visual Studio and then the only thing to do is to turn VS off and open it again. This has also happened lot less in resent time. I also recomend always using the newest preview version of VS..

**Comment by ghost** [comment]
@realLiangshiwei how would you like me to share my project? I cannot share here due to privacy reasons.  Here is what I have from the output during debug. I'm only including the last portion for brevity.

info: Volo.Abp.Modularity.ModuleManager[0]
      Initialized all ABP modules.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      PermissionRequirement: SettingManagement.Emailing
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      PermissionRequirement: AbpAccount.SettingManagement
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      PermissionRequirement: AbpIdentity.SettingManagement
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      PermissionRequirement: FeatureManagement.ManageHostFeatures
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
afterLeptonXInitialization
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.0\Microsoft.CSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x1 has exited with code 0 (0x0).
The program 'service-worker.js' has exited with code 4294967295 (0xffffffff).
The program '' has exited with code 4294967295 (0xffffffff).
The thread 0x0 has exited with code 0 (0x0).
The program 'localhost:44322' has exited with code 4294967295 (0xffffffff).
The program '[25556] iisexpress.exe' has exited with code 4294967295 (0xffffffff).
The program '[33096] iisexpress.exe' has exited with code 4294967295 (0xffffffff).

**Comment by realLiangshiwei** [comment]
> I cannot share here due to privacy reasons

You can create a new project to reproduce this issue.
