### ISSUE TITLE
template shou set ValidIssuers and and token time for save developer time

### ISSUE THREAD

**Issue by ohroy** [abpframework/abp#15379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

It took me a long time to solve a very common problem, which I think everyone can encounter.

The first is the token validity period, which is 30 minutes by default. I think everyone may have the need to modify this time.

The second is `ValidIssuers` , default the Issuer is null, that means it always check the request uri, and if someone deploy with docker or  nginx or just have many domain, it will meet `SecurityTokenInvalidIssuerException ` . This issue has discussed  at https://github.com/abpframework/abp/issues/5589 but It is outdated with openiddict now.

### Describe the solution you'd like

I think we shoud update the template project just like this

```c#
 var configuration = context.Services.GetConfiguration();
        PreConfigure<OpenIddictBuilder>(builder =>
        {
            builder.AddValidation(options =>
            {
                options.AddAudiences("[ProjectName]");
                options.UseLocalServer();
                options.UseAspNetCore();
                options.Configure(o =>
                    o.TokenValidationParameters.ValidIssuers =
                        configuration.GetSection("AuthServer:ValidIssuers").Get<string[]>());
            });
// update this line to change access token lifetime
            builder.AddServer(o => { o.SetAccessTokenLifetime(TimeSpan.FromDays(1)); });
        });
```

**Comment by ohroy** [comment]
Another solution is issuer to a fixed value, just like
```c#
            builder.AddValidation(options =>
            {
                options.SetIssuer("xxx");
```
This is mentioned in the document here
https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html#using-openid-connect-discovery-asymmetric-signing-keys-only

**Comment by maliming** [comment]
I don't think the template needs to be changed for now. Developers should change it as needed.

**Comment by ohroy** [comment]
emmm, Ok , just treat this issue as doc for someone who need this.
