### ISSUE TITLE
Maui blazor app Exception error (Cannot invoke JavaScript outside of a WebView context.)

### ISSUE THREAD

**Issue by yasinhallak** [abpframework/abp#15374]
An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module Volo.Abp.AspNetCore.Components.MauiBlazor.AbpAspNetCoreComponentsMauiBlazorModule, Volo.Abp.AspNetCore.Components.MauiBlazor, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null: 
Cannot invoke JavaScript outside of a WebView context.

### Reproduction Steps

I have created project with Ui MauiBlazor from abp suite. 

First : I run HttpApi.Host project.

Second: I run MauiBlazor project as andriod emulator and give me this error as above 

### Version

7.0.0

### User Interface

MAUI Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Sorry, I can't reproduce the problem.
Could you share the project that can reproduce with me? shiwei.liang@volosoft.com

**Comment by yasinhallak** [comment]
I sent you an invitation  @realLiangshiwei

**Comment by realLiangshiwei** [comment]
Hi,

I still could not reproduce the problem using the project you provided.

You can try to upgrade the `Volo.Abp.AspNetCore.Components.MauiBlazor.LeptonXTheme` to `2.0.0`.

Please open a ticket on the support website if you still face the problem. thanks.
