### ISSUE TITLE
ABP 7.0 - __tenant header is present in all HTTP request 

### ISSUE THREAD

**Issue by NicoFrLy** [abpframework/abp#15380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

Since the ABP 7.0 upgrade, the __tenant header is present in all http request (using angular httpClient), including not ABP's API. This is causing issue to our third party API server (for example to French Government Public API). 

The __tenant is not allowed and refused by remote server's CORS rule.

### Reproduction Steps

Deploy new abp template 7.0 (-t ng).

Write new httpClient call to another API (not a backend API). Check if firefox that the __tenant is present :
![image](https://user-images.githubusercontent.com/122021499/211610170-a666962d-946a-443b-b802-24c8f2854a19.png)

import { HttpClient } from '@angular/common/http';
...
 constructor(...
                private http: HttpClient,
...
this.http.get<addressDataGouvFrResponse>('https://api-adresse.data.gouv.fr/search/?q='+address.replace(replaceRegex, '+')
            .subscribe({..});
...

### Expected behavior

__tenant should not be present for API others than the ABP's.

### Actual behavior

__tenant is present in HTTP Request :
![image](https://user-images.githubusercontent.com/122021499/211610371-10e80360-bbba-461d-be83-e7f56000cfeb.png)

Error message :
![image](https://user-images.githubusercontent.com/122021499/211610552-59322094-1add-4d56-ad51-474950aa8965.png)

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://.... (Reason: header ‘__tenant’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

### Regression?

It did work perfectly using ABP 6.0, angular 14.

### Known Workarounds

Didn't find any.

### Version

7.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

**Comment by mahmut-gundogdu** [comment]
Actually, there hasn't been any change to HTTP interceptors or "__tenant" since V6.0; if it didn't add, it was a bug. However, you are correct. I believe it should only be added to the ABP url.  I will discuss with team. I will inform you. Then I will send a fix/solutuon for this version.

**Comment by NicoFrLy** [comment]
I found a workaround bypassing the http interceptors : 
private httpClientWithoutInterceptor: HttpClient;
...
constructor(..
                private http: HttpClient,
                private handler: HttpBackend,
                ) {
        this.httpClientWithoutInterceptor = new HttpClient(handler);
    }

this.httpClientWithoutInterceptor.get<addressDataGouvFrResponse>(
            'https://api-adresse.data.gouv.fr/reverse/?lon='+longitude+'&lat='+latitude).subscribe({...})

The __tenant header is not present anymore for these specifics API calls.

source : https://medium.com/nerd-for-tech/how-to-bypass-angular-http-interceptor-2491afca16a3

**Comment by mahmut-gundogdu** [comment]
> I found a workaround bypassing the http interceptors : private httpClientWithoutInterceptor: HttpClient; ... constructor(.. private http: HttpClient, private handler: HttpBackend, ) { this.httpClientWithoutInterceptor = new HttpClient(handler); }
> 
> this.httpClientWithoutInterceptor.get( '[https://api-adresse.data.gouv.fr/reverse/?lon='+longitude+'&lat='+latitude).subscribe({...}](https://api-adresse.data.gouv.fr/reverse/?lon='+longitude+'&lat='+latitude).subscribe(%7B...%7D))
> 
> The __tenant header is not present anymore for these specifics API calls.
> 
> source : https://medium.com/nerd-for-tech/how-to-bypass-angular-http-interceptor-2491afca16a3

I was unable  to come up with a good workaround. I am working a solution with a Http context token. All logic in middleware will skip if is set true. But it is breaking-change. . It'll be available in the 7.1 preview or 7.0 patch
