### ISSUE TITLE
Custom grant type in OpenIddict with all user claims

### ISSUE THREAD

**Issue by szilardd** [abpframework/abp#15387]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

Found this great article by @maliming on how to implement a custom OpenIddict grant validator 

https://community.abp.io/posts/how-to-add-a-custom-grant-type-in-openiddict.-6v0df94z

The issue is that the token returned by the `MyTokenExtensionGrant` grant type is shorter than an authentication token (one that is returned by the connect/token endpoint), reason being that it doesn't include the custom abp.io claims. A few examples:
- permission.*
- given_name
- phone_number
- email_verified

Can you help me with some suggestions on how to have all claims returned in the token? Couldn't find any other similar example.
Thanks

**Comment by szilardd** [comment]
I tried to extend the grant like this:

```cs
...
var abpClaimsPrincipalFactory = context.HttpContext.RequestServices.GetRequiredService<IAbpClaimsPrincipalFactory>();
var abpClaimsPrincipal = await abpClaimsPrincipalFactory.CreateAsync(claimsPrincipal);

return new SignInResult(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme, abpClaimsPrincipal);
```

`abpClaimsPrincipal` has all claims, but the token that is returned still doesn't contain the custom ones.

**Comment by maliming** [comment]
hi

`await context.HttpContext.RequestServices.GetRequiredService<AbpOpenIddictClaimDestinationsManager>().SetAsync(principal);`

**Comment by szilardd** [comment]
Thanks for the help. It didn't exactly work form me, had to tweak like this:

```cs
...
var abpClaimsPrincipalFactory = context.HttpContext.RequestServices.GetRequiredService<IAbpClaimsPrincipalFactory>();
var abpClaimsPrincipal = await abpClaimsPrincipalFactory.CreateAsync(claimsPrincipal);

await context.HttpContext.RequestServices.GetRequiredService<AbpOpenIddictClaimDestinationsManager>().SetAsync(abpClaimsPrincipal);

return new SignInResult(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme, abpClaimsPrincipal);
```

**Comment by szilardd** [comment]
For version > v7.3 the solution changed slightly

Changed shown here:

https://github.com/abpframework/abp/blob/db318186b3c8c4665e030648fbd632e315ff28c7/docs/en/Community-Articles/2022-11-14-How-to-add-a-custom-grant-type-in-OpenIddict/POST.md?plain=1#L79
