### ISSUE TITLE
Error to Create Applicaton with CLI

### ISSUE THREAD

**Issue by lommez** [abpframework/abp#1538]
Hi, i've been trying to use abp.cli to create a new application with no ui with the following command:
abp new app1 -t mvc-module --no-ui

Here is there screen shot with error:
[click here](https://portalvhdsdtx1sqp9m14cf.blob.core.windows.net/vhds/abp.cli.jpg)

**Comment by maliming** [comment]
see: https://github.com/abpframework/abp/issues/1535#issuecomment-515474146
