### ISSUE TITLE
OpenIdDict missing localization

### ISSUE THREAD

**Issue by szilardd** [abpframework/abp#15398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm working on upgrading from v5.3.4 to v7.0.0 which replaced IdentityServer with OpenIddict.

For IdentityServer I was able to provide localization overrides and localizations for a specific language like this:

```cs
Configure<AbpLocalizationOptions>(options =>
{
    options.Resources
        .Get<AbpIdentityServerResource>()
        .AddVirtualJson("/Localization/AbpIdentityServer");
});
```

I tried to do the same for OpenIdDict like this:

```cs
Configure<AbpLocalizationOptions>(options =>
{
      options.Resources
        .Get<AbpOpenIddictResource>()
        .AddVirtualJson("/Localization/AbpOpenIddict");
}
```

But it doesn't work because the error messages don't seem to be localized anymore. For example this one:

https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.Password.cs#L78

It looks like the localization was deliberately removed in this commit
https://github.com/abpframework/abp/commit/6953e9c8a400925a4c9ef0e823ff3d645856c1dd

The reason of the removal seems to be redundancy, but I'm not sure what is the alternative. Is there a different way to override localization for OpenIdDict?

Thanks

### Version

7.0.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
The error messages of OAuth2 protocol only supports English.

**Comment by zhangzunke** [comment]
@maliming 
I have the same issue in localization, if I want to support other language, how can I override default error message?

**Comment by maliming** [comment]
There may get errors if you add an error message in other languages.

**Comment by kevinchalet** [comment]
FWIW, I posted more information on StackOverflow on why error descriptions shouldn't be localized: https://stackoverflow.com/a/76483313/542757
