### ISSUE TITLE
LeptonXLite Theme Blazor WebAssembly responsive menu does not work.

### ISSUE THREAD

**Issue by curelom** [abpframework/abp#15393]
When webpage is narrow and menu changes to mobile/responsive mode where menu turns to hamburger menu on top, it is unusable.  Click on it and nothing happens.
![Screenshot 2023-01-12 005958](https://user-images.githubusercontent.com/1706500/212010654-ad2ae937-2a02-4e96-a253-2da0d80c2087.png)

version 7.0.0 release
replicate by creating new project as below
abp new Acme.BookStore -u blazor --pwa

then run project.  
shrink webpage to narrow version where menu appears on top.

**Comment by enisn** [comment]
It seems it's working on LeptonX Lite v2.1

![leptonxlite-mobille-menu](https://user-images.githubusercontent.com/23705418/229459141-65f1b0d5-157e-4e9e-8b3b-7c5b4401b9ed.gif)

**Comment by siimsep** [comment]
Something is still buggy, just did a new install:
abp new Acme.BookStore -u blazor
And the menu buttons don't respond to anything.

**Comment by enisn** [comment]
> Something is still buggy, just did a new install: abp new Acme.BookStore -u blazor And the menu buttons don't respond to anything.

Can you provide which version are you using?

**Comment by enisn** [comment]
I've just created a new project on v7.1.1 with provided command by you
`abp new Acme.BookStore -u blazor`
and couldn't reproduce the issue:
![leptonxlite-mobile-menu-new](https://user-images.githubusercontent.com/23705418/231156495-7ea17a8e-3ca7-4ced-bdad-0c750c220b47.gif)

**Comment by siimsep** [comment]
Thanks for fast response, very strange issue. 

v7.1.1 / Lepton X Lite 2.1.0 /  Blazorise Icons, Bootstrap5 v1.2.2 / Microsoft.AspNetCore.Components.WebAssembly 7.0.5, DevServer 7.0.4

I'm running the application as mentioned in the guide, .HttpApi.Host and .Blazor as startup projects. Only way I can see the mobile menus is when I delete d-none from Chrome Inspector.

**Comment by witlock** [comment]
I have the same problem. Tried it on windows, Mac, safari, chrome, edge- doesn't work anywhere

**Comment by fxandrei** [comment]
I have the same problem. Blazor Server, tiered.
Just update everything.

**Comment by enisn** [comment]
Finally, I reproduced the issue. It happens when the user is redirected to AuthServer. So this issue happens in mvc ui not in blazor.

We'll fix it and release a patch as soon as possible

**Comment by enisn** [comment]
Since AuthServer doesn't have any menu, mobile menu can't be opened and show anything on "Manage acount" pages. In the main application mobile menu seems working.

![authserver-no-menu](https://user-images.githubusercontent.com/23705418/233920810-c125f16b-6b54-4efd-97d3-7f1d85cf78af.gif)

**Comment by fxandrei** [comment]
Thats great news.

**Comment by witlock** [comment]
Well for us it was on all pages not just on the account one

**Comment by fxandrei** [comment]
> 

Yup. Should work. I think the fix is actually related to the fact that some of the components were separated when using the tiered template (auth, api and blazor)
