### ISSUE TITLE
Static proxy generation issue (ref issue 14114)

### ISSUE THREAD

**Issue by gdunit** [abpframework/abp#15390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP Framework version: 7.0
CLI version: 7.0

The issue reported in [#14114](https://github.com/abpframework/abp/issues/14114) appears to be still present in the latest CLI version (7.0): generic interface methods are not reproduced when service proxies are generated. 

As noted in the above issue, the problem can be worked around by setting the interface namespaces to Volo.Abp.Application.Services - but unfortunately this generates problematic side-effects (any DTOs must be moved to the Abp namespaces as well, otherwise the generated proxies will not recognise the DTOs without manually editing the generated files). 

Additionally, some of my service methods have a return type of Task<ListResultDto<KeyValuePair<Guid, String>>>. When this is converted to a proxy, an additional comma and space are added - Task<ListResultDto<KeyValuePair<Guid, String>>, > which have to be removed afterwards manually.

See reproduction repository listed below which reproduces these issues.

### Reproduction Steps

See [Sample Repository](https://github.com/gdunit/AbpStaticProxiesRepro) for minimal repro.

### Expected behavior

The generated proxies in the sample repro should:
1) Represent the DoMoreStuffAsync() method from the IDoMoreStuff<TDto> generic interface
2) Correctly represent the Task<ListResultDto<KeyValuePair<Guid, string>>> GetMyStuffAsync() method signature correctly from the IImaginaryAppService interface.

### Actual behavior

The generated proxies in the sample repro:
1) Do not include the DoMoreStuffAsync() method from the IDoMoreStuff<TDto> generic interface
2) Incorrectly represent the Task<ListResultDto<KeyValuePair<Guid, string>>> GetMyStuffAsync() method signature by adding a space

### Regression?

This issue was listed as fixed for the milestone 7.0 preview but is present in 7.0 release version of the CLI.

### Known Workarounds

Placing generic interfaces in Volo.Abp.Application.Services namespace and manually altering generated proxy code.

### Version

7.0

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
I will check it
