### ISSUE TITLE
Automapper doesn't work when add maps with `validate: true`

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#15404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

See https://github.com/abpframework/abp/pull/15405

### Version

7.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/15405#issuecomment-1382647493
