### ISSUE TITLE
Abp Lepton theme: left side menu broken: features[featureKey].toLowerCase() undefined

### ISSUE THREAD

**Issue by idreeshaddad** [abpframework/abp#15407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP Framework version: **6.0.1**
Lepton version: **6.0.1**

The project was created using Abp Suite and ran, and this happened:

`ERROR TypeError: Cannot read properties of undefined (reading 'toLowerCase')`
**in file**: `volo-abp.ng.theme.lepton.mjs:1266:42`

Going to that line in the file this is what I found:
```lang-js
const LEPTON_THEME_FEATURES = new InjectionToken('LEPTON_THEME_FEATURES', {
    providedIn: 'root',
    factory: () => {
        const configState = inject(ConfigStateService);
        const featureKey = 'LeptonManagement.Enable';
        const mapFn = features => ({
            
        // The prolem is here: Uncaught ReferenceError: features is not defined
            enable: features[featureKey].toLowerCase() !== 'false',
        });
        return featuresFactory(configState, [featureKey], mapFn);
    },
});
```
**Kindly how do I solve this problem?**

![image](https://user-images.githubusercontent.com/2285974/212448966-58873795-c695-47f5-bb8c-73e50c02af6f.png)

### Reproduction Steps

Create a new project with Abp suite with angular Lepton theme v6.0.1 and just run it.ABP

### Expected behavior

A proper UI without the bug seen in the description section above.
This is taken from the online demo page:

![image](https://user-images.githubusercontent.com/2285974/212449088-c3d62324-ac7d-4409-b5b6-de7ed82e220a.png)

### Actual behavior

```lang-js
Uncaught ReferenceError: features is not defined
    at eval (eval at factory (volo-abp.ng.theme.lepton.mjs:1265:23), <anonymous>:1:1)
    at Object.factory (volo-abp.ng.theme.lepton.mjs:1265:23)
    at R3Injector.hydrate (core.mjs:8719:35)
    at R3Injector.get (core.mjs:8607:33)
    at injectInjectorOnly (core.mjs:4782:33)
    at ɵɵinject (core.mjs:4786:60)
    at inject (core.mjs:4879:12)
    at Object.factory (volo-abp.ng.theme.lepton.mjs:1275:30)
    at R3Injector.hydrate (core.mjs:8719:35)
    at R3Injector.get (core.mjs:8607:33)
```

### Version

6.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

Stackoverflow question link:
https://stackoverflow.com/q/75098055/655605

**Comment by idreeshaddad** [comment]
@maliming is there a timeframe on when you will get to look into this, please?

**Comment by idreeshaddad** [comment]
@maliming Thank you for the prompt response.

@mahmut-gundogdu  is there a timeframe on when you will get to look into this, please?

**Comment by idreeshaddad** [comment]
My client chose Abp Commercial because it is reliable, but I have a demo very soon!
@mahmut-gundogdu Any input is highly appreciated, brother. şimdiden çok teşekkür ederim

**Comment by mahmut-gundogdu** [comment]
I couldn't produce the issue.

`abp new LeptonDemoApp -t app-pro -u angular --theme lepton -v 6.0.2`
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/2217899/214033765-f401ac1d-1fd4-4d2f-be13-4126e7b35e2e.png">

Is there any custom step  ?

I think the only way to appear this error, there is a feature key in features array but the value is undefined.  I have a suggestion, I couldn't tested because  I can't produce but it should works.
I would inject a new function, that works nullsafe

app.module.ts
`
  {
    provide: LEPTON_THEME_FEATURES,
    useFactory: () => {
      const configState = inject(ConfigStateService);
      const featureKey = 'LeptonManagement.Enable';
      const regex = /true/ig;
      const mapFn = features => ({
          enable: regex.test(features[featureKey])
        });
      return featuresFactory(configState, [featureKey], mapFn);
    }
  }
`

this code will fix the error that on the console.log

but defect does not related with this issue. I think backend has some issue. Could you share your result of application configuration,  i think lepton settings are missing.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/2217899/214039583-9155893f-175c-44ae-bcf2-643f3067a834.png">


Also  lastest version of ABP is 7.0 but if you want to use 6.x please use 6.0.2.
the Other topic is, if you are ABP commercial customer, you should use https://support.abp.io/. this issue related with open source sides.

**Comment by idreeshaddad** [comment]
I'm sorry, you are correct. It turns out the solution was created with LeptonX and manually changed to Lepton.
You are also correct, the solution is missing Lepton theme settings:

![image](https://user-images.githubusercontent.com/2285974/214387008-7cb8f59a-ae26-42b2-a36c-fad9a218ecdf.png)

And I'm also missing the Lepton theme settings tab Settings page:

![image](https://user-images.githubusercontent.com/2285974/214387674-2b3056f4-4a5e-4e97-82ab-25d95307e65a.png)

Please advise on what to do to fix the Lepton theme settings?

**Comment by idreeshaddad** [comment]
Good news, I added the missing backend references and settings and now the console error is gone and things are working properly.
Now I'm just missing the theme settings UI in angular:

![image](https://user-images.githubusercontent.com/2285974/214396006-aee7af95-1d27-47f3-b147-0b2b65466390.png)

How do I add this tab?

**Comment by idreeshaddad** [comment]
Found the answer.
In [Settings -> Users](http://localhost:4200/identity/users) gave the `admin` the permissions to Lepton Theme settings.

![image](https://user-images.githubusercontent.com/2285974/214439079-8b350bcd-98de-459a-9665-fc7af1e27481.png)
