### ISSUE TITLE
Fix redirection issue at https://abp.io/documents/

### ISSUE THREAD

**Issue by 4nonym0us** [abpframework/abp#1541]
README.md contains [broken link](https://abp.io/documents/) (which redirects to `https://docs.abp.io/en//Latest/`) to the documentation.
Either use `https://docs.abp.io/en/abp/latest` directly or fix the redirection rule.

**Comment by maliming** [comment]
Thanks, already fixed https://github.com/abpframework/abp/commit/211cd3fe8f90c6b537102f20f71ad7478a4ce0b0
