### ISSUE TITLE
How to test against security via OWASP ZAP tool

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#15418]
Hi,

As I see, there is a post[ABP Commercial Penetration Test Report](https://docs.abp.io/en/commercial/7.0/others/penetration-test-report)  but this is the old version of abp (v6.x). Now Abp v7.0 is released and I want to test the security of this version, how can I make it ?

Can you share me the step to do the test like the AspnetZero [Security Test with OWASP ZAP](https://docs.aspnetzero.com/en/aspnet-core-angular/v11.0.0/Security-Test-Angular) 

Thanks,

**Comment by leonkosak** [comment]
Reports like this are really important for specific customers, which requires that application is as secure as possible.
Testing with OWASP ZAP is blacbox testing. Some customers may ever require whitebox testing (so that can check all application code.

**Comment by EngincanV** [comment]
Hi @volethanh, currently we have an internal issue for creating a penetration test report for v7.0. So, you don't need to make a penetration test, we will do it and share the result in the documentation that you mentioned.

But if you want to still make a penetration test on your own, you can check [this article](https://medium.com/volosoft/running-penetration-tests-for-your-website-as-a-simple-developer-with-owasp-zap-493d6a7e182b) to see what you need to do to perform penetration tests with the OWASP ZAP tool.

**Comment by volethanh** [comment]
Hi @EngincanV ,

Do you have any plan to fix and share result to us? Our customer may need this report when we release and deploy applications using abp 7.0.0 to production

**Comment by EngincanV** [comment]
> Hi @EngincanV ,
> 
> Do you have any plan to fix and share result to us? Our customer may need this report when we release and deploy applications using abp 7.0.0 to production

We will update the [ABP Commercial Penetration Test Report](https://docs.abp.io/en/commercial/7.0/others/penetration-test-report) document, after assessing the penetration test results (all results are not correct, some of them might be false-positive or negative, for instance. so we need to examine them one by one). 

I've taken note of this and after updating the document I'll inform you.

**Comment by EngincanV** [comment]
@volethanh I've started updating the penetration test report. You can see the test results from [this PR](https://github.com/abpio/abp-commercial-docs/pull/336).
