### ISSUE TITLE
Is there a way to use different JsonSerializer implementation in different modules?

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#15422]
For now ABP provides two JsonSerializer implementations: 

- `SystemTextJson` by `Volo.Abp.Json.SystemTextJson`
- `Newtonsoft` by `Volo.Abp.Json.Newtonsoft`

In my module, I need to use a feature that only exists in Newtonsoft, so I use `Volo.Abp.Json.Newtonsoft` in my module, but once my module was used by an application, the JsonSerializer in that application will be replaced (globally) by Newtonsoft as well, but without  user noticed. I think it's some kind of dangerous.

So is it possible to use one in one module, and use the other one in another module?  Or use JsonSerializer in a module-scope way?

**Comment by maliming** [comment]
Currently not possible.

**Comment by wakuflair** [comment]
My workaround is using Newtonsoft directly in my module, instead of depending on `Volo.Abp.Json.Newtonsoft`.
In this way, I can prevent overriding the IJsonSerializer of the application.
