### ISSUE TITLE
Microservice Demo - How permissions works?

### ISSUE THREAD

**Issue by Klainer** [abpframework/abp#1543]
Hello,
I have one question about Permission system in Microservice demo project. 
On  image below you have 3 permission groups for each module: (Blog, Product, Identity).

How and where are this pemission sections created / defined ?
I suppose that in Identity module is referencing modules Blog and Product and they are sharing one database where are permissions stored.

When I send request to Product Microservice how are specific permissions checked for user Request? Is service somehow connected to Identity Service and Permssions DB ?

----GetProductData-->[ProductMicroServiceApiEndpoint] (How product miroservice check User Premission, does service calll another Microservice by HTTP ?) ??

What is premission check flow ?

![image](https://user-images.githubusercontent.com/2507183/62006513-91e1dd80-b141-11e9-8149-c037a6b9b9fb.png)

Thanks!

**Comment by Klainer** [comment]
I maybe got It. Each microservice is puzzled form application modules which depends on multiple core frameworks modules ig. `AbpAspNetCoreMvcModule`  which depends `AbpAspNetCoreModule `which depends on `AbpAuthorizationModule `.

Each microservice have an DB connection string to Identity Database :

` "Default": "Server=localhost;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true",`


So each microservice have conenction to multiple DB which one is IdentityDB. So in product microservice we can manage permission due to generic codebase in framewrok modules which are contained.

**Comment by hikalkan** [comment]
>I suppose that in Identity module is referencing modules Blog and Product and they are sharing one database where are permissions stored.

This would break microservice independence. None of these modules depend on another. They both depends on the Volo.Abp.Authorization package which provides services to check permissions.

As an interesting design, this modal dialog is not defined in the identity module! :)
It is inside the [permission-management](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Web/Pages/AbpPermissionManagement/PermissionManagementModal.cshtml) module. It also doesn't depend on the identity module. 
This module has a single table (entity) in its separated dbcontext ([see](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.EntityFrameworkCore/Volo/Abp/PermissionManagement/EntityFrameworkCore/PermissionManagementDbContext.cs#L14)).

In new ABP modularity design, every module may have its own database. But to keep it simple, I shared the MsDemo_Identity database among identity, permission-management, audit-logging, setting-management and so on. Having too many database is hard to maintain, but still possible.

We will write more document to explain all these, by time.

**Comment by Klainer** [comment]
Thanks for clerifying!
I have one minor question. In separed dbContext which you mention you are using attribute for naming conection strings:
` [ConnectionStringName(AbpPermissionManagementConsts.ConnectionStringName)]` = `"AbpPermissionManagement"` in this case..

But for exapple in Blog microservice you have only these twon connection string names (Default, Blogging):

```
"ConnectionStrings": {
    "Default": "Server=localhost;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true",
    "Blogging": "mongodb://localhost|MsDemo_Blogging"
  },
```

How does the module know which connection string name should use ? I do not see any 'AbpPermissionManagement' connection string name.

Thanks !

**Comment by hikalkan** [comment]
If it can not find AbpPermissionManagement, it fallbacks to Default :)
That makes it flexible.

**Comment by rwecho** [comment]
@hikalkan one little question, if each micro service has its own permission database and we want to have a center modal dialog to manage all the permissions in one place, there must be a registration or service discovery mechanism involved. Is there something like this built into ABP, or do we have to implement it ourselves?

**Comment by hikalkan** [comment]
>if each micro service has its own permission database

We don't suggest this. Otherwise, you can not create a single modal to manage all permissions in the system easily. We've thought that while designing it, I think storing permissions in a single database for all microservices is better. A microservice should not be responsible for its permissions, audit logs, settings... etc.

If you want to implement it like you want, you should implement it yourself.

**Comment by vijay2358** [comment]
@hikalkan  - we are using micro service in applications like you mentioned above  (Blog, Product, Identity)

Here our solution was designed 
1.	Identity API Service  scope as “Identity”
2.	Blog API Service  scope as “Blog”
3.	Product API Service  scope as “Product”

On top it – Gateway API  included all  scopes ((Blog, Product, Identity)  by referring adding .ApplicationContracts nuget

Now All WEBUI  calling Gateway API along with scope (Blog, Product, Identity),

Issue  permissions grants showing in all applications API.  we are expecting to see each permission should be filter by scope/resource but it is coming all permissions from all three modules even though calling by scope..

Gateway --> API – same data coming from all UI apps 

"auth": {
    "policies": {
      "AbpIdentity.Roles": true,
      "AbpIdentity.Roles.Create": true,
      "AbpIdentity.Roles.Update": true,
      "AbpIdentity.Roles.Delete": true,      
      "Blog.Business": true,
      "Blog.Business.Edit": true,      
      "Product.Test": true,
      "Product.Test.Create": true
    },
    "grantedPolicies": {}
  }
-----------------------------This should be filter if calling GATEWAY API from Blog UI 
****Blog**********
"auth": {
    "policies": {     
      "Blog.Business": true,
      "Blog.Business.Edit": true   
    },
    "grantedPolicies": {}
  }
-----------------------------This should be filter if calling GATEWAY API from Product UI
****Product**********
"auth": {
    "policies": {
      "Product.Test": true,
      "Product.Test.Create": true
    },
    "grantedPolicies": {}
  }
-----------------------------This should be filter if calling GATEWAY API from AbpIdentityUI
****AbpIdentity**********
"auth": {
    "policies": {
      "AbpIdentity.Roles": true,
      "AbpIdentity.Roles.Create": true,
      "AbpIdentity.Roles.Update": true,
      "AbpIdentity.Roles.Delete": true
    },
    "grantedPolicies": {}
  }
------------------------------------
	
Please let me know if you need more info.
