### ISSUE TITLE
About password visibility button icon

### ISSUE THREAD

**Issue by roc916** [abpframework/abp#15430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We appear to be violating 'mainstream' design.

The icon should not show the current state, since the text input already clearly shows the state.

I think we should exchange `"fa fa-eye"` with `"fa fa-eye-slash"`.

abp.io :

<img width="381" alt="image" src="https://user-images.githubusercontent.com/12685126/212824358-6f2b76a8-c4da-406f-9943-a90480feb003.png">

<img width="383" alt="image" src="https://user-images.githubusercontent.com/12685126/212824392-81b52669-6857-42ba-be2c-80cd803ac1bb.png">

Microsoft Edge:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/12685126/212823507-334c228e-dd68-477c-9c73-637d6cedc0b7.png">

<img width="816" alt="image" src="https://user-images.githubusercontent.com/12685126/212823874-787322e2-5fcb-4fe0-b588-5c7fa17b02d7.png">

Twitter:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/12685126/212823769-df1fe6fb-1ec3-4aa4-b087-d641cd6ff50d.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/12685126/212823822-017e20b9-b892-4f8c-b8bc-e4e8c88771cd.png">

...

### Version

7.0.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by onurpicakci** [comment]
What do you think about that? @ebicoglu
