### ISSUE TITLE
Pre-Defined Events - Etos not getting mapped after database set operations 

### ISSUE THREAD

**Issue by NunoGamaVieira** [abpframework/abp#15439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to use pre-defined events to send some data after creating an entity.  The thing is my entity Id is an int that is set by the database. Since the mapping for Eto is being done before the entity is saved to database, i am not getting it set on the event handler. 
I believe there is a reason why you doing it before and maybe it is the delete or something else. My question is if this is something you would look into or should i be working around it and if there is anything that i am not thinking about here. 

### Describe the solution you'd like

As a workaround i have extended your abpdbcontext class and used your EntityChangeEventHelper class to re-publish the event with a new mapped dto after the SaveChangesAsync.

        public override async Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
        {
            int returnValue = await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
             foreach (EntityEntry entityEntry in AddedEntities)
            {
                EntityChangeEventHelper.PublishEntityCreatedEvent(entityEntry.Entity);
            }
            AddedEntities.Clear();
            foreach (EntityEntry entityEntry in ModifiedEntities)
            {
                EntityChangeEventHelper.PublishEntityUpdatedEvent(entityEntry.Entity);
            }
            ModifiedEntities.Clear();
            return returnValue;
        }

        List<EntityEntry> AddedEntities = new List<EntityEntry>();
        List<EntityEntry> ModifiedEntities = new List<EntityEntry>();
        protected override void ChangeTracker_Tracked(object sender, EntityTrackedEventArgs e)
        {
            base.ChangeTracker_Tracked(sender, e);
            if (e.Entry.State.Equals(EntityState.Added))
                AddedEntities.Add(e.Entry);
            if (e.Entry.State.Equals(EntityState.Modified))
                ModifiedEntities.Add(e.Entry);
        }

**Comment by maliming** [comment]
> my entity Id is an int that is set by the database

You can do this in this case, our default design does not handle it for now.

**Comment by NunoGamaVieira** [comment]
Thanks for your reply.
Can you elaborate abit more on why are the convertion to eto made before the entity is saved on the transaction ? 
I can't find it on the documentation and it is also misleading as it says the events are published right after the entity is created.
If there is no real reason, would you consider this on your roadmap ?  

Thanks again
