### ISSUE TITLE
Create a community article to explain converting the CURD modal to a view page.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#15449]

**Comment by subhranshu00** [comment]
We are facing lot of issue when developing without modal pop-up. Can I get a sample BookStore app created with Asp Net MVC razor app?

**Comment by subhranshu00** [comment]
Hello Maliming,

Can I get the sample solution or documentation without having modal pop-up?

Regards,
Subhranshu

**Comment by maliming** [comment]
hi

I'll provide docs and examples soon.
