### ISSUE TITLE
abp generate-proxy [API Not Available] error after upgrading to ABP 7.0

### ISSUE THREAD

**Issue by lukagalovic** [abpframework/abp#15447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After updating to version 7.0, I am getting error after trying to execute command: `abp generate-proxy -t ng`.

Error: `[API Not Available] Request to https://localhost:44319/api/abp/api-definition is unsuccessful. Please double-check the URL in the source project environment and make sure your application is up and running.`
I also tried `abp generate-proxy -t ng -u https://localhost:44319` but I get same error.

When I send request from Swagger or Postman I get successful response.

My `environment.ts`

```
import { Environment } from '@abp/ng.core';

const baseUrl = 'http://localhost:4200';

export const environment = {
    production: false,
    application: {
        baseUrl,
        name: 'LicGen',
        logoUrl: '',
    },
    oAuthConfig: {
        issuer: 'https://localhost:44319/',
        redirectUri: baseUrl,
        clientId: 'LicGen_App',
        responseType: 'code',
        scope: 'offline_access LicGen',
        requireHttps: true,
    },
    apis: {
        default: {
            url: 'https://localhost:44319',
            rootNamespace: 'LicGen',
        },
    },
    localization: {
        defaultResourceName: 'LicGen'
    },
} as Environment;
```

### Version

7.0.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by muhammedaltug** [comment]
How did you start HttpApi.Host project? You should start with dotnet run command. You can check [document](https://docs.abp.io/en/abp/latest/UI/Angular/Service-Proxies#known-limitations)

**Comment by lukagalovic** [comment]
Tried it now and it works, thank you.
Strange it worked till now.
