### ISSUE TITLE
ISoftDelete cannot use customattributes [Column] 

### ISSUE THREAD

**Issue by EastRedBlack** [abpframework/abp#15468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ISoftDelete cannot use customattributes [Column]  

result: Unknown column 'o.IsDeleted' in 'field list

find source code in  columname defined by  nameof(IsDeleted)

### Version

6.03

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

empty

**Comment by realLiangshiwei** [comment]
**Reproduction Steps**

**Comment by EastRedBlack** [comment]
![图片](https://user-images.githubusercontent.com/28585139/213638515-1b1b36a6-5a45-4327-a2ff-14b4c8305096.png)
override this method fix this version bug its not good idea

**Comment by EastRedBlack** [comment]
![图片](https://user-images.githubusercontent.com/28585139/213638826-8944947b-54b7-47f2-bb91-2540e588bf2a.png)
that's why this issue open .
source code AbpEntityTypeBuilderExtensions.cs
![图片](https://user-images.githubusercontent.com/28585139/213639658-7a4dab30-6975-4870-920a-4470c51671f8.png)

**Comment by realLiangshiwei** [comment]
You can use the Fluent API to override the `IsDelete` column name.

For example:
```csharp
builder.Entity<Book>(b =>
{
    b.ApplyObjectExtensionMappings();
    b.Property(book => book.IsDeleted).HasColumnName("is_deleted");
});
```
