### ISSUE TITLE
CMS-KIT : There is a problem with the table in the page feature

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#15460]
When I created a page using the CmsKit pages feature with the AbpCommercialTest project, it did not look properly when I added a table.
Preview screenshot:
![image](https://user-images.githubusercontent.com/58659931/213391138-158bcf5f-f2f7-42c8-8682-9bd02c05be51.png)
Page screenshot:
![image](https://user-images.githubusercontent.com/58659931/213391183-e25d57bd-c28c-46ed-a02a-d1fe77eeb90a.png)

**Comment by EngincanV** [comment]
`tui-editor` uses custom CSS in its preview tab. There is nothing we can do about this. A user can add a page record from the admin application and want to see it on a public website. In such cases, we can't align styles for both applications. So, I close the issue.
