### ISSUE TITLE
Angular - Improvement issues

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#15467]
**App:** Angular - MongoDB v7.0.1

- The marked area display doesn't seem to be needed. This situation is not available on other pages.
![image](https://user-images.githubusercontent.com/99716457/213620715-00a71f41-453a-4ee6-9606-8c1850ae7ba4.png)

- There is very little space between the search field and the table.
![image](https://user-images.githubusercontent.com/99716457/213621370-30c06159-7781-412a-9eda-2772a2838f7e.png)

**Comment by mahmut-gundogdu** [comment]
I've checked that the settings page is correct, however additional ABP pages should use the <abp-page/> component. I have verified that all ABP commercial pages utilize the <abp-page/> tag.

**Comment by ebicoglu** [comment]
LeptonX v2.0.2 released.
please check if this issue has been fixed
