### ISSUE TITLE
Headers paralyze ids4

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1546]
1. Create a mvc tiered solution with `abp new MyProject -t mvc --tiered`
2. Run `MyProject.DbMigrator`
3. Run `MyProject.IdentityServer`
4. Request `https://localhost:port/connect/token` with these headers:
```
  Origin: http://127.0.0.1:33086
  Referer: http://127.0.0.1:33086/appservice/appservice?t=1564165664142?load
```
5. Ids4 takes long time to respone 404, and then it cannot handle other request any more.

It happens on Abp vNext 0.18.1, fail to reproduce in https://demo.identityserver.io

See: https://github.com/IdentityServer/IdentityServer4/issues/3485#issue-473491399

**Comment by maliming** [comment]
Microsoft.Extensions.Caching.Redis  this package seems to have problems.

Try to modify it as follows

![image](https://user-images.githubusercontent.com/6908465/62099080-874d5280-b2bf-11e9-93bf-ee64988e3435.png)

```
context.Services.AddDistributedRedisCache(options =>
context.Services.AddStackExchangeRedisCache(options =>


<PackageReference Include="Microsoft.Extensions.Caching.Redis" Version="2.2.0" />
<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="2.2.5" />
```

**Comment by gdlcf88** [comment]
It is fixed, thx.
