### ISSUE TITLE
Deploy to ISS as sub application

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#15480]
Hi.

I have created pure new ABP project (version 7.0.0) as `abp new Sebit.CIS -t app -u angular`
Opened it in visual studio, changed connection string and run it.
It worked as expected. Swagger showed up. Login in and logout worked ok.

After that i created new sub app (named **test**) in IIS application server manager and deployed (publish) server-side part to 
ISS folder of that sub app.
 
Then i tried to access server-side application as https://someapp.domain.si/test. Application started, but i noticed some problems:

**1. Swagger is not working**
(missing "/test/" in json uri)

![image](https://user-images.githubusercontent.com/2194876/213698481-8d08c0ce-5eaf-43b8-ba73-0a5fc285df47.png)

**2. On login's page "Register" and "Remember me" links are ok:**
 
![image](https://user-images.githubusercontent.com/2194876/213699249-b719ee5a-bda8-4dc3-b4ac-8167453f1e5e.png)

![image](https://user-images.githubusercontent.com/2194876/213699429-89555807-ce96-40be-aaa4-65fb29d4b7b8.png)

**3. After login menu links for "My account" and "Logout" are wrong (without "/test/"),**

![image](https://user-images.githubusercontent.com/2194876/213700178-f244539c-ef54-483a-b0db-583c2f9be6a5.png)

![image](https://user-images.githubusercontent.com/2194876/213700385-7f0a6327-8f08-49ec-a169-932aa9e793c3.png)

So, my question is:

Does ABP template support this deployment scenario ?
Why some parts (register, remember me) works fine, some (swagger, logout) not ?

Is there something i should configure ? Some parameters in web.config maybe ? On IIS ?

Please advice.

Edvin

**Comment by muhlisatac** [comment]
Did you configure the url in appsettings.json ?

**Comment by sebitsi** [comment]
@muhlisatac Yes i did.

```
{
   "Urls": "https://someapp.domain.si/test
}
```

**Comment by sebitsi** [comment]
Does anyone else have similar experiences?

**Comment by realLiangshiwei** [comment]
>. Swagger is not working

It's not related to ABP, you can get help from https://github.com/domaindrivendev/Swashbuckle.AspNetCore

> After login menu links for "My account" and "Logout" are wrong (without "/test/"),

I will check it.

**Comment by realLiangshiwei** [comment]
We will fix it in the next version.

You can try:

```csharp
public class MyProjectNameMenuContributor : IMenuContributor
{
    public async Task ConfigureMenuAsync(MenuConfigurationContext context)
    {
        if (context.Menu.Name != StandardMenus.User)
        {
            return Task.CompletedTask;
        }

        var manage = context.Menu.GetMenuItem("Account.Manage");
        var logout = context.Menu.GetMenuItem("Account.Logout");

        manage.Url = "test"+ manage.Url.TrimStart('~');
        logout.Url = "test"+ manage.Url.TrimStart('~');
    }
}
```

**Comment by sebitsi** [comment]
@realLiangshiwei Thanks for your suggestion.

Your code has bugs. I modified it a little:

```
public class MyProjectNameMenuContributor : IMenuContributor
{
    public async Task ConfigureMenuAsync(MenuConfigurationContext context)
    {
        if (context.Menu.Name != StandardMenus.User)
        {
            return Task.CompletedTask;
        }

        var manage = context.Menu.GetMenuItem("Account.Manage");
        var logout = context.Menu.GetMenuItem("Account.Logout");

        manage.Url = "~/test"+ manage.Url.TrimStart('~');
        logout.Url = "~/test"+ logout.Url.TrimStart('~');
    }
}
```
But this is simple.  There is another problem. 
When i tried to update personal data, API PUT request URI is wrong (test segment is missing).

![image](https://user-images.githubusercontent.com/2194876/214824794-91a340ac-a8e6-4ef1-a487-540a5f016055.png)

So i think ABP base template is not yet suitable to deploy behind  a proxy or as an IIS sub-application.

I suggest you to try implement configuration defined by ASP.NET Core team in [Proxy and load balancers](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0) document.

This will be hude benefit using ABP.

What do you think ?

**Comment by realLiangshiwei** [comment]
> When i tried to update personal data, API PUT request URI is wrong (test segment is missing).

ABP supports sub-application. you can try:

```csharp
Configure<AbpLayoutHookOptions>(options =>
{
      options.Add(LayoutHooks.Head.Last,
      typeof(AbpApplicationPathViewComponent));
});
```

**Comment by sebitsi** [comment]
@realLiangshiwei Thanks.

This configuration works.

Why this is not enabled by default ?
As part of application template or inside `Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared` module registration.

Variable abp.appPath should be allways initialized if MVC or razor pages are used.

Or there is another reason not to ?
