### ISSUE TITLE
Is there any plan that CreatorId compatible the type long  recently?

### ISSUE THREAD

**Issue by ty793941** [abpframework/abp#15498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello,I was migratored to abp vnext 7.0 , so i have lot of long types in `CreatorId` of my db tables .
I have tried many ways , and I found the same issue in abp issues, and got the answer **is not possible to change it.**

The Same Column likes CreatorId, LastModifierId and DeleterId.
```C#
	/// <inheritdoc />
	public virtual Guid? CreatorId { get; protected set; }
```
The Same Issues:
> _How to change CreatorId LastModifierId CreatorId from guid type to long type #10287
> Change the CreatorId inherit from Audited class from Guid to Int #1293_

### Describe the solution you'd like

I want to know that Is there any plan that the CreatorId to compatible the type long , or it has an other way to compatible the type long. Thank You!

**Comment by ty793941** [comment]
@maliming  @hikalkan

**Comment by maliming** [comment]
hi

There are no plans to make such a change. It breaks too much things.

**Comment by ty793941** [comment]
ok,thank you any well, that's a pity! And  I found that the column name has changed too. the column name was "CreatorUserId",but now the column name is "CreatorId". that's break too.

**Comment by ming2882** [comment]
太可惜了，为什么不支持呢，guid这么好吗
