### ISSUE TITLE
Static js proxys not found

### ISSUE THREAD

**Issue by CherryGoose** [abpframework/abp#15490]
Hello! Im trying to implement static js proxys and i have encountered a problem. I follow the guide as per v.6 documentation about implementing static proxys and after following every step all proxys are successfully generated. I Use v6 tiered solution with modules.
My problem is that while the c# static proxys work fine in module as well as in main project the js one return 404 not found error when im trying to call methods in web. I have tried to generate js proxys in Smain and in MOne web project. I Have tried to adding config to disable dynamic js proxys in Smain and in MOne web project. Result is still 404
Steps to reproduce:
1 Create tiered solution (Lets call it Smain)
2 Add new module to it lets(call it MOne)
3 Create a CRUD service in MOne module(db provider does not matter, i use sqlite for simplicity, entity can have only one parameter name and Id) 
4 Create a CRUD service in Smain (do the same as MOne service)
5 Add index.js files to main pages of MOne and Smain pages, add sample code to display table that gets data from corresponding services
6 Generate C# static proxys, change Configure services as per documentation
7 Add migrations, update db
8 Start project and check that api endpoints in swagger work as intendent
9 Add to appsettings redirection addresses for web project
10 Generate js proxys 
11 Try opening page with table

**Comment by CherryGoose** [comment]
On a side note: in documentation here https://docs.abp.io/en/abp/latest/UI/AspNetCore/Static-JavaScript-Proxies#disabling-dynamic-javascript-proxies it does to specify where you should disable dynamic javascript proxys, i assumed web.

**Comment by realLiangshiwei** [comment]
Please share a repo that can reproduce the problem.

**Comment by CherryGoose** [comment]
I have reserved port for api calls in web appsettings, that fixed the issue. Thank you. I'll try to post a repo with example if you need it. But issue is resolved.
