### ISSUE TITLE
Localization missing Saas Dashboard and Account Claims

### ISSUE THREAD

**Issue by ftornberg** [abpframework/abp#15500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Account\angular\projects\identity\src\lib\components\claim-modalclaim-modal.component.html, line 26, Localization is missing on "Value" 

In Saas\angular\projects\saas\src\lib\components\widgets\latest-tenants-widget.component.html, line 9, Localization is missing on "Latest tenants"

### Version

6.0.1

### User Interface

Angular

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by muhammedaltug** [comment]
We fixed the issue. The fix will available with the next version of 6.0 7.0 7.1
