### ISSUE TITLE
Cli add-module command migration needs to specify the startup project.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1551]
![image](https://user-images.githubusercontent.com/6908465/62109950-f175ef80-b2df-11e9-9d53-09f544f86e85.png)

**Comment by vnetonline** [comment]
so i have to use new CLI the production version 18.0.1 wont work??

**Comment by maliming** [comment]
You can manually migrate first.

**Comment by vnetonline** [comment]
you mean install the module and run update-database manually

**Comment by maliming** [comment]
Now the add-module command can add new modules just can't be migrated, you can migrate manually.

**Comment by vnetonline** [comment]
@maliming I ran the following 

```
PM> Add-Migration 'Added_Blogging_Module'
To undo this action, use Remove-Migration.
PM> update-database
Applying migration '20190730095802_Added_Blogging_Module'.
Done.
```

which added the migration and updated the database. I can see the Blogging modules tables in the database now so the fix you have just done will be out in 0.19.0.0?

**Comment by vnetonline** [comment]
Okay now that i have done that I can't see the Management menu to setup the Blog

<img width="533" alt="Screen Shot 2019-07-30 at 8 16 50 pm" src="https://user-images.githubusercontent.com/15242923/62121510-16ca2400-b307-11e9-9e76-64c8e13ac2a1.png">

**Comment by vnetonline** [comment]
Okay got it had to give permission to the admin user

<img width="533" alt="Screen Shot 2019-07-30 at 8 16 50 pm" src="https://user-images.githubusercontent.com/15242923/62122011-1ed69380-b308-11e9-903d-1f2800e34d43.png">
