### ISSUE TITLE
How can I add Encoder to JsonAuditSerializer?

### ISSUE THREAD

**Issue by ycc3000** [abpframework/abp#15532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to override CreateJsonSerializerOptions, but it throw Exception.
System.InvalidOperationException:“This JsonSerializerOptions instance is read-only or has already been used in serialization or deserialization.”

[Dependency(ServiceLifetime.Singleton, ReplaceServices = true)]
public class JsonAuditSerializer : Volo.Abp.Auditing.JsonAuditSerializer
{
    public JsonAuditSerializer(IOptions<AbpAuditingOptions> options) : base(options)
    {
    }

    protected override JsonSerializerOptions CreateJsonSerializerOptions()
    {
        var options = base.CreateJsonSerializerOptions();
        options.Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping;
        return options;
    }
}

### Describe the solution you'd like

I want to set Encoder property.

**Comment by maliming** [comment]
hi

You can try something like this, Also consider the `JsonSerializerOptionsCache`.

```cs
var options = new JsonSerializerOptions (base.CreateJsonSerializerOptions())
{
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
}
```

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.-ctor?view=net-7.0#system-text-json-jsonserializeroptions-ctor(system-text-json-jsonserializeroptions)

**Comment by ycc3000** [comment]
successfully, thank you :)
