### ISSUE TITLE
  "code": "Volo.Authorization:010001",   "message": "Authorization failed! Given policy has not granted.",

### ISSUE THREAD

**Issue by sherlockQcQ** [abpframework/abp#15537]
### Description

Abp Version="6.0.0"
I created a project template with '-ui None' ,After I start the project, I get the token via '/connect/token'，
The request parameters are as follows：
{
    client_id: 'BlogServer_App',
    grant_type: 'password',
    username: 'admin',    
    password: '1q2w3E*'
}
![屏幕截图 2023-01-29 235937](https://user-images.githubusercontent.com/61469754/215338705-03a539e8-0b14-4902-92b6-3a866e9241bd.jpg)

I tried to put the token in 'Header Authorization(type bearer)' and access '/api/identity/roles/all', but got an error:
[23:27:57 WRN] ---------- RemoteServiceErrorInfo ----------
{
  "code": "Volo.Authorization:010001",
  "message": "Authorization failed! Given policy has not granted.",
  "details": null,
  "data": {},
  "validationErrors": null
}

[23:27:57 WRN] Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.
![屏幕截图 2023-01-29 235958](https://user-images.githubusercontent.com/61469754/215338719-f733952d-e32a-4b69-b391-623c08dbd0b7.jpg)

I look in the template ‘OpenIddictDataSeedContributor.cs'，scopes includes everything by default，I don't know if this is a bug or if I made a mistake，I would like to ask, how do I get a token in the default template to access the default api of the system，
AuthorizationCode？Or because 'client_id: XX_App' generates a policy error,This problem bothering me. It is my first time to use the issues function. Please forgive me if I use it wrong!tks!

**Comment by maliming** [comment]
Add full scopes, eg `roles`.

**Comment by sherlockQcQ** [comment]
[thank you for response](javascript:;)!  I checked the template in the 'OpenIddictDataSeedContributor. cs' file, create a' XXX_App ', the parameters' scopes already contains all 'Permissions. Scopes', I have not changed the default template, Do you mean specify 'scopes' in '/connect/token'?
![屏幕截图 2023-01-30 091809](https://user-images.githubusercontent.com/61469754/215368524-a3a779e4-15fb-4359-9f70-32dfdcbee0b8.png)
![屏幕截图 2023-01-30 091847](https://user-images.githubusercontent.com/61469754/215368530-6b801562-5b88-4c90-a4ad-a00ce686c1dd.png)

**Comment by realLiangshiwei** [comment]
`scope` instead of `scopes`

![image](https://user-images.githubusercontent.com/16813853/215368538-2d878574-7f98-4d61-a74e-cddce58f3012.png)

**Comment by sherlockQcQ** [comment]
tks! After I add 'scope :BlogServer', the token can access the' role 'Api. Do I always add' scope 'requests to get the token? Most of the code I've seen shared in the forums doesn't have this parameter added to it, and it also has access to the system's default Api. But after I removed the "scope" parameter, I couldn't access the default Api

**Comment by sherlockQcQ** [comment]
> `scope` instead of `scopes`
> 
> ![image](https://user-images.githubusercontent.com/16813853/215368538-2d878574-7f98-4d61-a74e-cddce58f3012.png)

tks! After I add 'scope :BlogServer', the token can access the' role 'Api. Do I always add' scope 'requests to get the token? Most of the code I've seen shared in the forums doesn't have this parameter added to it, and it also has access to the system's default Api. But after I removed the "scope" parameter, I couldn't access the default Api

**Comment by realLiangshiwei** [comment]
https://oauth.net/2/scope/
Scope is a mechanism in OAuth 2.0 to limit an application's access to a user's account
