### ISSUE TITLE
Extended entities will become null if efcore queries with AsNoTracking

### ISSUE THREAD

**Issue by zhangtingwz** [abpframework/abp#15546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello sir, nice to meet you, I am a student studying ABP
In my TestEntityRepository，i write this code 
`
  public async Task<IEnumerable<IdentityUser>> QueryUser()
        {

            var db = await GetDbContextAsync();
            var query = db.Users.AsQueryable();
            return query.Skip(input.SkipCount).Take(input.MaxCount).AsNoTracking().ToList();
        }
`
Because of the amount of data, I wanted to speed up efcore queries with AsNoTracking

sorry img not upload

`query.ToList().First().ExtraProperties
Count = 4
    [0]: Key = "qqq"
    [1]: Key = "Avatar"
    [2]: Key = "IdCard"
    [3]: Key = "UserType"
query.ToList().First().ExtraProperties["IdCard"]
"45678"
query.AsNoTracking().ToList().First().ExtraProperties["IdCard"]
null
`

### Describe the solution you'd like

I wonder if AsNoTracking can be used for queries and the expansion of the entity can be displayed after AsNoTracking

**Comment by maliming** [comment]
You can't get `ExtraProperties` without `Tracking`.

https://github.com/abpframework/abp/blob/e92ef616c135c1c61a5d3ca705baf2097ae3c3b9/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L239

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
