### ISSUE TITLE
When installing the blogging module the packages are not loaded in wwwroot/libs folder 

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1554]

**Comment by vnetonline** [comment]
The following packages are not loaded when you install the Volo.Blogging Module via the ABP CLI 

codemirror
highlight.js
markdown-it
owl.carousel
squire-rte
to-mark
tui-code-snippet
tui-editor

I have added this to my packages.json and even when i run `dotnet restore` and ` yarn` these are not downloaded to the wwwroot/libs folder

```
{
  "version": "0.1.0",
  "name": "volo.blogtestapp",
  "private": true,
  "dependencies": {
    "@abp/aspnetcore.mvc.ui.theme.basic": "^0.6.6",
     **"@abp/blogging": "^0.6.6"**
  }
}
```

Do we have to install the following manually, if so how ???

**Comment by vnetonline** [comment]
@maliming @hikalkan 

Any comments on this one ?

**Comment by hikalkan** [comment]
Run gulp after yarn.

But we should check why everything didn't happen automatically. @yekalkan can u check?

**Comment by yekalkan** [comment]
![image](https://user-images.githubusercontent.com/5793291/62351288-c2dd5c00-b50d-11e9-80a8-d75718709eeb.png)

I've run the following commands, not done anything else (even not opened the solution)
`abp new Acme.BookStore`
`abp add-module Volo.Blogging`

**Comment by vnetonline** [comment]
Which version of visual studio are you using I am using 2019

Doesn't work that way for me

**Comment by vnetonline** [comment]
What version of ABP CLI are you using I am using 0.18.1

**Comment by vnetonline** [comment]
When i run the commands as mentioned by @yekalkan this is what i get 

I am running Version 0.18.1.0

<img width="1528" alt="Screen Shot 2019-08-05 at 11 24 56 am" src="https://user-images.githubusercontent.com/15242923/62432574-d7bb2900-b773-11e9-921b-4d754c5b0773.png">

Looks like there is an error with Yarn followed by an error with not being able to Add and run migrations

**Comment by vnetonline** [comment]
Okay Git wasn't installed on the command line so Yarn was failing to grab from packages from git repository

it is working now expect for the Add and running migrations which @maliming  has fixed in which should hopefully be in the next release so we can set the startup project.
