### ISSUE TITLE
Auto-logout not working anymore in ABP 7.0

### ISSUE THREAD

**Issue by ArneCools** [abpframework/abp#15552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP 7.0.0 Blazor Server Tiered - Basic theme

When token expires, the user is not logged out, but instead, every permission returns unauthorized. "CurrentUser.IsAuthenticated" still returns 'true' in blazor

Error in Host module: 
`Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: '30-01-2023 12:01:53', Current time: '30-01-2023 12:12:25'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
`

Questions:

- How can I log out the user in de front end (blazor server) when token has expired
- De default expiration time is only 1 hour, how can I change this to something higher?

Best regards

### Reproduction Steps

- Login into Blazor AP
- Wait until token expires

### Expected behavior

- Log the user out
- OR redirect to login

### Actual behavior

- You stay logged in, but permissions don't work anymore

### Regression?

This worked in ABP 6

### Version

7.0.0

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> De default expiration time is only 1 hour, how can I change this to something higher?

**builder.SetAccessTokenLifetime(TimeSpan.FromSeconds(10));**
```cs
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<OpenIddictBuilder>(builder =>
    {
        builder.AddValidation(options =>
        {
            options.AddAudiences("MyProjectName");
            options.UseLocalServer();
            options.UseAspNetCore();
        });
    });

    PreConfigure<OpenIddictServerBuilder>(builder =>
    {
        builder.SetAccessTokenLifetime(TimeSpan.FromSeconds(10));
    });
}

```
