### ISSUE TITLE
When changing the phone number in the profile, the email address must first be verified again

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#15554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have selected in the configuration that the phone number must be verified.

When I change the phone number in the profile and then press "submit", the email address must first be verified again before I can verify the Phone number (but I did not change the email address and it was already valid before).

### Reproduction Steps

1. Open personal info (with already verified email & phone number)
2. Change phone number
3. Press "Submit" button

### Expected behavior

I expect that only the phone number needs to be verified and that the button for this appears.

### Actual behavior

Instead of the phone number, the email address must be verified first.
After verifying the email address, the button to verify the phone number will appear.

### Version

7.0.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

It seems you are using ABP commercial.
Please get help on https://support.abp.io/
