### ISSUE TITLE
Entering invalid phone number locks you out of the system

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#15555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user enters an invalid phone number in the profile under "Personal info" and does not confirm it there, he will not be able to login the next time.

Reason for this: The phone number has to be verified, but this is not possible with a wrong number and the text field for this is readonly.

Hint: 
- The settings "Require confirmed phone number" and "Allow users to confirm their phone number" are activated.
- Very likely there is the same problem with the mail address.

By the way, very useful would be the validation of the phone number (e.g. whether the country code was specified). Otherwise, when using the Twilio module, you run into an exception with an invalid formatting.

### Reproduction Steps

1. Activate the following settings under "Identity Management": "Require confirmed phone number" and "Allow users to confirm their phone number" 
2. Change the phone number of a user in the "Personal infos".
3. Do NOT verify phone number and log out the user
4. Login again with this user
5. The phone number would have to be verified, but since it was entered incorrectly, the code never arrives. The number cannot be changed in this form (readonly).

### Expected behavior

The user should be able to correct the number there.

### Actual behavior

Field is readonly, number cannot be changed

### Version

7.0.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

Remove "readonly" or set readonly="false" for the PhoneNumber field:

`<input type="text" id="PhoneNumber" name="PhoneNumber" value="055 111 22 33" class="form-control" readonly="false">`

**Comment by maliming** [comment]
hi

It seems you are using ABP commercial.
Please get help on https://support.abp.io/
