### ISSUE TITLE
About abp version

### ISSUE THREAD

**Issue by ma7x** [abpframework/abp#15567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have a qustion,  we have abp vnext 7.0.1 / 6.0.3 /5.3.5 now.
Why not choose  .NET6 lts
too many release versions, Is it bad? 

### Describe the solution you'd like

Or for what reason.
What version should I choose?

**Comment by maliming** [comment]
**≥ 7.x target to NET 7**
**≤ 6.x target to NET 6**

> What version should I choose?

Depends on your NET platform.
