### ISSUE TITLE
Blogging: Increase the post read count if it viewed by a reader for the first time

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#15570]
We need to retrieve the reader's IP address and check from the database. If there is not any record with the current IP address for the post, then we can increase the post's read count. Otherwise, read counts can be easily manipulated by bots just visiting a certain post.

IP addresses are not reliable, see https://github.com/abpframework/abp/issues/15570#issuecomment-1411714626. So we need to save and check some other info, such as *User-Agent*, etc... Consider the other possible unique conditions.

**Comment by hikalkan** [comment]
Counting IP is not a proper solution, because a network may expose the same IP to outside. So, multiple users in same local network is counted as a single user if we only check IP.
