### ISSUE TITLE
The features check box is disable after saving

### ISSUE THREAD

**Issue by TaiNguyen2406** [abpframework/abp#15572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

some checkboxes like this one in the pic below. 
I check this and then save it, after that the check box is disabled, and can not uncheck or check again. 
If I press save again, the check box is unchecked and can be checked.

![image](https://user-images.githubusercontent.com/23568713/216041241-4b7c7491-174d-4aa8-8ec7-6d78fb5bf008.png)

### Version

6.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
User Interface?

**Comment by TaiNguyen2406** [comment]
> User Interface?

I just use the normal interface with LeptonX theme

**Comment by maliming** [comment]
MVC or Blazor or Angular?

**Comment by TaiNguyen2406** [comment]
> MVC or Blazor or Angular?

MVC

**Comment by maliming** [comment]
Can reproduce using a template project without any change?

**Comment by TaiNguyen2406** [comment]
I can not create a new template project

**Comment by maliming** [comment]
How can we reproduce this?

**Comment by TaiNguyen2406** [comment]
Can you try it with file management? I do not change anything on that

**Comment by maliming** [comment]
I did not reproduce the problem.

**Comment by TaiNguyen2406** [comment]
Is this still enable to uncheck after saving?

**Comment by TaiNguyen2406** [comment]
The data in the AbpFeatureValues. What is provider name E mean, I think we only have 
DefaultValueSettingValueProvider: "D".
ConfigurationSettingValueProvider: "C".
GlobalSettingValueProvider: "G".
TenantSettingValueProvider: "T".
UserSettingValueProvider: "U".
![image](https://user-images.githubusercontent.com/23568713/216828590-67c7525c-e144-426a-a822-c18baa17d889.png)

**Comment by TaiNguyen2406** [comment]
I think the problem is that I updated features from 2 places Tenants and Editions and it conflict with each other
![image](https://user-images.githubusercontent.com/23568713/216830403-6df0c408-b45a-4b07-b1ba-978389d6c7e8.png)

**Comment by maliming** [comment]
You can get help about ABP commercial at https://support.abp.io/
