### ISSUE TITLE
Separate layers into two different solutions one for frontend and one for backend

### ISSUE THREAD

**Issue by MohammdaSalah** [abpframework/abp#15595]
### Discussed in https://github.com/abpframework/abp/discussions/15560

Hi, we created a multilayer MVC application using ABP template but they are placed in one visual studio solution, we want to separate them to backend solution and frontend solution so that the backend solution should only talk to the database while the frontend have the user interface logic, the goal for this is to deploy each solution in a two different servers on the production servers.
We looked at the code and the relation between the layers I'm not sure if they are cleaned separated, it does not always talk to the database from one layer, many layers are doing that.

How we can accomplish this task?

**Comment by nebula2** [comment]
splitting the code into multiple solutions and deploying the apps on multiple servers are two different concerns.

if you use a layered template, everything is splitted nicely. Your UI will use the generated api client to interact with the backend. That is why you do not have a connection string to the database on your ui project.

If you want to split everything into multiple solutions, then you can just do that. Keep in mind that you may need to build nuget packages for the layers and consume them where needed.

If you want to deploy to multiple servers, just adjust your appsettings.

**Comment by MohammdaSalah** [comment]
I do not think the layered template is splitted nicely! If you check version 6 and above (I do not know about the previous versions) you will find that the UI itself access repository directly, not all of them uses api client!

**Comment by nebula2** [comment]
> I do not think the layered template is splitted nicely! If you check version 6 and above (I do not know about the previous versions) you will find that the UI itself access repository directly, not all of them uses api client!

I think I got my vocabulary wrong.
What I meant was the **tiered** option. Did you set that upon creation?

**Comment by MohammdaSalah** [comment]
Yes sure I set tiered option

**Comment by nebula2** [comment]
I just tested it by creating a new solution with 
`abp new Acme.BookStore -dbms SQLite --tiered `

![image](https://user-images.githubusercontent.com/5841525/218255262-ff108c49-b150-4bbb-85e3-11fd1765d769.png)

`Acme.BookStore.Web` is the UI project. As you can see in the appsettings there is no direct connection to the database.
![image](https://user-images.githubusercontent.com/5841525/218255299-17573492-af64-485c-8c91-daa61f3b5340.png)
![image](https://user-images.githubusercontent.com/5841525/218255314-ec06dc4a-b11a-458a-bd9c-2bdba901c265.png)

If you take a look at `Acme.BookStore.HttpApi.Host`'s appsettings - which is the API - you will notice that there is a connection string.
![image](https://user-images.githubusercontent.com/5841525/218255354-e7233cac-9137-4d1a-9be4-5143ad79f107.png)
![image](https://user-images.githubusercontent.com/5841525/218255371-ffa8a0c6-f1a3-41fa-b65a-c0afd4a8cacd.png)

Therefore, everything is as it is supposed to be.
Can you please double check your setup or elaborate more on your issue?

**Comment by MohammdaSalah** [comment]
Fine now try to separate the backend layers and frontend layer each in separate two solutions one for backend and one for front end, you will find the problems.

**Comment by nebula2** [comment]
> Fine now try to separate the backend layers and frontend layer each in separate two solutions one for backend and one for front end, you will find the problems.

did that multiple times without an issue

**Comment by MohammdaSalah** [comment]
How did you separate them?

**Comment by nebula2** [comment]
> How did you separate them?

as described in my first comment.
