### ISSUE TITLE
Unable to use Newtonsoft  in DynamicHttpProxyInterceptorClientProxy

### ISSUE THREAD

**Issue by myall200** [abpframework/abp#15598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/10205986/216664695-368aca2e-468b-4a06-9765-0cf82f7c747e.png)

### Reproduction Steps

1、Use  context.Services.AddTransient<Volo.Abp.Json.Newtonsoft.AbpDateTimeConverter>(); 
2、Use [DependsOn(
    typeof(TmsManagementApplicationContractsModule),
    typeof(AbpAspNetCoreMvcNewtonsoftModule))]
3、invoke other service by DynamicHttpProxyClient
4、
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/10205986/216666060-45d0e6ca-85a6-4471-aef8-4992c550f5d6.png">

### Version

7.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by myall200** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/10205986/216667182-5c976b1f-e981-4a57-9b43-16a6852fb8e6.png">

**Comment by myall200** [comment]
```cs
public class AbpCamelCasePropertyNamesContractResolver : CamelCasePropertyNamesContractResolver, ITransientDependency
{
    // private readonly Lazy<AbpDateTimeConverter> _dateTimeConverter;
    private readonly AbpDateTimeConverter _dateTimeConverter;
    public AbpCamelCasePropertyNamesContractResolver(IServiceProvider serviceProvider)
    {
        // _dateTimeConverter = new Lazy<AbpDateTimeConverter>(
        //     serviceProvider.GetRequiredService<AbpDateTimeConverter>,
        //     true
        // );
        _dateTimeConverter =
            serviceProvider.GetRequiredService<AbpDateTimeConverter>();

        NamingStrategy = new CamelCaseNamingStrategy
        {
            ProcessDictionaryKeys = false
        };
    }

    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
    {
        var property = base.CreateProperty(member, memberSerialization);

        if (AbpDateTimeConverter.ShouldNormalize(member, property))
        {
            property.Converter = _dateTimeConverter;
        }

        return property;
    }
}
```
remove Lazy,it work!

**Comment by maliming** [comment]
hi

Can you share a sample project?

**Comment by myall200** [comment]
Sorry,the project needs to rely on the data environment, and now it is the interservice calls that present the problem. The call was successful, but an exception occurred when the returned result was serialized.
