### ISSUE TITLE
Angular generate proxy with other module from application service

### ISSUE THREAD

**Issue by cloud0259** [abpframework/abp#15609]
Hello,
Is it possible to automatically generate proxies with angular from another module?
Do I have to use a controller or is there a way to generate the calls automatically?

I tried to add this line in the HttpApiHost but the actions of the controllers are not taken into account. I would like to use both possibilities, AppService and Controllers

```cs
 options.ConventionalControllers.Create(typeof(ModuleAApplicationModule).Assembly);
```

**Comment by salihozkara** [comment]
Hello, have you looked at [this document](https://docs.abp.io/en/abp/latest/UI/Angular/Service-Proxies)?
