### ISSUE TITLE
ABP blzor server file upload error

### ISSUE THREAD

**Issue by yupingyong** [abpframework/abp#15619]
.net 7 + abp 7.0.1 + blazor server

Error:Did not receive any data in the allotted time.
![image](https://user-images.githubusercontent.com/29831143/216998341-8f5113c8-675f-40d7-b58e-969f72c84d5b.png)

If I don't introduce the ABP framework, it's right to upload files directly using Blazor Server

**Comment by maliming** [comment]
https://support.abp.io/QA/Questions/4474/Upload-file-Did-not-receive-any-data-in-the-allotted-time#answer-1d0acd0d-5594-41d3-02aa-3a092715ad2c

**Comment by yupingyong** [comment]
thank's
