### ISSUE TITLE
Cannot make Websocket-based SignalR connection work with self-signed certificate on Azure VM

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#15623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whereas everything works properly on localhost, Azure VM version does not. The exception during handshaking is below:

> System.Net.WebSockets.WebSocketException (997): Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
>  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
>    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
>    at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
>    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
>    at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
>    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
>    at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Proxy(HttpContext context, String serverEndpoint)
>    at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
>    at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
>    at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
>    at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
>    at Ocelot.Multiplexer.MultiplexingMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
>    at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
>    at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext)

The endpoint setup is:

```
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
Configure<AbpSignalROptions>(options =>
{
    options.Hubs.AddOrUpdate(
        typeof(NotificationHub),
        config =>
        {
            config.RoutePattern = "/signalr-hubs/notification";
            config.ConfigureActions.Add(hubOptions =>
            {
                hubOptions.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets;
            });
        }
    );
});
```

I can't see the way to let this endpoint accept self-signed certificate as it is done for http/https requests:

```
context.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
   .AddJwtBearer(options =>
   {
       options.Authority = configuration["AuthServer:Authority"];
       options.RequireHttpsMetadata = Convert.ToBoolean(configuration["AuthServer:RequireHttpsMetadata"]); ;
       options.Audience = "CentralTools";
       options.BackchannelHttpHandler = new HttpClientHandler
       {
           //TODO: use valid certificate in future and change the logic
           ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
       };
```

![image](https://user-images.githubusercontent.com/6149843/217130288-586cdd5d-46bf-47a0-ac96-866c3e74f5aa.png)

![image](https://user-images.githubusercontent.com/6149843/217131036-6c93cda1-d77c-4d00-901e-54861ceb1d03.png)

### Version

5.1.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
**The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch**

<img width="944" alt="image" src="https://user-images.githubusercontent.com/6908465/217163007-08d0403f-5901-4908-b7ef-d95358eddae4.png">

**Comment by alexandis** [comment]
I know this. But it does not prevent me from working with it on dev site for http requests using "return true" for http server certificate handler callback.

My initial question was - how to make it work for websocket too?

**Comment by maliming** [comment]
> how to make it work for websocket too?

This is nothing to do with abp.

**Comment by alexandis** [comment]
But I'm using `AbpSignalROptions` and  the class inherited from `AbpHub` which add this wss endpoint in question. So it seems like the only way to setup the server certificate hander behavior would be to use this code options.
