### ISSUE TITLE
Autofac Cannot Resolve IApplicationService 

### ISSUE THREAD

**Issue by hieutns96** [abpframework/abp#1563]
Hello guys,
I'm having an issue with autofac. When I reference the http.api project to the Application.Contracts it's cannot resolve the service, but if I reference to the Application the issue is gone.

![image](https://user-images.githubusercontent.com/28976584/62216058-485bf180-b3d2-11e9-84b1-f8308bb11742.png).

![image](https://user-images.githubusercontent.com/28976584/62216242-940e9b00-b3d2-11e9-9e25-b70a932100a8.png)

**Comment by maliming** [comment]
Because the `IFuelRateAppService `interface needs to have an implementation.

If you only use `Application.Contracts` you can use Dynamic C# API Clients.
https://docs.abp.io/en/abp/latest/AspNetCore/Dynamic-CSharp-API-Clients

**Comment by hieutns96** [comment]
@maliming I actually have the implement of IFuelRateAppService in the AppService project. That's why i said that when i reference to the Applciation project the register of interface work fine.

**Comment by maliming** [comment]
I know what you mean.

Is the hierarchical structure of your project similar to this? Or tiered

![image](https://user-images.githubusercontent.com/6908465/62263923-74b65300-b450-11e9-8439-47c148676d64.png)

**Comment by hieutns96** [comment]
Yes when i try to use this hierarchical Autofac not working when Http.Api.Client depends on Contracts but it's work fine when depends on Application

**Comment by maliming** [comment]
How did you run this project?

I mean the xxx.Web project in the default template already references the xxx.Application and xxx.HttpApi projects you mentioned.

**Comment by hieutns96** [comment]
I don't need the web project, so I remove the .Web project. Currently i'm run it default is .HttpApi

**Comment by maliming** [comment]
If your HttpApi project only references interfaces, then of course you can't resolve it.

If so, you should reference the application service layer.

**Comment by hieutns96** [comment]
Well, you mean no matter what is my startup project, i still need to references to the applications service so that Autofac can resolve it. Right ?

**Comment by maliming** [comment]
In addition to this situation(https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Application.md#web-project-1), Yes.

**Comment by hieutns96** [comment]
Thanks for your help @maliming  ^^
