### ISSUE TITLE
Blazor wasm - Remote server returns 'InternalServerError' error while creating project

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#15634]
**Version:** `7.1.0-rc1`
**Command:** ` abp new BlazoorWasm.BWASMfCore070223Free  -u blazor --separate-identity-server -csf -t app  --version 7.1.0-rc.1`

Remote server returns 'InternalServerError' error while creating project

![image](https://user-images.githubusercontent.com/99716457/217225615-1944379c-a551-4788-9402-4838782c3bd1.png)

**Comment by EngincanV** [comment]
![image](https://user-images.githubusercontent.com/43685404/217275090-fe191def-f322-4fb4-99ce-8465567d7d21.png)

It was related to abp.io being temporarily inaccessible.
