### ISSUE TITLE
Localization resources in database

### ISSUE THREAD

**Issue by piktasdiedas** [abpframework/abp#15651]
I have seen this issue [2569](https://github.com/abpframework/abp/issues/2569) that you can store and fetch translations from database. But it seems that you still need to have .json files with translation keys, and database is used only for translation values. I want to able to add translations, and languages, on runtime, not on build time.

And, as far as I understand, I would like to implement _IStringLocalizer_ that that would have method _IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)_ . And this method would call database to get all available translations keys.

Is it possible to achieve that? Or do I need to have these json files?

**Comment by maliming** [comment]
Yes, It's possible. And we did it in https://commercial.abp.io/modules/Volo.LanguageManagement

**Comment by piktasdiedas** [comment]
Would it be possible to get basic example where to add/register _IStringLocalizer_  for this matter?

**Comment by maliming** [comment]
It is mainly implemented through `ILocalizationResourceContributor`.

```cs
Configure<AbpLocalizationOptions>(options =>
{
    options.GlobalContributors.Add<YourDynamicLocalizationResourceContributor>();
});
```
