### ISSUE TITLE
How to build mongodb index in abp code

### ISSUE THREAD

**Issue by zengnanhua** [abpframework/abp#15650]
![image](https://user-images.githubusercontent.com/22017107/217708427-4011e8ff-5063-4749-84e7-fdb4918c0ad7.png)

**Comment by maliming** [comment]
You can configure EF Core entities again.

**Comment by zengnanhua** [comment]
mongodb index

**Comment by maliming** [comment]
hi

You can replace the DbContext and configure the entities again.

https://docs.abp.io/en/abp/latest/MongoDB#replace-other-dbcontextes
