### ISSUE TITLE
Current user authorized, but tenant id is null

### ISSUE THREAD

**Issue by yuvarajass06** [abpframework/abp#15679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Please advise, what I am doing wrong here.
The current user is logged in, the user id and roles are set, but tenant id is null on Current User, I have tried. setting claim id as
"tid" and "tenantid" (http://www.aspnetboilerplate.com/identity/claims/tenantId). Always getting the tenant id null.

### Reproduction Steps

`{
  "sub": [
    "0703e8ed-02e6-4fd6-a888-2842a21ad039",
    "div@gmail.com"
  ],
  "name": "div@gmail.com",
  "AspNet.Identity.SecurityStamp": "F17F05F0-701C-420C-ADC8-12B508846675",
  "role": "TenantUser",
  "tid": "25388015-EF1C-4355-9C18-F6B6DDBAF89D",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn": "div@gmail.com",
  "jti": "190690e2-cab1-4af2-85a5-33a2e3cca421",
  "iat": 1676272518,
  "nbf": 1676272518,
  "exp": 1676358918,
  "iss": "https://localhost:44380",
  "aud": "default-api"
}`

**Another:**

`{
  "sub": [
    "0703e8ed-02e6-4fd6-a888-2842a21ad039",
    "div@gmail.com"
  ],
  "name": "div@gmail.com",
  "AspNet.Identity.SecurityStamp": "F17F05F0-701C-420C-ADC8-12B508846675",
  "role": "TenantUser",
  "http://www.aspnetboilerplate.com/identity/claims/tenantId": "25388015-EF1C-4355-9C18-F6B6DDBAF89D",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn": "div@gmail.com",
  "jti": "9dfcdbca-170b-46b8-abd5-12aeef1383e4",
  "iat": 1676273082,
  "nbf": 1676273082,
  "exp": 1676359482,
  "iss": "https://localhost:44380",
  "aud": "default-api"
}`

### Expected behavior

Current user should have tenant id. Also current tenant should have tenant details, which has been taken from claim. 

### Actual behavior

Current user tenant id is null. Still, I can find tenant id in claims. 

### Version

7.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Security/Volo/Abp/Security/Claims/AbpClaimTypes.cs#L59

**Comment by yuvarajass06** [comment]
Thank you. Resolved.
