### ISSUE TITLE
Extra slash when routing to Account in Angular LeptonX Lite.

### ISSUE THREAD

**Issue by lukagalovic** [abpframework/abp#15682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try, to go to `Account` I get route `https://localhost:44319//Account/Manage?returnUrl=http://localhost:4200/main/dashboard` which is incorrect as it has 2 slashes after `https://localhost:44319`.

Everything seems alright in configuration. I am using IIS.

Have I missed something in account module routing configuration ?

`app-routing.module.ts`
```
const routes: Routes = [
    { path: '', redirectTo: 'main/dashboard', pathMatch: 'full' },
    { path: 'admin', loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule) },
    { path: 'main', loadChildren: () => import('./main/main.module').then(m => m.MainModule) },
    { path: 'account', loadChildren: () => import('@abp/ng.account').then(m => m.AccountModule.forLazy()) },
    { path: 'identity', loadChildren: () => import('@abp/ng.identity').then(m => m.IdentityModule.forLazy()) },
    { path: 'tenant-management', loadChildren: () => import('@abp/ng.tenant-management').then(m => m.TenantManagementModule.forLazy()) },
    { path: 'setting-management', loadChildren: () => import('@abp/ng.setting-management').then(m => m.SettingManagementModule.forLazy()) },
    { path: '**', redirectTo: 'main/dashboard' }
];
```

`Environment.ts`
```
export const environment = {
    production: false,
    application: {
        baseUrl,
        name: 'LicGen',
        logoUrl: '',
    },
    oAuthConfig: {
        issuer: 'https://localhost:44319/',
        redirectUri: baseUrl,
        clientId: 'LicGen_App',
        responseType: 'code',
        scope: 'offline_access LicGen',
        requireHttps: true,
    },
    apis: {
        default: {
            url: 'https://localhost:44319',
            rootNamespace: 'LicGen',
        },
    }
} as Environment;
```
`appsettings.json`
```
"App": {
    "SelfUrl": "https://localhost:44319",
    "ClientUrl": "http://localhost:4200",
    "CorsOrigins": "http://*.*.com,http://localhost:4200",
    "RedirectAllowedUrls": "http://localhost:4200,https://localhost:44319"
```

ClientUri in `OpenIddictAuthorizations` table is `https://localhost:44319`

### Version

7.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by bariscanyilmaz** [comment]
Hi @lukagalovic, I tried to reproduce it using rel-7.0 branch and dev branch template projects, but I couldn't produce it. Could you share a demo project that causing extra slash when routing?

**Comment by lukagalovic** [comment]
I solved it by replacing `eThemeLeptonXComponents.CurrentUser` with custom component in which I made URL by myself.

I suppose problem is that somewhere in framework `issuer` property is picked from `oAuthConfig` in `environment.ts`, which has `/` at the end of the string, instead of picking `url` from `apis` in `environment.ts`.

**Comment by mahmut-gundogdu** [comment]
Issue related with ABP.
It will fix easly
<img width="844" alt="image" src="https://user-images.githubusercontent.com/2217899/223940177-eb72b5bf-a94e-4841-abb4-ed38c05b4cde.png">

https://github.com/abpframework/abp/blob/0b08f85ec4c3ae39f595241fe0568228468ba87f/npm/ng-packs/packages/oauth/src/lib/providers/navigate-to-manage-profile.provider.ts#L16

**Comment by masum-ulu** [comment]
This issue completed with [7.1-final](https://github.com/abpframework/abp/pull/15924)
