### ISSUE TITLE
'Volo.Abp.TextTemplating.Razor' nuget package could not be found

### ISSUE THREAD

**Issue by cemalkarabulakli** [abpframework/abp#15686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, when I try to install TextTemplating for Razor it returns me the below warning:

`'Volo.Abp.TextTemplating.Razor' nuget package could not be found!`

Do I miss anything or what do I need to do for this warning message? Thanks.

### Reproduction Steps

![image](https://user-images.githubusercontent.com/4073721/218457281-ecada959-fb39-4577-83ee-b5d4182af97b.png)

### Version

7.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by onurpicakci** [comment]
Can you try to add the project you want to add manually by following the steps in the [link](https://docs.abp.io/en/abp/latest/Text-Templating-Razor)?

**Comment by Hinairusu** [comment]
https://support.abp.io/QA/Questions/4525/Cannot-find-lepton-x-pro-nuget---auth-server

There are a number of us with the same problem, seems to be widespread as an issue, and not just limited to one module:
![image](https://user-images.githubusercontent.com/21159538/218468323-fb379213-5ddb-4ae1-8099-ddc751ac459a.png)

**Comment by Hinairusu** [comment]
> Can you try to add the project you want to add manually by following the steps in the [link](https://docs.abp.io/en/abp/latest/Text-Templating-Razor)?

Manually adding does not seem to resolve it either, and Abp Suite Update also throws the error "the tool package could not be restored" - looks like the same fault.

**Comment by cemalkarabulakli** [comment]
> Can you try to add the project you want to add manually by following the steps in the [link](https://docs.abp.io/en/abp/latest/Text-Templating-Razor)?

I tried manually but this time I get this error:

![image](https://user-images.githubusercontent.com/4073721/218477923-6ea6588f-c737-49d8-986b-99120a86e75d.png)

**Comment by cemalkarabulakli** [comment]
Ok. I solved the error. With package manager still I get the error but when I install it with  CLI 
`dotnet add package Volo.Abp.TextTemplating.Razor --version 7.0.1` works.
