### ISSUE TITLE
Angular LeptonX - replaceable breadrumb shown when application is loaded, it only dissapears when clicked

### ISSUE THREAD

**Issue by lukagalovic** [abpframework/abp#15691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I replaced breadcrumb with custom component which has empty template because I don't want breadcrumb in my application.
Problem is, the original breadcrumb is loaded and shown when page is loaded.
![shown](https://user-images.githubusercontent.com/84729436/218681634-dcd6ff12-724c-410d-8d4e-946ba2d574d8.png)

When I click on it, it dissapears and my custom component is loaded.
![now shown](https://user-images.githubusercontent.com/84729436/218681729-1e45a666-9224-4f32-9555-26e9d926e99a.png)

Code:
```
import { ReplaceableComponentsService } from '@abp/ng.core';
import { eThemeLeptonXComponents } from '@abp/ng.theme.lepton-x';
import { Component } from '@angular/core';
import { CustomBreadcrumbComponent } from './shared/components/custom-breadcrumb/custom-breadcrumb.component';

@Component({
    selector: 'app-root',
    template: `
    <abp-loader-bar></abp-loader-bar>
    <abp-dynamic-layout></abp-dynamic-layout>
  `,
})
export class AppComponent {
    constructor(
        private replaceableComponents: ReplaceableComponentsService,
    ) {
        // Replace default breadcrumb with custom one (empty in this case)
        this.replaceableComponents.add({
            component: CustomBreadcrumbComponent,
            key: eThemeLeptonXComponents.Breadcrumb,
        });
    }
}
```

When I set `reload: true` in `add` function it doesn't show original breadcrumb, but then it shows all custom items in navbar as active and routing is not working for my custom routes. However it works for routes that come with framework (settings, tenant management).
![first](https://user-images.githubusercontent.com/84729436/218682809-85ef13d1-e36e-4b18-8685-c7219642ed2c.png)
![third](https://user-images.githubusercontent.com/84729436/218682871-a59b7b23-6e63-47fc-bb69-1a9ee926c46e.png)

### Known Workarounds

Add following code to `styles.scss`:
```
.lpx-breadcrumb-container {
  visibility: hidden !important;
}
```
This is fine if you just want to remove the breadcrumb.

### Version

7.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by bariscanyilmaz** [comment]
If you want to just hide breadcrumb component you can just set it null in replaceableService
```
this.replaceableComponents.add({
       component: null,
       key: eThemeLeptonXComponents.Breadcrumb,
 });
```
Result:
![image](https://user-images.githubusercontent.com/30300440/233350203-bea9c3b1-1ddd-422f-ad1c-b76a9bbb0eea.png)

The problem that is causing the replaced component to still be visible is another issue. We will fix it in the next release.
