### ISSUE TITLE
User must change password at next logon

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#15695]

**Comment by hikalkan** [comment]
@maliming you first think on the implementation and write your solution before starting it

**Comment by hikalkan** [comment]
Moved to https://github.com/volosoft/volo/issues/13511

**Comment by balessi75** [comment]
> Moved to https://github.com/volosoft/volo/issues/13511

The above link to 13511 is not accessible. Please advise if this request will be eventually considered as it appears to be removed from the 7.2 preview.

**Comment by maliming** [comment]
hi @balessi75 

This will be a commericial feature of the account pro module

**Comment by balessi75** [comment]
Hi @maliming,

That makes sense, thank you. We appreciate the consideration and continued support.
