### ISSUE TITLE
NETSDK1045	The current .NET SDK does not support targeting .NET Core 2.2. 

### ISSUE THREAD

**Issue by padhumailin** [abpframework/abp#1569]
i have installed .net core 2.2 but still error throws while build the solution.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.	aspire.demo.Domain	C:\Program Files\dotnet\sdk\2.1.507\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	137

**Comment by MightyLoggor** [comment]
If you are on VS Studio 2017, try to update it to the latest version and if you can, uninstall the older versions of .NET Core. It's working just fine for me with .NET Core 2.2.106.

**Comment by hikalkan** [comment]
Are you trying to run a project created using the startup template?

**Comment by hikalkan** [comment]
We couldn't repeat the problem. Ensure that you've correctly install the latest .net core sdk.
