### ISSUE TITLE
ToListAsync() was not found when using Repository

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1570]
Only `ToList()` can be used. What is this consideration?
![image](https://user-images.githubusercontent.com/30018771/62324607-7e859800-b4dc-11e9-961a-f6f8581460e8.png)

**Comment by maliming** [comment]
`ToListAsync `Is the extension method of EF Core.

**Comment by gdlcf88** [comment]
When my code works asynchronously, it's a bit inconvenient because I have to customize a repository for any queries.

**Comment by liangshiw** [comment]
using `Microsoft.EntityFrameworkCore`

**Comment by gdlcf88** [comment]
Maybe one day I wont use ef core anymore, using Microsoft.EntityFrameworkCore pollutes the code.

**Comment by gdlcf88** [comment]
Is `AsyncQueryableExecuter` a temporary solution, or will this problem never be solved?

**Comment by maliming** [comment]
In order not to dependent on EF Core, you can use it. But if you don't plan to change EF Core you can dependent on it directly, but this is not a best practice.
