### ISSUE TITLE
FeatureDefinition.WithProviders has a wrong comment that copied from WithProperties

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#15704]
https://github.com/abpframework/abp/blob/280a1753749f68e875e9149858197176c87e44bf/framework/src/Volo.Abp.Features/Volo/Abp/Features/FeatureDefinition.cs#L116-L138

`WithProviders` has a wrong comment that copied from `WithProperties`.

**Comment by realLiangshiwei** [comment]
Thanks @PMExtra
