### ISSUE TITLE
IDynamicEntityParameterDefinitionContext , DynamicEntityParameterDefinitionProvider not supporting with .net 6 and abp new version 

### ISSUE THREAD

**Issue by pawansingh168** [abpframework/abp#15701]
**If we are update the existing project, the abp lower version will not support to other framework upper version, i updated the abp latest version but above property not supporting, and provide proper process while update the abp version.**

**Comment by realLiangshiwei** [comment]
Sorry, but what's the IDynamicEntityParameterDefinitionContext? are you talking about [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate)?

**Comment by pawansingh168** [comment]
yes exactly you are right.

**Comment by realLiangshiwei** [comment]
you can create an issue on the [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate)

**Comment by pawansingh168** [comment]
- Im going to move .net 3.1 to .net 6.0  not supporting the parameter share method.
- using **Abp.DynamicEntityParameters**  -This extension not supporting when i update abp framework with latest version.
public class AppDynamicEntityParameterDefinitionProvider : **DynamicEntityParameterDefinitionProvider**
    {
        public override void SetDynamicEntityParameters(**IDynamicEntityParameterDefinitionContext** context)
        {

}


}
All bold property not supporting.
