### ISSUE TITLE
HideAbpEndpoints also hides endpoints that have a route parameter constraint

### ISSUE THREAD

**Issue by tinowilloeper** [abpframework/abp#15712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

To only see my own endpoints I added the option HideAbpEndpoints() to AddAbpSwaggerGenWithOAuth. After doing that I checked the swagger document and some of my own endpoints were also hidden. These endpoints have a route parameter constraint like `[Route("{id:long}")]` or `[Route("internal/{id:guid}")]`

### Known Workarounds

**The reason:** 
In the Apply-method of AbpSwashbuckleDocumentFilter.cs the Templates will be selected with the constraint. The OpenApiPaths in the OpenApiDocument will not contain the constraint. So the RemoveAll-function removes also these endpoints.
`swaggerDoc
    .Paths
    .RemoveAll(path => !actionUrls.Contains(path.Key));
`

**The solution:** 
_Remove the route parameter constraints while selecting the actionUrls like this:_
`.Select(actionDescriptor => actionDescriptor.AttributeRouteInfo?.Template?
    .EnsureStartsWith('/')
    .Replace("?", "")
    .RemoveRouteParameterConstraint())
`

_And an extension method:_

```csharp
public static string RemoveRouteParameterConstraint(this string route)
{
    while (route.Contains(':'))
    {
        var start = route.IndexOf(':');
        var length = route.IndexOf('}', start) - start;
        route = route.Remove(start, length);
    }
    return route;
}
```

### Version

7.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

### Other information

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Swashbuckle/Volo/Abp/Swashbuckle/AbpSwashbuckleDocumentFilter.cs#L20

Sorry for the bad formatting.

**Comment by EngincanV** [comment]
Hi, thanks for reporting. I'll be fixing it.
