### ISSUE TITLE
Collapse menu does not work

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#15715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

clicking on the collapse menu button does not collapse the menu

### Reproduction Steps

create a new blazor wasm app v7.01 
run the app
click on the collapse menu icon

![Screenshot 2023-02-16 085301](https://user-images.githubusercontent.com/40014477/219237021-fca0c9ae-781f-4a3e-8793-44fe209b7e94.png)

![menu-bug-lepton-x](https://user-images.githubusercontent.com/40014477/219237127-439ea17c-a8b3-40da-80d3-40b6d3e45587.gif)

### Expected behavior

Menu should collpase to the left

### Actual behavior

Menu does not collpase to the left

### Regression?

  unknown

### Known Workarounds

unknown

### Version

7.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

__side note: I am using 7.1 commercial but unable to post a bug report in the commercial forum for some reason._ despite being logged in and having a current license._

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/issues/14506#issuecomment-1298243290

**Comment by 274188A** [comment]
maybe a regression?  
why is the bug label removed? i must be missing something...is there a patch/update already?

**Comment by realLiangshiwei** [comment]
> I am using 7.1 commercial but unable to post a bug report in the commercial forum for some reason. despite being logged in and having a current license.

you can send an email to info@abp.io,

**Comment by realLiangshiwei** [comment]
>maybe a regression?
why is the bug label removed? i must be missing something...is there a patch/update already?

As EngincanV said https://github.com/abpframework/abp/issues/14506#issuecomment-1298243290,
This is not a bug. and it's also working for me.


![test](https://user-images.githubusercontent.com/16813853/219254734-f5c5ca3c-79c5-4c50-87ed-a41e529e036c.gif)
