### ISSUE TITLE
Abp framework error: Keyword not supported: 'datasource'.

### ISSUE THREAD

**Issue by Ilthepriest** [abpframework/abp#15738]
Abp 7.0 MVC EF Core
I am getting the following error "System.ArgumentException: 'Keyword not supported: 'datasource'.'" with the first migration and seed of the DbMigrator project.
![errore_datasource](https://user-images.githubusercontent.com/95420941/219619416-5447f0fa-5c3a-4081-a8e6-f4b80aa46a6d.PNG)
![JsonDbMigrator](https://user-images.githubusercontent.com/95420941/219619723-04aa7e6e-061e-4634-9835-b9217b05ef6b.PNG)

**Comment by EngincanV** [comment]
Hi, this problem is not related to ABP Framework. This problem raises when one of your connection strings includes "datasource" keyword. So, please search for this keyword in your application and remove it.

**Comment by Ilthepriest** [comment]
Hi, thanks for the reply. I searched for the keyword in the entire solution with and without quotes but found no results.
I state that I haven't written any code yet I'm following the steps of the Abp framework documentation to create the initial project.
![search](https://user-images.githubusercontent.com/95420941/219629531-d0f48ede-7772-4885-876c-fb604e7eb511.PNG)

**Comment by berkansasmaz** [comment]
Hi, I tried to download a template with version `7.0.0` and reproduce the problem, but unfortunately without success.

Here are my steps:
1.`dotnet tool uninstall Volo.Abp.Cli -g`.
2.`dotnet tool install -g Volo.Abp.Cli --version 7.0.0`.
3. `abp new Acme.BookStore -t app --csf --version 7.0.0`.
4. I changed the connection string in `appsettings.json` for `Acme.BookStore.DbMigrator` and `Acme.BookStore.Web` projects accordingly to my local setup.
5. Run `Acme.BookStore.DbMigrator` project.
6. Run `Acme.BookStore.Web` project.

**Comment by Ilthepriest** [comment]
Hi @berkansasmaz , thanks for the reply, I tried to follow the procedure following your exact same steps but I get the same error...
However, I discovered that trying on another computer I don't get the error and I can start everything correctly what could it depend on?

**Comment by berkansasmaz** [comment]
Honestly, I have no idea, but after a little research, I found a related[ stackoverflow question](https://stackoverflow.com/questions/1404268/keyword-not-supported-data-source), [here](https://stackoverflow.com/a/27598354/9922629) is an interesting answer other than the connection string, if you want to check it out. 

Unfortunately, I can't help you further as I haven't encountered this problem before. However, if you solve it, please post how you solved it below this issue, it may be a reference for someone else.

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
