### ISSUE TITLE
LeptonX Blazor WASM account link links to api home page, not the blazor home page

### ISSUE THREAD

**Issue by curelom** [abpframework/abp#15730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When making updates to account information such as password reset/login and so forth, the current Blazor wasm  framework pushes you to the api server running the account pages.  This is fine, except the link lpx-logo-container in the top of the sidebar is set to send you to "/".  That takes you to the swagger page of the api instead of the blazor home page. 

### Reproduction Steps

Create a Blazor wasm project with LeptonX theme, then run.  Click on login 

### Expected behavior

We should never have a link for our users to go to the swagger page.  The link should instead point to the Blazor server instead of the current server which would be the api server.

### Actual behavior

Link takes you to swagger page instead of Blazor homepage

### Version

7.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
I can say that this is normal. For more information you can check [here](https://support.abp.io/QA/Questions/1560/Logo-on-login-page-redirects-to-Swagger#answer-7f48ce9f-7aa1-6497-b0f0-39fd95eeb5ea).

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
