### ISSUE TITLE
Blazor Converts Time Parameters to UTC on Get Requests

### ISSUE THREAD

**Issue by omer-repo** [abpframework/abp#15746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using Blazor Wasm with ABP 6.0.3. As guided, I create methods in  AppService, then using them in Blazor Wasm by injecting.

I have a problem with time parameters if my method is a GET request. (Actually I don't select request type for the method, ABP proxy generation does it automagically). For example I want to filter table between 19.01.2023 and 19.02.2023. If my method generated as POST method, Blazor sends this parameters and it seems ok.
{
    "date1": "**2023-01-19**T00:00:00",
    "date2": "**2023-02-19**T00:00:00",
    "accountId": "e5a3cfb6-237f-4ccc-c301-3a088464048d",
    "crossId": null,
    "transactionType": 5,
    "directionType": null,
    "amount": null,
    "currencyId": null,
    "description": "",
    "sorting": "TransactionDate",
    "skipCount": 0,
    "maxResultCount": 20
}
![Image](https://i.imgur.com/JTqPeiW.png)

But if my method is generated as GET method, Blazor sends parameters as QueryString (as it should) and converts time variables to UTC time.
Date1: **2023-01-18T21:00**:00.0000000Z
Date2: **2023-02-18T21:00**:00.0000000Z
![Image](https://i.imgur.com/VzJNMCu.png)

Actually, I thought Blazor does this conversation always, so I converted time values to LocalTime in filter methods.
`input.Date2.Value.ToLocalTime()`

But after realized that it sends time parameters differently on GET and POST methods, I am a little confused and I think there is bug here.

### Reproduction Steps

Create a method that will be generated as GET method:
`public async Task<byte[]> GetExcelListAsync(TransactionGetListInput input)`

Create a mehtod that will be generated as POST method:
`public async Task sendTransactionEmail(TransactionGetListInput input, string email)`

**input object should have a DateTime parameter**

### Version

6.0.3

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Can you upload your test project to GitHub?

**Comment by omer-repo** [comment]
Hi,
I uploaded the test project to https://github.com/omer-repo/Acme.POC1

Code
![Image](https://i.imgur.com/RWsDzae.png)

Get Request
![Image](https://i.imgur.com/CIAu95V.png)

Console (It comes to backend as different)
![Image](https://i.imgur.com/KhTYj9U.png)

Post Request
![Image](https://i.imgur.com/Zyj1Iv4.png)

**Comment by maliming** [comment]
hi


You can set the `Kind` of `AbpClockOptions` to `Local`.

```cs
Configure<AbpClockOptions>(x => x.Kind = DateTimeKind.Local);
```

Here are my test results, you can see the time is the same just has a different kind.

```cs
public Task GetExample(GetListInput input)
{
    Logger.LogError("GetExample");
    Logger.LogError(input.Date1.Kind.ToString());
    Logger.LogError(input.Date1.ToString("O"));
    Logger.LogError(input.Date1.ToUniversalTime().ToString("O"));
    Logger.LogError(input.Date1.ToLocalTime().ToString("O"));

    return Task.CompletedTask;
}

public Task PostExample(GetListInput input, string someAnohterParameter)
{
    Logger.LogError("PostExample");
    Logger.LogError(input.Date1.Kind.ToString());
    Logger.LogError(input.Date1.ToString("O"));
    Logger.LogError(input.Date1.ToUniversalTime().ToString("O"));
    Logger.LogError(input.Date1.ToLocalTime().ToString("O"));

    return Task.CompletedTask;
}
```

```
[11:23:00 ERR] PostExample
[11:23:00 ERR] Local
[11:23:00 ERR] 2023-02-27T11:22:53.8770000+08:00
[11:23:00 ERR] 2023-02-27T03:22:53.8770000Z
[11:23:00 ERR] 2023-02-27T11:22:53.8770000+08:00


[11:23:00 ERR] PostExample
[11:23:00 ERR] Local
[11:23:00 ERR] 2023-02-27T11:22:53.8770000+08:00
[11:23:00 ERR] 2023-02-27T03:22:53.8770000Z
[11:23:00 ERR] 2023-02-27T11:22:53.8770000+08:00
```

**Comment by omer-repo** [comment]
Thank you very much.

I added this line to ApplicationModudule.cs in Application layer. Now Date1.ToString() gives local time for GET request also. This solved the issue I think.

But why Blazor still sends different formats in GET and POST methods. Regardless of the format, wouldn't it be easier to manage if they were sent in the same format?

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/issues/3339#issuecomment-608280986
