### ISSUE TITLE
The DateTimeKind of use AbpHttpClientModule

### ISSUE THREAD

**Issue by helloxubo** [abpframework/abp#15754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Service A call service B by AbpHttpClientModule with httpGet request.  service a has a datetime paramater with local DateTimeKind ,but service B received a   datetime paramater with utc DateTimeKind.
I configred the AbpClockOptions kind with local ,But there are still problems.

### Reproduction Steps

/

### Expected behavior

/

### Actual behavior

/

### Regression?

/

### Version

6.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
This is by design.

See  https://github.com/abpframework/abp/issues/3339
https://github.com/abpframework/abp/blob/08cef7ca486b16a223aa08a8c7c3981f3be9247b/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/ClientProxying/ClientProxyUrlBuilder.cs#L225

**Comment by helloxubo** [comment]
> abp/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/ClientProxying/ClientProxyUrlBuilder.cs
Maybe use IClock.Normalize() method is better.

**Comment by helloxubo** [comment]
> This is by design.
> 
> See #3339
> 
> https://github.com/abpframework/abp/blob/08cef7ca486b16a223aa08a8c7c3981f3be9247b/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/ClientProxying/ClientProxyUrlBuilder.cs#L225



> This is by design.
> 
> See #3339
> 
> https://github.com/abpframework/abp/blob/08cef7ca486b16a223aa08a8c7c3981f3be9247b/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/ClientProxying/ClientProxyUrlBuilder.cs#L225

Maybe use IClock.Normalize() method is better.
