### ISSUE TITLE
Add source code option for the add-module CLI command

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1575]
Currently, [add-module command](https://docs.abp.io/en/abp/latest/CLI#add-module) adds a module as NuGet/NPM packages to a solution.
In addition, we can add a --with-source-code option to add source code of the module instead of packages. That will make easy to include a module to the solution and modify its source code freely. This may be wanted to fully customize it.

**Comment by maliming** [comment]
Resolved by https://github.com/abpframework/abp/pull/2926
