### ISSUE TITLE
Integration with asp.net identity

### ISSUE THREAD

**Issue by abdullahshaqaliah** [abpframework/abp#15766]
Hello
I already have tables for Students, Teachers, and Staff and each one of those tables contains a username and password.
how can itegration with abp with asp.net identity I need the best way to integration with abp to using all funcatinality of abp with asp.net identity

**Comment by maliming** [comment]
hi

You can try to find a way that integrates your tables with ASP NET Identity first.

Then it will be easy to integrate with abp.

**Comment by abdullahshaqaliah** [comment]
Hi
@maliming  i can not integrat with asp.net user tables Can create custom login like facebook and google and how can do that if we can ?

**Comment by maliming** [comment]
> i can not integrat with asp.net user tables

You have to integrate it then can use abp identity module.

**Comment by 0xtaichim** [comment]
I think you are trying to express that you have three roles with their own table fields, and they all need to log in to your system. I believe these roles are all Users, so you can use a shared primary key User.ID.  each role is a User, but they have different tables storing different custom fields.
