### ISSUE TITLE
Response 204  to swagger

### ISSUE THREAD

**Issue by hemiaoio** [abpframework/abp#15762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to clearly express the output type of the api in the result of the swagger, especially the api without content output. The current result has covered the common exception http status code, but if the api does not output content, the swagger does not clearly express it, only a 200 status code. So I want to mark some explicit no-output apis with 204 status code on swagger。

### Describe the solution you'd like

My solution is to judge the output type in [ApiDescriptionProvider](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApiExploring/AbpRemoteServiceApiDescriptionProvider.cs#L47), and then change the status code. Here is my code.
```csharp
foreach (var result in context.Results.Where(x => x.IsRemoteService()))
{
     var successResult =
                result.SupportedResponseTypes.FirstOrDefault(c => c.StatusCode == (int)HttpStatusCode.OK);
      if (successResult != null)
      {
          if (successResult.Type == null || successResult.Type == typeof(void) ||
              successResult.Type == typeof(Task))
          {
              successResult.StatusCode = (int)HttpStatusCode.NoContent;
          }
    }
    var actionProducesResponseTypeAttributes =  ..............other codes
}

```

**Comment by maliming** [comment]
This seems nothing to do with abp.

**Comment by hemiaoio** [comment]
> This seems nothing to do with abp.

Yes, it looks like this, but we can improve it in the default swagger response of abp mvc, right?
