### ISSUE TITLE
this client application is not allowed to use the specified scope

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [abpframework/abp#15769]
After creating a new microservice it work fine for me, then I'm pushing my changes to git. If some one pull this new microservice change and run it their local machine they are getting this error in UI.

Can some give a solution for this. Some times if I delete all the database it will work fine.

Server Side: C# Microservice
Front end: Angular

![image](https://user-images.githubusercontent.com/16976667/220324254-11cb3d07-5bc4-472d-9f87-09bf543d691c.png)

**Comment by maliming** [comment]
hi

What is your client creation code?
What is the full context logs?

**Comment by Mugesh-Rajaram** [comment]
Hi @maliming, From where i can take this context log and how to find the client creation code in my code base.

**Comment by maliming** [comment]
**Logs/logs.txt**

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/OpenIddict/OpenIddictDataSeedContributor.cs#L107-L130

**Comment by Mugesh-Rajaram** [comment]
@maliming, Thanks for sharing the link, do i need to make any change in this file or debug something ?.

**Comment by maliming** [comment]
Please share this info.

https://github.com/abpframework/abp/issues/15769#issuecomment-1439313736
