### ISSUE TITLE
How force AsyncPeriodicBackgroundWorker to execute worker on startup

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#15773]
I created worker based on AsyncPeriodicBackgroundWorkerBase.
It works perfect.

But 1st DoWork execution is triggered after Timer.Period expires. 
If this period is large (1 hour) then we must wait 1 our for 1st execution.

Is it possible to configure worker to execute  immediately after registration (on application start) ?

Regards.

**Comment by salihozkara** [comment]
Hello I think you can trigger this method when starting this application

**Comment by salihozkara** [comment]
Hello, you can move the code in your AsyncPeriodicBackgroundWorker into a service and then call that service in your AsyncPeriodicBackgroundWorker. You can then call and run this service in the OnApplicationInitialization method of your project.

**Comment by berkansasmaz** [comment]
Also, for advanced scenarios, you can use our Quartz integration package(`Volo.Abp.BackgroundWorkers.Quartz`).

For example, here is an example that uses the `StartNow` method to trigger the job to run now:
```csharp
public class MyLogWorker : QuartzBackgroundWorkerBase
{
    public MyLogWorker()
    {
        JobDetail = JobBuilder.Create<MyLogWorker>().WithIdentity(nameof(MyLogWorker)).Build();
        Trigger = TriggerBuilder.Create().WithIdentity(nameof(MyLogWorker)).StartNow().Build();
    }

    public override Task Execute(IJobExecutionContext context)
    {
        Logger.LogInformation("Executed MyLogWorker..!");
        return Task.CompletedTask;
    }
}

```

See more: https://docs.abp.io/en/abp/latest/Background-Workers-Quartz

---

Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Comment by sebitsi** [comment]
Thank you both.
