### ISSUE TITLE
Autofac module depend on Castle

### ISSUE THREAD

**Issue by nhant-tpg** [abpframework/abp#15777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[AbpAutofacModule.cs](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Autofac/Volo/Abp/Autofac/AbpAutofacModule.cs)

There are no reason for Autofac depend on Castle.Core

### Reproduction Steps

The project build error when using Castle Windsor

### Version

7.0.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/issues/1110

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
