### ISSUE TITLE
Fails to deserialize event data from outbox when publishing message using AbpAspNetCoreMvcDaprEventBusModule

### ISSUE THREAD

**Issue by bos-npaayush** [abpframework/abp#15778]
public override async Task PublishManyFromOutboxAsync(IEnumerable<OutgoingEventInfo> outgoingEvents, OutboxConfig outboxConfig)
    {
        var outgoingEventArray = outgoingEvents.ToArray();
        foreach (var outgoingEvent in outgoingEventArray)
        {
            await PublishToDaprAsync(outgoingEvent.EventName, Serializer.Deserialize(outgoingEvent.EventData, GetEventType(outgoingEvent.EventName)));
        }
    }

GetEventType(outgoingEvent.EventName) returns null if ETO with this eventname does not have a subscriber that implements IDistributedEventHandler interface.

I am not sure if this is an issue or if I am missing something else.

**Comment by maliming** [comment]
Your ABP Framework version.
Exception message and stack trace if available (check the logs).
Steps needed to reproduce the problem.

**Comment by bos-npaayush** [comment]
> Your ABP Framework version. Exception message and stack trace if available (check the logs). Steps needed to reproduce the problem.

**ABP Framework version** 5.3.3

**Exception:**
{"@t":"2023-02-21T13:04:45.9536662Z","@mt":"Value cannot be null. (Parameter 'returnType')","@l":"Error","@x":"System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')\r\n   at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String parameterName)\r\n   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)\r\n   at Volo.Abp.Json.SystemTextJson.AbpSystemTextJsonSerializerProvider.Deserialize(Type type, String jsonString, Boolean camelCase)\r\n   at Volo.Abp.Json.AbpHybridJsonSerializer.Deserialize(Type type, String jsonString, Boolean camelCase)\r\n   at Volo.Abp.Dapr.Utf8JsonDaprSerializer.Deserialize(Byte[] value, Type type) in E:\\src\\Volo.Abp.Dapr\\Volo\\Abp\\Dapr\\Utf8JsonDaprSerializer.cs:line 24\r\n   at Volo.Abp.EventBus.Dapr.DaprDistributedEventBus.PublishManyFromOutboxAsync(IEnumerable`1 outgoingEvents, OutboxConfig outboxConfig) in E:\\src\\Volo.Abp.EventBus.Dapr\\Volo\\Abp\\EventBus\\Dapr\\DaprDistributedEventBus.cs:line 161\r\n   at Volo.Abp.EventBus.Boxes.OutboxSender.PublishOutgoingMessagesInBatchAsync(List`1 waitingEvents)\r\n   at Volo.Abp.EventBus.Boxes.OutboxSender.RunAsync()\r\n   at Volo.Abp.EventBus.Boxes.OutboxSender.RunAsync()\r\n   at Volo.Abp.EventBus.Boxes.OutboxSender.TimerOnElapsed(AbpAsyncTimer arg)\r\n   at Volo.Abp.Threading.AbpAsyncTimer.Timer_Elapsed()","SourceContext":"Volo.Abp.Threading.AbpAsyncTimer"}
{"@t":"2023-02-21T13:04:46.5714976Z","@mt":"Found 1 events in the outbox.","SourceContext":"Volo.Abp.EventBus.Boxes.OutboxSender"}

**Background Description**
I am trying to replace AbpEventBusRabbitMqModule with AbpAspNetCoreMvcDaprEventBusModule in one of the old project that uses ABP Framework 5. I added four projects from ABP 7 to my project solution
Volo.Abp.AspNetCore.Mvc.Dapr
Volo.Abp.AspNetCore.Mvc.Dapr.EventBus
Volo.Abp.Dapr
Volo.Abp.EventBus.Dapr

Downgraded their dependencies from ABP 7 to ABP 5 and used AbpAspNetCoreMvcDaprEventBusModule as project reference rather than package reference in my .csproj file. I cannot upgrade my project from ABP 5 to ABP 7  because of the Identity Server but if I could use DaprEventBusModule, that would be great. I adapted Eshop On Abp microservice template for my project.

Everything works fine. I am able to publish and subscribe using Dapr PubSub Component when Inbox/Outbox pattern is disabled. But when Inbox/Outbox pattern is enabled, it fails to deserialize event data from outbox as only ETOs that has an event handler that implements IDistributedEventHandler interface are auto discovered and registered into DaprDistributedEventBus.EventTypes. Hence when publishing messages,
public Type GetEventType(string eventName)
    {
        return EventTypes.GetOrDefault(eventName);
    }
this returns null

**Comment by maliming** [comment]
hi


Can you share some code to reproduce it with `5.3.3` template project?

**Comment by bos-npaayush** [comment]
> hi
> 
> Can you share some code to reproduce it with `5.3.3` template project?

Noted. I will share with you asap.

**Comment by bos-npaayush** [comment]
> hi
> 
> Can you share some code to reproduce it with `5.3.3` template project?

Please find project @ https://github.com/bos-npaayush/dapr-event-bus.git

Setup Instructions @ https://github.com/bos-npaayush/dapr-event-bus/blob/main/readme.md

Please let me know if you have any issues with setup.
Thank you very much for your kind support.

**Comment by bos-npaayush** [comment]
@maliming Hi. did you manage to replicate the issue?

**Comment by maliming** [comment]
hi

Im working on other things, I will check it later.
