### ISSUE TITLE
Could AbpRole have the audit information 

### ISSUE THREAD

**Issue by yaohaizh** [abpframework/abp#15776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Current `IdentityUser` inherits from the FullAuditedAggregateRoot class while `IdentityRole` inherits from `AggregateRoot` which is without audit information. Quite curious about the reason behind this design decision. And is there anyway that we can add audit information to the IdentityRole instance?  

### Describe the solution you'd like

Making the `IdentityRole` auditable would be great. At least provide some extensibility.

**Comment by berkansasmaz** [comment]
Hi @yaohaizh, the answers to your questions can be found [here](https://support.abp.io/QA/Questions/508/Auditing-requirements-for-VoloAbpIdentityIdentityRole).

**Comment by yaohaizh** [comment]
@berkansasmaz thanks a lot for the replies.

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions 🥳
