### ISSUE TITLE
Improve filter/search of ABP Documents

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#15787]
We currently have a "filter topics" and "search in documents" textboxes in the docs.abp.io website:

![image](https://user-images.githubusercontent.com/1210527/220893060-03c8c6ac-dc5d-4c5f-b5f9-632c4a564bea.png)

Currently;

* "Filter topics" is used to filter the document navigation tree, by removing non-matched items from the navigation tree when you type. It doesn't filter by document contents. It only works with titles seen in the navigation tree.
* "search in documents" on the other hand searches in the contents of all documents (using Elastic Search) and shows a list of matched documents in a new page.

As far as we can see, some users confuse these. 

My suggestion is;

* Unify these textboxes by removing the "search in documents" one.
* Rename "filter topics" to "Search".
* When user start typing, auto-filter the navigation tree and also show a link over the tree (just below the search box) like "Search in the all documents". If user clicks this link or presses ENTER key, then open the current search page and show the results just like previous.

With this new design, we can easily filter the navigation tree. If we can't find the document we are looking for, we can just press ENTER (or click the link) to search in the entire documentation website.

**Comment by ebicoglu** [comment]
We can do it like Microsoft documentation
https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio
![image](https://user-images.githubusercontent.com/9526587/224914558-fb0b3376-4b1c-487d-ad3f-bc831591ee3b.png)
