### ISSUE TITLE
how to inject a repository to the child class of ITokenExtensionGrant

### ISSUE THREAD

**Issue by holyrong** [abpframework/abp#15784]
abp version: 7.0.2

I want to create a custom grant flow with OpenIdDict (followed the article:https://community.abp.io/posts/how-to-add-a-custom-grant-type-in-openiddict.-6v0df94z)

I created a class like this:
`
public class MyTokenExtensionGrant : ITokenExtensionGrant
{
        public MyTokenExtensionGrant (IUnionUserRepository unionUserRepository)
        {
            UnionUserRepository = unionUserRepository;
        }
}
`

but when I configure the grant type in MyProjectHostModule，
I got an issue about new MyTokenExtensionGrant(),
the constructor has a parameter,
 **how can I pass the unionUserRepository to new MyTokenExtensionGrant() ?**

`Configure<AbpOpenIddictExtensionGrantsOptions>(options =>
        {
            options.Grants.Add(
                DataSeedConsts.GrantTypes.HolyUnion, 
new MyTokenExtensionGrant());
        });`

**Why not add a way to add the custom grant type like IdentityServer?**
`
context.Services.PreConfigure<IIdentityServerBuilder>(builder =>
            {
                builder.AddExtensionGrantValidator<MyGrantValidator>();
            });
`

**Comment by berkansasmaz** [comment]
> how can I pass the unionUserRepository to new MyTokenExtensionGrant() ?

See:
- https://github.com/abpframework/abp/issues/13857#issuecomment-1230210608
- https://github.com/abpframework/abp/blob/ee730b6574409fa60a0ef13bba3fa060042778c7/modules/openiddict/app/OpenIddict.Demo.Server/ExtensionGrants/MyTokenExtensionGrant.cs#L46

--- 

>   Why not add a way to add the custom grant type like IdentityServer?

Thank you very much for your suggestion, I can say that the OpenIddict section is also very simple and similar IdentityServer section, but we will definitely consider your suggestion.

--- 

Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Comment by maliming** [comment]
hi

You can add your `extension grant` class to DI.

> If you inject a lot of services in the constructor that you don't use it will cause a performance issue.

```cs
context.Services.AddOptions<AbpOpenIddictExtensionGrantsOptions>().Configure<IServiceProvider>((options, serviceProvider) =>
  {
      options.Grants.Add(MyTokenExtensionGrant.ExtensionGrantName, serviceProvider.GetRequiredService<MyTokenExtensionGrant>());
  });
```

```cs
public class MyTokenExtensionGrant : ITokenExtensionGrant, ITransientDependency
{
    private readonly IOpenIddictServerFactory _openIddictServerFactory;
    private readonly IOpenIddictServerDispatcher _openIddictServerDispatcher;

    public MyTokenExtensionGrant(IOpenIddictServerFactory openIddictServerFactory, IOpenIddictServerDispatcher openIddictServerDispatcher)
    {
        _openIddictServerFactory = openIddictServerFactory;
        _openIddictServerDispatcher = openIddictServerDispatcher;
    }
}
```
