### ISSUE TITLE
Volo.Abp.EventBus.Azure' nuget package could not be found!

### ISSUE THREAD

**Issue by roger-cprops** [abpframework/abp#15795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Getting Volo.Abp.EventBus.Azure' nuget package could not be found! error when running abp add-package Volo.Abp.EventBus.Azure.

Also tried adding it using Visual Studio Nuget Package Manager with the same result.

### Reproduction Steps

In a terminal window navigate to Abp project directory
Enter the command **abp add-package Volo.Abp.EventBus.Azure**

### Expected behavior

Should install package

### Actual behavior

Error package not found

### Version

7.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

This is critical as we're trying to use the Azure Service Bus package for distributed events

**Comment by maliming** [comment]
hi

https://www.nuget.org/packages/Volo.Abp.EventBus.Azure/

**Comment by roger-cprops** [comment]
Hi,

We have tried ever method to download the package including the methods in the link you sent.

I see the package was updated 2 days ago.  Has anyone on your end made sure it works?

**Comment by roger-cprops** [comment]
Have an update for you.  It appears that we only get the error when trying to install in an existing project.

We created a new solution and a new project and were able to get it installed.  So your developer may need to look into what's breaking trying to install it in an existing project.

**Comment by berkansasmaz** [comment]
Hi @roger-cprops, thank you for your detailed explanations. It seems there is a problem with our CLI. Because when I try to install the package manually, there is no problem, but if I try to add the `Volo.Abp.EventBus.Azure` package with the `add-package` command in the CLI, I get the error you specified.

 **Workaround:** you can refer to [this document ](https://docs.abp.io/en/abp/latest/Distributed-Event-Bus-Azure-Integration#installation)already as you know.

**Comment by berkansasmaz** [comment]
Thank you @yekalkan, added this package to the place where we keep the list of our packages on our website and the problem was solved.

---

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
