### ISSUE TITLE
FakeCurrentPrincipalAccessor UserId is not the Same used by IdentityUserManager

### ISSUE THREAD

**Issue by leaortiz** [abpframework/abp#15799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you create a new solution and apply migrations, it will seed an Admin user with an auto generated Id
which is not the same as we have under FakeCurrentPrincipalAccessor GetPrincipal()

### Reproduction Steps

Create a new ABP 5.3.4 solution, 
Create a new test in the application layer
Update the admin user using the ProfileAppService

Did it because I extended the ProfileAppService and wanted to test my code, but there's no need to follow this step

### Expected behavior

The admin user will get updated

### Actual behavior

EntityNotFoundException is thrown

### Known Workarounds

Seed a new user with the Id we get from FakeCurrentPrincipalAccessor which is   
new Claim(AbpClaimTypes.UserId,"2e701e62-0953-4dd3-910b-dc6cc93ccb0d"),

### Version

5.3.4

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

If you get IRepository<IdentityUser, Guid> and do a GetListAsync you will see the admin user has another Id

**Comment by maliming** [comment]
hi

You can mock the current user with a real user.

https://github.com/abpframework/abp/blob/dev/modules/cms-kit/test/Volo.CmsKit.Application.Tests/Tags/TagAdminAppService_Tests.cs#L26
