### ISSUE TITLE
Xamarin infrastructure

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#158]
Should create a framework that is integrated to ABP for Xamarin.

**Comment by ktngoykalolo** [comment]
could we reuse an existing framework such as MVVMCross ? an integration could be interesting

**Comment by hikalkan** [comment]
Maybe. But, to be honest, Xamarin UI has very low priority for ABP.

**Comment by ricavir11** [comment]
Why Xamarin has a low priority for ABP ? It is a very good framework that is always improving. I learned it with aspnetboilerplate... the learning curve can be high but the result is great ; event for UWP apps. Also fits well with .NET developpers.
Should be great to have a base project also for abp (commercial?).
 
What is your plans about MAUI (.NET 5) ?

**Comment by hikalkan** [comment]
We haven't worked on MAUI. So, no idea yet.

Xamarin has low priority doesn't mean it is not good. We have limited development resource and we should focus on some other fundamental things on the framework.

**Comment by a-urel** [comment]
@hikalkan a Xamarin framework requires too much time and resource, for sure. But `Acme Bookstore` samples (w/ Xamarin, and even Flutter, Kotlin, Swift, ...) which access `Abp API` and perform CRUD operations would be totally fine. IMO, UI generation is not critical in this case.

**Comment by hikalkan** [comment]
To be honest, we don't have motivation to work on a Xamarin infrastructure now :)
For mobile, we now have a React Native option.
Consuming REST APIs and authentication though OAuth protocol is pretty standard actually, so you can use any mobile/web framework with the ABP Framework.
However, it would be good to write ABP Community articles to demonstre it, I agree. I created an issue for Xamarin: https://github.com/abpframework/abp/issues/7289

**Comment by enisn** [comment]
Since we've added MAUI in v6.0, this issue can be closed
