### ISSUE TITLE
Remove setter for IEntity<TKey>.Id

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1580]

**Comment by tomlewandowski** [comment]
Should the seters be removed from these classes and interfaces too?
IHasConcurrencyStamp
FullAuditedAggregateRoot

**Comment by hikalkan** [comment]
I am not sure, I will think about it while implementing this. Thanks for the additional info.

**Comment by hikalkan** [comment]
- I removed setter for IEntity<TKey>.Id, so ABP now doesn't force an entity with public setter.
- I also made Id property protected in the base entity/aggregateroot classes.

**Comment by gdlcf88** [comment]
Finally, developers learn DDD. >o<
