### ISSUE TITLE
how to hide the user's email list

### ISSUE THREAD

**Issue by xiaoyuer1015** [abpframework/abp#15811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

how to hide the user's email list in [Identity management].

### Describe the solution you'd like

how to hide the user's email list in [Identity management].

**Comment by maliming** [comment]
What is your UI type?

**Comment by xiaoyuer1015** [comment]
![image](https://user-images.githubusercontent.com/10320363/221486588-33da4465-5b4c-4259-ad4f-08f6e8b237c7.png)

**Comment by maliming** [comment]
Is it Mvc or Blazor or angular?

**Comment by xiaoyuer1015** [comment]
Blazor

**Comment by xiaoyuer1015** [comment]
Mvc

**Comment by maliming** [comment]
hi

https://docs.abp.io/en/abp/latest/UI/AspNetCore/Data-Table-Column-Extensions

**Comment by xiaoyuer1015** [comment]
Thank you!maliming. It is OK！

**Comment by xiaoyuer1015** [comment]
![image](https://user-images.githubusercontent.com/10320363/221566136-3cee6c79-4f44-44b3-a023-6bb5480b0017.png)
It is hidden. How to set up by JS.

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface

**Comment by xiaoyuer1015** [comment]
[Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(CreateModalModel))]
    public class MyCreateModalModel : CreateModalModel
    {
        public MyCreateModalModel(IIdentityUserAppService identityUserAppService) : base(identityUserAppService)
        {
        }
    }
why MyCreateModalModel  can not be opened when I click the new buttton. Thanks.

**Comment by xiaoyuer1015** [comment]
It is OK. Thank you!

**Comment by xiaoyuer1015** [comment]
![image](https://user-images.githubusercontent.com/10320363/221765421-a3b6fe48-8b4c-4b9f-9e70-0e2ddeade62a.png)
I am sorry. I happen a new problem.

**Comment by xiaoyuer1015** [comment]
public MyCreateModalModel(IIdentityUserAppService identityUserAppService) : base(identityUserAppService)
        {
        }

        public async override Task<IActionResult> OnPostAsync()
        {
            //TODO: Additional logic
            return await base.OnPostAsync();//TODO: Additional logic
        }
The data can not be saved to DB.
