### ISSUE TITLE
Consider bumping OpenIddict to 4.1.0

### ISSUE THREAD

**Issue by kevinchalet** [abpframework/abp#15825]
Hey,

Hope everyone at ABP is doing well 😃 
OpenIddict 4.1.0 just shipped and is a recommended update (release details here, if you're interested: https://github.com/openiddict/openiddict-core/releases/tag/4.1.0).

Let me know if you have any question.
Cheers!

**Comment by maliming** [comment]
Thanks @kevinchalet
