### ISSUE TITLE
Logout redirect not working

### ISSUE THREAD

**Issue by merijng** [abpframework/abp#15835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Is it true that it is currently impossible to redirect the OpenIddict OpenId logout page, to the client's logout page?

### Reproduction Steps

- Create a new ABP project with OpenIddict
- Create a new Application under Administration =>OpenId => Applications
- Make sure "Allow Logout Endpoint" is configured, and add a dummy redirect url
- Now go to the logout page
  - https://{your url}/api/account/logout?client_id={clientid}&Return_url={your dummy redirect url}
- Note that you won't get redirected

### Expected behavior

User get's redirected to the client redirect url

**Flow should be:**
- Client redirects user to logout page
- ABP logs the user out
- ABP redirects user back to the client (to the redirect page)

### Actual behavior

No redirection is happening. 204-content = the status code.

**Request**
GET https://{your url}/api/account/logout?client_id={clientid}&Return_url={your dummy redirect url} HTTP/1.1
Host: ...
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: ...
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Sec-GPC: 1
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,nl;q=0.8
Cookie: ARRAffinity={}

**Response**
HTTP/1.1 204 No Content
Content-Length: 0
Date: Tue, 28 Feb 2023 11:07:11 GMT
Server: Kestrel
Cache-Control: no-cache,no-store
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Set-Cookie: .AspNetCore.Identity.Application=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; secure; samesite=lax; httponly
Set-Cookie: Identity.External=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; secure; samesite=lax; httponly
Set-Cookie: Identity.TwoFactorUserId=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; secure; samesite=lax; httponly
Request-Context: appId=...
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

### Known Workarounds

Modify/override the [OpenIddict logout controller](https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/LogoutController.cs).

### Version

6.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Thanks @merijng

**Comment by merijng** [comment]
@maliming Shouldn't this be merged with 6.x-patch, either?

**Comment by maliming** [comment]
hi

Yes. I will push the commit to 6.x.
