### ISSUE TITLE
External Auth [Angular Account Module]

### ISSUE THREAD

**Issue by joernz** [abpframework/abp#15839]
### Describe the solution you'd like

If I am not mistaking, the login page of [angular account module with ResourceOwnerPassword auth flow](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/account/src/lib/components/login/login.component.ts) hasn't implemented the buttons and functions for external auth.

Would be nice to see it implemented finally. If it's reserved for commercial only, could you please point me the way how to do it by myself? Thanks!

**Comment by mahmut-gundogdu** [comment]
The lack of issue is not only for ABP. The feautre doesn't exists in Comercial too. (on the angular, MVC has it)

**Comment by mahmut-gundogdu** [comment]
We now use that functionality provided by the ngx-validation library in the abp. It 've  closed by me.
