### ISSUE TITLE
Physical Files not override the virtual files.

### ISSUE THREAD

**Issue by ohroy** [abpframework/abp#15844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The document said https://docs.abp.io/en/abp/latest/Virtual-File-System#physical-files

> Physical files always override the virtual files. That means if you put a file under the /wwwroot/my-folder/my-file.css, it will override the file in the same location of the virtual file system. So, you need to know the file paths defined in the modules to override them.

But when I do it like that, it does not work at all in `Production` mode.
When I debug it, the FileProviders does not have any provider like PhysicalFileProvider, see image below.
![image](https://user-images.githubusercontent.com/7907969/222124393-8e0a8041-8bf4-40be-abfa-84817929f6e9.png)

### Reproduction Steps

Just do it like the document https://docs.abp.io/en/abp/latest/Virtual-File-System#installation
And then create a controller 
HomeController
```c#
    public async Task<IActionResult> Index()
    {
        var info = _virtualFileProvider.GetFileInfo("/Resources/test/index.html");
        var txt = await info.ReadAsStringAsync();
        return Content(txt, "text/html");
    }
```
Test it in debug mode , and change the `/Resources/test/index.html` it will work.
Test it in Production mode, and then change the `/Resources/test/index.html` and `wwwroot/Resources/test/index.html` it will not work.

### Version

7.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

BTW, I want to change the test/index.html dynamic, is that a right way?

**Comment by ohroy** [comment]
May be it should enable by manual like the document said develop node?
```c#
            Configure<AbpVirtualFileSystemOptions>(options =>
            {
                options.FileSets.ReplaceEmbeddedByPhysical<MyWebModule>(hostingEnvironment.WebRootPath);
            });
```
In this case, I understand wrong. I think this replacement is automatic. cause the document said
> Physical files **always** override the virtual files.
 
Can we consider updating the document to avoid this confusion?

**Comment by DHclly** [comment]
> May be it should enable by manual like the document said develop node?
> 
> ```cs
>             Configure<AbpVirtualFileSystemOptions>(options =>
>             {
>                 options.FileSets.ReplaceEmbeddedByPhysical<MyWebModule>(hostingEnvironment.WebRootPath);
>             });
> ```
> 
> In this case, I understand wrong. I think this replacement is automatic. cause the document said
> 
> > Physical files **always** override the virtual files.
> 
> Can we consider updating the document to avoid this confusion?

use this way,the embedded files is useless，the abp framework will always use the physical files，if the physical files is not exist ,it will throw a exception，not use embedded file in same  file path. 

so ,I think if the files need to edit by outside ,do not use as embedded files, copy to publish folder is good job.

use this strategy

```
<Content Update="Localization\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

**Comment by ohroy** [comment]
正如你所说，这样做的话embedded file就失去了它存在的意义。我认为这是abp的bug，因为和文档描述的不太一样。但是官方好像对这个问题没有回复。

**Comment by DHclly** [comment]
> 正如你所说，这样做的话embedded file就失去了它存在的意义。我认为这是abp的bug，因为和文档描述的不太一样。但是官方好像对这个问题没有回复。

是的，确实是个bug，太坑了，我研究了半天的用法，麻了
