### ISSUE TITLE
Query params of DevExpress DataSourceLoadOptions class were removed when proxying via API gateway (YARP)

### ISSUE THREAD

**Issue by duyan11110** [abpframework/abp#15840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I use YARP as an API gateway and DevExpress for ASP.net Core for UI in my microservice solution.
UI code (port 7004)
```
gItems.AddSimpleFor(c => c.CustomerID).ColSpan(2)
                .Label(l => l.Text(@L["utim_form_CustomerAbbr"]).ShowColon(false))
                .Editor(e => e.SelectBox()
                    .DataSource(d => d.RemoteController()
                        .LoadUrl("/api/customer-service/customer/basic-list")
                        .Key("customerID")
                    )
                    .DataSourceOptions(c => c.Paginate(true).PageSize(10))                    
                    .ID("sb_customer")
                    .SearchEnabled(true)
                    .OnValueChanged("onChangedCustomerAbbr")
                    .ElementAttr("customerName", "customerName")
                    .DisplayExpr("customerAbbr")
                    .ValueExpr("customerID")
                    .ShowClearButton(true)
                );
```
Back-end code (port 7006)
```
public async Task<LoadResult> GetBasicListAsync(DataSourceLoadOptions loadOptions)
        {
            int companyId = 1;
            var customers = await _customerRepository.GetQueryableAsync();
            var query = (from c in customers
                         where c.CompanyID == companyId
                        select new
                        {
                            c.CustomerID,
                            c.CustomerAbbr,
                            c.CustomerName,
                            c.Address
                        });

            return await DataSourceLoader.LoadAsync(query, loadOptions);
        }
```
DataSourceLoadOptions properties:
```
{
  "requireTotalCount": true,
  "requireGroupCount": true,
  "isCountQuery": true,
  "isSummaryQuery": true,
  "skip": 0,
  "take": 0,
  "sort": [
    {
      "selector": "string",
      "desc": true
    }
  ],
  "group": [
    {
      "selector": "string",
      "desc": true,
      "groupInterval": "string",
      "isExpanded": true
    }
  ],
  "filter": [
    "string"
  ],
  "totalSummary": [
    {
      "selector": "string",
      "summaryType": "string"
    }
  ],
  "groupSummary": [
    {
      "selector": "string",
      "summaryType": "string"
    }
  ],
  "select": [
    "string"
  ],
  "preSelect": [
    "string"
  ],
  "remoteSelect": true,
  "remoteGrouping": true,
  "expandLinqSumType": true,
  "primaryKey": [
    "string"
  ],
  "defaultSort": "string",
  "stringToLower": true,
  "paginateViaPrimaryKey": true,
  "sortByPrimaryKey": true,
  "allowAsyncOverSync": true
}
```
YARP config (port 7500)
```
{
  "ReverseProxy": {
    "Routes": {
      "Customer Service": {
        "ClusterId": "customerCluster",
        "Match": {
          "Path": "/api/customer-service/{**everything}"
        }
      }
    },
    "Clusters": {
      "customerCluster": {
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:7006"
          }
        }
      }
    }
  }
}
```
When running my solution, in Chrome Developer tool, I see client sent correct request like this: `https://localhost:7004/api/customer-service/customer/basic-list?skip=0&take=10` but on the gateway, it only received this url:
```
2023-02-17 16:36:07.006 +07:00 [INF] Request starting HTTP/1.1 GET https://localhost:7500/api/customer-service/customer/basic-list?api-version=1.0 - -
2023-02-17 16:36:07.007 +07:00 [INF] Executing endpoint 'Customer Service'
2023-02-17 16:36:07.007 +07:00 [INF] Proxying to https://localhost:7006/api/customer-service/customer/basic-list?api-version=1.0 HTTP/2 RequestVersionOrLower no-streaming
2023-02-17 16:36:07.043 +07:00 [INF] Received HTTP/2.0 response 200.
```
As you can see, the part of `skip=0&take=10` was removed.

### Reproduction Steps

Sample here: https://github.com/duyan11110/MicroserviceSample
Steps to reproduce:
1. Open Sample.sln, add DevExpress nuget packages and make sure to build successfully
2. Change connection string in all appsettings.json files
3. In shared folder, run Sample.DbMigrator **twice**
4. Pull RabbitMq and Redis and run following commands:
docker run -it --rm --name localhost -p 5672:5672 -p 15672:15672 rabbitmq:latest
docker run -it --rm --name redislocal -p 6379:6379 redis:latest
5. Open terminal in root folder and run: tye run --watch
6. View tye dashboard at: http://localhost:8000/
7. Open UI at: http://localhost:7004/
8. Login with this account: admin/1q2w3E*
9. Open Develop Tool on Chrome/Firefox/...
10. Click on Menu:Test1 -> UTI -> UTI Maintenance by Ct Party menu, in Network tab, you will see this API: `http://localhost:7004/api/test1-service/u-tIMaintenance-by-ct-party?skip=0&take=100&requireTotalCount=true&value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&_=1677576922079`, but check on the gateway:
```
[gateway_2e90f858-3]: [16:35:25 INF] Request starting HTTP/1.1 GET http://localhost:7500/api/test1-service/u-tIMaintenance-by-ct-party?value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&api-version=1.0 - -
[gateway_2e90f858-3]: [16:35:25 INF] Executing endpoint 'Test1 Service'
[gateway_2e90f858-3]: [16:35:25 INF] Proxying to http://localhost:7005/api/test1-service/u-tIMaintenance-by-ct-party?value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&api-version=1.0 HTTP/2 RequestVersionOrLower no-streaming
[gateway_2e90f858-3]: [16:35:27 INF] Received HTTP/1.1 response 200.
[gateway_2e90f858-3]: [16:35:27 INF] Executed endpoint 'Test1 Service'
[gateway_2e90f858-3]: [16:35:27 INF] Request finished HTTP/1.1 GET http://localhost:7500/api/test1-service/u-tIMaintenance-by-ct-party?value=%7B%22InputDateFrom%22%3A%222023-02-28%22%2C%22InputDateTo%22%3A%222023-02-28%22%7D&api-version=1.0 - - - 200 - application/json;+charset=utf-8 2422.9062ms
```
11. Click on the arrow of Customer Abbr dropdown box, you will see this API in Network tab: `http://localhost:7004/api/customer-service/customer/basic-list?skip=0&take=10&_=1677576922080`, and check the gateway again:
```
[gateway_2e90f858-3]: [16:42:00 INF] Request starting HTTP/1.1 GET http://localhost:7500/api/customer-service/customer/basic-list?api-version=1.0 - -
[gateway_2e90f858-3]: [16:42:00 INF] Executing endpoint 'Customer Service'
[gateway_2e90f858-3]: [16:42:00 INF] Proxying to http://localhost:7006/api/customer-service/customer/basic-list?api-version=1.0 HTTP/2 RequestVersionOrLower no-streaming
[gateway_2e90f858-3]: [16:42:00 INF] Received HTTP/1.1 response 200.
[gateway_2e90f858-3]: [16:42:00 INF] Executed endpoint 'Customer Service'
[gateway_2e90f858-3]: [16:42:00 INF] Request finished HTTP/1.1 GET http://localhost:7500/api/customer-service/customer/basic-list?api-version=1.0 - - - 200 - application/json;+charset=utf-8 27.0743ms
```

### Version

7.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
After some research, I saw that you were creating issues in [YARP](https://github.com/microsoft/reverse-proxy/issues/2047) and [DevExpress](https://supportcenter.devexpress.com/ticket/details/t1148907/yarp-api-gateway-not-recognized-datasourceloadoptions-class), and did some research. One of the most likely problems is due to capitalization difference. I came to this conclusion after reading [this comment ](https://support.abp.io/QA/Questions/1423/How-to-access-entities-from-public-website#answer-75fe0539-eb76-861b-f232-39fcd8ea9c3f)on support.abp.io.

See more: https://support.abp.io/QA/Questions/1423/How-to-access-entities-from-public-website
> Regarding PascalCase/ camelCase: The community article suggests to use JsonProperty attributes to change ABP's behaviour of converting names to camelCase. I don't do this as I prefer camelCase in json objects. If you don't set JsonProperty, you can just use id or productName as field names (as in my snippet above) instead of Id or ProductName. However, if you want to use columns.AddFor(m => m.ProductName); it won't work with pascalCase. Therefore I created an extension method AddCamelCaseFor as suggested by DevExpress Support ([How to enable camel case for DevExtreme MVC Controls](https://supportcenter.devexpress.com/ticket/details/t584059/how-to-enable-camel-case-for-devextreme-mvc-controlshttps://supportcenter.devexpress.com/ticket/details/t584059/how-to-enable-camel-case-for-devextreme-mvc-controls) / [MVC Controls - How to allow CamelCase for AddFor methods](https://supportcenter.devexpress.com/ticket/details/t578340/mvc-controls-how-to-allow-camelcase-for-addfor-methods#).

See more: https://community.abp.io/posts/using-devextreme-components-with-the-abp-framework-zb8z7yqv
> You can see some JsonProperty attributes on the DTO properties. I use these attributes because DevExtreme example expects PascalCase property names in the serialized JSON that is sent to the client. But ABP Framework & ASP.NET Core conventionally uses camelCase property names on JSON serialization. Adding these JsonProperty attributes ensures that the related properties are serialized as PascalCase. 

As a result, can you activate camelCase on the DevExpress side, test it again and share the results with us?

**Comment by duyan11110** [comment]
> As a result, can you activate camelCase on the DevExpress side, test it again and share the results with us?
You mean that I have to activate camelCase for `DataSourceLoadOptions` class, right? If so, I can't, DevExpress doesn't support it. I still don't understand why client sent correct request, but removed when proxying via the gateway? As you can see here: https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1dcc20e6db209987c5634db79ea5997e9ef00ac8/net/DevExtreme.AspNet.Data/Helpers/DataSourceLoadOptionsParser.cs#L33
DevExpress needs correct params to parse `DataSourceLoadOptions` class. Is there any way to keep the query params of requests after proxying via the gateway the same as the client sent?

**Comment by duyan11110** [comment]
@berkansasmaz any update, pls?

**Comment by berkansasmaz** [comment]
Sorry, I have no idea about this. I don't want to mislead you as I don't understand what is causing the problem. However, if you accept the advice, you can create a controller on the UI side to minimize the probability surface, use this controller for DevExpress component, and test it. Thus, I think we can understand whether the problem stems from YARP or from somewhere else. Also, I think it would be easier to understand and solve the problem later in this way.
