### ISSUE TITLE
Languages obtained from ConfigStateService contain duplicates

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#15859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The list of languages, obtained from `ConfigStateService` contains duplucates which slightly differ by properties:

![image](https://user-images.githubusercontent.com/6149843/222463458-401e4872-e04a-402c-8234-b24226f94825.png)

As a result:

![image](https://user-images.githubusercontent.com/6149843/222463711-eb9f9dfa-1c0e-451e-9196-40116c8de53e.png)

We use a custom Languages component. But it's not supposed to affect the data returned by `ConfigStateService`. So how come that the service returns duplicates? Could you please suggest how to backtrack the issue?

### Version

7.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by bariscanyilmaz** [comment]
Hi @alexandis, can you give more detail how to reproduce this bug? What kind of changes you did? If you can share a demo that producing same bug it would be great.

**Comment by alexandis** [comment]
I didn't do anything special... This behavior occurred after upgrading from v5.1.2 to v.7.0.1. We have been using a "custom" language component and did not have this strange behavior before. Unfortunately, I cannot share the functioning project, because it's a part of a big commercial solution, just the [component code itself](https://drive.google.com/open?id=117yI5OvhOSRogsPwRcRr0u064MbC1uwf&authuser=alexandis%40gmail.com&usp=drive_fs)

**Comment by bariscanyilmaz** [comment]
Did you read migration guides.

* [ABP Framework](https://docs.abp.io/en/abp/latest/Migration-Guides/Index)
* [ABP Commercial](https://docs.abp.io/en/commercial/latest/migration-guides/index)

There made a lot of changes in localization. Checkout [localization changes](https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-7_0#external-localization-infrastructure) from v6.0 to v7.0

**Comment by alexandis** [comment]
I did read it before, but I cannot see anything that I might be missing to do to cause this. It looks like the language data is obtained twice, but the second time the object storing it is not cleared before:

![image](https://user-images.githubusercontent.com/6149843/223672229-42f15ba3-405e-46e7-b3ee-937dd8af19e4.png)

**Comment by bariscanyilmaz** [comment]
Hi @alexandis, I created a project with version 5.3 then I updated it to 7.1. Hovewer, I haven't faced any bug that you have had. I can only suggest you to solve this problem just use `filter` function to get appropitate languages. 

Use filtering function in your language component like below.

```
languages=languages.filter(x=>x.twoLetterISOLanguageName) 
```
