### ISSUE TITLE
All properties of `ICurrentUser` are empty when sign by using HttpContext.SignInAsync method in MVC

### ISSUE THREAD

**Issue by xixixixixiao** [abpframework/abp#15862]
### Description

I created a new empty `MVC` project.
I reference the official documentation to set up remote API accessing correctly.
I request a `UserInfo` according to the code in the demo project `OpenIddict.Demo.Client.Console` of the OpenIddict solution in the repository.
I log in the user by `HttpContext.SignInAsync` using the `UserInfo`.
The instance of ICurrent is not set correctly when I visit other pages again. Its properties are all default values.

### ABP Framework version

`7.0.2`

### User Interface

`MVC` and `Angular`

### Database provider

`EF Core`

### Actual behavior

Properties of the instance of `ICurrentUser` are the default values when the logged user accessing the page.

### Expected behavior

Properties of the instance of `ICurrentUser` are same  the current logged in user's.

### Reproducible Steps

1. Create a `MVC` project.
2. Request the `UserInfo`.
3. Sign in by the `UserInfo`.

#### Sign
```cs
using var http = new HttpClient();
var configuration = await http.GetDiscoveryDocumentAsync("https://localhost:44397");
if (configuration.IsError)
{
    throw new Exception(configuration.Error);
}

var passwordTokenRequest = new PasswordTokenRequest
{
    Address = configuration.TokenEndpoint,
    ClientId = "BookStore_App",
    UserName = "admin",
    Password = "1q2w3E*",
    Scope = string.Join(" ", new[]
    {
        "address",
        "email",
        "phone",
        "profile",
        "roles",
        "BookStore"
    }),
};
var tokenResponse = await http.RequestPasswordTokenAsync(passwordTokenRequest);
if (tokenResponse.IsError)
{
    throw new Exception(tokenResponse.Error);
}

if (string.IsNullOrEmpty(tokenResponse.AccessToken))
{
    throw new ArgumentNullException(nameof(tokenResponse.AccessToken));
}

var userInfoRequest = new UserInfoRequest
{
    Address = configuration.UserInfoEndpoint,
    Token = tokenResponse.AccessToken,
};
var userInfo = await http.GetUserInfoAsync(userInfoRequest);
var principal = new ClaimsPrincipal(
    new ClaimsIdentity(userInfo.Claims, CookieAuthenticationDefaults.AuthenticationScheme));
var props = new AuthenticationProperties();

props.StoreTokens(new[]
{
    new AuthenticationToken { Name = "access_token", Value = tokenResponse.AccessToken }
});
await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, props);
```

### Add Authentication

```cs
context.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = "Cookies";
    })
    .AddCookie("Cookies", options =>
    {
        options.ExpireTimeSpan = TimeSpan.FromDays(365);
    });
```

#### ICurrentUser
```cs
public class IndexModel : PageModel
{
    private readonly ICurrentUser _currentUser;

    public IndexModel(ICurrentUser currentUser)
    {
        _currentUser = currentUser;
    }

    public void OnGet()
    {
        Debug.WriteLine(_currentUser.IsAuthenticated); // false here.
    }
}
```

### Other information

The demo repository:

[https://github.com/xixixixixiao/abp-mvc-login-demo](https://github.com/xixixixixiao/abp-mvc-login-demo)

**Comment by journey191** [comment]
@xixixixixiao Hi,I met a similar problem when I use oidc auth,did you resolve it?
