### ISSUE TITLE
/authentication/login-callback is not found or not access when app is hosted on IIS

### ISSUE THREAD

**Issue by majidsureze** [abpframework/abp#15860]
I host my ABP Web API and Blazor on my server running IIS. I host web API and Blazor app separately. The Web API works as expected and the Blazor app connects to API and works with my application services defined in web API. But the Blazor app has some issues with openIddict I think.
For example when I click the login button the login page opens and I enter the user and pass but when I click to sign in the user becomes signed-in but the app cannot back to the home page because the /authentication/login-callback gives the error _404 - File or directory not found_. 
I almost read all the documents on abp website as well as stackoverflow but I couldn't find a workaround.
Anybody can help me with this?
Thank you

**Comment by omer-repo** [comment]
Did you run DB migration after setting URLs of application. I mean if you change the location or port of applications it may redirect wrong location now.

There is **dbo.OpenIddictApplications** table in database and there are redirection URLs. Can you verify that "RedirectUris" value of "Blazor Application" row; is it same with Blazor web url?

![image](https://i.imgur.com/Ztf5Uou.png)

**Comment by majidsureze** [comment]
Yes, I run the DBMigration. Even I manually check this table in the database. All the URLs are correct.
The login page opens and I enter my username and password and even it is accepted by openIddict but in redirection, I get this error.

**Comment by majidsureze** [comment]
Actually, I published the Blazor app and Web Api separately and as the default configuration, AuthServer is assigned to Web Api project.

**Comment by majidsureze** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/123804581/222760269-d45f861a-1789-4174-9891-3426ec539361.jpg)

**Comment by majidsureze** [comment]
I change the "RedirectUris" for blazor app in DB from **https** to **http** and got the above error. It tried to open the callback page in my api project. 
As you see I successfully logged in to the app now when I click on admin [username] it goes to **swagger** page!
