### ISSUE TITLE
Add Access-Control-Expose-Headers for ABP error response

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1587]
@mehmet-erim says "I can't handle "_AbpErrorFormat" header". It seems we should add Access-Control-Expose-Headers to allow it. See https://stackoverflow.com/questions/51971342/cant-get-headers-of-response-in-angular-5?answertab=active#tab-top

For the simplest solution, we can modify this Access-Control-Expose-Headers header (or add if it does not exists) to add _AbpErrorFormat to the list. We can do this where we return the error response.

**Comment by maliming** [comment]
ok I will try.
