### ISSUE TITLE
Mapping ILocalizableString to string

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#15873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to map a DTO from a object that contains properties of `ILocalizableString` such as:
```
public class Data
{
    public ILocalizableString DisplayName { get; set; }
}

public class DataDto
{
    public string DisplayName { get; set; }
}
```

But I can only get `DisplayName = "Volo.Abp.Localization.LocalizableString"` for now.

### Describe the solution you'd like

I found a solution from aspnetboilerplate project:
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/v8.1/src/Abp.AutoMapper/AutoMapper/AbpAutoMapperModule.cs#L81-L87

Shall we migrate it to the new abp?

**Comment by colinin** [comment]
I think you should need [ILocalizableStringSerializer](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Localization/Volo/Abp/Localization/ILocalizableStringSerializer.cs)

**Comment by PMExtra** [comment]
@colinin Thank you, according to your advices, I made these:
```csharp
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        Configure<AbpAutoMapperOptions>(options =>
        {
            options.Configurators.Add(ConfigureLocalizableStringMappings);
        });
    }

    private void ConfigureLocalizableStringMappings(IAbpAutoMapperConfigurationContext context)
    {
        var serializer = context.ServiceProvider.GetRequiredService<ILocalizableStringSerializer>();
        context.MapperConfiguration.CreateMap<ILocalizableString?, string?>()
            .IncludeAllDerived()
            .ConvertUsing(@string => serializer.Serialize(@string));
        context.MapperConfiguration.CreateMap<string?, ILocalizableString?>()
            .ConvertUsing(@string => serializer.Deserialize(@string));
    }
```

**Comment by PMExtra** [comment]
@maliming 能考虑把这个功能默认加进 `Volo.Abp.AutoMapper` 吗？就像 Asp.Net Boilerplate 那样
