### ISSUE TITLE
Allow to define groups for menu items

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#15883]
Some applications need to have such a grouping in their main menus (`LAYOUTS` and `HELP` for this example screenshot):

![image](https://user-images.githubusercontent.com/1210527/223045803-414602ba-3c9b-4a66-88cb-92420a172786.png)

We can allow to define groups and associate menu items with a group. Then, themes _may_ render the groups.

Example API:

````csharp
    private async Task ConfigureMainMenuAsync(MenuConfigurationContext context)
    {
        var l = context.GetLocalizer<MyProjectResource>();

        context.Menu.AddGroup("Main", l["Main"]); // Create a new group

        context.Menu.AddItem(
            new ApplicationMenuItem("MyProject.Crm", l["Menu:CRM"], groupName: "Main") // set group name for a menu item
                .AddItem(new ApplicationMenuItem(
                    name: "MyProject.Crm.Customers", 
                    displayName: l["Menu:Customers"], 
                    url: "/crm/customers")
                ).AddItem(new ApplicationMenuItem(
                    name: "MyProject.Crm.Orders", 
                    displayName: l["Menu:Orders"],
                    url: "/crm/orders")
                 )
        );
    }
````

Rules:

* Group name is optional for menu items. Also, in practice, only the top level menu items may have group names since sub-items can not be in a different group than the parent's group. However, we won't make such checks. Theme will only consider the top menu item group names.
* `context.Menu` should also have a `Groups` collection, so we may sort items, change their orders or remove some groups in a later contributor.
* If a menu item sets a group, but the is no such a group defined, just ignore it silently.
* The UI theme will decide to render groups or not, and if it decides to render, it is up to theme how to render.
* We won't render groups for the basic and lepton-x-lite themes currently.

**Comment by sturlath** [comment]
> The UI theme will decide to render groups or not, and if it decides to render, it is up to theme how to render.

I guess that means it will be possible to "stick" a group to the bottom (and have the option of having no name) ? Like this here?

![image](https://user-images.githubusercontent.com/2386572/223130579-f4cf54cb-5ba2-4875-b246-ff5a19e28c8f.png)

**Comment by hikalkan** [comment]
A theme can assume a group name, like "Bottom" and place these items at the bottom.
