### ISSUE TITLE
Clear Settings Cache of Blazor Wasm

### ISSUE THREAD

**Issue by omer-repo** [abpframework/abp#15887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm using ISettingManager  to manage settings from Application Layer. Also, using ISettingProvider to get values of settings in Blazor. (Wasm 7.0.1)
But after change values from Blazor Wasm (Blazor => Application Layer), I still get old values from settings. Because **/application-configuration/setting** endpoint should be loaded again. After I refresh page, I can see the new settings. So, I want to trigger a method to refresh this endpoint and load new settings without refreshing all page.

I tried to use **CurrentApplicationConfigurationCacheResetService.ResetAsync()** method but it didn't refresh the setting values. https://github.com/abpframework/abp/blob/c5df521b6c23f4809fed445b35cc0f9b8a5b7184/modules/setting-management/src/Volo.Abp.SettingManagement.Blazor/Pages/SettingManagement/EmailSettingGroup/EmailSettingGroupViewComponent.razor.cs#L73

### Describe the solution you'd like

It will be very useful to use some method like **CurrentApplicationConfigurationCacheResetService.ResetAsync()** and then **/application-configuration/setting** will be loaded again.

**Comment by maliming** [comment]
hi @omer-repo 

Can you test this implementation?

https://github.com/abpframework/abp/pull/15895

**Comment by omer-repo** [comment]
Hi @maliming ,

It worked well. Thank you so much. 

By the way is there a list of such methods and classes we can look and use? For example both **WebAssemblyCachedApplicationConfigurationClient**  and **CurrentApplicationConfigurationCacheResetService** classes are not listed anywhere but they are very useful for Blazor developers.

**Comment by maliming** [comment]
hi

These classes are used internally. You can take the time to review the source code of the module.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/15895
