### ISSUE TITLE
OpenIddict configuration

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#15897]
What settings and where to change for the production environment?
Please write a document under https://docs.abp.io/en/abp/latest/Deployment/Index

reported at https://support.abp.io/QA/Questions/4479#answer-3a09c950-dfa7-68c4-9d1d-ca6319f703fd

**Comment by hikalkan** [comment]
It seems already done: https://docs.abp.io/en/abp/latest/Deployment/Configuring-OpenIddict
So, you can check & improve it.
