### ISSUE TITLE
DbContextPool compability for EF Core 2.0

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#159]

**Comment by JadynWong** [comment]
[https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-4-performance-edition/#pooling-and-recycling-dbcontext-and-beyond](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-4-performance-edition/#pooling-and-recycling-dbcontext-and-beyond)

The article show 
`DbContextPool` has very important performance optimization.

**Comment by maliming** [comment]
> Context pooling is intended for scenarios where the context configuration, which includes services resolved, is fixed between requests. For cases where Scoped services are required, or configuration needs to be changed, don't use pooling. **The performance gain from pooling is usually negligible except in highly optimized scenarios.**

https://docs.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-constant#limitations

**Comment by GitOPa** [comment]
@maliming the linked Microsoft documentation about context pooling performance enhancement does not contain the quoted text anymore. To me, this might mean that Microsoft has changed its mind on when to use context pooling. Should we revisit this regarding abp framework?

**Comment by maliming** [comment]
hi @GitOPa 

Thanks. I will check it again.

------

2023-10-27

The current design of abp is not compatible with `DbContextPool`

**Comment by yaroslav-metelev** [comment]
> The current design of abp is not compatible with `DbContextPool`

Any plans to add support?
