### ISSUE TITLE
Login Angular with Keycloak

### ISSUE THREAD

**Issue by thanhtai9606** [abpframework/abp#15901]
I tried login angular with keycloak. But after login I cannot get token after login. I tried modified oauth module in abp framework too??
After login it redirect to first page and login button not hidden??
* Abp Framework 7.0.2**.

**Comment by mahmut-gundogdu** [comment]
Teorically,When you are using Keycloak insead of OpenIddict, no need to anychages because both framework uses OAuth2. Login button check `this.authService.isAuthenticated`.

**Comment by thanhtai9606** [comment]
No I get null accessToken after login. I already created a function to get token, but this.oAuthService is null??
![2023-03-08_22-10](https://user-images.githubusercontent.com/4544983/223750626-a911253a-5cdb-4e65-a2c5-fcad630b737e.png)

**Comment by thanhtai9606** [comment]
> Teorically,When you are using Keycloak insead of OpenIddict, no need to anychages because both framework uses OAuth2. Login button check `this.authService.isAuthenticated`.

I always get **false** value this.authService.isAuthenticated after login sso keycloak??
![2023-03-08_22-14](https://user-images.githubusercontent.com/4544983/223752075-54091e9d-5b00-4743-9aa2-d23a476c5b0a.png)

Can you help me solve it?? Because I need get this.oAuthService to getProfile and AccessToken after login sso??

**Comment by thanhtai9606** [comment]
@mahmut-gundogdu  can you help me??

**Comment by mahmut-gundogdu** [comment]
> > Teorically,When you are using Keycloak insead of OpenIddict, no need to anychages because both framework uses OAuth2. Login button check `this.authService.isAuthenticated`.
> 
> I always get **false** value this.authService.isAuthenticated after login sso keycloak?? ![2023-03-08_22-14](https://user-images.githubusercontent.com/4544983/223752075-54091e9d-5b00-4743-9aa2-d23a476c5b0a.png)
> 
> Can you help me solve it?? Because I need get this.oAuthService to getProfile and AccessToken after login sso??

If you are using OAuth.Module on your app.
AuthService replaced with this.

https://github.com/abpframework/abp/blob/b5549c607dd7c1c32c30773f97ca79e260bc5a7c/npm/ng-packs/packages/oauth/src/lib/services/oauth.service.ts#L59

so if the servis return false, `the service OAuthService (angular-oauth2-oidc)` doesn't has valid key.

**Comment by thanhtai9606** [comment]
@mahmut-gundogdu 
I just use AbpAuthModule but it just working inside this.
`return super
      .init()
      .then(() =>
        this.oAuthService
          .tryLogin()
          .then(() => {
            console.log(this.oAuthService.getAccessToken()); // it valid here
            console.log(this.oAuthService.hasValidAccessToken()); // it true here
          })
          .catch(noop),
      )
`
this is example 
![2023-03-11_09-54](https://user-images.githubusercontent.com/4544983/224461315-47c9bb49-d412-446b-b7cb-c9718921d4c7.png)
I don't know, why it not working outside .tryLogin.then()??? Can you help me??

**Comment by thanhtai9606** [comment]
@mahmut-gundogdu I solved it. You are mistake here
Thank for you help
![2023-03-14_09-29](https://user-images.githubusercontent.com/4544983/224877554-bf2379d9-84d7-447b-ad4a-4eca38941de6.png)

**Comment by mahmut-gundogdu** [comment]
> @mahmut-gundogdu I solved it. You are mistake here Thank for you help ![2023-03-14_09-29](https://user-images.githubusercontent.com/4544983/224877554-bf2379d9-84d7-447b-ad4a-4eca38941de6.png)

I'm glad the issue has been resolved. So I have mark as closed.
