### ISSUE TITLE
Invalid redirect_uri problem in External Provider

### ISSUE THREAD

**Issue by huseyinalan** [abpframework/abp#15936]
We are using DomainTenantResolver.
We want to add LinkedIn as external provider.
LinkedIn has filter for redirect_uri and doesn't allow wildcards.

When tenant wants to login with provider, the redirect_uri param being something like _\<tenant>_.mydomain.com
and provider reject this uri. 
Also found this issue but not solved. #4708
We don't have chance add every tenant uri to provider

How can i solve this problem?

**Comment by maliming** [comment]
hi

You can check this sample.
https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver

**Comment by huseyinalan** [comment]
Hi,
I tried again but didn't work.
I followed these steps:

1. Clone [sample project](https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver/OpenIddict/MVC-TIERED) 
2. Create project on [Google](https://console.cloud.google.com) 
3. Add OAuth Client in Google 
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/74354599/224587087-6aa39778-0614-47eb-9be4-72247c2cd421.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/74354599/224587338-41cf9a91-c72c-4054-bd41-051610ee1a13.png">

4. Configure ClientId & Secret in Abp Project
<img width="411" alt="image" src="https://user-images.githubusercontent.com/74354599/224587253-55efb505-43ad-4406-905a-9f660f8c8c3f.png">
5. Run Abp Project<br />
6.  Login with google in host side
<img width="500" alt="image" src="https://user-images.githubusercontent.com/74354599/224587543-63b4f97d-2c2c-4bc0-b19e-277600d55809.png"> (Successfull)
<img width="500" src="https://user-images.githubusercontent.com/74354599/224587851-231d0f9f-9178-4c71-91e4-9ad643839f81.png">
7. Switch to tenant by domain tenant resolver, try login with google
<img width="500" src="https://user-images.githubusercontent.com/74354599/224588044-08a1f9e8-979c-4b2a-9d78-6e22b4df2363.png">
 (Error)
<img width="500" src="https://user-images.githubusercontent.com/74354599/224588112-536b51eb-acc6-4a06-bc5a-c266cf18bdaa.png">

**Comment by maliming** [comment]
If google does not support wildcard domain, you have to add all tenant urls here.
Maybe google has related http apis.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/6908465/224589292-1e4c090f-c8c2-4228-a8d6-226d4714ec33.png">

**Comment by huseyinalan** [comment]
Yes google doesn't allow wildcard in redirect uri.
We gonna use multiple provider like LinkedIn, Google and we have a little too many tenants so we can't enter them manually also we can't manage properly.

I looked for API but couldn't find it. 

Is there any other solution?

**Comment by maliming** [comment]
In fact, this is the restriction of providers such as Google, and there is nothing we can do.

**Comment by huseyinalan** [comment]
Ok i understand, thanks for your effort
