### ISSUE TITLE
Namespace rules for DependencyInjection

### ISSUE THREAD

**Issue by korzanov** [abpframework/abp#15948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I was trying to find `using` of abp for DI but I found only default Microsoft namespaces.

### Describe the solution you'd like

I would like to see something like: 

``` csharp 
using Volo.Abp.Extensions.DependencyInjection;
``` 

instead 

``` csharp
using Microsoft.Extensions.DependencyInjection;
```

I think that would be more clearly definition what kind of dependencies I use.

---

Src: [DI extensions folder](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Core/Microsoft/Extensions/DependencyInjection)

**Comment by iyilm4z** [comment]
@korzanov this is not an issue. It is a design principle that ABP follows. 

I think ABP tries to separate real ABP-related codes(containing business) into ABP folders and non-ABP-related or more generic or a 3rd party related code to their own folders. This makes us have a more maintainable framework.

For example [AbpStringExtensions.cs](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/System/AbpStringExtensions.cs), it's in the `System` folder and most of those methods in that class are so generic and don't contain ABP-related business. Actually, some of them should be provided by the .net framework itself like the `IsNullOrEmpty` extension method but this is [another subject](https://stackoverflow.com/questions/14196593/why-is-mystring-isnullorempty-not-built-into-net). In other words, ABP completes the missing parts of .net framework in some places.

Also, this design principle makes you have less using blocks for non-ABP-related references. It makes you feel as if you are using native APIs. MS also follows this design principle for its libraries.

**Comment by berkansasmaz** [comment]
This is a recommended method. 

> Place extension methods in the [Microsoft.Extensions.DependencyInjection](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection) namespace to encapsulate groups of service registrations. Including the namespace portion `Microsoft.Extensions.DependencyInjection` for DI extension methods also:

See: https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage#register-services-for-di

**Comment by iyilm4z** [comment]
@berkansasmaz this is how I understand a general design principle of ABP. Please correct me if I'm wrong.
