### ISSUE TITLE
Upgrade .NET Standard 2.0 to .NET Standard 2.1

### ISSUE THREAD

**Issue by merijng** [abpframework/abp#15940]
[.NET Standard 2.1 is available for a while now](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/). It includes some features that might enhance ABP Framework, especially in Performance.

## Spans
In .NET Standard 2.0, Span functionality is available. However, in most scenario's there are not enough .NET API's available for the Span technique to get everything out of it. For example, [the String.Concat does not have an overload for Spans](https://github.com/abpframework/abp/pull/15878#event-8704527766). This impacts both performance and code readability.

I did not research it, but I would take a bet that many ABP functions can be improved to perform better, and use less memory by using spans more regularly.

_This might help refactoring after the upgrade:_
- [Code analysis CA1831](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1831)
- [Code analysis CA1832](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/CA1832)
- [Code analysis CA1833](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/CA1833)
- [Code analysis CA1845](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1845)
- [Code analysis CA1846](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1846)

## Other improvements
See the [announcement post](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/).

## Compatibility
.NET Standard2.1 drops support for older versions of .NET. This includes .NET Framework in general, and older versions of .NET, Mono, Xamarin.IOS, Xamarin.Android, Universal Windows Platform and Unity. See the [Microsoft .NET Standard site](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/) for more info.

Compatibility might be the reason to do the upgrade on a later version of ABP? Like ABP 8?

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/pull/16451
