### ISSUE TITLE
I want to create my own theme and record a video of how i did it

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1597]
Should i just copy `Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic` and make a new project `Amazing.Software.AspNetCore.Mvc.UI` or add a Amazing Theme folder to `Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic` ?

Can anyone give me the steps to follow?

**Comment by maliming** [comment]
Someone has created an abp AdminLTE theme, already open source, you can take a look.
https://github.com/csr2/AbpTheme

**Comment by hikalkan** [comment]
>Should i just copy Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic and make a new project 

Yes.

We'll create a theming doc (https://github.com/abpframework/abp/issues/631).
