### ISSUE TITLE
we cant install abp suite v 6.0.2 

### ISSUE THREAD

**Issue by cetins32** [abpframework/abp#15970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

we started solution on abp suite version 6.0.2 . and then we try to change solution. but we cant install abp suite v 6.0.2 on another pc

we try dotnet tool install -g Volo.Abp.Suite  --add-source https://nuget.abp.io/<token>/v3/index.json command. but cli install version 7.0.3 every time.

how can we resolve this error. we cant acces to volo.abp.suite.6.0.2.nupkg package

### Version

version 6.0.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
You can get help about ABP commercial at https://support.abp.io/
