### ISSUE TITLE
HomeComponent test build fails

### ISSUE THREAD

**Issue by nitrovent** [abpframework/abp#15983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

HomeComponent test build fails because of referencing a module that is not in the package.json.

### Reproduction Steps

1. Create new app with angular frontend
2. cd into angular folder
3. Run yarn
4. Run yarn test

### Expected behavior

Initial tests build and run without errors

### Actual behavior

Build fails with Error: Module not found: Error: Can't resolve '@abp/ng.theme.basic/testing' 

in ./src/app/home/home.component.spec.ts:2:0-70 
import { ThemeBasicTestingModule } from "@abp/ng.theme.basic/testing";

### Known Workarounds

1. Add "@abp/ng.theme.basic/testing": "~7.0.3" to package.json
2. Run yarn
3. Run yarn test

### Version

7.0.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by bariscanyilmaz** [comment]
Hi @nitrovent, we have removed theme.basic but forgot to remove it from testing files. You can remove it from `home.component.spec` file, you don't need to install `theme.basic package`.
