### ISSUE TITLE
ABP CLI — New version warning issue

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#15981]
Even though the new version is not set as 7.0.3, CLI shows an alert about the new version.
![image](https://user-images.githubusercontent.com/9526587/225534135-3a99eeda-b7dc-437a-b1f3-d927bd6804e7.png)

**Comment by berkansasmaz** [comment]
For `v7.1.*` this feature will be activated. It's normal that it doesn't work in previous versions. See: #15783
