### ISSUE TITLE
Use the ".Net Standard 2.0" framework for the web module, we will cannot use the VS feature to create "Areas", "Controller"  with the "scaffolder".

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#1598]
Use the ".Net Standard 2.0" framework for the web module, we will cannot use the VS feature to create "Areas", "Controller"  with the "scaffolder".
Sometimes we want to use the asp.net core mvc folder structure for web module development. Now if we want to add the "Controller" from the VS 2019 context menu, it will failed.
![image](https://user-images.githubusercontent.com/40879710/62600032-69679980-b920-11e9-9fff-f419105338ac.png)

**Comment by maliming** [comment]
My approach is to change the project to `Microsoft.NET.Sdk.Web.` (`<Project Sdk="Microsoft.NET.Sdk.Web">`)

Then reference to the relevant package(Microsoft.AspNetCore.Razor.Design, Microsoft.VisualStudio.Web.CodeGeneration.Design) in the project, and finally modify it back, I don't know if there are any other good ways.

**Comment by hikalkan** [comment]
We are doing it for the module template's Web project: https://github.com/abpframework/abp/blob/dev/templates/module/aspnet-core/src/MyCompanyName.MyProjectName.Web/MyCompanyName.MyProjectName.Web.csproj#L1
