### ISSUE TITLE
Required validation not work  in auto API controllers 

### ISSUE THREAD

**Issue by ohroy** [abpframework/abp#15998]
Consider the following scenario:

```c#
public class SomeDto
{
  [Required]
  public int test {get;set;}
  [Required]
  public DateTime test1 {set;set;}
}
```

If we use this DTO in SomeAppService with auto API controllers, the validation will work through ABP's implementation as described in https://docs.abp.io/en/abp/latest/Validation#ivalidatableobject.

The problem arises when the SomeDto object is passed to ABP's ObjectValidator, as both "test" and "test1" already have default values. In this scenario, the value of "test" is 0, while the value of "test1" is 0001-01-01. It is evident that it will pass our validation. Therefore, both "Required" and "not nullable" lose their intended function.

So, how can I check if "test" and "test1" are null in this scenario?

**Comment by ohroy** [comment]
Finally I found the reason is when `SystemTextJsonInputFormatter` deserialize a type with not nullable, it will set default value to it even the json value is null or does't exist at all.

If we set the test1 nullable,
```c#
public class SomeDto
{
  [Required]
  public int test {get;set;}
  [Required]
  public DateTime? test1 {set;set;}
}
```
Then it will work fine. the abp validation  will work too. But in this case, we must use `someDto.test1.Value` at all of the world....It's too troublesome : (


If we set the test1 requred 
```c#
public class SomeDto
{
  [Required]
  public int test {get;set;}
  public required DateTime test1 {set;set;}
}
```
Then, the json will deserialize fail,  and throw `InputFormatterException`.  But, abp validation can't work with it together.


Emmm, what's the right way to solve it?

**Comment by maliming** [comment]
Will the problem be solved if you don't use JSON to pass parameters?

Model binding and model validation are two processes.

The `required` attribute for non-nullable properties can be only validated during `Model binding`.

**Comment by ohroy** [comment]
Sorry my bad
This issue is not related to Abp because it has been tested and is now the same with dotnet (although I remember that dotnet can handle this situation correctly in the past, perhaps I remember it incorrectly).

Now, it is also explained in the dotnet document:
* [https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore -7.0#required-validation-on-the-server](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore -7.0#required-validation-on-the-server)
* [https://learn.microsoft.com/zh-cn/aspnet/web-api/overview/formats-and-model-binding/model-validation-in-aspnet-web-api])(https://learn.microsoft.com/zh-cn/aspnet/web-api/overview/formats-and-model-binding/model-validation-in-aspnet-web-api)

It is called "Under-Posting" (I think it's so **Anti intuition**, it means if not set, it will be default value and pass the validation even `Required`, such as if you forgot to post a enum, it will be the enum's first item, this can may be a very hidden problem)
> The model state is valid, because zero is a valid value for these properties. Whether this is a problem depends on your scenario. For example, in an update operation, you might want to distinguish between "zero" and "not set." To force clients to set a value, make the property nullable and set the Required attribute:


So I think the right way to do this

```c#
public class SomeDto
{
  [Required]
  public int? test {get;set;}
  [Required]
  public DateTime? test1 {set;set;}
}
```

But, as mentioned above, nullable syntax is used for every subsequent call, which is actually worthless. The cumbersome writing method is accompanied by poor performance, as redundant non null checking is required every time.
