### ISSUE TITLE
The modification audit properties will not be set if the field have default value when it's updated.

### ISSUE THREAD

**Issue by tbto** [abpframework/abp#15992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

my project code snippet

![image](https://user-images.githubusercontent.com/3437980/225836982-4c8451ed-0665-42f0-8ae7-8cfa752b161a.png)
![image](https://user-images.githubusercontent.com/3437980/225836791-071a9d4c-f34a-419b-9c9c-733169b8f7a1.png)

Abp 7.0 code snippet
![image](https://user-images.githubusercontent.com/3437980/225837393-0908aaaa-727f-429e-9bb6-42c75034e83c.png)
![image](https://user-images.githubusercontent.com/3437980/225837465-70edfc90-d271-45c1-883f-bb742c0da4b5.png)

### Expected behavior

It's should be set modification audit properties when only the field was updated

### Actual behavior

It not set modification audit properties when only the field was updated

### Version

7.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

**Comment by berkansasmaz** [comment]
Hello, I tried to reproduce the problem with the information you provided, but I could not reproduce it. Could you please explain the steps in more detail or send us a minimal reproducible example?

**Comment by hikalkan** [comment]
@maliming can you check this place?
