### ISSUE TITLE
Duplicated email sent when IEmailSender.QueueAsync method used

### ISSUE THREAD

**Issue by stristan** [abpframework/abp#16002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In app services for selected entities I need to send emails when entity created/updated/deleted. So at the end of each CreateAsync/UpdateAsync/DeleteAsync methos I use the following code to send email notification:
_emailSender.QueueAsync(...)
In this case I receiving 2 duplicated email fro each entity action. If I use _emailSender.SendAsync(...) instead - everything works as expected - single email is sending. Sometimes I receive only 1 email, sometimes 2 emails

### Version

7.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

What are related logs when you receive two mails?

**Comment by stristan** [comment]
This was first I have checked before registering this issue. Unfortunately, either log from Blazor app of HttpApi.Host service shows nothing about sending emails. Probably I need to change some log settings somewhere to be able see detailed logs from all ABP modules. Can you, please, point me how?

**Comment by maliming** [comment]
You can change the log level to `Debug`

```
public class Program
{
    public async static Task<int> Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .Enrich.FromLogContext()
            .WriteTo.Async(c => c.File("Logs/logs.txt"))
            .WriteTo.Async(c => c.Console())
            .CreateLogger();
```

**Comment by stristan** [comment]
After detailed investigation I have not found any issue in log. However, after experiment, I found that the issue is gone after my machine restarted.

**Comment by sturlath** [comment]
We have also had this issue... getting two registration emails for a new tenant but now that issue is gone... super strange..
