### ISSUE TITLE
replace bootstrap

### ISSUE THREAD

**Issue by washyn** [abpframework/abp#16004]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

![image](https://user-images.githubusercontent.com/15305896/226231986-49896d2e-b368-4da6-a3b8-1f4588cb0402.png)
How can I replace this bootstrap file with 2 other files? I know it can be replaced individually

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Bundling-Minification#bundle-contributors
