### ISSUE TITLE
The JSON value could not be converted to System.Nullable`1[System.Boolean].

### ISSUE THREAD

**Issue by wudi3121113** [abpframework/abp#16014]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Hi, I have an input parameter that is nullable
`public bool? IsAllocationed { get; set; }`

Based on business needs, when I request a method, I assign a null character to this parameter, like this:
`vm.filter.isAllocationed="" ;`

and then it throw an exception: The JSON value could not be converted to System.Nullable`1[System.Boolean].

It can works in the aspnetboilerplate, but not abp.io, could you give me some solutions? thank you very much.

### Version

7.0.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

**Reproduction Steps**

**Comment by wudi3121113** [comment]
> hi
> 
> **Reproduction Steps**

![1](https://user-images.githubusercontent.com/16113972/226362947-c3faf995-4a86-4291-9b6a-0372748d60c3.png)
![2](https://user-images.githubusercontent.com/16113972/226362996-24804d1a-c4ac-4bff-90bc-3ddf80f59332.png)
![3](https://user-images.githubusercontent.com/16113972/226363027-bcd34ccf-a109-479e-9c04-2e3aa57049cb.png)
![4](https://user-images.githubusercontent.com/16113972/226363077-b1785ede-73bf-4411-92d5-7fa422f10803.png)


when “true” or true, it can work
![5](https://user-images.githubusercontent.com/16113972/226363882-f043f1e7-e82c-41e9-9a55-9bbf002ab987.png)
![6](https://user-images.githubusercontent.com/16113972/226363894-9b97eba5-c37b-48d0-b6f5-2cabc485bf4d.png)

**Comment by wudi3121113** [comment]
> hi
> 
> **Reproduction Steps**

Can I convert “” to null by some config？

**Comment by maliming** [comment]
> Can I convert “” to null by some config？

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to

https://docs.abp.io/en/abp/latest/JSON#abpsystemtextjsonserializeroptions
https://docs.abp.io/en/abp/latest/JSON#configuring-json-options-in-asp-net-core

**Comment by wudi3121113** [comment]
> > Can I convert “” to null by some config？
> 
> https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to
> 
> https://docs.abp.io/en/abp/latest/JSON#abpsystemtextjsonserializeroptions https://docs.abp.io/en/abp/latest/JSON#configuring-json-options-in-asp-net-core

ok thank you, I am upgrading from abp to abpvnext, there are too many places that need to be changed, I control the parameter input through the front end.
