### ISSUE TITLE
Can ValueObject equality be implemented with this code?

### ISSUE THREAD

**Issue by cangunaydin** [abpframework/abp#16019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello,
I use lots of valueobject in my domain, so i was searching for an implementation that the equality operator == can be used instead ValueEquals(). 
I have seen the issue [#1728](https://github.com/abpframework/abp/issues/1728). Probably that's why equality op is removed from valueobject class. 

### Describe the solution you'd like

So when i look at some examples from Vladimir Khorikov here 
https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/ValueObject/ValueObject.cs, 
I think they overcome this problem by caching the hashcode and getting unproxied type. Can't we adapt this solution to abp valueobject?

**Comment by maliming** [comment]
hi

You can create a new value object base class and use it.

Custom the `IsValueObjectPredicate` to change its check predicate.
