### ISSUE TITLE
Non-Existing Tenant Issue

### ISSUE THREAD

**Issue by bariscanyilmaz** [abpframework/abp#16025]
ABP non-existing tenant error is returned when the user creates a tenant in one project and tries to run another project. To solve this problem, it is necessary to delete the relevant tenant id and cookie in the backend. This issue is reported in volosoft/volo#13028

**Comment by Stroudwater** [comment]
As a developer, I'm adding "?__tenant=" to the URL to clear the tenant cookie.  However, for users it is important that the browser remembers the tenant.

**Comment by maliming** [comment]
We have this feature.
https://github.com/abpframework/abp/pull/13157

**Comment by mahmut-gundogdu** [comment]
> We have this feature. #13157

but It didn't work when we sent logout request.

When tenant removed, a middleware check the tenant is is exists and id does not exits, it return a http-header that name is "Abp-Tenant-Resolve-Error".
in the angular, I got the value on http-header we trigger auth.logout() that redirect to  Auth Server but the server  has tenant cookie and it shown error. Thats the issue.

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/2217899/226949035-a625e5cb-617a-4a1e-923d-6670621ba19f.png">

**Comment by maliming** [comment]
hi @mahmut-gundogdu 

Can you share the steps that I can reproduce?

**Comment by mahmut-gundogdu** [comment]
> hi @mahmut-gundogdu
> 
> Can you share the steps that I can reproduce?

Create a angular app.
Add a tenant
Login with new tenant in new incognito browser
Remove logged tenant
Refresh the incognito browser.

Expected behavior: App can log-out. There is a middleware that return 404 with a header. But that code return when we try to logout- it should be skipp when logout requests.

**Comment by maliming** [comment]
hi @mahmut-gundogdu 

Can you remove the `__tenant` and the `bearer token` from the request header when you got the `tenant not found` error?

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/6908465/227882636-59b0675b-8d21-49dd-bd2e-91e3fa27b3b6.png">

**Comment by maliming** [comment]
hi @mahmut-gundogdu 

If the tenant does not exist or is not enabled, you don't need to logout it, because it does not exist on the server side. You can delete the login info directly.

**Comment by maliming** [comment]
I will handle this special case on the server side. But this 404 page will still appear once.

**Comment by mahmut-gundogdu** [comment]
> cause it does not exist on the server side. You can delete the login info directly.

When I delete all client site, then redirect to Auth server,  AuthServer return new key with same state. AuthServer will clean login state. There is a code for that but doesn't work

**Comment by maliming** [comment]
> AuthServer return new key with same state

Can you share an angular app that reproduces it?

**Comment by bariscanyilmaz** [comment]
> > AuthServer return new key with same state
> 
> Can you share an angular app that reproduces it?

1- run dev-app
2- login as admin and create a tenant
3- logout and login with new tenant username and password
4- open new private tab and login as admin
5- delete tenant in private window close this window
6- refresh page in tenant user's page you will get resource not found error
7- clear localstorage and refresh the page. you will see home page.
8- when you click login button it will give you tenant not found error like below 
![image](https://user-images.githubusercontent.com/30300440/228815455-c9d10c3a-284e-40ee-839c-7ed166fa4b4c.png)
9- if you go back and press login, error will be vanished

**Comment by maliming** [comment]
Do you test it with this PR code? 

https://github.com/abpframework/abp/pull/16095

**Comment by bariscanyilmaz** [comment]
> Do you test it with this PR code?
> 
> #16095

Yes

**Comment by maliming** [comment]
hi @bariscanyilmaz 

Can you test this new PR?

https://github.com/abpframework/abp/pull/16140/

**Comment by bariscanyilmaz** [comment]
> hi @bariscanyilmaz
> 
> Can you test this new PR?
> 
> #16140

Great, it is working
