### ISSUE TITLE
Method interception breaks Streams

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#16035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Method interception breaks service methods returning streams as it tries to read or serialize them. I believe this may be caused by audit log trying to serialize input parameters. However DisableAuditing did not work as workaround. RemoteContentStream is an existing workaround for the application layer but not a solution for other layers such as modules that need to take or return Stream as-is. 

### Reproduction Steps

1. Create a domain or module service that takes or returns a Stream
2. Call this method from a e.g. AppService or HttpController

### Expected behavior

You will see errors like "Timeouts are not supported on this stream."

### Actual behavior

Returning a Stream or having a Stream parameter should work without errors

### Regression?

Never worked.

### Known Workarounds

According to the docs using byte[] instead of Stream is one suggested workaround, but is not be feasible in many scenarios especially evolving bigger or long living streams. This also does not allow to forward streams from external sources such as databases for example. For byte[] the whole data would need to be downloaded first, which would occupy the full memory and cause delay as the data needs to be fetched fully on the server first. With streams this can be done buffered and endless instead for example. Hence byte[] is not a suitable replacement for Stream as they represent different things fundamentally.

For the ApplicationLayer we have the RemoteStreamContent workaround which works fine. However for internal services calling each other we shouldn't need to rely on RemoteStreamContent.

### Version

ABP 6

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

### Other information

Suggested solution:
- A way to disable method interception or parameter serialization for a given method so we can use Stream's as-is.
- Ignore streams during parameter serialization automatically

**Comment by maliming** [comment]
hi

> Create a domain or module service that takes or returns a Stream
> Call this method from a e.g. AppService or HttpController
> You will see errors like "Timeouts are not supported on this stream."

Please share your code and full error stack.
