### ISSUE TITLE
Why are the results of AsyncExecuter.CountAsync and EntityFrameworkQueryableExtensions.CountAsync inconsistent

### ISSUE THREAD

**Issue by Loiaa** [abpframework/abp#16039]
![20230322094601](https://user-images.githubusercontent.com/49937111/226783437-2ce0dd27-a54c-475a-a202-5123a44eae4d.png)

* 7.0.
* EF Core

**Comment by maliming** [comment]
Steps needed to reproduce the problem.

**Comment by Loiaa** [comment]
> Steps needed to reproduce the problem.

After I restarted Visual Studio, it disappeared. I'm sorry to disturb you.
