### ISSUE TITLE
How do these style files get loaded and where do they come from ?

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1603]
How do these style files get loaded and where do they come from ?

![Screen Shot 2019-08-08 at 5 42 37 pm](https://user-images.githubusercontent.com/15242923/62684593-54fccd00-ba04-11e9-95a7-45020fffbf0b.png)

**Comment by maliming** [comment]
Please see the documentation: 
https://docs.abp.io/en/abp/latest/AspNetCore/Bundling-Minification#bundle-contributors
https://github.com/abpframework/abp/search?l=C%23&q=BundleContributor&type=

**Comment by vnetonline** [comment]
Thanks @maliming that helped i have made progress

Can someone explain to me how this tool bar component works 

```
        <div id="AbpContentToolbar" class="text-right mb-3">
            @RenderSection("content_toolbar", false)
        </div>
```

I know what  RenderSection does where is @section content_toolbar defined?
