### ISSUE TITLE
Can't update Cli to 7.1.0

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#16037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Now that 7.1.0 has been released I wanted to update the Cli but when I run

dotnet tool update -g Volo.Abp.Cli

I get the following message:

Tool 'volo.abp.cli' was reinstalled with the latest stable version (version '7.0.3')

### Reproduction Steps

dotnet tool update -g Volo.Abp.Cli

### Expected behavior

Updates Cli to version 7.1.0

### Actual behavior

Doesn't update the Cli

### Version

7.0.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Still being released

**Comment by DonVliet** [comment]
@realLiangshiwei Thanks 👍

**Comment by fileman** [comment]
I have the same issue with "abp update"
VS nuget manager show all new 7.1.0 pkg in update tab

**Comment by DonVliet** [comment]
@fileman Please try again as it appears the update is now live :-)

**Comment by fileman** [comment]
I have tried even before click "comment" :-)
I retry later in the afternoon

**Comment by fileman** [comment]
Same issue:
```
PS C:\Users\usermane\source\repos\projectname> abp update
ABP CLI 7.1.0
Package: "Volo.Abp.PermissionManagement.Application.Contracts-v7.0.3" is up to date.
```

**Comment by fileman** [comment]
@realLiangshiwei @DonVliet can you reopen this ?

**Comment by realLiangshiwei** [comment]
Please create a new issue, thanks @fileman
