### ISSUE TITLE
CLI update to 7.1

### ISSUE THREAD

**Issue by fileman** [abpframework/abp#16056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

same problem as #16037 

### Reproduction Steps

PS C:\Users\usermane\source\repos\projectname> abp update
ABP CLI 7.1.0
Package: "Volo.Abp.PermissionManagement.Application.Contracts-v7.0.3" is up to date.
...
repeated for all packages
...

### Expected behavior

update nuget and npm

### Actual behavior

update only npm

### Version

7.0.3

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by yekalkan** [comment]
We no longer immediately inform cli for new versions. First we test if the release is successfull, and then update https://github.com/abpframework/abp/blob/dev/latest-versions.json file, so cli knows about the new version.

related PR: https://github.com/abpframework/abp/pull/15783

**Comment by fileman** [comment]
Ok, it's the first time since 4.x that happened
