### ISSUE TITLE
add  public setState Fn on ConfigStateService 

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#16059]
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/services/config-state.service.ts

related https://support.abp.io/QA/Questions/4652/The-attribute-setState-does-not-exist-on-the-type-ConfigStateService

**Comment by bhushansshah** [comment]
Hi, I was looking for good-first-issue as I am new to open source and I found this issue. I went through the given links. The setState function is missing in the class ConfigStateService. So adding that function will solve this issue. Please let me know your input. Thanks :)

**Comment by mahmut-gundogdu** [comment]
> Hi, I was looking for good-first-issue as I am new to open source and I found this issue. I went through the given links. The setState function is missing in the class ConfigStateService. So adding that function will solve this issue. Please let me know your input. Thanks :)

yes. That solution can close the issue. If you want to contribute, please send PR. I will review it.
