### ISSUE TITLE
The namespace confuse for "Abp.Application.Services.Dto" and "Volo.Abp.Application.Dto".

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#1605]
When I create a DTO object which inherits our DTO base class, the namespace confuses for "Abp.Application.Services.Dto" and "Volo.Abp.Application.Dto".
![image](https://user-images.githubusercontent.com/40879710/62753491-701c1b00-ba9e-11e9-8d43-33fc1f369ba4.png)
If I use the "Abp.Application.Services" related class, it will throw some errors.
Does anybody know why we have tow different namespace for the same base class? Thanks so much.

Abp version: 0.18.1

**Comment by maliming** [comment]
`Abp.Application.Services.Dto` does not belong to abp vnext. It should be Abp Boilerplate, do you have a wrong reference?

**Comment by jack-gaojz** [comment]
No, the project created by our template, I didn't change any nuget references. :(

**Comment by maliming** [comment]
Please check the reference package for your project.
