### ISSUE TITLE
Q: Effective Machine-To-Machine authentication

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#16063]
**Scenario**
External application or device should cummunicate via REST API with abp application (M2M communication).
External app or device has limited functionality to configure communication with our abp-based application.
Typical configuration options:
- Full URL to specific REST API method
- Http method type (POST, GET,...)
- key-value textboxes for defining Http headers and its values or maybe define username and password for Basic authentication type

There is no way that such external app/device can handle OAuth to generate new JWT tokens.
Changing JWT or username/password for such apps/devices are also not desirable by customers.

**There is no way that such REST API methods are not protected (access only possible to specific users).**

What are the best practices nowadays to handle authentication in such cases?

I would really like to leverage authentication mechanisms in abp framework so that I am relatively safe not to open additional security holes and that such "machine user" is basically not different from other "human users" inside abp application (so that I change permissions and roles).

The only solutions for described scenario I can see right now are:

1) Create new user (and add desired permissions and roles) with specific username and password. Save this credentials somewhere (Azure Vault,...) and then generate JWT token with (extremely) distant expiration datetime.
Use such long-life JWT token in external app/device as "Bearer" authentication header

How to generate long-life token inside abp application?

2) Add Basic type of authentication somehow.

What are suggestions for such situation?
Thank you.

**Comment by antosubash** [comment]
One option is to use the `Client Credentials Grant` to get the access token. more info here https://www.rfc-editor.org/rfc/rfc6749#section-4.4 keep in mind The client credentials grant type MUST only be used by confidential
   clients.

**Comment by leonkosak** [comment]
Ok, maybe I finally get it. :)
Example is based on abp Commercial 7.4.0.

1) Instead for new user (inside tenant), create **new Application** (Administration => OpenId => Application):
![image](https://github.com/abpframework/abp/assets/39346964/034268cb-52b1-441b-8be0-2e52a6b439b9)

2) Example call (in Postman):
![image](https://github.com/abpframework/abp/assets/39346964/885a39f0-0118-4404-ba36-bd4b1f2708a6)

External application (for M2M communication) should generate JWT token like example in Postman and then use returned JWT to further call REST API methods which require authentication?

This is recommended way for M2M communication as I can see: https://documentation.openiddict.com/guides/choosing-the-right-flow.html#client-credentials-grant-recommended-for-machine-to-machine-communication

Can you confirm this @maliming ?

**Comment by maliming** [comment]
Yes, this is how `client credentials ` work.

**Comment by leonkosak** [comment]
Well, how can I define permissions for such new Application (which API methods can be accessed)?
If I use grant_type=password and add additional headers (username, password and scope), I can define for such "machine user" which API method can be accessed.
