### ISSUE TITLE
Abp.io not use all resource of de cpu and memory using queues 

### ISSUE THREAD

**Issue by firminoeducbank** [abpframework/abp#16065]
I have an application using abp.io version 6, and I put many items in the queue example 10.000 items for processing.
My applications have a configuration auto-scaling in AWS ECS when CPU max usage is 70% but using abp.io this has not occurred.
The process is very slow and processes look execute one by one. Same time I need a scaling server manually to process more items, this approach isn't efficient.
I'm using Rabbitmq to control my queue and my initial I`m not setting prefetchCount so ABP gets all in the queue and does not process this item, Rabbitmq gives an error because the application delayed response ACK. Now I'm using prefetchCount 100 the error reflects a timeout ACK was resolved, but my application continues very slowly for processing items in the queue because I think the ABP process one by one.

The same one can confirm for me if this process executes one by one and if it is not will stress my CPU for scaling?

**Comment by maliming** [comment]
>and I put many items in the queue example 10.000 items for processing.

Can you explain this in detail?

What is the function of abp you are using?
