### ISSUE TITLE
IToolbarContributor not works on Blazor Server + LeptonXLite

### ISSUE THREAD

**Issue by stristan** [abpframework/abp#16088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to reproduce sample (add Notification icon) described in documentation: https://docs.abp.io/en/abp/latest/UI/Blazor/Toolbars
After implementing as described on sample the notification icon is not added to the main toolbar. Moreor, during debug I noticed that IToolbarContributor's ConfigureToolbarAsync method is not firing at all.
![image](https://user-images.githubusercontent.com/1971037/227799234-cf5ab7bd-6de8-4888-b4f8-f960a5adfd64.png)

### Version

7.0.3

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by beriniwlew** [comment]
I'm not sure if this is related, but I can't collapse the side menu.  

Blazor Server
Single Tiered
Ef Core

**Comment by enisn** [comment]
It seems it's working on ABP v7.0.3 and LeptonX v2.0.5.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/23705418/227887104-a1dbdb04-9d2c-4c6b-acb3-0158f9d36f39.png">

Here some tips to find the issue:

1. Make sure you're using `IToolbarContributor` from the namespace `Volo.Abp.AspNetCore.Components.Web.Theming.Toolbars` and not the MVC one.
  ![image](https://user-images.githubusercontent.com/23705418/227887186-e2c8a754-6364-41e8-831e-e8e12d83e326.png)

2. make sure `AbpToolbarOptions` is from `Volo.Abp.AspNetCore.Components.Web.Theming.Toolbars` namespace, not the mvc one.
      ```csharp
      Configure<AbpToolbarOptions>(options =>
      {
          options.Contributors.Add(new LeptonXLiteDemoAppToolbarContributor());
      });
      ```
      ![image](https://user-images.githubusercontent.com/23705418/227887395-abb10163-a53d-4804-9b6b-ee473743f2f9.png)

**Comment by stristan** [comment]
Confirming, now, after applying your instructions it is working, thanks!
Please, improve the related documentation, because yesterday I have spent about half of my day to understand what I'm doing wrong :)
You can close the issue

**Comment by enisn** [comment]
Thanks for your feedback, We'll update the documentation :)
