### ISSUE TITLE
Error when configuring EfCore entity relationships using OwnsOne.

### ISSUE THREAD

**Issue by wangj90** [abpframework/abp#16091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I configure an EfCore entity relationship using OwnsOne, and the owned object also a value object has a DateTime property. I get the following error:
` 'The entity type 'xx' cannot be configured as owned because it has already been configured as a non-owned. If you want to override previous configuration first remove the entity type from the model by calling 'Ignore'.`

This is because in EfCore's OnModelCreating method, abp makes an IsOwned judgement against the DateTime type property and sets it to an entity, and my object is a value object.

### Known Workarounds

Change the base OnModelCreating method order.

### Version

5.0.0-7.1.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

Here's a stackoverflow link to the same question：
https://stackoverflow.com/questions/71573134/adding-value-object-to-ef-entity-the-entity-type-cannot-be-configured-as-owned

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/2640

**Comment by wangj90** [comment]
Why not put OnModelCreating at the end? If so, I would not have to take Owned out separately and could use it like the official EfCore documentation。

**Comment by maliming** [comment]
There will be no chance to change the default behavior if `OnModelCreating` is at the end.

**Comment by wangj90** [comment]
`OnModelCreating` default behavior does 4 things：
1. Configure Base Properties。
2. Configure Global Filters。
3. Configure Value Converter for DateTime and nullable DateTime。
4. Configure Id Generated。

It seems it does not interrupt change the default behavior if `OnModelCreating` is at the end。

BTW，base `OnModelCreating` called `ConfigureByConvention`，why should we called it in our module？
