### ISSUE TITLE
abp Commercial: Unable to Installing LeptonX theme

### ISSUE THREAD

**Issue by MohammdaSalah** [abpframework/abp#16093]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

We are trying to install LeptonX theme instead of the default LeptonXLite using abp cli, when I try to execute the command using my commercial account:  `abp add-package Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX`  I got the following result with error : "error: Package 'Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX' is incompatible with 'all' frameworks in project 'C:\MyProject' "  although it setups the required code to use the new theme but it did not install the package dll Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX

Here is the entire result:
`[15:43:43 INF] ABP CLI (https://abp.io)
[15:43:44 INF] Installing 'Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX' package to the project 'MainApp.Web'...
  Determining projects to restore...
  Writing C:\Users\mohda\AppData\Local\Temp\tmpF1D6.tmp
info : Adding PackageReference for package 'Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX' into project 'C:\MyProject\MainApp.Web\MainApp.Web.csproj'.
info : Restoring packages for C:\MyProject\MainApp.Web\MainApp.Web.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/volo.abp.aspnetcore.mvc.ui.theme.leptonx/index.json
info :   CACHE https://nuget.devexpress.com/gyycK4CBuUWcSLdP4vnRpZC4pg87mWe7Jc3z1XWdz7vmMlRDCE/api/FindPackagesById()?id='Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX'&semVerLevel=2.0.0
info :   GET https://www.myget.org/F/blazorise/api/v3/flatcontainer/volo.abp.aspnetcore.mvc.ui.theme.leptonx/index.json
info :   NotFound https://www.myget.org/F/blazorise/api/v3/flatcontainer/volo.abp.aspnetcore.mvc.ui.theme.leptonx/index.json 512ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/volo.abp.aspnetcore.mvc.ui.theme.leptonx/index.json 977ms
error: NU1101: Unable to find package Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX. No packages exist with this id in source(s): BlazoriseMyGet, C:\Program Files\dotnet\library-packs, DevExpress 21.2 Local, DevExpress MAUI, Microsoft Visual Studio Offline Packages, nuget.org, Text Control Offline Packages, WebRequest
error: Package 'Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX' is incompatible with 'all' frameworks in project 'C:\MyProject\MainApp.Web\MainApp.Web.csproj'.
[15:44:03 INF] Successfully installed.`

### Version

6.0.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
You can get help with ABP commercial at https://support.abp.io/

**Comment by MohammdaSalah** [comment]
> You can get help with ABP commercial at https://support.abp.

How can I open a question? I cannot find any link or button to ask a new question

**Comment by maliming** [comment]
hi

Sign in the website and https://support.abp.io/QA/Questions/New
