### ISSUE TITLE
Virtual File System Explorer

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1609]
@hikalkan I want to create a Virtual File System browser as a module 

Can you let me know what your approach would be? It would be good to see what is in the Virtual File System when developing to override views and pages etc etc 

Once developed happy for you to include it as a module in the repository.

**Comment by hikalkan** [comment]
That is a good idea!  It can be useful in development.

Inject `IVirtualFileProvider` and use `GetDirectoryContents("/")` to get the root folder contents. It will return file and folders. Then you can reuse it to enter another folder and so on...

**Comment by vnetonline** [comment]
@hikalkan `GetDirectoryContents` Is not a Async function, how do I use it in the ApplicationService

Also it seems it only returns physical files should it return files and directors from all three file providers memory, physical and dynamic ?

**Comment by hikalkan** [comment]
It should return all, not only physical files.

A sync method can directly usable inside an async method. Do you have any problem of that?

**Comment by vnetonline** [comment]
No problem I thought that a ApplicationService should always return Async because the UI layer will call it using HttpAPI and whenever calling a HttpApi it should be done Async way as best practice ?? Is my understanding wrong ?

**Comment by hikalkan** [comment]
You are true. However, not possible (or meaningfull) to make all methods async.
Calling an async code from a sync method may cause problems. But vise verse does not.

BTW, this method is defined by Microsoft: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.ifileprovider?view=aspnetcore-2.2
So, I can't make it async :)

**Comment by vnetonline** [comment]
But the method I write in my application project should be Async right ?

Should I just put a task.delay ??

**Comment by hikalkan** [comment]
>But the method I write in my application project should be Async right ?
No, not required. However, I suggest it. Never do task.delay :) Remove async keyword and return Task.CompletedTask; (for void methods) or Task.FromResult(...) (for method returns a value).

**Comment by vnetonline** [comment]
@hikalkan 

thanks for your help that makes sense, I am not getting anything when I try and call `GetDirectoryContents("/")`

<img width="1185" alt="Screen Shot 2019-08-21 at 12 11 39 pm" src="https://user-images.githubusercontent.com/15242923/63397286-68993200-c40d-11e9-8dc9-aaf51a57713f.png">

I have changed the `launchSetting.json` as follows to simulate Production mode

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "https://localhost:44329",
      "sslPort": 44329 
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      }
    },
    "Amazing.Software.VirtualFileExplorer.DemoApp": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:44329",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by hikalkan** [comment]
@vnetonline can you create an issue for that so we check it. Thanks.

**Comment by liangshiw** [comment]
Hi @vnetonline,
Are you still working for this? If not, I can create this module.

**Comment by liangshiw** [comment]
Working in https://github.com/abpframework/abp/tree/liangshiwei/virtualfilesystem-explorer-module.
