### ISSUE TITLE
LayoutHooks.PageContent.Last not working for MVC LeptonX lite theme.

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#16119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The code not working for LayoutHooks.PageContent.Last, but works for LayoutHooks.Body.Last.

`Configure<AbpLayoutHookOptions>(options =>
        {
            options.Add(
                LayoutHooks.PageContent.Last, //The hook name
                typeof(FooterViewComponent) //The component to add
            );
        });`

### Version

7.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
What's your lepton version?

https://github.com/volosoft/lepton/pull/1227

**Comment by juchunwei** [comment]
@maliming 

I was using 2.0.5, seems it works after upgrade to 2.1.0. 
Thanks!
