### ISSUE TITLE
use Newtonsoft replace System.Text.Json exception Could not load type Volo.Abp.DependencyInjection.IHybridServiceScopeFactory

### ISSUE THREAD

**Issue by wang3156** [abpframework/abp#16124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error :Unhandled exception. System.TypeLoadException: Could not load type 'Volo.Abp.DependencyInjection.IHybridServiceScopeFactory' from assembly 'Volo.Abp.Core, Version=7.1.0.0, Culture=neutral, PublicKeyToken=null'.
i want use Newtonsoft  replace  System Text Json,According to the guide 
   1. add Volo.Abp.Json.Newtonsoft package
   2. depends on AbpJsonNewtonsoftModule 
![image](https://user-images.githubusercontent.com/18094713/228481982-82efb969-3137-4b5c-ac7d-4128201c23d7.png)
![image](https://user-images.githubusercontent.com/18094713/228482104-4641459d-08d5-40d0-a054-708a3f2fa865.png)
 3.
![image](https://user-images.githubusercontent.com/18094713/228482265-bd05e0e5-a5b3-417d-8965-1768a72625ac.png)
But the it runs wrong as follows
![image](https://user-images.githubusercontent.com/18094713/228482681-c053b5bf-5f73-4f74-b8af-223f1e2c4b8c.png)

Framework version   .net6
Related package and its version
![image](https://user-images.githubusercontent.com/18094713/228483102-5b42bcce-bf5e-4985-b155-ee25fe1da4bc.png)

### Expected behavior

Replace System.Text.Json with Newtonsoft to do the serialization

### Actual behavior

Unhandled exception. System.TypeLoadException: Could not load type 'Volo.Abp.DependencyInjection.IHybridServiceScopeFactory' from assembly 'Volo.Abp.Core, Version=7.1.0.0, Culture=neutral, PublicKeyToken=null'.

### Version

6.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Please use the same version of all abp packages.

![image](https://user-images.githubusercontent.com/6908465/228485236-2ce7131b-9f69-438e-9912-57b421dd299d.png)

**Comment by wang3156** [comment]
> 
Parts of abp packages are only supported by.NET 7.0, while abp.json. Newtonsoft is available from 7.0.0 to minimum.
How do you solve it?

**Comment by wang3156** [comment]
![image](https://user-images.githubusercontent.com/18094713/228724952-dbd9695d-490a-4384-8c52-78d4aefc237a.png)
Sorry I read the wrong document version. But I implemented the IJsonSerializerProvider and registered it as instructed in 6.0. However, it still failed to replace System.Text.Json. May I ask how to deal with it? Or where are some examples?

**Comment by wang3156** [comment]
> Please use the same version of all abp packages.
> 
> ![image](https://user-images.githubusercontent.com/6908465/228485236-2ce7131b-9f69-438e-9912-57b421dd299d.png)


Parts of abp packages are only supported by.NET 7.0, while abp.json. Newtonsoft is available from 7.0.0 to minimum.
How do you solve it?

I tried it here. It didn't work
![image](https://user-images.githubusercontent.com/18094713/228751031-a28864e4-df28-4951-a506-078f01462de6.png)

**Comment by maliming** [comment]
The packages of abp in your project must be same version.

https://github.com/abpframework/abp/issues/16124#issuecomment-1488220354

**Comment by wang3156** [comment]
I'll just follow the Settings here
https://github.com/abpframework/abp/issues/9179
My main problem is with the ConfigureServices setup, which should be in PreConfigureServices
public override void PreConfigureServices(ServiceConfigurationContext context)
{
      PreConfigure<AbpJsonOptions>(options =>
      {
          options.UseHybridSerializer = false;
      });
}
