### ISSUE TITLE
Abp update updates LeptonXLite to incorrect version

### ISSUE THREAD

**Issue by xorinzor** [abpframework/abp#16120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using `abp update` will update `Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite` to `7.1.0`, whereas the latest version on nuget is `2.1.0`

### Reproduction Steps

1. Set the package `Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite` in csproj from the webproject to version `2.1.0`
2. Run `abp update`
3. Package version will be changed to version `7.1.0`

### Expected behavior

Package will be left at `2.1.0`

### Actual behavior

Package is set to an invalid version (`7.1.0`)

### Version

7.1.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/pull/16057

**Comment by xorinzor** [comment]
Ah. Didn't search the pull requests, only the issues. Didn't have an existing issue yet.

EDIT:  @maliming  I updated my Volo Cli before this, I guess the PR isn't yet released then?

**Comment by maliming** [comment]
hi

The fix will be available on 7.1.1.
