### ISSUE TITLE
Inherit IDapperRepository from IRepository

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#16134]
In this way, it will automatically register to DI as transient. And it is better for our convention.

Is there any reason we didn't make it before?

**Comment by maliming** [comment]
> Repositories are not injected by class by default.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Repositories/AbpRepositoryConventionalRegistrar.cs#L29

**Comment by hikalkan** [comment]
OK, I will check it.
