### ISSUE TITLE
Add "Single Layer" option to Get Started tutorial

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#16146]
The [Quick Start document](https://docs.abp.io/en/abp/latest/Tutorials/Todo/Overall) has two options (layered and non-layered), however, the [Getting Started](https://docs.abp.io/en/abp/latest/Getting-Started) document has not. We can do same for the Getting-Started document too. We can create an overall/index page to pick the solution type. For layered solution, [the current document](https://docs.abp.io/en/abp/latest/Getting-Started) is used. For non-layered, create a similar multi-part document (with sub-parts "Setup your development environment", "Creating a new solution" and "Running the solution" just as the current one).

**Comment by braim23** [comment]
Closed https://github.com/abpframework/abp/pull/16359
