### ISSUE TITLE
OpenIddict scopes

### ISSUE THREAD

**Issue by merijng** [abpframework/abp#16141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to add a custom scope. Before it shows up in the _/.well-known/openid-configuration endpoint_, I have to [preconfigure scopes](https://docs.abp.io/en/abp/latest/Modules/OpenIddict#OpenIddictServerBuilder) in ***WebModule.cs**, see below.

```
PreConfigure<OpenIddictServerBuilder>(builder =>
{
    builder.RegisterScopes("my_custom_scope");
});
```

### Describe the solution you'd like

Currently, it is possible to add scopes though the interface of ABP (_Administration => OpenId => Scopes_). It would be nice if registered scopes are automatically registered to OpenIddict "discovery document" (_/.well-known/openid-configuration endpoint_).

### Additional context

I have to say that I don't know the exact impact of this feature. Is there a situation where this is not desirable?

If implemented, the feature should take standard scopes in consideration.

**Comment by maliming** [comment]
You can add a custom **Handler** to solve it.

Fake code.
```cs
public class AttachMyScopes : IOpenIddictServerHandler<OpenIddictServerEvents.HandleConfigurationRequestContext>
{
    public static OpenIddictServerHandlerDescriptor Descriptor { get; }
        = OpenIddictServerHandlerDescriptor.CreateBuilder<OpenIddictServerEvents.HandleConfigurationRequestContext>()
            .UseSingletonHandler<AttachMyScopes>()
            .SetOrder(OpenIddictServerHandlers.Discovery.AttachScopes.Descriptor.Order + 1)
            .SetType(OpenIddictServerHandlerType.Custom)
            .Build();

    private readonly IOpenIddictScopeRepository _scopeRepository;

    public AttachMyScopes(IOpenIddictScopeRepository scopeRepository)
    {
        _scopeRepository = scopeRepository;
    }

    public async ValueTask HandleAsync(OpenIddictServerEvents.HandleConfigurationRequestContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        var scopes = await _scopeRepository.GetListAsync();
        context.Scopes.UnionWith(scopes.Select(x => x.Name));
    }
}

```

**Comment by merijng** [comment]
@maliming 

Thanks!

Yes, am aware of that. However, should the "custom handler" not be the default of ABP?

**Comment by maliming** [comment]
Yes, I will do that on the commercial side. but I will confirm that on OrchardCore.

**Comment by merijng** [comment]
@maliming OrchardCore? That's a different framework, isn't it?

Anyway, good to have a discussion internally. Thanks for the fast response.

**Comment by maliming** [comment]
OrchardCore openid is similar to Openiddict Pro modules.
The author of Openiddict is also the developer of OrchardCore.
