### ISSUE TITLE
Blazor App (United) .net 8 option to abp´s Blazor offerings 

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#16156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Like many of us using the current versions of Blazor WASM/server (abp.io or others) we are not happy about the various [the limitations](https://code-maze.com/blazor-webassembly-introduction/) it offers. Either its [slow to startup/download](https://github.com/abpframework/abp/issues/13114) or it can disconnect needing the user to refresh the page.

But we still love it for all the [lovely things ](https://www.syncfusion.com/blogs/post/7-features-of-blazor-that-make-it-an-outstanding-framework-for-web-development.aspx) it brings to the table

Now that [Blazor United](https://github.com/dotnet/aspnetcore/issues/46636) is planned for .net 8 can we **ask that abp.io watches this development** and will at least try come out with a version and upgrade path in the very first versions of abp.io that ships with .net8? It would not be a great strategy to wait until its released and then start thinking about it.

I´m sure you have thought about this and are as excited as me, but we just can´t afford to just go by faith this time 😉

**Comment by omer-repo** [comment]
Blazor United is very good solution to solve Blazor's biggest issues (Latency in Blazor Server and slow load in Blazor Wasm)

Many features will come with .Net 8 and Blazor United: Server-side rendering, streaming rendering, enhanced navigations & form handling, add client interactivity per page or component, and determining the client render mode at runtime. (https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-3/comment-page-2/#comment-17958) 
And it's very likely that WASM and Server templates will be merged into United only.

So we can see what a great opportunity and facility it is for us Blazor developers to be able to use this template/method in APB projects.

**Comment by sturlath** [comment]
I can see that there is no mention of Blazor App (the name got changed from United) in the 8.0 version https://github.com/abpframework/abp/milestone/88

Can we get a working timeframe of when you think you will implemnt this @hikalkan ? This is a [major feature](https://visualstudiomagazine.com/articles/2023/06/14/blazor-net-8-preview-5.aspx?m=1) that everybody that has current implementations of Blazor wants to move to and nobody wants to greate a new solution without so I hope you have this in scope.

Here is a start of a upgrade docs for the Blazor Server https://github.com/dotnet/AspNetCore.Docs/issues/29505 but as I understand the WASM one is not clear atm

**Comment by nebula2** [comment]
Just a little informational update:

To avoid confusion, the term `Blazor United` is not used anymore. See [here](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#full-stack-web-ui-with-blazor) where they are referring it to `Full stack web UI with Blazor`. 
> IMHO this is even more confusing - but who am I to judge 😅

I found this issue. I think that the progress on this effort is tracked there:

https://github.com/dotnet/aspnetcore/issues/46636

EDIT:
The issues [here](https://github.com/dotnet/aspnetcore/labels/feature-blazor-single-project) are interesting to keep track of.

**Comment by omer-repo** [comment]
As Jon Hilton says, there are different render modes in .Net 8.  And the default render mode will be SSR(Server side rendering). So it should be implemented in ABP Framework also.
https://jonhilton.net/blazor-auto-render-mode/

**Comment by hikalkan** [comment]
We will evaluate that in the next version. Thanks 👍

**Comment by sturlath** [comment]
I would recommend reading this [here  about updating (Oqtane) to Blazor SSR (Static Server Rendering)](https://github.com/oqtane/oqtane.framework/discussions/3448#discussioncomment-7461283) it talks about the 

> "new **non**-interactive Blazor approach"

As you can see the SSR version is [**not** interactive ](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0) 

I don´t know what this means for Blazorise but

> if you are using a specific UI component library throughout your application which only supports interactive scenarios, it means your application will not be able to get the benefits of the non-interactive approach.


For me the SSR is the most interesting one (super quick rendering and no SignalR). The [Spark.net](https://spark-framework.net/) is will be using [HTMX ](https://htmx.org/) in their .net 8.0 version. Take a look at some of the stuff they are doing [here](https://twitter.com/wes_walke/status/1710402073068527880)

But this will be the [hottest version of Blazor](https://www.youtube.com/watch?v=VWwZrDA8om0) and I surely hope abp.io will focus on it as soon as possible.

**Comment by bxjg1987** [comment]
blazor web app (auto) template is greate

**Comment by hikalkan** [comment]
Thanks to everyone for your comments. This is moved to https://github.com/abpframework/abp/issues/18289
I can't promise that it will be completed in v8.1, but we will be working on.
