### ISSUE TITLE
Id missing when retrieving list of cached entity

### ISSUE THREAD

**Issue by Alexandre789010** [abpframework/abp#16158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to cache a list of entity, but when retrieving the data, it is missing the id.

When the data is not in the cache, everything works fine; when the data is in the cache, the id is missing.

### Reproduction Steps

Create an ABP project with the following entity and app service.

When the data is not in the cache, everything works fine; when the data is in the cache, the id is missing.

```csharp

public class Plant : Entity<string>
{
    public string? DispatchGroup { get; set; } = string.Empty;
    public string? Name { get; set; } = string.Empty;
}

public class PlantDto : EntityDto<string>
{
    public string DispatchGroup { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
}

public class PlantAppService : ReportsAppService, IPlantAppService
{
    private readonly IDistributedCache<List<Plant>> _cache;
    private readonly IPlantRepository _plantRepository;

    public PlantAppService(IDistributedCache<List<Plant>> cache, IPlantRepository plantRepository)
    {
        _cache = cache;
        _plantRepository = plantRepository;
    }
    
    public async Task<List<PlantDto>> GetListAsync(GetPlantListDto input)
    {
        var plants = await _cache.GetOrAddAsync(
                                                "plant_list",
                                                async () => await _plantRepository.GetListByDispatchGroupsAsync(input.DispatchGroups),
                                                () => new DistributedCacheEntryOptions
                                                {
                                                    AbsoluteExpiration = DateTimeOffset.Now.AddHours(1)
                                                }
                                               );
        
        return ObjectMapper.Map<List<Plant>, List<PlantDto>>(plants);
    }
    
    public async Task<PlantDto> GetAsync(string id)
    {
        var plant = await _plantRepository.GetAsync(id);
        return ObjectMapper.Map<Plant, PlantDto>(plant);
    }
}

```

### Expected behavior

Getting back the list of entity including their ids.

### Actual behavior

I get back the list of entity but without their ids.

### Known Workarounds

Dot not know any.

### Version

7.1.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please try to use **Entity-Cache**

https://docs.abp.io/en/abp/latest/Entity-Cache

**Comment by Alexandre789010** [comment]
Hi maliming,

Thanks for the quick reply.

I don't really understand how I could use entity-cache to cache a list of entity? Could you provide an example?

My cache key is made from parameters, see below:

```csharp

    private readonly IDistributedCache<List<Plant>> _cache;
    private readonly IPlantRepository _plantRepository;

    public PlantAppService(IDistributedCache<List<Plant>> cache, IPlantRepository plantRepository)
    {
        _cache = cache;
        _plantRepository = plantRepository;
    }
    
    public async Task<List<PlantDto>> GetListAsync(GetPlantListDto input)
    {
        var key = $"plant_list_{string.Join('_', input.DispatchGroups)}";
        var plants = await _cache.GetOrAddAsync(
                                                key,
                                                async () => await _plantRepository.GetListByDispatchGroupsAsync(input.DispatchGroups),
                                                () => new DistributedCacheEntryOptions
                                                {
                                                    AbsoluteExpiration = DateTimeOffset.Now.AddHours(1)
                                                }
                                               );
        
        return ObjectMapper.Map<List<Plant>, List<PlantDto>>(plants);
    }

```

**Comment by maliming** [comment]
Please add `AbpIncludeNonPublicPropertiesModifiers` to `Modifiers` of `AbpSystemTextJsonSerializerModifiersOptions`.

```cs
services.Configure<AbpSystemTextJsonSerializerModifiersOptions>(options =>
{
    options.Modifiers.Add(new AbpIncludeNonPublicPropertiesModifiers<Plant, string>().CreateModifyAction(x => x.Id));
});
```

https://github.com/abpframework/abp/blob/AttachScopes/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Caching/EntityCacheServiceCollectionExtensions.cs#L32

**Comment by Alexandre789010** [comment]
Works like a charm, thanks a lot!

**Comment by ahmadalmunajjed** [comment]
Hi @maliming is still adding AbpIncludeNonPublicPropertiesModifiers to Modifiers of AbpSystemTextJsonSerializerModifiersOptions necessary?
What is the reason of the issue? can it be solved?

**Comment by maliming** [comment]
hi @AhmadAlMunajjed 

You dont need to add `AbpIncludeNonPublicPropertiesModifiers` if you using the [Entity-Cache](https://docs.abp.io/en/abp/latest/Entity-Cache)

**Comment by ahmadmasoum** [comment]
Hi @maliming 
Is there a walkaround for older ABP version 5.4.3 ? since there's no AbpSystemTextJsonSerializerModifiersOptions
