### ISSUE TITLE
NPM install broken.

### ISSUE THREAD

**Issue by dmeagor** [abpframework/abp#16151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've tried creating various project types with both the CLI and the suite, Angular, MVC. Tiered/Untiered.

NPM install refuses to work with this error.

![image](https://user-images.githubusercontent.com/714902/229354206-fc53d15a-83ed-4807-ae1a-9dcb37722323.png)

Yarn seems to work.

I assume the missing bundle message on the MVC projects is also related.

### Reproduction Steps

npm install

### Known Workarounds

use yarn (peer dependency warnings still appear but it works)

### Version

7.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by masum-ulu** [comment]
Hi @dmeagor, 

I tried to create new project with **ABP 7.1.0** version and UI is angular, after I create template I ran `npm install` command and it's worked correctly for me
- `abp new Volo.ExampleApp -csf -t app -u angular` this is my CLI command

Can you tell me how can I produce this error ?

**Comment by dmeagor** [comment]
I'm using a clean virtual machine with .net 7 and node 16.

I used the code

abp new ExampleApp -u angular

I also used the suite.

Maybe npm has cached something on your pc?

Yarn did complete but had these warnings.
![image](https://user-images.githubusercontent.com/714902/229364526-a9c9a81c-9117-4095-849f-7d94992378fc.png)

**Comment by dmeagor** [comment]
When you ran abp new did the cli automatically detect yarn and run that instead of npm?

**Comment by masum-ulu** [comment]
Hi @dmeagor, Thanks for answer

The problem in the [theme-shared](https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages/theme-shared) / [dependency](https://github.com/abpframework/abp/blob/a8ed61bb1da8bb0be068359a3ffca6adce5547bf/npm/ng-packs/packages/theme-shared/package.json#L12), looks like we are using both version of @ng-bootstrap package
We'll take care about it but my advice is the using `yarn` or `npm install --legacy-peer-deps` command for solution. I'm moving this issue to [here](https://github.com/abpframework/abp/issues/16152) and closing this
