### ISSUE TITLE
All tabs are refreshing continuously using ABP commercial

### ISSUE THREAD

**Issue by Quangdung1996** [abpframework/abp#16160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We use ABP framework commercial version.

When the user opens more than two tabs simultaneously, after a while, all tabs start to refresh continuously. As we investigated, this issue probably is related to the refresh token mechanism, in which all tabs have shared one Local Storage in the browser. There is a chance that tabs override token values of each other. Our first guess was that we might have changed the structure of ABP which led to this problem, but when we checked the default project, we realized that after the end of the access token, the users in the adjacent tabs are automatically logged out. This is a problem in itself and we don't want the user to log out after each access token ends. Logging out of the user should happen when the refresh token expires. 
https://stackoverflow.com/questions/75372751/all-tabs-are-refreshing-continuously-using-abp-commercial

### Version

5.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
You can get help with ABP commercial at https://support.abp.io/
