### ISSUE TITLE
Create new Module inside framework

### ISSUE THREAD

**Issue by thanhtai9606** [abpframework/abp#16186]
I wanna create new module inside abp framework and add references into template project. I already added correct project as
Application into template asp-net Application ... and so on. But when I build it, error here

> `System.IO.FileNotFoundException: Could not load file or assembly 'Volo.Abp.Core, Version=7.0.3.0, Culture=neutral, PublicKeyTok[989/5633]

> The system cannot find the file specified.

> File name: 'Volo.Abp.Core, Version=7.0.3.0, Culture=neutral, PublicKeyToken=null'

 

>   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo `pCtor,` Byte** ppBlob,

 

> Byte* pEndBlob, Int32* pcNamedArgs)`
How to create new module correct?? please help

**Comment by maliming** [comment]
* Your ABP Framework version.
* Your User Interface type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and stack trace if available (check the logs).
* Steps needed to reproduce the problem.

**Comment by thanhtai9606** [comment]
Thank, I solved, I must add module inside template/module, it working now!!!
