### ISSUE TITLE
String validation on DTO

### ISSUE THREAD

**Issue by andmattia** [abpframework/abp#16187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi

I migrate my application from 5.3.1 to 7.1.0 and my DTO's that has a string field need to be set
```cs
public string Filter {get;set;}
public string? Filter {get;set;}
```

On Angular side my interface still remain 
```ts
filter?: string;
```

### Reproduction Steps

Create a DTO with string field

### Version

7.1.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
What's expected behavior?

**Comment by andmattia** [comment]
In 5.3.1 the same code pass validation in 7.1.0 no. 
```log
2023-04-04 02:19:04.299 +02:00 [WRN] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "Your request is not valid!",
  "details": "The following errors were detected during validation.\r\n - The Maps field is required.\r\n - The Filters field is required.\r\n",
  "data": {},
  "validationErrors": [
    {
      "message": "The Maps field is required.",
      "members": [
        "maps"
      ]
    },
    {
      "message": "The Filters field is required.",
      "members": [
        "filters"
      ]
    }
  ]
}

2023-04-04 02:19:04.299 +02:00 [WRN] ModelState is not valid! See ValidationErrors for details.
```
If I configure my DTO in this way

```cs
public string Filter {get;set;}
public string Maps {get;set;}
```
If I change with this code it works as expected (ModelState is valid).
```cs
public string? Filter {get;set;}
public string? Maps {get;set;}
```

**Comment by maliming** [comment]
Is your project has `<Nullable>enable</Nullable>`?

**Comment by andmattia** [comment]
Yes because I found it on new template for Contracts module template.
```xml
<Nullable>enable</Nullable>
```

I remove this and it works as previuos version. So I think ReShaper do this during migration process beacuse if I recreate the module from scracth I don't see this option

**Comment by maliming** [comment]
This is asp net core behavior.

https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-7.0#non-nullable-reference-types-and-required-attribute
