### ISSUE TITLE
Cannot compile Blazor Server application using basic theme

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#16195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Created a new Blazor Server application selecting the basic theme but when I compile I get the following error:

C:\Projects\Acme.BookStore\src\Acme.BookStore.Blazor\Pages\_Host.cshtml(4,42): error CS0234: The type or namespace name 'LeptonXLiteTheme' does not exist in the namespace 'Volo.Abp.AspNetCore.Components.Web' (are you missing an assembly reference?) [C:\Projects\Acme.BookStore\src\Acme.BookStore.Blazor\Acme.BookStore.Blazor.csproj]

Build FAILED.

I tried removing the following from ..\src\Acme.BookStore.Blazor\Pages\_Host.cshtml

@using Volo.Abp.AspNetCore.Components.Web.LeptonXLiteTheme.Themes.LeptonXLite

but now get the following error:

C:\Projects\Acme.BookStore\src\Acme.BookStore.Blazor\Pages\_Host.cshtml(23,81): error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\Acme. BookStore\src\Acme.BookStore.Blazor\Acme.BookStore.Blazor.csproj]

### Reproduction Steps

abp new Acme.BookStore -u blazor-server --theme basic

dotnet build

### Version

7.1.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Please use latest ABP CLI 7.1.1.

**Comment by DonVliet** [comment]
@maliming Thanks for the quick response. I was using latest ABP CLI 7.1.1 - I have now upgraded to ABP CLI 7.2.0-rc.1 and still have the same problem. When creating the project using --theme basic (and --version 7.2.0-rc.1) the ..\src\Acme.BookStore.Blazor\Pages\_Host.cshtml file contains:

@using Volo.Abp.AspNetCore.Components.Web.LeptonXLiteTheme.Themes.LeptonXLite

even though I am not using the Lepton theme

**Comment by EngincanV** [comment]
@DonVliet The problem has been fixed and will be available within the next releases. For now, please remove the wrong namespace.
