### ISSUE TITLE
UnitOfWorkAttribute with requiresNew property

### ISSUE THREAD

**Issue by iyilm4z** [abpframework/abp#16198]
Hi,

The `UnitOfWorkAttribute` doesn't have the **requiresNew** property. Is there any special reason why you prefer using the `IUnitOfWorkManager.Begin` method instead of a **requiresNew** property that the  `UnitOfWorkAttribute` easily can have? Don't you think this will allow us to have an easier API?

Thanks,

**Comment by maliming** [comment]
hi

If there is no uow, the `UnitOfWorkAttribute` will begin a new uow.
If there is already uow the `UnitOfWorkAttribute` will be ignored.

https://docs.abp.io/en/abp/latest/Unit-Of-Work#unitofworkattribute-properties

> If a method is called in an ambient UOW scope, then the UnitOfWork attribute is ignored and the method participates to the surrounding transaction in any way.
