### ISSUE TITLE
How Can I Change AbpAuditLogs table

### ISSUE THREAD

**Issue by CaglarMacha** [abpframework/abp#16205]
Hello, 
I am a sophomore in the software world and need to change the max length of the Parameters field in the AbpAuditLogs table by using migration. How can I change it?

**Comment by berkansasmaz** [comment]
For instance: 

You can try to change the `MaxCorrelationIdLength` then add new migrations.

https://github.com/abpframework/abp/blob/feb02a89189f134e4e16780b6ae725dfb030d705/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain.Shared/Volo/Abp/AuditLogging/AuditLogConsts.cs#L28

ref: https://stackoverflow.com/questions/tagged/abp

**Comment by CaglarMacha** [comment]
Thank you so much. By the way,  which class would it be best to set this value to without downloading the audit log module? Is the constructor method of DbContext best practice?

**Comment by CaglarMacha** [comment]
> For instance:
> 
> You can try to change the `MaxCorrelationIdLength` then add new migrations.
> 
> https://github.com/abpframework/abp/blob/feb02a89189f134e4e16780b6ae725dfb030d705/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain.Shared/Volo/Abp/AuditLogging/AuditLogConsts.cs#L28
> 
> ref: https://stackoverflow.com/questions/tagged/abp

Thank you so much. By the way, which class would it be best to set this value to without downloading the auditLog module? Is the constructor method of DbContext best practice?

**Comment by berkansasmaz** [comment]
Yes, you need to call code like below in the first line of `OnModelCreating` method in `YourDbContext`.

```csharp

AuditLogConsts. MaxCorrelationIdLength = 128;

```
