### ISSUE TITLE
Volo.Abp.Http.Client.AbpRemoteCallException: Unauthorized

### ISSUE THREAD

**Issue by souselesslove** [abpframework/abp#16208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created two api projects: "AService","BService",
then I followed the guide of [Dynamic C# API Client Proxies](https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients),
i can use AService.GetAsync() to call BService.GetAsync() and worked
![image](https://user-images.githubusercontent.com/26608215/230668465-ea37f559-3395-429e-86dd-705765e0c3cd.png)
but i added [Authorize] on BService.GetAsync(), it threw an 401 exception 
![image](https://user-images.githubusercontent.com/26608215/230668697-fcd83184-4f9a-497a-b864-db1ec95406e4.png)
the scope of the bearer token included both AService and BService.

### Version

7.1.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

i had tried the solusion of [#9102](https://github.com/abpframework/abp/issues/9102)

**Comment by maliming** [comment]
Please refer to the `ConsoleTestApp`.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp/appsettings.json#L7

**Comment by souselesslove** [comment]
> Please refer to the `ConsoleTestApp`.
> 
> https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp/appsettings.json#L7

thank you! I will try it.
I also have solved it like this:
![image](https://user-images.githubusercontent.com/26608215/230762224-0d7e4457-f9b0-4a4a-974c-d5712aa9e3c6.png)
