### ISSUE TITLE
UpdateProfileDto with ExtraProperties

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#16211]
Hi,
I extended IdentityUser with two properties everything is working fine. but when i use the endpoint my-profile (Patch) to update i lose all the datas in ExtraProperties because the UpdateProfileDto doesn't contine it.

Who can i configure (add) the extraproperties in UpdateProfileDto.

i tried this : 
in ProjectDtoExtensions.cs

``` cs

public static void Configure()
    {
        OneTimeRunner.Run(() =>
        {

            ObjectExtensionManager.Instance
                .AddOrUpdateProperty< string>(
                 new[]
                {
                    typeof(UpdateProfileDto)
                },

                ProfileConsts.ProfileType);
            ObjectExtensionManager.Instance
                .AddOrUpdateProperty<Guid>(
                                 new[]
                {
                    typeof(UpdateProfileDto)
                },
                ProfileConsts.ProfilePictureId);
        });
```
but it's not working. any help please ;-)

![image](https://user-images.githubusercontent.com/5918026/230746025-8c9094c5-27d1-4cb4-9c0e-5d1cead2e6f3.png)

**Comment by LordOfCinder2000** [comment]
Can you provide more information?

**Comment by aelhadi** [comment]
When you extend IdentityUser, the ExtraProperties are not present in UpdateProfileDto.

**Comment by berkansasmaz** [comment]
Thanks for the report @aelhadi 🎉

I will test it as soon as possible and get back to you.

**Comment by berkansasmaz** [comment]
I have examined your problem, it will work if you send a request as follows:

```csharp
{
  "userName": "admin",
  "email": "admin@abp.io",
  "name": "admin",
  "surname": null,
  "phoneNumber": null,
  "isExternal": false,
  "hasPassword": true,
  "concurrencyStamp": "5da4a0544bc94582b693f3faa941209d",
  "extraProperties": {
        "ProfileType": "TestProfileType",
        "ProfilePictureId": "3a0bcaf5-3d88-62e3-3633-204a540865d7"
  }
}


```

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
