### ISSUE TITLE
Dynamic Api HttpClient return null (204) when the interface don't use  genericType argument

### ISSUE THREAD

**Issue by lic0914** [abpframework/abp#16210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MyAppService such as
 
```csharp
public interface IDemoApiAppService:IApplicationService
{
    ApiResult Get();
}
```
Client-side AppService 
```csharp  
    [HttpGet("remote")]
    public ApiResult GetRemote([FromServices] IDemoApiAppService demoApiAppService)
    {
        var result= demoApiAppService.Get();
        return result;
    }
```
Dynamic Api HttpClient return null , http status code retrun 204

I found it when searched  source code 
[DynamicHttpProxyInterceptor](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs#L62)

### Expected behavior

If thie interface can't use generic type arguments when using dynamic api httpclient ,You had better output information to console 

Of course,it would be best return the value set by 

### Actual behavior

retrun null

### Version

7.1.1

### User Interface

Common (Default)

### Database Provider

None/Others

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

**Reproduction Steps**
