### ISSUE TITLE
React Native project in Development: Disable SSL Not working as per Doc

### ISSUE THREAD

**Issue by Enissay** [abpframework/abp#16213]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests, and other discussions about the framework.

If you're creating a bug/problem report, please include the followings:

* Your **ABP Framework version**: ABP CLI 7.1.1
* Your **User Interface**: React Native
* Your database provider: EF Core
* Steps needed to **reproduce** the problem:

Simply create a new project using the below command:
```bash
abp new MyNewProject --ui blazor-server -dbms PostgreSQL --mobile react-native --tiered --create-solution-folder
```

Then try to run it locally as per doc: https://docs.abp.io/en/abp/latest/Getting-Started-React-Native?Tiered=Yes
In the section regarding disabling SSL to be able to test locally in Development mode:
> You should add this code on MyProjectNameHttpApiHostModule.
```c#
  public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        #if DEBUG
            PreConfigure<OpenIddictServerBuilder>(options =>
            {
                options
                    .UseAspNetCore()
                    .DisableTransportSecurityRequirement();
            });
        #endif
        //....
    }
```
It does not work:

![image](https://user-images.githubusercontent.com/794673/230793726-c2b3c6c3-d289-4a87-8ce4-7bce2f196445.png)

I tried to skip it and completed the other steps, but Blazor and the App are unable to start:

![image](https://user-images.githubusercontent.com/794673/230793892-1e6395e2-3813-4af5-8551-c63fc9756097.png)
![image](https://user-images.githubusercontent.com/794673/230793897-cd9c2969-9233-46ae-9cde-b434ef15028d.png)
![image](https://user-images.githubusercontent.com/794673/230793899-a5882b9d-a083-4cae-bb31-ef525301d6ec.png)

**Comment by berkansasmaz** [comment]
Hi, I noticed the trouble you are having while trying to reproduce your problem. Your application is tiered, but "Getting Started with the React Native" document is not changed accordingly, even if the tiered option is selected.

You should add the following code to `MyProjectAuthServerModule`, not `MyProjectNameHttpApiHostModule`.

```csharp
#if DEBUG
        PreConfigure<OpenIddictServerBuilder>(options =>
        {
            options
                .UseAspNetCore()
                .DisableTransportSecurityRequirement();
        });
#endif
```

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
