### ISSUE TITLE
Error when completing unit of work

### ISSUE THREAD

**Issue by rwoznicki** [abpframework/abp#1623]
Let's assume following scenario.
There are two modules Products and Sales. Each of them have their own DBContext.
There is operation performed on ProductsModule that creates product and publish local event ProductCreatedEvent.
Next ABP calls UnitOfWork.Complete and UnitOfWork.SaveChangesAsync, so finally it calls SaveChanges on all currently registered databaseApis (DbContexts in that case). In that moment there is only one databaseApi- ProductsDbContext. After saving changes, ABP triggers event handler from SalesModule.
This handler creates another object in Sales Module, so it involves SalesDbContext.
After completing actions in Sales module, process returns to UnitOfWork.SaveChangesAsync, but collections of registered  databaseApis has changed, so it throws error.

![image](https://user-images.githubusercontent.com/52193936/62939164-e7b8b580-bdd0-11e9-8843-8d4d8bb38c4f.png)

**Comment by maliming** [comment]
see: https://github.com/abpframework/abp/issues/1417

**Comment by rwoznicki** [comment]
Great, thanks.
