### ISSUE TITLE
Hope to soft delete relate entities in aggregate root but actually got hard deleting

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1624]
The list `OrderItems` is a FullAuditedEntity collection in `Order` AggregateRoot.
I run these code:
```
order.OrderItems.Remove(orderItem);
await Repository.UpdateAsync(order);
```
And then the `OrderItem` which I removed disappears form the database.
Hope to use soft delete but I dont know how to do.

**Comment by maliming** [comment]
Please share a project that reproduces the above problem. You can create it by using the CLI.

**Comment by gdlcf88** [comment]
https://github.com/gdlcf88/AbpSoftDeleteTest

**Comment by maliming** [comment]
After the official release of EF Core 3.0, we continue to solve this problem.
https://github.com/aspnet/EntityFrameworkCore/issues/12833
https://github.com/aspnet/EntityFrameworkCore/issues/10114

**Comment by gdlcf88** [comment]
Did it fixed by Microsoft?

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1798
