### ISSUE TITLE
localization validationmessage display by culture ?

### ISSUE THREAD

**Issue by duanwenhao** [abpframework/abp#16259]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

i create a class and use it in view, the class like this
```c#
public class TestViewModel
 {
      [Required]
      public string TestName { get; set; }
 }
```
the view code like this 
```c#
public IActionResult TestView()
 {
        TestViewModel model = new TestViewModel();
         return View(model);
 }

@model XXX.Web.Models.TestViewModel
@Html.TextBoxFor(m=>m.TestName)
```
my current culture is zh-Hans , the html render validationmessage like this, This is the result I want
```html
<input data-val="true" data-val-required="字段TestName不可为空." id="TestName" name="TestName" type="text" value="">
```
but when i move TestViewModel to Application.Contracts project , and i use it in view , the html render english validationmessage，this is not the result I wanted
```html
<input data-val="true" data-val-required="The TestName field is required." id="TestName" name="TestName" type="text" value="">
```
how to let html render validationmessage by current culture ?

**Comment by maliming** [comment]
This is related to the current culture of http reqeust.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?view=aspnetcore-7.0

**Comment by duanwenhao** [comment]
i create a new class
```c#
public class WrapperModel
 {
      public TestViewModel2 Model2 { get; set; }  //this class  in Web project
      public TestViewModel Model { get; set; } //this class in Application.Contracts prject
}
```
i use it in view 
```c#
public IActionResult TestView()
 {
      WrapperModel model = new WrapperModel();
      return View(model);
 }

@Html.TextBoxFor(m=>m.Model.TestName)
@Html.TextBoxFor(m=>m.Model2.TestName2)
```
The presentation is as follows
```html
<input data-val="true" data-val-required="The TestName field is required." id="Model_TestName" name="Model.TestName" type="text" value="">
<input data-val="true" data-val-required="字段TestName2不可为空." id="Model2_TestName2" name="Model2.TestName2" type="text" value="">
```
Can't they be displayed the same?

**Comment by duanwenhao** [comment]
I found the reason，need AddAssemblyResource
