### ISSUE TITLE
How to change favicon in LeptonX Lite on .NET side ?

### ISSUE THREAD

**Issue by lukagalovic** [abpframework/abp#16253]
* ABP version: 7.1.1
* UI: Angular
* Db: EF Core

How can I change favicon that is being loaded on the .NET side of application ? I can't find place where it is pulled.

Do I have to replace whole Account module for that ?

**Comment by berkansasmaz** [comment]
### For favicon

You can add a favicon to the `~/wwwroot/favicon.svg` and `~/wwwroot/favicon.ico` path to override the current favicon. (We have an open [issue](https://github.com/abpframework/abp/issues/16262) about this problem and we'll improve and make it easier to customize)

### For brand component

As I understand that you want to change the brand component on the account module side. You can use [this document](https://docs.abp.io/en/abp/latest/Themes/LeptonXLite/AspNetCore#brand-component) for this.

Please let me know if I misunderstood or the solution doesn't work for you.

**Comment by lukagalovic** [comment]
I added `~/wwwroot/favicon.ico` but it still does not change. I tried clearing cache but problem persists.

Not a big problem so I can wait till `7.2 milestone`.

**Comment by berkansasmaz** [comment]
You also need to add `~/wwwroot/favicon.svg`.

---

> Not a big problem so I can wait till 7.2 milestone.

So, I'm closing the issue as we already have an issue on this.
