### ISSUE TITLE
easy CRM demo broke

### ISSUE THREAD

**Issue by geekyaniruddha** [abpframework/abp#16254]
https://easycrm.abp.io/ is not working.. Kindly check. 
![EasyCRM broke](https://user-images.githubusercontent.com/30797204/231483881-3851afb1-c3d7-4322-88f8-9ce7a70e22b0.png)

**Comment by maliming** [comment]
hi

It works now.

**Comment by geekyaniruddha** [comment]
Thanks. 
Dashboard page is also not working. Please refer to the below screenshot. 

![image](https://user-images.githubusercontent.com/30797204/231636792-dde698c2-ab73-48ae-b812-d40c303b9015.png)

**Comment by ebicoglu** [comment]
![image](https://user-images.githubusercontent.com/9526587/231732921-1f604936-7870-4b8b-be8d-3b9e46796fc7.png)

**Comment by onurpicakci** [comment]
Thanks for reporting these problems, we have fixed them.

**Comment by dicksonkimeu** [comment]
It's the abp easy upgraded to use leptonx and .net 7 ?
