### ISSUE TITLE
After migrating to Oracle, how to solve the problem of double quotation marks in SQL?

### ISSUE THREAD

**Issue by AnonymousDotNet** [abpframework/abp#16263]
How does Oracle solve the problem that SQL statements need double quotation marks after data migration?

Version：7.0+
EF CORE：7.1+ / Oracle 12c
MVC
![1](https://user-images.githubusercontent.com/19584200/231718645-0e9f9b8f-96d6-4f95-8832-5efe94b11e5e.png)

**Comment by berkansasmaz** [comment]
This issue doesn't seem to be related to ABP. However, after short research on the subject, I believe the links below will solve your question.

- https://stackoverflow.com/questions/73005441/entity-framework-core-automatically-inserts-double-quotes-in-oracle-database
- https://forums.oracle.com/ords/apexds/post/oracle-ef-core-with-disablequoting-2191

**Comment by AnonymousDotNet** [comment]
> 



> 这个问题似乎与ABP无关.但是，经过对该主题的简短研究，我相信下面的链接将解决您的问题。
> 
> * https://stackoverflow.com/questions/73005441/entity-framework-core-automatically-inserts-double-quotes-in-oracle-database
> * https://forums.oracle.com/ords/apexds/post/oracle-ef-core-with-disablequoting-2191

I know this issue has nothing to do with ABP, but I wanted to adapt it to Oracle's default capitalization behavior, and I tried adding the following code to the OnModelCreating method in the ExamineDbContext class under EF CORE:
`// Loop through all table names and convert uppercase
         foreach (var entityType in builder.Model.GetEntityTypes())
         {
             int num = entityType.Name.LastIndexOf('.');
             string tableName = entityType.Name.Substring(num + 1);
             entityType.SetTableName($"ABP{tableName.ToUpper()}");
         }

         // Cloumns
         foreach (var property in builder.Model.GetEntityTypes().SelectMany(e => e.GetProperties()))
         {
             property.SetColumnName(property.Name.ToUpper());
         }

         // key
         foreach (var index in builder.Model.GetEntityTypes().SelectMany(e => e.GetIndexes()))
         {
             if (index?.Name != null)
             {
                 index.SetDatabaseName(index.Name.ToUpper());
             }
         }`

Although the generated names of the above operations are converted to uppercase, the run will report an error, and I have not yet figured out the cause。

**Comment by AnonymousDotNet** [comment]
> This issue doesn't seem to be related to ABP. However, after short research on the subject, I believe the links below will solve your question.
> 
> * https://stackoverflow.com/questions/73005441/entity-framework-core-automatically-inserts-double-quotes-in-oracle-database
> * https://forums.oracle.com/ords/apexds/post/oracle-ef-core-with-disablequoting-2191

I know this issue has nothing to do with ABP, but I wanted to adapt it to Oracle's default capitalization behavior, and I tried adding the following code to the OnModelCreating method in the ExamineDbContext class under EF CORE:

*Although the generated names of the above operations are converted to uppercase, the run will report an error, and I have not yet figured out the cause。

``` C#
// Loop through all table names and convert uppercase
foreach (var entityType in builder.Model.GetEntityTypes())
         {
             int num = entityType.Name.LastIndexOf('.');
             string tableName = entityType.Name.Substring(num + 1);
             entityType.SetTableName($"ABP{tableName.ToUpper()}");
         }

         // Cloumns
         foreach (var property in builder.Model.GetEntityTypes().SelectMany(e => e.GetProperties()))
         {
             property.SetColumnName(property.Name.ToUpper());
         }

         // key
         foreach (var index in builder.Model.GetEntityTypes().SelectMany(e => e.GetIndexes()))
         {
             if (index?.Name != null)
             {
                 index.SetDatabaseName(index.Name.ToUpper());
             }
         }
``` C#

**Comment by maliming** [comment]
>  the run will report an error,

What's the error?

**Comment by AnonymousDotNet** [comment]
> > the run will report an error,
> 
> What's the error?



> 

I executed "dotnet ef migrations add" and was successful and then run". dbMigrator", reporting the error "Table or view does not exist", as shown below:
![VS_ERRO](https://user-images.githubusercontent.com/19584200/232947846-74cc5839-ddd4-438e-8dd5-f95aa8dffc79.png)

I looked at the generated file, where Init converted the field to uppercase, as shown below:
![VS_Init1](https://user-images.githubusercontent.com/19584200/232947907-816c3b04-3c69-4a12-935b-8f0824f58bff.png)

But in "BookStoreDbContextModelSnapshot" is still displayed case sensitivity, is this the cause of the error? But I don't know how to rephrase to solve this problem. As shown in the following figure:
![VS_Init2](https://user-images.githubusercontent.com/19584200/232947938-f374531c-7e5a-4f6a-8390-670f6fd401f2.png)

**Comment by maliming** [comment]
You can try your code in EF Core without abp framework.

**Comment by AnonymousDotNet** [comment]
> You can try your code in EF Core without abp framework.

Ok, I'll try; Do you understand Chinese? Just wrote Chinese didn't translate, hahaha

**Comment by maliming** [comment]
a little. ; )
