### ISSUE TITLE
New CLI Command: switch-to-local

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#16277]
ABP CLI provides the following commands:

* `switch-to-stable`: Switches to the latest stable versions of the ABP related packages on a solution.
* `switch-to-nightly`: Switches to the latest [nightly builds](https://docs.abp.io/en/abp/latest/Nightly-Builds) of the ABP related packages on a solution.
* `switch-to-preview`: Switches to the latest preview version of the ABP Framework.

These are great. I want one more:

* `switch-to-local`: Changes all NuGet package references to local project references for all the `.csproj` files in the current folder (and all its subfolders with any deep)

**Usage:**

````bash
abp switch-to-local --paths "D:\Github\abp|D:\Github\volo"
````

Here, I provided two paths separated with `|`: `D:\Github\abp` and `D:\Github\volo`. I expect that:

* Find all `.csproj` files in the current folder  (and all its subfolders with any deep)
* Find all NuGet package references (like `<PackageReference Include="..." Version="..." />`) **even if it is not ABP package**!
* Search the given paths, find all target `.csproj` files.
* Replace all package references to local project references for all the maching projects for the nuget package references.

This will be a useful command when we have local source code of any library (package), not only ABP packages. Obviously, it won't replace any NPM package. I don't expect that.

**Comment by gdlcf88** [comment]
Hi, does this local reference mode violate the LGPL-3.0 license?

**Comment by hikalkan** [comment]
@gdlcf88 I suppose it violates if you don't share your modified ABP version with the same license.

We will use this feature for test projects only. In this way, we don't need to wait for nightly releases. We can immediately use an API added to the framework with local references, test the feature.
