### ISSUE TITLE
Default application template in docker container is not working

### ISSUE THREAD

**Issue by maskalek** [abpframework/abp#16279]
I installed default application template using Abp Suite.

According to instructions I run `build-images-locally.ps1` and then `run-docker.ps1.`

Everything seems to be working, no errors in the logs. But when I try to open swagger page on https://localhost:44354/swagger have default error 'This page isn’t working'. Did I miss something? What is default steps here to find out where is the problem?

Also, tried to run it without containers, everything is working.

**Comment by maliming** [comment]
hi

Please create a question at https://support.abp.io/

Thanks
