### ISSUE TITLE
`ITenantManager` isn't efficient when inserting alot of tenants

### ISSUE THREAD

**Issue by ahmednfwela** [abpframework/abp#16296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`ITenantManager` has 2 main issues:
1. It isn't optimized for bulk operations
2. No way to override the generated Id

### Reproduction Steps

the `ITenantManager` has the following interface:
```csharp
public interface ITenantManager : IDomainService
{
    Task<Tenant> CreateAsync(string name);
    Task ChangeNameAsync(Tenant tenant, string name);
}
```

### Version

7.1.0

### User Interface

Common (Default)

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

 I suggest the following changes to its interface:
```csharp
public interface ITenantManager : IDomainService
{
    Task<Tenant> CreateAsync(string name, Guid? id = null);
    Task<List<Tenant>> CreateManyAsync(IEnumerable<string> names);
    Task<List<Tenant>> CreateManyAsync(IEnumerable<KeyValuePair<Guid?, string>> entries);
    Task ChangeNameAsync(Tenant tenant, string name);
    Task ChangeNameAsync(IEnumerable<KeyValuePair<Tenant, string>> entries);
}
```
which should handle bulk operations fairly well

**Comment by maliming** [comment]
> It isn't optimized for bulk operations

What's your way?

> No way to override the generated Id

Why do you need to change the Id?

**Comment by ahmednfwela** [comment]
I want to seed my tenants from a json file from a different database, so I need to adapt the same Ids as the other database, and I want to be able to insert >1000 tenants at once, both of these are currently impossible since `CreateAsync` checks on each call for name duplicates, and doesn't accept ids

**Comment by maliming** [comment]
You can create your own `TenantManager` for your case.

**Comment by ahmednfwela** [comment]
That would be ok if the `Tenant`'s constructor wasn't internal

**Comment by maliming** [comment]
`ObjectHelper.TrySetProperty`.


https://github.com/abpframework/abp/blob/a25af1b7ae396baa59cb4f4a841b966db91e9abb/framework/src/Volo.Abp.Core/Volo/Abp/ObjectHelper.cs#L10

**Comment by ahmednfwela** [comment]
how would I set the property if I can't construct the object?

**Comment by gdlcf88** [comment]
> I want to seed my tenants from a json file from a different database, so I need to adapt the same Ids as the other database, and I want to be able to insert >1000 tenants at once, both of these are currently impossible since `CreateAsync` checks on each call for name duplicates, and doesn't accept ids

Use `Tenant.Name` to identify them, and do not specify the ID properties.

**Comment by ahmednfwela** [comment]
it still doesn't solve the N+1 problem when inserting a lot of tenants, since each Create does a query to the database

**Comment by gdlcf88** [comment]
> so I need to adapt the same Ids as the other database

You can uninstall the TenantManagement module and implement the `ITenantStore` yourself.

**Comment by ahmednfwela** [comment]
yes, I can also download the tenant management module source code and build on top of it, but I think a more realistic solution is to optimize the existing module for bulk operations.

anyway I am not asking for alternatives, and I can create a PR to make the changes if there is an agreement on this

**Comment by gdlcf88** [comment]
What you need is an alternative, in fact.

Let me explain.

If you use the TenantManagement module, it is your app cluster's unique tenant store. So it is unnecessary to specify `Tenant.Id` since there will never be "Tenant ids from other databases".

If the "Tenant ids from other databases" already exist, it should indeed be the unique tenant store. So removing the TenantManagement module and implementing a new tenant store is all you need to do.

**Comment by ahmednfwela** [comment]
sorry if my comment was understood the wrong way, the "different database" is simply an excel file that my customer has exported from another database, and he wants to import it and "add" it to my database.

While there are many workarounds and tradeoffs I can make, I don't think my use case here is relevant, I think that ABP's motto is customizability and performance, and I think being able to override the ids of created entities, and creating a lot of entities efficiently is aligning with that.

anyway, I am opening this issue to document this feature request, and I am offering to create a PR for it. If this feature is not considered important/valid feel free to close this.

**Comment by piconnectdev** [comment]
I have same problem.
I'm porting [Odoo ERP](https://odoo.com) to ABP. I do map as below:
 - Convert fields "Id" data type serial to type UUID.
 - Company -> Tenant, 
 - User -> IdentityUser.
No easy way to create Tenant with pre-defined Id/Name.

**Comment by gdlcf88** [comment]
> * Convert fields "Id" data type serial to type UUID.
> * Company -> Tenant,
> * User -> IdentityUser.
>   No easy way to create Tenant with pre-defined Id/Name.

Map all the old IDs to the new generated IDs.

Or use your old system as the tenant provider.
