### ISSUE TITLE
FileManager query list returned data creationTime error

### ISSUE THREAD

**Issue by xiexingen** [abpframework/abp#16300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://user-images.githubusercontent.com/7939085/232801272-41650163-118b-4615-bef1-abe32293c2ee.png)

### Version

7.1.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please get help with commercial on https://support.abp.io/
