### ISSUE TITLE
Auto generated MenuItem.ElementId is not readable by BS nav pills

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#16312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The auto generated element id contains CompanyName_ProjectName.Menu.Name and it is not readable by BS nav pills and tabs. We must remove ```.``` char. This is an BS related bug. 

### Version

7.1.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

We can remove ```_``` and ```.``` to solving this:
```cshtml
    @{
        var itemId = Model.MenuItem.ElementId.Replace("_", "").Replace(".", "");
        //CompanyNameProjectNameMenuName 
    }
    <div class="nav-item">
        <a class="nav-link dropdown-toggle @(Model.IsActive ? "active" : "")" href="#@itemId" role="button" data-bs-toggle="collapse" data-bs-target="#@itemId" aria-expanded="@Model.IsActive" aria-controls="@itemId">
            @Model.MenuItem.DisplayName
        </a>

        <div id="@itemId" class="nav-collapse collapse @(Model.IsActive ? "show" : "")" data-bs-parent="#@Model.ParentId">
            @foreach (var childMenuItem in Model.Items)
            {
                childMenuItem.ParentId = itemId;
                @await Html.PartialAsync("~/Themes/Dashboard/Partials/Components/Collapse/_vertical-item.cshtml", childMenuItem)
            }
        </div>
    </div>
```

**Comment by EngincanV** [comment]
Thanks, I will be working on it.
