### ISSUE TITLE
Introduce a global point to be informed when a new distributed message received or sent

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#16321]
I want to know when my application receives or sends an event from/to the distributed event bus. We can publish **local events** for these. We need to events:

* DistributedEventReceived: This should be triggered when we receive a distributed event from the event bus. I also want to know if inbox is used. If inbox is used, we can trigger the same event twice, one when we receive the event, before saving to inbox, one when we process the event from the inbox. You can add a property to the local event args to understand the difference. If not inbox used, directly trigger the local event. Always trigger the local event with try-catch and ignore any error.
* DistributedEventSent: This should be triggered when we receive a distributed event from the event bus. Just like the inbox explained above, also consider the outbox here.

I want to use that system to log/trace/debug distributed messaging in a global point in my application.

**Comment by leonkosak** [comment]
@hikalkan will this be "compatible" with DTM (https://community.abp.io/posts/introduce-dtm-for-multitenant-multidatabase-scene-23ziikbe)?

**Comment by hikalkan** [comment]
@leonkosak I don't have an idea. Maybe you can ask to the author of the article.
