### ISSUE TITLE
SSO With Keycloak has been blocked by CORS policy

### ISSUE THREAD

**Issue by thanhtai9606** [abpframework/abp#16328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I config Keycloak with Swagger I received this error
`from origin 'https://localhost:44300' has been blocked by CORS policy: Request header field requestverificationtoken is not allowed by Access-Control-Allow-Headers in preflight response.`
**But when I change config** 
` app.UseAbpSwaggerUI(options =>
        {
            options.SwaggerEndpoint("/swagger/v1/swagger.json", "Support APP API");

            var configuration = context.GetConfiguration();
            options.OAuthClientId(configuration["AuthServer:SwaggerClientId"]);
            options.OAuthScopes("MyProjectName");
            options.OAuthClientSecret(configuration["AuthServer:SwaggerClientSecret"]);
            options.OAuthScopes("MyProjectName");
            options.OAuthAppName("OAuth-app");
        });`

=> **It working when I use Incognito web browser**
When I use this it working fine after login keycloak . But I cannot call restApi it get error 400

`app.UseSwaggerUI(options =>
        {
            var configuration = context.GetConfiguration();
            options.SwaggerEndpoint("/swagger/v1/swagger.json", "Support APP API");
            options.OAuthClientId(configuration["AuthServer:SwaggerClientId"]);
            options.OAuthClientSecret(configuration["AuthServer:SwaggerClientSecret"]);
            options.OAuthScopes("MyProjectName");
            options.OAuthAppName("OAuth-app");
        });`

### Version

7.0.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

**Comment by gterdem** [comment]
Hi,

Did you add the api endpoint to the Keycloak allwoed CORS origins?

**Comment by thanhtai9606** [comment]
> Hi,
> 
> Did you add the api endpoint to the Keycloak allwoed CORS origins?

Yes I already added CORS inside keycloak and appsettings.json and it working fine when I used **app.UseSwaggerUI** only, But not working use app. UseAbpSwaggerUI

**Comment by realLiangshiwei** [comment]
**Reproduction Steps**

**Comment by craigwardman** [comment]
This seems to be related to the anti-forgery header that is added by the ABP JavaScript which is injected when using UseAbpSwaggerUI.

https://github.com/abpframework/abp/blob/7c8628ce74a1f506d4260db2a01f9f2b88118e11/framework/src/Volo.Abp.Swashbuckle/wwwroot/swagger/ui/abp.swagger.js#L49

Some 3rd party auth providers (in my case Auth0) don't allow much control over the CORS policy so this custom header is causing issues. I'm guessing that this probably shouldn't be sent to 3rd party websites anyway so the code could be updated to omit this header when the base URL isn't calling home.

EDIT: you can use this workaround to remove the header when talking to the IDP:

```
app.UseAbpSwaggerUI(c =>
        {
            c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API");

            var configuration = context.ServiceProvider.GetRequiredService<IConfiguration>();
            c.OAuthClientId(configuration["AuthServer:SwaggerClientId"]);
            c.Interceptors.RequestInterceptorFunction = @"function(request){if(request.url.indexOf('" + configuration["AuthServer:Authority"] + "') == 00){delete request.headers[abp.security.antiForgery.tokenHeaderName];}}";
        });
```
