### ISSUE TITLE
Angular additional property localization not working

### ISSUE THREAD

**Issue by ertugrulbakidal** [abpframework/abp#16337]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I've tried all possible solutions to localize a property  which is entity extension as described [here ](https://docs.abp.io/en/abp/7.1/Module-Entity-Extensions#property-options). But seems it's not working for Angular UI

### Reproduction Steps

    ObjectExtensionManager.Instance.Modules()
                    .ConfigureIdentity(identity =>
                    {
                        identity.ConfigureUser(user =>
                        {
                            user.AddOrUpdateProperty<string>( //property type: string
                                "SocialSecurityNumber", //property name
                                property =>
                                {
                                    //validation rules
                                    property.Attributes.Add(new RequiredAttribute());
                                    property.Attributes.Add(new StringLengthAttribute(64) { MinimumLength = 4 });

                                    property.Configuration[IdentityModuleExtensionConsts.ConfigurationNames.AllowUserToEdit] = true;

                                    //...other configurations for this property
                                    property.DisplayName =
                                      LocalizableString.Create<BookStoreResource>(
                                          "UserSocialSecurityNumberDisplayName"
                                      );
                                }
                            );
                        });
                    });

### Version

7.1.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

![angular_localization_issue](https://user-images.githubusercontent.com/40223108/233457417-53d9416e-6baf-499e-a4e2-0b6824082374.png)

![angular_localization_issue1](https://user-images.githubusercontent.com/40223108/233456720-4aa4f608-8947-4259-a098-e4ab2d7e8699.png)

**Comment by bariscanyilmaz** [comment]
Pass param with given format `::UserSocialSecurityNumberDisplayName`

```csharp
property.DisplayName = LocalizableString.
    Create<MyProjectNameResource>("::UserSocialSecurityNumberDisplayName");
```


![image](https://user-images.githubusercontent.com/30300440/236951070-3dbaf1c5-9a51-47cf-826d-9f008f65b662.png)

**Comment by ertugrulbakidal** [comment]
Thank you @bariscanyilmaz, it worked :)
