### ISSUE TITLE
After upgrading from ABP 5.1.2 to 7.0.1 I cannot add a claim to "Owned" (getting JS exception)

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#16336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After upgrading from ABP 5.1.2 to 7.0.1 I cannot add a claim to "Owned"
When I'm trying to move any claim from right to left:

![image](https://user-images.githubusercontent.com/6149843/233364945-85fdcb2d-d488-44d0-a292-28aca360c034.png)

I am getting JS exception (because the given property is "undefined"):

![image](https://user-images.githubusercontent.com/6149843/233364473-228f5d48-27ef-47fb-9ade-54e86ab2cc41.png)

The same goes for Identity Resources:

![image](https://user-images.githubusercontent.com/6149843/233365956-c85f2f4c-0b48-498c-8b16-230382e972f6.png)

FYI: we keep using Identity Server, not Open ID Dict - probably it has something to do with this.

### Version

7.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by masum-ulu** [comment]
Duplicated from [Support](https://support.abp.io/QA/Questions/4953/After-upgrading-from-ABP-512-to-701-I-cannot-add-a-claim-to-Owned-getting-JS-exception)
