### ISSUE TITLE
An exception was thrown using domain name multi-tenant resolution

### ISSUE THREAD

**Issue by lee-vic** [abpframework/abp#16341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After I upgraded the abp framework to 7.1.1, an exception occurred in the multi-tenant work. So I tested the abp/modules/openiddict example and got the same exception.I went through the code change log and found the relevant code changes in this update.
![image](https://user-images.githubusercontent.com/2107826/233759906-2b689745-4d3d-414d-863d-1286fd77919a.png)

### Reproduction Steps

![image](https://user-images.githubusercontent.com/2107826/233759928-05829ab4-be26-4b24-bbcd-ac6f22359748.png)

### Version

7.1.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/16284
