### ISSUE TITLE
IdentityUser PasswordHash is protected and can't be set on constructor either...Can't build an ORM extension for ABP

### ISSUE THREAD

**Issue by seiggy** [abpframework/abp#16340]
https://github.com/abpframework/abp/blob/013d450eae5b5763b7aaa602e7eec5b947414acf/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUser.cs#L63

I'm trying to build a CosmosDB extension for ABP, as the existing documented "workaround" does not function with specific configurations of CosmosDB (Specifically - using NOSQL CosmosDB with sdk 3.32.3-preview throws errors about using a variable named ChangeTracking for Change Tracking, as CosmosDB requires the variable to be named ETag when using EntityFrameworkCore change tracking, and you can't use MongoDB Driver with the NOSQL CosmosDB API).

 The PasswordHash on the IdentityUser is set as protected internal, which prevents the ORM from loading this data back into the object once serialized out to the database. IdentityUser should include a constructor which takes PasswordHash as an argument to allow for ORM extensions to be built.

Would this be an acceptable change? I'll send a PR if so.

**Comment by maliming** [comment]
> which prevents the ORM from loading this data back into the object once serialized out to the database.

Maybe `CosmosDB` should take care of this problem.

**Comment by seiggy** [comment]
CosmosDB can't solve that problem. It's a security feature of marking a property protected internal. It prevents classes from outside of the assembly from setting the value. If you want the value to be set from outside the assembly, you need to provide a constructor or change the accessibility of the setter to public.

**Comment by maliming** [comment]
Many of our modules have this kind of code. I suggest you download the source code and change it.

**Comment by seiggy** [comment]
Yeah, as I dig further into this, I see that most of your code can't be deserialized from outside your assemblies. Good for security, bad for extensibility. So I'm assuming this is working as intended, and close this.
