### ISSUE TITLE
Inconsistent implementation of GetDbContextAsync method

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#16357]
Hi.

I'm using ABP Community ver. 7.0.1

When i call EfCoreRepository<>.GetDbContextAsync with multitenancy on this method doesn't ack same as UnitOfWorkDbContextProvider<>.GetDbContextAsync method.

Repository<>.GetDbContextAsync  method first check if entity is multitenant and if it is then change current tenant to null. 
So ConnectionStringResolver return host's connection string.

On other hand UnitOfWorkDbContextProvider.GetDbContextAsync method only checks for ConnectionStringNameAttribute and 
then calls ConnectionStringResolver. In that case tenant connectionString is returned. Not host's.

From user perpective this is not ok. 

Such behavior has another consequence.

If i have multitenant per database application i must define IMultiTenat interface on entity if i want to use repositories.
I think this is not right. My entity doesn't have TenantID property. Why should ? Each tenant have its own database.
So there is no need to add TenantID field to database table.

Please advice how i can configure abp application as multitenancy (tenant per database) without adding  IMultiTenat to each
entity and each database table.

Thanks for advance.

Edvin

**Comment by sebitsi** [comment]
I found some related posts that explain that this behavior is by design:

#10876 
#9401 

I don't understand why it's done that way.

If I implement dbcontext inheritance, I'll have to check my and your source code every time I upgrade.
Have you any plan to implement multi-tenancy without using IMultiTenant interface ?

I think this would benefit many people, not just me.

**Comment by maliming** [comment]
hi

>? If i have multitenant per database application i must define IMultiTenat interface on entity if i want to use repositories.

This is design. but you can override the default implementation.

**Comment by sebitsi** [comment]
Hi @maliming.

I know i can override default implementation.
Do you have any plans to extend this behavior ? So "tenant per database without need extra TenantID property" ? 

What about inconsistent  GetDbContextAsync method behavior ?

**Comment by maliming** [comment]
> Repository<>.GetDbContextAsync method first check if entity is multitenant and if it is then change current tenant to null.
So ConnectionStringResolver return host's connection string.

Can you share the github URL of this behavior?

**Comment by sebitsi** [comment]
[DBContext provider - lines 81+](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Uow/EntityFrameworkCore/UnitOfWorkDbContextProvider.cs)
[Repository - lines 52+](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/EfCoreRepository.cs)

Okay. I'm only now seeing the point.
Provider is a lower level that does not know the concept of multitenancy. Repository does.
@maliming  Am I right ?

**Comment by maliming** [comment]
The `UnitOfWorkDbContextProvider` can't get `TEntity` info.
