### ISSUE TITLE
Hide tennant switching box on login in angular client

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#16366]
Hi. 

I have multitenat enabled application service.

Is it possible to lock (preset) tenantID in angular client ?
I mean i want to lock this client to "Tenant1". And of course tenant switching box should be hidden when
client try to login ?

I'm using ABP 7.0.1

Thanks for advance.

**Comment by realLiangshiwei** [comment]
Hi,

See: https://docs.abp.io/en/abp/latest/Multi-Tenancy#default-tenant-resolvers

You can remove the `CookieTenantResolveContributor` and `QueryStringTenantResolveContributor` from `AbpTenantResolveOptions`

**Comment by sebitsi** [comment]
@realLiangshiwei 

Hi. 
I have more than 1 angular application-client.

If i remove those contributors then all angular clients will work same. Right ?
I want to lock just one.

With lock i mean preset tenantid in just one angular client app and hide tenant switch box in login form.

**Comment by realLiangshiwei** [comment]
You can give it a try.

**Comment by sebitsi** [comment]
@realLiangshiwei I will. 

But still don't understand how this suggestion will solve my requirements. 
How will webapi service know which client has tenant switcher enabled and which not. 
An on client side which client has fixed tenantid and which not.

**Comment by realLiangshiwei** [comment]
You can read the document: https://docs.abp.io/en/abp/latest/Multi-Tenancy#determining-the-current-tenant
The docs explain how to determine the current tenant

And we have an example about the domain tenant resolver: https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver

**Comment by sebitsi** [comment]
@realLiangshiwei  Thanks for your suggestions.

It works as i need
