### ISSUE TITLE
When a domain event has multiple handlers, can you add the ability to set the execution order for the handlers?

### ISSUE THREAD

**Issue by choby** [abpframework/abp#16361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

When a domain event has multiple handlers, can you add the ability to set the execution order for the handlers?

**Comment by maliming** [comment]
You can call your `event handles` in order in one `event handle`.

Local event handles can have `order`, but it is difficult for the distributeds.

**Comment by gterdem** [comment]
Why do you need execution order for event handling? 

If you are using local event handlers:
**a-** Maybe you don't need multiple handlers since you want to do some sequencial process. So, you can do whatever needs to be done in the same handler.
**b-** You can use decorator pattern.

If you are using distributed event handlers, that's whole different story.

**Comment by hikalkan** [comment]
In ideal, you should not implement your logic that depends on execution order. If you have two handlers, then merge their logic as @gterdem states.

The only use case I can think can be adding a local event handler that throws an exception in a specific case. In that case, you may want to execute that event handler before all the others. Actually, that is a sign of a design error, but can be a workaround in some specific cases.

Here, the code part that triggers the handlers: https://github.com/abpframework/abp/blob/c8199a2582f9e5302047b9c4360174e30e2e62a2/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/EventBusBase.cs#L139-L145

@maliming can you check it can be easily done (do not implement if it complicates the implementation too much). For event handler classes, we may consider to define an attribute (like `EventHandlerOrderAttribute` with an integer `Order` property (used like `EventHandlerOrder(-10)`). If not defined, all handlers can have `0` as order. So, we can define a negative order to take our handler before others.

For distributed events, it is impossible to implement it.
