### ISSUE TITLE
Change Language Button Doesn't work on LeptonX Theme

### ISSUE THREAD

**Issue by ahmednfwela** [abpframework/abp#16376]
Original issue: https://github.com/abpframework/abp/issues/15893

The same problem is present in LeptonX theme for the mobile UI, but works for the desktop UI

Not working (mobile):
![image](https://user-images.githubusercontent.com/63286031/234475857-e493db8c-2133-4a9c-af48-7f16c54d01e7.png)

Working (desktop):
![image](https://user-images.githubusercontent.com/63286031/234476034-b2737024-f037-4fcb-b0f0-a5648c70cef2.png)

**Comment by realLiangshiwei** [comment]
We will fix the problem in the next patch version.
