### ISSUE TITLE
Abp Suite v7.2.0-rc.2 Throws Exception: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Lepton.Global'!

### ISSUE THREAD

**Issue by justinb9909** [abpframework/abp#16387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Abp suite v7.2.0-rc.2 throws the following exception:

> Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Lepton.Global'!

### Reproduction Steps

abp suite update --version 7.2.0-rc.2
abp suite

### Expected behavior

abp suite runs

### Actual behavior

abp suite throws exception and does not load

### Regression?

7.1.1 works

### Version

7.2.0-rc.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

Very similar to #16303

**Comment by EngincanV** [comment]
Thanks for reporting the problem. We will be working on it.

**Comment by yekalkan** [comment]
Issue is fixed, you need to re-install the suite.

`dotnet tool uninstall -g Volo.Abp.Suite`
`abp suite install --preview`
