### ISSUE TITLE
 Login button and Language dropdown (top right of the page) swap positions

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#16399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Home page displays the Language dropdown on the left and the Login link on the right, but when I click on the Login link, the Login is now displays to the left and the Language dropdown is now displayed on the right.

![image](https://user-images.githubusercontent.com/69393775/234905116-465010c8-2ecc-4d61-a53c-5591f66e8d63.png)

![image](https://user-images.githubusercontent.com/69393775/234905183-f65e9996-5065-4039-a53c-a3aedec71e52.png)

### Reproduction Steps

Create Blazor Server app using basic theme

Run app

### Expected behavior

Login and Language dropdown to stay in the same position 

### Actual behavior

The Login button and Language dropdown in the top right of the page swap positions

### Version

7.2.0 rc-2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by DonVliet** [comment]
@realLiangshiwei @maliming Thank You.

**Comment by erayfirat** [comment]
@realLiangshiwei @maliming  
I have same issue.
I get the blazor server project with basic theme a month ago.
Could you please control it again?
Is something is missed?
