### ISSUE TITLE
Npgsql EF error on GroupBy

### ISSUE THREAD

**Issue by andmattia** [abpframework/abp#16398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi

today we test on ABP.IO 7.1.0 with postgress our module and a group by select has an error about LEFT JOIN translated into LATERAL JOIN.

We solve moving Pg EF to 7.0.4

### Version

7.1.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

* Exception message and stack trace if available (check the logs).
* Steps needed to reproduce the problem.
