### ISSUE TITLE
How ABP framework design its folder structure when it comes to extending an existing module/feature with another module?

### ISSUE THREAD

**Issue by iyilm4z** [abpframework/abp#16408]
Sorry for creating a question issue here. 

Related stackoverflow question: https://stackoverflow.com/questions/76108940/how-abp-framework-design-its-folder-structure-when-it-comes-to-extending-an-exis

I want to know how Abp decides its framework folder structure when it comes to extending an existing module/feature with another module. Honestly, I have little confusion with it. Let me explain it with an example of ObjectExtending and Uow modules/features.

When extending the ObjectExtending Module with the AspNetCore Module, the extension codes are located under Volo/Abp/**ObjectExtending** folder. However, when extending the Uow Module with the AspNetCore Module, the extension codes are located under Volo/Abp/**AspNetCore/ObjectExtending** folder. 

Why both extension codes are not in the **AspNetCore** folder or not in their own folders(e.g. Volo/**Abp/ObjectExtending** and Volo/**Abp/Uow**)? 

What is the difference?

| ObjectExtending Module | Extending ObjectExtending Module with AspNetCore Module|
|------------------------|--------------------------------------------------------|
| [![enter image description here][1]][1] | [![enter image description here][2]][2] |

| Uow Module | Extending Uow Module with AspNetCore Module |
|------------|---------------------------------------------|
| [![enter image description here][3]][3] | [![enter image description here][4]][4] |

[1]: https://i.stack.imgur.com/sKszd.png
[2]: https://i.stack.imgur.com/mc4E2.png
[3]: https://i.stack.imgur.com/DfzqG.png
[4]: https://i.stack.imgur.com/jT7K9.png

**Comment by iyilm4z** [comment]
Sorry for directly mentioning you dear @maliming, but I really wonder about the purpose of this design. Do you have anything to say about my question?

**Comment by maliming** [comment]
hi @iyilm4z 

There is no strict roles on the folder structure.

You can set it to your liking. : )
