### ISSUE TITLE
Community posts pagination doesn't work

### ISSUE THREAD

**Issue by szilardd** [abpframework/abp#16401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Go to https://community.abp.io/ and scroll down to pagination. Click on any of the pages or the 'Next' button. It doesn't navigate to a different page

![image](https://user-images.githubusercontent.com/968502/234941372-cbb15734-88d2-4c44-876f-2918dfc713ca.png)

### Version

N/A

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by onurpicakci** [comment]
Thank you for reporting the problem. I have opened an internal issue related to this problem. We will fix it as soon as possible.

**Comment by onurpicakci** [comment]
Problem solved, see: https://community.abp.io/posts
