### ISSUE TITLE
Improve blog detail page

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#16415]
The detail page shows only the post content.
There should be navigation to the main blog page, other blog posts, info about the author etc...
I sketched a design based on [this post](https://blog.abp.io/abp/Speed-Up-Your-ASP.NET-Application).

- [x] _Yellow sections are added._

![image](https://user-images.githubusercontent.com/9526587/235103169-31a1c1f0-3345-4dc8-b13b-d2aa5dab98c0.png)

- [x] New optional features and edit profile section will be added on Member profile page 

 
<img width="1440" alt="Ekran Resmi 2023-05-04 09 57 32" src="https://user-images.githubusercontent.com/98148844/236132426-c7a28289-a427-49b1-a9af-705ff05171b3.png">

**Comment by ebicoglu** [comment]
related https://github.com/volosoft/vs-internal/issues/1168

**Comment by hikalkan** [comment]
We should discuss that. As @ebicoglu stated, we should migrate to CMS Kit blog. We don't want to invest on the old blogging module.
