### ISSUE TITLE
When there is a 500 error, The modal(Connection Strings) cannot be closed.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1641]
hi @mehmet-erim 

I found a small problem. if the connection string is not entered, Click Save to trigger the error. The modal(Connection Strings) cannot be closed.

![image](https://user-images.githubusercontent.com/6908465/63137558-58e2ad80-c009-11e9-87b2-5059cd95a729.png)

**Comment by hikalkan** [comment]
Select the "Use the Shared Database"?

**Comment by maliming** [comment]
As the picture shows. 

1. Deselect `Use the Shared Database`.
2. Do not enter the contents of the `Default Connection String`.
3. Click the Save button.

**Comment by hikalkan** [comment]
I mean when you deselect the shared database then you need to enter a connection string. That is the expected behavior. Am I wrong?

**Comment by maliming** [comment]
I know that I need to enter the connection string, I just found this small problem when testing the angular template.

It may need to verify the null input.

**Comment by hikalkan** [comment]
Oh, got it :) Sure, it must validate & handle it.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/1673
