### ISSUE TITLE
abp get community version with full sourceCode

### ISSUE THREAD

**Issue by amira133** [abpframework/abp#16438]
Hi
I am using `abp new Acme.BookStore -u angular -dbms PostgreSQL -m react-native --pwa -csf` to generate new project. But after generating project, But I can't see the complete source of the project. How can I get and edit the complete source of the project, such as the login page, etc.?

**Comment by maliming** [comment]
hi

You can clone the [abp](https://github.com/abpframework/abp) repo and using `  abp new Acme.BookStore --local-framework-ref --abp-path "D:\github\abp"`

**Comment by amira133** [comment]
without cloning abp, how can I modify `user` page or `login` page? for example I want to show more info in `user` page.

**Comment by realLiangshiwei** [comment]
You can check the document: https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-User-Interface

**Comment by amira133** [comment]
So how can I get source code of login page to replace it?

**Comment by realLiangshiwei** [comment]
You don't need to download the source code, **please check the document to know how to override the User Interface**
https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-User-Interface
