### ISSUE TITLE
How long to update the target framework "netstandard2.1" version?

### ISSUE THREAD

**Issue by vioKamran** [abpframework/abp#16430]
Please update this version target framework "netstandard2.1" as soon as possible because this new Microsoft version has more running speed and new class features.
Please replace or update all dll classes in source abp framwork .

**Comment by maliming** [comment]
I think we can use multiple targets, I will give it a try.

**Comment by vioKamran** [comment]
> I think we can use multiple targets, I will give it a try.

Very thankyou 😊🙏🌹
