### ISSUE TITLE
In MarkDown how to show "static void Main(string[] args)"

### ISSUE THREAD

**Issue by freebsensetips** [abpframework/abp#16469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In CmsKit Try to add new blog posts in detail 
When I add this in the code it shows
 
`static void Main(string[] args)`

```
<pre><code class="hljs language-csharp"><span class="hljs-function"><span class="hljs-keyword">static</span> <span class="hljs-keyword">void</span> <span class="hljs-title">Main</span>(<span class="hljs-params"><span class="hljs-built_in">string</span>
</span></span></code></pre>
```

### Expected behavior

static void Main(string[] args) 

### Version

7.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by enisn** [comment]
I've tried and couldn't reproduce.

## Editor

<img alt="image" src="https://user-images.githubusercontent.com/23705418/235840336-fde0fe45-8e8d-48c5-8574-33579735d6a2.png">

## Editor Preview

<img alt="image" src="https://user-images.githubusercontent.com/23705418/235840395-e10d9841-2a0e-41ee-975e-f374a5f4e2d5.png">


## Public Web

- After published:
<img alt="image" src="https://user-images.githubusercontent.com/23705418/235840208-3925be74-0aec-4e0a-9b20-535fff72b5c5.png">

---

Can you provide more information with the reproduction steps?

**Comment by freebsensetips** [comment]
Thanks for you response but still facing issue

**Editor View**

![image](https://user-images.githubusercontent.com/111872178/235857603-c474c3e6-ea1f-45d0-9d66-f4dedefc27c1.png)

**Editor Preview**

![image](https://user-images.githubusercontent.com/111872178/235857925-2ff47863-d88d-4a93-8651-7bb70d4cf237.png)

**Published View**

![image](https://user-images.githubusercontent.com/111872178/235858138-91da667c-725f-4355-a0fe-081a80e51d86.png)

**Comment by enisn** [comment]
1. Which theme are you using? _(Basic, LeptonX Lite, other?)_
2. Can you please check if dependencies are up to date in **package.json**
    - If not, update them to latest version and run `abp install-libs` command.

**Comment by freebsensetips** [comment]
Using a Basic Theme and added some of my customized code to the theme
Ok I will check but can you tell me which option i need to check in the package.json file ?

**Comment by freebsensetips** [comment]
my package.json file 
{
  "version": "1.0.0",
  "name": "my-app",
  "private": true,
  "dependencies": {
    "@abp/aspnetcore.mvc.ui.theme.basic": "~7.0.2",
    "@abp/aspnetcore.mvc.ui.theme.leptonxlite": "~2.0.2",
    "@abp/cms-kit": "~7.0.2"
  }
}

**Comment by JadynWong** [comment]
It may be related to [this](https://github.com/abpframework/abp/pull/15414/files).

You can upgrade to v7.1.0+ to solve this problem.
Or replace `ContentParser`, but since in v7.0.0, the `ContentParser.ParseContent` method is not virtual, you may need to do a lot of work.

**Comment by freebsensetips** [comment]
Thanks @JadynWong I will try and update

**Comment by freebsensetips** [comment]
Done
