### ISSUE TITLE
Tutorial Web Application Development: Nullable filter

### ISSUE THREAD

**Issue by RickFrontis** [abpframework/abp#16507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When following the ABP tutorial from Web Application Development, you will get the following error after chapter 9:
![image](https://user-images.githubusercontent.com/132918318/236846082-71bd1609-1381-4a29-9d1f-4bf09b77640d.png)

This is because in chapter 8 when creating the "GetAuthorListDto" class, the filter is not nullable and because of this it look likes ABP thinks the filter property is required. Because when changing "public string Filter {get; set;}" to "public string? Filter {get; set;}" it's fixed (notice the question mark after the string). 

I think the tutorial need's to be changed and by creating https://docs.abp.io/en/abp/latest/Tutorials/Part-8?UI=MVC&DB=EF#getauthorlistdto the string needs to be nullable.

### Reproduction Steps

1. follow the steps from https://docs.abp.io/en/abp/latest/Tutorials/Part-6?UI=MVC&DB=EF until chapter 9
2. After chapter 9 is done, have a look at your authors page, you will see you get the error.

### Expected behavior

After chapter 9 just showing the list of the seeded authors.

### Actual behavior

Showing a error

### Known Workarounds

Change the string to a nullable

### Version

7.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
You can try:

```csharp
public class GetAuthorListDto : PagedAndSortedResultRequestDto
{
    public string? Filter { get; set; }
}
```

**Comment by RickFrontis** [comment]
Jeah I know, this post was also intended more so that you know that there was a bug in the documentation. But thanks for the quick response and fix!
