### ISSUE TITLE
In which layer should I create SmsSender and CustomBlobProvider  ?

### ISSUE THREAD

**Issue by CaglarMacha** [abpframework/abp#16519]
We are using abp framework default template including application,application.contracts,domain,domain, shared,Entityframework,httpApi,HttpApiClient and HttpApi.Host as a layer. I would like to create SmsSender and CustomblobProvider but ı can not decide which layer I create my classes. Do you have any advice?

**Comment by maliming** [comment]
https://support.abp.io/QA/Questions/5035/In-which-layer-should-I-create-SmsSender-and-CustomBlobProvider
