### ISSUE TITLE
How to Mock Manager Class Which is inherited from Domain Service

### ISSUE THREAD

**Issue by manojkrsna** [abpframework/abp#16512]
**How to Mock the AuthenticationManager from below code which is inherited from Domain Service**

public class AuthenticationAppService_Tests
{
    private readonly AuthenticationAppService _sampleAppService;
    public AuthenticationAppService_Tests()
    {
    }
    [Fact]
    public void Get()
    {
        // Arrange
        var fakeRepo = Substitute.For AuthenticationManager ();
        fakeRepo.Login(string.Empty, string.Empty).Returns(Task.FromResult(
            Tuple.Create(new AuthResponseEntity(), new GSS.Models.UserInfoEntity())));
    }
}

**Comment by realLiangshiwei** [comment]
There is no `AuthenticationManager`.
Are you talking about the [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate)?

**Comment by manojkrsna** [comment]
I just gave AuthenticationManager as an example. it might be xManager how to mock it when it is injected in Appservice class


the line var fakeRepo = Substitute.For AuthenticationManager (); is throwing error

**Comment by realLiangshiwei** [comment]
You can check the document: https://docs.abp.io/en/abp/latest/Testing

**Comment by manojkrsna** [comment]
Yes i have gone through the same and  i couldn't any reference of how to mock manager class

**Comment by realLiangshiwei** [comment]
What's the error message?

BTW, You should mock the interface instead of class: https://nsubstitute.github.io/help/creating-a-substitute/

<img width="1085" alt="image" src="https://github.com/abpframework/abp/assets/16813853/1e6eb556-22ff-4e72-a7ed-27f71c064233">

**Comment by manojkrsna** [comment]
This will work ! but if i use IDomainService instead of DomainService. I might miss few  method definitions in Domain service. Please suggest that if i use IDomainService with interface for Manager am i deviating ABP framework and how to overcome of using those missed methods in Domain service?

**Comment by realLiangshiwei** [comment]
Try:

```csharp
[Fact]
public void Get()
{
    
    var testManager = Substitute.For<TestManager>(Substitute.For<IIdentityUserRepository>());

    testManager.Get().Returns(string.Empty);
}
public interface ITestManager : IDomainService
{
    string Get();
}

public class TestManager : DomainService, ITestManager
{
    private readonly IIdentityUserRepository _identityUserRepository;

    public TestManager(IIdentityUserRepository identityUserRepository)
    {
        _identityUserRepository = identityUserRepository;
    }

    public virtual string Get()
    {
        return string.Empty;
    }
}
```

This is not related to ABP but Nsubstitute, you can check its document: https://nsubstitute.github.io/
