### ISSUE TITLE
ISoftDelete filtering does not work for the entities created after upgrading to version 7.2.1 but it's still working with the old entities, eg: IdentityUser

### ISSUE THREAD

**Issue by kynt-lean** [abpframework/abp#16528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When deleting the new entities (implement the ISoftDelete) created in new abp 7.2.1 it successfully updates IsDeleted to true, but after that the get methods of EfCoreRepository are still getting IsDeleted records. But it is strange behavior because the old entities like IdentityUser are still filtering IsDeleted.

In my case, the class UtilityStandardPriceGroup already inherits FullAuditedAggregateRoot.

![IsDeleted records are not filter!](https://i.imgur.com/YYCot4s.png)

### Reproduction Steps

This is a minimal project describing an issue. Please change the connection string and apply the migrations, then run the project to see the problem.

[https://github.com/kynt-lean/wfk-rental](url)

### Expected behavior

The new entities implementing ISoftDelete are still applying abp built-in global filter if not explicitly disable it.

### Actual behavior

The new entities implementing ISoftDelete created with abp version 7.2.1 are not filtered by default.

### Version

7.2.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

**Comment by realLiangshiwei** [comment]
You should add `DbSet<>` property to the RentalDbContext class

**Comment by amirhosseinhosseinzadeh** [comment]
I write this in case developers face with same issue 
After upgrading my **Volo** packages to **7.3.3** , faced with exact same issue and after a couple of hours diagnostics found a solid way that can fix this problem.

the solution is so easy .just need to add this peace of code in your module
`Configure<DataFilterOptions>(opt => opt.DefaultStates[typeof(ISoftDelete)] = new DataFilterState(isEnabled: true));`
