### ISSUE TITLE
how can i change the OpenIddict AccessToken Lifetime for different client in apb

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#16529]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

when I update to abp7 and replace ID4 with OpenIddict ,I  also want to set the different token  lifetime for different client.
I noticed that the only way to set lifetime globally is through code and has no fields in the database.
what should I do？

**Comment by maliming** [comment]
Sets the access token lifetime associated with the claims identity or claims principal.

https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs#L3025-L3041

https://docs.abp.io/en/abp/latest/Authorization#claims-principal-factory

**Comment by xxvolvo** [comment]
> Sets the access token lifetime associated with the claims identity or claims principal.
> 
> https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs#L3025-L3041
> 
> https://docs.abp.io/en/abp/latest/Authorization#claims-principal-factory

thx, I got it.I will implement this function by myself now, and hope that ABP can release an out-of-the-box solution like the one in the ID4 module in the future

**Comment by xxvolvo** [comment]
> > Sets the access token lifetime associated with the claims identity or claims principal.
> > https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Abstractions/Primitives/OpenIddictExtensions.cs#L3025-L3041
> > https://docs.abp.io/en/abp/latest/Authorization#claims-principal-factory
> 
> thx, I got it.I will implement this function by myself now, and hope that ABP can release an out-of-the-box solution like the one in the ID4 module in the future

Sorry，we can set the lifetime with the` Claims Principal Factory` but I thinks we can not get the clientid in `AbpClaimsPrincipalContributorContext`

**Comment by maliming** [comment]
You can try to get request info by `HttpContext.GetOpenIddictServerRequest() `.

We will consider this in the next version.

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Modules/OpenIddict#updating-claims-in-access_token-and-id_token
