### ISSUE TITLE
OpenIdict ClientId not found

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#16539]
Hi!
I was investigating "unauthorized" information(!) logs for like 6 hours. Then I found out that the detailed information log (wouldn't it be warning?)  about it was "Client Id not found". I checked every where like db, cache .. Then i figured out that the reason was case sensitivity.  "Mrp_Web" instead of "MRP_Web" as a client id was the issue. I just opened this issue for people like me. But I also suggest that, should client_Id be case insensitive?

**Comment by ajebabli** [comment]
Hi I have the same issue.

**Comment by maliming** [comment]
> should client_Id be case insensitive?

**Unless otherwise noted, all the protocol parameter names and values are case sensitive.**

https://www.rfc-editor.org/rfc/rfc6749#section-1.9


And this is not abp related.

**Comment by gterdem** [comment]
We also have an issue about logging at https://github.com/openiddict/openiddict-core/issues/1672 if you are wondering why it is not logged as `warning`.

**Comment by muhlisatac** [comment]
Thanks for the explanations @maliming. Im totaly agree with you @gterdem. Min. log level was warning in my prod setup at first. That was also took me some hours.
