### ISSUE TITLE
How to Mock ObjectMapper.Map used in ABP Farmework for Unit testing

### ISSUE THREAD

**Issue by manojkrsna** [abpframework/abp#16531]
How to mock the below line for unit testing as it throws me error at this piece of code when writing test case for the method.
ObjectMapper.Map<src, dest>(srcData);

**Comment by realLiangshiwei** [comment]
You can check unit test code of ABP: https://github.com/abpframework/abp/blob/dev/framework/test/Volo.Abp.AutoMapper.Tests/Volo/Abp/AutoMapper/AbpAutoMapperModule_Basic_Tests.cs
