### ISSUE TITLE
DevArt .Skip(count).Take(count) Query Bug

### ISSUE THREAD

**Issue by zizoumurat** [abpframework/abp#16550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It produces incorrect output when I send skipcount and takecount values ​​the same

example : 

var dbQuery = (await GetDbSetAsync()).Skip(10).Take(10);

query result :

-- p__ef_filter__p_0='False'
-- p__p_0='10'
SELECT "r".ID, "r".ASSIGNEEROLE, "r".AVAILABILITY, "r".CODE, "r".CONCURRENCYSTAMP, "r".CREATIONTIME, "r".CREATORID, "r".DEFINITION, "r".DELETERID, "r".DELETIONTIME, "r".DOMAIN, "r".EXECORDER, "r".EXTRAPROPERTIES, "r".ISDELETED, "r".LASTJOBID, "r".LASTMODIFICATIONTIME, "r".LASTMODIFIERID, "r".REQUESTID, "r".SOURCETASKID, "r".STATE, "r".STATEOWNERID, "r".STATETIME, "r".SUMMARY, "r".TYPE
FROM RMS.RMS_TASKS "r"
WHERE :p__ef_filter__p_0 = 1 OR "r".ISDELETED = 0
OFFSET :p__p_0 ROWS FETCH NEXT **::p__p_0** ROWS ONLY

The bug is => ::p__p_0  ( must be an : )

### Version

7.2 (latest)

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

We can only upgrade the package when Devart releases the fix.

https://github.com/abpframework/abp/blob/748e1d5db63efe8870690c8a167723e47efc652c/framework/src/Volo.Abp.EntityFrameworkCore.Oracle.Devart/Volo.Abp.EntityFrameworkCore.Oracle.Devart.csproj#L22

**Comment by zizoumurat** [comment]
is there any progress? or what is your suggestion  @maliming

**Comment by maliming** [comment]
hi

You can add `<PackageReference Include="Devart.Data.Oracle.EFCore" Version="10.1.151.7" />` to check if it is resolved.

**Comment by zizoumurat** [comment]
hi


When I add the reference, I get the following errors, the query that gives an error is as follows

"Devart.Data.Oracle.OracleException (0x80004005): ORA-00920: invalid relational operator" 

Sql : 

SELECT "j".ID, "j".CONCURRENCYSTAMP, "j".CREATIONTIME, "j".EXTRAPROPERTIES, "j".ISABANDONED, "j".JOBARGS, "j".JOBNAME, "j".LASTTRYTIME, "j".NEXTTRYTIME, "j".PRIORITY, "j".TRYCOUNT
FROM ADMINISTRATION.JOB_BACKGROUNDJOBS "j"
WHERE NOT ("j".ISABANDONED) AND "j".NEXTTRYTIME <= :p__now_0
ORDER BY "j".PRIORITY DESC, "j".TRYCOUNT, "j".NEXTTRYTIME
FETCH FIRST :p__p_1 ROWS ONLY

**Comment by maliming** [comment]
hi

I don't think this is a problem with abp. Can you try your code without abp?

**Comment by zizoumurat** [comment]
hi,

this problem is solved.

But now,  I get an error  "NetTopologySuite spatial service is not registered. "  

Do you have an opinion on the subject?

**Comment by maliming** [comment]
You can create a new issue and describe it in detail.
