### ISSUE TITLE
abp-date-range-picker date-format not work in docker linux

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#16558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`abp-date-range-picker` and `abp-datepicker` display as `MM/DD/yyyy` and not work expected after set `data-format="yyyy/MM/DD"`

### Reproduction Steps

```csharp
public class IndexModel : HrmPageModel
{
    public void OnGet()
    {
    }

    [DataType(DataType.Date)]
    public DateTime? OfferDateFrom { get; set; } = new DateTime(2020, 1, 1);

    [DataType(DataType.Date)]
    public DateTime? OfferDateTo { get; set; } = DateTime.Today;
}
```

```csharp
<abp-date-range-picker id="OfferDate"
                                         asp-for-start="OfferDateFrom"
                                         asp-for-end="OfferDateTo"
                                         auto-update-input="true"
                                         suppress-label="true"
                                         clear-button="false"
                                         date-format="yyyy/MM/DD" />
```

### Expected behavior

Should display as `2020/01/01 - 2023/05/15`

![image](https://github.com/abpframework/abp/assets/24971860/08ee3863-5053-44ab-b558-c4434c55d8a3)

### Actual behavior

Actually display as `01/01/2020 - 05/15/2023` in docker linux.

![image](https://github.com/abpframework/abp/assets/24971860/6c97d5a3-522b-41fd-a151-ee3d3c921fe8)

### Version

V7.2.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

**Comment by salihozkara** [comment]
Hi @weiwxg ,

```cs
<abp-date-range-picker id="OfferDate"
                                         asp-for-start="OfferDateFrom"
                                         asp-for-end="OfferDateTo"
                                         auto-update-input="true"
                                         suppress-label="true"
                                         clear-button="false"
                                         date-format="YYYY/MM/DD" />
```

Can you try this way?
![image](https://github.com/abpframework/abp/assets/58659931/1fc370de-85da-45d0-ae9c-59bdcc0b6e3f)
