### ISSUE TITLE
Using central package management

### ISSUE THREAD

**Issue by JadynWong** [abpframework/abp#16559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management

> Starting with [NuGet 6.2](https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.2), you can centrally manage your dependencies in your projects with the addition of a Directory.Packages.props file and an MSBuild property.

### Describe the solution you'd like

abp currently uses `Directory.Build.props` to manage most nuget packages. 

I think we can improve the package management experience by using centralized package management. This also applies to templates, where developers can more easily check and manage all abp package versions.

**Comment by htve** [comment]
PR submitted, waiting for approval.  
cc: @JadynWong
