### ISSUE TITLE
Mini Enhancement: MIXED encoding for specific .csproj and some other files (.cs)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#16560]
I've noticed that some .csproj and .cs (maybe even .cshtml) files have mixed encoding and when such is clicked (opened) in VS in Windows, Visual Studio shows a prompt to set coding and line breaks.
I would understand that all files would be encoded in such way, but only a few are.
I haven't changed the default encoding and crlf/lf in Visual Studio settings for files.

I think that I noticed this pattern in all solutions (abp Commercial and open-source abp, modules).

Described behavior is not a bug in any meaning, but it would be nice to eliminate it.

**Comment by muhlisatac** [comment]
Nice point @leonkosak. It would be really good if there is a cli command for it.

**Comment by leonkosak** [comment]
I think that only CL and CRLF for line breaks are not consistent between all files (csproj, cs, cshtml,...) and different tab spaces (idents).

**Comment by maliming** [comment]
If there is a Github Action that can change the encoding and add a blank line to the end of the file would be better.

**Comment by leonkosak** [comment]
@maliming maybe this one?
https://github.com/marketplace/actions/newline-action

**Comment by NecatiMeral** [comment]
Maybe consider just to create an `.editorconfig` in the repository root.
This way you could configure line breaks for `*.csproj` and so on. VSCore and Visual Studio will support this change. I don't know about JetBrains.

By utilizing this way, you could use the `dotnet format` command to unify all source files in the repository according to your configuration.

A proposal would be [dotnet/sdk/.editorconfing](https://github.com/dotnet/sdk/blob/main/.editorconfig). This is the most comprehensive and standard configuration that I've found.

I'm willing to contribute a PR for this.
