### ISSUE TITLE
I am getting the following error when i try and install the Volo.Blogging Module on v0.19.0.0

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1656]
Cmd used 

`abp add-module Volo.Blogging -s Amazing.Solutions --sp src\Amazing.Solutions.Web\Amazing.Solutions.Web.csproj`

error received 

```
└─ @abp/blogging@0.8.0
Done in 3.48s.
[13:55:09 INF] gulp
[13:55:11] Using gulpfile ~\Documents\Amazing\Projects\Amazing.Solutions\src\Amazing.Solutions.Web\gulpfile.js
[13:55:11] Starting 'default'...
[13:55:13] Finished 'default' after 2.17 s
MSBUILD : error MSB1009: Project file does not exist.
Switch: src\Amazing.Solutions.Web\Amazing.Solutions.Web.csproj
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
MSBUILD : error MSB1009: Project file does not exist.
Switch: src\Amazing.Solutions.Web\Amazing.Solutions.Web.csproj
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.

C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Solutions>abp add-module Volo.Blogging -s Amazing.Solutions --sp src\Amazing.Solutions.Web\Amazing.Solutions.Web.csproj
```

**Comment by vnetonline** [comment]
@maliming I think there is something wrong with the -sp option 

if I specify the full path 

```bash
abp add-module Volo.Blogging -s Aamzing.Solutions -sp C:\Users\vbelani\Documents\Amazing\Projects\Amazing.Solutions\src\Amazing.Solutions.Web\Amazing.Solutions.Web.csproj
```
the result is a success 

```
└─ @abp/blogging@0.8.0
Done in 4.78s.
[15:02:18 INF] gulp
[15:02:20] Using gulpfile ~\Documents\Amazing\Projects\Amazing.Solutions\src\Amazing.Solutions.Web\gulpfile.js
[15:02:20] Starting 'default'...
[15:02:23] Finished 'default' after 2.65 s
Done. To undo this action, use 'ef migrations remove'
Applying migration '20190819050255_Added_Blogging_Module_31018'.
Done.
```

**Comment by vnetonline** [comment]
@maliming 

the example in the usage is wrong since you are in the Db Migrations project the relative path should be 

`abp add-module Volo.Blogging -s Amazing.Solutions -sp **..\Amazing.Solutions.Web\Amazing.Solutions.Web.csproj**`

not 

`abp add-module Volo.Blogging -s Amazing.Solutions -sp **src\Amazing.Solutions.Web\Amazing.Solutions.Web.csproj**`

if I knew how to do a pull request i would send the pull request to fix this.

**Comment by vnetonline** [comment]
@hikalkan I submitted a pull request with a simple change to the example in the usage info so show how to refer to the startup project relatively

**Comment by wakuflair** [comment]
Yeah I got the same error when I used `-sp` with a relative folder path.
And thanks to @vnetonline for the absolute path solution.

**Comment by vnetonline** [comment]
The example usage has been fixed in the following commit 

https://github.com/abpframework/abp/pull/1659/commits

will be included in the next release of abp.

always use the relative or the absolute path when specifying the -sp option when adding a module. because the add-migration and update-database commands are run in the EntityFrameworkCore.DbMigrations Project path
