### ISSUE TITLE
401 and 404 Issues occurs when on login page or after login

### ISSUE THREAD

**Issue by khalilsheikh** [abpframework/abp#16577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/abpframework/abp/assets/77208325/59a10b8d-1bc1-47c5-b39e-9d546fd393e6)

not able to get any error details in log or over the web page or in output window 
its becomes very hard to get to the issue framework shouldn't eat the errors details

### Reproduction Steps

any issue in ApplicationService or Contract doesn't get displayed but doesnt login 

### Expected behavior

should show up the error details over web page and in log

### Actual behavior

few a time its 404 error before login page
and few a times 401 error after success login 

### Regression?

no

### Known Workarounds

no workaround as of now, just re check all the work done and keep changing the code

### Version

7.0.2

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
**Reproduction Steps**

**Comment by khalilsheikh** [comment]
Reproduction Steps : any runtime issue while loading the entitles which doesn't load service

**Comment by khalilsheikh** [comment]
not log to know where and what's the issue

**Comment by khalilsheikh** [comment]
if there is no permission added but policy is added happen 404 error but no error details is shown

**Comment by realLiangshiwei** [comment]
Sorry, but I need the **full steps to reproduce the problem**. We are not sure what you are trying to say or request at the moment.
