### ISSUE TITLE
Replace default AbpController/Service DTOs instead of extending

### ISSUE THREAD

**Issue by trungdang97** [abpframework/abp#16593]
Hi,
I want to customize `ProfileAppService` and replace the default DTOs of my own (not extending, because I am currently implementing a module and want to use my own profile model and split them into another table and keep the default `AbpUsers` table clean).

I have read #3132 and related issues but have not found any clues that can help me replace the DTOs. 
The only guide on DTOs is Extending Entities on the docs. So the DTOs can only be extended and cannot be replaced?

I've tried disable the `Volo.Abp.Account.ProfileController` in `HttpApi` configuration using `IgnoredControllersOnModelExclusion` but it still works. Removing `[DependsOn]` `AbpAccountApplicationModule` and `AbpAccountApplicationContractsModule` doensn't work either.

Now I want to:
- Disable both  `Volo.Abp.Account.ProfileController` and `Volo.Abp.Account.ProfileAppService` so I can keep using the endpoint `api/account/my-profile`.
Or
- Be able to replace the default DTOs of the above ABP controller and service (which I will have to reimplement because I don't want to use `IProfileAppService` interface with the default DTOs).

What should I do to achieve the above?

**Comment by maliming** [comment]
hi

> Disable both Volo.Abp.Account.ProfileController and Volo.Abp.Account.ProfileAppService so I can keep using the endpoint api/account/my-profile.

This is reasonable, We can support it later.

The way is to remove the `ProfileController` from the asp net core `ApplicationModel` and add yours. 


https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-7.0

**Comment by trungdang97** [comment]
Thank you @maliming. It works perfectly.

**Comment by sherlockQcQ** [comment]
> 谢谢@maliming.它工作得很好。

hello ，I met the same question, can you share the solution? Thank you very much 🤖👻
