### ISSUE TITLE
Connect\token failed with status: 400

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#16597]
ABP Framework version 5.0
User Interface Angular
database provider EF Core

Hi 
we are facing an issue after login, app keeps reloading and calling connect\token which failes with status: 400 as below
![image](https://github.com/abpframework/abp/assets/78806436/9bf06d1b-c8c3-49a3-8c73-2f98c0578bc0)

it keeps refereshing page until we delete cookies, then it redirects to login page again.

Do you have any clue why this is happening?  

Regards,

**Comment by realLiangshiwei** [comment]
Please share the error logs.

**Comment by amLabib** [comment]
thanks for your reply, please find log file below

[logs.txt](https://github.com/abpframework/abp/files/11518532/logs.txt)

**Comment by leonkosak** [comment]
CORS request made for path: /api/abp/application-configuration from origin: http://localhost:4200 but was ignored because path was not for an allowed IdentityServer CORS endpoint

Maybe, this is an issue.
