### ISSUE TITLE
`abp-date-picker` cannot bind value

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#16603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I follow the [tutorials document](https://docs.abp.io/en/abp/latest/Tutorials/Part-3?UI=MVC&DB=EF) 

but when edit ,the `abp-date-picker` can not display value correctly

![image](https://github.com/abpframework/abp/assets/7838147/2b12ebac-6c14-4380-b026-704aacbcff48)

``` razor
<abp-dynamic-form abp-model="Book" asp-page="/Books/EditModal">
    <abp-modal>
        <abp-modal-header title="@L["Update"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-input asp-for="Id" />
            <abp-form-content />
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</abp-dynamic-form>
```

``` cs
    public class CreateUpdateBookDto
    {
        [Required]
        [StringLength(128)]
        public string Name { get; set; }

        [Required]
        public BookType Type { get; set; } = BookType.Undefined;

        [Required]
        [DataType(DataType.Date)]
        public DateTime PublishDate { get; set; } = DateTime.Now;

        [Required]
        public float Price { get; set; }
    }
```

### Reproduction Steps

I provider a demo repo. <https://github.com/xyfy/AbpLearn/tree/abp7>

### Expected behavior

display a correct value

### Actual behavior

none value show on UI

### Version

7.2.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

**Comment by onurpicakci** [comment]
Hi, I tested using your demo and the date you sent in the background is correct. The reason why it looks wrong here is that the data in the date picker is written in iso format. 

![Ekran Resmi 2023-05-23 08 13 07](https://github.com/abpframework/abp/assets/98148844/1c8b3a9d-f604-4642-bcf7-6cda90201d94)

![Ekran Resmi 2023-05-23 08 13 32](https://github.com/abpframework/abp/assets/98148844/8f6badd4-e71e-423f-88ee-5571b1920e29)

**Comment by xyfy** [comment]
How to resolve it?

**Comment by salihozkara** [comment]
@xyfy Hello, is your problem that the date itself is the lowest date even though you have given DateTime.Now?
I'll test it and get back to you.

**Comment by xyfy** [comment]
No，it is display error only ,using `<abp-form-content />` @salihozkara

**Comment by salihozkara** [comment]
Could you explain in more detail what is the behavior you expect but what is happening? @xyfy

**Comment by xyfy** [comment]
As I wrote at the beginning, it does not display the correct value in browser @salihozkara 

it got the value in html ,but can not show on screen.

**Comment by salihozkara** [comment]
Hi, can you try like here?
https://github.com/abpframework/abp/issues/16494#issuecomment-1537895132

`AutoUpdateInput` feature should provide this

**Comment by xyfy** [comment]
> Hi, can you try like here?
> https://github.com/abpframework/abp/issues/16494#issuecomment-1537895132
> 
> `AutoUpdateInput` feature should provide this

i don't know what to do with it，but  follow the document，if any condition will be required，can you change the documents？


https://docs.abp.io/en/abp/latest/Tutorials/Part-3?UI=MVC&DB=EF

**Comment by salihozkara** [comment]
Hi, this might be a bug, I'll look into it and get back to you. @xyfy

**Comment by salihozkara** [comment]
@xyfy https://github.com/abpframework/abp/pull/16651

**Comment by xyfy** [comment]
> @xyfy https://github.com/abpframework/abp/pull/16651

which version it should be coming？

**Comment by salihozkara** [comment]
> > @xyfy #16651
> 
> which version it should be coming？

Coming with 7.2 patch
