### ISSUE TITLE
SettingManagement module not worked properly.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#1661]
I successfully added SettingManagement module to my solution with ABP CLI(building and the db migration are also succeeded). 
But after login with admin account, no setting management menu entry occured, and I added `/SettingManagement` manually to the url, just a blank page showed:

![image](https://user-images.githubusercontent.com/3471718/63267128-f537d900-c2c3-11e9-9135-df023d48736b.png)

**Comment by yekalkan** [comment]
There is no setting to show. So it is hidden in top menu. 

Documentation for settings are not ready yet.

**Comment by wakuflair** [comment]
And the SettingManagement module is not ready to use?

**Comment by yekalkan** [comment]
It is ready and working well. But it is useless for now since there is no setting in any of our modules yet.

**Comment by wakuflair** [comment]
Can I use it to management my own settings?
I defined some settings in my `XXXSettingDefinitionProvider` and expected the SettingManagement can handle them

**Comment by yekalkan** [comment]
> Can I use it to management my own settings?

Yes.

> I defined some settings in my XXXSettingDefinitionProvider and expected the SettingManagement module can handle them.

It's not that easy of course. Please wait for documentation.

**Comment by wakuflair** [comment]
OK. Thank you for your replies.
