### ISSUE TITLE
Address Value Object is not updating when I call  var updatedEntity = await _repository.UpdateAsync(updateGuest, true);

### ISSUE THREAD

**Issue by zaktecs** [abpframework/abp#16613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi,
I'm having an issue with updating my record which is hindering my implementation of DDD in Abpframework. I'm using Guest object which OwnsOne Address. I'm able to add new address but when I use the following code to update the Guest and it's address the address part doesn't get updated. Can someone please help me solve this issue. Please my code below:

            var updateGuest = await _repository.GetAsync(request.Id, true);

            // Update the guest properties
            updateGuest.FirstName = request.FirstName;
            updateGuest.LastName = request.LastName;
            updateGuest.Email = request.Email;
            updateGuest.PhoneNumber = request.PhoneNumber;
            updateGuest.DateOfBirth = request.DateOfBirth;

            // Update the address properties
            updateGuest.Address.Street = request.Street;
            updateGuest.Address.City = request.City;
            updateGuest.Address.Country = request.Country;
            updateGuest.Address.ZipCode = request.ZipCode;

            var updatedEntity = await _repository.UpdateAsync(updateGuest, true);

            var updatedGuestDto = updatedEntity.Adapt<CreateUpdateGuestDto>();

            return updatedGuestDto;

### Reproduction Steps

Retreive single guest from database using the following

```csharp
 public async Task<Result<CreateUpdateGuestDto>> Handle(Query request, CancellationToken cancellationToken)
            {
              
                try
                {
                   var guest = await _guestRepository.GetAsync(request.Id);
                    var data = guest.Adapt<CreateUpdateGuestDto>();
                    if (data == null)
                    {
                        throw new EntityNotFoundException(typeof(Guest), request.Id);
                    }

                    return data;
                }
                catch (Exception e)
                {

                    return Result.Fail(e.Message);
                }

            }
```
Then when I'm updating The address which is a value object is not getting updated

### Expected behavior

The Guest inclusing Address should be updated

### Actual behavior

Guest is getting update but the address part is not updating

### Regression?

NO

### Version

7.2.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Try to include the navigation property.

https://docs.abp.io/en/abp/latest/Entity-Framework-Core#repository-withdetails

**Comment by zaktecs** [comment]
@realLiangshiwei thanks very much for your response and direction, but unfortunately I'm still not able to persist my changes to the database. per your commets above I'm already including the related object(Address). Reading the Abp the documentation this var **updateGuest = await _repository.GetAsync(request.Id, true);** includes withDetails by default when called.

When I'm updating guest I can see the changes in the address when stepping through the code but it doesn't persist when I call  var updatedEntity = await _repository.UpdateAsync(updateGuest, true);.  Please see attached image.

Many thanks

![AddressUpdate](https://github.com/abpframework/abp/assets/10104562/499dd79b-ab4c-4046-8168-2e51417d8392)

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem.

```csharp

public class Order : AggregateRoot<Guid>
{
    public string Name { get; set; }
    
    public Address Address { get; set; }
}

public class Address : ValueObject
{
    public string Description { get;  set; }
    public string Street { get;  set; }

    private Address()
    {
    }

    public Address(string street, string description)
    {
        Street = Check.NotNullOrEmpty(street, nameof(street));
        Description = description;
    }

    protected override IEnumerable<object> GetAtomicValues()
    {
        yield return Street;
        yield return Description;
    }
}

builder.Entity<Order>(b =>
{
    b.OwnsOne(x => x.Address, a=> a.WithOwner());
    b.ConfigureByConvention(); //auto configure for the base class props
    //...
});

public class OrderAppService : ApplicationService, ITransientDependency
{
    private readonly IRepository<Order> _orderRepository;

    public OrderAppService(IRepository<Order> orderRepository)
    {
        _orderRepository = orderRepository;
    }

    public async Task<Guid> CreateOrderAsync(string name)
    {
        var order = new Order
        {
            Name = name,
            Address = new Address("street", "description")
        };

        await _orderRepository.InsertAsync(order, true);
        return order.Id;
    }

    public async Task UpdateOrderAsync(Guid id, string street, string des)
    {
        var order = await _orderRepository.GetAsync(x=> x.Id == id);

        order.Address.Street = street;
        order.Address.Description = des;

        await _orderRepository.UpdateAsync(order);
    }
    
}
```

**Comment by zaktecs** [comment]
@realLiangshiwei Many thanks for your help. It is now working after adapting your code.

**Much appreciated**

Zak
