### ISSUE TITLE
Consider to enable nullable annotations for all projects

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#16610]
We enabled nullable for the [templates](https://github.com/abpframework/abp/issues/14856)
But the ABP framework is not enabled, and developers will mistakenly think that the return value is not null when using some APIs
For example, the cache may return null.

https://github.com/abpframework/abp/blob/101afac92b62a6d388eb3220df3fd4a7c0f689fa/framework/src/Volo.Abp.Caching/Volo/Abp/Caching/IDistributedCache.cs#L26-L40

Microsoft enabled nullable for their packages, we might consider doing the same:

* https://github.com/dotnet/runtime/issues/43605
* https://github.com/dotnet/aspnetcore/issues/5680

**Comment by realLiangshiwei** [comment]
## ABP Framework

### Group1
- [x] Volo.Abp.Core https://github.com/abpframework/abp/pull/16693
- [x] Volo.Abp.Data
- [x] Volo.Abp.Json
- [x] Volo.Abp.Json.Abstractions
- [x] Volo.Abp.Json.Newtonsoft
- [x] Volo.Abp.Json.SystemTextJson
- [x] Volo.Abp.Threading
- [x] Volo.Abp.Timing
- [x] Volo.Abp.Guids
- [x] Volo.Abp.UI
- [x] Volo.Abp.UI.Navigation
- [x] Volo.Abp.Validation
- [x] Volo.Abp.Validation.Abstractions
- [x] Volo.Abp.Castle.Core
- [x] Volo.Abp.Autofac
- [x] Volo.Abp.Autofac.WebAssembly
- [x] Volo.Abp.Localization
- [x] Volo.Abp.Localization.Abstractions
 - [x] Volo.Abp.Security
- [x] Volo.Abp.Uow
- [x] Volo.Abp.ApiVersioning.Abstractions
- [x] Volo.Abp.VirtualFileSystem
- [x] Volo.Abp.Settings
- [x] Volo.Abp.Serialization
- [x] Volo.Abp.Specifications
- [x] Volo.Abp.TestBase
- [x] Volo.Abp.ExceptionHandling
- [x] Volo.Abp.Ldap
- [x] Volo.Abp.Ldap.Abstractions
- [x] Volo.Abp.Minify
- [x] Volo.Abp.RemoteServices
- [x] Volo.Abp.MultiLingualObjects
- [x] Volo.Abp.Sms
- [x] Volo.Abp.Sms.Aliyun
- [x] Volo.Abp.ObjectExtending

### Group2 https://github.com/abpframework/abp/pull/17047
 - [x] Volo.Abp.AspNetCore.Authentication.JwtBearer
 - [x] Volo.Abp.AspNetCore.Authentication.OAuth
 - [x] Volo.Abp.AspNetCore.Authentication.OpenIdConnect

### Group3 https://github.com/abpframework/abp/pull/17062
 - [x] Volo.Abp.AspNetCore
 - [x] Volo.Abp.AspNetCore.Components
 - [x] Volo.Abp.AspNetCore.Components.MauiBlazor
 - [x] Volo.Abp.AspNetCore.Components.MauiBlazor.Theming
 - [x] Volo.Abp.AspNetCore.Components.Server
 - [x] Volo.Abp.AspNetCore.Components.Server.Theming
 - [x] Volo.Abp.AspNetCore.Components.Web
 - [x] Volo.Abp.AspNetCore.Components.Web.Theming
 - [x] Volo.Abp.AspNetCore.Components.WebAssembly
 - [x] Volo.Abp.AspNetCore.Components.WebAssembly.Theming

### Group4 https://github.com/abpframework/abp/pull/17074
 - [x] Volo.Abp.MultiTenancy.Abstractions
 - [x] Volo.Abp.MultiTenancy
 - [x] Volo.Abp.AspNetCore.MultiTenancy


### Group5 https://github.com/abpframework/abp/pull/17094
 - [x] Volo.Abp.AspNetCore.Mvc
 - [x] Volo.Abp.AspNetCore.Mvc.Client
 - [x] Volo.Abp.AspNetCore.Mvc.Client.Common
 - [x] Volo.Abp.AspNetCore.Mvc.Contracts
 - [x] Volo.Abp.AspNetCore.Mvc.NewtonsoftJson
 - [x] Volo.Abp.AspNetCore.Mvc.UI
 - [x] Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy
 - [x] Volo.Abp.AspNetCore.Mvc.UI.Bootstrap
 - [x] Volo.Abp.AspNetCore.Mvc.UI.Bundling
 - [x] Volo.Abp.AspNetCore.Mvc.UI.Bundling.Abstractions
 - [x] Volo.Abp.AspNetCore.Mvc.UI.Packages
 - [x] Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared
 - [x] Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Demo
 - [x] Volo.Abp.AspNetCore.Mvc.UI.Widgets

### Group6 https://github.com/abpframework/abp/pull/17096
 - [x] Volo.Abp.AspNetCore.Serilog
 - [x] Volo.Abp.AspNetCore.SignalR
 - [x] Volo.Abp.AspNetCore.TestBase

### Group7 https://github.com/abpframework/abp/pull/17108
 - [x] Volo.Abp.Auditing
 - [x] Volo.Abp.Auditing.Contracts
 - [x] Volo.Abp.Authorization
 - [x] Volo.Abp.Authorization.Abstractions
 - [x] Volo.Abp.AutoMapper
 - [x] Volo.Abp.ObjectMapping
 - [x] Volo.Abp.Features
 - [x] Volo.Abp.FluentValidation
 - [x] Volo.Abp.Gdpr.Abstractions
 - [x] Volo.Abp.GlobalFeatures
 - [x] Volo.Abp.Emailing
 - [x] Volo.Abp.MailKit
 - [x] Volo.Abp.Swashbuckle
 - [x] Volo.Abp.Cli

### Group8 https://github.com/abpframework/abp/pull/17109
 - [x] Volo.Abp.BackgroundJobs
 - [x] Volo.Abp.BackgroundJobs.Abstractions
 - [x] Volo.Abp.BackgroundJobs.HangFire
 - [x] Volo.Abp.BackgroundJobs.Quartz
 - [x] Volo.Abp.BackgroundJobs.RabbitMQ
 - [x] Volo.Abp.BackgroundWorkers
 - [x] Volo.Abp.BackgroundWorkers.Hangfire
 - [x] Volo.Abp.BackgroundWorkers.Quartz
 - [x] Volo.Abp.HangFire
 - [x] Volo.Abp.Quartz
 - [x] Volo.Abp.RabbitMQ
 - [x] Volo.Abp.AzureServiceBus

### Group9 https://github.com/abpframework/abp/pull/17120
 - [x] Volo.Abp.BlazoriseUI
 - [x] Volo.Abp.BlobStoring
 - [x] Volo.Abp.BlobStoring.Aliyun
 - [x] Volo.Abp.BlobStoring.Aws
 - [x] Volo.Abp.BlobStoring.Azure
 - [x] Volo.Abp.BlobStoring.FileSystem
 - [x] Volo.Abp.BlobStoring.Minio

### Group10
- [x] Volo.Abp.Caching https://github.com/abpframework/abp/pull/16661
- [x] Volo.Abp.Caching.StackExchangeRedis https://github.com/abpframework/abp/pull/16661

### Group11
- [x] Volo.Abp.Dapper
- [x] Volo.Abp.Dapr
- [x] Volo.Abp.Ddd.Application
- [x] Volo.Abp.Ddd.Application.Contracts
- [x] Volo.Abp.Ddd.Domain
- [x] Volo.Abp.Ddd.Domain.Shared
- [x] Volo.Abp.DistributedLocking
- [x] Volo.Abp.DistributedLocking.Abstractions
- [x] Volo.Abp.DistributedLocking.Dapr

###  Group12 https://github.com/abpframework/abp/pull/17549
- [x] Volo.Abp.MemoryDb
- [x] Volo.Abp.MongoDB
- [x] Volo.Abp.EntityFrameworkCore 
- [x] Volo.Abp.EntityFrameworkCore.MySQL
- [x] Volo.Abp.EntityFrameworkCore.Oracle
- [x] Volo.Abp.EntityFrameworkCore.Oracle.Devart
- [x] Volo.Abp.EntityFrameworkCore.PostgreSql
- [x] Volo.Abp.EntityFrameworkCore.Sqlite
- [x] Volo.Abp.EntityFrameworkCore.SqlServer

### Group13 https://github.com/abpframework/abp/pull/17557
- [x] Volo.Abp.Kafka
- [x] Volo.Abp.EventBus
- [x] Volo.Abp.EventBus.Abstractions
- [x] Volo.Abp.EventBus.Azure
- [x] Volo.Abp.EventBus.Dapr
- [x] Volo.Abp.EventBus.Kafka
- [x] Volo.Abp.EventBus.RabbitMQ
- [x] Volo.Abp.EventBus.Rebus
- [x] Volo.Abp.AspNetCore.Mvc.Dapr
- [x] Volo.Abp.AspNetCore.Mvc.Dapr.EventBus

### Group14 https://github.com/abpframework/abp/pull/17560
- [x] Volo.Abp.Http
- [x] Volo.Abp.Http.Abstractions
- [x] Volo.Abp.Http.Client
- [x] Volo.Abp.Http.Client.Dapr
- [x] Volo.Abp.Http.Client.IdentityModel
- [x] Volo.Abp.Http.Client.IdentityModel.MauiBlazor
- [x] Volo.Abp.Http.Client.IdentityModel.Web
- [x] Volo.Abp.Http.Client.IdentityModel.WebAssembly
- [x] Volo.Abp.Http.Client.Web
- [x] Volo.Abp.IdentityModel

### Group15 https://github.com/abpframework/abp/pull/17561
- [x] Volo.Abp.TextTemplating
- [x] Volo.Abp.TextTemplating.Core
- [x] Volo.Abp.TextTemplating.Razor
- [x] Volo.Abp.TextTemplating.Scriban
- [x] Volo.Abp.Imaging.Abstractions
- [x] Volo.Abp.Imaging.AspNetCore
- [x] Volo.Abp.Imaging.ImageSharp
- [x] Volo.Abp.Imaging.MagickNet
- [x] Volo.Abp.AspNetCore.Mvc.Dapr
- [x] Volo.Abp.AspNetCore.Mvc.Dapr.EventBus
- [x] Volo.Abp.Json

**Comment by hikalkan** [comment]
Thanks for your effort until now. I moved this issue to 8.0 to track it there. It will be good if we can finish all in 8.0.
