### ISSUE TITLE
Override OpenIdDict Log Levels

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#16629]
Hi

Normally i set the log level as warning in my prod environment. But i want to override it for OpenIdDict. Couse it logs errors as information. Edited the program.cs like below. But Im not sure if the "OpenIdDict" is the right source name. If its not can you help me to find the right name?

```
        Log.Logger = new LoggerConfiguration()
#if DEBUG
            .MinimumLevel.Debug()
#else
            .MinimumLevel.Warning()
#endif
            .MinimumLevel.Override("OpenIdDict", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.Async(c => c.File("Logs/logs.txt"))
            .WriteTo.Async(c => c.Console())
            .CreateLogger();
```

**Comment by maliming** [comment]
hi

https://github.com/openiddict/openiddict-core/issues/1691
