### ISSUE TITLE
Warning when generating a project using 0.18.1 from website....

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1662]
Hi,

This may have already been fixed in 0.19.0. If so what is the fix to make this warning go away?

![image](https://user-images.githubusercontent.com/4738140/63315626-417c2b00-c34f-11e9-8f62-d74fec080b8f.png)

**Comment by hikalkan** [comment]
Make it sync (not async). But don't care about it, this is just a test code. We made it async since if you really implement it to get data from a database, you will do it async.
