### ISSUE TITLE
Add appsettings.secrets.json to .gitignore in templates

### ISSUE THREAD

**Issue by maskalek** [abpframework/abp#16625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

At this moment, templates (checked application and microservice template) don't have `appsettings.secrets.json` in `.gitignore`. As a result, secrets are committed in the repo.

### Describe the solution you'd like

I believe we should not store any secrets in repositories. Could you please add `appsettings.secrets.json` into `.gitignore` by default for all templates?

### Additional context

Would be nice to know the context behind and why it is not by default like that.

**Comment by realLiangshiwei** [comment]
Hi,

This file is used for license codes for commercial templates.

ABP CLI dynamically creates the `appsettings.secrets.json` file; we can enhance the CLI to prevent this file from being generated for open-source templates.

**Comment by maskalek** [comment]
Hi, thank you for the response. Ok, you are right. It is generated automatically but it has even more sense to gitignore it. Dont you think so? Because I have the license and every time I start a new project this file goes directly into the repo that doesn't sound safe (even if my repos are private).

**Comment by realLiangshiwei** [comment]
Hi,

We won't add it to gitignore, when you work with a team, other developers can't even run the project without it.

**Comment by realLiangshiwei** [comment]
After my check, this is by design, even for open-source templates.

**Comment by maskalek** [comment]
> Hi,
> 
> We won't add it to gitignore, when you work with a team, other developers can't even run the project without it.

yes, that is clear. Don't you think every developer should generate it by themselves or share via some password keepers?
Without other secrets(passwords, connections string, etc) you also can't run the project , but we still don't want to commit anything to the repo and have it in user secrets instead.

btw your main repo ignores this file https://github.com/abpframework/abp/blob/dev/.gitignore. Interesting that you don't want to have it in template by default
