### ISSUE TITLE
Angular app cannot start

### ISSUE THREAD

**Issue by xnzhwd** [abpframework/abp#16633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi
Two errors occur when start the angular app.

`
./node_modules/@angular/common/fesm2020/common.mjs:2987:10-29 - Error: export 'ɵisListLikeIterable' (imported as 'ɵisListLikeIterable') was not found in '@angular/core'
`
`./node_modules/@angular/router/fesm2020/router.mjs:2789:20-33 - Error: export 'ɵisStandalone' (imported as 'ɵisStandalone') was not found in '@angular/core' 
`

How to fix these?

### Reproduction Steps

1 Create abp 
`abp new Acme.BookStore -u angular -dbms PostgreSQL -csf`
2 npm install
3 npm run start

### Version

7.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by mahmut-gundogdu** [comment]
I couldn't produce the issue totally. It will works on my machine. 
<img width="1696" alt="image" src="https://github.com/abpframework/abp/assets/2217899/9bac36df-b108-4686-994b-f8fdbe47a723">

but I or my teammate will investigate the issue back but. You can try with `yarn`
could you try wity `yarn install`

**Comment by xnzhwd** [comment]
> 
Thank you！
It works  when I remove node_modules and install via `yarn intall`

**Comment by ebicoglu** [comment]
@gizemmutukurt will test this with `NPM install`

1. `abp new Acme.BookStore -u angular -dbms PostgreSQL -csf -t app --skip-installing-libs`
2. run `npm install` in the Angular
3. run the Host project
4. `npm run start` in the Angular

**Comment by mahmut-gundogdu** [comment]
It might be related https://github.com/abpframework/abp/issues/16652

**Comment by masum-ulu** [comment]
This issue is not related with #16652 directly
 - It seems like cache problem
 
This issue is not stable bug, that's why I'm closing, it again occur I'll reopen

After **7.2.patch** release 
 - `abp new Acme.BookStore -u angular -dbms PostgreSQL -csf -t app --skip-installing-libs` this command's will run successfully.
