### ISSUE TITLE
Angular can't install with npm

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#16652]
**Command:** `abp new Acme.BookStore -u angular -dbms PostgreSQL -csf -t app --skip-installing-libs`
The downloaded project lepton version is incorrect and an error is received when running the angular project.
![image](https://github.com/abpframework/abp/assets/99716457/b9eec831-76a3-4b5d-aeb0-46131def5e8d)
![image](https://github.com/abpframework/abp/assets/99716457/4d1af5d6-8c6d-4020-9d6c-ebb011190a02)

**Comment by Anurag1008** [comment]
can I work on this issue?

**Comment by masum-ulu** [comment]
Hi @Anurag1008 thank you for your request but this issue also related with commercial side that's why I need to fix that

**Comment by Anurag1008** [comment]
If in future you need someone to work on this issue. feel free to mention me .I will love to work with you. thankyou for your early response.

**Comment by masum-ulu** [comment]
It was related with lepton-x theme now it's fine
When I try to run 
`abp new Acme.BookStore -u angular -dbms PostgreSQL -csf -t app --skip-installing-libs`  command it's throw error below.

![image](https://github.com/abpframework/abp/assets/49063256/51a63bc3-6a94-478b-9bfa-ca51e9a0c34e)

This issue fixed at https://github.com/abpframework/abp/pull/16669

### Workaround
- Use yarn or edit package.json like below and run `npm install`
 
![image](https://github.com/abpframework/abp/assets/49063256/b3d9cd4b-767b-407c-9f43-80df3fb3ab10)
