### ISSUE TITLE
scopes and roles/permissions

### ISSUE THREAD

**Issue by alihdev** [abpframework/abp#16656]
If we have two clients accessing the same API, the first client being an admin and the second client being mobile users only, how can we set (roles/permissions) based on their scopes?

The scope_admin should have permissions 1, 2, 3, and 4 by default, while the scope_mobile should have permissions 1 and 4.

We have already created two scopes for the same API. However, both scope_1 and scope_2 have the same (roles/permissions). How can we associate each scope with specific (roles/permissions)?

We want users who use the mobile app to have access to specific resources based on their scope.

**Comment by berkansasmaz** [comment]
Hello, you can use `scope permissions` for this. See [here](https://documentation.openiddict.com/configuration/application-permissions.html#scope-permissions) for more information.

**Comment by alihdev** [comment]
Hello, thank you.
where can we manage that in abp?
in **OpenIddictDataSeedContributor** class?

```c#
           ...
            if (permissions != null)
            {
                await _permissionDataSeeder.SeedAsync(
                    ClientPermissionValueProvider.ProviderName,
                    name,
                    permissions,
                    null
                );
            }

            await _applicationManager.CreateAsync(application);
```

what about **Application.Contracts** permissions, How can we associate with specific scope ?

**Comment by berkansasmaz** [comment]
I'm starting to think you're implementing a wrong design from your question, please correct me if I'm wrong. According to best practices;

> Every application will have different requirements, different use cases (Application Service methods), different DTOs, different validation and authorization rules... etc.

> Mixing all these logics into a single application layer makes your services contain too many if conditions with complicated business logic makes your code harder to develop, maintain and test and leads to potential bugs.

![domain-driven-design-multiple-applications](https://github.com/abpframework/abp/assets/31216880/9aecea2f-f793-4f90-9d16-316f9c79a942)


For more information: https://docs.abp.io/en/abp/4.0/Domain-Driven-Design-Implementation-Guide#multiple-application-layers

**Comment by alihdev** [comment]
My idea was in a single layer.
Ok, great solution. If we add these layers, should we add them manually or is there a CLI command to add the host and application? a simple way to add these layers?

**Comment by berkansasmaz** [comment]
There is no direct ABP CLI command for this, but you can do it very easily with any IDE. Then you can create the same code from the current layer by copying it. Secondly, you can create a new startup template with the ABP CLI with a name suitable for you and copy the relevant projects.

**Comment by alihdev** [comment]
Thank u.
