### ISSUE TITLE
FreeSql integration as EF Core independent

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#1665]
There is a repository called FreeSql, i didn't try it. Yet repository's readme file has a performance record. It may be useful, i am just noting here 

Repo : https://github.com/2881099/FreeSql

**Comment by hikalkan** [comment]
Thanks.

**Comment by hikalkan** [comment]
Thanks. It is hard for us to integrate to every ORM :) If anyone want to use it with ABP, they can directly use it.
Any PR would be appreciated, but I don't think that we work on this in a reasonable time.

**Comment by hikalkan** [comment]
BTW, ABP already has Dapper integration if you want to check it: https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Dapper (not documented yet)

**Comment by ugurozturk** [comment]
@hikalkan Hi, so https://github.com/abpframework/abp/issues/1303 issue should close or this is a different purpose ?

**Comment by fawdlstty** [comment]
why stop planning? :cry:

**Comment by pengcong001** [comment]
freesql is the best ORM I have ever used
