### ISSUE TITLE
Bug Saving profile picture

### ISSUE THREAD

**Issue by MathiasKowoll** [abpframework/abp#16666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to upload a profile a profile image it fails.

### Reproduction Steps

log into application,
choose a file to upload
click save

### Expected behavior

save the profile picture

### Actual behavior

give a en error

### Known Workarounds

Change var UPPY_UPLOAD_ENDPOINT = "api/account/profile-picture" to "/api/account/profile-picture" in file Pages/Account/Components/ProfileManagement/Group/ProfilePicture/Default.js

You can recreate this folder structure and pasted the javascript code from original and change UPPY_UPLOAD_ENDPOINT to the correct api endpoint.

### Version

7.2.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

macOS

**Comment by berkansasmaz** [comment]
Thanks for the report @MathiasKowoll 🎉

I will test and if exist any problem I will fix this ASAP.

**Note:** Please use [commercial support website](https://support.abp.io/) for your ABP Commercial questions/issues.

**Comment by EngincanV** [comment]
This problem has been fixed (in our private repo) and will be included in the next version.

![image](https://github.com/abpframework/abp/assets/43685404/a56fd921-74ca-42a4-a2db-f5f6e82dba66)

---

The quick workaround is changing the `UPPY_UPLOAD_ENDPOINT` variable value as **/api/account/profile-picture** (under */Pages/Account/Components/ProfileManagement/Group/ProfilePicture/Default.js* file) as you stated.
