### ISSUE TITLE
AccountController from Account Web module can't find by Email

### ISSUE THREAD

**Issue by cerezojd** [abpframework/abp#1667]
If you do a request with your account email, the result is: 

```
{
  "result": 2,
  "description": "InvalidUserNameOrPassword"
}
```
I think this is because `singInManager.PasswordSignInAsync()` only searches a user by name, not by email. The same with `_userManager.FindByNameAsync()`

**Comment by maliming** [comment]
@hikalkan 
Do we need to add the `FindByNameOrEmailAsync` method to the `IdentityUserManager`?
This way we can pass the user to the `singInManager` method.

Or replace Dto's `Email` as `UserName` like account pro.

**Comment by hikalkan** [comment]
I can login by email. So, could not reproduce the problem.

@maliming if you check the Login page code, you will see that PostAsync method has a call to ReplaceEmailToUsernameOfInputIfNeeds method (https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L91).

It changes email to username. See: https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L213-L233

So, I see no problem.

**Comment by maliming** [comment]
see:
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/account/src/Volo.Abp.Account.Web/Areas/Account/Controllers/AccountController.cs#L32-L51
