### ISSUE TITLE
the permission ui error in administration

### ISSUE THREAD

**Issue by davidnasar** [abpframework/abp#16687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Screenshot 2023-05-27 235010](https://github.com/abpframework/abp/assets/6254752/37b83037-86ad-4e03-bcb8-9f53753d58d4)
As the screenshot shows, the ui has some additional html element behind, should be deleted.

### Reproduction Steps

1. ABP CLI 7.2.2
    .Net SDK 7.0.302
    win10-x64
    chrome
3. create project using this command: abp new MySite -u mvc -d ef
4. run the DbMigrator first, then run Web
5. login as admin

### Version

7.2.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/16677
