### ISSUE TITLE
Error performing password flow TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by indexlang** [abpframework/abp#1669]
when I run the Template angular  project 0.19, I got a error:
`Error performing password flow TypeError: Cannot read property 'toLowerCase' of null
    at HttpXsrfInterceptor.intercept (http.js:2731)
    at HttpInterceptorHandler.handle (http.js:1910)
    at HttpInterceptingHandler.handle (http.js:2808)
    at MergeMapSubscriber.project (http.js:1637)
    at MergeMapSubscriber._tryNext (mergeMap.js:46)
    at MergeMapSubscriber._next (mergeMap.js:36)
    at MergeMapSubscriber.next (Subscriber.js:49)
    at Observable._subscribe (scalar.js:4)
    at Observable._trySubscribe (Observable.js:42)
    at Observable.subscribe (Observable.js:28)
(anonymous) @ angular-oauth2-oidc.js:1276
__tryOrUnsub @ Subscriber.js:185
error @ Subscriber.js:137
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_tryNext @ mergeMap.js:49
_next @ mergeMap.js:36
next @ Subscriber.js:49
(anonymous) @ scalar.js:4
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:21
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
(anonymous) @ angular-oauth2-oidc.js:1262
ZoneAwarePromise @ zone-evergreen.js:876
fetchTokenUsingPasswordFlow @ angular-oauth2-oidc.js:1225
onSubmit @ abp-ng.account.js:51
(anonymous) @ LoginComponent.html:7
handleEvent @ core.js:43992
callWithDebugContext @ core.js:45631
debugHandleEvent @ core.js:45246
dispatchEvent @ core.js:29803
(anonymous) @ core.js:31836
schedulerFn @ core.js:35378
__tryOrUnsub @ Subscriber.js:185
next @ Subscriber.js:124
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35297
onSubmit @ forms.js:7398
(anonymous) @ LoginComponent.html:7
handleEvent @ core.js:43992
callWithDebugContext @ core.js:45631
debugHandleEvent @ core.js:45246
dispatchEvent @ core.js:29803
(anonymous) @ core.js:42924
(anonymous) @ platform-browser.js:2668
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:39679
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1640
Show 23 more frames
`

**Comment by indexlang** [comment]
I do nothing but re download an new project,the problem disappear.

**Comment by lyling** [comment]
i get the same problem. and i get the code today.
