### ISSUE TITLE
ABP Tag Helper Library

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#167]
We need a tag helper library for ASP.NET Core MVC

### Specs

- Based on Bootstrap 4 (BS4)
- 100% Compatible with BS4.
- It will have some improvements on BS4.
- It will have some additional features those are not in BS4.
- It will be well-integrated to the ABP framework.
- It will be overridable (especially, by premium themes).

### High Priority Features

- [x] Button
- [x] Card
- [x] Label (Nothing to implement?)
- [x] Rows & Cols (Grid System)
- [x] Tab
- [x] Form items (see https://github.com/volosoft/abp/issues/172)
- [x] Radio buttons
- [x] Dropdown button
- [x] Alert
- [x] Badges
- [x] Modal
- [x] Collapse
- [x] Tooltip
- [x] Popover
- [x] Progress http://getbootstrap.com/docs/4.1/components/progress/
- [x] Breadcrumb http://getbootstrap.com/docs/4.1/components/breadcrumb/
- [x] Blockquote http://getbootstrap.com/docs/4.1/content/typography/#blockquotes (automatically add blockquote class)
- [x] Image: http://getbootstrap.com/docs/4.1/content/images/
- [x] Figure http://getbootstrap.com/docs/4.1/content/figures/
- [x] Carousel http://getbootstrap.com/docs/4.1/components/carousel/
- [x] List group http://getbootstrap.com/docs/4.1/components/list-group/
- [x] Table http://getbootstrap.com/docs/4.1/content/tables/
- [x] Nav & Navbar

**Comment by bbakermmc** [comment]
@hikalkan Where is this class at?  And is it currently override-able?

**Comment by acjh** [comment]
Folder: [**abp**/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/](
https://github.com/volosoft/abp/tree/master/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers)
Demo: http://bootstrap-taghelpers.abp.io/

**Comment by hikalkan** [comment]
For override, you can derive from a service class and replace it in the dependency injection. Example service class: [AbpButtonTagHelperService](https://github.com/volosoft/abp/blob/master/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Button/AbpButtonTagHelperService.cs)
