### ISSUE TITLE
How to Disable default Module Api

### ISSUE THREAD

**Issue by sherlockQcQ** [abpframework/abp#16704]
how to disable default module api ,for example:'api/identity/users' ,**I hope he is banned from accessing (404) instead of hiding it in 'swagger' page。**
 
i serach document ,(https://docs.abp.io/zh-Hans/abp/latest/Customizing-Application-Modules-Overriding-Services)
i use Code :
![image](https://github.com/abpframework/abp/assets/61469754/87f9a10b-ad21-43fc-81ba-6c15368ad0aa)

I want to generate a set of routing paths that I control
![image](https://github.com/abpframework/abp/assets/61469754/6e09355a-0934-4aec-b468-a38130debbbe)

this is maybe ok , but I hope he is banned from accessing (404)(for example :'api/Identity/users' )

or replace Controller ?

**Comment by realLiangshiwei** [comment]
You can check this: https://github.com/abpframework/abp/issues/16593

**Comment by sherlockQcQ** [comment]
> 你可以检查这个：#16593

abp not have a shortcut configuration for this feature？i see this link ,I have tried some of the methods provided. But he only prohibits generation on the Controller layer, but I can still access it by using Api tool calls, not 404

**Comment by realLiangshiwei** [comment]
This document has introduced how to do it: https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-7.0#modify-the-applicationmodel

Try:

```csharp
public class ApplicationDescription : IApplicationModelConvention
{

    public ApplicationDescription()
    {
    }

    public void Apply(ApplicationModel application)
    {
        application.Controllers.RemoveAll(x=>x.ControllerType == typeof(IdentityUserController));

    }
}

Configure<MvcOptions>(options =>
{
    options.Conventions.Add(new ApplicationDescription());
});
```

**Comment by sherlockQcQ** [comment]
thks，👻🎉
