### ISSUE TITLE
TenantId is not automatically set when creating IMayHaveTenant object

### ISSUE THREAD

**Issue by 792702675** [abpframework/abp#16703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

protected virtual void CheckAndSetMayHaveTenantIdProperty(object entityAsObj)
        {
            if (SuppressAutoSetTenantId)
            {
                return;
            }

            //Only works for single tenant applications
            if (MultiTenancyConfig?.IsEnabled ?? false)
            {
                return;
            }

### Known Workarounds

protected virtual void CheckAndSetMayHaveTenantIdProperty(object entityAsObj)
        {
            if (SuppressAutoSetTenantId)
            {
                return;
            }

            //Only works for single tenant applications
            if (!(MultiTenancyConfig?.IsEnabled ?? false))
            {
                return;
            }

### Version

8.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi,

I guess you are talking about [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate).
please open an issue on aspnetboilerplate
