### ISSUE TITLE
How to use [Authorize] DataAnnotations?

### ISSUE THREAD

**Issue by SaeedSpate** [abpframework/abp#1670]
Hi,
I'm using [Authoriz(Permissions.MyAppPermissions.{$Some permissions})] in top of AppService class, but not work!

```csharp
namespace TH.Customers
{
    [Authorize(Permissions.THPermissions.Customers.Default)]
    public class CustomersAppService : CrudAppService<Customers, CustomersDto, Guid, PagedAndSortedResultRequestDto, CreateUpdateCustomersDto, CreateUpdateCustomersDto>, ICustomersService
    {
        public CustomersAppService(IRepository<Customers, Guid> repository) : base(repository)
        {
        }

        [Authorize(Permissions.THPermissions.Customers.Create)]
        public override Task<CustomersDto> CreateAsync(CreateUpdateCustomersDto input)
        {
            return base.CreateAsync(input);
        }
    }
}
```

Is it right?

**Comment by hikalkan** [comment]
Yes, this should work. What happens? Does it ignore the authorization or you are getting exception?

**Comment by SaeedSpate** [comment]
Authorization is ignored and result status is OK(200) and also i receive login form!
I not receive status code 401

**Comment by hikalkan** [comment]
I suppose it is redirected to the login form on an unauthorized request. Will check this.

**Comment by SaeedSpate** [comment]
@hikalkan 
I resolved temporary by removed `typeof(AbpAspNetCoreMvcUiBasicThemeModule)` from `MyAppHttpApiHostModule.cs` and add this code to the startup.cs:

```
app.UseExceptionHandler(appBuilder =>
{
	appBuilder.Use(async (context, next) =>
	{
		var error = context.Features[typeof(IExceptionHandlerFeature)] as IExceptionHandlerFeature;
		if (error?.Error is SecurityTokenExpiredException)
		{
			context.Response.StatusCode = 401;
			context.Response.ContentType = "application/json";
			await context.Response.WriteAsync(JsonConvert.SerializeObject(new
			{
				Message = "authentication token expired"
			}));
		}
		else if (error?.Error != null)
		{
			if(error.Error.Message.Equals("No theme registered! Use ThemingOptions to register themes."))
			{
				context.Response.StatusCode = 401;
			}
		}
		else
		{
			await next();
		}
	});
});
```

**Comment by hikalkan** [comment]
I tried this with the startup template. I run the API host project and trying to execute the URL: `https://localhost:44305/api/identity/users/`

The result is:

![image](https://user-images.githubusercontent.com/1210527/65323764-ed18d500-dbb2-11e9-855b-38016fba480c.png)

So, it seems normal, getting 401.

How can I repeat this?

**Comment by SaeedSpate** [comment]
@hikalkan If you'r tried call api from custom service, you'll see `Login page` instead `401`!

**Comment by hikalkan** [comment]
If you were requesting with ABP's dynamic c# proxies, I will fix it.

**Comment by gdlcf88** [comment]
> Authorization is ignored and result status is OK(200) and also i receive login form!
> I not receive status code 401

See: https://github.com/abpframework/abp/issues/845
