### ISSUE TITLE
Microservice timeout after 100 sec

### ISSUE THREAD

**Issue by chai93323** [abpframework/abp#1671]
MicroService Timeout after long running task. (over 100 second)
System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()

Is there any setting to extend the timeout?

**Comment by hikalkan** [comment]
Can you write more details, so we can exactly know where to introduce an option for it.

**Comment by cnfanhua** [comment]
Abp Version: vNext 2.9.0
.Net Core: 3.1.103

I have the same problem.
The API is always pending and then it will time out.

![2020-06-09 16-12-39屏幕截图](https://user-images.githubusercontent.com/12975837/84124196-763ba900-aa6d-11ea-8dfd-2dcd958b396c.png)

**Comment by cnfanhua** [comment]
The problem is solved.
The reason is that redis is not installed.
It's a bug?

**Comment by liangshiw** [comment]
@cnfanhua 
No, the applications use Redis as as distributed cache. So, you need to have Redis installed & running.

**Comment by cnfanhua** [comment]
@liangshiw thanks.
