### ISSUE TITLE
Add-Migration <PrivateAssets>

### ISSUE THREAD

**Issue by Elencon** [abpframework/abp#16716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using ABP version 7.2.2
I played with ABP Blazor-Server. Created project, executed DbMigrator everything works.
I Added DbSet properties and mapping code . Run  Add-Migration cmd in PN and get error
Your startup project 'cc.Blazor' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
I found solution here: 
https://stackoverflow.com/questions/52536588/your-startup-project-doesnt-reference-microsoft-entityframeworkcore-design
Simply erased :      <PrivateAssets>all</PrivateAssets>	
.EntityFrameworkCore.csproj
Can it be made in advance in template in order to make process smoother

### Reproduction Steps

Created project, executed DbMigrator everything works.
I Added DbSet properties and mapping code . Run  Add-Migration cmd in PN and get error

### Expected behavior

No error

### Actual behavior

Your startup project 'cc.Blazor' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

### Known Workarounds

I found solution here: 
https://stackoverflow.com/questions/52536588/your-startup-project-doesnt-reference-microsoft-entityframeworkcore-design
Simply erased :      <PrivateAssets>all</PrivateAssets>	
.EntityFrameworkCore.csproj

### Version

7.2.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
See: https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=MVC&DB=EF#add-database-migration

You should run the command in the `.EntityFrameworkCore` project instead of `.Migrator`
