### ISSUE TITLE
We do not want to use the API's other than POST and Get

### ISSUE THREAD

**Issue by pmjaleel** [abpframework/abp#16713]
Hi ABP Team,

We have a criteria where we cannot use API's other than POST and Get (Restricted in certain scenarios). This is an infosec standard followed by our firm. 

How can we override this and change the Verb of Put, Delete etc.

Your valuable guidance is appreciated

**Comment by realmingliang** [comment]
Override the SelectHttpMethod method of the AbpServiceConvention class

**Comment by realmingliang** [comment]
![image](https://github.com/abpframework/abp/assets/44856409/8864bd04-1228-4b7a-b868-2105515ca1de)
![image](https://github.com/abpframework/abp/assets/44856409/5aadf3a4-7368-493a-aae9-8eff356f588e)

**Comment by zhaofenglee** [comment]
`````
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAbpServiceConvention))]
public class MyServiceConvention:  AbpServiceConvention, ITransientDependency
{
    public MyServiceConvention(
        IOptions<AbpAspNetCoreMvcOptions> options,
        IConventionalRouteBuilder conventionalRouteBuilder)
        : base(options, conventionalRouteBuilder)
    {
    }
    
    
    protected override string SelectHttpMethod(ActionModel action, ConventionalControllerSetting configuration)
    {
        return GetConventionalVerbForMethodName(action.ActionName);
    }
    
    public const string DefaultHttpVerb = "POST";

    public static Dictionary<string, string[]> ConventionalPrefixes { get; set; } = new Dictionary<string, string[]>
    {
        {"GET", new[] {"GetList", "GetAll", "Get"}},
        // {"PUT", new[] {"Put", "Update"}},
        // {"DELETE", new[] {"Delete", "Remove"}},
        {"POST", new[] {"Create", "Add", "Insert", "Post"}},
        //{"PATCH", new[] {"Patch"}}
    };

    public static string GetConventionalVerbForMethodName(string methodName)
    {
        foreach (var conventionalPrefix in ConventionalPrefixes)
        {
            if (conventionalPrefix.Value.Any(prefix => methodName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)))
            {
                return conventionalPrefix.Key;
            }
        }

        return DefaultHttpVerb;
    }
}
`````

**Comment by pmjaleel** [comment]
Which solution we need to write this?

**Comment by zhaofenglee** [comment]
You can place the MyServiceConvention file in the Host directory.
![image](https://github.com/abpframework/abp/assets/111716814/12c0d895-f188-4fd3-8f07-09cb060ef355)

**Comment by pmjaleel** [comment]
Great it is working. 
The change that we see is that it changes the verb for the services that we create. What about the ABP services by default for the User tenant services etc?

**Comment by zhaofenglee** [comment]
hi,see
https://docs.abp.io/en/abp/7.2/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller
