### ISSUE TITLE
Not support event choreography

### ISSUE THREAD

**Issue by MapleWithoutWords** [abpframework/abp#16724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Because in certain special scenarios, I want to control the order of event processing. 

### Describe the solution you'd like

I want it to execute in the same order as shown in the figure below. And event handlers can be added at will

![image](https://github.com/abpframework/abp/assets/38368335/f1492bd6-f9ef-4897-9603-fe15ff5874a2)

**Comment by hikalkan** [comment]
Distributed or Local events?

**Comment by MapleWithoutWords** [comment]
> Distributed or Local events?

Yes, I think we can support that

**Comment by MapleWithoutWords** [comment]
Maybe I can try to add this feature. @hikalkan

**Comment by MapleWithoutWords** [comment]
I think distributed and local are the same, I just control the order in which it is executed

> Distributed or Local events?

**Comment by maliming** [comment]
hi @MapleWithoutWords 

https://github.com/abpframework/abp/issues/16361

**Comment by MapleWithoutWords** [comment]
@maliming I think local event support choreography help with program extension. It's a very good feature. 
Example:
 I have a feature that has a lot of logic, and one day I want to add caching to it, and if there's event orchestration, I can easily add functionality to it. I just need to add two event handlers, one to judge the cache and return on the first subscription, and one to add the cache at the end.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/16544

**Comment by MapleWithoutWords** [comment]
thank you

> #16544
