### ISSUE TITLE
Misleading summary in OrganizationUnitRole.cs

### ISSUE THREAD

**Issue by personball** [abpframework/abp#16731]
Here‘s a summary explains `OrganizationUnitRole`  as ou can having roles (for example: Leader、Member) represent memberships can be  assigned to a single user。 
https://github.com/abpframework/abp/blob/82eec06310f037a28b2d0241463bf670fc6191c1/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/OrganizationUnitRole.cs#LL8C46-L8C46

But these codes to query user's roles with all ou the user joined (these roles only related to the ou itself).
https://github.com/abpframework/abp/blob/82eec06310f037a28b2d0241463bf670fc6191c1/modules/identity/src/Volo.Abp.Identity.EntityFrameworkCore/Volo/Abp/Identity/EntityFrameworkCore/EfCoreIdentityUserRepository.cs#L47

We will see anyone in the ou will inherit all the roles related to the ou.

**Comment by EngincanV** [comment]
Thanks for the explanation, I will update the summary.

**Comment by personball** [comment]
> Thanks for the explanation, I will update the summary.

You are welcome.
