### ISSUE TITLE
abp generate-proxy when a class has a property of type List of another class with generic type

### ISSUE THREAD

**Issue by wael-razouk-9** [abpframework/abp#16743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have an app service called `CategoryAppService` as follows:
```
public class CategoryAppService : ICategoryAppService
    {
        public CategoryAppService() { }

        public List<CategoryDto> GetAll()
        {
            return new List<CategoryDto>();
        }
    }
```

and here is the `CategoryDto` class
```
public class CategoryDto : AuditedEntityWithUserDto<Guid, IdentityUserDto>
    {
        public string Name { get; set; }
        public List<NameId<Guid>> Subs { get; set; } = new List<NameId<Guid>>();
    }

    public class NameId<T>
    {
        public string Name { get; set; }
        public T Id { get; set; }
    }
```
When I generate the proxies for the angular project using command `abp generate-proxy -t ng`
I get this `models.ts` file
```
import type { AuditedEntityWithUserDto } from '@abp/ng.core';

export interface CategoryDto extends AuditedEntityWithUserDto<string, IdentityUserDto> {
  name?: string;
  subs: NameId<string>;
}

export interface NameId<T> {
  name?: string;
  id: T;
}
```
Here we have 3 problems:

- `Subs` property is converted to single element (not array)
- `IdentityUserDto` is not defined (missing adding import for it from `@abp/ng.identity/proxy`
- `AuditedEntityWithUserDto` in angular project is defined as `AuditedEntityWithUserDto<TUserDto, TPrimaryKey>` (which is the opposite in the backend project (`TUserDto` and `TPrimaryKey` are replaced in position), but here in this `models.ts` they are wrongly placed

### Version

7.1.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by wael-razouk** [comment]
One issue is fixed. Other 2 issues are still exist. Any updates please @maliming @mahmut-gundogdu ?

**Comment by maliming** [comment]
hi 
Please create a new issue. Thanks.

**Comment by ramilaliyev007** [comment]
Hi @maliming , @hikalkan, These problems already notified to you, but why we must open new issue ? 
I faced the same problem in my project at today. And I don't find any solution.
Really, your support is very bad.

**Comment by maliming** [comment]
hi @mahmut-gundogdu 

What do you think?

**Comment by wael-razouk** [comment]
@mahmut-gundogdu 
Any updates?
