### ISSUE TITLE
email tamplte

### ISSUE THREAD

**Issue by zahra96389** [abpframework/abp#16745]
> 

I had the same problem and resolved it by adding the `<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>`
as described in [abp virtual file documentation](https://docs.abp.io/en/abp/latest/Virtual-File-System#embedding-the-files)

_Originally posted by @amirhossein92 in https://github.com/abpframework/abp/issues/6523#issuecomment-1141734249_

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/6523#issuecomment-1141734249
