### ISSUE TITLE
Mvc UserMenu doesn't work

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1677]
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Components/Toolbar/UserMenu/Default.cshtml#L15

Toolbar UserMenu doesn't work.

1. Create a new abp mvc tiered solution.
2. Run Web project.
3. Login.
4. Clicek the user menu but it doesn't show.
![image](https://user-images.githubusercontent.com/30018771/63646490-2c840b00-c746-11e9-9373-c40bbda74ab5.png)

**Comment by yekalkan** [comment]
AbpAccountUserMenuContributor is in Volo.Abp.Account.Web module which is not referenced by *.Web project of tiered template. This is why dropdown is empty.

We will fix this.

**Comment by gdlcf88** [comment]
Try to depends on `AbpAccountWebModule`, the menu problem is fixed. But after clearing browser cache and try to login, it always return to home page with no identity.

**Comment by yekalkan** [comment]
This will be resolved when https://github.com/abpframework/abp/pull/1719 is merged.
