### ISSUE TITLE
User timeoutpermission behaviour with ABP 6.0.3

### ISSUE THREAD

**Issue by genoher** [abpframework/abp#16771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have seen that the following bug has been added to version 7.3.0-rc.1
I am using version 6.0.3. and I was wondering if there would be a new release of version 6 with the patch/fix 6.1.0

https://support.abp.io/QA/Questions/5022/User-timeoutpermission-behaviour
https://github.com/abpframework/abp/pull/16504

The validity period of access_token is shorter than Cookies and the API request will be 401 after it expires. But the ThreadCurrentPrincipal will not be invalidated.

The CheckTokenExpiration method will check the expiration time of access_token and request the authserver every 1 minute(configurable) to ensure the access_token is valid.

Sign out cookies if the token expires or is no longer valid.

### Reproduction Steps

Locally I have not been able to reproduce it.
The bug in question happens in Dev/Uat or Prod environments.

To reproduce it I follow the following steps:
1.- Login in the WEB application
2.- Make a publication. In my case they are docker images that are generated with Jenkins and uploaded to amazon.
3.- When it has finished publishing, I refresh the page (F5), it usually gives me a 401, although sometimes it gives me a 500.
4.- If I navigate to the main page "/" the user's data appears as it is "logged in", but the central menu disappears.

It is as if the permissions of the logged in user were lost, sometimes... changing the language, the menu appears, but if I put the same language again, it disappears.

Adding the next file in Web Host Project and adding options.CheckTokenExpiration(); in the WEB Host Module, resolve my bug...

https://github.com/abpframework/abp/blob/2774e6e7a8536858f3da91f523c663284ef0809b/framework/src/Volo.Abp.AspNetCore/Microsoft/Extensions/DependencyInjection/CookieAuthenticationOptionsExtensions.cs

### Expected behavior

Either the login is maintained with the permissions and the menu does not disappear, or the web application is logged out.

### Actual behavior

Se mantiene "logeado" pero desaparece el menu.

### Known Workarounds

https://support.abp.io/QA/Questions/5022/User-timeoutpermission-behaviour
https://github.com/abpframework/abp/pull/16504

The validity period of access_token is shorter than Cookies and the API request will be 401 after it expires. But the ThreadCurrentPrincipal will not be invalidated.

The CheckTokenExpiration method will check the expiration time of access_token and request the authserver every 1 minute(configurable) to ensure the access_token is valid.

Sign out cookies if the token expires or is no longer valid.

### Version

6.0.3

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

### Other information

My project is a Module Template (not application). Tiered with separated Auth Server (Identity Server).

**Comment by maliming** [comment]
hi

>  I was wondering if there would be a new release of version 6 with the patch/fix 6.1.0

There will be not release of 6.x for this PR.

You can copy the code in PR to your project.

**Comment by genoher** [comment]
I can and have copied the code from the PR, but surely other people have this problem, and if they have not been lucky enough to find the PR or the question in the support section, they will continue with the error...

Thanks for the solution you provide in the PR, but I still think a new release should be released.

If abp.io support the last two versions of .net (6 and 7), should release a patch for the abp 6 version...
From my point of view, I can be wrong.

**Comment by genoher** [comment]
I can and have copied the code from the PR, but surely other people have this problem, and if they have not been lucky enough to find the PR or the question in the support section, they will continue with the error...

Thanks for the solution you provide in the PR, but I still think a new release should be released.

If abp.io support the last two versions of .net (6 and 7), should release a patch for the abp 6 version...
From my point of view, I can be wrong.

**Comment by maliming** [comment]
We can't handle all the old versions. You can upgrade to latest or copy the fix code.

**Comment by genoher** [comment]
I can't upgrade abp 7,X because .net core 7 its not Long term support. 
I copy the code of the PR.
Thanks
