### ISSUE TITLE
Unable to find package Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXLiteTheme with version (>= 2.3.0-0)

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#16770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Created new application using the following cli command:

_**abp new TestProj -u blazor --preview --pwa -csf**_ 

but get the following error:

**_C:\Abp\TestProj\src\TestProj.Blazor\TestProj.Blazor.csproj : error NU1102: Unable to find package Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXLiteTheme with version (>= 2.3.0-0)
C:\Abp\TestProj\src\TestProj.Blazor\TestProj.Blazor.csproj : error NU1102:   - Found 34 version(s) in Nuget [ Nearest version: 2.2.1 ]
C:\Abp\TestProj\src\TestProj.Blazor\TestProj.Blazor.csproj : error NU1102:   - Found 0 version(s) in C:\Program Files\dotnet\library-packs
1 of 4 projects are up-to-date for restore.

Build FAILED._**

### Reproduction Steps

Create new application using the following:

abp new TestProj -u blazor --preview --pwa -csf 

### Version

7.3.0-rc.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by salihozkara** [comment]
Hello @DonVliet ,
this error should be solved, can you check again?

**Comment by DonVliet** [comment]
Thanks @salihozkara
