### ISSUE TITLE
Reference to Microsoft.EntityFrameworkCore.Design in template 

### ISSUE THREAD

**Issue by Elencon** [abpframework/abp#16785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created project with command 
abp new Something -u blazor-server -csf 
Then i followed instructions 
https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#using-multiple-databases
in order to create project with support to multiple DB
When I executed command 
:Add-Migration "Initial" -OutputDir "SecondDbMigrations" -Context BookStoreSecondDbContext
in Package-Manager console i get
**"Your startup project 'Something.Blazor' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again**."
I installed this package and everything executed properly.
Please add this package to ABP template 

### Reproduction Steps

Created project 
abp new Something -u blazor-server -csf
executed command
Add-Migration "Initial" -OutputDir "SecondDbMigrations" -Context BookStoreSecondDbContext

### Actual behavior

no errors

### Known Workarounds

Added package Microsoft.EntityFrameworkCore.Design.

### Version

7.2.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
You should create your migrations in the `MyCompanyName.MyProjectName.EntityFrameworkCore` project. Run the migration creation command under the directory of this project.

**Comment by Elencon** [comment]
I set default project .Blazor. 
In PM Console i set default .EntityFrameworkCore
then i run command
Add-Migration
What i did wrong ?

**Comment by EngincanV** [comment]
> I set default project .Blazor. In PM Console i set default .EntityFrameworkCore then i run command Add-Migration What i did wrong ?

Set your startup project as *MyCompanyName.MyProjectName.EntityFrameworkCore* while you are running the command. Then it should correctly create a migration under the project.

**Comment by Elencon** [comment]
then there is error in documentation 
https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#using-multiple-databases
**Now, you can open the Package Manager Console, select the .EntityFrameworkCore project as the default project (make sure the .Web project is still the startup project**

**Comment by Elencon** [comment]
the same is written in the book : Mastering Abp Framefork
**Select the ProductManagement.EntityFrameworkCore project as the Default project type.
Ensure that the ProductManagement.Web project is selected as the startup project**

**Comment by EngincanV** [comment]
In your case, you should select the `EntityFrameworkCore` project in the PM console and the `HttpApi.Host` project as the startup project.

**Comment by Elencon** [comment]
ok thanks

**Comment by RayWangQvQ** [comment]
> In your case, you should select the `EntityFrameworkCore` project in the PM console and the `HttpApi.Host` project as the startup project.

But when the solution is  blazor server with no-tiered, there is no `HttpApi.Host` project. 

So there is no way to run migration in pkg manager console in this situation.
