### ISSUE TITLE
Why cannot refresh the cache of IAuthorizationService.IsGrantedAsync()?

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1678]
**Mvc tiered.**

1. Use `AbpPermissionManagement` to grant a permission to admin role.
![63654334-a8646e80-c7ab-11e9-9b6f-9ff03becd570](https://user-images.githubusercontent.com/30018771/63697223-131ab600-c84f-11e9-8269-e05aa8a206e1.png)
2. Try relogin(clear browser cache), and run these code, but get false.
```
var authorizationService = context.ServiceProvider.GetRequiredService<IAuthorizationService>();
var result = await authorizationService.IsGrantedAsync(DentureMasterPermissions.Administration.ProductCategoryManagement.ProductCategoryManagementGroupName);
```
3. Try redis `flushall`, relogin and run the code, also get false.
4. Restart Web project and run the code, get true.

How to refresh the permisstion cache?

**Comment by maliming** [comment]
Can you provide a project to reproduce the problem?

**Comment by gdlcf88** [comment]
https://github.com/gdlcf88/AbpPermissionCacheTest
1.Run project `AbpPermissionCacheTest.DbMigrator`.
2.Run projects `AbpPermissionCacheTest.IdentityServer`, `AbpPermissionCacheTest.HttpApi.Host`, `AbpPermissionCacheTest.Web`.
3. Open home page(project Web), login as user admin(with password 1q2w3E*).
4. Grant all permissions to user "test".
5. Logout from user admin and login as user test.
6. Remove user test's all permissions about "Teant Manage".
7. Refresh the page, tenant manage in menu still exists.
8. Relogin user test, tenant manage in menu still exists.
9. Rerun projects, tenant manage in menu disappear.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.AspNetCore.Mvc.Client/Volo/Abp/AspNetCore/Mvc/Client/CachedApplicationConfigurationClient.cs#L44-L51

When the user's permissions change, it takes 60 seconds for the web to refresh.
But the request sent to the api will check the permissions in real time.

The cache should be invalidated when the contents of the cache are changed.
But it seems that it is not easy to implement the function of cache invalidation.

**Comment by hikalkan** [comment]
I think 60 second cache (for optimization) is tolerable for now for real world scenarios. We will work on this later.

**Comment by hikalkan** [comment]
This is also true for settings. I am taking this to the next milestone to see what we can do (for example, instead of a separate cache, we can share the same permission cache with the backend).

**Comment by hikalkan** [comment]
This is resolved like that: When a permission/feature/setting/localization changes, it automatically invalidates the configuration cache, so you get the latest configuration. This is done only for the current user, so you see the changes immediately you do it. Other users still will be affected by the changes after their cache duration expires. Cache time is 5 minutes.
