### ISSUE TITLE
Wrong Test  .EntityFrameworkCore.Tests for project with SqlServer

### ISSUE THREAD

**Issue by Elencon** [abpframework/abp#16787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Created Project with sql server with command
 abp new Acme.BookStore -u blazor-server -csf
But tests in .EntityFrameworkCore.Tests
they are for Sqlite

### Reproduction Steps

abp new Acme.BookStore -u blazor-server -csf

### Expected behavior

.EntityFrameworkCore.Tests must be for SqlServer

### Actual behavior

Test for Sqlite

### Regression?

don't know

### Known Workarounds

Changed manually

### Version

7.2.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

se tu

**Comment by maliming** [comment]
We can't use SQL Server in unit test.

**Comment by maliming** [comment]
https://learn.microsoft.com/en-us/ef/core/testing/testing-without-the-database
