### ISSUE TITLE
Volo Abp AbpSecurityStampValidator always invalidates existing user

### ISSUE THREAD

**Issue by angelcalvasp** [abpframework/abp#16799]
**ABP Framework version:** 7.0.4
**Authentication** OpendIdDict
**Database provider:** MSSQL

I am having an issue where AbpSecurityStampValidator is always loggin users out once it checks for security stamp, digging into the source I came across that TenantConfigurationProvider is never resolving tenant from any of the default resolvers,

    try
    {
        tenant = await TenantConfigurationProvider.GetAsync(saveResolveResult: false);
    }
    catch (Exception e)
    {
        Logger.LogException(e);
    }

therefore never getting the user to compare security stamp with, I have not cleared any of the default resolvers but I have added my own

I am attaching a picture of the claims from the context in case its relevant

![image](https://github.com/abpframework/abp/assets/7502746/96bed189-e60b-4a9f-9db5-50fef30e563e)

The application runs fine, CurrentTenant and CurrentUser are available during all calls to app services but there are never available on AbpSecurityStampValidator

**Comment by maliming** [comment]
hi

How to reproduce this issue?
Please share some steps.

**Comment by angelcalvasp** [comment]
Hi I apologize, for not adding the steps, 
What I do is the following

-  Login as any user 
- Wait for the interval (by default is 30 minutes, but can be lowered for testing purposes with the code below)
-  Refresh the view after the the validation interval
- User will be asked to login again because the security stamp is invalid

and on the main mvc project module I added the following to make the validation interval faster

```
Configure<SecurityStampValidatorOptions>(options =>
{
    options.ValidationInterval = TimeSpan.FromMinutes(1);
});
````

I would like to also add the project is a single asp.net core MVC site which is both client and does authorization 
cookie based authentication

**Comment by angelcalvasp** [comment]
The issue was caused by a a couple of separate overrides and custom code
