### ISSUE TITLE
AbpApplicationManager does not  populate descriptor correctly.

### ISSUE THREAD

**Issue by linyute** [abpframework/abp#16797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying get `AbpApplicationDescriptor` from `AbpApplicationManager.PopulateAsync()`, but the client URL and logo URI are not correct.
I traced the source code, as below, it should update the descriptor, not the application.

```
    public async override ValueTask PopulateAsync(OpenIddictApplicationDescriptor descriptor, OpenIddictApplicationModel application, CancellationToken cancellationToken = default)
    {
        await base.PopulateAsync(descriptor, application, cancellationToken);

        if (descriptor is AbpApplicationDescriptor model)
        {
            application.ClientUri = model.ClientUri; // here
            application.LogoUri = model.LogoUri; // here
        }
    }
```

### Reproduction Steps

```
private readonly IAbpApplicationManager _applicationManager;

var applications = this._applicationManager.ListAsync();

var list = new List<AbpApplicationDescriptor>();

await foreach (OpenIddictApplicationModel application in applications)
{
	// application.ClientUri has value

	var descriptor = new AbpApplicationDescriptor();

	await this._applicationManager.PopulateAsync(descriptor, application);

	// application.ClientUri is updated to null
}
```

### Expected behavior

The `applicationManager` should fill `ClientUri` and `LogoUri` of `application` to `descriptor` correctly.

### Actual behavior

The`ClientUri` and `LogoUri` of `application` are updated to `null`.

### Version

7.2.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

We will fix that in https://github.com/abpframework/abp/pull/16800
