### ISSUE TITLE
Current database does not support transactions.

### ISSUE THREAD

**Issue by mhdabdelrhman** [abpframework/abp#16794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello
I am using Abp framework v `5.2.2` with `mongoDB` (standalone), already I disabled the unit of work transactions in all modules 
```csharp
public class HMBLMongoDbModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddMongoDbContext<HMBLMongoDbContext>(options =>
            {
                options.AddDefaultRepositories();
            });

            Configure<AbpUnitOfWorkDefaultOptions>(options =>
            {
                options.TransactionBehavior = UnitOfWorkTransactionBehavior.Disabled;
            });

            Configure<AbpUnitOfWorkOptions>(options =>
            {
                options.IsTransactional = false;
            });
        }
    }

```

but still I am getting this error in the log:

     `Current database does not support transactions. Your database may remain in an inconsistent state in an error case.`
 
could you please help?.    

### Version

5.2.2

### User Interface

Angular

### Database Provider

MongoDB

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

**Comment by mhdabdelrhman** [comment]
@maliming   any solution please?

**Comment by maliming** [comment]
hi

This is a warning message. You can ignore it now.
