### ISSUE TITLE
Required antiforgery header value is not present

### ISSUE THREAD

**Issue by tiktb8** [abpframework/abp#1679]
During the execution of an ajax post I am getting a 400 error.  The resulting error from the log file is:
Antiforgery token validation failed. The required antiforgery header value "RequestVerificationToken" is not present.

Examining the actual post headers it appears as if the header is there but it's name is x-xsrf-token as appears to be correct.

The syntax of the post is:
`$.ajax({
            url: location.origin + '/FacebookAuth',            
            type: 'POST',
            contentType: "application/json",
            data: data,
            error: function (e) {
                console.log(e);
            }
        }).done(function (result) { });`

Have I missed some kind of service activation or option configuration that tells the framework to use this as the header name as opposed to the default "RequestVerificationToken"?

Thanks!

**Comment by ismcagdas** [comment]
@tiktb8 could you try with `abp.ajax` instead of `$.ajax` ? It should automatically add anti-forgery token to request headers.

**Comment by tiktb8** [comment]
The ajax interceptor property inserting the header when using $.ajax but as I mentioned, it is naming the header "x-xsrf-token".

I was able to come up with a workaround using this:
`services.AddAntiforgery(options =>
            {
                options.HeaderName = "x-xsrf-token";                
            });`

I just don't know if this is something the framework should be handling.

**Comment by mostafa1790** [comment]
I have this issue too I use javascript dynamic proxy and I get a bug fro it security from my company about interceptors, so I need to know if I missing something to I must write some of the code.
I use MVC Tiered project

**Comment by hikalkan** [comment]
Framework automatically adds antiforgery tokens on all ajax requests (see: https://github.com/abpframework/abp/blob/dev/npm/packs/jquery/src/abp.jquery.js#L248)
I never had this problem before.

Can you repeat it with a fresh new template or define steps how we can re-produce it?

BTW, if you've created a custom layout, you may need to call AbpAntiForgeryManager.SetCookie() like  https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Application.cshtml#L16

**Comment by hikalkan** [comment]
I am closing this since it is inactive. You can reopen if you still have the problem. Thanks.
