### ISSUE TITLE
Db update OpenIddictApplications.LogoUri = "dummy_string or http://path_to_online_logo" then Auth Server Raise 500 exeption on login form component

### ISSUE THREAD

**Issue by hungtrinh** [abpframework/abp#16804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On db, table `OpenIddictApplications`  if exits an record with `LogoUri` = 'dummy_string_not_start_by_char_/" or 'http://real_online_logo' Then access Auth Server will rasie error 500 on login form component

### Reproduction Steps

After login success, on Angular web screen: '/openiddict/Applications'  (Administration > OpenId > Applications)
1. Click Action / Edit an Record
2. On Screen Edit Application, Set `Logo Uri` field input: `abcdef` or `http://online_logo_path` 
3. On Screen Edit Application, Click Save

### Expected behavior

After Set LogoUri = 'dummy text, or http://online_logo_path' then auth server (local: https://localhost:44334/) working normal

### Actual behavior

On Auth server, login component section show error message `500
Internal Server ErrorAn internal error occurred during your request!`

Here is log on Auth Server
```
authserver    | [15:44:34 ERR] An unhandled exception has occurred while executing the request.
authserver    | System.ArgumentException: The path in 'value' must start with '/'. (Parameter 'value')
authserver    |    at Microsoft.AspNetCore.Http.PathString..ctor(String value)
authserver    |    at Microsoft.AspNetCore.Mvc.Routing.UrlHelperBase.Content(HttpContext httpContext, String contentPath)
authserver    |    at AspNetCoreGeneratedDocument.Pages_Index.<>c__DisplayClass29_1.<<ExecuteAsync>b__18>d.MoveNext() in /home/runner/work/abp/abp/aspnet-core/src/AuthServer/Pages/Index.cshtml:line 108
```

aspnet-core/src/AuthServer/Pages/Index.cshtml:line 108 FILE CONTENT
```C#
105      @if (!application.LogoUri.IsNullOrEmpty())
106      {
107          <div class="mx-auto">
108              <img src="@Url.Content(application.LogoUri.EnsureStartsWith('~'))" style="height:64px" class="mb-3" />
109          </div>
110      }
```

### Version

7.2.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

We will fix it in the next patch version. 

Thanks.
