### ISSUE TITLE
Documentation should not encourage IQueryable usage in AppServices

### ISSUE THREAD

**Issue by MichelZ** [abpframework/abp#16809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the documentation about [Repositories](https://docs.abp.io/en/abp/latest/Repositories#querying-linq-over-the-repositories), it does use `GetQueryableAsync()` in an AppService.
This section should probably be extended to note that using an `IQueryable<TEntity>` in an AppService is discouraged and not a best practice. 
So currently the documentation for [Repositories](https://docs.abp.io/en/abp/latest/Repositories#querying-linq-over-the-repositories) and the [Best Practice documentation](https://docs.abp.io/en/abp/latest/Best-Practices/Repositories#repository-interfaces) contradict each other.

> **Do not** use generic repository interfaces (like `IRepository<IdentityUser, Guid>`) from the application code.
> **Do not** use `IQueryable<TEntity>` features in the application code (domain, application... layers).

It's probably a good idea to link to the best practices where the usage of `IQueryable<TEntity>` is explained

**Comment by hikalkan** [comment]
Adding a warning section to the repositories document can be good. I agree. Thanks.

**Comment by hikalkan** [comment]
I added a warning box:

![image](https://github.com/abpframework/abp/assets/1210527/6dcb3fcc-4cb6-4240-91bc-e0dce01ded40)

I know that warning is not _so strong_. However, there are many developers are misunderstanding ABP. They think ABP strictly follows DDD and Layering and these are not needed for their applications. DDD and Layering may bring complexity and can be time-consuming for some applications, and I agree on that. However, ABP doesn't force these, but just make them easy to implement when you are mentally ready to implement them. So, the documentation should stay in a balance and understand different needs :)

**Comment by MichelZ** [comment]
This makes complete sense. You might also want to link the best practices document though, so people who want to follow it can easily reference it.

Thanks!
