### ISSUE TITLE
Can't logout from the Web UI

### ISSUE THREAD

**Issue by lukjok** [abpframework/abp#1680]
Using tiered MVC template, trying to log out from application using Account/Logout route as it is working properly for the IdentityServer project, but when called from Web project it throws this exception:

> Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.Account.Web.Areas.Account.Controllers.LogoutController -> Microsoft.AspNetCore.Identity.SignInManager`1[[Volo.Abp.Identity.IdentityUser, Volo.Abp.Identity.Domain, Version=0.19.0.0, Culture=neutral, PublicKeyToken=null]] -> λ:Microsoft.AspNetCore.Identity.UserManager`1[[Volo.Abp.Identity.IdentityUser, Volo.Abp.Identity.Domain, Version=0.19.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.Identity.IdentityUserManager -> Volo.Abp.Identity.IdentityUserStore. ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Volo.Abp.Identity.IdentityUserStore' can be invoked with the available services and parameters:
> Cannot resolve parameter 'Volo.Abp.Identity.IIdentityUserRepository userRepository' of constructor 'Void .ctor(Volo.Abp.Identity.IIdentityUserRepository, Volo.Abp.Identity.IIdentityRoleRepository, Volo.Abp.Guids.IGuidGenerator, Microsoft.Extensions.Logging.ILogger`1[Volo.Abp.Identity.IdentityRoleStore], Microsoft.AspNetCore.Identity.IdentityErrorDescriber)'

Dependencies of the Web project:
 ```
[DependsOn(
        typeof(CoreHttpApiModule),
        typeof(CoreHttpApiClientModule),
        typeof(AbpAspNetCoreAuthenticationOAuthModule),
        typeof(AbpAspNetCoreMvcClientModule),
        typeof(AbpAspNetCoreMvcUiBasicThemeModule),
        typeof(AbpAutofacModule),
        typeof(AbpFeatureManagementWebModule),
        typeof(AbpHttpClientIdentityModelModule),
        typeof(AbpIdentityWebModule),
        typeof(Volo.Abp.Account.Web.AbpAccountWebModule),
        typeof(AbpTenantManagementWebModule)
        )]
```

Any ideas?

**Comment by maliming** [comment]
Similar to #1462, it is also a problem with module dependencies.
