### ISSUE TITLE
Update Installation sections in some documents

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#16811]
Instead of that (https://docs.abp.io/en/abp/latest/Entity-Framework-Core):

![image](https://github.com/abpframework/abp/assets/1210527/f235c546-28eb-4c1a-aa31-59b6587c5f71)

Use a section similar to (https://docs.abp.io/en/abp/latest/Dapper):

![image](https://github.com/abpframework/abp/assets/1210527/dafbd3c0-8e51-474b-9b7a-d608b95b7ffa)

Please check all the documentation and update the installation sections according to that (ensure that the package description page does exists for each package. if not, contact to @yekalkan to add them).

**Comment by postmeback** [comment]
It looks like a documentation fix, I would like to contribute on this. Requesting guidance

**Comment by braim23** [comment]
> It looks like a documentation fix, I would like to contribute on this. Requesting guidance

Thank you for your offer pal, already took it

**Comment by braim23** [comment]
Completed
