### ISSUE TITLE
Slow request times in generated solution 7.2.2 & 7.3.0-rc.1 

### ISSUE THREAD

**Issue by tr1stan** [abpframework/abp#16817]
I'm currently evaluating ABP for a future project and I'm seeing slow response times when calling any of the endpoints. 

Specifically I'm  seeing slow GET request times from an out-the-box solution generated from https://abp.io/get-started on my MacOS environment running Visual Studio 2022. I'm seeing this with Postgres, MySQL and MSSQL DB providers. 

I see much better performance when I [download the BookStore sample](https://github.com/abpframework/abp-samples/tree/master/AcmeBookStoreAngularMaterial) and run it as-is on MSSQL.

-- 
Steps to reproduce on MSSQL, although I'm seeing the same results through local Postgres and MySql databases:

1. Generate new project: `abp new Sample.PerformanceMsSQL -u angular -csf `
2. Spin up MSSQL DB container 
`sudo docker pull mcr.microsoft.com/mssql/server:2022-latest`
```sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>" \
   -p 1433:1433 --name sql1 --hostname sql1 \
   -d \
   mcr.microsoft.com/mssql/server:2022-latest
```
3. Configure the connection string to point to a new database
4. Run DB migrations
5. Run Host
6. Using Swagger > Authenticate using `admin` > Run GET on `/identity/users`

And example of the request times I'm seeing in the logs:
![Screenshot 2023-06-12 at 20 38 59](https://github.com/abpframework/abp/assets/45169274/2759a86d-133a-430b-90cd-96493b10b5d6)

I have also tried the following steps using the preview release 7.3.0-rc.1, and I get the same results.

### Configuration

System: 
macOS Monterey
Version 12.6
MacBook Pro (16-inch, 2019)
Processor 2.4 GHz 8-Core Intel Core i9
Memory 64 GB 2667 MHz DDR4
Graphics AMD Radeon Pro 5500M 8 GB
Intel UHD Graphics 630 1536 MB

.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: x64

### Regression
I do not see the same performance issues when I [download the BookStore sample](https://github.com/abpframework/abp-samples/tree/master/AcmeBookStoreAngularMaterial) and run against the same MSSQL docker container, on a new database with the sample migrations run. 

![Screenshot 2023-06-12 at 20 28 11](https://github.com/abpframework/abp/assets/45169274/704caf71-d8ad-443c-b688-73326f6fce17)

**Comment by maliming** [comment]
hi

You can set the log level to debug to see more details.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/Program.cs#L17

**Comment by tr1stan** [comment]
Thanks, I’m presuming that the lines in the screen shot with [DBG] are debug lines? I’m running the code in debug mode, not release mode. 

Side-note: Running in release mode doesn’t speed anything up significantly, but it does remove the DBG lines in the logs.

**Comment by maliming** [comment]
hi

You can remove `MinimumLevel.Override` to more ASP NET Core logs.

**Comment by tr1stan** [comment]
So I have no idea what's going on with this. It turns out that if I run the `.Host` and `.AuthServer` projects of the generated app from Visual Studio 2022 as a Multiple Project startup which is setup using `Menu > Projects > Set Startup Projects...`. I get these response times:
![Screenshot 2023-06-14 at 15 20 42](https://github.com/abpframework/abp/assets/45169274/6260e2b0-f12a-48b5-b0e5-d5e1091a6a81)

But if I run the two projects separately from the terminal using `dotnet run --project src/PerformanceTest.AuthServer` 
& `dotnet run --project src/PerformanceTest.HttpApi.Host` then I get these response times: 
![Screenshot 2023-06-14 at 16 34 29](https://github.com/abpframework/abp/assets/45169274/ac24aa18-083a-469f-9aea-cce69e989474)

That's a bunch of hours of my life I'm not getting back. So running them separately (Also works if you run them separately through Visual Studio) is a work-around that allows me to get on with evaluating other parts of the framework.
