### ISSUE TITLE
Is abp.io stable and ready to use?

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#1681]
Hi,
I before used aspboilerplate in our projects and it was great, in our new project I want to use new abp.io.
is it stable and ready to use?

**Comment by ismcagdas** [comment]
Hi @mehdihadeli yes, it is stable at the moment and we will not add major features until 1.0 release. But currently the documentation is not complete, so you might have problems about that.

**Comment by mehdihadeli** [comment]
> Hi @mehdihadeli yes, it is stable at the moment and we will not add major features until 1.0 release. But currently the documentation is not complete, so you might have problems about that.

thanks, when documentation will be complete?

**Comment by JakeStaTeresa** [comment]
@ismcagdas when is the target release date for 1.0?

**Comment by ismcagdas** [comment]
See Road Map section of https://blog.abp.io/abp/ABP-v0-19-Release-With-New-Angular-UI

**Comment by KevinFarrow** [comment]
The Project Status in the documentation (https://docs.abp.io/en/abp/latest) says:

"It's currently in preview stage and not ready to use in production."

but you say "yes, it is stable at the moment" - which is correct?

**Comment by maliming** [comment]
@KevinFarrow The description in the blog post is the latest state.
https://blog.abp.io/abp/ABP-v0-19-Release-With-New-Angular-UI

**Comment by KevinFarrow** [comment]
@maliming I'm not sure what you mean by "description in the blog post is the latest state" as the blog doesn't mention whether the code is stable and ready to use.  This issue asks "Is abp.io stable and ready to use?" so I was wondering which of the 2 statements below are true?

1. Statement on abp.io website: "It's currently in preview stage and not ready to use in production." 

OR 

2. The reply in this issue from @ismcagdas : "yes, it is stable at the moment"

It's probably better if @ismcagdas could answer as I think you are getting confused. Thanks anyway for trying to help.

**Comment by ismcagdas** [comment]
@KevinFarrow code base is stable and can be used but we wrote the statement on the abp.io website for two reasons:

1. There is no documentation for most of the features.
2. We will upgrade to .NET Core 3.0 when it is released and there will be some breaking changes I guess. 

So, we officially don't want to say to use abp.io for production but if the project deadline is not very close, it would be better to start now for you. Also, think about breaking changes will be introduced when upgrading to .NET Core 3.0.
