### ISSUE TITLE
What is the expected way to get an id after doing a TRepository.Insert().... 

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1682]
Hi,

I see InsertAndGetId has been removed https://github.com/abpframework/abp/issues/54. What is the expected workflow now to get the identifier of a newly added record added via a repository call?

**Comment by ismcagdas** [comment]
@natiki use InsertAsync with autoSave=true if your PK is not Guid. See https://github.com/abpframework/abp/commit/a4594137514c0f25406ca667405874631181d374
