### ISSUE TITLE
Questions about the RemoteServiceAttribute

### ISSUE THREAD

**Issue by StrangerLi** [abpframework/abp#16832]
In my project, I want to disable all APIs in AppService by default, except for the APIs that I want to be exposed. Currently, I am using the RemoteServiceAttribute to disable APIs. However, this approach can be time-consuming when there are a lot of APIs in an AppService. Is there a way to enable specific APIs, like GetString(), without disabling the entire AppService?

My code now：
```C#
    public class SampleAppService : ApplicationService
    {
        private readonly ITenantUserAppService _appService;

        public SampleAppService(ITenantUserAppService appService)
        {
            _appService = appService;
        }

        public string GetStringNeedEnable()
        {
            return "1";
        }

        [RemoteService(false)]
        public string GetADisEnable()
        {
            return "1";
        }

        [RemoteService(false)]
        public string GetBDisEnable()
        {
            return "1";
        }

        //Other methods like GetCDisEnable，GetDDisEnable ...
    }
```

I expected code：
```C#
    [RemoteService(false)]
    public class SampleAppService : ApplicationService
    {
        private readonly ITenantUserAppService _appService;

        public SampleAppService(ITenantUserAppService appService)
        {
            _appService = appService;
        }

        [RemoteService(true)]
        public string GetStringNeedEnable()
        {
            return "1";
        }

        public string GetADisEnable()
        {
            return "1";
        }

        public string GetBDisEnable()
        {
            return "1";
        }

        //Other methods like GetCDisEnable，GetDDisEnable ...
    }
```

Reading the source code, I think that rewriting the `ConfigureSelector` method of `AbpServiceConvention` may be able to solve my problem, but I'm not sure if it's feasible.

Translated by chatgpt

**Comment by EngincanV** [comment]
Hi, I think you can configure the `AbpAspNetCoreMvcOptions` options as below in your `*.Web` module class:

```csharp
Configure<AbpAspNetCoreMvcOptions>(options =>
        {
            options.ConventionalControllers.Create(typeof(YourApplicationModule).Assembly, conventionalControllerOptions =>
            {
                conventionalControllerOptions.TypePredicate = t =>
                {
                    //only the below appservice will be exposed as API Controller
                    return t.Namespace == typeof(MyCompany.TodoAppService).Namespace;
                };
            });
        });
```

In the example above, I have only checked by namespace but you can improve this check. See the documentation: https://docs.abp.io/en/abp/7.3/API/Auto-API-Controllers#typepredicate-option

**Comment by StrangerLi** [comment]
@EngincanV thank you.

If i set both `RemoteService Attribute` and `TypePredicate Option` at the same time, what is the highest priority? Will they run simultaneously?

Translated by chatgpt

**Comment by EngincanV** [comment]
> If i set both `RemoteService Attribute` and `TypePredicate Option` at the same time, what is the highest priority? Will they run simultaneously?

`RemoteServiceAttribute` has higher priority.
