### ISSUE TITLE
ClientCredentialsTokenRequest in OpenIddict does not call IAbpOpenIddictClaimDestinationsProvider and IAbpClaimsPrincipalContributor

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#16833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Request like this
![image](https://github.com/abpframework/abp/assets/16984534/19b6e6fa-bea1-424e-a0a5-e81551f58276)

Is it by design or am I missing something?

### Version

7.2.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
There is no user concept on `ClientCredentials` grant type.

But I think we can call the `IAbpClaimsPrincipalContributor`.

I will do it on 7.3. You can try to override the `controller` now.

https://github.com/abpframework/abp/blob/rel-7.2/modules/openiddict/src/Volo.Abp.OpenIddict.AspNetCore/Volo/Abp/OpenIddict/Controllers/TokenController.ClientCredentials.cs
