### ISSUE TITLE
Command for downloding template not working "abp new Acme.BookStore --tiered -csf"

### ISSUE THREAD

**Issue by arpitce27** [abpframework/abp#16854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On https://abp.io/get-started page I was trying to download sample project but its not working with this command. 

abp new Acme.BookStore --tiered -csf 

### Reproduction Steps

Open Command Prompt on Windows 11 Machine.

Step 1: Open Command Prompt and type this command and enter
dotnet tool install -g Volo.Abp.Cli

Step 2: type this command and enter: 
abp new ABP.Sample --tiered -csf

### Expected behavior

Should be able to download the template file the project.

### Actual behavior

Throwing following error on step 2.

![image](https://github.com/abpframework/abp/assets/25935989/cf6bd679-08b5-4004-92c0-446a061525cb)

### Version

Tried with 7.2.2 & 7.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
`ABP CLI has a newer stable version 7.2.2, please update to get the latest features and fixes.`
