### ISSUE TITLE
AngularUI: Fix ngx-datatable responsive functionality when full screen

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#16851]
ngx-datatable page not autofilled after toggle side menu

![image](https://github.com/abpframework/abp/assets/49063256/f91fe0cc-0545-4f07-a7c2-c3f3132cdc23)

**Comment by mahmut-gundogdu** [comment]
I have tested it seems work well
![Screen Recording 2023-07-28 at 17 26 46](https://github.com/abpframework/abp/assets/2217899/de4b0411-b617-4bcf-b7aa-c473f79ee5b4)
