### ISSUE TITLE
What is purpose of HttpApi.Client ? 

### ISSUE THREAD

**Issue by CaglarMacha** [abpframework/abp#16874]
When we create a standard abp project, a project named HttpApi.Client comes up. What is the purpose of this project? Why does it use .net 2.0(<TargetFramework>netstandard2.0</TargetFramework>) instead of the current (5, 6, etc.) .net version, unlike other projects?
![image](https://github.com/abpframework/abp/assets/91030209/3d15f8eb-3e03-43d2-8201-24ca54ed64ac)

**Comment by maliming** [comment]
hi

https://docs.abp.io/en/abp/latest/Startup-Templates/Application#httpapi-client-project

**Comment by CaglarMacha** [comment]
Thank you
