### ISSUE TITLE
Blazor UI: The login screen can not be loaded if a custom theme is selected and you want to log in again

### ISSUE THREAD

**Issue by patrickjahr** [abpframework/abp#16887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a custom theme with Blazor Server and set that as default, the login screen does not load. For the login mask to load the cookie `lpx_loaded-css` must be deleted so that the application can use a default theme such as dark.

### Reproduction Steps

Add new Custom Theme in Configuration
```
Configure<LeptonXThemeOptions>(options =>
        {
            options.DefaultStyle = LeptonXStyleNames.System;
            options.Styles.Clear();

            options.Styles.Add(
                "customDark",
                new LeptonXThemeStyle(
                    LocalizableString.Create<MonitoringResource>("Theme:CustomDark"),
                    "bi bi-circle-fill")
                );
            options.DefaultStyle = "customDark";
        });
```

### Expected behavior

![success_login](https://github.com/abpframework/abp/assets/16818441/995f3efe-8f00-4182-b760-0ecb945ecab2)

### Actual behavior

![failed_login](https://github.com/abpframework/abp/assets/16818441/c2a20eb0-a301-406d-bbd2-a650e51b1b9c)

### Version

7.2.2

### User Interface

LEPTON X

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by enisn** [comment]
Can you share `customDark.css` with us? it'll help us to reproduce earlier
