### ISSUE TITLE
Inheritance issues of Authorize in custom AppService

### ISSUE THREAD

**Issue by chenyigg** [abpframework/abp#16899]
### Description

Authorize cannot be added to the default method in a custom AppService that inherits ReadOnlyAppService, such as GetAsync

### Configuration

    [ApiServiceName("Record")]
    [Authorize(Roles = "Admin")]
    public class OperationRecordAppService : ReadOnlyAppService<AuditLog, AuditLogDto, Guid, AuditLogListInput>
    {
        public OperationRecordAppService(IReadOnlyRepository<AuditLog, Guid> repository) : base(repository)
        {
        }

        protected override IQueryable<AuditLog> ApplyDefaultSorting(IQueryable<AuditLog> query)
        {
            return query.OrderByDescending(e => e.ExecutionTime);
        }

        protected override async Task<IQueryable<AuditLog>> CreateFilteredQueryAsync(AuditLogListInput input)
        {
            return (await base.CreateFilteredQueryAsync(input))
                    .WhereIf(!String.IsNullOrEmpty(input.UserName), t => t.UserName == input.UserName)
                    .WhereIf(!String.IsNullOrEmpty(input.BusinessType), t => t.HttpMethod == input.BusinessType)
                    .WhereIf(input.Status.HasValue, t => input.Status.Value ? String.IsNullOrEmpty(t.Exceptions) : !String.IsNullOrEmpty(t.Exceptions))
                    .WhereIf(input.StartTime.HasValue && input.EndTime.HasValue, x => x.ExecutionTime != default && x.ExecutionTime >= input.StartTime.Value && x.ExecutionTime <= input.EndTime.Value);
        }
    }

### Actual effect
In Swagger, all default methods still display unlocked
![image](https://github.com/abpframework/abp/assets/60416790/048f6740-efdc-4505-8662-8c54d157af31)

**Comment by maliming** [comment]
* Your ABP Framework version.

* Steps needed to reproduce the problem.

**Comment by chenyigg** [comment]
> * 您的 ABP 框架版本。
6.0
> * 重现问题所需的步骤。
1. Create a custom AppService that inherits from ReadonlyAppService

2. Add feature [Authorize] on AppService

3. Opening the swagger page, you can see that the default methods implemented by ReadonlyAppService are not locked, and you need to override or specify the method to display locked.

Here is the implementation of the third step
``` c#
[ApiServiceName("Record")]
    [Authorize]
    public class OperationDetailsRecordAppService : ReadOnlyAppService<AuditLogAction, AuditLogActionDto, Guid, AuditLogActionListInput>
    {
            public OperationDetailsRecordAppService(IReadOnlyRepository<AuditLogAction, Guid> repository) : base(repository)
            {
            }
            public async Task<ListResultDto<AuditLogActionDto>> GetByActionIdAsync(Guid acditLogId)
            {
                      return new ListResultDto<AuditLogActionDto>()
                      {
                          Items = ObjectMapper.Map<List<AuditLogAction>, List<AuditLogActionDto>>(
                                      (await Repository.GetQueryableAsync()).WhereIf(true, t => t.AuditLogId == acditLogId).OrderBy(u => u.ExecutionTime).ToList())
                      };
            }
    }

```
![image](https://github.com/abpframework/abp/assets/60416790/0886b59c-5345-467f-aed4-e60ed70bc126)

**Comment by maliming** [comment]
What is your project type?

**Comment by chenyigg** [comment]
> 你的项目类型是什么？
Sorry, I didn't understand what you meant. I am using community open source

**Comment by maliming** [comment]
You can upload a demo project to Github.

**Comment by chenyigg** [comment]
> 您可以将演示项目上传到 Github。

Okay, if there is any follow-up, I will consult you again，thank you
