### ISSUE TITLE
How to override exception message to respone from ABP farmework

### ISSUE THREAD

**Issue by manojkrsna** [abpframework/abp#16893]
How to override exception message to respone through ABP farmework  commonly

Have tried the things which is in below link but it was only to read. Please help here.

https://docs.abp.io/en/abp/latest/Exception-Handling#subscribing-to-the-exceptions

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.ExceptionHandling/Volo/Abp/AspNetCore/ExceptionHandling/IExceptionToErrorInfoConverter.cs#L10

**Comment by manojkrsna** [comment]
Do we get any example of using the interface IExceptionToErrorInfoConverter

**Comment by berkansasmaz** [comment]
Just override the relevant localization strings.

For example, for internal server error message, you need to override `InternalServerErrorMessage` localization string. You can find the relevant localization keys [here](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.ExceptionHandling/Volo/Abp/AspNetCore/ExceptionHandling/DefaultExceptionToErrorInfoConverter.cs).

**Comment by manojkrsna** [comment]
I tried with below code and the exception is not going through this class. My requirement not to just change localization string , need to change few things here



    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IExceptionToErrorInfoConverter), typeof(DefaultExceptionToErrorInfoConverter), typeof(CustomExceptionToErrorInfoConverter))]
    public class CustomExceptionToErrorInfoConverter : DefaultExceptionToErrorInfoConverter
    {
     // CODE
     }

**Comment by manojkrsna** [comment]
It worked when i made below changes

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IExceptionToErrorInfoConverter), typeof(DefaultExceptionToErrorInfoConverter), typeof(CustomExceptionToErrorInfoConverter))]
public class CustomExceptionToErrorInfoConverter : DefaultExceptionToErrorInfoConverter
{
   // Code
}


**to**



public class CustomExceptionToErrorInfoConverter : : IExceptionToErrorInfoConverter, ITransientDependency
{
   // Code
}


Please explain why is it so, this should work with Dependency and ExposeServices Attributes right and this is working with out those?

**Comment by berkansasmaz** [comment]
Glad it worked after recent changes 🥳

In response to your question, the code that shows how to override an example method like the one below should work.
```csharp
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(DefaultExceptionToErrorInfoConverter), typeof(IExceptionToErrorInfoConverter))]
public class CustomExceptionToErrorInfoConverter : DefaultExceptionToErrorInfoConverter
{

    protected override RemoteServiceErrorInfo CreateErrorInfoWithoutCode(Exception exception, AbpExceptionHandlingOptions options)
    {
        // code
    }

}
```


--- 

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
