### ISSUE TITLE
How to change table prefix on apb framework?

### ISSUE THREAD

**Issue by buif** [abpframework/abp#1690]
I tried to with code in OnModelCreating mothod: 
```
builder.ConfigurePermissionManagement("");
builder.ConfigureSettingManagement("");
builder.ConfigureBackgroundJobs(options =>
{
    options.TablePrefix = "";
});
builder.ConfigureAuditLogging("");
builder.ConfigureIdentity(options =>
{
    options.TablePrefix = "";
});
builder.ConfigureIdentityServer();
builder.ConfigureFeatureManagement(options =>
{
    options.TablePrefix = "";
});
builder.ConfigureTenantManagement("");
```
Result: database table name changed as I want, but when I tried to run my site, i get error:

SqlException: Invalid object name 'AbpSettings'.
System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__122_0(Task<SqlDataReader> result)

SqlException: Invalid object name 'AbpSettings'.
......
Could you please help me resolve this issue?
Thank so much!

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/1387#issuecomment-506645119
