### ISSUE TITLE
Failed to Login v0.19.0

### ISSUE THREAD

**Issue by nebiyout** [abpframework/abp#1693]
Hi there,
Failed to login to the console.

![LogInError](https://user-images.githubusercontent.com/5265204/63856998-905b3d80-c9ab-11e9-8f84-0440037cd8e4.PNG)

![LogInErrorConsole](https://user-images.githubusercontent.com/5265204/63857035-a406a400-c9ab-11e9-8816-4a3fd249222b.PNG)

and the second issue:- "MyApplication Portal" doesn't route to the login page. https://localhost:44373/

**Comment by maliming** [comment]
What are the steps to reproduce your problem?

**Comment by godrunner** [comment]
I have the same problem here. Just following the getting started steps on with a brand new download of the Angular template from the "Create New Project" wizard. (Useing SQL Server)
https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template

I had a quick look and there is nothing in the AbpUsers users table. 
Maybe a seed method didn't run?

BTW, there is an errors on that page that references a project name that is not there, under this section:
https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template#using-ef-core-update-database-command
- There is no .web project. It appears that should be HttpApi.Host

**Comment by maliming** [comment]
I can log in according to the documentation. Can't reproduce your problem.


> I had a quick look and there is nothing in the AbpUsers users table.
Maybe a seed method didn't run?

**Using the .Migrator tool is the suggested way, because it also seeds the initial data to be able to properly run the web application.**

![image](https://user-images.githubusercontent.com/6908465/64302269-36630500-cfb5-11e9-8954-25238ee229e4.png)

**Comment by godrunner** [comment]
> **Using the .Migrator tool is the suggested way, because it also seeds the initial data to be able to properly run the web application.**

Ok, thanks @maliming . That works.
I am used to Asp.Net Zero. :)

**Comment by maliming** [comment]
: )
