### ISSUE TITLE
How to use different DTO for CREATE and UPDATE/EDIT?

### ISSUE THREAD

**Issue by SaeedSpate** [abpframework/abp#1694]
I'm using different **DTO** for `create` and `update/edit`, when i tried to update/edit, get this error:
 ```
{
  "error": {
    "code": null,
    "message": "An internal error occurred during your request!",
    "details": null,
    "validationErrors": null
  }
}
```
so added `[Required(AllowEmptyStrings = true)]` to any optional fields and get validation error `The field is required.`.

InterfaceService code:
```
public interface ITrackingService : ICrudAppService<TrackingDto, Guid, PagedAndSortedResultRequestDto, CreateTrackingDto, UpdateTrackingDto>
{
}
```

AppSerivce code:
```
public class TrackingAppService : CrudAppService<Tracking, TrackingDto, Guid, PagedAndSortedResultRequestDto, CreateUpdateTrackingDto, CreateUpdateTrackingDto>, ITrackingService
{
	public TrackingAppService(IRepository<Tracking, Guid> repository) : base(repository)
	{
	}
}
```

**Any problem in my code?**

**Comment by maliming** [comment]
> An internal error occurred during your request!

What is the detailed error message?

Please share the code of the DTO class and the content of the http request.

**Comment by SaeedSpate** [comment]
> What is the detailed error message?

> Not any more details!

DTO code:
```
public class TrackingDto : FullAuditedEntityDto<Guid>
{
	public bool IsActive { get; set; }
	public string Number { get; set; }

	public ICollection<ClientInfoDto> ClientInfo { get; set; } = new HashSet<ClientInfoDto>();
}
```

I tried to update `ClientInfo` but get an error **code 500**!

```
{
  "error": {
    "code": null,
    "message": "An internal error occurred during your request!",
    "details": null,
    "validationErrors": null
  }
}
```

**Comment by maliming** [comment]
Detailed error messages exist in the application's log file.

At the same time you can refer to this issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4817#issuecomment-525596501

**Comment by SaeedSpate** [comment]
Do you mean override 

> Detailed error messages exist in the application's log file.
> 
> At the same time you can refer to this issue [aspnetboilerplate/aspnetboilerplate#4817 (comment)](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4817#issuecomment-525596501)

Do you mean override update method in AppService?

**Comment by maliming** [comment]
> Do you mean override update method in AppService?

Yes, you can try.

**Comment by SaeedSpate** [comment]
@maliming 
Can you please tell me how to override Update method?
Any DI is required?

**Comment by GFoley83** [comment]
Sounds like you haven't configured your mappings correctly. Nothing to do with ABP. This is a question for StackOverflow.

**Comment by SaeedSpate** [comment]
> Sounds like you haven't configured your mappings correctly. Nothing to do with ABP. This is a question for StackOverflow.

All DTO mapped to ENTITY, and `Add and Update` currently worked, but part of query result is work without nested!
I think needed to override `GeltListAsync` method in `AppService` class, and i don'n know how to override query inside of method.

**Comment by SaeedSpate** [comment]
@GFoley83 @maliming 
This problem solved by override `GetListAsync` method in AppService!

Usage:
```
public override Task<PagedResultDto<TrackingInfoDto>> GetListAsync(PagedAndSortedResultRequestDto input)
{
	var trackingInfo = MapToGetOutputDto(Repository.AsNoTracking().Include(x => x.ClientInfo).ToList());
	PagedResultDto<TrackingInfoDto> pageResult = new PagedResultDto<TrackingInfoDto>();
	pageResult.Items = trackingInfo.As<IReadOnlyList<TrackingInfoDto>>();
	return Task.FromResult(pageResult);
}

private object MapToGetOutputDto(List<TrackingInfo> list)
{
	return ObjectMapper.Map<List<TrackingInfo>, List<TrackingInfoDto>>(list);
}
```
