### ISSUE TITLE
Blazor WASM template ignores theme.css

### ISSUE THREAD

**Issue by Robert-Laverick** [abpframework/abp#16942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Blazor WASM template has a static global.css and global.js file which are already minified and difficult to modify that are included in the page. These files include all the CSS and JavaScript needed for the basic theme. This means that if you make changes to the theme (by importing it and making changes to theme.css) they have no effect as the included theme css file isn't used. 

Also I think this means that updates to includes such as blazorise won't apply updates to CSS files (or I'm guessing JS changes too?) when library updates as they are frozen in these combined minified files which don't seem to be getting rebuilt when I build the app in visual studio.

### Reproduction Steps

abp new PowerOptions2 -u blazor --separate-identity-server --theme basic --pwa -csf

abp add-package Volo.Abp.Identity.Blazor.WebAssembly --with-source-code --add-to-solution-file
abp add-package Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme --with-source-code --add-to-solution-file
abp add-package Volo.Abp.AspNetCore.Components.Web.BasicTheme --with-source-code --add-to-solution-file

Edit the theme.css in Volo.Abp.AspNetCore.Components.Web.BasicTheme/wwwroot/libs/abp/css/theme.css

### Expected behavior

Changes to theme.css reflected in pages

### Actual behavior

No changes are reflected

### Version

7.2.2

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
See: https://docs.abp.io/en/abp/latest/CLI#bundle

**Comment by Robert-Laverick** [comment]
Sorry I totally missed that! It's a shame that's not part of the build in visual studio, but thanks for pointing it out. 

Maybe it could be added as a pre-build action in the .sln?
