### ISSUE TITLE
 _virtualFileProvider.GetDirectoryContents("") not returning all files

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1695]
@hikalkan @maliming 

As requested I am creating a seperate issue where I am not getting all the files from all fileProviders when I call 

` _virtualFileProvider.GetDirectoryContents("")` or  `_virtualFileProvider.GetDirectoryContents("/")`

I am only getting the Physical Files. Please see below screenshot which shows the values of the variable `dir` which is declared as follows by my calculations there should you **336** files returned not **17**

`IDirectoryContents dir =  _virtualFileProvider.GetDirectoryContents("");`

<img width="1680" alt="Screen Shot 2019-08-29 at 2 21 35 pm" src="https://user-images.githubusercontent.com/15242923/63910156-ee9a2600-ca68-11e9-9c88-8e13c48595ae.png">

As far as i can tell from the below the `return new CompositeFileProvider(fileProviders);` which is returned by the `CreateHybridProvider(IDynamicFileProvider dynamicFileProvider)` method is doing the right thing.

Shouldn't the `GetDirectoryContents` method I am calling cycle through all the fileProviders and return all the files not just the `PhysicalFileProvider`

public class VirtualFileProvider : IVirtualFileProvider, ISingletonDependency
    {
        private readonly IFileProvider _hybridFileProvider;
        private readonly VirtualFileSystemOptions _options;

        public VirtualFileProvider(
            IOptions<VirtualFileSystemOptions> options,
            IDynamicFileProvider dynamicFileProvider)
        {
            _options = options.Value;
            _hybridFileProvider = CreateHybridProvider(dynamicFileProvider);
        }

        public virtual IFileInfo GetFileInfo(string subpath)
        {
            return _hybridFileProvider.GetFileInfo(subpath);
        }

        public virtual IDirectoryContents GetDirectoryContents(string subpath)
        {
            return _hybridFileProvider.GetDirectoryContents(subpath);
        }

        public virtual IChangeToken Watch(string filter)
        {
            return _hybridFileProvider.Watch(filter);
        }

        protected virtual IFileProvider CreateHybridProvider(IDynamicFileProvider dynamicFileProvider)
        {
            var fileProviders = new List<IFileProvider>();

            fileProviders.Add(dynamicFileProvider);

            if (_options.FileSets.PhysicalPaths.Any())
            {
                fileProviders.AddRange(
                    _options.FileSets.PhysicalPaths
                        .Select(rootPath => new PhysicalFileProvider(rootPath))
                        .Reverse()
                );
            }

            fileProviders.Add(new InternalVirtualFileProvider(_options));

            return new CompositeFileProvider(fileProviders);
        }

        protected class InternalVirtualFileProvider : DictionaryBasedFileProvider
        {
            protected override IDictionary<string, IFileInfo> Files => _files.Value;

            private readonly VirtualFileSystemOptions _options;
            private readonly Lazy<Dictionary<string, IFileInfo>> _files;

            public InternalVirtualFileProvider(VirtualFileSystemOptions options)
            {
                _options = options;
                _files = new Lazy<Dictionary<string, IFileInfo>>(
                    CreateFiles,
                    true
                );
            }
            
            private Dictionary<string, IFileInfo> CreateFiles()
            {
                var files = new Dictionary<string, IFileInfo>(StringComparer.OrdinalIgnoreCase);

                foreach (var set in _options.FileSets)
                {
                    set.AddFiles(files);
                }

                return files;
            }

            protected override string NormalizePath(string subpath)
            {
                return VirtualFilePathHelper.NormalizePath(subpath);
            }
        }
    }

**Comment by maliming** [comment]
I will check it out.

**Comment by vnetonline** [comment]
not sure what you mean can you let me know how i should change and then i can test it locally

**Comment by vnetonline** [comment]
@maliming not sure what you mean can you let me know how i should change and then i can test it locally

**Comment by vnetonline** [comment]
@hikalkan @maliming 

so is this a bug??

**Comment by maliming** [comment]
I am not sure, please wait for the view of hikalkan.

**Comment by vnetonline** [comment]
@hikalkan any idea why I can’t get all directory contents

**Comment by SphinxGraph** [comment]
I think I'm having a related issue on my side:

1. The files in my wwwroot-directory:
![cldr-data-main-de](https://user-images.githubusercontent.com/7882753/71591467-bd238b00-2b2c-11ea-9a8c-c7345811ed7d.png)

2. The files are known to the `Volo.Abp.VirtualFileSystem.VirtualFileProvider.InternalVirtualFileProvider` that's used by the formerly known hybrid file provider.
![files-in-virtual-file-provider](https://user-images.githubusercontent.com/7882753/71591468-bd238b00-2b2c-11ea-9759-f48a97aae909.png)

3. The files aren't returned by the `GetDirectoryContents`-Method.
![files-not-being-returned](https://user-images.githubusercontent.com/7882753/71591466-bc8af480-2b2c-11ea-967b-b595a6990b91.png)

**Comment by maliming** [comment]
hi @SphinxGraph Try **IWebContentFileProvider**.

**Comment by SphinxGraph** [comment]
Hi @maliming, unfortunately the **IWebContentFileProvider** doesn't work either.
`Exists` returns true, but still no results inside the enumeration.

**Comment by maliming** [comment]
@SphinxGraph 
I can get the list of files
![image](https://user-images.githubusercontent.com/6908465/71713918-ac358b00-2e46-11ea-8b2d-3fc6b6dfe9b2.png)

**Comment by SphinxGraph** [comment]
Hi @maliming,

thanks for your checking. But I still can't get it working. I've tried to use backslashes (as shown in your screenshot) instead of slashes but this doesn't work either.

Could it be, that this approach doesn't work if I'm using the `IWebContentFileProvider` inside a class library project? The wwwroot directory (and it's children) are configured as embedded resource. I've attached my project setup:
![grafik](https://user-images.githubusercontent.com/7882753/71715118-9b6a2280-2e10-11ea-9833-923c2d5c73b4.png)

The `GetFileInfo` method works, if the file name is known. But I want to dynamically iterate the directories depending on the locales (see watch **1**).

It's weird that your `GetDirectoryContents` function call returned something with a trailing backslash and in my example this doesn't return anything (see watch **2** and **3**):
![grafik](https://user-images.githubusercontent.com/7882753/71715153-b89ef100-2e10-11ea-93dd-2fa6714f60e1.png)

**Comment by maliming** [comment]
hi @SphinxGraph 
Can you provide a project that reproduces the problem?

**Comment by SphinxGraph** [comment]
Hi @maliming,

I've created a project based on the default cli app template and added a module `MyModule` that contains the example code. You can check out the project under https://github.com/SphinxGraph/AbpIssue1695

**Comment by maliming** [comment]
hi @SphinxGraph 

```
var de = _virtualFileProvider.GetDirectoryContents("/wwwroot/themes/mytheme/cldr_data/main/de");
var files = de.ToList();
```

![image](https://user-images.githubusercontent.com/6908465/71797438-19386300-3089-11ea-99b8-46ce63fd9a39.png)

**Comment by SphinxGraph** [comment]
Hi @maliming,

thanks for your example. The underscore really killed me, but it works now as intended.
