### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dzunglesi** [abpframework/abp#16956]
Error: node_modules/@volo/abp.ng.account/public/components/two-factor-tab/two-factor-tab.component.d.ts:3:10 - error TS2305: Module '"@abp/ng.core"' has no exported member 'AbpWindowService'.
3 import { AbpWindowService } from '@abp/ng.core';

**Comment by gerryge** [comment]
The same issue:
abp version: 7.3.0-rc.2
angular startup template project!!!
![image](https://github.com/abpframework/abp/assets/6952917/9539a856-c81e-4f59-b8c7-bc4bb322b225)

**Comment by masum-ulu** [comment]
Hi @dzunglesi @gerryge sorry for that here's the [PR](https://github.com/abpframework/abp/pull/16908). It's merged after rc.2 published. It will be fixed at final
