### ISSUE TITLE
Angular - Pages work incorrectly and there is an error in the console

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#16950]
**App:** Angular - MongoDb  `7.3-rc.2`
**Command:** `abp new Angular.MoongoSeperate210623Free   -t app -u angular -m none --separate-identity-server --database-provider mongodb -csf  --version 7.3.0-rc.2`
![Apex_1687507060886-_2_ (1)](https://github.com/abpframework/abp/assets/99716457/7c425f9d-c887-4386-8418-bd8a6231cb1e)

**Comment by masum-ulu** [comment]
This is internal bug at LeptonX
