### ISSUE TITLE
Do not expose integration services and controllers by default

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#16961]
Integration services and controllers should not be exposed by default for security reasons. They typically don't require authorization, so we should **carefully and explicitly** allow them to be visible and usable to client applications.

Hiding integration services is useful when you are building reusable application modules, where they may be used in a monolith application or in a microservice system. In a monolith application, integration services don't need to be exposed outside since the modules may in-process communicate with each other. On the other hand, if you build a microservice solution and use that module as a service, it will be proper to expose the integration services, so other microservices can consume them remotely inside your private network (or Kubernetes cluster). In that case, be careful to not accidently expose the integration services out of your private network. Configuring your API Gateway so that it blocks requests to `integration-api` prefixed URLs from outside of your network will be a good option.

To expose integration services and controllers, set `AbpAspNetCoreMvcOptions.ExposeIntegrationServices` to `true` in the `ConfigureServices` method of your [module class](Module-Development-Basics.md):

````csharp
Configure<AbpAspNetCoreMvcOptions>(options =>
{
    options.ExposeIntegrationServices = true;
});
````

**Comment by gdlcf88** [comment]
Thanks to this change, we can now create controller classes for integration services in modules. 🌹
