### ISSUE TITLE
How to configure AbpEmailingModule to use NullEmailSender?

### ISSUE THREAD

**Issue by GFoley83** [abpframework/abp#1696]
I'm injecting `AbpEmailingModule` into my module but I'm unsure of how to set `IEmailSender` to `NullEmailSender`.

Any help is much appreciated.

**Comment by maliming** [comment]
Try use `services.Replace` under `ConfigureServices` method. 

```
services.Replace(ServiceDescriptor.Singleton<IEmailSender, NullEmailSender>());
```

**Comment by GFoley83** [comment]
I thought I'd already tried that but clear not as it worked a treat. Thanks so much!
