### ISSUE TITLE
Why DistributedCache uses a SemaphoreSlim to lock resource

### ISSUE THREAD

**Issue by zhangzunke** [abpframework/abp#16984]
I looked at the DistributedCache source code, I found DistributedCache's GetOrAddAsync method uses SyncSemaphore to lock resource, I am not sure why use SyncSemaphore to lock a resource before write value to cache.

DistributedCache is registered as a singleton, that means only one request can be handled at same time when we use GetOrAddAsync approach to write cache, because of the code SyncSemaphore = new SemaphoreSlim(1, 1) in the constructor, so other requests will wait for until the resource is released, I suspect that will have a performance issue, maybe I am wrong.

It's a great if someone can explain the design purpose.

**Comment by gterdem** [comment]
In case you may be using multiple instances of the application that uses the DistributedCache.

**Comment by zhangzunke** [comment]
> In case you may be using multiple instances of the application that uses the DistributedCache.

Sorry, @gterdem Could you give me more detail explanation for your comment, you mean the design is just for multiple instances of the application. 
If I have a scenario as below:
If I want to cache user's basial information in the Redis, the Redis key should be "User_" + user.id, the cache value should be user information, if there are two request comes from client hit same instance concurrently, user B request need to wait for the user A request complete when useing GetOrAddAsync method, that was my understand according to current code logic, please correct me if I ignore some of important points, Thanks.

@maliming

**Comment by maliming** [comment]
> DistributedCache is registered as a singleton, that means only one request can be handled at same time when we use GetOrAddAsync approach to write cache

I don't think so. Singletons should always consider thread safety.

**Comment by zhangzunke** [comment]
> > DistributedCache is registered as a singleton, that means only one request can be handled at same time when we use GetOrAddAsync approach to write cache
> 
> I don't think so. Singletons should always consider thread safety.

So the design purpose is to prevent multiple thread to save value to Redis at the same time, Can I understand the purpose of this design in this way?

**Comment by gerryge** [comment]
@zhangzunke 
The `SemaphoreSlim(1, 1)` in `DistributedCache` creates a semaphore to allow only one thread access to a shared resource, thus achieving thread-safety for the GetOrAddAsync method. The semaphore is used to prevent race conditions when trying to add a new item to the cache. Without this lock, multiple threads could perform the Get operation, fail to find the cached item, and then attempt to write the new value to the cache simultaneously. To avoid adding multiple computed results to the cache, it's essential to ensure that only one thread can execute the "set" logic at a time.

While using the semaphore restricts concurrent access to the shared resource, that restriction applies mainly when the data has not been loaded into the cache yet. When multiple requests access the `GetOrAddAsync` method concurrently, the role of the `SyncSemaphore` is to ensure that only one thread executes data loading when multiple requests attempt to load the same data not yet in the cache. Once the data is loaded into the cache, concurrent access to the `GetOrAddAsync` method will not be constrained by the semaphore. At this point, the semaphore will not hinder other requests, and performance when handling multiple requests simultaneously will increase.

In summary, using a semaphore to limit concurrent access to shared resources indeed introduces some performance costs, but this is necessary in the trade-off for computing and writing the data into the cache. The design intent is to allow only one thread to compute data and write it to the cache when the data is not yet cached and to reduce duplicate computations and simultaneously writing conflicts. The goal of the design is to provide safe access to resources, so its performance costs are generally acceptable in real-world scenarios when the data is already loaded into the cache.

PS:
`DistributedCache` 中的 `SemaphoreSlim(1, 1)` 创建了一个信号量，允许有一个线程访问共享资源，以实现 GetOrAddAsync 方法的线程安全。此信号量用于防止在尝试向缓存中添加新项时的竞态条件。如果没有这个锁，多个线程可能会执行 Get 操作，同时找不到缓存项，并尝试将新的值同时写入缓存。为了避免向缓存添加多个计算出的结果，需要首先确保同一时间只有一个线程可以执行“设置”逻辑。

虽然使用信号量会限制共享资源的并发访问，但是这个限制主要是在数据还未加载到缓存时才生效的。 在多个请求同时访问 `GetOrAddAsync` 方法时，`SyncSemaphore` 的作用是确保当多个请求同时尝试加载同一个尚未缓存的数据时，仅有一个线程执行数据加载以减少不必要的计算和写入操作。当数据已被加载到缓存时，并发访问`GetOrAddAsync` 方法将不受信号量的限制。 此时，当缓存被命中时，信号量不会阻碍其他请求，并且同时处理多个请求的性能会得到提高。

总之，使用信号量限制对共享资源的并发访问确实会引入一些性能成本，但这是在权衡计算和写入缓存中的数据时所必需的。设计目的是在数据尚未缓存时只允许一个线程计算数据并写入缓存，减少重复计算和同时写入冲突。这种设计的目标是对资源访问进行安全保护，因此当数据已加载到缓存时，其性能问题在实际应用中通常可以接受。

**Comment by zhangzunke** [comment]
@gerryge Thanks for your comprehensive explain.
