### ISSUE TITLE
The error `Tenant not found` is a bug

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#17022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a new tenant and then change the tenant to this new tenant on the login page, I get the following error.

```
Tenant not found!
There is no tenant with the tenant id or name: xxx
```

### Reproduction Steps

<ol>
<li>Create a project through the abp cli and run it.</li>
<li>Use a browser to access the project and create a new tenant on the Create Tenant page or through swagger's associated interface.</li>
<li>Access the Login page '/Account/Login' using another browser or using the traceless mode of your current browser.</li>
<li>Change the tenant to a newly created tenant.</li>
</ol>

### Expected behavior

Tenant change succeeded.

### Actual behavior

Tenant change failure.

### Known Workarounds

In `TenantStore`, when determining whether the tenant cache item is empty, the value of the tenant cache item is empty.
Of course, I'm not sure if the same is needed for `FeatureManagementStore`, `PermissionStore` and `SettingManagementStore`.

### Version

6.0.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

Modify the code in TenantStore.

```
if (cacheItem != null)
```
to
```
if (cacheItem != null && cacheItem.Value != null)
```

**Comment by maliming** [comment]
I can't reproduce your problem.

This can only happen if the cache is accidentally modified or removed.

**Comment by ArcherTrister** [comment]
> I can't reproduce your problem.
> 
> This can only happen if the cache is accidentally modified or removed.

Sorry, This should be due to my development environment causing this error, it worked on my colleague's browser, but it didn't work on mine, and the cookie didn't write the tenant's value after I switched to a new tenant.

![image](https://github.com/abpframework/abp/assets/35516482/5ae8ddb7-689e-4cd2-abfc-7851b531f970)
