### ISSUE TITLE
Build fails after 7.2.3 release

### ISSUE THREAD

**Issue by payoff** [abpframework/abp#17024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the host project reference to 
`    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX" Version="2.2.*-*" />`
that requires MultiTenant 7.2.3.
With 7.2.2 solution the project fails for a package downgrade. 

Fix requires to set exact version:
  `  <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX" Version="2.2.1-*" />`
Regards

### Version

7.2.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Using the correct Lepton version will solve the problem, thank you.
