### ISSUE TITLE
Consider hold current page when reloading data on datatable.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#17029]
https://support.abp.io/QA/Questions/5355/Paging-issue-after-update-any-record

https://datatables.net/reference/api/ajax.reload()

> Reset (default action or true) or hold the current paging position (false). A full re-sort and re-filter is performed when this method is called, which is why the pagination reset is the default action.

`ajax.reload(null, false);` will keep the hold page.

----

Angular has the same behavior.

**Comment by maliming** [comment]
I will do that for abp&volo if you are agreed.

**Comment by ebicoglu** [comment]
the current page and the order fields must be persisted.
