### ISSUE TITLE
Please consider use alternative keys with GUID type for each abp entity

### ISSUE THREAD

**Issue by SergeyLimonov** [abpframework/abp#1704]
It would be better if most of entities like AbpUser, AbpTenant, AbpRole and so on will contains alternative key UID with GUID type. It's very difficult to create an application using microservices architecture or scalable (with data sharding) application using autogenerated from sequence value as a primary key. And if auth token will contains user and tenant GUIDs instead of long or int ID then it will be possible to use same auth token to authenticate on different our microservices. Thanks.

**Comment by hikalkan** [comment]
Ids are already Guid in the Identity & Tenant Management modules. We don't use sequential int/long ids anymore with this new ABP framework by default (but you can use it for your own entities if you like).
