### ISSUE TITLE
After successful forgot password changing process return to application button is not working.

### ISSUE THREAD

**Issue by bugrayus** [abpframework/abp#17044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After successful forgot password changing process return to application button is not working.

error:invalid_request
error_description:The mandatory 'response_type' parameter is missing.
error_uri:https://documentation.openiddict.com/errors/ID2029

showing this error

my opinion is 
https://localhost:44390/Account/ResetPassword?userId=757c54d1-9a00-f1d5-51be-3a0c37e92cb5&__tenant=&resetToken=CfDJ8AKltf8vMRxOnR2i96xd4o%2FrQJ824rNRmhOcHYmPHGAQ3d7%2FKZeeTr8IVSNElMGBP9J7d%2FW9YJR3ABP93KAHchlaCC5raZ5NMcUaSg7q9VQmi89FjsaRlDvO2Wio7Otwc1u44eZ%2BWfbeB5RnR%2FBaj%2B700saK6qhHm2zd5ExyRzllgt6jJfn5Zb3hMJ8UoojpjP%2F%2BNLFNJLM5eHi%2BxBnfkoT1ydqStgr6etDIpUWD2mJg&returnUrl=/connect/authorize?client_id=HaliPratik_App&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Foidc-callback&response_type=code&scope=offline_access%20openid%20profile%20email%20phone%20HaliPratik&state=025698f221ac494ea7d3f10d81ecb53e&code_challenge=anK9RxJm8Hpi-6REDEQCEPrb3ynv4y5q6iuIYr0yZZQ&code_challenge_method=S256&response_mode=query
 this url does not see after returnUrl=/connect/authorize?client_id=HaliPratik_App& part because & operator

### Reproduction Steps

after creating new project and configuring mail settings when you try to change password using forgot password 
![image](https://github.com/abpframework/abp/assets/57290623/52643a55-613e-43e9-8119-4b16d1d39c7f)
this button redirects you to application but its not working.

### Expected behavior

i should be redirected to my application properly

### Version

7.2.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Is this a commercial project?

**Comment by maliming** [comment]
The `ResetPassword` url is below. 


```
<body>
    <h3>Password reset</h3>
    
    <p>We received an account recovery request! If you initiated this request, click the following link to reset your password.</p>
    
    <div>
        <a href="https://localhost:44303/Account/ResetPassword?userId=620ba47f-a731-88f8-8eba-3a0c3b52cce5&__tenant=&resetToken=CfDJ8AHOwjA8TaBJmeKXg71nsbKt%2B11TzHT9peVDEICOUc45hCGJ%2FMf5QI3kp8h2d20kG7qF4DvAdZ7i2UEmKaTCCnJo4bFW5o%2F6rEmP8SZ4GdrN9GBCdof7xb5%2BdITUFgj1IS%2BX0WsW2W4aKdNerfhuL7Zw3b1CIj0w3s8j8ycj7tqyhC12q4QvcMliBuZsmQyB7AOhqrcoRFuswT%2FHPnMc%2BTEBs4q1Pkav6NT%2F8vtdQmb2">Reset my password</a>
    </div>
</body>
```

**Comment by bugrayus** [comment]
> hi
> 
> 
> 
> Is this a commercial project?

No abp framework

**Comment by bugrayus** [comment]
> The `ResetPassword` url is below. 
> 
> 
> 
> 
> 
> ```
> 
> <body>
> 
>     <h3>Password reset</h3>
> 
>     
> 
>     <p>We received an account recovery request! If you initiated this request, click the following link to reset your password.</p>
> 
>     
> 
>     <div>
> 
>         <a href="https://localhost:44303/Account/ResetPassword?userId=620ba47f-a731-88f8-8eba-3a0c3b52cce5&__tenant=&resetToken=CfDJ8AHOwjA8TaBJmeKXg71nsbKt%2B11TzHT9peVDEICOUc45hCGJ%2FMf5QI3kp8h2d20kG7qF4DvAdZ7i2UEmKaTCCnJo4bFW5o%2F6rEmP8SZ4GdrN9GBCdof7xb5%2BdITUFgj1IS%2BX0WsW2W4aKdNerfhuL7Zw3b1CIj0w3s8j8ycj7tqyhC12q4QvcMliBuZsmQyB7AOhqrcoRFuswT%2FHPnMc%2BTEBs4q1Pkav6NT%2F8vtdQmb2">Reset my password</a>
> 
>     </div>
> 
> </body>
> 
> ```

This url might be right but when everything is done password is changed and click go back to application its not working

**Comment by maliming** [comment]
Please share the details steps. Thanks.

**Comment by bugrayus** [comment]
> Please share the details steps. Thanks.

Create new abp framework using abp new MyProject -u angular

Define your db source in appsettings and migrate.

Define mail settings using google and delete NullEmailSender so you can really send forgot password mail.

Create new user with your mail.

Then click forgot password and change your password using link from mail.

After changing your password successfully click go to application button which appears in You seccessfully changed your password phrase.

Go to application button is not working properly.
