### ISSUE TITLE
The page is not rendered after successful login in Angular

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#17061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When update to 7.2.3,if add the AuthGuard in entry page as below
![image](https://github.com/abpframework/abp/assets/16984534/aeb07acb-d0aa-4a8e-ad15-d4af2b84e5e7)
after login in success but page is not rendered and url without `?iss=`

In 7.2.2 it works well,the redirect url is `http://localhost:4200/?iss=https:%2F%2Flocalhost:44373%2F`..

I noticed that the `angular-oauth2-oidc` package is not updated. So is this problem caused by abp removing the `iss `parameter?

### Version

7.2.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1213

**Comment by xxvolvo** [comment]
#16592  affected by this Issue? @mahmut-gundogdu

**Comment by xxvolvo** [comment]
This problem is also reproduced in 7.3.0-RC3, can someone help me deal with this issue?

**Comment by mahmut-gundogdu** [comment]
Could you describe the issue with more detail? Is there any error on screen or is it  fully white ?

you are using codeflow or password owner flow ? what is the test steps ?

**Comment by xxvolvo** [comment]
1、create a new project  with angular UI
2、add the `AuthGuard` to home route like below
![image](https://github.com/abpframework/abp/assets/16984534/290df12e-5d90-40e3-97a0-353980f2e99b)
3、login and or relogin ,then the redirect page is empty. only request some global requests 
![image](https://github.com/abpframework/abp/assets/16984534/7bb0b68f-324a-4095-82de-86a8fd8abec3)

![image](https://github.com/abpframework/abp/assets/16984534/db7e011c-778d-4bd5-8cf7-a1d656d1245a)


It works well in 7.2.2

**Comment by mahmut-gundogdu** [comment]
After the angular 15. Guard class removed. It must be function.
you can see https://github.com/angular/angular/issues/50234

**Comment by xxvolvo** [comment]
Thx，but i notice that both `7.2.1`,`7.2.2`,`7.2.3` are both under  angular 15.Is this not a direct cause?
In #16592 ，it seems to work well. So,what change caused this issue？

**Comment by xxvolvo** [comment]
> Thx，but i notice that both `7.2.1`,`7.2.2`,`7.2.3` are both under angular 15.Is this not a direct cause? In #16592 ，it seems to work well. So,what change caused this issue？

`AuthGuard` used from `@abp/ng.core`

**Comment by xxvolvo** [comment]
Update：
1、In this line [Line 58](https://github.dev/abpframework/abp/blob/9628bf3deb19ec0987276c2196139c74833e1ddc/npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts#L58)，if replace with `this.getLayout()`. This problem will be solved.
2、In this line [Line 1766](https://github.dev/manfredsteyer/angular-oauth2-oidc/blob/3ba7303b5a6fdbae5ca214764c9191637cd00126/projects/lib/src/oauth-service.ts#L1766),if replace with `location.replaceState`. This problem will be solved.

**Comment by masum-ulu** [comment]
Hi @xxvolvo,
The problem was about the dynamic-layout component, when you pass AuthGuard for home page it's not render the layout, we've checked and solved this problem I'll drop the PR when open

**Comment by HDaoud** [comment]
Hello, I am having this issue with v7.4 commercial, what should I do to fix it?
