### ISSUE TITLE
How to switch language?

### ISSUE THREAD

**Issue by NajibbUllah** [abpframework/abp#17065]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

I have created a project by using **"abp new Acme.BookStore -u angular --separate-identity-server --theme basic -csf "** which contains angular and .net core projects. I have integrated my own angular template in the Basic theme provided by abp instead of using the basic theme.
I want to switch the language English to Turkish for example, for that I have populated available languages in a dropdown. So how do I implement this functionality.

For reference, on click a language following API is being called **"https://localhost:44370/api/abp/application-localization?cultureName=ar&onlyDynamics=false"**. I do call the same api on my populated list of languages button click but nothing happens.

**Comment by mahmut-gundogdu** [comment]
what is your ui? Angular, jquery , blazor ... ?

**Comment by mahmut-gundogdu** [comment]
The session-state service is responsible for storing language settings.  If you want to change language, you should mutate the key 'localization.currentCulture.cultureName' in config.service. 

https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/services/session-state.service.ts

**Comment by NajibbUllah** [comment]
Thank you! I got it.
