### ISSUE TITLE
Add a new feature along with Email settings to the Setting Management in Tenant Features

### ISSUE THREAD

**Issue by parthiban23** [abpframework/abp#17070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi,

I wanted to add a new feature in the Tenant in the Manage Feature. I tried to add the code here.

Please refer the attachment. I got the below link,
https://docs.abp.io/en/abp/latest/Modules/Feature-Management

But is it possible to add a feature with the existing code.

 private static void ConfigureExtraProperties()
    {

        ObjectExtensionManager.Instance.Modules()
          .ConfigureTenantManagement(tenantConfig =>
          {
              tenantConfig.ConfigureTenant(t =>
              {

              });
          });
}
![251783649-d891d30f-1a0f-43ba-860f-9726b3ec1277](https://github.com/abpframework/abp/assets/6650940/aafd07da-5975-4ef4-b599-4953f3c8cd0b)

### Describe the solution you'd like

Hi,

I wanted to add a new feature in the Tenant in the Manage Feature. I tried to add the code here.

Please refer the attachment. I got the below link,
https://docs.abp.io/en/abp/latest/Modules/Feature-Management

But is it possible to add a feature with the existing code.

 private static void ConfigureExtraProperties()
    {

        ObjectExtensionManager.Instance.Modules()
          .ConfigureTenantManagement(tenantConfig =>
          {
              tenantConfig.ConfigureTenant(t =>
              {

              });
          });
}

### Additional context

Hi,

I wanted to add a new feature in the Tenant in the Manage Feature. I tried to add the code here.

Please refer the attachment. I got the below link,
https://docs.abp.io/en/abp/latest/Modules/Feature-Management

But is it possible to add a feature with the existing code.

 private static void ConfigureExtraProperties()
    {

        ObjectExtensionManager.Instance.Modules()
          .ConfigureTenantManagement(tenantConfig =>
          {
              tenantConfig.ConfigureTenant(t =>
              {

              });
          });
}

**Comment by maliming** [comment]
Same with https://github.com/abpframework/abp/issues/17069#issuecomment-1627258949
