### ISSUE TITLE
wpf

### ISSUE THREAD

**Issue by ygr757326** [abpframework/abp#17073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/abpframework/abp/assets/42167347/2288b627-efe2-4a57-9918-dfc0c4fc7fed)

### Version

7.2.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Try to clear the download cache and recreate the project.

```
abp clear-download-cache
```
