### ISSUE TITLE
post error in swagger when use http mode

### ISSUE THREAD

**Issue by terius** [abpframework/abp#17076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When my abp's swagger is in http mode, any post or delete or update request will cause error like "The required antiforgery header value "RequestVerificationToken" is not present.", but Get request is ok, 
when my swagger site is set to https, everything is ok, this error looks like js cannot get XSRF-TOKEN in http mode, how to solve this problem? Thank you so much!

![image](https://github.com/abpframework/abp/assets/7608809/5b2af6a1-f080-4623-91a3-4ee77606e5e4)
![image](https://github.com/abpframework/abp/assets/7608809/08d80c7c-5cd2-483a-b71b-499bda907bc9)
![9JQ_C_3CHV6YDQ`1TGB6D2Y](https://github.com/abpframework/abp/assets/7608809/6a46f823-407f-4cd4-8e72-a5adaff1aa46)

### Version

7.0.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> this error looks like js cannot get XSRF-TOKEN in http mode, how to solve this problem? Thank you so much!

You can check this cookie in your browser dev tools.

**Comment by terius** [comment]
the request SetCsrfCookie is response  XSRF-TOKEN,bu can not get it
![image](https://github.com/abpframework/abp/assets/7608809/930a56ae-7e71-4df8-b50a-079044834bb5)

Is Http method can not support get XSRF-TOKEN??

**Comment by terius** [comment]
![image](https://github.com/abpframework/abp/assets/7608809/d572acb2-b1d8-4511-858a-8f3969f40a39)

**Comment by maliming** [comment]
> Is Http method can not support get XSRF-TOKEN??

This is browser(chrome) behavior.

**Comment by terius** [comment]
I just downloaded the 7.0.1 version of the abp project (site:https://www.abp.io/get-started) and compiled it successfully and initialized the database. 
The default site (including AuthServer) is https://localhost:44353. any request is ok in swagger(after I requested authorization  it can response XSRF-TOKEN ), 
but when I changed the site to http://localhost:44353 in project, clearing the cookie in the browser, and requesting authorization (request page: http://localhost:44353/connect/token), 
I found that XSRF-TOKEN cookie was not returned, 
and then any request except get request will cause  400 error (The required antiforgery header value "RequestVerificationToken" is not present). 
Does this mean that swagger in ABP cannot run in http mode?I really want to know where the source of the problem is, ABP or browser or openiddict? 
I just started using abp framework, thank you very much~

**Comment by maliming** [comment]
> but when I changed the site to http://localhost:44353/ in project, clearing the cookie in the browser, and requesting authorization (request page: http://localhost:44353/connect/token),
I found that XSRF-TOKEN cookie was not returned,

The cookies maybe block by browser(chrome), Please check the console.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/14089
