### ISSUE TITLE
AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Basic.Global'!

### ISSUE THREAD

**Issue by ZihHengMa** [abpframework/abp#17081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/abpframework/abp/assets/67789449/f830f3da-5d8a-4425-a84a-8be9fa8c7cfe)
I have tried to use abp install-libs with ABP CLI 7.2.3, however this problem still shows up when I try to follow the tutorial ACME.BookStore.

### Version

7.2.3

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by salihozkara** [comment]
Use the abp install-libs command (it won't work if you don't have Yarn, install yarn first)
https://docs.abp.io/en/abp/7.2/UI%2FAspNetCore%2FClient-Side-Package-Management#install-libs-command

**Comment by ZihHengMa** [comment]
I have yarn in my system
![image](https://github.com/abpframework/abp/assets/67789449/582344ee-4131-4343-a4c6-1e9f1eac7d4e)

**Comment by salihozkara** [comment]
Did the abp install-libs command work?

**Comment by ZihHengMa** [comment]
yap it still does not work for me, i have tried to use the command in the root of the project and in Acme.BookStore.Web folder

**Comment by salihozkara** [comment]
Did it give any error?

**Comment by salihozkara** [comment]
I'm closing the issue because there is no return
