### ISSUE TITLE
ABP 7.3.0 new project build fails due to (missing) references to Microsoft.EntityFrameworkCore 7.0.9

### ISSUE THREAD

**Issue by malfaitbart** [abpframework/abp#17100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi

after createing a new solution using the CLI (version 7.3.0), I receive an error due to missing references to Microsoft.EntityFrameworkCore & Microsoft.EntityFrameworkCore.Relational 7.0.9.

A manual installation in the domain and entityframework project fixes this.

Can you add the references in the template?

### Version

7.3.0

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
What was your create command? `abp new ...`

**Comment by malfaitbart** [comment]
abp new Bookstore -u blazor --theme basic --pwa -csf

**Comment by maliming** [comment]
I can't reproduce it.

**Comment by malfaitbart** [comment]
Just had another try and it is my fault :(
First action i did was update all nuget packages. If i run the dbmigrator after the nuget update, i get the errors.

Was a bit to fast in createing the issue.

My appologies
