### ISSUE TITLE
After login redirect to home page, the url contains iss parameter:http://localhost:4200/?iss=https:%2F%2Flocalhost:44328%2F

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#17106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After login redirect to home page, the url contains iss parameter:
http://localhost:4200/?iss=https:%2F%2Flocalhost:44328%2F

This issue exsit in both free and pro templates.
![url-issue](https://github.com/abpframework/abp/assets/6952917/78e7f2f6-0d21-4848-af50-622ca575945e)

### Reproduction Steps

1. abp new Acme.BookStore -u angular -csf true
2. run the projects and login

### Expected behavior

After login redirect to home page, the url shouldn't contains the iss parameter:
http://localhost:4200/

### Actual behavior

http://localhost:4200/?iss=https:%2F%2Flocalhost:44328%2F

### Regression?

Yes, It works correctly in V7.2.3.

### Version

7.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by masum-ulu** [comment]
Hi @gerryge it's not a bug actually it's related with [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc) package. There is an issue for this situation [check issue](https://github.com/manfredsteyer/angular-oauth2-oidc/issues/1213) if it's not merge i'll find another way to improve current situtation.

It comes after [RFC 9207](https://datatracker.ietf.org/doc/rfc9207/)

**Comment by HDaoud** [comment]
Hello @masumulu28, I am running ABP v7.4 commercial and the problem exists. Is there anything that can be done to resolve the issue?
