### ISSUE TITLE
Rename AbpSettingDefinitionRecords table

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#17101]
Please rename `AbpSettingDefinitionRecords` table to `AbpSettingDefinitions`, which is shorter. No need to use the `Record` suffix, we didn't use it anywhere before. This will need to recreate or add migrations, but it would be better to do it know, otherwise it will be a breaking change.

**Comment by maliming** [comment]
> we didn't use it anywhere before


<img width="670" alt="image" src="https://github.com/abpframework/abp/assets/6908465/b390462d-f21d-49a5-a32e-f01ae81eead4">

**Comment by hikalkan** [comment]
I mean at the database table name, sorry for misunderstanding. These entities have no "Records" suffix in database table names. Do not change the entity/class name.
