### ISSUE TITLE
How to upgrade to v7.3.0 from v7.2.2

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#17115]
While I upgrade my project use `abp update`，it can only upgrade to v7.2.3, not v7.3.0. What's wrong with it?
![uTools_1689299938520](https://github.com/abpframework/abp/assets/24971860/79892ffa-b0f2-43c8-a2ad-898b1d130375)

**Comment by EngincanV** [comment]
Hi, [this PR](https://github.com/abpframework/abp/pull/17098) needed to be merged and it has merged just before. So, when you retry again you should be able to upgrade your application version to v7.3.0.

![image](https://github.com/abpframework/abp/assets/43685404/d93f45f9-76df-406f-9904-c485678eec82)

**Comment by weiwxg** [comment]
> Hi, [this PR](https://github.com/abpframework/abp/pull/17098) needed to be merged and it has merged just before. So, when you retry again you should be able to upgrade your application version to v7.3.0.
> 
> ![image](https://user-images.githubusercontent.com/43685404/253480337-d93f45f9-76df-406f-9904-c485678eec82.png)

Great, thanks!
