### ISSUE TITLE
after upgrading to 7.3.0 the multitenant stopped working.

### ISSUE THREAD

**Issue by wenceslaoleon** [abpframework/abp#17123]
[AllowAnonymous]
        public override async Task<PagedResultDto<ComplaintTypeDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            //Get the IQueryable<Book> from the repository
            var queryable = await Repository.WithDetailsAsync(); // this line changed

            //Paging
            var query = queryable            
              .OrderBy(input.Sorting)
              .Skip(input.SkipCount)
              .Take(input.MaxResultCount);

            //Execute the query and get a list
            var queryResult = await AsyncExecuter.ToListAsync(query);

            //Convert the query result to a list of ComplaintTypeDto objects
            var complaintTypeDtos = queryResult.Select(x =>
            {
                var complaintTypeDto = ObjectMapper.Map<ComplaintType, ComplaintTypeDto>(x);
                return complaintTypeDto;
            }).ToList();

            //Get the total count with another query
            var totalCount = await Repository.GetCountAsync();

            return new PagedResultDto<ComplaintTypeDto>(
                totalCount,
                complaintTypeDtos
            );
        }

**Comment by maliming** [comment]
hi

Can you explain it in more detail?

**Comment by wenceslaoleon** [comment]
With the previous version, filtering was automatically done by the active tenant by default. Now, with the new version, I have to add the filter.

        [AllowAnonymous]
        public override async Task<PagedResultDto<ComplaintTypeDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            //Get the IQueryable<Book> from the repository
            var queryable = await Repository.WithDetailsAsync(); // this line changed

            //Paging

            var query = from complaintType in queryable
                        where complaintType.TenantId == _currentTenant.Id.Value
                        orderby input.Sorting
                        select complaintType;

            var filteredQuery = query
                .Skip(input.SkipCount)
                .Take(input.MaxResultCount);

            //Execute the query and get a list
            var queryResult = await AsyncExecuter.ToListAsync(filteredQuery);

            //Convert the query result to a list of ComplaintTypeDto objects
            var complaintTypeDtos = queryResult.Select(x =>
            {
                var complaintTypeDto = ObjectMapper.Map<ComplaintType, ComplaintTypeDto>(x);
                return complaintTypeDto;
            }).ToList();

            //Get the total count with another query
            var totalCount = queryResult.Count;

            return new PagedResultDto<ComplaintTypeDto>(
                totalCount,
                complaintTypeDtos
            );
        }

**Comment by maliming** [comment]
hi

Can you share a simple project to reproduce? Thanks

**Comment by wenceslaoleon** [comment]
[https://mgticl-my.sharepoint.com/:u:/g/personal/wenceslao_leon_mgti_cl/EWZP4l52zblLnv1ZqmSTXYcBsAgFTBadObzpeZjQ0U9j7w?e=3ofRvN](url)

**Comment by wenceslaoleon** [comment]
[](https://mgticl-my.sharepoint.com/:u:/g/personal/wenceslao_leon_mgti_cl/EWZP4l52zblLnv1ZqmSTXYcBsAgFTBadObzpeZjQ0U9j7w?e=3ofRvN)

**Comment by wenceslaoleon** [comment]
[Test.MultiTenant.zip](https://github.com/abpframework/abp/files/12071939/Test.MultiTenant.zip)

**Comment by maliming** [comment]
Remove the `b.HasQueryFilter(x => !x.IsDeleted);` and override the `ConfigureGlobalFilters` method of `AbpDbContext` to add additional filter.

**Comment by wenceslaoleon** [comment]
And how do I do so that it does not show the deleted items?
what do you mean by override the ConfigureGlobalFilters, in the previous version everything worked correctly.

**Comment by maliming** [comment]
```cs
protected override void ConfigureGlobalFilters<TEntity>(ModelBuilder modelBuilder, IMutableEntityType mutableEntityType)
{
    if (typeof(ComplaintType) is TEntity)
    {
        if (mutableEntityType.BaseType == null && ShouldFilterEntity< ComplaintType >(mutableEntityType))
        {
            var filterExpression = CreateFilterExpression<ComplaintType>();
            if (filterExpression != null)
            {
                Expression<Func<ComplaintType, bool>> myFilter = e => !e.IsDeleted;
                modelBuilder.Entity<ComplaintType>().HasQueryFilter(CombineExpressions(filterExpression, myFilter));
                return;
            }
        }
    }

    base.ConfigureGlobalFilters<TEntity>(modelBuilder, mutableEntityType);
}
```

This `x => !x.IsDeleted` is similar to `SoftDeleteFilter` btw.

**Comment by maliming** [comment]
I will improvement this case. I mean to support the `b.HasQueryFilter` in `ConfigureGlobalFilters` method.

**Comment by wenceslaoleon** [comment]
ok, but I still have the problem that it is not filtering by the tenant, I have to explicitly filter by the _currentTenant.Id.Value, when in the previous version I didn't have to do it.

        //Get the IQueryable<Book> from the repository
        var queryable = await Repository.WithDetailsAsync(); // this line changed

        //Paging

        var query = from complaintType in queryable
                    where complaintType.TenantId == _currentTenant.Id.Value
                    orderby input.Sorting
                    select complaintType;

**Comment by maliming** [comment]
I can't reproduce. Make sure you had remove the `b.HasQueryFilter(x => !x.IsDeleted);`.

**Comment by wenceslaoleon** [comment]
is ok. thank.
