### ISSUE TITLE
Optimization: ABP Default Converters (AbpStringToGuidConverter & AbpNullableStringToGuidConverter) Have Performance Impact Nearly a Hundred Times Higher Than Native Converters

### ISSUE THREAD

**Issue by nankingcigar** [abpframework/abp#17124]
### Description

I encountered performance issues when retrieving a large amount of people-related data (approximately 30MB) through a new interface. The execution time from the 'Executing ObjectResult' to the 'Executed' action took more than 3 seconds on my local environment, leading me to suspect serialization as the cause. To address this, I reconfigured the JsonOptions in the HttpApiHostModule. Upon retesting the API, I observed a significant improvement, with the execution time reduced to less than 1 second, possibly around 100ms or even less.

During my investigation, I focused on the AbpStringToGuidConverter and AbpNullableStringToGuidConverter Write Methods, which were triggered by the data. After reviewing the code of these converters in ABP 7.3.0, I concluded that they might be responsible for the performance issue. To verify this, I performed a test by copying the AbpStringToGuidConverter code into AbpStringToGuidConverter2 and AbpStringToGuidConverter3, respectively. By measuring the average number of ticks using a stopwatch, I found that AbpStringToGuidConverter2 took around 100 ticks on average, whereas AbpStringToGuidConverter3 only took 1 tick on average.

Please note that the suggested optimization is subjective, and you can adjust it further based on your preferred style and context.

public class AbpStringToGuidConverter2 : JsonConverter<Guid>
    {
        private JsonSerializerOptions _writeJsonSerializerOptions;

        public override Guid Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.String)
            {
                var guidString = reader.GetString();
                string[] formats = { "N", "D", "B", "P", "X" };
                foreach (var format in formats)
                {
                    if (Guid.TryParseExact(guidString, format, out var guid))
                    {
                        return guid;
                    }
                }
            }

            return reader.GetGuid();
        }

        public override void Write(Utf8JsonWriter writer, Guid value, JsonSerializerOptions options)
        {
            Stopwatch sw = Stopwatch.StartNew();
            _writeJsonSerializerOptions ??= JsonSerializerOptionsHelper.Create(options, this);
            var entityConverter = (JsonConverter<Guid>)_writeJsonSerializerOptions.GetConverter(typeof(Guid));

            entityConverter.Write(writer, value, _writeJsonSerializerOptions);
            sw.Stop();
            Console.WriteLine(sw.ElapsedTicks + " ticks");
        }
    }

public class AbpStringToGuidConverter3 : JsonConverter<Guid>
    {
        private JsonSerializerOptions _writeJsonSerializerOptions;

        public override Guid Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.String)
            {
                var guidString = reader.GetString();
                string[] formats = { "N", "D", "B", "P", "X" };
                foreach (var format in formats)
                {
                    if (Guid.TryParseExact(guidString, format, out var guid))
                    {
                        return guid;
                    }
                }
            }

            return reader.GetGuid();
        }

        public override void Write(Utf8JsonWriter writer, Guid value, JsonSerializerOptions options)
        {
            Stopwatch sw = Stopwatch.StartNew();
            writer.WriteStringValue(value);
            sw.Stop();
            Console.WriteLine(sw.ElapsedTicks + " ticks");
        }
    }

### Configuration

context.Services.AddOptions<JsonOptions>()
            .Configure<IServiceProvider>((options, rootServiceProvider) =>
            {
                options.JsonSerializerOptions.Converters.Clear();
                //options.JsonSerializerOptions.Converters.Add(new AbpStringToEnumFactory());
                //options.JsonSerializerOptions.Converters.Add(new AbpStringToBooleanConverter());
                //options.JsonSerializerOptions.Converters.Add(new AbpStringToGuidConverter());
                //options.JsonSerializerOptions.Converters.Add(new AbpNullableStringToGuidConverter());
                options.JsonSerializerOptions.Converters.Add(new ObjectToInferredTypesConverter());
            });

### Analysis
Upon further reflection, I have noticed that the performance issue may be related to the process of obtaining the converter. Specifically, when examining the AbpStringToGuidConverter, I found the following lines of code:

```csharp
_writeJsonSerializerOptions ??= JsonSerializerOptionsHelper.Create(options, this);
var entityConverter = (JsonConverter<Guid>)_writeJsonSerializerOptions.GetConverter(typeof(Guid));
```

It appears that the converter is obtained using `_writeJsonSerializerOptions.GetConverter(typeof(Guid))`. While this may not be noticeable with a small number of calls, it can become problematic with a large number of calls, especially when ABP recommends using GUID as the primary key. In such cases, data nesting can have a catastrophic impact on performance.

I want to clarify that these observations are based on my personal research. I hope that by sharing this information, I can assist others who are experiencing similar issues. It's important to conduct more in-depth investigations to fully understand and address the performance problem.

**Comment by maliming** [comment]
hi

Please share the test data of `a large amount of people-related data (approximately 30MB)`.

**Comment by nankingcigar** [comment]
[response.zip](https://github.com/abpframework/abp/files/12063409/response.zip)


> hi
> 
> Please share the test data of `a large amount of people-related data (approximately 30MB)`.

Please see attach zip

**Comment by maliming** [comment]
Please also share the class definition. or your test app. :)

**Comment by nankingcigar** [comment]
> Please also share the class definition. or your test app. :)

[aspnet-core.zip](https://github.com/abpframework/abp/files/12064157/aspnet-core.zip)
Please see attach zip. 
![image](https://github.com/abpframework/abp/assets/9410343/f73305eb-582a-4c55-a506-980168e43c82)

**Comment by maliming** [comment]
Here is my test code. I didn't got obvious performance issues.

https://gist.github.com/maliming/7ab15800f66bd12b8f67564e0624ce30

**Comment by nankingcigar** [comment]
> Here is my test code. I didn't got obvious performance issues.
> 
> https://gist.github.com/maliming/7ab15800f66bd12b8f67564e0624ce30
Hi @maliming,

Your test is wrong. You misunderstand me. It's converter write method issue. Your test is converting json text to object list.
You never do another test converting object list to json text.  I add code as below:
var peoplesDto = JsonSerializer.Deserialize<ApiResponse<IEnumerable<PeopleDto>>>(json, new JsonSerializerOptions(JsonSerializerDefaults.Web));
var sss2 = JsonSerializer.Serialize(peoplesDto);

var peoplesDto2 = abpJsonSerializer.Deserialize<ApiResponse<IEnumerable<PeopleDto>>>(json);
var sss = abpJsonSerializer.Serialize(peoplesDto2);

Please rerun it you would found the performance issue,

using Microsoft.Extensions.DependencyInjection;
using System.Diagnostics;
using System.Text.Json;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Json.SystemTextJson;
using Volo.Abp.Modularity;

var json = await File.ReadAllTextAsync("response.json");

var stopWatch = new Stopwatch();

stopWatch.Start();
var peoplesDto = JsonSerializer.Deserialize<ApiResponse<IEnumerable<PeopleDto>>>(json, new JsonSerializerOptions(JsonSerializerDefaults.Web));
var sss2 = JsonSerializer.Serialize(peoplesDto);
stopWatch.Stop();
Console.WriteLine($"Deserialize: {stopWatch.ElapsedMilliseconds} ms");

return 0;

using (var application = AbpApplicationFactory.Create<AppModule>())
{
    application.Services.Configure<AbpSystemTextJsonSerializerOptions>(options =>
    {
        //options.JsonSerializerOptions.Converters.Clear();
    });

    application.Services.Configure<AbpSystemTextJsonSerializerModifiersOptions>(options =>
    {
        //options.Modifiers.Clear();
    });

    await application.InitializeAsync();
    var abpJsonSerializer = application.ServiceProvider.GetRequiredService<AbpSystemTextJsonSerializer>();

    stopWatch.Restart();
    var peoplesDto2 = abpJsonSerializer.Deserialize<ApiResponse<IEnumerable<PeopleDto>>>(json);
    var sss = abpJsonSerializer.Serialize(peoplesDto2);
    stopWatch.Stop();
    Console.WriteLine($"Deserialize: {stopWatch.ElapsedMilliseconds} ms");
}

return 0;

public class AdministrativePositionLevelDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class ApiResponse<TResult>
{
    public ApiResponse(TResult result)
    {
        Result = result;
    }

    public bool __chao { get; } = true;
    public TResult Result { get; set; }
    public bool Success { get; } = true;
}

[DependsOn(typeof(AbpJsonSystemTextJsonModule))]
public class AppModule : AbpModule
{
}

public class AreaDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class GenderDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class OrganizationCategoryDto : EntityDto<Guid>
{
    public virtual string Name { get; set; }
}

public class OrganizationDto : EntityDto<Guid>
{
    public virtual bool? Administration { get; set; }
    public virtual AreaDto Area { get; set; }
    public virtual Guid? AreaId { get; set; }
    public virtual IEnumerable<OrganizationDto> Children { get; protected set; }
    public virtual string Code { get; set; }
    public virtual bool? College { get; set; }
    public virtual bool? Department { get; set; }
    public virtual string Designation { get; set; }
    public virtual long? EnableEndDate { get; set; }
    public virtual long? EnableStartDate { get; set; }
    public virtual string EnglishName { get; set; }
    public virtual string Name { get; set; }
    public virtual float Order { get; set; }
    public virtual OrganizationCategoryDto OrganizationCategory { get; set; }
    public virtual Guid? OrganizationCategoryId { get; set; }
    public virtual Guid? ParentId { get; set; }
    public virtual string ShortName { get; set; }
    public virtual bool Virtual { get; set; }
}

public class PeopleDto : EntityDto<Guid>
{
    public virtual OrganizationDto AdministrativeOrganization { get; set; }
    public virtual Guid AdministrativeOrganizationId { get; set; }
    public virtual AdministrativePositionLevelDto AdministrativePositionLevel { get; set; }
    public virtual Guid? AdministrativePositionLevelId { get; set; }
    public virtual string AdministrativePositionTitle { get; set; }
    public virtual AreaDto Area { get; set; }
    public virtual Guid? AreaId { get; set; }
    public virtual OrganizationDto BusinessOrganization { get; set; }
    public virtual Guid? BusinessOrganizationId { get; set; }
    public virtual string CardId { get; set; }
    public virtual OrganizationDto Department { get; set; }
    public virtual Guid? DepartmentId { get; set; }
    public virtual string Email { get; set; }
    public virtual long? ExpirationDate { get; set; }
    public virtual string FullName { get; set; }
    public virtual GenderDto Gender { get; set; }
    public virtual Guid? GenderId { get; set; }
    public virtual string Phone { get; set; }
    public virtual string Phone2 { get; set; }
    public virtual string PhysicalCardId { get; set; }
    public virtual PositionCategoryDto PositionCategory { get; set; }
    public virtual Guid? PositionCategoryId { get; set; }
    public virtual ProfessionalPositionDto ProfessionalPosition { get; set; }
    public virtual Guid? ProfessionalPositionId { get; set; }
    public virtual IEnumerable<RoleDto> Roles { get; set; }
    public virtual string TeacherId { get; set; }
    public virtual UserStatusDto UserStatus { get; set; }
    public virtual Guid? UserStatusId { get; set; }
    public virtual UserTagDto UserTag { get; set; }
    public virtual Guid? UserTagId { get; set; }
    public virtual UserTypeDto UserType { get; set; }
    public virtual Guid? UserTypeId { get; set; }
}

public class PositionCategoryDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class ProfessionalPositionDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
    public virtual ProfessionalPositionLevelDto ProfessionalPositionLevel { get; set; }
    public virtual Guid? ProfessionalPositionLevelId { get; set; }
}

public class ProfessionalPositionLevelDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class RoleDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class UserStatusDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class UserTagDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

public class UserTypeDto : EntityDto<Guid>
{
    public virtual string Code { get; set; }
    public virtual string Name { get; set; }
}

**Comment by maliming** [comment]
Please share the console app.

**Comment by nankingcigar** [comment]
Hi @maliming 
Add a test gif, hopelly it would be helpful. ConsoleApp1.zip is a test program based on your code. I noticed that the API returns DTOs data in about 5-6 seconds on my local machine. After examining the log file, I observed that the business logic itself only takes 1-2 seconds, which includes retrieving data from SQL Server and mapping it to DTOs. However, from the log keyword 'Executing ObjectResult,' it seems that most of the time is spent on converting the object list into JSON text and returning it. To address this, I looked into the source code for version 7.3.0 of SystemTextJson and found some converters such as AbpStringToGuidConverter and AbpNullableStringToGuidConverter. I decided to remove these converters and retested the API, which significantly improved its performance. To verify this, I conducted a simple comparative experiment and recorded the elapsed time using a Stopwatch instead of milliseconds. Typically, with small amounts of data, we might not notice this performance gap. However, when dealing with large amounts of data, the repeated invocation of these converter write methods becomes a major performance bottleneck. 
I apologize if raising this performance issue causes any inconvenience. If it does, please feel free to ignore it.
![Animation](https://github.com/abpframework/abp/assets/9410343/edaa8f3e-9ab9-47cf-b483-051e2733b4c5)
[ConsoleApp1.zip](https://github.com/abpframework/abp/files/12066348/ConsoleApp1.zip)

**Comment by maliming** [comment]
You can remove and add the new converter for now.

https://github.com/abpframework/abp/pull/17128
