### ISSUE TITLE
Why import Ef Dbcontext in Volo.Abp.Dapper

### ISSUE THREAD

**Issue by bidianqing** [abpframework/abp#1713]
in my opinion,use Dapper so easy 
https://github.com/bidianqing/oneaspnet.repository/tree/master/src/OneAspNet.Repository.Dapper

**Comment by maliming** [comment]
Because we need Dapper to work with the unit of work.   For example, using unit of work connections and transactions.

see: https://github.com/abpframework/abp/blob/dev/docs/en/Dapper.md
