### ISSUE TITLE
Why creator id not be set for multi tenant?

### ISSUE THREAD

**Issue by qq362220083** [abpframework/abp#17149]
We use abp vnext v7.x, and custom tenant logic.

But, we found entity has no creator id.

We found `AuditPropertySetter` has check entity tenant id logic.

:clown_face: Can you tell us why, thanks. 🚀 🚀 🚀 

https://github.com/abpframework/abp/blob/9628bf3deb19ec0987276c2196139c74833e1ddc/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditPropertySetter.cs#L70-L76

**Comment by muhlisatac** [comment]
X tenant user is not belongs to Y tenant. As a Y tenant admin what would you do if you saw a creatorId that is not belongs to Y tenant?

**Comment by qq362220083** [comment]
> X tenant user is not belongs to Y tenant. As a Y tenant admin what would you do if you saw a creatorId that is not belongs to Y tenant?

Yeah, I see, you are right. Thank you👍 

We will replace AuditPropertySetter. 😄
