### ISSUE TITLE
Can config map function with DI

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#1714]
The most common way is config map in profile class. But how can I create dynamic map which I can get ServiceProvider during the map

**Comment by maliming** [comment]
Do you want to use dependency injection in Automapper's Profile class?

**Comment by Goxiaoy** [comment]
@maliming Yes, or somwhere else I can difine map function with DI envolved

**Comment by maliming** [comment]
Try the following code:

```
public class BookStoreApplicationModule : AbpModule
{
	public override void ConfigureServices(ServiceConfigurationContext context)
	{
		Configure<AbpAutoMapperOptions>(options =>
		{
			options.Configurators.Add(abpAutoMapperConfigurationContext =>
			{
				var bookStoreApplicationAutoMapperProfile = abpAutoMapperConfigurationContext.ServiceProvider
					.GetRequiredService<BookStoreApplicationAutoMapperProfile>();

				abpAutoMapperConfigurationContext.MapperConfiguration.AddProfile(
					bookStoreApplicationAutoMapperProfile);
			});

		});
	}
}

public class BookStoreApplicationAutoMapperProfile : Profile, ISingletonDependency
{
	//example service
	private readonly IHttpContextAccessor _contextAccessor;
	
	public BookStoreApplicationAutoMapperProfile(IHttpContextAccessor contextAccessor)
	{
		_contextAccessor = contextAccessor;

		/* You can configure your AutoMapper mapping configuration here.
		 * Alternatively, you can split your mapping configurations
		 * into multiple profile classes for a better organization. */
	}
}
```

**Comment by Goxiaoy** [comment]
So the Profile is defined as singleton. And If I want to get a scope or transist object, I have to inject IHttpContextAccessor and get object by ```_contextAccessor.HttpContext.RequestServices.GetRequiredService<T>()``` ?

**Comment by maliming** [comment]
This is just a simple example.

**Comment by Goxiaoy** [comment]
I am creating a feature MultiLingual like the [aspnetboilerplate](https://aspnetboilerplate.com/Pages/Documents/Multi-Lingual-Entities) do. So I need to get `ISettingProvider ` during the map to get the default language setting whichimplements ITransientDependency. The ServiceProvider define in IAbpAutoMapperConfigurationContext is only available during the application initialize. So if I  want to resolve a transist object, I can only resolve a singleton object like IHttpContextAccessor and the get the ServiceProvider from HttpContext or I should use `IHybridServiceScopeFactory` ?
