### ISSUE TITLE
AddAudiances() method name mismatch in doc and code 

### ISSUE THREAD

**Issue by Sahulhameed9094** [abpframework/abp#17150]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

![image](https://github.com/abpframework/abp/assets/30176312/71b2ea0f-09bb-479a-a6ba-3c72a9c37e19)

![image](https://github.com/abpframework/abp/assets/30176312/ba421324-9eff-4072-8983-40e18b27cf10)

**Comment by maliming** [comment]
hi

We will mention many methods in the docs, but may not provide complete parameters in it.

**Comment by Sahulhameed9094** [comment]
@maliming  sorry we have some miscommunication, In my code I have AddAudi**e**nces(), but document showing as  AddAudi**a**nces() . when i try to search  AddAudiences() in [openiddictvalidationbuilder](https://docs.abp.io/en/abp/latest/Modules/OpenIddict#openiddictvalidationbuilder) its not showing. due to spelling mismatch AddAudi**e**nces() != AddAudi**a**nces()  not same.

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/pull/17154
