### ISSUE TITLE
Can't resolve '@abp/ng.theme.lepton-x'

### ISSUE THREAD

**Issue by MortenWernberg** [abpframework/abp#17157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I ran the following cmd to create my abp project:
abp new VisionAiGeotabConnector -u angular -dbms PostgreSQL --theme basic

Then I installed angular packages with:
npm install --shamefully-hoist

and build with
npm start

I get the following build error:
./src/app/app.module.ts:8:0-60 - Error: Module not found: Error: Can't resolve '@abp/ng.theme.lepton-x' in 'C:\Users\modum\Documents\GitRepoClones\VisionAiGeotabConnector\angular\src\app'

### Reproduction Steps

I ran the following cmd to create my abp project:
abp new VisionAiGeotabConnector -u angular -dbms PostgreSQL --theme basic

Then I installed angular packages with:
npm install --shamefully-hoist

and build with
npm start

I get the following build error:
./src/app/app.module.ts:8:0-60 - Error: Module not found: Error: Can't resolve '@abp/ng.theme.lepton-x' in 'C:\Users\modum\Documents\GitRepoClones\VisionAiGeotabConnector\angular\src\app'

### Expected behavior

Angular project builds successfully.

### Actual behavior

Build error

### Version

ABP CLI 7.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by MortenWernberg** [comment]
Running npm i @abp/ng.theme.lepton-x fixes the issue. It themes it is a problem with the package dependencies...

**Comment by AhmedBoody** [comment]
@MortenWernberg  I have the same issue I tried to run the command `npm i @abp/ng.theme.lepton-x `
 but still got the same error
for reference: https://github.com/abpframework/abp/issues/17228

**Comment by rashedjawda** [comment]
Hi Ahmed 
@AhmedBoody 

Did you find a solution to this issue ?

**Comment by masum-ulu** [comment]
Hi all,

It must configure angular.json & app.module.ts file for theme-basic because of your --theme parameter. It seems like it's not create correct I've created an issue I'll check for now if you configure your file like below it'll fixed


## app.module.ts

```ts
// import { ThemeLeptonXModule } from '@abp/ng.theme.lepton-x'; Remove this
import { ThemeBasicModule } from '@abp/ng.theme.basic'; // Add this

@NgModule({
  imports: [
    //ThemeLeptonXModule.forRoot(), Remove this
    ThemeBasicModule.forRoot(),// Add this 
  ],
})
export class AppModule {}
```

## angular.json
Configure styles array like below
```json
"styles": [
  {
    "input": "node_modules/@fortawesome/fontawesome-free/css/all.min.css",
    "inject": true,
    "bundleName": "fontawesome-all.min"
  },
  {
    "input": "node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css",
    "inject": true,
    "bundleName": "fontawesome-v4-shims.min"
  },
  {
    "input": "node_modules/@swimlane/ngx-datatable/index.css",
    "inject": true,
    "bundleName": "ngx-datatable-index"
  },
  {
    "input": "node_modules/@swimlane/ngx-datatable/assets/icons.css",
    "inject": true,
    "bundleName": "ngx-datatable-icons"
  },
  {
    "input": "node_modules/@swimlane/ngx-datatable/themes/material.css",
    "inject": true,
    "bundleName": "ngx-datatable-material"
  },
  {
    "input": "node_modules/bootstrap/dist/css/bootstrap.rtl.min.css",
    "inject": false,
    "bundleName": "bootstrap-rtl.min"
  },
  {
    "input": "node_modules/bootstrap/dist/css/bootstrap.min.css",
    "inject": true,
    "bundleName": "bootstrap-ltr.min"
  },
  "src/styles.scss"
],
```

**Comment by rashedjawda** [comment]
Thanks @masumulu28 
but what about this line 

`import { AccountLayoutModule } from '@volosoft/abp.ng.theme.lepton-x/account'; `

**in app.module.ts**

it still reference lepton-x

**Comment by masum-ulu** [comment]
> Thanks @masumulu28 but what about this line
> 
> `import { AccountLayoutModule } from '@volosoft/abp.ng.theme.lepton-x/account'; `
> 
> **in app.module.ts**
> 
> it still reference lepton-x

Hi please remove all import from lepton-x package
