### ISSUE TITLE
Admin login failed at localhost Blazor Server 

### ISSUE THREAD

**Issue by kali2rk** [abpframework/abp#17169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I face login in admin login after follow step at : **abp new BQ.Project -u blazor-server -csf**   using VS2022
there is any password beside : '1q2w3e*', even i tried using ADMIN , still failed
![image](https://github.com/abpframework/abp/assets/4215058/a61f3e97-b80a-4e43-b4cb-e34a7d8a2615)

The seed data populate at sql server. 

### Version

7.30

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by kali2rk** [comment]
at console log: 
![image](https://github.com/abpframework/abp/assets/4215058/ad140688-20bf-499d-9e36-06405d3f14c7)

**Comment by masoodkhoshgard** [comment]
Hi @kali2rk  
Default password is: **1q2w3E***
you enter 1q2w3e*

E is uppercase

**Comment by kali2rk** [comment]
@masoodkhoshgard Thank you 
it working
