### ISSUE TITLE
Angular library in Module template fails to build on production.

### ISSUE THREAD

**Issue by mgochmuradov** [abpframework/abp#17161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Running Angular application works as expected but building library on production fails in the ABP Module template

### Reproduction Steps

- abp new Payhas -t module --version 7.3.0
- update `projects\payhas\src\lib\components\payhas.component.ts` set template: ` <p [ngClass]="{'screen-x-small': true}">payhas works!</p> `
- yarn build

### Expected behavior

Library project build successfully

### Actual behavior

Build fails with following exception:
```
✖ Compiling with Angular sources in Ivy partial compilation mode.
projects/payhas/src/lib/components/payhas.component.ts:6:18 - error NG8002: Can't bind to 'ngClass' since it isn't a known property of 'p'.

6   template: ` <p [ngClass]="{'screen-x-small': true}">payhas works!</p> `,
```

### Regression?

Yes, it was working on previous versions.

### Known Workarounds

The solution is to add `"ng-packagr": "^16.0.0",` package.
```
yarn add --dev ng-packagr
```

It took almost half a day for me to figure out what was the problem.
And after I had added this package everything started to build.

Please add this package back to the template, so other people don't waste their time.

### Version

7.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by masum-ulu** [comment]
It seems like this package added in `8.0` version. I'm closing this issue. If the same problem still exits please re-open this I'll check again

https://github.com/abpframework/abp/blob/rel-8.0/templates/module/angular/package.json#L59
