### ISSUE TITLE
Http status code 405 when deploy project in the IIS or Linux

### ISSUE THREAD

**Issue by diennttlu** [abpframework/abp#17176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/abpframework/abp/assets/36124566/84be62f8-9dec-4eb4-9bbd-564266fac8a6)

I have deployed the project to IIS and Linux. When requesting from client to server, it does not allow POST, PUT, DELETE  methods

### Version

6.0.0.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Linux

**Comment by maliming** [comment]
https://mozartec.com/asp-net-core-error-405-methods-not-allowed-for-put-and-delete-requests-when-hosted-on-iis/

**Comment by diennttlu** [comment]
this is my web.config: 
```
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
	 <modules runAllManagedModulesForAllRequests="false">
		<remove name="WebDAVModule" />
	  </modules>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\WebMaster.HttpApi.Host.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
```
it isn't success: 
![image](https://github.com/abpframework/abp/assets/36124566/ddd4c442-bd61-4b67-8ade-270eab570fdb)

**Comment by maliming** [comment]
Check your logs.txt for the new error. It is a CROS problem.

**Comment by diennttlu** [comment]
the server has not started so the log.txt file does not exist

**Comment by diennttlu** [comment]
I'm checked the log file. no error found
