### ISSUE TITLE
7.3.0 commercial Angular  openiddict  module edit modal show error log  

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#17170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when update to7.3.0 commercial, click the edit button in openiddict  module,the console log as below
![image](https://github.com/abpframework/abp/assets/16984534/a341ee7d-5fb5-4ed3-821c-9262d8878969)

### Version

7.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please create a support ticket on https://support.abp.io/

Thanks.
