### ISSUE TITLE
Outdated library: System.Linq.Dynamic.Core

### ISSUE THREAD

**Issue by nev-21** [abpframework/abp#17175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Just to notify there is a security issue in System.Linq.Dynamic.Core about linq injection attacks.

This issue was fixed in Version 1.3 of the library:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/660

But by default Volo.Abp.Core still allow previous versions: System.Linq.Dynamic.Core (>= 1.2.18)
https://www.nuget.org/packages/Volo.Abp.Core/

### Expected behavior

Existing and new projects should install new version (>=1.3.3) 

### Actual behavior

Existing and new projects are installed the previous nuget version (1.2.18)

### Version

7.2.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/17052

**Comment by bluewind1205** [comment]
> #17052
Version:6.0.x 
Resolves or not
