### ISSUE TITLE
Mongodb cannot filter data

### ISSUE THREAD

**Issue by XiaoChenDan** [abpframework/abp#17203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I create MongoDbRepositoryFilterer<TEntity, TKey> based on [https://docs.abp.io/en/abp/latest/Data-Filtering](url) , but when I do a data query GetListAsync() , process did not enter . it return all items.
Whether the data filtering for get operation is missing?
#11595 

ProjectRepositoryFilterer:
```
[ExposeServices(typeof(IMongoDbRepositoryFilterer<Project, Guid>))]
public class ProjectRepositoryFilterer : MongoDbRepositoryFilterer<Project, Guid>, ITransientDependency
{
    private readonly ISettingProvider _settingProvider;
    private readonly ICurrentUser _currentUser;
    public ProjectRepositoryFilterer(
        IDataFilter dataFilter,
        ICurrentTenant currentTenant,
        ICurrentUser currentUser,
        ISettingProvider settingProvider) : base(dataFilter, currentTenant)
    {
        _currentUser = currentUser;
        _settingProvider = settingProvider;
    }

    public override async Task AddGlobalFiltersAsync(List<FilterDefinition<Project>> filters)
    {
        await base.AddGlobalFiltersAsync(filters);

        if (!(await _settingProvider.GetOrNullAsync(ProjectManagementSettings.ManagerRoles))
            .Split(',').Any(_currentUser.IsInRole))
        {
            filters.Add(Builders<Project>.Filter.Or(
                Builders<Project>.Filter.Eq(x => x.CreatorId, _currentUser.Id),
                Builders<Project>.Filter.Eq(x => x.ProjectManager, _currentUser.Id),
                Builders<Project>.Filter.Eq(x => x.ProjectBimManager, _currentUser.Id),
                Builders<Project>.Filter.Where(x => x.Members.Contains(_currentUser.Id!.Value))));
        }
    }
}
```
ProjectRepository:
```
public class ProjectRepository : MongoDbRepository<ProjectManagementMongoDbContext, Project, Guid>, IProjectRepository
    {
        private readonly ProjectManager _projectManager;

        public ProjectRepository(
            IMongoDbContextProvider<ProjectManagementMongoDbContext> dbContextProvider,
            ProjectManager projectManager) : base(dbContextProvider)
        {
            _projectManager = projectManager;
        }
    }
```
ProjectManagementMongoDbContext
```
[ConnectionStringName(ProjectManagementDbProperties.ConnectionStringName)]
public class ProjectManagementMongoDbContext : AbpMongoDbContext, IProjectManagementMongoDbContext
{
    /* Add mongo collections here. Example:
     * public IMongoCollection<Question> Questions => Collection<Question>();
     */

    public IMongoCollection<Project> Projects => Collection<Project>();

    protected override void CreateModel(IMongoModelBuilder modelBuilder)
    {
        base.CreateModel(modelBuilder);

        modelBuilder.ConfigureProjectManagement();
    }
}
```

### Version

7.3.0.0

### User Interface

Common (Default)

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by masoodkhoshgard** [comment]
Hi @XiaoChenDan 

You must register this filter in the services like the following code example:

```
public class ProjectManagementMongoDbModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        //.......
        context.Services
            .Replace(ServiceDescriptor.Transient(typeof(IMongoDbRepositoryFilterer<,>),typeof(ProjectRepositoryFilterer<,>)));
    }
}
```

**Comment by XiaoChenDan** [comment]
Hi @masoodkhoshgard , thanks you for your reply
I don't think the problem is that the service has not been successfully injected. In fact, I also tried it, and it failed again.
I try to understand IMongoDbRepositoryFilterer implementation to better solve the problem, and I only find IMongoDbRepositoryFilterer<TEntity, TKey> in [https://github.com/abpframework/abp/blob/a2875f1d276e0a8fbe98ea3d7b4ea97964d5b230/framework/src/Volo.Abp.MongoDB/Volo/Abp/Domain/Repositories/MongoDB/MongoDbRepository.cs#L749](url)
and  in CreateEntityFilterAsync () , CreateEntitiesFilterAsync () method to use the service,and it just filters the 'ConcurrencyStamp' parameters.
I also found that CreateEntitiesFilterAsync methods seem to be differences between the target and actual , 'withConcurrencyStamp' or 'applyFilters' Parameters.
Where was I wrong?

**Comment by maliming** [comment]
hi @XiaoChenDan 

See https://github.com/abpframework/abp/pull/17207

We will introduce a new method to filter the `IQueryable`.

**Comment by maliming** [comment]
hi @XiaoChenDan 

We will introduce a `FilterQueryable` method to `IMongoDbRepositoryFilterer`.

**Comment by XiaoChenDan** [comment]
hi @maliming 
That's great! It solved my problem.
By the way, are there any plans to switch to asynchronous methods

**Comment by maliming** [comment]
> By the way, are there any plans to switch to asynchronous methods

Sync methods will call it.
