### ISSUE TITLE
IdentityServer ClaimTypeMap Won't work in Introspection mode

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#1720]
I notice that the reccomend way to config IdentityServer authentication code is following

```
context.Services.AddAuthentication("Bearer")
.AddIdentityServerAuthentication(options =>
{
    options.Authority = configuration["AuthServer:Authority"];
    options.ApiName = configuration["AuthServer:ApiName"];
    options.RequireHttpsMetadata = false;    
    options.InboundJwtClaimTypeMap["sub"] = AbpClaimTypes.UserId;
    options.InboundJwtClaimTypeMap["role"] = AbpClaimTypes.Role;
    options.InboundJwtClaimTypeMap["email"] = AbpClaimTypes.Email;
    options.InboundJwtClaimTypeMap["email_verified"] = AbpClaimTypes.EmailVerified;
    options.InboundJwtClaimTypeMap["phone_number"] = AbpClaimTypes.PhoneNumber;
    options.InboundJwtClaimTypeMap["phone_number_verified"] = 
        AbpClaimTypes.PhoneNumberVerified;
    options.InboundJwtClaimTypeMap["name"] = AbpClaimTypes.UserName;
});
```

But options.InboundJwtClaimTypeMap only works in JWT token, so the [reference token](http://docs.identityserver.io/en/latest/topics/reference_tokens.html) will pass the authentication but ICurrentUser cannot get the correct data

The recommend way is by using middware to customize the claim
```
app.UseAuthentication();
            //after authentication middleware
            app.Use(async (ctx, next) =>
            {
                ICurrentPrincipalAccessor currentPrincipalAccessor =
                    ctx.RequestServices.GetRequiredService<ICurrentPrincipalAccessor>();
                var map = new Dictionary<string, string>()
                {
                    { "sub", AbpClaimTypes.UserId },
                    { "role", AbpClaimTypes.Role },
                    { "email", AbpClaimTypes.Email },
                    //any other map
                };
                var mapClaims = currentPrincipalAccessor.Principal.Claims.Where(p => map.Keys.Contains(p.Type))
                    .ToList();
                currentPrincipalAccessor.Principal.AddIdentity(new ClaimsIdentity(mapClaims.Select(p => new Claim(map[p.Type], p.Value, p.ValueType, p.Issuer))));
                await next();
            });
```

**Comment by maliming** [comment]
Using middleware is not a good solution, can you provide a project to reproduce the problem?

**Comment by Goxiaoy** [comment]
Check out this commit [TestProject](https://github.com/Goxiaoy/ABPTestProject/commit/aa1fb0c72d460b947816877f7744b9b612fb0c9c).

This is a template created on https://abp.io/get-started with parameter:
Project type: Application
UI Framework: Angular
Database provider: Entity Framework Code
Separate Identity Server: checked

**Comment by maliming** [comment]
Using the project you provide cannot be reproduced.

![image](https://user-images.githubusercontent.com/6908465/64343389-0fd9b400-d01f-11e9-8abf-629633da40e8.png)

**Comment by Goxiaoy** [comment]
That's really weird. When will static property AbpClaimTypes.UserId be changed? I testd in this [commit](https://github.com/Goxiaoy/ABPTestProject/commit/a7ac769ef7390174dca9933a527c28ac4f62da96). AbpClaimTypes.UserId is changed between pre and post configure service.

**Comment by Goxiaoy** [comment]
To clarify what I am talking about,  I have to creat a [empty project](https://github.com/Goxiaoy/ABPTestProject/commit/29075b4efa9ccb4f8a07b577d99f1c4130c69a27) to explain what I am talking about

So I have created a test `token` api to get resource owner reference token 

![image](https://user-images.githubusercontent.com/8577611/64403458-36453100-d0ab-11e9-9bdd-11f2d3c9742a.png)

And then, I use this token to request `claim` api

![image](https://user-images.githubusercontent.com/8577611/64403484-4e1cb500-d0ab-11e9-8a18-8717674b6acc.png)


And the previous test project rely on IdentityServer module and run the code in  [AddAbpIdentityServer]()  which will not happen in a usual api project

**Comment by Goxiaoy** [comment]
Either the api project should change static property of AbpClaimTypes or use middleware to remap claim type
```
AbpClaimTypes.UserId = JwtClaimTypes.Subject;
AbpClaimTypes.UserName = JwtClaimTypes.Name;
AbpClaimTypes.Role = JwtClaimTypes.Role;
AbpClaimTypes.Email = JwtClaimTypes.Email;
```

**Comment by maliming** [comment]
I will check it out.

**Comment by maliming** [comment]
Try it in your `TestProject.EmptyProject` project

```
AbpClaimTypes.UserId = JwtClaimTypes.Subject;
AbpClaimTypes.UserName = JwtClaimTypes.Name;
AbpClaimTypes.Role = JwtClaimTypes.Role;
AbpClaimTypes.Email = JwtClaimTypes.Email;
```

**Comment by Goxiaoy** [comment]
> Try it in your `TestProject.EmptyProject` project
> 
> ```
> AbpClaimTypes.UserId = JwtClaimTypes.Subject;
> AbpClaimTypes.UserName = JwtClaimTypes.Name;
> AbpClaimTypes.Role = JwtClaimTypes.Role;
> AbpClaimTypes.Email = JwtClaimTypes.Email;
> ```

Yes it will work. But anything I can find configure authentication is [here](https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo#authentication-2). So I do not think the design of static class AbpClaimTypes is good.

**Comment by maliming** [comment]
Other frameworks are designed like this. For example: Identity.

![image](https://user-images.githubusercontent.com/6908465/64409320-436a1c00-d0bb-11e9-81b2-0e13837a9dee.png)

**Comment by hikalkan** [comment]
The latest IDS4 & AspNet Core has not a `InboundJwtClaimTypeMap` dictionary, so that solution was not working for the microservice demo.

I switched to the approach that is suggested by @Goxiaoy and it worked. Thanks. https://github.com/abpframework/abp/commit/d8bdcffd4c69787e69fb7ae3c3375a44a0067e7c
