### ISSUE TITLE
DateRangePicker dependency on moment.js

### ISSUE THREAD

**Issue by JadynWong** [abpframework/abp#17204]
abp v7.3.0 / MVC / EF Core

abp has been using `luxon` to handle datetime since its early versions. 

`luxon` provides similar functionality to `moment.js`. I don't understand the need to bring in `moment.js` to handle datetime. It is added in the `Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared` package (which is dependent on `BootstrapDaterangepickerScriptContributor`). Users have to reference to two functionally similar packages at the same time.

momentjs: https://momentjs.com/docs/#/-project-status/
luxon: https://moment.github.io/luxon/#/why

https://github.com/abpframework/abp/blob/cea7c9e1696a10973253dd7108ad06e5a1b69e4b/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/dom-event-handlers.js#L416-L428

**Comment by JadynWong** [comment]
Hi @salihozkara, what do you think about it?

**Comment by salihozkara** [comment]
> Hi @salihozkara, what do you think about it?

The [package](https://www.daterangepicker.com/) we use for datepicker is using moment. For this reason, the moment is also added.

**Comment by JadynWong** [comment]
Thanks for the explanation, looks like it's a must.
