### ISSUE TITLE
Cannot download the template

### ISSUE THREAD

**Issue by v-jinhuali** [abpframework/abp#17208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

PS C:\Users\vjinh> abp new Acme.BookStore -t app-nolayers -u angular -csf
ABP CLI 7.3.0
Creating your project...
Project name: Acme.BookStore
Template: app-nolayers
UI Framework: Angular
Output folder: C:\Users\vjinh\Acme.BookStore
Downloading template: app-nolayers, version: 7.3.1
Error occured while downloading source-code from https://abp.io/api/download/template/ : StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Thu, 27 Jul 2023 12:42:54 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Pragma: no-cache
  Set-Cookie: .AspNetCore.Antiforgery.-6OvtTX3HwI=CfDJ8FwlyK6gBQtDks_tINvwLxMwj-BpeDLMQf6zIUvH3mwlOVDMUbW2bhVZZ64R8zxWw5N7c7lgSNGMpidySYZYS3erjlRulmZPergW8AVqKaQhKRdY84Su4T-p_gIDDVyF4vZzwpBbet0q1-FnHMHWjHA; path=/; samesite=strict; httponly
  Set-Cookie: XSRF-TOKEN=CfDJ8FwlyK6gBQtDks_tINvwLxMmfq_35MDxo16X0yQ7pPiIwgUsO4NBWg3KMr7iByadlHN9mOgFA501imIDJ4lbDdqnEH9bjeftknVvRg2bdCJeoY8NW5d9tJwtgLv5TnKph9QJaOIu1U9YybSozFe6MGc; expires=Sun, 24 Jul 2033 12:42:54 GMT; path=/; secure; samesite=none
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15724800; includeSubDomains
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  X-Frame-Options: SAMEORIGIN
  CF-Cache-Status: DYNAMIC
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=XJq7zCn5950ZXfOAN0kEdZfbYy5XXUkeDu2B4fkwRgxzxfeCpZoKnXy6B6bM8J2OUd%2Bl2SJb1UMJbiV2U3eynLuZ6n0WSngbHIBySdMgvJVS6IBvGq2fqA%3D%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 7ed4f6f13cb4820e-IAD
  Content-Type: text/html; charset=utf-8
  Expires: -1
}
'<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
'<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.

### Version

7.3.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by ugurozturk** [comment]
7.3.0 was working but with 7.3.1 I am  having problem
`
abp new UOzturk.ReportSystem -t module --no-ui
`

Edit : tried removing cli 7.3.1 and reinstalling 7.3.0 but still failed. Perhaps because of template version is on 7.3.1. 

Error messages
```

space\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\TemplateProjectBuilder.cs:line 66
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 92
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 169
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 77

```
Operation System : Mac M1 Pro

Edit 2:
used -v 7.3.0 and worked for me. like

`abp new UOzturk.ReportSystem -t module --no-ui -v 7.3.0`

**Comment by maliming** [comment]
7.3.1 works now, you can try again.
