### ISSUE TITLE
Unable to Create New Project 

### ISSUE THREAD

**Issue by silambarasan-ilango** [abpframework/abp#17215]
### Is there an existing issue for this?

https://github.com/abpframework/abp/issues/9368

### Description

Unable to create a new project

### Reproduction Steps

Run ABP Cli command in terminal:
abp new Acme.BookStore -csf

### Expected behavior

Project will be created.

### Actual behavior

![image](https://github.com/abpframework/abp/assets/28433279/ba6c2cf7-831a-4d43-a1bc-de0b79578d36)

### Regression?

Not tried.

### Known Workarounds

NO

### Version

7.3.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

I tested it, and it works. You can try again.

**Comment by silambarasan-ilango** [comment]
@maliming 
Yes, resolved now. Thanks.
