### ISSUE TITLE
How to prevent if-not-exists-insert concurrently ?

### ISSUE THREAD

**Issue by rwecho** [abpframework/abp#1721]
Is there any mechanism to prevent concurrents? 

I have code like below, if there are many concurrent requests, it will create more records.

Should I use SemaphoreSlim or Sql Transaction to solve this question. And how ? 

``` csharp

[UnitOfWork(isTransactional: true)]
public async Task<IActionResult> TestController(string name)
{
       var existence = this.RecordRepository.GetFirstOrDefault(name);
       if (existence == null )
       {
              await    this.RecordRepository.InsertAsync(new Record(){Name = name});
       }
}

```

Thank you for your help in advance.

**Comment by maliming** [comment]
This issue is essentially not related to abp.
If you want to prevent duplicate data from being inserted, you can use the unique constraint of sql server. If you want to implement it through a transaction, you should set a stricter transaction isolation level.
Please refer to the database documentation for details.

**Comment by rwecho** [comment]
@maliming 
I dont' familiar with abp uow/transactional, I thought it has transaction capacity. This is mix me with database transaction.

Typically, How to do with unitofwork and DbTransaction?  

Thanks

**Comment by maliming** [comment]
> Typically, How to do with unitofwork and DbTransaction?

The framework will handle it automatically, it will create a unit of work according to the convention or UnitOfWorkAttribute.

The unit of work manages database connections and transactions, usually you don't need to modify it.
Of course you can modify some of the properties of the unit of work through UnitOfWorkAttribute.

See UnitOfWorkAttribute for details (https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkAttribute.cs)

**Comment by dicksonkimeu** [comment]
In my application services, i have a scenario where i want to update multiple tables, and if one fails, it should role back the whole transaction. Is below setting sufficient ?

![image](https://user-images.githubusercontent.com/4476822/79029952-6c95e200-7b9f-11ea-9857-4b74880775db.png)

**Comment by liangshiw** [comment]
@dicksonkimeu Yes it is transactional

**Comment by hikalkan** [comment]
`isTransactional` is nor needed since it is already transactional by default.
