### ISSUE TITLE
 Error: Module not found: Error: Can't resolve '@volosoft/abp.ng.theme.lepton-x'

### ISSUE THREAD

**Issue by AhmedBoody** [abpframework/abp#17228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I ran the following cmd to create my abp project:
`abp new Acme.BookStore -u angular --separate-identity-server --theme basic -csf `

then I follow the guidelines steps for running the solution from :
https://docs.abp.io/en/commercial/latest/getting-started-running-solution?UI=NG&DB=EF&Tiered=Yes

I could launch the backend successfully,

then I run the command 
`yarn`

last step I run the command 
'yarn start'

I got these errors 
![image](https://github.com/abpframework/abp/assets/16067845/bef8c292-5d23-4bb0-9dda-bc740c5dfd78)

### Reproduction Steps

I ran the following cmd to create my abp project:
`abp new Acme.BookStore -u angular --separate-identity-server --theme basic -csf `

then I follow the guidelines steps for running the solution from :
https://docs.abp.io/en/commercial/latest/getting-started-running-solution?UI=NG&DB=EF&Tiered=Yes

I could launch the backend successfully,

then I run the command 
`yarn`

last step I run the command 
'yarn start'

I got these errors 
![image](https://github.com/abpframework/abp/assets/16067845/bef8c292-5d23-4bb0-9dda-bc740c5dfd78)

### Expected behavior

Angular project builds successfully.

### Actual behavior

Build error

### Version

7.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by rashedjawda** [comment]
Hi Ahmed 
@AhmedBoody 

Did you find a solution to this issue ?

**Comment by Sinan997** [comment]
duplicated issue https://github.com/abpframework/abp/issues/17157
