### ISSUE TITLE
Overridable AuditLogActionConsts

### ISSUE THREAD

**Issue by dadotnetkid** [abpframework/abp#17226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

httppost body is greater than 2000 and it not logging 

### Describe the solution you'd like

 Configure<AbpAuditingOptions>(options =>
        {
            options.Parameter.MaxLength=int.MaxValue;
            
        });
    }

**Comment by maliming** [comment]
hi

The values of `AuditLogActionConsts` are `static`. You can change them.

**Comment by dadotnetkid** [comment]
we are using nuget package.

**Comment by maliming** [comment]
<img width="719" alt="image" src="https://github.com/abpframework/abp/assets/6908465/66033529-a68e-416a-9fe6-d188552d23b5">

**Comment by dadotnetkid** [comment]
will try this one

**Comment by maliming** [comment]
Also add this line to `MyProjectNameDbContextFactory`.
