### ISSUE TITLE
EventBus.RabbitMQ in ExchangeDeclarePassive will close channel,and ExchangeDeclare will fail and throw error

### ISSUE THREAD

**Issue by bingtianyiyan** [abpframework/abp#17237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1.in Volo.Abp.EventBus.RabbitMQ, for EnsureExchangeExists function code , channel.ExchangeDeclarePassive(AbpRabbitMqEventBusOptions.ExchangeName) will close channel,
so in catch for  
     channel.ExchangeDeclare(
                AbpRabbitMqEventBusOptions.ExchangeName,
                AbpRabbitMqEventBusOptions.GetExchangeTypeOrDefault(),
                durable: true
            );
will fail and throw error ,because channel is close。

so we should use channel.ExchangeDeclare  to create exchange

### Version

8.2.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Thanks @bingtianyiyan , we will fix it.
