### ISSUE TITLE
webapi return error "invaild_client"

### ISSUE THREAD

**Issue by woshiyifadaguangtou** [abpframework/abp#1723]
i download demo with webapi and angular then run appliction.when i click sign in ,webapi return error "invaild_client".how to fix it

**Comment by maliming** [comment]
How did you migrate the database?

**Comment by woshiyifadaguangtou** [comment]
> How did you migrate the database?



First I set up a database in sqlserver management studio .
Then I  set .web project as startUp Project then open the Package Manager Console ,selected .EntityFramewrokCore.DbMigrations project as the Default Project and  used EF Core Update-DataBaseCommand.it returns success,and .web project runs,but when i sign in ,angular project try to  access api " localhost:43389/connect/token" ,it got "invalid_client", and i don't know how to debug it

**Comment by maliming** [comment]
> Using the .Migrator tool is the suggested way, because it also seeds the initial data to be able to properly run the web application.

see: https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template#using-the-dbmigrator-application

**Comment by woshiyifadaguangtou** [comment]
> > Using the .Migrator tool is the suggested way, because it also seeds the initial data to be able to properly run the web application.
> 
> see: https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template#using-the-dbmigrator-application

Thanks,I'll try it right away.

**Comment by woshiyifadaguangtou** [comment]
> > Using the .Migrator tool is the suggested way, because it also seeds the initial data to be able to properly run the web application.
> 
> see: https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template#using-the-dbmigrator-application

Hi ,i used the .Migrator tool and then i got a new error message

 error: "invalid_grant"
error_description: "invalid_username_or_password"


here is my client post  data 

![image](https://user-images.githubusercontent.com/8001533/64436654-60bcdb80-d0f7-11e9-809e-cba19f7d0f5c.png)

grant_type: password
scope: Wss
username: admin
password: 1q2w3e*
client_id: Wss_App
client_secret: 1q2w3e*

**Comment by woshiyifadaguangtou** [comment]
@maliming 您好，我用文档建议的方法迁移了一下数据库，数据库里面也已经有种子数据，在获取token的时候提示我帐号密码不对。另外还遇到一个问题，就是angular的前端 样式没有加载出来

**Comment by maliming** [comment]
**invalid_username_or_password**

`admin `password is `1q2w3E*`
