### ISSUE TITLE
I Cant receive DistributedEvent use Pre-Defined Events

### ISSUE THREAD

**Issue by choby** [abpframework/abp#17235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i add an entity and eto config like this :
```csharp
 Configure<AbpDistributedEntityEventOptions>(options =>
        {
            options.AutoEventSelectors.Add<Supplier>();
            options.EtoMappings.Add<Supplier, SupplierEto>();        
        });
```
in profile I add this code :
```csharp
 CreateMap<Supplier, SupplierEto>();
```

bug i test the event sent like this: 
![image](https://github.com/abpframework/abp/assets/13461239/d0dedce5-323d-4fb3-ba8f-c79b14b038a5)

and in another project, i cant receive event use  `IDistributedEventHandler<EntityUpdatedEto<SupplierEto>>`

### Version

7.3

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

macOS

**Comment by choby** [comment]
i tarcking the code , find this place cant work, the first fieldinfo's name is "__interceptors"
![image](https://github.com/abpframework/abp/assets/13461239/456ee9d9-15d0-4432-a289-3d6b6a74ac18)

![image](https://github.com/abpframework/abp/assets/13461239/98ff9e9d-794c-4760-8d58-6e01520e5f05)

**Comment by gterdem** [comment]
> in another project, i cant receive event use IDistributedEventHandler<EntityUpdatedEto<SupplierEto>>

So you have 2 different projects and trying to communicate using the `DistributedEventBus`.

- Do your projects use any integrations Kafka, RabbitMq etc? Can you make sure you have correctly added the DependsOn attributes etc.

Can you share a sample repository so we can check?

**Comment by choby** [comment]
this is the sample repo :
[https://github.com/choby/eto_cant_mapping](https://github.com/choby/eto_cant_mapping)

**Comment by choby** [comment]
> > in another project, i cant receive event use IDistributedEventHandler<EntityUpdatedEto>
> 
> So you have 2 different projects and trying to communicate using the `DistributedEventBus`.
> 
> * Do your projects use any integrations Kafka, RabbitMq etc? Can you make sure you have correctly added the DependsOn attributes etc.
> 
> Can you share a sample repository so we can check?

this is the sample repo:

[https://github.com/choby/eto_cant_mapping](https://github.com/choby/eto_cant_mapping)

**Comment by choby** [comment]
> > in another project, i cant receive event use IDistributedEventHandler<EntityUpdatedEto>
> 
> So you have 2 different projects and trying to communicate using the `DistributedEventBus`.
> 
> * Do your projects use any integrations Kafka, RabbitMq etc? Can you make sure you have correctly added the DependsOn attributes etc.
> 
> Can you share a sample repository so we can check?

Have you looked at the demo code? Can you figure out what the problem is

**Comment by choby** [comment]
I rewrote the EntityToEtoMapper class, and call the ProxyHelper. GetUnProxiedType() method can solve the problem

**Comment by gterdem** [comment]
I couldn't run your sample. The Domain.Shared project is missing.

You should configure pre-defined events in Domain layer:
```cs
Configure<AbpDistributedEntityEventOptions>(options =>
        {
            options.AutoEventSelectors.Add<Supplier>();
            options.EtoMappings.Add<Supplier, SupplierEto>();
        });
```

Add the mapping to the Application layer under `ScmApplicationAutoMapperProfile`:
```cs
public class ScmApplicationAutoMapperProfile : Profile
{
    public ScmApplicationAutoMapperProfile()
    {
        CreateMap<Supplier, SupplierEto>();
    }
}
```
Your `SupplierEto` should be located under Domain.Shared layer to be able share.

Also I didn't understand why do you need `Evo.Scm.EventHandlers` project. You can write your handlers in Application layer if it is related to your application or Domain layer if it is related to your domain.

You are also using `ILocalEventHandler` to handle distributed events, that's wrong. You should use `IDistributedEventHandler`.
See  https://docs.abp.io/en/abp/latest/Distributed-Event-Bus for proper usage of events and handlers.

**Comment by choby** [comment]
> I couldn't run your sample. The Domain.Shared project is missing.
> 
> 
> 
> You should configure pre-defined events in Domain layer:
> 
> ```cs
> 
> Configure<AbpDistributedEntityEventOptions>(options =>
> 
>         {
> 
>             options.AutoEventSelectors.Add<Supplier>();
> 
>             options.EtoMappings.Add<Supplier, SupplierEto>();
> 
>         });
> 
> ```
> 
> 
> 
> Add the mapping to the Application layer under `ScmApplicationAutoMapperProfile`:
> 
> ```cs
> 
> public class ScmApplicationAutoMapperProfile : Profile
> 
> {
> 
>     public ScmApplicationAutoMapperProfile()
> 
>     {
> 
>         CreateMap<Supplier, SupplierEto>();
> 
>     }
> 
> }
> 
> ```
> 
> Your `SupplierEto` should be located under Domain.Shared layer to be able share.
> 
> 
> 
> Also I didn't understand why do you need `Evo.Scm.EventHandlers` project. You can write your handlers in Application layer if it is related to your application or Domain layer if it is related to your domain.
> 
> 
> 
> You are also using `ILocalEventHandler` to handle distributed events, that's wrong. You should use `IDistributedEventHandler`.
> 
> See  https://docs.abp.io/en/abp/latest/Distributed-Event-Bus for proper usage of events and handlers.
> 
> 
> 
> 

thank you. 

Although many codes are not positioned correctly，but I think these problems have nothing to do with this bug.

The problem is that ProxyHelper.UnProxy(） did not work as expected.it couldnt map the proxyed domain to Eto. And i call ProxyHelper. GetUnProxiedType() solved the problem. maybe it's because my domain is dynamically loaded into dbcontext?

Or you should use ProxyHelper. GetUnProxiedType() by default in EntityToEtoMapper class.

**Comment by alvstw** [comment]
@choby 
I am getting the same issue you described. Did you manage to resolve the issue without changing the internal code of the framework?

**Comment by choby** [comment]
> @choby I am getting the same issue you described. Did you manage to resolve the issue without changing the internal code of the framework?

I rewrote the EntityToEtoMapper class
