### ISSUE TITLE
Order setting tabs by display name

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#17232]
![image](https://github.com/abpframework/abp/assets/1210527/eb711a84-ae2c-4dfd-ae26-c8c6ce8390c5)

In this example, the true order should be:

* Account
* Emailing
* Identity Management

# TODO

- [x] MVC UI
- [x] Blazor UI

**Comment by rqx110** [comment]
It's better to allow developers to define (change) the sorting logic instead of fixed sorting by name

**Comment by maliming** [comment]
> It's better to allow developers to define (change) the sorting logic instead of fixed sorting by name

Yes. https://github.com/abpframework/abp/pull/17254
