### ISSUE TITLE
Remove Logo implementation (CSS and HTML) out of Lepton template

### ISSUE THREAD

**Issue by sephit** [abpframework/abp#17243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Whenever you override the default Lepton or LeptonX logo, you have a blink until the website fully loads. It will display for a short time (depending on client's internet connection) the lepton logo instead of the replaced one.

### Describe the solution you'd like

To solve this issue. We can take the logo implementation (the SVG inside of the CSS files) and the physical SVG and PNG files out of Lepton template and implement the injection of that file from the root project (Demo.Web or Demo.Web.Public).

**Comment by leonkosak** [comment]
ASP.NET Zero (and maybe ASP.NET Boilerplate also) has uploader for uploading tenant oz host logo (which is stored in database).
Maybe, this is even a better solution. What do you think @sephit, @maliming and @hikalkan?

**Comment by sephit** [comment]
It's a good solution to retrieve it from the database but there is an implementation in ABP Framework that you can replace any file from Lepton or LeptonX if you place the same folder structure in your main applications. (Virtual directory)

So if you want to replace, for example, the dark.css. you just have to create a file like this "Themes\LeptonX\Global\top-menu\css\dark.css" in your Demo.Web Project.

A simpler solution would be to replace in dark.css, light.css, dim.css and their rtl versions  the 
```
  --lpx-logo
  --lpx-logo-icon
```
with an empty SVG implementation. 

And replace the physical logo and icon in the theme source code for also empty files. So whenever we replace those files in our projects. The default value won't be noticeable by the end users.

What do you think @hikalkan  @leonkosak @maliming

**Comment by leonkosak** [comment]
Yes, I agree.
Maybe I would distinguish two logos. One is the application logo (which should also be replaceable on filesystem and on the database level) and the second is tenant-specific logo.

**Comment by enisn** [comment]
If you replace the physical file in `ProjectName.Web\wwwroot\images\logo\leptonx\logo-light.png`, it'll directly load that file instead of loading the original leptonx logo then your custom logo


![leptonx-logo-loading](https://github.com/abpframework/abp/assets/23705418/e250bc1c-a016-4155-bd31-4bab25d7675e)



---
You'll see the `--lpx-logo` CSS variable has `/images/logo/leptonx/logo-light.png)` default value:
<img width="100%" alt="image" src="https://github.com/abpframework/abp/assets/23705418/a01a063e-4bc0-475e-827f-02b9f083b376">

**Comment by enisn** [comment]
We've changed the logo implementation in the v8.0. I hope it'll provide a better experience. I'm closing this issue
