### ISSUE TITLE
relation AbpBackgroundJobs does not exist

### ISSUE THREAD

**Issue by qzwzqty** [abpframework/abp#1724]
I changed the BackgroundJobs prefix like this:
````
builder.ConfigureBackgroundJobs(opt =>
            {
                opt.Schema = "Zx";
                opt.TablePrefix = "T_";
            });
````

error:
![Snipaste_2019-09-06_11-46-53](https://user-images.githubusercontent.com/23160268/64399893-bc0db000-d09c-11e9-9090-bd0730c86032.png)

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1690

**Comment by qzwzqty** [comment]
@maliming  ok,thanks
