### ISSUE TITLE
InvalidCastException at GetPoliciesNames when launching the Abp website 

### ISSUE THREAD

**Issue by rwecho** [abpframework/abp#17259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/abpframework/abp/assets/8048753/299c2816-1f20-41cb-a3ec-c7ed6b21fb07)
Like the image, When I update the project to Abp 7.3.1. It throws an InvalidCastException like this.
And the dotnet core version is 8.0.100-preview.6.23330.14

### Version

7.3.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> And the dotnet core version is 8.0.100-preview.6.23330.14

ABP is not support net core 8 yet.
