### ISSUE TITLE
In which layer should I depend on the Hangfire module to use the Hangfire attributes?

### ISSUE THREAD

**Issue by iyilm4z** [abpframework/abp#17268]
I usually depend on the Hangfire modules of Abp in host projects like `Web.Host` and `HttpApi.Host`. And I use Abp's abstraction classes like `AsyncBackgroundJob` and `IBackgroundJobManager` in the `Domain` layer. In this way, I prevent my domain code from depending on the Hangfire code itself. Thanks to Abp to abstract them for me.

Recently, I would like to use the Hangfire `Queue` attribute as documented here https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire#specifying-queue. So, should I depend on the Hangfire modules in the Domain layer now? I think the `Domain` layer should be infrastructure framework-agnostic as much as possible. Using an infrastructure framework code(except Abp) directly in my domain code seems wrong to me.  What if I switch to `Quartz` or `RabbitMQ` later?

In which layer should I depend on the Hangfire module? What I'm doing wrong?

**Comment by maliming** [comment]
hi @iyilm4z 

You can add a custom attribute and override this method.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BackgroundJobs.HangFire/Volo/Abp/BackgroundJobs/Hangfire/HangfireBackgroundJobManager.cs#L34


It is difficult for us to abstract all background job features.

**Comment by maliming** [comment]
`var queueAttribute = Options.GetJob(argsType).JobType.GetCustomAttribute<QueueAttribute>() ?? Options.GetJob(argsType).JobType.GetCustomAttribute<MyQueueAttribute>();`

**Comment by iyilm4z** [comment]
Hi @maliming,

>It is difficult for us to abstract all background job features.

You are definitely right about abstracting all. 

---

Actually, I expected that you would give this advice. But since I will need new attributes in the future like `LatencyTimeout`, `AutomaticRetry` and my own custom attributes depend on Hangfire's `JobFilterAttribute` class, etc. But I still wanted to ask for a possibly better option.  

Thank you dear friend, it clearer now.
