### ISSUE TITLE
Remove overriding equals for entities and value types

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1728]
Because of https://github.com/aspnet/EntityFrameworkCore/issues/15687#issuecomment-492280606

I will instead create `EntityEquals` and `ValueEquals` methods to compare keys/values instead of object references.

**Comment by maliming** [comment]
Is Boilerplate also affected by this problem?
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Domain/Entities/Entity.cs#L56

**Comment by hikalkan** [comment]
When we upgrade to EF Core 3.0, yes, probably. Created an issue: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4856
Thank you for reminding this.
