### ISSUE TITLE
Need Help: How to Initialize LazyServiceProvider in Domain Service for Unit  Test

### ISSUE THREAD

**Issue by QaisAlkhateeb** [abpframework/abp#17290]
### Discussed in https://github.com/abpframework/abp/discussions/17289

<div type='discussions-op-text'>

<sup>Originally posted by **QaisAlkhateeb** August  5, 2023</sup>
I'm writing unit test to my domain service `DefaultNotificationDistributer`, I'm facing issues when using `GuidGenerator` because it's `null` and the `LazyServiceProvider` itself is `null`

```cs
internal class DefaultNotificationDistributer : DomainService, INotificationDistributer
{
    public DefaultNotificationDistributer(IDependencyA a, IDependencyB b) 
   {
     // code here  ... 
   }
   
   public void Foo()
   {
       var newGuid = GuidGenerator.Create(); // This is this throw null exception when running a unit test because I'm using the `new` for constructor initialization
   }  
   // other methods ...
}
```

The Unit Class

```cs
 public DefaultNotificationDistributer_Tests()
 {
            mockA= new Mock<IDependencyA>();
            mockB= new Mock<IDependencyB>();

           // I need to use mock Objects here because I need to focuse the test on the logic of DefaultNotificationDistributer
            sut = new DefaultNotificationDistributer(
                mockA.Object,
                mockB.Object);
}

[Fact]
public void Do_Test()
{
    sut.Foo();
}
```</div>

**Comment by QaisAlkhateeb** [comment]
I fix this by Keep depending on native dependency injection and override the registration of the objects and Need to mock in `AfterAddApplication`:

here is the code:
```cs

 public DefaultNotificationDistributer_Tests()
{
    sut = GetRequiredService<DefaultNotificationDistributer>();
}

[Fact]
public void Do_Test()
{
    sut.Foo();
}

protected override void AfterAddApplication(IServiceCollection services)
{
       base.AfterAddApplication(services);
      
      // override services 
      mockA= new Mock<IDependencyA>();
      mockB= new Mock<IDependencyB>();

      services.Replace(new ServiceDescriptor(
                typeof(IDependencyA),
                (f) => mockA.Object,
                ServiceLifetime.Transient));

            services.Replace(new ServiceDescriptor(
                typeof(IDependencyB),
                (f) => mockB.Object,
                ServiceLifetime.Transient));
}

``` 


Now it's working fine, I will keep this issue open just to get the Abp team feedback

**Comment by maliming** [comment]
hi

The `LazyServiceProvider` is designed to inject as property.

https://docs.abp.io/en/abp/latest/Dependency-Injection#property-injection

That means you should get the services from DI, or initial the properties manually.

**Comment by QaisAlkhateeb** [comment]
Hi @maliming , 

Thanks for your response, The Idea that I don't want to change the implementation just to be able to initialize the Property in unit test.

Can you please elaborate with an example?

**Comment by maliming** [comment]
hi

```cs
sut = new DefaultNotificationDistributer(
                mockA.Object,
                mockB.Object);

sut.LazyServiceProvider = GetRequiredService<LazyServiceProvider>()/...
```

**Comment by QaisAlkhateeb** [comment]
Thanks for your help, I tried this but did not work on our solution, but when I tried it on a sample app it works, I will investigate it and found what's wrong in our solution.
