### ISSUE TITLE
Dynamic API Clients using WebAssembly, Generate TS definations.

### ISSUE THREAD

**Issue by xxyuze** [abpframework/abp#1729]
- Dynamically create C# API client proxies to call remote HTTP services and compile it to [WebAssembly](https://webassembly.org/) like blazor.
- We call C# functions in javascript using [JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#invoke-net-methods-from-javascript-functions).
- Generate typescript definitions for calling.

**Comment by hikalkan** [comment]
>Dynamically create C# API client proxies to call remote HTTP services
That's already done: https://docs.abp.io/en/abp/latest/AspNetCore/Dynamic-CSharp-API-Clients

>Generate typescript definitions for calling
You already created an issue for it and I replied: https://github.com/abpframework/abp/issues/1717

**Comment by leonkosak** [comment]
If I understand correctly - when Blazor comes in abp, there will also be separated "solution" for backend and frontend?
"By default in Blazor", frontend and backend code is "glued" together and that concept is not something that I would like to have in application framework like abp.

**Comment by hikalkan** [comment]
>If I understand correctly - when Blazor comes in abp, there will also be separated "solution" for backend and frontend?

We will create a single solution, but separate projects inside the solution. I think that's more practical for development. If you have two teams one for backend and one for frontend, you can separate them.

**Comment by leonkosak** [comment]
Maybe multiple solution files (.sln) - just like in ANZ (.Web.sln, .Mobile.sln, .All.sln)?
