### ISSUE TITLE
CmsKit - After switching to `Form` from `DynamicForm`, `CoverImageMediaId` is missing.

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#17296]
After switching to `Form` from `DynamicForm`, `CoverImageMediaId` is also missing.

Update page `ConcurrencyStamp` label is not hidden.

_Originally posted by @JadynWong in https://github.com/abpframework/abp/issues/17286#issuecomment-1667078620_

**Comment by enisn** [comment]
Take a loot at
https://github.com/abpframework/abp/issues/17286#issuecomment-1667276476

**Comment by JadynWong** [comment]
Uh, the Create page is still missing the `CoverImageMediaId`.
