### ISSUE TITLE
AbpExceptionPageFilter and log content are inconsistent

### ISSUE THREAD

**Issue by ViatorLife** [abpframework/abp#17309]
![image](https://github.com/abpframework/abp/assets/26713143/bf88514f-2e68-40fa-834b-3cdb099dab38)

When reading the source code, I found that this place is inconsistent with the current class, is there another reason?

location: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionPageFilter.cs

**Comment by maliming** [comment]
hi

I will make it consistent, Thanks
