### ISSUE TITLE
Why is the module not using auto api controllers?

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#1731]
I noticed that auto api controllers are not used in the template of the module, but instead the controller class is defined (eg [SampleController](https://github.com/abpframework/abp/blob/dev/templates/module/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi/Samples/SampleController.cs)).

However, you also know that creating a controller for each application service is a tedious job, so I want to know why the auto api controller is not used in modules? Is this a violation of the best practice?

**Comment by maliming** [comment]
HTTP API package only depends on the Application.Contracts package. It does not depend on the Application package.

![image](https://user-images.githubusercontent.com/6908465/64501982-5c124600-d2f6-11e9-9a96-7381cfcb504f.png)

**Comment by wakuflair** [comment]
@maliming 
Yes, I found out that the `HttpApi` project does not reference the `Application` project.
And I tried to use the auto api controller method without changing the dependencies by adding the following code in the `XXXHttpApiModule` `ConfigureServices` method:

``` charp
            Configure<AbpAspNetCoreMvcOptions>(options =>
            {
                options
                    .ConventionalControllers
                    .Create(typeof(XXXApplicationContractsModule).Assembly);
            });
```
I used `ApplicationContracts` insteadof `Application`, but this does not work.

So, is there a win-win approach that can use the auto api controller and follow the best practice?

**Comment by wakuflair** [comment]
Thanks to @maliming , I got it.

**Comment by felipemoreira2x** [comment]
@wakuflair Hi!

How did you solve this issue ?

**Comment by wakuflair** [comment]
Hi @felipemoreira2x 
Just use the `options.ConventionalControllers.Create` in the `ConfigureServices` method of `YourModuleWebUnifiedModule.cs`:

``` csharp
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
	    ... 

            // Auto controllers
            Configure<AbpAspNetCoreMvcOptions>(options =>
            {
                options.ConventionalControllers.Create(typeof(PersonnelManagementApplicationModule).Assembly);
            });
        }
```

**Comment by hikalkan** [comment]
>So, is there a win-win approach that can use the auto api controller and follow the best practice?

For the modules, we couldn't find a way of using auto api controllers without depending on the application service implementation, unfortunately.

**Comment by jevonsflash** [comment]
It's not exactly a win-win situation ,it only works on single applications. In the gateway layer of the microservice, there is no way to get an interface definition, because it does not rely on ApplicationModuel and those Api for proxy cannot be automatically generated

> > Hi @felipemoreira2x
> > Just use the `options.ConventionalControllers.Create` in the `ConfigureServices` method of `YourModuleWebUnifiedModule.cs`:
> > ```cs
> >         public override void ConfigureServices(ServiceConfigurationContext context)
> >         {
> > 	    ... 
> > 
> >             // Auto controllers
> >             Configure<AbpAspNetCoreMvcOptions>(options =>
> >             {
> >                 options.ConventionalControllers.Create(typeof(PersonnelManagementApplicationModule).Assembly);
> >             });
> >         }
> > ```
> 
> Thanks @wakuflair. It worked.

**Comment by wakuflair** [comment]
Yes you are right.
It's like a hack to let you use auto controller in a module, don't do it in a real scenario.
