### ISSUE TITLE
`EntityCreatedEto<UserEto>` can't get all the user's values.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#1732]
Hi, 
I just created a class to handle `EntityCreatedEto<UserEto>` event, which is generally created according to the [BlogUserSynchronizer](https://github.com/abpframework/abp/blob/master/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUserSynchronizer.cs) class, except that I handled the "Created" event instead of the "Updated" event.

However, only the `Id`, `UserName`, and `Email` values existed in the `UserDto`, and the others are null:

![image](https://user-images.githubusercontent.com/3471718/64512402-f2576380-d318-11e9-9b45-1322c5f9a50a.png)

I also debugged the "Updated" event, it can get all the values.
Is this a BUG, or is it designed like this.

**Comment by maliming** [comment]
Please share the code for `Create user`.

**Comment by wakuflair** [comment]
@maliming I didn't modify the code for `Create user`. Just use the default UI of the template to create one.

**Comment by maliming** [comment]
Updating the user's other fields after creating the user caused this problem.
https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L59

**Comment by maliming** [comment]
@hikalkan What do you think?
