### ISSUE TITLE
CMS Kit: Revise the EntityTagManager 

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#17327]
Related to https://github.com/abpframework/abp/pull/17326#discussion_r1288245794

We need to revise the `EntityTagManager` class. Because, currently it has some responsibilities that it should not be. For example, the following two methods should not be domain manager methods, since they just wrap the repository methods and do not contain any logic:

https://github.com/abpframework/abp/blob/7e03f4b48a316e40c60e90f080c9e02113f1fe2a/modules/cms-kit/src/Volo.CmsKit.Domain/Volo/CmsKit/Tags/EntityTagManager.cs#L75-L88

Therefore, we should remove these methods and also check for other methods and their usage and make a proper refactoring.

> **Note**: We might have been using these domain manager methods in our external projects, such as abp.io websites, so please also check our internal projects and ensure we are not using these methods to prevent build problems.

**Comment by hikalkan** [comment]
@EngincanV I want to cancel this, because of unnecessary development time. BTW, I agree about your comments, we should care about that in our next developments.
