### ISSUE TITLE
How to integrate Azure Application Insights with ABP Framework

### ISSUE THREAD

**Issue by manojkrsna** [abpframework/abp#17323]
ABP Framework Version :- 7.1.1

We followed the below article but not able to log anything in Azure Application Insights
https://www.c-sharpcorner.com/article/using-azure-application-insights-for-exception-logging-in-c-sharp/

we are seeing below message

**_AI: Diagnostic message: Performance counters are unavailable when the application is running under IIS Express. Use EnableIISExpressPerformanceCounters element with a value of 'true' within the Performance Collector Module element to override this behavior._**

is there anything we are missing program.cs

   Log.Logger = new LoggerConfiguration()
#if DEBUG
            .MinimumLevel.Debug()
#else
            .MinimumLevel.Information()
#endif
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.Async(c => c.File("Logs/logs.txt"))
            .WriteTo.Async(c => c.Console())
            .CreateLogger();

**Comment by JadynWong** [comment]
https://github.com/serilog-contrib/serilog-sinks-applicationinsights

**Comment by manojkrsna** [comment]
It worked! thanks a ton !
