### ISSUE TITLE
DomainTenantResolver - Missing subdomain in password reset email

### ISSUE THREAD

**Issue by szilardd** [abpframework/abp#17343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have integrated `DomainTenantResolver` based on the sample

https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver/OpenIddict/NG

It works great (after applying fix described [here](https://github.com/abpframework/abp/issues/16135#issuecomment-1514202181)), but there seems to be an issue with the password reset functionality. 

I created a tenant named `t1` and after requesting a password reset, an email is sent which contains the `Reset my password` link. The problem is that the URL doesn't contain the tenant name as a subdomain.

Instead of

`https://t1.api.getabp.net:44301/Account/ResetPassword...`

It is only

`https://api.getabp.net:44301/Account/ResetPassword...`

Because of this it throws an error that it can't find the user (which is correct since it tries to search for the user in the host, not in the tenant).

Is there a workaround for this?

Does the url in the email come from `appsetting.json`?

```json
"AuthServer": {
    "Authority": "https://api.getabp.net:44301",
...
```

I tried to change to `https://*.api.getabp.net:44301` or `https://{0}.api.getabp.net:44301` but it doesn't work, it throws an error during startup the the url is invalid.

### Reproduction Steps

1. Start DomainTenantResolver sample: https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver/OpenIddict/NG
1. Apply fix described [here](https://github.com/abpframework/abp/issues/16135#issuecomment-1514202181)
1. Create new tenant with name `t1`
1. Go to `Reset Password` page and request reset
1. Open email and click on the `Reset my password` link

### Expected behavior

The `Reset Password` page should be shown to provide a new password

### Actual behavior

Error page is shown with error below because the user is a tenant user, not a host user

```
An unhandled exception occurred while processing the request.
EntityNotFoundException: There is no such an entity. Entity type: Volo.Abp.Identity.IdentityUser, id: c8da486b-68fd-5b91-e807-3a0aa1852330
Volo.Abp.Identity.IdentityUserManager.GetByIdAsync(Guid id)
```

### Version

7.2.0 and 7.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please refer to this unit test, You should put the `{{tenantName}}` into your URL.

https://github.com/abpframework/abp/blob/dev/framework/test/Volo.Abp.UI.Navigation.Tests/Volo/Abp/Ui/Navigation/AppUrlProvider_Tests.cs#L33

**Comment by szilardd** [comment]
Thanks! What worked for me was to add `{{tenantName}}` to `App:SelfUrl` in `appsettings.json`

```json
{
  "App": {
    "SelfUrl": "https://{{tenantName}}.api.getabp.net:44301",
    ...
  } 
  ...
}
```

The password reset is working now, but there is still a small issue. After the reset, this page is shown:

![image](https://github.com/abpframework/abp/assets/968502/e44918ac-0cc1-4e68-badc-2f563c7da837)

the url is:

https://t1.api.getabp.net:44301/Account/ResetPasswordConfirmation?returnUrl=%2Fconnect%2Fauthorize%3Fresponse_type%3Dcode

When I click on `Go to the application`, it redirects to https://t1.api.getabp.net:44301/connect/authorize?response_type=code and this error appears

```
error:invalid_request
error_description:The mandatory 'client_id' parameter is missing.
error_uri:https://documentation.openiddict.com/errors/ID2029
```

If I manually add the client_id to the url: `&client_id=BookStore_App` it works, it redirects to login page. Is there a way to have the `client_id` included in the url by default?

https://t1.api.getabp.net:44301/connect/authorize?response_type=code&client_id=BookStore_App

Appreciate the help.

**Comment by maliming** [comment]
hi

I will fix this.

**Comment by maliming** [comment]
hi @szilardd 

You can try to override the `AccountEmailer`.

see https://github.com/abpframework/abp/pull/17364

**Comment by szilardd** [comment]
Thanks, I applied the override to `AccountEmailer` as advised and it works.

```cs
[ExposeServices(typeof(IAccountEmailer))]
public class MyAccountEmailer : AccountEmailer, IAccountEmailer, ITransientDependency
{
	public MyAccountEmailer
	(
		IEmailSender emailSender,
		ITemplateRenderer templateRenderer,
		IStringLocalizer<AccountResource> stringLocalizer,
		IAppUrlProvider appUrlProvider,
		ICurrentTenant currentTenant
	) : base(emailSender, templateRenderer, stringLocalizer, appUrlProvider, currentTenant)
	{
	}

	protected override string NormalizeReturnUrl(string returnUrl)
	{
		var normalizedReturnUrl = base.NormalizeReturnUrl(returnUrl);

		// fixes 'Go to the application' url (missing `client_id` parameter) shown after resetting password
		// https://github.com/abpframework/abp/issues/17343#issuecomment-1676605493
		if (normalizedReturnUrl.StartsWith("/connect/authorize?", StringComparison.OrdinalIgnoreCase))
		{
			normalizedReturnUrl = HttpUtility.UrlEncode(normalizedReturnUrl);
                }

		return normalizedReturnUrl;
	}
}
```
