### ISSUE TITLE
ConfigureExistingProperties function not working 

### ISSUE THREAD

**Issue by AliAli93** [abpframework/abp#17384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to change the length of column "Name" and "surname" in users table from 64 to 250 
when I follow the instruction in this function in domain.shared project and try to add migration the migration always be empty 

`private static void ConfigureExistingProperties()
    {
        /* You can change max lengths for properties of the
         * entities defined in the modules used by your application.
         *
         * Example: Change user and role name max lengths

           IdentityUserConsts.MaxNameLength = 99;
           IdentityRoleConsts.MaxNameLength = 99;

         * Notice: It is not suggested to change property lengths
         * unless you really need it. Go with the standard values wherever possible.
         *
         * If you are using EF Core, you will need to run the add-migration command after your changes.
         */
        IdentityUserConsts.MaxNameLength = 256;

    }`
    what is the problem here ? and how to fix it ?

### Reproduction Steps

add this line in the function

        IdentityUserConsts.MaxNameLength = 256;

### Expected behavior

when add migration the migration contains column update sentence 

### Actual behavior

Migration always empty 

### Version

7

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

`AbpUserConsts.MaxNameLength = 256`

**Comment by AliAli93** [comment]
Thanks I did this and it works with me now @maliming
