### ISSUE TITLE
Some questions about `DAP and AAD (Oauth Login) `

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#17408]
Hello ABP Team

1. Does the ABP application save the password of uses of LDAP and AAD in local DB after logging on?
2. Do the Tenant need to Import LDAP & AAD to use the ABP login screen?
3. When the user tries to use his LDAP username and password to log in, will the ABP application check if the user is active in ActiveDirectory?

_Originally posted by @NavneetProject in https://github.com/abpframework/abp/issues/4977#issuecomment-1683567510_

**Comment by maliming** [comment]
1. No, we will get user info(username email etc.) from LDAP or AAD.
2. I don't understand your mean very well. but you can see https://docs.abp.io/en/commercial/5.0/modules/account/ldap
3. We implemented a basic LDAP feature you can customize with your business logic.

**Comment by NavneetProject** [comment]
Thanks, Maliming. I believe this feature is similar to ADFS, very powerfull
