### ISSUE TITLE
Authorization Problem with Flutter and ABP

### ISSUE THREAD

**Issue by alihassan12r** [abpframework/abp#17407]
We are currently utilizing Flutter and ABP in our project. We have created a login request that involves two steps:

1- Acquiring a token through 'connect/token'.
2- Retrieving user information via 'api/abp/application-configuration'.

While the token is successfully returned in step 1, we encounter an "Unauthorized" error in step 2.

![image](https://github.com/abpframework/abp/assets/26666796/77d7c19a-cd13-4e11-ba12-be4e3d13bd3d)

Interestingly, the authorization process works as expected when tested with Postman.

It's important to note that we are running the server on localhost. 
When we test the API on the server, the authorization returns as true.

We appreciate any assistance in resolving this issue.

**Comment by maliming** [comment]
hi

> While the token is successfully returned in step 1, we encounter an "Unauthorized" error in step 2.

Please share the full logs of this request.

Are you sure you carried the token in your request?

**Comment by alihassan12r** [comment]
Hello @maliming, sure:

![image](https://github.com/abpframework/abp/assets/26666796/677968f6-006d-4cb4-b642-f159c7fc3064)

token payload:
![image](https://github.com/abpframework/abp/assets/26666796/3c8dac47-8026-494f-8afe-139bb402ec88)

**Comment by alihassan12r** [comment]
Hello @maliming, sure:

Request:
![image](https://github.com/abpframework/abp/assets/26666796/93638961-88e5-4526-ab63-ee0793cac8dc)


Token payload:
![image](https://github.com/abpframework/abp/assets/26666796/812e0695-c766-474a-9f87-eec2bb474186)

**Comment by maliming** [comment]
Please share the full logs of this request.

**Comment by alihassan12r** [comment]
![image](https://github.com/abpframework/abp/assets/26666796/887c44dc-9991-44d6-bbeb-d54b24357c70)
