### ISSUE TITLE
Improve all Chinese localization information before 1.0 release.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1740]

**Comment by wakuflair** [comment]
Is there anything I can help?

**Comment by hikalkan** [comment]
@maliming what we will do about this?

**Comment by maliming** [comment]
I will take the time to improve all Chinese translations based on English localization before the 1.0 release. Many projects and modules have no or missing Chinese localization translations. Maybe this weekend.

**Comment by hikalkan** [comment]
We can move this to 1.1.
