### ISSUE TITLE
[BackgroundJobName] does not work in hangfire

### ISSUE THREAD

**Issue by wallee85** [abpframework/abp#17410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i create a abp proejct via abp cli, and imported hangfire followed the way described in abp document(https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire). but the [BackgroundJobName] does not work as expected.

### Reproduction Steps

 https://github.com/pangjianxin/Wallee.Boc.DataPlane.git

### Expected behavior

job name display correctly in which i defined in [BackgroundJobName] attribute.  

### Actual behavior

![image](https://github.com/abpframework/abp/assets/22126455/1765c892-3ace-4ea1-b173-93b1f3fa1c0d)

### Regression?

it's the first time i use hangfire for backgroundjob

### Version

7.3.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Try

```csharp
var options = app.ApplicationServices.GetRequiredService<AbpDashboardOptionsProvider>().Get()
options.DashboardTitle = "....";
app.UseHangfireDashboard("/hangfire", options);
```

**Comment by wallee85** [comment]
i added the code you provided  into WebModule, like this:
  `  //OnApplicationInitialization()
       ........
        var options = app.ApplicationServices.GetRequiredService<AbpDashboardOptionsProvider>().Get();
        options.DashboardTitle = "....";
        app.UseHangfireDashboard("/hangfire", options);
        app.UseConfiguredEndpoints();`

but it's still the same.did you run my code?

**Comment by realLiangshiwei** [comment]
Delete the Recurring Job and try again.

<img width="1789" alt="image" src="https://github.com/abpframework/abp/assets/16813853/8192cab4-82ff-4a30-acc7-628e6a5b91e1">

**Comment by wallee85** [comment]
whether i deleted it in dashboard or deleted it in code,just nothing hanppened.mybe i missed something in hangfire ,thank you for your time
