### ISSUE TITLE
How do I set additional connection strings when doing testing...

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1743]
Hi,

I have used the standard MVC template and am trying to write some tests inside `\src\test\MyProject.DomainTests`. My test class ultimately descends from `AbpIntegratedTest<TStartupModule>` using the sample test code provided.

I added an `appsettings.json` inside that folder with some additional connection strings viz:

![image](https://user-images.githubusercontent.com/4738140/64750881-c678ef80-d55d-11e9-99ca-f052c6a1daa4.png)

but when I attempt to access the configuration strings using:

```c#
ConfigurationManager.ConnectionStrings[]
```

I only have a SINGLE connection string of:

`{data source=.\SQLEXPRESS;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|aspnetdb.mdf;User Instance=true}`

So my question is how/where are connection strings read from? 

I tried overriding the ABP method:

```c#
   protected override void SetAbpApplicationCreationOptions(AbpApplicationCreationOptions aOptions)
        {
            base.SetAbpApplicationCreationOptions(aOptions);

            aOptions.Configuration.FileName = "BOGUS";
        }
```

but that made no difference as I got no exception when trying to load the "BOGUS" settings file (not physically on disk) either.

**Comment by maliming** [comment]
You should not use `ConfigurationManager` in asp.net core, it has its own configuration system.
see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2

**Comment by natiki** [comment]
OK so assuming I use `Configuration`, how do I make sure my appsettings.json file is read for unit tests?

Adding `string someConnectionString = Configuration["ConnectionStrings:Logging"];` does not compile. And also assuming that the code above is in a .NET Standard 2.0 assembly that is used between WebForms, MVC, .NET Core what is the agnostic way to retrieve connection strings?

**Comment by natiki** [comment]
Can anyone tell me where ABP is reading the connection strings from?

**Comment by maliming** [comment]
Abp uses `IConfigurationRoot `to read the configuration (connection string).

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationroot?view=aspnetcore-2.2

**Comment by natiki** [comment]
Ta, So how do I access that from AbpIntegratedTest<TStartupModule> to add additional appsettings.json? Or which appsettings.json is it picking up? Because that `SQLEXPRESS` connection string does not exist anywhere.

**Comment by maliming** [comment]
First of all, since it is a test, why read the contents of appsettings.json, you should simulate some data or set some information.

Or do you want to use a real database in unit testing?

**Comment by natiki** [comment]
We use a real database in unit testing so cannot use the in memory SQLLite approach presented in the templates.

**Comment by natiki** [comment]
Bump https://github.com/abpframework/abp/issues/1743#issuecomment-531615060

**Comment by natiki** [comment]
Any pointers here guys? https://github.com/abpframework/abp/issues/1743#issuecomment-531615060

**Comment by natiki** [comment]
Bump!!!

**Comment by maliming** [comment]
@natiki 
Accessing Configuration in .NET Core Test Projects.
https://weblog.west-wind.com/posts/2018/Feb/18/Accessing-Configuration-in-NET-Core-Test-Projects
