### ISSUE TITLE
Middleware not being invoked

### ISSUE THREAD

**Issue by ahmedisam99** [abpframework/abp#17457]
I have a middleware which I registered using `app.UseMiddleware<>` in my `HttpApi.Host` layer, but the middleware is not being invoked and is skipped. I moved the registration of the middleware to the `HttpApi` layer and it started working fine but when I inject the CurrentUser (i.e. check for authenticated user) it appears that the authentication flow is not done yet.

Aren't the middlewares in `HttoApi.Host` supposed to work before `HttpApi`?

Is there something wrong that I'm doing here, please help.

**Comment by maliming** [comment]
hi

> when I inject the CurrentUser (i.e. check for authenticated user) it appears that the authentication flow is not done yet.

Your `SessionMiddleware` needs to be added after the `Authentication` middleware.
