### ISSUE TITLE
How to disable Data Filtering for Host Admin?

### ISSUE THREAD

**Issue by najeeb-ullah1** [abpframework/abp#17450]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

I have created a project by using **"abp new Acme.BookStore -u angular --separate-identity-server --theme basic -csf "** which contains angular and .NET Core projects.

I want to get all the data when I am loggedIn as Host admin. And when LoggedIn with Tenant Admin only the Tenant data should be retrieved.

For Example,
I have two users. **a) host-admin    b) tenant-admin** in my database. I have an entity called as Campuses. I have inserted two records **_Campus-A_** and **_Campus-B_**. 
Campus-A has null TenantId which means that campus belongs to **host-admin**, and Campus-B has TenantId (2FD64D3A-AE84-E830-DDC6-3A0D33EE9E11) which means the Campus-B belongs to Tenant-ABC.

The Service for getting campuses is following.

 ```
public class CampusAppService:CrudAppService
        <BusinessEntities.Campus,
        CampusDto,
        Guid,
        CampusPagedResultRequestDto,
        CreateCampusDto,
        UpdateCampusDto>, ICampusAppService
    {

        public CampusAppService(IRepository<BusinessEntities.Campus,Guid> repository)
            : base(repository)
        {
        }
     }
     
     //Entity
     public class Campus:AuditedAggregateRoot<Guid>, IMultiTenant
    {
        public Guid? TenantId { get; set; }
        [Required]
        public string Name { get; set; }
  }
```

**Comment by maliming** [comment]
hi

https://docs.abp.io/en/abp/latest/Data-Filtering#idatafilter-service-enable-disable-data-filters

**Comment by najeeb-ullah1** [comment]
@maliming  I have seen this article. This will enable or disable data filter for all of the users irrespective host or tenant users. 
I want to disable data-filters for host users and enable for tenant users at the same time.

**Comment by maliming** [comment]
hi

> ABP uses [EF Core's Global Query Filters](https://docs.microsoft.com/en-us/ef/core/querying/filters) system for the [EF Core Integration](https://docs.abp.io/en/abp/latest/Entity-Framework-Core). So, it is well integrated to EF Core and works as expected even if you directly work with DbContext.

> Best way to implement a custom filter is to override ShouldFilterEntity and CreateFilterExpression method for your DbContext. 

https://docs.abp.io/en/abp/latest/Data-Filtering#entityframework-core

**Comment by najeeb-ullah1** [comment]
Thank you. Though my requirements are little different. I think I can use  custom filter to override the existing functionality.
