### ISSUE TITLE
Abp localizations "ResourceNotFound"

### ISSUE THREAD

**Issue by alihdev** [abpframework/abp#17453]
Hello,
I encountered an issue related to localization. In the following code snippet:

```c#
        var message = L["MyAccount"];
```

I expected the resulting value to be correct, but it seems that the localization is not working as intended. The actual result is shown in the screenshot below:

![image](https://github.com/abpframework/abp/assets/97635301/10206f84-a9a1-4c26-9bab-e840755807ab)

I have confirmed that the necessary key "MyAccount" has been added to the localization JSON file.

**Comment by maliming** [comment]
hi

Steps needed to reproduce the problem.

**Comment by alihdev** [comment]
Hi, thank u .. we have resolved it by adding **FileProviders.Embedded** extensions
