### ISSUE TITLE
CMS Kit: Revise reCaptcha Generator for Comment Feature

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#17454]
Whenever a new reCaptcha is generated, we store it in a static dictionary:

https://github.com/abpframework/abp/blob/d33b6dd41db1c801d46ba485ae0451be06da458f/modules/cms-kit/src/Volo.CmsKit.Public.Web/Security/Captcha/SimpleMathsCaptchaGenerator.cs#L29

`SimpleMathsCaptchaGenerator` registered as `singleton` and the dictionary is storing more and more value in every single generation, this might cause memory problems in the long term. We should revise the current design and fix this possible problem.

**Comment by enisn** [comment]
Also, we can consider storing it in a distributed cache to cover multiple instances behind load-balancer scenario
