### ISSUE TITLE
Upgrade depended NuGet packages to the latest versions

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#17464]
It is good to start this work after October 15 since we will release ABP at ~ November 15.
(including the ABP Commercial dependencies)
Please write here which package is updated from what version to which new version.

Example table:

| Package | Old Version | New Version |
| ----------- | ----------- | ----------- |
| Hangfire.AspNetCore  | 1.8.2 |  1.8.5 |

**Comment by maliming** [comment]
Package change list: https://github.com/abpframework/abp/blob/dev/docs/en/Migration-Guides/Abp-8_0.md
