### ISSUE TITLE
Abstract all db-related tests in the domain test project

### ISSUE THREAD

**Issue by jflaga** [abpframework/abp#17488]
@maliming asked me to create an issue to abstract all db-related tests in the domain. then implement these in ef and mongo test projects, because I asked the question "why does DomainTestModule depends on EntityFrameworkCoreTestModule?" [here](https://github.com/abpframework/abp/discussions/17469)

This is the content of the question:

<blockquote>

I have a question about the generated `DomainTestModule` for ABP.
There is a comment at the top saying "... however your domain tests should be database independent anyway", 

```

/* Domain tests are configured to use the EF Core provider.
 * You can switch to MongoDB, however your domain tests should be
 * database independent anyway.
 */
[DependsOn(
    typeof(SampleEntityFrameworkCoreTestModule)
    )]
public class SampleDomainTestModule : AbpModule
{

}
```

but `DomainTestModule` depends on `EntityFrameworkCoreTestModule`.

Is this a mistake? \
If it's not a mistake, is it okay, or even recommended, to remove the `DomainTestModule`'s dependency on `EntityFrameworkCoreTestModule`? \
If it's not recommended to remove it, what are the reason(s) why `DomainTestModule` depends on `EntityFrameworkCoreTestModule`?

Thanks
</blockquote>

**Comment by maliming** [comment]
> why does DomainTestModule depends on EntityFrameworkCoreTestModule

We will change this behavior. Make them independent.

**abstract all db-related tests in the domain. then implement these in ef and mongo test projects,**
