### ISSUE TITLE
Blazor Server localization problem 

### ISSUE THREAD

**Issue by elitesw** [abpframework/abp#17489]
## 1. First run form validation without localization
![q1_01](https://github.com/abpframework/abp/assets/54815375/4fc7a732-23cb-4a1b-8394-83c1a534526d)

## 2. After calling the application service and throwing an exception ( in my use case), it's done.
![q1_02](https://github.com/abpframework/abp/assets/54815375/e18cfdc3-0c42-4339-a851-3e163189ea3d)
![q1_03](https://github.com/abpframework/abp/assets/54815375/ba355bdf-1698-43ed-9fbe-aa2b018a8c14)

## 3. But DTO class property DisplayName localization invalid. （It has been written to the JSON file）
![q1_04](https://github.com/abpframework/abp/assets/54815375/004edf37-44ff-44fc-962d-d8666ff14171)

**Comment by realLiangshiwei** [comment]
Should be`DisplayName:Code` instead of `DisplayName:XXDto:Code`

You can refer to the source code of ABP: https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/Localization/en.json
https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Blazor/Pages/Identity/UserManagement.razor

**Comment by elitesw** [comment]
## Thank you for reply!  I have tried, the same. 
![image](https://github.com/abpframework/abp/assets/54815375/31d81c99-dfa3-49b9-ad96-2692cfaa7c52)
![image](https://github.com/abpframework/abp/assets/54815375/a910d703-a519-4bdb-9920-ee73d87a9a86)
## Another, What may be the reason for the lack of localization during the first run?
![q1_01](https://github.com/abpframework/abp/assets/54815375/4fc7a732-23cb-4a1b-8394-83c1a534526d)

**Comment by realLiangshiwei** [comment]
It looks like you are using a **third-party theme**
We do not support a third-party theme, 
you can create an issue in the third-party theme GitHub repository. thanks
It looks like my personal project. You can create an issue here: https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI

**Comment by elitesw** [comment]
#### Yes, the theme layout uses your project.  Thank you very much for this.  But I'm sure the problem is not on the theme.  When executing form.Validate (i.e. EditContext.Validate), the returned ValidationMessages are already in English. Validation message will only be localized when submitted to a service interface with a form.Model object.  And this english validation error message should come from ABP. Now, how do make it return to Chinese from the beginning?
![image](https://github.com/abpframework/abp/assets/54815375/12048bbb-9eac-4f48-bfd7-789b01155fff)
#### Blazor Server Module
![image](https://github.com/abpframework/abp/assets/54815375/1075560c-493f-4c92-8a74-c37d694ae3fa)

**Comment by realLiangshiwei** [comment]
Can you reproduce this problem using the ABP official template&Theme?

**Comment by elitesw** [comment]
#### Yes, the Blazor Server project generated using ABP official template. The essence of the problem is that when the Form. Validate method is executed, the validation information (data annotation) returned is still in English. already set to zh_Hans.
For example, when clicking on query in the following image.
DTO:
[StringLength(ErpUiConsts.MaxNameLength)]        
public string Name { get; set; }

![image](https://github.com/abpframework/abp/assets/54815375/0ae4a751-7221-4078-acfa-cc777d3d0c60)

**Comment by realLiangshiwei** [comment]
Please try reproduce this problem using the ABP **official template&Theme**
