### ISSUE TITLE
Cluster configuration with ApiHost & Angular UI

### ISSUE THREAD

**Issue by diennttlu** [abpframework/abp#17480]
I have deployed a dockerized, monolith deployment of ABP to a nginx cluster. When running with 1 server, everything works. When I have > 1 servers behind a load balancer, I tried to login but got an error API `https://mydomain/connect/token` Bad request/400 and some other requests. 
I have enabled  `PersistKeysToStackExchangeRedis` to ApiHost: 
```
if (bool.TryParse(configuration["Cache:IsRedis"], out bool isRedis) && isRedis)
{
    services.AddSingleton<IRedisInstance, RedisInstance>();
    services.AddSingleton<ICacheService, RedisCache>();

    var dataProtectionBuilder = services.AddDataProtection().SetApplicationName("MyProjectName");
    var cache = services.BuildServiceProvider().GetService<IRedisInstance>();
    dataProtectionBuilder.PersistKeysToStackExchangeRedis(cache.GetInstance(), "MyProjectName-Protection-Keys");
}
```
I check Redis-Cache and it shows that data-protection-keys has been added to the cache:
![image](https://github.com/abpframework/abp/assets/36124566/7dd216c5-c16b-47fe-acb0-f31d0d2d4dd3)
***
The frontend application and APIs run on the same domain, following to: `MapFallbackToFile`
***

I need to do to properly enable a clustered environment or have I completed the necessary steps?
ABP Framework version: 6.0.0.0.
UI type: Angular
DB provider: EF Core, IdentityServer4

**Comment by maliming** [comment]
>  Bad request/400 and some other requests.

What are the logs?

**Comment by diennttlu** [comment]
I am missing this configuration:
```
 builder.Services.AddIdentityServer()
     .AddOperationalStore(ops => ops.RedisConnectionMultiplexer = cache.GetInstance())
     .AddRedisCaching(ops => ops.RedisConnectionMultiplexer = cache.GetInstance());
```
 now how do I add it to IdentityModule?

**Comment by maliming** [comment]
hi

I'm not familiar with IdentityModule.

**Comment by diennttlu** [comment]
so how do i add the AddOperationalStore and AddRedisCaching configuration for IdentityServer4 in my repository?

**Comment by maliming** [comment]
hi

```
  
  PreConfigure<IIdentityServerBuilder>(identityServerBuilder =>
  {
      identityServerBuilder..AddOperationalStore(ops => ops.RedisConnectionMultiplexer = cache.GetInstance())
     .AddRedisCaching(ops => ops.RedisConnectionMultiplexer = cache.GetInstance());
  });
```

**Comment by diennttlu** [comment]
hi. I logged in on angular client interface and it throws this error:
```
2023-08-22 08:09:58.117 +00:00 [INF] Request starting HTTP/1.0 POST http://mydomain.com/connect/token application/x-www-form-urlencoded 231
2023-08-22 08:09:58.117 +00:00 [INF] CORS policy execution successful.
2023-08-22 08:09:58.118 +00:00 [INF] The request address matched a server endpoint: "Token".
2023-08-22 08:09:58.118 +00:00 [INF] The token request was successfully extracted: {
  "grant_type": "authorization_code",
  "code": "[redacted]",
  "redirect_uri": "http://mydomain.com",
  "code_verifier": "aVBPWGtGVkhBak5wSHJ6bndzeng1QW1sdVFTM1V4Q3JoaTJaVF9NbUhBMzBv",
  "client_id": "WebMaster_App"
}.
2023-08-22 08:09:58.140 +00:00 [INF] The response was successfully returned as a JSON document: {
  "error": "invalid_grant",
  "error_description": "The specified token is invalid.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2004"
}.
```

**Comment by maliming** [comment]
This is the log from `openiddict` but you say you are using `IdentityServer`.
