### ISSUE TITLE
How to remove AddDeveloperSigningCredential from Identity server for non development environment.

### ISSUE THREAD

**Issue by dreamerNcoder** [abpframework/abp#1749]
Hi, 

I am trying to get rid of tempkey.rsa, but due not able to do so. 

https://github.com/abpframework/abp/blob/c836349ccadffba277a1e851ea16015bd7f2cd8c/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AbpIdentityServerDomainModule.cs#L46

Any idea how to achieve ?

**Comment by maliming** [comment]
It is not currently possible to change it, as you can see in the source code.
We should improve it before the next version. @hikalkan  Any ideas?

**Comment by hikalkan** [comment]
I will work on this. Thank you.

**Comment by hikalkan** [comment]
For non development environment, override `PreConfigureServices` in your module and PreConfigure the `IIdentityServerBuilder` as shown below:

````csharp
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<IIdentityServerBuilder>(identityServerBuilder =>
    {
        identityServerBuilder.AddSigningCredential(...);
    });
}
````

For more information, see IdentityServer's documentation: http://docs.identityserver.io/en/latest/topics/startup.html#key-material

**Comment by hikalkan** [comment]
When you call AddSigningCredential, it will override services registered in the AddDeveloperSigningCredential. But if you want that ABP doesn't call AddDeveloperSigningCredential at all, you can do that in the next version (I just added https://github.com/abpframework/abp/commit/c80de66b4fcef70215b06d1c014a50de1167ca4c):

````csharp
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<AbpIdentityServerBuilderOptions>(identityServerBuilder =>
    {
        identityServerBuilder.AddDeveloperSigningCredential = false;
    });
}
````
