### ISSUE TITLE
Angular schematics creates invalid template for selected theme

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#17493]
Related https://github.com/abpframework/abp/issues/17157

### For the re-produce
`abp new VisionAiGeotabConnector -u angular -d mongodb --theme basic -csf -t app`

It must configure app.module and angular.json for theme-basic module

**Comment by mahmut-gundogdu** [comment]
Angular schema does not has change module ability for a now. We should add the functionalty but it is not bug. It is lack of feature.

**Comment by rashedjawda** [comment]
Is this mean we should keep reference lepton-x theme even if we are using basic theme ?

or you mean we have to change the code manually after generation ?

**Comment by masum-ulu** [comment]
> Is this mean we should keep reference lepton-x theme even if we are using basic theme ?
> or you mean we have to change the code manually after generation ?

Hi, no CLI will configure styles and module imports depends on your `--theme` arg

**Comment by mahmut-gundogdu** [comment]
the implementation finished. We may check the issue after the 7.4 final released. It probably will fixed.
