### ISSUE TITLE
ABP Angular APP throwing Web Socket failed

### ISSUE THREAD

**Issue by cgdif** [abpframework/abp#17505]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests, and other discussions about the framework.

If you're creating a bug/problem report, please include the followings:

* Your **ABP CLI 7.3.1**.
* Angular
* EF Core
* WebSocket connection to 'ws://some-ip/cgdbt/ng-cli-ws' failed: 
*hosted APP on local IP, added public IP to access the API and APP.

Please **write in English**.

**Comment by Sinan997** [comment]
i didn't understand the problem fully, could you give detail
