### ISSUE TITLE
How to update/delete detail model in Master-Detail scenario?

### ISSUE THREAD

**Issue by SaeedSpate** [abpframework/abp#1750]
How to `UPDATE/DELETE` detail model in `Master-Detail scenario` using EF EntityState?
Any settings needed in `DBContext` file or any where?
It's possible in `ABP`?

**Comment by SaeedSpate** [comment]
@hikalkan @maliming 
Can you please help me?

**Comment by maliming** [comment]
hi @SaeedSpate 
Can you explain it in detail? I don't understand it.

**Comment by SaeedSpate** [comment]
Hi @maliming 

Master entity:
```
    public class ClientInfo : FullAuditedAggregateRoot<Guid>
    {
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }
        public virtual DateTime BirthDate { get; set; }
        public virtual GenderType Gender { get; set; }
        public virtual string IdentityNumber { get; set; }
        public virtual string Phone { get; set; }
        public virtual string Mobile { get; set; }
        public virtual string Address { get; set; }
        public virtual string Email { get; set; } = null;
        public virtual string Country { get; set; }
        public virtual string Province { get; set; }
        public virtual string City { get; set; }
        public virtual bool IsActive { get; set; }

        public virtual ICollection<CompanionInfo> CompanionInfos { get; set; } = new HashSet<CompanionInfo>();
    }
```
Detail entity:
```
    public class CompanionInfo : Entity<Guid>
    {
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }
        public virtual DateTime BirthDate { get; set; }
        public virtual GenderType Gender { get; set; }
        public virtual string IdentityNumber { get; set; }
        public virtual string Phone { get; set; }
        public virtual string Mobile { get; set; }
        public virtual string Address { get; set; }
        public virtual Guid ClientInfoId { get; set; }
        public virtual CompanionTypes CompanionType { get; set; }
        public virtual ClientInfo ClientInfo { get; set; }
    }
```
Insert new data to this model is worked! but i can't update exist `Companion` Info and received error for duplicate data!

**Comment by maliming** [comment]
You can try using `AutoMapper.Collection`
see: 
https://support.aspnetzero.com/QA/Questions/7581#answer-5975b8e7-3f78-e17a-01b1-39f007199ca4

**Comment by SaeedSpate** [comment]
Hi @maliming 
My AutoMapper profile is:
```
namespace TH.Clients
{
    public class ClientInfoApplicationAutoMapperProfile : Profile
    {
        public ClientInfoApplicationAutoMapperProfile()
        {
            CreateMap<ClientInfo, ClientInfoDto>().ReverseMap();
            CreateMap<ClientInfo, CreateUpdateClientInfoDto>().ReverseMap();
            CreateMap<CompanionInfo, CompanionInfoDto>().ReverseMap();
        }
    }
}
```
How to work with `AutoMapper.Collection`?

**Comment by hitaspdotnet** [comment]
@SaeedSpate 
```C#
    public class CreateUpdateClientInfoDto : EntityDto<Guid?>
    {
        public List<CreateUpdateCompanionInfoDto> CompanionInfos { get; set; } = new List<CreateUpdateCompanionInfoDto>();
    }
```
And add this to your mapper profile
```c#
CreateMap<CreateUpdateCompanionInfoDto, CompanionInfo>().ReverseMap();
```
DONE.

This is not related to ABP. Please use https://stackoverflow.com and ask your question then tag your question with `AutoMapper` `DTO`.

**Comment by SaeedSpate** [comment]
@hitaspdotnet 
My original question is:
> How to `UPDATE/DELETE` detail model in `Master-Detail scenario` using EF EntityState?
> Any settings needed in `DBContext` file or any where?
> It's possible in `ABP`?

and not about AutoMapper!
@maliming  told me to use AutoMapper.Collection!

I can add to detail model but can't  update them!
By the way, my question is: `How to UPDATE/DELETE detail model?`

**Comment by hitaspdotnet** [comment]
This is depends on your case. Based on your code attachment you need to do this manually and check every inputs for duplicates before create or update. 
**OR** =>  You can use [Collection of Owned Entity Types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#collections-of-owned-types). Then as @maliming suggestion use `AutoMapper.Collection` like my previous comment. You can set properties as key and let EF do jobs for you. 

_[Extra Resource](https://www.nankov.com/posts/improved-support-value-objects-ef-core-22)_

**Comment by SaeedSpate** [comment]
Hi @hitaspdotnet @maliming 
I think is better to you added `EntityFramwork ChangeTracker` to `ABP` at `FullAuditedAggregateRoot`!
It's so cool to send modification state to `API` and `APB` know about **Added/Modified/Deleted/Unchanged** entity.

**Comment by maliming** [comment]
hi @SaeedSpate  We can't do this. `FullAuditedAggregateRoot` has nothing to do with EF Core.  You might not even use EF Core (like using MongoDb), which requires a high degree of separation and abstraction.
