### ISSUE TITLE
Value cannot be null. (Parameter 'ExtraProperties') Mongodb Cmskit and other possible modules

### ISSUE THREAD

**Issue by sharmawaiaman** [abpframework/abp#17521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[ERR] Value cannot be null. (Parameter 'ExtraProperties')
System.ArgumentNullException: Value cannot be null. (Parameter 'ExtraProperties')
at Volo.Abp.Check.NotNull[T](T value, String parameterName)
at Volo.Abp.ObjectExtending.ExtensibleObjectMapper.MapExtraPropertiesTo[TSource,TDestination](TSource source, TDestination destination, Nullable1 definitionChecks, String[] ignoredProperties) at Volo.Abp.ObjectExtending.HasExtraPropertiesObjectExtendingExtensions.MapExtraPropertiesTo[TSource,TDestination](TSource source, TDestination destination, Nullable1 definitionChecks, String[] ignoredProperties)
at Volo.Payment.Admin.Plans.PlanAdminAppService.UpdateAsync(Guid id, PlanUpdateInput input)

### Reproduction Steps

create a abp commercial mvc project with cmskit included with mongodb as a provider.

Error occurs when updating a blog

Investigated the issue. it only occurs when an entity doesn't have a parameter less constructor. 

i see it has been added to IdentityUsers but there is no parameter less constructor for CMSkit Blogs entity

![image](https://github.com/abpframework/abp/assets/94415615/b6e612f5-666f-43da-ad4b-b655db0944d2)

`input.MapExtraPropertiesTo(dd);` will give error because dd.extraproperty is null.

### Expected behavior

Extraproperties should not be null

### Actual behavior

Extraproperties is null when fetching from db only when provider is mongodb 

### Known Workarounds

Written a Custom Mongodb Serializer

### Version

7.3.2

### User Interface

Common (Default)

### Database Provider

MongoDB

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by ebicoglu** [comment]
reported at https://support.abp.io/QA/Questions/5650

**Comment by enisn** [comment]
Similar problem with https://github.com/abpframework/abp/issues/17285#issuecomment-1666496809

**Comment by sharmawaiaman** [comment]
reported here also https://support.abp.io/QA/Questions/5600
