### ISSUE TITLE
1.90  SignInManager not work

### ISSUE THREAD

**Issue by xgd224743** [abpframework/abp#1752]
HI!
Need a help,
override account
--------------------
i'm create .web project pages/accounts/login.cshtml , 
login.cshtml.cs
[UnitOfWork]
        public virtual async Task<IActionResult> OnPostAsync()
        {  
            ValidateModel();

            // await ReplaceEmailToUsernameOfInputIfNeeds();

            var result = await SignInManager.PasswordSignInAsync(

              LoginInput.UserNameOrEmailAddress,
           LoginInput.Password,
             LoginInput.RememberMe, true
             );

            
            return RedirectSafely(ReturnUrl, ReturnUrlHash);
        }
   but run project  error 
NullReferenceException: Object reference not set to an instance of an object.
WGO.UAM.Web.Pages.Accounts.LoginModel.OnPostAsync() in Login.cshtml.cs
+
            var result = await SignInManager.PasswordSignInAsync(

What do I need to do.

**Comment by maliming** [comment]
> Object reference not set to an instance of an object.

Is `SignInManager` null? Please share the full code.

**Comment by xgd224743** [comment]
yes ,SignInManager is null.
Full Code
-------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options; 
using Volo.Abp.Identity;
using Volo.Abp.Uow;
using Volo.Abp.Validation;
using WGO.UAM.Accounts;
using WGO.UAM.Users;  

namespace WGO.UAM.Web.Pages.Accounts
{
    public class LoginModel : UAMPageModel
    {
        [HiddenInput]
        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; }

        [HiddenInput]
        [BindProperty(SupportsGet = true)]
        public string ReturnUrlHash { get; set; }

        [BindProperty]
        public LoginInputModel LoginInput { get; set; }

        public LoginModel()
        {

        }

        public virtual void OnGet()
        {

        }

        [UnitOfWork]
        public virtual async Task<IActionResult> OnPostAsync()
        {  
            ValidateModel();

            // await ReplaceEmailToUsernameOfInputIfNeeds();

            var result = await SignInManager.PasswordSignInAsync(

              LoginInput.UserNameOrEmailAddress,
           LoginInput.Password,
             LoginInput.RememberMe, true
             );

            if (result.RequiresTwoFactor)
            {
                return RedirectToPage("./SendSecurityCode", new
                {
                    returnUrl = ReturnUrl,
                    returnUrlHash = ReturnUrlHash,
                    rememberMe = LoginInput.RememberMe
                });
            }

            if (result.IsLockedOut)
            {
                Alerts.Warning(L["UserLockedOutMessage"]);
                return Page();
            }

            if (result.RequiresTwoFactor)
            {
                return RedirectToPage("./SendSecurityCode");
            }
          

            if (result.IsNotAllowed)
            {
                Alerts.Warning(L["LoginIsNotAllowed"]);
                return Page();
            }

            if (!result.Succeeded)
            {
                Alerts.Danger(L["InvalidUserNameOrPassword"]);
                return Page();
            }

            //TODO: Find a way of getting user's id from the logged in user and do not query it again like that!
            //var user = await UserManager.FindByNameAsync(LoginInput.UserNameOrEmailAddress) ??
            //           await UserManager.FindByEmailAsync(LoginInput.UserNameOrEmailAddress);

             
            return RedirectSafely(ReturnUrl, ReturnUrlHash);
        }

        protected virtual async Task ReplaceEmailToUsernameOfInputIfNeeds()
        {
            if (!ValidationHandler.IsValidEmailAddress(LoginInput.UserNameOrEmailAddress))
            {
                return;
            }

            var userByUsername = await UserManager.FindByNameAsync(LoginInput.UserNameOrEmailAddress);
            if (userByUsername != null)
            {
                return;
            }

            var userByEmail = await UserManager.FindByEmailAsync(LoginInput.UserNameOrEmailAddress);
            if (userByEmail == null)
            {
                return;
            }

            LoginInput.UserNameOrEmailAddress = userByEmail.UserName;
        }

        public class LoginInputModel
        {
            [Required]
            [StringLength(IdentityUserConsts.MaxEmailLength)]
            public string UserNameOrEmailAddress { get; set; }

            [Required]
            [StringLength(IdentityUserConsts.MaxPasswordLength)]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            public bool RememberMe { get; set; }
        }
    }
}

**Comment by xgd224743** [comment]
this code copy moulds account , only change name to accounts.

**Comment by maliming** [comment]
Where is the initialization code for `SignInManager`?

**Comment by xgd224743** [comment]
public abstract class UAMPageModel : AbpPageModel
    {
        protected UAMPageModel()
        {
            LocalizationResourceType = typeof(UAMResource);
        }

        public Microsoft.AspNetCore.Identity.SignInManager<IdentityUser> SignInManager { get; set; }
        public IdentityUserManager UserManager { get; set; }
        public Microsoft.Extensions.Localization.IStringLocalizer<UAMResource> L { get; set; }

        protected Microsoft.AspNetCore.Mvc.RedirectResult RedirectSafely(string returnUrl, string returnUrlHash = null)
        {
            return Redirect(GetRedirectUrl(returnUrl, returnUrlHash));
        }

        protected void CheckIdentityErrors(Microsoft.AspNetCore.Identity.IdentityResult identityResult)
        {
            if (!identityResult.Succeeded)
            {
                throw new UserFriendlyException("Operation failed: " + identityResult.Errors.Select(e => $"[{e.Code}] {e.Description}").JoinAsString(", "));
            }

            //identityResult.CheckErrors(LocalizationManager); //TODO: Get from old Abp
        }

        private string GetRedirectUrl(string returnUrl, string returnUrlHash = null)
        {
            returnUrl = NormalizeReturnUrl(returnUrl);

            if (!returnUrlHash.IsNullOrWhiteSpace())
            {
                returnUrl = returnUrl + returnUrlHash;
            }

            return returnUrl;
        }

        private string NormalizeReturnUrl(string returnUrl)
        {
            if (returnUrl.IsNullOrEmpty())
            {
                return GetAppHomeUrl();
            }

            if (Url.IsLocalUrl(returnUrl))
            {
                return returnUrl;
            }

            return GetAppHomeUrl();
        }
         
        protected virtual void CheckCurrentTenant(Guid? tenantId)
        {
            if (CurrentTenant.Id != tenantId)
            {
                throw new ApplicationException($"Current tenant is different than given tenant. CurrentTenant.Id: {CurrentTenant.Id}, given tenantId: {tenantId}");
            }
        }

        protected virtual string GetAppHomeUrl()
        {
            return "/"; //TODO: ???
        }
    }

**Comment by xyfy** [comment]
hey ,what is the probelem?I got the `IdentityUserManager ` null ...

are you resolved this issuse??  @xgd224743
