### ISSUE TITLE
IUserValidator custom implementation always returns `Identity.Default`.

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#17539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Roughly consistent with what this #14889 described, the only difference is that custom validation always returns `Identity.Default`.

### Reproduction Steps

[The demo app:](https://cdn-1255895673.cos.ap-chengdu.myqcloud.com/Acme.BookStore.rar)

Run the program and call the `/api/app/account/register` interface twice via swagger and using the same request parameters.
ex:
```
{
  "userName": "test",
  "emailAddress": "user@example.com",
  "phoneNumber": "13888888888",
  "password": "1q2w3E*"
}
```

### Expected behavior

Before calling the CheckErrors, the identityResult value:
```
{"Succeeded":false,"Errors":[{"Code":"DuplicateUserName","Description":"Username 'test' is already taken."},{"Code":"DuplicateEmail","Description":"Email 'user@example.com' is already taken."},{"Code":"Volo.Abp.Identity:010013","Description":"手机号 13888888888 已被使用."}]}
```

After calling CheckErrors, the interface returns:
```
{"error":{"code":"Volo.Abp.Identity:DuplicateUserName","message":"用户名 'test' 已存在., 邮箱 'user@example.com' 已存在., 手机号 13888888888 已被使用.","details":null,"data":{"0":"test"},"validationErrors":null}}
```

### Actual behavior

Before calling the CheckErrors, the identityResult value:
```
{"Succeeded":false,"Errors":[{"Code":"DuplicateUserName","Description":"Username 'test' is already taken."},{"Code":"DuplicateEmail","Description":"Email 'user@example.com' is already taken."},{"Code":"Volo.Abp.Identity:010013","Description":"手机号 13888888888 已被使用."}]}
```

After calling CheckErrors, the interface returns:
```
{"error":{"code":"Volo.Abp.Identity:DuplicateUserName","message":"用户名 'test' 已存在., 邮箱 'user@example.com' 已存在., Identity.Default","details":null,"data":{"0":"test"},"validationErrors":null}}
```

### Known Workarounds

[Line of code](https://github.com/abpframework/abp/blob/51c742ec6474e26f899adc03066cdc4303fb311d/modules/identity/src/Volo.Abp.Identity.Domain/Microsoft/AspNetCore/Identity/AbpIdentityResultExtensions.cs#L125)

Should this line of code be `return error.Description;`?

### Version

7.3.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
You can use identity standard error: `Volo.Abp.Identity:{error.Code}`
