### ISSUE TITLE
Not wrapping the books components with the main or defined ApplicationLayoutComponent..

### ISSUE THREAD

**Issue by ThapeloDev** [abpframework/abp#1753]
https://github.com/abpframework/abp/blob/c836349ccadffba277a1e851ea16015bd7f2cd8c/samples/BookStore-Angular-MongoDb/angular/src/app/books/books-routing.module.ts#L9

Hi, Should this not be **ApplicationLayoutComponent** instead of the **BooksComponent**?
Because if I followed the example correctly it does not seem to wrap the book view into the ApplicationLayout but is displayed as a separate own separate view.

**Comment by mehmet-erim** [comment]
Hi,

The parent component of BooksModule is ApplicationLayoutComponent.  [Check the app-routing.module.ts](https://github.com/abpframework/abp/blob/c836349ccadffba277a1e851ea16015bd7f2cd8c/samples/BookStore-Angular-MongoDb/angular/src/app/app-routing.module.ts#L37)

The role of BooksComponent is to wrap the BooksModule components. But in that case, BooksComponent looks unnecessary. I will remove it.
