### ISSUE TITLE
use blazor-server template，when running, click the home menu, prompting 404

### ISSUE THREAD

**Issue by ihoeysun** [abpframework/abp#17541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Build the project with the following command：
```
abp new Acme.BookStore -u blazor-server -dbms MySQL -csf 
```
step 1 : init database
step 2:  build and run the Acme.BookStore

![image](https://github.com/abpframework/abp/assets/41185330/feaab5d8-f4b7-46fd-8493-4f46ba852a8f)

how to do?need any additional settings? i need help,thanks~

### Version

7.3.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
I could not reproduce the problem.

<img width="1812" alt="image" src="https://github.com/abpframework/abp/assets/16813853/6a63d014-3d35-49a2-8e85-59483e02d14a">

**Comment by ihoeysun** [comment]
> I could not reproduce the problem.
> 
> <img alt="image" width="1812" src="https://user-images.githubusercontent.com/16813853/265313660-6a63d014-3d35-49a2-8e85-59483e02d14a.png">

Glad to receive your reply,
I think it's a problem with my computer environment. I ran it successfully on another computer.
