### ISSUE TITLE
Multi lingual entities 

### ISSUE THREAD

**Issue by SVronskiy** [abpframework/abp#1754]
Hello!

[Multi lingual entities](https://github.com/aspnetboilerplate/aspnetboilerplate/tree/dev/src/Abp/Domain/Entities) were realized recently in ASP.NET Boilerplate [Entites](https://aspnetboilerplate.com/Pages/Documents/Multi-Lingual-Entities).

It supports IMultiLingualEntity, IEntityTranslation, Translations, MultiLingualMap, MultiLingual CRUD operation.

Please, realize, multi-lingual entities in Abp.Io [Entites](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities).

Regards, Sergey

**Comment by a-patel** [comment]
Any update on this?

**Comment by maliming** [comment]
There are currently no plans to implement it, it is still backlog.

**Comment by yozzozo** [comment]
+1 for this feature!

**Comment by tntwist** [comment]
Hi there,

I would like to contribute to this feature, since I need this feature for my projects and I already have some of the Components(Generic MultiLinuaglEntity/AggregateRootTypes, a MultiLingualManager Service and the MultiLingualMap). 

@maliming Would it be ok for you, if I work on it?

**Comment by maliming** [comment]
Hi @tntwist We always welcome contributions.

**Comment by tntwist** [comment]
Great. I forked the repo and started the implementation. Just got the base types and interfaces today.

Everyone interested can track the progess here: [tntwist/feat/multilingual-entities](https://github.com/tntwist/abp/tree/feat/multilingual-entities). Open for any kind of feedback and help.

**Comment by realLiangshiwei** [comment]
@tntwist  Hi, Are you still working on this? I will implement this feature, if you don't have time.

**Comment by tntwist** [comment]
> @tntwist  Hi, Are you still working on this? I will implement this feature, if you don't have time.

@realLiangshiwei I was pretty busy the last two  weeks and wont have time to work on it till mid of september. So you can implement it.

**Comment by kion-admin** [comment]
abp boilerplate was filter current language row in memory after get all rows from db, we'd better offer this as an option

**Comment by MooazHammam** [comment]
any updates regard this issue, is it planned to be released soon

**Comment by muratyuceer** [comment]
we are waiting

**Comment by yozzozo** [comment]
Hi @maliming, @realLiangshiwei and @hikalkan, just wondering what the current status of this feature is.  This issue and #5265 are closed, but according to the latest Roadmap, it’s still on the backlog (as of 4.3 final).  Can you please clarify?

Thanks!

**Comment by maliming** [comment]
@yozzozo This feature has been canceled.

**Comment by yozzozo** [comment]
@maliming May I ask why?  I think this feature is very important for a lot of people (including myself).  I see some commits were made for this, I’d like to understand what happened and offer assistance if I can.

Thanks!

**Comment by maliming** [comment]
hi @yozzozo 

Object mapping methods are `sync` now, but the feature needs to use `Repository`, we don't want `async over sync`.

**Comment by yozzozo** [comment]
@hikalkan Any context you can provide here?  Is there a way the feature can be redesigned so it can work in the current state of the system?  I think many of us would appreciate being able to have multi-lingual entities on ABP, the feature was really useful on aspboilerplate.

**Comment by mtozlu** [comment]
I actually implemented this system in a private project. 
I would like to share it however i am not sure it will be 100% compliant with abp's design guidelines. That's why i didn't create a PR until now.
How can i help about this @maliming / @hikalkan ? 
Maybe you can check my codes and make some reviews to make it ready for abp codebase?

**Comment by maliming** [comment]
@mtozlu 

Did you encounter `async over sync` problems when you tried to use Repository?

**Comment by mtozlu** [comment]
No i didn't. 
Where exactly current implementation causes async over sync problems?
Is it here:
https://github.com/abpframework/abp/pull/5265/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.xml&file-filters%5B%5D=.xsd#diff-12d9de60ded6db704708126614e4f4610e3eb0a6636c7208296742ba9ecb5699R31

**Comment by maliming** [comment]
We don't want to use `AsyncHelper`.

**Comment by mtozlu** [comment]
Oh i remember now... I walked the same path. That's why I don't use any async call in `GetTranslations` method.
Actually the only async call needed is `SettingProvider.GetOrNullAsync` call, which is needed in case no translations can be found from CurrentCulture and CurrentCulture's parent cultures. 
That's why I always use sync version GetTranslations method of `MultiLingualObjectManager`
I found two solutions (which you may not like as I mentioned in my comment about guidelines):
1- GetTranslations method should include a `default culture` property which you can get from SettingProvider before calling the method and pass.
2- Create a default language as a constant property and use it in GetTranslations method. (I use this. In case of changing the default language, a new deployment is needed which I never came across however in some scenarios, this may be unacceptable):
Here is that portion of my implementation:
```csharp
// Can't make async calls, disable this:
//var defaultLanguage = await SettingProvider.GetOrNullAsync(LocalizationSettingNames.DefaultLanguage);
// Use this:
var defaultLanguage = PortalConsts.DefaultLanguage;
```

**Comment by muratyuceer** [comment]
soo because of async willl you cancel it ?

**Comment by jfmeyers** [comment]
+1 for this feature!

**Comment by okains** [comment]
+1 for this feature also.  I have been waiting on this implementation for a while now.  Is there no workaround for the mapping issue?  How about @mtozlu implementation?

> hi @yozzozo
> 
> Object mapping methods are `sync` now, but the feature needs to use `Repository`, we don't want `async over sync`.

**Comment by ghost** [comment]
+1 for this feature

**Comment by hitaspdotnet** [comment]
My suggestion is using `string DefaultLanguage` property in MultiLingual class, or a solution around [my issue](https://github.com/abpframework/abp/issues/1832#issuecomment-539673995) with using a key value dictionary.
For who looking for a workaround for integrate multi lingual entities, I was shared a module 
https://github.com/hitaspdotnet/Volo.Abp.MultiLingualObjects

**Comment by sel-carlitos** [comment]
+1 for this feature!

**Comment by imabdulsal** [comment]
> @yozzozo This feature has been canceled.

Do those PRs (https://github.com/abpframework/abp/pull/5265 & https://github.com/abpframework/abp/pull/8156) mean Multi-lingual entity feature will be shipped soon?
