### ISSUE TITLE
AutoFac resolution issue when writing a test.....

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#1755]
Hi,

Apologies for the length of this and the amount of code, but I need to get this working....

I have used the standard MVC template and am trying to write some tests inside \src\test\MyProject.DomainTests. My test class ultimately descends from AbpIntegratedTest<TStartupModule> using the sample test code provided.

Using NUnit my text class is as follows:

```c#
[TestFixture]
public class OzCyPlatformOzPlacesDomainServiceTests : OzCyDomainTestBase
{
    private IOzCyPlatformOzPlacesDomainService _OzCyPlatformOzPlacesDomainService;

    /// <summary>
    ///     Called at the conclusion of all the unit tests.
    /// </summary>
    protected override void Init()
    {
        base.Init();

        _OzCyPlatformOzPlacesDomainService = TestServiceScope.ServiceProvider.GetService<IOzCyPlatformOzPlacesDomainService>();
    }
}
```

but my Init() test is failing with:

ActivatorChain: OzCruisingSystem.Domain.GbGb.DomainServices.PlatformOzPlaces.OzCyPlatformOzPlacesDomainService

>   ----> Autofac.Core.DependencyResolutionException : None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'OzCruisingSystem.Domain.GbGb.DomainServices.PlatformOzPlaces.OzCyPlatformOzPlacesDomainService' can be invoked with the available services and parameters:
> Cannot resolve parameter 'OzCruisingSystem.Domain.Shared.GbGb.Repositories.IOzCyPlatformOzPlacesRepository aTableRepository' of constructor 'Void .ctor(OzCruisingSystem.Domain.Shared.GbGb.Repositories.IOzCyPlatformOzPlacesRepository)'.
>   Exception doesn't have a stacktrace
> 

however the test class ultimately includes the following module which is pretty much everything in the solution:

```c#
[DependsOn(
    typeof(OzCruisingSystemEntityFrameworkCoreTestModule),
    typeof(OzCruisingSystemDomainModule),
    typeof(OzCruisingSystemDomainSharedModule)
    )]
public class OzCruisingSystemDomainTestModule : AbpModule
{

}
```

I include the other referenced classes here for completeness:

```c#
public abstract class OzCruisingSystemDomainServiceBase : DomainService

public abstract class OzCyDomainServiceBase<TRepository, TEntity, TCrudFieldValues, TPrimaryKey> : OzCruisingSystemDomainServiceBase,
                                                                                                       IOzCyDomainServiceBase<TEntity, TCrudFieldValues, TPrimaryKey, TRepository>

public class OzCyPlatform_OzPlacesTableModel : Entity<long>, IOzCtPlatformOzPlacesFields

public interface IOzCyPlatformOzPlacesRepository : IRepository<OzCyPlatform_OzPlacesTableModel, long>

public class OzCyPlatformOzPlacesDomainService : OzCyDomainServiceBase<IOzCyPlatformOzPlacesRepository, OzCyPlatform_OzPlacesTableModel, OzCtPlatformOzPlacesFields, long>,
                                                 IOzCyPlatformOzPlacesDomainService

```

As ultimately IOzCyPlatformOzPlacesRepository inherits ABP IRepository I cannot see what the issue is. This same class hierarchy works fine in the original ABP Boilierplate.

Any pointers appreciated.

**Comment by maliming** [comment]
Can you share a project that reproduces the problem?

**Comment by natiki** [comment]
Can I post that via PM or something? Don't really want to post my entire solution here on a public forum.

**Comment by maliming** [comment]
You can use the CLI to create a simple project to reproduce your problem. I believe it won't have much code.

**Comment by natiki** [comment]
Not so easy.... As I then have to port over all my code to that to get it into the same state. I assume there is nothing obvious from what I already posted?

**Comment by ZouZou** [comment]
Were you able to solve this issue?
