### ISSUE TITLE
Cms Kit- Markdown Render Issue

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#17567]
![image](https://github.com/abpframework/abp/assets/58659931/ac5c125d-f0a8-4087-9400-74b3edd804ab)
![image](https://github.com/abpframework/abp/assets/58659931/d823380a-78e5-490b-b87e-373e7aeac438)

As you can see, it evaluates text that starts with "[Widget" and ends with "]" as a widget and removes it from the content. However, I wanted to include a link, for example. Another issue is that it completely deletes the "---" part instead of rendering it.

**Comment by ebicoglu** [comment]
test against XSS
