### ISSUE TITLE
When use the automatic registration service, there is duplicate data

### ISSUE THREAD

**Issue by qzwzqty** [abpframework/abp#1757]
1. auto registration
* create a class `TestClass` implements `ITransientDependency` or `ISingletonDependency` or `IScopedDependency` or use `[Dependency(ServiceLifetime.Singleton, ReplaceServices = false)]`
* Resolve Service by `var services = context.ServiceProvider.GetServices<TestClass>()` or `IServiceProvider`
* result `services.Count() = 2`
![{)XE$3B@4U@Q750_L(3_11F](https://user-images.githubusercontent.com/23160268/64946198-e2a1c700-d8a4-11e9-9fcd-72ccfcb218aa.png)
![LNVL1R$LP%`2R832T`E)7FT](https://user-images.githubusercontent.com/23160268/64946199-e3d2f400-d8a4-11e9-9ebf-fba6f1eae152.png)
2. manually registration
![15 JAIFQMMCNS90QWDYITO7](https://user-images.githubusercontent.com/23160268/64946341-3ca28c80-d8a5-11e9-9dab-3efa4835423a.png)
![~{YLZY8PKKECZA TCWOJ Q1](https://user-images.githubusercontent.com/23160268/64946344-3d3b2300-d8a5-11e9-8027-6ad29ffa1823.png)

how do I use this? thanks!

**Comment by maliming** [comment]
The steps to reproduce the problem?

**Comment by qzwzqty** [comment]
@maliming 
1. Create a class implement `ISingletonDependency ` or use [Dependency(ServiceLifetime.Singleton, ReplaceServices = false)]
2. Resolve Service by `var services = context.ServiceProvider.GetServices<TestClass>()` or use `IServiceProvider`
3.result `services.Count() = 2`

Demo:
There are three classes：TestClass1、TestClass2、TestClass3
https://github.com/qzwzqty/TestProject/tree/master/src/TestProject.Application

Resolve Service ：
https://github.com/qzwzqty/TestProject/blob/master/src/TestProject.Application/TestProjectApplicationModule.cs#L37
