### ISSUE TITLE
*.Web.Tests test project is not created using ABP CLI

### ISSUE THREAD

**Issue by jflaga** [abpframework/abp#17571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I executed this command to create a new ABP app (multi-layer, MCV app)

``` terminal
abp new Acme.BookStore --tiered
```

![image](https://github.com/abpframework/abp/assets/108422823/3e5dd869-cf0c-4210-aacb-c2562ea0df1b)

But no `*.Web.Tests` project was generated:

![image](https://github.com/abpframework/abp/assets/108422823/d3d519e2-2999-4623-9aa3-2be42d26efda)

### Reproduction Steps

Run this in terminal:

``` terminal
abp new Acme.BookStore --tiered
```

### Expected behavior

A test project named `Acme.BookStore.Web.Tests` should be created.

### Actual behavior

No project named `Acme.BookStore.Web.Tests` was created.

### Known Workarounds

Clone `abpframework/abp` (https://github.com/abpframework/abp).

Go to folder `abp/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.Web.Tests/`, then copy it to your project.

Rename everything that needs to be renamed.

### Version

7.3.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
`.Web.Tests` is designed for `web` instead of `web.host`. This is why it was removed on tiered projects.

**Comment by jmflaga** [comment]
Hi @maliming , there is a `.Web` project in the `src` folder

![image](https://github.com/abpframework/abp/assets/110797508/f64ea5f0-5d03-451c-845f-5ead5e6e97d2)

**Comment by maliming** [comment]
The `Web` is `Web.Host` actually.
https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web.Host
