### ISSUE TITLE
Deprecate SmtpEmailSender in favour of MailKit

### ISSUE THREAD

**Issue by TechnoPorg** [abpframework/abp#17573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

According to Microsoft's documentation for the `System.Net.Mail.SMTPClient` class, its use is not recommended due to it being obsolete on some platforms, and now poorly supported, and the use of the `MailKit` package is recommended instead ([source](https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-7.0#remarks)).
ABP can use both as emailing service providers, but the default implementation uses the the former, whereas MailKit has to be explicitly installed by the developer.
Given that `SmtpClient` is now recommended against by Microsoft, it seems wise to move away from its use going forward.

### Describe the solution you'd like

I propose making `IMailKitSmtpEmailSender` the default email sending service in the ABP framework. This would mean having the `Volo.Abp.MailKit` package installed with the startup template, registering `IMailKitSmtpEmailSender` rather than `ISmtpEmailSender` as the default service, and eventually removing `ISmtpEmailSender` altogether.

**Comment by maliming** [comment]
> We don't recommend that you use the SmtpClient class for new development because SmtpClient doesn't support many modern protocols. Use [MailKit](https://github.com/jstedfast/MailKit) or other libraries instead. For more information, see [SmtpClient shouldn't be used](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md) on GitHub.

Thanks @TechnoPorg 

I will change it in 8.0

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/17776/commits/f5f8b714957238ac152fd9525b7701e910358ab7
