### ISSUE TITLE
CMS Kit: Enhancement ideas for some features

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#17587]
While working on https://github.com/abpframework/abp/issues/17555, I have taken notes on some enhancement ideas for some features in the CMS Kit Module and wanted to create an issue, so we can consider making the related improvements. You can see the following sections for enhancement ideas by each feature:

<details>
<summary><h2>Blogging Feature</h2></summary>

> https://docs.abp.io/en/abp/latest/Modules/Cms-Kit/Blogging

* We have a hard-coded blog prefix, which is *blogs*. So, whenever we create a blog, the URL becomes something like */blogs/{{blog-name}}*, I think this is a restriction, we can allow users to set another prefix or they might want to have just single blog and in that case the *blogs* prefix is completely make no sense.

https://github.com/abpframework/abp/blob/bda231b319b62582dee4f8389494cd4442ac474f/modules/cms-kit/src/Volo.CmsKit.Public.Web/CmsKitPublicWebModule.cs#L94-L95

> We can define a const for blog prefixes as we did in the Blogging Module:

* The blog homepage has a select box that allows us to filter blog posts by authors. This can be optional, so we can add a checkbox on features modal to make it enable/disable on runtime. Also, "searching by tag" feature would be good on homepage (if it's enabled) because otherwise the only place that we can see posts by tags is in the footer of the blog post.

![image](https://github.com/abpframework/abp/assets/43685404/8c0b637f-2909-45e4-9901-def7c5bdcd53)

* Also, we should completely revise the blog post page because it has some virtual problems on the basic-theme (especially if we enable tagging & comment features). 

</details>

---

<details>
<summary><h2>Page Feature</h2></summary>

> https://docs.abp.io/en/abp/latest/Modules/Cms-Kit/Pages

* We can consider allowing a `/` character in the slug while creating a page. A page URL might be like *"products/product-1" but in the current design it replaces the `/` character with an empty string and it's not possible to use such a URL.
</details>

**Comment by gterdem** [comment]
I want to add my feedback for the CmsKit aswell:
As in a common scenario, **rating** and **commenting** system should have an option to be **read-only**:

![image](https://github.com/volosoft/volo/assets/25867/71f6982b-9561-435c-97d8-506417bafcf8)

**Comment by enisn** [comment]
We can add a `ReadOnly` parameter to ViewComponents 👍
