### ISSUE TITLE
Background Jobs how to work

### ISSUE THREAD

**Issue by xgd224743** [abpframework/abp#1758]
HI!

I read this documents  https://docs.abp.io/en/abp/latest/Background-Jobs,

job data is store to databse ,
but I don't know how to run it.

**Comment by xgd224743** [comment]
await _backgroundJobManager.EnqueueAsync(new RegisterEmailSendingArgs
            {
                EmailAddress = input.EmailAddress,
                Subject = await base.SettingProvider.GetOrNullAsync(AccountSettingNames.RegisterAccountEmailSubject),
                Body = "https://localhost:44343/accounts/confirm/" + confirmToken
            `});`

**Comment by xgd224743** [comment]
Where to perform background job

**Comment by xgd224743** [comment]
create new project 
-------------------------
[DependsOn(
        typeof(AbpAutofacModule),
        typeof(UAMEntityFrameworkCoreDbMigrationsModule),
        typeof(UAMApplicationContractsModule),
        typeof(UAMApplicationModule),
        typeof(Volo.Abp.Emailing.AbpEmailingModule),
          typeof(AbpBackgroundJobsModule)
        )]
    public class UAMDbMigratorModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<BackgroundJobOptions>(options => options.IsJobExecutionEnabled = true);
        }
    }
---------------------
 static void Main(string[] args)
        {
            ConfigureLogging();

            using (var application = AbpApplicationFactory.Create<UAMDbMigratorModule>(options =>
            {
                options.UseAutofac();
                options.Services.AddLogging(c => c.AddSerilog());
            }))
            {
                application.Initialize();
 
                Console.WriteLine("Started: " + typeof(Program).Namespace);
                Console.WriteLine("Press ENTER to stop the application..!");
                Console.ReadLine();
                application.Shutdown();
            }
        }
----------------------------
now ,background jobs is working

**Comment by johnnba** [comment]
actually, you can refference the demo project Volo.Abp.BackgroundJobs.DemoApp.RabbitMq.
there has been lots of  examples with backgroundjob and module that can be helpful to startup yours customize project
