### ISSUE TITLE
Static C# Api Client Support Nested Types

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#17590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

a dto
``` csharp
public class OutsideDto
{
    public string Name { get; set; }
    public InsideDto Inside { get; set; }
    class InsideDto
    {
        public int Age { get; set; }
    }
}
```
When I run:

``` bash
abp generate-proxy -t csharp -m module-name
```

generate result:
``` csharp
// OutsideDto.cs
public class OutsideDto
{
    public string Name { get; set; }
    public OutsideDto+InsideDto Inside { get; set; }
}
```
``` csharp
// OutsideDto+InsideDto.cs
class InsideDto
{
    public int Age { get; set; }
}
```
When I Build, get error.because class name cannot use +.

### Version

7.3.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
We can't support all cases. Please use standard code as much as possible.
