### ISSUE TITLE
Upgrade to OpenIddict 5.x.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#17605]
https://github.com/openiddict/openiddict-core/issues/1690#issuecomment-1714331135

**OpenIddict 5.0 RTM is expected to ship mid-December.** 

https://github.com/openiddict/openiddict-core/releases/tag/5.0.0-preview1

**Comment by maliming** [comment]
https://github.com/openiddict/openiddict-core/releases/tag/5.0.0-preview1

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/18347

**Comment by kevinchalet** [comment]
FYI, OpenIddict 5.0 is now available: https://kevinchalet.com/2023/12/18/openiddict-5-0-general-availability/ 🎄

**Comment by maliming** [comment]
Thanks @kevinchalet 👍
