### ISSUE TITLE
Changing AppName does not seem to change name in UI

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#17601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

How can we change the text "ProjectName" in the menu bar of a newly created ABP project? Logo we know how to change. It does not appear to use AppName or anything else I've found in the code as a change like this has no effect on rendered UI. 

```
public class TodoManagerBrandingProvider : DefaultBrandingProvider
{
    public override string AppName => "My new name here";
}
```

![image](https://github.com/abpframework/abp/assets/2812422/b46e36eb-f61e-403c-a7e7-8efde7f3cc5d)

As this does not seem to work and also that I have not been able to find any documentation on how to make it work, I file this as a bug. 

### Version

7.3.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by improwise** [comment]
![image](https://github.com/abpframework/abp/assets/2812422/b5dc0494-ed24-4d14-b5ec-ef415924dba7)

**Comment by EngincanV** [comment]
Hi, this is an image rather than the application name. If you want to override the branding logo you can override the `LogoUrl` property of your branding class. Setting the application name is only applicable to the [basic theme](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Basic-Theme) for now.

**Comment by improwise** [comment]
> Hi, this is an image rather than the application name. If you want to override the branding logo you can override the `LogoUrl` property of your branding class. Setting the application name is only applicable to the [basic theme](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Basic-Theme) for now.

Ah, that explains why we were unable to find it. Is this something that is intended to be fixed in the future as it is a bit confusing, especially since it was possible to configure this in the past if I remember correctly? Thanks.

**Comment by EngincanV** [comment]
> Ah, that explains why we were unable to find it. Is this something that is intended to be fixed in the future as it is a bit confusing, especially since it was possible to configure this in the past if I remember correctly? Thanks.

Yes, you are right, this seems misleading and we should update related parts in the documentation. I have taken note of that and will update the related sections asap. Thanks 👍

**Comment by improwise** [comment]
Great.

**Comment by mirfanazam** [comment]
Please make sure you are writing code in the right place.

![image](https://github.com/abpframework/abp/assets/16230194/5e6f9dc7-e474-4730-9788-2cf4cfc47156)

**Comment by Md-Faisal-Mahmud** [comment]
I override LogURL it's not effecting in url favicon icon. what is the solution
