### ISSUE TITLE
Consider bumping OpenIddict to 4.8.0

### ISSUE THREAD

**Issue by kevinchalet** [abpframework/abp#17613]
Hey there,

Hope everyone is doing well at ABP 👋🏻 

FYI, OpenIddict 4.8.0 just shipped and is a (very 😄) recommended update, given that it includes a compatibility fix needed to work with the IdentityModel 7.0 packages released yesterday: https://github.com/openiddict/openiddict-core/releases/tag/4.8.0

Note: OpenIddict 4.8.0 deliberately still targets IdentityModel 6.25.1 (the same version as OpenIddict 4.7.0: explicitly referencing IM 7.0 was not necessary to fix the compat' issue).

Have a nice day 😃

**Comment by sturlath** [comment]
https://github.com/abpframework/abp/issues/17605

**Comment by kevinchalet** [comment]
@sturlath https://github.com/abpframework/abp/issues/17605 tracks migrating to OpenIddict 5.0, which will be a major version (with breaking changes) coming later this year. 4.8 on the other hand, is already available and doesn't have any breaking change.
