### ISSUE TITLE
Where to configure password strength

### ISSUE THREAD

**Issue by xgd224743** [abpframework/abp#1761]

**Comment by maliming** [comment]
Configure it with settings.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpIdentitySettingDefinitionProvider.cs#L8

**Comment by xgd224743** [comment]
thanks
