### ISSUE TITLE
External auth

### ISSUE THREAD

**Issue by elie-chaaban** [abpframework/abp#17643]
I am using abp module with no UI.

Let's say I have scaffolded a sql table with username and password.

How can I create authentication based on this table? I can have a JWT token but I am not able to know where should I create the custom auth attribute, can anyone help?

**Comment by elie-chaaban** [comment]
Or How to create a web api key that I can check on the app service if available then he's logged in

**Comment by maliming** [comment]
hi

The above has nothing to do with the abp framework.

abp uses standard asp net core' authentication.

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-7.0
