### ISSUE TITLE
Microservice solution is not working with ASP.NET Core 3.0 because of Ocelot dependency

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1764]
Because of this: https://github.com/ThreeMammals/Ocelot/issues/1001
I didn't want to implement the solution mentioned in https://github.com/ThreeMammals/Ocelot/issues/1001#issuecomment-525963734

I leave this to v1.0 milestone to see if this is implemented by the Ocelot team.

**Comment by geffzhang** [comment]
ocelot update .net core 3.0 RTM https://github.com/ThreeMammals/Ocelot/pull/1025

**Comment by hikalkan** [comment]
You are great! :)

**Comment by geffzhang** [comment]
https://github.com/ThreeMammals/Ocelot/releases/tag/13.8.0  Officially released for .NET Core 3

**Comment by pranavpatil19** [comment]
waiting stable release with multi tenancy
