### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1765]
Is there a caching mechanism that works like memorycache in the other abpframework.

Thank you!

**Comment by ismcagdas** [comment]
@wocar you can directly use https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#idistributedcache-interface. By default it acts like an in-memory cache https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#distributed-memory-cache.

But, it can be easily converted to distributed cache if you want.

**Comment by wocar** [comment]
Thank you. Already using net core memory cache.
