### ISSUE TITLE
External login button cannot be displayed on the login page with LeptonX theme

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#17657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The account layout of LeptonX Theme added the "override-hidden" CSS class to the "container-fluid" container, it caused the external login button cannot be displayed on the login page.

### Reproduction Steps

1. Enable external login
2. Add more than 4 type external login method

### Expected behavior

the over flow external button should be displayed or the page disappear the scroll bar, let a user scrolling the page

### Actual behavior

the login area fixed, cannot be scrolled

### Regression?

before the version 2.3 of LeptonX, no issue with this behavior

### Known Workarounds

remove the hard code CSS class "override-hidden", let the scroll bar disappear when more content rendered on the login page

### Version

7.3.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

I have tried override the account layout via the theme customization, created a same razor page under the path "\Themes\LeptonX\Layouts\Account\" , but the bundling files cannot be translated, all css and script file not loaded on the page

**Comment by enisn** [comment]
I couldn't reproduce the same issue

All of them are listed below the login form:
<img width="323" alt="image" src="https://github.com/abpframework/abp/assets/23705418/ef46ac9e-d3be-44b9-aa40-10adb6bf9737">

**Comment by enisn** [comment]
It works on **LeptonX** Commercial version too

<img width="328" alt="image" src="https://github.com/abpframework/abp/assets/23705418/192e3b71-7316-44ae-aaac-92f5b48778c6">


Here is my changes:

csroj
```xml
  <ItemGroup>
    <PackageReference Include="AspNet.Security.OAuth.Discord" Version="7.0.2" />
    <PackageReference Include="AspNet.Security.OAuth.Amazon" Version="7.0.2" />
    <PackageReference Include="AspNet.Security.OAuth.Bitbucket" Version="7.0.2" />
    <PackageReference Include="AspNet.Security.OAuth.Apple" Version="7.0.2" />
    <PackageReference Include="AspNet.Security.OAuth.Reddit" Version="7.0.2" />
  </ItemGroup>
```

Module class:
```cs
context.Services.AddAuthentication()
           .AddDiscord(options =>
           {
               options.ClientId = "SOME_WRONG_ID";
               options.ClientSecret = "SOME_SECRET";
           })
           .AddAmazon(options =>
           {
               options.ClientId = "SOME_WRONG_ID";
               options.ClientSecret = "SOME_SECRET";
           })
           .AddBitbucket(options =>
           {
               options.ClientId = "SOME_WRONG_ID";
               options.ClientSecret = "SOME_SECRET";
           })
           .AddApple(options =>
           {
               options.ClientId = "SOME_WRONG_ID";
               options.ClientSecret = "SOME_SECRET";
           })
           .AddReddit(options =>
           {
               options.ClientId = "SOME_WRONG_ID";
               options.ClientSecret = "SOME_SECRET";
           });
```

And all of them are visible on the login screen

**Comment by sephit** [comment]
Depending on the window size, try in different resolutions, that issue will appear and also try in other browsers. In my case, it's hidden too. I reported in the commercial support forum but it was not fixed.

This is a workaround fix that I'm using.

```

.lpx-login-area .lpx-login-bg {
  height: fit-content;
}

.abp-account-layout > .container-fluid {
  overflow-y: auto!important;
}
```

**Comment by gizemmutukurt** [comment]
When I checked I was able to repeat the error this way. Thank you, we will take action to fix it.

![image](https://github.com/abpframework/abp/assets/99716457/daf873c9-6054-485a-aa0a-b52800f46c36)

**Comment by enisn** [comment]
It can be reproduced on iPhone SE screen in the inspect tools
