### ISSUE TITLE
ABP CLI error in Ubuntu 18.04.3 LTS : The type initializer for 'System.Net.Http.CurlHandler' threw an exception 

### ISSUE THREAD

**Issue by Muhammad-Fakhr-Elden** [abpframework/abp#1766]
abp
[15:06:47 INF] ABP CLI (https://abp.io)
[15:06:47 INF] Version 0.19.0 (Stable channel)
[15:06:47 WRN] Unable to retrieve the latest version
[15:06:47 WRN] The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
[15:06:47 INF] 
Usage:

    abp <command> <target> [options]

Command List:

    > help 
    > new: Generates a new solution based on the ABP startup templates.
    > update: Automatically updates all ABP related NuGet packages and NPM packages in a solution or project to the latest versions
    > add-package: Adds a new ABP package to a project by adding related nuget package as a dependency to the project and adding [DependsOn(...)] attribute to the module class in the project.
    > add-module: Adds a multi-package module to a solution by finding all packages of the module, finding related projects in the solution and adding each package to the corresponding project in the solution.
    > login 
    > logout 

To get a detailed help for a command:

    abp help <command>

See the documentation for more info: https://docs.abp.io/en/abp/latest/CLI

**Comment by maliming** [comment]
Try install `openssl` on your Ubuntu.

eg:
```
apt-get install libcurl4-openssl-dev
```

**Comment by Muhammad-Fakhr-Elden** [comment]
Thanks a lot for your reply. The issue was because 2.2 and 2.1 dotnet SDKs were installed. when remove them and install 2.2, the issue was resolved.
