### ISSUE TITLE
`abp new` command reference wrong database package

### ISSUE THREAD

**Issue by minhtaile2712** [abpframework/abp#17667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using `abp new` command to create new module.
`abp new Acme.MyModule -t module --no-ui -dbms PostgreSQL -csf -sib --no-random-port`
and
`abp new Acme.MyModule -t module --no-ui -csf -sib --no-random-port`
show the same package references, only connection string is changed.

### Reproduction Steps

Using powershell.

Create a new folder and add git for comparison
```
mkdir test-folder
cd test-folder
git init
```
Run the first case, commit it to capture the state
```
abp new Acme.MyModule -t module --no-ui -dbms PostgreSQL -csf -sib --no-random-port
git add .
git commit -m 'Initial commit'
```
Delete created files, run the second case and compare using `git diff` (or `git status`) to see the difference
```
rm -r -fo .\Acme.MyModule\
abp new Acme.MyModule -t module --no-ui -csf -sib --no-random-port
git diff
```
Here is the result. Only the connection strings in `appsettings.json` is changed

### Expected behavior

In the first case, whole solution should have at least one module referencing to `Volo.Abp.EntityFrameworkCore.PostgreSql`

### Actual behavior

In both case, only `Volo.Abp.EntityFrameworkCore.SqlServer` is referenced

### Version

7.3.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by yekalkan** [comment]
Hi @minhtaile2712

As i see, DBMS selection should not be available for module template. Because it is not supported by CLI. (I know this is not described in the docs.)

**Comment by minhtaile2712** [comment]
Hi @yekalkan 
But we still needed it in "host projects" for development, right?
