### ISSUE TITLE
Usage of LazyServiceProvider.

### ISSUE THREAD

**Issue by agustinsilvano** [abpframework/abp#17688]
Hi, 

I've been checking the source code of some classes (i.e `ApplicationService` and `DomainService`) and I'd like to understand the "why" (and "when") of the usage of the (Cached) Service Provider on these classes. 

![image](https://github.com/abpframework/abp/assets/29497274/4b19c00f-1037-4bfe-aaef-7c076a15b0fe)

Is the main reason to avoid having a bunch of dependencies while inheriting from an `ApplicationService`? I mean, is this technique used to have a parameter-less constructor?

Thanks! 

A.

**Comment by maliming** [comment]
hi

Injecting too many services can impact performance, it can delay injecting services until you need to use them.

**Comment by agustinsilvano** [comment]
@maliming thanks!

Do you have a threshold for a "healthy" amount of deps to inject?

**Comment by maliming** [comment]
The lock will be used when the DI container resolving service. That's the reason.

**Comment by JontyMin** [comment]
> hi
> 
> Injecting too many services can impact performance, it can delay injecting services until you need to use them.

Lazily resolving services to fix circular dependencies
