### ISSUE TITLE
abp Commercial: Add security key authentication

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#17698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Login with FIDO2 (YubiKey,...) security key with the ability to add multiple security keys for one user.
Just like Google, Microsoft and others have.

### Describe the solution you'd like

-

### Additional context

-

**Comment by maliming** [comment]
hi

https://github.com/openiddict/openiddict-core/issues/1885#issuecomment-1727379487

**Comment by leonkosak** [comment]
Thank you!.
