### ISSUE TITLE
Blazor - The single button does not utilize a dropdown.

### ISSUE THREAD

**Issue by zhaofenglee** [abpframework/abp#17703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If there is only one button in EntityActions, it should be displayed as a standalone button.

https://support.abp.io/QA/Questions/1431/Blazor---Action-Button---DataGridEntityActionsColumn-with-single-EntityAction

### Describe the solution you'd like

You don't need to set the `EntityActions` property; instead, you can determine whether to use a dropdown based on the number of actions available. If there is only one action, it will be displayed as a standalone button without a dropdown.

### Additional context

![image](https://github.com/abpframework/abp/assets/111716814/a84a4fb8-5805-4d00-9e1e-1f687d386574)

![image](https://github.com/abpframework/abp/assets/111716814/168b4a3c-9994-4fb4-a826-b77b75ca3044)

**Comment by zhaofenglee** [comment]
Similarly, when there is only one button visible to the user, you should not use a dropdown.

![image](https://github.com/abpframework/abp/assets/111716814/8b78b758-f0c7-4d8e-92a3-af697e098d9b)

![image](https://github.com/abpframework/abp/assets/111716814/1efcdba4-25ac-42bb-bdda-70f9528287e5)

**Comment by rqx110** [comment]
https://github.com/abpframework/abp/pull/16131

**Comment by zhaofenglee** [comment]
> #16131

This pull request (PR) only addresses the issue with AbpExtensibleDataGrid. If you are using the DataGrid control, the problem may still exist.
