### ISSUE TITLE
Create page error.

### ISSUE THREAD

**Issue by zlcoolzl** [abpframework/abp#17707]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

`@page
@using CarePro.Localization
@using CarePro.Web.Pages.Devices
@using Microsoft.Extensions.Localization
@model IndexModel
@inject IStringLocalizer<CareProResource> L
@section scripts
{
    <abp-script src="/Pages/Devices/Index.js"/>
}
<abp-card>
    <abp-card-header>
        <h2>@L["DeviceTypesTitle"]</h2>
    </abp-card-header>
    <abp-card-body>
        <abp-table striped-rows="true" id="DeviceTypesTable"></abp-table>
    </abp-card-body>
</abp-card>
`

`$(function (){
    var l = abp.localization.getResource('CarePro');
    var dataTable = $('#DeviceTypesTable').DataTable(
        abp.libs.datatables.normalizeConfiguration({
            serverSide: true,
            paging: true,
            order: [[1, "asc"]],
            searching: false,
            scrollX: true,
            ajax: abp.libs.datatables.createAjax(carePro.devices.deviceType.getlist),
            columnDefs: [
                {
                    title: "Name",
                    data: "deviceTypeName",
                },
                {
                   title: "Time", data: "creationTime",
                   render: function (data) {
                       return "time";
                       //return luxon
                       //    .DateTime
                       //    .fromISO(data, {
                       //        locale: abp.localization.currentCulture.name
                       //    }).toLocaleString(luxon.DateTime.DATETIME_SHORT);
                   }
                }
            ]
        })
    );
});
`

报错！
![image](https://github.com/abpframework/abp/assets/7567074/3b63f611-29f4-46b4-845e-a4b236c71b06)
请问如何解决

**Comment by maliming** [comment]
>Reproduction Steps
>Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).

**Comment by zlcoolzl** [comment]
> Reproduction Steps
> Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).

Index.cshtml
![image](https://github.com/abpframework/abp/assets/7567074/343cb415-270e-4a81-83ce-cf29ae08fe97)
Index.cshtml.cs
![image](https://github.com/abpframework/abp/assets/7567074/7a8ad799-f4c7-44b2-991f-3e7bb017706b)
Index.js
![image](https://github.com/abpframework/abp/assets/7567074/ee62301c-ce1c-44f9-9a6a-03a2080648d2)

**Comment by zlcoolzl** [comment]
> > Reproduction Steps
> > Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
> 
> Index.cshtml ![image](https://user-images.githubusercontent.com/7567074/269858250-343cb415-270e-4a81-83ce-cf29ae08fe97.png) Index.cshtml.cs ![image](https://user-images.githubusercontent.com/7567074/269858319-7a8ad799-f4c7-44b2-991f-3e7bb017706b.png) Index.js ![image](https://user-images.githubusercontent.com/7567074/269858363-ee62301c-ce1c-44f9-9a6a-03a2080648d2.png)

Abp.Io Version 7.3

**Comment by zlcoolzl** [comment]
It's my writing error。
Error：abp.libs.datatables.createAjax(carePro.devices.deviceType.getlist)
Correct：abp.libs.datatables.createAjax(carePro.devices.deviceType.getList)
Thank you all
