### ISSUE TITLE
LeptonXLite home icon in the breadcrumb menu doesn't work

### ISSUE THREAD

**Issue by JadynWong** [abpframework/abp#17704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The home icon in the breadcrumb menu doesn't work.

![image](https://github.com/abpframework/abp/assets/13699353/b4c9f04c-2fb5-4541-9626-e0d60628e8da)

![image](https://github.com/abpframework/abp/assets/13699353/52ce9dd5-13ca-4064-82ac-e0594bbe64b5)

### Known Workarounds

Possibly all icons should be within the `a` tag

### Version

7.3.3

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
The problem will fixed in the next patch version
