### ISSUE TITLE
HttpApi project automatically registers controllers

### ISSUE THREAD

**Issue by Brandejs** [abpframework/abp#17700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi I just noticed that if I add a reference in .csproj ```<PackageReference Include="Volo.Abp.TenantManagement.HttpApi" Version="7.3.2" />```, or whatever, I get the tenant management controllers displayed in the swagger. Although I have not added ``[DependsOn(typeof(AbpTenantManagementHttpApiModule))]``. Is it bug? Or are controllers automatically searched and registered differently? Is there any way to prevent this?

### Reproduction Steps

```abp new Acme.BookStore -u angular -dbms SQLite -csf ```

open ```Acme.BookStore/aspnet-core/src/Acme.BookStore.HttpApi/BookStoreHttpApiModule.cs``` and remove HttpApiModuless from **DependsOn** or remove ```typeof(BookStoreHttpApiModule)``` in Acme.BookStore.HttpApi.Host

Open the app and they are still visible in the swagger and can be called.

### Expected behavior

If the module does not contain ```[DependsOn(typeof(AbpTenantManagementHttpApiModule)]``` The controller should not be registered.  

### Actual behavior

Controllers are registered even if there is no ```[DependsOn(typeof(AbpTenantManagementHttpApiModule)]```. Only by adding a reference in csproj.

### Regression?

Tested with Abp. 7.1.1 and 7.3.2

### Version

7.3.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

### Other information

I thought that the registration of controllers from the reference has to go through "Application Parts" and that it is part of the abp module registration.

**Comment by maliming** [comment]
This may be the behavior of ASPNET Core instead of abp.

**Comment by Brandejs** [comment]
Yes it looks like ASPNET Core searches the bin folder and automatically registers the DLL into ApplicationParts. 

I noticed that the startup template does not include.

```
public override void PreConfigureServices(ServiceConfigurationContext context)
    {
        PreConfigure<IMvcBuilder>(mvcBuilder =>
        {
            mvcBuilder.AddApplicationPartIfNotExists(typeof(BookStoreHttpApiModule).Assembly);
        });
    }
```

And yet the controllers from BookStoreHttpApiModule are registered.

But it seems pretty dangerous to me. This way they get controllers into the application just by the fact that there is a reference.

**Comment by maliming** [comment]
So you can remove the `part` from `ApplicationParts`, right?

**Comment by Brandejs** [comment]
It looks like the current workaround is to add the following to Program.cs.


```var builder = WebApplication.CreateBuilder(args);
            builder.Host.AddAppSettingsSecretsJson()
                .UseAutofac()
                .UseSerilog();
            
            var mvcBuilder = builder.Services.AddControllers();
            mvcBuilder.ConfigureApplicationPartManager(apm =>
            {
                apm.ApplicationParts.Clear();
            });

            await builder.AddApplicationAsync<BookStoreHttpApiHostModule>();
            var app = builder.Build();
```

Subsequently, only things from DependsOn are registered. I think this should be noted in the documentation.


EDIT: 

But this will also remove Parts that should be registered... For UI and OpenIddict. So it is probably not recommended way.. .

**Comment by Brandejs** [comment]
The best solution I have come up with so far is this. 
```
var assembliesToRemove = AppDomain.CurrentDomain.GetAssemblies()
    .Where(assembly =>
        assembly.GetTypes().Any(type =>
            typeof(IAbpModule).IsAssignableFrom(type)
        )
    )
    .ToList();
mvcBuilder.ConfigureApplicationPartManager(apm =>
{
    foreach (var assemblyToRemove in assembliesToRemove)
    {
        var assemblyPart = apm.ApplicationParts.FirstOrDefault(part => part is AssemblyPart assemblyPart && assemblyPart.Assembly == assemblyToRemove);
        if (assemblyPart != null)
        {
            apm.ApplicationParts.Remove(assemblyPart);
        }
    }
});
```

When I compare the registered application parts I come to this difference (in the startup template) Maybe add mvcBuilder.AddApplicationPartIfNotExists for these modules related to MVC?


| Without Remove Parts | With Remove Parts |
| --- | --- |
| Acme.BookStore.HttpApi |  Acme.BookStore.HttpApi |
| Acme.BookStore.HttpApi.Host |  Acme.BookStore.HttpApi.Host |
| Microsoft.AspNetCore.Mvc.Razor |  Microsoft.AspNetCore.Mvc.Razor |
| Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation |  Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation |
| Microsoft.AspNetCore.Mvc.TagHelpers |  Microsoft.AspNetCore.Mvc.TagHelpers |
| Microsoft.AspNetCore.Mvc.Versioning |  Microsoft.AspNetCore.Mvc.Versioning |
| Swashbuckle.AspNetCore.SwaggerGen |  Swashbuckle.AspNetCore.SwaggerGen |
| Volo.Abp.Account.HttpApi |  Volo.Abp.Account.HttpApi |
| Volo.Abp.Account.Web |  Volo.Abp.Account.Web |
| Volo.Abp.Account.Web.OpenIddict |  Volo.Abp.Account.Web.OpenIddict |
| Volo.Abp.AspNetCore.Mvc |   |
| Volo.Abp.AspNetCore.Mvc.UI |  Volo.Abp.AspNetCore.Mvc.UI |
| Volo.Abp.AspNetCore.Mvc.UI.Bootstrap |   |
| Volo.Abp.AspNetCore.Mvc.UI.Bundling |   |
| Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy |  Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy |
| Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite |  Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite |
| Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared |  Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared |
| Volo.Abp.AspNetCore.Mvc.UI.Widgets |  Volo.Abp.AspNetCore.Mvc.UI.Widgets |
| Volo.Abp.FeatureManagement.HttpApi |  Volo.Abp.FeatureManagement.HttpApi |
| Volo.Abp.Identity.HttpApi |  Volo.Abp.Identity.HttpApi |
| Volo.Abp.OpenIddict.AspNetCore |  Volo.Abp.OpenIddict.AspNetCore |
| Volo.Abp.PermissionManagement.HttpApi |  Volo.Abp.PermissionManagement.HttpApi |
| Volo.Abp.SettingManagement.HttpApi |  Volo.Abp.SettingManagement.HttpApi |
| Volo.Abp.Swashbuckle |   |
| Volo.Abp.TenantManagement.HttpApi |  Volo.Abp.TenantManagement.HttpApi |

**Comment by maliming** [comment]
hi

Since this is ASP NET Core behavior and only seems to affect you, this is not a problem of abp. We will do nothing.

**Comment by Brandejs** [comment]
Okay. I appreciate your time. And I'm closing the issue
