### ISSUE TITLE
<p-table> in angular template

### ISSUE THREAD

**Issue by alaawahbah** [abpframework/abp#1770]
Hi
I follow the Abp FrameWork angular tutorial step by step but the pager not working on data is garater than 10 and i try to find any document or google search but there is no document.
please help me to make paging work.
thanks in advance....

**Comment by mehmet-erim** [comment]
Hi

Backend sends 10 books. You should add the MaxResultCount filter to your request.

Open `books.service.ts` and replace the `get` method as shown below:

```
export class BooksService {
  // ...
  get(): Observable<Books.Response> {
    return this.restService.request<void, Books.Response>({
      method: 'GET',
      url: '/api/app/book?MaxResultCount=999',
    });
  }
```

and then check the table. Pagination will work.

Check the primeNG documentation
Client-side paging: https://www.primefaces.org/primeng/#/table/page
Server-side paging: https://www.primefaces.org/primeng/#/table/lazy
