### ISSUE TITLE
In MVC the language "German" is displayed incorrectly (with DE-DE instead of DE)

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#17719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the toolbar of MVC (e.g. under Profile) the language for German is displayed DE-DE. In Blazor it is displayed correctly: DE

Why is this done differently? Can you fix this so that only DE is used everywhere? Or how can I correct this myself?

### Reproduction Steps

Choose German as language and switch between Blazor and MVC and see the difference.

### Expected behavior

Everywhere there is the abbreviation DE for German

### Actual behavior

DE-DE instead of DE (in MVC)

### Regression?

This has been the case since I started working with ABP (version 6 and higher).

### Version

7.3.3

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

Using LeptonX Theme

**Comment by ageiter** [comment]
Sorry, I forgot the screenshots:

![image](https://github.com/abpframework/abp/assets/17644153/5dce3155-21ab-4098-b17a-1416407816ee)

![image](https://github.com/abpframework/abp/assets/17644153/491a35ea-395f-45c8-9dc2-d549de5bbb25)

**Comment by realLiangshiwei** [comment]
Hi,

We will fix this in the next patch version.

**Comment by ageiter** [comment]
Thanks for the adjustment. Unfortunately this was not adjusted everywhere... the header still says DE-DE.

![image](https://github.com/abpframework/abp/assets/17644153/b6fb56af-56d8-4260-8d02-edd27d5e61a4)

**Comment by ageiter** [comment]
Hi @realLiangshiwei ,

I have also been using the public website since today and have seen that it also says DE-DE. Can you please adapt this to DE as well?

![image](https://github.com/abpframework/abp/assets/17644153/fd7a6931-e3f3-4f55-9fbe-d7be841950ba)

However, this is only the case if the application is initially started in German. If I then select DE in the menu, it appears correctly.

**Comment by ageiter** [comment]
@realLiangshiwei, do you see my comment? I just didn't want to create a new issue for the same thing...

**Comment by realLiangshiwei** [comment]
I could not reproduce the problem.

<img width="1379" alt="image" src="https://github.com/abpframework/abp/assets/16813853/4a45f041-3360-40b1-a9ba-af16c200373c">

**Comment by ageiter** [comment]
Select "Deutsch / DE" and then restart the application.

**Comment by realLiangshiwei** [comment]
I tried, but still can't reproduce

**Comment by ageiter** [comment]
ok, thanks for checking. I'll let you know if I know how to reproduce it.

**Comment by ageiter** [comment]
Hi @realLiangshiwei,

I know it will be annoying, but I still have the problem with a new application (ABP 8.2.2). On the public website (Projectname.Web.Public) the language still appears as DE-DE. 

![image](https://github.com/user-attachments/assets/74ab79af-b30b-4e11-a5d3-ab3d30d80b25)


![image](https://github.com/user-attachments/assets/20f21dfb-167d-4e3f-ba43-6d5696ade87c)


Unfortunately, I don't know how I can make sure that you can reproduce it. Can you tell me where I could solve this myself? Where are the names taken from? Directly from the name of the resource file? I have not found it in the localized strings.

Thanks,
Adrian

**Comment by ageiter** [comment]
Hi @realLiangshiwei,

I now know how to reproduce the problem.

1. select German (DE-DE) as the default language in your application. 
2. start the application and open it in the incognito mode of the browser

It is only displayed like this when the user accesses the page for the first time. As soon as the user has changed / set the language once, it will appear correctly afterwards.

**Comment by ageiter** [comment]
Hi @realLiangshiwei 

Are you interested in a solution? I have now overwritten the layout and fixed the problem. It would be useful if you could also correct this in your code. I looked at the Blazor layout, it always worked there.

In the GeneralSettingsViewComponent of the MVC project, the file _src\Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX\Themes\LeptonX\Components\Common\GeneralSettings\Default.cshtml_:

```
<div id="language" class="setting-icon" data-lpx-setting-icon="language" data-lpx-setting-id="settings-context-menu">
    <div class="setting">
	<span>@languageModel.CurrentLanguage.TwoLetterISOLanguageName.ToUpperInvariant()</span>
    </div>
</div>
```

instead of

```
<div id="language" class="setting-icon" data-lpx-setting-icon="language" data-lpx-setting-id="settings-context-menu">
    <div class="setting">
        <span></span>
    </div>
</div>
```
