### ISSUE TITLE
abp 4.3.3 update 4.4.0,guid collation: "ascii_general_ci" foreign key association failed

### ISSUE THREAD

**Issue by zhangzw218** [abpframework/abp#17728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

abp 4.3.3 add-migration
Id = table.Column<Guid>(type: "char(36)", nullable: false),
Name = table.Column<string>(type: "varchar(40) CHARACTER SET utf8mb4", maxLength: 96, nullable: true),

abp 4.4.0 add-migration
Id = table.Column<Guid>(type: "char(36)", nullable: false, collation: "ascii_general_ci"),
Name = table.Column<string>(type: "varchar(40)", maxLength: 40, nullable: true).Annotation("MySql:CharSet", "utf8mb4")

This causes two problems: one serious problem is that when foreign keys are associated, the old table Id<Guid> and the new table foreign key RoleId<Guid> cannot be associated:
`
Create table 'migrationdemo/apptempusers' with foreign key constraint failed. There is no index in the referenced table where the referenced columns appear as the first columns.
`
A minor problem: a large number of string encoding remigrations:
```
            migrationBuilder.AlterColumn<string>(
                name: "Value",
                table: "AbpSettings",
                type: "varchar(2048)",
                maxLength: 2048,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "longtext CHARACTER SET utf8mb4(2048)",
                oldMaxLength: 2048)
                .Annotation("MySql:CharSet", "utf8mb4")
                .OldAnnotation("MySql:CharSet", "utf8mb4");
```

### Reproduction Steps

[github demo](https://github.com/zhangzw218/AbpSignalRDemo/tree/feature/2023092502_zzw_efcore_add_migration)

1.abp new demo -v 4.3.3
2.create entity TestRole
```
public class TestRole{
public Guid Id{get;set;}
public string Name{get;set;}
}
```
3.Add-Migration Initial
4.abp update -v 4.4.0
5.create entity TestUser
```
public class TestUser{
public Guid Id{get;set;}
public string Name{get;set;}
public TestRole TestRole {get;set;}
}
```
6.Add-Migration AddTestUser

After the demo is ready, check the migration scripts of TestRole and TestUser. The Guid statements are very different, and TestUser will fail to associate with TestRole

### Actual behavior

1.About guid, 1. Is there a way to migrate all the old guid to the new guid? 
If I specify:
context -> configurationBuilder.Properties<Guid>().UseCollation("ascii_general_ci");
Migration errors can also occur because those fields already have a foreign key index and cannot be changed

2.Can I specify guid collation to be empty and not set to ensure the same behavior as in 4.3.3?

3.Can I specify a global build statement for string to ensure the same behavior as in 4.3.3?
My main concern is the Guid issue, which is not very important because the migration is not abnormal.

### Version

4.3.3

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by JadynWong** [comment]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1477

**Comment by zhangzw218** [comment]
多谢，我在那边另外提问了，这边问题关闭。
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1790#issue-1914585427
