### ISSUE TITLE
DynamicLayoutComponent cause snapshot error

### ISSUE THREAD

**Issue by cloud0259** [abpframework/abp#17731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

I created a new Module project with the command 
```abp new Acme.IssueManagement -t module``` 
and an error appears when I browse the module page about DynamicLayoutComponent.
![image](https://github.com/abpframework/abp/assets/6765644/b6742a31-b2cc-4924-921f-6abb6b676e40)

### Reproduction Steps

Create project ```abp new Acme.IssueManagement -t module``` 

### Known Workarounds

As a workaround, I replaced the **abp-dynamic-layout** component with **router-outlet** in the module's dev-app project.

### Version

7.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by mahmut-gundogdu** [comment]
I have couldn't produced.  It works on my machine. Could you share your package.json ? Maybe I miss/skip something?

**Comment by cloud0259** [comment]
I solved the problem by changing DynamicLayoutComponent to EmptyLayoutComponent in the routing--module. I don't know if this is the best solution

**Comment by mahmut-gundogdu** [comment]
> DynamicLayoutComponent

What is you theme ? Lepton x lite ? theme basic ?
if it is lepton x, it is know issue. it will fixed next stable release but you can fix.


```js
 constructor(
    private replaceableComponents: ReplaceableComponentsService, // injected the service
  ) {
    this.replaceableComponents.add({
      component: YourNewEmptyLayoutComponent,
      key: eThemeLeptonXComponents.EmptyLayout,
    });
  }
```
the example empty layout.

https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/theme-basic/src/lib/components/empty-layout/empty-layout.component.ts


https://docs.abp.io/en/abp/latest/Themes/LeptonXLite/Angular#how-to-replace-a-component

**Comment by masum-ulu** [comment]
It was comes from [module template](https://github.com/abpframework/abp/blob/rel-7.4/templates/module/angular/projects/my-project-name/src/lib/my-project-name-routing.module.ts#L10) I've switch to `RouterOutletComponent`  in `8.0` you can also use this component for the solve problem. I'm closing this issue
