### ISSUE TITLE
Dto value still get string, when i use ObjectExtensionManager.Instance.AddOrUpdateProperty<int>

### ISSUE THREAD

**Issue by amin168** [abpframework/abp#17747]
```

ObjectExtensionManager.Instance
  .MapEfCoreProperty<IdentityUser, int>("WorkflowId",
      (entityBuilder, propertyBuilder) =>
      {
          propertyBuilder.HasDefaultValue(1);
      })

```

```

ObjectExtensionManager.Instance
    .AddOrUpdateProperty<int>(
        new[]
        {
            typeof(IdentityUserDto),
            typeof(IdentityUserCreateDto),
            typeof(IdentityUserUpdateDto)
        },
        "WorkflowId"
    );

```

![image](https://github.com/abpframework/abp/assets/10808093/c08938d9-49d3-4082-9712-7945b61e14dd)

**Comment by maliming** [comment]
hi

You can check the json data in database.

**Comment by amin168** [comment]
@maliming sorry, for the late answer, please see the pic below
![image](https://github.com/abpframework/abp/assets/10808093/ca340aa4-82f7-41b6-a1cf-e6f4e0f25efc)
 
![image](https://github.com/abpframework/abp/assets/10808093/9460dc15-cc0d-412d-af09-92840913c212)

**Comment by maliming** [comment]
Please share a simple template project on GitHub. Thanks

**Comment by amin168** [comment]
I use abp-cli to create a project, and it's working, I don't why my project is not working, I will check again, thanks !
