### ISSUE TITLE
How can use Kendo DataSourceRequest in Abp?

### ISSUE THREAD

**Issue by masgarifor2** [abpframework/abp#17743]
Hi guys.

I asked my question in StackOverFlow:
[https://stackoverflow.com/questions/77078845/how-can-i-use-kendo-datasourcerequest-in-abp](https://stackoverflow.com/questions/77078845/how-can-i-use-kendo-datasourcerequest-in-abp)

I have an Abp project; I want to read data for show in kendo grid. my code is:

`[HttpPost]
    public async Task<DataSourceResult> ReadAsync([FromBody][DataSourceRequest] DataSourceRequest request)
    {
        var query = await _repository.GetQueryableAsync();
        return await query.ToDataSourceResultAsync(request);
    }`

When I call api by Swagger, the request parameter is empty and can't bind model.

![Untitled](https://github.com/abpframework/abp/assets/30830198/28132956-a8f2-4fc1-b4f3-e6e2ccdadfa1)

If I don't use [FromBody] attribute I have this error:

`Could not load type 'Microsoft.AspNetCore.Mvc.ModelBinding.Internal.ModelBindingHelper' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

please help me.

**Comment by bcanylmz** [comment]
How did you solve this problem?
