### ISSUE TITLE
How to use AbpExtensibleDataGrid？

### ISSUE THREAD

**Issue by He-Wu** [abpframework/abp#17744]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

I need to use the AbpExtensibleDataGrid component to query data. I need to display personalized content such as pictures in columns. This component has a Columns attribute but I don't know how to achieve the effect. Is there any documentation or related information on the AbpExtensibleDataGrid component? I'm confused

**Comment by realLiangshiwei** [comment]
Hi,

We don't have the `AbpExtensibleDataGrid` document yet.

You can refer to its usage in the module:

https://github.com/abpframework/abp/blob/dd1bc966be5bbe32656934dea69d099302ba701d/modules/identity/src/Volo.Abp.Identity.Blazor/Pages/Identity/RoleManagement.razor#L24-L32

https://github.com/abpframework/abp/blob/dd1bc966be5bbe32656934dea69d099302ba701d/modules/identity/src/Volo.Abp.Identity.Blazor/Pages/Identity/RoleManagement.razor.cs#L83-L106

**Comment by He-Wu** [comment]
Thank you very much, your answer is very helpful to me

**Comment by He-Wu** [comment]
> 你好，
> 
> 我们还没有`AbpExtensibleDataGrid`文件。
> 
> 模块中的用法可以参考：
> 
> https://github.com/abpframework/abp/blob/dd1bc966be5bbe32656934dea69d099302ba701d/modules/identity/src/Volo.Abp.Identity.Blazor/Pages/Identity/RoleManagement.razor#L24-L32
> 
> https://github.com/abpframework/abp/blob/dd1bc966be5bbe32656934dea69d099302ba701d/modules/identity/src/Volo.Abp.Identity.Blazor/Pages/Identity/RoleManagement.razor.cs#L83-L106

Thank you very much, your answer is very helpful to me
