### ISSUE TITLE
Better navigation to "Next Step" in the documentation

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#17775]
Currently, we are using such a manuel section to the documentation to navigate to the next step:

![image](https://github.com/abpframework/abp/assets/1210527/e576f518-c2d2-4254-b67a-56455da04f90)

It would be better if the docs module provides a built-in system for that. We may define it in the document file with a special format, docs module understands it and generated a navigation button. Also, good to create a Previous button. Maybe two buttons like that:

![image](https://github.com/abpframework/abp/assets/1210527/1043ca03-6b80-4fd4-9a21-4f1c6b8fcb55)

Get help from the design team for a better design idea, I am just a developer :)

After that feature, please check the documentation and apply that for existing documentation for the proper ones.

**Comment by sedasen** [comment]
@salihozkara [Figma](https://www.figma.com/file/1mXESoeknrrYhnhA4erXhe/New-ABP.io?type=design&node-id=15955-80&mode=design&t=cmWaei44I1jwg0XY-4)

![image](https://github.com/abpframework/abp/assets/20427515/f48872b6-06b2-450b-9333-bc8589da4838)
