### ISSUE TITLE
Volo.Abp.Cli `abp install-libs` command ignores Microsoft.NET.Sdk.Razor/Microsoft.NET.Sdk.BlazorWebAssembly projects

### ISSUE THREAD

**Issue by ikappas** [abpframework/abp#17777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `abp install-libs` command ignores Microsoft.NET.Sdk.Razor projects due to a check on 
`abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\LIbs\InstallLibsService.cs:123`

```csharp
using (var reader = File.OpenText(file))
{
    return reader.ReadToEnd().Contains("Microsoft.NET.Sdk.Web");
}
```
I expected to be able to use npm/yarn to bring in packaged resources that will be managed via the abp.resourcemapping.js to be bundled into the application.

### Reproduction Steps

Run `abp install-libs` command in a `Microsoft.NET.Sdk.Razor` or `Microsoft.NET.Sdk.BlazorWebAssembly` project with configured `package.json` and `abp.resourcemapping.js`

### Expected behavior

The command to report the following:
```
ABP CLI 7.3.3
Found 1 projects.
D:\ProjectCompany.Abp.AspNetCore.Components.Web.SomeTheme
Running Yarn on D:\MyCompanyName.Abp.AspNetCore.Components.Web.MyThemeName
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.06s.
```

### Actual behavior

The command reports the following:

```
ABP CLI 7.3.3
No project found in the directory.
```

### Known Workarounds

Add the following comment somewhere in the csproj file:
```
<!-- abp install-libs workaround: Microsoft.NET.Sdk.Web -->
```

### Version

7.3.3

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

This command is designed for the template project. I will add for `Microsoft.NET.Sdk.Razor`, but does `Microsoft.NET.Sdk.BlazorWebAssembly` also need it?

**Comment by ikappas** [comment]
@hikalkan @maliming Good morning and thank you for your swift response! There is a typo in #17779 commit `Microsoft.NET.Sdk.BlazorWebAssemblys` should be `Microsoft.NET.Sdk.BlazorWebAssembly`

**Comment by ikappas** [comment]
@maliming same goes for `Microsoft.NET.Sdk.Razors` which should be `Microsoft.NET.Sdk.Razor`

https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview
