### ISSUE TITLE
File upload in local folder not working

### ISSUE THREAD

**Issue by cgdif** [abpframework/abp#17805]
* Your **ABP 7.3.1**.
* **Angular**
* **EF Core**
* Steps:
* 1: followed every step of the document:
> [Blob-Storing](https://docs.abp.io/en/abp/latest/Blob-Storing)
> [Blob-Storing-File-System](https://docs.abp.io/en/abp/latest/Blob-Storing-File-System)
getting following output on swagger:
Image 1:
![image](https://github.com/abpframework/abp/assets/117594282/74dec2ae-2ef2-4366-bcfd-28c93ee0cd45)

Image 2:
![image](https://github.com/abpframework/abp/assets/117594282/ef413d8f-dd6c-41cf-ad0a-a445d4948d09)

**### how to use that on angular, for saving a file on the folder and retrieving it as there are no samples available for angular**

**Comment by cgdif** [comment]
@maliming

**Comment by cgdif** [comment]
@ebicoglu, @gterdem

**Comment by Keertesh** [comment]
Please suggest

**Comment by mahmut-gundogdu** [comment]
I have wrote an article about it. It wait to review but you be able to read it.

https://github.com/abpframework/abp/pull/17827

**Comment by Keertesh** [comment]
Thanks,Let me try this.

**Comment by cgdif** [comment]
how to get rid of following error.

` The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
[14:05:18 INF] Authorization failed for the request at filter 'Volo.Abp.AspNetCore.Mvc.AntiForgery.AbpAutoValidateAntiforgeryTokenAuthorizationFilter'.
[14:05:18 DBG] Added 0 entity changes to the current audit log`
