### ISSUE TITLE
Show Angular error component when app initialization fails

### ISSUE THREAD

**Issue by szilardd** [abpframework/abp#17811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When the Angular frontend loads and the backend is offline or an error occurs during the initialization HTTP calls (see list below), this is what is shown:

![image](https://github.com/abpframework/abp/assets/968502/3d149b1c-de6f-4b00-8795-c6c754614394)

It's not very user-friendly. I would like to show a custom error page/component instead. Is there some kind of built-in solution for this?

I created the error component and when an error occurs it redirects to that component, but the issue is that when it is shown, the initialization is still being triggered, and since those HTTP calls fail it will show that default error message again instead of the custom component. I'm referring to these initialization HTTP calls:

- api/abp/multi-tenancy/tenants/by-name
- api/abp/application-configuration
- api/abp/application-localization
- .well-known/openid-configuration
- .well-known/jwks

I tried to create another `MainModule` Angular module and moved the `CoreModule`, `AbpOAuthModule` etc. module imports from the `AppModule` into `MainModule` to avoid triggering the initialization when showing the error component, but ran into multiple issues. It seems to work only if these modules are imported from the root module.

I also tried to override the initialization services in my `ErrorModule` so that they don't trigger HTTP calls:

```ts
@NgModule({
     imports: [CommonModule, ErrorRoutingModule, ButtonModule],
     declarations: [ErrorComponent],
     providers: [
         { provide: AbpTenantService, useClass: NoopAbpTenantService }
   ]
})
export class ErrorModule {}

@Injectable()
class NoopAbpTenantService extends AbpTenantService {
    override findTenantById = (id: any) => {
        return of({ success: true, isActive: true });
    };
    override findTenantByName = (name: any) => {
        return of({ success: true, isActive: true });
    };
}
```

But these overrides work only in the `AppModule`. In the `ErrorModule` they are ignored.

### Describe the solution you'd like

Some kind of solution to be able to show a custom error component.

**Comment by mahmut-gundogdu** [comment]
If you want to replace Error  handler function, You may replace the service or some value of service..
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/theme-shared/src/lib/handlers/error.handler.ts

if you want to change error component,
you may override  CreateErrorComponentService 

https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/theme-shared/src/lib/services/create-error-component.service.ts

**Comment by szilardd** [comment]
Thanks for providing the urls, they are helpful.

I found another solution in the documentation:

https://docs.abp.io/en/abp/7.4/UI/Angular/HTTP-Requests#http-error-handling

I created a `StartupErrorComponent` which just displays some custom error message, and registered a new `HTTP_ERROR_HANDLER` in `app.module.ts`.

```ts
import { handleStartupErrors } from '@shared/handlers';
import { StartupErrorComponent } from '@shared/components';
...

@NgModule({
        // standalone
        StartupErrorComponent,
    ],
    providers: [
        { provide: LocationStrategy, useClass: HashLocationStrategy },
        { provide: HTTP_ERROR_HANDLER, useValue: handleStartupErrors },
    ],
    bootstrap: [AppComponent],
})
export class AppModule {}
```

and the `handleStartupErrors` function looks like this:

```ts
import { ContentProjectionService, PROJECTION_STRATEGY } from '@abp/ng.core';
import { HttpErrorResponse } from '@angular/common/http';
import { Injector } from '@angular/core';
import { StartupErrorComponent } from '@shared/components';
import { throwError } from 'rxjs';

const startupUrls = [
    'api/abp/multi-tenancy/tenants/by-name',
    'api/abp/application-configuration',
    'api/abp/application-localization',
    '.well-known/openid-configuration',
    '.well-known/jwks',
];

export function handleStartupErrors(injector: Injector, httpError: HttpErrorResponse) {
    const isStartupUrl = startupUrls.some(url => {
        const index = httpError?.url?.indexOf(url);
        return index && index >= 0;
    });

    if (isStartupUrl) {
        const contentProjection = injector.get(ContentProjectionService);
        contentProjection.projectContent(
            PROJECTION_STRATEGY.AppendComponentToBody(StartupErrorComponent),
        );
        return;
    }

    return throwError(() => httpError);
}
```

I only want to show the custom error component when there is an error during startup.

**Comment by AsmaaHassanHamza2022** [comment]
thanks all for your solution it is very useful, I am facing the same issue and I use this way but have one problem 
in my app initialization 2 configuration endpoints Fail so the component that I use as an Error Component renders twice 
What do you think I should do to prevent this duplication?
