### ISSUE TITLE
Blazor Wasm - When I click on the login button I get a 400 error

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#17829]
**App:** Blazor Wasm - EfCore `7.4.0`

![image](https://github.com/abpframework/abp/assets/99716457/fc6e6a99-aa7f-4dbc-8812-a8c9546edf76)

**Comment by enisn** [comment]
I couldn't reproduce the same issue, make sure you have cleared all the cookies on `localhost` domain, and make sure you used a freshly generated database and make sure you ran DbMigrator and seeded all the required OpenId configuretion

**Comment by gterdem** [comment]
Seems like data seeding problem. Please make sure the db is seeded.
