### ISSUE TITLE
Need a demo for new feature int V7.4.0 Database Migration System for EF Core

### ISSUE THREAD

**Issue by xxvolvo** [abpframework/abp#17840]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

Is there a demo to show how to use this new feature? 
For example, how to execute `CheckAndApplyDatabaseMigrationsAsync`.
I cannot successfully resolve a service witch derives from `EfCoreRuntimeDatabaseMigratorBase `class in `OnPostApplicationInitializationAsync `

**Comment by maliming** [comment]
> I cannot successfully resolve a service witch derives from EfCoreRuntimeDatabaseMigratorBase class in OnPostApplicationInitializationAsync 

What happened?

**Comment by xxvolvo** [comment]
> > I cannot successfully resolve a service witch derives from EfCoreRuntimeDatabaseMigratorBase class in OnPostApplicationInitializationAsync
> 
> What happened?

derive like below
![image](https://github.com/abpframework/abp/assets/16984534/a6433ce5-f94e-4125-9503-0f9df90e8199)
and try to resovle in OnPostApplicationInitializationAsync like below
![image](https://github.com/abpframework/abp/assets/16984534/5f9a0406-6389-4fca-a9ed-1f7bf4c92fca)
then throw a exception 
![image](https://github.com/abpframework/abp/assets/16984534/c5fe3a00-7e5e-4f27-b66d-98907bd109f5)

**Comment by maliming** [comment]
You can try removing the `databaseName` from the `TestEfCoreRuntimeDatabaseMigrator's ctor, then passing a fixed string to the base class ctor.

**Comment by xxvolvo** [comment]
> You can try removing the `databaseName` from the `TestEfCoreRuntimeDatabaseMigrator's ctor, then passing a fixed string to the base class ctor.

Got it,thx,
