### ISSUE TITLE
Duplicate register when using Google authentication

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#17862]
Reproduce steps:
1- Login via Google and finish the registration step.
2- Open an incognito window and try to log in again via Google

I opened this to this repo because it looks like a problem in the account-module.

![image](https://github.com/abpframework/abp/assets/9526587/573d0c10-be50-44f2-8ce6-e348158eef81)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/17883
