### ISSUE TITLE
Add CDN support for bundling

### ISSUE THREAD

**Issue by jasenf** [abpframework/abp#17864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently when deploying an ABP service we have no way to distribute bundles JS and CSS to our CDN.  

### Describe the solution you'd like

The built-in ASP.NET bundling provides the option to set a URL to be used when injecting the bundled URL into pages, see here: https://learn.microsoft.com/en-us/aspnet/mvc/overview/performance/bundling-and-minification#using-a-cdn

Optimally we would have the similar ability when configuring our bundles:

```
Configure<AbpBundlingOptions>(options =>
        {
            options
                .ScriptBundles
                .Add("MyGlobalBundle", bundle => {
                    bundle.Url("https://my.cdn.com")
                    bundle.AddFiles(
                        "/libs/jquery/jquery.js",
                        "/libs/bootstrap/js/bootstrap.js",
                        "/libs/toastr/toastr.min.js",
                        "/scripts/my-global-scripts.js"
                    );
                });                
        })
```

**Comment by leonkosak** [comment]
Somehow related @maliming?
https://github.com/abpframework/abp/issues/14107

**Comment by maliming** [comment]
hi @leonkosak 

I will check them as soon as possible.

**Comment by leonkosak** [comment]
@maliming CDN url (or more of them) should be located in appsettings.json and also be optional in my opinion (based on the suggested code snippet in the first post). What do you think?

**Comment by maliming** [comment]
hi @leonkosak 

The PR of CDN https://github.com/abpframework/abp/pull/17894

I will check the https://github.com/abpframework/abp/issues/14107 now.
