### ISSUE TITLE
AbpExtensibleDataGrid component enables inline editing mode error

### ISSUE THREAD

**Issue by He-Wu** [abpframework/abp#17869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I use the AbpExtensibleDataGrid component to enable inline editing mode. My column names are Enum enumeration types, and some columns need to be customized with some editing styles. For example, when editing, a certain column needs to be rendered into a drop-down box and go to the data source to obtain the drop-down options. I I don’t know how to use this component to complete it. If I use the Blazorise DataGrid component directly, I can use EditTemplate to customize the editing template, but there is no such flexible configuration method in the AbpExtensibleDataGrid component.

### Reproduction Steps

![image](https://github.com/abpframework/abp/assets/56440130/2f1781b9-5560-4ec9-a6cd-4e4e75c05e4b)

### Expected behavior

I can customize the columns of this component through EditTemplate

### Actual behavior

I cannot use Columns to configure custom templates

### Version

7.3.3

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
You can try : https://docs.abp.io/en/abp/latest/UI/Blazor/Data-Table-Column-Extensions#rendering-custom-components-in-the-data-table-columns
