### ISSUE TITLE
abp language chang event

### ISSUE THREAD

**Issue by He-Wu** [abpframework/abp#17877]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

I'm using LeptonX Blazor UI and I want to be able to listen to the event and execute some custom methods when the language changes, what should I do?

**Comment by maliming** [comment]
There is an `ApplicationConfigurationChangedService`. 

https://github.com/abpframework/abp/pull/15649

**Comment by He-Wu** [comment]
> There is an `ApplicationConfigurationChangedService`.
> 
> #15649
![image](https://github.com/abpframework/abp/assets/56440130/36747fe9-5cd1-4cfa-ac9f-3c5916c92803)
Hello, I changed the language but the method is not executed
```
public override void OnPostApplicationInitialization(Volo.Abp.ApplicationInitializationContext context)
{
    base.OnPostApplicationInitialization(context);
    ApplicationConfigurationChangedService ApplicationConfigurationChangedService = context.GetApplicationBuilder().ApplicationServices.GetRequiredService<ApplicationConfigurationChangedService>();

    ApplicationConfigurationChangedService.Changed += () =>
    {
        Blazorise.Localization.ITextLocalizerService LocalizationService = context.GetApplicationBuilder().ApplicationServices.GetRequiredService<ITextLocalizerService>();
        LocalizationService.ChangeLanguage(CultureInfo.CurrentCulture.IetfLanguageTag.Split("-")[0]);
    };
}
```

**Comment by maliming** [comment]
https://github.com/search?q=repo%3Aabpframework%2Fabp%20ApplicationConfigurationChangedService&type=code

**Comment by He-Wu** [comment]
> https://github.com/search?q=repo%3Aabpframework%2Fabp%20ApplicationConfigurationChangedService&type=code

After I clicked on the page to switch languages, it did not trigger
![image](https://github.com/abpframework/abp/assets/56440130/e036037a-1007-47da-a992-6993ce188767)

**Comment by maliming** [comment]
You can try to use `ApplicationConfigurationChangedService` in a component.

**Comment by He-Wu** [comment]
> You can try to use `ApplicationConfigurationChangedService` in a component.

![image](https://github.com/abpframework/abp/assets/56440130/81bd66bd-158d-4be9-9a4e-3e55b8cb92fd)
Hello, I used it in the component, but it didn’t work. I don’t know why.

**Comment by maliming** [comment]
Could you let me know if you're using the Blazor server?

`ApplicationConfigurationChangedService` is designed for wasm.

**Comment by He-Wu** [comment]
> Could you let me know if you're using the Blazor server?
> 
> `ApplicationConfigurationChangedService` is designed for wasm.

@maliming  Yes,I using the Blazor Server

**Comment by maliming** [comment]
The page will be refreshed when you switch the language. so you can use the 

```cs
CultureInfo.CurrentCulture
CultureInfo.CurrentUICulture
```

**Comment by He-Wu** [comment]
> The page will be refreshed when you switch the language. so you can use the
> 
> ```cs
> CultureInfo.CurrentCulture
> CultureInfo.CurrentUICulture
> ```
@maliming  thank you
