### ISSUE TITLE
Settings Module

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1787]
How can I get the settings management page to show?

I installed the module via CLI and executed migrations correctly thank you.

Do settings map to appsettings.json?

**Comment by maliming** [comment]
Well, this feature is not simple, there is no settings managementpage provided by default.
Basically you need to provide an implementation of the `ISettingPageContributor` for the `Contributors` of the `SettingManagementPageOptions`. You also need to provide a component that implements the `AbpViewComponent`. You can read and modify the settings in your ViewComponent.

You can wait for documentation on this feature. I believe the documentation will be improved soon.

**Comment by wocar** [comment]
So if I want to change for example the SelfRegister configuration easily
what can I do can i map it to appsetttings.json

**Comment by maliming** [comment]
> I want to change for example the SelfRegister configuration easily

Please use the `ISettingManager `interface of the `setting-management` module to manage settings.

**Comment by wakuflair** [comment]
The setting related docs have been released, but I still need some guidance on how to use the `ISettingPageContributor`.

My goal is provide a UI that allows users to manage the setting values by themselves with the Setting Management Module.

Should I expect some more docs?

**Comment by hikalkan** [comment]
You're right @wakuflair, no document for the UI part yet. I created an issue: https://github.com/abpframework/abp/issues/2187

BTW, you can just create a page and handle it yourself. Setting management UI system is useful if you want to create a reusable module, define the UI in the module package and show the setting UI in an application using this module.
