### ISSUE TITLE
CombineExpressions disappeared from AbpDbContext in 7.4

### ISSUE THREAD

**Issue by lgadola** [abpframework/abp#17873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created custom filters according to the [documentation](https://docs.abp.io/en/abp/latest/Data-Filtering)
This worked in 7.3
In 7.4 the function CombineExpressions seems to have disappeared.

### Reproduction Steps

create code like this in your DbContext:
`protected bool IsActiveFilterEnabled => DataFilter?.IsEnabled<IIsActive>() ?? false;

protected override bool ShouldFilterEntity<TEntity>(IMutableEntityType entityType)
{
    if (typeof(IIsActive).IsAssignableFrom(typeof(TEntity)))
    {
        return true;
    }

    return base.ShouldFilterEntity<TEntity>(entityType);
}

protected override Expression<Func<TEntity, bool>> CreateFilterExpression<TEntity>()
{
    var expression = base.CreateFilterExpression<TEntity>();

    if (typeof(IIsActive).IsAssignableFrom(typeof(TEntity)))
    {
        Expression<Func<TEntity, bool>> isActiveFilter =
            e => !IsActiveFilterEnabled || EF.Property<bool>(e, "IsActive");
        expression = expression == null 
            ? isActiveFilter 
            : CombineExpressions(expression, isActiveFilter);
    }

    return expression;
}
`

### Expected behavior

Compile error: The name 'CombineExpressions' does not exist in the current context

### Version

7.4

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by JadynWong** [comment]
https://github.com/search?q=repo%3Aabpframework%2Fabp%20CombineExpressions&type=code

https://github.com/abpframework/abp/commit/2df380724d8cc9b42388a1f288f19e6c473693e1

**Comment by fileman** [comment]
Has workaround we can use QueryFilterExpressionHelper.CombineExpressions() in CreateFilterExpression method
Wait for fix or document update
