### ISSUE TITLE
ABP NuGet 8.4.0 references an pre-release dependency

### ISSUE THREAD

**Issue by damien-r** [abpframework/abp#17887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

I am trying to update to the latest ABP NuGet, currently the verision 8.4.0. https://www.nuget.org/packages/Abp

Unfortunately, it references the NuGet [System.ComponentModel.Annotations](https://www.nuget.org/packages/System.ComponentModel.Annotations/) (>= 6.0.0-preview.4.21253.7), but this version 6 is not available without enabling the pre-release. Am I missing something? ABP NuGet 8.4.0 should be marked as pre-release if it depends on pre-release dependencies?

### Version

8.4.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by hikalkan** [comment]
Can you please open the issue here: https://github.com/aspnetboilerplate/aspnetboilerplate
This is wrong repository for this issue.

**Comment by damien-r** [comment]
Thanks for your answer and sorry for the mistake. I created it here: [#6801](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/6801)
