### ISSUE TITLE
UseAbpRequestLocalization arabic FormData issue

### ISSUE THREAD

**Issue by alihdev** [abpframework/abp#17897]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When entering data (FormData), we encountered an error:

```
{
    "error": {
        "code": null,
        "message": "طلبك غير صحيح!",
        "details": "تم الكشف عن الأخطاء التالية أثناء التحقق .\r\n - The value '-1' is not valid for Factor.\r\n",
        "data": {},
        "validationErrors": [
            {
                "message": "The value '-1' is not valid for Factor.",
                "members": [
                    "contractAmounts[0].Factor"
                ]
            }
        ]
    }
}
```

The Default Culture is **ar**, our configurations :  

```c#

        var supportedCultures = new[] { new CultureInfo("ar"), new CultureInfo("en") };

        app.UseAbpRequestLocalization(options =>
        {
            options.DefaultRequestCulture = new RequestCulture("ar");
            options.SupportedCultures = supportedCultures;
            options.SupportedUICultures = supportedCultures;
            options.RequestCultureProviders = new List<IRequestCultureProvider>
            {
                new AcceptLanguageHeaderRequestCultureProvider()
            };
        });
```

### Version

6

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Can you add a new localized text?

```json
"The value '{0}' is not valid for '{1}'.": "your ar text"
```

**Comment by alihdev** [comment]
Hello, 
Thank u for ur reply. the issue is not in the localized key

It appears that the issue lies within the middleware of localizations when the request header includes the "accepted-language" field. Specifically, when the accepted language is set to "ar" and the body of the request contains either -1 or 1,123, an error is thrown.

On the other hand, when the accepted language is set to "en," everything runs smoothly without any errors.

**Comment by maliming** [comment]
hi

Have you tried the plain asp net core app? Such error does not come from abp framework.

**Comment by alihdev** [comment]
Yes, we need your help resolving this error.

**Comment by maliming** [comment]
Does your code work on the plain asp net core app but doesn't work with the abp framework?

If so, please share some code to reproduce.

**Comment by alihdev** [comment]
Please check: 
- Project [DotnetAbp](https://github.com/alihdev/DotnetAbp.Issues) with localization issue 400
- Request [Img](https://github.com/alihdev/DotnetAbp.Issues/blob/main/src/DotnetAbp.Issues.Application/Issues/LocalizationIssue.jpg) and [cURL](https://github.com/alihdev/DotnetAbp.Issues/blob/main/src/DotnetAbp.Issues.Application/Issues/LocalizationIssueCURL.txt)

**Comment by maliming** [comment]
hi

The `NegativeSign` of `ar` is not equal `-`.

```
؜-1
```

<img width="1169" alt="image" src="https://github.com/abpframework/abp/assets/6908465/a84f76d7-fa13-4b7d-83c2-275f74b20b51">

**Comment by alihdev** [comment]
Hello,
Okay, thank you. If we set the number format to be the same as in English using 

```c3
arCultureInfo.NumberFormat = enCultureInfo.NumberFormat;
```

is this approach acceptable, or is there a more efficient way to achieve this?
