### ISSUE TITLE
What is the milestone time for the ABP V1.x?

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#1789]
The ABP is so excellent, I hope to get the milestone time in a hurry. Because I plan to use it in my new project if possible. :) Do you have a publishing plan for the ABP v1.x version? Thanks so much.

**Comment by maliming** [comment]
You can expect ABP v1.0 to be released in the first half of the October.

https://blog.abp.io/abp/ABP-v0-19-Release-With-New-Angular-UI
