### ISSUE TITLE
Replace `ImageSharp` library.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#17909]
https://github.com/mono/SkiaSharp

**Comment by rqx110** [comment]
can you explain why we need to replace `ImageSharp`?
It's best to let the community know why.

**Comment by maliming** [comment]
Because it's license might not be suitable for abp.

https://github.com/SixLabors/ImageSharp/blob/main/LICENSE#L37

**Comment by DonVliet** [comment]
> Because it's license might not be suitable for abp.
> 
> https://github.com/SixLabors/ImageSharp/blob/main/LICENSE#L37

@maliming @rqx110 The Blazorise components used in the Blazor project have a similar licensing issue and infact the Blazorise website specifies that the components are not for commercial use unless we buy the Professional or higher license.

It might therefore be worth using something like MudBlazor, or other open source components instead?

Thanks, Don

**Comment by rqx110** [comment]
@DonVliet there is a discussion about blazorise: https://github.com/abpframework/abp/discussions/17248
