### ISSUE TITLE
CMS Kit: Fix missing method exception problem

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#17906]
![image](https://github.com/abpframework/abp/assets/43685404/105ce79b-109a-4300-8898-91452fc46025)

Update the `SixLabors.ImageSharp.Drawing` package version and make the related changes:

https://github.com/abpframework/abp/blob/6ecdeb991188f5b9be52393315a9c001adfe2a6b/Directory.Packages.props#L141-L142

**Comment by enisn** [comment]
Still a problem for CMS Kit

**Comment by enisn** [comment]
https://github.com/abpframework/abp/pull/17916#issuecomment-1767912201
