### ISSUE TITLE
We should continue to use Newtonsoft.Json in MVC.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1790]
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support

https://github.com/abpframework/abp/blob/654eeede81a733382066bfd00ab19b6b65ceec0e/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AbpAspNetCoreMvcModule.cs#L114-L117

```
var mvcBuilder = context.Services.AddMvc()
	.AddNewtonsoftJson(options =>
		{
			options.SerializerSettings.ContractResolver =
				new AbpMvcJsonContractResolver(context.Services);
		})
```

**Comment by ebicoglu** [comment]
To replace `System.Text.Json` with `Microsoft.AspNetCore.Mvc.NewtonsoftJson` package, write the below code to your final application.

Step-1: Install the [Microsoft.AspNetCore.Mvc.NewtonsoftJson v3.0.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson) package to your Web project. 

Step-2:
```
public class MyWebModule: AbpModule {

 public override void ConfigureServices(ServiceConfigurationContext context) {

  var configuration = context.Services.BuildConfiguration();
  //............

  context.Services.PreConfigure < IMvcBuilder > (mvcBuilder => {
   mvcBuilder.AddNewtonsoftJson(
    options => options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver());
  });

  //............
 }
}
```

**Comment by hikalkan** [comment]
It seems System.Text has misssing features. So, we will consider to use Newtonsoft.Json by default.
