### ISSUE TITLE
NumericEdit component is used incorrectly in LeptonX Theme theme

### ISSUE THREAD

**Issue by He-Wu** [abpframework/abp#17917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I used the LeptonX Theme and then used the NumericEdit component. It does not limit the input type. This is different from the NumericEdit used on the blazorise official website. Using TValue in the blazorise official website document can limit the input type. I set TValue=int, but decimals can still be input.

### Reproduction Steps

this is my code
```
@page "/"
<NumericEdit TValue="int"></NumericEdit>
```

page result,but decimals can still be input.
![image](https://github.com/abpframework/abp/assets/56440130/ff32e191-f45f-4ba0-8812-f19b91e1506a)

### Expected behavior

Only integers can be entered

### Actual behavior

Can enter decimals

### Version

7.3.3

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
https://support.abp.io/QA/Questions/6034/NumericEdit-component-is-used-incorrectly-in-LeptonX-Theme-theme
