### ISSUE TITLE
Upgrade Pomelo.EntityFrameworkCore.MySql package for EF core 3.0 when it is available

### ISSUE THREAD

**Issue by xgd224743** [abpframework/abp#1791]
upgrade to 0.21.0 ,run httpapi.host ,

throw
HTTP Error 500.30 - ANCM In-Process Start Failure 

create new project ,also same error

**Comment by maliming** [comment]
> HTTP Error 500.30 - ANCM In-Process Start Failure

see https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.0#50030-in-process-startup-failure

**Comment by wangchuangruler** [comment]
![image](https://user-images.githubusercontent.com/25163291/65484668-337f7400-ded2-11e9-8021-02c28d2f1db8.png)

**Comment by maliming** [comment]
Pomelo does not support net core 3.0. 

Please follow: 
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/797

**Comment by xgd224743** [comment]
@maliming 
HttpApiHostModule.cs
must delete under code, then run api project
//app.UseSwagger();
            //app.UseSwaggerUI(options =>
            //{
            //    options.SwaggerEndpoint("/swagger/v1/swagger.json", "UAM API");
//});

**Comment by maliming** [comment]
We should update it when Pomelo supports net core 3.0.

**Comment by maliming** [comment]
Releasing 3.0.0-preview1 

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/839

**Comment by lauxjpn** [comment]
Is this issue just kept open until we can confirm that is is indeed implicitly fixed with the 3.0.0 preview, or do we actually need to take action of some kind?

@xgd224743, @jack-gaojz Also consider https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/797#issuecomment-533895024 as a temporary workaround from the thread that @maliming referenced above.

**Comment by Y2zz** [comment]
I just created a new project and found this problem, I can't create a migration script.

**Comment by hikalkan** [comment]
@maliming can you upgrade to [3.0.0-rc1-final](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/3.0.0-rc1-final)? Thanks.

**Comment by maliming** [comment]
I wanted to wait for the official version of 3.0.0 before, but upgrading to rc1 is no problem.
