### ISSUE TITLE
ConcurrencyStamp field size in table

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#17922]
What is ConcurrencyStamp field size in SQL table ?

It is changing from version to version.

Is it **nvarchar(40) not null** in latest ABP 7.4.0 version ?

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/blob/251238bbd8659df6c17ecdb78f3cf60a473a11ba/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs#L43-L46

https://github.com/abpframework/abp/blob/251238bbd8659df6c17ecdb78f3cf60a473a11ba/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/ConcurrencyStampConsts.cs#L5

**Comment by sebitsi** [comment]
Thanks @maliming.

What about nullability ? 

ConcurrencyStamp field definition changed from null (ABP ver 7.3.2) to not null (7.4.0).

Is this related to EF or ABP ? 

If "not null" is for all ConcurrencyStamp fields (ver 7.4.0+), 
what value you propose to fill in when migrating to 7.4.0+ ?

**Comment by maliming** [comment]
It may be related to the EF Core. I don't remember that we changed that.
