### ISSUE TITLE
Are AbpGlobalFilters supported for entity inheritance ?

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#17921]
I have noticed that global filter for tenant (and soft delete) is not set if i query entities are implemented as EF inheritance.

After digging in ABP source code i found:

```
    protected virtual void ConfigureGlobalFilters<TEntity>(ModelBuilder modelBuilder, IMutableEntityType mutableEntityType)
        where TEntity : class
    {
        if (mutableEntityType.BaseType == null && ShouldFilterEntity<TEntity>(mutableEntityType))
        {
            var filterExpression = CreateFilterExpression<TEntity>();
            if (filterExpression != null)
            {
                modelBuilder.Entity<TEntity>().HasAbpQueryFilter(filterExpression);
            }
        }
    }
```
Condition **mutableEntityType.BaseType == null** prevents setting tenant filter if entity is derived from some base class.

Is my observation correct?
Why is this condition necessary?

Edvin

**Comment by maliming** [comment]
hi

> Filters can only be defined for the root Entity Type of an inheritance hierarchy.

https://learn.microsoft.com/en-us/ef/core/querying/filters#limitations

**Comment by sebitsi** [comment]
@maliming Thanks.

This limitation should be also documented in ABP documentation. (or i missed it ?)
