### ISSUE TITLE
Schematic: Invalid proxy model for DateOnly type

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#17923]
## Description

Please check detail at the question: https://support.abp.io/QA/Questions/5965

**Comment by dmannionDCI** [comment]
It looks like this wasn't included in 7.4.1.  Can we get this prior to 8.0?  If not, what is the ETA for 8.0?

**Comment by maliming** [comment]
hi @dmannionDCI 

This will be available in 8.0.
