### ISSUE TITLE
Input tags automatically get "Required" attiributes, even if they are not required.

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#1793]
Unrelated to tag helpers because this occurs for asp.net input tags too.

**Comment by hikalkan** [comment]
Couldn't repeat.

**Comment by yekalkan** [comment]
Closing this because this is a result of a breaking change in c# 8.0 release.

**Comment by maliming** [comment]
I am curious what does this have to do with C# 8?

**Comment by yekalkan** [comment]
in c# 8.0, even if you don't set [Required] attribute, string fields becomes required in input tag helpers unless you make them nullable (string?).
