### ISSUE TITLE
Unable to resolve already created scoped dependency in DbContext

### ISSUE THREAD

**Issue by MannRobertJ** [abpframework/abp#17930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using ABP 7.3.2 with Blazor Server and EFCore.

I'm facing the same issue as #12206. I have a scoped service `ShouldBeScoped`, which I inject in my `DbContext`. However, because the `DbContext` is used within a scope created by the `UnitOfWorkManager` a new instance of `ShouldBeScoped` gets resolved. 

The proposed solution to that issue was to use `IHybridServiceScopeFactory` to resolve the scoped service `ShouldBeScoped`. This solution no longer works because `IHybridServiceScopeFactory` no longer exists. Injecting an `IServiceScopeFactory` to resolve the dependency also does not fix the issue, because then it simply resolves a new instance. 

### Reproduction Steps

Create an ABP project using the following command

    abp new ScopedDependencyIssue -u blazor-server -dbms SQLite -csf 

In the `Application` project create the following class

    public class TestAppService : ScopedDependencyIssueAppService, ITestAppService
    {
        private readonly IRepository<IdentityUser, Guid> repository;

        public TestAppService(IRepository<IdentityUser, Guid> repository)
        {
            this.repository = repository;
        }

        public async Task<int> GetUserCount()
        {
            return await repository.CountAsync();
        }
    }

In Application.Contracts create

    public interface ITestAppService
    {
        Task<int> GetUserCount();
    }

In Domain.Shared create the following class:

    public class ShouldBeScoped : IScopedDependency
    {
        public Guid Test { get; };

        public ShouldBeScoped()
        {
            Test = Guid.NewGuid();
        }
    }

Replace the contents of Index.razor with

    @page "/"
    @using ScopedDependencyIssue.AppService;
    @using Volo.Abp.MultiTenancy
    @inherits ScopedDependencyIssueComponentBase
    @inject AuthenticationStateProvider AuthenticationStateProvider
    @inject ShouldBeScoped shouldBeScoped
    @inject ITestAppService appService;
    <h1>
        @shouldBeScoped.Test
    </h1>
    <h1>
        @count
    </h1>

and replace the contents of Index.razor.cs with

    using System.Threading.Tasks;

    namespace ScopedDependencyIssue.Blazor.Pages;

    public partial class Index
    {
        private int count = -1;

        protected override async Task OnInitializedAsync()
        {
            count = await appService.GetUserCount();
        }
    }

Add the field 

    private readonly ShouldBeScoped shouldBeScoped;

to `ScopedDependencyIssueDbContext` and update the constructor to be

    public ScopedDependencyIssueDbContext(DbContextOptions<ScopedDependencyIssueDbContext> options, ShouldBeScoped shouldBeScoped)
        : base(options)
    {
        this.shouldBeScoped = shouldBeScoped;
    }

Also update `ScopedDependencyIssueDbContextFactory` with the following lines 

    private readonly ShouldBeScoped shouldBeScoped;

    public ScopedDependencyIssueDbContextFactory(ShouldBeScoped shouldBeScoped)
    {
        this.shouldBeScoped = shouldBeScoped;
    }

and replace

    return new ScopedDependencyIssueDbContext(builder.Options);

with

    return new ScopedDependencyIssueDbContext(builder.Options, shouldBeScoped);

Run the DbMigrator project.

Place a breakpoint in the constructor of `ScopedDependencyIssueDbContext`. Start the Blazor project

Make a note of `shouldBeScoped.Test`. Continue. Check the value that appears on the Index page. You would want them to be the same. However they are different.

Now try implementing the suggested fix from the linked issue. So update the constructor of the DbContext with

    public ScopedDependencyIssueDbContext(DbContextOptions<ScopedDependencyIssueDbContext> options, IServiceScopeFactory serviceScopeFactory)
        : base(options)
    {
        this.shouldBeScoped = serviceScopeFactory.CreateScope().ServiceProvider.GetRequiredService<ShouldBeScoped>();
    }

and update the factory in the same way.

Run the Blazor project again. Check the Guids in the same way again. Once again they give different results.

### Expected behavior

The instance of `ShouldBeScoped` in the Index.razor page and the DbContext should be the same. Or there should be some way to reliably inject a scoped service into a DbContext without it resolving a new instance.

### Actual behavior

A new instance is resolved in the DbContext.

### Regression?

The previous solution was to use the `IHybridServiceScopeFactory` to resolve the dependency. This worked as expected. However this interface no longer exists.

### Version

7.3.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi @MannRobertJ 

Please upload your test project on GitHub, Thanks.

**Comment by MannRobertJ** [comment]
hi @maliming 

I've created it here: https://github.com/MannRobertJ/ScopedDependencyIssue

Thanks for looking into it

**Comment by maliming** [comment]
hi

The `DbContext` resolve from `service provider` of `unit of work`.

```cs
public ScopedDependencyIssueDbContext(DbContextOptions<ScopedDependencyIssueDbContext> options, IServiceProvider serviceProvider)
    : base(options)
{
    _shouldBeScoped = serviceProvider.GetRequiredService<ShouldBeScoped>();
}
```

```cs
public partial class Index
{
    private int count = -1;

    public IServiceProvider ServiceProvider { get; set; }
    public ShouldBeScoped ShouldBeScoped { get; set; }
    public ITestAppService AppService { get; set; }

    public Index(IServiceProvider serviceProvider)
    {
        ServiceProvider = serviceProvider;
    }

    protected override async Task OnInitializedAsync()
    {
        var unitOfWorkManager = ServiceProvider.GetRequiredService<IUnitOfWorkManager>();
        using (var uow = unitOfWorkManager.Begin())
        {
            ShouldBeScoped = unitOfWorkManager.Current.ServiceProvider.GetRequiredService<ShouldBeScoped>();
            AppService = unitOfWorkManager.Current.ServiceProvider.GetRequiredService<ITestAppService>();

            count = await AppService.GetUserCount();

            await uow.CompleteAsync();
        }
    }
}

```

**Comment by MannRobertJ** [comment]
Ok this at least gives a workaround so I'm gonna accept this solution. 

Thanks!
