### ISSUE TITLE
How can dependency injection when use AutoMapper IMappingAction<,> interface?

### ISSUE THREAD

**Issue by kefengwei** [abpframework/abp#1794]
When create AutoMapper in Profile by .BeforeMap<BeforeActionClass>, the BeforeActionClass can't work with dependency injection.

**Comment by maliming** [comment]
Please share some code.

**Comment by kefengwei** [comment]
`
using System;
using System.Globalization;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Localization;
using Volo.Abp.Domain.Entities;

namespaceCommon.AutoMapper
{
    public static class MultiLingualAutoMapExtensions
    {

        public static CreateMultiLingualMapResult<TMultiLingualEntity, TTranslation, TDestination>
            CreateMultiLingualMap<TMultiLingualEntity, TMultiLingualEntityPrimaryKey, TTranslation, TDestination>(
                this Profile configuration)
            where TTranslation : class, IEntityTranslation<TMultiLingualEntity, TMultiLingualEntityPrimaryKey>
            where TMultiLingualEntity : IMultiLingualEntity<TTranslation>
        {
            var result = new CreateMultiLingualMapResult<TMultiLingualEntity, TTranslation, TDestination>
            {
                TranslationMap = configuration.CreateMap<TTranslation, TDestination>(),
                EntityMap = configuration.CreateMap<TMultiLingualEntity, TDestination>()
                    .BeforeMap<BeforeAction<TMultiLingualEntity, TDestination, TTranslation,
                            TMultiLingualEntityPrimaryKey>
                    >()
            };


            return result;
        }
    }

    public class BeforeAction<TMultiLingualEntity,
        TDestination,
        TTranslation,
        TMultiLingualEntityPrimaryKey> : IMappingAction<TMultiLingualEntity, TDestination>
        where TTranslation : class, IEntityTranslation<TMultiLingualEntity, TMultiLingualEntityPrimaryKey>
        where TMultiLingualEntity : IMultiLingualEntity<TTranslation>
    {
        private readonly IMultiLingualMapContext _multiLingualMapContext;

        public BeforeAction(IMultiLingualMapContext multiLingualMapContext)
        {
            _multiLingualMapContext = multiLingualMapContext;
        }

        public void Process(TMultiLingualEntity source, TDestination destination, ResolutionContext context)
        {
            var translation =
                source.Translations.FirstOrDefault(pt => pt.Language == CultureInfo.CurrentUICulture.Name);
            if (translation != null)
            {
                context.Mapper.Map(translation, destination);
                return;
            }

            var defaultLanguage =
                _multiLingualMapContext.SettingDefinitionManager.Get(LocalizationSettingNames.DefaultLanguage)
                    .DefaultValue;

            translation = source.Translations.FirstOrDefault(pt => pt.Language == defaultLanguage);
            if (translation != null)
            {
                context.Mapper.Map(translation, destination);
                return;
            }

            translation = source.Translations.FirstOrDefault();
            if (translation != null)
            {
                context.Mapper.Map(translation, destination);
            }
        }
    }
}
`
When i try to map DTO, I got error:`
Mapping types:
List`1 -> List`1
System.Collections.Generic.List`1[[Mortars.ProductManagement.Features.Feature, Mortars.ProductManagement.Domain, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[Mortars.ProductManagement.Features.Public.Dtos.FeatureDto, Mortars.ProductManagement.Application.Contracts, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]]
AutoMapper.AutoMapperMappingException: Error mapping types.
`

**Comment by kefengwei** [comment]
I reference aspnetboilerplate [Multi-Lingual-Entities](https://aspnetboilerplate.com/Pages/Documents/Multi-Lingual-Entities) to implement Multi-Lingual-Entities.

**Comment by kefengwei** [comment]
@maliming I have solve this problem according #1714 in your reply. Thank you very much.
