### ISSUE TITLE
How can I remove unwanted data from error JSON in ABP

### ISSUE THREAD

**Issue by nimaaran** [abpframework/abp#17949]
I configured ABP with the following options:

```
Configure<AbpExceptionHandlingOptions>(options =>
{
    options.SendExceptionsDetailsToClients = false;
    options.SendStackTraceToClients = false;
});
```

But still I have some unwanted `data `in the error JSON like this:

```
{
    "error": {
        "code": null,
        "message": "An internal error occurred during your request!",
        "details": null,
        "data": {
            "HelpLink.ProdName": "Microsoft SQL Server",
            "HelpLink.EvtSrc": "MSSQLServer",
            "HelpLink.EvtID": "4060",
            "HelpLink.BaseHelpUrl": "https://go.microsoft.com/fwlink",
            "HelpLink.LinkId": "20476"
        },
        "validationErrors": null
    }
}
```

How can I remove `data `and its subset from the response JSON.

I tried to find a way to filter Unhandled exceptions or something like that in ABP. In my solution, unfortunately I have a lot of unhandled exceptions and I should have a canonical point to catch them and prevent data leakage in the system.

**Comment by maliming** [comment]
hi

You can override the [DefaultExceptionToErrorInfoConverter](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.ExceptionHandling/Volo/Abp/AspNetCore/ExceptionHandling/DefaultExceptionToErrorInfoConverter.cs#L22) and remove `data ` from the `RemoteServiceErrorInfo`.

**Comment by nimaaran** [comment]
Thank you @maliming. It works fine. I think that we should have better control over `data` property of JSON error. Maybe something like this. 

```
Configure<AbpExceptionHandlingOptions>(options =>
{
    options.SendExceptionsDetailsToClients = false;
    options.SendStackTraceToClients = false;
    options.SendAdditionalDataToClients = false;
});
```
