### ISSUE TITLE
Sample to load the parent entity object in the entity app service class

### ISSUE THREAD

**Issue by Muhammad-Fakhr-Elden** [abpframework/abp#1795]
Please provide a Sample to load the parent entity (eager loading) in the entity app service class

**Comment by hitaspdotnet** [comment]
You can read [join clause](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/join-clause) docs, this is not related to ABP.

**Comment by hitaspdotnet** [comment]
```C#
            var posts = from post in _postRepository.GetAll()
                        join joinedBlog in _blogRepository.GetAll() on post.BlogId equals joinedBlog.Id into joinedBlogs
                        from blog in joinedBlogs.DefaultIfEmpty()

                        select new GetPostForViewDto()
                        {
                            Post = ObjectMapper.Map<PostDto>(post),
                            BlogName = blog == null ? "" : blog.Name.ToString()
                        };
```

**Comment by Muhammad-Fakhr-Elden** [comment]
Thank you for your reply. I was thinking about how to use the EF "include clause" for the parent entity. I heard about some method in abp called "WithDetails" in the default repository implementation but I do not know how to use it in the child entity app service class that inherits from crudAppService.

**Comment by hitaspdotnet** [comment]
If you have a reference from blog entity into post entity (which is not suggested for aggregate roots) , then in your repository call method set the `withDetails: true`
```C#
    var postsWithBlog = _postRepository.GetAll(withDetails: true);
```

**Comment by Muhammad-Fakhr-Elden** [comment]
Thank you so much brother.
