### ISSUE TITLE
Why the autoSave parameter of repository cannot work normally in the hub?

### ISSUE THREAD

**Issue by zhusoz** [abpframework/abp#17952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I called an repository method in a SignalR hub(derived from AbpHub), and modified an entity object in the repository,at the same time,I set the auto save to the true, but after this method ended, the data changes were not persisted to the database until I close the websocket connection.I try to use the attribute of UnitOfWork,but it doesn't even matter.So,how should I do make it work immediately?

### Reproduction Steps

using Dsfds.Datasets;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.SignalR;
using Microsoft.ML;
using Microsoft.ML.AutoML;
using Microsoft.ML.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using Volo.Abp.AspNetCore.SignalR;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Uow;

namespace Dsfds.Models;

public class ModelHub : AbpHub
{
    private readonly IUnitOfWorkManager _unitOfWorkManager;
    private readonly IRepository<Model, Guid> _modelRepository;
    private readonly IWebHostEnvironment _env;

    public ModelHub(IUnitOfWorkManager unitOfWorkManager, IRepository<Model, Guid> modelRepository, IWebHostEnvironment env)
    {
        _unitOfWorkManager = unitOfWorkManager;
        _modelRepository = modelRepository;
        _env = env;
    }

    public async Task FitModel(CreateModelDto input)
    {
        
        await Clients.Caller.SendAsync("FitModel", "已加入模型训练队列，请耐心等待。");

        // 拟合模型
        // Initialize MLContext
        MLContext ctx = new MLContext();

        // Define data path
        string dataPath = Path.Combine(_env.WebRootPath, "datasets", $"{input.DatasetId}.csv");

        // Infer column information
        ColumnInferenceResults columnInference =
            ctx.Auto().InferColumns(dataPath, labelColumnName: "label", groupColumns: false);
        columnInference.ColumnInformation.IgnoredColumnNames.Add("sample_id");

        // Create text loader
        TextLoader loader = ctx.Data.CreateTextLoader<MetaDataset>(columnInference.TextLoaderOptions);

        // Load data into IDataView
        IDataView data = loader.Load(dataPath);

        // 使用 TrainTestSplit 将数据集拆分为 80% 训练集和 20% 验证集。
        var trainData = ctx.Data.TrainTestSplit(data, testFraction: 0.2);

        // 定义管道
        SweepablePipeline pipeline = ctx.Auto()
            .Featurizer(data, columnInformation: columnInference.ColumnInformation)
            .Append(ctx.Auto().MultiClassification(labelColumnName: columnInference.ColumnInformation.LabelColumnName));

        // 定义AutoML配置
        MulticlassExperimentSettings mes = new MulticlassExperimentSettings
        {
            MaxExperimentTimeInSeconds = input.MaxExperimentTimeInSeconds,
            OptimizingMetric = MulticlassClassificationMetric.MicroAccuracy
        };

        // 配置试验
        MulticlassClassificationExperiment experiment = ctx.Auto().CreateMulticlassClassificationExperiment(mes);

        // Log experiment trials
        ctx.Log += (_, e) =>
        {
            if (e.Source.Equals("AutoMLExperiment"))
            {
                Console.WriteLine(e.RawMessage);
            }
        };

        // 训练时间到期后，结果为 TrialResult，表示在训练期间找到的最佳模型。
        ExperimentResult<MulticlassClassificationMetrics> experimentResults = experiment.Execute(trainData.TrainSet, trainData.TestSet, columnInformation: columnInference.ColumnInformation);
        Console.WriteLine("***************Trainer***************");
        Console.WriteLine($"{experimentResults.BestRun.TrainerName}");
        Console.WriteLine("***************Trainer***************");

        Console.WriteLine();

        Console.WriteLine("===============ValidationMetrics===============");
        Console.WriteLine($"MicroAccuracy:{experimentResults.BestRun.ValidationMetrics.MicroAccuracy}");
        Console.WriteLine($"MacroAccuracy:{experimentResults.BestRun.ValidationMetrics.MacroAccuracy}");
        Console.WriteLine($"LogLoss:{experimentResults.BestRun.ValidationMetrics.LogLoss}");
        Console.WriteLine($"LogLossReduction:{experimentResults.BestRun.ValidationMetrics.LogLossReduction}");
        Console.WriteLine("===============ValidationMetrics===============");
        Console.WriteLine();

        // 保存模型到数据库
        Model newModel = new Model()
        {
            Name = input.Name,
            DatasetId = input.DatasetId,
            MaxExperimentTimeInSeconds = input.MaxExperimentTimeInSeconds,
            TrainerName = experimentResults.BestRun.TrainerName,
            MicroAccuracy = experimentResults.BestRun.ValidationMetrics.MicroAccuracy,
            MacroAccuracy = experimentResults.BestRun.ValidationMetrics.MacroAccuracy,
            LogLoss = experimentResults.BestRun.ValidationMetrics.LogLoss,
            LogLossReduction = experimentResults.BestRun.ValidationMetrics.LogLossReduction
        };
        await _modelRepository.InsertAsync(newModel, autoSave: true);
        await _unitOfWorkManager.Current.SaveChangesAsync();

        // 保存模型文件
        string modelSaveDirectory = Path.Combine(_env.WebRootPath, "models");
        if (!Directory.Exists(modelSaveDirectory))
            Directory.CreateDirectory(modelSaveDirectory);
        string modelSavePath = Path.Combine(modelSaveDirectory, $"{newModel.Id}.zip");
        ctx.Model.Save(experimentResults.BestRun.Model, loader, modelSavePath);

        // 训练结果
        await Clients.Caller.SendAsync("FitModel", "模型训练完成。");
    }

}

### Expected behavior

the data changes were persisted to the database even though I didn't close the websocket connection.

### Actual behavior

 The data changes were not persisted to the database until I close the websocket connection.

### Version

7.4.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

You can try to begin a new uow via https://docs.abp.io/en/abp/latest/Unit-Of-Work#begin-a-new-unit-of-work

**Comment by zhusoz** [comment]
Thanks,it's helpful.
