### ISSUE TITLE
DbMigrator: module database per tenant migrations and seeding

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#17977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**abp v 7.4.0, tiered, MVC, Postgres** - abp Commercial

In DbMigrator project, I have defined connection strings in appsettings.json the following way:
```
"ConnectionStrings": {
  "Default": "Host=localhost;Port=5432;Database=AbpTestApp;User ID=postgres;Password=mypwd123;",
  "AbpAuditLogging": "Host=localhost;Port=5432;Database=AbpTestApp_AL;User ID=postgres;Password=mypwd123;"
}
```
When I run migrator, only "Default" database is created (with abp tables). Why database in connection string "AbpAuditLogging" is not created and seeded?

Then I create Tenant with Ten1 name with dedicated database on GUI (abp Commercial) and there is record in table SaasTenantConnectionStrings in **host database**. This adabase is created, migrated and seeded.
Then I manually add "AbpAuditLogging" for this TenantId for different database like so:
![image](https://github.com/abpframework/abp/assets/39346964/4eed4c12-c443-4e7d-811a-8632377f106d)
However, AbpTestApp_ten1_Logs is not created and also no error during migration proces (exit(0) inside DbMigrator console application).

I also found very similar question on StackOverflow: https://stackoverflow.com/questions/67616203/trying-to-create-the-database-using-abp-framework-while-db-migration

Even Cotur suggested this way: https://stackoverflow.com/questions/68066375/store-abp-autid-log-in-separate-database

@maliming and @hikalkan - how does this migration work? I would like to migrate and seed Default and module-specific connection strings per tenant which are defined in host database (inside table SaasTenantConnectionStrings).

Thank you for clarifications.

### Version

7.4.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#using-multiple-databases

**Comment by leonkosak** [comment]
Tnx, I'll try.
