### ISSUE TITLE
Make TenantAppService methods virtual

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1797]
So that we inherit the class and modify the behaviour. If you want i can do the PR

**Comment by maliming** [comment]
@hikalkan  Or should we make all application service methods `virtual`?

**Comment by hikalkan** [comment]
@maliming 
>should we make all application service methods virtual?

Yes! Not only app services, we should make everything virtual and easy to override. ABP should be hack-able framework (with good meaning). We trust in developers :)
I try to remember that while writing classes, however it is not fully implemented.

We can not make all virtual now, it gets long time to check everything. But we will accept PRs when needed.
