### ISSUE TITLE
Audit log entity changes for ValueObject - null value in column "EntityId" of relation "AbpEntityChanges" violates not-null constraint

### ISSUE THREAD

**Issue by s4lvo** [abpframework/abp#17975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm raising a concern with the Volo.Abp.Auditing module, as it currently fails to track changes to the properties of value objects. This issue stems from an error in inserting data into the EntityChanges table, which does not allow null values in the EntityId column.

[ERR] An error occurred while saving the entity changes. See the inner exception for details.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
---> Npgsql.PostgresException (0x80004005): 23502: null value in column "EntityId" of relation "AbpEntityChanges" violates not-null constraint

### Reproduction Steps

Please add the following check [here](https://github.com/abpframework/abp/blob/ab03a57f342743b28cd0661d2eaae571ab8421b6/framework/test/Volo.Abp.Auditing.Tests/Volo/Abp/Auditing/Auditing_Tests.cs#L421) on the update operation
`&& !x.EntityChanges[1].EntityId.IsNullOrEmpty()
`

### Expected behavior

Property changes to value object stored in auditlogs tables

### Actual behavior

You will have the following test result:

Volo.Abp.Auditing.Auditing_Tests.Should_Write_AuditLog_For_ValueObject_Entity
 Source: Auditing_Tests.cs line 366
 Duration: 9,8 sec
Message: 
NSubstitute.Exceptions.ReceivedCallsException : Expected to receive a call matching:
SaveAsync(x => ((((((((((x.EntityChanges.Count == 2) AndAlso (Convert(x.EntityChanges.get_Item(0).ChangeType, Int32) == 1)) AndAlso (x.EntityChanges.get_Item(0).EntityTypeFullName == Volo.Abp.Auditing.App.Entities.AppEntityWithValueObject.FullName)) AndAlso (Convert(x.EntityChanges.get_Item(1).ChangeType, Int32) == 1)) AndAlso (x.EntityChanges.get_Item(1).EntityTypeFullName == Volo.Abp.Auditing.App.Entities.AppEntityWithValueObjectAddress.FullName)) AndAlso (x.EntityChanges.get_Item(1).PropertyChanges.Count == 1)) AndAlso (x.EntityChanges.get_Item(1).PropertyChanges.get_Item(0).PropertyName == "Country")) AndAlso (x.EntityChanges.get_Item(1).PropertyChanges.get_Item(0).OriginalValue == ""England"")) AndAlso (x.EntityChanges.get_Item(1).PropertyChanges.get_Item(0).NewValue == ""Germany"")) AndAlso Not(x.EntityChanges.get_Item(1).EntityId.IsNullOrEmpty())))
Actually received no matching calls.
Received 2 non-matching calls (non-matching arguments indicated with '*' characters):
SaveAsync(*AUDIT LOG: [---: -------]
- UserName - UserId : -
- ClientIpAddress :
- ExecutionDuration : 332
- Entity Changes:
- [Created] Volo.Abp.Auditing.App.Entities.AppEntityWithValueObjectAddress, Id =
AppEntityWithValueObjectId: -> "08d140ca-5b9f-4f28-a797-b7d3b77b1522"
Country: -> "England"
- [Updated] Volo.Abp.Auditing.App.Entities.AppEntityWithValueObject, Id = 08d140ca-5b9f-4f28-a797-b7d3b77b1522
Name: "test name" -> "test name 2"
- [Deleted] Volo.Abp.Auditing.App.Entities.AppEntityWithValueObjectAddress, Id =
AppEntityWithValueObjectId: "08d140ca-5b9f-4f28-a797-b7d3b77b1522" ->
Country: "USA" ->
*)
SaveAsync(*AUDIT LOG: [---: -------]
- UserName - UserId : -
- ClientIpAddress :
- ExecutionDuration : 59
- Entity Changes:
- [Updated] Volo.Abp.Auditing.App.Entities.AppEntityWithValueObject, Id = 08d140ca-5b9f-4f28-a797-b7d3b77b1522
**- [Updated] Volo.Abp.Auditing.App.Entities.AppEntityWithValueObjectAddress, Id =**
Country: "England" -> "Germany"
*)
Stack Trace: 
ReceivedCallsExceptionThrower.Throw(ICallSpecification callSpecification, IEnumerable`1 matchingCalls, IEnumerable`1 nonMatchingCalls, Quantity requiredQuantity)
CheckReceivedCallsHandler.Handle(ICall call)
Route.Handle(ICall call)
CallRouter.Route(ICall call)
CastleForwardingInterceptor.Intercept(IInvocation invocation)
AbstractInvocation.Proceed()
ProxyIdInterceptor.Intercept(IInvocation invocation)
AbstractInvocation.Proceed()
ObjectProxy.SaveAsync(AuditLogInfo auditInfo)
Auditing_Tests.Should_Write_AuditLog_For_ValueObject_Entity() line 412
--- End of stack trace from previous location ---

### Version

7.4

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by s4lvo** [comment]
Hi @maliming,

When we use a Value Object, we typically have an immutable value in mind that is used with an aggregate root. This implies that the properties of a value object are owned by the parent entity.

In our example, the AppEntityWithValueObject serves as the aggregate, while the AppEntityWithValueObjectAddress functions as the value object. What I expect is that when I change the property Country, the audit log module will track the property change with the EntityId of the aggregate root, which is AppEntityWithValueObject.

What are your thoughts on this?

Instead of changing the "nullable" of EntityId, I made adjustments to EntityHistoryHelper to achieve this objective:

`protected override List<EntityPropertyChangeInfo> GetPropertyChanges(EntityEntry entityEntry)
    {
        List<EntityPropertyChangeInfo> propertyChanges = base.GetPropertyChanges(entityEntry);

        foreach (ReferenceEntry reference in entityEntry.References)
        {
            if (reference.TargetEntry == null)
            {
                continue;
            }

            List<EntityPropertyChangeInfo> referencePropertyChanges = GetPropertyChanges(reference.TargetEntry);

            foreach (EntityPropertyChangeInfo referencePropertyChange in referencePropertyChanges)
            {
                referencePropertyChange.PropertyName = $"{reference.Metadata.Name}.{referencePropertyChange.PropertyName}";
            }

            propertyChanges.AddRange(referencePropertyChanges);
        }

        return propertyChanges;
    }`

**Comment by maliming** [comment]
hi @s4lvo 

I will make EntityId nullable in the database.
