### ISSUE TITLE
Default Auto-Increment Enum Index Is Overwritten

### ISSUE THREAD

**Issue by j0nimost** [abpframework/abp#17986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have noticed while importing Enums the auto-increment indexes are not applied; 

### Reproduction Steps

 Create an Enum file for example :
```c#
public enum AccountUsage
{
    Detail=1,
    Header
}
```
Import the Enum file to an Entity property using Abp Suite.

### Expected behavior

I expect the index of the Header enum value to auto-increment thus the Index value should be `2`

### Actual behavior

`Header` enum value is set to 0 on the Abp Suite enum import interface.
<img width="344" alt="image" src="https://github.com/abpframework/abp/assets/24381727/9b8dd1ad-647b-4bda-8378-c585cabb65d4">

### Known Workarounds

Assigning an index value to each enum value does maintain consistency.

### Version

7.4

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

The challenge is the consistency from what I expect in C# and UI

**Comment by maliming** [comment]
hi

Please create a support ticket on https://support.abp.io/

Thanks.
