### ISSUE TITLE
Upgrade SixLabors.ImageSharp the latest

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#17989]
https://support.abp.io/QA/Questions/6048/Issue-after-updating-to-740-and-my-custom-LoginModel-throwing-DI-issue

**Comment by TronActive** [comment]
This will be a big help

**Comment by huyqta** [comment]
Is this fixing on latest version? I've just upgraded to 7.4.0 today and still met SixLabors.ImageSharp error.
