### ISSUE TITLE
[mvc]model.open support array parameter

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#17988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

``` js
var myModal = new abp.ModalManager({
    //...options
});
myModal.open({ ids: [1,2,3,4] })
```
server could not get the parameter. because $.param() second parameter needs to be true
please add options

abp version:7.3.1

### Describe the solution you'd like

``` js
myModal.open({ ids: [1,2,3,4] }, true)
```

**Comment by maliming** [comment]
You can override the `ModalManager` script. We will not change this behavior.
