### ISSUE TITLE
EF Core 3.0 Cascade Delete Timing

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1798]
We should modify CascadeDeleteTiming to implement soft deletion.

```
ChangeTracker.CascadeDeleteTiming = CascadeTiming.OnSaveChanges;
```

see: 
https://github.com/aspnet/EntityFrameworkCore/issues/12833
https://github.com/aspnet/EntityFrameworkCore/issues/10114
https://github.com/aspnet/EntityFrameworkCore/pull/14470

**Comment by maliming** [comment]
Ef core 3.0 no longer has this problem.

**Comment by ranouf** [comment]
Hi, Could you give a link to get the documentation of this new Feature?

**Comment by maliming** [comment]
hi @ranouf  
Only this https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#cascade-deletions-now-happen-immediately-by-default
