### ISSUE TITLE
Volo.Abp.AspNetCore.Mvc 0.21.0 is not compatible with netstandard 2.1

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#1799]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1202	包 Volo.Abp.AspNetCore.Mvc 0.21.0 与 netstandard2.1 (.NETStandard,Version=v2.1) 不兼容。 包 Volo.Abp.AspNetCore.Mvc 0.21.0 支持: netcoreapp3.0 (.NETCoreApp,Version=v3.0)	.HttpApi	.HttpApi.csproj	1

**Comment by maliming** [comment]
Please describe the problem in detail and the steps to reproduce the problem

**Comment by xewn** [comment]
我就用中文吧。要不说不清楚
这个是原来自动创建的项目，HttpApi.csproj工程是没有做过任何改动的。今天尝试更新到0.21版本的时候。
发现有这个错误。我看了一下book工程，里面是没有直接依赖Volo.Abp.AspNetCore.Mvc 0.21.0的，但是原来的HttpApi工程是依赖了的。就造成这个错误。

**Comment by xewn** [comment]
知道是什么问题了，以前的HttpApi工程是标准库2.1。这次更新后的HttpApi编程了.net core3.0的库了。
