### ISSUE TITLE
The Json formatting configuration in the extension field ExtraPropertiesValueConverter will result in the inability to encode Chinese characters

### ISSUE THREAD

**Issue by l2999019** [abpframework/abp#17996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The DeserializeOptions in the ExtraPropertiesValueConverter did not set the character set during initialization, which can cause Chinese to not be stored properly in the database
this code:
```
private static readonly JsonSerializerOptions DeserializeOptions = new JsonSerializerOptions()
    {
        Converters =
        {
            new ObjectToInferredTypesConverter()
        }
    };
```
I can only solve this problem by forcing default values, such as:
````
((JsonSerializerOptions)typeof(JsonSerializerOptions)
.GetField("s_defaultOptions", System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic).GetValue(null))
.Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping;
```

### Describe the solution you'd like

Suggest changing to the following code
```
private static readonly JsonSerializerOptions DeserializeOptions = new JsonSerializerOptions()
    {
        Converters =
        {
            new ObjectToInferredTypesConverter()
        }
        ,Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };
```
### Additional context

_No response_

**Comment by maliming** [comment]
hi

You can override the code of `ExtraPropertiesValueConverter`.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs#L56-L69

**Comment by l2999019** [comment]
override ExtraPropertiesValueConverter
But 'TryConfigureExtraProperties' is a direct new  'ExtraPropertiesValueConverter'
 I need to rewrite a new TryConfigureExtraProperties method and initialize it in bulk?

**Comment by maliming** [comment]
Something like this

```cs
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);

    foreach (var entityType in builder.Model.GetEntityTypes())
    {
        var b = builder.Entity(entityType.ClrType);
        if (!b.Metadata.ClrType.IsAssignableTo<IHasExtraProperties>())
        {
            continue;
        }

        b.Property<ExtraPropertyDictionary>(nameof(IHasExtraProperties.ExtraProperties))
            .HasColumnName(nameof(IHasExtraProperties.ExtraProperties))
            .HasConversion(new YourExtraPropertiesValueConverter(b.Metadata.ClrType))
            .Metadata.SetValueComparer(new YourExtraPropertyDictionaryValueComparer());

        b.TryConfigureObjectExtensions();
    }

}
```

**Comment by l2999019** [comment]
The EF context that comes with ABP is like IdentityDbContext,  I can only inherit and override OnModelCreating? For existing projects The impact is a bit significant

**Comment by maliming** [comment]
You can override the `OnModelCreating ` method of your `DbContext` now.

I will improve it in next version(8.0)

**Comment by l2999019** [comment]
Looking forward to the improvement of 8.0. Thank you

**Comment by JadynWong** [comment]
The public `JsonSerializerOptions` in PR are only used when deserializing. Serialization does not pass JsonSerializerOptions, it still uses unicode characters for non-English characters.

**Comment by maliming** [comment]
Yes, We can add another `JsonSerializerOptions` for `Serialize`
