### ISSUE TITLE
Text Replacement Not Working [Angular]

### ISSUE THREAD

**Issue by cloud0259** [abpframework/abp#18000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, 

I'm trying to replace a validation text but nothing happens.
 I've followed the documentation here: https://docs.abp.io/en/abp/latest/UI/Angular/Form-Validation

I would like to point out that I am working on a module project.

### Reproduction Steps

```ts
import { VALIDATION_BLUEPRINTS } from "@ngx-validate/core";
import { DEFAULT_VALIDATION_BLUEPRINTS } from "@abp/ng.theme.shared";

@NgModule({
  imports: [
    ThemeSharedModule.forRoot({
      validation: {
        blueprints: {
          required: "::RequiredInput",
        },
      },
      // rest of theme shared config
    }),

    // other imports
  ],

  // rest of the module metadata
})
export class AppModule {}
```

### Expected behavior

![image](https://github.com/abpframework/abp/assets/6765644/75db5176-2d05-4761-b7d3-120866e1281d)

### Actual behavior

Nothing happens

### Version

7.4

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi,

You can try this:

```
@NgModule({
  providers: [
    {
      provide: VALIDATION_BLUEPRINTS,
      useValue: {
        ...DEFAULT_VALIDATION_BLUEPRINTS,
        required: "::RequiredInput",
      },
    },

    // other providers
  ],

  // rest of the module metadata
})
export class AppModule {}
JavaScript

```

**Comment by realLiangshiwei** [comment]
It works for me.

<img width="1612" alt="image" src="https://github.com/abpframework/abp/assets/16813853/f4a63888-74d3-4429-aebb-d69b9af70bd7">

Can you share your app.module.ts code?

**Comment by Sinan997** [comment]
I am closing the issue. If the error still persists, you can open a new issue.
