### ISSUE TITLE
Client java script proxies point to web application instead of API Host

### ISSUE THREAD

**Issue by manasheed** [abpframework/abp#18008]
Hi,
I created book store application using Getting started tutorial. 
API's are working fine. 
I created book store MVC/Razor Tiered application using Getting Started tutorial using command
abp new Acme.BookStore --tiered
API's are working fine.
![Swagger](https://github.com/abpframework/abp/assets/17447195/51d737fe-38bd-42ad-9ad5-975b60cfeca1)

In Web application neither dynamic javascript proxies not working at all.

1. Created static proxies in web project folder. Proxies are created successfully. 
2. Added reference of the proxy script in index.cshtml
3. Disabled dynamic proxies in ConfigureServices method BookStoreWebModule.cs in web project
        Configure<DynamicJavaScriptProxyOptions>(options =>
        {
            options.DisableModule("app");
        });
4. Now running AuthServer, Api Host and Web projects
5. Now running command in Web application console window 
acme.bookStore.books.book.getList({}).done(function (result) { console.log(result); });
7. shows error "Resource not found". Also the API call points to web application url instead of API Host.
![WebConsole](https://github.com/abpframework/abp/assets/17447195/82dc30d2-716d-4bf5-876a-686c177111c4)

8.

**Comment by maliming** [comment]
> Created static proxies in web project folder. Proxies are created successfully.

What's your command args?

**Comment by manasheed** [comment]
> > Created static proxies in web project folder. Proxies are created successfully.
> 
> What's your command args?

Thanks for your prompt response :)

abp generate-proxy -t js -url https://localhost:44357/

This is the url to api host.

**Comment by manasheed** [comment]
> > > Created static proxies in web project folder. Proxies are created successfully.
> > 
> > 
> > What's your command args?
> 
> Thanks for your prompt response :)
> 
> abp generate-proxy -t js -url https://localhost:44357/
> 
> This is the url to api host.

Please help @maliming .

**Comment by maliming** [comment]
hi

You can try to depend on `AbpHttpClientWebModule(Volo.Abp.Http.Client.Web)` in your web project.

If still not working, please upload your template project on GitHub.

**Comment by manasheed** [comment]
> AbpHttpClientWebModule(Volo.Abp.Http.Client.Web)

Hi @maliming 
Thanks for response. The web application already depending on AbpHttpClientWebModule(Volo.Abp.Http.Client.Web). The issue is still there. Please get below github link for the repository.

https://github.com/manasheed/Acme.BookStore.git

Ashhar

**Comment by maliming** [comment]
This repo is private.

https://github.com/manasheed/Acme.BookStore

**Comment by manasheed** [comment]
> This repo is private.
> 
> https://github.com/manasheed/Acme.BookStore

Hi @maliming 
 Sorry I thought default public. I have set it public now. Please check.

**Comment by manasheed** [comment]
> > https://github.com/manasheed/Acme.BookStore
> 
> Hi @maliming Sorry I thought default public. I have set it public now. Please check.

Hi @maliming ,
I have recommended this framework in my company, but I myself is stuck here.
Ashhar

**Comment by maliming** [comment]
https://github.com/manasheed/Acme.BookStore/pull/1

**Comment by manasheed** [comment]
Thanks. It is working with custom controller.
