### ISSUE TITLE
Repository interface with 'Customizable code' checked is implemented by base repository instead of extended repository

### ISSUE THREAD

**Issue by AdriRed** [abpframework/abp#18025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you're generating all the code for one entity and have checked the new option of 'Customizable code', it generates for you all the base services/managers/entities/dtos and the extended ones correctly, except for the repository.

When you want to add a custom method in the repository you should add it to the extended interface, and then implment it in the extended repository, but the base repository has to implement the interface, therefore the build fails.

### Reproduction Steps

1. Create project in abp suite 7.4.0
2. Create an entity and generate the code `Foo`
3. Add a custom method definition in the `IFooRepository.Extended.cs`
4. The method must be implemented at the level of the `FooRepository.cs` instead of `FooRepository.Extended.cs`.
5. The next regeneration of code with the abp suite will erase the implementation of the method and will make the build fail.

### Expected behavior

The implementation of the interface should be at the level of the `FooRepository.Extended.cs`. The same behaviour of the AppServices.

### Actual behavior

The implementation of the interface is at the level of the base repository instead of the extended one.

### Regression?

No, because the 'Customizable code' option wasn't available.

### Known Workarounds

Nope

### Version

7.4.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
Please create a question on the [support.abp.io website](https://support.abp.io/QA/Questions). We are not giving commercial support here. Thanks for your understanding.

Regards.
