### ISSUE TITLE
Send SignalR message from server to client using userId not connectionId with angular UI

### ISSUE THREAD

**Issue by wael-razouk** [abpframework/abp#18022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cannot notify signalr clients from server when trying to notify  single use by their id i.e: `Clients.User(userId).SendAsync` when the frontend is angular

### Reproduction Steps

1- create new project using abp cli (choose angular as UI)
2- copy the code related to signalr hub from the sample project [SignalrDemo](https://github.com/abpframework/abp-samples/tree/master/SignalRDemo)
3- notifications don't reach clients in the frontend (i.e: events registered using `connection.on` are not triggered)
I think it's something related to authentication flow (it differs between web and angular). Some people on the internet say that signalr uses `NameIdentifier` Claim to get the user

### Expected behavior

notification reach to user in fronend

### Actual behavior

Notification doesn't reach user

### Version

7.2.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Can you upload a test project? thanks

**Comment by wael-razouk** [comment]
@realLiangshiwei  sure, here is a zipped project. in the home component there is a button to trigger hub method to send a message to the admin user. A subscription to the message is done in the home component also to log the received message to the console
[TestSignalR](https://drive.google.com/file/d/1-Qy39smvMWUwomvg6_I0ur1qki547XtW/view?usp=sharing)

**Comment by realLiangshiwei** [comment]
You should pass the access token from the Angular app

<img width="1146" alt="image" src="https://github.com/abpframework/abp/assets/16813853/45109a29-e5f9-42c7-bac5-d29808a22b21">

<img width="847" alt="image" src="https://github.com/abpframework/abp/assets/16813853/d959d356-7d99-40c1-ac99-a2ac96f1e53f">

**Comment by wael-razouk** [comment]
@realLiangshiwei  Thanks, it worked. But when I try to include the login page inside the angular app and not redirect the user to backend host (using angular ui account module [described here](https://docs.abp.io/en/abp/latest/UI/Angular/Authorization#resource-owner-password-flow), it stops working. Any suggestions?


### Update

The issue was with my abp packages version (it was 7.1.1) once I updated it to 7.2 it started working.
Thanks.

### Update 2
The issue was not with version, rather than `IdentityServer`. Our project is old and it was on version 4.4 (with `IdentityServer` for authoriation. authentication, ...). We upgraded recently to v7 but didn't do the migrate for `OpenIdDict`. It was resolved when we did the migrate.

**Comment by wael-razouk** [comment]
@realLiangshiwei  Hello, any suggestions here?
