### ISSUE TITLE
appsettings.json: tenantname template for subdomain

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#18029]
As far as I know, ASP.NET Boilerplate (and ASP.NET Zero) has option to define tenant subdomain in appsettings.json file.
I looked at docs for abp framework: https://docs.abp.io/en/abp/latest/Multi-Tenancy#determining-the-current-tenant
Why is there no option to define tenant subdomain placeholder in appsettings.json in abp framework (without additional/changed code in middleware)?

**Comment by realLiangshiwei** [comment]
> As far as I know, ASP.NET Boilerplate (and ASP.NET Zero) has option to define tenant subdomain in appsettings.json file.

Can you share some links?

**Comment by leonkosak** [comment]
Hi @realLiangshiwei,
https://support.aspnetzero.com/QA/Questions/8835/AppBaseUrl---Tenancy-name-as-subdomain-for-a-multi-tenant-application#answer-8f6dd7be-c43f-2a72-fc2c-39f48dc39e70

So, something like https://{TENANCY_NAME}.domain.com

**Comment by realLiangshiwei** [comment]
Hi,

Do you mean this?
https://docs.abp.io/en/abp/latest/UI/Angular/Multi-Tenancy#domain-subdomain-tenant-resolver

And we have an example:

https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver

**Comment by leonkosak** [comment]
https://github.com/abpframework/abp-samples/blob/master/DomainTenantResolver/MVC-TIERED/src/Acme.BookStore.HttpApi.Host/BookStoreHttpApiHostModule.cs#L55

Well, this is hardcoded in middleware. What if I want multiple installations of application on different domains?

abp Documentation for subdomain resolver is just for Angular, right?

**Comment by realLiangshiwei** [comment]
Sorry, I couldn't understand, Even in aspnetboilerplate, it is such a configuration that there must be middleware to resolve the current tenant: https://aspnetboilerplate.com/Pages/Documents/Multi-Tenancy#determining-current-tenant

I guess you want to resolve multiple domain names to the same application.

```json
{
    "app": {
         "DomainUrls": "{0}.mydomain.com;{0}.mywebsite.com"
    }
}
```

```csharp
var configuration = context.Services.GetConfiguration();

var urls = configuration["app:DomainUrls"];

Configure<AbpTenantResolveOptions>(options =>
{
    foreach(var url in urls.Split(";"))
    {
           options.AddDomainTenantResolver(url);
    }
});
```
