### ISSUE TITLE
Non-ASCII characters in tenant admin email address domains don't work

### ISSUE THREAD

**Issue by joosep-devication** [abpframework/abp#18024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating a new tenant under the super-admin account, specifying a non-ASCII character in the domain of the admin email address (ex. admin@ä.com) creates an account with a completely different email address. The issue does not occur when creating new users, only when creating tenants. Special characters also work as expected before the '@' in the email, only breaking in the domain part.

### Reproduction Steps

1. Create new ABP project.
2. Create a new tenant as super-admin.
3. Enter non-ASCII character into the DOMAIN of the admin email address (ex. admin@ü.com)

### Expected behavior

A user with the email "admin@ü.com" is created.

### Actual behavior

A user with the email "admin@xn--tda.com" is created.

### Regression?

Issue persists in version 7.1.0-rc2.

### Version

7.4.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

What is the `DistributedEventBus` you are using?

**Comment by joosep-devication** [comment]
Default

**Comment by maliming** [comment]
hi

This is a browser/chrome issue.

https://bugs.chromium.org/p/chromium/issues/detail?id=410937

**Comment by joosep-devication** [comment]
Thanks. I had checked with Edge as well, but forgot that was also Chromium based.
