### ISSUE TITLE
start Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.Demo ，Error: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery

### ISSUE THREAD

**Issue by 137464023** [abpframework/abp#1802]
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery
Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List<string> assemblies)

**Comment by yekalkan** [comment]
see this commit: https://github.com/abpframework/abp/commit/132de6d99d719f2518b174c6e38bb3c88cb7736c

**Comment by 137464023** [comment]
i go to try, thanks

**Comment by 137464023** [comment]
why do you add " <PreserveCompilationReferences>true</PreserveCompilationReferences>"?
do you need this for later projects

**Comment by hikalkan** [comment]
see https://github.com/aspnet/AspNetCore/issues/8416#issuecomment-471736911
