### ISSUE TITLE
Change password is throwing error

### ISSUE THREAD

**Issue by vipulbuoyancy** [abpframework/abp#18026]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Change password from My Account menu is throwing an error after updating password.

### Reproduction Steps

Login > Click on Profile (right top corner) > Click on My Account menu > Click on Change Password Tab

![image](https://github.com/abpframework/abp/assets/80636669/f5cd4f3c-658f-48e2-954b-849593925359)

I get the error below error

![image](https://github.com/abpframework/abp/assets/80636669/d94f918f-319e-4214-9446-1e1ca85ccab6)

### Expected behavior

It should show success message instead of error message

### Actual behavior

It is showing an error message

### Version

7.4.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by HDaoud** [comment]
Hello team! Any update on this issue?

**Comment by vipulbuoyancy** [comment]
Hi @mahmut-gundogdu, I know you have fixed this issue few days back.  Can you please let us know the version in which this issue has been fixed?

Thank you.

**Comment by Sinan997** [comment]
This issue has fixed at 7.4.2 version.
