### ISSUE TITLE
Configure abp asp.net to deploy to with customize base path

### ISSUE THREAD

**Issue by anhlee97** [abpframework/abp#18033]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

I am trying to configure asp.net core application to use Lepton X lite theme to deploy on k8s infrastructure with https://localhost:5000/admin/ instead of https://localhost:5000/.

i try UseBasePath. i work for endpoint but some resource in Theme not work correct .

**Comment by anhlee97** [comment]
Please help !

**Comment by anhlee97** [comment]
@maliming  please help

**Comment by maliming** [comment]
> but some resource in Theme not work correct .

Please share the error info.

**Comment by anhlee97** [comment]
i try use Base Path :[image: image.png]

but some resource in Lepton Theme css, js is not in base path
[image: image.png]

**Comment by anhlee97** [comment]
@maliming.
My goal is deploy my app to nginx proxy subpath.
 i try
 use Base Path![image](https://github.com/abpframework/abp/assets/135435270/5375a3a1-f7c3-47ec-ba8e-70358d4d2685)

but some resource in Lepton Theme css, js is not in base path
![image](https://github.com/abpframework/abp/assets/135435270/fb542d53-7591-44af-9238-50adead8174b)

**Comment by anhlee97** [comment]
![image](https://github.com/abpframework/abp/assets/135435270/56d4490e-7d80-49d2-8b54-2c8032f63a8b)

**Comment by maliming** [comment]
Can you try to move the `UsePathBase` before the `UseStaticFiles `

**Comment by anhlee97** [comment]
i tried by still error 
![image](https://github.com/abpframework/abp/assets/135435270/5d46badd-dbc9-4f26-b915-c9892bf3d79d)

**Comment by maliming** [comment]
Please share a simple project on GitHub.

**Comment by anhlee97** [comment]
you can view here: https://github.com/anhlee97/AbpNginx.git

**Comment by anhlee97** [comment]
![image](https://github.com/abpframework/abp/assets/135435270/f774896c-b325-4d5a-82b0-2bbc6896fc18)
@maliming

**Comment by maliming** [comment]
It works on my local.

```cs
  var rootPath = "/customer/admin";
  app.UsePathBase(new PathString(rootPath));
  app.UseStaticFiles();
```

<img width="1444" alt="image" src="https://github.com/abpframework/abp/assets/6908465/e7e67b7e-f191-43fa-8ead-873cee82cdec">

**Comment by anhlee97** [comment]
Thanks @maliming. It's work. but i have another problem when login.
![image](https://github.com/abpframework/abp/assets/135435270/ef644139-53a6-45dd-96c4-0cd4d4fa2f4d)

it return /customer/admin but don't have cookie 
![image](https://github.com/abpframework/abp/assets/135435270/8d640c98-9a75-4d48-b1c1-1b3a4edd50b9)

**Comment by maliming** [comment]
Please check your logs and browser console to see the cookies.

**Comment by anhlee97** [comment]
![image](https://github.com/abpframework/abp/assets/135435270/a9481c30-1b99-480d-9ca8-bfb1bf22f1d8)
this is my log. and my cookie 
![image](https://github.com/abpframework/abp/assets/135435270/6ef0ee4d-ef0f-4104-b1f0-bf2c5a2ed519)

**Comment by anhlee97** [comment]
i try set: RootUrl. it work for login but when i access identity management module it say You are not authenticated!
You should sign in to perform this operation.
![image](https://github.com/abpframework/abp/assets/135435270/7f5e08bd-4012-4b7c-a533-f13487f75187)

**Comment by anhlee97** [comment]
![image](https://github.com/abpframework/abp/assets/135435270/ca7c6402-38b8-4bb8-b0d1-02b5260e1f87)

**Comment by anhlee97** [comment]
@maliming please help !!!

**Comment by maliming** [comment]
Please check your app logs.

**Comment by anhlee97** [comment]
HI @maliming , I resolved this problem but i have another.
![image](https://github.com/abpframework/abp/assets/135435270/07486668-1862-40e4-a774-a29cbcc2cb4f)
 i try create subfolder. 
![image](https://github.com/abpframework/abp/assets/135435270/d678993e-cc92-4a0d-af71-fb8af1be7fa5)
but it not working

**Comment by maliming** [comment]
hi

Can you run the `abp install-libs` command to create the js libs?

**Comment by anhlee97** [comment]
Yeah. Thank you ! This is my stupid. I forgot when ci/cd.
@maliming 
So help me another issue.

In my case: i want use app.UsePathBase(new PathString(AdminConst.RootPath)); 
abp.js : not change appPath . 
var abp = abp || {};
(function () {
    /* Application paths *****************************************/
    //Current application root path (including virtual directory if exists).
    abp.appPath = abp.appPath || '/';
}
![image](https://github.com/abpframework/abp/assets/135435270/e74be847-5942-4cbf-a608-e9576e1a3a73)
