### ISSUE TITLE
Remove Permissions and other user-related data when deleting a user

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#18042]
Based on the problem https://github.com/abpframework/abp/issues/17927

When a user is deleted (in the Identity module), we can publish a distributed event, so other modules can know that and take the necessary actions.

Actually, an auto event for `UserEto` is already published automatically by the ABP framework. But that is not enabled by default. We can enable it by default in the Identity module, like that:

````csharp
Configure<AbpDistributedEntityEventOptions>(options =>
{
	options.AutoEventSelectors.Add<IdentityUser>();
});
````

Once we enabled it, we can subscribe to `IDistributedEventHandler<EntityDeletedEto<UserEto>>` in the following modules and make the necessary changes:

* Permission management module deletes the permissions related to that user.
* Setting management module deletes the permissions related to that user.
* Identity management module deleted user delegations, user claims, linked users and role-assignments for that user (it actually doesn't need to do with events since it is in the same module - maybe it can listen the local event to be transactional by default)

**Comment by maliming** [comment]
Can we add a `Volo.Abp.SettingManagement.Domain.Identity` module to clear the settings of a user?

https://github.com/abpframework/abp/blob/bcf65ab18d4b0a26b922dbad28ebaf24f5da53ba/modules/identity/src/Volo.Abp.PermissionManagement.Domain.Identity/Volo/Abp/PermissionManagement/Identity/UserDeletedEventHandler.cs#L23

**Comment by hikalkan** [comment]
No, don't add such a package. Also, add the event handler to Setting Management module's application layer, so only the application/service that manages the settings will handle the event (If we add the handler to domain package, all microservices will handle the event since that package is added to all of them - I know the same is true for the permission side, but we don't want to change it now).
