### ISSUE TITLE
I found that .NET Core 3.0 works with Swashbuckle.AspNetCore -Version 5.0.0-rc2

### ISSUE THREAD

**Issue by brittos** [abpframework/abp#1805]
I found that .NET Core 3.0 does not work with Swashbuckle.AspNetCore -Version 5.0.0-rc3, but with Swashbuckle.AspNetCore -Version 5.0.0-rc2. I recommend you try rc2.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/1849

Thanks for informing.
