### ISSUE TITLE
Remove CurrentDirectoryHelpers.cs when upgrade to ASP.NET Core 3.0.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1807]
https://github.com/aspnet/AspNetCore/blob/3ce6c1dc5b022116ec9b13f9158e092323ac1158/src/Servers/IIS/IIS/src/WebHostBuilderIISExtensions.cs#L36

**Comment by hikalkan** [comment]
@maliming can we implement this now?

**Comment by maliming** [comment]
Yes, I will implement it as soon as possible.
