### ISSUE TITLE
Abp-Password might be change with a common directive

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#18077]
the code 

https://github.com/abpframework/abp/blob/rel-7.4/npm/ng-packs/packages/theme-shared/src/lib/components/password/password.component.ts

If we implement the functionalty with directive

- [ ] Replace the component with directive   in ABP and ABP Commercial, Lepton X
- [ ] Mark deprecated exists component (and remove in the future)

**Comment by ebicoglu** [comment]
@Sinan997 close it if it's done
