### ISSUE TITLE
Test it with ng-packs and   copy-to-templates at app on templates.

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#18081]
We changed base packages. So ABP functionalty might be broken.  We should test manually.
- Run ng-packs check every exists functionalty. It must be work without any issue.
- Test Extensible System. https://docs.abp.io/en/abp/latest/UI/Angular/Extensions-Overall
  - Test Extensible-Table with extra property
  - Test Grid Action
  - Test Toolbar
  - Test Form. (it should update and create with extended property)

**Comment by Sinan997** [comment]
I have tested at both dev-app and templates app, extension system is works without an issue
