### ISSUE TITLE
In IEfCoreBulkOperationProvider to changed CreatorId or CreationTime or More Entity

### ISSUE THREAD

**Issue by zyknow** [abpframework/abp#18094]
i use EFCore.BulkExtensions to Implement InsertManyAsync,
how can i to set  `CreationTime` and `CreatorId` in IEfCoreBulkOperationProvider

**Comment by realLiangshiwei** [comment]
The `EFCore.BulkExtensions` Bulk CRUD Ops are without tracking, you can inject the `IAuditPropertySetter` service manually to set value.

```csharp
private readonly IAuditPropertySetter _auditPropertySetter;

public async Task InsertManyAsync...(... IEnumerable<TEntity> entities)
{
     foreach(var entity in entities)
     {
          _auditPropertySetter.SetCreationProperties(entity);
     }

     ......
}
```

**Comment by zyknow** [comment]
Thanks, it worked.
