### ISSUE TITLE
Angular: Unexpected dot symbol in account manage page

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#18096]
https://github.com/abpframework/abp/blob/rel-7.4/npm/ng-packs/packages/account/src/lib/components/manage-profile/manage-profile.component.html#L2

<img width="1549" alt="image" src="https://github.com/abpframework/abp/assets/16813853/8d0f5a3a-484c-414b-8197-5b47147512b3">

**Comment by ebicoglu** [comment]
![image](https://github.com/abpframework/abp/assets/9526587/593ca532-43de-474c-a520-6efb1b9c54a2)
