### ISSUE TITLE
[Question] ToList & Count give me different count

### ISSUE THREAD

**Issue by alihdev** [abpframework/abp#18091]
Hi,
In the GetListAsync method, I've noticed that the total count != list.count

```c#

public override async Task<PagedResultDto<BatchDto>> GetListAsync(BatchGetListInput input)
    {
        await CheckGetListPolicyAsync();

        var query = await CreateFilteredQueryAsync(input);

        var data = query.ToList(); // give me 10
        var totalCount = await AsyncExecuter.CountAsync(query); // give me 11
..
```

why & how can we resolve that ?

**Comment by realLiangshiwei** [comment]
**Reproduction Steps**

Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).

**Comment by alihdev** [comment]
For more details please check :
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1728#issuecomment-271752867

Is there any update for it?

**Comment by realLiangshiwei** [comment]
If you are talking about: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1728#issuecomment-271752867

I think this explanation is pretty clear: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1728#issuecomment-271834463

**Comment by alihdev** [comment]
Yes, it's clear but what
