### ISSUE TITLE
InsertAsync is different from expected

### ISSUE THREAD

**Issue by bingzhizhi** [abpframework/abp#18093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The data isnt saved when i use _currentUnitOfWork.SaveChangesAsync()
i  inserted the data before saving,
and then i getlist ,the list is enpty
![图片](https://github.com/abpframework/abp/assets/54054078/183cd846-504f-49a5-8324-a26d7fe369ea)

### Reproduction Steps

this is my code
await _chatMessageRepository.InsertAsync(chatMessage);
                await _currentUnitOfWork.SaveChangesAsync();
                var messages = await _chatMessageRepository.GetListAsync();

this is my injection
        private readonly IUnitOfWork _currentUnitOfWork;
public ChatHub(
            IDataFilter dataFilter,
            IUnitOfWork currentUnitOfWork
            IRepository<ChatRecord, Guid> chatRecordRepository,
            IRepository<ChatMessage, Guid> chatMessageRepository)
        {
            _dataFilter = dataFilter;
            _currentUnitOfWork = currentUnitOfWork;
            _chatRecordRepository = chatRecordRepository;
            _chatMessageRepository = chatMessageRepository;
        }

### Expected behavior

list.count = 1  or  if my insert data is error It will throw an exception but not

### Actual behavior

list.count = 0

### Version

4.3.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by bingzhizhi** [comment]
chatmessage.isdeleted is false
![图片](https://github.com/abpframework/abp/assets/54054078/d55f1ef9-874f-43fd-90be-5a56d670a706)

**Comment by bingzhizhi** [comment]
I select the table when this task finished ,the table ChatMessages is empty
![图片](https://github.com/abpframework/abp/assets/54054078/2d871555-8b29-4bf0-8195-213fbd00f978)

**Comment by bingzhizhi** [comment]
when i use await _chatMessageRepository.InsertAsync(message, true);
it works 
but why? _currentUnitOfWork doesnt work

**Comment by realLiangshiwei** [comment]
You should use the `IUnitOfWorkManager` instead of `IUnitOfWork `
