### ISSUE TITLE
AbpComponentBase HandleErrorAsync shows twice dialog message

### ISSUE THREAD

**Issue by happtim** [abpframework/abp#18104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am using Blazor WebAssembly.I try to catch some exception logs. In the catch, I use the await HandleErrorAsync(ex) method. But it shows the information twice.

``` csharp
private async void TestException()
{
    try
    {
        throw new UserFriendlyException("A user friendly error message!");
    }
    catch  (Exception ex)
    {
        await HandleErrorAsync(ex);
    }
}
```

HandleErrorAsync has two functions, one logs the exception using Logger.LogException(exception); and the other is InformAsync.

``` csharp
    protected virtual async Task HandleErrorAsync(Exception exception)
    {
        Logger.LogException(exception);
        await InvokeAsync(async () =>
        {
            await UserExceptionInformer.InformAsync(new UserExceptionInformerContext(exception));
            StateHasChanged();
        });
    }
```

For WebAssembly programs, there is a custom LoggerProvider to handle uncaught exceptions.

``` csharp
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddHttpClient();
        context.Services
            .GetHostBuilder().Logging
            .AddProvider(new AbpExceptionHandlingLoggerProvider(context.Services));
    }
```
The Logger provided by AbpExceptionHandlingLoggerProvider will also call _userExceptionInformer.Inform.

``` csharp
    public virtual void Log<TState>(
        LogLevel logLevel,
        EventId eventId,
        TState state,
        Exception exception,
        Func<TState, Exception, string> formatter)
    {
        if (exception == null)
        {
            return;
        }

        if (logLevel != LogLevel.Critical && logLevel != LogLevel.Error)
        {
            return;
        }

        TryInitialize();

        if (_userExceptionInformer == null)
        {
            return;
        }

        _userExceptionInformer.Inform(new UserExceptionInformerContext(exception));
    }

```

### Version

7.2.2

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi 

Please share the `Reproduction Steps` of a new template project.

Thanks

**Comment by happtim** [comment]
hi maliming

I found that the modal in BlazoriseUI is a singleton, it only appears once, while the MudBlazorUI I am using can appear multiple times.

Example code repository: https://github.com/happtim/issue18104

```
protected async Task ClickAsync()
{
    try
    {
        throw new UserFriendlyException("Test");
    }
    catch (Exception ex)
    {
        await HandleErrorAsync(ex);
        await Message.Error(ex.Message + "1");
        await Message.Error(ex.Message + "2");
        //Logger.LogException(ex,LogLevel.Error);
    }
}
```
![微信图片_20231115215252](https://github.com/abpframework/abp/assets/7238267/4d342243-09fd-4a4c-af0f-d28ed337dd25)

Do you need me to provide the code for MudBlazorUI?

**Comment by maliming** [comment]
hi

> I found that the modal in BlazoriseUI is a singleton, it only appears once, while the MudBlazorUI I am using can appear multiple times.

We are not using `MudBlazorUI` now. You can try to make it to singleton.

**Comment by happtim** [comment]
Thanks
