### ISSUE TITLE
After configuring using password rules, ResetPasswordAsync did not apply the configuration rules

### ISSUE THREAD

**Issue by magicalconchs** [abpframework/abp#18113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The injected IdentityUserManager. ResetPasswordAsync did not reset the password according to the expected configuration password rules

### Reproduction Steps

Firstly, I configured the following password verification rules in the ApiSettingDefinitionProvider of the Domain layer:
```
public class ApiSettingDefinitionProvider : SettingDefinitionProvider
{
    public override void Define(ISettingDefinitionContext context)
    {
        context.Add(
            new SettingDefinition(ApiSettings.DataBase.DefaultDataSourceType, 
                ((int)DataSourceTypeEnum.SqlServer).ToString()),
            new SettingDefinition(ApiSettings.User.DftPwd, "123456"),
            new SettingDefinition(IdentitySettingNames.Password.RequiredLength, 6.ToString()),
            new SettingDefinition(IdentitySettingNames.Password.RequiredUniqueChars, 0.ToString()),
            new SettingDefinition(IdentitySettingNames.Password.RequireNonAlphanumeric, false.ToString()),
            new SettingDefinition(IdentitySettingNames.Password.RequireLowercase, false.ToString()),
            new SettingDefinition(IdentitySettingNames.Password.RequireUppercase, false.ToString()),
            new SettingDefinition(IdentitySettingNames.Password.RequireDigit, false.ToString()),
            new SettingDefinition(IdentitySettingNames.Lockout.AllowedForNewUsers, true.ToString()),
            new SettingDefinition(IdentitySettingNames.Lockout.LockoutDuration, 1.ToString()),
            new SettingDefinition(IdentitySettingNames.Lockout.MaxFailedAccessAttempts, 9999.ToString()),
            new SettingDefinition(IdentitySettingNames.SignIn.RequireConfirmedEmail, false.ToString()),
            new SettingDefinition(IdentitySettingNames.SignIn.RequireConfirmedPhoneNumber, false.ToString()),
            new SettingDefinition(LocalizationSettingNames.DefaultLanguage, "zh-Hans"), 
            new SettingDefinition(EmailSettingNames.Smtp.EnableSsl, false.ToString())
        );
    }
}
```
Then, I called the password reset method on the Service layer, but still triggered password rule verification
```
/// <summary>
/// ResetPassword
/// </summary>
/// <param name="input"></param>
/// <returns></returns>
public async Task ResetPasswordAsync(ResetPwdInput input)
{
    var token = await _identityUserManager.GeneratePasswordResetTokenAsync(data);
    var res = await _identityUserManager.ResetPasswordAsync(data, token, input.DftPwd ?? dftPwd);
    if (!res.Succeeded)
    {
        throw new UserFriendlyException(string.Join(",", res.Errors.Select(c=> c.Description)));
    }
}
```
<img width="813" alt="image" src="https://github.com/abpframework/abp/assets/150404101/4174b979-5b3a-4c9a-9377-8127d7765544">

### Expected behavior

Ability to set passwords according to default configured password rules

### Actual behavior

The configured password rules have not been applied at all

### Regression?

Previously, this rule was valid. One day, I suddenly realized that it was completely invalid and I did not upgrade to any ABP version

### Known Workarounds

I have temporarily used Options configuration to solve this problem, and the configuration here is valid
```
Configure<IdentityOptions>(options =>
  {
      options.Password.RequiredLength = 6;
      options.Password.RequireLowercase = false;
      options.Password.RequireDigit = false;
      options.Password.RequireUppercase = false;
      options.Password.RequiredUniqueChars = 0;
      options.Password.RequireNonAlphanumeric = false;
});

```
### Version

7.1.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

**Comment by JadynWong** [comment]
Inject `IOptions<IdentityOptions>` _identityOptions into your service.

It acts as an abp dynamic option and you must first perform `await _identityOption.SetAsync();`
After that use IdentityUserManager to do your operations. For example `IdentityUserManager.ResetPasswordAsync`.

https://github.com/abpframework/abp/blob/d7d848c938c820733c382a0979d1ae3d2268d1e9/modules/account/src/Volo.Abp.Account.Application/Volo/Abp/Account/ProfileAppService.cs#L78-L97

**Comment by magicalconchs** [comment]
> 将`IOptions<IdentityOptions>`_identityOptions注入您的服务中。
> 
> 它支持 abp 动态选项，必须首先执行，`await _identityOption.SetAsync();` 然后使用 IdentityUserManager 来执行您的操作。例如`IdentityUserManager.ResetPasswordAsync`。
> 
> https://github.com/abpframework/abp/blob/d7d848c938c820733c382a0979d1ae3d2268d1e9/modules/account/src/Volo.Abp.Account.Application/Volo/Abp/Account/ProfileAppService.cs#L78-L97

**Comment by magicalconchs** [comment]
> > 将`IOptions<IdentityOptions>`_identityOptions注入您的服务中。
> > 它支持 abp 动态选项，必须首先执行，`await _identityOption.SetAsync();` 然后使用 IdentityUserManager 来执行您的操作。例如`IdentityUserManager.ResetPasswordAsync`。
> > https://github.com/abpframework/abp/blob/d7d848c938c820733c382a0979d1ae3d2268d1e9/modules/account/src/Volo.Abp.Account.Application/Volo/Abp/Account/ProfileAppService.cs#L78-L97

Oh, God, I'm surprised that the atomicity of this logic is not aggregated within the domain service, but needs to be assembled within the application service. It seems that I did miss this step. Thank you

**Comment by CAH-FlyChen** [comment]
await IdentityOptions.SetAsync();  
the step is confusing  without document
