### ISSUE TITLE
Add an API for checking if a user exists on the target tenant

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#18120]
Angular UI needs an endpoint to check whether a user exists in a tenant.
If the entered username doesn't exist, we'll show a warning message about this.
This will be used when in impersonation.
This operation will be done by the host admin user.

---

The parent issue is https://github.com/volosoft/volo/issues/15631
Related support ticket is https://support.abp.io/QA/Questions/6142/Identity-scopes-requested-but-openid-scope-is-missing

**Comment by ebicoglu** [comment]
@maliming we need to implement this issue for https://github.com/volosoft/volo/issues/15631

**Comment by maliming** [comment]
The impersonation request will return an error message if the username does not exist. 
Do we need an additional endpoint?

<img width="669" alt="image" src="https://github.com/abpframework/abp/assets/6908465/a29f974d-cace-41ef-b591-83dd9444d74c">

**Comment by masumulu28** [comment]
I'll try this end-point for solution @maliming

**Comment by masum-ulu** [comment]
We don't need this end point for now, because when we get error token removing by [this line](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/oauth/src/lib/strategies/auth-flow-strategy.ts#L120-L122) not by oidc-client package
