### ISSUE TITLE
project after upgrading to asp.net core 3.0 authorization does not working

### ISSUE THREAD

**Issue by cinaradem** [abpframework/abp#1813]
project after upgrading to asp.net core 3.0
authorization does not work, giving 401 forbidden to each permission. sample code blog
[Route("all")]
        [Authorize(ProductManagementPermissions.Products.Update)]
        [HttpGet]
        public ActionResult GetAsync()
        {
            return Content("ok");
        }

public class ProductManagementPermissions
    {
        public const string GroupName = "ProductManagement";

        public static class Products
        {
            public const string Default = GroupName + ".Product";
            public const string Delete = Default + ".Delete";
            public const string Update = Default + ".Update";
            public const string Create = Default + ".Create";

        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(ProductManagementPermissions));
        }
    }

**Comment by Trojaner** [comment]
Do you use `app.UseAuthorization();`?
For me this was required to add after upgrading to ABP 0.21.0 and .NET Core 3

**Comment by maliming** [comment]
@cinaradem  Can you reproduce your problem with the template project created by cli?

**Comment by cinaradem** [comment]
> Do you use `app.UseAuthorization();`?
> For me this was required to add after upgrading to ABP 0.21.0 and .NET Core 3

yes,I use app.UseAuthorization();
but not working permissions

**Comment by cinaradem** [comment]
When I made a migration on template.
