### ISSUE TITLE
ABP HangFire Authentication Failure

### ISSUE THREAD

**Issue by jerinantony11** [abpframework/abp#18130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The ABP Hang-Fire dashboard is unable to authenticate the user after closing the browser (without logging out) and come back.
This is the code for my dash board configuration.  
 
![image](https://github.com/abpframework/abp/assets/57087890/5062fb13-27ad-4704-a4e3-7cb653fc56eb)

The `currentUser.IsAuthenticated` property is false when browser is closed . If I do a proper login by providing username and password then everything is working as expected.

![image](https://github.com/abpframework/abp/assets/57087890/519435bd-c0cd-44bc-94ea-794377a3d818)

I'm using Angular as UI and also using OpenIdDict as athentication.  The module file code is below. 

`using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using MyOrg.MyApp.EntityFrameworkCore;
using MyOrg.MyApp.MultiTenancy;
using Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic;
using Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Bundling;
using Microsoft.OpenApi.Models;
using OpenIddict.Validation.AspNetCore;
using Volo.Abp;
using Volo.Abp.Account;
using Volo.Abp.Account.Web;
using Volo.Abp.AspNetCore.MultiTenancy;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc.UI.Bundling;
using Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared;
using Volo.Abp.AspNetCore.Serilog;
using Volo.Abp.Autofac;
using Volo.Abp.Localization;
using Volo.Abp.Modularity;
using Volo.Abp.Swashbuckle;
using Volo.Abp.UI.Navigation.Urls;
using Volo.Abp.VirtualFileSystem;
using MyOrg.MyApp.Swagger;
using System.Security.Cryptography.X509Certificates;
using Volo.Abp.OpenIddict;
using System.Threading.Tasks;
using MyOrg.MyApp.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System.Security.Claims;
using Microsoft.Identity.Web;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authentication;
using Hangfire;
using MyOrg.MyApp.AuthFilters;
using Volo.Docs;

namespace MyOrg.MyApp;

[DependsOn(
    typeof(MyAppHttpApiModule),
    typeof(AbpAutofacModule),
    typeof(AbpAspNetCoreMultiTenancyModule),
    typeof(MyAppApplicationModule),
    typeof(MyAppEntityFrameworkCoreModule),
    typeof(AbpAspNetCoreMvcUiBasicThemeModule),
    typeof(AbpAccountWebOpenIddictModule),
    typeof(AbpAspNetCoreSerilogModule),
    typeof(AbpSwashbuckleModule),
    typeof(DocsWebModule)
)]
public class MyAppHttpApiHostModule : AbpModule
{
    public override async Task OnPreApplicationInitializationAsync(ApplicationInitializationContext context)
    {
        var configuration = context.GetConfiguration();

        // Run migrations pre-application initialization
        if (bool.TryParse(configuration["EXECUTE_MIGRATIONS"], out var execute) && execute)
        {
            var migrationsService = context.ServiceProvider.GetRequiredService<MyAppDbMigrationService>();
            await migrationsService.MigrateAsync();
        }

        await base.OnPreApplicationInitializationAsync(context);
    }

    public override void PreConfigureServices(ServiceConfigurationContext context)
    {
#if RELEASE
        var configuration = context.Services.GetConfiguration();
        var hostingEnvironment = context.Services.GetHostingEnvironment();

        PreConfigure<AbpOpenIddictAspNetCoreOptions>(options =>
        {
            if (hostingEnvironment.IsProduction())
            {
                //https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html
                options.AddDevelopmentEncryptionAndSigningCertificate = false;
            }
        });

        PreConfigure<OpenIddictServerBuilder>(options =>
        {
            if (hostingEnvironment.IsProduction())
            {
                options.AddEncryptionCertificate(LoadCertificate(
                    configuration["AuthServer:EncryptionCertificateThumbprint"]));
                options.AddSigningCertificate(LoadCertificate(
                    configuration["AuthServer:SigningCertificateThumbprint"]));
            }
        });
#endif

        PreConfigure<OpenIddictBuilder>(builder =>
        {
            builder.AddValidation(options =>
            {
                options.AddAudiences("MyApp");
                options.UseLocalServer();
                options.UseAspNetCore();
            });
        });
    }

    private X509Certificate2 LoadCertificate(string thumbprint)
    {
        var bytes = File.ReadAllBytes($"/var/ssl/private/{thumbprint}.p12");
        return new X509Certificate2(bytes);
    }

    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        var configuration = context.Services.GetConfiguration();
        var hostingEnvironment = context.Services.GetHostingEnvironment();

        ConfigureAuthentication(context, configuration);
        ConfigureBundles();
        ConfigureUrls(configuration);
        ConfigureConventionalControllers();
        ConfigureLocalization();
        ConfigureIdentityOptions(context);
        ConfigureVirtualFileSystem(context);
        ConfigureCors(context, configuration);
        ConfigureSwaggerServices(context, configuration);
        context.Services.AddSpaStaticFiles(cfg => { cfg.RootPath = "ClientApp/dist"; });
    }

    private void ConfigureAuthentication(ServiceConfigurationContext context, IConfiguration configuration)
    {
        context.Services.ForwardIdentityAuthenticationForBearer(OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme);
    }

    private void ConfigureBundles()
    {
        Configure<AbpBundlingOptions>(options =>
        {
            options.StyleBundles.Configure(
                BasicThemeBundles.Styles.Global,
                bundle =>
                {
                    bundle.AddFiles("/global-styles.css");
                }
            );
        });
    }

    private void ConfigureUrls(IConfiguration configuration)
    {
        Configure<AppUrlOptions>(options =>
        {
            options.Applications["MVC"].RootUrl = configuration["App:SelfUrl"];
            options.RedirectAllowedUrls.AddRange(configuration["App:RedirectAllowedUrls"].Split(','));

            options.Applications["Angular"].RootUrl = configuration["App:ClientUrl"];
            options.Applications["Angular"].Urls[AccountUrlNames.PasswordReset] = "account/reset-password";
        });
    }

    private void ConfigureVirtualFileSystem(ServiceConfigurationContext context)
    {
        var hostingEnvironment = context.Services.GetHostingEnvironment();

        if (hostingEnvironment.IsDevelopment())
        {
            Configure<AbpVirtualFileSystemOptions>(options =>
            {
                options.FileSets.ReplaceEmbeddedByPhysical<MyAppDomainSharedModule>(
                    Path.Combine(hostingEnvironment.ContentRootPath,
                        $"..{Path.DirectorySeparatorChar}MyOrg.MyApp.Domain.Shared"));
                options.FileSets.ReplaceEmbeddedByPhysical<MyAppDomainModule>(
                    Path.Combine(hostingEnvironment.ContentRootPath,
                        $"..{Path.DirectorySeparatorChar}MyOrg.MyApp.Domain"));
                options.FileSets.ReplaceEmbeddedByPhysical<MyAppApplicationContractsModule>(
                    Path.Combine(hostingEnvironment.ContentRootPath,
                        $"..{Path.DirectorySeparatorChar}MyOrg.MyApp.Application.Contracts"));
                options.FileSets.ReplaceEmbeddedByPhysical<MyAppApplicationModule>(
                    Path.Combine(hostingEnvironment.ContentRootPath,
                        $"..{Path.DirectorySeparatorChar}MyOrg.MyApp.Application"));
            });
        }
    }

    private void ConfigureConventionalControllers()
    {
        //Configure<AbpAspNetCoreMvcOptions>(options =>
        //{
        //    options.ConventionalControllers.Create(typeof(MyAppApplicationModule).Assembly);
        //});
    }

    private static void ConfigureSwaggerServices(ServiceConfigurationContext context, IConfiguration configuration)
    {
        context.Services.AddAbpSwaggerGenWithOAuth(
            configuration["AuthServer:Authority"],
            new Dictionary<string, string>
            {
                    {"MyApp", "MyApp API"}
            },
            options =>
            {
                options.SwaggerDoc("v1", new OpenApiInfo { Title = "MyApp API", Version = "v1" });
                options.DocInclusionPredicate((docName, description) => true);
                options.CustomSchemaIds(x => SwaggerHelper.DefaultSchemaIdSelector(x, true));
                options.SchemaGeneratorOptions.UseInlineDefinitionsForEnums = true;
            });
    }

    private void ConfigureLocalization()
    {
        Configure<AbpLocalizationOptions>(options =>
        {
            options.Languages.Add(new LanguageInfo("ar", "ar", "العربية"));
            options.Languages.Add(new LanguageInfo("cs", "cs", "Čeština"));
            options.Languages.Add(new LanguageInfo("en", "en", "English"));
            options.Languages.Add(new LanguageInfo("en-GB", "en-GB", "English (UK)"));
            options.Languages.Add(new LanguageInfo("fi", "fi", "Finnish"));
            options.Languages.Add(new LanguageInfo("fr", "fr", "Français"));
            options.Languages.Add(new LanguageInfo("hi", "hi", "Hindi", "in"));
            options.Languages.Add(new LanguageInfo("is", "is", "Icelandic", "is"));
            options.Languages.Add(new LanguageInfo("it", "it", "Italiano", "it"));
            options.Languages.Add(new LanguageInfo("hu", "hu", "Magyar"));
            options.Languages.Add(new LanguageInfo("pt-BR", "pt-BR", "Português"));
            options.Languages.Add(new LanguageInfo("ro-RO", "ro-RO", "Română"));
            options.Languages.Add(new LanguageInfo("ru", "ru", "Русский"));
            options.Languages.Add(new LanguageInfo("sk", "sk", "Slovak"));
            options.Languages.Add(new LanguageInfo("tr", "tr", "Türkçe"));
            options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));
            options.Languages.Add(new LanguageInfo("zh-Hant", "zh-Hant", "繁體中文"));
            options.Languages.Add(new LanguageInfo("de-DE", "de-DE", "Deutsch", "de"));
            options.Languages.Add(new LanguageInfo("es", "es", "Español", "es"));
            options.Languages.Add(new LanguageInfo("el", "el", "Ελληνικά"));
        });
    }

    private void ConfigureIdentityOptions(ServiceConfigurationContext context)
    {
        context.Services.Configure<IdentityOptions>(options =>
        {
            options.SignIn.RequireConfirmedAccount = true;
            options.SignIn.RequireConfirmedEmail = true;
            options.SignIn.RequireConfirmedPhoneNumber = false;
        });
    }
    private void ConfigureCors(ServiceConfigurationContext context, IConfiguration configuration)
    {
        context.Services.AddCors(options =>
        {
            options.AddDefaultPolicy(builder =>
            {
                builder
                    .WithOrigins(
                        configuration["App:CorsOrigins"]
                            .Split(",", StringSplitOptions.RemoveEmptyEntries)
                            .Select(o => o.RemovePostFix("/"))
                            .ToArray()
                    )
                    .WithAbpExposedHeaders()
                    .SetIsOriginAllowedToAllowWildcardSubdomains()
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials();
            });
        });
    }

    public override void OnApplicationInitialization(ApplicationInitializationContext context)
    {
        var app = context.GetApplicationBuilder();
        var env = context.GetEnvironment();

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseAbpRequestLocalization();

        if (!env.IsDevelopment())
        {
            app.UseErrorPage();
        }

        app.UseCorrelationId();
        app.UseStaticFiles();

        // Add the following
        if (!env.IsDevelopment())
        {
            app.UseSpaStaticFiles();
        }

        app.UseRouting();
        app.UseCors();
        app.UseAuthentication();
        app.UseAbpOpenIddictValidation();

        if (MultiTenancyConsts.IsEnabled)
        {
            app.UseMultiTenancy();
        }

        app.UseUnitOfWork();
        app.UseAuthorization();

        app.UseSwagger();
        app.UseAbpSwaggerUI(c =>
        {
            c.SwaggerEndpoint("/swagger/v1/swagger.json", "MyApp API");

            var configuration = context.ServiceProvider.GetRequiredService<IConfiguration>();
            c.OAuthClientId(configuration["AuthServer:SwaggerClientId"]);
            c.OAuthScopes("MyApp");
        });

        app.UseAuditing();
        app.UseAbpSerilogEnrichers();
        app.UseHangfireDashboard("/hangfire", new DashboardOptions
        {
            AsyncAuthorization = new[] { new AbpHangfireAuthorizationFilter(requiredPermissionName: "MyApp.ScheduleJobs.ViewAdminDashBoard") }
        });
        app.UseConfiguredEndpoints();

        // Add  the following after app.UseConfiguredEndpoints();
        app.UseSpa(spa =>
        {
            spa.Options.SourcePath = "ClientApp";
            if (env.IsDevelopment())
            {
                // spa.UseAngularCliServer(npmScript: "start");
                spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
            }
        });
    }
}
`

### Expected behavior

As the ABP application allows us to come back to the application after closing the browser (without needing to login by providing user name and password),  The currentUser.IsAuthenticated must return true.
`  var currentUser = context.GetHttpContext().RequestServices.GetRequiredService<ICurrentUser>();
currentUser.IsAuthenticated`

### Version

6.0.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

> user after closing the browser 

How did you sign in to the website? 
Cookies or oauth2?

**Comment by jerinantony11** [comment]
I'm using the ABP MVC login . Its cookies

**Comment by maliming** [comment]
hi

You can select the `remember me` on the login page.

**Comment by jerinantony11** [comment]
Is there any way to force login once the user closes the browser ?   At the moment , the behavior I see is , ABP allows user to go back to application pages just by using the "Continue as xxx" provision  (even if the user do not select 'remember me' option) . I think The ideal behavior has to be like  - At anytime user accessing the application, it checks for a valid cookie and if not present , redirect to the login page  not to 'continue as xxx' . Is this achievable ?

**Comment by maliming** [comment]
You can implement yourself in asp net core.
