### ISSUE TITLE
Community Article: .NET Aspire

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#18146]
The [first preview](https://aka.ms/aspireannouncement) of .NET Aspire is available with the .NET 8 release and it seems very promising. 

Here is its repository: https://github.com/dotnet/aspire 
/ docs: https://learn.microsoft.com/en-us/dotnet/aspire/ 
/ and samples: https://github.com/dotnet/aspire-samples

Check the .NET Aspire, deep dive it, and create a community article for it.

**Comment by helloxubo** [comment]
Aspire looks very nice and hopefully integrated with ABP.

**Comment by leonkosak** [comment]
@helloxubo, I wouldn't integrate it in abp, because it's opinionated stack. Community article or even better - deployment documentation option inside docs.abp.io is a better approach.

**Comment by EngincanV** [comment]
> @helloxubo, I wouldn't integrate it in abp, because it's opinionated stack. Community article or even better - deployment documentation option inside docs.abp.io is a better approach.

I agree with you.

**Comment by umerkle** [comment]
@maliming mentioned, that abp will switch to Aspire in the near future [here](https://github.com/abpframework/abp/issues/18271)

I think Aspire will be the future, not tye anymore.

**Comment by leonkosak** [comment]
@berkansasmaz (or @EngincanV), what would this community article cover?
Is it viable to expect how to run a layered MVC (and/or Blazor) solution?

I am also looking at [ABP Studio](https://commercial.abp.io/studio) and want to figure what Studio offers more compared to Aspire regarding running abp-based solution in kubernetes.

Thank you for explanations.

**Comment by berkansasmaz** [comment]
> @berkansasmaz (or @EngincanV), what would this community article cover? Is it viable to expect how to run a layered MVC (and/or Blazor) solution?
> 
> I am also looking at [ABP Studio](https://commercial.abp.io/studio) and want to figure what Studio offers more compared to Aspire regarding running abp-based solution in kubernetes.
> 
> Thank you for explanations.

Yes, I want to explain how to run a layered MVC (and/or Blazor) solution, but at this stage, we should not expect 100% compatibility with some of Aspire's Components.


I haven't fully investigated Aspire's Aspir8 (aspire for K8s) project, so I can't say anything comparatively. However, if you want to learn about the features ABP Studio provides for Kubernetes, you can look [here](https://docs.abp.io/en/commercial/latest/studio/kubernetes).

**Comment by kfrancis** [comment]
Well, if I can figure out how to migrate the db in the correct way .. 

![image](https://github.com/abpframework/abp/assets/67574/70af8e9b-ebd6-4fd0-9554-6ad7477219fd)

**Comment by leonkosak** [comment]
@kfrancis, as I understand, only running dbmigrator project is the only thing that is not resolved (and all other projects are running in Aspire)?

**Comment by kfrancis** [comment]
> @kfrancis, as I understand, only running dbmigrator project is the only thing that is not resolved (and all other projects are running in Aspire)?

It seems to be running the sites as expected, the only tricky bit seems to be the SQL. They all seem to be communicating with the same SQL instance now that I modified the factory:

```c#
var builder = new DbContextOptionsBuilder<BookStoreDbContext>()
    .UseSqlServer("sqldata");
```

and here's my host config:
```c#

var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("RedisConnection");

var sql = builder.AddSqlServer("sql");
var sqldb = sql.AddDatabase("sqldb");

builder.AddProject<Projects.Acme_BookStore_AuthServer>("acme-bookstore-authserver")
    .WithHttpsEndpoint(port: 44387)
    .WithReference(cache)
    .WithReference(sqldb);

builder.AddProject<Projects.Acme_BookStore_HttpApi_Host>("acme-bookstore-httpapi-host")
    .WithHttpsEndpoint(port: 44358)
    .WithReference(cache)
    .WithReference(sqldb);

builder.AddProject<Projects.Acme_BookStore_Web>("acme-bookstore-web")
    .WithHttpsEndpoint(port: 44336)
    .WithReference(cache)
    .WithReference(sqldb);

//builder.AddProject<Projects.Acme_BookStore_DbMigrator>("acme-bookstore-dbmigrator")
//    .WithReference(sqldb);

builder.Build().Run();
```

So, while I can have it run the migrator - when I do it seems to be trying to migrate more than once?
![image](https://github.com/abpframework/abp/assets/67574/f4191610-9cf6-493b-9cdf-f62182154a83)

**Comment by kfrancis** [comment]
Structured logs work:
![image](https://github.com/abpframework/abp/assets/67574/77313705-b092-4deb-bfe1-4a9da69b774c)

Just adding `Serilog.Sinks.OpenTelemetry` to `web`, `httpapi.host` and `authserver` and changing:
```c#
builder.Host
    .AddAppSettingsSecretsJson()
    .UseAutofac()
    .UseSerilog();

// To this
builder.Host
    .AddAppSettingsSecretsJson()
    .UseAutofac()
    .UseSerilog((ctx, lc) => lc
        .Enrich.FromLogContext()
        .WriteTo.OpenTelemetry(options =>
        {
            options.Endpoint = builder.Configuration["OTEL_EXPORTER_OTLP_ENDPOINT"];
            var headers = builder.Configuration["OTEL_EXPORTER_OTLP_HEADERS"]?.Split(',') ?? [];
            foreach (var header in headers)
            {
                var (key, value) = header.Split('=') switch
                {
                [string k, string v] => (k, v),
                    var v => throw new Exception($"Invalid header format {v}")
                };

                options.Headers.Add(key, value);
            }
            options.ResourceAttributes.Add("service.name", ctx.HostingEnvironment.ApplicationName.ToLower().Replace(".","-"));

            //To remove the duplicate issue, we can use the below code to get the key and value from the configuration

            var (otelResourceAttribute, otelResourceAttributeValue) = builder.Configuration["OTEL_RESOURCE_ATTRIBUTES"]?.Split('=') switch
            {
            [string k, string v] => (k, v),
                _ => throw new Exception($"Invalid header format {builder.Configuration["OTEL_RESOURCE_ATTRIBUTES"]}")
            };

            options.ResourceAttributes.Add(otelResourceAttribute, otelResourceAttributeValue);
        })
        .ReadFrom.Configuration(ctx.Configuration));
```

Just reading through https://github.com/serilog/serilog-aspnetcore/issues/359

**Comment by EngincanV** [comment]
https://community.abp.io/posts/how-to-use-.net-aspire-with-abp-framework-h29km4kk
