### ISSUE TITLE
In In Blazor project there is no reference to PackageReference Include="Microsoft.EntityFrameworkCore.Design"

### ISSUE THREAD

**Issue by Elencon** [abpframework/abp#18141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I executed command add Migration and get error:
Your startup project '*.Blazor' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

### Describe the solution you'd like

Insert reference to "Microsoft.EntityFrameworkCore.Design" into project template

**Comment by gterdem** [comment]
Migrations are not created under the **Blazor** layer but under the **EntityFrameworkCore** layer. So you need to run `dotnet ef migrations add` under the EntityFrameworkCore layer.

**Comment by Elencon** [comment]
Thanks My mistake Sorry
