### ISSUE TITLE
The homepage of the website has one character ">"

### ISSUE THREAD

**Issue by sxfkue** [abpframework/abp#1816]
The homepage of the website has one character ">"
![image](https://user-images.githubusercontent.com/16209295/65810283-384a6d80-e1db-11e9-8ea4-ac343c2df8b1.png)

**Comment by sxfkue** [comment]
&gt;Advanced authorization with user, role and fine-grained permission system. Built on the Microsoft Identity library.

**Comment by sxfkue** [comment]
![image](https://user-images.githubusercontent.com/16209295/65810277-21a41680-e1db-11e9-90c8-cabfdb37e11f.png)

**Comment by maliming** [comment]
Already fixed, waiting for website updates.
