### ISSUE TITLE
How to run it, OpenIddict.Demo.Server

### ISSUE THREAD

**Issue by billpeace** [abpframework/abp#18162]
OpenIddict.Demo.Server  

EntityFrameworkCore\Add-Migration -Context ServerDbContext  20231116
EntityFrameworkCore\Update-Database -Context ServerDbContext

then start

then test OpenIddict.Demo.Client.Console  OpenIddict.Demo.Client.Mvc

https://localhost:44301/connect/token  invalid_request

OpenIddict.Demo.Client.Console  error
![image](https://github.com/abpframework/abp/assets/372286/5fdb5c1a-4c23-40e2-8745-660fe48ed02d)

OpenIddict.Demo.Client.Mvc
![image](https://github.com/abpframework/abp/assets/372286/adefd9ef-57df-41c0-bbb1-c57103d31b3f)

**Comment by maliming** [comment]
Please check the logs.

**Comment by billpeace** [comment]
There are other files for logging？

![image](https://github.com/abpframework/abp/assets/372286/4725d98e-b518-4385-80e7-545965313ec4)

![image](https://github.com/abpframework/abp/assets/372286/65340012-9436-4f91-a6fa-1702652db5af)

**Comment by maliming** [comment]
It works on my machine.

<img width="2173" alt="image" src="https://github.com/abpframework/abp/assets/6908465/ff401482-f2f5-4cbe-8a75-e325adbb8f0d">

**Comment by billpeace** [comment]
"grant_type": "password",  Yours is not

how to change in this project?

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:44301/connect/token - application/x-www-form-urlencoded 116
info: OpenIddict.Server.OpenIddictServerDispatcher[0]
      The request URI matched a server endpoint: Token.
info: OpenIddict.Server.OpenIddictServerDispatcher[0]
      The token request was successfully extracted: {
        "grant_type": "password",
        "username": "admin@abp.io",
        "password": "[redacted]",
        "scope": "AbpAPI profile roles email phone offline_access",
        "client_id": "AbpApp",
        "client_secret": "[redacted]"
      }.

![image](https://github.com/abpframework/abp/assets/372286/f2db21b1-7695-4a8e-abf5-d4a67f7c63ce)

**Comment by billpeace** [comment]
Suddenly it's OK

Thanks
