### ISSUE TITLE
How to Migration old ASP.NET Boilerplate to new ABP Vnext?

### ISSUE THREAD

**Issue by vincywindy** [abpframework/abp#1817]
Any document?
I want to ASP.NET Boilerplate to use ABP Vnext Identity server.So how to Migration old abp users,roles and permissions to new ABP Vnext?

**Comment by maliming** [comment]
There are currently no migration documents. The documentation will be enhanced soon, you can wait for it.

**Comment by jack-gaojz** [comment]
> There are currently no migration documents. The documentation will be enhanced soon, you can wait for it.

Thanks so much. it's awesome! :)

**Comment by hikalkan** [comment]
Follow https://github.com/abpframework/abp/issues/2120
