### ISSUE TITLE
Build MicroserviceDemo Image Failed, cannot read sqlite3\db.lock

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#1819]
Permission denied:  MicroserviceDemo\.vs\MicroserviceDemo\v16\Server\sqlite3\db.lock
![image](https://user-images.githubusercontent.com/15363011/65815296-4f5f7e80-e220-11e9-9d89-fa6849036fa7.png)

docker info:   docker desktop for windows     19.03.2
![image](https://user-images.githubusercontent.com/15363011/65815287-3d7ddb80-e220-11e9-9668-9035703e094f.png)

**Comment by maliming** [comment]
This has nothing to do with abp, and is related to docker.

eg
https://github.com/docker/for-win/issues/1924#issuecomment-381927447
