### ISSUE TITLE
How to Skip creating topic with Kafka Eventbus?

### ISSUE THREAD

**Issue by ttl1601** [abpframework/abp#18201]
I using Distributed Event Bus Kafka Integration and has issue:

```
 An error occurred creating topics: [dev-notifications-data]: [Broker: Cluster authorization failed].
Confluent.Kafka.Admin.CreateTopicsException: An error occurred creating topics: [dev-notifications-data]: [Broker: Cluster authorization failed].
   at Volo.Abp.Kafka.KafkaMessageConsumer.CreateTopicAsync()
   at Volo.Abp.Kafka.KafkaMessageConsumer.Timer_Elapsed(AbpAsyncTimer timer)
   at Volo.Abp.Threading.AbpAsyncTimer.Timer_Elapsed()
```
Actually my Kafka system has Authentication, so it doesn't have permission to create Topic, and this Topic ([dev-notifications-data]) has created by Admin manages Kafka.

**Desire**: can skip CreateTopic, only need Consumer Subscribe to Topic has created

Thanks for support.

**Comment by realLiangshiwei** [comment]
Hi,

You can replace the `KafkaMessageConsumer` to override the `CreateTopicAsync` method.

**Comment by ttl1601** [comment]
> Hi,
> 
> You can replace the `KafkaMessageConsumer` to override the `CreateTopicAsync` method.

@realLiangshiwei  Thank you!

**Comment by cheefoong5512** [comment]
> Hi,
> 
> You can replace the `KafkaMessageConsumer` to override the `CreateTopicAsync` method.

Hi! I am a beginner to this framework, how can I do this exactly? Appreciate it :)
