### ISSUE TITLE
How to use ISettingManager in test?

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#1820]
public MyAppServiceTest()
        {
            _settingManager = GetRequiredService<ISettingManager>();
        }

Cause exception:
~~~
Autofac.Core.Registration.ComponentNotRegisteredException : The requested service 'Volo.Abp.SettingManagement.ISettingManager' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
~~~

**Comment by maliming** [comment]
Does your module depend on `AbpSettingManagementDomainModule`?

https://github.com/abpframework/abp/blob/dev/modules/setting-management/test/Volo.Abp.SettingManagement.TestBase/Volo/Abp/SettingManagement/AbpSettingManagementTestBaseModule.cs#L11

**Comment by wakuflair** [comment]
I added `typeof(AbpSettingManagementDomainModule)` in "DependsOn of my TestBaseModule class, now the constructor is OK.
However, my test method begin to raise exception after I added the depends on stuff.
Test method:
``` csharp
        [Fact]
        public async Task Test1()
        {
            await _myDomainService.MyDomainServiceMethod();
        }
```

MyDomainService is a domain service which uses SettingProvider inside:
``` csharp
    public class MyDomainService : DomainService, IMyDomainService
    {

        private ISettingProvider _settingProvider;

        public MyDomainService(ISettingProvider settingProvider)
        {
            _settingProvider = settingProvider;
        }

        public async Task MyDomainServiceMethod()
        {
            string value = await _settingProvider.GetOrNullAsync("MY_SETTING");
        }
```

The strange thing is that if I remove the depends on stuff, the Test1 method works fine.

**Comment by maliming** [comment]
Provide a project to reproduce the problem?

**Comment by wakuflair** [comment]
@maliming Sorry for late replay.
DEMO project uploaded: https://github.com/wakuflair/MyABPModule
Please see the readme to reproduce the issue.

**Comment by maliming** [comment]
The test project is missing the `AbpSettingManagementEntityFrameworkCoreModule`
