### ISSUE TITLE
Abp generate-proxy : adding headers

### ISSUE THREAD

**Issue by Dinotsuyo** [abpframework/abp#18228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello,

I can't currently send headers within my endpoints from generate-proxy.

### Describe the solution you'd like

I have seen a closed issue about adding the headers to the endpoints generated-proxy :
https://github.com/abpframework/abp/issues/12310
Do we have now access to these headers in the latest versions ?

**Comment by masum-ulu** [comment]
Hi @Dinotsuyo I know it's been a while, yet have u tried to interceptions ? What is your exac problem ? Can u give me a some use cases for example ?
