### ISSUE TITLE
The RNGCryptoServiceProvider  is thread safe.

### ISSUE THREAD

**Issue by tangdf** [abpframework/abp#1823]
https://github.com/abpframework/abp/blob/d3d28ea0c5c526342a0dbb18bf11dcd98bd520c6/framework/src/Volo.Abp.Guids/Volo/Abp/Guids/SequentialGuidGenerator.cs#L30-L38

RandomNumberGenerator.Create() return the type of System.Security.Cryptography.RNGCryptoServiceProvider；

This type is thread safe.

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?redirectedfrom=MSDN&view=netframework-4.8#thread-safety

**Comment by maliming** [comment]
It looks like it is.

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider.getbytes?redirectedfrom=MSDN&view=netcore-3.0#overloads
