### ISSUE TITLE
.net8 starting slowly

### ISSUE THREAD

**Issue by cocosip** [abpframework/abp#18241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`After upgrade abp from  v7.4.0 to v8.0.0-rc.1, the app start slowly`
`The abp 8.0.0-rc.1 version took nearly 1 minute to start loading the abp module`

![net7](https://github.com/abpframework/abp/assets/9337837/7dd2d802-04f0-4cd8-90f2-c4b22130637c)
![net8](https://github.com/abpframework/abp/assets/9337837/3dd49431-8d73-4e1b-80f4-0867d6db046b)

### Version

8.0.0-rc.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem

Steps:

* abp new Qa74 -d mongodb -v 7.4.2 -t app
* abp new Qa80 -d mongodb --preview -t app

#### 7.4.2

```
[09:06:20 INF] Starting web host.
[09:06:21 INF] Loaded ABP modules:
[09:06:21 INF] - Qa74.Web.Qa74WebModule
[09:06:21 INF]   - Qa74.Qa74HttpApiModule
```

#### 8.0

```
[09:06:23 INF] Starting web host.
[09:06:24 INF] Loaded ABP modules:
[09:06:24 INF] - Qa80.Web.Qa80WebModule
[09:06:24 INF]   - Qa80.Qa80HttpApiModule
```

<img width="1732" alt="image" src="https://github.com/abpframework/abp/assets/16813853/079994db-f2bf-408c-9f08-217713690a6b">

**Comment by cocosip** [comment]
> I can't reproduce the problem
> 
> Steps:
> 
> * abp new Qa74 -d mongodb -v 7.4.2 -t app
> * abp new Qa80 -d mongodb --preview -t app
> 
> #### 7.4.2
> ```
> [09:06:20 INF] Starting web host.
> [09:06:21 INF] Loaded ABP modules:
> [09:06:21 INF] - Qa74.Web.Qa74WebModule
> [09:06:21 INF]   - Qa74.Qa74HttpApiModule
> ```
> 
> #### 8.0
> ```
> [09:06:23 INF] Starting web host.
> [09:06:24 INF] Loaded ABP modules:
> [09:06:24 INF] - Qa80.Web.Qa80WebModule
> [09:06:24 INF]   - Qa80.Qa80HttpApiModule
> ```
> 
> <img alt="image" width="1732" src="https://user-images.githubusercontent.com/16813853/285329960-079994db-f2bf-408c-9f08-217713690a6b.png">

Do you upgrade All ABP package and Microsoft Package to 8.0 ? Or just upgrade host project from 7.0 to 8.0? 
When i just use ABP 7.4.0, and set project to net8.0, it start quickly

![onet8](https://github.com/abpframework/abp/assets/9337837/c2d9469b-20fa-4c7e-af33-0db2ad27ae1d)

**Comment by cocosip** [comment]
It seems to be caused by EFCore. When the number of DbSet entities in EFCore is relatively small, it is still very fast. When the number of entities becomes large, the ABP startup becomes very slow. @realLiangshiwei

**Comment by realLiangshiwei** [comment]
Can you share a test project?

**Comment by cocosip** [comment]
> Can you share a test project?

Here is my demo project [https://github.com/cocosip/AbpSlowDemo](https://github.com/cocosip/AbpSlowDemo) 

1. Create project by Abp Cli tool

2. Add some EntityFramework project to EntityFrameworkCore layer *( I have added some open source projects from ABP and my own defined business modules. You can add more modules )*
![slow3](https://github.com/abpframework/abp/assets/9337837/a2226d57-a75b-40e3-815b-c0e4a878343c)

3. The project starting slowly *(The time required for project initiation has increased from 3s to 13s)*
![slow1](https://github.com/abpframework/abp/assets/9337837/6c24ed9b-4ab9-4000-991b-7c8fcd3768fc)
![slow2](https://github.com/abpframework/abp/assets/9337837/f17a857c-3691-4642-b19f-f4dcf2db41eb)

**Comment by leonkosak** [comment]
@realLiangshiwei, just a feature suggestion: Create a boolean parameter in appsettings.json (default: false ?) and in startup project (deployed project) fire an easy first query on the database (let's say on small existing Abp table) based on enabled/disabled property in appsettings.json.
What do you think @maliming?

**Comment by realLiangshiwei** [comment]
@cocosip I will check it.

**Comment by realLiangshiwei** [comment]
@leonkosak 

This seems unnecessary because ABP application will access the database during startup.

**Comment by leonkosak** [comment]
Well, then this is not the source of the described issue.

**Comment by cocosip** [comment]
@realLiangshiwei 

thank you!
