### ISSUE TITLE
Q: Dapper still needed?

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#18245]
Based on this part of the documentation: https://docs.abp.io/en/abp/latest/Dapper

EF Core has the ability to trigger raw SQL queries: https://learn.microsoft.com/en-us/ef/core/querying/sql-queries
and now EF Core 8 even raw sql queries for unmapped types: https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#raw-sql-queries-for-unmapped-types

What is the benefit of using Dapper nowadays?

**Comment by maliming** [comment]
hi

Dapper should answer this. : )

**Comment by leonkosak** [comment]
I do not use Dapper and my knowledge is really limited, but I cannot see performance advantages over raw queries in EF Core. :)

**Comment by maliming** [comment]
We will continue to keep the Dapper module/package.

**Comment by leonkosak** [comment]
Of course. :) But I would prefer even 100% usage of ef core raw queries instead of using additional ORM.
