### ISSUE TITLE
Allow for manual setting of Id (int) identity values in Repositories

### ISSUE THREAD

**Issue by DonovanAGBR** [abpframework/abp#18255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm attempting to create DataSeedContributors for multiple tables in a database which each have an integer primary key. Since the sample data I'm attempting to use is from a legacy system and has multiple foreign keys (all integer based), I'm trying to set the value of the primary keys on the parent tables so that subsequent child tables can be inserted while maintaining the original values from the legacy system. However, since SQLServer requires you to execute "SET IDENTITY_INSERT TableName ON" beforehand, I am unable to insert my sample data.

The repository I'm using is currently declared as:
`private readonly IRepository<Category, int> _categoryRepository;`

This currently fails when it attempts to execute the insert, since the identity value is specified:
`await _categoryRepository.InsertAsync(new Category(123) { Name = "Sample", DisplayText = "Sample"}, autoSave: true);`

### Describe the solution you'd like

InsertAsync should have an optional boolean parameter named something like "**identityInsert**" which would ensure that "SET IDENTITY_INSERT Category ON" was executed before the actual insert was executed and then turned off afterwards.

`await _categoryRepository.InsertAsync(new Category(123) { Name = "Sample", DisplayText = "Sample"}, autoSave: true, identityInsert: true);`

**Comment by realLiangshiwei** [comment]
This is not related to ABP but EF Core, you can check : https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#no-value-generation

**Comment by DonovanAGBR** [comment]
But is there way to dynamically enable/disable this feature. For the data seeder, I would want it on (to allow for specifying the value). For production, I would want it off (to allow for automatic population by the DB).

**Comment by realLiangshiwei** [comment]
You can use EF Core to manually execute SQL to enable or disable: https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#executing-non-querying-sql

Because this is not a common requirement, we will not add it.

**Comment by DonovanAGBR** [comment]
The problem I had was gaining access to the DbContext from within the DataSeederContributor in order to be able to execute arbitrary commands. 

I was able get the job done by implementing a custom repository inheriting from EfCoreRepository which allowed me access to the DbContext from within the DataSeederContributor instance (following the instructions on https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-custom-repositories).
