### ISSUE TITLE
writing errors in Documentation in chapter "LeptonX Lite Blazor UI"

### ISSUE THREAD

**Issue by Elencon** [abpframework/abp#18258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

in documentation 
url:  https://docs.abp.io/en/abp/7.4/Themes/LeptonXLite/Blazor?UI=BlazorServer
in  Layout chapter
code:
```csharp
@using Volo.Abp.AspNetCore.Components.Web.LeptonXLiteTheme.Themes.LeptonXLite;
@using Volo.Abp.DependencyInjection

@inherits MainLayout
@attribute [ExposeServices(typeof(MainLayout))]
@attribute [Dependency(ReplaceServices = true)]

@Name
```
Is wrong  and does not compile.
I found code

```csharp
@using Volo.Abp.AspNetCore.Components.Web.LeptonXLiteTheme.Themes.LeptonXLite; 
@using Volo.Abp.DependencyInjection

@inherits Branding
@attribute [ExposeServices(typeof(Branding))]
@attribute [Dependency(ReplaceServices = true)]
@name
@code{
    string name = "QQQQ";
}
```
Which compiles and changes Logo but obscures Icon

The next peace of code is simply wrong

```csharp
[ExposeServices(typeof(MainLayout))]
[Dependency(ReplaceServices = true)
namespace LeptonXLite.DemoApp.Blazor.MyComponents
{
    public partial class MyMainLayout
    {
        public string Name = "My Main Layout";
    }
}
```
As there is no closing square bracket in [Dependency line

### Version

7.4.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
> Which compiles and changes Logo but obscures Icon

Replace component will completely override the page. there is no problem.  if you want to keep the Icon, you have to add it manually.

We will fix other problems, thank you.
