### ISSUE TITLE
Auto API Controllers use controller implementation instead of default interface, which disables interceptors

### ISSUE THREAD

**Issue by ltvan** [abpframework/abp#18278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is an extended report of this issue: https://github.com/abpframework/abp/issues/14168

Not just Fluent Validation, but also other interceptors won't work if we didn't add virtual to service method of a controller by convention. This is because the auto controllers resolved the service implementation instead of service interface. 

In addition, the service implementation also exposed other public methods, which is not included in the service interface, which defeats the purpose of service interface as the application contract. 

Therefore, the auto controllers should use the service interface instead.

### Known Workarounds

Adding virtual to service method could help to enable interceptors on service method invocation. But it's easy to forget, and the service implementation may mistakenly expose more methods than the service contract.

### Version

7.4.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

>  interceptors won't work if we didn't add virtual to service method of a controller by convention.

You have to add `virtual`. There is no other way.

**Comment by ltvan** [comment]
@maliming: Why don't the auto controllers use interfaces instead of service implementation? Is there any technical limit?

**Comment by maliming** [comment]
ASP.NET Core controller must be a class.

**Comment by ltvan** [comment]
I see. I thought that the controllers are just proxies but they are actually the application service classes.

**Comment by ltvan** [comment]
Then the documentation here should be updated to highlight the issue:
https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers

There should be a unit test to ensures all application services use `virtual` methods.

**Comment by maliming** [comment]
See https://github.com/Fody/Virtuosity?tab=readme-ov-file#why-is-this-useful
