### ISSUE TITLE
Using ABP-CLI without changing project references

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#1827]
I want to develop modules for ABP. I need to keep references as projectReference instant packages to the framework/modules directory when creating new module using CLI. Is it possible?

**Comment by maliming** [comment]
Use `local-framework-ref`

```
abp new QA --local-framework-ref
```

**Comment by hitaspdotnet** [comment]
Thanks @maliming

**Comment by hitaspdotnet** [comment]
Should open new issue for this.
`PS D:\github\abp\modules\my-module>abp new MyModule -t module --local-framework-ref`
Then .csproj(s) contains:
`<ProjectReference Include="..\..\..\..\..\framework\src\Volo.Abp.{ModuleName}\Volo.Abp.{ModuleName}.csproj" />`

ShouldBe:
`<ProjectReference Include="..\..\..\..\framework\src\Volo.Abp.{ModuleName}\Volo.Abp.{ModuleName}.csproj" />`

**Comment by hitaspdotnet** [comment]
Of curse modules references too!

**Comment by yekalkan** [comment]
@hitaspdotnet I think the developer of the downloaded project/module should be in charge of where the project will be located and should change those ProjectReference paths on their own (it's an easy job). Even if they want local references, that doesn't mean that new project will be located in abp repository. Therefore paths doesn't have to be fixed for a certain location.

@hikalkan What do you think? Should we fix the paths for a certain location like "abp\modules"?

**Comment by hikalkan** [comment]
We may add another option to set the location of the abp repository. Example usage:

````csharp
abp new BookStore --local-framework-ref --abp-path "..\..\..\abp"
````

or

````csharp
abp new BookStore --local-framework-ref --abp-path "D:\GitHub\abp"
````

@yekalkan is it possible to implement like that?

**Comment by maliming** [comment]
I think the second way is better.

`--abp-path "D:\GitHub\abp"`
