### ISSUE TITLE
[Angular] LeptonX Lite Replacing the SideBarComponent

### ISSUE THREAD

**Issue by cloud0259** [abpframework/abp#18292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, 

I've been following the documentation for replacing the SideBarComponent but nothing happens.

### Reproduction Steps

https://docs.abp.io/en/abp/latest/Themes/LeptonXLite/Angular#sidebar-menu-component

I created a simple component to replace this one

### Version

7.4.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by idreeshaddad** [comment]
A couple of component replacements do not work; unfortunately, the theme source code is not open source. 
So for now I'm doing a lot of walkaround!

**Comment by Sinan997** [comment]
i have produced the issue, we will fix this at new patch version

**Comment by idreeshaddad** [comment]
> i have produced the issue, we will fix this at new patch version

That is good to hear.
Please do mention the patch version here once it's released so we update it.
Thanks

**Comment by cloud0259** [comment]
Thank you, in the meantime, is there a palliative solution?

**Comment by Sinan997** [comment]
> Thank you, in the meantime, is there a palliative solution?

@cloud0259, the sidebar replacement is deprecated. use `Navbar` instead of it. It Behaves same.

we will update documentation.

**Comment by cloud0259** [comment]
Thank you! 
Could you let us know when the documentation has been updated?

**Comment by Sinan997** [comment]
you can follow the related pr -> https://github.com/abpframework/abp/pull/18401
