### ISSUE TITLE
Angular sidebar menu stops working after code inspection

### ISSUE THREAD

**Issue by nurlix** [abpframework/abp#18293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you go to inspection mode aka F12 and change layout to mobile Sidebar menu stops navigating to other components although url seems changing even if you close developer window until page refresh or change language

### Reproduction Steps

I created project F12 minimize until layout changes to mobile mode and manu stops working 

### Version

7.4.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by Sinan997** [comment]
Hi, this problem also occurs when you zoom in and mobile sidebar rendered to the screen.
will be fixed in lepton 3.0.

**Comment by masum-ulu** [comment]
This issue fixed `lepton-x@3.0.0` version
