### ISSUE TITLE
generate-proxy.json should be sorted to avoid conflicts

### ISSUE THREAD

**Issue by ltvan** [abpframework/abp#18306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently the modules and types in generate-proxy.json are generated in different order each running. This make this file conflicts when merging feature branches.

### Describe the solution you'd like

The modules and types should be sorted alphabetically, so that it's always generated in a predictable manner, reduce the chance of conflicts.

**Comment by realLiangshiwei** [comment]
Hi,

Because it is a generated file, if it conflicts when merging branches, you just need to regenerate it.

**Comment by ltvan** [comment]
It took times for every merge. `yarn.lock` and other kinds of lock file are sorted to make sure that same input, same output, so there are not much conflicts occurred. This should be the same.

**Comment by realLiangshiwei** [comment]
Ok, we can consider it.
