### ISSUE TITLE
Better German translation for "Theme:light"

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#18303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The German translation for the key "Theme:light" is wrong.

Current translation: Licht
Better translation: Hell

The German word "Hell" is the opposite of "Dunkel" (dark).

![image](https://github.com/abpframework/abp/assets/17644153/c3e95f8f-b3d2-477c-98e5-76c6bae58bda)

Thanks!
Adrian 

### Version

7.4.2

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
We will update it, thank you
