### ISSUE TITLE
Create examples for `NgbModalOptions` to Angular Modal document

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#18315]
## Purpose

We want to add frequently used examples for Angular Bootstrap Options based on [Angular Bootstrap Modal Document](https://ng-bootstrap.github.io/#/components/modal/examples)

## Todo
- Define option name
- Add simple defination
- Add Image/GIF
- You can chooice examples for our document on the https://ng-bootstrap.github.io/#/components/modal/examples

**Comment by E-Aghbari** [comment]
Hello, I would like to work on this issue. Where do I add the documentation to?

**Comment by masum-ulu** [comment]
> Hello, I would like to work on this issue. Where do I add the documentation to?

Hi, https://abp.io/docs/latest/framework/ui/angular/modal#options
You can contribute to this file: https://github.com/abpframework/abp/blob/dev/docs/en/framework/ui/angular/modal.md

Thanks 🙌

**Comment by E-Aghbari** [comment]
@masum-ulu Heya, I have created a PR regarding this issue. Please review and give me a feedback. Thanks

**Comment by E-Aghbari** [comment]
Can I add my name on the contributors section of Abp website?

**Comment by masum-ulu** [comment]
> Can I add my name on the contributors section of Abp website?

It'll add auto. At contributions section on docs. after PR merged
