### ISSUE TITLE
New created preview (8.0.0-rc.2) project failed

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#18328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Can't create 8.0.0-rc.2 project.

### Reproduction Steps

abp new TestCiCd --ui none -csf --preview
![image](https://github.com/abpframework/abp/assets/834156/0672f2f0-1dd1-497a-b5c0-70ab3a3f23ae)

### Expected behavior

Create a project without error.

### Actual behavior

Error occured while getting the latest version from https://abp.io/api/download/template/get-version/ : 'e' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
The remote service is currently unavailable, please specify the version.

### Regression?

7.x

### Version

8.0.0-rc.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
I could not reproduce the problem.

It may be related to your network.
<img width="876" alt="image" src="https://github.com/abpframework/abp/assets/16813853/482cd8ab-6cf6-450d-ab2d-4fed68df181b">

**Comment by jakeuj** [comment]
> abp new TestCiCd --ui none -csf --preview

It's ok now.
