### ISSUE TITLE
Font-awesome styles missing some icons

### ISSUE THREAD

**Issue by nitrovent** [abpframework/abp#18332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some of the icons available on font-awesome 5.15.4 are not usable via the fa/fas/far classes.
The problem lies within the css stylesheet provided by font-awesome with verision(s) 5.
In version 6 I found no missing icons.

### Reproduction Steps

E.g. try to use the `fa-xmark` class for the x-mark icon. 

### Expected behavior

It should display an `x`.

### Actual behavior

Nothing is displayed because no style is defined for `.fa-xmark::before`

### Known Workarounds

For missing icons, look up the unicode on the font awesome website and append the missing styles to the styles.scss (i.e. if using angular).

```css
.fa-xmark::before { 
  content: "\f00d"; 
}
```

### Version

7.4.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

An update of the lepton theme to fontawesome 6 should help.

**Comment by realLiangshiwei** [comment]
This is not a bug, `xmark` icon is not available in font-awesome version 5 .
https://fontawesome.com/v5/search?q=xmark

You can consider using the [`times` icon](https://fontawesome.com/v5/icons/times?f=classic&s=solid).

**Comment by nitrovent** [comment]
Interesting. Seems they just renamed it. The unicode is the same.
What's irritating is the information on the bottom of the icon detail page
where it says released 1.0.0 for both icon names, whereas the x icon for
example is really introduced with 6.0.0.
If someone else has this problem: the search supports searching for the
unicode, so one can find the icon for older versions.
This issue may be closed then ;)
