### ISSUE TITLE
Problem when using Swagger with OpenIdDict

### ISSUE THREAD

**Issue by lommez** [abpframework/abp#18331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hey,
When obtaining the token through Swagger, the audience value is configured in another property other than "aud", it is configured in "oi_au_id".
When trying to request a protected endpoint I receive the following message: "The audience 'empty' is invalid".

![image](https://github.com/abpframework/abp/assets/10900667/b13a9ebf-95ef-43da-a6d9-e95f40ed9f21)

JWT:

![image](https://github.com/abpframework/abp/assets/10900667/18abfc73-459a-4f50-964e-16b9ef4db26b)

### Version

7.4.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by kevinchalet** [comment]
Hi,

>  When obtaining the token through Swagger, the audience value is configured in another property other than "aud", it is configured in "oi_au_id".

No, `oi_au_id` is not related to audiences, it's a claim that represents the identifier of the authorization to which the token is attached.

The error you're seeing is typically returned by the JWT bearer handler, which indicates you're not using the OpenIddict validation handler. Unlike the JWT handler, the OpenIddict validation handler accepts tokens without an audience (unless you explicitly configured one or more values using `.SetAudiences(...)`.

If you don't want to use the OpenIddict validation handler, you'll need to attach at least one audience to your access tokens. For that, the best option is to use scopes to which one or more resources (that will be used as audiences) are attached.

**Comment by kevinchalet** [comment]
@maliming hey! By looking at the screenshot provided by @lommez, it seems the `email_verified` and `phone_number_verified` claims are not correctly formatted in the tokens (e.g the value is represented as a JSON string instead of a boolean). I suspect the root cause is here: https://github.com/abpframework/abp/blob/1c9e8d28d6bbed284bae405e52305b1508f902ba/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L56-L69 (the `ClaimValueType` is not set, so it defaults to `ClaimValueTypes.String`).

**Comment by maliming** [comment]
Thanks @kevinchalet , I will update the code.

**Comment by maliming** [comment]
hi @lommez 

> When obtaining the token through Swagger,

Did you select the `scope` on swagger UI?

![image](https://github.com/abpframework/abp/assets/6908465/162ca18f-173f-4499-810e-0a05349067e5)

**Comment by lommez** [comment]
Hi @maliming  and @kevinchalet 
Thanks so much helping me..
Now is working perfectly. 

I´ve checked the scopes on the Swagger Ui..
And on the Application Client Side, i´ve changed from
```csharp
context.Services.AddAbpSwaggerGenWithOAuth()
```
to
```csharp
context.Services.AddAbpSwaggerGenWithOidc()
```
