### ISSUE TITLE
background event

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1833]
How can i publish an event so that it runs in a background job.

 I think there is a built in way in the old abpframework but idk if it is implemented yet here, thank you.

**Comment by ismcagdas** [comment]
@wocar why don't you just start a background job ? Is there a specific reason ? If not, you can check https://docs.abp.io/en/abp/latest/Background-Jobs

**Comment by wocar** [comment]
Can’t recall very well, I think it was because my queue object was generic! And wouldn’t work
