### ISSUE TITLE
MaxResultCount only allows a maximum of 1000. - ABP Suite Blazor wasm

### ISSUE THREAD

**Issue by giathanhit** [abpframework/abp#18339]
The data in AuditLogs exceeds 1000, but MaxResultCount only allows a maximum of 1000.

Because I want to retrieve data from the EntityChanges table, but also want to retrieve the ExtraProperties that store the URL of the page and the UserId from the AuditLogs table. However, the data in the AuditLogs table exceeds 1000 records, and the MaxResultCount parameter only allows a maximum of 1000 records to be retrieved, resulting in incorrect data retrieval.

What should I do? Please help me by providing an example to solve it.
![image](https://github.com/abpframework/abp/assets/123981771/df70308d-adb4-4802-8ec9-065ce6b43062)
![image](https://github.com/abpframework/abp/assets/123981771/e0a859bd-e931-487d-a149-fdb0d313370d)
![image](https://github.com/abpframework/abp/assets/123981771/3acec131-7536-4124-9d2f-48d1678bb3bb)
![image](https://github.com/abpframework/abp/assets/123981771/d08208dd-3757-46b8-850c-02478ca1f66a)

**Comment by EngincanV** [comment]
We are not giving commercial support in GitHub. Please create a question at https://support.abp.io/QA/Questions.
