### ISSUE TITLE
ExtraProperties for AuditLogs, EntityChanges - ABP Suite Blazor wasm

### ISSUE THREAD

**Issue by giathanhit** [abpframework/abp#18340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I can add ScreenUrl to the ExtraProperties of AuditLogs, but I cannot add it to the ExtraProperties of EntityChanges.
![image](https://github.com/abpframework/abp/assets/123981771/80fb6e53-6b4f-411e-8248-979280bad504)
![image](https://github.com/abpframework/abp/assets/123981771/8ae0e640-756d-448f-8d78-e3c4c5c9c01c)

### Describe the solution you'd like

I am using AuditLogs, EntityChanges, and EntityChangesProperties to display change history. While AuditLogs can add ExtraProperties for AuditLogs, EntityChanges cannot store them. What should I do?

**Comment by EngincanV** [comment]
We are not giving commercial support in GitHub. Please create a question at https://support.abp.io/QA/Questions.
