### ISSUE TITLE
Response Compression Technique using ABP

### ISSUE THREAD

**Issue by manojkrsna** [abpframework/abp#18348]
* ABP Framework version 7.1.1.

I am trying to use response compression technique which is gzip by following below article and it has not effect 

https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-7.0

PLease help here if anything am i missing here w.r.t ABP to make it work

**Comment by maliming** [comment]
hi

Steps needed to reproduce the problem.

**Comment by manojkrsna** [comment]
Hi,
We are using Module template and in Host Module class

1. For Method ConfigureServices

add below code

        _ = context.Services.Configure<GzipCompressionProviderOptions>(options =>
        {
            options.Level = CompressionLevel.SmallestSize;
        });

        _ = context.Services.AddResponseCompression(options =>
        {
            options.EnableForHttps = true;
            options.Providers.Add<GzipCompressionProvider>();
        });

2. For Method OnApplicationInitialization add below code

        _ = app.UseResponseCompression();


PFB image of OnApplicationInitialization  method to check where it's placed
![image](https://github.com/abpframework/abp/assets/29368357/0180bab2-aeaf-467f-a1ce-ec9bd0c90438)


And run the API in postman to see whether response size changes are occurring.

It's not actually making any impact

**Comment by JadynWong** [comment]
Does your request contain the `Accept-Encoding: gzip` http request header?

**Comment by manojkrsna** [comment]
Yes i am sending that in Headers

![image](https://github.com/abpframework/abp/assets/29368357/d4f7e01d-ae80-4ecd-b68c-ac6191abbbc6)

**Comment by JadynWong** [comment]
Oddly enough, I use it in many projects. Haven't come across your case, may need more detailed information. Also, this doesn't seem to have anything to do with abp.

![image](https://github.com/abpframework/abp/assets/13699353/69bc88ef-43a7-47ca-a003-a8482cde9069)

https://github.com/JadynWong/AbpIssue/blob/18348/src/Acme.BookStore.Web/BookStoreWebModule.cs

**Comment by manojkrsna** [comment]
This is working. Some how post man does't show the compressed response. We need to test this other than post man
