### ISSUE TITLE
Snake Case Naming in PostgreSQL 

### ISSUE THREAD

**Issue by icecactus** [abpframework/abp#18354]
I am just starting out using this framework and I really like it. EXCEPT for 1 thing so far. The naming in postgres is a real pita. Having to quote everything is ridiculous when interacting with the DB outside entity framework. 

I tried to use the https://github.com/efcore/EFCore.NamingConventions library, which normally works great in other projects. However it doesn't work with this framework. This really should be supported. It would be great to have the option of different casing for the db.  :)

**Comment by EngincanV** [comment]
Actually, this should already be supported, I'll test it and let you know.

**Comment by EngincanV** [comment]
Since we specify the table name for each table, [EFCore.NamingConventions](https://github.com/efcore/EFCore.NamingConventions) could not interfere and convert the table name to snake case.

If you want you can add the following code-block to your `OnModelCreating` method in your db context class and use [`NpgsqlSnakeCaseNameTranslator`](https://www.npgsql.org/doc/api/Npgsql.NameTranslation.NpgsqlSnakeCaseNameTranslator.html):

```csharp
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        /* Include modules to your migration db context */

        builder.ConfigurePermissionManagement();
        //...

       //use NpgsqlSnakeCaseNameTranslator (https://www.npgsql.org/doc/api/Npgsql.NameTranslation.NpgsqlSnakeCaseNameTranslator.html)
        var mapper = new NpgsqlSnakeCaseNameTranslator();
        foreach (var entity in builder.Model.GetEntityTypes())
        {
            foreach (var property in entity.GetProperties())
            {
                var storeObjectIdentifier = StoreObjectIdentifier.Create(property.DeclaringEntityType, StoreObjectType.Table);
                if (storeObjectIdentifier.HasValue)
                {
                    property.SetColumnName(mapper.TranslateMemberName(property.GetColumnName(storeObjectIdentifier.Value)));
                }
            }
                    
            entity.SetTableName(mapper.TranslateTypeName(entity.GetTableName()));
        }
    }
```

Also, you may wanna see https://github.com/npgsql/efcore.pg/issues/21#issuecomment-376114368

**Comment by icecactus** [comment]
Thanks for your quick reply @EngincanV ! This does indeed make everything in the db snake case. Unfortunately, the DbMigrator project no longer works and when you try to run the main web application you get tons of errors. Its looking for camelcase table names. 

for instance, its saying npgsql.postgresexcetption relations "AbpSettings" does not exist

I think i somehow need to set builder.UseSnakeCaseNamingConvention() on all the db contexts. Im not sure how to do that though, nor why the migration works when i do Add-Migration Initial.

**Comment by icecactus** [comment]
I found a solution. Im going to post it here since I have seen quite a few people ask how, but I couldnt find any complete solutions.

Im a c# newb and also just learning this framework so correct me if im doing something wrong.

First, in your modules ConfigureServices(ServiceConfigurationContext context) function, add 

`           options.Configure(opts =>
           {
               opts.UseNpgsql();
               opts.DbContextOptions.UseSnakeCaseNamingConvention();               
           });
`

This will change almost everything. The issue like said above, is that ABP sets the table name in the OnModelCreating function, so the UseSnakeCaseNaming gets overridden. 

To solve that, I created a model builder extensions based on @EngincanV code


```
        public static void ChangeEntitiesToSnakeCase(this ModelBuilder builder)
        {
            //use NpgsqlSnakeCaseNameTranslator (https://www.npgsql.org/doc/api/Npgsql.NameTranslation.NpgsqlSnakeCaseNameTranslator.html)
            var mapper = new NpgsqlSnakeCaseNameTranslator();
            foreach (var entity in builder.Model.GetEntityTypes())
            {
                foreach (var property in entity.GetProperties())
                {
                    var storeObjectIdentifier = StoreObjectIdentifier.Create(property.DeclaringEntityType, StoreObjectType.Table);
                    if (storeObjectIdentifier.HasValue)
                    {
                        property.SetColumnName(mapper.TranslateMemberName(property.GetColumnName(storeObjectIdentifier.Value)));
                    }
                }

                entity.SetTableName(mapper.TranslateTypeName(entity.GetTableName()));
            }
        }
```

You can then override each modules DbContext with your own by using their naming convention so it auto loads, so for instance

```
    public class MySettingManagementDbContext : SettingManagementDbContext
    {
        public MySettingManagementDbContext(DbContextOptions<SettingManagementDbContext> options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            
            builder.ChangeEntitiesToSnakeCase();
        }
    }
```

You have to do that for each module you use.

Then finally, add builder.ChangeEntitiesToSnakeCase(); into your own DbContext so the migrations work correctly.

This appears to solve the issue and relieve my OCD :) Its to bad they couldn't do it another way so that UseSnakeCaseNamingConvention would just work, but at least it seems i can work around.
