### ISSUE TITLE
EntityFrameworkCore.Tests has an error with missing the CollectionDefinitionName of TestConsts.

### ISSUE THREAD

**Issue by jakeuj** [abpframework/abp#18357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

.EntityFrameworkCore.Domains & .EntityFrameworkCore.Applications has an error.

![image](https://github.com/abpframework/abp/assets/834156/6c11295b-0fd5-42cc-88d2-a46fc23e9050)

### Reproduction Steps

`abp new TestCiCd --ui none -csf --preview`

### Expected behavior

Has TestCiCdTestConsts.CollectionDefinitionName for `[Collection(TestCiCdTestConsts.CollectionDefinitionName)]`.

### Actual behavior

Missing `TestCiCdTestConsts.CollectionDefinitionName`.

### Known Workarounds

Copy [MyProjectNameTestConsts](https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.TestBase/MyProjectNameTestConsts.cs) to test project.

![image](https://github.com/abpframework/abp/assets/834156/78dea325-0de9-46c7-a2d3-01a42a11a200)

### Version

8.0.0-RC2

### User Interface

Common (Default) => Need add a new option for `None UI`.

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Fixed by https://github.com/abpframework/abp/pull/18346
