### ISSUE TITLE
how can i disable an interceptor

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#1837]
I want to disable the validation interceptor for example:

```
using (_interceptorManager.Disable<Authorize>())
{
 _appService.GetUsers();
}
```

I have a background worker that sends emails to all users and I need to get the user list. But it gives me access denied due to lack of permissions.

Is this possible? Thank you :)

**Comment by hitaspdotnet** [comment]
You need to create a method (may private) without authorization or use `[AllowAnonymous]`. Getting users data without authorization isn't good idea. So, be careful on what you do.

**Comment by wocar** [comment]
I 

> You need to create a method (may private) without authorization or use `[AllowAnonymous]`. Getting users data without authorization isn't good idea. So, be careful on what you do.

I understand what you are saying however in this case doesn't apply. I have a background worker that notifies users, therefore I need to get the user list. What I did as a workaround is to user the IIdentityRepository, which now makes my module coupled to the IdentityModule by using the repository instead of the appservice. 

I dont know if this might be solved using the user/tenant impersonation approach @hikalkan

**Comment by mehmetuken** [comment]
You can use directly Repository in your job.

**Comment by hikalkan** [comment]
Background jobs should not use application services, which is conceptually a wrong design.
Think that ABP don't provide an authorization interceptor and you have manually checked authorization in the first line of your app service method. How would you disable it for a particular request? It is not easy without an ugly workaround.

Suggestion: Extract the code to another class (not an app service, a domain service or another helper service) and share it among your app service and background job.

**Comment by wocar** [comment]
Thank you, I just wanted to query all the users to get their names and show the “Last Modified By” correctly.

I made the background job use the user repository to do this. This worked because my system is monolithic, if I ever wanted to implement micro services then I’d have to refactor this part. Thank you.

**Comment by msanlisavas** [comment]
A work around: ISessionAppService comes in handy in those situations. Add a hangfire specific user. Give permissions to app service you wanna use. Create hangfire specific functions and call app services like this
` hangfireSpecificFunction(){
_sessionAppService.Use(tenantId,hangfireUserId);
// call the appservice you want
}
`
