### ISSUE TITLE
Add `NormalizedTenantName` to Tenant entity.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#18394]
When resolving tenant names by subdomains, Browsers prefer to use lowercase as subdomain names.

We can add a new property(`NormalizedTenantName`) to solve this. It can always uses uppercase/lowercase.

https://github.com/abpframework/abp/blob/d7502bdee7acfb8d8c2448450b3571bc4aabf927/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/Tenant.cs#L12

Just like the `NormalizedUserName` of `IdentityUser`.

![image](https://github.com/abpframework/abp/assets/6908465/298c0841-7b74-424c-a249-3b4237dc4318)

**Comment by leonkosak** [comment]
@maliming, where is documentation regarding resolving tenants based on subdomain (configuration,...)?

**Comment by maliming** [comment]
hi @leonkosak 

https://docs.abp.io/en/abp/8.0/Multi-Tenancy#domain-subdomain-tenant-resolver
https://github.com/abpio/abp-commercial-docs/pull/600
https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver
