### ISSUE TITLE
[Angular] Login button doesn't appear on navitem in LeptonX Lite theme

### ISSUE THREAD

**Issue by cloud0259** [abpframework/abp#18409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

The login button doesn't appear on the navitem in LeptonX Lite theme when the user is not logged in.
However, there is the component loaded in the list of items
![image](https://github.com/abpframework/abp/assets/6765644/f4d348dc-e60c-41a4-bf6f-317ae0c50f8e)
![image](https://github.com/abpframework/abp/assets/6765644/fc72ec6e-d1e7-47b8-af0c-f61f4c963347)

### Version

7.4.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by Sinan997** [comment]
![image](https://github.com/abpframework/abp/assets/72804437/25ed4c92-1001-45e1-bcaa-44e630b091f0)

i have created a new abp project and it worked fine.

could you give **Reproduction Steps**

**Comment by rqx110** [comment]
@cloud0259 means the login button not exist on the top bar

**Comment by cloud0259** [comment]
Is it possible to change to have the login button in the top bar?
I have create a new component to add on a NavItem and it doesn't work it.
However, I followed the documentation
https://docs.abp.io/en/abp/latest/UI/Angular/Modifying-the-Menu#how-to-add-an-element-to-right-part-of-the-menu
```ts
navItems.addItems([
      {
        id: 'Login',
        order: 1,
        component: LoginMenuComponent,
        visible: () => true
      },     
    ]);
```

**Comment by Sinan997** [comment]
> Is it possible to change to have the login button in the top bar? I have create a new component to add on a NavItem and it doesn't work it. However, I followed the documentation https://docs.abp.io/en/abp/latest/UI/Angular/Modifying-the-Menu#how-to-add-an-element-to-right-part-of-the-menu
> 
> ```ts
> navItems.addItems([
>       {
>         id: 'Login',
>         order: 1,
>         component: LoginMenuComponent,
>         visible: () => true
>       },     
>     ]);
> ```

this feature is supported ThemeBasicModule.

in leptonx you can use `ReplaceableComponentsService`. 
documentation link -> https://docs.abp.io/en/commercial/latest/themes/lepton-x/angular#breadcrumb-component

if you want to add link to navbar -> follow this [documentation](https://docs.abp.io/en/abp/latest/UI/Angular/Modifying-the-Menu#how-to-add-a-navigation-element)
