### ISSUE TITLE
Language status listener method in dynamic-layout needs to be refactor

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#18419]
related https://github.com/abpframework/abp/pull/18418

issue: https://github.com/abpframework/abp/blob/fa50d7e9702479d06ec90b5c5cce7bccb4ae3cb1/npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts#L108

**Comment by mahmut-gundogdu** [comment]
abpLocalize work with localization.instant. It should be observable

**Comment by mahmut-gundogdu** [comment]
after the implementation, I am not sure should wedo it . in the current version, translate pipes works as pure function and when the language changes, mount and unmound all components. Changing language is rare. So maybe we should keeep it as before. I am not sure. Due that.  I didn't merged

**Comment by masum-ulu** [comment]
We can continue like this, listening the changes can be more costly
