### ISSUE TITLE
When switch to Password flow in oauth, it throws an error

### ISSUE THREAD

**Issue by Sinan997** [abpframework/abp#18425]
when i switch from `code flow` to `password flow` i get an error.

i have followed this [documentation](https://docs.abp.io/en/abp/latest/UI/Angular/Authorization).

![image](https://github.com/abpframework/abp/assets/72804437/1eeb8b83-4c65-45a5-8ae3-062315af1ce1)

**Comment by mahmut-gundogdu** [comment]
related https://github.com/abpframework/abp/issues/18128
