### ISSUE TITLE
Remember Me choice doesn't work properly

### ISSUE THREAD

**Issue by Sinan997** [abpframework/abp#18421]
if you didnt switch `Remember me`, It should'nt be logged in when you close browser and open again. 

![rememberMe](https://github.com/abpframework/abp/assets/72804437/a69bade8-a982-45f5-a1a4-d455f9023f8a)

can you check other ui's as well

**Comment by oykuermann** [comment]
This issue only appears on Angular. @Sinan997

**Comment by Sinan997** [comment]
### Need to decide

- The implementation of remember me is differentiates from mvc because angular is SPA.
- When the site refreshed or open in new tab, angular application resets itself. so every time the application resetted, application will check is remember me checked or not.
- We cannot track the browser is it closed or not in angular.


- the user is automatically navigated to login according the 2 strategies below

1. **LocalStorage** || **Cookie**, if the application resets, we have got to logout user if remember_me is not checked.
2. **SessionStorage**, In SessionStorage we can catch the remember_me option even page refreshed. But if the application opened in new tab sessionStorage resetted. 

### Change the behavior of Remember me option
Normally, we are refreshing the access_token via refresh_token if the token expires.

- If the remember me is not checked, dont set refresh_token. if the access_token expires then navigate to the login page.
- if the remember me is checked. set refresh token and behave normally.

**Comment by gterdem** [comment]
I think this can be handled by adding a `RememberMe` property to cookie (or session storage). 
If it is set to **true**, you can set the `refresh_token`, otherwise don't keep the `refresh_token` in the storage.

Though, the `access_token` lifetime should be short, like 8-12 hours.
