### ISSUE TITLE
Update abp.io 8.0 final with Blazorise 1.4 (full .net 8.0 support)

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#18427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Blasorise 1.4 just landed. Will you be updating abp.io 8.0 with this version? What matters most is that its fully SSR enabled!

https://blazorise.com/news/release-notes/140

### Describe the solution you'd like

Next abp.io veraion updated with Blazorise 1.4

**Comment by realLiangshiwei** [comment]
Ok, we will
