### ISSUE TITLE
The latest BookStore Sample cannot run

### ISSUE THREAD

**Issue by forestaiste** [abpframework/abp#1843]
The lasts BookStore in samples cannot run. Started from VS 2019, the browser shows "localhost is currently unable to handle this request". And the TestController cannot be reached. However, the previous version works well. The module generated with Startup Templates has the same issue.

**Comment by forestaiste** [comment]
The root cause was got finally. The connection string is invalid. However, no exception was thrown out. It is hard to find for a beginner of the framework.

**Comment by maliming** [comment]
Usually you can find detailed errors in the log file.
