### ISSUE TITLE
Oracle database migration fail

### ISSUE THREAD

**Issue by thaohp2238** [abpframework/abp#18450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I try ABP 8.0.0-rc.3, it throw error when running migration:
[15:58:28 INF] Creating initial migration...
ABP CLI 8.0.0-rc.3
Creating initial migrations...
Creating initial migrations process is failed! Details:
Build started...
Build succeeded.
Unable to create a 'DbContext' of type ''. The exception 'Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

Migrations failed! A migration command didn't run successfully.
Migrations failed! A migration command didn't run successfully.
System.Exception: Migrations failed! A migration command didn't run successfully.
   at Volo.Abp.Cli.Commands.CreateMigrationAndRunMigratorCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\CreateMigrationAndRunMigratorCommand.cs:line 68
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 169
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 77

D:\Data\Source\ABPFramework\ABP8\Oracle\MyCompany.Cts\src\MyCompany.Cts.DbMigrator\bin\Debug\net8.0\MyCompany.Cts.DbMigrator.exe (process 21820) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

### Version

8.0.0-rc.3

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi,

Oracle just supported NET8 4 days ago:  https://www.nuget.org/packages/Oracle.EntityFrameworkCore#versions-body-tab

**Comment by thaohp2238** [comment]
Hello,
Could you please update nuget packages?
Thanks,

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/pull/18452
