### ISSUE TITLE
Move Operation in Organization Units not work

### ISSUE THREAD

**Issue by maariaaruiz** [abpframework/abp#18471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The functionality to move an organizational unit is not working.

Should be the component not recognize the click

### Reproduction Steps

![image](https://github.com/abpframework/abp/assets/44084882/67f10cd3-a653-4b81-b8fc-12a977d11d8b)

Not allow to select any

![image](https://github.com/abpframework/abp/assets/44084882/18aee32b-c01e-448d-a8cc-fdc7ad49eb7b)

Even if I click on save, it does nothing.

### Expected behavior

That allows the organizational unit to move

### Version

7.4.3

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please create a support ticket on https://support.abp.io/

Thanks.
