### ISSUE TITLE
Suggestion: AsNoTracking() for default GetAsync and GetListAsync implementations

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#1848]
Since the entities from CrudAppServiceBase.GetAsync and CrudAppServiceBase.GetListAsync do not get modified EF Core does not have to track their changes. Adding AsNoTracking() will result in EF Core not tracking these changes and hence result in faster execution.

For more information see:
https://docs.microsoft.com/en-us/ef/core/querying/tracking

Proposed change:
```cs
public virtual async Task<PagedResultDto<TGetListOutputDto>> GetListAsync(TGetListInput input)
{
    await CheckGetListPolicyAsync();

    var query = CreateFilteredQuery(input)
                            .AsNoTracking(); // add here or maybe even in CreateFilteredQuery()?

    var totalCount = await AsyncQueryableExecuter.CountAsync(query);

    query = ApplySorting(query, input);
    query = ApplyPaging(query, input);

    var entities = await AsyncQueryableExecuter.ToListAsync(query);

    return new PagedResultDto<TGetListOutputDto>(
        totalCount,
        entities.Select(MapToGetListOutputDto).ToList()
     );
}

// do same for GetAsync
```

There is one problem: this requires a reference to Microsoft.EntityFrameworkCore (since this is obviously EF Core specific) which we do not want in the application layer. So this needs to abstracted away.

This could also be a breaking bug for some consumers.

**Comment by maliming** [comment]
> So this needs to abstracted away.

Just like `IAsyncQueryableExecuter`, it also abstracts the functions of EF Core such as `ToListAsync`.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Threading/Volo/Abp/Linq/IAsyncQueryableExecuter.cs#L11


However, we can also override the `CreateFilteredQuery` method to return an `NoTracking` collection of entities through a custom repository method.

**Comment by hikalkan** [comment]
Related to https://github.com/abpframework/abp/issues/355

**Comment by Trojaner** [comment]
There are more ways of controlling tracking and I suggest including these in the abstraction.

For example, EF Core provides the Attach() method to track entities (which allows to update entities without having to query them).

There is also the EntityState property which allows even more control over entities, like detaching them. However I couldn't think of a use case where manually detaching would be useful (maybe calling SaveChanges multiple times? Does EF Core update EntityState to Unchanged after SaveChanges?).

See [Attach Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.attach?view=efcore-3.0) and [EntityState Docs](https://docs.microsoft.com/en-us/dotnet/api/system.data.entitystate?view=netframework-4.8) for more information on EF Core tracking.

**Comment by olicooper** [comment]
Are there any updates on this? In my project I have found that background services/jobs require features like this to maximise performance and using Attach() to avoid having to load entities when we already know the Id's of the entities we need to update is really useful.

**Comment by muratyuceer** [comment]
We have same problem, to abstract it maybe it can be done like with create IRepositoryProviderQueryOptions and store options as key value which implement class can take them from ctor and pass to optionally repo queryable methods. Check if asnotracking key value exist apply it to ef core repo methods, ignore for mongo etc..

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/17487
