### ISSUE TITLE
abp version 7.4.4 Remote server returns '403-Forbidden'. Message: Pro templates require an active commercial license.

### ISSUE THREAD

**Issue by wangyue20075** [abpframework/abp#18480]
abp 7.4.4, run abp new Acme.BookStore -u angular -dbms MySQL -csf 

Error occured while getting the latest version from https://abp.io/api/download/template/get-version/ : Remote server returns '403-Forbidden'. Message: Pro templates require an active commercial license.
The remote service is currently unavailable, please specify the version.

Find the following template in your cache directory:
        Template Name   Version
        app             7.3.0
        app             7.3.2
        module          7.0.3
        module          7.1.0
        module          7.3.0
        module          7.3.2
        module          7.3.3
        module          7.4.3

Use command: abp new Acme.BookStore -v version

**Comment by maliming** [comment]
Can you try again?

**Comment by wangyue20075** [comment]
![2023-12-16_102620](https://github.com/abpframework/abp/assets/4567121/198d20fb-6210-45ff-a0d1-7115dcf751fb)

**Comment by maliming** [comment]
You can add the `-t app` parameter to specify the template type.

`abp new Acme.BookStore -t app -u angular -dbms MySQL -csf`

If you want create the pro template you can try to logout and login again.

**Comment by wangyue20075** [comment]
> You can add the `-t app` parameter to specify the template type.
> 
> `abp new Acme.BookStore -t app -u angular -dbms MySQL -csf`
> 
> If you want create the pro template you can try to logout and login again.

success, thinks
