### ISSUE TITLE
abp generate-proxy -t ng command does not work

### ISSUE THREAD

**Issue by letienhoang** [abpframework/abp#18490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/abpframework/abp/assets/105542197/f621f3e0-628f-47ef-855c-d469130c422b)
![image](https://github.com/abpframework/abp/assets/105542197/60c56a12-c5d0-469f-9c3d-050070b801de)

### Version

6.0.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by mahmut-gundogdu** [comment]
Could you  share the minimal steps that we be able to produce the bug?

**Comment by letienhoang** [comment]
I Run project asp 
then run terminal abp generate-proxy -t ng
but it generate 2 file generate-proxy.json and README.md

**Comment by letienhoang** [comment]
Ohhh, I reinstalled the appropriate cli version and it worked
Thank you
