### ISSUE TITLE
Abp.IdentityServer Module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#185]
#### Volo.Abp.IdentityServer.Domain

Create Volo.Abp.IdentityServer.Domain based on https://github.com/IdentityServer/IdentityServer4.EntityFramework, but not including DbContext related stuff

- [x] Entities
- [x] Stores & Repositories
- [x] Use composite keys for sub-entities and revise all entities.

#### Volo.Abp.IdentityServer.EntityFrameworkCore

Create Volo.Abp.IdentityServer.EntityFrameworkCore based on Volo.Abp.IdentityServer.Domain and EF Core to implement repositories defined in Domain using EF DbContext. Again, use IdentityServer4.EntityFramework as an implementation reference.

- [x] DbContext

### Goals

* Act as Single Sign On / OpenId Connect Server.
* Based on Abp.Identity & Abp.Account modules.

### The Admin UI

https://www.identityserver.com/documentation/admin-ui/

Check database and UI of this project

### Questions..?

- Application?

### Resources

Check these implementations:

* Take Auth0 as example: http://auth0.com
* https://developer.okta.com/

**Comment by Goxiaoy** [comment]
Hi, 
I want to know is there any plan for creating admin-ui module for Volo.Abp.IdentityServer module?
Just like
[https://www.identityserver.com/products/adminui](https://www.identityserver.com/products/adminui)
[https://github.com/skoruba/IdentityServer4.Admin](https://github.com/skoruba/IdentityServer4.Admin)
[https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI](https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI)

**Comment by hikalkan** [comment]
No plan to create a free module for the UI part.

**Comment by GFoley83** [comment]
https://github.com/skoruba/IdentityServer4.Admin
https://github.com/brunohbrito/JPProject.IdentityServer4.AdminUI

Couldn't either of these solutions technically be included with ABP though? 
E.g. as an `AbpModule`? 
Or even just run separately but using the ABP Identity Db.

**Comment by hikalkan** [comment]
I don't know, but they probably work since they are for any asp.net core application.
