### ISSUE TITLE
Volo.Abp.EntityFrameworkCore.Oracle version missmatch

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#18514]
The error when trying to create migrations:
![image](https://github.com/volosoft/volo/assets/25867/9b5549f8-f206-4ff8-a03b-32fa67dbc222)

We don't provide version in https://github.com/abpframework/abp/blob/a5b61905cdcecc5186b71d15091d606065470417/framework/src/Volo.Abp.EntityFrameworkCore.Oracle/Volo.Abp.EntityFrameworkCore.Oracle.csproj#L25

but I think the [Volo.Abp.EntityFrameworkCore.Oracle](https://www.nuget.org/packages/Volo.Abp.EntityFrameworkCore.Oracle/8.0.0-rc.3#dependencies-body-tab) dependency should be updated to [Oracle.EntityFrameworkCore 8](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/8.21.121). 

@maliming What do you think?

**Comment by maliming** [comment]
We have upgraded it.

https://github.com/abpframework/abp/pull/18452
