### ISSUE TITLE
Npgsql.EntityFrameworkCore.PostgreSQL 8.0.0 Incorrect Time Returns

### ISSUE THREAD

**Issue by JadynWong** [abpframework/abp#18528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`Npgsql.EntityFrameworkCore.PostgreSQL` 8.0.0 has a problem with time, always returning the time of `Kind=Utc`. Even if `EnableLegacyTimestampBehavior` has been set.

https://github.com/npgsql/npgsql/issues/5465

### Reproduction Steps

- abp new BookStore -t app --dbms PostgreSQL
- login the app
- update any user
- go to /swagger
- invoke get /api/identity/users/
- check changed user's `lastModificationTime`

### Expected behavior

The value should be `2023-12-20T04:00:00.00Z`

### Actual behavior

The value is `2023-12-20T012:00:00.00Z`

### Known Workarounds

When encountering this issue, try adding the `npgsql` 8.0.1 package to *.EntityFramework. This will fix it!

### Version

8.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Thanks @JadynWong 

We will update the `Npgsql.EntityFrameworkCore.PostgreSQL` to the latest when it releases new version.

https://github.com/abpframework/abp/issues/18193

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/18193
