### ISSUE TITLE
enter add-module CLI appearance error

### ISSUE THREAD

**Issue by sonhoang23** [abpframework/abp#18542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i run CL example: abp add-module Volo.CmsKit  --with-source-code --add-to-solution-file --skip-db-migrations 

apprear a lot of erre 

example:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Volo.Abp.EventBus;Volo.Abp.EventBus;Volo.Abp.EventBus.	Volo.CmsKit.Public.Application.Contracts	D:\Abp\v8\New folder\Booky.BE\modules\Volo.CmsKit\src\Volo.CmsKit.Public.Application.Contracts\Volo.CmsKit.Public.Application.Contracts.csproj	1	

### Version

8.0.0

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
See: https://github.com/abpframework/abp/issues/18565
