### ISSUE TITLE
Abp8.0 MinioBlobProvider's  BlobExistsAsync has a bug  

### ISSUE THREAD

**Issue by wallee85** [abpframework/abp#18550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

abp8 udpated the minio client to 6.0.1,but there is a breaking changes in minio-dotnet package's  StatObjectAsync.this method would throw a ObjectNotFoundException originally and now it wouldn't in the same situation....by now there are some issue about this problem in minio-dotnet github repo,but can not see any response from the official .
relevant:thttps://github.com/minio/minio-dotnet/issues/953

### Reproduction Steps

#abp minioblobprovider's blobexistsasync is here:
protected override async Task<bool> BlobExistsAsync(IMinioClient client, string containerName, string blobName)
{
	// Make sure Blob Container exists.
	if (await client.BucketExistsAsync(new BucketExistsArgs().WithBucket(containerName)))
	{
		try
		{
			var statObjectArgs = new StatObjectArgs().WithBucket(containerName).WithObject(blobName);
			await client.StatObjectAsync(statObjectArgs);
		}
		catch (Exception e)//can not catch anything acturally due to the StatObjectArgs in minio-dotnet 6.0.1 not throw exceptions when the object doesn't exists.
		{
			if (e is ObjectNotFoundException)
			{
				return false;
			}

			throw;
		}

		return true;
	}

	return false;
}

### Expected behavior

same as before

### Version

8.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
We will be waiting for the https://github.com/minio/minio-dotnet/issues/953

**Comment by wallee85** [comment]
> We will be waiting for the [minio/minio-dotnet#953](https://github.com/minio/minio-dotnet/issues/953)

this issue is closed as completed

**Comment by maliming** [comment]
hi

We need to wait for the new package on Nuget.
