### ISSUE TITLE
IdentityServer CurrentUser is null

### ISSUE THREAD

**Issue by cocosip** [abpframework/abp#18552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Upgrade ABP from 7.2.2 to 8.0.0 , get api `/api/abp/application-configuration` current user is null

 

```json
"currentUser": {
		"isAuthenticated": false,
		"id": null,
		"tenantId": null,
		"impersonatorUserId": null,
		"impersonatorTenantId": null,
		"impersonatorUserName": null,
		"impersonatorTenantName": null,
		"userName": "admin",
		"name": null,
		"surName": null,
		"email": null,
		"emailVerified": false,
		"phoneNumber": null,
		"phoneNumberVerified": false,
		"roles": []
	},
```

### Version

8.0.0-rc.1~8.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by cocosip** [comment]
Try print claim type

```c#
   var claims = _currentPrincipalAccessor.Principal.Claims.ToList();
   foreach (var claim in claims)
   {
       Logger.LogInformation("Type:{Type},Value:{Value}", claim.Type, claim.Value);
   }
```

7.2.2 Claims
![claimType老](https://github.com/abpframework/abp/assets/9337837/6d76c380-9006-46f9-af11-29c1b6e3a726)

8.0.0 Claims
![claimType新](https://github.com/abpframework/abp/assets/9337837/15a8da0c-e92b-49c3-9c09-c0a7f01c06fb)

**Comment by BirajMainali** [comment]
Facing the same issue in  on 7.4.1
```csproj
<TargetFramework>net7.0</TargetFramework>

```

**Comment by ShawnRom** [comment]
> Facing the same issue in  on 7.4.1
> 
> ```csproj
> 
> <TargetFramework>net7.0</TargetFramework>
> 
> 
> 
> ```

I also encountered it. How to solve it?

**Comment by myall200** [comment]
I also encountered it. How to solve it?

**Comment by myn1ckname** [comment]
I have the same problem. ABP version 8.0.5, net8.0. I noticed that this depends on the `Microsoft.AspNetCore.Authentication.JwtBearer` package. If you use `7.0.17` everything works as before, if `8.0.3` then the CurrentUser is empty.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/18895#issuecomment-1993588224

**Comment by YoussofAshraf** [comment]
Hello @maliming  this solution you mentioned [here](https://github.com/abpframework/abp/issues/18895#issuecomment-1993588224) works fine If I am using EfCore For `MSSQL` but it still return  
```Json
"currentUser": {
		"isAuthenticated": false,
		"id": null,
		"tenantId": null,
		"impersonatorUserId": null,
		"impersonatorTenantId": null,
		"impersonatorUserName": null,
		"impersonatorTenantName": null,
		"userName": "admin",
		"name": null,
		"surName": null,
		"email": null,
		"emailVerified": false,
		"phoneNumber": null,
		"phoneNumberVerified": false,
		"roles": []
	},
```
When I use EfCore For `PostgreSQL` 
Version of Abp `8.0.5`

**Comment by maliming** [comment]
hi @YoussefRashed 

Can you share a simple project?

**Comment by YoussofAshraf** [comment]
@maliming  Thanks For your Attention ❤️ But  Sorry `it Works` ! I missed this Line on my ***PostgresHostModule***
```Cs
  options.MapInboundClaims = false;
```
