### ISSUE TITLE
Projects that use central package version management should not define the version on the PackageReference

### ISSUE THREAD

**Issue by zaktecs** [abpframework/abp#18565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Attempting to switch the theme to my custom theme. I followed the same process I used with Abp Version 7 without any issues. However, upon creating a solution with Version 8 and incorporating the theme module, I encounter the following error.

Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy;Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.	Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic	\modules\Volo.BasicTheme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic\Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.csproj	1	

### Reproduction Steps

Add the basic theme module to app  

abp add-module Volo.BasicTheme --with-source-code --add-to-solution-file

### Expected behavior

Should able to change theme

### Actual behavior

Attempting to switch the theme to my custom theme. I followed the same process I used with Abp Version 7 without any issues. However, upon creating a solution with Version 8 and incorporating the theme module, I encounter the following error.

Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy;Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.	Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic	\modules\Volo.BasicTheme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic\Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.csproj	1	

### Regression?

YES

### Version

8.0

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

You can add a `Directory.Packages.props` file to the `modules` folder.

https://github.com/abpframework/abp/blob/dev/templates/Directory.Packages.props

**Comment by zaktecs** [comment]
Thanks @maliming. The initial error is gone now, but I'm now getting the fiollowing error

Severity	Code	Description	Project	File	Line	Suppression State
Error	**MSB4018	The "GenerateStaticWebAsssetsPropsFile" task failed unexpectedly.**
Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Pack.targets	136

**Comment by maliming** [comment]
hi

We will use `VersionOverride`. : )  I'm changing the CLI.



<img width="1023" alt="image" src="https://github.com/abpframework/abp/assets/6908465/a223ae48-ead1-4840-aac1-8876cf1b2b39">

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/18565

**Comment by zaktecs** [comment]
@maliming thanks for your support, but using overriding the version didn't solve my problem with 
Error MSB4018 The "GenerateStaticWebAsssetsPropsFile" task failed unexpectedly. Please see attached .proj
![VersionOverride2023-12-25 020109](https://github.com/abpframework/abp/assets/10104562/38e453a2-dd5e-41d6-b797-60d0c9bdbc33)

**Comment by maliming** [comment]
hi

You don't need the `ManagePackageVersionsCentrally` anymore.
