### ISSUE TITLE
Task.Run AppService

### ISSUE THREAD

**Issue by laosandegudai** [abpframework/abp#18578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 have a time-consuming asynchronous service that I want to return directly on request without waiting for the result of subsequent processing. I use the Task.Run implementation, but I always get an exception like,
`System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.` 

I knew it was a life cycle problem, so I used the  ``IServiceScopeFactory` ,but it was still the same error.

## BackController
```csharp
  [RemoteService(Name = "back")]
  [Route("api/back")]
  public class BackController : BookStoreController
  {
      private readonly IBackAppService _backAppService;
      private IServiceScopeFactory _serviceScopeFactory;
      public BackController(IBackAppService backAppService, IServiceScopeFactory serviceScopeFactory)
      {
          _backAppService = backAppService;
          _serviceScopeFactory = serviceScopeFactory;
      }

      [HttpGet]
      public async Task<IActionResult> NoWaitAsync()
      {

          _ = Task.Run(async () =>
          {
              try
              {
                  using var scopeService = _serviceScopeFactory.CreateAsyncScope();
                  {
                      var _backAppService2 = scopeService.ServiceProvider.GetService<IBackAppService>();
                      await _backAppService2.NoWaitAsync();
                  }

              }
              catch (Exception ex)
              {
                  Debug.WriteLine($"BackException:-------------{ex}");
              }

          });

          return Ok();

      }

  }
```
## BackAppService
```csharp
 [RemoteService(false)]
 public class BackAppService : IBackAppService
 {
     private IdentityUserManager _userManager;

     public BackAppService(IdentityUserManager userManager)
     {
         _userManager = userManager;
     }

     public async Task NoWaitAsync()
     {
         try
         {
             Debug.WriteLine("Back Start");
             await Task.Delay(5 * 1000);
             var user = await _userManager.FindByNameAsync("admin");
             user.Name = "Back";
             await _userManager.UpdateAsync(user);
             Debug.WriteLine("Back End");
         }
         catch (Exception ex)
         {

             Debug.WriteLine($"BackService:------------- {ex} ");
         }

     }
 }
```

### Expected behavior

I just wanted to run a time-consuming background task that didn't require persistence or repetition, so I didn't use the `backgroundworker`.

### Version

5.3.5

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
I don't think your way is correct. but you can try to use `IRootServiceProvider `.

**Comment by laosandegudai** [comment]
> I don't think your way is correct. but you can try to use `IRootServiceProvider `.

yes,I search it ,but it does not exist 5.3.5.

**Comment by maliming** [comment]
You can copy the code of `RootServiceProvider` and use it in your project.

**Comment by laosandegudai** [comment]
> You can copy the code of `RootServiceProvider` and use it in your project.

ok,i understand.

**Comment by laosandegudai** [comment]
> You can copy the code of `RootServiceProvider` and use it in your project.

Great, it's correct.
I used the wrong root container
