### ISSUE TITLE
Use the `abp generate-proxy` command to report an error when the interface return type is generic

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#18579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Use the `abp generate-proxy` command to report an error when the interface return type is generic.

### Reproduction Steps

Defines an interface whose return type is generic, This is the interface code:
```
    public class BookCategorieAppService : BookStoreAppService
    {
        public Task<List<NameValue<Guid>>> GetOptionsAsync()
        {
            return Task.FromResult(new List<NameValue<Guid>>
            {
                new NameValue<Guid> { Name = "传记类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "政治类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "历史类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "小说类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "科普类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "艺术类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "哲学类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "游记类", Value = GuidGenerator.Create() },
                new NameValue<Guid> { Name = "心理类", Value = GuidGenerator.Create() }
            });
        }
    }
```

Execute the following command:
> abp generate-proxy -t ng -url https://localhost:44390 -m app

This is the error message:
![image](https://github.com/abpframework/abp/assets/35516482/fe3a6e95-fe73-43b0-9c0e-25d20c748c1c)

### Version

7.4.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by sumeyyeKurtulus** [comment]
Hello @ArcherTrister, [this issue](https://github.com/abpframework/abp/issues/20172) should have resolved your problem 🙌

**Comment by ArcherTrister** [comment]
Hello @sumeyyeKurtulus, When I updated to version 8.2.0 it solved my problem, thank you very much!
