### ISSUE TITLE
After 7.4 to 8.0 Upgrade, Migration Failed Because of OpenIddict Upgrade

### ISSUE THREAD

**Issue by omer-yel** [abpframework/abp#18581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Existing project from 7.4 to 8.0 upgraded by following  below links` articles
https://docs.abp.io/en/commercial/8.0/migration-guides/v8_0
https://docs.abp.io/en/abp/8.0/Migration-Guides/Abp-8_0
https://community.abp.io/posts/upgrade-your-existing-projects-to-.net-8-abp-8.0-x0n7hiqr

Implemented property name change
![image](https://github.com/abpframework/abp/assets/151017919/66ae4d18-43db-4334-9102-e18d63a8408a)

After upgrade, was not changed anything. Was tried to add migration as explained below link.
https://docs.abp.io/en/abp/8.0/Migration-Guides/OpenIddict4-to-5
After adding migration update database command executed. But failed.

![image](https://github.com/abpframework/abp/assets/151017919/359eba71-aa84-480f-86a4-3893716dae02)

Above image error occurred.

### Version

8.0

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Please share the full logs. Thanks.

**Comment by omer-yel** [comment]
> PM> Update-Database
Both Entity Framework Core and Entity Framework 6 are installed. The Entity Framework Core tools are running. Use 'EntityFramework6\Update-Database' for Entity Framework 6.
Build started...
Build succeeded.
[09:27:28 INF] Starting web host.
Applying migration '20231225070040_Added_Customer'.
Failed executing DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
EXEC sp_rename N'[OpenIddictApplications].[Type]', N'ClientType', N'COLUMN';
Microsoft.Data.SqlClient.SqlException (0x80131904): Either the parameter @objname is ambiguous or the claimed @objtype (COLUMN) is wrong.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:19fcaba2-3b2e-460f-a112-486b82429e34
Error Number:15248,State:1,Class:11
Either the parameter @objname is ambiguous or the claimed @objtype (COLUMN) is wrong.
PM> 

Package manager console output is above 

I could not get meaning of full log. Where can i get full log?

**Comment by maliming** [comment]
Can you share a project that can reproduce the problem? I think the log has nothing to do with openiddict.

**Comment by omer-yel** [comment]
I have sent project files via email with subject same as issue title. Please consider to check email.

**Comment by maliming** [comment]
hi

I downloaded your project.

Then update abp and Microsoft package to 8.0, also change the `net7.0` to `net8.0`

and add new migrations and update the database.

Everything works.

```
Build started...
Build succeeded.
Applying migration '20231202143651_Initial'.
Applying migration '20231202144234_Added_Country'.
Applying migration '20231202144352_Added_City'.
Applying migration '20231202145339_Updated_City_23120217532836'.
Applying migration '20231202145448_Added_District'.
Applying migration '20231202145553_Updated_District_23120217554124'.
Applying migration '20231202153745_Added_Branch'.
Applying migration '20231204095622_Branch_Code_Name_Unique'.
Applying migration '20231205152934_Updated_Branch_23120518292072'.
Applying migration '20231205154811_Updated_Branch_23120518475803'.
Applying migration '20231205160523_Added_ConditionType'.
Applying migration '20231205160717_Added_Condition'.
Applying migration '20231205163255_Updated_Branch_23120519324186'.
Applying migration '20231205163941_Updated_Branch_23120519392781'.
Applying migration '20231206091057_Updated_Country_23120612103970'.
Applying migration '20231212063813_Added_Department'.
Applying migration '20231212064617_Updated_Department_23121209460254'.
Applying migration '20231212065137_Added_Title'.
Applying migration '20231212065800_Updated_Title_23121209574489'.
Applying migration '20231212065908_Updated_Department_23121209585255'.
Applying migration '20231212134646_Added_Person'.
Applying migration '20231212140734_Updated_Person_23121217071959'.
Applying migration '20231212141244_Added_PersonIdentificationInfo'.
Applying migration '20231213073352_One-To-One-RelationWithPerson_PersonInfo'.
Applying migration '20231213084750_Updated_City_23121311472508'.
Applying migration '20231213085548_Updated_Person_23121311552709'.
Applying migration '20231213091121_Updated_PersonIdentificationInfo_23121312110740'.
Applying migration '20231213102445_Person_PersonInfo_Relation'.
Applying migration '20231213103122_Updated_PersonIdentificationInfo_23121313310625'.
Applying migration '20231213111706_Updated_PersonIdentificationInfo_23121314165083'.
Applying migration '20231213112230_Updated_Person_23121314221332'.
Applying migration '20231213114934_Updated_Person_23121314491791'.
Applying migration '20231213115138_Updated_PersonIdentificationInfo_23121314512138'.
Applying migration '20231213231843_Updated_PersonIdentificationInfo_23121402182592'.
Applying migration '20231214074709_OneToOne_Person_PersonInfo'.
Applying migration '20231214113822_PersonId_PersonIdentiId_columnsRemoved'.
Applying migration '20231215085617_Added_Employee'.
Applying migration '20231215085835_Updated_Employee_23121511581572'.
Applying migration '20231215110532_Person_One-To-One_Employee'.
Applying migration '20231215111517_Person-M_One-to-One_Employee-C'.
Applying migration '20240104065736_OpenIddict'.
Done.
```


```
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AizonaiTemp.Migrations
{
    /// <inheritdoc />
    public partial class OpenIddict : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "Type",
                table: "OpenIddictApplications",
                newName: "ClientType");

            migrationBuilder.AddColumn<string>(
                name: "ApplicationType",
                table: "OpenIddictApplications",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "JsonWebKeySet",
                table: "OpenIddictApplications",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Settings",
                table: "OpenIddictApplications",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "EntityId",
                table: "AbpEntityChanges",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(128)",
                oldMaxLength: 128);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ApplicationType",
                table: "OpenIddictApplications");

            migrationBuilder.DropColumn(
                name: "JsonWebKeySet",
                table: "OpenIddictApplications");

            migrationBuilder.DropColumn(
                name: "Settings",
                table: "OpenIddictApplications");

            migrationBuilder.RenameColumn(
                name: "ClientType",
                table: "OpenIddictApplications",
                newName: "Type");

            migrationBuilder.AlterColumn<string>(
                name: "EntityId",
                table: "AbpEntityChanges",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(128)",
                oldMaxLength: 128,
                oldNullable: true);
        }
    }
}

```

**Comment by maliming** [comment]
You can compare your old and new changes via Git.

**Comment by omer-yel** [comment]
There is an sql backup file of production database. Backup latest version of db before .net 8. We have got error while trying to add .net 8 update migration and updating database. 
Please restore db from backup file. Than try to upgrade to .net 8 and add migration.

**Comment by maliming** [comment]
hi

Your `project_dbfile.sql` already uses the 8.0 columns of OpenIddict. Which means your database and your migration files are inconsistent.

<img width="1152" alt="image" src="https://github.com/abpframework/abp/assets/6908465/abfb35c4-53ed-49da-b4a7-1b68d48de303">

**Comment by omer-yel** [comment]
Db is used by several developers.  This error might occurred because of upgrading abp at the same time. Thanks for your help.
