### ISSUE TITLE
Remove AbpAuthorizationServiceCollectionExtensions.AddAlwaysAllowPermissionChecker

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#1861]
It is obsolete and will be removed. Use AddAlwaysAllowAuthorization instead.

@maliming please remove it then run build-all.ps1 to check if it is used in any module (I am almost sure that it is not used but it is good to check :)

**Comment by maliming** [comment]
This method has not been used by other modules. The framework and modules have been rebuild and the strings(`AddAlwaysAllowPermissionChecker `) have been globally searched.

**Comment by hikalkan** [comment]
Awesome!
