### ISSUE TITLE
Entity Versioning

### ISSUE THREAD

**Issue by hishamco** [abpframework/abp#18614]
Is there a mechanism to version the entities in ABP Framework? I saw `IHasEntityVersion` which increments the version number, but I didn't see any versioning for the entity data. I didn't see any value for such interface or did I miss something?

**Comment by maliming** [comment]
hi

The `IHasEntityVersion` is designed to mark if the entity has changed. it used by `EntitySynchronizer`


https://github.com/abpframework/abp/blob/054bad8914382a1c2ef9c672d631114b591473ff/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/Distributed/EntitySynchronizer.cs#L159

**Comment by gdlcf88** [comment]
https://docs.abp.io/en/abp/latest/Entities#versioning-entities
https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#entity-synchronizer

**Comment by hishamco** [comment]
@maliming could `EntitySynchronizer` helps to get the versions for the a particular entity?

@gdlcf88 I already saw the docs before I submit my question

Thanks anyway

**Comment by maliming** [comment]
It can't help, It is just a value to compare whether the two entities are the `same`.

**Comment by hishamco** [comment]
So that means I need to implement the versioning myself

Thanks anyway
