### ISSUE TITLE
ABP commertial support of 4.2 in .net core 7

### ISSUE THREAD

**Issue by nayanranjane** [abpframework/abp#18615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Can we use entire abp.comertial version project which is in 4.2 can we use this all volo libraries in .net core 7

### Describe the solution you'd like

I have .net 5.0 project which is using abp 4.2 libraries now i want to upgrade my project to 7.0 but want to used old structure of abp modules that I have kept in shared is there any issue to do that

**Comment by maliming** [comment]
Please create a support ticket on https://support.abp.io/

Thanks.
