### ISSUE TITLE
The entity type 'ExtraPropertyDictionary' requires a primary key to be defined

### ISSUE THREAD

**Issue by cocosip** [abpframework/abp#18620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The entity type 'ExtraPropertyDictionary' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.

### Reproduction Steps

```c#
 var query = (await QueryProxyInfoRepository.GetQueryableAsync())
     .WhereIf<QueryProxyInfo>(!input.Name.IsNullOrWhiteSpace(), item => item.Name.Contains(input.Name));

 var count = await AsyncExecuter.CountAsync(query);
 var queryProxyInfos = await AsyncExecuter.ToListAsync(
     query.OrderBy(input.Sorting ?? nameof(QueryProxyInfo.Id))
     .Skip(input.SkipCount)
     .Take(input.MaxResultCount));
 var dtos = ObjectMapper.Map<List<QueryProxyInfo>, List<QueryProxyInfoDto>>(queryProxyInfos);
```

```c#
 builder.Entity<QueryProxyInfo>(b =>
 {
     b.ToTable(KayiImageServerConsts.DbTablePrefix + "QueryProxyInfos", KayiImageServerConsts.DbSchema);
     b.ConfigureByConvention(); //auto configure for the base class props

     b.Property(p => p.Name).IsRequired().HasMaxLength(QueryProxyInfoConsts.MaxNameLength);
     b.Property(p => p.HttpQueryForward).IsRequired();
     b.Property(p => p.QuerierId).IsRequired();
     b.Property(p => p.EnableSecondQuerier).IsRequired();
     b.Property(p => p.SecondQuerierId).IsRequired(false);
     b.Property(p => p.Description).HasMaxLength(QueryProxyInfoConsts.MaxDescriptionLength);

 });
```

### Version

8.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

When use IRepository<QueryProxyInfo, Guid> QueryProxyInfoRepository to query data, it will get the error

**Comment by cocosip** [comment]
I deleted all the Migration files and generated new ones, and the problem was magically solved. However, there will be a problem that the historical data cannot be migrated to the new version.

**Comment by maliming** [comment]
hi

I think there is an error in your migration. This is not the scope of abp.

**Comment by cocosip** [comment]
> hi
> 
> I think there is an error in your migration. This is not the scope of abp.

It seems that there are some minor issues with the compatibility of the related libraries after upgrading EF Core to 8.0.
