### ISSUE TITLE
Permission check failed in Distributed EventHandler

### ISSUE THREAD

**Issue by kaleyroy** [abpframework/abp#1862]
Assuming i have an application service: **OrderAppService**
`  [Authorize(OrderManagementPermissions.Orders.Default)]
    public class OrderAppService : ApplicationService, IOrderAppService {}`

When an order is created, i would publish an event: **OrderCreatedEvent** and registered an event handler for this. When the event handler is executed, i call **OrderAppSevice** to get current order information, but it throws an exception

> Authorization failed! Given policy has not granted: OrderManagement.Order

`public async Task HandleEventAsync(OrderCreatedEventData eventData)
{
    var user = _currentUser;
    try
    {
        var order = await _orderAppService.GetAsync(eventData.OrderId);
    }
    catch (Exception ex)
    {
    }
}`

I have noticed that the _currentUser (**ICurrentUser**) is not avaliable in event handler, it can't fetch the current user id/name etc .. the **ICurrentPrincipalAccessor** also null either.

So i think in the event handler **_we can not get the current user_** properly, that causes the permission check  process not working as expected?

Any suggestions?  How to get this work?

**Comment by maliming** [comment]
> When the event handler is executed, i call OrderAppSevice to get current order information

**Do not call the application service method in the event handler.**

You can do your work in the domain service. can use any userid directly.

**Comment by kaleyroy** [comment]
> > When the event handler is executed, i call OrderAppSevice to get current order information
> 
> **Do not call the application service method in the event handler.**
> 
> You can do your work in the domain service. can use any userid directly.

You mean i should subscribe the event: **OrderCreatedEvent** in **DomainService** and all works need to be done in there, right?

**Comment by kaleyroy** [comment]
> > When the event handler is executed, i call OrderAppSevice to get current order information
> 
> **Do not call the application service method in the event handler.**
> 
> You can do your work in the domain service. can use any userid directly.

Okkk, i figure it out! domain service is right way to go. many thanks  @maliming
