### ISSUE TITLE
An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor

### ISSUE THREAD

**Issue by Qither** [abpframework/abp#18634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This application was built with linking (tree shaking) disabled. 
Published applications will be significantly smaller if you install wasm-tools workload. 
See also https://aka.ms/dotnet-wasm-features[0m
Loaded 11.98 MB resources from cache
Debugging hotkey: Shift+Alt+D (when application has focus)
info: Volo.Abp.AbpApplicationBase[0]
      Loaded ABP modules:
info: Volo.Abp.AbpApplicationBase[0]
      - Store.Blazor.StoreBlazorModule
info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.Autofac.WebAssembly.AbpAutofacWebAssemblyModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Autofac.AbpAutofacModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.Castle.AbpCastleCoreModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.AspNetCore.Components.WebAssembly.AbpAspNetCoreComponentsWebAssemblyModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AspNetCore.Mvc.Client.AbpAspNetCoreMvcClientCommonModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Http.Client.AbpHttpClientModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Http.AbpHttpModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Http.AbpHttpAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Json.AbpJsonModule
info: Volo.Abp.AbpApplicationBase[0]
                    - Volo.Abp.Json.SystemTextJson.AbpJsonSystemTextJsonModule
info: Volo.Abp.AbpApplicationBase[0]
                      - Volo.Abp.Json.AbpJsonAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
                      - Volo.Abp.Timing.AbpTimingModule
info: Volo.Abp.AbpApplicationBase[0]
                        - Volo.Abp.Localization.AbpLocalizationModule
info: Volo.Abp.AbpApplicationBase[0]
                          - Volo.Abp.VirtualFileSystem.AbpVirtualFileSystemModule
info: Volo.Abp.AbpApplicationBase[0]
                          - Volo.Abp.Settings.AbpSettingsModule
info: Volo.Abp.AbpApplicationBase[0]
                            - Volo.Abp.Localization.AbpLocalizationAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
                            - Volo.Abp.Security.AbpSecurityModule
info: Volo.Abp.AbpApplicationBase[0]
                            - Volo.Abp.Data.AbpDataModule
info: Volo.Abp.AbpApplicationBase[0]
                              - Volo.Abp.ObjectExtending.AbpObjectExtendingModule
info: Volo.Abp.AbpApplicationBase[0]
                                - Volo.Abp.Validation.AbpValidationAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
                              - Volo.Abp.Uow.AbpUnitOfWorkModule
info: Volo.Abp.AbpApplicationBase[0]
                              - Volo.Abp.EventBus.Abstractions.AbpEventBusAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
                          - Volo.Abp.Threading.AbpThreadingModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Minify.AbpMinifyModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.MultiTenancy.AbpMultiTenancyModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.MultiTenancy.AbpMultiTenancyAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Validation.AbpValidationModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.ExceptionHandling.AbpExceptionHandlingModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.RemoteServices.AbpRemoteServicesModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.EventBus.AbpEventBusModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Guids.AbpGuidsModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.BackgroundWorkers.AbpBackgroundWorkersModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.DistributedLocking.AbpDistributedLockingAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.AspNetCore.Mvc.AbpAspNetCoreMvcContractsModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Application.AbpDddApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
                  - Volo.Abp.Auditing.AbpAuditingContractsModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Caching.AbpCachingModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Serialization.AbpSerializationModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Authorization.AbpAuthorizationModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Authorization.AbpAuthorizationAbstractionsModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Features.AbpFeaturesModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.UI.AbpUiModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AspNetCore.Components.Web.AbpAspNetCoreComponentsWebModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.AspNetCore.Components.AbpAspNetCoreComponentsModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.ObjectMapping.AbpObjectMappingModule
info: Volo.Abp.AbpApplicationBase[0]
        - Store.StoreHttpApiClientModule
info: Volo.Abp.AbpApplicationBase[0]
          - Store.StoreApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
            - Store.StoreDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.AuditLogging.AbpAuditLoggingDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.BackgroundJobs.AbpBackgroundJobsDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.FeatureManagement.AbpFeatureManagementDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Identity.AbpIdentityDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Users.AbpUsersDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.OpenIddict.AbpOpenIddictDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.PermissionManagement.AbpPermissionManagementDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.SettingManagement.AbpSettingManagementDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.TenantManagement.AbpTenantManagementDomainSharedModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.Account.AbpAccountApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Identity.AbpIdentityApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.Users.AbpUsersAbstractionModule
info: Volo.Abp.AbpApplicationBase[0]
                - Volo.Abp.PermissionManagement.AbpPermissionManagementApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.FeatureManagement.AbpFeatureManagementApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.SettingManagement.AbpSettingManagementApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.TenantManagement.AbpTenantManagementApplicationContractsModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Account.AbpAccountHttpApiClientModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Identity.AbpIdentityHttpApiClientModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.PermissionManagement.AbpPermissionManagementHttpApiClientModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.TenantManagement.AbpTenantManagementHttpApiClientModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.FeatureManagement.AbpFeatureManagementHttpApiClientModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.SettingManagement.AbpSettingManagementHttpApiClientModule
info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXLiteTheme.AbpAspNetCoreComponentsWebAssemblyLeptonXLiteThemeModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.AspNetCore.Components.Web.LeptonXLiteTheme.AbpAspNetCoreComponentsWebLeptonXLiteThemeModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AspNetCore.Components.Web.Theming.AbpAspNetCoreComponentsWebThemingModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.BlazoriseUI.AbpBlazoriseUIModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.UI.Navigation.AbpUiNavigationModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.AspNetCore.Components.WebAssembly.Theming.AbpAspNetCoreComponentsWebAssemblyThemingModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Http.Client.IdentityModel.WebAssembly.AbpHttpClientIdentityModelWebAssemblyModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.Http.Client.IdentityModel.AbpHttpClientIdentityModelModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.IdentityModel.AbpIdentityModelModule
info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.Identity.Blazor.WebAssembly.AbpIdentityBlazorWebAssemblyModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.Identity.Blazor.AbpIdentityBlazorModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.AutoMapper.AbpAutoMapperModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.Auditing.AbpAuditingModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.PermissionManagement.Blazor.AbpPermissionManagementBlazorModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.PermissionManagement.Blazor.WebAssembly.AbpPermissionManagementBlazorWebAssemblyModule
info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.TenantManagement.Blazor.WebAssembly.AbpTenantManagementBlazorWebAssemblyModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.TenantManagement.Blazor.AbpTenantManagementBlazorModule
info: Volo.Abp.AbpApplicationBase[0]
            - Volo.Abp.FeatureManagement.Blazor.AbpFeatureManagementBlazorModule
info: Volo.Abp.AbpApplicationBase[0]
              - Volo.Abp.SettingManagement.Blazor.AbpSettingManagementBlazorModule
info: Volo.Abp.AbpApplicationBase[0]
          - Volo.Abp.FeatureManagement.Blazor.WebAssembly.AbpFeatureManagementBlazorWebAssemblyModule
info: Volo.Abp.AbpApplicationBase[0]
        - Volo.Abp.SettingManagement.Blazor.WebAssembly.AbpSettingManagementBlazorWebAssemblyModule
warn: Volo.Abp.IdentityModel.IdentityModelAuthenticationService[0]
      Could not find IdentityClientConfiguration for AbpMvcClient. Either define a configuration for AbpMvcClient or set a default configuration.
info: System.Net.Http.HttpClient.AbpMvcClient.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:44374/api/abp/application-configuration?IncludeLocalizationResources=False&api-version=1.0
info: System.Net.Http.HttpClient.AbpMvcClient.ClientHandler[100]
      Sending HTTP request GET https://localhost:44374/api/abp/application-configuration?IncludeLocalizationResources=False&api-version=1.0
Error: One or more errors occurred. (An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module Volo.Abp.AspNetCore.Components.WebAssembly.AbpAspNetCoreComponentsWebAssemblyModule, Volo.Abp.AspNetCore.Components.WebAssembly, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null: An error occurred during the ABP remote HTTP request. (TypeError: Failed to fetch) See the inner exception for details.. See the inner exception for details.)
    at Jn (e:\CSProject\Store\src\Store.Blazor\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\5535e31a712343a63f5d7d796cd874e563e5ac14\src\mono\wasm\runtime\marshal-to-js.ts:349:18)
    at Ul (e:\CSProject\Store\src\Store.Blazor\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\5535e31a712343a63f5d7d796cd874e563e5ac14\src\mono\wasm\runtime\marshal-to-js.ts:306:28)
    at wasm://wasm/00b1e8b6:wasm-function[350]:0x1faca
    at wasm://wasm/00b1e8b6:wasm-function[246]:0x1bf8b
    at wasm://wasm/00b1e8b6:wasm-function[239]:0xf172
    at wasm://wasm/00b1e8b6:wasm-function[307]:0x1e7e4
    at wasm://wasm/00b1e8b6:wasm-function[328]:0x1efda
    at wasm://wasm/00b1e8b6:wasm-function[218]:0xcfec
    at wasm://wasm/00b1e8b6:wasm-function[774]:0x440ad
    at Go (https://localhost:44340/_framework/dotnet.runtime.8.0.0.14kkjimq5k.js:3:50974) {superStack: {…}, stack: <accessor>, message: 'One or more errors occurred. (An error occur…ails.. See the inner exception for details.)', Symbol(wasm js_owned_gc_handle): 134}

### Reproduction Steps

Create the Blazor project and run it

### Version

8.0.0

### User Interface

Blazor

### Database Provider

MongoDB

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by QiYouGames** [comment]
An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor

**Comment by Qither** [comment]
It is good to run the application before starting the development. The solution has two main applications;

TodoApp.HttpApi.Host hosts the server-side HTTP API.
TodoApp.Blazor is the client-side Blazor WebAssembly application.
Ensure the TodoApp.HttpApi.Host project is the startup project, then run the application (Ctrl+F5 in Visual Studio)
