### ISSUE TITLE
Where is angular account module's source code?

### ISSUE THREAD

**Issue by vincywindy** [abpframework/abp#1864]
I want to rewrite the account module with different theme,but I could't find the account source code?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/modules/account/README.md


https://github.com/abpframework/abp/issues/1597
https://github.com/abpframework/abp/issues/631

**Comment by vincywindy** [comment]
Sorry,all I want is angular part's soure code,no background‘s source code.

**Comment by maliming** [comment]
it's here. : )

https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages

![image](https://user-images.githubusercontent.com/6908465/66377247-c4cb0c00-e9e3-11e9-8626-a5b7f35f1bdd.png)

**Comment by vincywindy** [comment]
> it's here. : )
> 
> https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages
> 
> ![image](https://user-images.githubusercontent.com/6908465/66377247-c4cb0c00-e9e3-11e9-8626-a5b7f35f1bdd.png)

Ok thanks!
