### ISSUE TITLE
Option to prevent modal close on form submit

### ISSUE THREAD

**Issue by mcsc-gareth** [abpframework/abp#18641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to prevent an ABP modal from closing when the form is submitted/saved, but there is no easy way to accomplish this.

### Describe the solution you'd like

I suggest that an optional attribute such as "data-close-modal-on-submit" (or something with a better name) be added to the modal-manager.js file. The "_$form.on('abp-ajax-success')" callback should then just consider whether this attribute is set before calling modal.hide(). 

I can see several use cases for this sort of functionality, but most importantly, the workaround required in the absence of this option is quite extensive (unless I'm really just missing something), and the magnitude of the workaround needed seems at odds with the spirit of ABP.io's "get going quickly" approach.

I see one previous issue that discussed this (many years ago), but the outcome seems peculiar. As mentioned above, this seems like a small addition that saves a lot of effort in the cases where this behaviour is needed.

**Comment by realLiangshiwei** [comment]
You can set the `data-ajaxForm` to "false" and manually call `abpAjaxForm` method:

```csharp
<form method="post" data-ajaxForm="false">
```

```js
form.abpAjaxForm({
    beforeSubmit : function (){
        // return false to prevent modal close
        return false;
    }
})
```

**Comment by mcsc-gareth** [comment]
Sorry for the late response, but thank you for this. I tried this almost immediately and it did what I needed it to. A much shorter workaround to the path I'd started down, so thank you.

I'm still tempted to suggest exposing this as an attribute on the modal element (or similar), but it's a minor point certainly.
