### ISSUE TITLE
The problem of running abp in Linux (mint)

### ISSUE THREAD

**Issue by behnamasaei** [abpframework/abp#18650]
dotnet sdks installed:
6.0.417 [/usr/share/dotnet/sdk]
7.0.404 [/usr/share/dotnet/sdk]
8.0.100 [/usr/share/dotnet/sdk]

---

when run the command "abp" :
You must install or update .NET to run this application.

App: /home/oem/.dotnet/tools/abp
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/lib/dotnet

The following frameworks were found:
  6.0.25 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=linuxmint.21.2-x64

**Comment by maliming** [comment]
hi

> To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=linuxmint.21.2-x64

Does this help?

**Comment by behnamasaei** [comment]
Hi. 
I appreciate your guidance, but it doesn't help me as I have already installed the SDKs and runtime.

![Screenshot from 2024-01-02 10-20-45](https://github.com/abpframework/abp/assets/46339775/e0910fc3-98d5-4d40-98ad-6697cb90fc23)

**Comment by maliming** [comment]
hi

Does `dotnet ef` tool also have a similar problem?

https://www.nuget.org/packages/dotnet-ef/8.0.0

**Comment by behnamasaei** [comment]
Finally, I believe the issue was resolved by entering the following command:

`export PATH="$PATH:$HOME/.dotnet/tools/"
`

**Comment by behnamasaei** [comment]
I'm sorry, but I don't know why I encountered the same issue again after reopening and closing the terminal.

![Screenshot from 2024-01-02 11-10-02](https://github.com/abpframework/abp/assets/46339775/d2dca342-778a-497b-aeca-856d5e16db18)

it`s information of my PATH

**Comment by behnamasaei** [comment]
I encounter this error for the remaining commands as well.
like : dotnet-ef

![Screenshot from 2024-01-02 11-12-15](https://github.com/abpframework/abp/assets/46339775/e616c49c-99b6-4c71-b43a-1d5272f0ecd4)

**Comment by maliming** [comment]
This is a NET Core-related problem. `abp cli` is just a normal net core global tool.

We don't have much info.
