### ISSUE TITLE
How to Integrated third-party sign-in?

### ISSUE THREAD

**Issue by vincywindy** [abpframework/abp#1865]
The old abp project has https://aspnetboilerplate.com/Pages/Documents/Zero/User-Management#external-authentication, Does vnext has same like this? I want to Integrated Wechat sign-in

**Comment by maliming** [comment]
There seems to be no such module at present. However, vnext integrates asp net core identity. You can try its external authentication.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-3.0&tabs=visual-studio
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers
