### ISSUE TITLE
Admin menu not rendering when logging in until refreshing (Deployed in Azure Web Service)

### ISSUE THREAD

**Issue by yanxiaodi** [abpframework/abp#18664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've got this problem since abp 6.x. Today I updated it to abp 8.0 but the issue still exists. 

When the user logs in successfully, the admin menu is not rendering until refreshing the index page.

I've searched github issues and the support QA and found similar issues:

* https://support.abp.io/QA/Questions/4763/
* https://support.abp.io/QA/Questions/4363
* https://support.abp.io/QA/Questions/5830/
* https://github.com/abpframework/abp/issues/12118

I believe this problem is not fixed in 8.0.

### Reproduction Steps

Create a new abp application using the Blazor UI and deploy it to Azure Web Service. 

**Note that the app works on local machine. It can show the admin menu correctly but after I deployed it to Azure, then it cannot render the admin menu when logging in until I manually refresh the page.**

### Expected behavior

The admin menu should show correctly when user logs in. 

### Version

8.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Can you share an online url that includes a test user and password?

**Comment by yanxiaodi** [comment]
@maliming sure I can make one tonight

**Comment by maliming** [comment]
Thanks. liming.ma@volosoft.com

**Comment by yanxiaodi** [comment]
@maliming I've emailed you. Thanks!

**Comment by maliming** [comment]
hi

Can you create a **new abp template application** and deploy it to Azure Web Service?

Thanks.

**Comment by yanxiaodi** [comment]
The app I showed is basically a new one. The solution consists of two parts:
* An basic service created by ABP CLI using the new abp template to manage users, permissions, etc
* A module to implement the other business logic. 

Currently the problem is that when the user logs in, neither the menu of the **admin role** nor the menu of the module works. If you login using my username & password, you would find that the **Administration** menu does not work either, which means it's not caused by the module. If you refresh the page, you will see the **Administration** menu.

**Comment by maliming** [comment]
ok, Can you also share the source code of the current app?

**Comment by yanxiaodi** [comment]
@maliming I invited you. Let me know if you cannot see the invitation. Thanks

**Comment by maliming** [comment]
Thanks. I will do some research.

**Comment by yanxiaodi** [comment]
Hi @maliming  any updates? Thanks.

**Comment by maliming** [comment]
https://github.com/yanxiaodi/TheWashHouse/issues/66

**Comment by yanxiaodi** [comment]
Many thanks @maliming  I'll try it and let you know if it works.

**Comment by yanxiaodi** [comment]
Thanks @maliming  I can confirm the issue is solved. It would be great if you include the fix in the next release. Many thanks!

**Comment by developerMCSI** [comment]
Hi everyone,
Since this is a recurring error and it happens to me too, can you share the fix?

Thanks

**Comment by maliming** [comment]
hi @developerMCSI 

It is about `LeptnXLite`.

<img width="1866" alt="image" src="https://github.com/abpframework/abp/assets/6908465/498ebfbd-6be2-4b1a-99c3-732bc8c4e892">

**Comment by developerMCSI** [comment]
Thanks @maliming

**Comment by gmaldarelli** [comment]
hi @maliming i have a similar problem, your sample https://github.com/yanxiaodi/TheWashHouse/issues/66 is not more available.
Can you share it again? 
Thanks
