### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by heitorgiacomini** [abpframework/abp#18705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I trying  to add localization in angular frontend

### Describe the solution you'd like

Localization should be in angular front-end not in the back-end, its the normal convention.

### Additional context

not necessary

**Comment by Sinan997** [comment]
we have more than one UI (angular, blazor, mvc). so that makes it easier to manage localizations in our case.

if you want to add your localizations to your angular app, you can add other 3th libraries like ngx-translate, transloco etc.
