### ISSUE TITLE
NavItemsService new Items not rendered

### ISSUE THREAD

**Issue by Ibrahimogod** [abpframework/abp#18704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I tried to use `NavItemsService` to add new Componet to the top right nav items but it's not being rendered don't know what is the reason, I tried the same with `UserMenuService ` and It worked fine but I don't need it there, however I tried another solution to replace the Language Selection Component using `ReplaceableComponentsService` with a new Component which should include both the Language Selection Component and My New Component and it's rendered but the issue is I can't reuse the Language Selection Component, 
I tried to use the selector `<abp-language-selection> </abp-language-selection>`  and  `<lpx-language-selection></lpx-language-selection>` but both can't be found or treated as existing Components
**I'm using angular for the UI** and the Theme is **LeptonX**

### Reproduction Steps

use `NavItemsService.add` in `AppComponet` constructor on `OnInit ` nothing happened and the item is not rendered

### Expected behavior

the new Item should be rendered and show at the top right menu Nav Items

### Actual behavior

Nothing happened and the Item not rendered

### Known Workarounds

use `ReplaceableComponentsService` instead of `NavItemsService`

### Version

7.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by Sinan997** [comment]
Hi, i have produced your problem. We will fix this. Thank you for reporting. I will inform you about issues and pr's.

**Comment by masum-ulu** [comment]
Hi @Ibrahimogod it was about the theme (theme-lepton-x) we've fixed in 3.0-patch version It'll release today FYI
