### ISSUE TITLE
Example of a Monolith with at least one module communicating via distributed event

### ISSUE THREAD

**Issue by iang0ld** [abpframework/abp#1871]
This idea here is to provide an example of building a Monolith ready to be converted to a Microservice when the need arises. So there should be communication via a distributed event.

**Comment by hikalkan** [comment]
I didn't understand what you need here? You can just use IDistributedEventBus.

**Comment by iang0ld** [comment]
I am starting out with microservices and messaging between modules and it would be helpful to have an example as there is lot to learn. I'm looking to use abp with identity, tenant, user, settings module, etc as a monolith like existing ASP Boilerplate, but with messaging between modules so it can be moved to microservices when the need arises.

**Comment by iang0ld** [comment]
This is all sorted.  Thanks. Your hint about IDistributedEventBus helped greatly.
