### ISSUE TITLE
Abp call github abp

### ISSUE THREAD

**Issue by heitorgiacomini** [abpframework/abp#18720]
* Your **ABP Framework version** 7.4.1.
* Your **User Interface** Angular
* Your database provider(**EF Core**)

Currently, ABP does requests to the GitHub API to get a static file. Why does this even exist? This was not in previous versions. I am using 7.4.1, and it makes no sense to make a request to external resources to get a static file. So I am looking for a solution to disable requests to api.github.com/repos/abpframework/abp

![image](https://github.com/abpframework/abp/assets/19227918/b8272717-baee-46e3-a956-7d7aae1087aa)

![image](https://github.com/abpframework/abp/assets/19227918/afbec295-71c9-48f6-a137-54fcfd11a617)

**Comment by realLiangshiwei** [comment]
I don't remember ABP will call GitHub API internally. can you try to use a new project to reproduce the problem?

**Comment by heitorgiacomini** [comment]
> I don't remember ABP will call GitHub API internally. can you try to use a new project to reproduce the problem?

Yes, even on 8.0.1 version the same happens.
![image](https://github.com/abpframework/abp/assets/19227918/9a507476-4efe-42c8-a7e8-622aec8bf570)

![image](https://github.com/abpframework/abp/assets/19227918/b091a21d-af61-418e-82ef-cbba71547a5a)

**Comment by Sinan997** [comment]
this ain't spesific to angular ui. i am investigating

**Comment by Sinan997** [comment]
the reasons for request is these lines; https://github.com/abpframework/abp/blob/dev/templates/app/angular/src/app/home/home.component.html#L133-L143

this request brings the star count, thats why it requests to github
![image](https://github.com/abpframework/abp/assets/72804437/c37ad06c-6acc-44d0-bbec-d96d21895845)

**Comment by heitorgiacomini** [comment]
Thank you to solve this mystery.
