### ISSUE TITLE
seed data error on remote sql server

### ISSUE THREAD

**Issue by mehmetcimen** [abpframework/abp#18741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is no problem when I run it on my local database, but when I run it on my remote sql server, I get this error
SeedDataAsync
![abp-framework-seed-data](https://github.com/abpframework/abp/assets/10267525/622a9ee1-0480-4979-887e-e96afe4d5598)

### Version

8.0.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

What's your remote database info? eg version.

**Comment by mehmetcimen** [comment]
> hi
> 
> What's your remote database info? eg version.

MSSQL 2019

**Comment by maliming** [comment]
hi

You can copy the generated SQL to your remote SQL server and try to run it.

https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#sensitive-data

<img width="1515" alt="image" src="https://github.com/abpframework/abp/assets/6908465/f092655d-e1f8-4671-b684-7a300d44a9d4">


Maybe you can change the **CompatibilityLevel**

https://www.youtube.com/watch?v=g-6Fs9c5Ryo

**Comment by mehmetcimen** [comment]
Hi 
CompatibilityLevel Sql Server 2016 (130) is working 
but   SQL Server 2014 (120 is not working   
**this problem exists only in version 8.0.0**

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-8_0#use-newer-versions-of-the-sql-server-sql-server-14
