### ISSUE TITLE
Swagger UI login feature.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1874]
https://github.com/abpframework/abp/issues/1849
https://github.com/abpframework/abp/issues/1383
https://github.com/abpframework/abp/issues/1872#issuecomment-539893781

**Comment by KidoPlay** [comment]
Are you planning to do it the old way like zero?
Use a mvc page to do the login, and share cookies and stuff with swagger?

**Comment by maliming** [comment]
I have simply implemented it, using password grant type of Identity Server.

Of course this may need to be enhanced or replaced with other methods.

see https://github.com/abpframework/abp/compare/maliming/swagger

**Comment by LGinC** [comment]
I try it and chrome blocked by CORS
![image](https://user-images.githubusercontent.com/15363011/69535468-fa897b80-0fb6-11ea-8409-7da7a26d04ba.png)

[close chrome CORS policy](https://www.cnblogs.com/yanggl/p/10211930.html) and it work

**Comment by maliming** [comment]
I haven't encountered the problem with cors. I will check it.

**Comment by maliming** [comment]
We should provide a class library to reuse swagger login functionality. (js,html...)

Such as:
```
app.UseSwagger();
app.UseSwaggerUIWithAbpLogin(//config);
```

**Comment by maliming** [comment]
Already implemented, but we can discuss it.https://github.com/abpframework/abp/commit/3d0573f54c6613f14b37a1fe83e6ed8c2b94cf65

**Comment by leonkosak** [comment]
@maliming what is the status/priority of this feature?

**Comment by maliming** [comment]
hi @leonkosak 

it's still in the backlog.

**Comment by maliming** [comment]
Resolved by https://github.com/abpframework/abp/pull/6124
