### ISSUE TITLE
Skipping the default error handling in custom error handler shows a error popup

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#18753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We want to handle all errors by our self and using a custom http error handler for that. the [documentation](https://docs.abp.io/en/abp/8.0/UI/Angular/HTTP-Requests#custom-http-error-handler) for custom error handling mention that you can skip the default error handling simply by return. In 8.0 this cause a confirmation to be shown instead.

We want only our own (custom http error handler) error handling to be shown.

You can see in the [error.handler.ts](https://github.com/abpframework/abp/blob/68cb2f001cffb48dc6887cb30433567d2fce05e0/npm/ng-packs/packages/theme-shared/src/lib/handlers/error.handler.ts#L59-L70) that the showError function is called if you skip the default handler

### Reproduction Steps

1. follow the [custom http error handle documentation](https://docs.abp.io/en/abp/8.0/UI/Angular/HTTP-Requests#custom-http-error-handler) including 'Note 1'
2. cause an 403 http error

### Expected behavior

No confirmation popup is shown when all handler are skipped

### Actual behavior

confirmation popup is shown

### Known Workarounds

create an custom error handler (CustomHttpErrorHandlerService) that does nothing and always return true for canHandle (at lowest priority)

### Version

8.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

Would be great if the documentation would include CUSTOM_ERROR_HANDLERS and HTTP_ERROR_CONFIG

**Comment by Sinan997** [comment]
@puschie286 hi, i have created an issue about it. You can follow the related issue from [here](https://github.com/abpframework/abp/issues/18774). 
It will be fixed in next release and the documentation will be updated.
