### ISSUE TITLE
Email verification failed during registration

### ISSUE THREAD

**Issue by RayWangQvQ** [abpframework/abp#18763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I enabled `options.SignIn.RequireConfirmedEmail = true;`, but I could not receive the verification email when registering.
There is no problem with the config of smtp service, because when I click Forgot Password, I can receive a password reset email.

Another phenomenon is that when I register successfully without verifying my email address, I will immediately go to the home page successfully. When I log out and log in again, I am prompted for email verification.

I wonder if this is a bug?

I did some searching, there is not much information in the documentation and issues, and there is an article in the community(https://community.abp.io/posts/setup-email-confirmation-on-user-registration-q0vgxang), but it looks very old and I don't think it is the answer to the current version of implementing email login.

Did I miss some information for email confirmation? And how can I implement it?

### Reproduction Steps

1. Create a new project by `abp new Acme.BookStore -csf `
2. add following codes

```
        context.Services.Configure<IdentityOptions>(options =>
        {
            options.SignIn.RequireConfirmedAccount = true;
            options.SignIn.RequireConfirmedEmail = true;
        });
```

3. update following codes

```
#if DEBUG
        //context.Services.Replace(ServiceDescriptor.Singleton<IEmailSender, NullEmailSender>());
#endif
```

4. config email smtp service and test it
5. register a new user with email

### Expected behavior

The verification information can be received by email, and the homepage cannot be accessed immediately after registration.

### Actual behavior

cannot receive the verification message in my email, and go directly to the homepage after registering.

### Version

ABP CLI 8.0.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
I will check it

**Comment by realLiangshiwei** [comment]
Hi,

This is not a bug. email verification is not included in the basic account module

See: https://docs.abp.io/en/commercial/latest/abp-framework-vs-abp-commercial#account-module-basic-vs-pro

>  and there is an article in the community(https://community.abp.io/posts/setup-email-confirmation-on-user-registration-q0vgxang), but it looks very old and I don't think it is the answer to the current version of implementing email login.

It is still available, you can refer to it: https://community.abp.io/posts/setup-email-confirmation-on-user-registration-q0vgxang

**Comment by RayWangQvQ** [comment]
Got it, thanks.
