### ISSUE TITLE
Policy on package dependencies that are no longer in use

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [abpframework/abp#18769]
What is the policy on package dependencies in ABP when the framework no longer uses them directly? Just to bring one example, and there may be others of course, `Nito.AsyncEx.Coordination` referenced in [Volo.Abp.Core](https://github.com/abpframework/abp/blob/6bd43caee572af6acec744e768982430ea788b0d/framework/src/Volo.Abp.Core/Volo.Abp.Core.csproj) and [Directory.Packages.props](https://github.com/abpframework/abp/blob/6bd43caee572af6acec744e768982430ea788b0d/Directory.Packages.props) is unused and I could compile the whole solution without it.

**Comment by maliming** [comment]
hi

I will remove it from `Volo.Abp.Core` package in the next version.

Maybe we used it but didn't need it anymore.
