### ISSUE TITLE
Entity Framework 6.3 integration is possible?

### ISSUE THREAD

**Issue by jader1313** [abpframework/abp#1878]
Since there are several databases without EF Core providers yet, would it not be possible for ABP to integrate with EF 6.3?

The EF 6.3.0 runtime was released to NuGet in September 2019. The main goal of this release was to facilitate migrating existing applications that use EF 6 to .NET Core 3.0. Here are some of the more notable ones:

**Support for .NET Core 3.0**
The EntityFramework package now targets .NET Standard 2.1 in addition to .NET Framework 4.x.
This means that EF 6.3 is cross-platform and supported on other operating systems besides Windows, like Linux and macOS.
The migrations commands have been rewritten to execute out of process and work with SDK-style projects.

**Comment by maliming** [comment]
I don't think it is necessary. It will not be difficult to migrate ef 6 to ef core.

After all, ef core is the future, it has a lot of advanced features. It will continue to improve and support modern features.

Once ef 6 and ef core have some inconsistent functions or features, abp will not be able to abstract them. Maintaining ef 6 is also a development cost.

If my opinion is wrong, please let me know. : )

**Comment by hikalkan** [comment]
>Maintaining ef 6 is also a development cost

For me, the essential point is that. So, we don't plan to support EF 6.x unless there is a huge demand by the community :)

**Comment by jader1313** [comment]
I understand that EF Core is the future and that keeping EF 6 would be costly (I believe the cost will not be that high), but I believe there are many situations where this would be the only alternative I know.
I will cite my specific case:
I have a legacy system that accesses the Visual FoxPro database (.DBC / .DBF)
There is a provider for EF 6 but it does not exist for EF Core and may never be created.
-We are starting development of a new version of the system. The idea is an incremental development, migrating parts only. That way, for a long time, we will continue to access the old database through the old and new systems until we can migrate the entire system and then move to another database.
-The chosen framework was ASPNET BoilerPlate + EF6. This way the new system will be born outdated (.Net Framework + EF6) in addition to the outdated BoilerPlate.

So with the release of EF6.3 I think it would be a great solution ABP + .Net Core + EF6.3.

Would this be technically possible?

**Comment by hikalkan** [comment]
Your case seems reasonable. I moved it to normal priority in the backlog. I don't know when we can work on that. If you can understand the EF Core integration and implement it for EF 6.x, you can send a pull request :)
