### ISSUE TITLE
Can not redirect successfully from auth server to angular app if uri include params

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#18804]
### The problem

Ref: https://support.abp.io/QA/Questions/6495

When attempting to access the link: **domain.com/**`my-link?queryParam=value` without authentication, the system redirects to the authentication server. However, when the authentication server returns with query parameters, the resolution process fails to complete successfully

### Sample

![image](https://github.com/abpframework/abp/assets/49063256/3f5122f2-e629-4b67-b5fc-0f9be73f4c78)
--
![image](https://github.com/abpframework/abp/assets/49063256/8c2073e0-ee9d-4186-967f-59bf6477d2f6)
--
![image](https://github.com/abpframework/abp/assets/49063256/f0425dec-72c4-4f5b-89e5-691fb9ccf8b1)

**Comment by JanneHarju** [comment]
This is such a small change/fix. Could you reconsider to fix this also to 7.3 or 7.4 versions. This is just bad UX for our customers that they are not getting where they were trying to navigate before login. Our quick and dirty fix was to add this to app.routing-module to avoid error message about no path match:
`{
    path: '**',
    redirectTo: 'dashboard',
  },`

**Comment by mkincyan** [comment]
Yeah, it would be great if this was in 7.3 or 7.4. We haven't been able to fix the issue by injecting the relevant changes into our project.
