### ISSUE TITLE
Settings will be cleared unexpectedly if multiple providers with the same name

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#18809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It seems that `SettingManager` supports multiple providers with the same name, but there is an issue with this implementation.

According to that:

`SettingManager.GetOrNullInternalAsync(string name, string providerName, string providerKey, bool fallback = true)`:

https://github.com/abpframework/abp/blob/b595ff497176c17c5411e0e762694fcf248f3e0a/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingManager.cs#L181-L189

If we expect the `providerName` to be unique, we should constrain it within `SettingManagementOptions` and take it by the `FirstOrDefault` method. But there are `SkipWhile` and `TakeWhile`.

So, I think ABP allows multiple providers with the same name. But then, if we set a value with this provider name, it will lose the value:

`SettingManager.SetAsync(string name, string value, string providerName, string providerKey, bool forceToSet = false)`:

https://github.com/abpframework/abp/blob/b595ff497176c17c5411e0e762694fcf248f3e0a/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingManager.cs#L136-L144

If the `providers` list contains providers named `[ "U", "U", "T", ... ]`, the `fallbackValue` will still be retrieved from the providers named `U`.

And then, if the `value` equals the `fallbackValue`, the `value` will be set to `null`.  `SettingManager` will clear the value for **each** provider `U`:

https://github.com/abpframework/abp/blob/b595ff497176c17c5411e0e762694fcf248f3e0a/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingManager.cs#L150-L156

### Reproduction Steps

1. Insert the second `ISettingManagementProvider` named `U` near the origin `UserSettingManagementProvider`.
2. Call `await SettingManager.SetAsync(key, value, "U", CurrentUser.Id);`.
3. Repeat the step 2 again, with the same arguments.
4. Call `await SettingManager.GetAsync(key, "U", CurrentUser.Id);`

### Expected behavior

Retrieved the previously set value.

### Actual behavior

Retrieved `null`.

### Known Workarounds

Retrieve `fallbackValue` from the second unique name of the providers, rather than the second provider's name.

```CSharp
var providerName = providers.Select(provider => provider.Name).Distinct().Skip(1).FirstOrDefault();
if (providerName is not null)
{
    var fallbackValue = await GetOrNullInternalAsync(name, providerName, null); 
}
```

### Version

7.4.5

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
This seems to be a problem. The framework should prevent adding `SettingValueProvider` with duplicate names.
I will check it

**Comment by hikalkan** [comment]
Multiple providers with the same name is not allowed. The code seems trying to somehow tolerate it, but we don't expect multiple providers with the same name. It is stated in the documentation: https://docs.abp.io/en/abp/latest/Settings#custom-setting-value-providers

![image](https://github.com/abpframework/abp/assets/1210527/d8e48d38-c8f6-480f-ab29-0f4042ada4de)

If that's the only problem, we can close this issue @realLiangshiwei
