### ISSUE TITLE
openIddict applications page: Javascript Datatables error

### ISSUE THREAD

**Issue by Domitnator** [abpframework/abp#18807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dear Support,

We just updated from 7.04 to 8.2. I made the changes that were noted in the migration guide:

- https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-8_0
- https://docs.abp.io/en/abp/latest/Migration-Guides/OpenIddict4-to-5

I also created a database migration and updated the database. And i ran "abp install-libs" to be sure.

The admin interface is up and running and our application works as excpected. So far so good! 

The only issue we have is:

When navigating to: /openIddict/Applications i get the following error:

![image](https://github.com/abpframework/abp/assets/13468638/fc289994-bb80-4c90-9122-eefd69932cae)

I guess this has to do with the openiddict change? Any idea how i can fix this?

### Version

8.0.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please create a support ticket on https://support.abp.io/

Thanks.
