### ISSUE TITLE
Problem with the ABP setup

### ISSUE THREAD

**Issue by migueldeltorodev** [abpframework/abp#18827]
### Description
I'm starting to use abp and I'm running with some problems installing/using node/npm commands, first I installed node from https://nodejs.org/en/download/ and works! but when I try to install yarn with the command "npm install --global yarn" give me the following error: 
npm ERR! code ENOTFOUND 
(the description of the error)
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.

I think is because a my registry configuration, I try several registry and none of then work, some give me that error and others gave me:
npm ERR! code EACCES
(the description of the error)
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.

I disable my antivirus protection, I'm also using VPN because in my country we don't have access to those registry.

Any Solution to this?

### Configuration

* I'm using .NET 8.0.0 with node 20.11.0 , yarn 1.22.19  and ABP CLI 8.0.2
* I'm using Windows 10
* Architecture 64bits
* My PC is an HP Laptop of 10th gen with 8gb of RAM, don't know if is related

### Analysis
The project it's created but with missing files at node_modules and a yarn-error.log and when I execute the project in the .web I get a lot of errors in the dev tools window (related to a missing bundle file)

Maybe it's something related with connection? I don't know what else to try here.

**Comment by maliming** [comment]
hi

>  but when I try to install yarn with the command "npm install --global yarn" give me the following error:


ABP applications may need `npm` and `yarn,` But we have no idea about the install error. you can google it.
