### ISSUE TITLE
DomainTenantResolver sample for NG-TIERED with OpenIddict

### ISSUE THREAD

**Issue by dkaczor97** [abpframework/abp#18824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

There are samples for every scenario of DomainTenantResolver except NG-TIERED with OpenIddict. Please provide such sample. Thank you.

**Comment by maliming** [comment]
hi

Move to https://github.com/abpframework/abp-samples/issues/223
