### ISSUE TITLE
TenantKey is configurable and cannot be hardcoded.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#1883]
`__tenant` parameter name can be changed using `AspNetCoreMultiTenancyOptions`.
```
services.Configure<AspNetCoreMultiTenancyOptions>(options =>
{
    options.TenantKey = "MyTenantKey";
});
```
https://github.com/abpframework/abp/blob/33a450bb621de36517c7943d261a063b3accf4a4/npm/ng-packs/packages/core/src/lib/interceptors/api.interceptor.ts#L29

**Comment by hikalkan** [comment]
Thank you @maliming for reporting this. Added it to backlog.

**Comment by vijay2358** [comment]
below is not working - any idea? version 5.3.X

services.Configure<AspNetCoreMultiTenancyOptions>(options =>
{
    options.TenantKey = "MyTenantKey";
});

**Comment by vijay2358** [comment]
options.TenantKey is name of tenant name or guid?

**Comment by mahmut-gundogdu** [comment]
in the angular app,  tenant key is already configuratable via token or option. (almost v5.3)


https://github.com/abpframework/abp/blob/rel-7.0/npm/ng-packs/packages/oauth/src/lib/interceptors/api.interceptor.ts

I think we can close the issue
