### ISSUE TITLE
A custom AuthorizationHandler or a custom PermissionValueProvider is executed twice when the service is set to a virtual method

### ISSUE THREAD

**Issue by Azirliang** [abpframework/abp#18845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![img_v3_027c_4708e1b4-18c5-41f4-ae90-8a6c9fd2693g](https://github.com/abpframework/abp/assets/113135423/6a53253a-fb9f-4b27-b155-b85aa506ff8b)

### Version

6.0.3 OR 8.0.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

A project that is not ABP will not be executed twice

**Comment by maliming** [comment]
hi

Can you share a **simple** project on Github?

**Comment by Azirliang** [comment]
[ABP.DEMO.zip](https://github.com/abpframework/abp/files/14040564/ABP.DEMO.zip)

Unable to push to github due to network issue,So zip attachment is used here

You can debug `TestPolicyHandler`

``` shell
virtual method API:
curl --location 'https://localhost:44331/api/demo/sample/virtualAge'

Nonvirtual method API:
curl --location 'https://localhost:44331/api/demo/sample/age'
``` 
@maliming

**Comment by Azirliang** [comment]
稍微看了下源码，猜测是在ABP中的虚方法的AuthorizationInterceptor和.NET CORE的Authorization中间件冲突了

**Comment by maliming** [comment]
The `AuthorizationMiddleware` and the `AuthorizationInterceptor` do the same work. For the app services as a controller, we need to find a way to improve it.

**Comment by Azirliang** [comment]
After improve, hope your team can patch to 6.0.x

**Comment by maliming** [comment]
> After improve, hope your team can patch to 6.0.x

You can apply the PR's code to your project.

https://github.com/abpframework/abp/pull/18874

**Comment by Azirliang** [comment]
> > After improve, hope your team can patch to 6.0.x
> 
> You can apply the PR's code to your project.
> 
> #18874

thanks

**Comment by hikalkan** [comment]
Closed by https://github.com/abpframework/abp/pull/18874
