### ISSUE TITLE
Support facebook login

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#1885]
after I upgraded from 0.19 to 0.21. I do not use login with facebook, google. Can you fix it as soon as possible?
![image](https://user-images.githubusercontent.com/10234503/66570415-bcb3cd80-eb97-11e9-9bc2-e65ddc84b3b3.png)

**Comment by maliming** [comment]
Abp v0.2.1 uses asp net core 3.0. Does AddFaceBook` support it?

**Comment by nguyendev** [comment]
yes, you can see at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.0

**Comment by maliming** [comment]
So what is the problem you are experiencing? Is there an error message? Please elaborate.

**Comment by maliming** [comment]
You'll need to install the following NuGet Package

```
<PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="3.0.0" />
```
