### ISSUE TITLE
Filtering returns incorrect response

### ISSUE THREAD

**Issue by Sinan997** [abpframework/abp#18877]
when i click refresh button it returns totalCount:1 but not returning an item

![image](https://github.com/abpframework/abp/assets/72804437/fab6023e-b996-4104-871c-74f523af1941)

**Comment by realLiangshiwei** [comment]
How to reproduce the problem?

**Comment by Sinan997** [comment]
take an url in first page and search in second page

**Comment by realLiangshiwei** [comment]
I can't reproduce the problem
<img width="1345" alt="image" src="https://github.com/abpframework/abp/assets/16813853/ea039884-ebc6-4f1c-b4e6-87512299e0e5">

**Comment by Sinan997** [comment]
![filter](https://github.com/abpframework/abp/assets/72804437/e0985293-5afa-411e-be8e-53eb261296ad)

**Comment by realLiangshiwei** [comment]
This is no problem, you should clear the `skipCount` when first searching
