### ISSUE TITLE
Remove table-striped class from tables MVC / Blazor UI

### ISSUE THREAD

**Issue by Sinan997** [abpframework/abp#18906]
![image](https://github.com/abpframework/abp/assets/72804437/e952a4d4-d33b-4c7a-b565-f3d0286cca2c)

**Comment by JadynWong** [comment]
After removing `table-striped`, would you consider adding `table-hover` to clearly show the current row?

**Comment by enisn** [comment]
> After removing `table-striped`, would you consider adding `table-hover` to clearly show the current row?

Hi, I asked the design team and table-hover isn't necessary at this point
