### ISSUE TITLE
abp-button tag helper busy-text usage

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#18900]
Abp version: 8.0.2 (MVC/EF)

Hi
I was looking at abp-button tag helper. There is an attribute named [busy-text](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Tag-Helpers/Buttons#busy-text).
> A text that is shown when the button is busy.

What makes it busy or how can I make it busy? There is no information about it in documentation. Can you please tell me how to do it and add an info about it in documentation?

**Comment by Sinan997** [comment]
https://github.com/abpframework/abp/blob/ad0daa12c0add20f136f6b11c8bd723bacfe2f38/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Button/AbpButtonTagHelperService.cs#L20

it seems this method sets button label to busy-text. maybe @maliming can give you detail about it

**Comment by muhlisatac** [comment]
I have found the [function](https://github.com/abpframework/abp/blob/ad0daa12c0add20f136f6b11c8bd723bacfe2f38/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery/jquery-extensions.js#L11). It would be nice if it was also included in the documentation.

**Comment by muhlisatac** [comment]
Added a pull request for doc update.
