### ISSUE TITLE
How to ignore Accept-Language Header for culture in ABP

### ISSUE THREAD

**Issue by manojkrsna** [abpframework/abp#18918]
* Your **ABP Framework version**. 7.1.1

**Accept-Language** Header in the Request of the API's is setting up the culture. How to ignore /override this Header for culture set . Please suggest

**Comment by maliming** [comment]
hi

You can remove `AcceptLanguageHeaderRequestCultureProvider` from `RequestLocalizationOptions`.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/select-language-culture?view=aspnetcore-8.0#change-request-culture-providers-order

**Comment by manojkrsna** [comment]
Thanks, it works. Sorry for troubling here by  thinking it is abp related but it is common thing in .net
