### ISSUE TITLE
Unable to run database migration. 

### ISSUE THREAD

**Issue by rupesh-adapty** [abpframework/abp#18928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The project was created following the instructions in the "Mastering ABP Framework" book.

The solution is created using: `abp new ProductManagement`

After defining the entities, the Web project is set as the startup project and in the PM Console, the EntityFrameworkCore project is set as default. On running the Add-Migration command, the error displayed is: 
`Your startup project 'ProductManagement.DbMigrator' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again`.

There was a similar bug reported but the issue was closed without a satisfactory resolution: https://github.com/abpframework/abp/issues/16785

### Reproduction Steps

Follow instruction in Chapter 3 of the "Mastering ABP Framework" book up to page 38. On Page 38, the command `Add-Migration "Added_Categories_And_Products"` throws the error.

### Version

8.0.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

You can run `dotnet ef migrations add MyName` command under the `EntityFrameworkCore ` project.

**Comment by benrivero** [comment]
![error](https://github.com/abpframework/abp/assets/22895959/3af7a249-e0b9-4155-902d-b0cd744cd15b)
Hi, I have the same Issue, tried with Add-Migration and with dotnet ef migrations add NameMigration under EntityFrameworkCore project and is not working.

**Comment by maliming** [comment]
hi @benrivero 

You can try to use `dotnet-ef` instead of `Add-Migration`

https://learn.microsoft.com/en-us/ef/core/cli/dotnet

**Comment by Pantex9** [comment]
Hi, do you know if this issue is still open?
