### ISSUE TITLE
Issue with generated proxy with self referencing to DTO class

### ISSUE THREAD

**Issue by Feramor** [abpframework/abp#18956]
**ABP Version: 8.0.2**

- [X] I have searched the existing issues

Generated self referencing DTO's has issues given below;

Backend Implementations
```csharp
[Serializable]
public class EntityDtoWithConcurrencyStamp<Tkey> : EntityDto<Tkey>, IHasConcurrencyStamp
{
    [DisableAuditing] public string ConcurrencyStamp { get; set; }
}

public class OptionDto<Tkey>
{
    public string Key { get; set; }
    public Tkey Value { get; set; }
}

public class CascadeOptionDto<Tkey> : OptionDto<Tkey>
{
    public List<CascadeOptionDto<Tkey>> Childs { set; get; }
}
```

### Expected behavior

![image](https://github.com/abpframework/abp/assets/6627652/51838cf1-7d61-4bdb-a7a3-93dbfe4cfd0a)

![image](https://github.com/abpframework/abp/assets/6627652/072e9971-93d4-443f-bbaf-d4593d47e64c)

### Actual behavior

![image](https://github.com/abpframework/abp/assets/6627652/e207bd83-5777-4762-a00f-a855d1bbd410)

![image](https://github.com/abpframework/abp/assets/6627652/a5726fe3-b092-4689-b7cb-a54e7302c63f)

**Comment by ryanrocksize5** [comment]
I have the same type of bug aswell, from ABP 5.2 all the way to ABP 8, easiest way is to delete the additional Tkey import, although I have no idea why this keeps happening to me too.

**Comment by steffbeckers** [comment]
Related to https://github.com/abpframework/abp/issues/19656

**Comment by masum-ulu** [comment]
The problem occurs from server in [this line](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Http/Volo/Abp/Http/Modeling/PropertyApiDescriptionModel.cs#L39-L40) > [also this line](https://github.com/abpframework/abp/blob/9bc3b9b28c4d114120e67eea3316991bba461db2/framework/src/Volo.Abp.Core/Volo/Abp/Reflection/TypeHelper.cs#L217). @maliming can we add GenericArgument to `TypeSimple` and `Type` properties, even property is DTO itself ?

### Sample DTO
![image](https://github.com/abpframework/abp/assets/49063256/eebc0ad9-dfb5-4ce5-8ac2-d56430b706d7)


### Excepted (generate-proxy.json)
![image](https://github.com/abpframework/abp/assets/49063256/0dd8687c-447f-48f4-8651-cca78878f9a5)

### Actual (generate-proxy.json)
![image](https://github.com/abpframework/abp/assets/49063256/a2d5150a-d1b7-43a6-bb91-8031c2443cb4)
