### ISSUE TITLE
Header is missing when in mobile size

### ISSUE THREAD

**Issue by KennyEng12** [abpframework/abp#18964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, we are using [ABP Framework + Angular + LeptonX Lite Theme + Entity Framework Core] version 8.0.

<img width="571" alt="image" src="https://github.com/abpframework/abp/assets/29649512/8c3f923e-8f31-4b0d-bce5-d64117be2ba6">
<img width="553" alt="image" src="https://github.com/abpframework/abp/assets/29649512/0ca8cfcc-756d-4e02-9f05-ea4623546157">

The header is missing when in mobile size with width less than 480px as image shown above.

Thanks,
Kenny.

### Reproduction Steps

1. Created new project with `abp new Acme.BookStore -u angular -m react-native -csf`
2. Setup everything following [Getting Started Document](https://docs.abp.io/en/abp/latest/Getting-Started-Running-Solution?UI=NG&DB=EF&Tiered=No)
3. Run both front-end & back-end projects
4. Set the screen size to mobile size with width less than 4780px

### Expected behavior

The expected behaviour should be showing the header as when the width size is larger & larger than 480px.

### Actual behavior

The header is missing when in mobile size with width less than 480px as image shown above.

### Version

8.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by masum-ulu** [comment]
Hi Kenny, Thanks I'll check it

**Comment by Sinan997** [comment]
will be fixed in next patch version

**Comment by KennyEng12** [comment]
Hi, may I know where to get the latest patch version & when would it be ready?

Thanks,
Kenny.

**Comment by masum-ulu** [comment]
> Hi, may I know where to get the latest patch version & when would it be ready?
> 
> Thanks, Kenny.

Hi @KennyEng12 you can wait for next 8.0.x version of ABP it is releasing parallel don't worry 👍

**Comment by KennyEng12** [comment]
Would you mind drop me a message here when it's available?

Thanks,
Kenny.
