### ISSUE TITLE
[INVALID] - CLI automatic bundle did not work when the project was created

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#18974]
**App:** Mvc - `8.1 pre-rc`
**Command:** `abp new Mvc.EfCore080224App -csf -t app -u mvc --local-framework-ref --abp-path D:\GitHub\abp --template-source C:\Users\Volosoft\.abp\templates --version 8.1.0-preview20240208 -tv -sib`

CLI automatic bundle did not work when the project was created.  Problem fixed when  run  `abp install-libs` 
![image](https://github.com/abpframework/abp/assets/99716457/7a67f08b-a56b-4314-8c1e-f3ca27f5cf1e)

**Comment by EngincanV** [comment]
Since you used the `-sib` parameter, it's normal to skip the install libs command:

![image](https://github.com/abpframework/abp/assets/43685404/7aa5d526-f401-4214-8af8-8fac7916f7bc)
