### ISSUE TITLE
Issues while customizing main header branding

### ISSUE THREAD

**Issue by mirfanazam** [abpframework/abp#18987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am using LeptonX with commercial version (v8.0.3, Personal licence).

Application Layout: Top Menu

I have customized main header branding, to change the application name but after this logo disappeared from main header.

When I tried to override the logo then logo appeared but application name disappeared.

### Reproduction Steps

**1. Application name appears in main header but logo disappears.**

`    public class MyProjectBrandingProvider : DefaultBrandingProvider
    {
        public override string AppName => "My Application Name";
    }`

**2. Logo appears but application name disappears.**

`    public class MyProjectBrandingProvider : DefaultBrandingProvider
    {
        public override string AppName => "My Application Name";

        public override string LogoUrl => "/images/icon.svg";
    }`

### Version

8.0.3

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

Theme LeptonX

**Comment by maliming** [comment]
hi

Please create a support ticket on https://support.abp.io/

Thanks.
