### ISSUE TITLE
Error with Tests

### ISSUE THREAD

**Issue by migueldeltorodev** [abpframework/abp#18984]
Hello! My ABP Framework version is 8.0.1 and I'm using MVC with Razor Pages for my UI and MySQL for my database

I'm following the guide to make services and I make the GetListAsync service following every step from the book and it works fine! but the problem is when I make a test for it, I get this error:

### Error:

```
ProductManagement.Products.ProductAppService_Tests`1.Should_Get_Product_List
   Source: ProductAppService_Tests.cs line 21 //This is the line of the method public async Task Should_Get_Products_List()
   Duration: 1 ms

  Message: 
System.ArgumentException : Cannot create an instance of ProductManagement.Products.ProductAppService_Tests`1[TStartupModule] because Type.ContainsGenericParameters is true.

  Stack Trace: 
RuntimeType.CreateInstanceCheckThis()
RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
Activator.CreateInstance(Type type, Object[] args)
<>c__DisplayClass0_0.<CreateTestClass>b__0() line 42
ReflectionAbstractionExtensions.CreateTestClass(ITest test, Type testClassType, Object[] constructorArguments, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) line 42
```

My Tests class: ProductAppService_Tests looks like this:
```
using Shouldly;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Modularity;
using Xunit;

namespace ProductManagement.Products
{
    public class ProductAppService_Tests<TStartupModule>: ProductManagementApplicationTestBase<TStartupModule> 
        where TStartupModule: IAbpModule
    /* The original configuration is without TStartupModule and without the where state, but that gives me an error:
    CS0305*/
    {
        private readonly IProductAppService _productAppService;

        public ProductAppService_Tests()
        {
            _productAppService = GetRequiredService<IProductAppService>();
        }

        
        [Fact]
        public async Task Should_Get_Product_List()
        {
            //Act
            var output = await _productAppService.GetListAsync(
                new PagedAndSortedResultRequestDto()
            );

            //Assert
            output.TotalCount.ShouldBe(3);
            output.Items.ShouldContain(x => x.Name == "Acme Monochrome Laser Printer, Compact All-In One");
        }
    }
}

### Implementation

My method GetListAsync from ProductAppService:

    public async Task<PagedResultDto<ProductDto>> GetListAsync(PagedAndSortedResultRequestDto input)
    {
        var queryable = await _productRepository.WithDetailsAsync(x => x.Category);

        queryable = queryable
            .Skip(input.SkipCount)
            .Take(input.MaxResultCount)
            .OrderBy(input.Sorting ?? nameof(Product.Name));

        var products = await AsyncExecuter.ToListAsync(queryable);
        var count = await _productRepository.GetCountAsync();

        return new PagedResultDto<ProductDto>(count, ObjectMapper.Map<List<Product>, List<ProductDto>>(products));
    }
}
```

**Comment by maliming** [comment]
hi

https://docs.abp.io/en/abp/latest/Tutorials/Part-4?UI=NG&DB=EF

**Comment by TRB7** [comment]
Dear @maliming,
I hope this comment finds you well!

I tried to replicate this issue, using the BookStore in the tutorial "https://docs.abp.io/en/abp/latest/Tutorials/Part-4?UI=NG&DB=EF" , and I get the same error as @shinAC01 

ABP Framework version is **8.0.5**, UI:**NG**, DB:**EF** with Postgres as DBMS

> System.ArgumentException : Cannot create an instance of Acme.BookStore.Books.BookAppService_Tests`1[TStartupModule] because Type.ContainsGenericParameters is true.

![image](https://github.com/abpframework/abp/assets/61992476/73bd8890-446b-4a5a-a938-432e987fc85c)

**Should_Get_List_Of_Books** implementation

![image](https://github.com/abpframework/abp/assets/61992476/3d362709-d94a-4371-bb6d-0e0e9f635f4b)



When I try to set this class "_BookAppService_Tests_" as `abstract ` and `protected ` for its constructor as mentioned in the tutorial, and I build the project, I'm no longer able to see the whole project _Acme.BookStore.Application.Tests_ in **Test explorer**, as shown below

![image](https://github.com/abpframework/abp/assets/61992476/1a9fcd53-6799-45fb-aec2-dbd07c1a64ae)

_Acme.BookStore.Application.Tests_ is no longer available
![image](https://github.com/abpframework/abp/assets/61992476/30e8f974-ba12-4c9a-9732-60644069d656)

With `dotnet test` in CMD it gives **No test is available**
![image](https://github.com/abpframework/abp/assets/61992476/6787b5b5-c584-4b2d-8ff3-e5b3eda695b4)

But when I set it back to `public class BookAppService_Tests<TStartupModule>...` and `public BookAppService_Tests()...` for the constructor, I'm again able to see the _Acme.BookStore.Application.Tests_ in Test explorer and the **Run All Tests** gives the exception described above.

Find below the full exception
![image](https://github.com/abpframework/abp/assets/61992476/d30441cb-da15-4152-a054-b2acc2cc24d0)

Best regards!

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp-samples/blob/master/BookStore-Mvc-EfCore/test/Acme.BookStore.Application.Tests/Books/BookAppService_Tests.cs#L13

https://github.com/abpframework/abp-samples/blob/master/BookStore-Mvc-EfCore/test/Acme.BookStore.EntityFrameworkCore.Tests/EntityFrameworkCore/Applications/Books/EfCoreBookAppService_Tests.cs
<img width="1059" alt="image" src="https://github.com/abpframework/abp/assets/6908465/38efb62d-f55a-4ed9-b271-2e6bd8cb90c9">

**Comment by TRB7** [comment]
Hi @maliming ,

Thanks for your prompt reply!

Yes I followed all the steps in the tutorial and it worked, however as mentioned in my previous comment, Acme.BookStore.Application.Tests is no longer visible in the Test Explorer, the test should be ran in _Acme.BookStore.EntityFrameworkCore.Tests_ project, `EfCoreBookAppService_Tests` class instead.

![image](https://github.com/abpframework/abp/assets/61992476/7b439c33-4cfd-4b7c-b26d-d4e79ae741d4)
PS: EfCoreBookAppService_Tests is created in _EntityFrameworkCore\Applications\Books_ namespace (folder) of the _Acme.BookStore.EntityFrameworkCore.Tests_ project


Maybe this part in the tutorial could be updated accordingly, people would be tempted to look at BookAppService_Tests to run their tests, while the class is not visible in Test Explorer

![image](https://github.com/abpframework/abp/assets/61992476/4b7ae676-1ab8-4a4a-aa2f-402c10d2320a)

Regards!

**Comment by maliming** [comment]
Thanks. I will update the images in the docs.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/19384
