### ISSUE TITLE
Get culture properties in localization when ask for localization resources 

### ISSUE THREAD

**Issue by Sinan997** [abpframework/abp#18993]
Related #18977 

Hi, when we change localization in angular, we need to make a request to applicationConfiguration for currentCulture properties.
If we can get culture attributes when we asked for localization resources we can get rid of extra request to backend.

![image](https://github.com/abpframework/abp/assets/72804437/968ce09f-ad12-48fd-a0ac-c496604c0dfb)

@maliming, can we do that, is it possible?

**Comment by maliming** [comment]
> If we can get culture attributes when we asked for localization resources 

https://abp.io/api/abp/application-localization?cultureName=tr

Do you want `culture: tr` to appear in the returned JSON?

**Comment by Sinan997** [comment]
yes, this object 
![image](https://github.com/abpframework/abp/assets/72804437/ca5e94a9-373a-43e2-8f03-82db1d5c540e)

if it possible, it would be nice
