### ISSUE TITLE
In ASP.NET Core 3.0, ConfigureServices returning an System.IServiceProvider isn't supported

### ISSUE THREAD

**Issue by CCC598** [abpframework/abp#1902]
Example:
```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
	services.AddApplication<AppModule>();

	return services.BuildServiceProviderFromFactory();
}
```
will throw System.NotSupportedException:“ConfigureServices returning an System.IServiceProvider isn't supported.” in ASP.NET Core 3.0.
https://docs.autofac.org/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting.
If use this way, some features will not work.

**Comment by hikalkan** [comment]
For v0.21, if you are starting with an empty project, follow https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-Application

You should change Program.cs as like in the last code blog in this document.
