### ISSUE TITLE
[Angular] Login Page SideBar flicker on reload

### ISSUE THREAD

**Issue by Shahid-khan5** [abpframework/abp#19038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you are on the login page and refresh the site, the sidebar flicker and shown for very short amount. Please check the video

### Reproduction Steps

1. Create a multi layered angular app using the cli
2. Run the migration
3. Run the apis
4. Run the angular app
5. Go to login page
6. Refresh the login page

### Expected behavior

It shouldn't flicker and the sidebar shoudn't visible

### Actual behavior

The sidebar is visible for very short amount of time

### Version

8.0.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

**Comment by Shahid-khan5** [comment]
https://github.com/abpframework/abp/assets/76004649/042e18af-8bfb-4ca5-a037-f8448098a50c

**Comment by masum-ulu** [comment]
We'll try to find a way for improve User Experience

**Comment by Shahid-khan5** [comment]
Thanks for fixing the issue. When It will be released?

**Comment by masum-ulu** [comment]
You can track new version release date in here

https://github.com/abpframework/abp/milestone/95
