### ISSUE TITLE
Auto API Problem in Tiered Startup Template

### ISSUE THREAD

**Issue by mypolat** [abpframework/abp#1903]
Hi all,
I selected tiered startup template and MVC. I have made improvements by following the documentation, but the API that should be created automatically does not work on me. 
(You can review [this link](https://github.com/KatmerTeam/Wenitor.Backend)) 
I cannot access Javascript functions. Why is this possible? How can I fix ? Thank you.

Best regards.

**Comment by maliming** [comment]
> but the API that should be created automatically does not work on me.

Can you describe it in detail? 
What are the steps to reproduce the problem?

**Comment by mypolat** [comment]
Thanks for your reply. I created application service interfaces and implementations, dtos, mappings. I prepared mvc page but there is no my entity in dynamic javascript. I didn't do anything else. If you want to review this project you can use https://github.com/KatmerTeam/Wenitor.Backend 
Best regards.

**Comment by maliming** [comment]
@mypolat
What are the steps to reproduce the problem? : )

**Comment by ekangal** [comment]
JavaScript proxies not working.  When I test in the Google development tool, I get the error in the image below.

There is no problem with the "app" application template; JavaScript proxies works. I get an error when I create a "tiered" application template. When MVC, WEBAPI, IdentyServer runs separately.

`katmer.wenitor.targetSource.getList({}).done(function (result) { console.log(result); });`

![image](https://user-images.githubusercontent.com/3465364/66732362-51eae680-ee64-11e9-81eb-21f7d9576a5c.png)

![image](https://user-images.githubusercontent.com/3465364/66732378-64652000-ee64-11e9-8902-3ff1473267f1.png)

![image](https://user-images.githubusercontent.com/3465364/66732385-6e871e80-ee64-11e9-9f00-997015a73f1b.png)

**Comment by maliming** [comment]
please see https://github.com/abpframework/abp/issues/1469#issuecomment-517705968

**Comment by luy710** [comment]
@ekangal  How did you solve this problem
