### ISSUE TITLE
Hamburger menu doesnt work on the abp.io site if you are in the blog module.

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#19037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The menu just toggles on/off x and hamburger on the Blog page.

Menu works on other pages.

Just tested on IPhone/Safari.

### Reproduction Steps

N/a

### Expected behavior

N/a

### Actual behavior

N/a

### Regression?

N/a

### Known Workarounds

N/a

### Version

N/a

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Related to https://github.com/volosoft/vs-internal/pull/2959
