### ISSUE TITLE
ABP v 8.0.3 - Angular -  Lookup fields ((Associate a department to a user)  for extra properties not showing up 

### ISSUE THREAD

**Issue by nurkmez2** [abpframework/abp#19055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The example in the following link not working properly. The response from API  has department's list as expected.
However, in the Angular app Department is visible the datatable (user list screen) but not  in the modal edit window. 
 
https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#navigation-properties-foreign-keys

Angular Error in the developer console as below
<img width="956" alt="image" src="https://github.com/abpframework/abp/assets/117904000/a7958e1a-79d9-42a0-bee5-6e63bf581fdf">

### Reproduction Steps

By following these steps in the link below;

https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#example-associate-a-department-to-a-user

### Expected behavior

<img width="392" alt="image" src="https://github.com/abpframework/abp/assets/117904000/2b35808b-7cde-4695-af52-9d7f0b00ed42">

### Actual behavior

<img width="394" alt="image" src="https://github.com/abpframework/abp/assets/117904000/c912124a-ac03-4c21-85df-4c45eb6e1083">
<img width="959" alt="image" src="https://github.com/abpframework/abp/assets/117904000/73d8c02e-518d-477f-a940-c460c7abfe9f">

### Version

8.0.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by ryanrocksize5** [comment]
Same here, ABP 8.0.2

**Comment by Sinan997** [comment]
Hi, we have released 8.0.4 patch version. It should be solved. Related pr; https://github.com/abpframework/abp/pull/18962

Could you update to 8.0.4 and try again?

**Comment by Sinan997** [comment]
if the error continues you can open a new issue.
