### ISSUE TITLE
How to register Autofac modules?

### ISSUE THREAD

**Issue by lommez** [abpframework/abp#1906]
How can i register autofac modules?
If so, is it auto registered? 

thanks

**Comment by maliming** [comment]
Please see the documentation

https://docs.abp.io/en/abp/latest/Dependency-Injection

https://docs.abp.io/en/abp/latest/Autofac-Integration

**Comment by lommez** [comment]
In my case i need some more advanced registrations.
Would be possible to call the methods:
public void ConfigureContainer(ContainerBuilder builder)
public void ConfigureContainer(AutofacChildLifetimeScopeConfigurationAdapter config)

like in the specified in that article:

[https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting](https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting)

For example... is a abp.module have those public methods, by reflection call them? Maybe is an idea.

Thanks

**Comment by hikalkan** [comment]
Write this to ConfigureServices of your module:

````csharp
var containerBuilder = context.Services.GetContainerBuilder();
containerBuilder.RegisterModule...
````

**Comment by lommez** [comment]
thanks @hikalkan !!
