### ISSUE TITLE
Mark AggreateRoot as modified

### ISSUE THREAD

**Issue by Brandejs** [abpframework/abp#19060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

According to [AggregateRoot Class](https://docs.abp.io/en/abp/latest/Entities#aggregateroot-class) I would expect that if I am working with Order as a single unit, the modification in the OrderLines collection will cause a change to Order at the same time. 

So if I add a new OrderLine to an Order.  I would expect that there will be a LastModifierId and LastModificationTime change on the Order.

I would also expect that
`ILocalEventHandler<EntityUpdatedEventData<Order>>` should be triggered

### Describe the solution you'd like

Would it be possible to add a MarkAsModified() method to BasicAggregateRoot? that would mark the entity as modified? So proper audition and event triggers be handled? Or with a repository.UpdateAsync() mark as changed even if there is no property change. 

### Additional context

![image](https://github.com/abpframework/abp/assets/5411927/8d2e5eca-df61-4cab-8a63-0677ec131bad)
![image](https://github.com/abpframework/abp/assets/5411927/02ff0f17-0924-49ae-bad3-0d4683cec697)

**Comment by maliming** [comment]
hi

What is your ABP Framework version?

Can you share a test project? Thanks.

**Comment by Brandejs** [comment]
Hi,

sure. ABP Framework version: 8.0.3

It's a newly generated project.

Code
`src/Acme.BookStore_Eventing.Domain/Orders/Order.cs`

Test
`test/Acme.BookStore_Eventing.Domain.Tests/Samples/SampleDomainTests.cs`
[Acme.BookStore_Eventing.zip](https://github.com/abpframework/abp/files/14328020/Acme.BookStore_Eventing.zip)

**Comment by Brandejs** [comment]
HI,

maybe not related... But I notice another thing. 

If in DbContextModelCreatingExtensions we set HasDefaultValue for property. 

```
b.Property(x => x.Name).HasDefaultValue("DefaultVlaue");
```

in AbpDbContext.cs

In the same method that is responsible for emitting events
`PublishEventsForTrackedEntity¨

There is condition
`if (entry.Properties.Any(x => x.IsModified && x.Metadata.ValueGenerated == ValueGenerated.Never))`

but with HasDefaultValue:  x.Metadata.ValueGenerated == 'OnAdd'

I think that correct condition should be
`if (entry.Properties.Any(x => x.IsModified && (x.Metadata.ValueGenerated == ValueGenerated.Never || x.Metadata.ValueGenerated == ValueGenerated.OnAdd)))`

![Screenshot 2024-02-19 at 11 17 13](https://github.com/abpframework/abp/assets/5411927/3f06fffe-20c9-48d7-88d3-36651f542602)

**Comment by maliming** [comment]
hi

The EF Core has an issue; We can't know whether the aggregate root has changed when deleting the child collection.

https://github.com/dotnet/efcore/issues/24076

**Comment by Brandejs** [comment]
Hi, 

I think there may be more cases. For example, changing the Child Entity of Child entity.  So I would suggest as a fallback to add some dummy property to BasicAggreageRoot, which we can set with `this.MarkAsModified()` As I know there is a similar problem with ValueObjects. So this could be used as a fallback.  

I currently set LastModificatioTime = null as a fallback. Which will mark the entity as Modified.

**Comment by maliming** [comment]
We should wait for EF Core to support it.

**Comment by maliming** [comment]
Done by https://github.com/abpframework/abp/pull/19079

**Comment by JadynWong** [comment]
If you don't use Include to load the sub-navigation properties at the beginning, and use `Repository.EnsureCollectionLoadedAsync` in the middle of the process, it won't trigger `EntityUpdatedEventData<TEntity>`.

Such as:
https://github.com/abpframework/abp/blob/63b8d555fcd8b8b8ccea2ff4cf49a0e31014b430/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserManager.cs#L192-L199

It does not trigger `EntityChangedEventData<IdentityUser>`.

**Comment by maliming** [comment]
> If you don't use Include to load the sub-navigation properties at the beginning, and use `Repository.EnsureCollectionLoadedAsync` in the middle of the process, it won't trigger `EntityUpdatedEventData<TEntity>`.
> 
> Such as:
> 
> https://github.com/abpframework/abp/blob/63b8d555fcd8b8b8ccea2ff4cf49a0e31014b430/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserManager.cs#L192-L199
> 
> It does not trigger `EntityChangedEventData<IdentityUser>`.

Will be fixed by https://github.com/abpframework/abp/pull/19523 https://github.com/abpframework/abp/pull/19523/commits/5f56d2bb0e3e2977d17d473aaaecec933e0c87e9
