### ISSUE TITLE
Add UK English (en-GB) to the list of supported languages

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#1907]
Please add en-GB (UK English) to the list of supported languages as 'en' is used for US English

e.g. US English date formats use mm/dd/yyyy format whereas the UK uses dd/mm/yyyy. Also, language / spelling is different; US English uses 'Color' whereas UK is spelt 'Colour'

**Comment by hikalkan** [comment]
Language list is in the startup template, so you can change it yourself: https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/MyProjectNameWebModule.cs#L152-L156

**Comment by KevinFarrow** [comment]
@hikalkan I can see how to add a new language but we need to also have the UK English set as the main installation language and not just another language added at a later date.

Is there any reason why you ignore the UK? Remember US English is not English, it's a variation on English!

Also, If you won't add **en-gb** as a built-in language, does that mean that you won't add any other languages in future, even if they send you the translations? If you need translations for en-GB I can translate the existing texts to UK English.

**Comment by hikalkan** [comment]
@KevinFarrow, I suppose you are misunderstanding it. I am not ignoring any language, I don't do that :) I also has respect to UK :)

However, we don't add all languages to the startup template, there are hundreds of languages and no meaning to add to the language combobox without a translation.

In real life, a developer downloading the template will already arrange the language list, add his own and translate if no translation available. There is no "built-in" language list. If the list was in the framework (in a nuget package), you were right. But it is in the startup template.

We are adding languages those have translations for the framework and pre-built modules. See Resource Localization section in this document: https://docs.abp.io/en/abp/latest/Contribution/Index
If you add en-GB translations, it would be appreciated and we immediately add it in the startup template :)
