### ISSUE TITLE
Enum type bind to select

### ISSUE THREAD

**Issue by CoderLittleChen** [abpframework/abp#19104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I follow the tutorial of abp 8,but I encounter this problem.How can i fix it?I have searched the existing issues,but i can't find the solution.
Abp cli：8.0
.Net Core：6
Frontend:Angular
![image](https://github.com/abpframework/abp/assets/32502670/30bba0a3-dc5f-4c0d-8b6b-33dfdd7a35e3)
![image](https://github.com/abpframework/abp/assets/32502670/3a237437-13fc-4348-88c8-331e2f1ca7e9)

### Version

8

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by Sinan997** [comment]
It seems like localization doesn't work.  Can you re-check these steps https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=NG&DB=EF#localization

**Comment by CoderLittleChen** [comment]
> It seems like localization doesn't work. Can you re-check these steps https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=NG&DB=EF#localization

I find the reason. '::Enum:BookType:0' change to '::Enum:BookType.0'.
Thank you so much.
