### ISSUE TITLE
ERROR: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#1911]
**ABP.IO Version 0.21.0**

I'm receiving **ERROR:** _No connection could be made because the target machine actively refused it._

**Step to Reproduce**
1. Modify the DBMigrator connection string.
2. Build/Run DBMigrator to create DB.
3. Copy connection string to .Web appsettings.json
4. Build/Run .Web. 

**NOTE**

I also tried **_update-database_** with Default project: EntitiyFrameworkCore.DbMigraitons and received: 

**ERROR:** Your startup project '....Web' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

**Comment by hikalkan** [comment]
Please be sure that your connection string is true and your server is running.
It has less propability that startup template has a problem. But we will try it.

**Comment by seanalford** [comment]
@hikalkan I'm using the same connection string in both projects. (.DBMigrator, and .Web)

DBMirgrator created the database successfully.  The MS SQL Server is running.

**Comment by maliming** [comment]
@seanalford
No one has feedbacked the problem you mentioned, can you share your project source code?

**Comment by hikalkan** [comment]
I tried, but no problem.

**Comment by seanalford** [comment]
@maliming, here is the web project.

[Eagle.System.Web.zip](https://github.com/abpframework/abp/files/3729172/Eagle.System.Web.zip)

**Comment by maliming** [comment]
@seanalford 
Can you provide a complete project source that can reproduce the problem?

**Comment by cemalsukri** [comment]
Hi , I get same error.
**Steps** :
1. Create template from abp.io 
2. Run DbMigrator ( there no problem it connect and create the database) 
3. Run .web project and here I get the error 
  
![RunError](https://user-images.githubusercontent.com/4073721/68593957-97bcbe00-04a7-11ea-9604-dc41c6f8b535.png)

**Comment by maliming** [comment]
@cemalsukri Can you upload your project?

**Comment by cemalsukri** [comment]
Project file is over than 10MB therefore I upload it to wetransfer : 
https://wetransfer.com/downloads/e9ee5a78fed012eeb0401793b557c96420191112071208/07cd43099ba1835584ae8e66c6d9bb3920191112071208/51aa91
I didn't change anything direct after download from abp.io I run dbMigrator and after successful db creation run .web than I get this error.

**Comment by maliming** [comment]
hi @cemalsukri 
You are using a **tiered** project.

Please check the documentation.
https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Application.md#how-to-run-1

**Comment by karkius** [comment]
Has anyone resolved this issue? How can I debug it? Is my project trying to use some other connection string? Where can I see it? Following this documentation does not help: https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Application.md#how-to-run-1 . IdentityServer project throws same exception "No connection could be made because the target machine actively refused it". I have not changed any connection strings in any projects and I have default localdb connection string which migrator uses successfully. I got the project by downloading it from https://abp.io/get-started with "tiered" checked.

**Comment by hikalkan** [comment]
@karkius tiered template requires redis server on your computer, do you have running it?

**Comment by improwise** [comment]
I also run into this problem and was not able to solve it until I found this ticket, so perhaps this is something that should be highlighted more in the documentation. The information is indeed in there if you read carefully enough (and has the right choices) but still a few people seem to have had similar problems. Thanks.

**Comment by mohammed3296** [comment]
I also run into this problem
