### ISSUE TITLE
abp-input tag helper generates 2 hidden fields instead of one

### ISSUE THREAD

**Issue by sephit** [abpframework/abp#19130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you use the <abp-input> tag helper for hidden values, It will generate two input tags, one of them with the correct name and the other one with a similar name but not correct.

### Reproduction Steps

If you use the following code

`<abp-input add-margin-bottom-class="false" asp-for="DemoEntity.IsEnabled" hidden="true" suppress-label="true" />`

It will generate in the place where you want to display the input tag the following code

`<input hidden="true" type="checkbox" checked="checked" data-val="true" data-val-required="The Is Enabled field is required." id="DemoEntity_IsEnabled" name="DemoEntity.IsEnabled" value="true" class="form-check-input valid" aria-describedby="DemoEntity.IsEnabled-error">
`

AND

At the end of the <form> tag, It will add another hidden input tag

`<input name="DemoEntity.IsEnabled" type="hidden" value="false">`

### Expected behavior

The expected behavior it's to only have one representation of the hidden input tag and that would be like the following

`<abp-input add-margin-bottom-class="false" asp-for="DemoEntity.IsEnabled" hidden="true" suppress-label="true" />`

`<input hidden="true" type="checkbox" checked="checked" data-val="true" data-val-required="The Is Enabled field is required." id="DemoEntity_IsEnabled" name="DemoEntity.IsEnabled" value="true" class="form-check-input valid" aria-describedby="DemoEntity.IsEnabled-error">`

### Actual behavior

Right now, it is generating two input tags

### Version

8.1.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/issues/19128
