### ISSUE TITLE
Invalid code generation for C# static proxy

### ISSUE THREAD

**Issue by Shtong** [abpframework/abp#19137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The C# code that is generated by the `generate-proxy` command is sometimes invalid (does not build) when DTOs contain certain combination of generic arguments.

### Reproduction Steps

Tested using ABP CLI 8.0.4:

1. Create a new project using the default settings `abp new Abp.ReproProxyGen`. Run the Db Migrator to initialize the database.
2. Create the following DTO in the `Application.Contracts` project:
```cs
public class TestOutputDto
{
    public IDictionary<string, IDictionary<string, IEnumerable<string>>> Values { get; set; }
}
```
3. Create an app service in the `Application` project, with a method that returns the DTO we just created
```cs
public class TestAppService : ReproProxyGenAppService
{
    public TestOutputDto GetRepro()
    {
        return null;
    }
}
```
4. Build and run the application
5. Run the proxy generation command. For example: `abp generate-proxy -t csharp -u https://localhost:44385 -wd .\src\Abp.ReproProxyGen.HttpApi.Client\`

### Expected behavior

The proxy generation command creates new files in the `HttpApi.Client` project. After these files are generated, the project can still build.

### Actual behavior

The proxy generation command did create the expected files. However, the file containing the DTO has a syntax error that prevents the project from building:

```cs
public class TestOutputDto
{
    public Dictionary<string, IDictionary<String, IEnumerableString>>> Values { get; set; }
    // Missing '<' character here:       --------------------^
}

```

### Regression?

Not that know of

### Known Workarounds

Override the C# generation service to provide your own working implementation

### Version

8.0.4

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
We will fix it.
