### ISSUE TITLE
Single layer template (Blazor Server), unable to access Index page？

### ISSUE THREAD

**Issue by netty2019** [abpframework/abp#19142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Single layer template (Blazor Server), unable to access the Index page, displaying the following error message：
 An unhandled exception has occurred. See browser dev tools for details. [Reload](https://localhost:44328/) 🗙

### Version

8.0.4

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
**Reproduction Steps**

**Comment by netty2019** [comment]
abp new MES.PumpInspect -t app-nolayers -u blazor-server --theme basic -csf

cd \MES.PumpInspect\MES.PumpInspect

nuget Install-Package Volo.Abp.AspNetCore.Components.Server.BasicTheme

nuget Install-Package Volo.Abp.AspNetCore.Components.Web.BasicTheme

dotnet run --migrate-database

abp install-libs

abp bundle

run project

**Comment by realLiangshiwei** [comment]
I can run the project without any problem. what is the error log?

<img width="1633" alt="image" src="https://github.com/abpframework/abp/assets/16813853/4ed135e8-767a-4610-9742-edeec619d11e">

**Comment by netty2019** [comment]
Thank you, it has been resolved by regenerating the template
