### ISSUE TITLE
A single-layer template project (Blazor Server), when accessing Swagger, the cookie cannot generate XSRF-TOKEN

### ISSUE THREAD

**Issue by netty2019** [abpframework/abp#19157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When accessing Swagger in Chrome Edge for a single layer template project (Blazor Server), XSRF-TOKEN cannot be generated in the cookie, resulting in a continuous 400 error message in the test post interface. It works normally in FireFox browser.
![image](https://github.com/abpframework/abp/assets/47128297/39578297-6970-4d19-b3f2-0bf6fdacf246)

### Version

8.0.4

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
XSRF-TOKEN  is a secure cookie by default,Please use HTTPS

**Comment by netty2019** [comment]
Thank you, is there a way to use it in HTTP mode

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/CSRF-Anti-Forgery#abpantiforgeryoptions
If you want to set you can do it in [AbpAntiForgeryOptions](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AntiForgery/AbpAntiForgeryOptions.cs#L56) class.
