### ISSUE TITLE
CMS Kit - Replace dummy images with actual default images

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#19175]
### Documentation

Check https://github.com/abpframework/abp/pull/19173

Required sized:
- 1280x720
- 320x180
![image](https://github.com/abpframework/abp/assets/23705418/8261e64a-92ed-42a8-b001-ff5f34b53211)

**Comment by armgnunlu** [comment]
![placeholder-img-1](https://github.com/abpframework/abp/assets/36102404/77b84ccd-0298-4007-8b18-2e26176d5a36)
![placeholder-img](https://github.com/abpframework/abp/assets/36102404/dbe0b7ce-632d-4e14-a9c4-fba652d0ab49)
