### ISSUE TITLE
Cannot generate proxy implementation for Hub

### ISSUE THREAD

**Issue by cuongnd235** [abpframework/abp#19176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created signalr asp.net core and used angular to connect. After a successful connection, the client invokes successfully and then the server reports an error using Clients.Caller
![err](https://github.com/abpframework/abp/assets/76472304/880a11bd-6ca9-4e33-85ec-511658c4adec)

### Reproduction Steps

![1](https://github.com/abpframework/abp/assets/76472304/f132cf7c-3f34-47c1-8701-fb905a26b84d)
![2](https://github.com/abpframework/abp/assets/76472304/883023ef-3e04-4982-bed0-d72d4584cdaf)
![3](https://github.com/abpframework/abp/assets/76472304/40074a28-21fc-4cc7-bf5d-13cf98379edc)

### Actual behavior

System.InvalidOperationException: 'Cannot generate proxy implementation for 'Bravo.Backend.WebMaster.Hub.IWebMasterHub.OnFetchPushUser'. All client proxy methods must return 'System.Threading.Tasks.Task'.'

### Version

14.2

### User Interface

Angular

### Database Provider

None/Others

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

**Comment by maliming** [comment]
hi

Please share a simple project. Thanks

**Comment by cuongnd235** [comment]
Sorry, due to personal reasons, I cannot send you my project. Can you share your simple project using apb signalr for agular connection?

**Comment by maliming** [comment]
You can create a new template project to reproduce the problem instead of your personal project.

**Comment by cuongnd235** [comment]
Hello maliming. I share simple project in my github https://github.com/cuongnd235/SignalrApb. you can run it and will get an error at WebMasterHub.cs as I described

**Comment by maliming** [comment]
Please change the return type from `void` to `Task` of `OnFetchPushUser` method. 

```cs
public interface IWebMasterHub
{
    Task OnGetCustomerAccess(object pCustomerAccess);

    Task OnFetchPushUser(object pBravoPushUser, bool pIsStopCalled);

}
```

**Comment by cuongnd235** [comment]
Thanks for your support.
