### ISSUE TITLE
DBMigration fails while more than one *.DBMigrator folder exists

### ISSUE THREAD

**Issue by morosm** [abpframework/abp#19217]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

![dberror](https://github.com/abpframework/abp/assets/32974598/ab789f8e-781d-4cad-8471-fd03c4292c3d)
> DbMligrator is not found!
It occurs while there are more than *.DBMigrator folders in the source folder.

### Reproduction Steps

Occasionally, I renamed the project name, but the `OldProject.DBMigrator` folder not deleted totally and the folder was empty. Then this error occurs.
I checked the source code. It runs `ExecuteAsync` and then `GetDbMigratorProjectPath`, this method got the first `*.DBMigrator` folder. I thought that the method got my `OldProject.DBMigrator` so migrator failed.

```csharp
        private string GetDbMigratorProjectPath(string dbMigrationsFolderPath)
        {
            var srcFolder = Directory.GetParent(dbMigrationsFolderPath);
            var dbMigratorFolderPath = Directory.GetDirectories(srcFolder.FullName).FirstOrDefault(d => d.EndsWith(".DbMigrator"));
            if (dbMigratorFolderPath == null)
            {
                return null;
            }
            return Directory.GetFiles(dbMigratorFolderPath).FirstOrDefault(f => f.EndsWith(".csproj"));
        }
```

### Expected behavior

DB Migration runs successfully.

### Version

8.0.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

The CLI assumes that the structure of your project is designed according to abp conventions.
