### ISSUE TITLE
Identity application and identity application contracts should not depend on permission management

### ISSUE THREAD

**Issue by kynt-lean** [abpframework/abp#19210]
### Description
When separating identity as an independent service, there is still a need of data infrastructure implementation for the Permission Management Domain because the Identity Application Module depends on the Permission Management Application Module. This is not necessary when the service only requires the identity domain.

https://github.com/abpframework/abp/blob/325fa5b54061b0fef5a0cdb4ac924d3c61a7d5d4/modules/identity/src/Volo.Abp.Identity.Application/Volo.Abp.Identity.Application.csproj#L20C5-L20C161

**Comment by seayxu** [comment]
Only `Volo.Abp.Identity` application tiered reference `Volo.Abp.PermissionManagement` application tiered and not use any service,`Volo.Abp.Identity.Application*` should reference  `Volo.Abp.PermissionManagement.Application*`?

**Comment by maliming** [comment]
Hi @hikalkan 

What are your thoughts on this?

**Comment by hikalkan** [comment]
@maliming It currently depends on `Volo.Abp.PermissionManagement.Application`. I suppose only depending on `Volo.Abp.PermissionManagement.Domain` can be enough. Can you check this?

**Comment by maliming** [comment]
The `Identity.Web/Blazor` depends on the `PermissionManagement.Web/Blazor`.
So I think this is why the `Identity.Application` requires the `PermissionManagement.Application`. Otherwise, the `Permissions` modal of user/role will not work anymore.
