### ISSUE TITLE
How to hidden Abp-Api shown in webApi with volo.abp 0.22.0 ？

### ISSUE THREAD

**Issue by xiangxingxing** [abpframework/abp#1922]
<img width="1417" alt="屏幕快照 2019-10-16 上午10 57 11" src="https://user-images.githubusercontent.com/52204046/66884443-cad47480-f003-11e9-90e3-b5b2a0287a66.png">

I just upgrade volo.abp to 0.22.0 and find the AbpApi shown in the SwaggerUI which is unexpected. I'd appreciate it if you could help me to hide the AbpApi .

**Comment by xiangxingxing** [comment]
By the way,  this situation is based on .net core 3.0 and  Swashbuckle.AspNetCore 5.0.0-rc4.

**Comment by maliming** [comment]
The default cannot be hidden. These controllers are for other components.

`Swashbuckle.AspNetCore 5.0.0-rc4.` see https://github.com/abpframework/abp/pull/1917

**Comment by xiangxingxing** [comment]
> The default cannot be hidden. These controllers are for other components.
> 
> `Swashbuckle.AspNetCore 5.0.0-rc4.` see #1917

Thanks. But it confuses me that when using Volo.Abp v-0.21.0 in my project , webApi runs normally and the controllers shown in the picture don't exist.

**Comment by Rwing** [comment]
In some scenarios really should  hide them, maybe make a option to control hide/show them is a better solution.

**Comment by deleteLater** [comment]
you want this?
```c#
public class HiddenApisFilters : IDocumentFilter
{
    private static readonly string[] IgnorePaths = { "/Abp" };

    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        var pathToRemove = swaggerDoc.Paths
            .Where(pathItem => IgnorePaths.Any(x => pathItem.Key.Contains(x)))
            .ToList();

        foreach (var path in pathToRemove)
        {
            swaggerDoc.Paths.Remove(path.Key);
        }
    }
}
```
