### ISSUE TITLE
The [ApiController] attribute can be applied to specific controllers which designed for RESTful api

### ISSUE THREAD

**Issue by CooperLiu** [abpframework/abp#1923]
When I tried to delivery some RESTful APIs with versions feature，it integrated with the swagger doc. Those build-in Abp's modules APIs did not list in the swagger doc.

it's the only difference that I applied [ApiController] attribute to my controllers and Abp build-in `ApiController` was not.

follow MS doc for WebApi apps tips. [Don't create a web API controller by deriving from the `Controller` class](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.0#controllerbase-class).

so is it any advice for those APIs scenarios?

**Comment by maliming** [comment]
> Don't create a web API controller by deriving from the Controller class. Controller derives from ControllerBase and adds support for views, so it's for handling web pages, not web API requests. There's an exception to this rule: if you plan to use the same controller for both views and web APIs, derive it from Controller.

@hikalkan What do you think?

**Comment by CooperLiu** [comment]
try to fix `build-in Abp's modules APIs did not list in the swagger doc` issue. 
`
    [DependsOn(
        typeof(AbpAspNetCoreMvcModule))]
    public class AuthCenterHttpApiModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true; // set `true` to fix swagger doc
                options.UseApiBehavior = false; //set `false` to fix swagger doc, default value is `true`

                var mvcOptions = context.Services.ExecutePreConfiguredActions<AbpAspNetCoreMvcOptions>();
                options.ConfigureAbp(mvcOptions);
            });
           
        }
    }`

**Comment by CooperLiu** [comment]
try to fix `build-in Abp's modules APIs did not list in the swagger doc` issue. 


``` csharp
 [DependsOn(
        typeof(AbpAspNetCoreMvcModule))]
    public class AuthCenterHttpApiModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true; //set true to fix swagger doc
                options.UseApiBehavior = false; //set false to fix swagger doc, default value is true

                var mvcOptions = context.Services.ExecutePreConfiguredActions<AbpAspNetCoreMvcOptions>();
                options.ConfigureAbp(mvcOptions);
            });
        }
    }
```

**Comment by hikalkan** [comment]
>build-in Abp's modules APIs did not list in the swagger doc

swagger is not supporting asp.net core 3 as I know, so I can't test it for now (@maliming was working on it, but I didn't check the result). However, before asp.net core 3.0 upgrade, all the module APIs were already shown in the swagger, there was no issue.

**Comment by 274188A** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1323
