### ISSUE TITLE
FastEndpoint Support

### ISSUE THREAD

**Issue by lommez** [abpframework/abp#19230]
Hi...
Do you know the library FastEndpoint?
Maybe could be a interesting thing to be supported by Abp!
Coud you evaluate that?

Here is the website: [https://fast-endpoints.com/](https://fast-endpoints.com/ )

Thanks

**Comment by leonkosak** [comment]
I was wondering if there would be performance difference if all abp would be rewritten to Minimal API.
What do you think @maliming?

**Comment by maliming** [comment]
I think there might be a performance gain but not much.

**Comment by maliming** [comment]
I'll look into abp with minimal API.

**Comment by leonkosak** [comment]
> I'll look into abp with minimal API.

@maliming you are trying to say that you will evaluate if there would be enough performance benefit to replace "controller API" (currently used in abp) with MinimalAPI and keep all existing (implemented) "rich" features that are part of abp framework?

**Comment by lommez** [comment]
@leonkosak 
I think I could perhaps try to keep both things, and it's up to the end user to decide which type of API they want to use, the minimal one or the more robust one.

**Comment by leonkosak** [comment]
@lommez can you have both API "types" (controller and Minimal) in the same solution at the same time or do you suggest an additional option in abp cli (or abp suite for Commercial) for generating project?

**Comment by lommez** [comment]
@leonkosak
Initially, I had thought about having an option in abp-cli for generating the application with minimal API.
But if it is possible to have both options running at the same time, it would be very interesting.
