### ISSUE TITLE
 change ABP Prefix to custom name

### ISSUE THREAD

**Issue by pranavpatil19** [abpframework/abp#1924]
public class BlogModule : **Abp**Module
{        
}

[DependsOn(typeof(**Abp**AspNetCoreMvcModule))]
[DependsOn(typeof(**Abp**AutofacModule))]
public class BlogModule
{
}

**Comment by maliming** [comment]
Can you talk about it in detail?

**Comment by pranavpatil19** [comment]
i am working on micro-service project. So i decide to use abp project  as base project for that.  in abp project satisfy my all requirement. yesterday i demonstrate this project to my senior . he give me a suggestion to remove  AbpModule to  Module or any Custom prefix like XYZModule .

IS this possible . if yes  then how???


public class BlogModule : AbpModule
{
}

to

public class BlogModule : XyxModule
{
}


[DependsOn(typeof(AbpAspNetCoreMvcModule))]
[DependsOn(typeof(AbpAutofacModule))]
public class BlogModule
{
}

to

[DependsOn(typeof(XyxAspNetCoreMvcModule))]
[DependsOn(typeof(XyxAutofacModule))]
public class BlogModule
{
}

**Comment by maliming** [comment]
Most people will let us add prefixes to modules, options, etc. abp stuff.

I don't understand why you want to remove/change it.

**Comment by pranavpatil19** [comment]
i am happy with abp prefix. but Team senior member ask me  what is abp? why you write abp?  so they suggest me to change  abp prefix  or dont write abp there ..

**Comment by hitaspdotnet** [comment]
Don't span your time, ask your senior to read [ABP.io](abp.io) to understanding what is abp. If you changed prefixes you may lose any future updates.
@maliming Maybe changing ownership of the product from ABP to TeamSeniorXYZ.
I suggest you to read [LICENSE](https://github.com/abpframework/abp/blob/dev/LICENSE).

**Comment by hikalkan** [comment]
You mean you download the ABP source code, modify it and use in your company as an internal framework.
Then you will not be able to get new features and bugfixes we add? I don't think you want that.
On the other hand, it is impossible to make Abp prefix changeable per project.

Also, check the license: https://github.com/abpframework/abp/blob/dev/LICENSE (GNU Lesser General Public License v3.0) You should follow the license rules.
