### ISSUE TITLE
ExceptionHandling

### ISSUE THREAD

**Issue by myn1ckname** [abpframework/abp#19263]
Hi 👋
I'm having a few problems with exception handling.
I have an ```IActionFilter``` that does this
``` cs
    public void OnActionExecuted(ActionExecutedContext context)
    {
        if (context.Exception is HttpResponseException httpResponseException)
        {
            var problemDetails = _problemDetailsFactory.CreateProblemDetails(
                httpContext: context.HttpContext,
                statusCode: httpResponseException.StatusCode);

            foreach (var (key, value) in httpResponseException.Extensions)
            {
                problemDetails.Extensions.Add(key, value);
            }

            context.Result = new ObjectResult(problemDetails)
            {
                StatusCode = problemDetails.Status,
            };

            context.ExceptionHandled = true;
        }
    }
```
but then I hit an ```AbpExceptionFilter``` and my response is corrupted 🤬

You shouldn't handle this if ```context.ExceptionHandled is true```
https://github.com/abpframework/abp/blob/5624a46f410c5ba33396abf70054ae19512ab611/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs#L66

And I don't like that either
https://github.com/abpframework/abp/blob/5624a46f410c5ba33396abf70054ae19512ab611/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs#L81

Just use ```context.ExceptionHandled = true``` like Microsoft

**Comment by maliming** [comment]
hi

We will make this change in 8.2.
https://github.com/abpframework/abp/pull/19268
