### ISSUE TITLE
Validation popup not displaying in multiline

### ISSUE THREAD

**Issue by sephit** [abpframework/abp#19274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The popup shown with the validations of the form that contains more than one error is displayed in a single line instead of multiple lines.

### Reproduction Steps

Create a form with inputs and make validations on it and display those using abp framework method abp.message.error("")
![image](https://github.com/abpframework/abp/assets/6320029/a8d846e2-b6c8-4b48-9715-fa85fb036c21)

### Expected behavior

The details of the validation should be multiline

### Actual behavior

It's displaying in a single line even if it has more than 1 validation

### Version

8.1.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi @sephit 

Can you share a simple project?

Thanks.

**Comment by sephit** [comment]
Hi @maliming ,
I will send you a demo project to your email.

**Comment by maliming** [comment]
hi

I will make it support `\n`.

The final alert looks like:

![image](https://github.com/abpframework/abp/assets/6908465/35197b21-6e43-48aa-bb40-b805c2701a94)

https://github.com/sweetalert2/sweetalert2/issues/2368#issuecomment-1000873297
