### ISSUE TITLE
Extend DI documentation for classes with multiple interfaces

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#19280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The documentation doesn't describe how exposing the interfaces for a class with multiple interfaces can change the instantiation behavior (for singleton and scoped lifetime)

### Describe the solution you'd like

We have 2 behaviors:
1. Single instance for every interface (exposing all interfaces **but not** the class itself)
2. Shared instance between interfaces (exposing all interfaces **and** the class itself)

This should be made clear in the [ExposeService Attribute](https://docs.abp.io/en/abp/latest/Dependency-Injection#exposeservices-attribute) section.

But the behavior itself gives you two limits: 
1. you cant expose the interfaces only with a shared instance
2. you cant expose the implementation class with separate instances for each interface

( well you can always fall back to manually register those cases )

### Additional context

This is somehow surprising: you might try to prevent the usage of the implementation class by only exposing the interfaces but result in having multiple singleton instances (one for each interface).

Maybe this is even classified as bug, because you change the behavior (that is defined by the Dependency attribute) by the way you use the ExposeServices attribute

**Comment by maliming** [comment]
hi @puschie286 

Can you share some code to explain this?

Thanks.

**Comment by puschie286** [comment]
sure:
```c#
interface IFirstSingle;
interface IFirstMulti;
interface ISecondSingle;
interface ISecondMulti;

[ExposeServices( typeof( SingleInstance ), typeof( IFirstSingle ), typeof( ISecondSingle ) )]
class SingleInstance : IFirstSingle, ISecondSingle, ISingletonDependency;

[ExposeServices( typeof( IFirstMulti ), typeof( ISecondMulti ) )]
class MultipleInstances : IFirstMulti, ISecondMulti, ISingletonDependency;

public class TestClass
{
	public void Test( IServiceProvider provider )
	{
		var firstSingle = provider.GetService<IFirstSingle>();
		var secondSingle = provider.GetService<ISecondSingle>();
		
		Debug.Assert( firstSingle == secondSingle );

		var firstMulti = provider.GetService<IFirstMulti>();
		var secondMulti = provider.GetService<ISecondMulti>();
		
		Debug.Assert( firstMulti != secondMulti );
	}
}
```
its just example code, but this is the behavior you will see when using ABP auto registration process

**Comment by maliming** [comment]
hi

In this case, you only added 2 services(`IFirstMulti` and `ISecondMulti`) to DI. They cannot get a unique implementation because `IFirstMulti` and `ISecondMulti` are different.

>  you can always fall back to manually register those cases

You have to add a new service to the DI to `manually register those cases`

```cs
[ExposeServices( typeof( IFirstMulti ), typeof( ISecondMulti ) )]
class MultipleInstances : IFirstMulti, ISecondMulti, ISingletonDependency;
```

**Comment by puschie286** [comment]
Yes, i understand that - but its still somehow surprising that ExposeServices can change the behavior. Would be great if the documentation state something like "If you dont expose the class itself, each interface get their own instance"

**Comment by maliming** [comment]
Thanks. I will mention this in the document.
