### ISSUE TITLE
Microservice Demo - Can I get current user permissions?

### ISSUE THREAD

**Issue by WilliamXu96** [abpframework/abp#1929]
Hello,
I have one question about Permission system in Microservice demo project.
Can I get current user permissions like AspNet Zero？

**Comment by maliming** [comment]
`IPermissionManager.GetAllForUserAsync(user.Id)`

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/identity/test/Volo.Abp.Identity.Domain.Tests/Volo/Abp/Identity/PermissionManager_Tests.cs#L66

**Comment by WilliamXu96** [comment]
Okay, I see it, thanks.
