### ISSUE TITLE
IGuidGenerator doesn't work when inserting a new entity

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#1931]
Id(Guid type) property will be set when this line of code is executed. But it is not generated by `IGuidGenerator`.
https://github.com/abpframework/abp/blob/6a05ad36ead31fa5534cfbba3e43115152af6f87/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/EfCoreRepository.cs#L57

`SaveChangesAsync` method in `AbpDbContext.cs` will generate a correct Guid for Id property, but it doesn't work if Id already has a not empty value before `SaveChangesAsync` method run.
https://github.com/abpframework/abp/blob/fa56017647748e502b2524fc57f59d1a026f8424/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L189

We should ensure that all the Guids are created by `IGuidGenerator`, so ef core should never generate a value for Id of Guid type.
We can set FluentAPI `ValueGeneratedNever` for entities one by one, but it is unattractive.
https://www.learnentityframeworkcore.com/configuration/fluent-api/valuegeneratednever-method

Another way is using attribute `[DatabaseGenerated(DatabaseGeneratedOption.None)]`, but `Entity<T>` is a Generic class, not easy to customize for Guid Id.
https://www.learnentityframeworkcore.com/configuration/data-annotation-attributes/databasegenerated-attribute

So I try to replace the new Id(which generated by ef core provider) to Guid.Empty.
https://github.com/gdlcf88/abp/commit/d1c2754a05824c835d7ce090d71871bd96c88ad8#diff-a0cb792ce4dcc78227affdc1b9e1ec26R66
But it only help with current entity, related entities still have wrong Id.

So what can we do? Do you want to set `ValueGeneratedNever` for each Guid key entity?

**Comment by maliming** [comment]
Entity Framework Core does not implement a value generation strategy. Database providers differ in the way that values are automatically generated. Some will generated values for selected data types such as Identity, rowversion, GUID. Others may require manual configuration such as setting default values or triggers.

**Comment by gdlcf88** [comment]
We should ensure Guid Id always created by `IGuidGenerator`, but obviously not now.

**Comment by gdlcf88** [comment]
This method can help, but it also override the `b.Property(e => e.Id).ValueGeneratedNever()` settings in `DbContextModelCreatingExtensions.cs`.
https://github.com/gdlcf88/abp/commit/8f32a90a17cc8537b44c51c164b966e4aca5d853

**Comment by gdlcf88** [comment]
But if there are more than 1 new entities have Guid.Empty id, it throw this error:

> [ERR] The instance of entity type 'OrderItem' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

**Comment by gdlcf88** [comment]
https://github.com/abpframework/abp/issues/1580
After removing setter of Id property, it becomes harder. Cannot find a way to set correct Id for Entity which maps from Dto.

**Comment by yekalkan** [comment]
> Cannot find a way to set correct Id for Entity which maps from Dto

Mapping from dto to entity is not suggested. You need to use constructor.

**Comment by gdlcf88** [comment]
See https://github.com/abpframework/abp/issues/4631
