### ISSUE TITLE
Modal warns browser before window refresh even with `SUPPRESS_UNSAVED_CHANGES_WARNING` set to true

### ISSUE THREAD

**Issue by ayyash** [abpframework/abp#19310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There are two lines that go against each other in this file:
https://github.com/abpframework/abp/blob/125395a93b08c0116a5832a56494e46e477e12c2/npm/ng-packs/packages/theme-shared/src/lib/components/modal/modal.component.ts#L208

```
 fromEvent(window, 'beforeunload')
      .pipe(takeUntil(this.destroy$))
      .subscribe(event => {
        // TODO: check this
        if (!this.isFormDirty || this.suppressUnsavedChangesWarning) {
          event.preventDefault();
        }
      });
```

According to documentation, `suppressUnsavedChangesWarning` needs to be set to true to get rid of the notification, but on window refresh, I still get the browser confirmation because it returns `event.preventDefault`, it should be like the one in line 172:
```
if (this.isFormDirty && !this.suppressUnsavedChangesWarning) {
```

Although we're using 7.3 but the 8.0 version has not changed. 

### Reproduction Steps

- Set `{ provide: SUPPRESS_UNSAVED_CHANGES_WARNING, useValue: true },` in app.module
- Go to Saas>Tenants of the host application (a Volosoft module)
- Select to "login with this tenant" to impersonate. 

### Expected behavior

The browser alert should not appear

### Actual behavior

Right after you click "login" the browser alerts `Changes you made may not be saved`.

### Version

7.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by Sinan997** [comment]
Hi, it will be fixed in next patch version. You can see the related PR above.
