### ISSUE TITLE
Is there a reason why ValueObject base class doesn't override Equals(object? obj)

### ISSUE THREAD

**Issue by davidliang2008** [abpframework/abp#19311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The abstract base class `ValueObject` doesn't override `object`'s `Equals()` method. So if you do `==` or `.Equals()` between 2 value objects, you will always get `false`.

To be fair, there are 2 workarounds you can do, but in my opinion they're both not convenient, and they require you to put extra code in every single value object in your application.

You can also create another abstract class that inherits from `ValueObject`, but why not just override `Equals()` at the first place? I mean, by definition, isn't the equality of two value object the equality of each property within the value object? And when I do comparison between two value objects using `==`, I was expecting just that.

### Reproduction Steps

```c#
public class Permission : ValueObject, IComparable<Permission>
{
	public string Scope { get; private set; }

	public Permission(string scope)
	{
		Check.NotNullOrWhiteSpace(scope, nameof(scope));

		Scope = scope;
	}

	protected override IEnumerable<object> GetAtomicValues()
	{
		yield return Scope;
	}

	public int CompareTo(Permission? other)
	{
		return string.Compare(Scope, other?.Scope, StringComparison.Ordinal);
	}
}
```

This is a simple Value Object class that presents the permission scope. One of the example scope values would be just a string such as `resource1:area1:subarea1:read`.

And when I compare two of these Value Objects,
```c#
var scope = "scope";
var permission1 = new Permission(scope);
var permission2 = new Permission(scope);

Console.WriteLine($"==?: {permission1 == permission2}");
Console.WriteLine($"Equals()?: {permission1.Equals(permission2)}");
```

### Expected behavior

I would expect them to be
```c#
// Output:
// ==?: True
// Equals()?: True
```

### Actual behavior

```c#
// Output:
// ==?: False
// Equals()?: False
```

demo: https://dotnetfiddle.net/APJKYS

### Known Workarounds

There are 2 workarounds:

1. Use `ValueEquals()` instead:
   ```c#
   Console.WriteLine($"ValueEquals()?: {permission1.ValueEquals(permission2)}");

   // Output:
   // ValuEquals()?: True
   ```
2. Override `Equals(object? obj)` to use `ValueEquals` (will also need to override `GetHashCode()` and add operator overloading to `==` and `!=`)
   ```c#
   public class Permission : ...
   {
       ...

       public override bool Equals(object? obj)
       {
           if (obj == null)
           {
               return false;
           }

           return ValueEquals(obj);
       }

       public override int GetHashCode() { ... }
   }
   ```

### Version

8.0.5

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
I think this is the design idea of ​​`ValueEquals`. That is, it will not `override Equals` method.

**Comment by davidliang2008** [comment]
Fair enough. I might just go with the workaround # 2 for now, but will have to remember to do so on every value object I have.

I was just thinking if the Value Object base overrides the `Equals()`, it will automatically solve the issue #19312.

Anyway, I will mark this as Close. Thanks for your quick response :)
