### ISSUE TITLE
About Documentation

### ISSUE THREAD

**Issue by emreerkoca** [abpframework/abp#1932]
- Open this page. https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template 
- Scroll down to this "Using EF Core Update-Database Command" 

Users can' t fully understand this sentence. "Right click to the **.Web** project and select Set as StartUp Project:" When they read it, they search ".Web" into solution. Sentence can be like these "Right click to the **.HttpApi.Host"** project and select Set as StartUp Project:" or "Right click to the Web application and select Set as StartUp Project:"

Regards.

**Comment by maliming** [comment]
I will update the documentation, thanks for feedback.

**Comment by emreerkoca** [comment]
You' re welcome @maliming
