### ISSUE TITLE
Acme.BookStore sample - throws exception adding new Book

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#1934]
Starting from a brand new clone of repo, run the Bookstore sample after carrying out the required db migrations.

**Steps**
1) Clone Repo
2) Run migrations
3) Run Bookstore sample
4) Login
5) Try to add a new Book

**Error:**
>System.ArgumentException
  >HResult=0x80070057
  >Message=Acme.BookStore.Book needs to have a constructor with 0 args or only optional args.
  >Source=<Cannot evaluate the exception source>
  >StackTrace:
><Cannot evaluate the exception stack trace>

**Comment by maliming** [comment]
Is it this one?
https://github.com/abpframework/abp/tree/dev/samples/BookStore

**Comment by 274188A** [comment]
yes

**Comment by maliming** [comment]
Before this pr merge, you can manually modify the Book class.
https://github.com/abpframework/abp/pull/1894/files#diff-f926b79ef8caafa4634bdb2b89e771f1R16
