### ISSUE TITLE
Separate Incoming Events by Tenants. Is it possible?

### ISSUE THREAD

**Issue by Gilcemir** [abpframework/abp#19358]
Hi,
I'm using abp framework 7.0, mongodb and EFCore as database providers (we have microservice architecture). RabbitMQ as message broker and Redis as Cache Provider.

Our app main microservice is Multi-tenant. Last week we had a problem with our Incoming events processing, which one event was stucked on the incoming events, the same event was beeing processed over and over again, and all events from all tenants were growing large on the Incoming events.
This was a coding problem, of course, but I was thinking what we could do to minimize this kind of problem. Since we deploy every day, this can happen again...

I read about the [Outbox/Inbox](https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#outbox-configuration) config, and I thought If I could process those events in FIFO but separated by tenant. I wasnt able to do that here, so I dont know if it is possible.
If it is not, do you guys have any suggestion for this kind of problem?
If it is, can you provide a coding example?
Thanks

**Comment by maliming** [comment]
hi

Currently this is not possible, you can customize this code for your tenants, for example by creating separate processors for certain tenants.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/Distributed/InboxProcessor.cs#L93-L118

**Comment by Gilcemir** [comment]
Thanks

**Comment by sulaimanmugahed** [comment]
> Thanks

hi, did u find a solution?

**Comment by Gilcemir** [comment]
> > Thanks
> 
> hi, did u find a solution?

No :/
