### ISSUE TITLE
Angular: `ABP.Route` items shows only once when has same name

### ISSUE THREAD

**Issue by mustafapsd** [abpframework/abp#19359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to add the same menu item with **different** `parentName` properties, but only the last item appears, the above is not. When I change its name, it appears as well. I want to have the same names.

### Reproduction Steps

Try this config:
```typescript
[
  {
    path: '/',
    name: 'Parent',
    iconClass: 'fas fa-star',
    order: 2,
  },
  {
    path: '/test-url',
    name: 'TestUrl',
    iconClass: 'fas fa-star',
    order: 3,
    parentName: 'Parent',
  },
  {
    path: '/test-url',
    name: 'TestUrl',
    iconClass: 'fas fa-star',
    order: 4,
  }
]
```

You will see only the second will be rendered.

This will not also work:
```typescript
{
  path: '/',
  name: 'Parent',
  iconClass: 'fas fa-star',
  order: 2,
},
{
  path: '/test-url',
  name: 'TestUrl',
  iconClass: 'fas fa-star',
  order: 3,
  parentName: 'Parent',
},
{
  path: '/different-url',
  name: 'TestUrl',
  iconClass: 'fas fa-star',
  order: 4,
},
```

### Expected behavior

I should see every item I added to the config. Even if they duplicate, I want it, or I can remove it. 

![Screenshot 2024-03-20 at 13 32 23](https://github.com/abpframework/abp/assets/61491079/8b3bd2e1-8217-4839-9ff7-6f557d054609)

### Actual behavior

`ABP.Route` items with the same `name` property do not appear.

![Screenshot 2024-03-20 at 13 32 37](https://github.com/abpframework/abp/assets/61491079/d4e8a98b-0fbc-46fd-8bcf-84bb269532ee)

### Version

8.0.5

**Comment by Sinan997** [comment]
This is not bug, It was designed as this way. 

May i know why do you want them to be same name

**Comment by mustafapsd** [comment]
Well, as I said this is a **manual** config. If I added 2 Items, I'll want 2 items. However, the case is two different items inside the two different **Parents**. 

## Case 1
I have links. I want to add a **_QuickLink_** group where that user can add the link from the menu dynamically. If the user adds a link, it should appear in the **_Quicklink_** group, also its group.

## Case 2
I have two different groups: `GroupA` and `GroupB`. They both have dashboards. I want to achieve this:

Config:
```typescript
      {
        name: 'GroupA',
        iconClass: 'fas fa-star',
      },
      {
        name: 'Dashboard',
        path: '/groupA/dashboard',
        iconClass: 'fas fa-tachometer-alt',
        parentName: 'GroupA',
      },
      {
        name: 'GroupB',
        iconClass: 'fas fa-star',
      },
      {
        name: 'Dashboard',
        path: '/groupB/dashboard',
        iconClass: 'fas fa-tachometer-alt',
        parentName: 'GroupB',
      },
```

The output does not have even `GroupA` because its children have filtered, and become empty:
![Screenshot 2024-03-20 at 15 01 54](https://github.com/abpframework/abp/assets/61491079/46e087c8-1e3e-4835-8487-c8f9b1d45aa9)

What I expect (I did with HTML in the inspector):
![Screenshot 2024-03-20 at 15 04 38](https://github.com/abpframework/abp/assets/61491079/f7458d42-35f0-47b5-8a1a-6dc4ee891f9c)

@Sinan997

**Comment by mustafapsd** [comment]
Hello, do you think you'll plan to fix it soon? I can contribute too if you are too busy. @Sinan997

**Comment by Sinan997** [comment]
Hi @mustafapsd, if you can, why not. Thank you in advance
