### ISSUE TITLE
Check and update the zh-hans document.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#19366]
https://github.com/abpframework/abp/tree/dev/docs/zh-Hans

**Comment by ebicoglu** [comment]
you can update the Chinese localization after this[ issue completes](https://github.com/volosoft/vs-internal/issues/3690) 
because the localizations (docs+abp.io) will change so much.

**Comment by maliming** [comment]
I'll try to use OpenAI's translation service to translate all documents outside of English and keep them in markdown format and abp style.

**Comment by maliming** [comment]
Will be fixed by https://github.com/abpframework/abp/pull/20181
