### ISSUE TITLE
Alerts are not dismissible in Blazor Server

### ISSUE THREAD

**Issue by MannRobertJ** [abpframework/abp#19374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When creating an alert with dismissible set to true there is no button available to dismiss the alert.

### Reproduction Steps

Create a new Blazor Server project

    abp new DismissibleAlerts -u blazor-server -dbms SQLite --theme basic -csf

Run the DbMigrator Project

Replace Index.razor.cs with 

    namespace DismissibleAlerts.Blazor.Pages;

    public partial class Index
    {
        protected override void OnInitialized()
        {
            Alerts.Success("Dismissible True", dismissible: true);
            Alerts.Success("Dismissible False", dismissible: false);
        }
    }

Run the Blazor project.

### Expected behavior

The first Alert is dismissible. The second is not.

### Actual behavior

Neither alert is dismissible.

### Regression?

Unknown.

### Known Workarounds

None.

### Version

8.0.5

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

I initially noticed this problem using the LeptonX Lite Theme. However the problem also occurs with the Basic Theme.

The problem occurs in Firefox, Edge and Chrome. I have not tried any other browsers.

**Comment by MannRobertJ** [comment]
It just occurred to me that I should really post a screenshot.

Here's a screenshot from your [website](https://docs.abp.io/en/abp/latest/UI/Blazor/Page-Alerts):

![image](https://github.com/abpframework/abp/assets/16478695/4ec59c92-fc29-40ea-9a62-b0c473464b5a)

Notice the dismiss button in the top right.

Here's a screenshot from my locally running version of ABP with Blazor Server:

![image](https://github.com/abpframework/abp/assets/16478695/c8e04ebe-ad25-4a56-8577-ae3cd5a6d3df)

Notice the lack of a dismiss button.

**Comment by maliming** [comment]
hi
I will check this.

**Comment by maliming** [comment]
hi

https://github.com/abpframework/abp/pull/19388

**Comment by MannRobertJ** [comment]
Fast fix! 

Will this be in 8.0.6?

**Comment by maliming** [comment]
> Fast fix! 
> 
> 
> 
> Will this be in 8.0.6?

yes
