### ISSUE TITLE
"Consider marking event handler as 'passive' to make the page more responsive." console warning in Blazor Server

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#19403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I´m getting the following **warning** in the console

 ```
Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
autoNumeric.js?v=1.4.2.0:6 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
value @ autoNumeric.js?v=1.4.2.0:6
B @ autoNumeric.js?v=1.4.2.0:6
initialize @ numericPicker.js?v=1.4.2.0:13
(anonymous) @ Blazor.LeptonTheme.Global.BA9D3DAEB2B7953F5B34F351DA325FDA.js?_v=638466737001834207:2
beginInvokeJSFromDotNet @ Blazor.LeptonTheme.Global.BA9D3DAEB2B7953F5B34F351DA325FDA.js?_v=638466737001834207:2
_invokeClientMethod @ Blazor.LeptonTheme.Global.BA9D3DAEB2B7953F5B34F351DA325FDA.js?_v=638466737001834207:2
_processIncomingData @ Blazor.LeptonTheme.Global.BA9D3DAEB2B7953F5B34F351DA325FDA.js?_v=638466737001834207:2
connection.onreceive @ Blazor.LeptonTheme.Global.BA9D3DAEB2B7953F5B34F351DA325FDA.js?_v=638466737001834207:2
e.onmessage @ Blazor.LeptonTheme.Global.BA9D3DAEB2B7953F5B34F351DA325FDA.js?_v=638466737001834207:2
autoNumeric.js?v=1.4.2.0:6 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

![image](https://github.com/abpframework/abp/assets/2386572/ec889034-4fcf-4d3a-a6fa-c08fce0c9a70)

### Reproduction Steps

Create Blazor Server (commercial) 8.0.4

### Expected behavior

no warnings

### Actual behavior

console warnings

### Regression?

never seen this before (was on 7.x last one)

### Known Workarounds

n/a

### Version

8.0.4

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
This is related to some `js` functions in **lepton** theme.

**Comment by enisn** [comment]
It seems it's included in the LeptonX theme javascript bundle and it's not included in the Blazor project.

@masumulu28  can you take a look at it?

**Comment by masum-ulu** [comment]
Hi @sturlath this is not a bug and it comes from `autoNumeric.js` package. We'll check for it in lepton-x theme we might update version if it's old.
