### ISSUE TITLE
Compatibility Issues with primeNG Styles After Upgrading ABP and Angular Versions

### ISSUE THREAD

**Issue by alvagabriel** [abpframework/abp#19402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We have been utilizing the ABP Framework version 7 alongside Angular version 15 for the past few months and decided to incorporate primeNG version 15.4.1 for its components, which introduced minimal breaking styling issues. This week, we made a decision to update both ABP and Angular to their latest versions and simultaneously upgraded primeNG to version 17.12.0. Following this upgrade, we encountered significant styling conflicts.

It appears that primeNG has revised its styling implementation, now employing CSS layers for its styles. This change has led to Bootstrap, as utilized within ABP (which does not employ CSS layers), overriding many of the primeNG styles. Furthermore, it seems we cannot manually integrate CSS layers into ABP's Bootstrap version due to constraints outlined in the "Angular UI: Theme Configurations" section of the ABP documentation for version 6, which states: "Theme packages no longer import styles as CSS modules."

Given these circumstances, we are seeking guidance or a known solution for integrating the latest version of primeNG with the ABP Framework. Is there a recommended approach or workaround to resolve the styling conflicts arising from the primeNG upgrade?

### Version

8.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by kiennc** [comment]
I have same issues. Bassicly,Bootstrap's grid system is conflict with primeNG. Because Bootstrap has too less UI component then i must use primeNG.

**Comment by kiennc** [comment]
@Sinan997 I found this commit https://github.com/abpframework/abp/commit/63b74254fef7b38c965daf571c9a362aae80041c.
I followed it, managed to get the interface, but I had to manually disable some Bootstrap properties to make the interface look better, although it still doesn't quite resemble the PrimeFace demo. I'm using laster version of primeNg, Angular, Abp ("@abp/ng.core": "~8.0.4", "@angular/core": "~17.0.0",  "primeng": "^17.12.0",)
![image](https://github.com/abpframework/abp/assets/54437842/f16e2ec6-c27f-4d5f-beb7-44413ce26aae)

**Comment by Sinan997** [comment]
I have researched what we can do in ABP but it seems there is nothing we can do because this is not related to ABP. Maybe we can switch `@layer` in the future but even if we switch there will be conflicts.

You have to find the broken places and override them by your own, [The PrimeNG author has made a video about 
 it](https://www.youtube.com/watch?v=EPRUy0lvgBA), i recommend you to check this video.

**Comment by kiennc** [comment]
Thank you. If that's the case, there will be a lot of editing needed. Are you intending to use another UI library? Because ng-bootstrap has very few components.

**Comment by Sinan997** [comment]
We have no plans for that at the moment
