### ISSUE TITLE
UserFriendlyException is showing 2 error popups in frontend

### ISSUE THREAD

**Issue by JigneshBuoyancy** [abpframework/abp#19432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For Validation purpose, I am throwing a UserFriendlyException from the application service after validating the data, but when the response come in the front end, with 403 error code, It is showing 2 error popups. One with the error message sent by me from the code and the other error popup is "**Error detail not sent by server.**". 

Please have a look at attached video recording of overlapping an error messages.

https://github.com/abpframework/abp/assets/128613140/2a25fd65-c85e-4d02-bcd3-b41569b137d1

Please help me to get it resolved.

Thank you

### Reproduction Steps

Return **throw new UserFriendlyException(L["ErrorMsg"])** from any of the app service.

### Expected behavior

Application should only show error message return from the user friendly exception. 

### Actual behavior

Application is showing one extra error message popup. 

### Regression?

Not sure

### Known Workarounds

I am unable to find the workaround as of now.

### Version

7.4.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

I think it should be with the api response error code as we are returning 403 for userfriendly exception.

**Comment by Sinan997** [comment]
Hi, are you using sweetalert?
If you don't want to show abp default you can pass `skipHandleError: true` to config object, before making a network request. [For more info](https://docs.abp.io/en/abp/7.4/UI/Angular/HTTP-Requests#how-to-disable-default-error-handler-of-restservice)

**Comment by Sinan997** [comment]
You can re-open the issue if your problem still continues.
