### ISSUE TITLE
Unable to compile the angular code after upgraded to 8.0.5 

### ISSUE THREAD

**Issue by vipulbuoyancy** [abpframework/abp#19452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have upgraded my code base & ABP version to 8.0.5 from 7.4.0 and successfully able to run the backend code for .net, But when I started upgrading the Angular code I am getting attached error message. I think its something related to version but I am unable to figure it out. Below is my package config. Can you please help me with the correct version if needed.

![pkg1](https://github.com/abpframework/abp/assets/80636669/f8885d70-99cc-435e-b9de-9d1d16c335b0)
{
  "name": "project",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --open",
    "build": "ng build",
    "build:prod": "ng build --configuration production",
    "build:dev": "ng build --configuration development",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@abp/ng.components": "~8.0.5",
    "@abp/ng.core": "~8.0.5",
    "@abp/ng.oauth": "~8.0.5",
    "@abp/ng.setting-management": "~8.0.5",
    "@abp/ng.theme.shared": "~8.0.5",
    "@angular-material-components/datetime-picker": "^16.0.1",
    "@angular/animations": "^17.3.1",
    "@angular/cdk": "^17.3.1",
    
    "@angular/material": "^17.3.1",
    "@angular/common": "~17.3.1",
    "@angular/compiler": "~17.3.1",
    "@angular/core": "~17.3.1",
    "@angular/forms": "~17.3.1",
    "@angular/localize": "~17.0.9",
    "@angular/platform-browser-dynamic": "~17.0.9",
    "@angular/platform-browser": "~17.0.9",
    "@angular/router": "~17.3.1",

    "@fullcalendar/angular": "^6.1.9",
    "@fullcalendar/core": "^6.1.9",
    "@fullcalendar/daygrid": "^6.1.9",
    "@ngtools/webpack": "^16.2.13",
    "@volo/abp.commercial.ng.ui": "~8.0.5",
    "@volo/abp.ng.account": "~8.0.5",
    "@volo/abp.ng.audit-logging": "~8.0.5",
    "@volo/abp.ng.gdpr": "~8.0.5",
    "@volo/abp.ng.identity": "~8.0.5",
    "@volo/abp.ng.language-management": "~8.0.5",
    "@volo/abp.ng.openiddictpro": "~8.0.5",
    "@volo/abp.ng.saas": "~8.0.5",
    "@volo/abp.ng.text-template-management": "~8.0.5",
    "@volo/ngx-lepton-x.core": "~3.0.5",
    "@volosoft/abp.ng.theme.lepton-x": "~3.0.1",
    "angular-calendar": "^0.31.0",
    "angular-moment": "^1.3.0",
    "angular-oauth2-oidc": "^15.0.1",
    "fullcalendar": "^6.1.9",
    "ng-image-fullscreen-view": "^3.0.3",
    "ng-multiselect-dropdown": "^1.0.0",
    "ng2-pdf-viewer": "^10.0.0",
    "ngx-color-picker": "^16.0.0",
    "ngx-lightbox": "^3.0.0",
    "ngx-mat-datetime-picker": "^3.0.0",
    "print-js": "^1.6.0",
    "rxjs": "7.8.1",
    "sweetalert2": "^11.7.32",
    "tslib": "^2.6.2",
    "zone.js": "~0.14.0"
  },
  "devDependencies": {
    "@abp/ng.schematics": "~8.0.5",
    "@angular-devkit/build-angular": "^17.3.2",
    "@angular-eslint/builder": "^17.3.0",
    "@angular-eslint/eslint-plugin": "~17.3.0",
    "@angular-eslint/eslint-plugin-template": "~17.3.0",
    "@angular-eslint/schematics": "^17.3.0",
    "@angular-eslint/template-parser": "~17.3.0",
    "@angular/cli": "^17.3.2",
    "@angular/compiler-cli": "^17.3.1",
    "@angular/language-service": "^17.3.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^20.8.6",
    "@typescript-eslint/eslint-plugin": "^6.9.1",
    "@typescript-eslint/parser": "^6.9.1",
    "eslint": "^8.51.0",
    "jasmine-core": "~5.1.1",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.1",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.1.0",
    "ng-packagr": "^17.3.0",
    "typescript": "^5.2.2"
  }
}

### Reproduction Steps

trying to upgrade the ABP version from 7.4.0 to 8.0.5 

### Expected behavior

It should compile the angular code & run

### Actual behavior

It is throwing error in ts-toolbelt plugin which is used in @abp/ng.core & lepton theme.

### Regression?

I have tried with different version of type script, Angular CLI.

### Known Workarounds

I don't have any work around as of now. I can't upgrade my project to 8.0.5 version due to this error.

### Version

8.0.5

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by Sinan997** [comment]
Hi, have you tried the remove all caches like `node_modules`, `yarn.lock` etc. If you didn't please delete them and run `yarn` command.

And may i know which package manager are you using

**Comment by vipulbuoyancy** [comment]
Hi Sinan, Yes I have tried multiple times by removing node modules & yarn.lock files. I am using yarn.

Thank you,

**Comment by Sinan997** [comment]
I have tried the reproduce your problem but i couldn't. I want to give you a sample `package.json` which works in version 8.0.5. This might help you to run your project. 

Try to make them same.

```json
"dependencies": {
  "@abp/ng.components": "~8.0.5",
  "@abp/ng.core": "~8.0.5",
  "@abp/ng.oauth": "~8.0.5",
  "@abp/ng.setting-management": "~8.0.5",
  "@abp/ng.theme.shared": "~8.0.5",
  "@volo/abp.commercial.ng.ui": "~8.0.5",
  "@volo/abp.ng.account": "~8.0.5",
  "@volo/abp.ng.audit-logging": "~8.0.5",
  "@volo/abp.ng.gdpr": "~8.0.5",
  "@volo/abp.ng.identity": "~8.0.5",
  "@volo/abp.ng.openiddictpro": "~8.0.5",
  "@volo/abp.ng.language-management": "~8.0.5",
  "@volo/abp.ng.saas": "~8.0.5",
  "@volo/abp.ng.text-template-management": "~8.0.5",
  "@volosoft/abp.ng.theme.lepton-x": "~3.0.1",
  "@angular/animations": "~17.0.0",
  "@angular/common": "~17.0.0",
  "@angular/compiler": "~17.0.0",
  "@angular/core": "~17.0.0",
  "@angular/forms": "~17.0.0",
  "@angular/localize": "~17.0.0",
  "@angular/platform-browser-dynamic": "~17.0.0",
  "@angular/platform-browser": "~17.0.0",
  "@angular/router": "~17.0.0",
  "rxjs": "~7.8.0",
  "tslib": "^2.0.0",
  "zone.js": "~0.14.0"
},
"devDependencies": {
  "@abp/ng.schematics": "~8.0.5",
  "@angular-devkit/build-angular": "~17.0.0",
  "@angular-eslint/builder": "~17.0.0",
  "@angular-eslint/eslint-plugin": "~17.0.0",
  "@angular-eslint/eslint-plugin-template": "~17.0.0",
  "@angular-eslint/schematics": "~17.0.0",
  "@angular-eslint/template-parser": "~17.0.0",
  "@angular/cli": "~17.0.0",
  "@angular/compiler-cli": "~17.0.0",
  "@angular/language-service": "~17.0.0",
  "@types/jasmine": "~3.6.0",
  "@types/node": "^12.0.0",
  "@typescript-eslint/eslint-plugin": "6.9.1",
  "@typescript-eslint/parser": "6.9.1",
  "eslint": "^8.0.0",
  "jasmine-core": "~4.0.0",
  "karma": "~6.3.0",
  "karma-chrome-launcher": "~3.1.0",
  "karma-coverage": "~2.1.0",
  "karma-jasmine": "~4.0.0",
  "karma-jasmine-html-reporter": "^1.0.0",
  "ng-packagr": "~17.0.0",
  "typescript": "~5.2.0"
}
```

**Comment by vipulbuoyancy** [comment]
Hi Sinan,

Yes, I have replaced sample package.json and then added my package on top of that and it started working.

Thank you.
