### ISSUE TITLE
how to add new theme to abp? any document?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#1946]
now day,the abp vnext use the default theme ,but I want use diffrent theme for example metronic.how to add new theme to abp vnext? any document? thanks

**Comment by yinchang0626** [comment]
I have the same question,and then i try to create one  before any  document , it maybe not correct way to do  a new theme but you can reference it https://github.com/yinchang0626/abp.ng?files=1

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/631
