### ISSUE TITLE
Server Error in '/' Application in abp.io website

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#1947]
If i navigate to abp.io I get the following error:

![image](https://user-images.githubusercontent.com/1365851/67145384-2196b400-f279-11e9-9252-6cb084cf58ad.png)

**Comment by ismcagdas** [comment]
Thanks for reporting this. Can you see a star sign when you click the address bar ? If so, removing it might help until we fix the problem.

**Comment by KevinFarrow** [comment]
Ah yes, the address changes to https://www.abp.io/*

**Comment by KevinFarrow** [comment]
BTW If I use www.abp.io it works fine

**Comment by ismcagdas** [comment]
@erolarkat sometimes I also face this problem. Could you check why there is * sign on the address bar ? This might be related to rewrite rule on IIS.

**Comment by gdlcf88** [comment]
Only `http://abp.io` redirects to error page, `https://abp.io` is ok.

**Comment by maliming** [comment]
It works now!  check out http://abp.io/
