### ISSUE TITLE
BlazorServer sometimes loosing letters in forms

### ISSUE THREAD

**Issue by lucashanak** [abpframework/abp#19473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I type into the form, characters randomly disappear. I have identified that it is caused by Validations with the setting Mode="ValidationMode.Auto". When I switch to Manual, it is OK.

### Reproduction Steps

https://www.loom.com/share/a9c40d54f4684ed689a6bb0df825b6e4?sid=521ba6cb-c263-4f0b-aad8-7ec3c2f56b65

BlazorServer + Postgresql app, created with ABP Suite.

### Version

8.0.3

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Can you reproduce this with the minimal code?

I think this is related to https://github.com/Megabit/Blazorise , I will report it to it.

**Comment by maliming** [comment]
hi @lucashanak 

Can you reproduce this with the minimal code?

You can test it with https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo/Pages/Tests/FormsPage.razor

**Comment by lucashanak** [comment]
The forms themselves work without any issues, as does /Tests/FormsPage.razor. The problem was caused by validations configured by ABP Suite. Switching to ValidationMode.Manual resolved the issue.

It's hard to reproduce without sharing the entire project. And after updating to 8.1, I tried switching back to Auto and it seems OK. So, it looks like it's resolved. Thanks.
