### ISSUE TITLE
Can't build project if new version is released

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#19482]
https://support.abp.io/QA/Questions/6981/Can%27t-build-project-if-new-version-is-released

@EngincanV 
Can we change the Leptonx theme version to the exact version number instead of a wildcard when creating a new project?
what do you think?

**Comment by enisn** [comment]
Yes, It makes sense for created projects. But check #19483 
We have to update nightly `(-preview)` versions for each version deployed for development purposes.

Still, I agree that created ABP projects should have specific version that is created with. 

Maybe we can use wildcard for development and CLI puts the specific version while project creation steps.

What do you think @EngincanV ?

**Comment by EngincanV** [comment]
> Yes, It makes sense for created projects. But check #19483 We have to update nightly `(-preview)` versions for each version deployed for development purposes.
> 
> Still, I agree that created ABP projects should have specific version that is created with.
> 
> Maybe we can use wildcard for development and CLI puts the specific version while project creation steps.
> 
> What do you think @EngincanV ?

I agree that we should specify the exact version of LeptonX Theme packages in abp template before every release. Doing this with CLI is easy but as we talked yesterday, this breaks the mentality of being able to release independent LeptonX releases and we would assume that the release schedule and cycle will be the same always. So, it occurs to me that the best option for now is to set the exact version for LeptonX Theme packages even before it's released (we should assume that it's released with the version that we specified).

**Comment by nebula2** [comment]
what if the cli would get the latest compatible leptonx version for the corresponding abp version (by hitting some api or something) on creation and then replaces on project creation?
