### ISSUE TITLE
Feature: Log out from other tabs automatically when user logout from the current tab

### ISSUE THREAD

**Issue by Sinan997** [abpframework/abp#19488]
- [x] Angular
- [x] Blazor
- [x] MVC

**Comment by realLiangshiwei** [comment]
Why there is no MVC UI @Sinan997

**Comment by Sinan997** [comment]
if you checked the pr in angular side, we need to add eventListener for storage.

But MVC is using ssr, so it seems like it can't be done in MVC.

**Comment by maliming** [comment]
> But MVC is using ssr, so it seems like it can't be done in MVC.

It seems we can do this in MVC.(multiple tabs)

![image](https://github.com/abpframework/abp/assets/6908465/17efc66d-9a66-4ad4-a47c-48ab0639deae)

**Comment by Sinan997** [comment]
> > But MVC is using ssr, so it seems like it can't be done in MVC.
> 
> It seems we can do this in MVC.(multiple tabs)
> 
> ![image](https://private-user-images.githubusercontent.com/6908465/321148967-17efc66d-9a66-4ad4-a47c-48ab0639deae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTQ5NjYsIm5iZiI6MTcxMjc1NDY2NiwicGF0aCI6Ii82OTA4NDY1LzMyMTE0ODk2Ny0xN2VmYzY2ZC05YTY2LTRhZDQtYTQ3Yy00OGFiMDYzOWRlYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMTMxMTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY5ZjUxMGQ4YzVhMTk3NjBkMTQwZTdiZTAwNzVlN2I0Yjk3OWU5MTgzNWZkZmEyNWVjMzI5YmVkZDA3MDg0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v30XydzBi8PO3051oQBjZMU3no8IrE2U-revAeuHmcI)

Nice! i am adding an MVC section to the issue
