### ISSUE TITLE
IdentityServer minor revison notes

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#195]
- [ ] Ensure that Guid foreign keys are set as required in the db.
- [ ] Add default field values to EF core model.
- [ ] Check consts. Ensure to not have inconsistents and too long constraints.
- [ ] Ensure that all necessary indexes are done.

**Comment by maliming** [comment]
Do we follow the constraints of Identity Server? For example: MaxLength, IsUnique, etc. There are some inconsistencies found.

![image](https://user-images.githubusercontent.com/6908465/66363727-c97aca80-e9b9-11e9-98c4-cc55609011e3.png)

**Comment by hikalkan** [comment]
I thought 2000 was too much, unnecessary and big numbers may have problems in some DBMSs. But I am not sure about it. It is better to align them. Please do it and send a PR.

**Comment by hikalkan** [comment]
This requires to add new migration for EF Core since it has some changes on table columns.

**Comment by maliming** [comment]
I will update the ef migration.

**Comment by hikalkan** [comment]
Great!
