### ISSUE TITLE
can not update ABP related packages  to last version with abp cli 8.1.0

### ISSUE THREAD

**Issue by codeCHN** [abpframework/abp#19509]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

![QQ图片20240407161425](https://github.com/abpframework/abp/assets/16838650/bc12adff-1ea5-420a-994a-0e7963eb3357)

### Version

8.1.0

### User Interface

Common (Default)

### Database Provider

None/Others

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
Hi, please wait for [this PR](https://github.com/abpframework/abp/pull/19500) to be merged to upgrade your project. We haven't completed our final tests for the stable version and therefore have not activated the stable version yet. So, it's normal to not be able to update your solution.

**Comment by EngincanV** [comment]
The PR is merged, please try again.
