### ISSUE TITLE
ABP 8.1 - Hangfire jobs are stuck in enqueued status  

### ISSUE THREAD

**Issue by jerinantony11** [abpframework/abp#19515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

HangFire jobs are stuck in the enqueued  status.

![image](https://github.com/abpframework/abp/assets/57087890/bdc91bf9-de84-4a10-b5b7-c3607a2221a7)

### Reproduction Steps

1) create a new project :- abp new Acme.BookStore -u angular
2) add hangfire module to the application project :- abp add-package Volo.Abp.BackgroundJobs.HangFire
3) follow the documentation to add sql server support https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire
4) add [Hangfire.SqlServer](https://www.nuget.org/packages/Hangfire.SqlServer) package.  Documentation doesn't say which version is compactable. I tried both the latest and 1.8.6 

![image](https://github.com/abpframework/abp/assets/57087890/f7608f12-ebde-4001-b798-bb191ae1bccc)
5) add hang-fire dashboard 
6) create an API and application service 

**JobAppService** 
`
public class JobAppService : BookStoreAppService, IJobApplicationService
{
    public Task CallJob()
    {
        var jobId = BackgroundJob.Enqueue<IBackgroundServiceManagement>(x => x.RunJOb());
        return Task.CompletedTask;
    }
}
`

**IBackgroundServiceManagement**

`namespace Acme.BookStore.jobs
{
    public interface IBackgroundServiceManagement
    {
        Task RunJOb();
    }
}`

**BackgroundServiceManagement** 

`
namespace Acme.BookStore.jobs
{
    public class BackgroundServiceManagement : IBackgroundServiceManagement
    {
        public Task RunJOb()
        {
            Console.WriteLine("Task executed");
            return Task.CompletedTask;
        }
    }
}
`

### Expected behavior

1. The Hang-Fire should enqueue the jobs successfully 

2. Enqueued jobs should get moved Scheduled--> Processing --> Succeeded/Failed 

### Actual behavior

The Hang-Fire should enqueue the jobs successfully  :-  working as expected
Enqueued jobs should get moved Scheduled--> Processing --> Succeeded/Failed  : -  Stuck at Enqueued  

![image](https://github.com/abpframework/abp/assets/57087890/bdc91bf9-de84-4a10-b5b7-c3607a2221a7)

### Regression?

it working ok in ABP 6 version

### Known Workarounds

Downgraded the  ABP hang-fire module version as in the screen below and its working 
![image](https://github.com/abpframework/abp/assets/57087890/547bb0ef-5e73-4f52-b1ed-6217fbfe4f9f)

### Version

8.0.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

You can add the latest hangfire package to your solution.

https://github.com/HangfireIO/Hangfire/releases/

**Comment by jerinantony11** [comment]
If I just add the latest version of  Hangfire.SqlServer 1.8.12  then below dependency issue appears
![image](https://github.com/abpframework/abp/assets/57087890/cb6e4a54-7e0b-4c9d-9384-c35a67c9b5bf)

So I updated below packages 
![image](https://github.com/abpframework/abp/assets/57087890/32f409c6-2e48-4003-ad10-7b99710b3bf9)

But the job is still stuck at enqueue

**Comment by maliming** [comment]
hi

Can you share your test project?

Thanks

**Comment by thmoises** [comment]
Same problema here
Im using Hangfire.Mongo and im geting the same problem

RecurringJobs works normally. But BackgroundJob never fire

Its Works
![image](https://github.com/abpframework/abp/assets/156837610/de4eb93c-ec7e-489c-834c-7d6e58344a03)

But, It's not

![image](https://github.com/abpframework/abp/assets/156837610/8262d3fe-839a-488b-9e84-68d765c00d25)

**Comment by jerinantony11** [comment]
@maliming ,
I have updated my sample  ABP 8.1.0 project references again as below 
![image](https://github.com/abpframework/abp/assets/57087890/a406cae8-4c03-4912-9c96-01b0ebe83dd6)
 

   // **schedule -  doesn't work**
`   var jobId = Hangfire.BackgroundJob.Schedule<IBackgroundServiceManagement>(queue: "alpha", x => x.RunJOb(), TimeSpan.FromSeconds(10));`

   //**recurring job - works okay**
```
   RecurringJob.AddOrUpdate<IBackgroundServiceManagement>
              (Guid.NewGuid().ToString(), x => x.RunJOb(), "20 13 10 4 *");
```

   //**fire and forget - works okay**
`   var jobId2 = BackgroundJob.Enqueue<IBackgroundServiceManagement>(x => x.RunJOb());`


But in my actual project (its a migration from a working ABP 6 to  8.1.0),   none of the above works.   The recurring job doesn't trigger and the fire and forget is stuck at enqueued.  The  references are  as per the sample project.  Any guidance on how to debug this issue ? I believe its something to do with the package versions.  My ABP 6 version is a live application and after the migration everything works except the  Hang-fire stuffs. 

 My **sample** project is attached. 
[aspnet-core.zip](https://github.com/abpframework/abp/files/14937507/aspnet-core.zip)

**Comment by maliming** [comment]
hi all

Please define your queue names:

```
Configure<AbpHangfireOptions>(options =>
{
    options.ServerOptions = new BackgroundJobServerOptions()
    {
        Queues = new[] {"default", "alpha"}
    };
});
```

![image](https://github.com/abpframework/abp/assets/6908465/f5d7800c-b30a-4442-9ce2-3d73c1163c6d)


See https://docs.hangfire.io/en/latest/background-processing/configuring-queues.html

**Comment by jerinantony11** [comment]
okay, I tried below  syntaxes for adding the  queue names,

```
   Configure<AbpHangfireOptions>(options =>
   {
       options.ServerOptions = new BackgroundJobServerOptions()
       {
           Queues = new[] { "default", "alpha" }
       };
   });
```

```
   context.Services.Configure<BackgroundJobServerOptions>(options =>
   {
       options.Queues = new[] { "default", "alpha" };
   });
```

but it didn't work in my actual project. 
So I tried to use below from the Hang-Fire package and its all working properly. 

```
 context.Services.AddHangfireServer(options =>
        {
            options.Queues = new[] { "alpha", "beta", "default" };
            options.WorkerCount = 10;
        });       
```

**Comment by maliming** [comment]
Thanks @jerinantony11 

I will confirm again.

**Comment by maliming** [comment]
hi @jerinantony11 

The `BackgroundJobServerOptions` of `AddHangfireServer` and `AbpHangfireOptions ` are different. so you have to configure both.


https://github.com/HangfireIO/Hangfire/blob/main/src/Hangfire.NetCore/HangfireServiceCollectionExtensions.cs#L209
https://github.com/abpframework/abp/blob/63b8d555fcd8b8b8ccea2ff4cf49a0e31014b430/framework/src/Volo.Abp.HangFire/Volo/Abp/Hangfire/AbpHangfireOptions.cs#L36

**Comment by sephit** [comment]
Hello @maliming,

like @jerinantony11  refered, this should be added in the documentation of background jobs.

Recently in the version 9.1.1, I just added hangfire background jobs with the dashboard but not even a single Job were executed until I google it why it was always enqueue but if you add the following code, it works like charm

```
        Configure<AbpHangfireOptions>(options =>
        {
            options.ServerOptions = new BackgroundJobServerOptions
            { 
                WorkerCount = 10,
                Queues = ["myQueue", "default"],
                ServerName = "MyApp"
            };
        });
```

Not in a goog laptop right now to add it myself but would like the help of someone to add it.

At the begining the BackgroundJobServerOptions is null and It doesn't know how many workers are going to start the app. I believe that's the issue

**Comment by maliming** [comment]
hi @jerinantony11 @sephit @thmoises 

I checked. In fact, you don't need to call `AddHangfireServer`, because ABP will create a server.

I will mention this in the document.

Thanks.

https://github.com/abpframework/abp/blob/902601c016089a5b7062be8afe37f569c14f81b8/framework/src/Volo.Abp.HangFire/Volo/Abp/Hangfire/AbpHangfireOptions.cs#L45-L58

**Comment by sephit** [comment]
> hi [@jerinantony11](https://github.com/jerinantony11) [@sephit](https://github.com/sephit) [@thmoises](https://github.com/thmoises)
> 
> I checked. In fact, you don't need to call `AddHangfireServer`, because ABP will create a server.
> 
> I will mention this in the document.
> 
> Thanks.
> 
> [abp/framework/src/Volo.Abp.HangFire/Volo/Abp/Hangfire/AbpHangfireOptions.cs](https://github.com/abpframework/abp/blob/902601c016089a5b7062be8afe37f569c14f81b8/framework/src/Volo.Abp.HangFire/Volo/Abp/Hangfire/AbpHangfireOptions.cs#L45-L58)
> 
> Lines 45 to 58 in [902601c](/abpframework/abp/commit/902601c016089a5b7062be8afe37f569c14f81b8)
> 
>  private BackgroundJobServer CreateJobServer(IServiceProvider serviceProvider) 
>  { 
>      Storage = Storage ?? serviceProvider.GetRequiredService<JobStorage>(); 
>      ServerOptions = ServerOptions ?? serviceProvider.GetService<BackgroundJobServerOptions>() ?? new BackgroundJobServerOptions(); 
>      AdditionalProcesses = AdditionalProcesses ?? serviceProvider.GetServices<IBackgroundProcess>(); 
>   
>      return new BackgroundJobServer(ServerOptions, Storage, AdditionalProcesses, 
>          ServerOptions.FilterProvider ?? serviceProvider.GetRequiredService<IJobFilterProvider>(), 
>          ServerOptions.Activator ?? serviceProvider.GetRequiredService<JobActivator>(), 
>          serviceProvider.GetService<IBackgroundJobFactory>(), 
>          serviceProvider.GetService<IBackgroundJobPerformer>(), 
>          serviceProvider.GetService<IBackgroundJobStateChanger>() 
>      ); 
>  }

Totally agree with you, It only need to get known how many workers and the queue names (this is crucial).

If it doesn't have the queue name stablished in the configuration. It will live forever in the "Queue" section of Hangfire
