### ISSUE TITLE
Tenant Based Dependency Injection

### ISSUE THREAD

**Issue by silvercoffin** [abpframework/abp#1952]
I mean, for example we have multiple class with inherit same interface. Because i needed seprate somethinks for tenants. Then for convenience maybe you could add somethink like [InjectForTenant("XTenant")] and it automatic will inject that class for that tenant (if its current tenant)

public class DefaultTranscriptCalculator : IDefaultTranscriptCalculator
{
...
    public void Calculate() {}
}

[InjectForTenant("XTenant")]
public class XTenantTranscriptCalculator : DefaultTranscriptCalculator
{
...
   public override void Calculate() {}
}

**Comment by hitaspdotnet** [comment]
Check the [feature management](https://github.com/abpframework/abp/tree/dev/modules/feature-management)

**Comment by silvercoffin** [comment]
> Check the [feature management](https://github.com/abpframework/abp/tree/dev/modules/feature-management)

I checked but where?

**Comment by hitaspdotnet** [comment]
`ABPFeatureManagementModule`'s documents is not ready yet. Check [this](https://aspnetboilerplate.com/Pages/Documents/Feature-Management) from previous version to understand how FeatureManagement helps you in this case.

**Comment by silvercoffin** [comment]
I read the document, but could not find. I could override dependency injection (manually) on some module event by tenant when app starting. "Feature Management" module how could decide and resolve interfaces by tenant?

**Comment by maliming** [comment]
hi @silvercoffin 

Maybe you can try using the dependency injection container factory to create a service.
Get the current tenant information in the factory method and then find the class that uses the `InjectForTenant `attribute in all services that implement an interface.

**Comment by hikalkan** [comment]
Have you checked this: https://autofaccn.readthedocs.io/en/latest/advanced/multitenant.html
I haven't tried but it is promising.

**Comment by silvercoffin** [comment]
@hikalkan yes, that's exactly what I mean ... But for convenience abp framework coluld resolve that easily like just with use [InjectForTenant("XTenant")] attiribute on the class or some think like that.
If you want i could work on that
