### ISSUE TITLE
Implement refresh token in Blazor UI

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#19522]
https://support.abp.io/QA/Questions/7023/accesstoken-expiration-is-not-triggering-the-signout-in-Blazor-Server

**Comment by realLiangshiwei** [comment]
Because the refresh token must be Implemented in `OnValidatePrincipal` callback, It requires the current page to be refreshed, so the refresh token is meaningless.

**Comment by Dresel** [comment]
But that's only half of the story, right?

Other authentication frameworks like BFF (see [docs](https://docs.duendesoftware.com/identityserver/v7/quickstarts/7_blazor/#modifying-the-frontend-part-2)) are querying the current authentication session and state on a regular basis for Blazor (SPA) projects.

One could use a combination of [RevalidatingServerAuthenticationStateProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.revalidatingserverauthenticationstateprovider) and a custom user endpoint to fetch and update the authentication state on the client side. This endpoint would also trigger `OnValidatePrincipal` where one could update / revoke the AccessToken if needed. Then components could listen to `[AuthenticationStateChanged]` events and update the UI accordingly.

**Comment by realLiangshiwei** [comment]
Hi，

@Dresel yes, I'm working on it.
Related: https://github.com/abpframework/abp/issues/19488

**Comment by pergerch** [comment]
@realLiangshiwei would you be so kind and elaborate a bit, please?

Working on what? Just logging out automatically, or making the refresh possible? I am just wondering because this issue is closed as "completed".

**Comment by realLiangshiwei** [comment]
Hi @pergerch ,

As I mentioned: https://github.com/abpframework/abp/issues/19522#issuecomment-2056646342
But I will continue to investigate if it is possible
