### ISSUE TITLE
Insecure Session Handling

### ISSUE THREAD

**Issue by sbarnard12** [abpframework/abp#19520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

JSON (JavaScript Object Notation) Web Tokens (JWTs) are used to authenticate 
actions performed by a user against the API. JWTs should be invalidated after users log out of the 
application. However, under the current configuration, the tokens remain valid even after a user logs out.  

The lack of an access token revocation mechanism and reliance on access token expiry could lead to a scenario 
where users and their security teams assume that once a user has logged out or reset their password any 
access token, including those acquired by attackers, are terminated instantly; where in reality a 30-minute 
window exists where tokens remain valid. This degrades the ability of security teams to limit the potential 
impacts of credential breaches. 

### Reproduction Steps

1. Log into a site
2. log out
3. Try to access an API which should otherwise require the user to be logged in and authenticated

![image](https://github.com/abpframework/abp/assets/9059564/b1ef3502-4d2b-49bd-8daf-1478224735ff)

The screenshot above shows that the user "test.bdo2" is logged out of the web portal, yet their token
still working, and able to successfully send a GET request to an API endpoint to get the user's information. 

### Expected behavior

After logging out, the JWT Token should be expired when a user logs out of the system, instead of a timed window

### Actual behavior

![image](https://github.com/abpframework/abp/assets/9059564/b1ef3502-4d2b-49bd-8daf-1478224735ff)

The screenshot above shows that the user "test.bdo2" is logged out of the web portal, yet their token
still working, and able to successfully send a GET request to an API endpoint to get the user's information. 

### Version

7.2

### User Interface

MVC

### Database Provider

MongoDB

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

What type of startup template are you using?  Can you share the `CLI` command to create the test project?

It should request to revocation endpoint when logging out.


BTW, We will introduce the `sessions management` feature on abp commercial 8.2, which will invalidate the token/cookies after logout/revoke.

![image](https://github.com/abpframework/abp/assets/6908465/6ba4f4af-21cd-4c90-9367-a0aadb14209f)

See https://github.com/abpio/abp-commercial-docs/pull/780
