### ISSUE TITLE
Can Automapper be upgraded to Automapper 13.0 in ABPVnext8.0 version

### ISSUE THREAD

**Issue by BlueTomT** [abpframework/abp#19557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have encountered a problem, please refer to for details https://github.com/AutoMapper/AutoMapper/issues/4235 
This issue was resolved in version 13.0 of Automapper

Due to the target framework of Automapper 13.0 being. net6.0, I attempted to replace Volo.Abp.Automapper, but it may cause other exceptions, so we are considering whether to start this work and hope that the ABP framework can solve this problem

### Version

8.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
We will upgrade the automapper package.

**Comment by BlueTomT** [comment]
OK  Thank you so much
