### ISSUE TITLE
Host failed to start due to use of "AbpEventBusRebusModule"

### ISSUE THREAD

**Issue by keithtoop** [abpframework/abp#19558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using "**AbpEventBusRebusModule**", host failed to start as the following exception prompted.

![image](https://github.com/abpframework/abp/assets/31195722/84738a24-fb0e-47c4-91df-3bd56a3bde87)

### Reproduction Steps

- Add AbpEventBusRebusModule, config in-memory subscription, start the host

The implementation seems not following Rebus.ServiceProvider guideline.

https://github.com/rebus-org/Rebus.ServiceProvider?tab=readme-ov-file#hosting-outside-of-the-generic-host

It calls "StartRebus()" straight away, making the project run failed as a standalone console process.

### Expected behavior

Host should start successfully

### Version

8.1.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Could you provider a small project to reproduce the problem?

**Comment by keithtoop** [comment]
[hosting.AppServiceApi.zip](https://github.com/abpframework/abp/files/15011174/hosting.AppServiceApi.zip)
Mini project attached. Cheers

**Comment by realLiangshiwei** [comment]
This is a bug of Rebus: https://github.com/rebus-org/Rebus.ServiceProvider/pull/90
You can manually install the latest version of the Rebus package into your project to fix the problem.
