### ISSUE TITLE
No key value is passed when the form is submitted after disabled abp-select

### ISSUE THREAD

**Issue by myesn** [abpframework/abp#19561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

normal behavior：
```html
<form asp-page="/EditModal" method="post" novalidate="novalidate">
  <abp-select asp-for="Platform" />
  <input type="submit" value="submit" />
</form>
```
Platform property type is enum.
![image](https://github.com/abpframework/abp/assets/18598579/4fc6730a-2ee2-486c-9c4b-b69ab7e4e01a)

After setting abp-select to `disabled="true"`：
```html
<form asp-page="/EditModal" method="post" novalidate="novalidate">
  <abp-select asp-for="Platform" disabled="true" />
  <input type="submit" value="submit" />
</form>
```
![image](https://github.com/abpframework/abp/assets/18598579/dc13cb75-0d75-4655-85df-8a2f962cff7e)

### Reproduction Steps

Setting abp-select to `disabled="true"`：
```html
<form asp-page="/EditModal" method="post" novalidate="novalidate">
  <abp-select asp-for="Platform" disabled="true" />
  <input type="submit" value="submit" />
</form>
```

### Expected behavior

After setting abp-select to `disabled = "true"`, the default key-value is still present when submitting the form.
![image](https://github.com/abpframework/abp/assets/18598579/4fc6730a-2ee2-486c-9c4b-b69ab7e4e01a)

### Actual behavior

After setting abp-select to `disabled = "true"`：
![image](https://github.com/abpframework/abp/assets/18598579/dc13cb75-0d75-4655-85df-8a2f962cff7e)

### Version

8.1.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
This is how `Form` element  and `Disabled` attribute working.

> Disabled controls
Attribute definitions
disabled [CI]
When set for a form control, this boolean attribute disables the control for user input.
When set, the disabled attribute has the following effects on an element:
Disabled controls do not receive focus.
Disabled controls are skipped in tabbing navigation.
Disabled controls cannot be successful.
The following elements support the disabled attribute: BUTTON, INPUT, OPTGROUP, OPTION, SELECT, and TEXTAREA.
This attribute is inherited but local declarations override the inherited value.

> How disabled elements are rendered depends on the user agent. For example, some user agents "gray out" disabled menu items, button labels, etc.

> In this example, the INPUT element is disabled. Therefore, it cannot receive user input nor will its value be submitted with the form.

> <INPUT disabled name="fred" value="stone">

See: https://www.w3.org/TR/html401/interact/forms.html#disabled

**Comment by myesn** [comment]
@realLiangshiwei Thanks.
