### ISSUE TITLE
Insufficient Session Termination

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#19576]
After logging out from the application, the authentication cookies are automatically removed, that's good...
But these cookies are not invalidated on the backend. 
Therefore, if anyone uses the same cookies, they can still successfully make requests with the logged-out cookies. 

![image](https://github.com/abpframework/abp/assets/9526587/25b66f72-56df-46c4-82c1-2afd065572e3)

**Comment by maliming** [comment]
1. If the browser and the server communicate with each other via **HTTPS** protocol, We can assume the [middleman](https://owasp.org/www-community/attacks/Manipulator-in-the-middle_attack) cannot obtain the information in the request, such as `cookies, tokens.`

> Of course, **HTTPS** is not enough. It would be best to prevent other situations leading to man-in-the-middle attacks, such as fake certificates. Please refer to https://www.rapid7.com/fundamentals/man-in-the-middle-attacks/ and https://www.imperva.com/learn/application-security/man-in-the-middle-attack-mitm/ for more details.

2. The server will instruct the browser to delete the cookies after logging out via the [`Set-Cookie Header`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie).

Even though cookies may still be valid, no one can retrieve deleted cookies. The browser is responsible for preventing **cookies** leaks.

![image](https://github.com/abpframework/abp/assets/6908465/0ea78593-926d-452c-b956-239c924ec2ed)


3. ABP commercial will introduce a `Sessions Management` feature to invalidate the **cookies and tokens**. 

https://github.com/abpio/abp-commercial-docs/blob/dev/en/modules/identity/session-management.md
https://github.com/abpio/abp-commercial-docs/blob/dev/en/modules/account/session-management.md
