### ISSUE TITLE
Angular: Update imports in `CoreTestingModule`

### ISSUE THREAD

**Issue by yusuf-cirak** [abpframework/abp#19570]
### Documentation

I've encountered some issues when trying to reproduce the issue in this support question: https://support.abp.io/QA/Questions/7022/Angular-Testing-DynamicTestModule-error

I got errors with `OTHERS_GROUP` and `SORT_COMPARE_FUNC` injection tokens.

CoreTestingModule should be updated to prevent failures related to dependencies.

**Comment by ayyash** [comment]
So what's the work around for v 7.4?
