### ISSUE TITLE
Bearer Access Token Authorize Failed

### ISSUE THREAD

**Issue by Kenjiang110** [abpframework/abp#1958]
1、Add [Authorize] to TestController in HttpApi project
```
    [Authorize]
    [Route("api/test")]
    public class TestController : POController
    {
    }
```
2、Get Access Token from IDS4
![image](https://user-images.githubusercontent.com/12540333/67159135-571fc800-f373-11e9-9f0d-3ebe22c7b16b.png)

3、Try Call api/test using the access token
![image](https://user-images.githubusercontent.com/12540333/67159151-90f0ce80-f373-11e9-87a4-ee43bcd6028e.png)

4、Authorize Failed and redirect to Login Page

5、Modify Web Module like this:
```
            app.UseAuthentication();
            //app.UseAuthorization();   //should after  app.UseIdentityServer();

            app.UseJwtTokenMiddleware();

            if (MultiTenancyConsts.IsEnabled)
            {
                app.UseMultiTenancy();
            }
            app.UseIdentityServer();
            app.UseAuthorization();  //move to here
```
  Problem solved !  Is this a bug?

**Comment by maliming** [comment]
`UseIdentityServer `includes a call to `UseAuthentication`, so it’s not necessary to have both.

**Comment by Kenjiang110** [comment]
But the abp have both now and causing this bug.




| |
Ken Jiang
邮箱：ken_yhy@163.com
|

Signature is customized by Netease Mail Master

On 10/20/2019 21:14, maliming wrote:

UseIdentityServer includes a call to UseAuthentication, so it’s not necessary to have both.

**Comment by maliming** [comment]
I will try to fix it.

**Comment by mehmetuken** [comment]
MyCompanyName.MyProjectName.HttpApi.HostWithIds project not resolved.

**Comment by maliming** [comment]
@mehmetuken https://github.com/abpframework/abp/pull/1969
