### ISSUE TITLE
Prevent e-mail address enumeration

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#19588]
### Security vulnerability description:

It is possible to collect valid email addresses by interacting with the "Forgot Password" function of the
application. This vulnerability is useful to increase the efficiency of brute force attacks. If the email is known, it
is easier to find the corresponding password. The affected URL is `/Account/ForgotPassword`.

With the "Forgot Password" function, the security consultants were able to enumerate valid email addresses as
the function returns "Cannot find the given email" error, when there is no user registered with the provided e-
mail address. Figure 12 shows the error message received if the email is not registered.

![image](https://github.com/abpframework/abp/assets/9526587/e08ec6d0-430d-4ce0-8ca9-b00c0610e32f)

If a user is registered with the provided email address, the application informs them that a recovery email has
been sent as shown below.

![image](https://github.com/abpframework/abp/assets/9526587/eb48b256-e553-4006-ae13-d1c8a29b0cea)

Ref: https://portswigger.net/blog/preventing-username-enumeration

---

### Explanation for this security issue:

This behavior is user-friendly, and it's a tradeoff between being user-friendly and security-friendly. The following popular websites all show user-friendly warning messages about user existence. So this is a worldwide accepted behavior. 

![image](https://github.com/abpframework/abp/assets/9526587/0dd8066f-f08a-4ba6-9e1d-52e5b0dce91b)

---

### Solution:

We can give this security level as an option. By default current behaviour will be valid. With an extra configuration, we can change the response of "forget my password request".  If this option is enabled, we shouldn't show positive or negative responses if the user enters a valid email or not. Always show a generic message as the following : 

```
If the provided e-mail address is registered in the system, we will send a password reset link. If you don't get an email within a few minutes, please check your spam box or try again later.
```

**Comment by Pavesi99** [comment]
Hi, @ebicoglu and  @oykuermann, did you add any feature to this? Could you link the commit/PR here? 

Thanks in advance.

**Comment by maliming** [comment]
hi @Pavesi99 

This feature is added to [Account.Pro](https://abp.io/modules/Volo.Account.Pro) module.

![Image](https://github.com/user-attachments/assets/f4b62e5f-be86-47ce-858b-984dd192397a)
