### ISSUE TITLE
Documentation for extending ApplicationConfiguration Endpoint

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#19583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently there is no documentation about extending the [Application Configuration](https://docs.abp.io/en/abp/latest/API/Application-Configuration) with AbpApplicationConfigurationOptions / IApplicationConfigurationContributor.

### Describe the solution you'd like

Mention that AbpApplicationConfigurationOptions exist and show how to add static information to the ApplicationConfiguration Enpoint by creating an IApplicationConfigurationContributor.

This reduces required initial requests and ensure data is available after initial request

### Additional context

Maybe a section about ObjectExtensions would nice to (currently its not even mentioned that extension information are included)

References: [AbpApplicationConfigurationAppService](https://github.com/abpframework/abp/blob/49fd762d6c7c414120f1aa212739385e72f16a8c/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationAppService.cs)

**Comment by EngincanV** [comment]
I wrote an article to show how to extend the application-configuration endpoint, which you can check at https://engincanv.github.io/abp/2022/08/02/extending-the-application-configuration-endpoint.html

Regardless, I agree that we should document it in the [Application Configuration](https://docs.abp.io/en/abp/latest/API/Application-Configuration) document as you said. I'll be working on that.

**Comment by EngincanV** [comment]
Done: https://github.com/abpframework/abp/pull/19595 ✅
