### ISSUE TITLE
Cannot create a no-ui solution

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#1959]
I want to create an app that has service only modules i.e. has no UI. I've tried the following but it always creates an app based on the app template with login pages etc.

apb new testing --no-ui
![image](https://user-images.githubusercontent.com/1365851/67167228-45e4b480-f38f-11e9-8ff2-14a13f85f1aa.png)

apb new testing -t --no-ui
![image](https://user-images.githubusercontent.com/1365851/67167221-2b124000-f38f-11e9-89e7-99b72c4fb10c.png)

I would have thought the **node_modules** folder and **@abp/aspnetcore.ui.theme.basic** wouldn't be installed if they aren't needed
![image](https://user-images.githubusercontent.com/1365851/67167253-8fcd9a80-f38f-11e9-9402-d1d120d03ef8.png)

**Comment by maliming** [comment]
`no-ui` is an option for the `module` template.

**Comment by KevinFarrow** [comment]
Thanks for update but the documentation implies that there are 3 options to the **--template** or **-t** parameter, **app**, **module** or **--no-ui**

if the **--no-ui** is an option of the **module** template then it should be indented i.e. the **--no-ui** should be indented below the **module** (square bullet point)

![image](https://user-images.githubusercontent.com/1365851/67188480-52dfc300-f3e4-11e9-8abc-2d4b729a9846.png)

**Comment by mehmetuken** [comment]
App template has host projects. But just create project ui select angular is created. This option --ui none selected without ui app template created.
https://github.com/abpframework/abp/blob/decad8e30f6186be87db8c5743bf55d530514bb9/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/TemplateProjectBuilder.cs#L126
Here we not normalized ui framework NotSpecified = no-ui just create host project.

**Comment by hikalkan** [comment]
Sorry for the documentation. It should be like that:

![image](https://user-images.githubusercontent.com/1210527/67267777-affa7800-f4bb-11e9-9d39-e6f7ecfd7670.png)

I don't know why it is rendered like that in the docs.abp.io web site, will fix it.
