### ISSUE TITLE
Support Angular 17's new build system (esbuild)

### ISSUE THREAD

**Issue by hillin** [abpframework/abp#19607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

As of Angular 17, a new esbuild-based build system has been added and is likely to deprecate the old webpack-based system in a future version: https://angular.io/guide/esbuild

Currently there are some hard-coded webpack directives in the [abp code](https://github.com/abpframework/abp/blob/d157ccac4ede63d190fff73c76df5edf30d0382b/npm/ng-packs/packages/core/locale/src/utils/register-locale.ts#L29-L32). These are stumbling blocks to migrate to the new build system.

### Describe the solution you'd like

Support the new build system, probably by re-implementing the webpack-oriented code.

**Comment by mahmut-gundogdu** [comment]
@masumulu28  the issue may  mark as good-first-issue because it is not related to domain. just webconfig and esbuild.

**Comment by mahmut-gundogdu** [comment]
@hillin  I have found a solution. I have tested in my local env but Could you check ? It is easy to test without wait to deploy. just copy the function in your local. and inject in localfile

https://github.com/abpframework/abp/pull/20096
