### ISSUE TITLE
Bundle command should work with different versions

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#19602]
We will separate framework and cli versions soon. So, version matching in bundle command will be a problem.

@maliming You can ask me and @enisn for more information.

**Comment by enisn** [comment]
Here is the case:

ABP CLI version is `8.1.1` and when you try to run `abp bundle` for project with ABP version `8.0.2` it fails to load DLLs since because it tries to load all project assemblies into CLI's own process at runtime,

**Comment by maliming** [comment]
It works for me.

![image](https://github.com/abpframework/abp/assets/6908465/f335ca5f-3832-4a47-9385-4208a8517c98)

**Comment by enisn** [comment]
This is a wider problem, maybe we can install local tool in the directory with the same version with project instead using global in project folders

**Comment by maliming** [comment]
>  it fails to load DLLs 

How can I reproduce this?

**Comment by enisn** [comment]
It works now with 8.3/8.2 CLI on 8.0 projects. But When you try to bundle project 7.4 or version with breaking-changes it'll fail.


How about placing dotnet-tools.json in projects with the same version of project and execute always same CLI version with project?

![image](https://github.com/abpframework/abp/assets/23705418/3a0924eb-f569-4698-b2bd-bb16b41c527f)

**Comment by enisn** [comment]
Each project can use their own version CLI different than global cli version

**Comment by maliming** [comment]
Developers should use the same CLI version as the project package version, at least the same NET platform version. (net 7, net 8)

---

Of course, they can install CLI at the folder level.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#description

**Comment by enisn** [comment]
> Developers should use the same CLI version as the project package version, at least the same NET platform version. (net 7, net 8)
> 
> Of course, they can install CLI at the folder level.
> 
> https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#description

Should we include `dotnet-tools.json` file in the templates?

**Comment by maliming** [comment]
We can output a warning message for the `abp bundle` command and add a document to explain this.

Include `dotnet-tools.json` still requires the developer to do extra work, so I think we can tell the developer to install the CLI herself/himself.

**Comment by enisn** [comment]
Yes,`dotnet tool restore` must be executed manually, so it needs extra work. You're right, we can explain with warning message when version mismatch with project
