### ISSUE TITLE
Volo.Abp.AspNetCore.Abstractions  not found in nuget.org

### ISSUE THREAD

**Issue by sdjnzjz** [abpframework/abp#19606]
i want to use  IWebClientInfoProvider in ApplicationService layer, 
but
Volo.Abp.AspNetCore.Abstractions  not found in nuget.org

**Comment by maliming** [comment]
The `Volo.Abp.AspNetCore.Abstractions` package will be available on 8.2.

https://github.com/abpframework/abp/pull/18242
