### ISSUE TITLE
HideAbpEndpoints also hides endpoints when I use v{version:apiVersion} in route

### ISSUE THREAD

**Issue by xiaoxiaotank** [abpframework/abp#19636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I use api versioning, the apis can't show in swagger ui,like this:
```csharp
[ApiController]
[ApiVersion("1.0")]
[Route("api/v{version:apiVersion}/[controller]")]
public class MyController : ControllerBase {}
```

I guess it is beacause AbpSwashbuckleDocumentFilter.RemoveRouteParameterConstraints, it transform `api/v{version:apiVersion}/my` to `api/v{version}/my`, rather than `api/v1/my`、`api/v2/my` and etc.

### Version

8.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

https://github.com/abpframework/abp/issues/15712

**Comment by maliming** [comment]
hi

* Steps needed to reproduce the problem.

**Comment by maliming** [comment]
Reopen if you still have this problem.

**Comment by MernaMustafa** [comment]
Same issue
