### ISSUE TITLE
Cache invalidation `considerUow` problem

### ISSUE THREAD

**Issue by ahmetfarukulu** [abpframework/abp#19633]
When handling cache invalidation, it's crucial to set the `considerUow` parameter to true. If this parameter is not set correctly, the cache gets removed [immediately](https://github.com/abpframework/abp/blob/74d0ca0f7eb1d85cf4f016156d4d7233fe37e1b3/framework/src/Volo.Abp.Caching/Volo/Abp/Caching/DistributedCache.cs#L1368). However, if there are other HTTP requests for related cache before the unit of work is complete, the cache might remain in a dirty state.

We should do this for all invalidators such as; [PermissionGrantCacheItemInvalidator](https://github.com/abpframework/abp/blob/b275719535e66ed6c73852925f49a78855c900b0/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionGrantCacheItemInvalidator.cs#L34), [TenantConfigurationCacheItemInvalidator](https://github.com/abpframework/abp/blob/74d0ca0f7eb1d85cf4f016156d4d7233fe37e1b3/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/TenantConfigurationCacheItemInvalidator.cs#L42) etc.

**Comment by maliming** [comment]
We can set the transaction isolation level at the database level to prevent dirty reads.
However, we can't control concurrent requests at the HTTP request level so that you may get an outdated response.

When you see this comment of mine, I may have already sent an edit request.

**Comment by ahmetfarukulu** [comment]
https://github.com/abpframework/abp/pull/19671
