### ISSUE TITLE
ABP 8.1.0 & 8.1.1  - GetListAsync is slow

### ISSUE THREAD

**Issue by jerinantony11** [abpframework/abp#19649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After upgrading from ABP 8.00 to 8.1.0 the GetListAsync  & InsertManyAsync are  very slow.
After testing the 8.1.1, it  sloved the InsertManyAsync slowness.  The  GetListAsync still takes ages when querying large tables.

If I override the GetListAsync  with a custom implementation then Its a lot more faster.

### Reproduction Steps

1. Create an ABP 8.1.1 project. 

2. Use GetListAsync in  the repository     `await Repository.GetListAsync (x=> x.abc = 'something')`
3. It takes a while to  retrieve records

### Expected behavior

The data retrieval shouldn't take long

### Actual behavior

The data retrieval takes ages

### Known Workarounds

overwrite GetListAsync in the repo with something like this  

` public override async Task<List<myModel>> GetListAsync(Expression<Func<myModel, bool>> predicate, bool includeDetails = false, CancellationToken cancellationToken = default)
 {
     var dbContext = await GetDbContextAsync();
     var setContext = dbContext.Set<myModel>();
     var result = await (from data in setContext.AsNoTracking().Where(predicate) select data).ToListAsync();
     return result;
 }`

### Version

8.1.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

This will be fixed in the next release.

See https://github.com/abpframework/abp/pull/19559
