### ISSUE TITLE
Illegal Characters in swagger.json - Unable to use in swagger generator.

### ISSUE THREAD

**Issue by sjdean** [abpframework/abp#19666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have noticed a problem reported elsewhere but so far unchanged where the swagger.json is corrupt. This is especially true for things like PagedResultDto objects and you'll note within the name of the object there are "`" tick marks.

Please see below a sample of the created JSON:
```

      "Volo.Abp.Application.Dtos.PagedResultDto`1[[Application.Shared.ExtendedLookupDto`1[[System.Guid, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=XXX]], Application.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Application.Shared.ExtendedLookupDto`1[[System.Guid, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=XXX]]"
            },
            "nullable": true
          },
          "totalCount": {
            "type": "integer",
            "format": "int64"
          }
        },
        "additionalProperties": false
      },
```

In the _HttpApiHostModule.cs file, we see the following line:

`options.CustomSchemaIds(type => type.FullName);`

Being a previous user of AspNetZero, there is a function called CustomDefaultSchemaIdSelector() within SwaggerExtensions.cs which seems to do what we need here. I have incorporated the code within _HttpApiHostModule.cs by changing the above line to:

```
                options.CustomSchemaIds(type =>
                {
                    string SchemaIdSelector(Type mType)
                    {
                        if (!mType.IsConstructedGenericType)
                        {
                            return mType.FullName;
                        }
                        else
                        {
                            var prefix = mType.GetGenericArguments()
                                .Select(SchemaIdSelector)
                                .Aggregate((previous, current) => previous + current);
                            return mType.FullName.Split('`').First() + "Of" + prefix;
                        }
                    }
                    return SchemaIdSelector(type);
                });
```

This seems to work well for me, and I now have a valid JSON file I can pass into my swagger generator.

### Reproduction Steps

- Occurs out of the box, if you view the swagger.json file on the host referring to PagedResultDto usages. 
- Parse it at editor.swagger.io to see issues.

### Expected behavior

Correct swagger.json file should be created with no illegal characters.

### Actual behavior

Current setup produces incorrect JSON. 

### Version

8.1.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

**Comment by maliming** [comment]
hi @sjdean 

Thank you for your suggestion. I have added an extension method.

See https://github.com/abpframework/abp/pull/19669
