### ISSUE TITLE
abp.io login | reset password | register not working

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#1967]
![image](https://user-images.githubusercontent.com/23167047/67184798-65142e00-f3f1-11e9-8a31-14e8770140b6.png)

**Comment by hitaspdotnet** [comment]
After clearing browser cache:
![image](https://user-images.githubusercontent.com/23167047/67185232-3a76a500-f3f2-11e9-9701-befa61669de6.png)

**Comment by maliming** [comment]
already fixed.
