### ISSUE TITLE
fontawesome is not in the package.json

### ISSUE THREAD

**Issue by epgeroy** [abpframework/abp#1973]
just installed a fresh `abp new Acme.BookStore -u angular` and when I ran `yarn start` it return an error:
`Module not found: Error: Can't resolve '/home/XXX/Desktop/test/angular/node_modules/@fortawesome/fontawesome-free/css/all.min.css'`

just running
`yarn add --dev @fortawesome/fontawesome-free`

solves the problem

**Comment by maliming** [comment]
Please upgrade the `@abp` related package to the latest version, I will update the template.

`yarn upgrade --pattern "@abp" --latest`

**Comment by epgeroy** [comment]
thxs
