### ISSUE TITLE
Show `H1` tag value for page titles 

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#19761]
> Show h1 text
## test

![image](https://github.com/abpframework/abp/assets/9526587/4e1d1696-3187-4c32-9891-6fcae3176d35)

When the link is being shared, it doesn't show a user-friendly description
![image](https://github.com/abpframework/abp/assets/9526587/831fd762-639c-4975-8dda-bb5835e42066)

**Comment by oykuermann** [comment]
There is a problem with the Overall sub-menu items, so we decided to continue with the h1 text for the page title:
![image](https://github.com/user-attachments/assets/ab3eabae-f26e-4d9e-9840-c63b3d84390f)

@realLiangshiwei 

![image](https://github.com/user-attachments/assets/73685e75-2253-4457-b28f-e51854baf7ed)
