### ISSUE TITLE
Error - Invalid_client on login 

### ISSUE THREAD

**Issue by ramusbucket** [abpframework/abp#1976]
On fresh start - 

![image](https://user-images.githubusercontent.com/3519523/67259461-cc120100-f44a-11e9-9ef0-7aaf76474a7e.png)

this api - https://localhost:44357/connect/token - throws erro - invalid_client.
https://localhost:44357/api/abp/multi-tenancy/tenants/by-name/SingleApp_App => throws - {"success":false,"tenantId":null,"name":null}

 My database is setup with update-database

Can I have a debugging tutorial link. I seem not to get where to put the break-point to investigate..

**Comment by maliming** [comment]
> My database is setup with update-database

The solution contains a console application (`SingleApp.DbMigrator`) that can create database, apply migrations and seed initial data. It is useful on development as well as on production environment.

**Comment by ramusbucket** [comment]
You are right. Done. That resolves - "invalid_client" error. I'm still struggling with - {"success":false,"tenantId":null,"name":null} - Given tenant is not available:

**Comment by maliming** [comment]
`SingleApp_App` not a Tenant, it's Client of Identity Server.
