### ISSUE TITLE
error in host side login

### ISSUE THREAD

**Issue by ramusbucket** [abpframework/abp#1977]
If I leave tenant blank, I cannot login to host side. Getting following error - 

{"error":"invalid_grant","error_description":"invalid_username_or_password"}

**Comment by hikalkan** [comment]
Is it n-tier application?

**Comment by ramusbucket** [comment]
Here is the way I downloaded it - 
![image](https://user-images.githubusercontent.com/3519523/67259461-cc120100-f44a-11e9-9ef0-7aaf76474a7e.png)

**Comment by KevinFarrow** [comment]
Have you run the DbMigrator console project rather than the EntityFrameworkCore.DbMigrations?

For some reason the seed data isn't inserted into the database if you use the EntityFrameworkCore.DbMigrations project

**Comment by ramusbucket** [comment]
You are right, I did that mistake first but after that I ran DbMigrator and I have all the seed data populated 

![image](https://user-images.githubusercontent.com/3519523/67303611-86cfec80-f4a7-11e9-8089-574c737f6d69.png)

**Comment by maliming** [comment]
hi @ramusbucket 
Please provide the steps to reproduce the problem, if possible please share some screenshots.

**Comment by ramusbucket** [comment]
hi @maliming, sure. My apologies, I should have done that in original issue description.

Here are the steps - 
1. Download code from - https://abp.io/get-started -  (Direct Download)  - with following options selected.
![image](https://user-images.githubusercontent.com/3519523/67259461-cc120100-f44a-11e9-9ef0-7aaf76474a7e.png)

2. Unzip downloaded file to `:\SingleApp`
3. Open - `C:\SingleApp\aspnet-core\SingleApp.sln` with VS 2019
4. Configure connection string in `SingleApp.DbMigrator` and `SingleApp.HttpApi.Host` project as - 
`Server=(localdb)\\mssqllocaldb;Database=SingleApp;Trusted_Connection=True;MultipleActiveResultSets=true`
5. Create `SingleApp` database on `(localdb)\\mssqllocaldb`  server.
6. Build Solution - builds successfully
7. Set `SingleApp.DbMigrator` as startup project
8. Run `SingleApp.DbMigrator`  from VS 2019. It creates all tables with data.
for example, I can see single record for `admin` user in `AbpUsers` table -

![image](https://user-images.githubusercontent.com/3519523/67303611-86cfec80-f4a7-11e9-8089-574c737f6d69.png)

9. Set `SingleApp.HttpApi.Host` as startup project
10. Run this project in IIS Express from VS 2019. I can see swagger page on - `https://localhost:44357/swagger/index.html`
11. Navigate to `C:\SingleApp\angular` and run `yarn` command on command prompt opened with Administrator privilege. 
12. Run `yarn start`. This fails for following error - 

> ERROR in multi ./node_modules/@fortawesome/fontawesome-free/css/all.min.css
> Module not found: Error: Can't resolve 'C:\SingleApp\angular\node_modules\@fortawesome\fontawesome-free\css\all.min.css' in 'C:\SingleApp\angular'
> ERROR in multi ./node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css
> Module not found: Error: Can't resolve 'C:\SingleApp\angular\node_modules\@fortawesome\fontawesome-free\css\v4-shims.min.css' in 'C:\SingleApp\angular'

13. Run `yarn add @fortawesome/fontawesome-free` to resolve above error
14 Run `yarn start`. This runs successfully.
15. Browse to `http://localhost:4200` and click on login button
16. Enter crentials - admin/1q2w3e*  on login page to get an error popup which says - `invalid_username_or_password`

![image](https://user-images.githubusercontent.com/3519523/67348657-709f4c00-f4fa-11e9-933b-191bd7ba6d2d.png)

Chrome network tab says, it is trying to call - https://localhost:44357/connect/token and getting response as below - 
`{"error":"invalid_grant","error_description":"invalid_username_or_password"}`

Please let me know if you need any additional information.

**Comment by maliming** [comment]
@ramusbucket 
I will try it, before that, you can try upgrading the abp package See https://github.com/abpframework/abp/issues/1973#issuecomment-544770517

**Comment by ramusbucket** [comment]
Ok, 

I did that. And it has no effect on this particular issue. I will wait for your comments. thanks.

**Comment by maliming** [comment]
I will give it a try later. : )

**Comment by ramusbucket** [comment]
damn it! I'm a fool :(

It worked!  Thanks a ton.
