### ISSUE TITLE
Must call SetAsync() before IOptions<IdentityOptions> used？

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#19787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have been config IdentityOptions in appsettings.js.  And not config in settings database table.
But I only got default value when inject IOptions<IdentityOptions> on appservice。not the value whitch i config in the appsettings.js
And when called IOptions<IdentityOptions>.SetAsync() ,the value is correct,but i found it already called on login.
Must call SetAsync() before IOptions<IdentityOptions> used？

### Version

8.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by CAH-FlyChen** [comment]
related to  https://github.com/abpframework/abp/issues/18113
it seems must call the function

**Comment by maliming** [comment]
The `SetAsync` method will populates the `IdentityOptions` with `Identity` settings. so, Yes, You have to call it.
