### ISSUE TITLE
 Default value of the TenantResolverConsts.DefaultTenantKey is "_ tenant"

### ISSUE THREAD

**Issue by BlueTomT** [abpframework/abp#19784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I use nginx proxy, nginx defaults to not forwarding headers with '__', but TenantResolverConsts The default value of the Default TenantKey is "__tenant", which prevents it from being retrieved from the header

### Version

8.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by BlueTomT** [comment]
Should we avoid using underline in headerkey?

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/latest/Multi-Tenancy#problems-with-the-nginx

**Comment by BlueTomT** [comment]
ok
