### ISSUE TITLE
Given tenant is not available

### ISSUE THREAD

**Issue by ramusbucket** [abpframework/abp#1978]
If I use available tenant, I cannot login, I get error - 

Given tenant is not available: SingleApp_App.

I can see it is available in database - 

![image](https://user-images.githubusercontent.com/3519523/67260245-3b89ef80-f44f-11e9-8110-e7b08d3041c2.png)

as well as config files - 

![image](https://user-images.githubusercontent.com/3519523/67260258-4e9cbf80-f44f-11e9-8720-43a010afaaa1.png)

**Comment by maliming** [comment]
SingleApp_App not a Tenant, it's Client of Identity Server.

**Comment by ramusbucket** [comment]
Oh! I see. got it.
