### ISSUE TITLE
Blazor Server & Blazor WebApp - Project logo is missing.

### ISSUE THREAD

**Issue by oykuermann** [abpframework/abp#19780]
Blazor Server & Blazor WebApp app template 8.2 pre-rc

The project logo is missing.
![screenshot-localhost_44364-2024 05 10-15_50_19](https://github.com/abpframework/abp/assets/142304401/279473dc-4f71-4f8b-a05b-ee2c637320d9)

**Comment by enisn** [comment]
I can't reproduce the same issue. Can you provide me steps to reproduce or the project itself?

![image](https://github.com/abpframework/abp/assets/23705418/a969c1ff-fa54-46d8-93fc-c9a350cada61)


Installing client-packages with `abp install-libs` in `.Blazor` project and bundling client files with `abp bundle` in the `.Client` might solve the problem

**Comment by oykuermann** [comment]
I sent you my project via email @enisn

**Comment by enisn** [comment]
Ok, found it, thanks 🙏
