### ISSUE TITLE
Blazor Web App with MongoDB - Project gets an error when running the project.

### ISSUE THREAD

**Issue by oykuermann** [abpframework/abp#19781]
Blazor Web App with MongoDB `v8.2 pre-rc`

The project gets an error when running the project.
![image](https://github.com/abpframework/abp/assets/142304401/f4e05a2f-97f0-4501-bb41-c97e0597c25d)

**Comment by maliming** [comment]
Please share your `BWebFree820510mongo` project.
Thanks
 liming.ma@volosoft.com

**Comment by oykuermann** [comment]
I sent you @maliming

**Comment by maliming** [comment]
Your project file is wrong, Please share the complete project creation steps.

`<PackageReference Include="BWebFree820510mongo.EntityFrameworkCore" Version="8.2.0-preview20240510" />`

```
<ProjectReference Include="..\BWebFree820510mongo.Application\BWebFree820510mongo.Application.csproj" />
<ProjectReference Include="..\BWebFree820510mongo.Blazor.Client\BWebFree820510mongo.Blazor.Client.csproj" />
<ProjectReference Include="..\BWebFree820510mongo.HttpApi\BWebFree820510mongo.HttpApi.csproj" />
<PackageReference Include="BWebFree820510mongo.EntityFrameworkCore" Version="8.2.0-preview20240510" />
<PackageReference Include="Volo.Abp.Autofac" Version="8.2.0-preview20240510" />
<PackageReference Include="Volo.Abp.Swashbuckle" Version="8.2.0-preview20240510" />
```

**Comment by oykuermann** [comment]
I created the project with this command:
abp new BWebFree820510mongo -csf -t app -u blazor-webapp --database-provider mongodb --template-source C:\Users\oykue\.abp\templates --version 8.2.0-preview20240510 -tv -sib

**Comment by maliming** [comment]
Please share your local template project file.

**Comment by oykuermann** [comment]
I sent you via mail

**Comment by maliming** [comment]
Thanks. I will fix this asap.
