### ISSUE TITLE
Provide support for interceptors in both factory and instance injection

### ISSUE THREAD

**Issue by Tairitsua** [abpframework/abp#19808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am attempting to develop an interceptor for identifying slow methods, and I have various custom services such as Dapr client invocation that require factory dependency injection. However, I am facing several challenges. Firstly, the current implementation of dynamic proxy with Autofac does not support factory and instance injection as I reviewed the code in `AutofacRegistration.Register`. Secondly, it is difficult to implement if I prefer to use class proxy instead of interface proxy, which can help me proxy not only interface method but also its virtual method.

### Describe the solution you'd like

I would like to see the implementation of `ConfigureAbpConventions` to support `IRegistrationBuilder<object, SimpleActivatorData, SingleRegistrationStyle>`.  Additionally, I would like to see the introduction of a parameter in `IOnServiceRegistredContext` or elsewher  that can indicates ABP to use a class proxy.

**Comment by maliming** [comment]
Autofac/Castle DynamicProxy doesn't support creating intercepts for an `instance or instance factory` .
