### ISSUE TITLE
Add cli app template --ui none option.

### ISSUE THREAD

**Issue by mehmetuken** [abpframework/abp#1982]
This option create just httpapi.host project app template without ui.

**Comment by maliming** [comment]
I will try to implement it. Thanks feedback.

**Comment by KevinFarrow** [comment]
The problem I have is that I need to be able to change the login screen layout, css, HTML, and also add functionality (CAPTCHA etc.) and debug this as part of the whole solution (I'll also need to do this to other modules).

Separating everything into modules means I can't do this unless I debug each module separately but unfortunately some modules depend on others, so if I need to step into a different module (say from login to IdentityServer module), I need to stop the project and load the solution of the IdentityServer module.

I'm not sure why the account/core functionality (login etc.) isn't part of the main project as I can't think of any project that wouldn't need this functionality, and I can't image anyone writing a replacement account module. I can understand having the **docs** and **blog** as separate modules but I need core functionality to exist in my main project. 

The other headache I have is that there are so many language strings. In Zero we had one file for each language that could send off to be translated. Now there are so many that it's hard to ensure duplication doesn't creep in. Wouldn't it be better to have a single entry point / file for each language? Adding a new module could check each string and merge the data?

I could be wrong in my assumptions above (and hopefully I am) so any guidance would be much appreciated.
