### ISSUE TITLE
Mvc / Blazor -  Features button styles are outdated

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#19836]
**App:** Mvc/Blazor Server/wasm - `8.0.6`

 Features button styles are outdated
**Mvc/Blazor:**
![image](https://github.com/abpframework/abp/assets/99716457/60d381cc-dc4d-4bbf-9fd4-7d915819c02a)

**Should be:**
![image](https://github.com/abpframework/abp/assets/99716457/69b6d04c-f25c-46f7-8ecd-a9f5ea9fcdc7)

**Comment by enisn** [comment]
It's changed in **v8.1** in this PR: https://github.com/abpframework/abp/pull/18842

No need to backport this one. It was planned for 8.1
