### ISSUE TITLE
Angular - Action buttons are missing.

### ISSUE THREAD

**Issue by oykuermann** [abpframework/abp#19848]
Angular app template v8.1.3

Action buttons are missing for Admin on Users & Roles pages.
![image](https://github.com/abpframework/abp/assets/142304401/8b72bd38-d78d-44b3-9d73-023dc3373994)
![image](https://github.com/abpframework/abp/assets/142304401/72f1eeec-722f-49f9-86ec-59212059d86c)

![image](https://github.com/abpframework/abp/assets/142304401/181b17ac-6459-4d38-9f2a-a545e3353879)

**Comment by sumeyyeKurtulus** [comment]
Resolved in https://github.com/abpframework/abp/pull/19846
