### ISSUE TITLE
Request new Patch for dependant package vulnerability fix

### ISSUE THREAD

**Issue by RicardoLans** [abpframework/abp#19845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

All Volo.Abp.**.EntityFrameworkCore v8.1.3 packages still has dependencies on [Microsoft.EntityFrameworkCore.SqlServer 8.0.0](https://github.com/abpframework/abp/blob/8.1.3/Directory.Packages.props)
Which somewhere down the drain references old System.IdentityModel.Tokens.Jwt 6.24.0 which contains a known vulnerability.

Volo.Abp.AspNetCore 8.1.3 has a dependency on [Microsoft.AspNetCore.Authentication.OpenIdConnect 8.0.0](https://github.com/abpframework/abp/blob/8.1.3/Directory.Packages.props)
Which somewhere down the drain references old System.IdentityModel.Tokens.Jwt 7.0.3 which also contains a known vulnerability.

Based on the current [dev branch](https://github.com/abpframework/abp/blob/dev/Directory.Packages.props) you already fixed Microsoft.EntityFrameworkCore.SqlServer using version 8.0.4
Microsoft.AspNetCore.Authentication.OpenIdConnect using version 8.0.4

### Describe the solution you'd like

Is it possible to patch these package updates soon?

**Comment by realLiangshiwei** [comment]
Hi,
We upgraded the packages in 8.2.0, and it will be released soon
https://github.com/abpframework/abp/pull/19730

As a temporary solution, you can add references to the latest versions of these packages in your project

**Comment by RicardoLans** [comment]
Ah sweet I missed that PR when I searched this repo, ill close this and wait for 8.2 release :) thanks for the quick response.
