### ISSUE TITLE
I want to use new blazor webapp for my new project. Please give me guide line on that

### ISSUE THREAD

**Issue by freebsensetips** [abpframework/abp#19849]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

I want to use new blazor webapp for my new project. Please give me guide line on that

As found in 8.2.preview it going to launch but how can I get started with that please.

**Comment by realLiangshiwei** [comment]
When 8.2 is released, you can use the ABP CLI to create a Blazor web app project

**Comment by freebsensetips** [comment]
What if I want to use this with preview edition ? Can you help me on that please

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/blob/dev/docs/en/Migration-Guides/Abp-8-2-Blazor-Web-App.md

https://docs.abp.io/en/abp/latest/Previews

**Comment by freebsensetips** [comment]
![image](https://github.com/abpframework/abp/assets/111872178/2d223212-35bf-419e-bfad-9e5e969e40a5)

Is I am doing something wrong ??

**Comment by freebsensetips** [comment]
![image](https://github.com/abpframework/abp/assets/111872178/73cc7cba-0501-42ad-bf91-1b3dddca186c)

**Comment by realLiangshiwei** [comment]
The version 8.2.0 has not been released yet

**Comment by freebsensetips** [comment]
Actually I want to use 8.2-preview to generate blazor-webapp as it is included in that..

**Comment by justinb9909** [comment]
try updating your CLI:

abp cli update --preview

**Comment by MuhammadFayed** [comment]
> try updating your CLI:
> 
> abp cli update --preview

The command does not update to preview, just staying on the latest installed version [8.1.3]

Are we missing something here ?

![image](https://github.com/abpframework/abp/assets/5268288/6aa1e669-5421-4762-9df7-1c9af0dc2bf7)

**Comment by realLiangshiwei** [comment]
The 8.2.0 preview haven't released

**Comment by freebsensetips** [comment]
The latest template version (8.1.3) is different than the CLI version (8.2.0-rc.1).

So its not create webapp folder
