### ISSUE TITLE
MySQL can't create table.

### ISSUE THREAD

**Issue by MXPiao** [abpframework/abp#1985]
Download 1.0 application from abo.io,install Volo.Abp.EntityFrameworkCore.MySQL, then run DbMigrator

![AX](https://user-images.githubusercontent.com/13601390/67298633-1c0dc800-f51e-11e9-8fdb-521e9524ba85.png)

**Comment by Y2zz** [comment]
Custom table?

**Comment by MXPiao** [comment]
no additional table,only modify to use MySQL

**Comment by csr2** [comment]
@MXPiao How to deal with this error？

**Comment by maliming** [comment]
@csr2  see https://github.com/abpframework/abp/issues/1920#issuecomment-543551659

**Comment by csr2** [comment]
@maliming  加了没用，这是这张表AbpAuditLogs报错的

**Comment by maliming** [comment]
@csr2 Please create an issue separately and describe it in detail.

**Comment by csr2** [comment]
Use this command “update-database”，
Report an error，
Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `AbpAuditLogs` (
    `Id` uniqueidentifier NOT NULL,
    `ExtraProperties` nvarchar(max) NULL,
    `ConcurrencyStamp` nvarchar(max) NULL,
    `ApplicationName` nvarchar(96) NULL,
    `UserId` uniqueidentifier NULL,
    `UserName` nvarchar(256) NULL,
    `TenantId` uniqueidentifier NULL,
    `TenantName` nvarchar(max) NULL,
    `ImpersonatorUserId` uniqueidentifier NULL,
    `ImpersonatorTenantId` uniqueidentifier NULL,
    `ExecutionTime` datetime2(6) NOT NULL,
    `ExecutionDuration` int NOT NULL,
    `ClientIpAddress` nvarchar(64) NULL,
    `ClientName` nvarchar(128) NULL,
    `ClientId` nvarchar(64) NULL,
    `CorrelationId` nvarchar(64) NULL,
    `BrowserInfo` nvarchar(512) NULL,
    `HttpMethod` nvarchar(16) NULL,
    `Url` nvarchar(256) NULL,
    `Exceptions` nvarchar(4000) NULL,
    `Comments` nvarchar(256) NULL,
    `HttpStatusCode` int NULL,
    CONSTRAINT `PK_AbpAuditLogs` PRIMARY KEY (`Id`)
);
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uniqueidentifier NOT NULL,
    `ExtraProperties` nvarchar(max) NULL,
    `Conc' at line 2
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uniqueidentifier NOT NULL,
    `ExtraProperties` nvarchar(max) NULL,
    `Conc' at line 2

**Comment by maliming** [comment]
You should delete the existing mssql migration and re-add the mysql migration.

**Comment by csr2** [comment]
@maliming This operation is no problem, thank you
