### ISSUE TITLE
Property injection not work

### ISSUE THREAD

**Issue by v2codes** [abpframework/abp#19869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Thanks to Abp's excellent design and implementation. I've been using ABP for web.
Recently, I integrate ABP modules into the WPF project. 
The properties of ApplicationService and BasicRepositoryBase always null. 
It seems that AutoFac's Property Injection is not working.
Asking help to solve this, thanks a lot !

**Exception：**
![image](https://github.com/abpframework/abp/assets/32858631/4c088e4d-d0c1-4071-91ea-47af19bb8396)

**Project Structure：**
![image](https://github.com/abpframework/abp/assets/32858631/6cefe48f-3ada-4a0b-b4b2-71ab474b42ae)

**Program main entry：**
```
 var builder = Host.CreateApplicationBuilder(args);

_abpApplication = await builder.Services.AddApplicationAsync<NCWpfAppModule>(options =>
{
    options.UseAutofac();
    options.Services.AddLogging(loggingBuilder => loggingBuilder.AddSerilog(dispose: true));
    options.Services.AddHostedService<NCWpfAppHostedServcie<App, LoginWindow>>();
    options.Services.AddRegion().AddMvvm();
});

_host = builder.Build().UseRegion();
await _host.InitializeAsync();
await _host.RunAsync();
return 0; 
``` 

**AppModule：** 
```
[DependsOn(typeof(AbpAutofacModule),
               typeof(NCWpfFrameworkModule),
               typeof(NCWpfHomeModule),
               typeof(NCWpfEntityFrameworkCoreModule),
               typeof(AbpEntityFrameworkCoreSqlServerModule),
               typeof(NCWpfApplicationContractsModule),
               typeof(NCWpfApplicationModule))]
    public class NCWpfAppModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpDbContextOptions>(options =>
            {
                options.UseSqlServer();
            });
        }
    }
```

### Version
v8.1.3

### User Interface
Common (Default)

### Database Provider
EF Core (Default)

### Operation System
Windows (Default)

**Comment by maliming** [comment]
Can you reproduce this with less code?

**Comment by v2codes** [comment]
> Can you reproduce this with less code?

Thank you , In the following repository, dev branch.
https://github.com/v2codes/NC.Wpf.Framework/tree/dev

**Comment by maliming** [comment]
hi

Can you use a simple project?

Such as ABP WPF project. 
https://docs.abp.io/en/abp/latest/Startup-Templates/WPF

**Comment by v2codes** [comment]
There is no problem with Property Injection when using templates. It should be some problems with the way I use IHost startup. But there is another problem with the template. After called the Repository query method, it gets stuck. SQL was output in the log, there is no exception and any response.
Simple project is in the branch abp-wpf-template：
https://github.com/v2codes/NC.Wpf.Framework/tree/abp-wpf-template

**Comment by maliming** [comment]
>  After called the Repository query method, it gets stuck. SQL was output in the log, there is no exception and any response.

`var result = AsyncHelper.RunSync(() => _sampleAppService.GetAsync());`


The property injects of `SampleAppService` works.

**Comment by v2codes** [comment]
> > After called the Repository query method, it gets stuck. SQL was output in the log, there is no exception and any response.
> 
> `var result = AsyncHelper.RunSync(() => _sampleAppService.GetAsync());`
> 
> The property injects of `SampleAppService` works.

I solved the Property Injection problem by referring to the Program.cs in the console template. 
Like this:
![image](https://github.com/abpframework/abp/assets/32858631/4a37a1a8-f043-401c-a780-3fb9e18e10e1)

**Comment by v2codes** [comment]
@maliming  Thanks a lot, everything is all right!

**Comment by abdoutech93** [comment]
Facing the same issue, all BasicRepositoryBase always null.
![image](https://github.com/user-attachments/assets/813096f3-6e04-4f48-bf95-146b701d9972)
