### ISSUE TITLE
Make `DynamicFileProvider` support `web farm`.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#19861]
https://support.abp.io/QA/Questions/7209/

**Comment by leonkosak** [comment]
Is this somehow related @maliming?
https://github.com/abpframework/abp/issues/14107

**Comment by maliming** [comment]
hi @leonkosak 

This [PR](https://github.com/abpframework/abp/pull/19870) will store the bundle files in the cache(`reads`).

It doesn't have much to do with #14107

**Comment by hikalkan** [comment]
Resolved by https://github.com/abpframework/abp/pull/19870
