### ISSUE TITLE
EF core CLI does't work in .EntityFrameworkCore.DbMigrations

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#1986]
Run ef core CLI under .EntityFrameworkCore.DbMigrations project, it doesn't work, it will lookup the appsettings.json file under the project, no such file be found.

Follow the guidelines docs, set a start up project, open the Package Manager Console, select .EntityFrameworkCore.DbMigrations project as the Default Project then run the Add-Migration it works.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/1516#issuecomment-513649432
