### ISSUE TITLE
IApplicationConfigurationContributor is not auto discovered as documented unless explicitly added to in ConfigureService

### ISSUE THREAD

**Issue by nurlix** [abpframework/abp#19879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

IApplicationConfigurationContributor is not auto discovered as documented 

![image](https://github.com/abpframework/abp/assets/12874050/6f96f945-cb67-46b2-9f21-12aae3cb9f1c)

```
public class MyApplicationConfigurationContributor : IApplicationConfigurationContributor
{
    public Task ContributeAsync(ApplicationConfigurationContributorContext context)
    {
        context.ApplicationConfiguration.SetProperty("userStationId", null);
        return Task.CompletedTask;
    }
}
```

![image](https://github.com/abpframework/abp/assets/12874050/e4d62791-2cf5-48f6-a942-7d670ad9067b)

not auto discovered unless
as documented here [https://engincanv.github.io/abp/2022/08/02/extending-the-application-configuration-endpoint.html](url)
```
Configure<AbpApplicationConfigurationOptions>(options =>
{
    options.Contributors.AddIfNotContains(new MyApplicationConfigurationContributor());
});
```

![image](https://github.com/abpframework/abp/assets/12874050/74a75416-36f9-454b-a0f1-38b2530c15ad)

am I missing something?

### Version

8.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

I will update the document. Change code will bring breaking change.  )
