### ISSUE TITLE
Unable to find package leptonxlite leptonxlitetheme with 3.2.0-rc.1

### ISSUE THREAD

**Issue by zhaofenglee** [abpframework/abp#19875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/abpframework/abp/assets/111716814/a27fb752-d7c6-4b10-ad6c-02bbd7518f13)

### Version

8.2.0-rc.1

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
We will release it today

**Comment by leksts** [comment]
Will you also release the corresponding NuGet's; Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXLiteTheme and Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite?

> error NU1102: Unable to find package Volo.Abp.AspNetCore.Components.WebAssembly.LeptonXLiteTheme with version (>= 3.2.0-0)

**Comment by zhaofenglee** [comment]
The npm package already exists in versions 8.2.0-rc1~2, but the nuget package does not. In addition, the project may encounter the following errors.

![image](https://github.com/abpframework/abp/assets/111716814/b62a11d6-ce01-459d-98dd-97761fc8ab62)

The following is sample.
https://github.com/zhaofenglee/abp-test-0522

**Comment by realLiangshiwei** [comment]
Upgrade your CLI version to rc2

**Comment by zhaofenglee** [comment]
![image](https://github.com/abpframework/abp/assets/111716814/8c9463f8-926e-4087-988d-fe751ef4f478)
![image](https://github.com/abpframework/abp/assets/111716814/e1d0eb3a-9f8b-4743-8033-397d17e76b9f)

**Comment by realLiangshiwei** [comment]
Add the night source package to your nuget

`https://www.myget.org/F/abp-nightly/api/v3/index.json`

**Comment by zhaofenglee** [comment]
Adding the abp-nightly NuGet package and modifying the LeptonXLite version to 3.2.0-preview20240508 can start up normally.

![image](https://github.com/abpframework/abp/assets/111716814/b97eb983-6650-4dea-9447-d619904c86e2)

**Comment by realLiangshiwei** [comment]
We will release the leptonx nuget package today.
