### ISSUE TITLE
Is there a way update the template to latest version

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#1987]
It is very convenient when use "abp update" cli, it could update the solution or project all ABP related package.

Is there a way also could update the template files to latest version, for example, one package updated db migration, the version of the package get updated, but the db migration file not be pulled to local

**Comment by mkmita** [comment]
I'm looking for upgrade solution also

**Comment by hitaspdotnet** [comment]
you can choice what version you want or what branch and using your favorite version controller to keep your solution up to day 
`abp new MyApp --version 'dev'`

**Comment by KevinFarrow** [comment]
@hitaspdotnet I thought the "abp new" command was for creating new apps? Are you saying we can run the command over an existing app and all files will be updated in-place, ignoring any files I have already made changes to?

**Comment by hitaspdotnet** [comment]
> I thought the "abp new" command was for creating new apps?

Exactly.
> we can run the command over an existing app and all files will be updated in-place, ignoring any files I have already made changes to?

Of curse it's impossible. You can use [VC](https://en.wikipedia.org/wiki/Version_control) and try to merge with newest version you just generated with Abp.Cli

**Comment by hikalkan** [comment]
>Is there a way also could update the template files to latest version?

No way. ABP CLI does not change the solution files which might be changed after the initial creation.
However, the template is almost empty and most of times doesn't need to be changed while upgrading NuGet packages.
