### ISSUE TITLE
I want to use new blazor webapp for my new project. Please give me guide line on that

### ISSUE THREAD

**Issue by freebsensetips** [abpframework/abp#19878]
The latest template version (8.1.3) is different than the CLI version (8.2.0-rc.1).

So its not create webapp project and webapp.client project.

https://github.com/abpframework/abp/issues/19849

**Comment by realLiangshiwei** [comment]
* `abp cli update --preview`
* `abp new BookStore -t app -u blazor-webapp --preview`
* Add the night source package to your Nuget sources

https://www.myget.org/F/abp-nightly/api/v3/index.json

**Comment by freebsensetips** [comment]
Thank you its generated now... One question Can I add blog module Or CMS Kit Module in this Web App project ??

**Comment by realLiangshiwei** [comment]
Yes, I'm closing this. because this is not an issue
