### ISSUE TITLE
Cannot create Blazor WebApp Project in suite (8.2.0-rc.1)

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#19889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I updated to preview version of suite, then created a new Blazor WebApp solution but there's no Blazor project created.

Kind Regards, Dan

### Reproduction Steps

Update to latest Cli and Suite (8.2.0-rc.1)

![image](https://github.com/abpframework/abp/assets/69393775/b7fc10b4-93dc-470c-84de-ce8ff1842362)

Create new project, selecting Blazor WebApp as the type. Solution is created but get the following popup when finished

![image](https://github.com/abpframework/abp/assets/69393775/6ea9815a-9c91-4817-ac17-d3367e6182dc)

If I look at the folder, the Blazor project is missing:

![image](https://github.com/abpframework/abp/assets/69393775/4a57971d-80d7-40b8-ac5d-638e333bab68)

### Actual behavior

Blazor project not created

### Version

8.2.0-rc.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

User Interface is Blazor WebApp

**Comment by realLiangshiwei** [comment]
We fixed the problem in the 8.2.0-rc2.
You can upgrade your CLI and use CLI to create the project

**Comment by DonVliet** [comment]
@realLiangshiwei 

Thank you, Dan
