### ISSUE TITLE
License Change Consideration

### ISSUE THREAD

**Issue by nenitiko** [abpframework/abp#1988]
Propose to change the Licensing to [MIT](https://opensource.org/licenses/MIT) or even [Apache](https://opensource.org/licenses/Apache-2.0) instead of the current and more restrictive LGPL.

**Comment by Trojaner** [comment]
ABP does not have a Contributor License Agreement (CLA). This means copyright remains on each contributor and is not shared with Volosoft. 

In short this means that changing the license would require approval of each one of the [72 contributors](https://github.com/abpframework/abp/graphs/contributors).

See https://www.openlogic.com/blog/openssl-license-change-cautionary-tale for a similar case.

**Comment by ismcagdas** [comment]
@nenitiko the Framework itself will stay as LGPL but application modules will be MIT. We will make necessary changes and it is on our plan.

**Comment by mschaefer88** [comment]
Is there any plan **when** the modules will be available as **MIT**?

**Comment by ismcagdas** [comment]
@mschaefer88 probably around 2 weeks.

**Comment by hikalkan** [comment]
Created https://github.com/abpframework/abp/issues/2352
