### ISSUE TITLE
[8.2.0-rc.2] Lepton.Global errors trying to run Suite

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#19897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to run Suite I get the following **Lepton.Global** errors

![image](https://github.com/abpframework/abp/assets/69393775/c68f0cdf-4b82-4f13-9a97-fd1e598214bd)

### Reproduction Steps

Upgrade abp and suite to version 8.2.0-rc.2

### Version

8.2.0-rc.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Hi,

we will check it.

**Comment by realLiangshiwei** [comment]
Fixed.

* `dotnet nuget locals all --clear`
* `abp suite update --version 8.2.0-rc.2`

**Comment by DonVliet** [comment]
> Fixed.
> 
> * `dotnet nuget locals all --clear`
> * `abp suite update --version 8.2.0-rc.2`

@realLiangshiwei Thank you so much for sorting this for us, Dan :-)
