### ISSUE TITLE
missing local update events when PublishEntityUpdatedEventWhenNavigationChanges is disabled

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#19895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When PublishEntityUpdatedEventWhenNavigationChanges is disabled and you change a (normal) property and a navigation property, no update event is generated.

### Reproduction Steps

1. disable PublishEntityUpdatedEventWhenNavigationChanges
2. change an navigation property (set to null) and a primitive property on an entity
3. listen for (local) update events

### Expected behavior

update event should be generated

### Actual behavior

no updates events are generated

### Known Workarounds

no clean workaround because PublishEventsForTrackedEntity is called before DetectChange is done

### Version

8.1.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

ChangeTracker.StateChanged is only called once per entity (for the first changed property) - so checking IsModified ([here](https://github.com/abpframework/abp/blob/4f282552fd89d5b612e53c82ae07e29a2cd8d0c5/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L375)) is not reliable because its only true for the first property. if PublishEntityUpdatedEventWhenNavigationChanges is enabled, you dont depend on IsModified state.

a solution could be to override ChangeDetector.DetectChanges and call PublishEventsForTrackedEntity after detection is done completly or listen on ChangeDetector.DetectedEntityChanges - but im not sure which side effects this might have. in both cases, EntityState is updated to Unchanged if no changes were detected, so there is no need for checking IsModified at this point

**Comment by maliming** [comment]
hi

Can you share some code to reproduce?

**Comment by puschie286** [comment]
[missing-update.zip](https://github.com/abpframework/abp/files/15398625/missing-update.zip)

Disabled PublishEntityUpdatedEventWhenNavigationChanges in domain
Added ChangeListener to domain

if you update one property of a book (example price to 15) you see the "Book changed" message in console
if you update one native property and the author, no event is generated and the "Book changed" is not triggered

**Comment by maliming** [comment]
We check the `IsModified` to determine if a property has changed, but EF Core gives us the wrong value. 

I will check it in depth. We may need to patch this behavior again.

![image](https://github.com/abpframework/abp/assets/6908465/68d205dd-1ace-448c-8774-27ced69c5816)

**Comment by puschie286** [comment]
thanks - please note the information in the "Other information" section of the issue. the current trigger point for PublishEventsForTrackedEntity seems to be too early

**Comment by maliming** [comment]
hi

You can try to override the `SaveChangesAsync` method in your `BookStoreDbContext`, I will do more tests.

```cs
public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = new CancellationToken())
{
    foreach (var entry in AbpEfCoreNavigationHelper.GetChangedEntityEntries())
    {
        if (entry.Properties.Any(x => x.IsModified && (x.Metadata.ValueGenerated == ValueGenerated.Never || x.Metadata.ValueGenerated == ValueGenerated.OnAdd)))
        {
            if (entry.Properties.Where(x => x.IsModified).All(x => x.Metadata.IsForeignKey()))
            {
                // Skip `PublishEntityDeletedEvent/PublishEntityUpdatedEvent` if only foreign keys have changed.
                break;
            }

            if (entry.Entity is ISoftDelete && entry.Entity.As<ISoftDelete>().IsDeleted)
            {
                EntityChangeEventHelper.PublishEntityDeletedEvent(entry.Entity);
            }
            else
            {
                EntityChangeEventHelper.PublishEntityUpdatedEvent(entry.Entity);
            }
        }
    }

    return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
}
```

**Comment by puschie286** [comment]
well our workaround is to override PublishEventsForTrackedEntity and remove the IsModified check ( but we also want updates for all entity properties - so we ignoring PublishEntityUpdatedEventWhenNavigationChanges on purpose )

```
protected override void PublishEventsForTrackedEntity( EntityEntry entry )
{
	switch (entry.State)
        {
            case EntityState.Added:
                ApplyAbpConceptsForAddedEntity(entry);
                EntityChangeEventHelper.PublishEntityCreatedEvent(entry.Entity);
                break;

            case EntityState.Modified:
                ApplyAbpConceptsForModifiedEntity(entry);
                if (entry.Entity is ISoftDelete && entry.Entity.As<ISoftDelete>().IsDeleted)
                {
                    EntityChangeEventHelper.PublishEntityDeletedEvent(entry.Entity);
                }
                else
                {
                    EntityChangeEventHelper.PublishEntityUpdatedEvent(entry.Entity);
                }
                break;

            case EntityState.Deleted:
                ApplyAbpConceptsForDeletedEntity(entry);
                EntityChangeEventHelper.PublishEntityDeletedEvent(entry.Entity);
                break;
        }
}
```

**Comment by maliming** [comment]
Is this work for you?

https://github.com/abpframework/abp/issues/19895#issuecomment-2124101557

**Comment by puschie286** [comment]
yes - this solution seems to work.

if you going to edit AbpDbContext, please create an additional AbpEntityChangeOptions property (like PublishEntityUpdatedEventWhenForeignKeyChanges) to dont skip update / delete event on the entity itself:
```c#
if ( !EntityChangeOptions.Value.PublishEntityUpdatedEventWhenForeignKeyChanges && entry.Properties.Where(x => x.IsModified).All(x => x.Metadata.IsForeignKey()))
{
      // Skip `PublishEntityDeletedEvent/PublishEntityUpdatedEvent` if only foreign keys have changed.
      break;
}
```

our goal was to get all update events for the entity itself but non on the navigation entity (when we found this problem)
(described in the second part of the #19894 issue)

**Comment by maliming** [comment]
ok.

**Comment by maliming** [comment]
The fix PR https://github.com/abpframework/abp/pull/19910
You can test it if you have time.

**Comment by puschie286** [comment]
Yes it fix the skipped update problem. thanks
