### ISSUE TITLE
document AbpEntityChangeOptions and add aditional PublishNavigationEntityUpdatedEventWhenNavigationChanges

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#19894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

AbpEntityChangeOptions (with PublishEntityUpdatedEventWhenNavigationChanges) should be documented in local event bus (its surprising that events are generated for unchanged entities)

Currently this option control the update event generation for the entity itself and the navigation entity - so you can only disable both. If you want only events for the entity itself, you have to override AbpDbContext and implement it yourself

([entity self](https://github.com/abpframework/abp/blob/4f282552fd89d5b612e53c82ae07e29a2cd8d0c5/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L392) and [navigation entity](https://github.com/abpframework/abp/blob/4f282552fd89d5b612e53c82ae07e29a2cd8d0c5/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L195)

### Describe the solution you'd like

Add information about AbpEntityChangeOptions on LocalEventBus documentation page.

Add PublishNavigationEntityUpdatedEventWhenNavigationChanges and use it in [SaveChangesAsync](https://github.com/abpframework/abp/blob/4f282552fd89d5b612e53c82ae07e29a2cd8d0c5/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L195)

**Comment by maliming** [comment]
Resolve by https://github.com/abpframework/abp/pull/19901
