### ISSUE TITLE
 Nswag typescript overload.

### ISSUE THREAD

**Issue by vincywindy** [abpframework/abp#1990]
> > > The reason is because.typescript does not allow this kind of overload.
> > > This is a bug related with nswag.
> > > The problem is get roles and get roles with param id, it will generate two func with the same name getRoles with different param and response type.
> > > But ts does not allow this kind of overload.
> > > One solution is to use another generation mode, but it is very ugly.
> > > It generates something like getRoles1 getRoles2 which is unreadable.
> > 
> > 
> > Yes，I think the best way is use method+function names，like /api/identity/getroles /api/identity/postroles,but it seems like there are no way to do it on nswag
> 
> getRoles and PostRoles can be generated.
> but getRoles(no param) and getRoles(withParam) is a pain

How about use this mode ,use differrent tag with the same method
![image](https://user-images.githubusercontent.com/30209724/67348769-910deb80-f578-11e9-90c4-15c803ed77b6.png)

_Originally posted by @vincywindy in https://github.com/abpframework/abp/issues/1872#issuecomment-545224752_

**Comment by Trojaner** [comment]
You can also try [openapi-generator](https://github.com/OpenAPITools/openapi-generator) instead of nswag.

**Comment by vincywindy** [comment]
I know there are many way to slove it, but I want to know which is the "official" way

**Comment by Trojaner** [comment]
There is no official way but the recommend way is using operationId's since most code generators support them

**Comment by vincywindy** [comment]
> There is no official way but the recommend way is using operationId's since most code generators support them

I mean witch solutions will the angular temple uesd
