### ISSUE TITLE
Blazor webapp language switch error

### ISSUE THREAD

**Issue by zhaofenglee** [abpframework/abp#19911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the basic theme, an error occurred while switching the language.

![image](https://github.com/abpframework/abp/assets/111716814/85eb6e17-f99d-45c4-ae02-c2363497c84e)

### Reproduction Steps

1.Creating a project using CLI.
abp new Acme.BookStore -t app -u blazor-webapp --preview --theme basic -csf 
2.Migrating and running the project.
3.Switching languages.

### Version

8.2.0-rc.2

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Upgrading Blazorise to 1.5.2 will solve this.

https://github.com/Megabit/Blazorise/pull/5408

https://blazorise.com/news/release-notes/151

**Comment by zhaofenglee** [comment]
After the upgrade, it runs normally. Thanks
