### ISSUE TITLE
BookStore  - Identity/Roles Vew JS error

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#1991]
https://localhost:44361/Identity/Roles

using nightly builds (v5.0.0-preview20191015)

![Capture](https://user-images.githubusercontent.com/40014477/67360892-a9423280-f599-11e9-8f6a-92329b1defbd.PNG)

**Comment by maliming** [comment]
Can you try abp 1.0?

**Comment by 274188A** [comment]
yeah that works

**Comment by 274188A** [comment]
@maliming This is broken again...

**Comment by maliming** [comment]
Try clean and rebuild the project?
```
dotnet clean
dotnet build
```

**Comment by 274188A** [comment]
yup that did the trick!
