### ISSUE TITLE
No project found in the directory  when run abp install-libs

### ISSUE THREAD

**Issue by Huangzc88** [abpframework/abp#19929]
After restoring npm packages through the package.json file in an ASP.NET Core web project, when executing the 'abp install-libs' command in the root directory of the web project, the prompt 'No project found in the directory' appears.

![image](https://github.com/abpframework/abp/assets/31158857/c9251b57-9ee5-47d1-98c0-5cee8c7e0a67)

My abp project is not a standard abp-cli-created project, but rather a self-built project based on abp modular conventions, which depends on some official abp modules and has gone through upgrades from abp 3.0 to 6.0 and then to 8.0. 

Initially, there was a gulp.js file in the root directory of the web project, which I have now deleted. 

Based on the documentation for client-side package copying in the newer versions, I have added an abp.resourcemapping.js file in the project root directory.

when running the 'abp install-libs' command, it prompts with an error that no project is found.

I know that there are actually project files in the path where the command is run, so I don't know where the problem lies. Do you have any suggestions?

**Comment by realLiangshiwei** [comment]
> My abp project is not a standard abp-cli-created project, but rather a self-built project based on abp modular conventions, which depends on some official abp modules and has gone through upgrades from abp 3.0 to 6.0 and then to 8.0

Because your project is not a standard ABP template, you need to check your project

Here is the logic code for finding projects

https://github.com/abpframework/abp/blob/b46dfa722a36b3bd9cd903def1793b114ca639b4/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/LIbs/InstallLibsService.cs#L108-L129

**Comment by Huangzc88** [comment]
Hi [realLiangshiwei](https://github.com/realLiangshiwei),

Thanks for the answer, after I debugged the code, I found that it was this code that filtered the problem
![image](https://github.com/abpframework/abp/assets/31158857/041e358e-c1f7-4c5c-ae0d-6ac611ef6156)
![image](https://github.com/abpframework/abp/assets/31158857/cdc94fe1-5dbb-4255-a9cc-d0b399c2319f)

and when I removed the .git from the ExcludeDirectory collection, I was able to find the project.

I know what the problem is, my web project path goes like this: 

![image](https://github.com/abpframework/abp/assets/31158857/3cbe8bca-5eee-4f7f-ab56-aa60de099339)

This path just includes the . Git, so no project files are found，I think excluding the .git handling code can be optimized to prevent exceptions because the directory contains .git


![image](https://github.com/abpframework/abp/assets/31158857/03996853-bbba-4be7-a786-8597aeb37afb)
