### ISSUE TITLE
Cannot get value in AppSettings on the default page of AbpFramework, such as in Login.cshtml.cs

### ISSUE THREAD

**Issue by ynkdqe** [abpframework/abp#19923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

How to get value in appsettings in Page default of Abp as Login.cshtml.cs
![image](https://github.com/abpframework/abp/assets/43467307/be0db6d4-b2d0-4133-a994-aaeef8e84431)
In the picture, _mfaConfig always returns null even though I registered it in the AuthServerModule.
`var mfaConfig = configuration.GetSection(nameof(MfaConfig)).Get<MfaConfig>();`
`context.Services.AddSingleton(mfaConfig);`

### Version

ABP Framwork 8.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
This is not an issue .
You can check the document
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-8.0
https://docs.abp.io/en/abp/latest/Options
