### ISSUE TITLE
ABP Paid version

### ISSUE THREAD

**Issue by myomyinthan** [abpframework/abp#1992]
When will paid version come out and what kind of features will be included? All ASP.Net Zero features will be included?

**Comment by ismcagdas** [comment]
@myomyinthan abpframework will be free but we will provide paid services on top of it. The planned services are: Application Templates (Razor and Angular at first), UI Themes, Developer Tools, Premium Support, Pro Modules and some additional services like training etc... 

Our plan is to release those services in around 4 weeks. But, there will be some missing features like Organization Units, Chat etc... at the beginning. We will share the website URL and exact feature list in 4 weeks.

**Comment by myomyinthan** [comment]
Hi ismcagdas,
Thanks for you reply. Paid version will come out with microservice approach ? :)
