### ISSUE TITLE
GetIdentityUsersInput recommends inheriting an extended property

### ISSUE THREAD

**Issue by shuangbaojun** [abpframework/abp#19937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

![image](https://github.com/abpframework/abp/assets/64063254/60c7c86c-e983-41c1-aa2f-ab0979e99cbc)

GetIdentityUsersInput recommends inheriting an extended property. This facilitates business customization.

@maliming 

### Describe the solution you'd like

![image](https://github.com/abpframework/abp/assets/64063254/c283a870-63d3-4222-8664-8edc36522417)

**Comment by maliming** [comment]
ok
