### ISSUE TITLE
Documentation: topic labels

### ISSUE THREAD

**Issue by Ice2burn** [abpframework/abp#1994]
Since your documentation is in active development, I would like to suggest to mark recently added documents with [new] label in the documentation tree. This way we can track changes and learn new framework features as soon as you update the documentation. 

Devexpress documentation for example:
![image](https://user-images.githubusercontent.com/6002280/67386905-7e0e1200-f59e-11e9-9434-65af10561b09.png)

**Comment by Ice2burn** [comment]
Also last edit date might be helpfull at this stage

**Comment by hikalkan** [comment]
Good feature.
