### ISSUE TITLE
getaccesstoken err when granttype is client_credentials

### ISSUE THREAD

**Issue by mrh520** [abpframework/abp#19994]
version 7.4.4 upgrade 8.1.3
RequestPath = connect/token

{
  "Depth": 0,
  "ClassName": "Volo.Abp.Domain.Entities.EntityNotFoundException",
  "Message": "There is no such an entity. Entity type: Volo.Abp.Identity.IdentityUser, id: de8acc86-0046-4ea5-a3d6-3a11c865bfc1",
  "Source": "Volo.Abp.Identity.Domain",
  "StackTraceString": "   at Volo.Abp.Identity.IdentityUserManager.GetByIdAsync(Guid id)\n   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)\n   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()\n   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)\n   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)\n   at Volo.Abp.Identity.IdentityDynamicClaimsPrincipalContributorCache.<>c__DisplayClass23_0.<<GetAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, Boolean considerUow, CancellationToken token)\n   at Volo.Abp.Identity.IdentityDynamicClaimsPrincipalContributorCache.GetAsync(Guid userId, Nullable`1 tenantId)\n   at Volo.Abp.Identity.IdentityDynamicClaimsPrincipalContributor.ContributeAsync(AbpClaimsPrincipalContributorContext context)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "HResult": -2146233088,
  "HelpURL": null
}

**Comment by maliming** [comment]
hi

Can you share the code to reproduce?

There should be no `userId` in `client_credentials` flow.

**Comment by mrh520** [comment]
Thanks for reply.

I just rewrote this method

public class AppTokenController : TokenController
{
    protected override async Task<IActionResult> HandleClientCredentialsAsync(OpenIddictRequest request)
    {
        // Note: the client credentials are automatically validated by OpenIddict:
        // if client_id or client_secret are invalid, this action won't be invoked.
        var application = await ApplicationManager.FindByClientIdAsync(request.ClientId);
        if (application == null)
        {
            throw new InvalidOperationException(L["TheApplicationDetailsCannotBeFound"]);
        }

        // Create a new ClaimsIdentity containing the claims that
        // will be used to create an id_token, a token or a code.
        var identity = new ClaimsIdentity(
            TokenValidationParameters.DefaultAuthenticationType,
            OpenIddictConstants.Claims.PreferredUsername,
            OpenIddictConstants.Claims.Role);

        // The Subject and PreferredUsername will be removed by <see cref="RemoveClaimsFromClientCredentialsGrantType"/>.
        // Use the client_id as the subject identifier.
        identity.AddClaim(OpenIddictConstants.Claims.Subject, await ApplicationManager.GetClientIdAsync(application));
        identity.AddClaim(OpenIddictConstants.Claims.PreferredUsername, await ApplicationManager.GetDisplayNameAsync(application));
        identity.AddClaim(OpenIddictApplicationConstants.Claims.CustomerId, await ApplicationManager.GetCustomerIdAsync(application) ?? "");

        // Note: In the original OAuth 2.0 specification, the client credentials grant
        // doesn't return an identity token, which is an OpenID Connect concept.
        //
        // As a non-standardized extension, OpenIddict allows returning an id_token
        // to convey information about the client application when the "openid" scope
        // is granted (i.e specified when calling principal.SetScopes()). When the "openid"
        // scope is not explicitly set, no identity token is returned to the client application.

        // Set the list of scopes granted to the client application in access_token.
        var principal = new ClaimsPrincipal(identity);

        principal.SetScopes(request.GetScopes());
        principal.SetResources(await GetResourcesAsync(request.GetScopes()));

        await OpenIddictClaimsPrincipalManager.HandleAsync(request, principal);

        return SignIn(principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
    }
}

**Comment by maliming** [comment]
Make sure there is no `userId` claim in your `principal`.

**Comment by mrh520** [comment]
I did not find userId in the rewrite method debugging

**Comment by maliming** [comment]
Please share the full error stack or a simple test project.

**Comment by mrh520** [comment]
thinks.
this error cannot be replicated locally ,no error log was recorded for local debugging.
Can you determine whether to search user information according to granttype

**Comment by maliming** [comment]
There is no user concept in the `client_credentials` flow.

**Comment by mrh520** [comment]
claim type  sub  mapTo userId ？

**Comment by mrh520** [comment]
![image](https://github.com/abpframework/abp/assets/20501328/db5d8d27-3b7c-4f93-9a62-7fce52d2073e)

**Comment by mrh520** [comment]
> Make sure there is no `userId` claim in your `principal`.

![image](https://github.com/abpframework/abp/assets/20501328/9d152cf1-5248-4130-b00c-6f1d334f0001)

**Comment by maliming** [comment]
This seems to be a problem. I will find a way to fix this.

**Comment by mrh520** [comment]
will this issue be resolved in the future?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/20045

**Comment by mrh520** [comment]
thank you
