### ISSUE TITLE
The show/hide icon on the password field does not change when the user toggles it.

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#19991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

it may be a design decision but the issue appears to be related to a bug. In the Auth server, which is essentially an MVC page within Lepton-x, there is a password field that includes an icon.

![CleanShot 2024-06-06 at 20 20 55@2x](https://github.com/abpframework/abp/assets/2217899/cc7167f6-0406-4c02-a079-d9dfe3ca5e5f)

### Reproduction Steps

	1.	Go to https://commercial-demo.abp.io/Account/Login
	2.	Click the icon next to the password field
 

### Expected behavior

When a user clicks the icon, it should change its appearance depending on whether it’s visible or invisible.

### Actual behavior

The input type changes the text to a password when entered, but the icon remains unchanged.

### Version

8.1

### User Interface

MVC

### Database Provider

None/Others

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
Thanks, I will fix the problem.
Move this issue to volo.
