### ISSUE TITLE
PermissionChecker.IsGrantedAsync always returns false

### ISSUE THREAD

**Issue by aalzehla** [abpframework/abp#2001]
I'm using microservices in my app and after upgrade to dotnet core 3 it fails.
to figure out what is happening, I run the latest MicroserviceDemo example and it fails. I dont know the problem is caused by the configuration of Microservice  in my app or it's bug.
since log shows that there is an issue related to authorization. I found that that the PermissionChecker.IsGrantedAsync always returns false. 
I think my issue is similar to #1610. 
the issue is solved there by introducing identity modules. i don't know know what does that mean. since the gateways already uses identity modules. and also i use the MicroserviceDemo example i just added the UseRouting to make it work as following:
 ```
app.MapWhen(
                ctx => ctx.Request.Path.ToString().StartsWith("/api/abp/") ||
                       ctx.Request.Path.ToString().StartsWith("/Abp/"),
                app2 =>
                {
                    app2.UseRouting();
                    app2.UseMvcWithDefaultRouteAndArea();
                }
            );
app.UseOcelot().Wait();
```
I don't know what to do.
I attached the backendAdminGateway log.
[logs.txt](https://github.com/abpframework/abp/files/3767465/logs.txt)

**Comment by mehmetuken** [comment]
Ocelot not ready .net core 3.0
Follow this #1764

**Comment by Trojaner** [comment]
I have similar issue since the upgrade to ABP v1.0: all kind of authorization requests to controllers fails now

**Comment by maliming** [comment]
@Trojaner  Can you share some logs or a project to reproduce the problem?

**Comment by Trojaner** [comment]
I can not provide a reproduction yet, however I created a test controller to see if it caused by IPermissionChecker too:

![grafik](https://user-images.githubusercontent.com/1809172/67562891-44691280-f728-11e9-9d48-cf6a3e157df5.png)

My conclusion is that I have the same issue as the IPermissionChecker always returns false for me too

**Comment by kaleyroy** [comment]
This problem is similar to #1720 
I think that may be a bug after ABP 0.22

We can fix this using below code in **HttApi.Host Module**
Hope this help 

>          app.UseAuthentication();
            app.Use(async (ctx, next) => //after authentication middleware
            {
                var currentPrincipalAccessor = ctx.RequestServices.GetRequiredService<ICurrentPrincipalAccessor>();
                var map = new Dictionary<string, string>()
                {
                    { "sub", AbpClaimTypes.UserId },
                    { "role", AbpClaimTypes.Role },
                    { "email", AbpClaimTypes.Email } //any other map
                };
                var mapClaims = currentPrincipalAccessor.Principal.Claims.Where(p => map.Keys.Contains(p.Type)).ToList();
                currentPrincipalAccessor.Principal.AddIdentity(new ClaimsIdentity(mapClaims.Select(p => new Claim(map[p.Type], p.Value, p.ValueType, p.Issuer))));
                await next();
            });

            app.UseAuthorization();
            app.UseAbpRequestLocalization();

**Comment by Trojaner** [comment]
Thank you @kaleyroy, your post helped me in finding the root issue.

I was able to fix this issue:
I am using a custom JWT middleware and was creating a new ClaimsPrincipal like this:
```cs
var claimsId = await GenerateClaimsIdAsync(...);
var newPrincipal = new ClaimsPrincipal(claimsId);
httpContext.User = newPrincipal;
```

I have modified the code to use the ICurrentPrincipalAccessor in combination with AddIdentitiy instead:
```cs
var claimsId = await GenerateClaimsIdAsync(...);
_currentPrincipalAccessor.Principal.AddIdentity(claimsId);
```

> I think that may be a bug after ABP 0.22

This is 100% the case because the issue suddenly appeared after I have upgraded from 0.22 to 1.0.2.

**Comment by aalzehla** [comment]
Thank you @kaleyroy, your solution fixed the problem. 
and i have to add the code not just to HttpApi.Host module, but to the gateway modules as well. 
Thank you all for help.
