### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by GaryShao** [abpframework/abp#2002]
Hi, I'm new to abp vnext framework. But I have been with .net core for 2 years. Recently, we wanna re-build our service with abp. Here is my question: how could I remove all of those web things off from it while at the same time keep the uow, model validation, exceptionhandling functions.  I only wanna web api(we choose vuejs as front end solution not razor), not Acme.BookStore.Web with Acme.BookStore.HttpApi.  I tried but it turned out that all service providers in abpcontroller are null; Could anyone tell me how to do it please. thx in advance. 

Detail: 
dotnet:  .net sdk 3.0
abp:  1.0.2

**Comment by KevinFarrow** [comment]
You should download the Angular version; this will give you 2 solutions: an Angular solution and a Web API solution.

You then just need to delete the Angular version and you will be left with just the Web API

**Comment by Trojaner** [comment]
You can use the ABP tool in combination with the --no-ui option

**Comment by hitaspdotnet** [comment]
@Trojaner Application template haven't --no-ui option yet. 
@GaryShao For now, @KevinFarrow is easiest way.

**Comment by GaryShao** [comment]
@KevinFarrow  @hitaspdotnet @Trojaner  thanks bros, u save my week!  I ever noticed it, but the wwwroot folder let me just ignored it. How stupied I am. Again thx all of you!
