### ISSUE TITLE
How to avoid global blocking in distributed event handlers

### ISSUE THREAD

**Issue by one-sword** [abpframework/abp#20020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to minimize the impact of an entire inbox queue being blocked due to an exception in one event handler in a distributed event processing system. For example, by distinguishing events generated by different aggregate roots, ensuring that only events from the same aggregate root are executed in one queue with ordered execution and error retries, rather than having a single queue for the entire inbox. However, it seems that there is currently no way to achieve this.

### Describe the solution you'd like

I hope to be able to differentiate inbox queues based on certain conditions to avoid global blocking.

**Comment by leuoson** [comment]
We are currently seeking a solution as our production environment has been impacted.  We are evaluating approaches to address the issues that have arisen.  Specifically, we have accumulated over 60,000 data entries in a single queue.  Preliminary analysis suggests that a specific event may be causing the backlog;  however, it appears that all events have been affected to some extent.
![image](https://github.com/user-attachments/assets/8eecc87a-9f17-4c07-89db-4e102f4bb318)

**Comment by maliming** [comment]
hi

I will add `Filter` parameter to `GetWaitingEventsAsync`. so you can get the events by some conditions.

Then you can add your background worker to process specific events.

See https://github.com/abpframework/abp/pull/21716
