### ISSUE TITLE
IDX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty.

### ISSUE THREAD

**Issue by wangyue20075** [abpframework/abp#20034]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

abp version is 8.1.4.
when i user localhost to access ,it's success.
but when i use the IP to access, it doesn't work properly. failed to validate the token.
IDX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty.

![2024-06-13_193101](https://github.com/abpframework/abp/assets/4567121/773d985d-2508-4b0b-8eaf-9a2f278c2092)
![2024-06-13_193335](https://github.com/abpframework/abp/assets/4567121/4c00e92f-9073-4c08-985a-1ef3d78165a4)

### Version

8.1.4

### User Interface

Common (Default)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/15379#issuecomment-1377129014

**Comment by wangyue20075** [comment]
It's success.


context.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {

        options.Authority = configuration["AuthServer:Authority"];
        options.RequireHttpsMetadata = configuration.GetValue<bool>("AuthServer:RequireHttpsMetadata");
        options.MetadataAddress = configuration["AuthServer:Authority"]!;
        options.Audience = "Admin";

        // IDX10204: Unable to validate issuer on K8s if not set
        options.TokenValidationParameters = new TokenValidationParameters()
        {
            ValidIssuers = new[] { "https://192.168.1.61:44325/" },
            // IDX10500: Signature validation failed. No security keys were provided to validate the signature on K8s
            SignatureValidator = delegate (string token, TokenValidationParameters parameters)
            {
                var jwt = new Microsoft.IdentityModel.JsonWebTokens.JsonWebToken(token);
                return jwt;
            }
        };
    });

**Comment by wangyue20075** [comment]
SignatureValidator = delegate (string token, TokenValidationParameters parameters)
        {
            var jwt = new Microsoft.IdentityModel.JsonWebTokens.JsonWebToken(token);
            return jwt;
        }
