### ISSUE TITLE
New project doesn't seem to be working

### ISSUE THREAD

**Issue by gvassao** [abpframework/abp#20058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Generating a new project using the CLI doesn't seem to be working. There seems to be invalid usings being added to the top of the file:

![image](https://github.com/abpframework/abp/assets/3765243/248a35dc-32ed-4f2a-91e1-d5868d3e0d81)
![image](https://github.com/abpframework/abp/assets/3765243/2b07335d-30f9-42af-b078-c6d730971a5b)

### Reproduction Steps

Update the tool to the latest version:

`dotnet tool install -g Volo.Abp.Cli`
Tool 'volo.abp.cli' was reinstalled with the stable version (version '8.1.4').

`abp new Acme.BookStore -u angular --separate-auth-server --theme basic -csf`
ABP CLI 8.1.4
Creating your project...

After the project is generated, open the visual studio solution and compile

### Expected behavior

Solution compiles

### Actual behavior

There's a compilation error:

Error (active)	CS0234	The type or namespace name 'Basic' does not exist in the namespace 'Volo.Abp.AspNetCore.Mvc.UI.Theme' (are you missing an assembly reference?)	Acme.BookStore.HttpApi.Host /.../BookStoreHttpApiHostModule.cs	1	

### Version

8.1.4

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
we will fix it
You can delete them manually

**Comment by gvassao** [comment]
@realLiangshiwei thanks!
