### ISSUE TITLE
Add functionality to modules and debug along with main solution

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#2006]
Is there a way to add functionality to the modules (account, Identity etc.) and change their HTML layout, css, js etc. and then debug alongside my solution?

Initially I need to add additional functionality and make changes to the layout of the account module but in future I'll need to make changes to other modules that might depend on other modules, at which point I'll need to debug / step into each module from my main solution.

**Comment by KevinFarrow** [comment]
Is anyone going to answer this?

**Comment by ismcagdas** [comment]
@KevinFarrow for now, you can replace the views with your versions by placing your view into the same location as the original view file path. We are working on extensibility and there is no straight way to modify behavior of a module at the moment.

**Comment by KevinFarrow** [comment]
ok thanks for the update. Unfortunately it looks like abp.io is not going to be a usable base framework like Zero or Boilerplate, looking more like a WordPress type system where lots of different modules can be "plugged in". This would make it difficult for us to manage and keep control of the source in an Enterprise situation.

**Comment by ismcagdas** [comment]
@KevinFarrow we are currently working on this. We are expecting to finish this work in a month or so. You can check back and see it it works for you or not to decide.
