### ISSUE TITLE
Show a redirection page after login when scheme is different than http(s)

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#20078]
Show another page after login like below when redirect uri scheme is different than `http(s)`

![image](https://github.com/abpframework/abp/assets/23705418/016bdae5-9d9d-4e1f-8281-58cf79fc3ce2)

Since MAUI apps has their own schemes like: `myprojectname://login-callback` etc. We can show a message in the account login page that says "you can continue in the application" etc.

See the original problem: https://support.abp.io/QA/Questions/7323/BUG-Login-page-in-browser-does-not-redirect

**Comment by maliming** [comment]
The alert is browser behavior. We don't seem to be able to do that.

![image](https://github.com/abpframework/abp/assets/6908465/33225637-ff3c-468e-ae15-7f5c88677a2c)

**Comment by enisn** [comment]
Nope, this page:
![image](https://github.com/abpframework/abp/assets/23705418/496540a3-fdd6-4aa7-916e-268e98068eaf)

We need to show something like that:
![image](https://github.com/abpframework/abp/assets/23705418/114693a2-49a4-4760-aece-47e0d43b73ce)


Now it stays in the login page and users can't understand if login operation completed or not, They try to click login button again and again. We can show a page like this if redirected uri is different than https

**Comment by improwise** [comment]
Maybe you have already solved this as well but another problem with the current implementation (8.2) we noted is that it will fool the user into thinking that they entered the wrong password. This could happen if you try to login with an incorrect password, which would give you something like this:

![image](https://github.com/abpframework/abp/assets/2812422/dd29ec07-f9eb-4baf-85fc-72583fcaca0a)

However, if you then enter the correct password and tries again to login, you will actually get logged in, but page in browser wont update and still show that login failed.

**Comment by maliming** [comment]
hi @improwise 

Can you create a new issue?

Thanks.

**Comment by improwise** [comment]
> hi @improwise
> 
> Can you create a new issue?
> 
> Thanks.

It seems to be the same problem as is already described in this issue, that the login form does not update as it should after successful login, so depending on what has already been fixed, this might have been fixed as well?
