### ISSUE TITLE
Customize LoginModel

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#2007]
Given a `Volo.Abp.Account.Web.Pages.Account.LoginModel`

```
        protected virtual async Task<IdentityUser> CreateExternalUserAsync(ExternalLoginInfo info)
        {
            var emailAddress = info.Principal.FindFirstValue(AbpClaimTypes.Email);

            var user = new IdentityUser(GuidGenerator.Create(), emailAddress, emailAddress, CurrentTenant.Id);

            CheckIdentityErrors(await UserManager.CreateAsync(user));
            CheckIdentityErrors(await UserManager.SetEmailAsync(user, emailAddress));
            CheckIdentityErrors(await UserManager.AddLoginAsync(user, info));

            return user;
        }
```

How can I modify this method or customize it. When my user logs in using Facebook I want to set the username from the claims because now, only the email is being set.

Thank you!

**Comment by develtos** [comment]
I join the question. It would be nice to understand best practice to overloading external authorization methods. I'm particularly interested in how to use Volo.Abp.Ldap to authenticate users at login.

**Comment by maliming** [comment]
Also has a certain relationship with this issue. https://github.com/abpframework/abp/issues/2023

**Comment by wocar** [comment]
The logic should be moved to a IAccountManager or something like that or IAccountService si it is decoupled from the view? Does that sound like a good idea?

**Comment by maliming** [comment]
hi @wocar 

You can try the following code to override the CreateExternalUserAsync method of LoginModel. 
**[ExposeServices(typeof(LoginModel))]**

```
[ExposeServices(typeof(LoginModel))]
public class MyLoginModel : LoginModel
{
	public MyLoginModel(IAuthenticationSchemeProvider schemeProvider, IOptions<AbpAccountOptions> accountOptions) : base(schemeProvider, accountOptions)
	{

	}

	protected override Task<IdentityUser> CreateExternalUserAsync(ExternalLoginInfo info)
	{

		return base.CreateExternalUserAsync(info);
	}
}

```

**Comment by raminmjj** [comment]
Hi @maliming 
can you share a sample("How to customize user and related services")?
thank you.

**Comment by maliming** [comment]
> How to customize user 

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Users/AppUser.cs#L43
https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContextModelCreatingExtensions.cs#L24

>  related services

Almost all related services and components can be replaced and rewritten.
