### ISSUE TITLE
ABP CLI Exit code is always 0

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#20090]
### Documentation

Thrown exceptions cause the application to exit with code 0. 

It makes it hard to define errors in pipelines.

Here are some of examples:
![image](https://github.com/abpframework/abp/assets/23705418/2568546d-d41a-43e8-b49f-4d46ab798152)
---
![image](https://github.com/abpframework/abp/assets/23705418/4f111290-6f3b-45f5-9475-1269cf8491a3)

When exception thrown we should exit with a different code like `-1`.

**Comment by ebicoglu** [comment]
we can return `-1` for any error exit

**Comment by maliming** [comment]
> Exit codes have a minimum value of 0 and a maximum value of 255.

Which number should we use for `CliUsageException`?

Microsoft's approach:

https://github.com/dotnet/templating/blob/main/docs/Exit-Codes.md

**Comment by maliming** [comment]
You can edit the `exit code` in https://github.com/abpframework/abp/pull/20092/files#diff-90c7af3964984f93808b2686cc3038f01a774e859b21860586b8f0b46cdaa92cR86

**Comment by ebicoglu** [comment]
just return -1 as default
