### ISSUE TITLE
How to replace SetConfiguration() which is Obsolete in 1.0.2?

### ISSUE THREAD

**Issue by xiangxingxing** [abpframework/abp#2010]
<img width="917" alt="屏幕快照 2019-10-25 上午10 32 42" src="https://user-images.githubusercontent.com/52204046/67538824-d7974d80-f712-11e9-913c-5c61bfe71f75.png">
I want to know how to SetConfiguration in abp-1.0.2 to achieve the same effect shown in this picture. Thanks!

**Comment by maliming** [comment]
```
Host.CreateDefaultBuilder(args)
    .ConfigureHostConfiguration(configHost =>
    {
        configHost.SetBasePath(Directory.GetCurrentDirectory());
        configHost.AddJsonFile("hostsettings.json", optional: true);
        configHost.AddEnvironmentVariables(prefix: "PREFIX_");
        configHost.AddCommandLine(args);
    });
```

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/Program.cs#L45

**Comment by maliming** [comment]
```
internal static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureWebHostDefaults(webBuilder =>
		{
			webBuilder.UseStartup<Startup>();
		})
		.ConfigureAppConfiguration((context, builder) =>
		{

		})
		.UseAutofac()
		.UseSerilog();
```

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/Program.cs

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-3.0#configureappconfiguration

**Comment by xiangxingxing** [comment]
Thanks a lot!

**Comment by xiangxingxing** [comment]
> ```
> internal static IHostBuilder CreateHostBuilder(string[] args) =>
> 	Host.CreateDefaultBuilder(args)
> 		.ConfigureWebHostDefaults(webBuilder =>
> 		{
> 			webBuilder.UseStartup<Startup>();
> 		})
> 		.ConfigureAppConfiguration((context, builder) =>
> 		{
> 
> 		})
> 		.UseAutofac()
> 		.UseSerilog();
> ```
> 
> https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/Program.cs
> 
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-3.0#configureappconfiguration

thanks a lot!
