### ISSUE TITLE
BookStore Sample- Need Guidance

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#2012]
After cloning the entire Apb root I tried to run the `BookStore` (non-modular) sample project.

I noticed it has dependencies upon various `modules` so dug around and found the script `build-all.ps1`

The script does do some of the work but I must be missing a step. As I'm missing some dependencies.

Are there any instructions as as to how to compile/run the Sample `BookStore` (not modular)?

Thanks

PS -  _I have had this running successfully in the last few days but I think there must have been some changes made to the way the projects get their dependcies now._

**Comment by maliming** [comment]
What is the detailed error?

**Comment by 274188A** [comment]
There are too many to list all but they are along the line of (for example):


>Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'VirtualFileSystem' does not exist in the namespace 'Volo.Abp' (are you missing an assembly reference?)	Acme.BookStore.Domain.Shared	C:\Users\274188a\source\repos\abp\samples\BookStore\src\Acme.BookStore.Domain.Shared\BookStoreDomainSharedModule.cs	13	Active

```

**Comment by maliming** [comment]
I will update these examples.

**Comment by 274188A** [comment]
If we say look at the project file definition for `Acme.BookStore.Domain` we see this:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
    <ProjectReference Include="..\..\..\..\modules\identity\src\Volo.Abp.Identity.Domain\Volo.Abp.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\modules\identity\src\Volo.Abp.PermissionManagement.Domain.Identity\Volo.Abp.PermissionManagement.Domain.Identity.csproj" />
    <ProjectReference Include="..\..\..\..\modules\identityserver\src\Volo.Abp.IdentityServer.Domain\Volo.Abp.IdentityServer.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\modules\identityserver\src\Volo.Abp.PermissionManagement.Domain.IdentityServer\Volo.Abp.PermissionManagement.Domain.IdentityServer.csproj" />
    <ProjectReference Include="..\..\..\..\modules\background-jobs\src\Volo.Abp.BackgroundJobs.Domain\Volo.Abp.BackgroundJobs.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\modules\audit-logging\src\Volo.Abp.AuditLogging.Domain\Volo.Abp.AuditLogging.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\modules\tenant-management\src\Volo.Abp.TenantManagement.Domain\Volo.Abp.TenantManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\modules\feature-management\src\Volo.Abp.FeatureManagement.Domain\Volo.Abp.FeatureManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\modules\setting-management\src\Volo.Abp.SettingManagement.Domain\Volo.Abp.SettingManagement.Domain.csproj" />
  </ItemGroup>
```

**Comment by 274188A** [comment]
I see this is Closed now.  

Can I confirm that we should be able to run the sample `BookStore` now?

Despite  doing a fresh clone of the **entire** repo, and running the `build-all.ps1` script - I am still unable to compile the sample `BookStore`.

**Comment by maliming** [comment]
What is the error you are now experiencing?

**Comment by 274188A** [comment]
![image](https://user-images.githubusercontent.com/40014477/67548907-a714db00-f735-11e9-8b4b-53ae12bc0c88.png)

**Comment by maliming** [comment]
You can try build the BookStore.
```
dotnet build
```

**Comment by 274188A** [comment]
Here's what for example the `Acme.BookStore.Domain project used to look like a few version back:
![image](https://user-images.githubusercontent.com/40014477/67549075-fb1fbf80-f735-11e9-9a24-b4d19238d4ca.png)


and here is what it looks like now:
![image](https://user-images.githubusercontent.com/40014477/67549114-14c10700-f736-11e9-8b7f-68143a1bce05.png)

quire different

**Comment by 274188A** [comment]
ok, will try `dotnet build`

**Comment by 274188A** [comment]
It worked but would love to know why this works BUTVS2019 rebuild all on the sln does not...
