### ISSUE TITLE
Update BookStore Tutorial for Blazor UI (according to the new hosting logic changes for blazor web app)

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#20138]
https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=Blazor&DB=EF

Revise the docs and change the related projects. For example, the code should be written under the `*.Blazor.Client` project. Also, see https://github.com/volosoft/volo/issues/17990

**Comment by abooraja** [comment]
Why is it divided into two parts in the new version of the Blazer project?
