### ISSUE TITLE
Error Loading Blazor WebApp Project in WebAssembly Mode: 'MD5' is not a known hash algorithm

### ISSUE THREAD

**Issue by charleszh-dev** [abpframework/abp#20164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I encountered an error when attempting to load a Blazor WebApp project in WebAssembly mode. The error message states that 'MD5' is not a known hash algorithm.

### Reproduction Steps

1. Use the Blazor WebApp startup template to create a new project.
2. In the Blazor WebApp Tiered Client, add the ClientCredentials grant type to grantType.
3. Update the appsettings configuration files in both the *.Blazor.Client and *.Blazor projects.
Add the following JSON content to configure IdentityClients:
``` json
"IdentityClients": {
    "Default": {
        "GrantType": "client_credentials",
        "ClientId": "TransAI_BlazorWebAppTiered",
        "ClientSecret": "1q2w3e*",
        "Authority": "",
        "Scope": ""
    }
}
```
4. Run the .Blazor Project:
    - Start the *.Blazor project.
    - Once the page and wasm files are fully loaded, refresh the page.
    - Open the browser console (F12) and observe the error message.

### Expected behavior

The Blazor WebApp should load without any issues in WebAssembly mode.

### Actual behavior

The application fails to load, displaying an error message indicating that 'MD5' is not a known hash algorithm.

### Version

8.2.0

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

### Other information

The issue might be caused by the `.ToMD5()` extension method being called in the `IdentityModelAuthenticationService` when calculating the cache keys in the `CalculateTokenCacheKey` and `CalculateDiscoveryDocumentCacheKey` methods.

See also [System.Security.Cryptography APIs not supported on Blazor WebAssembly](https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly)

**Comment by charleszh-dev** [comment]
Maybe related: #7559

**Comment by maliming** [comment]
Yes, we can consider changing the hash method.

**Comment by charleszh-dev** [comment]
Thank you for considering changing the hash method. I appreciate your prompt response.

**Comment by maliming** [comment]
wasm support sha256(https://github.com/dotnet/runtime/issues/73858), I have changed the md5 to sha256
