### ISSUE TITLE
integrate elasticsearch?

### ISSUE THREAD

**Issue by mingyangzhu** [abpframework/abp#2016]
hi @hikalkan , abp roadmap  is there a plan to  integrate  elasticsearch? i think it`s  great for  full-text search  features.

**Comment by xewn** [comment]
https://github.com/abpframework/abp/issues/1621

**Comment by xewn** [comment]
https://github.com/abpframework/abp/issues/1699

**Comment by hikalkan** [comment]
You can already use elasticsearch in your ABP based application. What type of integration? IRepository implementation?

**Comment by mingyangzhu** [comment]
> You can already use elasticsearch in your ABP based application. What type of integration? IRepository implementation?

hi ,hikalkan. Do you have  about how to use es documentation ?i want to implement  full-text search features (integration es).

Of course, it would be better if abp could provide this feature (like IRepository implementation ).

**Comment by hikalkan** [comment]
>Do you have about how to use es documentation

No, but it should be pretty standard, nothing special to ABP. You can find documentation on the web.

I am not ES expert, so now I can't realize if implementing repositories with ES is feasible and meaningful.
