### ISSUE TITLE
Missing btn-sm class in datatables action button

### ISSUE THREAD

**Issue by maowohl** [abpframework/abp#20160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a datatable is configured with a single action button there is a difference in its size if compared with the dropdown button generated when there are multiple actions.

### Reproduction Steps

Create a regular datatable and configure a column with multiple actions to get the dropdown button with the `btn-sm` class:
```js
...
{
    title: l('Actions'),
    rowAction: {
        items:
            [
                {
                    iconClass: 'fa fa-edit',
                    text: l('Action:Edit'),
                    visible: true,
                    action: function (data) { }
                },
                {
                    iconClass: 'fa fa-trash',
                    text: l('Action:Remove'),
                    visible: true,
                    action: function (data) { }
                }
            ]
    },
},
...
```
![image](https://github.com/abpframework/abp/assets/10617405/0a293471-ae15-4f2b-8f7f-4ac0a7907265)

Create a regular datatable and configure a column with a single action to get the button without the `btn-sm` class:
```js
...
{
    title: l('Actions'),
    rowAction: {
        items:
            [
                {
                    iconClass: 'fa fa-trash',
                    text: l('Action:Remove'),
                    visible: true,
                    action: function (data) { }
                }
            ]
    },
},
...
```
![image](https://github.com/abpframework/abp/assets/10617405/fcf27e53-f569-4f83-b159-cd3eaff966ab)

### Version

8.2.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

I did a little digging on the git repository and found these lines that might be related with the missing `btn-sm` class:

single button generation?
https://github.com/abpframework/abp/blob/ea5b1bc0a6c110aec699918b9a3415a13051a343/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L93

dropdown button generation?
https://github.com/abpframework/abp/blob/ea5b1bc0a6c110aec699918b9a3415a13051a343/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L153

**Comment by maliming** [comment]
hi

I have added the `btn-sm` class. You can override `datatables-extensions.js` file to temporary to solve it.

https://github.com/abpframework/abp/pull/20161
