### ISSUE TITLE
Angular - Duplicate Proxy Generation Problem

### ISSUE THREAD

**Issue by sumeyyeKurtulus** [abpframework/abp#20172]
### Description

This issue is expected to resolve the problem reported in this [support question].(https://support.abp.io/QA/Questions/7454/Duplicate-imports-when-generating-proxies) 

![image](https://github.com/abpframework/abp/assets/92928815/c036ed62-bede-45e0-b918-ca5efe4f14d7)
![image](https://github.com/abpframework/abp/assets/92928815/15b500be-085e-4f5f-adec-5105130babae)

### GitHub Issues

This issue might have a dependency here in this closed issue #18956

**Comment by chiefupstart** [comment]
Does this fix require an 8.2 upgrade? I'm on 8.1.4 and, as of yesterday (7/17/24), still getting duplicate imports on proxy generation.

**Comment by sumeyyeKurtulus** [comment]
@chiefupstart Yes, it should require such an upgrade. The next patch will be released as soon as possible, and you can follow [this link](https://github.com/abpframework/abp/releases).

**Comment by scott7106** [comment]
Is there any projected date for an 8.2 patch to include this fix? It is extremely annoying to manually fix the generated proxy files every time we add or change an endpoint in the API.

**Comment by jeff-nelson-78954** [comment]
Bump having the same issue. If there is a better known workaround then to manually fix all these files that would be appreciated. I tried downgrading my cli back to 6.0.2 that was working, and that still will not work for me.
