### ISSUE TITLE
CLI: Only add module project to the *.Blazor.Client project.

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#20171]
Reported at https://support.abp.io/QA/Questions/7457/Issue-with-CMS-Kit-Pro-in-Blazor-Full-Stack-Web-App-UI-in-ABP-Commercial-Suite-82

When we use the `add-module` command to add a module to the blazor application, with the new hosting logic, it should add the related blazor packages to the client project. Therefore, we need check if it's a blazor web app and then add the package to the client project.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/20154
