### ISSUE TITLE
ABP Bundle command not working according to documentation

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#20170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Seems like abp bundle command is not working as it should in a MAUI Blazor project, at least not according to documentation.

Docs:

"bundle
This command generates script and style references for ABP Blazor WebAssembly and MAUI Blazor project and updates the index.html file. It helps developers to manage dependencies required by ABP modules easily. In order bundle command to work, its executing directory or passed --working-directory parameter's directory must contain a Blazor or MAUI Blazor project file(*.csproj)."

Outcome:

`abp bundle --maui-blazor ABP CLI 8.2.0 Unsupported project type. Project type must be Microsoft.NET.Sdk.BlazorWebAssembly. Unsupported project type. Project type must be Microsoft.NET.Sdk.BlazorWebAssembly. Volo.Abp.Cli.Bundling.BundlingException: Unsupported project type. Project type must be Microsoft.NET.Sdk.BlazorWebAssembly. at Volo.Abp.Cli.Bundling.BundlingService.CheckProjectIsSupportedType(String projectFilePath, String projectType) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 333 at Volo.Abp.Cli.Bundling.BundlingService.BundleAsync(String directory, Boolean forceBuild, String projectType) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 50 at Volo.Abp.Cli.Commands.BundleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\BundleCommand.cs:line 47 at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 173 at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 80 Unhandled exception. Volo.Abp.Cli.Bundling.BundlingException: Unsupported project type. Project type must be Microsoft.NET.Sdk.BlazorWebAssembly. at Volo.Abp.Cli.Bundling.BundlingService.CheckProjectIsSupportedType(String projectFilePath, String projectType) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 333 at Volo.Abp.Cli.Bundling.BundlingService.BundleAsync(String directory, Boolean forceBuild, String projectType) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Bundling\BundlingService.cs:line 50 at Volo.Abp.Cli.Commands.BundleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\BundleCommand.cs:line 47 at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 173 at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 80 at Volo.Abp.Cli.Program.Main(String[] args) in D:\ci\Jenkins\workspace\abp-volo-release\abp\framework\src\Volo.Abp.Cli\Volo\Abp\Cli\Program.cs:line 43 at Volo.Abp.Cli.Program.<Main>(String[] args)`

### Reproduction Steps

Run abp bundle on a MAUI Blazor project

### Expected behavior

Should work

### Actual behavior

Does not work calming it isn't an WASM project. 

### Version

8.2

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
Hi, as far as I see from the outcome you shared, you used the following command, right?

```bash
abp bundle --maui-blazor
```

Instead, the command should be as follows:

```bash
abp bundle --project-type maui-blazor
```

Please, try this command in the maui-blazor project directory and let me know if it works as expected.

**Comment by improwise** [comment]
Thanks, must have been really tired when I did that yesterday :) My bad, you are correct. It is even mentioned in the documentation

--project-type or -t: Specifies the project type. Default type is webassembly. Available types:
webassembly
maui-blazor

Perhaps the error message "Unsupported project type. Project type must be Microsoft.NET.Sdk.BlazorWebAssembly." could be improved but I wont blame that for my mistake.
