### ISSUE TITLE
Random exception after switching from IdentityServer to OpenDict

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#20184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is hard to tell exactly, in which moment it happens, so no reproducing steps given. But this seems to be completely inside your code, so maybe it's an error within your logic. Please take a look at the exception stack below and let us know:

> 2024-06-20 14:19:04.849 -05:00 INF () Lock is acquired for TokenCleanupBackgroundWorker
> 
> ﻿[14:19:04 INF] Lock is acquired for TokenCleanupBackgroundWorker
> 
> ﻿2024-06-20 14:19:04.859 -05:00 ERR () An exception was thrown while activating Volo.Abp.OpenIddict.Tokens.TokenCleanupService -> ?:OpenIddict.Abstractions.IOpenIddictTokenManager -> Volo.Abp.OpenIddict.Tokens.AbpTokenManager -> Volo.Abp.OpenIddict.Tokens.AbpOpenIddictTokenCache -> Volo.Abp.OpenIddict.Tokens.AbpOpenIddictTokenStore.Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.OpenIddict.Tokens.TokenCleanupService -> ?:OpenIddict.Abstractions.IOpenIddictTokenManager -> Volo.Abp.OpenIddict.Tokens.AbpTokenManager -> Volo.Abp.OpenIddict.Tokens.AbpOpenIddictTokenCache -> Volo.Abp.OpenIddict.Tokens.AbpOpenIddictTokenStore.
> 
> ﻿ ---> Autofac.Core.DependencyResolutionException: None of the constructors found on type 'Volo.Abp.OpenIddict.Tokens.AbpOpenIddictTokenStore' can be invoked with the available services and parameters:
> 
> ﻿Cannot resolve parameter 'Volo.Abp.OpenIddict.Tokens.IOpenIddictTokenRepository repository' of constructor 'Void .ctor(Volo.Abp.OpenIddict.Tokens.IOpenIddictTokenRepository, Volo.Abp.Uow.IUnitOfWorkManager, Volo.Abp.Guids.IGuidGenerator, Volo.Abp.OpenIddict.Applications.IOpenIddictApplicationRepository, Volo.Abp.OpenIddict.Authorizations.IOpenIddictAuthorizationRepository, Volo.Abp.OpenIddict.AbpOpenIddictIdentifierConverter, Volo.Abp.OpenIddict.IOpenIddictDbConcurrencyExceptionHandler)'.

### Version

8.1.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by alexandis** [comment]
Any estimation to get the reply??

**Comment by realLiangshiwei** [comment]
We have never seen this error.
Please provide full steps or a minimal example

**Comment by alexandis** [comment]
I wish I could... As I mentioned, it happens randomly. Do you have any guesses what might cause this issue considering the provided exception stack? It happens without our participation, probably during token expiration. Really no clue...

**Comment by alexandis** [comment]
At our end, the forementioned exception was reproduced using the following scenario:

1. Being logged in the front-end part (Angular), add some custom page to the browser favorites.
2. Logout.
3. Populate user credentials and click on ‘Login’ button.
4. Open link from step 1 on the second tab of the browser while the first tab is trying to log in.

Probably there's an easier scenario, but at least this one has the steps.

Looking forward for your reply.

**Comment by alexandis** [comment]
Please reply. Or should i create an ABP commercial ticket for this? We need to resolve this.

UPDATE: this takes too long by now. Submitting a commercial ticket...
