### ISSUE TITLE
After change default table prefix, application cannot run.

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#2022]
After change the default table prefix, either run .Project.DbMigrator or the Startup project, both of them failed to start, check the log file, the DbMigrator project with below error:

`[ERR] Connection ID "18230571336156053853", Request ID "8000015e-000a-fd00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name "AbpSettings".
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)`

The startup project with below error:

`[ERR] Invalid object name "AbpBackgroundJobs".
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name "AbpBackgroundJobs".
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction))`

It seems they are looking for default table by the dataSeeder.

**Comment by maliming** [comment]
> After change the default table prefix.

How did you modify the table prefix? Did you re-add the migration and update the database?

Please provide all the steps.

**Comment by viewtance** [comment]
Tried 2 approaches:
1, Use the Initial migration create the database, then change the table prefix, generate a new migration, update the database.
2, Delete the Initial migration which come from the template, configure to change the default table fix, update the database with the first migration.

 All of these done via EF CLI, because the .Project.DbMigrator will throw not find "AbpSettings" exception if you run it to seed data.

**Comment by maliming** [comment]
You need to set the `AbpCommonDbProperties.DbTablePrefix` property for possible projects.
```
XXX.DbMigrator
XXX.DbMigrations(BookStoreMigrationsDbContextFactory)
XXX.Web
```

**Comment by viewtance** [comment]
So many entry points to configure, an ugly design.

**Comment by viewtance** [comment]
@maliming After these action, the .Project.IdentityServer still cannot run, it still try to find the settings from AbpSettings
Below is the error, find in the log:
`[ERR] Connection ID "18302628921604046884", Request ID "80000025-0008-fe00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'AbpSettings'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)`

**Comment by zainvegeta** [comment]
Facing the same problem.Setting the TablePrefix to string.empty to remove Abp causes the same error.

'Invalid object name 'AbpSettings'

**Comment by damien-r** [comment]
Hello Everyone,

I think I found a potential source of the `Invalid object name 'AbpSettings'.`. I found it related to a background worker that was run, I don't know why. I am currently in version 5.1.4.

**Comment by MatkoMilic** [comment]
I have the same issue, Invalid object name 'AbpSettings'

**Comment by thanhdongha** [comment]
same issue, Invalid object name 'AbpSettings'
