### ISSUE TITLE
BusinessException message is not set correctly

### ISSUE THREAD

**Issue by lbianfa** [abpframework/abp#20231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I set a custom message in a custom exception by implementing `BusinessException`, it doesn't display in the API response unless I enable `SendExceptionsDetailsToClients`. However, I do not want to include details in my response.

![image](https://github.com/user-attachments/assets/52bd93f1-8c8d-46a4-8939-563d42e7b9a1)

### Reproduction Steps

1. Create a custom exception, passing a custom message to the base.
![image](https://github.com/user-attachments/assets/49e19360-568f-47f2-b7f3-3ed8a93bec39)

2. Do not enable `SendExceptionsDetailsToClients`.
![image](https://github.com/user-attachments/assets/787580bc-efa4-4e4e-85e1-1e58e50a220e)

3. Throw the exception somewhere.
![image](https://github.com/user-attachments/assets/f0cfae40-057b-403c-95b3-b96b4c20519b)

### Expected behavior

Response with custom message

![image](https://github.com/user-attachments/assets/12357f35-f9dc-4a61-9837-e53925941133)

### Actual behavior

Generic response with correctly set error code but without the custom message.

![image](https://github.com/user-attachments/assets/5462da73-f9ea-4be7-8cab-d93f8d05e691)

### Known Workarounds

Currently, the custom message can only be achieved if `SendExceptionsDetailsToClients` is enabled

### Version

8.2.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

I am working without a user interface or client-side project, as my interest is solely the API.

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Exception-Handling#business-exceptions

> Volo.Qa:010002
> Volo.Qa is the code-namespace here. code-namespace is then will be used while **localizing exception messages**.

Or you can use `UserFriendlyException` https://docs.abp.io/en/abp/latest/Exception-Handling#user-friendly-exception

**Comment by lbianfa** [comment]
@realLiangshiwei 

![image](https://github.com/user-attachments/assets/5c65e4b2-b51c-4d97-b0a5-5a130c359a38)

As I understand it, `UserFriendlyException` is more focused on the client-side without modifying the API responses. However, I need to modify my API responses because I am not working with a client-side or frontend in the project.

In the case that I did use a frontend, the bug would still exist, and `UserFriendlyException` would be another workaround besides the previously mentioned `SendExceptionsDetailsToClients`.

**Comment by realLiangshiwei** [comment]
This is by design; `BusinessException` uses code to localize messages

**Comment by lbianfa** [comment]
Aah Ok, thank you very much.
