### ISSUE TITLE
Steps required to add custom property to AppUser

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#2023]
So I have added an additional property to `AppUser`:

`public virtual  Guid? OriginId { get; set; }`

I have add the migrations and synched the db schema successfully.

However I think I am missing a mappings step...
**Question**: Do I define a mapping expression somewhere to pick up my new property?
If so where should this be defined? In the imported identity module?

**Comment by maliming** [comment]
Have you seen the explanation in the template file?

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Users/AppUser.cs#L7

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContext.cs#L38

**Comment by 274188A** [comment]
Yes - seen that but when I run the app I get a mapping exception - missing map for my new property

**Comment by maliming** [comment]
This is very strange, can you provide the steps to reproduce the problem?

**Comment by 274188A** [comment]
step 1: a the following property to `namespace Acme.BookStore.Users.AppUser` 

`public virtual  Guid? OriginId { get; set; }`

In `PersonalSettingsInfoModel` add the following:

```
[StringLength(50)]
[Display(Name = "DisplayName:OriginId")]
public string OriginId { get; set; }

```



In `BookStoreDbContextModelCreatingExtensions` add: 

 ```
public static void ConfigureCustomUserProperties<TUser>(this EntityTypeBuilder<TUser> b)
	where TUser: class, IUser
{
	b.Property<Guid?>(nameof(AppUser.OriginId)).IsRequired(false);
}
```


step 2: run code first migrations

**Comment by maliming** [comment]
> In PersonalSettingsInfoModel add the following:
```
[StringLength(50)]
[Display(Name = "DisplayName:OriginId")]
public string OriginId { get; set; }
```

`PersonalSettingsInfoModel` is the class of the `account` module. How do you add new property?

**Comment by 274188A** [comment]
I see - I should not have touched that. I added it by editing the module itself

**Comment by 274188A** [comment]
I edited the Manage.cshtml file of that module

**Comment by 274188A** [comment]
if i'm going down the wrong track happy to receive feedback...

**Comment by maliming** [comment]
You should not modify the source code of the module. You can override the components in the module in some cases.

**Comment by 274188A** [comment]
So are we not allowed to add a new property to AppUser and have it editable in the UI?

**Comment by ismcagdas** [comment]
@274188A you are but it is not very easy at the moment. We are working on extensibility and will offer a solution for such cases.

**Comment by 274188A** [comment]
I understand - thanks for taking the time to look at my question
