### ISSUE TITLE
GetContainerBuilder can't get on AbpModule

### ISSUE THREAD

**Issue by JadynWong** [abpframework/abp#2025]
```c#
internal static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseAutofac()
                .UseSerilog();
```
In .net core 3.0, thanks to Microsoft's tweaking the way ServiceProvider is done, it is now must to use `UseServiceProviderFactory`. Abp provides the IHostBuilder extension method `UseAutofac` But  in the current order of templates, I can't use `GetContainerBuilder` to get autofac ContainerBuilder instances in AbpModule.
`Could not find ContainerBuilder. Be sure that you have called UseAutofac method before!`

Now `UseAutofac()` is after `ConfigureWebHostDefaults()`，the `ContainerBuilder` is not inject  IOC Container on create AbpModule.

I move `UseAutofac` to ahead `ConfigureWebHostDefaults`. It will create normally.
```c#
internal static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseAutofac()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseSerilog();
```

**Comment by maliming** [comment]
Related: https://github.com/abpframework/abp/issues/391#issuecomment-545242848

@hikalkan What do you think?
