### ISSUE TITLE
Prevent user from getting access to permission which is accessible in the user's assigned role.

### ISSUE THREAD

**Issue by ali-mustafa-98** [abpframework/abp#20250]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

If I have a role "Customer" assigned to the user "user1" and it has many permissions assigned to it, how can I prevent "user1" from getting access to permission "p1," which is accessible from the "Customer" role, while keeping all other permissions assigned to the "Customer" role still accessible by "user1"?
I have tried doing this by using `IPermissionManager` like this:
`await permissionManager.SetForUserAsync(userId, p1, false).`
However, this approach did not work, and "user1" still has access to permission "p1."
Then I tried defining a new custom permission management provider as stated in the "Abp framework tutorial => Permission Management Module,",
![image](https://github.com/user-attachments/assets/264860c8-82a2-49c9-a0e4-20974a701d82)
But this also did not work. I was not able to prohibit the user from getting access to any permission that is accessible by the user's role.

### Version

8.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
This is not a bug. Users should be able to access all permissions of the role.

If you need you can override the `PermissionChecker` to deny certain permissions
https://github.com/abpframework/abp/blob/c9f59bc75d41d4b9f7865bf491eb470d4d496d80/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/Permissions/PermissionChecker.cs#L44

**Comment by ali-mustafa-98** [comment]
> This is not a bug. Users should be able to access all permissions of the role.
> 
> If you need you can override the `PermissionChecker` to deny certain permissions
> 
> https://github.com/abpframework/abp/blob/c9f59bc75d41d4b9f7865bf491eb470d4d496d80/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/Permissions/PermissionChecker.cs#L44

The documentation states that the Identity Module defines two types of permission management providers:

`UserPermissionManagementProvider:` Manages user-based permissions.
`RolePermissionManagementProvider:` Manages role-based permissions.
The order of the providers is important. Providers are executed in the reverse order.
 If `RolePermissionManagementProvider` gets executed first, how can I change the order of execution? More importantly, if I had the `UserPermissionManagementProvider` as the first provider to be executed, will this allow me to make some permissions prohibited from being accessed by the user while being accessible by the user's role?

**Comment by realLiangshiwei** [comment]
Arrange in order of adding to options

https://github.com/abpframework/abp/blob/8e72c106e662a503e359319aae32fd23ab45a713/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/AbpAuthorizationModule.cs#L40-L44

You can add your `PermissionValueProvider` to the top

```csharp
Configure<AbpPermissionOptions>(options =>
{
  options.ValueProviders.Insert(0, new YourPermissionValueProvider());
});
```

There is the document:

https://docs.abp.io/en/abp/latest/Authorization#advanced-topics

**Comment by RamySobhieh** [comment]
Here i am facing the same issue. Problem is i have a user that is in a Role admin and admin has delete permissions. For this specific user, I want to be able to revoke the delete permission without removing him from the role. Tried using SetForUserAsync() for permission with granted false, however since the AbpPermissionGrants table only has the granted permission, true and false for is granted is more like add or delete instead of a flag in the db. How can i be implementing my logic?
