### ISSUE TITLE
Entity Extensions (EF Core) in OrganizationUnit Entity cant delete in ver8.x

### ISSUE THREAD

**Issue by Vktun** [abpframework/abp#20277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

hi when i use entity extension in 'AbpOrganizationUnit' extension columns like 'DisplayCode'
![image](https://github.com/user-attachments/assets/3b14c32a-dbec-4e88-a183-919a800f3da4)

 OrganizationUnitManager.CreateAsync(OK)
 OrganizationUnitManager.UpdateAsync(OK)
 OrganizationUnitManager.DeleteAsync(failed)
All the OrganizationUnit data has values
![image](https://github.com/user-attachments/assets/aed50104-bcc4-42f8-83ad-0f34d3889aa9)

the error like 
![image](https://github.com/user-attachments/assets/88bec872-1c8a-4925-a1ce-72933e5124e1)

when i used ver8.x it will be occur   

### Regression?

abp new -t module 

### Version

8.x

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Please try to `EnableSensitiveDataLogging` to see the SQL variable values.

**Comment by Vktun** [comment]
thank you for response ! by the way I cant find values , I used template for module
![image](https://github.com/user-attachments/assets/6edf78c7-6870-452b-ac74-f97d5908e192)
![image](https://github.com/user-attachments/assets/df4a6043-8983-4daa-aa5e-0334d7028256)

**Comment by Vktun** [comment]
thank you for response ! in my opinion,   when  I just use default OrganizationUnitManager do soft delete  , update command should not have extension properties. 
![image](https://github.com/user-attachments/assets/fbe37061-3bf9-4c6d-97f7-6f2a948ce2a8)

**Comment by maliming** [comment]
Can you try your code in a new template project(SQL server)?

**Comment by Vktun** [comment]
I used new template ver8.2.0 to for same mysql db ,I worked ,but I cant find other different libs. new template generate sql is ideal.
but my project is from v7.x to ver 8.x . I figure it ,this problem is the layers  domain ,domain.shared ,application.contracts TargetFrameworks use netstandard2.1;.net8.0 will be occur ,if I change  to net8.0 only will be right, solve this problem. 
![image](https://github.com/user-attachments/assets/cb44a871-a5ba-4306-b2be-4597296997df)

**Comment by maliming** [comment]
> ,if I change to net8.0 only will be right, solve this problem.

This sounds like a Database provider problem.

**Comment by Pantex9** [comment]
Hi, do you know if this issue is still open?

**Comment by cdlian** [comment]
I may encounter the same issue when using the latest version (8.3.0-rc.3). In my example code, there are two extended properties: `DbProperty` is mapped to a database field through EFCore and cannot be NULL, while `NoDbProperty` is stored in ExtraProperties. When I delete an entity, the generated SQL sets DbProperty to NULL.

<img width="1276" alt="iShot_2024-09-02_10 58 25" src="https://github.com/user-attachments/assets/2b6892b3-54e7-43eb-a710-833e4f6706a5">
<img width="1879" alt="iShot_2024-09-02_11 00 52" src="https://github.com/user-attachments/assets/f24ec8fe-e03b-42d4-90be-e8b6aef35776">


[Sample Code](https://github.com/cdlian/abp-issue-20277)
