### ISSUE TITLE
Mvc: DateRangePicker Improvements

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#20287]
If time selection is also active in date picker, auto apply is disabled. If auto apply is active even though time selection is also active, it should not be disabled. Find a workable solution for this.

**Comment by hikalkan** [comment]
@realLiangshiwei ask to @salihozkara

**Comment by realLiangshiwei** [comment]
@salihozkara 
Can you explain it? I don't quite understand it well

**Comment by salihozkara** [comment]
> @salihozkara Can you explain it? I don't quite understand it well

If time selection and auto apply enable in datepicker, it is mandatory to click apply button. Instead, if the time selection and auto apply enable in the datepicker, the time should be set to 00.00 when the date is selected. If the time is to be changed, the user can open the datepicker again. In addition, if the user clicks somewhere outside without canceling, maybe we can set the last selected date.
