### ISSUE TITLE
TableColumn is recommended to add a width attribute？

### ISSUE THREAD

**Issue by shuangbaojun** [abpframework/abp#20285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

old:
![image](https://github.com/user-attachments/assets/7996fb92-65ae-4813-aa6f-d749cb2d6e7d)
old:
![image](https://github.com/user-attachments/assets/9a557123-c780-4351-9512-d4d6681fce1c)

It is recommended that tablecolum can support extensible

**Comment by shuangbaojun** [comment]
@maliming I wonder if you could think about it

**Comment by maliming** [comment]
ok, We will check it in the next version.
