### ISSUE TITLE
application-configuration api timeout?

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#2030]
version: **1.0.2**
issue:  
api like `application-configuration` `ApplicationConfigurationScript` cannot used in browser.
but can use in swagger ui although very slow.
reappear:
Download the template to run directly

**Comment by maliming** [comment]
Unable to reproduce the problem, please check your local environment.

![image](https://user-images.githubusercontent.com/6908465/67729765-5222de80-fa2d-11e9-9072-e7f111d3aef8.png)
