### ISSUE TITLE
Identity Module — Fix too long module area

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#20319]
In the current design, the module names on the left side go too long, and it is hard to find the related module with an eye check.
![image](https://github.com/user-attachments/assets/b5eb6cdd-b3a1-43ff-9ecf-08f614ea5f88)

---

My suggestion is to join the module names into a dropdown. 
Or any other user-friendly solution is accepted.

![image](https://github.com/user-attachments/assets/1330e88c-f4d9-432a-b33e-7201d16c4778)

**Comment by hikalkan** [comment]
My suggestion to add a filter/search box on top of the module names and filter them while typing. Same also can be applied to the permission tree, and maybe a global search can be done (searches in all tabs).

**Comment by maliming** [comment]
Add a search box and scroll bar to the group/permission list.

![image](https://github.com/user-attachments/assets/b673ec5f-4c84-472d-8acd-83cb13a1e809)

**Comment by NecatiMeral** [comment]
^- this plus consider to increase the left bar width.

**Comment by ebicoglu** [comment]
also we should add a filter box to find the related permission

**Comment by ebicoglu** [comment]
after @EngincanV finishes, we'll open Angular, Blazor UI issues

**Comment by ebicoglu** [comment]
the new design 
![image](https://github.com/user-attachments/assets/c40cfbd1-b888-4277-bd54-545a836c12f8)

**Comment by hikalkan** [comment]
Please remembe to open issues for all UIs.

**Comment by EngincanV** [comment]
Is this issue still valid with the new design?

![image](https://github.com/user-attachments/assets/047bc4bb-d023-4245-aa38-ce1075881ba7)

---

It's implemented for all UIs:

* MVC -> https://github.com/abpframework/abp/pull/20893
* Angular -> https://github.com/abpframework/abp/pull/21184
* Blazor UI -> https://github.com/abpframework/abp/pull/21122
