### ISSUE TITLE
Why authorization many times？

### ISSUE THREAD

**Issue by vincywindy** [abpframework/abp#2031]
I run IdentityServer4 and host+angular,when the call the host api,the console shows the infomations
![image](https://user-images.githubusercontent.com/30209724/67731340-c449f200-fa32-11e9-9d94-7020a33e4774.png)
I only refresh the user page,it takes 2.5s to finish,this is too slowly

**Comment by maliming** [comment]
Steps needed to reproduce the problem.

**Comment by vincywindy** [comment]
> Steps needed to reproduce the problem.

1.Download the temple from abp.io
![image](https://user-images.githubusercontent.com/30209724/67732853-a7fc8400-fa37-11e9-960f-72f224451b63.png)

2.run migrator
3.add Serilog.Sinks.Console package to test.IdentityServer and test.HttpApi.Host and config their program.cs
![image](https://user-images.githubusercontent.com/30209724/67733007-06c1fd80-fa38-11e9-8149-93b3ea288a9d.png)
4.run test.IdentityServer and login ,the IdentityServer's console will shows the Authorization message 11 times
![image](https://user-images.githubusercontent.com/30209724/67733069-3c66e680-fa38-11e9-9403-88e62a6e6cb9.png)
5.do not close the test.IdentityServer and run test.HttpApi.Host,and start angular,login to angular,when I refresh page,the test.HttpApi.Host's console shows  the Authorization message 17 times
![image](https://user-images.githubusercontent.com/30209724/67733177-84860900-fa38-11e9-97eb-882702dc611d.png)

**Comment by maliming** [comment]
These are just some of the normal logs. Will optimize & cache.

https://github.com/abpframework/abp/blob/ae1ac4849a1f107fdf22b9b341c5d4adf4b4a462/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationAppService.cs#L85
