### ISSUE TITLE
abp.io cannot register, return 500

### ISSUE THREAD

**Issue by halida** [abpframework/abp#2035]
Hi, I'm trying to register, got 500 error, my email: linjunhalida@gmail.com, please check it.

**Comment by maliming** [comment]
We will fix it, thanks for feedback.

**Comment by ismcagdas** [comment]
Seems like it is related to sending emails and MailKit.

**Comment by hikalkan** [comment]
Is that already fixed?

**Comment by ismcagdas** [comment]
I just checked and problem still exists.

**Comment by leo4444** [comment]
the problem still persist if you put a weak password. I tried with "something123" and I received 500 error code but when i tried "Something@123" I could register. 

I'm sorry, but my english isn't good

**Comment by maliming** [comment]
@leo4444 We will fix it, thanks for your feedback.
