### ISSUE TITLE
use cli to create module without host folder

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#20365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i use command `abp new-module Acme.BookStore -t module:ddd --no-ui` to create a module,
I'v got only src and test folder.So I have no startup project.
where is host folder?

### Reproduction Steps

run command abp new-module Acme.BookStore -t module:ddd --no-ui

### Expected behavior

got src test host 3 folders.

### Actual behavior

got src test 2 folders.

### Version

cli 0.7.4 beta

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by ahmetfarukulu** [comment]
We've created an issue and addressed the backlog. The fix will be included in the upcoming versions. As a workaround, you can create an app project and add the modules you've created. Then, import the module into the application template. For an example, check out [ABP Community Talks 2024.4 example](https://youtu.be/uYTbGLtxdUE?t=1843)

**Comment by gdlcf88** [comment]
Developing with modules' demo hosts can decouple us from infrastructure dependencies, greatly improving efficiency. Up until today, demo hosts have still not been included in the module template. Please prioritize this requirement. Thanks.
