### ISSUE TITLE
Swashbuckle has wrong framework dependency

### ISSUE THREAD

**Issue by MaiReo** [abpframework/abp#2036]
![image](https://user-images.githubusercontent.com/11777709/67820212-4d286280-faf3-11e9-9de8-52749e0f50ba.png)

I want to know why you decided to use Swashbuckle.AspNetCore.
It has wrong deps aslo at past, e.g. JsonFormatter 1.0.0 
thank you

**Comment by maliming** [comment]
What impact does this have on your application?

Maybe you should ask [Swashbuckle.AspNetCore ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore)

**Comment by MaiReo** [comment]
@maliming 
There is no issue what I found yet.

**Comment by hikalkan** [comment]
>I want to know why you decided to use Swashbuckle.AspNetCore.

What do you suggest?
