### ISSUE TITLE
abp cli generate angular proxy less some models

### ISSUE THREAD

**Issue by wxyer** [abpframework/abp#20377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

use cmd ,abp generate-proxy -t ng ,generate proxy successfully,
but identity module less IdentityRoleDto and IdentityUserDto

### Version

8.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by Shtong** [comment]
We also encoutered this issue after upgrading to 8.2.1.

As an example, in the proxy's `models.ts` file, before the upgrade, imports were : 
```ts
import type { UserType } from './user-type.enum';
import type { PagedAndSortedResultRequestDto } from '@abp/ng.core';
import type { IdentityUserDto } from '../volo/abp/identity/models';
import type { CompanyDto } from '../companies/models';
```

After the upgrade, (and after running `abp generate-proxy` again), they are :
```ts
import type { UserType } from './user-type.enum';
import type { PagedAndSortedResultRequestDto } from '@abp/ng.core';
import type { IdentityUserDto } from '@volo/abp.ng.identity/proxy';
import type { CompanyDto } from '../companies/models';
```

This new version does not build, as the package `@volo/abp.ng.identity/proxy` does not exist.

This can be easily reproduced by creating a new solution using the Angular template, and creating a DTO in the backend that inherits `IdentityUserDto`

**Comment by masum-ulu** [comment]
Duplicated of #20680
