### ISSUE TITLE
Abp Cli does not create a new solution with the preview version

### ISSUE THREAD

**Issue by RobertoFiocchiMCSI** [abpframework/abp#20385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If i use the command:

abp new Acme.BookStore -u blazor -m none --preview --theme leptonx -csf

The solution created is version 8.2.1 (stable) instead of 8.3.rc1 (preview)

### Reproduction Steps

abp new Acme.BookStore -u blazor -m none --preview --theme leptonx -csf

### Expected behavior

A solution with abp version 8.3.rc1 (preview)

### Actual behavior

A solution with abp version 8.2.1 (stable)

### Regression?

Yes

### Known Workarounds

No

### Version

ABP CLI 0.7.4 (Beta)

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
https://github.com/abpframework/abp/issues/20384#issuecomment-2264759815

---

Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Comment by RobertoFiocchiMCSI** [comment]
@berkansasmaz Why did you remove this feature?

P.s. How can I reopen this ticket?

**Comment by enisn** [comment]
> @berkansasmaz Why did you remove this feature?

Hi @RobertoFiocchiMCSI , we planned a development in our internal issue tracker

**Comment by RobertoFiocchiMCSI** [comment]
Ok, thanks
