### ISSUE TITLE
After one entity update(autosave=true), another entity removes foreign keys without triggering an event

### ISSUE THREAD

**Issue by zhangzw218** [abpframework/abp#20384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```

    [Fact]
    public async Task Should_Trigger_Domain_Events_For_Aggregate_Root_OneToOne_Null_Changes_Tests()
    {
        _loadEntityWithDetails = true;

        var entityId = Guid.NewGuid();

        await AppEntityWithNavigationsRepository.InsertAsync(new AppEntityWithNavigations(entityId, "TestEntity")
        {
            OneToOne = new AppEntityWithNavigationChildOneToOne
            {
                ChildName = "ChildName1"
            }
        });
        var productId = Guid.NewGuid();
        await ProductRepository.InsertAsync(new Product(productId,"Tem",0));

        var entityUpdatedEventTriggered = false;

        LocalEventBus.Subscribe<EntityUpdatedEventData<AppEntityWithNavigations>>(data =>
        {
            entityUpdatedEventTriggered = !entityUpdatedEventTriggered;
            return Task.CompletedTask;
        });

        using (var scope = ServiceProvider.CreateScope())
        {
            var uowManager = scope.ServiceProvider.GetRequiredService<IUnitOfWorkManager>();
            using (var uow = uowManager.Begin())
            {
                var entity2 = await ProductRepository.GetAsync(productId);
                // await ProductRepository.DeleteAsync(entity2, true); //If the Product is deleted before the AppEntityWithNavigations query, the unit test works
                var entity = await (await AppEntityWithNavigationsRepository.GetQueryableAsync())
                    .Where(s=>s.Id ==entityId)
                    .Include(s=>s.OneToOne)
                    .SingleOrDefaultAsync();
                // await ProductRepository.DeleteAsync(entity2); //If you change autoSave to false, the unit test works
                await ProductRepository.DeleteAsync(entity2, true); //Only here will the unit test fail
                entity.OneToOne = null;

                await AppEntityWithNavigationsRepository.UpdateAsync(entity);

                await uow.CompleteAsync();
            }
        }

        entityUpdatedEventTriggered.ShouldBeTrue();
    }
```

Not sure if it has anything to do with this, I just saw that there was an entity change event, but it was abandoned because there was a foreign key index change.
https://github.com/abpframework/abp/pull/19523#issue-2241231007

### Regression?

I upgraded from 7.2.2 to 8.0.6, which was normal before the upgrade.

### Version

8.0.6

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
> I upgraded from 7.2.2 to 8.0.6, which was normal before the upgrade.

Can you try your test code in the new 8.3 template project?

https://github.com/abpframework/abp/releases/tag/8.3.0-rc.1

**Comment by RobertoFiocchiMCSI** [comment]
@maliming How can I create a new solution wiuth preview version of ABP with abp studio ?

**Comment by zhangzw218** [comment]
> > I upgraded from 7.2.2 to 8.0.6, which was normal before the upgrade.
> 
> Can you try your test code in the new 8.3 template project?
> 
> https://github.com/abpframework/abp/releases/tag/8.3.0-rc.1

I tried it. Same problem
https://github.com/zhangzw218/abp/commit/4c0f0a4093655af725a45ae5cc45acd696927a0c

**Comment by maliming** [comment]
> @maliming How can I create a new solution wiuth preview version of ABP with abp studio ?

https://abp.io/docs/latest/release-info/previews#new-solutions

**Comment by RobertoFiocchiMCSI** [comment]
Ah! Creating new solutions with the preview version is not supported. All new solutions must be created with the stable version.

But with old cli it was possible and it also seems possible from the get started page on abp web site
I will open a ticket for it.

Sorry for OT
Thanks

**Comment by berkansasmaz** [comment]
> Ah! Creating new solutions with the preview version is not supported. All new solutions must be created with the stable version.
> 
> But with old cli it was possible and it also seems possible from the get started page on abp web site I will open a ticket for it.
> 
> Sorry for OT Thanks

Hello @RobertoFiocchiMCSI, thank you for letting us know about this situation. We will remove it from the website as soon as possible. Also, since this feature is in high demand, we may implement it in the new template system in the future.

**Comment by maliming** [comment]
hi @zhangzw218 

Please test https://github.com/abpframework/abp/pull/20396 , I think it will solve your problem.
