### ISSUE TITLE
Abp Cli (old) and Abp Studio Cli (new) generate different code

### ISSUE THREAD

**Issue by RobertoFiocchiMCSI** [abpframework/abp#20388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created a new solution using abp cli 8.2.1 and then I installed abp studio and created a new solution always abp 8.2.1
Comparing the two generated solutions I noticed that they are different, obviously excluding the files that abp studio added for its configurations.
Why?

### Reproduction Steps

1) dotnet tool install -g Volo.Abp.Cli

2) abp new Acme.BookStore -u blazor -m none --theme leptonx -csf

3) ren Acme.BookStore Acme.BookStore_8_2_1_OldCli

4) Delete Database ->  Server=(LocalDb)\\MSSQLLocalDB;Database=BookStore 

5) dotnet tool uninstall -g Volo.Abp.Cli

6) dotnet tool install -g Volo.Abp.Studio.Cli

7) abp new Acme.BookStore -u blazor -m none --theme leptonx -csf

Compare the 2 solution/directory : Acme.BookStore_8_2_1_OldCli -> Acme.BookStore

### Expected behavior

The files .razor , .cs and .csproj should be the same

### Actual behavior

The solution created with new cli have the modules Chat and File Management installed

_Acme.BookStore.Blazor.Client\Components\Layout_
In the new solution (NewCli) removed MainFooterComponent.razor and added LeptonXFooter.razor

_BookStoreMenuContributor.cs_
in the new solution (NewCli) removed the code:
```
//Administration->Saas
administration.SetSubItemOrder(SaasHostMenus.GroupName, 2);
```

And
```
 context.Menu.AddItem(new ApplicationMenuItem(
            "Account.Sessions", 
            accountStringLocalizer["Sessions"], 
            url: $"{authServerUrl.EnsureEndsWith('/')}Account/Sessions", 
            icon: "fa fa-clock", 
            order: 1002,
            target: "_blank").RequireAuthenticated());
```

_HostDashboard.razor.cs  e TenantDashboard.razor.cs_ 
In the new solution (New cli) don't have
```
protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await SetBreadcrumbItemsAsync();
            await InvokeAsync(StateHasChanged);
        }
    } 
``` 
_BookStoreBlazorClientModule.cs_ 
In the new solution (New cli) 
Added
```
    private void ConfigureLocalization()
    {
        Configure<AbpLocalizationOptions>(options =>
        {
            options.Resources
                .Get<BookStoreResource>()
                .AddBaseTypes(typeof(AbpUiResource));
        });
    }
```

And in fucntion ConfigureAuthentication removed the line
`options.ProviderOptions.DefaultScopes.Add("offline_access");`

_BookStoreBrandingProvider.cs_ is different. in New solution it uses localizer to get application name.  **Why?**

_BookStoreDomainModule.cs_
in New solution added display name 
```
            options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));
            options.Languages.Add(new LanguageInfo("zh-Hant", "zh-Hant", "繁體中文"));
```

_Acme.BookStore.Domain.Shared\Localization\BookStore\_
The new solution is missing many localization labels and the hr.json file

_Acme.BookStore.HttpApi.Host_
In the new solution 
- added Controllers\HomeController.cs
- removed foleder Pages (index.cshtml and others)
- changed files in folder images
- changed global-styles.css

_Acme.BookStore.HttpApi.Host.csproj_
 In the new solution 
Use version 7 instead of 8 for  **(!!! THIS IS IMPORTANT FOR US !!!)**
 ```
   <PackageReference Include="AspNetCore.HealthChecks.UI" Version="7.0.2" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="7.1.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="7.0.0" />
```
Added  (**Why EfCore?**)
```
 <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.4" />
 <PackageReference Include="Volo.Abp.Studio.Client.AspNetCore" Version="0.7.4" />
```
Changed version of LeptonX from 3.2.0 to 3.2.1
   ` <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX" Version="3.2.1" />`
Changed the name of file .pfx -> from openiddict.pfx to authserver.pfx    **(!!! THIS IS IMPORTANT FOR US !!!)**

_appsettings.json_
In the new solution
added uri in CorsOrigins e RedirectAllowedUrls (I think to support abp studio)

_Program.cs_ 
In the new solution changed and added
.WriteTo.Async(c => c.AbpStudio(services));          **How used it on production system?** 

_BookStoreEntityFrameworkCoreTestModule.cs_
In the new solution removed
```
        Configure<SettingManagementOptions>(options =>
        {
            options.SaveStaticSettingsToDatabase = false;
            options.IsDynamicSettingStoreEnabled = false;
        });
```
Changed AbpUnitTestSqliteConnection to SqliteConnection

_editorconfig_
File added in main directory

### Regression?

Yes

### Known Workarounds

There is no documentation on these changes  and how AbpStudio is integrated into the framework.
Do we need to open ports on firewalls when we are in staging and production?

### Version

ABP CLI 0.7.4 (Beta)

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

It looks like two different repositories/branches were used.
Does the new cli use an old branch?

**Comment by RobertoFiocchiMCSI** [comment]
Is there any news on this?

**Comment by yekalkan** [comment]
We are aware of this and will add missing features to new template.

However, we don't aim it to be line-to-line same with old template.

**Comment by RobertoFiocchiMCSI** [comment]
Thanks for reply @yekalkan, but if Volosoft tell me to switch to AbpStudio I expect that the AbpStudio template is like with AbpCli Legacy and not that there are missing features/patches. 
In addition, if there are any breaking changes they should be written, example:
In the new solution (NewCli) removed MainFooterComponent.razor and added LeptonXFooter.razor

Please to update template and documentation.
Thanks
