### ISSUE TITLE
Hide parent menu if no permission

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#20394]
**App:** Angular/Mongo (public website)
**Studio Version:** `0.7.4`
**Abp version:** `8.2.1`

![image](https://github.com/user-attachments/assets/f0fcb9ac-44e2-42c7-8619-5255d24b0cf2)

Docs: https://new.abp.io/docs/latest/tutorials/book-store/index

**Comment by masum-ulu** [comment]
Ref https://github.com/abpframework/abp/pull/20246
