### ISSUE TITLE
The get methods is repeated when generating typescript file with nSwagStudio

### ISSUE THREAD

**Issue by w21976169** [abpframework/abp#2040]
### typescript code:
```
    /**
     * @return Success
     */
    apiIdentityUsersGet(id: string): Observable<IdentityUserDto> {}

    /**
     * @param filter (optional) 
     * @param sorting (optional) 
     * @param skipCount (optional) 
     * @param maxResultCount (optional) 
     * @return Success
     */
    apiIdentityUsersGet(filter: string | undefined, sorting: string | undefined, skipCount: number | undefined, maxResultCount: number | undefined): Observable<IdentityUserDtoPagedResultDto> { }

```

### error：
![SharedScreenshot](https://user-images.githubusercontent.com/11971234/67832306-35b19f80-fb1c-11e9-96f5-b0f4d30e014a.jpg)

**Comment by maliming** [comment]
More explanation?

**Comment by w21976169** [comment]
The getById method and the getAllPage method has a same name, and the typescript file cannot be compiled

**Comment by w21976169** [comment]
@maliming 

我用 nSwagStudio 生成 Typescript，
swagger.json 来自BackendAdminApp.Host 项目，
**GET ​/api​/identity​/users​/{id}**
**GET ​/api​/identity​/users**
这两个 api 生成的 方法名字相同

**Comment by maliming** [comment]
You should ask nSwagStudio, this has nothing to do with abp, abp uses the standard http.
