### ISSUE TITLE
angular UI calls api twice when creating tenant

### ISSUE THREAD

**Issue by MaiReo** [abpframework/abp#2042]
![image](https://user-images.githubusercontent.com/11777709/67837172-66e49c80-fb29-11e9-9a7a-eb4c312dd17e.png)

It makes twice POST requests  to the CreateTenant endpoint 

package version : abp/ng.tenant-management@^1.0.2

**Comment by maliming** [comment]
It looks like `save()` is executed twice, @thediaval what do you think?

https://github.com/abpframework/abp/blob/7ebb7a0097e8cc1f84c41078a802c596135e3dcf/npm/ng-packs/packages/tenant-management/src/lib/components/tenants/tenants.component.html#L132

https://github.com/abpframework/abp/blob/7ebb7a0097e8cc1f84c41078a802c596135e3dcf/npm/ng-packs/packages/tenant-management/src/lib/components/tenants/tenants.component.html#L137

**Comment by mehmet-erim** [comment]
Thanks @MaiReo
