### ISSUE TITLE
Cannot create a new Blazor Web app (no cli option)

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#20439]
The option to create a new Blazor Web app has disappeared. Has this been removed?

Thanks, Don

**Comment by realLiangshiwei** [comment]
The new template doesn't support webapp yet.
you can try `abp new BookStore -u blazor-webapp --old`

**Comment by Areyouwell** [comment]
The command "abp new BookStore -u blazor-webapp --old" does not work, a project is created with a Blazor server UI

**Comment by realLiangshiwei** [comment]
it works for me

<img width="935" alt="image" src="https://github.com/user-attachments/assets/ac607f0b-7cca-4068-baca-e94afbad0e6e">

**Comment by Areyouwell** [comment]
No, it doesn't work because it's a Blazor server and not a web app, it used to be like that:

**Comment by Areyouwell** [comment]
It works, thank you
