### ISSUE TITLE
Module Identity: Missing complete logic for 'PasswordRequiresUniqueChars'

### ISSUE THREAD

**Issue by stewinfanter** [abpframework/abp#20449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The setting of the option in "Adminisrtaion > Settings > Identity management > Required unique characters number" does not currently apply. For example, if the setting is set to 2 and an attempt is made to assign a password such as "SSSSSSSSSS", this validation is completely ignored.
The error here lies in the completely forgotten "not" implementation of this validation.
The `validation-utils.ts` in `ng.theme.shared` component does not contain this validation.

### Reproduction Steps

- Path: Adminisrtaion > Settings > Identity management > Required unique characters number
- Action: set to an individual number (I did 2)
- Path: Administration > Identity management > Users
- Action: Set Password
- Action: Insert "SSSSSSSS"

The validation will not trigger on `validatePassword()`

### Expected behavior

It should trigger the setting and validate the input. Also it should show an error if invalid.

### Version

8.2.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by sumeyyeKurtulus** [comment]
Hello @stewinfanter, I have followed the steps that you provided above. However, I could not duplicate the problem as can be seen in the video

[8_8_2024, 1_12_31 PM - Screen - PasswordValidator.webm](https://github.com/user-attachments/assets/e4888581-011b-4f36-93fd-edab97403c0a)

**Comment by stewinfanter** [comment]
Hello @sumeyyeKurtulus, you are totlay right. I was assuming, that the two Requirements on top are also comming from the client  (as function call). I never trought about to remove the 4 other requirements. I could successfully follow all steps and it is all ok. I appologize for the wrong bug report. Thank you for your time.
