### ISSUE TITLE
Blazor Webapp - slow loading problems

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#20445]
**App:** Blazor Webapp and Blazor webapp Tiered - EfCore

- [ ] When the language is changed, the application freezes and the logo disappears.

[Apex_1722944131166.webm](https://github.com/user-attachments/assets/12795b03-6087-4347-97ea-e973e72d0a3a)

- [ ] The logo icon is loaded slowly every time the page is refreshed.

[Apex_1722944417709.webm](https://github.com/user-attachments/assets/2dca08bf-e1df-48c7-b6c2-7888a57ad97e)

**Comment by maliming** [comment]
please share your test project.

liming.ma@volosoft.com

**Comment by enisn** [comment]
Logo disappearance might be solved by https://github.com/volosoft/abp-studio/pull/1515

**Comment by gizemmutukurt** [comment]
https://drive.google.com/file/d/1bOcdTpx2mDPWtyeGkZkpXhkeFmItVGME/view?usp=sharing  @maliming

**Comment by maliming** [comment]
> The logo problem

https://github.com/volosoft/abp-studio/pull/1564

> The freezes problem

https://discord.com/channels/687243951924838430/813806518578315264/1271029817709432844
