### ISSUE TITLE
Method not found: 'Void Blazorise.Modules.BaseJSModule when updating Blazorise to 1.6.0 for abp.io 8.2.1

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#20482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If I update my abp.io (version 8.2.1) projects Blazorise from 1.5.3 to 1.6.0 I get the following exception.

Unhandled exception rendering component: Method not found: 'Void Blazorise.Modules.BaseJSModule..ctor(Microsoft.JSInterop.IJSRuntime, Blazorise.IVersionProvider)'.
System.MissingMethodException: Method not found: 'Void Blazorise.Modules.BaseJSModule..ctor(Microsoft.JSInterop.IJSRuntime, Blazorise.IVersionProvider)'.
at Blazorise.DataGrid.JSDataGridModule..ctor(IJSRuntime jsRuntime, IVersionProvider versionProvider)
at Blazorise.DataGrid.BaseDataGridComponent.OnInitialized()
at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
at Blazorise.DataGrid.DataGrid1.SetParametersAsync(ParameterView parameters) [10:10:29 ERR] Unhandled exception in circuit '89BBKUt_Q5D6LVbxZIsEJddhtm9kepM6ZMnvOqG06Ng'. System.MissingMethodException: Method not found: 'Void Blazorise.Modules.BaseJSModule..ctor(Microsoft.JSInterop.IJSRuntime, Blazorise.IVersionProvider)'.    at Blazorise.DataGrid.JSDataGridModule..ctor(IJSRuntime jsRuntime, IVersionProvider versionProvider)    at Blazorise.DataGrid.BaseDataGridComponent.OnInitialized()    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()    at Blazorise.DataGrid.DataGrid1.SetParametersAsync(ParameterView parameters)

Take a look at my issue at Blazorise https://github.com/Megabit/Blazorise/issues/5685 

### Reproduction Steps

Update abp.io version 8.2.1 Blazorise project to 1.6.0 and try with DataGrid

### Expected behavior

No error

### Actual behavior

Exception

### Regression?

🤷‍♂️

### Known Workarounds

None

### Version

8.2.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Please create a new template project and check its blazorise package version.

You should use same version.

**Comment by Sturla76** [comment]
But what is causing this and isnt there any workaround? I want to go much faster with Blazorise than abp.io!

And why is Blazorise Grid having this issue with nothing else (no Volo package)? If its trimming you should offer some way of stopping it.

For us that want/need to be on a faster band with a package like Blazorise its a super bad experiance when there is something like this that stops us from doing that.

**Comment by maliming** [comment]
> But what is causing this and isnt there any workaround? 

You can try upgrading Blazorise to 1.6.0 in a new template project to see if the error persists.

**Comment by sturlath** [comment]
I just did @maliming try this one out https://github.com/sturlath/BlazorUpdateTest 

New project with updated Blazorise. Just hit the books page

![image](https://github.com/user-attachments/assets/87144c30-b939-4030-bd82-b73ee9fe11bd)

**Comment by cuno92** [comment]
Dear @sturlath , I faced this problem too. My solution is to add the package Blazorise.DataGrid version 1.6.0.

**Comment by sturlath** [comment]
Thank you @cuno92 that fixed my isse

> My solution is to add the package Blazorise.DataGrid version 1.6.0.

I just didn´t think of doing that 🙈since I thought it just wouldn´t work because of some Volo packed thingy..

But this is still something you guys should look into @maliming ... 

> In the case of APB, I suspect that they should recompile making sure that they are on latest .NET

https://github.com/Megabit/Blazorise/issues/5685#issuecomment-2294828966

**Comment by sturlath** [comment]
@maliming will you recompile as suggested https://github.com/Megabit/Blazorise/issues/5685#issuecomment-2294828966 for 8.2.3?

**Comment by maliming** [comment]
We will check this when we upgrading Blazorise.

**Comment by alvahdean** [comment]
I just ran into this and I did upgrade from .NET Sdk 8.0.3 -> 8.0.4 (but that alone doesn't fix it)
The installation of the Blazorise.DataGrid package is what did the trick. 
Note that I am using the Blazorise 1.6.1 packages and all is well.
Thanks for tracking this down @sturlath and @cuno92, saved me a lot of time!

**Comment by sturlath** [comment]
Creat it worked for you @alvahdean. Since you are updating is there any change you are getting either of these https://github.com/abpframework/abp/issues/20619 or https://github.com/abpframework/abp/issues/20616?

**Comment by alvahdean** [comment]
I'm not seeing the same problems you referred to (at least not the "Features") but I'm using the Basic theme so it maybe something in the Lepton code. 
I am using ABP 8.2.2, dotnet-sdk 8.0.401 and Blazorise 1.6.1.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/20960
