### ISSUE TITLE
AbpExceptionFilter  write header error

### ISSUE THREAD

**Issue by labman003** [abpframework/abp#20483]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

location: abpframework/abp/tree/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs

```
    protected virtual async Task HandleAndWrapException(ExceptionContext context)
    {
        //TODO: Trigger an AbpExceptionHandled event or something like that.

        LogException(context, out var remoteServiceErrorInfo);

        await context.GetRequiredService<IExceptionNotifier>().NotifyAsync(new ExceptionNotificationContext(context.Exception));

        if (context.Exception is AbpAuthorizationException)
        {
            await context.HttpContext.RequestServices.GetRequiredService<IAbpAuthorizationExceptionHandler>()
                .HandleAsync(context.Exception.As<AbpAuthorizationException>(), context.HttpContext);
        }
        else
        {
            context.HttpContext.Response.Headers.Add(AbpHttpConsts.AbpErrorFormat, "true");
            context.HttpContext.Response.StatusCode = (int)context
                .GetRequiredService<IHttpExceptionStatusCodeFinder>()
                .GetStatusCode(context.HttpContext, context.Exception);

            context.Result = new ObjectResult(new RemoteServiceErrorResponse(remoteServiceErrorInfo));
        }

        context.ExceptionHandled = true; //Handled!
    }
```

when   The request has started responding ,  context.HttpContext.Response.Headers.Add will  throw execption 
 
maybe   can   prewrite  check HttpContext.RequestAborted or HttpContext.Response.HasStarted

### Version

7.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Linux

**Comment by maliming** [comment]
hi

> The request has started responding 

How to reproduce this case?

Can you share some code and steps?

**Comment by labman003** [comment]
![image](https://github.com/user-attachments/assets/3dee50d6-926f-49a9-bf65-0181d90f069b)

like this  when the request is cancel the  response has begun

if request abort   cancellationToken will throw excepotion
