### ISSUE TITLE
"--ui no-ui" its not working on ABP CLI 8.3.0-rc.1

### ISSUE THREAD

**Issue by sujonahmed2500** [abpframework/abp#20495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/user-attachments/assets/81523c39-377b-4ade-b89f-e20d3fa5c32e)

I upgraded latest cli but its not working.

### Version

ABP CLI 8.3.0-rc.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by salihozkara** [comment]
This would be --no-ui. I think you created it from the start page. We'll fix it there. Thank you for your notification. @sujonahmed2500

**Comment by realLiangshiwei** [comment]
`--ui-framework or -u: Specifies the UI framework.`

https://abp.io/docs/latest/cli#options

**Comment by woodevera** [comment]
you should use none instead of no-ui , Docs need to be updated !
