### ISSUE TITLE
Having trouble using the IIdentityUserAppService in the console app

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#2051]
I want to import some user records into the database of my abp project, so I wrote a console app, basically referring to [this document](https://docs.abp.io/en/abp/latest/Getting-Started-Console-Application).

I think using `IIdentityUserAppService` is a good choice, so I denpended on the `AbpIdentityApplicationContractsModule` in my module:

``` csharp
    [DependsOn(typeof(AbpAutofacModule))]
    [DependsOn(typeof(MyAbpApplicationModule))]
    [DependsOn(typeof(AbpIdentityApplicationContractsModule))]
    public class AppModule : AbpModule
    {

    }
```

The program.cs is also pretty standard:

``` csharp
        static async Task Main(string[] args)
        {
            using (var application = AbpApplicationFactory.Create<AppModule>(options =>
            {
                options.UseAutofac(); //Autofac integration
            }))
            {
                application.Initialize();

                //Resolve a service and use it
                var service = application.ServiceProvider.GetService<ImportService>();
                Console.ReadLine();
            }
        }
```

The `ImportService` is where the `IIdentityUserAppService` injected:

``` csharp
    public class ImportService : ITransientDependency
    {
        private readonly IIdentityUserAppService _identityUserAppService;

        public ImportService(IIdentityUserAppService identityUserAppService)
        {
            _identityUserAppService = identityUserAppService;
        }
```

But the autofac complained that `IIdentityUserRepository` can't be resolved:
![image](https://user-images.githubusercontent.com/3471718/67931642-39692300-fbfd-11e9-9bf0-6a143a1e1644.png)

So I added the `[DependsOn(typeof(AbpIdentityEntityFrameworkCoreModule))]`, this time the missing dependency became `IdentityUserManager`:
![image](https://user-images.githubusercontent.com/3471718/67931668-49810280-fbfd-11e9-8d37-9871a5218840.png)

I thought the ABP module system would resolve all the dependencies from the dependency graph, am I missing something?

**Comment by maliming** [comment]
The project you provided is incomplete and it needs to be debuggable.

**Comment by wakuflair** [comment]
Sorry for that, zip reuploaded.

**Comment by wakuflair** [comment]
Should configure the connection string:

``` csharp
    [DependsOn(typeof(AbpAutofacModule))]
    [DependsOn(typeof(ABPTestApplicationModule))]
    [DependsOn(typeof(ABPTestEntityFrameworkCoreDbMigrationsModule))]
    public class AppModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<DbConnectionOptions>(conn =>
            {
                conn.ConnectionStrings.Default =
          "Server=localhost;Database=ABPTest;Trusted_Connection=True;MultipleActiveResultSets=true";
            });
        }
```

Thank you @maliming .
