### ISSUE TITLE
nuget Volo.Abp.EntityFrameworkCore.MySQL package?

### ISSUE THREAD

**Issue by halida** [abpframework/abp#2053]
Hi, I'm trying to use MySQL, but I did not found Volo.Abp.EntityFrameworkCore.MySQL package, will you release it?

My dotnet version: .NET Core 3.0

**Comment by maliming** [comment]
https://www.nuget.org/packages/Volo.Abp.EntityFrameworkCore.MySQL

**Comment by halida** [comment]
@maliming Thanks, when will it support .NET Core 3.0?

**Comment by maliming** [comment]
Now!
https://github.com/abpframework/abp/releases

**Comment by halida** [comment]
@maliming But on the nuget page above, it only shows: .NETStandard 2.1, and I cannot found the package, do you need some change on it?

**Comment by johnnba** [comment]
with the package  <PackageReference Include="Volo.Abp.EntityFrameworkCore.MySQL" Version="1.0.2" />
when update-database , it occurs the critical erros as follow:
`BLOB/TEXT column 'Value' used in key specification without a key length.`
```
Failed executing DbCommand (22ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `IdentityServerApiSecrets` (
    `Type` varchar(250) NOT NULL,
    `Value` longtext NOT NULL,
    `ApiResourceId` char(36) NOT NULL,
    `Description` varchar(2000) NULL,
    `Expiration` datetime(6) NULL,
    CONSTRAINT `PK_IdentityServerApiSecrets` PRIMARY KEY (`ApiResourceId`, `Type`, `Value`),
    CONSTRAINT `FK_IdentityServerApiSecrets_IdentityServerApiResources_ApiResou~` FOREIGN KEY (`ApiResourceId`) REFERENCES `IdentityServerApiResources` (`Id`) ON DELETE CASCADE
);
MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB/TEXT column 'Value' used in key specification without a key length
```
It just happens via the standard abp-cli generated projects. @maliming @yekalkan

**Comment by maliming** [comment]
@johnnba  https://github.com/abpframework/abp/issues/1920#issuecomment-543551659

**Comment by johnnba** [comment]
> @johnnba [#1920 (comment)](https://github.com/abpframework/abp/issues/1920#issuecomment-543551659)

i referrenced the solution, it still couldn't work.
[https://github.com/abpframework/abp/issues/1920#issuecomment-543021173]
it still reports the same error, i think you can reproduce the same error.

**Comment by maliming** [comment]
Recreate the migration.

**Comment by johnnba** [comment]
yeah, i delted the old migration and the database, then Recreate the migration..
the failed report still keep the same 
 `Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `IdentityServerApiSecrets` (
    `Type` varchar(250) NOT NULL,
    `Value` longtext NOT NULL,
    `ApiResourceId` char(36) NOT NULL,
    `Description` varchar(2000) NULL,
    `Expiration` datetime(6) NULL,
    CONSTRAINT `PK_IdentityServerApiSecrets` PRIMARY KEY (`ApiResourceId`, `Type`, `Value`),
    CONSTRAINT `FK_IdentityServerApiSecrets_IdentityServerApiResources_ApiResou~` FOREIGN KEY (`ApiResourceId`) REFERENCES `IdentityServerApiResources` (`Id`) ON DELETE CASCADE
);
MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB/TEXT column 'Value' used in key specification without a key length
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB/TEXT column 'Value' used in key specification without a key length`

i used the codes as follow

`public static class IdentityServerModelCreatingExtensions
    {
        public static void ConfigureIdentityServerForMySQL(this ModelBuilder builder)
        {
            // Solve the problem of MySQL migration
            // https://github.com/abpframework/abp/issues/1920

            builder.Entity<ApiSecret>(b =>
            {
                // After trying, you can also set it to 400
                b.Property(x => x.Value).HasMaxLength(300);
            });

            builder.Entity<ClientPostLogoutRedirectUri>(b =>
            {
                b.Property(x => x.PostLogoutRedirectUri).HasMaxLength(300); // or 400 ？
            });

            builder.Entity<ClientRedirectUri>(b =>
            {
                b.Property(x => x.RedirectUri).HasMaxLength(300); // or 400 ？
            });

            builder.Entity<ClientSecret>(b =>
            {
                b.Property(x => x.Value).HasMaxLength(300); // or 400 ？
            });
            
        }
    }`

and  in the migration dbcontext, i repairt it.
protected override void OnModelCreating(ModelBuilder builder)
        {
// ...

// ....
//            builder.ConfigureIdentityServer(options =>
//            {
//                options.DatabaseProvider = EfCoreDatabaseProvider.MySql;  // no worked effect
//            });
builder.ConfigureIdentityServerForMySQL(); // no work effect

}

**Comment by maliming** [comment]
The `OnModelCreating `method needs to call the `OnModelCreating `of the base class.
`base.OnModelCreating(modelBuilder);`

**Comment by johnnba** [comment]
> The `OnModelCreating `method needs to call the `OnModelCreating `of the base class.
> `base.OnModelCreating(modelBuilder);`

that's right; sorry for the codes ignored in the previous comment; i amend the last comment.
it still could not work.

i think you could use the abp-cli tool to reproduce the same problem on version 1.0.2

**Comment by maliming** [comment]
Can you provide a project to reproduce the problem?

**Comment by johnnba** [comment]
> Can you provide a project to reproduce the problem?

ok, i pushed the below demo project generated by abp-cli tool 
https://github.com/johnnba/simpleAbpNextMysqlDemo.git

**Comment by maliming** [comment]
@johnnba 

![image](https://user-images.githubusercontent.com/6908465/68003521-b56c7500-fca8-11e9-84a0-f224b8aabbb5.png)

**Comment by johnnba** [comment]
it's great that the code worked finally , thanks a lot.
it was amazing that the same codes in DbContextModelCreatingExtensions worked rather than OnModelCreating functions.  
i'm still puzzled .

**Comment by maliming** [comment]
see [MyProjectNameMigrationsDbContextFactory](https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/MyProjectNameMigrationsDbContextFactory.cs#L19)
