### ISSUE TITLE
Document render errors (new issues will be added as they're reported)

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#20545]
Our automation tool automatically reports the following errors at [ABP Documentation website](https://abp.io/docs).
These problems are mostly related to Scriban syntax.
We will add new issues here as they are reported by the error monitoring tool.

---

- [x]  ERROR WHILE RENDERING THE DOCUMENT
**Document name:** `startup-templates/application/deployment-docker-compose.md`
**URL:** https://abp.io/docs/commercial/7.1/startup-templates/application/deployment-docker-compose
**Exception message:**
><input>(708,23) : error : The function `if` was not found

User preferences:
```
Document_Language_Code: en
Document_Version: 7.1
Release_Status: stable
UI: MVC
UI_Value: MVC / Razor Pages
DB: EF
DB_Value: Entity Framework Core
Tiered: No
Tiered_Value: Not Tiered
```

---

- [x]  **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `ui/angular/entity-action-extensions.md`
**URL**: https://abp.io/docs/commercial/2.7/ui/angular/entity-action-extensions
**Exception message**:
```
<input>(113,36) : error : The function `abpLocalization` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 2.7
Release_Status: stable
```

---

- [x]  **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `get-started/layered-web-application.md`
**URL**: https://localhost:44328/docs/latest/get-started/layered-web-application?projectname=discord
**Exception message**:
```
This template has errors. Check the <Template.HasError> and <Template.Messages> before evaluating a template. Messages:
<input>(200,154) : error : Error while parsing else statement: The <end> statement was not found in: else | else if <expression> ... end|else|else if
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 1
Release_Status: stable
UI: MVC
UI_Value: MVC / Razor Pages
DB: EF
DB_Value: Entity Framework Core
Tiered: No
Tiered_Value: Not Tiered
```

---

- [x]  **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `Tutorials/Angular/Part-I.md`
**URL**: https://abp.io/docs/1.0/Tutorials/Angular/Part-I
**Exception message**:
```
<input>(634,23) : error : Cannot get the member data.name for a null object.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 1.0
Release_Status: stable
```

---

- [x]  **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `ui/angular/entity-action-extensions.md`
**URL**: https://abp.io/docs/commercial/2.7/ui/angular/entity-action-extensions
**Exception message**:
```
<input>(113,36) : error : The function `abpLocalization` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 2.7
Release_Status: stable
```

---

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `startup-templates/application/deployment-docker-compose.md`
**URL**: https://abp.io/docs/commercial/7.1/startup-templates/application/deployment-docker-compose?UI=Blazor&DB=Mongo&Tiered=No
**Exception message**:
```
<input>(708,23) : error : The function `if` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 7.1
Release_Status: stable
UI: Blazor
UI_Value: Blazor WebAssembly
DB: Mongo
DB_Value: MongoDB
Tiered: No
Tiered_Value: Not Tiered
```

---

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `UI/Angular/DateTime-Format-Pipe.md`
**URL**: https://abp.io/docs/5.3/UI/Angular/DateTime-Format-Pipe
**Exception message**:
```
<input>(8,18) : error : Invalid number of parameters `2` for `date` object/function.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 5.3
Release_Status: stable
```

---

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `startup-templates/application/deployment-docker-compose.md`
**URL**: https://abp.io/docs/commercial/7.1/startup-templates/application/deployment-docker-compose?UI=BlazorServer&DB=Mongo&Tiered=No
**Exception message**:
```
<input>(708,23) : error : The function `if` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 7.1
Release_Status: stable
UI: BlazorServer
UI_Value: Blazor Server
DB: Mongo
DB_Value: MongoDB
Tiered: No
Tiered_Value: Not Tiered
```

---

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `UI/Angular/DateTime-Format-Pipe.md`
**URL**: https://abp.io/docs/5.3/UI/Angular/DateTime-Format-Pipe
**Exception message**:
```
<input>(8,18) : error : Invalid number of parameters `2` for `date` object/function.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 5.3
Release_Status: stable
```

**Comment by oykuermann** [comment]
- [x] ERROR WHILE RENDERING THE DOCUMENT

Document name: UI/Angular/DateTime-Format-Pipe.md
URL: https://abp.io/docs/5.3/UI/Angular/DateTime-Format-Pipe
Exception message:
`<input>(8,18) : error : Invalid number of parameters `2` for `date` object/function.`

User preferences:
```
Document_Language_Code: en
Document_Version: 5.3
Release_Status: stable
```


- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `Tutorials/Angular/Part-I.md`
**URL**: https://abp.io/docs/1.0/Tutorials/Angular/Part-I
**Exception message**:
```
<input>(634,23) : error : Cannot get the member data.name for a null object.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 1.0
Release_Status: stable
```


- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `guides/ms-multi-tenant-domain-resolving.md`
**URL**: https://abp.io/docs/commercial/8.0/guides/ms-multi-tenant-domain-resolving
**Exception message**:
```
This template has errors. Check the <Template.HasError> and <Template.Messages> before evaluating a template. Messages:
<input>(277,12) : error : Unexpected token .
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 8.0
Release_Status: stable
UI: MVC
UI_Value: 
DB: EF
DB_Value: 
Tiered: No
Tiered_Value: 
```


- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `startup-templates/application/deployment-docker-compose.md`
**URL**: https://abp.io/docs/commercial/7.1/startup-templates/application/deployment-docker-compose?UI=BlazorServer&DB=Mongo&Tiered=No
**Exception message**:
```
<input>(708,23) : error : The function `if` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 7.1
Release_Status: stable
UI: BlazorServer
UI_Value: Blazor Server
DB: Mongo
DB_Value: MongoDB
Tiered: No
Tiered_Value: Not Tiered
```

**ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `UI/Angular/DateTime-Format-Pipe.md`
**URL**: https://abp.io/docs/5.3/UI/Angular/DateTime-Format-Pipe
**Exception message**:
```
<input>(8,18) : error : Invalid number of parameters `2` for `date` object/function.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 5.3
Release_Status: stable
```

**Comment by gizemmutukurt** [comment]
- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name:** `Tutorials/Angular/Part-I.md`
**URL:** https://abp.io/docs/1.0/Tutorials/Angular/Part-I
**Exception message:**
`<input>(634,23) : error : Cannot get the member data.name for a null object.`

**User preferences:**
```
Document_Language_Code: en
Document_Version: 1.0
Release_Status: stable
```



- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name:** ui/angular/entity-action-extensions.md
**URL:** https://abp.io/docs/commercial/2.7/ui/angular/entity-action-extensions
**Exception message:**
`<input>(113,36) : error : The function `abpLocalization` was not found`

**User preferences:**
```
Document_Language_Code: en
Document_Version: 2.7
Release_Status: stable
```

**Comment by oykuermann** [comment]
**ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `Tutorials/Angular/Part-I.md`
**URL**: https://abp.io/docs/1.0/Tutorials/Angular/Part-I
**Exception message**:
```
<input>(634,23) : error : Cannot get the member data.name for a null object.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 1.0
Release_Status: stable
```

**Comment by oykuermann** [comment]
- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `UI/Angular/DateTime-Format-Pipe.md`
**URL**: https://abp.io/docs/5.3/UI/Angular/DateTime-Format-Pipe
**Exception message**:
```
<input>(8,18) : error : Invalid number of parameters `2` for `date` object/function.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 5.3
Release_Status: stable
```

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `Tutorials/Angular/Part-II.md`
**URL**: https://abp.io/docs/1.0/Tutorials/Angular/Part-II
**Exception message**:
```
<input>(458,19) : error : Cannot get the member data.name for a null object.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 1.0
Release_Status: stable
```

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `UI/Angular/DateTime-Format-Pipe.md`
**URL**: https://abp.io/docs/5.3/UI/Angular/DateTime-Format-Pipe
**Exception message**:
```
<input>(8,18) : error : Invalid number of parameters `2` for `date` object/function.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 5.3
Release_Status: stable
```

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `Tutorials/Angular/Part-I.md`
**URL**: https://abp.io/docs/1.0/Tutorials/Angular/Part-I
**Exception message**:
```
<input>(634,23) : error : Cannot get the member data.name for a null object.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 1.0
Release_Status: stable
```

**Comment by oykuermann** [comment]
- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `Tutorials/Angular/Part-II.md`
**URL**: https://abp.io/docs/1.0/Tutorials/Angular/Part-II
**Exception message**:
```
<input>(458,19) : error : Cannot get the member data.name for a null object.
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 1.0
Release_Status: stable
```

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `startup-templates/application/deployment-docker-compose.md`
**URL**: https://abp.io/docs/commercial/7.1/startup-templates/application/deployment-docker-compose
**Exception message**:
```
<input>(708,23) : error : The function `if` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 7.1
Release_Status: stable
UI: MVC
UI_Value: MVC / Razor Pages
DB: EF
DB_Value: Entity Framework Core
Tiered: No
Tiered_Value: Not Tiered
```

**Comment by oykuermann** [comment]
- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `ui/angular/entity-action-extensions.md`
**URL**: https://abp.io/docs/commercial/2.7/ui/angular/entity-action-extensions
**Exception message**:
```
<input>(113,36) : error : The function `abpLocalization` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 2.7
Release_Status: stable
UI: MVC
UI_Value: 
DB: EF
DB_Value: 
Tiered: No
Tiered_Value: 
```

**Comment by oykuermann** [comment]
- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `ui/angular/entity-action-extensions.md`
**URL**: https://abp.io/docs/commercial/2.7/ui/angular/entity-action-extensions
**Exception message**:
```
<input>(219,40) : error : The function `abpLocalization` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 2.7
Release_Status: stable
```

**Comment by oykuermann** [comment]
- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `ui/angular/entity-action-extensions.md`
**URL**: https://abp.io/docs/commercial/2.7/ui/angular/entity-action-extensions
**Exception message**:
```
<input>(219,40) : error : The function `abpLocalization` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 2.7
Release_Status: stable
```

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `guides/ms-multi-tenant-domain-resolving.md`
**URL**: https://abp.io/docs/commercial/7.4/guides/ms-multi-tenant-domain-resolving?LanguageCode=en
**Exception message**:
```
This template has errors. Check the <Template.HasError> and <Template.Messages> before evaluating a template. Messages:
<input>(277,12) : error : Unexpected token .
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 7.4
Release_Status: stable
```

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `ui/angular/entity-action-extensions.md`
**URL**: https://abp.io/docs/commercial/2.7/ui/angular/entity-action-extensions
**Exception message**:
```
<input>(219,40) : error : The function `abpLocalization` was not found
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 2.7
Release_Status: stable
```

- [x] **ERROR WHILE RENDERING THE DOCUMENT**
**Document name**: `guides/ms-multi-tenant-domain-resolving.md`
**URL**: https://abp.io/docs/commercial/7.4/guides/ms-multi-tenant-domain-resolving?LanguageCode=en
**Exception message**:
```
This template has errors. Check the <Template.HasError> and <Template.Messages> before evaluating a template. Messages:
<input>(277,12) : error : Unexpected token .
```
**User preferences**:
```
Document_Language_Code: en
Document_Version: 7.4
Release_Status: stable
UI: BlazorServer
UI_Value: 
DB: Mongo
DB_Value: 
Tiered: No
Tiered_Value: 
```

**Comment by hikalkan** [comment]
I am closing this. Open another issue if you need.
