### ISSUE TITLE
Any reasons not to upgrade to datatables.net 2.1.4?

### ISSUE THREAD

**Issue by sephit** [abpframework/abp#20546]
In the last R.C. version, datatables get upgraded to 2.0.2, any reason why is not upgraded to the latest version?

**Comment by maliming** [comment]
They released version 2.1 after we upgraded.

https://github.com/abpframework/abp/pull/19340
https://datatables.net/blog/2024/datatables-2.1

**Comment by luwei0314** [comment]
@maliming 承德老乡，20年互联网从业人员，想加个好友QQ 2533925990
