### ISSUE TITLE
Template disable Multi-Tenancy by default?

### ISSUE THREAD

**Issue by halida** [abpframework/abp#2055]
I'm using "Direct download" on abp.io website, I found Multi-Tenancy is enabled, I think normal project won't use Multi-Tenancy, so maybe it should not be a default feature?

**Comment by maliming** [comment]
```
/* Enable/disable multi-tenancy easily in a single point.
 * If you will never need to multi-tenancy, you can remove
 * related modules and code parts, including this file.
 */
public const bool IsEnabled = true;
```

**Comment by halida** [comment]
@maliming Well, I mean disable it by default.

**Comment by maliming** [comment]
I know what you mean, I mean it can be easily disabled, and the template also relies on a lot of multi-tenant libraries.
