### ISSUE TITLE
Show an error page if libs folder is empty or bundling is not done

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#20559]
Check if `wwwroot/libs` is empty; then show an error page.
In the error page; write that the developer has not run `abp install-libs` therefore the client-side packages are not installed.
You can redirect to the docs 👉 https://abp.io/docs/latest/CLI#install-libs
Make this check only once when the application starts up.
You can check in both dev & prod environment.

Error page can be like this or better one
![image](https://github.com/user-attachments/assets/606a7ca6-a1ba-4b03-bff3-467d6667746f)

---

Sometimes developers also forget to run `abp bundle`!
You can check if bundle is created or not; then show warning at startup and redirect to the docs 👉 https://abp.io/docs/latest/CLI#bundle

---

Note; this implementation can be done in all templates except Angular...

---

An example issue is https://github.com/abpframework/abp/issues/12995

**Comment by maliming** [comment]
> Sometimes developers also forget to run abp bundle!

We will generate the `global.js` and `global.css` in backend. So we can ignore it now.
