### ISSUE TITLE
Syntax error near keyword 'WITH', how to solver

### ISSUE THREAD

**Issue by billpeace** [abpframework/abp#20563]
sql server 2016 No error reported

sql server 2014 have error：Syntax error near keyword 'WITH'.

Microsoft.Data.SqlClient.SqlException: 'Syntax error near keyword 'WITH'.
Syntax error near keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause, or a change tracking context clause, the previous statement must end with a semicolon.'

![image](https://github.com/user-attachments/assets/79bf7eb6-eeaf-4c7c-a93b-5abbb19b73e0)

![image](https://github.com/user-attachments/assets/a5c45d63-b85a-4c21-bb54-ca53c42e46ca)

**Comment by maliming** [comment]
You can refer to
https://github.com/dotnet/efcore/issues/32400#issuecomment-1825363302
https://abp.io/support/questions/6484/ABP-Suite-Create-Project---Incorrect-syntax-near-the-keyword-'WITH'--error#answer-3a100aca-a408-3998-ec64-001d0c010936

**Comment by billpeace** [comment]
Thanks

**Comment by billpeace** [comment]
Can be used UseCompatibilityLevel ?
The following code doesn't seem to work

public class SimpleProjectDbContextFactory : IDesignTimeDbContextFactory<SimpleProjectDbContext>
{
    public SimpleProjectDbContext CreateDbContext(string[] args)
    {
        SimpleProjectEfCoreEntityExtensionMappings.Configure();

        var configuration = BuildConfiguration();

        var builder = new DbContextOptionsBuilder<SimpleProjectDbContext>()
            .UseSqlServer(configuration.GetConnectionString("Default"), o => o.UseCompatibilityLevel(100)); // UseCompatibilityLevel(120)

        return new SimpleProjectDbContext(builder.Options);
    }

**Comment by billpeace** [comment]
Found it  ，Thanks 

![image](https://github.com/user-attachments/assets/14609161-dc12-4124-ad9b-cea31e98ceb1)
