### ISSUE TITLE
ReferenceError: abp is not defined in ServiceProxyScript

### ISSUE THREAD

**Issue by diennttlu** [abpframework/abp#20587]
I go to login page, after restarting web server. The login UI interface is broken as below:
![Screenshot_3](https://github.com/user-attachments/assets/c00b7475-375e-45b2-87cd-099cfbb43c78)
![Screenshot_2](https://github.com/user-attachments/assets/b3f12aea-aa8a-4f96-ae1f-9045d5fa01f7)

I have to press F5 to reload the page, then the login page interface can load.

please help me fix this.
ABP Framework 6.0.0
Angular
EF Core

**Comment by diennttlu** [comment]
dev tool log: 
![image](https://github.com/user-attachments/assets/f4b98220-2c74-4bef-b399-2aaeb064e3ef)

**Comment by maliming** [comment]
Can you share a online URL to reproduce this?

**Comment by diennttlu** [comment]
No, I am currently working on the company's private network environment. 
Let me describe it again. I logged into the system and used it for 30 minutes, then I logged out. At the login screen, it couldn't reload the file
https://domain.com.vn/__bundles/LeptonXLite.Global.4A197B50FEFB1D476E4E506AD6A7411F.css?_v=638599762368498365
https://domain.com.vn/__bundles/LeptonXLite.Global.04C0E47DD336A51CE8C4D9CC45EF565E.js?_v=638599762376167780

I assume those 2 files do not exist in the web-server cache.
![image](https://github.com/user-attachments/assets/7ae98f5d-5a5d-41f5-a40b-fdd2e4e140b7)

**Comment by diennttlu** [comment]
Is there any way to configure not to cache the above 2 files?

**Comment by maliming** [comment]
hi

I think this pr(https://github.com/abpframework/abp/pull/19870) will fix your problem.

https://abp.io/support/questions/7209/404-error-because-of-inconsistent-bundle-hash-keys-across-multiple-instances-on-running-MVC-web-service-with-round-robin-setup#answer-3a12b527-36ba-b989-de9c-ad2e2aff17d9

**Comment by diennttlu** [comment]
This is my configure bundles. Can you confirm for me?. Thank you so much!

```
private void ConfigureBundles()
{
    Configure<AbpBundlingOptions>(options =>
    {
        options.Mode = BundlingMode.BundleAndMinify;
        options.StyleBundles.ConfigureAll(
            bundle =>
            {
                bundle.AddFiles("/global-styles.css", 
                    "/libs/abp/core/abp.css");
            }
        );

        options.ScriptBundles.ConfigureAll(
            bundle =>
            {
                bundle.AddFiles(
                    "/libs/abp/utils/abp-utils.umd.js",
                    "/libs/abp/jquery/abp.jquery.js",
                    "/libs/abp/luxon/abp.luxon.js",
                    "/libs/abp/core/abp.js");
            }
        );
    });
}
```

**Comment by diennttlu** [comment]
![image](https://github.com/user-attachments/assets/61d0f8d5-777a-4dea-8381-e577767abe87)

`  protected IDistributedCache<InMemoryFileInfoCacheItem> Cache { get; }`
Does this configuration work with Redis cache?

**Comment by maliming** [comment]
> Does this configuration work with Redis cache?

Yes

**Comment by diennttlu** [comment]
this is my configure for add stack exchange redis:
```
Configure<AbpDistributedCacheOptions>(options =>
{
    options.KeyPrefix = "WebMaster:" + (string.IsNullOrWhiteSpace(environmentVariable) ? string.Empty : $"{environmentVariable}:");
});

services.AddStackExchangeRedisCache(options =>
{
    var isSentinel = configuration["Cache:Type"].Equals("Sentinel");
    var connectionString = configuration["Cache:ConnectionString"];
    var serviceName = configuration["Cache:InstanceName"];
    if (isSentinel)
    {
        options.ConfigurationOptions = new ConfigurationOptions
        {
            ServiceName = serviceName,
            CommandMap = CommandMap.Sentinel,
            TieBreaker = "",
            AbortOnConnectFail = false,
            SyncTimeout = 3000,
            Ssl = false,
            ConnectRetry = 3,
            KeepAlive = 180
        };

        string[] array = connectionString.Split(';');
        foreach (string hostAndPort in array)
        {
            options.ConfigurationOptions.EndPoints.Add(hostAndPort);
        }
    }
    else
    {
        options.ConfigurationOptions = new ConfigurationOptions
        {
            Ssl = false,
            AbortOnConnectFail = false,
            SyncTimeout = 3000,
            ConnectRetry = 3,
            KeepAlive = 180,
            ServiceName = serviceName
        };

        options.ConfigurationOptions.EndPoints.Add(connectionString);
    }

});
```
I start the program on local machine it shows this error: 
![image](https://github.com/user-attachments/assets/6ee5e5c5-7df9-4b40-aac4-1b4f7086617d)

**Comment by maliming** [comment]
https://github.com/StackExchange/StackExchange.Redis/issues/1580

**Comment by diennttlu** [comment]
![image](https://github.com/user-attachments/assets/92a6e514-8790-4d91-be06-5424ef10ec79)
I have saved 2 bundles to redis. Thank you very much.
