### ISSUE TITLE
the entity inherited by FullAuditedAggregateRoot<Guid>  got failed when insert into the table

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#2060]
1: create the below simple entity 
```
public class AppGuild:FullAuditedAggregateRoot<Guid>
    {
        public AppGuild(Guid id,string name)
        {
            Id = id;
            Name = name;
        }

        public  string Name { get; set; }
        public  string Desc { get; set; }
        public  int Compacity { get; set; }
    }
```
2: when insert or insertasync method called , the following error reported.

```MySqlException: Field 'IsDeleted' doesn't have a default value```

actually when efcore.sqlserver used ,it reported that  `Field 'IsDeleted'  has a null value ,insert table fails` . 
```
private async Task CreateGuildsAsync()
        {
            var guild=new AppGuild(_guidGenerator.Create(), "someone foo")
            { 
                Compacity = 200,
                Desc = "guild tester created"
            };
            await _guilds.InsertAsync(guild);
        }
```
3: the related project  illustrated in below address.

https://github.com/johnnba/simpleAbpNextMysqlDemo.git

you can get the code  and then run MysqlDemo.DbMigrator project after add-migration and update-database

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/68021292-0184dd00-fcdc-11e9-8407-acef167ca50c.png)

**Comment by johnnba** [comment]
though i debugged into the source codes ,i couldn't find the right issue, sorry , sincere thanks @maliming
