### ISSUE TITLE
RedirectAllowedUrls does not allow all urls (*) 

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#20617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to redirect a user to login when there is a 401 error. And using the code below and the RedirectAllowedUrls I'm able to do that **but** only to specific pages that have been set in the appsettings.json.

I can't only set `https://localhost:44306` since that will just redirect the user to be logged into the Blazor Server (http://localhost:44307). But if I set this to  `https://localhost:44306/Index` I get routed there after logging in.

Code that catches 401 and forces the user to login and get returned back.

```csharp
catch (AbpRemoteCallException ex) when (ex.HttpStatusCode == 401)
{
    // Index needs to be specified in the json. That means I can´t just route back to the page I was on witout specifying them all in the json
    var returnUrl = $"{configuration["App:SelfUrl"]}/Index"; 
    var loginUrl = $"{configuration["App:BlazorUrl"]}/Account/Login?returnUrl={Uri.EscapeDataString(returnUrl)}";
    Response.Redirect(loginUrl);
}
```
the appsettings.json file.

```json
{
  "App": {
    "SelfUrl": "http://localhost:44307", // 44307 is the Blazor Server and 44306 the public web
    "HttpApiUrl": "http://localhost:44307",
    "CorsOrigins": "https://localhost:44307,",
     // this only works if I have https://localhost:44306/Index
    "RedirectAllowedUrls": "https://localhost:44306,http://localhost:44307",
    "MVCPublicUrl": "https://localhost:44306",
    "MVCPublicUrlSubDomain": "https://localhost:44306",
    "BlazorUrl": "http://localhost:44307",
    "DisablePII": "false"
  }
```

### Reproduction Steps

Just try out the code in the description.

### Expected behavior

Being able to set what ever return url pointing to any page within my public website that is in RedirectAllowedUrls.

### Actual behavior

I need to set all pages I want to access in the json, even pages with special ids in them like "https://localhost:44306/Event/ab8211bd-a40a-4038-8420-e0e891f576b6" will have to be completly in the json.

### Regression?

Maybe.. because I have this code in another place that when testing it, it doesn´t work. It does nothing of what I expect it should do... it must have worked sometime in the past when I added it...

```csharp
Response.Cookies.Delete(CookieConst.UrlToRedirect);
Response.Cookies.Append(CookieConst.UrlToRedirect, $"/Event/{Id}");
Response.Redirect($"{configuration["App:BlazorUrl"]}/Account/Login");
```

### Known Workarounds

Just adding my frontpage (with Index) so that users get routed somewhere but I don´t want them to loose the places where they are at so its not a great one.

Also I had

### Version

8.2.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

This is a MVC public frontend with Blazor Server backend.

**Comment by maliming** [comment]
hi

You can override the `https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.UI.Navigation/Volo/Abp/Ui/Navigation/Urls/AppUrlProvider.cs#L3 method.

We will consider supporting the wildcard in the next version.
