### ISSUE TITLE
Entity History validatin error

### ISSUE THREAD

**Issue by prisznitz** [abpframework/abp#2062]
Hi,
I'm getting validation error 
The value in the PropertyTypeFullName field must be a string with a maximum length of 192
if entity history is enabled. How is this possible according to EntityPropertyChange.cs? Thank you in advance.
Version ABP 4.5.0

**Comment by Ice2burn** [comment]
Wrong repo? https://github.com/aspnetboilerplate/aspnetboilerplate

**Comment by maliming** [comment]
@prisznitz 
For issue about aspnetboilerplate, please go here.
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/new
