### ISSUE TITLE
website Configuration Section  move to database (multi tenancy)

### ISSUE THREAD

**Issue by pranavpatil19** [abpframework/abp#2063]
IS possible to website Configuration Section  handle from  database (multi tenancy).

Like Set website multi tenancy  true or false, Connection string  ,secrete key  use in identity server
SMTP Configuration etc....

**Comment by maliming** [comment]
You can customize `IConfigurationSource`

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.0#custom-configuration-provider

**Comment by pranavpatil19** [comment]
than you ...but i need help ..   multi tenancy website how i configure different secrete key for different tenent in abp framework....  please guide me
