### ISSUE TITLE
Creating a module project using CLI is missing the host folder

### ISSUE THREAD

**Issue by zhaofenglee** [abpframework/abp#20640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating a template project using the latest CLI does not include a host folder.

![image](https://github.com/user-attachments/assets/6e0a522f-6b0b-4703-bc5c-0bfb4489930c)

### Reproduction Steps

abp new-module Acme.Abp.BookStore -t module:ddd -u angular,blazor-server,mvc,blazor -d ef,mongodb

### Version

8.2.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/20365#issuecomment-2298072482
