### ISSUE TITLE
invalid_token

### ISSUE THREAD

**Issue by HmertC** [abpframework/abp#20665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I generate tokens using openiddict on abp.io. But when I request this token to my class that has [Authorize], I get the Bearer error="invalid_token" error.

### Version

version "7.2.2"

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

### Other information

![Screenshot (1)](https://github.com/user-attachments/assets/28ca88d2-e681-4264-8ab7-8af67db20623)
![Screenshot (2)](https://github.com/user-attachments/assets/45409892-d837-4047-94a2-67cd97480479)
![Screenshot (3)](https://github.com/user-attachments/assets/d5d5108b-e1b2-42d9-b0fd-0e09d4191099)

**Comment by maliming** [comment]
hi

Please check your `logs.txt` to see the reason.

**Comment by HmertC** [comment]
I solved my error even though there was no additional information in my logs file. Thank you.

**Comment by oziriz31** [comment]
Hi. Got the same issue recently. Can u share what was the solution !?

**Comment by maliming** [comment]
Hi @oziriz31 

Please check your app `logs.txt`.

https://abp.io/support/questions/8622/How-to-enable-Debug-logs-for-troubleshoot-problems
