### ISSUE TITLE
working with ng-packs and customize theme (ex:ngx-admin)

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#2068]
Hi, all
thanks a lot Abp team for creating this great project.
When I create an application with angular ui,
Abp cli generated angular's template is hard to reuse or replace all done packages for some reason to me.
, so I plan to put all code to one place just like “abp/npm/ng-packs/” did.
And customize themes to extend and replace theme-shared theme-basic without modify the Abp's code,
and also create components or router for a match every theme.
Now I am starting such that of the project at https://github.com/yinchang0626/abp.ng
if anyone is interested in that. Please ref my repository and I hope to help someone!

**Comment by lktiep** [comment]
@yinchang0626 that's so nice project mate. Please keep it up :)

**Comment by hikalkan** [comment]
Great! We will also check it and see what we can do :)
