### ISSUE TITLE
Localization tag of generated code is not module or microservice compatible In angular Template

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#20715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If developer uses monolith template there is a default localization key and  `{{ '::YourKey' | abpLocalization }}` works but in microservice template or module template. it must be spesified. as a user we can mutate the exists template but it may fixed in default template. So it is tiny and easy to fix bug. 

<img width="1633" alt="resim" src="https://github.com/user-attachments/assets/f8e3d06e-611c-416c-ad99-0faef957be70">

### Reproduction Steps

Create module or microservice.
Generate an entity with abp suite.
go to detail page and see the localization tag doesn't have resource name

also marked place should be   bigger than 1. Because If I have only one tab, I should I do tab! 
<img width="1413" alt="resim" src="https://github.com/user-attachments/assets/24845dd6-a6c1-4e9b-bae4-377ba90091d7">

### Expected behavior

is must be {{ 'ModuleName::<%= name %>' | abpLocalization }}

### Actual behavior

it is  {{ '::<%= name %>' | abpLocalization }}

### Known Workarounds

Use the force harry! change your template. (if you need)

### Version

8.1

**Comment by masum-ulu** [comment]
Solved in pro side, you can track at https://abp.io/pro-releases
