### ISSUE TITLE
WebAuthn - IdentityServer

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2071]
https://www.identityserver.com/articles/fido2-for-aspnet-core-solving-the-password-problem

When IdentityServer will receive fido2 certification, abp will "automatically" get authentication via Yubikey-like security keys?

**Comment by maliming** [comment]
Abp does not make any changes to the identity server, it uses the identity server directly.
So you can try it. If you encounter problems, welcome feedback.
