### ISSUE TITLE
stuck with custom external oauth provider

### ISSUE THREAD

**Issue by buerobuettner** [abpframework/abp#2072]
hi
i need help using authorization in the abp framework with a custom external oauth provider. The provider create a token to secure the APB API and also stores all users:

![schema](https://user-images.githubusercontent.com/17150747/68123161-7f2f2f80-ff0c-11e9-94b7-525b67eda43a.png)

Can anyone help me out with an example?

regards
christian

**Comment by maliming** [comment]
hi @buerobuettner

The abp account module uses the external login function of identity.

You can find a lot of providers in [AspNetCore](https://github.com/aspnet/AspNetCore/tree/master/src/Security/Authentication) and [AspNet.Security.OAuth.Providers](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers), and you can implement your provider yourself.

**Comment by buerobuettner** [comment]
thx @maliming 
the account module with identity isnt the right thing i guess, because i do no user management. i use the users from a remote service.
Your links point to ready made external providers - i need to use a custom one.. Ain't there an example for custom ones, that i can use with abp?

**Comment by hyzx86** [comment]
I have follow this document https://docs.abp.io/zh-Hans/abp/latest/How-To/Customize-SignIn-Manager
but the sample is login from mvc page
how can I use Jwt to login and  get the user token?
