### ISSUE TITLE
How to ack a RabbitMQ message?

### ISSUE THREAD

**Issue by buzzlu** [abpframework/abp#2074]
Hello:

We have enable package Volo.Abp.EventBus.RabbitMq for MQ message consuming.
How can I consum messages in a RabbitMQ queue ?
How to Ack the MQ message after subscrib with IDistributedEventBus?

Any tips or samples are appreciated. Thanks

 public  class MQListener  : IHostedService
    {
        private readonly IDistributedEventBus _distributedEventBus;
        public IDistributedEventHandler<User> _userMsgHandler;

        public MQListener(IDistributedEventBus distributedEventBus, IDistributedEventHandler<User> userMsgHandler)
        {
            _distributedEventBus = distributedEventBus;
            _userMsgHandler = userMsgHandler;
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            _distributedEventBus.Subscribe<User>(
                     eventData =>
                     {
                         _userMsgHandler.HandleEventAsync(eventData);
                         var _userName = eventData.UserName;
                         var _userId = eventData.Id;
                         /// to do ack for MQ messages
                         /// 
                       
                         return Task.CompletedTask;
                     });

            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }
    }

**Comment by mehmetuken** [comment]
Check this sample project.
https://github.com/abpframework/abp/tree/dev/samples/RabbitMqEventBus

**Comment by hikalkan** [comment]
No need to ACK, ABP automatically sents ACK if you don't throw any exception.
Instead of subscribing manually, you can implement IDistributedEventHandler like https://github.com/abpframework/abp/blob/dev/samples/RabbitMqEventBus/App2/App2TextReceivedEventHandler.cs#L12

**Comment by buzzlu** [comment]
Thanks, It's Publish/Subscribe model and my task will be done automatically after implement the IDistributedEventHandler.

**Comment by xyfy** [comment]
@hikalkan  I am working with eventbus with rabbitmq,  can it take a **manual ack** option?    consumer B receive a message ,do othing ,and auto ack it. so consumer  B can not receive this message

**Comment by volethanh** [comment]
Hi @hikalkan , how to ack when my app throws exception. It stucked in the queue and everytime I restart the app, it consume again and again
