### ISSUE TITLE
Entity Extensions (EF Core) generate incorrect SQL when deleting entities

### ISSUE THREAD

**Issue by cdlian** [abpframework/abp#20744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In my example code, there are two extended properties: DbProperty is mapped to a database field through EFCore and cannot be NULL, while NoDbProperty is stored in ExtraProperties. When I delete an entity, the generated SQL set DbProperty to NULL.

<img width="1276" alt="iShot_2024-09-02_10 58 25" src="https://github.com/user-attachments/assets/2b6892b3-54e7-43eb-a710-833e4f6706a5">
<img width="1879" alt="iShot_2024-09-02_11 00 52" src="https://github.com/user-attachments/assets/f24ec8fe-e03b-42d4-90be-e8b6aef35776">

[Sample Code](https://github.com/cdlian/abp-issue-20277)

### Version

8.3.0-rc.3

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

macOS

**Comment by maliming** [comment]
You can try to override the `ApplyAbpConceptsForDeletedEntity` method of `AbpDbContext`.

![image](https://github.com/user-attachments/assets/a0333699-b47a-47f1-b33c-1c94b0970b49)
```cs
protected override void ApplyAbpConceptsForDeletedEntity(EntityEntry entry)
{
    if (!(entry.Entity is ISoftDelete))
    {
        return;
    }

    if (IsHardDeleted(entry))
    {
        return;
    }

    ExtraPropertyDictionary? originalExtraProperties = null;
    if (entry.Entity is IHasExtraProperties)
    {
        originalExtraProperties = entry.OriginalValues.GetValue<ExtraPropertyDictionary>(nameof(IHasExtraProperties.ExtraProperties));
    }

    entry.Reload();

    if (entry.Entity is IHasExtraProperties)
    {
        ObjectHelper.TrySetProperty(entry.Entity.As<IHasExtraProperties>(), x => x.ExtraProperties, () => originalExtraProperties);
    }

    ObjectHelper.TrySetProperty(entry.Entity.As<ISoftDelete>(), x => x.IsDeleted, () => true);
    SetDeletionAuditProperties(entry);
}
```
