### ISSUE TITLE
Integration tests randomly hanging using dotnet test

### ISSUE THREAD

**Issue by javiercampos** [abpframework/abp#2075]
I have a problem which has me banging my head against a wall, and I don't know what else to try. We have over 400 integration tests that *"generally"* run fine on our development machines.

However when running on the CI runner, they seem to hang at some test randomly (sometimes they do hang, sometimes they don't). I suspect the main difference is the number of threads available to the test runner.

I'd blame the CI runner, but since we started having a big number of tests, it has actually started happening -to much less degree, but I blame that on the CI runner being a limited-hardware VM and our developers running on i7s- on some development computers (not specifically in mine though)... that's why I said *"generally run fine"* up there.

I have tried both XUnit and NUnit, and I have the same problem on both (I've configured both of them to remove parallelization, and either limited the number of threads to 1, many, infinite, or the default: same thing)... I've narrowed it down to calls on ABP code: everytime we get one of those "hangs", it happens on ABP specific code (seems totally random), and never on our code. I traced that providing my own test discoverer and executor in XUnit and sending out diagnostic messages (using `IMessageSink`) before every `await`: so far (in several days doing different tests), everytime we get a "deadlock", it always happens after entering an ABP implementation (which again: it's totally random: it doesn't even -always- happen, so I can't pinpoint any specific code in ABP), and never in our own code await's.

My suspicions come from the lack of use of `ConfigureAwait(false)` in ABP code: this does not matter in asp.net core since it doesn't use a `SynchronizationContext` (it continues the awaitables using the threadpool), however, at least both XUnit and NUnit do supply one and I have a suspicion it may be hanging to some worker thread that never ends because it's out of real threads to use to be able to go back to the continuation on the same thread.

I've made *totally* sure we don't have any `async void` tests, we don't have any anonymous async lambda, and we do not use `.Wait()`, or `.Result()` or anything else that could be blocking in the tests (I'm also not using the `AsyncHelper.RunSync` on test code, although I do on the initialization).

I'm using the `AbpIntegratedTest` as a base for our tests, but I'm using it as a `ICollectionFixture` instead of deriving the test classes from it (so that the required services and data are only initialized one). Just as a test, I did try to derive the actual test class from the base (which in itself derives from `AbpIntegratedTest`) and have a whole `AbpApplication` initialized per test: same result... random deadlocks.

Also, although we do use local events, I've tried disabling them for the tests (replacing the `ILocalEventBus` service with the `NullLocalEventBus` implementation).

I understand this is vague and I'm not providing a reproducible case, so I'm not expecting a direct answer, but I'm just wondering if it has happened to someone else and could pinpoint some speciifc reason or somewhere to look.

Also, would it be possible to add ConfigureAwait to all awaitables (as it should be for libraries) in ABP? I could provide a PR for that (I have a tool to add them automatically to a whole codebase), however it would probably touch -everywhere- and many conflicts would arise from that on other branches.

Adding `ConfigureAwait(false)` should not make any difference in the runtime on asp.net core, yet it would help any other runner using a `SynchronizationContext`.

Of course, I'm not sure that would help at all with my problem, but there's absolutely nothing else I can think of trying at this point.

PS: unit tests (for which we have some hundreds too) work flawlessly, but they don't really use ABP code, we just mock the interfaces for those and test just our code.

**Comment by javiercampos** [comment]
Just to rule out the CI runner (we were using Gitlab CI with our own -not the shared one- runner), I've installed TeamCity and set up a private agent, with the same result (actually, it ran fine the first build, and it did a deadlock/hang on the second and third one, with no changes whatsoever)

**Comment by maliming** [comment]
I found that a large number of MongoDb processes remain in the system after the unit test. This is definitely not normal. Maybe it is related to this problem. I will investigate it.

![image](https://user-images.githubusercontent.com/6908465/70129990-aff4b700-16ba-11ea-9628-f90ade35c88d.png)

**Comment by javiercampos** [comment]
I've investigated deeply, and I believe you have two problems on the library (generally):

1) You don't use `ConfigureAwait(false)` on your awaitables... this bears no importance on asp.net core (running on either kestrel or IIS), but it does when using a synchronization context (like on a test runner like xunit or nunit)

2) You use the `AsyncHelper.RunSync` on some processes (specially the validator chain on the proxies). This uses the `Nito.AsyncEx` library by Stephen Cleary, and creates a synchronization context for those sync calls (using the [AsyncSynchronizationContext](https://github.com/StephenCleary/AsyncEx/blob/master/src/Nito.AsyncEx.Context/AsyncContext.SynchronizationContext.cs) which may give problems if running on asp.net (you prevent it from using its own thread pool, plus you prevent the usage of the synchronization context used on the test runners, which is what manages parallelization, so at some point, tests may be waiting for a semaphore to be released which is never done).

Regarding your problem, there's an inherent problem on ABP (at least on the standard templates), when using AutoFac and proxies: the Autofac container is never disposed so basically every singleton remains on memory even after the `Application` (the abp `Application`) has ended. We have had many problems with hosts just never closing (and threads still opened and running) until we started storing the container elsewhere and disposing it after closing the host. This may be related even if you don't use a host, but if you do initialize Autofac on the ABP application.

What we have done for that is made our custom `IHost` extension (instead of using the ABP's `UseAutofac()` one) and storing the container (currently on a static variable, but we are going to change that to a `ConcurrentBag` to allow multiple hosts or containers to be created):

```c#
    public static class AutofacHostBuilderExtensions
    {
        public static AutofacServiceProviderFactory DiFactory { get; set; }
        public static IHostBuilder UseCustomAutofac(this IHostBuilder hostBuilder)
        {
            var containerBuilder = new ContainerBuilder();

            DiFactory = new AutofacServiceProviderFactory(containerBuilder);

            return hostBuilder.ConfigureServices((_, services) =>
            {
                services.AddObjectAccessor(containerBuilder);
            })
            .UseServiceProviderFactory(spFactory);
        }
    }
``` 

Then, when we create and run our IHost, we use that extension (which stores the container) instead of ABP's `UseAutofac()` (which doesn't)

```c#
            try
            {
                Log.Information("Starting " + name);
                var hostBuilder = Microsoft.Extensions.Hosting.Host.CreateDefaultBuilder(args)
                     .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<TStartup>(); })
                     .UseCustomAutofac()
                     .UseSerilog();
                if (hostBuilderPostCreationOptions != null)
                    hostBuilder = hostBuilderPostCreationOptions(hostBuilder);
                var host = hostBuilder.Build();
                if (hostPostBuildOptions != null)
                    host = hostPostBuildOptions(host);
                using (host)
                {
                    await host.RunAsync().ConfigureAwait(false);
                }

                return 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Host terminated with exception: {ex}");
                Log.Fatal(ex, "Host terminated unexpectedly!");
                return 1;
            }
            finally
            {
                // Dispose our container here
                AutofacHostBuilderExtensions.DiFactory?.Dispose();
                Log.CloseAndFlush();
            }
```

**Comment by tolemac** [comment]
@hikalkan I would like to have a feedback about @javiercampos words.
Can you give us a small explanation of how did resolve this issue?

**Comment by javiercampos** [comment]
@hikalkan would you accept a PR where I call `ConfigureAwait(false)` on every `await` throughout the whole library once 2.0 is feature-complete (so causing the minimum friction, because that will create tons of conflicts on dev branches)?

I believe it's quite important on some scenarios (for a recent writeup of why, you may want to check https://devblogs.microsoft.com/dotnet/configureawait-faq/ )

**Comment by hikalkan** [comment]
>@hikalkan would you accept a PR where I call ConfigureAwait(false) on every await throughout the whole library once 2.0 is feature-complete

Yes, please. We intent to release 2.0 in the next week (probably friday), can you complete it?

**Comment by hikalkan** [comment]
Created a separate issue: https://github.com/abpframework/abp/issues/2497

**Comment by javiercampos** [comment]
> > @hikalkan would you accept a PR where I call ConfigureAwait(false) on every await throughout the whole library once 2.0 is feature-complete
> 
> Yes, please. We intent to release 2.0 in the next week (probably friday), can you complete it?

Sure thing, I'll open a PR referencing #2497 as soon as I'm done
