### ISSUE TITLE
Show menuoption only if user has permission (role)

### ISSUE THREAD

**Issue by felipemoreira2x** [abpframework/abp#2076]
Hi guys. 
Firstly, congratulations for amazing work!

I´m trying to show a menu item only if a user has permission. 

I have a role name "user" and set permission to access Products Crud Operation:
![image](https://user-images.githubusercontent.com/57194497/68156054-c11a9e80-ff29-11e9-98d0-355075ab6bf8.png)

On my backend, i have BookAppService that will only be accessed with user has Products_Management role:

```
 [Authorize("Products_Management")]
    public class BookAppService : CrudAppService<Book, BookDto, Guid, PagedAndSortedResultRequestDto,
                           CreateUpdateBookDto, CreateUpdateBookDto>, IBookAppService
    {
        public BookAppService(IRepository<Book, Guid> repository)
            : base(repository)
        {

        }
    }
```

As a result, any user who does not have Products_Management, returns "You are not authorized" as expected.

So, taking a look at the existing module codes, i tried this code to intended to show only the Products menu item if the user has permission, on app-routing-module.js:

```
{ 
    path: 'books', 
    component: ApplicationLayoutComponent,
    loadChildren: () => import('./books/books.module').then(m => m.BooksModule),
    canActivate: [AuthGuard, PermissionGuard],
    data: {
      routes: {
        name: 'Books',
      } as ABP.Route,
      requiredPolicy: 'Products_Management'
    } 
  }
```
As a result, regardless the user has permission or not, the menu item Books always shown.

How can a resolve this situation ? 

Thanks!

**Comment by mehmet-erim** [comment]
Check the `grantedPolicies` data in the `application-configuration` response. Is there `Products_Management` key?

**Comment by felipemoreira2x** [comment]
Hi @mehmet-erim. Thanks for your feedback.

After request "/api/abp/application-configuration" i check out that grantedPolicies is empty, ok. But, even though this option is empty, how other modules like Identity, show menu item acoordly with your permissions ?

**Comment by felipemoreira2x** [comment]
This is my application-configuration response:
 ```
"auth": {
    "policies": {
      "AbpIdentity.Roles": true,
      "AbpIdentity.Roles.Create": true,
      "AbpIdentity.Roles.Update": true,
      "AbpIdentity.Roles.Delete": true,
      "AbpIdentity.Roles.ManagePermissions": true,
      "AbpIdentity.Users": true,
      "AbpIdentity.Users.Create": true,
      "AbpIdentity.Users.Update": true,
      "AbpIdentity.Users.Delete": true,
      "AbpIdentity.Users.ManagePermissions": true,
      "AbpIdentity.UserLookup": true,
      "AbpTenantManagement.Tenants": true,
      "AbpTenantManagement.Tenants.Create": true,
      "AbpTenantManagement.Tenants.Update": true,
      "AbpTenantManagement.Tenants.Delete": true,
      "AbpTenantManagement.Tenants.ManageFeatures": true,
      "AbpTenantManagement.Tenants.ManageConnectionStrings": true,
      **"Products_Management": true**
    },
    "grantedPolicies": {}
  },
```
