### ISSUE TITLE
MySql BLOB/TEXT column 'Value' used in key specification without a key length

### ISSUE THREAD

**Issue by sdjnzjz** [abpframework/abp#2077]
IdentityServerApiSecrets Value

**Comment by sdjnzjz** [comment]
![TIM图片20191105103848](https://user-images.githubusercontent.com/5534101/68174350-c4a93680-ffb8-11e9-8f66-80a01714c3c3.png)

**Comment by maliming** [comment]
Duplicate of https://github.com/abpframework/abp/issues/1920#issuecomment-543551659 https://github.com/abpframework/abp/issues/2053#issuecomment-548626182

**Comment by sdjnzjz** [comment]
thanks !!
