### ISSUE TITLE
When creating a module the module projects are not added to the solution.

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#20781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you create a new solution in ABP Studio and you create a module the module projects are not added to the main solution when you import it.

the legacy CLI used to have a command to do this where the module used to reside in the modules folder part of the main solution.

### Version

Latest

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
Hi, you can use the **Import Module** option to import a module to a .NET solution:

![image](https://github.com/user-attachments/assets/3cff4379-40f6-485f-8a86-c80e74de1965)

See the documentation: https://abp.io/docs/latest/studio/solution-explorer#import-a-module

ABP Studio gives you a flexible development environment, it's totally up to you to import the module or developing it and use another solution for your needs.
