### ISSUE TITLE
Truncate `IpAddresses` of session.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#20794]
Also add the length of `IdentitySessionConsts.MaxIpAddressesLength`.

**Comment by colinin** [comment]
How to record the region where the login ip address is located? for example: 180.168.255.18 from Shanghai,

```csharp
public class IdentitySession : BasicAggregateRoot<Guid>, IMultiTenant
{
    public virtual string Region { get; protected set; }
    // ...
}
```


or an IdentitySession entity inherited from IHasExtraProperties

```csharp
public class IdentitySession : BasicAggregateRoot<Guid>, IHasExtraProperties, IMultiTenant
{
    public ExtraPropertyDictionary ExtraProperties { get; protected set; }
    // ...
}
```

This is optional. Users can implement IP address resolution by themselves, such as [IP2Region](https://github.com/lionsoul2014/ip2region)

**Comment by maliming** [comment]
> How to record the region where the login ip address is located? for example: 180.168.255.18 from Shanghai,
> 
> ```cs
> public class IdentitySession : BasicAggregateRoot<Guid>, IMultiTenant
> {
>     public virtual string Region { get; protected set; }
>     // ...
> }
> ```
> 
> or an IdentitySession entity inherited from IHasExtraProperties
> 
> ```cs
> public class IdentitySession : BasicAggregateRoot<Guid>, IHasExtraProperties, IMultiTenant
> {
>     public ExtraPropertyDictionary ExtraProperties { get; protected set; }
>     // ...
> }
> ```
> 
> This is optional. Users can implement IP address resolution by themselves, such as [IP2Region](https://github.com/lionsoul2014/ip2region)

https://github.com/abpframework/abp/pull/20771
