### ISSUE TITLE
Online & Offline feature for Angular UI using Electron

### ISSUE THREAD

**Issue by HAja85** [abpframework/abp#20809]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I tried to configure the angular application in online and offline mode using electron. But it’s not working. in support forum, it mentioned to disable skipGetAppConfiguration and skipInitAuthService. But in aspnetzero code, we can’t find the properties. 
Is it possible to make aspnetzero application working in offline mode(No Internet/Intranet connection)?
We are using aspnetzero version - 13.0.1.

### Version

ABP 9.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by ismcagdas** [comment]
This is related to a different product, so I'm closing it.
