### ISSUE TITLE
Lang attribute on HTML is always set to en on the first load

### ISSUE THREAD

**Issue by maskalek** [abpframework/abp#20805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When opening a page for the first time in a web application, the lang attribute on the <html> tag is always set to en (English), regardless of the selected language. This issue only occurs on the first load of the page. After selecting new language, attribute is set correctly.

### Reproduction Steps

1. Set up a new app with Angular UI
2. Open the application for the first time in a browser.
3. Inspect the lang attribute on the <html> tag in the developer tools.
4. Change language
5. tag is changed
6. Reload page

### Expected behavior

The lang attribute on the <html> tag should be set based on the user's preferred language 

### Actual behavior

On the first load of the page, the lang attribute is always set to en, even if the default language is set to something else.

### Version

8.3.0

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

This issue seems to be in `setInitialLanguage` in `SessionStateService`. 
`if` is always false as far as I see in the block below
```
if (appLanguage !== lang) {
          this.setLanguage(lang);
        }
```

**Comment by masum-ulu** [comment]
Welcome PR :)
