### ISSUE TITLE
Don't show up all default API

### ISSUE THREAD

**Issue by lktiep** [abpframework/abp#2082]
My problem:

- I can't have the full default APIs after pulling the code as expected. This is show up at my machine: https://i.imgur.com/tOT9u7j.png

- This is default template solution, I've followed steps to migrate DB (database showed as expected).

- I packed whole solution and send to my 2 friends, and they CAN run without any errors (they can see full APIs).

- I'm using Visual Studio 2019 v16.3.7

Do you have any ideas???

**Comment by maliming** [comment]
Try the following command and then rerun the project with Visual Studio .
```
dotnet clean
dotnet build
```

**Comment by lktiep** [comment]
> 
> 
> Try the following command and then rerun the project with Visual Studio .
> 
> ```
> dotnet clean
> dotnet build
> ```

You saved my day!!! Thanks mate!
