### ISSUE TITLE
About Blazor IStringLocalizer

### ISSUE THREAD

**Issue by llp1520** [abpframework/abp#20821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

i have found that the AbpCrudPageBase class has a IStringLocalizer property ,when i use it in Book.razor page ,it doesn't work.Then i followed thd doc at https://abp.io/docs/latest/tutorials/book-store/part-02?UI=Blazor&DB=EF .I use inject IStringLocalizer<BookStoreResource> L to inject it ,It works very well.But the vs IDE was warned.there are the picture.
![image](https://github.com/user-attachments/assets/8ae5efbd-8a7b-4b94-8760-81bfe8d5ab31)

### Version

8.3

### User Interface

Blazor

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
You can set the `LocalizationResource` of base class then use the `L` property.

**Comment by llp1520** [comment]
Thank you for the answer,i am new in learning abp,could you please tell me how to  set the `LocalizationResource `of base class

**Comment by llp1520** [comment]
> You can set the `LocalizationResource` of base class then use the `L` property.
Thank you for the answer,i am new in learning abp,could you please tell me how to set the LocalizationResource of base class

**Comment by llp1520** [comment]
Thank you for the answer,i am new in learning abp,could you please tell me how to set the LocalizationResource of base class

**Comment by maliming** [comment]
In the constructor of your `books` component set the `LocalizationResource` to your resource. then the `L` will use the correct resource.

**Comment by llp1520** [comment]
Get it! Thank you very munch!
