### ISSUE TITLE
Volo.Abp.Studio.Cli.Commands cannot create Console template.

### ISSUE THREAD

**Issue by mahmut-gundogdu** [abpframework/abp#20855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the command that I executed
`abp new Acme.MyConsoleApp -t console`
the code come from document. https://abp.io/docs/latest/get-started/console

<img width="1320" alt="image" src="https://github.com/user-attachments/assets/296d7831-a72c-48f5-903b-bd2b8160bfbe">

### Version

0.8.2

### Operation System

macOS

**Comment by EngincanV** [comment]
For a quick workaround, you can pass the **--old** parameter to the end of the command:

```bash
abp new Acme.MyConsoleApp -t console --old
```

This will create a console template with the old cli.

**Comment by EngincanV** [comment]
I created an internal issue to add the console & wpf templates to the new templating system. In meantime, you can create the template by passing the **--old** parameter at the end of the command. BTW, documentation will be updated with https://github.com/abpframework/abp/pull/20929
