### ISSUE TITLE
Languages found in /dev missing in releases

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#20864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It seems like there are several languages translated in /dev branch that has never made it into releases, even though they have been merged with /dev several months ago. I can find for example  "cs", "is" and "sv" even though they are in in /dev since a few months back like

https://github.com/abpframework/abp/tree/dev/abp_io/AbpIoLocalization/AbpIoLocalization/Account/Localization/Resources

I would imagine that they are supposed to make it into the releases and that you are not intended to add them manually once they have been merged into /dev?

Have tried creating new projects both for Angular and Blazor with both free and commercial versions and they seem to be missing  in everyone so I assume this is not related to a specific template. 

Thanks. 

### Version

8.3

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by improwise** [comment]
Just to clarify, this isn't really a bug but more of a missing feature or whatever we should call it, does not seem like I can change that now.

**Comment by maliming** [comment]
hi @improwise 

www.abp.io has disabled the localization feature. It only supports English now.

I'm very sorry about this.

**Comment by improwise** [comment]
> hi @improwise
> 
> [www.abp.io](http://www.abp.io) has disabled the localization feature. It only supports English now.
> 
> I'm very sorry about this.

This is about the ABP Framework and solutions created using that, not the ABP website :)

**Comment by maliming** [comment]
hi

The changes merged to `dev`, and the `dev` target to abp 9.0

Current releases are target 8.x

This is the reason. I have picked the commit to rel-8.3. so it will available in next 8.x patch version.

Thanks.

**Comment by improwise** [comment]
Thank you!
