### ISSUE TITLE
TypeError: Cannot read property 'identityUser' of undefined

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#2086]
Fetched repo (10 min ago)
dotnet clean
dotnet build

run BookStore Sample

Click Admin|Identity|Users

![image](https://user-images.githubusercontent.com/40014477/68189994-81b28780-ffe7-11e9-8d37-169788f54ed0.png)

**Comment by 274188A** [comment]
cannot reproduce now

**Comment by maliming** [comment]
Maybe related: https://github.com/abpframework/abp/issues/2082

**Comment by 274188A** [comment]
issue now reproducible - but not resolved by `dotnet clean` + `dotnet build`

so now when navigating to: https://localhost:44361/Identity/Users
 I see the following is in the console:

![image](https://user-images.githubusercontent.com/40014477/68259413-c5070780-0074-11ea-9ac1-6a80479325a5.png)

**Comment by maliming** [comment]
```
{
  "version": "1.0.0",
  "name": "my-app",
  "private": true,
  "dependencies": {
    "@abp/aspnetcore.mvc.ui.theme.basic": "^1.0.2"
  }
}


> yarn
> gulp
```

**Comment by 274188A** [comment]
now fixed - thanks
