### ISSUE TITLE
MicroserviceDemo

### ISSUE THREAD

**Issue by leunghoary** [abpframework/abp#2089]
No policy defined to get/set permissions for the provider ''. Use PermissionManagementOptions to map the policy.

**Comment by maliming** [comment]
Can you talk about it in detail?

**Comment by leunghoary** [comment]
I get on the postman to token, http://localhost:65115/api/abp/permissions?ProviderName =User&providerKey=75f8fd90-d094-eb8b-9f73-39f14f1af542 "500 error appears here, check log:"Volo. Abp. AbpException: No policy defined to get/set permissions for the provider '. Use PermissionManagementOptions to map the policy."

**Comment by maliming** [comment]
`ProviderName` has been renamed.
https://github.com/abpframework/abp/issues/286

**Comment by leunghoary** [comment]
Thank you ,but http://localhost:65115/api/abp/application-configuration currentUser is null

**Comment by leunghoary** [comment]
我用token访问上面的地址，返回的结果CurrentUser is null ，还有什么地方改过了吗

**Comment by maliming** [comment]
Please see https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo
