### ISSUE TITLE
AngularUI: Console displays many warning

### ISSUE THREAD

**Issue by masum-ulu** [abpframework/abp#20909]
Check https://abp.io/support/questions/7980

![image](https://github.com/user-attachments/assets/85880456-42d0-4e6e-90db-3efee13f2a6e)

**Comment by CrazyBaran** [comment]
I had the same issue, is there any solution for that? It came from navbar component. @masum-ulu 
![image](https://github.com/user-attachments/assets/581e442c-fd55-4c6e-bb1e-2e6c9dbcbd46)

**Comment by CrazyBaran** [comment]
I just update to 9.0.0 and it still happen.

**Comment by CrazyBaran** [comment]
Is there any walkaround to suppress it? Right now it is not possible to use console at all.

**Comment by masum-ulu** [comment]
We haven't check yet, for temp solution uncheck warning message if you don't need.

**Comment by masum-ulu** [comment]
This issue solved internally for 9.0-patch
