### ISSUE TITLE
Add Layout Name Selection Feature for CMS Pages

### ISSUE THREAD

**Issue by suhaib-mousa** [abpframework/abp#20910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to customize the pages within the CMSKit more effectively, but currently, there is no intuitive way to select a specific layout for each page. This limits flexibility in page design.

### Describe the solution you'd like

Add a dropdown menu for selecting predefined layouts to enhance page customization during creation and editing.

**Comment by suhaib-mousa** [comment]
Thanks for the approval @enisn

**Comment by enisn** [comment]
Thanks for your contribution, everything is done well 👍 💯

**Comment by suhaib-mousa** [comment]
> Thanks for your contribution, everything is done well 👍 💯

Great to hear, appreciate the feedback ❤️

**Comment by sturlath** [comment]
Any change you can share with me how you are using this to customise page layouts @suhaib-mousa? Is this something I could use to full fill my requirements I have as seen here https://abp.io/qa/questions/8432/3a16b8f0-e57b-135a-858a-911c2b3b3456

**Comment by suhaib-mousa** [comment]
> Any change you can share with me how you are using this to customise page layouts @suhaib-mousa? Is this something I could use to full fill my requirements I have as seen here https://abp.io/qa/questions/8432/3a16b8f0-e57b-135a-858a-911c2b3b3456

The feature I implemented is indeed limited in scope. It allows you to select a predefined layout during page creation or editing, but the customization options are primarily confined to the layout's structure. The content of the page body is rendered in a single placeholder `@RenderBody()`, and the flexibility lies in how you define and extend those layouts.

To get started with creating your own layouts, you can refer to the following examples in the ABP Framework repository:
[ABP Basic Theme Layouts](https://github.com/abpframework/abp/tree/dev/modules/basic-theme/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts)

These layouts are defined in the Basic Theme module, and they demonstrate how to set up placeholders and structure your pages. You can adapt these layouts to your needs or create new ones by following a similar approach.

You might need another implementation if your requirements involve rendering multiple placeholders or dynamic content.
