### ISSUE TITLE
Website abp.io pt-BR version is weird

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2092]
![image](https://user-images.githubusercontent.com/6138475/68264759-b8f55880-0028-11ea-87b6-74dd8c6863b8.png)

![image](https://user-images.githubusercontent.com/6138475/68264831-f954d680-0028-11ea-8349-85c8ba65a467.png)

Also, while trying to access from 'abp.io' it does not redirect to its secure version 'https://abp.io'

I'll be submitting PR's to help with translation to pt-BR

**Comment by yekalkan** [comment]
I guess this is already fixed by https://github.com/abpframework/abp/commit/af80f43c4c92eb006b4acd8faedb8aae7b70f1a4#diff-6e6a8c949c01380e8fbfca46f3a9f303
