### ISSUE TITLE
Angular template: Save button on form does not 'recover' after validation error

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2093]
ABP Version: 1.0.2

![image](https://user-images.githubusercontent.com/6138475/68264700-703d9f80-0028-11ea-836c-d624a691f556.png)

![image](https://user-images.githubusercontent.com/6138475/68264691-64ea7400-0028-11ea-9380-428049ddfa09.png)

**Comment by mehmet-erim** [comment]
Thanks @thiag0coelho
