### ISSUE TITLE
Upgrade to Openiddict 6.0.0

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#20977]
https://github.com/openiddict/openiddict-core/releases/

OpenIddict will probably have one RC in November. As usual, the final version is planned for December, one or two weeks before Christmas.

**Comment by ebicoglu** [comment]
[openiddict 6.0.0-preview1](https://github.com/openiddict/openiddict-core/releases/tag/6.0.0-preview3)

**Comment by maliming** [comment]
https://kevinchalet.com/2024/12/17/openiddict-6-0-general-availability/
