### ISSUE TITLE
Datatable fnSetColumnVis legacy method usage issue

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#20970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm getting "tableInstance.fnSetColumnVis is not a function at hideColumnWithoutRedraw" error when there is only 1 rowAction item and its visibility is related to a permission check. If the user doesn't have that permission error occurs. I think root of the error is related to fnSetColumnVis legacy datatable method used in [datatables-extensions.js].(https://github.com/abpframework/abp/blob/6a810dbed50f8b8d9a8e0914f56825ac6922ef20/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L229). 

### Reproduction Steps

```js
    columnDefs: [
            {
                title: "",
                rowAction: {
                    items:
                        [
                            {
                                text: 'Edit',
                                visible: function (data) {
                                    return abp.auth.isGranted('Acme.Test.Edit')
                                },
                                action: function (data) {
                                    editModal.open({ id: data.record.id });
                                }
                            },
                        ]
                }
            },
            {
                title: 'Test',
                data: "test"
            }
]
```

### Version

8.3.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

What is the package version in your `packages.json` file?

**Comment by muhlisatac** [comment]
"@abp/aspnetcore.mvc.ui.theme.shared": "~8.3.1",

**Comment by maliming** [comment]
Thanks,Can you share a test project?

**Comment by muhlisatac** [comment]
https://we.tl/t-rr5jNDkzqp . Just remove book update permission from the admin role then look at the books page.

**Comment by realLiangshiwei** [comment]
@muhlisatac 

Hi, could you share the project again?
<img width="550" alt="image" src="https://github.com/user-attachments/assets/afbbcd83-b6aa-4942-99b1-ead400fc553c">

**Comment by muhlisatac** [comment]
https://we.tl/t-ttRvq66TF7. Sure here you are.

**Comment by realLiangshiwei** [comment]
HI @muhlisatac 
Sorry I was a little busy before, could you share again. thanks
