### ISSUE TITLE
`ABP Studio`  cannot install the solution templates

### ISSUE THREAD

**Issue by izanhzh** [abpframework/abp#20978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Same issue as https://github.com/abpframework/abp/issues/20905

Log:
```
11:57:55.750 	 Information  	 Starting task execution: "Loading extensions"
11:57:55.760 	 Warning      	 "Volo.Abp.Studio.Extensions.StandardSolutionTemplates" extension not found in the NuGet cache. Directory: "C:\Users\xxx\.nuget\packages\volo.abp.studio.extensions.standardsolutiontemplates\0.8.3\lib\net8.0"
11:57:56.111 	 Warning      	 Extension 'Volo.Abp.Studio.Extensions.StandardSolutionTemplates.Core.dll' is not loaded! Path: C:\Users\xxx\AppData\Local\abp-studio\current\Volo.Abp.Studio.Extensions.StandardSolutionTemplates.Core.dll.
11:57:56.111 	 Warning      	 Extension 'Volo.Abp.Studio.Extensions.StandardSolutionTemplates.UI.dll' is not loaded! Path: C:\Users\xxx\AppData\Local\abp-studio\current\Volo.Abp.Studio.Extensions.StandardSolutionTemplates.UI.dll.
11:57:56.114 	 Information  	 Completed task execution: "Loading extensions"
```

I think it is because I changed the `Nuget.Config`  `globalPackagesFolder` value, which is no longer in the C disk.

https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

### Version

0.8.3

### Operation System

Windows (Default)

**Comment by iamjjt** [comment]
I also have the same problem, and I can't create templates using cli too。 The error is the same as yours。

**Comment by izanhzh** [comment]
@iamjjt finally, instead of modifying Nuget.config, I set the relevant custom paths to Nuget via environment variables, and now `ABP Studio` works
![image](https://github.com/user-attachments/assets/902948fc-d548-428e-9e6d-37a2076d2087)

**Comment by XUGUI-CTOR** [comment]
Thank you for your solution.
