### ISSUE TITLE
ABPCLI problem, "--version 'dev'" uses outdated cached template

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#2098]
Since the branches doesn't have version, that should be downloaded per request and not used the cached versions.

**Comment by hikalkan** [comment]
You're right and #2101 solves it. However, we have more serious problem if we disable caching. Every time our server will download a huge repository which will make our server slower and also will use a huge bandwidth. So, I want to delay this issue & solution to think on it later.

**Comment by hitaspdotnet** [comment]
For similar problems, I solve this for now by deleting 'C:\Users\$USER\.abp\templates' cached template.
