### ISSUE TITLE
Optimistic concurrency failure, object has been modified.

### ISSUE THREAD

**Issue by maomaoispan** [abpframework/abp#2099]
I ceate a test project  using 'abp new TestApi -ui angular' cmd.
It tip 'Optimistic concurrency failure, object has been modified.' when i edit user or role.

**Comment by hikalkan** [comment]
Please write steps to reproduce the problem, because it normally works.

**Comment by maomaoispan** [comment]
### 1. first step 
 D:\Dev\Note\abp\04> abp new TestApi -ui angular
[17:31:50 INF] ABP CLI (https://abp.io)
[17:31:53 INF] Version 1.0.0 (Stable channel)
[17:31:54 WRN] ABP CLI has a newer stable version 1.0.2, please update to get the latest features and fixes.
[17:31:54 WRN]
[17:31:54 WRN] Update Command:
[17:31:54 WRN] dotnet tool update -g Volo.Abp.Cli
[17:31:54 WRN]
[17:31:54 INF] Creating your project...
[17:31:54 INF] Project name: TestApi
[17:31:54 INF] UI Framework: Angular
[17:31:54 INF] Output folder: D:\Dev\Note\abp\04
[17:31:56 INF] Using cached template: app, version: 1.0.2
[17:31:59 INF] Check out the documents at https://docs.abp.io/en/abp/latest/Startup-Templates/Application
[17:32:04 INF] 'TestApi' has been successfully created to 'D:\Dev\Note\abp\04'
PS D:\Dev\Note\abp\04> cd .\angular\
PS D:\Dev\Note\abp\04\angular> yarn
yarn install v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "win32" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@abp/ng.account > @abp/ng.theme.shared > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "@abp/ng.account > @abp/ng.theme.shared > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "@abp/ng.account > @abp/ng.theme.shared > @abp/ng.core@1.0.2" has incorrect peer dependency "@angular/common@~8.1.2".
warning "@abp/ng.account > @abp/ng.theme.shared > @abp/ng.core@1.0.2" has incorrect peer dependency "@angular/core@~8.1.2".
warning "@abp/ng.account > @abp/ng.theme.shared > @abp/ng.core@1.0.2" has incorrect peer dependency "@angular/forms@~8.1.2".
warning "@abp/ng.account > @abp/ng.theme.shared > @abp/ng.core@1.0.2" has incorrect peer dependency "@angular/router@~8.1.2".
warning " > @ngxs/logger-plugin@3.5.1" has unmet peer dependency "@ngxs/store@^3.5.1 || ^3.5.1-dev".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 47.86s.
PS D:\Dev\Note\abp\04\angular> yarn start                                                                               yarn run v1.19.1
$ ng serve
10% building 8/8 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {0} 0.js, 0.js.map () 7.71 kB  [rendered]
chunk {1} 1.js, 1.js.map () 8.72 kB  [rendered]
chunk {2} 2.js, 2.js.map () 13.8 kB  [rendered]
chunk {3} 3.js, 3.js.map () 9.31 kB  [rendered]
chunk {4} 4.js, 4.js.map () 9.27 kB  [rendered]
chunk {5} 5.js, 5.js.map () 7.31 kB  [rendered]
chunk {6} 6.js, 6.js.map () 14.3 kB  [rendered]
chunk {7} 7.js, 7.js.map () 11.8 kB  [rendered]
chunk {8} 8.js, 8.js.map () 13 kB  [rendered]
chunk {9} 9.js, 9.js.map () 12.2 kB  [rendered]
chunk {10} 10.js, 10.js.map () 12.1 kB  [rendered]
chunk {11} 11.js, 11.js.map () 10.4 kB  [rendered]
chunk {12} 12.js, 12.js.map () 10.3 kB  [rendered]
chunk {13} 13.js, 13.js.map () 8.33 kB  [rendered]
chunk {14} 14.js, 14.js.map () 10.6 kB  [rendered]
chunk {15} 15.js, 15.js.map () 11.1 kB  [rendered]
chunk {16} 16.js, 16.js.map () 9.71 kB  [rendered]
chunk {17} 17.js, 17.js.map () 11.4 kB  [rendered]
chunk {18} 18.js, 18.js.map () 6.89 kB  [rendered]
chunk {19} 19.js, 19.js.map () 9.88 kB  [rendered]
chunk {20} 20.js, 20.js.map () 7.75 kB  [rendered]
chunk {21} 21.js, 21.js.map () 7.52 kB  [rendered]
chunk {22} 22.js, 22.js.map () 11.7 kB  [rendered]
chunk {23} 23.js, 23.js.map () 9.16 kB  [rendered]
chunk {24} 24.js, 24.js.map () 9.16 kB  [rendered]
chunk {25} 25.js, 25.js.map () 7.54 kB  [rendered]
chunk {26} 26.js, 26.js.map () 10.1 kB  [rendered]
chunk {27} 27.js, 27.js.map () 7.5 kB  [rendered]
chunk {28} 28.js, 28.js.map () 3.68 kB  [rendered]
chunk {29} 29.js, 29.js.map () 4.57 kB  [rendered]
chunk {30} 30.js, 30.js.map () 6.03 kB  [rendered]
chunk {31} 31.js, 31.js.map () 2.46 kB  [rendered]
chunk {32} 32.js, 32.js.map () 4.37 kB  [rendered]
chunk {33} 33.js, 33.js.map () 2.47 kB  [rendered]
chunk {34} 34.js, 34.js.map () 2.46 kB  [rendered]
chunk {35} 35.js, 35.js.map () 4.99 kB  [rendered]
chunk {36} 36.js, 36.js.map () 4.63 kB  [rendered]
chunk {37} 37.js, 37.js.map () 3.33 kB  [rendered]
chunk {38} 38.js, 38.js.map () 3.3 kB  [rendered]
chunk {39} 39.js, 39.js.map () 4.13 kB  [rendered]
chunk {40} 40.js, 40.js.map () 4.05 kB  [rendered]
chunk {41} 41.js, 41.js.map () 3.3 kB  [rendered]
chunk {42} 42.js, 42.js.map () 4.51 kB  [rendered]
chunk {43} 43.js, 43.js.map () 4.14 kB  [rendered]
chunk {44} 44.js, 44.js.map () 3.73 kB  [rendered]
chunk {45} 45.js, 45.js.map () 3.83 kB  [rendered]
chunk {46} 46.js, 46.js.map () 2.47 kB  [rendered]
chunk {47} 47.js, 47.js.map () 3.38 kB  [rendered]
chunk {48} 48.js, 48.js.map () 3.98 kB  [rendered]
chunk {49} 49.js, 49.js.map () 3.96 kB  [rendered]
chunk {50} 50.js, 50.js.map () 3.81 kB  [rendered]
chunk {51} 51.js, 51.js.map () 3.81 kB  [rendered]
chunk {52} 52.js, 52.js.map () 3.49 kB  [rendered]
chunk {53} 53.js, 53.js.map () 3.63 kB  [rendered]
chunk {54} 54.js, 54.js.map () 4.74 kB  [rendered]
chunk {55} 55.js, 55.js.map () 2.47 kB  [rendered]
chunk {56} 56.js, 56.js.map () 4.36 kB  [rendered]
chunk {57} 57.js, 57.js.map () 5 kB  [rendered]
chunk {58} 58.js, 58.js.map () 4.61 kB  [rendered]
chunk {59} 59.js, 59.js.map () 4.09 kB  [rendered]
chunk {60} 60.js, 60.js.map () 2.47 kB  [rendered]
chunk {61} 61.js, 61.js.map () 2.46 kB  [rendered]
chunk {62} 62.js, 62.js.map () 2.46 kB  [rendered]
chunk {63} 63.js, 63.js.map () 3.68 kB  [rendered]
chunk {64} 64.js, 64.js.map () 3.96 kB  [rendered]
chunk {65} 65.js, 65.js.map () 4.74 kB  [rendered]
chunk {66} 66.js, 66.js.map () 2.46 kB  [rendered]
chunk {67} 67.js, 67.js.map () 5.48 kB  [rendered]
chunk {68} 68.js, 68.js.map () 4.09 kB  [rendered]
chunk {69} 69.js, 69.js.map () 3.85 kB  [rendered]
chunk {70} 70.js, 70.js.map () 3.86 kB  [rendered]
chunk {71} 71.js, 71.js.map () 4.58 kB  [rendered]
chunk {72} 72.js, 72.js.map () 3.29 kB  [rendered]
chunk {73} 73.js, 73.js.map () 2.46 kB  [rendered]
chunk {74} 74.js, 74.js.map () 4.34 kB  [rendered]
chunk {75} 75.js, 75.js.map () 3.65 kB  [rendered]
chunk {76} 76.js, 76.js.map () 3.39 kB  [rendered]
chunk {77} 77.js, 77.js.map () 4.63 kB  [rendered]
chunk {78} 78.js, 78.js.map () 2.47 kB  [rendered]
chunk {79} 79.js, 79.js.map () 2.47 kB  [rendered]
chunk {80} 80.js, 80.js.map () 4.4 kB  [rendered]
chunk {81} 81.js, 81.js.map () 4.13 kB  [rendered]
chunk {82} 82.js, 82.js.map () 4.45 kB  [rendered]
chunk {83} 83.js, 83.js.map () 3.39 kB  [rendered]
chunk {84} 84.js, 84.js.map () 2.47 kB  [rendered]
chunk {85} 85.js, 85.js.map () 2.46 kB  [rendered]
chunk {86} 86.js, 86.js.map () 3.6 kB  [rendered]
chunk {87} 87.js, 87.js.map () 4.44 kB  [rendered]
chunk {88} 88.js, 88.js.map () 2.47 kB  [rendered]
chunk {89} 89.js, 89.js.map () 5.92 kB  [rendered]
chunk {90} 90.js, 90.js.map () 5.9 kB  [rendered]
chunk {91} 91.js, 91.js.map () 3.36 kB  [rendered]
chunk {92} 92.js, 92.js.map () 5.23 kB  [rendered]
chunk {93} 93.js, 93.js.map () 4.01 kB  [rendered]
chunk {94} 94.js, 94.js.map () 2.46 kB  [rendered]
chunk {95} 95.js, 95.js.map () 4.56 kB  [rendered]
chunk {96} 96.js, 96.js.map () 3.72 kB  [rendered]
chunk {97} 97.js, 97.js.map () 3.5 kB  [rendered]
chunk {98} 98.js, 98.js.map () 3.48 kB  [rendered]
chunk {99} 99.js, 99.js.map () 2.46 kB  [rendered]
chunk {100} 100.js, 100.js.map () 2.46 kB  [rendered]
chunk {101} 101.js, 101.js.map () 2.5 kB  [rendered]
chunk {102} 102.js, 102.js.map () 4.36 kB  [rendered]
chunk {103} 103.js, 103.js.map () 4.32 kB  [rendered]
chunk {104} 104.js, 104.js.map () 4.54 kB  [rendered]
chunk {105} 105.js, 105.js.map () 3.93 kB  [rendered]
chunk {106} 106.js, 106.js.map () 3.62 kB  [rendered]
chunk {107} 107.js, 107.js.map () 4.59 kB  [rendered]
chunk {108} 108.js, 108.js.map () 4.54 kB  [rendered]
chunk {109} 109.js, 109.js.map () 2.46 kB  [rendered]
chunk {110} 110.js, 110.js.map () 2.47 kB  [rendered]
chunk {111} 111.js, 111.js.map () 2.5 kB  [rendered]
chunk {112} 112.js, 112.js.map () 2.47 kB  [rendered]
chunk {113} 113.js, 113.js.map () 4.82 kB  [rendered]
chunk {114} 114.js, 114.js.map () 4.84 kB  [rendered]
chunk {115} 115.js, 115.js.map () 4.74 kB  [rendered]
chunk {116} 116.js, 116.js.map () 2.47 kB  [rendered]
chunk {117} 117.js, 117.js.map () 3.94 kB  [rendered]
chunk {118} 118.js, 118.js.map () 4.33 kB  [rendered]
chunk {119} 119.js, 119.js.map () 4.05 kB  [rendered]
chunk {120} 120.js, 120.js.map () 3.86 kB  [rendered]
chunk {121} 121.js, 121.js.map () 4.89 kB  [rendered]
chunk {122} 122.js, 122.js.map () 4.86 kB  [rendered]
chunk {123} 123.js, 123.js.map () 5.9 kB  [rendered]
chunk {124} 124.js, 124.js.map () 3.47 kB  [rendered]
chunk {125} 125.js, 125.js.map () 2.46 kB  [rendered]
chunk {126} 126.js, 126.js.map () 5.88 kB  [rendered]
chunk {127} 127.js, 127.js.map () 2.46 kB  [rendered]
chunk {128} 128.js, 128.js.map () 2.46 kB  [rendered]
chunk {129} 129.js, 129.js.map () 4.6 kB  [rendered]
chunk {130} 130.js, 130.js.map () 2.46 kB  [rendered]
chunk {131} 131.js, 131.js.map () 2.46 kB  [rendered]
chunk {132} 132.js, 132.js.map () 4.02 kB  [rendered]
chunk {133} 133.js, 133.js.map () 4.15 kB  [rendered]
chunk {134} 134.js, 134.js.map () 3.35 kB  [rendered]
chunk {135} 135.js, 135.js.map () 2.5 kB  [rendered]
chunk {136} 136.js, 136.js.map () 4.33 kB  [rendered]
chunk {137} 137.js, 137.js.map () 2.46 kB  [rendered]
chunk {138} 138.js, 138.js.map () 2.46 kB  [rendered]
chunk {139} 139.js, 139.js.map () 4.11 kB  [rendered]
chunk {140} 140.js, 140.js.map () 3.49 kB  [rendered]
chunk {141} 141.js, 141.js.map () 3.28 kB  [rendered]
chunk {142} 142.js, 142.js.map () 9.67 kB  [rendered]
chunk {143} 143.js, 143.js.map () 17 kB  [rendered]
chunk {144} 144.js, 144.js.map () 11 kB  [rendered]
chunk {145} 145.js, 145.js.map () 12.2 kB  [rendered]
chunk {146} 146.js, 146.js.map () 6.99 kB  [rendered]
chunk {147} 147.js, 147.js.map () 8.26 kB  [rendered]
chunk {148} 148.js, 148.js.map () 9.87 kB  [rendered]
chunk {149} 149.js, 149.js.map () 10.8 kB  [rendered]
chunk {150} 150.js, 150.js.map () 7.23 kB  [rendered]
chunk {151} 151.js, 151.js.map () 9.71 kB  [rendered]
chunk {152} 152.js, 152.js.map () 7.13 kB  [rendered]
chunk {153} 153.js, 153.js.map () 9.44 kB  [rendered]
chunk {154} 154.js, 154.js.map () 9.29 kB  [rendered]
chunk {155} 155.js, 155.js.map () 13.7 kB  [rendered]
chunk {156} 156.js, 156.js.map () 9 kB  [rendered]
chunk {157} 157.js, 157.js.map () 10.3 kB  [rendered]
chunk {158} 158.js, 158.js.map () 7.45 kB  [rendered]
chunk {159} 159.js, 159.js.map () 7.15 kB  [rendered]
chunk {160} 160.js, 160.js.map () 9.7 kB  [rendered]
chunk {161} 161.js, 161.js.map () 8.67 kB  [rendered]
chunk {162} 162.js, 162.js.map () 6.44 kB  [rendered]
chunk {163} 163.js, 163.js.map () 10.4 kB  [rendered]
chunk {164} 164.js, 164.js.map () 7.49 kB  [rendered]
chunk {165} 165.js, 165.js.map () 7.78 kB  [rendered]
chunk {166} 166.js, 166.js.map () 11.2 kB  [rendered]
chunk {167} 167.js, 167.js.map () 7.65 kB  [rendered]
chunk {168} 168.js, 168.js.map () 12.1 kB  [rendered]
chunk {169} 169.js, 169.js.map () 6.55 kB  [rendered]
chunk {170} 170.js, 170.js.map () 7.4 kB  [rendered]
chunk {171} 171.js, 171.js.map () 9.77 kB  [rendered]
chunk {172} 172.js, 172.js.map () 12.7 kB  [rendered]
chunk {173} 173.js, 173.js.map () 11 kB  [rendered]
chunk {174} 174.js, 174.js.map () 7.59 kB  [rendered]
chunk {175} 175.js, 175.js.map () 11.8 kB  [rendered]
chunk {176} 176.js, 176.js.map () 11.3 kB  [rendered]
chunk {177} 177.js, 177.js.map () 8.62 kB  [rendered]
chunk {178} 178.js, 178.js.map () 9.45 kB  [rendered]
chunk {179} 179.js, 179.js.map () 7.28 kB  [rendered]
chunk {180} 180.js, 180.js.map () 10.5 kB  [rendered]
chunk {181} 181.js, 181.js.map () 10.5 kB  [rendered]
chunk {182} 182.js, 182.js.map () 10.2 kB  [rendered]
chunk {183} 183.js, 183.js.map () 8.42 kB  [rendered]
chunk {184} 184.js, 184.js.map () 8.43 kB  [rendered]
chunk {185} 185.js, 185.js.map () 11.4 kB  [rendered]
chunk {186} 186.js, 186.js.map () 8.48 kB  [rendered]
chunk {187} 187.js, 187.js.map () 6.38 kB  [rendered]
chunk {188} 188.js, 188.js.map () 9.51 kB  [rendered]
chunk {189} 189.js, 189.js.map () 9.47 kB  [rendered]
chunk {190} 190.js, 190.js.map () 13.5 kB  [rendered]
chunk {191} 191.js, 191.js.map () 8.62 kB  [rendered]
chunk {192} 192.js, 192.js.map () 8.25 kB  [rendered]
chunk {193} 193.js, 193.js.map () 10 kB  [rendered]
chunk {194} 194.js, 194.js.map () 13.9 kB  [rendered]
chunk {195} 195.js, 195.js.map () 7.14 kB  [rendered]
chunk {196} 196.js, 196.js.map () 6.94 kB  [rendered]
chunk {197} 197.js, 197.js.map () 7.03 kB  [rendered]
chunk {198} 198.js, 198.js.map () 9.15 kB  [rendered]
chunk {199} 199.js, 199.js.map () 13.1 kB  [rendered]
chunk {200} 200.js, 200.js.map () 10.7 kB  [rendered]
chunk {201} 201.js, 201.js.map () 9.36 kB  [rendered]
chunk {202} 202.js, 202.js.map () 8.91 kB  [rendered]
chunk {203} 203.js, 203.js.map () 9.78 kB  [rendered]
chunk {204} 204.js, 204.js.map () 11.5 kB  [rendered]
chunk {205} 205.js, 205.js.map () 11.2 kB  [rendered]
chunk {206} 206.js, 206.js.map () 8.02 kB  [rendered]
chunk {207} 207.js, 207.js.map () 10.7 kB  [rendered]
chunk {208} 208.js, 208.js.map () 7.71 kB  [rendered]
chunk {209} 209.js, 209.js.map () 9.15 kB  [rendered]
chunk {210} 210.js, 210.js.map () 9.33 kB  [rendered]
chunk {211} 211.js, 211.js.map () 7.74 kB  [rendered]
chunk {212} 212.js, 212.js.map () 9.12 kB  [rendered]
chunk {213} 213.js, 213.js.map () 9.15 kB  [rendered]
chunk {214} 214.js, 214.js.map () 10.1 kB  [rendered]
chunk {215} 215.js, 215.js.map () 7.43 kB  [rendered]
chunk {216} 216.js, 216.js.map () 7.82 kB  [rendered]
chunk {217} 217.js, 217.js.map () 7.61 kB  [rendered]
chunk {218} 218.js, 218.js.map () 13.8 kB  [rendered]
chunk {219} 219.js, 219.js.map () 7.16 kB  [rendered]
chunk {220} 220.js, 220.js.map () 8.48 kB  [rendered]
chunk {221} 221.js, 221.js.map () 6.17 kB  [rendered]
chunk {222} 222.js, 222.js.map () 9.21 kB  [rendered]
chunk {223} 223.js, 223.js.map () 6.7 kB  [rendered]
chunk {224} 224.js, 224.js.map () 8.05 kB  [rendered]
chunk {225} 225.js, 225.js.map () 7.76 kB  [rendered]
chunk {226} 226.js, 226.js.map () 6.89 kB  [rendered]
chunk {227} 227.js, 227.js.map () 9.81 kB  [rendered]
chunk {chart-js} chart-js.js, chart-js.js.map (chart-js) 1020 kB  [rendered]
chunk {fontawesome-all.min} fontawesome-all.min.css, fontawesome-all.min.css.map (fontawesome-all.min) 56.8 kB [initial] [rendered]
chunk {fontawesome-v4-shims.min} fontawesome-v4-shims.min.css, fontawesome-v4-shims.min.css.map (fontawesome-v4-shims.min) 26.5 kB [initial] [rendered]
chunk {home-home-module} home-home-module.js, home-home-module.js.map (home-home-module) 6.69 kB  [rendered]
chunk {lazy-libs-account-wrapper-module} lazy-libs-account-wrapper-module.js, lazy-libs-account-wrapper-module.js.map (lazy-libs-account-wrapper-module) 41.2 kB  [rendered]
chunk {lazy-libs-identity-wrapper-module} lazy-libs-identity-wrapper-module.js, lazy-libs-identity-wrapper-module.js.map (lazy-libs-identity-wrapper-module) 91.6 kB  [rendered]
chunk {lazy-libs-setting-management-wrapper-module} lazy-libs-setting-management-wrapper-module.js, lazy-libs-setting-management-wrapper-module.js.map (lazy-libs-setting-management-wrapper-module) 11.9 kB  [rendered]
chunk {lazy-libs-tenant-management-wrapper-module} lazy-libs-tenant-management-wrapper-module.js, lazy-libs-tenant-management-wrapper-module.js.map (lazy-libs-tenant-management-wrapper-module) 57.6 kB  [rendered]
chunk {main} main.js, main.js.map (main) 52.9 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 290 kB [initial] [rendered]
chunk {primeicons} primeicons.css, primeicons.css.map (primeicons) 9.77 kB [initial] [rendered]
chunk {primeng-nova-light-theme} primeng-nova-light-theme.css, primeng-nova-light-theme.css.map (primeng-nova-light-theme) 99.5 kB [initial] [rendered]
chunk {primeng.min} primeng.min.css, primeng.min.css.map (primeng.min) 81.4 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.34 kB [entry] [rendered]
chunk {styles} styles.css, styles.css.map (styles) 154 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.41 MB [initial] [rendered]
Date: 2019-11-06T09:34:58.410Z - Hash: 2ae5edfd2df3ebcfbbaa - Time: 17047ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled successfully.


### 2. open vs ,set TestApi.DbMigrator as startup project and F5

[17:34:59 INF] Started database migrations...
[17:34:59 INF] Migrating database schema...
[17:35:03 INF] Executing database seed...
[17:35:06 INF] Successfully completed database migrations.

D:\Dev\Note\abp\04\aspnet-core\src\TestApi.DbMigrator\bin\Debug\netcoreapp3.0\TestApi.DbMigrator.exe (进程 27052)已退出 ，返回代码为: 0。
若要在调试停止时自动关闭控制台，请启用“工具”->“选项”->“调试”->“调试停止时自动关闭控制台”。
按任意键关闭此窗口...

### 3. set TestApi.HttpApi.Host as startup project and F5
brownser opened https://localhost:44304/ everything is ok;

### 4. open localhost:4200
login->
edit user info ->change user "surname":"aaa"

tooltip:'Optimistic concurrency failure, object has been modified.'


debug:
Request URL: https://localhost:44304/api/identity/users/945d9413-315a-5eb8-2e47-39f1523e1d71
Request Method: PUT
Status Code: 403 
Remote Address: [::1]:44304
Referrer Policy: no-referrer-when-downgrade
:authority: localhost:44304
:method: PUT
:path: /api/identity/users/945d9413-315a-5eb8-2e47-39f1523e1d71
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlYjg2M2IyNTgxMWE3MDk5ZjliYzkyNWMwZmRmNjgwIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE1NzMwMzMxNTksImV4cCI6MTYwNDU2OTE1OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMDQiLCJhdWQiOiJUZXN0QXBpIiwiY2xpZW50X2lkIjoiVGVzdEFwaV9BcHAiLCJzdWIiOiI5NDVkOTQxMy0zMTVhLTVlYjgtMmU0Ny0zOWYxNTIzZTFkNzEiLCJhdXRoX3RpbWUiOjE1NzMwMzMxNTksImlkcCI6ImxvY2FsIiwicm9sZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhYnAuaW8iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInNjb3BlIjpbIlRlc3RBcGkiXSwiYW1yIjpbInB3ZCJdfQ.cbsJJrXYy-Mg7baWH5-omIR67iAg1fFUq8HKXeNbgF0C898ohGCCHzhuwo71VCk1SCKZ5TtRkAL73ruR3QByEZGESZj6iW8Rhbp66Z3Q6GFphJDBbzwpNcyO1tjvjc2MNdljB_hV6_nV9p7Q4EUSHwes7CdIqTfrqCdalr8WPWaGysCfXGTj9d0EQjgeV6pvEj7N4YM45lK7Iv_5G7QUHf4Qm96fDX-wjE_jZlORjzex__pmUBK1FEhv1xO0KCpVc7JBt5uLgfcdTjVfX2bcuhpy6UVEmX_4-JEyMFzRlsR_BV35bh3rx4SP16wQn7ZwpUO4zbcP7yaIIsKeZkiS3A
content-length: 507
content-type: application/json
origin: http://localhost:4200
referer: http://localhost:4200/identity/users
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36

{"tenantId":null,"userName":"admin","name":"admin","surname":"aaa","email":"admin@abp.io","emailConfirmed":false,"phoneNumber":"","phoneNumberConfirmed":false,"twoFactorEnabled":false,"lockoutEnabled":false,"lockoutEnd":null,"concurrencyStamp":"6450c7be04fa4e0e9d8ad3947dd01ae2","isDeleted":false,"deleterId":null,"deletionTime":null,"lastModificationTime":"2019-11-06T17:35:04.7346486","lastModifierId":null,"creationTime":"2019-11-06T17:35:04.2827001","creatorId":null,"roleNames":["admin"],"password":""}

**Comment by mehmet-erim** [comment]
Already fixed. See the [commit](https://github.com/abpframework/abp/commit/878d39c993e85c8d25a2932f776e0d0a850b694a)
