### ISSUE TITLE
Entity history / audit log improvements

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2100]
- [x] Disable property auditing for FullAuditedEntity (and others) base properties like CreationTime, LastModificationTime, IsDeleted... etc. - implemented by https://github.com/abpframework/abp/pull/4516
- [ ] Allow to enable auditing of some selected properties of an entity while other property changes are not saved (this will make easy to track a few property of a class that has too many properties).

**Comment by iyilm4z** [comment]
@hikalkan if i understood the issue correctly, we need this improvement because we already save props of FullAuditedEntity in it's own table while creating(CreationTime, CreatorUserId) and updating(LastModificationTime, LastModifierUserId) and deleting(DeletionTime, DeleterUserId, IsDeleted).
 
Without this improvement we will keep saving the same data(FullAuditedEntity props) in two different tables (AbpEntityPropertyChanges and entity' own table).  So it's better to make it optional for users.

Am i right? If i'm not, could you please explain why we need this improvement?

**Comment by hikalkan** [comment]
Yes, you got it right (for the first part).
For example, when we create a new entity, it sets its creating time on the entity, so no need to write it to the AbpEntityPropertyChanges table. Other fields are also similar. But if you find any different case, write here.

**Comment by iyilm4z** [comment]
@hikalkan I would like to share with you what i've experimentally done. It works but there is a limitation of this implementation which is we enable or disable ignored properties for all audited entities, not for specific ones. I think we need more flexible api to make users able to choose disabling/enabling for specific entity types. Also i'm not sure if this implementation follows your codding conventions or not.

**_Below is first requirement of the issue._**

**Step#1**: add a list for ignored properties and initialize them with names of properties which needed to be ignored as default(auditing properties)

```csharp
public class AbpAuditingOptions {
    public List<string> IgnoredProperties { get; set; }

    public AbpAuditingOptions () {
        IgnoredProperties = new List<string> {
            nameof (ICreationAuditedObject.CreatorId),
            nameof (ICreationAuditedObject.CreationTime),
            nameof (IModificationAuditedObject.LastModifierId),
            nameof (IModificationAuditedObject.LastModificationTime),
            nameof (IDeletionAuditedObject.DeleterId),
            nameof (IDeletionAuditedObject.DeletionTime),
            nameof (IDeletionAuditedObject.IsDeleted)
        };
    }
}
```

**Step#2**: check if current property of the entity is one of  ignored properties, if so skip it
```csharp
public class EntityHistoryHelper : IEntityHistoryHelper, ITransientDependency {

    private bool ShouldSavePropertyHistory (PropertyEntry propertyEntry, bool defaultValue) {
        // ...
        
        if (Options.IgnoredProperties.Contains (propertyEntry.Metadata.Name)) {
            return false;
        }

        // ...
    }
}
```
**_Below is second requirement of the issue._**

**Step#2**: enable auditing for any propery by removing the name of it from IgnoredProperties list via charp api.
```csharp
public class MyModuleModule : AbpModule {
    public override void ConfigureServices (ServiceConfigurationContext context) {
        options.IgnoredProperties.Remove (nameof (IModificationAuditedObject.LastModifierId));
    }
}
```

**Comment by iyilm4z** [comment]
@hikalkan any idea?:)

**Comment by hikalkan** [comment]
For the first requirement;
I think selecting the ignored properties by naming (just string) is not a good idea. It should be type safe. If a class has `CreationTime` but not implements `ICreationAudited` should be audit logged, because framework has no idea about this `CreationTime`.
A solution could be adding `[DisableAuditLogging]` attribute to base entity/aggregateroot classes. 

1 & 2 is completely independent, you got it wrong.

>Allow to enable auditing of some selected properties of an entity while other property changes are not saved (this will make easy to track a few property of a class that has too many properties).

We use [Audited] for an entity and [IgnoreAuditing] for those properties we don't want to log. This makes hard if we want to log only 2 properties of an entity with 100 properties (we should add IgnoreAuditing to 98 properties). So, find a design and implement it.

**Comment by iyilm4z** [comment]
@hikalkan  thanks for your response.

> I think selecting the ignored properties by naming (just string) is not a good idea. It should be type safe.

That's definitely true! 


> So, find a design and implement it.


Ok, i'll try.

**Comment by iyilm4z** [comment]
@hikalkan for the first requirement i did as you said below.
> A solution could be adding `[DisableAuditLogging]` attribute to base entity/aggregateroot classes.

for the second requirement, i designed something like below, it's more type-safe and working, i tested it with AbpEntityFrameworkCoreTestModule, you can also try it just by doing a copy&paste codes below.
As you said if an entity has 100+ props, this code only saves selected props to db.  I'm not sure about priority/order of my checking-code blocks.

```csharp

public class AbpAuditingOptions {
    public List<PropertyInfo> AuditedProperties { get; }

    public AbpAuditingOptions () {
        AuditedProperties = new List<PropertyInfo> ();
    }
}

public static class AbpAuditingOptionsExtensions {
    // This method is so generic, it should be moved into 
    // a class in Reflection folder of Core module.
    private static PropertyInfo[] GetPropertyInfos<T> (
        [NotNull] params Expression<Func<T, object>>[] propertySelectors)
    where T : class {
        Check.NotNull (propertySelectors, nameof (propertySelectors));

        if (propertySelectors.IsNullOrEmpty ())
            return Array.Empty<PropertyInfo> ();

        var infos = new List<PropertyInfo> ();
        foreach (var selector in propertySelectors) {
            var member = GetMemberExpression (selector);
            if (member?.Member is PropertyInfo info)
                infos.AddIfNotContains (info);
        }
        return infos.ToArray ();
    }

    // This method is so generic, it should be moved into 
    // a class in Reflection folder of Core module.
    private static MemberExpression GetMemberExpression<T> (
        Expression<Func<T, object>> expression) {
        var member = expression.Body as MemberExpression;
        var unary = expression.Body as UnaryExpression;
        return member ?? unary?.Operand as MemberExpression;
    }

    public static void AddAuditedProperties<TEntity> (
        this AbpAuditingOptions options, [NotNull] params Expression<Func<TEntity, object>>[] propertySelectors)
    where TEntity : class {
        Check.NotNull (propertySelectors, nameof (propertySelectors));

        options.AuditedProperties.AddRange (GetPropertyInfos (propertySelectors));
    }
}

public class EntityHistoryHelper : IEntityHistoryHelper, ITransientDependency {
    private bool ShouldSaveEntityHistory (EntityEntry entityEntry, bool defaultValue = false) {
        //existing codes here...

        var properties = entityEntry.Metadata.GetProperties ();
        if (properties.Any (p => p.PropertyInfo?.IsDefined (typeof (AuditedAttribute)) ?? false)) {
            return true;
        }
        if (!Options.AuditedProperties.IsNullOrEmpty () &&
            Options.AuditedProperties.Any (pi => properties.Any (p => pi.DeclaringType == p.PropertyInfo.DeclaringType && pi.Name == p.PropertyInfo.Name))) {
            return true;
        }
        return defaultValue;
    }
    private bool ShouldSavePropertyHistory (PropertyEntry propertyEntry, bool defaultValue) {
        //existing codes here...

        var propertyInfo = propertyEntry.Metadata.PropertyInfo;
        if (propertyInfo != null && propertyInfo.IsDefined (typeof (DisableAuditingAttribute), true)) {
            return false;
        }

        //existing codes here...

        if (!Options.AuditedProperties.IsNullOrEmpty () &&
            !Options.AuditedProperties.Any (pi => pi.DeclaringType == propertyInfo.DeclaringType && pi.Name == propertyInfo.Name)) {
            return false;
        }

        //existing codes here...

        return defaultValue;
    }
}

public class AbpEntityFrameworkCoreTestModule : AbpModule {
    public override void ConfigureServices (ServiceConfigurationContext context) {
        Configure<AbpAuditingOptions> (options => {
            options.AddAuditedProperties<Person> (p => p.Name, p.CityId);
        });
    }
}

```

**Comment by iyilm4z** [comment]
@hikalkan 

> A solution could be adding `[DisableAuditLogging]` attribute to base entity/aggregateroot classes.

I'm not sure but i think that using disable auditing attribute couldn't be working if want to be able to do the scenario in your statement below.

> If a class has `CreationTime` but not implements `ICreationAudited` should be audit logged, because framework has no idea about this `CreationTime`.

That's why i wrote method below which does exactly what we want  to have. I also think, this method looks so generic and we may move it somewhere relevant to have dry principle.

I use this method in EntityHistoryHelper.ShouldSavePropertyHistory to determine if a property one of those base auditing properties, if so i pass to store propery change.

```csharp
private bool IsBaseAuditProperty(PropertyInfo propertyInfo, Type entityType)
{
    if (entityType.IsAssignableTo<IHasCreationTime>()
        && propertyInfo.Name == nameof(IHasCreationTime.CreationTime))
    {
        return true;
    }
    if (entityType.IsAssignableTo<IMayHaveCreator>()
        && propertyInfo.Name == nameof(IMayHaveCreator.CreatorId))
    {
        return true;
    }
    if (entityType.IsAssignableTo<IMustHaveCreator>()
        && propertyInfo.Name == nameof(IMustHaveCreator.CreatorId))
    {
        return true;
    }
    if (entityType.IsAssignableTo<IHasModificationTime>()
        && propertyInfo.Name == nameof(IHasModificationTime.LastModificationTime))
    {
        return true;
    }
    if (entityType.IsAssignableTo<IModificationAuditedObject>()
        && propertyInfo.Name == nameof(IModificationAuditedObject.LastModifierId))
    {
        return true;
    }
    if (entityType.IsAssignableTo<ISoftDelete>()
        && propertyInfo.Name == nameof(ISoftDelete.IsDeleted))
    {
        return true;
    }
    if (entityType.IsAssignableTo<IHasDeletionTime>()
        && propertyInfo.Name == nameof(IHasDeletionTime.DeletionTime))
    {
        return true;
    }
    if (entityType.IsAssignableTo<IDeletionAuditedObject>()
        && propertyInfo.Name == nameof(IDeletionAuditedObject.DeleterId))
    {
        return true;
    }
    return false;
}
```

For second requirement of the issue, i did exactly the same approved logic of existing boilerplate code. In order to do it, i used history of EntityHistoryHelper file and i merged it with abp.

If you want i can send a pr?

**Comment by hikalkan** [comment]
Closing this. Created a new issue for the second item: https://github.com/abpframework/abp/issues/5417
