### ISSUE TITLE
Started to get an error from OpenId TokenCleanupBackgroundWorker

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#21024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I know this is not directly a bug but it may be directing us to an issue.

I am using Volo.Abp.Account.Web.OpenIddict and Volo.Abp.Identity.Web both Version="8.1.3"

Somehow I started to get a deletion error like this. And it is periodically throwing this. 

Why did something like this may happen?
And
How to solve this issue?

Failed executing DbCommand ("5"ms) [Parameters=["@__ef_filter__p_0='?' (DbType = Boolean), @__authorizations_0='?' (DbType = Object)"], CommandType='Text', CommandTimeout='300']"
""DELETE FROM \"OpenIddictAuthorizations\" AS o
WHERE (@__ef_filter__p_0 OR NOT (o.\"IsDeleted\")) AND o.\"Id\" = ANY (@__authorizations_0)"

23503: update or delete on table "OpenIddictAuthorizations" violates foreign key constraint "FK_OpenIddictTokens_OpenIddictAuthorizations_AuthorizationId" on table "OpenIddictTokens"

### Reproduction Steps

I do not know, because it started to happen without any intervention.

### Version

8.1.3

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Linux

**Comment by maliming** [comment]
hi @espindl 

You can try to configure the OpenIddict entities to enable the `DeleteBehavior.Cascade` and update migrations.

![image](https://github.com/user-attachments/assets/50326f14-5a74-47cf-aac7-eea523213d60)

**Comment by maliming** [comment]
hi @espindl 

Have you tried that?

**Comment by espindl** [comment]
Unfortunately not yet. But I will try it today and inform here.... Thank you...

**Comment by espindl** [comment]
> You can try to configure the OpenIddict entities to enable the `DeleteBehavior.Cascade` and update migrations.

That worked... Thank you @maliming 

I modified like these: 
delete cascade 
- OpenIddictApplication foreign key for OpenIddictAuthorization 
- OpenIddictApplication and OpenIddictAuthorization foreign keys for OpenIddictToken

**Comment by maliming** [comment]
hi @espindl 

This has nothing to do with cascade deletion. I think there is a problem with your data. If you can share the detailed Debug log, I can check it again.


```cs
public class Program
{
    public async static Task<int> Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Debug)
```

**Comment by espindl** [comment]
It was happening on prod, and after the DB changes it was resolved, so I do not have any logs now. 

**My understanding about the issue is:** 
After or during a framework update deployment, something wrong happened with the data (one of the updates which has some changes on OpenId system in Abp). And because these cascades were not there, we were getting that error every hour or so (I guess a job is working every hour to clean the OpenID system). But I do not know how this inconsistency happened in the first place. 

Do you think I should revert the changes? @maliming

**Comment by maliming** [comment]
> I guess a job is working every hour to clean the OpenID system

Yes, https://github.com/abpframework/abp/blob/dev/modules/openiddict/src/Volo.Abp.OpenIddict.Domain/Volo/Abp/OpenIddict/Tokens/TokenCleanupBackgroundWorker.cs#L11


We will delete the `tokens` before deleting `authorizations`.
So there will be no `violates foreign key`.

https://github.com/abpframework/abp/blob/prerel-9.0/modules/openiddict/src/Volo.Abp.OpenIddict.EntityFrameworkCore/Volo/Abp/OpenIddict/Authorizations/EfCoreOpenIddictAuthorizationRepository.cs#L85-L97

**Comment by maliming** [comment]
> Do you think I should revert the changes? @maliming

Yes. You can try that. You can share the logs and data in your Database if you get new errors.
