### ISSUE TITLE
I cannot run Api host on Macos

### ISSUE THREAD

**Issue by tainhx** [abpframework/abp#2104]
Hi friend, I have download project sample from abp.io...Run it on Visual studio and build well.But the project HttpApi.Host cannot load on Safari

**Comment by maliming** [comment]
Can other browsers work? Like chrome?

You can check if there is any error in the console of safari.

**Comment by tainhx** [comment]
> 
> 
> Can other browsers work? Like chrome?
> 
> You can check if there is any error in the console of safari.

No..I tried Safari, Chrome and Firefox...maybe system can host port 44370

I don't this ouput like below picture in Output log
![image](https://user-images.githubusercontent.com/6361078/68382865-27502d00-0187-11ea-8786-7bf611209c9d.png)

**Comment by hikalkan** [comment]
We will try this on Mac.

**Comment by tainhx** [comment]
> 
> 
> We will try this on Mac.

Thanks..If it work,please make a tutorial...

**Comment by mehmet-erim** [comment]
Hello @tainhx. It works on safari.
Did you run the DbMigrator?

I applied the following steps:
1- Download the Angular UI project on [abp.io](https://abp.io)
2- Run the MSSQL container on Docker
3- Open `YourProjectName.DbMigrator/appsettings.json` and then change the connection string. My connection string as shown below:
```json
"ConnectionStrings": {
    "Default": "Server=localhost;Database=YourProjectName;User Id=sa;password=yourPassw0rd;MultipleActiveResultSets=true"
  },
```
4- Run the `DbMigrator`
5- Open `YourProjectName.HttpApi.Host/appsettings.json` and then change the connection string.
6- Run the `HttpApi.Host`

Everything looks good
![Screen Shot 2019-11-08 at 09 52 48](https://user-images.githubusercontent.com/34455572/68456532-13500e00-020f-11ea-9ba5-3bf0d378cc1c.png)
