### ISSUE TITLE
Upgrade Vulnerable BouncyCastle and ImageSharp libraries

### ISSUE THREAD

**Issue by MichelZ** [abpframework/abp#21041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We get vulnerability warnings in a scan of the built containers about packages with vulnerabilities being used:

`BouncyCasle.Cryptography` library version `2.2.1`
Please find vulnerability information here: https://github.com/advisories/GHSA-m44j-cfrm-g8qc
Please update this library to at least Version `2.3.1`, It seems to be referenced in `Volo.Abp.Commercial.Core`

`SixLabors.ImageSharp` library version `3.1.4`
Please find vulnerability information here:
https://github.com/advisories/GHSA-63p8-c4ww-9cg7
https://github.com/advisories/GHSA-qxrv-gp6x-rc23

Please update this library to as least Version `3.1.5`, it seems to be referenced in `Volo.Abp.Imaging.ImageSharp`

Thanks!

### Version

8.3.1

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Linux

**Comment by maliming** [comment]
Already fixed by https://github.com/abpframework/abp/pull/20960

**Comment by MichelZ** [comment]
@maliming While I can see Imagesharp, I would like to make sure that BouncyCastle was not missed in the `Volo.Abp.Commercial.Core` package, as it's not in that PR. Thanks

**Comment by maliming** [comment]
hi

We also update the `Volo.Abp.Commercial.Core` in private repos.

Thanks
