### ISSUE TITLE
Create application without any **Management Modules

### ISSUE THREAD

**Issue by ramiglez30** [abpframework/abp#2106]
Hi, 

I´m an old user of aspnet boilerplate and I´m right now jumping into the new version. I really appreciate your work. Thanks. 

In the current scenario I´m modernazing an old system with existing domain and database. I need to provide with implementations for multitenants and user management that already exist. 

I would like docs on how to do that, and also it would be nice to use the CLI to create an app without TenantManagementModules (or any others) So I can plug-in my own implementations and datastores.

Thanks again for the amazing work.

**Comment by maliming** [comment]
I think you can read the documentation(https://docs.abp.io/en/abp/latest/) and then manually add/remove any modules.

**Comment by ramiglez30** [comment]
I did, thanks.. conclusion is it´s not a straight forward thing to do, especially with Tenants (current doc is incomplete in this point). 
That´s why I posted the feature request: use CLI with an option to create an app without any concrete modules plugged in.  
Thanks.

**Comment by hikalkan** [comment]
Thank you for the suggestion. We don't want to maintain too many startup templates, but we will consider this in the next releases.

**Comment by dathoang** [comment]
> I think you can read the documentation(https://docs.abp.io/en/abp/latest/) and then manually add/remove any modules.

I have tried to remove one module (Feature Management for example) by remove all related DependsOn attribute in the template:
- AbpFeatureManagementHttpApiModule
- AbpFeatureManagementDomainSharedModule
- AbpFeatureManagementDomainModule
- AbpFeatureManagementApplicationContractsModule
- AbpFeatureManagementApplicationModule

And I still see the features enpoint in the swagger page.
Do I have to remove all the nuget package as well.

**Comment by hikalkan** [comment]
Yes, please also remove the related nuget packages (asp.net core may discover APIs in the depended assemblies).

**Comment by dathoang** [comment]
> Yes, please also remove the related nuget packages (asp.net core may discover APIs in the depended assemblies).

Well, I've remove all the related feature management nuget packages in all the template's projects.
And I still see the Features enpoint in the swagger page. 
May it be the cached somewhere or may it be included in other modules ? 
Really confused about this module system now.
