### ISSUE TITLE
where I can't get the IRepository?

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2108]
when my entity drive from AggregateRoot<Guid> I can get the IRepository<SyncTime, Guid> repository from constructor,but when my entity drive from Entity<Guid>,it will raise am error below:
_Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[SyncData.Host.Domain.SyncTime,System.Guid] repository' of constructor 'Void .ctor(Volo.Abp.Domain.Repositories.IRepository`2[SyncData.Host.Domain.SyncTime,System.Guid])'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)_

This is my code:
 public class SyncTimeService: CrudAppService<SyncTime, SyncTimeDto, Guid, PagedAndSortedResultRequestDto,
                            CreateUpdateSyncTimeDto, CreateUpdateSyncTimeDto>, ISyncTimeService, IApplicationService
    {
        public SyncTimeService(IRepository<SyncTime, Guid> repository)
            : base(repository)
        {

        }
    }

**Comment by maliming** [comment]
Please share your DbContext code.

**Comment by abllyboy** [comment]
> Please share your DbContext code.

This is my dbcontext:
[ConnectionStringName("ChargeConn")]
    public class ChargeDbContext : AbpDbContext<ChargeDbContext>
    {
        public DbSet<Department> Department { get; set; }
        public DbSet<SyncTime> SyncTime { get; set; }
        public DbSet<SyncHis> SyncHis { get; set; }
        public DbSet<WriteBook> WriteBook { get; set; }
        public ChargeDbContext(DbContextOptions<ChargeDbContext> options) : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ConfigureCharge();
            base.OnModelCreating(modelBuilder);
        }
    }

And this is my EntityFrameworkCoreModule:
[DependsOn(
      typeof(SyncDataDomainModule),
        typeof(AbpEntityFrameworkCoreModule)
      )]
    public class ChargeEntityFrameworkCoreModule: AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<ChargeDbContext>(options =>
            {
                options.AddDefaultRepositories();
            }); 
        }
    }

**Comment by maliming** [comment]
Can you provide a project to reproduce the problem? You can use the CLI.

**Comment by hikalkan** [comment]
>when my entity drive from Entity,it will raise am error below

This is by design. See documentation: https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-default-repositories

If you want to create repositories for other entities too, then set includeAllEntities to true:

````csharp
services.AddAbpDbContext<MyDbContext>(options =>
{
    options.AddDefaultRepositories(includeAllEntities: true);
});
````

**Comment by abllyboy** [comment]
> > when my entity drive from Entity,it will raise am error below
> 
> This is by design. See documentation: https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-default-repositories
> 
> If you want to create repositories for other entities too, then set includeAllEntities to true:
> 
> ```cs
> services.AddAbpDbContext<MyDbContext>(options =>
> {
>     options.AddDefaultRepositories(includeAllEntities: true);
> });
> ```

Yes you are right,when I use the CLI, I fond is ok,so I compared the code the different is the includeAllEntities: true. Thank you very much.
