### ISSUE TITLE
Lazy expandable feature for documentation

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#21095]
I didn't add sub-documents of the [microservice startup template document](https://abp.io/docs/latest/solution-templates/microservice) to the navigation menu.

If you go to the [microservice startup template document](https://abp.io/docs/latest/solution-templates/microservice)  document, you can see it is highlighted, but there is no item under it on the menu:

![image](https://github.com/user-attachments/assets/45347c30-1e1d-4f93-8227-186b53e6c603)

However, if you open a sub-document (example: [API Gateways](https://abp.io/docs/latest/solution-templates/microservice/api-gateways)), it is not found and highlighted on the menu as expected:

![image](https://github.com/user-attachments/assets/80c4ff0a-6d7a-4d46-9f9b-312036cf2659)

The problem is solved if I add all sub-documents to the menu. However, I don't want to it for three reasons;

1. It will make filtering the items hard on the "Filter by title" area. Many unrelated items will be found.
2. It will make the nav tree unnecessarily big, which may cause performance
3. It has no meaning when I look at the menu manually, because for that kind of documents, details are only important after I open the main document, and it has sub-documents only because it is long.

So, I offer to introduce a new feature to the documentation system: Lazy expandable.

I will give the usage example with the [book store tutorial](https://abp.io/docs/latest/tutorials/book-store) since it has already sub-items on the menu.

I want to change the related part of `docs-nav.json` file as shown below:

````json
{
  "text": "Web Application Development",
  "isLazyExpandable": true, // ADDED THIS
  "path": "tutorials/book-store",  // ADDED THIS
  "items": [
    {
      "text": "Overview",
      "path": "tutorials/book-store"
    },
    {
      "text": "1: Creating the Server Side",
      "path": "tutorials/book-store/part-01.md"
    },
    {
      "text": "2: The Book List Page",
      "path": "tutorials/book-store/part-02.md"
    },
    {
      "text": "3: Creating, Updating and Deleting Books",
      "path": "tutorials/book-store/part-03.md"
    },
    {
      "text": "4: Integration Tests",
      "path": "tutorials/book-store/part-04.md"
    },
    {
      "text": "5: Authorization",
      "path": "tutorials/book-store/part-05.md"
    },
    {
      "text": "6: Authors: Domain Layer",
      "path": "tutorials/book-store/part-06.md"
    },
    {
      "text": "7: Authors: Database Integration",
      "path": "tutorials/book-store/part-07.md"
    },
    {
      "text": "8: Authors: Application Layer",
      "path": "tutorials/book-store/part-08.md"
    },
    {
      "text": "9: Authors: User Interface",
      "path": "tutorials/book-store/part-09.md"
    },
    {
      "text": "10: Book to Author Relation",
      "path": "tutorials/book-store/part-10.md"
    }
  ]
},
````

I just added `isLazyExpandable` to the root document of the tutorial. As a result on the UI, I am expecting the followings:

* Do not render sub-items (including the overall) normally.
* When I click to the root item (`Web Application Development` for this example), go to the defined `path` (`tutorials/book-store` in this example).
* When we are showing a page under that lazy item, render all the sub-times and highlight the matching item on the UI.
* Notice that I also added `path` to the root item, otherwise, you can not make it clickable and we can not know where to go. It is a kind of duplication, yes.
* Please consider a lazy item can have items which have sub-items. In that case, visiting a 3-rd level sub-item's page should expand 2-levels up lazy item.
* Please consider scenarios where we define lazy items under another lazy item (some kind of recursion).
* After doing the feature and updating the abp.io website, please also modify the docs-nav.json to make these lazy:
  * https://abp.io/docs/latest/tutorials/todo
  * https://abp.io/docs/latest/tutorials/book-store
  * https://abp.io/docs/latest/tutorials/modular-crm
  * https://abp.io/docs/latest/solution-templates/microservice (and add sub-items)
  * https://abp.io/docs/latest/modules/identity-server
  * https://abp.io/docs/latest/modules/openiddict

**Comment by ebicoglu** [comment]
I don't think this issue will fix the below situation or not, but when somebody finds a doc on google he can not go to the parent of this doc, and cannot see it on the navigation menu. 

https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers/buttons
![image](https://github.com/user-attachments/assets/4696c013-3a49-46c4-906f-6f0ddab719d1)

and actually this document is not at the correct place which shows on google search
![image](https://github.com/user-attachments/assets/7558bb39-0ba2-4955-b23e-7707c97658bc)

**Comment by hikalkan** [comment]
It is not related to this issue. But we can add tag helpers to the menu, no problem on that. Create a new issue and assign it to someone.

We can add a "Components" item under the "Overview" menu item (see below screenshot), and add all the components under that new item.

![image](https://github.com/user-attachments/assets/044593c3-41a1-4d8b-a63b-778543c442ae)

https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers

URLs can be like:

* https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers/components/alerts
* https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers/components/badges
* https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers/components/buttons
* ...

**Comment by ebicoglu** [comment]
> It is not related to this issue. But we can add tag helpers to the menu, no problem on that. Create a new issue and assign it to someone.
> 
> We can add a "Components" item under the "Overview" menu item (see below screenshot), and add all the components under that new item.
> 
> ![image](https://private-user-images.githubusercontent.com/1210527/397063667-044593c3-41a1-4d8b-a63b-778543c442ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTE3MDcsIm5iZiI6MTczNDU5MTQwNywicGF0aCI6Ii8xMjEwNTI3LzM5NzA2MzY2Ny0wNDQ1OTNjMy00MWExLTRkOGItYTYzYi03Nzg1NDNjNDQyYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMDY1NjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAyYWFiOTdiNzU2YTkwNzgzNmU3OGRiMzgxOWUxMDI4NjRjMjYzZDM1MTdkZTBiZTVjMzAxZjQ5MzFkODNlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TZRvZuJ1AwZJos0pnxMRKv9C6kRR8I7bf8wHjroG1bs)
> 
> https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers
> 
> URLs can be like:
> 
> * https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers/components/alerts
> * https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers/components/badges
> * https://abp.io/docs/latest/framework/ui/mvc-razor-pages/tag-helpers/components/buttons
> * ...

I create a new issue for this one https://github.com/abpframework/abp/issues/21673
