### ISSUE TITLE
Blog Module posts

### ISSUE THREAD

**Issue by gnsilence** [abpframework/abp#2111]
When I download the template project.Then the Blog module is installed.
But there was an error when I added the article:

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
/Pages/Blog/Posts/New.cshtml

TagHelper attributes must be well-formed.
-
@model Volo.Blogging.Pages.Blog.Posts.NewModel
@inherits Volo.Blogging.Pages.Blog.BloggingPage
@{
    ViewBag.PageTitle = "Blog";
}
@section styles {
    <abp-style-bundle @*name="@typeof(NewModel).FullName" *@>
        <abp-style type="@typeof(TuiEditorStyleContributor)" />
        <abp-style src="/Pages/Blog/Posts/new.css" />
    </abp-style-bundle>
}
@section scripts {
    <abp-script-bundle @*name="@typeof(NewModel).FullName" *@>
TagHelper attributes must be well-formed.
-
    <abp-style-bundle @*name="@typeof(NewModel).FullName" *@>
        <abp-style type="@typeof(TuiEditorStyleContributor)" />
        <abp-style src="/Pages/Blog/Posts/new.css" />
    </abp-style-bundle>
}

**Comment by yekalkan** [comment]
fixed by that commit: https://github.com/abpframework/abp/commit/e605cafe70adf21d339ae6527dec1021edf036aa
