### ISSUE TITLE
Is the abp studio ui client developed by electron or avlonia?

### ISSUE THREAD

**Issue by shuangbaojun** [abpframework/abp#21126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Is the abp studio ui client developed by electron or avlonia?
@hikalkan  @maliming 

### Version

0.52

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

It's [Avalonia UI](https://avaloniaui.net/).

**Comment by shuangbaojun** [comment]
Does abp have an integrated anvlonia demo, written in the native xmal language, or developed in blazor hybrid mode?

**Comment by maliming** [comment]
hi

There is no such demo yet.

**Comment by berkansasmaz** [comment]
I am closing this issue as it is not related to ABP Studio, but if you want to write an article on this topic, feel free to open an issue from [here](https://github.com/abpframework/abp/issues/new?assignees=&labels=community-article-request&projects=&template=04_article_request.yml).
