### ISSUE TITLE
the startup template of angular  some action will repeate request twice to api server

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#2115]
I Create an angular project with ABP cli

 `abp new Acme.BookStore -u angular`

 modify the connection string, generate the database, then run the front & backend.

When change the administrator password, you will get optimistic concurrent lock error. 

Monitor the network request and find that the front end will send two requests to the background in a short time

For example, creating users will create the same two users at the same time.

delete action will not do twice.

![1](https://user-images.githubusercontent.com/7838147/68370786-38de0880-0178-11ea-96db-84ee755c04b4.jpg)

I am using  abp  with version 1.02
![2](https://user-images.githubusercontent.com/7838147/68370835-58753100-0178-11ea-95e5-6f719b144b77.jpg)

**Comment by maliming** [comment]
> When change the administrator password, you will get optimistic concurrent lock error.

This problem cannot be reproduced.

>  creating users will create the same two users at the same time.

Successfully reproduced this problem.

**Comment by xyfy** [comment]
from monitor the network ,change password will repeate twice request too,

**Comment by mehmet-erim** [comment]
Already resolved, see https://github.com/abpframework/abp/commit/878d39c993e85c8d25a2932f776e0d0a850b694a

**Comment by xyfy** [comment]
do you publish the new npm package?

**Comment by maliming** [comment]
Maybe v1.1
