### ISSUE TITLE
How can i integrated a module in a solution 

### ISSUE THREAD

**Issue by seycan-dev** [abpframework/abp#2118]
Hello, i tried to roles page like login page or user account page to my solution but i couldnt please help me about

**Comment by hikalkan** [comment]
Do you want to add source code of a module into your solution?

**Comment by seycan-dev** [comment]
No no i try to use roles, users tables as list or other things but i couldn't get  it that is related from module

**Comment by hikalkan** [comment]
Startup template contains all. But it uses all as NuGet packages instead of directly including into the solution. If you are looking for their source code, you can not find in your solution.

**Comment by seycan-dev** [comment]
no no firstly  i am sorry i couldnt explain to you exactly about it. For example i there are so many module like that link https://github.com/abpframework/abp/tree/dev/modules/feature-management/src/Volo.Abp.FeatureManagement.Web/Pages/FeatureManagement i want to use that page on my solustion. i didnt want use source code i just using your paging on your module. i hope i explained it

**Comment by seycan-dev** [comment]
i have tried to use as link "FeatureManagement/FeatureManagementModel" but it did not work

**Comment by seycan-dev** [comment]
please help me about called it and using

**Comment by seycan-dev** [comment]
Hello ,
i called the users screen 
   context.Menu.AddItem(new ApplicationMenuItem("Volo.Abp.PermissionManagement", l["Menu:Kullanıcılar"], url: "/Identity/Users")); that works for users and roles but i cant called
that module  https://github.com/abpframework/abp/tree/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Web/Pages/SettingManagement
            context.Menu.AddItem(new ApplicationMenuItem("Volo.Abp.SettingManagement", l["Menu:Profile"], url: "/SettingManagement")); but it does not work how can i call it?
