### ISSUE TITLE
Autofac.Core.DependencyResolutionException

### ISSUE THREAD

**Issue by quocduong** [abpframework/abp#21196]
### Is there an existing article or article request for this?

- [X] I have searched the existing resources

### Describe the article you'd like

- Abp Framework version: 8.3.1
- UI: RazorPage
- Abp Studio: 0.92

Hi guys,

I am newer in AbpFramework.
I am using the Business license to work.
I created a DDD principle to manage our categories, use Abp Suite to generate code, I also selected the "Customizable code" option, just use the generated code without modify anything.
After that, I import the project into AdministrationService project.
I have tested in Swagger works well but when calling from js function, got the issue:

```
[ERR] An exception was thrown while activating XXX.AdminCategoryService.ListOrganizations.ListOrganizationController -> XXX.AdminCategoryService.ListOrganizations.ListOrganizationsAppService.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating XXX.AdminCategoryService.ListOrganizations.ListOrganizationController -> XXX.AdminCategoryService.ListOrganizations.ListOrganizationsAppService.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found on type 'XXX.AdminCategoryService.ListOrganizations.ListOrganizationsAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'XXX.AdminCategoryService.ListOrganizations.IListOrganizationRepository listOrganizationRepository' of constructor 'Void .ctor(XXX.AdminCategoryService.ListOrganizations.IListOrganizationRepository, XXX.AdminCategoryService.ListOrganizations.ListOrganizationManager)'.
```

I also have tried https://github.com/abpframework/abp/issues/13979.
Please help, I spent 2 days to compare code with the Volo.Abp.LanguageManagement

Many thanks.

**Comment by maliming** [comment]
hi

Please create a support ticket on https://support.abp.io/

Thanks.

**Comment by quocduong** [comment]
The problem was resolved.
Thank you @maliming
