### ISSUE TITLE
[BUG] Invalid logic in `LocalizableStringSerializer` causes failure in  `FeatureAppService`

### ISSUE THREAD

**Issue by ahmednfwela** [abpframework/abp#21191]
This part here:
https://github.com/abpframework/abp/blob/3db054e7d9a45b36990eae7289ce09b5b7dd6749/framework/src/Volo.Abp.Localization/Volo/Abp/Localization/LocalizableStringSerializer.cs#L38-L43

will create a `new FixedLocalizableString(value)` if the value is null

and then for any subsequent call to Localize (e.g. in `FeatureAppService`)
this will call:

https://github.com/abpframework/abp/blob/3db054e7d9a45b36990eae7289ce09b5b7dd6749/framework/src/Volo.Abp.Localization.Abstractions/Volo/Abp/Localization/FixedLocalizableString.cs#L14-L17

which will throw because the constructor checks if name and value are not null:

https://github.com/dotnet/aspnetcore/blob/8b857e42aee71f3d8030708e3a2d51191238f8fe/src/Localization/Abstractions/src/LocalizedString.cs#L45-L46

**Comment by maliming** [comment]
Move to https://abp.io/support/questions/8169/Bug-in-Localization-logic-causes-feature-management-to-fail
