### ISSUE TITLE
Register failed. Username or Email is already registered. You can try registering on https://abp.io website.

### ISSUE THREAD

**Issue by anderjef** [abpframework/abp#21208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

# Problem 

Cannot register with username containing ampersand (&):

An error has occured!
Register failed. Username or Email is already registered. You can try registering on https://abp.io website. 

 # Details 

 Volo.Abp.Studio.AbpStudioException: Exception of type 'Volo.Abp.Studio.AbpStudioException' was thrown.
   at async Task Volo.Abp.Studio.Auth.StudioAuthService.RegisterAsync(string emailAddress, string userName, string password)
   at async Task Volo.Abp.Studio.UI.ViewModels.LoginViewModel.jklfH0Pwq()

### Version

0.9.2

### Operation System

Windows (Default)

### Other information

This issue has been reported from ABP Studio.

**Comment by ismcagdas** [comment]
Moved to ABP Studio repositoru https://github.com/volosoft/abp-studio/issues/2178
@anderjef thank you for your report, we will fix this issue. You can register with a username without `&` character.
