### ISSUE TITLE
ASP.NET Boilerplate 5.x to ABP 1.x migration guide document

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2120]

**Comment by viewtance** [comment]
Could make this done in v1.1, we want to start new project with vNext and use the current application users which build by ANZ with ABP.

**Comment by hikalkan** [comment]
Such a guide will be a brief and will reference to the documentation in many points. But currently the documentation is missing. So, I was planning this a bit later. I know it is being waited, but should wait a bit more.

**Comment by hikalkan** [comment]
BTW, we are working hard on the ABP Framework and the ABP.IO platform (not only commits to the repository, writing documents, building CI/CD...). We know the demand from the community, but a bit more patience :)

**Comment by hikalkan** [comment]
Started to work on this: https://github.com/abpframework/abp/blob/dev/docs/en/AspNet-Boilerplate-Migration-Guide.md

**Comment by hikalkan** [comment]
Published it: https://docs.abp.io/en/abp/latest/AspNet-Boilerplate-Migration-Guide
However, will improve this guide by the time: https://github.com/abpframework/abp/issues/2832
