### ISSUE TITLE
QuartzBackgroundWorkerBase can't start Jobs when class name starting with I

### ISSUE THREAD

**Issue by nurlix** [abpframework/abp#21214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi. I have no idea if its bug or feature.
I had a QuartzBackgroundWorkerBase job name IftminWorker and couldn't make it start although I had others which worked fine with exact same code. So I renamed file just for fun to SmgsWorker and it worked. And when I renamed it to ISmgsWorker it stoped work again

### Version

8.3.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by iiiixxl** [comment]
I think you may not be successfully injecting into DI. Also, don't start with I because that's the convention for interfaces. In a sense, convention is greater than configuration. What is the specific reason? It is recommended that you upload specific code for analysis.

**Comment by maliming** [comment]
hi

You can also use `Dependency Attribute` if your service name is special.

https://abp.io/docs/latest/framework/fundamentals/dependency-injection#dependency-attribute

**Comment by nurlix** [comment]
Yes I think it has to do with convention. At first it did't come to my mind. Crazy part is that it was working for few months and suddenly refused to work after I changed IftminService nothing serious few code formatting. But the class calling it i.e IftminWorker was intact. I tried to revert all back and commenting everything related to IftminService didn't help. Any ways renaming it from IftminWorker to SmgsWorker worked. I guess no words starting with I.
```﻿using System;
using System.Threading.Tasks;
using Ftu.AsoupServices;
using Microsoft.Extensions.Logging;
using Quartz;
using Volo.Abp.BackgroundWorkers.Quartz;

namespace Ftu.Jobs;

public class IftminWorker : QuartzBackgroundWorkerBase
{
    private readonly IftminService _iftminService;

    public IftminWorker(IftminService iftminService)
    {
        _iftminService = iftminService;
        
        JobDetail = JobBuilder.Create<IftminWorker>()
            .WithIdentity(nameof(IftminWorker))
            .Build();
        
        Trigger = TriggerBuilder.Create()
            .WithIdentity(nameof(IftminWorker))
            .WithSimpleSchedule(s => s.WithIntervalInMinutes(120).RepeatForever())
            .Build();
    }

    public override async Task Execute(IJobExecutionContext context)
    {
        try
        {
            Logger.LogInformation("************************* Starting: IFTMIN ****************************");
            await _iftminService.Run();
            Logger.LogInformation("************************* IFTMIN Completed ****************************");
        }
        catch (Exception e)
        {
            Logger.LogError($"IFTMIN: {e.Message}");
        }
    }
}
```
