### ISSUE TITLE
Maybe IDataFilter  change another name will be better 

### ISSUE THREAD

**Issue by yilianhuaixiao** [abpframework/abp#2123]
The nameing makes me confused.    Actually IDataFilter  is a collection of  IDataFilter<>  but with same name 'IDataFilter' .   Maybe change   'IDataFilter' to  'IDataFilterManager' will be better.

```
public interface IDataFilter<TFilter> 
        where TFilter : class
    {
        IDisposable Enable();

        IDisposable Disable();

        bool IsEnabled { get; }
    }

    public interface IDataFilter  
    {
        IDisposable Enable<TFilter>()  
            where TFilter : class;
        
        IDisposable Disable<TFilter>()
            where TFilter : class;

        bool IsEnabled<TFilter>()
            where TFilter : class
    }

```

**Comment by hikalkan** [comment]
>Actually `IDataFilter` is a collection of `IDataFilter<> `

It is not exactly. `IDataFilter` can be used to control any filter, while `IDataFilter<ISoftDelete>` is used to control only the ISoftDelete filter.
Injecting `IDataFilter<ISoftDelete>` makes it clear that the class will work on the ISoftDelete filter. But in practical everyone will probably inject and use the `IDataFilter`. So, maybe it was an overengineering :)

**Comment by yilianhuaixiao** [comment]
> Actually IDataFilter is a collection of IDataFilter<>  

It is a Broadly speaking.  I mean  IDataFilter can contains  IDataFilter<>   generally.
Look at abp default impletation of IDataFilter
```
  public class DataFilter : IDataFilter, ISingletonDependency
    {
        private readonly ConcurrentDictionary<Type, object> _filters; //IDataFilter<Xxx>

        private readonly IServiceProvider _serviceProvider;

        public DataFilter(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
            _filters = new ConcurrentDictionary<Type, object>();
        }

        public IDisposable Enable<TFilter>()
            where TFilter : class
        {
            return GetFilter<TFilter>().Enable();
        }
        ...
}

```

IDataFilter<>   and  IDataFilter used the same name. And we know DataFilter is 'a container of  IDataFilter<>' ,   change IDataFilter to  'IDataFilterMananger' can makes things clear.

**Comment by hikalkan** [comment]
>change IDataFilter to 'IDataFilterMananger' can makes things clear

`IDataFilter` manages all filters while `IDataFilter<T>` manages a single filter. From this point of view, they are both managers.

Thank you for your sharing your thought, but we don't want that (which also will bring an unnecessary breaking change).
