### ISSUE TITLE
Is it more reasonable to remove the IMultiTenant from OrganizationUnitRole?

### ISSUE THREAD

**Issue by shuangbaojun** [abpframework/abp#21272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/61fa8261-8f0c-4686-8198-340418700c8a)
hi，
  Isn't it more appropriate that general data filtering is a global approach to aggregation roots rather than entities

@maliming

**Comment by maliming** [comment]
hi

The `OrganizationUnitId` and `RoleId` of `OrganizationUnitRole` may be the same under multiple tenants. 

We have to use `TenantId`.
