### ISSUE TITLE
Help with Encyption/Hashing strings?

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2129]
I have a custom MailAccount table with passwords that I'd like to encrypt so if the database is stolen or leaked, then the password can't be read. It needs to be reversible so I can still send and receive emails.

I have found the `Volo.Abp.Security.Encryption.IStringEncryptionService` and configured the options in the `Domain` project like so (obviously with different strings!):
```csharp
public override void ConfigureServices(ServiceConfigurationContext context)
{
    var configuration = context.Services.GetConfiguration();
    Configure<AbpStringEncryptionOptions>(options =>
    {
        options.DefaultPassPhrase = "gsKnGZ041HLL4IM8";
        options.InitVectorBytes = Encoding.ASCII.GetBytes("jkE49230Tf093b42");
        options.DefaultSalt = Encoding.ASCII.GetBytes("hgt!16kl");
    });
}
```

My questions are:
1. Is this the correct place to configure the service?
2. How do I use this service? Inject the `IStringEncryptionService` to the DomainService?
3. How is the IdentityUser `PasswordHash` encrypted? I assume it uses the `Microsoft.AspNet.Identity.PasswordHasher`

It would be good if there could be a 'Security Hardening' guide on the docs with examples like this.

Thanks!

**Comment by hikalkan** [comment]
You did all right.

>Is this the correct place to configure the service?
Yes.

>How do I use this service? Inject the IStringEncryptionService to the DomainService?
You can inject to any class, including domain services.

>How is the IdentityUser PasswordHash encrypted? I assume it uses the Microsoft.AspNet.Identity.PasswordHasher
Yes. It is not related to IStringEncryptionService
