### ISSUE TITLE
What is the use of adding distributed event LanguageChangedEto in 8.3.3?

### ISSUE THREAD

**Issue by mrh520** [abpframework/abp#21302]
What is the use of adding distributed event LanguageChangedEto in abp 8.3.3

**Comment by hikalkan** [comment]
ABP internally uses it to invalidate the language list that is used to localize responses for ASP.NET Core:

https://github.com/abpframework/abp/blob/5d2abf2f4f68d1ce4bdfd620a9df09f8309e885d/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/RequestLocalization/DefaultAbpRequestLocalizationOptionsProvider.cs#L102-L108

**Comment by mrh520** [comment]
Thanks for reply.
I probably don't need to use this, but the queue needs to be bound to a routingkey.
Whether can use it on demand.
