### ISSUE TITLE
Kaspersky accuses Trojan infection by Abp Studio

### ISSUE THREAD

**Issue by vinicete** [abpframework/abp#21319]
Today I was studying and executing the Monolith Modular Project suggested by the documentation, everything was ok, I've been executed the MVC project several times and nothing happened, but suddenly, my antivirus (Kaspersky Standard) accuses a big problem: An Trojan Infection.

I suddenly started a cleaning on my pc, and quickly things start to happen, when I tried to inicialize my browser or windows explorer, an error message popped up saying I have no authority to execute that action, I was despaired.

The PC restarted and I my password doesn't worked, I waited 10 minutes and then it worked (?), and showed up a message from kaspersky to resolve damages.

I am very confused and scared. The log from Kaspersky accuses a trojan infecction by abp studio, but i dont know if its a false positive cause I lost for few minutes my authorization under my pc.

Please help me, I was studying for my job and I need answers. What should I do?

I have attached some screenshots but they are mainly in Portuguese.

![WhatsApp Image 2024-11-12 at 15 25 08](https://github.com/user-attachments/assets/5768bad1-7eda-40fa-88b1-83c81cf6593a)
![WhatsApp Image 2024-11-12 at 15 25 08 (1)](https://github.com/user-attachments/assets/4db63837-be6a-4152-813f-f21092d48859)
![WhatsApp Image 2024-11-12 at 16 07 55](https://github.com/user-attachments/assets/3516f2e2-11a1-46ec-97ca-1ef6097ec693)

#abp

**Comment by ebicoglu** [comment]
Kaspersky makes a heuristic scan, that's why this is a false alert.
When you send Studio binary to Kaspersky website, it **reports as clean**.
You can see the Kaspersky virus check report:
https://opentip.kaspersky.com/B5366475C0C24A1A3C51FD44A9D05B24AFA519912E9C08B315AD2E845367B1F9/results
![image](https://github.com/user-attachments/assets/db48c084-f4a4-481b-ba96-4929a9c31e69)
