### ISSUE TITLE
Unable to change abp table names

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2131]
In the `OnModelCreating` method I try to update one of the built-in entities such as BackgroundJobs or Settings etc.

```csharp
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);
    builder.ConfigureBackgroundJobs();

    builder.Entity<BackgroundJobRecord>(e => { e.ToTable("abp_background_jobs"); });
}
```
After migrating `Add-Migration Initial` I see the generated script has the correct table name.

When I run the application I get errors in the logs saying:
`MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'testapp.abpbackgroundjobs' doesn't exist`. It seems to be looking for the original table name. How can I fix this?

**Comment by olicooper** [comment]
This issue touches on some of the issues I face too: https://github.com/abpframework/abp/issues/2095

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1429#issuecomment-541096039

**Comment by olicooper** [comment]
That doesn't do quite what I want...
I am trying to make all table names lower-case because of the issue with portability between windows (case insensitive) and Unix systems.
I found out the hard way when I ran some custom migration SQL command `MigrationBuilder.Sql()` and wasn't aware of the case sensitivity issue. This meant that all my my migrations failed on Linux.
My solution would be to convert all table names to snake_case like `abp_background_jobs` so it is more readable than `abpbackgroundjobs`.
I am using something something like this: https://github.com/leonibr/efcore-snakecase/blob/master-v30/src/Marques.EFCore.SnakeCase/ToSnakeCase.cs
It works but I get errors like the one above for the abp tables.

**Comment by hikalkan** [comment]
@olicooper you may do it in the end of the OnModelCreating of the MigrationsDbContext ([see](https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/MyProjectNameMigrationsDbContext.cs#L28)).

For all entity, you can map to another table name. You can even try to write a generic code that gets the list of all entities from the builder and change table names to snake_case.

**Comment by hikalkan** [comment]
This is how you can get the list: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L73

**Comment by johnnba** [comment]
yes, @olicooper  you need to do it in the end of the OnModelCreating of the MigrationsDbContext  where the abp related tables get configured .

 

>             /* Include modules to your migration db context */

            builder.ConfigurePermissionManagement();
            builder.ConfigureSettingManagement();
            builder.ConfigureBackgroundJobs();
            builder.ConfigureAuditLogging();
            builder.ConfigureIdentity();
            builder.ConfigureIdentityServer();
            builder.ConfigureFeatureManagement();
            builder.ConfigureTenantManagement();

`builder.Entity<BackgroundJobRecord>(e => { e.ToTable("abp_background_jobs"); });`

then you will get worked. that's how i resolved the same problem .

**Comment by olicooper** [comment]
I've had another shot at it and it still doesn't seem to be working.

I add the code to change table names at the end of `OnModelCreating` in `MigrationsDbContext`. 
I am using this to migrate the database: [efcore-snakecase](https://github.com/leonibr/efcore-snakecase/blob/master-v30/src/Marques.EFCore.SnakeCase/ToSnakeCase.cs)

```csharp
builder.ToSnakeCase(ModelToSnakeCase.ConvertOptions.Tables);
```
It changes the table names fine as you can see below but I get an exception when running the migration console app (after running `PM> add-migration Initial` in package manager).
![image](https://user-images.githubusercontent.com/22296715/69833895-a2f54500-122e-11ea-9cd2-c84d0f92248d.png)

```
An exception was thrown while activating Volo.Abp.Identity.IdentityDataSeedContributor -> Volo.Abp.Identity.IdentityDataSeeder -> Volo.Abp.Identity.IdentityUserManager.
Autofac.Core.DependencyResolutionException
{"Table 'myproject.abpsettings' doesn't exist"}
```

I wonder if it is the way I am changing the table names or an maybe it is an EF Core bug?
```csharp
foreach (var entity in modelBuilder.Model.GetEntityTypes())
{
    entity.SetTableName(entity.GetTableName().ToSnakeCase());
}
```

**Comment by qzwzqty** [comment]
@olicooper hello! Did you solve it? I have the same problem.

**Comment by hikalkan** [comment]
@olicooper I understand your case. Unfortunately, that will not work. Because, setting management module has [its own DbContext](https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.MongoDB/Volo/Abp/SettingManagement/MongoDB/SettingManagementMongoDbContext.cs) and it is unaware of your changes.
You can try this ([Replace Other DbContextes](https://docs.abp.io/en/abp/latest/Entity-Framework-Core#replace-other-dbcontextes)) but it will make your application more complex.
Best way to leave existing tables as is :)

I created a new issue https://github.com/abpframework/abp/issues/2351 to define an handler that you can completely override the naming code. But I don't think it is urgent and added to backlog. Howeer, any good implemented PR would be appreciated :)

**Comment by hikalkan** [comment]
I am closing this since you can set prefixes like:

````csharp
AbpIdentityDbProperties.DbTablePrefix = "MyPrefix";
````

Write this before any code executed (for example, in Program.cs file, at the beginning).
