### ISSUE TITLE
Please close the source of all your products ！！！！！！

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#21336]
Hi,
Despite your lack of response, I have deleted my project. Please close-source all your products and do not make them available in any form, whether-source or for sale.

尽管你们不做回复，但是我已经删除了我的项目，请你们闭源你们所有的产品，不要以开源、出卖等任何方式出现。

![a891342d4ce1513a7b9216caf82648c](https://github.com/user-attachments/assets/ac63d67e-cecb-4759-9872-972912ca1e5c)
![image](https://github.com/user-attachments/assets/d2900908-7b06-449a-9f1b-448bd1ac3434)

**Comment by maliming** [comment]
Thank you for your understanding. We support and respect open source.  👍
