### ISSUE TITLE
AuditPropertySetter in AbpDbContext<TDbContext> always null

### ISSUE THREAD

**Issue by meision** [abpframework/abp#2134]
I could not insert default CreationTime due to AuditPropertySetter in AbpDbContext<TDbContext> always null.
I think this may be caused by microsoft .net core DI lack of Property injection, how could I resolve this?

**Comment by meision** [comment]
Once i change DI system to autofac, the problem resolved. Any idea if I want to use Microsoft DI system?

**Comment by maliming** [comment]
> I think this may be caused by microsoft .net core DI lack of Property injection, how could I resolve this?

You are right, Microsoft's default dependency injection container function is relatively simple, I suggest you always integrate autofac.

**Comment by hikalkan** [comment]
Microsoft's default DI library doesn't play well with ABP framework, because some of the ABP functionalities rely on "property injection" and "dynamic proxying" those are not supported in the default container.
