### ISSUE TITLE
Abp Studio detected as malware by Kaspersky 

### ISSUE THREAD

**Issue by makhalaf** [abpframework/abp#21359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Abp Studio detected as malware by Kaspersky 
![abp_antivirus](https://github.com/user-attachments/assets/eaf029a1-3a90-4470-a6cb-7adecc27659f)

### Version

0.9.5

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment]
@enisn Can we do something to make Kaspersky recognize ABP Studio?

**Comment by berkansasmaz** [comment]
We are considering installing the application from the Microsoft Store to resolve this issue. However, this will take some time, and in the meantime, you can have the virus program you are using not scan ABP Studio.

---

Closing the issue. Feel free to re-open or create a new issue if you have further questions.
