### ISSUE TITLE
How to enable Localization

### ISSUE THREAD

**Issue by raminmjj** [abpframework/abp#2136]
Hi.
I create a [sample project](https://github.com/raminmjj/test-abp-localization) from abp.io document.
but localization doesn't work for me.
where am I doing wrong?

> please fix document in "Creating A Localization Resource" section.
> "VirtualFileSystemOptions" most be "AbpVirtualFileSystemOptions"

Thank you.

**Comment by hikalkan** [comment]
@yekalkan can you help to @raminmjj please?

**Comment by raminmjj** [comment]
I found the problem.
in "options.FileSets.AddEmbedded<MyAppModule>()", the namespace must be specified. like this:
`options.FileSets.AddEmbedded<MyAppModule>("BasicAspNetCoreApplication");`
*please fix localization's document.
thanks for your grate work.

**Comment by maliming** [comment]
we also need to update the documentation.

**Comment by hikalkan** [comment]
I will update the docs. Thanks.

**Comment by hikalkan** [comment]
Done: https://github.com/abpframework/abp/commit/9deb8804b2c18495fc7a43de80d1a68dfafc040a

**Comment by maliming** [comment]
Add a description to the localization document.
https://github.com/abpframework/abp/commit/f4c8efceb2ebaa3330ed0804a82945a310501d89#diff-f53ab683a53c59943d88ca6c389957d5R52
