### ISSUE TITLE
'Volo.Abp.BlobStoring.Aliyun' nuget package could not be found!

### ISSUE THREAD

**Issue by myesn** [abpframework/abp#21365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The CLI command not works：https://abp.io/docs/latest/framework/infrastructure/blob-storing/aliyun

```
abp add-package Volo.Abp.BlobStoring.Aliyun
```

```
abp add-package Volo.Abp.BlobStoring.Aliyun --old
```

![image](https://github.com/user-attachments/assets/ee3f919e-363a-45e7-b8c9-1cc464b59411)

### Version

8.1.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Please add package(https://www.nuget.org/packages/Volo.Abp.BlobStoring.Aliyun/) and `AbpBlobStoringAliyunModule` module manually.

We will add `Volo.Abp.BlobStoring.Aliyun` to abp.io platform.
