### ISSUE TITLE
GetClientIpAddress support X-Forwarded-For | X-Real-IP

### ISSUE THREAD

**Issue by RobertoFiocchiMCSI** [abpframework/abp#21380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

See https://github.com/aspnetboilerplate/aspnetboilerplate/pull/7038 

please apply the same patch
https://github.com/aspnetboilerplate/aspnetboilerplate/pull/7038/commits/f139f682283468412a20505bbcee5fbdcc5a781d
to the file https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/WebClientInfo/HttpContextWebClientInfoProvider.cs

Thanks

### Version

last

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

https://abp.io/support/questions/1950/How-to-use-a-custom-HTTP-header-to-get-the-client-remote-IP-address#answer-ecede883-2a1e-9d09-7a4b-39ff67b1a2e5

**Comment by RobertoFiocchiMCSI** [comment]
Thanks for the info, but wouldn't it be better if this is included in the framework like it is in AspNetZero?

**Comment by maliming** [comment]
hi

Using `UseForwardedHeaders` is a standard way.

We prefer to use it.

**Comment by RobertoFiocchiMCSI** [comment]
Ok, but why do I need to have a UseCustomHttpHeaders instead of this already included in the framework?

I think RemoteIpAddress should always work regardless of whether the application is not running behind a proxy today and is running behind a proxy tomorrow.

**Comment by maliming** [comment]
hi

> but why do I need to have a UseCustomHttpHeaders

This is standard, that's why ASP.NET Core introduces a `Middleware` instead of directly reading the `X—` header to set the `RemoteIpAddress`.

**Comment by RobertoFiocchiMCSI** [comment]
ok, it is not clear to me why being a standard for asp.net core, and aspnetzero is based on it, it has been implemented differently.

In any case, confirm that it is enough to follow what is reported here: 
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-9.0#forwarded-headers-middleware-order

If so, can I ask for a feature request to add these instructions in the base template?

If not, it means that a custom configuration is necessary for each customer to whom my application will be released.

Thanks

**Comment by maliming** [comment]
hi

I will add some instructions to the document to explain the `ForwardedHeaders`.


`ForwardedHeaders` solves the IP problem and has other advantages, such as the `HTTP Scheme,` etc.

![image](https://github.com/user-attachments/assets/6008f837-9dab-49ab-940a-68547f36a9e5)

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-9.0

**Comment by RobertoFiocchiMCSI** [comment]
ok, thanks.
we will be careful when we release in proxy environments.
