### ISSUE TITLE
EmailConfirmed and PhoneNumberConfirmed are set to false after updating a user

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2140]
When updating a user with identity-management, if user's `EmailConfirmed` and `PhoneNumberConfirmed` dont change, should them keep original value?

https://github.com/abpframework/abp/blob/79cc798b6bc05b4596a5590884205eb1318c81cc/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L128

**Comment by hikalkan** [comment]
@maliming can you test this and fix if there is a bug please?

**Comment by maliming** [comment]
This is actually the design of the Identity.
https://github.com/aspnet/AspNetCore/blob/bfec2c14be/src/Identity/Extensions.Core/src/UserManager.cs#L1389

**Comment by gdlcf88** [comment]
What if dont set the un-changed Email/PhoneNumber value for keeping their confirmed status?
https://github.com/abpframework/abp/blob/79cc798b6bc05b4596a5590884205eb1318c81cc/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L130

**Comment by maliming** [comment]
You can override the related methods.  I will take the time to figure out the design logic of identity.

**Comment by maliming** [comment]
Well, maybe we should not call the SetEmailAsync method if the email has not changed.
