### ISSUE TITLE
ABP CLI Update Command Does Not Install .NET 9 Packages

### ISSUE THREAD

**Issue by ekaradev** [abpframework/abp#21415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm running the update command in ABP CLI, but it doesn't install .NET 9 packages and says everything is up to date

![image](https://github.com/user-attachments/assets/8236a1be-3828-4cf9-a34d-e63c10948264)

### Version

0.9.8

### Operation System

Windows (Default)

**Comment by EngincanV** [comment]
Hi, since we are not completing all tests, we did not set the latest version as 9.0.0. You can see the current latest version from https://github.com/abpframework/abp/blob/dev/latest-versions.json

We will set it to v9.0 as soon as possible, thanks for your understanding.
