### ISSUE TITLE
Volo.Abp.Studio.Cli on Github Actions miss Extensions.

### ISSUE THREAD

**Issue by CrazyBaran** [abpframework/abp#21420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After migrate to version 9 I had start problems on my Github Actions CI/CD, after install Volo.Abp.Studio.Cli, it missing some packages `[12:56:06 WRN] Volo.Abp.Studio.Extensions.StandardSolutionTemplates extension not found in the NuGet cache. Directory: /home/runner/.nuget/packages/volo.abp.studio.extensions.standardsolutiontemplates/0.9.9/lib/net9.0`
and try to install, but after install and restart of CLI still this extension is missing. 
![image](https://github.com/user-attachments/assets/a1566fd7-d544-4b78-8e0a-d5ef935e6b51)

### Version

0.9.9

### Operation System

Linux

**Comment by berkansasmaz** [comment]
We are aware of the issue and will release a new version as soon as possible. Thank you for your understanding 🙏🙏

**Comment by CrazyBaran** [comment]
Ok, then I'm waiting :)

**Comment by izanhzh** [comment]
> Ok, then I'm waiting :)

@CrazyBaran
Maybe the same issue as me: https://github.com/abpframework/abp/issues/20978
