### ISSUE TITLE
MicroserviceDemo and BookStore-Modular: VS solution files (.sln,...)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2144]
Is there any reason, why in the _MicroserviceDemo_ solution is no .sln files ("whole module solution") in /modules/[module_name]?
Example: https://github.com/abpframework/abp/tree/dev/samples/MicroserviceDemo/modules/product

But there is whole VS solution for BookStore-Modular example in /modules/[module_name].
Example: https://github.com/abpframework/abp/tree/dev/samples/BookStore-Modular/modules/book-management

Thank you for explanations.

**Comment by maliming** [comment]
I don't think there is any difference in essence. As a demonstration, they can all be integrated into one solution or independently into multiple solutions.

Modules are independent, so separating them is a good choice, of course you can also merge your projects and modules in a solution for your convenience, depending on yourself.

**Comment by leonkosak** [comment]
Help needed (BookStore-Modular example).
There is no readme how to build, run migrations, deploy,... BookStore-Modular example and I am confused.

I see that application (Acme.BookStore) has local references inside solution projects to /modules solution and DependsOn dependencies "definitions" (as [DependsOn] attribute).

However, I cannot figure out:

1) How to properly build whole solution (if I am in Acme.BookStore solution). Currently, I am using build-all.ps1 to do this job. Solution Acme.BookStore.BookManagement has te bo compiled before that. Is using this PowerShell script ok to build the whole solution?

2) How to build and apply database migration - separately for module and application or together from application solution?

3) Are there separated databases (for solution and module) or abp "combines" all classes (tables) into one database (with different schema perixes)?

4) How to properly build the whole solution (Acme.BookStore) for deploy - as one solution (from application project) or separately somehow and which projects?

Thank you for explanations.
