### ISSUE TITLE
How can I config one to many relationship without navigation property?

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2145]
![image](https://user-images.githubusercontent.com/15363011/68585496-60590c00-04bd-11ea-8789-7c31adda90c6.png)
like this.  order to orderline.
no navigation,no foreignKey, I don't know how to config ModelBuilder.

![image](https://user-images.githubusercontent.com/15363011/68585838-48ce5300-04be-11ea-81bd-4558a1ee68d1.png)

**Comment by maliming** [comment]
You can refer to the **blog** and **post** configuration code in the **Blogging** module.

https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.EntityFrameworkCore/Volo/Blogging/EntityFrameworkCore/BloggingDbContextModelBuilderExtensions.cs#L38
