### ISSUE TITLE
Could not retrieve the OpenId Connect discovery document! ErrorType: Http. Error: Error connecting to https://account.abp.io/.well-known/openid-configuration: Forbidden

### ISSUE THREAD

**Issue by Candy-Zoe** [abpframework/abp#21454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When abp studio logging in, prompt ：Could not retrieve the OpenId Connect discovery document! ErrorType: Http. Error: Error connecting to https://account.abp.io/.well-known/openid-configuration: Forbidden

### Version

9.0

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

We will fix this soon.

**Comment by maliming** [comment]
hi

It works now. You can try again.

Thanks.

**Comment by Candy-Zoe** [comment]
Yes, I can now log in normally. Thank you for your hard work.
