### ISSUE TITLE
ABP translation process seems broken

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#21473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It seems like the translation process described here https://abp.io/docs/latest/contribution is either incomplete or not working. When running the "abp translate" command does not seem to include all the necessary strings to be translated which can easily be confirmed by just doing a search for "login" or "claim" in the produced file which are missing. 

So even when we have translated all the entries in that file and had that committed via a PR to ABP code, the end result is still something that is almost useless as half of the UI would still be in English. 

How can we do an actual translation of ABP for, in our case, Swedish?

**Comment by maliming** [comment]
hi

> When running the "abp translate" command does not seem to include all the necessary strings to be translated which can easily be confirmed by just doing a search for "login" or "claim" in the produced file which are missing.

Please share full steps.

**Comment by improwise** [comment]
> hi
> 
> > When running the "abp translate" command does not seem to include all the necessary strings to be translated which can easily be confirmed by just doing a search for "login" or "claim" in the produced file which are missing.
> 
> Please share full steps.

Followed the guide linked above https://abp.io/docs/latest/contribution. In our case, we cloned the latest ABP version (9.0 at the time of writing) and then run the abp translate. When looking in the produced file, there are not entries for things like "login" and "claim" etc thus it never gets translated and the end result is a UI with English and another language mixed. 

Not  sure if the instructions provided on the ABP web site above is incorrect as there seem to be translations like Finish that have translation of these strings as well?

**Comment by improwise** [comment]
@maliming  Follow up, looking here https://abp.io/docs/latest/CLI#translate there are different instructions on how to translate which seems to be more up to date than the ones provided on the https://abp.io/docs/latest/contribution. 

Even when running with the -all option, things like "security logs" and "claim types" are missing in the produced abp-translation.json file

![image](https://github.com/user-attachments/assets/9635815a-9b33-44a8-989b-319fd6743e2d)

**Comment by improwise** [comment]
Can we do a new translation and use it locally before the PR is approved and included in an official ABP release and if so, how?

We are ABP Commercial users BTW.

**Comment by improwise** [comment]
Something is quite weird here, using the "abp translate -c sv -all" command gives us a JSON file containing this

```
        {
          "LocalizationKey": "AlreadyRegistered",
          "Reference": "Already registered?",
          "Target": "Är du redan registrerad?"
        },
```

Yet, even if we delete the database, add

`options.Languages.Add(new LanguageInfo("sv", "sv", "Svenska"));`

and then run DBMigrator again,

We still get this (Swedish values missing)

![image](https://github.com/user-attachments/assets/ca696ef2-82e9-477f-9711-a4de2fa666b2)

"AlreadyRegistered" is just an example, there are many entries like this that are missing.

There are also entries that seem to be missing even in the JSON file, like the "Not a member yet?" on the login page, which does not seem to be included as English (Reference) in the generated abp-translation.json file. Despite this, it seem to be translated for several languages. 

![image](https://github.com/user-attachments/assets/2faae53e-2172-4ad6-9cdb-f0832990804e)

![image](https://github.com/user-attachments/assets/1f5f6de9-3f7a-4c94-9033-65704b3183bc)

Either we are doing something really wrong here or there seem to be something that isn't working as it should with ABP translation (I hope it is us doing things wrong). 

Please advice :)

**Comment by maliming** [comment]
hi

I will share all commercial localization JSON with you.

You can send me the translated JSON file. Then, I will update the commercial modules.

Let discuss this in https://abp.io/support/questions/8415/Problems-with-translating-ABP-confusing-instructions-does-not-seem-to-work-etc

**Comment by improwise** [comment]
> hi
> 
> I will share all commercial localization JSON with you.
> 
> You can send me the translated JSON file. Then, I will update the commercial modules.
> 
> Let discuss this in https://abp.io/support/questions/8415/Problems-with-translating-ABP-confusing-instructions-does-not-seem-to-work-etc

I still believe there are updates needed for the ABP free version as well, at least to the documentation about how to contribute to the translation as it seems somewhat confusing and incorrect now, especially with to parts of the documentation describing the same thing differently. But I agree that we should probably keep the ABP Commercial specific stuff out of this issue.

**Comment by improwise** [comment]
> > hi
> > I will share all commercial localization JSON with you.
> > You can send me the translated JSON file. Then, I will update the commercial modules.
> > Let discuss this in https://abp.io/support/questions/8415/Problems-with-translating-ABP-confusing-instructions-does-not-seem-to-work-etc
> 
> I still believe there are updates needed for the ABP free version as well, at least to the documentation about how to contribute to the translation as it seems somewhat confusing and incorrect now, especially with to parts of the documentation describing the same thing differently. But I agree that we should probably keep the ABP Commercial specific stuff out of this issue.

@maliming Addition to this, besides just providing one correct set of instructions, it should probably also be mentioned that those instructions are not valid for ABP Commercial customers/users as that source code is not available. Or rather, as I understand it, that further translation is needed. 

Thanks.

**Comment by maliming** [comment]
hi

https://abp.io/support/questions/8415/Problems-with-translating-ABP-confusing-instructions-does-not-seem-to-work-etc#answer-3a16c0b0-9fac-5ba4-1e46-0dd4e3006c8d

I will update the translation document.

Thanks.
