### ISSUE TITLE
I received an error when I went to the settings page on the account I logged in with the tenant.

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#21477]
**App :** Free Blazor Wasm - Mongo (Single layer) 

I received an error when I went to the settings page on the account I logged in with the tenant.

![image](https://github.com/user-attachments/assets/1a0d8c7d-2fb9-412c-b5d3-9945c72645d0)

**Comment by enisn** [comment]
![image](https://github.com/user-attachments/assets/c466c626-8b1c-4816-9395-1060936918a2)
It seems the user doesn't have permission to open that page

---

I'll check and show a better message
