### ISSUE TITLE
Q: using Cached Service Providers - performance impact

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#21476]
Documentation: https://docs.abp.io/en/abp/latest/Dependency-Injection#cached-service-providers
@maliming when this functionality was developed in abp framework - do you have any performance testing results and what "kind" of optimization to expect and how big impact (e.g. reduced CPU usage, lower RAM consumption, lower execution times of API methods,...) can using cached services bring?
Thank you.

**Comment by maliming** [comment]
hi

See 
https://github.com/abpframework/abp/pull/6815

**Comment by leonkosak** [comment]
Maybe it would be beneficial to add these results inside to the documentation somehow?

**Comment by maliming** [comment]
You're right, I will update the `dependency-injection` document to mention this. 👍
