### ISSUE TITLE
MicroserviceDemo have not action?

### ISSUE THREAD

**Issue by qiang999** [abpframework/abp#2147]
i use MicroserviceDemo 1.0.2.
Table have not action?
user : admin
![image](https://user-images.githubusercontent.com/15817336/68647700-74eae200-0559-11ea-8354-1c9c8c484b9d.png)

**Comment by maliming** [comment]
Please use the latest dev branch code.

**Comment by qiang999** [comment]
I update  "@abp/aspnetcore.mvc.ui.theme.basic": "1.0.2",but have not action!
![image](https://user-images.githubusercontent.com/15817336/68650520-28ef6b80-0560-11ea-9589-3dcd2f5a5f39.png)

**Comment by maliming** [comment]
Did you execute the restore package command and the gulp command?
Does the browser's console have any information?

**Comment by qiang999** [comment]
yes,I did execute the restore package command and the gulp command.
The browser's console and the ElasticSearch does not have any information.
![image](https://user-images.githubusercontent.com/15817336/68651425-589f7300-0562-11ea-8e35-7c89418d1597.png)
And Identity management have not role?
![image](https://user-images.githubusercontent.com/15817336/68651618-b92eb000-0562-11ea-9bff-d290dbc4fc05.png)

**Comment by qiang999** [comment]
index.js code
columnDefs: [
                {
                    rowAction: {
                        items:
                            [
                                {
                                    text: l('Edit'),
                                    visible: abp.auth.isGranted('AbpIdentity.Users.Update'),
                                    action: function (data) {
                                        _editModal.open({
                                            id: data.record.id
                                        });
                                    }
                                },
                                {
                                    text: l('Permissions'),
                                    visible: abp.auth.isGranted('AbpIdentity.Users.ManagePermissions'),
                                    action: function (data) {
                                        _permissionsModal.open({
                                            providerName: 'U',
                                            providerKey: data.record.id
                                        });
                                    }
                                },
                                {
                                    text: l('Delete'),
                                    visible: abp.auth.isGranted('AbpIdentity.Users.Delete'),
                                    confirmMessage: function (data) { return l('UserDeletionConfirmationMessage', data.record.userName); },
                                    action: function (data) {
                                        _identityUserAppService
                                            .delete(data.record.id)
                                            .then(function () {
                                                _dataTable.ajax.reload();
                                            });
                                    }
                                }
                            ]
                    }
                },
                {
                    data: "userName"
                },
                {
                    data: "email"
                },
                {
                    data: "phoneNumber"
                }

**Comment by qiang999** [comment]
index.js code:
columnDefs: [
                {
                    rowAction: {
                        items:
                            [
                                {
                                    text: l('Edit'),
                                    visible: abp.auth.isGranted('AbpIdentity.Users.Update'),
                                    action: function (data) {
                                        _editModal.open({
                                            id: data.record.id
                                        });
                                    }
                                },
                                {
                                    text: l('Permissions'),
                                    visible: abp.auth.isGranted('AbpIdentity.Users.ManagePermissions'),
                                    action: function (data) {
                                        _permissionsModal.open({
                                            providerName: 'U',
                                            providerKey: data.record.id
                                        });
                                    }
                                },
                                {
                                    text: l('Delete'),
                                    visible: abp.auth.isGranted('AbpIdentity.Users.Delete'),
                                    confirmMessage: function (data) { return l('UserDeletionConfirmationMessage', data.record.userName); },
                                    action: function (data) {
                                        _identityUserAppService
                                            .delete(data.record.id)
                                            .then(function () {
                                                _dataTable.ajax.reload();
                                            });
                                    }
                                }
                            ]
                    }
                },
                {
                    data: "userName"
                },
                {
                    data: "email"
                },
                {
                    data: "phoneNumber"
                }

**Comment by maliming** [comment]
Try use the latest dev branch code.

**Comment by qq550723504** [comment]
![image](https://user-images.githubusercontent.com/6007227/68727701-25132600-0600-11ea-91aa-cf5c13469a73.png)
![image](https://user-images.githubusercontent.com/6007227/68727867-9521ac00-0600-11ea-8e65-90525347fded.png)

**Comment by qiang999** [comment]
Thanks!
The problem is solved using your method.
