### ISSUE TITLE
Language and user menu buttons do not work

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#21480]
**App:** Blazor Webapp (free template)

![image](https://github.com/user-attachments/assets/b50bf6ca-4036-4629-a03a-77c69efdcc72)

**Comment by jacekmichalski** [comment]
@gizemmutukurt @masum-ulu Is there a fix for that? I'm facing the same problem

**Comment by masum-ulu** [comment]
> @gizemmutukurt @masum-ulu Is there a fix for that? I'm facing the same problem

Hi we're working on it. Blazor WASM or Server is not the problem the new one occurs error (WebApp) we'll try to detech where is the exac problem. We've opened internal issue.

**Comment by jacekmichalski** [comment]
I've also noticed that when using Blazor WebApp and creating a module with Blazor WebAssembly (modular monolith)  when I add menu in the ConfigureMainMenuAsync, the module menu is loading realy slow. I'm not sure if this is linked or not.

**Comment by enisn** [comment]
Hi, this problem has been resolved and it'll be published in the next release. But you can fix it in your own project by editing `wwwroot/bootstrap-patch.js` file in your `Blazor.Client` project. The file content has to be the following:

```js
$(document.querySelectorAll('.dropdown-toggle')).each(function ( index, element ) {

    if (element.getAttribute('data-initialized')) {
        return;
    }

    element.setAttribute('data-initialized', 'true');
    $(element).on("click", function () {
        new bootstrap.Dropdown($(this)).toggle();
    })
});
```


### The problem
It was initialized twice both at Server-Side & Client-Side.

I tried running it only on server-side but sometimes pages are opened directly in wasm runtime. So checking them if they're initialized or not was the best option. It's applied to the templates, so you have to make changes in your template

**Comment by jacekmichalski** [comment]
@enisn This only fixes the problem partially.

My account menu is loaded ok:
![image](https://github.com/user-attachments/assets/3200f47c-cf33-4ec1-ac8f-9e288c952f55)

But as soon as all of the modules are loaded (info: Volo.Abp.Modularity.ModuleManager[0] Initialized all ABP modules.) the my account menu disappears:
![image](https://github.com/user-attachments/assets/be51ff9e-8e3a-430c-bec2-28eb55be5c86)

**Comment by enisn** [comment]
You can add that menu item in the `MenuContributor`:

```csharp
public class MyProjectNameMenuContributor : IMenuContributor
{
    private readonly IConfiguration _configuration;

    public MyProjectNameMenuContributor(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public async Task ConfigureMenuAsync(MenuConfigurationContext context)
    {
        // ...
        if (context.Menu.Name == StandardMenus.User)
        {
            await ConfigureUserMenuAsync(context);
        }
    }

    private async Task ConfigureUserMenuAsync(MenuConfigurationContext context)
    {
        var authServerUrl = _configuration["AuthServer:Authority"] ?? "~";
        var accountResource = context.GetLocalizer<AccountResource>();

        // 👇 This one
        context.Menu.AddItem(new ApplicationMenuItem("Account.Manage", accountResource["MyAccount"], $"{authServerUrl.EnsureEndsWith('/')}Account/Manage", icon: "fa fa-cog", order: 900,  target: "_blank").RequireAuthenticated());
    }

}
