### ISSUE TITLE
 Undefined background job for the job name: Web.Lucene.LuceneIndexArgs

### ISSUE THREAD

**Issue by xiaoyc** [abpframework/abp#2148]
Hi .

I met below issue when i test backgroud jobs . i want to build a lucene index when the application started , so i put the  EnqueueAsync to OnPostApplicationInitialization . but from the log file , i see the below error.

 public override void OnPostApplicationInitialization(ApplicationInitializationContext context)
        {
         ....
 var backgroundJobManager = context.ServiceProvider.GetRequiredService<IBackgroundJobManager>();
            backgroundJobManager.EnqueueAsync(new Lucene.LuceneIndexArgs() { o = "backgroud lucene job" }, delay: new TimeSpan(0, 0, 30));
}

Volo.Abp.AbpException: Undefined background job for the job name: ...Web.Lucene.LuceneIndexArgs
   at Volo.Abp.BackgroundJobs.AbpBackgroundJobOptions.GetJob(String name)
   at Volo.Abp.BackgroundJobs.BackgroundJobWorker.DoWork()
2019-11-12 15:47:00.371 +08:00 [ERR] Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Volo.Abp.Data.AbpDbConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
 ---> Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)

**Comment by maliming** [comment]
Please share your background job related code

**Comment by xiaoyc** [comment]
```
public class LuceneIndexArgs
    {
        public object o { get; set; }
    }
```


LuceneIndexJob
```
 public class LuceneIndexJob : BackgroundJob<LuceneIndexArgs>
    {
        ISeriesService seriesService;
        ILuceneService luceneService;

        public LuceneIndexJob(ISeriesService seriesService, ILuceneService luceneService)
        {
            this.seriesService = seriesService;
            this.luceneService = luceneService;
        }

        public override void Execute(LuceneIndexArgs args)
        {
            var series = seriesService.GetAll(new Dtos.SeriesPagedResultRequestDto() { SkipCount = 0, MaxResultCount = int.MaxValue }).Result;

            IList<SearchEntity> entities = new List<SearchEntity>();

            series.Items.ForEach(s => entities.Add(
                new SearchEntity() { Name = s.Name, Picture = s.Picture, Description = s.Description, Id = s.Id }
                ));

            luceneService.AddToLuceneIndex(entities);

        }
```

web module
```
  [DependsOn(
     ...
        typeof(AbpAutofacModule),
        typeof(AbpIdentityWebModule),
        typeof(AbpAccountWebIdentityServerModule),
        //typeof(AbpAspNetCoreMvcUiBasicThemeModule),
        typeof(AbpAspNetCoreMvcUiMultiTenancyModule),
        typeof(AbpAspNetCoreAuthenticationJwtBearerModule),
        typeof(AbpTenantManagementWebModule),
        typeof(WebCoreMoudle),
        typeof(AbpBackgroundJobsModule)
        )]
    public class YouTubeWebModule : AbpModule

```

**Comment by maliming** [comment]
Inherit the **ITransientDependency** interface

` public class LuceneIndexJob : BackgroundJob<LuceneIndexArgs>, ITransientDependency`
