### ISSUE TITLE
I get the latest dev branch code, micro service demo report error.

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2149]
I get the latest dev branch code, micro service demo report error.
Error NU1105 find "E: \ develop \ lot \ abp \ framework \ SRC \ Volo abp. Localization \ Volo abp. Localization. The csproj" of project information.If you use Visual Studio, this may be because the project has been uninstalled or is not part of the current solution. Run restore from the command line.Otherwise, the project file may be invalid or lack the desired target for restoration.

**Comment by maliming** [comment]
Try run `build-all.ps1` 
https://github.com/abpframework/abp/blob/dev/build-all.ps1

**Comment by 344089386** [comment]
@maliming I promise I ran build-all.ps1, but I still have this problem.

**Comment by maliming** [comment]
You can try to build the project with dotnet cli

**Comment by 344089386** [comment]
@maliming The god really can, but I am very confused about this is what caused.

**Comment by maliming** [comment]
me too.

**Comment by 344089386** [comment]
thanks.
