### ISSUE TITLE
I requested the microservice permission api timeout

### ISSUE THREAD

**Issue by leunghoary** [abpframework/abp#2150]
It takes me a ten seconds to request "/ API /abp/permissions" when providerName=U, but it is ok when providerName=R

**Comment by hikalkan** [comment]
Can you write more details to help us on repeating the problem (For instance, which service you are calling, there are 10+ services/apps)?

**Comment by leunghoary** [comment]
I use the micro service demo to change to a single page, modify the user permission, and call the gateway "/api/abp/permissions?ProviderName =U&providerKey= "interface, it will take a long time, the database is postgresql, I think it may be my server, I am trying to change a server try

**Comment by cnfanhua** [comment]
Abp Version:  vNext 2.9.0
.Net Core: 3.1.103

I have the same problem.
The API is always pending and then it will time out.

![2020-06-09 16-12-39屏幕截图](https://user-images.githubusercontent.com/12975837/84123488-7ab39200-aa6c-11ea-8f46-289447e3ef10.png)
