### ISSUE TITLE
abp 9.0 swagger invoke post api error The required antiforgery header value "RequestVerificationToken" is not present

### ISSUE THREAD

**Issue by RobinGitHub** [abpframework/abp#21524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

abp 9.0  use swagger invoke post api tip 
`
The required antiforgery header value "RequestVerificationToken" is not present
`
in abp 8.0 swagger invoke post api is ok

swagger set
`private void ConfigureSwaggerServices(IServiceCollection services, IConfiguration configuration)
{
    services.AddAbpSwaggerGenWithOAuth(
        configuration["AuthServer:Authority"]!,
        new Dictionary<string, string>
        {
            { "Test", "Test API" }
        },
        options =>
        {
            options.SwaggerDoc("v1", new OpenApiInfo { Title = "Test API", Version = "v1" });
            options.DocInclusionPredicate((docName, description) => true);
            options.CustomSchemaIds(type => type.FullName);
        }
    );
}`
  
![image](https://github.com/user-attachments/assets/1b56aaf1-00e5-40f7-8b20-7dfa7afa741b)

### Version

9.0

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

You can check this pr
https://github.com/abpframework/abp/pull/21444

**Comment by RobinGitHub** [comment]
ok,thanks
