### ISSUE TITLE
Source files cannot be loaded correctly on iis

### ISSUE THREAD

**Issue by obassullu** [abpframework/abp#2152]
While trying to access my application from http://localhost resource files load correctly . 
But when I try to access from http://localhost/tt resource files don't load correctly . 
how can i fix this problem ?

![voloiis](https://user-images.githubusercontent.com/1825965/68690071-77156680-0582-11ea-9d09-8f123d70d499.PNG)

**Comment by mehmetuken** [comment]
Can u share chrome devtools screen(f12) network and console screenshot?

**Comment by obassullu** [comment]
when i install the application on iis root folder resource files load correctly. when i add application with alias on iis resource files cannot be loaded . so i get 404 error

![voloconsole](https://user-images.githubusercontent.com/1825965/68692316-5818d380-0586-11ea-997a-d12b431022c3.PNG)

**Comment by mehmetuken** [comment]
Maybe help this document your problem.
https://docs.microsoft.com/tr-tr/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0#virtual-directories

> IIS Virtual Directories aren't supported with ASP.NET Core apps. An app can be hosted as a sub-application.
