### ISSUE TITLE
New swagger/ui/index.js is not included in the virtual file system as an embedded resource and it's not parsed

### ISSUE THREAD

**Issue by dimitrov9** [abpframework/abp#21538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is a continuation of #21444. It doesn't solve the #21524. 

- The new `framework/src/Volo.Abp.Swashbuckle/wwwroot/swagger/ui/index.js` in `framework/src/Volo.Abp.Swashbuckle/Volo.Abp.Swashbuckle.csproj` is not included in the virtual file system as an embedded resource
- The file is also not injected in `framework/src/Volo.Abp.Swashbuckle/Microsoft/AspNetCore/Builder/AbpSwaggerUIBuilderExtensions.cs`
- I get the following errors when I try to manually include it:
```
Uncaught SyntaxError: Unexpected token '%', "%(ConfigObject)" is not valid JSON
    at JSON.parse (<anonymous>)
    at window.onload (index.js:33:29)
```

### Version

9.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Tiered

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment]
You can try replacing `UseAbpSwaggerUI` with  `UseSwaggerUI` as a temporary solution
