### ISSUE TITLE
Cannot override Identity/Users/index.js

### ISSUE THREAD

**Issue by ejohnson-dotnet** [abpframework/abp#21592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a web project using Abp.  It was using Abp version 8.3, MVC UI, the basic theme.  I had a file `Pages\Identity\Users\index.js` to override the built in `index.js` in the identity module.  It was working fine in version 8.3.x.  I upgraded to 9.0.0 and now the custom `index.js` is not loaded, and the embedded one is instead.

### Reproduction Steps

`abp new BookStore`

Create a new `index.js` file in `Pages\Identity\Users\index.js` in the .Web project.

### Expected behavior

The custom `index.js` is loaded when navigating to the page `Identity\Users`

### Regression?

Yes.  It worked fine in 8.3

### Version

9.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Please share a test project to reproduce.

**Comment by ejohnson-dotnet** [comment]
Here is a sample test project. 

1.  Log in to the website
2.  Navigate to the Users page, `Identity\Users`

There is a custom `index.js` file there which should show a `window.alert` saying "Hello from index.js"

I have attached two zip files. The first `Bookstore-8.2.3.zip` is an Abp version 8.2.3 project and it shows the window.alert message.

The second `Bookstore-9.0.2.zip` is an Abp version 9.0.2 project and it does NOT show the window.alert message.  It does not allow overriding the embedded `index.js`

I have deleted the 'node-modules' and 'libs' folders from both to reduce the size.  You need to run `yarn` and `abp install-libs` to get them to work.

[BookStore-8.2.3.zip](https://github.com/user-attachments/files/18097938/BookStore-8.2.3.zip)
[BookStore-9.0.2.zip](https://github.com/user-attachments/files/18097943/BookStore-9.0.2.zip)

**Comment by ejohnson-dotnet** [comment]
Adding the line
```
options.FileSets.AddEmbedded<BookStoreWebModule>();
```
in the `BookStoreWebModule.cs` file fixes this issue.


Which creates another problem, why does the new `abp` command have different app templates for the old and the new?  Why are the templates not matching?

Why are the new templates not open source?

**Comment by maliming** [comment]
Will fixed by https://github.com/abpframework/abp/pull/21642
