### ISSUE TITLE
Add a document to explain why need the Redis.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#21604]
> For any kind of applications, if the application has more than one instance, they should use redis cache. Simple. Otherwise, every application will have its own internal memory cache for same data and no way to invalidate these data.

**Comment by hikalkan** [comment]
We can simply add a warning to the beginning of https://abp.io/docs/latest/framework/fundamentals/caching (after the current warning box). A separate document is not needed. I can write that.

**Comment by maliming** [comment]
We can add a short URL https://abp.io/why-redis
