### ISSUE TITLE
ICurrentUser all property is null

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2160]
![image](https://user-images.githubusercontent.com/15363011/68747494-9a4d1e00-0635-11ea-8b4a-2e5c32f7b6e7.png)
ICurrentUser is from HttpContext.User, but there is not any claim type = "NameIdentity"
but there is role claim,and ICurrentUser.Role is string[0]
![image](https://user-images.githubusercontent.com/15363011/68747418-738ee780-0635-11ea-8e70-5efcf3ea4a5c.png)

**Comment by maliming** [comment]
You need to provide a detailed description of the problem and the steps to reproduce the problem, not two screenshots.

**Comment by LGinC** [comment]
AuthServer:

1. Create Client:
![image](https://user-images.githubusercontent.com/15363011/68748994-750ddf00-0638-11ea-8460-086e286ca410.png)

2. Get Token:
![image](https://user-images.githubusercontent.com/15363011/68749013-7ccd8380-0638-11ea-9f8e-6968a2134a22.png)

API Host:
1. Add Authentication:
![image](https://user-images.githubusercontent.com/15363011/68749097-a1296000-0638-11ea-916e-4e7c2cabdf4b.png)

2. set Bearer token:
![image](https://user-images.githubusercontent.com/15363011/68749113-aa1a3180-0638-11ea-96de-1b1495889f02.png)

3. request api:
![image](https://user-images.githubusercontent.com/15363011/68749190-c4eca600-0638-11ea-8b97-2fff26ae2e89.png)

**Comment by LGinC** [comment]
ClaimTypes.Email = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
but 
![image](https://user-images.githubusercontent.com/15363011/68749571-683dbb00-0639-11ea-99d6-26fc586425b1.png)

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/68752006-89a0a600-063d-11ea-9a21-0bcb4014f94b.png)
I set AbpClaimTypes.Email = "email" and ICurrentUser.Emaile is correct
but this is any claim type is "Id" in HttpContext.User,so How can I add it

**Comment by LGinC** [comment]
Over. Need to MapAbpClaimTypes in HostModule. 
if you want to get CurrentUser in ProductManagement.Application,and you need map AbpClaimTypes in ProductService.Host
![image](https://user-images.githubusercontent.com/15363011/68757599-287dd000-0647-11ea-9eac-63a9006c70dd.png)
