### ISSUE TITLE
There is no "Manage Account" menu item in Blazor Web App

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#21610]
In the user menu, there is no Manage Account menu item on Blazor Web App:
![image](https://github.com/user-attachments/assets/e0e1ba2e-9202-49e1-a606-3a2939a87d5d)

**Comment by maliming** [comment]
How do you create this `Blazor Web App`?

**Comment by maliming** [comment]
How did you create this `Blazor Web App`?

**Comment by enisn** [comment]
Created with ABP Studio with a freshly created new account _(non-commercial account without license)_

![image](https://github.com/user-attachments/assets/0e72e77f-8e38-4d6f-9f8e-03550918f996)

**Comment by jacekmichalski** [comment]
@enisn Is there a fix for that?

**Comment by enisn** [comment]
> @enisn Is there a fix for that?

It'll be released in the next patch release
