### ISSUE TITLE
Update ng-zorro-antd for Angular

### ISSUE THREAD

**Issue by MichelZ** [abpframework/abp#21627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

warning "@abp/ng.components > ng-zorro-antd@17.4.1" has incorrect peer dependency "@angular/core@^17.0.0".

ng-zorro-antd needs to be 18.x for Angular 18 support
ng-zorro-antd needs to be 19.x for Angular 19 support

This should depend on #21460 and directly be fixed for 19.x

### Describe the solution you'd like

No warnings for ng-zorro-antd

**Comment by masum-ulu** [comment]
Thanks for feedback we'll update this dependency also
