### ISSUE TITLE
Is there ui template that adapts to the abp framework?

### ISSUE THREAD

**Issue by neozhu** [abpframework/abp#2162]
Built-in ui template is too simple！
Is there a recommendation?

**Comment by bobingham** [comment]
I would recommend you put 15 different flavours of Metronic in there....

**Comment by seycan-dev** [comment]
i wonder how to do it.

**Comment by yinchang0626** [comment]
If you are using angular ui,   you can ref my [repository](https://github.com/yinchang0626/abp.ng).
Now i try to change theme to ngx-admin ,ng-alain,or maybe another one but the same way
and keep version is the same  with abp version of ng-packs

**Comment by seycan-dev** [comment]
I use the mvc ui what can i do about it?

**Comment by hikalkan** [comment]
We'll write a theming document: https://github.com/abpframework/abp/issues/631
However, you can inverstigate [the basic theme](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic) to understand how to adapt your UI theme to the framework.

**Comment by wakuflair** [comment]
Me and some ABP fans are intergating [AdminLTE](https://adminlte.io/) to ABP.

![image](https://user-images.githubusercontent.com/3471718/68986486-c2699680-085a-11ea-9386-64347c579934.png)

Once it's ready, It'll be released as an open source theme module.

**Comment by GerryGe** [comment]
> Me and some ABP fans are intergating [AdminLTE](https://adminlte.io/) to ABP.
> 
> ![image](https://user-images.githubusercontent.com/3471718/68986486-c2699680-085a-11ea-9386-64347c579934.png)
> 
> Once it's ready, It'll be released as an open source theme module.

Have you done? Can you share the repository?

**Comment by wakuflair** [comment]
@GerryGe 
It's not ready now, but I push it to GITHUB:

https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE

**Comment by GerryGe** [comment]
> @GerryGe
> It's not ready now, but I push it to GITHUB:
> 
> https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE

Thanks your hard work！
