### ISSUE TITLE
How can add Feature Management ?

### ISSUE THREAD

**Issue by seycan-dev** [abpframework/abp#2163]
I can see users and roles screen but i cant see features screen please help me about how can i see because i cant add new feature

![features isnot avaible](https://user-images.githubusercontent.com/57485673/68763278-1ab95200-0629-11ea-8ae6-10850c89a6c3.png)

**Comment by hikalkan** [comment]
Feature system has not documented yet.  It's purpose and usage is similar to https://aspnetboilerplate.com/Pages/Documents/Feature-Management

Create a class inheriting from the [FeatureDefinitionProvider](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Features/Volo/Abp/Features/FeatureDefinitionProvider.cs) and define the features. They will appear in this screen.

Documentation will come, follow this: https://github.com/abpframework/abp/issues/2188
