### ISSUE TITLE
MultiTenantConnectionStringResolver and TenantStore have an infinite loop

### ISSUE THREAD

**Issue by Y2zz** [abpframework/abp#2164]
[`Volo.Abp.MultiTenancy.MultiTenantConnectionStringResolver`](https://github.com/abpframework/abp/blob/8a74d4bca1b203af02bbde2a49225039cafac811/framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/MultiTenantConnectionStringResolver.cs#L36)
```c#
var tenantStore = serviceScope
                     .ServiceProvider
                     .GetRequiredService<ITenantStore>();

                 var tenant = tenantStore.Find(_currentTenant.Id.Value); // here
```

An infinite loop with [`TenantStore`](https://github.com/abpframework/abp/blob/8a74d4bca1b203af02bbde2a49225039cafac811/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/TenantStore.cs#L73)
```c#
public TenantConfiguration Find(Guid id)
{
    using (_currentTenant.Change(null)) //TODO: No need this if we can implement to define host side (or tenant-independent) entities!
    {
        var tenant = _tenantRepository.Find(id); // here
        if (tenant == null)
        {
            return null;
        }

        return _objectMapper.Map<Tenant, TenantConfiguration>(tenant);
    }
}
```

**Comment by maliming** [comment]
`MultiTenantConnectionStringResolver` needs tenantStore, tenantStore needs to use repository. repository needs to resolve tenant connection string.

But in general, there will be no infinite loops. Because
```
_currentTenant.Change(null)


//No current tenant, fallback to default logic
If (_currentTenant.Id == null)
{
      Return base.Resolve(connectionStringName);
}
```

**Comment by Y2zz** [comment]
When using CurrentTenant.GetId () will enter the MultiTenantConnectionStringResolver, Then TenantStore relies on ITenantRepository and will enter MultiTenantConnectionStringResolver

**Comment by maliming** [comment]
Please provide a project to reproduce the problem.

**Comment by maliming** [comment]
Follow https://github.com/abpframework/abp/issues/2029
