### ISSUE TITLE
Account Module is not user-friendly and reports an error

### ISSUE THREAD

**Issue by lamdieujdo** [abpframework/abp#21640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi ABP Team,

I have been put Account and Password is blank. I saw it. Why? How to fix it?
![Screenshot 2024-12-16 132523](https://github.com/user-attachments/assets/ac4d639e-7874-43d0-b75d-c95f0c6417d6)

### Version

9.0.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

Have you restored the libs by `abp install-libs` command?
Can you share a GIF to show this error?

**Comment by lamdieujdo** [comment]
> restored the libs by `abp install-libs` command

![image](https://github.com/user-attachments/assets/588f7202-0fcd-4281-8fbc-aa58519b4f5a)

My result has been finished!
![image](https://github.com/user-attachments/assets/6edb0eab-d506-4787-a28e-5bd221873629)

Thanks @maliming so much!
