### ISSUE TITLE
Configuring Hangfire as Background Job Manager

### ISSUE THREAD

**Issue by aburakab** [abpframework/abp#2166]
I have a good experience in **Hangfire** but not in **Abp**. 
I created two Web Apps (**BizWebApp** and **BackgroundJobWebApp**).
**BizWebApp** will enqueue the jobs (But not executing it).
**BackgroundJobApp** will pull or dequeue the jobs from hangfire storage and execute it.
I configured **BizWebApp** as follows. 
```C#
Configure<BackgroundJobOptions>(options =>
{
    options.IsJobExecutionEnabled = false; //Disables job execution in the same process
});
```
**BackgroundJobWebApp** is just a hangfire server, nothing more, i added the whole dependencies which is required to execute the job.

I do not want to start **Hangfire** on **BizWebApp** but looks like that using `AbpBackgroundJobsHangfireModule` will make this App a Hangfire server automatically!
even if used `options.IsJobExecutionEnabled = false`.

So running both apps will show two servers on Hangfire Dashboard.
**Hangfire** will choose which server will execute the Job.
If the job executed from where it's enqueued (which is **BizWebApp**) it will succeed. 
But executing it from **BackgroundJobWebApp** will give the following exception:
```
Volo.Abp.AbpException
Undefined background job for the job args type: AIL.WorkflowEngine.ProcessEngine.ProcessExecutionOrderDto, AIL.WorkflowEngine.Application.Contracts, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null

Volo.Abp.AbpException: Undefined background job for the job args type: AIL.WorkflowEngine.ProcessEngine.ProcessExecutionOrderDto, AIL.WorkflowEngine.Application.Contracts, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
   at Volo.Abp.BackgroundJobs.BackgroundJobOptions.GetJob(Type argsType) in D:\Github\abp\framework\src\Volo.Abp.BackgroundJobs.Abstractions\Volo\Abp\BackgroundJobs\BackgroundJobOptions.cs:line 35
   at Volo.Abp.BackgroundJobs.Hangfire.HangfireJobExecutionAdapter`1.Execute(TArgs args) in D:\Github\abp\framework\src\Volo.Abp.BackgroundJobs.HangFire\Volo\Abp\BackgroundJobs\Hangfire\HangfireJobExecutionAdapter.cs:line 24
```

So If want to summarize the problems:

1. Hangfire server should not start just because I added DependsOn: `AbpBackgroundJobsHangfireModule`. It should start only if I called `app.UseHangfireServer()` or wrap the logic in `options.IsJobExecutionEnabled = false`. which I'm expecting that it will turn off the InProc Execution for the jobs.
2. **GetJob** implementation returns `Volo.Abp.AbpException: Undefined background job for the job args type`. Which is weird!

**Comment by chris-stormideas** [comment]
I currently work around this by **not** `Depend`ing on the module, and including the following class in the app enqueues jobs

```
using Volo.Abp.BackgroundJobs.Hangfire;
using Volo.Abp.DependencyInjection;

namespace HMC
{
  [Dependency(ReplaceServices = true)]
  public class LocalHangfireBackgroundJobManager : HangfireBackgroundJobManager
  {
    public LocalHangfireBackgroundJobManager()
    {
    }
  }
}

```

**Comment by aburakab** [comment]
Ohh, thank you. I will try that. 👍

**Comment by aburakab** [comment]
@chris-stormideas Thanks a lot for your suggestion. 
Your suggested solution solved problem number [1] which mentioned above, but problem [2] still exists.
currently, **BizWebApp** only enqueuing the Job, and **BackgroundJobWebApp** is de-queueing it. But I've got this exception. I'm sure that all dependencies are available in **BackgroundJobWebApp**. Did I forget something?

Here is the exception:
```C#
Volo.Abp.AbpException
Undefined background job for the job args type: AIL.WorkflowEngine.ProcessEngine.ProcessExecutionOrderDto, AIL.WorkflowEngine.Application.Contracts, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null

Volo.Abp.AbpException: Undefined background job for the job args type: AIL.WorkflowEngine.ProcessEngine.ProcessExecutionOrderDto, AIL.WorkflowEngine.Application.Contracts, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
   at Volo.Abp.BackgroundJobs.BackgroundJobOptions.GetJob(Type argsType) in D:\Github\abp\framework\src\Volo.Abp.BackgroundJobs.Abstractions\Volo\Abp\BackgroundJobs\BackgroundJobOptions.cs:line 35
   at Volo.Abp.BackgroundJobs.Hangfire.HangfireJobExecutionAdapter`1.Execute(TArgs args) in D:\Github\abp\framework\src\Volo.Abp.BackgroundJobs.HangFire\Volo\Abp\BackgroundJobs\Hangfire\HangfireJobExecutionAdapter.cs:line 24
```

**Comment by chris-stormideas** [comment]
Sorry, missed that!  Im caught out by this all the time:

Make sure the job is being registered in the container, it's not done automatically.  You will usually want to inherit one of these:. `ITransientDependency`/`ISingletonDependency`

On 20 Nov 2019 20:31, Mohammad Aljaber <notifications@github.com> wrote:

@chris-stormideas<https://github.com/chris-stormideas> Thanks a lot for your suggestion.
Your suggested solution solved problem number [1] which mentioned above, but problem [2] still exists.
currently, BizWebApp only enqueuing the Job, and BackgroundJobWebApp is de-queueing it. But I've got this exception. I'm sure that all dependencies are available in BackgroundJobWebApp. Did I forget something?

Here is the exception:

Volo.Abp.AbpException
Undefined background job for the job args type: AIL.WorkflowEngine.ProcessEngine.ProcessExecutionOrderDto, AIL.WorkflowEngine.Application.Contracts, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null

Volo.Abp.AbpException: Undefined background job for the job args type: AIL.WorkflowEngine.ProcessEngine.ProcessExecutionOrderDto, AIL.WorkflowEngine.Application.Contracts, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
   at Volo.Abp.BackgroundJobs.BackgroundJobOptions.GetJob(Type argsType) in D:\Github\abp\framework\src\Volo.Abp.BackgroundJobs.Abstractions\Volo\Abp\BackgroundJobs\BackgroundJobOptions.cs:line 35
   at Volo.Abp.BackgroundJobs.Hangfire.HangfireJobExecutionAdapter`1.Execute(TArgs args) in D:\Github\abp\framework\src\Volo.Abp.BackgroundJobs.HangFire\Volo\Abp\BackgroundJobs\Hangfire\HangfireJobExecutionAdapter.cs:line 24

**Comment by aburakab** [comment]
The Job already implementing `ITransientDependency`.
Here is my class
```C#
public class ApiCallerJob : BackgroundJob<ProcessExecutionOrderDto>, ITransientDependency
{
.... 
}
```
Actually it's going to be executed successfully if I started Hangfire server on **BizWebApp** (maybe because the job enqueued by it). But the exception above will happen if it's executed by **BackgroundJobWebApp**.

**Comment by chris-stormideas** [comment]
And you are DependOn the assembly the job is part of from the background job project?



On 20 Nov 2019 20:55, Mohammad Aljaber <notifications@github.com> wrote:

The Job already implementing ITransientDependency.
Here is my class

public class ApiCallerJob : BackgroundJob<ProcessExecutionOrderDto>, ITransientDependency
{
....
}

Actually it's going to be executed successfully if I started Hangfire server on BizWebApp (maybe because the job enqueued by it). But the exception above will happen if it's executed by BackgroundJobWebApp.

**Comment by aburakab** [comment]
Here is my **background job**
```C#
public class ApiCallerJob : BackgroundJob<ProcessExecutionOrderDto>, ITransientDependency
```
Which is available in this **Abp module**
```C#
    [DependsOn(
        ...
        typeof(WorkflowEngineApplicationContractsModule), // <---- ProcessExecutionOrderDto available here
        typeof(AbpAutoMapperModule),
        ....
        )]
    public class WorkflowEngineApplicationModule : AbpModule
```
And here is my **WebBackgroundJobServerModule**
```C#
    [DependsOn(
       ....
        // WorkflowEngine module
        typeof(WorkflowEngineApplicationModule),
        ....
        )]
    public class WebBackgroundJobServerModule : AbpModule
```
