### ISSUE TITLE
Can not save the correct content-type when upload blob to azure

### ISSUE THREAD

**Issue by hgy225** [abpframework/abp#21670]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hello team,
Now when i upload a svg file like below 
`var blobContainer = LazyServiceProvider.LazyGetRequiredService<IBlobContainer<T>>();
using (var stream = new MemoryStream())
{
    await file.CopyToAsync(stream);
    await blobContainer.SaveAsync(newFileName, stream.ToArray(), true);
}` , then i found the content-type in azure blob is 'application/octet-stream' not 'image/svg+xml', then when i show this svg file in tag img, it can not show correctly, 
i checked the class AzureBlobProvider and found there is no possible to pass the content-type to SaveAsync(BlobProviderSaveArgs args), 

### Describe the solution you'd like

could you enable this feature(allow to pass the content-type) in future version?

**Comment by hgy225** [comment]
@maliming could you have your comment on this?

**Comment by maliming** [comment]
hi

You can override the `SaveAsync` method.

```cs
public override async Task SaveAsync(BlobProviderSaveArgs args)
{
    var blobName = AzureBlobNameCalculator.Calculate(args);
    var configuration = args.Configuration.GetAzureConfiguration();

    if (!args.OverrideExisting && await BlobExistsAsync(args, blobName))
    {
        throw new BlobAlreadyExistsException($"Saving BLOB '{args.BlobName}' does already exists in the container '{GetContainerName(args)}'! Set {nameof(args.OverrideExisting)} if it should be overwritten.");
    }

    if (configuration.CreateContainerIfNotExists)
    {
        await CreateContainerIfNotExists(args);
    }

    if (blobName.EndsWith(".svg", StringComparison.OrdinalIgnoreCase))
    {
        await GetBlobClient(args, blobName).UploadAsync(args.BlobStream, new BlobUploadOptions
        {
            HttpHeaders = new BlobHttpHeaders { ContentType = "image/svg+xml" }
        });
    }
    else
    {
        await GetBlobClient(args, blobName).UploadAsync(args.BlobStream, true);
    }
}
```

https://github.com/abpframework/abp/blob/411d7afa9badfb2ec5a1c7073dcf48043f29392f/framework/src/Volo.Abp.BlobStoring.Azure/Volo/Abp/BlobStoring/Azure/AzureBlobProvider.cs#L37

**Comment by hgy225** [comment]
thank you.
