### ISSUE TITLE
Datatable Actions Not Rendering

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#21674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If there is only one action and this action is not visible in some rows, then the entire column becomes invisible.
Repro project link is below.

### Reproduction Steps

Create a sample project with studio (mvc / ef core / sample crud page). Change the index.js of books page like below. 

```js
{
    title: l('Actions'),
    rowAction: {
        items:
            [
                {
                    text: l('Edit'),
                    visible: function (data) {
                        console.log(data.type);
                        //todo:actions column should be visible if there is any visible actions row.
                        return (abp.auth.isGranted('SingleAction.Books.Edit') && data.type == 3);
                    },
                    action: function (data) {
                        editModal.open({ id: data.record.id });
                    }
                },
            ]
    }
}
```

### Expected behavior

Actions column should be visible if there is any visible actions row.

### Actual behavior

If there is only one action and this action is not visible in some rows, then the entire column becomes invisible.

### Regression?

repro project [https://we.tl/t-tq18dh5OVZ](url)

### Version

9.0.2

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
hi

You can override the `wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js` file

https://github.com/abpframework/abp/pull/21676/files
