### ISSUE TITLE
Is there any way to wrap the 401 result of abp?

### ISSUE THREAD

**Issue by wdwwtzy** [abpframework/abp#2168]
I wanna wrap the 401 result to 200 result and I'm tried use AuthorizeFilter but failed.

**Comment by maliming** [comment]
You can try overriding **DefaultHttpExceptionStatusCodeFinder**

The **IHttpExceptionStatusCodeFinder** is used to automatically determine the HTTP status code. The default implementation is the **DefaultHttpExceptionStatusCodeFinder** class. It can be replaced or extended as needed.

**Comment by wdwwtzy** [comment]
Thanks for your quickly repsonse. I'll try later.
But I aslo want put some content to response body at the same time, can it do that?

**Comment by maliming** [comment]
As above, I think you can override **AbpExceptionHandlingMiddleware**.

**Comment by wdwwtzy** [comment]
I tried it today but it seems there is not a extension point to override or replace the `AbpExceptionHandlingMiddleware`.
Maybe it is a silly question, can you help me?

**Comment by maliming** [comment]
You can implement your own extension methods to use your own middleware.

https://github.com/abpframework/abp/blob/4b682fb2622d96f39ad54cb17824e6890d75132e/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/Builder/AbpApplicationBuilderExtensions.cs#L35

https://github.com/abpframework/abp/blob/4b682fb2622d96f39ad54cb17824e6890d75132e/framework/src/Volo.Abp.AspNetCore/Microsoft/AspNetCore/Builder/AbpApplicationBuilderExtensions.cs#L54

**Comment by wdwwtzy** [comment]
I cant find invoker of `UseUnitOfWork` method in this repository :confused:

**Comment by maliming** [comment]
Try `AbpExceptionFilter`? 🙂

https://github.com/abpframework/abp/blob/4b682fb2622d96f39ad54cb17824e6890d75132e/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs#L68
