### ISSUE TITLE
AWSSDK.S3 version mismatch?

### ISSUE THREAD

**Issue by gvassao** [abpframework/abp#21691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to upgrade my ABP solution from 8.0.2 to 9.0.2. The upgrade seems fine but I'm getting a warning after building the project.

Volo.Abp.BlobStoring.Aws 9.0.2 depends on AWSSDK.S3 (>= 3.7.400.30) but AWSSDK.S3 3.7.400.30 was not found. AWSSDK.S3 3.7.401 was resolved instead.

If go to https://www.nuget.org/packages/AWSSDK.S3/3.7.400.30 it shows the message:  The specified version 3.7.400.30 was not found. You have been taken to version 3.7.410.9.

Am I missing something?

### Reproduction Steps

Run abp update on a 8.0.2 solution

Followed https://learn.microsoft.com/en-us/aspnet/core/migration/80-90?view=aspnetcore-9.0&tabs=visual-studio to upgrade everything else

Compile the solution

### Expected behavior

No warnings after compiling

### Actual behavior

Warning shows: Volo.Abp.BlobStoring.Aws 9.0.2 depends on AWSSDK.S3 (>= 3.7.400.30) but AWSSDK.S3 3.7.400.30 was not found. AWSSDK.S3 3.7.401 was resolved instead.

### Version

8.0.2 to 9.0.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Thanks  @gvassao. I will update the `Directory.Packages.props`. 

You can reference the specified package version for your project.
