### ISSUE TITLE
ABP 9 and wwwroot/libs

### ISSUE THREAD

**Issue by gvassao** [abpframework/abp#21692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After I upgraded my ABP 8.0.2 to 9.0.2, when I run the .Host project it shows the message:

```
The Libs folder under the wwwroot/libs directory is empty!
The Libs folder contains mandatory NPM Packages for running the project.

Make sure you run the abp install-libs CLI tool command.

For more information, check out the [ABP CLI documentation](https://abp.io/docs/latest/CLI#install-libs)
```

It seems that the separated auth server is now behind a paywall. My solution was generated before it became a paid feature.

Running abp install-libs, installs the libs on my .AuthServer project not on my .Host project and now the .Host project complains it doesn't have that folder when it shouldn't need anyway because my auth server is on a separate project

### Reproduction Steps

Run abp update on a 8.0.2 solution

Followed https://learn.microsoft.com/en-us/aspnet/core/migration/80-90?view=aspnetcore-9.0&tabs=visual-studio to upgrade everything else

Compile the solution

dotnet run on the .Host project and open the url on the browser

### Expected behavior

Apps runs successfully

### Actual behavior

App crashses with the message:

```
The Libs folder under the wwwroot/libs directory is empty!
The Libs folder contains mandatory NPM Packages for running the project.

Make sure you run the abp install-libs CLI tool command.

For more information, check out the [ABP CLI documentation](https://abp.io/docs/latest/CLI#install-libs)
```

### Known Workarounds

Manually copy the libs folder from AuthServer to Host project

### Version

8.0.2 to 9.0.2

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

Separate Auth Server

### Operation System

Windows (Default)

**Comment by q51758018** [comment]
I also encountered the same problem. I just want to use WebAPI through Abp and provide interface documentation through Swagger. I don't need the homepage stuff, why do I have to ask for the wwwroot/lib folder

**Comment by oufu99** [comment]
I also encountered the same problem. I just want to use WebAPI through Abp and provide interface documentation through Swagger. I don't need the homepage stuff, why do I have to ask for the wwwroot/lib folder

**Comment by maliming** [comment]
hi

> After I upgraded my ABP 8.0.2 to 9.0.2, when I run the .Host project it shows the message:

Can you share a project to reproduce?

Thanks.

**Comment by fl95149** [comment]
Same problem from 8.1.5 to 8.2.0.

**Comment by maliming** [comment]
Can anyone share a project to reproduce the problem?

**Comment by osilvaa** [comment]
My app is very basic. As you can tell, I use Swashbuckle, provided by ABP. 

In my situation, I upgraded from v8 to v9. If you are able to open one of your v8 *API* projects (i.e. no UI) where you don't have a `package.json` and if you upgrade that to v9,  you will be able to reproduce that.

Please note that I had to manually copy the `libs` folder indicated below as I don't have `package.json` as part of my project

![image](https://github.com/user-attachments/assets/0328aa4c-f612-4c5c-9a80-377b63aaccc9)

**Comment by maliming** [comment]
hi

You can disable the `CheckLibs` feature. I will find a way to prevent this.

```cs
Configure<AbpMvcLibsOptions>(options =>
{
    options.CheckLibs = false;
});
```

**Comment by maliming** [comment]
We have added `how to disable check libs` on the error page.

![image](https://github.com/user-attachments/assets/c8edf6fa-340d-4cea-a54c-53ea986c8206)
