### ISSUE TITLE
Startup calling AbpLocalizationTexts table over 400x

### ISSUE THREAD

**Issue by jasenf** [abpframework/abp#21704]
Hi all --

I've been trying to figure out why abp.io takes so long to load, and randomly turned on verbose logging for EFCore.   What I found was that during application startup, abp seems to be querying the AbpLocalizationTexts hundreds and hundreds of times.

Is this by-design?  It seems like this could be consolidated or temporarily cached during startup to reduce this.

I know my scenario may be a little weird but when I'm trying to debug a remote database, this section of startup is taking over 30 seconds to make 438+ calls to this table.

thank you,
jasen

**Comment by hikalkan** [comment]
@maliming can you please test that.

**Comment by maliming** [comment]
hi @jasenf 

You can try to set `SaveToExternalStore` of `AbpExternalLocalizationOptions` to `false`.

I will find a better solution.

Thanks.

**Comment by jasenf** [comment]
Thanks @maliming 

I’m not sure where I would set that, but this isn’t a critical path item.  I just thought I’d bring it up as it seemed odd.  You guys are so good at this stuff I thought it was my code for a hot minute. 😀

**Comment by maliming** [comment]
hi

In your host project(eg: `XXX.Web`, `XXX.Api.Host`.).

```cs
Configure<AbpExternalLocalizationOptions>(options =>
{
    options.SaveToExternalStore = false;
});
```

**Comment by maliming** [comment]
Hi @jasenf 

This problem will be solved in 9.0.3.
You don't need to set `SaveToExternalStore` after `9.0.3`.

**Comment by HDaoud** [comment]
@maliming is this issue the cause of this support ticket: https://abp.io/support/questions/8484/Login-response-time
if so, and as we are still on 8.x version do we use the workaround you mentioned?

**Comment by maliming** [comment]
hi @HDaoud 

Please create a new question in the support website.

I will refund your ticket and share the source code.

Thanks.
