### ISSUE TITLE
Swagger page shows `404`.

### ISSUE THREAD

**Issue by 1957993455liulong** [abpframework/abp#21723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

我使用abp cli下载了模版，在启动时就不能显示swagger
![image](https://github.com/user-attachments/assets/cc5e7827-eec9-4b03-9769-f576bc8fbfb7)
![image](https://github.com/user-attachments/assets/ea9f407a-6892-4b3d-842e-e457651776c6)

### Expected behavior

显示swagger界面

### Actual behavior

没有显示

### Known Workarounds

我已经看过https://abp.io/support/questions/4455/403-Forbidden---After-Upgrading-to-OpenIdDict，但是没有找到解决方法，我想问一下这个应该bug？

### Version

9

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment]
Please try to upgrade abp packages to `9.0.2`.

#21538
