### ISSUE TITLE
IOptions<IdentityOptions> doesn't change value when set by ISettingManager

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#2176]
In  identity module ,
We have a [AbpIdentityOptionsFactory](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpIdentityOptionsFactory.cs) to create IdentityOptions by abp Settings module.
That is easy to store identityOptions  base on tenant or other [SettingValueProvider](https://github.com/abpframework/abp/blob/dev/docs/en/Settings.md#custom-setting-value-providers)...
but when i set value by [ISettingManager](https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/ISettingManager.cs)( [setting-management module](https://github.com/abpframework/abp/blob/dev/docs/en/Modules/Setting-Management.md#isettingmanager)),
identityOptions doesn't know the value  is changed, below code:
``` csharp
  var oldValue = IdentityOptions.Value.Password.RequiredLength;
  await settingManager.SetGlobalAsync(IdentitySettingNames.Password.RequiredLength, newValue);
  var updatedValue = IdentityOptions.Value.Password.RequiredLength;
```
updatedValue should be newValue but it is oldValue.
@hikalkan :
could you tell me how to enhance [AbpIdentityOptionsFactory](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpIdentityOptionsFactory.cs)  like IOptionsMonitor do .let it can auto change when database(by settingstore) is change.
or  is it now enough that , no need to enhance ?

**Comment by maliming** [comment]
Please see this unit test method.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/identity/test/Volo.Abp.Identity.Domain.Tests/Volo/Abp/Identity/IdentityOptions_Tests.cs#L32-L48

**Comment by yinchang0626** [comment]
@maliming 
thank for reply.
in that unit test doesn't present this question .
it should be in the same scope to  modify value and get value directly like
``` csharp
using (var scope1 = ServiceProvider.CreateScope())
{
    var options = scope1.ServiceProvider.GetRequiredService<IOptions<IdentityOptions>>().Value;
    options.Password.RequiredLength.ShouldBe(6); //Default value
    options.Password.RequiredUniqueChars.ShouldBe(1); //Default value 
    _settingProvider.GetOrNullAsync(IdentitySettingNames.Password.RequiredLength).Returns(Task.FromResult("42"));//====>pretend changed by settingManager
    options.Password.RequiredLength.ShouldBe(42);//=====>error,value is 6
}
```
in fact
it will be fine if modify value by ISettingManager and get value by(IOptions<IdentityOptions>) is in different scope(different http request).
but you should take care in one request  the options  value is different with db.
so i hope to enhance it to advoid mistack
and this is my test code
``` csharp
    public class SampleAppService : EpsyAppService, ISampleAppService
    {
        public IOptions<IdentityOptions> IdentityOptions { get; set; }
        public ISettingManager _settingManager { get; set; }
        public Volo.Abp.SettingManagement.ISettingManager settingManager { get; set; }
        public SampleAppService(){}
        public async Task<object> PostIdentity(string newValue)
        {
            var oldValue = IdentityOptions.Value.Password.RequiredLength;
            await settingManager.SetGlobalAsync(IdentitySettingNames.Password.RequiredLength, newValue);
            var updatedValue = IdentityOptions.Value.Password.RequiredLength;
            return Task.FromResult(new { oldValue, newValue, updatedValue });
        }
    }
```
i use it in SampleController to try it.

**Comment by maliming** [comment]
This is because IOptions is a singleton.  I can't think of any way to enhance it.

**Comment by yinchang0626** [comment]
i found it [ASP.NET Core 2.1 源码学习之 Options[3]:IOptionsMonitor](https://www.cnblogs.com/RainingNight/p/strongly-typed-options-ioptions-monitor-in-asp-net-core.html)
in this article ,the option can watch file change (appsettings.json).
but i have no idea how to do with abp ISettingManager

**Comment by maliming** [comment]
@hikalkan What do you think?

**Comment by hikalkan** [comment]
Options are cached by aspnet core. I don't know if there is a way of invalidating the cache. I should check it deeper.

**Comment by hikalkan** [comment]
Currently, options are cached only for a single request. Normally you update the settings in a separate request, so you can get the new values in the next request.
I am moving this to the next milestone since it is not urgent and there is no problem in most cases.

For now, you may want to set options after changing the setting, so other services can get the latest setting value.

**Comment by DreamTreem** [comment]
@hikalkan 
Is it possible to get updated value through `IOptionsMonitor<> CurrentValue` property or in the `OnChange` method after the value was stored in the `AbpSettings` db table but not to `appsettings.json`?
Currently, `IOptionsMonitor.OnChange `method is triggered by change in the file `appsettings.json`. Storing values via `_settingManager.SetGlobalAsync `has no effect.
