### ISSUE TITLE
Interface parameter format

### ISSUE THREAD

**Issue by KFF1998** [abpframework/abp#21778]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

How to standardize the capitalization of interface parameters？
![image](https://github.com/user-attachments/assets/5920b252-f045-4cff-8199-c4cfc75fbbbb)
PascalCase
![Uploading image.png…]()
camelCase

### Describe the solution you'd like

how  to achieve it，please

**Comment by maliming** [comment]
hi

Your picture is broken.

![image](https://github.com/user-attachments/assets/f57d6036-70fe-40b9-8a02-1ff0d25ec0e4)

**Comment by KFF1998** [comment]
![image](https://github.com/user-attachments/assets/47d8b823-a9f7-454d-b2f7-f2ff4c26c417)
here

**Comment by maliming** [comment]
You can add an `OperatuionFilter` to change the parameter name. This is unrelated with abp framework.


```cs
services.AddAbpSwaggerGen(
options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo { Title = "MyProjectName API", Version = "v1" });
    options.DocInclusionPredicate((docName, description) => true);
    options.CustomSchemaIds(type => type.FullName);
    
    options.OperationFilter<CamelCaseOperationFilter>();
}
);
```
```cs
public class CamelCaseOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        foreach (var operationParameter in operation.Parameters)
        {
            operationParameter.Name = operationParameter.Name.ToCamelCase();
        }
    }
}

```

**Comment by KFF1998** [comment]
> You can add an `OperatuionFilter` to change the parameter name. This is unrelated with abp framework.
> 
> ```cs
> services.AddAbpSwaggerGen(
> options =>
> {
>     options.SwaggerDoc("v1", new OpenApiInfo { Title = "MyProjectName API", Version = "v1" });
>     options.DocInclusionPredicate((docName, description) => true);
>     options.CustomSchemaIds(type => type.FullName);
>     
>     options.OperationFilter<CamelCaseOperationFilter>();
> }
> );
> ```
> 
> ```cs
> public class CamelCaseOperationFilter : IOperationFilter
> {
>     public void Apply(OpenApiOperation operation, OperationFilterContext context)
>     {
>         foreach (var operationParameter in operation.Parameters)
>         {
>             operationParameter.Name = operationParameter.Name.ToCamelCase();
>         }
>     }
> }
> ```

yeah，it is ok，thanks，I'm curious why ABP doesn't add it by default, haha
