### ISSUE TITLE
Handle localized text in UTF-8 format

### ISSUE THREAD

**Issue by duard-sf** [abpframework/abp#2180]
I have found that text containing accents (e.g. "é", "è", "ö") are transmitted as "�" from the server.
I have tried inspecting the source code, but I am unable to find anything useful.

Example:
_nl.json_:
```
{
  "Validation:PasswordLowerCase": "Eén kleine letter"
}
```
response from _application-configuration_ endpoint:
```
{
  localization: {
    values: {
      <app resource>: {
        Validation:PasswordAlphanumeric: "E�n alfanumeriek teken"
      }
    }
  }
}
```

Perhaps during serialization/de-serialization the text is converted to ASCII? How could we specify that localized text should be handled as UTF-8? That being said, should at least UTF-8 not be the default, to be able to support the various characters used in different languages?

**Comment by pranavpatil19** [comment]
same problem in  pt-BR version is weird #2092

**Comment by hikalkan** [comment]
>Perhaps during serialization/de-serialization the text is converted to ASCII

ABP doesn't make something like that. However, we should test this and investigate the root problem. Thanks for reporting.

**Comment by lanpin** [comment]
Related to this?
https://developercommunity.visualstudio.com/content/problem/757607/automatic-ansi-rc-file-conversion-to-utf8-not-want.html

**Comment by duard-sf** [comment]
> ABP doesn't make something like that. However, we should test this and investigate the root problem. Thanks for reporting.

Yes, thank you. This will unfortunately will be quite a blocker, since the website needs to be translated to Dutch. Perhaps in the meantime we could try to use words that do not contain accents 😅 

> Related to this?
> https://developercommunity.visualstudio.com/content/problem/757607/automatic-ansi-rc-file-conversion-to-utf8-not-want.html

I don't think so, since that solution seems to be to update Visual Studio? I am pretty much up to date with the latest version of VS 2019.

**Comment by maliming** [comment]
@duard-sf I will check it out. : )

**Comment by maliming** [comment]
@duard-sf 

You need to modify the encoding format of the json file (UTF-8)

I will update all json to UTF8 encoding.

![image](https://user-images.githubusercontent.com/6908465/69025688-fc759c80-0a02-11ea-9d2a-90ee2164d1d2.png)

![image](https://user-images.githubusercontent.com/6908465/69025779-54ac9e80-0a03-11ea-877e-f9686bb6d754.png)

**Comment by duard-sf** [comment]
Ah, so simple, yet I haven't thought of it! Thanks all for the help, this resolves the issue 👍

**Comment by maliming** [comment]
@hikalkan Should we change all json file encodings to UTF8?
