### ISSUE TITLE
Dapr integration

### ISSUE THREAD

**Issue by geffzhang** [abpframework/abp#2183]
In the Dapr .NET SDK：https://github.com/dapr/dotnet-sdk , you'll find asP.NET Core integration, which brings a state routing controller that responds to publish/subscribe events for other services

**Comment by xdmushui** [comment]
I think if abp.io can integrate Dapr, that would be the best.
@geffzhang  Do you have any good ideas or designs for integrating Dapr?

**Comment by xewn** [comment]
Is it feasible to automatically generate actor server and client through applictionservice?
Make some conventions for actors in Application.Contracts to facilitate the generation of actor server

**Comment by geffzhang** [comment]
Discover that the dotnet team is writing a dapr for dotnet developer e-book https://github.com/dotnet/docs/tree/master/docs/architecture/dapr-for-net-developers

**Comment by geffzhang** [comment]
https://blog.dapr.io/posts/2021/02/17/announcing-dapr-v1.0/

**Comment by leonkosak** [comment]
@hikalkan would you consider using dapr also for [microservice template](https://docs.abp.io/en/commercial/latest/startup-templates/microservice/index) (abp Commercial)? It should greatly simplify overall architecture, right?

**Comment by mooresway** [comment]
Maybe [Project Tye](https://github.com/dotnet/tye) as well? 

- [Introducing Project Tye](https://devblogs.microsoft.com/aspnet/introducing-project-tye/)
- [Developing distributed applications with Tye](https://renatogolia.com/2020/11/12/developing-distributed-applications-with-tye/)
- [Using Tye with Dapr](https://github.com/dotnet/tye/blob/master/docs/recipes/dapr.md)
- [Demo video with David Fowler & Justin Kotalik](https://www.youtube.com/watch?v=prbYvVVAcRs)

Looks like another ms experiment headed towards official status.

**Comment by volethanh** [comment]
Hi @hikalkan , Do you have any plan to integrate Dapr and What release version do you plan ?

**Comment by hikalkan** [comment]
Hi,

In the next milestone (~2 weeks later) we will start to investigate integration possibilities with dapr. As I see, there are some common features with the ABP Framework. When you use the ABP framework, inter-microservice method invocation is simpler than dapr usage. ABP has distributed cache and distributed event bus systems those are easy to use. I mean you have have less need to a tool like dapr with the ABP framework, comparing a solution without ABP.
You can currently use dapr in your ABP solutions (I didn't try, but I don't see any opposite reason). However, we will work more to understand the value that we can add a dapr integration when it works with the ABP. If you have any suggestions, it is appreciated.

We are currently integrating Tye (actually, not hard, you can do it easily), it will be available with the next release.

**Comment by geffzhang** [comment]
There are at least a few aspects of  dapr integration value ，dapr allows you to use part of the content, not all of it
1、dapr actor 
2、grpc

**Comment by Shawn-Fan** [comment]
Dapr is a multi-language supported runtime in the kubernetes/local development environment.  The sidecar(can be used by http and grpc) is the kernel part of the runtime, Dapr affords basic connection to different state storage(redis, cosmos DB, ...), pubsub(redis, nats, kafka,...), autoscale(keda), Actor(so far, only http), and so on...
The key point is that if ABP framwork want to be applied onto kubernetes, it is based on building your own kubernetes enviroment or Dapr.

**Comment by geffzhang** [comment]
The abp eventbus for dapr has been adapted  https://github.com/geffzhang/EasyAbp.Abp.EventBus.Dapr

**Comment by Shawn-Fan** [comment]
cool!

**Comment by colinin** [comment]
The invocation of Dapr.Acotrs can be simplified by using interceptors, Like Volo.Abp.Http.Client

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/124719090-5c52eb00-df39-11eb-85b0-fea926cabd07.png)

Hi, may this issue should be moved to the [5.0-preview](https://github.com/abpframework/abp/milestone/51) milestone?

**Comment by EngincanV** [comment]
Thanks @gdlcf88, I've moved the issue to the 5.0-preview.

**Comment by geffzhang** [comment]
See this dapr integrated module https://github.com/colinin/abp-vue-admin-element-typescript/tree/master/aspnet-core/modules/dapr

**Comment by hikalkan** [comment]
We can't able to work on this in v5.0. We will revisit this later and decide how we can integrate to dapr, or should we integrate.

**Comment by xdmushui** [comment]
> We can't able to work on this in v5.0. We will revisit this later and decide how we can integrate to dapr, or should we integrate.

A little down to hear this news.

**Comment by wallee85** [comment]
is there any news about this issue???

**Comment by maliming** [comment]
No, still in the backlog.

**Comment by 0andy** [comment]
Will abp still consider integrate with Dapr? thx

**Comment by hikalkan** [comment]
We've started investigation for this integration. Branch name is https://github.com/abpframework/abp/tree/dapr-integration

**Comment by hikalkan** [comment]
Moved this to https://github.com/abpframework/abp/issues/13337
