### ISSUE TITLE
Ng routes for lazy-loaded modules not appearing in menu

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2186]
I have a number of modules that I want to appear in the menu, but the menu items are only populated from routes defined in `app-routing.module.ts`. If I move the route `data` attribute to a lazy-loaded sub-module the menu item no-longer shows up. I have tried using `addAbpRoutes` from the `@abp/ng.core` package within the constructor of the `app-module` and the sub-modules with no success.

On the basic Angular application supplied, perform the following steps to reproduce:

In `app-routing.module.ts`, replace the Home route with the following:
```typescript
{
    path: '',
    loadChildren: () => import('./home/home.module').then(m => m.HomeModule),
},
```
In `home-routing.module.ts`, replace the main route with the following:
```typescript
{
    path: '',
    component: ApplicationLayoutComponent,
    data: {
      routes: {
        name: '::Menu:Home',
      } as ABP.Route,
    },
    children: [{ path: '', component: HomeComponent }],
},
```

**Comment by yinchang0626** [comment]
That’s right, menu definition should be in app-routing.module.ts,or early load config module with menu .i think  lazy load module can’t include menu definition

**Comment by olicooper** [comment]
I saw that the [tenant-management-config.service.ts](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/tenant-management/src/lib/tenant-management-routing.module.ts) is configuring the `data` attributes using `addAbpRoutes([{...}])` from the `@abp/ng.core` package but the module is lazy-loaded in [app-routing.module.ts](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/apps/dev-app/src/app/app-routing.module.ts#L27)

I'm don't fully understand Angular routing or module loading, how does this work if they can only be eagerly-loaded in `app-routing.module.ts`? The only other file that seems relevant is [app.module.ts](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/apps/dev-app/src/app/app.module.ts#L31)

I'd like to implement this strategy but I have no clue how it works so I have been unsuccessful in implementing it so far.

**Comment by yinchang0626** [comment]
As I know 
All ABP. Route data is needed to be loaded when the app starts. 
So. ($modulename)ConfigService adds some ABP. Route when ($modulename)ConfigModule be imported in root (AppModule). 
According to angular router rule.
Lazy load module imports dynamic when user into this path. 
So I think
1. All lazy module needs a ConfigModule to do add ABP. Route or
 2. Set ABP. Route data in root routing module (AppRoutingModule)

**Comment by mehmet-erim** [comment]
The `routes` property of `data` must be into the `app-routing.module.ts`.

I will add an action to add your custom page(s) to the menu.

**Comment by mehmet-erim** [comment]
See the usage: https://github.com/abpframework/abp/pull/2425#issue-355018812
