### ISSUE TITLE
Setting management UI document

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2187]
see https://github.com/abpframework/abp/issues/1787#issuecomment-552723266

**Comment by marlonbidu** [comment]
Hi! Any news about this documentation? Thanks

**Comment by bogiahuy** [comment]
how to used ISettingPageContributor. Please for me Document please

**Comment by maliming** [comment]
@bogiahuy There is no documentation yet. But you can refer to this project https://github.com/EasyAbp/Abp.SettingUi for now.
