### ISSUE TITLE
use Directory.Build.props instead of common.props in default templates

### ISSUE THREAD

**Issue by tky753** [abpframework/abp#2189]
The default template use **common.props** to import common properties.
But I find that if I define custom variables in  **common.props** , like
```
<PropertyGroup>
  <AbpVer>1.0.2</AbpVer>
</PropertyGroup>
```
It becomes undefined in MsBuild.

If I rename **common.props** to ** Directory.Build.props**, even I remove `<Import Project="..\..\XXX" />` in csproj file, it still imports custom variables well.

**Comment by maliming** [comment]
I will try it.
https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019

**Comment by tky753** [comment]
After I tried again, I find **common.props** works, variable defined in it can be used in msbuild, it must be my mistake, sorry.
