### ISSUE TITLE
Switch tenant ignore case

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2191]
Hi!

Is it possible to ignore case while trying to switch tenant?
I've tried login with "VMPromotora" following my tests, but when I tried "vmpromotora" it does not found any tenant

If in any scenario it does make sense to have different tenants like "test" "Test" "TeSt", maybe it could have a setting somewhere with default to ignore case

![image](https://user-images.githubusercontent.com/6138475/69008273-67ea3c00-0927-11ea-900e-1f125efed98b.png)
Tenant not found

![image](https://user-images.githubusercontent.com/6138475/69008331-fc549e80-0927-11ea-8e6a-f59532511133.png)
Existing tenant

**Comment by maliming** [comment]
I think the tenant name should be the same as `IdentityUser.NormalizedUserName`, `IdentityRole.NormalizedName`. Especially the subdomain case.

Eg: `Tenant.NormalizedName`

Related discussion: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3767#issuecomment-415692080

**Comment by thiag0coelho** [comment]
Yes, normalize tenant name would work. 

I'm also using PostgreSQL just like #3767. There was any decision on that matter?

**Comment by maliming** [comment]
@ismcagdas What do you think?

**Comment by olicooper** [comment]
It would also be nice if we could get a 'DisplayName' property added to `AbpTenant` if possible?

**Comment by hikalkan** [comment]
It is case insensitive for me. I suppose it is related to the database collation. Mine is "SQL_Latin1_General_CP1_CI_AS" (Case Insensitive)

**Comment by maliming** [comment]
I still think it necessary to add the `Tenant.NormalizedName` property.
