### ISSUE TITLE
Updating AbpAccount and docs to pt-BR

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2194]
I've created a branch to update AbpAccount localization. Later I'll be updating docs. 
Need permission to push my branch and make PR's

![image](https://user-images.githubusercontent.com/6138475/69010000-793c4400-0939-11ea-92a7-dbcf28840d03.png)

**Comment by maliming** [comment]
Abp is an open source github repository, you don't need push permissions.

You can always send pull requests to the Github repository.

1. Clone the ABP repository from Github.
2. Make the required changes.
3. Send a pull request.
