### ISSUE TITLE
Customize user and tenant management UI

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2195]
Hello,

How can i customize this pages ?

**Comment by dicksonkimeu** [comment]
This ?

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio

**Comment by dicksonkimeu** [comment]
Perhaps related, how can customize the menu i.e position it to the left?

**Comment by maliming** [comment]
The document has not been completed. https://github.com/abpframework/abp/issues/631

**Comment by dicksonkimeu** [comment]
Okie, we shall wait.
