### ISSUE TITLE
How to implement like AbpSession.Use(userId,tenantId) in ABP

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2200]
I can find this function in vNext.
AbpSession.Use(useId, tenantId)
UnitOfWorkManager.Current.SetTenantId(tenantId)

ICurrentUser, ICurrentTenant   are both readonly, no set func. So how change it temporily

**Comment by LGinC** [comment]
just find ICurrentTenant.Change ...

**Comment by maliming** [comment]
Duplicate of #887

**Comment by hikalkan** [comment]
see https://github.com/abpframework/abp/blob/dev/docs/en/CurrentUser.md#changing-the-current-principle
