### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by SarcoZ** [abpframework/abp#2209]
1. Can get service before application Initialization?sometimes,like microservice config center,before run want get configuration from config center and then replace iconfiguration ,any other method?
2.Can config service after application Initialization?

**Comment by gdlcf88** [comment]
Dont use title like `some questions`, it is not good for searching.

**Comment by hikalkan** [comment]
Are you asking related to dependency injection? Please write more detailed.

**Comment by SarcoZ** [comment]
@hikalkan  yes,in microservice  scene,appsetting.json only store config center information,when i start application ,i can use dependency injection to get real config from config center,what i want is replace IConfigurationRoot before OnApplicationInitialization method,because some time in OnApplicationInitialization method need read some config

**Comment by SarcoZ** [comment]
@hikalkan I try it, because after serviceprovider build it can not be replace
