### ISSUE TITLE
/api/identity/roles doesn't return ABP.PagedResponse

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2212]
The Identity store model suggests that roles should return a [ABP.PagedResponse](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/identity/src/lib/models/identity.ts#L12)

I need `totalCount` to populate my table data. Could this be added please?

Also see: [identity.state.ts](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/identity/src/lib/states/identity.state.ts#L31)

**Comment by hikalkan** [comment]
Roles page doesn't need to be pages since we think there will not be too many roles in a typical application. The UI should support it.

However, I think we should make it pages for a better standard.

**Comment by thediaval** [comment]
Roles table already has a [paginator attribute](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/identity/src/lib/components/roles/roles.component.html#L29) which is **true** by default in Angular UI.
