### ISSUE TITLE
Custom repository cannot be injected

### ISSUE THREAD

**Issue by mymaizi** [abpframework/abp#2216]
### error log:

2019-11-20 00:21:01.517 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
2019-11-20 00:21:01.571 +08:00 [ERR] {
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "validationErrors": null
}
2019-11-20 00:21:01.574 +08:00 [ERR] An exception was thrown while activating Castle.Proxies.UserAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.UserAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.UserAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'MyWorld.IUserRepository userRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], MyWorld.IUserRepository)'.

### Service part1:
```
public interface IUserAppService: IApplicationService
    {
        Task TestAsync();
    }
public class UserAppService : ApplicationService, IUserAppService
    {
        private readonly IUserRepository _userRepository;
        public UserAppService(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
 public Task TestAsync()
        {
            throw new NotImplementedException();
        }
    }

```

###  Repository part2:
```
public interface IUserRepository : IBasicRepository<User, Guid>
    {
}
 public class UserRepository : EfCoreRepository<MyWorldDbContext, User, Guid>, IUserRepository
    {
        public UserRepository(IDbContextProvider<MyWorldDbContext> dbContextProvider)
        : base(dbContextProvider)
        {

        }
       
    }
```

### Service part3:
```
[DependsOn(
      typeof(MyWorldDomainModule)
      )]
    public class MyWorldEntityFrameworkCoreModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<MyWorldDbContext>(options => {
                options.AddDefaultRepositories();
                options.AddRepository<Users.User, UserRepository>();
            });

            Configure<AbpDbContextOptions>(options =>
            {
                options.UseSqlServer();
            });
        }
    }

[ConnectionStringName("MyWorld")]
    public class MyWorldDbContext: AbpDbContext<MyWorldDbContext>
    {
        public DbSet<Users.User> Users { get; set; }

        public MyWorldDbContext(DbContextOptions<MyWorldDbContext> options)
          : base(options)
        {

        }
    }
```

This project is created manually according to the document. I wonder if it is caused by the fact that I did not introduce relevant modules? Please give me some ideas. Thank you very much

**Comment by maliming** [comment]
Is **Users.User** class **Entity** or **AggregateRoot**?

see https://github.com/abpframework/abp/issues/2108#issuecomment-551124211

**Comment by mymaizi** [comment]
> Is **Users.User** class **Entity** or **AggregateRoot**?
> 
> see [#2108 (comment)](https://github.com/abpframework/abp/issues/2108#issuecomment-551124211)
Aggregate root：
public class User : FullAuditedAggregateRoot<Guid>

**Comment by maliming** [comment]
Can you create a project using the CLI to reproduce the problem?

**Comment by mymaizi** [comment]
> Can you create a project using the CLI to reproduce the problem?

Okay, I'll try

**Comment by mymaizi** [comment]
Because the project is not created by cli, and the storage layer is not added to the dependency due to manual building according to the document[Module Architecture Best Practices & Conventions](https://docs.abp.io/en/abp/latest/Best-Practices/Module-Architecture), internal error (storage injection is not implemented) is caused
