### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2217]
I already have a business system with complete user management and authorization. How can I integrate microservices with my business system?

**Comment by 344089386** [comment]
I have a few ideas:
1. Modify the official identity modules and account modules
2. When creating users and roles in my business system, insert into the table corresponding to abp
3. I added functions required by the business according to the official user role and returned them all when logging in

**Comment by 344089386** [comment]
@maliming

**Comment by maliming** [comment]
I don't know about it.

**Comment by 344089386** [comment]
Well, I'll study it myself.thank you

**Comment by 344089386** [comment]
We decided to drop the old business system.
We develop on the basis of the micro service demo to realize unified authorized login. I think we should modify the official account modules and identity modules, right?
@maliming
