### ISSUE TITLE
EntityUpdatedEto<TEntityEto>should contain OldEntityEto and NewEntityEto

### ISSUE THREAD

**Issue by kefengwei** [abpframework/abp#2218]
We should got the OldValue and NewValue ,when trigger the EntityUpdated event.

**Comment by hikalkan** [comment]
It may not be easy to implement it for all database providers, especially for those has not change tracking, like mongodb.

We can take this as a feature request in the backlog.

**Comment by Trojaner** [comment]
I believe this is a really important feature especially in distributed scenarios.   
E.g. imagine you want to run code when a user's name changes, currently it would be very difficult as the related user update code is in ABP.

**Comment by johnwanzhi** [comment]
This feature is really important, because in many cases it is necessary to record the difference between the old entity and the new entity

**Comment by hikalkan** [comment]
My comment is still valid: https://github.com/abpframework/abp/issues/2218#issuecomment-556093678
