### ISSUE TITLE
请问在app层如何过滤数据？

### ISSUE THREAD

**Issue by easyfast** [abpframework/abp#2219]
`获取数据列表时需要进行一定的条件过滤。发现IRepository只提供了GetList()和GetListAsync()方法。请问如何实现条件过滤呢？`

> /// <summary>
        /// 获取全部可用的租户列表
        /// </summary>
        /// <returns></returns>
        public async Task<List<GetListOutput>> GetList()
        {
            //var data = await _tenantRepository.GetList().Where(o => o.IsActive == true).GetAll().Where(o => o.IsActive == true)
            //    .ToListAsync();
            var data = await _tenantRepository.GetListAsync().Where(o => o.IsActive == true);
            throw new NotImplementedException();
        }

**Comment by xewn** [comment]
whereif
linq

**Comment by gdlcf88** [comment]
To customized methods for a repository, you can create your custom repository.
See https://docs.abp.io/en/abp/latest/Repositories#custom-repositories

By the way, using English or most people can't understand it.

**Comment by riyuexing** [comment]
都可以用中文提issue了？
