### ISSUE TITLE
Angular service / type generator

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2222]
We are in progress of creating a tool to automatically generate typescript service proxies and DTOs to call server-side HTTP APIs.
We are not using NSWAG becase it doesn't cover the features we need. We are trying to generate services and DTOs more aligned to the backend, with less generated code, inheritance & generic classes (probably, not in the first version), modular (generate the code only for desired modules), class per file (instead of single large file)... etc.

Developed on the branch: https://github.com/abpframework/abp/tree/api-definition

**Comment by leonkosak** [comment]
C# enums in DTOs too?

**Comment by hikalkan** [comment]
>C# enums in DTOs too?

Definitely yes.

**Comment by holpit** [comment]
Hi,
We have already done a very similar feature for our dto.
Very simple and useful for us.
If necessary I can share our approach

**Comment by hikalkan** [comment]
>If necessary I can share our approach

It would be appreciated. You can share if it is open source, or share partially with me (send to info@abp.io please). Thanks :)

**Comment by holpit** [comment]
I've sent you a private email with all details.

**Comment by xxyuze** [comment]
Awesome! can we use axios for http request?

**Comment by hikalkan** [comment]
@mehmet-erim what do you think about axios?

**Comment by mehmet-erim** [comment]
I think Axios is a great library for HTTP requests. We can use `axios' within Vue and React applications but I do not recommend for Angular applications because Angular has an HTTP module based on RxJS observable structure.

**Comment by tyson-benson** [comment]
I'm eager to see this feature. I tried using NSwag and was quite disappointed by the limitations you mentioned (single file, lots of boilerplate code). I also found there was no simple way to group the operations into logically named clients with meaningfully-named methods without creating an operation filter and massaging the controller names, crud actions and http methods to create sensible operationId's.

**Comment by tyson-benson** [comment]
The other thing i noticed was that there doesnt appear to be a straightforward way to configure the JSON serialiser settings. Normally I prefer enums serialised as strings. I think this affected the code generated by NSwag, so that only the numeric representations were in the model.
```
export enum RegionType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}
```
I'm hoping this is what @hikalkan was referring to in the [comment above](https://github.com/abpframework/abp/issues/2222#issuecomment-556108064).

**Comment by hikalkan** [comment]
Moved to #2981
