### ISSUE TITLE
api-definition endpoint should also include type definitions

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2223]
To be able to support client side type generation (see #2222).
It will be optional since it makes the api-definition JSON larger:
``/api/abp/api-definition?includeTypes=true``

Developed on the branch: https://github.com/abpframework/abp/tree/api-definition

**Comment by holpit** [comment]
Hi,
We have already done a very similar feature for our dto.
Very simple and useful for us.
If necessary I can share our approach

**Comment by mehmet-erim** [comment]
We need the requirement information of the type parameters. It may be fine to add the `isRequired` field like below:

```
"Volo.Abp.Identity.IdentityRoleDto": {
      "baseType": "Volo.Abp.Application.Dtos.EntityDto<System.Guid>",
       ...
      "properties": [
        {
          "name": "Name",
          "type": "System.String",
          "typeSimple": "string",
+         "isRequired": false
        },
        {
          "name": "IsDefault",
          "type": "System.Boolean",
          "typeSimple": "boolean",
+         "isRequired": true
        },
      ]
    },
```

@hikalkan

**Comment by hikalkan** [comment]
Moved to #2981
