### ISSUE TITLE
Change SQL Server to LocalDb for the startup template connection strings

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2224]
To make it easier to start with since some developers may not have SQL Server installed.

**Comment by gdlcf88** [comment]
Hi @hikalkan 
According to your viewpoint, how about using `MemoryCache` instead of `Redis` for the startup template?

**Comment by wakuflair** [comment]
+1
After creating the ABP solution, the first thing I do is change the connection string to LocalDb.
This is a convenient change.

**Comment by hikalkan** [comment]
>how about using MemoryCache instead of Redis for the startup template

It is already using MemoryCache. It is using Redis only if you create NTiered solution. We can't use in-memory for ntiered, otherwise they can't share the cache.
