### ISSUE TITLE
Endpoint /Account/Manage contains authorization metadata, but a middleware was not found that supports authorization

### ISSUE THREAD

**Issue by nobilegend** [abpframework/abp#2228]
System.InvalidOperationException: Endpoint /Account/Manage contains authorization metadata, but a middleware was not found that supports authorization.
Configure your application startup by adding app.UseAuthorization() inside the call to Configure(..) in the application startup code.
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)

**Comment by nobilegend** [comment]
please help me.

**Comment by hikalkan** [comment]
Did you check if your asp.net core request pipeline configuration has `app.UseAuthorization()` ?

**Comment by Sen-Gupta** [comment]
Looks like this is missing in AuthServer.Host in Microservice Demo as well. 
Added it and it fixed the issues: @liangshiw , in case you are maintaining the project, please include it!

**Comment by ghasemi1994** [comment]
@nobilegend 
use bleow code

      app.UseAuthentication();
      app.UseRouting();
      app.UseAuthorization();
