### ISSUE TITLE
Built-in settings should define the `DisplayName` and the `Description`.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#2229]
DefaultLanguage e.g.:

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Localization/Volo/Abp/Localization/LocalizationSettingProvider.cs#L10

I'm making a UI that allows users to manage the setting values, but It's hard to show a localized string in it because of lacking of the  `DisplayName` and the `Description`.

**Comment by hikalkan** [comment]
OK, we will check these and complete.
You can override/set display name and descriptions of framework-defined settings in your application. In the setting provider, get the setting and set the related properties.

**Comment by maliming** [comment]
Fixed by https://github.com/abpframework/abp/pull/2392
