### ISSUE TITLE
Any plan to have a workflow module?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#2232]
does this project plan to add workflow mudule? Or integrate [https://github.com/elsa-workflows/elsa-core](url) to it?

**Comment by hikalkan** [comment]
Not planned such a module yet. workflow is a wide topic. I don't know if there is a popular library for that. We would think an integration/simplification if there is.

**Comment by xewn** [comment]
[Use Elsa in abpframework](https://github.com/elsa-workflows/elsa-core/issues/468)
Are there any better suggestions?

**Comment by ebicoglu** [comment]
For those who are interested in using Elsa Workflow in ABP, check out:

- [Blog Post — Using Elsa Workflow](https://community.abp.io/posts/using-elsa-workflow-with-the-abp-framework-773siqi9)
- [Elsa Workflow Sample ABP Project](https://github.com/abpframework/abp-samples/tree/master/ElsaDemo)
