### ISSUE TITLE
why I always got ""error": "invalid_client""

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2233]
I want to integrate SPA with abp, the first step is to deal user login,but when I try to get token,I got the error invalid_client.I generate the project with CLI fro test,Below is the screenshots.
<img width="873" alt="step1" src="https://user-images.githubusercontent.com/57399417/69401719-bf761680-0d30-11ea-8793-f64e36234bc1.png">
<img width="1062" alt="step2" src="https://user-images.githubusercontent.com/57399417/69401760-e3395c80-0d30-11ea-99e9-641432a9ebfc.png">

<img width="276" alt="step3" src="https://user-images.githubusercontent.com/57399417/69401728-c735bb00-0d30-11ea-978c-dd9d0c1c7dc0.png">

**Comment by abllyboy** [comment]
I see,this because my password is not correct ,the password should be '1q2w3e*',please note that the passowd is not ‘1q2w3E*’

**Comment by Sniipe** [comment]
Can you update the password on the getting started guide? https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template
