### ISSUE TITLE
permission of microservice

### ISSUE THREAD

**Issue by chi7cha7rito** [abpframework/abp#2234]
I want to manage the user permissions in a react application.
So how can I get the permission list of each micro-service?

**Comment by acid12** [comment]
we did that by referencing the Contracts modules of each microservice/domain in 'identity-microservice' that has the PermissionsApplicationsModule & HttpApiModule .

Calling Permissions endpoints on 'identity-microservice' gives us access to crud like actions, to manage all permissions in system.

Alternatively, you'd need to reference the PermissionManagementModules in each microservice and query each and every microservice for the permissions.
