### ISSUE TITLE
How to seed data when tenant is created?

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2236]
I'd like to seed data in other tables when a tenant is created. I found the [`CreateAsync(TenantCreateDto input)`](https://github.com/abpframework/abp/blob/dev/modules/tenant-management/src/Volo.Abp.TenantManagement.Application/Volo/Abp/TenantManagement/TenantAppService.cs#L46) method but I also see an `IDataSeeder` which seems like the right choice but I'm not sure how to use it?

I saw the BookStore [`BookManagementDataSeedContributor.cs`](https://github.com/abpframework/abp/blob/dev/samples/BookStore-Modular/modules/book-management/src/Acme.BookStore.BookManagement.Domain/Books/BookManagementDataSeedContributor.cs) but I don't know how this fits in when you need to override the tenant module from your own application.

**Comment by gdlcf88** [comment]
Seed data for a created tenant:
```
            using (CurrentTenant.Change(tenant.Id, tenant.Name))
            {
                // All seeders will excute under this tenant.
                await DataSeeder.SeedAsync(tenant.Id);
            }
```

You can choose not to override tenant module but create your custom seed contributor, just like:
https://github.com/abpframework/abp/blob/4efe72c901fa407d45c78c8e89dd0aefb760a3fe/samples/BookStore-Modular/modules/book-management/src/Acme.BookStore.BookManagement.Domain/Books/BookManagementDataSeedContributor.cs#L12

And then when a tenant is created, `TenantManagement` will excute your seeder contributor for it.

**Comment by olicooper** [comment]
Oh wow, I didn't know it would just execute it automatically! I thought I'd have to replace a service or add a dependency to the injector! Very good work guys :)

For anyone else trying this, simply add this to your `Domain` project...
```csharp
public class MultiTenancyDataSeedContributor : IDataSeedContributor, ITransientDependency
{
    private readonly IRepository<Book, Guid> _recipientGroupRepository;
    private readonly IAsyncQueryableExecuter _bookRepository;

    public MultiTenancyDataSeedContributor(
        IRepository<Book, Guid> bookRepository,
        IAsyncQueryableExecuter queryableExecuter)
    {
        _bookRepository = bookRepository;
        _queryableExecuter = queryableExecuter;
    }

    public async Task SeedAsync(DataSeedContext context)
    {
        // perform work here
    }
}
```
The code will be executed when a tenant is created.
