### ISSUE TITLE
How to disable background jobs in development environment?

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2237]
I run a project in production environment, with the same database, sometimes I run the project on my PC, so backgound jobs may be executed on either side.

For now I can use:
```
        Configure<BackgroundJobOptions>(options =>
        {
            options.IsJobExecutionEnabled = false;
        });
```
But it needs to change the code. Is there any other way?

**Comment by ismcagdas** [comment]
You can disable it like this https://github.com/abpframework/abp/blob/dev/samples/BookStore-Modular/modules/book-management/host/Acme.BookStore.BookManagement.HttpApi.Host/BookManagementHttpApiHostModule.cs#L56 for development time.

**Comment by gdlcf88** [comment]
I was forgetting `hostingEnvironment.IsDevelopment()`
