### ISSUE TITLE
How can I Auto Generate DbSet in my DbContext?

### ISSUE THREAD

**Issue by holyrong** [abpframework/abp#2242]
I'm working with abp vnext 1.0。
I want EF Core auto generate DbSet in DbContext。
There is my code in MyDbContext:

`protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            AutoGenerateDbSet(builder);

            /* Configure the shared tables (with included modules) here */

            builder.Entity<AppUser>(b =>
            {
                b.ToTable("AbpUsers"); //Sharing the same table "AbpUsers" with the IdentityUser
                b.ConfigureFullAudited();
                b.ConfigureExtraProperties();
                b.ConfigureConcurrencyStamp();
                //b.ConfigureFullAuditedAggregateRoot();
                b.ConfigureAbpUser();

                //Moved customization to a method so we can share it with the HolyschoolMigrationsDbContext class
                b.ConfigureCustomUserProperties();
            });

            /* Configure your own tables/entities inside the ConfigureHolyschool method */

            builder.ConfigureMyProject();
        }

        private void AutoGenerateDbSet(ModelBuilder builder)
        {
            var assembly = typeof(HolyschoolDomainModule).Assembly;
            foreach (Type type in assembly.ExportedTypes)
            {
                if (type.IsClass
                    && !type.IsGenericType
                    && !type.IsAbstract
                    && type != typeof(Volo.Abp.Domain.Entities.Entity)
                    && typeof(Volo.Abp.Domain.Entities.Entity).IsAssignableFrom(type))
                {
                    if (builder.Model.FindEntityType(type) == null)
                    {
                        builder.Model.AddEntityType(type);
                    }
                }
            }
        }`
**There is not any DbSet<TEntity> in MyDbConext class**。
I find it can't run into the OnModelCreating method,and when calling the api,I've saved exception like ‘**Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2**’

**Comment by maliming** [comment]
Does this code work in EF Core (Without abp framework)?
