### ISSUE TITLE
TPH (Table Per Hierarchy)

### ISSUE THREAD

**Issue by emwagner76** [abpframework/abp#2243]
Hello,

I downloaded the MVC Core starter template from abp.io using the CLI.

I am creating customers and vendors using TPH  (Table Per Hierarchy).

When looking at your documentation, it is telling me to go into the DbContextModelCreatingExtensions class to configure the entities. Usually, I would configure the entity in the OnModelCreating method like so:

            builder.Entity<CustomerVendorBase>() <-- abstract base class
                   .ToTable("CustomerVendor")
                   .HasDiscriminator<string>("RecordType")
                   .HasValue<Customer>("Customer")
                   .HasValue<Vendor>("Vendor");

But, when I am in the DbContextModelCreatingExtensions class, I can specify the .HasDiscriminator, but there is no .HasValue??

**Comment by emwagner76** [comment]
Ok... After hours of thinking... I think I got this TPH table to configure correctly. Figured I would show what I did here, so that others can learn my hours of pain and get it right the first time.

**Domain.Shared project**
I created a folder called **Interfaces**.
I created four interfaces within the Interfaces folder.
```
namespace Retail.OrderSource.Interfaces
{
    public interface IActive
    {
        bool IsActive { get; set; }
    }
}
```

```
namespace Retail.OrderSource.Interfaces
{
    public interface ICommercial
    {
        bool IsCommercial { get; set; }
    }
}
```

```
namespace Retail.OrderSource.Interfaces
{
    public interface ICompany
    {
        string CompanyName { get; set; }
    }
}
```

```
namespace Retail.OrderSource.Interfaces
{
    public interface IDropShip
    {
        bool IsDropShip { get; set; }
    }
}
```

I then moved over to the **.Domain** project and created a folder called **CustomerVendor**.
Customers and Vendors could share properties as well as have their own properties unique to themselves. This is why I did it using **TPH (Table Per Hierarchy)**.

Inside the CustomerVendor folder, I created three classes.
```
using Retail.OrderSource.Interfaces;
using System;
using Volo.Abp.Domain.Entities.Auditing;
namespace Retail.OrderSource.CustomerVendor
{
    public class CustomerVendorBase : AuditedAggregateRoot<Guid>, IActive, ICompany
    {
        public CustomerVendorBase()
        {
            this.IsActive = true;
        }

        public bool IsActive { get; set; }
        public string CompanyName { get; set; }
    }
}
```

```
using Retail.OrderSource.Interfaces;
namespace Retail.OrderSource.CustomerVendor
{
    public class Customer : CustomerVendorBase, ICommercial
    {
        public bool IsCommercial { get; set; }
    }
}
```

```
using Retail.OrderSource.Interfaces;
namespace Retail.OrderSource.CustomerVendor
{
    public class Vendor : CustomerVendorBase, IDropShip
    {
        public bool IsDropShip { get; set; }
    }
}
```

Then I opened up the **DbContext** class and added three DbSet<>
 ```
 public DbSet<CustomerVendorBase> CustomerVendor { get; set; }
 public DbSet<Customer> Customers { get; set; }
 public DbSet<Vendor> Vendors { get; set; }
```

Then I opened up the **DbContextModelCreatingExtensions** class and added the following at the bottom of the ConfigureOrderSource method (OrderSource being my project name):
```
public static void ConfigureOrderSource(this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            builder.Entity<CustomerVendorBase>(cv =>
            {
                cv.ToTable(OrderSourceConsts.DbTablePrefix + "CustomerVendor", OrderSourceConsts.DbSchema);
                cv.ConfigureByConvention();
            });

            builder.Entity<Customer>();
            builder.Entity<Vendor>();
        }
```

I did an **Add-Migration** and the migration file contained the correct schema:
```
migrationBuilder.CreateTable(
                name: "AppCustomerVendor",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    ExtraProperties = table.Column<string>(nullable: true),
                    ConcurrencyStamp = table.Column<string>(nullable: true),
                    CreationTime = table.Column<DateTime>(nullable: false),
                    CreatorId = table.Column<Guid>(nullable: true),
                    LastModificationTime = table.Column<DateTime>(nullable: true),
                    LastModifierId = table.Column<Guid>(nullable: true),
                    **From CustomerVendorBase**
                    IsActive = table.Column<bool>(nullable: false),
                    CompanyName = table.Column<string>(nullable: true),
                    **TPH discriminator column - which I could change the name using Fluent API**
                    Discriminator = table.Column<string>(nullable: false),
                    **From Customer class**
                    IsCommercial = table.Column<bool>(nullable: true),
                    **From Vendor class**
                    IsDropShip = table.Column<bool>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AppCustomerVendor", x => x.Id);
                });
```

**Comment by maxrizwork** [comment]
Hi emwagner I was deadling with a similar problem, trying to customize entities using EF Core TPH.
Did you use interfaces because in this way it's more flexible compared to inheritance of concrete classes?
