### ISSUE TITLE
AbpValidationException doesn't output the message

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2244]
When the exception is thrown, the message supplied in to the constructor is not output to the user.
```json
{
  "error": {
    "code": null,
    "message": "Your request is not valid!",
    "details": "The following errors were detected during validation.\r\n",
    "validationErrors": []
  }
}
```
```csharp
throw new AbpValidationException("Your query is malformed.");
```

**Comment by maliming** [comment]
Thanks for the feedback, I will check it out.

**Comment by hikalkan** [comment]
@olicooper if you want to directly show a message to the user, throw a `UserFriendlyException`.
If you want to return 400, but set your own validation error message, create a new exception class, derive from `AbpValidationException` and implement `IUserFriendlyException`, like this:

````csharp
public class MyValidationException : AbpValidationException, IUserFriendlyException
{
    public MyValidationException()
    {
        
    }

    public MyValidationException(string message)
        : base(message)
    {

    }
}
````

Then throw this exception.
