### ISSUE TITLE
Managing users

### ISSUE THREAD

**Issue by AlphaComposite** [abpframework/abp#2246]
Can someone explain which modules need to be installed and in which order so that we can manage users? I've also seen some pages files in the account module. Are these files merged into an existing solution or do you have to add these files manually? Without any documentation, this basic feature is a blackbox to outsiders who haven't used the older netzero before.

**Comment by maliming** [comment]
> Documentation is in progress, but will get some time. #2138

**Comment by AlphaComposite** [comment]
Until the documentation is done, maybe someone can spell out how to use these particular modules here in this thread.
