### ISSUE TITLE
UnitOfWork.OnCompleted not called?

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#2247]
I was debugging why my distributed entity created event never gets published and that's when I noticed that in `TriggerEventWithEntity` the [following callback](https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/EntityChangeEventHelper.cs#L200) never gets called:
```cs
UnitOfWorkManager.Current.OnCompleted(() =>
{
[BREAKPOINT HERE] return eventPublisher.PublishAsync(eventType, Activator.CreateInstance(eventType, entity));
});
```

However the entity gets created and there is no error. But because the callback does not get called my events won't dispatch. I am using postgresql & rabbitmq modules (ABP 1.0.2)

**Comment by gterdem** [comment]
@Trojaner Hey,
Is there any code piece you can share that I can check to reproduce the behaviour?

**Comment by Trojaner** [comment]
There isn't much code on my side, all I did was create an ETO for an entity, adding related IMapTo to the Entity and adding the ETO to EtoMappings. After that I noticed that the distributed entity events are not fired because UOW.OnCompleted isn't called in ABP's EntityChangeEventHelper.

I was using it in combination with PostgreSQL.

If you still want a reproduction repository let me know.

**Comment by maliming** [comment]
It's best if there is a project that reproduces the problem.

**Comment by Trojaner** [comment]
I tried to reproduce the error in a separate project but failed to so.
I need to investigate more what exactly triggers the issue.
