### ISSUE TITLE
Volo.Abp.AutoMapper not contains the AutoMapFromAttribute in 1.0.2

### ISSUE THREAD

**Issue by w371987114** [abpframework/abp#2258]
I use abp cli command create a solution,and I create Dto module in `*.Application` project
then I `Install-Package Volo.Abp.AutoMapper -Version 1.0.2` and use `AutoMapFrom[]` for the dto module.
the only thing I get from Resharper is install package `Abp.AutoMapper`.
And `using Volo.Abp.AutoMapper;` is suggested `Remove Unnecessary Usings` by visual studio
I do all from this [ABP Documents](https://docs.abp.io/zh-Hans/abp/0.8.0/Tutorials/AspNetCore-Mvc/Part-I),So I think  either the AutoMapFromAttribute type is missing or the documentation is wrong
My module file is like this:
```c#
using System;
using System.ComponentModel.DataAnnotations;
using Volo.Abp.Application.Dtos;
using Volo.Abp.AutoMapper;

namespace Mendy.MessageBoard.Messages.MessageDto
{
    [AutoMapFrom(typeof(Message))]
    public class MessageDto : FullAuditedEntityDto<int>
    {
        /// <summary>
        /// 標題
        /// </summary>
        [Required]
        public string Title { get; set; }

        /// <summary>
        /// 正文
        /// </summary>
        [Required]
        public string Content { get ; set; }
        /// <summary>
        /// 发送时间
        /// </summary>
        public DateTime SendTime { get; set; }
    }
}

```

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1706

**Comment by w371987114** [comment]
I got it
But I always want to know how to add map for `MessageBoardApplicationAutoMapperProfile` in `Volo.Abp.AutoMapper`
there is no `Configuration` property in it after all

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1705

**Comment by w371987114** [comment]
For anyone need it,I write my test ok code in here
```c#
using AutoMapper;
using Mendy.MessageBoard.Messages;
using Mendy.MessageBoard.Messages.MessageDto;

namespace Mendy.MessageBoard
{
    public class MessageBoardApplicationAutoMapperProfile : Profile
    {
       
        public MessageBoardApplicationAutoMapperProfile()
        {
            /* You can configure your AutoMapper mapping configuration here.
             * Alternatively, you can split your mapping configurations
             * into multiple profile classes for a better organization. */
           CreateMap<MessageDto, Message>().ReverseMap();
        }
    }
}
```
Or you can see the tutorial in [Getting Started with AutoMapper in ASP.NET Core](https://code-maze.com/automapper-net-core/)
