### ISSUE TITLE
Hangfire MySQL support?

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2260]
I'm trying to integrate Hangfire in to my application which uses MySQL with help from [the docs](https://docs.abp.io/en/abp/latest/Background-Jobs). I managed to get the application to start but Hangfire has created it's own database tables and isn't integrated with ABP so I must be doing something wrong.

I performed the following steps on the `EntityframeworkCore` project:

1. Installed `Volo.Abp.BackgroundJobs.Hangfire` nuget package.
2. Installed [`Hangfire.Mysql.Core`](https://github.com/stulzq/Hangfire.MySql.Core) for MySQL support.
3. Added code to `PreConfigureServices` similar to the [sample BackgroundJobs module](https://github.com/abpframework/abp/blob/dev/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp.HangFire/DemoAppHangfireModule.cs)
```csharp
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    var configuration = context.Services.GetConfiguration();

    context.Services.PreConfigure<IGlobalConfiguration>(hangfireConfiguration =>
    {
        hangfireConfiguration.UseStorage(new MySqlStorage(configuration.GetConnectionString("Default")));
    });
}
```
4. Added a dependency for the `Domain` project in my new `Scheduler` project.
5. Added `[DependsOn(typeof(AbpBackgroundJobsAbstractionsModule))]` in my new `Scheduler` project/module and set the module up like so:
```csharp
[DependsOn(
    typeof(EverymonDomainModule),
    typeof(AbpAutofacModule),
    typeof(AbpBackgroundJobsAbstractionsModule)
)]
public class MyApplicationSchedulerModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        Configure<AbpBackgroundJobOptions>(options =>
        {
            options.IsJobExecutionEnabled = true;
        });
    }

    public override void OnPostApplicationInitialization(ApplicationInitializationContext context)
    {
        context.ServiceProvider
            .GetRequiredService<MyApplicationSchedulerJobManager>()
            .CreateJobs();
    }
}
```
6. Added dependency from `Application` to `Scheduler` project so the scheduler project is run when the application starts.

Ideally I'd like to have the jobs handled within a `Scheduler` project with a dependency on the `Domain` project to give me access to the domain models because I would like to perform recurring audit log cleansing on the database.

Sorry if I'm being dumb! Any help is much appreciated, thanks!

**Comment by hikalkan** [comment]
Hangfire creates and uses its own tables yes, this is true. The integration point is the API (IBackgroundJobManager, BackgroundJob... etc.).
