### ISSUE TITLE
How to Extend IdentityUserCreateDto properties

### ISSUE THREAD

**Issue by inamvar** [abpframework/abp#2268]
I Added custom properties to `AppUser` Model and now I want to create a new User  with custom properties included. but I can't change Identity user DTOs.
I Still see the default properties in swagger :

![image](https://user-images.githubusercontent.com/6972027/69732165-621f0280-1140-11ea-82e4-1cbeb6c47e0e.png)

 how can I add my custom properties to them?
here is my new properties added to `AppUser`:

![image](https://user-images.githubusercontent.com/6972027/69731876-defdac80-113f-11ea-85c4-acf7a959bf38.png)
and here my  `ConfigureCustomUserProperties` method in `PmsCloudDbContextModelCreatingExtensions` :

![image](https://user-images.githubusercontent.com/6972027/69732036-2d12b000-1140-11ea-8457-7044c765ba10.png)

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2023#issuecomment-546831029

**Comment by inamvar** [comment]
Thanks @maliming. I solved it by Implementing a  new `UserAppService` class and inherit that from `CrudAppService` and  Then I override the `CreateAsync`  method like below: 

![image](https://user-images.githubusercontent.com/6972027/69787051-eae57f00-11d0-11ea-9d8f-a05791933554.png)

It worked properly. 
is that the correct way ?

**Comment by maliming** [comment]
Are you creating a new UserAppService that is independent of the Identity module? Are their routes different?

**Comment by inamvar** [comment]
> Are you creating a new UserAppService that is independent of the Identity module? Are their routes different?

@maliming Yes, it is in another module and has different routes.

**Comment by maliming** [comment]
Although this may solve the problem, we should consider that we can expand the functions in the module, so you can do this temporarily.

**Comment by inamvar** [comment]
@maliming Thanks alot
