### ISSUE TITLE
how to insert login attempt log

### ISSUE THREAD

**Issue by tky753** [abpframework/abp#2273]
For identity server 4 auth, where to do login attempt logging?

**Comment by maliming** [comment]
Consider using Identity Server4 events.
https://identityserver4.readthedocs.io/en/latest/topics/events.html

Or rewrite some components of identity server4.
Example: `AbpResourceOwnerPasswordValidator`
https://github.com/abpframework/abp/blob/dev/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AspNetIdentity/AbpResourceOwnerPasswordValidator.cs#L19

**Comment by tky753** [comment]
Thx, **identity server4 events** works for me.
```C#
public class LoginEventSink: IEventSink, ITransientDependency
{
    public Task PersistAsync(Event evt)
    {
        switch (evt.Id)
        {
            case EventIds.UserLoginSuccess:
                if (evt is UserLoginSuccessEvent userLoginSuccessEvent)
                {
                }
                break;
            case EventIds.UserLoginFailure:
                if(evt is UserLoginFailureEvent userLoginFailureEvent)
                {
                }
                break;
            default:
                break;
        }

        return Task.CompletedTask;
    }
}
```
