### ISSUE TITLE
Allow to write audit logs on exceptions even if disabled for GET requests

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2277]
- [x] Add an option to save audit logs on exceptions on GET requests even if audit log is disabled for GET requests.
- [x] Handle exceptions in the AuditLogMiddleware those might not be handled in the Audit action filter.

**Comment by gterdem** [comment]
We can implement an enum named something like `AuditLogLevel` with; 

- `AuditLogLevel.All` (log both gets and posts)
- `AuditLogLevel.PostOnly` (logs only posts)
- `AuditLogLevel.ExceptionOnly` (logs only exceptions of gets and posts)
- `AuditLogLevel.None` (no logging to db, only logs exceptions to file via ILogger)

What do you think @hikalkan? Is this seems a valid approach?

**Comment by hikalkan** [comment]
Instead add `public bool AlwaysLogOnException { get; set; } = false;`
