### ISSUE TITLE
Use owned entity types to better reflect the aggregates

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2278]
In the modules, we have aggregate roots and entities, where entities are parts of some aggregates.
EF Cores's owned types and owned collections reflect this better and prevents direct usage of an owned type. So, to implement DDD better for EF Core ORM, we can use it: https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities

However, consider shortcomings like;

* Inheritance hierarchies that include owned entity types are not supported

**Comment by maliming** [comment]
By the way, Owned entities have some restrictions in shared tables.

https://github.com/abpframework/abp/issues/2192

`
The navigation property 'MyOwnedEntity' cannot be added to the entity type 'IdentityUser' because the target entity type 'ICollection' is defined in shadow state and navigations properties cannot point to shadow state entities.
`

**Comment by agustinsilvano** [comment]
Hi @hikalkan, 

I saw that you marked this as not planned but in fact it looks like the correct approach to implement DDD, letting the Aggregate to own/manage his entities or value objects. I was trying to implement the same than [Amichai's video](https://youtu.be/5_un3PUER8U?si=glrBUNszG24ZmwZF) and so far everything is achievable but I found two main issues/concerns:
1. I copied and pasted the extension method `ConfigureByConvention` of `EntityTypeBuilder` and adapt it for `OwnedNavigationBuilder`. The issue there is the ObjectExtensions on these owned entities, these should be extended for this new type also.
![image](https://github.com/abpframework/abp/assets/29497274/87dd9d6d-7616-46c9-b36c-87db38fe71b0)

2. My other concern is about the pre-config of the Owned entities. Why we need to do that in ABP? The Amichai's video, [offical docs](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities#collections-of-owned-types), and other [code sample](https://github.com/kgrzybek/modular-monolith-with-ddd/tree/master) don't use that config. 
I was reviewing [this issue](https://github.com/abpframework/abp/issues/2640#issuecomment-575907408) and [this one](https://github.com/abpframework/abp/issues/16091) which looks valid until now.
The fact of having it before the `base.OnModelCreating(builder)` isn't compatible at all with the Configuration pattern for the aggregates.
![image](https://github.com/abpframework/abp/assets/29497274/1a355566-f520-460d-bd04-0932579b2e5c)

About the shared table issue, we are no longer using the shared table for the IdentityUser, right?
