### ISSUE TITLE
Extract AbpDbContext.ConfigureBaseProperties to an extension method

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2279]
Extract AbpDbContext.ConfigureBaseProperties to an extension method, so it can be reused easily.

**Comment by maliming** [comment]
> Extract AbpDbContext.ConfigureBaseProperties to an extension method, so it can be reused easily.

I think [AbpEntityTypeBuilderExtensions](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs) can solve this problem.

> Create similar method for configuring Owned types, because it ignores owned types (#1933).

We can't judge the relationship very accurately. (OwnsOne or OwnsMany) Developers need to manually configure it.

**Comment by hikalkan** [comment]
OK, then I'm closing this. Thanks.
