### ISSUE TITLE
Can't override IdentityUserAppService methods

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2280]
I need to create some other database records when users are created/edited/deleted so I inherited from the `IdentityUserAppService` and tried to `override` the methods. The dev branch shows they are virtual methods [(see here)](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs) but the master branch doesn't [(see here)](https://github.com/abpframework/abp/blob/master/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs). Will this be in the next release? Do you have a time-scale for the next release?
Thank you :)

**Comment by maliming** [comment]
It will be in abp 1.1, There is no release date at this time.
