### ISSUE TITLE
Contribute an ABP setting management UI module

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#2283]
![image](https://user-images.githubusercontent.com/3471718/69897431-faa6c400-1386-11ea-8db3-05c17a49924a.png)

Features:

* Manage ABP setting values via UI
* Support localization
* Control display of the settings via JSON (grouping, form controls, etc.)

Repo URL: https://github.com/wakuflair/Abp.SettingManagement.Mvc.UI

Welcome PRs :blush: .

**Comment by wakuflair** [comment]
Hi 
I refactored this module, now it is called [EasyAbp.Abp.SettingUi](https://github.com/EasyAbp/Abp.SettingUi).

What's new:
* Intergrated with the `Volo.Abp.SettingManagement.Web` module
* Adopted ISSUE https://github.com/abpframework/abp/issues/2229
* Simplified project structures and optimized code
* More complete document with a step-by-step tutorial

Have a try:)

**Comment by hikalkan** [comment]
Great! It seems very helpful to the community. I will check this to see if we should add it to the startup template or merge to this repository. Thanks again.

**Comment by zHaytam** [comment]
Hello, does this only manage ABP's settings? What about the settings we add in our projects?

**Comment by maliming** [comment]
@zHaytam Please check https://github.com/EasyAbp/Abp.SettingUi/blob/master/README.md

**Comment by zHaytam** [comment]
I see that ABP v2.2 is required, does upgrading the NuGet packages versions is enough to upgrade ABP? Or is there a guide to do so properly?

**Comment by maliming** [comment]
@zHaytam 
You can discuss it at https://github.com/EasyAbp/Abp.SettingUi/issues/new.

**Comment by Znow** [comment]
What is the status of this? It is a very much needed feature :)
