### ISSUE TITLE
ABP Zero V8 :  No Authorize button to swagger UI 

### ISSUE THREAD

**Issue by Anshukmr** [abpframework/abp#2286]
I have ABP Zero project(.Net core + Angular) template V8 paid one downloaded. And have found that there is no

>  Authorize Button in Swagger UI

I appreciate any help on this, this is currently blocker to test backend services using swagger.

**Comment by maliming** [comment]
You need feedback in Zero's repository.
https://github.com/aspnetzero/aspnet-zero-core/issues/new

> .Web.Host project contains a basic login page. If you login on this page, you can execute actions on Swagger UI which requires authentication.
