### ISSUE TITLE
Why not a Domain.Abstractions project in template?

### ISSUE THREAD

**Issue by scavarda** [abpframework/abp#2288]
By default in app template there's only a xxx.Domain project but not a Domain.Abstractions or Domain.Contracts project, useful for DI test. In Application layer instead we do have, Why?

**Comment by maliming** [comment]
`Domain.Abstractions` aka [.Domain.Shared](https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain.Shared)  : )

**Comment by scavarda** [comment]
So Domain.Shared must contain also all abstractions for domain services and not only the common types/enums useful for Dtos, right?

**Comment by maliming** [comment]
Please check the documentation: https://docs.abp.io/en/abp/latest/Best-Practices/Module-Architecture#domain-layer
