### ISSUE TITLE
Error on transfer from Dto to model for There is no implicit reference conversion

### ISSUE THREAD

**Issue by dwp008** [abpframework/abp#2290]
Hello 
    I am doing my test follow the sample document  ASP.NET Core MVC Tutorial - Part I. And I get the error on  the step
 public interface IBookAppService : 
        ICrudAppService< //Defines CRUD methods
            BookDto, //Used to show books
            Guid, //Primary key of the book entity
            PagedAndSortedResultRequestDto, //Used for paging/sorting on getting a list of books
            CreateUpdateBookDto, //Used to create a new book
            CreateUpdateBookDto> //Used to update a book
    {    }
the error is 

"DWP.Name.BestNamePattenDto" cannot be used as the type parameter "TEntityDto" in the generic type or method "ICrudAppService <TEntityDto, TKey, TGetListInput>". There is no implicit reference conversion from "DWP.Name.BestNamePattenDto" to "Volo.Abp.Application.Dtos.IEntityDto <int>". 

Here is my model, I not use the AuditedEntityDto<Guid> as in my test

 public class BestNamePatten 
    {
        public int Id { get; set; }
        public int Xing1 { get; set; }
        public int Xing2 { get; set; }
        public int Ming1 { get; set; }
        public int Ming2 { get; set; }
        public int NameLevel { get; set; }
    }
Here is my interface
 public interface IBestNamePattenService : ICrudAppService<BestNamePattenDto,int, PagedAndSortedResultRequestDto> 
    {
    }
Is there any step I missed?
Thanks for help.

**Comment by maliming** [comment]
Try to inherit from ` : AuditedEntityDto<Guid>`

```
public class BestNamePatten :   AuditedEntityDto<Guid>
{
	public int Xing1 { get; set; }
	public int Xing2 { get; set; }
	public int Ming1 { get; set; }
	public int Ming2 { get; set; }
	public int NameLevel { get; set; }
}
```

see https://github.com/abpframework/abp/blob/dev/samples/BookStore/src/Acme.BookStore.Application.Contracts/BookDto.cs#L6
