### ISSUE TITLE
when i debug MicroserviceDemo throw error

### ISSUE THREAD

**Issue by luy710** [abpframework/abp#2295]
引发了异常: System.Private.CoreLib.dll 中的“System.Threading.Tasks.TaskCanceledException”(“A task was canceled.”)

![01](https://user-images.githubusercontent.com/19400252/69953027-6037b380-1533-11ea-96b6-e7cbf31e8618.png)

引发了异常: Elasticsearch.Net.dll 中的“Elasticsearch.Net.ElasticsearchClientException”(“Maximum timeout reached while retrying request”)

![02](https://user-images.githubusercontent.com/19400252/69953180-ac82f380-1533-11ea-8820-97ba4fba5911.png)

**Comment by maliming** [comment]
I think this exception message is already obvious. Please check your ElasticSearch.

![image](https://user-images.githubusercontent.com/6908465/70007012-eb539080-15a9-11ea-95c1-572defb9e43a.png)

**Comment by luy710** [comment]
it's run well , show this error only  debug
