### ISSUE TITLE
.NET Core 3.1 Support

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#2302]
.NET Core 3.1 has been [just released](https://github.com/dotnet/announcements/issues/142)

[ASP.NET Core Bugs](https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aclosed+3.1+in%3Amilestone+is%3Amerged+-label%3Aarea-infrastructure+-involves%3Adotnet-maestro-bot+-involves%3Aapp%2Fdotnet-maestro+) 
[ASP.NET Core Features](https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aclosed+3.1+in%3Amilestone+label%3Aenhancement+label%3Adone)
[ASP.NET Core 3.1 Blog post](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/)

**Comment by viewtance** [comment]
When could release 1.1 with .net core 3.1?

**Comment by maliming** [comment]
I will try to upgrade it.

**Comment by viewtance** [comment]
Why not include this issue to version 1.1 release?

**Comment by hikalkan** [comment]
We will release v1.1.1 with AspNet Core 3.1 in the next week.

**Comment by lanpin** [comment]
@hikalkan Are you waiting for ocelot to support .net core 3.1?

**Comment by maliming** [comment]
@lanpin I have tested that ocelot works in netcore 3.1.
