### ISSUE TITLE
Question: AggregateRoot & DTO

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#2303]
1. What are the best practices for **_DTO's_** for these situations?

- When an AggregateRoot (Book) contains a property that is an AggregateRoot (BookType Type)?

- When an AggregateRoot (Book) contains a property that is a list of AggregateRoot (List<Page> Pages)?

2. Would it be considered bad practice to use a DTO inside of a DTO?

**Module.Domain**
```csharp
public class Book : AuditedAggregateRoot<Guid>, IMultiTenant
{
    public Guid? TenantId { get; set; }

    public virtual string Title { get; set; }
    public BookType Type { get; set; }
    public List<Page> Pages { get; set; }
}

public class BookType : AuditedAggregateRoot<Guid>, IMultiTenant
{
    public Guid? TenantId { get; set; }
    public string Name { get; set; }
}
public class Page : AuditedAggregateRoot<Guid>, IMultiTenant
{
    public Guid? TenantId { get; set; }
    public string Header { get; set; }
    public List<string> Body { get; set; }
    public string Footer { get; set; }
    public int Number { get; set; }
}
```

**Module.Application.Contracts**
```csharp
public class BookDto : AuditedEntityDto<Guid>
{
    public string Title { get; set; }        
  
    // BookType cannot be found because Module.Domain is not referenced
    // Module.Application.Constatns
    public BookType Type { get; set; }  
  
    // Page cannot be found because Module.Domain is not referenced
    // Module.Application.Constatns
    public List<Page> Pages { get; set; } 

    // Bad practice???
    public BookTypeDto Type { get: set; }
    public List<PageDto> Pages { get: set; }

}
```

**Comment by maliming** [comment]
Please check Domain Driven Design documentation.

https://docs.abp.io/en/abp/latest/Domain-Driven-Design
https://github.com/hikalkan/presentations/tree/master/2019-XX-XX%20Implementing%20DDD

![image](https://user-images.githubusercontent.com/6908465/70101646-92026480-1670-11ea-94f4-bf7bfa599ee2.png)

![image](https://user-images.githubusercontent.com/6908465/70101653-96c71880-1670-11ea-9482-379d7559b7b8.png)

![image](https://user-images.githubusercontent.com/6908465/70101662-9e86bd00-1670-11ea-8e41-fd6b94265a4a.png)

![image](https://user-images.githubusercontent.com/6908465/70101674-a47c9e00-1670-11ea-95e6-104d83641069.png)

![image](https://user-images.githubusercontent.com/6908465/70101682-ac3c4280-1670-11ea-9450-c9a0fca4bc6d.png)

![image](https://user-images.githubusercontent.com/6908465/70101690-b6f6d780-1670-11ea-9ecd-55f062ad5436.png)

**Comment by seanalford** [comment]
Thanks @maliming!  I’ve read the documentation several times and still wasn’t quite getting it. The presentation cleared up several things.
