### ISSUE TITLE
why ISettingManager not in Volo.Abp.Settings module

### ISSUE THREAD

**Issue by tky753** [abpframework/abp#2304]
If I do not reference **Volo.Abp.SettingManagement** modules, 
I can't use **ISettingManager**?
I don't need **GlobalSetting**, **TenantSetting** and **UserSetting** in database, 
but ISettingManager is usefaull, 
now I reference **Volo.Abp.SettingManagement.Domain** and **Volo.Abp.SettingManagement.Domain.Shared**, 
but don't reference **Volo.Abp.SettingManagement.EntityFrameworkCore**,
and in module:
```
Configure<SettingManagementOptions>(options =>
{
    options.Providers.Remove<GlobalSettingManagementProvider>();
    options.Providers.Remove<TenantSettingManagementProvider>();
    options.Providers.Remove<UserSettingManagementProvider>();
});
```
It works for me for now, but I'm not sure if it's recommended.

**Comment by maliming** [comment]
The core setting system is pretty independent and doesn't make any assumption about how you manage (change) the setting values. Even the default ISettingStore implementation is the NullSettingStore which returns null for all setting values.

The setting management module completes it (and implements ISettingStore) by managing setting values in a database. See the Setting Management Module(https://docs.abp.io/en/abp/latest/Modules/Setting-Management) document for more.
