### ISSUE TITLE
Document how to switch to different DBMS for EF Core for the app startup template

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2310]
- [x] MySQL
- [x] PostgreSQL
- [x] SQLite
- [x] Others?

**Comment by gterdem** [comment]
Here is a list of [efcore database providers](https://docs.microsoft.com/en-us/ef/core/providers/index?tabs=dotnet-core-cli).

`CosmosDb `can be added as an other.
`MariaDb `uses MySql Provider, maybe requires a few tweaks.

- MySql
- PostgresSql
- SQLite
documentations are ready.

**Comment by hikalkan** [comment]
Moved CosmosDB to another issue and closing this one: https://github.com/abpframework/abp/issues/2532
Thanks.
