### ISSUE TITLE
Does ABP follow DDD Infrastructure layer?

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2311]
I've been reading the documentation that explains the initial ABP architecture in search of where to put a service that make http calls to third party api's. 

https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Application.md
https://github.com/abpframework/abp/blob/dev/docs/en/Domain-Driven-Design.md

On DDD.md it says it follows Infrasctucture layer, but it is unclear to me where I would have access to such functionality and a place for it in the structure.

**Comment by hikalkan** [comment]
Startup solution has not a `Infrastructure` project inside it. The only main infrastructure is the database provider (e.g. EF Core) and it has a separate project.
You can create an `.Infrastructure` project for other type of infrastructure.
