### ISSUE TITLE
DbMigrator and DbMigrations Project

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#2314]
DbMigrator Project and DbMigrations Project included in the Module.Demo project ?

**Comment by hikalkan** [comment]
Didn't understand.

**Comment by xewn** [comment]
The downloaded module project does not include the DbMigrator project

**Comment by maliming** [comment]
You can add migrations to projects in the host directory.

https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Module.md

![image](https://user-images.githubusercontent.com/6908465/70511562-8defae80-1b6a-11ea-931d-144d08523991.png)

**Comment by xewn** [comment]
This is not convenient，A separate project will be much more convenient.
Each time a module is downloaded, need to  add DbMigrator and DbMigrations Project

**Comment by hikalkan** [comment]
The module template is for developing reusable independent modules. You typically use it in a larger project (application) which will already have the DbMigrator project.

Host folder is for hosting the module in a simple application used in the development time (not optimized for production), to help developers easily test what they are building.

So, I believe we should not add such a DbMigrator and DbMigrations projects which is usaful for a real application but not necessary for a module development.
