### ISSUE TITLE
CLI "unstable"

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2315]
Always update abp CLI.
There are error generating templates via CLI (object reference not set to an instance of an object) basically every time that I want to create module or app.

Generating module/app via web page works.

What are the reasons that CLI is so "unstable"?

**Comment by liangshiw** [comment]
I can't reproduce your problem. 
You can try a few more times or download a new project from abp.io.
This issue will be studied in depth after 1.1 https://github.com/abpframework/abp/issues/2049#issuecomment-554669170
