### ISSUE TITLE
How to use cache in css and javascript ?

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#2317]
I am using page speed insight to improve my website. And I have a problem with cache
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fthuviencaudo.net%2F&tab=desktop&hl=en

![image](https://user-images.githubusercontent.com/10234503/70290726-623b9400-180b-11ea-8f74-1b7fabd42917.png)

**Comment by maliming** [comment]
This has nothing to do with ABP, you can refer to the relevant documentation of asp net core.

https://stackoverflow.com/questions/57254048/how-to-cache-static-files-in-asp-net-core
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-3.1#cache-profiles

**Comment by nguyendev** [comment]
don't working
![image](https://user-images.githubusercontent.com/10234503/70294750-11319d00-1817-11ea-91c2-930b38e6c1ea.png)

![image](https://user-images.githubusercontent.com/10234503/70294701-f19a7480-1816-11ea-9a2f-61bc1968a316.png)

**Comment by nguyendev** [comment]
My code.
app.UseStaticFiles(new StaticFileOptions()
            {
                OnPrepareResponse =
                r =>
                {
                    string path = r.File.PhysicalPath;
                    if (path.EndsWith(".css") || path.EndsWith(".js") || path.EndsWith(".gif") || path.EndsWith(".jpg") || path.EndsWith(".png") || path.EndsWith(".svg"))
                    {
                        TimeSpan maxAge = new TimeSpan(7, 0, 0, 0);
                        r.Context.Response.Headers.Append("Cache-Control", "max-age=" + maxAge.TotalSeconds.ToString("0"));
                    }
                }
            });

**Comment by liangshiw** [comment]
You should notice that your static resources are versioned
![image](https://user-images.githubusercontent.com/16813853/70312877-71443580-184f-11ea-9c0c-a23f4df220eb.png)
