### ISSUE TITLE
New tiered option: Merge IdentityServer into Http API

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#2320]
How to use cli cmd to create an mvc project which separate Web and Http api.
When I use --tiered, the project will separate into three, I don't want separate Http Api Host and Identity Server.
Can cli command work for this situation?

![image](https://user-images.githubusercontent.com/6952917/70304839-c9723c00-183d-11ea-993a-c08134918ffd.png)

**Comment by maliming** [comment]
> Can cli command work for this situation?

Not currently supported.

https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Index.md

**Comment by GerryGe** [comment]
> Not currently supported.

Do you have any plan to support this?

**Comment by hikalkan** [comment]
We can take this as a feature request. However, I think separating IDS with HttpApi.Host is essential for tiered, because IDS has login UI and if you merge it top HttpApi then you have HttpApi with some UI which breaks real tiering.
