### ISSUE TITLE
get my-profile error

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2322]
![image](https://user-images.githubusercontent.com/15363011/70314629-d2213d00-1852-11ea-97ef-fb65abcb32a0.png)
get my profile from auth-server
and cannot DI 
![image](https://user-images.githubusercontent.com/15363011/70315232-18c36700-1854-11ea-989f-bb4b603f8cd2.png)

Volo.Abp.Identity.ProfileAppService cannot DependencyInjection IdentityUserManager

**Comment by liangshiw** [comment]
Can't reproduce your problem, can you create a new project via cli to reproduce and upload here

**Comment by LGinC** [comment]
I use old version of MicroService Sample, and I get a new ids4 host proj from abp cli, it work
