### ISSUE TITLE
API GateWay,Ocelot or Apache Apisix?

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#2328]
API gateway, whether to consider Apache apisix?

**Comment by liangshiw** [comment]
https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo
The microservice example uses Ocelot, in fact you can choose any gateway you want

**Comment by xewn** [comment]
like  https://github.com/renardguill/KongRegister

**Comment by xewn** [comment]
like   https://github.com/lianggx/Kong.Net.git

**Comment by xewn** [comment]
abp api automatically register with apache apisix
