### ISSUE TITLE
Not able to use the default Acme.BookStore.Application.Contracts due to .NET Framework Reference instead of Core

### ISSUE THREAD

**Issue by MohanaRanjan** [abpframework/abp#2329]
Hi, I was trying to run the create sample Project using the Tutorials steps and stuck at some point for not able to refer the Models in DTO class. 

**Problem:** Not able to refer the Enum Type defined in Acme.BookStore.Domain in the Acme.BookStore.Application.Contracts.BooksDto.cs due to Dot NET version Mismatch

**Project Name:**
Acme.BookStore.Application.Contracts

**Issue Found:**
While checking the Project Properties it is referencing the .NET SDK 2.0 Version but netcoreapp3.0 is expected. Due to Version mismatch i am not able to include any entity. Since this is the Auto generated using the Abp Cli tool, i wonder how to reference the new Core Project. 

**Reproducing Steps:** 
As in the Tutorial https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I

Thanks,
Mohan

**Comment by liangshiw** [comment]
Can't reproduce your problem, can you create a new project via cli to reproduce and upload here

**Comment by MohanaRanjan** [comment]
Sorry for posting this bug. Actually the error is i did not created the BookType Enum in Acme.BookStore.Domain.Shared project instead i created it in Acme.BookStore.Domain and not able to access it.
I followed the steps and able to create the BookStore App. 

**Resolution**: This is not a bug. It is problem of not following the steps carefully in tutorials.

Thanks for your time  and sorry for wasting that.
