### ISSUE TITLE
Entity Creation/Modification/Deletion Auditing

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#233]
- [x] Standard interfaces.
- [x] Entity base classes.
- [x] DTO base classes.
- [x] Make UserIds Guid, rename properties (remove User postfix).
- [x] Implement and test IAuditPropertySetter.
- [x] EF Core integration.

**Comment by leonkosak** [comment]
@hikalkan Where are "standard interfaces" documented on docs.abp.io?
https://docs.abp.io/en/abp/latest/Entities
There are just Entity and AggregateRoot described.

https://aspnetboilerplate.com/Pages/Documents/Entities
On ASP.NET Boilerplate, there is much more interfaces (IPassivable,...)?

**Comment by hikalkan** [comment]
See https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing and https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing

Not documented all yet.
