### ISSUE TITLE
Missing admin user in AbpUsers

### ISSUE THREAD

**Issue by Sniipe** [abpframework/abp#2331]
Using the sample Angular project.
I ran Update-Database from Acme.BookStore.EntityFrameworkCore.DbMigrator and it ran fine however the admin user wasn't seeded.

When I try and login as admin/1q2w3E* (no tenant selected) I get:
_2019-12-07 21:53:15.918 +00:00 [INF] {"ClientId":"BookStore_App","Category":"Authentication","Name":"Client Authentication Failure","EventType":"Failure","Id":1011,"Message":"Unknown client","ActivityId":"8000000c-000b-ff00-b63f-84710c7967bb","TimeStamp":"2019-12-07T21:53:15.0000000Z","ProcessId":3624,"LocalIpAddress":"::1:44322","RemoteIpAddress":"::1","$type":"ClientAuthenticationFailureEvent"}
2019-12-07 21:53:15.918 +00:00 [ERR] No client with id 'BookStore_App' found. aborting_

Any suggestions?

**Comment by pointlevel** [comment]
Try to run the console-application DbMigrator. (Set it as Startup-project and run)
