### ISSUE TITLE
Question: ValueObject Persistance

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#2334]
How should value object's be persisted?

Lets use the **_IssueLabel_** value object from @hikalkan's presentation as an example.  

![image](https://user-images.githubusercontent.com/8544833/70392831-cbf5a280-19b1-11ea-879b-537d310941f7.png)

Unfortunately, **_IssueLabel_** isn't fully implemented in the supplemental **Acme.DddDemo** solution. 

_**IssueLabel**_ (**Acme.DddDemo.Domain\Roles\Roles.cs**)
```csharp
public class IssueLabel
{
}
```

So, based on the documentation from [ASP.NET Boilerplate](https://aspnetboilerplate.com/Pages/Documents/Value-Objects) I've come up with this implementation for **_IssueLabel_**

```csharp
public class IssueLabel : ValueObject
{   
    public Guid IssueId { get; private set; }
    public Guid UserId { get; private set; }

    public IssueLabel()
    {
    }

    public IssueLabel(Guid issueId, Guid userId)
    {
        IssueId = issueId;
        UserId = userId;
    }

    protected override IEnumerable<object> GetAtomicValues()
    {
        yield return IssueId;
        yield return UserId;
    }
}
```

Now, how do we persist this the value object?

**Comment by hikalkan** [comment]
Use owned types in EF Core: https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#collections-of-owned-types

**Comment by seanalford** [comment]
Wow that was a fast resonance @hikalkan! Thanks!

**Comment by hikalkan** [comment]
You're welcome. I'm closing this, reopen if you have additional questions while I can't promise that fast in the future :D

**Comment by seanalford** [comment]
@hikalkan does ABP.IO have a distillation document of best practices for the Domain Layer?

- Aggregates
- AggregateRoots
- Entities
- ValueObjects

As a new comer to DDD, I'm still struggling with few concepts.  I was thinking about creating one here (Doc\Domain Driven Design\Domain Layer\Best Practices.md) for future new comers, but don't want to duplicate efforts if one already exists.  

I was planning on basically boiling down presentation into a short lists of Do's and Don't's along with some other notes.

**Comment by hikalkan** [comment]
See  https://docs.abp.io/en/abp/latest/Domain-Driven-Design

Also see https://docs.abp.io/en/abp/latest/Best-Practices/Index for best practices. For example, for aggregate roots and entities: https://docs.abp.io/en/abp/latest/Best-Practices/Entities

**Comment by gdlcf88** [comment]
Hi @seanalford , could you share your final code?

**Comment by seanalford** [comment]
@gdlcf88 yes in about 12 hours. I’ve already pack up the laptop for the night.

**Comment by seanalford** [comment]
@gdlcf88 you can find @hikalkan code here [Acme.DddDem](
https://github.com/hikalkan/presentations/tree/master/2019-XX-XX%20Implementing%20DDD/src) and make the above changes yourself if you don’t want to make.

Note the Issue code is defined in the Domain\Roles.cs file.

**Comment by sam0817** [comment]
just for reference:
need to set Owned<T> in OnModelCreating,
or will get Exception

https://github.com/abpframework/abp/issues/1933#issuecomment-559539505
