### ISSUE TITLE
Edit layout and style of pages

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#2335]
How do I edit the layout and style of pages e.g. login etc. ? as there doesn't appear to be any css or html I can edit in the solution?

I also need to add my own template and this will involve moving the menu to down the left side of the page. As it stands the default layout is ugly but that is ok as I'd rather not have the headache of a preinstalled template like Metronic cluttering up the project.

**Comment by liangshiw** [comment]
see https://docs.abp.io/en/abp/latest/Virtual-File-System#virtual-file-system

**Comment by KevinFarrow** [comment]
> 
> 
> See https://docs.abp.io/en/abp/latest/Virtual-File-System#virtual-file-system

Yup, seen that page but it doesn't answer the question!
