### ISSUE TITLE
Extend and manage existing entities

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#2336]
As I move my code from Zero to abp.io I need to extend some of the existing tables, namely the AbpUsers and AbpTenants (or whatever the equivalent tables are). I also need to add the new fields to the editable pages for managing any changes.

I understand the documentation is still poor but could you let me know how I can achieve this?

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Virtual-File-System#virtual-file-system

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/issues/469#issuecomment-425720097
