### ISSUE TITLE
Multi Tenancy - Fails to Connect - Separate SQL Database Connection String for each Tenant

### ISSUE THREAD

**Issue by AidanTfL** [abpframework/abp#2338]
Hey,  I thought I'd try out the standard layered ASP.NET Core 3.1 Abp.io template available at: https://Abp.io

I've followed the setup instructions, running the migration scripts to create the host database in localdb, and am able to successfully load the UI.

I login with the default credentials, then I create a new Tenant under 'Tenant Management' in the UI. I specify a custom database connection string for that tenant.

I open SQL Server Management Studio and create an empty database matching this in localdb.

Next, I logout of the admin host user, then press 'switch tenant' and type in the tenant name I just created. It gets stuck on loading, and there's a bunch of SQL Exceptions, then finally it gives up and shows the unable to connect error.

What steps do I need to take to setup a separate database for a tenant? Are there any migration scripts I need to run after creating the empty database?

**Comment by AidanTfL** [comment]
When I repeat the process using a SQL Server running on localhost, instead of localdb, it is able to connect. I receive the following error:

An unhandled exception occurred while processing the request.
SqlException: Invalid object name 'AbpSettings'.
Microsoft.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__164_0(Task<SqlDataReader> result)

DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Volo.Abp.Identity.IdentityUserStore, Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Identity.IdentityOptions], Microsoft.AspNetCore.Identity.IPasswordHasher`1[Volo.Abp.Identity.IdentityUser], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Identity.IUserValidator`1[Volo.Abp.Identity.IdentityUser]], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Identity.IPasswordValidator`1[Volo.Abp.Identity.IdentityUser]], Microsoft.AspNetCore.Identity.ILookupNormalizer, Microsoft.AspNetCore.Identity.IdentityErrorDescriber, System.IServiceProvider, Microsoft.Extensions.Logging.ILogger`1[Volo.Abp.Identity.IdentityUserManager], Volo.Abp.Threading.ICancellationTokenProvider)' on type 'IdentityUserManager'.
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

DependencyResolutionException: An exception was thrown while activating Microsoft.AspNetCore.Identity.SignInManager`1[[Volo.Abp.Identity.IdentityUser, Volo.Abp.Identity.Domain, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]] -> λ:Microsoft.AspNetCore.Identity.UserManager`1[[Volo.Abp.Identity.IdentityUser, Volo.Abp.Identity.Domain, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]] -> Volo.Abp.Identity.IdentityUserManager.
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters, out object decoratorTarget)

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1371

**Comment by AidanTfL** [comment]
Thank you @maliming for re-raising the issue - I appreciate that 👍  @hikalkan mentions that it is in the startup file so I can make changes there. Can you advise what changes I need to make?
