### ISSUE TITLE
how to change the listening address when run the project in product environment

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#2339]
in the product environment, it's normally  work in the below address, however what i configured is https://localhost:44348. 

> Now listening on: http://localhost:5000
> Now listening on: https://localhost:5001

**Comment by johnnba** [comment]
`private void ConfigureUrls(IConfiguration configuration)
        {
            Configure<AppUrlOptions>(options =>
            {
                options.Applications["MVC"].RootUrl = configuration["App:SelfUrl"];
            });
        }
`
the above code doesn't work. it's a puzzled problem.

**Comment by maliming** [comment]
Do you want to change the binding endpoint of kestrel?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#endpoint-configuration

**Comment by johnnba** [comment]
yes, the post blog solved my problem. sincerely thanks. @maliming 
here is my way to solve the problem, it's not so perfect but get worked and  can be refferenced by anyone who has the same demand.

```
 internal static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    var config = new ConfigurationBuilder()
                        .SetBasePath(Directory.GetCurrentDirectory())
                        .AddJsonFile("appsettings.json", optional: true)
                        .Build();
                    webBuilder.
//                        ConfigureKestrel(serverOptions =>
//                        {
//                             serverOptions.ListenAnyIP(44348);
//                        }).
                        UseConfiguration(config).
                        UseUrls(config["App:SelfUrl"]).
                        UseStartup<Startup>();
                    webBuilder.UseShutdownTimeout(TimeSpan.FromSeconds(10));
                })
                .UseAutofac()
                .UseSerilog();
    }
```
