### ISSUE TITLE
Create Template without Abp.IdentityServer?

### ISSUE THREAD

**Issue by crashsol** [abpframework/abp#2340]
can provide creation templates that don't  install  abp.identityserver ？

**Comment by hikalkan** [comment]
We can not manage that much template. Current template is already complicated and supports different scenarios.

I think most of the applications need to serve a REST API and IDS4 is a good way to authenticate clients using OAuth. Setting up the IDS4 is a bit hard, but deleting it from an application is relatively easy. So, please delete it for your application for now.

But we will consider to make it optional in the future releases. Thank you for the feature request.

**Comment by crashsol** [comment]
thank you

**Comment by hikalkan** [comment]
Keep this open to consider in the next versions.

**Comment by arashraf** [comment]
> 
> 
> We can not manage that much template. Current template is already complicated and supports different scenarios.
> 
> I think most of the applications need to serve a REST API and IDS4 is a good way to authenticate clients using OAuth. Setting up the IDS4 is a bit hard, but deleting it from an application is relatively easy. So, please delete it for your application for now.
> 
> But we will consider to make it optional in the future releases. Thank you for the feature request.

Can you please provide some guidelines to how to remove the Identity server from Angular Project
