### ISSUE TITLE
Upgrade Angular version to 9 and make Ivy the default compiler

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#2345]

**Comment by Y2zz** [comment]
Wow, so radical, I like

**Comment by kefengwei** [comment]
https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3
The version 9 is released.. When we can upgrade too?

**Comment by mehmet-erim** [comment]
We have started to work. If we don't encounter a problem caused by Ivy, we will update it as soon as possible.

**Comment by fowardyehuo** [comment]
Looking forward to the update of 9
