### ISSUE TITLE
Void migrations generated from standard ABP template (doc update needed?)

### ISSUE THREAD

**Issue by scavarda** [abpframework/abp#2358]
I've built up a new solution from template

```
abp new MyApp --ui mvc --tiered
```

- Added Entities and DBSets inside MyAppDbContext, ```MyApp.EntityFrameworkCore``` project
- Selected ```MyApp.HttpApi.Host``` as Startup Project
- In ```Package Manager Console``` selected ```MyApp.EntityFrameworkCore.DbMigrations``` as default project
- In ```Package Manager Console``` executed
```
Add-Migration MyFirstMigration
```

But Migrations are void:
```cs
public partial class MyFirstMigration : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
```

The error is because it uses ```MyAppMigrationsDbContext``` instead of ```MyAppDbContext```
If I follow the code execution the following lines are invoked:
```
context.Services.AddAbpDbContext<MyAppDbContext>();
context.Services.AddAbpDbContext<MyAppMigrationsDbContext>();
```

How can I generate the migration for the first one (```MyAppDbContext```) ?
- In ```Package Manager Console``` also tried
```
Add-Migration MyFirstMigration -c MyApp.EntityFrameworkCore.MyAppDbContext
```
```
>> No DbContext named 'MyApp.EntityFrameworkCore.MyAppDbContext' was found.
```

I've read the doc but found nothing about, I think it doesn't cover the ```MyApp.EntityFrameworkCore.DbMigrations``` project:

https://docs.abp.io/en/abp/latest/Best-Practices/Entity-Framework-Core-Integration
https://docs.abp.io/en/abp/latest/Entity-Framework-Core

**Comment by maliming** [comment]
Have you configured your entity?

```
/* Configure your own tables/entities inside here */

//builder.Entity<YourEntity>(b =>
//{
//    b.ToTable(MyProjectNameConsts.DbTablePrefix + "YourEntities", MyProjectNameConsts.DbSchema);

//    //...
//});
```

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContextModelCreatingExtensions.cs#L14

**Comment by scavarda** [comment]
No thanks, now I just see the point
https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-I#configure-your-book-entity

```
builder.ConfigureDirector();
```
is called both from ```MyAppDbContext.OnModelCreating(ModelBuilder builder)``` and ```MyAppMigrationsDbContext.OnModelCreating(ModelBuilder builder)```


But why is so important to configure each Entities? Is there an extension method to automatically configure each DbSet present in ```MyAppDbContext``` or is a bad practice?
```cs
builder.Entity<YourEntity_1>(b =>
{
    b.ToTable(DirectorConsts.DbTablePrefix + "YourEntities_1", DirectorConsts.DbSchema);
    b.ConfigureByConvention();  // auto configure for the base class props
    //...
});
builder.Entity<YourEntity_2>(b =>
{
    b.ToTable(DirectorConsts.DbTablePrefix + "YourEntities_2", DirectorConsts.DbSchema);
    b.ConfigureByConvention();  // auto configure for the base class props
    //...
});
```

**Comment by maliming** [comment]
see:
https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContext.cs#L10-L18

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/MyProjectNameMigrationsDbContext.cs#L15-L19

**Comment by scavarda** [comment]
Perfect
