### ISSUE TITLE
how to integrate with oidc-client ?

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2360]
when I  use the original IdentityServer4 to  integrate with oidc-client ,it works well,but when I use ABP's "AuthServer.Host" is say "unauthorized_client" and "Invalid scope for client".

Here is the code with original IdentityServer4:
<img width="749" alt="0" src="https://user-images.githubusercontent.com/57399417/70507440-55020a80-1b67-11ea-9cd0-c5229a140864.png">
<img width="751" alt="1" src="https://user-images.githubusercontent.com/57399417/70507514-795de700-1b67-11ea-951b-70be27fa9cb5.png">

 
<img width="768" alt="5" src="https://user-images.githubusercontent.com/57399417/70510507-3c472400-1b6a-11ea-98c3-40bb09438db4.png">

It works well. Below is the add client code with ABP:
<img width="892" alt="3" src="https://user-images.githubusercontent.com/57399417/70507531-87136c80-1b67-11ea-9859-ab9cb60ced50.png">
<img width="740" alt="2" src="https://user-images.githubusercontent.com/57399417/70507545-8bd82080-1b67-11ea-8281-a7b18c13c13a.png">

who can tell me how to do .

**Comment by maliming** [comment]
Please remove IdentityService from client scope.

**Comment by abllyboy** [comment]
> Please remove IdentityService from client scope.

got it,thank you very much
