### ISSUE TITLE
DistributedCache causes problem when multiTenant is enabled 

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#2361]
For now the only way to avoid a xxxCacheItem is MultiTenancy enable is to add IgnoreMultiTenancyAttribute on the class. But it's impossible to customize the current existing xxxCacheItem. And I also think NOT all of the existing xxxCacheItem should be multi-tancy

And all of extsing xxxCacheItemInvalidator can not avoid data inconsistence in multi tanant situation

For example.
- FeatureManagement module
The current `FeatureValueCacheItem` should be multi tenant ignored because `FeatureValue` has not implement `IMultiTenant`

- PermissionManagement module
Permisison cache is much more complicate. `PermissionGrantCacheItem` is multi tenant enabled because `PermissionGrant` has implemented `IMultiTenant`. But a permisison value provider like `ClientPermissionValueProvider`  should disable multi tenant data fitler during query from PermissionStore because I do not think tenant could create his own client in the current design.  Or the host side should enable client permisison for each tenant ( or seed/migrate tenant permisison durint tenant creation or permission definition update )

**Comment by maliming** [comment]
The problem of `FeatureValueCacheItem` and `SettingCacheItem` has been fixed.

https://github.com/abpframework/abp/commit/c4932e67a2ef3c30bf8c0f2940e8e95ec9b38359
https://github.com/abpframework/abp/pull/2523

**Comment by hikalkan** [comment]
I am closing this since it seems they already fixed. If not, please reopen.
