### ISSUE TITLE
Could not find corresponding document or sample codes

### ISSUE THREAD

**Issue by baoshenyi** [abpframework/abp#2367]
Hello, I like the abp framework and will use it for my future project after reviewing it. 
I follow up the the instructions on https://docs.abp.io/en/abp/0.18.1/Tutorials/AspNetCore-Mvc/Part-II but I would like to customize data table. 
1. Replace "Actions" drop down with bootstrap button 
2. make data table responsive, I added responsive-sm="true" still not working 
3. Replace date input fields with datapicker. 
I could not find any related documents about changes. Any shared urls or sample code? 
Thanks lots! Shenyi

**Comment by hikalkan** [comment]
Hi @baoshenyi,

1 & 2: We are using Datatables. You can refer to its own documentation for customizations. You don't have to use ABP's action, which is actually a simple addition to the Datatables. If you don't like it, you can implement it yourself.
3: You can use any javascript library you like. We are generally using [bootstrap-datepicker](https://github.com/uxsolutions/bootstrap-datepicker) which works with ABP templates out of the box. You can see its documentation.

**Comment by baoshenyi** [comment]
Thank you, hikalkan. I will use original Datatables to replace apb library, which answers that abp js library has no document and is just for demo purpose, not for production.

**Comment by hikalkan** [comment]
>abp js library has no document and is just for demo purpose, not for production
Actually it is for production, but not documented. But don't think it as a Datatables wrapper. It just simplifies some common use cases. If your user case is not that, just use Datatables API directly.

**Comment by baoshenyi** [comment]
thank you for the clarification.
