### ISSUE TITLE
I can't get the FirstOrDefault method in IRepository

### ISSUE THREAD

**Issue by dwp008** [abpframework/abp#2372]
Hello 
    Here is my sample in application layer. there is no _characterRepository.FirstOrDefault method. It has the Insert,Delete,GetList and other functions but no  FirstOrDefault.
    Is there any mistake where I made. or how could I get single result from query by filter . Thanks

 public class BestNameAppService: ApplicationService
    {
        private readonly IRepository<Character> _characterRepository;
        public BestNameAppService(IRepository<Character> characterRepository)
        {
            _characterRepository = characterRepository;
         }
         public NameScoreDto ScoreName(NameDTO name)
        {
             var ch =_characterRepository.
        }
    }

**Comment by yekalkan** [comment]
Try injecting **IRepository<TEntity, TKey>**

see https://docs.abp.io/en/abp/latest/Repositories#generic-repositories

**Comment by dwp008** [comment]
Hello yekalkan thanks for your help. I tryed the IRepository<TEntity, TKey>  as the document write. I can get the find method which can query item by id but still not have FirstOrDefault method.

**Comment by yekalkan** [comment]
You need **AsQueryable()**.

_characterRepository.**AsQueryable()**.FirstOrDefault(...)

**Comment by maliming** [comment]
You may need to add the namespace for linq `FirstOrDefault`.
```
using System.Linq;
```

**Comment by dwp008** [comment]
Thanks very much. yes I lost the using of System.Linq. very thanks.
