### ISSUE TITLE
admin user and Administration are missed after update database

### ISSUE THREAD

**Issue by baoshenyi** [abpframework/abp#2376]
I could update database but I could not use "admin" and "1q2w3E*" to login.
I searched "admin" in code and could not find any script to insert this default user. Also I could not see "Administration" menu either, any ideas? thank you for the help again!

**Comment by maliming** [comment]
How do you update the database? 
Using EF Core `Update-Database` Command or using the `DbMigrator` Application?

**Comment by baoshenyi** [comment]
Thank you for the quick reply. yes, select DbMigrator as project and run Update-Database in PM. I also search "admin" and could not find in the solution. thanks again.

**Comment by maliming** [comment]
You need to run the DbMigrator application.

![image](https://user-images.githubusercontent.com/6908465/70684371-f365ab80-1ce0-11ea-973f-c9807bbb8c61.png)

**Comment by baoshenyi** [comment]
thank you for you help again. 
According to document, I thought I could use "Using the DbMigrator Application" or "Using EF Core Update-Database Command", which quite misleading to the developer. Also I wonder is there any tech reasons to not insert seeds by ef update database?thanks again, Shenyi

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1123
