### ISSUE TITLE
Shared IdentityServer makes CurrentUser incorrect.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2379]
I have two abp projects (projectA and projectB), I wanna share the IdentityServer of projectA to projectB. So I remove IdentityServer in projectB and set projectB's `AuthServer.Authority` to projectA's IdentityServer.

But when I use `CurrentUser` in projectB, it becomes one of projectA's user.
![image](https://user-images.githubusercontent.com/30018771/70685930-c8ca2180-1ce5-11ea-9442-8bb1524f85be.png)
![image](https://user-images.githubusercontent.com/30018771/70688223-35481f00-1cec-11ea-8675-e3274e498b9c.png)

**Comment by Loongle** [comment]
First, check your database connectionString. and then you post your `appsettings.json` screenshot

**Comment by gdlcf88** [comment]
> First, check your database connectionString. and then you post your `appsettings.json` screenshot

All entities are correctly under projectB (including User), problem is `ICurrentUser` specially get projectA's admin user information.

**Comment by gdlcf88** [comment]
If diffirent Apps need to share ids4, does User entity must in the ids4 server? I think I understand now, it means I should use `Microservice` to share User entity.
