### ISSUE TITLE
Question : too much nugets/assemblies/etc...

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2388]
Hi,

I've just discovered abp and really like it, but I also have the feeling that there are too much nugets.
It seems overkill and difficult to manage too (Not for abp itself, but in real production env with a lot of projects and libs).

So, it is a question... I'm really wish to understand and know your point of view.

In theory, you force to have good separation (maybe soft-coupling ?) and it provides flexibility about what you really need (depends) or not. It avoid to be coupled with some external assemblies you don't need.

In practice, when you have a lot of projects and a lot of libraries (nugets), it is very difficult
to maintain. It is something I'm currently experiencing in my own company too !
We have a lot of libraries, each linked to other, then linked to others, then used by different softwares... we have a graph of dependencies. The difficulty is when a nuget version increase, not another, etc etc... it become quickly complex to maintain if the version management is not alignement correctly ! (It is the same overkill problem that we have with JS packages, you can drive crazy when trying to upgrade one version... sometimes you have blocking situations !)

My point of view is that, we should try to keep a good balance, I mean :
- Having a framework in one assembly (core)
- Having a nuget when it depends of an external provider (mongo, identify, ...)
- Having a nuget per independent module

Please, let me know, where does this 'guideline' come from ?

Thanks

**Comment by maliming** [comment]
Abp related package versions are always the same, even if some packages have not changed, it will release new versions.

So you should make the abp package used in your project always the same version.

**Comment by hikalkan** [comment]
I suppose @maliming's answer solves the problem. If you have additional question, please reopen this.

In addition, [ABP CLI](https://docs.abp.io/en/abp/latest/CLI) has an update command that upgrades all ABP related NuGet and NPM packages in one command. We try to solve hard part in our side and keep the application simple :)
