### ISSUE TITLE
Make email required for identity user

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2389]
see the comment: https://github.com/abpframework/abp/commit/74c034e864d2d85bb418dfdcb0a40d545c98a5bf#commitcomment-36020945

**Comment by hikalkan** [comment]
While this is a breaking change, it should be done. Because it is required in MS Identity, but was not required by the domain object, IdentityUser.

**Comment by gdlcf88** [comment]
Hello @hikalkan, I found that this configuration doesn't work, I can set the same email to different users. 
https://github.com/abpframework/abp/blob/decad8e30f6186be87db8c5743bf55d530514bb9/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpIdentityDomainModule.cs#L28

**Comment by maliming** [comment]
@gdlcf88 
> I can set the same email to different users.

Please share your code.

**Comment by gdlcf88** [comment]
> @gdlcf88
> 
> > I can set the same email to different users.
> 
> Please share your code.

It cannot be reproduced now.

**Comment by Goxiaoy** [comment]
I have to write some ugly code to fit my case now. Because the user can login or register by phone verification code insead of email in my case.

**Comment by xyfy** [comment]
> I have to write some ugly code to fit my case now. Because the user can login or register by phone verification code insead of email in my case.

May you share the code? I wan't to do this like you~~

**Comment by Goxiaoy** [comment]
> > I have to write some ugly code to fit my case now. Because the user can login or register by phone verification code insead of email in my case.
> 
> May you share the code? I want to do this like you~~

@xyfy Try these following steps:

1. override your dbcontext `OnModelCreating` to make sure the email is not required in db level
```
modelBuilder.Entity<IdentityUser>(entity =>
{
        entity.Property(p => p.Email).IsRequired(false);
        entity.Property(p => p.NormalizedEmail).IsRequired(false);
});
```

2. replace the default `IdentityUserStore`. (Usually in your Domain module)

```
    [Dependency(ReplaceServices = true)]
    public class MyIdentityUserStore: IdentityUserStore
    {
        public MyIdentityUserStore(IIdentityUserRepository userRepository, IIdentityRoleRepository roleRepository, IGuidGenerator guidGenerator, ILogger<IdentityRoleStore> logger, IdentityErrorDescriber describer = null) : base(userRepository, roleRepository, guidGenerator, logger, describer)
        {
        }

        /// <summary>
        /// Sets the <paramref name="email" /> address for a <paramref name="user" />.
        /// </summary>
        /// <param name="user">The user whose email should be set.</param>
        /// <param name="email">The email to set.</param>
        /// <param name="cancellationToken">The <see cref="T:System.Threading.CancellationToken" /> used to propagate notifications that the operation should be canceled.</param>
        /// <returns>The task object representing the asynchronous operation.</returns>
        public override Task SetEmailAsync(IdentityUser user, string email, CancellationToken cancellationToken = new CancellationToken())
        {
            cancellationToken.ThrowIfCancellationRequested();

            Check.NotNull(user, nameof(user));
            var t = typeof(IdentityUser);
            t.GetProperty(nameof(IdentityUser.Email))
                .SetValue(user, email, null);

            return Task.CompletedTask;
        }
    }
```

```
public override void ConfigureServices(ServiceConfigurationContext context)
{
        ...
       context.Services.Replace(ServiceDescriptor.Scoped<IdentityUserStore, MyIdentityUserStore>());
}
```
