### ISSUE TITLE
Multiple version issues Of ClientAPI

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#2401]
How to use the old version of HttpApi.Client in new versions of ApplicationService?
Some ApplicationService were developed using older versions of ABP.

**Comment by hikalkan** [comment]
>older versions of ABP

[AspNet Boilerplate](https://aspnetboilerplate.com/)?

Please write more details and be specific.

**Comment by xewn** [comment]
不是 AspNet Boilerplate，是abp vnext。
比如我用0.21版本的abp vnext开发了3个服务，A,B,C。A服务中使用了B服务的clientAPI，
现在abp vnext发布了1.1.2版本，我要把A服务升级到abp vnext1.1.2版本，但是A服务依赖了B服务，就必须把B服务也升级到abp vnext1.1.2版本，A服务才能够升级成功。
实际情况是，B服务不需要升级到最新的abp vnext版本。只想升级A服务到abp vnext1.1.2版本。

**Comment by xewn** [comment]
不好意思，英文表达不来，只好用中文表达了。

**Comment by maliming** [comment]
> 但是A服务依赖了B服务，就必须把B服务也升级到abp vnext1.1.2版本，A服务才能够升级成功。

Do not understand what you mean.

**Comment by zhchlmm** [comment]
你如果是微服务方式部署的话，服务间通过api调用或者消息队列解耦，各个服务是独立部署的，升级版本互不影响啊

**Comment by xewn** [comment]
@zhchlmm   abp vnext是通过引用client api工程的dll的方式，以远程服务的方式来调用另外一个服务的。也就是A服务依赖了B服务，A服务要升级abp vnext的办法时，就必须先把B服务的abp vnext的版本升级。
