### ISSUE TITLE
Template - Identity / MongoDB - Identity tables are not called

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2402]
Hi,

I have a sample (created online) and when I run it there is no collection in my MongoDB database.
I have the cache database only.

No collection/DB for the identity.
No collection/DB for the application.

The 'IdentityServerDataSeedContributor' is never called !

Any idea ?

PS: I have no exception and see nothing in the logs !

**Comment by maliming** [comment]
Using the DbMigrator Application

The solution contains a console application (named XXX.DbMigrator in this sample) that can create database, apply migrations and seed initial data. It is useful on development as well as on production environment.

.DbMigrator project has its own appsettings.json. So, if you have changed the connection string above, you should also change this one.

**Comment by vd3d** [comment]
Ok thanks. But does this one should'nt be started when the project start ? Or it is normal to do this manually ? Thanks

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1123
