### ISSUE TITLE
How to customize UrlActionNameNormalizer ？

### ISSUE THREAD

**Issue by yexianzhu** [abpframework/abp#2403]
it is，i do like the default UrlActionNameNormalizer ,but there is nowhere tell me how to customize it.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/blob/decad8e30f6186be87db8c5743bf55d530514bb9/framework/test/Volo.Abp.AspNetCore.Mvc.Tests/Volo/Abp/AspNetCore/Mvc/AbpAspNetCoreMvcTestModule.cs#L52

**Comment by yexianzhu** [comment]
it looks like only one is defined，can you be more specific?

**Comment by maliming** [comment]
I don't understand what you mean, can you elaborate it?

**Comment by yexianzhu** [comment]
比如GetBookList被转成了books，但是我想要的是getBookList

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1840#issuecomment-538707374
