### ISSUE TITLE
Template - several issues

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2406]
Hi,

I have generate a new sample from the online page. I use a tiered one and MongoDB. (I also use MongoDB as cache, and not Redis, but not sure it is related)

I have several issues:

1 - In the templates/samples, I should also have a gateway, right ?
At least in production, I'm not sure if have so much opened 'port' are an issue !
In general, web site only targets the port 80/443, other port are not allowed externally (server & client side).

2 - When I'm logged, if I click on the 'Profile' it open a new browser tab, instead of opening a dialog or even keeping on the same page.

3 - I try to register a new user, and after I got an issue on this page ( https://localhost:44328/signin-oidc ) :

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Text.Json.JsonElement.GetProperty(String propertyName) at Volo.Abp.AspNetCore.Authentication.OAuth.Claims.MultipleClaimAction.Run(JsonElement userData, ClaimsIdentity identity, String issuer) at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetUserInformationAsync(OpenIdConnectMessage message, JwtSecurityToken jwt, ClaimsPrincipal principal, AuthenticationProperties properties) at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

System.Exception: An error was encountered while handling the remote login. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Text.Json.JsonElement.GetProperty(String propertyName) at Volo.Abp.AspNetCore.Authentication.OAuth.Claims.MultipleClaimAction.Run(JsonElement userData, ClaimsIdentity identity, String issuer) at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetUserInformationAsync(OpenIdConnectMessage message, JwtSecurityToken jwt, ClaimsPrincipal principal, AuthenticationProperties properties) at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync() --- End of inner exception stack trace --- at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync() at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Thanks

**Comment by hikalkan** [comment]
Hi,

1. Startup template has not a gateway. It is not a microservice solution. It is a solution where the UI, IdentityServer and the API host are separated.
2. This is by design. Since you selected "tiered", account management (including profile management) is inside the IDS side while your main application is another application. So, it is redirecting user to the IDS to change the password on that site. Think like that: When you use Facebook auth, user will change his password on the facebook side, not your side.
3. Should check this one.

**Comment by hikalkan** [comment]
@maliming can you try if you can get the same exception for the 3rd issue.

**Comment by maliming** [comment]
> 3 - I try to register a new user, and after I got an issue on this page ( https://localhost:44328/signin-oidc )

hi @vd3d 
Looks like you are using openid connect,  Please share the code that can reproduce the problem. Thank you.

**Comment by maliming** [comment]
hi @vd3d Did you solve your problem?
