### ISSUE TITLE
Few Volo.Abp projects could not be loaded in VS 2019 16.4.1

### ISSUE THREAD

**Issue by baoshenyi** [abpframework/abp#2413]
I have follow vs version and .net core on my local.
Microsoft Visual Studio Enterprise 2019 Version 16.4.1
C:\dotnet --version 3.1.100

When Volo.abp solution is loaded, quite few projects could not be loaded. Could you please help me with it? thanks

![image](https://user-images.githubusercontent.com/9803653/71016920-13b3b280-20b3-11ea-852a-0b7110b13207.png)

**Comment by maliming** [comment]
Can you see why VS can't load the solution? VS will prompt you.
