### ISSUE TITLE
A problem with dynamic api when integrating with Ocelot

### ISSUE THREAD

**Issue by colinin** [abpframework/abp#2415]
**Ocelot** has the concept of **ReRoutes**, but the upstream routing address cannot be duplicated. By default, the **HttpCliantProxy** class of the abp framework is spliced by **BaseUrl** in **RemoteServices** plus **/api/abp/api-definition**. In this case, if multiple microservices are unified At the entrance, you cannot call other services through the gateway. It is recommended to add a **DynamicServicePrefix** to the **RemoteServiceConfiguration** configuration item as the prefix of the dynamic proxy interface to distinguish different service proxies. What do you think?

**Comment by hikalkan** [comment]
Let us work on that after 2.0 release.

**Comment by hikalkan** [comment]
From a client perspective, `/api/abp/api-definition` should be retrieved from the gateway, not from an individual microservice. So, when you call `/api/abp/api-definition`, it should be execuited in the gateway and gateway merges all the API definitions.

Are you getting an exception about that or you need to another use case?

**Comment by volethanh** [comment]
@hikalkan : How can I reroute all APIs because with the sample, I only see `ctx => ctx.Request.Path.ToString().StartsWith("/api/abp/") || ctx.Request.Path.ToString().StartsWith("/Abp/"),` so it only reroutes APIs with that prefix. I cannot use these below apis in the picture below through API Gateway

![image](https://user-images.githubusercontent.com/46510130/76396997-df4b4c00-63ac-11ea-9b9e-da6d0d11a43f.png)

**Comment by hikalkan** [comment]
If you're writing about this:

https://github.com/abpframework/abp/blob/ace4b5526eb00d0ed6429834693fc618dc6c54b2/samples/MicroserviceDemo/gateways/BackendAdminAppGateway.Host/BackendAdminAppGatewayHostModule.cs#L138-L146

>so it only reroutes APIs with that prefix

No. Vice verse. It doesn't re-route URLs starting with this prefix, but re-routes everything else.

**Comment by colinin** [comment]
Enough time point recently, I saw the Ocelot about route merging source code and documentation, to implement a AbpApiDefinitionAggregator, used internally JObject Merge method is ok, it is very convenient, Ocelot extensibility is really good
![AbpApiDefinition](https://user-images.githubusercontent.com/35512826/82451133-286ff880-9ae0-11ea-8770-4813e8f877d6.png)
