### ISSUE TITLE
how to enable multi tenancy in microservice?

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2416]
when I run the project which is generate by ABP CLI,by default the multi tenancy is enabled and works fine.Like the screenshot below:
 
<img width="544" alt="pp1" src="https://user-images.githubusercontent.com/57399417/71074908-1d760c80-21be-11ea-9023-c2a14ad9ceb7.png">

But when I want to enable it in microservice's "AuthServer.Host" project like the screenshot below,it works bad.And when I debug the "Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic" project,the HttpContextTenantResolveResultAccessor'Result is null.

Are the anything I need to set more?
 
<img width="1226" alt="pp2" src="https://user-images.githubusercontent.com/57399417/71074978-3f6f8f00-21be-11ea-9685-45d5a3fd7efe.png">

 
<img width="954" alt="pp3" src="https://user-images.githubusercontent.com/57399417/71074999-4bf3e780-21be-11ea-8d50-3b9f7c59f0e3.png">

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/956
