### ISSUE TITLE
Is it possibile to control the order of the data seeding?

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#2417]
I have some seed classes (all of them implement `IDataSeedContributor`),
There are dependencies between data, so I want to know if there is a way to control the order of the seed classes execution.

Or I have to merge them into one class and write seed code from top to bottom.

**Comment by maliming** [comment]
The order doesn't seem to make much sense.
Modules may need to seed some data, which should have nothing to do with the seed data of other modules.

You can call separate methods in your IDataSeedContributor to execute the seeds if you want to separate them.

**Comment by gdlcf88** [comment]
This is what I do:
1. Create more than one seeder, such as `CategoryDataSeeder`, `ProductDataSeeder`.
2. Create single seed contributor to execute all the seeders:
![image](https://user-images.githubusercontent.com/30018771/71076313-79da2b80-21c0-11ea-832e-0811216001ad.png)

**Comment by gdlcf88** [comment]
Inspiration from:

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionDataSeedContributor.cs#L10

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionDataSeeder.cs#L9

**Comment by saraBadawy77** [comment]
Hello, I would like some help??

**Comment by cristiandmonda** [comment]
@saraBadawy77 What do you need help with?

**Comment by saraBadawy77** [comment]
I have a table in the database. I added it. I want to add some basic data to it( Dataseeding). I want a simple example that applies this. I read the documentation for ABP, but I did not understand this well. Can you help me?

**Comment by cristiandmonda** [comment]
@saraBadawy77 Seeding data involves implementing the `IDataSeedContributor` interface in your domain layer, which is then discovered and ran by the framework when you use the DbMigrator. You'd inject your repository in said class, and use it in the SeedAsync method to insert into the database. For a running example you have the [EventHub project](https://github.com/abpframework/eventhub), which has some [data seeding](https://github.com/abpframework/eventhub/blob/main/src/EventHub.Domain/Data/EventHubDataSeedContributor.cs). It would be helpful if you could post some code that's not doing what you expect it to, or a more detailed use case you'd like to implement, otherwise it's too generic :)

**Comment by saraBadawy77** [comment]
I really thank you for your interest in responding and for your time. This was very useful to me. Thank you very much

**Comment by puschie286** [comment]
we use an attribute (similar to LoaclEventHandlerOrder) to simplify related seeds and keep the it decoupled
Order Attribute
```c#
[AttributeUsage( AttributeTargets.Class, AllowMultiple = false, Inherited = true )]
public class DataSeedOrderAttribute( int order ) : Attribute
{
	/**
	 * Seed contributors execute in ascending value of Order property
	 */
	public int Order { get; set; } = order;
}
```
Ordered Seed service ([original](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Data/Volo/Abp/Data/DataSeeder.cs))
```c#
[Dependency( ReplaceServices = true )]
[ExposeServices( typeof( IDataSeeder ) )]
public class OrderedDataSeeder(
	IOptions<AbpDataSeedOptions> options,
	IServiceScopeFactory serviceScopeFactory )
	: IDataSeeder, ITransientDependency
{
	private IServiceScopeFactory ServiceScopeFactory { get; } = serviceScopeFactory;
	private AbpDataSeedOptions   Options             { get; } = options.Value;

	[UnitOfWork]
	public virtual async Task SeedAsync( DataSeedContext context )
	{
		using IServiceScope scope = ServiceScopeFactory.CreateScope();

		// order seeder by attribute
		List<Type> contributors = GetOrderedContributors();

		if( context.Properties.ContainsKey( DataSeederExtensions.SeedInSeparateUow ) )
		{
			IUnitOfWorkManager manager = scope.ServiceProvider.GetRequiredService<IUnitOfWorkManager>();
			foreach( Type contributorType in contributors )
			{
				AbpUnitOfWorkOptions options = context.Properties.TryGetValue(
					DataSeederExtensions.SeedInSeparateUowOptions,
					out object? uowOptions )
					? (AbpUnitOfWorkOptions)uowOptions!
					: new AbpUnitOfWorkOptions();

				bool requiresNew =
					context.Properties.TryGetValue( DataSeederExtensions.SeedInSeparateUowRequiresNew, out object? obj )
					&& (bool)obj!;

				using IUnitOfWork uow = manager.Begin( options, requiresNew );
				IDataSeedContributor contributor = scope.ServiceProvider
					.GetRequiredService<IDataSeedContributor>( contributorType );

				await contributor.SeedAsync( context );
				await uow.CompleteAsync();
			}
		}
		else
		{
			foreach( Type contributorType in contributors )
			{
				IDataSeedContributor contributor = scope.ServiceProvider
					.GetRequiredService<IDataSeedContributor>( contributorType );

				await contributor.SeedAsync( context );
			}
		}
	}

	private List<Type> GetOrderedContributors()
	{
		return Options.Contributors
			.Select( type => ( type, GetOrderOfType( type ) ) )
			.OrderBy( x => x.Item2 )
			.Select( x => x.type )
			.ToList();
	}

	private static int GetOrderOfType( Type type )
	{
		return ReflectionHelper
				.GetAttributesOfMemberOrDeclaringType<DataSeedOrderAttribute>( type )
				.FirstOrDefault()?.Order
			?? 0;
	}
}
```

**Comment by jsgoupil** [comment]
Since this was requested and closed, it would have been simpler to add an optional order on the interface, but since it's not present, let me add some piece of code to order your seed contributors:

Put this in your `YourDbMigratorModule`
```
public override void ConfigureServices(ServiceConfigurationContext context)
{
    Configure<AbpDataSeedOptions>(options =>
    {
        // This is automatic, but we do it here because the order matters.
        var requestedOrder = new Type[] { typeof(ParkDataSeedContributor), typeof(ProductDataSeedContributor) };

        var orderedContributors = options.Contributors
            .OrderBy(contributor =>
            {
                var index = Array.IndexOf(requestedOrder, contributor);
                return index == -1 ? int.MaxValue : index;
            })
            .ToList();

        options.Contributors.Clear();
        foreach (var contributor in orderedContributors)
        {
            options.Contributors.Add(contributor);
        }
    });
}
```
