### ISSUE TITLE
How to extend Application Modules to add register tenant api to MultiTenancyModule

### ISSUE THREAD

**Issue by AhmadAlMunajjed** [abpframework/abp#2418]
I'm starting a new project with abp. Meanwhile, I work on a project with asp.net zero and I want to implement the same functionality of register tenant that creates a new tenant and admin user for it.

Thanks a lot.

**Comment by maliming** [comment]
You can enhance your application with the tenant management module. https://github.com/abpframework/abp/tree/dev/modules/tenant-management


However, it may have some differences from zero. You can check its code first. We will enhance these modules and documentation later.

**Comment by AhmadAlMunajjed** [comment]
Thanks, found it.
