### ISSUE TITLE
cshtml file Intellisense not work

### ISSUE THREAD

**Issue by mentianyi** [abpframework/abp#2420]
tagHelper cant work with cshtml.
Context,Component,inject.......

Projects upgrade to .net core 3.0.0,must add     `<AddRazorSupportForMvc>true</AddRazorSupportForMvc>`
in csprojet/propertyGroup section.

**Comment by maliming** [comment]
> tagHelper cant work with cshtml. Context,Component,inject.......

How to reproduce the problem?

**Comment by mentianyi** [comment]
[https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#startup-changes](url)

**Comment by mentianyi** [comment]
```
<PropertyGroup>
  <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
</PropertyGroup>
```

**Comment by mentianyi** [comment]
![image](https://user-images.githubusercontent.com/11286219/71143453-94121900-2255-11ea-8421-a949958d9014.png)

**Comment by maliming** [comment]
I will research and solve this problem, thanks for feedback.

**Comment by mentianyi** [comment]
> I will research and solve this problem, thanks for feedback.

You can test my way.
