### ISSUE TITLE
How can I extend the entities defined in modules?

### ISSUE THREAD

**Issue by luy710** [abpframework/abp#2421]
How can I extend the entities defined in modules? Can only add association tables? For example, if I want to add fields to tenant entities and do some adding, deleting, modifying and querying, what are the good suggestions or cases?
Thanks a lot.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/469#issuecomment-425720097

**Comment by luy710** [comment]
ok Thank you ! @maliming
