### ISSUE TITLE
Feature checker can not invalidate the cached value

### ISSUE THREAD

**Issue by rneto** [abpframework/abp#2429]
I have created my own FeatureDefinitionProvider base at https://aspnetboilerplate.com/Pages/Documents/Feature-Management.

Initially, the management of features at the tenant level works correctly with my host admin user, however, when I use the _IFeatureChecker.IsEnabledAsync_ method to check the feature for the tenant user it always have the start value when the application startup, although the value in the database (_AbpFeatureValues_ table) has been changed.

The _IFeatureChecker.IsEnabledAsync_ value only changes if I restart my IIS Express.

How to reproduce issue?

1. Startup the app.
1. Login with the tenant admin user: then "Feature1" is "false".
1. Log out.
1. Login with the host admin user: then change "Feature1" to "true".
1. Log out.
1. Login with the tenant admin user again: then "Feature1" is still "false".

My _FeatureDefinitionProvider_ class:

```csharp
using Volo.Abp.Features;
using Volo.Abp.Validation.StringValues;

namespace MyApp.Features
{
    public class AdminAppFeatureDefinitionProvider : FeatureDefinitionProvider
    {
        public override void Define(IFeatureDefinitionContext context)
        {
            var group = context.AddGroup(MyAppFeatures.Group1.GroupName);

            group.AddFeature(
                MyAppFeatures.Group1.Feature1,
                valueType: new ToggleStringValueType()
            );
        }
    }
}
```

**Comment by maliming** [comment]
First, [Feature-Management](https://aspnetboilerplate.com/Pages/Documents/Feature-Management) documentation works for [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate).

Are you using the FeatureManagement module?

**Comment by rneto** [comment]
I know that this documentation is for aspnetboilerplate (abp documentation is incomplete and I have subscribe to #2188).

I implement my solution based in this other issue: #2163

I created my app with your app template that includes the _FeatureManagement_ module:

```
abp new MyApp
```

**Comment by maliming** [comment]
The project created by cli includes the feature-management module by default.


> How to reproduce issue?
Startup the app.
Login with the tenant admin user: then "Feature1" is "false".
.....

I didn't understand the steps you provided, can you explain and share some code in detail?

**Comment by rneto** [comment]
I have created an example repository in my profile (https://github.com/rneto/AbpRoverInMars).

In the **develop** branch you can see two commits made a few minutes ago:
- [_feat: add featuredefinitionprovider_](https://github.com/rneto/AbpRoverInMars/commit/27d8c6c923fc2795d06cd21c41e6e0dd54f87fe6), where I create my FeatureDefinitionProvider.
- [_feat: create featurecheker_](https://github.com/rneto/AbpRoverInMars/commit/83995bb995064ac562deef57ece3bd64d5d8973c) test, where I add a visualization space to my feature.

How to reproduce issue?

1. Clone [my code](https://github.com/rneto/AbpRoverInMars/tree/develop).
1. Follow the [Getting Started With the ASP.NET Core MVC Template](https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-MVC-Template) from the step _Create Database & Apply Database Migrations_.
1. Login with the host admin user.
1. Create "tenant1".
1. Go to "tenant1" features and set "Camera.Enable" feature to "true".
1. Log out.
1. Login with the "tenant1" admin user.
1. You will see _Camera.Enable: True_ in _Index.cshtml_ redering.
1. Log out.
1. Login with the host admin user
1. Go to "tenant1" feartures and set **"Camera.Enable"** feature to **"false"**.
1. Log out.
1. Login with the "tenant1" admin user
1. **You will still see _Camera.Enable: True_ in _Index.cshtml_ redering.**

**Comment by maliming** [comment]
`FeatureValue `and `Setting `have no tenant information and cannot switch tenants like `PermissionGrant`.

May cause problems that fail to invalidate the cache.

@hikalkan What do you think?

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/SettingCacheItemInvalidator.cs#L25-L27

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/feature-management/src/Volo.Abp.FeatureManagement.Domain/Volo/Abp/FeatureManagement/FeatureValueCacheItemInvalidator.cs#L27-L30


https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionGrantCacheItemInvalidator.cs#L30-L34

**Comment by rneto** [comment]
Hi @maliming,

I have added the _IgnoreMultiTenancy_ attibute to my class in a [new commit](https://github.com/rneto/AbpRoverInMars/commit/6193a02d4efb0c3df143a7bd5cd437e9e2c9b49c), but it still behaves in the same way. What I am doing wrong?

Thanks,

**Comment by maliming** [comment]
`IgnoreMultiTenancy `should work for `TCacheItem`.

**Comment by hikalkan** [comment]
I am working on it. First, I will try to repeat with unit test.

**Comment by maliming** [comment]
@hikalkan We should also make the same changes(c4932e6) to the settings module.

**Comment by hikalkan** [comment]
Yes, we should. But first write a unit test as I've written to repeat the problem. Thanks.

**Comment by hikalkan** [comment]
I see that you've already done. Thanks ;)
