### ISSUE TITLE
Example of the REST API Versioning

### ISSUE THREAD

**Issue by xirius** [abpframework/abp#2432]
Hi, is there any example somewhere of how to create several version of the REST API with auto controllers ?

For example, what is the right approach to create several API versions (v1, v2) of BookStore example ?
https://github.com/abpframework/abp/tree/master/samples/BookStore

I saw a closed issue about [API versioning](https://github.com/abpframework/abp/issues/103)  but I cannot find any example of the usage.

Any directions ?

**Comment by maliming** [comment]
hi

You can refer to the `Volo.Abp.AspNetCore.Mvc.Versioning.Tests` project.

https://github.com/abpframework/abp/tree/dev/framework/test/Volo.Abp.AspNetCore.Mvc.Versioning.Tests
