### ISSUE TITLE
Blazor & ABP : crash

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2434]
Hi,

I have create a new 'blazor' project and try to add ABP.

In my Startup.cs I have the following code:

`endpoints.MapFallbackToPage("/_Host");`

It work fine, until I have my ABP module:

`services.AddApplication<MyAppWebModule>();`

I got the following error: "Value cannot be null. (Parameter 'provider')" 

>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceCollectionCommonExtensions.GetRequiredService[T](IServiceCollection services)
>    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.get_Value()
>    at Volo.Abp.AspNetCore.Mvc.AbpDataAnnotationAutoLocalizationMetadataDetailsProvider.CreateDisplayMetadata(DisplayMetadataProviderContext context)

What is strange is that the class MyAppWebModule is almost empty !

public class ProductFlyWebModule : AbpModule .....

Is there something in conflict in the AbpModule, Any idea ?

PS: I can provides you the sample and/or a remote session to show you if needed !

**Comment by acjh** [comment]
Call `app.InitializeApplication()` in the `Configure` method of your `Startup` class.

Docs: https://github.com/abpframework/abp/blob/1.1.2/docs/en/Getting-Started-AspNetCore-Application.md#the-startup-class

**Comment by vd3d** [comment]
Ok. Thanks. InitializeApplication has to be called before MapFallbackToPage !
