### ISSUE TITLE
template lack  using Volo.Abp.EntityFrameworkCore.Modeling  

### ISSUE THREAD

**Issue by zengxinle** [abpframework/abp#2435]
new Solution Mvc template,  in Project XXX.EntityFrameworkCore 's  
HPComDbContextModelCreatingExtensions.cs

lack  "using Volo.Abp.EntityFrameworkCore.Modeling;"  

hope to add in template.

**Comment by zengxinle** [comment]
b.ConfigureByConvention();    ---- product  a ref Error.

**Comment by acjh** [comment]
There is no `b.ConfigureByConvention();` in [*DbContextModelCreatingExtensions.cs (v1.1.2)](https://github.com/abpframework/abp/blob/1.1.2/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContextModelCreatingExtensions.cs).

Did you add that yourself?

**Comment by maliming** [comment]
Like @acjh said, if you use `ConfigureByConvention `or other methods, you need to reference their namespaces. The default templates are fine.
