### ISSUE TITLE
Error in sample (and solution) : 44328 port is wrong

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2436]
In the sample, and more precisely in several appsettings, we can find this:

  "RootUrl": "https://localhost:44328"

or 

  "SelfUrl": "https://localhost:44328"

But theses ports are wrong !!

By example, we should use the existing 44367 port instead

**Comment by maliming** [comment]
Sorry, I didn't understand your question, can you elaborate on it?

cli or website generated application port is random, What is the wrong port?

**Comment by vd3d** [comment]
It is not a question ;-)

In fact, it is a bug.

I have create a sample with the online generator, and it use some ports that are wrong.
Theses ports are in the appsettings.json files ... they have to be changed to make it work correctly.
