### ISSUE TITLE
Optimize getting permissions

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2437]
Each permission grant info for a user is separately cached and queried. This is fine normally since yu expect to query against a few permissions in a request and they are cached then.
But, for endpoints like `/Abp/ApplicationConfigurationScript` it is required to query all permissions for a user or role which causes tens of database query. These queries are simple, fast and indexed. However, it would be a good optimization to query all permissions of a user in a single query.

The optimization have done:

- [x] When it don't find a permission (of a user/role/client) in the cache, query all granted permissions in a single query and set all cache items. So, for next permission checks, they are in the cache!
- [x] When setting permissions to the cache, use the new SetManyAsync method instead of setting one by one. Uses #4482

**Comment by maliming** [comment]
Related issue: https://github.com/abpframework/abp/issues/1678#issuecomment-532504149
