### ISSUE TITLE
In Module Template ,angular app cant get correct application-configuration after login

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#2438]
In [Moduel Template](https://github.com/abpframework/abp/tree/dev/templates/module),
We has a full Abp Module with [`HttpApi.Host`](https://github.com/abpframework/abp/tree/dev/templates/module/aspnet-core/host/MyCompanyName.MyProjectName.HttpApi.Host),[`IdentityServer`](https://github.com/abpframework/abp/tree/dev/templates/module/aspnet-core/host/MyCompanyName.MyProjectName.IdentityServer) host,
And an [`angular application`](angular), 
I run all(`HttpApi.Host` and 'IdentityServer' did `Update-Database` command) and try to use angular app,
It get access_token by login page successfully,
![image](https://user-images.githubusercontent.com/16490084/71317434-ff5d2480-24bb-11ea-8960-28c06185a7af.png)
 and then fetch `application-configuration` by this access_token,
![image](https://user-images.githubusercontent.com/16490084/71317373-ad67cf00-24ba-11ea-89f3-8f75edb095e1.png)
but server return  result without Authenticated.
![image](https://user-images.githubusercontent.com/16490084/71317380-d38d6f00-24ba-11ea-8cf9-757e5d719bb6.png)
Is some thing missing about clientid permission??

**Comment by maliming** [comment]
hi @yinchang0626 see https://github.com/abpframework/abp/pull/2449 for **currentUser** output.

The policies and grantedPolicies in auth are empty because no permissions are provided in your module.
https://github.com/abpframework/abp/blob/7110b49f6cd6ef4c6cc18fd327392e34fa0689f4/templates/module/aspnet-core/src/MyCompanyName.MyProjectName.Application.Contracts/Authorization/MyProjectNamePermissionDefinitionProvider.cs#L7-L12

**Comment by yinchang0626** [comment]
@maliming thanks for your help,
If policies and grantedPolicies are empty in module template,
why angular application have `@abp/ng.identity` `@abp/ng.tenant-management` `@abp/ng.setting-management`... modules ? #1652
Maybe remove them in default will be clearer and avoid confuse.
We can add these modules(include backend and frontend) by self 
after created the module template or use it in application template.
What do you think?

**Comment by maliming** [comment]
> why angular application have @abp/ng.identity @abp/ng.tenant-management @abp/ng.setting-management... modules ?

I don't know much about angular templates. :)
