### ISSUE TITLE
Logout : doesn't work correctly

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2442]
Hi,

In the Web sample, when I try to logout, it redirect to another page.

But, when I restart the application, I'm logged in automatically !!

It seems it is a call to: 

> https://localhost:44328/Account/Logout

I've checked the code in ChallengeAccountController, and I see this :
`await HttpContext.SignOutAsync();`

But it seems that the cookies are still there !

**Comment by maliming** [comment]
hi @vd3d

Please provide complete steps to reproduce the problem, thanks

**Comment by vd3d** [comment]
Ok,

Create a sample with the online generator. (Mine is mongodb + Tiered).
Start the web app.

1 - login with the admin
2 - logout
3 - restart the application and click on the 'login' link. I'm directly redirected to the web site, not the login page

**Comment by vd3d** [comment]
I continue to search, added something on stackoverflow :
https://stackoverflow.com/questions/59486045/net-core-identityserver-unable-to-logout

**Comment by maliming** [comment]
I think your problem is that your application has been logged out, but the identity server is not logged out, so when you click `login`, it automatically logs in.

see https://identityserver4.readthedocs.io/en/latest/topics/signout.html

**Comment by navneet1sharma** [comment]
Hello Guys, 

I am facing the below issue after clicking on the logout button.

![image](https://github.com/user-attachments/assets/0d3a9bc6-e0c3-4d57-bab6-56ac39254898)

Can someone suggest to fix it

**Comment by navneet1sharma** [comment]
After clicking on the logout button, this screen is stayed for 2 mins & then redirected to the login page.

Can someone help me to immediately redirect after clicking on the logout button?

![Screenshot 2024-07-23 161000](https://github.com/user-attachments/assets/f6191bd3-0ff4-404e-9683-87dbef0c3b15)
