### ISSUE TITLE
about csproj project file.

### ISSUE THREAD

**Issue by RyanOvO** [abpframework/abp#2443]
Since abp v1.0.0. csproj file like this:
![image](https://user-images.githubusercontent.com/31231960/71334976-55dd6800-257b-11ea-8709-afa545416bfd.png)
but vs couldn't find and build project, how solution it.

**Comment by maliming** [comment]
Couldn't understand your question, Please explain it in detail.

**Comment by ismcagdas** [comment]
@RyanOvO are you trying to build framework itself ?

**Comment by olicooper** [comment]
This will happen when building a module that depends on another module. You have to open the solutions for each module that you see listed to create the compiled files.
The main project under _framework_ folder should build without a problem as the modules depend on the main project (not the other way around).

**Comment by RyanOvO** [comment]
> @RyanOvO are you trying to build framework itself ?

yes, I build framework, and it's successful.
![image](https://user-images.githubusercontent.com/31231960/71361324-9ebe0c80-25cd-11ea-9890-424a0a13178b.png)
but,the module folder,like docs project, it's build error.
![image](https://user-images.githubusercontent.com/31231960/71361390-cf9e4180-25cd-11ea-80ef-42f36e606ef2.png)
so, I want to know how to solution it

**Comment by RyanOvO** [comment]
> This will happen when building a module that depends on another module. You have to open the solutions for each module that you see listed to create the compiled files.
> The main project under _framework_ folder should build without a problem as the modules depend on the main project (not the other way around).

i had try,but it's not work. why change <itemgroup>?

**Comment by maliming** [comment]
@RyanOvO 
Try to execute dotnet cli command in the module directory.

```
dotnet build
```
