### ISSUE TITLE
hope to improve the documentation

### ISSUE THREAD

**Issue by dazsco** [abpframework/abp#2446]
this is a great project, but some of the documentation is not complete. We can only use it through examples and reading the source code, which increases the development cycle. ABP VNext has been iterated to version 1.0. I hope the ABP team can supplement the remaining documents. This is very important. Thank you very much for your efforts.

**Comment by hikalkan** [comment]
Thank you for your feedback. The documentation is the high priority in our waiting list and will be improved.
