### ISSUE TITLE
Cli tool is not compatible with netcore 3.0

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#2448]
dotnet tool install -g Volo.Abp.Cli

command 

returns this

error NU1202: Package Volo.Abp.Cli 1.1.2 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any. Package Volo.Abp.Cli 1.1.2 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any
The tool package could not be restored.
Tool 'volo.abp.cli' failed to install.

**Comment by acjh** [comment]
Install .NET Core 3.1.
