### ISSUE TITLE
Aggregate root cannot be saved with new related entities.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2450]
Steps for reproduce:

1. Create `Score` aggregate root:
```
    public class Score : FullAuditedAggregateRoot<Guid>, IMultiTenant
    {
        public Guid? TenantId { get; set; }
        
        public virtual int InitialScoreValue { get; protected set; }
        
        public virtual List<ScoreDetail> ScoreDetails { get; set; }
        
        protected Score() {}

        public Score(
            Guid id,
            Guid? tenantId,
            int initialScoreValue)
        {
            Id = id;
            TenantId = tenantId;
            InitialScoreValue = initialScoreValue;
            
            ScoreDetails = new List<ScoreDetail>();
        }
    }
```

2. Create a related entity:
```
    public class ScoreDetail : FullAuditedEntity<Guid>, IMultiTenant
    {
        public Guid? TenantId { get; }
        
        public virtual Guid ScoreId { get; set; }
        
        public virtual Score Score { get; set; }

        public virtual string Name { get; protected set; }
        
        protected ScoreDetail() {}

        public ScoreDetail(
            Guid id,
            Guid? tenantId,
            Guid scoreId,
            string name)
        {
            Id = id;
            TenantId = tenantId;
            ScoreId = scoreId;
            Name = name;
        }
    }
```

3. Set DbContext:
```
            builder.Entity<Score>(b =>
            {
                b.ToTable(BrightDentistryConsts.DbTablePrefix + "Scores", BrightDentistryConsts.DbSchema);
                b.ConfigureByConvention();
            });
            
            builder.Entity<ScoreDetail>(b =>
            {
                b.ToTable(BrightDentistryConsts.DbTablePrefix + "ScoreDetails", BrightDentistryConsts.DbSchema);
                b.ConfigureByConvention();
            });
```

4. Create a appservice method:
```
        public async Task Test2()
        {
            var score = await _scoreRepository.GetAsync(Guid.Parse("39f24517-e636-c0e7-9d9f-c979bdef7218"));  // An existing score
            score.ScoreDetails.Add(new ScoreDetail(GuidGenerator.Create(), CurrentTenant.Id, score.Id, "1"));
            score.ScoreDetails.Add(new ScoreDetail(GuidGenerator.Create(), CurrentTenant.Id, score.Id, "2"));

            await _scoreRepository.UpdateAsync(score);
        }
```

5. Run the method, then you get:
`[ERR] Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.`

Abp v1.1.2, Npgsql

**Comment by olicooper** [comment]
You probably need to configure concurrency stamps for your DbContext by adding `b.ConfigureFullAuditedAggregateRoot();` and `b.ConfigureFullAudited();` respectively (which automatically calls `b.ConfigureConcurrencyStamp()` internally). You might need to add another migration afterwards as well.

**Comment by gdlcf88** [comment]
> You probably need to configure concurrency stamps for your DbContext by adding `b.ConfigureFullAuditedAggregateRoot();` and `b.ConfigureFullAudited();` respectively (which automatically calls `b.ConfigureConcurrencyStamp()` internally). You might need to add another migration afterwards as well.

`b.ConfigureByConvention()` contains these methods.
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs#L16

**Comment by olicooper** [comment]
Ah I missed that sorry! I don't have postgresql setup right now to test it myself. Maybe delete your migrations and try again? If that doesn't work then it might be a bug.

**Comment by maliming** [comment]
see https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#detectchanges-honors-store-generated-key-values

```
builder.Entity<ScoreDetail>(b =>
{
	b.ToTable(BrightDentistryConsts.DbTablePrefix + "ScoreDetails", BrightDentistryConsts.DbSchema);
	b.Property(e => e.Id).ValueGeneratedNever();
	b.ConfigureByConvention();
});

```

**Comment by gdlcf88** [comment]
It helps. Thanks @maliming .

By the way, is there any way to simplify? It seems not friendly to beginners. (Even if it will be written in the manual to remind us)

**Comment by maliming** [comment]
@hikalkan How do we deal with it?

**Comment by hikalkan** [comment]
Maybe we can call `ValueGeneratedNever()` for Guid keys if it does not define `DatabaseGeneratedAttribute` (to be compatible with ``AbpDbContext.TrySetGuidId``).

**Comment by hikalkan** [comment]
I'm closing this since it is already resolved: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L529

**Comment by maliming** [comment]
It is recommended to generate the Id value through the abp framework.

https://github.com/abpframework/abp/issues/2450#issuecomment-568986527
https://github.com/abpframework/abp/issues/3795
