### ISSUE TITLE
SQL Server Warning on Clustered Indexes

### ISSUE THREAD

**Issue by kbowma** [abpframework/abp#2451]
When I generated a SQL Server 2019 script for the default tables and run it, I get the following warnings:
* Warning! The maximum key length for a clustered index is 900 bytes. The index 'PK_IdentityServerApiSecrets' has maximum length of 8516 bytes. For some combination of large values, the insert/update operation will fail.
* Warning! The maximum key length for a clustered index is 900 bytes. The index 'PK_IdentityServerClientClaims' has maximum length of 1016 bytes. For some combination of large values, the insert/update operation will fail.
* Warning! The maximum key length for a clustered index is 900 bytes. The index 'PK_IdentityServerClientPostLogoutRedirectUris' has maximum length of 4016 bytes. For some combination of large values, the insert/update operation will fail.
* Warning! The maximum key length for a clustered index is 900 bytes. The index 'PK_IdentityServerClientRedirectUris' has maximum length of 4016 bytes. For some combination of large values, the insert/update operation will fail.
* Warning! The maximum key length for a clustered index is 900 bytes. The index 'PK_IdentityServerClientSecrets' has maximum length of 8516 bytes. For some combination of large values, the insert/update operation will fail.

**Comment by maliming** [comment]
The identity server did not create indexes for these columns.

https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Extensions/ModelBuilderExtensions.cs

**Comment by maliming** [comment]
> As I see the IDS4 implementation, they defined Id properties to the entities. But our entities has no Id property. We are implementing DDD and these entities are not aggregate roots, so we didn't define an unnecessary Id.

> I don't know how to solve the problem. Maybe we need to decrease the total length of the primary keys, or define an Id property for these entities (which will require the code change on the entities and other services). This would be a big breaking change. We can go with the first option if we need.

**Comment by hikalkan** [comment]
Changing entity structure is a breaking change for existing applications. I moved it to v3.0.

@kbowma you can re-arrange max lengths in your application (in the MigrationDbContext onmodelcreating) or use it like that (because it will not be a problem in practical).

**Comment by maliming** [comment]
Let us try to solve this problem in identity server 4.0. https://github.com/abpframework/abp/issues/4461
