### ISSUE TITLE
adfs signout issue

### ISSUE THREAD

**Issue by jortygu** [abpframework/abp#2454]
I have add an ADFS IDP by WsFederation ,but when I logout(/Account/Logout),the ADFS IDP status is still log-in.
Bellow is my code,my question is how can i config when i logout ,then ADSF status is also logout.
```
context.Services.AddAuthentication()
.AddIdentityServerAuthentication(options =>
{
	options.Authority = configuration["AuthServer:Authority"];
	options.RequireHttpsMetadata = false;
	options.ApiName = "AdminLTEPro";
})
.AddWsFederation("adfs", "adfs", options => {
	options.MetadataAddress = "https://adfstest/federationmetadata/2007-06/federationmetadata.xml";
	options.Wtrealm = "urn:identityServer";
});
```

**Comment by hikalkan** [comment]
See http://docs.identityserver.io/en/latest/topics/signout_external_providers.html
That may help.

**Comment by jortygu** [comment]
> See http://docs.identityserver.io/en/latest/topics/signout_external_providers.html
> That may help.

Thanks hikalkan. This is useful to me.
