### ISSUE TITLE
Finds and returns a user, if any, who has the specified phone number

### ISSUE THREAD

**Issue by geffzhang** [abpframework/abp#2455]
IdentityUserStore need a method Finds and returns a user, if any, who has the specified phone number

**Comment by maliming** [comment]
**IdentityUserStore** implements the interface of asp net core identity, and identity has no related methods for phone number. If you need you can extend it yourself.

https://github.com/abpframework/abp/blob/655e8f0102f236557eac1604785beb1a0f04b13f/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserStore.cs#L21-L34
