### ISSUE TITLE
Define a custom 'admin' email/password when creating a tenant?

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2458]
I'd like to define custom values for the Email and Password when new tenants are created. Ideally this can be defined when creating a new tenant via the UI or in appsettings.json. is this possible already?

I've seen **[this code](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeedContributor.cs#L19)** to pull the info from the SeedContext but I'm not sure where I should define the values.

**Comment by maliming** [comment]
hi @olicooper 

in MyProjectNameDbMigrationService's **MigrateAsync** method.
```
Logger.LogInformation("Executing database seed...");

var email = _configuration["AdminEmail"];
var password = _configuration["AdminPassword"];

await _dataSeeder.SeedAsync(new DataSeedContext()
	.WithProperty("AdminEmail", "maliming@abp.io")
	.WithProperty("AdminPassword", "P@ssW0rd"));
```

https://github.com/abpframework/abp/blob/6cdbfc507ce54820e96a4865bafeed1f09d34057/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Data/MyProjectNameDbMigrationService.cs#L34

**Comment by olicooper** [comment]
Hi @maliming, thanks for your previous comments.

I believe the code snippet you supplied only applies when running DbMigrator? When creating a new tenant via the UI it didn't change the username or password and I need it to work for every tenant created.

As an alternative, I tried to override the class by creating a custom [IdentityDataSeedContributor](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeedContributor.cs#L7) and used `[Dependency(ReplaceServices = true)]` 

Have I missed something?

**Comment by maliming** [comment]
You can wait for the tenant module to support custom admin username and password.

`//TODO: Set admin email & password..? `

https://github.com/abpframework/abp/blob/6a073e6b56350b4b8b949bcc5a862ccfe7318e05/modules/tenant-management/src/Volo.Abp.TenantManagement.Application/Volo/Abp/TenantManagement/TenantAppService.cs#L45-L56

**Comment by mrs01dev** [comment]
For seeding Custom User Name , Password   and Tenants 
1- modify  MyProjectNameDbMigrationService.cs 
 public class ***DbMigrationService : ITransientDependency
    {
        public ILogger<***DbMigrationService> Logger { get; set; }

        private readonly IDataSeeder _dataSeeder;
        private readonly IEnumerable<ITSPDbSchemaMigrator> _dbSchemaMigrators;
        private readonly ITenantRepository _tenantRepository;
        private readonly ITenantManager _tenantManager;
        private readonly ICurrentTenant _currentTenant;
        private readonly IConfiguration _configuration;
        public ***DbMigrationService(
            IDataSeeder dataSeeder,
            IEnumerable<ITSPDbSchemaMigrator> dbSchemaMigrators,
            ITenantRepository tenantRepository,
            ITenantManager tenantManager,
            ICurrentTenant currentTenant,
            IConfiguration configuration)
        {
            _dataSeeder = dataSeeder;
            _dbSchemaMigrators = dbSchemaMigrators;
            _tenantRepository = tenantRepository;
            _tenantManager = tenantManager;
            _currentTenant = currentTenant;
            _configuration = configuration;
            Logger = NullLogger<TSPDbMigrationService>.Instance;
        }

        public async Task MigrateAsync()
        {
            Logger.LogInformation("Started database migrations...");

            await MigrateDatabaseSchemaAsync();
            await SeedTenantAsync();
            await SeedDataAsync();

            Logger.LogInformation($"Successfully completed host database migrations.");

            var tenants = await _tenantRepository.GetListAsync(includeDetails: true);

            var migratedDatabaseSchemas = new HashSet<string>();
            foreach (var tenant in tenants)
            {
                using (_currentTenant.Change(tenant.Id))
                {
                    if (tenant.ConnectionStrings.Any())
                    {
                        var tenantConnectionStrings = tenant.ConnectionStrings
                            .Select(x => x.Value)
                            .ToList();

                        if (!migratedDatabaseSchemas.IsSupersetOf(tenantConnectionStrings))
                        {
                            await MigrateDatabaseSchemaAsync(tenant);

                            migratedDatabaseSchemas.AddIfNotContains(tenantConnectionStrings);
                        }
                    }

                    await SeedDataAsync(tenant);
                }

                Logger.LogInformation($"Successfully completed {tenant.Name} tenant database migrations.");
            }

            Logger.LogInformation("Successfully completed database migrations.");
        }

        private async Task MigrateDatabaseSchemaAsync(Tenant tenant = null)
        {
            Logger.LogInformation(
                $"Migrating schema for {(tenant == null ? "host" : tenant.Name + " tenant")} database...");

            foreach (var migrator in _dbSchemaMigrators)
            {
                await migrator.MigrateAsync();
            }
        }

        private async Task SeedDataAsync(Tenant tenant = null)
        {
            Logger.LogInformation($"Executing {(tenant == null ? "host" : tenant.Name + " tenant")} database seed...");
            string userEmail = string.Empty;
            string userPassword = string.Empty;
            IConfigurationSection userConfigurationSection = _configuration.GetSection("AdminUserIdentity");
            if (userConfigurationSection!= null)
            {
                userEmail = userConfigurationSection["Email"] ?? "admin@abp.io";
                userPassword = userConfigurationSection["Password"] ?? "1q2w3E*";
            }
            else
            {
                userEmail= "admin@abp.io";
                userPassword = "1q2w3E*";
            }
            // change user name by prefixing with tenantName
            if (tenant != null)
            {
                userEmail = tenant.Name + "_"+ userEmail;
                await _dataSeeder.SeedAsync(
                new DataSeedContext(tenant.Id)
            .WithProperty("AdminEmail", userEmail)
            .WithProperty("AdminPassword", userPassword)
            );

            }
            else
            {
                
                await _dataSeeder.SeedAsync(
               new DataSeedContext(null)
           .WithProperty("AdminEmail", userEmail)
           .WithProperty("AdminPassword", userPassword)
           );

            }


        }

        private async Task SeedTenantAsync()
        {
            List<string> tenantNameslist =new List<string>();

            var tenantConfigurationSection = _configuration.GetSection("TenantData:TenantNameslist");  
            if (tenantConfigurationSection != null)
            {
                 tenantNameslist = tenantConfigurationSection.Get<List<string>>();
               

            }
          
            tenantNameslist.Sort();


            foreach (string tenantName in tenantNameslist)
            {
                Tenant tenant = await _tenantManager.CreateAsync(tenantName);
             
               await  _tenantRepository.InsertAsync(tenant,true);


            }

        }
    }

2- add to appsettings in ***DbMigrator project
"AdminUserIdentity": {
    "Email": "admin@abp.io",
    "Password": "1q2w3E*"
  },
  "TenantData": {

    "TenantNameslist": [

      "Tokyo",
      "London",
      "Cairo",
      "Astana",
      "Berlin",
      "Washington",
    ]
    
  }
