### ISSUE TITLE
RolePermissionValueProvider optimization suggestion

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2460]
At present, `CheckAsync` in RolePermissionValueProvider get user's roles by claims. When admin user update user's roles, claims in JWT will not be updated. So admin should remind the user to relogin(get a new accesstoken) to get the new roles.

Just think about it, if an employee is fired, I remove his role, but he still has permissions, it is really dangerous.

Maybe RolePermissionValueProvider should cache user's roles, instead of reading roles from claims, what do you think? @hikalkan @maliming

**Comment by gdlcf88** [comment]
Or maybe we can create a "refresh flag" in cache, when RolePermissionValueProvider gets user's roles, check the flag first, and if it is existing, make current accesstoken invalid.

**Comment by maliming** [comment]
Claim-based authorization is common, of course ABP allows you to replace the built-in `RolePermissionValueProvider`, etc ...

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1

**Comment by Y2zz** [comment]
I override the CheckAsync method of RolePermissionValueProvider to support real-time checking

**Comment by gdlcf88** [comment]
> I override the CheckAsync method of RolePermissionValueProvider to support real-time checking

In my submission, this is a communal need for many apps, so it would be even better if ABP can provide a option to enable real-time updated roles.

**Comment by Y2zz** [comment]
> > 我重写RolePermissionValueProvider的CheckAsync方法以支持实时检查
> 
> 在我的提交中，这是许多应用程序的共同需求（由于存在危险），因此，如果ABP可以提供启用实时更新角色的选项，那就更好了。

I think can add an option to control

**Comment by Y2zz** [comment]
> > I override the CheckAsync method of RolePermissionValueProvider to support real-time checking
> 
> In my submission, this is a communal need for many apps (because of its danger), so it would be even better if ABP can provide a option to enable real-time updated roles.

I think can add an option to control

**Comment by hikalkan** [comment]
This is not a unique problem to roles. Insted, we should invalidate the access token when a user related change happens. `SecurityStamp` of the User is for this purpose. It can be updated when a user role has changed (I am not sure but maybe it is already implemented by the UserManager of the Microsoft Identity) then it should be verified on every request (can be cached for performance reasons).

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/2980
