### ISSUE TITLE
AbpIdentityOptionsFactory will cause IdentityOptions settings to default value

### ISSUE THREAD

**Issue by zredb** [abpframework/abp#2461]
I config the Password option as below in ConfigureServices method:
 context.Services.Configure<IdentityOptions>(options =>
            {
                // Password settings.
                options.Password.RequireDigit = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequiredLength = 3;
                options.Password.RequiredUniqueChars = 1;

                // Lockout settings.
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                options.Lockout.MaxFailedAccessAttempts = 15;
                options.Lockout.AllowedForNewUsers = true;

                // User settings.
                options.User.AllowedUserNameCharacters =
                    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";
                options.User.RequireUniqueEmail = true;
            });
   but this has no effect because after OverrideOptionsAsync(IdentityOptions options) method excuted. the IdentityOptions will fall back to default. 
abp version is 1.0.2

**Comment by maliming** [comment]
You can use the settings module to change its value
https://docs.abp.io/en/abp/latest/Settings
https://docs.abp.io/en/abp/latest/Modules/Setting-Management

or change the default value of the identity setting.
```
app.ApplicationServices.GetService<ISettingDefinitionManager>().Get(IdentitySettingNames.Password.RequiredLength).DefaultValue = 6.ToString();
```

**Comment by zredb** [comment]
Hello,
@maliming  How can I change the default value of the identity settings?

**Comment by maliming** [comment]
```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
	app.ApplicationServices.GetService<ISettingDefinitionManager>().Get(IdentitySettingNames.Password.RequiredLength).DefaultValue = 6.ToString();

	app.InitializeApplication();
}

```

**Comment by MMoussaSURE** [comment]
@maliming
 i configure the blow 
context.Services.Configure(options =>
{
            // Lockout settings.
            options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(2);
            options.Lockout.MaxFailedAccessAttempts = 2;
            options.Lockout.AllowedForNewUsers = true;
        
  });
 
and at AbpSettingDefentions  table i  change the default values for the records with  the blow names as following 
 Abp.Identity.Lockout.LockoutDuration = 120
 Abp.Identity.Lockout.MaxFailedAccessAttempts = 2 
Abp.Identity.Lockout.AllowedForNewUsers = true



can you explain

**Comment by maliming** [comment]
hi @MMoussaSURE 

Can you create a new issue and share your code?

Thanks.
