### ISSUE TITLE
How to set the default culture in "BackendAdminApp.Host"?

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2469]
In the "BackendAdminApp.Host" project's BackendAdminAppHostModule.cs I add the following code force to set all the DefaultCultureName to the culture I needed.But it didn't work, the culture is also "en",and I found  the culture resource I added can work if the key is not the same as others.
And also I tryed to add the cookie in the start page like the code below,because I found the "/Abp/Languages/Switch" do the same thing.But it did'nt work also.
 

 ```cs
   Configure<AbpLocalizationOptions>(options =>
            {
                 options.Languages.Add(new LanguageInfo("en", "en", "English"));
                 options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));
                 foreach (var key in options.Resources.Keys)
                 {
                     options.Resources[key].DefaultCultureName = "zh-Hans";
                 }
            });
```
 ```cs
  
  public void OnGet()
        {
            string cookieValue = CookieRequestCultureProvider.MakeCookieValue(new RequestCulture("zh-Hans", "zh-Hans"));

            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, cookieValue, new CookieOptions
            {
                Expires = DateTime.Now.AddYears(2)
            });
        }

**Comment by hikalkan** [comment]
Set `Abp.Localization.DefaultLanguage` setting (as constant: `LocalizationSettingNames.DefaultLanguage`) to `zh-Hans`. See https://docs.abp.io/en/abp/latest/Settings#setting-values-in-the-application-configuration to simply set it in the appsettings.json

**Comment by abllyboy** [comment]
I added like this way but it does not work, is it right?
![setting](https://user-images.githubusercontent.com/57399417/71559002-f78d1980-2a93-11ea-949e-29b5167fa295.jpg)

**Comment by hikalkan** [comment]
Should be inside the `Settings` section.

{
  "Settings": {
    "Abp.Localization.DefaultLanguage": "zh-Hans"
  }
}

**Comment by abllyboy** [comment]
when I added the settings in AuthServer.Host and BackendAdminApp.Host ,the AuthServer.Host's default language changed,but the BackendAdminApp.Host not.Even though I added the settings in "IdentityService.Host" and "BackendAdminAppGateway.Host" it not change also.

**Comment by abllyboy** [comment]
I stills think this is an issue,even I set the "Abp.Localization.DefaultLanguage" in  the table “AbpSettings” to "zh-Hans" and when I visited "http://localhost:51954/Abp/ApplicationConfigurationScript" the settings show the default language is 'zh-Hans' but the words also show as english.Please see the screenshot below:
<img width="1093" alt="1" src="https://user-images.githubusercontent.com/57399417/71711668-fc0f5480-2e3c-11ea-919d-b334ac3702ee.png">
<img width="585" alt="2" src="https://user-images.githubusercontent.com/57399417/71711673-06315300-2e3d-11ea-92b8-bbe165c09b0f.png">
<img width="557" alt="3" src="https://user-images.githubusercontent.com/57399417/71711675-07fb1680-2e3d-11ea-815e-55df985b49c0.png">

**Comment by hikalkan** [comment]
Clear all cookies and try again. Also, be sure that the default language setting was not set for the user in the database.

**Comment by mentianyi** [comment]
The reason is your default cultrue is "zh-CN", not "zh-Hans".

**Comment by maliming** [comment]
I write a class library that can map these language codes.

https://github.com/maliming/Owl.Abp.CultureMap
```c#
var maps = new Dictionary<string, string>
{
	{"zh", "zh-Hans"},
	{"zh-CN", "zh-Hans"},
	{"zh-Hant", "zh-Hans"},
	{"zh-TW", "zh-Hans"}
}
```

**Comment by x2009again** [comment]
> 
> 
> Should be inside the `Settings` section.
> 
> ```json
> {
>   "Settings": {
>     "Abp.Localization.DefaultLanguage": "zh-Hans"
>   }
> }
> ```

no effect

**Comment by x2009again** [comment]
> 
> 
> I stills think this is an issue,even I set the "Abp.Localization.DefaultLanguage" in the table “AbpSettings” to "zh-Hans" and when I visited "http://localhost:51954/Abp/ApplicationConfigurationScript" the settings show the default language is 'zh-Hans' but the words also show as english.Please see the screenshot below:
> <img alt="1" width="1093" src="https://user-images.githubusercontent.com/57399417/71711668-fc0f5480-2e3c-11ea-919d-b334ac3702ee.png">
> <img alt="2" width="585" src="https://user-images.githubusercontent.com/57399417/71711673-06315300-2e3d-11ea-92b8-bbe165c09b0f.png">
> <img alt="3" width="557" src="https://user-images.githubusercontent.com/57399417/71711675-07fb1680-2e3d-11ea-815e-55df985b49c0.png">

Have you solved it?

**Comment by xyfy** [comment]
@abllyboy do you fixed it?  I  can not make it works

**Comment by x2009again** [comment]
> 
> 
> In the "BackendAdminApp.Host" project's BackendAdminAppHostModule.cs I add the following code force to set all the DefaultCultureName to the culture I needed.But it didn't work, the culture is also "en",and I found the culture resource I added can work if the key is not the same as others.
> And also I tryed to add the cookie in the start page like the code below,because I found the "/Abp/Languages/Switch" do the same thing.But it did'nt work also.
> 
> ```cs
>   Configure<AbpLocalizationOptions>(options =>
>            {
>                 options.Languages.Add(new LanguageInfo("en", "en", "English"));
>                 options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));
>                 foreach (var key in options.Resources.Keys)
>                 {
>                     options.Resources[key].DefaultCultureName = "zh-Hans";
>                 }
>            });
> ```
> 
> ```cs
>  
>  public void OnGet()
>        {
>            string cookieValue = CookieRequestCultureProvider.MakeCookieValue(new RequestCulture("zh-Hans", "zh-Hans"));
> 
>            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, cookieValue, new CookieOptions
>            {
>                Expires = DateTime.Now.AddYears(2)
>            });
>        }
> ```

I got it.
just modify in GateWay，Not in WebSite.And add app.UseAbpRequestLocalization(); into GatewayHostModule.@xyfy

**Comment by journey191** [comment]
> Should be inside the `Settings` section.
> 
> ```json
> {
>   "Settings": {
>     "Abp.Localization.DefaultLanguage": "zh-Hans"
>   }
> }
> ```

It worked except in Identity Moudule,for example,when I create a user with duplicate UserName,the err msg is still in English.

**Comment by x2009again** [comment]
> 
> 
> > Should be inside the `Settings` section.
> > ```json
> > {
> >   "Settings": {
> >     "Abp.Localization.DefaultLanguage": "zh-Hans"
> >   }
> > }
> > ```
> 
> It worked except in Identity Moudule,for example,when I create a user with duplicate UserName,the err msg is still in English.



> 
> 
> > In the "BackendAdminApp.Host" project's BackendAdminAppHostModule.cs I add the following code force to set all the DefaultCultureName to the culture I needed.But it didn't work, the culture is also "en",and I found the culture resource I added can work if the key is not the same as others.
> > And also I tryed to add the cookie in the start page like the code below,because I found the "/Abp/Languages/Switch" do the same thing.But it did'nt work also.
> > ```cs
> >   Configure<AbpLocalizationOptions>(options =>
> >            {
> >                 options.Languages.Add(new LanguageInfo("en", "en", "English"));
> >                 options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));
> >                 foreach (var key in options.Resources.Keys)
> >                 {
> >                     options.Resources[key].DefaultCultureName = "zh-Hans";
> >                 }
> >            });
> > ```
> > 
> > 
> > ```cs
> >  
> >  public void OnGet()
> >        {
> >            string cookieValue = CookieRequestCultureProvider.MakeCookieValue(new RequestCulture("zh-Hans", "zh-Hans"));
> > 
> >            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, cookieValue, new CookieOptions
> >            {
> >                Expires = DateTime.Now.AddYears(2)
> >            });
> >        }
> > ```
> 
> I got it.
> just modify in GateWay，Not in WebSite.And add app.UseAbpRequestLocalization(); into GatewayHostModule.@xyfy

@journey191

**Comment by journey191** [comment]
@x2009again Hi,
My project type is Application(Angular),not Module.There is no GatewayHostModule in my project.
I reuqest the API `/api/abp/application-configuration` and the response show that `currentCulture`  is already Chinese.
![image](https://user-images.githubusercontent.com/11626700/99018385-e27a8580-2594-11eb-8014-582e55e0534f.png)

But the Excetion Message is still in English.For example,client request get  "Identity.DuplicateUserName",not expected "用户名 '{0}' 已存在."

**Comment by x2009again** [comment]
> 
> 
> @x2009again Hi,
> My project type is Application(Angular),not Module.There is no GatewayHostModule in my project.
> I reuqest the API `/api/abp/application-configuration` and the response show that `currentCulture` is already Chinese.
> ![image](https://user-images.githubusercontent.com/11626700/99018385-e27a8580-2594-11eb-8014-582e55e0534f.png)
> 
> But the Excetion Message is still in English.For example,client request get "Identity.DuplicateUserName",not expected "用户名 '{0}' 已存在."

UI should access api through gateway,not directly access the api.

**Comment by 344089386** [comment]
I have the same problem. Is there a solution?
