### ISSUE TITLE
Email setting and sending sample?

### ISSUE THREAD

**Issue by buzzlu** [abpframework/abp#2471]
I am new to ABP and I'd like to publish a notice via email on demand.  

Which module should I use? AbpMailKitModule?

If so, how to set the email server information? Any examples?

Thanks very much.

**Comment by maliming** [comment]
You can change email related settings.  `AbpMailKitModule `just uses MailKit to send mail.

Eventually use `IEmailSender `to send mail.

https://github.com/abpframework/abp/blob/65cd3ea8ab7b919cf4ff958dd272415b38ad7926/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/EmailSettingProvider.cs#L11-L23

**Comment by hikalkan** [comment]
I just added a new sections to the Setting document:

Setting Values in the Application Configuration: https://github.com/abpframework/abp/blob/dev/docs/en/Settings.md#setting-values-in-the-application-configuration

See all setting names related to email sending here: https://github.com/abpframework/abp/blob/65cd3ea8ab7b919cf4ff958dd272415b38ad7926/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/EmailSettingNames.cs

Then use the `IEmailSender` to send emails as @maliming has written before.

**Comment by johnnba** [comment]
@hikalkan  @maliming 

i create a backgroudjob to send email, however  i met the follwing error,  how could i do with it ,thanks so much

---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'XXXX.Web.EmailSendingJob' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Emailing.IEmailSender emailSender' of constructor 'Void .ctor(Volo.Abp.Emailing.IEmailSender)'.
