### ISSUE TITLE
How to understand uow design？

### ISSUE THREAD

**Issue by squarezx** [abpframework/abp#2475]
Recently I was looking at the code of the uow module and I have some questions. If there is an application service method that is time-consuming, a real UnitOfWork object is created through the IUnitOfWorkManager.Begin () method. Before this object executes the Dispose method, are other threads calling other application service methods create ChildUnitOfWork object? Which means that the DataContext object in all Repository objects is the same?

**Comment by hikalkan** [comment]
>Before this object executes the Dispose method, are other threads calling other application service methods create ChildUnitOfWork object

No. Unit of work is thread basis (actually, it uses `AsyncLocal`, so it is safe with async/await pattern), so other threads will use their own UOW, database connection, transaction, repository and dbcontext instances.
