### ISSUE TITLE
UnitOfWork not working with Quartz.net IJob

### ISSUE THREAD

**Issue by ChEhrhard** [abpframework/abp#2480]
My Jobs are injected via IOC ( Autofac ) and this works well with non proxied jobs. 

The UOW Attribute makes the Job being proxied by Castle. 

When i try to get the Jobs in my JobFactory, the type in Jobdetail.JobType is the castle proxy type. But this proxy type isn't registered in AutoFac so the factory didn't find him ...

What i am missing ?

**Comment by maliming** [comment]
hi @ChEhrhard 

Please share some code to help us understand your problem.

**Comment by hikalkan** [comment]
You can use `ProxyHelper.UnProxy` to get the non proxied base object type. But if that doesn't work, please share some code as @maliming has written.
