### ISSUE TITLE
Override html page of module

### ISSUE THREAD

**Issue by MROALI** [abpframework/abp#2481]
Hello, 
I was wondering how can i override the html page of the account module, and other abp modules?
Do i need to include source code of the module in my solution? Or there is a way to ovveride it.. i want to 
 -customise the gui And use for example material design bsb..
-  change the menu items position..
- hide the tenant select.
- redirect tenant by refering to domain name or multiple domain name... (can we add in the settings a domains parameters related to tenant).

I will apreciate if anyone could help and guide me to a good solution..

Thankyou in advance

**Comment by maliming** [comment]
> Embedded razor views/pages are available in the application without any configuration. Simply place them into the standard Views/Pages virtual folders of the module being developed.
 An embedded view/page can be overrided if a module/application locates a new file into the same location as mentioned above.

https://docs.abp.io/en/abp/latest/Virtual-File-System#views-pages


And https://github.com/abpframework/abp/issues/631

**Comment by MROALI** [comment]
Thankyou @maliming i am gona refer to the basictheme project in order to personnalise the theme.

Otherwise do you have any idea about  ; 
how to redirect tenant by referring to domain name or multiple domain name... (can we add in the settings a domains parameters related to tenant).
