### ISSUE TITLE
MongoDB & Migration

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2482]
Hi,

I'm looking for a sample to migration a project with MongoDB.

Some kind of operations:
- creation of new collections
- delete old collections
- schema modifications
- data seed

I only see the Null...DbSchemaMigrator, but even there I don't know how I can create new collection and how I can access the MongoDB client to insert new datas.

Any ideas ?

**Comment by hikalkan** [comment]
No need to create new collections for mongodb, it is automatically done by mongodb. In most cases, you don't need to manipulate the schema. If you need it (to rename a field), you should create your own solution. ABP doesn't provide an infrastructure for it. You can search web, it is a common thing.

Data seed system is same with EF Core and already configured in the startup template.

**Comment by pascalfossouo** [comment]
Hi, I have this error when running the .DBMigrator 

Unhandled exception. Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.Identity.IdentityDataSeedContributor -> Volo.Abp.Identity.IdentityDataSeeder -> Castle.Proxies.IdentityUserManagerProxy.


  "ConnectionStrings": {
    "Default": "mongodb://localhost:27017/BookStore"
  },

**Comment by maliming** [comment]
hi @pascalfossouo 

Please create a new issue.
