### ISSUE TITLE
IdentityServer with abp Modular Template

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2485]
Hi, 
I saw your sample about modular template https://github.com/abpframework/abp/tree/master/samples/BookStore-Modular
In this project, each module has its own identity server in host folder of the module, why?
it is not better we create a separate module for IdentityServer for managing identity and user management? usually, we use IdentityServer in a single place and other components use this unifies Identity server.

**Comment by hikalkan** [comment]
>In this project, each module has its own identity server in host folder of the module, why?

Each module has its own identity server to make possible to separately develop, run and test it. So, it is only for development time. A module should not host itself (unless it is deployed as a microservice). So, host folder projects are just for development.

In production, you will use the module in an application (as a NuGet or project reference) and it will use your application's identityserver.

**Comment by mehdihadeli** [comment]
ok thanks, please complete your docs, the documentation is very incomplete
