### ISSUE TITLE
SettingCacheItem Should Use IgnoreMultiTenancy Attribute

### ISSUE THREAD

**Issue by xkaede** [abpframework/abp#2486]
If you do not add this attribute. This will cause the cache to not be cleared properly. 
eg:
I have a global mail-related Setting, such as "Abp.Mailing.DefaultFromAddress". The default value is: "noreply@abp.io"

1. First I read this setting on the tenant "Default". The value is "noreply@abp.io".
2. Then I call SettingManager.SetGlobalAsync method on the host side. Modify the value to "abc@abp.io".
3. At this time switch back to the tenant Default and read this Setting. You will find the value "noreply@abp.io" instead of "abc@abp.io".

**Comment by maliming** [comment]
Related: https://github.com/abpframework/abp/issues/2429#issuecomment-568381412
