### ISSUE TITLE
There is no suitable method  `IncludeDetails` to override in EfCoreRepository

### ISSUE THREAD

**Issue by inamvar** [abpframework/abp#2488]
I have a repository inherited from `EfCoreRepository` I wrote an extension method  in  `PmsCloudEfCoreQueryableExtensions.cs` like this : 
``` C#
  public static IQueryable<RateGroup> IncludeDetails(this IQueryable<RateGroup> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }

            return queryable
                .Include(x => x.Mpe);


        }
```

then I tried to override `IncludeDetails` method  in the repository as the [documentaion](https://docs.abp.io/en/abp/latest/Best-Practices/Entity-Framework-Core-Integration#repository-implementation) said.
. but I got this error:

![image](https://user-images.githubusercontent.com/6972027/71545596-612cfb00-29a2-11ea-888c-45407f140b9f.png)

**Comment by acjh** [comment]
Repository's `IncludeDetails` was refactored to `WithDetails` in https://github.com/abpframework/abp/commit/649f80e8de2231f6e3d6ad645697832d76cad905 (released in version 0.3.7).

```c#
public override IQueryable<RateGroup> WithDetails()
{
    return GetQueryable().IncludeDetails();
}
```

I've created PR #2493 to update the docs.
