### ISSUE TITLE
Logon Question

### ISSUE THREAD

**Issue by shrimpwang** [abpframework/abp#2494]
Generate the project at http://abp.io/get-started, restore the database, run the project, and click login to enter your account and password
No screenshot content appears
![7](https://user-images.githubusercontent.com/57536643/71554954-8d0eb600-2a60-11ea-88d2-0576505a87ba.png)

**Comment by hikalkan** [comment]
@maliming can you understand & test this? Thanks.

**Comment by shrimpwang** [comment]
hello
I run the project
![1](https://user-images.githubusercontent.com/57536643/71555247-0c05ed80-2a65-11ea-8272-6db199db9bd6.png)
Enter account and password and click login
![2](https://user-images.githubusercontent.com/57536643/71555254-2a6be900-2a65-11ea-90b3-638f9453ea46.png)
又返回首页
![1](https://user-images.githubusercontent.com/57536643/71555273-5dae7800-2a65-11ea-9e58-28757e66bbaa.png)

**Comment by shrimpwang** [comment]
@hikalkan @maliming

**Comment by AhmadAlMunajjed** [comment]
I've experienced something related to this issue, it might help understanding it.  After logging in, the authentication works properly in the same browser tab. But, when I open a new tab, I find that I'm not logged in (on the new tab only. However, the first tab still logged in!) 
So, it seems the authentication works on tab level only! 
And, to fix it I had to change the OAuthStorage in angular-oauth2-oidc to localStorage.
I don't have prior experience with angular-oauth2-oidc lib so I don't know if this is the default behaviour of password token authentication, or it's something related to abp.
 
@shrimpwang Do you face that when opening a new tab?

**Comment by maliming** [comment]
@shrimpwang 
Are you using the **DbMigrator** application to migrate the database?
https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-MVC-Template#using-the-dbmigrator-application

**Comment by shrimpwang** [comment]
@maliming ,yes,I'm using DbMigrator Migrate database.

我找到了问题的根源：我本地一款浏览器程序造成的不显示管理权限栏目。当我切换到Internet explorer、safari或chrome时，可以正常显示管理权限

I got to the root of the problem: I had a local browser program that didn't show the admin rights section.When I switched to Internet explorer, safari, or chrome, I was able to display administrative rights as normal

Thank you
![ok](https://user-images.githubusercontent.com/57536643/71568583-6eadc680-2b03-11ea-8aea-4c5ef2c0d73a.png)
