### ISSUE TITLE
Drop down list with Dynamics Forms and DateTime issue

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2501]
1. As per attached; i want date only note date time for generated form fields

2. Any code sample where i can see drop downs based of foreign keys fields, the book store sample uses book type from enum list. I want to see sample where the list is in DB. with a foreign key

![image](https://user-images.githubusercontent.com/4476822/71563708-11832800-2aa5-11ea-8815-d9e9c405b1a8.png)

**Comment by yekalkan** [comment]
> As per attached; i want date only note date time for generated form fields

use `[DataType(DataType.Date)]` attribute. for example:
```
            [DataType(DataType.Date)]
            [Display(Name = "Day")]
            public DateTime Day { get; set; }
```

> Any code sample where i can see drop downs based of foreign keys fields, the book store sample uses book type from enum list. I want to see sample where the list is in DB. with a foreign key

see https://github.com/abpframework/abp/issues/617#issuecomment-443692943
