### ISSUE TITLE
IdentityServer - How to customize it ?

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2504]
Hi,

I use the identity server and I wish to :

- Provide a better UI for all the web pages, login/register/lost-pwd ( like : https://colorlib.com/wp/wp-content/uploads/sites/2/Login_v4.jpg )
- Add google authentication
- hide the tenant field, and manage it automatically when I user pay for a subscription by example

Does such features are possible ?

Thx

**Comment by hikalkan** [comment]
You've two options:

1. Move Account module's source code into your solution and freely customize it.
2. Override `.cshtml` files with the [virtual file system](https://docs.abp.io/en/abp/latest/Virtual-File-System).

In addition, you can create your own theme based on [the basic theme](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic). While it was not documented yet, you can check the source code and understand it.

**Comment by KevinFarrow** [comment]
As far a i'm aware there's no way of easily editing the existing pages (login etc.) or extend entities (adding files to the AbpUsers table etc.) without some drastic coding e.g. overriding files in the virtual file system and creating new modules and DbContexts. If it's RAD you're looking for, you've come to the wrong place. The following issues might help:

https://github.com/abpframework/abp/issues/469#issuecomment-425720097

https://github.com/abpframework/abp/issues/2336

https://github.com/abpframework/abp/issues/2335
