### ISSUE TITLE
How to use IdentityServer with angular in abp?

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2507]
Hi,
I want to use IdentityServer as oidc in my angular abp, is there any client angular service for doing this, for example, Implicit Flow in angular or I have to use other libraries such as `oidc-client`?

**Comment by hikalkan** [comment]
I suggest you to refer [IDS4's documentation](http://docs.identityserver.io/en/latest/). There is no pre-build example for it and we would implement it by reading the IDS4 docs.

**Comment by mehdihadeli** [comment]
ok thanks.
