### ISSUE TITLE
Customize and extend abp angular modules

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2508]
I want to customize some of the angular modules such as account and identity and extend them, I can't find the source of these modules. how can I do that?

**Comment by hikalkan** [comment]
Here the source code of all angular modules: https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages

In addition, @mehmet-erim are working to make the customization easier: https://github.com/abpframework/abp/issues/2404

**Comment by mehdihadeli** [comment]
thanks.
