### ISSUE TITLE
Error performing password flow TypeError: Cannot read property 'toLowerCase' of null 

### ISSUE THREAD

**Issue by lyling** [abpframework/abp#2509]
like issue #1669 said.
but i download the code today.

**Comment by mehmet-erim** [comment]
Can you reproduce the problem?
I just downloaded it. I didn't get any error.

Did you try it after clearing the browser cache?

**Comment by lyling** [comment]
always. i use yarn to restore pakcages get error: jasime mismatch sha1 value. i use npm install to make it build successfully
________________________________

**Comment by mehmet-erim** [comment]
We tried on Windows and macOS. We haven't seen any problems. 
Please describe it in detail.
Can you provide the steps to reproduce the problem?

**Comment by HenroOnline** [comment]
I have the same error message, I followed the steps from the tutorial. I did not create a project through the CLI but downloaded from the website.

**Comment by mehmet-erim** [comment]
Things to pay attention:

- Make sure that the OAuth configuration matches the backend OAuth configuration.
> You can find the OAuth configuration in the `environment.ts`.
- You should clean the browser cache, session storage and local storage.
- If you downloaded with the "Separate Identity Server" option, make sure that the `IdentityServer` project is running before open the Angular application.
