### ISSUE TITLE
Display the menu only authenticated 

### ISSUE THREAD

**Issue by riregi** [abpframework/abp#2513]
Hi, 

I would like to display the menu item only if authenticated is it possible?

I'm trying 

`````
ICurrentUser _user ????? ;   // is empty
if ( _user.IsAuthenticated) //  Check IsAuthenticated 
            {
                context.Menu.AddItem(
                new ApplicationMenuItem("Anagrafice", l["Menu:Anagrafiche"])
                    .AddItem(new ApplicationMenuItem("Anagrafiche.Aziende", l["Menu:Aziende"], url: "/Azienda"))
                );
            }`
`````

**Comment by maliming** [comment]
Please refer to: https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Web/Navigation/AbpIdentityWebMainMenuContributor.cs#L19

**Comment by martenw** [comment]
Was looking for the same thing and did not find a solution on the provided link above so just thought I would add this here also for reference, found that `RequireAuthenticated()` solved it.

```C#
context.Menu.AddItem(
    new ApplicationMenuItem(
        MyMenus.Home,
        l["Home"],
        "~/",
        icon: "far fa-list-alt",
        order: 1
    ).RequireAuthenticated()
);
```
