### ISSUE TITLE
Dropdowns in Dynamic forms when not using enum

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2516]
```
            CreateMap<CreateUpdateLeaveEntryDto,LeaveEntry>()
                .ForMember(d => d.LeaveType, opt => opt.MapFrom(src => src.LeaveTypeId))
  .ReverseMap()
  .ForPath(s => s.LeaveTypeId, opt => opt.MapFrom(src => src.LeaveType));
```

![image](https://user-images.githubusercontent.com/4476822/71621063-4e066f00-2bde-11ea-8b6b-f9e71a9e23c9.png)

**Comment by yekalkan** [comment]
> still doesn't work

What is the error?

**Comment by dicksonkimeu** [comment]
See below code

My generated form doesn't have the drop down, after i debug i can see the look up list populated well.

![image](https://user-images.githubusercontent.com/4476822/71615796-096dda00-2bc4-11ea-8fab-ebc7178e51f6.png)

![image](https://user-images.githubusercontent.com/4476822/71615693-8c426500-2bc3-11ea-8275-5eb86945a16d.png)

No error but it lists all fields in the look up table

![image](https://user-images.githubusercontent.com/4476822/71615825-2f937a00-2bc4-11ea-821c-0831d084014b.png)

**Comment by dicksonkimeu** [comment]
I was check below example; how do you them map `public string Country { get; set; } to the CountryId in the DBEntity class
`
```
public class DynamicFormsModel : PageModel
    {
       public MyModelDto Model { get; set; }

       public List<SelectListItem> CountryLookupList { get; set; }

       public void OnGet()
       {
           var countries = await _countryAppService.GetAllListAsync();
           CountryLookupList = countries.Select(c=> new SelectListItem { Value = C.Id, Text = C.Name}).ToList();
       }

       public class MyModelDto 
       {
           [SelectItems(nameof(CountryLookupList))]
           public string Country { get; set; }
       }
   }
```
