### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2517]
Am using a single tiered architecture i.e I use the Web App module to host API...I hope that's the right description.

Swagger works fine.

How can an API Client access this API using an access token ? How can I get an access token ?

**Comment by maliming** [comment]
> Am using a single tiered architecture i.e I use the Web App module to host API...I hope that's the right description.

Can you share a screenshot of your project structure?

![image](https://user-images.githubusercontent.com/6908465/71608243-c1968500-2bba-11ea-8b22-1400bc5658d0.png)

**Comment by dicksonkimeu** [comment]
Its just 100% like what you have shared.

**Comment by maliming** [comment]
This hierarchical structure references the abp identity module, you can use the endpoint of the identity server to get tokens, etc.

**Comment by dicksonkimeu** [comment]
Does the identity server endpoint have a swagger url ?

Any sample how to pass the token to call API ?

**Comment by maliming** [comment]
> Does the identity server endpoint have a swagger url ?

No.

> Any sample how to pass the token to call API ?

I suggest you check the documentation of Identity Server first.

**Comment by gdlcf88** [comment]
You should read ids4 docs first and try `/connect/token`

**Comment by dicksonkimeu** [comment]
@gdlcf88 @maliming I was able to get token, but could use it because of policy error. How can give the default clientid/ secret access to my API resources ?

![image](https://user-images.githubusercontent.com/4476822/73142465-ff92a600-409f-11ea-93a9-c93292d1c450.png)

**Comment by maliming** [comment]
hi @dicksonkimeu Does the user corresponding to the access token have relevant permissions?
