### ISSUE TITLE
EnablePostSignOutAutoRedirect = true

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2519]
In the identity server, we have to set EnablePostSignOutAutoRedirect = true.

Currently, when we set PostLogoutRedirectUris to an URL, we are not redirected after logged out !

PS: I suppose it is the issue, can you confirm that ?

**Comment by hikalkan** [comment]
Didn't try that. And now I don't know this is something to be done in the ABP framework, or with IDS4 configuration.
We will check. If you have time, you can check the logout source code and understand the problems and offer a solution (and send a PR if possible 😄).

**Comment by vd3d** [comment]
I expect to add some PR one day, but I have to learn and play more with ABP first. Need a few month ;-)

**Comment by Alexbits** [comment]
Hi @hikalkan, @vd3d. I have this problem as well

The ```LogoutController``` in ```Volo.Abp.Account.Web.Areas.Account.Controllers``` has to use ```IIdentityServerInteractionService```  to get ```PostLogoutRedirectUri```

```c#

private readonly IIdentityServerInteractionService _interaction;

public LogoutController(SignInManager<IdentityUser> signInManager, IIdentityServerInteractionService interaction)
{
     _signInManager = signInManager;
     _interaction = interaction;
}

public async Task<IActionResult> Index(string returnUrl = null)
{
   await _signInManager.SignOutAsync();

   if (returnUrl != null)
   {
       return LocalRedirect(returnUrl);
   }
   else
   {
         var logoutId = Request.Query["logoutId"].ToString();

         if (!string.IsNullOrEmpty(logoutId))
         {
             var logoutContext = await _interaction.GetLogoutContextAsync(logoutId);

             var postLogoutUri = logoutContext.PostLogoutRedirectUri;

              if (!string.IsNullOrEmpty(postLogoutUri))
              {
                   return Redirect(postLogoutUri);
               }
           }
     }

   return RedirectToPage("/Account/Login");
}
```

**Comment by hikalkan** [comment]
I moved this to v2.1 to consider to work on.
