### ISSUE TITLE
ConventionalControllerSetting.RootPath can't set to empty

### ISSUE THREAD

**Issue by Rwing** [abpframework/abp#2520]
I just wanna set default url from 'api/app/foo/bar' to 'api/foo/bar', but I found source code as below looks like it's can't set to empty.
https://github.com/abpframework/abp/blob/e81a4bbbef77ef13278f145a69a14a220fecc8f0/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Conventions/AbpServiceConvention.cs#L295

**Comment by maliming** [comment]
According to the current design, you can change it but you cannot remove it.

**Comment by hikalkan** [comment]
It is not allowed because of the modular design. `{rootPath}` is generally used as the module name. If you use `api/foo/bar` and one module defined a `foo` controller then the controllers conflict.

So, this is by design.
