### ISSUE TITLE
Get Current tenant and current user

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2524]
How can I get current tenant and current user ? 

How can I loop through all tenants and all users ?

Can I add a field to the tenants table and how can I add it to UI ?

Can I add a field to the users table and how can I add it to UI ?

**Comment by hikalkan** [comment]
>How can I get current tenant and current user ?

Inject `ICurrentTenant` and `ICurrentUser`.

>How can I loop through all tenants and all users ?

Query from their repositories: `IIdentityUserRepository` and `ITenantRepository`.

>Can I add a field to the tenants table and how can I add it to UI ? Can I add a field to the users table and how can I add it to UI ?

You can add to database. Startup template already configured to add your application-required user properties to the `AppUser` entity. You can do same for the Tenant. However, there is no magic yet to understands your change and dynamically arrange the UI.

**Comment by dicksonkimeu** [comment]
I got this class for users. Where is an equal class for tenants i add fields ?

![image](https://user-images.githubusercontent.com/4476822/71640334-21635d80-2c99-11ea-9169-d23a9419adda.png)

**Comment by maliming** [comment]
> You can add to database. Startup template already configured to add your application-required user properties to the AppUser entity. You can do same for the Tenant. However, there is no magic yet to understands your change and dynamically arrange the UI.

In the tenant module.
https://github.com/abpframework/abp/blob/dev/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/Tenant.cs#L9

https://github.com/abpframework/abp/blob/dev/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/ITenantRepository.cs#L9

**Comment by dicksonkimeu** [comment]
The biggest issue now is how to change/ set current users in a module.

At-least there is .Change Tenant/ but for current user, it's the issue.

**Comment by maliming** [comment]
@dicksonkimeu Related #1082

**Comment by hikalkan** [comment]
see https://github.com/abpframework/abp/issues/1686#issuecomment-570942811
