### ISSUE TITLE
Dynamically Adding Meta Tags

### ISSUE THREAD

**Issue by cotur** [abpframework/abp#2525]
Hi,

Is there any way to set meta tags dynamically from entity for ABP MVC porjects?

Example:
`class A{string x; string y;}`

`<meta property="og:title" content="<A.x>" />`
`<meta property="og:image" content="<A.y>" />`

**Comment by hikalkan** [comment]
Create a ViewComponent and add to the layout hooks like that:

````xml
Configure<AbpLayoutHookOptions>(options =>
{
    options.Add(LayoutHooks.Head.First, typeof(YourViewComponent));
});
````
