### ISSUE TITLE
Handling error on client side

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2527]
Hi,

There is a nice document about throwing an exception with localization and parameters.

https://docs.abp.io/en/abp/latest/Exception-Handling

So, I throw such an exception : 

`throw new BusinessException("App:010046").WithData("UserName", "john");`

The problem is that, I don't know how I'm supposed to convert from this exception to the real message. Will it be on the server side or client side ?

I expected that the exception are catched on the server side, a the message is modified ?

BTW, I got an **AbpRemoteCallException** on the client side, but there is no translation, even in the RemoteServiceErrorInfo

PS: I have try '**app.UseAbpExceptionHandling();**' but it does not work !

**Comment by hikalkan** [comment]
Did you added `App:010046` to your localization JSON file?
If so, ABP automatically handles it with the [AbpExceptionFilter](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs) and [localizes it](https://github.com/abpframework/abp/blob/8d5fb81cfae2a09cc1cf3577b55b5a45ff1b7322/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/ExceptionHandling/DefaultExceptionToErrorInfoConverter.cs#L137-L154).

BTW, are you calling it with the C# dynamic http client proxy system?
