### ISSUE TITLE
The Web layer cannot get a value with the protected property

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2530]
![image](https://user-images.githubusercontent.com/22017199/71660411-eb4fd780-2d85-11ea-85d2-d7a546e5c450.png)
![image](https://user-images.githubusercontent.com/22017199/71660415-f0148b80-2d85-11ea-8566-9619527806c9.png)
![image](https://user-images.githubusercontent.com/22017199/71660422-fa368a00-2d85-11ea-823e-82ab20b41477.png)
![image](https://user-images.githubusercontent.com/22017199/71660452-12a6a480-2d86-11ea-9522-ddf71caa8ef8.png)

The service layer, the interface layer all have data and if you go back to the Web layer you have no data what's the reason?
Although the Type property is protected.

**Comment by maliming** [comment]
Please share some code, it is difficult to see the cause of the problem through the screenshot.

**Comment by 344089386** [comment]
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.IdentityServer.ApiResources;

namespace Volo.Abp.IdentityServer
{
    [Authorize(IdentityServerPermissions.ApiResources.Default)]
    public class ApiResourceAppService : CrudAppService<ApiResource, ApiResourceDto, Guid, PagedAndSortedResultRequestDto,
                        CreateUpdateApiResourceDto, CreateUpdateApiResourceDto>, IApiResourceAppService
    {
        private readonly ApiResourceRepository _repository;

        public ApiResourceAppService(ApiResourceRepository repository)
            : base(repository)
        {
            _repository = repository;
        }

        public override async Task<ApiResourceDto> GetAsync(Guid id)
        {
            var apiResource = await _repository.GetAsync(id);
            return ObjectMapper.Map<ApiResource, ApiResourceDto>(apiResource);
        }

        [Authorize(IdentityServer.IdentityServerPermissions.ApiResources.Create)]
        public override async Task<ApiResourceDto> CreateAsync(CreateUpdateApiResourceDto input)
        {
            var apiResource = await _repository.InsertAsync(
                new ApiResource(GuidGenerator.Create(), 
                    input.Name, 
                    input.DisplayName, 
                    input.Description),
                autoSave: true
                );

            if (input.UserClaims != null)
            {
                foreach (var claim in input.UserClaims.Split(","))
                {
                    if (apiResource.FindClaim(claim) == null)
                    {
                        apiResource.AddUserClaim(claim);
                    }
                }
            }
            if (input.Scopes != null)
            {
                foreach (var scope in input.Scopes.Split(","))
                {
                    if (apiResource.FindScope(scope) == null)
                    {
                        apiResource.AddScope(scope);
                    }
                }
            }
            if (input.Secrets != null)
            {
                foreach (var secret in input.Secrets.Split(","))
                {
                    if (apiResource.FindSecret(secret) == null)
                    {
                        apiResource.AddSecret(secret);
                    }
                }
            }

            await _repository.UpdateAsync(apiResource);

            return ObjectMapper.Map<ApiResource, ApiResourceDto>(apiResource);
        }

        [Authorize(IdentityServerPermissions.ApiResources.Update)]
        public override async Task<ApiResourceDto> UpdateAsync(Guid id, CreateUpdateApiResourceDto input)
        {
            var apiResource = await _repository.GetAsync(id);
            apiResource.DisplayName = input.DisplayName;
            apiResource.Description = input.Description;

            apiResource.RemoveAllUserClaims();
            apiResource.RemoveAllScopes();
            apiResource.RemoveAllSecrets();
            if (input.UserClaims != null)
            {
                foreach (var claim in input.UserClaims.Split(","))
                {
                    if (apiResource.FindClaim(claim) == null)
                    {
                        apiResource.AddUserClaim(claim);
                    }
                }
            }
            if (input.Scopes != null)
            {
                foreach (var scope in input.Scopes.Split(","))
                {
                    if (apiResource.FindScope(scope) == null)
                    {
                        apiResource.AddScope(scope);
                    }
                }
            }
            if (input.Secrets != null)
            {
                foreach (var secret in input.Secrets.Split(","))
                {
                    if (apiResource.FindSecret(secret) == null)
                    {
                        apiResource.AddSecret(secret);
                    }
                }
            }

            await _repository.UpdateAsync(apiResource);

            return ObjectMapper.Map<ApiResource, ApiResourceDto>(apiResource);
        }


        public async Task<ListResultDto<ApiResourceDto>> GetAllListAsync()
        {
            var apiResources = await _repository.GetListAsync();

            var apiResourceList = ObjectMapper.Map<List<ApiResource>, List<ApiResourceDto>>(apiResources);

            return new ListResultDto<ApiResourceDto>(apiResourceList);
        }
    }
}

**Comment by 344089386** [comment]
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;

namespace Volo.Abp.IdentityServer
{
    [RemoteService]
    [Area("identity-server")]
    [Route("api/identity-server/api-resources")]
    public class ApiResourceController : IdentityServerController, IApiResourceAppService
    {
        private readonly IApiResourceAppService _apiResourceAppService;

        public ApiResourceController(IApiResourceAppService apiResourceAppService)
        {
            _apiResourceAppService = apiResourceAppService;
        }

        [HttpPost]
        public async Task<ApiResourceDto> CreateAsync(CreateUpdateApiResourceDto input)
        {
            return await _apiResourceAppService.CreateAsync(input);
        }

        [HttpDelete]
        [Route("{id}")]
        public async Task DeleteAsync(Guid id)
        {
            await _apiResourceAppService.DeleteAsync(id);
        }

        [HttpGet]
        [Route("all")]
        public Task<ListResultDto<ApiResourceDto>> GetAllListAsync()
        {
            return _apiResourceAppService.GetAllListAsync();
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<ApiResourceDto> GetAsync(Guid id)
        {
            return await _apiResourceAppService.GetAsync(id);
        }

        [HttpGet]
        public async Task<PagedResultDto<ApiResourceDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            return await _apiResourceAppService.GetListAsync(input);
        }

        [HttpPut]
        [Route("{id}")]
        public async Task<ApiResourceDto> UpdateAsync(Guid id, CreateUpdateApiResourceDto input)
        {
            return await _apiResourceAppService.UpdateAsync(id, input);
        }
    }
}

**Comment by 344089386** [comment]
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.AspNetCore.Mvc.UI.RazorPages;
using Volo.Abp.Identity;
using Volo.Abp.IdentityServer.ApiResources;
using Newtonsoft.Json;

namespace Volo.Abp.IdentityServer.Web.Pages.IdentityServer.ApiResources
{
    public class EditModel : AbpPageModel
    {
        private readonly IApiResourceAppService _apiResourceAppService;
        private readonly IIdentityClaimTypeAppService _identityClaimTypeAppService;

        [BindProperty]
        public ApiResourceEditViewModel ApiResource { get; set; } = new ApiResourceEditViewModel();

        public ApiResourceDto ApiResourceDto { get; set; }

        public ListResultDto<IdentityClaimTypeDto> NotOwnedClaims { get; set; }

        public EditModel(IApiResourceAppService apiResourceAppService, IIdentityClaimTypeAppService identityClaimTypeAppService)
        {
            _apiResourceAppService = apiResourceAppService;
            _identityClaimTypeAppService = identityClaimTypeAppService;
            NotOwnedClaims = _identityClaimTypeAppService.GetAllListAsync().Result;
        }

        public async Task<ActionResult> OnGetAsync(Guid id)
        {
            var apiResourceDto = await _apiResourceAppService.GetAsync(id);
            ApiResourceDto = apiResourceDto;

            ApiResource = ObjectMapper.Map<ApiResourceDto, ApiResourceEditViewModel>(apiResourceDto);
            ApiResource.UserClaims = string.Join(',', apiResourceDto.UserClaims.Select(t => t.Type));
            ApiResource.Scopes = JsonConvert.SerializeObject(apiResourceDto.Scopes);
            ApiResource.UserClaims = JsonConvert.SerializeObject(apiResourceDto.UserClaims);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var apiResourceDto = ObjectMapper.Map<ApiResourceEditViewModel, CreateUpdateApiResourceDto>(ApiResource);

            await _apiResourceAppService.UpdateAsync(ApiResource.Id, apiResourceDto);

            return NoContent();
        }

        public class ApiResourceEditViewModel
        {
            [HiddenInput]
            [Required]
            public Guid Id { get; set; }

            [Required]
            public string Name { get; set; }

            [Required]
            public string DisplayName { get; set; }

            public string Description { get; set; }

            public bool Enabled { get; set; } = true;

            [HiddenInput]
            public string UserClaims { get; set; }

            [HiddenInput]
            public string Secrets { get; set; }

            [HiddenInput]
            public string Scopes { get; set; }
        }
    }
}

**Comment by 344089386** [comment]
var apiResourceDto = await _apiResourceAppService.GetAsync(id);

I'm having a problem with this line of code.None of the protected properties are available.
@maliming
