### ISSUE TITLE
Document how to switch to CosmosDB for EF Core

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2532]
And also create an integration package like [Volo.Abp.EntityFrameworkCore.MySQL](https://www.nuget.org/packages/Volo.Abp.EntityFrameworkCore.MySQL) if needed.

**Comment by yuriy-yarosh** [comment]
@hikalkan Existing CosmosDB for MongoDB API has certain restrictions and undocumented behaviors, that break certain aggregate queries in an unpredictable manner, so some companies had switched to CosmosDB for NoSQL API and Native CosmosDB driver instead (for EFCore). It worth clarifying if this ticket is for CosmosDB for NoSQL, or CosmosDB for Relational Databases (PostgreSQL + Citus under the hood) ?

Also it worth providing proper backwards compatibility layer between CosmosDB for Mongo and CosmosDB for NoSQL, so all the respective collections and indices are properly created, with all the relevant cascading operations. Probably deserve a new ticket and a bit of prior investigation.
