### ISSUE TITLE
Question : How to customize the Login page

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2533]
Hi,

Is there an easy way to customize all the 'identity server' pages ?

There are custom pages in ABP, they handle the multi-tenant. I wish to handle it another way !
(The tenant should be selected based on the user)

Should I ?
- recreate complete new pages
- look at the identityserver web site to check how I can do
- there is an ABP way of doing this

Thanks

**Comment by hikalkan** [comment]
If you want a major design & code change for a module, I suggest you to get the source code into your solution, remove the nuget package references and customize it based on your requirements.

Module licenses are MIT (we will write this somewhere), so getting the source code has no problem at all.
