### ISSUE TITLE
Contribute : Organization Module

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2534]
Hi,

I need the organization module, it seems it does not exist right now.

If you agree, I wish to start working on it, then once done, share it directly in ABP ?
(With a pull request).

Do you agree ?

**Comment by yinchang0626** [comment]
@vd3d :
I am also doing that,but before `organization module`
I created a [`Tree module`](https://github.com/yinchang0626/FS.Abp.Trees)
In this repository only implement tree structure and most code are from [`aspnetboilerplate`](https://github.com/aspnetboilerplate/aspnetboilerplate) and created by abp vnext way.
I hope it helps you.

**Comment by vd3d** [comment]
Thanks a lot @yinchang0626 ,

I will look at your Tree Module first... but so, maybe I can help you for the 'organization' module ?

Otherwise I will develop my own !

**Comment by vd3d** [comment]
Hi @mehmet-erim,

Do you agree for such contribution, or we do this outside this repo ?

**Comment by hikalkan** [comment]
We thought that as a part of the Identity module (see https://github.com/abpframework/abp/issues/1666) rather than a separate module.
The implementation will be similar to [the ASP.NET Boilerplate's OU system](https://aspnetboilerplate.com/Pages/Documents/Zero/Organization-Units).

If you want to implement this, it is appreciated :) If you will implement also the UI part, please implement both for Angular & Razor Pages.

Thanks.

**Comment by mperk** [comment]
Hi @vd3d
I am working on the organization unit in identity module. I'm very close to finish. You can see my last commits: https://github.com/mperk/abp/tree/%231666-organization-units

**Comment by hikalkan** [comment]
Great @mperk :)

**Comment by leonkosak** [comment]
@hikalkan do you consider using HierarchyId instead of Code (string)?

**Comment by maliming** [comment]
@leonkosak 

> OU code is automatically generated and maintained by the OrganizationUnit Manager. It's a string that looks something like this:

```
"00001.00042.00005"
```

> This code can be used to easily query the database for all the children of an OU (recursively). There are some rules for this code:

**Comment by hikalkan** [comment]
> do you consider using HierarchyId

What is HierarchyId? It already has ParentId.

**Comment by leonkosak** [comment]
https://github.com/abpframework/abp/issues/1666#issuecomment-523351050
If you using HierarchyId, you get (optimized) methods so that you don't have to write your own.

**Comment by hikalkan** [comment]
I didn't know it. We should check. But "Organization Code" is simpler and don't rely on the DBMS features. We may add both, this is also an option.

**Comment by leonkosak** [comment]
https://dba.stackexchange.com/questions/17302/anybody-using-hierarchyid-in-production-is-it-reliable

https://softwarehut.com/blog/tech/hierarchyid-entity-framework/

It should work for non-MSSQL databases as far as I understand.
It's more optimized compared to strings if larger hierarchies are created.

**Comment by carloszan** [comment]
when @mperk finishes OU, will it be included in abp 3.0? is there a prediction?

**Comment by carloszan** [comment]
will this feature be included in some milestone?

**Comment by SmallShrimp** [comment]
api: https://gitee.com/xugege/KST.ABP.git folder organizations
ng: @hedou/abp-ng.organizations

**Comment by hikalkan** [comment]
@carloszan did you see https://github.com/abpframework/abp/pull/2563 (in 2.1 milestone).
