### ISSUE TITLE
StringLocalizer issue

### ISSUE THREAD

**Issue by chai93323** [abpframework/abp#2535]
Sometime the system will throw exception when system load StringLocalizer. Exception show as below:
InvalidOperationException: Collection was modified; enumeration operation may not execute.

DependencyResolutionException: An exception was thrown while activating Microsoft.Extensions.Localization.StringLocalizer.....

Exception throw from:
var l = context.ServiceProvider.GetRequiredService<IStringLocalizer<IdentityResource>>();

This issue mostly happen when first load the StringLocalizer to system, after refresh browser then work fine.

**Comment by maliming** [comment]
Please provide complete steps to reproduce the problem. Thanks
