### ISSUE TITLE
Abp v1.1.2 Mvc fail to login

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2536]
Steps to reproduce:
1. Create a new solution by cli command `abp new MyProject`.
2. Execute migration and run the `MyProject.Web` project.
3. Try to login as admin with wrong password "123456", it throws wrong password error.
4. Try to login as admin with correct password "1q2w3E*", **it returns to home page and keep not logged in.**

**Comment by 344089386** [comment]
I have a similar question.
I am the architecture of microservices.
After launching the program, the application will automatically jump to the login page of the AuthServer. After clicking the login page, the application link cannot be returned directly.
You need to access the application site in the browser and then jump to AuthServer login to jump back to the application properly.

**Comment by yekalkan** [comment]
@gdlcf88 I couldn't reproduce.

Can you delete browser cookies and try again?

**Comment by gdlcf88** [comment]
Delete all browser's caches, cannot fix.

My Chrome version is 63.0.3239.132.

Try to use a new Chrome version 78.0.3904.108, cannot reproduce this problem any more.

Is it a compatibility problem? @yekalkan

**Comment by yekalkan** [comment]
I reproduced on chrome v63.0.3239.132.

**Comment by gdlcf88** [comment]
The latest version of Chinese web users' popular browser is based on chrome v63.0.3239.132.

**Comment by maliming** [comment]
Please check the **cookie** request and response in chrome's network panel.

![image](https://user-images.githubusercontent.com/6908465/71714104-6d540500-2e47-11ea-89ae-335d7282a3a4.png)

![image](https://user-images.githubusercontent.com/6908465/71714111-77760380-2e47-11ea-9fd8-4da2e7fada64.png)

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/71714167-b441fa80-2e47-11ea-8fd8-4eb830493047.png)
![image](https://user-images.githubusercontent.com/30018771/71714173-bad07200-2e47-11ea-9d11-1255380c329a.png)
After login, it returned to home page with no identity, and I captured these screenshots.

**Comment by maliming** [comment]
Try the identity templates provided by net core.

```
dotnet new mvc -au Individual -o Test
```

**Comment by gdlcf88** [comment]
> Try the identity templates provided by net core.
> 
> ```
> dotnet new mvc -au Individual -o Test
> ```

This template can login correctly.

**Comment by maliming** [comment]
I don't know why this happens in chrome, but it should have nothing to do with abp.

![image](https://user-images.githubusercontent.com/6908465/71718796-50273280-2e57-11ea-8739-75de9e4d46f5.png)

**Comment by wjkhappy14** [comment]
app.UseAuthentication();
 app.UseJwtTokenMiddleware();

**Comment by maliming** [comment]
hi all

This problem exists in old browsers (chrome, Safari etc), please refer to the extension method of identity server to solve it.

https://github.com/IdentityServer/IdentityServer4/pull/3940
