### ISSUE TITLE
Send IServiceProvider to DoWork method of the periodic background worker

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2539]
* Added `IServiceScopeFactory` to the `PeriodicBackgroundWorkerBase` constructor.
* Added `PeriodicBackgroundWorkerContext` to the `DoWork` method.

**Comment by dicksonkimeu** [comment]
@hikalkan 

Any sample code on how to use this, before 2.o my code was working, but now it's not.

Added IServiceScopeFactory to the PeriodicBackgroundWorkerBase constructor.
Added PeriodicBackgroundWorkerContext to the DoWork method.

**Comment by dicksonkimeu** [comment]
@hikalkan How should i use the workerContext and the scope factory ?

Below is my code

```
public class BankingSwitchSync : PeriodicBackgroundWorkerBase, ISingletonDependency
    {
        private readonly IBackgroundJobManager _backgroundJobManager;
        private readonly ICurrentUser _currentUser;
        private readonly ICurrentTenant _currentTenant;
        public BankingSwitchSync(AbpTimer timer, IServiceScopeFactory serviceScopeFactory, IBackgroundJobManager backgroundJobManager,
             ICurrentTenant currentTenant, ICurrentUser currentUser
            )
            : base(timer,serviceScopeFactory)
        {
            _backgroundJobManager = backgroundJobManager;
            _currentTenant = currentTenant;
            _currentUser = currentUser;
            timer.Period = 6000;
        }
        protected override void DoWork(PeriodicBackgroundWorkerContext workerContext)
        {
            this.Logger.LogDebug("Banking Switch Sync => Do Work..");
            string user = "";
            string tenant = "";
            user = _currentUser.UserName;
            tenant = _currentTenant.Name;
            string settings1 = "";
        }
    }
```

**Comment by acjh** [comment]
@dicksonkimeu Sample code on how to use `workerContext`:

https://github.com/abpframework/abp/blob/401376e10951fc5a33d9111a5d9b1c20ee63e51e/framework/src/Volo.Abp.BackgroundJobs/Volo/Abp/BackgroundJobs/BackgroundJobWorker.cs#L35

You should not need to use `IServiceScopeFactory` directly.
