### ISSUE TITLE
how to get the value configured in  appsetting.json via the IsettingManager/SettingProvider

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#2544]
as shown below,  i need to get the value AuthServer:Authority in the application service layer;

 
![image](https://user-images.githubusercontent.com/2950822/71722184-fdec0e80-2e62-11ea-9905-061eb7edcc2c.png)

but i can't find any api to fetch its value, please help me, sincerely thanks

**Comment by hikalkan** [comment]
Inject & use the `IConfiguration` service (like `var value = _configuration["App:SelfUrl"];`).

**Comment by hikalkan** [comment]
This is not related to the setting system (while it uses the `IConfiguration` as a provider - but needs to explicitly define settings before. see the doc: https://docs.abp.io/en/abp/latest/Settings)

**Comment by johnnba** [comment]
@hikalkan  thanks, with the injection of  IConfiguration  service,  i can get the configuration value.
but if there is some other way  to get the key-value settings defined in the configuration with the injection of  `ISettingManager` , i see that the setting usage will be more flexible. 

> As mentioned in the previous section, ConfigurationSettingValueProvider reads the settings from the IConfiguration service, which can read values from the appsettings.json by default. So, the easiest way to configure setting values to define them in the appsettings.json file.
> 
> For example, you can configure IEmailSender settings as shown below:

```
{
  "Settings": {
    "Abp.Mailing.DefaultFromAddress": "noreply@mydomain.com",
    "Abp.Mailing.DefaultFromDisplayName": "My Application",
    "Abp.Mailing.Smtp.Host": "mail.mydomain.com",
    "Abp.Mailing.Smtp.Port": "547",
    "Abp.Mailing.Smtp.UserName": "myusername",
    "Abp.Mailing.Smtp.Password": "mySecretPassW00rd",
    "Abp.Mailing.Smtp.EnableSsl": "True"
  }
}

```
sorry to ask the question, i can get the configured value via the `ISettingProvider ` service  inject, but the abpmailkit still send the email with the default configuration, is there something i've missed?
