### ISSUE TITLE
Use Razor UI Libraries instead of embedded view system if possible!

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#255]
When v2.1 final is released!

See https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries/

**Comment by hikalkan** [comment]
It's not possible and needed since ABP's Virtual File System does much more. However, we can try it with a sample to see if it has any compatibility problem.

**Comment by liangshiw** [comment]
Related: https://github.com/abpframework/abp/issues/3740

**Comment by hikalkan** [comment]
I am closing this since VFS is much more powerful.
