### ISSUE TITLE
How to extend existing module in abp like Account Module?

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2551]
Hi,
I want to extend existing abp modules like account module, I want to change in `AccountAppService`

**Comment by maliming** [comment]
I think you can use DI to replace its interface.

https://docs.abp.io/en/abp/latest/Dependency-Injection

**Comment by mehdihadeli** [comment]
@maliming replacing my implementation with already exist abp service with `ReplaceServices` feature?

**Comment by hikalkan** [comment]
`context.Services.Replace(...)` inside the Configure of your module. ABP Framework (this one) uses Microsoft's DI infrastructure, you can find info on the web.

**Comment by maliming** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1
