### ISSUE TITLE
Problem: The view '~/Pages/Error/Default.cshtml' was not found

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2552]
Steps to reproduce:
1. Create a new solution by cli command: `abp new MyProject -v 1.1.2`.
2. Set `ASPNETCORE_ENVIRONMENT=Production` in  `launchSettings.json`.
3. Change `context.Services.AddAuthentication()` to `context.Services.AddAuthentication("Bearer")`.
4. Create MyTestAppService:
```
    public class MyTestAppService : MyProjectAppService
    {
        public MyTestAppService()
        {
            
        }

        [Authorize]
        public async Task TestAsync()
        {
            
        }
    }
```
5. Execute migration and run the Web project.
6. Run `/api/app/myTest/test`, it throw a 500 error.
7. You can get a log:
```
[ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The view '~/Pages/Error/Default.cshtml' was not found. The following locations were searched:
~/Pages/Error/Default.cshtml
......
```

@yekalkan @maliming

**Comment by gdlcf88** [comment]
It throws 401 error in `Development` env, but it try to redirect to error page in `Production` env.

I have set:
```
            context.Services.AddAuthentication(options =>
                {
                    options.DefaultScheme = IdentityConstants.ApplicationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.RequireHttpsMetadata = false;
                    options.ApiName = "MyProject";
                });
```
The redirection is not expected.

PS: Only my custom appservice methods can reproduce this problem, apis in abp official modules throw 401 error correctly.

**Comment by gdlcf88** [comment]
The 500 error problem is caused by this commit: https://github.com/abpframework/abp/commit/297706a6d54f4958df574e817b24e82422a4ba1f#diff-0f222f914475925996164439e0490aa8

**Comment by johnnba** [comment]
@gdlcf88  you can refference my solution that i solved the same problem with you.

https://github.com/abpframework/abp/issues/2396

**Comment by gdlcf88** [comment]
Thanks @johnnba . The 500 error problem will be fix after abp change default error page path. But now I remove `app.UseErrorPage()` because of another problem: https://github.com/abpframework/abp/issues/2552#issuecomment-570778296

**Comment by gdlcf88** [comment]
https://github.com/abpframework/abp/issues/2552#issuecomment-570778296
Does anyone know why it doesn't responses 401 but 302 in production env? 😢
