### ISSUE TITLE
Best Practice For Identity Management in abp

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2554]
Hi,
What is the best practice for identity server in abp? is it ok, I put all identity management and permission management and user auth identity server?

**Comment by gdlcf88** [comment]
I'm not quite sure what the question is. `Identity` and `Identity Server` are different. What is your focus? And what do you want?

**Comment by mehdihadeli** [comment]
I have some monolithic apps, I want to create an Identity Server using .net core Identity management in this auth server for using in my monolithic apps.
we need admin users in each application could manage permission in its own application and they couldn't see other application permission but in identity server, they can see other application permission in Identity server UI, so it is not secure and user-friendly. is it ok I design separate UI for each monolithic app for permission management plus there are all permission in identity server that only super admin user can see all permissions?

**Comment by hikalkan** [comment]
You can implement all the scenerious you've written. However, all of them are custom solution structures and you need to implement it yourself by understanding the IDS4 and the permission system. If you have specific question on your implementation, we try to help. But we can not design solutions for everyone's custom requirements you know :)
