### ISSUE TITLE
IdentityServer, create my own Blazor Login / Registration pages...

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2555]
Hi,

I wish to customize the IdentityServer and use custom pages for login / registration / lost password / etc... ( FYI, I use Blazor, but it should be the same ! ).

Notice it is a critical feature, any web site should have its own design & features.

**_Example_**
By example, for now, I use the following code:

`Challenge(authProps, "oidc");`

But it redirects to a pre-defined login page, how can I change this?

**_Information_**
I have searched for some information, I have seen that some peoples use the following

`.UserInteraction.LoginUrl = "http://..../MyLoginPage";`

I'm not sure it is possible, because the AddIdentityServer is hardcoded somewhere and I have no access to it (AbpIdentityServerDomainModule.cs) !

**Comment by Alexbits** [comment]
Check this #2289
