### ISSUE TITLE
Cant access new app if multi tenancy is enabled

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#2557]
abp new TestApp latest version issue

Have to turn off multi tenancy if i want to start using new app template.

![Screenshot_13](https://user-images.githubusercontent.com/1131514/71780426-da43d800-2fca-11ea-8864-cfd0362fc8a5.png)

Is this done by purpose so user would be aware of multi tenancy option or is this a bug?

How to make this work? Write sql script insert tenant record with id into database?

Thanks

**Comment by maliming** [comment]
Your browser may have the wrong `__tenant` cookie. You can try clearing the cookie, or try Chrome's incognito mode.

**Comment by mkmita** [comment]
@maliming I will try this today, thank you!
