### ISSUE TITLE
Generic repository dependency injection not working in module

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#2562]
Latest version 1.1.2

I created app service in the newly generated module, injected generic repository into application service constructor.

Added this module to the newly generated application solution (1.1.2)

I got a dependency injection issue when I tried using application service to load grid data.

I got this solved when I started using IRepository<TEntity, Guid> implementation.

Documentation is telling me that I can inject IRepository<TEntity, Guid> straight to application service.

Maybe there are common mistakes what developers do during this or this is a bug?

**Comment by maliming** [comment]
What are the steps to reproduce the problem?

**Comment by hikalkan** [comment]
>I got this solved when I started using IRepository<TEntity, Guid> implementation.

Didn't understand it.

Did you call `options.AddDefaultRepositories()` (https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-default-repositories) in your module?

**Comment by mkmita** [comment]
> > I got this solved when I started using IRepository<TEntity, Guid> implementation.
> 
> Didn't understand it.
> 
> Did you call `options.AddDefaultRepositories()` (https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-default-repositories) in your module?

I created IBookRepository: IRepository<Book, Guid>  interface Created BookRepository class which implemented IBookRepository

In the module, app service injected IBookRepository instead of IRepository<Book, Guid> and injection started working.

I didn't change any dependency configuration

**Comment by maliming** [comment]
Is your `Book` class an entity or an aggregate root?  https://docs.abp.io/en/abp/latest/Entities

**Comment by mkmita** [comment]
> Is your `Book` class an entity or an aggregate root? https://docs.abp.io/en/abp/latest/Entities

Its AggregateRoot<Guid>

**Comment by maliming** [comment]
What are the steps to reproduce the problem?

**Comment by mkmita** [comment]
Can try to investigate this further if still can't reproduce.

1. Generate module 1.1.2
2. Create AgregateRoot entity in module
3. Create app service in module
4. Inject generic repository IRepository<Entity, Guid> in module app service
5 Create API controller in module
6. Use module app service in controller
7. Generate a new solution
8. Add module to newly generated solution
9. Try to use rest api from the added module with generic repository inject

**Comment by maliming** [comment]
hi @mkmita 

> Generate a new solution & Add module to newly generated solution

These steps are vague and it is most likely the problem.
Can you share a problem project?

**Comment by mkmita** [comment]
@maliming i can try create one when i have time.
