### ISSUE TITLE
Abp ef core with sql server stored proc

### ISSUE THREAD

**Issue by kurtwilbies** [abpframework/abp#2565]
I tried several ideas (fromsql, ..), but I cant get stored proc working in (ef core) Abp framework. Why? Is this by design. Do you or somebody have working code?

**Comment by maliming** [comment]
You should use EF Core's API in the repository, does it not work?  I think you should check the documentation of EF Core.

**Comment by thiagocoppi** [comment]
@kurtwilbies  Dapper is most easy to consume SP (stored procedures), you tested with it?
