### ISSUE TITLE
Unknown Razor section problem

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2567]
![image](https://user-images.githubusercontent.com/30018771/71827830-0a2ed080-30dc-11ea-8f90-44012b0323f1.png)

Pages in startup template have this error. Is there any way to solve this problem without ide configuration?

**Comment by hikalkan** [comment]
There is no way to solve this issue as I know. It works, but the IDE can not recognize it, because VS assumes to find the RenderSection inside the same project but it is defined in the framework (nuget package).

**Comment by gdlcf88** [comment]
It may relate to https://github.com/abpframework/abp/issues/4175
