### ISSUE TITLE
User menu in Module.Web.Host not working

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#2568]
Steps to reproduce:

1. Create an ABP module solution: `abp new MyModule -t module -v 1.1.2`
1. Run `dotnet ef database update` in "host\MyModule.IdentityServer" folder
1. Launch following projects respectively:

    1. MyModule.IdentityServer
    1. MyModule.HttpApi.Host
    1. MyModule.Web.Host
1. Login "Web.Host" by using "admin / 1q2w3E*"
1. Click the user menu, but no dropdown menu appeared.

![image](https://user-images.githubusercontent.com/3471718/71865313-565e2d00-313d-11ea-9da5-0a5a6fd6917b.png)

I found the issue: #1677, so I added the "DependsOn" :

``` csharp
    ...
    [DependsOn(typeof(AbpAccountWebModule))]
    public class MyModuleWebHostModule : AbpModule
    ...
```

After clear cookies and relogin, this time even the user name disappeared:

![image](https://user-images.githubusercontent.com/3471718/71865670-7b06d480-313e-11ea-8a0c-ffafa14ee99f.png)

It seems that login failed.

**Comment by maliming** [comment]
This pr will solve your problem https://github.com/abpframework/abp/pull/1719

**Comment by wakuflair** [comment]
@maliming  It's merged already, but Is it not publised yet?

**Comment by maliming** [comment]
I mistaken the milestone as 2.0, it is actually 0.20.
![image](https://user-images.githubusercontent.com/6908465/71866208-6a575e00-3140-11ea-91cf-2755a744ff2f.png)


I will check it.

**Comment by maliming** [comment]
Try set **DefaultSignInScheme** to **Cookies**.

https://github.com/abpframework/abp/blob/4c1e4a323d24493e4e90f9410662d2c01e7cabc9/templates/module/aspnet-core/host/MyCompanyName.MyProjectName.Web.Host/MyProjectNameWebHostModule.cs#L116-L119

```
options.DefaultSignInScheme = "Cookies";
```

However, there are still problems **log out** of the current user.

**Comment by wakuflair** [comment]
> Try set **DefaultSignInScheme** to **Cookies**.

The dropdown menu appeared.

> However, there are still problems **log out** of the current user.

**user profile** has problem too.

**Comment by maliming** [comment]
`AbpAccountWebModule` is a bit special.

The login and register pages for `AbpAccountWebModule`  use the settings provided by `AbpAccountApplicationModule`. (`IsSelfRegistrationEnabled`, `EnableLocalLogin`).

It also depends on `AbpIdentityAspNetCoreModule` => `AbpIdentityDomainModule`.

The `Web.Host` project in the module template should not depend on these modules.

@hikalkan What do you think?
