### ISSUE TITLE
Undefined setting: Abp.Account.EnableLocalLogin

### ISSUE THREAD

**Issue by derily** [abpframework/abp#2572]
`AbpException: Undefined setting: Abp.Account.EnableLocalLogin
Volo.Abp.Settings.SettingDefinitionManager.Get(string name) in SettingDefinitionManager.cs, line 40`

appsettings.json
`  {
 "Settings": {
    "Abp.Account.EnableLocalLogin":"True"
  }
}`

**Comment by maliming** [comment]
Your module need depend on `AbpAccountApplicationModule `, it provides`EnableLocalLogin ` setting.
eg: https://github.com/abpframework/abp/pull/2571

`appsettings.json` is used to read the setting values.


https://docs.abp.io/en/abp/latest/Settings
https://docs.abp.io/en/abp/latest/Modules/Setting-Management

**Comment by derily** [comment]
> Your module need depend on `AbpAccountApplicationModule `, it provides`EnableLocalLogin ` setting.
> eg: #2571
> 
> `appsettings.json` is used to read the setting values.
> 
> https://docs.abp.io/en/abp/latest/Settings
> https://docs.abp.io/en/abp/latest/Modules/Setting-Management

thanks,i'am newer of abp,i think i need know more about abp.Meanwhile,hope abp more and more friendly to newbie
