### ISSUE TITLE
Volo.Abp.Configuration

### ISSUE THREAD

**Issue by gxlqssjf** [abpframework/abp#2575]
包从0.22.0升级包到1.1.2就没有了,请问在哪个包里?

**Comment by maliming** [comment]
There is no package named `Volo.Abp.Configuration`.
What is the problem you encountered?

![image](https://user-images.githubusercontent.com/6908465/71890662-c2618500-317f-11ea-8179-bb82f1ffe454.png)

**Comment by gxlqssjf** [comment]
准确不应该是包,这个命名空间应该在volo.abp.core里
![图片](https://user-images.githubusercontent.com/1277598/71892186-51bc6780-3183-11ea-8316-e93f2c95c114.png),升级包之后找不到导致
![图片](https://user-images.githubusercontent.com/1277598/71892264-80d2d900-3183-11ea-9eec-b29ba961afd8.png)

**Comment by maliming** [comment]
**Remove IConfigurationAccessor. Use IConfiguration instead.** 
https://github.com/abpframework/abp/issues/1094

**Comment by gxlqssjf** [comment]
还有就是你们的源码git不下来,下载不了
![图片](https://user-images.githubusercontent.com/1277598/71892316-9942f380-3183-11ea-9681-7562ed6618d2.png)
![图片](https://user-images.githubusercontent.com/1277598/71892487-f474e600-3183-11ea-8bc8-391e62b1a02b.png)
![图片](https://user-images.githubusercontent.com/1277598/71894420-32c0d400-3189-11ea-8440-fb6d014f2b60.png)

**Comment by gxlqssjf** [comment]
那
![图片](https://user-images.githubusercontent.com/1277598/71895244-774d6f00-318b-11ea-94ae-844fbdcc2092.png)这种现在应该怎么用?

![图片](https://user-images.githubusercontent.com/1277598/71895256-846a5e00-318b-11ea-9ba9-523125fe1c1f.png)
public static IServiceCollection AddSingleton<TService>(this IServiceCollection services, TService implementationInstance) where TService : class;

改成什么样了?

**Comment by maliming** [comment]
this has nothing to do with abp，it is related github.；)

**Comment by gxlqssjf** [comment]
那
图片这种现在应该怎么用?

图片
public static IServiceCollection AddSingleton(this IServiceCollection services, TService implementationInstance) where TService : class;

改成什么样了?

> 
> 
> this has nothing to do with abp，it is related github.；)
https://github.com/abpframework/abp/issues/2575#issuecomment-571566044
那
图片这种现在应该怎么用?

图片
public static IServiceCollection AddSingleton(this IServiceCollection services, TService implementationInstance) where TService : class;

改成什么样了?

**Comment by gxlqssjf** [comment]
谢谢,应该发这一段给我
using System;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Volo.Abp.Configuration;

namespace Microsoft.Extensions.DependencyInjection
{
    public static class ServiceCollectionConfigurationExtensions
    {
        [Obsolete]
        public static IServiceCollection SetConfiguration(this IServiceCollection services, IConfigurationRoot configurationRoot)
        public static IServiceCollection ReplaceConfiguration(this IServiceCollection services, IConfiguration configuration)
        {
            return services.Replace(ServiceDescriptor.Singleton<IConfigurationAccessor>(new DefaultConfigurationAccessor(configurationRoot)));
            return services.Replace(ServiceDescriptor.Singleton<IConfiguration>(configuration));
        }

        public static IConfigurationRoot GetConfiguration(this IServiceCollection services)
        public static IConfiguration GetConfiguration(this IServiceCollection services)
        {
            var hostBuilderContext = services.GetSingletonInstanceOrNull<HostBuilderContext>();
            if (hostBuilderContext?.Configuration != null)
            {
                return hostBuilderContext.Configuration as IConfigurationRoot;
            }

            return services.GetSingletonInstance<IConfigurationAccessor>().Configuration;
            return services.GetSingletonInstance<IConfiguration>();
        }
    }
}
