### ISSUE TITLE
Circular dependency detected in angular core module

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2576]
Hi,
I copy abp core module folder in my angular project because I want to customize that, but I got this warring in my project
https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages/core/src/lib

```
WARNING in Circular dependency detected:
src\app\core\services\application-configuration.service.ts -> src\app\core\services\rest.service.ts -> src\app\core\states\config.state.ts -> src\app\core\services\application-configuration.service.ts

WARNING in Circular dependency detected:
src\app\core\services\localization.service.ts -> src\app\core\states\config.state.ts -> src\app\core\states\session.state.ts -> src\app\core\services\localization.service.ts

WARNING in Circular dependency detected:
src\app\core\services\rest.service.ts -> src\app\core\states\config.state.ts -> src\app\core\services\application-configuration.service.ts -> src\app\core\services\rest.service.ts

WARNING in Circular dependency detected:
src\app\core\states\config.state.ts -> src\app\core\services\application-configuration.service.ts -> src\app\core\services\rest.service.ts -> src\app\core\states\config.state.ts

WARNING in Circular dependency detected:
src\app\core\states\session.state.ts -> src\app\core\services\localization.service.ts -> src\app\core\states\config.state.ts -> src\app\core\states\session.state.ts
```

**Comment by hikalkan** [comment]
I am not sure but it may be because other modules still use the npm package.
BTW, check the [licensing ](https://github.com/abpframework/abp/blob/dev/LICENSE) if you want to copy a framework code into your private solution.

**Comment by mehdihadeli** [comment]
@hikalkan ok sure , I had to do that because customizing angular modules was hard

**Comment by mehmet-erim** [comment]
These packages are used after the compilation. These warnings do not occur after the compilation.

>I had to do that because customizing angular modules was hard

You can customize the Angular UI components easily. See #2522.
This feature will be available with v2.

**Comment by mehdihadeli** [comment]
@mehmet-erim Thanks, it just to replace our component with abp components? what about customizing the existing one and add a new feature to them?

**Comment by olicooper** [comment]
I have a custom angular project too but I didn't copy the core module code, instead you probably need to add `"@abp/ng.core": "2.0.0"` in your `package.json` and reference it in your app module to use it.

**Comment by mehdihadeli** [comment]
> I have a custom angular project too but I didn't copy the core module code, instead you probably need to add `"@abp/ng.core": "2.0.0"` in your `package.json` and reference it in your app module to use it.

@olicooper Me too, I removed my copy apb core folder, and I imported abp core module package in my project after @mehmet-erim answer but my question now is about customizing existing abp components not replacing them with my component, is it possible or we have to completly replace our component with existing one?

**Comment by olicooper** [comment]
I wrote my own code instead of using abp. If you look at their modules you can design your code in a similar way. The `abp/ng.core` module contains the stuff to login and logout as well as some code for angular routes and also reading settings and application-configution. I used ngxs stores and creates services to make the API calls. You can use the `Rest.Request` and `RestService` in the core module to make API requests.
You should spend some time looking at the abp source code because it helped me a lot.

**Comment by yinchang0626** [comment]
@olicooper 
> You should spend some time looking at the abp source code because it helped me a lot.

So am i,maybe trace all abp code and self code in Chrome Debugger is more 
easier know how it work,
So I created a [Repository ](https://github.com/yinchang0626/abp.ng)to do that , i just ref npm/ng-packs/packages/ as 
a submodule by git .not for modify abp code,but let me know how to use it,
In that Repository,I did my customized theme by `dynamic-layout.component` and   `replaceable-components.state` let those code align to abp style..(thanks @mehmet-erim  ),and more, It can extend  any abp packages in other library without modify abp code(that will be easy to update abp code by git),hope it help you.

**Comment by mehmet-erim** [comment]
> > I have a custom angular project too but I didn't copy the core module code, instead you probably need to add `"@abp/ng.core": "2.0.0"` in your `package.json` and reference it in your app module to use it.
> 
> @olicooper Me too, I removed my copy apb core folder, and I imported abp core module package in my project after @mehmet-erim answer but my question now is about customizing existing abp components not replacing them with my component, is it possible or we have to completly replace our component with existing one?

@mehdihadeli, If you want to customize a component, you must replace it. Because some of the components are so complex. Customizing the certain parts may break the application.

**Comment by mehdihadeli** [comment]
@mehmet-erim  ok thanks.
