### ISSUE TITLE
Consider to use Fody ConfigureAwait library instead of manual ConfigureAwait calls.

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2577]
For v2.0, we've merged https://github.com/abpframework/abp/pull/2500 to not introduce a new dependency to the build pipeline.
However, we know that it brings additional complexity to the development. We will consider to use the Fody ConfigureAwait library to automate it.

**Comment by gdlcf88** [comment]
Does it mean that `ConfigureAwait(false)` is automatically added to my codes too?

**Comment by hikalkan** [comment]
No, Fody works when we compile the ABP framework. It doesn't effect your application. If you want, you can also use it.

**Comment by hikalkan** [comment]
Done with https://github.com/abpframework/abp/pull/2645
