### ISSUE TITLE
Serilog.Extensions.Hosting

### ISSUE THREAD

**Issue by Gosha24** [abpframework/abp#2583]
Hello . In your framework you are using package Serilog.Extensions.Hosting., while in Serilog.Extensions.Hosting documentation it is written: ASP.NET Core applications should consider using Serilog.AspNetCore instead, which bundles this package and includes other ASP.NET Core-specific features.
Can you comment on this?

**Comment by maliming** [comment]
It looks like we need to replace it with `Serilog.AspNetCore`.

**Comment by johnnba** [comment]
![image](https://user-images.githubusercontent.com/2950822/72130611-08ebf500-33b5-11ea-8481-df11cb1acb9d.png)
@Gosha24 @maliming 
actually, if we want to show all logs on console, we should referrence the `Serilog.Aspnetcore` currently . then  we can add the console logger configuration. so it's a good suggestion.

 ```
  Log.Logger = new LoggerConfiguration()
#if DEBUG
                .MinimumLevel.Debug()
#else
                .MinimumLevel.Information()
#endif
                .MinimumLevel.Override("Microsoft", LogEventLevel.Debug)
                .Enrich.FromLogContext()
                .WriteTo.Async(c => c.File("Logs/logs.txt"))
                .WriteTo.Console()
                .CreateLogger();
```

**Comment by maliming** [comment]
Fixed by https://github.com/abpframework/abp/pull/2597
