### ISSUE TITLE
Windows authentication not working

### ISSUE THREAD

**Issue by obassullu** [abpframework/abp#2584]
I can't login when i tried windows authentication in template project.  I can see windows button as below . I didn't receive any warning when I click this button . I have seen "Authorization failed." in log file . I have added log file of identity server project . 

![winauth](https://user-images.githubusercontent.com/1825965/71975852-0eff9b80-3226-11ea-8c61-8f9fceef1477.PNG)

[logs.txt](https://github.com/abpframework/abp/files/4035134/logs.txt)

**Comment by maliming** [comment]
hi @obassullu Can you share the steps to reproduce the problem?

**Comment by obassullu** [comment]
Hi @maliming it's my mistake. now I can login.
thanks

**Comment by aelhadi** [comment]
Hi,

@obassullu can you please share the solution? i'm stack with this too....

Best Regards
