### ISSUE TITLE
Password max length limit on Angular application

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2590]
Is this because of a design restriction such as the hard limit of 256 characters in the database _PasswordHash_ field?

Could we remove the limit or increase it maybe?

https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/identity/src/lib/components/users/users.component.ts#L147

**Comment by hikalkan** [comment]
32 chars should be enough normally, what do you offer :)

**Comment by olicooper** [comment]
We had a client try to use a longer password the other day and they said they had used a password generator. I'd personally not have a limit if there is no technical reason for it as this makes the app feel less secure for some people?
I think NIST say you should allow at least 64 characters as a minimum so I guess at least this?

**Comment by olicooper** [comment]
I have noticed the [IdentityUserConsts.MaxPasswordLength](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/IdentityUserConsts.cs#L21) property also has this limit and given that it is hard-coded in the framework, I think the limit should be 128 characters because this satisfies the [NIST requirements](https://pages.nist.gov/800-63-3/sp800-63b.html#-5112-memorized-secret-verifiers) whilst also giving some overhead.

Lower soft limits could be placed using global or tenant settings if required.

**Comment by hikalkan** [comment]
OK, we will allow to 128 chars length.

**Comment by hikalkan** [comment]
@yekalkan can you make it 128, implement in UIs too and re-generate the initial migration for the startup templates.
