### ISSUE TITLE
Can't seed permissions due to project dependencies/structure

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2591]
I have created a `MultiTenancyDataSeedContributor : IDataSeedContributor` and I want to be able to create another role in the system with a pre-defined set of permissions whenever a new tenant is created.

I need access to the [MyProjectNamePermissions](https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Application.Contracts/Permissions/MyProjectNamePermissions.cs) and [IdentityPermissions](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/IdentityPermissions.cs) but these are contained in `Application.Contracts` and the various _SeedContributors_ such as [IdentityDataSeedContributor](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeedContributor.cs) should reside within the `Domain` project (and this can't depend on the Application because of breaking DDD principles etc).

I am aware of the [PermissionDefinitionManager](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionDataSeedContributor.cs#L30) but this just fetches all permissions and I need a select few.

Whats the solution to this? Currently I have to find the permission names and include magic strings in my code to seed the permissions I need.

**Comment by maliming** [comment]
I think since your service(`MultiTenancyDataSeedContributor`) is related to permissions, then you can put it in the application service layer.
`IDataSeedContributor `can be implemented in any layered module.

But there may be other better solutions.

**Comment by mahdighorbanpour** [comment]
I have exactly the same problem, I have implemented the seed contributor in the Application layer, however, it seems DbMigrator will not detect the contributors in this layer. I even added the project reference to the Application project (for the DbMigrator) but didn't help. 
The intention is simple, seed a set of defined permissions for a specific role(s). What do you suggest?

**Comment by mahdighorbanpour** [comment]
Found it: 
Adding the dependency to the application module will result in detecting the seed contributor in the application layer. You need to change the DbMigratorModule and update it like below:
```csharp
[DependsOn(
        typeof(AbpAutofacModule),
        typeof(XXXEntityFrameworkCoreModule),
        typeof(XXXApplicationContractsModule),
        typeof(XXXApplicationModule) // add this line here
        )]
    public class XXXDbMigratorModule : AbpModule
    {
       // ...
    }
```

**Comment by olicooper** [comment]
@maliming could this possibly be reopened?

The issue extends to permissions from other modules such as "AbpIdentity" because the permission definitions for each module are in the `Application.Contracts` layer, which forces us to use magic strings instead.
The use of magic strings is code smell and the contributor does not get executed if placed in the `Application` layer because the `DbMigrator` layer doesn't know about it.

Any thoughts on how to overcome this issue? I currently place the contributor in the `Domain` layer and the permission definitions in the `Domain.Contracts` layer.
