### ISSUE TITLE
Documentation error - with solution ;-)

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2592]
in the following page :
https://docs.abp.io/en/abp/latest/Virtual-File-System

It claims that I have to add this into the .csproj file :

```
<ItemGroup>
  <None Remove="MyResources\**\*.*" />
</ItemGroup>
```

But I had to use this to make it work :

```
    <EmbeddedResource Include="wwwroot\**" />
    <Content Remove="wwwroot\**" />
```

Please, update the documentation ;-)

**Comment by wildest** [comment]
FYI if you click Edit in the top right hand corner of the document it will push you to the file in github where you can fork and edit the file and commit it back in.

**Comment by maliming** [comment]
Fix by https://github.com/abpframework/abp/commit/201f08856482930649f1bbc406e7088db7a76183
