### ISSUE TITLE
HeaderTenantResolver and RouteTenantResolver cannot resolve by tenant name

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2593]
![image](https://user-images.githubusercontent.com/30018771/72017038-d9979400-329f-11ea-8327-c1a462630ab1.png)
![image](https://user-images.githubusercontent.com/30018771/72016985-bc62c580-329f-11ea-88ce-711c030ad239.png)
![image](https://user-images.githubusercontent.com/30018771/72016648-2890f980-329f-11ea-8c58-0ff4ddd6bfc9.png)

I didn't test `CookieTenantResolver` and `DomainTenantResolver`.

**Comment by maliming** [comment]
It cannot be reproduced on the `dev `branch.
Please distinguish the case of the tenant name if the database requires it.

![image](https://user-images.githubusercontent.com/6908465/72034338-b684d880-32cf-11ea-83b8-3ede8eef3ea5.png)

![image](https://user-images.githubusercontent.com/6908465/72034393-d4523d80-32cf-11ea-8ada-9ee99827441f.png)

**Comment by gdlcf88** [comment]
I found the true problem. Please try with a Chinese tenant name. @maliming

**Comment by maliming** [comment]
This has nothing to do with ABP, please refer to Microsoft's discussion.

https://github.com/dotnet/aspnetcore/issues/4727

**Comment by dicksonkimeu** [comment]
> It cannot be reproduced on the `dev `branch.
> Please distinguish the case of the tenant name if the database requires it.
> 
> ![image](https://user-images.githubusercontent.com/6908465/72034338-b684d880-32cf-11ea-83b8-3ede8eef3ea5.png)
> 
> ![image](https://user-images.githubusercontent.com/6908465/72034393-d4523d80-32cf-11ea-8ada-9ee99827441f.png)

May i see what is in the body ?

**Comment by maliming** [comment]
hi @dicksonkimeu 

see http://docs.identityserver.io/en/aspnetcore2/endpoints/token.html

![image](https://user-images.githubusercontent.com/6908465/78335004-67dd9680-75bf-11ea-86a5-63ceb624545f.png)

**Comment by dicksonkimeu** [comment]
Thank you.
