### ISSUE TITLE
I do not register in abp.io

### ISSUE THREAD

**Issue by gxlqssjf** [abpframework/abp#2595]
I do not register in abp.io

**Comment by ismcagdas** [comment]
@gxlqssjf might be related to your password. Could you try with a password which contains an uppercase letter and a special letter like Axxxxxxxx! ?

**Comment by gxlqssjf** [comment]
Then it should  display a tip

**Comment by gxlqssjf** [comment]
I try later

**Comment by gxlqssjf** [comment]
That is OK!Thanks
