### ISSUE TITLE
UI Layout system

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#26]
- [ ] Menus (and a default main menu)
- [ ] Top Bar(s) (can contains menus)
- [ ] User Menu (special menu for user actions)
- [ ] Side Bar (left/right) (can contain menus)
- [ ] Top/Left/Right/Bottom areas.
- [ ] Warning areas
- [ ] BreadCrumb system
- [ ] Footer

**Comment by djlaney3** [comment]
Has the Side Bar feature been planned yet?

**Comment by hikalkan** [comment]
I'm closing this since it is too old and we have already implemented some of them. Will continue on separated issues when needed.
