### ISSUE TITLE
A second operation started on this context before a previous operation completed. 

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2601]
A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

**Comment by hikalkan** [comment]
Be sure that you are not using the same DbContext intance from multiple threads, as indicated by the exception message.

You might forgot an await statement resulting to create multiple threads. Check your code please. 

You can share code & stacktrace if you can't find, but please carefully check your code before.

**Comment by dicksonkimeu** [comment]
How can i create a new DbContext for each db operation ?

**Comment by dicksonkimeu** [comment]
Also this error pop: 

{"A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913."}

**Comment by hikalkan** [comment]
Adding multiple background worker should not cause any problem.

Can you repeat the problem with a fresh downloaded project with a simple scenario please? This would make it faster for us to find the problem and fix it.

**Comment by dicksonkimeu** [comment]
I am creating a new project. I will share the code.

**Comment by dicksonkimeu** [comment]
@hikalkan can I share my project in private?

**Comment by maliming** [comment]
@dicksonkimeu This is best if you can create a new project using the cli to reproduce the problem.

**Comment by dicksonkimeu** [comment]
I have recreated, and added the db entities to provide a comprehensive test.

I can share re downloaded project in private ?

**Comment by maliming** [comment]
@dicksonkimeu 
You can send me the projects.
liming.ma@volosoft.com

**Comment by yinchang0626** [comment]
@maliming @hikalkan 
In my case ,I creaed a `IDataSeeder` for  insert db data,
If use `linq ForEach` to iteration data and call `InsertAsync` will receive the same error:
![image](https://user-images.githubusercontent.com/16490084/73517309-0faadc80-4436-11ea-9433-3c81c144c68a.png),
But If use `for loop` to `InsertAsync` data is work fine
test code is like below,and called by `AppService`
```csharp
public class TestDataSeeder : IDataSeeder
{
        private readonly IRepository<Code> _codeRepository;
        public TestDataSeeder (
            IGuidGenerator guidGenerator,
            IRepository<Code> CodeRepository
            )
        {....}
        [UnitOfWork]
        public virtual async Task SeedAsync(DataSeedContext context)
        {
            var items = new List<Code>()
            {
               new Code
               {
                   TenantId=context.TenantId,
                   No="01",
                   DisplayName= "test1",
                    Description="test1"
               },
               new Code
               {
                   TenantId=context.TenantId,
                   No="02",
                   DisplayName= "test2",
                   Description="test2"
               },....
            };
            //below code is work fine
            //for (var i = 0; i < items.Count; i++)
            //{
            //    EntityHelper.TrySetId(items[i], () => _guidGenerator.Create(), true);
            //    await _codeRepository.InsertAsync(items[i], false).ConfigureAwait(false);
            //}
            items.ForEach(async item =>
            {
                 //receive `System.InvalidOperationException` 
                await _codeRepository.InsertAsync(item, false).ConfigureAwait(false);
            });
        }
}
```
Should i do not use `linq` operators in asynchronous method or framework miss somethings to handle?
Tell me If you need those test code,i can create a branch,thanks.

**Comment by maliming** [comment]
**This is wrong.**

```
items.ForEach(async item =>
{
	 //receive `System.InvalidOperationException` 
	await _codeRepository.InsertAsync(item, false).ConfigureAwait(false);
});
```


![image](https://user-images.githubusercontent.com/6908465/73519199-5222e800-443b-11ea-8ea9-4d71b80ab674.png)

**Comment by yinchang0626** [comment]
@maliming 
Thank you very much.
could you tell me this article from?
i need read it deeply.thanks

**Comment by maliming** [comment]
https://markheath.net/post/async-antipatterns
