### ISSUE TITLE
System.ObjectDisposedException: 'Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.'

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2603]
System.ObjectDisposedException: 'Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.'

This exception was originally thrown at this call stack:
	Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed()
	Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(object)
	Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope()
	Autofac.Extensions.DependencyInjection.AutofacServiceScopeFactory.CreateScope()
	Volo.Abp.AspNetCore.DependencyInjection.HttpContextServiceScopeFactory.CreateScope()
	Volo.Abp.Validation.ObjectValidator.GetErrors(object, string, bool)
	Volo.Abp.Validation.MethodInvocationValidator.AddMethodParameterValidationErrors(Volo.Abp.Validation.IAbpValidationResult, System.Reflection.ParameterInfo, object)
	Volo.Abp.Validation.MethodInvocationValidator.AddMethodParameterValidationErrors(Volo.Abp.Validation.MethodInvocationValidationContext)
	Volo.Abp.Validation.MethodInvocationValidator.Validate(Volo.Abp.Validation.MethodInvocationValidationContext)
	Volo.Abp.Validation.ValidationInterceptor.Validate(Volo.Abp.DynamicProxy.IAbpMethodInvocation)
    ...
    [Call Stack Truncated]

**Comment by hikalkan** [comment]
Probably related to your other problem: https://github.com/abpframework/abp/issues/2601

"You might forgot an await statement resulting to create multiple threads. Check your code please."
