### ISSUE TITLE
How to Integrate abp Identity Server without MVC UIs 

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2618]
Hi,
I want to use an identity server without MVC UI for login and register, I want to map existing mvc route to my angular UI. how can I do this?

This is my Identity Server Module dependencies:

```
 [DependsOn(
        typeof(AbpAutofacModule),
        typeof(AbpPermissionManagementEntityFrameworkCoreModule),
        typeof(AbpAuditLoggingEntityFrameworkCoreModule),
        typeof(AbpSettingManagementEntityFrameworkCoreModule),
        typeof(AbpIdentityEntityFrameworkCoreModule),
        typeof(AbpIdentityApplicationContractsModule),
        typeof(AbpIdentityServerEntityFrameworkCoreModule),
        typeof(AbpEntityFrameworkCoreSqlServerModule),
        typeof(AbpAccountWebIdentityServerModule),
        typeof(AbpIdentityServerDomainModule),
        typeof(AbpAspNetCoreMvcUiBasicThemeModule),
        typeof(AbpAccountApplicationModule)
    )]
    public class AuthServerHostModule : AbpModule
    {
    }
```

**Comment by olicooper** [comment]
I mentioned something similar recently: https://github.com/abpframework/abp/issues/2604

**Comment by mehdihadeli** [comment]
@olicooper I have to remove some dependency for preventing UI generation for my Identity Server and it works fine for my purpose.
 ```
   [DependsOn(
        typeof(AbpAutofacModule),
        typeof(AbpPermissionManagementEntityFrameworkCoreModule),
        typeof(AbpAuditLoggingEntityFrameworkCoreModule),
        typeof(AbpSettingManagementEntityFrameworkCoreModule),
        typeof(AbpIdentityEntityFrameworkCoreModule),
        typeof(AbpIdentityApplicationContractsModule),
        typeof(AbpIdentityServerEntityFrameworkCoreModule),
        typeof(AbpEntityFrameworkCoreSqlServerModule),
        typeof(AbpIdentityServerDomainModule),
        typeof(AbpIdentityAspNetCoreModule),
        typeof(AbpAutoMapperModule),
        typeof(AbpAspNetCoreMvcUiBasicThemeModule)
    )]
```
@olicooper in the above thread you mention `registration can be disabled`, how we can do this? please give me a sample code for disabling UI rout for Identity Server.

**Comment by olicooper** [comment]
Adding this to your appsettings.json will stop users from registering accounts on your application
```json
{ 
  "settings": {
        "Abp.Account.IsSelfRegistrationEnabled": "true"
   }
}
```
I disabled all `/Account` routes by replacing `typeof(AbpAspNetCoreMvcUiBasicThemeModule)` with `typeof(AbpAspNetCoreMvcUiMultiTenancyModule)`
Fyi my project is the API with angular UI so Identity Server is integrated.

**Comment by mehdihadeli** [comment]
Ok, thanks. Your approach is like my approuch but with replacing another module both work but In my mind in addition to the disabling `register route` abp should give us the capability of disabling other route too not just registering route.
