### ISSUE TITLE
Can't install Volo.Blogging

### ISSUE THREAD

**Issue by AlphaComposite** [abpframework/abp#2620]
When running the CLI command to install the blogging module, I get this error. 

bash-3.2$ abp add-module Volo.Blogging
[01:50:43 INF] ABP CLI (https://abp.io)
[01:50:43 INF] Version 1.1.2 (Stable channel)
[01:50:55 INF] Installing module 'Volo.Blogging' to the solution 'Test'
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by acjh** [comment]
```sh
dotnet tool install --global dotnet-ef
```

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#ef-core-3x

**Comment by AlphaComposite** [comment]
Thanks. Now I'm getting this error: 

bash-3.2$ abp add-module Volo.Blogging                               
[17:31:51 INF] ABP CLI (https://abp.io)
[17:31:52 INF] Version 1.1.2 (Stable channel)
[17:31:54 INF] Installing module 'Volo.Blogging' to the solution 'Test'
No project was found. Change the current working directory or use the --project option.
No project was found. Change the current working directory or use the --project option.

So, the command must be run in a directory that has a solution file, but it also needs to have the correct project option added. 

Which --project needs to be specified?

**Comment by maliming** [comment]
What version of the `abp cli` are you using?

```
dotnet tool list -g
```

**Comment by AlphaComposite** [comment]
1.1.2

**Comment by maliming** [comment]
http://abp.io/api/app/module/byName/?name=Volo.Blogging
```
{
	"name": "Volo.Blogging",
	"displayName": "Blogging",
	"shortDescription": "Create and manage your own blogs.",
	"efCoreConfigureMethodName": "Volo.Blogging.EntityFrameworkCore:ConfigureBlogging",
	"isPro": false,
	"longDescription": "This module adds a simple blog to your ABP application;\r\n\r\n* Allows to create multiple blogs in a single application.\r\n* Supports the Markdown format.\r\n* Allows to write comment for a post.\r\n* Allows to assign tags to the blog posts.\r\n\r\nSee the [blog.abp.io](https://blog.abp.io/) website as a live example of the blogging module.\r\n\r\nThis module is free and [open source](https://github.com/abpframework/abp/tree/dev/modules/blogging).",
	"documentationLinks": null,
	"efCoreSupport": false,
	"mongoDBSupport": false,
	"angularUi": false,
	"mvcUi": false,
	"nugetPackages": [],
	"npmPackages": [],
	"images": [],
	"id": "41185a58-90c3-b628-a529-39ee9b7ece63"
}
```

hi @yekalkan `nugetPackages` is empty.  Is this a problem?

**Comment by yekalkan** [comment]
@maliming module & nuget packages relations may not be complete. Therefore 'add-module' command is not working as intended for now. We'll fill them for all modules in a short time.

**Comment by yekalkan** [comment]
"Add-module" is working now. Remember that it needs a startup project for adding migration and updating database. 

for example: 
`abp add-module Volo.Blogging -sp ../AddModuleTest.DbMigrator/AddModuleTest.DbMigrator.csproj`

**Comment by leonkosak** [comment]
@yekalkan Can you explain how to "deal" with migrations in application/modules ([my base question](https://github.com/abpframework/abp/issues/2511#issuecomment-575688089) and [this](https://github.com/abpframework/abp/issues/2688))
