### ISSUE TITLE
Somebody actually tried publishing abp mvc application into azure web app?

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#2622]
abp 1.1.2 deployment to azure app doesn't work for me. Maybe there is some special setup involved in the process? Is there any documentation about deployment?

**Comment by maliming** [comment]
> abp 1.1.2 deployment to azure app doesn't work for me. 

Can you share the details? Any error log?

**Comment by stay2be** [comment]
@mkmita Yes and works fine except for this (#2026) problem which will be fixed in v2.0.

**Comment by mkmita** [comment]
@stay2be do you mind give some information? I followed the instructions from a few Microsoft docs, but no luck.

**Comment by mkmita** [comment]
> > abp 1.1.2 deployment to azure app doesn't work for me.
> 
> Can you share the details? Any error log?

As I understand logs folder should be able to provide?
