### ISSUE TITLE
Visual Studio Mac can't run DbMigrator (v 2.0)

### ISSUE THREAD

**Issue by AlphaComposite** [abpframework/abp#2632]
"Cannot exectue /path/todbmigrator/bin/debug/ProjectName.DbMigrator.exe"

Using Visual Studio Community 2019 for Mac, Version 8.4.

**Comment by maliming** [comment]
Can you share some screenshots?

Did you build the project and then run it.

**Comment by AlphaComposite** [comment]
Okay, I got it to run finally, but now when running the DbMigrator project the new error is referring to a table that doesn't exist. Is there an initial table generation routine that I'm missing? 

[15:19:57 INF] Started database migrations...
[15:19:57 INF] Migrating database schema...
[15:19:58 INF] Executing database seed...
[15:19:59 ERR] Failed executing DbCommand (30ms) [Parameters=[@__name_0='?' (Size = 128), @__providerName_1='?' (Size = 64)], CommandType='Text', CommandTimeout='30']
SELECT `a`.`Id`, `a`.`Name`, `a`.`ProviderKey`, `a`.`ProviderName`, `a`.`Value`
FROM `AbpSettings` AS `a`
WHERE ((`a`.`Name` = @__name_0) AND (`a`.`ProviderName` = @__providerName_1)) AND `a`.`ProviderKey` IS NULL
LIMIT 1
[15:19:59 ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext'.
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'testapp.abpsettings' doesn't exist

**Comment by AlphaComposite** [comment]
I see that there are some "initial" instructions (https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL), but they don't work either. 

"Run Add-Migration "Initial" on the Package Manager Console (select the .DbMigrator (or .Web) project as the startup project in the Solution Explorer and select the .EntityFrameworkCore.DbMigrations project as the default project in the Package Manager Console)."

Since Visual Studio on Mac doesn't have a package manager console, I'm guessing that we have to run this from the terminal in the DbMigrator project: abp Add-Migration "Initial"

Here's the error when trying to run that (there's a reference to a missing key in one of the dictionaries):

abp Add-Migration "Initial"
[15:27:35 INF] ABP CLI (https://abp.io)
[15:27:35 INF] Version 2.0.0 (Stable channel)
[15:27:36 ERR] The given key 'Initial' was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key 'Initial' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Volo.Abp.Cli.Commands.HelpCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\HelpCommand.cs:line 35
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\Github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 55

**Comment by maliming** [comment]
>  Table 'testapp.abpsettings' doesn't exist

What changes have you made to the project? Such as changing the table schema.

Will this issue still occur if you create a new project using cli?

> Since Visual Studio on Mac doesn't have a package manager console, I'm guessing that we have to run this from the terminal in the DbMigrator project folder: abp Add-Migration "Initial"

abp cli has no `Add-Migration` command, it belongs to ef core tool.
https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

**Comment by AlphaComposite** [comment]
> What changes have you made to the project? Such as changing the table schema.

None. 

> Will this issue still occur if you create a new project using cli?

Good suggestion. I updated this test project from 1.1.2 to 2.0. I'll give a clean start a try and let you know.

**Comment by AlphaComposite** [comment]
I tried to run this on Windows because there's obviously an issue with Mac due to the fact that there's no package manager in the Mac version of Visual Studio (this supposed to be a cross-platform solution, isn't it?). But changing to Windows didn't work either. Here's the error: 

![image](https://user-images.githubusercontent.com/25360554/72403417-98780780-3717-11ea-844f-bb5a2c5c3d66.png)

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/72403562-76b96780-378d-11ea-9262-f3c6666a4bf0.png)

**Comment by AlphaComposite** [comment]
Thanks. I'd been at this so long I'm starting to make silly mistakes. 

Anyway, after selecting the correct project, I'm getting another error. This one is related to MySQL. 

![image](https://user-images.githubusercontent.com/25360554/72404499-2a354400-371b-11ea-940c-b88b23f221ce.png)

**Comment by maliming** [comment]
see
https://github.com/abpframework/abp/issues/1920#issuecomment-543551659
https://github.com/abpframework/abp/issues/2053

**Comment by zhchlmm** [comment]
Thanks @maliming ,   this #2053 helped me.

btw: would you like to update the document at DataAccess Part.
|-- Switch to EF Core MySQL Provider  --> Change the Migrations DbContext

**Comment by maliming** [comment]
allright.
