### ISSUE TITLE
ABP CLI Template Database Migration doesn't seed for a default tenant.

### ISSUE THREAD

**Issue by talhazengin** [abpframework/abp#2633]
### **Reproducing the problem;**

* I created a new CLI template project with this command:
**abp new TTest -t app -u none --separate-identity-server**

* After changed default connection strings and used a localhost SQLServer instance.

* Made database migrations successfully and it shows me database seed executed.
![image](https://user-images.githubusercontent.com/46625533/72324410-ef4ff380-36bb-11ea-9d52-f28d04fe6d69.png)

* When i run "IdentityServer" or "HttpApi.Host" projects, they simply didn't run. 
Logs show me this exception:
![image](https://user-images.githubusercontent.com/46625533/72324675-85841980-36bc-11ea-99d7-46ee87a05015.png)

* So system seeks for a tenant but that tenant doesn't exist on the database.
![image](https://user-images.githubusercontent.com/46625533/72324794-cd0aa580-36bc-11ea-80a8-47f839615b63.png)

**Comment by maliming** [comment]
I guess it is caused by the localhost cookie, please try to clear it, or try use incognito mode of chrome.

**Comment by talhazengin** [comment]
Thank you very much. It is a cache issue. I use incognito mode from now.
