### ISSUE TITLE
How to integrate Identity Server with Active Directory

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2636]
Hi,
I want to integrate my identity server with active directory. is there any module in abp for this purpose or I have to use built-in identity server features?

**Comment by jortygu** [comment]
my solution is add WsFederation privider , then i can login in adfs login page,and then redirect to my own web application with authentication info.
```
context.Services.AddAuthentication()
     .AddWsFederation("adfs", "adfs", options => {
          options.MetadataAddress = "https://adfstest/federationmetadata/2007-06/federationmetadata.xml";
          options.Wtrealm = "urn:identityServer";
     });
```

**Comment by mehdihadeli** [comment]
@jortygu I can't use ADFS, I want to use LDAP.

**Comment by hikalkan** [comment]
@mehdihadeli have you searched for this on web? You know because we are using standard AspNet Core Identity library and IDS4 for the authentication system. Maybe you can configure it in your solution. If not, we try to help.

**Comment by gterdem** [comment]
I think @mehdihadeli wants to use LDAP userstore for authenticating the users for IdentityServer4 which will cause some problems (if @hikalkan can confirm) since users won't be stored in IdentityServer4 entities but somewhere else.

You can create a new `UserStore` which has some methods like `bool ValidateCredentials` and match the user's username and password via LDAP (like `LdapEntry.Bind` method).
You may also need to manually implement a new ProfileService service with `IProfileService` and handle the issued claims for requests.

**Comment by hikalkan** [comment]
I should check this (added to milestone 2.2). If needed, we can add extension points to the Identity and Account modules (like we did for [AspNet Boilerplate before](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.Zero.Ldap/Ldap/AbpZeroLdapModule.cs)).

**Comment by hikalkan** [comment]
BTW, how this is done if we would use a standard AspNet Core application with AspNet Core Identity? Anyone tried?

**Comment by mehdihadeli** [comment]
@hikalkan Yes, I search about it and I decided to use LDAP for this purpose. I read your identity server module, you created a custom `ResourceOwnerPasswordValidator` for simple authentication. I decided to extended this validator to support both LDAP and Simple user and password authentication, Actually I want both these features in my IDP. Do you have any solution for my case? Maybe my design is incorrect.

**Comment by gterdem** [comment]
Hello @mehdihadeli 
What is you current status about the issue?

**Comment by mehdihadeli** [comment]
@gterdem Hi, I created a custom user manager for this purpose:

 ```
public class LdapUserManager<TUser> : Microsoft.AspNetCore.Identity.UserManager<TUser>
        where TUser : IdentityUser
    {
        private readonly IEventService _events;
        private readonly ILdapManager _ldapManager;
        private readonly AbpLdapOptions _ldapOptions;

        public LdapUserManager(
            IUserStore<TUser> store, IOptions<IdentityOptions> optionsAccessor, IPasswordHasher<TUser> passwordHasher,
            IEnumerable<IUserValidator<TUser>> userValidators,
            IEnumerable<IPasswordValidator<TUser>> passwordValidators, ILookupNormalizer keyNormalizer,
            IdentityErrorDescriber errors, IServiceProvider services, ILogger<UserManager<TUser>> logger,
            IEventService events,
            ILdapManager ldapManager,
            IOptions<AbpLdapOptions> ldapOptions
        ) : base(
            store, optionsAccessor, passwordHasher, userValidators, passwordValidators, keyNormalizer, errors, services,
            logger
        )
        {
            _events = events;
            _ldapManager = ldapManager;
            _ldapOptions = ldapOptions.Value;
        }

        public override async Task<bool> CheckPasswordAsync(TUser user, string password)
        {
            if (string.IsNullOrEmpty(_ldapOptions.DomainName))
            {
                throw new InvalidOperationException("The LDAP Hostname cannot be empty or null.");
            }

            if (string.IsNullOrEmpty(password) || string.IsNullOrEmpty(user.UserName))
            {
                throw new InvalidOperationException("The LDAP User and Password cannot be empty or null.");
            }

            var userName = string.IsNullOrWhiteSpace(_ldapOptions.DomainName)
                ? user.UserName
                : $"{user.UserName}@{_ldapOptions.DomainName}";

            var success = _ldapManager.Authenticate(userName, password);
            if (success)
            {
                Logger.LogInformation("Credentials validated for username: {username}", userName);
                await _events.RaiseAsync(new UserLoginSuccessEvent(userName, user.Id.ToString(), userName,
                    interactive: false));
                return true;
            }

            Logger.LogInformation("Authentication failed for username: {username}, reason: invalid credentials",
                userName);
            await _events.RaiseAsync(new UserLoginFailureEvent(userName, "invalid credentials",
                interactive: false));
            return false;
        }
//...
}
```

**Comment by gterdem** [comment]
@mehdihadeli Yeah, seems about right. Does it work for you?

**Comment by mehdihadeli** [comment]
> @mehdihadeli Yeah, seems about right. Does it work for you?

yes it worked correctly

**Comment by gterdem** [comment]
@mehdihadeli Good to hear that. Closing the issue.
