### ISSUE TITLE
Rename Tenant to Company Code on log in screen

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2638]
How can I rename tenant label to Company Code in login screens ? i can use resources settings file ?

**Comment by maliming** [comment]
You can override the `AbpUiMultiTenancyResource `localization text.


https://docs.abp.io/en/abp/latest/Localization
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy/Volo/Abp/AspNetCore/Mvc/UI/MultiTenancy/Localization/AbpUiMultiTenancyResource.cs

**Comment by dicksonkimeu** [comment]
Any sample code ?

I don't want to update abp source code.

**Comment by maliming** [comment]
Please follow the instructions in the documentation to override it.

https://docs.abp.io/en/abp/latest/Localization
