### ISSUE TITLE
abp v2.0.0,when FullAuditedAggregateRoot use owned entity types(ValueObject), Efcore throw error

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#2640]
When i add a ValueObject as owned by FullAuditedAggregateRoot.
Get a exception below
```csharp
System.InvalidOperationException: 'The type 'ISBN' cannot be marked as owned because a non-owned entity type with the same name already exists.'
```
I just reuse code of #2365 to report this error,but in v1.1.2 or pure aspnet mvc template propject, It works fine.
You can get sample code in
 [this for v1.1.2(PASS)](https://github.com/yinchang0626/abp/tree/feature/book_store_ownedType_112),
[this for v2.0.0(NG)](https://github.com/yinchang0626/abp/tree/feature/book_store_ownedType_200).

@hikalkan 
Suppose Abp support OwnedType of EFCore(#2278 ),I can't find anything to test this feature,
could I add those sample code to BookStore sample or add unitest ,
because of in DDD,ValueObject  is very common sense. We hope abp can fully support it for EFCore

**Comment by maliming** [comment]
TRY

```
protected override void OnModelCreating(ModelBuilder builder)
{
	//Mark owned types, so base.OnModelCreating can handle them
	builder.Owned<ISBN>();

	base.OnModelCreating(builder);

	/* Configure the shared tables (with included modules) here */
	
	//...........
}
```

**Comment by yinchang0626** [comment]
@maliming 
thank you for help , butthe error still exist
![image](https://user-images.githubusercontent.com/16490084/72404427-4921ed80-3790-11ea-8305-c5e4ba7dff0f.png)

**Comment by maliming** [comment]
Please put the code(`builder.Owned<ISBN>();` `base.OnModelCreating(builder);`) in your `OnModelCreating` method.

https://github.com/yinchang0626/abp/blob/feature%2Fbook_store_ownedType_200/samples/BookStore/src/Acme.BookStore.EntityFrameworkCore/EntityFrameworkCore/BookStoreDbContext.cs#L36

**Comment by yinchang0626** [comment]
@maliming 
Thank you very much,it works!!
This is related to the execution order.

Is possible move `base.OnModelCreating(builder);` to bottom of `protected override void OnModelCreating(ModelBuilder builder)`
```csharp
        protected override void OnModelCreating(ModelBuilder builder)
        {
            //builder.Owned<ISBN>();
            //builder.ConfigureBookStore();// move to bottom

            /* Configure the shared tables (with included modules) here */

            builder.Entity<AppUser>(b =>
            {
                b.ToTable("AbpUsers"); //Sharing the same table "AbpUsers" with the IdentityUser

                b.ConfigureFullAudited();
                b.ConfigureExtraProperties();
                b.ConfigureConcurrencyStamp();
                b.ConfigureAbpUser();

                //Moved customization to a method so we can share it with the BookStoreMigrationsDbContext class
                b.ConfigureCustomUserProperties();
            });

            /* Configure your own tables/entities inside the ConfigureBookStore method */

            builder.ConfigureBookStore();//include config ISBN (builder.Owned<ISBN>();)
            base.OnModelCreating(builder);// move to here
        }
```
above code runs well too,
But Is It break something about abp code?

**Comment by maliming** [comment]
> But Is It break something about abp code? 

Not currently.

**Comment by yinchang0626** [comment]
> > But Is It break something about abp code?
> 
> Not currently.

excuse me @maliming 
Do you mean It's fine now?
So,could I modify the code of template(both app and module) to move `base.OnModelCreating(builder);` to bottom at `MyProjectNameDbContext`??

**Comment by maliming** [comment]
Yes, you can modify your project code. I think we should not change the code of the abp module and template but use the above method to solve it.

**Comment by yinchang0626** [comment]
Ok. got it.
thank you.
Maybe you can close this issuse if no need to add sample code for test `OwnedType` feature or modify anything.
by the way ,in my situation 
I just want to add OwnedType in a from abp template generated project,
should be careful can't config it in `YYDbContextModelCreatingExtensions` and remember do it before  `base.OnModelCreating` of all `DbContext`(both module,app ,host app..).
why not modify template code to avoid missing something?

**Comment by LGinC** [comment]
put code to OnModelCreating method and add migration will delete this table

**Comment by yinchang0626** [comment]
`Order` Entity should config in `builder.ConfigureOrderManagement()`. Because of migration need it.
Just `ShippingAddress` OwnedType config before `base.OnModelCreating`
```csharp
        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Owned<ShippingAddress>();
            base.OnModelCreating(builder);
            builder.ConfigureOrderManagement();//include config Order
            
        }
```

**Comment by LGinC** [comment]
> @LGinC
> `Order` Entity should config in `builder.ConfigureOrderManagement()`. Because of migration need it.
> Just `ShippingAddress` OwnedType config before `base.OnModelCreating`
> 
> ```cs
>         protected override void OnModelCreating(ModelBuilder builder)
>         {
>             builder.Owned<ShippingAddress>();
>             base.OnModelCreating(builder);
>             builder.ConfigureOrderManagement();//include config Order
>             
>         }
> ```

thx
