### ISSUE TITLE
How to configure Authentication to respond failed information just like /api/identity/users did? 

### ISSUE THREAD

**Issue by RayMMond** [abpframework/abp#2643]
I created a custom CRUD app service with Authorize attribute and configured authentication using  **bearer**.

`context.Services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)`

but the response does't contain response body like /api/identity/users when authentication failed.

Expected response (/api/identity/users):

Response body
> "error": {
    "code": null,
    "message": "Authorization failed! Given policy has not granted: AbpIdentity.Users",
    "details": null,
    "validationErrors": null
  }

Response headers

>  _abperrorformat: true 
 content-length: 144 
 content-type: application/json; charset=utf-8 
 date: Wed, 15 Jan 2020 08:21:00 GMT 
 server: Kestrel 
 status: 401 

Actual response (Custom app service):

Response headers

>  content-length: 0 
 date: Wed, 15 Jan 2020 08:23:07 GMT 
 server: Kestrel 
 status: 401 
 www-authenticate: Bearer 
 x-correlation-id: 727da97c0d5b4eff8dc83c521055255c 

The same happened when adding [Authorize] to TestController in template.

**Comment by maliming** [comment]
Try calling an application service that requires authorization in a controller that allows anonymous methods

**Comment by RayMMond** [comment]
@maliming Thanks for the explanation :).
And one more question, Why calling auto generated API(Auto API Controllers) will redirect to the login page when authentication failed but standard MVC controller respond 401?

**Comment by maliming** [comment]
> Why calling auto generated API(Auto API Controllers) will redirect to the login page when authentication failed  but standard MVC controller respond 401?

When you call the controller that requires authentication, the authentication middleware finds that the current user is not authenticated and calls ChallengeAsync (DefaultChallengeScheme is identity cookie). At this point the request has been shorted.

If your anonymous controller calls the application service method, it will execute the ABP filter and interceptor. The framework throws AbpAuthorizationException, the filter wraps the exception into a 401, etc.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/9940
