### ISSUE TITLE
how to send email with the correct email configuration without nonencrypted password.

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#2644]
@maliming @hikalkan 
it's sorry to disturb you ; but i can't send the email with correct setting of emailings.
when i debugged the code, i found that the below code will throw exceptions.
``` 
var password = await SmtpConfiguration.GetPasswordAsync() 

The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
```

and i  see that setting definitions like these shows that is default Password is encrypted, how can i set it non encrypted.

 https://github.com/abpframework/abp/blob/65cd3ea8ab7b919cf4ff958dd272415b38ad7926/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/EmailSettingProvider.cs#L11-L23

in fact , i can directly send emails  with the mailkit , however , i want to use the abp.emailing module to work more effectively. 
sincerely thanks.

**Comment by johnnba** [comment]
although i tried to encrypt the password by the IStringEncryptionService; the password will be fine. 
but the following code stills return error

> await smtpClient.SendMailAsync(mail);

**Comment by maliming** [comment]
> in fact , i can directly send emails with the mailkit

You can try [Volo.Abp.MailKit](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.MailKit).

**Comment by johnnba** [comment]
yeah, i've made some mistakes, with the encrypted password, i can send email successfully. thanks.
it's my fault. 

> although i tried to encrypt the password by the IStringEncryptionService; the password will be fine.
> but the following code stills return error
> 
> > await smtpClient.SendMailAsync(mail);
> 
> ```
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
>    at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
>    at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
>    at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
> ```

the exception is the emailsend wrote by myself that i used to replace the original MailKitSmtpEmailSender ,missed the authenticate step. sorry .

however it's happy that the issue is solved now. thanks
