### ISSUE TITLE
How to disable show  ef core sql to console

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2647]
update to 2.0,and show ef core sql default, but i just want to watch business output. so how to disable it.

**Comment by mehmetuken** [comment]
Add in Program.cs Logger configure
`.MinimumLevel.Override("Microsoft", LogEventLevel.Information)` after this line
`.MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Error)`.
Set EntityFrameworkCore minimum log level Error.
