### ISSUE TITLE
ajax: abp.libs.datatables.createAjax

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2650]
How do I add input parameters ?

i.e assume the getList expects a input parameter as string how do i add to below code ?

`ajax: abp.libs.datatables.createAjax(insurance.selfCore.custEntry.getList),`

below is not working

```
ajax: abp.libs.datatables.createAjax(insurance.selfCore.custEntry.getList),
            function () {
                return {no: 'F006-1022'};
                        }),
```

**Comment by dicksonkimeu** [comment]
hospital.selfCore.assigments.getListByIDNo({}).done(function (result) { console.log(result); });

By service getListByIDNo expects some input parameters, how can i pass them ?

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/775

**Comment by dicksonkimeu** [comment]
@maliming it worked. But when the input variable/ value is hardcoded. How can assign the value which is in the onGet method in the razor page.

bookNo should be assigned to a value derived in the razor page onGet method.

```
       ajax: abp.libs.datatables.createAjax(insurance.selfCore.custEntry.getList),
            function () { return bookNo;                  }),
```

**Comment by wakuflair** [comment]
@dicksonkimeu 
I did it in this way:
Use a hidden input to bind `bookNo` value:
`<input type="hidden" id="bookNo" value="@Model.BookNo">`

Then use jquery to get value:
``` javascript
ajax: abp.libs.datatables.createAjax(insurance.selfCore.custEntry.getList, function() {
 return {
    bookNo: $(bookNo).val()
});
```

**Comment by dicksonkimeu** [comment]
@wakuflair @maliming Thank you it has worked.

My last question is on how to refresh the table based on a selected list changed event.

![image](https://user-images.githubusercontent.com/4476822/72518202-d6834180-3865-11ea-9f7d-1b4d63719aef.png)

**Comment by dicksonkimeu** [comment]
> @dicksonkimeu
> I did it in this way:
> Use a hidden input to bind `bookNo` value:
> `<input type="hidden" id="bookNo" value="@Model.BookNo">`
> 
> Then use jquery to get value:
> 
> ```js
> ajax: abp.libs.datatables.createAjax(insurance.selfCore.custEntry.getList, function() {
>  return {
>     bookNo: $(bookNo).val()
> });
> ```

In this example what happens when the input is two or three values i.e `getList(string a, string b)`
