### ISSUE TITLE
Disable ABP module

### ISSUE THREAD

**Issue by duard-sf** [abpframework/abp#2653]
I would like to disable the `Volo.Abp.Account.Web` module, because its routing is taking precedence. This prevents initial routing to any `account/` routes I have set up in my Angular app.

I tried using `PreConfigureServices` to remove the application part (see code below), but this does not seem to work.

```c#
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<IMvcBuilder>(mvcBuilder =>
    {
        mvcBuilder.PartManager.ApplicationParts.Remove(mvcBuilder.PartManager.ApplicationParts.FirstOrDefault(p => p.Name == "Volo.Abp.Account.Web"));
    });
}
```

Is there any way to achieve this?

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2604

**Comment by duard-sf** [comment]
So should I disable the following two settings?

- Abp.Account.IsSelfRegistrationEnabled
- Abp.Account.EnableLocalLogin

I did so in appsettings.json ([following the docs](https://docs.abp.io/en/abp/latest/Settings#setting-values-in-the-application-configuration)), but still no change.

```javascript
"Settings": {
  "Abp.Account.IsSelfRegistrationEnabled": "False",
  "Abp.Account.EnableLocalLogin": "False"
}
```

**Comment by duard-sf** [comment]
Ah, no worries, I followed [the advice from mehdihadeli](https://github.com/abpframework/abp/issues/2618#issuecomment-574526156) which solves the issue!

Thanks very much for you help.
