### ISSUE TITLE
Dynamic JavaScript Proxies Not Working In Tiered Project

### ISSUE THREAD

**Issue by mostafa1790** [abpframework/abp#2656]
**Dynamic JavaScript Proxies** Not Working In Tiered Project When I Run The Project I Can Use The Name Space In Browser Developer Tools And I Found The *.HttpApi Project Controllers But I Didn't Found Any Services From *.Application.Contracts

Note :
I Took Book Service From The Example And Insert All Related Files [Entity - Dtos - Service] And Didn't Work Also

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/1469

**Comment by mostafa1790** [comment]
Ok Thanks For Fast Replying .
