### ISSUE TITLE
Test bootstrap tag helpers documentation

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2657]
- [x] Test all components on the https://bootstrap-taghelpers.abp.io/ web site.
- [x] Extract a list of missing component documentation & samples.

**Comment by mkmita** [comment]
I noticed there is no file helper right?

**Comment by hikalkan** [comment]
>I noticed there is no file helper right?

Yes! :)

**Comment by armgnunlu** [comment]
# Abp Bootstrap Tag Helper 

### [+] Alerts 

### [+] Badges

### [+] Breadcrumbs 

### [-] Buttons

​	Active state 

​	Disabled state 

​	Checkbox and radio buttons

### [-] Button group

​	dropright dropleft options

### [-] Card

​	card styles are broken

​	navigation and pills to a card’s header 

​	cards with using grid markup

​	cards with using utilities

​	Image overlays

​	Text alignment

​	card borders 

​	card layout/groups

​	Card decks

​	Card columns

### [-] Carousel

### [-] Collapse

​	need to explain methods

### [-] Dropdowns

​	dropdowns with button OK - dropdowns with <a> not OK

​	2nd Split button header > Sizing (wrong title)

​	directions > variations (dropup - dropright....) should be same with bootstrap

​	menu headers

​	menu forms

​	active/disabled menu items

------------------------------------------

### [] Forms

### [] Dynamic Forms

### [] Input group

We should text them together

-----------------------------------------------------------



### [-] Jumbotron

### [-] List group

​	need to be same with BS (priority: high)

### [-] Modal

​	missing all examples

### [-] Navs

​	there is just basic. need to more

### [-] Navbar

### [-] Pagination

​	sizing

### [-] Popovers

​	dismiss on next click

### [+] Progress

### [-] Scrollspy

### [+] Tooltips

**Comment by armgnunlu** [comment]
About the forms and inputs:
I think "form" and "form elements" are messy because they are used on other pages. We should write them on one page and repeat them if necessary.
@yekalkan

**Comment by armgnunlu** [comment]
@cotur
