### ISSUE TITLE
entity framework throw an exception when use conversion

### ISSUE THREAD

**Issue by xkaede** [abpframework/abp#2664]
I have an entity User and a value object UserName like this.
```
public class User : AggregateRoot<Guid>
{
    public UserName Name { get; set; }
}

public class UserName : ValueObject
{
    public UserName(string name)
    {
        Value = name;
    }

    public virtual string Value { get; protected set; }
}
```
In entity framework I use the conversion to map UserName to string.
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    var nameConverter = new ValueConverter<UserName, string>(d => d.Value, s => (UserName) s);
    modelBuilder.Entity<User>(b =>
    {
        b.Property(t => t.Name).HasConversion(nameConverter);
    });
}
```
When I use the repository to get the User.The ef throw the exception:
" No suitable constructor found for entity type 'UserName'. The following constructors had parameters that could not be bound to properties of the entity type: cannot bind 'name' in 'UserName(string name)'"

I find the Issues due to this changes:
https://github.com/abpframework/abp/blob/0c16d0439a6b51f0fb45872f69e1f6c3a5009eaa/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L90

the "modelBuilder.Model.GetEntityTypes()" does not filter the entity which is not an actual database entity.in my situation , the UserName entity should be excluded.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2640#issuecomment-574483336

**Comment by xkaede** [comment]
I have checked the #2640 before, but I do not want to use the own type. by the way, if I use the owned type to do this.I need to add the builder.Owned<UserName>() to all DbContext who use my module. and may foget to add it.
eg:
```
protected override void OnModelCreating(ModelBuilder builder)
{
    //builder.Owned<UserName>();

    base.OnModelCreating(builder);

    builder.ConfigureIdentity();
}
```
It force the user to add builder.Owned<UserName>(); before the base.OnModelCreating(builder);
not just add builder.ConfigureIdentity(); simply

**Comment by xkaede** [comment]
ok, may be I can define a method called PreConfigureIdentity() like this.
```
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.PreConfigureIdentity();

    base.OnModelCreating(builder);

    builder.ConfigureIdentity();
}
```
I am trying to find a way to support skip conversion entity.

**Comment by xkaede** [comment]
Hi @maliming .
I solve the issue finally. by just ignore the UserName entity.
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    var nameConverter = new ValueConverter<UserName, string>(d => d.Value, s => (UserName) s);
    modelBuilder.Entity<User>(b =>
    {
        b.Property(t => t.Name).HasConversion(nameConverter);
    });
    modelBuilder.Ignore<UserName>();
} 
```
Thank you very much!
