### ISSUE TITLE
Q: Upgrading to netstandard2.1

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2667]
Modules project files (.csproj) have TargetFramework assigned to netstandard2.0.
Consider upgrading to **netstandard2.1** ?

Related: https://github.com/abpframework/abp/issues/87

**Comment by leonkosak** [comment]
Huh, targeting NET Standard 2.1 currently (will change in the future) significantly reduces usage in other frameworks.

**Comment by hikalkan** [comment]
>Consider upgrading to netstandard2.1 ?

Why? you can use in .netstandard 2.0 based project in any project can use netstandard2.1. Right? Why we depend on a higher version that will restrict its usage unnecessarily.

**Comment by leonkosak** [comment]
I agree. :) If you need (want) you can manually change this param in csproj file in generated module project.
