### ISSUE TITLE
Add dynamic Angular environment configuration

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2669]
I'd like to be able to build my angular application for production and then change the api urls and oauth config between environments. Is there a way to do this or can it be built-in?

**Comment by mehmet-erim** [comment]
Angular UI modules can't access the application environment directly. The environment passes to the `CoreModule` inside the `AppModule`. See the [`AppModule`](https://github.com/abpframework/abp/blob/dev/templates/app/angular/src/app/app.module.ts#L23).
Then, `CoreModule` add the environment to the `ConfigState`. All Angular UI modules consume the environment via `ConfigState`.

We can create an action named `SetEnvironment` to change the environment dynamically.

**Comment by olicooper** [comment]
Yes that would work. I imagined creating a json file that I could read in similar to how [aspnetboilerplate did it](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/assets/appconfig.json).
Thanks :+1:
