### ISSUE TITLE
Any plan to have a shared js model library?

### ISSUE THREAD

**Issue by tekix** [abpframework/abp#2673]
Today most of the js models are in the `ng-packs` projects (such as ApplicationConfiguration.Response), is there any plan to move them into a shared library so they can be reused in react or vue projects 

https://github.com/abpframework/abp/blob/be1433846edbb6953ea3700aef6a0b22ac4f4399/npm/ng-packs/packages/core/src/lib/models/application-configuration.ts#L4-L10

**Comment by ismcagdas** [comment]
@itryan seems a good idea. @mehmet-erim what do you think ?

**Comment by hikalkan** [comment]
@mehmet-erim is it possible? If possible, we can add this to the backlog.

**Comment by mehmet-erim** [comment]
@hikalkan Yes, it is possible. We can create a library that doesn't contain framework-specific codes.

**Comment by itryan** [comment]
maybe some of the returned types of `observable/Subject` can be adapted to `Promise<>` so they will not depend on `rxjs` library.

**Comment by mehmet-erim** [comment]
> maybe some of the returned types of `observable/Subject` can be adapted to `Promise<>` so they will not depend on `rxjs` library.

That's right. We will consider this.
