### ISSUE TITLE
New ABP 2.0 project has below error

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#2676]
![image](https://user-images.githubusercontent.com/4476822/72665752-5fdc7480-3a1c-11ea-8e43-ee310e16226d.png)

![image](https://user-images.githubusercontent.com/4476822/72665764-839fba80-3a1c-11ea-9035-b7ef6d580586.png)

**Comment by hikalkan** [comment]
Can you share the exception message and stacktrace in the log file (inside the Logs folder of the applcation)?

**Comment by dicksonkimeu** [comment]
@hikalkan 
[logs.txt](https://github.com/abpframework/abp/files/4083633/logs.txt)

**Comment by maliming** [comment]
@dicksonkimeu  What are the steps to reproduce the problem?

**Comment by dicksonkimeu** [comment]
Just create a new project from abp site. Update Database and run.

No changes at all.

**Comment by hikalkan** [comment]
I don't see any exception in your logs.

You are getting error from the ServiceProxyScript endpoint. Can you show what it returns?
What is your project name? "Switch"?

Also, I suppose this is an MVC project. @maliming can you just download a new project and test please (I don't suppose it will have a problem, but to be sure).

**Comment by maliming** [comment]
Everything works fine.
![image](https://user-images.githubusercontent.com/6908465/72710415-056d2080-3ba2-11ea-8c87-d8391253fb57.png)

**Comment by dicksonkimeu** [comment]
See below . I can log in but cant see users and can't create. Same to everything else. Can't see list, create etc.

![image](https://user-images.githubusercontent.com/4476822/72749467-31e96280-3bcb-11ea-9117-e4312e82e586.png)

**Comment by dicksonkimeu** [comment]
Hello.
Project name is the issue. Switch.

Java seems to use this name. Hence the issue
