### ISSUE TITLE
how to use auto primary key in mongodb

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2677]
auto increase id or objectid,  how  to use it in mongodb,how to implete entity

public class MyEntity : Entity<ObjectId>   ???

**Comment by hikalkan** [comment]
We are generally using Guid. @maliming can you try and help on that?

**Comment by maliming** [comment]
When you use MongoDbRepository's `InsertAsync `method to insert an entity that inherits from `IEntity<Guid>`, it will automatically set the value of the guid.

https://github.com/abpframework/abp/blob/0a1568781df03fe9c86dc38cb7d47b95389cdf0b/framework/src/Volo.Abp.MongoDB/Volo/Abp/Domain/Repositories/MongoDB/MongoDbRepository.cs#L186-L192

**Comment by hikalkan** [comment]
I suppose @LGinC want to use auto increase id or [objectid](https://mongodb.github.io/node-mongodb-native/2.0/tutorials/objectid/) instead of Guid.
But I suppose there is not an auto increase id in MongoDB by default (maybe I'm wrong).

**Comment by LGinC** [comment]
> I suppose @LGinC want to use auto increase id or [objectid](https://mongodb.github.io/node-mongodb-native/2.0/tutorials/objectid/) instead of Guid.
> But I suppose there is not an auto increase id in MongoDB by default (maybe I'm wrong).

yes, that's so

**Comment by maliming** [comment]
@LGinC Can you share a project?

**Comment by SarcoZ** [comment]
@hikalkan 
mongodb  auto increase id can be create like this
 [ExposeServices(typeof(ISequenceGenerator<int>))]
    public class MongoSequenceGenerator : ISequenceGenerator<int>, ITransientDependency
    {
        private readonly IRepository<Sequence, string> _sequenceRepository;
     
        public MongoSequenceGenerator(IRepository<Sequence, string> repository)
        {
            _sequenceRepository = repository;
        }
      
        public int GetSequence(string key, int step)
        {
            var sequenceCollection = _sequenceRepository.GetCollection();

            return sequenceCollection.FindOneAndUpdate(Builders<Sequence>.Filter.Eq(p => p.Id, key),
                Builders<Sequence>.Update.Inc(p => p.CurrentValue, step),
                    new FindOneAndUpdateOptions<Sequence>
                    {
                        IsUpsert = true,
                        ReturnDocument = ReturnDocument.After
                    })
                .CurrentValue;
        }
    }

when any other appservice use this service, ,first get getsequence,then do something else wrong, it seems transaction not work well, [UnitOfWork(true)] still not work,how do i to do?

**Comment by fmpfmp** [comment]
@LGinC 

ConventionRegistry.Register("StringObjectIdRepresentationConvention", new ConventionPack { new StringObjectIdRepresentationConvention() }, t => true);

public class StringObjectIdRepresentationConvention : ConventionBase, IPostProcessingConvention
    {
        public void PostProcess(BsonClassMap classMap)
        {
            foreach (var memberMap in classMap.DeclaredMemberMaps)
            {
                if (memberMap.MemberName.Equals("id", StringComparison.OrdinalIgnoreCase) && memberMap.MemberType == typeof(string))
                {
                    memberMap.SetIdGenerator(StringObjectIdGenerator.Instance).SetSerializer(new StringSerializer(BsonType.ObjectId));
                }
            }
        }
    }
}
