### ISSUE TITLE
No theme registered!

### ISSUE THREAD

**Issue by abdumostafa** [abpframework/abp#2679]
I'm trying to remove **AbpAspNetCoreMvcUiBasicThemeModule** from my web module because I have my own theme, but I got this Exception:

> AbpException: No theme registered! Use AbpThemingOptions to register themes.

..
Do I have to develop my own theme ? or I can  just remove the basic theme module and work with razor pages normally ?

**Comment by hikalkan** [comment]
Use `AbpThemingOptions` to register your theme. If you remove the theme, other modules will fail because they are using layouts of the current theme.
So, copy the basic theme into your solution and start your customization. This would be better and more compatible to existing modules.
