### ISSUE TITLE
Show additional info/notifications after a request

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#268]
We may want to show additional info to the user after the request.

- Consider AJAX scenario.
- Consider regular http request (full page load).
- We may want to show a toastr style notification or a messagebox (where user need to click to the OK button).

So, we should allow the application code to add such info to a state (a service?) and send to and handle on the client side.

**Comment by hikalkan** [comment]
Additional info: Already implemented alerts system for MVC applications.

**Comment by zHaytam** [comment]
Hello, is it possible to show us how? I want to show a message to the user after `OnPostAsync`, is it possible with ABP or should I roll my own thing? 
Thank you!

**Comment by hikalkan** [comment]
If you've inherited from the [AbpPageModel](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI/Volo/Abp/AspNetCore/Mvc/UI/RazorPages/AbpPageModel.cs), directly use `Alerts.Add...` (or Info, Warning... etc.). You can inject IAlertManager where you need in another code part.

**Comment by zHaytam** [comment]
I tried that, but since it uses a plain `List`, using `RedirectToX` won't work :/

**Comment by hikalkan** [comment]
So, you implement yourself 😄
