### ISSUE TITLE
How to customize or Replace AbpResourceOwnerPasswordValidator?

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2680]
Hi,
I want to customize AbpResourceOwnerPasswordValidator to add some extra functionality for support LDAP. how can I customize or Replace `AbpResourceOwnerPasswordValidator` for validation `resource owner flow` in Identity Server?

**Comment by hikalkan** [comment]
Just replace IResourceOwnerPasswordValidator service with your own implementation (probably derived from AbpResourceOwnerPasswordValidator and overriding some virtual methods). 

See https://docs.abp.io/en/abp/latest/Dependency-Injection#replace-a-service

**Comment by mehdihadeli** [comment]
Ok thanks.

**Comment by mtozlu** [comment]
For reference;
First create a class named `CustomResourceOwnerPasswordValidator` derived from `AbpResourceOwnerPasswordValidator`. And register it in your module:
```csharp
public override void PreConfigureServices(ServiceConfigurationContext context)
{
  PreConfigure<IIdentityServerBuilder>(builder =>
  {
    builder.AddResourceOwnerValidator<CustomResourceOwnerPasswordValidator>();
  });
  context.Services.Replace(
    ServiceDescriptor.Transient<AbpResourceOwnerPasswordValidator, CustomResourceOwnerPasswordValidator>());
}
```
