### ISSUE TITLE
How to change CurrentTenant in IAuthorizationFilter

### ISSUE THREAD

**Issue by luy710** [abpframework/abp#2682]
How to change CurrentTenant in IAuthorizationFilter
I execute _currentTenant.Change (new Guid ("3FA85F64-5717-4562-B3FC-2C963F66AFA7")) in IAuthorizationFilter; but the CurrentTenant value has not changed in the DbContext

I need to determine tenant by user identity and corresponding action
Is there any good solution for this requirement

thanks !

**Comment by maliming** [comment]
`IAuthorizationFilter`  seems unable to intercept methods, please share your code.

**Comment by luy710** [comment]
`namespace MT.Module.Shops.Filter
{
    public class TestChangeTenantAttribute : TypeFilterAttribute
    {

        public TestChangeTenantAttribute(string  actionType ) : base(typeof(AuthorizeAdminFilter))
        {
            this.Arguments = new object[] { actionType };
        }

        #region 内部过滤器

        /// <summary>
        /// 管理员授权过滤器
        /// </summary>
        private class AuthorizeAdminFilter : IAuthorizationFilter
        {
            public ICurrentTenant _currentTenant { get; set; }
            public string _actionType { get; set; }
            public ICurrentUser _currentUser { get;set;}
            #region 构造函数

            public AuthorizeAdminFilter(string actionType, ICurrentTenant currentTenant, ICurrentUser _currentUser)
            {
               
                this._currentTenant = currentTenant;
                this._actionType = actionType;
            }

            #endregion
            public void OnAuthorization(AuthorizationFilterContext context)
            {
                //if(this._actionType == "TTenant" && _currentUser.ComId == "2C963F66AFA7")
                _currentTenant.Change(new Guid("3FA85F64-5717-4562-B3FC-2C963F66AFA7"));
            }
        }
        #endregion
    }
}`

**Comment by maliming** [comment]
You should use the Change method as follows.

https://github.com/abpframework/abp/blob/0a1568781df03fe9c86dc38cb7d47b95389cdf0b/framework/src/Volo.Abp.AspNetCore.MultiTenancy/Volo/Abp/AspNetCore/MultiTenancy/MultiTenancyMiddleware.cs#L46-L49


You cannot change subsequent tenants in the OnAuthorization method because there is no way to intercept it.
