### ISSUE TITLE
Integrate abp modules with angular insted of MVC

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2684]
Hi,
Is it possible we use angular for our modules UIs instead of mvc? I saw existing abp modules and all of them use mvc for generating UI for modules.I want to create modular system with angular insted of mvc. Do you any solutions for this issue?

**Comment by leonkosak** [comment]
You have Angular UI option when generating abp application. In Angular application, there are Volo npm packages referenced.
I don't know where do you see problems?

**Comment by mehdihadeli** [comment]
@leonkosak I want to create a module, not application, for example, I want to create an abp module with angular UI and I want to add it to my application with `[DependsOn()]` attribute.

**Comment by hikalkan** [comment]
All abp modules also have angular UIs, but not inside the module folder. See angular UI of the modules: https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages 
They are deployed as NPM packages. It is not C#, so you cand use DependsOn attribute for them. You will depend in your package.json file for NPM.
