### ISSUE TITLE
How to support the "Devart.Data.*.EFCore"?

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#2685]
Now we need to use the "Devart.Data.Oracle.EFCore" for the spatial data, but the Abp does not provide the package for the "Devart", how to support it? Could you please give some guides for it? Thanks so much.
https://www.devart.com/dotconnect/oracle/

**Comment by maliming** [comment]
Please refer to the existing package, it's simple.
https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.EntityFrameworkCore.MySQL
https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.EntityFrameworkCore.PostgreSql

**Comment by jack-gaojz** [comment]
@maliming Thanks so much. :)
