### ISSUE TITLE
Connection Strings and database migrations (EF) - more detailed documentation

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2688]
https://docs.abp.io/en/abp/latest/Connection-Strings

![image](https://user-images.githubusercontent.com/39346964/72751530-22b0e780-3bc0-11ea-92d8-1c04b87938e5.png)

Better documentation (with examples) how to achieve grouping databases defined in modules into single database (or other gruping).

Modules don't have .DbMigrations project and it's not clear where to create and run migration? On module level or application level (if we take for instance BookStore-Modular sample-like).

**Comment by hikalkan** [comment]
Migrations and database groupings are managed by the final application.
If you will have 3 databases, you need to have 3 separate migration paths. I would create 3 .DbMigrations projects. A single .DbMigrator console app would be enough if you make it parametric to pass which migration to run.
This is the best practice as we thought on EF Core code first approach. If you have a better approach, please share, ABP can work with alternative ways if you have.

**Comment by hikalkan** [comment]
BTW, more document and tutorials will come.
