### ISSUE TITLE
Build the microservicedemo project   get version mismatch with the latest abp version v.2.0.0.0

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#2689]
Dears：
      when pull down the latest source code, and try to build the microservice demo project , i get the following compile error. please help me to figure out the issue.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'Volo.Abp.Core' with identity 'Volo.Abp.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Configuration.Abstractions' with identity 'Microsoft.Extensions.Configuration.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	ProductManagement.Domain.Shared	E:\Projects\abp\samples\MicroserviceDemo\modules\product\src\ProductManagement.Domain.Shared\ProductManagement\ProductManagementDomainSharedModule.cs	15	Active

```

**Comment by maliming** [comment]
Your problem cannot be reproduced in the latest code of the `dev `branch. You can try clean and rebuild.

```
dotnet clean
dotnet build
```

**Comment by johnnba** [comment]
yeah, i'm in the latest code of the `dev` branch. i've tried many times.

**Comment by maliming** [comment]
This should not happen if you haven't changed any code. : )

**Comment by johnnba** [comment]
sorry for this issue, but what i've cleaned and rebuilded is in the visual studio 2019 IDE, then it will throw the 1# error and exceptions. when i try the dotnet build commands ,it works well.
sincerely thanks. @maliming
