### ISSUE TITLE
ValueGeneratedNever assigned to all Id properties now

### ISSUE THREAD

**Issue by javiercampos** [abpframework/abp#2697]
Upon update to 2.0, our application started breaking badly when inserting many entities of the same type into our repositories or context without saving inbetween, the root cause is that now on `AbpDbContext` you add this:

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	base.OnModelCreating(modelBuilder);

	foreach (var entityType in modelBuilder.Model.GetEntityTypes())
	{
		/* ... */
		ConfigureValueGeneratedMethodInfo
			.MakeGenericMethod(entityType.ClrType)
			.Invoke(this, new object[] { modelBuilder, entityType });
	}
}
```
which calls this:

```c#
protected virtual void ConfigureValueGenerated<TEntity>(ModelBuilder modelBuilder, IMutableEntityType mutableEntityType)
	where TEntity : class
{
	/* ... */
	var idPropertyBuilder = modelBuilder.Entity<TEntity>().Property(x => ((IEntity<Guid>) x).Id);
	if (idPropertyBuilder.Metadata.PropertyInfo.IsDefined(typeof(DatabaseGeneratedAttribute), true))
	{
		return;
	}

	idPropertyBuilder.ValueGeneratedNever();
}

```

So now the id of the new `IEntity<Guid>` entities (with a default Id, or `Guid.Empty`) is only generated upon saving, but not upon adding to the context.

This fails when calling `SaveChanges` because you use the entity tracker, which detects that there are two entities of the same type with the same Id, before you get to the point where you generate the ids.

The workaround is simple, just add `ValueGeneratedOnAdd` for the ids on our derived `DbContext` **after** the base `OnModelCreating` has been called. Something like:

```c#
protected override void OnModelCreating(ModelBuilder builder)
{
	// Configure our model
	/* ... */
	
	// Let ABP do its configuration
	base.OnModelCreating(builder);
	
	// Reconfigure our Ids
	foreach (var entity in builder.Model.GetEntityTypes().Where(x => typeof(IEntity<Guid>).IsAssignableFrom(x.ClrType)))
	{
		builder.Entity(entity.ClrType).Property(typeof(Guid), "Id").ValueGeneratedOnAdd();
	}
}
```

I see a few problems:

1) Although `ValueGeneratedNever` is a valid choice, it forces you to specify an Id for each entity when creating
2) Point 1 is ok, but **it is a breaking change**, and I haven't seen any documentation (either on the release or anywhere else) for it
3) There is no way to configure the defaults (at least with fluent configuration: you take into account the `DatabaseGenerated` attribute but not the model state), they are added hard-coded on the `AbpDbContext`

Is this planned as a breaking change and just undocumented? Are there any plans to make the default configurable? Should we just assign our Ids when creating the entities and not let EF generate them at all?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/2450#issuecomment-568986527
https://github.com/abpframework/abp/pull/2470

**Comment by javiercampos** [comment]
I see. This slipped into the "others" pile in the release changelog, and not into "breaking changes".

Perfect, we'll workaround it ourselves then! 

Thanks

**Comment by Goxiaoy** [comment]
Is it able to set empty id of type `IEntity<Guid>`  automatically before inert? I notice that  IEntity<Guid> is set only for id?

**Comment by Goxiaoy** [comment]
I notice that in AbpDbContext So this funtion is broken when tring to add multiple none id set entities to dbcontext
https://github.com/abpframework/abp/blob/c708a7eb310acd6c0d318c8c48e764c6a311d01e/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L175

**Comment by javiercampos** [comment]
@Goxiaoy this is what this issue is about. I explicitly provided a workaround on the first post

**Comment by Goxiaoy** [comment]
@javiercampos Thanks a lot for your solution. Override `ConfigureValueGenerated` to config `ValueGeneratedOnAdd` will also work.
But there is one side effect. It leaves the database provider to decide id value generated from client or server( ref: https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations)

It may cause some inconsistent result when using different database provider
