### ISSUE TITLE
New React Native Mobile Application

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2699]
I want to annouce that the ABP Framework core team has started to work on a React Native application for the ABP Framework.

* It will simply login to the application using OAuth (as a client to the IdentityServer based backend).
* It will manage users in the system.
* It will share the same settings, localization, permissions...etc. in the server side.

So, it will be a good starting point for who want to create a react native application for their ABP based backends.

We decided to use [the expo](https://expo.io/) tooling [instead of standard CLI](https://stackoverflow.com/questions/54862388/what-is-the-difference-between-expo-cli-and-react-native-cli).

**Comment by myomyinthan** [comment]
Why not angular native script or angular ionic 4 ? 😁

**Comment by ryoldash** [comment]
Wow, great news. Then we will have the React Native integration for both [@aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4584) and @abpframework. @sametkabay @mhmtyasr

**Comment by MRashed** [comment]
Did you check Flutter ?
Highly recommend
https://flutter.dev/

**Comment by taichimeow** [comment]
😄 exciting news !  just what I wanted !

**Comment by mehmet-erim** [comment]
> Why not angular native script or angular ionic 4 ? 😁

React Native is more popular than NativeScript and Ionic.
![state-of-js-2019](https://2019.stateofjs.com/images/captures/mobile_desktop_experience_ranking.png)
[(The State of JavaScript 2019 result)](https://2019.stateofjs.com/mobile-desktop/)

React Native has a huge community. RN is more performant than Ionic. More React Native packages are published to NPM. So we have a lot of reasons to choose to React Native. These are just some reasons.

**Comment by ukocabicak** [comment]
It is definitely the right decision for me.

**Comment by ram16g** [comment]
> > Why not angular native script or angular ionic 4 ? 😁
> 
> React Native is more popular than NativeScript and Ionic.
> ![state-of-js-2019](https://camo.githubusercontent.com/a3e51b0330e81aa12f1b08c397ea119549fbcaef/68747470733a2f2f323031392e73746174656f666a732e636f6d2f696d616765732f63617074757265732f6d6f62696c655f6465736b746f705f657870657269656e63655f72616e6b696e672e706e67)
> [(The State of JavaScript 2019 result)](https://2019.stateofjs.com/mobile-desktop/)
> 
> React Native has a huge community. RN is more performant than Ionic. More React Native packages are published to NPM. So we have a lot of reasons to choose to React Native. These are just some reasons.



> > Why not angular native script or angular ionic 4 ? 😁
> 
> React Native is more popular than NativeScript and Ionic.
> ![state-of-js-2019](https://camo.githubusercontent.com/a3e51b0330e81aa12f1b08c397ea119549fbcaef/68747470733a2f2f323031392e73746174656f666a732e636f6d2f696d616765732f63617074757265732f6d6f62696c655f6465736b746f705f657870657269656e63655f72616e6b696e672e706e67)
> [(The State of JavaScript 2019 result)](https://2019.stateofjs.com/mobile-desktop/)
> 
> React Native has a huge community. RN is more performant than Ionic. More React Native packages are published to NPM. So we have a lot of reasons to choose to React Native. These are just some reasons.
I think it is better to keep the angular technology stack instead of introducing react

**Comment by hikalkan** [comment]
We know making everybody happy is impossible and a decision can not be 100% true.
We are working on the react native now.
Based on the feedback and other priorities, we may build other mobile application templates too.
Also, community can contribute (like they did Vue and React UIs for the [AspNet Boilerplate](https://aspnetboilerplate.com/Templates)) and it is appreciated :)

**Comment by ryoldash** [comment]
React-Native is one of the leading mobile framework for mobile app development, so I appreciate your choice for developing New React-Native Mobile App for ABP backend. 

After completing the React Native integration for [AspNet Boilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4584) we are planning to implement ABP frameworks new ReactJS UI as well. So we can create a new issue for creating New ReactJS UI in @abpframework and assign us :) 

We are glad to be contributors of @abpframework and AspNet Boilerplate. @hikalkan @ismcagdas 
@sametkabay @mhmtyasr
