### ISSUE TITLE
Transactional & SuppressTransaction attibutes

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#270]
#### TransactionalAttribute

It can be used for a method/class and controls/starts a transactional scope.

Additional options:
- Transaction timeout
- Isolation level
- bool requiresnew

#### SuppressTransactionAttribute

It can be used for a method/class and disble transaction for a scope (and create a non-transactional scope).

Instead of UnitOfWorkAttribute, we can use these attributes to be more clear.

**Comment by dicksonkimeu** [comment]
was this abandoned ?

**Comment by hikalkan** [comment]
No, we'll consider for 3.0 since it is a breaking change. However, this is just a usage change, same functionality is already currently available.

**Comment by talhazengin** [comment]
Current UnitOfWork attribute, does not supply RequiresNew feature. Can't we consider such a thing?

**Comment by leonkosak** [comment]
I use requiresNew in code (ignore isTransactional, because I made copy/paste from my code)

```
using (var uow = _unitOfWorkManager.Begin(requiresNew: true, isTransactional: true))
{
   ...
   await uow.CompleteAsync();
}
```

**Comment by talhazengin** [comment]
@leonkosak I mean this attribute: https://github.com/abpframework/abp/blob/78e396a27b8a4e9c2d69880fae5ad9b3b306c5d6/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkAttribute.cs

I know we can use it explicitly coding.
