### ISSUE TITLE
IDistributedEventHandler not being triggered

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#2701]
I am using abp 2.0.0, trying to use RabbitMq.
I connected to the RabbitMq, created a class which inherits from EtoBase, called the AddDistributedEvent however nothing shows up on the RabbitMq Manager and the class which implements the IDistributedEventHandler is not being called at all.

What exactly am I missing?

**Comment by acjh** [comment]
Is your aggregate root (entity) successfully saved?

**Comment by ZouZou** [comment]
what exactly do you mean by saved? saved to the DB? I am testing the class without saving anything to the db

**Comment by acjh** [comment]
Yes, I mean saved to the DB.

Distributed events are triggered after `SaveChanges`/`SaveChangesAsync`. See https://github.com/abpframework/abp/issues/2433#issuecomment-568159017.

**Comment by ZouZou** [comment]
I got it to work without saving to the DB, it seems that my issue was that the handler had to implement the ITransient
