### ISSUE TITLE
Oracle 11g: the identifier name can not more than 30 characters

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#2704]
When I use the Oracle 11g to generate the database, the error message as below:
'Column name 'AlwaysIncludeUserClaimsInIdToken' in table "IdentityServerClients" is too long (32 characters). An identifier with more than 30 characters was specified.'

**Comment by maliming** [comment]
Duplicate of #1920

**Comment by Monodytheone** [comment]
@jack-gaojz-zz  Could you please explain your solution to me? I'm unable to understand it just from issue #1920 . I would greatly appreciate.
