### ISSUE TITLE
Change style template

### ISSUE THREAD

**Issue by shrimpwang** [abpframework/abp#2705]
hello,@maliming

![1](https://user-images.githubusercontent.com/57536643/72973734-bd036c00-3e08-11ea-890f-696eb164de13.png)

I created the project and wanted to modify the current Login and register all the interface styles, but I couldn't find /Account/Login

I want to more to http://8b77c880f7587eeb.demo.commercial.abp.io/init-demo?Theme =Style1 the same interface style,

thank you

**Comment by maliming** [comment]
hi 
The project downloaded by abp.io has a simple bootstrap theme by default. 

You mentioned the theme of the abp commercial(https://commercial.abp.io)

**Comment by shrimpwang** [comment]
Default theme, how to modify?
thank you

**Comment by shrimpwang** [comment]
The front page of the /Account/Login page could not be found
Happy New Year

**Comment by maliming** [comment]
` /Account/Login` page exist in the account module.  https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml

> Default theme, how to modify?

see https://github.com/abpframework/abp/issues/631#ref-issue-503873626
![image](https://user-images.githubusercontent.com/6908465/73038257-b3234c80-3e8c-11ea-812a-d0348d9c51a6.png)

**Comment by shrimpwang** [comment]
ok， thank you
