### ISSUE TITLE
bootstrap-datepicker forces modal to close when a date is being selected.

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#2706]
When the [bootstrap-datepicker ](https://github.com/uxsolutions/bootstrap-datepicker) is used within a Bootstrap Modal dialog, the 'hide' event of the datepicker forces the modal dialog to close!
There's an open issue on their repo https://github.com/uxsolutions/bootstrap-datepicker/issues/810

---
**Repro steps:**
Open volo\abp\samples\BookStore-MVC solution
-    Run the project
-    Click edit action on a record
-    Open developer console and run the below
-    $("input[type='datetime-local']").datepicker({format: 'yyyy-mm-ddT00:00'});
-    When you select a date, it forces to close the modal

![image](https://user-images.githubusercontent.com/9526587/72982342-e1068380-3def-11ea-99d7-f413d97c7203.png)

**Comment by yekalkan** [comment]
Current solution until datepicker lib natively fixes this issue:

```
$("#my-datepicker").datepicker().on('show.bs.modal', function(event) {   event.stopPropagation(); });
```

**Comment by wakuflair** [comment]
My worked solution is attached to the `hide` event:

``` js
            $("#my-datepicker").datepicker().on('hide', function (event) {
                event.stopPropagation();
            });
```
