### ISSUE TITLE
[Question] Permission Manager

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#2711]
I would like to know how to access the permission manager dialog in abp
When I run the IdentityServer project, I log in as an Admin but I cannot access the Permission Management dialog.
The question might seem silly at this point but still I would appreciate the help.

**Comment by hikalkan** [comment]
Permission management module is used by the Identity module to manage the permissions of the users and roles. So, go the the users page, click to the actions of a user and click to the manage permissions.

You normally don't need to directly open it. Do you need?

**Comment by ZouZou** [comment]
I kind of figured that much after following the dependencies of the modules.
Reached the understanding that the web.host project is the project able to show me the users, roles and permissions.
however, whenever I run it, it only shows the login button and when i click it I get an error. According to the IndentityServer logs, the problem is with the openid and profile scope
