### ISSUE TITLE
In MVC  Project Tired Application Error

### ISSUE THREAD

**Issue by pranavpatil19** [abpframework/abp#2715]
In MVC  Project Tired Application Registration Process Not Working

**Comment by ismcagdas** [comment]
@pranavpatil19 is there any error message in the server side log file ?

**Comment by pranavpatil19** [comment]
API work fine but... from front end registration form  in identity server ... if i enter username email and password after submit request .. it redirect to web page and give 400 errror and registration fail

**Comment by maliming** [comment]
hi @pranavpatil19 Please check and share the logs of the application.

**Comment by pranavpatil19** [comment]
@maliming  i remove all log file and follow registration process. error resolve ..
i think its a cache issue.
