### ISSUE TITLE
Bug in Sample DashboardDemo

### ISSUE THREAD

**Issue by Gosha24** [abpframework/abp#2716]
I'm playing with sample DashboardDemo. When i run it in Debug mode i get exception in line
 app.UseVirtualFiles(); in DashboardDemoWebModule. I commented out lines 
                Configure<AbpVirtualFileSystemOptions>(options =>
                {
                    //options.FileSets.ReplaceEmbeddedByPhysical<AbpAspNetCoreMvcUiThemeSharedModule>(Path.Combine(hostingEnvironment.ContentRootPath, string.Format("..{0}..{0}..{0}..{0}framework{0}src{0}Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared", Path.DirectorySeparatorChar)));
                    //options.FileSets.ReplaceEmbeddedByPhysical<DashboardDemoDomainSharedModule>(Path.Combine(hostingEnvironment.ContentRootPath, string.Format("..{0}DashboardDemo.Domain.Shared", Path.DirectorySeparatorChar)));
                    //options.FileSets.ReplaceEmbeddedByPhysical<DashboardDemoDomainModule>(Path.Combine(hostingEnvironment.ContentRootPath, string.Format("..{0}DashboardDemo.Domain", Path.DirectorySeparatorChar)));
                    //options.FileSets.ReplaceEmbeddedByPhysical<DashboardDemoApplicationContractsModule>(Path.Combine(hostingEnvironment.ContentRootPath, string.Format("..{0}DashboardDemo.Application.Contracts", Path.DirectorySeparatorChar)));
                    //options.FileSets.ReplaceEmbeddedByPhysical<DashboardDemoApplicationModule>(Path.Combine(hostingEnvironment.ContentRootPath, string.Format("..{0}DashboardDemo.Application", Path.DirectorySeparatorChar)));
                    //options.FileSets.ReplaceEmbeddedByPhysical<DashboardDemoWebModule>(hostingEnvironment.ContentRootPath);
                });
as was recomended in issue 	274188A .Then i get next exception in line
         var myGroup = context.AddGroup(DashboardDemoPermissions.GroupName);
in file DashboardDemoPermissionDefinitionProvider
I commented out this line then everything works. 
It looks like this code was not renewed from previous versions.

**Comment by yekalkan** [comment]
I encountered none of these problems. I can check again if you provide more detailed reproduction steps.

**Comment by Gosha24** [comment]
1 Copy sample from source repository
2) I changed all references on framework and module projects in .csproj files to references on NugetPackages with latest version 2/0/1 . 
3) All standard steps with migration of DB
4) Run DasboardDemo.Web
5) First exception in app.UseVirtualFiles();
6) Commented  Configure(options => as shown before
7) Next run
8) exception in  var myGroup = context.AddGroup(DashboardDemoPermissions.GroupName);
Volo.Abp.AbpException
  HResult=0x80131500
  Message=There is already an existing permission group with name: DashboardDemo
  Source=Volo.Abp.Authorization
  StackTrace:
   at Volo.Abp.Authorization.Permissions.PermissionDefinitionContext.AddGroup(String name, ILocalizableString displayName, MultiTenancySides multiTenancySide)
   at DashboardDemo.Permissions.DashboardDemoPermissionDefinitionProvider.Define(IPermissionDefinitionContext context) in E:\temp\Azure\WpfDev\DashboardDemo\src\DashboardDemo.Application\Permissions\DashboardDemoPermissionDefinitionProvider.cs:line 11
   at Volo.Abp.Authorization.Permissions.PermissionDefinitionManager.CreatePermissionGroupDefinitions()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

**Comment by hikalkan** [comment]
@yekalkan can you check it again?

**Comment by yekalkan** [comment]
> 5) First exception in app.UseVirtualFiles();

Pretty normal. You changed ProjectReferences to PackageReferenceses and therefore you can't use `ReplaceEmbeddedByPhysical` method anymore.

> Message=There is already an existing permission group with name: DashboardDemo

That is strange. You can delete **DashboardDemoPermissionDefinitionProvider.cs** file and try again.

**Comment by Gosha24** [comment]
I deleted DashboardDemoPermissionDefinitionProvider.cs . Exception disappeared

**Comment by JohnnyZhang0628** [comment]
I also encountered this problem
![image](https://user-images.githubusercontent.com/28375774/93981500-a7d54780-fdb2-11ea-84b7-cd3ec6d956f3.png)
I Commented configure code, and deleted DashboardDemoPermissionDefinitionProvider.cs .It still not work.What should i do?
```
// options.FileSets.ReplaceEmbeddedByPhysical<AbpAspNetCoreMvcUiThemeSharedModule>(Path.Combine(hostingEnvironment.ContentRootPath, string.Format("..{0}..{0}..{0}..{0}abp{0}framework{0}src{0}Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared", Path.DirectorySeparatorChar)));
```
