### ISSUE TITLE
Missing column definitions in ModelBuilder configs causing issues with Oracle database

### ISSUE THREAD

**Issue by abdusco** [abpframework/abp#2717]
Hey,
I'm trying to use Oracle Server (Oracle Database 12c Enterprise Edition Release 12.2.0.1.0) using DevArt EF Core driver (Devart.Data.Oracle.EFCore 9.10.909) on .NET Core 3.1.1 with Abp 2.0.1 https://github.com/abpframework/abp/releases/tag/2.0.1. 

When I try to apply migrations using:
```
path\to\project\src>dotnet ef database update -v -s MyProject.DbMigrator -p MyProject.EntityFrameworkCore.DbMigrations
```
I get this error
<details>
<summary>click to view the log output</summary>
<pre>
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='0']
CREATE TABLE "AbpAuditLogs" ( 
  "Id" RAW(16) NOT NULL,
  "ExtraProperties" NVARCHAR2 NULL,
  "ConcurrencyStamp" NVARCHAR2 NULL,
  "ApplicationName" NVARCHAR2(96) NULL,
  "UserId" RAW(16) NULL,
  "UserName" NVARCHAR2(256) NULL,
  "TenantId" RAW(16) NULL,
  "TenantName" NVARCHAR2 NULL,
  "ImpersonatorUserId" RAW(16) NULL,
  "ImpersonatorTenantId" RAW(16) NULL,
  "ExecutionTime" TIMESTAMP(7) NOT NULL,
  "ExecutionDuration" NUMBER(10) NOT NULL,
  "ClientIpAddress" NVARCHAR2(64) NULL,
  "ClientName" NVARCHAR2(128) NULL,
  "ClientId" NVARCHAR2(64) NULL,
  "CorrelationId" NVARCHAR2(64) NULL,
  "BrowserInfo" NVARCHAR2(512) NULL,
  "HttpMethod" NVARCHAR2(16) NULL,
  "Url" NVARCHAR2(256) NULL,
  "Exceptions" NVARCHAR2(4000) NULL,
  "Comments" NVARCHAR2(256) NULL,
  "HttpStatusCode" NUMBER(10) NULL,
  PRIMARY KEY ("Id")
)
Failed executing DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
CREATE TABLE "AbpAuditLogs" ( 
  "Id" RAW(16) NOT NULL,
  "ExtraProperties" NVARCHAR2 NULL,
  "ConcurrencyStamp" NVARCHAR2 NULL,
  "ApplicationName" NVARCHAR2(96) NULL,
  "UserId" RAW(16) NULL,
  "UserName" NVARCHAR2(256) NULL,
  "TenantId" RAW(16) NULL,
  "TenantName" NVARCHAR2 NULL,
  "ImpersonatorUserId" RAW(16) NULL,
  "ImpersonatorTenantId" RAW(16) NULL,
  "ExecutionTime" TIMESTAMP(7) NOT NULL,
  "ExecutionDuration" NUMBER(10) NOT NULL,
  "ClientIpAddress" NVARCHAR2(64) NULL,
  "ClientName" NVARCHAR2(128) NULL,
  "ClientId" NVARCHAR2(64) NULL,
  "CorrelationId" NVARCHAR2(64) NULL,
  "BrowserInfo" NVARCHAR2(512) NULL,
  "HttpMethod" NVARCHAR2(16) NULL,
  "Url" NVARCHAR2(256) NULL,
  "Exceptions" NVARCHAR2(4000) NULL,
  "Comments" NVARCHAR2(256) NULL,
  "HttpStatusCode" NUMBER(10) NULL,
  PRIMARY KEY ("Id")
)
Disposing transaction.
Closing connection to database '' on server 'SECRET_DSN'.
Closed connection to database '' on server 'SECRET_DSN'.
'MyProjectMigrationsDbContext' disposed.
Devart.Data.Oracle.OracleException (0x80004005): ORA-00906: missing left parenthesis
   at ═  .╚(Int32 ╗)
   at ║  .╚(Int32 ╗)
   at ║  .╗      ╗(Int32 ╗,    ╚)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.OracleCommand.ExecuteNonQuery()
   at Devart.Common.Entity.cu.ExecuteNonQuery()
   at Devart.Data.Oracle.Entity.aj.h()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ORA-00906: missing left parenthesis
</pre>
</details>

The problem is that `ExtraProperties`, `ConcurrencyStamp`, `TenantName` columns don't have a max length like `nvarchar2(256)`. This is a bug caused by the DevArt Oracle driver not complaining when a column is missing `.HasMaxLength(<length>)` declaration, and consequently generating invalid SQL. 

Here are the SQL syntax errors and locations:
![image](https://user-images.githubusercontent.com/3243482/73158811-03e9ae00-40f6-11ea-94b6-6cc0fc82be5e.png)

I've reported the issue at [DevArt forums](https://forums.devart.com/viewtopic.php?f=30&t=39808&p=145079) as well, but a quick solution to the problem might come from simply adding missing column definitions in `Volo.Abp.AuditLogging.EntityFrameworkCore.AbpAuditLoggingDbContextModelBuilderExtensions.ConfigureAuditLogging` method (**and similarly other entities**).

https://github.com/abpframework/abp/blob/110f015d38b48c7636d89dc31eacd01202134b47/modules/audit-logging/src/Volo.Abp.AuditLogging.EntityFrameworkCore/Volo/Abp/AuditLogging/EntityFrameworkCore/AbpAuditLoggingDbContextModelBuilderExtensions.cs#L11-L103

In this method, there are 18 column declarations for [`AuditLog`](https://github.com/abpframework/abp/blob/110f015d38b48c7636d89dc31eacd01202134b47/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain/Volo/Abp/AuditLogging/AuditLog.cs) entity, whereas it has at the moment 22 properties.

These 3 missing declarations result in `nvarchar2` without a max length.  
(notice that there are many entities with same issue in the same migration file.)

https://github.com/abpframework/abp/blob/832a2b91d9f95221cceb23c595ae293b5ef08b6b/samples/BookStore-Modular/modules/book-management/host/Acme.BookStore.BookManagement.Web.Unified/Migrations/20200106082340_Initial.cs#L21

**Comment by abdusco** [comment]
Ok, syntax errors in generated SQL scripts seem to be caused by the assumption of ABP CLI (and also the sample projects) that MSSQL server will be used. This is indeed the case, because generated projects use sqllocaldb by default. But it'd be nice to have a warning in docs for this. I might send a PR for it.

Removing the migration files in `.\src\MyProject.EntityFrameworkCore.DbMigrations\Migrations`, then regenerating them using 

```cmd
cd path\to\project\src
dotnet ef migrations add Initial -s MyProject.DbMigrator -p MyProject.EntityFrameworkCore.DbMigrations
```

will generate syntactically correct SQL script in Oracle dialect.


However, this does **not** solve the problem.  
Now, due to having columns with max-length set to 4000, this size exceeds max allowed `nvarchar2` column size in Oracle (bypassing this limit requires [risky and potentially breaking changes][oracle]). Here's an example of column size of 4000 (similar constants are distributed throught the codebase in `___Consts.cs` files):

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain.Shared/Volo/Abp/AuditLogging/AuditLogConsts.cs#L17

This issue requires changes in upstream by ABP team to be solved, or having to take production database offline, which frankly won't be easy to get an approval for. 

I'm open to suggestions.

[oracle]: https://docs.oracle.com/database/121/REFRN/GUID-D424D23B-0933-425F-BC69-9C0E6724693C.htm#REFRN10321

**Comment by maliming** [comment]
hi @abdusco 

You can take look this issue: https://github.com/abpframework/abp/issues/1920

**Comment by abdusco** [comment]
@maliming I've been trying to override column configuration set by ABP to fit Oracle constraints, but I've encountered yet another issue with DevArt.

It seems that DevArt driver fails to convert fields of `enum` type to their value type.  
One example: 

https://github.com/abpframework/abp/blob/cc8fd28e5d1c37f8bdb4ac66c5c6f7f35d5f4b74/modules/background-jobs/src/Volo.Abp.BackgroundJobs.EntityFrameworkCore/Volo/Abp/BackgroundJobs/EntityFrameworkCore/BackgroundJobsDbContextModelCreatingExtensions.cs#L35

After generating migration files with

```
dotnet ef migrations add Init -v -s MyProject.DbMigrator -p MyProject.EntityFrameworkCore.DbMigrations -c MyProjectMigrationsDbContext
```

I get:

```c# 15
// .\src\MyProject.DbMigrations\Migrations\20200131072446_Init.cs

migrationBuilder.CreateTable(
    name: "AbpBackgroundJobs",
    columns: table => new
    {
        ...
        Priority = table.Column<byte>(nullable: false, defaultValue: BackgroundJobPriority.Normal)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_AbpBackgroundJobs", x => x.Id);
    });
```

and

```c#
// .\src\MyProject.DbMigrations\Migrations\MyProjectMigrationsDbContextModelSnapshot.cs
b.Property<BackgroundJobPriority>("Priority")
    .ValueGeneratedOnAdd()
    .HasColumnType("byte")
    .HasDefaultValue(BackgroundJobPriority.Normal);
```

Applying these migrations with 

```
dotnet ef database update -v -s MyProject.DbMigrator -p MyProject.EntityFrameworkCore.DbMigrations -c MyProjectMigrationsDbContext
```

gives me this error:

```
System.InvalidOperationException: Cannot set default value '15' of type 'System.Int32' on property 'Priority' of type 'Volo.Abp.BackgroundJobs.BackgroundJobPriority' in entity type 'BackgroundJobRecord'.
```

DevArt driver seems to convert `enum` to its base type `byte`, but leaves enum values as their string representations.

<details>
<summary>click to see stack trace</summary>
<pre>
Failed executing DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
CREATE TABLE "AbpBackgroundJobs" (
  "Id" RAW(16) NOT NULL,
  "ExtraProperties" NCLOB NULL,
  "ConcurrencyStamp" NCLOB NULL,
  "JobName" NVARCHAR2(128) NOT NULL,
  "JobArgs" NCLOB NOT NULL,
  "TryCount" NUMBER(5) DEFAULT 0 NOT NULL,
  "CreationTime" TIMESTAMP(7) NOT NULL,
  "NextTryTime" TIMESTAMP(7) NOT NULL,
  "LastTryTime" TIMESTAMP(7) NULL,
  "IsAbandoned" NUMBER(1) DEFAULT 0 NOT NULL,
  "Priority" NUMBER(3) DEFAULT Normal NOT NULL,
  PRIMARY KEY ("Id")
)
Disposing transaction.
Closing connection to database '' on server 'ORACLE_DSN'.
Closed connection to database '' on server 'ORACLE_DSN'.
'MyProjectMigrationsDbContext' disposed.
Devart.Data.Oracle.OracleException (0x80004005): ORA-00904: "NORMAL": invalid identifier
   at ═  .╚(Int32 ╗)
   at ║  .╚(Int32 ╗)
   at ║  .╗      ╗(Int32 ╗,    ╚)
   at Devart.Data.Oracle.OracleCommand.InternalExecute(CommandBehavior behavior, IDisposable disposable, Int32 startRecord, Int32 maxRecords, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Data.Oracle.OracleCommand.ExecuteNonQuery()
   at Devart.Common.Entity.cu.ExecuteNonQuery()
   at Devart.Data.Oracle.Entity.aj.h()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IR
elationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ORA-00904: "NORMAL": invalid identifier
</pre>
</details>

and still manages to generate invalid SQL!

```sql
CREATE TABLE "AbpBackgroundJobs" (
  ...
  "Priority" NUMBER(3) DEFAULT Normal NOT NULL,
  ...
)
```

**Comment by hikalkan** [comment]
It would be better if we can try with oracle.

**Comment by maliming** [comment]
[Oracle.EntityFrameworkCore](https://www.nuget.org/packages/Oracle.EntityFrameworkCore) does not yet support  .NET Core 3.1.
DevArt  supports .NET Core 3.1 but it is a paid product.

**Comment by dicksonkimeu** [comment]
I think we should implement compatibility for ms SQL, my SQL, postgres and oracle out of the box.

**Comment by dicksonkimeu** [comment]
This means we can't use Devart ? Because of this errors

**Comment by maliming** [comment]
@dicksonkimeu  https://github.com/abpframework/abp/issues/2717#issuecomment-581133553

**Comment by dicksonkimeu** [comment]
> [Oracle.EntityFrameworkCore](https://www.nuget.org/packages/Oracle.EntityFrameworkCore) does not yet support .NET Core 3.1.
> DevArt supports .NET Core 3.1 but it is a paid product.

Without the above quoted errors ?

**Comment by hikalkan** [comment]
is there still a problem after https://gist.github.com/ebicoglu/9f364c7eff9d87315af0178866186401 ?

**Comment by hikalkan** [comment]
I am closing this. See: https://github.com/abpframework/abp/issues/3983
