### ISSUE TITLE
How to add a module to the framework?

### ISSUE THREAD

**Issue by kurtwilbies** [abpframework/abp#2718]
If you develop a module, what are the correct steps to incorporate te module in the framework. And how to incorporate the provided sample modules in the framework. There is a cli cmd, but its too unclear.

**Comment by leonkosak** [comment]
Via CLI or "manually" ([look this](https://github.com/abpframework/abp/issues/2654#issuecomment-575091535)).

**Comment by kurtwilbies** [comment]
@leonkosak Your answer is too cryptic. What are steps before and after.

**Comment by leonkosak** [comment]
I suggest, that you look at BookStore-Modular example: https://github.com/abpframework/abp/tree/dev/samples/BookStore-Modular

If you decide to go "manual way":

1) create application
2) create module
3) based on my link, make connections from application .csproj files to module's .csproj files
4) build module solution
5) in application project files [xyz]Module.cs add imports in DependsOn

These are quick "orientational" steps.

**Comment by kurtwilbies** [comment]
I follwed the instructions and added the bnlogging module, but where is the fronend part. The backend was easy to install.

**Comment by viewtance** [comment]
Any guideline to install the front end of both docs and blogging modules? I have installed the docs module via CLI, but cannot find the front end changes.

**Comment by hikalkan** [comment]
Have you seen this: https://docs.abp.io/en/abp/latest/Modules/Docs

**Comment by kurtwilbies** [comment]
This is more for a mvc app. If you want to add angular as the framework of choice.
