### ISSUE TITLE
Best practices developing custom frontend!

### ISSUE THREAD

**Issue by kurtwilbies** [abpframework/abp#2719]
I managed to custom the frontend, but I got some errors. Is there an easy way to customize the frontend. An easy step by step guide, tut, video, whatever... without n easy way to customize the frontend abp is useless.

**Comment by vd3d** [comment]
I think that you have several options, but nothing seems documented yet:

- create a new theme
- create a module and override the existing pages (with the Virtual File System)
- I'm not, maybe it is also possible to customize the 'abp-button' etc ...

If you find a better, let us know and/or maybe it will be fine to add it to the documentation ;-)
