### ISSUE TITLE
MultiTenancyMiddleware : issues at registration

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2720]
Hi,

I have create a sample project (with the generator), then in the "Web" one I wish to completely redo the project (I'm creating a blazor sample, without admin etc...)

then I remove the following dependency:

typeof(AbpTenantManagementWebModule)

And at launch I got an error :

`ComponentNotRegisteredException: The requested service 'Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.`

But I still have the following instruction : app.UseMultiTenancy();

So, what can be the problem ?

**Comment by acjh** [comment]
Did you add `[DependsOn(typeof(AbpMultiTenancyModule))]`?
Documentation: https://docs.abp.io/en/abp/latest/Multi-Tenancy

**Comment by vd3d** [comment]
Yes, I have :-(

What is strange is that I add the middleware, no exception... and later it ask for it !

**Comment by acjh** [comment]
Which version of `Volo.Abp.AspNetCore.MultiTenancy` are you on?

**Comment by vd3d** [comment]
Version 2.0.0

**Comment by acjh** [comment]
Try to add `DefaultConventionalRegistrar` in your module's `PreConfigureServices` method:

```c#
services.AddConventionalRegistrar(new DefaultConventionalRegistrar());
```

**Comment by vd3d** [comment]
Unfortunately, it does not help :-(

**Comment by hikalkan** [comment]
You may need to add `AbpAspNetCoreMultiTenancyModule` to your module's dependency list.
Actually, you also need to add AbpTenantManagementHttpApiModule to be able to use the HTTP API.
