### ISSUE TITLE
Property IsDefault of entity IdentityRole not implemented

### ISSUE THREAD

**Issue by HenroOnline** [abpframework/abp#2721]
When creating a new Role there is the property IsDefault. The comments for this property are:
_A default role is automatically assigned to a new user_

But when I am registering or creating a new user from the Administration within the demo app (Angular in my case), these roles are not assigned to the new user.

**Comment by mehmet-erim** [comment]
Did you try that in ABP Angular v2.0.1?

To reinstall packages, you can remove `yarn.lock` file and run the `yarn` in the root Angular application folder.

**Comment by HenroOnline** [comment]
I have updated the NPM packages and NuGet packages to v2.0.1.
When I create a user through the administration in de default roles are selected in the UI. 
But when I create an account (self registration) these roles are not assigned, is this by design?

And when I open the user (which I created through self registration) in the administration, the default roles are selected. I expected the default roles only selected when creating a new user, not when editing an existing user.

**Comment by johnnba** [comment]
yes, i have the same problem with @HenroOnline . 
i used the latest version 2.0.1 and called directly create new user api , but didn't have the permission of the default role. @mehmet-erim 。
it seems not fixed in ABP Angular v2.0.1?

**Comment by mehmet-erim** [comment]
Sorry, my bad. I'll be fixed.

**Comment by gdlcf88** [comment]
This is really a important problem. I tested default roles feature before, and I remember it works in abp v0.19.
