### ISSUE TITLE
Language switching failed

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#2724]
No matter which language you switch, only English will be returned.

live demo have same problem: https://commercial.abp.io/

**Comment by maliming** [comment]
> No matter which language you switch, only English will be returned.

I can't reproduce the problem in a project with version 2.0.1.

> live demo have same problem

The commercial version does have this problem, and we are working on it.

**Comment by Loongle** [comment]
@maliming I remember that I was supposed to print the corresponding language prompt, am I wrong? 😢
![image](https://user-images.githubusercontent.com/7290992/73354155-fab43900-42cf-11ea-8e48-0942d3b1e068.png)

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1119
