### ISSUE TITLE
AbpRemoteCallException when running Web project

### ISSUE THREAD

**Issue by abdumostafa** [abpframework/abp#2726]
I had a tiered application, APIs are working fine but when I Run the Web I got from no where

> An unhandled exception occurred while processing the request.
> AbpRemoteCallException: An internal error occurred during your request!
> Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor<TService>.ThrowExceptionForResponseAsync(HttpResponseMessage response)

**This is my stacktrace:**

> Volo.Abp.Http.Client.AbpRemoteCallException: An internal error occurred during your request!
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo)
>    at Volo.Abp.AspNetCore.Mvc.Client.CachedApplicationConfigurationClient.<GetAsync>b__13_0()
>    at Volo.Abp.Caching.DistributedCache`2.GetOrAddAsync(TCacheKey key, Func`1 factory, Func`1 optionsFactory, Nullable`1 hideErrors, CancellationToken token)
>    at Volo.Abp.AspNetCore.Mvc.Client.CachedApplicationConfigurationClient.GetAsync()
>    at Volo.Abp.AspNetCore.Mvc.Client.RemoteLanguageProvider.GetLanguagesAsync()
>    at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
>    at Nito.AsyncEx.AsyncContext.<>c__DisplayClass16_0`1.<Run>b__0(Task`1 t)
>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location where exception was thrown ---
>    at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
>    at Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
>    at Volo.Abp.Threading.AsyncHelper.RunSync[TResult](Func`1 func)
>    at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.<>c__DisplayClass3_0.<InitLocalizationOptions>b__0()
>    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.get_Value()
>    at Microsoft.AspNetCore.RequestLocalization.DefaultAbpRequestLocalizationOptionsProvider.GetLocalizationOptions()
>    at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
>    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I even tried debugging the `DynamicHttpProxyInterceptor` with dotPeek but never hit the breakpoint on that interceptor even It's working on other Volo.* files !

**Comment by maliming** [comment]
If you are using Tiered Structure :

**You should run the application with the given order:**

* First, run the .IdentityServer since other applications depends on it.
* Then run the .HttpApi.Host since it is used by the .Web application.
* Finally, you can run the .Web project and login to the application (using admin as the username and 1q2w3E* as the password).

https://github.com/abpframework/abp/blob/dev/docs/en/Startup-Templates/Application.md#how-to-run-1

**Comment by abdumostafa** [comment]
@maliming I am already running them in the correct order, I need more info about how this interceptor is being called by the web project

**Comment by abdumostafa** [comment]
@maliming @hikalkan 
After long investigations and commit compares, there was a comma **,** missing in a resource file **en.json** which leads to this Exception, however the Exception was a way misleading and confusing and leads to nothing.
```
{
  "culture": "en",
  "texts": {
    "Menu:Home": "Home",
    "Welcome": "Welcome",
    "LongWelcomeMessage": "Welcome to the application. For more information, visit abp.io."
    "Etimad.Domain:EX-8": "The invoice number you filled already exists in the system"
  }
}
```
we need either a compile time error on these resource files or a meaningful exception when serializing them. 😃

**Comment by maliming** [comment]
hi @abdumostafa 

The detailed error is in the log of the API project (HttpApi.Host)

eg:
```
[ERR] Can not parse json string. After parsing a value an unexpected character was encountered
```
