### ISSUE TITLE
Question Angular template: Is there any function available to check if user has permission

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2737]
Angular template v2.0.1

I need to hide or disable components, I need something to check policies and act like so:

````xml
<div disabled="hasPermission('Permission:PropostaAlterarComissao')">
...
</div>
<div *ngIf="hasPermission('Permission:PropostaAlterarComissao')">

</div>
````

Is there any way to do this, using directive, service, something?

**Comment by ismcagdas** [comment]
@thiag0coelho do you mean permissions ?

**Comment by hikalkan** [comment]
Yes, there is such a feature. See its usage: https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/identity/src/lib/components/users/users.component.html#L9

**Comment by hikalkan** [comment]
@mehmet-erim can you write for different use cases?

**Comment by thiag0coelho** [comment]
@hikalkan That worked for hiding. Thanks! 
It'll be nice if there's anything to disable components also. :)

**Comment by mehmet-erim** [comment]
You can use the `PermissionDirective` to manage the permission of a DOM element. It can be used in two ways.

Attiribute usage:
```html
<button abpPermission="Type here a policy key e.g: AbpIdentity.Users.Create">Create a new user</button>
```

Structural usage:
```html
<button *abpPermission="'Type here a policy key'">Create a new user</button>
```
>You should use the structural usage when you would like to hide a component.

You can also manage the permission of a route with `PermissinGuard`:
```ts
import { PermissionGuard } from '@abp/ng.core';
// ...
{
  path: 'your-route-path',
  component: YourComponent
  canActivate: [PermissionGuard],
  data: {
    routes: {
      requiredPolicy: 'Type here a policy key',
    },
  },
}
```

### To disable a DOM element

Add a select decorator to your component as shown below:

```ts
import { ConfigState } from '@abp/ng.core';
import { Select } from '@ngxs/store';
// ...
export class YourComponent {
  @Select(ConfigState.getGrantedPolicy('Type here a policy key'))
  createButtonPermission$: Observable<boolean>
// ...
```

Use `disabled` attiribute on a DOM element like this:
```html
<button [disabled]="!(createButtonPermission$ | async)">Create new</button>
```

**Comment by luisp88** [comment]
Is there a way to use OR/AND within *abpPermission? Thats because I have a "more actions" menu button that shows edit and delete buttons, and want to hide the menu button if cannot edit and delete

**Comment by mehmet-erim** [comment]
@luisp88 You can use permission directive like this:

```html
*abpPermission="'YourModule.Edit || YourModule.Delete'"

or

*abpPermission="'YourModule.Edit && YourModule.Delete'"
```

For further information, see the [permission management documentation](https://docs.abp.io/en/abp/latest/UI/Angular/Permission-Management)

You can also get permissions manually via `getGrantedPolicy ` selector of ConfigState. See https://docs.abp.io/en/abp/latest/UI/Angular/Config-State#how-to-get-a-specific-permission-from-the-store
