### ISSUE TITLE
Angular template: Not possible to make Administration as parent route

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2738]
Tried to create a sub menu for Administration and it doesn't have url

Used the code above in app.component.ts (is it the right place to add routes?)

```
    this.store.dispatch(
      new AddRoute({
        name: "My new page",
        iconClass: "fa fa-dashboard",
        path: "page",
        invisible: false,
        order: 2,
        parentName: "AbpUiNavigation::Menu:Administration"
      } as Omit<ABP.Route, "children">)
    );
```

![image](https://user-images.githubusercontent.com/6138475/73595810-4565c900-44fb-11ea-9fcf-bdcf054621d5.png)

It throws an error for not having url

**Comment by mehmet-erim** [comment]
>Used the code above in app.component.ts (is it the right place to add routes?)
Yes, right place.

It seems like a bug. I will fix it.

**Comment by mehmet-erim** [comment]
Thanks @thiag0coelho
