### ISSUE TITLE
Module configuration JsonStringEnumConverter doesn't work

### ISSUE THREAD

**Issue by JoseW3b** [abpframework/abp#2740]
I'm working on Abp 2.0.1

I have configured JsonOptions globally in the module:
`       context.Services.AddControllers()
        .AddJsonOptions(options =>
        {
            options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
        });`
but when api controller is called, the enum fields on the response is not correctly serialized. It is serialized as number, not as string as expected.

But, if I serialize it with JsonSerializer it works fine.
`
            var b = new JsonSerializerOptions { };
            b.Converters.Add(new JsonStringEnumConverter());
            var a = JsonSerializer.Serialize(ret, b);
`
Variable `a` contains enum field as string as expected.

Why it works in one way and not the other??

Thanks in advance!!!

**Comment by maliming** [comment]
abp is using NewtonsoftJson instead of System.Text.Json.

You can try the following code.
```
context.Services.PostConfigure<MvcNewtonsoftJsonOptions>(options =>
{
	options.SerializerSettings.Converters.Add(new StringEnumConverter());
});
```

**Comment by JoseW3b** [comment]
With newtonsoft it works fine.
But abp will let us choose in the future???

**Comment by gdlcf88** [comment]
https://github.com/abpframework/abp/issues/1790
