### ISSUE TITLE
Q: Volo.Abp.AspNetCore.Authentication.Basic feature (framework)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2741]
Is there any reason that Basic authentication option (Basic base64("username:password")) is not not implemented yet (or is already on your pipeline)?

Some closed-source external systems have no option to use JWT (Bearer) as an authentication option for abp API.

Thank you for explanations.

**Comment by hikalkan** [comment]
I have no much experience with the basic authentication. Isn't it possible you to add the basic authentication to the current startup template without making something in the framework level?

**Comment by leonkosak** [comment]
I have also no deeper experience with Basic auth (and IdentityServer and management at all).
Could someone who integrated IdentityServer in abp.io give some advice about how to do that (just descriptive quick explanations)?
Thank you.

**Comment by maliming** [comment]
hi @leonkosak 
You can take look this article: 
https://jasonwatmore.com/post/2019/10/21/aspnet-core-3-basic-authentication-tutorial-with-example-api

**Comment by leonkosak** [comment]
@maliming So implementing Basic authentication has nothing to do with [IdentityServer4](https://identityserver4.readthedocs.io/en/latest/) in abp.io?

**Comment by maliming** [comment]
Yes, Authentication and authorization are independent.
Authentication is just to get the user's identity claims in some way. Such as cookies, jwt, openid, etc.

Microsoft abstracts the design of authentication and provides common authentication methods. You can customize any authentication method that conforms to Microsoft design.

![image](https://user-images.githubusercontent.com/6908465/76403305-aa94c000-63bf-11ea-9f2d-5504a07473f3.png)
