### ISSUE TITLE
DashboardDemo package.json Wrong Version 1.0.2

### ISSUE THREAD

**Issue by Gosha24** [abpframework/abp#2742]
In DashboardDemo  in package.json packages has version numbers
dependencies": {
    "@abp/aspnetcore.mvc.ui.theme.basic": "^1.0.2",
    "@abp/chart.js": "^1.0.2"
}
Is it true? they must be 2.0.1

**Comment by maliming** [comment]
I will update them, thanks for the feedback.

**Comment by Gosha24** [comment]
the same in E:\temp\Azure\WpfDev\Abp\abp-2.0.1\modules\client-simulation\demo\Volo.ClientSimulation.Demo\package.json

**Comment by maliming** [comment]
https://github.com/abpframework/abp-samples/tree/master/DashboardDemo

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp-samples/blob/master/DashboardDemo/src/DashboardDemo.Web/package.json
