### ISSUE TITLE
JsonSerializerSettings.DateTimeZoneHandling is ignored

### ISSUE THREAD

**Issue by Sethcran** [abpframework/abp#2743]
When the following setting is configured using (using asp.net but I believe this affects anyone using the newtonsoft json package):

```
Configure<MvcNewtonsoftJsonOptions>(options =>
{
    options.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.Utc;
});
```

Dates should be serialized as UTC all the time. ex: 2020-02-03T03:56:20.7130155Z

However, they currently serialize as 2020-02-03T03:56:20.7130155
(Note the missing Z)

This appears to be primarily caused by the use of a separate contract resolver (AbpMvcJsonContractResolver) that explicitly overrides and provides special behavior for DateTime and DateTime? types. 

Workaround: Set the ContractResolver to DefaultContractResolver.

Request: Please either provide full compatibility with DateTime serializer settings if you're going to override the resolver in this way, or remove the custom resolver (or otherwise make it not the default).

Of course, if the intent is to go back to the System.Text serializer then this is all a moot point, but right now the existing behavior is quite confusing and took a while to figure out why this was happening, hoping to avoid others going through the same process.

**Comment by maliming** [comment]
`AbpMvcJsonContractResolver `and `AbpJsonIsoDateTimeConverter `are mainly used to allow applications to support multiple time zones.

`DisableDateTimeNormalizationAttribute` can disable it.  You can also replace it with your custom implementation.


There is no document yet, but it is similar to aspnetboilerplate(https://aspnetboilerplate.com/Pages/Documents/Timing).
