### ISSUE TITLE
AppUser.ExtraProperties

### ISSUE THREAD

**Issue by majidbigdeli** [abpframework/abp#2746]
The property 'AppUser.ExtraProperties' could not be mapped, because it is of type 'Dictionary<string, object>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'

**Comment by Alexbits** [comment]
Check #1517 #1414 #927

**Comment by maxrizwork** [comment]
I resolved for now putting 
`builder.Ignore<AppUser>();`
inside the OnModelCreating method
only (important, only) when I need to use add-migration, update-database

For the rest (when I'm not updating the db ) I use the default code:
```
   builder.Entity<AppUser>(b =>
                {
                    b.ToTable(AbpIdentityDbProperties.DbTablePrefix + "Users"); //Sharing the same table "AbpUsers" with the IdentityUser

                    b.ConfigureByConvention();
                    b.ConfigureAbpUser();
```
