### ISSUE TITLE
SignalR Package

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2747]
Using SignalR is pretty simple in ABP based applications, just as any asp.net core application. However, we will investigate the ways of pre-integrating to other features of the framework and/or consider to add it to the startup template by default.
(see this: https://github.com/abpframework/abp/issues/1571)

**Comment by leonkosak** [comment]
Based on my previous suggestions (https://github.com/abpframework/abp/issues/1571#issuecomment-532146116), I saw that SQL scaleout is not an option anymore (just Redis and Azure SignalR Service).

https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.1#scaleout-differences

It's disappointing (at least for me) that they canceled SQL option.

**Comment by hikalkan** [comment]
I am working on this. The idea is simply create a `Volo.Abp.AspNetCore.SignalR` package that adds SignalR to the AspNet Core middlewares by default.

**Comment by hikalkan** [comment]
This is completed, I already created a sample application: https://github.com/abpframework/abp-samples/tree/master/SignalRDemo
Documentation is tracked by another issue: https://github.com/abpframework/abp/issues/3912
