### ISSUE TITLE
Accents in french language don't show up correctly

### ISSUE THREAD

**Issue by zHaytam** [abpframework/abp#2752]
Hi,

I added a `fr.json` file and the language in `ConfigureLocalizationServices`.  
The json file contains translations that contain accents, e.g.: `Téléphone`.

These words show up like this: 
![image](https://user-images.githubusercontent.com/34218324/73728097-ff934580-4732-11ea-8bde-f2425b9cf4d3.png)

When checking the file `ApplicationConfigurationScript`, they are represented as `ï¿½`.  
Any idea of where the problem might be?

**Comment by zHaytam** [comment]
Nevermind, I didn't know Visual Studio creates files in a weird encoding. Changing it to UTF-8 works.  
Sorry!

**Comment by maliming** [comment]
Related https://github.com/abpframework/abp/issues/2180#issuecomment-554852256
