### ISSUE TITLE
Server-side search box in DataTables

### ISSUE THREAD

**Issue by zHaytam** [abpframework/abp#2756]
Hello,

Is there any docs/tutorial on how to include a search box in DataTables?

Thank you!

**Comment by zHaytam** [comment]
For some reason, `searching: true` doesn't show the search box and calling `dataTable.search("value").draw()` doesn't include the filter in the api call.

Also, since `PagedAndSortedResultRequestDto` doesn't contain a filter property, the search wouldn't work anyway right?

**Comment by gdlcf88** [comment]
You can find the it in DataTable docs or abp samples.
https://github.com/abpframework/abp/blob/a9a9cf2ef02107ba3b56a48308297d99a0d00789/samples/MicroserviceDemo/modules/product/src/ProductManagement.Web/Pages/ProductManagement/Products/index.js#L9

Search first. 😺

**Comment by zHaytam** [comment]
I'm not sure how that helps me?
The DataTables docs says to set `searching` to true, except it doesn't work.  
And your example shows `serverSide`? I don't understand :/

**Comment by gdlcf88** [comment]
Thought you were asking Server-side search.

Yes, there is not a `Filter` property in dto, maybe it should be added to `LimitedResultRequestDto`.

**Comment by hikalkan** [comment]
It is already implemented for the Identity module's user management page. Check [its source code](https://github.com/abpframework/abp/tree/dev/modules/identity).
It defines its own Filter property: https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/GetIdentityUsersInput.cs

We can add a PagedSortedFilteredResultRequestDto or something like that, but I think you can do it yourself for now.
