### ISSUE TITLE
Stop tenant with the same name being created

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2757]
If `ISoftDelete` is enabled, we can delete a tenant and create a new tenant with the same name. If we want to un-delete the first tenant then there will be a conflict. Could we disable the ISoftDelete filter when checking if a tenant name exists?

https://github.com/abpframework/abp/blob/d99a9ffe008b764fa7c4f0ef6fb4d87e03fc6ecb/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/TenantManager.cs#L35-L42

**Comment by gdlcf88** [comment]
You can try: https://github.com/abpframework/abp/blob/cfb0f094c5cd206bfad1e30153edd07bbc9d46c1/docs/en/Data-Filtering.md

**Comment by olicooper** [comment]
@gdlcf88 Yes this would be the best option if I was writing my own code but this issue is happening with the core MultiTenancyModule code so I would have to override the methods to change how it behaves.

I expected the default behaviour of the module to also check the deleted tenants here: `_tenantRepository.FindByNameAsync(name)`

@maliming I thought allowing duplicate tenant names might be a bug? Or was this part of the design?

**Comment by gdlcf88** [comment]
https://github.com/abpframework/abp/blob/0a1568781df03fe9c86dc38cb7d47b95389cdf0b/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/TenantManager.cs#L40

TenantManager will check duplicate tenant names.

**Comment by olicooper** [comment]
Yes but it doesn't look at the deleted tenants when creating new tenants. Notice the same tenant name **test** in the database screenshot below:
![image](https://user-images.githubusercontent.com/22296715/73870413-f2b24700-4843-11ea-8b91-44aacb1ef2b9.png)

This is on a clean version of abp v2.0.1 (with angular UI).

**Comment by gdlcf88** [comment]
Soft delete also means delete. If you delete an entity, abp considers it's permanently deleted and never be restored.

**Comment by gdlcf88** [comment]
However, if you really want to restore deleted tenants or stop abp from deleting tenants, you can implement `ITenantManager` by your custom class likes `MyTenantManager` to replace abp's `TenantManager`, then you can control all the logic.
