### ISSUE TITLE
EnableLocalLogin setting ignored on the API

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2758]
Similar to [this closed issue](https://github.com/abpframework/abp/issues/2512).
The Angular application correctly displays "Invalid login request" but the API still allows login.
I am able to login via the `/api/account/login` endpoint even if the `Abp.Account.EnableLocalLogin` setting is set to false.

To reproduce:
* load the angular login screen and type in the admin credentials for the host.
* open the `appsettings.json` and add disable local login:
    ```json
   "Settings": { "Abp.Account.EnableLocalLogin": "false" }
    ```
* press the 'login' button on the angular app and you can login without any error.
* if you now logout and attempt to login again you'll see the login error message (showing that the setting is actually updated).

**Comment by maliming** [comment]
I will try to fix it, thanks.

**Comment by olicooper** [comment]
Thanks for your fix so far! Although it works for the login screen it doesn't seem to stop users logging in via the API directly. The user is able to successfully make a request to the `/connect/token` endpoint with a username and password. I don't think the identity server requests are being intercepted.

**Comment by maliming** [comment]
hi @olicooper 
`EnableLocalLogin ` belongs to the account module. The identity server module should not be related to this.

**Comment by olicooper** [comment]
Okay that makes sense.
Unfortunately I have realised this is still not working on the Angular application using the steps in my original comment. Is it within scope to add a check for the angular application? I imagine you'd have to fetch the latest setting value from the API rather than using the ones from the angular store?

**Comment by maliming** [comment]
@olicooper Please create a new issue and explain it in detail.
