### ISSUE TITLE
Contribute Guide - How to build ?

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2759]
Hi,

I wish to contribute, but first I need to build abp.io on my machine.

I have built the framework, it was easy. But I got issues when trying to build the modules.

I know that:
- There is no .sln for all the modules
- The module build order is important due to dependencies
- I got such error : 

`Error	NU1105	Unable to find project information for 'C:\Libraries\abp.io\abp\framework\src\Volo.Abp.Authorization\Volo.Abp.Authorization.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so please run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.	Volo.Abp.Identity.Application.Contracts	C:\Libraries\abp.io\abp\modules\identity\src\Volo.Abp.Identity.Application.Contracts\Volo.Abp.Identity.Application.Contracts.csproj	1	`

So, is there another way to build everything ?

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/73804027-75fc7a00-47fd-11ea-8406-6eab3503322d.png)

**Comment by hikalkan** [comment]
In addition to running the build-all.ps1:

Modules and Templates have their own solutions and have local references to the framework and each other.

Visual Studio can not work properly with the local references out of the solution folder. When you open a module/sample solution in the Visual Studio, you may get some errors related to the dependencies. In this case, run the dotnet restore on the command prompt for the related solution's folder. You need to run it after you first open the solution or change a dependency.

**Comment by yekalkan** [comment]
We published a tool for `dotnet restore` command. You can install it.

https://marketplace.visualstudio.com/items?itemName=alper-ebicoglu.DotnetRestoreVsix

With this extension, when you right click on a solution, you will see a 'dotnet restore' command in menu. You wont need to open a command prompt and type dotnet restore.
