### ISSUE TITLE
[DOC] Since entity ID is now readonly, the tutorial need to be updated

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#2760]
https://docs.abp.io/en/abp/latest/Tutorials/AspNetCore-Mvc/Part-III#adding-test-data

![image](https://user-images.githubusercontent.com/3471718/73803118-c6bea380-47fa-11ea-8f0a-6a47930c6cfa.png)

There's an `EntityHelper.TrySetId` method, is it the recommaned way to use?

**Comment by acjh** [comment]
Will be resolved by #2713

**Comment by hikalkan** [comment]
Resolved by #2713
