### ISSUE TITLE
Any plans to integrate Quartz.net  with Background Worker?

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#2762]
In Asp.Net Boilerplate, it integrated Quartz.net with background workers, so that, it is easy to use Quartz.net.
Any plans abp vNext could integrate Quartz.net to background workers, current only hangfire integrated to background job.

Or, any guideline to add quartz.net with asp.net core background tasks?

**Comment by hikalkan** [comment]
Yes, that can be possible and probably easy. Any PR welcome :)
You can check [hangfire integration source code](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.BackgroundJobs.HangFire) and [asp.net boilerplate quartz integration source code](https://github.com/aspnetboilerplate/aspnetboilerplate/tree/dev/src/Abp.Quartz) to understand how to implement it.

**Comment by viewtance** [comment]
Is these information useful to integrate it? Based on asp.net core hosted services interface, it has singleton and scoped services scenarios.
[https://andrewlock.net/creating-a-quartz-net-hosted-service-with-asp-net-core/](url)
[https://andrewlock.net/using-scoped-services-inside-a-quartz-net-hosted-service-with-asp-net-core/](url)

**Comment by olicooper** [comment]
Ref: https://github.com/abpframework/abp/pull/2904

**Comment by hikalkan** [comment]
Documentation: https://docs.abp.io/en/abp/latest/Background-Workers-Quartz and https://docs.abp.io/en/abp/latest/Background-Jobs-Quartz
