### ISSUE TITLE
The separate identity server for Angular template is very slow

### ISSUE THREAD

**Issue by yanxiaodi** [abpframework/abp#2764]
I use abp CLI v2.0.1 to create a new Angular project with `--separate-identity-server` parameter but the identity server website is very slow. 

By the default setting, run the separate identity server website and navigate to `/Account/Login` in the browser. But after a long time the page is still loading.

If I create a new project without `--separate-identity-server`, the `/Account/Login` page is fast. I can also log in from the angular website.

Not sure why it does not work well with the separate identity server. Any ideas? Thanks.

**Comment by maliming** [comment]
>  the identity server website is very slow.

It may be caused by redis, please check the connection string.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.IdentityServer/appsettings.json#L10

**Comment by yanxiaodi** [comment]
Thanks, @maliming . There is no redis component in the default Angular template. Can I remove this configuration?

**Comment by maliming** [comment]
Including the code that enables redis, but then the cache cannot be shared between multiple applications. This may cause some problems, I am not sure.

I suggest you install a redis on your computer.

https://github.com/abpframework/abp/blob/3967c642bb3c3d69911d0c77b09bb2bb8a7f7b38/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.IdentityServer/MyProjectNameIdentityServerModule.cs#L105-L116

**Comment by yanxiaodi** [comment]
@maliming Thanks for your help. I installed redis and it works now.
