### ISSUE TITLE
how to replace  standard  @abp/bootstrap  package with my own bootstrap version?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#2770]
I want to develpment a third abp  theme ,but the third theme use lower verison of bootstrap,
if I use the standard @abp/bootstrap version, I got a wrong view. so I want to replace the stand @abp/bootstrap  package with the lower bootstrap version. Any idea? Thanks a lot.

**Comment by maliming** [comment]
I think maybe you can create a low version bootstrap npm package.

**Comment by hikalkan** [comment]
Hi @zsanhong 

We don't recommend this. Go with Bootstrap 4.x. Even if you can create a bs3 based theme, the modules and the tag helpers will not be compatible with it.
