### ISSUE TITLE
Allow to download react native mobile ui as a part of the application creation

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2771]
Once https://github.com/abpframework/abp/issues/2699 completes.

### ABP CLI

When you create a new application (independenty from the UI type), react native mobile app will be included in the downloaded zip as a separate folder (like angular now). If you like, you can delete after download.

If you want, you can specify `--mobile none` to not include it in the downloaded zip. In the future, we can add options like `--mobile xamarin` if we add Xamarin UI and so on...

### Direct Download

Add a combobox labeled "Mobile UI" with 2 options: "None" and "React Native" (selected).

**Comment by gdlcf88** [comment]
As more and more UI templates, maybe optional list will be better?
- [x] Mvc
- [ ] Angular
- [ ] React
- [x] React Native
- [ ] Vue.js

**Comment by hikalkan** [comment]
Do you think it is useful to download MVC & Angular UI together? I thought one web and one mobile UI selection would be better and simpler.

**Comment by gdlcf88** [comment]
Yes, the single web project is enough. 

Maybe one day you add new template (like Electron) for other platforms, so what about rename the "Mobile UI" to "Client UI" or "Client project"? 😄

Web background management UI:
- [ ] None
- [x] Mvc
- [ ] Angular
- [ ] React
- [ ] Vue.js

Client projects: (Multiple choice)
- [ ] None
- [x] React Native
- [ ] Xamarin
- [x] Electron

**Comment by hikalkan** [comment]
YAGNI! We start with mobile UI, it is easy to change later.
