### ISSUE TITLE
Bulk insert using repository

### ISSUE THREAD

**Issue by zHaytam** [abpframework/abp#2772]
Hello,

I have a case where I have a stream of entries, say books, and I need to insert them all.  
Using `InsertAsync` with `autoSave: true` will be very expensive, since there are hundreds of entries.

Setting `autoSave` to false would work, the only problem is that I have no way to save changes at the end.

Any solution to this?

**Comment by hikalkan** [comment]
At the end, call `await UnitOfWorkManager.Current.SaveChangesAsync()`.
