### ISSUE TITLE
Change seed Data

### ISSUE THREAD

**Issue by majidbigdeli** [abpframework/abp#2773]
I add BirthDate Property To The AppUser Entity  it is not Null able
I  want add Seed for this propery  the First Time  but i can not . then DbMigrator Project Can not run .

**Comment by maliming** [comment]
Please refer to https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/IdentityServer/IdentityServerDataSeedContributor.cs#L20
