### ISSUE TITLE
Support file downloading

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2774]
I would like to be able to download files in the Angular UI using the API. I have been able to hack a solution together which I will try to outline below.

In the `HttpApi.Host` Controller I needed to return a `FileResult`:
```csharp
[HttpGet("download-something")]
// The attributes below are required to make sure Swagger docs understand the response
[SwaggerResponse(200, type: typeof(FileContentResult))]
[ProducesResponseType(typeof(FileContentResult), 200)]
public async Task<FileResult> DownloadSomething()
{
    return new FileContentResult(new byte[0], Volo.Abp.Http.MimeTypes.Text.Plain)
    {
        FileDownloadName = "file.txt",
        LastModified = DateTimeOffset.UtcNow,
    };
}
```
I needed to expose the `Content-Disposition` header in the cors policy during `ConfigureServices`:
```csharp
context.Services.AddCors(options =>
{
    options.AddPolicy(DefaultCorsPolicyName, builder =>
    {
        builder
            // ...
            .WithExposedHeaders("Content-Disposition"); // Add this
    });
});
```
And also update the Swagger generation:
```csharp
context.Services.AddSwaggerGen(
    options =>
    {
        // ...
        // For file downloads
        options.MapType<FileContentResult>(() => new OpenApiSchema { Type = "string", Format = "binary" });
        // ...
    });
```

Within Angular I needed to intercept the error response to convert the `Blob` response back to json if it was an error (this is a bug with Angular). I got the code from here https://stackoverflow.com/a/57530087/2634818 and it works perfectly with abp as far as I can see.

I also needed to use the `RestService` like this to allow downloading blobs:
```javascript
downloadSomething(): Observable<HttpResponse<Blob>> {
  return this.restService.request<void, HttpResponse<Blob>>({
      method: 'GET',
      url: `/api/app/download-something`,
      responseType: 'blob',
      reportProgress: true
    } as Rest.Request<void>,
    {
      observe: Rest.Observe.Response
    });
}
```

And subscribe to the download like this to parse the filename and create a hidden link which is clicked:
```javascript
this.myService.downloadSomething()
  .pipe(take(1))
  .subscribe((response: HttpResponse<Blob>) => {
    if (!response.headers || !response.headers.get('content-disposition') || !response.body) return;
    const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
    const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
    const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
    
    const url = window.URL.createObjectURL(response.body);

    var a = document.createElement('a');
    document.body.appendChild(a);
    a.setAttribute('style', 'display: none');
    a.href = url;
    a.download = fileName;
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();
  });
}
```

It would be great to see: 
- The API to include native support for the `FileResult`/`FileContentResult` return type
- The Angular `error.handler.ts` support decoding errors when the response is of type `Blob`.
- The new [Angular service generator](https://github.com/abpframework/abp/issues/2222) support file downloads

I hope this code also helps others to implement file downloading too.

**Comment by mehmet-erim** [comment]
Hi @olicooper,

Until we develop something for this issue, you can handle the error manually in Angular.
Pass `skipHandleError: true` to `RestService` as shown below:

```diff
downloadSomething(): Observable<HttpResponse<Blob>> {
  return this.restService.request<void, HttpResponse<Blob>>({
      method: 'GET',
      url: `/api/app/download-something`,
      responseType: 'blob',
      reportProgress: true
    } as Rest.Request<void>,
    {
      observe: Rest.Observe.Response,
+     skipHandleError: true
+    }).pipe(catchError(err) => {
+    // handle error here and return an observable e.g. of(null)
+    });
}
``` 

See the [`catchError` documentation](https://rxjs-dev.firebaseapp.com/api/operators/catchError)

**Comment by mahmut-gundogdu** [comment]
This feature already implemented. We have supported the file download for 6.0 or older version. I didn't closed because I just want to make sure. Me or a teammate will test it in local, then it will be fixed or closed.

**Comment by olicooper** [comment]
Thanks for the update, I assume it is the `RemoteStreamContent` documented in https://docs.abp.io/en/abp/7.3/Application-Services ?
Is the `Content-Disposition` header on the server and file/error handling in Angular implemented too?

**Comment by Sinan997** [comment]
- create a service as below
```csharp
  public Task<IRemoteStreamContent> Download()
  {
      var fs = new FileStream("yourfilepath", FileMode.OpenOrCreate);
      return Task.FromResult(
          (IRemoteStreamContent) new RemoteStreamContent(fs){}
      );
  }
```
- generate proxy in angular

```ts
download = (config?: Partial<Rest.Config>) =>
  this.restService.request<any, Blob>({
    method: 'POST',
    responseType: 'blob',
    url: '/api/app/todo/download',
  },
  { apiName: this.apiName,...config });
``` 

You can download the file as below
```ts


  download(): void {
    this.service.download().subscribe(file=>{
      downloadBlob(file, 'fileName');
    })
  }
```
