### ISSUE TITLE
How to set the default language？

### ISSUE THREAD

**Issue by majidbigdeli** [abpframework/abp#2775]
i use 

  "Settings": {
    "Abp.Localization.DefaultLanguage": "cs"
  }

in appsettings.json 

but not working

**Comment by maliming** [comment]
The default language has lower priority than `QueryStringRequestCultureProvider`, `CookieRequestCultureProvider`, `AcceptLanguageHeaderRequestCultureProvider`.

see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#localization-middleware

**Comment by johnnba** [comment]
Dear @majidbigdeli 
```
 var defaultLanguage = context.ServiceProvider.GetService<ISettingDefinitionManager>().Get(LocalizationSettingNames.DefaultLanguage);
            defaultLanguage.DefaultValue = "zh-Hans";
```
if you set failed ,you can set it manually by the above code.

**Comment by majidbigdeli** [comment]
@Hello @johnnba  

it is not working . Current Culture not changed

**Comment by yerayvm** [comment]
@majidbigdeli you can try in startup.cs inside `ConfigureServices` this code:

```
CultureInfo[] supportedCultures = new[]
               {
                    new CultureInfo("cs"),
                    new CultureInfo("en")
                };

            services.Configure<RequestLocalizationOptions>(options =>
            {
                options.DefaultRequestCulture = new RequestCulture("cs");
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
                options.RequestCultureProviders = new List<IRequestCultureProvider>
                {
                    new QueryStringRequestCultureProvider(),
                    new CookieRequestCultureProvider()
                };
            });
 
```

and then in your `---module.cs` inside `OnApplicationInitialization` paste this code above `            app.UseMvcWithDefaultRouteAndArea();`  :

`app.UseRequestLocalization();`

**Comment by longxiaomiao** [comment]
@yerayvm Hi, I tried your way, it worked for me, thanks!
I modified the `app.UseAbpRequestLocalization()` in `OnApplicationInitialization` to the following code:
``` C#
var supportedCultures = new[]
{
    new CultureInfo("cs"),
    new CultureInfo("en"),
};
app.UseAbpRequestLocalization(options =>
{
    options.DefaultRequestCulture = new RequestCulture("cs");
    options.SupportedCultures = supportedCultures;
    options.SupportedUICultures = supportedCultures;
    options.RequestCultureProviders = new List<IRequestCultureProvider>
    {
        new QueryStringRequestCultureProvider(),
        new CookieRequestCultureProvider()
    };
});
```
and thank you again!

**Comment by bodeg** [comment]
I tried @crybigsea suggestion
Set two supported languages: English and Hebrew, the default language is Hebrew.

Once I did it - I got the correct default language, but when I switch to the other language I still getting the default language texts.

Switching languages without that code works fine.
any idea?
