### ISSUE TITLE
Question: Fk error while trying to reference Creator 

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2776]
I've read several posts on past issues related to AppUser, but still I don't fully understand. I'm trying to use AppUser as follows:

public AppUser Creator { get; set; }

Throws error as it creates an empty table AppUser (and references it as fk as convention) instead of referencing AbpUsers.

![image](https://user-images.githubusercontent.com/6138475/73996430-4e5efc00-493a-11ea-87a5-7edf5d3db07b.png)
![image](https://user-images.githubusercontent.com/6138475/73996435-54ed7380-493a-11ea-8a5f-9a2b1386c87a.png)

Currently using default implementation 
```
builder.Entity<AppUser>(b =>
{
       b.ToTable("AbpUsers"); //Sharing the same table "AbpUsers" with the IdentityUser
       b.ConfigureByConvention();
       b.ConfigureAbpUser();

       b.ConfigureCustomUserProperties();
});
```

**Comment by maliming** [comment]
> Throws error as it creates an empty table AppUser (and references it as fk as convention) instead of referencing AbpUsers.

What is the detailed error message?

**Comment by thiag0coelho** [comment]
MessageText: insert or update on table "AppPropostas" violates foreign key constraint "FK_AppPropostas_AppUser_CreatorId"
    Detail: Key (CreatorId)=(a38f1a21-2273-3444-0927-cb4e-39f3344e46d8) is not present in table "AppUser".



Part of migration causing problem. I had removed for testing and everything went well without it, Creator object was loaded fine... But if someday I have to remake migrations that would come back

```
                    table.ForeignKey(
                        name: "FK_AppPropostas_AppUser_CreatorId",
                        column: x => x.CreatorId,
                        principalTable: "AppUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);

```

**Comment by maliming** [comment]
I think the `AppUser Creator` foreign key property should be nullable.
