### ISSUE TITLE
access to efcore raw sql api and docs  should be updated

### ISSUE THREAD

**Issue by johnnba** [abpframework/abp#2778]
Hello:
as with the efcore 3.1, there is the breaking changes to access to raw sql api . so the follow docs should be updated.

https://github.com/abpframework/abp/blob/dev/docs/en/Entity-Framework-Core.md

the new qualified usage should follow the below convention;

https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/core/Querying/RawSQL/Sample.cs

however , i got some problems to access the efcore's raw sql in the applicationservice.

```
var dbcontext=Repository.GetDbContext();
dbcontext.Set<T>().FromSqlRaw<T>(sql, parameters);
dbcontext.Set<T>().FromSqlInterpolated<T>(sql, parameters);
var count =await dbcontext.Database.ExecuteSqlInterpolatedAsync(sql );
```
it works, but all of them  get 0 query result.  is there the dbcontext get wrong instance?

**Comment by maliming** [comment]
The documentation does not need to be updated, it just shows how to get DbContext and DbSet.

> it works, but all of them get 0 query result. is there the dbcontext get wrong instance?

Please check the log, ef will output a lot of messages. If possible, provide unit test code to reproduce the problem.

**Comment by johnnba** [comment]
dear @maliming :
1:please see the https://github.com/johnnba/simpleAbpNextMysqlDemo that i pushed the unit test in  the Should_Count_Greater_Than_0_User test  in the class of SampleDomainTests.

> 2:The documentation does not need to be updated, it just shows how to get DbContext and DbSet.
 i see the follow tutorial had the outdated raw sql api , so i suggest to update the docs
```
 Example implementation of the IBookRepository interface:

public class BookRepository : EfCoreRepository<BookStoreDbContext, Book, Guid>, IBookRepository
{
    public BookRepository(IDbContextProvider<BookStoreDbContext> dbContextProvider)
        : base(dbContextProvider)
    {
    }

    public async Task DeleteBooksByType(BookType type)
    {
        await DbContext.Database.ExecuteSqlCommandAsync(
            $"DELETE FROM Books WHERE Type = {(int)type}"
        );
    }
}
Now, it's possible to inject the IBookRepository and use the DeleteBooksByType method when needed.
```

**Comment by johnnba** [comment]
@maliming  i've fixed the un expected query error.  you can close the issue if you think there is no need to update the related docs.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/commit/f4675e8ae07cba20a79c8f42324595ae46aa9b9f https://github.com/abpframework/abp/commit/5841b5d53720037ef651b4ec1ea53f4303678fd0
