### ISSUE TITLE
AuditLogActions contains passwords from IdentityUserAppService.CreateAsync

### ISSUE THREAD

**Issue by zHaytam** [abpframework/abp#2782]
Hello,

Is there a way to somehow disable logging a parameter in the `AuditLogActions` table? The method `Volo.Abp.Identity.IdentityUserAppService.CreateAsync` contains passwords and we should really avoid that, security wise.

Any info about this?

**Comment by zHaytam** [comment]
I found out about `DisableAuditing` but I'm not sure if there is a way to use it on an entity that isn't ours? Since the password is in the identity entity.

Thank you!

**Comment by maliming** [comment]
We should use `DisableAuditing `in the dto class.
