### ISSUE TITLE
Can I Extend Role Entity like AppUser?

### ISSUE THREAD

**Issue by inamvar** [abpframework/abp#2786]
I have a entity called MPE and I need to add one-to-many relation to a role entity. how can I extend the role?

**Comment by gdlcf88** [comment]
I think you can add `IdentityRole` to your DbContext, even if the relation between aggregate roots is not a good practice for DDD.

**Comment by inamvar** [comment]
> I think you can add `IdentityRole` to your DbContext, even if the relation between aggregate roots is not a good practice for DDD.

You mean I define a new class like `AppIdentityRole` and derive if from `IdentityRole`  and then add the `AppIdenityRole` to my `DbContext`?

**Comment by gdlcf88** [comment]
No, just add abp's `IdentityRole`.

**Comment by inamvar** [comment]
> No, just add abp's `IdentityRole`.

So How can I add my custom property?

**Comment by gdlcf88** [comment]
Add it to MyDbContext then you can make MPE relate to IdentityRole without changing IdentityRole's properties. But if possible, dont make relation between aggregate roots.

**Comment by hikalkan** [comment]
You can do same we did for AppUser. Just check where it is used to understand how we did it. Not so hard.
