### ISSUE TITLE
Full control over User page 

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2787]
I've come across a client requirement to add 1 more field to user page. Now I have 2 user pages, one of them with just 1 field to edit. 

The whole framework feels great overall, but I think this is one thing that has to change, maybe give full control to these modules ( @abp/ng.account,  @abp/ng.identity,  @abp/ng.setting-management,
@abp/ng.tenant-management), keep them in ABP boilerplate instead of npm packages.

Most systems will have more fields than Name, Email, Phone Number, etc.
One more reason to have full control over these pages, styling and controls are becoming different:

User
![image](https://user-images.githubusercontent.com/6138475/74093066-b7b24c80-4aab-11ea-8bc9-1944031db604.png)

Other page
![image](https://user-images.githubusercontent.com/6138475/74093010-ff84a400-4aaa-11ea-927e-d66fcc7dbcd8.png)

What do you guys think? Does that make sense?

**Comment by hikalkan** [comment]
Hi @thiag0coelho 
We will be working on a system to easily extend/customize current UIs, DTOs, services and entities.
Currently you can copy the Identity module source code into your solution (and remove npm dependencies) and freely customize it.

**Comment by wakuflair** [comment]
@hikalkan
Will this feature avaliable in 2.1?

**Comment by hikalkan** [comment]
No, we'll start to work on it in v2.2. We will try to explain/document current extension/customization points and work on other possibilities.
