### ISSUE TITLE
UserFriendlyException throws 403 error and causes a problem.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2789]
If a user does not have specified permission, abp throws:
```
{
	"error": {
		"code": null,
		"message": "Authorization failed! Given policy has not granted: xxx",
		"details": null,
		"validationErrors": null
	}
}
```

And for some other reason I throw UserFriendlyException, it throws:
```
{
	"error": {
		"code": null,
		"message": "My custom message for UserFriendlyException",
		"details": null,
		"validationErrors": null
	}
}
```

In practice I need to handle authorization failed error in user's browser. Problem is how to distinguish which is abp's authorization failed error, and which is my custom error?

I have many ways to solve this problem by myself, but I think it is a common problem for us.

**Comment by hikalkan** [comment]
Throw [AbpAuthorizationException](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Security/Volo/Abp/Authorization/AbpAuthorizationException.cs) instead of UserFriendlyException

**Comment by gdlcf88** [comment]
> Throw [AbpAuthorizationException](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Security/Volo/Abp/Authorization/AbpAuthorizationException.cs) instead of UserFriendlyException

I use UserFriendlyException because it want to say such as "insufficient inventory" which is not an authorization failed error. But the problem is template the UserFriendlyException throws is the same as AbpAuthorizationException (only message is different), so client-side is hard to judge the error and make different deals for them. For example, if it throws AbpAuthorizationException, the browser will redirect to login page, but just show message for UserFriendlyException and other type of exception.

**Comment by acjh** [comment]
@gdlcf88 Either:
- throw `AbpValidationException`, or
- pass `code` in `UserFriendlyException` constructor and map it in `AbpExceptionHttpStatusCodeOptions`: https://docs.abp.io/en/abp/latest/Exception-Handling#custom-mappings

**Comment by gdlcf88** [comment]
> For example, if it throws AbpAuthorizationException, the browser will redirect to login page

But I cannot consider all the exception with null code is AbpAuthorizationException. It would be better if abp retains some code for framework level error. For now I have to find AbpAuthorizationException with `result.error.message.startsWith('Authorization failed!')`

**Comment by gdlcf88** [comment]
> throw AbpValidationException

For "insufficient inventory" error, maybe 403 is better than 400.

**Comment by acjh** [comment]
Then do (part of) the "or" way, which the framework already supports, for your custom error:
> - pass `code` in `UserFriendlyException` constructor

**Comment by gdlcf88** [comment]
I made a mistake. AbpAuthorizationException means user has logged in, but not have specified permission.

**Comment by HeroSpha** [comment]
i have a same problem, but mine is UserFriendlyException shows [403] You are not authorized! (the endpoint doesnt need any authorisisation, it jst throws UserFriendlyException ) in my angular app which is deployed to azure as a static web app, but in localhost the app works fine.
