### ISSUE TITLE
Method For Clearing The Distributed Cache

### ISSUE THREAD

**Issue by hieutns96** [abpframework/abp#2793]
Hi all, Do we have any method to clearing the Distributed Cache ?
I've define the distributed cache object, and now I'm looking for a function to clear the Cache when there is some change.

**Comment by maliming** [comment]
You can only remove the cache through its `Remove `method.

https://github.com/abpframework/abp/blob/82c01a4c95e54a25f069ef4d712a7248dea47458/framework/src/Volo.Abp.Caching/Volo/Abp/Caching/IDistributedCache.cs#L144-L160

https://docs.abp.io/en/abp/latest/Caching

**Comment by hieutns96** [comment]
Hi @maliming 

Is there any method for clearing all the cache in DistributedCache, I'm using MemoryDistributedCache.

**Comment by chris-stormideas** [comment]
@hieutns96 

As @maliming mentioned, yes, the only way to remove items via IDDistributedCache` is with the `Remove` and knowing the key.

However, you can connect to redis and do it yourself, this should help: https://stackoverflow.com/questions/24531421/remove-delete-all-one-item-from-stackexchange-redis-cache
