### ISSUE TITLE
ABP with Xamarin.Forms

### ISSUE THREAD

**Issue by Hardshop18** [abpframework/abp#2801]
Hi,
I created an Android project that uses Volo.ABP, and the project is running both on the emulator and on the phone. I have two cases to resolve:

1 - When generating the APK the application size is around 71mb, I have already changed some settings to generate the APK. But when it decreases the size of the APK does not work (29mb and 10mb).

2 - When creating the module to access the database in the APK it takes 17s to start the module. While in a WPF application it is instantaneous.

Command used to start the module:

```
Application = AbpApplicationFactory.Create<SincaModule>(options =>
{
    options.UseAutofac();
});
Application.Initialize();
```
[project image](https://drive.google.com/file/d/1q1ber-6C78cSNUYHbTV2vMzIMbWTGkYn/view?usp=sharing)

**Comment by hikalkan** [comment]
We are working on the v2.1 release, so not have time at the moment. We will check it in the milestone.
Thank you for your contribution :)

**Comment by ebicoglu** [comment]
as far as I understand, you create a Xamarin App for your project, not a contribution?!
if so can you share your project via GoogleDrive and send the link to me, I'll check on the code.
`info [@] abp.io`

**Comment by volethanh** [comment]
Hi, Is this priority ?

**Comment by Loongle** [comment]
@gterdem An `Operation is not supported on this platform` exception occurs when running on IOS, can you try?

**Comment by gterdem** [comment]
@Loongle I think you wanted to mention someone else? :)

**Comment by Loongle** [comment]
> An Operation is not supported on this platform exception occurs when running on IOS, can you try?

@Hardshop18
