### ISSUE TITLE
BUG : claims not persisted with MongoDB

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2803]
Hi,

I try to add some 'extra' information to the users, so I try to add a custom "claim".

The problem is that none of the claims is persisted into MongoDB, it "looks" like a bug because even the "Abp" claims are absents!

**Comment by hikalkan** [comment]
There is no "Abp" claims stored in the database. Can you please share the code you've written, so we can understand what you are trying to do.

**Comment by vd3d** [comment]
I mean, all the types from AbpClaimTypes ! PhoneNumber, etc...

I wish to add a my own property to my user "age", "gender, ...
