### ISSUE TITLE
Q: Yarn 2 (Berry) fiasco

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2809]
Besides huge braking change (PnP), Yarn 1.x will be archived in a year or two.
https://dev.to/arcanis/introducing-yarn-2-4eh1

![image](https://user-images.githubusercontent.com/39346964/74269312-8f278e00-4d09-11ea-8ef6-6c9dda590331.png)

Video on Yarn 2 topic: https://www.youtube.com/watch?v=bPae4Z8BFt8

For Angular GUI project - what will you do? NPM did a huge step forward since you were "forced" to use Yarn (lockfile, major speed improvements,...).

**Comment by hikalkan** [comment]
Thanks @leonkosak for sharing this.
We will check & discuss it again in the next weeks. We will also see the trend of the community.

**Comment by leonkosak** [comment]
@hikalkan, when this will be actual, consider [Deno](https://deno.land/). Maybe when Yarn v1.22.4 will become EOL, Deno will be stable and feature-rich enough.

**Comment by hikalkan** [comment]
@armanozak can you briefly write your thought on that?

**Comment by hikalkan** [comment]
We were internally discussing to stop suggesting the yarn and turn back to the npm by default.

@armanozak can you briefly write your thought on that?

**Comment by armanozak** [comment]
Hi @leonkosak,

We believe, Yarn 2 is a completely different package manager and we are not planning to use it. We are waiting for npm v7 release to leave Yarn behind and are hoping this will be the smoothest transition.

I know what Deno is, but cannot see how it is related. Could you please elaborate on that?

**Comment by leonkosak** [comment]
Moving away from node runtime (and "ecosystem").
But I agree, npm v7 is currently much better option for quicker migration.

**Comment by merceyz** [comment]
> Besides huge braking change (PnP)

Yarn 2 supports `node_modules` even better than Yarn 1 did, the breaking change was switching the default from `node_modules` to PnP. You can easily switch back using `yarn config set nodeLinker node-modules`

**Comment by MichelZ** [comment]
With NPM7 now being GA for more than a Year, what's the current stance on this issue? @hikalkan

**Comment by MichelZ** [comment]
@hikalkan How was this item completed? Is a newer version of yarn supported now?
