### ISSUE TITLE
Application/Tenant based dynamic theme selection

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#281]
Create a setting to determine the theme dynamically based on application/tenant based.

**Comment by mperk** [comment]
Hey hikalkan,
Do you think to get a plan this issue in soon?

**Comment by hikalkan** [comment]
You can override the [default theme selector](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI/Volo/Abp/AspNetCore/Mvc/UI/Theming/DefaultThemeSelector.cs) and return a different theme based on the current tenant. I think we don't work on this in a short time.
