### ISSUE TITLE
How To override  api​/identity​/users Parameter in post And Put Request

### ISSUE THREAD

**Issue by majidbigdeli** [abpframework/abp#2810]
How To Can I  Change api​/identity​/users  Parameter ?

I want override IdentityUserCreateDto And Add Property To it.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2268

**Comment by majidbigdeli** [comment]
@maliming  
I See [#2268](https://github.com/abpframework/abp/issues/2268) But it Create Another new Service ;
You dont have Another Solution That Change IdentityUserCreateDto And Add Parameter To it;

**Comment by maliming** [comment]
> We are working on extensibility and will offer a solution for such cases. https://github.com/abpframework/abp/issues/2023#issuecomment-546831029

**Comment by majidbigdeli** [comment]
@maliming  Thank You  .
