### ISSUE TITLE
ICurrentUser properties are null in a remote service, why ?

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2811]
Hi,

I have created a new remote service and need to get some information about the current user, but all the fields are null ! Of course, I'm logged in... on the Web site pages, I can get my "HttpContext.User"... but cannot retrieve it on the Service side (HttpApi.Host).

In a second step, I added tried to add [Authorize] and then got an exception:
`Volo.Abp.AbpException: 'Remote service returns error! HttpStatusCode: Unauthorized, ReasonPhrase: Unauthorized'`

I don't need any special permission/role to access this service, and I'm logged in... so why it tell me it is unauthorized ?

Any idea ?

Thx

**Comment by maliming** [comment]
Are you using tiered template?

Can you share some code to explain your problem?

**Comment by vd3d** [comment]
Yes, I use a tiered template.

Here some code, hope it help :

In my MyProject.Application :

```
[Authorize]
public class EditorAppService :
        ApplicationService,
        IEditorAppService
{
	public async Task CreateProAccountAsync()
    {
		string email = CurrentUser.Email;
	}
}
```

Then, in my MyProject.Web, I call it with :

`await _service.CreateProAccountAsync();`

Really, nothing special, but I don't understand why I have nothing in the CurrentUser and if I add the [Authorize] attribute, I got an exception... I only need to be logged in (which is the case)

**Comment by maliming** [comment]
hi
Can you provide complete steps so that I can reproduce your problem?

**Comment by vd3d** [comment]
I'm trying... so I have create a full sample. But it work !
In my app, I have switched from Razor (default sample) to Server-sider Blazor, but not sure it is the problem ! I try to reproduce it... (no luck for now).

**Comment by vd3d** [comment]
So, I have a tiered application, what I have:
- The Web app is authenticated
- The Host app is not authenticated

It seems that the authentication remain on the Web side and is not 'propagated' on the Host side.

How does this work ? How does we can authenticate and then being authenticated too on the tiered app ?

**Comment by maliming** [comment]
1.When the web is authenticated by the identity server, the token will be saved.
2. The web will call the host's api and pass the token through `Dynamic C # API Clients`(https://github.com/abpframework/abp/blob/dev/docs/en/AspNetCore/Dynamic-CSharp-API-Clients.md).
3. The host will verify the token through the identity server.

This is the flow of the tiered application.

**Comment by vd3d** [comment]
Thanks, I understand that everything goes through the HttpClient, but I don't know how I can debug the fact that the service is called, but it is not authenticated. Any idea ?

**Comment by Stirda** [comment]
Same usage. Same problem. Please help.
