### ISSUE TITLE
How to implement AOP with Autofac Inspectors?

### ISSUE THREAD

**Issue by inamvar** [abpframework/abp#2812]
I want to add AOP feature to my project. how can I implement that with Autofac inspectors? I found some documentation (with castle inspectors) in old boilerplate framework, but  is there any in new abp framework?

**Comment by maliming** [comment]
Please refer to the built-in interceptors, such as uow.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/AbpUnitOfWorkModule.cs#L10

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptorRegistrar.cs

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptor.cs#L10

**Comment by inamvar** [comment]
thanks, that's great. and how can I specify a method or a class to apply that interceptor? atucally li what we can do in `AspectCore` library. for example we can use predicate strings to apply an interceptor to any classes ends with name "*Service" : 
```C#
// this is a sample for AspectCore 
  config.Interceptors.AddTyped<MethodExecuteLoggerInterceptor>(Predicates.ForService("*Service"));
```

**Comment by inamvar** [comment]
> Please refer to the built-in interceptors, such as uow.
> 
> https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/AbpUnitOfWorkModule.cs#L10
> 
> https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptorRegistrar.cs
> 
> https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptor.cs#L10

I used abp builtin Interceptor and got This error :
```
System.TypeLoadException: Could not load type 'Castle.Proxies.LifetimeProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69' because the parent type is sealed.
```

Any idea?

**Comment by maliming** [comment]
Judge the `Type `in the `RegisterIfNeeded `method.
```
Type.FullName
```
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptorRegistrar.cs#L10

**Comment by inamvar** [comment]
> Judge the `Type `in the `RegisterIfNeeded `method.
> 
> ```
> Type.FullName
> ```
> 
> https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptorRegistrar.cs#L

**Comment by inamvar** [comment]
> > Please refer to the built-in interceptors, such as uow.
> > https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/AbpUnitOfWorkModule.cs#L10
> > https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptorRegistrar.cs
> > https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Uow/Volo/Abp/Uow/UnitOfWorkInterceptor.cs#L10
> 
> I have used abp built-in Interceptor and got This error :
> 
> ```
> System.TypeLoadException: Could not load type 'Castle.Proxies.LifetimeProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69' because the parent type is sealed.
> ```
> 
> Any idea?

I'm completely confused. is there any solution for this error?

**Comment by maliming** [comment]
Please share the code that caused the error.

**Comment by inamvar** [comment]
> Please share the code that caused the error.

```C#

    [DependsOn(
        typeof(PmsCloudDomainModule),
        typeof(AbpAccountApplicationModule),
        typeof(PmsCloudApplicationContractsModule),
        typeof(AbpIdentityApplicationModule),
        typeof(AbpPermissionManagementApplicationModule),
        typeof(AbpTenantManagementApplicationModule),
        typeof(AbpFeatureManagementApplicationModule)
        )]
    public class PmsCloudApplicationModule : AbpModule
    {

        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
           context.Services.OnRegistred(RegisterInterceptors.Register);

        }
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpAutoMapperOptions>(options =>
            {
                options.AddMaps<PmsCloudApplicationModule>();
            });

            
        }
    }

```

```C#
 public static class RegisterInterceptors
    {
        public static void Register(IOnServiceRegistredContext context)
        {
            context.Interceptors.TryAdd<MethodExecuteLoggerInterceptor>();
        }
    }
```

```C#
  public class MethodExecuteLoggerInterceptor : AbpInterceptor, ITransientDependency
    {

        public override async Task InterceptAsync(IAbpMethodInvocation invocation)
        {
            var stopwatch = Stopwatch.StartNew();
            await invocation.ProceedAsync();
            stopwatch.Stop();
            Console.WriteLine("Executed method {0}.{1}.{2} ({3}) in {4}ms",
                invocation.Method.DeclaringType.Namespace,
                invocation.Method.DeclaringType.Name,
                invocation.Method.Name,
                invocation.Method.DeclaringType.Assembly.GetName().Name,
                stopwatch.ElapsedMilliseconds
            );
            return;
        }


    }
```

**Comment by inamvar** [comment]
> RegisterIfNeeded

I checked the `RegisterIfNeeded` method  and  `UnitOfWorkHelper` class.  The helper just check if the implementaionType has any specified attribute, and if one of its method has that attribute the interceptor will apply to  all off the methods of that class. and then I found that you checked the executing method in an  action filter separately at runtime. this is not  the solution I'm looking for. I'm looking for something that act like AspectJ in java.

**Comment by maliming** [comment]
hi

Can you filter the services you need interceptors here? Such as application services. Not all services can be intercepted.

```
 public static void Register(IOnServiceRegistredContext context)
{
     context.Interceptors.TryAdd<MethodExecuteLoggerInterceptor>();
}
```

**Comment by inamvar** [comment]
> hi
> 
> Can you filter the services you need interceptors here? Such as application services. Not all services can be intercepted.
> 
> ```
>  public static void Register(IOnServiceRegistredContext context)
> {
>      context.Interceptors.TryAdd<MethodExecuteLoggerInterceptor>();
> }
> ```

Yes, I filtered the services and the error has gone, but this solution is not as simple as AspectCore library. is there any way to use AspectCore instead of builtin Incterceptors?

**Comment by maliming** [comment]
> is there any way to use AspectCore instead of builtin Incterceptors?

Your problem is not related to the class library. 

![image](https://user-images.githubusercontent.com/6908465/74413916-4abbff80-4e7b-11ea-83a1-cfe4dce136dd.png)

The interceptor is abstract. If you are interested, you can try to replace it with other intercepting libraries.

https://github.com/abpframework/abp/blob/88ded4ef643f2eb8786574794b45b84e0d66e4f9/framework/src/Volo.Abp.Core/Volo/Abp/DynamicProxy/

**Comment by NewABPDeveloper** [comment]
> hi
> 
> Can you filter the services you need interceptors here? Such as application services. Not all services can be intercepted.
> 
> ```
>  public static void Register(IOnServiceRegistredContext context)
> {
>      context.Interceptors.TryAdd<MethodExecuteLoggerInterceptor>();
> }
> ```

Do you mean only application service can be intercepted? Other regular dotnet service cannot be intercepted by AbpInterceptor?
