### ISSUE TITLE
User login attempt audit log

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#2813]
In aspnetboilerplate we had a table to store user login attempts called `AbpUserLoginAttempts` with the following table structure:
![image](https://user-images.githubusercontent.com/22296715/74338004-491a0b00-4d99-11ea-98c4-ddc9d426a36a.png)

I'd like to implement something similar and I was wondering if there was plans to add this feature or if we are meant to use to use the current `AuditLogging` system? I *don't* want to log in a file as previously [mentioned here](https://github.com/abpframework/abp/issues/2273).

If we have to write our own `AuditLogContributor` then would it be possible to provide an example  on the docs for how to log user login attempts as I think it would be a useful example to include.

**Comment by maliming** [comment]
Maybe you can replace `SignInManager` for your own implementation and intercept login attempts in methods like `PasswordSignInAsync`.

**Comment by hikalkan** [comment]
Done with https://github.com/abpframework/abp/pull/4675

**Comment by olicooper** [comment]
Just tried this and it works exactly as expected for the MVC app and Angular client! Fantastic work guys ❤️
