### ISSUE TITLE
language-management/language-texts method return error

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#2814]
the language texts method of the language management services return below error:
`Unable to cast object of type "Volo.Abp.LanguageManagement.Dto.LanguageTextDto"to type Volo.Abp.Application.Dtos.PagedResultDto`1[Volo.Abp.LanguageManagement.Dto.LanguageTextDto]
System.InvalidCastException: Unable to cast object of type "Volo.Abp.LanguageManagement.Dto.LanguageTextDto"to type "Volo.Abp.Application.Dtos.PagedResultDto"1[Volo.Abp.LanguageManagement.Dto.LanguageTextDto]`

Please help fix it.

**Comment by maliming** [comment]
How to reproduce the problem?

**Comment by viewtance** [comment]
> How to reproduce the problem?

Using app-pro template with mvc tiered UI,  create a new application, did the db migration, run the application, click the language texts

**Comment by maliming** [comment]
Fixed in 2.1, may be released on February 20.
