### ISSUE TITLE
SelectItems in a CreateUpdateXDto in Application.Contracts

### ISSUE THREAD

**Issue by zHaytam** [abpframework/abp#2817]
Hello,

The only example I can find of `SelectItems` is where the model (dto) is in the razor page's model, but I don't think that's a good idea? (correct me if I'm wrong please).

If the model is in the Web project, it can't be used in our service. Imagine i'm handling products, each product has a category and upon its creation, I want the user to choose it. Usually I put the `CreateUpdateProductDto` in `Application.Contracts` and create an `IProductService` to work with it. But I can't have `SelectItems` in the application layer but I also can't have the dto in the presentation layer...

Any guidance will be greatly appreciated!

**Comment by maliming** [comment]
Dto should be a simple class. It can be serialized.

You can configure the mapping of the viewmodel class that contains the SelectItems property to the dto class.

**Comment by hikalkan** [comment]
I suppose you mean ` SelectlistItem`. However, I didn't understand the question.
