### ISSUE TITLE
Consider to save audit logs even if no action performed in the request

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2820]
https://github.com/abpframework/abp/blob/f47a0c1f5f8e9d224663b2d8c2f829c8b78f91b1/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingManager.cs#L125-L128

It doesn't save if no action or entity changes in the current request.

**Comment by hikalkan** [comment]
@maliming can you work on that (I don't remember why I did this, but probably not needed to check this)

**Comment by maliming** [comment]
ok

**Comment by maliming** [comment]
Consider this situation. 
```
using (var scope = _auditingManager.BeginScope())
{
	await scope.SaveAsync();
}
```
Is auditing meaningless if there is no action or entity change?

**Comment by hikalkan** [comment]
>Is auditing meaningless if there is no action or entity change?

I think we should still save since the developer wanted it 😄 

Normally, this is intended to be used by the framework in one place ([AbpAuditingMiddleware](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAuditingMiddleware.cs)) and no where else.
