### ISSUE TITLE
Acme.BookStore module example have wrong

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#2823]
when I download the Acme.BookStore module example, and run https://localhost:44349/BookManagement/Books,
I got a wrong msg:
"Cannot read property 'getList' of undefined" in the web/Pages/BookManagement/Books/index.js
so I add a BookController.cs in the path HttpApi/Books/,
and the code:
  `using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.AspNetCore.Mvc;

namespace Acme.BookStore.BookManagement.Books
{
    [RemoteService]
    [Route("api/BookManagement/book")]
    class BookController : BookManagementController, IBookAppService
    {
        private readonly IBookAppService _service;

        public BookController(IBookAppService service)
        {
            _service = service;
        }
        [HttpPost]
        public Task<BookDto> CreateAsync(CreateUpdateBookDto input)
        {
            return _service.CreateAsync(input);
        }
        [HttpDelete]
        [Route("{id}")]
        public Task DeleteAsync(Guid id)
        {
            return _service.DeleteAsync(id);
        }
        [HttpGet]
        [Route("{id}")]
        public Task<BookDto> GetAsync(Guid id)
        {
            return _service.GetAsync(id);
        }

        [HttpGet]
        public Task<PagedResultDto<BookDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            return _service.GetListAsync(input);
        }
        [HttpPut]
        [Route("{id}")]
        public Task<BookDto> UpdateAsync(Guid id, CreateUpdateBookDto input)
        {
            return _service.UpdateAsync(id, input);
        }
    }
}
`
but still, I got the same error. and when I run https://localhost:44349/swagger/index.html,
I can't see the Book Api, so , have I missed something? or is a bug？

**Comment by maliming** [comment]
> when I download the Acme.BookStore module example

Which module example?

![image](https://user-images.githubusercontent.com/6908465/74434055-9632d580-4e9c-11ea-9883-df7345d3dbc3.png)

**Comment by zsanhong** [comment]
yes ,modules/book-management

**Comment by maliming** [comment]
I ran the `\abp\samples\BookStore-Modular\application\src\Acme.BookStore.Web\Acme.BookStore.Web` project and did not reproduce your problem.

![image](https://user-images.githubusercontent.com/6908465/74494760-db90ea80-4f10-11ea-89c4-fd6f5a0f0c6c.png)

**Comment by zsanhong** [comment]
Thank you maliming。If you use abp cli to create the module,then you will encounter this problem. And now I know the reason, because the web project did not reference the application project, and did not add the follow code in the BookManagementWebModule.cs like :
``Configure<AbpAspNetCoreMvcOptions>(options =>
            {
                options.ConventionalControllers.Create(typeof(BookManagementApplicationModule).Assembly);
            });
