### ISSUE TITLE
How to mock CurrentUser in unit test

### ISSUE THREAD

**Issue by xxyuze** [abpframework/abp#2827]

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/search?utf8=%E2%9C%93&q=Substitute.For%3CICurrentUser%3E&type=

**Comment by xxyuze** [comment]
CurrentUser allways be null in AppService tests.

![image](https://user-images.githubusercontent.com/17399581/74503643-7d720080-4f2c-11ea-9558-a866e603edb3.png)

![image](https://user-images.githubusercontent.com/17399581/74503673-9a0e3880-4f2c-11ea-8fe5-7e6ec7268f01.png)

![image](https://user-images.githubusercontent.com/17399581/74503684-a72b2780-4f2c-11ea-9b90-f0945ac78c5f.png)

**Comment by maliming** [comment]
Please use Interface instead of class.

![image](https://user-images.githubusercontent.com/6908465/74503807-1bfe6180-4f2d-11ea-8030-f25f436e3d02.png)

**Comment by xxyuze** [comment]
The same error happened

![image](https://user-images.githubusercontent.com/17399581/74504411-0be78180-4f2f-11ea-8502-295cd0ec3108.png)

![image](https://user-images.githubusercontent.com/17399581/74504480-47824b80-4f2f-11ea-8953-a353f76e91ee.png)

**Comment by acjh** [comment]
Show code for `GroupAppService`.

**Comment by xxyuze** [comment]
I make project from empty AspNet Core MVC Web Application Template

![image](https://user-images.githubusercontent.com/17399581/74510457-caf76900-4f3e-11ea-8428-07a7602de8b5.png)
![image](https://user-images.githubusercontent.com/17399581/74510489-e06c9300-4f3e-11ea-9d52-e2a79b797710.png)

**Comment by maliming** [comment]
@xxyuze Please share the full steps to reproduce the problem.
