### ISSUE TITLE
How to Test MemoryCache Module

### ISSUE THREAD

**Issue by nexawo** [abpframework/abp#2830]
I am using ABP memory cache in my project where it first gets data from DB and then on second run it's load data from the cache and also I have written a function which clears the cache if a new record insert.

Now I created a test for inserting a new record which is working fine but I also want to test that is the cache is also getting cleared when new record inserts.

**Comment by maliming** [comment]
You can test it by injecting the cache interface and checking if the previous key exists.

**Comment by hikalkan** [comment]
This is how we've implemented the test in the framework:

https://github.com/abpframework/abp/blob/2e20131ed8c83d6fb926dfa6da3b5215d2aa10c8/framework/test/Volo.Abp.Caching.Tests/Volo/Abp/Caching/DistributedCache_Tests.cs#L11-L38

So, you can it similar for your side.
