### ISSUE TITLE
ABP CLI Replace Packages with Previews

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2837]
We re-started to release nightly previews. However, it is tedious to replace all NuGet/NPM packages with the previews and return to stables when its released.

So, add a new command to the ABP CLI to replace all NuGet/NPM packages with the previews and vice verse. Example commands:

````
abp --switch-to-preview
abp --switch-to-stable
````

If anyone has a better command name, it is appreciated :)

**Comment by acjh** [comment]
How about:

```sh
abp sources switch --preview
abp sources switch --stable
```

Inspired by `nuget sources`: https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources

**Comment by hikalkan** [comment]
Good suggestion. But "source" has a single meaning for NuGet, while it may mean "the source of the modules" for abp. We have/will another command to replace a module reference by its source code, so a root "sources" command would not be suitable. Maybe "abp package-sources -p" and "abp package-sources -s" (long versions are --preview and --stable).

**Comment by acjh** [comment]
> replace a module reference by its source code

Do you mean replace a remote reference with a local reference?

**Comment by hikalkan** [comment]
You know, startup project is using the modules as NuGet packages. For example, for the Identity module, you don't have the source code. We will try to add a command to CLI to remove Identity Nuget packages, download and add [its source code](https://github.com/abpframework/abp/tree/dev/modules/identity) directly into the current solution, so you can freely modify it.
