### ISSUE TITLE
Cannot resolve parameter 'Volo.Abp.Caching.IDistributedCache

### ISSUE THREAD

**Issue by mabusaa** [abpframework/abp#2839]
I am trying to use Redis cache in .net core 3.1 , I am injecting the interface "IDistributedCache" in App service constructor , but I am receiving the below error :

---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.RequestStatusAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Caching.IDistributedCache`1[System.Collections.Generic.List`1

Module Configuration

````csharp
private void ConfigureRedis(
            ServiceConfigurationContext context,
            IConfiguration configuration,
            IWebHostEnvironment hostingEnvironment)
        {

            context.Services.AddStackExchangeRedisCache(options =>
            {
                options.Configuration = configuration["Redis:Configuration"];
            });

            var redis = ConnectionMultiplexer.Connect(configuration["Redis:Configuration"]);
            context.Services
                .AddDataProtection()
                .PersistKeysToStackExchangeRedis(redis, "Coo-Protection-Keys");
        }
````

**Comment by hikalkan** [comment]
Are you injecting `IDistributedCache<List<T>>`? I suggest you to create another class to use for the cache and add `List<T>` inside it.
We didn't test well with generics as the `IDistributedCache` type parameter.
We can try to add this support if it is not supported, but first I want to understand if it works as I said.

**Comment by mabusaa** [comment]
My bad , Solved by adding [DependsOn(typeof(AbpCachingModule))]

**Comment by mabusaa** [comment]
It will be great if this was added to documentation @hikalkan

**Comment by hikalkan** [comment]
Startup templates already has this dependency, so didn't need to document. However, you are right, anyone may start with an empty project and want to use the caching module. Created an issue: https://github.com/abpframework/abp/issues/2842

**Comment by Jesn** [comment]
> Are you injecting `IDistributedCache<List<T>>`? I suggest you to create another class to use for the cache and add `List<T>` inside it. We didn't test well with generics as the `IDistributedCache` type parameter. We can try to add this support if it is not supported, but first I want to understand if it works as I said.


```
 private readonly IDistributedCache<List<SpeedTestJobV2Args>, string> _speedTestJobArgCache;

 await _speedTestJobArgCache.SetAsync("SpeedTestJobV2Args",
                listArgs,
                new DistributedCacheEntryOptions()
                {
                    SlidingExpiration = TimeSpan.FromHours(2)
                }, token: cancellationToken);
```

Found the generated redis key as follows
```
c:System.Collections.Generic.List`1[[Rich.MagicNetWork.BackgroundJob.SpeedTest.Dto.SpeedTestJobV2Args, Rich.MagicNetWork.BackgroundJob, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]],k:MagicNetwork:speedTestArgs
```
