### ISSUE TITLE
Dynamic C# API Clients - .Net-Standard

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#2847]
Hello,

we're currently evaluating abp for our products. 
Our client-applications (.NetFX 4.8 / WinForms) will be powered by a abp-based backend and we would like to elevate the Dynamic C# API Clients for the client applications.

Unfortunately the Volo.Abp.Http.Client depends on .net core 3.1 therefore the generated clients are using .net core 3.1 too. Is there any way to make the clients .net standard 2.0 (or 2.1) compatible?

**Comment by xewn** [comment]
[Multiple version](https://github.com/abpframework/abp/issues/2401)

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2294
