### ISSUE TITLE
[Question] - Customizing default API

### ISSUE THREAD

**Issue by newacc12** [abpframework/abp#2851]
I just generated a new project with no UI (--ui none) and I see there are some routes in Swagger by default. How can I customize/remove those? 

For some of the routes (e.g. api/account/register) I want to completely replace with mine while others I want to remove because I won't be using them.

Thanks,

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/2787#issuecomment-583873851 and https://github.com/abpframework/abp/issues/2533#issuecomment-570939959 for a general response on the customization of the current modules.

**Comment by newacc12** [comment]
@maliming thanks for the fast response. So as far as I understand the best current way is to copy the code and use inside my app but there will be changes to allow it easily in the future, right? If that is the case we can close this.

**Comment by maliming** [comment]
This is currently the only way.
