### ISSUE TITLE
how can i use sql server and mysql in tow DbContexts? 

### ISSUE THREAD

**Issue by doufeng007** [abpframework/abp#2858]
i have tow DbContexts in a sln, one use sql server, one use mysql,  In fact, it's all used one.

**Comment by leonkosak** [comment]
Two different SQL providers also requires two different migrations (because migrations are sql-dependent code).

**Comment by doufeng007** [comment]
sql server DbContext does not need  migrate.

**Comment by doufeng007** [comment]
in one EntityFrameworkCoreModule  i use   `options.UseSqlServer();`   the other one i use  `UseMySql` 

but, in the db query, all use"
 Microsoft.EntityFrameworkCore.Infrastructure
` using provider '"Pomelo.EntityFrameworkCore.MySql"' `

**Comment by maliming** [comment]
Unable to understand, did you encounter an error?

**Comment by doufeng007** [comment]
one dbContext code:

```
public class QAEntityFrameworkCoreModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<Eplus_QAContext>(options =>
            {
                options.AddDefaultRepositories(includeAllEntities: true);

            });

            Configure<AbpDbContextOptions>(options =>
            {
                /* The main point to change your DBMS.
                 * See also BookStoreMigrationsDbContextFactory for EF Core tooling. */
                options.UseSqlServer();
            });
        }
    }
```


the other one dbContext code ; it is default:

```
 public class EplusDoctorToolEntityFrameworkCoreModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<EplusDoctorToolDbContext>(options =>
            {
                /* Remove "includeAllEntities: true" to create
                 * default repositories only for aggregate roots */
                options.AddDefaultRepositories(includeAllEntities: true);
            });

            Configure<AbpDbContextOptions>(options =>
            {
                /* The main point to change your DBMS.
                 * See also EplusDoctorToolMigrationsDbContextFactory for EF Core tooling. */
                options.UseMySQL();
            });
        }
    }
```


Host Code:


 ```
   [DependsOn(
        typeof(EplusDoctorToolHttpApiModule),
        typeof(AbpAutofacModule),
        typeof(AbpAspNetCoreMvcUiMultiTenancyModule),
        typeof(EplusDoctorToolApplicationModule),
        typeof(QAEntityFrameworkCoreModule),
        typeof(EplusDoctorToolEntityFrameworkCoreDbMigrationsModule),
        typeof(AbpAspNetCoreSerilogModule)
        )]
```


Now  I  use  like this:  tableA is in Eplus_QAContext.

```
  public class TestAppService : ApplicationService, ITestAppService
    {
        private readonly IRepository<tableA, string> _qARepository;

        public TestAppService(IRepository<TBAskMain, string> qARepository)
        {
            _qARepository = qARepository;
        }

        public async Task<string> Test()
        {
            var count = await _qARepository.GetCountAsync();
            return "123";
        }
    }
```

I get an error:


 Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter
An exception was thrown while activating EplusDoctorTool.QA.EntityFrameworkCore.QA_Models.Eplus_QAContext -> λ:Microsoft.EntityFrameworkCore.DbContextOptions`1[[EplusDoctorTool.QA.EntityFrameworkCore.QA_Models.Eplus_QAContext, EplusDoctorTool.QA.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].
Autofac.Core.DependencyResolutionException: An exception was thrown while activating EplusDoctorTool.QA.EntityFrameworkCore.QA_Models.Eplus_QAContext -> λ:Microsoft.EntityFrameworkCore.DbContextOptions`1[[EplusDoctorTool.QA.EntityFrameworkCore.QA_Models.Eplus_QAContext, EplusDoctorTool.QA.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].
 ---> System.ArgumentException: Option 'trusted_connection' not supported.
   at MySql.Data.MySqlClient.MySqlConnectionStringOption.GetOptionForKey(String key) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnectionStringBuilder.cs:line 435


Eplus_QAContext   use `UseSqlServer`

**Comment by maliming** [comment]
Try the code below, if it doesn't work, please use cli to create a project that reproduces the problem and then share it.

```c#
public class EplusDoctorToolEntityFrameworkCoreModule : AbpModule
{
	public override void ConfigureServices(ServiceConfigurationContext context)
	{
		context.Services.AddAbpDbContext<EplusDoctorToolDbContext>(options =>
		{
			/* Remove "includeAllEntities: true" to create
			 * default repositories only for aggregate roots */
			options.AddDefaultRepositories(includeAllEntities: true);
		});

		Configure<AbpDbContextOptions>(options =>
		{
			/* The main point to change your DBMS.
			 * See also MyProjectNameMigrationsDbContextFactory for EF Core tooling. */
			options.Configure<EplusDoctorToolDbContext>(context =>
			{
				context.UseMySQL();
			});
		});

	}
}
```

**Comment by doufeng007** [comment]
@leonkosak     it works;    thank you very much!
