### ISSUE TITLE
How can I use Apb.Localization in DataAnnotations localization?

### ISSUE THREAD

**Issue by zredb** [abpframework/abp#2860]
Hi,

  In asp.net core,DataAnnotations error messages are localized with IStringLocalizer<T>,the error messages in RegisterViewModel can be stored in either of the following paths:
```
Resources/ViewModels.Account.RegisterViewModel.fr.resx
Resources/ViewModels/Account/RegisterViewModel.fr.resx 
```
```
public class RegisterViewModel
{
[Required(ErrorMessage = "The Email field is required.")]
[EmailAddress(ErrorMessage = "The Email field is not a valid email address.")]
[Display(Name = "Email")]
public string Email { get; set; }
[Required(ErrorMessage = "The Password field is required.")]
[StringLength(8, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
[DataType(DataType.Password)]
[Display(Name = "Password")]
public string Password { get; set; }
[DataType(DataType.Password)]
[Display(Name = "Confirm password")]
[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
public string ConfirmPassword { get; set; }
}
```
but in abp.localization, the use of localation is introduced in ca https://docs.abp.io/en/abp/latest/Localization
but this document don't state how to use the DataAnnotations localization. Can someone give me some tips?

**Comment by maliming** [comment]
The framework already has these localization messages built in. You just need to provide localization of the fields.

https://github.com/abpframework/abp/blob/3ba06fe0227b86099f3aa718b5d3976bb0e4bbe0/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/Localization/en.json#L4-L18

https://github.com/abpframework/abp/blob/1a84e8ade17ae8978e50e6d03fb7367de2357c19/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L253

https://github.com/abpframework/abp/blob/2328841062a6f11cc1070e9efd2b8e6f857d4bc1/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/Resources/en.json#L6

**Comment by ankyo** [comment]
your answer as document too simple, can with codes?

**Comment by hikalkan** [comment]
For example, for the  `public string ConfirmPassword { get; set; }` don't define any `DisplayName` attribute. Just add a `DisplayName:ConfirmPassword` (or `ConfirmPassword`) key to your localization json file in the Domain.Shared project. ABP automatically finds and matches it.
