### ISSUE TITLE
Question: DDD Documentation seems inconsistent

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2862]
Using newly created project using version 2.0.1

Following [DDD - Application Layer - Application Services](https://docs.abp.io/en/abp/latest/Application-Services#ibookappservice-interface), while it says to use [StringLength(Book.MaxNameLength)] on CreateBookDto, this dto is located at Contracts project and this project depends only on Domain.Shared, while Book entity is located at Domain. 

While trying update Contracts project references
Domain.Shared - ok
Domain - error, as it is a .net core 3.1 project and cannot be referenced. 

So I changed Domain to .net standard, as it is a class library and must be accesible to a wide range of versions from .NET (as it contains entities etc, I could reference it on legacy systems for example). 

Domain project could target .net standard from the start and Contracts project reference it from the start?

**Comment by maliming** [comment]
`Book.MaxNameLength`  should exist as a constant in the `Domain.Shared` layer. The documentation needs to be updated.

see:
https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/IdentityUserConsts.cs#L7

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/IdentityUserCreateOrUpdateDtoBase.cs#L9

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Best-Practices/Module-Architecture
