### ISSUE TITLE
pack.ps1 : error during nuget packing

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2863]
Hi,

I wish to build, pack and push the nuget to my own private server server.

So I have build, then I use the nuget/pack.ps1 script, but I got a crash :

> .nuget\packages\sourcelink.create.commandline\2.8.3\build\SourceLink.Create.CommandLine.targets(21,5): error MSB3073: the command "git rev-parse --show-toplevel" has stopped with the code 128.

I have search for, but cannot find any 'git' command anywhere... any idea ?

**Comment by maliming** [comment]
Does your computer have git installed?

https://git-scm.com/

**Comment by vd3d** [comment]
no, and I don't want to do any interaction with GIT... I work on my local computer without any GIT !
I wish to remove / disable any GIT call... but how ?
