### ISSUE TITLE
Docs Module is not Updated

### ISSUE THREAD

**Issue by pranavpatil19** [abpframework/abp#2864]
Please update
https://docs.abp.io/en/abp/latest/Modules/Docs

INSERT [dbo].[DocsProjects] ([Id], [Name], [ShortName], [Format], [DefaultDocumentName], [NavigationDocumentName], [MinimumVersion], [DocumentStoreType], [ExtraProperties], [MainWebsiteUrl], [LatestVersionBranchName]) VALUES (N'12f21123-e08e-4f15-bedb-ae0b2d939658', N'Document Master', N'doc', N'md', N'Index', N'docs-nav.json', NULL, N'GitHub', N'{"GitHubRootUrl":"https://github.com/pranavpatil19/DocumentMaster/tree/Master/docs","GitHubAccessToken":"****"}', N'/', N'master')

Not working

**Comment by pranavpatil19** [comment]
@maliming Please help.. i implement Doc Module as per document.but get 404 error after redirect .. please provide sample project for doc module ..its help me lot

**Comment by maliming** [comment]
There is already a demo project.
https://github.com/abpframework/abp/tree/dev/modules/docs/app

You can open the project url after creating the docs project.
eg: **abp** is the project `short name`.
http://localhost:55008/abp

**Comment by pranavpatil19** [comment]
Its nOt working

Please help ...  Get page not found 400 error message

https://github.com/pranavpatil19/DocTest1/tree/master

USE [DocumentTest]
GO
INSERT [dbo].[DocsProjects] ([Id], [ExtraProperties], [ConcurrencyStamp], [Name], [ShortName], [Format], [DefaultDocumentName], [NavigationDocumentName], [ParametersDocumentName], [MinimumVersion], [DocumentStoreType], [MainWebsiteUrl], [LatestVersionBranchName]) VALUES (N'12f21123-e08e-4f15-bedb-ae0b2d939658', N'{"GitHubRootUrl":"https://github.com/pranavpatil19/DocTest1/tree/master/docs","GitHubAccessToken":"***"}', NULL, N'Document Master', N'doc', N'md', N'Index', N'docs-nav.json', N'', NULL, N'GitHub', N'/', N'master')
INSERT [dbo].[DocsProjects] ([Id], [ExtraProperties], [ConcurrencyStamp], [Name], [ShortName], [Format], [DefaultDocumentName], [NavigationDocumentName], [ParametersDocumentName], [MinimumVersion], [DocumentStoreType], [MainWebsiteUrl], [LatestVersionBranchName]) VALUES (N'12f21123-e08e-4f15-bedb-ae0b2d939659', N'{"Path":"V:\\Master1\\DocTest1"}', NULL, N'Document Master (FileSystem)', N'doc', N'md', N'Index', N'docs-nav.json', N'', NULL, N'FileSystem', N'/', NULL)

**Comment by maliming** [comment]
try
```
"GitHubRootUrl":"https://github.com/pranavpatil19/DocTest1/tree/{version}/docs"
```

**Comment by pranavpatil19** [comment]
Not working ......  get 400 error

**Comment by maliming** [comment]
>There is already a demo project.
>https://github.com/abpframework/abp/tree/dev/modules/docs/app

>You can open the project url after creating the docs project.
>eg: abp is the project short name.
http://localhost:55008/abp

```sql
INSERT INTO [dbo].[DocsProjects]([Id], [ExtraProperties], [ConcurrencyStamp], [Name], [ShortName], [Format], [DefaultDocumentName], [NavigationDocumentName], [ParametersDocumentName], [MinimumVersion], [DocumentStoreType], [MainWebsiteUrl], [LatestVersionBranchName]) VALUES ('F3D42C0D-451B-DFE4-1285-39F34A16B0FE', N'{"GitHubRootUrl":"https://github.com/abpframework/abp/tree/{version}/docs/","GitHubUserAgent":null,"GitHubAccessToken":"***"}', N'b41df31fef784ead89e4a2a581cdbf70', N'abp', N'abp', N'md', N'Index', N'docs-nav.json', N'', NULL, N'GitHub', NULL, N'dev');
```

**Comment by pranavpatil19** [comment]
ok i will try this ... But dont know what is missing step in my project... and why its not working.. if you have time just look its really help me

**Comment by maliming** [comment]
You already have its source code and you can troubleshoot the problem based on the application's logs.

**Comment by pranavpatil19** [comment]
KeyNotFoundException: The given key 'GitHubUserAgent' was not present in the dictionary.

**Comment by pranavpatil19** [comment]
I dont know what is problem ... i follow every step...  not working...   document  is not well documented ..
working from last 2 day but still not understand...  git and local doc also not working

**Comment by maliming** [comment]
abp **dev** branch code.
You can troubleshoot the problem based on the application's logs.


![image](https://user-images.githubusercontent.com/6908465/75020931-94859500-54ce-11ea-968f-5aac21168279.png)

**Comment by pranavpatil19** [comment]
SecurityException: Can not get a resource file out of the project folder!
Volo.Docs.FileSystem.Documents.FileSystemDocumentSource.CheckDirectorySecurity(string projectFolder, string path)

extrapropoerty : documenting missing

**Comment by pranavpatil19** [comment]
SecurityException: Can not get a resource file out of the project folder!
Volo.Docs.FileSystem.Documents.FileSystemDocumentSource.CheckDirectorySecurity(string projectFolder, string path)

extrapropoerty : documenting missing 

@maliming  Please update doc module document incomplete ... if you have working source code for doc module please share...

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/3073
