### ISSUE TITLE
Tiered application : how authentication is propagated ?

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2866]
Hi,

In the context of the Tiered applicatio, when I login on the Web app, how does the
Host app know that I'm authenticated and how does it retrieve the current user ?

I ask because it failed in my application, it is related to this:
https://github.com/abpframework/abp/issues/2811

I try to fix it, but need some driving :-P

**Comment by maliming** [comment]
Duplicate of #2811 Please discuss in #2811.
