### ISSUE TITLE
`ConfigurationHelper` should support in-memory collections

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#2870]
I'm currently building some unit tests based on `AbpIntegratedTest` for one of my modules.
Since some ABP modules use `AbpModule.Configure<TOptions>(IConfiguration configuration)`, I can't use fixed values in my tests out-of-the-box for the built in abp-modules.

This issue can easily fixed by adding a `InMemoryCollection` property to `AbpConfigurationBuilderOptions`. Here`s a commit that I can open a PR for: https://github.com/NecatiMeral/abp/commit/75d332371c86068fbf393d3bb0a688fa995b4327

**Comment by maliming** [comment]
Can you explain the problem in detail?

**Comment by NecatiMeral** [comment]
When I attempt to use the `Volo.Abp.Http.Client` package in a test project, I can't specify the `IdentityClients` configuration because the client uses the `Configure` method to read this from the app configuration. 
A way to resolve this would be to implement the configuration as a fixed dictionary in-memory and just pass it to the `AbpApplicationCreationOptions.Configuration` in my `MyModule.TestBase.SetAbpApplicationCreationOptions` implementation.

**Comment by maliming** [comment]
hi

We should mock components in unit tests rather than adapt them to unit tests.

There are many mocked implementations in unit tests of frameworks and modules, you can refer to them.

**Comment by NecatiMeral** [comment]
Okay, I will test it out and think I can live with it. 😄
