### ISSUE TITLE
Maybe entities that implement IMultiTenant should have TenantId index by default.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#2871]
https://github.com/abpframework/abp/blob/bf07efd8e1a5b11cf3c6ef75dc405661a12387df/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/Modeling/AbpEntityTypeBuilderExtensions.cs#L252-L260

The GetListAsync() method could run slowly if there are many tenants.

**Comment by maliming** [comment]
> The GetListAsync() method could run slowly if there are many tenants.

why?

**Comment by gdlcf88** [comment]
A multi tenant entity datatable may have more than 99.9% of rows that not belong to current tenant, and GetListAsync() of the repository will query with specified TenantId. Maybe we can consider multi tenant entities always need the TenantId index.

**Comment by hikalkan** [comment]
Assume that we create a TenantId index by default and you create a separate UserName index. What would happend when you query by UserName (remember, ABP adds TenantId to the where condition by default)? It will select one of the indexes, but can not utilize both. It would be better to define a composite index like `TenantId, UserName`.

So, it would be better to carefully & manually create indexes based on your entity.

What do you think?

**Comment by gdlcf88** [comment]
> It would be better to define a composite index like TenantId, UserName.

Yes, `IX_MyEntity_TenantId_UserName` is better for the scene _query by UserName_, and it helps `GetListAsync()` too.

But we can also create both `IX_MyEntity_TenantId` and `IX_MyEntity_UserName_TenantId` (UserName in front), because the selectivity of UserName is higher so the index can play a better role.

Maybe we can consider that the selectivity of TenantId is always the lowest, so we create a exclusive index `IX_MyEntity_TenantId` for it.

And by the way, `IX_MyEntity_TenantId` may be used by index_merge.
