### ISSUE TITLE
about  existing users and permissions   best practice

### ISSUE THREAD

**Issue by 3151036158** [abpframework/abp#2873]
Is there any implementation document or tutorial for existing users and permissions? I want to implement micro services on the basis of existing users and permissions. There is no need to bring your own user and permissions asp.net core identity.

**Comment by maliming** [comment]
There are currently no related documents.

You can consider migrating existing users and permissions to ABP's module architecture.

**Comment by 3151036158** [comment]
Migration is equivalent to using ABP's module architecture.

**Comment by maliming** [comment]
You can refer to the source code below to try to use your existing users and permissions.
If necessary, you can replace the components in them.

https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Authorization
https://github.com/abpframework/abp/tree/dev/modules/permission-management

**Comment by 3151036158** [comment]
Thank you, that's what I'm thinking, implementing interfaces(Volo.Abp.Authorization,Voloabp.User.permission-management), but I think most developers run into this problem and want to see what the best way to share it is.
