### ISSUE TITLE
after Application.Contract module depended on the AbpDddApplication module,the AddAlwaysAllowAuthorization invalid

### ISSUE THREAD

**Issue by Maple512** [abpframework/abp#2874]
en: as shown in the title,after Application.Contract module depended on the AbpDddApplicationModule module,the AddAlwaysAllowAuthorization invalid,or after the AbpDddApplicationModule not dependent,AuthorizeAttribute is invalid.

above, found in the xUnit test

Can be reproduced in the Volo.Blogging

zh-Hans: Applicatoin.Contract模块在 DepensNo 中加入 AbpDddApplicationModule 后，AddAlwaysAllowAuthorization 无效，或者 注释 Application.Contract中的[DepensOn(typeof(AbpDddApplicationModule)] 后，[Authorize] 无效

以上，在单元测试中发现

在Volo.Blogging中可以复现

**Comment by maliming** [comment]
Please share the code that reproduces your problem.

**Comment by Maple512** [comment]
> Please share the code that reproduces your problem.

you can try it in the volo.blogging

**Comment by maliming** [comment]
Try
```
public class BloggingApplicationTestModule : AbpModule
{
	public override void ConfigureServices(ServiceConfigurationContext context)
	{
		context.Services.AddAlwaysAllowAuthorization();
		context.Services.Replace(ServiceDescriptor.Singleton<IMethodInvocationAuthorizationService, AlwaysAllowMethodInvocationAuthorizationService>());
	}
}

public class AlwaysAllowMethodInvocationAuthorizationService : IMethodInvocationAuthorizationService
{
	public Task CheckAsync(MethodInvocationAuthorizationContext context)
	{
		return Task.CompletedTask;
	}
}
```

**Comment by Maple512** [comment]
thanks👍
