### ISSUE TITLE
Official CAP Integration

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2878]
Thanks to @geffzhang implemented [CAP](https://github.com/dotnetcore/CAP/) integration for the ABP Framework ([see](https://github.com/EasyAbp/Yhd.Abp.EventBus.CAP)).

We will consider to add it to the ABP Framework as an official package and document it.

**Comment by volethanh** [comment]
hi @hikalkan, is there any plan to integrate this feature to the ABP Framework ?

**Comment by hikalkan** [comment]
It is planned, but has no high priority. I haven't investigated the project yet. You can already use https://github.com/EasyAbp/Abp.EventBus.CAP it is up to date.

**Comment by hikalkan** [comment]
We won't integrate CAP since we've already done https://github.com/abpframework/abp/issues/6126
