### ISSUE TITLE
Disabled Multi-Tenancy and get the boolean 

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#2879]
hello ,
When  i disabled  MultiTenancy,
``` csharp
namespace FSTest.MultiTenancy
{
    public static class MultiTenancyConsts
    {
        /* Enable/disable multi-tenancy easily in a single point.
         * If you will never need to multi-tenancy, you can remove
         * related modules and code parts, including this file.
         */
        public const bool IsEnabled = false;
    }
}
```
Where can i get  MultiTenancy.IsEnabled  value  in anuglar?

In aspnetzero  version,when i disabled multiTenancy  , i can get the value from javascript  
``` javascript
abp.multiTenancy.isEnabled = false
```

In AbpVnext 
(In angular)ConfigState,SessionState ,dont have multiTenancy.isEnable

here is my use case 
1. i want to hide tenant selector in login page when multiTenancy  is disabled.
2. When admin login in , I want to hide the page "tenant management".

**Comment by hikalkan** [comment]
Depends on https://github.com/abpframework/abp/issues/2982
