### ISSUE TITLE
ApplicationAutoMapperProfile call Twice on start

### ISSUE THREAD

**Issue by cheetahing** [abpframework/abp#2884]
I have two module,the HttpApi.Host modeule DependsOn the tow module.
one module ApplicationAutoMapperProfile call twice on start,first call is work well,second call throw exception.

Exception message
``` Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
===========================================================================
CreateAndUpdateMaterialDto -> Material (Destination member list)
BigCat.Basic.Materials.CreateAndUpdateMaterialDto -> BigCat.Basic.Material (Destination member list)

Unmapped properties:
ExtraProperties
ConcurrencyStamp
Id
```

Domain
``` 
public class Material: AggregateRoot<Guid>
    {
        public Material()
        {
        }

        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
    }
```

Dto
```
    public class CreateAndUpdateMaterialDto
    { 
	   /// <summary>
	  /// 名称
	  /// </summary>
        public string Name { get; set; }
    }
```

mapper
```
            CreateMap<Material,MaterialDto>();
            CreateMap<CreateAndUpdateMaterialDto, Material>();
```

**Comment by cheetahing** [comment]
Find the bug code,if is a bug

```
           Configure<AbpAutoMapperOptions>(options =>
            {
                options.AddMaps<BasicApplicationModule>(/*validate: true*/);
            });
```
if validate is **true** throw the exception.But i new a template project is default **true**.  
if validate is **false** work well.

Please tell me why?

**Comment by acjh** [comment]
From https://docs.abp.io/en/abp/latest/Object-To-Object-Mapping#configuration-validation:

> it is suggested to enable configuration validation as a best practice.

From https://docs.automapper.org/en/stable/Configuration-validation.html#selecting-members-to-validate:

> By default, AutoMapper uses the destination type to validate members. It assumes that all destination members need to be mapped. To modify this behavior, use the `CreateMap` overload to specify which member list to validate against

Fix your code:

```diff
- CreateMap<CreateAndUpdateMaterialDto, Material>();
+ CreateMap<CreateAndUpdateMaterialDto, Material>(MemberList.Source);
```
