### ISSUE TITLE
Could not find embedded resource files with dots(.) and bars(-) in the file name

### ISSUE THREAD

**Issue by yshulin** [abpframework/abp#2885]
I have two embedded resource files:
"/libs/bootstrap/dist/css/bootstrap-theme.css" and "/libs/bootstrap/dist/css/bootstrap-theme.min.css",
The "bootstrap-theme.css" file can be found nomarlly, but the "bootstrap-theme.min.css" file can not be found, I don't know why?

And I foud that all embedded files have "XXX-XX.XX.X" format can not be found. jus like:
"/libs/jQueryUI/**jquery-ui.min.js**"
"/libs/bootstrap3-wysihtml5-npm/dist/**bootstrap3-wysihtml5.all.js**"

**Comment by yshulin** [comment]
my abp version was 2.0.1

**Comment by hikalkan** [comment]
This should be related to https://github.com/aspnet/FileSystem/issues/184

We have an issue to track it: https://github.com/abpframework/abp/issues/128

For now, try to not use such file names. We will work on this.
