### ISSUE TITLE
The src attribute value of abp-script and abp-style tags can not start with "~/"

### ISSUE THREAD

**Issue by yshulin** [abpframework/abp#2886]
I have the below code in razor page:
`<abp-script src="~/libs/jvectormap/jquery-jvectormap.js" />`

but the result code in the page was below:
`<script src="~/libs/jvectormap/jquery-jvectormap.js"></script>`

so, the "jquery-jvectormap.js" file can not be found in the page.

**Comment by viewtance** [comment]
Do you use the abp-srcript tag?

**Comment by yshulin** [comment]
@viewtance  yes, abp-script was used.

**Comment by hikalkan** [comment]
Just use `<abp-script src="/libs/jvectormap/jquery-jvectormap.js" />` (without `~`), it should work.
