### ISSUE TITLE
How to : change user's tenant Id

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2888]
Hi,

How can I change user's tenant Id ? I have create a new tenant, but how to assign it to my user ?

Also, I'm lost in all the 'users' we have here, is there some guide about this ?
- IdentityUser
- ICurrentUser + CurrentUser
- AppUser

and so, how to add/update/delete all theses users, how to add properties etc?

thanks

**Comment by Znow** [comment]
@vd3d What was the solution to this?
