### ISSUE TITLE
Unexpected decrease of memory

### ISSUE THREAD

**Issue by xiangxingxing** [abpframework/abp#2891]
With the upgrade of abpframework recently,  I've attempted to update the packages of abp to the latest version in our project. A problem about memory was found in monitor during auto-tests. 

1. With "Volo.Abp-1.1.2", the memory tends to be stable finally after handling various affairs，which is expected.
![1 1 2](https://user-images.githubusercontent.com/52204046/75093346-c58fc380-55bb-11ea-9034-99a5d4f56e35.png)
2.  With "Volo.Abp-2.0.1", the memory decreased obviously to the end.
![2 0 1](https://user-images.githubusercontent.com/52204046/75093400-52d31800-55bc-11ea-80b9-de92e1718a3d.png)
3.  With "Volo.Abp-2.1.1", the memory decreased slowly than the scenario depending on Volo.Abp-2.0.1.
![2 1 1](https://user-images.githubusercontent.com/52204046/75093567-c295d280-55bd-11ea-9996-72bc5df3151f.png)

I'm confused about this phenomenon and can't target the reason till now. May be it's caused by incorrect use of the new abp version.  I’ll appreciate it if you can give me some suggestions.

**Comment by hikalkan** [comment]
Hi @xiangxingxing I don't have an idea with such limited information. It seems there is no memory leak, which is a good thing.

**Comment by xiangxingxing** [comment]
> Hi @xiangxingxing I don't have an idea with such limited information. It seems there is no memory leak, which is a good thing.
Got it.  Many thanks!
