### ISSUE TITLE
Using localization resource in application service

### ISSUE THREAD

**Issue by zHaytam** [abpframework/abp#2894]
Hello,

In my service, a property `L` is available in order to localize strings.  
The problem is that the `LocalizationResource` points to a `DefaultResource` in the implementation of `ApplicationService`, but my localized strings are in the resource available in `Domain.Shared.Localization`.

I'm wondering if this is the normal behaviour?  

My current work around is:
```cs
public MyService(IRepository<Entity, Guid> repository) : base(repository)
{
    LocalizationResource = typeof(ProjectNameResource);
}
```

**Comment by maliming** [comment]
Yes see https://github.com/abpframework/abp/commit/4c1e36f81d766789e998a6b80a6893c1253f443a .
