### ISSUE TITLE
CRITICAL BUG : IdentityUserAppService : no tenant management

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2896]
Hi,

We can create a role per tenant, by using 'IdentityRole'. This way, each tenant can have its own role.

**_An example:_**

Tenant : "Microsoft" Role : "Editor"
Tenant : "AMD" Role : "Editor"

The problem I see in the code is that in the classes:
- IdentityUserAppService
- IdentityRoleAppService
- maybe others? ... Controllers etc...

Theses classes manage the roles per name, and not per role GUID!
But we can have several times the same role name (one per tenant).

The result is that we can have a Role from one tenant, associated with a user from another tenant!
Except that the 'role name' is the same!

Here is an example of code:

```
public async Task ConvertToEditorAsync(string publicName)
{
    var identity = await _userRepository.FindAsync(CurrentUser.Id.Value);
    if (identity == null)
        return;

    // Create a new tenant
    Tenant tenant;
    try
    {
        tenant = await _tenantManager.CreateAsync(publicName);
        await _tenantRepository.InsertAsync(tenant);
    }
    catch (UserFriendlyException e)
    {
        throw new UserFriendlyException("Duplicate tenant name: " + publicName);
    }

    // Set it as the current tenant
    CurrentTenant.Change(tenant.Id, tenant.Name);

    //---- Assign the tenant to the user
    identity.AddClaim(_guidGenerator, new Claim(AbpClaimTypes.TenantId, tenant.Id.ToString()));
    await _userManager.AddClaimAsync(identity, new Claim(AbpClaimTypes.TenantId, tenant.Id.ToString()));

    // Create the tenant admin role" for the tenant
    const string tenantAdminRoleName = "tenantAdmin";
    var adminRole = await _roleRepository.FindByNormalizedNameAsync(_lookupNormalizer.NormalizeName(tenantAdminRoleName));

    if (adminRole == null)
    {
        adminRole = new Volo.Abp.Identity.IdentityRole(_guidGenerator.Create(), tenantAdminRoleName, tenant.Id)
        {
            IsStatic = true,
            IsPublic = true
        };

        (await _roleManager.CreateAsync(adminRole).ConfigureAwait(false)).CheckErrors();

        //await CurrentUnitOfWork.SaveChangesAsync().ConfigureAwait(false);
    }

    // Assign the role to the user
    await _userManager.AddToRoleAsync(identity, tenantAdminRoleName);
    await _userRepository.UpdateAsync(identity).ConfigureAwait(false);
}
```

In the current example, I try to create a tenant and assign it to the current user, there are 2 issues for now:

1 - The line 28, (_roleRepository.FindByNormalizedNameAsync) only work with a name, not a tenantId
2 - The line 44, assign the role per name without tenant Id (AddToRoleAsync)

**Comment by hikalkan** [comment]
`CurrentTenant.Change` switches to the tenant, so all operations are performed for the current tenant:

````csharp
    // Set it as the current tenant
    CurrentTenant.Change(tenant.Id, tenant.Name);
````

No need to filter data based on the current tenant since it is done by the ABP Framework automatically (https://docs.abp.io/en/abp/latest/Data-Filtering#imultitenant)

Did you test it or just checking the code?

**Comment by vd3d** [comment]
Yes, I tested it !

1 - the user is not associated to the tenant, both the classes (CurrentUser, IdentityUser) are not associated, but even in the database, the AbpUsers (Mongo) has tenantId = null

2 - I cannot associate the new role to the user, I got an exception when calling AddToRoleAsync.
I have check the code of AddToRoleAsync, and it does not use the tenantId at all !

**Comment by hikalkan** [comment]
@maliming can you test & fix this please?
If that's a critical bug, please fix on the master branch, we may release a patch version (2.1.2).

**Comment by maliming** [comment]
ok, i will check it.

**Comment by vd3d** [comment]
@maliming , to help you we can do a remote session... (team viewer etc...), that way I can directly show you where the issue is and how to reproduce it !

**Comment by maliming** [comment]
**CurrentTenant.Change** works as expected. 

---

> var identity = await _userRepository.FindAsync(CurrentUser.Id.Value);

**You should manage users and roles in the scope of the tenant** 

```
 using (CurrentTenant.Change(tenant.Id, tenant.Name))
{
      //here
}
```
![image](https://user-images.githubusercontent.com/6908465/75136665-58e20980-5720-11ea-9143-4eb2d63f28b8.png)

Tenant table:
![image](https://user-images.githubusercontent.com/6908465/75136611-2f28e280-5720-11ea-865d-f6d871a61e5f.png)

User table:
![image](https://user-images.githubusercontent.com/6908465/75136622-394ae100-5720-11ea-8778-08cbbedd015f.png)

Role table:
![image](https://user-images.githubusercontent.com/6908465/75136630-3ea82b80-5720-11ea-8b0a-3bf914f5a6db.png)

User & Role table
![image](https://user-images.githubusercontent.com/6908465/75136640-436cdf80-5720-11ea-8f09-a261091b8ae3.png)

**Comment by vd3d** [comment]
Thanks, but you create a new user, it is not the purpose ;-)
I want to keep my user, and create a tenant form him/her !
You understand the difference ?

**Comment by maliming** [comment]
**You should manage users and roles in the scope of the tenant**

> I want to keep my user, and create a tenant form him/her !

You need to manually change the TenantId of the user. Including all entities associated with the user, in short the framework is no problem.

**Comment by vd3d** [comment]
Ok, I will manage it myself then.

But the IdentityUser.TenantId is 'protected', should I use AppUser and change it, create a custom Repository too ?

(Should I also update the claims, the cookie, or something else ?)

**Comment by vd3d** [comment]
So,

I have update the IdentityUser tenantId, everything looks good in the database.

But at the next API call... it seems the CurrentTenant is still NULL.

How can I update this ?

**Comment by maliming** [comment]
```c#
using (_currentTenant.Change(tenant.Id, tenant.Name))
{
	//...
}
```
