### ISSUE TITLE
make a suggestion

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2903]
Individuals were slow to gain access.
Repeated queries against the database.
I can improve it a little bit. I can add a cache.
I modified the Volo. Common sense Abp. PermissionManagement. Domain. Identity module, but I feel this way is bad.
![image](https://user-images.githubusercontent.com/22017199/75139234-13750a80-5727-11ea-95e0-3dad46eacb9a.png)

**Comment by gdlcf88** [comment]
Is it related to https://github.com/abpframework/abp/issues/2437 ?

**Comment by 344089386** [comment]
> Is it related to #2437 ?

thanks.
