### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2910]
Are this is document error? I found only  "AbpExceptionLocalizationOptions" not  "ExceptionLocalizationOptions"
<img width="1026" alt="20200225084034" src="https://user-images.githubusercontent.com/57399417/75204146-10bbf900-57ab-11ea-99a4-62206fc4424f.png">

**Comment by maliming** [comment]
https://github.com/abpframework/abp/commit/75972bde74c180030c45cf6bbf34cfbe811be971
