### ISSUE TITLE
[Suggestion] Create appsettings.Staging.json and appsettings.Production.json while create new project in cli tool

### ISSUE THREAD

**Issue by h82258652** [abpframework/abp#2914]
Suggest creating the **Staging** and **Production** environment appsettings.json for the `host` and `dbmigrator` project. At current, only created `appsettings.json` and `appsettings.Development.json` two files.
Many times, the database connection strings are different between the environments.

**Comment by sam0817** [comment]
As my opinion, file ``appsettings.Production.json`` should never be in any non-production environment. Also never be in any code repository. ``Staging`` is fine.

ref: https://docs.microsoft.com/zh-tw/aspnet/core/fundamentals/environments?view=aspnetcore-3.1

**Comment by h82258652** [comment]
@sam0817 
You can keep the ```appsettings.Production.json``` file empty. My suggestion is just to create the files. If you don't want to use it, you can keep it empty or even delete it. Delete a file is much easier than create a file.

**Comment by sam0817** [comment]
@h82258652 
Hi there, i think good architecture or pattern should keep developer from mistakes. When we keep the file there, someday somehow someone junior see the file there and put something into(It makes sense to edit what exist there).

Just like something in  domain entity make as  ``internal `` to prevent unexpected usage. 
So there is also no such production related file in official template:

```
dotnet new webapp
dotnet new webapi
dotnet new mvc
```

**Comment by Loongle** [comment]
@sam0817 I can't seem to read in `migraions`  `appsettings.Development.json` content. 

My entry `Program.cs` has been configured:
My entry has been configured: 
```
 ...
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    string path = Directory.GetCurrentDirectory();
                    config.SetBasePath(Directory.GetCurrentDirectory());
                    config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
                    config.AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true);

                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<DbMigratorHostedService>();
                });
```
Can you tell me how do that? thankyou

**Comment by Loongle** [comment]
[https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1](url)
It seems that the.net core method cannot replace the global configuration

**Comment by h82258652** [comment]
@Loongle The migrator project won't read the ```appsettings.{environment}.json```. You need to add some codes to do this. Here is my code (in ```DbMigratorHostedService.cs```):
```C#
public async Task StartAsync(CancellationToken cancellationToken)
{
    using (var application = AbpApplicationFactory.Create<MyAppDbMigratorModule>(options=> 
    {
        // other codes

       // add this
       options.Services.ReplaceConfiguration(BuildConfiguration());
    }))
    {
        // other codes
    }
}
```
and BuildConfiguration like this:
```C#
private static IConfiguration BuildConfiguration()
{
    var configurationBuilder = new ConfigurationBuilder()
        .AddJsonFile("appsettings.json");

    var environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
    if (environmentName)
    {
        configurationBuilder.AddJsonFile($"appsettings.{environmentName}.json", true);
    }

    return configurationBuilder
        .AddEnvironmentVariables()
        .Build();
}
```

**Comment by Loongle** [comment]
@h82258652  Sorry, I made the wrong @. But anyway, you  are right.
