### ISSUE TITLE
login by identityserver4 connect/token

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#2923]
how to post the user‘s tenantid？ or how to login

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Multi-Tenancy

> `Volo.Abp.AspNetCore.MultiTenancy` package has implementation to determine the current tenant from current web request (from subdomain, header, cookie, route... etc.)


see https://github.com/abpframework/abp/issues/2593#issue-547108695

**Comment by wjkhappy14** [comment]
when login by connect/token  ，no cookie yet，post username password ok，but how to post  tenantid？

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/75323306-90cb8700-58af-11ea-8d26-aff42d09cb5f.png)

see https://github.com/abpframework/abp/issues/2593#issue-547108695

**Comment by mujthabagroad** [comment]
@maliming working fine with postman client request with __tenant header, when we use the console client, how we can pass the tenant Id?. or how we can resolve it on server side with current user info. tried both ways, but couldn't find a solution.

**Comment by maliming** [comment]
>  when we use the console client, how we can pass the tenant Id?.

Please share your code. 

I think you just need to set the http request header.

**Comment by mujthabagroad** [comment]
This is my project structure for a scheduled job to push some data from a desktop application db using windows service worker.

![image](https://user-images.githubusercontent.com/7587853/77315259-3ba75780-6d2d-11ea-927d-9cb2768c9475.png)

For this i added a service worker project and abp reference and module classes same like sample console app from abp project template. for tenant specific login, taking credentials from config.
`"IdentityClients": {
    "Default": {
      "GrantType": "password",
      "ClientId": "POS_App",
      "ClientSecret": "1q2w3e*",
      "UserName": "admin",
      "UserPassword": "1q2w3E*",
      //"UserPassword": "Admin@789",
      "Authority": "https://localhost:44399",
      "Scope": "POS"
      //"TenantId": "f7172cb7-23bd-d524-40bb-39f38f07d87c"
    }`
 I need to pass tenant id from client while login or need to identify and set tenant id from server for all request to get tenant specific user session on API server.

**Comment by dicksonkimeu** [comment]
Does this https://localhost:xxxx/connect/token work with the Web.Unified url/api ? in a module project ?
