### ISSUE TITLE
AbpValidationActionFilter not validating

### ISSUE THREAD

**Issue by EpsilonRepo** [abpframework/abp#2928]
Hello,

I try using `[Required]` attributes on Controller action parameters like this:
![image](https://user-images.githubusercontent.com/5107594/75371654-6d143b00-58c7-11ea-966e-3580e9061787.png)

But even if I don't pass a value, I don't get the expected AbpValidationException.
It looks like the validation filter isn't active. Is that possible?

My controller inherits AbpController.
ModelState is invalid when debugging.
![image](https://user-images.githubusercontent.com/5107594/75371963-ff1c4380-58c7-11ea-82ac-ee1edc15e764.png)

Thank you for your help

**Comment by maliming** [comment]
Please change the method return value to one of the following.
```
JsonResult
ObjectResult
NoContentResult
```

**Comment by EpsilonRepo** [comment]
That works, thank you!
