### ISSUE TITLE
CurrentUser

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#2930]
how to add new property  ？example：MerchantId

**Comment by maliming** [comment]
You can try extension methods.

```
public static Guid? GetMerchantId(this ICurrentUser currentUser)
{
	var merchantId = currentUser.FindClaim("MerchantIdClaimType")?.Value;
	if (merchantId == null || merchantId.IsNullOrWhiteSpace())
	{
		return null;
	}
	return Guid.Parse(merchantId);
}
```

https://github.com/abpframework/abp/blob/1a622bc50fbd9b554f61078d5eeafa9def3216e3/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L26

**Comment by wjkhappy14** [comment]
OK，thks

**Comment by wjkhappy14** [comment]
C:\Users\Administrator\source\repos\abp\modules\identity\src\Volo.Abp.Identity.Domain\Microsoft\Extensions\DependencyInjection\**AbpIdentityServiceCollectionExtensions**.cs 

 //  _AbpUserClaimsPrincipalFactory_

            return services
                .AddIdentityCore<IdentityUser>(setupAction)
                .AddRoles<IdentityRole>()
                .AddClaimsPrincipalFactory<**MyUserClaimsPrincipalFactory**>();

**Comment by wjkhappy14** [comment]
var merchantId=  CurrentUser.FindClaim("MerchantId");
