### ISSUE TITLE
Ok, Is there really no lazy loading in this framework for EF?

### ISSUE THREAD

**Issue by SoloHam** [abpframework/abp#2935]
I've been going crazy trying to figure this out. I've looked at every issue I could find, read everything I could. ut it seems I'm still missing something.

All I'm trying to do is Lazy Load a child entity when I call my custom method on the AppService object.

But It doesn't happen automatically and there isn't any ` GetAllIncluding()`  method in services or IRepository. 

COA Entity:

```
   public class COA : AuditedAggregateRoot<Guid>
    {
        public COA()
        {

        }
        public COA(Guid id)
        {
            Id = id;
        }
        public string Name { get; set; }
        public virtual COASubCategory COASubCategory { get; set; }

    }
```
 
COASubCategory Entity:

```
   public class COASubCategory : AuditedAggregateRoot<Guid>
    {
        public COASubCategory()
        {

        }
        public COASubCategory(Guid id)
        {
            Id = id;
        }

        public SubCategoryTypeEnum SubCategoryType { get; set; }
    }
```

COAAppService: 

```
   public class COAAppService : CrudAppService<COA, COADto, Guid, 
         PagedAndSortedResultRequestDto, 
         CreateUpdateDto, CreateUpdateDto>
    {
        public readonly IRepository<COA, Guid> repository;

        public COAAppService(IRepository<COA, Guid> repository) : base(repository)
        {
            this.repository = repository;
        }

        public async Task<List<COADto>> GetAll()
        {
            var list = await Repository.GetListAsync(true);
            //This Line
            >>   SubCategoryTypeEnum subCategoryType = list[0].COASubCategory.SubCategoryType;

            List<COADto> result = new List<COADto>();

            result = ObjectMapper.Map<List<COA>, List<COADto>>(list);
            return result;
        }
    }
```

**Comment by SoloHam** [comment]
Ha! Found it. 

For some reason the `includeDetails `parameter being set to true did nothing. but then by adding `WithDetails` While Querying the Repository worked. 

Shouldn't there be functionality to do this from the CrudAppService Implementation Instead of having to create custom methods?

**Comment by maliming** [comment]
Creating custom methods in the repository is the recommended practice.

Because the module of abp needs to support mongodb. So we cannot access the ef core api in the application service layer.

If you don't plan to support mongodb you are free to use it.

**Comment by acjh** [comment]
Duplicate of #616
