### ISSUE TITLE
[Suggestion] Allows the CLI to generate projects using custom template paths

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#2936]
Projects are now created using the official template by default. People maybe need a basic template without any additional modules, but this one maybe customized. Although it is now possible to do this by modifying the template compression package in the cache, this is extremely inconvenient.

**Comment by yinchang0626** [comment]
@Loongle 
Hi,I agree with you, So I extended code  on abp cli,
it can download template from some repository from github,
If you are interesting,pls ref [this](https://github.com/yinchang0626/abp/blob/feature/fs_abp_cli/framework/src/FS.Abp.Cli/ProjectBuilding/GitHubSourceCodeStore.cs)

**Comment by Loongle** [comment]
@yinchang0626 I implemented this before, but the cli updates too quickly. It's easy to fall behind, and installing two cli is a hassle

**Comment by Loongle** [comment]
I think it would be possible to use a local zip directly, which would save a lot of development effort and also be compatible with the current cli process of creating new projects

**Comment by yinchang0626** [comment]
Of course,if abp cli supports any other way to do it (use custom template to generate project ),that’s awesome

**Comment by hikalkan** [comment]
This is a good idea. Added to backlog and will definitely work on.

**Comment by liangshiw** [comment]
I will do it
