### ISSUE TITLE
Bundling Improvements (II)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#294]
Consider for next versions:

- Allow bundle tag helpers to declare base bundle names for inheritance
- Support URL as file paths for bundle items.
- Support CDN & alternative URLs on production.
- Support to save bundle to the file system (optional). And also do not re-bundle if bundle files are not changed after the last bundling even the application restarted. Current dynamic (in memory) bundling resets bundles on application restart as expected.
- Can we auto compile Less/Scss files? We should check if this possible via a standard library. Thus, we can completely throw web compiler VS extension away. We can design so that any module can contribute to pre-processing phase. Thus, anyone can create plugins to precompile js/css files.
- Allow contributors raise event when they want to invalidate the bundle cache
- Optimize minimizing (if the file is already minimized then skip minimizing for it - that means minimize file by file)

**Comment by bbakermmc** [comment]
@hikalkan Is this what youre looking for for Less: https://github.com/twenzel/WebOptimizer.Dotless

**Comment by hikalkan** [comment]
Thank you @bbakermmc for finding that. I didn't see it and it's what we need.

**Comment by wocar** [comment]
Can we at least change it so that if it’s a remote url won’t bundle just convert it to a normal script tag

**Comment by hikalkan** [comment]
Sure. But if you want a immediate workaround, why don't you just use regular `script` tag :)

**Comment by wocar** [comment]
Yes I did redactor already, however I think using apb script across all pages keeps the code more consistent. 

Moreover it might be a little bit counterintuitive because the tag is abp-script not bundle or local script. Regards

**Comment by NecatiMeral** [comment]
Would be great if ViewComponents could provide their own stylesheets / scss files and so on, which are compiled and bundled in a global stylesheet.

**Comment by hikalkan** [comment]
@NecatiMeral it is already done: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Widgets
