### ISSUE TITLE
Swagger duplicate HttpStatusCode 

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#2940]
![image](https://user-images.githubusercontent.com/7290992/75554796-fd907e00-5a75-11ea-956b-34da487565ec.png)
This will cause unnecessary deletion, which is boring

**Comment by maliming** [comment]
This has nothing to do with abp.

https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=netcore-3.1
