### ISSUE TITLE
How to use dotnet ef migrations in abp

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#2944]
Hi,
How can I use `dotnet ef migrations` command for applying migration in abp?
I used this command in xx.EntityFrameworkCore.DbMigrations project because xxDbContextFactory exists in this project, but I got this error 

> System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional

**Comment by mehdihadeli** [comment]
I've used this command in xx.HttpApi.Host project root and specifying startup and it worked,
`dotnet ef database update  -s  xx\xx.HttpApi.Host.csproj`

**Comment by ugurozturk** [comment]
dotnet ef database update --startup-project ".\src\xx.Web" --project ".\src\xx.EntityFrameworkCore.DbMigrations"
