### ISSUE TITLE
Can not localize Abp.UI messages to Arabic

### ISSUE THREAD

**Issue by abdumostafa** [abpframework/abp#2945]
I'm trying to localize Abp.UI messages like ValidationErrorMessage: "Your request is not valid!" to arabic culture but It does not work:
What I did:
I copies contents of file 
[abp/framework/src/Volo.Abp.UI/Localization/Resources/AbpUi/en.json](https://github.com/abpframework/abp/blob/3ba06fe0227b86099f3aa718b5d3976bb0e4bbe0/framework/src/Volo.Abp.UI/Localization/Resources/AbpUi/en.json)
to my ar.json resource but It does not work although I did the same with:
[abp/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/Localization/en.json](https://github.com/abpframework/abp/blob/3ba06fe0227b86099f3aa718b5d3976bb0e4bbe0/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/Localization/en.json)
Added my arabic text and It worked fine !

**Comment by maliming** [comment]
Can you share a project that reproduces the problem?

**Comment by abdumostafa** [comment]
I'm really sorry, this will not be possible " Company policies".
I have a tiered startup application
with service that its input dto parameter includes properties with data annotations like Required or Range , when validation fails messages are not localized although I added the localization keys in my ar.json file.

**Comment by maliming** [comment]
You can use CLI to create a simple project to reproduce the problem.

https://docs.abp.io/en/abp/latest/CLI

**Comment by abdumostafa** [comment]
@maliming I've created a PR to add Arabic language to AbpUi, please check it.
