### ISSUE TITLE
Q: Best practices for preventing race conditions for bg jobs/workers on distributed multi-instance environments

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2952]
Let's say that we have a background job (or any type of periodically-executed code) inside abp framework (Hangfire,... - no matter what technology is used).
It is also required that such application should be installed (and working properly) on the cluster (for instance Windows cluster environment) or any multi-instance environment (Docker Swarm, Kubernetes,...).
(The main reason for multi-instance installation is higher application uptime during upgrading and not performance-related demands.)

Do you have any tips or suggestions on how to properly design and implement such background job?
You can assume, that business logic of such job is idempotent, but race conditions could result in performance penalties.
Thank you.

**Comment by liangshiw** [comment]
hangfire will be responsible for job scheduling in the cluster environment
https://docs.hangfire.io/en/latest/configuration/using-sql-server.html
https://docs.hangfire.io/en/latest/best-practices.html

**Comment by leonkosak** [comment]
I know that, but I have Postgres database (this package is probably good: https://www.nuget.org/packages/Hangfire.PostgreSql/) and one specific need - dedicated instances of bg job/worker for specific tenants (or maybe in some cases dedicated instances for each tenant.
Some tenants could generate so much data for bg job/worker that foreach loop (through all tenants - settenant method inside loop) in one bg job/worker is maybe not good idea.

Each tenant also has its own database.

**Comment by hikalkan** [comment]
For ABP's default background, you need to disable background job execution in all instances except one (or disable all and create another service responsible to execute jobs)

For hangfire, @liangshiw has explained.

Beside these, I don't know any built-in solution. I don't want to give suggestion since giving a suggestion without thinking much is not good :)
