### ISSUE TITLE
Announcement: Breaking Change for Volo.Abp.Http.Client.IdentityModel package

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2960]
`Volo.Abp.Http.Client.IdentityModel` package was using `Microsoft.NET.Sdk.Web` SDK and it was using .net core 3.1. https://github.com/abpframework/abp/pull/2867 removes this dependency so it can be usable by non .net core projects too (like Xamarin and full .net framework).

This PR moves web depended functionality to `Volo.Abp.Http.Client.IdentityModel.Web` package, which can be a breaking change for existing applications.

Fortunately it is easy to fix.

1. For web projects depend on the `Volo.Abp.Http.Client.IdentityModel` package;

- Replace the `Volo.Abp.Http.Client.IdentityModel` reference by the `Volo.Abp.Http.Client.IdentityModel.Web` reference.
- Replace the dependency `typeof(AbpHttpClientIdentityModelModule)` to `typeof(AbpHttpClientIdentityModelWebModule)` for your related module class.

2. For console applications depend on the `Volo.Abp.Http.Client.IdentityModel` package;

- Add `Microsoft.Extensions.Hosting` package reference to your `.csproj` file:

````xml
<PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.2" />
````

Reason: Because the hosting services were coming indirectly from the `Volo.Abp.Http.Client.IdentityModel` dependency and now we should manually use this package.

Example change set: https://github.com/abpframework/abp/commit/7d94050caec05bdb3b2095d3d26a0869d9104c2e

**Comment by viewtance** [comment]
The `Volo.Abp.Http.Client.IdentityModel.Web` not published yet?

**Comment by ismcagdas** [comment]
@viewtance yes it seems like there is problem about this. We will publish it in a short time.

**Comment by hikalkan** [comment]
It is available now.
