### ISSUE TITLE
How Can Run Automatic Seed Without Run DbMigrator Project?

### ISSUE THREAD

**Issue by majidbigdeli** [abpframework/abp#2963]
How Can Automatic Seed Without Run DbMigrator Project?

**Comment by hikalkan** [comment]
Inject `IDataSeeder` and use the `SeedAsync()` method whenever you need it.

**Comment by majidbigdeli** [comment]
@hikalkan  it is not True because Create Duplicate Record . after run .

**Comment by maliming** [comment]
@majidbigdeli 
DataSeed should determine if the same data already exists.

**Comment by hikalkan** [comment]
Existing seed code (see [this](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeeder.cs) and [this](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionDataSeeder.cs) for examples) handles the duplication. If you create your own data seed contributor, you should take care of it yourself.

See this to learn how to create a data seed contributor: https://github.com/abpframework/abp/issues/2236#issuecomment-557739567
