### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#2967]
Using the ps1 `build-all.ps1` script after doing a PULL

>Pages\Account\IdentityServerSupportedLoginModel.cs(188,40): error CS1069: The type name 'WindowsPrincipal' could not be found in the namespace 'System.Security.Principal'. This type has been forwarded to assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly. [C:\Users\xxxx\source\repos\abp\modules\account\src\Volo.Abp.Account.Web.IdentityServer\Volo.Abp.Account.Web.IdentityServer.csproj]
Pages\Account\IdentityServerSupportedLoginModel.cs(203,41): error CS1503: Argument 1: cannot convert from 'string' to 'System.IO.BinaryReader' [C:\Users\xxxx\source\repos\abp\modules\account\src\Volo.Abp.Account.Web.IdentityServer\Volo.Abp.Account.Web.IdentityServer.csproj]
Pages\Account\IdentityServerSupportedLoginModel.cs(204,41): error CS1503: Argument 1: cannot convert from 'string' to 'System.IO.BinaryReader' [C:\Users\xxxx\source\repos\abp\modules\account\src\Volo.Abp.Account.Web.IdentityServer\Volo.Abp.Account.Web.IdentityServer.csproj]

>Build FAILED.

>Pages\Account\IdentityServerSupportedLoginModel.cs(188,40): error CS1069: The type name 'WindowsPrincipal' could not be found in the namespace 'System.Security.Principal'. This type has been forwarded to assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly. [C:\Users\xxxx\source\repos\abp\modules\account\src\Volo.Abp.Account.Web.IdentityServer\Volo.Abp.Account.Web.IdentityServer.csproj]
Pages\Account\IdentityServerSupportedLoginModel.cs(203,41): error CS1503: Argument 1: cannot convert from 'string' to 'System.IO.BinaryReader' [C:\Users\xxxx\source\repos\abp\modules\account\src\Volo.Abp.Account.Web.IdentityServer\Volo.Abp.Account.Web.IdentityServer.csproj]
Pages\Account\IdentityServerSupportedLoginModel.cs(204,41): error CS1503: Argument 1: cannot convert from 'string' to 'System.IO.BinaryReader' [C:\Users\xxxx\source\repos\abp\modules\account\src\Volo.Abp.Account.Web.IdentityServer\Volo.Abp.Account.Web.IdentityServer.csproj]
    0 Warning(s)
    3 Error(s)

**Comment by maliming** [comment]
I also encountered this problem, this should be a very rare case, and I believe it is an environmental problem. 


I manually reference the `System.Security.Principal.Windows` package in `Volo.Abp.Core.csproj` can be solved temporarily.

```
<PackageReference Include="System.Security.Principal.Windows" Version="4.7.0" />
```
