### ISSUE TITLE
Dapper Integration ,where are query result dto class file in project

### ISSUE THREAD

**Issue by cheetahing** [abpframework/abp#2968]
Defalut dto class file is in Application.Contracts project.  
Use dapper in EntityFrameworkCore project.  
I have a dapper sample sql like this
```
sql=
"select 
	s.Id,
	s.Name,
	t.Name TeacherName
from student s
left join teacher t on s.teacherId=t.id
where s.id=@id"

return dapper.QueryFirstAsync<StuedntDetailDto>(sql,new {id=id});
```

sample dto
```
public class StuedntDetailDto
{
	public Guid Id{get;set;}
	public string Name{get;set;}
	public string TeacherName{get;set;}
}
```
1. If the dto file in Application.Contracts project,it's wrong.Because the project EntityFrameworkCore not DependsOn Application.Contracts.
2. If the dto file in Domain.Shared project.It can work,but i don't know is right or wrong  

Abp framework team suggest how to do?

**Comment by maliming** [comment]
You can create some dapper poco classes in Domain.
