### ISSUE TITLE
Add Slovenian translations

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#2969]
Thanks to @leonkosak for Slovenian translations!

**Comment by sebitsi** [comment]
Thanks  @leonkosak  for Slovenian translation.
As i can see from commits, there is only json files. 

What about DB migrations ? Shouldn't be new (Slovenian) language added too ?

**Comment by leonkosak** [comment]
@sebitsi  Yes, all modules for abp (and Commercial) are distributed as NuGet packages and therefore the translations (.json) are inside packages.

The boilerplate code for language "initialization" is inside actual code. If you upgrade module/application, you have to manually add a new record in .cs code.

Example: https://github.com/abpframework/abp/pull/2671

When you run migrator, the language is also inserted in SQL database.

**Comment by sebitsi** [comment]
Hi @leonkosak.
Thanks for your explanation. 

I forgot to initialize language. :(

**Comment by leonkosak** [comment]
@sebitsi are you from Slovenia?

**Comment by sebitsi** [comment]
@leonkosak Yes I'm. You can contact me on edvin[at]sebit.si
