### ISSUE TITLE
Widget system

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#297]
Allow modules to define and register widgets (as view components) so they can be usable in the application.
They can also be used inside dashboards.

**Comment by hitaspdotnet** [comment]
@hikalkan Hi,
I can work on this If nobody else started before. 
Only I need some info. Whats the best target package for Infrastructures in the Framework? `Volo.Abp.AspNetCore.Mvc.UI` for Infrastructures and `Volo.Abp.AspNetCore.Mvc.UI.Widgets` from module and internal jobs is my idea. What you think sir?

**Comment by hitaspdotnet** [comment]
Or new additional package `Volo.Abp.AspNetCore.Mvc.UI.Widgets` for both 😑

**Comment by hitaspdotnet** [comment]
I just duplicated ABP Toolbar system as Widget system plus few widget's changes, now I have ready to use widget system in my new theme.

**Comment by hikalkan** [comment]
Good. If you send a PR, we evaluate it. Thanks :)

**Comment by hitaspdotnet** [comment]
@hikalkan Coming soon

**Comment by hikalkan** [comment]
Actually, we are also starting to work on that in a short time (already analysed it). It would be better If you have any other idea to contribute. Thanks a lot.

**Comment by hikalkan** [comment]
Done & documented: https://github.com/abpframework/abp/blob/dev/docs/en/AspNetCore/Widgets.md
