### ISSUE TITLE
Host the API

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#2970]
Question: 

Is it possible to split out an API Host like we had in the old framework?  Having a Host for the API is useful to allow for different UIs like Blazor.

Apologies if I have missed another approach to this but gladly take advise on how to use this Framework with client-side Blazor (not server-side).

**Comment by 274188A** [comment]
Some progress - so using swagger i can read the api calls available.  using this i can theoretically use these API calls from any UI that sends the auth token

**Comment by maliming** [comment]
You can use cli to create projects without UI. It is similar to angular, you can use different UI.

**Comment by 274188A** [comment]
Thank you - I see now.  However, when running swagger there seems to be a missing Authorize button on the swagger page.  Is this intentional?

**Comment by gdlcf88** [comment]
> Thank you - I see now. However, when running swagger there seems to be a missing Authorize button on the swagger page. Is this intentional?

https://thecodebuzz.com/jwt-authorization-token-swagger-open-api-asp-net-core-3-0/
