### ISSUE TITLE
UseAutrorization should be later than UseMultiTenancy

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2976]
This is a bug in the startup template, so should be fixed by existing applications.

**Comment by hikalkan** [comment]
It is easy to fix: https://github.com/abpframework/abp/commit/50cae73e90032820f61d199952965e528d8ec3f4

**Comment by codestellar** [comment]
Typo error in UseAuthorization

**Comment by codestellar** [comment]
I see a typo error in Release Notes and here as well in UseAuthorization

**Comment by hikalkan** [comment]
:) thanks, fixed both.
