### ISSUE TITLE
can i use some modules in WPF(.net core 3.1) App？AbpAutofacModule

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#2978]

**Comment by wjkhappy14** [comment]
and some others modules AbpAutofacModule，AbpAutofacModule  so on。。。。

**Comment by maliming** [comment]
> ABP should work in any type of application. BTW, It will definitely work with WPF. You can take the console application sample as a starting point.

**Comment by hikalkan** [comment]
I also created an issue to prepare a sample: https://github.com/abpframework/abp/issues/2988
But you can do it yourself, by understanding the console sample.
