### ISSUE TITLE
ConcurrentDictionary.GetOrAdd may not be always thread safe

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2979]
[The implementation of the GetOrAdd](https://github.com/dotnet/runtime/blob/e2881ae96bb4399864723aa46469c82379b03b32/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1026-L1039) may not be thread safe if we modify a shared object in the factory method.

It caused a bug for https://github.com/abpframework/abp/issues/2736

While not reported any other problem, we need to check other usages of this to see if there are other potential problems.

**Comment by fmpfmp** [comment]
https://github.com/abpframework/abp/issues/7994

**Comment by fmpfmp** [comment]
https://github.com/abpframework/abp/pull/6725

**Comment by fmpfmp** [comment]
https://github.com/abpframework/abp/issues/7994
