### ISSUE TITLE
Create a WPF sample startup project

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2988]

**Comment by yanxiaodi** [comment]
Do you mean to access the data directly from WPF app? I think it seems not safe to store the db connection string in a local folder. I'm trying to develop a WPF app that calls APIs of abp to access the data and use the identity server for authentication & authorization. I think it would be better to provide a template that integrates the identity server module of abp.

**Comment by hikalkan** [comment]
It will be just like [the console sample](https://github.com/abpframework/abp/tree/dev/samples/BasicConsoleApplication). Main idea is to integrate to abp framework and use the configuration, dependency injection, logging... etc.

It will not connect to any database. In real life, it can authenticates and uses a remote server as a client, but this can be done by the developer, not included in the sample.

**Comment by yanxiaodi** [comment]
@hikalkan I am wondering if I could do some works for this issue. From my understanding, most of MVVM frameworks of WPF/UWP provide built-in DI already. Basically, it could be a desktop client app, just like the Angular app.

My interest is implementing a sample that shows how to authenticate the user and call APIs from abp. It would make development easier. Glad to hear your thoughts and I can have a try.

**Comment by mujthabagroad** [comment]
How it could be if WPF direct integration with ABP rather than a client app same like console demo @hikalkan mentioned. @yanxiaodi as you said WPF has good structure with DI and all. but still abp users always love to use same pattern for their all project plans, (an abp lover 👍)

**Comment by wakuflair** [comment]
Since WPF can now run on .NET Core, it's simplier to use the ".NET Core way" with these MVVM frameworks.(`ServiceProvider` for DI, etc.)
Maybe In future we ABP lovers could contribute intergration libraries with ABP system for these MVVM frameworks :)
