### ISSUE TITLE
TenantId issue - null

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2989]
No metter where is tenant - in host or separated db, the TenantId column in tables (saving via IRepository) is NULL.
This is probably a bug, right?

P.S.: I am using Postgres database.

**Comment by leonkosak** [comment]
Therefore I have issues when seeding data in tables during migrations.

**Comment by acjh** [comment]
Duplicate of #1130

**Comment by leonkosak** [comment]
Ok, I understand.

I have the following code in DataSeedContributor method

```
// It's IMPORTANT to set tenant manually!
newEntity.TenantId = context.TenantId;
```

However, there are multiple records in host database (for host and for each tenant), even if all tenants are outside host database (each tenant have a dedicated database).
How to handle that tables in host database have only seeded data for host (where TenantId is null)?
