### ISSUE TITLE
Multithreading issue with AppliedCrossCuttingConcerns

### ISSUE THREAD

**Issue by mywhitecat** [abpframework/abp#2990]
At the 
```

public interface IAvoidDuplicateCrossCuttingConcerns
{
        List<string> AppliedCrossCuttingConcerns { get; }
}
```

list of  AppliedCrossCuttingConcern is not thread safe, which lead to issues for app services that are registered with singleton lifestyle.

**Comment by hikalkan** [comment]
Application services should be transient by design. Don't make them singleton. Change design of your implementation :)
