### ISSUE TITLE
abp\samples\RabbitMqEventBus

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#2991]
can not find  IDistributedEventBus.Subscribe method  called， so how to receive  the data someone published？
can not understand，pls   give some help

**Comment by hikalkan** [comment]
It will be documented. However, I will explain here briefly;

1. No need to explicitly subscribe. Create a class [like that](https://github.com/abpframework/abp/blob/dev/samples/RabbitMqEventBus/App1/App1TextEventHandler.cs) - implement IDistributedEventHandler and register to dependency injection (with ITransientDependency here). ABP auto subscribes to the event.

2. Configure the rabbitmq exchange and client:

https://github.com/abpframework/abp/blob/e87154a4d79c533d3976ea31f01e17b9e4ac529e/samples/RabbitMqEventBus/App1/App1Module.cs#L15-L19

**Comment by wjkhappy14** [comment]
thks,i will try
