### ISSUE TITLE
Update min VS version

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#2992]
Should be 16.4+ instead of 16.3+

In the documents:

https://github.com/abpframework/abp
https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-MVC-Template
https://docs.abp.io/en/abp/latest/Getting-Started-Angular-Template
https://docs.abp.io/en/commercial/latest/getting-started?UI=MVC&DB=EF&Tiered=No
https://github.com/abpio/abp-commercial-docs/blob/master/en/getting-started.md

**Comment by cotur** [comment]
fixed by: https://github.com/abpframework/abp/commit/1d3f0c3cdbf025f567f285eb7b3fd7df3ffffcb1
