### ISSUE TITLE
Volo.Abp.Http.Client.IdentityModel.Web package not published

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#2996]
The `Volo.Abp.Http.Client.IdentityModel.Web` package not published yet on nuget server?

It also will cause token verification failed, if still using `Volo.Abp.Http.Client.IdentityModel` package in the *.Web.project.

**Comment by ismcagdas** [comment]
@viewtance yes it seems like there is problem about this. We will publish it in a short time.

**Comment by hikalkan** [comment]
It has been published, will be available in a few minutes. Thank you for reporting this.
