### ISSUE TITLE
Q: Background Worker - how to init and set "base entrance method"

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#2997]
I see thet Background worker document is in creation, but I need bg worker functionality now.
https://aspnetboilerplate.com/Pages/Documents/Background-Jobs-And-Workers#background-workers

Based on this, document, can you give me quick explanations how to create and enable bg worker in abp.io (and Commercial) module?

Thank you.

**Comment by liangshiw** [comment]
The documentation is complete, but not merged yet. see https://github.com/abpframework/abp/pull/2973

**Comment by leonkosak** [comment]
The requested service 'Volo.Abp.BackgroundWorkers.IBackgroundWorkerManager' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

I have worker in .Domain module.

**Comment by liangshiw** [comment]
@leonkosak Move to https://github.com/abpframework/abp/pull/2973
