### ISSUE TITLE
May be error in documentation

### ISSUE THREAD

**Issue by EugeniZaplatin** [abpframework/abp#3003]
In this section of documentation https://docs.abp.io/en/abp/latest/Authorization#permission-value-providers  I found type PermissionOptions, but in sources I found AbpPermissionOptions.

https://user-images.githubusercontent.com/11317749/76072352-6aea6480-5fca-11ea-988e-d7c2aa70bc26.png

**Comment by edwardmcleodjones** [comment]
@yekalkan Documentation (2.3.0 - latest) still states `PermissionOptions ` not `AbpPermissionOptions`.  Does this need to be reopened?

https://github.com/abpframework/abp/blob/dev/docs/en/Authorization.md
