### ISSUE TITLE
How to disable login before email is validated and send a validation email after registration ?

### ISSUE THREAD

**Issue by xirius** [abpframework/abp#3004]
I'm new to ABP and currently learning it. I'm exploring the registration of the new user and would like to configure the standard flow. 
I use the standard template: abp new Acme.BookStore --template app --ui mvc --tiered -d mongodb

1. When the user registers I would like to send an email to validate the email address (/api/account/register endpoint) ? How can I do it ? Is there an example somewhere ?
2. How can I disable user login before his/her email address is validated ?
Currently when the user registers it is automatically logged in which is not normal.

Any guidance on this ? Thanks in advance.

**Comment by maliming** [comment]
The free and open source account does not implement some features.

![image](https://user-images.githubusercontent.com/6908465/76194945-3d97f380-6222-11ea-8be5-1e40796fda1f.png)

see https://docs.abp.io/en/commercial/latest/abpframeworkcomparison

**Comment by hikalkan** [comment]
@maliming this document is not complete yet and also it is wrong. I will work on it in this week to fix.

For example, "UI to change language", "switch between tenants"...etc are already available in the free Account module.

**Comment by hikalkan** [comment]
Email validation has not been implemented for the free account module.
You can register to `EntityCreatedEventData<IdentityUser>` to be notified when a user has been created. Then you can send an email in this case. Then you create a page to validate the email. We use standard Identity library you know, use IdentityUserManager.

You can override LoginModel class to perform additional logic (like done here: https://github.com/volosoft/volo/blob/dev/abp/account/src/Volo.Abp.Account.Pro.Public.Web.IdentityServer/Pages/Account/IdentityServerSupportedLoginModel.cs)

**Comment by hikalkan** [comment]
Alternatively, you can add account & identity source code to your application (and remove NuGet references) and freely customize.

Latest CLI should automate this. @yekalkan do you know how it works, since I see it is not documented yet.

**Comment by yekalkan** [comment]
`abp add-module Volo.Account --with-source-code`

**Comment by xirius** [comment]
@hikalkan Thanks a lot!
