### ISSUE TITLE
One of the identified items was in an invalid format 

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#3005]
I import data from other system to MYSQL,and use mysql UUID() to generate Id.But when I run the project It says"One of the identified items was in an invalid format ". One of the id is "b80cb65a-5f8f-11ea-be54-0242ac110007". How to deal this issue?

**Comment by maliming** [comment]
This seems to have nothing to do with ABP, like a problem with EF Core.

**Comment by hikalkan** [comment]
It seems MySQL driver can not properly convert it to a GUID. As @maliming stated, nothing to do with ABP in this case. Please search on the web.
