### ISSUE TITLE
Docs Elastic Search Problem: Search is performed on raw document

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#3009]
Search is performed before documents is converted to plain text from markdown format and processed by scriban.

![image](https://user-images.githubusercontent.com/5793291/76084214-7042b180-5fc0-11ea-8eeb-9938f164e4d1.png)

related https://github.com/abpframework/abp/pull/2901
related https://github.com/abpframework/abp/issues/1621

**Comment by ebicoglu** [comment]
this project needs to be radical refactored. elastic search section should move to appservice layer.
also, rendering MD to HTML should be done in appservice.
now, elastic search indexing is done in domain and markdown converters work in Web layer.
