### ISSUE TITLE
custom user validation by IExtensionGrantValidator

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#3010]
I've just download a template(angular) to test new framework.

we have a legacy database which stores our user accounts, and I want to custom user validation logic to let the legacy user login.

the best practice is to use IExtensionGrantValidator, and I found some clues [here](https://stackoverflow.com/questions/43809881/how-to-integrate-custom-authentication-provider-into-identityserver4). 

the custom grant type:
         public string GrantType => "my_credentials";

I added it to service :

      private void ConfigureAuthentication(ServiceConfigurationContext context, IConfiguration configuration)
        {
            context.Services.AddAuthentication()
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.RequireHttpsMetadata = false;
                    options.ApiName = "rpt";
                    options.JwtBackChannelHandler = new HttpClientHandler()
                    {
                        ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
                    };
                });

            context.Services.AddTransient<IExtensionGrantValidator, myCrapGrantValidator>();
        }

and create new grant type in IdentityServerClientGrantTypes:

      insert IdentityServerClientGrantTypes VALUEs ('rtp_Web id','my_credentials')

When I run the project,  swagger api page (account/login) cannot reach the custom logic, and then I tried postman, added the header 'grant_type = my_credentials', and still no luck.

my question is How to make the customized validator work?
or there are better ways to change the auth/validation logic.

**Comment by evenlee** [comment]
I also tried to implement my IResourceOwnerPasswordValidator， but still no luck.

**Comment by alexandis** [comment]
> I've just download a template(angular) to test new framework.
> 
> we have a legacy database which stores our user accounts, and I want to custom user validation logic to let the legacy user login.
> 
> the best practice is to use IExtensionGrantValidator, and I found some clues [here](https://stackoverflow.com/questions/43809881/how-to-integrate-custom-authentication-provider-into-identityserver4).
> 
> the custom grant type:
> public string GrantType => "my_credentials";
> 
> I added it to service :
> 
> ```
>   private void ConfigureAuthentication(ServiceConfigurationContext context, IConfiguration configuration)
>     {
>         context.Services.AddAuthentication()
>             .AddIdentityServerAuthentication(options =>
>             {
>                 options.Authority = configuration["AuthServer:Authority"];
>                 options.RequireHttpsMetadata = false;
>                 options.ApiName = "rpt";
>                 options.JwtBackChannelHandler = new HttpClientHandler()
>                 {
>                     ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
>                 };
>             });
> 
>         context.Services.AddTransient<IExtensionGrantValidator, myCrapGrantValidator>();
>     }
> ```
> 
> and create new grant type in IdentityServerClientGrantTypes:
> 
> ```
>   insert IdentityServerClientGrantTypes VALUEs ('rtp_Web id','my_credentials')
> ```
> 
> When I run the project, swagger api page (account/login) cannot reach the custom logic, and then I tried postman, added the header 'grant_type = my_credentials', and still no luck.
> 
> my question is How to make the customized validator work?
> or there are better ways to change the auth/validation logic.

I suppose it's not correct way to add Extension Validator. You have to use AddExtensionGrantValidator  Extension in PreConfigure

**Comment by xyfy** [comment]
@alexandis  can you show me how to call `AddExtensionGrantValidator` ?

**Comment by alexandis** [comment]
@xyfy

    public class YOURIdentityServerModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PreConfigure<IIdentityServerBuilder>(identityServerBuilder =>
            {
                identityServerBuilder.AddExtensionGrantValidator<SwitchToTenantGrantValidator>();
            });
        }
        ...
    }

**Comment by xyfy** [comment]
Thanks

**Comment by szilardd** [comment]
This worked for me https://github.com/abpframework/abp/issues/3077#issuecomment-597655930

Note that it is `context.Services.PreConfigure` instead of just `PreConfigure`
