### ISSUE TITLE
how config the long type auto serialize string type json

### ISSUE THREAD

**Issue by cheetahing** [abpframework/abp#3018]
c# abp entity id type is long,use Snowflake.Core lib generate long id.  
Serialize entity id to json, then javascript deserialize javascript obj loss precision.
```
public class Student:AuditedEntity<long>
{
}
```
When c# student id value is 1236305924231139328.  
Serialize obj is right.
Javascript deserialize json loss precision.  
javascript obj id value is 12363059242311393**00**    

I want to all  long type entity id or dto id serialize to string type json obj.
How can i config it.

**Comment by Loongle** [comment]
you can using Guid 👌

**Comment by cheetahing** [comment]
I know using guid.But i want to use long.
I have other idea,add property IdString in base dto calss.
Do you have a perfect idea?
```
public class BaseDto:IEntityDto<long>
{
	public IdString
	{
		get
		{
			return this.Id.ToString();
		}
	}
}
```

**Comment by maliming** [comment]
I think this problem has nothing to do with ABP, you will also encounter this problem if you use EF. This is related to the json serialization object.

**Comment by cheetahing** [comment]
Use BaseEntityDto,all the id convert to string type json,it's work well.  
I wish it can help other developer.  

myEntityDto
```
public class MyEntityDto : BaseEntityDto
{
	
}
```

the BaseEntityDto
```
public class BaseEntityDto : IEntityDto<long>
{
	[JsonConverter(typeof(LongStringConvert))]
	public long Id
	{
		get;
		set;
	}
}
```
the json converter
```
public class LongStringConvert : JsonConverter
{
	public override bool CanConvert(Type objectType)
	{
		return false;
	}

	public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
	{
		return long.Parse(reader.Value.ToString());
	}

	public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
	{
		writer.WriteValue(value.ToString());
	}
}
```
