### ISSUE TITLE
How Can unload Module  From Startup Template ?

### ISSUE THREAD

**Issue by majidbigdeli** [abpframework/abp#3019]
For Example How Can Remove /api/account/login From Api ?

**Comment by maliming** [comment]
These APIs exist in ABP modules, you can remove dependencies on these modules.

You can find it on github or clone abp source code.

**Comment by majidbigdeli** [comment]
@maliming  
Yes I Know .But  For Example  When I delete AbpIdentityHttpApiModule from MyProject.Http.Api Project  yet still i see /api/identity/users api ;

**Comment by wjkhappy14** [comment]
clean  and then rebuild ，pls try

**Comment by wjkhappy14** [comment]
<PackageReference Include="Volo.Abp.Identity.Application" Version="2.2.1" />

**Comment by wjkhappy14** [comment]
<PackageReference Include="Volo.Abp.Identity.Application" Version="2.2.1" />

**Comment by wjkhappy14** [comment]
PackageReference Include="Volo.Abp.Identity.Application" Version="2.2.1"

**Comment by majidbigdeli** [comment]
@maliming  @wjkhappy14  @hikalkan 
My HttpApiModule 

![image](https://user-images.githubusercontent.com/26275762/76167633-51d5e500-617d-11ea-8e72-a673675ed826.png)


my ApplicationModule

![Capture](https://user-images.githubusercontent.com/26275762/76167620-366ada00-617d-11ea-8b79-9491a7c64c4c.PNG)

**still i see /api/identity/users api ;**
