### ISSUE TITLE
Regression : UserFriendlyException through remote service

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#3020]
Hi,

I have upgrade to the last version of abp 2.2.1, and when I throw an exception in a ApplicationService, the client receive a Volo.Abp.Http.Client.AbpRemoteCallException.

Previously I received a UserFriendlyException !

**Comment by vd3d** [comment]
BTW, I have upgrade from 2.1... and I have see this breaking change :

https://github.com/abpframework/abp/issues/2960

I have adapted my code and it looks to work, but not sure that this regression issue is related.

Thanks

**Comment by hikalkan** [comment]
It was always AbpRemoteCallException. No change on that I know.
