### ISSUE TITLE
There are no login schemes configured for this client.

### ISSUE THREAD

**Issue by doganc** [abpframework/abp#3024]
Hi, how can configure login schemas for users? For example Locking account after failed login attempts. 
Thanks

**Comment by liangshiw** [comment]
See [Settings Document](https://docs.abp.io/en/abp/latest/Settings) .
You can configure values in `appsettings` file, Like :
```
"Settings": {
    "Abp.Identity.Password.RequiredLength": 100,
    "Abp.Identity.Lockout.MaxFailedAccessAttempts": 200
  }
```
Or you can use the [`ISettingManager`](https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/ISettingManager.cs) provided by the setting management module to set the value

**Comment by doganc** [comment]
Thanks for your help @liangshiw
