### ISSUE TITLE
Webhook Feature

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3026]
How can i implement web hooks?

**Comment by cotur** [comment]
Hi @dicksonkimeu, 

Recieving or sending webhooks can be created by you, this question is not related to ABP Framework. 

Here is for you some documents: 
https://docs.microsoft.com/en-us/samples/microsoftgraph/aspnetcore-webhooks-sample/microsoft-graph-webhooks-sample-for-aspnet-core/

**Comment by dicksonkimeu** [comment]
@hikalkan i meant to sent out notifications, not incoming notifications

**Comment by hikalkan** [comment]
Currently, there is no such a feature of the framework. So, you can implement it yourself as you can do in any asp.net core project. Nothing special.

We will create a real time notification system (see https://github.com/abpframework/abp/issues/633), but it is not a webhook system. Webhook system is on the road map, but with low priority.

**Comment by jhallam3** [comment]
Please advise where this should be built, im very new to ABP Commercial and finding it difficult to understand where code should go..
