### ISSUE TITLE
Define ETO's for all aggregate roots for all modules

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3033]
ETO: Event Transfer Object.

Used to transfer info about a change for an entity, like creation, deletion and updating.

If we don't define a specific ETO for an entity, [the default one](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/Distributed/EntityEto.cs) is used, which simply has entity name and id.

Defining specific ETO allows to easily subscribe to an event of that entity type. There are 3 steps to define an ETO for an aggregate root:

1. Create a ETO class that contains the ensential properties of the agg.root, in the .Domain.Shared project. Example:

https://github.com/abpframework/abp/blob/ecac0358fbc9a0acbbda91111d41d5ee6bfb795a/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain.Shared/Volo/Abp/TenantManagement/TenantEto.cs#L1-L12

2. Register it for Entity to ETO mapping, in the .Domain project. Example:

https://github.com/abpframework/abp/blob/ecac0358fbc9a0acbbda91111d41d5ee6bfb795a/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/AbpTenantManagementDomainModule.cs#L29-L32

3. Define the AutoMapper mapping (which is used for the mapping by default) in the .Domain project. Example:

https://github.com/abpframework/abp/blob/ecac0358fbc9a0acbbda91111d41d5ee6bfb795a/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/AbpTenantManagementDomainMappingProfile.cs#L27

That's all. Then ABP will automatically publish create,delete,update events for this ETO when corresponding entity change happen. You can subsrcibe the event you like, example:

https://github.com/abpframework/abp/blob/ecac0358fbc9a0acbbda91111d41d5ee6bfb795a/samples/MicroserviceDemo/microservices/IdentityService.Host/Tenants/TenantCreatedDistributedEventHandler.cs#L13-L37

Notice that this is a distributed event, but will be in-process by default. When you configure RabbitMq or another real distributed event bus provider, it will be real distributed.

**Comment by hikalkan** [comment]
Update https://github.com/abpframework/abp/blob/dev/docs/en/Customizing-Application-Modules-Guide.md#subscribing-to-distributed-events once this issue is done!

**Comment by cotur** [comment]
- [ ] Identity
- [ ] Blogging
- [ ] Docs
- [ ] IdentityServer

**Comment by sanghel-payoff** [comment]
...related official doc should be updated: https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities#subscribing-to-distributed-events

> Pre-built application modules do not define specialized event types yet (like UserEto - "ETO" means "Event Transfer Object"). This feature is on the road map and will be available in a short term (follow this issue). Once it is implemented, you will be able to subscribe to individual entity types

**Comment by cotur** [comment]
Thank you @sanghel-payoff ,

We will update documentation soon. Tracked here: https://github.com/abpframework/abp/issues/11337
