### ISSUE TITLE
File uploads with S3

### ISSUE THREAD

**Issue by AlphaComposite** [abpframework/abp#3037]
What's best practice when uploading a file at the same time form data is submitted. Per the design of ABP, form data is sent across the wire via script and APIs. Is there a way to upload a file easily with the current implementation?

**Comment by maliming** [comment]
You should implement the method of uploading files in the web layer controller instead of the application service.

asp net core's documentation has said a lot. https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1

**Comment by AlphaComposite** [comment]
If I'm submitting the form data to a controller and not the application service, doesn't this particular form you're proposing break the convention of the ABP framework? 

Are you saying that I should add a controller to the ProjectName.web project for this functionality? I'd like to store the filename in the project database, too, so I have to be able to submit the form with other user-related text fields along with the file and get all the information at the same time. 

I suppose I'd need a bit more information from you about how to do this in the context of ABP.
