### ISSUE TITLE
Docs Module documentataion is Not up to date

### ISSUE THREAD

**Issue by pranavpatil19** [abpframework/abp#3063]
https://docs.abp.io/en/abp/latest/Modules/Docs

Docs Module documentataion is Not up to date

i follow every singale step but  not working .. please anybody here implement this  in project

**Comment by liangshiw** [comment]
Do you mean the Chinese document or the English document?

**Comment by pranavpatil19** [comment]
@liangshiw  in Engalish Document.. some step is missing.. please help me

**Comment by liangshiw** [comment]
@pranavpatil19 I will update the documentation today

**Comment by liangshiw** [comment]
@pranavpatil19 I have updated the documentation, you can confirm this https://github.com/abpframework/abp/pull/3073
