### ISSUE TITLE
How to: change role of the current user without sign out ?

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#3067]
Hi,

In my application, there is a specific action from the current user to create his own "club" for him (and friends).

Once I create a club, I also associate a role "club admin" to the current user.

It works, the role is associated in the database, but he has to logout and then login again to have the new role "detected" on the client/web side.

By example, I use blazor (but it will be the same issue with other tech), I use such code:

<AuthorizeView Roles="ClubAdmin">
                <Authorized>
                    <MatIconButton Icon="dashboard" OnClick="@OnClickDashboard"></MatIconButton>
                </Authorized>
            </AuthorizeView>

It use the normal ASP.NET authorization mechanism.

How can I force a refresh to see the new role on the client side ? Any idea ?

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2460#issuecomment-569508003
