### ISSUE TITLE
How to use my sigin manager?

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#3070]
I want to customize the login method, and I saw .net core support it in start file:
  .AddSignInManager<MySignInManager<User>>();

But in the API.Host Project, I cannot find it,  do we need to do it other way in ABP?

thanks in advance.

**Comment by maliming** [comment]
Try replacing it with dependency injection.

https://docs.abp.io/en/abp/latest/Dependency-Injection


Or

```
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<IdentityBuilder>(builder =>
    {
        builder.AddSignInManager...
    });
}

```

**Comment by evenlee** [comment]
I've used pre config:

public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PreConfigure<IdentityBuilder>(builder =>
            {
                builder.AddSignInManager<MySignInManager>();

            });
        }

and my sign in manger:

public class MySignInManager:SignInManager<IdentityUser> 
    {
        public RtpSignInManager(UserManager<IdentityUser> userManager,
            IHttpContextAccessor contextAccessor,
            IUserClaimsPrincipalFactory<IdentityUser> claimsFactory,
            IOptions<IdentityOptions> optionAccessor,
            ILogger<SignInManager<IdentityUser>> logger,
            IAuthenticationSchemeProvider schemes,
            IUserConfirmation<IdentityUser> confirmation
            ) : base (userManager, contextAccessor, claimsFactory,
                optionAccessor, logger, schemes, confirmation)
        {

        }

But when I run the host project, I got an error:

System.InvalidOperationException: Type MySignInManager must derive from SignInManager<IdentityUser>.

it's wired cos I've inherit the sign manager.

**Comment by maliming** [comment]
You need use `TUser(IdentityUser)`.

`public class SignInManager<TUser>`

**Comment by evenlee** [comment]
code changed, but still get the same error.

`public class MySignInManager<TUser>: SignInManager<IdentityUser>`

```
 public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PreConfigure<IdentityBuilder>(builder =>
            {
                builder.AddSignInManager<MySignInManager<IdentityUser>>();

            });
        }
```

**Comment by maliming** [comment]
```

public class MySignInManager : SignInManager<Volo.Abp.Identity.IdentityUser>
{
	public MySignInManager(UserManager<Volo.Abp.Identity.IdentityUser> userManager, IHttpContextAccessor contextAccessor,
		IUserClaimsPrincipalFactory<Volo.Abp.Identity.IdentityUser> claimsFactory, IOptions<IdentityOptions> optionsAccessor,
		ILogger<SignInManager<Volo.Abp.Identity.IdentityUser>> logger, IAuthenticationSchemeProvider schemes,
		IUserConfirmation<Volo.Abp.Identity.IdentityUser> confirmation) : base(userManager, contextAccessor, claimsFactory,
		optionsAccessor, logger, schemes, confirmation)
	{
	}
}


public override void ConfigureServices(ServiceConfigurationContext context)
{
	context.Services
		.GetObject<IdentityBuilder>()
		.AddSignInManager<MySignInManager>();
}
```

**Comment by evenlee** [comment]
Thanks @maliming, seems the reason is I mis-used .net core IdentityUser, your code works. really appreciate.
