### ISSUE TITLE
The default hangfire server always created when app start

### ISSUE THREAD

**Issue by zredb** [abpframework/abp#3074]
I configed two hangfire server as below:
  
            context.Services.AddHangfireServer(options =>
            {
                options.Queues = new[]
                {
                    HangfireQueueNames.WrfCalcQueueName,
                };
                options.WorkerCount = 1;
                options.ServerName = "Msp wrf job server";
                //options.TaskScheduler
            });
            context.Services.AddHangfireServer(options =>
            {
                options.Queues = new[]
                {
                    "default"
                };
                options.WorkerCount = 5;
                options.ServerName = "Msp other job server";
                //options.TaskScheduler
            });
   but  when app started,  there are 3 hangfire server created, the information from log file is : 
2020-03-09 11:56:23.512 +08:00 [INF] Using the following options for Hangfire Server:
    Worker count: 1
    Listening queues: 'wrf'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2020-03-09 11:56:23.523 +08:00 [INF] Using the following options for Hangfire Server:
    Worker count: 5
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2020-03-09 11:56:34.144 +08:00 [INF] Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15

**Comment by maliming** [comment]
Will it work as expected if you use plain asp net core?

**Comment by gdlcf88** [comment]
Did you add `app.UseHangfireServer();`?

**Comment by zredb** [comment]
Yes, It works normally, but i think it would be to server instance in this case.
@gdlcf88 I'm not use app.UseHangfireServer();

**Comment by maliming** [comment]
hi @zredb 

Can you share sample projects of plain asp net core and abp?
