### ISSUE TITLE
Repository not returning any objects

### ISSUE THREAD

**Issue by LiljebergXYZ** [abpframework/abp#3076]
Hello
I tried searching if there was something related, however I created a new appservice and got my `IRepository` based on my class an primary key. However no matter what I do I don't get any results back. If I try to use `GetListAsync` I get a list of 0 elements and if I try to select using a` Where` it's the same result even though I have added data into the database. 

Why could that be?

**Comment by liangshiw** [comment]
Show your code and recurrence conditions

**Comment by LiljebergXYZ** [comment]
The below is all that I have and I can't make it work.

ClassesAppService
```cs
[Authorize]
    public class ClassesAppService : CrudAppService<Class, ClassDto, Guid>, IClassesAppService
    {
        public ClassesAppService(IRepository<Class, Guid> repository) : base(repository)
        {
        }

        [Route("/api/app/classes/current-class")]
        public async Task<ClassDto> GetCurrentClass()
        {
            try
            {
                var id = CurrentUser.Id;
                var cClass = await Repository.GetListAsync();

                return MapToGetOutputDto(cClass[0]);
            }
            catch (Exception ex)
            {
                Logger.Log(LogLevel.Warning, "No class found for teacher ID: " + CurrentUser.Id, ex);
                throw new EntityNotFoundException("No class found for current user");
            }
        }
    }
```
Class.cs
```cs
public class Class : FullAuditedAggregateRoot<Guid>, IMultiTenant, IClass
    {
        public Guid? TenantId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public Guid RoomId { get; set; }
        public Guid TeacherUserId { get; set; }
        public bool Started { get; set; }
    }
```

**Comment by liangshiw** [comment]
Is there an error log? and you can see if the database table contains any records.

**Comment by LiljebergXYZ** [comment]
There is no error log other than the EntityNotFound exception, or in the case of GetListAsync, `Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')` sicne it's empty.

And yes the database table does contain records as I created them myself and can write a manual query that works

**Comment by LiljebergXYZ** [comment]
It seems that the new object when it was created did not get a tenantId. Thanks for your help, but it's working now!
