### ISSUE TITLE
Angular Component Replacement Document enhancement

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3080]
Listing "Available Replaceable Components" is not a good idea here, because it is hard to maintain. Also, this list covers only the pre-built open source modules. Suggestion:

1. Remove this section from here, move component lists to the documents of the related modules ([see the list of the modules](https://docs.abp.io/en/abp/latest/Modules/Index) - every module will have its own documentation).
2. Reference to this document from the module documents.

**Comment by mehmet-erim** [comment]
Depends on: #3425
