### ISSUE TITLE
Question about Description property of Blog entity.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#3081]
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Blogs/Blog.cs#L17

https://github.com/abpframework/abp/blob/b8e4f8051c905ee7d5ab8dc843f1ea192495a373/modules/blogging/src/Volo.Blogging.Application/Volo/Blogging/Blogs/BlogAppService.cs#L51-L54

Why the `Description` property has public setter and not set by the constructor?

**Comment by ismcagdas** [comment]
@gdlcf88 because it can be null, https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Blogs/Blog.cs#L16. This field is not required to create a valid Blog.

**Comment by gdlcf88** [comment]
Hi @ismcagdas.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/setting-management/src/Volo.Abp.SettingManagement.Domain/Volo/Abp/SettingManagement/Setting.cs#L15-L19

`ProviderName` is also a nullable string property and it does not have a public setter. I still do not understand why `Description` needs a public setter and it is not in the constructor.
