### ISSUE TITLE
question on the way to use webapi client

### ISSUE THREAD

**Issue by iamskyye** [abpframework/abp#3084]
Hi Team,

Can i ask a question on this post(https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients)?
I really want to call the rest api in my winform project? Based on the example above - the IBookAppService interface is defined in the project Acme.BookStore.Application.Contracts. So dose that mean my winform project has to have this dll reference on this project? 

Thank you
Sky

**Comment by ismcagdas** [comment]
@iamskyye yes both `Acme.BookStore.Application.Contracts` and `Acme.BookStore.HttpApi.Client`

**Comment by iamskyye** [comment]
Thank you for wonderful abp!
