### ISSUE TITLE
Problem with UnitOfWorkAttribute definition

### ISSUE THREAD

**Issue by netcore-jroger** [abpframework/abp#3086]
**abp version: 2.2.1**
`struct` cannot be used in attribute constructor. I think this is bug.

The error I receive when I define it like this is:
```
[UnitOfWork(isTransactional: false, isolationLevel: IsolationLevel.ReadCommitted, IsDisabled = false, Timeout = TimeSpan.FromHours(3D))]
```
> Error message: **'TimeOut' is not a valid named attribute argument because it is not a valid attribute parameter type**

The error I receive when I define it like this is:
```
[UnitOfWork(isTransactional: false, isolationLevel: IsolationLevel.ReadCommitted, TimeSpan.FromHours(3D))]
```
> Error message: **Attribute constructor parameter 'timeout' has type 'TimeSpan', which is not a valid attribute parameter type**

So I currently have to configure it globally.

**Comment by netcore-jroger** [comment]
show problem code:
```CSharp
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Class)]
public class BestAttribute : Attribute
{
    public BestAttribute()
    {
        
    }

    public BestAttribute(TimeSpan timeout)
    {
        this.TimeOut = timeout;
    }

    public TimeSpan TimeOut { get; set; }
}
```

```CSharp
[Best(TimeOut = new TimeSpan())]  // 'TimeOut' is not a valid named attribute argument because it is not a valid attribute parameter type
[Best(new TimeSpan())]  // Attribute constructor parameter 'timeout' has type 'TimeSpan', which is not a valid attribute parameter type
public async Task FileStorageTest()
```

**Comment by maliming** [comment]
This has nothing to do with abp.
see https://stackoverflow.com/questions/3192833/why-decimal-is-not-a-valid-attribute-parameter-type

**Comment by netcore-jroger** [comment]
When I want to set timeout on a specified method, can I only set it globally?

**Comment by maliming** [comment]
You need to specify a constant timeout or manually begin a unit of work.

**Comment by netcore-jroger** [comment]
This is a bad solution. 👎

**Comment by netcore-jroger** [comment]
```
public int TimeoutSeconds { get; set; }
```
