### ISSUE TITLE
How to creating Seed Data for Roles ? 

### ISSUE THREAD

**Issue by octalpixel** [abpframework/abp#3087]
I have a few roles that I want to seed roles and seed user based on some of the roles. How can I achieve this ?

I couldnt find a solution based on my searches.

**Comment by ismcagdas** [comment]
You can create a Seeder like this one https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeeder.cs

**Comment by octalpixel** [comment]
> You can create a Seeder like this one https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeeder.cs

How are assign the privileges for the new roles to have access  AppUser ? Attached the error as an image
![image](https://user-images.githubusercontent.com/30002284/76502723-8fcb5580-646a-11ea-8860-90d68f264ea0.png)

**Comment by gdlcf88** [comment]
You can seed permissions to new roles after you create them.

**Comment by octalpixel** [comment]
> You can seed permissions to new roles after you create them.

@gdlcf88 any reference I can refer to get this sorted ?

**Comment by gdlcf88** [comment]
> > You can seed permissions to new roles after you create them.
> 
> @gdlcf88 any reference I can refer to get this sorted ?

https://github.com/abpframework/abp/issues/2417

**Comment by octalpixel** [comment]
@ismcagdas @gdlcf88 both of your suggestions worked perfectly. Thank you
