### ISSUE TITLE
Can't resolve all parameters

### ISSUE THREAD

**Issue by chougule-lalit** [abpframework/abp#3096]
Cannot find the root cause of this issue , angular v9 , asp.net core 3.1 & Volo.Abp 2.1

![ipmsgclip_s_1584022235_0](https://user-images.githubusercontent.com/45535527/76530230-6fff5600-6499-11ea-892e-13a2762b46db.png)

If anyone have solved this issue please revert !!!

**Comment by maliming** [comment]
What are the steps to reproduce the problem?

**Comment by chougule-lalit** [comment]
The issue was with the BookState class

import { State, Action, StateContext, Selector } from '@ngxs/store';
import { GetBooks } from '../actions/books.actions';
import { Books } from '../models/books';
import { BooksService } from '../../books/shared/books.service';
import { tap } from 'rxjs/operators';

@State<Books.State>({
       name: 'BooksState',
       defaults: { books: {} } as Books.State
})
export class BooksState {
      @Selector()
      static getBooks(state: Books.State) {
      return state.books.items || [];
  }

  constructor(private booksService: BooksService) { }

  @Action(GetBooks)
      get(ctx: StateContext<Books.State>) {
      return this.booksService.get().pipe(
      tap(booksResponse => {
      ctx.patchState({
       books: booksResponse,
        });
      }),
    );
  }
}

After this code these warnings appeared in the console window.

![ipmsgclip_s_1584081973_0](https://user-images.githubusercontent.com/45535527/76597528-b058e580-6526-11ea-824b-17ec014b3887.png)

After reading these warning i just added the following code 

`import { Injectable } from '@angular/core';`

`@Injectable({
  providedIn: 'root'
})`

Issue resolved . 
@maliming Thanks for the trying to help ...

**Comment by thoseyears** [comment]
@maliming Thanks a lot.
