### ISSUE TITLE
Overriding AppService mantains both services

### ISSUE THREAD

**Issue by luisp88** [abpframework/abp#3101]
I need to add a profilePicture database field for my AbpUsers, so I extended IdentityUserAppService and changed the return with new Dto (this dto extends from IdentityUserDto, so dont need to change the inerface signatures).
![image](https://user-images.githubusercontent.com/4925069/76570912-1c8b0900-6495-11ea-844b-d20e03880e9c.png)
Al worked fine, the problem is that I see "old" and "new" identityappservice, and both goes to the same method and return the Dto with the profile picture (that is ok)
Custom:
![image](https://user-images.githubusercontent.com/4925069/76570821-ed749780-6494-11ea-85a2-2837b26bde92.png)
Original:
![image](https://user-images.githubusercontent.com/4925069/76570862-00876780-6495-11ea-862f-97617d3ad58b.png)

Is there a easier way to achieve that?
Thanks in advance

**Comment by luisp88** [comment]
Did the same with AbpApplicationConfigurationAppService to insert an AppVersion value in ApplicationConfigurationDto and also, two endpoints in swagger
MyAbpApplicationConfiguration
and
AbpApplicationConfiguration

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/docs/en/Customizing-Application-Modules-Overriding-Services.md

```
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentityUserAppService))]
public class MyIdentityUserAppService : IdentityUserAppService
```

see https://docs.abp.io/en/abp/latest/Dependency-Injection#exposeservices-attribute

**Comment by luisp88** [comment]
Hi, I already did this and still duplicated on swagger... Also tried the .Replace in configureServices of MyProjectApplicationModule without success. Both GetList methods goes into my custom MyIdentityUserAppService, but there are two endpoints in swagger as the image shows.
Something else I am missing?

**Comment by maliming** [comment]
@luisp88 Can you use cli to create a project that reproduces the problem?

**Comment by luisp88** [comment]
@maliming I just saw your recently answer in another post yesterday (#3123) that has the exact same problem than me
This solves 
`    [ExposeServices(typeof(IAbpApplicationConfigurationAppService), typeof(AbpApplicationConfigurationAppService))]
    [RemoteService(IsEnabled = false)]
    public class MyAbpApplicationConfigurationAppService : AbpApplicationConfigurationAppService, IAbpApplicationConfigurationAppService`
Thanks.
