### ISSUE TITLE
AuditLogActionConsts.MaxParametersLength is too short.

### ISSUE THREAD

**Issue by Rwing** [abpframework/abp#3102]
https://github.com/abpframework/abp/blob/110f015d38b48c7636d89dc31eacd01202134b47/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain.Shared/Volo/Abp/AuditLogging/AuditLogActionConsts.cs#L9
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain/Volo/Abp/AuditLogging/AuditLogAction.cs#L46

In some cases it's to short, should we change it to MAX ?

**Comment by maliming** [comment]
@hikalkan What do you think?

**Comment by Rwing** [comment]
@maliming Is there any workaround to this problem now? I have a system in production that needs to be solved

**Comment by maliming** [comment]
>  Is there any workaround to this problem now? 

Unfortunately No.

**Comment by Rwing** [comment]
So sad 😢

**Comment by maliming** [comment]
You can download the audit-logging's source code and change it, then release a temporary package to solve this problem.

**Comment by Rwing** [comment]
Okay, it's a temporary solution.
But I want waitting for @hikalkan to decide how to solve this problem。

**Comment by Rwing** [comment]
Is there any plan to resovle this?

**Comment by jortygu** [comment]
just like DbTablePrefix,can cusomize MaxParametersLength

**Comment by hikalkan** [comment]
I will work on this in the next milestone to see if we can provide a simple way to make all such constants changeable.

**Comment by hikalkan** [comment]
There are two main cases;

* Making the length consts has an advantage: We can use it on data annotation properties on create/update DTOs. I know, MaxParametersLength is not something like that, but speaking in general.
* 2000+ is not working for Oracle.

However, I will try to resolve this problem with https://github.com/abpframework/abp/issues/4139
It will probably a breaking change (an easy-to-fix one, hopefully).
