### ISSUE TITLE
Using BackgroundWorker causes memory problem

### ISSUE THREAD

**Issue by zhxymh** [abpframework/abp#3104]
When we upgraded the apb framework from 1.1.2 to 2.2.1, the memory footprint of our program continued to increase with the running time. And finally, it was related to BackgroundWorker. 

I wrote an only BackgroundWorker program test that can reproduce this memory problem. I found object **Autofac.Extensions.DependencyInjection.AutofacServiceProvider** Numbers have been growing, unable to release. 

Can you help me to see if it is the problem I use?

This is my test program, which can reproduce the above problem:
https://github.com/zhxymh/AbpBackgroundWorkerTest

Environment
```
.NET Core 3.1.100
ubuntu.18.04-x64
```
Thx!

**Comment by maliming** [comment]
I will test it, thank you for your feedback.

**Comment by maliming** [comment]
Try this, I tested in windwos and found no memory leaks.
```
protected override async Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
{
	using (var serviceScope = workerContext.ServiceProvider.CreateScope())
	{
		var service = serviceScope.ServiceProvider.GetRequiredService<ITestService>();
		await service.RunAsync();
	}
}
```

**Comment by zhxymh** [comment]
I tried this, and it's still the same. After I ran for a few minutes, there was a lot of Autofac.Extensions.DependencyInjection.AutofacServiceProvider in the stack. And it will grow over time.

```
(lldb) dumpheap -stat
Statistics:
              MT    Count    TotalSize Class Name
00007fca8facff58     1060        33920 Autofac.Extensions.DependencyInjection.AutofacServiceProvider
00007fca8f1632b0      532        34048 System.Action
00007fca8f3c2a68      534        34176 System.Action`1[[System.Object, System.Private.CoreLib]]
00007fca8ec9acd0      984        35256 System.Type[]
00007fca8facbd50      528        38016 AbpBackgroundWorkerTest.TestWorker+<DoWorkAsync>d__1
00007fca8fd39d48      529        38088 System.Threading.Tasks.UnwrapPromise`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]]

```

**Comment by maliming** [comment]
Can you try your `AbpBackgroundWorkerTest `project on windows platform?

**Comment by zhxymh** [comment]
No problem. I'll test it.

**Comment by zhxymh** [comment]
@maliming Sorry, I find that I can't reproduce now, I find that the growth stops at a certain point. I will test again and again by myself, thank you very much!
