### ISSUE TITLE
Chinese document bookmarks not work

### ISSUE THREAD

**Issue by mentianyi** [abpframework/abp#3119]
e.g. [解决方案结构](https://docs.abp.io/zh-Hans/abp/latest/Startup-Templates/Module#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E7%BB%93%E6%9E%84)

Basic.Global......has errors.

**Comment by liangshiw** [comment]
Any errors?

**Comment by mentianyi** [comment]
> Any errors?

Your page has no errors?

**Comment by mentianyi** [comment]
![image](https://user-images.githubusercontent.com/11286219/76698070-6bc17b80-66d9-11ea-91eb-7519053894f8.png)
