### ISSUE TITLE
Cannot migarate db after change prefix

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#3121]
I do read the thread [1429](https://github.com/abpframework/abp/issues/1429), and I use code
on the program.cs of mycompay.myproject.DbMigrator:

` public static int Main(string[] args)
        {
            AbpCommonDbProperties.DbTablePrefix = "myprefix";`

When I migrate the database, got error:

`ERR] Failed executing DbCommand (50ms) [Parameters=[@__name_0='?' (Size = 128), @__providerName_1='?' (Size = 64)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [r].[Id], [r].[Name], [r].[ProviderKey], [r].[ProviderName], [r].[Value]
FROM [myprefixSettings] AS [r]
WHERE (([r].[Name] = @__name_0) AND ([r].[ProviderName] = @__providerName_1)) AND [r].[ProviderKey] IS NULL
[21:33:07 ERR] An exception occurred while iterating over the results of a query for context type 'Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'myprefixSettings'.
`

I also tried add 

`AbpSettingManagementDbProperties.DbTablePrefix = "myprefix";` 

but still got the same error. Are there other concerns when changing the prefix?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/1387#issuecomment-506645119

1. Every module has option to change schema & table prefix. Examples:

````csharp
IdentityServerDbContext.TablePrefix = "AbpIdentityServer";
IdentityServerDbContext.Schema = "Abp";
````

Run this code in the beginning of your application. They are static properties. **You can add this code to Program.cs for all db-using applications (migrator, web... etc.).**

2. If you don't use IDS4, you can remove the related module packages, remove ConfigureIdentityServer in your migration dbcontext and add a new migration which will delete the tables.
IDS4 modules are added in the startup template since most applications may need it and it is a bit hard to configure it :)

**Comment by evenlee** [comment]
Thanks @maliming, I've tried in program file of migrator project
` MyPrjectNameDbContext.TablePrefix = "myprefix";`
and
` IdentityServerDbContext.TablePrefix = "AbpIdentityServer";`

both of them have error:
'MyPrjectNameDbContext' does not contain a definition for 'TablePrefix'
'IdentityServerDbContext' does not contain a definition for 'TablePrefix'

I ues the angular template(integrated identity server), did I miss some nuget Libararies?

**Comment by maliming** [comment]
It looks like the name has changed, try it.
```
AbpIdentityServerDbProperties.DbTablePrefix = "MyIdentityServer";
```

**XXXDbTablePrefix**
https://github.com/abpframework/abp/search?q=DbTablePrefix&unscoped_q=DbTablePrefix

**Comment by evenlee** [comment]
interesting, this is the way I used at the beginning:
```
AbpCommonDbProperties.DbTablePrefix = "myprefix";
AbpSettingManagementDbProperties.DbTablePrefix = "myprefix";
```

but I got errors from the above.

**Comment by maliming** [comment]
hi
This is my approach.
https://github.com/maliming/AbpModulePrefix
https://github.com/maliming/AbpModulePrefix/commit/2cf890a012079d35c67d998745c5bafc2ac9ba91

**Comment by evenlee** [comment]
thanks for you approach, I think I found the reason, when changing prefix, the migration command need to be followed.

I saw your new migration record:

`20200316032406_rename.cs `

But when I run 'dotnet ef migrations add rename_table' under DbMigrationss project, I got error:

`e configuration file 'appsettings.json' was not found and is not optional. The physical path is '/Users/userABC/Downloads/AbpModulePrefix-master/src/Acme.BookStore.EntityFrameworkCore.DbMigrations/appsettings.json'.`

I tested the project in Windows, use 'Add-Migration', it works, but in Mac, the dotnet ef command does not work.

**Comment by maliming** [comment]
> But when I run 'dotnet ef migrations add rename_table' under DbMigrationss project, I got error:

```
dotnet ef migrations add rename_table -s ..\Acme.BookStore.Web\Acme.BookStore.Web.csproj
```

```
-s   --startup-project <PROJECT>  Relative path to the project folder of the startup project. Default value is the current folder.
```

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#common-options

**Comment by evenlee** [comment]
thanks, -s parameter works.
