### ISSUE TITLE
How To Replace Auto Api

### ISSUE THREAD

**Issue by chaoyi996** [abpframework/abp#3123]
Hi：
I Include 'EasyAbp.Abp.SettingUi'  in a project ,It is work well.
Now I want to execute some of my code when the user updates the settings
I tried to override 'settinguiappservice. Setsettingvalues' and found that it did replace the service,But the auto API has not been rewritten and a new API like '/API/APP/mysettingui/setsettingvalues' has been generated,Old APIs still exist.
How To Replace Auto Api?
Thanks

**Comment by maliming** [comment]
see https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services

**Comment by chaoyi996** [comment]
> see https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services

I try to follow the document, and the result is that the service can be  overwrite, but the dynamic API cannot be overwrite.

I looked at the code of IdentityUserAppService in the example. found that not using the automatic API, that created a controller to call the identityUserAppService

**Comment by maliming** [comment]
Maybe you can ask `EasyAbp.Abp.SettingUi` why there is no `HttpApi`?
https://github.com/EasyAbp/Abp.SettingUi/issues/new

**Comment by chaoyi996** [comment]
My question is how to rewrite the dynamic API

**Comment by maliming** [comment]
> My question is how to rewrite the dynamic API

You can try use the `ExposeServices` attribute, I'm not sure.

```
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(SettingUiAppService ))]
public class MySettingUiAppService : SettingUiAppService 
{
}
```

**Comment by chaoyi996** [comment]
> > My question is how to rewrite the dynamic API
> 
> You can try use the `ExposeServices` attribute, I'm not sure.
> 
> ```
> [Dependency(ReplaceServices = true)]
> [ExposeServices(typeof(SettingUiAppService ))]
> public class MySettingUiAppService : SettingUiAppService 
> {
> }
> ```
Yes, I did the same.
but the result like I said:
1.The service has been replaced. If I inject the service into the page(controller) and call it, I can get the sure result.
2.Old API not removed
3.New Auto API created, route like '/API/APP/**my**settingui/setsettingvalues'

Remarks:
When I try to rewrite the Identityuserappservice according to the document, the automatic API system still generates a new API for the new service.It could be a bug

Thanks.

**Comment by maliming** [comment]
First, the method of `SettingUiAppService `should be virtual.

Then we can disable the remote service of `MySettingUiAppService`. And expose `ISettingUiAppService `and `SettingUiAppService`.

![image](https://user-images.githubusercontent.com/6908465/76703651-f45a0f00-670d-11ea-8e73-15177e6ec924.png)

**Comment by chaoyi996** [comment]
Thank you for your answer.
 I've overlooked something,
The method in SettingUiAppService is not virtual and cannot be overridden,I implemented an interface again
this is my code
![image](https://user-images.githubusercontent.com/14135714/76704313-0e4a2080-6713-11ea-88f7-0922183a4531.png)

But I haven't successfully implemented the API coverage,
Can only virtual methods that can be rewritten be overwritten?
Isn't the way of reimplementing the interface like this not working properly?

Thanks
chaoyi996

**Comment by maliming** [comment]
The method of `SettingUiAppService `should be `virtual`.
https://github.com/EasyAbp/Abp.SettingUi/issues/new

**Comment by journey191** [comment]
Hi,@maliming 
If disable the remote service,the methods of this service cannot be found in another microservice by Dynamic C# API Client Proxies.

```
[Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IIdentityUserAppService), typeof(IdentityUserAppService), typeof(IMyIdentityAppService), typeof(MyIdentityUserAppService))]
    [RemoteService(IsEnabled = false)]
    [Authorize]
    public class MyIdentityUserAppService : IdentityUserAppService, IMyIdentityAppService
```

```
private IMyIdentityAppService _userService;

        public TestAppService(IMyIdentityAppService userService)
        {
            _userService = userService;
        }

public async Task<int> GetUserCountAsync()
        {
            var list = await _userService.GetAllListAsync(new MyIdentityUserNonePageInput()
            {
                Filter = null
            });
            return list.Items.Count;
        }
```

![image](https://user-images.githubusercontent.com/11626700/122756263-c24c3b00-d2c8-11eb-8fce-ddea418607b3.png)

**Comment by maliming** [comment]
HI journey191 

Can you try this in the latest version abp? 

https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller
