### ISSUE TITLE
HttpApi.Host project needs EfCore.Tools reference in module startup template.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#3124]
https://github.com/abpframework/abp/blob/dev/templates/module/aspnet-core/host/MyCompanyName.MyProjectName.HttpApi.Host/MyCompanyName.MyProjectName.HttpApi.Host.csproj

Or we cannot migrate the `MyModule_Module` database.

**Comment by maliming** [comment]
If you like, you can contribute code. :)
