### ISSUE TITLE
How to map ExtraProperties of an entity to a type-safe DTO?

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3128]
[ExtraProperties](https://docs.abp.io/en/abp/latest/Entities#extra-properties) of an entity is a dictionary that contains some additional properties related to the entity.

If you map such an entity to a DTO (or vice verse), the values in the extra properties will not be mapped as you can expect. You can manually define AutoMapper mapping configuration.

Since this is pretty standard, we can define some extension methods & conventions to make this easier.

**Comment by iyilm4z** [comment]
I think this feature is already implemented [here](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AutoMapper/AutoMapper/AbpAutoMapperExtensibleDtoExtensions.cs)?

**Comment by hikalkan** [comment]
No, it doesn't. It maps Obj1.ExtraProperties to Obj2.ExtraProperties (copy the items inside the dictionary).
This issue is about copying an item in the dictionary to a regular property of another object. Obj1.ExtraProperties["Name"] to Obj2.Name.

**Comment by iyilm4z** [comment]
As you know we use [ExtensibleObjectMapper](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.ObjectExtending/Volo/Abp/ObjectExtending/ExtensibleObjectMapper.cs) for mapping SrcObj.ExtraProperties to DestObj.ExtraProperties. This class contains methods working with two objects implement IHasExtraProperties interface.

Below possible steps to help us having this feature. 

1-Make implementing IHasExtraProperties optional for destination objects in ExtensibleObjectMapper or create a new class specially for this feature(we always should apply required extensible object logic for source)
2- Use Apb's json serializer for mapping ExtraProperties of source to destination's properties like [here](https://stackoverflow.com/questions/7310533/dictionary-string-string-map-to-an-object-using-automapper).(this is just a logic, sure we can modify it)

What do you think about this possible solution?

**Comment by hikalkan** [comment]
Hi,

1- I thought we can just an option to `MapExtraProperties` definition here: https://docs.abp.io/en/abp/latest/Object-To-Object-Mapping#mapping-the-object-extensions (like `bool mapToRegularProperties = false`).
2 - I wouldn't use the JSON serialization for such a simple think that can be easily done via reflection.
