### ISSUE TITLE
Permission and roles

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#3130]
Hi,

We can define permissions in our modules.
How can we attach this permissions to roles ? For example: at least admin role ?
Is data seed-ing only option, or there is another way - with code ?

**Comment by ismcagdas** [comment]
@sebitsi [PermissionManagementModal](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Web/Pages/AbpPermissionManagement/PermissionManagementModal.cshtml.cs) already has an example. Do you want to use it like that ?
