### ISSUE TITLE
Create local Identity User after external login (AAD) from angular

### ISSUE THREAD

**Issue by luisp88** [abpframework/abp#3144]
I already have the AAD login success, put the token in http request (via local storage access_token) and everything works fine. The problem is that when AAD is used, no local identity is created and it passes the [Authorized] but I doesnt have any user permissions, so I need to create and "assign" to the local user.
Adds the authentication (api):
![image](https://user-images.githubusercontent.com/4925069/76767229-07a1c480-6778-11ea-988c-cae7ff8eab74.png)
Adds the AAD prompt (angular):
![image](https://user-images.githubusercontent.com/4925069/76767368-40da3480-6778-11ea-924d-20744b41d882.png)
When obtained the token, set to local storage and it uses automatically in requests headers (that's why Authorized is passed ok):
![image](https://user-images.githubusercontent.com/4925069/76767495-75e68700-6778-11ea-96b2-6b00feb9852d.png)

**Comment by luisp88** [comment]
I already checked #2815 but that uses .cshtml pages

**Comment by luisp88** [comment]
It seems that it only needs the access_token in localStorage and it is not validating anything in backend (removed the AddAzureAd or AddAzureADBearer and behaviour is the same)
![image](https://user-images.githubusercontent.com/4925069/76772917-6ec37700-6780-11ea-866e-8f011ce2fa71.png)
Someone has this already working?

**Comment by gterdem** [comment]
Hello @luisp88,

Did you solve the problem?
If not, can you give me more information about your project structure? (tiered  etc)

**Comment by luisp88** [comment]
@gterdem thanks for your concern.
I'm using abp template: EFCore angular, all backend projects in same solution (identityserver is in the same backend project).
My angular project (using `import { MsalGuard } from '@azure/msal-angular';`) redirect to MS login and authenticate the user in its tenant OK, but the backend isn't authenticating the calls
Localstorage after MS Login:
![image](https://user-images.githubusercontent.com/4925069/79995417-313fc100-8485-11ea-8b2b-28d89e47c1bc.png)
Http requests is sending bearer in header:
![image](https://user-images.githubusercontent.com/4925069/79995821-b1febd00-8485-11ea-82f1-58edf801f1b9.png)
But api logs shows:
AuthenticationScheme: Bearer was not authenticated.
![image](https://user-images.githubusercontent.com/4925069/79996004-eecab400-8485-11ea-9874-57a7405c7a6c.png)

My code (based on your documentation):
![image](https://user-images.githubusercontent.com/4925069/79997980-263a6000-8488-11ea-8e30-6583d0d2ed29.png)

I have two azure app registration configured, one for angular and one for backend. The frontapp has the callbackUrl since it will be doing the authentication and what I think is that the backendapp  will be checking the token when angular makes endpoint calls.

**Comment by luisp88** [comment]
If I use /account/login's AzureActiveDirectory button, I can login and go thru my custom sign in manager (getexternallogin, etc), so I think it is something to do with the call from angular to API. I was passing in auth bearer the rawIdToken from MS, but I think I need to do something else to get the actual access token before calling my API? If someone could guide me I would appreciate it a lot. Thanks in advance
