### ISSUE TITLE
Multi-Tenancy dependency in 'Volo.Abp.AspNetCore.Serilog'

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3147]
It seems that _Volo.Abp.AspNetCore.Serilog_ is dependant on _Volo.Abp.MultiTenancy_ - is this intentional?

**Comment by maliming** [comment]
`Volo.Abp.AspNetCore.Serilog`  requires use `ICurrentTenant`.

**Comment by olicooper** [comment]
Ah okay, that makes sense, thanks.
