### ISSUE TITLE
NGXS Logger should be able to ignore some actions

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#3152]

**Comment by armanozak** [comment]
Development has been completed, but NGXS team should publish the new version for us to use it.

**Comment by armanozak** [comment]
The new version of NGXS is not released yet.

**Comment by armanozak** [comment]
The new version of NGXS is still not released.

**Comment by armanozak** [comment]
The new version of NGXS is still not released.

**Comment by armanozak** [comment]
The new version of NGXS is still not released.

**Comment by bnymncoskuner** [comment]
> The new version of NGXS is still not released.

#FeelsBadMan

**Comment by armanozak** [comment]
NGXS v3.7 has been integrated in ABP.
