### ISSUE TITLE
List module names for people to download or add

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#3161]
Currently folks don't know the names of modules. We can list it with a CLI command or list on abp.io website.

**Comment by nadeemkhoury** [comment]
Hi There, 
Any update on this issue?

What is the name of the account module ?

**Comment by yekalkan** [comment]
> What is the name of the account module ?

`Volo.Account`

**Comment by nadeemkhoury** [comment]
Thank you so much for your response. I was able finally to reach out to all Module Names, however, if I need to contribute and write the names of the modules to the docs, can you please provide me a link or how can I do that ? 

Thanks

**Comment by iyilm4z** [comment]
@nadeemkhoury [Here](https://github.com/abpframework/abp/tree/dev/modules) is free modules.
[Here](https://commercial.abp.io/modules) are commercial modules. This may help you.
@yekalkan for cli side, you mean listing only app modules or all modules(framework and app)?

**Comment by yekalkan** [comment]
@iyilm4z app modules

https://docs.abp.io/en/abp/latest/Modules/Index#open-source-application-modules

**Comment by iyilm4z** [comment]
@yekalkan let me tell you what i think to do cli work.

**Comment by iyilm4z** [comment]
@yekalkan let me tell you what i think to do cli task.
1. We need an api endpoint which returns names and descriptions of app modules just like in the link you shared.(maybe there is already one?)
2. A cli command to list all app modules.(all installed in current app? or just all retrived from the api endpoint?)

**Comment by yekalkan** [comment]
> We need an api endpoint which returns names and descriptions of app modules just like in the link you shared.(maybe there is already one?)

Yes, there is already one: https://www.abp.io/api/download/modules

> A cli command to list all app modules.

This is the subject of this issue. I'll move this to current milestone.

**Comment by iyilm4z** [comment]
Before starting to work on this feature, i wanted to be sure if i understood everything correctly. However i see that you assigned it to yourself, cool:)

**Comment by gdlcf88** [comment]
I'm developing a new version AbpHelper GUI app, it can be used to list community modules and install them to your apps or modules. The module list source is https://github.com/EasyAbp/ModuleLibrary/blob/main/index.json, every module has a "target", for example, `EasyAbp.EShop.Application` module's target is `Application`, it means this module will be installed to the Application project of your apps by default, so it may realize one-click module installation.

Here are some screenshots of the new GUI app:

![image](https://user-images.githubusercontent.com/30018771/108834992-cf526980-7609-11eb-8069-3fcd2a054376.png)
![image](https://user-images.githubusercontent.com/30018771/108834997-d1b4c380-7609-11eb-9e27-40ede465300c.png)
![image](https://user-images.githubusercontent.com/30018771/108835008-d5e0e100-7609-11eb-89b4-2b27ee31df2e.png)
![image](https://user-images.githubusercontent.com/30018771/108835018-d8dbd180-7609-11eb-93e0-d10e8fd8eabd.png)
![image](https://user-images.githubusercontent.com/30018771/108835027-dbd6c200-7609-11eb-9318-60d85aa493dd.png)

This new GUI app is planned to be released at the end of this month or early next month.

**Comment by nadeemkhoury** [comment]
@yekalkan I have abp cli version 4.2.2 and I can't find the command list-modules. 
Additionaly, the documentation is not updated with a new command as well as the command list. Can you please help ?

**Comment by yekalkan** [comment]
@nadeemkhoury This feature will be available in v4.3.0
