### ISSUE TITLE
Major revision for module class/methods

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3166]
For pre-built application modules;

- [x] Make all public/protected methods virtual (including entities, domain services, application services, page models, view components...) to make them easily overridable.
- [x] Make all private methods of domain & application services "propected virtual" to also be able to override them.

**Comment by cotur** [comment]
- [ ] Account
- [ ] Audit Logging
- [ ] Background Jobs
- [ ] Feature Management
- [ ] Identity
- [ ] Identity Server
- [ ] Permission Management
- [ ] Setting Management
- [ ] Tenant Management
