### ISSUE TITLE
Documentation missing for migration for book entity

### ISSUE THREAD

**Issue by StevenOwenNell** [abpframework/abp#3169]
Part one of the tutorial is missing a migration section.

**Comment by maliming** [comment]
Which document?

**Comment by GerryGe** [comment]
> Part one of the tutorial is missing a migration section.
migration section have moved to "Getting Started".

**Comment by StevenOwenNell** [comment]
[ASP.NET Core Angular Tutorial - Part 1](https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=NG#asp-net-core-angular-tutorial-part-1)

Nowhere on this tutorial is a migration mentioned to update the database with the book entity

**Comment by StevenOwenNell** [comment]
I am using SQL Server as the DB and I saw what to do in the MVC tutorial, I think that the solution to this task would be to create Documentation for Angular UI and Entity Framework Core. (I think the effort will then be much more than 0.5 @maliming )

**Comment by maliming** [comment]
hi @StevenOwenNell 

Angular uses mongodb it does not require migration.

https://github.com/abpframework/abp/blob/dev/docs/en/Tutorials/Part-1.md

```
if UI == "MVC"
  DB="ef"
  DB_Text="Entity Framework Core"
  UI_Text="mvc"
else if UI == "NG"
  DB="mongodb"
  DB_Text="MongoDB"
  UI_Text="angular"
```

**Comment by StevenOwenNell** [comment]
Hi @maliming 
Indeed it is not part of that tutorial and I got what I needed to from the MVC tutorial for the migration part.

Happy to close this :)
