### ISSUE TITLE
Load specific set of child entities only

### ISSUE THREAD

**Issue by SoloHam** [abpframework/abp#3170]
Currently in order to load the child entities you have no option to do so using AppServices. I get that it's by design so you have to access the repository and use the `WithDetails` method to include entities but that also only allows you to include one child entity and in order to include more than one you have to specify the default `WithDetails` method in EFCoreModule but the drawback of that is let's say I want all entities at one point in the application and only two at the rest I still will have to be including all entities for even the places I don't need them. 

Does there exist a workaround or even a solution that I might not be aware of? Please inform me if so otherwise when will this be added to the framework?

Thanks.

**Comment by SoloHam** [comment]
@maliming Please shed some light. Thanks.

**Comment by maliming** [comment]
I think you can pass an include delegate in the repository method.

```
Getlist(string name, params Expression<Func<TEntity, object>>[] propertySelectors);
```

**Comment by SoloHam** [comment]
IRepository:
```
public interface IRepository<TEntity, TKey> : IRepository<TEntity>, IReadOnlyRepository<TEntity>, IQueryable<TEntity>, IEnumerable<TEntity>, IEnumerable, IQueryable, IReadOnlyBasicRepository<TEntity>, IRepository, IBasicRepository<TEntity>, IReadOnlyRepository<TEntity, TKey>, IReadOnlyBasicRepository<TEntity, TKey>, IBasicRepository<TEntity, TKey> where TEntity : class, IEntity<TKey>
```

The `IRepository` interface doesn't seem to have a `Getlist` method. It only has the following:

![Annotation 2020-04-09 132135](https://user-images.githubusercontent.com/8042978/78873957-13c22e80-7a65-11ea-8134-4dd35c4983d1.png)

And none of these have a method that takes a delegate. 

`GetAsync` & `GetListAsync` take a boolean `includeDetails` which I suppose calls the default `WithDetails` function but I could be wrong. 

GetListAsync:
```
Task<List<TEntity>> GetListAsync(bool includeDetails = false, CancellationToken cancellationToken = default);
```

GetAsync:
```
Task<TEntity> GetAsync(Expression<Func<TEntity, bool>> predicate, bool includeDetails = true, CancellationToken cancellationToken = default);
```

In any case none of the repository methods take that delegate for including specific set of entities.
As a workaround I've to define the default `WithDetails` method in EFCoreModule and call `Repository.WithDetails().Where(...)` wherever I need more than one child entity included.

**Comment by maliming** [comment]
I mean you implement custom repository method and pass include delegate.

**Comment by hikalkan** [comment]
Hi,

Repository pattern's purpose is to provide a unified interface accross different database systems. If you want to use EF Core API in the application layer, add `Volo.Abp.EntityFrameworkCore` package to your application layer and directly use its API. When you add the package, then you can directly do it: `_myRepository.Include(...).Where(...).ToListAsync()`.
