### ISSUE TITLE
Many controllers in *.HttpApi take too long to load a project

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#3180]
Hi,

I'm facing a problem that when I define many many controllers (around 100 controllers), It takes too long to start project *.HttpApi.Host

How can I solve this issue ?

**Comment by maliming** [comment]
Can you share the application's log?

Is the request slow after the application is started?

**Comment by volethanh** [comment]
The request is normal, but when I start debug the application, it's very slow. I try to exclude about 90 controllers, and it's not slow anymore

**Comment by maliming** [comment]
Is it possible to reproduce the problem if there are many empty controllers?

**Comment by volethanh** [comment]
After I reproduce, I can start the project *.HttpApi.Host with many empty controllers normally. But when I try again with full actions in controller, The browser loading very long!

I attatched 2 logs for you to review. It stucks at "Starting web host"

2020-03-18 **21:04:23.124** +07:00 [INF] Starting web host.
2020-03-18 **21:10:08.538** +07:00 [INF] User profile is available. Using...
[logs_1_controller.txt](https://github.com/abpframework/abp/files/4349450/logs_1_controller.txt)
[logs_n_controllers.txt](https://github.com/abpframework/abp/files/4349451/logs_n_controllers.txt)

 
This is my controller

`using DDC.BackendService.DMS;
using DDC.BackendService.DMS.Dtos;
using DDC.BackendService.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;

namespace DDC.BackendService.CustomerProduct
{
    [RemoteService]
    [Route("api/backendservice/CustomerProduct")]
	public class CustomerProductsController : BackendServiceController
    {
        private readonly ICustomerProductsAppService _customerProductsAppService;

        public CustomerProductsController(ICustomerProductsAppService customerProductsAppService)
        {
            _customerProductsAppService = customerProductsAppService;
        }

        [HttpGet]
        [Route("Get")]
        [Authorize]
        public async Task<CustomerProductDto> GetAsync(Guid id)
        {
            return await _customerProductsAppService.GetAsync(id);
        }

        [HttpGet]
        [Route("GetList")]
        [Authorize]
        public async Task<PagedResultDto<CustomerProductDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            return await _customerProductsAppService.GetListAsync(input);
        }

        [HttpPost]
        [Route("Create")]
        [Authorize]
        public async Task<CustomerProductDto> CreateAsync(CreateOrEditCustomerProductDto input)
        {
            return await _customerProductsAppService.CreateAsync(input);
        }

        [HttpPut]
        [Route("Update")]
        [Authorize]
        public async Task<CustomerProductDto> UpdateAsync(Guid id, CreateOrEditCustomerProductDto input)
        {
            return await _customerProductsAppService.UpdateAsync(id, input);
        }

        [HttpDelete]
        [Route("Delete")]
        [Authorize]
        public async Task DeleteAsync(Guid id)
        {
            await _customerProductsAppService.DeleteAsync(id);
        }

        [HttpGet]
        [Route("GetListToSync")]
        [Authorize]

        public async Task<List<CustomerProductDto>> GetListToSync(DateTime? lastSync, string salesOrgCode, string customerCode, string salesRouteCode, int daysToSync)
        {
            return await _customerProductsAppService.GetListToSync(lastSync, salesOrgCode, customerCode, salesRouteCode, daysToSync);
        }

        [HttpGet]
        [Route("GetSerializedListToSync")]
        [Authorize]
        public async Task<ListResultWithDataVersionDto> GetSerializedListToSync(byte[] dataVersion, string salesOrgCode, string customerCode, string salesRouteCode, int daysToSync, int pageIndex, int pageSize)
        {
            return await _customerProductsAppService.GetSerializedListToSync(dataVersion, salesOrgCode, customerCode, salesRouteCode, daysToSync, pageIndex, pageSize);
        }

        [HttpPost]
        [Route("CastFromObject")]
        [Authorize]
        public CustomerProductDto CastFromObject(object obj)
        {
            return _customerProductsAppService.CastFromObject(obj);
        }
    }
}

`

**Comment by maliming** [comment]
Did you configure the correct redis connection string?

![image](https://user-images.githubusercontent.com/6908465/77022539-d833c780-69c4-11ea-9fc4-ef44ddeb9a5f.png)

**Comment by volethanh** [comment]
Redis is not the problem, I've tried again and this is the log
[logs_n_controllers1.txt](https://github.com/abpframework/abp/files/4352324/logs_n_controllers1.txt)

**Comment by maliming** [comment]
hi @hikalkan 

When I add 300 controllers, the project launch will be very slow. It may take a few minutes or even longer.

```c#

// 0-300
[Route("api/testapi/test0api")]
public class Test0Controller : MyProjectNameController
{
	[HttpGet]
	[Route("Get")]
	[Authorize]
	public string TestMethod()
	{
		return "test";
	}
}


[Route("api/testapi/test1api")]
public class Test1Controller : MyProjectNameController
{
	[HttpGet]
	[Route("Get")]
	[Authorize]
	public string TestMethod()
	{
		return "test";
	}
}

//... more

```

I debugged and found that it seems that the `EnableClassInterceptors `method will take a long time.

**And the time is constantly increasing**(`foreach (var service in services)`).

https://github.com/abpframework/abp/blob/f6084749f9a6625e0b5d18eae00dce8a7e4f1a91/framework/src/Volo.Abp.Autofac/Autofac/Builder/AbpRegistrationBuilderExtensions.cs#L86

**Comment by maliming** [comment]
300 test controllers.
https://gist.github.com/maliming/ce8b166efd854f49e414458bc2965a23

**Comment by maliming** [comment]
Wait for issues below:
https://github.com/autofac/Autofac.Extras.DynamicProxy/issues/36
https://github.com/castleproject/Core/issues/486

**Comment by maliming** [comment]
@hikalkan 

One possible solution is not to create a class proxy for the controller. That is, don't add interceptors to the controller. Because the controller's base class has too many methods and properties. It's complicated. **Use middleware or filters.**

**Comment by maliming** [comment]
The advice given by castle(https://github.com/castleproject/Core/issues/486#issuecomment-603502736) is to avoid enabling proxy classes for controllers.
