### ISSUE TITLE
Move to .NET 5!

### ISSUE THREAD

**Issue by mkmita** [abpframework/abp#3190]
.NET5 preview 1 was announced. Maybe it would be a good time to discuss this?

https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-1/

**Comment by hikalkan** [comment]
We are closely following. It is early now, but we will start (and hopefully finish) the work before it's final release (November as they've declared).

**Comment by hikalkan** [comment]
Our goal is to move to .net 5 with the ABP Framework 4.0, which will be released in Nov 2020.

**Comment by staticcat** [comment]
Is there a branch from which we can early adopt this update?

**Comment by maliming** [comment]
@staticcat There is not branch for now.

**Comment by staticcat** [comment]
What would be the process for using 5.0 now on a new project? Would just using the 3.1.2 cli to create the project and then update all the projects to use 5.0 be enough? Happy to help move this issue forward as I can see it saving us some pain later =)

**Comment by maliming** [comment]
You can't use net 5.0 now, because the **framework** and **modules** are developed based on net core 3.x.
We will upgrade after net 5 is released. or last 5.0 RC.

**Comment by maliming** [comment]
.NET 5.0 RC 1 👍
https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1/

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/3190
