### ISSUE TITLE
Failing tests of Identity Server module because of shared tempkey.rsa

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3194]
````
System.IO.IOException : The process cannot access the file 'D:\Github\abp\modules\identityserver\test\Volo.Abp.IdentityServer.MongoDB.Tests\bin\Debug\netcoreapp3.1\tempkey.rsa' because it is being used by another process.
````

Is there any way to use an in-memory tempkey instead of a shared file?

**Comment by gterdem** [comment]
![image](https://user-images.githubusercontent.com/25867/77318373-06dfd400-6d1e-11ea-8759-25c0caaaa8a3.png)

How can I reproduce this?

**Comment by maliming** [comment]
hi @gterdem 

You can try using `excel `to open the `tempkey.rsa` file, or any editor that will lock the file. Then execute the `dotnet test` command in the identityserver module.

![image](https://user-images.githubusercontent.com/6908465/77320747-170ea800-6d4c-11ea-8189-df61b1835e75.png)

**Comment by maliming** [comment]
During unit testing, files may be locked by other unit tests.

**Comment by gterdem** [comment]
Because other parallel threads trying to access to file which is already in use. Ok, working on it.

**Comment by gterdem** [comment]
Well, easier way is seems not create `tempkey.rsa` by 
```
if (builderOptions.AddDeveloperSigningCredential)
{
   identityServerBuilder = identityServerBuilder.AddDeveloperSigningCredential(false);
}
```
However this may cause clients to re-signin when identityserver is restarted as stated in this [issue](https://github.com/IdentityServer/IdentityServer4/issues/4192)
The only in-memory RSA key generation and persisting can be done with a distributed cache which is not reasonable.

@hikalkan @maliming  the best way is to override/set `identityServerBuilder.AddDeveloperSigningCredential(false)` at test modules.
I tried on `PreConfigureServices` and `ConfigureServices` of `AbpIdentityServerTestBaseModule` however I got no luck. 
Is it possible to override only signingCredential?

**Comment by maliming** [comment]
hi @gterdem 

Please refer to https://github.com/abpframework/abp/issues/1749#issuecomment-541753102

**Comment by gterdem** [comment]
thanks @maliming 
I tried it;
Once `AddIdentityServer` method of `AbpIdentityServerDomainModule` kicks in, `tempkey.rsa` is already created and it is used for validation.
```
PreConfigure<IIdentityServerBuilder>(identityServerBuilder =>
{
    identityServerBuilder.AddDeveloperSigningCredential(false);
});
```
Doesn't seem to be overriding the validator keys.

**Comment by maliming** [comment]
@gterdem Maybe this works.

```C#
public class AbpIdentityServerTestBaseModule : AbpModule
{
	public override void PreConfigureServices(ServiceConfigurationContext context)
	{
		PreConfigure<AbpIdentityServerBuilderOptions>(options =>
		{
			options.AddDeveloperSigningCredential = false;
		});
		
		PreConfigure<IIdentityServerBuilder>(identityServerBuilder =>
		{
			identityServerBuilder.AddDeveloperSigningCredential(persistKey: false, filename: Guid.NewGuid().ToString());
		});
	}
}
```

**Comment by gterdem** [comment]
@maliming Cheers. 

Works pretty fine. Sent PR about it.
