### ISSUE TITLE
AbpDictionaryExtensions.cs GetOrAdd method has conflict

### ISSUE THREAD

**Issue by zeinali0** [abpframework/abp#3195]
In our test we find out `AbpDictionaryExtensions.cs` `GetOrAdd` method has conflict with `CuncurrentDictionary` `GetOrAdd `method which is thread safe.
You most change `System.Collections.Generic` namespace of `AbpDictionaryExtensions.cs`to a more specific namespace to fix this problem.

**Comment by maliming** [comment]
>You most change System.Collections.Generic namespace of MicroNetDictionaryExtensions.csto a more specific namespace to fix this problem.

What are `MicroNetDictionaryExtensions`?

Do you mean `AbpDictionaryExtensions`?
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Core/System/Collections/Generic/AbpDictionaryExtensions.cs#L8

**Comment by zeinali0** [comment]
Yes, I mean that. Sorry my mistake.

**Comment by maliming** [comment]
Their method signatures are different, so you need to pay attention.

**Comment by zeinali0** [comment]
`public static TValue GetOrAdd<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key, Func<TKey, TValue> factory)`

this signature are same in both
