### ISSUE TITLE
Need Export/Import Excel function like abpzero

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#3196]
Need Export/Import Excel function like abpzero,any plan?

**Comment by maliming** [comment]
This is hard to abstract, and you can implement it yourself using a third-party class library.

**Comment by wakuflair** [comment]
For RazorPages, I recommand [Datatabels button extension](https://datatables.net/extensions/buttons/examples/initialisation/export.html), it's lightweight and a completely frontend feature.
