### ISSUE TITLE
AbpDbContext.OnModelCreating will config valueobject as Entity?

### ISSUE THREAD

**Issue by carsonlaw** [abpframework/abp#3207]
I have a entity with valueobject property,
I config the entity：
`builder.Entity<Entity >(b =>`
 `          {`
     ` *******`
     ` b.OwnsOne(f=>f.valueobject).WithOwner();`
`}`
But if i use `base.OnModelCreating(builder)` also,that will throw exception:
`The type 'valueobject' cannot be marked as owned because a non-owned entity type with the same name already exists.`
have any good solution?

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/2640#issuecomment-574496442

**Comment by carsonlaw** [comment]
I got it,Thank's you
