### ISSUE TITLE
chrome 80 set-cookie:samesite=lax  Default: 'Lax'

### ISSUE THREAD

**Issue by qiang999** [abpframework/abp#3227]
Ho,I hava a problem.
I use chrome 80 , find default samsite = lax , not none . But Microservice Authserver use samsite=none.
Are you have any solution by coding? Thanks.

**Comment by qiang999** [comment]
Maybe
https://www.thinktecture.com/en/identity/samesite/prepare-your-identityserver/
But I use invalid.

**Comment by maliming** [comment]
I remember using `https `to solve the problem.

**Comment by qiang999** [comment]
It‘s OK. 
Thanks.’

**Comment by lanpin** [comment]
@maliming 
The url you quoted is not the final solution to the problem, because before I reinstalled Chrome, abp.io also failed to log in, and it used https. This issue may recur at some time in the future, and if it happens again, I will record and issue the issue again.
