### ISSUE TITLE
Module Design To Implement DevExtreme

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#323]
I want to design out a module to implement the DevExtreme frame work.
IE: Installing the nuget packages, and making the base bundles..  That way I can make other modules dependent on it.

One of the things I currently use is an Error filter (Defined in Application, can probably be moved to mvc) so that way I can return 400 w/the error message instead of the "Internal Server Error Occurred" and a custom DevExtreme Exception(Defined in Core.Shared) that inherits form the AbpException.

In the new format should the Exception go in the Application or Domain or just in root of sln?  And it looks like I should inherit from the IBusinessException now.

Do you have a method to get all the inner exceptions?  IE I can either pass the message to my exception or I have to implement a DefaultExceptionToErrorInfoConverter to look for my type of DevExtremeException just like for the BusinessException?.

I also need to return 400 bad request for this type of error, is there an override for that someplace I missed, I would also love to just have this exception not wrap by default as well ;)

**Comment by bbakermmc** [comment]
@ismcagdas guidance :)

**Comment by hikalkan** [comment]
* [DefaultExceptionToErrorInfoConverter](https://github.com/volosoft/abp/blob/master/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/DefaultExceptionToErrorInfoConverter.cs) converts exception to error messages.
* HTTP Status code is determined by [DefaultHttpExceptionStatusCodeFinder](https://github.com/volosoft/abp/blob/master/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/DefaultHttpExceptionStatusCodeFinder.cs).

You can inherit from them and replace.

I had created an issue to make these easier to extend. You can delay the exception handling part a bit :)

**Comment by hikalkan** [comment]
These are related to Web and should be inside your .Web project.

Do it for your own solution first.
For now, please do not contribute your custom error converter and status finder to the framework.

**Comment by bbakermmc** [comment]
My "DevExtremeFilter" would be used mainly in the AppServices so they can be used in the Dynamic Jquery API.  And Ill probably make a custom IRepository base to implement some standard things/endpoints.

In our move to v5, we dont really use any controllers, other than for the index page, but that goes away with razor pages lol.

My idea is to make 1 DevExtreme module that has all the "base" crap like my nuget install for the paid mvc tag helpers, the base _layout/view imports.  That I can then use as a dependent module on my actual modules.

I wasnt going to contribute anything for now lol.  Just trying to structure it correctly
