### ISSUE TITLE
Design for docs search

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3238]
- [x] Change icon to magnifier (because it is same of the filter box):

![image](https://user-images.githubusercontent.com/1210527/77089677-2d002e00-6a17-11ea-8d2d-6a0b0cf27b32.png)

- [x] Work on the search result page design: https://docs.abp.io/search/en/abp/dev/design%20change

- [x] Filterbox redesign

- [x] Mobile menu design improvements

**Comment by armgnunlu** [comment]
![docs-updates](https://user-images.githubusercontent.com/36102404/77767228-cc45a680-7051-11ea-935c-f6ab33cb1ced.png)

**Comment by armgnunlu** [comment]
![search-result](https://user-images.githubusercontent.com/36102404/77767295-e4b5c100-7051-11ea-8384-590fd7c0db09.png)
