### ISSUE TITLE
How to login to Facebook on mobile device using Identity server ?

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#3239]
Can you help me please. How to login to facebook on mobile device using identification server with facebook access token?

**Comment by nguyendev** [comment]
Can you help answer this question

**Comment by maliming** [comment]
I think this is more related to asp net core + identity server.

**Comment by nguyendev** [comment]
I tried, but I could not find any instructions on it. This is an important thing for a mobile application

**Comment by gterdem** [comment]
This is related with IdentityServer. You may want to check [this guide](https://identityserver4.readthedocs.io/en/latest/topics/signin_external_providers.html).

Closing the issue. Feel free to open if it is related with abp framework.

**Comment by nguyendev** [comment]
This is one thing I want. I think, in the next version. You can add something like this
https://github.com/waqaskhan540/IdentityServerExternalAuth
