### ISSUE TITLE
Possible @abp/ng.core dependency issue (breaking change)

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3244]
I am wondering if anyone could help me out...

Today I updated `@abp/ng.core` from v2.1.0 to v2.3.0 in my custom angular app and also updated the Angular packages to Angular v9.0.2 (the same as in the demo app).

For some reason the wrong base api url is being used (`environment.apis.default.url`)... 
`CoreModule` tries to load the `application-configuration` from `http://localhost:4200/undefined/api/abp/application-configuration` instead of `https://localhost:44316/api/abp/application-configuration`.
My `environment.ts` is identical to the demo app and it is located in the same place. I've checked tsconfig.json/angular.json/package.json/app.module.ts etc. and nothing seems any out of place compared to the demo app. I have also looked at abp commit history to see if I could figure it out but I'm struggling.

Any help would be great!

**Comment by olicooper** [comment]
It seems that `ngxs` isn't loading the Config when it initializes, so when the [CoreModule](https://github.com/abpframework/abp/blob/db4b8d111b6a65b335a472b3fcf74317a171dcda/npm/ng-packs/packages/core/src/lib/core.module.ts#L122-L126) calls `getInitialData`, the Store is not populated and the api url is not valid.
https://github.com/abpframework/abp/blob/db4b8d111b6a65b335a472b3fcf74317a171dcda/npm/ng-packs/packages/core/src/lib/utils/initial-utils.ts#L7-L15

Still not sure why this isn't working !

**Comment by mehmet-erim** [comment]
Thanks for reporting @olicooper.

**Comment by mehmet-erim** [comment]
This bug has been resolved but caused a problem in Angular 9 applications.

### The problem:

Routes don't appear on the menu.

### Fixing the problem

![Screen Shot 2020-04-17 at 12 07 39](https://user-images.githubusercontent.com/34455572/79553655-78087200-80a5-11ea-8be7-6e7e63c59d2b.png)

BrowserModule, BrowserAnimationsModule, and AppRoutingModule should be placed at the top level of imports array like below:

![Screen Shot 2020-04-17 at 12 21 57](https://user-images.githubusercontent.com/34455572/79554061-2ca29380-80a6-11ea-8de6-c97e939d3391.png)

**Comment by alirizaadiyahsi** [comment]
@mehmet-erim this should be added documents.
