### ISSUE TITLE
Default MongoDB repository delete by id does not take into account ISoftDelete interface

### ISSUE THREAD

**Issue by michaelsudnik** [abpframework/abp#3256]
Hi,

I am using a MongoDB database and found that when I send a delete request for an entity that inherited from `FullAuditedAggregateRoot<Guid>`, it would actually be deleted (and not soft deleted). 

It appears that the `DeleteAsync(
            TKey id,
            bool autoSave = false,
            CancellationToken cancellationToken = default)` method on the default `MongoDbRepository<TMongoDbContext, TEntity, TKey>` repository actually just calls the `DeleteOneAsync` method on the MongoDB collection object without considering the `ISoftDelete` interface.

I created a fix/hack by overriding the method on a custom default repository class

```
Type type = typeof(TEntity);
if (typeof(ISoftDelete).IsAssignableFrom(type))
{
	var entity = await GetAsync(id, false, cancellationToken);

	await DeleteAsync(entity, autoSave, cancellationToken);
}
else
{
	await base.DeleteAsync(id, autoSave, cancellationToken);
}
```
This could be optimised in MongoDB to just perform a relevant update, rather than a Get and then an update, but just wanted to get it working for the time being.

Or - have I missed something?

Many thanks.

**Comment by maliming** [comment]
Are you talking about this method?

https://github.com/abpframework/abp/blob/f2be037bfc519bf24ac85f3604be84f921ca32b3/framework/src/Volo.Abp.MongoDB/Volo/Abp/Domain/Repositories/MongoDB/MongoDbRepository.cs#L367-L376

**Comment by michaelsudnik** [comment]
Yes.

**Comment by michaelsudnik** [comment]
What do you think?

**Comment by maliming** [comment]
This is like a bug, I will check it.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/3259
```
public override Task DeleteAsync(
	TKey id,
	bool autoSave = false,
	CancellationToken cancellationToken = default)
{
	return DeleteAsync(x => x.Id.Equals(id), autoSave, cancellationToken);
}
```
