### ISSUE TITLE
Set remote service name for all modules

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3265]
Following https://github.com/abpframework/abp/issues/3264

**Comment by hikalkan** [comment]
I've done it for the identity module: https://github.com/abpframework/abp/commit/5d22dc773206bc8c0ec25ab7e6addfb89969cdc7

The progress is simple:

- Move `RemoteServiceName` const from `<module-name>HttpApiClientModule` to the application.contracts
- Set this name to RemoteService attributes wherever used.

**Comment by cotur** [comment]
- [x] Account
- [ ] Blogging
- [ ] Feature Management
- [x] Identity
- [ ] IdentityServer
- [ ] Permission Management
- [ ] Setting Management
- [ ] Tenant Management
