### ISSUE TITLE
how to download file from FileStreamResult in ApplicationService?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#3272]
I create a service return FileStreamResult like this:
```
public class XXAppService: ApplicationService,IXXAppService
{
       public async Task<FileStreamResult> GetExport(string path)
      {
            string fileExt = GetFileExt(path);
            var memory = new MemoryStream();
            var provider = new FileExtensionContentTypeProvider();
            var memi = provider.Mappings[fileExt];
             var stream= File.OpenRead(path);

            var provider = new FileExtensionContentTypeProvider();
            var memi = provider.Mappings[fileExt];
            return new FileStreamResult(stream, memi);
      }
      private string GetFileExt(string filename)
        {
            return filename.Substring(filename.LastIndexOf("."));
        }
}
```
In the front, I write a js like this:
```
   $("#exportBtn").click(function () {
         var path="testfile.zip"//the file do exist
        _service.getExport(path);
   }
```
everything seem ok ,

![image](https://user-images.githubusercontent.com/5259153/77172169-82f8d280-6af8-11ea-9681-690b9d83a61c.png)

but the page show something error

![image](https://user-images.githubusercontent.com/5259153/77172001-3ca37380-6af8-11ea-8a05-728d9a5fc713.png)

so, what's wrong in my code?

**Comment by liangshiw** [comment]
You should return `FileStreamResult` in the controller

**Comment by zsanhong** [comment]
I tried as you said,but I got the same result. and if I test in swagger,I can download the file correct

![image](https://user-images.githubusercontent.com/5259153/77218561-84adaf00-6b67-11ea-92eb-38ec33f53159.png)
so, I think the code is wrong in my js code. But I didn't know how to correct it

**Comment by liangshiw** [comment]
Ajax cannot download files, you can direct use: ` window.location=<your http url> `

**Comment by olicooper** [comment]
Related: https://github.com/abpframework/abp/issues/2774
