### ISSUE TITLE
Remove specific BundleContributor from specific pages

### ISSUE THREAD

**Issue by javeez** [abpframework/abp#3273]
For performance purpose, is there a way to remove/disable a specific BundleContributor?

For example, I don't need DatatablesNetScriptContributor in some pages but it add up to the page size.

**Comment by Xeevis** [comment]
You can avoid using the shared theme, you can create your own from scratch.

If you indeed only want to remove certain contributors, you can do so in your web project module under ConfigureSevices(). You can either remove the entire Shared theme contributors including dependencies or just specific ones by passing respective types to Remove method.

```csharp
Configure<AbpBundlingOptions>(options =>
{
    options
    .StyleBundles
    .Get(StandardBundles.Styles.Global)
    .Contributors.Remove<SharedThemeGlobalStyleContributor>(includeDependencies: true);

    options
    .ScriptBundles
    .Get(StandardBundles.Scripts.Global)
    .Contributors.Remove<SharedThemeGlobalScriptContributor>(includeDependencies: true);
});
```

**Comment by javeez** [comment]
Thank you, got your point
