### ISSUE TITLE
Only run tenant migrations for tenants with external databases?

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3292]
I noticed the migrator console application runs for the host and every tenant. Data seeding takes a little while for my application so with multi-tenant migrations enabled it takes a long time.

Is it possible to migrate the host database and then generate a list of tenants with external databases and only run the migrations again for those tenants?

Related: https://github.com/abpframework/abp/issues/1371

**Comment by maliming** [comment]
you are right, I will try enhancement it.
