### ISSUE TITLE
Add predicate versions of all IRepository methods

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3293]
I saw this was recently implemented in https://github.com/abpframework/abp/issues/3148 but I'd love to see this for the other methods in IRepository too such as `GetListAsync`, `GetCountAsync`, `DeleteAsync`. Is this possible?

**Comment by hikalkan** [comment]
Repository already implement IQueryable. So, use `userRepository.Where(...).ToList()` or `userRepository.Where(...).Count()` for examples.

The only problem is Async versions of these methods are database provider specific. That means you need to reference to EF Core package to be able to use ToListAsync() for example.

If you want to be database independent, you can use `IAsyncQueryableExecuter` service.
