### ISSUE TITLE
abp generate-proxy - output switch

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#3295]
It will bi nice if you can extend ABP CLI generate-proxy command with output directory option.

Sometimes we need for selected module to put generated code inside custom folder.

Thanks.

**Comment by sebitsi** [comment]
Hi all.
Is there any plans impementing this switch ?

**Comment by erolarkat** [comment]
Hi,

Thanks for the suggestion. We are considering bringing this feature.

Follow the updates.

**Comment by volethanh** [comment]
Hi @erolarkat,

Is there any way to generate proxy for some selected models for angular UI ?

**Comment by erolarkat** [comment]
Hi @volethanh 

There is creation by choosing for the module, not for the model, you can create the modules you want and delete what they don't need.
