### ISSUE TITLE
Micro service demo can't build

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3296]
I just downloaded the project, tried to build but it can't. Am using latest vs 19.5 and .net core 3.1.

Issues seems to be referencing some ddl which are not there.

Any proper guide on how it works ? The online documentation is what am following

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo.
Did you use `dotnet build` ? ,it's works for me

![image](https://user-images.githubusercontent.com/16813853/77241446-2d721200-6c2d-11ea-9205-b04f98e96c2c.png)

**Comment by dicksonkimeu** [comment]
has worked. thank you.

**Comment by dicksonkimeu** [comment]
One issue now, redis cache error. Am using windows 10, how can i make it run ?

**Comment by maliming** [comment]
> redis cache error. 

You need to solve it yourself. Make sure your redis server is available and the connection string is correct.
