### ISSUE TITLE
(@abp/ng.core) How to reset  layout in lazy load module

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#3297]
@mehmet-erim 
It is very great about `DynamicLayoutComponent`,
I know i should set `layout types` in `CoreModule`,
```typescript
    CoreModule.forRoot({
      environment,
      requirements: {
//not just in core module ,but also other lazy module need to change their layouts
        layouts: LAYOUTS,
      },
    }),
```
But in my situation,I need to change layouts definition in `Lazy Load Module`:
Is there any way to do it now?
I think if we add a action for modify `Config.State.requirements` just like `SetEnvironment`(#2822).
does `DynamicLayoutComponent` works fine?

By the way ,
In `Route`, `layout` property is `enum` type ,we can define just three kinds of layout,
If let it be a `string`,we can add other custom layouts, `DynamicLayoutComponent` will be more flexibility
``` typescript
  export interface Route {
    children?: Route[];
    invisible?: boolean;
    layout?: eLayoutType//| string;
    name: string;
    order?: number;
    parentName?: string;
    path: string;
    requiredPolicy?: string;
    iconClass?: string;
  }
export const enum eLayoutType {
  account = 'account',
  application = 'application',
  empty = 'empty',
}

```
So ,I hope:
1.add `SetRequirements` action for `Config.State`
2.let `layout` of `Route`  type be `eLayoutType | string`
thank you.

**Comment by mehmet-erim** [comment]
Each ABP theme module has 3 layouts named; application, account, and empty. We designed the layout structure with this rule.

We'll change the layout definition a little bit. `requirements` property probably will be deprecated.
Please follow the this issue: #3171

You can replace a layout easily in the v2.4.
