### ISSUE TITLE
Can we use Table attribute for new entity migration

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#3298]
I created a new entity in a downloaded template:
```
 [Table("Booming")]
    public class Booming : FullAuditedAggregateRoot<Guid>
    {
        public string Name
        { get; set;}

        public string Author
        { get; set; }
    }
```
I saw we also need to config new entity in DbContextModelCreatingExtensions like below
   ```
     builder.Entity<Booming>(b =>
            {
                b.ToTable(ABCConsts.DbTablePrefix + "Booming", ABCConsts.DbSchema);
                b.ConfigureByConvention();
                //...
            });

```
I found the migraine file will be empty if not config entity in DbContextModelCreatingExtensions(put Dbset in DbContext only),
but if configured, the migration file is right, but table name is replaced by 'AppBooming'  no matter I  comment 
` b.ToTable(ABCConsts.DbTablePrefix + "Booming", ABCConsts.DbSchema);`
or not.

can we only use table attribute and only put DbSet in DbContext?

**Comment by maliming** [comment]
> I found the migraine file will be empty if not config entity in DbContextModelCreatingExtensions(put Dbset in DbContext only),

> can we only use table attribute and only put DbSet in DbContext?

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameDbContext.cs#L10-L18

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/MyProjectNameMigrationsDbContext.cs#L15-L19


> but if configured, the migration file is right, but table name is replaced by 'AppBooming' 

I think it may be that EF's table attribute has high priority.

**Comment by evenlee** [comment]
Thanks for your explanation, I copied 
`  public DbSet<Booming> Boomings { get; set; } `
to ABCMigrationsDbContext, and removed 

```
 builder.Entity<Booming>(b =>
         {
             b.ToTable(ABCConsts.DbTablePrefix + "Booming", ABCConsts.DbSchema);
             b.ConfigureByConvention();
             //...
         });
```
from DbContextModelCreatingExtensions, the table attribute works.

As my understanding, we need put table DbSet
` public DbSet<Booming> Boomings { get; set; }`
 to both ABCDbContext and ABCMigrationsDbContext,
one for runtime, one for db migrations, right?

**Comment by maliming** [comment]
No. Please refer to example:
https://github.com/abpframework/abp/blob/dev/samples/BookStore/src/Acme.BookStore.EntityFrameworkCore/EntityFrameworkCore/BookStoreDbContext.cs#L24

https://github.com/abpframework/abp/blob/dev/samples/BookStore/src/Acme.BookStore.EntityFrameworkCore.DbMigrations/EntityFrameworkCore/BookStoreMigrationsDbContext.cs#L52

**Comment by evenlee** [comment]
Then things come to the beginning, we need put 
`public DbSet<Booming> Boomings { get; set; }`

in ABCDbContext, and mapping table  in DbContextModelCreatingExtensions

```
builder.Entity<Booming>(b =>
         {
             b.ToTable(ABCConsts.DbTablePrefix + "Booming", ABCConsts.DbSchema);
             b.ConfigureByConvention();
             //...
         });
```

is this by design, the Table attribute will be replace by  the mapping, that's been said, we cannot use Table attribute. right? we must map each entity in DbContextModelCreatingExtensions?
