### ISSUE TITLE
Distributed Event Bus

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#33]
### IDistributedEventBus abstraction

- [x] Publishes events

### LocalDistributedEventBus

- [x] Publishes events using IEventBus

### RabbitMQ Integration

- [x] Implements IDistributedEventBus and publish events to RabbitMQ
- [x] Receive events of RabbitMQ, dispatches them to subscribers, acknowledges the message then.

**Comment by hikalkan** [comment]
RabbitMQ integration is moved to https://github.com/abpframework/abp/issues/593
Current implementation is not complete.

**Comment by hillin** [comment]
When will we have a documentation for this feature? (It's been in TODO state for a while)

**Comment by hikalkan** [comment]
Writing documentation one by one, it is on queue :)

**Comment by yadurajshakti** [comment]
Dear @hikalkan **Do we have Amazon MQ integration support as well?** 

I am very new to this framework and have to decide between Rabbit MQ or Amazon MQ. Any help would be greatly appreciated

**Comment by hikalkan** [comment]
>Do we have Amazon MQ integration support as well?

No, not yet. Any contribution is appreciated.
