### ISSUE TITLE
Pascal/CamelCase defined in Models

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#330]
There should be something around the type of case used for the models.
IE all models should implement a NamingStrategyType if you plan do do any JS work with it. [JsonObject(NamingStrategyType = typeof(CamelCaseNamingStrategy))]
https://www.newtonsoft.com/json/help/html/NamingStrategyAttributes.htm

Alot of the 3rd party controls IE Telerik/DevExtreme all have lambda helpers,  but they resolve to the exact name of the property, so in most cases that's Pascal :).

It would be nice to be able to override the default resolver to use the old default of Pascal, instead of camel, the only issue is, you then need to update all the existing code that you guys have implemented that is camel cased.  Or you have to override each JSON call/model on our side to be pascal based.

**Comment by hikalkan** [comment]
AspNet Core uses a global Json serialization setting. We will work on that to see if it's possible per response.

**Comment by bbakermmc** [comment]
You can can override per request if needed, but that gets annoying fast :)

EX: Currently what I do

```
[DontWrapResult]
        public virtual object GetAllDevExtreme(DataSourceLoadOptions input, bool withIncludes = true)
        {
            CheckGetPermission();

            try
            {
                return DataSourceLoader.Load(GetAllQueryable(withIncludes), input).ToJsonString(false, true);
            }
            catch (Exception ex)
            {
                throw new DevExtremeException("Load Error: ", ex);
            }
        }
```

**Comment by hikalkan** [comment]
Yes, this is a solution :))

BTW, new ABP does not have result wrapping for successful requests.

**Comment by bbakermmc** [comment]
Yeah that is what I DONT want to do lol.

For DevExteme I need no wrapping on the Error also :) per my other issue about setting the exception type to no wrap by default.

https://dotnetcoretutorials.com/2018/05/05/setting-json-serialization-configuration-at-runtime-on-a-net-core-api/

.Net core already uses json.net as the json serializer so I assume the attribute I first posted should work ;)

**Comment by laosandegudai** [comment]
> Yes, this is a solution :))
> 
> BTW, new ABP does not have result wrapping for successful requests.

hi, This is a very useful feature why did you remove it?Good for Ajax requests
