### ISSUE TITLE
DataTables.Net Actions Improvements

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3301]
- [x] Add datatables reference to the data sent to the action (currently it only send the `data.record`).
- [x] Show as a primary button if the actions only has a single item.

**Comment by fenggaoyao** [comment]
Consider Set a custom button, provided for data export, printing and column visibility control.especially When there are too many columns, the user sets which columns to display, and can sort the columns according to the user's habits.

**Comment by hikalkan** [comment]
We don't want to add such features to datatablesnet library. It probably supports such scenarios. See its documentation: https://datatables.net/

**Comment by mehmet-erim** [comment]
Github actions button:
https://cdn.discordapp.com/attachments/687626261438529536/718092078780776500/unknown.png

We can implement similar actions button. The main action can be "Edit".
