### ISSUE TITLE
Why dapperrepository's method must be virtual;

### ISSUE THREAD

**Issue by fmpfmp** [abpframework/abp#3303]
Why dapperrepository's method must be virtual;

Otherwise, an exception will be prompted: a dbcontext can only be created inside a unit of work!

**Comment by maliming** [comment]
> We recommended you always make the methods virtual. You can not use the attribute for private methods because ASP.NET Boilerplate uses dynamic proxying for that, and because private methods can not be seen from derived classes. The UnitOfWork attribute (and any proxying) does not work if you don't use dependency injection and instantiate the class yourself.

https://aspnetboilerplate.com/Pages/Documents/Unit-Of-Work#unitofwork-attribute-restrictions
