### ISSUE TITLE
Docs module: navigation tree bug after search in topics

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#3311]
To reproduce:

* open docs.abp.io
* filter topics with "agg" input
![image](https://user-images.githubusercontent.com/5793291/77304817-0dfae800-6d06-11ea-94ba-9e857c1d99ed.png)
* when you click on "Domain Layer" node, it hides search result leaves but shows other leaves.
![image](https://user-images.githubusercontent.com/5793291/77305021-5fa37280-6d06-11ea-913f-d52ffbd9d9dc.png)

**Comment by NecatiMeral** [comment]
I think this is identical to #7567 (shame on me).

**Comment by yekalkan** [comment]
@NecatiMeral Np, even i have forgotten that i detected this bug.
