### ISSUE TITLE
Add NavigationMenu to the application-configuration action

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#3312]
We should add Navigation Menu and items of it to the `api/abp/application-configuration` endpoint.
Therefore, different front-ends can build their navigation menu automatically. In the current case, a menu item is being added manually.

This has been done in AspNet Boilerplate 
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/a9211bd6ed0e17b2a5e5273cffc31fb0d237fca8/src/Abp.Web.Common/Web/Configuration/AbpUserConfigurationBuilder.cs#L212

![image](https://user-images.githubusercontent.com/9526587/77305109-8792d600-6d06-11ea-9939-eec179334808.png)

Sample DTOs for this implementation

UserMenu:
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp/Application/Navigation/UserMenu.cs

UserMenuItem:
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/e0ded5d8702f389aa1f5947d3446f16aec845287/src/Abp/Application/Navigation/UserMenuItem.cs

**Comment by hikalkan** [comment]
I think menu is a UI-related thing and should not return from server.
