### ISSUE TITLE
AbpException: en template not exist!

### ISSUE THREAD

**Issue by shelang08** [abpframework/abp#3313]
When get email template with following config, system throws error.

![2020-03-23_181626](https://user-images.githubusercontent.com/17937212/77306343-7eb7f980-6d32-11ea-8e78-e9a2cbfbd494.png)

`var template = await _emailTemplateProvider.GetAsync("notification");`
![2020-03-23_180951](https://user-images.githubusercontent.com/17937212/77305890-c1c59d00-6d31-11ea-89c3-ca76dab013fd.png)
![2020-03-23_181212](https://user-images.githubusercontent.com/17937212/77305951-e02b9880-6d31-11ea-99dd-412e1ff6165f.png)
![2020-03-23_181303](https://user-images.githubusercontent.com/17937212/77306009-f9344980-6d31-11ea-9869-5391e9f9c55d.png)

**Comment by maliming** [comment]
Is `en.tpl` an embedded file?

**Comment by shelang08** [comment]
> Is `en.tpl` an embedded file?

Yes, it is.
