### ISSUE TITLE
How to use API versioning

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#3315]
Hi,

can anyone show, how to use the api versioning properly?
As described in #2432, I checked the tests but haven't managed it to make it work with swagger and swagger-ui. I'm using auto api controllers and have separated them into a dedicated v1-namespace.

**Comment by liangshiw** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents

**Comment by hikalkan** [comment]
For the ABP side, it will be documented: https://github.com/abpframework/abp/issues/497

You can try to understand from the tests: https://github.com/abpframework/abp/tree/dev/framework/test/Volo.Abp.AspNetCore.Mvc.Versioning.Tests/Volo/Abp/AspNetCore/Mvc/Versioning

**Comment by dicksonkimeu** [comment]
Hi. Was this documented?
