### ISSUE TITLE
PagedResultDto<T> can't be interpreted in /swagger/v1/swagger.json

### ISSUE THREAD

**Issue by buzzlu** [abpframework/abp#3325]
### Sinces options.CustomSchemaIds(type => type.FullName) was introduced to method AddSwaggerGen,   the component   PagedResultDto<IdentityUserDto> can't be interpreted correctly.

# code as below
        context.Services.AddSwaggerGen(
                options =>
                {
                    options.SwaggerDoc("v1", new OpenApiInfo { Title = "Workflow API", Version = "v1" });
                    options.DocInclusionPredicate((docName, description) => true);
                    options.CustomSchemaIds(type => type.FullName);
                });
 # Pic:
![2020-03-24 13_26_54-Swagger UI](https://user-images.githubusercontent.com/23555993/77391774-83cd8500-6dd4-11ea-9d89-60c52ed978ce.png)

# Context of swagger.json:
 "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Volo.Abp.Application.Dtos.PagedResultDto`1[[Volo.Abp.Identity.IdentityUserDto, Volo.Abp.Identity.Application.Contracts, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Volo.Abp.Application.Dtos.PagedResultDto`1[[Volo.Abp.Identity.IdentityUserDto, Volo.Abp.Identity.Application.Contracts, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Volo.Abp.Application.Dtos.PagedResultDto`1[[Volo.Abp.Identity.IdentityUserDto, Volo.Abp.Identity.Application.Contracts, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]"
                }
              }
            }
          }

Any advices? 

Thanks Very Much

**Comment by maliming** [comment]
Does this cause any problems?
Or is it related to https://github.com/domaindrivendev/Swashbuckle.AspNetCore?

**Comment by hemiaoio** [comment]
@maliming When I use nswag to generate tslang, this class is very long and looks very strange. Do you have any key words to prompt?

**Comment by hemiaoio** [comment]
> @maliming When I use nswag to generate tslang, this class is very long and looks very strange. Do you have any key words to prompt?

Well ，I found a solution through the above code, using the CustomSchemaIds method to deal with these long schema names

**Comment by mrcarl79** [comment]
> > @maliming When I use nswag to generate tslang, this class is very long and looks very strange. Do you have any key words to prompt?
> 
> Well ，I found a solution through the above code, using the CustomSchemaIds method to deal with these long schema names

I've been struggling with this and the swagger.json not being liked by OpenAPI Generator, can you expand more on how you changed the long schema names?
