### ISSUE TITLE
Conflicting concept in using [AbpAutoMapFrom(typeof(Book))] on BookDto

### ISSUE THREAD

**Issue by BrianCodeman** [abpframework/abp#3327]
Hi Developers, 
While DTO is recommended to be positioned in .Application.Contracts project, according to the Doc, and .Application.Contracts never references to the .Domain project, how could it get the Book type?

Could you please guide me some best practice about this issue?

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/blob/dev/samples/BookStore/src/Acme.BookStore.Application/BookStoreApplicationAutoMapperProfile.cs

**Comment by maliming** [comment]
And https://docs.abp.io/en/abp/latest/Object-To-Object-Mapping

**Comment by BrianCodeman** [comment]
> The Abp framework does not have `AbpAutoMapFromAttribute`. See https://github.com/abpframework/abp/blob/dev/samples/BookStore/src/Acme.BookStore.Application/BookStoreApplicationAutoMapperProfile.cs

Thanks, you mean line 149 of the Doc [here](https://github.com/abpframework/abp/blob/bae6983eb48ffa86239c82cb66b1f1da0af403be/docs/en/Application-Services.md#L149)   is inconsistent with the framework now?

**Comment by maliming** [comment]
We need to update the documentation.
https://github.com/abpframework/abp/issues/1706

**Comment by BrianCodeman** [comment]
Well, that's clear, helpful a lot. Thank you again.
