### ISSUE TITLE
How do I use it in net core 3.1?

### ISSUE THREAD

**Issue by gudufy** [abpframework/abp#3333]
![TIM截图20200324192903](https://user-images.githubusercontent.com/117419/77420935-e68b4480-6e05-11ea-8266-9df0662f9472.png)
![TIM截图20200324192920](https://user-images.githubusercontent.com/117419/77420943-eb4ff880-6e05-11ea-93db-1ce688eb46c4.png)

**Comment by liangshiw** [comment]
Check your project, It works for netcoreapp3.1
![image](https://user-images.githubusercontent.com/16813853/77421699-3d454e00-6e07-11ea-99e6-91da63319270.png)

**Comment by gudufy** [comment]
![TIM截图20200324194320](https://user-images.githubusercontent.com/117419/77421989-bb095980-6e07-11ea-80ea-c5daf6e7eb8f.png)
My project is net core 3.1, and I used nuget to restore the same error as the present

**Comment by gudufy** [comment]
I downloaded abp.io sample project run the same error

**Comment by gudufy** [comment]
![TIM截图20200324195300](https://user-images.githubusercontent.com/117419/77422809-14be5380-6e09-11ea-90ea-14fe861921ea.png)

**Comment by liangshiw** [comment]
Share your .csproj file content
![image](https://user-images.githubusercontent.com/16813853/77423148-aa59e300-6e09-11ea-9d75-239cabae0c99.png)

**Comment by gudufy** [comment]
![TIM截图20200324195859](https://user-images.githubusercontent.com/117419/77423323-f2790580-6e09-11ea-8356-41579677042f.png)
I can use 'Abp' package.

**Comment by gudufy** [comment]
我换台电脑就可以了
