### ISSUE TITLE
Swagger generate unwanted documents API for none dependent modules

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#3335]
Hi,
I created a simple example with abp framework and in my example, I don't have any dependency on `Account Module` and `Identity Module` but swagger generates documents for these modules! why?

this is my app dependencies:

```
[DependsOn(
        typeof(AbpAutofacModule),
        typeof(AbpAutoMapperModule),
        typeof(AbpAuditLoggingEntityFrameworkCoreModule),
        typeof(AbpSettingManagementEntityFrameworkCoreModule),
        typeof(AbpAspNetCoreMvcUiBasicThemeModule),
        typeof(AbpLdapModule)
    )]
```

![3](https://user-images.githubusercontent.com/3678399/77421457-82f31e00-6de9-11ea-8c25-4c211914cd75.jpg)

sample code: 
[test.zip](https://github.com/abpframework/abp/files/4374977/test.zip)

**Comment by maliming** [comment]
Try to remove the `volo.abp.xxx` package in `AuthServer.Host.csproj`.

**Comment by mehdihadeli** [comment]
@maliming it worked thanks. why does this happen? Does it actually scan the assembly references for generating documents? 
I just config this code for swagger:

```
 context.Services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new OpenApiInfo {Title = "Identity Service API", Version = "v1"});
                options.DocInclusionPredicate((docName, description) => true);
                options.CustomSchemaIds(type => type.FullName);
            });
```

**Comment by maliming** [comment]
This belongs to how asp net core mvc finds that the controller has nothing to do with abp.

**Comment by mehdihadeli** [comment]
@maliming thanks.
