### ISSUE TITLE
Dynamic C# API Clients may not handle DateTime on QueryString when client and server cultures are different

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#3339]
Hi,

I'm encountering a issue when using dynamic c# api clients and having datetime parameters on my service dtos.

When using the swagger-UI, the following, working request is created:
`http://localhost:44344/api/app/rosterPlanning?ContractNumber=1003666-01&Begin=2019-12-01%2000%3A00%3A00&End=2019-12-31%2000%3A00%3A00`

The `DynamicHttpProxyInterceptor` creates the following request, which doesn't work:
`http://localhost:44344/api/app/rosterPlanning?ContractNumber=1003666-01&Begin=01.12.2019+00%3A00%3A00&End=31.12.2019+00%3A00%3A00`

The underlying issue is that the datetime value get's string encoded using the wrong cultureinfo.

```lang=json
{
  "code": null,
  "message": "Your request is not valid!",
  "details": "The following errors were detected during validation.\r\n - The value '31.12.2019 00:00:00' is not valid for End.\r\n - The value '01.12.2019 00:00:00' is not valid for Begin.\r\n",
  "validationErrors": [
    {
      "message": "The value '31.12.2019 00:00:00' is not valid for End.",
      "members": [
        "end"
      ]
    },
    {
      "message": "The value '01.12.2019 00:00:00' is not valid for Begin.",
      "members": [
        "begin"
      ]
    }
  ]
}
```

Example code
```lang=csharp
public interface IRosterPlanningAppService : IApplicationService
{
   Task<RosterEntryDto[]> GetAsync(ContractQueryDto query);
}

public class ContractQueryDto
{
	[Required]
	public string ContractNumber { get; set; }

	[Required]
	public DateTime Begin { get; set; }

	[Required]
	public DateTime End { get; set; }
}
```

I think this issue can be fixed in the `Volo.Abp.Http.Client.DynamicProxying.UrlBuilder.AddQueryStringParameter` method.

Is there any workaround (such as custom validation) to fix this issue?

**Comment by maliming** [comment]
hi @NecatiMeral 
Can you share the content of the http request?

eg
![image](https://user-images.githubusercontent.com/6908465/77505102-310bd000-6e9d-11ea-8201-657816d428d3.png)

**Comment by NecatiMeral** [comment]
hi @maliming,

the faulty request contains the following parameters:
```
ContractNumber=1003666-01&Begin=01.12.2019+00%3A00%3A00&End=31.12.2019+00%3A00%3A00

ContractNumber: 1003666-01
Begin: 01.12.2019 00:00:00
End: 31.12.2019 00:00:00

ContractNumber: 1003666-01
Begin: 01.12.2019+00%3A00%3A00
End: 31.12.2019+00%3A00%3A00
```

The issue is the `value.ToString()`, which is used to build the query string.
As temporary workaround, I'm using a fork of the `Volo.Abp.Http.Client`-package, where I customized the following method:

**Volo.Abp.Http.Client.DynamicProxying.UrlBuilder**
```csharp
private static void AddQueryStringParameter(StringBuilder urlBuilder, bool isFirstParam, string name, object value)
{
	urlBuilder.Append(isFirstParam ? "?" : "&");
	// NM@24.03.2020: HACK to make datetime-query parameter work independent from the clients culture
	if (value is DateTime dateTime)
	{
		urlBuilder.Append(name + "=" + System.Net.WebUtility.UrlEncode(dateTime.ToString("yyyy-MM-ddTHH:mm:ssZ")));
	}
	else
	{
		urlBuilder.Append(name + "=" + System.Net.WebUtility.UrlEncode(value.ToString()));
	}
}
```

**Comment by maliming** [comment]
hi @NecatiMeral 
This is actually related to the current culture. I am researching whether the culture of `QueryStringValueProviderFactory `should be changed.
https://github.com/aspnet/Mvc/issues/5335

**Comment by NecatiMeral** [comment]
The server-side implementation expects a invariant-culture input.
Wouldn't it be simply enough to convert the parameters using the invariant culture?

I think this issue will occur on floating values (0.00 vs 0,00) too.

**Comment by maliming** [comment]
@hikalkan  Should we change the default behavior of `QueryStringValueProviderFactory`?

https://github.com/dotnet/aspnetcore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/ModelBinding/QueryStringValueProviderFactory.cs#L30

**Comment by NecatiMeral** [comment]
I don't think that we have to adjust anything on the `QueryStringValueProviderFactory`. The client should create the url-parameters culture independent, which is currently not the case. **I think the server-side mustn't be changed at all.**

I can submit a PR adressing this issue by making my hack (https://github.com/abpframework/abp/issues/3339#issuecomment-603761777) more production ready.

**Comment by hikalkan** [comment]
>The client should create the url-parameters culture independent, which is currently not the case

I agree, and also your solution seems good :) I will check & fix it. Thanks.
