### ISSUE TITLE
Upgrade to the lastest abp versions

### ISSUE THREAD

**Issue by luisp88** [abpframework/abp#3342]
I downloaded a new startup template project (2.2.1) with angular. Now that 2.3.0 have been released, what do I need to do to have all the new features/fixes from API and FRONT?
I guess this (https://docs.abp.io/en/abp/latest/CLI#update) is a shortcut from updating each csproj nugets pkgs... what else?

**Comment by maliming** [comment]
hi 
For c # you just need to upgrade the package. Of course pay attention to some breaking changes. This information can be found in the release. https://github.com/abpframework/abp/releases

@mehmet-erim  Is there any upgrade guide for angular?

**Comment by mehmet-erim** [comment]
There is no guide for Angular but it's very easy to update. You can manually update the ABP versions in `package.json` and run the `yarn` command, or you can run in the `angular` folder;

```bash
abp update --npm
```
or

```bash
npx npm-check-updates "/^@(abp|volo).*$/" -u
```
