### ISSUE TITLE
Micro Service Admin Portal Log In - Username and Password

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3343]
What's the username and password for log in to the back end portal ?

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo#authentication-identityserver-client-configuration

**Comment by dicksonkimeu** [comment]
Am still not able to log in to back end portal.

**Comment by maliming** [comment]
hi dicksonkimeu
Please follow the steps in the documentation.  
**Step by step**
https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo

**Comment by dicksonkimeu** [comment]
Have followed the instructions.

All services are running well and migrations run. Public site also running .

My issues i can't log in to either public site or back end admin portal.
What should i do?

**Comment by maliming** [comment]
Please check the application's log for the reason or error that the login failed.

**Comment by dicksonkimeu** [comment]
Public website logs, same for back end.

![image](https://user-images.githubusercontent.com/4476822/77528621-56014280-6e9f-11ea-828d-7d3bcbafc010.png)

**Comment by dicksonkimeu** [comment]
Am running the demo without changing any configurations.

**Comment by xyfy** [comment]
you should see the log in auth-server
