### ISSUE TITLE
Why the GuidGenerator in class Volo.Abp.Application.Services.ApplicationService don't from GetRequiredService

### ISSUE THREAD

**Issue by carsonlaw** [abpframework/abp#3346]
The Code:
```
        protected ApplicationService()
        {
            GuidGenerator = SimpleGuidGenerator.Instance;
        }
```
If my class:

`class SomeAppService : CrudAppService<***`

If GuidGenerator is always SimpleGuidGenerator?

**Comment by maliming** [comment]
Property injection will replace `SimpleGuidGenerator`.

https://docs.abp.io/en/abp/latest/Dependency-Injection#property-injection
