### ISSUE TITLE
Create docs for using ConcurrencyStamp

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3351]
I've searched the docs and samples and I can't see examples of using the ConcurrencyStamp field in Dto's etc.

Would it be possible to mention it somewhere in the docs and/or sample projects to help new users? The sample application doesn't throw any concurrency errors so it's not clear that they should be included in the GET, PUT, PATCH requests that people create.

**Comment by liangshiw** [comment]
I think the documentation of ef core is clear enough  https://docs.microsoft.com/en-us/ef/core/saving/concurrency

**Comment by olicooper** [comment]
I guess it would detail how abp are handling it.

Even something short like "we have an IConcurrecy interface. To use it, please include 'ConcurrencyStamp' on your dtos when updating records. Please refer to Microsoft docs for more information."

**Comment by liangshiw** [comment]
I don't think it's necessary, developers should understand the libraries they are using.  and don't put concurrency mark on dtos. Because optimistic locking is a feature provided by ef core, it should be used in entities.

**Comment by olicooper** [comment]
Okay fair enough. When I was saying about the dto's I wasn't talking about the concurrency attribute, but passing the property through to users in the dto's:
```csharp
public class MyDto
{
    public string ConcurrencyStamp { get; set; }
}
```

**Comment by yeahe83** [comment]
Since ConcurrencyStamp is frequently used in edit methods, why not add some default logic for it at the application layer.

**Comment by hikalkan** [comment]
Already done: https://docs.abp.io/en/abp/latest/Concurrency-Check
