### ISSUE TITLE
Micro Service Demo API Entity Names

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3353]
How can i make the auto generated API's user friendly ? Below names are too long and not friendly for API.

Volo.Abp.Application.Dtos.PagedResultDto`1[[ProductManagement.ProductDto, ProductManagement.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

**Comment by maliming** [comment]
> Below names are too long and not friendly for API.
> Volo.Abp.Application.Dtos.PagedResultDto`1[[ProductManagement.ProductDto, ProductManagement.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

Can you explain the problem in detail?

**Comment by dicksonkimeu** [comment]
It's a question of how the API looks like. How can I make them user friendly especially to 3rd parties?
