### ISSUE TITLE
Why Volo.Abp.IdentityServer.EntityFrameworkCore is netcoreapp3.1

### ISSUE THREAD

**Issue by hubo0831** [abpframework/abp#3354]
My EntityFrameworkCore(netstandard2.1)  projects can't refer it.

**Comment by maliming** [comment]
I don't know why the identity server module is missing.
https://github.com/abpframework/abp/pull/2683

**Comment by maliming** [comment]
Because `IdentityServer4  `is not compatible with `netstandard2.0`

https://github.com/IdentityServer/IdentityServer4/issues/4080#issuecomment-585057809
https://www.nuget.org/packages/IdentityServer4
