### ISSUE TITLE
Owned Entity Type problem

### ISSUE THREAD

**Issue by sdly602** [abpframework/abp#3357]
abp 2.3.0

owned entity type can not be loaded.

- step 1.  define entities 

>     public class TestEntityA : Entity<Guid>
>     {
>         public TestEntityA(Guid id) : base(id) { }
>         public ICollection<TestEntityB> BList { get; set; }=new List<TestEntityB>();
>         public OwnedEntity Owned { get; set; }
>     }
> 
>     public class TestEntityB : Entity<Guid>
>     {
>         public TestEntityB(Guid id) : base(id) { }
>         public Guid TestEntityAId { get; set; }
>     }
> 
>     public class OwnedEntity
>     {
>         public string Name { get; set; }
>     }
- step 2. configure entity

>     builder.Entity<TestEntityA>(b =>
>     {
>          b.ToTable("TableA", null);
>          b.HasMany(x => x.BList).WithOne().HasForeignKey(x => x.TestEntityAId);
>          b.OwnsOne(x => x.Owned);
>      });
> 
>      builder.Entity<TestEntityB>(b =>
>      {
>           b.ToTable("TableB", null);
>           b.HasOne<TestEntityA>().WithMany().HasForeignKey(x => x.TestEntityAId);
>       });

- setp 3. test

>     public class OwnedDebuTests : OwnedDebugDomainTestBase
>     {
>         private readonly IRepository<TestEntityA, Guid> _repoA;
>         private readonly IRepository<TestEntityB, Guid> _repoB;
> 
>         public OwnedDebuTests()
>         {
>             _repoA = GetRequiredService<IRepository<TestEntityA, Guid>>();
>             _repoB = GetRequiredService<IRepository<TestEntityB, Guid>>();
>         }
> 
>         [Fact]
>         public async Task Should_Get_Owned_Property()
>         {
> 
>             var aId = Guid.NewGuid();
>             var entityA = new TestEntityA(aId) { Owned = new OwnedEntity { Name = "name" } };
>             await _repoA.InsertAsync(entityA, true);
> 
>             //return true;
>             (await _repoA.GetAsync(aId)).Owned.Name.ShouldBe("name");
>             
>             var aId2 = Guid.NewGuid();
>             var bId = Guid.NewGuid();
>             //create two entities,  type of TestEntityA and TestEntityB
>             var entityA2 = new TestEntityA(aId2) { Owned = new OwnedEntity { Name = "name" } };
>             var entityB = new TestEntityB(bId);
>             //add entityB to navigation collection of entityA ,then insert entityA
>             entityA2.BList.Add(entityB);
>             await _repoA.InsertAsync(entityA2, true);
> 
>             //throw NullReferenceException ,Owned is null
>             (await _repoA.GetAsync(aId2)).Owned.Name.ShouldBe("name");
> 
>         }
>     }
> 
Is this a  EF Core Bug or ABP ?

**Comment by maliming** [comment]
Have you tried the above code works in EF Core(without abp)?

**Comment by sdly602** [comment]
I have tried the above code works in EF Core without abp.  It's ok.

>            var options = new DbContextOptionsBuilder<MyDbContext>()
>                 .UseInMemoryDatabase(databaseName: "testDB")
>                 .Options;
>             var context = new MyDbContext(options);
>             var aId = Guid.NewGuid();
>             var bId = Guid.NewGuid();
> 
>             var a = new EntityA() { Id = aId ,Owned=new OwnedEntity {Name="name"} };
>             var b = new EntityB { Id = bId };
>             a.BList.Add(b);
> 
>             context.Add(a);
>             context.SaveChanges();
> 
>             var aFromDb = context.Set<EntityA>().First();
> 
>             Assert.NotNull(aFromDb.Owned);
>             Assert.True(aFromDb.Owned.Name == "name");

**Comment by maliming** [comment]
Is the id correct?

![image](https://user-images.githubusercontent.com/6908465/77602464-894bdc00-6f48-11ea-90a3-f1d4ac8e2302.png)

**Comment by Huangzc88** [comment]
I have the same problem.
This problem arises when I update the project's abp vnext package from 1.1.2 via the abp update command to the latest stable version 2.3.0：
![image](https://user-images.githubusercontent.com/31158857/77620503-78fe2600-6f75-11ea-9ce8-299634bd7285.png)
 ![image](https://user-images.githubusercontent.com/31158857/77620518-82878e00-6f75-11ea-8859-1e5fbba1d555.png)

I checked Microsoft's official documents and this error occurred only when the ef.core version below 3.0 was updated to version 3.0, but back in abp vnext 1.1.2, the ef.core version of the project was 3.1.

I also suspect there is a problem with the ef fluent api configuration, but I can't actually find out where the configuration is wrong.
![image](https://user-images.githubusercontent.com/31158857/77620893-4ef93380-6f76-11ea-9104-63498cf1c281.png)
![image](https://user-images.githubusercontent.com/31158857/77620905-57516e80-6f76-11ea-86a7-192ed1ef6d2b.png)
![image](https://user-images.githubusercontent.com/31158857/77620938-6801e480-6f76-11ea-8b1c-0b4c6329acfd.png)

**Comment by maliming** [comment]
@Huangzc88  see https://github.com/abpframework/abp/issues/2640

**Comment by Huangzc88** [comment]
@maliming Thank you very much,it works!!

**Comment by sdly602** [comment]
![image](https://user-images.githubusercontent.com/11803547/77625464-95529080-6f7e-11ea-8ea1-6bc94c0beb29.png)
The problem is value object.  if use that a new value object then the problem are resolved.

![image](https://user-images.githubusercontent.com/11803547/77626033-a5b73b00-6f7f-11ea-87f5-2cf36e4171c7.png)

**Comment by maliming** [comment]
hi @sdly602 Can you use cli to create a project that reproduces the problem?

**Comment by sdly602** [comment]
OK, I'll email you

**Comment by maliming** [comment]
You can share it on github.

**Comment by sdly602** [comment]
test project:  [https://github.com/sdly602/OwnedEntityDebug.git](url)

**Comment by maliming** [comment]
@sdly602 

Steps to reproduce?

**Comment by sdly602** [comment]
yes

**Comment by maliming** [comment]
The following code also gives an error when adding migrations.

You can ask in the EF Core community.

We will also consider adding `AbpOwnedAttribute `or an empty interface to mark Owned entities.

```c#
public class ApplicationDbContext : IdentityDbContext
{
	public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
		: base(options)
	{
	}

	public DbSet<Order> Orders { get; set; }

	public DbSet<Cargo> Cargos { get; set; }

	protected override void OnModelCreating(ModelBuilder builder)
	{
		base.OnModelCreating(builder);

		builder.Owned<Address>();

		builder.Entity<Order>(b =>
		{
			b.OwnsOne(x => x.InvoiceAddress);
			b.HasMany(x => x.Cargoes).WithOne();
		});

		builder.Entity<Cargo>(b =>
		{
			b.OwnsOne(x => x.ConsigeeAddress);
		});
	}
}

public class Order
{
	public Guid Id { get; set; }

	public ICollection<Cargo> Cargoes { get; set; }

	public virtual Address InvoiceAddress { get; set; }
}

public class Cargo
{
	public Guid Id { get; set; }

	public virtual Address ConsigeeAddress { get; set; }

	public Guid OrderId { get; set; }
}

public class Address
{
	public string City { get; set; }

	public string Street { get; set; }
}
```

`builder.Owned<Address>();`
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationshipDiscoveryConvention.ProcessNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnNavigationRemoved(IConventionEntityTypeBuilder sourceEntityTypeBuilder, IConventionEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo)

```

**Comment by sdly602** [comment]
@maliming Thank you very much.
