### ISSUE TITLE
ISSUE: Overridden User Interface doesn't work when published

### ISSUE THREAD

**Issue by SoloHam** [abpframework/abp#3358]
I've added Pages/Account Folder in my application where I've changed the default UI and when I run it from VS 2019 it works just fine but when I publish to IIS it loads the default page.

This is the customized page at Pages/Account/Login.cshtml:

```
@page "/Login"
@using Volo.Abp.Account.Settings
@using Volo.Abp.Settings
@inherits Volo.Abp.Account.Web.Pages.Account.AccountPage
@model CERP.Web.Pages.Account.CustomLoginModel
@inject Volo.Abp.Settings.ISettingProvider SettingProvider

@{
    ViewData["Title"] = "Log In";
}

<h1 class="m-t-0 m-b-5 text-center">@ViewData["Title"]</h1>

@if (Model.EnableLocalLogin)
{
    <div class="card m-t-3 shadow-sm rounded">
        <div class="card-body p-t-15">
            @*@if (await SettingProvider.IsTrueAsync(AccountSettingNames.IsSelfRegistrationEnabled))
            {
                <strong>
                    @L["AreYouANewUser"]
                    <a href="@Url.Page("./Register", new {returnUrl = Model.ReturnUrl, returnUrlHash = Model.ReturnUrlHash})" class="text-decoration-none">@L["Register"]</a>
                </strong>
            }*@
            <form method="post" class="m-t-10">
                <input asp-for="ReturnUrl" />
                <input asp-for="ReturnUrlHash" />
                <div class="form-group">
                    <label asp-for="LoginInput.UserNameOrEmailAddress"></label>
                    <input asp-for="LoginInput.UserNameOrEmailAddress" class="form-control" />
                    <span asp-validation-for="LoginInput.UserNameOrEmailAddress" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LoginInput.Password"></label>
                    <input asp-for="LoginInput.Password" class="form-control" />
                    <span asp-validation-for="LoginInput.Password" class="text-danger"></span>
                </div>
                @*<div class="form-check">
                        <label asp-for="LoginInput.RememberMe" class="form-check-label">
                            <input asp-for="LoginInput.RememberMe" class="form-check-input" />
                            @Html.DisplayNameFor(m => m.LoginInput.RememberMe)
                        </label>
                    </div>*@
                <div class="form-group">
                    <label class="custom-control custom-control-info custom-checkbox active" asp-for="LoginInput.RememberMe">
                        <input class="custom-control-input" style="display:none; visibility:hidden" type="checkbox" visible="false" name="mode" checked="checked" asp-for="LoginInput.RememberMe">
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-label" style="z-index:-1">@Html.DisplayNameFor(m => m.LoginInput.RememberMe)</span>
                    </label>
                </div>
                <abp-button type="submit" button-type="Primary" name="Action" value="Login" class="btn btn-info btn-block">@L["Login"]</abp-button>
            </form>
        </div>
    </div>
}

@if (Model.VisibleExternalProviders.Any())
{
    <div class="col-md-6">
        <h4>@L["UseAnotherServiceToLogIn"]</h4>
        <form asp-page="./Login" asp-page-handler="ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl" asp-route-returnUrlHash="@Model.ReturnUrlHash" method="post">
            <input asp-for="ReturnUrl" />
            <input asp-for="ReturnUrlHash" />
            @foreach (var provider in Model.VisibleExternalProviders)
            {
                <button type="submit" class="btn btn-primary" name="provider" value="@provider.AuthenticationScheme" title="@L["GivenTenantIsNotAvailable", provider.DisplayName]">@provider.DisplayName</button>
            }
        </form>
    </div>
}

@if (!Model.EnableLocalLogin && !Model.VisibleExternalProviders.Any())
{
    <div class="alert alert-warning">
        <strong>@L["InvalidLoginRequest"]</strong>
        @L["ThereAreNoLoginSchemesConfiguredForThisClient"]
    </div>
}
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
```

And the corresponding Model: Pages/Account/Login.cshtml.cs:

```
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Account.Settings;
using Volo.Abp.Account.Web;
using Volo.Abp.Account.Web.Pages.Account;
using Volo.Abp.Auditing;
using Volo.Abp.Identity;
using Volo.Abp.Security.Claims;
using Volo.Abp.Settings;
using Volo.Abp.Uow;
using Volo.Abp.Validation;
using IdentityUser = Volo.Abp.Identity.IdentityUser;

namespace CERP.Web.Pages.Account
{
    [AllowAnonymous]
    public class CustomLoginModel : LoginModel
    {
        public CustomLoginModel(IAuthenticationSchemeProvider schemeProvider, IOptions<AbpAccountOptions> accountOptions) : base(schemeProvider, accountOptions)
        {
        }
    }
}
```

This is how the Startup.cs is setup:
```
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplication<ABPDefaultAppWebModule>();
            services.AddRazorPages()
                .AddRazorRuntimeCompilation()
                .AddRazorPagesOptions(options =>
                {
                   

                    //options.Conventions.AddPageRoute("/index", "{*url}");
                })
                .AddNewtonsoftJson(options =>
                {
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                });

            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.Name = "cerpCs";
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromMinutes(100);

                options.AccessDeniedPath = "/AccessDenied";
                options.LoginPath = "/Login";
                options.LogoutPath = "/Logout";

                options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
                options.SlidingExpiration = true;
            });
        }

        public void Configure(IApplicationBuilder app)
        {
            app.InitializeApplication();
        }
    }
```
Kindly look into this.

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#overriding-a-page-model-c

https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#overriding-a-razor-page-cshtml

> Overriding a .cshtml file (razor page, razor view, view component... etc.) is possible through the Virtual File System.

> Virtual File system allows us to embed resources into assemblies. In this way, pre-built modules define the razor pages inside their NuGet packages. When you depend a module, you can override any file added to the virtual file system by that module, including pages/views.

**Comment by SoloHam** [comment]
I've done just that. Followed the tutorial from a new abp project. works fine on IIS Express locally but when I deploy to IIS it still goes to the default abp login page.

**Comment by maliming** [comment]
Can you share a project that reproduces the problem? You can create it using cli.

**Comment by SoloHam** [comment]
Yes, I'm using the CLI Version 2.3.0 [stable channel] with ASP.NET Core 3.1.2 on VS 2019

https://www.mediafire.com/file/7oqjjvzcneug58l/ABPDefaultApp.rar/file

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/3358#issuecomment-604176166

As I mentioned above and also mentioned in the documentation, I don't see your module configuration for VirtualFileSystem. 

You can change the environment of your application to **production** while debugging it locally.

https://docs.abp.io/en/abp/latest/Virtual-File-System

**Comment by SoloHam** [comment]
> Volo.Abp.VirtualFileSystem is the core package of the virtual file system. Install it in your project using the package manager console (PMC)  ✔

> Then you can add AbpVirtualFileSystemModule dependency to your module ✔

`[DependsOn(
        typeof(ABPDefaultAppHttpApiModule),
        typeof(ABPDefaultAppApplicationModule),
        typeof(ABPDefaultAppEntityFrameworkCoreDbMigrationsModule),
        typeof(AbpAutofacModule),
        typeof(AbpIdentityWebModule),
        typeof(AbpAccountWebIdentityServerModule),
        typeof(AbpAspNetCoreMvcUiBasicThemeModule),
        typeof(AbpAspNetCoreAuthenticationJwtBearerModule),
        typeof(AbpTenantManagementWebModule),
        typeof(AbpAspNetCoreSerilogModule),
        typeof(AbpVirtualFileSystemModule)
        )]
    public class ABPDefaultAppWebModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.PreConfigure<AbpMvcDataAnnotationsLocalizationOptions>(options =>
            {
                options.AddAssemblyResource(
                    typeof(ABPDefaultAppResource),
                    typeof(ABPDefaultAppDomainModule).Assembly,
                    typeof(ABPDefaultAppDomainSharedModule).Assembly,
                    typeof(ABPDefaultAppApplicationModule).Assembly,
                    typeof(ABPDefaultAppApplicationContractsModule).Assembly,
                    typeof(ABPDefaultAppWebModule).Assembly
                );
            });
            Configure<AbpVirtualFileSystemOptions>(options =>
            {
                //Register all embedded files of this assembly to the virtual file system
                options.FileSets.AddEmbedded<ABPDefaultAppWebModule>("ABPDefaultApp");
            });
        }
....
}`

> A file should be first marked as an embedded resource to embed the file into the assembly. ✔

![Capture](https://user-images.githubusercontent.com/8042978/77603295-85608f80-6f31-11ea-8783-42b2487e8242.PNG)

> Then the module needs to be configured using AbpVirtualFileSystemOptions to register the embedded files to the virtual file system ✔

`
`[DependsOn(
        typeof(ABPDefaultAppHttpApiModule),
        typeof(ABPDefaultAppApplicationModule),
        typeof(ABPDefaultAppEntityFrameworkCoreDbMigrationsModule),
        typeof(AbpAutofacModule),
        typeof(AbpIdentityWebModule),
        typeof(AbpAccountWebIdentityServerModule),
        typeof(AbpAspNetCoreMvcUiBasicThemeModule),
        typeof(AbpAspNetCoreAuthenticationJwtBearerModule),
        typeof(AbpTenantManagementWebModule),
        typeof(AbpAspNetCoreSerilogModule),
        typeof(AbpVirtualFileSystemModule)
        )]
    public class ABPDefaultAppWebModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.PreConfigure<AbpMvcDataAnnotationsLocalizationOptions>(options =>
            {
                options.AddAssemblyResource(
                    typeof(ABPDefaultAppResource),
                    typeof(ABPDefaultAppDomainModule).Assembly,
                    typeof(ABPDefaultAppDomainSharedModule).Assembly,
                    typeof(ABPDefaultAppApplicationModule).Assembly,
                    typeof(ABPDefaultAppApplicationContractsModule).Assembly,
                    typeof(ABPDefaultAppWebModule).Assembly
                );
            });
            Configure<AbpVirtualFileSystemOptions>(options =>
            {
                //Register all embedded files of this assembly to the virtual file system
                options.FileSets.AddEmbedded<ABPDefaultAppWebModule>("ABPDefaultApp");
            });
        }
....
}`

> The Virtual Files Middleware is used to serve embedded (js, css, image...) files to clients/browsers just like physical files in the wwwroot folder. Add it just after the static file middleware as shown below:  ✔

`
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            var hostingEnvironment = context.Services.GetHostingEnvironment();
            var configuration = context.Services.GetConfiguration();

            ConfigureUrls(configuration);
            ConfigureAuthentication(context, configuration);
            ConfigureAutoMapper();
            ConfigureVirtualFileSystem(hostingEnvironment);
            ConfigureLocalizationServices();
            ConfigureNavigationServices();
            ConfigureAutoApiControllers();
            ConfigureSwaggerServices(context.Services);
        }
`

I'm obviously missing something here or doing it wrong totally but What is it? Could you please clarify the mistake or update the Project above with the working code and I'll look it up. Thanks.

**Comment by maliming** [comment]
https://github.com/maliming/LoginPageDemo

https://github.com/maliming/LoginPageDemo/blob/master/src/LoginPageDemo.Web/LoginPageDemo.Web.csproj#L35

https://github.com/maliming/LoginPageDemo/blob/master/src/LoginPageDemo.Web/LoginPageDemoWebModule.cs#L118

**Comment by SoloHam** [comment]
Thanks a lot.
