### ISSUE TITLE
Building Volo.Abp.AspNetCore.HealthChecks

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#336]
Given that ABP vNext focused on microservices, I recommend using the Services [Microsoft.AspNetCore.HealthChecks](https://github.com/dotnet-architecture/HealthChecks) Library in ABP framework that is an important component of MicroServices architecture.
ASP.NET Core 2.2 has a plan for built in health checks.
[Microsoft Docs - Health monitoring](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/monitor-app-health)

**Comment by hikalkan** [comment]
It's replaced by https://github.com/aspnet/Diagnostics

**Comment by hitaspdotnet** [comment]
@hikalkan [BeatPulse](https://github.com/Xabaril/BeatPulse) project now supports the new Health Checks API and all the existing features is work with the new Microsoft Health Checks abstractions [AspNetCore.Diagnostics.HealthChecks](https://github.com/aspnet/Diagnostics/tree/master/src/Microsoft.AspNetCore.Diagnostics.HealthChecks).

**Comment by hikalkan** [comment]
Thanks @hitaspdotnet for the suggestion.

**Comment by brunobertechini** [comment]
I would also consider an agnostic approach if possible...We might want to use other tools like Nagios, Zabbix, New Relic, Zxse for synthetics and health checks for Loadbalancers

**Comment by aididhaiqal** [comment]
Hi,

Are we getting this feature anytime soon?

**Comment by NecatiMeral** [comment]
Upvote 👍🏼

**Comment by hikalkan** [comment]
We are not interested in building this. You can use health check in your project, no need to create an ABP specific health check system at that point.
