### ISSUE TITLE
How to implement GetPagedListAsync use case smoothly in Repository and AppService?

### ISSUE THREAD

**Issue by BrianCodeman** [abpframework/abp#3364]
Hi team,
I am considering to implement a `GetPagedListAsync` method in the `AppServive` and return a `PagedResultDto<SomeEntityDto>`, which involves using repository.

The thing is, according to **DDD**, the repository is only responsive to provide business entities, but should not know any thing like paging logic, and that should be the responsibility of `AppService`, so I either need to return an `IQueryable<SomeEntity>` from My inherited `CustomerRepository` (from `EfCoreRepository`), or directly use the base method `GetListAsync()` to pull all entities from the data source into memory at first place, and then to page them.

The first way of using `IQueryable`, which is not recommended according to the **abp official doc**, even harder to render the data asynchronously, since I have to reference `EntityFrameworkCore` package from `AppService` to use the `ToListAsync()` method at the end of repository return, and I believe that package is an unnecessary pollution to `AppServive`. 

But the second way, is also weird when I think about it. Is it pragmatic to realize a method of pulling all items out of the data source like the default `GetListAsync()` method of `EfCoreRepository` did? What if I have (and commonly most of the businesses) millions of items in the database? Maybe I will never need such a method in any use case.

But I do believe the developer team have best choices in design.  The problem is I could not find a elegant way to do this, maybe due to my poor understanding of the framework. So could you guide me about this issue of implementing a `GetPagedListAsync`-like service correctly?

**Comment by maliming** [comment]
> the repository is only responsive to provide business entities, but should not know any thing like paging logic

https://github.com/abpframework/abp/blob/9e31797766f1f8686fd37862fcebe6d1b5e1f204/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IIDentityClaimTypeRepository.cs#L20

**Comment by BrianCodeman** [comment]
> > the repository is only responsive to provide business entities, but should not know any thing like paging logic
> 
> https://github.com/abpframework/abp/blob/9e31797766f1f8686fd37862fcebe6d1b5e1f204/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IIDentityClaimTypeRepository.cs#L20

Thanks a lot, does that mean you recommend me implement the paging from inside the repository? Isn't that a little invading to the repository? And, If convenient of course, could you please give a hint about the purpose of design a full pulling method of `GetListAsync` which directly return a (maybe 
surprisingly huge) `List<TEntity>`?

**Comment by maliming** [comment]
> does that mean you recommend me implement the paging from inside the repository?

Yes.

> Isn't that a little invading to the repository? 

I think the `GetPagedListAsync` method of the repository does not contain business logic. So it is appropriate.

> And, If convenient of course, could you please give a hint about the purpose of design a full pulling method of GetListAsync which directly return a (maybe
surprisingly huge) List<TEntity>?

Because some entities may not be a large list. For a large number of lists, this is why a paging method is needed.

**Comment by BrianCodeman** [comment]
> > does that mean you recommend me implement the paging from inside the repository?
> 
> Yes.
> 
> > Isn't that a little invading to the repository?
> 
> I think the `GetPagedListAsync` method of the repository does not contain business logic. So it is appropriate.
> 
> > And, If convenient of course, could you please give a hint about the purpose of design a full pulling method of GetListAsync which directly return a (maybe
> > surprisingly huge) List?
> 
> Because some entities may not be a large list. For a large number of lists, this is why a paging method is needed.

It's clear. You are so considerable, Thanks for helping us newbies.
