### ISSUE TITLE
Does hangfire currently support setting IsJobExecutionEnabled as false to disable background jobs?

### ISSUE THREAD

**Issue by Huangzc88** [abpframework/abp#3365]
Does hangfire currently support setting IsJobExecutionEnabled as false to disable background jobs? 
I use hangfire, but I need to disable background jobs in the development environment, how should I do that?

**Comment by maliming** [comment]
Yes, `IsJobExecutionEnabled `of `AbpBackgroundJobOptions `can control whether it is enabled.

You can enable or disable it depending on the environment.

**Comment by Huangzc88** [comment]
At abp 1.1.2, I tested that setting this didn't work for hangfire, and then looked at the source code
![image](https://user-images.githubusercontent.com/31158857/77625442-879d0b00-6f7e-11ea-9e94-f12d7fda9cb9.png)
This is the source code to see today, it seems to have not been updated. 
I will update to abp 2.3.0 to test whether it works again, thank you

**Comment by liangshiw** [comment]
Hangfire currently doesn't support  `IsJobExecutionEnabled ` and Quartz also.  I will try implement it.
