### ISSUE TITLE
bundleRelativePath does not take into consideration a virtual directory deployment

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#3368]
I am using the latest version of Abp 2.3.0
I have published the IdentityServer.Host project and I am deploying it as a virtual directory and it seems the bundles do not take into consideration the virtual directory, it keeps looking for the bundles directly under the main site.

Is there a way around that?

**Comment by maliming** [comment]
Hi 

Can you share some code to explain the problem?

**Comment by ZouZou** [comment]
Hi,

It's not a certain code, I published the IdentityServer as a virtual directory and found out that it keeps looking for the __bundles under directly the main site.
After checking the Abp framework source code, I found that they are using a variable called "bundleRelativePath" however there is no way to inform this variable to actually start relatively to my virtual directory.

I don't know if I am ranting here but the main question is can I deploy the IdentityServer as a virtual directory?

**Comment by maliming** [comment]
I remember that asp net core does not support IIS virtual directories, but I will see if we can configure this path.

**Comment by ZouZou** [comment]
Thank you.
If it does not then please just inform me so I can reconfigure my deployment.

**Comment by maliming** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#virtual-directories

**Comment by ZouZou** [comment]
Thank you very much for your help.
