### ISSUE TITLE
Ajax events in abp javascript library

### ISSUE THREAD

**Issue by atak946** [abpframework/abp#3370]
Hello,

I'm using abp javascript library for micro services but i can't handle error or fail event for ajax request.

only have done function.

if request gets failed all javascript code crashing. "Uncaught TypeError: Cannot read property 'constructor' of undefined"

https://imgur.com/J7BzzXk

can anyone help me for this issue?

thank you.

**Comment by maliming** [comment]
How to reproduce your problem?

**Comment by atak946** [comment]
> How to reproduce your problem?
@maliming 

didn't understand, can you explain in more detail?

**Comment by maliming** [comment]
> if request gets failed all javascript code crashing. "Uncaught TypeError: Cannot read property 'constructor' of undefined"

Can you give an example to reproduce the problem?

**Comment by atak946** [comment]
sayacAyarServisi = Project namespace
meterType = app service name, table name

`
sayacAyarServisi.meterType.get({}).done(function(r){console.log(r)});
`
error:
![image](https://user-images.githubusercontent.com/16645386/77650936-1c9f0480-6f7d-11ea-95cb-226ceec3fac2.png)

if request response is 200, i can handle with done function

but i can't handle for this case (error, exception).

i need this for example: namespace.serviceName.`get({}).fail or error or danger`

i need this completed example
`
sayacAyarServisi.meterType.get({}).error(function(r){console.log(r)});
`

but abp doesn't have any fail, danger, error promise function.

**Comment by atak946** [comment]
@hikalkan @yekalkan i need help for this issue, can you help me ?

**Comment by atak946** [comment]
@maliming do you have any idea about this problem?

**Comment by maliming** [comment]
Ajax promise callbacks:  .done(), .fail(), .always(), and .then()`.

```
sayacAyarServisi.meterType.get({}).fail(function(r){console.log(r)});
```

**Comment by atak946** [comment]
> Ajax promise callbacks: ` .done(), .fail(), .always(), and .then()`.
> 
> ```
> sayacAyarServisi.meterType.get({}).fail(function(r){console.log(r)});
> ```
> 
> https://api.jquery.com/category/deferred-object/
@maliming 

yes i know jquery but not working with abp, can you try?

**Comment by maliming** [comment]
About `abp.ajax` please check its source code.

![image](https://user-images.githubusercontent.com/6908465/77914608-c279a880-72c8-11ea-96ef-30c971018976.png)


https://github.com/abpframework/abp/blob/02f5f1562567e16b317f81815500819843fb82e6/npm/packs/jquery/src/abp.jquery.js#L100-L113

**Comment by atak946** [comment]
![2020-03-30 16_31_26-DevTools - localhost_44396_Index](https://user-images.githubusercontent.com/16645386/77918062-0c03cc80-72a4-11ea-902f-13a06bc5b36a.png)

@maliming Okey, i understand now.

abp.sweetalert plugin is missing in my code..

thank you for help.
