### ISSUE TITLE
How to integreted with IdentityServer4.Quickstart.UI? or abp have identityui it self?

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#3378]
I have been build an api with identity.
i want to manage identity info,claims,clients etc with ui.
https://github.com/IdentityServer/IdentityServer4.Quickstart.UI
![image](https://user-images.githubusercontent.com/1214546/77719876-5c1f2c80-7021-11ea-8c09-58f77abddaf5.png)

**Comment by NecatiMeral** [comment]
ABP offers a commercial identity server UI module [here](https://commercial.abp.io/modules/Volo.Identityserver.Ui).

You can, of course, write your own UI.
