### ISSUE TITLE
(@abp/ng.core) PatchRouteByName should deeply modify new url path

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#3379]
@mehmet-erim
Here is my `PatchRouteByName ` usage:
```typescript
        var oldRoute=configStateService.getRoute(null,'AbpUiNavigation::Menu:Administration');
        store.dispatch(new PatchRouteByName(
            'AbpUiNavigation::Menu:Administration',
            {
                path: 'administrator',
                iconClass: 'fa fa-wrench',
                children:oldRoute.children
            }
        ));
```
I wish to all url in `AbpUiNavigation::Menu:Administration` be modified like below but didn't:
`/identity/roles`=>`administrator/identity/roles`
`/identity/users`=>`administrator/identity/user`
`/tenant-management/tenants`=>`administrator/tenant-management/tenants`
...
After check code in [`patchRouteDeep`,](https://github.com/abpframework/abp/blob/c4c4cfadccc27dadac817b9d0e96a0df4f6c0cc6/npm/ng-packs/packages/core/src/lib/states/config.state.ts#L311) it doesn't seem to modify url deeply
``` typescript
      newValue.url = `${parentUrl}/${(!newValue.path && newValue.path === ''
        ? route.path
        : newValue.path) || ''}`;

      if (newValue.children && newValue.children.length) {
        newValue.children = newValue.children.map(child => ({
          ...child,
          url: `${newValue.url}/${child.path}`.replace('//', '/'),
        }));
      }

      return { ...route, ...newValue };
```
Is it modify all url of children deeply or not?
May I try to fix it?

**Comment by mehmet-erim** [comment]
Hi @yinchang0626 

Route structure might be changed in the future. We discuss the routes should be defined in the backend.

`patchRouteDeep` can't do this. For now, I suggest you patch all routes that you need.
If we'll decide we can use the same structure, I can enhance the `patchRouteDeep`  function to update all routes deeply.

**Comment by bnymncoskuner** [comment]
This is not valid anymore.
