### ISSUE TITLE
How to seed Entities/Aggregates with private setters?

### ISSUE THREAD

**Issue by BrianCodeman** [abpframework/abp#3394]
Hi team,
I am implementing an `IDataSeeder` in the Migration project, just like the tutorial did here [https://github.com/abpframework/abp/blob/29bbb7560e98591723595533f01ed79caca498f4/docs/en/Tutorials/Part-1.md](https://github.com/abpframework/abp/blob/29bbb7560e98591723595533f01ed79caca498f4/docs/en/Tutorials/Part-1.md). The thing is, my aggregate do have dozens of properties which all have private setters. It's **DDD** practice pattern of course. In an `AppService`, The complex mapping thing has delegated to **AutoMapper**. But in a Migration project, it has no clue of **DTO**s from Application.Contracts project, Dose that means I have to call all the aggregate methods to set properties for each seed Entity, or I should reference Application.Contracts project and use **AutoMapper** directly?

As has mentioned above, there is another not-so-related, but still **confusing** question about **AutoMapper**. If it can map DTO to a domain entity and overlook all its private setters (Yes it did even I didn't provide a constructor to initialize those properties, but all the properties were set successfully after map), what's the meaning of using private setters? The domain entities/aggregates will lose protection since **DTO** validation only check **data integration** instead of **business rationality**

Hope to get your guidance.
Thanks.

**Comment by gdlcf88** [comment]
> I am implementing an IDataSeeder in the Migration project

Do you mean `IDataSeedContributor`?

**Comment by gdlcf88** [comment]
> The thing is, my aggregate do have dozens of properties which all have private setters.

No matter how many properties an entity has, you should create it using a public constructor.

Refer to:
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUser.cs#L30-L35

> But in a Migration project, it has no clue of DTOs from Application.Contracts project

Why you create an entity in the "Migration project"? Just achieve your purpose like the `IdentityServerDataSeedContributor.cs` in Domain project.

**Comment by BrianCodeman** [comment]
> > I am implementing an IDataSeeder in the Migration project
> 
> Do you mean `IDataSeedContributor`?

No, the (app) template v2.3.0 injects `IDataSeeder` to `XxxDbMigrationService` of Domain project and been called in `MigrateAsync()`, not `IDataSeedContributor`, though they are identical.

**Comment by BrianCodeman** [comment]
> No matter how many properties an entity has, you should create it using a public constructor.

Well in theory that's true, but such a big constructor is too ugly to use, and that's not the point. What I concern is the correct seed pattern of using AutoMapper, and the problem of AutoMapper invading private properties.

> Why you create an entity in the "Migration project"? 

Thank you for your solution of moving seeder class into Domain project, although I reckon this way is a little improper since seeding should be kind of Migration logic but Domain's responsibility. Anyway, it's convenient to use.
