### ISSUE TITLE
Get current user's culture in appservice

### ISSUE THREAD

**Issue by luisp88** [abpframework/abp#3397]
I plan to have one table with lists (columns) of translated country names. I am wondering if I could get the users culture in my appservice so I can select and return the proper list (entity column). Abp app services have something done for this or do I need to get it from http request?

**Comment by liangshiw** [comment]
May you need https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?view=netcore-3.1
