### ISSUE TITLE
There are no login schemes configured for this client.

### ISSUE THREAD

**Issue by saintpoida** [abpframework/abp#3400]
Hi guys,

Have been reading through and setting up the microservices demo (i didnt have any dependencies installed originally like elasticsearch etc so it took a little while to get everything running). 

However i now have all the services running but i cant seem to login to the AuthServer.Host project as an initial testing point with account 'admin'. I am not even 100% sure what the default password but believe it is supposed to be '123qwe'? But i have also tried 'qwe123' and '1q2w3e*'.

The wierdest error im getting is 'Invalid username or password!' but in addition below that error im getting 'Invalid login request There are no login schemes configured for this client.' and im not exactly sure how to deal with that issue. I have checked the logs for AuthServer.Host and it doesnt seem to really be logging much about the failed login so for now im just hoping its an incorrect password?

I have built several projects with AspnetZero so im not particularly new to ABP but am to the seperated services, can you guys advise on what i can look at to find out the issue and advise the default admin password.

Thanks,
Pete

**Comment by maliming** [comment]
> default admin password.
```
admin
1q2w3E*
```

> The wierdest error im getting is 'Invalid username or password!' but in addition below that error im getting 'Invalid login request There are no login schemes configured for this client.' 


This error message appears only if the following happens: 
https://github.com/abpframework/abp/blob/02c1b02b810c8bcbf458a4d78a320177e5836ebc/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml#L63

This may be a problem, I will check it.
