### ISSUE TITLE
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.StudentsControllerProxy

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3409]
I created an ABP module based project.

I added a new entity/ service implementations. 

Am using UnifiedWeb project to host the module. I can run it, log in and see the API (/swagger).

When i try to execute any on my custom entities i get this error.

_Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.StudentsControllerProxy_

**Comment by maliming** [comment]
hi

Please share some code.

**Comment by zhchlmm** [comment]
I'm also have this problem when i installed a third party module .

Please look at this:
#https://github.com/EasyAbp/CacheManagement/issues/8 

Thanks.

**Comment by maliming** [comment]
@zhchlmm We only discuss the modules provided by Abp.

**Comment by dicksonkimeu** [comment]
Worked.

**Comment by PooriaShariatzadeh** [comment]
I have the same problem can you please explain how to resolve it

**Comment by PooriaShariatzadeh** [comment]
> Worked.

I have the same problem can you please explain how to resolve it
