### ISSUE TITLE
how to trigger migration when tenant added!

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#3412]
I know that database migration is triggered when adding tenants! but when db migration is in another microservice,It will be invalid. What should I do!?

**Comment by maliming** [comment]
> I know that database migration is triggered when adding tenants!

I remember now that we can only migrate manually, Can't migrate the database at runtime. 

`Migrate the database at runtime` feature has been planned to improve, maybe v2.5.

https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations

**Comment by SmallShrimp** [comment]
I mean DataSeeder !

**Comment by hikalkan** [comment]
In a microservice world, each service should care about its own data seed. They can register to new tenant created distributed event and seed their data.
