### ISSUE TITLE
Can a pure Blazor project consume HttpApiClient without becoming an abp module?

### ISSUE THREAD

**Issue by BrianCodeman** [abpframework/abp#3413]
I have noticed that the template HttpApiClient  test console project builds itself as an abp module. Does that mean if I want to consume Dynamic C# API Clients from a separated Blazor project, I should first install abp packages and make it an abp module too? Could I keep the Blazor client native and consume the convenient HttpApiClient functions? And if possible, how to achieve that?

Thanks for notice this issue.

**Comment by maliming** [comment]
No, Abp is a module system and requires a bootstrapper to start the module. Just like using Abp in a console application.

https://github.com/abpframework/abp/blob/dev/samples/BasicConsoleApplication/AbpConsoleDemo/AppHostedService.cs#L13

**Comment by BrianCodeman** [comment]
> No, Abp is a module system and requires a bootstrapper to start the module. Just like using Abp in a console application.
> 
> https://github.com/abpframework/abp/blob/dev/samples/BasicConsoleApplication/AbpConsoleDemo/AppHostedService.cs#L13

Thanks you for conform.

Well maybe it's not a big problem to Blazor Server side since all dependencies run on the server, but  it's another thing to WebAssembly, client has to download too much things. So I think for the latter, it's better to use native HttpClient instead.

Or, maybe the team could consider to provide a module independent HttpApiClient service which could be injected to any dotnet core program without been coupled to the framework. Anyway, I think Abp is an excellent RESTful DDD implementation, and should let wider kinds of client to consume easily.

**Comment by maliming** [comment]
> Or, maybe the team could consider to provide a module independent HttpApiClient service which could be injected to any dotnet core program without been coupled to the framework. 

hi @BrianCodeman 

Abp is open source,  So you can change its code into independent components without depend on the module system, etc. : )

**Comment by BrianCodeman** [comment]
> > Or, maybe the team could consider to provide a module independent HttpApiClient service which could be injected to any dotnet core program without been coupled to the framework.
> 
> hi @BrianCodeman
> 
> Abp is open source, So you can change its code into independent components without depend on the module system, etc. : )

I see it a huge challenge to my coding skill, but sincerely thank for your encourage. I will try to do study that.
