### ISSUE TITLE
Make a stress / load testing for ABP Framework

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#3414]
**Test Tool:** jMeter (https://jmeter.apache.org/)

**Steps:**

1. Create an empty **MVC + EF Core** ABP template with the CLI command 
```
abp new Acme.BookStore
```

2. Implement CRUD actions.
     2.1. Create `Book` entity.
     ....2.1.1. Properties: `Id<Guid>`, `Name<string>`, `PageSize <int>`, `PublishDate <DateTime>`
    2.2- Create `BooksController` and implement 4 CRUD actions in this controller:
    ....2.3.1. `Task<BookDto> InsertAsync(<BookDto> dto)`
    ....2.3.2. `Task<BookDto> UpdateAsync(<BookDto> dto)`
    ....2.3.3. `Task<BookDto> GetAsync(<Guid> id)`
    ....2.3.4. `Task DeleteAsync(<Guid> id)`
    ....2.3.5. `Task<string> GetConstant()` (return constant "Test" string without DB transaction)
 
3. Run the project with CTRL+F5 and make a load test with jMeter.
   3.1. 2500 requests per controller action with 50 parallel request.
   3.2. Order of action executions: `InsertAsync`, `UpdateAsync`, `GetAsync`, `DeleteAsync`, `GetConstant`

4. Write jMeter test results to this table

| Action      | Request Count | Concurrent Action | Sent (KB/sec)  | Received (KB/sec) | Error rate (%) | Average duration per request | {add other results supplied by jMeter...} |
|-------------|---------------|-------------------|----------------|-------------------|----------------|------------------------------|-----------------------------------------------|
| InsertAsync | 2500          | 50                |                |                   |                |                              |                                               |
| UpdateAsync | 2500          | 50                |                |                   |                |                              |                                               |
| GetAsync    | 2500          | 50                |                |                   |                |                              |                                               |
| DeleteAsync | 2500          | 50                |                |                   |                |                              |                                               |
| GetConstant | 2500          | 50                |                |                   |                |                              |                                               |

5. Clear the existing database or use another database.

6. Create an empty **MVC** project from Microsoft MVC template with the command

```
dotnet new mvc -n Acme.BookStore
```

   ....6.1 Add `EF Core` database provider and configure it.
   ....6.2. Do the same steps from **2** to **4** for this project.

---

As a reference, here's the AspNet Boilerplate test issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2444

**Comment by hikalkan** [comment]
Closing since @AkinSabriCam did it, but waiting my fine tune: https://github.com/abpframework/abp/issues/3663
