### ISSUE TITLE
Localization help

### ISSUE THREAD

**Issue by LiljebergXYZ** [abpframework/abp#3417]
Hi

Is it possible to localize say the AbpAccount module only in my application without creating a PR to this repo? I need this as I don't intend to localize everything at this time and need it for a preview

**Comment by maliming** [comment]
hi 

Have you read the documentation of localization?
https://docs.abp.io/en/abp/latest/Localization

**Comment by LiljebergXYZ** [comment]
Yes I did read that document, but that doesn't really explain how to translate the AbpAccount namespace or such

**Comment by maliming** [comment]
But I can't reproduce your problem.

**Comment by maliming** [comment]
Can you explain your problem in detail?

**Comment by LiljebergXYZ** [comment]
Well the login page is currently only available in certain languages in the angular template, where it appears to be using the `AbpAccount` namespace for translations. I don't seem to have access to edit these templates and as a result they are in English, while the rest of the application is in Swedish (Except for once again, Abp namespace translations).

I want to somehow be able to translate these parts of the frontend as well

**Comment by luisp88** [comment]
You could extend these localization resources

             options.Resources
                    .Add<FichaMedicaResource>("es")
                    .AddBaseTypes(typeof(AbpValidationResource))
                    .AddVirtualJson("/Localization/FichaMedica");
                //se extienden otros LocalizationResources en nuestro mismo localization
                options.Resources
                    .Get<IdentityResource>() //AbpIdentity
                    .AddVirtualJson("/Localization/FichaMedica");
                options.Resources
                    .Get<AbpTenantManagementResource>() //AbpTenantManagement
                    .AddVirtualJson("/Localization/FichaMedica");`
Add your own languages in YouProjectHttpApiHostModule
`                options.Languages.Add(new LanguageInfo("es", "es", "Español"));`
The override tags in your own resource

> // Override de AbpIdentity
    "Permission:IdentityManagement": "Usuarios y roles",
    "Permission:RoleManagement": "Roles",
    "Permission:Create": "Crear",
    "Permission:Edit": "Editar",
    "Permission:Delete": "Eliminar",
    "Permission:ChangePermissions": "Cambiar permisos",
    "Permission:UserManagement": "Usuarios",

**Comment by LiljebergXYZ** [comment]
Thanks for the help, that solved my issue!

**Comment by LiljebergXYZ** [comment]
Hmm actually I can't seem to override the AccountResource as it seems to be assigned later in the cycle. Why is that?

**Comment by LiljebergXYZ** [comment]
I solved it as I remembered how the structure worked. I added the `AbpAccountApplicationContractsModule` as a dependency and now it works.
