### ISSUE TITLE
Issue with Quartz job persistence

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3422]
I've been working on job persistence with the new Quartz jobs and there seems to be an issue with it.

Example:
```csharp
public class DataArchiveJob : QuartzBackgroundWorkerBase, ISingletonDependency
{
    public DataArchiveJob()
    {
        JobDetail = JobBuilder.Create<DataArchiveJob>()
            .WithIdentity($"{nameof(DataArchiveJob)}")
            .Build();

        Trigger = TriggerBuilder.Create()
            .WithIdentity($"{nameof(DataArchiveJob)}")
            .WithCronSchedule("0 30 1/6 ? * * *")
            .StartNow().Build();
    }
}
```

The code above create a job that runs every 6 hours. The job is inserted in the database when running the application for the first time, but when it is run for a seconds time I receive an exception about a duplicate job: 
> Quartz.JobPersistenceException: 'Couldn't store job: Unable to store Job: 'DEFAULT.DataArchiveJob', because one already exists with this identification.'

I believe we need a check in the job factory to ensure jobs aren't created twice or they are deleted and re-added? I'm not sure how you'd handle changes to the job trigger, job detail or the JobDataMap? I've seen this as an example: https://stackoverflow.com/a/51724460

If any more information is needed just let me know.

**Comment by liangshiw** [comment]
I will check this

**Comment by olicooper** [comment]
Thanks for the quick update! I have a question...

When I do a go-live, the in-memory jobs are deleted and re-added after the application is restarted which causes the scheduled job to be missed until the next time determined by the CronExpression. I want to use the persistent job store to ensure this doesn't happen.

For example, if I have a job that runs once a day at 18:00 (`0 0 18 ? * * *`) and I do a go-live around this time, the job will normally be missed and the next one will be scheduled for tomorrow rather than the one that was missed at 18:00. 

Will your code make sure that missed jobs are still executed as soon as they can, even if the application is restarted?
