### ISSUE TITLE
how to set authtoken in RemoteService?

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#3423]
my operation:
1. install package `Volo.Abp.Http.Client.IdentityModel.Web` and `Volo.Abp.AspNetCore.Mvc.Client` in host project
2. depend modules `AbpAspNetCoreMvcClientModule`  and `AbpHttpClientIdentityModelWebModule` in host project
3. add json config in host project:
```json
"IdentityClients": {
    "Default": {
      "GrantType": "client_credentials",
      "ClientId": "xxx",
      "ClientSecret": "xxx*",
      "Authority": "xxx",
      "Scope": "AuthServer",
      "RequireHttps": false
    }
  },
  "AuthServer": {
    "Authority": "xxx",
    "ApiName": "AuthServer"
  },
  "RemoteServices": {
    "Default": {
      "BaseUrl": "xxx"
    },
    "AbpMvcClient": {
      "BaseUrl": "xxx"
    }
  }
```
**but i get response `Authorization failed! Given policy has not granted:xxx`**
**remark: The remotely authorized token does not have user information**

**Comment by maliming** [comment]
I remember `Client Credentials` couldn't get user information. Because it does not require user involvement.

**Comment by SmallShrimp** [comment]
I found the code:
```c#
if (context.RemoteService.GetUseCurrentAccessToken() != false)
            {
                var accessToken = await GetAccessTokenFromHttpContextOrNullAsync();
                if (accessToken != null)
                {
                    context.Request.SetBearerToken(accessToken);
                    return;
                }
            }
```
I do not set  `UseCurrentAccessToken` ,it should run 
```c#
protected virtual async Task<string> GetAccessTokenFromHttpContextOrNullAsync()
        {
            var httpContext = HttpContextAccessor?.HttpContext;
            if (httpContext == null)
            {
                return null;
            }

            return await httpContext.GetTokenAsync("access_token");
        }
```
Did I get it right?
But it doesn't seem to get tokens through access_token!
I'm listening for HTTP,I found that it still got the token remotely over HTTP.
![image](https://user-images.githubusercontent.com/8120385/77990180-49736300-7353-11ea-8f06-67909eeddc7c.png)

**Comment by SmallShrimp** [comment]
Am I missing anything

**Comment by maliming** [comment]
hi

>but i get response Authorization failed! Given policy has not granted:xxx

Have you set permissions for client with grant type `client_credentials`?

https://github.com/abpframework/abp/blob/dev/templates/module/aspnet-core/host/MyCompanyName.MyProjectName.IdentityServer/IdentityServer/IdentityServerDataSeedContributor.cs#L143

**Comment by SmallShrimp** [comment]
I've set the permissions for the user.I want to use currentUser's token to set http request!But there is no

**Comment by maliming** [comment]
Like i said above `client_credentials `grant type has no user information, you can try `password `grant type.

**Comment by SmallShrimp** [comment]
I can't authorize using the user who is currently logged in.My request is from the front end.So I should pass my authorization information to the authorization center!
I don't know if I can express myself clearly

**Comment by SmallShrimp** [comment]
I got the problem:
source code:
```c#
protected virtual async Task<string> GetAccessTokenFromHttpContextOrNullAsync()
        {
            var httpContext = HttpContextAccessor?.HttpContext;
            if (httpContext == null)
            {
                return null;
            }

            return await httpContext.GetTokenAsync("access_token");
        }
```
Correct code：
```c#
 protected virtual async Task<string> GetAccessTokenFromHttpContextOrNullAsync()
        {
            var httpContext = HttpContextAccessor?.HttpContext;
            if (httpContext == null)
            {
                return null;
            }

            return await httpContext.GetTokenAsync("Bearer", "access_token");
        }
```
is a bug?

**Comment by maliming** [comment]
hi I will check. : )

**Comment by maliming** [comment]
I think there is no problem with the code.

https://github.com/dotnet/aspnetcore/blob/87a92e52c8b4bb7cb75ff78d53d641b1d34f8775/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L149

**Comment by SmallShrimp** [comment]
ok！
But I used my method to solve my problem！this is my code:
```
httpContext.GetTokenAsync("Bearer", "access_token");
```
I used 'Bearer' as schema and i got the token !
I still think that's the reason:
 https://github.com/dotnet/aspnetcore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Authentication.Abstractions/src/TokenExtensions.cs#L157

**Comment by dicksonkimeu** [comment]
I need to connect my android app to the API, how can i generate token ? according to identity server documentation, the url is below. I doesn't seem to work on the API.

```
/connect/token
https://identitymodel.readthedocs.io/en/latest/client/token.html 
```

**Comment by maliming** [comment]
@dicksonkimeu 
You need to make sure your project is using modules and middleware for Identity Server.

**Comment by dicksonkimeu** [comment]
Noted.

Thank you.
