### ISSUE TITLE
Response Message on API

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3437]
Am getting below message, how can i control the message text to a more friendly error ? in the log file i have actual message, how can expose the same to this response ?

_{
  "error": {
    "code": "PM:000001",
    "message": "An internal error occurred during your request!",
    "details": null,
    "validationErrors": null
  }
}_

LogFile

2020-04-01 11:59:28.819 +03:00 [WRN] A product with code string already exists!

**Comment by maliming** [comment]
hi

Have you checked the documentation?

https://docs.abp.io/en/abp/latest/Exception-Handling

**Comment by dicksonkimeu** [comment]
Thank you.
