### ISSUE TITLE
can add an overload to PermissionGroupDefinition.AddPermission?

### ISSUE THREAD

**Issue by fmpfmp** [abpframework/abp#3440]
can add an overload method to PermissionGroupDefinition.AddPermission  and PermissionDefinition.AddChild with string parameter of displayName? if my system not need Localizable。

**Comment by maliming** [comment]
I think this is impossible.

**Comment by hikalkan** [comment]
Pass a `FixedLocalizableString` object which is not a localized string that implements `ILocalizableString`. Example: `new FixedLocalizableString("My value")`.
