### ISSUE TITLE
When publish HttpApi to IIS, Cannot show Administration menu after login with admin

### ISSUE THREAD

**Issue by yaoru** [abpframework/abp#3441]
I create a application by angular template with no tiered, and deploy HttpApi.Host to the IIS on the server. Then I call the Api from the iis in vs code, and can't show Administration and admin menu after login with admin. However, I run HttpApi.Host in vs2019 ，and then call then API in vs code,after i login with admin，Administration and admin menu can show .......
![1](https://user-images.githubusercontent.com/16953219/78139506-2ced2e80-7418-11ea-8ef1-ea4202344cb1.png)
![2](https://user-images.githubusercontent.com/16953219/78139514-2f4f8880-7418-11ea-954c-944b6cd1304b.png)

**Comment by maliming** [comment]
Are there any messages in the browser's console and application's logs?

**Comment by yaoru** [comment]
No any error message in the browser's console, and there are any error messages in application's logs，pleae see the below . 
[logs.txt](https://github.com/abpframework/abp/files/4418246/logs.txt)

I  try copy some code for permission verification from Volo.Abp.Identity module like this：
` var hasRolePermission = await authorizationService.IsGrantedAsync(IdentityPermissions.Roles.Default);
            var hasUserPermission = await authorizationService.IsGrantedAsync(IdentityPermissions.Users.Default);`
and debug in VS2019：
when call HttpApi.host in IIS，hasRolePermission  and hasUserPermission are all false.
when call HttpApi.host in VS2019, hasRolePermission  and hasUserPermission are all true.

**Comment by maliming** [comment]
It may be that your `appsettings.json` settings are wrong, you can debug the application using the `Production` environment in VS2019.

**Comment by yaoru** [comment]
Yes,it is wrong in server's `appsettings.json`,the authority URL is set to localhost, just change it to the IP of the server ，then it work normally.
Thanks for your help,I will close this issue.
