### ISSUE TITLE
Localization fails on console application

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#3442]
Hi,

I'm working on a console application which I wanted to localize, using the same approach as described in the docs:
![grafik](https://user-images.githubusercontent.com/7882753/78141984-95460b00-742c-11ea-9c8e-b7f3ed507226.png)

When trying to access a localized string using `L["MyString"]` inside a application service, I'm getting the following exception:
![grafik](https://user-images.githubusercontent.com/7882753/78141924-78a9d300-742c-11ea-98ef-793f6346dfc2.png)

I followed the docs and cannot find a configuration issue here. The json files are properly configured as embedded resources:
![grafik](https://user-images.githubusercontent.com/7882753/78142410-3339d580-742d-11ea-9797-7005d6971a05.png)

**Comment by olicooper** [comment]
Does your project `.csproj` file include a reference to the embedded resource?
Look for something like this:
```xml
<ItemGroup>
  <EmbeddedResource Include="Localization\DPToolImport\*.json" />
</ItemGroup>
```

**Comment by NecatiMeral** [comment]
hi,

I've configured the project as described in the docs:
**.Domain.Shared.csproj**
![grafik](https://user-images.githubusercontent.com/7882753/78143108-194cc280-742e-11ea-9d3c-d937549565c5.png)

**Comment by olicooper** [comment]
If you are running in development mode, do you also have something similar to this in your startup project (.Web / .HttpApi module) for the `DomainSharedModule`? Everything else looks okay from your screenshots.
https://github.com/abpframework/abp/blob/2d55f3aabc314d8c01d791cbc005066cb68259a9/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Host/MyProjectNameHttpApiHostModule.cs#L62-L76

**Comment by NecatiMeral** [comment]
Hi @olicooper,

thanks for your help, but I haven't set up the `ReplaceEmbeddedByPhysical` stuff since I don't need to change my localization files during debugging.

**Comment by liangshiw** [comment]
Hi @NecatiMeral ,
I made an example, hope I can help you. https://github.com/liangshiw/LocalizationDemo

**Comment by NecatiMeral** [comment]
Hi @liangshiw,

thanks for providing an example. I'll take a look ASAP and give feedback.
