### ISSUE TITLE
How to create a shared ETO class inheriting EtoBase?

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#3450]
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/Distributed/EtoBase.cs

It seems that I cannot create a new ETO class inheriting EtoBase, because the EtoBase class is in Volo.Abp.Ddd.Domain which is not in the dependencies of MyProject.Domain.Shared.

So how to create a shared ETO class inheriting EtoBase?
Or maybe the question is: is it necessary to inherit EtoBase?

**Comment by cotur** [comment]
It is not necessary to inherit EtoBase.
There is an example Eto in IdentityServer: https://github.com/abpframework/abp/blob/dev/modules/identityserver/src/Volo.Abp.IdentityServer.Domain.Shared/Volo/Abp/IdentityServer/ApiResources/ApiResourceEto.cs

**Comment by gdlcf88** [comment]
OK, thank you. 😀
