### ISSUE TITLE
Rename Identity Server Tables

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3455]
How can i rename all this tables ?

![image](https://user-images.githubusercontent.com/4476822/78308592-89a03480-7551-11ea-86ea-43083f1bf95b.png)

**Comment by dicksonkimeu** [comment]
For identity server there is a guide here, but am not sure how it can be applied to a ABP project.

**Comment by maliming** [comment]
Please try searching before asking questions. : )
https://github.com/abpframework/abp/issues?q=Table+prefix

**Comment by dicksonkimeu** [comment]
Thank you sir.
