### ISSUE TITLE
IsDeleted Error (Cannot insert the value NULL into column 'IsDeleted')

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3456]
Everything works fine when am using AuditedAggregateRoot , but when i switch to FullAuditedAggregateRoot i get error IsDeleted cannot be null. I thought abp takes care of this.

Note: Am not using default CRUD services. 

Have even tried to set IsDeleted manually, but still i get error.

![image](https://user-images.githubusercontent.com/4476822/78308919-6de95e00-7552-11ea-9155-73bd90d2db3f.png)

![image](https://user-images.githubusercontent.com/4476822/78309084-c587c980-7552-11ea-862e-daf6281cedcf.png)

**Comment by maliming** [comment]
What database are you using?

**Comment by dicksonkimeu** [comment]
MS SQL

**Comment by maliming** [comment]
Can you share a project that reproduces the problem?

**Comment by dicksonkimeu** [comment]
It's a huge project, I have created a new two entity project and using crud services it works well. Let me look into sql profiling, unless you have any other idea on where I can check the failure point.

**Comment by SoloHam** [comment]
You might want to look in your [ProjectName]DbContextModelCreatingExtensions.cs to make sure you're configuring your entity properly. It should have ConfigureAuditedAggregateRoot() and also try adding ConfigureSoftDelete() as well. Add a migration and update the DB.

**Comment by maliming** [comment]
`ConfigureByConvention()` configures the standard/base properties (like TenantId) and recommended to always call it.

**Comment by dicksonkimeu** [comment]
@maliming @SoloHam worked like charm. thank you soo much.
