### ISSUE TITLE
How do I stop/replace data seeder?

### ISSUE THREAD

**Issue by aklscv** [abpframework/abp#3459]
How do I stop current data seeders from the existing modules?

I don't want any admin users to be seeded on my database when running the dbmigrator but the [IdentityDataSeedContributor](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeedContributor.cs) runs and seeds it every time.

**Comment by maliming** [comment]
You can try to remove IdentityDataSeedContributor in AbpDataSeedOptions.

**Comment by aklscv** [comment]
That worked thanks!

```csharp
Configure<AbpDataSeedOptions>(options =>
{
   options.Contributors.Remove<IdentityDataSeedContributor>();
});
```
