### ISSUE TITLE
source link broken

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#3462]
only afew package contains source link.
![image](https://user-images.githubusercontent.com/1214546/78325581-9d2bb980-75aa-11ea-8beb-bb4a4ccea43b.png)

![image](https://user-images.githubusercontent.com/1214546/78325788-44a8ec00-75ab-11ea-9551-b4f0f94c3c2c.png)

but i can debug setp into core dll
![image](https://user-images.githubusercontent.com/1214546/78327099-a3bc3000-75ae-11ea-9d04-2991ce66e542.png)

and i can not setp into app dll.eg:CheckGetListPolicyAsync funciton and ApplySorting function
![image](https://user-images.githubusercontent.com/1214546/78327062-88e9bb80-75ae-11ea-9d95-46cc7277de64.png)

**Comment by maliming** [comment]
`SourceLink.Create.CommandLine` doesn't seem to work in net core 3.x anymore.

**Comment by maliming** [comment]
Waiting..
https://github.com/shiftkey/dotnetcore-sourcelink-test-bug
https://github.com/shiftkey/dotnetcore-sourcelink-test-bug/issues/1

**Comment by KevinBassaDevelopment** [comment]
Any update on this issue? Beeing able to debug the abp packages is really essential.

**Comment by maliming** [comment]
hi, @KevinBassaDevelopment  This problem is related to the .net core, we are waiting for the above issue.

https://github.com/shiftkey/dotnetcore-sourcelink-test-bug
shiftkey/dotnetcore-sourcelink-test-bug#1

**Comment by windsOne** [comment]
@maliming please quick ,very thanks

**Comment by maliming** [comment]
There is nothing I can do except waiting. https://github.com/abpframework/abp/issues/3462#issuecomment-671848281

**Comment by yanxiaodi** [comment]
Just leave a workaround if you have the below issue:
If you are using Azure DevOps pipeline to build abp applications, you may see the error:
```
##[error]/home/vsts/.nuget/packages/sourcelink.create.commandline/2.8.3/build/SourceLink.Create.CommandLine.targets(30,5): Error : unable to convert OriginUrl: https://xxxx

```
FYI: https://support.abp.io/QA/Questions/60/Azure-Devops-Build-Pipeline-SourceLinkCreateCommandLine-Error
You can edit the **common.props** file in your solution folder and delete the reference to the **SourceLink.Create.CommandLine** package then the pipeline can work correctly.

**Comment by Enissay** [comment]
`/root/.nuget/packages/sourcelink.create.commandline/2.8.3/build/SourceLink.Create.CommandLine.targets(30,5): error : unable to convert OriginUrl: https://gitlab-ci-token:....`
The same issue we face when trying to build a nuget package. @yanxiaodi workaround solves the issue. I wonder if there's any premanent fix!

**Comment by sevenNightL** [comment]
> There is nothing I can do except waiting. [#3462 (comment)](https://github.com/abpframework/abp/issues/3462#issuecomment-671848281)

fixed this problem at now?

**Comment by maliming** [comment]
@sevenNightL 
See https://github.com/abpframework/abp/issues/6702
