### ISSUE TITLE
Razor Pages on API

### ISSUE THREAD

**Issue by aklscv** [abpframework/abp#3464]
I created a new project using --ui none. When exploring the .Host project I found out that if I navigate to /account/login it displays a login page:

![image](https://user-images.githubusercontent.com/63085156/78326621-76389d80-7540-11ea-9b13-3de03d17e041.png)

Is there a way to remove this and the others? (register etc...)

I create a project with no UI so I can use my own SPA and handle all the front-end there. I don't want my users to find this url and suddenly login/create accounts using it.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/3441

**Comment by aklscv** [comment]
@maliming I don't see how that is related to my problem. As a matter of fact is the opposite situation. I don't want those pages to show at all. My users should use my SPA to interact with my database not find out about the API url and find these pages.

**Comment by maliming** [comment]
hi @aklscv

Maybe related: https://github.com/abpframework/abp/issues/3434

**Comment by aklscv** [comment]
@maliming Thanks! I saw [this commit](https://github.com/abpframework/abp/commit/b38c7ebc3cb2c66a1c07840fa4883184527014d9) and it worked. However, I can't do the same for the [Register](https://github.com/abpframework/abp/blob/237a35306089132380b9a94d745e45d65463fbef/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Register.cshtml.cs#L34) page because it returns a ``Task`` instead of ``Task<IActionResult>``. Maybe it should be changed to return ``IActionResult`` too.

**Comment by maliming** [comment]
hi @aklscv 

Please follow: https://github.com/abpframework/abp/issues/3495
