### ISSUE TITLE
MongoDB module ACID transaction implementation

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#347]
MongoDB 4.0 supports ACID transactions. MongoDB 4.2 supports distributed ACID transactions too!

**Comment by maliming** [comment]
After trying it was unsuccessful. https://github.com/abpframework/abp/commit/7c145bc2e20ea2880e08ea46e6cde6a64cd710c1


1.Mongo2Go has problems with transaction support.
https://github.com/Mongo2Go/Mongo2Go/issues/89

2. The database needs to be configured to use transactions.
> In version 4.0, MongoDB supports multi-document transactions on replica sets.
> In version 4.2, MongoDB introduces distributed transactions, which adds support for multi-document transactions on sharded clusters and incorporates the existing support for multi-document transactions on replica sets.
