### ISSUE TITLE
UserFriendlyException is not being sent to the client

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#3471]
I am using the latest version of ABP 2.3.0

In my appservice I am throwing a UserFriendlyException
> throw new UserFriendlyException("Error: Car not found!");> 

On the swagger side I am getting the below 
> {
  "error": {
    "code": null,
    "message": "An internal error occurred during your request!",
    "details": null,
    "validationErrors": null
  }
}
> 

And in the log it keeps saying 
> Request was short circuited at exception filter 'Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter'
> 

Anyone has any idea why this is happening? please this is urgent for me.

**Comment by ZouZou** [comment]
I forgot to mention that my appservice is being called from the controller

**Comment by maliming** [comment]
hi
Please share the application's full error log.

**Comment by ZouZou** [comment]
Hi,

After debugging my problem I just found out that the error with my reference it should have been Volo.Abp and not Volo.UI.

However I have a class that inherits from the BusinessException and I don't get the errors back at the client's side, I will share its code here.

`/// <summary>
    /// This exception type is directly shown to the user.
    /// </summary>
    /// <typeparam name="T">Type of message to be structured</typeparam>
    [Serializable]
    public class CustomUserFriendlyException: BusinessException
    {
        static string _parsedMessage;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="message">Exception message</param>
        public CustomUserFriendlyException(string message) : base(parseMessage(message))
        {

        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="code">Error code</param>
        /// <param name="message">Exception message</param>
        public CustomUserFriendlyException(int code, string message) : base(parseCode(message).ToString(), _parsedMessage)
        {

        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="code">Error code</param>
        /// <param name="message">Exception message</param>
        /// <param name="withInternalReference">Add Internal Reference to the exception</param>
        public CustomUserFriendlyException(int code, string message, Boolean withInternalReference) : base(parseMessage(message, withInternalReference))
        {

        }

        private static int parseCode(string message)
        {
            try
            {
                ProblemDetails oException = parseException(message);
                return oException.status;
            }
            catch (Exception e)
            {
                _parsedMessage = message;
                return 500;
            }
        }
        private static string parseMessage(string message)
        {
            try
            {
                ProblemDetails oException = parseException(message);
                return _parsedMessage;
            }
            catch (Exception e)
            {
                return message;
            }
        }
        private static string parseMessage(string message, Boolean withInternalReference)
        {
            try
            {
                JObject loObject = new JObject();
                loObject.Add("error", message);
                loObject.Add("InternalReference", Guid.NewGuid());
                return loObject.ToString();
            }
            catch (Exception e)
            {
                return message;
            }
        }
        private static ProblemDetails parseException(string exception)
        {
            ProblemDetails oException = JsonConvert.DeserializeObject<ProblemDetails>(exception);
            _parsedMessage = JsonConvert.SerializeObject(oException.errors);
            if (string.IsNullOrEmpty(_parsedMessage) || (oException.status == 404) || (_parsedMessage == "null"))
            {
                _parsedMessage = oException.title;
            }
            return oException;
        }
    }`

**Comment by ZouZou** [comment]
Again it seems I was in the wrong.
All I had to do with add the following interfaces to my custom class ", IBusinessException, IUserFriendlyException"
