### ISSUE TITLE
how to get LicenseCode in microservice?

### ISSUE THREAD

**Issue by lanpin** [abpframework/abp#3474]
![image](https://user-images.githubusercontent.com/8994721/78369791-52d12980-75f8-11ea-8021-664d4beb942d.png)
I have a solution that includes many projects. as the picture shows.
I am a business user, how do I get the abplicensecode for each project?
@hikalkan

**Comment by hikalkan** [comment]
Sorry @lanpin, but this is the open source ABP Framework. Please ask to https://support.abp.io/ for ABP Commercial questions.
Thanks for your understanding.
