### ISSUE TITLE
Tenant Resolvers

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3476]
on the documentation it talks of subdomains and domain, and that works have also tested. works fine.

Will below also work?

options.AddDomainTenantResolver("{0}.oauth.mydomain.com"); second level and third level sub domain ?

Also; when using remote services (microservices - gateways too), how should i set up the IP settings since it should be based on Tenant Resolvers?

I am referring to below.

```
  "RemoteServices": {
    "Default": {
      "BaseUrl": "https://localhost:44379/"
    },
    "CORE": {
      "BaseUrl": "https://localhost:44385/"
    }
  }
```

```
"AuthServer": {
    "Authority": "https://localhost:44379/"
  }
```

**Comment by dicksonkimeu** [comment]
@maliming how should I set these settings in the JSON files in the projects? I am using the Module Starter Template with the below projects all with JSON's settings file. In production, I want to use subdomains as per below

> Identity - tenantname.identity.maindomain.com
> httpAPI - tenantname.api.maindomain.com 
> Host - tenantname.maindomain.com
> Unified - tenantname.maindomain.com

**Comment by maliming** [comment]
> options.AddDomainTenantResolver("{0}.oauth.mydomain.com"); second level and third level sub domain ?

This is no problem, domain name resolvers supports this subdomain.

Inside the gateway you can use http headers to pass the tenant id. DynamicHttpProxy  also do the same thing.

https://github.com/abpframework/abp/blob/ea928f8937c3092fec7ebc9bf53320fdeaeb87f1/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs#L219

**Comment by dicksonkimeu** [comment]
This code should be placed on which class? 

```
 //TenantId
            if (CurrentTenant.Id.HasValue)
            {
                //TODO: Use AbpAspNetCoreMultiTenancyOptions to get the key
                requestMessage.Headers.Add(TenantResolverConsts.DefaultTenantKey, CurrentTenant.Id.Value.ToString());
            }
```

**Comment by dicksonkimeu** [comment]
@maliming

**Comment by maliming** [comment]
I remember that `Authority `can only be a fixed domain name, which is why http headers are used to pass tenants.

**Comment by dicksonkimeu** [comment]
That I agree.

But where do enter such code, 
```

//TenantId
            if (CurrentTenant.Id.HasValue)
            {
                //TODO: Use AbpAspNetCoreMultiTenancyOptions to get the key
                requestMessage.Headers.Add(TenantResolverConsts.DefaultTenantKey, CurrentTenant.Id.Value.ToString());
            }
```

**Comment by maliming** [comment]
> This code should be placed on which class?

It depends on your actual situation. I just give an example. If you are using `DynamicHttpProxy `it has already done this.

**Comment by dicksonkimeu** [comment]
@maliming have noticed that I can't see my HTTP API (Dynamics Proxy Classes) when I run HttpApi.Host (localhost:44383/swagger) am using the Module Template. But when I add the controllers manually to the HttpApi Module, they appear.

I only see AbpTenant by name, by id, API definition, languages, proxy scripts and app configurations.

And that could be the reason why my tenant resolvers are not working, but I was using manually defined controllers which have removed now, but can't see generated API.

**Comment by dicksonkimeu** [comment]
@maliming have switched to DynamicHttpProxy and it worked. I was using manually defined controllers.

Thank you.
