### ISSUE TITLE
Abpio DataTable Server-Side search

### ISSUE THREAD

**Issue by NikitaUsefi** [abpframework/abp#3477]
I'm using abpio 2.2.1 and become confused on how to make searchable server-side search with data table 
I read https://github.com/abpframework/abp/issues/2756 and tutorials on https://docs.abp.io/ however I'm still not sure how to make datatable server-side searchable 
can anyone suggest a working sample ?

**Comment by maliming** [comment]
I think there are already examples. : )
https://github.com/abpframework/abp/issues/2756#issuecomment-582243266
