### ISSUE TITLE
abp with angular Ui

### ISSUE THREAD

**Issue by YoussefSalameh** [abpframework/abp#3483]
Hello guys , 
I've already create a abp.io project :
* project type : Application 
* ui framework : angular 
 and separate identity server of course was checked 

so i already use the angular project that was downloaded with my abp project and all was good till i arrived to deploy my project 
1) i published http.api.host
2) i published identityserver
3) i published my angular project 
and here was my problem when i change url in environment.ts and environment.prod.ts
tenant management and identity management disappear from my App and when i re-change url in environment.ts and environment.prod.ts to be localhost tenant management and identity management will appear .

please can anyone help me

**Comment by yaoru** [comment]
check `appsettings` on your server which you  published identityserver, see if the authority's URL is configured as localhost and try changing it to IP address

**Comment by YoussefSalameh** [comment]
already checked , appsettings is correct  @yaoru

**Comment by mehmet-erim** [comment]
Hi @YoussefSalameh,
What is your `@abp/ng.*` packages version?

It might be a cache problem. If you change the URL in the environment, you should clear the browser storages (session and local).

**Comment by YoussefSalameh** [comment]
Hi @mehmet-erim  my @abp/ng.* version is 2.3.0

After a Long Debugging I Found That The Problem Might be From Abp Because After Login The /api/abp/application-configuration It Doesn't Return Current User And His Granted Policies When It's  Related To Ip Address Not To Localhost.

Any Suggestions About it ? 

Best Regards

**Comment by mehmet-erim** [comment]
I think it is not related to the IP address. Are you logged in? Can you open the app in the incognito tab and try again or navigate to the `/account/login` page and re-login?

**Comment by YoussefSalameh** [comment]
I’ve try it but the same issue ,

 

 

Do You Think That Admin User causing  this issue ?

**Comment by YoussefSalameh** [comment]
i added the below code in home component.ts to check user and his granted policy 
currentUser = {isAuthenticated: false, id: null, tenantId: null, userName: null};
hasIdentityPermission = false 


    const hasIdentityPermission = this.config.getGrantedPolicy("AbpIdentity.Users");
    alert(hasIdentityPermission);
    const currentUser = this.config.getOne("currentUser");
    console.log(currentUser);

**Comment by DataQuestSAL** [comment]
@YoussefSalameh you probably need to share the difference between the 2 response which you are getting from the api so they can see what we are talking about

**Comment by YoussefSalameh** [comment]
Hi Everyone ,
Problem Found !!!!!!!!!!!!!!!!!!

IdentityServer And Api's Was Published Over Http So The Error Was In HttpApiHostModule And Specifically In ConfigureAuthentication Function :
" options.RequireHttpsMetadata " Was True So After Changing It To false => Administration Section
( tenant management , identity management , user management ) appears again  And Problem Was Solved .

Thank You All And Specifically @DataQuestSAL   For Helping Me To Fix This Issue

**Comment by elhanda** [comment]
hi all  i got this error when i try to publish 
here my appsettings.json
![image](https://user-images.githubusercontent.com/56455161/134472490-c381ab2a-cb56-47d3-a688-947e6ca128b3.png)

and angular here my environement
![image](https://user-images.githubusercontent.com/56455161/134472669-c144349f-c3e7-42b5-b911-3ab62f6b5834.png)

when i publish the backand in iis windows server i works fine swagger calls api 
but when i publish the frantand  and click on login button this hapen
![image](https://user-images.githubusercontent.com/56455161/134472983-e60a3506-1e49-44d5-8163-0afbc5b2824e.png)
and when i modify the url to 
https://192.168.11.101:44311/account/login
loginpage appererd but no respond 

and 
in another project i got this error (The required antiforgery header value "RequestVerificationToken" is not present)
please can anyone help me
