### ISSUE TITLE
How can I manual register service in module ?

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#3484]
Hi,

I created a Storage module with multiple providers (like LocalStorage, AmazonS3Storage, ...) but I cannot manual register one of them based on the configuration file. I tried many ways but still stuck. It's always resolve AmazonS3StorageService although I change my config in appsettings.json  to LocalStorage
How can I handle this ? 

![image](https://user-images.githubusercontent.com/46510130/78545822-a1fca180-7826-11ea-800e-c9c76093cca4.png)

![image](https://user-images.githubusercontent.com/46510130/78545886-b9d42580-7826-11ea-9e1c-ab6d126cb8f1.png)

![image](https://user-images.githubusercontent.com/46510130/78545940-d53f3080-7826-11ea-8367-70412b1be94c.png)

Thanks for your support

**Comment by gdlcf88** [comment]
You can refer to the [ABP DI document](https://docs.abp.io/en/abp/latest/Dependency-Injection).

**Comment by hitaspdotnet** [comment]
1.Don't mark your services with ABP DI interfaces if you want registering them manually. 
2.Register replaceable null or localStorage service as default for when your storage config is missed
3.Replace default with target service as you do in your code

**Comment by volethanh** [comment]
thanks all, now I can resolve this
