### ISSUE TITLE
[Question] How to extend the audit log table

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#3485]
I am trying to extend the audit log table by adding some fields to it instead of adding the values in the extraproperties field, just for the ease of querying them later.

I have created a class which inherits from AuditLogContributor, but that would only give me the option to add to the AuditLogInfo.

I am trying to see if there is a way to use the IAuditingStore in order to do so without breaking the current auditing system.

Does anyone have any idea how to do it?

**Comment by gdlcf88** [comment]
Version 2.4 has a new feature (Object Extending System) that might be able to address your needs.
The document has not been updated, you can read this PR for now: https://github.com/abpframework/abp/pull/3401
