### ISSUE TITLE
The method of razor page should return IActionResult

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#3495]
_Originally posted by @aklscv in https://github.com/abpframework/abp/issues/3464#issuecomment-609466915_

**Comment by maliming** [comment]
Includes all modules.

**Comment by maliming** [comment]
When developers want to customize some pages, such as redirect or return other types, they need `IActionResult `as the return value of `Get/Post` method.

@hikalkan What do you think?

**Comment by hikalkan** [comment]
I agree. Returning `IActionResult` gives more opportunity while overloading.
