### ISSUE TITLE
Upgrading to the latest startup template

### ISSUE THREAD

**Issue by SoloHam** [abpframework/abp#3510]
Recently v2.4.0 was released and I've got a project on v2.3.0. 

I can upgrade all the packages from NuGet PM or the ABP CLI but is there a guide to pull the changes made to the startup template or do I have to see the changes from the git repo and apply manually?

I did find an issue already (#3342) but that was referring to the packages I suppose.

**Comment by maliming** [comment]
If there are major changes to the startup template, we will explain in the release.

But we plan to provide an upgrade guide. see https://github.com/abpframework/abp/issues/1442
