### ISSUE TITLE
DistributedEventHandler with RabbitMQ

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#3512]
Hi,

I've just created a web api project to push distributed event through rabbitmq and I have a console application for consuming that event using **IDistributedEventHandler**.

I start console application project first and I saw on rabbitmq 1 consumer, it's ok. But after that, I start web project and try that API pushing event on swagger, I saw there is another consumer on rabbitmq. In this time, there are 2 consumers on rabbitmq. This make a problem that when I push about 10 messages, my consumer in console app received only 4 or 5 messages.

I tried to test the sample **RabbitMqEventBus** and it's working fine. 
I retried by create a EventHandler in App1(of project sample) and then start web project to push message again, and the issue is again.

![image](https://user-images.githubusercontent.com/46510130/78774414-d86d2480-79be-11ea-8262-1039ccf3f0ad.png)

**Comment by Loongle** [comment]
maybe your client name repetition

**Comment by hikalkan** [comment]
Did you solve the issue? Are you sure that you're using different client names and not subscribed to the same event in both applications.

**Comment by volethanh** [comment]
Ah, my fault, I'm setting the same Client name.

@hikalkan : I also have a question about DistributedEvent with rabbitmq, Is there any option to configure number of EventHandlers handle concurrently ? It's refer to PrefetchCount in rabbitmq

**Comment by hikalkan** [comment]
>Is there any option to configure number of EventHandlers handle concurrently ? It's refer to PrefetchCount in rabbitmq

How do you set it with the [RabbitMQ.Client](https://www.nuget.org/packages/RabbitMQ.Client) package?

**Comment by volethanh** [comment]
Hi @hikalkan , you can set it like `Channel.BasicQos(PrefetchSize, PrefetchCount, false);`.
And then handle the message in parallel

**Comment by hikalkan** [comment]
moved to https://github.com/abpframework/abp/issues/4012
