### ISSUE TITLE
TagHelper - Validation error is invalid!

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#3517]
When used both min & max length, the validation shows only max length validation message.

![image](https://user-images.githubusercontent.com/9526587/78779341-781db900-79a5-11ea-91db-86af4f211c23.png)

![image](https://user-images.githubusercontent.com/9526587/78779363-81a72100-79a5-11ea-9168-bb79e1f86667.png)

The correct statement should be:
**The "Name" field must be a string of minimum 5 and maximum 5.**

```
  public class BookCreateDto
    {
        [StringLength(BookConsts.NameMaxLength, MinimumLength = BookConsts.NameMinLength)]
        public string Name { get; set; }

        [Range(BookConsts.PageSizeMinLength, BookConsts.PageSizeMaxLength)]
        public int PageSize { get; set; }

        [Required]
        public bool IsPublished { get; set; }

        [Required]
        public DateTime PublishDate { get; set; }
    }
```

---

```
<form data-ajaxForm="true" asp-page="/Books/CreateModal" autocomplete="off">
    <abp-modal>
        <abp-modal-header title="@L["NewBook"].Value"></abp-modal-header>

        <abp-modal-body>
            
            <abp-input asp-for="Book.Name"/>

            <abp-input asp-for="Book.PageSize"/>

            <abp-input asp-for="Book.IsPublished"/>

            <abp-input asp-for="Book.PublishDate" type="text" class="datepicker"/>

            
        </abp-modal-body>

        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</form>

```

**Comment by yekalkan** [comment]
This is not related to tag helpers. Further more, i don't think this is related to abp framework.

@hikalkan reopen this issue if you think this is related to us.

**Comment by yekalkan** [comment]
Also, you can use **MinLength** attribute.

![image](https://user-images.githubusercontent.com/5793291/78901137-91476800-7a80-11ea-92ef-48ed8f074ff7.png)
