### ISSUE TITLE
Remote authorization problem

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#3527]
#### reproduction

1.  Create a identity server client and set permission `UserLookup`
2.  Use `UserLoopupService` get an user in microservices(Remote Reqeuest)
2.1.  The current authorization information is obtained dynamically through IdentitiClient,like this:
```
"IdentityClients": {
    "Default": {
      "GrantType": "client_credentials",
      "ClientId": "AuthServer_App",
      "ClientSecret": "1q2w3e*",
      "Authority": "http://localhost:44318",
      "Scope": "AuthServer",
      "RequireHttps": false
    }
  },
  "AuthServer": {
    "Authority": "",
    "ApiName": "AuthServer"
  },
  "RemoteServices": {
    "Default": {
      "BaseUrl": "http://localhost:44318"
    },
    "AbpMvcClient": {
      "BaseUrl": "http://localhost:44318"
    },
    "AbpIdentity": {
      "BaseUrl": "http://localhost:44318",
      "UseCurrentAccessToken": false
    }
  }
```
3. I got a result of `Authorization failed! Given policy has not granted: AbpIdentity.UserLookup`
4. Here is the body of the request:

![image](https://user-images.githubusercontent.com/8120385/78864361-11180700-7a6e-11ea-84c1-25d655caa561.png)

#### conclusion
- All remote requests are automatically tagged with tenant headers，As long as the current context contains tenants
- However, the tenant management interface does not set the permissions of IdentityServerClient
- All when using IdentityClient to remotely request data and the current context contains the tenant，Always get an unauthorized response

**I think is a bug!**

**Comment by maliming** [comment]
I will check it. Thanks for the feedback.

**Comment by gdlcf88** [comment]
It may relate to: https://github.com/abpframework/abp/issues/3131

**Comment by maliming** [comment]
@SmallShrimp Please provide a project.

**Comment by SmallShrimp** [comment]
https://github.com/SmallShrimp/AbpRemotePermissionDemo
Switching between different tenants to access the API `/api/Client/sample/{id}` ill give you different results

**Comment by maliming** [comment]
Please provide full steps to reproduce.
