### ISSUE TITLE
Using framework source code in startup template

### ISSUE THREAD

**Issue by zafariNet** [abpframework/abp#3528]
Hello,
Is there any way to using framework source code  in startup template instead of using nuget packages ?
I mean , i want to change framework source code any time i want,
For example i change repository source code or change some third party configuration and other things in framework source code without overriding methods and derive any class.
I would like to make source code of abp part of my project and don’t want to use dlls.

**Comment by liangshiw** [comment]
Use `--local-framework-ref --abp-path` options
![image](https://user-images.githubusercontent.com/16813853/78867017-01e78800-7a73-11ea-88e5-7f52acbcb1c5.png)

**Comment by johnwanzhi** [comment]
I downloaded an ABP sample project, how do I refer to the local framework for debugging?
For example, I downloaded a sample from https://github.com/abpframework/abp-samples, and I want to replace the NuGet package of the sample with the ABP local framework for debugging.
I've looked through all the cli commands and can't find it, can anyone help me?

**Comment by johnwanzhi** [comment]
@maliming

**Comment by maliming** [comment]
You can only change the package manually.
