### ISSUE TITLE
Why loop excuting "Executing DbCommand"

### ISSUE THREAD

**Issue by holyrong** [abpframework/abp#3532]
I'm working with abp vnext 2.4，I‘ve get many logs every several seconds。The logs I've got like this：
![image](https://user-images.githubusercontent.com/8318475/78889787-f3ab6300-7a96-11ea-89bb-a38ae3a7247b.png)

**How can i  stop the loop job?**

**Comment by liangshiw** [comment]
Hi @holyrong 
ABP framework background jobs system use background workers to achieve scheduling. Background Job module use database persistence jobs. This is the design.
1. If you don't need a background jobs system, you can disable it. See https://docs.abp.io/en/abp/latest/Background-Jobs#disable-job-execution
2. You can also replace it with your own implementation (like use redis)

**Comment by holyrong** [comment]
> Hi @holyrong
> ABP framework background jobs system use background workers to achieve scheduling. Background Job module use database persistence jobs. This is the design.
> 
> 1. If you don't need a background jobs system, you can disable it. See https://docs.abp.io/en/abp/latest/Background-Jobs#disable-job-execution
> 2. You can also replace it with your own implementation (like use redis)

OK,Thank you!
