### ISSUE TITLE
Angular Update

### ISSUE THREAD

**Issue by nemesis567** [abpframework/abp#3537]
So I updated my angular version to the last release and I'm facing an issue with ABP table and my action not getting executed:

`
core.js:6189 ERROR TypeError: Cannot read property 'length' of undefined
   at TableComponent.get totalRecords [as totalRecords] (abp-ng.theme.shared.js:2411)
   at TableComponent.get totalPages [as totalPages] (abp-ng.theme.shared.js:2429)
   at TableComponent_Template (abp-ng.theme.shared.js:2472)
   at executeTemplate (core.js:12010)
   at refreshView (core.js:11857)
   at refreshComponent (core.js:13295)
   at refreshChildComponents (core.js:11586)
   at refreshView (core.js:11909)
   at refreshDynamicEmbeddedViews (core.js:13220)
   at refreshView (core.js:11880)
  defaultErrorLogger | @ | core.js:6189

-- | -- | -- | --
  | handleError | @ | core.js:6242
  | handleError | @ | core.js:13624
  | detectChangesInternal | @ | core.js:13476
  | detectChanges | @ | core.js:15091
  | ngAfterViewInit | @ | abp-ng.core.js:2212
  | callHook | @ | core.js:4690
  | callHooks | @ | core.js:4654
  | executeInitAndCheckHooks | @ | core.js:4595
  | refreshView | @ | core.js:11933
  | refreshDynamicEmbeddedViews | @ | core.js:13220
  | refreshView | @ | core.js:11880
  | refreshDynamicEmbeddedViews | @ | core.js:13220
  | refreshView | @ | core.js:11880
  | refreshDynamicEmbeddedViews | @ | core.js:13220
  | refreshView | @ | core.js:11880
  | refreshDynamicEmbeddedViews | @ | core.js:13220
  | refreshView | @ | core.js:11880
  | refreshDynamicEmbeddedViews | @ | core.js:13220
  | refreshView | @ | core.js:11880
  | refreshDynamicEmbeddedViews | @ | core.js:13220
  | refreshView | @ | core.js:11880
  | refreshDynamicEmbeddedViews | @ | core.js:13220
  | refreshView | @ | core.js:11880
  | detectChangesInternal | @ | core.js:13473
  | detectChanges | @ | core.js:15091
  | ngAfterViewInit | @ | abp-ng.core.js:2212
  | callHook | @ | core.js:4690
  | callHooks | @ | core.js:4654
  | executeInitAndCheckHooks | @ | core.js:4595
  | Promise.then (async) |   |  
  | scheduleMicroTask | @ | zone-evergreen.js:552
  | scheduleTask | @ | zone-evergreen.js:388
  | onScheduleTask | @ | zone-evergreen.js:272
  | scheduleTask | @ | zone-evergreen.js:378
  | scheduleTask | @ | zone-evergreen.js:210
  | scheduleMicroTask | @ | zone-evergreen.js:230
  | scheduleResolveOrReject | @ | zone-evergreen.js:847
  | resolvePromise | @ | zone-evergreen.js:785
  | (anonymous) | @ | zone-evergreen.js:705
  | webpackJsonpCallback | @ | bootstrap:25
  | (anonymous) | @ | tenantconfigurations…rations-module.js:1
  | Show 49 more frames

`

This is using the documented books example.

**Comment by mehmet-erim** [comment]
Hi @nemesis567,

Please check the `value` input of `abp-table`. It must be an array. 

```html
<!-- table value shouldn't be undefined or null. You add an or operator like below-->
<abp-table [value]="data || []">
```

**Comment by nemesis567** [comment]
Needed to add forFeature([ModuleState]) to the module imports. Fixed now.

**Comment by mehmet-erim** [comment]
It is right. The state must declare to NgxsModule via `forRoot` or `forFeature` like below:

```ts
// app.module
NgxsModule.forRoot([YourState]);

// custom module
NgxsModule.forFeature([YourState]);
```
