### ISSUE TITLE
Navigation link problem for docs module multiple projects with the same name

### ISSUE THREAD

**Issue by liangshiw** [abpframework/abp#3539]
After adding multiple projects with the same name in the docs module, a list page will be displayed to select different items, which is good.
But the same navigation link results in only one project being displayed.

![image](https://user-images.githubusercontent.com/16813853/78963508-3b2eff00-7b2a-11ea-9f22-d2555d1c423a.png)

Is this a issue? If we have multiple projects, may we can consider adding GUID as a condition.

https://github.com/abpframework/abp/blob/94156f70b527d50e905b9cc903384051618117ca/modules/docs/src/Volo.Docs.Web/Pages/Documents/Project/Index.cshtml.cs#L177

**Comment by maliming** [comment]
Your project name should be unique.

**Comment by liangshiw** [comment]
Should you think `ShortName` is unique?  Because I can add duplicate projects in the admin page.

**Comment by maliming** [comment]
> A short name of the project to be seen in URLs.

According to the current URL routing template, the `ShortName `of the project cannot be duplicate,
We should make sure it is unique in the domain.
