### ISSUE TITLE
With selecting "Require confirmed email" for the first time I can no longer login

### ISSUE THREAD

**Issue by michaelsudnik** [abpframework/abp#3542]
When selecting this option, if I then try to login again, I cannot because my email address has not yet been confirmed. Maybe the initial created admin account should have its email address confirmed property set to true by default. And if logging in with the correct username and password, the confirmation email could be resent or at least give the user the option to resend it.

----

When the "Require confirmed email" option is selected and a new user registers, they are logged in straight away. They should be presented with a message saying thank you for registering and to confirm their email before logging in.

**Comment by michaelsudnik** [comment]
It would also be useful to be able to set the email address confirmed property for individual users within the user management.

**Comment by maliming** [comment]
Please follow: https://github.com/abpframework/abp/issues/2608#issuecomment-572883146

**Comment by brunobertechini** [comment]
I am able to reproduce this using angular & separated identity server. After registering a new user, when "Required confirmed email" enabled, the user is automatically logged in and redirected to the application (Even before clicking on the confirmation link received via email).

Is there a configuration we can set or is this a bug ?

**Comment by 543787366** [comment]
Any news about this? 😄

**Comment by hikalkan** [comment]
I suppose this issue no longer exists. Please create another issue if necessary.
