### ISSUE TITLE
GET Request Optimizations

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#355]
- [x] Disable audit logging by default.
- [x] Disable transaction by default for GET requests
- [ ] Disable EF Core change tracking by default. -> moved to https://github.com/abpframework/abp/issues/1848

**Comment by bbakermmc** [comment]
You should add ReadUncommitted as the transaction level as to not lock tables instead of disabling the transaction.

**Comment by bbakermmc** [comment]
Not sure why you're confused.  In highly transact-able DBs you cant be waiting for gets,  In our environment we could have data being loaded/updated behind the scenes while the users work.  However, we also verify the data on updates using a version number.  You need to think about these things  If you don't want it to be default, make it configurable/attribute-able so I don't have to go thru and change it out myself later like currently.

Note: We do this on Querable/List pulls for displaying in grids etc., not GetByIds.

I looks like youre going down the path to have concurrency updates, so it should be fine to read uncommitted.
https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/handling-concurrency-with-the-entity-framework-in-an-asp-net-mvc-application

I would say use use this like we do, but Im sure not everyone can, and it is specific to SQL, uncommitted should be universal.
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/snapshot-isolation-in-sql-server

**Comment by hikalkan** [comment]
Hi @bbakermmc 

Is "disabling transaction" better than "using a ReadUncommited transaction" for just reading data from database? I suppose @acjh also thought like that.

**Comment by bbakermmc** [comment]
No because sql still issues it as read committed

Sent from my iPhone

On Jul 11, 2018, at 3:49 AM, Halil İbrahim Kalkan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @bbakermmc<https://github.com/bbakermmc>

Is "disabling transaction" better than "using a ReadUncommited transaction" for just reading data from database? I suppose @acjh<https://github.com/acjh> also thought like that.

**Comment by hikalkan** [comment]
I believe that reading commited data is better. ReadUncommited probably needed only for specific cases. In anyway, it will be easily configurable, don't worry.

**Comment by bbakermmc** [comment]
Sure, Ill let you believe that ;)
