### ISSUE TITLE
How-to debug automagically APIs

### ISSUE THREAD

**Issue by connde** [abpframework/abp#3551]
Hi, sorry if this is not the right place to post this kind of question, let me know if needed.

I'm trying out ABP and I'm getting an exception on automagically generated API. I got the error from the log file, but I would like to know what is the best way to debug it from VS so I don't need to open the log file and look for the exception.

Do I need to override the methods I want to debug or is there an easier way to do it?

**Comment by liangshiw** [comment]
Hi @connde 
You can debug by referencing the framework source code.

**Comment by connde** [comment]
> Hi @connde
> 
> 1. When debugging starts, VS will display abnormal information in the events window.
> 2. You can debug by referencing the framework source code.

Thanks, will do that.
