### ISSUE TITLE
how can i integrate module source code in my application

### ISSUE THREAD

**Issue by MROALI** [abpframework/abp#3555]
Hello , 
how can integrate module in my application. Ohtersayin when generating module with abp a solution file is created. 

My need is to have a module directory which will contains my module projects... 

Thankyou in advance for your help, and sorry if my question is so newbie but didn't find a clear answer in the doc.

**Comment by gdlcf88** [comment]
You don't have to do that. Try to use [JetBrains Rider](https://www.jetbrains.com/rider) to explore or debug your module source code. (Of course, Visual Studio can also do this :D )

**Comment by MROALI** [comment]
I need to do that, to reference my module in my startup mvc project ?

**Comment by liangshiw** [comment]
The way of integrate to modules is mentioned here. See https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Guide
