### ISSUE TITLE
Entity with child properties results into tracking key error

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3565]
I have two tables

Student and student subjects .

A student has many subjects. When I create a student with only one subjects at a time it works. When I have several subjects it results to a key tracking error. 

How can I avoid this error. Am using fullaudit.

**Comment by liangshiw** [comment]
This sounds nothing to do with ABP

**Comment by hikalkan** [comment]
Can you share stacktrace and full error message? Also, share your source code parts. If possible, create a simple project that re-produces it.

**Comment by dicksonkimeu** [comment]
I addressed this, i had to sort the Keys.
