### ISSUE TITLE
Upgrade Swashbuckle.AspNetCore to v5.3.0

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3566]
For fixed issues since v5.0.0 see:
* 5.3.0 https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/12?closed=1
* 5.2.0 https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/10?closed=1
* 5.1.0 https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/9?closed=1

**Comment by hikalkan** [comment]
@liangshiw can you upgrade it?

**Comment by liangshiw** [comment]
@hikalkan  Yes of course.
