### ISSUE TITLE
Update abp modules source code that added with --with-source-code command to latest abp version codes

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#3567]
Hi,
Is it possible also to update source codes for modules that added with `--with-source-code` to get the latest changes from abp beside our modification in these modules?

**Comment by hikalkan** [comment]
No, not possible. Becuase when you get the source code, you can make any change and upgrading it overwites your changes. If you won't make change, then use as NuGet packages. We can not build a "smart merge system" that automatically update the changed files.

**Comment by mehdihadeli** [comment]
@hikalkan ok thanks.
