### ISSUE TITLE
Upgrade @ng-bootstrap/ng-bootstrap in @abp/ng.theme.shared

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3568]
[@ng-bootstrap/ng-bootstrap](https://www.npmjs.com/package/@ng-bootstrap/ng-bootstrap) now supports Angular 9.

**Comment by hikalkan** [comment]
@mehmet-erim can you schedule this?

**Comment by mehmet-erim** [comment]
Unfortunately, @ng-bootstrap/ng-bootstrap v6.0 doesn't work with Angular 8. We still support Angular v8. ng-bootstrap v5 works with both V8 and v9 Angular versions.

**Comment by olicooper** [comment]
Okay, maybe this is one for the backlog when Angular 8 is depreciated later down the line then. Thanks for looking at this.
> Unfortunately, @ng-bootstrap/ng-bootstrap v6.0 doesn't work with Angular 8. We still support Angular v8. ng-bootstrap v5 works with both V8 and v9 Angular versions.

**Comment by mehmet-erim** [comment]
Upgraded the `@ng-bootstrap/ng-bootstrap` version to the latest.
