### ISSUE TITLE
External Login With Github User. The email claim can't be retrived even I set the scope to user/

### ISSUE THREAD

**Issue by youlxs** [abpframework/abp#3570]
I try to integrate the abp vnext with external login for github provider.
But I got this exception.
System.ArgumentNullException: Value cannot be null. (Parameter 'userName')
   at Volo.Abp.Check.NotNull[T](T value, String parameterName)
   at Volo.Abp.Identity.IdentityUser..ctor(Guid id, String userName, String email, Nullable`1 tenantId)
   at Volo.Abp.Account.Web.Pages.Account.LoginModel.CreateExternalUserAsync(ExternalLoginInfo info)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo 

The code here can not get the correct email claim.

![image](https://user-images.githubusercontent.com/10609666/79071634-64f54b00-7d0f-11ea-91b8-ca159f24f8e3.png)

here is my setup 

![image](https://user-images.githubusercontent.com/10609666/79071645-750d2a80-7d0f-11ea-8197-77ef0d047690.png)

**Comment by olicooper** [comment]
Have you looked at what the values in `info.Principal` are in a debugging session? It might help to see why the email address is null. I would also suggest not to use ABP's ClaimTypes as they won't match GitHub's claims which may change in the future too. https://github.com/abpframework/abp/blob/c2b77fa92c961b6e05e848832946b60ab3a09f5d/framework/src/Volo.Abp.Security/Volo/Abp/Security/Claims/AbpClaimTypes.cs#L6-8

Also, maybe the scope you need is `user:email` (the `user` scope also gives write access which might not be needed?) [seen here](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/blob/1e5f9111fde5bb7750ffdd53b11dbaef9207f3b7/docs/en/How-To/Azure-Active-Directory-Authentication-MVC.md#faq

**Comment by youlxs** [comment]
> Have you looked at what the values in `info.Principal` are in a debugging session? It might help to see why the email address is null. I would also suggest not to use ABP's ClaimTypes as they won't match GitHub's claims which may change in the future too.
> 
> https://github.com/abpframework/abp/blob/c2b77fa92c961b6e05e848832946b60ab3a09f5d/framework/src/Volo.Abp.Security/Volo/Abp/Security/Claims/AbpClaimTypes.cs#L6-L8
> 
> Also, maybe the scope you need is `user:email` (the `user` scope also gives write access which might not be needed?) [seen here](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)

**Comment by youlxs** [comment]
> Have you looked at what the values in `info.Principal` are in a debugging session? It might help to see why the email address is null. I would also suggest not to use ABP's ClaimTypes as they won't match GitHub's claims which may change in the future too.
> 
> https://github.com/abpframework/abp/blob/c2b77fa92c961b6e05e848832946b60ab3a09f5d/framework/src/Volo.Abp.Security/Volo/Abp/Security/Claims/AbpClaimTypes.cs#L6-L8
> 
> Also, maybe the scope you need is `user:email` (the `user` scope also gives write access which might not be needed?) [seen here](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)

I just debug the ticket received event, the claims returned by github does not contain the email.  The ClaimTypes.Name is returned. I think the sourcecode 
info.Principal.FindFirstValue(Email) should be change to Name for github.

**Comment by liangshiw** [comment]
Does this work for you?
![image](https://user-images.githubusercontent.com/16813853/79100230-97975600-7d98-11ea-95f5-1e5d8881eb65.png)

**Comment by youlxs** [comment]
> Does this work for you?
> ![image](https://user-images.githubusercontent.com/16813853/79100230-97975600-7d98-11ea-95f5-1e5d8881eb65.png)

do not work

**Comment by liangshiw** [comment]
As @olicooper said , you need is `user:email` . You can consider override `CreateExternalUserAsync` method.

**Comment by youlxs** [comment]
Hi All,
I resolved github integration. There are two issues here.

1> When we request the github the scope options should be added like this.
     
![image](https://user-images.githubusercontent.com/10609666/79103077-89e4cf00-7d9e-11ea-953d-5e11673e76f0.png)
     Both user and user:email should be added.

2>The line code here is incorrect for github, we should use the ClaimsType.Email.
 
![image](https://user-images.githubusercontent.com/10609666/79103212-c44e6c00-7d9e-11ea-8c9e-ee6efe390536.png)

![image](https://user-images.githubusercontent.com/10609666/79103236-cadce380-7d9e-11ea-915b-20711e74845f.png)
