### ISSUE TITLE
(docs) Running ms-demo using docker missed

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#3573]

**Comment by hikalkan** [comment]
We should update docker containers, publish to the docker hub and update the documentation.

**Comment by hitaspdotnet** [comment]
Can be good if we see Docker section in related document with TODO tag. For who don't want to lose their internet bandwidth 😄

**Comment by gterdem** [comment]
Pushing this issue to 3.1 since we need to publish updated images to docker hub.

**Comment by gterdem** [comment]
@hitaspdotnet 
We've updated docker images with 3.0.2 tag. `Latest` tags are still pointing to old version. We're discussing about it. Currently, you can use the docker images by using the `3.0.2` tag explicitly .

**Comment by gterdem** [comment]
Closing the issue. Feel free to create a new issue if you come across any problems.
