### ISSUE TITLE
Audit/Error Log Subscription Notifications

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#358]
As an extra bonus it would be nice to be able to setup subscriptions for specific audit/errors events that I can choose to be notified about on a per user/tenant level (ideally cross tenants if we have users cross tenants).

IE Send me notification/email when there is an error on xxx service yyy action.  This helps to direct the specific users who care about xxx service to better monitor when potential errors occur since we all know how fun it is to monitor/manage errors :)

**Comment by hikalkan** [comment]
I think there are some cloud services & products doing similar things. We will consider this as a potential module, but after first stable version of the framework. Thanks for the suggestion.
