### ISSUE TITLE
Please set ServiceCollectionConventionalRegistrationExtensions.GetOrCreateRegistrarList from private to public

### ISSUE THREAD

**Issue by hubo0831** [abpframework/abp#3584]
I want change behavior of DefaultConventionalRegistrar, but I only can use reflection to change, thanks!

**Comment by maliming** [comment]
I think making GetConventionalRegistrars public should also solve your problem.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Core/Microsoft/Extensions/DependencyInjection/ServiceCollectionConventionalRegistrationExtensions.cs#L16

**Comment by hubo0831** [comment]
OK, thanks!
