### ISSUE TITLE
How to use Configuration APIs in my API.Host project without dependency to MVC modules

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#3587]
Hi,
I use angular for front-end and abp `API.Host` for the backend. I have to add the dependency to `AbpAspNetCoreMvcModule` for working this api `api/abp/application-configuration`. is there any approach for none mvc apps?

**Comment by maliming** [comment]
You must use `AbpAspNetCoreMvcModule`. Mvc and Web Api are essentially the same.

**Comment by mehdihadeli** [comment]
ok thanks.
