### ISSUE TITLE
npm ERR! peer dep missing 

### ISSUE THREAD

**Issue by connde** [abpframework/abp#3588]
Hi, I'm testing the Angular application and I'm getting these messages (bottom), should I worry about it or this does not interfere with the application?

PS C:\Workspace\Store\angular> npm ls --depth=0
Store@0.0.0 C:\Workspace\Store\angular
+-- @abp/ng.account@2.5.0
+-- @abp/ng.identity@2.5.0
+-- @abp/ng.setting-management@2.5.0
+-- @abp/ng.tenant-management@2.5.0
+-- @abp/ng.theme.basic@2.5.0
+-- @angular-devkit/build-angular@0.901.1
+-- @angular-devkit/build-ng-packagr@0.901.1
+-- @angular/animations@9.1.1
+-- @angular/cli@9.1.1
+-- @angular/common@9.1.1
+-- @angular/compiler@9.1.1
+-- @angular/compiler-cli@9.1.1
+-- @angular/core@9.1.1
+-- @angular/forms@9.1.1
+-- @angular/language-service@9.1.1
+-- @angular/platform-browser@9.1.1
+-- @angular/platform-browser-dynamic@9.1.1
+-- @angular/router@9.1.1
+-- @ngxs/logger-plugin@3.6.2
+-- @types/jasmine@3.5.10
+-- @types/jasminewd2@2.0.8
+-- @types/node@12.12.35
+-- codelyzer@5.2.2
+-- jasmine-core@3.5.0
+-- jasmine-spec-reporter@4.2.1
+-- karma@4.4.1
+-- karma-chrome-launcher@3.1.0
+-- karma-coverage-istanbul-reporter@2.1.1
+-- karma-jasmine@3.0.3
+-- karma-jasmine-html-reporter@1.5.3
+-- ng-packagr@9.1.1
+-- ngxs-schematic@1.1.9
+-- protractor@5.4.3
+-- rxjs@6.5.5
+-- ts-node@8.3.0
+-- tslib@1.11.1
+-- tslint@6.1.1
+-- typescript@3.8.3
`-- zone.js@0.10.3

**npm ERR! peer dep missing: @angular/common@^8.0.0, required by @ng-bootstrap/ng-bootstrap@5.3.0
npm ERR! peer dep missing: @angular/common@>=5.0.0 <9.0.0, required by @ngx-validate/core@0.0.7
npm ERR! peer dep missing: @angular/core@^8.0.0, required by @ng-bootstrap/ng-bootstrap@5.3.0
npm ERR! peer dep missing: @angular/core@>=5.0.0 <9.0.0, required by @ngx-validate/core@0.0.7
npm ERR! peer dep missing: @angular/forms@^8.0.0, required by @ng-bootstrap/ng-bootstrap@5.3.0
npm ERR! peer dep missing: @angular/forms@>=5.0.0 <9.0.0, required by @ngx-validate/core@0.0.7
npm ERR! peer dep missing: jquery@1.9.1 - 3, required by bootstrap@4.4.1
npm ERR! peer dep missing: popper.js@^1.16.0, required by bootstrap@4.4.1
npm ERR! peer dep missing: rollup@^1.20.0, required by @rollup/plugin-json@4.0.2**

**Comment by mehmet-erim** [comment]
There are a few peer dependency warnings but these are not a problem. NPM throws errors with `npm ls --depth=0` command, actually these errors are simple warnings. Everything is working correctly. You shouldn't worry.
