### ISSUE TITLE
Using ResourceOwnerPassword flow in angular account module is a secure way? 

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#3589]
Hi,
Using ResourceOwnerPassword flow in angular account module and use it for login page of identity server is ok for security purpose? Or is better we use another oauth flows? this link shows some of its dangers.
https://www.identityserver.com/articles/fact-sheet-the-dangers-of-using-the-password-grant-type-with-mobile-applications

**Comment by maliming** [comment]
`ResourceOwnerPassword `is a simple authentication flow. You can choose and implement your own authentication flow according to your actual situation. : )

**Comment by mehdihadeli** [comment]
@maliming @mehmet-erim  what flows do you suggest for login page for identity server for covering security issues mentioned in the link?

**Comment by maliming** [comment]
The `authorization code` is the strictest authorization mode.
