### ISSUE TITLE
Solution: HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#3590]
I'm receiving the error below after building and running a new ABP Suite 2.5.0 project.  Note, I also experienced this issues in 2.4.0 

**Steps to Reproduce**
1. Create a new project using ABP Suite 2.5.0 or 2.4.0
2. Build and Run DBMigrator application to deploy database.
3. Build and Run Web application.

**Problem**
HTTP Error 500.30 - ANCM In-Process Start Failure

***Log File***
```
2020-04-13 14:42:30.366 -04:00 [INF] Starting web host.
2020-04-13 14:42:33.465 -04:00 [FTL] Host terminated unexpectedly!
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

**Solution**
1. Add _**Microsoft.EntityFrameworkCore**_ to the _**Acme.Bookstore.EntityFrameworkCore.DbMigrations**_ project.  
2. Rebuild & Run Project.

**Comment by maliming** [comment]
For questions about ABP Suite, please feedback in the support forum. https://support.abp.io/QA/Questions/100
