### ISSUE TITLE
After using 'abp generate-proxy', no dto was found in @abp-ng.core

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#3598]
I am working hard on my English.Please bear with me!
Use [ng-alain](https://ng-alain.com/docs/getting-started/en) as the Web framework.Throw an exception after using the command `abp generate-proxy --apiUrl https://localhost:44305 --ui angular --module all`.
but Normal in abp-angular,Can you help me!
**Here is some configuration information:**
package.json
```
"dependencies": {
    "@abp/ng.core": "~2.5.0",
    "@abp/ng.theme.basic": "~2.5.0",
    "@angular/animations": "~8.2.11",
    "@angular/common": "~8.2.11",
....
```
ap.module.ts
```
import { CoreModule as AbpCoreModule } from '@abp/ng.core';
```
**The following error message**
```
ERROR in src/app/account/shared/models/identity-user-dto.ts:1:10 - error TS2305: Module '"D:/\u6587\u6863/\u684C\u9762/a7/Mobest/mobest-alain/node_modules/@abp/ng.core/abp-ng.core"' has no exported member 'ExtensibleFullAuditedEntityDto'.

1 import { ExtensibleFullAuditedEntityDto } from '@abp/ng.core';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/identity/shared/models/identity-role-dto.ts:1:10 - error TS2305: Module '"D:/\u6587\u6863/\u684C\u9762/a7/Mobest/mobest-alain/node_modules/@abp/ng.core/abp-ng.core"' has no exported member 'ExtensibleEntityDto'.

1 import { ExtensibleEntityDto } from '@abp/ng.core';
           ~~~~~~~~~~~~~~~~~~~
src/app/identity/shared/models/identity-user-dto.ts:1:10 - error TS2305: Module '"D:/\u6587\u6863/\u684C\u9762/a7/Mobest/mobest-alain/node_modules/@abp/ng.core/abp-ng.core"' has no exported member 'ExtensibleFullAuditedEntityDto'.

......
```
**THKS!**

**Comment by hexianggui** [comment]
The problem has been solved！
I manually delete the prefix "Extensible", like this: "ExtensibleFullAuditedEntityDto" - >"FullAuditedEntityDto".
My project is now up and running.
Hope "abp generate-proxy" can customize the wrong directory，so that I don't need to change my project structure(My business directory is located in "app/routes" instead of "app"o(∩_∩)o ).
THKS!

**Comment by uwascan** [comment]
@hexianggui could you please share your basic integration with ng-alain. I  intend to use ng-alain for a new project and have been stalling using this framework because of the basic angular template which is not good for Apps
