### ISSUE TITLE
Do you have any blog, or something like that for details about your changelogs  and new features?

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#3603]
Hi,
Do you have any blog or something like that for details about your changelogs and new features? I miss your change and new feature sometimes.

**Comment by liangshiw** [comment]
Hi , You can see https://github.com/abpframework/abp/blob/dev/docs/en/Blog-Posts/ for more information

**Comment by hikalkan** [comment]
Also see release notes: https://github.com/abpframework/abp/releases
Also, read the blog here: https://blog.abp.io/abp
