### ISSUE TITLE
Invalid character on char field in Abp Input TagHelper

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#3613]
![image](https://user-images.githubusercontent.com/9526587/79254356-49b04a00-7e8d-11ea-9564-95c85a3cdb8c.png)

![image](https://user-images.githubusercontent.com/9526587/79254639-b3c8ef00-7e8d-11ea-9e6f-d5a7550f7e25.png)

`<abp-input asp-for="Book.Code"/>`

The entities used for generating this page in Suite 👉  [entities.zip](https://github.com/volosoft/volo/files/4476747/entities.zip)

**Comment by yekalkan** [comment]
This is not related to us. You can try it with Asp.Net Core tag helpers: 
`<input asp-for="Book.Code"/>`
You will see the same result.

`Char` is not nullable. So asp.net core assigns it the default value �. (like assigning "0" to a integer.)

You can use `char?` to avoid this issue.
