### ISSUE TITLE
Leave empty for date input when initial load in AbpTagHelper 

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#3614]
The below tag helper adds a value of `0001-01-01T00:00:00.000`.
Leave it empty.

```
<abp-input asp-for="Book.PublishDate" type="text" class="datepicker" />
```
![image](https://user-images.githubusercontent.com/9526587/79255256-a4967100-7e8e-11ea-9c86-5916b243d58b.png)

**Comment by yekalkan** [comment]
> The below tag helper adds a value of 0001-01-01T00:00:00.000.

No, it doesn't.

"0001-01-01T00:00:00.000" is default value of `DateTime`. If it is wanted empty, then `Datetime?` must be used.

You can try it with Asp.Net Core tag helpers: `<input asp-for="PublishDate"/>`
You will see the same result.

If developer wants to set an initial date, he can do it easily before page is rendered.
