### ISSUE TITLE
MissingMethodException  Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll

### ISSUE THREAD

**Issue by fenggaoyao** [abpframework/abp#3615]
Add Module **Volo.Docs** to xxxHost.project.  An error occurred .When I Deleted  
` Logger  WriteTo.Elasticsearch Code`  in Program.cs。It's OK。
**Delete Affect Code**
`    .WriteTo.Elasticsearch(
                    new ElasticsearchSinkOptions(new Uri(configuration["ElasticSearch:Url"]))
                    {
                        AutoRegisterTemplate = true,
                        AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6,
                        IndexFormat = "msdemo-log-{0:yyyy.MM}"
                    })`

What Reason？ How to solve it without deleting the above code and they do not affect each other.
Thanks

**The Error**
`System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
  Source=Serilog.Sinks.Elasticsearch
  StackTrace:
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink..ctor(ElasticsearchSinkOptions options)
   at Serilog.LoggerConfigurationElasticsearchExtensions.Elasticsearch(LoggerSinkConfiguration loggerSinkConfiguration, ElasticsearchSinkOptions options)`

**Comment by maliming** [comment]
The Docs module is using version 7.5.1 of `NEST`, and you can troubleshoot based on this information.

`<PackageReference Include="NEST" Version="7.5.1" />`
