### ISSUE TITLE
Login "issues" (tenant)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#3618]
abp version: 2.5.0 (generated on website yesterday) - Angular UI
VS version: 2019, 16.5.4
Database: MSSQL 2019
Browser: Edge (Chromium), Chrome v81
OS: Windows 10 (1909)
Environment: Development

My scenario:

1) Create blank database for host and tenant
2) Run .DbMigrator (connection string on host database)
3) Run application and create new tenant (**with admin password that is different from default for abp**)
4) Set tenant connection string to dedicated database
5) Run .DbMigrator (**connection string on host database**) - no issues, tenant database has all tables
6) Logout from host in browser, change tenant (success) and then try to login with "admin" "[my_password]"

Returned error (visible in Developer Tools):

![image](https://user-images.githubusercontent.com/39346964/79300165-38dff280-7ee6-11ea-8ab1-df1aa230d891.png)

`{"error":"invalid_grant","error_description":"Invalid username or password!"}`

7) Then I try to login (in tenant) with "admin" and "1q2w3E*" without any issues/errors.

The second thing, which I noticed in databases is email address.

- There are two users in host database (AbpUsers table)) (one admin for host and one admin for tenant). Admin user for tenant has correct email address (which I assigned during tenant creation - in modal window).

- There is also one admin user in dedicated tenant database (also AbpUsers table), which has email "admin@abp.io".

I know that this is not an issue, because "local admin user" (in tenant dedicated database) is generated after second Migrator run (because dedicated connection string for tenant is assigned after tenant is created and his database is host database).
Is possible to somehow inform user when setting dedicated connection string for tenant that "admin" user could have default password and assigned also default email address?

In my scenario, login to tenant could be very frustrated for new developers/....

Thank you.

**Comment by maliming** [comment]
We have planned to work for the **auto create & migrate database when a tenant conn string changes or create a new tenant with custom conn string**.
