### ISSUE TITLE
abp template renderer doesn't work

### ISSUE THREAD

**Issue by cem1835** [abpframework/abp#3627]
I want to use the abp template render but unfortunately it doesn't work.

![abp email bug](https://user-images.githubusercontent.com/17495243/79358502-f2bc7a80-7f49-11ea-869b-5ad3b283b976.PNG)

Edit :
As far as I understand , It works When I change the EmailAddress property name with "Emailaddress"

**Comment by maliming** [comment]
I will check it.

**Comment by maliming** [comment]
See https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer


If we use `member => member.Name.` this will cause a breaking change.

**Comment by hikalkan** [comment]
template renderer was experimental so far. We are currently working on to make it usable and stable: https://github.com/abpframework/abp/issues/407
