### ISSUE TITLE
Repositories Document error? Not updated?

### ISSUE THREAD

**Issue by qq520360** [abpframework/abp#3628]
https://docs.abp.io/en/abp/latest/Repositories

**Comment by qq520360** [comment]
var people = _personRepository
            .Where(p => p.Name.Contains(nameFilter))
            .ToList();

        return people
            .Select(p => new PersonDto {Id = p.Id, Name = p.Name, Age = p.Age})
            .ToList();

**Comment by liangshiw** [comment]
Where is the error?

**Comment by qq520360** [comment]
> Where is the error

> Where is the error?

“_personRepository ” not have “where”

**Comment by qq520360** [comment]
> Where is the error?

v2.5.0

**Comment by liangshiw** [comment]
> GetList method uses the standard LINQ Where and ToList methods to filter and get a list of people from the data source.

These methods are extension methods for `IQueryable` provided by ef core extension

**Comment by qq520360** [comment]
> > GetList method uses the standard LINQ Where and ToList methods to filter and get a list of people from the data source.
> 
> These methods are extension methods for `IQueryable` provided by ef core extension.

thanks!
