### ISSUE TITLE
whats difference between AppUser and AbpUser

### ISSUE THREAD

**Issue by mohammed-hussein** [abpframework/abp#3631]
Hello,
whats difference between AppUser and AbpUser?,
i found auto generated User 'admin' in abpuser table only.

and how can i reference AbpUser on my entity?

**Comment by liangshiw** [comment]
`AbpUser` is the table name of the `AppUser` entity. 
`AppUser` shares the same table with the `IdentityUser` entity of the identity module.

See the document : https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#entityframeworkcore-project for more information

**Comment by maliming** [comment]
Are you saying `IdentityUser` vs `AppUser?

`AbpUsers`: This entity shares the same table/collection ("AbpUsers" by default) with the `IdentityUser `entity of the Identity module.

You can view the comments of the entity in the template project.

**Comment by mohammed-hussein** [comment]
okay, as per template comment and your reply AppUser entity and AbpUser/Identityuser entity share same table so why there are two different tables 'APPUsers' & 'ABPUser'? and data not synced between them

**Comment by maliming** [comment]
>  why there are two different tables 'APPUsers' & 'ABPUser'? and data not synced between them

Are you using the project created by cli? 
How to reproduce the problem?

**Comment by mohammed-hussein** [comment]
Yes, i'm using cli, and using ABP version 2.5 and this command used to generate my project
"abp new Acme.BookStore --template app --database-provider ef --ui mvc"

**Comment by maliming** [comment]
Full steps, thanks I didn't see any `APPUsers` table.

**Comment by hikalkan** [comment]
There is no AppUsers table when you create a new application.

**Comment by krugerm** [comment]
Starting from a new application using CLI, add-migration generates a migration which includes an AppUser table.

**Comment by maliming** [comment]
@krugerm Please create a new issue.
