### ISSUE TITLE
Logout link Issue

### ISSUE THREAD

**Issue by Wello86** [abpframework/abp#3633]
Hi,
I am using Angular UI with layered architecture and Identity server separated. It is working fine local but when I deploy angular using ng build and host on IIS, I can login but logout link, name and manage profile are not there ! however if I logged in on the identity server itself using the same user I can see them. Any ideas ?

**Comment by mehmet-erim** [comment]
Hi @Wello86 

Please check the `currentUser` object in the `app-configuration` response after logged in. Is `isAuthenticated` property equal to `true`.

**Comment by Wello86** [comment]
"currentUser":{"isAuthenticated":false,"id":null,"tenantId":null,"userName":null}

> Hi @Wello86
> 
> Please check the `currentUser` object in the `app-configuration` response after logged in. Is `isAuthenticated` property equal to `true`.

Hi Mehmet,

Yes is it showing ""currentUser":{"isAuthenticated":false,"id":null,"tenantId":null,"userName":null}"
however this "return this.oAuthService.hasValidAccessToken();" is returning true !
Any suggestions why this happens ? what I need to check more ?

**Comment by mehmet-erim** [comment]
@Wello86 Can you check the *.Host project configurations in `appsettings.json`. `AuthServer.Authority` property shouldn't be `localhost` address. You should replace the `localhost` with your *.IdentityServer project address that working on your server.

**Comment by Wello86** [comment]
@mehmet-erim 
Yes I am using IP already not localhost.

**Comment by maliming** [comment]
@Wello86 

> when I deploy angular using ng build and host on IIS, I can login but logout link, name and manage profile are not there.

When you log in, please check angular's requests and responses and the logs of the application backend. I think the login was not successful.

**Comment by Wello86** [comment]
@mehmet-erim 
Ok I think I am near to get it, it seems problem in Identity Servery configuration. When I ran "DbMigrator" from VS to affect on server DB, this problems happens however when I run "DbMigrator" on identity server locally on my machine it is working!!. Do u know what is the difference?

**Comment by maliming** [comment]
DbMigrator project has appsettings.json, which contains connection string and IdentityServer configuration, which applies migrations and also seed the initial data. It is useful on development as well as on production environment.

**Comment by Wello86** [comment]
@maliming  Yes when I am using it on Development from VS, it works perfectly but when I run its exe on Production, this problem happens!. So now to summarize password is 100% correct and login form is passed and homepage is viewed but IsAuthenticated = false and actually no sign-in happened!. Any suggestions?

**Comment by Wello86** [comment]
@maliming  0K, may be u r right. What is "RootUrl", it has port no that is different than API or Angular. What is also "Test_Web"
"IdentityServer": {
    "Clients": {
      "Test_Web": {
        "ClientId": "Test_Web",
        "RootUrl": "https://localhost:44323"
      },
      "Test_App": {
        "ClientId": "Test_App",
      }
    }
  }

I think may be this config is the problem.

**Comment by maliming** [comment]
> What is "RootUrl"

It is the root url of the Identity Server Client. It will participate in the seed data.
You should change it based on the actual url.

https://github.com/abpframework/abp/blob/4228ce096ee3d9ab063f3a9799e9137ae82f2556/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/IdentityServer/IdentityServerDataSeedContributor.cs#L113

**Comment by Wello86** [comment]
Hi @maliming,
https://localhost:44311/api/abp/application-configuration
Is the code of this API open source so that I can review to know why isAuthenticated is false ?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/AbpApplicationConfigurationController.cs#L8
