### ISSUE TITLE
Preflight Origin CORS issue using abp.ajax

### ISSUE THREAD

**Issue by connde** [abpframework/abp#3634]
Hi, to avoid installing Mvc package in the Application project I´m trying to use abp.ajax to download an Excel file and send it to AppService using JavaScript API proxy. 

Have set a module using 2.50 version and running Unified web project.

First, if this is not the best way let me know, I couldn't call a method from PageModel from the index.js, that might be also a solution?

I'm failing at that and not sure what I'm missing, it also fails with $.ajax, so I'm probably missing something here? I tried adding AllowAllOrigins() but I get the same message.

Index.js
```
var alamodeFeedUrl = 'https://alamodeonline.com/en/Topics/InventoryFeed.xlsx';
$('#ImportAlamodeDataFeedButton').click(function (e) {
        e.preventDefault();
        abp.ajax({
            url: alamodeFeedUrl,
            type: 'GET',
            contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            success: function (result) { console.log(result) },
            error: function (e) { console.log(e); }
        });
    });
```

Added this code to Unified as it did not exist
```
context.Services.AddCors(options =>
            {
                options.AddPolicy(DefaultCorsPolicyName, builder =>
                {
                    builder
                        .WithOrigins(
                            configuration["App:CorsOrigins"]
                                .Split(",", StringSplitOptions.RemoveEmptyEntries)
                                .Select(o => o.RemovePostFix("/"))
                                .ToArray()
                        )
                        .WithAbpExposedHeaders()
                        .SetIsOriginAllowedToAllowWildcardSubdomains()
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials();
                });
            });

app.UseCors(DefaultCorsPolicyName);
```

Added this as well to appSettings.json in Unified project.
```
"App": {
    "CorsOrigins": "https://*.DataFeedManagement.com,https://localhost:44352"
  },
```
Chrome console
![image](https://user-images.githubusercontent.com/1514559/79414839-1c919380-7f82-11ea-803d-967b74143658.png)

Fiddler result
![image](https://user-images.githubusercontent.com/1514559/79414387-db4cb400-7f80-11ea-8a96-6ae4d8924c53.png)

Thanks in advance.

**Comment by liangshiw** [comment]
You won't be able to download a file using $.ajax function, because it only handles text related formats (text, xml, json), and the Excel file is not.
About Origin CORS, your can see: https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1

**Comment by connde** [comment]
> You won't be able to download a file using $.ajax function, because it only handles text related formats (text, xml, json), and the Excel file is not.
> About Origin CORS, your can see: https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1

Ok, so my best approach would be to install Mvc to application service and download it from there?

Is there a way to call a method in Razor PageModel from JavaScript to avoid my first question?

**Comment by liangshiw** [comment]
You can direct use: window.location=<your http url>

**Comment by connde** [comment]
> you can direct use: window.location= `<your http url>`

I don't want to download the file to the client but process it further by sending the array to a method in application layer.

Thanks for your help anyways!
