### ISSUE TITLE
Authentication with Windows account (profile) - Volo.Abp.Ldap?

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#3638]
I found package Volo.Abp.Ldap: https://www.nuget.org/packages/Volo.Abp.Ldap/

Is this package needed for authenticating in application with Windows account?
Is there any example/documentation how to implement Windows Authentication (Angular UI)?
Thank you.

**Comment by maliming** [comment]
see https://github.com/abpframework/abp/issues/1189

**Comment by leonkosak** [comment]
How I missed that! Thank you.

**Comment by leonkosak** [comment]
@maliming I think that this is not the case that I am looking for. Is somehow possible to automatically login in Windows into application based on user windows profile ([domain]\username) without manually writing credentials in textboxes?

**Comment by maliming** [comment]
@akinix Can you help?

**Comment by Stirda** [comment]
I am also looking for automatically login into application based on user windows profile, then query Active Directory which groups current user belongs to. @akinix Any suggestion?

**Comment by VidyaPuri** [comment]
> @maliming I think that this is not the case that I am looking for. Is somehow possible to automatically login in Windows into application based on user windows profile ([domain]\username) without manually writing credentials in textboxes - when Windows Authentication option is enabled on IIS.

Did you manage it?

**Comment by emilsjog** [comment]
@Stirda I'm also interested in the same thing. Did you get it to work? And did you use Blazor WASM or Razor pages?
My use case is to use windows auth on a local network with ABP.io. No connection to outside resources.

**Comment by Stirda** [comment]
@emilsjog See https://github.com/abpframework/abp/discussions/6295

**Comment by emilsjog** [comment]
@Stirda I looked into that one. But the question remains for me. I have not seen any example of authentication with windows accounts that is not against an Azure AD.

**Comment by VidyaPuri** [comment]
> @Stirda I looked into that one. But the question remains for me. I have not seen any example of authentication with windows accounts that is not against an Azure AD.

I managed to succeed in using Windows Authentication for automatic login with ABP.io (commercial) with native and web application. If you are interested make a question on SO and i will answer.

**Comment by Stirda** [comment]
@VidyaPuri @emilsjog If so, please share such a SO link, because we are many to hope finding a working implementation.

**Comment by VidyaPuri** [comment]
> @VidyaPuri @emilsjog If so, please share such a SO link, because we are many to hope finding a working implementation.
Sure, i was also thinking of writing an article for abp because i know how much i struggled with it, might help somebody

**Comment by emilsjog** [comment]
@VidyaPuri It sounds like a good idea for an article about this
