### ISSUE TITLE
using sql scalar functions in linq filters (IQueryable)

### ISSUE THREAD

**Issue by erojasd** [abpframework/abp#3643]
Hi.

Is it possible to use database user-defined scalar functions in linq query using EF Core?
The purpose is to avoid bringing unnecessary data into memory.
Example:

public IQueryable CreateFilter (string someFilter) {
IQueryable test = repository.Where (e => dbUserFunction (e.Name, someFilter)). ToList ()
return test;
}

**Comment by maliming** [comment]
Please refer to:
https://docs.abp.io/en/abp/latest/Entity-Framework-Core#access-to-the-ef-core-api
https://docs.abp.io/en/abp/latest/Repositories
