### ISSUE TITLE
How to disable ThemeSharedModule from angular-UI

### ISSUE THREAD

**Issue by begandroide** [abpframework/abp#3653]
Hi! I'm trying to disable the `ThemeSharedModule` from my frontend application and some components from these module still appearing. 

How we can disable ThemeSharedModule? I tried to remove reference to module in all my modules and in app module too. 

Why i want to do that? : Because we are using another UI framework (Angular material), and Abp is using Bootstrap. So, we need be persistent in UI area.

Thanks 😄

**Comment by mehmet-erim** [comment]
ABP NG modules depend on `ThemeSharedModule`. If you want to remove `ThemeSharedModule`, you should remove all modules, except `CoreModule`. 

Please describe your problem in detail, Maybe we can find a solution without removing the `ThemeSharedModule`.

**Comment by mehmet-erim** [comment]
I have closed the issue because you have not responded for a long time. If you have any questions about this, feel free to open the issue.
