### ISSUE TITLE
the program starts slowly

### ISSUE THREAD

**Issue by h394631316** [abpframework/abp#3657]
When the number of entities is 300, the program starts slowly ，It will take about two minutes to complete ！

![image](https://user-images.githubusercontent.com/33739174/79631256-a14efe00-818a-11ea-9abf-1f26dec30e79.png)
![image](https://user-images.githubusercontent.com/33739174/79631301-f428b580-818a-11ea-8662-ba7ea3339f18.png)

**Comment by liangshiw** [comment]
Maybe related to this issue: https://github.com/abpframework/abp/issues/3180.
It is resolved in the upcoming 2.6 version : https://github.com/abpframework/abp/pull/3348.

**Comment by maliming** [comment]
Maybe related: https://github.com/abpframework/abp/pull/3348

You can try again after v2.6 released.

**Comment by zr53722** [comment]
你好，你的问题解决没，我也遇到了

**Comment by Nokecy** [comment]
`2023-04-19 20:36:00.584 +08:00 [INF] Starting Burn.Abp.HuaHao.HttpApi.Host.
2023-04-19 20:37:17.591 +08:00 [INF] Loaded ABP modules:`

**Comment by Nokecy** [comment]
@maliming  启动需要一分半，直接干超时了。
