### ISSUE TITLE
Simplify DbMigrator console output

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3658]
Just a small suggestion... Because Serilog is already outputting to the console for the DbMigrator, there is no need for the default ILogger to be registered and outputting unnecessary information on the console. We can disable like below:

```csharp
using Microsoft.Extensions.Hosting;

public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureLogging((context, logging) => logging.ClearProviders()) //ADD THIS
        .ConfigureServices((hostContext, services) =>
        {
            services.AddHostedService<DbMigratorHostedService>();
        });
```

Before:
![image](https://user-images.githubusercontent.com/22296715/79639354-51206d80-8183-11ea-8175-bbc16501f1f7.png)

After:
![image](https://user-images.githubusercontent.com/22296715/79639321-19192a80-8183-11ea-949d-471e409d6374.png)

I would probably make it read "Migration successful. Press Ctrl+C to exit." at the end.

**Comment by maliming** [comment]
> I would probably make it read "Migration successful. Press Ctrl+C to exit." at the end.

The migration application will automatically terminate.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.DbMigrator/DbMigratorHostedService.cs#L37
