### ISSUE TITLE
Considering balzor's code sharing, need to modify the framework

### ISSUE THREAD

**Issue by geffzhang** [abpframework/abp#3661]
https://github.com/abpframework/abp/issues/394 ，I looked at the framework code and there are a lot of libraries that can be used as base libraries in blazor。
Now，
Volo.Abp.AspNetCore.Mvc.Client 
Volo.Abp.AspNetCore.Mvc.Contracts
are netcoreapp3.1 

Should be netstandard 2.1 ，share with blazor webassembly。also consider changing a more generic name to express his use

Next 
https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI/Volo/Abp/AspNetCore/Mvc/UI/Theming 
This part of Theme structure can also be used in blazor, which needs to be refactored on the structural considerations of the mvc section

**Comment by hikalkan** [comment]
Thank you @geffzhang. We will consider these while working on [the blazor UI](https://github.com/abpframework/abp/issues/394). We will try to maximize the code share without depending UIs each other.
