### ISSUE TITLE
Allow to hide some URLs in audit logs

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#367]

**Comment by espindl** [comment]
Is there a way to do this now? 
Hangfire requests are logged to audit log from URL `/hangfire/stats`. We want to eliminate them from the audit logs.

**Comment by jortygu** [comment]
@espindl  i think you can reference below link (https://github.com/HangfireIO/Hangfire/issues/1668).

**Comment by hikalkan** [comment]
Most simple way can be overriding the [AuditingManager.SaveAsync](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingManager.cs#L113) method and return without saving for desired URLs.

**Comment by hikalkan** [comment]
This is already done: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAspNetCoreAuditingOptions.cs

**Comment by hikalkan** [comment]
Added to the documentation: https://docs.abp.io/en/abp/latest/Audit-Logging#abpaspnetcoreauditingoptions
