### ISSUE TITLE
LTS version very Essential for ABP

### ISSUE THREAD

**Issue by papyr** [abpframework/abp#3673]
Hello, ABP is constantly changing with updates.

Can you please also include an **Long Term Software** version

**Comment by hikalkan** [comment]
We are trying to not introduce breaking change in feature versions (like 2.5, 2.6) unless we have a very good reason. In such cases, the breaking change is being very simple to fix and it is documented in the change logs.

Maintaining a LTS is hard for such a rapidly growing software and we are not a big team as Microsoft.

Thank you for your suggestion, we will consider it in the future.

BTW, we are planning to fix critical bugs in the current and previous major versions, starting from v3.0. That means, if we find a critical bug in v3.4 and fix it in v3.4.1 or 3.5.0, we will also fix it for 2.x.x version and publish the related NuGet packages.
