### ISSUE TITLE
Auto API Controllers: require authentication by default and AllowAnonymous

### ISSUE THREAD

**Issue by FrancoisKr** [abpframework/abp#3682]
How to require authentication by default for the auto API controllers?

With this:

        context.Services.AddAuthorization(options =>
        {
            options.FallbackPolicy = new AuthorizationPolicyBuilder()
                .RequireAuthenticatedUser()
                .Build();
        });

the auto API controllers require authentication, however the [AllowAnonymous] attribute does not work with specific services.

Thanks

**Comment by liangshiw** [comment]
Hi.
After testing, it works fine. So what is your question?

**Comment by FrancoisKr** [comment]
Hi,

Configuring the application to require authentication works.

However, if I add [AllowAnonymous] to a specific class or method, it does not work: I get a 302 response code (redirection to login page).

Thank you

**Comment by liangshiw** [comment]
I can't reproduce your problem, can you use the CLI to create a simple project to reproduce?

**Comment by FrancoisKr** [comment]
I created a simple project and get the same result (302 response).

Source code is here of the created project:
https://github.com/FrancoisKr/abp-require-authentication-auto-controllers

I must be missing something.

Thank you

**Comment by liangshiw** [comment]
![2020-04-21-11-33-56](https://user-images.githubusercontent.com/16813853/79822624-2ffa8f80-83c4-11ea-88eb-b1945ef799e4.gif)

**Comment by liangshiw** [comment]
![2020-04-21-11-33-56 (1)](https://user-images.githubusercontent.com/16813853/79822719-6fc17700-83c4-11ea-92d0-8e71c0cb8f1f.gif)

**Comment by FrancoisKr** [comment]
Hi Liang,

Thanks for the feedback, I confirm that it works. In fact it's the javascript proxies that no longer work. Is there any way to maintain the proxies for the anonymous endpoints?

Thanks

**Comment by liangshiw** [comment]
1.  Add a new class and copy the following into the class.

```csharp
public class ControllerAllowAnonymousConventionCollection : IApplicationModelConvention
    {
        private readonly string _controllerName;

        public ControllerAllowAnonymousConventionCollection(string controllerName)
        {
            _controllerName = controllerName;
        }

        public void Apply(ApplicationModel application)
        {
            application.Controllers.Where(x => x.ControllerName == _controllerName).ForEach(x =>
            {
                x.Filters.Add(new AllowAnonymousFilter());
                x.Selectors.First().EndpointMetadata.Add(new AllowAnonymousAttribute());
            });
        }
    }
```
2. Open you moduel class and add the following code.

```csharp
Configure<MvcOptions>(option =>
{
       option.Conventions.Add(new ControllerAllowAnonymousConventionCollection("AbpServiceProxyScript"));
});
```

**Comment by FrancoisKr** [comment]
Excellent! Many thanks!

**Comment by FrancoisKr** [comment]
For localization client side to work when user is not authenticated:
options.Conventions.Add(new ControllerAllowAnonymousConventionCollection("AbpApplicationConfigurationScript"));

**Comment by FrancoisKr** [comment]
Hi,

On this topic, could you please confirm that it is safe to allow anonymous access to all ABP controllers:

"Volo.Abp.Account.Web.Areas.Account.Controllers.AccountController   (Volo.Abp.Account.Web)"
"Volo.Abp.Account.AccountController   (Volo.Abp.Account.HttpApi)"
"Pages.Abp.MultiTenancy.AbpTenantController   (Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy)"
"Volo.Abp.Identity.IdentityRoleController   (Volo.Abp.Identity.HttpApi)"
"Volo.Abp.Identity.IdentityUserController   (Volo.Abp.Identity.HttpApi)"
"Volo.Abp.Identity.IdentityUserLookupController   (Volo.Abp.Identity.HttpApi)"
"Volo.Abp.Identity.ProfileController   (Volo.Abp.Identity.HttpApi)"
"Volo.Abp.PermissionManagement.PermissionsController   (Volo.Abp.PermissionManagement.HttpApi)"
"Volo.Abp.TenantManagement.TenantController   (Volo.Abp.TenantManagement.HttpApi)"
"Volo.Abp.FeatureManagement.FeaturesController   (Volo.Abp.FeatureManagement.HttpApi)"
"Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Controllers.ErrorController   (Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared)"
"Volo.Abp.AspNetCore.Mvc.ProxyScripting.AbpServiceProxyScriptController   (Volo.Abp.AspNetCore.Mvc)"
"Volo.Abp.AspNetCore.Mvc.Localization.AbpLanguagesController   (Volo.Abp.AspNetCore.Mvc)"
"Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationController   (Volo.Abp.AspNetCore.Mvc)"
"Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.AbpApplicationConfigurationScriptController   (Volo.Abp.AspNetCore.Mvc)"
"Volo.Abp.AspNetCore.Mvc.ApiExploring.AbpApiDefinitionController   (Volo.Abp.AspNetCore.Mvc)"

Many thanks

**Comment by liangshiw** [comment]
The service has to require authorized access. In addition, you should confirm other controllers yourself

https://github.com/abpframework/abp/blob/bde3dca83dae41d1a53016dca294915e23c555c6/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityRoleAppService.cs#L10

**Comment by FrancoisKr** [comment]
Ok will do so. Thx
