### ISSUE TITLE
Angular UI Change

### ISSUE THREAD

**Issue by chougule-lalit** [abpframework/abp#3684]
Hi,

Is there any way to override styles, navigation, menus and themes.
for example : I want to change the look and feel of <abp-table> how do i do this 
Where can i find the document regarding this ?

**Comment by liangshiw** [comment]
Hi , You can see https://github.com/abpframework/abp/blob/dev/docs/en/UI/Angular/Component-Replacement.md

**Comment by Tashaa78** [comment]
you can also checkout @yinchang0626 's abp.ng repo [here](https://github.com/yinchang0626/abp.ng). He also used the replaceable components [api](https://github.com/abpframework/abp/blob/dev/docs/en/UI/Angular/Component-Replacement.md) to port the UI to [ng-alain](https://ng-alain.github.io/ng-alain/#/dashboard/v1) & [ngx-admin](https://github.com/akveo/ngx-admin)
