### ISSUE TITLE
BackgroundService use AutoMapper ObjectMapper.Map  has big problem

### ISSUE THREAD

**Issue by LouieGuo** [abpframework/abp#3688]
When I use BackgroundService  to use ObjectMapper.Map ,it has a error, for example:
![image](https://user-images.githubusercontent.com/29138525/79835210-e5d3d700-83e0-11ea-8eea-eecee342b225.png)

but,when I use swagger to use this AppService, it doesn't error, and Normal mapping，
so Could you help me ?

**Comment by liangshiw** [comment]
Can you provide the steps to reproduce?

**Comment by LouieGuo** [comment]
-------------- this is  Module Config ------------------

public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddHostedService<DemoMQ>();
        }

---------------this is BackgroundService---------------

public class DemoMQ : BackgroundService
    {
        private readonly IDemoTestAppService _demoTestAppService;

        public DemoMQ(IDemoTestAppService demoTestAppService)
        {
            _demoTestAppService = demoTestAppService;
        }

        protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            string str = "{\"alarmTime\":1586228252000,\"capSrc\":0,\"deviceSerialNum\":\"210235C3MK3201000030\"}";

            _demoTestAppService.HandleIncomingMessage(str);
            return Task.CompletedTask;
        }
    }

---------------this is interface service------------------

public interface IDemoTestAppService
    {
        void HandleIncomingMessage(string input);
    }

----------------this is service----------------------------
public class DemoTestAppService : ApplicationService, IDemoTestAppService
    {
        public void HandleIncomingMessage(string input)
        {
            try
            {
                var quickDoorModel = JsonConvert.DeserializeObject<DeviceDto>(input);
                Devices entity = ObjectMapper.Map<DeviceDto, Devices>(quickDoorModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
    }

    public class DeviceDto
    {
        public long AlarmTime { get; set; }
        public int CapSrc { get; set; }
        public string DeviceSerialNum { get; set; }
    }

    public class Devices
    {
        public string DeviceSerialNum { get; set; }
    }

-----------------this is AutoMapper Profile------------------------------

public class DemoAutoMapperProfile : Profile
    {
        public DemoAutoMapperProfile()
        {
            CreateMap<DeviceDto, Devices>();
        }
}

**Comment by LouieGuo** [comment]
1、
![image](https://user-images.githubusercontent.com/29138525/79859324-69062480-8403-11ea-8493-7fe31b87ee72.png)
2、
![image](https://user-images.githubusercontent.com/29138525/79859344-70c5c900-8403-11ea-8051-36c09eb23582.png)
3、
![image](https://user-images.githubusercontent.com/29138525/79859377-7e7b4e80-8403-11ea-8fe8-7ed977777e3d.png)
4、
![image](https://user-images.githubusercontent.com/29138525/79859430-9a7ef000-8403-11ea-8f97-c34a3648f59f.png)

**Comment by liangshiw** [comment]
You should add delayed execution parameter to let the abp module initialization end.

**Comment by LouieGuo** [comment]
Thank you,I got it
