### ISSUE TITLE
Testing with CrudAppService and domain entity

### ISSUE THREAD

**Issue by connde** [abpframework/abp#3699]
Hi, I created my entity domain and all set are private so I can initiate then with a constructor and check each property before the object is created.

I'm trying to test normal behavior, where I will have Dtos and map then to entity before storing it in db. I'm new to testing, so I might be doing something wrong or just got the wrong concept when designing my tests.

When running a test to throw an exception I'm not getting any error, what am I doing wrong?

Sample code

Domain class
```
public Product(Guid id, ... decimal originalPrice, decimal discountedPrice...) :
            base(id)
        {
            OriginalPrice = CheckOriginalPrice(originalPrice, discountedPrice);
            DiscountedPrice = CheckDiscountedPrice(originalPrice, discountedPrice);
        }

        public virtual void SetOriginalPrice(decimal originalPrice, decimal discountedPrice)
        {
            OriginalPrice = CheckOriginalPrice(originalPrice, discountedPrice);
        }

private static decimal CheckOriginalPrice(decimal originalPrice, decimal discountedPrice)
        {
            if (originalPrice < 0)
                throw new ArgumentOutOfRangeException($"original price ({originalPrice} cannot be negative");
            else if (originalPrice < discountedPrice)
                throw new ArgumentOutOfRangeException($"original price ({originalPrice}) can not be lower than discounted price ({discountedPrice})!");

            return originalPrice;
        }
```

Test

```
var exception = await Assert.ThrowsAsync<Volo.Abp.Validation.AbpValidationException>(async () =>
            {
                await _productAppService.CreateAsync(
                    new CreateProductDto
                    {
...
                        OriginalPrice = 4.05m,
                        DiscountedPrice = 8.05m,
 ...
                    });
            });
```

**Comment by liangshiw** [comment]
This has nothing to do with ABP. You can google or refer to abp unit test 
 :https://github.com/abpframework/abp/tree/dev/framework/test

**Comment by connde** [comment]
I imaged that it wasn't related to ABP itself, I will take a look at referenced link.

**Comment by connde** [comment]
@liangshiw I know is not related to ABP, I tried to map Dto to Entity and it works without any validation on the rules I have set on the entity.

What is the correct approach to use mapping and ensure that my domain rules are validated? 
Does ABP have something available or should I manually create the entity using the set methods I've created for each property?

**Comment by connde** [comment]
I actually managed to solve my problem by having a constructor with same parameters as my dto, that way AutoMapper uses the correct constructor directly and the setters as intended.
