### ISSUE TITLE
Update Nuggets

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#3712]
If I update the nuggets, does that mean I am running on the latest ABP?

Can that break my codes?

**Comment by maliming** [comment]
Are you talking about upgrading the abp package from the nuget(https://nuget.org) source to the latest?

If this is the case, you should pay attention to the release notes, there may be some breaking changes,  of course, not every version. But you should pay attention to it.

**Comment by hikalkan** [comment]
We don't introduce breaking changed in the same major version except;

* We may make breaking changes for not documented / experimental features.
* We may make breaking changes if it is a bug and need to make the change.

Generally, these changes doesn't effect the applications. If they effect, we document it in the "breaking changes" section of the related release notes and also document what to do for existing applications. For example: https://github.com/abpframework/abp/issues/2960
