### ISSUE TITLE
Audit Property Issue

### ISSUE THREAD

**Issue by jortygu** [abpframework/abp#3713]
hi,
   i have an aggregate root define like below,has two Audit Properties,when i only changed **Property1** value, in AbpEntityPropertyChanges Table,both **Property1** & **Property2** are saved,**Property2**'s NewValue and OriginalValue have the same value,is this correct behavior ? or have some method/configuration  only save changed properties just like **Property1**?
```
[DisableAuditing]
public class MyAggregateRoot: FullAuditedAggregateRoot<Guid>
{
    [Audited]
    public virtual string Property1 { get; protected set; }
    [Audited]
    public virtual string Property2 { get; protected set; }
    ...
}
```

**Comment by liangshiw** [comment]
Yes, this is the design of the current audit log system.

**Comment by hikalkan** [comment]
I aggre that it should not save unchanged properties. I created an issue: https://github.com/abpframework/abp/issues/3726
