### ISSUE TITLE
Details operations implementation needs documentation update

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#3724]
After reading these issues about `WithDetails`, `DefaultWithDetailsFunc`, `CreateFilteredQuery` and some @acjh answers ...

- https://github.com/abpframework/abp/issues/3007
- https://github.com/abpframework/abp/issues/2474
- https://github.com/abpframework/abp/issues/616

... I think that the ["Repository Implementation" chapter](https://docs.abp.io/en/abp/master/Best-Practices/Entity-Framework-Core-Integration#repository-implementation) of the "Entity Framework Core Integration Best Practices" documentation page needs an update.

Maybe a merge between 

- https://github.com/abpframework/abp/issues/616#issuecomment-443387977 
- https://github.com/abpframework/abp/issues/2474#issuecomment-569508507
- ["Repository Implementation" chapter](https://docs.abp.io/en/abp/master/Best-Practices/Entity-Framework-Core-Integration#repository-implementation) saying that `WithDetails()` (now by using `DefaultWithDetailsFunc`) should only include collection properties by default 

 would cover many needs?

**Comment by hikalkan** [comment]
Thank you, I will check these and update the document.

**Comment by hikalkan** [comment]
https://docs.abp.io/en/abp/4.0/Entity-Framework-Core#loading-related-entities
