### ISSUE TITLE
Documentation or Linux Template for Linux hosts

### ISSUE THREAD

**Issue by papyr** [abpframework/abp#3725]
Hello, setting it up on Linux with cheaper hosts is not possible, with `Digital Ocean` is only 12$ compared to other hosts.

Not everyone can afford Azure or AWS, can you please **add some documentation help on how to run of Debian/Ubunutu Linux**, now that some of the issues seems to be resolved.

thanks.

**Comment by hikalkan** [comment]
Hi @papyr can you write what issues you have?

We are running it in linux based containers without any problem.

**Comment by papyr** [comment]
Hello @hikalkan I'm not a linux expert, but someone recommended your template and there is no documentation or script to run to setup on Debain or CentOs.

I think it will help many developers migrate to ABP with some basic templates.

______________________________
Here is what I tried, I think we can package this for the community, this should [help ](https://dejanstojanovic.net/aspnet/2018/june/how-to-setup-aspnet-core-run-on-debian-linux-with-nginx/) you.

mkdir $HOME/dotnet     
    
cd $HOME/dotnet     

sudo nano /lib/systemd/system/dotnet-webapi-service.service  

[Unit]  
Description=Dotnet Core WebApi Demo service  
  
[Service]  
ExecStart=/bin/dotnet/dotnet Sample.Core.Web.Api.dll  
WorkingDirectory=/etc/SampleWebApi/  
User=dotnetuser  
Group=dotnetuser  
Restart=on-failure  
SyslogIdentifier=dotnet-webapi-service  
PrivateTemp=true  
  
[Install]  
WantedBy=multi-user.target  
    
wget https://download.microsoft.com/download/D/7/2/D725E47F-A4F1-4285-8935-A91AE2FCC06A/dotnet-sdk-2.0.3-linux-x64.tar.gz   
  
tar zxf dotnet-sdk-2.0.3-linux-x64.tar.gz  
  
sudo cp -r ./dotnet /bin

**Comment by maliming** [comment]
hi @papyr

I think abp is just an asp net core application, we can refer to Microsoft's documentation for deployment and hosting(`windows iis. linux nginx, linux apache, docker  etc.`).

**Comment by papyr** [comment]
Hi @hikalkan, in shared hosting they don't give us access to host containers, since its shared hosting. Mainly just we have to login in to Cpanel or a secure Shell and execute a script to setup. 

So my request is for those shared Linux hosting scenarios, when we want to host in those Linux scenarios. I also think you will get a lot of traction if people can easily setup in shared hosting.

thanks

**Comment by hikalkan** [comment]
This can be a good community article (https://community.abp.io/), but nothing to do for ABP documentation. If anyone can write such an article it is appreciated.
