### ISSUE TITLE
Localization - add german localization for framework & modules

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#3727]
Hello,

is it okay to contribute german (and maybe netherland) localization for the abp framework and modules?
I know we can override the localization and so on but it would be kinda nice to have the localization in the upstream.

If so, I will open a PR for each language we want to contribute.

Here's the current list of `en` localization files, which must be translated:

**framework**
1. `src\Volo.Abp.UI\Localization\Resources\AbpUi\en.json`
2. `test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\TestResources\SourceExt\en.json`
3. `test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\TestResources\Source\en.json`
4. `test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\TestResources\Base\Validation\en.json`
5. `test\Volo.Abp.Localization.Tests\Volo\Abp\Localization\TestResources\Base\CountryNames\en.json`
6. `test\Volo.Abp.Emailing.Tests\Volo\Abp\Emailing\Localization\en.json`
7. `test\Volo.Abp.AspNetCore.Mvc.Tests\Volo\Abp\AspNetCore\Mvc\Localization\Resource\en.json`
8. `src\Volo.Abp.Validation\Volo\Abp\Validation\Localization\en.json`
9. `src\Volo.Abp.UI.Navigation\Volo\Abp\Ui\Navigation\Localization\Resource\en.json`
10. `src\Volo.Abp.Localization\Volo\Abp\Localization\Resources\AbpLocalization\en.json`
11. `src\Volo.Abp.Emailing\Volo\Abp\Emailing\Localization\en.json`
12. `src\Volo.Abp.Ddd.Application.Contracts\Volo\Abp\Application\Localization\Resources\AbpDdd\en.json`
13. `src\Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy\Volo\Abp\AspNetCore\Mvc\UI\MultiTenancy\Localization\en.json`
14. `test\Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.Demo\node_modules\yargs\locales\en.json`
15. `test\Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Demo\node_modules\yargs\locales\en.json`

**modules**
1. `setting-management\src\Volo.Abp.SettingManagement.Domain.Shared\Volo\Abp\SettingManagement\Localization\Resources\AbpSettingManagement\en.json`
2. `permission-management\src\Volo.Abp.PermissionManagement.Domain.Shared\Volo\Abp\PermissionManagement\Localization\Domain\en.json`
3. `feature-management\src\Volo.Abp.FeatureManagement.Domain.Shared\Volo\Abp\FeatureManagement\Localization\Domain\en.json`
4. `docs\src\Volo.Docs.Admin.Application.Contracts\Volo\Docs\Admin\Localization\Resources\Docs\ApplicationContracts\en.json`
5. `docs\app\VoloDocs.Web\Localization\Resources\VoloDocs\Web\en.json`
6. `blogging\src\Volo.Blogging.Application.Contracts\Volo\Blogging\Localization\Resources\Blogging\ApplicationContracts\en.json`
7. `account\src\Volo.Abp.Account.Application.Contracts\Volo\Abp\Account\Localization\Resources\en.json`
8. `docs\src\Volo.Docs.Domain\Volo\Docs\Localization\Domain\en.json`
9. `blogging\src\Volo.Blogging.Domain.Shared\Volo\Blogging\Localization\Resources\en.json`
10. `tenant-management\src\Volo.Abp.TenantManagement.Domain.Shared\Volo\Abp\TenantManagement\Localization\Resources\en.json`
11. `identity\src\Volo.Abp.Identity.Domain.Shared\Volo\Abp\Identity\Localization\en.json`
12. `identityserver\src\Volo.Abp.IdentityServer.Domain.Shared\Volo\Abp\IdentityServer\Localization\Resources\en.json`

**Comment by liangshiw** [comment]
Hi,
Welcome you contributes. Please follow [Contribution Guide]( https://docs.abp.io/en/abp/latest/Contribution/Index).
