### ISSUE TITLE
When I execute the method in swagger  get error Self referencing loop detected with type

### ISSUE THREAD

**Issue by luy710** [abpframework/abp#3730]
When I execute the method in swagger  get error Self referencing loop detected with type

How can I set this？
SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore

I tried a way, but it didn't work
  [JsonObject(ItemReferenceLoopHandling = ReferenceLoopHandling.Ignore)]
 [JsonProperty(ReferenceLoopHandling = ReferenceLoopHandling.Ignore)]

**Comment by liangshiw** [comment]
Try :

`[JsonProperty(ReferenceLoopHandling = ReferenceLoopHandling.Ignore)]`

**Comment by luy710** [comment]
> Try :
> 
> `[JsonProperty(ReferenceLoopHandling = ReferenceLoopHandling.Ignore)]`

thank your reply!
I tried that but it didn't work

**Comment by liangshiw** [comment]
I tested , It works fine.
Can you provide complete steps to reproduce?

**Comment by ArneCools** [comment]
I tried the same, but still get the error: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected

I also tried in PreConfigureServices:
```
context.Services.PreConfigure<IMvcBuilder>(mvcBuilder => {
                mvcBuilder.AddNewtonsoftJson(
                    options => options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);
            });
```

**Comment by CodeOutput** [comment]
Setting ReferenceLoopHandling in JsonProperty on the attribute together with [JsonObject(IsReference = true)] solved the problem. The original answear with AddJsonOptions doesn't had any effect for me.
