### ISSUE TITLE
Why the GetKeys method in entity uses object[] instead of Enumerable

### ISSUE THREAD

**Issue by Maple512** [abpframework/abp#3735]
like this:
```C#
public IEnumerable<object> GetKeys()
{
    yield return Name;
}
```

**Comment by liangshiw** [comment]
The array type itself is iterable.

![image](https://user-images.githubusercontent.com/16813853/80269815-9d206480-86e5-11ea-96ee-653507bfc1e4.png)

**Comment by hikalkan** [comment]
>Why the GetKeys method in entity uses object[] instead of Enumerable

No special reason, `IEnumerable<object>` would also be possible. But no point to discuss this now since it would be an unnecessary breaking change.
