### ISSUE TITLE
The virtual file system cannot handle static asset files well

### ISSUE THREAD

**Issue by liangshiw** [abpframework/abp#3740]
About static asset files: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#consume-content-from-a-referenced-rcl.

ASP NET Core reusable UI library have some static asset files. Due to the lack of `StaticWebAssetsFileProvider`, these files will get a **404 response** during **development**. 

https://github.com/abpframework/abp/blob/3dced6e58bb28168beeab80d8bef3ff405722a85/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/VirtualFileSystem/WebContentFileProvider.cs#L92

![image](https://user-images.githubusercontent.com/16813853/80281965-55c7c180-8741-11ea-81f8-211c14046780.png)

We should consider changing the `CreateFileProvider` method to support static asset files.

**Comment by liangshiw** [comment]
The following code works fine, Since `StaticWebAssetsFileProvider` is inner class, so I can't by comparison with the type.

```csharp
protected virtual IFileProvider CreateFileProvider()
{
   var fileProviders  = new List<IFileProvider>()
    {
         new PhysicalFileProvider(_hostingEnvironment.ContentRootPath),
         _virtualFileProvider
    };

    if (_hostingEnvironment.IsDevelopment() && _hostingEnvironment.WebRootFileProvider is CompositeFileProvider compositeFileProvider)
    {
        fileProviders.AddRange(compositeFileProvider.FileProviders.Where(f => f.GetType().Name.Equals("StaticWebAssetsFileProvider")).ToList());
    }

    return new CompositeFileProvider(
        fileProviders
    );
}
```

**Comment by wjkhappy14** [comment]
got it ,thks !

**Comment by liangshiw** [comment]
@hikalkan  What do you think?

**Comment by liangshiw** [comment]
@hikalkan  
Why close ?

When we integrate some UI libraries like : https://github.com/elsa-workflows/elsa-core#workflow-designer, the application cannot get static resources during development.

**Comment by hikalkan** [comment]
I already implemented your solution.

**Comment by liangshiw** [comment]
ok  : ) .
