### ISSUE TITLE
debug volo.abp source error,get pdb file failed..how handle???

### ISSUE THREAD

**Issue by heyuquan** [abpframework/abp#3741]
information

SYMSRV:  BYINDEX: 0xCE3
         C:\Users\heyuquan\AppData\Local\Temp\SymbolCache*https://symbols.nuget.org/download/symbols
         Volo.Abp.PermissionManagement.Domain.Identity.pdb
         1148E9A31977404ABED21CA40F02E7C4ffffffff

SYMSRV:  UNC: C:\Users\heyuquan\AppData\Local\Temp\SymbolCache\Volo.Abp.PermissionManagement.Domain.Identity.pdb\1148E9A31977404ABED21CA40F02E7C4ffffffff\Volo.Abp.PermissionManagement.Domain.Identity.pdb - path not found

SYMSRV:  UNC: C:\Users\heyuquan\AppData\Local\Temp\SymbolCache\Volo.Abp.PermissionManagement.Domain.Identity.pdb\1148E9A31977404ABED21CA40F02E7C4ffffffff\Volo.Abp.PermissionManagement.Domain.Identity.pd_ - path not found

SYMSRV:  UNC: C:\Users\heyuquan\AppData\Local\Temp\SymbolCache\Volo.Abp.PermissionManagement.Domain.Identity.pdb\1148E9A31977404ABED21CA40F02E7C4ffffffff\file.ptr - path not found

SYMSRV:  HTTPGET: /download/symbols/Volo.Abp.PermissionManagement.Domain.Identity.pdb/1148E9A31977404ABED21CA40F02E7C4ffffffff/Volo.Abp.PermissionManagement.Domain.Identity.pdb

SYMSRV:  HttpQueryInfo: 80190193 - HTTP_STATUS_FORBIDDEN

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/issues/3462.
You can debug by downloading the source code.
