### ISSUE TITLE
(question)How to solve background job call authrized application service calls the exception(Authorization failed! User has not logged in)

### ISSUE THREAD

**Issue by zredb** [abpframework/abp#3743]
hello, 
      I have a background job in which Execute method, I called a service method from application service layer,
the  service class has a [Authorize] attribute, so if I call the service method will catch the Volo.Abp.Authorization.AbpAuthorizationException, how can i solve this problem safely? any comment is welcomed.

**Comment by wjkhappy14** [comment]
maybe  [AllowAnonymous]  attribute

**Comment by zredb** [comment]
Yes,  [AllowAnonymous] attribute can solve this problem, 
but this attribute also expose the API to user which isn't Authorized.

**Comment by maliming** [comment]
Please refer to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1107#issuecomment-226714736

It also applies to vnext.

**Comment by zredb** [comment]
thank you.
