### ISSUE TITLE
(@abp/ng.core) ReplaceableComponent not work fine at get @Input Property

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#3744]
@mehmet-erim 
Hi, as we know `Component Replacement` is very good design for customization component
but latest version has something wrong:
1.Follow [docs](https://github.com/abpframework/abp/blob/dev/docs/en/UI/Angular/Component-Replacement.md#component-replacement),I created a `MyPermissionManagementComponent` in `dev-app`
2.Add it to `AppComponent`
```typescript
  declarations: [AppComponent, MyPermissionManagementComponent],
  entryComponents:[MyPermissionManagementComponent],
  exports:[MyPermissionManagementComponent]
export class AppModule {}
```
3.call a action to change component on `OnInit` of `AppComponent`
```typescript
export class AppComponent implements OnInit {
  ngOnInit() {
    this.store.dispatch(
      new AddReplaceableComponent({
        component: MyPermissionManagementComponent,
        key: ePermissionManagementComponents.PermissionManagement,
      }));

  }
}
```
Run `identity/roles`:
the component is showed but @Input properties didn't get data:

1.before replace `PermissionManagementComponent` component
![image](https://user-images.githubusercontent.com/16490084/80299525-b6014680-87c7-11ea-9cb0-a4f796c4ebd4.png)
2. after replaced `PermissionManagementComponent` component
![image](https://user-images.githubusercontent.com/16490084/80299588-2740f980-87c8-11ea-849f-725ffa5c832b.png)

Could you help me to check this issue is a bug or not?
[Here](https://github.com/abpframework/abp/compare/dev...FurtherSoftware:feature/ng) is test code, you can get it in this [branch](https://github.com/FurtherSoftware/abp/tree/feature/ng),
Thank You

**Comment by mehmet-erim** [comment]
Hi @yinchang0626   
Which angular version is installed in your project?
