### ISSUE TITLE
IStringLocalizer not work,when i just set CultureInfo.CurrentCultrue property value

### ISSUE THREAD

**Issue by maomft** [abpframework/abp#3747]

**Comment by maomft** [comment]
`        protected virtual LocalizedString GetLocalizedString(string name)
        {
            return GetLocalizedString(name, CultureInfo.CurrentUICulture.Name);
        }` The source code in AbpDictionaryBasedStringLocalizer.cs class in Volo.Abp.Localization project.I think that is why

**Comment by maomft** [comment]
reopen.comment is edited.

**Comment by liangshiw** [comment]
Can you provide complete steps to reproduce?

**Comment by maomft** [comment]
> Can you provide complete steps to reproduce?
`using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using MyAbpNext.Localization;
using MyAbpNext.Web.Mvc.Models;
using MyAbpNext.Web.Pages;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.Localization;

namespace MyAbpNext.Web.Mvc.Controllers
{
    public class HomeController : AbpController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStringLocalizer<MyAbpNextResource> localizer;
        public HomeController(
            ILogger<HomeController> logger, 
            IStringLocalizer<MyAbpNextResource> localizer
            )
        {
            _logger = logger;
            this.localizer = localizer;
        }

        public IActionResult Index()
        {
            CultureInfo.CurrentCulture = new CultureInfo("zh-Hans");//its not working
            //CultureInfo.CurrentUICulture = new CultureInfo("zh-Hans");//its working
            return Content("Hello,World!"+ "IStringLocalizer:" + localizer["Welcome"]);
        }
    }
}
`
I create a HomeConctroller and a action called index.

**Comment by liangshiw** [comment]
`CurrentCulture` is the .NET representation of the default user locale of the system. This controls default number and date formatting and the like.

`CurrentUICulture` refers to the default user interface language. This is primarily regarding the UI localization/translation part of your app.

**Comment by maomft** [comment]
> `CurrentCulture` is the .NET representation of the default user locale of the system. This controls default number and date formatting and the like.

thanks for your reply,i have learned a lot.Thanks again.
