### ISSUE TITLE
Background tasks with hosted services integration

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#375]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1

We may use it for background workers and jobs.

**Comment by leonkosak** [comment]
Future feature suggestion

Background workers (and jobs) have to be "cluster-friendly".
Hangfire has this feature (but HF is just bor background JOBS): https://www.hangfire.io/features.html#multiple-queues-processing
