### ISSUE TITLE
Get tenant ID from user table.

### ISSUE THREAD

**Issue by dmeagor** [abpframework/abp#3752]
Looking at the AbpUser table I can see that TenantId is stored with the user however I cannot see a way to sign the user into that tenant when they login (angular version.)

I simply want them to login normally and current tenant id set to the one listed on the user table entry.

At this point no cookies have been set and everyone logs in on the same domain/path so I don't see how we map them?

I hope I haven't misunderstood a key feature of this platform and this is supported somehow!

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Multi-Tenancy#custom-tenant-resolvers

**Comment by dmeagor** [comment]
CustomTenantResolveContributor runs before the user is logged in, and you cannot login without knowing the tenant first.

So I need to disable the tenant check on the login but I don't see how to do this.  Could you please point me in the right direction?

**Comment by liangshiw** [comment]
@dmeagor  https://docs.abp.io/en/abp/latest/Multi-Tenancy#determining-current-tenant-from-web-request

**Comment by dmeagor** [comment]
Thanks for the reply.  These options seem to rely on the tenant already being known or entered by the user.

> CurrentUserTenantResolveContributor: Gets the tenant id from claims of the current user, **if the current user has logged in**. 

User cannot login with null/unspecified tenant.  **I need to login and THEN set the tenant.**

I think this should be an option.

> QueryStringTenantResolver: Tries to find current tenant id from query string parameter. Parameter name is "__tenant" by default.
> RouteTenantResolver: Tries to find current tenant id from route (URL path). Variable name is "__tenant" by default. So, if you defined a route with this variable, then it can determine the current tenant from the route.
> HeaderTenantResolver: Tries to find current tenant id from HTTP header. Header name is "__tenant" by default.
> CookieTenantResolver: Tries to find current tenant id from cookie values. Cookie name is "__tenant" by default.
> 

Requires path or prior knowledge of the tenant which the customer doesn't have.

**Comment by liangshiw** [comment]
If you want to not isolate tenants when logging in, you can choose to disable the multi-tenant filter for the login method.
But if you are developing a multi-tenant application, I do not recommend you to use this method, you should determine the current tenant from the route ,header or other.
However, the choice is yours .

**Comment by dmeagor** [comment]
Thanks.

Do I DI replace this method (when using the Angular version.)

**Volo.Abp.Identity.IdentifyUser.AddLogin**

> public virtual void AddLogin([NotNull] UserLoginInfo login)

I've been hunting around the source code and so far that's all I've found.

**Comment by dmeagor** [comment]
**Ignore previous post.**  

For the benefit of anyone else with the same problem.  After lots/hours of trial and error the class that hits the debugger is: **IdentityServerSupportedLoginModel.OnPostAsync()**.

I think this should just be a simple configuration option for the MultiTenant setup though as many sites just have a single login page but still want segregate their users easily.  Overriding classes in this way causes maintenance issues.

**It would be nice if sql filters could be disabled by attribute rather than using block.**  Then we could just disable it for a class without implementing all of the code.


Following the abp documentation I've replaced this class with my own like so...

```
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IdentityServerSupportedLoginModel),typeof(LoginModel))]
    public class MyIdentityServerSupportedLoginModel :  IdentityServerSupportedLoginModel

    {
        private readonly IDataFilter _dataFilter;
        
        public MyIdentityServerSupportedLoginModel(IAuthenticationSchemeProvider schemeProvider,
            IOptions<AbpAccountOptions> accountOptions,
            IIdentityServerInteractionService interaction,
            IClientStore clientStore,
            IEventService identityServerEvents,
            IDataFilter dataFilter) : base(schemeProvider,
            accountOptions,
            interaction,
            clientStore,
            identityServerEvents)
        {
            _dataFilter = dataFilter;
        }
```

And disabled the filter around the post with a using block.

```
        [UnitOfWork] //TODO: Will be removed when we implement action filter
        public override async Task<IActionResult> OnPostAsync(string action)
        {
            using (_dataFilter.Disable<IMultiTenant>())
            {
//existing code.
            }
```

The other members of this class might also need to have the filter disabled.

**Comment by liangshiw** [comment]
I think the current way is more flexible.

**Comment by wushizhan** [comment]
I have the same question. I want get the tenantId form login with ids4 connect/token. I know the accecc_token will contain tenantId if request with __tenant header, But I want ids4 connect/token always contain tenantId  whatever it is null or have value.  My English is not so good, I hope I have described the problem clearly.
