### ISSUE TITLE
Error when access authorized AppService

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#3755]
Hi,

I'm facing a problem that when I access the authorized AppService, I got an error 

> "Volo.Abp.AbpException: There is already an existing permission group with name: AbpIdentity"

Then I tried to remove package AbpIdentity*module, I got different error 

> "Volo.Abp.Authorization.AbpAuthorizationException: Authorization failed! Given policy has not granted."

**Comment by liangshiw** [comment]
Can you provide steps to reproduce?

**Comment by volethanh** [comment]
I'm using template mongodb and then add `DependsOn `to *.HttpApi.Host project 

![image](https://user-images.githubusercontent.com/46510130/80357609-6bee9280-88a5-11ea-9929-c17abcf71e34.png)

**Comment by volethanh** [comment]
I found my fault, after changing `ApiName`, it worked !

`context.Services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.RequireHttpsMetadata = true;
                    options.ApiName = "DDC";
                });`
