### ISSUE TITLE
Can we hide ABP related HTTP API endpoints if desired?

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3758]
Even for an empty project, we have the following pre-defined HTTP endpoints:

![image](https://user-images.githubusercontent.com/1210527/80378092-d18e4f00-88a4-11ea-9920-d877443c7438.png)

We may want to disable these endpoints (not only hide from swagger, but completely disable them). So, we need to provide an option for it.

**Comment by olicooper** [comment]
I am hiding the abp endpoints on Swagger UI by adding a `[ShowInSwagger]` attribute to the controllers I want to see, then using this in my host module:

```csharp
public class ShowInSwaggerAttributeFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        var filteredApis = context.ApiDescriptions.Where(a => a.CustomAttributes().Any(x => 
            x.GetType() == typeof(ShowInSwaggerAttribute)));

        foreach (var path in swaggerDoc.Paths.ToList())
        {
            if (filteredApis.All(x => ("/" + x.RelativePath) != path.Key))
                swaggerDoc.Paths.Remove(path.Key);
        }
    }
}
```

**Comment by tinonetic** [comment]
How do I prevent the execution of certain methods and tell ABP to ignore them when creating endpoints (by convention)

**Comment by xyfy** [comment]
it is greate enhancement, recently I am looking for it .

I don’t want to expose some pre-built apis

**Comment by ozdogans** [comment]
Is there any update on this?

**Comment by ArneCools** [comment]
> I am hiding the abp endpoints on Swagger UI by adding a `[ShowInSwagger]` attribute to the controllers I want to see, then using this in my host module:
> 
> ```cs
> public class ShowInSwaggerAttributeFilter : IDocumentFilter
> {
>     public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
>     {
>         var filteredApis = context.ApiDescriptions.Where(a => a.CustomAttributes().Any(x => 
>             x.GetType() == typeof(ShowInSwaggerAttribute)));
> 
>         foreach (var path in swaggerDoc.Paths.ToList())
>         {
>             if (filteredApis.All(x => ("/" + x.RelativePath) != path.Key))
>                 swaggerDoc.Paths.Remove(path.Key);
>         }
>     }
> }
> ```

How do I make this work? I added this class to my host module, but swagger doesnt run it (I tried setting a breakpoint)

**Comment by yellow-dragon-cloud** [comment]
@hikalkan @ArneCools  `ShowInSwaggerAttributeFilter` must be added in `.HttpApi.Host` project configuration:
```csharp
private static void ConfigureSwaggerServices(ServiceConfigurationContext context, IConfiguration configuration)
{
    context.Services.AddAbpSwaggerGenWithOAuth(
        configuration["AuthServer:Authority"],
        new Dictionary<string, string>
        {
            {"...", "... API"}
        },
        options =>
        {
            options.DocumentFilter<ShowInSwaggerAttributeFilter>(); // <- ADD THIS!
            options.SwaggerDoc("v1", new OpenApiInfo {Title = "... API", Version = "v1"});
            options.DocInclusionPredicate((docName, description) => true);
            options.CustomSchemaIds(type => type.FullName);
        });
}
```

**Comment by 1d0n7kn0w** [comment]
@hikalkan any news?

**Comment by gaoconggit** [comment]
```csharp  
private static void ConfigureSwaggerServices(ServiceConfigurationContext context, IConfiguration configuration)
{
   context.Services.AddAbpSwaggerGenWithOAuth(
   configuration["AuthServer:Authority"],
   new Dictionary<string, string>
   {
      {"...", "... API"}
   },
   options =>
   {
      options.SwaggerDoc("v1", new OpenApiInfo {Title = "... API", Version = "v1"});
      //options.DocInclusionPredicate((docName, description) => true); // <- Comment out this line of code
      options.CustomSchemaIds(type => type.FullName);
   });
}  

```

try it out

**Comment by cdlian** [comment]
The following example hides the API in Volo.Abp.Account.HttpApi
```csharp
public override void OnPreApplicationInitialization(ApplicationInitializationContext context)
{
    var applicationPartManager = context.ServiceProvider.GetRequiredService<ApplicationPartManager>();

    applicationPartManager.ApplicationParts.RemoveAll(s => s.Name == "Volo.Abp.Account.HttpApi");
}
```
For more information, please visit [ASP.NET Core Docs](https://docs.microsoft.com/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-5.0#prevent-loading-resources)

**Comment by AlexanderSysoev** [comment]
@cdlian thanks! What about other endpoints?

**Comment by AlexanderSysoev** [comment]
According to @cdlian answer this code snippet:

```
   public override void OnPreApplicationInitialization(ApplicationInitializationContext context)
    {
        var applicationPartManager = context.ServiceProvider.GetRequiredService<ApplicationPartManager>();
        applicationPartManager.ApplicationParts.RemoveAll(s => s.Name == "Volo.Abp.Account.HttpApi");
        applicationPartManager.ApplicationParts.RemoveAll(s => s.Name == "Volo.Abp.FeatureManagement.HttpApi");
        applicationPartManager.ApplicationParts.RemoveAll(s => s.Name == "Volo.Abp.Identity.HttpApi");
        applicationPartManager.ApplicationParts.RemoveAll(s => s.Name == "Volo.Abp.PermissionManagement.HttpApi");
        applicationPartManager.ApplicationParts.RemoveAll(s => s.Name == "Volo.Abp.SettingsManagement.HttpApi");
    }
```
hides everything except:

- AbpApiDefinition
- AbpApplicationConfiguration
- AbpTenant
- EmailSettings

Still confused about this.

**Comment by zjsjmvn** [comment]
Is there any update on this?

**Comment by cdlian** [comment]
@AlexanderSysoev 

By overriding the ApplyForControllers method of AbpServiceConvention, you can remove controllers you don't need.

```csharp
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAbpServiceConvention))]
public class MyServiceConvention : AbpServiceConvention
{
    public MyServiceConvention(IOptions<AbpAspNetCoreMvcOptions> options, IConventionalRouteBuilder conventionalRouteBuilder) : base(options, conventionalRouteBuilder)
    {
    }

    protected override void ApplyForControllers(ApplicationModel application)
    {
        application.Controllers.RemoveAll(s => s.ControllerType == typeof(AbpApplicationConfigurationController));

        base.ApplyForControllers(application);
    }
}
```

**Comment by EngincanV** [comment]
With v5.2 there is a built-in option to hide ABP-related endpoints on Swagger UI.

Call the `HideAbpEndpoints` method in your Swagger configuration as follows:

```csharp
services.AddAbpSwaggerGen(
    options => 
    {
        //... other options
        
        //Hides ABP Related endpoints on Swagger UI
        options.HideAbpEndpoints();
    }
)
```

> After that, ABP's default endpoints will still be functional, but will be hidden on Swagger UI. 
https://docs.abp.io/en/abp/5.2/API/Swagger-Integration#hide-abp-endpoints-on-swagger-ui

**Comment by truongkyit** [comment]
> ```cs
> private static void ConfigureSwaggerServices(ServiceConfigurationContext context, IConfiguration configuration)
> {
>    context.Services.AddAbpSwaggerGenWithOAuth(
>    configuration["AuthServer:Authority"],
>    new Dictionary<string, string>
>    {
>       {"...", "... API"}
>    },
>    options =>
>    {
>       options.SwaggerDoc("v1", new OpenApiInfo {Title = "... API", Version = "v1"});
>       //options.DocInclusionPredicate((docName, description) => true); // <- Comment out this line of code
>       options.CustomSchemaIds(type => type.FullName);
>    });
> }  
> ```
> 
> try it out


this is very helpful

**Comment by MathiasKowoll** [comment]
It is possible to force authentication on EmailSettings API
