### ISSUE TITLE
record level security in abp

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#3759]
Hi,
How can I do a record level security in abp with specific permission?

**Comment by maliming** [comment]
It is not implemented by default, you should refer to abp and Microsoft's permission design to implement it yourself.

https://docs.abp.io/en/abp/latest/Authorization
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/introduction?view=aspnetcore-3.1

**Comment by mehdihadeli** [comment]
ok thanks.
