### ISSUE TITLE
How to get currentUser email or other info in micro services?

### ISSUE THREAD

**Issue by shikelong** [abpframework/abp#3761]
Hi, I am a newer to abp and id4, Sometime We need get current user info in micro services.

I inject ICurrentUser to my microservice's Application Layer, But i can only get user id from IcurrentUser instance. Other info is null.

![2020-04-28_122647](https://user-images.githubusercontent.com/4499997/80444127-d65a0e00-894b-11ea-9406-16571c0d4ef7.png)

In my micro service host module. I has map identity claim key to abpClaimTypes like this:

```csharp

app.Use(async (ctx, next) =>
            {
                var user = ctx.User;
                var currentPrincipalAccessor = ctx.RequestServices.GetRequiredService<ICurrentPrincipalAccessor>();
                var map = new Dictionary<string, string>()
                {
                    { "sub", AbpClaimTypes.UserId },
                    { "role", AbpClaimTypes.Role },
                    { "email", AbpClaimTypes.Email },
                    //any other map
                };
                var mapClaims = currentPrincipalAccessor.Principal.Claims.Where(p => map.Keys.Contains(p.Type)).ToList();
                currentPrincipalAccessor.Principal.AddIdentity(new ClaimsIdentity(mapClaims.Select(p => new Claim(map[p.Type], p.Value, p.ValueType, p.Issuer))));
                await next();
            });

```

And I find my HttpContext.User has no email info in it:

![2020-04-28_122750](https://user-images.githubusercontent.com/4499997/80444119-d22df080-894b-11ea-9293-5db3a9ae9a08.png)

My Access_token type is reference token, The Data field in DataTable `IdentityServerPersistedGrants` like this:

```json

[{
	"Type": "client_id",
	"Value": "SchoolSite",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}, {
	"Type": "scope",
	"Value": "openid",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}, {
	"Type": "scope",
	"Value": "profile",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}, {
	"Type": "scope",
	"Value": "questionniare",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}, {
	"Type": "scope",
	"Value": "schoolsitegateway",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}, {
	"Type": "sub",
	"Value": "716cc26d-de3e-a647-70d8-39f4c7b19845",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}, {
	"Type": "auth_time",
	"Value": "1587896193",
	"ValueType": "http://www.w3.org/2001/XMLSchema#integer64"
}, {
	"Type": "idp",
	"Value": "local",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}, {
	"Type": "amr",
	"Value": "pwd",
	"ValueType": "http://www.w3.org/2001/XMLSchema#string"
}], "Version": 4
}
```

Also no email info in database.

If I call id4's userinfo endpoint via access_token. I can get username, email info:

```csharp

GET http://localhost:24617/connect/userinfo

Authorization  Bearer zS_BRllqnjph9J_yWE7d74xhRQmBhn4Q_baNQCTbaM0

response is :

{
    "sub": "618ac26f-c474-5708-8bd3-39f4c7b19845",
    "preferred_username": "rio.shi@grapecity.com",
    "name": "rio.shi@grapecity.com"
}

```

So, I want to know, What's the right way to get user info claims in abp micro services's backend?

Extend acess_token's claims to include custom info, or just call userinfo endpoint ?

Regards.

**Comment by maliming** [comment]
Generally, the access_token issued by the identity server should contain many claims of user information. jwt token and reference tokens are the same.

You can troubleshoot the problem at this point, because your project is more complicated, it is difficult to directly find the problem.

**Comment by shikelong** [comment]
Thank you
