### ISSUE TITLE
.CSHTML override invalid when an app run in Linux + Docker + Production env.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#3766]
![image](https://user-images.githubusercontent.com/30018771/80467693-c99be100-8970-11ea-88c2-b11207f3d91c.png)
```
...
        <abp-modal-body>
            Hello
            <abp-form-content/>
        </abp-modal-body>
...
```
I overrode a .CSHTML file, when I run the web project in Windows locally (tried: debug/release, production/development), it works:
![image](https://user-images.githubusercontent.com/30018771/80467951-28f9f100-8971-11ea-9386-1e9b79790780.png)
But when I published it to the formal environment: Linux + Docker + Production env, the inserted text "Hello" cannot be found in the create modal.

I created a repository to show my usage:
https://github.com/gdlcf88/ModuleOverrideTest

**Comment by maliming** [comment]
Try to test the application after publishing it locally (windows).

**Comment by gdlcf88** [comment]
> Try to test the application after publishing it locally (windows).

I tried published .dll file locally (Win10), it **can be** reproduced.

And I tried to replace the login page following the [example](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#example-1), the problem **can be** reproduced too.

**Comment by maliming** [comment]
Try this demo.

https://github.com/maliming/LoginPageDemo/blob/master/src/LoginPageDemo.Web/Pages/Account/Login.cshtml

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/80477289-45505a80-897e-11ea-9674-e83cf17bdfac.png)
It works in this demo.

**Comment by gdlcf88** [comment]
I think it is because I did not add this configuration:
```
            Configure<AbpVirtualFileSystemOptions>(options =>
            {
                options.FileSets.AddEmbedded<ModuleOverrideTestWebModule>("ModuleOverrideTest.Web");
            });
```

Hi @maliming, could you please tell me why the AbpVirtualFileSystemOptions is not configured by default in the startup template? thx.

**Comment by maliming** [comment]
> why the AbpVirtualFileSystemOptions is not configured by default in the startup template?

The startup template does not use the [virtual file system](https://docs.abp.io/en/abp/latest/Virtual-File-System) by default.

**Comment by gdlcf88** [comment]
Overriding a CSHTML file may not need VFS after this PR merged: https://github.com/abpframework/abp/pull/4016
