### ISSUE TITLE
Create simplest Microservice startup template

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#377]
- [x] Create the template.
- [x] Create a sample API.
- [x] Create IdentityServer4 host application.
- [x] Create a console application that authorizes and uses the sample API.
- [x] Configure IdentityServer4 for authentication.
- [x] Create template downloading for this new template.

**Comment by natiki** [comment]
@hikalkan has the documentation caught up for this change? Is this the "ASP NET Core API Module (without UI)" on https://abp.io/Templates?

**Comment by hikalkan** [comment]
Yes. But there is no documentation yet.
