### ISSUE TITLE
ErrorHandler is not exported in public-api.ts of ThemeSharedModule

### ISSUE THREAD

**Issue by pn-william** [abpframework/abp#3772]
Hi! 
I tried to reuse the the class [ErrorHandler](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/theme-shared/src/lib/handlers/error.handler.ts) in the module ThemeSharedModule from my front-end application. I'm using Zorro(another UI library based on angular) instead of using the module @abp/ng.theme.basic to build my font-end. My front-end does depend on ThemeSharedModule  in order to reuse some basic infrastructure like class ErrorHandler  in ThemeSharedModule  .

But I'm running into the following problem,

**Obstacle**
The class ErrorHandler is not exported in the file [public-api.ts](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/theme-shared/src/public-api.ts)

Given that, there is no way for me to import ErrorHandler  into my own application.

**Expected Behavior**
Add the new line in public-api.ts of the module ThemeSharedModule
`export * from './lib/handlers';`

Look forward to your feedback soon.

**Comment by mehmet-erim** [comment]
Hi,
Thanks for reporting. It will be exported from the `public-api`.

**Comment by kenan0122** [comment]
httpErrorConfig's property errorScreen not work
