### ISSUE TITLE
Memory leak after upgrading ABP

### ISSUE THREAD

**Issue by aerkol** [abpframework/abp#3778]
Hi guys,

We have been developing a blockchain platform based on ABP framework and everything was fine until we tried to upgrade to latest ABP packages recently.

We skipped a few versions after ABP 1.1.2 but when we upgraded to 2.2.1, we noticed that our application's memory usage was growing abnormally until the server runs out of memory. Recently, we upgraded ABP to 2.6.2 and we still observe the same memory issue. With ABP 1.1.2, we don't have any memory issues so this happens only when we upgrade.

For troubleshooting, I saved our application's memory dump via coredump and checked the object stats with lldb and I noticed that majority of memory is used by `Autofac.Extensions.DependencyInjection.AutofacServiceProvider` objects:

![image](https://user-images.githubusercontent.com/44253196/80564905-ba28a080-8a21-11ea-9b9a-0773b44447d7.png)

When I check the stats only for this type, I see below:

![image](https://user-images.githubusercontent.com/44253196/80565685-ab42ed80-8a23-11ea-9ed6-46762444e9f0.png)

When I look at these objects one by one, this is what I see for most of them:

![image](https://user-images.githubusercontent.com/44253196/80566080-b21e3000-8a24-11ea-9ce0-999be6f678f6.png)

I am not sure what is causing those many objects created and not disposed, so I am a bit lost troubleshooting on this issue. I just wanted to write here to check whether you have any opinion on what could be causing this issue or whether you have any advice on where to look at, that would be great help.

Simdiden cevabiniz icin tesekkur eder, hepinize bol saglik ve guclu bagisikliklar dilerim :)

**Comment by liangshiw** [comment]
Can you explain it in detail and share the dump file?

**Comment by aerkol** [comment]
Hi Liangshiw,

The issue arises after we upgrade ABP from 1.1.2 to a later version, that we first noticed 2.2.1 and same with 2.6.2.

Our code base is here if you want to have a look, the project that is to launch the application is AElf.Launcher:

https://github.com/AElfProject/AElf
https://github.com/AElfProject/AElf/blob/dev/src/AElf.Launcher/Program.cs

The PR we attempted to fix the issue:

https://github.com/AElfProject/AElf/pull/2536

You can download the memory dump from below links:

http://www.dosyapaylas.com/coredump_20200427.gz
http://www.dosyapaylas.com/coredump_20200429.gz

**Comment by liangshiw** [comment]
Can you provide dump files supported by dotmemory tool?

**Comment by aerkol** [comment]
@liangshiw 

Thank you for your response.

I will need some time to reproduce this in Windows OS (as dotmemory only runs in Windows), currently we use Ubuntu in our test environment and the memory dump was created with coredump and can be opened with lldb & sos plugin... So I don't have a dump compatible with dotmemory yet with this issue present.

Creating a simple project to reproduce this problem is not possible because I am unclear what causes this issue and our project is very large, I will check with my team on this. The only thing we know as of now is that this issue only happens after upgrading ABP.

I will update you here if I have any of above, meanwhile it would be very helpful if you have any experience what can potentially cause the issue we are experiencing. It may be due to a misuse in our code but not sure why it doesn't happen with an older version of ABP.

Certainly something has changed and we need to fix or update our code...

**Comment by Ly2630039223** [comment]
> Hi guys,
> 
> We have been developing a blockchain platform based on ABP framework and everything was fine until we tried to upgrade to latest ABP packages recently.
> 
> We skipped a few versions after ABP 1.1.2 but when we upgraded to 2.2.1, we noticed that our application's memory usage was growing abnormally until the server runs out of memory. Recently, we upgraded ABP to 2.6.2 and we still observe the same memory issue. With ABP 1.1.2, we don't have any memory issues so this happens only when we upgrade.
> 
> For troubleshooting, I saved our application's memory dump via coredump and checked the object stats with lldb and I noticed that majority of memory is used by `Autofac.Extensions.DependencyInjection.AutofacServiceProvider` objects:
> 
> ![image](https://user-images.githubusercontent.com/44253196/80564905-ba28a080-8a21-11ea-9b9a-0773b44447d7.png)
> 
> When I check the stats only for this type, I see below:
> 
> ![image](https://user-images.githubusercontent.com/44253196/80565685-ab42ed80-8a23-11ea-9ed6-46762444e9f0.png)
> 
> When I look at these objects one by one, this is what I see for most of them:
> 
> ![image](https://user-images.githubusercontent.com/44253196/80566080-b21e3000-8a24-11ea-9ce0-999be6f678f6.png)
> 
> I am not sure what is causing those many objects created and not disposed, so I am a bit lost troubleshooting on this issue. I just wanted to write here to check whether you have any opinion on what could be causing this issue or whether you have any advice on where to look at, that would be great help.
> 
> Simdiden cevabiniz icin tesekkur eder, hepinize bol saglik ve guclu bagisikliklar dilerim :)

can you tell me this problem how to solve?
