### ISSUE TITLE
SQL column projections in IQueryalbe (.ProjectTo<T>() in AutoMapper.QueryableExtensions)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#378]
It would be nice to make projections while EF (Core) does not "hit" database.

Example (RoleAppService.cs):

Original
```
public async Task<ListResultDto<RoleListDto>> GetRoles(GetRolesInput input)
{
    var roles = await _roleManager
        .Roles
        .WhereIf(
            !input.Permission.IsNullOrWhiteSpace(),
            r => r.Permissions.Any(rp => rp.Name == input.Permission && rp.IsGranted)
        )
        .ToListAsync();

    return new ListResultDto<RoleListDto>(ObjectMapper.Map<List<RoleListDto>>(roles));
}
```

Better
```
public async Task<ListResultDto<RoleListDto>> GetRoles(GetRolesInput input)
{
    var roles = await _roleManager
        .Roles
        .WhereIf(
            !input.Permission.IsNullOrWhiteSpace(),
            r => r.Permissions.Any(rp => rp.Name == input.Permission && rp.IsGranted)
        )
        .ProjectTo<RoleListDto>() // PROJECTION
        .ToListAsync();

    return new ListResultDto<RoleListDto>(roles);
}
```

There is basically no performance hit if List (or FirstOrDefault()/First()) is small.

But I have a scenario that we have approx 58.000 items in a list (and database table has a lot of columns).
Before using .ProjectTo<T>(), API request finished after **approx. 37 seconds**. After adding just .ProjectTo<T>() at the end of IQueryable, this same request (with the same data) now takes **approx. 250-400ms**.

There are a lot of places where can described projection simply be added to the code.

As I said, it's not something big for "bare" application framework, but because it's so easy to add projection in IQueryable, that is literally a no-brainer for not doing this.

In case of "classic C# List", you can benefit even more, because you have:
- just one mapping (instead of two)
- one line less of code
- ...

Example (TenantAppService.cs):

Original
```
var tenants = await query.OrderBy(input.Sorting).PageBy(input).ToListAsync();

    return new PagedResultDto<TenantListDto>(
        tenantCount,
        ObjectMapper.Map<List<TenantListDto>>(tenants)
        );
```

Better
```
var tenants = await query.OrderBy(input.Sorting).PageBy(input).ProjectTo<TenantListDto>().ToListAsync();

    return new PagedResultDto<TenantListDto>(
        tenantCount,
        tenants
        );
```

What do you think?

**Comment by hikalkan** [comment]
Hi,

This has no use case for the framework. However, we can consider it for modules & applications developed on the framework. While most of the code does not work with huge data, we can use it while working with too many rows.

So, not it's nothing todo. I'm adding this to backlog, so we can think it later.

**Comment by leonkosak** [comment]
Ok, no problem.
