### ISSUE TITLE
Can I use difference Login view for clients?

### ISSUE THREAD

**Issue by shikelong** [abpframework/abp#3782]
I have a Auth Server user Abp Account/Identity/IdentityServer Module. 

And I has a Desktop SPA Client and a Mobile SPA Client. I hope they has different login view. 

Can Abp Support it? 

Thanks.

**Comment by maliming** [comment]
You can try customize the Login page and LoginPageModel.

https://docs.abp.io/en/abp/latest/How-To/Customize-Login-Page-MVC
