### ISSUE TITLE
DevExpress (DevExtreme) custom localization (also for other localizations)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#379]
DevExpress lacks many translations and localizations.
Consider creating folder(s) outside node_modules.
**Workflow in code**
If translation (and localization) files are not found in "node_modules" (or other package manager folder), look into custom localization folder (fallback).

This concept has an advantage that you can't override or lose custom translations/localizations for components like DevExpress.
In case of an upgradeable framework, you know that custom translations/localizations folder should not be deleted or replaced.

**Comment by bbakermmc** [comment]
For devexpress you need to implement their own localization
https://js.devexpress.com/Documentation/16_1/Guide/UI_Widgets/Common/Localization/

**Comment by hikalkan** [comment]
Hi,

I don't know what to do about that issue. If the request is translating devexpress components, it's not our job. I'm closing this, but continue to discuss if there is any value for ABP about that.
