### ISSUE TITLE
cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.

### ISSUE THREAD

**Issue by Meowv** [abpframework/abp#3795]
My entity inherits: `Entity<Guid>`, at this time the primary key is protected. Can't assign value to it?

When I insert data in bulk, the following exception is reported.

System.InvalidOperationException: The instance of entity type 'Wallpaper' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

System.InvalidOperationException: The instance of entity type 'Wallpaper' cannot be tracked because another instance with the key value '{Id: 00000000-0000-0000-0000-000000000000}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

what should I do ??

**Comment by maliming** [comment]
> My entity inherits: Entity<Guid>, at this time the primary key is protected. Can't assign value to it?

Use the entity's constructor.

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUser.cs#L137

**Comment by Meowv** [comment]
Thanks Reply.

Adding the following code solves.
```C#
b.Property(x => x.Id).ValueGeneratedOnAdd();
```
