### ISSUE TITLE
Removing unused CSS

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#380]
Bootstrap 4 and Metronic theme are large libraries and mot CSS rules are not used in finished applications in production.
Consider using **PurifyCSS** (https://github.com/purifycss/purifycss), **UnCSS** (https://github.com/uncss/uncss) or **Purgecss** (https://github.com/FullHuman/purgecss) as pipe at build time (WebPack).

https://stackoverflow.com/questions/37007814/difference-between-uncss-and-purifycss

My preferred choice would PurifyCSS, because original CSS files stay untouched.

**Comment by hikalkan** [comment]
Thanks for the suggestion. Will think on that later. Added to the backlog.

**Comment by hikalkan** [comment]
Hi,

We can apply this. Because, this can not be known on development or deploy time since ABP allows plugin modules those may use a css class which is not used by the application. These tools can only works statically.
