### ISSUE TITLE
How to a module that accesses existing data - No migrations necessary

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#3803]
Hi,

Is it possible with ABP, to add a module that accesses existing data without any need for migrations?

How is it done?

Thanks for your awesome product!

**Comment by liangshiw** [comment]
Hi ,
I don't think unnecessary  to add such a template, you simply need to change the connection string to the existing database.

**Comment by tinonetic** [comment]
Thank-you for responding.

Does it have to have ABP tables? What if for that module, I do not want the standard ABP tables? Just my own

**Comment by liangshiw** [comment]
Application module  only has its own table. You can refer to Abp [pre-built modules](https://github.com/abpframework/abp/blob/dev/modules).
