### ISSUE TITLE
Where is the DbMigrator when you run "abp new Acme.BookStore -t module --no-ui"

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#3804]
Hi,

I created a new module using CLI(https://docs.abp.io/en/abp/latest/CLI#options) and tried to run the "...Http.Api.Host" project.

It is complaining that it cannot find tables that seem to be system tables

For example:

> 2020-04-30 11:23:21.878 +02:00 [ERR] Invalid column name 'ConcurrencyStamp'.
> Invalid column name 'ExtraProperties'.
> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'ConcurrencyStamp'.
> Invalid column name 'ExtraProperties'.

It did not generate a **DbMigrator** project. What could I be missing here?

Thanks in advance for your help!

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Startup-Templates/Module

**Comment by liangshiw** [comment]
1. Set `host/YourProjectName.Web.IdentityServer` as the startup project and PMC default project, run Update-Database command
2. Set `host/YourProjectName.HttpApi.host` as the startup project and PMC default project, run Update-Database command

**Comment by tinonetic** [comment]
@liangshiw Thank-you for responding. What is PMC?

**Comment by tinonetic** [comment]
Ok, I figured it out. Package manager console. Do I still need the IdentityServer if it becomes a second module to a MicroService solution?

**Comment by liangshiw** [comment]
Do you check the [Module documentation](https://docs.abp.io/en/abp/latest/Startup-Templates/Module)?
