### ISSUE TITLE
repository pattern with ado.net

### ISSUE THREAD

**Issue by RyanOvO** [abpframework/abp#3813]
Hi, Ado.net can implement data access based on the Repository module in ABP.
like ef core，memory db.

**Comment by liangshiw** [comment]
Can you explain it in detail?

**Comment by RyanOvO** [comment]
> Can you explain it in detail?

Implement repository using ado.net.
Not ORM.

**Comment by liangshiw** [comment]
I think there is no such plan for the abp framework ,you can use dapper integration or implement ado.net integration yourself
