### ISSUE TITLE
Theme management module

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#3817]
on the blog module
Allow tenants to set default themes
Allow users to upload themes, change themes

**Comment by liangshiw** [comment]
Hi，
Currently ABP modules cannot be dynamically loaded at runtime.
The switching theme is already provided in the [pro template](https://commercial.abp.io/startup-templates), you can use the [pro template](https://commercial.abp.io/startup-templates) or implement these features yourself.

**Comment by xewn** [comment]
The pro template only allows the selection of themes and cannot upload themes. Nor can there be users uploading their own themes.

**Comment by hikalkan** [comment]
Uploading a theme on the fly is not possible and not planned to implement. However, you can select among installed themes by implementing the `IThemeSelector` interface. See the default implementation: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI/Volo/Abp/AspNetCore/Mvc/UI/Theming/DefaultThemeSelector.cs
