### ISSUE TITLE
CODE Documentation

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#382]
https://visualstudiomagazine.com/articles/2017/02/21/vs-dotnet-code-documentation-tools-roundup.aspx

Swagger is just for documenting API. Code documentation is also important. 

DocFX: https://dotnet.github.io/docfx/
("Compatible" with Swagger: https://dotnet.github.io/docfx/tutorial/intro_rest_api_documentation.html)

https://github.com/RaynaldM/autohelp

My point is that the application framework needs additional documentation that is currently provided with Swagger (which is important for "external" users).

**Comment by danielmeza** [comment]
@leonkosak I agree with you, further more, the swagger implementation its not complete, cause the documentation code are not mapped to the generated controller when service are exposed throw the api.

So if something is done for this it should keep the c# documentation standard and avoid the use of custom attributes to document the code, and use the attributes only for stuffs that can't be described with the code documentation.
