### ISSUE TITLE
Question : Blazor DataAnnotation Validation - Localization

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#3822]
Hi,

I'm currently using a mix of ABP & Blazor, I use an EditForm with some data annotation and data validation.

The problem is that the error message is english only, is there a way to connect it to th abp localization ?

```
    public class UserTestModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The firstname must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        public string FirstName { get; set; }
    }
```

**Comment by liangshiw** [comment]
Can you provide complete steps to reproduce the problem?

**Comment by maliming** [comment]
This requires Blazor to support `DataAnnotations localization` similar to asp net core.


https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#dataannotations-localization
