### ISSUE TITLE
ES-MX translation needs updating

### ISSUE THREAD

**Issue by LuisPignataro** [abpframework/abp#3832]
Some entries are missing from the file. One might consider keeping only one es.json file for Spanish.

https://github.com/abpframework/abp/blob/0fa5346e7f2a2e154b69aa9739ab52b5ef73f16b/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/Resources/es-mx.json#L4

**Comment by hikalkan** [comment]
Keeping only a single file breaks modularity, sorry for that :(
It is appreciated if you could fill the mssing texts.

**Comment by LuisPignataro** [comment]
I mean use a file for Spanish in general, instead of es.json and es-MX.json, logically for each module.

**Comment by hikalkan** [comment]
Hmmm... I prefer es.json but currently I don't know if es-MX files contains mexican specific texts. I am not Spanish, so you Spanish guys find a solution for it 😄
