### ISSUE TITLE
Consider changing authentication flow for client side apps (Angular/React)

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#3833]
Currently, angular app uses **RO** flow which has its own login page and accessing to resources via jwt signed by IdentityServer.
Loging in to angular apps doesn't sign in the user to identityServer hence user can not logout aswell.

We should consider changing the flow to **implicit**, letting identityserver handle the sign-in and sign-out process as it does for MVC apps.

Comparing to mvc apps (hybrid flow) there should be a few more effort required for implementing extra feature like **silent renew** which refreshes the access token.

**Comment by hikalkan** [comment]
Closed. Will be discussed and tracked internally. We'll create an issue later if needed.

**Comment by olicooper** [comment]
Related? https://github.com/abpframework/abp/issues/4492
