### ISSUE TITLE
EF Core Read/Write Separation

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#3838]
Hello,
I am currently working on a project which will use a PostgreSQL cluster.

There will be a primary node which will be used for read/write operations and many standby nodes for faster read-only operations. This means I will have to use different connection strings based on my query type.

While searching on how this could be done with .NET I came across this EF Core issue: https://github.com/dotnet/efcore/issues/6525. This allows to change the connection string of a DbContext instance. I also noticed that by pure coincidence @ismcagdas already looked into this :)

The related EF Core API has been created already, but is sadly only available on .NET 5 Preview 1 onwards.

I assume there is no way to get this working until .NET 5 releases and ABP upgrades to it? How would the related ABP API look like? What's the latest state on this?

**Comment by liangshiw** [comment]
ABP provides the `IReadOnlyRepository` interface,but it only removes the `insert`, `delete` and `update` methods.

Just suggest :

You can customize the implementation of `IReadOnlyRepository` interface and use a read-only database server connection string.

**Comment by hikalkan** [comment]
Use IReadOnlyRepository, override SaveChangesAsync on your dbcontext and throw exception if the change tracker has any entity changed 😃
