### ISSUE TITLE
Navigation - DB Driven

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#384]
It would be ideal to allow for tenant admins to "customize" or add their own navigation nodes w/out having to do it in code.  Maybe along the same lines as roles, where you can create "static" ones and they can maybe just change the text/position, and then allow them to create new ones that are feature/permission dependent.

**Comment by hikalkan** [comment]
This is one of the features we definitely want to develop. Menu should be customizable per user/tenant (re-order menu items, hide menu items, mark menu items as favorite and so on...).

**Comment by KidoPlay** [comment]
Remember seeing this while using XAF framework (DevExpress eXpressAppFramework).
Menu and layout are stored in DB/XML.
Filters while doing query are also stored dynamic.
This is a good feature.

**Comment by hikalkan** [comment]
Most similar feature currently available is CMS Kit menu: https://docs.abp.io/en/abp/latest/Modules/Cms-Kit/Menus
