### ISSUE TITLE
How to Specify Database Schema for Modules

### ISSUE THREAD

**Issue by kbowma** [abpframework/abp#3844]
I have a requirement to use database schema for all tables (not dbo.). I have tried to use the following in `<my app>DbContext.cs` with no luck:
```
            builder.Entity<BackgroundJobInfo>(b =>
            {
                b.ToTable("AbpBackgroundJobs", "Application");
                b.ConfigureByConvention();
            });
```
What do I need to do to implement schemas for all tables in the database?

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/blob/10313cf02c04b9b813fcd2d25913e80198b54733/framework/src/Volo.Abp.Data/Volo/Abp/Data/AbpCommonDbProperties.cs

**Comment by kbowma** [comment]
Thank you for the quick response. I saw this but my requirement specifies that schemas are based on module (area of app), and therefore, all the Abp tables will not have the same schema. I need to be able to specify at the table level its schema.

**Comment by liangshiw** [comment]
Each module has DbProperties class, like :

https://github.com/abpframework/abp/blob/10313cf02c/modules/feature-management/src/Volo.Abp.FeatureManagement.Domain/Volo/Abp/FeatureManagement/FeatureManagementDbProperties.cs

You can set prefixes like:

`FeatureManagementDbProperties.DbTablePrefix = "MyPrefix";`
