### ISSUE TITLE
can't mapper using objectMapper

### ISSUE THREAD

**Issue by 1259724620** [abpframework/abp#3849]
```csharp
public class ApplicationServiceModule:AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpAutoMapperOptions>(options =>
            {
                options.AddProfile<HqhProjectAutoMapperProfile>(validate: true);
            });
        }
    }
 /// <summary>
    /// 实体与Dto映射关系
    /// </summary>
    public class HqhProjectAutoMapperProfile : Profile
    {
        /// <summary>
        /// 
        /// </summary>
        public HqhProjectAutoMapperProfile()
        {
            CreateMap<AddEditUserDto, User>().ForMember(f=>f.Password,opt=>opt.Ignore()).ForMember(f=>f.LastLoginTime,opt=>opt.Ignore());
            CreateMap<User, UserDto>();
        }
    }

servevice code:
var entity = ObjectMapper.Map<AddEditUserDto, User>(input);
entity.Password = EncryptionPwd(_option.InitPassword);
await _userRepository.InsertAsync(entity);

**Comment by liangshiw** [comment]
Can you explain in detail?

**Comment by NecatiMeral** [comment]
Your `ApplicationServiceModule` requires `[DependsOn(typeof(AbpAutoMapperModule))]`

**Comment by 1259724620** [comment]
ApplicationServiceModule has [DependsOn(typeof(AbpAutoMapperModule))],as below:
[DependsOn(typeof(ApplicationContractModule))]
    [DependsOn(typeof(EntityFrameCoreModule))]
    [DependsOn(typeof(AbpAutoMapperModule))]
    [DependsOn(typeof(CommonModule))]
    public class ApplicationServiceModule:AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpAutoMapperOptions>(options =>
            {
                options.AddProfile<HqhProjectAutoMapperProfile>(validate: true);
            });
        }
    }

**Comment by 1259724620** [comment]
> Can you explain in detail?
I configure by official documation,but mapper throw exception as bellow:
Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Volo.Abp.Application.Services.ApplicationService.LazyGetRequiredService[TRef](Type serviceType, TRef& reference)
   at Volo.Abp.Application.Services.ApplicationService.LazyGetRequiredService[TService](TService& reference)
   at Volo.Abp.Application.Services.ApplicationService.get_ObjectMapper()
   at hqh.project.Application.Services.Services.UserService.<AddEditUser>d__3.MoveNext() in E:\test\hqh.project\hqh.project\hqh.project\hqh.project.Application.Services\Services\UserService.cs:line 46

**Comment by liangshiw** [comment]
Please use cli to create simple project to reproduce this problem.

**Comment by 1259724620** [comment]
> Please use cli to create simple project to reproduce this problem.

I create project by Manual，er....
