### ISSUE TITLE
How to make data annotation message international?

### ISSUE THREAD

**Issue by shikelong** [abpframework/abp#3852]
Hi, I am using abp's account model in japanese.
I know abp provider localization message in `/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/Localization/`

But there are no ja /ja-JP json. Can I extend japanese to Abp's Localization resource or completely assign my message by overider the login model just like this?

```csharp

public class CustomLoginInputModel
{
            [Required(ErrorMessage = "ユーザー名は空にできません")]
            [StringLength(IdentityUserConsts.MaxEmailLength)]
            public string UserNameOrEmailAddress { get; set; }
}
```

**Comment by liangshiw** [comment]
Hi shikelong,

Here is validation localization files
https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Validation/Volo/Abp/Validation/Localization.

You can [extending existing resource](https://docs.abp.io/en/abp/latest/Localization#extending-existing-resource) .  But if you want you can contribute Japanese localization files : )

**Comment by shikelong** [comment]
Thank you!
