### ISSUE TITLE
How to get actionName in AbpInterceptor

### ISSUE THREAD

**Issue by hieutns96** [abpframework/abp#3858]
Hi, 

I'm facing a problem when implementing a custom Interceptor. When I Intercept from a AbpController I want to get the ActionName but I only got the ActionExcutedFilter name example "OnActionExcuted" instead of my ActionName. How can I get the ActionName on this case?

Many thanks

**Comment by liangshiw** [comment]
Use `IAsyncActionFilter` instead of `AbpInterceptor `.
