### ISSUE TITLE
Consider to separate background tasks to another application for tiered startup solutions

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3859]
For tiered solutions, there will be two applications at least. In this case, we may consider to create another application (a console app?) that executes the background jobs and disable job execution for other applications.

**Comment by abdumostafa** [comment]
Any updates regarding this issue ?

**Comment by hikalkan** [comment]
That will be overhead for most developers. They already find the tiered structure complicated ( yet I don't know why they are selecting tiered if so :)) ). Anyway, it would be interesting if we can write an ABP community article that explains what is the advantage of doing it and how to do. I will plan it. Closing this issue now.
