### ISSUE TITLE
[docs] Creation of a deployment guide?

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3862]
Deploying Abp to a production environment has additional steps beyond deploying a basic AspNetCore application. For example, the multi-tenancy documentation specifies adding [additional headers for nginx](https://docs.abp.io/en/abp/latest/Multi-Tenancy#determining-current-tenant-from-web-request), which isn't specified in [Microsoft's deployment guide](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1).

Additionally, it is not clear how to configure [(EntityFramework based) DataProtection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio#entity-framework-core) with abp's module system.

It might be worth creating a guide which explains how to deploy to Linux and Docker which consolidates all of the steps in one guide and provides links to external material for any other steps.

**Comment by volethanh** [comment]
I also stuck in cannot login with identityserver and till now it cannot be resolved although it 's posted to Support forums :(

**Comment by hikalkan** [comment]
I created an issue for the EF Core: https://github.com/abpframework/abp/issues/3890

We also will consider to create deployment guides. thanks.

**Comment by staticcat** [comment]
Any suggested reading material on how to correctly deploy abp.io from a startup installation? I am currently reading the source code for the microservices architecture and reversing the method used in there for deploying. Is there something that can be shared with regards to how the doco / abp.io sites are deployed?

**Comment by yerz** [comment]
> I also stuck in cannot login with identityserver and till now it cannot be resolved although it 's posted to Support forums :(

hi~,I wonder if you have solved the IdentityServer login problem, I have been unable to login :(

**Comment by Wiblox** [comment]
@hikalkan  Hello,
Do you think you can add the deployment guide for 5.2?


I do think it is necessary documentation.

**Comment by hikalkan** [comment]
We have now deployment guides: https://docs.abp.io/en/abp/latest/Deployment/Index (we hope to improve them by the time).
