### ISSUE TITLE
activate location when I use data annotation

### ISSUE THREAD

**Issue by erojasd** [abpframework/abp#3863]
Hello,

I am working with Data Annotations"for validations in the dto. Based on what I read in the documentation, abp automatically validates and sends the location-based message, but this doesn't work for me.
I checked if the localization files are in the abp project, it is Spanish to check if they actually existed and it was so.
What do I have to do to activate the translations in Data annotation?

This is an example of the response when the system performs a validation.
`{
  "error": {
    "code": null,
    "message": "Su pedido no es válido!",
    "details": "Los siguientes errores se encontraton durante la validación.\r\n - The field NameAbbrev must be a string with a maximum length of 64.\r\n",
    "validationErrors": [
      {
        "message": "The field NameAbbrev must be a string with a maximum length of 64.",
        "members": [
          "nameAbbrev"
        ]
      }
    ]
  }
}`

**Comment by aklscv** [comment]
Try upgrading to ABP 2.7. I had the problem and it went away after the upgrade.

**Comment by hikalkan** [comment]
Maybe it is related to this change: https://github.com/abpframework/abp/issues/3739

Are other validation attributes correctly localized?

**Comment by erojasd** [comment]
only occurs in validations with data annotation.
I also tried to update abp to version 2.7 and the problem persists

**Comment by maliming** [comment]
hi @erojasd 
Please share the steps to reproduce the problem.

**Comment by hikalkan** [comment]
Could not repeat it. For example, it works for Portugal language:

![image](https://user-images.githubusercontent.com/1210527/83303390-a7161580-a205-11ea-8239-678057106b25.png)

Please re-open the issue if you need, but share the steps to reproduce the problem.
