### ISSUE TITLE
How to implement paging in client side angular UI so that first 10 items in page1, next 10items in page2 of the BookStore Sample App.

### ISSUE THREAD

**Issue by ManiSJ** [abpframework/abp#3866]

**Comment by armanozak** [comment]
Hi @ManiSJ,

First of all, thank you for your question and patience.

Upon your question, we have realized that it is not obvious or easy to implement pagination, sorting, and search in an entity list page. We have developed the `ListService` that will help anyone who needs to introduce them to a page quickly and efficiently. The PR of this feature, #3956, has been merged to the main branch.

You can see the documentation of the new `ListService` [here](https://github.com/abpframework/abp/blob/dev/docs/en/UI/Angular/List-Service.md). We believe it is clear and concise. The feature will be released within less than a week. Nevertheless, if you have an urgent need and cannot for the next version, you may review the PR and check how we have implemented the pagination. 

If you think your question is not resolved, please feel free to reopen the issue.

Cheers!
