### ISSUE TITLE
Angular UI How to add new column to user list

### ISSUE THREAD

**Issue by BlackNinja1903** [abpframework/abp#3874]
I extended current AppUser Entity with a property in my project by following related abp document(https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities) . 
But I don't know how to show this column in core user module. Is there a way to do this without replace the core user component?

![image](https://user-images.githubusercontent.com/17542728/81401833-cfe04900-9138-11ea-8840-aaee251621c5.png)

Abp Version => 2.6.2

**Comment by hikalkan** [comment]
This feature is currently available for the [ABP Commercial](https://commercial.abp.io/) (see https://docs.abp.io/en/commercial/latest/guides/module-entity-extensions).

We will consider to bring it to the ABP Framework modules too in the next versions.

**Comment by BlackNinja1903** [comment]
> This feature is currently available for the [ABP Commercial](https://commercial.abp.io/) (see https://docs.abp.io/en/commercial/latest/guides/module-entity-extensions).
> 
> We will consider to bring it to the ABP Framework modules too in the next versions, but we don't promise about that.

Thanks for quick response. I already have the commercial version and read all the documentation but assume that it was missed, sorry for that. Could it be possible that this link you've sent, is not located in documentation tree? 

And May I ask a question related to that topic. Is it also possible to add a navigational property to the user component. Currently i took care of it by a workaround solution over abp suite.

**Comment by hikalkan** [comment]
>Could it be possible that this link you've sent, is not located in the documentation tree yet?

Oh, yes it is not on the document three. This is the related item on the tree: https://docs.abp.io/en/commercial/latest/guides/customizing-modules

We will add this to the document tree, I thought it was unnecessary but now I see it is needed. Thanks.

>And May I ask a question related to that topic. Is it also possible to add a navigational property to the user component. Currently i took care of it by a workaround solution over abp suite.

This is a feature in our roadmap.

You've two options now:

* Override the edit/create modal to implement it yourself (https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#overriding-a-page)
* Create an entity action (https://docs.abp.io/en/commercial/latest/ui/aspnetcore/entity-action-extensions) then open another modal to edit this navigation property separated from the main edit/create operation.

**Comment by hikalkan** [comment]
BTW, please ask ABP Commercial questions to the [support forum](https://support.abp.io/) (we don't want to distrub the open source community :)
