### ISSUE TITLE
How to add additional filters to PagedResultDto/PagedAndSortedResultRequestDto ?

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#3876]
Hi,

Today, we can use PagedAndSortedResultRequestDto/PagedResultDto to get a list of entities.

It is fine, but how can I add additional conditions/filters ?

By example, in the CrudAppService I can have such method "GetListAsync", but I'm looking for filtering based on geolocation, or name, or datetime etc ?

Is it possible today ? (Without retreiving everything and then filtering, I have millions of data)

**Comment by liangshiw** [comment]
You can create a new class that inherits from `PagedAndSortedResultRequestDto` , and override `CreateFilteredQuery` method.
