### ISSUE TITLE
Application Development Tutorial using Visual Studio for Mac

### ISSUE THREAD

**Issue by muharihar** [abpframework/abp#3881]
Hi Team,

Got an awesome Application Development Tutorial using Visual Studio for Windows!
```
https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=NG
```

Any roadmap for Application Development Tutorial using Visual Studio for Mac?
I think it's would be attracting a  huge Mac Developer Community to using ABP!

Thank you so much!

**Comment by hikalkan** [comment]
Thank you @muharihar for your suggestion. Is it really much different? Can't you follow the tutorial while using VS for Mac? What are the main differences you see? I am asking since I'm not VS for Mac user and I try to understand if it is really different.

**Comment by evenlee** [comment]
I've been use ABP and Mac for at least 1 year, the new abp works well on Mac, but visual studio for Mac is not powerful as its Windows version, but good to use.
the only thing bothered me is the unit tests  cannot show up in the unit test section, which you may need other members who use windows for a run.

**Comment by hikalkan** [comment]
I am using JetBrains Rider for a month and I never return back to the Visual Studio. Rider is fast and stable. Try it.

I am closing this issue since we can't duplicate the tutorial for different IDEs.
