### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by zaktecs** [abpframework/abp#3887]
I started getting the following error after migrating version 2.7 when I try to login
thanks
An unhandled exception occurred while processing the request.
AbpException: Could not find the bundle file '/libs/abp/utils/abp-utils.umd.min.js' from IWebContentFileProvider
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(TagHelperContext context, TagHelperOutput output, List<BundleTagHelperItem> bundleItems, string bundleName)

Stack Query Cookies Headers Routing
AbpException: Could not find the bundle file '/libs/abp/utils/abp-utils.umd.min.js' from IWebContentFileProvider

**Comment by liangshiw** [comment]
Please use CLI`update` command to update version.
If you still have this problem, you can copy the files to your project. See https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/wwwroot/libs
