### ISSUE TITLE
Feature - API Rate Limits

### ISSUE THREAD

**Issue by bbakermmc** [abpframework/abp#389]
https://github.com/DomainGroupOSS/domain-rate-limiting

**Comment by hikalkan** [comment]
Have you seen https://github.com/stefanprodan/AspNetCoreRateLimit

**Comment by bbakermmc** [comment]
@hikalkan I have, it doesn't seem as robust as the other other one.  The one you showed seems to only have 2 built in modes of IP or Client.  We would want it based on a Key or JWT or something instead that we can then define out the limits via some other FK join to a rate limits table.

Mull it over and see what you come up with :)  But we shouldn't just let people call the dynamic endpoints if they have permission  100000000 times a second :p Ideally it would be restricted to the app itself/those we allow, or if the user has another permission/token where they are throttled.

**Comment by mehmetuken** [comment]
https://github.com/dotnet/aspnetcore/issues/39504 .NET 7 coming with rate limiting.

**Comment by mehmetuken** [comment]
Preview 4 published with rate limiting. https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#rate-limiting-middleware
