### ISSUE TITLE
How to store data protection keys for Entity Framework Core

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3890]
See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio#entity-framework-core

We should provide a way and document it.

This is also related to https://github.com/abpframework/abp/issues/3862

**Comment by liangshiw** [comment]
There are two ways to store data keys using Entity Framework Core:

1. Create a new project and configuration data protection database context.
2. Configure data protection using  an existing database context.

I created examples for both : https://github.com/liangshiw/AbpDataProectionSamles

**Comment by hikalkan** [comment]
Great! I will check your source code.
