### ISSUE TITLE
Blog comment counts are now shown

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3891]
Example:

![image](https://user-images.githubusercontent.com/1210527/81511488-7dfb1700-9322-11ea-893b-1011c4f9af67.png)

This post has 4 comments but shows 0 on https://blog.abp.io/abp

**Comment by yekalkan** [comment]
resolved by https://github.com/abpframework/abp/commit/7fbf91b20beb40f8444f89d0bd98c0de2e56a4d8

Comment count is unintentionally there. Db query doesn't include comments and therefore it is always "0 comments". We can bring this feature back if we make a major refactor on blogging domain.
