### ISSUE TITLE
move the MicroserviceDemo to the abp-samples repository

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3892]
I think it is mature enough to be able to use stable, released NuGet packages instead of local framework references. This will make it faster to run, debug and easy to deploy.

**Comment by gterdem** [comment]
Fixed via [PR#15](https://github.com/abpframework/abp-samples/pull/15).

**Comment by maliming** [comment]
hi @gterdem Should we remove it in abp? 
https://github.com/abpframework/abp/tree/dev/samples/MicroserviceDemo

**Comment by gterdem** [comment]
Hey @maliming, yet it can be removed from abp.
