### ISSUE TITLE
How to properly create my own customized layout

### ISSUE THREAD

**Issue by xirius** [abpframework/abp#3899]
What is the proper way to create a customized layout ?
I know that `ThemeManager.CurrentTheme.GetEmptyLayout()` is quite empty but I want to personalize css classes of the body `<body class="abp-empty-layout">` (Is it possible to inject my own css classes there somehow ?).
Also I want to have my own structure instead of 
```html
<div class="@containerClass">
        @(await Component.InvokeAsync<PageAlertsViewComponent>())
        @RenderBody()
</div>
```

What is the proper way to create a custom layout ? How should I start ? Thanks in advance.

**Comment by maliming** [comment]
You can customize it based on the layout page provided by the default theme.

https://github.com/abpframework/abp/issues/631#issuecomment-626393976

**Comment by xirius** [comment]
Ok, I got the idea. Thanks.
