### ISSUE TITLE
Test & upgrade all samples to v3.0

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3907]
- [x] Update all samples here: https://github.com/abpframework/abp-samples (use `abp update` CLI command).
- [x] Test all samples on this document: https://docs.abp.io/en/abp/latest/Samples/Index (except the microservice demo). Also follow the related document while testing.
- [x] Move `abp-samples/aspnet-core/Authentication-Customization/` to `abp-samples/Authentication-Customization/` (removed `aspnet-core` part) and update the link on all the documents.

**Comment by gterdem** [comment]
@hikalkan @AkinSabriCam 
I didn't see this issue and updated [Authentication Customization Sample](https://github.com/abpframework/abp-samples/tree/master/aspnet-core/Authentication-Customization) to 2.8 and tested already.
Also there is a pending PR by @maliming which i saw late already updates sample to 2.8.

**Comment by AkinSabriCam** [comment]
-[] BookStore Razor Page Applciation (**Test Passed**)
- [] BookStore Angular UI and MongoDb (**Test Failed**)
- [] BookStore Modular Application (**Test Passed**)

**Comment by liangshiw** [comment]
Hi @AkinSabriCam ,

https://github.com/abpframework/abp/pull/4479

We need to regenerate the migration file.
