### ISSUE TITLE
When the permission definition exceeds 2500, it takes about 7s

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#3914]
https://github.com/abpframework/abp/blob/cae569f9c390ad53e7bb70236e50b328dbb4fe92/modules/permission-management/src/Volo.Abp.PermissionManagement.Application/Volo/Abp/PermissionManagement/PermissionAppService.cs#L32

**Comment by liangshiw** [comment]
I will check it.

**Comment by liangshiw** [comment]
Hi,
I created 10,000 permission definitions and the method execution took `3914 milliseconds`.

```csharp
for (var i = 1; i <= 10000; i++)
{
    myGroup.AddPermission(i.ToString());
}
```

![image](https://user-images.githubusercontent.com/16813853/81640211-85b8d980-9450-11ea-989f-3af2b257b401.png)

![image](https://user-images.githubusercontent.com/16813853/81640251-a1bc7b00-9450-11ea-9410-81567259cbf0.png)

I think this is acceptable, and in most cases there will not be so many permission definitions. In fact, most of the time is wasted on HTML rendering, you can customize the page lazy loading permission definition.

**Comment by colinin** [comment]
In fact, most of the time is spent on provider queries for each permission, not just one query...
![permission-query](https://user-images.githubusercontent.com/35512826/81682732-a6505600-9487-11ea-84c5-8b3303465471.png)

**Comment by hikalkan** [comment]
We have an issue to optimize it: https://github.com/abpframework/abp/issues/2437
I am closing this.
