### ISSUE TITLE
How to forbid using distributed transaction in sqlquery

### ISSUE THREAD

**Issue by Asilent** [abpframework/abp#3917]
I want to query with sql server stored procedure, but the ef core threw an exception:
`Microsoft.Data.SqlClient.SqlException (0x80131904): 无法执行该操作，因为链接服务器的 OLE DB 访问接口 "SQLNCLI11" 无法启动分布式事务。`
I don't have permission to modify the connection server, so I want to forbid using distributed transaction when I use stored proc.

**Comment by liangshiw** [comment]
Try :
`[UnitOfWork(IsDisabled = true)]`

**Comment by Asilent** [comment]
> Try :
> `[UnitOfWork(IsDisabled = true)]`

Where should I add this navigation?

**Comment by liangshiw** [comment]
> I want to query with sql server stored procedure

The query method in your service.

**Comment by Asilent** [comment]
> > I want to query with sql server stored procedure
> 
> The query method in your service.

application or repository? else controller...?

**Comment by Asilent** [comment]
> > I want to query with sql server stored procedure
> 
> The query method in your service.

I had tried this method, but it didn't work.
