### ISSUE TITLE
Not able to see the entry in the audit log table

### ISSUE THREAD

**Issue by pmjaleel** [abpframework/abp#3920]
We are using one of the service template with User and Tenant Management. While checking the feature or the entry of the Audit log table, it has not records. We can see that the AuditLog module is used. Even though the audit property is true by default, we have added the [Audit] attribute explicitly.

Still we are not able to see any entry to the AudtiLog Table. Kindly guide us in configuring this.

Regards

**Comment by liangshiw** [comment]
Please use CLI create a simple project to reproduce this problem.

**Comment by pmjaleel** [comment]
Could you be more elaborate?

**Comment by pmjaleel** [comment]
It is working in the Sample Book Store app

**Comment by liangshiw** [comment]
I can't reproduce the problem. Can you provide steps to reproduce this problem.

![image](https://user-images.githubusercontent.com/16813853/81681985-26c28700-9487-11ea-9101-fbea96181d32.png)

**Comment by pmjaleel** [comment]
This could be something that we might have done wrong. We tested the sample application, Book Store and it has the audit log data.

If there are anything that we have overlooked, please let us know.

**Comment by liangshiw** [comment]
Can you use CLI create a simple project to reproduce this problem?

**Comment by pmjaleel** [comment]
We created the Book store as per your suggestion. It is working

**Comment by liangshiw** [comment]
If you share your full code we can see it.

**Comment by pmjaleel** [comment]
It would be a problem to share the code. 
We are using your service template. Which project will have the reference of the Auditlog Module?

**Comment by liangshiw** [comment]
It's open source, you can find it in the source code : ).

**Comment by pmjaleel** [comment]
I see that it is referenced in all the components in the framework project.

Is there any settings that we would have missed?

**Comment by pmjaleel** [comment]
I am not getting help here and you closed the issue. I know it is open source I am looking that code as well. I see all the references and database tables and the logs are not being written. I cannot share the code due to our firms policy.

**Comment by liangshiw** [comment]
If your provide a simple project to reproduce this problem. I can help you , now I don't know anything about your project.

**Comment by pmjaleel** [comment]
Solved it. Moved the position of the Middleware calling couple of steps above it started to work.
