### ISSUE TITLE
How to get the number of affected rows ?

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#3921]
Hi ，how to get the num of updated rows. I'd like to konw the data has been updated beacause of concurrency issues.

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/master/Entity-Framework-Core#access-to-the-ef-core-api.

`DbContext.SaveChangesAsync()` return affected rows : https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.savechangesasync?view=efcore-3.1#Microsoft_EntityFrameworkCore_DbContext_SaveChangesAsync_System_Threading_CancellationToken_
