### ISSUE TITLE
Generate proxies specify folder name

### ISSUE THREAD

**Issue by alirizaadiyahsi** [abpframework/abp#3922]
I am using following command:

````c#
yarn ng generate module book-type --routing true
````

And it is creating: `app/book-type` folder. But when I generate proxies with following command:

````c#
abp generate-proxy --module app
````

It is creating `app/booktype` folder. So models and services are placing in different folder than they should be.  

I don't know how proxy-generate tool working, but I think it can be compatible with existing folder name.

**Comment by maliming** [comment]
`booktype` is the controller name. Its name is from the application backend.

Maybe the folder name should also use `Kebab Case`. @erolarkat  What do you think?

**Comment by dicksonkimeu** [comment]
This proxy classes are for c# clients ?

**Comment by snowchenlei** [comment]
Can You specify the generated path, not all under the app folder.
