### ISSUE TITLE
Volo.Abp.Emailing set Abp.Mailing.Smtp.Password at appsettings.json

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#3923]
I'm try to set default vlaue  `Abp.Mailing.Smtp.Password`  and it will cause an error.  
here is my `appsettings.json`
![image](https://user-images.githubusercontent.com/2546026/81698273-4f06b180-9498-11ea-8014-0321cde9284e.png)

the error in log show
``` text
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
```

Can i past an  isEncrypted password  at `appsettings.json` ?
https://github.com/abpframework/abp/blob/ffdb8aca294842caa7de57cca1f72460a3dbd7de/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/EmailSettingProvider.cs#L32

**Comment by maliming** [comment]
You can use the encrypted `smtp password` in `appsettings.json`.

**Comment by ChangYinShung** [comment]
thanks,but i ask a simple question: 
how to  make this string `ispassword`  turn into encrypted string ? 
Do i need to call `SettingEncryptionService` to get encrypted string and paste the result on appsettings.json?

**Comment by maliming** [comment]
> Do i need to call SettingEncryptionService to get encrypted string and paste the result on appsettings.json?

Yes

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Emailing#encrypt-the-smtp-password
