### ISSUE TITLE
please add  a sample about how to extend IdentityUser.

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#3925]

**Comment by liangshiw** [comment]
Did you see https://docs.abp.io/en/abp/master/Customizing-Application-Modules-Extending-Entities#entity-extensions-ef-core ?

**Comment by zsanhong** [comment]
yes,I have read the doc,but these doc is just fragmentary code, a sample may more direct and easy to understand

**Comment by maliming** [comment]
@liangshiw 
We can consider adding some samples of common questions to https://github.com/abpframework/abp-samples. For example, use virtual file system to replace pages, replace built-in localization, etc.

**Comment by maliming** [comment]
Replace the prefix of the module table.
