### ISSUE TITLE
Automapper Entity to Dto mapping not convert the relation values

### ISSUE THREAD

**Issue by ametist-studio** [abpframework/abp#3927]
my models is

    public class PostCategory : Entity<int>
    {
        public string Title { get; set; }
        public string Slug { get; set; }
    }

    public class Post : AggregateRoot<long>
    {
        public string Title { get; set; }
        public PostType Type { get; set; }
        public int CategoryId { get; set; }
        public string Body { get; set; }

        [ForeignKey(nameof(CategoryId))]
        public PostCategory Category { get; set; }
    }

    public class PostDto : EntityDto<long>
    {
        public string Title { get; set; }
        public PostType Type { get; set; }
        public int CategoryId { get; set; }
        public string CategoryTitle { get; set; }
        public string Body { get; set; }
    }

the CategoryTitle not converted and its value is null

**Comment by liangshiw** [comment]
You should include `Category `. See https://docs.abp.io/en/abp/master/Best-Practices/Entity-Framework-Core-Integration#repository-implementation.

**Comment by ametist-studio** [comment]
I found another solution:
add Volo.Abp.EntityFrameworkCore package to application layer, and directly use its API

var query = CreateFilteredQuery(input);
var entities = query.Include(c => c.Category).ToList();

this is better for me
