### ISSUE TITLE
[Question] Has anyone been able to add the httpapi.client to a non-abp project?

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#3937]
I created a project which is not abp and I added the httpapi.client as a reference
I injected the interface in the constructor of my service in the new project, however when I run the project it always gives me an error that it could not add my interface

So my question is Has anyone been able to add the httpapi.client to a non-abp project?

**Comment by NecatiMeral** [comment]
I'm using the `MyCompany.MyProject.HttpApi.Client` project in non-abp applications. However you have to make sure the configuration of endpoints is made (appsettings.json for example) and you're using the same dependency injection approach as ABP (same container [builder]).

**Comment by ZouZou** [comment]
I was able to get it to work, however I had to create a module which inherits from abpmodule
if you can share a sample code on how you did it, I would highly appreciate it

**Comment by NecatiMeral** [comment]
hi @ZouZou,

yes - you're right. I created a separate module to integrate the `HttpApi.Client` project in my application.

**Comment by ZouZou** [comment]
Ok Tks, so I was on the right track after all.
