### ISSUE TITLE
How do i clear SessionState in angular  ?

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#3938]
angular version:`2.8.X `  
this is my step
1. Add setting in appsettings.json (an wrong setting)
``` json
  "Settings": {
    "Abp.Localization.DefaultLanguage": "zh-hant"
  }
```
2. serve angular application(chrome browser) and get an error
![image](https://user-images.githubusercontent.com/2546026/81819685-3793fb00-9562-11ea-9445-5c26113d9c57.png)

3.modfiy appsettings.json to the correct setting(angular)
``` json
  "Settings": {
    "Abp.Localization.DefaultLanguage": "zh-Hant"
  }
```
4.SessionState still get old value(zh-hant) even if i delete localstoreage through browser(refresh many times,clear storage)
![image](https://user-images.githubusercontent.com/2546026/81820359-18e23400-9563-11ea-90da-f915ac69ac35.png)

5. i open other browser(edge ) is work fine,but chrome browser is still get error
![image](https://user-images.githubusercontent.com/2546026/81821180-26e48480-9564-11ea-955c-cd63af3f6857.png)

Is it possible  that  when  enter  a wrong locale code(like: `ZH-Hant,zh-hant`) ,then use `en` as default and throw a waring at console ?
https://github.com/abpframework/abp/blob/23443c8eb98b1f9e578f01112876bf13bf02c2a2/npm/ng-packs/packages/core/src/lib/utils/initial-utils.ts#L49

**Comment by mehmet-erim** [comment]
Thanks for reporting @ChangYinShung, We'll fix the problem.

**Comment by mehmet-erim** [comment]
`registerLocale` strategy has been improved. For more information see the [document](https://docs.abp.io/en/abp/latest/UI/Angular/Localization#registering-a-new-locale)
