### ISSUE TITLE
Identity module - Search box doesn't search in phone number field

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#3944]
Reported here
https://support.abp.io/QA/Questions/156/Search-Box-Doesn%27t-Search-by-The-Phone-Number

**Comment by liangshiw** [comment]
I think the mongodb repository also needs to be updated.
https://github.com/abpframework/abp/blob/2143e904343707902f16fdf5da71bb5c63e54fc1/modules/identity/src/Volo.Abp.Identity.MongoDB/Volo/Abp/Identity/MongoDB/MongoIdentityUserRepository.cs#L90

**Comment by maliming** [comment]
@liangshiw Please open a new PR.
