### ISSUE TITLE
Toast throwing error after update

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#3949]
Hi!

I've updated angular application to version 2.7.0. 
Also what changed is that I moved this application from Azure to a on-premise server and hosted in IIS, but I dont think that's the problem..

Now this variable is undefined and throws error after that.
![image](https://user-images.githubusercontent.com/6138475/81881129-c1919300-9565-11ea-8255-be1efa97f184.png)

**Comment by yinchang0626** [comment]
@thiag0coelho 
Maybe you can check your [layout component](https://github.com/abpframework/abp/commit/c9b709b69d43bddef22f55385f7d283da57b6b8e)
it is no longer need below :
```typescript
-<abp-confirmation></abp-confirmation>	
-<abp-toast-container right="30px" bottom="30px"></abp-toast-container>	
```

**Comment by thiag0coelho** [comment]
> @thiag0coelho
> Maybe you can check your [layout component](https://github.com/abpframework/abp/commit/c9b709b69d43bddef22f55385f7d283da57b6b8e)
> it is no longer need below :
> 
> ```ts
> -<abp-confirmation></abp-confirmation>	
> -<abp-toast-container right="30px" bottom="30px"></abp-toast-container>	
> ```

I don't use abp-toast anywhere..

**Comment by yinchang0626** [comment]
@thiag0coelho 
Can you show elements of page like this:
![image](https://user-images.githubusercontent.com/16490084/81884736-3945d900-95cb-11ea-98f0-bd7f5917243d.png)
Check It should not include ```<abp-toast-container>``` in ```<abp-layout-application>```
I guess maybe @abp/ng.theme.basic in `node_modules` is not new version.

**Comment by thiag0coelho** [comment]
You're right, it's there, but as I said it is an entirely new environment where I configured CI/CD, it was using version 2.7 from the start.
But I'll take a look at it, thanks for now!
