### ISSUE TITLE
Whether MigrateDatabaseToLatestVersion can be supported？

### ISSUE THREAD

**Issue by qiang999** [abpframework/abp#3951]
Hello,
I have a question.Whether MigrateDatabaseToLatestVersion can be supported？

**Comment by liangshiw** [comment]
Can you explain in detail?

**Comment by qiang999** [comment]
This is microsoft docs.
https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.migratedatabasetolatestversion-2?view=entity-framework-6.2.0
Using migratedatabasetolatestversion can auto update database on application startup instead of update-datebase command.

**Comment by liangshiw** [comment]
You can inject `<YourPojectNmae>MigrationService` in the `OnApplicationInitialization` method of the module class, and execute `MigrateAsync` method.
