### ISSUE TITLE
cannot load theme when use configurable json file #3536

### ISSUE THREAD

**Issue by TuyenDinh1205** [abpframework/abp#3952]
Hi!
I'm using  option skipGetAppConfiguration: true in CoreModule to using config json file instead of enviroment.ts like topic #3536  but when I run web it has error 
![Capture](https://user-images.githubusercontent.com/34994601/81919246-cb68d400-9601-11ea-8381-49a16f1f0330.PNG)
Please tell me how to fix it?
Thanks

**Comment by mehmet-erim** [comment]
There is a problem in the theme-lepton package. It'll be fixed in v2.8.

If you pass `skipGetAppConfiguration` value true, you should call `application-configuration` like below:

```ts
this.store.dispatch(GetAppConfiguration).subscribe(async () => {
  // below codes refresh the page sliently. That is required.
  const { shouldReuseRoute } = this.router.routeReuseStrategy;
  this.router.routeReuseStrategy.shouldReuseRoute = () => false;
  this.router.navigated = false;
  await this.router.navigateByUrl(this.router.url);
  this.router.routeReuseStrategy.shouldReuseRoute = shouldReuseRoute;
});
```
