### ISSUE TITLE
Change HttpApi.Client project target of start template to netstandard2.0

### ISSUE THREAD

**Issue by liangshiw** [abpframework/abp#3960]
Related https://github.com/abpframework/abp/pull/2867

We can change `HttpApi.Client` project target of the start template to netstandard2.0.

https://github.com/abpframework/abp/blob/25085b2959bf315814507cef9835d9e2a8d673a5/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Client/MyCompanyName.MyProjectName.HttpApi.Client.csproj#L6

https://github.com/abpframework/abp/blob/25085b2959bf315814507cef9835d9e2a8d673a5/templates/module/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.Client/MyCompanyName.MyProjectName.HttpApi.Client.csproj#L6

**Comment by NecatiMeral** [comment]
Would be a nice change to make (parts of) the start template usable for other clients (WinForms, ...) without hassle.
