### ISSUE TITLE
How to get the token when I login?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#3962]
I want to use the api of the abp application, but I can't see the token  return from swagger api '/api/account/login' . how to deal with it? thanks.

**Comment by liangshiw** [comment]
You can use `/connect/token` endpoint get token. See http://docs.identityserver.io/en/3.1.0/endpoints/token.html.

**Comment by xyfy** [comment]
It need a `code` params ,How can I get it in the `Login` action?
