### ISSUE TITLE
How to change the validate code by myself?

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#3972]
![image](https://user-images.githubusercontent.com/14011792/82113111-eebc8c00-9785-11ea-9176-b837dcfb2443.png)
I want to custom return code ，like  the loction of  the pic above.
By the way， Can I change the whole json format to what I want  ？In other words, I want  to change the json format of exception.

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Exception-Handling

You can customize exception filter to return your json format : https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs

**Comment by wingqing1314** [comment]
So i must change the source code?

**Comment by wingqing1314** [comment]
> See https://docs.abp.io/en/abp/latest/Exception-Handling
> 
> You can customize exception filter to return your json format : https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ExceptionHandling/AbpExceptionFilter.cs

So i must change the source code?

**Comment by liangshiw** [comment]
Yes.

**Comment by ZouZou** [comment]
> ![image](https://user-images.githubusercontent.com/14011792/82113111-eebc8c00-9785-11ea-9176-b837dcfb2443.png)
> I want to custom return code ，like the loction of the pic above.
> By the way， Can I change the whole json format to what I want ？In other words, I want to change the json format of exception.

How were you able to get it to return a validation exception? I threw a validation exception but all I got on the swagger was a status code 500
{
  "error": {
    "code": null,
    "message": "An internal error occurred during your request!",
    "details": null,
    "validationErrors": null
  }
}

**Comment by maliming** [comment]
hi @ZouZou 

Please create a new issue separately and explain it in detail, thanks.
