### ISSUE TITLE
ProgressiveWebApp integration issue - ServiceProxyScript crashes 500 error

### ISSUE THREAD

**Issue by kgamalseif** [abpframework/abp#3980]
Following this link [https://blog.elmah.io/turning-an-aspnet-core-website-into-a-progressive-web-app-pwa/](url) to add PWA feature to MVC template it crashes:

**ArgumentNullException: Value cannot be null. (Parameter 'httpMethod')
Volo.Abp.Check.NotNull<T>(T value, string parameterName)
Volo.Abp.Http.Modeling.ActionApiDescriptionModel.Create(string uniqueName, MethodInfo method, string url, string httpMethod, IList<string> supportedVersions)
Portal.Halaqat.Web.Framework.RepAspNetCoreApiDescriptionModelProvider.AddApiDescriptionToModel(ApiDescription apiDescription, ApplicationApiDescriptionModel applicationModel, ApplicationApiDescriptionModelRequestDto input) in RepAspNetCoreApiDescriptionModelProvider.cs
+
            var actionModel = controllerModel.AddAction(uniqueMethodName, ActionApiDescriptionModel.Create(
Portal.Halaqat.Web.Framework.RepAspNetCoreApiDescriptionModelProvider.CreateApiModel(ApplicationApiDescriptionModelRequestDto input) in RepAspNetCoreApiDescriptionModelProvider.cs
+
                    AddApiDescriptionToModel(apiDescription, model, input);**

---
changed the method **CreateApiModel** at **AspNetCoreApiDescriptionModelProvider** solved the problem:
`

            var model = ApplicationApiDescriptionModel.Create();

            foreach (var descriptionGroupItem in _descriptionProvider.ApiDescriptionGroups.Items)
            {
                foreach (var apiDescription in descriptionGroupItem.Items)
                {
                    if (!apiDescription.ActionDescriptor.IsControllerAction())
                    {
                        continue;
                    }

                    if (apiDescription.HttpMethod.IsNullOrEmpty()) apiDescription.HttpMethod = "GET";

                    AddApiDescriptionToModel(apiDescription, model, input);
                }
            }

            return model;`

**Comment by hikalkan** [comment]
@maliming can you try to understand this?

**Comment by maliming** [comment]
@kgamalseif This is like a third-party library problem, please provide a project to reproduce the problem. You can use cli to create it.

**Comment by kgamalseif** [comment]
[https://github.com/kgamalseif/PwaTest](url)
Kindly find the above project.
to reproduce the issue, just comment line:
`if (apiDescription.HttpMethod.IsNullOrEmpty()) apiDescription.HttpMethod = "GET";`
at RepAspNetCoreApiDescriptionModelProvider.cs

Thanks,
Khaled

**Comment by maliming** [comment]
hi @kgamalseif  
`WebEssentials.AspNetCore.ServiceWorker` has fixed this problem, but it does not seem to be released to nuget.
https://github.com/madskristensen/WebEssentials.AspNetCore.ServiceWorker/pull/62
