### ISSUE TITLE
Create Oracle integration package for EF Core

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3983]
* Create Volo.Abp.EntityFrameworkCore.Oracle.Devart package
* Upgrade EF Core packages to the latest version on the framework & templates

**Comment by ebicoglu** [comment]
also comment out the below section because devart oracle provider throws exception when using `context.ExistingConnection`

![](https://user-images.githubusercontent.com/9526587/82150328-03ba1d80-9861-11ea-9696-9a633d006a9b.png)

```
Exception Message "Unexpected connection type 'Devart.Data.Oracle.Entity.ao'."  

  at Microsoft.EntityFrameworkCore.OracleDbContextOptionsBuilderExtensions.a(DbConnection A_0)
  at Microsoft.EntityFrameworkCore.OracleDbContextOptionsBuilderExtensions.UseOracle(DbContextOptionsBuilder options, DbConnection connection, Action`1 optionAction)
  at Acme.OracleApp.EntityFrameworkCore.OracleAppEntityFrameworkCoreModule.<>c.<ConfigureServices>b__1_2(AbpDbContextConfigurationContext ctx) in D:\Alper\Github\Acme.OracleApp\src\Acme.OracleApp.EntityFrameworkCore\EntityFrameworkCore\OracleAppEntityFrameworkCoreModule.cs:line 61
  at Volo.Abp.EntityFrameworkCore.DependencyInjection.DbContextOptionsFactory.Configure[TDbContext](AbpDbContextOptions options, AbpDbContextConfigurationContext`1 context)
  at Volo.Abp.EntityFrameworkCore.DependencyInjection.DbContextOptionsFactory.Create[TDbContext](IServiceProvider serviceProvider)
  at Autofac.Extensions.DependencyInjection.AutofacRegistration.<>c__DisplayClass2_0.<Register>b__0(IComponentContext context, IEnumerable`1 parameters)
  at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
  at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
```

**Comment by ebicoglu** [comment]
### Here's the step by step guide to integrate ABP project with EF Core Oracle (Devart provider)

https://gist.github.com/ebicoglu/9f364c7eff9d87315af0178866186401

**Comment by hikalkan** [comment]
done: https://github.com/abpframework/abp/blob/dev/docs/en/Entity-Framework-Core-Oracle.md

**Comment by dicksonkimeu** [comment]
The official ef core for Oracle is released.

I think, you should base this test on this.

https://medium.com/@alex.keh/beta-release-oracle-entity-framework-core-3-1-eb0b4d3c93b1

**Comment by daconglee** [comment]
.EntityFrameworkCore

Install-Package Oracle.EntityFrameworkCore -Version 3.19.0-beta1
public static class AbpDbContextConfigurationContextOracleExtensions
    {
        public static DbContextOptionsBuilder UseOracle(
          [NotNull] this AbpDbContextConfigurationContext context,
          [CanBeNull] Action<OracleDbContextOptionsBuilder> oracleSQLOptionsAction = null)
        {
            if (context.ExistingConnection != null)
            {
                return context.DbContextOptions.UseOracle(context.ExistingConnection, oracleSQLOptionsAction);
            }
            else
            {
                return context.DbContextOptions.UseOracle(context.ConnectionString, oracleSQLOptionsAction);
            }
        }
    }
    public static class AbpDbContextOptionsMySQLExtensions
    {
        public static void UseOracle(
                [NotNull] this AbpDbContextOptions options,
                [CanBeNull] Action<OracleDbContextOptionsBuilder> oracleSQLOptionsAction = null)
        {
            options.Configure(context =>
            {
                context.UseOracle(oracleSQLOptionsAction);
            });
        }

        public static void UseMySQL<TDbContext>(
            [NotNull] this AbpDbContextOptions options,
            [CanBeNull] Action<OracleDbContextOptionsBuilder> oracleSQLOptionsAction = null)
            where TDbContext : AbpDbContext<TDbContext>
        {
            options.Configure<TDbContext>(context =>
            {
                context.UseOracle(oracleSQLOptionsAction);
            });
        }
    }
}
 

//xxxxxxEntityFrameworkCoreModule.cs文件

 public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<SysAdminDbContext>(options =>
            {
                /* Remove "includeAllEntities: true" to create
                 * default repositories only for aggregate roots */
                options.AddDefaultRepositories(includeAllEntities: true);
            });

            Configure<AbpDbContextOptions>(options =>
            {

                /* The main point to change your DBMS.
                 * See also SysAdminMigrationsDbContextFactory for EF Core tooling. */
                options.UseOracle(b => b.UseOracleSQLCompatibility("11"));
            });
        }

**Comment by liangshiw** [comment]
@dicksonkimeu  Please create a new issue to discuss.

**Comment by hikalkan** [comment]
see https://github.com/abpframework/abp/issues/4160
