### ISSUE TITLE
Expose enum type & members to client side for extension properties

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#3984]

**Comment by jortygu** [comment]
why change SelectListItem value property form enum int to enum string?
[before code](https://github.com/abpframework/abp/blob/e3e3ecd71233a1bf4173df791bd079d1ba204742/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Form/AbpSelectTagHelperService.cs)
[after code](https://github.com/abpframework/abp/blob/2f0a7af7b3b4b849a392ad21572565789055bc22/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Form/AbpSelectTagHelperService.cs)
``` c#
//before:
selectItems.AddRange(enumType.GetEnumNames().Select(enumName => new SelectListItem
{
     Value = Convert.ToUInt64(Enum.Parse(enumType, enumName)).ToString(), //here
     Text = GetLocalizedEnumFieldName(containerLocalizer, modelObjectLocalizer, enumType, enumName)
}));
//after:
selectItems.Add(new SelectListItem
{
     Value = enumValue.ToString(), //here
     Text = localizedMemberName
});
```
