### ISSUE TITLE
[question]How can I add a IUserValidator to abp

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#3990]
if I has a custom validator
``` C#
    public class YunUserValidator<TUser> : IUserValidator<TUser> where TUser : IdentityUser
```

How can I add it when I re-use the `Volo.Abp.Identity` module

I try do something in `ConfigureServices`

```
    [DependsOn(
        typeof(IdentityDomainSharedModule),
        typeof(AbpIdentityDomainModule)
        )]
    public class IdentityDomainModule : AbpModule
.....
            var identityBuilder = context.Services.AddAbpIdentity(options =>
            {
                options.User.RequireUniqueEmail = false;
            }).AddUserValidator<YunUserValidator<IdentityUser>>();
```

is it correct?

**Comment by maliming** [comment]
```
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<IdentityBuilder>(builder =>
    {
        builder.AddUserValidator<YunUserValidator<IdentityUser>>();
    });
}
```

>  options.User.RequireUniqueEmail = false;

https://github.com/abpframework/abp/issues/2461#issuecomment-568840948

**Comment by xyfy** [comment]
If I want to remove the default user validator
``` C#
  PreConfigure<IdentityBuilder>(builder =>
    {
                var service = context.Services.FirstOrDefault(s => s.ImplementationType == typeof(UserValidator<IdentityUser>));
                if (service != null)
                {
                    context.Services.Remove(service);
                }
    });
```
is it right?

**Comment by xyfy** [comment]
> 
> > options.User.RequireUniqueEmail = false;
> 
> [#2461 (comment)](https://github.com/abpframework/abp/issues/2461#issuecomment-568840948)

I can not found a setting named `RequireUniqueEmail`, How can I set it to false?

**Comment by kishoresahas** [comment]
> > > options.User.RequireUniqueEmail = false;
> > 
> > 
> > [#2461 (comment)](https://github.com/abpframework/abp/issues/2461#issuecomment-568840948)
> 
> I can not found a setting named `RequireUniqueEmail`, How can I set it to false?

Did you find a solution for this?
