### ISSUE TITLE
`IdentityUserAppService.CreateAsync` implement

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#3991]
the ` CreateAsync(IdentityUserCreateDto input)` in `IdentityUserAppService` of `Volo.Abp.Identity` 
```
            (await UserManager.CreateAsync(user, input.Password)).CheckErrors();
            await UpdateUserByInput(user, input);
            await CurrentUnitOfWork.SaveChangesAsync();
```

why you donnot call the `UpdateUserByInput` before `UserManager.CreateAsync`

I add a validator for user's `PhoneNumber` ,but it cannot works.

It always get `PhoneNumber` value is null.

**Comment by xyfy** [comment]
I know it ,  you want do with roles apply.
How can I make the IValidator<TUser> for PhoneNumber correctly?

**Comment by xyfy** [comment]
I think you should split it to two diffrent method.

**Comment by xyfy** [comment]
The `PhoneNumber` is protected set .

**Comment by xyfy** [comment]
Can I override `IdentityUser` to provide a construct can set PhoneNumber?

How to do it?

**Comment by xyfy** [comment]
I want to create a user with `PhoneNumber`,not `Email`.

**Comment by maliming** [comment]
> I want to create a user with PhoneNumber,not Email.

Identity doesn't seem to allow this. You can ask this in Microsoft's repository.
https://github.com/dotnet/aspnetcore/tree/master/src/Identity

**Comment by ayazzz** [comment]
Hi @xyfy 
What about a common solution I have seen in many big projects? 
They take the phone number and save in db as {phoneNumber}`@domain.com`
Whatsapp is an example of this..

**Comment by xyfy** [comment]
l am&nbsp; already do it,but it&nbsp; cannot validate&nbsp; phone number&nbsp; at&nbsp; &nbsp;create async



---Original---

**Comment by xyfy** [comment]
I think it maybe a bug,  When excute the `UserManager.CreateAsync` ,according the user's property is not inited,so the `IUserValidator` for `PhoneNumber` can not work correctly.     

 @maliming what do you think about it?
