### ISSUE TITLE
Option to disable updating LastModificationTime on entity

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#3992]
I'd like to update an entity in a background service but I don't want to update the modification time and user information as I think it should reflect when there was user interaction with an entity.

I thought I'd be able to use `IDataFilter<IModificationAuditedObject>.Disable()` to stop the information being updated similar to the HardDelete function but after looking at [AbpDbContext](https://github.com/abpframework/abp/blob/2.7.0/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs) I see that only `ISoftDelete` and `IMultiTenant` filters can be disabled?

Would it be possible to implement the ability to disable updates to the various auditing interfaces [seen here](https://docs.abp.io/en/abp/latest/Entities#auditing-interfaces)?

Also, is there a way to work around this until there is an official was to do it?

**Comment by liangshiw** [comment]
Ccurrently no way to disable updating LastModificationTime.
I think you need another business level audit time, like `LastInteractionTime`.

**Comment by olicooper** [comment]
I need this feature for various entities in the system. It would add redundant data to my tables by adding extra columns, it would also be a breaking change in my case so that solution won't work for me.

The solution I mentioned above was actually simpler to implement than I thought.. I think there are going to be times when people want to not update their entity modification times, would Abp team consider making this an official feature? There may be alternative/better solutions such as disabling auditing altogether for a single transaction.

I added this to my `AbpDbContext`:
```csharp
protected override void SetModificationAuditProperties(EntityEntry entry)
{
    if (DataFilter?.IsEnabled<Volo.Abp.Auditing.IModificationAuditedObject>() ?? true)
    {
        AuditPropertySetter?.SetModificationProperties(entry.Entity);
    }
}
```

**Comment by hikalkan** [comment]
Thanks for your suggestion. I added it to backlog.

**Comment by hikalkan** [comment]
One way of doing it can be overriding the `SetModificationAuditProperties` method for your `DbContext` class and skip calling the base method if you like in a certain case. For example, you may define a static bool property to disable it. You set it to false when you need to disable, then check it here. Instead of statics, which is not threadsafe, you can surely use ambient context pattern (or simple `AsyncLocal<bool>`). So, you can do it in your application.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/17542
