### ISSUE TITLE
Online Clients System

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#40]
like in ABP1. But should consider web farm scenarios better. Create AspNet Core SignalR implementation.

**Comment by hikalkan** [comment]
Hi,

Yes, it has created at 2016, just a few days after the first commit: https://github.com/abpframework/abp/graphs/contributors :)

"Online Clients" system has lower priority. But SignalR integration & real time notification have higher priority: https://github.com/abpframework/abp/issues/633
But we may need to this system while implementing the #633.

**Comment by ebicoglu** [comment]
year 2019 :)

**Comment by Loongle** [comment]
year 2020 :)

**Comment by danghung-dev** [comment]
Year 2021 :)

**Comment by hikalkan** [comment]
😄 I think it is time to close this issue since we won't make it. Creating such a feature and support every possible scenario is a hard work. However, implementing it for a particular case is very easy (for example: handle signalr connection events, store online users in a cache or mark as online in the database). So, it is better to leave such non-framework features to the developers to implement for their own cases.

**Comment by danielmeza** [comment]
@hikalkan how this afect the Real-time notification system? is still in the roadmap?

**Comment by hikalkan** [comment]
It is on the road map for the abp commercial. We see it as an application functionality rather than a framework feature. One possibility may be adding the abstraction to the framework side to provide a standard, so module & application developers can make assumption on the contracts.

**Comment by danielmeza** [comment]
@hikalkan I like that approach!
