### ISSUE TITLE
MVC Module Startup Template .Web project description missing

### ISSUE THREAD

**Issue by GerryGe** [abpframework/abp#4002]
I would like to know how to create the .Web project in my module? I found it is a class library("Microsoft.NET.Sdk"), not a true web application, but the project sdk is the same:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
```
As I known, there are Razor class library project in ASP.NET Core, Can I use this project type and Why you don't use this type of project?
```
<Project Sdk="Microsoft.NET.Sdk.Razor">
```

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/issues/255. Abp provide virtual file system to build module.
But you can also use Razor class library project.

**Comment by GerryGe** [comment]
@liangshiw Tks, I got it.
