### ISSUE TITLE
Does the HEAD method access need to be recorded by audit log?

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4010]
ABP sets `IsEnabledForGetRequests=false` by default to disable audit log for GET method.

The HEAD method is very similar to the GET method, and it is often used by heartbeat detectors. Maybe it does not have to be recorded.

**Comment by hikalkan** [comment]
Good suggestion, while HEAD method is not so frequently used.
To be more flexible, we can create a service that has a ShouldCreateAuditLog() method that returns true/false. In this way, you can override the service and do whatever you want.

**Comment by wjkhappy14** [comment]
Good suggestion

**Comment by hikalkan** [comment]
I think we can disable logging for `HEAD` if `IsEnabledForGetRequests` is `false`. No need to define another option. @maliming can we implement this?
