### ISSUE TITLE
RabbitMq Distributed EventBus Implement Retry

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#4015]
Hi, guys
Now, All failed events are now queued and retry is not work.When my app restarts, it takes the event out of the queue again and consumes it

**Comment by hikalkan** [comment]
Can you write in more details. I suppose you are writing about retrying to execute/handle an event, but not retrying to send an event to rabbitmq, right?

@maliming can you check how it works now?

**Comment by senxiaoxing** [comment]
When a message fails to be consumed, the message will not be Acked, remain in the Unacked of the queue, and there should be a mechanism to consume it again.

**Comment by hikalkan** [comment]
RabbitMQ immediately sends it back to the application as I know. I am closing this because it is a very old issue, please open another issue.
