### ISSUE TITLE
Update Background document

### ISSUE THREAD

**Issue by liangshiw** [abpframework/abp#4028]
Related : https://github.com/abpframework/abp/pull/3382

- [x] Introduce the default quartz background jobs exception handling strategy and how to customize it
- [x] Introduce how to disable the automatic registration of quartz background workers
- [x] Introduce advanced scenes of quartz background workers

**Comment by maliming** [comment]
If it is not completed within the 2.8 milestone, please open PR in the **master** branch.

**Comment by liangshiw** [comment]
Ok.
