### ISSUE TITLE
Can not Inject IObjectMapper workable according to the Document

### ISSUE THREAD

**Issue by BrianCodeman** [abpframework/abp#4030]
Hi team,

I Created a MVC project from scratch (from VS asp.net core MVC template, without using the ABP CLI). Without anything else in concern, I just want to see if I could make use of Volo.Abp.AutoMapper Module in a custom project. As the [Document](https://docs.abp.io/en/abp/latest/Object-To-Object-Mapping#automapper-integration) suggests, I did this way:

1. Install packages:
`
PM> install-package volo.abp.automapper
`

2. Defined my mappings:
```
    using AutoMapper;
    public class MyProfile : Profile
    {
        public MyProfile()
        {
             ...
        }
    }
```

3. Create a Module class and Register my profile:
```
    [DependsOn(
    typeof(AbpAutoMapperModule)
    )]
    public class MyModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpAutoMapperOptions>(options =>
            {
                options.AddMaps<MyModule >();
            });
        }
    }
```

4. Load module when Startup:
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplication<MyModule>();
            ...
        }
```

5. Inject the IObjectMapper to my Controller:
```
    using Volo.Abp.ObjectMapping;    
    
    public class HomeController : Controller
    {
        private readonly IObjectMapper _mapper;

        public HomeController(IObjectMapper mapper)
        {
              _mapper = mapper;
        }
    }
```

6. Set breakpoint to Profile constructor and Controller constructor to see if the IObjectMapper  was correctly injected, but the result is, MyProfile constructor wasn't called at all, and injected IObjectMapper had a null Mapper property like this:
![IObjectMapperFailed](https://user-images.githubusercontent.com/59074131/82513154-b8478e00-9b44-11ea-82a2-3d14fb969e85.png)

Since the try failed, I removed Volo.Abp.AutoMapper package and turned to use AutoMapper package directly, which works fine. 
So, what I am wondering is: Did I make something wrong or miss some steps when I followed the guide to use Volo.Abp.AutoMapper Module? Could you please help me to figure that out? Thanks for your concern.

**Comment by maliming** [comment]
You can refer to this example project.
https://github.com/abpframework/abp-samples/tree/master/BasicAspNetCoreApplication/BasicAspNetCoreApplication

**Comment by BrianCodeman** [comment]
Thanks a lot, I got the point. All because I didn't install and depended on AbpAspNetCoreMvcModule. It works now.
