### ISSUE TITLE
Docs module gives HTTP 500 error when I open a document first time

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4042]
https://github.com/abpframework/abp/issues/3731 is still valid!

**Comment by maliming** [comment]
This error is caused by elasitc.

@erolarkat Can you help check?


```
 Request failed to execute. Call: Status code 403 from: PUT /abp_io_documents/_doc/b0c9f41a-e518-07ee-d4ef-39f54beb408d. ServerError: Type: cluster_block_exception Reason: "index [abp_io_documents] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
````

https://kb.objectrocket.com/elasticsearch/how-to-fix-the-forbidden-12-read-only-api-error-in-elasticsearch-282

**Comment by hikalkan** [comment]
Even if we get such an exception, we should ignore it and continue.

**Comment by maliming** [comment]
I can change the thrown exception to error log.

**Comment by erolarkat** [comment]
@maliming I changed the index read only setting. Can you check again?

**Comment by maliming** [comment]
I will pay attention to the audit log in the next few days. Thanks. 👍
