### ISSUE TITLE
Remove ConsoleApp suffix from the console template

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4043]
If I want ConsoleApp naming, I can already do. It is not good to assume that we always want a .ConsoleApp suffix.

We can create multi-namespace solution names:

````bash
abp new MyApp.Ns1.Ns2.FinalNs -t console
````

But it always add .ConsoleApp to the end:

![image](https://user-images.githubusercontent.com/1210527/82582491-ce803900-9b9a-11ea-81e4-439ac2770901.png)

**Comment by liangshiw** [comment]
If we delete the consoleApp suffix of the project name, then it will be the same name as the solution. Should we keep  project name suffix?

**Comment by hikalkan** [comment]
I think no problem with that. A single application in a solution can be same named with the solution.

For example, I want to create a console application like `Acme.TempFilesDeleter` which deletes some predefined folders, why should I be forced to name it like `Acme.TempFilesDeleter.ConsoleApp`.
