### ISSUE TITLE
Motivation for ABP vNext development

### ISSUE THREAD

**Issue by devsoitic08** [abpframework/abp#405]
I used to develop using the last version of [ABP](https://aspnetboilerplate.com/), and now i'm really intrigued with this new version and what was the motivation to develop it. Could you explain **what are your goals** with this new model of ABP and **what was the motivation** to make it?

**Comment by devsoitic08** [comment]
Closing this issue due to #388 


I would sugest to post this answer on your blog, its something of great interest from devs that used the last version.

**Comment by hikalkan** [comment]
We will create a blog post soon.

**Comment by wakuflair** [comment]
Any news of the blog post？

**Comment by hikalkan** [comment]
Not yet, but very close. We are working to finalize the [blogging module](https://github.com/abpframework/abp/tree/master/modules/blogging) and post it in our own blog.

**Comment by wakuflair** [comment]
Can't wait to see it.

**Comment by hikalkan** [comment]
Me too :)
