### ISSUE TITLE
[Question] how to return ValidationException to the client?

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#4050]
I am using abp 2.3.0
I have a custom function which validates the date format of the parameter value, in the function I am throwing a ValidationException but on the swagger file, I am getting a status code 500
When I switched to throw an AbpValidationException, I got a 400 status code
```
{
  "error": {
    "code": null,
    "message": "Your request is not valid!",
    "details": "The following errors were detected during validation.\r\n - Second Approval Date has an invalid date format!\r\n",
    "validationErrors": [
      {
        "message": "Second Approval Date has an invalid date format!",
        "members": null
      }
    ]
  }
}
```

my question is: - how do I return a code and what about the members?

**Comment by maliming** [comment]
You should use `AbpValidationException`.

```c#
throw new AbpValidationException(message,
	new List<ValidationResult>
	{
		new ValidationResult(message, new[] { memberName1, memberName2 })
	});
```

`AbpValidationException` currently does not implement `IHasErrorCode`.

**Comment by ZouZou** [comment]
@maliming Thank you very much, I was missing the 
`new[] { memberName1, memberName2 }`
`                throw new AbpValidationException(propertyName + " has an invalid date format!",
                    new List<ValidationResult>() { new ValidationResult(propertyName + " has an invalid date format!") } );`
