### ISSUE TITLE
use generate-proxy get more error

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#4051]
in c#,I defined a dto
``` csharp
public class UserListDto : EntityDto<int>
    {
        public string RealName { get; set; }
    }
```
Next use `abp generate-proxy`.I get error!
![image](https://user-images.githubusercontent.com/26211283/82646657-908d1e80-9c47-11ea-838e-380615934210.png)
The resulting ts files are as follows：

1. in user-list-dto.ts
``` ts
import { EntityDto } from '@abp/ng.core';
export class UserListDto extends EntityDto<System.Int32> {
  realName: string;
  id: number;

  constructor(initialValues: Partial<UserListDto> = {}) {
    super(initialValues);
  }
}
```
2. in int32.ts
``` ts
import { EntityDto } from '@abp/ng.core';
export class Int32 extends EntityDto {
  id: number;

  constructor(initialValues: Partial<Int32> = {}) {
    super(initialValues);
  }
}

```
The above is an error with upgrade 2.8.0

**Comment by snowchenlei** [comment]
@maliming in 2.9. The problem still exists.

**Comment by maliming** [comment]
Have you upgraded abp cli to 2.9?

```cmd
dotnet tool list -g

Package Id                            Version      Commands
------------------------------------------------------------------------------
volo.abp.cli                          2.9.0        abp
```

**Comment by snowchenlei** [comment]
![image](https://user-images.githubusercontent.com/26211283/83998376-02c56900-a993-11ea-81ed-2e2ecdead335.png)
yes

**Comment by snowchenlei** [comment]
And the generate int32.ts was never used

![image](https://user-images.githubusercontent.com/26211283/83998645-9f880680-a993-11ea-86e5-1bd38a2a2bb3.png)

**Comment by maliming** [comment]
Are these files newly generated?

**Comment by snowchenlei** [comment]
I first deleted the old file.
second use `abp generate-proxy --apiUrl url --o test` Rebuild

**Comment by maliming** [comment]
The 3.0 milestone will refactor `generate-proxy`.

**Comment by sebitsi** [comment]
> The 3.0 milestone will refactor generate-proxy.

@maliming What exactly this mean ?
