### ISSUE TITLE
Cannot found js in razorPages Area

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4056]
My Project like below
![1](https://user-images.githubusercontent.com/7838147/82656639-ae15b480-9c56-11ea-8190-624dd1e24a17.jpg)
I have config the `VirtualFile`
![2](https://user-images.githubusercontent.com/7838147/82656752-da313580-9c56-11ea-8477-cf1f55db43c2.jpg)
When I use `abp-style` tag in `Areas` ,it got err
```
@section styles{
    <abp-style src="/Areas/Admin/Pages/Orders/Index.css" />
}
```
![3](https://user-images.githubusercontent.com/7838147/82656960-28decf80-9c57-11ea-8594-e7538d840918.jpg)
but in just /pages,it works well
![4](https://user-images.githubusercontent.com/7838147/82657097-5c215e80-9c57-11ea-85be-735344518db3.jpg)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by xyfy** [comment]
I will create a demo to reproduce it

**Comment by xyfy** [comment]
It is no time to do this ,I will close it now.and opened it in fulture
