### ISSUE TITLE
FakeCurrentPrincipalAccessor - IDisposable Change not implemented

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#4057]
There is error in .TestBase project in Security/FakeCurrentPrincipalAccessor.cs.

There is ICurrentPrincipalAccessor with IDisposable Change(ClaimsPrincipal principal) method, which is not declared (and implemented) in FakeCurrentPrincipalAccessor.cs.

**Comment by maliming** [comment]
Please refer to https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.TestBase/Security/FakeCurrentPrincipalAccessor.cs#L10

**Comment by leonkosak** [comment]
How this issue is closed if there is still error?

**Comment by wakuflair** [comment]
Your should now inherit `ThreadCurrentPrincipalAccessor`.

**Comment by leonkosak** [comment]
Oh, I see now.
