### ISSUE TITLE
Question: How do you add an action to a Navigation Property Picker / Modal Ui

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#4059]
How do you add a new action like (+ New Entity) to a Navigation Property picker, or it's modal picker so the user can create a new Entity if the one they're looking for doesn't exist?

![image](https://user-images.githubusercontent.com/8544833/82695151-8dd3fe80-9c32-11ea-9e87-787e1de07675.png)

![image](https://user-images.githubusercontent.com/8544833/82694945-2918a400-9c32-11ea-94bf-7f0ba022d4a8.png)

**Comment by liangshiw** [comment]
Please write ABP Commercial related questions to the https://support.abp.io/
