### ISSUE TITLE
Ideas to make abp.io web site more "live"

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4061]
- Add the latest version info to he home page
- Add GitHub star count (and give a star link)
~~- Last community article to the home page~~ (done)
- Add "latest blog post" info/link to the abp.io home page

All these are my ideas, we should discuss about them.

**Comment by iyilm4z** [comment]
Just fyi, [this](https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/_screenshots/module-zero-core-template-ui-home.png) is the latest home page of module-zero-core-template. On that page, we put some important infos for devs to choose your framework like contributor count, watching-by count, used-by/dependents-on count etc.
