### ISSUE TITLE
Error generating API service with parameter enumeration

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#4064]
**My Api:**
 ```
 public async Task<List<TagDto>> GetListByTypeAsync(TagType type)
{
........
}
```
**Generating Service:**
```
getListByTypeByType(params = {} as TagType): Observable<TagDto[]> {
    return this.restService.request({ url: '/api/com/tag/byType', method: 'GET', params }, { apiName: this.apiName });
  }
```
**The TagDto is Enum**

**Error Message:**

> `The expected type comes from property 'params' which is declared here on type 'HttpRequest<unknown> | Request<unknown>'`

**Comment by hexianggui** [comment]
**I have to change it manually:**
'params' to 'params: {params}'

**Comment by maliming** [comment]
Please share the definition of `TagType`.

**Comment by hexianggui** [comment]
```
[Flags]
public enum TagType
{
    Default,
    Linkman,
    Customer,
    ContactWay,
    Undefined
}
```

**Comment by maliming** [comment]
Have you tried creating a Dto for `TagType`?

```c#
public class GetListByTypeInput
{
     public TagType Type { get; set; }
}

```

**Comment by hexianggui** [comment]
I just used the DTO, and it's OK.
Maybe the parameter can't be a value type.
It's only true if it's an object.
hope it gets better and better for abp.

**Comment by hikalkan** [comment]
closing this since we are completely re-writing the angular proxy-generation: https://github.com/abpframework/abp/issues/4881
