### ISSUE TITLE
Re-run gulp when using 'update' multiple times on the Abp.Cli

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#4065]
There has been a few occasions now where I have run the cli to upgrade my project and it fails to successfully run yarn or gulp. Ideally I'd like to just run the cli update command again so that it runs gulp again but when I try to do that it seems to not do it.

For example, this time gulp could not delete the 'fortawesome' directory inside the 'wwwroot' folder. I deleted the folder myself and had to manually run yarn and gulp to finish the upgrade.

**Comment by hikalkan** [comment]
We will consider this in the next version. Thanks.

**Comment by yekalkan** [comment]
I don't think running `yarn` & `gulp` is a hard task compared to running `abp update` again.
