### ISSUE TITLE
How to set SupportsMultipleTimezone true and DateTimeKind to UTC

### ISSUE THREAD

**Issue by AhmadAlMunajjed** [abpframework/abp#4067]
How to set SupportsMultipleTimezone to true and DateTimeKind to UTC in all modules? 

Thanks a lot

**Comment by liangshiw** [comment]
Try:

`Configure<AbpClockOptions>(options => options.Kind = DateTimeKind.Utc);`

**Comment by AhmadAlMunajjed** [comment]
It workes, thanks!
