### ISSUE TITLE
Mvc start template login/register layout bug

### ISSUE THREAD

**Issue by GerryGe** [abpframework/abp#4069]
Mvc start template login/register layout bug

![layout](https://user-images.githubusercontent.com/6952917/82733341-bd276000-9d45-11ea-822f-2241f40cd031.gif)

![image](https://user-images.githubusercontent.com/6952917/82733494-cc5add80-9d46-11ea-9b12-8e3821cb3b49.png)

Changing the width of the browser results in the login/register part is so narrow, it's not as wide as origin.

**Comment by hikalkan** [comment]
Thank you for reporting this. Will be fixed in the next release.
