### ISSUE TITLE
Text Template System

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#407]
I've created a simple email template system to send localized emails with placeholders replaced by values on the runtime.

We can create a general-purpose templating system that can be integrated to templating existing libraries and play well with the Virtual File System and Localization features of ABP framework.

**Comment by hikalkan** [comment]
We should check https://github.com/toddams/RazorLight for insance.

**Comment by natiki** [comment]
Something like https://github.com/andrewdavey/postal would also be ideal. It does HTML and Text very easily using Razor syntax.

**Comment by bbakermmc** [comment]
If its specif for email you should look at: 
https://mjml.io/

**Comment by hikalkan** [comment]
I thought it as generic, but will look for mjml too. Thanks.

**Comment by hikalkan** [comment]
This is implemented for email sending (https://github.com/abpframework/abp/pull/1141) using this library: https://github.com/lunet-io/scriban

I keep this issue open. We may generalize it to provide a more generic text templating feature.

**Comment by natiki** [comment]
@hikalkan how does scriban specifically deal with email templating? I don't see how it deals with plain text vs HTML templating etc.?

**Comment by maliming** [comment]
hi @natiki 

Scriban is an engine that processes text templates. So it can handle all the text of html, md, etc.

At the same time scriban is also a very active project, compatibility is also very good.
Support for advanced template syntax.

If you have other equally powerful text template engine class libraries, you can also replace it.

**Comment by natiki** [comment]
@maliming Understood.... Was just hoping that this would tie in easily to be able to use MVC to send emails like [Postal](https://github.com/andrewdavey/postal) or simlair.
