### ISSUE TITLE
Document may be wrong

### ISSUE THREAD

**Issue by cicna** [abpframework/abp#4075]
https://docs.abp.io/zh-Hans/abp/latest/Startup-Templates/Module
**Document may be wrong，last step can not login？**
run .Web.Host use : admin password: 1q2w3E* login to application.

An unhandled exception occurred while processing the request.
SocketException: 由于线程退出或应用程序请求，已中止 I/O 操作。
Unknown location

IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.
System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

TaskCanceledException: The operation was canceled.
System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Steps needed to **reproduce** the problem.
