### ISSUE TITLE
It is not work to modify the listening port

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#4076]
![image](https://user-images.githubusercontent.com/14011792/82748566-8dc03400-9dd5-11ea-9d1a-2a377547fe7e.png)
```
internal static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseUrls("http://localhost:5003", "https://localhost:5004");
                })
                .UseAutofac()
                .UseSerilog();
```
I changed the port, but the website is still listening 5000

**Comment by liangshiw** [comment]
I can't reproduce your problem, and I think it has nothing with abp, Please check microsoftion document https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1

![image](https://user-images.githubusercontent.com/16813853/82748741-e6440100-9dd6-11ea-957d-64c85b87b952.png)

**Comment by wingqing1314** [comment]
![image](https://user-images.githubusercontent.com/14011792/82749219-31abde80-9dda-11ea-89b2-101427d62ac5.png)
Maybe because of I replaced the configuration.When I comment out the code，it works.

But I don't know why

**Comment by maliming** [comment]
@wingqing1314 This issue has nothing to do with abp. 
You can check the source code of ASPNET Core's `UseUrls `to see why.
