### ISSUE TITLE
abp TenantId is not Guid

### ISSUE THREAD

**Issue by 842549829** [abpframework/abp#4086]
ABP Framework version 2.6.0
User Interface Mvc

    public class BasicTenantInfo
    {
        public BasicTenantInfo(Guid? tenantId, string name = null);
        public Guid? TenantId { get; }
        public string Name { get; }
    }

TenantId "4ab5f021-34l8-4a9c-a7a2-773fb4697013"   is not Guid
new BasicTenantInfo(Guid.Parse("4ab5f021-34l8-4a9c-a7a2-773fb4697013"), name?.Value)
Guid string should only contain hexadecimal characters.

expect

    public class BasicTenantInfo
    {
        public BasicTenantInfo(string tenantId, string name = null);
        public string TenantId { get; }
        public string Name { get; }
    }

**Comment by liangshiw** [comment]
Tenant entity primary key is GUID

https://github.com/abpframework/abp/blob/3109e6ea7618356c01f3ca99dad5f0cbb387a0a2/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/Tenant.cs#L9

**Comment by 842549829** [comment]
ABP Can't restrict Tenant entity primary key type

**Comment by liangshiw** [comment]
A guid should not contain any q

**Comment by liangshiw** [comment]
A guid should not contain any l.

A GUID is a 16-byte (128-bit) number, typically represented by a 32-character hexadecimal string. A GUID (in hex form) need not contain any alpha characters, though by chance it probably would. If you are targeting a GUID in hex form, you can check that the string is 32-characters long (after stripping dashes and curly brackets) and has only letters A-F and numbers.

**Comment by 842549829** [comment]
I see. But I mean can the ABP framework entity primary key be any type? Or add the plan to the next milestone.

**Comment by liangshiw** [comment]
Your own entity can be any type. Module predefined entities cannot change type (You can implement by changing the source code).

**Comment by 842549829** [comment]
I want to modify the source code implementation But may affect future updates to the ABP framework.

**Comment by fmpfmp** [comment]
us guid as primary key type is a bad design
