### ISSUE TITLE
Bad description of "Bootstrap Tag Helpers & Dynamic Forms" on abp.io main page

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#4091]
The description of "Bootstrap Tag Helpers & Dynamic Forms" on abp.io main page "Strong infrastructure" section talks about .NET jobs, not Razor pages.
![image](https://user-images.githubusercontent.com/32323613/82829848-8c196d80-9eb4-11ea-9fee-220dd8be5a63.png)

**Comment by maliming** [comment]
We will update it, thanks for your feedback.
