### ISSUE TITLE
Micrsoservice Demo: AuthServerDataSeeeder should read from appsettings?

### ISSUE THREAD

**Issue by Sen-Gupta** [abpframework/abp#4093]
ABP Core, Latest, MVC
Micrsoservice Demo

Snippets from AuthServerDataSeeder.cs

await CreateClientAsync(
                "console-client-demo",
                new[] { "BloggingService", "IdentityService", "InternalGateway", "ProductService", "TenantManagementService" },
                new[] { "client_credentials", "password" },
                commonSecret,
                permissions: new[] { IdentityPermissions.Users.Default, TenantManagementPermissions.Tenants.Default, "ProductManagement.Product" }
            );
            
            await CreateClientAsync(
                "backend-admin-app-client",
                commonScopes.Union(new[] { "BackendAdminAppGateway", "IdentityService", "ProductService", "TenantManagementService" }),
                new[] { "hybrid" },
                commonSecret,
                permissions: new[] { IdentityPermissions.Users.Default, "ProductManagement.Product" },
                redirectUri: "http://localhost:51954/signin-oidc",
                postLogoutRedirectUri: "http://localhost:51954/signout-callback-oidc"
            );

            await CreateClientAsync(
                "public-website-client",
                commonScopes.Union(new[] { "PublicWebSiteGateway", "BloggingService", "ProductService" }),
                new[] { "hybrid" },
                commonSecret,
                redirectUri: "http://localhost:53435/signin-oidc",
                postLogoutRedirectUri: "http://localhost:53435/signout-callback-oidc"
            );

            await CreateClientAsync(
                "blogging-service-client",
                new[] { "InternalGateway", "IdentityService" },
                new[] { "client_credentials" },
                commonSecret,
                permissions: new[] { IdentityPermissions.UserLookup.Default }
            );
 

Is it possible to read redirectUri na postLogoutRedirectUri from envrionment configs?

Am I missing something?

**Comment by liangshiw** [comment]
You can inject `IConfiguration` in  AuthServerDataSeeder class.
