### ISSUE TITLE
Mapping ObjectMapper with NotNull parameter

### ISSUE THREAD

**Issue by TuyenDinh1205** [abpframework/abp#4096]
Hi all!
I have problem with mapping object with not null parameter i'm using version 2.8
When i insert parameter like this 
![API1](https://user-images.githubusercontent.com/34994601/82870264-dd2f6d00-9f59-11ea-83b7-7aa0ff18eace.PNG)
In Backend Service I have receive this parameter
![API2](https://user-images.githubusercontent.com/34994601/82870422-1ff14500-9f5a-11ea-8cf7-28d2e0cafff5.png)
But when mapping, my parameter is null and it show error
![API3](https://user-images.githubusercontent.com/34994601/82870494-41eac780-9f5a-11ea-84f0-e95a5ab5548a.png)
![API4](https://user-images.githubusercontent.com/34994601/82870516-48793f00-9f5a-11ea-85fa-89921af5cdbd.png)
If i set it can be null it mapping between AlbumCreateDto & Album completely
I don't know why. Please help me
Thanks

**Comment by maliming** [comment]
Please share the code of `Album` class.

**Comment by TuyenDinh1205** [comment]
Here is my AlbumCreateDto class:
![API5](https://user-images.githubusercontent.com/34994601/82903283-eedd3880-9f8a-11ea-8cd7-09c36d13e950.png)
And Album class:
![API6](https://user-images.githubusercontent.com/34994601/82903336-fe5c8180-9f8a-11ea-8f45-f626358fc268.png)
![API7](https://user-images.githubusercontent.com/34994601/82903344-01577200-9f8b-11ea-9d6f-c69416ef5fea.png)

**Comment by maliming** [comment]
Try create a protected empty constructor in `Album `class.

This is an automapper problem, you can refer to https://docs.automapper.org/en/stable/Construction.html

According to best practices, you should manually create the aggregate root object.
https://docs.abp.io/en/abp/latest/Best-Practices/Entities
https://docs.abp.io/en/abp/latest/Application-Services

**Comment by TuyenDinh1205** [comment]
Thanks so much
