### ISSUE TITLE
Console Application OnApplicationInitialization Error

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#4102]
Hi,

I'm using abp v2.8.0. I've got an error when start console app like below. How to get ApplicationBuilder when Initialize ?

![image](https://user-images.githubusercontent.com/46510130/82887708-94d07900-9f72-11ea-93d8-e04e98978c5c.png)

**Comment by liangshiw** [comment]
Try

```csharp
[DependsOn(typeof(AbpAspNetCoreModule))]
```

**Comment by volethanh** [comment]
Thanks @liangshiw . The issue is solved but `GetApplicationBuilder` is still null

![image](https://user-images.githubusercontent.com/46510130/82965353-14515d00-9ff2-11ea-9fa5-0fec6ddaffc7.png)

**Comment by liangshiw** [comment]
Please provide steps to reproduce this problem.

**Comment by volethanh** [comment]
I generate a ConsoleApp based on new template of version 2.8.0
Then I added the following packages because I want to use Hangfire and host it in the console app

![image](https://user-images.githubusercontent.com/46510130/82974584-85017500-a004-11ea-92bf-13375dc4e8c7.png)

In the module class, I added the depends as the following 

![image](https://user-images.githubusercontent.com/46510130/82974686-bf6b1200-a004-11ea-9163-067ccbcee8a2.png)
![image](https://user-images.githubusercontent.com/46510130/82974706-d0b41e80-a004-11ea-9d53-53d3e5c15417.png)

**Comment by liangshiw** [comment]
Pipeline is used to process http requests but it's just a console application.
You can use ASPNET Core Application , see https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-Application.
