### ISSUE TITLE
Will ABP vNext be integrated with net core desktop UI program? 

### ISSUE THREAD

**Issue by LostAsk** [abpframework/abp#4104]
Will ABP vNext integrate the MVVM framework with the net core desktop UI program? For example, WPF. Many MVVM frameworks have built-in Di, such as prism, which should be the mainstream of MVVM.

**Comment by liangshiw** [comment]
Prism does not seem to support standard DI: https://github.com/PrismLibrary/Prism/issues/1765.
You can create issue on https://github.com/PrismLibrary/Prism/issues/new/choose.

**Comment by LostAsk** [comment]
> Prism似乎不支持标准DI：[PrismLibrary / Prism＃1765](https://github.com/PrismLibrary/Prism/issues/1765)。
> 您可以在https://github.com/PrismLibrary/Prism/issues/new/choose上创建问题。

I don't know much about standard Di. Does standard Di support the form of resolve < T > (string name), and how can I describe the problem on prism

**Comment by leonkosak** [comment]
I would say that currently "GUI technology" with the highest priority right now is Blazor UI.
Even ASP.NET Zero has no desktop thin-client (WPF/WinForms) option.
