### ISSUE TITLE
Mysql：Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by iimax** [abpframework/abp#4118]
* ABP v2.8.0
* UI Framework: Angular
* MySQL v5.6
* Steps needed to **reproduce** the problem.

1. abp new Acme.BookStore -t app -u angular
2. ref  [Switch to EF Core MySQL Provider](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL)
3. run the **.DbMigrator** project

logs:
2020-05-27 16:28:38.136 +08:00 [INF] Started database migrations...
2020-05-27 16:28:38.210 +08:00 [INF] Migrating schema for host database...
2020-05-27 16:28:55.437 +08:00 [ERR] Failed executing DbCommand (37ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
CREATE TABLE `IdentityServerPersistedGrants` (
    `Key` varchar(200) CHARACTER SET utf8mb4 NOT NULL,
    `Id` char(36) NOT NULL,
    `ExtraProperties` longtext CHARACTER SET utf8mb4 NULL,
    `ConcurrencyStamp` longtext CHARACTER SET utf8mb4 NULL,
    `Type` varchar(50) CHARACTER SET utf8mb4 NOT NULL,
    `SubjectId` varchar(200) CHARACTER SET utf8mb4 NULL,
    `ClientId` varchar(200) CHARACTER SET utf8mb4 NOT NULL,
    `CreationTime` datetime(6) NOT NULL,
    `Expiration` datetime(6) NULL,
    `Data` longtext CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK_IdentityServerPersistedGrants` PRIMARY KEY (`Key`)
);
got 1071 - Specified key was too long; max key length is 767 bytes

**Comment by maliming** [comment]
https://github.com/abpframework/abp/search?q=Specified+key+was+too+long&type=Issues

**Comment by liquehuo** [comment]
@iimax  Hello, have you solved it?
