### ISSUE TITLE
Geolocation support

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#4120]
Hi,

Is there a way to support Geolocation data & geolocation queries.

For now, abp support basic types, but both:
- Geolocation points
- Geolocated queries

Are specific by data provider, I mean that for Mongo it is GeoJsonPointby example.
If I use GeoJsonPoint it is no more generic.

Also, by using linq, how can I do some geolocation based queries, by example get the closest item etc.

any idea ?

**Comment by leonkosak** [comment]
https://www.markopapic.com/finding-nearby-users-using-ef-core-spatial-data/

**Comment by wjkhappy14** [comment]
**Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite**

 Configure<AbpDbContextOptions>(options =>
            {
                options.UseSqlServer(x => x.**UseNetTopologySuite**());
            });
