### ISSUE TITLE
Localization files for Arabic and French culture

### ISSUE THREAD

**Issue by f-belhocine** [abpframework/abp#4121]
### Modules Locales Translation to Arabic and French
Hi all,
 I want to thank you for the great work you did and do.
I want to contribute for translating ABP module locales for Arabic and French, as i saw the Arabic is done by others, so can i work on French locales.

Thank you in advance

**Comment by hikalkan** [comment]
That would be a great contribution. I will be easier after https://github.com/abpframework/abp/issues/4072 release. So, please wait until thursday - you can start once v2.9 released.

If you have any difficulties, please write here.

Thanks.

**Comment by f-belhocine** [comment]
Great, I'll wait and try to use ABP Tanslate CLI.

**Comment by maliming** [comment]
hi @f-belhocine 
CLI translate command is already available.
https://docs.abp.io/en/abp/latest/CLI#translate

**Comment by f-belhocine** [comment]
Arabic translation in PR  : #4915 for Abp framework.

**Comment by hikalkan** [comment]
I am closing this issue. You can send PR when you are ready. Thanks :)

**Comment by badre429** [comment]
@hikalkan  just added french culture in the pr #5494
