### ISSUE TITLE
List<Guid> not supported in the Services

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#4123]
Hi,

I have a service, this one contains a method with a List<Guid> parameter:

`public async Task<StoreDto> GetClosestAsync(double latitude, double longitude, List<Guid> storeIds);`

When I try to call it, I got an exception with the following message:

> The following errors were detected during validation.
>  - The value 'System.Collections.Generic.List`1[System.Guid]' is not valid.

So, I tried several solutions, but what is strange is when I change the method signature to:

`public async Task<StoreDto> GetClosestAsync(double latitude, double longitude, string[] storeIds);`

In this case, there is no exception, but 

> storeIds[0] = "System.String[]"

It seems to be an error when passing parameters to a service. Noticed that I have also tried with a DTO, Collection etc... as defined in the Best Practices.

Do you have any solution, idea to solve this problem ?

Thanks

**Comment by vd3d** [comment]
I have found the solution, I have to use HttpPut (instead of HttpGet) !

**Comment by maliming** [comment]
This is like an MVC model binding problem.
