### ISSUE TITLE
FileSystemBlobProvider Ehnancements

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4126]
[FileSystemBlobProvider](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BlobStoring.FileSystem/Volo/Abp/BlobStoring/FileSystem/FileSystemBlobProvider.cs) improvement notes:

- [ ] Implement all methods truly async (if possible)!
- [ ] What if the file is being used on create, delete or read? Can we prevent it or implement re-try?

**Comment by hitaspdotnet** [comment]
This is a simple (not tested) idea:
```Cs
    private bool FileCanBeRead(string filepath)
    {
        try
        {
            File.Open(filepath, FileMode.Open, FileAccess.Read).Dispose();
            return true;
        }
        catch (IOException)
        {
            return false;
        }
    }
```
