### ISSUE TITLE
Async calls for Generic Repositories

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#4141]
Hi,

I am following the documentation on generic repositories (https://docs.abp.io/en/abp/master/Repositories#generic-repositories)

I see that the example using the generic repository is a synchronous method. Is that a limitation?

Is it correct to say the generic repository does not extend the EF Core async linq extensions? (https://docs.microsoft.com/en-us/ef/core/querying/async)

I am guessing I will have to create a domain class for me to have asynchrony

**Comment by liangshiw** [comment]
The repository interface provides asynchronous methods,there is no synchronous method.

> GetList method uses the standard LINQ Where and ToList methods to filter and get a list of people from the data source.

These are the **extension methods** provided by EF Core for the IQueryable interface. EF Core also provides asynchronous methods.

**Comment by tinonetic** [comment]
Thank-you for responding.

Please share the link with this documentation.

I would like to do something similar to the following "pseudocode":

`
//where _myEntityRepository is of type IRepository<MyEntity>

var result = _myEntityRepository.Where(x => x.Type == "foo").FirstOrDefaultAsync(); 
`

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Entity-Framework-Core
You can custom repository to access ef core api. you can also using `Microsoft.EntityFrameworkCore` in class to use extension methods.

**Comment by tinonetic** [comment]
Thanks.

So it's correct then that if I use `IRepository<MyEntity>`, I cannot make asyncronous calls? 

Any chance that may be included in a future release? 

I realise I meant to say custom repository in my question.

**Comment by tinonetic** [comment]
Not to worry, found the answer! 

It **is possible** to through generic repository `IRepository<>` 

Found the solution by searching through the Microservice demo

**The Repository**
```c#
private readonly IRepository<Product, Guid> _productRepository;
```

**The code**
```c#
var products = await _productRepository
                .OrderBy(input.Sorting ?? "Name")
                .Skip(input.SkipCount)
                .Take(input.MaxResultCount)
                .ToListAsync();
```
