### ISSUE TITLE
Uglify ES6 support or upgrade ES6 version

### ISSUE THREAD

**Issue by atak946** [abpframework/abp#4143]
Hi,

i'm use abp .net core mvc application.

i have one question in uglify.

I noticed that abp does bundle using uglify, but the version of the uglify package used in abp does not support ES6. When I researched the Uglify package, I saw that it also has ES6 supporting version.

How do I update the uglify package to the version that supports ES6, or when can you provide this support?

ES6 is very important to us in the use of javascript.

I would be glad if you can share information on this subject.

**Sample Exception**

```
NUglifyException: 
run-time error JS1317: 
Unable to convert from reference to binding: 
await new Promise(async __bundles/D7D567AB5D651BD2227A204B9BE8BCF3.D7D567AB5D651BD2227A204B9BE8BCF3.js(409,6): 
```

Best regards

**Comment by maliming** [comment]
hi

Abp is using the NUglify library(v1.5.13 https://github.com/xoofx/NUglify/)


> When I researched the Uglify package, I saw that it also has ES6 supporting version.

Can you point out relevant information?

**Comment by atak946** [comment]
> hi
> 
> Abp is using the NUglify library(v1.5.13 https://github.com/xoofx/NUglify/)
> 
> > When I researched the Uglify package, I saw that it also has ES6 supporting version.
> 
> Can you point out relevant information?

https://www.npmjs.com/package/uglify-es
i found this.

**Comment by maliming** [comment]
This is a nodejs package, we need the nuget package.
