### ISSUE TITLE
Why does _ViewStart not work

### ISSUE THREAD

**Issue by hanfeige** [abpframework/abp#4146]
I added the _ViewStart file to the pages directory to implement my own UI interface to override the basic style. When I ran the program through vs, everything was fine, but when I released it, the style became basic

![image](https://user-images.githubusercontent.com/17940219/83318358-abbee600-a266-11ea-9f2d-1dbd4ff2714e.png)

**vs:**
![image](https://user-images.githubusercontent.com/17940219/83318376-e45ebf80-a266-11ea-8460-917e64404224.png)
**publish:**
![image](https://user-images.githubusercontent.com/17940219/83318411-22f47a00-a267-11ea-99e2-3581797a9535.png)

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/pull/4113
