### ISSUE TITLE
catch a error with add-migration

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#4147]
when I use add-migration in abp vnext, I catch a error, how can I solve the problem? thanks
![image](https://user-images.githubusercontent.com/4489940/83321267-02d1b480-a281-11ea-8ee8-d7c48032259d.png)

**Comment by liangshiw** [comment]
![image](https://user-images.githubusercontent.com/16813853/83321462-76c08c80-a282-11ea-89bb-fcdb124157ef.png)

Please double check your code.

**Comment by ruby0602** [comment]
> ![image](https://user-images.githubusercontent.com/16813853/83321462-76c08c80-a282-11ea-89bb-fcdb124157ef.png)
> 
> Please double check your code.

I use Sqlserver to replace Mysql, the code can work normal

**Comment by liangshiw** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by ruby0602** [comment]
> * Your **ABP Framework version**.
> * Exception message and **stack trace** if available (check the logs).
> * Steps needed to **reproduce** the problem.

the versoin is 2.8

**Comment by ruby0602** [comment]
I solve the problem, but still thank the help from 

> * Your **ABP Framework version**.
> * Exception message and **stack trace** if available (check the logs).
> * Steps needed to **reproduce** the problem.

I solve the problem by myself, but still thank you
