### ISSUE TITLE
Test "sample application with SignalR & Tiered architecture" article

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4151]
The article: https://github.com/volosoft/volo/blob/dev/blog/posts/2020-05-29-Real-Time-Messaging-In-A-Distributed-Architecture-Using-Abp-Framework-SingalR-RabbitMQ/POST.md

I wanted some improvement from @yekalkan then you can test it. Our purpose is that you can be able to re-implement the solution just following the article.

**Comment by AkinSabriCam** [comment]
I followed the docs and created projects.
When I run the project, I got this error after login

![redirectToIdentityUser](https://user-images.githubusercontent.com/37196959/83411608-43683400-a421-11ea-8d3f-cd089d1cc525.PNG)

**Comment by AkinSabriCam** [comment]
- I tested the project by following the steps of  docs, it works correctly.
![chatTest](https://user-images.githubusercontent.com/37196959/83511162-e62eba00-a4d6-11ea-847b-4f28a184329f.PNG)
