### ISSUE TITLE
Create Oracle.EntityFrameworkCore Integration Package

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4160]
It now supports EF Core 3.1.4. It has just been released (2 days ago) and it is currently in beta. However, we can try to integrate it.

**Comment by dicksonkimeu** [comment]
Also, test with Oracle Autonomous Database. Its free for 20gb db.

**Comment by hikalkan** [comment]
Updated the document: https://github.com/abpframework/abp/blob/dev/docs/en/Entity-Framework-Core-Oracle.md

The new package will be released with v3.0.
