### ISSUE TITLE
Microsoft AD Integration

### ISSUE THREAD

**Issue by a-patel** [abpframework/abp#4165]
How to integrate Microsoft AD Integration in ABP Framework?
Is it possible?
Is there any sample application for that?
Is there documentation for that?

**Comment by Znow** [comment]
Like Azure AD? Please search through the issues, several issues have examples of the implementation, and the documentation is available here: https://docs.abp.io/en/abp/master/How-To/Azure-Active-Directory-Authentication-MVC

**Comment by a-patel** [comment]
Like local Windows AD.
e.g. Corporate Office AD Accounts

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/issues/1189

**Comment by leonkosak** [comment]
@liangshiw It's not clear how to use Volo.Abp.Ldap in conjunction with generating JWT token.
The "strict Microsoft AD enterprises" always require that all users are defined only in AD or at least, that application user is seamlessly connected to AD user. When AD user has changed password, it should be "invisible" for him/her when doing login to web application (like abp.io). Such user will type new password in web application and he/she should be authenticated without any issues.
