### ISSUE TITLE
Consider to remove inheriting from a base class for pages (cshtml files)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4175]
While it works on runtime, it doesn't play well with the IDE (tested on Visual Studio & Rider):

![image](https://user-images.githubusercontent.com/1210527/83467319-3fb8c980-a482-11ea-850c-abba3342c9b4.png)

We should find a solution to this problem (since it makes harder to use intellisense in views) or remove inheritance and add @inject directives for the inherited properties when needed.

We had used this style of inheritance on some module and template pages (I am not sure about templates).

**Comment by maliming** [comment]
@hikalkan 
We can’t use `@model` and `@inherits` on the same page. We can have `@inherits` in a `_ViewImports.cshtml` file that the Razor page imports. 

![image](https://user-images.githubusercontent.com/6908465/83501640-fc4a7380-a4f2-11ea-849c-b80e4451a6f7.png)

**Comment by hikalkan** [comment]
@maliming we can relove all inheritances, it has no much benefit.
