### ISSUE TITLE
The mail configuration does not take effect

### ISSUE THREAD

**Issue by hanfeige** [abpframework/abp#4179]
The basic configuration for sending mail is set, but it doesn't seem to work
You can see that the default localization Settings are in effect, but the Host for the message is not

![image](https://user-images.githubusercontent.com/17940219/83491112-d1a4ee80-a4e3-11ea-8641-03cdbff4ed07.png)

![image](https://user-images.githubusercontent.com/17940219/83491058-b5a14d00-a4e3-11ea-9c91-afceaa720fa0.png)

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Settings#change-setting-definitions-of-a-depended-module
