### ISSUE TITLE
Use string value for CreatorId, LastModifierId and DeleterId

### ISSUE THREAD

**Issue by abxeps** [abpframework/abp#4182]
Hi,
We would like to write the user name (some string value) instead of user Id (guid) when saving entities to the database.
Is it possible to override the CreatorId and LastModifierId fields in order to do that?
Best regards,

**Comment by gdlcf88** [comment]
I think you can do these:

1. Create an abstract class MyFullAuditedAggregateRoot with extra audit properties like CreatorName and make your aggregate roots inherit it.

2. Implement the **IAuditPropertySetter** yourself and replace the default implementation. Refer to:
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditPropertySetter.cs#L24-L40

**Comment by abxeps** [comment]
That works indeed.
It would be great if it could be done without overwriting code from the framework.
Is that possible somehow?

**Comment by maliming** [comment]
> Is that possible somehow?

The framework already allows you to customize and extend it. : )

**Comment by alexandis** [comment]
Could you please let me know how to "replace the default implementation"? I've tried to use IocManager, but no luck so far.

**Comment by maliming** [comment]
@alexandis Please check the official documentation  https://docs.abp.io/en/abp/latest/How-To/Index

**Comment by alexandis** [comment]
> @alexandis Please check the official documentation https://docs.abp.io/en/abp/latest/How-To/Index
Ok, great - do you mean it is supposed to be done via `PreConfigure<Something>` in `PreConfigureServices`? If so, I have no any clue what Something should be, sorry.
