### ISSUE TITLE
Cors Issues using angular 8 .Net Core template version 4.8.0

### ISSUE THREAD

**Issue by marcelluswalace** [abpframework/abp#4190]
Hello, 
I have a problem with the cors; When I working on my localhost everything is super but in production, for any get api call from UI to back end its working but for as soon as I do a delete or an update api call I get this: Access to XMLHttpRequest at 'http://#########:21021/api/services/app/Scheduler/Delete?Id=5' from origin 'http://#########:4202' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Only if I do a delete or an update. My cors policies are updated like required. on UI side like so
  "remoteServiceBaseUrl": "http://#########:21021",
  "appBaseUrl": "http://#########:4202",

On the backend side I have this:

  "App": {
    "ServerRootAddress": "http://#########:21021/",
    "ClientRootAddress": "http://#########:4202/",
    "FileFolder": "C:\\Files",
    "SendErrorToClient": true,
    "CorsOrigins": "http://localhost:4200,http://localhost:4202,http://#########:4200,http://#########:4202",

Can somebody explain to me what I am doing wrong? if I am doing something wrong? 

Web site deployed on windows 10 is working fine. But as soon as it is windows server this issue pops up?

Regards

**Comment by maliming** [comment]
It looks like you are using aspnetboilerplate instead of abp.

**Comment by marcelluswalace** [comment]
Sorry I didnt know there were a difference. it is aspnetboilerplate yes

**Comment by liangshiw** [comment]
Please create issue on https://github.com/aspnetboilerplate/aspnetboilerplate/issues/new
