### ISSUE TITLE
Catching UI language change on other layers

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#4192]
Using the latest ABP framework version (2.8) for my AspNet Core 3.1 solution, I still can’t see the proper way to catch current UI language change event on the web site from other layers.

Whereas I understand it’s possible to plug into each request for app, I think it’s not good approach. I can see it’s possible to add a culture request provider, but it’s not possible to use some sort of subscription for existing ones.

Specifically: one of my DB entities is filtered based on the currently selected UI language and I need to reload it if this language changes.

**Comment by maliming** [comment]
hi

I don’t quite understand your use case. 
I think you just need to use `CultureInfo.CurrentCulture/CultureInfo.CurrentUICulture` directly.

**Comment by alexandis** [comment]
Hi. I’ve already tried that. I put breakpoint in OnModelCreating and it doesn’t get fired when I switch UI language.

**Comment by maliming** [comment]
`OnModelCreating` will only run once, I don't know why you are trying to use currentin this method.

**Comment by alexandis** [comment]
Ok, so we return to my initial problem: I need to automatically filter out DB entity based on currently selected UI language (including the case when user changes it). And I would not like to do that check on each app request, thought should be other way like subscription to some event...

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Data-Filtering#defining-custom-filters

**Comment by alexandis** [comment]
> https://docs.abp.io/en/abp/latest/Data-Filtering#defining-custom-filters
I see, fine. But does it mean I have to write something like ...[myEntity].IsLicenceType... in each query to trigger `CreateFilterExpression` call? If so - it's not exactly what I want. I don't want user to forget putting the filter somewhere: indeed, `LicenceType` entity is ALREADY of a _licence type_ and  I need this filter to be applied invisibly and automatically - i.e. the filter needs to be applied everywhere this entity occurs in the linq query. In fact, I even don't need the interface, because only LicenceType entity will be of a licence type :)
So, I've tried to override ShouldFilterEntity (returning true if my entity is LicenceType) and CreateFilterExpression and still not sure the filter is applied on each http request considering language change...

**Comment by alexandis** [comment]
It did not work in a way I wanted. However, I have resolved the issue by introducing new property in `DbContext`, re-initializing it in the constructor each time with current language and using this property inside `HasQueryFilter`.
