### ISSUE TITLE
How to change validation localization?

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#4199]
![image](https://user-images.githubusercontent.com/14011792/83627483-911fa080-a5c9-11ea-98b1-7261bad898b9.png)
How to use the resource in the picture

**Comment by maliming** [comment]
Please check the official documentation before asking questions: https://docs.abp.io/en/abp/latest/Localization

**Comment by wingqing1314** [comment]
> Please check the official documentation before asking questions: https://docs.abp.io/en/abp/latest/Localization

I followed the documentation and it didn't work
![image](https://user-images.githubusercontent.com/14011792/83632076-325e2500-a5d1-11ea-9e64-9175816f7935.png)
![image](https://user-images.githubusercontent.com/14011792/83632108-4144d780-a5d1-11ea-86ac-0a2ace741e9d.png)
