### ISSUE TITLE
ICurrentUser

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#42]
* Should be more and easier extensible, by extension methods?.
* It should work by claims by default.

By default, it will only contain UserId. TenantId, Impersonator informations, organization units... should all be extensions.

**Comment by abllyboy** [comment]
hi , how can I add my claims into ClaimsIdentity so I can use it from CurrentUser? I try to add "organize" below but doesn't work.
```
public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            var app = context.GetApplicationBuilder();

            app.UseCorrelationId();
            app.UseVirtualFiles();
            app.UseRouting();
            app.UseAuthentication();

            app.Use(async (ctx, next) =>
            {
                var currentPrincipalAccessor = ctx.RequestServices.GetRequiredService<ICurrentPrincipalAccessor>();
                var map = new Dictionary<string, string>()
                {
                    { "sub", AbpClaimTypes.UserId },
                    { "role", AbpClaimTypes.Role },
                    { "email", AbpClaimTypes.Email },
                    //any other map
                };
                var mapClaims = currentPrincipalAccessor.Principal.Claims.Where(p => map.Keys.Contains(p.Type)).ToList();
                var claimIdentity = new ClaimsIdentity(mapClaims.Select(p => new Claim(map[p.Type], p.Value, p.ValueType, p.Issuer)));
                claimIdentity.AddClaim(new Claim("organize","1111111"));
                currentPrincipalAccessor.Principal.AddIdentity(claimIdentity);
                await next();
            });
......

**Comment by hikalkan** [comment]
Don't create a new Identity, but add your claims to existing Identity: 

````csharp
var identity = currentPrincipalAccessor.Principal?.Identities.FirstOrDefault();
if (identity != null)
{
    identity.AddClaim(...);
}
````

BTW, in this way you are adding the claim in every request. If that's you want, it's OK. But, we generally want to add a claim to the authentication cookie/ticker while the user is logging in. To do that;

1. Create a class inheriting from the `[AbpUserClaimsPrincipalFactory](https://github.com/abpframework/abp/blob/8e20aab617205936c299ed5c3c40e0c529a3f06b/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L25-L38)` class (say MyUserClaimsPrincipalFactory) and override the CreateAsync method. 

2. Find the claim value from somewhere (you can inject a service for example) and add the the ClaimsPrincipal. Do it like how AbpUserClaimsPrincipalFactory is doing it.

3. Replace the AbpUserClaimsPrincipalFactory with your class by pre-configuring the IdentityBuilder in the PreConfigureServices of your module:

````csharp
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<IdentityBuilder>(builder =>
    {
        builder.AddClaimsPrincipalFactory<MyUserClaimsPrincipalFactory>();
    });
}
````

**Comment by abllyboy** [comment]
Thank you for your patience answer,I'll try this.

**Comment by thk-liu** [comment]
When I create the code in your way, the class no work and breakpoints .Could you help me?
the code like this:
1.public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            
            //base.PreConfigureServices(context);

            PreConfigure<IdentityBuilder>(builder =>
            {
                builder.AddClaimsPrincipalFactory<UserClaimsPrincipalFactory>();
            });
        }
2.public class UserClaimsPrincipalFactory : UserClaimsPrincipalFactory<IdentityUser, IdentityRole>, ITransientDependency
    {
        private readonly IRepository<IdentityUser, Guid> _identityUsers;

        public UserClaimsPrincipalFactory(
            IRepository<IdentityUser, Guid> identityUsers,
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IOptions<IdentityOptions> options)
            : base(
                  userManager,
                  roleManager,
                  options)
        {
            _identityUsers = identityUsers;
        }

        [UnitOfWork]
        public async override Task<ClaimsPrincipal> CreateAsync(IdentityUser user)
        {
            //this method did not execute 
            Console.WriteLine("-------------------------------------");
            var principal = await base.CreateAsync(user).ConfigureAwait(false);

            if (user.TenantId.HasValue)
            {
                principal.Identities
                    .First()
                    .AddClaim(new Claim(AbpClaimTypes.TenantId, user.TenantId.ToString()));
            }
            var tt = user.Claims;
            if (user.Claims != null && user.Claims.Count > 0)
            {
                foreach (var item in user.Claims)
                {
                    principal.Identities
                    .First()
                    .AddClaim(new Claim(item.ClaimType, item.ClaimValue));
                }
            }
            return principal;
            //return base.CreateAsync(user);
        }
    }

**Comment by maliming** [comment]
@thk-liu 

Your code worked for me.

![image](https://user-images.githubusercontent.com/6908465/73037704-fe3c6000-3e8a-11ea-9119-7e0666143297.png)

**Comment by Stirda** [comment]
@maliming Currently I add a claim by following the [ClaimsPrincipalFactory-way](https://github.com/abpframework/abp/blob/8e20aab617205936c299ed5c3c40e0c529a3f06b/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L25-L38). How to migrate to the new `AbpClaimsMapMiddleware` ? I don't know where to set the value. Browsing [recent middleware commit](https://github.com/abpframework/abp/commit/b70497eb6c6c03e692f5e186d38333b4258ed92c) doesn't help me to answer this particular question.

**Comment by maliming** [comment]
`AbpClaimsMapMiddleware `  is to replace some cliams. It doesn't seem to be related to your question.

https://github.com/abpframework/abp/issues/3975

**Comment by journey191** [comment]
@maliming 
code worked for me,but I can't get my claims from CurrentUser by this way:
`var allClaims = _currentUser.GetAllClaims();` or  `var allClaims = _currentPrincipalAccessor.Principal.Claims.ToList();`
![UX3HN~5@(YH`G`F2~5KERES](https://user-images.githubusercontent.com/11626700/97797490-7e80c480-1c58-11eb-9a5c-aa4934b524f8.png)
![S8OW} 1{U%XW9 VL58JS VH](https://user-images.githubusercontent.com/11626700/97797488-7b85d400-1c58-11eb-9413-95adaa1491d0.png)

**Comment by sgalcheung** [comment]
I also encountered this problem, can you help me

**Comment by piresashwin** [comment]
> Don't create a new Identity, but add your claims to existing Identity:
> 
> ```cs
> var identity = currentPrincipalAccessor.Principal?.Identities.FirstOrDefault();
> if (identity != null)
> {
>     identity.AddClaim(...);
> }
> ```
> 
> BTW, in this way you are adding the claim in every request. If that's you want, it's OK. But, we generally want to add a claim to the authentication cookie/ticker while the user is logging in. To do that;
> 
> 1. Create a class inheriting from the `AbpUserClaimsPrincipalFactory` class (say MyUserClaimsPrincipalFactory) and override the CreateAsync method.
> 2. Find the claim value from somewhere (you can inject a service for example) and add the the ClaimsPrincipal. Do it like [how AbpUserClaimsPrincipalFactory is doing it](https://github.com/abpframework/abp/blob/8e20aab617205936c299ed5c3c40e0c529a3f06b/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L25-L38).
> 3. Replace the AbpUserClaimsPrincipalFactory with your class by pre-configuring the IdentityBuilder in the PreConfigureServices of your module:
> 
> ```cs
> public override void PreConfigureServices(ServiceConfigurationContext context)
> {
>     PreConfigure<IdentityBuilder>(builder =>
>     {
>         builder.AddClaimsPrincipalFactory<MyUserClaimsPrincipalFactory>();
>     });
> }
> ```

How to achieve the same result in v4.2.2. I am using microservices. Also added the module to the authserver project. The code is not getting executed on login.

```
public class ResellerUserClaimsPrincipalFactory : AbpUserClaimsPrincipalFactory
    {
        public ResellerUserClaimsPrincipalFactory(
           UserManager<IdentityUser> userManager,
           RoleManager<IdentityRole> roleManager,
           IOptions<IdentityOptions> options, ICurrentPrincipalAccessor currentPrincipalAccessor,
            IAbpClaimsPrincipalFactory abpClaimsPrincipalFactory)
           : base(
                 userManager,
                 roleManager,
                 options, currentPrincipalAccessor, abpClaimsPrincipalFactory)
        {
        }


        [UnitOfWork]
        public async override Task<ClaimsPrincipal> CreateAsync(IdentityUser user)
        {
            var principal = await base.CreateAsync(user);
            var identity = principal.Identities.First();

            if (user.GetResellerId() != Guid.Empty)
            {
                identity.AddIfNotContains(new Claim("ResellerId", user.GetResellerId().ToString()));
            }

            return principal;

        }
    }
```

Added to the preconfigure services of the module.

```
public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PreConfigure<IdentityBuilder>(builder =>
            {
                builder.AddClaimsPrincipalFactory<ResellerUserClaimsPrincipalFactory>();
            });
        }
```

**Comment by lijiaxuanabc** [comment]
I'm following this procedure but I'm doing it

var principal = await base.CreateAsync(user).ConfigureAwait(false);

It reported The error 
System. InvalidOperationException: "The navigation 'IdentityUser. Claims' always be The loaded because The entity is not being tracked. Navigations can only be loaded for tracked entities.”

**Comment by MehtiSini** [comment]
> @thk-liu
> 
> Your code worked for me.
> 
> ![image](https://user-images.githubusercontent.com/6908465/73037704-fe3c6000-3e8a-11ea-9119-7e0666143297.png)

i have the same Problem , can you share the full code that is working for you , i dont understand what is the problem 
this is my code
using System.Linq;
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Options;
using Volo.Abp.Identity;
using Volo.Abp.Security.Claims;
using Volo.Abp.Uow;
using Volo.Abp.DependencyInjection;
using IdentityUser = Volo.Abp.Identity.IdentityUser;
using IdentityRole = Volo.Abp.Identity.IdentityRole;

namespace NozhanPlatform
{
    public class MyUserClaimsPrincipalFactory : UserClaimsPrincipalFactory<IdentityUser, IdentityRole>, IScopedDependency
    {
        public MyUserClaimsPrincipalFactory(
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IOptions<IdentityOptions> options)
            : base(
                  userManager,
                  roleManager,
                  options)
        {
        }

        [UnitOfWork]
        public override async Task<ClaimsPrincipal> CreateAsync(IdentityUser user)
        {
            Console.WriteLine("oooooo!");

            var principal = await base.CreateAsync(user).ConfigureAwait(false);

            if (user.TenantId.HasValue)
            {
                principal.Identities
                    .First()
                    .AddClaim(new Claim(AbpClaimTypes.TenantId, user.TenantId.ToString()));
            }

            return principal;
        }
    }
}
  public override void PreConfigureServices(ServiceConfigurationContext context)
  {

      var hostingEnvironment = context.Services.GetHostingEnvironment();
      var configuration = context.Services.GetConfiguration();


      PreConfigure<IdentityBuilder>(builder =>
      {
          builder.AddClaimsPrincipalFactory<MyUserClaimsPrincipalFactory>();
      });

      PreConfigure<OpenIddictBuilder>(builder =>
      {
          builder.AddValidation(options =>
          {
              options.AddAudiences("NozhanPlatform");
              options.UseLocalServer();
              options.UseAspNetCore();
          });
      });
