### ISSUE TITLE
generate-proxy creating Int64 class in typescript

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#4202]
Hello,

Using the latest ABP CLI: 2.8.0

When using the generate-proxy command a class for Int64 is created where 'long' is used in c#. 

Used as:
`postDeleteByModel(body: Int64): Observable<GroupDto>{}`

The class:
```
import { EntityDto } from '@abp/ng.core';

export class Int64 extends EntityDto {
  id: number;

  constructor(initialValues: Partial<Int64> = {}) {
    super(initialValues);
  }
}
```

Also, where 'long' is used in a generic, there seems to have been no conversion:

`export class GroupDto extends EntityDto<System.Int64>`

Thank you :)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/4051
