### ISSUE TITLE
How to change validation localization?

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#4203]
> Please check the official documentation before asking questions: https://docs.abp.io/en/abp/latest/Localization

I followed the documentation and it didn't work
![image](https://user-images.githubusercontent.com/14011792/83632076-325e2500-a5d1-11ea-9e64-9175816f7935.png)
![image](https://user-images.githubusercontent.com/14011792/83632108-4144d780-a5d1-11ea-86ac-0a2ace741e9d.png)
![image](https://user-images.githubusercontent.com/14011792/83632239-89fc9080-a5d1-11ea-8b2f-ffe10b38ddbc.png)
![image](https://user-images.githubusercontent.com/14011792/83632192-6f2a1c00-a5d1-11ea-966a-8e5fa2e4cc95.png)

_Originally posted by @wingqing1314 in https://github.com/abpframework/abp/issues/4199#issuecomment-638139275_

**Comment by wingqing1314** [comment]
![image](https://user-images.githubusercontent.com/14011792/83635693-39883180-a5d7-11ea-805c-2fdedaffd112.png)
It works after added  `ErrorMessage` .
It has to be ，right？

**Comment by liangshiw** [comment]
What is the value of `CultureInfo.CurrentUICulture`
Make sure your current UI culture is zh-hans.

**Comment by wingqing1314** [comment]
> What is the value of `CultureInfo.CurrentUICulture`
> Make sure your current UI culture is zh-hans.

I just want the response message is in Chinese, not displayed on UI.

**Comment by liangshiw** [comment]
Please check 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1 first.

**Comment by wingqing1314** [comment]
> Please see
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1 learn about localization in ASP.NET Core.

Got it!
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplication<UserHttpApiHostModule>();
            services.AddMvc()
                    .AddDataAnnotationsLocalization(options =>
                    {
                        options.DataAnnotationLocalizerProvider = (type, factory) =>
                            factory.Create(typeof(UserResource));
                    });
        }
```
Add this code will be work without `ErrorMessage`  😀
