### ISSUE TITLE
Feature: Doc Module - Download PDF

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#4204]
### Feature: Doc Module Download PDF

Please add a feature to allow user to download a document, or group of documents to PDF.

**Comment by liangshiw** [comment]
Hi 

I think this is not a necessary feature. you can use the save pdf of chrome:

![image](https://user-images.githubusercontent.com/16813853/83647011-fc2ba000-a5e6-11ea-9c61-69a980f7cfd9.png)

Chrome Store also provides these extensions:
https://chrome.google.com/webstore/detail/pdf-mage/gknphemhpcknkhegndlihchfonpdcben

**Comment by hikalkan** [comment]
duplicate of https://github.com/abpframework/abp/issues/481
