### ISSUE TITLE
Cannot display hangfire's dashboard

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#4214]
I have followed the documentation and the hangfire works. However, I cannot use the hangfire dashboard
Currently ABP does not support right?
![image](https://user-images.githubusercontent.com/10234503/83739719-2d0be380-a680-11ea-97bc-a652b144b263.png)

**Comment by liangshiw** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by hikalkan** [comment]
ABP does nothing with the hangfire dashboard. You may need to add its middleware or somehow configure it. Follow its own document please.
