### ISSUE TITLE
How do I get IServiceProvider from startup or HostModule and resolve an interface?

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#4217]
Hi,

I read the [dependency injection documentation](https://docs.abp.io/en/abp/master/Dependency-Injection#resolve-service-from-iserviceprovider) 

I would like to find out:

1. where in the startup/HostModule can I access the container or IServiceProvider?
2. what is the code that I write to manually resolve, say a repository?

Using version 2.8.0

Thank-you!

**Comment by tinonetic** [comment]
I found the solution. `ISeriveProvider` is a .NET core interface and its available in the `ServiceConfigurationContext` in ABP

I got it as follows
```c#
var serviceProvider = context.Services.BuildServiceProvider();

**Comment by liangshiw** [comment]
Please follow best practices:
https://docs.abp.io/en/abp/master/Module-Development-Basics

**Comment by tinonetic** [comment]
Hi @liangshiw 

Thank you for responding. We had no choice as we could not get it to work for a pressing issue. Will definitely do so when we get the time. This is based on an earlier issue https://github.com/abpframework/abp/issues/4174

**Comment by tinonetic** [comment]
Just to let you know that we managed to do this the right way. I have removed our "hack"
