### ISSUE TITLE
Idea: Access-Control-Layer

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#4229]
Hi,

I was wondering what the abp community thinks about more advanced permission-module, inspired by [joomla's ACL system](https://docs.joomla.org/J3.x:Access_Control_List_Tutorial).

It would be nice to have a modular, enterprise-ready acl in the ABP upstream. We could implement it by ourselves according to our needs but I think it won't be compatible with the upstream since the permissions module must be changed dramatically to support such a scenario.

The main differences are:
- **Hierarchical roles:** The roles are inside a hierarchy, to support the following features.
- **Inherited permissions (roles only):** The permissions can be inherited from parent roles.
- **Access Levels:** A access level groups several roles together and describes wether the users in the groups can access stuff (such as entities)
- **Access Level for entities:** Entities can be provided with a access level. Therefore the permissions can be defined more fine-grained. 

So let's discuss the idea, requirements and the scope of this idea.

**Comment by hikalkan** [comment]
Thank you @NecatiMeral for your suggestion.

Have you seen https://github.com/abpframework/abp/issues/236?

I suppose it is similar to what you want. I will also check the Joomla document deeply (it is a bit long)

**Comment by NecatiMeral** [comment]
hi @hikalkan,

yeah, that's basically the core of my idea.
My suggestion mainly focuses on the area around the evaluation as described in the MS docs page and gives a idea, how to manage and handle some use cases (access-levels, hierarchical authorizations [blogs > blog posts].

**Comment by NecatiMeral** [comment]
I don't think this should get tagged as inactive. 😅
