### ISSUE TITLE
ABP CLI update command may need a retry mechanism

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4235]
Today I try to upgrade my app from ABP 2.8.0 to 2.9.0.

In the end, it told me that the update is successful, but when I global searched the keyword "2.8.0", I saw there were still several 2.8.0 projects. I found console outputs showed network errors during these projects updating.

In my submission, when a network error occurs, it should be retried or even stop and throw the error.

**Comment by liangshiw** [comment]
> I found console outputs showed network errors during these projects updating.

You have seen the error, you can try again manually.

**Comment by gdlcf88** [comment]
The full output is very long, I started the update command, then I went to make coffee because it will take some time. When I came back, the last screen tell did not show any error, so I mistakenly thought everything was going well.

**Comment by gdlcf88** [comment]
I am closing this issue since today's ABP CLI has been pretty nice.
