### ISSUE TITLE
Idea of passing twice the same parameter(same injection) to constructor in IdentityUserManager class?

### ISSUE THREAD

**Issue by talhazengin** [abpframework/abp#4237]
In below class, `IIdentityUserRepository `interface injection repeated.
`modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserManager.cs`

**Comment by liangshiw** [comment]
We should keep only one

**Comment by hikalkan** [comment]
Human mistake :) Thank you for finding this.
