### ISSUE TITLE
Azure AD - redirect to microsoft login page on startup

### ISSUE THREAD

**Issue by Znow** [abpframework/abp#4239]
Heya, I have searched and haven't yet found a way to redirect to the standard login page that Microsoft provides, when you want to login with your Azure AD account for example.

"AccessDeniedPath" requires a path within the application, not a remote URL.

Any advice?

Thanks

**Comment by liangshiw** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.cookieauthenticationoptions.accessdeniedpath?view=aspnetcore-1.1

`The AccessDeniedPath property informs the middleware that it should change an outgoing 403 Forbidden status code into a 302 redirection onto the given path.`

You can refer azure AD integrated [documentation](https://docs.abp.io/en/abp/master/How-To/Azure-Active-Directory-Authentication-MVC)

**Comment by Znow** [comment]
@liangshiw the "AccessDeniedPath" requires a path that starts with a "/", which a remote URL doesn't not start with.

**Comment by liangshiw** [comment]
AccessDeniedPath can provide a redirect path to the user agent when the user doesn't approve the requested authorization demand.

It should redirect to a local url, this is by design and I think it has nothing to do with ABP. If you need to redirect again, you can redirect on your own page.
