### ISSUE TITLE
Using SettingManager for tenants 

### ISSUE THREAD

**Issue by nacho-gonzalez** [abpframework/abp#4243]
Hi, first of all contratulations, It's a great framework!

I am trying to set and read some settings for a new module following the documentation: https://docs.abp.io/en/abp/latest/Modules/Setting-Management#isettingmanager
`await _settingManager.SetForTenantAsync(tenant1Id, "App.UI.LayoutType", "LeftMenu");`

I cannot see `SetForTenantAsync` method but it seems I can use `ChangeSettingForTenantAsync`.
When I try to set "MySetting" for an specific tenant I cannot do it because `ChangeSettingForTenantAsync` expects the parameter tenantId as `int` instead of `Guid`:
![image](https://user-images.githubusercontent.com/43535988/83946560-ee0d9780-a811-11ea-9059-f4c087160f0d.png)

Therefore, if I am not mistaken, there are two issues:
1. I`ChangeSettingForTenantAsync` should receive a `Guid` tenantId.
2. Documentation is obsolete.

**Comment by liangshiw** [comment]
Are you talking about aspnetboilerplate? abp framework has no `ChangeSettingForTenantAsync` `method

**Comment by nacho-gonzalez** [comment]
Hi liangshiw, It was my mistake. 
I was referencing `Abp.Configuration` instead of `Volo.Abp.SettingManagement`. Now I can see the correct methods and documentation is also OK.
Sorry for the inconveniences.
