### ISSUE TITLE
Virtual File System: Some chars in file name are replaced unexpectedly.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#4248]
For example, I have a file with the name `{{ Person.Name }}.txt` (The file name is weird because I'm intended to use scriban to render it to the real file name.)
I add the file to the VFS, however, when I check the file name(through the `GetVirtualOrPhysicalPathOrNull` extension method), it becomes something like `__Person/Name__.txt`, noticed that the `{` and `}` become `_`, and the `.` between "Person" and "Name" becomes `/`.
Of couse then scriban cann't render it correctly.

I examine the source and find this may be the reason:
https://github.com/abpframework/abp/blob/0d791ff4bf24a72bdd661b4c6f409845a8d22e6a/framework/src/Volo.Abp.VirtualFileSystem/Volo/Abp/VirtualFileSystem/VirtualFilePathHelper.cs#L40

But I have no clue why it is doing it.

**Comment by wakuflair** [comment]
Oh, I found there's a related issue: https://github.com/abpframework/abp/issues/128.
It seems that it's nothing to do with ASP.NET Core now, but only wait for the ABP team to fix it.

**Comment by yshulin** [comment]
[https://github.com/aspnet/FileSystem/issues/184#issuecomment-352907578](url)
It seems that this bug was fixed by ASP.NET Core, but ABP team have not fixed it.
waiting...

**Comment by hikalkan** [comment]
I will try to work on this in 3.0 milestone.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/4528
