### ISSUE TITLE
Remove NGXS Whereever Not Required

### ISSUE THREAD

**Issue by armanozak** [abpframework/abp#4254]

**Comment by sarshogh** [comment]
Hi @armanozak  and @mehmet-erim @hikalkan 

Is there any reason  Ngxs has been removed from ABP template V.3.4 ? 
We are keen to keep our project based on Abp angular template but getting latest version looks threre is no Ngix state and actions folders ? right ? 
we used abp cli to generate those proxy, can still use them ? 
can you please provide us any document how to keep them or how to migrate it to new version ?

**Comment by armanozak** [comment]
Hi,

Gradually, we are planning to remove dependency to NGXS in all our core features and make them available for use with, including but not limited to NGXS, NgRx, Akita, or no state management at all.

The store is still generated and placed at the same directory as before. The component templates do not use them, because there is no need to, but using actions and selectors is still possible.

We will add this to the documentation soon.
