### ISSUE TITLE
Clock documentation

### ISSUE THREAD

**Issue by javierhuerta** [abpframework/abp#4255]
Hello, I need guidance regarding how to use the timezone functionality added in the latest version of abp framework (2.9). The documentation regarding the 'clock' is empty. I'd appreciate your help.

**Comment by liangshiw** [comment]
Hi,
The documentation is not complete. You can learn how to use it by reading the [source code](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Timing/Volo/Abp/Timing)

**Comment by maliming** [comment]
We will improve the documentation in v3.0.

**Comment by javierhuerta** [comment]
Thank you

**Comment by hikalkan** [comment]
see https://docs.abp.io/en/abp/latest/Timing
