### ISSUE TITLE
2.9 Upgrade - Links for Modules (Account, Tenant Management, etc)

### ISSUE THREAD

**Issue by collomd** [abpframework/abp#4257]
After upgrading from 2.8 to 2.9, the UI links to all the built-in modules now have a tilde character in front of them so I get a 404.  I made a backup of my 2.8 and can confirm that they still work fine 2.8. 
So previous where I would get "/TenantManagement/Tenants", I get "~/TenantManagement/Tenants"...

Is there some sort of relative path setting that needs to be modified ? I do have a modified basic theme application.cshtml, but it did work fine in all the previous versions.

Thanks,

**Comment by liangshiw** [comment]
Do you installed a third-party theme?

Can you provide a project reproduce this problem?

**Comment by collomd** [comment]
I tracked it down to a change I had made in the Menu cshtml, sorry !

**Comment by liangshiw** [comment]
Is the problem solved?

**Comment by collomd** [comment]
Yeah, I have it sorted...thanks!
