### ISSUE TITLE
Separate Identity Server: Performance Issue

### ISSUE THREAD

**Issue by a-patel** [abpframework/abp#4267]
Separate Identity Server: Performance Issue:
- Project type: Application
- UI Framework: Angular
- Database provider: EF Core
- Separate Identity Server: Enabled

Using the above options, I have created a sample application. I haven't made any changes, But I am not able to log in.

**Comment by a-patel** [comment]
https://localhost:44312/api/abp/application-configuration
https://localhost:44312/.well-known/openid-configuration

Above API calls take more than 5-10 minutes every time during development.

**Comment by liangshiw** [comment]
Did you start the redis server? Please provide logs Thanks.

**Comment by a-patel** [comment]
@liangshiw 
Can we make Redis optional?

**Comment by maliming** [comment]
The applications use Redis as as distributed cache. So, you need to have Redis installed & running.

**Comment by a-patel** [comment]
I have changed the Redis connection string and made sure that it is running.
Now I am able to get responses and able to log in. But still, it is taking more than 10s -1 minute for some API call.

https://localhost:44373/.well-known/openid-configuration/jwks
https://localhost:44373/connect/token
https://localhost:44312/api/abp/application-configuration

![ABP-IDV-Issue - After-Redis](https://user-images.githubusercontent.com/8511777/84127377-d6761f00-aa5c-11ea-893e-f73344df1826.PNG)

**Comment by maliming** [comment]
Please check the application log.

**Comment by a-patel** [comment]
Logs (Identity Server):

2020-06-09 14:14:44.824 +05:30 [INF] Request finished in 13143.7343ms 200 application/json; charset=UTF-8
2020-06-09 14:14:45.023 +05:30 [INF] Request starting HTTP/1.1 GET https://localhost:44373/.well-known/openid-configuration/jwks  
2020-06-09 14:14:45.028 +05:30 [DBG] Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
2020-06-09 14:14:58.524 +05:30 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryKeyEndpoint
2020-06-09 14:14:58.524 +05:30 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
2020-06-09 14:14:58.524 +05:30 [DBG] Start key discovery request
2020-06-09 14:14:58.526 +05:30 [INF] Request finished in 13503.4084ms 200 application/jwk-set+json; charset=UTF-8

[logs.txt](https://github.com/abpframework/abp/files/4751022/logs.txt)

**Comment by maliming** [comment]
Please follow the logs to solve your problem.

```
 [WRN] It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 6s ago, v: 2.0.593.37019
```

**Comment by a-patel** [comment]
That was old logs before local Redis.
Then I have changes the Redis (Azure Redis) server endpoint.
Above mentioned logs are after that change.

**Comment by a-patel** [comment]
please re-open this issue.

**Comment by a-patel** [comment]
I am doing the above things again. (Fresh start - with working Redis and deleting old logs)
Still taking too much time.

![ABP with IDV - Login - API Calls](https://user-images.githubusercontent.com/8511777/84133564-edb90a80-aa64-11ea-9679-6ae9498a85e9.PNG)

**Comment by a-patel** [comment]
Logs:

2020-06-09 15:17:31.516 +05:30 [INF] Request finished in 13397.3514ms 200 application/json; charset=UTF-8
2020-06-09 15:17:31.581 +05:30 [INF] Request starting HTTP/1.1 GET https://localhost:44373/.well-known/openid-configuration/jwks  
2020-06-09 15:17:31.584 +05:30 [DBG] Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
2020-06-09 15:17:44.881 +05:30 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryKeyEndpoint
2020-06-09 15:17:44.881 +05:30 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
2020-06-09 15:17:44.881 +05:30 [DBG] Start key discovery request
2020-06-09 15:17:44.885 +05:30 [INF] Request finished in 13303.8247ms 200 application/jwk-set+json; charset=UTF-8



[logs.txt](https://github.com/abpframework/abp/files/4751343/logs.txt)

**Comment by maliming** [comment]
hi @a-patel Can you check the logs of the identity server project? 

**All the information is in the log.**

**Comment by a-patel** [comment]
I already have checked that, also attached whole log file in my previous comment.

**Comment by a-patel** [comment]
If I am trying without Identity Server option while creating the project then it is working fine,

**Comment by maliming** [comment]
hi @a-patel 

I can't reproduce your problem. The response of the Identity server is fast in my computer. Can you try another computer?

**Comment by a-patel** [comment]
@maliming 
I have tried on other machine, other browsers, private browser, etc.
It takes around 1-2 minutes to complete the above API call.

**Comment by maliming** [comment]
hi

Please try to remove the redis related code. 
Then the memory cache will be used.

**Comment by leonkosak** [comment]
@a-patel so if Redis is NOT used, the Separated Identity Server "version" of abp still works as expected?

**Comment by a-patel** [comment]
Yes, If Redis is not used (after removing above code), it is working as expected.
What if I want to use Redis?

**Comment by leonkosak** [comment]
I tried with Redis for windows(https://www.onlinetutorialspoint.com/spring-boot/setup-install-redis-server-on-windows-10.html), but I always get this error (Postgres db):

![image](https://user-images.githubusercontent.com/39346964/84405893-0f52f700-ac09-11ea-8f99-4033e68cea6b.png)

**Comment by leonkosak** [comment]
Crap, this is cookie-related issue. :( I tried in other browser and it works.

**Comment by a-patel** [comment]
I am using SQL Server database, I have tried in different machines.

**Comment by leonkosak** [comment]
@a-patel, my timings with fresh abp v2.9.0 and Redis (https://www.onlinetutorialspoint.com/spring-boot/setup-install-redis-server-on-windows-10.html):

![image](https://user-images.githubusercontent.com/39346964/84466603-06e6d480-ac7a-11ea-9dd9-55c636315b51.png)

@maliming, do you get comparable timings (in development environment)?

**Comment by maliming** [comment]
hi @a-patel @leonkosak 

I think we have confirmed that this problem is related to the performance of redis, not to abp.


I am using docker's redis in wsl (ubuntu).

![image](https://user-images.githubusercontent.com/6908465/84467206-fbad9c00-acad-11ea-8230-36656450433a.png)

**Comment by leonkosak** [comment]
I agree. But in my case (my computer), the timings are acceptable (and much lower than what @a-patel environment).

**Comment by xyfy** [comment]
the redis on windows version is very old,  I came this sence before ,when I use the new redis server in linux,it may reduce much time

**Comment by xyfy** [comment]
it 

> the redis on windows version is very old, I came this sence before ,when I use the new redis server in linux,it may reduce much time

That is when I used the `old abp` named  (aspnetboilerplate)[https://github.com/aspnetboilerplate/aspnetboilerplate]
