### ISSUE TITLE
About FluentValidation in abp

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#4277]
How to use FluentValidation without inheriting CrudAppService.

My Validator is not run when my appservice without  inheriting CrudAppService.

![image](https://user-images.githubusercontent.com/14011792/84143403-1bb04600-aa89-11ea-8671-b131f1d4b1ac.png)

**Comment by liangshiw** [comment]
I will check it out

**Comment by liangshiw** [comment]
Make sure your application service method is virtual.

**Comment by wingqing1314** [comment]
> Make sure your application service method is virtual.

Yes! Thank you very much 😉

**Comment by Muhammed-Aslan** [comment]
> Make sure your application service method is virtual.

Please add this information to the documentation
