### ISSUE TITLE
Introduce read-only app service

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#4282]
I am wondering if it might be nice to introduce a `IReadOnlyAppService` which is similar to `CrudAppService` but excludes:
* CreateAsync
* UpdateAsync
* DeleteAsync

The reason is that sometimes there are cases where we may only want to read via the API, but the updating happens somewhere else like another service.

In my case I have a 'Policy' which has sub-types like 'SimplePolicy' and 'ScheduledPolicy' which have their own 'update' and 'create' functionality, but share common set of 'Policy' properties and I want to be able to 'get' their high level properties.
Right now I will have to re-implement all the features from the `CrudAppService` and exclude these 3 endpoints, because the class is templated and I don't have the CRUD Dto's on the base class.

**Comment by hikalkan** [comment]
I agree with @NecatiMeral 
I added to backlog. Any PR would be appreciated.

**Comment by trgiangvp3** [comment]
Which package should I install to use `ReadOnlyAppService`?
I updated from abp v2.8.0 to the latest v2.9.0 using CLI command abp update from the folder containing .sln file.
But when I extend `ReadOnlyAppService` to create my own Service, VS reports that The type or namespace `ReadOnlyAppService` could not be found.

**Comment by NecatiMeral** [comment]
I'll be released in 3.0.0 (which will be release very soon).

**Comment by trgiangvp3** [comment]
> I'll be released in 3.0.0 (which will be release very soon).

Yeah. This `ReadOnlyAppService` is exactly what I've thinked of before. Will wait for it.
Thank you guys very much for making an excellent framework.

**Comment by NecatiMeral** [comment]
Kudos should go to @hikalkan and volosoft ;-)

**Comment by appsupport-gc** [comment]
Would a Blazor AbpReadOnlyPageBase make sense?
