### ISSUE TITLE
DependencyResolutionException

### ISSUE THREAD

**Issue by zaktecs** [abpframework/abp#4285]
Hi,
I was wondering if someone can help me with following as I keep getting errors when I use the following dependency injection

in my startup:
       `services.AddScoped<IFeesTypeAppService, FeesTypeAppService>();`

in Edit.chtml.cs
```csharp
        private readonly IFeesTypeAppService _feesTypeAppService;
        public Edit(IFeesTypeAppService feesTypeAppService)
        {
           
            _feesTypeAppService = feesTypeAppService;
        }
```
Many thanks
Zak
===========================
ERROR
DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'OptimalCore.StudentManager.FeesTypeAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[OptimalCore.StudentManager.FeesType,System.Guid] repository' of constructor 'Void .ctor(Volo.Abp.Domain.Repositories.IRepository`2[OptimalCore.StudentManager.FeesType,System.Guid])'.
Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable<Parameter> parameters)

**Comment by maliming** [comment]
```
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository2[OptimalCore.StudentManager.FeesType,System.Guid]
```

Possible reason:
If you want to create repositories for other entities too, then set **includeAllEntities** to true:
```
services.AddAbpDbContext<MyDbContext>(options =>
{
    options.AddDefaultRepositories(includeAllEntities: true);
});
```

**Comment by zaktecs** [comment]
Hi,
Thanks very much for your help. 
This is already set to true in my EntityFrameworkCoreModule
services.AddAbpDbContext<MyDbContext>(options =>
{
    options.AddDefaultRepositories(includeAllEntities: true);
});

Kind Regards,
Zak

**Comment by maliming** [comment]
hi

* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.
