### ISSUE TITLE
Maybe I want to know that how to set Current User

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#4287]
See https://docs.abp.io/en/abp/latest/Entities#base-classes-interfaces-for-audit-properties

_Originally posted by @liangshiw in https://github.com/abpframework/abp/issues/4286#issuecomment-641677741_

Thanks liang, but the doc won't solve my problem.

**Comment by liangshiw** [comment]
**Please read the document first** : https://docs.abp.io/en/abp/latest/CurrentUser

**Comment by wingqing1314** [comment]
> **Please read the document first** : https://docs.abp.io/en/abp/latest/CurrentUser

wow ，hot and fresh！

**Comment by wingqing1314** [comment]
> **Please read the document first** : https://docs.abp.io/en/abp/latest/CurrentUser

Sorry , I still don't understand that how/where to set Current User 's properties.

**Comment by wingqing1314** [comment]
Solved！

Add the code in `OnApplicationInitialization` method of `HostModule`
```
app.Use(async (ctx, next) =>
            {
                var currentPrincipalAccessor = ctx.RequestServices.GetRequiredService<ICurrentPrincipalAccessor>();
                var map = new Dictionary<string, string>()
                {
                    { "userId", AbpClaimTypes.UserId },
                    { "role", AbpClaimTypes.Role },
                    { "userNo", AbpClaimTypes.UserName },
                    //any other map
                };
                var mapClaims = currentPrincipalAccessor.Principal.Claims.Where(p => map.Keys.Contains(p.Type)).ToList();
                currentPrincipalAccessor.Principal.AddIdentity(new ClaimsIdentity(mapClaims.Select(p => new Claim(map[p.Type], p.Value, p.ValueType, p.Issuer))));
                await next();
            });
```
