### ISSUE TITLE
Is ABP Framework 4.x ultimately this project?

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#430]
Hi @hikalkan.

You mentioned in the existing ABP that things will be considered in 4.x. Did you mean that will be the next version of ABP with what is currently implemented or is 4.x ultimately ABP Framework 1.x?

**Comment by hikalkan** [comment]
ASP.NET Boilerplate v4.x is not this (ABP vNext) project. 4.x is a regular major version of current framework (https://github.com/aspnetboilerplate/aspnetboilerplate)
