### ISSUE TITLE
Auto api

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#4310]
![image](https://user-images.githubusercontent.com/14011792/84337510-4ce55f00-abcc-11ea-8c49-2c9277e6b466.png)
According to the document
>If the method has an 'id' parameter then it adds '/{id}' ro the route.

I wonder if I can change it to "code" then it adds '/{code}'.

**Comment by xyfy** [comment]
yes,you can, just do it

**Comment by xyfy** [comment]
change all `id` to `code`

**Comment by gdlcf88** [comment]
If you want to keep the Auto API Controller feature working and customize an API's route, the simple way is you can try to add `[Route("your custom route")]` attribute to the method of the application service class.

If you want to follow the best practice:
1. Add `[RemoteService(false)]` attribute to the method of the application service class.
2. Create a controller manually. See the [demo](https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.HttpApi/Volo/Blogging/BlogsController.cs).

**Comment by gdlcf88** [comment]
Another way for you :)

```
private void ConfigureConventionalControllers()
{
    Configure<AbpAspNetCoreMvcOptions>(options =>
    {
        options.ConventionalControllers.Create(typeof(MyProjectApplicationModule).Assembly, opt =>
        {
            opt.UrlActionNameNormalizer = context =>
            {
                if (context.ControllerName == "AdminUser" && context.Action.ActionMethod.Name == "GetAdminUserAndStationAsync")
                {
                    return "{code}/adminUserAndStationAsync";
                }
                return null;
            };
        });
    }
}
```
