### ISSUE TITLE
Which ABP package has .IgnoreAuditedObjectProperties()?

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#4313]
Using ABP v2.8.0

I am following the documentation on mapping objects: https://docs.abp.io/en/abp/master/Object-To-Object-Mapping#ignoring-audit-properties

Which package has the extension method: ` .IgnoreAuditedObjectProperties();`

I installed `Volo.Abp.AutoMapper` but it doesn't seem to have it

Thanks!

**Comment by gdlcf88** [comment]
It is a new feature of ABP version 2.9.0. See https://github.com/abpframework/abp/issues/4163

**Comment by tinonetic** [comment]
Thanks @gdlcf88 I noticed that you can no longer select the version for the documentation you are reading. It is only 1.0.0 (latest) see screenshot.
![2020-06-11 13_15_02-Object To Object Mapping _ ABP Documentation](https://user-images.githubusercontent.com/8109147/84379470-26ccb880-abe6-11ea-8f3f-04effec0fa27.png)
