### ISSUE TITLE
Set AbpSequentialGuidGeneratorOptions.DefaultSequentialGuidType by the database provider packages

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4323]
`AbpSequentialGuidGeneratorOptions.DefaultSequentialGuidType` is used to set how sequential GUIDs are generated. Its default value is `SequentialAtEnd` which is proper for SQL Server.

However, if you are using a different DB provider, you probably want to change this. For example, `SequentialAsBinary` is proper for Oracle.

Since we have already DB provider packages like Volo.Abp.EntityFrameworkCore.PostgreSql, they can set this option if it was not set by the application code.

To make this possible, we also make `AbpSequentialGuidGeneratorOptions.DefaultSequentialGuidType` nullable, so providers only set if it is null.

**Comment by gdlcf88** [comment]
This really makes it easier for beginners to get started!
