### ISSUE TITLE
https://generator.swagger.io/ not working abp generated API

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#4329]
error

Error: Bad RequestResponse bodyDownload{   "code": 1,   "type": "error",   "message": "The swagger specification supplied was not valid" }
--

**Comment by liangshiw** [comment]
Can you explain in detail?

**Comment by dicksonkimeu** [comment]
I want to generate client code for my api done in abp.

I want to use https://generator.swagger.io/ website to do that.

![image](https://user-images.githubusercontent.com/4476822/84521862-53fc9200-acde-11ea-8db0-ff9fa77d935f.png)

**Comment by liangshiw** [comment]
Will you have this problem if you directly use the aspnet core application to generate swagger?

**Comment by dicksonkimeu** [comment]
No

**Comment by liangshiw** [comment]
This has nothing to do with ABP,I also encountered the problem using ASP.NET Core WebAPI application.
See https://github.com/swagger-api/swagger-codegen/issues/6598
