### ISSUE TITLE
Revise design for search/filter & nav on the docs module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4332]
- [ ] Search & filter is confusing. We may move search to another place
- [ ] I can not understand that the nav menu has more items unless I move the mouse over to see the scroll.

![image](https://user-images.githubusercontent.com/1210527/84539111-836dc780-acfb-11ea-9cf8-0b120d3cb951.png)

**Comment by armgnunlu** [comment]
![docs-old](https://user-images.githubusercontent.com/36102404/85132305-2c0eb080-b241-11ea-8e04-bb83804ac5eb.png)
![docs-new](https://user-images.githubusercontent.com/36102404/85132309-2d3fdd80-b241-11ea-9bd1-937df164a1aa.png)

**Comment by armgnunlu** [comment]
![image](https://user-images.githubusercontent.com/36102404/85132399-611b0300-b241-11ea-810a-5170fd146695.png)
