### ISSUE TITLE
Razor Pages Tutorial has a typo/error

### ISSUE THREAD

**Issue by cesardv** [abpframework/abp#4333]
In the Acme.BookStore application tutorial using Razor Pages (and EFCore) in the [Create the Books page](https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=MVC#create-the-books-page) section, there's the following bullet point:

- Set the `IndexModel`'s namespace to `Acme.BookStore.Pages.Books` in `Index.cshtml.cs`

**However, the example code below for Index.cshtml.cs** does not reflect that.

Correct me if I'm wrong, but the intent behind changing the namespace of Index.cshtml.cs is done in order to have the Index.cshtml.cs's `IndexModel` be in the same namespace as the `BookStorePageModel` (i.e in `Acme.BookStore.Web.Pages`) or am I misunderstanding that?

Further, I think following the tutorial to the letter right as it is seems to cause a compile error: 
`Error CS0115	'Pages_Books_Index.ExecuteAsync()': no suitable method found to override.` Or is it just me?

**Comment by liangshiw** [comment]
Thanks for your feedback, the documentation needs to be updated

**Comment by liangshiw** [comment]
Documentation has been updated: https://github.com/abpframework/abp/commit/ed46f92c10190a72151d430f628bfd7373836479#diff-6136c7c24aa5ee8a82fd19cfe6455365

**Comment by cesardv** [comment]
Sweet! Thanks guys!
