### ISSUE TITLE
Should a lookup type be an AggregateRoot or an Entity? How do you decide one vs the other?

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#4334]
Hi,

I am on ABP 2.8.0

I have a question about `AggregateRoot` and `Entity`:

I read the docs:

1. https://docs.abp.io/en/abp/master/Entities
2. https://docs.abp.io/en/abp/master/Best-Practices/Repositories
3. https://docs.abp.io/en/abp/master/Entity-Framework-Core

I am working on a new project that has an `AggregateRoot` which has been implemented well and working.

As I expand the requirements, I have a new lookup type that will be associated with the `AggregateRoot`. Should this lookup type be a sub-Entity of the `AggregateRoot`? If not, do I relate the two in a standard EF Core navigation properties?

**Example** 
A Book has a Genre
Suppose it is a library with a warehouse receives books, saves details of the books in the system
At another stage, when the books arrive at the library the books are classified into their respective Genres in the same system

So if  `Book : AggregateRoot<Guid>`, should one have a `Genre: Entity` and make it a sub-entity of `Book : AggregateRoot<Guid>`?

Do I make them both `AggregateRoot`? Can an `AggregateRoot` exist in another? That doesn't sound right to me when I think about it, because it contradicts the concept of being the root class that aggregates others.... or am I wrong?

What makes you decide to use `AggregateRoot` vs `Entity`?

**Comment by liangshiw** [comment]
Implementing DDD is usually based on your business.
Here is something about DDD: https://github.com/hikalkan/presentations/tree/master/2019-XX-XX%20Implementing%20DDD

**Comment by tinonetic** [comment]
Thank-you for answering, but you really didn't help much

I will figure it out

**Comment by tinonetic** [comment]
For the benefit of anyone who's also interested, I found the answer by looking at the relationship between ABP's `Post` and `Blog` ( `public class **Post** : FullAuditedAggregateRoot<Guid>` and `public class **Blog** : FullAuditedAggregateRoot<Guid>`)

Both are of type `AggregateRoot`

No naviagation property defined

**_Simplified_** versions are:

**Post**
```c#
public class Post : FullAuditedAggregateRoot<Guid>
{
        public virtual Guid BlogId { get; protected set; }

        [NotNull]
        public virtual string Url { get; protected set; }

        [NotNull]
        public virtual string CoverImage { get; set; }

        [NotNull]
        public virtual string Title { get; protected set; }

        [CanBeNull]
        public virtual string Content { get; set; }

        protected Post()
        {
        }

        public Post(Guid id, Guid blogId, [NotNull] string title, [NotNull] string coverImage, [NotNull] string url)
        {
            Id = id;
            BlogId = blogId;
            Title = Check.NotNullOrWhiteSpace(title, nameof(title));
            Url = Check.NotNullOrWhiteSpace(url, nameof(url));
            CoverImage = Check.NotNullOrWhiteSpace(coverImage, nameof(coverImage));

        }
}
```

**Blog**
```c#
public class Blog : FullAuditedAggregateRoot<Guid>
{
        [NotNull]
        public virtual string Name { get; protected set; }

        [NotNull]
        public virtual string ShortName { get; protected set; }

        [CanBeNull]
        public virtual string Description { get; set; }

        protected Blog()
        {
            
        }
}
```

**EF Core Fluent Mappings:**

```c#
builder.Entity<Post>(b =>
            {
                b.ToTable(options.TablePrefix + "Posts", options.Schema);

                b.ConfigureByConvention();

                b.Property(x => x.BlogId).HasColumnName(nameof(Post.BlogId)); //### Blog foreign key
               //...other mappings

                b.HasOne<Blog>().WithMany().IsRequired().HasForeignKey(p => p.BlogId); //### The relationship
            });
```
