### ISSUE TITLE
FeatureManagement.FeatureDto.IStringValueType  Cause Newtonsoft.Json.JsonSerializationException 

### ISSUE THREAD

**Issue by fenggaoyao** [abpframework/abp#4337]
` public interface IFeatureAppService : IApplicationService
    {
        Task<FeatureListDto> GetAsync([NotNull] string providerName, [NotNull] string providerKey); 
    }`
 the GetAsync method  Return  FeatureListDto that contains IStringValueType. 
In a monolithic application,It work well. But In microservices，IFeatureAppService  as IRemoteService, and the returned Json format result,The Client cannot be serialized,it cause Newtonsoft.Json.JsonSerializationException: Could not create an instance of type Volo.Abp.Validation.StringValues.IStringValueType. Type is an interface or abstract class and cannot be instantiated.

How to deal with it？

**Comment by hikalkan** [comment]
Yes, that can be a problem we need to work on.

**Comment by hikalkan** [comment]
@maliming this problem really happens and I think there are two possible solutions:

1. Completely change the DTOs and eleminate inheritance. This would be a breaking change.
2. Write a custom JSON converter to manually deserialize the objects.

I prefer the 2nd option. If we write a custom deserializer, we can convert the following JSON:

````json
{
  "features": [
    {
      "name": "MyProjectName.Feature1",
      "displayName": "MyProjectName.Feature1",
      "value": "B",
      "description": null,
      "valueType": {
        "itemSource": {
          "items": [
            {
              "value": "A",
              "displayText": {
                "resourceName": "MyProjectName",
                "name": "AKey"
              }
            },
            {
              "value": "B",
              "displayText": {
                "resourceName": "MyProjectName",
                "name": "BKey"
              }
            }
          ]
        },
        "name": "SelectionStringValueType",
        "properties": {},
        "validator": {
          "name": "NULL",
          "properties": {}
        }
      },
      "depth": 0,
      "parentName": null
    }
  ]
}
````

`"name": "SelectionStringValueType"` helps us to find the correct value type class.
`"validator"."name": "NULL"` helps us to find the correct validator class.

Can you please work on that? If you have any question, please write to me.
