### ISSUE TITLE
Setting schema for OrganizationUnits tables

### ISSUE THREAD

**Issue by kbowma** [abpframework/abp#4341]
I am trying to set the schema for the Organization Unit feature that was added in 2.9.0. It seems there is no ...DbProperties.DbSchema property to set that is specifically for AbpOrganizationUnits, AbpOrganizationUnitRoles, and AbpUserOrganizationUnit. looks like they may be included in AbpIdentityDbProperties.DbSchema? Is there a way to set the schema for the three tables I mention above independently of other DbProperties.DbSchema?

**Comment by liangshiw** [comment]
There is currently no such method.

**Comment by hikalkan** [comment]
A module is considered a unit and should be configured together. OU is a part of the Identity module.
