### ISSUE TITLE
How to add a domain event that executes after the UnitOfWork is completed?

### ISSUE THREAD

**Issue by thinkershare** [abpframework/abp#4347]
Meeting publish a domain event when  modify `Type `property to `Canceled` and has been persisted to the database successfully, but now, the domain event is always triggered before the UnitOfWork is completed. I read the source code, but I still found nothing.

```CSharp
public class Meeting : AggregateRoot<Guid>{
    public Meeting(Guid id, Guid applicantId) : base(id) {
        ApplicantId = applicantId;
        Phase = MeetingPhase.Draft;
        Type = MeetingType.Default;
        TimeAndPlaces = new Collection<TimeAndPlace>();
        InsideAttendees = new Collection<InsideAttendee>();
        MeetingFiles = new Collection<MeetingFile>();
    }

    /// <summary>
    /// 取消会议
    /// </summary>
    public void Cancel() {
        Phase = MeetingPhase.Draft;
        Type = MeetingType.Canceled;
        var cancelData = new MeetingCancelData(this);
        AddLocalEvent(cancelData);
    }
}
```

**Comment by liangshiw** [comment]
It is triggered after SaveChangesAsync

https://github.com/abpframework/abp/blob/95d2eb200d704768f67764dd3c1b02258e9e6f6f/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L163

**Comment by liangshiw** [comment]
z`
