### ISSUE TITLE
How can get the current login user organization

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#4350]
How can i get the current login user organization. I did not find an organizational acquisition method from the interface ICurrentUser. Are there any other places?

**Comment by liangshiw** [comment]
You can custom `UserClaimsPrincipalFactory` to add current user's organization to the claims when login. like this: 
https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs

Then you can use `FindClaimValue` extension method to get current user's organization

**Comment by hikalkan** [comment]
Or use [IdentityUserManager.GetOrganizationUnitsAsync](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserManager.cs#L190) method to query it (cache it if you need performance).
