### ISSUE TITLE
[Question] Why can't login after the multi-tenant changes the connection string?

### ISSUE THREAD

**Issue by liquehuo** [abpframework/abp#4352]
v2.9.0 Angular UI .
Why can't login after the multi-tenant changes the connection string?

1. Added a tenant
![image](https://user-images.githubusercontent.com/40256444/84632544-a5489380-af21-11ea-8213-8f3818441a6c.png)

2. Modified the connection string ; database is WMS1
![image](https://user-images.githubusercontent.com/40256444/84632561-a974b100-af21-11ea-8939-9fb2f96267de.png)

3. Admin login error ：Invalid username or password 
![image](https://user-images.githubusercontent.com/40256444/84632750-f2c50080-af21-11ea-939f-b6ef3ad1f296.png)

Default  connection string ; database is WMS
![image](https://user-images.githubusercontent.com/40256444/84633134-85659f80-af22-11ea-8f15-e470ec870e68.png)

But if I change the connection string back to WMS as default  connection string, I can login!

**Comment by liquehuo** [comment]
If I register a new account under the tenant WMS1, I can also log in normally. 
The database was generated by .DbMigrator project.
What is the problem?

**Comment by liangshiw** [comment]
When you add tenant's connection string, you need run `.DbMigrator` application to create database.

**Comment by liquehuo** [comment]
> When you add tenant's connection string, you need run `.DbMigrator` application to create tenant database.
I have run the .DbMigrator application, you see I have two database,  WMS and WMS1 
If no database is generated, the error is that an error has occurred！
![image](https://user-images.githubusercontent.com/40256444/84640673-93202280-af2c-11ea-8e35-056e3fe1d24f.png)

**Comment by liangshiw** [comment]
I can't reproduce your problem,

**Comment by liquehuo** [comment]
> You should use `1q2w3E*` as the password. because `.DbMigrator` application use seed data.

I promise i used **1q2w3E*** as the password , But Invalid username or password .
The generated database tenantid is Null ,Is this the problem?

**Comment by liquehuo** [comment]
Oh，thanks!
I know the reason that is I need to change the tenantId in the new database!!
