### ISSUE TITLE
abp cli could quickly add an Host project through a command ?

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#4358]
hi,
Is it posible that abp cli could add a command that it could add an HttpApi.Host project ?

For example
i create a project call  'AbcCollege' through cmd  :
`abp new AbcColleage -t app -u angular`

Step1  
deploy it for  Economics department(MSSQL)  using HttpApi.Host  project.   

Step2
i need manual clone all codes of HttpApi.Host projects, and rename all namespace(call HttpApi.HostMedicine)
2.deploy for Medicine department.(MongoDB)  using HttpApi.HostMedicine  project

**Comment by hikalkan** [comment]
I am addining this to backlog.
