### ISSUE TITLE
Please set length to EntityFrameworkCore IdentityServerClients table, column "ExtraProperties" and "ConcurrencyStamp"

### ISSUE THREAD

**Issue by jiazhiliang** [abpframework/abp#4361]
ABP Framework "Volo.Abp.IdentityServer.EntityFrameworkCore (v2.9.0)"

`builder.Entity<Client>(b =>` <== started line 31

Noticed that length is missing when specifying column "ExtraProperties" and "ConcurrencyStamp".

That will make entityFrameworkCore created with nvarchar(MAX) which results in very slow query performance to execute FindByCliendIdAsync().

**Comment by maliming** [comment]
You can customize it

**Comment by hikalkan** [comment]
I don't suppose it has a significiant performance effect, but specifying max length would be good for the ConcurrencyStamp. For ExtraProperties, we can't know how much it is needed, MAX is fine. Bu we can optimize it (like writing `null` to database instead of `{}` if doesn't contain a property)

**Comment by hikalkan** [comment]
@maliming,

We use GUID for the `ConcurrencyStamp` which is 36 chars at max. We can make it 40 chars in the database field.

Also, handle nulls for the ExtraProperties as I've explained.

What do you think, is that reasonable?

**Comment by maliming** [comment]
I will try it.

**Comment by maliming** [comment]
> We use GUID for the ConcurrencyStamp which is 36 chars at max. We can make it 40 chars in the database field.

Should we use 40 or 256?

https://github.com/abpframework/abp/blob/ddcfd3a1995721e958c332a0c459efaf4f9e8bef/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/IdentityUserConsts.cs#L27


> Bu we can optimize it (like writing null to database instead of {} if doesn't contain a property)

The value conversion function of ef core does not yet support the conversion of null.

**Comment by hikalkan** [comment]
>The value conversion function of ef core does not yet support the conversion of null.

OK, `{}` is fine for now.

>Should we use 40 or 256?

I believe 40 is fine. We can make such an assumption. Create a const on the framework and set `public const int MaxConcurrencyStampLength = ConcurrencyStampConsts.MaxLength;` (where ConcurrencyStampConsts is in the `Volo.Abp.Ddd.Domain` package, near to `IHasConcurrencyStamp` interface)
