### ISSUE TITLE
How to get data of 1 models in other services in microservice

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#4367]
Hi,

I'm creating a microservice project based on the abp sample. I don't know how to get data of service A from service B

Thanks

**Comment by hikalkan** [comment]
Write a REST API service to service A and use HttpClient to call it. This is a standard way even if you don't use the ABP Framework.

Also see https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients if you take advantage of dynamic C# HTTP API proxies.

**Comment by xyfy** [comment]
#4049 

@volethanh   here has a usefull PPT
