### ISSUE TITLE
`MethodInfo`/`MemberInfo`'s `GetCustomAttributes` method ignores the inherit parameter for properties and events.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#4372]
To search the inheritance chain for attributes on properties and events, use the appropriate overloads of the `Attribute.GetCustomAttributes` method.
https://docs.microsoft.com/en-us/dotnet/api/system.attribute.getcustomattributes?view=netcore-3.1

If we use attributes for abstract class methods, etc., some interceptors and attribute-dependent components will not work.
```cs
public abstract class MyBaseService
{
	[UnitOfWork]
	public virtual async Task TestMethod()
	{
	}
}

public class MyService : MyBaseService
{

}
```

@hikalkan What do you think?

**Comment by hikalkan** [comment]
I agree, but we should check all. Can you work on that if you have time in 3.0 milestone? Otherwise, we'll move to the backlog since we have enough planned work for 3.0.

**Comment by maliming** [comment]
I will move to v3.1 if it is not completed before v3.0 released.

**Comment by maliming** [comment]
This problem doesn't seem to exist, and I can't remember why I found this.
