### ISSUE TITLE
[Question] how to suport multi-tenant with legacy database which have no tenant Id

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#4389]
I have an old legacy database which we want to support multi tenant, we want to copy the database several times and each copy will be a tenant. current design has no tenant involved.

per my research, abp need tenant id for each table even if we create a separate database for the tenant, is it possible to support the old database which without tenant id but in a single db(we can create the needed abp tables in it)?

**Comment by liangshiw** [comment]
No tenant id, it means the data is the host data. If you want to differentiate the tenant data, you can pre-define the tenant and then migrate the data

**Comment by evenlee** [comment]
thanks for your answer. but i think i did not say it clear, my situation is I cannot change the old database design to add tenant id column but I can add new tables to the database(like abp default tables)
but without tenant id, abp cannot return data from the separated tenant db.

my research:
1) create new entity(no tenant id) with default mvc template and migrated
2) re - migrate the database as for tenant A
3)  create new tenant A use connection string of tenant A database
3) use a service to find the data:
 i do have records in tenant A's database, but when i give the right tenant id to the api request, no 
data returns. it returns data only when I add tenantid column to the table.

I was wondering: 
abp has know the tenantId(request header), then knows the separated tenant database by tenant connection string, is there a way to let abp does not use tenantid to filter data as the data is already in a tenant's own database,

e.g: there are some table without tenant id, when tenant id is null from request, return data from host database with no filters, when Tenant id comes from request(support tenant A), return all the data from tenant A's own database with no filters.

**Comment by liangshiw** [comment]
You can customize filter tenant expression

https://github.com/abpframework/abp/blob/ae8095d1eac23cad4d7f652012578157a5ba5a86/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L586

**Comment by liangshiw** [comment]
It works fine
![image](https://user-images.githubusercontent.com/16813853/84987221-5a718a80-b172-11ea-89eb-4326c6a06f61.png)

**Comment by evenlee** [comment]
thanks @liangshiw, let me try it:)

**Comment by evenlee** [comment]
@liangshiw can you share me the demo project you made?

**Comment by evenlee** [comment]
and two more question:
1) will data insert affected?
2) how did you generated the new tenant, do you create the tenant in host first and then use migrator to create the new?

As I know, if an entity does not have tenant Id, it cannot be migrated to tenant database, how do deal with this?

**Comment by liangshiw** [comment]
Steps:

1.  You can login to the application as a tenant and call service methods to add data
2.  Use the host to create the tenant and set the connection string, then run the `DbMigrator` application.
