### ISSUE TITLE
#4333 Error CS0115 'Pages_Books_Index.ExecuteAsync() still there

### ISSUE THREAD

**Issue by julianlaudat** [abpframework/abp#4396]
ABP Framework version 2.9.
MVC UI

I had seen #4333 before putting this up.

I am following the BookStore tutorial. A problem arises with the example code seem to cause a problem.

this is the line causing the problem in Index.cshtml
**@inherits Acme.BookStore.Web.Pages.BookStorePageModel**

In **Index.cshtml.cs**
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Acme.BookStore.Web.Pages.Books
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

@page
@using Acme.BookStore.Web.Pages.Books
@inherits Acme.BookStore.Web.Pages.BookStorePageModel
@model IndexModel

"Error CS0115 'Pages_Books_Index.ExecuteAsync()': no suitable method found to override".

I am following the tutorial and only found abp.io yesterday but I get the above error. It is probably something simple to fix or am I missing something in the documentation.

error is still there.

**Comment by liangshiw** [comment]
The updated document has not been release, but you can follow https://github.com/abpframework/abp/commit/ed46f92c10190a72151d430f628bfd7373836479#diff-6136c7c24aa5ee8a82fd19cfe6455365L564 the changes
