### ISSUE TITLE
how to add myown module to my solution?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#4400]
![image](https://user-images.githubusercontent.com/5259153/85020518-0b901900-b1a3-11ea-8425-a3fc687eefc8.png)

the stuctor of ZSHTech.TestMongo
![image](https://user-images.githubusercontent.com/5259153/85021175-0e3f3e00-b1a4-11ea-91bf-8d0223779ea0.png)

the stuctor of ZSHTech.CanteenManager
![image](https://user-images.githubusercontent.com/5259153/85021926-1fd51580-b1a5-11ea-9b2e-7c9229f4c783.png)

ZSHTech.TestMongo is a application folder and ZSHTech.CanteenManager is a module folder
I want to use abp cli  tools  to add module ZSHTech.CanteenManager to ZSHTech.TestMongo application, So I enter the ZSHTech.TestMongo folder and input the cmd in the folder
`abp add-module ZSHTech.CanteenManager -s F:\mysourcecode\abp_vnext_code\ZSHTech.CanteenManager\ZSHTech.CanteenManager.sln`

but I get the wrong msg:

[20:44:04 WRN] ERROR: 'ZSHTech.CanteenManager' module could not be found!

how to write the correct command？thanks

**Comment by liangshiw** [comment]
ABP CLI does not support adding local modules, You need to install manually.

**Comment by zsanhong** [comment]
maybe this function should be added to the abp cli
