### ISSUE TITLE
Question about the usage of RegisterDto in Account module

### ISSUE THREAD

**Issue by RayMMond** [abpframework/abp#4405]
ABP version: 2.9.0 **Source code**

## The usage of AppName

The AppName property is meaningless and not used.

Declaration:
https://github.com/abpframework/abp/blob/39b5260014518d44a428a1e00d800621d2987c2c/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/RegisterDto.cs#L24-L25

Implementation:
https://github.com/abpframework/abp/blob/39b5260014518d44a428a1e00d800621d2987c2c/modules/account/src/Volo.Abp.Account.Application/Volo/Abp/Account/AccountAppService.cs#L24-L36

## Why RegisterDto is not extendable
https://github.com/abpframework/abp/blob/39b5260014518d44a428a1e00d800621d2987c2c/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/RegisterDto.cs#L7-L26

**Comment by liangshiw** [comment]
https://github.com/abpframework/abp/blob/6a892bfa53d2c7745d4dfa0593a7aa82adb1b53b/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Register.cshtml.cs#L49

About extendable. See https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Guide

**Comment by RayMMond** [comment]
@liangshiw I need to add custom property to RegisterDto, but [Extend DTOs](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#extending-data-transfer-objects) requires that DTO is inherited from Extensible**EntityDto.

**Comment by RayMMond** [comment]
> I think maybe it is used for auditing:
> 
> https://github.com/abpframework/abp/blob/6a892bfa53d2c7745d4dfa0593a7aa82adb1b53b/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Register.cshtml.cs#L49
> 
> About extendable. See https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Guide

If there is only one app, what's the point of auditing app's name? So question is whether hosting multiple app is supported by ABP?

**Comment by liangshiw** [comment]
There are different front-end applications, like vue,android,ios...etc.

https://github.com/abpframework/abp/blob/a55b1db59c7af60d28517c7bd2c38dc00cdca868/npm/ng-packs/packages/account/src/lib/components/register/register.component.ts#L68

About extensible dto, I create an issue for this https://github.com/abpframework/abp/issues/4412

**Comment by RayMMond** [comment]
That's make sense, but I think adding some docs to **AppName** would be better, it's a little implicit.
Any way, thanks for the reply!

**Comment by leonkosak** [comment]
Where in Application (database) additional **AppName** could be defined (abp v3.3+)?

**Scenario**
Some external systems (applications) would use _/api/account/register_ API method to register user. It would be nice and correct to give each external system individual name, right?
Thank you.

[ERR] Url, named 'Abp.Account.EmailConfirmation', for the application 'MyBusinessApp' was not configured. Use AppUrlOptions to configure it!

(MyBusinessApp was provided via appName parameter.)
