### ISSUE TITLE
Datatable extensions: add support for resources other than Abpui for datatable "language" options

### ISSUE THREAD

**Issue by FrancoisKr** [abpframework/abp#4406]
Currently the language options are set in datatables-extensions.js, and the script uses the AbpUi resource only, making it impossible to use the datatable extensions AND translate the language options.

`var localize = function (key) {
        return abp.localization.getResource('AbpUi')(key);
    };`

`configuration.language = {
                info: localize("PagerInfo"),
                infoFiltered: localize("PagerInfoFiltered"),
                infoEmpty: localize("PagerInfoEmpty"),
                search: localize("PagerSearch"),
                processing: localize("ProcessingWithThreeDot"),
                loadingRecords: localize("LoadingWithThreeDot"),
                lengthMenu: localize("PagerShowMenuEntries"),
                emptyTable: localize("NoDataAvailableInDatatable"),
                paginate: {
                    first: localize("PagerFirst"),
                    last: localize("PagerLast"),
                    previous: localize("PagerPrevious"),
                    next: localize("PagerNext")
                }`

**Comment by liangshiw** [comment]
Hi,
See https://github.com/abpframework/abp/pull/4399/files.

You can customize datatable language configuration,It will be available in version 3.0 or you can manually copy it to your application

**Comment by FrancoisKr** [comment]
Great thanks!
