### ISSUE TITLE
Doc Module - GitHub Personal Access Token

### ISSUE THREAD

**Issue by seanalford** [abpframework/abp#4409]
In this section of the Doc Module, [Sample Project Record for "GitHub"](https://docs.abp.io/en/abp/latest/Modules/Docs#sample-project-record-for-github) links to GitHub for instructions on creating a personal access token, but doesn't define the scope requirements needed by the Doc Module.  

How should the scope be defined?

![image](https://user-images.githubusercontent.com/8544833/85064621-cefbf780-b179-11ea-82a5-62372b591c02.png)

**Comment by maliming** [comment]
Just **repo** scope. : )

**Comment by seanalford** [comment]
@maliming thx :)
