### ISSUE TITLE
Configure extensible Dtos for all pre-built modules

### ISSUE THREAD

**Issue by liangshiw** [abpframework/abp#4412]
This document describes that all pre-built modules dto are configured to be extensible, but only some DTO are configured. We should configure All Dto.

![image](https://user-images.githubusercontent.com/16813853/85087118-2f894400-b20f-11ea-9457-1627746ec395.png)

**Comment by xyfy** [comment]
it may be related with #4447

**Comment by liangshiw** [comment]
https://github.com/abpframework/abp/pull/4427#issuecomment-650603470
