### ISSUE TITLE
class AbpIdentitySettingDefinitionProvider has a problen

### ISSUE THREAD

**Issue by hubo0831** [abpframework/abp#4414]
below code :
                 new SettingDefinition(
                    IdentitySettingNames.OrganizationUnit.MaxUserMembershipCount,
                    int.MaxValue.ToString(), 
                    L("Identity.OrganizationUnit.MaxUserMembershipCount"),
                    L("Identity.OrganizationUnit.MaxUserMembershipCount"),
                    true)
LocalizableString missing DisplayName and Description

**Comment by maliming** [comment]
I found no problem.
