### ISSUE TITLE
BackgroundTask in multiple modules

### ISSUE THREAD

**Issue by dmeagor** [abpframework/abp#4425]
What is the recommended way to add BackgroundJobs to multiple modules within a monolithic application.  As standard they are included in the Application template but not the Module ones.

Are there any issues running muitiple BackgroundJobs queues (presumably all with their own module name prefixed tables.) 

Would a hangfire implementation be better for this?

**Comment by liangshiw** [comment]
If it is a cluster environment, it is recommended that you use hangfire. If it is a distributed application, each module has its own background jobs table, then you can use the default implementation.

**Comment by dmeagor** [comment]
Thanks.  Initially we will be deploying as a single application with separate databases for the modules so I'm guessing the default implementation will be fine.
