### ISSUE TITLE
How to use IGuidGenerator to create Sequential ID for the ABP entity and seed data

### ISSUE THREAD

**Issue by huoyuanss** [abpframework/abp#4435]
Hi,
   1、 I can use IGuidGenerator to create Sequential Id as primary key for my own business entity， bug how can I  create Sequential Id for the ABP entity or ABP table？ Such the AbpAuditLogs, AbpUsers  and so on. These tables store a lot of data, we should have a method to solve this problem. 
   2、how can I use DbMigrator project to seed data with Sequential Id？

**Comment by gdlcf88** [comment]
Maybe you should read [this article](https://www.codeproject.com/Articles/388157/GUIDs-as-fast-primary-keys-under-multiple-database) to understand SQL Server's SequentialAtEnd Sequential GUID.

**Comment by liangshiw** [comment]
You just inject `IGuidGenerator` and  use it to generate id.
See https://docs.abp.io/en/abp/latest/Guid-Generation

**Comment by huoyuanss** [comment]
I kown how to use IGuidGenerator  on my own entities,but how to use on the ABP's entities or tables, like AbpAuditLogs,AbpUsers,AbpUserTokens ? I can't even modify these ABP's APIS.

**Comment by liangshiw** [comment]
ABP framework uses `IGuidGenerator` internally

https://github.com/abpframework/abp/blob/1a622bc50fbd9b554f61078d5eeafa9def3216e3/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain/Volo/Abp/AuditLogging/AuditLog.cs#L63
