### ISSUE TITLE
EntityChangeEventHelper.TriggerEventWithEntity Parameter use error？

### ISSUE THREAD

**Issue by yangfan-zz** [abpframework/abp#4436]
### In EntityChangeEventHelper  class  at TriggerEventWithEntity method

```csharp
protected virtual async Task TriggerEventWithEntity(
            IEventBus eventPublisher,
            Type genericEventType,
            object entityOrEto,
            object originalEntity,
            bool triggerInCurrentUnitOfWork)
        {

            if (triggerInCurrentUnitOfWork || currentUow == null)
            {
                await eventPublisher.PublishAsync(
                    eventType,
                    Activator.CreateInstance(eventType, entityOrEto)
                );
                  
                return;
            }
                                  ...
      }
 }
```

### should be
            if (!triggerInCurrentUnitOfWork || currentUow == null)

**Comment by liangshiw** [comment]
If `triggerInCurrentUnitOfWork` value is `true` or `currentUow` is null. before saving the unit of work publish event,
I think there is no problem.

**Comment by yangfan-zz** [comment]
when **currentUow** not **null** and **triggerInCurrentUnitOfWork** value is **true** , then unable to trigger event using unit of work.

**Comment by liangshiw** [comment]
Sorry, I do not understand what you mean.

**Comment by liangshiw** [comment]
See https://github.com/abpframework/abp/blob/dev/docs/en/Local-Event-Bus.md
