### ISSUE TITLE
Provide a better way to custom existing module

### ISSUE THREAD

**Issue by goxiaoy** [abpframework/abp#4439]
The feature `Object Extensions` provide a great way to custom existing entity/dtos
but it's kind of tricky in generated apis.
I propose a better way to custom existing application and dtos

Considering the following purpose
I want to custom existing `IdentityUser` relative api, which starts with `/api/identity/users`
1. add custom field return in `Volo.Abp.Identity.IdentityUserDto`, such as adding `address` object, add birthday field
The existing `Object Extensions` can only add custom data into `extraProperties`

2. add custom filter to `GetIdentityUsersInput` such as `FilterRole` to filter users who has such role

---

For the purpose 1, It's easy to implement based on OO design

add custom class MyIdentityUserDto
```
public class MyIdentityUserDto:Volo.Abp.Identity.IdentityUserDto
{
  public AddressDto Address { get; set; }
  ...
}
```
add custom class IdentityUserAppService
```
    [Dependency(ReplaceServices = true)]
    public class IdentityUserAppService: Volo.Abp.Identity.IdentityUserAppService
    {
         ...

        public override async Task<IdentityUserDto> GetAsync(Guid id)
        {
            var source=await base.GetAsync(id);
            var ret = ObjectMapper.Map<IdentityUserDto, MyIdentityUserDto>(source);
            ...
            return ret;
        }
    }
```
so the response model will be new created polymorphic `MyIdentityUserDto`  

---
For the purpose 2, you can use [Custom Model Binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1) to achieve polymorphic  model binding

create class `MyGetIdentityUsersInput`
```
    public class MyGetIdentityUsersInput: GetIdentityUsersInput
    {
        public string FilterRole { get; set; }
    }
```
implement custom `IModelBinderProvider` and `IModelBinder`, so that you can use your class to perform query
```
    [Dependency(ReplaceServices = true)]
    public class IdentityUserAppService: Volo.Abp.Identity.IdentityUserAppService
    {
         private readonly IUserAddressRepository _userAddressRepository;

         ...

        public override async Task<PagedResultDto<IdentityUserDto>> GetListAsync(GetIdentityUsersInput input)
        {
            var myInput = input as MyGetIdentityUsersInput;
            //myInput will not be null
            //...
        }
    }
```

---
For now, your api will support new created dtos. But the generated swagger document will be incorrect, so you need to custom swagger document generation
this can be done by replace existing `AbpModelMetadataProvider` to replace type and properties meta with new created dtos

---
Final result.
![image](https://user-images.githubusercontent.com/8577611/85205469-1f2bb300-b34e-11ea-998c-ccb1e5bd3391.png)

![image](https://user-images.githubusercontent.com/8577611/85205481-2a7ede80-b34e-11ea-98bd-90c7f60da5c4.png)

---
If you think it's a good design, I can open a PR for this 😄

**Comment by maliming** [comment]
This also needs to consider the dynamic API, http api proxy, etc. You can continue to test it in your modules and applications.

**Comment by hikalkan** [comment]
Hi @Goxiaoy 

Thanks for sharing your thoughts. I didn't find this kind design useful. It breaks standards and will not compatible to API explorer or other type of systems.

We will continue to improve the ExtraProperties way, but at least foe now, we don't want to introduce a new kind of extensibility way until we make the ExtraProperties was more mature and feature complete.

**Comment by hemiaoio** [comment]
Based on this problem, I have my problem. If I want to combine user-defined fields, roles and other data to filter users, I can't find an effective implementation of database based filtering.I have a [Flag] enum field in AppUser, I'm going to use HasFlag() to filter this field, and I find that it can't be implemented through IdnetityUserRepository.
```
The LINQ expression 'DbSet<IdentityUser>()
    .Where(i => __ef_filter__p_0 || !(EF.Property<bool>(i, "IsDeleted")) && __ef_filter__p_1 || (Nullable<Guid>)EF.Property<Guid>(i, "TenantId") == __ef_filter__CurrentTenantId_2)
    .Where(i => i
        .GetUserType().HasFlag((Enum)Administrator))' could not be translated. Either rewrite the query in a form that can be translated,
```

**Comment by luy710** [comment]
how to custom existing module? GetIdentityUsersInput
