### ISSUE TITLE
Docs is wrong about dependency injection part of customizing SignInManager

### ISSUE THREAD

**Issue by RayMMond** [abpframework/abp#4440]
### Documentation

[Docs](https://docs.abp.io/en/abp/latest/How-To/Customize-SignIn-Manager#register-to-dependency-injection) says:

Inside your .Web project, locate the YourProjectNameWebModule and add the following code under the PreConfigureServices method to replace the old SignInManager with your customized one:

```
PreConfigure<IdentityBuilder>(identityBuilder =>
{
    identityBuilder.AddSignInManager<CustomSignInManager>();
});
```

But actually, if you add this to module's PreConfigureServices method as docs said, the code below will override SignIdManager with default one.

https://github.com/abpframework/abp/blob/0ea1e59d3be1241433434c73c81bff293f5aaeb5/modules/identity/src/Volo.Abp.Identity.AspNetCore/Volo/Abp/Identity/AspNetCore/AbpIdentityAspNetCoreModule.cs#L14-L17

**Comment by liangshiw** [comment]
We should configure `IdentityBuilder` using `PreConfigure` in `AbpIdentityAspNetCoreModule`
