### ISSUE TITLE
[bug] TokenCleanupBackgroundWorker will fail when enable Volo.Abp.BackgroundJobs.Quartz

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#4442]
@liangshiw Hi:
   Thank you for `Volo.Abp.BackgroundWorkers.Quartz` module to integrate Quartz,
but I think [`QuartzBackgroundWorkerManager`](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BackgroundWorkers.Quartz/Volo/Abp/BackgroundWorkers/Quartz/QuartzBackgroundWorkerManager.cs#L37) lost some things :
```csharp
[Dependency(ReplaceServices = true)]
public class QuartzBackgroundWorkerManager : IBackgroundWorkerManager
{
        public virtual void Add(IBackgroundWorker worker)
        {
            AsyncHelper.RunSync(() => ReScheduleJobAsync(worker));
        }

        protected virtual async Task ReScheduleJobAsync(IBackgroundWorker worker)
        {
            if (worker is IQuartzBackgroundWorker quartzWork)
            {
                Check.NotNull(quartzWork.Trigger, nameof(quartzWork.Trigger));
                Check.NotNull(quartzWork.JobDetail, nameof(quartzWork.JobDetail));

                if (quartzWork.ScheduleJob != null)
                {
                    await quartzWork.ScheduleJob.Invoke(_scheduler);
                }
                else
                {
                    await DefaultScheduleJobAsync(quartzWork);
                }
            }
        }
}
```
When I enable this module, it take over the only one `IBackgroundWorkerManager` in app,
so if other modules has workers that is not a `IQuartzBackgroundWorker`(example:[`TokenCleanupBackgroundWorker`](https://github.com/abpframework/abp/blob/dev/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/Tokens/TokenCleanupBackgroundWorker.cs))
will be ignored. 
```csharp
namespace Volo.Abp.IdentityServer.Tokens
{
    public class TokenCleanupBackgroundWorker : AsyncPeriodicBackgroundWorkerBase
    {
        protected TokenCleanupOptions Options { get; }
        protected override async Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
        {
             ....
        }
    }
}
```

I should to create a new `QuartzTokenCleanupBackgroundWorker` class that implement `IQuartzBackgroundWorker` to fix it.

And also,  `BackgroundJobWorker` of  `Volo.Abp.BackgroundJobs` is the same,
If I just use `Volo.Abp.BackgroundWorkers.Quartz` but not `Volo.Abp.BackgroundJobs.Quartz`,
the default `BackgroundJobWorker` will doesn't work.

I think `IBackgroundWorkerManager` should ensure  All `IBackgroundJobWorker`(not only `IQuartzBackgroundWorker`) in application works fine

Do you have any idea ?
Please let me know if I have misunderstood about design of this module,Thanks.

**Comment by yinchang0626** [comment]
Temporary,maybe this is the simplest way to resolve it now.
But I think will cause other issue when  `QuartzBackgroundJobManager` is enabled
```csharp
    [Dependency(ReplaceServices = true)]
    public class FixQuartzBackgroundWorkerManager : IBackgroundWorkerManager,ISingletonDependency
    {
        private readonly QuartzBackgroundWorkerManager quartzBackgroundWorkerManager;
        private readonly BackgroundWorkerManager backgroundWorkerManager;

        public FixQuartzBackgroundWorkerManager(
            QuartzBackgroundWorkerManager quartzBackgroundWorkerManager,
            BackgroundWorkerManager backgroundWorkerManager
            )
        {
            this.quartzBackgroundWorkerManager = quartzBackgroundWorkerManager;
            this.backgroundWorkerManager = backgroundWorkerManager;
        }
        public void Add(IBackgroundWorker worker)
        {
            quartzBackgroundWorkerManager.Add(worker);
            backgroundWorkerManager.Add(worker);
        }

        public async Task StartAsync(CancellationToken cancellationToken = default)
        {
            await quartzBackgroundWorkerManager.StartAsync(cancellationToken);
            await backgroundWorkerManager.StartAsync(cancellationToken);
        }

        public async Task StopAsync(CancellationToken cancellationToken = default)
        {
            await quartzBackgroundWorkerManager.StopAsync(cancellationToken);
            await backgroundWorkerManager.StopAsync(cancellationToken);
        }
    }
```

**Comment by liangshiw** [comment]
We can create an adapter to provide quartz support instead of using the default implementation, I will try implement.
