### ISSUE TITLE
Need to fine-tune "abp-modal" (suppress unsaved changes warning)

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#4444]
Hi,

I cannot find how to suppress showing "You have unsaved changes" warning in abp-modal.

**Comment by maliming** [comment]
You can find a solution by looking at the source code.

https://github.com/abpframework/abp/blob/bb00278a9b160d258110782b42ad906b8a73dbb1/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L75-L77

**Comment by alexandis** [comment]
It's strange - first of all, I don't have form tag at all in my abp-modal: I have removed it, because the functionality inside abp-modal does not need a form at all. According to the source code, this part of logic should not have been triggered at all:
`if (_$form.length) {`

For experiment, I have added form back and added attribute to it:
`<ng-template #abpBody>
    <form data-check-form-on-close="false">`

But it did not work either - the confirmation message is still there. What am I missing?

**Comment by alexandis** [comment]
BTW, I have noticed you were referencing MVC, but I am using Angular...

**Comment by maliming** [comment]
hi

You should answer the questions in the issue template. : )

* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* ....

Angular doesn't seem to implement the function to disable the `You have unsaved changes` message.

**Comment by mehmet-erim** [comment]
Hi @alexandis 

Unfortunately, there is no way to suppress the confirmation popup. We'll add an input to `abp-modal` for disabling/enabling this feature.

**Comment by alexandis** [comment]
Hi, any progress on that?

**Comment by mehmet-erim** [comment]
Hi @alexandis

We are working on it.

**Comment by mehmet-erim** [comment]
## How to use

When v4.0 is released, you can add a new provider to `app.module.ts` as shown below to suppress the unsaved changes warning popup:

```
// app.module.ts

import { SUPPRESS_UNSAVED_CHANGES_WARNING } from '@abp/ng.theme.shared';

// ...

@NgModule({
  // ...
  providers: [{provide: SUPPRESS_UNSAVED_CHANGES_WARNING, useValue: true}]
```

...or you can pass the `suppressUnsavedChangesWarning` input value as true to the `<abp-modal>` tag like below:

```html
<abp-modal [suppressUnsavedChangesWarning]="true">
```

Note: The `ModalComponent` input (`suppressUnsavedChangesWarning`) value overrides the `SUPPRESS_UNSAVED_CHANGES_WARNING` injection token value.

**Comment by freelearncoding** [comment]
@mehmet-erim, is it possbile to overwrite  / customize text on unsaved changes popup screen?
![image](https://user-images.githubusercontent.com/86627409/170042479-51768416-b11d-47e1-9b91-9b6c494e5da1.png)

**Comment by mehmet-erim** [comment]
Hi @freelearncoding, this issue was closed 2 years ago so would you mind creating a new issue for that?

**Comment by freelearncoding** [comment]
@mehmet-erim , Done! [#12742](https://github.com/abpframework/abp/issues/12742)
