### ISSUE TITLE
how can I add additional property to params

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4447]
if I want to override Volo.Abp.Identity.IdentityUserAppService.GetListAsync
```
public virtual Task<PagedResultDto<IdentityUserDto>> GetListAsync(GetIdentityUsersInput input)
```

How can I add an additional property named 'UserType'  to  `GetIdentityUsersInput ` input

GetIdentityUsersInput  is not an ExtensibleObject

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/4412
