### ISSUE TITLE
Add Permission Dynamically by Tenant

### ISSUE THREAD

**Issue by gumalheiros** [abpframework/abp#4448]
Hi,
I need to add permission Dynamically by Tenant.
I got it that way with the "Permission DefinitionProvider" and the permissions loaded right, but when I change Tenant, it doesn't update the list of permissions on the screen. This works if I restart the API application. Is there a way to resolve this? I'm using Angular 9.

Thanks by this excelent framework!!
I intend to make some videos in Portuguese for the community.

My Code:
```csharp
 public class CustomerPortalPermissionDefinitionProvider : PermissionDefinitionProvider, ITransientDependency
    {
        private IRepository<Cliente, int> _customerRepository;
        private readonly ICurrentTenant _currentTenant;

        public CustomerPortalPermissionDefinitionProvider(IRepository<Cliente, int> customerRepository, ICurrentTenant currentTenant)
        {
            _customerRepository = customerRepository;
            _currentTenant = currentTenant;
        }
        public override void Define(IPermissionDefinitionContext context)
        {
            
            var grpCustomer = context.AddGroup("Customer");

            var customerManagement =  grpCustomer.AddPermission("Customer_Management", null, MultiTenancySides.Tenant);
            customerManagement.AddChild("Customer_Management_Create");
            customerManagement.AddChild("Customer_Management_Edit");
            customerManagement.AddChild("Customer_Management_Delete");
            
            var visualizar = customerManagement.AddChild("Customer_Management_View");
            var customers = _customerRepository.Where(c => c.TenantId == _currentTenant.Id).ToList();
            foreach (var item in customers)
            {
                visualizar.AddChild("Customer_" + item.Id);
            }

        }
    }
```

![image](https://user-images.githubusercontent.com/53195213/85249782-b19d8680-b422-11ea-8cf1-d65e39eb7fc9.png)

**Comment by NecatiMeral** [comment]
I think that's not how the tenants are intended to be used.
You can't define permissions per tenant, since the permission provider runs only once (i think).

**Comment by gumalheiros** [comment]
> I think that's not how the tenants are intended to be used.
> You can't define permissions per tenant, since the permission provider runs only once (i think).

Thanks @NecatiMeral for the comment. As far as I could see, that's right. I'm trying to find a way to refresh the "Define" method, but without success yet!

**Comment by liangshiw** [comment]
The easiest way is to customize `PermissionDefinitionManager` and set DI life to `transient`(Will be initialized every time), like this:

```csharp
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPermissionDefinitionManager))]

public class MyPermissionDefinitionManager : PermissionDefinitionManager,ITransientDependency
{
    public MyPermissionDefinitionManager(
        IOptions<AbpPermissionOptions> options,
        IServiceProvider serviceProvider)
        : base(options, serviceProvider)
    {
    }

    public override PermissionDefinition Get(string name)
    {
        try
        {
            return base.Get(name);
        }
        catch (Exception e)
        {
            return MyPermissionDefinition.CreatePermissionDefinition(name);
        }

    }
}

public class MyPermissionDefinition : PermissionDefinition
{
    protected internal MyPermissionDefinition(string name, ILocalizableString displayName = null, MultiTenancySides multiTenancySide = MultiTenancySides.Both, bool isEnabled = true)
        : base(name, displayName, multiTenancySide, isEnabled)
    {
    }


    public static PermissionDefinition CreatePermissionDefinition(string name)
    {
        return new MyPermissionDefinition(name,isEnabled:false);
    }
}
```
This way can achieve your purpose, but it is not a best practice. Another way is that you can define the `Refresh` method in the custom `PermissionDefinitionManager` class and call it when switching tenants.

**Comment by gumalheiros** [comment]
> The easiest way is to customize `PermissionDefinitionManager` and set DI life to `transient`(Will be initialized every time), like this:
> 
> ```cs
> [Dependency(ReplaceServices = true)]
> [ExposeServices(typeof(IPermissionDefinitionManager))]
> 
> public class MyPermissionDefinitionManager : PermissionDefinitionManager,ITransientDependency
> {
>     public MyPermissionDefinitionManager(
>         IOptions<AbpPermissionOptions> options,
>         IServiceProvider serviceProvider)
>         : base(options, serviceProvider)
>     {
>     }
> 
>     public override PermissionDefinition Get(string name)
>     {
>         try
>         {
>             return base.Get(name);
>         }
>         catch (Exception e)
>         {
>             return MyPermissionDefinition.CreatePermissionDefinition(name);
>         }
> 
>     }
> }
> 
> public class MyPermissionDefinition : PermissionDefinition
> {
>     protected internal MyPermissionDefinition(string name, ILocalizableString displayName = null, MultiTenancySides multiTenancySide = MultiTenancySides.Both, bool isEnabled = true)
>         : base(name, displayName, multiTenancySide, isEnabled)
>     {
>     }
> 
> 
>     public static PermissionDefinition CreatePermissionDefinition(string name)
>     {
>         return new MyPermissionDefinition(name,isEnabled:false);
>     }
> }
> ```
> 
> This way can achieve your purpose, but it is not a best practice. Another way is that you can define the `Refresh` method in the custom `PermissionDefinitionManager` class and call it when switching tenants.

Works Like a Charm!! 😄    Thanks @liangshiw

**Comment by alexandis** [comment]
@realLiangshiwei hi, I have similar problem - I'm trying to assign custom permission (which actually is a different kind of permission and served by a different permission definition provider) to a role. And I also want to avoid restarting app and just hot-reload a list of available permissions. Making the manager ITransient is not a way to go, it would be too slow. But I need kind of "Refresh" method you mentioned. However, I do not imagine what it is supposed to look like to force an up-to-date list of permissions to be loaded... Could you please explain? Should I just call `GetPermissionsAsync` inside and return void?
