### ISSUE TITLE
Runtime configuration in Angular App

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#4449]
Hi,
@mehmet-erim  In your angular demo project, you used the compile-time configuration. is it not better we change it run time configuration?

**Comment by mehmet-erim** [comment]
Hi @mehdihadeli,

Can you explain your question in more detail and examples?

**Comment by mehdihadeli** [comment]
Yes, In this article compared two approaches for setup configuration in angular apps. `run time configuration` and `compile-time configuration`. in your angular apps, you used compile-time configuration. in this article and some others, suggested use of run time configuration for more flexibility. what is your opinion?
link: https://juristr.com/blog/2018/01/ng-app-runtime-config/

**Comment by mehmet-erim** [comment]
We are using the compile-time configuration because it is a default in Angular. Many people use ABP's Angular UI. As much as possible we should choose the default systems. If you would like to use the runtime configuration, you can use it. ABP does not prevent this.

**Comment by mehdihadeli** [comment]
> We are using the compile-time configuration because it is a default in Angular. Many people use ABP's Angular UI. As much as possible we should choose the default systems. If you would like to use the runtime configuration, you can use it. ABP does not prevent this.

ok thanks.
