### ISSUE TITLE
IdentityUserManager inject problem

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4450]
I have a Project named 'Yun.Module.IdentityManager.Web'
and `WebModule.cs` has below Dependson
``` C#
        typeof(IdentityManagerHttpApiModule),
        typeof(AbpAspNetCoreMvcUiThemeSharedModule),
        typeof(AbpAccountWebIdentityServerModule),
        typeof(IdentityManagerApplicationModule),
        typeof(IdentityManagerEntityFrameworkCoreDbMigrationsModule),
```
and in the `Yun.Module.IdentityManager.Domain` project   has depends on `AbpIdentityDomainModule`

And I add a class named 'IdentityManagerPageModel'  extending `AbpPageModel`
 
``` C#
    public abstract class IdentityManagerPageModel : AbpPageModel
    {
        public SignInManager<IdentityUser> SignInManager { get; set; }
        public YunIdentityUserManager UserManager { get; set; }
        [RazorInject]
        public IConfiguration Configuration { get; set; }

        protected IdentityManagerPageModel()
        {
            LocalizationResourceType = typeof(YunResource);
        }
    }
```

`YunIdentityUserManager`  overide the `Volo.Abp.Identity.IdentityUserManager`
``` C#
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(Volo.Abp.Identity.IdentityUserManager))]
    public class YunIdentityUserManager : Volo.Abp.Identity.IdentityUserManager
    {}
```
It always  got null value ,when get the property in `IdentityManagerPageModel `,`UserManager `

what should I do to inject the property successful?

**Comment by xyfy** [comment]
I try to register  
`public IdentityUserManager UserManager { get; set; }`

It got null value as well

**Comment by liangshiw** [comment]
I can't reproduce your problem, please check your code.

![image](https://user-images.githubusercontent.com/16813853/85263364-a473ac80-b4a1-11ea-85c6-d5c23685c92a.png)

**Comment by xyfy** [comment]
I just create a module to customize the abp identity & account module.  I think there is some dependson or configurtion is wrong.    but I can not find out it.

if I just use one project to do this ,it works as well.

![1](https://user-images.githubusercontent.com/7838147/85263811-4dbaa280-b4a2-11ea-9b13-f52b874ed98c.jpg)

**Comment by xyfy** [comment]
I use abp cli  add the `identity ` &`account ` module to `IdentityManager`
```
abp add-module Volo.Account
```

**Comment by xyfy** [comment]
here the property  is not null ,and got the correct value.
```
 public SignInManager<IdentityUser> SignInManager { get; set; }
``

**Comment by xyfy** [comment]
Thanks @liangshiw 

I fixed the module depends,now it can inject `IdentityUserManager UserManager`

then I below code to direct inject `YunIdentityUserManager `  as property

```
public override void ConfigureServices(ServiceConfigurationContext context)
        {
...
            //AbpUserManager
            context.Services.TryAddScoped<YunIdentityUserManager>();
...
}
```
