### ISSUE TITLE
SetMenuPlacement not applied when logout and  login

### ISSUE THREAD

**Issue by TuyenDinh1205** [abpframework/abp#4456]
Hi all
I have a problem of SetMenuPlacement.
Currently, my menu is on the left. 
![ERROR1](https://user-images.githubusercontent.com/34994601/85282446-f3c3d800-b4b5-11ea-8c7e-5c8e34aaef06.PNG)
I would like to set Menu on the top of page so I use layoutStateService.dispatchSetMenuPlacement(1), then it's ok. As a result: 
![ERROR2](https://user-images.githubusercontent.com/34994601/85282480-050ce480-b4b6-11ea-8a31-eb8db4511308.PNG)
But I have trouble:
- It can't work when I log in and log out again , Menu is still on the left.
- When I refresh this page, Menu is on the top.

How I can set it's alway on top when I logout and login again

**Comment by liangshiw** [comment]
Hi,
For issues about the abp commercial version, please create an issue in the support forum: https://support.abp.io/QA/Questions. Thanks.
