### ISSUE TITLE
Update IdentityServer4-packages and examples to IS4 ≥ 4.0.0

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#4461]
Since the [IdentityServer4](IdentityServer/IdentityServer4) project released a new major release (4.0.0), the abp framework should consider updating it's own guides, tutorials and examples to the latest IS4 release.

As far I've tested, the following adjustments have to be made:
- Update IdentityServer4 configuration to separate ApiResources and ApiScopes: [Migration steps](https://identityserver4.readthedocs.io/en/latest/topics/resources.html#migration-steps-to-v4)
  - When separating the scopes, check their naming and consider to update them

If wanted, I can create a PR with my propsals.

**Comment by maliming** [comment]
hi @NecatiMeral 

This is a major version update, and brings a lot of **breaking changes.**  This may involve a lot of changes, the workload may be very large.

 if you have time, you are welcome to contribute code. Otherwise I can try to upgrade it in v3.1.

**Comment by hikalkan** [comment]
@maliming can you check how feasible to make this work in this milestone?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/4578
