### ISSUE TITLE
Setting CommandTimeout when using a default repository: 'IRepository<MyEntity, Guid>'

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#4462]
Hi,

I am on ABP v2,8,0

When using default repositories (example `IRepository<MyEntity, Guid> _myEntityRepo `), how do you set the CommandTimeout?

I have tried:  _myEntityRepo.GetDbContext().Database.SetCommandTimeout(180); and I get a `System.ObjectDisposedException`  

> Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context...  

Does this mean I will have to implement a custom repository to do this or is there a way to do it properly?

Thank-you!

**Comment by maliming** [comment]
You can configure timeout options for units of work.

https://github.com/abpframework/abp/blob/ae8095d1eac23cad4d7f652012578157a5ba5a86/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L184-L191

> Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context...

This is like a problem with the unit of work, you can share some code.

**Comment by tinonetic** [comment]
Thank-you @maliming 

Do I put this in my DbContext of type: `AbpDbContext<>`?

It works sometimes but at other times I do get a timeout.

I will create a project that reproduces the scenario

**Comment by tinonetic** [comment]
Thanks, this worked! Went over my head that I needed to `override` the initialization method in my DbContext:

```c#
[ConnectionStringName("Default")]
public class MyDbContext : AbpDbContext<MyDbContext>, IMyDbContext
{
       public override void Initialize(AbpEfCoreDbContextInitializationContext initializationContext)
        {
            Database.SetCommandTimeout(TimeSpan.FromSeconds(60));
            base.Initialize(initializationContext);
        }

        //.... other code ....
}
