### ISSUE TITLE
How can I manage permissions for special case users?

### ISSUE THREAD

**Issue by soullpoint** [abpframework/abp#4464]
I have an application that will be structured as follows:

- Have staff Users, who may view all parts of the system, subject to the usual roles/permissions they have
- Can create an Account that is associated with a customer
- An Account may have orders
- Accounts may be allowed to log into the application, but may only view their own details and orders that are associated with themselves

How would something like this be implemented? It doesn't seem to quite fit into the Roles model as they can access the pages, but the specific resources must be restricted.

The only solution I can come up with is to extend users and add an optional AccountId foreign key. They would be treated like regular users when logging in, but if the user has an AccountId reference then the resources will be restricted based on that.

I'm not sure if this is a good approach.

Any advice or suggestions would be appreciated.

Thanks!

**Comment by gumalheiros** [comment]
Hi,
Can you see if this #4448 can help you!!

**Comment by hikalkan** [comment]
Why not creating a custom authorization logic? ABP doesn't provide a resource based authorization. However, AspNet Core has: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased and the ABP framework is compatible with this approach.
