### ISSUE TITLE
JsonSerializationException: Could not cast or convert from System.DateTime to NodaTime.Instant

### ISSUE THREAD

**Issue by jortygu** [abpframework/abp#4466]
Hi ，

   i  have two applications just like  App1(Web),App2(ApiHost). in App2 ,i define a AppService while return DemoModel, App1 call this AppService by Dynamic C# API Clients Setting.
   my question is when App1 call this AppService, it throw error 'Newtonsoft.Json.JsonSerializationException: Error converting value 6/22/2020 7:24:24 AM to type 'NodaTime.Instant'. Path 'demoModel.createdAt', line 1, position 207.
 ---> System.ArgumentException: Could not cast or convert from System.DateTime to NodaTime.Instant', i have configure MvcNewtonsoftJsonOptions,but it's not work for me!
if i call MyApp2Service by swagger, it's work.
```c#
public class DemoModel
{
  public Instant CreatedAt { get; set; }
}
//App2(ApiHost)  //Auto API Controllers
public interface IMyApp2AppService : IApplicationService {
        Task<DemoModel> Details(string id);
}
//App2(Web)
var model = await _myApp2AppService.Details(id); //throw error here
//MvcNewtonsoftJsonOptions Configure
public override void ConfigureServices(ServiceConfigurationContext context)
{
    Configure<MvcNewtonsoftJsonOptions>(options => {
        options.SerializerSettings.Converters.Add(
            NodaConverters.CreateDateTimeZoneConverter(DateTimeZoneProviders.Tzdb));
    });
}
```

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by jortygu** [comment]
below is my solution!
```
[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IJsonSerializer))]
public class NewtonsoftJsonInstantSerializer: NewtonsoftJsonSerializer, ITransientDependency
{
	public NewtonsoftJsonInstantSerializer(AbpJsonIsoDateTimeConverter dateTimeConverter)
		: base(dateTimeConverter)
	{

	}

	protected override JsonSerializerSettings CreateSerializerSettings(bool camelCase = true, bool indented = false)
	{
		var settings = base.CreateSerializerSettings(camelCase, indented);
		settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
		return settings;
	}
}
```
