### ISSUE TITLE
How can I receive a extra property from pre-builtin module api

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#4467]
How can I receive a extra property from pre-builtin module api

such as the method `Task<IdentityUserDto> CreateAsync(IdentityUserCreateDto input)` in  `Volo.Abp.Identity.IdentityUserAppService` 

I want extend `IdentityUserCreateDto ` ,add a `UserType` property to it ,

I followed this doc（https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#extending-data-transfer-objects）

```C#
    public static class IdentityManagerDomainObjectExtensions
    {
        private static readonly OneTimeRunner OneTimeRunner = new OneTimeRunner();

        public static void Configure()
        {
            OneTimeRunner.Run(() =>
            {
                ObjectExtensionManager.Instance
                .AddOrUpdateProperty<UserType>(
                    new[]
                    {
                        typeof(IdentityUserDto),
                        typeof(IdentityUserCreateOrUpdateDtoBase),
                    },
                    nameof(AppUser.UserType), options =>
                    {
                        options.DefaultValue = UserType.普通用户;
                    });
            });
        }
    }
```

when  I call the method `CreateAsync` through the httpapi,   how can I pass the value to api backend?
I try add a field named 'UserType' or Json Array
``` json
{"userName":"111111",
"extraProperties":[{"userType":2}]
}
```
or 

``` json
{
"userName":"111111",
"userType":2
}
```
It can not works

**Comment by xyfy** [comment]
```
It is also possible to extend Data Transfer Objects (DTOs) used by the application services. In this way, you can get extra properties from the UI (or client) and return extra properties from the service.
```

do it mean ，I can not pass the extra properties from ui(or client)?only return from backend?

**Comment by liangshiw** [comment]
It possible, but your code has error.

Should be:
```csharp
{
 "userName":"111111",
 "extraProperties":{"UserType":2}
}
```

![image](https://user-images.githubusercontent.com/16813853/85369330-83719100-b55f-11ea-89d4-5b244dc515cc.png)

**Comment by xyfy** [comment]
thanks ,I will try it

**Comment by xyfy** [comment]
It works fine,thanks again~
