### ISSUE TITLE
Can’t run microservice Demo

### ISSUE THREAD

**Issue by ToanDao2612** [abpframework/abp#4475]
i try run microservice demo then i get exception in picture below!
[Image](https://i.imgur.com/ytdWU5w.jpg)
![Image](https://i.imgur.com/YPqcEe2.jpg)

**Comment by maliming** [comment]
The problem should be related to sql server.

![image](https://user-images.githubusercontent.com/6908465/85483874-42798b00-b5f8-11ea-82b5-aa2090fd2141.png)

**Comment by simonmatt** [comment]
@maliming 
You could use the command line to check the logs for SQL Server of Docker
```bash
$ docker logs yoursqlservercontianernameorid
```
to see if the connection works properly.
