### ISSUE TITLE
How do I make FluentValidation work when the Dto is in another Dto

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#4478]
I have two validators:
CreateADtoValidator、CreateBDtoValidator     
Dto:
CreateADto、CreateBDto
```
public class CreateADto
{
   .......
   public virtual List<CreateBDto> Items { get; set; }
}
```
CreateBDtoValidator is not run (CreateADtoValidator   running) when my application service method like this:
```
 public virtual async Task<ResultDto> CreateAAsync(CreateADto input)
{
   var a= ObjectMapper.Map<CreateADto, A>(input);
    await _serRepository.InsertAsync(a);
    return new ResultDto();
}

```

What should I do?Please help me

**Comment by maliming** [comment]
This has nothing to do with abp, please refer to or ask for help in https://fluentvalidation.net/.

**Comment by hexianggui** [comment]
THKS

**Comment by hexianggui** [comment]
I have found the help document  https://docs.fluentvalidation.net/en/latest/start.html#chaining-validators
THKS
