### ISSUE TITLE
Upgrade samples to v3.0

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#4480]

**Comment by liangshiw** [comment]
https://github.com/abpframework/abp/pull/4443

https://github.com/abpframework/abp-samples/blob/221ae408b8c5eaffaeef0123b70a876c16f481d9/aspnet-core/Authentication-Customization/src/Acme.BookStore.Web/BookStoreWebModule.cs#L82

We should update the code in the example to keep it consistent with the documentation

**Comment by maliming** [comment]
Find a way to try to use automation to recreate or add new migrations.

We can create a json file under the project. It stores the migration information of the current project, some projects may need to be deleted and re-created migration, some projects need to add migration.

Then automatically deal with these cumbersome things.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/3907
