### ISSUE TITLE
Create Volo.Abp.Caching.StackExchangeRedis package

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4483]
This packages will;

- Call `services.AddStackExchangeRedisCache()` and configure it using the `IConfiguration["Redis:Configuration"]`. So, depending on this module will make the configuration easier.
- Extend the Redis cache by allowing to set/get multiple cache items in one call. See https://github.com/abpframework/abp/issues/4489

**Comment by danghung-dev** [comment]
I will setup redis for our project. I use abp.io commercial. 
I don't know how to config redis use Volo.Abp.Caching.StackExchangeRedis package above.
Can you share sample code? Which file should I modify?
Thank you

**Comment by maliming** [comment]
hi @danghung-dev 

`AbpCachingStackExchangeRedisModule `will try to read the configuration of redis.

https://github.com/abpframework/abp/blob/82baa238d448919909d00a96c92db4981a091463/framework/src/Volo.Abp.Caching.StackExchangeRedis/Volo/Abp/Caching/StackExchangeRedis/AbpCachingStackExchangeRedisModule.cs#L18-L25

https://github.com/abpframework/abp/blob/fd4efb6daf612398074c3e5f9b2f5b4ade0ba698/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.IdentityServer/appsettings.json#L9-L11
