### ISSUE TITLE
How to manage authentication on angular project for customized login pages

### ISSUE THREAD

**Issue by hassona-kun** [abpframework/abp#4484]
I have an issue with replaced component of login screen. after i send the API request it response with success. but when i call OAuthService.getAccessToken(). it comes always as null. how do i authenticate my angular client to make secure API calls?.

my issue is almost same as the below link
https://stackoverflow.com/questions/62191905/how-do-i-authenticate-when-calling-an-abp-io-application-rest-endpoint

**Comment by mehmet-erim** [comment]
Hi @hassona-kun,

Can you share a code example with us?

**Comment by hassona-kun** [comment]
Hi @mehmet-erim 
This is the component code i'm binding this function on button click

`Login() {

    if (this._form.invalid) {

      console.log('invalid');
      return;
    }

    this._loginModel = new LoginModel();

    this._loginModel.userNameOrEmailAddress = this._form.controls['userName'].value;
    this._loginModel.password = this._form.controls['password'].value;
    this._loginModel.rememberMe = this._form.controls['remeberMe'].value;

    this._loginService.doLogin(this._loginModel).subscribe((result) => {

      switch (result.result) {

        case LoginResultType.Success:
          debugger;
          console.log(this._oAuthService.getAccessToken());
          break;
        case LoginResultType.InvalidUserNameOrPassword:
          break;
      }
    })
  }
`

and this is the logic of the doLogin function on LoginService.

`    doLogin(LoginModel: LoginModel): Observable<AbpLoginResult> {

        return this.restService.request<LoginModel, AbpLoginResult>({
            method: 'POST',
            url: '/api/account/login',
            body: LoginModel
        },{ apiName: 'AbpLogin' });

    }`

**Comment by mehmet-erim** [comment]
You should call the `login` method of OAuthService like this:

https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/account/src/lib/components/login/login.component.ts#L54

Then, you can get the access token.

**Comment by mehmet-erim** [comment]
Assuming your problem is solved, I closed the issue. If you have still a problem feel free to open the issue.
