### ISSUE TITLE
User security log feature.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#4492]
I plan to implement the `IUserSecurityLog `feature in `Volo.Abp.Security`. Similar to the audit log.

It has an interface (`IUserSecurityLogStore`) + default implementation class + `UserSecurityLogInfo` model class.

User security logs can be written in any layer in any module, such as` login success/failure, logout. Change password. Modify email, get refresh_token` and any security logs that need to be recorded.

After that,Implemented EF/MongoDB storage in the Identity module.

```cs
public interface IUserSecurityLogStore
{
	Task SaveAsync(UserSecurityLogInfo userSecurityLogInfo);
}

[Serializable]
public class UserSecurityLogInfo : IHasExtraProperties
{
	/// <summary>
	/// The name of the application or service writing user security logs.
	/// Default: null.
	/// </summary>
	public string ApplicationName { get; set; }

	/// <summary>
	/// Web, JWT, Identity, Identity_Server
	/// </summary>
	public string Identity { get; set; }

	/// <summary>
	/// login_successful, login_failed, logout, change_pwd, refresh_token...
	/// </summary>
	public string Action { get; set; }

	public Dictionary<string, object> ExtraProperties { get; }

	public Guid? UserId { get; set; }

	public string UserName { get; set; }

	public Guid? TenantId { get; set; }

	public string TenantName { get; set; }

	public string ClientId { get; set; }

	public string ClientName { get; set; }

	public string CorrelationId { get; set; }

	public string ClientIpAddress { get; set; }

	public string BrowserInfo { get; set; }

	public DateTime CreationTime { get; set; }

	public UserSecurityLogInfo()
	{
		ExtraProperties = new Dictionary<string, object>();
	}
}
```

**Comment by olicooper** [comment]
So would this be similar to `AbpUserLoginAttempts` the in the old framework except it is more generic? And would it log user login/registration attempts as default? https://github.com/abpframework/abp/issues/2813

**Comment by maliming** [comment]
Yes.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/4675
