### ISSUE TITLE
how to determine current tenant in the distributedEventBus

### ISSUE THREAD

**Issue by fenggaoyao** [abpframework/abp#4508]
1. IDistributedEventHandler is different from mvc, it does not go through middleware, such as `.UseMiddleware<MultiTenancyMiddleware>`. So the DbContext uses the current host ,
, Such as BlogUserSynchronizer in the Volo.Blogging module, it can only handle the host,
If you need to handle tenant,do we need to add `_currentTenant.Change(**)`,like this
```C#
  public async Task HandleEventAsync(EntityUpdatedEto<UserEto> eventData)
        {
            using (_currentTenant.Change(eventData.Entity.TenantId))
            {
                var user = await UserRepository.FindAsync(eventData.Entity.Id);
                if (user == null)
                {
                    user = await UserLookupService.FindByIdAsync(eventData.Entity.Id);
                    if (user == null)
                    {
                        return;
                    }
                }
                if (user.Update(eventData.Entity))
                {
                    await UserRepository.UpdateAsync(user);
                }
            }          
        }
```
2. Volo.Abp.Domain.Entities.Events.Distributed.EntityEto, it does not include tenantId, do we noed to add tenantId?

**Comment by maliming** [comment]
The entity's **TenantId** may be different from the current **TenantId**.
  We can consider providing **TenantId** in the event. Developers can also customize this **TenantId**.

**Comment by hikalkan** [comment]
1. You're definitely right. We should store TenantId in the event data and switch to the tenant in the event handler. We can consider to handle it in the framework side (like if the ETO implements IMultiTenant, we can switch to the tenant before calling the handleevent method).
2. I don't think so, because not all entities are multi-tenant. If your entity is multi-tenant, then implement IMultiTenant for the ETO.

**Comment by fenggaoyao** [comment]
thanks
1、EntityUpdatedEto<UserEto>, as the main synchronization example of distributedEventBus in the framework.but it is hard to use.UserEto should implements IMultiTenant.And when an update IdentityUser, more than 6 times events handle  action will be triggered，and Each Messages is different。I think it Caused by  [IdentityRoleStore] AutoSaveChanges。It should be as UnitofWork, Can it be Changed to false？
(https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityRoleStore.cs)
```C#
        public bool AutoSaveChanges { get; set; } = true;
```
2、Volo.Abp.Domain.Entities.Events.Distributed.EntityEto, as a general Eto, it has extensible Properties. If  If your entity is multi-tenant. can add to this in the framework 
[EntityToEtoMapper](https://github.com/abpframework/abp/blob/bda2f4184ee5138b54687f40944289836df53e51/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/Distributed/EntityToEtoMapper.cs). 
```C#
public object Map(object entityObj)
        {
            ......
            var etoMappingItem = Options.EtoMappings.GetOrDefault(entityType);
            if (etoMappingItem == null)
            {
                var keys = entity.GetKeys().JoinAsString(",");
                var eto = new EntityEto(entityType.FullName, keys);
                 // add this
                if (entityObj is IMultiTenant multitenantEntity)
                {
                    eto.Properties.Add("tenantid",multitenantEntity.TenantId);
                }
                return eto;
            }  
          ....         
        }
```

**Comment by gdlcf88** [comment]
It will be a big change. I always inject the `ICurrentTenant` and change the current tenant to `MyOwnEto.TenantId`.

**Comment by hikalkan** [comment]
1 was done with https://github.com/abpframework/abp/issues/4433
I didn't like the solution 2. Simply implement IMultiTenant for the ETO. For generic ETOs (like `EntityUpdatedEto<T>`) the framework can also check the T.

**Comment by gdlcf88** [comment]
> For generic ETOs (like EntityUpdatedEto<T>) the framework can also check the T.

Does it mean that If MyEto class implements `IMultiTenant`, the `IDistributedEventHandler<EntityUpdatedEto<MyEto>>` will automatically change the current tenant Id to `MyEto.TenantId`?

**Comment by hikalkan** [comment]
>Does it mean that If MyEto class implements IMultiTenant, the IDistributedEventHandler<EntityUpdatedEto<MyEto>> will automatically change the current tenant Id to MyEto.TenantId?

Yes, I mean that.

**Comment by hikalkan** [comment]
@maliming can you work on that:

>If the ETO implements IMultiTenant, we can switch to the tenant before calling the handleevent method.

Also consider this scenario:

>Does it mean that If MyEto class implements IMultiTenant, the IDistributedEventHandler<EntityUpdatedEto> will automatically change the current tenant Id to MyEto.TenantId
