### ISSUE TITLE
MyProjectNameMenus.Prefix property needs to be used externally

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4512]
Hi @ebicoglu, I saw the commit https://github.com/abpframework/abp/commit/76f9e65ad08566ce2bee61238297c7ad065e3c8f

Sometimes I need to use the `Prefix` as the name of the parent menu item, for example:
```
├── MyModuleName (the Prefix)
│   └── MyModuleName.Product
│   └── MyModuleName.Order
```

Could you please change `private const string Prefix = "MyProjectName";` to `public const string Prefix = "MyProjectName";`?

**Comment by hikalkan** [comment]
This is just the startup template (and not a reusable/upgradeable code), so change it in your project if you need it. I agree to make it private until it is needed to make it public in the application.
