### ISSUE TITLE
Add abp.currentUser.roles as a string array in the client side

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4517]
It should not be null, but it can be empty if user has not logged it or has no role.

- [x] Server side & MVC UI - @maliming 
- [x] CurrentUser interface in the Angular UI - @mehmet-erim

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/4519
```js
> abp.currentUser.roles
> ["admin"]

> abp.currentUser.roles
> []
```
