### ISSUE TITLE
ListService implementation

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#4518]
Hello,

I've been following [docs](https://docs.abp.io/en/abp/latest/UI/Angular/List-Service#getting-started) to refactory some pages (that I built using abp v. 2.2 or so) to use abp-table and ListService, but I've noticed it hasn't been destroying the state of ListService. I've also tried to force OnDestroy() { this.list.OnDestroy() } but without success. Hope you can help!

* v2.9.0
* Angular

I can reproduce the problem by going to another page and coming back, the state is being kept, like the page and sorting, and it is subscribing to yet another query.
Example of implementation:

![image](https://user-images.githubusercontent.com/6138475/85958442-edc56f80-b96b-11ea-88b5-6df290191038.png)
![image](https://user-images.githubusercontent.com/6138475/85958227-5c093280-b96a-11ea-9443-92a570a9c960.png)

Problem:
![image](https://user-images.githubusercontent.com/6138475/85958394-a0e19900-b96b-11ea-83b4-51930a8c862e.png)

**Comment by mehmet-erim** [comment]
Hi @thiag0coelho

- Do you provide the ListService from any module? ListService should be provided only component level.

- You should call the `get` method only one time (ngOnInit is good choice). Would you like to refresh the table value, you should call below:

```ts
this.list.get();
```

**Comment by thiag0coelho** [comment]
I had ListService provided on SharedModule, removed it from module and provided on each component list.
Issue solved! Thanks!
