### ISSUE TITLE
Blog Enhancements

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#452]
- [x] show the -new message box- even to the unauthenticated users. 
- [x] after the post back of a new message, scroll down to the message.
- [x] put a `Cancel` button to be able to cancel an already opened reply box.
- [x] localize `ReplyTo` to `Reply to`
- [x] better locate the -new message box- to the bottom of messages.
- [x] add total comments count.
- [x] Place Create A New Post button on index page.

![image](https://user-images.githubusercontent.com/9526587/46129371-1b353480-c23f-11e8-9fe7-768f8d5fbe77.png)

![image](https://user-images.githubusercontent.com/9526587/46129415-46b81f00-c23f-11e8-8d5e-0e83583b7f67.png)

**Comment by yekalkan** [comment]
3 tanesini yaptım. kalanlarda da:

> - show the -new message box- even to the unauthenticated users.
> - add total comments count.

bunları nasıl ve ne görünüşte yerleştireceğimi bilmiyorum.

> - better locate the -new message box- to the bottom of messages.

Blog'u yaparken bunu tartışmış, üstte olmasına karar vermiştik. yeniden değerlendirebiliriz
