### ISSUE TITLE
How to get role name(s) in IdentityUser or AppUser

### ISSUE THREAD

**Issue by kaank** [abpframework/abp#4520]
Hi,

We're using latest abp fw , needs role name(s) in IdentityUser. We can override CreateFilteredQuery and change repository include, but it doesnt include role name.

How to get role name of user?

Regards,
Kaan

**Comment by kaank** [comment]
@hikalkan merhaba hocam konuyu değerlendirebilir misiniz?

**Comment by liangshiw** [comment]
Hi,
Please see :
https://github.com/abpframework/abp/blob/8371b74839be57c955d7b6199d1ee10422e4cd26/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L53

**Comment by kaank** [comment]
> Hi,
> Please see :
> https://github.com/abpframework/abp/blob/8371b74839be57c955d7b6199d1ee10422e4cd26/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L53

Hi, Thanks for reply.
We needs get role name of user in user get list request.

**Comment by liangshiw** [comment]
Hi,
1. You can write your own appservice to do this
2. You can override the `IdentityUserAppService` service method and use [object extend system](https://docs.abp.io/en/abp/latest/Object-Extensions) to extend `IdentityUserDto` dto. like this:

```csharp
//pseudo code
public override async Task<PagedResultDto<IdentityUserDto>> GetListAsync(GetIdentityUsersInput input)
{
    var count = await UserRepository.GetCountAsync(input.Filter);
    var list = await UserRepository.GetListAsync(input.Sorting, input.MaxResultCount, input.SkipCount, input.Filter);

    var result = new PagedResultDto<IdentityUserDto>(
        count,
        ObjectMapper.Map<List<IdentityUser>, List<IdentityUserDto>>(list)
    );

    foreach (var identityUserDto in result.Items)
    {
        var roleNames = await UserRepository.GetRoleNamesAsync(identityUserDto.Id);
        identityUserDto.SetProperty("RoleNames", roleNames.JoinAsString(","));
    }

    return result;
}
```

**Comment by xyfy** [comment]
`Volo.Abp.Identity.IdentityUser` has a navigation property `Roles` , can you use `DbSet.Include` when you needed in `UserManager` or `Repository`?

and `IdentityUserDto` like #4519

**Comment by hikalkan** [comment]
@kaank can you create another service endpoint that has all the information you need? You don't have to reuse the existing endpoints.
