### ISSUE TITLE
ABP Chinese website

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#453]
We plan to establish the ABP Chinese website. 
It is easier for Chinese developers to learn and use the abp framework.

The initial idea is:
1. abp framework document translation.
2. abp framework FAQ and tutorial.
3. abp framework peripheral technology stack documentation / tutorial/
4. abp download template CDN acceleration.
5. abp framework project featured (personal/enterprise projects developed using abp)/
6. abp framework talent recruitment job search.

We welcome interested Chinese developers to join us.

https://cn.abp.io/

**Comment by liangshiw** [comment]
I'm in

**Comment by redheart47** [comment]
这个可以有，支持

**Comment by sfwjiao** [comment]
支持支持

**Comment by seamusic** [comment]
where is the Chinese website?

**Comment by maliming** [comment]
> where is the Chinese website?

Now we conceiving and preparing. everyone can discuss it.

**Comment by zLulus** [comment]
good job

**Comment by wakuflair** [comment]
I'm in.

算我一个。

**Comment by wadereye** [comment]
强烈支持

**Comment by HelloSeattle** [comment]
我也加入一个

**Comment by scanf123** [comment]
I guess I should be in.

**Comment by staneee** [comment]
It's a coincidence that we're doing this right now.This is a version of what we're currently doing:

https://www.52ABP.com

**Comment by maliming** [comment]
> It's a coincidence that we're doing this right now.This is a version of what we're currently doing:
> 
> https://www.52ABP.com

We want to make a website with the same style as abp.

**Comment by liangshiw** [comment]
This website should be updated synchronously with abp.io's website, just like angular.cn

**Comment by hikalkan** [comment]
Hi all,

Thank you @maliming for opening this topic. We will support this movement.

**Comment by viewtance** [comment]
+1, let me in.

**Comment by edison1105** [comment]
+1

**Comment by maliming** [comment]
Hi everyone.
We created the organization to start doing this, interested Chinese developers please contact us.

https://github.com/cnAbp/Home

**Comment by denghejing** [comment]
+1

**Comment by kelely** [comment]
+1

**Comment by DomoYao** [comment]
强烈支持，abp 关注学习已久，一直了解这里的发展，ABP vNext 独立化了。比之前ABP更容易理解。ABP随着功能增多，好像代码膨胀太多。这次重构感觉清晰很多,大力支持！

**Comment by hikalkan** [comment]
As the first step, @maliming created the ABP documentation in Chinese: https://github.com/abpframework/abp/blob/master/docs/zh-Hans/Index.md

**Comment by maliming** [comment]
Our organization [cnAbp](https://github.com/cnAbp)  is translating documents(Existing documents will be translated within one week).

If you are interested and free time, welcome to join us (currently we have 6 people).
We have a lot of meaningful things to do.

**Comment by maliming** [comment]
https://cn.abp.io/documents/abp/latest/Index
https://cn.abp.io/blog/abp/Abp-vNext-Announcement

Chinese documents and blogs are online!

**Comment by hikalkan** [comment]
Shall I close this? It has its own organization and the web site is online now.

**Comment by maliming** [comment]
I think it can be closed. If there are any comments or suggestions, we can move on to discuss here(https://github.com/cnAbp/Home).

**Comment by hikalkan** [comment]
Thanks @maliming

**Comment by mainxx** [comment]
真棒...+1

**Comment by Aprite** [comment]
感兴趣 但是没时间 996

**Comment by maliming** [comment]
Stay away from 996. 

I will update the new UI on the weekend.
