### ISSUE TITLE
How to configure a remote rabbitmq server?

### ISSUE THREAD

**Issue by townsendtan** [abpframework/abp#4535]
### Abp/Sample/Microservice
I downloaded the latest sample Microservice and run it on my desktop successfully. When I tried to connect to remote sqlserver, redis, RabbitMQ, I got an error of failed to connect RabbitMQ while starting AuthServer.Host.  Will you please tell me how to configure it in appsettings.json. ip address, port, username, password

**Comment by maliming** [comment]
Please check the official documentation

https://docs.abp.io/en/abp/latest/Distributed-Event-Bus-RabbitMQ-Integration

**Comment by hikalkan** [comment]
@townsendtan if you have a problem, please reopen.
