### ISSUE TITLE
Refactor the Bookstore tutorial without NGXS

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#4537]

**Comment by sarshogh** [comment]
Hi there, 

Is there any readon ngxs has been removed from New version of ABP v3.4 ?

**Comment by mehmet-erim** [comment]
Hi @sarshogh

If your component logic does not affect another component, you do not need to use the store. BookStore is a CRUD tutorial. The store is not required in this case. The BookStore tutorial was too complex. We made it a simple tutorial.

You can still use the store, there is not any problem to use the store. My suggestion is to you, follow the BookStore tutorial again and see what changes we made for Angular UI. Now the best guide is the BookStore tutorial.
