### ISSUE TITLE
ABP dynamic form adds default value to AbpInputTagHelper

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4548]
The first way:
```
    public class CreateEditProductViewModel
    {
        [DefaultValue("Default")]
        public string Name { get; set; }
    }
```
The second way:
```
    public class CreateEditProductViewModel
    {
        public string Name { get; set; } = "Default";
    }
```

I thought the **Name** input box to use the default value on the creation modal page, but not really, neither of the above two ways worked.

**Comment by hikalkan** [comment]
Can you share your full code class (you may need to create new `CreateEditProductViewModel` in the Get method)

**Comment by gdlcf88** [comment]
> (you may need to create new CreateEditProductViewModel in the Get method)

I think that's why the problem happened.

I try to create `CreateEditProductViewModel` manually, it works:
```csharp
    public class CreateEditProductViewModel
    {
        public string Name { get; set; } = "Default";
    }

    public class CreateModalModel : MyProjectPageModel
    {
        [BindProperty]
        public CreateEditProductViewModel ViewModel { get; set; } = new CreateEditProductViewModel(); // default value works.

        // .ctor

        public virtual Task OnGetAsync()
        {
            ViewModel = new CreateEditProductViewModel();  // default value works.
            
            return  Task.CompletedTask;
        }
    }
```

There are some questions:
* The document's [demo](https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=MVC#createmodal-cshtml-cs) does not create a new model, should it be updated?
* Should the default value works if the model is not assigned a value?
* Should the `DefaultValueAttribute` also be able to provide the default value?

**Comment by yekalkan** [comment]
Hi,

It seems like creating a new instance of the model in OnGet method is required. I couldn't find any other way to make it work with `Name { get; set; } = "Default";` usage.


>Should the default value works if the model is not assigned a value?

No. But it would be nice.

> Should the DefaultValueAttribute also be able to provide the default value?

It doesn't provide for default AspNet Core input tag helper.

> The document's demo does not create a new model, should it be updated?

It doesn't use any default value, so no need to initialize a new model in OnGetAsync.

**Comment by jonny-xhl** [comment]
> > (you may need to create new CreateEditProductViewModel in the Get method)
> 
> I think that's why the problem happened.
> 
> I try to create `CreateEditProductViewModel` manually, it works:
> 
> ```cs
>     public class CreateEditProductViewModel
>     {
>         public string Name { get; set; } = "Default";
>     }
> 
>     public class CreateModalModel : MyProjectPageModel
>     {
>         [BindProperty]
>         public CreateEditProductViewModel ViewModel { get; set; } = new CreateEditProductViewModel(); // this way works.
> 
>         // .ctor
> 
>         public virtual Task OnGetAsync()
>         {
>             ViewModel = new CreateEditProductViewModel();  // or this way.
>             
>             return  Task.CompletedTask;
>         }
>     }
> ```
> 
> There are some questions:
> 
> * The document's [demo](https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=MVC#createmodal-cshtml-cs) does not create a new model, should it be updated?
> * Should the default value works if the model is not assigned a value?
> * Should the `DefaultValueAttribute` also be able to provide the default value?

So you need to initialize instances?
