### ISSUE TITLE
Authorization issue : Web vs API

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#4556]
### Issue

I have a 3 tier application with:
- Web app
- API server
- Identity Server

Each one lives separately... different versions etc.

Currently, I have a problem, it seems that the authentication is not "synchronized" between the API and the Web App.

I join a small image, it shows a test page that displays the authorization status:
- We see that the Web app is well connected
- But when calling the API it got an "unauthorized" exception

So, from my understanding, the Webapp uses cookies... so the user remains authenticated.
But on the API side, it seems the current user is no more authorized to access?

- Why?
- How can I solve this? Maybe we need something to "reconnect" and re-authorize in such case ?

Noticed it is a CRITICAL issue because none of the customers we have been able to use the app for now!

![image](https://user-images.githubusercontent.com/17200971/86219596-be3c8000-bb82-11ea-9f3d-12d784f18487.png)

**Comment by xyfy** [comment]
I got some exception as well ,when I used a cookie wich is expired  ,it can not detected it .it will caught err 500  ,  I need manually clear cookie in webbrowser  to continue.

**Comment by xyfy** [comment]
or I　pass  a expired jwt token to `microservice `, it checked it was not authorized ,  the fronted will send a err 500  but not err 401

**Comment by vd3d** [comment]
Thanks,

But here none of the token has expired, their expiration year is 2022 ;-)
Here is seems to be a different situation !

Anyway it is not possible to ask peoples to clear their cookies... we have to handle theses cases ourself, but how ? No idea :-(

**Comment by vd3d** [comment]
Hi,

Does someone has an idea that can help ? Really, I cannot fix this issue in production :-(

**Comment by xyfy** [comment]
if you call the api ,you should pass the jwt token

**Comment by xyfy** [comment]
or named accesstoken

**Comment by xyfy** [comment]
the WebApi is Stateless
