### ISSUE TITLE
Could not view  any entity in table although the entity is in database in BookStore-Angular-MongoDb sample 

### ISSUE THREAD

**Issue by AkinSabriCam** [abpframework/abp#4569]
@hikalkan

I tried to add a book entity to database and could not see the entity in ui after this process.

- I created a book  via create modal in ui.
![BookStoreAngularCreate](https://user-images.githubusercontent.com/37196959/86293642-ba007900-bbfb-11ea-9d69-3186b9701b09.PNG)

- The book entity is saved in mongo database
![BookStoreAngularMongoDb](https://user-images.githubusercontent.com/37196959/86293692-d3092a00-bbfb-11ea-8b2b-ade3bf59c722.PNG)

- I can not see the entity in ui and see an expection.
![BookStoreAngularUıError](https://user-images.githubusercontent.com/37196959/86293800-02b83200-bbfc-11ea-9d50-b5dbfc758752.PNG)

**Comment by maliming** [comment]
What is the specific error message?

**Comment by AkinSabriCam** [comment]
- the error log screen shot
![mongoError](https://user-images.githubusercontent.com/37196959/86323645-e4772400-bc45-11ea-8958-d0c793bab66e.PNG)

- you can check the log file.
[logs.txt](https://github.com/abpframework/abp/files/4862361/logs.txt)
