### ISSUE TITLE
There is a problem in Account/Login razor page in the Authentication-Customization sample

### ISSUE THREAD

**Issue by AkinSabriCam** [abpframework/abp#4571]
There is a problem in razor page in Authentication-Customization sample. 
See the example .

![accountpage](https://user-images.githubusercontent.com/37196959/86296015-7eb47900-bc00-11ea-94a3-c9b88cb4ec78.PNG)

**Comment by gterdem** [comment]
Fixed via https://github.com/abpframework/abp-samples/commit/2afdba13da2e80ae47ccb0adb40509ac98e1bec0.
