### ISSUE TITLE
How do I hide the default exposed APIs ?

### ISSUE THREAD

**Issue by anaya-upadhyay** [abpframework/abp#4581]
I don't require the default APIs ABP exposes, for one of my project. **How can I hide or not expose these APIs?**

The snapshot below shows some the APIs that I need to hide.

![image](https://user-images.githubusercontent.com/16795691/86346664-fcb66580-bc7c-11ea-980a-46f46dfd8bc9.png)

The project is created using abp.io with Angular as the frontend.

**Comment by liangshiw** [comment]
See https://support.abp.io/QA/Questions/264/How-to-hide-an-endpoint-from-Swagger

**Comment by anaya-upadhyay** [comment]
Thanks @liangshiw 
But I don't meant to hide these APIs from the Swagger only. Instead, I don't want to be able to expose these APIs via Postman or Browser also.

**Comment by liangshiw** [comment]
See https://support.abp.io/QA/Questions/255/We-don%27t-want-to-use-the-Organization-Unit-functionality-and-want-to-remove-it-from-the-UIAPI#answer-e417f04d-4fe3-c8d1-e36a-39f5f89805ef

**Comment by anaya-upadhyay** [comment]
Hi @liangshiw ,
I did the as the link referred to. But I am still seeing those APIs in Swagger.

Is there anything more to do?

**Comment by liangshiw** [comment]
It works.

![image](https://user-images.githubusercontent.com/16813853/86350149-d7355600-bc94-11ea-8cf9-2cec72b7fda0.png)

**Comment by anaya-upadhyay** [comment]
Thanks @liangshiw ,

I wrote the wrong Controller Name. Thanks again for all the help. :)
