### ISSUE TITLE
Identity Module Information(how it will connect with login part in angular (/connect/token) )

### ISSUE THREAD

**Issue by HiteshAnshani** [abpframework/abp#4586]
Hello Team,

We are trying to explore the ABP framework from last 15-20 days but unable to identify where the
Identity server is Plugged and how it is working.

Identity server 4 is understood how it works but, how it is working in ABP that's the big question we have.

Let's say when we are trying to login from angular app
it will retrieve the token from **/connect/token**
so we know identity server is used but,

**where it is plugged?
how is the process?
where the username and password are checked?
how to debug the process(in this case which modules we need to attach to perform the debug)?
and what will be the hierarchy(we have checked the dependency of each project but unable to figure out)?**

Or if this happens in modules, we would like to know the **name** or **location**

we need to create our Own Application using ABP framework so before starting the project
we wanted to understand each and everything properly.

It would be great if you please guide us.

I would appreciate it a lot.

**Comment by liangshiw** [comment]
It has nothing to do with ABP. If you know IdentityServer4, you should know how it works. ABP just integrates it.

However , ABP [implements](https://github.com/abpframework/abp/blob/dev/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AspNetIdentity/AbpResourceOwnerPasswordValidator.cs) the IResourceOwnerPasswordValidator interface. Identityserver4 will [use it](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Endpoints/TokenEndpoint.cs#L88).
