### ISSUE TITLE
CLI generate-proxy: On Turkish Language settings computers, property names starting with 'I' letter is made lower case as turkish 'ı' letter

### ISSUE THREAD

**Issue by HakanBayrak** [abpframework/abp#4589]
When we generate proxy on a Turkish language setting computer with CLI; file names first letter and property names first letter which is starting with 'I' letter becomes Turkish 'ı' letter (i without a dot on top). This makes no problem for filenames. Also property names starting with 'ı' is not a problem on typescript component.ts files, but they can not be used in html template files.
Also Enum types or navigation properties, as you see at below example, imported correctly but property is referred as 'any' (For this, a new issue may be required?).
And also nullable enum types converted fully incorrect. they can not be compiled.

This is the dto definition:

```
public class IletisimPersonelDto : FullAuditedEntityDto
    {
        public Guid PersonelKimlikId { get; set; }

        public IletisimReferansi IletisimReferansi { get; set; }

        public string TelefonEv { get; set; }

        public string TelefonIs { get; set; }

        public string TelefonCep { get; set; }

        public string EPosta { get; set; }
    }
```

and it is converted as "ıletisim-personel-dto.ts" file name (name starts with 'ı')
Content: 
```
import { IletisimReferansi } from './ıletisim-referansi';

import { FullAuditedEntityDto } from '@abp/ng.core';

export class IletisimPersonelDto extends FullAuditedEntityDto {
  personelKimlikId: string;
  ıletisimReferansi: any;
  telefonEv: string;
  telefonIs: string;
  telefonCep: string;
  ePosta: string;
  ısDeleted: boolean;
  deleterId?: string;
  deletionTime?: string;
  lastModificationTime?: string;
  lastModifierId?: string;
  creationTime: string;
  creatorId?: string;

  constructor(initialValues: Partial<IletisimPersonelDto> = {}) {
    super(initialValues);
  }
}
```

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/ffe6360b70e354b107b4fda3507ba3f042e23e4e/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/GenerateProxyCommand.cs#L797-L810
```cs
public static class StringExtensions
{
	public static string PascalToKebabCase(this string value)
	{
		if (string.IsNullOrEmpty(value))
		{
			return value;
		}

		using (CultureHelper.Use(CultureInfo.InvariantCulture))
		{
			if (string.IsNullOrEmpty(value))
			{
				return value;
			}

			return Regex.Replace(
				value,
				"(?<!^)([A-Z][a-z]|(?<=[a-z])[A-Z])",
				"-$1",
				RegexOptions.Compiled)
				.Trim()
				.ToLower();
		}
	}
}
```

**Comment by maliming** [comment]
Fixed by https://github.com/abpframework/abp/pull/4602
