### ISSUE TITLE
DynamicHttpProxyInterceptor mask real StatusCode

### ISSUE THREAD

**Issue by MatthieuTruchet** [abpframework/abp#4590]
Hi,

We use currently Abp Framework in version 2.8.0 and tiered architecture (Back-end server does not exposed over internet, Front-end server exposed over internet and an Angular client).

The http status code from the back-end application is ok but when we call the api through the Front-end all http status code is 500.

After analyzing, it's due to the DynamicHttpProxyInterceptor and more exactly here:
```
private async Task ThrowExceptionForResponseAsync(HttpResponseMessage response)
{
    if (response.Headers.Contains(AbpHttpConsts.AbpErrorFormat))
    {
        var errorResponse = JsonSerializer.Deserialize<RemoteServiceErrorResponse>(
            await response.Content.ReadAsStringAsync()
        );

        throw new AbpRemoteCallException(errorResponse.Error);
    }

    throw new AbpException($"Remote service returns error! HttpStatusCode: {response.StatusCode}, ReasonPhrase: {response.ReasonPhrase}");
}
```

All not success calls are wrap in AbpRemoteCallException and the AbpExceptionFilter formats them with an http status 500.

Is it possible to save HttpStatusCode in the AbpRemoteCallException at least and use the Status in AbpExceptionFilter for AbpRemoteCallException?
Or any other solution to keep the original StatusCode.

I think my issue is related to this PR : #4572

**Comment by hikalkan** [comment]
I am not so sure about that. Think that you called an X method of a service A (and you have permission to do it), then the service A calls a Y method of a service B which returns 403 (forbidden). Should A.X return 403 too?
I believe there is a design error here which can not be resolved unless you fix the code (because the client has necessary permission). So, it should be considered as an internal server error (500).

For this scenario, I consider the service A is the client of the service B. If service B returns a client error (4xx), we can not turn this client error to the original client of the service A, because it didn't make any mistake that it can fix.

I am adding this to backlog as a high priority item, but we should discuss it more. What do you think?

**Comment by xyfy** [comment]
I am using the `microservice` sample 

the publichost call api use abp.ajax  ,which call DynamicHttpProxyInterceptor  auto ,use the publicSite.Host  base url  ,not gateway url

After I publish  a new identityServer in  docker,I visit the page,which call a service behind gateway using abp.ajax, it will get a 500 exception ,the remote service say the user has not login.      

I can only use browser tool to clear the local cookie,or logout&re-login ,then the page is display correctly.  it is very poor user experience

if the `DynamicHttpProxyInterceptor ` do not return 401,How can I avoid this happening

Ｉam not sure how the `publicSite.Host  ` pass `the current user info` to `gateway` or  the `module service`

**Comment by MatthieuTruchet** [comment]
@hikalkan I'm agree with your scenario. The service A should return a 500 when a remote service fails with the original error message in body.

But in the context of the DynamicProxy, I don’t have a controller to add Authorization or Validation or Business controls. I just use the service A as a proxy for my service B who are in charge to do all validation and business controls.
But all the logic doing by Abp to auto mapping AbpValidationException or BusinessException to http status code are lost or hidden by a global 500.

If I am doing what you said, I must write on my public Host a controller for each backend controller. Do manually the call to the remote service, handle the response and throw the right exception. In other words, doing the job of the DynamicProxy no? The DynamicProxy it's a good time saving and maintenance in my scenario.

Perhaps, it's a configuration option to the DynamicProxy to throw a 500 like now, or throw the original http status?

**Comment by hikalkan** [comment]
Thank you guys for extra use case explanations. I accept the situations. I will try to work on this in the next milestone.

**Comment by MatthieuTruchet** [comment]
Hi,

Do you have any news on this subject ?
