### ISSUE TITLE
ABP CLI should edit the text "MY_PROJECT_NAME" (snake case & upper case) when generating a new project

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#4592]
CLI can't convert `MY_PROJECT_NAME` (snake & upper case) while a new project generating. 
We are using this constant in Angular UI module template

![image](https://user-images.githubusercontent.com/6908465/86548844-70ec5400-bf70-11ea-88d3-1993bad2d2ea.png)

**Comment by maliming** [comment]
It could be: `BOOKSTORE_ROUTE_PROVIDERS` `ISSUEMANAGEMENT_ROUTE_PROVIDERS` is this OK?
