### ISSUE TITLE
Add GetPagedList & GetPagedListAsync methods to the repository

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4593]
This reduces the need to create custom repositories for paging where we don't need to filtering.

We can add it to the `IReadOnlyBasicRepository<TEntity>`, so it inherently will be available on the derived repo interfaces

````csharp
        Task<List<TEntity>> GetPagedListAsync(
            int skipCount,
            int maxResultCount,
            string sorting,
            bool includeDetails = false,
            CancellationToken cancellationToken = default);
````

**Comment by liangshiw** [comment]
I think only `GetPagedListAsync` method should be add. We did not add any synchronization method to the repository.
