### ISSUE TITLE
ABP CLI command: update does not run yarn (or npm i)

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4598]
@yekalkan This problem is related to the commit: https://github.com/abpframework/abp/commit/d8a8d0f1e45548341093d2014f386076e8da6c49#diff-e057c9d8e81acf62fac9f55ea6980e05R75-R79

https://github.com/abpframework/abp/blob/40efc0aa4711aaf9a74361dde9e181588a46f39c/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectModification/NpmPackagesUpdater.cs#L70-L79

https://github.com/abpframework/abp/blob/a78702de4061087f682ff142fa3864536aa2663a/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/UpdateCommand.cs#L49-L52

`RunYarn()` and `RunNpmInstall()` will never be executed, because `includePreviews` and `switchToStable` is always `false`.

This is my logs:

```
[22:57:49 INF] Checking installed npm global packages...
[22:57:58 INF] Updated @abp/aspnetcore.mvc.ui.theme.basic to ~3.0.1 in \sample\MyProject\aspnet-core\src\MyProject.Web\package.json.
[22:57:59 INF] Running Gulp on D:\Projects\EasyAbp\EasyAbp.GiftCardManagement\sample\MyProject\aspnet-core\src\MyProject.Web\
[[90m22:58:04[39m] Using gulpfile D:\Projects\EasyAbp\EasyAbp.GiftCardManagement\sample\MyProject\aspnet-core\src\MyProject.Web\gulpfile.js
[[90m22:58:04[39m] Starting 'default'...
[[90m22:58:07[39m] Finished 'default' after 3.58 s
```

**Comment by yekalkan** [comment]
I've fixed. Thanks for informing.
