### ISSUE TITLE
The date selection box does not work properly on Firefox

### ISSUE THREAD

**Issue by EricChenZW** [abpframework/abp#4601]
The date selection box does not work properly on Firefox.

ABP Framework version: 3.0.1
User Interface type: MVC
Exception message and **stack trace** if available (check the logs): None.
Steps: Open a window with date in Firefox.

**Comment by cotur** [comment]
Hi @EricChenZW, 

I don't see any problem with datapickers, and we use [bootstrap date picker](https://www.npmjs.com/package/bootstrap-datepicker) package for them.

There is an example usage https://github.com/abpframework/abp/issues/4529#issuecomment-651792366 so you can check it, I use Firefox and I don't have any problem.

**Comment by EricChenZW** [comment]
![2020-07-04_014535](https://user-images.githubusercontent.com/37535753/86489899-46e03980-bd98-11ea-8ace-2e14ad4d39ec.png)

Hi，

The problem is shown in the picture, I cannot enter the date by clicking on the plugin. I will check if there is a problem with my code, if it is my problem, I will close this issue.

Thanks for your reply

**Comment by EricChenZW** [comment]
![image](https://user-images.githubusercontent.com/37535753/86710517-a3b84a00-c04d-11ea-8d44-9de2c3bd1996.png)

Hi,
This is a picture of datapickers in Google. I can't use it in Firefox like in Google. I don't know if it is my operation problem? I need help.

Thanks.

**Comment by maliming** [comment]
You can create a `bootstrap-datepicker` example that does not use the abp framework. If firefox still has the same problem, you should seek help in https://github.com/uxsolutions/bootstrap-datepicker.

**Comment by EricChenZW** [comment]
It should be a problem with bootstrap-datepicker.
Close this  issue.
