### ISSUE TITLE
Add a separate logo for the tenant

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#4604]
Add a separate logo for the tenant

**Comment by hikalkan** [comment]
Override the `DefaultBrandingProvider` ([see](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/Components/DefaultBrandingProvider.cs)) to dynamically determine the logo for the current tenant.
