### ISSUE TITLE
abp generate-proxyy must specify -module parameter

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#4605]
in [document](https://docs.abp.io/en/abp/latest/CLI#generate-proxy)
![image](https://user-images.githubusercontent.com/26211283/86427695-74d46800-bd1d-11ea-84f5-286808bb0145.png)
`Specifies the module name. Default module name is app.`
But in 3.0.0 version, there are no app module。so run error : **Module can not find!**

-- old   /api/abp/api-definition?IncludeTypes=true
![image](https://user-images.githubusercontent.com/26211283/86427856-e7ddde80-bd1d-11ea-819c-862b9737dca3.png)
-- new   /api/abp/api-definition?IncludeTypes=true
![image](https://user-images.githubusercontent.com/26211283/86427862-ee6c5600-bd1d-11ea-969f-01fa44eb4048.png)

**Comment by maliming** [comment]
I think you should implement your `app `module(`controller`).

**Comment by hikalkan** [comment]
Let me check this.

**Comment by hikalkan** [comment]
You should define a controller/service before using this tool. Otherwise, no meaning to run it.
