### ISSUE TITLE
#Extra property added for user.

### ISSUE THREAD

**Issue by pramodbobde** [abpframework/abp#4618]
**# Can anyone help me to add new new property for user please?
**# This framework is not even gives permission to add me a new fiield and show on UI.
**# CustomApplication module you have added two properties but these are not shown on UI even after adding.

**Comment by gdlcf88** [comment]
See https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities

**Comment by hikalkan** [comment]
>CustomApplication module you have added two properties but these are not shown on UI even after adding.

We added UI layer of the customization with the v3.1. So, when you add an extension poropery, it will appear on the UI too. See this document: https://docs.abp.io/en/commercial/latest/guides/module-entity-extensions We will move it to open source side after 3.1 release.
