### ISSUE TITLE
When click on login, 404 internal error occured

### ISSUE THREAD

**Issue by naveenkumart450s** [abpframework/abp#4621]
ABP Framework version - 5.9.0
User Interface type -  React native, 

we have used react-native-app-auth and try to connect using clientId,scopes with proper authority

When we try to click on login getting internal server error

![Screenshot (1664)](https://user-images.githubusercontent.com/48850690/86505519-4d47d300-bde3-11ea-8995-bed1f52a3add.png)

Not able to find the issue. 
Updated proper redirect urls, post logout urls, cors in identity tables

Could you please provide any document and help us in resolving login related issue from mobile react app

**Comment by mehmet-erim** [comment]
Hi @naveenkumart450s 

Have you looked at how we did this in React Native?

Login screen: https://github.com/abpframework/abp/blob/dev/templates/app/react-native/src/screens/Login/LoginScreen.js
API call function for login: https://github.com/abpframework/abp/blob/dev/templates/app/react-native/src/api/AccountAPI.js#L6

We have tried OAuth packages developed for React Native before. We saw the packages don't work. I suggest you that call the `/connect/token` API manually.

We'll improve the React Native documentation soon.
