### ISSUE TITLE
abp 3.x , AddRazorRuntimeCompilation , please remove ?

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#4627]
### Documentation

I've noticed that you have added AddRazorRuntimeCompilation() into :

framework\src\Volo.Abp.AspNetCore.Mvc\Volo\Abp\AspNetCore\Mvc\AbpAspNetCoreMvcModule.cs

But why ? you should use this only for debugging, right ?

The problem is that I don't see som error at compile time... but runtime... if I discover them !

**Comment by gdlcf88** [comment]
See https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities

**Comment by maliming** [comment]
We have changed the way to handle embedded `cshtml`
https://github.com/abpframework/abp/pull/4016
