### ISSUE TITLE
Add AutoMapper to the Application.Contracts package to allow to use AutoMap attributes on the DTOs

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4630]

**Comment by gdlcf88** [comment]
Hi @hikalkan, as far as I know, Contracts cannot use entity types in Domain, do you have any plans to create a document to show the usage?

**Comment by hikalkan** [comment]
Hmmm.. you are right for the entity to dto mapping. So, I didn't think carefully. I will remove it. Thank you for notifying it.
