### ISSUE TITLE
Try to set GUID Id in the InsertAsync method of the EF Core repository

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4631]
In this way, we don't need to wait until SaveChangesAsync if we use GUID Id but not set it before InsertAsync call.
It is currently like that for the MongoDbRepository.

Note: Apply the same logic inside the AbpDbContext.CheckAndSetId

**Comment by gdlcf88** [comment]
Greate! It ensures that the Ids of all new entities are generated by IGuidGenerator by default.

**Comment by dicksonkimeu** [comment]
This will be great. I had to write alot of code since this was missing. I.e to ensure uniqueness of records before saving to db etc
