### ISSUE TITLE
Suggestion on tenancy segregation

### ISSUE THREAD

**Issue by jiazhiliang** [abpframework/abp#4635]
Here's a usage scenario:

1. TenancyContributor will look to currentUser and prioritise the tenancy if found associated with currentUser.
2. However, while identityServer building, I need to specify tenancy (header, route, domain, etc.) in order to get user authenticated.

Can I let TenancyContributor find the tenancy in identityServer instead of specifying tenancy BEFORE user get authenticated?

Cheers.

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/latest/Multi-Tenancy#custom-tenant-resolvers

**Comment by hikalkan** [comment]
It is already like that @jiazhiliang: https://docs.abp.io/en/abp/latest/Multi-Tenancy#determining-current-tenant-from-web-request
