### ISSUE TITLE
Cannot access cache from distributed event handler

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#4641]
Version 3.0.2

I'm having an issue accessing the distributed cache from an event handler. Using Redis for caching and RabbitMQ for events. 

This is my event handler. The GetAsync method returns null. If I run it from a http request the object is returned from cache. Do I need so set a scope with tenant somehow?

```
public class FilterResponseEventHandler
            : IDistributedEventHandler<FilterResponseEto>,
              ITransientDependency
{
        private readonly IDistributedCache<FilterRequestCache, Guid> _distributedCache;

        public FilterResponseEventHandler(
            IDistributedCache<FilterRequestCache, Guid> distributedCache,
            IUnitOfWorkManager unitOfWorkManager
            ) {
            _distributedCache = distributedCache;
        }

        public async Task HandleEventAsync(FilterResponseEto response)
        {
            // Find the associated cache
            var cache = await _distributedCache.GetAsync(response.Id);
        }
}

```

**Comment by liangshiw** [comment]
* Steps needed to **reproduce** the problem.

**Comment by lukebooroo** [comment]
To reproduce, set the cache and post event:

```
    public class ContactAppService : ApplicationService
    {
        private readonly IDistributedEventBus _distributedEventBus;
        private readonly IDistributedCache<FilterRequestCache> _distributedCache;

        public ContactAppService(
            IDistributedEventBus distributedEventBus,
            IDistributedCache<FilterRequestCache> distributedCache)
        {
            _distributedEventBus = distributedEventBus;
            _distributedCache = distributedCache;
        }

        public async Task SetCache()
        {
            var cacheId = "CacheId";

            // Set the cahce
            await _distributedCache.SetAsync(cacheId, new FilterRequestCache
            {
            },
            new DistributedCacheEntryOptions
            {
                AbsoluteExpiration = DateTimeOffset.Now.AddHours(1)
            });

            // Publish event
            await _distributedEventBus.PublishAsync(new FilterResponseEto
            {
            });

        }
}

```

The cache in event handler will be null. 
```
    public class FilterResponseEventHandler
            : IDistributedEventHandler<FilterResponseEto>,
              ITransientDependency
    {
        private readonly IDistributedCache<FilterRequestCache> _distributedCache;

        public FilterResponseEventHandler(
            IDistributedCache<FilterRequestCache> distributedCache
            ) {
            _distributedCache = distributedCache;
        }

        public async Task HandleEventAsync(FilterResponseEto response)
        {
            var cacheId = "CacheId";

            // Get the cahce
            var cache = await _distributedCache.GetAsync(cacheId);
         }
}

```

**Comment by liangshiw** [comment]
I can't reproduce your problem.

![image](https://user-images.githubusercontent.com/16813853/86594801-3f07db80-bfca-11ea-90ab-786a16772534.png)

**Comment by lukebooroo** [comment]
Sorry for wasting your time. I didn't mention that I was using multi-tenancy. In the end I got it working by calling

` _currentTenant.Change(response.TenantId);`

**Comment by xyfy** [comment]
@lukebooroo @realLiangshiwei  Must mannual using pass the **TenantId**& change the **TenantId** in the event publish & handle??

**Comment by lukebooroo** [comment]
@xyfy when on receiving an event, there is no session so **TenantId** is unknown. There are two options, the event fired could supply the **TenantId** . Alternatively, if you're sure it won't create a vulnerability, you can disable the tenant filter.

```
using (_dataFilter.Disable<IMultiTenant>())
{
      return await _bookRepository.GetListAsync();
}
```

https://docs.abp.io/en/abp/latest/Data-Filtering#idatafilter-service-enable-disable-data-filters

**Comment by xyfy** [comment]
I inject the&nbsp; Icurrenttenant&nbsp; interface&nbsp; in the handle&nbsp; ,&nbsp; it&nbsp; has&nbsp; tenantid . but&nbsp; sometimes it had&nbsp; null&nbsp; value



---Original---

**Comment by lukebooroo** [comment]
@xyfy Injecting current tenant into the event handler will not work.

**Comment by xyfy** [comment]
but  it worked before I changed some thing ,it works well as a long time.


after I changed some depends on  ,it can not work. 


when I restore the changes ,it work.


So I am very confused，when and where the current tenant  will set the value?  


the event handler is a back-end worker? why it can work as well, before I changed some things?

**Comment by sofm13** [comment]
Yes, I have the same problem. just  currentTenant.Change can used
