### ISSUE TITLE
Feature Request - Windows Authentication path

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#465]
Many websites sit behind company firewalls and/or inside private networks where users are already authenticated by their Windows System (i'm using windows as an example for now).

There is an opportunity to cater to this scenario by providing a path in the code where the login screen does not appear.  The credentials are instead taken from the current Logged-in users principle.

I would like this feature or scenario to be considered if at all possible in the future.

Many thanks,

John

**Comment by acjh** [comment]
https://stackoverflow.com/questions/48820965/integrated-windows-authentication-in-abp-framework

Is that insufficient?

**Comment by 274188A** [comment]
Thanks for your consideration - I appreciate your time.  If the request is too much then I can certainly use the solution defined in your link. 
However, the point being, it is not a case of insufficient/sufficient.  More a case of not having the user have to re-enter their credentials.  That would have been really good to have.
Cheers
