### ISSUE TITLE
Migrations in a production environment

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#4653]
Seems after adding a new tenant to use a different connection string from host database,  migration must he done. The database migration project does this well, but in visual studio. 

In a production server where no visual studio installed how can this be done ?

**Comment by liangshiw** [comment]
You can publish the migration application and run in production server.

**Comment by jacmiller12** [comment]
Hi @liangshiw ,

Is it possible to create an endpoint/ApplicationService that will call the DB migration service?
If yes please let us know.

**Comment by liangshiw** [comment]
You can directly inject the `BookStoreDbMigrationService` service.

You should check `BookStore_App` client exists.
![image](https://user-images.githubusercontent.com/16813853/86741148-c0627b00-c069-11ea-96e9-98ffa0da663b.png)

**Comment by jacmiller12** [comment]
Hi @liangshiw 

I have updated Implementation but same error

**Can you please tell me where we need to check the client ID in the table or in code?**
Can you please guide me.

```
2020-07-07 13:43:44.716 +05:30 [INF] {"ClientId":"BookStore_App","Category":"Authentication","Name":"Client Authentication Failure","EventType":"Failure","Id":1011,"Message":"Unknown client","ActivityId":"800000c1-0001-fd00-b63f-84710c7967bb","TimeStamp":"2020-07-07T08:13:44.0000000Z","ProcessId":7592,"LocalIpAddress":"::1:44310","RemoteIpAddress":"::1","$type":"ClientAuthenticationFailureEvent"}
2020-07-07 13:43:44.716 +05:30 [ERR] No client with id 'BookStore_App' found. aborting
2020-07-07 13:43:44.723 +05:30 [INF] Request finished in 257.2557ms 400 application/json; charset=UTF-8
```


```
using Acme.BookStore.Data;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;

namespace Acme.BookStore
{
    public class CreateDbAppService : ApplicationService
    {
        private BookStoreDbMigrationService _BDS;
        public CreateDbAppService(BookStoreDbMigrationService BDS)
        {
            _BDS = BDS;
        }


        public async Task GetDb()
        {
            await _BDS.MigrateAsync();
        }
    }
}
```

**Comment by jacmiller12** [comment]
Hello @liangshiw ,
I have updated the implementation.
but **IdentityServerClients** table is empty there is no client available
but when I am running DB migrator project I am getting entry in **IdentityServerClients** table

_so which method I need to call in this service to seed the data?_

```
using Acme.BookStore.Data;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;

namespace Acme.BookStore
{
    public class CreateDbAppService : ApplicationService
    {
        private BookStoreDbMigrationService _BDS;
        public CreateDbAppService(BookStoreDbMigrationService BDS)
        {
            _BDS = BDS;
        }


        public async Task GetDb()
        {
            await _BDS.MigrateAsync();
        }
    }
}
```

**Comment by NecatiMeral** [comment]
We're deploying the `Host` and the `DbMigrator` for a microservice.
Our docker-compose contains both as services.

**Comment by dicksonkimeu** [comment]
I will try this, though it would be good to have this as a standard features for abp
