### ISSUE TITLE
Allow to call base DbContext.SaveChangesAsync() from the application's DbContext

### ISSUE THREAD

**Issue by jimmidier** [abpframework/abp#4659]

**Comment by jimmidier** [comment]
As I wanted to derive from AbpDbContext and override the SaveChangesAsync method, I found that calling the base DbContext's SaveChangesAsync method is impossible because AbpDbContext base class blocks the way, while it is generally needed for most situations.
So how do I implement my own AbpDbContext while still able to call DbContext's SaveChangesAsync? Or did I miss something?

**Comment by maliming** [comment]
> I found that calling the base DbContext's SaveChangesAsync method is impossible because AbpDbContext base class blocks the way

Don't understand.

**Comment by jimmidier** [comment]
> > I found that calling the base DbContext's SaveChangesAsync method is impossible because AbpDbContext base class blocks the way
> 
> Don't understand.

For example if I create a class derived from AbpDbContext, override the SaveChangesAsync method, catch the DbUpdateConcurrencyException, handle it and recall the SaveChangesAsync method, then I need to directly call Microsoft.EntityFrameworkCore.DbContext's version because I don't want to repeatedly creat audit logs, update concurrencystamps, or trigger entity events etc as AbpDbContext's version would do. But it seems when I derived from AbpDbContext I couldn't call that base method because AbpDbContext has already overrided it.

**Comment by maliming** [comment]
@hikalkan  Is it necessary to support calling `savechange `method of ef `dbcontext`?

**Comment by hikalkan** [comment]
We can create such a method:

````csharp
Task<int> SaveChangesOnDbContextAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
````

which directly calls `base.SaveChangesAsync`. This solves your problem.

@maliming can you add this (and add summary on top of the method that explains why we did it)?

**Comment by jimmidier** [comment]
@hikalkan @maliming This will work thanks.

**Comment by MohammdaSalah** [comment]
Hi, I override SaveChangesOnDbContextAsync in SettingManagementDbContext like the following but it never been called whenever I update the settings:

 ```
public override async Task<int> SaveChangesOnDbContextAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
    {
        var result = await base.SaveChangesAsync();
        return result;
    }
```

**Comment by acjh** [comment]
`SaveChangesOnDbContextAsync` is provided for your application code to bypass the logic in `AbpDbContext.SaveChangesAsync`. ABP does not call it.

It seems this is what **jimmidier** meant:

```c#
public override async Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
{
    try
    {
        return await base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
    }
    catch (AbpDbConcurrencyException) // DbUpdateConcurrencyException
    {
        // Handle it
        // ...

        // Directly call Microsoft.EntityFrameworkCore.DbContext's SaveChangesAsync(bool, CancellationToken)
        return await base.SaveChangesOnDbContextAsync(acceptAllChangesOnSuccess, cancellationToken);
    }
}
```

You probably just want to override `SaveChangesAsync` instead.
