### ISSUE TITLE
download problem on mac

### ISSUE THREAD

**Issue by alkanarslan** [abpframework/abp#466]
Getting error  on download from https://abp.io/

<img width="429" alt="screen shot 2018-09-28 at 12 54 19" src="https://user-images.githubusercontent.com/1850657/46209402-71d16a00-c336-11e8-966c-bd00309fc8be.png">

**Comment by hikalkan** [comment]
I suppose it's being in Mac. Will try it and resolve. Thanks for reporting.

**Comment by alkanarslan** [comment]
thanks bro

**Comment by hikalkan** [comment]
Resolved with https://github.com/abpframework/abp/commit/0fb6a00922d3525c7386c6f2df06467835344a48

**Comment by hikalkan** [comment]
abp.io has been updated.
