### ISSUE TITLE
Video course for the web application development tutorial (Part 1-5)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4668]

**Comment by hikalkan** [comment]
I've prepared for the first 5 parts:

Part-1: https://www.youtube.com/watch?v=cJzyIFfAlp8&list=PLsNclT2aHJcPNaCf7Io3DbMN6yAk_DgWJ&index=1
Part-2: https://www.youtube.com/watch?v=UDNlLiPiBiw&list=PLsNclT2aHJcPNaCf7Io3DbMN6yAk_DgWJ&index=2
Part-3: https://www.youtube.com/watch?v=TLShZO8u2VE&list=PLsNclT2aHJcPNaCf7Io3DbMN6yAk_DgWJ&index=3
Part-4: https://www.youtube.com/watch?v=aidRB4YFDLM&list=PLsNclT2aHJcPNaCf7Io3DbMN6yAk_DgWJ&index=4
Part-5: https://www.youtube.com/watch?v=1WsfMITN_Jk&list=PLsNclT2aHJcPNaCf7Io3DbMN6yAk_DgWJ&index=5

**Comment by leonkosak** [comment]
@hikalkan, please divide content inside videos like in this one for instance: https://www.youtube.com/watch?v=bf5aHZtwuh8
It's much more search friendly. :)

**Comment by hikalkan** [comment]
Thanks @leonkosak for your feedback.

I see this video course as an experimental weekend project :) I want to get feedback from community and see if it is really helpful. We will work on a more professional video course later.

**Comment by hikalkan** [comment]
But, yes, I can tag sections to align with the documentation, I will do it.

**Comment by zsanhong** [comment]
great job,Need more vidio on how to write a abp module. I write the same code, in application,it's works well.but It wrong in a module

**Comment by hikalkan** [comment]
@leonkosak done:

![image](https://user-images.githubusercontent.com/1210527/89325409-6cab7780-d691-11ea-957a-47b0fdf4bf38.png)
