### ISSUE TITLE
MVC controller with same name as AppService issue

### ISSUE THREAD

**Issue by f-belhocine** [abpframework/abp#4669]
### ControllerConvention
Hi,
If I have an AppService called ExerciseAppService:CrudAppService<,,,,> and then I create an MVC Controller having the name ExerciseController, I have an issue when routing to the Create action in the controller.

[Route("[controller]/[action]")
public ExerciseController : AbpController
{
public IActionResult Create()
{
return PartialView("_Create");
}
}

when using @Url.Action("Create","Exercise") in the view the generated url is     https://host/api/app/exercise

Is it an issue or as designed when generating AutoApi Controllers

**Comment by maliming** [comment]
Auto API Controller has created an **ExerciseController**. So there are two controllers with the same name but their routes are different.

`@Url.Action("Create","Exercise")` will only find the first controller that meets the criteria.
