### ISSUE TITLE
When using mongodb, how to use objectId as Entity.Id's type?

### ISSUE THREAD

**Issue by fmpfmp** [abpframework/abp#4670]
Generally, we use  [BsonId],[BsonRepresentation(BsonType.ObjectId)]  to define _id  with type objectId in mongodb for example:

public class MyClass {
    [BsonId]    
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }
}

the property  will map bo _id with type ‘ObjectId’ in mongodb

However, in ABP, Id is encapsulated in Entity<Tkey> and we cannot set [BsonId] and [BsonRepresentation(BsonType.ObjectId)] for it;

When using mongodb, how to use  objectId as Entity.Id's type?

thanks for your anwser ，thanks

**Comment by maliming** [comment]
Can you share a project?

Related: https://github.com/abpframework/abp/issues/2677

**Comment by Linsan925** [comment]
mark

**Comment by fmpfmp** [comment]
@maliming  @Linsan925 @

https://mongodb.github.io/mongo-csharp-driver/2.10/reference/bson/mapping/#the-id-member

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/4670#issuecomment-655232479

**Comment by fmpfmp** [comment]
@maliming 

https://github.com/fmpfmp/AbpMongodb

**Comment by maliming** [comment]
You can try with this, but this is a problem of `mongo-csharp-driver`.

It should also check **ReflectedType** when using a generic base class.

```cs
cm.DeclaredMemberMaps.As<List<BsonMemberMap>>().Add(new BsonMemberMap(cm,  typeof(MyEntity).GetMember(nameof(MyEntity.Id)).First()));
···

https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Bson/Serialization/BsonClassMap.cs#L1252
