### ISSUE TITLE
Make DistributedMemoryCache implement ICacheSupportsMultipleItems.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#4673]
This makes it easy to test components that use `ICacheSupportsMultipleItems`.

**Comment by hikalkan** [comment]
I see that you've created [TestMemoryDistributedCache](https://github.com/abpframework/abp/blob/dev/framework/test/Volo.Abp.Caching.Tests/Volo/Abp/Caching/TestMemoryDistributedCache.cs). Should we close this?
