### ISSUE TITLE
Outdated documentation localization

### ISSUE THREAD

**Issue by Xeevis** [abpframework/abp#4677]
Hello,
I'd like to apologize but I won't be able to manage more Czech docs translations. It's quite a task not easily handled by single person in his free time and there isn't enough incentive for me to give it enough time it requires.  I can however still keep all the other framework areas up-to-date.

Since Czech documentation is currently quite outdated, it may be doing more harm than good to anyone reading it. Please consider it's removal from publication.

**Comment by hikalkan** [comment]
@yekalkan can you remove the Czech docs?

Thank you @Xeevis for your contribution :)
