### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#468]
In the [Tutorial](https://github.com/abpframework/abp/blob/master/docs/Tutorials/AspNetCore-Mvc/Part-I.md) document, javascript is used,
and I found the #169, but didn't know why it's been cancelled. 
Any plan for supporting typescript?

**Comment by hikalkan** [comment]
It's cancelled because current compile and other tooling does not fit to MVC architecture without some complicated works.
So, we didn't want to use it in the template.

However, there is nothing in ABP restricts Typescript usage. You can do it for your application if you can.
