### ISSUE TITLE
Questions about domain events

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4698]
For EF Core, the distributed events added by the method `AggregateRoot.AddDistributedEvent()` are published in the method `AbpDbContext<TDbContext>.SaveChangesAsync()`.

Method `ChangeStockCount()` in the doc's [example](https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#inside-entity-aggregate-root-classes) is expected to publish a `StockCountChangedEto` distributed event after the StockCount is really changed.

There are some questions:
1. The transaction may fail but the `StockCountChangedEto` distributed event has already been published, is that reasonable?
2. In the current design, `AggregateRoot.AddDistributedEvent()` and `AggregateRoot.AddLocalEvent()` could be used to publish some “ing” events. It is helpful to publish them as local events, but when is it used for distributed events?

Thanks.

**Comment by bxjg1987** [comment]
I've been dealing with this issue all the time. When a logic contains data addition or modification, and then triggers distributed events, are these two operations transactional?

**Comment by gdlcf88** [comment]
> There is no clear explanation in the document

Maybe the code has been explained. The events will be published before the UOW completed, but if you a using the [CAP distributed event bus implementation](https://github.com/EasyAbp/Abp.EventBus.CAP), the transaction may be shared to the distributed event bus (not sure).

**Comment by bxjg1987** [comment]
I typed the wrong word. There is no description of the transaction in the event section of the ABP document. As you said, the event may have been released, but UOW may have an exception, causing a rollback, and eventually putting the software in an error state, right?

**Comment by gdlcf88** [comment]
> UOW may have an exception, causing a rollback, and eventually putting the software in an error state, right?

Yes, I think the events will be published (unless you are using CAP) even if the transaction rollbacked.

**Comment by bxjg1987** [comment]
Yes, the cap framework is more reasonable. Thank you very much.

**Comment by gdlcf88** [comment]
Normally, I will ignore the CAP's transaction feature, because my code is not only for CAP framework but other distributed event bus implementations.
