### ISSUE TITLE
Default organization unit and function in organisation unit

### ISSUE THREAD

**Issue by abxeps** [abpframework/abp#4717]
Abp Version 3.0.3.

It would be great to have the ability to define a "default" or "primary" organisation unit for a user.
Also we should be able to define the function of a user in an organisation unit, like User A is "CEO" in organization unit B.

Is it possible via extensions?
Or could it be part of the framework?

Best regards,

**Comment by liangshiw** [comment]
ABP provides infrastructure for organizational units, and you can easily implement these feature. It should not be part of the framework.
