### ISSUE TITLE
Suggested way to create related entity

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#472]
Using the tutorial:https://github.com/abpframework/abp/blob/master/docs/Tutorials/AspNetCore-Mvc/Part-I.md

Imagine the Book had a property called Category
A Category also has a name, 

Or lets say there is a Job that has a Customer

What'd the suggested way to handle this scenario in which you need to create an entity with another related entity (view wise and also in the application layer)

Thank you

**Comment by hikalkan** [comment]
I suppose the relation is Book *-1 Category and they are aggregate roots.

Actually, you can do as you like, ABP has no restriction.

However, the best practice is not adding a Category navigation property to the Book since aggregates don't add direct references to other aggregates. So, Book will have CategoryId.

BookAppService.Create can get a CategoryId, gets this category from repository (to check if there is such a category) and then create the book entity with given CateogoryId.

If you write a draft code, I can provide suggestions.

**Comment by wocar** [comment]
I just have one more question, if for example I
1.- Add a button "New Category" in the create book modal dialog
2.- I click it and create the new category

How do I get the new created categoryid using the modal manager to use it in the book im creating?
Or should I refer myself to bootstrap modalmanager documentation

Thank you

**Comment by hikalkan** [comment]
So, you want to create nested modals. It's possible, sure.
If you are using ModalManager, it can get result when the modal is saved. So, your server side API can return the new category Id as a result to the save action then you can get it and set to the input.
Please try it, we can help more if needed.

**Comment by wocar** [comment]
Hello Halil could you give me some insight on how to return a value from a modal?

Also I also want you to notice that sometimes nested modals give some sort of focus warning/error that I had to solve using the following code: 

`    $.fn.modal.Constructor.prototype._enforceFocus = function () { };
`

**Comment by hikalkan** [comment]
Simplest demonstration, I worked on the Identity module:

1. Changed ``CreateModalModel.OnPostAsync`` like this:

````C#
        public async Task<ObjectResult> OnPostAsync()
        {
            ValidateModel();

            var input = ObjectMapper.Map<RoleInfoModel, IdentityRoleCreateDto>(Role);
            var role = await _identityRoleAppService.CreateAsync(input);

            return new ObjectResult(role);
        }
````

Just returned the created `RoleDto` object as a result.

2. Registered to onResult callback of the modal:

````js
_createModal.onResult(function (obj, evnt) {
    console.log('id: ' + evnt.xhr.responseJSON.id);
    console.log('name: ' + evnt.xhr.responseJSON.name);
    _dataTable.ajax.reload();
});
````

Here, I can get the returned JSON object as shown.

ModalManager will be documented for different use cases.
