### ISSUE TITLE
Object Disposed Error in IDistributedEventHandler that take a dependency on IRepository

### ISSUE THREAD

**Issue by feanz** [abpframework/abp#4721]
I have IDistributedEventHandler  handlers that take a dependency on IRepository.  This breaks though as you get ObjectDisposed errors on the DB context.  

I have faced similar issues in other solutions that were not based on ABP using entity framework in both asp.net and in event handlers.  It could be that the DBContext has been disposed by the request context but is resolved by the handler.  I had to solve this with different DBContext registrations in the DI container.  I'm not sure how this would work in ABP?

Do you have working examples of EventHandlers using repositories?  I'm happy to update the documentation if users need to handle data access code in event handlers in a different way.

**Comment by maliming** [comment]
Please shared your handler code.

**Comment by feanz** [comment]
Sure

```
 public class ClientSearchIndexUpdatingEventHandler :
        IDistributedEventHandler<EntityCreatedEto<ClientEto>>,
        ITransientDependency
    {
        private readonly IRepository<Client> _repository;

        public ClientSearchIndexUpdatingEventHandler(
            IRepository<Client> repository)
        {
            _repository = repository;
        }

        public async Task HandleEventAsync(EntityCreatedEto<ClientEto> eventData)
        {
            var currentClient = await _repository.Where(x => x.Id == eventData.Entity.Id)
                .SingleOrDefaultAsync();

        }
}
}
```

The error you get when the handler code is fired is 

```
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'MyDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression 
```

**Comment by maliming** [comment]
See https://stackoverflow.com/questions/62777358/objectdisposedexception-when-trying-to-use-the-dbcontext-inside-an-idistributede

**Comment by feanz** [comment]
Thanks that has fixed the issue if its OK I will make a pull request to update the documentation to highlight this when using event handlers and link it back here.
