### ISSUE TITLE
Extend AbpIdentityServerResource problem

### ISSUE THREAD

**Issue by erojasd** [abpframework/abp#4722]
I'm trying to extend "AbpIdentityServerResource" to the Spanish language but when I implement it it causes the login error message to appear in Spanish for any language. My goal is for the login error message to appear in Spanish when this language is selected

Attached test project with the problem: https://drive.google.com/file/d/1xEiLPZCI_w0bOfG6_23TsREedZ8lMPv8/view?usp=sharing.

![image](https://user-images.githubusercontent.com/8540060/87176192-c47bdc00-c2a7-11ea-9b98-3aba882b5758.png)

**Comment by maliming** [comment]
hi @erojasd 

Can you share your steps?

**Comment by erojasd** [comment]
hi @maliming, 
All I did was extend the resource "AbpIdentityServerResource" and override the keys "InvalidUserNameOrPassword" and "InvalidUsername" for the Spanish language

![image](https://user-images.githubusercontent.com/8540060/87345372-f8f8cd80-c51d-11ea-9330-fd1c767e67ed.png)

![image](https://user-images.githubusercontent.com/8540060/87345588-49702b00-c51e-11ea-9674-0d3be08afd10.png)

thanks!

**Comment by maliming** [comment]
hi

When you expand the built-in resources you need to use different folders for them.

https://docs.abp.io/en/abp/latest/Localization#extending-existing-resource

**Comment by erojasd** [comment]
Hi
I tried creating the resources in different folders, but the problem persists. Then, in addition to the Spanish language, I added a resource file for English and now it is launching the validation only in English for all languages: 
Thanks!
![image](https://user-images.githubusercontent.com/8540060/87435733-22673700-c5ba-11ea-972c-6166e940485c.png)
![image](https://user-images.githubusercontent.com/8540060/87435889-4cb8f480-c5ba-11ea-85da-d53f2f718fc1.png)
![image](https://user-images.githubusercontent.com/8540060/87435923-58a4b680-c5ba-11ea-918b-c59b77217866.png)

**Comment by erojasd** [comment]
any idea what might be going on?

**Comment by hikalkan** [comment]
You should extend the AccountResource ([see](https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/Resources/en.json#L11))

**Comment by erojasd** [comment]
Thanks for the reply.
The problem was fixed and it was due to an incorrect setting in OnApplicationInitialization within the HttpApiHostModule file
