### ISSUE TITLE
Replace function in service with different signature

### ISSUE THREAD

**Issue by engmohamedead** [abpframework/abp#4726]
hi all, I am new to that framework and i want to replace the update function in service with different signature
the new signature will be as follow:

```
public  async Task<CustomerDto> UpdateAsync(CreateUpdateCustomerDto input)

the original signature is like this

public  async Task<CustomerDto> UpdateAsync(int id,CreateUpdateCustomerDto input)

Please show me how to do this

**Comment by gdlcf88** [comment]
You can use `ReadOnlyAppService` instead of `CrudAppService`, and implement the UpdateAsync method yourself.

**Comment by engmohamedead** [comment]
This is not fully clear to me
Can you post a full example please?

**Comment by hikalkan** [comment]
`public  async Task<CustomerDto> UpdateAsync(int id,CreateUpdateCustomerDto input)` is better and it is easier to set route on the http api layer. I suggest you to go with the conventions. Otherwise, don't inherit from the CrudAppService base class and write your own application service manually.
