### ISSUE TITLE
New Module: CMS Kit / Prepare the initial solution

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4743]
## Introduction

CMS Kit (CmsKit) is a new module idea that contains CMS (Content Management System) components. It is not a CMS application, but actually a CMS framework or component set.

Some of the planned components are;

* Reactions (thumbs up, smile... etc.)
* Rating
* Comments
* Tags
* Favorites

These components are entity independent and provides reusable widgets. For example, you can add a "comment" or "tag" functionality to an image gallery or a blog post.

**This is currently experimental and you are free to comment on this issue for your ideas.**

This issue is to create the initial solution structure for the development.

### Switch to Local Framework References

* We should change project references to the local framework, instead of NuGet package references.

### Change the Solution Structure

- host
  * (keep current projects)
- core
  * Volo.CmsKit.Domain.Shared
  * Volo.CmsKit.Domain
  * Volo.CmsKit.EntityFrameworkCore
  * Volo.CmsKit.MongoDB
- public
  * Volo.CmsKit.Public.Application.Contracts
  * Volo.CmsKit.Public.Application
  * Volo.CmsKit.Public.HttpApi
  * Volo.CmsKit.Public.HttpApi.Client
  * Volo.CmsKit.Public.Web
- admin
  * Volo.CmsKit.Admin.Application.Contracts
  * Volo.CmsKit.Admin.Application
  * Volo.CmsKit.Admin.HttpApi
  * Volo.CmsKit.Admin.HttpApi.Client
  * Volo.CmsKit.Admin.Web
- unified
  * Volo.CmsKit.Application.Contracts
  * Volo.CmsKit.Application
  * Volo.CmsKit.HttpApi
  * Volo.CmsKit.HttpApi.Client
  * Volo.CmsKit.Web

#### Additional Info

* Unified packages are shortcut to add admin+public. They don't have their own functionality (so, they are meta packages).

### Apply Module Standards

* Root namespaces should be empty. So, re-arrange folders & files.
* Configure Fody.
* Configure common.props
* ...

**Comment by wakuflair** [comment]
I'm excited to see this.

I think the key of a CMS is to be able to handle dynamic content flexibly. Users should easily define a content (blog, questionnaire, webpage, etc.) without hardcode.

So is there anything you can share about dynamic content management?

**Comment by gdlcf88** [comment]
> It is not a CMS application, but actually a CMS framework or component set.

https://github.com/maliming/Owl.GeneralTree may be a good example, it provides a standard entity structure, repository, UI component, and more.

CMS Kit is a great and important infrastructure for application module development. After I knew this plan, I stopped the development of application modules that depend on CMS Kit's features. I hope it will be released earlier. 😃

**Comment by 1d0n7kn0w** [comment]
There is already an in-progress CMS module https://github.com/EasyAbp/Cms/
It would be wise to combine efforts and learn from what has been done

**Comment by gdlcf88** [comment]
> There is already an in-progress CMS module https://github.com/EasyAbp/Cms/

EasyAbp.Cms is an application module, not **a CMS framework or component set** and it is a backlog for now. I'd like to continue to develop this module with the CMS Kit after it's released.

**Comment by NecatiMeral** [comment]
Looking forward for the favourites widget!
