### ISSUE TITLE
Can Remove UseHangfireServer in the Hangfire background job doc

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4745]
It is about the doc https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire

If we follow the original doc to add `app.UseHangfireServer();`, we can see there are two servers with the same name in the Hangfire dashboard. Then we add this configuration:

```csharp
context.Services.Configure<AbpBackgroundJobOptions>(options =>
{
    options.IsJobExecutionEnabled = false;
});    
```

We can still see one server is running locally.

So I think the doc is wrong, we should not add `app.UseHangfireServer();` since the `AbpBackgroundJobsHangfireModule.OnPreApplicationInitialization()` method has created the HangfireServer.

**Comment by liangshiw** [comment]
We have started the server in `AbpHangfireModule`,  can remove `UseHangfireServer` in the document.

> Problem: Hangfire server is always enabled

Is not problem, because only add background jobs still requires server, but it will not execute the job.
