### ISSUE TITLE
MicroserviceDemo Backend Admin App Permission endpoint not found error

### ISSUE THREAD

**Issue by gterdem** [abpframework/abp#4751]
```
[ERR] Remote service returns error! HttpStatusCode: NotFound, ReasonPhrase: Not Found
Volo.Abp.AbpException: Remote service returns error! HttpStatusCode: NotFound, ReasonPhrase: Not Found
```

BackendAdminAppGateway:
```
message: DownstreamRouteFinderMiddleware setting pipeline errors. IDownstreamRouteFinder returned Error Code: UnableToFindDownstreamRouteError Message: Failed to match ReRoute configuration for upstream path: /api/permission-management/permissions, verb: GET.
```

**Comment by RobinDavisNotts** [comment]
Using the latest version of Ocelot the issue seems to stem from the old config value being "ReRoutes" when it should be "Routes", demo application worked as expected when I did the change

**Comment by MohanaRanjanKP** [comment]
@gterdem I faced the same error when trying to run the project as mentioned in the [Microservice Demo Solution](https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo#run-projects).

I rerun the Projects, but this time by **authenticating the AuthServer.Host** by giving the username and Password and proceed with running other projects in same order.

Now the Issue is not reproduced. By design the Backend Admin App requires this authentication.

I think this is an authentication issue and not related to bug.

**Comment by MohanaRanjanKP** [comment]
Also the document [Microservice Demo Solution#Run-Projects](https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo#run-projects) should be updated with one additional step of Authenticating the AuthServer.Host before proceeding to running other projects as well.

**Comment by RezaPouya** [comment]
Can anyone tell me how this permission system work? 
there is only one PermissionGrant table and I can't see any document about it ... for example how in this table you can prohabit a permission for a user ? or does permission with permission providerKey of "C" can be applied to roles ? 

i create multiple microservices but none of them can authorized permission ... the permission are not in claims .. should i make http request to auth-server to check those !? 

can you explain how this permission grant table works ?

I read this article several times , but i couldn't understand from which store is going to authorize the permission ? 
https://docs.abp.io/en/abp/latest/Authorization

- UserPermissionValueProvider  , RolePermissionValueProvider  : against what store is checking UserPermission correctness ? local store , claims or remote-store ? 

for god sake , if my authorization server is separated from micro-service server , from where it the microservice is going to ask for authorizing the permission !?

**Comment by gterdem** [comment]
https://github.com/abpframework/eShopOnAbp is the main sample for microservice now. Closing the issue.
