### ISSUE TITLE
Background Jobs and worker Tenant wise Information

### ISSUE THREAD

**Issue by HiteshAnshani** [abpframework/abp#4754]
Hello,

I have seen **background jobs** and **workers**.
but I wanted to know how to run the jobs and workers tenants wise?
**can you please provide the sample code.**

**like:-**

I want to access the user repository tenant wise so what will be the options?

**Comment by jacmiller12** [comment]
Hi @HiteshAnshani ,
I also wanted to know how it will work.
Team @maliming @ChangYinShung can you please help us the same.
Because in my future project I also wanted to use these background jobs and workers tenant wise.

**Comment by gdlcf88** [comment]
If you want to change to a specified tenant, you can inject `ICurrentTenant` and try:

```csharp
using (_currentTenant.Change(tenantId))
{
    var user = await _identityUserRepository.GetAsync(userId);
}
```

If you want to execute some query without multi-tenant data filter, you can inject `IDataFilter` and try:

```csharp
using (_dataFilter.Disable<IMultiTenant>())
{
    return await _bookRepository.GetListAsync();
}
```

See:
https://docs.abp.io/en/abp/latest/Multi-Tenancy#change-current-tenant (should be completed)
https://docs.abp.io/en/abp/master/Data-Filtering#idatafilter-service-enable-disable-data-filters

**Comment by HiteshAnshani** [comment]
yes, I tried this it's working.
thanks, @gdlcf88.

**Comment by wjkhappy14** [comment]
great
