### ISSUE TITLE
Create controller manually 

### ISSUE THREAD

**Issue by ToanDao2612** [abpframework/abp#4756]
I try create controller manually but i can't protect it with identity server so i can access this controller from anywhere

**Comment by maliming** [comment]
Please check the docs: https://docs.abp.io/en/abp/latest/Authorization

**Comment by ToanDao2612** [comment]
> Please check the docs: https://docs.abp.io/en/abp/latest/Authorization

I used authorize attribute then i get internal server error, i want it identity by client scope, client id in identity server

**Comment by maliming** [comment]
This is not simple to explain. You should refer to the identity server documentation and examples.
