### ISSUE TITLE
Initial CmsKit Reactions System

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4761]
# CMS Kit / Reactions

The purpose is to create a system to react to an entity. Example screens:

![image](https://user-images.githubusercontent.com/1210527/87456845-2aea5c80-c610-11ea-9f15-92c48528fcc0.png)

![image](https://user-images.githubusercontent.com/1210527/87456853-2e7de380-c610-11ea-9bcf-94f18f0c9959.png)

Yes, copied from GitHub 😃 

## Requirements

* Only an authenticated user can create reactions
* A reactions has;
  * A unique (programmatic) name
  * A localizable display name (optional, determined by conventions)
  * An icon (localizable?)
* Configurations;
  * Can add new reactions (we provide a few common reactions out of the box)
  * Can determine available reactions for an entity type
* The API (and UI) should allow to;
  * Create (idempotant) and delete reaction for an entity
  * Get a list of reactions (with reaction name & count) for an entity, including reactions of the current user.

**Comment by gdlcf88** [comment]
> An icon (localizable?)

Just like "doge" is not popular in CN, but we have "funny" (that's my GitHub profile picture🌝), they are similar in expression. So I think this feature is really useful.

![image](https://user-images.githubusercontent.com/30018771/89512567-fc723280-d805-11ea-9e57-a0bfbec0f299.png)
