### ISSUE TITLE
bug of Volo.Blogging module?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#4765]
I add Volo.Blogging to my application,and when I create a new Post,there always show the message:
![image](https://user-images.githubusercontent.com/5259153/87491306-63bf1b80-c67a-11ea-9605-e45a364aebd0.png)

in fact I have choose the cover image file, any thing have I missed? or is this a bug?

**Comment by liangshiw** [comment]
I will check it out.

**Comment by zhchlmm** [comment]
Try to configure BloggingFileOptions to set the file storage folder.

**Comment by zsanhong** [comment]
@zhchlmm how to config?

**Comment by zsanhong** [comment]
thank you,I have add the code :
```
 Configure<BlogFileOptions>(options =>
            {
                options.FileUploadLocalFolder = Path.Combine(hostingEnvironment.WebRootPath, "files");
            });
```
and it worked
