### ISSUE TITLE
Using Hangfire in Domain project makes the DbMigrator project not runnable.

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4773]
The `AbpHangfireModule.OnApplicationInitialization()` method invokes `AbpHangfireOptions.CreateJobServer()` method, it requires that the `JobStorage` be in IOC, but in DbMigrator project, we don't add Hangfire, so `JobStorage` is never in the IOC, it raises the problem.

**Comment by liangshiw** [comment]
![image](https://user-images.githubusercontent.com/16813853/87679189-75094480-c7ae-11ea-9835-9e46dd88a596.png)
