### ISSUE TITLE
Identity refresh token needed in ABP framework

### ISSUE THREAD

**Issue by jacmiller12** [abpframework/abp#4781]
Hello,

I want refresh token while login from **connect/token** so while referring the identity 4 document

https://identityserver4.readthedocs.io/en/latest/topics/refresh_tokens.html

in our ABP framework **AllowOfflineAccess**  property is already true but when I am passing `offline_access` in scope
parameter its says 

```
{
    "error": "invalid_scope"
}
```
I can see client, scops, grant types classes are designed our own so can you guide me on what I will do to get refresh token.
I know this is related to the Identity server but When I am changing in the ABP framework still it showing me an error.

Please check the logs and openId configuration 

[Logs.txt](https://github.com/abpframework/abp/files/4931573/Logs.txt)

`{"issuer":"https://localhost:44310","jwks_uri":"https://localhost:44310/.well-known/openid-configuration/jwks","authorization_endpoint":"https://localhost:44310/connect/authorize","token_endpoint":"https://localhost:44310/connect/token","userinfo_endpoint":"https://localhost:44310/connect/userinfo","end_session_endpoint":"https://localhost:44310/connect/endsession","check_session_iframe":"https://localhost:44310/connect/checksession","revocation_endpoint":"https://localhost:44310/connect/revocation","introspection_endpoint":"https://localhost:44310/connect/introspect","device_authorization_endpoint":"https://localhost:44310/connect/deviceauthorization","frontchannel_logout_supported":true,"frontchannel_logout_session_supported":true,"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"scopes_supported":["openid","profile","email","address","phone","role","offline_access","BookStore","offline_access"],"claims_supported":["sub","birthdate","family_name","gender","given_name","locale","middle_name","name","nickname","picture","preferred_username","profile","updated_at","website","zoneinfo","email","email_verified","address","phone_number","phone_number_verified","role","offline_access"],"grant_types_supported":["authorization_code","client_credentials","refresh_token","implicit","password","urn:ietf:params:oauth:grant-type:device_code"],"response_types_supported":["code","token","id_token","id_token token","code id_token","code token","code id_token token"],"response_modes_supported":["form_post","query","fragment"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"id_token_signing_alg_values_supported":["RS256"],"subject_types_supported":["public"],"code_challenge_methods_supported":["plain","S256"],"request_parameter_supported":true}`

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by HiteshAnshani** [comment]
Hi @jacmiller12,

try to pass **BookStore offline_access** both in the scope parameter.

**Comment by jacmiller12** [comment]
Hello @HiteshAnshani ,
thanks, man it's working.
