### ISSUE TITLE
Requesting to an API without authorization is redirected to Login page

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4785]
I read the [document](https://github.com/abpframework/abp/blob/07d07fe238e74f00f570d2731b737b954654678f/docs/en/Exception-Handling.md#automatic-exception-handling):

> Client explicitly accepts the application/json content type (via accept HTTP header).

![image](https://user-images.githubusercontent.com/30018771/87760101-d8908200-c841-11ea-9152-b854450e88cd.png)

The ABP version: 3.0.1
The startup template: app with MVC-UI

Configurations in WebModule is following the startup template.

Other information:
* Requesting with `XMLHttpRequest = X-Requested-With` does not redirect to the login page, but get **empty content** with 401 status code.

**Comment by gdlcf88** [comment]
I see https://github.com/abpframework/abp/issues/2643#issuecomment-574940166, it explained the reason.

Does it mean I must manually create controllers?

**Comment by wakuflair** [comment]
Is there a convenient way to configure the authorization for all the auto controller methods? Something like

```
ConfigureAutoController(opt => opt.UseAnonymousForAll())
```

@maliming

**Comment by maliming** [comment]
`AutoController` depends on the `[Authorize]` attribute on the application service.

**Comment by wakuflair** [comment]
The `[Authorize]` returns 401 if authorization failed, but `AutoController` redirects to the login page.

It's hard for mobile or other clients that only using API as a server due to this behaviour.

**Comment by maliming** [comment]
This is the behavior of asp net core unless we use other methods to implement auto controllers.

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/5235#event-3716370525

**Comment by yincen** [comment]
This issue has been added to the milestone. See https://github.com/abpframework/abp/milestone/39

**Comment by yincen** [comment]
> 
> 
> The `[Authorize]` returns 401 if authorization failed, but `AutoController` redirects to the login page.
> 
> It's hard for mobile or other clients that only using API as a server due to this behaviour.

This issue has been added to the milestone. See https://github.com/abpframework/abp/milestone/39

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/9940
