### ISSUE TITLE
abp generate-proxy error with customized IdentityUserAppService

### ISSUE THREAD

**Issue by Zupit-Director** [abpframework/abp#4786]
# abp generate-proxy error with customized IdentityUserAppService
## Description
With an App Service derived from IdentityUserAppService
`abp generate-proxy ` 
create a model identity-user-dto.ts referring to a non existent ExtensibleFullAuditedEntityDto instead of FullAuditedEntityDto

## Version
* Abp Version : 2.9
* Gui : Angular

## Steps needed to **reproduce** the problem.
  - in a new project 
  - Add extraproperties to IdentityUserDto as explained in docs
  - create a CustomIdentityUserAppService derived from IdentityUserAppService ( with no ExposeServices  and RemoteService  attributes)
  - overried GetAsyncs(Guid id)
  - execute abp generate-client
  - models generated include identity-user-dto.ts referring to a non existent ExtensibleFullAuditedEntityDto instead of FullAuditedEntityDto

**Comment by maliming** [comment]
Can you share you c# code and generated angular code.

**Comment by Zupit-Director** [comment]
I ran **abp new Test.User**

I created file Test.User\aspnet-core\src\Test.User.Application\CustomizedIdentityUserAppService.cs

`
	using Volo.Abp.Identity;
	namespace Test.User.Application
	{
		public class CustomizedIdentityUserAppService : IdentityUserAppService {

			public CustomizedIdentityUserAppService(IdentityUserManager userManager, IIdentityUserRepository userRepository, IIdentityRoleRepository roleRepository) : base(userManager, userRepository, roleRepository)
			{
			}
	   }
	}

`

Then I ran 

`abp generate-proxy`

It added folder Test.User\angular\src\app\customizedidentityuser contaning also Test.User\angular\src\app\customizedidentityuser\models\identity-user-dto.ts

`
    import { **Extensible**FullAuditedEntityDto } from '@abp/ng.core';
    export class IdentityUserDto extends **Extensible**FullAuditedEntityDto<string> {
     tenantId?: string;
     userName: string;
     name: string;
     surname: string;
     email: string;
     emailConfirmed: boolean;
     phoneNumber: string;
     phoneNumberConfirmed: boolean;
     twoFactorEnabled: boolean;
     lockoutEnabled: boolean;
     lockoutEnd?: string;
     concurrencyStamp: string;
     isDeleted: boolean;
     deleterId?: string;
     deletionTime?: string;
     lastModificationTime?: string;
     lastModifierId?: string;
     creationTime: string;
     creatorId?: string;
     id: string;
     extraProperties: any[];

      constructor(initialValues: Partial<IdentityUserDto> = {}) {
         super(initialValues);
      }
   }
`

**Comment by hikalkan** [comment]
We are re-wrting the generate-proxy system. Follow https://github.com/abpframework/abp/issues/4881 It will be available with 3.1. If your problem persists after 3.1, please reopen the issue.
