### ISSUE TITLE
How to configure Quartz using MongoDb

### ISSUE THREAD

**Issue by carloszan** [abpframework/abp#4800]
I've followed the docs about how to install [quartz in background jobs](https://docs.abp.io/en/abp/latest/Background-Jobs-Quartz). But the problem is: I want to use MongoDb to save the jobs. I've installed 2 libs to help me to achieve that: **Quartz.Serialization.Json and Quartz.Spi.MongoDbJobStore**.  So now I can say to quartz config that it should use that job store.
My module is like this:

```
[DependsOn(
        typeof(MyDomainSharedModule),
        typeof(AbpAutofacModule),
        typeof(AbpBackgroundJobsQuartzModule)
        )]
    public class MyDomainModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            var configuration = context.Services.GetConfiguration();

            PreConfigure<AbpQuartzOptions>(options =>
            {
                options.Properties = new NameValueCollection
                {
                    ["quartz.serializer.type"] = "json",
                    ["quartz.jobStore.collectionPrefix"] = "quartz",
                    ["quartz.jobStore.type"] = "Quartz.Spi.MongoDbJobStore.MongoDbJobStore, Quartz.Spi.MongoDbJobStore",
                    ["quartz.jobStore.connectionString"] = configuration["ConnectionStrings:Default"]
                };
            });
        }
    }
```

So when I run that service I know everything worked because of this log:

```
[21:35:53 Information] Quartz.Core.QuartzScheduler
Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Spi.MongoDbJobStore.MongoDbJobStore' - which supports persistence. and is not clustered.
```

But few more logs later, it stops in this message:

```
[21:35:56 Information] Quartz.Core.QuartzScheduler
JobFactory set to: Volo.Abp.Quartz.AbpQuartzJobFactory
```

And nothing else is loaded. We can't see Swagger, etc.

I ran the application without configuration and the next config after AbpQuartzJobFactory is this one here:

```
[21:45:30 Information] Quartz.Core.QuartzScheduler
Scheduler QuartzScheduler_$_NON_CLUSTERED started.
```

EDIT: [the whole log from MyService.Host here](https://gist.github.com/carloszan/220f74d1a27e86b3c0ac9b5a27b1fe4f)
After those logs, nothing else appears like it were waiting for something. while when there's no those configs, server runs 100% ok. i have no idea why this could be happening.

I'm kinda lost. Could anyone help me? Thank you!

**Comment by liangshiw** [comment]
Can you shared more logs?

**Comment by carloszan** [comment]
> Can you share more logs?

I edited the issue

**Comment by liangshiw** [comment]
Hi,

Deadlock occurred in the `MongoDbJobStore` code, I forked mongodb-quartz-net project and modified the source code. see : https://github.com/liangshiw/mongodb-quartz-net/tree/ConfigureAwait
