### ISSUE TITLE
Documentation 404- Check a Permission in JavaScript

### ISSUE THREAD

**Issue by rafaelgfirmino** [abpframework/abp#4803]
The link [abp.auth](https://docs.abp.io/en/abp/latest/Authorization#check-a-permission-in-javascript) is broken.

**Comment by maliming** [comment]
I have updated the link. 

We are constantly improving the documentation of the ABP Framework. In the previous milestone, we've completed most of the fundamental documents (like UOW, distributed event bus... etc). Recently, completely revised and extended the startup tutorial. Documentation will be a high priority in the next milestones too.
