### ISSUE TITLE
Introduce BasicAggregateRoot base class

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4808]
Sometimes, I want to create an aggregate root, but don't want to add `ConcurrencyStamp` and `ExtraProperties`.

So, create `BasicAggregateRoot` and `BasicAggregateRoot<TKey>`, just like the [current classes](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/AggregateRoot.cs), but don't implement `IHasExtraProperties` and `IHasConcurrencyStamp`. Then inherit the current `AggregateRoot` and `AggregateRoot<T>` from these new classes.

**Comment by ViatorLife** [comment]
I try to use [NotMapped] attribute and Fluent.API ".ignore(x=>x.ExtraProperties)" in order to not generate an ExtraProperties field in the data table,but none of these methods work. Is there a way to accomplish this function?
The version I'm using is 3.0.5,Expect 3.1 to arrive.

**Comment by maliming** [comment]
The best way is waiting for 3.1.

**Comment by ViatorLife** [comment]
> The best way is waiting for 3.1.

Thank you, full of anticipation.

**Comment by sebitsi** [comment]
@hikalkan  As i can see from code, BasicAggregateRoot is put behind AggregateRoot.
What about AuditedAggregateRoot and CreationAuditedAggregateRoot ?

Is it possible to create BasicAuditedAggregateRoot and BasicCreationAuditedAggregateRoot too ? 

It will be very usefull for us.

Regards

**Comment by hikalkan** [comment]
`BasicFullAditedAggregateRoot` naming seems strange to me ("basic" and "full" together). I think if you add audit properties, you can add two more standard properties (concurrencystamp and extraproperties) :)

**Comment by sebitsi** [comment]
@hikalkan Thanks for answere. 

I'm asking if you will add BasicAuditedAggregateRoot and BasicCreationAuditedAggregateRoot as abstract classes without IHasExtraProperties and IHasConcurrencyStamp implemented.

Of course i can do myself. I think this two classes could be part of abpFramework too.

What do yo mean ?

**Comment by ViatorLife** [comment]
> @hikalkan Thanks for answere.
> 
> I'm asking if you will add BasicAuditedAggregateRoot and BasicCreationAuditedAggregateRoot as abstract classes without IHasExtraProperties and IHasConcurrencyStamp implemented.
> 
> Of course i can do myself. I think this two classes could be part of abpFramework too.
> 
> What do yo mean ?

I added an additional aggregate root based on basic aggregate root, named Common Aggregate Root, not inherited by IHas Extra Properties, and added Audited Common Aggregate Root, Created Audited Common Aggregare Root and Full Audited Common Common Root, this complete set is used directly in the project.

**Comment by sebitsi** [comment]
@SAssassin i know it is possible that i can create abstract class as you by myself.

My question for @hikalkan was if ABP team has plan to put some in framework.

**Comment by hikalkan** [comment]
Hi @sebitsi we don't plan to add these for now, please do it in your application.
