### ISSUE TITLE
How to catch and use inner BusinessException message in outter class?

### ISSUE THREAD

**Issue by BrianCodeman** [abpframework/abp#4811]
Hi team,

BusinessException is really helping, but I want to know if I could catch child class' BusinessException message, add some extra information and re-throw another BusinessException at the parent class. For instance, I could have a class structure like this:

```
    public class Person
    {
        public string Name { get; set; }
        public Address Address { get; set; }

        public Person(string name, string address)
        {
            try
            {
                Address = new Address(address);
            }
            catch (BusinessException e)
            {
                throw new  BusinessException(null, $"Error for {name}: {e.Message}");
            }
        }
    }

    public class Address
    {
        public string Street { get; set; }

        public Address(string street)
        {
            if (string.IsNullOrEmpty(street))
            {
                throw new  BusinessException(ErrorCodes.AddressShouldNotBeEmpty);
            }
        }
    }
```

My aim is obvious, if an Exception happens to Address, it can't aware who it belongs to, so the Exception should be catched by Person class, add name to the message and re-throw again. The issue is, I found it's impossible to get meaningful e.Message, since it isn't being translated to user-end.

Could you please give me some advice to solve this kinda use case?

**Comment by maliming** [comment]
hi 
I think your needs cannot be solved.

**Comment by BrianCodeman** [comment]
Still thanks.
