### ISSUE TITLE
Cannot run Volo.Docs.Admin.Web.

### ISSUE THREAD

**Issue by mohammad198600** [abpframework/abp#4816]
When I run the project, I run into this error "Unable to run your project. The **"RunCommand"** property is not defined."

When changing the <OutputType>Library</OutputType> to <OutputType>exe</OutputType> I run into this error **"Program does not contain a static 'Main' method suitable for an entry point"**

The question is, how to run VoloDocs?

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/master/Modules/Docs
