### ISSUE TITLE
Add DomainTenantResolver and with angular.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#4817]
Hi Guys,

You all guys are doing wonderful job. Thank you so much for your efforts and wonderful thought.
 
I am trying to test multi tenant (subdomain) on localhost using angular platform with following the below steps:
Step 1. Added "options.AddDomainTenantResolver("{0}.mydomain.com") and added corsorigin too.
Step 2. Added test1.mydomain.com, test2.mydomain.com in hosts file (as I am using windows OS).
Step 3. Run the asp.net project on localhost.
Step 4: Build the angular project and then hosted on IIS with bindings *.mydomain.com and mydomain.com
Step 5: Logged in as admin in host (angular) http://mydomain.com and added two test tenants (test1, test2).
Step 6: Logged out and tried with subdomain http://test1.mydomain.com (angular), it does not auto bind tenant. -- ISSUE 1
Step 7: Even after set tenant from tenant switch box and logged in, it still logged into as host app with subdomain url. - ISSUE 2

What else should I need to do to consider subdomain from URL in angular project?

_Originally posted by @brainedcode in https://github.com/abpframework/abp/issues/3304#issuecomment-661647820_

**Comment by brainedcode** [comment]
@maliming : Is it the know issue or have not implemented yet?

**Comment by maliming** [comment]
hi @brainedcode  This featue has not been implemented.

**Comment by maliming** [comment]
This feature will be available after 4.3.

![image](https://user-images.githubusercontent.com/6908465/112990801-08e23b80-9199-11eb-8bcd-63a57eb0ab49.png)
