### ISSUE TITLE
Unify own Tenant entity (User, etc.) and ABP Tenant (User, etc.) in one edit control of Angular app

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#4819]
Hi!

We need to have own DB tables for many entities like _Tenant_, _User_, etc. - extending built-in **ABP** functionality, i.e. each own entity contains corresponding ABP entity as a property. We need to perform _CRUD_ operation on such entity as a whole - i.e. creating **ABP** _Tenant_ (using existing **ABP** backend functionality) + our _Tenant_ (**ABP** _User_ and our _User_). This means we would like to have one UI control in **Angular** app for editing **ABP** entity + our entity. We don't want to break existing functionality if **ABP** would change own controls in future. Now we cannot see the way to unify editing in one control. Could you please suggest how to do that? Is it supposed to be a brand-new component of ours and hiding your component or some injection, etc.? So far I have replaced built-in _SAAS_ _TenantComponent_ with my own in **Angular** app, but going to call _SAAS_ built-in **TenantAppService** to operate on _SAAS_ _Tenant_ entity within my app custom _tenant app service_. Just want to make sure I am doing it as supposed and won't meet any impediments and issues this way.

I am stuck here, because **OnCompleted** is not triggered straight after **CompleteAsync**, but instead `return ObjectMapper.Map` - is called right away. According to your unit tests, it is incorrect behaviour? Another question - do I have to use **RollbackAsync** somwhere if error happens during second _Insert_?:

                Tenant newTenant = null;
                using (var uow = _unitOfWorkManager.Begin(new AbpUnitOfWorkOptions { IsTransactional = true }))
                {
                    var abpTenant = await _abpTenantManager.CreateAsync(input.AbpTenant.Name, input.AbpTenant.EditionId);
                    input.AbpTenant.MapExtraPropertiesTo(abpTenant);
                    var newAbpTenant = await _abpTenantRepository.InsertAsync(abpTenant);

                    uow.OnCompleted(async () =>
                    {
                        var tenant = ObjectMapper.Map<CreateTenantDto, Tenant>(input);
                        tenant.AbpId = newAbpTenant.Id;
                        var newTenant = await _tenantRepository.InsertAsync(tenant);
                    });

                    await uow.CompleteAsync();
                }
                return ObjectMapper.Map<Tenant, TenantDto>(newTenant);

Thank you!

**Comment by maliming** [comment]
You can try to create a new unit of work.

 `using (var uow = _unitOfWorkManager.Begin(new AbpUnitOfWorkOptions {requiresNew: true, isTransactional= true }))`
