### ISSUE TITLE
Multi-language support for the docs module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#482]
Support translations of the documents

**Comment by yrmartinez** [comment]
I would like to help if you have interest in support Spanish language please let me know.

**Comment by hikalkan** [comment]
Thanks @yrmartinez for your help. Currently, the only texts are https://github.com/abpframework/abp/blob/master/modules/docs/src/Volo.Docs.Domain/Volo/Docs/Localization/Domain/en.json.
Just create a json file for spanish and send a PR :)

BTW, this issue (Multi-language support) is actually for content localization and is a bigger job. If you want to translate documents (which is a hard job) then we can talk on that too :)

**Comment by yrmartinez** [comment]
Already created a PR,  and yes, I would like to help with the translation even if it is a hard job :) so let me know the details.

**Comment by epgeroy** [comment]
Hi there, I would like to help with the documentation translations to Spanish also. Since I know @yrmartinez we can collaborate with this easily together with this.

**Comment by hikalkan** [comment]
@yrmartinez pleace check this: https://github.com/abpframework/abp/blob/master/docs/en/Contribution/Index.md
