### ISSUE TITLE
  [SourceCodeInvestigation] which class inherited from IDataSeedContributor do user initialization while EF Migrating

### ISSUE THREAD

**Issue by wossig** [abpframework/abp#4821]
Hi Guys, 

I'm really interested on ABP Framework,  so I'm trying to read source code to help to deeply know how does it work. 
So I'm trying to find where to initialize user when first EF Migration, but unfortunately I didn't found it, any guy can help point out where it is?  and is there any good advise to read source code?

**Comment by maliming** [comment]
hi

Have you read the Data seeding document?

https://docs.abp.io/en/abp/master/Data-Seeding


> and is there any good advise to read source code?

You can check the unit test to study the source code.

**Comment by wossig** [comment]
Thanks @maliming ,  yeah, I had read the data seeding documentation, I know data initialization came from **IDataSeedContributor**,   but I didn't find the place to initialize  **AbpUsers**, yeah I just want know which data seeder class initialized the admin user  **admin**, so could you guy give further help or clue to find it out?

**Comment by wossig** [comment]
Thanks guy, I found the place now, I should read documentation carefully!

[https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityDataSeedContributor.cs](url)
