### ISSUE TITLE
How to get permissions defined by multiple projects.

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#4824]
I have two projects, `admin` and `public`, both of which have their own `PermissionDefinitionProvider`. How to get public project permissions in admin project permission management. This is similar to the Blogging module.
or  should admin and public put in one project?
Thanks!

**Comment by liangshiw** [comment]
You can create a `Application.Contracts.Shared` project.

See https://github.com/abpframework/abp/tree/dev/modules/blogging/src/Volo.Blogging.Application.Contracts.Shared

**Comment by snowchenlei** [comment]
This is exactly what I need, thank you for your help.
