### ISSUE TITLE
I am wonder where is the tenant id input parameter for api token? 

### ISSUE THREAD

**Issue by brainedcode** [abpframework/abp#4825]
ABP Version: latest.

![image](https://user-images.githubusercontent.com/7672031/88070357-9799b580-cb40-11ea-9ddb-fe33a70cef9b.png)

**Comment by liangshiw** [comment]
See https://docs.abp.io/en/abp/latest/Multi-Tenancy

**Comment by brainedcode** [comment]
Thanks @liangshiw for quick response. But my application is already configured to use Multi tenancy. Please refer below screenshot:
![image](https://user-images.githubusercontent.com/7672031/88073675-73d86e80-cb44-11ea-8919-a435a8fb38e8.png)
