### ISSUE TITLE
Blogging module doesn't work correctly

### ISSUE THREAD

**Issue by 1d0n7kn0w** [abpframework/abp#4829]
* ABP Framework version : 3.0.4
* User Interface : MVC

I added the blogging module to my app but I can't create a new post, I think the problem is with the npm packages

![newPost](https://user-images.githubusercontent.com/3910210/88126601-d031a180-cbc9-11ea-83d5-86f20a23e7ac.png)

![newPostConsole](https://user-images.githubusercontent.com/3910210/88126619-d889dc80-cbc9-11ea-983e-c463d5324c39.png)

![npm](https://user-images.githubusercontent.com/3910210/88126628-dde72700-cbc9-11ea-8b15-46957e688c07.png)

**Comment by liangshiw** [comment]
I will check it out.

**Comment by liangshiw** [comment]
I can't reproduce your problem. 
You should check your npm source.

**Comment by 1d0n7kn0w** [comment]
if you use yarn you can reproduce the problem
I used npm and then my problem is solved

**Comment by zhchlmm** [comment]
I had a samilar problem with tuiEditor initialization that caused by the error 'msie' undefined,  I found that the tui-code-snipet.js raised the 'msie' undefined error, because the npm restored  a wrong version of tui-code-snipet.js .

**Comment by liangshiw** [comment]
This has nothing to do with ABP. https://github.com/nhn/tui.editor/issues/748

**Comment by vnetonline** [comment]
I am using the new 4.0.0 and having the same issues with the same error message ..... there seems to be some conflict with the outdates jQuery.
