### ISSUE TITLE
NgxsStoragePluginModule can't forRoot twice

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#4839]
Your ABP Framework version. 3.0.3  
Your User Interface Angular  
https://github.com/abpframework/abp/blob/4f57c823c8eb72c4e72f87db07f6fe4bbbe6f09f/npm/ng-packs/packages/core/src/lib/core.module.ts#L120

In some situation ,  i also  need  use `NgxsStoragePluginModule` too,something like 
``` javascript
 NgxsStoragePluginModule.forRoot({ key: ['SessionState','MyInfoState'] }), 
```
Is is possible that  remove `NgxsStoragePluginModule.forRoot({ key: ['SessionState'] })`   from `core.module.ts`  
and add it  in angular application's `app.module.ts`,so that i can use NgxsStoragePluginModule to save my state?

**Comment by hikalkan** [comment]
@mehmet-erim can you comment on this?

**Comment by mehmet-erim** [comment]
Hi @ChangYinShung

We may not remove NgxsStoragePluginModule from CoreModule. But we will fix the problem.

Thanks for the information.

**Comment by mehmet-erim** [comment]
Hi @ChangYinShung

See the [PR comment](https://github.com/abpframework/abp/pull/5060#issue-467939259) to learn how to pass custom NgxsStoragePlugin options to CoreModule.

Thanks for reporting.

**Comment by ChangYinShung** [comment]
@mehmet-erim  thanks
