### ISSUE TITLE
The Cover Image field is required although it is not marked with an *

### ISSUE THREAD

**Issue by 1d0n7kn0w** [abpframework/abp#4848]
ABP Framework version : 3.0.4
User Interface : MVC

When I submit a new post, the cover image is required but it's not marked with an *

![coverImageRequired](https://user-images.githubusercontent.com/3910210/88206539-52f84200-cc46-11ea-9c9a-2ea269d6a7dc.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/4765#issuecomment-659114944

**Comment by 1d0n7kn0w** [comment]
that's not the issue, in my case i didn't upload any image
the problem is the image filed is not marked as required (in the UI) but when I submit i get the popup
the solution is just to add * after Cover Image
