### ISSUE TITLE
BlogFileOptions.FileUploadLocalFolder is null by default

### ISSUE THREAD

**Issue by 1d0n7kn0w** [abpframework/abp#4850]
ABP Framework version : 3.0.4
User Interface : MVC

I suggest to add this method :
`        private void ConfigureBlogging(IWebHostEnvironment hostingEnvironment)
        {
	        Configure<BlogFileOptions>(options =>
	        {
		        options.FileUploadLocalFolder = Path.Combine(hostingEnvironment.WebRootPath, "files");
	        });
        }`

And call it in the ConfigureServices method when we add the module blogging because that's not trivial

**Comment by maliming** [comment]
hi 1d0n7kn0w 

I think use blob storing in blog module is better.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/4879
