### ISSUE TITLE
Generated service proxies lack route params on GET requests

### ISSUE THREAD

**Issue by haivp3010** [abpframework/abp#4853]
**ABP Framework version**: 3.0.4
**User Interface**: Angular

For example, with a controller method like this:
```c#
[HttpGet]
[Route("{groupId}/users")]
public Task<PagedResultDto<GroupDto>> GetUsers(Guid groupId, PagedResultRequestDto request)
{
    return groupAppService.GetUsers(groupId, request);
}
```

What I get using `abp generate-proxy` is:
```ts
getUsersByGroupIdAndRequest(params = {} as PagedResultRequestDto): Observable<PagedResultDto<UserDto>> {
   return this.restService.request({ url: `/api/v1/groups/${groupId}/users`, method: 'GET', params },{ apiName: this.apiName });
}
```

The generated typescript method is lacking argument `groupId` in its signature, causing it to fail to compile.

Also, I notice that on other requests that are working, the arguments in method signature seem to be reversed in order while the output from `/api/abp/api-definition?IncludeTypes=true` is reflecting the correct order from the API

**Comment by maliming** [comment]
hi @haivp3010 

I think a single parameter doesn't have this problem, right? 
eg: `GetUsers(Guid groupId)` or `GetUsers(PagedResultRequestDto request)`

**Comment by haivp3010** [comment]
Hi @maliming 
Yes a single parameter doesn't have this problem. And other similar requests other than GET like PUT, POST,  etc. are fine too.

**Comment by maliming** [comment]
hi @erolarkat  
I can't understand some logic of `generate-proxy`, Can you check this problem?

**Comment by hikalkan** [comment]
We are already changing this feature. Follow https://github.com/abpframework/abp/issues/4881
