### ISSUE TITLE
how support dbfirst???

### ISSUE THREAD

**Issue by heyuquan** [abpframework/abp#4866]
community have any method to support abp dbfirst??
have any generate entity template for abp?

**Comment by maliming** [comment]
Maybe you should ask from [EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore)

**Comment by hikalkan** [comment]
We don't provide any solution for dbfirst. you can search on the web. if you find anything on the abp side that prevents it, we would be glad to help you.
