### ISSUE TITLE
Tenant Switch box not working in production

### ISSUE THREAD

**Issue by Znow** [abpframework/abp#4875]
Hi

Based on my previous issue I have enabled so I can use the Tenant switch box, even if the app is deployed to Azure.

1. Click on "switch"
2. Enter valid Tenant
3. Click Save
4. Tenant name should be filled out in box, but is not
5. Cookie for "__tenant" with valid value is created

Below is the overriden account layout file, to show the tenant switch box

```html
<body class="abp-account-layout bg-light @rtl">
    @await Component.InvokeLayoutHookAsync(LayoutHooks.Body.First, StandardLayouts.Account)

    @(await Component.InvokeAsync<MainNavbarViewComponent>())

    <div class="@containerClass">
        <abp-row>
            <abp-column class="col mx-auto" style="max-width: 440px">
                @* BUG HERE *@
                @if (MultiTenancyOptions.Value.IsEnabled /*&&
             (TenantResolveResultAccessor.Result?.AppliedResolvers?.Contains(DomainTenantResolveContributor.ContributorName) == true)*/)
                {
                    <div class="card shadow-sm rounded mb-3">
                        <div class="card-body px-5">
                            <div class="row">
                                <div class="col">
                                    <span style="font-size: .8em;" class="text-uppercase text-muted">@MultiTenancyStringLocalizer["Tenant"]</span><br />
                                    <h6 class="m-0 d-inline-block">
                                        @if (CurrentTenant.Id == null)
                                        {
                                            <span>
                                                @MultiTenancyStringLocalizer["NotSelected"]
                                            </span>
                                        }
                                        else
                                        {
                                            <strong>@(CurrentTenant.Name ?? CurrentTenant.Id.Value.ToString())</strong>
                                        }
                                    </h6>
                                </div>
                                <div class="col-auto">
                                    <a id="AbpTenantSwitchLink" href="javascript:;" class="btn btn-sm mt-3 btn-outline-primary">@MultiTenancyStringLocalizer["Switch"]</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                else
                {

                    <div class="card shadow-sm rounded mb-3">
                        <div class="card-body px-5">
                            <div class="row">
                                <div class="col">
                                    <span style="font-size: .8em;" class="text-uppercase text-muted">@MultiTenancyStringLocalizer["Tenant"]</span><br />
                                    <h6 class="m-0 d-inline-block">
                                        @if (CurrentTenant.Id == null)
                                        {
                                            <span>
                                                @MultiTenancyStringLocalizer["NotSelected"]
                                            </span>
                                        }
                                        else
                                        {
                                            <strong>@(CurrentTenant.Name ?? CurrentTenant.Id.Value.ToString())</strong>
                                        }
                                    </h6>
                                </div>
                                <div class="col-auto">
                                    <a id="AbpTenantSwitchLink" href="javascript:;" class="btn btn-sm mt-3 btn-outline-primary">@MultiTenancyStringLocalizer["Switch"]</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                @(await Component.InvokeAsync<PageAlertsViewComponent>())
                @RenderBody()
            </abp-column>
        </abp-row>
    </div>

    <abp-script-bundle name="@BasicThemeBundles.Scripts.Global" />

    <script src="~/Abp/ApplicationConfigurationScript"></script>
    <script src="~/Abp/ServiceProxyScript"></script>

    @await RenderSectionAsync("scripts", false)

    @await Component.InvokeAsync(typeof(WidgetScriptsViewComponent))

    @await Component.InvokeLayoutHookAsync(LayoutHooks.Body.Last, StandardLayouts.Account)
</body>
```

Below is a screenshot showing the page with the cookie value, and the tenant not being shown in the switch box.

![image](https://user-images.githubusercontent.com/265719/88391481-8c51be80-cdba-11ea-8264-fd43db47c711.png)

Based on this, i am not able to log in to the tenant with an admin account.

This works as it should when developing locally.

Thanks

**Comment by liangshiw** [comment]
Do you use cookie tenant resolve?
Please provide a simple project to reproduce this problem.

**Comment by Znow** [comment]
@liangshiw Hmm, I haven't specific stated it anywhere in the code - so I cant answer that tbh.

I will create a project to try and reproduce

**Comment by Znow** [comment]
@liangshiw 
**Azure test website**: https://tenantswitchtestweb20200724182711.azurewebsites.net/Account/Login
_Login with standard abp credentials, I have created a "TestTenant" also._

**Github repository**: https://github.com/Znow/TenantSwitchTest

**Files modified/added:**

* TenantSwitchTestWebModule.cs
** Added domain tenant resolver, which seems to mess it up
* Views/Shared/_AccountLayout.cshtml
* Pages/Account/Login.cshtml

Example:

![tenantswitchtest](https://user-images.githubusercontent.com/265719/88416513-a7372980-cde0-11ea-845d-0395b35ec627.gif)

**Comment by maliming** [comment]
@Znow  Maybe you're not successful override the `Login.cshtml` page on production environment.

**Comment by Znow** [comment]
@maliming - how would I not be? Can't see how I should override else, beside the way I did already

**Comment by liangshiw** [comment]
Maybe this is a bug.


Set `Handled` value to `true` before determining whether it matches
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.AspNetCore.MultiTenancy/Volo/Abp/AspNetCore/MultiTenancy/DomainTenantResolveContributor.cs#L37

Since the `Handled` value is `true`, the subsequent tenant resolution provider is skipped
https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/TenantResolveContext.cs#L15

**Comment by Znow** [comment]
> Maybe this is a bug.
> 
> Set `Handled` value to `true` before determining whether it matches
> https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.AspNetCore.MultiTenancy/Volo/Abp/AspNetCore/MultiTenancy/DomainTenantResolveContributor.cs#L37
> 
> Since the `Handled` value is `true`, the subsequent tenant resolution provider is skipped
> https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/TenantResolveContext.cs#L15
> 
> @Znow You can try:
> 
> ```cs
> options.TenantResolvers.Add(new DomainTenantResolveContributor("your host"));
> ```
> 
> I'm not sure this is by design. @hikalkan What do you think?

How much different is that than the stuff that is in the code already? :)

```csharp
Configure<AbpTenantResolveOptions>(options =>
            {
                options.AddDomainTenantResolver($"{0}.tenantswitchtestweb20200724182711.azurewebsites.net/");
                //options.TenantResolvers.Add(new IdentityServerTenantResolveContributor());
            });
```

**Comment by liangshiw** [comment]
Use `options.TenantResolvers.Add(new DomainTenantResolveContributor("your host"));` will add `DomainTenantResolveContributor` to the end of the `TenantResolvers` list.
It will be executed at the last one and will not affect other tenant resolvers

**Comment by Znow** [comment]
@liangshiw Thanks a million! Seems to work just fine. The test site I provided can now fine change tenant, with domain tenant resolvers also applied - I will test further with subdomain and see if this still works.

**Comment by Znow** [comment]
@liangshiw The domain tenant resolver does still not seem to work.

I have added several subdomains as custom domain names to my Azure app service - so they are all valid. If I enter "X".somedomain.com where "X" is a valid created tenant in my application, nothing happens - the "__tenant" cookie is not being set, neither is the tenant switch box's value changed.

**Comment by liangshiw** [comment]
I think your code has woring.

Your domain should be `"{0}.subdomain.com"`  instead of `$"{0}.subdomain.com/"`

**Comment by Znow** [comment]
That was a typo, sorry

**Comment by maliming** [comment]
I think the `DomainTenantResolveContributor` is special. When it enabled you shouldn't use other contributions anymore. eg: cookie, header.

**Comment by Znow** [comment]
Sure, but it still does not seem to work with the domaintenantresolver...

**Comment by liangshiw** [comment]
I used you provided project, It works fine.  Please check your code.

![image](https://user-images.githubusercontent.com/16813853/88480279-b73d3d80-cf87-11ea-9615-19b623a217f8.png)

**Comment by Znow** [comment]
@liangshiw Have triple checked my code. 

When deploy on Azure, as a total reqular Azure App Service (Windows), it will not work.

The test website I created previously (https://tenantswitchtestweb20200724182711.azurewebsites.net), now have "http://tenant1.znow.dk" as CNAME.

![image](https://user-images.githubusercontent.com/265719/88481763-97911f80-cf5d-11ea-84fc-0a01c1c36890.png)

With the below code, it still does not work

```csharp
public override void ConfigureServices(ServiceConfigurationContext context)
        {
            var hostingEnvironment = context.Services.GetHostingEnvironment();
            var configuration = context.Services.GetConfiguration();

            ConfigureUrls(configuration);
            ConfigureAuthentication(context, configuration);
            ConfigureAutoMapper();
            ConfigureVirtualFileSystem(hostingEnvironment);
            ConfigureLocalizationServices();
            ConfigureNavigationServices();
            ConfigureAutoApiControllers();
            ConfigureSwaggerServices(context.Services);

            //if (!hostingEnvironment.IsDevelopment())
            //{
                ConfigureTenantResolver();
            //}
        }

        private void ConfigureTenantResolver()
        {
            Configure<AbpTenantResolveOptions>(options =>
            {
                options.TenantResolvers.Add(new DomainTenantResolveContributor($"{0}.znow.dk"));
                //options.TenantResolvers.Add(new IdentityServerTenantResolveContributor());
            });
        }
```
Tenant:
![image](https://user-images.githubusercontent.com/265719/88481802-d6bf7080-cf5d-11ea-98bf-fc350f65d460.png)

Example:

![tenantswitchtest1](https://user-images.githubusercontent.com/265719/88481995-decbe000-cf5e-11ea-9352-1939239cdf33.gif)

**Comment by liangshiw** [comment]
I already told you.

> Domain should be `"{0}.subdomain.com"`  instead of `$"{0}.subdomain.com/"`

![image](https://user-images.githubusercontent.com/16813853/88482232-8b738500-cf92-11ea-952b-4296f6aed735.png)

**Comment by Znow** [comment]
No need to harsh :)

Honest mistake that I didn't see that one, I am very sorry... I just looked at the trailing slash.

Thanks alot for your help, really appreciate it.
