### ISSUE TITLE
"Options" on a document can be a problem for search engines

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4877]
They probably can not index such documents: https://docs.abp.io/en/abp/latest/Tutorials/Part-1?UI=NG&DB=EF
Because there is no link on the web site, but we switch option & refresh page by JavaScript.

You can take support from @armgnunlu

**Comment by yekalkan** [comment]
We already add links of all possible combinations at the bottom of the article, when doc is visited by a web crawler.

See https://github.com/abpframework/abp/blob/7ee6692a52f297a3954f9e3c75c31ea633c6802b/modules/docs/src/Volo.Docs.Web/Pages/Documents/Project/index.js#L240

Do you suspect that it doesn't work?
