### ISSUE TITLE
Want to increase the Api IBlobContainer CreateContainerIfNotExistsAsync

### ISSUE THREAD

**Issue by colinin** [abpframework/abp#4878]
Although can define an extension by referring to a specific **BlobContainerProvider**, providing this interface would be more efficient, what do you think

**Comment by colinin** [comment]
This interface is for BLOB Storage only, and it looks like another interface is needed to implement this functionality

**Comment by hikalkan** [comment]
I think "Creating the container if not exists" should be default when I call Container.Save. A code that wants to save a BLOB should not be responsible to create the container or check if it does exists.

**Comment by colinin** [comment]
Sometimes I just want to create a container, although I don't know how many such scenarios there are. Currently, this can be achieved by creating an empty file and deleting it.
