### ISSUE TITLE
Blog posts filter by tagName return all posts if the tag does't exist

### ISSUE THREAD

**Issue by zhchlmm** [abpframework/abp#4880]
*  **ABP Vesion** v3.0.4
*  **User Interface**  MVC

**Comment by maliming** [comment]
@yekalkan What do you think?

https://github.com/abpframework/abp/blob/8cd6d83f51aadf1f43d007880698f39ad3d7ae8d/modules/blogging/src/Volo.Blogging.Application/Volo/Blogging/Posts/PostAppService.cs#L30-L35

**Comment by yekalkan** [comment]
@maliming I probabaly thought it is better to show all posts rather than displaying nothing or whrowing exception. I am not sure which is the best way.

Btw, there is an issue which suggests a complete separate page for tag filtering https://github.com/abpframework/abp/issues/3438
