### ISSUE TITLE
The default language setting is ineffective with Volo.Docs module

### ISSUE THREAD

**Issue by zhchlmm** [abpframework/abp#4895]
* **ABP Framework version** v3.0.4.
* **User Interface**  MVC

I add the following setting in the `appsettings.json` to set the default language, and it has no problem.    
```json
  "Settings": {
    "Abp.Localization.DefaultLanguage": "zh-Hans"
   }
```
   
When i navigate to `/documents/docProject1` , it will be redirected to  `/documents/en/docProject1/latest`,  the defualt language is not the value setted in the `appsettings.json`, but in the  [docs-langs.json](https://github.com/abpframework/abp/blob/dev/docs/docs-langs.json) .

**Comment by liangshiw** [comment]
The docs module does not use this setting, you can set zh-Hans's `IsDefault`  to true in `docs-langs.json` file.
