### ISSUE TITLE
Register page throw exception if the user name or email has been taken

### ISSUE THREAD

**Issue by taujiong** [abpframework/abp#4896]
* ABP Vesion: v3.0.4
* User Interface: Mvc for sure, others not test
* Step to reproduce: go to the default register page and type "admin" for username, "admin@abp.io" for email and anything for password, it goes to the exception page.

The code [here](https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Register.cshtml.cs#L56) should be surrounded by a try catch since the controller can issue the exception correctly while the page fails.

**Comment by maliming** [comment]
Please share a screenshot of the exception.

**Comment by taujiong** [comment]
The exception page is shown below
![image](https://user-images.githubusercontent.com/52844763/88553758-37cb6f00-d058-11ea-8c6d-37fa6c9f45cd.png)

and the supposed action should like below
![image](https://user-images.githubusercontent.com/52844763/88554100-a90b2200-d058-11ea-9b6e-6e8af8cf8b13.png)
