### ISSUE TITLE
application-configuration 500

### ISSUE THREAD

**Issue by zorc** [abpframework/abp#4900]
### Documentation

I have checked the official documentation in [https://docs.abp.io/en/abp/latest/Getting-Started?UI=NG&DB=Mongo&Tiered=Yes](https://docs.abp.io/en/abp/latest/Getting-Started?UI=NG&DB=Mongo&Tiered=Yes)

### GitHub Issues

My ABP Framework version:3.0.4 | Angular | MongoDB | Tiered

Step to 《Running the Angular application (client-side)》

https://localhost:44375/ and https://localhost:44354/swagger/index.html work fine

but http://localhost:4200/ response is：
{"error":{"code":null,"message":"An internal error occurred during your request!","details":null,"validationErrors":null}}

I tried rebuild all,but things have not changed

Request:
Request URL: https://localhost:44354/api/abp/application-configuration
Request Method: GET
Status Code: 500 
Remote Address: [::1]:44354
Referrer Policy: no-referrer-when-downgrade

Response header：
_abperrorformat: true
access-control-allow-credentials: true
access-control-allow-origin: http://localhost:4200
access-control-expose-headers: _AbpErrorFormat
content-length: 122
content-type: application/json; charset=utf-8
date: Tue, 28 Jul 2020 07:00:12 GMT
server: Microsoft-IIS/10.0
status: 500
vary: Origin
x-powered-by: ASP.NET

Request header：
:authority: localhost:44354
:method: GET
:path: /api/abp/application-configuration
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImFjMGQyZWRmM2MwNGQxM2NkOTVjYzQxYjliMzNhYjAzIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE1OTU5MTk2MTIsImV4cCI6MTYyNzQ1NTYxMiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNzUiLCJhdWQiOiJCb29rU3RvcmUiLCJjbGllbnRfaWQiOiJCb29rU3RvcmVfQXBwIiwic3ViIjoiOTUyNmNjNWQtMWE3Ny0xMjhlLTUyMGEtMzlmNmExZjRkMmMzIiwiYXV0aF90aW1lIjoxNTk1OTE5NjEyLCJpZHAiOiJsb2NhbCIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWJwLmlvIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJzY29wZSI6WyJCb29rU3RvcmUiXSwiYW1yIjpbInB3ZCJdfQ.j82sx8EgfqrTlaaUfKi-i2LgPu9AV3GtF5wogxSiQcg-4lwWvtwc8CaRsr_ruMARTRrHWq-fHQSUt4vomE5sQ4bOJvIYdWMm8JpT3yvXQmaUdfpNWQo8G6e_ymEEKGHk7H49Q7BYB0fZFlYAz8YmFB5cbbzK_1wWU1RGW9K5A1Ph6qZcPAqAhL1lVXdx3NxN5OWl0YDuJvQTwIrhnzSfO09g5vkIoptygZTzoZ_lM8zCiK-vuxYDff-mSLczJHtNMOfkeIySVxxvFgCDWGkwD8WsT4cv4VG-pJih83F_mnPGDdYD6QneLRqOt9frGEB0pNwcUlKmzJdGDk8ujvMTwA
origin: http://localhost:4200
referer: http://localhost:4200/account/login
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by maliming** [comment]
> An internal error occurred during your request!

Please check your application logs.

**Comment by zorc** [comment]
> > An internal error occurred during your request!
> 
> Please check your application logs.

Thank you ! It's ok now.
