### ISSUE TITLE
What are the best practices for implementing micro-services with 'ABP'?

### ISSUE THREAD

**Issue by cocosip** [abpframework/abp#4903]
We tried to use the ABP framework to implement the microservice architecture related to our business ,but we found that ABP lacks some related components. such as : **Service Registry**, **Service Discovery**, **Loadbalancer** 。
Is there any plan for this? Or my understanding is somewhat biased?

**Comment by liangshiw** [comment]
This has nothing to do with ABP.

If you are use k8s, these are built-in. 
See https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/
