### ISSUE TITLE
UI - How to create a custom bootstrap theme using sass

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#4913]
Hey,

I'm working on a custom bootstrap theme. Since the theming docs aren't written yet, maybe you guys can assist me a little bit here.

* **ABP Framework version**: 3.0.4
* **User Interface** type: MVC

I understood the client side depdendency management stuff in the docs, but how would you define multiple styles, like in the lepton theme by using scss-files?

The main issue I'm currently facing is the import of bootstrap's scss files. My goal is to make use of the WebCompiler extension to modify the scss files on-the-fly.

My approach was to create a custom theme project. This project serves as my template with different styles.
For example, I created a `wwwroot/themes/mytheme/styles/style1.scss`-file. Now I need to import the bootstrap scss files.
One way to solve this issue would be to manually import the bootstrap scss files and import them. In this case I have to remove the bootstrap.css in my Style contributor before adding my individually compiled bootstrap css.

Is this way correct and what do you recommend?

**Comment by hikalkan** [comment]
Hi @NecatiMeral I think this is not related to the theme system of the ABP Framework, but theme development in general. I personally don't have a good experience with csss, web compiler, includes, build, multiple output... etc. You should do it yourself :(
