### ISSUE TITLE
A  minor improvement to the tutorial

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#4916]
A small improvement to the otherwise excellent tutorial. 

In the step "Web Application Development Tutorial - Part 8: Authors: Application Layer" (MVC/RP - EF) Authors are added to the seed in code but there is no instruction to actually run the Acme.BookStore.DbMigrator so the data displayed in the next step (step 9) won't actually be in the database. Not sure if this is on purpose to make sure people completed the previous steps in the tutorial though :)

Thanks.

**Comment by liangshiw** [comment]
You are right, I will update the document. Thanks.
