### ISSUE TITLE
Upgrade Automapper to v10.0

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#4918]
https://github.com/AutoMapper/AutoMapper/releases/tag/v10.0.0
https://docs.automapper.org/en/latest/10.0-Upgrade-Guide.html

**Comment by hikalkan** [comment]
@maliming why are you waiting for a PR: https://github.com/abpframework/abp/compare/maliming/automapper-10 ?
Is there any breaking change may effect the applications? I see https://docs.automapper.org/en/latest/10.0-Upgrade-Guide.html which has some changes and they are not so breaking changes.

**Comment by maliming** [comment]
At the time I was waiting for a customer’s feedback and then forgot to open the PR. I already updated in **aspnetboilerplate**.

https://github.com/abpframework/abp/pull/5004
