### ISSUE TITLE
ValueObject Migrations Error

### ISSUE THREAD

**Issue by helloxubo** [abpframework/abp#4919]
* Your **ABP Framework version**.
3.0.4
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
no
* Exception message and **stack trace** if available (check the logs).
no
* Steps needed to **reproduce** the problem.
no

     An ValueObject 'StreetAddress' ,When i use AbpDbContext<> migrations occurs an error "The type 'StreetAddress' cannot be marked as owned because a non-owned entity type with the same name already exists."; but ues microsoft Dbcontext is rigth.
     Use atrribute  [Owned] on 'StreetAddress' ,migration is right, but use IRepository<StreetAddress> has the same problem.
     Like the following codes:

```csharp
    public class StreetAddress
    {
        public string Street { get; set; }
        public string City { get; set; }
    }

    public class Order
    {
        public int Id { get; set; }
        public StreetAddress ShippingAddress { get; set; }
    }

    public class OrderDbContext : AbpDbContext<OrderDbContext>
    {
        public DbSet<Order> Orders { get; set; }
        public OrderDbContext(DbContextOptions<OrderDbContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Order>(b =>
            {
                b.ToTable("Orders")
                .OwnsOne(x => x.ShippingAddress).WithOwner();
            });
        }
    }
```

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/search?q=cannot+be+marked+as+owned+because+a+non-owned+entity+type+with+the+same+name+already+exists.&type=Issues

**Comment by helloxubo** [comment]
Reply so fast!
think you .
