### ISSUE TITLE
Permission Manager Doesn't set User Permission

### ISSUE THREAD

**Issue by davesimtech** [abpframework/abp#4938]
ABP Framework Version: 3.0.5
UI: React

There seems to be an issue when trying to set permissions at a user level (using SetForUserAsync). 

Set up some simple permissions:

```
    public class ApplicationPermissionDefinitionProvider : PermissionDefinitionProvider
    {
        public override void Define(IPermissionDefinitionContext context)
        {
            //Define your own permissions here. Example:
            //myGroup.AddPermission(ApplicationPermissions.MyPermission1, L("Permission:MyPermission1"));

            var clientGroup = context.AddGroup(PermissionGroup.Client);

            clientGroup.AddPermission(ApplicationPermissions.Client_Create);
            clientGroup.AddPermission(ApplicationPermissions.Client_Edit);
            clientGroup.AddPermission(ApplicationPermissions.Client_View);
            clientGroup.AddPermission(ApplicationPermissions.Client_ViewFinance);
	}
    }
```

Inject the IPermissionManager as follows:

```
        public UserAppService(
            IRepository<AppUser, Guid> userRepository,
            IPermissionManager permissionManager)
            : base(userRepository)
        {
            _userRepository = userRepository;
            _permissionManager = permissionManager;
        }
```

then setting the permission as follows:

`await _permissionManager.SetForUserAsync(id, permission.Name, permission.IsGranted);`

There are no rows created in the [AbpPermissionGrants] table and there are also no errors/exceptions thrown.

**Comment by maliming** [comment]
hi

What are the steps to **reproduce** the problem? Is there anything in the logs file?

**Comment by davesimtech** [comment]
Hello,

I've created a project that reproduces the problem: https://github.com/davesimtech/abp_user_permission

1. I basically created a project using the 'direct download' on https://abp.io/get-started
2. Setup my permissions in TestProjectPermissions.cs and TestProjectPermissionDefinitionProvider.cs
3. Created a simple appservice that has a method that sets permissions, and a method to test each permission (TestAppService.cs)
4. Call the method to set the permission for a user e.g. 
            `await _permissionManager.SetForUserAsync(userId, TestProjectPermissions.Client_Create, true);`
5. No new rows created in the database

There aren't any errors in the logs, it just runs and no matching rows are created in the AbpPermissionGrants table.

**Comment by maliming** [comment]
Unable to reproduce.

![image](https://user-images.githubusercontent.com/6908465/89142620-81e1b280-d57a-11ea-8ad7-b5902493e220.png)

**Comment by davesimtech** [comment]
Thanks for investigating this for me. Your screenshot has helped me figure out what the issue was:

The role the user was assigned to already had certain permissions, you can't then customise the users individual permissions if they are already assigned to that role.

E.g. Admin role has Client_Create, Client_Edit, Client_View, Client_ViewFinance. If you then set the user to the admin role but want to customise so that they no longer have Client_Edit - they essentially need to be removed from the admin role and have the individual permissions assigned to them.

**Comment by maliming** [comment]
This is by design.
