### ISSUE TITLE
Hangfire dashboard via Ocelot

### ISSUE THREAD

**Issue by pmjaleel** [abpframework/abp#4939]
We are using your API service. UI is in Angular version.

There is Ocelot to access the UI and API. While trying to access the Hangfire dashboard, we are not getting it displayed. Is there an approach to integrate the Hangfire Dashboard from the UI via Ocelot?

**Comment by maliming** [comment]
hi

I think this has nothing to do with abp.

**Comment by pmjaleel** [comment]
> hi
> 
> I think this has nothing to do with abp.

In the Microservice architecture example, if you look at the diagram of ABP, it has Ocelot as API gateway. All the API service of ABP has hangfire component. If so how is the dashboard of Hangfire of each microservice being accessed? Yes it is has something to do with ABP . I am checking if there is any solution on this.

**Comment by hikalkan** [comment]
If you have multiple services and multiple UIs, I think it is better to create a new UI application that includes the HangFire dashboard. I don't know if hangfire allows tiered architecture (where UI and API are separated and the API can be located behind a gateway). If not, you have no chance, it will directly access to the database.

In this design, you typically have a single hangfire job executer where each service may add tasks to the database.

I also think that this is unrelated to the ABP Framework at all.

**Comment by pmjaleel** [comment]
> If you have multiple services and multiple UIs, I think it is better to create a new UI application that includes the HangFire dashboard. I don't know if hangfire allows tiered architecture (where UI and API are separated and the API can be located behind a gateway). If not, you have no chance, it will directly access to the database.
> 
> In this design, you typically have a single hangfire job executer where each service may add tasks to the database.
> 
> I also think that this is unrelated to the ABP Framework at all.

Hi ,

I agree that it is not completely an ABP issue. But if you look at the link below: which is what we are using,

https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo

The services are behind the Front End gateway developed via Ocelot. In this scenario, we will not get the dashboard. Hence my question was was there any solution being recommended? So in a way, this issue can be related to ABP partially. I was looking for recommendation. 

We have decided to build our own UI for the Hangfire rather than consuming theirs. 
This could help ABP in micro service architecture. Once complete we will update

**Comment by hikalkan** [comment]
Don't expect everything from the microservice demo, it shows an overall design. Hangfire is a 3rd-party library with its own features and limitations.

I don't have experience on that and suggesting a good design requires to spend some time on it. If you find a good design, please share with the community.
