### ISSUE TITLE
QuartzBackgroundWorkerManager is not works fine for take over DefaultBackgroundJobManager

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#4945]
@realLiangshiwei Hi:
I created a [branch ](https://github.com/yinchang0626/abp-samples/commit/b4766dae610ee23cd047a9d071a2a7f9738f485d)to descript it:
1.create a `AsyncBackgroundJob` EmailSendingJob
```csharp
    public class EmailSendingJob : AsyncBackgroundJob<EmailSendingArgs>, ITransientDependency
    {
        public override async System.Threading.Tasks.Task ExecuteAsync(EmailSendingArgs args)
        {
            System.Threading.Thread.Sleep(args.SpendTime);//simulation long time job
            Console.WriteLine("Task completed");//when AbpBackgroundWorkersQuartzModule enable,long time job wiil be executed twice
        }
    }
```
2.test it in a appservice
```csharp
    public class JobAppService : Volo.Abp.Application.Services.ApplicationService, IJobAppService
    {
        public Volo.Abp.BackgroundJobs.IBackgroundJobManager BackgroundJobManager { get; set; }
        public async Task EnqueueJobAsync(int spendTime)
        {
            await BackgroundJobManager.EnqueueAsync(
                new EmailSendingArgs
                {
                    EmailAddress = "",
                    Subject = "You've successfully registered!",
                    Body = "0",
                    SpendTime = spendTime
                });
        }
    }
```
If `AbpBackgroundWorkersQuartzModule` didn't [enable](https://github.com/yinchang0626/abp-samples/blob/b4766dae610ee23cd047a9d071a2a7f9738f485d/BookStore/src/Acme.BookStore.Web/BookStoreWebModule.cs#L44),whether `spendTime` is long time or not,It works fine,
but when `AbpBackgroundWorkersQuartzModule` enabled and `spendTime` is more than 5 seconds,this job will execute twice or more times,
I thinks this question is related to `QuartzPeriodicBackgroundWorkerAdapter`?
Maybe cause by timeout of `Quartz`?
Could you help me to check it? thanks.

**Comment by realLiangshiwei** [comment]
I will check it out.

**Comment by realLiangshiwei** [comment]
Because the `AsyncPeriodicBackgroundWorkerBase` use timer. it will block method execution. but quartz will not. It will check the pending job every 5 seconds
So, if you are using quartz as background worker integration, you need also use the quartz background job integration or hangfire background job integration.
