### ISSUE TITLE
custom response result

### ISSUE THREAD

**Issue by Aoqin** [abpframework/abp#4951]
How can i get a custom  response result？
such as a JSON result，
```javascript
{
  status: 200, 
  // http status is 200  include exception always.
  data: {  
    code: 2000,  
    data: {  
      userInfo: {}  
    },  
    status: true,  
    message: 'success'  
  }  
}
```
i can use exceptionFilter and resultFilter in net core, but i cant find an Function in offcial documents excitpt  AbpExceptionFilter

**Comment by maliming** [comment]
There is no document you can check the source code and unit tests.
