### ISSUE TITLE
When I create a role with extraProperties,the was no data in the field extraProperties of db's AbpRole.

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#4953]
When I create a role with extraProperties,the was no data in the field extraProperties of db's AbpRole.Below is the reason:
![image](https://user-images.githubusercontent.com/57399417/89264801-1ffe7700-d666-11ea-8e03-ff6bb4cc71e0.png)
![image](https://user-images.githubusercontent.com/57399417/89264850-34427400-d666-11ea-80c2-6891cc8bc209.png)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by abllyboy** [comment]
ABP Version is 3.0.4,UI is VUE. You can see the input params's extraProperties has tow items. After exec 'input.MapExtraPropertiesTo(role)' ,the role's extraProperties also has zero item.

**Comment by xyfy** [comment]
Do you use `XXXApplicationObjectExtensions` to define the property?

like below 
``` C#
                ObjectExtensionManager.Instance
                .AddOrUpdateProperty<string>(
                    new[]
                    {
                        typeof(ProfileDto),
                        typeof(IdentityUser),
                        typeof(UpdateProfileDto),
                    },
                    AppUser.Tel,
                    options =>
                    {
                        options.Validators.Add(context =>
                        {
                            var val = context.Value as string;
                            if (val != null && val.Length > LengthConsts.MaxLength16)
                            {
                                context.ValidationErrors.Add(
                                    new ValidationResult(
                                        "电话号码长度超过限制: " + val,
                                        new[] { AppUser.Tel }
                                        )
                                    );
                            }
                        });
                    });`
```

**Comment by abllyboy** [comment]
![image](https://user-images.githubusercontent.com/57399417/89988229-ce7f6900-dcb1-11ea-82db-047a8229d9a0.png)
The Create or Update Role's API is this ths same as the commercial. I didn't add or modify anything.

**Comment by xyfy** [comment]
pleease follow `Extending Data Transfer Objects` in  this doc
https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#extending-data-transfer-objects%EF%BC%89

**Comment by xyfy** [comment]
MapExtraPropertiesTo requires to define properties (as described above) in both sides (IdentityUser and IdentityUserDto in this case) in order to copy the value to the target object. Otherwise, it doesn't copy the value even if it does exists in the source object (identityUser in this example). There are some ways to overload this restriction.

https://docs.abp.io/en/abp/latest/Object-Extensions#mapextrapropertiesto

**Comment by abllyboy** [comment]
ths, now I use other ways to deal this. I just  hope abp to fix this issue.
