### ISSUE TITLE
Error occurs when setting developmentMode in ngxs config to true

### ISSUE THREAD

**Issue by jimmidier** [abpframework/abp#4958]
In the angular app, after setting developmentMode to true in `NgxsModule.forRoot()`, error occurs.

![typeerror](https://user-images.githubusercontent.com/16027480/89319660-00417000-d6b3-11ea-9479-44923663ef39.PNG)

Steps to reproduce:

1. Create a template project from abp cli with angular ui
2. In the `app.module.ts` file, make changes:
```
import ...

@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    CoreModule.forRoot({
      environment,
    }),
    ThemeSharedModule.forRoot(),
    AccountConfigModule.forRoot(),
    IdentityConfigModule.forRoot(),
    TenantManagementConfigModule.forRoot(),
    SettingManagementConfigModule.forRoot(),
    // change here, or simply set to true
    NgxsModule.forRoot([], {
      developmentMode: !environment.production
    }),
    ThemeBasicModule.forRoot(),
  ],
  declarations: [AppComponent],
  providers: [APP_ROUTE_PROVIDER],
  bootstrap: [AppComponent],
})
export class AppModule { }
```
3. set proper environments, compile and open in browser and see the errors
(I already had a proper server running so just skip the backend part here and I believe that these errors have nothing to do with backend APIs or dbs)
4. setting developmentMode back to false will make everything normal again

I made this change because I was following ngxs's docs
https://www.ngxs.io/getting-started/installation

After some debugging I found that 
1. The errors occur during theme styles initialization, when three `AddReplaceableComponent` actions are dispatched:
```
(styles.provider.ts)

function initLayouts(store: Store) {
  store.dispatch([
    new AddReplaceableComponent({
      key: eThemeBasicComponents.ApplicationLayout,
      component: ApplicationLayoutComponent,
    }),
    new AddReplaceableComponent({
      key: eThemeBasicComponents.AccountLayout,
      component: AccountLayoutComponent,
    }),
    new AddReplaceableComponent({
      key: eThemeBasicComponents.EmptyLayout,
      component: EmptyLayoutComponent,
    }),
  ]);
```
2. When `ReplaceableComponentsState` receives the actions, ngxs deep freezes new states at subsequent calls to `patchState` because `developmentMode` is set to true.
3. When deep freezing `ReplaceableComponentsState`'s value, `SubscriptionService` type gets freezed during the recurse because it is injected in the `ApplicationLayoutComponent`, and that's when the first error occurs because the `isClosed` getter of `SubscriptionService` is called without calling ctor.
4. When rendering `AppComponent`, `SubscriptionService` type is somehow modified by angular because it is injected as a class provider in the `LoaderBarComponent`, that's when the next two errors occur.

To make it short, using component types as part of the state model seems to be against ngxs's 'immutability' paradigm.

I'm not so good at angular and I can't think of any solutions without breaking existing designs. 
Should we consider this an issue or just leave it as an antipattern design?

**Comment by armanozak** [comment]
Hi @jimmidier,

Thank you for the feedback and detailed analysis of the matter.

When `developmentMode` is turned on, as you have described, NGXS starts deep freezing every state in store, including replaceable components. Unfortunately, NGXS freezes everything and provides no way to exclude state slices from that.

Can we consider keeping a constructor in application state an anti-pattern? Maybe. 🤷 All I am sure about is, the `developmentMode` option would have been much more useful if there was a way of defining exclusions.

Anyway. Removing `SubscriptionService` will not fix the problem, because there will still be no way to set frozen properties which, obviously, would make instances useless (and throw errors). So, there is no quick solution to this.

On the other hand, we are gradually removing NGXS from ABP frontend and will be transforming all NGXS states into plain Angular services. This will be obsolete when the transition is complete, so let's leave it as an anti-pattern for now.

Thanks again.

Have a beautiful day.

**Comment by jimmidier** [comment]
> Hi @jimmidier,
> 
> Thank you for the feedback and detailed analysis of the matter.
> 
> When `developmentMode` is turned on, as you have described, NGXS starts deep freezing every state in store, including replaceable components. Unfortunately, NGXS freezes everything and provides no way to exclude state slices from that.
> 
> Can we consider keeping a constructor in application state an anti-pattern? Maybe. 🤷 All I am sure about is, the `developmentMode` option would have been much more useful if there was a way of defining exclusions.
> 
> Anyway. Removing `SubscriptionService` will not fix the problem, because there will still be no way to set frozen properties which, obviously, would make instances useless (and throw errors). So, there is no quick solution to this.
> 
> On the other hand, we are gradually removing NGXS from ABP frontend and will be transforming all NGXS states into plain Angular services. This will be obsolete when the transition is complete, so let's leave it as an anti-pattern for now.
> 
> Thanks again.
> 
> Have a beautiful day.

Thanks for the explanation.
But if we ignore it, will there be any influence on performance or change detection?

**Comment by armanozak** [comment]
The states in ABP packages are fine in terms of performance and change detection. However, since they cannot use the developmentMode, developers are not able to check immutability of their NGXS states and can make a mistake that causes change detection issues. Therefore, this will be the first part we will transform into a service.

**Comment by jimmidier** [comment]
Thanks for your answer. Looking forward to the future features.
I think I can close this issue now.

**Comment by sebitsi** [comment]
@armanozak 

> On the other hand, we are gradually removing NGXS from ABP frontend and will be transforming all NGXS states into plain Angular services. This will be obsolete when the transition is complete, so let's leave it as an anti-pattern for now.

Can you please explain why you decide to remove ngsx and put all states to services ?

Related: #4254

**Comment by armanozak** [comment]
Hi @sebitsi,

We want to remove dependency to a specific state management library and let ABP developers choose their own state management library.

Have a nice day.

**Comment by sebitsi** [comment]
@armanozak 
Thanks for fast response. 

What exactly this decision mean for me as developer ?
Will you create some base (generic) servicec, selectors etc. to support state management or selecting and using some state management is on us ?

**Comment by armanozak** [comment]
Once we finish the transition, singleton services will provide methods and properties to select state slices and change state safely. You will simply inject services and use their methods and properties to manage application state.

You will not need to, but you will be able to use any state management library you choose together with our services.

**Comment by sebitsi** [comment]
Sorry my question wasn't well defined.

After you finished transition and remove ngxs dependency will there be some infrastructure to support our states ?
Like IObjectMapper as infrastrucure and automapper as implementation of that infrastructure ?

It will be nice if we decide to replace ngsx with services as you do, to use same base classes as your code will.
