### ISSUE TITLE
How to call a "Get" RESTful service with parameters of "IEnumarable<int>" from HttpAip.Client?

### ISSUE THREAD

**Issue by BrianCodeman** [abpframework/abp#4969]
### Use Case
I have a scenario like this: Users supply a bunch of Id and suppose to get relative entitiesDto by calling a HttpAip.Client method like :

```
IEnumerable<int> ids = UserSuppliedIdsSomewhere();
IEnumerable<MyTypeDto> dto = await _myAppService.GetCustomListAsync(ids);
```

and the signature of GetCustomListAsync method is:

`Task<IEnumerable<MyTypeDto>> GetDetailListAsync(IEnumerable<int> ids);`

### Issue
The operation above will cause an exception since the IEnumerable<int> argument couldn't bind to  parameter properly. However, if I try this Api from swagger, everything is fine, and the argument will be serialized to querystring of url. So I doubt the HttpAip.Client failed to form proper querystring. My temporary solution is to change my api to Post by attribute [HttpPost], which will force the api to get data from request body.

### Question
Could you team supply a guide to me about solving the problem? After all, changing a Get behavior to Post is weird, and retrieving a collection of entities by there ids is such a common use case.

Thank you so much.

**Comment by maliming** [comment]
Hi

* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by BrianCodeman** [comment]
- My ABP Framework version: 3.0.0
- Exception message and stack trace:

> Volo.Abp.Http.Client.AbpRemoteCallException:
> 
> **Message**:
> Your request is not valid!
> 
> **Details**:
> The following errors were detected during validation.
>  - The value 'System.Collections.Generic.List`1[System.Int32]' is not valid.
> 
> **Source**:
> Volo.Abp.Http.Client
> 
> **Stack Trace**:
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAndGetResultAsync[T](IAbpMethodInvocation invocation)
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetResultAsync(Task task, Type resultType)
>    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
>    at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
>    at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
>    at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
>    at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
>    at Taurus.Blazor.Pages.TranscriptManagement.Export.OnExportClick() in D:\Taurus\aspnet-core\src\Taurus.Blazor\Pages\TranscriptManagement\Export.razor:line 21

>**Taurus.Blazor is my Blazor project, who calls the HttpApi.Client. They works fine elsewhere but this place.**

- Steps needed to reproduce the problem:
Nothing special than I mentioned in the first post, I just added a method called
`Task<IEnumerable<MyTypeDto>> GetDetailListAsync(IEnumerable<int> ids);`
in my existing MyAppService, and called it via injected HttpApi.Client "_myAppService":
`IEnumerable<MyTypeDto> dto = await _myAppService.GetCustomListAsync(ids);`

All other methods of the AppService works normally without the newly added one.

**Comment by BrianCodeman** [comment]
If I simply add [HttpPost] attribute to "GetDetailListAsync" method, it works, or if I try the "Get" api from swagger, it works too. that's why I doubt the error is due to parameter binding or something.

**Comment by jimmidier** [comment]
I tried to reproduce your problem but everything works fine. Would be better if you provide server side exception logs.

**Comment by BrianCodeman** [comment]
Thanks for your attention, server side logs attached below:

> 2020-08-06 09:19:39.234 +08:00 [INF] Executing endpoint 'Taurus.Services.TranscriptAppService.GetDetailListAsync (Taurus.Application)'
> 2020-08-06 09:19:39.249 +08:00 [INF] Route matched with {action = "GetDetailList", controller = "Transcript", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[Taurus.Dto.TranscriptDetailDto]] GetDetailListAsync(System.Collections.Generic.IEnumerable`1[System.Int32]) on controller Taurus.Services.TranscriptAppService (Taurus.Application).
> 2020-08-06 09:19:39.376 +08:00 [WRN] ---------- RemoteServiceErrorInfo ----------
> 2020-08-06 09:19:39.376 +08:00 [WRN] {
>   "code": null,
>   "message": "Your request is not valid!",
>   "details": "The following errors were detected during validation.\r\n - The value 'System.Collections.Generic.List`1[System.Int32]' is not valid.\r\n",
>   "validationErrors": [
>     {
>       "message": "The value 'System.Collections.Generic.List`1[System.Int32]' is not valid.",
>       "members": [
>         "ids"
>       ]
>     }
>   ]
> }
> 2020-08-06 09:19:39.407 +08:00 [WRN] ModelState is not valid! See ValidationErrors for details.
> Volo.Abp.Validation.AbpValidationException: ModelState is not valid! See ValidationErrors for details.
>    at Volo.Abp.AspNetCore.Mvc.Validation.ModelStateValidator.Validate(ModelStateDictionary modelState)
>    at Volo.Abp.AspNetCore.Mvc.Validation.AbpValidationActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> 2020-08-06 09:19:39.407 +08:00 [WRN] There are 1 validation errors:
> 2020-08-06 09:19:39.407 +08:00 [WRN] The value 'System.Collections.Generic.List`1[System.Int32]' is not valid. (ids)
> 2020-08-06 09:19:39.438 +08:00 [INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
> 2020-08-06 09:19:39.438 +08:00 [INF] Executed action Taurus.Services.TranscriptAppService.GetDetailListAsync (Taurus.Application) in 165.1187ms
> 2020-08-06 09:19:39.438 +08:00 [INF] Executed endpoint 'Taurus.Services.TranscriptAppService.GetDetailListAsync (Taurus.Application)'

**Comment by maliming** [comment]
hi @BrianCodeman 

Have you tried `List`? Does this work?

`Task<List<MyTypeDto>> GetDetailListAsync(List<int> ids);`

**Comment by BrianCodeman** [comment]
Yes, I have tried it minutes ago, the exception is the same. I am trying to build a sample project that can reproduce the issue and upload it. You can help me to check it then.

**Comment by BrianCodeman** [comment]
By the way, I built my working project since  v2.0, and updated it from "abp update" way up to v 3.0.0 now, is that lead to some unaware problem? Should I re-establish a new v 3.0.5 project from scratch?

**Comment by maliming** [comment]
You can use the latest template project.

**Comment by jimmidier** [comment]
@BrianCodeman I've reproduced your problem, didn't make it httpget at first. Sorry for that. 
And I think you are right about Http.Client that it didn't resolve the query strings correctly.

When `DynamicHttpProxyInterceptor` builds the url, it seems like it directly convert the value of any type to string.
```
(UrlBuilder.cs)

private static string ConvertValueToString([NotNull] object value)
{
    using (CultureHelper.Use(CultureInfo.InvariantCulture))
    {
        if (value is DateTime dateTimeValue)
        {
            return dateTimeValue.ToUniversalTime().ToString("u");
        }

        return value.ToString();
    }
}
```

This leads to a url like this in our situation
![url](https://user-images.githubusercontent.com/16027480/89513535-43acf300-d807-11ea-95d4-5e1575cdd234.png)



@maliming Please check it out if it's the right cause.

**Comment by BrianCodeman** [comment]
I am so glad to see you have pinpointed the issue. That means the bug-fix is coming soon. Really appreciate for you effort!

**Comment by BrianCodeman** [comment]
I still attach a [Sample.zip](https://github.com/abpframework/abp/files/5034221/Sample.zip)  project to show the Issue

### Modified Code
1. **IMyAppService** interface added to **Sample.Application.Contracts** project.
```
    public interface IMyAppService : IApplicationService
    {
        Task<IEnumerable<int>> GetDetailListAsync(IEnumerable<int> ids);
    }
```
2. **MyAppService** class added to **Sample.Application** project.
```
    public class MyAppService : ApplicationService, IMyAppService
    {
        public Task<IEnumerable<int>> GetDetailListAsync(IEnumerable<int> ids)
        {
            return Task.FromResult(ids);
        }
    }
```
3. Remote call added to **ClientDemoService's RunAsync** method of **Sample.HttpApi.Client.ConsoleTestApp** project:
```
IEnumerable<int> ids = new List<int>{1,2,3,4};
var result = await _myAppService.GetDetailListAsync(ids);
```

### Way to reproduce it
1. Set proper ConnectionStrings in **Sample.HttpApi.Host** and **Sample.DbMigrator** project
2. Restore and Build the Solution.
3. Run **Sample.DbMigrator** to prepare Database.
4. Run **Sample.HttpApi.Host**
5. Run **Sample.HttpApi.Client.ConsoleTestApp**
 and the Exception will be caught at **ClientDemoService** class.

**Comment by maliming** [comment]
hi, @BrianCodeman I'm fixing this.
