### ISSUE TITLE
API Versioning test, finalize & document

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#497]
We should check and understand ABP's current API versioning system (I had built a system based on appservices), think the missing parts if there are. We want to document the current status. Also, think on different scenarios (like if we don't want to use appservices and/or we write API controllers, how we should go) including client scenarios (javascript and c# clients with and without abp proxies). We should prepare a complete guide for developers who want to implement API versioning in their solutions.

**Comment by xyfy** [comment]
abp v4.2?

**Comment by xyfy** [comment]
when will this to finish?  something demo about the auto  dynamic  api proxy?

**Comment by aelhadi** [comment]
Hello, 
Any news about this?

Best regards

**Comment by maliming** [comment]
https://github.com/abpframework/abp-samples/pull/126
