### ISSUE TITLE
Cannot get right id from Repository.InsertAsync(entity) when seeding

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#4971]
* Your **ABP Framework version**. 
3.0.5
* Your **User Interface** type  
API only
* Exception message and **stack trace** if available (check the logs).
      The instance of entity type cannot be tracked because another instance of this type with the same key is already being tracked

* Steps needed to **reproduce** the problem.
1) Set breakpoint in domian/seed/OwnerDataSeeder in line 62
2) Change connection string for migrator project
2) Run the migrator project of the attached project

I am trying to seed some data to db. and I use the contributor, when insert data by 
      `await _ownerRepository.InsertAsync(entity);`
I got above exception. and when I use 
     ` await _ownerRepository.InsertAsync(entity,true);`
it works fine.

after some debug, I found await _ownerRepository.InsertAsync(entity); cannot return righ guid, just default zero string which lead to error when insert the second record.

And another confusion when migration for tenant.
I blind below code to enable tenant (without connectionstring) migration, 

   
                  if (!tenant.ConnectionStrings.Any())
                {
                    continue;
                }

but when debugging, even the seed context has tenantid already, when you call insert method:
       `     await _ownerRepository.InsertAsync(entity,true);`
database records still have no tenant Id, I have to set tenantId when  building the entity.

[mtest.zip](https://github.com/abpframework/abp/files/5032608/mtest.zip)

**Comment by jimmidier** [comment]
If the entity key is of type guid, you have to provide it manually.
Change the `Test` entity to receive the id in ctor.
```
...
public Test(Guid id)
{
     Id = id;
}
```
Inject `IGuidGenerator` in `OwnerDataSeeder` to provide id.
```
...
private readonly IGuidGenerator _guidGenerator;
...

public OwnerDataSeeder(
           ITenantRepository tenantRepository,
           IRepository<Test, Guid> ownerRepository,
           IdentityUserManager userManager,
           IGuidGenerator guidGenerator)
{
        _tenantRepository = tenantRepository;
        _ownerRepository = ownerRepository;
        _userManager = userManager;
        _guidGenerator = guidGenerator;
}
```
And use it to provide id when seeding.
```
...
entity = new Test(_guidGenerator.Create())
{
    //TenantId = tenantId,
    Name = category
};
...
```

As for the tenantId, yes you have to manually set it. I think seed context just provides you with the current tenant id and it's up to you to decide whether and how to use it.

**Comment by evenlee** [comment]
thanks @jimmidier , does that mean
`await _ownerRepository.InsertAsync(entity,true); `
will create guid pk automatically?

**Comment by jimmidier** [comment]
Yes, if you leave guid pk empty then abp will create one for you when `SaveChangesAsync`.

**Comment by hikalkan** [comment]
`InsertAsync(entity)` doesn't set GUID value now, for EF Core. It will set with v3.1 (if you haven't set before).
ABP v3.0 sets Id on database save. `InsertAsync(entity, autoSave: true)` sets because it saves changes to database.

**Comment by evenlee** [comment]
thanks for the details @hikalkan, I am quite clear now:)
