### ISSUE TITLE
Authentication Extensibility system to check username & password from an external source

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4977]
ASP.NET Boilerplate has a good feature, named "External Authentication": https://aspnetboilerplate.com/Pages/Documents/Zero/User-Management#external-authentication

It makes possible to check username & password from any source (a database, a REST service, LDAP.... etc.). This is a good system which allows to easily extend the authentication mechanism.

I will implement a similar system for the ABP Framework, in the Identity module.

**Comment by hikalkan** [comment]
Done. This will be (eventually) documented. But, if you want to use it today;

1. Create a class inherits from the `ExternalLoginProviderBase` (defined in the Volo.Abp.Identity.AspNetCore package). Example:

````csharp
using System;
using System.Threading.Tasks;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Guids;
using Volo.Abp.MultiTenancy;

namespace Volo.Abp.Identity.AspNetCore
{
    public class FakeExternalLoginProvider : ExternalLoginProviderBase, ITransientDependency
    {
        public const string Name = "Fake";

        public FakeExternalLoginProvider(
            IGuidGenerator guidGenerator,
            ICurrentTenant currentTenant,
            IdentityUserManager userManager,
            IIdentityUserRepository identityUserRepository)
            : base(
                guidGenerator,
                currentTenant,
                userManager,
                identityUserRepository)
        {

        }

        public override Task<bool> TryAuthenticateAsync(string userName, string plainPassword)
        {
            return Task.FromResult(
                userName == "ext_user" && plainPassword == "abc"
            );
        }

        protected override Task<ExternalLoginUserInfo> GetUserInfoAsync(string userName)
        {
            if (userName != "ext_user")
            {
                throw new ArgumentException();
            }

            return Task.FromResult(
                new ExternalLoginUserInfo("ext_user@test.com")
                {
                    Name = "Test Name", //optional, if the provider knows it
                    Surname = "Test Surname", //optional, if the provider knows it
                    EmailConfirmed = true, //optional, if the provider knows it
                    TwoFactorEnabled = false, //optional, if the provider knows it
                    PhoneNumber = "123", //optional, if the provider knows it
                    PhoneNumberConfirmed = false, //optional, if the provider knows it
                    ProviderKey = "123" //The id of the user on the provider side
                }
            );
        }
    }
}
````

`TryAuthenticateAsync` should check user & pass and `GetUserInfoAsync` should provide user details. `GetUserInfoAsync` is called on create (when the user first logins) and update (subsequent logins).

2. Register to the `AbpIdentityAspNetCoreOptions`:

````csharp
Configure<AbpIdentityAspNetCoreOptions>(options =>
{
    options.ExternalLoginProviders.Add<FakeExternalLoginProvider>(FakeExternalLoginProvider.Name);
});
````

You can register more than one provider.

### Additional notes

* This feature comes with a new `IsExternal` field to the `IdentityUser` which is set to true if the user was created on an external authentication process.

**Comment by jortygu** [comment]
@hikalkan it should be Register to the AbpIdentityOptions，not AbpIdentityAspNetCoreOptions

**Comment by ejohnson-dotnet** [comment]
Can you help us understand something.  Can you explain the "IsExternal" property a little better.  Isn't a Google authenticated user an "external" user?  If implementing Azure Active Directory, isn't those users an external user?   Why is the IsExternal still false for these users?

**Comment by leonkosak** [comment]
@hikalkan, this example does not work anymore.
I have abp v5.2.1 (MVC, non-tiered) and "MyExternalLoginProvider.cs" is located in .Web project.

The following code was added to xxxxWebModule.cs (inside ConfigureAuthentication method):

`Configure<AbpIdentityOptions>(options =>
        {
            options.ExternalLoginProviders.Add<MyExternalLoginProvider>(MyExternalLoginProvider.Name);
        });`

(AbpIdentityAspNetCoreOptions has no ExternalLoginProviders prop.)

However, there is no External providers visible on Login page (Login.cshtml).

As far as I know, external providers should be visible in this part of Login.cshtml:

`@if (Model.VisibleExternalProviders.Any())
        {
            <div class="mt-2">
                <h5>@L["OrLoginWith"]</h5>
                <form asp-page="./Login" asp-page-handler="ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl" asp-route-returnUrlHash="@Model.ReturnUrlHash" method="post">
                    @foreach (var provider in Model.VisibleExternalProviders)
                    {
                        <button type="submit" class="btn btn-primary m-1" name="provider" value="@provider.AuthenticationScheme" title="@L["LogInUsingYourProviderAccount", provider.DisplayName]">@provider.DisplayName</button>
                    }
                </form>
            </div>
        }`

What am I doing wrong?
Thank you.

P.S.: @maliming, @ebicoglu do you have any suggenstions for this ExternalLoginProviders? There is nothing in documentation. Just in this and few other GH issues. :(

**Comment by NavneetProject** [comment]
Hello ABP Team,
In LDAP and AAD (Oauth Login) - 
1. Does the ABP application save the password of uses of LDAP and AAD in local DB after logging on?
2. Do the Tenant need to Import LDAP & AAD to use the ABP login screen?
3. When the user tries to use his LDAP username and password to log in, will the ABP application check if the user is active in ActiveDirectory?

**Comment by maliming** [comment]
hi @NavneetProject 

Please create a new issue. Thanks

**Comment by NavneetProject** [comment]
There is no issue, we just want to understand the capabilities of LDAP and Oauth in ABP.

I don't have any problem, ABP is amazing :-)

**Comment by maliming** [comment]
hi https://github.com/abpframework/abp/issues/17408
