### ISSUE TITLE
Setting management document

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#498]

**Comment by mtringuyen** [comment]
I wish we have a quick guide how to use setting management module

**Comment by maliming** [comment]
hi @mtringuyen
Before the document is completed, you can refer to the way other modules use **Setting management**. Of course, unit testing is also a good way to understand the function.

The source code of the **Setting management**is not particularly complicated.

**Comment by hikalkan** [comment]
Completed:

* Setting system: https://github.com/abpframework/abp/blob/dev/docs/en/Settings.md
* Setting management module: https://github.com/abpframework/abp/blob/dev/docs/en/Modules/Setting-Management.md

**Comment by wakuflair** [comment]
@hikalkan 

The link from [this page](https://docs.abp.io/en/abp/latest/Modules/Index) is broken.

![image](https://user-images.githubusercontent.com/3471718/68640149-cf784400-0541-11ea-84c5-59c139503204.png)

**Comment by maliming** [comment]
@wakuflair The content of the website has not been updated.

**Comment by hikalkan** [comment]
Thanks @wakuflair for reporting this. MD seems normal, I will check this.
