### ISSUE TITLE
BusinessException on Angular UI  has non-localized toaster TITLE using Toaster Service.

### ISSUE THREAD

**Issue by buaziz** [abpframework/abp#4986]
* **ABP Framework version** : v3.0.5
* type Angular
* Steps needed to **reproduce** the problem.

BusinessException has non-localized toaster TITLE on Angular UI using Toaster Service.

referencing original issue :https://github.com/abpframework/abp/issues/3503

and my comment : https://github.com/abpframework/abp/issues/3503#issuecomment-670065666

**Comment by maliming** [comment]
hi @buaziz 
Can you share the http response? 

![image](https://user-images.githubusercontent.com/6908465/92543318-bb929100-f27d-11ea-9062-c272fac0ac4d.png)

**Comment by buaziz** [comment]
@maliming  I am referring to the text **_"An error has occurred!"_** 

how do I localize this text ?

**Comment by maliming** [comment]
hi

It belongs to **AbpUiResource**,

![image](https://user-images.githubusercontent.com/6908465/92563861-d7f8f280-f2aa-11ea-9cdb-8cc91c47d095.png)


https://github.com/abpframework/abp/blob/90d779453eab27f35bcfa7308f1a308aa5dee40e/framework/src/Volo.Abp.UI/Localization/Resources/AbpUi/en.json#L7

https://docs.abp.io/en/abp/latest/Localization#extending-existing-resource
