### ISSUE TITLE
Document : Setup and sending Emails

### ISSUE THREAD

**Issue by buaziz** [abpframework/abp#4987]
https://docs.abp.io/en/abp/latest/Emailing

**Comment by hikalkan** [comment]
Setting email setting is pretty easy: https://docs.abp.io/en/abp/latest/Settings#setting-values-in-the-application-configuration

Then inject & use IEmailSender :)

**Comment by hikalkan** [comment]
Documented: https://docs.abp.io/en/abp/latest/Emailing
