### ISSUE TITLE
BlobStoring need more  features and api

### ISSUE THREAD

**Issue by cocosip** [abpframework/abp#4989]
- 1. Now,most of the  integrated `BlobStoring` provider ,the blob name was generate by client side, but how can i get the blob name when the name was generate  by server side. Such as `FastDFS`,`Seaweedfs` ?

- 2. How to get blob propery? When use `Aliyun`,`AWS`,`Minio` , how to get file access url ? the url was generate by sdk, and not by our own stitching .  Maybe we need a api like :
```c#
 Task<MetaData> GetMetaDataAsync(BlobProviderGetMetaDataArgs args);
```
- 3.  When the file upload is larger, it's better to auto-sharding in `Aliyun`,`Minio`,`AWS` and so on, they are compatible s3 protocol.

**Comment by gdlcf88** [comment]
> how to get file access url ?

I think the BLOB storing does not care about that, since it is only used by the application/module, not by the user directly. You may need an external download URL generator which should be designed by yourself.

**Comment by hikalkan** [comment]
BLOB storing system is an high level abstraction to use a storing system by reusable modules without depending on the actual provider.

If you want to work with low level details, you should directly use the provider you need. Trying to bring the full power of all the providers to a common abstraction is no so possible.

If you really find solutions to these problems, you can still do it. For example, create a FastDFS provider that gets blob name from out of the class, internally store a blob name - generated id match table and find the proper blob resource on need. In this way, you can still use the server side id generation of the underlying provider.
However, I don't think it worths, especially if you are developing an application.

Currently, we don't think to add these details to the BLOB storage system.

**Comment by aricyu** [comment]
Is it possible to add a GetAccessUrl method in `BlobProvider` and `BlobContainer`?

**Comment by gdlcf88** [comment]
> Is it possible to add a GetAccessUrl method in `BlobProvider` and `BlobContainer`?

So how to get the AccessUrl of a local file from File System Provider?

**Comment by aricyu** [comment]
@hikalkan 
Most file storage providers (FileSystem needs to add wwwroot and set it to `fileSystem.BasePath = Path.Combine(hostingEnvironment.WebRootPath, "my-files")`) support direct connection to url to obtain files, why can't it be abstracted into a method? It's like getting a stream.

**Comment by aricyu** [comment]
@gdlcf88  
If it is FileSystem, you need to set fileSystem.BasePath = Path.Combine(hostingEnvironment.WebRootPath, "my-files") and add wwwroot

If it is not set, I have no solution for the time being, which is also my confusion。

I am also confused about the FileSystem package. Why can BasePath set a folder outside the project, and what scenarios would require this? If it is just to look high-end, I don't think it is necessary.
