### ISSUE TITLE
Introducing the ABP Community (community.abp.io)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#4990]
Hello all!

We are excited to announce that we've published the initial version of the **ABP Community Web Site**: https://community.abp.io/

The goal of this web site is to **bring the ABP Community together, create and share content** related to the ABP Framework and Software development.

Currently, we started with "**Articles**". You can **publish your own ABP related articles** here. There is no topic restriction, but we expect the article be related to the ABP somehow :)

You can write your article on your own GitHub repository with Markdown format and submit your article's URL to the https://community.abp.io/articles/submit

If you want to write your article in any other platform (like Medium or your own blog), it is still possible to add it here as an external article.

Middle & Long-term goals of the ABP Community project are including;

* Adding surveys for requested features and other ABP related topics.
* Adding tags, comments, upvote, reactions... to the contents to increase interactivity.
* Adding "announcements / news" section.
* Adding the latest stackoverflow question and blog post related to the ABP Framework
* Multi-language support to share content is different languages. Currently, we accept articles in English.

**Comment by leonkosak** [comment]
This is great. Some kind additional documentation for abp. 👍

**Comment by xdmushui** [comment]
I recommend adding a hyperlink to the author's blog in the "author" label.

**Comment by hikalkan** [comment]
We are creating a profile page which will include details about the author and his/her bio, social links... etc.

**Comment by hikalkan** [comment]
* Profile page is available. Click to a username. Example: https://community.abp.io/members/alper
* Also, a summary of the profile is available at the end of an article.

**Comment by hikalkan** [comment]
Anyone can fill the public profile:

![image](https://user-images.githubusercontent.com/1210527/91850314-00a73980-ec66-11ea-90f7-f198d5e1fc78.png)

**Comment by wocar** [comment]
I was thinking... could we organize a virtual conference for more advanced topics regarding abp, that would be nice.

**Comment by hikalkan** [comment]
Yeah.. we definitely want this. We talked a lot about that internally :)
We will first make a Webinar, a small virtual conference, consists of 3-4 talks. It will probably be in the first quarter of 2021.
