### ISSUE TITLE
Implement "Authorization Code Grant with PKCE" for the Angular UI

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#4994]
Change the `angular-oauth2-oidc` configuration in environment to implement the code flow in v3.1:

New configuration:

```ts
const baseUrl = 'http://localhost:4200';

export const environment = {
  //...
  oAuthConfig: {
    issuer: 'https://localhost:44305',
    redirectUri: baseUrl,
    clientId: 'MyProjectName_App',
    responseType: 'code',
    scope: 'offline_access MyProjectName',
  },
  //...
}
```

**Comment by olicooper** [comment]
Related? https://github.com/abpframework/abp/issues/2980

It seems like the new code-flow implementation calls `/connect/token` endpoint every 4mins and refreshes the `access_token` but the user information doesn't update in the token. Should it automatically update?

**Comment by mehmet-erim** [comment]
Hi @olicooper

As you know, we are using the `angular-ouaht2-oidc` package to manage OAuth processes. The `setupAutomaticSilentRefresh` method of `OAuthService` has been called on the app initialization. (See https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/core/src/lib/strategies/auth-flow.strategy.ts#L44) I did not do anything for refresh token implementation. The package manage the process.

I think it is sufficient to refresh the access token. I will handle in detail the refresh token implementation issue in v3.2. It will also be implemented for password flow and fix the known problems.
