### ISSUE TITLE
How to manage multiple website in a same solution ?

### ISSUE THREAD

**Issue by Jaeha90** [abpframework/abp#5000]
I have a solution which already have a backend .Web project, using mvc / razor. I want to add an other project for my frontend which will using Angular. This new project must have access to the already existing API (The same that I use for the backend).

Is there some samples for this scenario ?

I already created my new Angular project (Server side and client-side), generate-proxy worked, but when I launch my angular site with ng serve command I got this error in logs.txt : "There is already an existing permission group with name: AbpIdentity".

I think I'm missing something (Or added too many modules) in the Angular project (Server-side).

Thank for your help

**Comment by hikalkan** [comment]
Hi,

Normally, it is expected to create 2nd UI manually. However, the way you did it may simplify it: Re-generate a solution with the same name with Angular UI, **then delete the server side** (do not use the server side since you already have one), change server URL on the angular application.

**Comment by Jaeha90** [comment]
It's working, thank you so much ! Have a nice day !

**Comment by hikalkan** [comment]
Congratulations for the 5000th issue :)
