### ISSUE TITLE
Cli and docs down cannot create new projects 

### ISSUE THREAD

**Issue by duhowise** [abpframework/abp#5002]
![Screenshot_20200808-155934_Firefox.jpg](https://user-images.githubusercontent.com/17531922/89714743-7df5cc00-d990-11ea-8f26-d975df6ca96a.jpg)

**Comment by hikalkan** [comment]
Thank you for informing. We are checking it.

**Comment by duhowise** [comment]
> Thank you for informing. We are checking it.

Checking further reveals issue presents only for the latest version of the framework.  Using the - v 2.8.0 works

**Comment by hikalkan** [comment]
Because it uses the local cached copy of the startup template. We are close to resolve the issue. I will write when we solve it.

**Comment by hikalkan** [comment]
The problem has been fixed. Thank you again for informing us.
