### ISSUE TITLE
angular-oauth2-oidc bailout warning - included with CommonJS (needs package update)

### ISSUE THREAD

**Issue by davidzwa** [abpframework/abp#5003]
- Abp 3.0.5
- Angular (@abp/ng.core 3.0.5)
`
  WARNING in C:\Users\david\Projects\Teamsite\src-angular\node_modules\angular-oauth2-oidc\__ivy_ngcc__\fesm2015\angular-oauth2-oidc.js depends on 'js-sha256'. CommonJS or AMD dependencies can cause optimization bailouts.  
`

This problem has been fixed in v10 of the package as described in this closed issue https://github.com/manfredsteyer/angular-oauth2-oidc/issues/866

**Comment by yinchang0626** [comment]
this package will update in this [pr](https://github.com/abpframework/abp/pull/4995/files#)
