### ISSUE TITLE
Console applications revision

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5007]
* I've done https://github.com/abpframework/abp/issues/5006 for https://github.com/abpframework/abp/tree/dev/templates/console Please apply to the app/module startup templates
* Delete the https://github.com/abpframework/abp-samples/tree/master/BasicConsoleApplication because it is no longer needed. We can create the same via console template.
* Change https://docs.abp.io/en/abp/latest/Getting-Started-Console-Application to show how to use the abp cli and the console template to create the application. No need to show how to create manually.

**Comment by JadynWong** [comment]
It it good for console application.But I think there may be more than one service in a project. Execute `Application.Initialize` in `IHostedService` is a bit strange to me. I think we can execute `Application.Initialize` before the host starts.

Related #4608

**Comment by hikalkan** [comment]
>Execute Application.Initialize in IHostedService is a bit strange to me

I agree. I will create a new issue to improve this further.
