### ISSUE TITLE
"Blogging API" presented in module template code.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#501]
https://github.com/abpframework/abp/blob/13fff38fc3c4a9b2af3179ed111d939882d7822f/templates/module/app/MyCompanyName.MyProjectName.DemoApp/DemoAppModule.cs#L77

**Comment by hikalkan** [comment]
Thanks. A PR would be awesome :)

**Comment by wakuflair** [comment]
> Thanks. A PR would be awesome :)

It's my pleasure:)

#509

**Comment by hikalkan** [comment]
Thanks :)
