### ISSUE TITLE
How To: generate password hash

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#5014]
### Documentation

Hi,

I'm trying to generate a set of users with code, and so I also need to generate a default password.
The problem is that I can't find a way to correctly generate my password has.

Here is how I do:

```
var filter = Builders<BsonDocument>.Filter.Eq("UserName", userName);
            var doc = usersCollection.Find(filter).FirstOrDefault();
            Volo.Abp.Identity.IdentityUser identityUser = BsonSerializer.Deserialize<Volo.Abp.Identity.IdentityUser>(doc);

            // Generate
            var hasher = new Microsoft.AspNetCore.Identity.PasswordHasher<Volo.Abp.Identity.IdentityUser>();
            string passwordHash = hasher.HashPassword(identityUser, newPassword);

            Microsoft.AspNet.Identity.PasswordHasher hasher2 = new Microsoft.AspNet.Identity.PasswordHasher();
            string passwordHash2 = hasher2.HashPassword(newPassword);
```

I do this directly from a small batch program, this one has no access to the identity features etc... it use direct DB insertion/update

First, I retrieve the user, then I try to generate the same password hash from the same password, but it does not match.

Any idea ?

**Comment by maliming** [comment]
hi 

We are using the asp net core Identity(https://github.com/dotnet/aspnetcore/tree/master/src/Identity). so you can refer to its document.

eg:
https://andrewlock.net/exploring-the-asp-net-core-identity-passwordhasher/

**Comment by amirsaeed33** [comment]
actually, abp framework is password-secure so u don't descriptive the password
