### ISSUE TITLE
Can't login to demo.commercial.abp.io

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#5019]
Identity server seems to be failing due to config/proxy issue...
I am also navigated to the http version of the site byt default and the https version doesn't have an SSL certificate. This is possibly why it has stopped working.

Url: http://bea812baf741b556.demo.commercial.abp.io/account/login

tried changing the tenant to: `bea812baf741b556` but it says tenant isn't available.

**Comment by hikalkan** [comment]
I could able to login successfully.

I am using Chrome version 84.0.4147.105. What's your browser & version.

**Comment by olicooper** [comment]
I am also using Chrome 84.0.4147.105 on Windows.
I have navigated again without clearing browser cache etc. and it is working again now. Not sure what was wrong because I tried it in incognito and got the same results before so I'm confident it wasn't my PC.

Connection is still only http though.
Thanks for looking in to it, I will let you know if it happens again :)
