### ISSUE TITLE
[ABP Samples: Microservice Demo Solution] Cannot resolve controller Logout

### ISSUE THREAD

**Issue by ablekh** [abpframework/abp#5020]
I've looked everywhere and couldn't find any definitions of a `Logout` class that is referenced in the following files: `applications\AuthServer.Host\Pages\Index.cshtml` and `applications\PublicWebSite.Host\Pages\Index.cshtml`.

**Comment by hikalkan** [comment]
is these what you are looking for: https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Areas/Account/Controllers/AccountController.cs#L73 or https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Logout.cshtml.cs

**Comment by ablekh** [comment]
@hikalkan Thank you for your prompt reply and suggestions. I don't see how the second link is relevant (directly), but the first one seems to be. However, if we are supposed to refer to a specific `Task` class name (`Logout`, in this case) as a name of relevant controller in `asp-controller` (expecting value of `System.String Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper.Controller` type), how are we supposed to use it? I have tried to add `@using Volo.Abp.Account.Web` or `@using Volo.Abp.Account.Web.Areas.Account.Controllers`, but `Logout` still cannot be resolved ... :-(

**Comment by hikalkan** [comment]
>but Logout still cannot be resolved

You mean it works but Visual Studio shows warning/error? Or it doesn't work at all? If not working, how can I re-produce the problem?

**Comment by ablekh** [comment]
@hikalkan I haven't built it yet, assuming that it makes little sense to try build a solution with unresolved symbols.

FYI: the on-hover message `Cannot resolve controller Logout` appears only in JetBrains Rider (version 2020.1.4), which I'm using as my main IDE; relevant message in VS Code (I don't have Visual Studio) is `Loading...` (I suspect that, for some reason, VS Code's IntelliSense is not working correctly; or it does not work as well as Rider's implementation).

**Comment by hikalkan** [comment]
I am also using Rider and getting the same warning on hover, but it works, don't worry :)
The IDE is looking to the current solution to find it, but it is defined in a NuGet package. So, this is a problem of IDEs actually. I couldn't find a way yet to make the IDE happy.

**Comment by ablekh** [comment]
@hikalkan Oh, wow! Color me surprised. :-) In that case, I will try to build the solution (as well as other examples) and will continue studying .NET and ABP Framework, which is quite impressive. 👍 

`<rant>` I guess, I had higher expectations of modern IDEs. After all, if some symbols are defined in some NuGet packages, which are declared as part of a project or solution, why IntelliSense wouldn't search through all declared packages to correctly resolve all symbols is beyond my comprehension. `</rant>`

Anyway, thank you very much for your prompt and kind help. Much appreciated. By the way, could you suggest Rider and VS Code alternatives [extensions/plugins, I assume] for Visual Studio's Package Manager Console (PMC)? I have found the following extension for VS Code, but no relevant plugins for Rider: https://marketplace.visualstudio.com/items?itemName=jmrog.vscode-nuget-package-manager ...

**Comment by hikalkan** [comment]
I also didn't find a good plugin for it, which is especially useful for EF Core commands, like Add-Migration.  Currently I am using "dotnet ef migrations add ...". If you find, please inform me too 😄

**Comment by ablekh** [comment]
@hikalkan I see. Sure, will definitely let you know. :-)
