### ISSUE TITLE
Account-module - Architectural question

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#5027]
Hi,

I've just a small question:

Is there a reason that not all APIs of the account module are defined in the `Application.Contracts` package?
The [AccountController](https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Areas/Account/Controllers/AccountController.cs), which is in the `Volo.Abp.Account.Web` package defines some endpoints which would be nice to have a contract for.

It would be nice if the `AccountController` just implements the `IAccountAppService` so it can be used as a dynamic C# API client.
In case there isn't a particular reason for this, I would like to contribute a PR which streamlines the account module to provide a proper http api.

**Comment by hikalkan** [comment]
Unfortunately that's not possible.

For example, see https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Areas/Account/Controllers/AccountController.cs#L54

We are using `SignInManager.PasswordSignInAsync` which internally uses IdentityManager and finally adds a cookie to the current http response. That means it logins the current user. We can not make it working on a remote API. Microsoft Identity library has not been designed to be tiered (where you separate UI and API layers)

**Comment by NecatiMeral** [comment]
Hi @hikalkan,

thank you for your answer.
Wouldn't it be possible to create another interface in the `Application.Contracts` which is implemented by the `AccountController`?

By declaring a interface this way, it could be possible to use the controller with a dynamic C# API client.

Background:
We're trying to use the Account APIs to login users in a WinForms application. Directly using the apis with a `HttpClient` works currently but the automatic C# client's are unable to use the authentication cookie which is stored in the cookie container. We don't want to use a embedded browser to authenticate the user.

**Comment by hikalkan** [comment]
You should use token based authentication and this `AccountController` is not for it.
The startup template has a [console application](https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp) which successfully authenticates and calls backend APIs using the C# dynamic proxies. You should follow the same approach for the WinForms app.

**Comment by NecatiMeral** [comment]
Thank you @hikalkan.

We'll investigate this topic further. :-)
