### ISSUE TITLE
AbpProfileService during Multitenancy: Switches to null tenant from grant during authorization

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [abpframework/abp#5032]
- ABP Framework version 3.0.5.

**How to reproduce:**

- We have a solution that gets the tenant from the header during authentication on identity server (we use startup with identity server included in api host)
- We have a database per tenant approach, and the connection strings get correctly resolved in all services except AbpProfileService
- Call https://localhost:44347/connect/token, provide a valid tenant in the header
![bug_connect_token](https://user-images.githubusercontent.com/11556950/89987177-e63cfa00-dc7d-11ea-9fed-28db35656df2.PNG)

- For all services, this tenant is correctly used
- Except **AbpProfileService**, which switches from the selected tenant to the tenant in the claim: "context.Subject.FindTenantId()", which at this point is null.
- This leads to an error during 'GetProfileDataAsync' / 'IsActiveAsync', making the token call fail

![bug_abpprofileservice](https://user-images.githubusercontent.com/11556950/89987196-ee953500-dc7d-11ea-8454-421ef740370a.PNG)

**Current Workaround**
- ReplaceServices AbpProfileService with one that is not switching the tenant

**Comment by maliming** [comment]
hi 
I will check this.

**Comment by maliming** [comment]
I can't reproduce the problem you encountered.


![image](https://user-images.githubusercontent.com/6908465/90226631-d96b0280-de45-11ea-8f5b-52d828bd244f.png)


![image](https://user-images.githubusercontent.com/6908465/90226613-d3752180-de45-11ea-9584-18236ad66d54.png)

**Comment by KevinBassaDevelopment** [comment]
Thanks for checking this!
Now I was able to track down the issue. The tenantid claim was missing because the tenantid was not set in the user table.

We chose to use a database per tenant, and to have a separate application managing the tenants (so without the 'default tenant' approach).
That's why we thought we can have the tenantId null on each tenant (so tenant may not know its own id).

**Comment by maliming** [comment]
>  the tenantid was not set in the user table. 
> so tenant may not know its own id

Is this reasonable? of course you can replace `AbpProfileService` with yours.

**Comment by KevinBassaDevelopment** [comment]
> 
> 
> > the tenantid was not set in the user table.
> > so tenant may not know its own id
> 
> Is this reasonable? of course you can replace `AbpProfileService` with yours.

We thought it works with the framework. As it does not, its of course not reasonable, as we want to stay close to the base abp framework. Now we are just storing the tenant ids as it does on default.

Does a setup make sense where there are only tenants, without a default tenant (so just throw exceptions if tenant info is missing in a call)?
It looks like ABP is setup around having a default tenant (especially on startup / ef core initializations).

**Comment by hikalkan** [comment]
>Does a setup make sense where there are only tenants

Just write an aspnet core middleware in front of the MVC middleware, check tenantid and return error to the client if it is null :)
