### ISSUE TITLE
 ERROR: 'Volo.Abp.Account' module could not be found!

### ISSUE THREAD

**Issue by matt14m** [abpframework/abp#5036]
Attempting to add source for the account module with the following CLI command:

abp add-module Volo.Abp.Account --with-source-code

Returns:

[14:49:53 WRN] ERROR: 'Volo.Abp.Account' module could not be found!

Version 3.0.5 (Stable channel)
Interface: MVC

**Comment by maliming** [comment]
Try
`abp add-module Volo.Account --with-source-code`

**Comment by zhenglin-charlie-li** [comment]
> abp add-module Volo.Account --with-source-code

That works for me, thanks!
