### ISSUE TITLE
Global Query Filter Issues In BackGroundJob&Console

### ISSUE THREAD

**Issue by jortygu** [abpframework/abp#5040]
Hi 

* Your **ABP Framework version**.
   3.0.5
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
  MVC
* Exception message and **stack trace** if available (check the logs).
  No
* Steps needed to **reproduce** the problem.
  Demo:https://github.com/jortygu/AbpQueryFilterDemo
  Run AbpQueryFilterDemo.Jobs.Test , check the Active,it should be false  but true;

  i have define a Active Filter on DbContext and get value from DI ICurrentActive. it work's fine on MVC project(dynimic change Active value by ActiveMiddleware).
  but in console project,the Active is alway true,even i had set ICurrentActive.Active=false. 
  ICurrentActive's lifecycle is Scope.

``` C#
public interface ICurrentActive : IScopedDependency{
	bool Active { get; set; }
}
public class CurrentActive : ICurrentActive{
	public bool Active { get; set; }
	public CurrentActive(){
		Active = true;
	}
}
public class AbpQueryFilterDemoDbContext : AbpDbContext<AbpQueryFilterDemoDbContext>, IAbpQueryFilterDemoDbContext
{
	protected virtual bool Active => GetActive();
	public ICurrentActive CurrentActive { get; set; }
	protected bool IsActiveFilterEnabled => DataFilter?.IsEnabled<IActive>() ?? false;
	private bool GetActive()
	{
		Logger.LogInformation($"Active:{CurrentActive.Active}");
		return CurrentActive.Active;
	}
	protected override bool ShouldFilterEntity<TEntity>(IMutableEntityType entityType)
	{
		if (typeof(IActive).IsAssignableFrom(typeof(TEntity)))
			return true;
		return base.ShouldFilterEntity<TEntity>(entityType);
	}
	protected override Expression<Func<TEntity, bool>> CreateFilterExpression<TEntity>()
	{
		var expression = base.CreateFilterExpression<TEntity>();
		if (typeof(IActive).IsAssignableFrom(typeof(TEntity)))
		{
			Expression<Func<TEntity, bool>> dataSourcingFilter = e => !IsActiveFilterEnabled || EF.Property<bool>(e, "Active") == Active;
			expression = expression == null ? dataSourcingFilter : CombineExpressions(expression, dataSourcingFilter);
		}
		return expression;
	}
	...
}

public class OrderSyncJob : AsyncBackgroundJob<OrderSyncJobArgs>, ITransientDependency
{
	private readonly IOrderRepository _orderRepository;
	public IServiceProvider ServiceProvider { get; set; }
	public OrderSyncJob(IOrderRepository orderRepository)
	{
		_orderRepository = orderRepository;
	}

	public override async Task ExecuteAsync(OrderSyncJobArgs args)
	{
                //change ICurrentActive.Active
		ServiceProvider.GetRequiredService<ICurrentActive>().Active = args.Active;
		var list = await _orderRepository.GetListAsync();
	}
}
```

**Comment by maliming** [comment]
This may be a problem caused by the service lifecycle . You can check if ICurrentActive is created as expected.

**Comment by jortygu** [comment]
hi @maliming ,

  ICurrentActive is auto injection via property injection way,and it's lifecyle is IScopedDependency. in mvc project, it work's fine(one request resolve an instance). in console project,the ICurrentActive.Active property is alway true,even i had change ICurrentActive.Active=false.i don't konw is there any configuration or attentions to be care in console project(or background job execute by hangfire)?

**Comment by maliming** [comment]
>  in mvc project, it work's fine(one request resolve an instance). in console project,the ICurrentActive.Active property is alway true,even i had change ICurrentActive.Active=false

You have confirmed the problem.

you can try to change its lifecycle, or use other methods to dynamically change the value of `Active `.
