### ISSUE TITLE
Can some on help me to Remove [Extraproperties, ConcurencyStamp] columns from my entity this expecting database table too

### ISSUE THREAD

**Issue by kotishwerreddy** [abpframework/abp#5051]
Hello Everyone!

I'm using ABP.IO Framework to write API services, 
when the time of using we are inherited AggregateRoot<int> to my entity it was expecting [Extraproperties, ConcurencyStamp] columns in the related table.

also tried with inheriting  Entity<int> getting dependency injection auto fac issue 

Geeting below Exception :

 [ERR] An exception was thrown while activating eMedEvents.Controllers.EventsController -> eMedEvents.EventsappService -> eMedEvents.Data.EventsService.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating eMedEvents.Controllers.EventsController -> eMedEvents.EventsappService -> eMedEvents.Data.EventsService.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'eMedEvents.Data.EventsService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[eMedEvents.MySQL_Entities.Actor,System.Int32] actorRepository'

can someone help me to resolve this issue .?

**Comment by sebitsi** [comment]
As i can see there will be BasicAggregateRoot without ExtraProperties and CurrencyStamp in 3.1 version.
I think it is not possible for now.

Look at #4808
