### ISSUE TITLE
Allow customization of modal header

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#506]
```
  <abp-modal-header title="@Model.Job.Number">
<!-- If I add a button here for example, an actions button for the header, wont work! -->
</abp-modal-header>
```

**Comment by hikalkan** [comment]
If you are using "title", then you can not add HTML inside the header. So, don't use title and add your title inside the header tag.

**Comment by wocar** [comment]
Not working 

![image](https://user-images.githubusercontent.com/9215073/46500645-ebf76800-c7e8-11e8-941a-0a49f6689613.png)

![image](https://user-images.githubusercontent.com/9215073/46500654-f4e83980-c7e8-11e8-9fe2-0ce1e3c0adb5.png)

**Comment by hikalkan** [comment]
OK. Will try this.
