### ISSUE TITLE
Override services on child service scope

### ISSUE THREAD

**Issue by tolemac** [abpframework/abp#5065]
I would like to override service on service scope creation, something like that:

``` csharp
using (var scope = serviceProvider.CreateScope(serviceCollection => {
        serviceCollection.AddTransient<IChildService, OtherChildService>();
    }))
{
    scope.Services.GetService<IMainService>().DoSomeThing();
}
```

It can be useful for many tasks like user impersionation on background jobs or other task where you want change the default behaviour.

.Net Core dependency system does't support that but it's supported by [Autofac](https://autofaccn.readthedocs.io/en/latest/lifetime/working-with-scopes.html#adding-registrations-to-a-lifetime-scope).

If this feature is welcome I think that I can implement it.

**Comment by hikalkan** [comment]
We don't want to add DI-Framework specific feature that may not be possible to implement with other providers.

I suppose you can inject AutoFac services and directly use the AutoFac API (I suppose you should inject & use the `ILifetimeScope.BeginLifetimeScope`).
