### ISSUE TITLE
Unhandled exception details

### ISSUE THREAD

**Issue by KovtunV** [abpframework/abp#5066]
Hi, how can I send exception details to the client? 
In "Abp boilerplate" I used to 
`Configuration.Modules.AbpWebCommon().SendAllExceptionsToClients = true;`

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/blob/6cd3e1f472562a508dcf985d3dd25fe7b37aa493/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/ExceptionHandling/DefaultExceptionToErrorInfoConverter.cs#L55

Currently the value of `SendAllExceptionsToClients` is always `false`. you can create a subclass and set the value to `true` when you need it.

I think we should create an options to configure.

**Comment by KovtunV** [comment]
@realLiangshiwei Thanks! Yep, it would be perfect if you created options to configure :)
