### ISSUE TITLE
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.xero.com/identity ....

### ISSUE THREAD

**Issue by akshaybhagwat76** [abpframework/abp#5070]
https://www.loom.com/share/53628225eb1442be9c2d231f6b53cd20

![image](https://user-images.githubusercontent.com/26058268/90333698-9ba4e000-dfe5-11ea-97b5-cb78f0e5d3a4.png)

![image](https://user-images.githubusercontent.com/26058268/90333699-9f386700-dfe5-11ea-916f-090b8b1b4fa1.png)

![image](https://user-images.githubusercontent.com/26058268/90333702-a19ac100-dfe5-11ea-8123-258c90062d62.png)

![image](https://user-images.githubusercontent.com/26058268/90333706-a3fd1b00-dfe5-11ea-84cb-edb44ee22ed5.png)

Have been struggle since 2 weeks about this can someone watch video and give some reviews regarding where i am wrong, i am trying to achieve xero sign up in aspnetzero project.

**Comment by maliming** [comment]
> i am trying to achieve xero sign up in aspnetzero project.

Please get support in Zero support website or Github. This repo is for abp vnext.
