### ISSUE TITLE
Lazy loading data on UI

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#5078]
Am using asp.net razor pages option for UI with abp framework, Am loading 50,000 + customers lists with images in a UI. Any ideas on how I can lazy load them? Load more as i scroll?

**Comment by leonkosak** [comment]
Not the best answer, but we use DevExpress components (or Syncfusion). These components provide nice interface for partial loading (skip/take).

**Comment by hikalkan** [comment]
Hi @dicksonkimeu you should find a data table component. We have used [datatables.net](https://datatables.net/) for the module pages, but we don't have such a requirement. You can use another component for your page. As @leonkosak stated, paid components have such features.
However, this is not the business of the ABP Framework at all. So, I am closing this issue.
