### ISSUE TITLE
How to use ngx-datatable with pagination

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#5080]
### Help

* **ABP Framework version** `3.0.5`.
* **User Interface** `Angular`

### Q
***Code:***
``` HTML
<ngx-datatable [rows]="(terminals$ | async)" [count]="(terminalTotalCount$ | async)"
                    [list]="list" default>
```
***my question***
- How to display pagination？
![image](https://user-images.githubusercontent.com/8120385/90349436-70b19f00-e06c-11ea-972b-486322d44f7e.png)

**Comment by mehmet-erim** [comment]
Hi @SmallShrimp

Pagination will appear when your total count of records is greater than 10.
The default value of ListService's `maxResultCount` is 10.

You can change this value in your component as shown below:

```ts
  constructor(
    public readonly list: ListService
  ) {
    this.list.maxResultCount = 5;
  }
```

If you want the pagination to be always visible, you should ask a question on https://stackoverflow.com/questions/tagged/ngx-datatable to learn the answer

I hope I could help 😊

**Comment by SmallShrimp** [comment]
ok thanks! @mehmet-erim

**Comment by amirmujtaba** [comment]
I have facing same problem, I'm getting totalCount more than 10, along with first 10 records, but still pagination is not visible, Can you please help?
