### ISSUE TITLE
Help needed: Docker (Angular)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#5087]
Does anyone have clue how to resolve CORS header 'Access-Control-Allow-Origin' missing issue in Docker.
We have separated HttpApi.Host and .IdentityServer (and of course Angular frontend).
Each of these three projects have dedicated container in Docker (separated IP addresses inside Docker network).

API (.HttpApi.Host) works - I can see Swagger when calling IP from host operating system.
Identity Server (.IdentityServer) also works (also login in Identity Server login page).
Inside Docker environment is also Redis which is required for separated API and Identity Server (and works).

The problem is just Angular. Login page is loaded without problems, but when someone tries to login, there is
CORS issue (looking in Developer Tools - Network).
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

Doen anyone have similar issues?

**Comment by mehmet-erim** [comment]
Hi @leonkosak

What is your Angular app running URL?

**Comment by leonkosak** [comment]
@mehmet-erim The problem is CORS issue, not URL. Of course, there are separated URLs (IPs) for API, IS and Angular.
Look also https://github.com/abpframework/abp/issues/3815

We have all in containers (API, IS, Angular, Nginx,... even DbMigrator and databases).
We also use Portainer (business reasons) and not docker-compose. API, IS and Angular are reacheable through Docker bridge to Ubuntu OS.
Login to IS is working (via interal Docker IP or external to host). API is working (swagger is visible) and non protected GET methods return result (200 - OK).
The only missing part is Angular.

![image](https://user-images.githubusercontent.com/39346964/90792854-4cbfb900-e30b-11ea-90c1-4ece683c3227.png)
172.20.10.11:11500 is external (host) (172.20.10.11 is gateway in docker).

How can header "Access-Control-Allow-Origin" be added? I think that Nginx is required.
(Someday, ssl connection would also be required.)

Does someone have similar installation and can share Dockerfiles and nginx.conf for each project?

Thank you.

**Comment by maliming** [comment]
hi @leonkosak  
Everything is fine in API application logs?

Maybe the plain asp net core application will have the same problem according to your deployment method because abp is also using the cors of asp net core.

**Comment by leonkosak** [comment]
Agh! Wrong CorsOrigins defined in .IdentityServer. :(
