### ISSUE TITLE
Exception Subscribers in unit tests

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#5092]
Hello,

I'm setting up something to use ExceptionSubscriber, seems to work fine, except I'm not sure how to get this working in unit tests?

**Comment by hikalkan** [comment]
I am assuming you're building a web application.

ABP handles exceptions in the exception action filter, in the web layer. If you are developing an integration test (that includes the aspnet core pipeline), your handler is executed as like in a normal web request.

However, for unit tests or testing up to the application layer, ABP won't handle exceptions. So, your test code should use `Assert.Throws[Async]` to handle and check if it expects an exception.
