### ISSUE TITLE
How to assign value to AppUser attribute when adding user(IdentityUser)

### ISSUE THREAD

**Issue by aricyu** [abpframework/abp#5095]
Version:3.0.5

Hi，thanks abp.
Currently I am using `IdentityUserManager.CreateAsync(identityUser)` to add user, but I added an attribute `NickName` to `AppUser`. How do I assign a value to `NickName` when adding a user?

#### AppUser
```
public class AppUser : FullAuditedAggregateRoot<Guid>, IUser
{
    //....

    
    public virtual string NickName { get; set; }
}
```

#### ConfigureCustomUserProperties
```
public static void ConfigureCustomUserProperties<TUser>(this EntityTypeBuilder<TUser> b)
    where TUser : class, IUser
{
    b.Property<string>(nameof(AppUser.NickName)).HasMaxLength(64);
}

```

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/938bab5b6a451032b688deb3ace92d1de0ff79fc/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Users/AppUser.cs#L10-L13

**Comment by aricyu** [comment]
What do you mean?
How to assign values to AppUser's custom fields?

**Comment by mtozlu** [comment]
@ChiakiYu 
You can use `SetProperty` method to set extra properties:
```user.SetProperty("NickName", "ChiakiYu");```

**Comment by rygar08** [comment]
some documentation would be helpful
