### ISSUE TITLE
Why is default warehousing an instantaneous lifecycle?

### ISSUE THREAD

**Issue by mzqs5** [abpframework/abp#5098]
Recently, I was troubled by a problem. When using the same repository in different services, one added a piece of data, and the other queried the new data, and found that it could not be found. Later, we found that the instantaneous life cycle of the repository was not the same object. Should the warehouse be set to scope singleton according to the user's request to the end of the same unit of work?

**Comment by realLiangshiwei** [comment]
Hi,
It has nothing to do with life cycle, See https://docs.abp.io/en/abp/latest/Unit-Of-Work#alternative-to-the-savechanges
