### ISSUE TITLE
Set `-m none` as a default for the ABP CLI

### ISSUE THREAD

**Issue by cotur** [abpframework/abp#5106]
For now, [abp cli](https://docs.abp.io/en/abp/latest/CLI) creates mobile project with default.

I think the mobile project creation should be optional.

It will be more good if we have a command that creates default empty mobile project whenever we want (adding mobile project to an exist project).

**Comment by gdlcf88** [comment]
Should the option `-m none` for mobile framework be added to the "en" [CLI document](https://github.com/abpframework/abp/pull/5107/files#diff-1a13459b5e34fe6a32671df319068e50L82-R83)?
