### ISSUE TITLE
Forget/reset password UI (Angular)

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#5113]
Related : https://github.com/abpframework/abp/issues/2608

**Comment by hikalkan** [comment]
Thanks @realLiangshiwei for opening this issue. However, we won't implement this for the Angular UI. Because, beginning from the v3.1, Angular UI uses the MVC login form to authenticate the user (via authorization code flow) and all the MVC functionalities will be available to the Angular side.
