### ISSUE TITLE
can not login by http (no ssl)

### ISSUE THREAD

**Issue by nonepassby** [abpframework/abp#5114]
- env:
abp version: 3.0.5
os: windows 10
app: demo app (just change db to mysql)

- problem:
use http://localhost:5000, user admin login failed.
use https://localhost:5001, user admin login success.

- logs from _http://localhost:5000_:

**Comment by maliming** [comment]
Related https://github.com/abpframework/abp/blob/9adab77257b31d40e4e4b1ae826a813d075efe4e/docs/en/Community-Articles/2020-08-12-Patch-Chrome-Login-Issue-For-IdentityServer4/POST.md
