### ISSUE TITLE
Solution for unable to log in via http in the new chrome.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#5138]
The new Chrome will block your application cookies because of the `SameSite` problem.

Error message in the console.
> A cookie associated with a resource at http://example.com/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.`

There are two solutions:
1. Use **https** for your website.(**recommend**)

2. **Add SameSite Cookie Policy**

https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/host/Extensions/SameSiteHandlingExtensions.cs
https://github.com/IdentityServer/IdentityServer4/blob/c62ae5edd69ef087a99deb62abe7e45c1cdb2bb0/src/IdentityServer4/host/Startup.cs#L43
https://github.com/IdentityServer/IdentityServer4/blob/c62ae5edd69ef087a99deb62abe7e45c1cdb2bb0/src/IdentityServer4/host/Startup.cs#L113

**Comment by hikalkan** [comment]
I suppose this is same of https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n right?
