### ISSUE TITLE
Upgrade the ABP to 3.0.5 version failed with the Nuget for the solution

### ISSUE THREAD

**Issue by jack-gaojz-zz** [abpframework/abp#5144]
Current ABP version: 3.0.1
Visual Studio version: 2019 16.7.2

Description: Manage Nuget Packages for Solution -> Update all the "Volo.Abp.*” packages failed.
Always display the error messages: Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/40879710/90948035-421d3500-e46d-11ea-829a-b1c46f1d838e.png)

**Comment by maliming** [comment]
This is nothing to do with abp. You can try to edit the `csproj ` file of the project .

**Comment by jack-gaojz-zz** [comment]
> This is nothing to do with abp. You can try to edit the `csproj ` file of the project .

When I upgraded from 2.9.0 to 3.01, everything is ok. But upgrade 3.0.1 to 3.0.5 faield.

**Comment by hikalkan** [comment]
This problems seems related to NuGet package manager. A package can not do it.
