### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by banitt** [abpframework/abp#5151]
1. https://docs.abp.io/api-docs/abp/rel-3.1/api/index.html (link in table of contents) redirects to 404
2. https://docs.abp.io/en/abp/latest/Best-Practices/Entities is not inserted in table of contents
3. Search is not working: https://docs.abp.io/search/en/abp/3.0/?KeyWord=Domain+Driven+Design

**Comment by hikalkan** [comment]
Thanks for reporting these.

1. We are currently publishing it. 3.1 is RC. It will be available soon. @erolarkat can you write when it is ready.
2. It is referenced from https://docs.abp.io/en/abp/latest/Best-Practices/Index Didn't add to the navigation menu, intentionally.
3. Duplicate of https://github.com/abpframework/abp/issues/5132 @maliming will it work with the next deploy?

**Comment by erolarkat** [comment]
Hi,

https://docs.abp.io/api-docs/abp/rel-3.1/api/index.html is available now.

**Comment by maliming** [comment]
Search works now.
