### ISSUE TITLE
Entering a password that does not meet the rules causes concurrent errors.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#5157]
**Mongodb + MVC** 
Maybe also exists in EF Core.

![image](https://user-images.githubusercontent.com/6908465/91129380-83ffe280-e6dc-11ea-9917-11553f7784b3.png)

![image](https://user-images.githubusercontent.com/6908465/91129405-911cd180-e6dc-11ea-9f4c-3fd5c880b528.png)

**Comment by hikalkan** [comment]
Interesting. It should be normally rollback the transaction, so the concurrency token in the database remain unchanged.

**Comment by hikalkan** [comment]
There is no transaction support with mongodb. it should not be a problem with ef core.

**Comment by hikalkan** [comment]
Should wait for https://github.com/abpframework/abp/issues/347
