### ISSUE TITLE
MongoDb transaction is not rolled back.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#5158]
**MVC + MongoDb**

![image](https://user-images.githubusercontent.com/6908465/91130099-b52ce280-e6dd-11ea-813b-6b521bf606f3.png)
![image](https://user-images.githubusercontent.com/6908465/91130158-cb3aa300-e6dd-11ea-830d-3c569c35fba0.png)

**Comment by realLiangshiwei** [comment]
Related https://github.com/abpframework/abp/issues/347

**Comment by hikalkan** [comment]
There is no transaction support with mongodb

**Comment by hikalkan** [comment]
should wait for https://github.com/abpframework/abp/issues/347
