### ISSUE TITLE
[question]can I set some applicatoin service use special JsonSerializerOptions

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#5159]
abp v3.0.5

Can I set some services to return JSON in a specific format instead of all services?

```
var options = new JsonSerializerOptions
{
    IgnoreNullValues = true,
    WriteIndented = true
};
jsonString = JsonSerializer.Serialize(weatherForecast, options);
```

what should I do?

**Comment by xyfy** [comment]
Because some interfaces get large data back, they need to compress the fields, and some fields with null values do not want to be returned to the foreground

**Comment by xyfy** [comment]
Can only create a new class to resolve it ? or other way??

**Comment by hikalkan** [comment]
I suppose there is no way to specialize a JSON serializer for a specific service in ASP.NET Core. You can try some workarounds (e.g. writing an aspnet core middleware to re-serialize it on a matching URL pattern).

**Comment by xyfy** [comment]
it can do in controller,but can not in the application service 

but the `microservice`'s api  need implete the `application service `
