### ISSUE TITLE
Module development: AddDefaultRepositories(includeAllEntities: true) not working.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#516]
In my module, I have a normal entity `AEntity`.
* I didn't add `DbSet<AEntity>` propertie to my DbContext interface since [Entity Framework Core Integration Best Practices](https://github.com/abpframework/abp/blob/master/docs/Best-Practices/Entity-Framework-Core-Integration.md#dbcontext-interface) said only aggregate roots should be added.
* I didn't define `IAEntityRepository` and its implementation for the same reason --- it is not a aggregate entity.

Now I want ABP to automatically create a repositoriy for `AEntity`, so I use the following code but it didn't work:

``` csharp
            context.Services.AddAbpDbContext<MessageBoardDbContext>(options =>
            {
                /* Add custom repositories here. Example:
                 * options.AddRepository<Question, EfCoreQuestionRepository>();
                 */
                options.AddDefaultRepositories(includeAllEntities: true);
            });
```

After debugging, I found that it might be related to this:

https://github.com/abpframework/abp/blob/f62ed01ac24433dcdc0faf02400fc871caa65dbe/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/DbContextHelper.cs#L13-L21

Method `GetEntityTypes` uses reflection to get entity types from DbContext  type and then [RegisterDefaultRepositories](https://github.com/abpframework/abp/blob/f62ed01ac24433dcdc0faf02400fc871caa65dbe/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Repositories/RepositoryRegistrarBase.cs#L32) uses them to create repositories.

But I didn't have entity type added in my DbContext....

**Comment by hikalkan** [comment]
Hi @wakuflair,

Best practices works together. Adding DbSet only for aggregate roots is a best practice (if you want to be ORM independent and want to apply DDD best practices). But also setting includeAllEntities to false (which is actually default) is a best practice for same reason.

So, if you want to use repository for non-aggroot entities, then add them to the DbContext as DbSets and use includeAllEntities: true.
