### ISSUE TITLE
When clicking the menu item, route changes but menu stays opened

### ISSUE THREAD

**Issue by ismcagdas** [abpframework/abp#5160]
Here is a sample screenshot;

![image](https://user-images.githubusercontent.com/4133525/91145250-d2ea4f80-e6bd-11ea-81cb-fbc977e4d0f1.png)

**Comment by hikalkan** [comment]
I think this is because you are still on the menu item with the mouse and the page switch is so fast :)

**Comment by ismcagdas** [comment]
Yes, the mouse pointer is still on the menu item. But, I expect menu to close when I click a menu item.
