### ISSUE TITLE
HOW TO CHANGE LOGO IN THE DEFAULT TEMPLATE? 

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#517]
Or should I say, add one

**Comment by hikalkan** [comment]
Simplest way: https://github.com/abpframework/abp/blob/master/templates/mvc/src/MyCompanyName.MyProjectName.Web/Branding/MyProjectNameBrandingProvider.cs

Override LogoUrl here. For more advanced cases, you can replace template's components/views.

**Comment by wocar** [comment]
How can i add a logo using the default theme because i did override the logourl and it is not showing up

**Comment by hikalkan** [comment]
Oh, yes Basic theme does not support it yet, sorry.

* Copy [this file](https://github.com/abpframework/abp/blob/master/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Components/Brand/Default.cshtml) to your Web project (under `Themes/Basic/Components/Brand/Default.cshtml` path).
* Make it embedded resource and register to the [virtual file system](https://abp.io/documents/abp/latest/Virtual-File-System).
* Change however you want. Your file will override theme's file.

**Comment by wocar** [comment]
Thank you 🙏🏼 very helpful Halil =)

**Comment by wocar** [comment]
Just to remark that you **must** correctly type the namespace of the webproject otherwise it wont map it correctly.
 ```
 options.FileSets.Add(
                    new EmbeddedFileSet(
                        typeof(ManagerWebModule).Assembly,"NAMESPACE.HERE.WEB"
                    )
                );
```
