### ISSUE TITLE
Dropdown button does not expand menu in mobile mode (narrow screen) in the replaced NavItemsComponent

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#5184]
2.9.0, Angular UI.
I have replaced **NavItemsComponent** according to documentation.
Everything works properly in _Desktop_ mode when I click Profile, language and other icons in top right corner. However, when I narrow the browser window and layout is switched to _mobile_ mode (two icons) - clicking _Profile_ icon does not expand dropdown menu. Such problem is not occured when using built-in **NavItemsComponent**.
Could you please confirm this is reproduced? If so - I think it may be something to do with **NgbDropdownMenu** registration...

**Comment by mehmet-erim** [comment]
Hi @alexandis

You should import the `SharedModule` (or `NgbDropdownModule`) to the `imports` array of `AppModule`:

```js
// app.module.ts

import { SharedModule } from './shared/shared.module';

@NgModule({
  imports: [
    //...
    SharedModule
  ]
)}
```

I will update the document. Thanks.

**Comment by alexandis** [comment]
Hi, I had **SharedModule** within **AppModule** (also **AppModule** has this: `declarations: [AppComponent,TenantsComponent,NavItemsComponent]`). And **SharedModule** has this: `import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';` and also in _import_ list. Still, it does not work. Probably it has something to do with the sequence of Modules in import or something else...

**Comment by mehmet-erim** [comment]
I don't encounter any errors after adding the import. Does the problem still exist?

**Comment by alexandis** [comment]
> I don't encounter any errors after adding the import. Does the problem still exist?

I cannot check this out, because after upgrade to 3.1.2 something has been broken in Angular part. This is how navigation component looks like now. Even if I don't replace the component - it looks in the same broken way. Do you know by chance what's happening?

![image](https://user-images.githubusercontent.com/6149843/94453533-75b05500-01b9-11eb-9520-14cd9901200b.png)

**Comment by alexandis** [comment]
> I don't encounter any errors after adding the import. Does the problem still exist?

Can't check it, because after upgrading to 3.1.2 have another issue with Navigation area: [https://github.com/abpframework/abp/issues/5642](url)
