### ISSUE TITLE
questio：Use GuidGenerator for CrudAppService

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#5188]
When I use CrudAppService to create API, the guid is generated by repository.insertAsync(entity,true),
which means db generate the id, for consistency, how to user GuidGenerator for CrudAppService

**Comment by maliming** [comment]
It's already has used the GuidGenerator.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/AbstractKeyCrudAppService.cs#L161

**Comment by evenlee** [comment]
Thanks for clarify @maliming ,see the code now, closed.
