### ISSUE TITLE
.min file access problem

### ISSUE THREAD

**Issue by cem1835** [abpframework/abp#5193]
![min file bug](https://user-images.githubusercontent.com/17495243/91418399-bfc0b680-e85a-11ea-8963-573f1c7dc837.PNG)

We generally have problems with .min file extensions.

The jquery-knob.min.js  in the picture returned 404 on the server but working on local. (Module Project)
İnfo: The project's bundling mode:none 
and  everything in the sample 2 files is the same (content type etc.)

**Comment by realLiangshiwei** [comment]
Hi,

I can't reproduce your problem.

![image](https://user-images.githubusercontent.com/16813853/91425735-20b5b200-e88e-11ea-9465-69375dbe5461.png)

* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by cem1835** [comment]
> Hi,
> 
> I can't reproduce your problem.
> 
> ![image](https://user-images.githubusercontent.com/16813853/91425735-20b5b200-e88e-11ea-9465-69375dbe5461.png)
> 
> * Your **ABP Framework version**.
> * Steps needed to **reproduce** the problem.

ABP Framework version 2.9.0
you tried it on a local server but the problem is on IIS. Also works on my local pc too. ( and please create same file structure /js/candidate-statistic/jquery-knob.min.js)

**Comment by realLiangshiwei** [comment]
I still can't reproduce your problem.

![image](https://user-images.githubusercontent.com/16813853/91437681-d556d000-e89c-11ea-834b-73775b8aa163.png)
