### ISSUE TITLE
Feature suggestion: Serilog.Sinks.File on deployable projects (.NET Core)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#5199]
It would be nice to add Serilog.Sinks.File (which is present in .DbMigrator project) to other deployable projects
(web - .Host, .IdentityServer for instance).

and added this line in Program.cs:

```
.MinimumLevel.Override("Microsoft", LogEventLevel.Information)
.Enrich.FromLogContext()
.WriteTo.Console()  //ADD THIS LINE
.WriteTo.File("Logs/logs.txt")
.CreateLogger();
```

Writing log to console is useful when you have application inside Docker. :)
What do you think guys?

**Comment by maliming** [comment]
Agree,  Especially when an error occurs while using the Rider, I need to check the log file instead of the console. : )

**Comment by leonkosak** [comment]
One more suggestion at this point.
Wouldn't be nice to move hardcoded "Logs/Logs.txt" in appsettings.json files?
https://github.com/serilog/serilog-settings-configuration

Even the code in Program.cs would be much simpler to init.

```
var configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json")
        .Build();

    var logger = new LoggerConfiguration()
        .ReadFrom.Configuration(configuration)
        .CreateLogger();
```

**Comment by Rwing** [comment]
Agree, but there seems to be a performance issue when using console logging.
FYI https://weblog.west-wind.com/posts/2018/Dec/31/Dont-let-ASPNET-Core-Default-Console-Logging-Slow-your-App-down

**Comment by maliming** [comment]
`AddConsole `for `debug `or `development ` will be good.

**Comment by leonkosak** [comment]
@maliming what about Serilog.Settings.Configuration? With Serlilog configuration inside appsettings.json you can enable console logging on-the-fly when needed without recompiling the code.

**Comment by maliming** [comment]
@leonkosak sounds great, I will check it.

**Comment by maliming** [comment]
@hikalkan 

Should we use `serilog-settings-configuration`? what do you think?
https://github.com/serilog/serilog-settings-configuration

**Comment by hikalkan** [comment]
>Should we use serilog-settings-configuration? what do you think?

Seems fine.

**Comment by maliming** [comment]
It seems `serilog-settings-configuration` is not actively developing.  Back to https://github.com/abpframework/abp/issues/5199#issuecomment-682278787

**Comment by leonkosak** [comment]
Where did you get this info? Last commit?

**Comment by NecatiMeral** [comment]
Hi @maliming 
your adjustments are great. But wouldn't it make sense to change the file extension to *.log instead of *.txt?

**Comment by leonkosak** [comment]
The first problem is, that Logs file grows relatively fast. The second problem is that there are no new files created (each day or when specific filesize is reached).
Having log files inside folder where application is installed is far from ideal situation. You have to stop service, rename/delete log file in start again.

I don't see that serilog-settings-configuration is not maintained. It just works for the its purpose. :)

**Comment by maliming** [comment]
hi @NecatiMeral @leonkosak 
We just provide a basic configuration, you can change it freely.  : )
