### ISSUE TITLE
Providing --dryRun parameter with abp-cli

### ISSUE THREAD

**Issue by bnymncoskuner** [abpframework/abp#5208]
When generating code with `angular-cli`, if you pass `--dryRun`, `angular-cli` runs the given command and outputs whatever would be generated but it does not generate any code. Sometimes, it is quite to useful to check what will be generated before running the actual command. If `abp-cli` has a similar parameter, it will be useful to the users.

**Comment by iyilm4z** [comment]
Hi @hikalkan, 

I see that this is an old issue and there is no action for it yet. Maybe nowadays you are focusing your attention on other points.
I may work on this issue? If you are ok, below is my possible solution.

- Create an interface named like **IDryRunnableCommand** which has a void typed  method named **DryRunAsync**
- Before running a command first check if an option named **dry-run** passed 
- Check if IDryRunnableCommand interface implemented by given command
- If so, just call **DryRunAsync** method which just logs to console what the command really does
- Return early.

**Comment by hikalkan** [comment]
We don't want to make that. It is too complicated. For example, `abp new` command does a lot of things and it is not possible to write it to the console.
I am closing this @iyilm4z :)
