### ISSUE TITLE
Hide item administration on Menu 

### ISSUE THREAD

**Issue by TuyenDinh1205** [abpframework/abp#5212]
I want to hide administration on menu. I'm using route.provider
 Please help me how to do it

ABP Framework version: 3.0.5
 User Interface type: Angular

![error](https://user-images.githubusercontent.com/34994601/91516826-a7ae6d00-e916-11ea-8935-8f45285d8fbd.PNG)

**Comment by mehmet-erim** [comment]
Hi @TuyenDinh1205 

You can patch the "Administration" route value as shown below:

```ts
import { RoutesService } from '@abp/ng.core';
import { Component } from '@angular/core';
import { eThemeSharedRouteNames } from '@abp/ng.theme.shared';

@Component(/* component metadata */)
export class AppComponent {
  constructor(private routes: RoutesService) {
    this.routes.patch(eThemeSharedRouteNames.Administration, { invisible: true });
  }
}
```

See the [Modifying the Menu document](https://docs.abp.io/en/abp/latest/UI/Angular/Modifying-the-Menu) for more information.

**Comment by alexandis** [comment]
How to make invisible an element inside of any top section or even deeper?
