### ISSUE TITLE
When tiered templates, tenants of independent databases cannot login (AngularUI).

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#5215]
Related https://github.com/abpframework/abp/issues/5213

Should add tenant key to the request.

![image](https://user-images.githubusercontent.com/16813853/91529174-69777480-e93b-11ea-8853-090e7a67859e.png)

**Comment by hikalkan** [comment]
Closing?

**Comment by realLiangshiwei** [comment]
Reproduced the problem using the v3.1 template.

@mehmet-erim Could you check it?

![image](https://user-images.githubusercontent.com/16813853/92340374-a33f3c80-f0ec-11ea-8d32-32fb7f5df52b.png)

![image](https://user-images.githubusercontent.com/16813853/92340382-acc8a480-f0ec-11ea-9cd9-a2cf566b6e5b.png)

**Comment by mehmet-erim** [comment]
Hi @realLiangshiwei 

It can't be reproduced in v3.2.0-rc.2 template. Can you try again? If the problem still exists, can you explain the reproducing steps in detail?

**Comment by realLiangshiwei** [comment]
okay, I will try again and tell you the result.

**Comment by realLiangshiwei** [comment]
@mehmet-erim 
I used v3.2.0-rc.2 template, the pro template also has this problem.

First, create a tenant:

![image](https://user-images.githubusercontent.com/16813853/94394896-07579c80-0191-11eb-8901-2f9783e40fb7.png)


Then, run the `DbMigrator` application and use `tenant` to login.

![ng](https://user-images.githubusercontent.com/16813853/94395315-007d5980-0192-11eb-9a5b-a29791ebe1a0.gif)

**Comment by FriHub** [comment]
same issue here with a new Blazor project, created with abp suite (4.0.0).

**Comment by allstarcrypto** [comment]
any resolution on this?

**Comment by hikalkan** [comment]
Hi,

We had progress but could not solved the problem yet. Will be working on.
