### ISSUE TITLE
Background workers: Parallel processing - concept

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#5217]
Situation:
Each tenant has its own dedicated database. The current implementation (look code below) is working, but is serial and therefore relatively slow if there are a lot of tenants and data for processing is growing fast (in each tenant).

```
public class AcceptedMessageImportBackgroundWorker : AsyncPeriodicBackgroundWorkerBase
{
	private readonly AcceptedMessageImportLogic _acceptedMessageImportLogic;
	private readonly ITenantRepository _tenantRepository;
	private readonly ICurrentTenant _currentTenant;

	public AcceptedMessageImportBackgroundWorker(
		AbpTimer timer, IServiceScopeFactory serviceScopeFactory,
		AcceptedMessageImportLogic acceptedMessageImportLogic,
		ITenantRepository tenantRepository,
		ICurrentTenant currentTenant
	) : base(timer, serviceScopeFactory)
	{
		timer.Period = 3000;
		_acceptedMessageImportLogic = acceptedMessageImportLogic;
		_tenantRepository = tenantRepository;
		_currentTenant = currentTenant;
	}

	protected override async Task DoWorkAsync(PeriodicBackgroundWorkerContext workerContext)
	{
		var tenants = await _tenantRepository.GetListAsync();
		foreach (var tenant in tenants)
		{
			using (_currentTenant.Change(tenant.Id))
			{
				try
				{
					await _acceptedMessageImportLogic.StartImportLogicForNewAcceptedMessages(tenant.Id);
				}
				catch (Exception e)
				{
				}
			}
		}
	}
}
```

There are some articles on the web where authors states that using [TPL Library](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl) inside web application (web server exactly) is not recommended.

Worker which is defined above would run in "Console Application" and not web server and that's fine. If each tenant would have its own dedicated instance of such background worker Docker image (aka container) - what possible side effects could appear in production runtime environment?
(You can assume that each instance (container) would get TenantId as parameter in main method - so that start of background method would look like:

`await _acceptedMessageImportLogic.StartImportLogicForNewAcceptedMessages(tenant.Id);`

without boilerplate code for tenants search in for loop for each tenant.)

The second question is related to _degree of parallelism inside one instance_ of background worker (Docker container).
New records (messages) come in tenant db and have bigint for id.
Let's say that we want degree of parallelism **4** and that new records with the following ids were assigned to new messages:

122, 123, 124, 125, 126, 127

Each worker instance would get parameter fo degree of paralellism (4 in this case) and which is its number based on [modulo calculation](https://en.wikipedia.org/wiki/Modulo_operation) for id (in this case 0, 1, 2, 3).

Instance with 0 would get: 124
Instance with 1 would get: 125
Instance with 2 would get: 122, 126
Instance with 3 would get: 123, 127

Importing message (which are inside JSON data and have ids 122-127) are multi-stage process, so each instance would update data for each stage (columns in the same table as messages 122-127).

Question: Does anyone have experience with such design of background workers and what performance benefits are expected (you can assume that sql database is not too-overloaded with queries)?
Let's say that importing one message takes for instance 1.5s.
If degree of parallelism could be set to higher than 1 (serial import on-by-one), this should import these 6 messages (122-127) faster than 6x1.5s?

Thank you.

**Comment by hikalkan** [comment]
Would you consider to use RabbitMQ or HangFire provider for background jobs? It is possible to process messages in parallel with them.

**Comment by duyan11110** [comment]
Hi @leonkosak,

I have the same problem when running background work in parallel for all tenants. Have you solved this issue? If yes, could you pls share the solution?

Thank you so much

**Comment by leonkosak** [comment]
@duyan11110 you can make console application, which periodically grab all tenantids and then with Task (TPL library) call REST API method with different tenant in parallel.

**Comment by duyan11110** [comment]
@leonkosak 
Thanks for your sharing, but I'm seeking a solution with Hangfire for more flexible configuration of job's schedule for each tenant.

**Comment by leonkosak** [comment]
@duyan11110 there is no difference.
Use cron expressions in a console application (using hangfire/Quartz) for each individual tenant and always calculate next execution time (in the future) based on "base startup time in the past".
In a console application trigger tenant query for tenants which have "next execution time" before the current time.
This infinite tenant query should be triggered periodically for instance every 10 seconds. This "time resolution" should be defined based how often specific cron job should be executed.
One job should be executed for instance every minute and each tenant have for instance 5 second delay, so that pressure on SQL is not too high at the same time. In such case, I would set periodic trigger for tenants in a console application every 5 seconds.
Keep i mind that I would create multiple instance of this console application, so that one instance is statically call execution logic for tenant1, tenant2,.. and other instance for others.

For even more deterministic execution I would define "start every 5 seconds" inside a console application based on time (for instance at 01, 06, 11 seconds after each minute). This approach is also achieved via cron expressions.

Additional tip: Keep timestamp for cron jobs execution and next execution times in UTC.

Additionally, for each instance of a console application set an instance nape in appsettings.json and for each tenant set the name of instance which is dedicated to trigger execution on REST API.

Kepp null instance value as default (and first) instance name.

**Comment by leonkosak** [comment]
Also keep in mind that each instance of a console application, which triggers REST API call for background job execution should run strictly only on one "node" in a cluster environment (for instance k8s cluster). Otherwise, race-condition issues will appear and potential deadlocks in databases.

**Comment by Gilcemir** [comment]
> Would you consider to use RabbitMQ or HangFire provider for background jobs? It is possible to process messages in parallel with them.

How is it possible?
We cant process in parallel using rabbitMQ, because the Queue runs the events as fifo (just release next job after ack).
