### ISSUE TITLE
ExtraProperties field is not registered in MongoDb.

### ISSUE THREAD

**Issue by ertucaglar** [abpframework/abp#5218]
I abp.io framework version is 3.0.5

I'm using multiple database provider. PostgreSQL and MongoDB.

This my collection model for MongoDb collection.

`public class UserCollection : AggregateRoot<Guid>, IHasCreationTime, IHasModificationTime
    {
        public string Title { get; set; }
        public string Picture { get; set; }
        public string SubTitle { get; set; }
    }`

However, when I add a record in this model, extraProperties does not appear in mongodb.

**My collection entity with binded extraProperties:**
<img width="648" alt="Screenshot at Aug 28 11-21-20" src="https://user-images.githubusercontent.com/4929653/91538785-0678e400-e921-11ea-8c02-b313b2864bbe.png">

**My mongodb context:**
`modelBuilder.Entity<UserCollection>(p =>
            {
                p.BsonMap.TryConfigureExtraProperties();
            });`

But missing ExtraProperties field in mongodb records.

**Comment by realLiangshiwei** [comment]
Please provide steps to reproduce

**Comment by ertucaglar** [comment]
I do not understand exactly what you want. Can you elaborate a little more please...

**Comment by realLiangshiwei** [comment]
I mean how to reproduce your problem.

**Comment by ertucaglar** [comment]
Sorry, ok...

In my case...

- Followed abp.io mongodb instruction
- Create a mongodb collection entity your solution with extend AggregateRoot<Guid>.
For example:
`public class UserCollection : AggregateRoot<Guid>
...`
- Create new record on mongoDb:
`var row = new UserCollection();
var entity = new EntityDto();
entity.Title = "Test row";
row.SetProperty("Entity", entity);
_repository.InsertAsync(row);`

Then saved record to mongodb with all nested fields, but missing ExtraProperties field.

**Comment by realLiangshiwei** [comment]
Hi,

For mongo, it is stored as a regular field, see the document: https://docs.abp.io/en/abp/latest/Entities#how-is-it-stored

**Comment by ertucaglar** [comment]
Oh nooo... :( ok thank you.
