### ISSUE TITLE
Authorization failed! Given policy has not granted

### ISSUE THREAD

**Issue by ertucaglar** [abpframework/abp#5220]
Version: 3.0.5

I working on localhost and authentication is successful.

**On Localhost:**
1. Call to "/connect/token" with request body and than response the access_token
2. Call to "/api/identity/my-profile" with Bearer token and than response is current user information

However, AWS Elasticbeanstalk is not responding to the current user in production mode.
**On AWS**
1. Call to "/connect/token" with request body and than response the access_token
2. Call to "/api/identity/my-profile" with Bearer token and than response is "Authorization failed! Given policy has not granted."

I can receive tokens, but when I send a request with the token, it cannot find the user. What can be the problem?

**UPDATE**
I was sending the wrong request for current user information.
"/api/identity/my-profile" to "/connect/userinfo"

**But...**CurrentUser is null although login process is still successful in application

**Comment by maliming** [comment]
You can check the application logs.

**Comment by ertucaglar** [comment]
In my case, i setup the secure url on AWS Elasticbeanstalk, resolved this issue.
