### ISSUE TITLE
Permission Management responds slowly

### ISSUE THREAD

**Issue by kzmyvr** [abpframework/abp#5224]
Hi,

![image](https://user-images.githubusercontent.com/5845762/91625103-42f22180-e9ad-11ea-8159-1d2570dfb34e.png)

Permission modal very slow opening. 

version : 3.1.0-rc.3 - mvc
database : mysql

`2020-08-29 03:53:01.397 +03:00 [INF] Executed page /AbpPermissionManagement/PermissionManagementModal in 14490.3918ms
2020-08-29 03:53:01.397 +03:00 [INF] Executed endpoint '/AbpPermissionManagement/PermissionManagementModal'`

**Comment by colinin** [comment]
the permission services are not cache hit and are not batch queried for multiple providers, it is recommended to override the **PermissionAppService** to predetermine all providers that the permission needs to be retrieved and then batch queried, of course you can also use the cache

**Comment by hikalkan** [comment]
Is that a one time problem or is it always slow? Actually, there is a caching system that uses Redis. Sometimes I see that redis cache is very slow. Are you using a local redis server, are you trying it in dev environment?

**Comment by kzmyvr** [comment]
@hikalkan Hi, yes it's always slow. I do not use redis. I'm experimenting in the dev environment.
