### ISSUE TITLE
AbpIdentityOptionsFactory can not get currentUser or currentTenant

### ISSUE THREAD

**Issue by zh-wq** [abpframework/abp#5225]
Version: 3.0.5

While I want to define password for tenants, I override password settings by add WithProviders(TenantSettingValueProvider.ProviderName). However, when I set password for tenant users, I found that the password is not with correct passwordValidators. The reason is that I can not get currentTenant in AbpIdentityOptionsFactory or TenantSettingValueProvider.

**Comment by maliming** [comment]
* Steps needed and code to **reproduce** the problem.

**Comment by zh-wq** [comment]
![image](https://user-images.githubusercontent.com/27350164/91652976-b770b180-eace-11ea-818c-949093739b20.png)

**Comment by maliming** [comment]
Please provide full details. Thanks.

**Comment by zh-wq** [comment]
The code above is only for find out what is wong. I try to inject the class above in IdentityUserManager and call "OverrideOptions" methd, Then I can get passwordValidators with tenant settings, which is what I want. The debug info show me that there is current user and tenant only in the last instance I injected.
