### ISSUE TITLE
Multi-Tenancy but some of tenant need binding domain name

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#5236]
I already  deploy a Multi-Tenancy website and work fine. 
someting like :
``` text
companyName1.demo.com.tw 
companyName2.demo.com.tw
``` 
iis binding setting will be : 
``` text
*.demo.com.tw
demo.com.tw
``` 
In some of case:
i already  buy  a domain name : companyName.com.tw   
iis binding setting will be:
``` text
*.demo.com.tw
demo.com.tw
companyName.com.tw
``` 

Question : 
how to  fixed  tenant when user visit by http://companyName.com.tw (same as http://companyName2.demo.com.tw) ?

Create Domain Tenant Resolver?

**Comment by realLiangshiwei** [comment]
You can create your own tenant resolver. https://docs.abp.io/en/abp/latest/Multi-Tenancy#custom-tenant-resolvers

**Comment by ChangYinShung** [comment]
So in my custom tenant resolver will :
Will find that if current domain name is `companyName.com.tw`  then set  context.TenantIdOrName=companyName (tenant will be set as `companyName`)

i will try it ,thanks.
