### ISSUE TITLE
use DotNetty in abp  web  application

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#5248]
Can i use **dotnetty**  in abp  web  application, reuse the service to handle **http** request and **tcp** command ?
i have tried,but got some errors ,the service  can't  init  ...... maybe  some troubles in  Ioc or DI.

can you give me some useful tips ?

**Comment by hikalkan** [comment]
I personally don't have experience with dotnetty. Anyone?

You can ask this to Stackoverflow to get a better response.
