### ISSUE TITLE
What is the difference between the two project templates?

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#525]
Hi,

Apologies if this is in the documentation somewhere. I did have a read but could not find anything. What is the difference between the two?

![image](https://user-images.githubusercontent.com/4738140/46665135-b39fc180-cc0e-11e8-8b29-9c5ee1a37db8.png)

**Comment by hikalkan** [comment]
ASP.NET Core MVC Application documentation: https://abp.io/documents/abp/latest/Tutorials/AspNetCore-Mvc/Part-I

MVC Module documentation is not available. This template is used to develop reusable application modules based on the best practices described here: https://abp.io/documents/abp/latest/Best-Practices/Index
