### ISSUE TITLE
BlobStoring：How to get the file access URL when using Aliyun, AWS

### ISSUE THREAD

**Issue by aricyu** [abpframework/abp#5252]
**ABP Framework version**:3.0.5

The current practice of BlobStoring is to obtain the file stream from `Aliyun` and then return it to the front end. This is obviously a wasteful behavior.
Is there a way to get the file access URL? 
I really want to get files directly from `Aliyun` instead of going through my own server.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/4989#issuecomment-670577121

**Comment by aricyu** [comment]
@maliming  Is it possible to add a GetAccessUrl method in `BlobProvider` and `BlobContainer`?
