### ISSUE TITLE
The project file may be invalid or missing targets required for restore

### ISSUE THREAD

**Issue by mperk** [abpframework/abp#526]
Hi,

I opened Volo.Docs.sln after rebuild framework.
It has 39 same Errors. You can see:
![image](https://user-images.githubusercontent.com/3465794/46665341-37848a00-cbcc-11e8-84c0-71c9a389728c.png)

I didn't rebuild the docs project.

**Comment by maliming** [comment]
Disable "Automatically check for missing packages during build in Visual Studio" in the Visual Studio options.
When you open a solution, first run dotnet restore in the root folder of the solution.

https://github.com/abpframework/abp#modulestemplates

**Comment by mperk** [comment]
This issue can close.
I still didn't fix it. But the problem is .net core.
