### ISSUE TITLE
How To Remove API  that  Inherit the application service interface and AbpController

### ISSUE THREAD

**Issue by yZuoB** [abpframework/abp#5270]
hi
I created a simple project
![image](https://user-images.githubusercontent.com/10497416/92049705-b933c100-edbd-11ea-8005-444f83cc00e2.png)
But the system has automatically generated the following interfaces,
![image](https://user-images.githubusercontent.com/10497416/92050102-cbfac580-edbe-11ea-99d8-2786054da253.png)

 such as this interface. 
![image](https://user-images.githubusercontent.com/10497416/92050111-d2893d00-edbe-11ea-9a91-bfa087819225.png)

I want to Remove this interface, but what should I do if it is not exposed. Removing the module has no effect?

**Comment by realLiangshiwei** [comment]
You can remove unnecessary modules

**Comment by yZuoB** [comment]
> You can remove unnecessary modules

Remove the  Volo.Abp.*.Web ??

**Comment by realLiangshiwei** [comment]
Example: you want to remove the feature-management

you need to remove all `AbpFeatureManagement*Module`
