### ISSUE TITLE
running api with dotnet command 

### ISSUE THREAD

**Issue by liej6799** [abpframework/abp#5286]
Hi, Is there a way to run the host application with dotnet command line.

Here are the things that I have tested:

- I can run the application with Visual Studio
- I can run the application with Rider 
- I can run with **dotnet run** command specifying the project like:
**dotnet run --project test.HttpApi.Host**
![image](https://user-images.githubusercontent.com/52598803/92130361-38191000-ee37-11ea-8fb0-de872dc48abb.png)

But when I want to run through dll or executable file it just exit immediately like:

- dotnet /bin/Debug/netcoreapp3.1/test.HttpApi.Host.dll
- or directly execute bin/Debug/netcoreapp3.1/test.HttpApi.Host
![image](https://user-images.githubusercontent.com/52598803/92131011-05bbe280-ee38-11ea-86ed-455f3abbadbe.png)

This is a latest project created and downloaded from the website. 
Is there anything I can do and did I miss out something?

The reason I want to do that, is for deployment and docker purposes.

**Comment by realLiangshiwei** [comment]
Please check logs

**Comment by liej6799** [comment]
Hi, this are the things I have tried:
a. tail the Logs/logs.txt but nothing shows
b. delete the logs.txt, after run the command it will not create new file.

My guess would be not related to the logs or something.


Anyway, can you run the command such as **dotnet test.HttpApi.Host.dll** in your environment, see you having the same issue?

**Comment by realLiangshiwei** [comment]
I tried, it works fine.

**Comment by liej6799** [comment]
Hi @realLiangshiwei thanks, I did not noticed there is a Log file from the bin folder. After checked it turns out the ports has been used haha. Thanks man I really appreciate it.. Anyway case closed now.
