### ISSUE TITLE
Proxy Generator: Recursive types cause infinite loop

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#5291]
```
PS D:\Document\Desktop\Mobest\mobest-alain> abp generate-proxy --apiUrl http://localhost:6298 --ui angular --module asm
[16:00:55 INF] ABP CLI (https://abp.io)
[16:00:55 INF] Version 3.1.0 (Stable)
? Please enter backend api name, a.k.a. remoteServiceName. (default: "default") 
Maximum call stack size exceeded
PS D:\Document\Desktop\Mobest\mobest-alain> 
```
Normal in other modules
Is there too many apis for this module?
Can you help me? THKS!

**Comment by armanozak** [comment]
Hi @hexianggui,

`Maximum call stack size exceeded` is usually  an infinite loop.

Could you please share the api-definition.json response and the environment.ts in your default Angular app?

BTW, the command parameters have changed, but it is not the reason behind this error.

**Comment by hexianggui** [comment]
THKS! 
I found the reason!
It's the Tree Dto
```
 public class ExceptionPartTreeDto : ExceptionPartDto
    {
        //public List<ExceptionPartTreeDto> Children { get; set; }
    }
```
I guess I'll have to switch to Tree at the front end
Do you have a goodidea?

**Comment by armanozak** [comment]
:)

I actually do have an idea for trees.

Check the `@abp/ng.components` package. It uses NgZorro tree with an adapter implementation for transforming flat models to a tree structure. You may find the source of the adapter [here](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/components/tree/src/lib/utils/nz-tree-adapter.ts).

Should we close this issue now?

**Comment by hexianggui** [comment]
> :)
> 
> I actually do have an idea for trees.
> 
> Check the `@abp/ng.components` package. It uses NgZorro tree with an adapter implementation for transforming flat models to a tree structure. You may find the source of the adapter [here](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/components/tree/src/lib/utils/nz-tree-adapter.ts).
> 
> Should we close this issue now?

yes,thank you very much!
