### ISSUE TITLE
No available test documents for Mocking with nsubstitute

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#5296]
Sorry To post here but I can’t find any documentation for using mocks in abp.io.

I'm trying to write a test for my FamilyAppService class (see below). I need to mock my IAutho instance in the constructor of the FamilyAppService. I tried mocking the IAutho With nsubstitute then adding it to a new instance of FamilyAppService (instead of using GetRequiredService()) but I get a 'System.ArgumentNullException' error with the ObjectMapper.

FamilyAppService Class
```
     public class FamilyAppService : KmAppService, IFamilyAppService { 
        private readonly IAutho autho;

        public FamilyAppService( 
            IAutho autho) {
 
            this.autho = autho;
        } 

        public virtual async Task SendRequest(SendRequestInput input) {
             var family = ObjectMapper.Map<FamilyDto, Family>(input.Family);
             // code ...
             await autho.FindUserIdByEmail(family.Email); 
        }
    }
```
Autho Class. I need to substitute the IAutho dependence with a Mocked class using nSubstitute

```
public class Autho : IAutho, ITransientDependency { 

        public Autho( ) {
        } 

        public virtual async Task<User> FindUserIdByEmail(string input) { 
            // Don’t want this code touched in test 
            // Code ...
        }
 
    }
```
My current test...

```
  [Fact]
        public async Task ShouldSendEmail() {
  
            var autho = Substitute.For<IAutho>();
            autho.FindUserIdByEmail(Arg.Any<string>()).Returns((User)null);  
    
            var familyAppService = new FamilyAppService(autho);
            // var familyAppService = GetRequiredService<IFamilyAppService>();

            // setup input code here..
            // get ObjectMapper error here
            await familyAppService.SendRequest(input);
 
            // Assert  
        }
```
https://stackoverflow.com/questions/63733699/how-do-you-mock-a-dependency-using-nsubstitute-in-abp-framework?noredirect=1#comment112706635_63733699

**Comment by maliming** [comment]
hi

You can refer to https://github.com/abpframework/abp/blob/d2b39c0087e3da6898367dc2b74401f314662fb0/modules/feature-management/test/Volo.Abp.FeatureManagement.Application.Tests/Volo/Abp/FeatureManagement/FeatureAppService_Tests.cs#L29-L33

**Comment by rygar08** [comment]
This is perfect, just what I needed. Thank you.
