### ISSUE TITLE
Generate-proxy:Multiple modules cannot be generated

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#5302]
An API endpoint has multiple modules
After producing one module, generate other modules will report an error
**ENOTEMPTY: directory not empty, rmdir**
Am I using it the wrong way?
```
PS D:\Document\Desktop\Mobest\mobest-alain> abp generate-proxy -m cms
......(the right generate )

PS D:\Document\Desktop\Mobest\mobest-alain> abp generate-proxy -m asm
[10:54:42 INF] ABP CLI (https://abp.io)
[10:54:42 INF] Version 3.1.0 (Stable)
? Please enter backend api name, a.k.a. remoteServiceName. (default: "default") 
ENOTEMPTY: directory not empty, rmdir 'D:Document\Desktop\Mobest\mobest-alain\src\app\proxy\cms\organizations'
```
This is the API definition screenshot
![2020-09-05_111237](https://user-images.githubusercontent.com/30622318/92296607-f5efeb80-ef68-11ea-861c-06634ec04120.png)

**Comment by hikalkan** [comment]
Is your Angular application running? If so, can you stop it and try again?
@armanozak can you check this?

**Comment by armanozak** [comment]
I don’t think this is about a running app. We have generated several modules in succession and have never received that error. The command even removes everything and regenerates all modules.

This error may be sth. about folder permissions, but I cannot reproduce it. Can you @hikalkan ?

**Comment by hikalkan** [comment]
I also haven't had this error before. I generally stop the angular app before proxy generation.

**Comment by armanozak** [comment]
Hi @hexianggui,

Are you running the command as administrator?

**Comment by hexianggui** [comment]
> Hi @hexianggui,
> 
> Are you running the command as administrator?

Sorry for the late reply！

I think I've figured it out.
Error executing command when I open project with VS.
Successful execution, when I close the project, execute the command using the PwoerShell.
**So this has nothing to do with ABP!**
Runing the command as administrator, or close all IO for the project.

Using vs 
![1](https://user-images.githubusercontent.com/30622318/92339267-d03d2080-f0e7-11ea-8929-46943452b86b.png)
Using powershell
![2](https://user-images.githubusercontent.com/30622318/92339287-e519b400-f0e7-11ea-9fe6-e78aaf66e378.png)

**thank you very much!**
