### ISSUE TITLE
JWT invalid_client

### ISSUE THREAD

**Issue by CaiJinHao** [abpframework/abp#5308]
![image](https://user-images.githubusercontent.com/16984784/92326420-9686fe00-f084-11ea-936f-65168a0c71c0.png)
数据库种子数据都有，使用这段代码会报invalid_client，但是使用Module 的IdentityServer能够登陆
![image](https://user-images.githubusercontent.com/16984784/92326452-f67da480-f084-11ea-8cc4-62686bd4480f.png)
请问，这种问题如何处理？

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Please **write in English**.

**Comment by wjkhappy14** [comment]
**### remind：Please write in English.**


my code works  well  

public async Task<TokenResponse> RequestPasswordTokenAsync()
        {
            DiscoveryDocumentRequest discoveryDoc = new DiscoveryDocumentRequest()
            {
                Address = BaseAddress,
                Policy = new DiscoveryPolicy()
                {
                    RequireHttps = false,
                }
            };
DiscoveryDocumentResponse disco = await HttpClient.GetDiscoveryDocumentAsync(discoveryDoc);

            if (disco.IsError)
                throw new Exception(disco.Error);
            TokenResponse response = await HttpClient.RequestPasswordTokenAsync(new PasswordTokenRequest
            {
                Address = disco.TokenEndpoint,
                Scope = "Trump",
                **GrantType** = "password",
                ClientId = "Trump_App",
                ClientSecret = "1q2w3e*",

                UserName = "Trump@stubid.com",
                Password = "stubid@Trump.com",
            });

            if (response.IsError)
                throw new Exception(response.Error);
            return response;
        }


Maybe you missing  the  **GrantType**

**Comment by CaiJinHao** [comment]
@maliming 
 ABP Framework version is 3.1
Using the Module template, I could not find the specific reason for the error below the Logs newspaper while testing JWT.
Error is as follows:
2020-09-07 13:42:19.468 +08:00 [DBG] client configuration validation for client MyBookStore_Web succeeded.
2020-09-07 13:42:19.478 +08:00 [DBG] No matching hashed secret found.
2020-09-07 13:42:19.478 +08:00 [DBG] Secret validators could not validate secret
2020-09-07 13:42:19.489 +08:00 [INF] {"ClientId":"MyBookStore_Web","Category":"Authentication","Name":"Client Authentication Failure","EventType":"Failure","Id":1011,"Message":"Invalid client secret","ActivityId":"0HM2IU2T834GB:00000003","TimeStamp":"2020-09-07T05:42:19.0000000Z","ProcessId":84124,"LocalIpAddress":"::1:44363","RemoteIpAddress":"::1","$type":"ClientAuthenticationFailureEvent"}
2020-09-07 13:42:19.490 +08:00 [ERR] Client secret validation failed for client: MyBookStore_Web.
2020-09-07 13:42:19.499 +08:00 [INF] Request finished in 374.7184ms 400 application/json; charset=UTF-8
I'm using this code:
var address = "https://localhost:44363/";
            DiscoveryDocumentRequest discoveryDoc = new DiscoveryDocumentRequest()
            {
                Address = address,
                Policy = new DiscoveryPolicy()
                {
                    RequireHttps = false,
                }
            };
            var client = new HttpClient();
            DiscoveryDocumentResponse disco = await client.GetDiscoveryDocumentAsync(discoveryDoc);

            if (disco.IsError)
                throw new Exception(disco.Error);
            const string commonSecret = "E5Xd4yMqjP5kjWFKrYgySBju6JVfCzMyFp7n2QmMrME=";
            TokenResponse tokenResponse = await client.RequestPasswordTokenAsync(new PasswordTokenRequest
            {
                Address = disco.TokenEndpoint,
                Scope = "MyBookStore",
                GrantType = "password",
                ClientId = "MyBookStore_ConsoleTestApp",
                ClientSecret = commonSecret,

                UserName = "admin@abp.io",
                Password = "1q2w3E*",
            });
            tokenResponse.AccessToken.ShouldNotBeNullOrEmpty();

**Comment by CaiJinHao** [comment]
@wjkhappy14 Thank you for your answer, But I still haven't solved it

**Comment by wjkhappy14** [comment]
maybe you  should set the GrantType in the database      **IdentityServerClientGrantTypes**

**Comment by CaiJinHao** [comment]
@wjkhappy14  Thank you, I finally solved the key problem.It's ClientSecret
var address = "https://localhost:44363/";
            var client = new HttpClient();
            var disco = await client.GetDiscoveryDocumentAsync(address);
            if (disco.IsError)
            {
                Console.WriteLine(disco.Error);
                return;
            }

            // request token
            var tokenResponse = await client.RequestPasswordTokenAsync(new PasswordTokenRequest
            {
                Address = disco.TokenEndpoint,
                ClientId = "MyBookStore_ConsoleTestApp",
                ClientSecret = "1q2w3e*",

                UserName = "admin",
                Password = "1q2w3E*",
                Scope = "MyBookStore",
            });
            tokenResponse.AccessToken.ShouldNotBeNullOrEmpty();
