### ISSUE TITLE
CanActivate: [PermissionGuard] reports an error:  The maximum call stack size is exceeded

### ISSUE THREAD

**Issue by bigqiusnow** [abpframework/abp#5313]
My Routing:
```
import { PermissionGuard } from '@abp/ng.core';
  {
    path: 'service-request-list',
    component: ServiceRequestListComponent,
    canActivate: [PermissionGuard],  
    data: {
      routes: {
        requiredPolicy: 'CRM.ServiceRequest',
      },
    },
  },
```

After I upgraded ABP to 3.1 from 2.9, My Angular  reports an error:  The maximum call stack size is exceeded. Please help.
![image](https://user-images.githubusercontent.com/30037177/92346515-8ceeac00-f0ff-11ea-9f68-26625d4f9919.png)

**Comment by mehmet-erim** [comment]
Hi @bigqiusnow

I can't reproduce the problem. Can you describe in detail how can I reproduce the problem?

Did you define your component via `route.provider`? [This document](https://docs.abp.io/en/abp/latest/UI/Angular/Modifying-the-Menu#how-to-add-a-navigation-element) will help you.

**Comment by bigqiusnow** [comment]
@mehmet-erim 
Thank you. 
My problem is solved.

In ABP 2.9 it's "Add requiredPolicy to the **routes** property in your routing module.", but In ABP 3.1 it's "Add requiredPolicy to the **data** property of your route in your routing module." 

So,My Routing should be written like this:

`canActivate: [PermissionGuard],  
    data: {
        requiredPolicy: 'CRM.ServiceRequest',
    },`
