### ISSUE TITLE
Suggestion:use string as the type of ICurrentUser.Id

### ISSUE THREAD

**Issue by fmpfmp** [abpframework/abp#5314]
### Documentation

https://docs.abp.io/en/abp/latest/CurrentUser#authentication-authorization

ICurrentUser works independently of how the user is authenticated or authorized. It seamlessly works with any authentication system that works with the current principal (see the section below).

### GitHub Issues

As a general framework, the type of Id should not be fixed.

I recommend use string or object  as the type of Id

**Comment by maliming** [comment]
Why not `CurrentUser.Id.ToString()`?

**Comment by wjkhappy14** [comment]
it's not a good Suggestion !

**Comment by JadynWong** [comment]
I think it can be considered. Currently, if a developer wants to use `ICurrentUser`, the design user table must use a guid as an identifier.

With strings, other components do not need to consider the user unique identification type of the current system. This is how AspNet core identity is designed.

https://github.com/dotnet/aspnetcore/blob/a190fd34854542266956b1af980c19afacb95feb/src/Identity/Extensions.Core/src/UserManager.cs#L420

Alse we can use the generic interface or generic method to implement, allowing developers to customize the type of user's unique identity.
 It's like repository interface.But it's more complicated.

**Comment by fmpfmp** [comment]
@maliming   

For example, my system ID uses int, objectid, or distributed ID generated by other algorithms. These types cannot be converted to guids CurrentUser.Id , CurrentUser.IsAuthenticated Not available

**Comment by fmpfmp** [comment]
As the name of ABP, as a basic application framework, it is not a good practice to fix the basic type;

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Guid-Generation#why-prefer-guid

**Comment by ignite-404** [comment]
string has better compliancy than guid, why not using string instead?

**Comment by ming2882** [comment]
放弃
