### ISSUE TITLE
Feature Management Modal improvements (MVC UI)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5327]
![image](https://user-images.githubusercontent.com/1210527/92411768-dcf65e80-f151-11ea-8a1e-9c5493f6f06e.png)

* Checkboxes should be on the left side of the feature name
* Child features should be only selectable when the parent was selected (recursively), just like the permissions.
* Numeric features should properly validate numbers (also in the server) and should show a numeric textbox.
* Test if validators are properly working and fix if not.

These are valid for the SaaS module too.

I am currently writing the Features document: https://github.com/abpframework/abp/blob/rel-3.1/docs/en/Features.md
You can read the document when I complete (tomorrow) and work on this issue then.

**Comment by hikalkan** [comment]
Documentation is done: https://github.com/abpframework/abp/blob/dev/docs/en/Features.md

**Comment by realLiangshiwei** [comment]
wait for https://github.com/abpframework/abp/pull/5334, https://github.com/abpframework/abp/pull/5259 merge

**Comment by hikalkan** [comment]
@realLiangshiwei they are merged ;)
