### ISSUE TITLE
A embedded file "/wwwroot/libs/timeago/locales/jquery.timeago.en.js" error

### ISSUE THREAD

**Issue by yshulin** [abpframework/abp#5337]
After I upgraded to 3.1.0, I encountered a problem in /Themes/AdminLTE/Layouts/Account.cshtml page. see below:

![error_1](https://user-images.githubusercontent.com/13978614/92453147-804a8080-f1f1-11ea-89e4-a5897da336e1.png)

I debug into code and found a null reference exception, just like:

![error_2](https://user-images.githubusercontent.com/13978614/92453650-1f6f7800-f1f2-11ea-874c-c51ff880f679.png)

and debug into the code again, I found the embedded file "/wwwroot/libs/timeago/locales/jquery.timeago.en.js" was renamed to "/wwwroot/libs/timeago/locales/**jquery.timeago.js**", see the below image:

![error_3](https://user-images.githubusercontent.com/13978614/92454427-17640800-f1f3-11ea-8487-afcfca475e6e.png)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem. You can use a template project.

**Comment by gdlcf88** [comment]
You may need to upgrade the client-side packages:
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Client-Side-Package-Management#using-the-gulp

**Comment by yshulin** [comment]
@maliming 
Maybe I found the answer, but i do not know how to solve it, can you give me some suggestions, thanks!

Because the file "/wwwroot/libs/timeago/locales/jquery.timeago.en.js" was build into another single dll file which was generated in /bin/Debug/netcoreapp3.1/en/ProjectName.Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2.resources.dll, and its file name was changed to "ProjectName.Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2.wwwroot.libs.timeago.locales.jquery.timeago.js", just like below:
![timeago_en_error](https://user-images.githubusercontent.com/13978614/105324794-d6e7b280-5c06-11eb-843b-64e66c28a6e1.png)

**Comment by maliming** [comment]
`Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2` is not maintained by us, I can't provide much help.

**Comment by yshulin** [comment]
@maliming 
not care about Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2 project, see the embedded file "/wwwroot/libs/timeago/locales/jquery.timeago.en.js" not be found question, thks!

**Comment by yshulin** [comment]
It means that some language js files was build into /bin/Debug/netcoreapp3.1/ProjectName.Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2.dll dll file, such as:

![image](https://user-images.githubusercontent.com/13978614/105327477-e288a880-5c09-11eb-8d57-b6e6f47f648f.png)


and another language js files was build into 
/bin/Debug/netcoreapp3.1/en/ProjectName.Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2.**resources**.dll dll file, such as:

![image](https://user-images.githubusercontent.com/13978614/105327234-9c334980-5c09-11eb-934d-acfcd7701ad5.png)

**and these files which was build into ProjectName.Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2._resources_.dll have the above question.**

**Comment by yshulin** [comment]
@maliming 
I think that it is a bug about abp code in below line https://github.com/abpframework/abp/blob/6afb80a724e86c38e3673b1a0e67d8708bcd9184/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Packages/Volo/Abp/AspNetCore/Mvc/UI/Packages/Timeago/TimeagoScriptContributor.cs#L22

And I basically solved the problem according to the official Microsoft documentation, refer to the below docs:
https://docs.microsoft.com/zh-cn/dotnet/core/project-sdk/msbuild-props#embeddedresourceusedependentuponconvention
https://docs.microsoft.com/zh-cn/dotnet/core/resources/manifest-file-names

I added the below code in .csproj file, finally it works well.
```
<PropertyGroup>
  <EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
</PropertyGroup>
<ItemGroup>
    <EmbeddedResource Include="wwwroot\libs\timeago\locales\jquery.timeago.en.js" LogicalName="ProName.Abp.AspNetCore.Mvc.UI.Theme.AdminLTE2.wwwroot.libs.timeago.locales.jquery.timeago.en.js" />
    <EmbeddedResource Include="wwwroot\**\*.*" Exclude="wwwroot\libs\timeago\locales\jquery.timeago.en.js" />
    <Content Remove="wwwroot\**\*.*" />
</ItemGroup>
```
