### ISSUE TITLE
Oracle 11g: the identifier name can not more than 30 characters

### ISSUE THREAD

**Issue by yuyuguo1707** [abpframework/abp#5342]
i use abp 3.1 when i user oracle 11g ,When I use the Oracle 11g to generate the database , the identifier name too long,
i useoracle(p => p.UseOracleSQLCompatibility("11")) but it not use .
and  use  #1920 ，  still reproduce it。 whether the problem has been solved？

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/1920#issuecomment-577475627
