### ISSUE TITLE
Use ABP Without Identity Server 

### ISSUE THREAD

**Issue by michelveloso** [abpframework/abp#5343]
Hi,

Is it possible to use ABP Framework without Identity Server?

So that all tables referenced to the Identity Server stops being generated, but with the possibility of using ABP Modules?

And if possible, using customized user management and authentication tables with ABP Modules.

**Comment by maliming** [comment]
hi

Of course, you can use ABP without the Identity Server. you need to remove the identity server related module and code.

Abp will use I[identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity) for user manage etc.

**Comment by michelveloso** [comment]
@maliming great!

But without Identity Server module, I will be able to use ABP modules like Volo.Abp.Auditing, Volo.Abp.MultiTenancy, Volo.Abp.Features etc?

And if possible, using customized user management and authentication tables with that modules?

**Comment by maliming** [comment]
Yes. I suggest you start with the document. https://docs.abp.io/en/abp/latest/

**Comment by ivanrusso** [comment]
@michelveloso 
I try to use the startup template without Identity Server.

Have you already done a try without the Identity Server? I would be interested in the easiest way to implement this.

**Comment by imabdulsal** [comment]
@maliming What do you think if there's **a CLI option to prevent installing anything is related to IdentityServer**?

**Comment by maliming** [comment]
@abdullahsalem I agree with you.

**Comment by imabdulsal** [comment]
@maliming Should I file a new issue for that CLI feature?

**Comment by maliming** [comment]
ok please.

**Comment by arashraf** [comment]
> 
> 
> @michelveloso
> I try to use the startup template without Identity Server.
> 
> Have you already done a try without the Identity Server? I would be interested in the easiest way to implement this.

Had you found a way to remove the Identity Server?

**Comment by arashraf** [comment]
> 
> 
> @michelveloso
> I try to use the startup template without Identity Server.
> 
> Have you already done a try without the Identity Server? I would be interested in the easiest way to implement this.

@michelveloso had you found out the solution to remove the Identity Server, we have tried but failed, if you had then can you please guide us.

**Comment by dlsmartlink** [comment]
I tried not to use Identity Server for Web Assebmly with Blazor, and I failed! Any suggestions for me? thanks.

**Comment by ghost** [comment]
I tried not to use Identity Server for Web Assebmly with Blazor, and I failed! Any suggestions for me? thanks.

**Comment by michelveloso** [comment]
@arashraf, @ghost, @abdullahsalem  sorry for the delay, this may be what you need:

https://www.youtube.com/watch?v=6By_lKDyTGg
