### ISSUE TITLE
a faster way to create abp project!

### ISSUE THREAD

**Issue by akinix** [abpframework/abp#535]
@hikalkan 
![demo](https://github.com/akinix/AbpvNextTemplate-MvcModule/blob/master/doc/img/demo.gif?raw=true)

# for developer
create a project takes only 1 second. 
automatic update if the templates has been modified. 
project should be created offline when the template has already been cloned.

# for Abp
the project is generate locally, not occupy resources of servers. E.g CPU NETWORK.

https://github.com/akinix/AbpvNextTemplate-MvcModule

**Comment by hikalkan** [comment]
Thank you @akinix this is awesome!
The only problem I see is that the template code with {{ and }} should be in the C# code ([example](https://github.com/akinix/AbpvNextTemplate-MvcModule/blob/master/%7B%7Bcookiecutter.pn%7D%7D/src/%7B%7Bcookiecutter.cn%7D%7D.%7B%7Bcookiecutter.pn%7D%7D.Application/%7B%7Bcookiecutter.cn%7D%7D/%7B%7Bcookiecutter.pn%7D%7D/%7B%7Bcookiecutter.pn%7D%7DApplicationModule.cs)) which can not be compiled.
This templates are not static and we are actively working on them. So, if we can not compile it, how we know it's stable? Do you have a solution for that.

One solution could be creating an automatic way of converting [our template](https://github.com/abpframework/abp/tree/master/templates/module) to the template you prepared.

**Comment by akinix** [comment]
https://github.com/akinix/AbpVnextTemplates2Cookiecutter
it has not been completed yet, just written some unit tests, but it does not affect the use.

**Comment by akinix** [comment]
@hikalkan
what do you think of this tool https://github.com/akinix/AbpVnextTemplates2Cookiecutter ? 
I'm going to make this conversion tool a global tool if it is useful for ABP

**Comment by hikalkan** [comment]
https://github.com/akinix/AbpVnextTemplates2Cookiecutter is good :) This is what we need.

**Comment by Allvirus** [comment]
![Uploading TIM图片20181011124029.png…]()


I used it and built project successfully, it's very great and powerful tools to generate ABP project，I like it.  
And I met a  trouble due to I installed "GitHub Extension for Visual Studio".  if u also did ,please remove it， and remove git 32 bit version.
I think it's fatser than other way I see to generate project. I hope this conversion tool.

**Comment by personball** [comment]
Is there any possibility to create new abp solution through  dotnet cli ?
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create

**Comment by akinix** [comment]
@personball 
i am thinking about whether to provide another dotnet cli tool. 
**because cookiecutter can be run self in the command line without vs2017.**

you can see these topics:
- https://cookiecutter.readthedocs.io/en/latest/installation.html
- https://cookiecutter.readthedocs.io/en/latest/usage.html

run below in command
``` shell
cookiecutter gh:akinix/AbpvNextTemplate-MvcModule.git
```

**Comment by maliming** [comment]
The `Abp cli` can download the template code from github (can choose the version) and then rename it locally.

**Comment by akinix** [comment]
> The `Abp cli` can download the template code from github (can choose the version) and then rename it locally.
@personball
this an other way to create ABP project.

**Comment by personball** [comment]
@maliming  It's a good idea.

@akinix Thanks for your reply, I will try this tool.

Maybe we can develop it (Abp cli) as dotnet cli tool, for much better customizing features when the tool needs to access csharp language feature which like reflection.

**Comment by hikalkan** [comment]
`abp cli` is one of the important features we want to add in the future, like `dotnet abp new -name MyComp.MyProj -db mongodb` and so on.

**Comment by hikalkan** [comment]
Created an issue to track it: https://github.com/abpframework/abp/issues/544

**Comment by hikalkan** [comment]
I'm closing this since CLI creates projects faster: https://github.com/abpframework/abp/pull/1089
