### ISSUE TITLE
EntityFramework Core Oracle 3.x New Stable Release

### ISSUE THREAD

**Issue by onurcanyilmaz** [abpframework/abp#5354]
Hello,

EF Core Oracle Provider latest stable has been released today.
Related link : https://github.com/oracle/dotnet-db-samples/issues/49#issuecomment-689232173
Nuget Url: https://www.nuget.org/packages/Oracle.EntityFrameworkCore/3.19.80/

We waiting your new stable release for Volo.Abp.EntityFrameworkCore.Oracle
Can you help with this? 

Thanks.

**Comment by alexandis** [comment]
I have problem running Netcore 3.1 project with this version. Any thoughts?

> TypeLoadException: Method 'Create' in type 'Oracle.EntityFrameworkCore.Query.Internal.OracleQueryableMethodTranslatingExpressionVisitorFactory' from assembly 'Oracle.EntityFrameworkCore, Version=3.1.19.1, Culture=neutral, PublicKeyToken=89b483f429c47342' does not have an implementation.
> Microsoft.Extensions.DependencyInjection.OracleServiceCollectionExtensions.AddEntityFrameworkOracle(IServiceCollection serviceCollection)
> 
> DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions`1[Volo.Abp.SettingManagement.EntityFrameworkCore.SettingManagementDbContext])' on type 'SettingManagementDbContext'.
> Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
