### ISSUE TITLE
After adding more localization texts, those are ignored in markup file

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#5356]
2.9.0, Angular UI.
We have a lot of localization texts and adding more.
Now, after adding some texts today, I've noticed they are ignored (localization key is displayed as if no localization found in JSON file). No matter where I put those texts: at the beginning of JSON file or at the end.
If I place them in another JSON file that is short enough so far - the texts are displayed properly.

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.
