### ISSUE TITLE
Question abp : Best Practice To Write Unit Test For Code Coverage

### ISSUE THREAD

**Issue by mostafa1790** [abpframework/abp#5359]
Hello,

kindly i have one question, i am using abp framework and i need to write unit test so shall i write unit test for all projects like domain , application services , api , ....etc or just for business methods in application services.

i just need you opinion and experience to code coverage my project

thanks.

**Comment by hjkl950217** [comment]
I think it depends on the strategy of you and your team:
1. Full coverage
2. Cover only the core logic

Writing UT requires relatively few changes and a certain time cost, so you and your team should choose a strategy that suits you.

If you choose Strategy 1, it is recommended that you each project corresponds to a UT project, and in principle, a class corresponds to a UT class.

If you choose strategy 2, it is recommended that you create only one UT project and divide folders according to the field of test modules.

**Comment by mostafa1790** [comment]
thank you for replying i will discuss with my team
