### ISSUE TITLE
(bug) DbMigrationService not seeding tenant data

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#5362]
Abp v3.1.0

The `MyProjectNameDbMigrationService` only seeds tenant data if they have an external database. We should still skip migration but not skip seeding of tenant data if they are on the host database.

https://github.com/abpframework/abp/blob/fb14a9a68ccbf152777864ce103640d7e02a2067/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Data/MyProjectNameDbMigrationService.cs#L48-L53

**Comment by realLiangshiwei** [comment]
You are right. I will fix it.
