### ISSUE TITLE
abp, ASP.NET Boilerplate, abp Commercial and ASP.NET Zero feature comparison matrix

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#5367]
It would be useful and transparent if user can see feature comparison matrix (**only for latest versions of frameworks**), segmented by UI technology on abp.io and abp Commercial websites.
Something similar to these matrixes:
https://docs.aspnetzero.com/en/common/latest/Abp-Template-vs-AspNet-Zero
https://docs.aspnetzero.com/en/common/latest/Version-Differences

When choosing the right framework (based on implemented features), developers would have clearer picture which is currently more appropriate framework for them.

Additional suggestion for not-yet-implemented features which are currently in development and features with high priority for next version could be marked in matrix (some kind of metadata for developers).

What do you think?

**Comment by hikalkan** [comment]
These are currently available:

* ABP Framework vs ABP Commercial: https://docs.abp.io/en/commercial/latest/abp-framework-vs-abp-commercial
* AspNet Zero vs ABP Commercial: https://docs.abp.io/en/commercial/latest/aspnet-zero-vs-abp-commercial
* ABP Framework Road Map: https://docs.abp.io/en/abp/latest/Road-Map
* ABP Commercial Road Map: https://docs.abp.io/en/commercial/latest/road-map

It may not be such a format you offer, but at least a thing.

**Comment by leonkosak** [comment]
Ok. :) Good enough.
