### ISSUE TITLE
CurrentUser.IsAuthenticated always false

### ISSUE THREAD

**Issue by michelveloso** [abpframework/abp#5377]
Hi, 

I'm simulating a authentication with this code bellow, but **isAuth** always returning false.

```
public async Task<IActionResult> Index()
{
    var isAuth = CurrentUser.IsAuthenticated;
    
    var user = await identityUserManager.FindByEmailAsync("admin@abp.io");
    if (user != null)
    {
        var result = identityUserManager.PasswordHasher.VerifyHashedPassword(user, user.PasswordHash, "1q2w3E*");
        if (result == PasswordVerificationResult.Success)
        {
            await HttpContext.AuthenticateAsync();
        }
    }
}         
     
```

In the ConfigureAuthentication method I got:

```
private static void ConfigureAuthentication(ServiceConfigurationContext context, IConfiguration configuration)
{
    context.Services.AddAuthentication(options =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        })
        .AddCookie()
        .AddJwtBearer();
}

```

Need I change the default authentication schema to work with **CurrentUser**?

Regards

**Comment by michelveloso** [comment]
I think I got it! ;)

I added the package **Volo.Abp.Identity.AspNetCore** to *.Web project and **AbpIdentityDomainModule** as dependency.

In my **PreConfigureServices**, I added the extentions:

```
PreConfigure<IdentityBuilder>(builder =>
            {
                builder
                    .AddDefaultTokenProviders()
                    .AddSignInManager<AbpSignInManager>();
            });
```

In the **ConfigureAuthentication**, add to.AddCookie("Identity.Application").

Finally, I just used the **AbpSignInManager** as bellow in the Action:

```
var result = await signInManager.PasswordSignInAsync(
    user.UserName,
    "1q2w3E*",
    true,
    false
);
```

And It worked very well.

Is it ok?

Regards

**Comment by maliming** [comment]
hi @michelveloso 

> I added the package Volo.Abp.Identity.AspNetCore to *.Web project and AbpIdentityDomainModule as dependency.

You should depend on the `AbpIdentityAspNetCoreModule `

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.AspNetCore/Volo/Abp/Identity/AspNetCore/AbpIdentityAspNetCoreModule.cs
