### ISSUE TITLE
Configuring Hangfire BackgroundJobServerOptions in a console application

### ISSUE THREAD

**Issue by xirius** [abpframework/abp#5378]
I'm trying to configure Hangfire server options in a console application.

```C#
context.Services.AddHangfire(config =>
{
    config.UseMemoryStorage();
});

Configure<BackgroundJobServerOptions>(options =>
{
    options.WorkerCount = 10;
});
```
But the configuration doesn't seem to change anything as per the logs:

```
[01:54:06 INF] Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
[01:54:06 INF] Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
```

It seems to work if I add singleton though:

```C#
context.Services.AddSingleton(provider => new BackgroundJobServerOptions
{
    WorkerCount = 10
});
```

```
[02:01:00 INF] Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
[02:01:00 INF] Using the following options for Hangfire Server:
    Worker count: 10
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:01
```
Is it the right way to set the configuration ?

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by xirius** [comment]
ABP Framework version: 3.1.2 (Stable)

Steps needed to reproduce: 
Follow the instructions to integrate [Hangfire Job Manager](https://docs.abp.io/en/abp/latest/Background-Jobs-Hangfire) + add the `Hangfire.MemoryStorage` nuget package.

**Comment by maliming** [comment]
hi

You can try configure `ServerOptions ` of `AbpHangfireOptions`.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.HangFire/Volo/Abp/Hangfire/AbpHangfireOptions.cs#L16
