### ISSUE TITLE
Proxy Generator:generate error url,missing $

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#5379]
api:
```
 public async Task<CreateRepairInitDto> GetCreateRepairInitAsync(Guid Id){
....
}
```
generate code:
```
getCreateRepairInit = (Id: string) =>
    this.restService.request<any, CreateRepairInitDto>({
      method: 'GET',
      url: `/api/asm/repair/createRepairInit/{Id}`,
    },
    { apiName: this.apiName });
```
right url: `/api/asm/repair/createRepairInit/${Id}`,
**the url lost $**,but not all of these types of apis are wrong,Some of them will be generated right

**Comment by hikalkan** [comment]
Can you try with `id` as the parameter name, instead of `Id` ?

**Comment by maliming** [comment]
```js

var id = 123

> `/api/asm/repair/createRepairInit/{id}`
"/api/asm/repair/createRepairInit/{id}"

> `/api/asm/repair/createRepairInit/${id}`
"/api/asm/repair/createRepairInit/123"
```

**Comment by hexianggui** [comment]
> Can you try with `id` as the parameter name, instead of `Id` ?

Sorry for the late reply！
Thank you!you are right.  Changing the `Id` to `id` in the API results in the correct URL.
```
 public async Task<CreateRepairInitDto> GetCreateRepairInitAsync(Guid id){
....
}
```
However, the problem remains that the 'Get' method cannot be capitalized

**Comment by hexianggui** [comment]
This is the API definition before and after modification
**'Id':**
![2020-09-14_094357](https://user-images.githubusercontent.com/30622318/93035501-b794b380-f66f-11ea-8f98-66e4a99ad616.png)
```
"GetCreateRepairInitAsyncById": {
              "uniqueName": "GetCreateRepairInitAsyncById",
              "name": "GetCreateRepairInitAsync",
              "httpMethod": "GET",
              "url": "api/asm/repair/createRepairInit/{Id}",
              "supportedVersions": [],
              "parametersOnMethod": [
........
```
**'id':**
![2020-09-14_094255](https://user-images.githubusercontent.com/30622318/93035417-81efca80-f66f-11ea-9d76-1f265612387a.png)
```
 "GetCreateRepairInitAsyncById": {
              "uniqueName": "GetCreateRepairInitAsyncById",
              "name": "GetCreateRepairInitAsync",
              "httpMethod": "GET",
              "url": "api/asm/repair/{id}/createRepairInit",
              "supportedVersions": [],
              "parametersOnMethod": [
```

**Comment by armanozak** [comment]
Hi @hexianggui,

The generated classes and interfaces are according to common TypeScript and Angular practices, i.e. method and property names are in camel case.

Is there a specific reason why you want to have a capitalized "Get" in your frontend app?

**Comment by hexianggui** [comment]
> Hi @hexianggui,
> 
> The generated classes and interfaces are according to common TypeScript and Angular practices, i.e. method and property names are in camel case.
> 
> Is there a specific reason why you want to have a capitalized "Get" in your frontend app?

No particular reason，Just accidentally using Pascal named API parameters。

**Comment by armanozak** [comment]
Can we close this issue then?
