### ISSUE TITLE
How to to create a sub-set of an existing entity with Entity framework.

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#5386]
Hi, I'm following the documentation from the link below on how to create a sub set of an existing entity. 
I'm getting this error when I get to the add-migration step. 

`**Cannot use table 'AbpRoles' for entity type 'IdentityRole' since it is being used for entity type 'AppRole' and there is no relationship between their primary keys.**`

It shouldn't need a relationship as it's extending the AbpRoles table not relating to it.

https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#create-a-new-entity

**Steps to reproduce error:** 
1. Created a new abp solution (version : 3.1.2)  ... abp new MyApp -u angular
2. Added Sub set class to domain...
```
 public class AppRole : AggregateRoot<Guid>, IMultiTenant {
        // Properties shared with the IdentityRole class

        public Guid? TenantId { get; private set; }
        public string Name { get; private set; }

        //Additional properties

        public string Title { get; set; }

        private AppRole() {

        }
    }
```
3. Added AppRole to DBContext
```
 public DbSet<AppRole> Roles { get; set; }
```
4. Configured model in DbContextModelCreatingExtensions.cs file
```
  builder.Entity<AppRole>(b =>
            {
                b.ToTable("AbpRoles");
                b.ConfigureByConvention();
                b.Property(x => x.Title).HasMaxLength(128);
            });
```
5. Add mapping in EfCoreEntityExtensionMappings.cs file.
```
        ObjectExtensionManager.Instance
        .MapEfCoreProperty<IdentityRole, string>(
            nameof(AppRole.Title),
            (entityBuilder, propertyBuilder) => {
                propertyBuilder.HasMaxLength(128);
            }
        ); 
```
6. Executed 'add-migration AddedTitleToAppRoles'

**Comment by maliming** [comment]
hi @rygar08 

Did you check the usage of `AppUser` in the template project?

**Comment by rygar08** [comment]
Thanks, in step 4. above, i put that code in DbContactModelCreatingExtensions thinking it gets called by the OnModelCreating method. It worked when I put the code directly into OModelCreating Method in the MyAppDbContext.cs file, just like the documentation says.
```
 protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            /* Configure the shared tables (with included modules) here */ 

            builder.Entity<AppRole>(b => {
                b.ToTable("AbpRoles");
                b.ConfigureByConvention();
                b.Property(x => x.Title).HasMaxLength(128);
            }); 

            builder.ConfigureCxn();
        }
```
