### ISSUE TITLE
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`1[Volo.Abp.Identity.IdentityUserOrganizationUnit] identityUserOrganizationUnitRepository' 

### ISSUE THREAD

**Issue by buxueke** [abpframework/abp#5390]
```csharp
public class UserAppService : ApplicationService, IUserAppService
    {
        private readonly IdentityUserManager UserManager;
        protected IIdentityUserRepository UserRepository { get; }
        protected IIdentityRoleRepository RoleRepository { get; }
        private readonly IRepository<AppUser, Guid> _appUserRepository;
        private readonly IRepository<OrganizationUnit, Guid> _orgRepository;
        private readonly IRepository<IdentityUserOrganizationUnit> _identityUserOrganizationUnitRepository;

        public UserAppService(
            IdentityUserManager userManager,
            IIdentityUserRepository userRepository,
            IIdentityRoleRepository roleRepository,
            IRepository<AppUser, Guid> appUserRepository,
            IRepository<OrganizationUnit, Guid> orgRepository,
            IRepository<IdentityUserOrganizationUnit> identityUserOrganizationUnitRepository
           )
        {
            UserManager = userManager;
            UserRepository = userRepository;
            RoleRepository = roleRepository;
            _appUserRepository = appUserRepository;
            _orgRepository = orgRepository;
            _identityUserOrganizationUnitRepository = identityUserOrganizationUnitRepository;
        }
}
```
Error:
2020-09-14 19:02:51.821 +08:00 [ERR] An exception was thrown while activating AppUserManagement.UserManagement.UserController -> AppUserManagement.UserManagement.UserAppService.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating AppUserManagement.UserManagement.UserController -> AppUserManagement.UserManagement.UserAppService.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'AppUserManagement.UserManagement.UserAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`1[Volo.Abp.Identity.IdentityUserOrganizationUnit] identityUserOrganizationUnitRepository' of constructor 'Void .ctor(Volo.Abp.Identity.IdentityUserManager, Volo.Abp.Identity.IIdentityUserRepository, Volo.Abp.Identity.IIdentityRoleRepository, Volo.Abp.Domain.Repositories.IRepository`2[AppUserManagement.Users.AppUser,System.Guid], Volo.Abp.Domain.Repositories.IRepository`2[Volo.Abp.Identity.OrganizationUnit,System.Guid], Volo.Abp.Domain.Repositories.IRepository`1[Volo.Abp.Identity.IdentityUserOrganizationUnit])'.

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-default-repositories

**Comment by buxueke** [comment]
[DependsOn(
        typeof(AppUserManagementDomainModule),
        typeof(AbpIdentityEntityFrameworkCoreModule),
        typeof(AbpEntityFrameworkCoreModule)
    )]
    public class AppUserManagementEntityFrameworkCoreModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            //context.Services.AddAbpDbContext<AppUserManagementDbContext>(options =>
            //{
            //    /* Add custom repositories here. Example:
            //     * options.AddRepository<Question, EfCoreQuestionRepository>();
            //     */
            //});

            context.Services.AddAbpDbContext<AppUserManagementDbContext>(options =>
            {
                options.AddDefaultRepositories(includeAllEntities: true);
               
            });
            //Configure<AbpDbContextOptions>(options =>
            //{
            //    /* The main point to change your DBMS.
            //     * See also CustomApplicationModulesMigrationsDbContextFactory for EF Core tooling. */
            //    options.UseSqlServer();
            //});
        }
    }

 It didn't work

**Comment by realLiangshiwei** [comment]
Try using `IOrganizationUnitRepository` interface

**Comment by buxueke** [comment]
It's solved：
        
AppUserManagementDbContext

public DbSet<IdentityUserOrganizationUnit> IdentityUserOrganizationUnits { get; set; }

**Comment by ChiakiYu** [comment]
@buxueke  
hi
```
AppUserManagementDbContext

//public DbSet IdentityUserOrganizationUnits { get; set; }
public DbSet<IdentityUserOrganizationUnit> IdentityUserOrganizationUnits { get; set; }
```
Is ok like this?
I reported an error here:
```
2020-09-23 20:31:08.585 +08:00 [ERR] The entity type 'IdentityUserOrganizationUnit' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.
System.InvalidOperationException: The entity type 'IdentityUserOrganizationUnit' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.
```
