### ISSUE TITLE
FromRoute attribute without need to specify the route in Application Services

### ISSUE THREAD

**Issue by luciapeixoto54** [abpframework/abp#5393]
Hi,

Would be possible or make sense to use the [FromRoute] attribute without specifying the route in Application Services methods?

For example:

Instead of using this code below:

```csharp
        [Route("/api/app/people/{personId}")]
        public async Task<dynamic> GetAsync([FromRoute] string personId)
        {
        }
```

use this:
```csharp
        public async Task<dynamic> GetAsync([FromRoute] string personId)
        {
        }
```

Because it only works if the route is specified with the parameter

**Comment by realLiangshiwei** [comment]
see https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#attribute-routing-for-rest-apis
