### ISSUE TITLE
Abp 'FeatureManagementPermissions' does not exist in the current context

### ISSUE THREAD

**Issue by kharazian** [abpframework/abp#5394]
I am using Dev branch and I run app project (User Interface MVC) from template folder. It works perfectly but I have had a problem with tenant section. In fact, when I clicked on tenants management sections, I got this error

    abp\modules\tenant-management\src\Volo.Abp.TenantManagement.Web\Pages\TenantManagement\Tenants\Index.cshtml
    
    The name 'FeatureManagementPermissions' does not exist in the current context
    +
    @if (await Authorization.IsGrantedAsync(FeatureManagementPermissions.ManageHostFeatures))

**Comment by maliming** [comment]
hi @kharazian

You can try run `build-all.ps1` .
https://github.com/abpframework/abp/blob/dev/build/build-all.ps1

**Comment by kharazian** [comment]
@maliming Thanks. Is solved
