### ISSUE TITLE
Error monitoring - Sentry

### ISSUE THREAD

**Issue by bruno-garcia** [abpframework/abp#541]
I couldn't find any support for a error monitoring tool.

Giving a green light from the maintainers, I'd be happy to PR support to [Sentry](https://github.com/getsentry/sentry) which is an open source error tracking tool.

Sentry has a SaaS [sentry.io](https://sentry.io/) which includes a free tier and also [can run on-premise](https://github.com/getsentry/onpremise).

There's a [new .NET SDK for Sentry which supports ASP.NET Core.](https://github.com/getsentry/sentry-dotnet)

**Comment by hikalkan** [comment]
It would be better to do it after we complete this: https://github.com/abpframework/abp/issues/371
Follow it and send PR after we resolve it.

**Comment by natiki** [comment]
> It would be better to do it after we complete this: #371
Agreed as the list of trackers is pretty much endless.... 

https://exceptionless.com/
https://elmah.io/
https://www.datadoghq.com/
https://stackify.com/

to name a few. Most have free tiers. So the ability to add providers via #371 will be the way to go.

**Comment by bruno-garcia** [comment]
Which ones are open sourcr and can be self hosted free of charge?
