### ISSUE TITLE
The user cannot switch the tenant of the Login page while logged in.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#5413]
Because `AppliedResolvers` will only contain the`CurrentUserTenantResolveContributor` while logged in.

https://github.com/abpframework/abp/blob/1a1dc3e0da20e447234350a528ddf818a0639160/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Account.cshtml#L63

https://github.com/abpframework/abp/blob/decad8e30f6186be87db8c5743bf55d530514bb9/framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/AbpTenantResolveOptions.cs#L10-L18

@hikalkan Is this by designed?

**Comment by hikalkan** [comment]
Yes, users should not be able to change the tenant if they are logged in. Tenant is determined via the current auth cookie/token if user has logged in and we should not check any other source to determine the user in this case.
