### ISSUE TITLE
Api definition ignores [ApiExplorerSettings(IgnoreApi = true)]

### ISSUE THREAD

**Issue by bnymncoskuner** [abpframework/abp#5424]
Even though a controller has following attribute, its information is still included in `api-definition`

```csharp
[ApiExplorerSettings(IgnoreApi = true)]
public virtual async Task<string> GetSomethingAsync(Guid id)
{
  // do something
}
```

**Comment by maliming** [comment]
I can't reproduce this problem

![image](https://user-images.githubusercontent.com/6908465/93336286-25043800-f85a-11ea-8e76-c38fa92e3daa.png)

![image](https://user-images.githubusercontent.com/6908465/93336296-2897bf00-f85a-11ea-87a9-a08318b999b1.png)

**Comment by hikalkan** [comment]
@bnymncoskuner are you sure that you're running the right backend 😄

**Comment by bnymncoskuner** [comment]
@hikalkan @maliming I've generated proxies some time ago. I'll try it again after updating abp-cli. Maybe my version was old. I'll post it here my findings.
