### ISSUE TITLE
Microservice document

### ISSUE THREAD

**Issue by Rwing** [abpframework/abp#543]
I noticed that there is 'Microservice Focused' feature in homepage, so I think should have a document to explain how to use abp in microservice architect pattern

**Comment by hitaspdotnet** [comment]
The [ABP documents](https://abp.io/documents/abp/latest/Best-Practices/Module-Architecture) about Application design is in [TODO ](https://github.com/abpframework/abp/blob/master/docs/en/Contribution/Index.md) phase.

**Comment by hikalkan** [comment]
You can start from this document: https://abp.io/documents/abp/latest/Best-Practices/Index

This describes best practices of creating a microservice compatible module.

We will create more documentation in the future. ABP's documentation is far from complete yet.
