### ISSUE TITLE
oracle:Table name length too long

### ISSUE THREAD

**Issue by checkmateTowindn** [abpframework/abp#5442]
I use oralce,in order to avoid too long, the ef core
```
 if (builder.IsUsingOracle())
            {
                builder.Model.SetMaxIdentifierLength(30);
            }
```
this solves the foreignkey problem,but the table name also exceeds 30 characters，such as 'IdentityServerIdentityResources',I have read the previous questions, but I still don't understand them.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/1920#issuecomment-577475627
