### ISSUE TITLE
404

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5446]
Seeing broken link on the link here: https://github.com/abpframework/abp-samples#readme

![image](https://user-images.githubusercontent.com/40014477/93428933-e3739b80-f8f2-11ea-9170-f5854f88db72.png)

**Comment by maliming** [comment]
Thanks @274188A 

https://github.com/abpframework/abp-samples/commit/ab8d75c080a8f46d05246b35b3e7507f2d2b8a47
