### ISSUE TITLE
Xamarin integration

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#5450]
Hi,

We are looking to build a Xamarin version of our application, the API & Identity are based on ABP and so, they are .NET CORE.

The problem is that Xamarin is not .NET Core yet :-( ... so, we cannot use the HttpAPI.Client :-(

Do you have a way to create a copy of this project that we will be able to use into Xamarin?
Today, we expect t recreate a new problem, rebuild all the DTO for Xamarin... but it is the worst solution, but
do we have an alternative?

PS: I have see several other issues, peoples are facing the same problem... but without any solution.

**Comment by NecatiMeral** [comment]
The required modules for implementing clients are targeting net-standard already.

We use ABP for WinForms Clients and have no issues.
Which packages do you need additonally?

**Comment by vd3d** [comment]
Thanks a lot,

I have try with Xamarin, but unfortunately I have a DLL conflict:

`Error	CS1703	Multiple assemblies with equivalent identity have been imported: 'C:\Users\ClubberLang\.nuget\packages\system.reflection.emit\4.3.0\ref\netstandard1.1\System.Reflection.Emit.dll' and 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Reflection.Emit.dll'. Remove one of the duplicate references.	MyApp.iOS`

I have no idea to fix it. Of course, I cannot remove the Xamarin dependency ... it is a framework library.
And for ABP, it seems linked to several 4.3.x net libraries (netstandard1.1)

So what, is there a solution? Any idea is welcome ;-)

Thanks
