### ISSUE TITLE
Problem while creating a solution with a stable version using the preview version of the ABP CLI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5453]
It should tolerate and work with the previous startup templates.

![image](https://user-images.githubusercontent.com/1210527/93468688-05bbe800-f8f8-11ea-8b37-b2844556c260.png)

**Comment by yekalkan** [comment]
resolved by https://github.com/abpframework/abp/commit/196a206107dbe655f570024ed450c972231e7e37
