### ISSUE TITLE
Could not find the bundle file '/libs/luxon/luxon.min.js' from IWebContentFileProvider

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#5456]
`abp new Angular.NonSeperatedEfCore -t app -u angular --mobile none  --database-provider ef --preview`

**Comment by maliming** [comment]
https://github.com/abpframework/abp/commit/ae9f593b5e990a27f40b67eadcfb15f24d54d5cb#diff-8d7bacdeb0620aad6ca081e59ae42a11R1-R6

**Comment by hikalkan** [comment]
Duplicate of https://github.com/abpframework/abp/issues/5457
