### ISSUE TITLE
How do I run the Docs projects 

### ISSUE THREAD

**Issue by mperk** [abpframework/abp#547]
I opened Volo.Docs.sln.
All rebuild succeeded. But I don't see static int Main(string[] args) method.
When I run the project, I get this error:

![image](https://user-images.githubusercontent.com/3465794/46816354-7873ce80-cd85-11e8-9c13-5777ed1b0b7a.png)

**Comment by hitaspdotnet** [comment]
Set Web.DocsTestApp project as the startup. Config the appSettings, set Web.Docs.TestApp.EfCore as target project in PMC, then run update-database. Next, push F5 ( or ctrl + F5)

**Comment by hikalkan** [comment]
We should provide a documentation for it :)

**Comment by hikalkan** [comment]
Created an issue: https://github.com/abpframework/abp/issues/549
