### ISSUE TITLE
Identity Server (separated) - disable CORS checking

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#5475]
Is somehow possible to disable CORS checking (validating) in Identity Server project?
For testing environment, I have issues:

[04:33:46 WRN] Origin is not allowed: http://186.xx.xx.xxx:[port_number]
[04:33:46 WRN] CorsPolicyService did not allow origin: http://186.xx.xx.xxx:[port_number]

URL http://186.xx.xx.xxx:[port_number] is defined in CorsOrigins in .IdentityServer project.

This installation is inside Docker environment. It worked (inside Ubuntu virtual machine where Docker is installed), but now with external IP addresses (translation is executed inside network equipment).

What should I do? There is no nginx inside docker. API and IDS run "directly" in kestrel. Angular solution runs with "ng serve".

In Angular, I can see generatet jwt token, but there are warnings in .IdentityServer Logs.txt file (mentioned above).

Thank you.

**Comment by realLiangshiwei** [comment]
Hi,

Actually, This is the default behavior of the browser, it nothing to do with ABP. You can try https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by leonkosak** [comment]
Are you sure? These errors regarding CorsPolicyService are inside Logs.txt in IdentityServer project (container).
I also try with Firefox (and the behavior is the same).
There are no errors in browser console or network tab (developer tools).

**Comment by maliming** [comment]
hi @leonkosak 

See the source code:
https://github.com/abpframework/abp/blob/dev/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AbpCorsPolicyService.cs#L29
https://github.com/abpframework/abp/blob/dev/modules/identityserver/test/Volo.Abp.IdentityServer.Domain.Tests/Volo/Abp/IdentityServer/CorsPolicyService_Tests.cs#L31

**Comment by leonkosak** [comment]
@maliming, but why on earth this does not work? There is http://186.xx.xx.xxx:[port_number] in App:CorsOrigins in IdentityServer container defined. There is no typo.

And there are a lot of "Authorization failed." records (sequentially) in Logs.txt gor .HttpApi project.

**Comment by leonkosak** [comment]
There are the following error in Logx.txt in .HttpApi container:


`[07:38:43 INF] Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.`


```
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.,
 ---> System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
```

**Comment by maliming** [comment]
hi

**[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]**.

**Comment by leonkosak** [comment]
The problem is that calling external IP address (with port) from local network is "loop" and therefore API cannot access Identity Server.
Where can [this piece of code](https://github.com/abpframework/abp/issues/5125#issuecomment-683922623) be placed?
Should the value be internal Docker IP of Identity Server?
Currently, I get just errors wherever this code is placed.

**Comment by maliming** [comment]
This is about deployment, I’m not familiar with it. : )
