### ISSUE TITLE
On the security of ABP depending on the third party JS static scanning

### ISSUE THREAD

**Issue by git102347501** [abpframework/abp#5478]
**Usage environment**
ABP Framework version：3.1.0
User Interface Type：Angular

I am using the ABP framework to develop a WebAPI program, but when my program is scanned through the static code, I find that ABP references many third-party outdated or dangerous js libraries. Can these libraries be replaced or updated?

**For example:**

- luxon.js
**Criticality:** Critical
**Category:** Key Management: Hardcoded Encryption Key**
![微信截图_20200918152119](https://user-images.githubusercontent.com/37917403/93568405-b393c900-f9c2-11ea-87aa-f20fb6e0c869.png)

- jquery.validate.unobtrusive.js
**Criticality:** Critical
**Category:** Key Management: Hardcoded Encryption Key**
![2](https://user-images.githubusercontent.com/37917403/93568599-fbb2eb80-f9c2-11ea-8ffc-7f7f87c0b445.png)

- jquery.validate.js:
**Category:** Race Condition
![3](https://user-images.githubusercontent.com/37917403/93568814-4df40c80-f9c3-11ea-880f-cbe4f8d2b2d3.png)

- sweetalert.min.js
**Criticality:** Low 
**Category:** HTML5: Overly Permissive Message Posting Policy
![image](https://user-images.githubusercontent.com/37917403/93568960-7d0a7e00-f9c3-11ea-83f8-9d1b54a1b1a9.png)

- abp.jquery.js
**Criticality:** Low
**Category:** JavaScript Hijacking: Vulnerable Framework
![55](https://user-images.githubusercontent.com/37917403/93569114-b511c100-f9c3-11ea-9ba0-dd5bb5e3a115.png)

**Comment by git102347501** [comment]
The following are the scan vulnerability supplements.

**- bootstrap.bundle.min.js**
**Criticality:** High
**Category:** Insecure Randomness
![image](https://user-images.githubusercontent.com/37917403/96243652-9a893280-0fd7-11eb-8f68-dc321f3dda35.png)

**- bootstrap.bundle.js**
**Criticality:** High
**Category:** Insecure Randomness
![image](https://user-images.githubusercontent.com/37917403/96243839-df14ce00-0fd7-11eb-8d01-0c05e4cf15c4.png)

**- select2.full.min.js**
**Criticality:** High
**Category:** Insecure Randomness
![image](https://user-images.githubusercontent.com/37917403/96244008-171c1100-0fd8-11eb-957f-4e41fe12b44a.png)

**- select2.min.js**
**Criticality:** High
**Category:** Insecure Randomness
![image](https://user-images.githubusercontent.com/37917403/96244055-24d19680-0fd8-11eb-9ca3-161239610877.png)

**Comment by maliming** [comment]
We will update npm packages regularly, but these warnings may not be eliminated. You can give feedback to the package owner.
