### ISSUE TITLE
Feature & Structure Request - Node.js & React

### ISSUE THREAD

**Issue by sbenfares** [abpframework/abp#5480]
Hello,

Your product is very useful and complete.

- Do you have any plan to extend it to a **Node.js & React framework** with the same structure & features ?

- It would be very useful for a lot of developers since these technologies are very widely used in the 👍 **_Startup Ecosystem_** because of the quick "set up / dev & deploy" aspect.

Thanks for considering it as an option, it would be a **huge market opportunity** for your product 🥇

**Comment by antosubash** [comment]
There is already an issue created for React template #1638. 

Here is the [Roadmap](https://docs.abp.io/en/abp/latest/Road-Map) of the features.

if you are looking for something similar now then look at [Strapi](https://strapi.io/). Hope this helps.
