### ISSUE TITLE
ResponseCache on ApplicationService

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#5482]
Hi,

I wish to know if we can use the ResponseCache attribute to the ApplicationService ?

My wish is to allow some images to be cached, I have tried by adding:

`[ResponseCache(Duration = 86400, Location = ResponseCacheLocation.Any, NoStore = false)]`

and also this in the service config:

`context.Services.AddResponseCaching();`

```
            app.UseResponseCaching();
            app.Use(async (context, next) =>
            {
                context.Response.GetTypedHeaders().CacheControl =
                    new Microsoft.Net.Http.Headers.CacheControlHeaderValue()
                    {
                        Public = true,
                        MaxAge = TimeSpan.FromSeconds(10)
                    };
                context.Response.Headers[Microsoft.Net.Http.Headers.HeaderNames.Vary] =
                    new string[] { "Accept-Encoding" };

                await next();
            });
```

But when I test, I do not see the caching information in the response, nothing. I try to set cache duration at 24 hours.

Do you have any idea?

![image](https://user-images.githubusercontent.com/17200971/93589802-b2a46c80-f9ad-11ea-8a87-cfa6432fb693.png)

**Comment by maliming** [comment]
You can try it on the controller first.

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-3.1#troubleshooting

**Comment by ngocnv371** [comment]
Just in case someone still looking for an answer, your code doesn't work because you might have put it after the endpoints. You should put them just before the setting of `cors` and `auth`.
