### ISSUE TITLE
There are errors on the docs module when FileSystem is used as the source

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5487]
Please test and ensure that FileSystem works (without needing GitHub parameters).

![image](https://user-images.githubusercontent.com/1210527/93589224-301fab00-f9b5-11ea-981b-dd7aac316744.png)

**Comment by yekalkan** [comment]
resolved by https://github.com/abpframework/abp/commit/ec234321f3d5932335d34e30a23ae9d259fe1a78
