### ISSUE TITLE
Should remove the "host/" prefix of blob name when the blob container is set to "IsMultiTenant = false"?

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#5492]
https://github.com/abpframework/abp/blob/87cb32955b367a637260545ff697e4e62900f236/framework/src/Volo.Abp.BlobStoring.Azure/Volo/Abp/BlobStoring/Azure/DefaultAzureBlobNameCalculator.cs#L15-L20

https://github.com/abpframework/abp/blob/cdae51ba1aebcf2749375ea0e5d27727613b9051/framework/src/Volo.Abp.BlobStoring/Volo/Abp/BlobStoring/BlobContainer.cs#L206-L214

If a blob name is `something`, and the blob container is set to `IsMultiTenant = false`, the actual blob name will be `host/something`, but I think the blob name should be `something` itself.

**Comment by hikalkan** [comment]
What if you later change your application to be multi-tenant? All your BLOB data become lost. I suppose I did it intentionally because of this reason.

**Comment by gdlcf88** [comment]
Hi @hikalkan,

I think when it is changed to be multi-tenant, developers should handle the existing BLOBs themself.

But, maybe the above need should not exist. A BLOB container with `IsMultiTenant = false` is usually used to store system-level BLOBs (such as certificates). If there is a container that may need multi-tenancy, it should be set `IsMultiTenant = true` even if there is only one tenant (host) currently.

In the current design, if a BLOB container is changed to be multi-tenant, BLOBs of any tenant are still stored in "host/", it is not expected (either before or after the change). And the essential reason is that the "non-multi-tenant" may be different from "arrange all tenants as the host".

**Comment by hikalkan** [comment]
https://github.com/abpframework/abp/pull/5510#issuecomment-704282029
