### ISSUE TITLE
Is there any possible way to increase the password minimum length and how to add mandatory to the name and surname fields of user?

### ISSUE THREAD

**Issue by senthiljruby** [abpframework/abp#5493]

**Comment by maliming** [comment]
hi

> Is there any possible way to increase the password minimum length 

See https://github.com/abpframework/abp/issues/2755

how to add mandatory to the name and surname fields of user? 

You can try custom the module.

https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Guide
