### ISSUE TITLE
The Angular UI keep loading when I generate the proxy

### ISSUE THREAD

**Issue by amsaighi** [abpframework/abp#5498]
### Description

The Angular UI keep loading

![1](https://user-images.githubusercontent.com/3142753/93709680-83723480-fb40-11ea-81a5-f6ff7579b719.PNG)

I followed the the second tutorials " the book list Page " using **Angular and EF Core **.
After finishing the tuto, I launched the both of projects **Http.Api.Host** and **IdentityServer** .

### The issues

*  **ABP Framework version : Version 3.1.2 (Stable)**. 
*  **User Interface : Angular UI** 

The API worked normally but when I try to see the result on Angular, it still loading without result, 

![2](https://user-images.githubusercontent.com/3142753/93709682-879e5200-fb40-11ea-8e23-74c5701dee53.PNG)

When I checked on network all of status ( stylesheet or Js ) 304

![3](https://user-images.githubusercontent.com/3142753/93709685-8ec56000-fb40-11ea-8552-e5a5243e5a68.PNG)

**Comment by eng-mohammed-emam** [comment]
Hello,

I faced the same issue but after I added the first entity and made a table and then added the application service for this entity, 
the command that generates proxy worked well in the Angular project.

Hope this works with you.

**Comment by amsaighi** [comment]
Hello, 
I added a new entity, service then I generate the new proxy, after that it still loading, when I inspect the network application I get this 
this : localhost:4200 OpenId still pending
![1](https://user-images.githubusercontent.com/3142753/93752393-e3c7ab80-fbfe-11ea-8a3e-bc6f7c732328.PNG)

https://localhost:44335/ in Acme.BookStore.IdentityServer applicationConfigurationScript still pending
![2](https://user-images.githubusercontent.com/3142753/93755586-d95be080-fc03-11ea-8ee2-1fc9bb9cc1fd.PNG)

**Comment by amsaighi** [comment]
ping @mehmet-erim

**Comment by mehmet-erim** [comment]
Hi @amSaighi 

Please check the browser console, do you see any errors?

**Comment by mehmet-erim** [comment]
Hi @maliming

Can you check the problem? Apparently the problem is caused by the backend.

**Comment by maliming** [comment]
hi @amSaighi 

Please share some code. eg Application services or controllers.

**Comment by amsaighi** [comment]
Hi @maliming 
When I tried to debug and to know the root cause, I think it with backend and exactly with some abp DLL.
It take a lot of time to see the result, see the screenshot 

![3](https://user-images.githubusercontent.com/3142753/93872315-4177f880-fcd0-11ea-88cb-bc0e434fd047.PNG)

![4](https://user-images.githubusercontent.com/3142753/93872342-49d03380-fcd0-11ea-9409-f4d4b6a2c37a.PNG)

**Comment by maliming** [comment]
Can you share the steps to reproduce this problem?

**Comment by amsaighi** [comment]
Yep sure, 
Abp -v : **3.1.2 (Stable)**

- Create entity, 
- Create App service

Angular -v : **10.0.10**

- Generate proxy

**Run** : http, and identity Server, and Angular
ping @maliming

**Comment by maliming** [comment]
hi

Can you provide detailed steps? Or a project. : )

**Comment by amsaighi** [comment]
Hi @maliming 
As I said in the top, u can try the example : https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=NG&DB=EF
with the same version of Angular and ABP 

Thank you :D

**Comment by maliming** [comment]
I tried from scratch following the steps in the document,  Can't reproduce.

```cs
[09:26:37 INF] ABP CLI (https://abp.io)
[09:26:37 INF] Version 3.1.2 (Stable)
```
![image](https://user-images.githubusercontent.com/6908465/93953762-da654d00-fd7e-11ea-9499-6e74ccb4ede6.png)

**Comment by amsaighi** [comment]
Did you try it with ABP and Angular ? @maliming 
I did the test again for the 3rd time and always the same result, as soon as I get an answer I share the screen.

New project  ABP **Version 3.1.2 (Stable)** with Angular 

![3](https://user-images.githubusercontent.com/3142753/93988848-7d22c900-fd89-11ea-928c-169db07b5653.PNG)

Still waiting 

![1](https://user-images.githubusercontent.com/3142753/93988879-8744c780-fd89-11ea-97b5-35d6324c0ce8.PNG)

Identity server 

![2](https://user-images.githubusercontent.com/3142753/93988924-93308980-fd89-11ea-8294-5ec60de00d56.PNG)

**Comment by amsaighi** [comment]
Look, @maliming 
9.7 min for openId-configuration 


![4](https://user-images.githubusercontent.com/3142753/93991218-50bc7c00-fd8c-11ea-9dbf-5ff34fede2b5.PNG)

12.8 min login 

![5](https://user-images.githubusercontent.com/3142753/93991241-5a45e400-fd8c-11ea-98e3-66527f27e910.PNG)

**Comment by maliming** [comment]
hi @amSaighi 

Are your Redis works normal?

**Comment by amsaighi** [comment]
ping @maliming 
in console I have only this us info : `NgxsModule.forRoot(states, { development Mode: !environment.production })`

The Angular tooks a lot of time to get the right URL, it still waiting for the answer.

**Comment by amsaighi** [comment]
check it please : https://github.com/amSaighi/ABP-Angular

@maliming @mehmet-erim

**Comment by maliming** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/6908465/94015083-fa2c5d80-fdde-11ea-8266-e8539e6b2e25.png)

**Comment by amsaighi** [comment]
it's awkward, I ll try to same example in another machine.

**Comment by maliming** [comment]
Are your Redis server works normal?

**Comment by amsaighi** [comment]
Why redis ? 
look the same repo in my VM Azure, I clone it and I get the same result 
FYI : I using EF Core with SqlServer management 

![1](https://user-images.githubusercontent.com/3142753/94131183-e3791b80-fe5d-11ea-93ec-768f31421288.PNG)

ping @maliming

**Comment by amsaighi** [comment]
ping @maliming  @mehmet-erim

**Comment by maliming** [comment]
> Why redis ?

See https://github.com/abpframework/abp/issues/5023

https://github.com/amSaighi/ABP-Angular/blob/master/aspnet-core/src/Acme.BookStore.IdentityServer/appsettings.json#L12
https://github.com/amSaighi/ABP-Angular/blob/master/aspnet-core/src/Acme.BookStore.HttpApi.Host/appsettings.json#L11

**Comment by amsaighi** [comment]
Hello @maliming 
Thank you it's working perfectly.
in the first I didn't get the information about Redis in the first use ABP.
I installed Redis, I launched it and everything sill good.

Redis link : [Redis Download ](https://github.com/dmajkic/redis/downloads)
[Setup/Install Redis Server on Windows 10](https://www.onlinetutorialspoint.com/spring-boot/setup-install-redis-server-on-windows-10.html)
