### ISSUE TITLE
Login/Registration UI

### ISSUE THREAD

**Issue by hottabych07** [abpframework/abp#5499]
Hi how can I change the user interface of the login or login page. If she is now running on the identity server. ABP.io version 3.2?
My project = ASP.NET + Angular

Thanks.

**Comment by eng-mohammed-emam** [comment]
Hello,

This article explains how to change the login page.

https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface

**Comment by hottabych07** [comment]
> Hello,
> 
> This article explains how to change the login page.
> 
> https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface

Thank you, but as I understand it for the ASP.NET MVC + RAZOR template. And I use Angular

**Comment by eng-mohammed-emam** [comment]
Hello,
In the newer version of ABP Framework, login page moved to identity server and the Angular project just calls the login page from the identity server.
Like this: https://identityServerUrl/account/login
