### ISSUE TITLE
Dynamic entities

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#55]
### Requirements

- [ ] Can create dynamic entities without defining an entity class.
- [ ] Tenants can customize dynamic entities (per tenant entity and properties).

**Comment by wakuflair** [comment]
I created this repo: https://github.com/EasyAbp/Abp.DynamicEntity
maybe helpful.

**Comment by carbonhe** [comment]
Is there any progress on this feature?

**Comment by vnetonline** [comment]
Will this be built into the core or a separate module? in AspNetBoilerPlate this was called DynamicEntityProperties and was built into the core 2 years ago

**Comment by vnetonline** [comment]
I would like to work on this feature can you please let me know if you will build this into the framework or as a separate module?
