### ISSUE TITLE
Audit Entity Property Name Localization requirement.

### ISSUE THREAD

**Issue by jack-gaojz-zz** [abpframework/abp#5500]
ABP Framework version: 3.1.2
Module: Volo.Abp.Auditing, Volo.Abp.EntityframeworkCore 
Description: The log information does not make sense to the final user. For example, the property name change. Currently, the property name is the entity property name, not the localization name. If the user is not a developer, he can not understand the property name meaning.

So, could we can store the localization name instead of the original entity property name? I saw the codes in the Volo.Abp.EntityframeworkCore module as below:
![image](https://user-images.githubusercontent.com/40879710/93692235-156b4480-fb23-11ea-942c-47f43c1f810c.png)

**Comment by realLiangshiwei** [comment]
You can custom `AuditLogContributor`: https://docs.abp.io/en/abp/latest/Audit-Logging#audit-log-contributors

In addition, I think audit logs are not for the final users, you need a business log.

**Comment by jack-gaojz-zz** [comment]
@realLiangshiwei Thanks so quick reply. I will try to follow your suggestion.
