### ISSUE TITLE
Angular UI keeps loading if you cancel login of identity server

### ISSUE THREAD

**Issue by eng-mohammed-emam** [abpframework/abp#5501]
Hello,
* I'm using ABP Framework version 3.1.2
* User Interface: Angular.

Scenario:
When user tries to login, the Angular redirects to login page of identity server.
If you press "Cancel" button, then the angular project keeps loading with a console error.

![image](https://user-images.githubusercontent.com/33034344/93709248-7c99f080-fb45-11ea-86a0-b4c042b4e574.png)

**Comment by amsaighi** [comment]
> Hello,
> 
> * I'm using ABP Framework version 3.1.2
> * User Interface: Angular.
> 
> Scenario:
> When user tries to login, the Angular redirects to login page of identity server.
> If you press "Cancel" button, then the angular project keeps loading with a console error.
> 
> ![image](https://user-images.githubusercontent.com/33034344/93709248-7c99f080-fb45-11ea-86a0-b4c042b4e574.png)

Hello check this :[The Angular UI keep loading]( https://github.com/abpframework/abp/issues/5498#issuecomment-700621131)

Good luck
