### ISSUE TITLE
Identity server :: Some translations of words are missing in pages Login and Forget password

### ISSUE THREAD

**Issue by eng-mohammed-emam** [abpframework/abp#5503]
Hello,

I'm using ABP Framework version 3.1.2
User Interface: Angular.

Some translations of words are missing in pages Login and Forget password in the identity server project.

Is there a way to add missing translations texts in the identity server project?

The missing translations in Arabic language.

**Comment by maliming** [comment]
hi @eng-mohammed-emam 

Please refer to https://docs.abp.io/en/abp/latest/Contribution/Index#resource-localization

**Comment by eng-mohammed-emam** [comment]
I translated all the un-translated words into Arabic.

[abp-translation.zip](https://github.com/abpframework/abp/files/5252737/abp-translation.zip)

**Comment by maliming** [comment]
hi @eng-mohammed-emam 
Thank you! I make it work. https://github.com/abpframework/abp/pull/5507
