### ISSUE TITLE
How do I set EditionId to authorization

### ISSUE THREAD

**Issue by SmallShrimp** [abpframework/abp#5511]
####  **ABP Framework version** `3.1.2`.

- ***How do I set EditionId to authorization***.
I tried to get the list of features through the Edition, but couldn't because the EditionId was not included in the authorization information。What should I do？

**Comment by maliming** [comment]
What is your use case?

**Comment by SmallShrimp** [comment]
I use the method `FeatureChecker.IsEnabledAsync('Account.EnableLdapLogin')` to get the result False.
My database results show that there is value.
![image](https://user-images.githubusercontent.com/8120385/93736426-dddbc580-fc12-11ea-9c32-a17e881c0773.png)

I used the tenant authorization with this feature to request data，And use the following code in the controller to get Null.
```
// Shouldn't this be "35f6c555-030b-bd23-662f-39f7bb0d154b"?
var editionId = User.FindEditionId();
```

**Comment by maliming** [comment]
There is not create an `EditionId ` in claims for now. Maybe you can try it.

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L14

**Comment by SmallShrimp** [comment]
If so, how should I verify the Feature?

**Comment by SmallShrimp** [comment]
I found a bug，By default the Edition has all the features。But these data are not stored in the database。
If the database does not have corresponding data，`FeatureChecker.IsEnabledAsync` method can't output right results.

**Comment by maliming** [comment]
All boolean features should be `false` by default.

**Comment by SmallShrimp** [comment]
look this !
![image](https://user-images.githubusercontent.com/8120385/93744963-42a01b80-fc25-11ea-8e2b-91c1ea5b2df9.png)
***I didn't make any changes***，but all items are selected

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by SmallShrimp** [comment]
I cannot reproduce the problem，because when I use a brand new project, the problem is gone.
But I still think there is a problem with the ui of the `Feature Setting`.
look :
1. beafore setting:
![image](https://user-images.githubusercontent.com/8120385/93749558-ac6ff380-fc2c-11ea-95d3-63d66c0d0c2f.png)
2. setting:
![image](https://user-images.githubusercontent.com/8120385/93749697-ef31cb80-fc2c-11ea-9c14-d04d56ff7aec.png)
3. after:
![image](https://user-images.githubusercontent.com/8120385/93749827-27d1a500-fc2d-11ea-9a88-43c64a2c8e52.png)

***I just canceled a few items, but the canceled item is selected again***

**Comment by maliming** [comment]
Without steps we can't confirm the problem.
