### ISSUE TITLE
Generate-Proxy Angular UI error when Dtos are in a subfolder separated from interfaces.

### ISSUE THREAD

**Issue by enramgarcia** [abpframework/abp#5512]
Assuming the following structure:

```
- Foo.Bar.Application.Contracts
    - Common
        - Dtos
            - AddressDto.cs
            - CreateAddressDto.cs
            - UpdateAddressDto.cs
        - IAddressAppService
```

Once you run abp generate-proxy command it will generate the models, and services, but the angular compiler will throw the following error: 

```diff
-    ERROR in ./src/app/proxy/common/index.ts 1:9
-    Module parse failed: Unexpected token (1:9)
-    File was processed with these loaders:
-    \* ./node_modules/@ngtools/webpack/src/index.js
-    You may need an additional loader to handle the result of these loaders.
-   > export * as Dtos from './dtos';
-    | export * from './address.service';
```

The **index.ts** generated under **proxy** -> **common** is as follow: 

    export * as Dtos from './dtos'; // Error
    export * from './address.service';

The **index.ts** generated under **proxy** -> **common** -> **dtos** is as follow:

    export * from './models';

**Comment by bnymncoskuner** [comment]
Hello, I've tried with a similar setup however Angular compiler didn't give me any error. Could you please share a repo that reproduces your problem?
