### ISSUE TITLE
How to override tag helper

### ISSUE THREAD

**Issue by fengyeju** [abpframework/abp#552]
I create a new service try to replace `AbpInputTagHelperService`, but it does not work. 
My class:
``` C#
[Dependency(ServiceLifetime.Transient, ReplaceServices = true)]
public class MyInputTagHelperService : AbpTagHelperService<AbpInputTagHelper>
{
        private readonly IHtmlGenerator _generator;
        private readonly HtmlEncoder _encoder;

        public MyInputTagHelperService(IHtmlGenerator generator, HtmlEncoder encoder)
        {
            _generator = generator;
            _encoder = encoder;
        }
        //code
}
```

**Comment by hikalkan** [comment]
Hi,

You should declare the service you are trying to replace. `ReplaceServices = true` in the attribute can only work when you use appropriate naming conventions.

1. Create a class, like MyAbpInputTagHelperService, derived from ``AbpInputTagHelperService``.
2. Override `Process` method and do whatever you like.
3. Replace AbpInputTagHelperService by MyAbpInputTagHelperService.  Use context.Services.Replace... in the Configure method of you module. If you don't know how to use the Replace method, you can Google or ask if you can't find.
