### ISSUE TITLE
How to manage 3rd-party global js/css file dependencies of a module with the Blazor UI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5520]
* Should we define npm packages [just like done for the MVC UI](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Client-Side-Package-Management) for the modules?
* Should we use the same system to copy files from node_modules to wwwroot/libs?
* .NET 5 Blazor will provide a way to add a a style to a page as lazy, can we benefit from it?
* Page specific dependencies or JS/CSS files?
* Change CDN usages to local files in the startup template

**Comment by hikalkan** [comment]
One solution to this problem is;

### Managing JS/CSS dependencies of the modules

* If a module package has its own js/css file, then it is used as `_content/PackageName/resource.js`. This is currently the suggested way by Microsoft. So, we don't change it.
* If the module package depends on a 3rd-party JavaScript or CSS library, say to font-awesome library, then we have two options;
  1. Module copies the library in its own package and we include the font-awesome like `_content/PackageName/fontawesome/all.css`. This has a problem: If two independent module package requires `font-awesome`, both will include the same resources unnecessarily.
  2. We can introduce `Volo.Abp.AspNetCore.Components.WebAssembly.FontAwesome` (the name may change) package that embeds font-awesome library in it and we use the fontawesome as `_content/Volo.Abp.AspNetCore.Components.WebAssembly.FontAwesome/all.css` in the index.html. I prefer this option.

Embedding a 3rd-party library into a NuGet package seems not native. We could use NPM dependencies, package.json file and a gulp task to copy the library files into wwwroot/libs folder, as we've done for MVC UI.

However, I found this way more practical for Blazor applications. Because we won't have much 3rd-party native JS/CSS library dependencies. We generally will use Bootstrap and a few base libraries. And we don't want to deal with npm, gulp... tooling and preparing an integration package for each packages like [we did for MVC](https://github.com/abpframework/abp/tree/dev/npm/packs).

### Adding link/script tags to the index.html

The second problem is to add the depended JS files into the index.html for blazor webassembly projects. We currently do it manually:

````html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
<link href="flag-icon-css/css/flag-icon.min.css" rel="stylesheet"/>
<link href="_content/Blazorise/blazorise.css" rel="stylesheet" />
<link href="_content/Blazorise.Bootstrap/blazorise.bootstrap.css" rel="stylesheet" />
````

However, when I use a module, how can I know all the dependency chain and manually add the css/js files in the right order. It is actually a dependency graph. Different modules may depend on each other and same or different js/css libraries.

My solution offer is to introduce an ABP CLI command, like `abp bundle`. This command will investigates all the module assemblies (beginning from the root module), find the global dependencies, order them by the dependency order, make them distinct... and finally add the list into a placeholder in the index.html file (for css and styles).

So, whenever we add/remove a module into the application, we simply run the `abp set-global-resources` command and it refresh the global css/style imports correctly.

### Bundling & Minification

Another missing feature of the Blazor is it hasn't a built-in bundle and minification system. I suppose `abp bundle -b -m` command can also bundle & minify the files and add a single css and single js file to the index.html. It can read the resources from the module packages & application statics and prepare a single bundle.

**Comment by stsrki** [comment]
One other option is to use javascript isolation, but it would require more work on Blazor libraries. And probably not every library can be done with isolation in mind.

https://www.meziantou.net/javascript-isolation-in-blazor-components.htm

**Comment by hikalkan** [comment]
Thanks @stsrki I will check it deeper. The problem is that: We can apply it for our modules, but 3rd-party Blazor libraries (like Blazorise 😄 ) will continue to use `_content/...` approach.
