### ISSUE TITLE
Interactive Validation model for the Blazor UI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5524]
Can we automate or simplify the validation stuff, with localization?

* Should support data annotation validations
* Should support IValidatableObject
* Should support FluentValidation (with low priority and we can create a separate issue for that)

Initially, we can implement the validation for the user create and edit modals of the identity module and then we discuss on it (before deciding to implement for other modules).

**Comment by stsrki** [comment]
https://github.com/stsrki/Blazorise/issues/1371
