### ISSUE TITLE
How to uninstall the old ABP CLI version or upgrade the ABP CLI?

### ISSUE THREAD

**Issue by jack-gaojz-zz** [abpframework/abp#5539]
![image](https://user-images.githubusercontent.com/40879710/93780510-d7713c00-fc5a-11ea-8ae7-6f931981af55.png)

When I plan to upgrade the latest ABP CLI, but failed.
`dotnet tool update -g Volo.Abp.Cli`
The error messages as below:
**Tool 'volo.abp.cli' failed to update due to the following:
Failed to create shell shim for tool 'volo.abp.cli': Command 'abp' conflicts with an existing command from another tool.
Tool 'volo.abp.cli' failed to install.**

I just want to list all the dotnet tool.
`dotnet tool list`
But no items list. And I want to uninstall the package using the command:
`dotnet tool uninstall -g Volo.Abp.Cli`
The follow message display: Tool 'volo.abp.cli' has multiple versions installed and cannot be uninstalled.

Anyone can give some suggestions? Thanks so much.

**Comment by amsaighi** [comment]
Hello, 

I tried and I get the same result, 
to get the lastest **abp** you can use other ways 


`  > switch-to-preview: Switches packages to preview ABP version.`
`   > switch-to-stable: Switches packages to stable ABP version from preview version.`
`  > switch-to-nightly: Switches packages to nightly preview ABP version.`

**Comment by maliming** [comment]
hi

`Volo.Abp.Cli` is dotnet tool. and it's published on [nuget.org](https://www.nuget.org/packages/Volo.Abp.Cli/3.2.0-rc.2).

You can refer to: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

**Comment by jack-gaojz-zz** [comment]
> Hello,
> 
> I tried and I get the same result,
> to get the lastest **abp** you can use other ways
> 
> ` > switch-to-preview: Switches packages to preview ABP version.`
> ` > switch-to-stable: Switches packages to stable ABP version from preview version.`
> ` > switch-to-nightly: Switches packages to nightly preview ABP version.`

I try to install the "Volo.Abp.Cli" and it always throws the error message as below:
![image](https://user-images.githubusercontent.com/40879710/93860782-2918d580-fcf2-11ea-8ddb-891c1224d669.png)
So I have to uninstall the previous version firstly. :(

**Comment by yekalkan** [comment]
@jack-gaojz 

1) Open `%USERPROFILE%\.dotnet\tools` directory, delete abp.exe.

2) Then open `.store` folder and delete `volo.abp.cli` folder.

3) Run `dotnet tool install Volo.Abp.Cli -g` command.

**Comment by jack-gaojz-zz** [comment]
> @jack-gaojz
> 
> 1. Open `%USERPROFILE%\.dotnet\tools` directory, delete abp.exe.
> 2. Then open `.store` folder and delete `volo.abp.cli` folder.
> 3. Run `dotnet tool install Volo.Abp.Cli -g` command.

It works, thanks so much. 👍
