### ISSUE TITLE
Localization does not work after Publish

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#555]
When debug the abp_io project locally, the Localization works fine.

The Localization does not work properly after the site is published.

`dotnet publish "abp_io/src/Volo.AbpWebSite.Web/Volo.AbpWebSite.Web.csproj" -c Release`

``` c#
app.UseRequestLocalization(options =>
{
	options.DefaultRequestCulture = new RequestCulture("zh-Hans", "zh-Hans");
	options.AddSupportedCultures("zh-Hans");
	options.AddSupportedUICultures("zh-Hans");
});
```

I think it is related to #554

**Comment by hikalkan** [comment]
I will check this. Thanks @maliming

**Comment by hikalkan** [comment]
Hi @maliming does that problem still exists?

**Comment by maliming** [comment]
Wait a moment for me to sync the code and test it out

**Comment by maliming** [comment]
@hikalkan 
 `In this document` still not working.


![image](https://user-images.githubusercontent.com/6908465/49431469-8b84a700-f7e8-11e8-8af6-257c0f6d8fa0.png)

![image](https://user-images.githubusercontent.com/6908465/49431512-a525ee80-f7e8-11e8-9112-d033b627ef72.png)

**Comment by hikalkan** [comment]
Can you try it like that: https://github.com/abpframework/abp/commit/fd72d7a61fe2e7d85e2b0a67cba5738d50218bad

Used `UseAbpRequestLocalization` instead of `UseRequestLocalization` and configured `AbpLocalizationOptions`.

**Comment by maliming** [comment]
I will try it to see.

**Comment by maliming** [comment]
It work. thanks @hikalkan

**Comment by djlaney3** [comment]
This is still broke with the latest starter template.
