### ISSUE TITLE
Blazor UI: Progress bar / loading indicator

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5554]
Especially for server side API calls, we should show a progress bar or some kind of loading indicator. This should be done automatically wherever possible (we can do it with an HttpClient handler).

**Comment by stsrki** [comment]
in progress: https://github.com/stsrki/Blazorise/issues/1244

**Comment by cetins32** [comment]
How can we Add  Loader/Spinner  gif  to all  Blazor UI pages 
in ComponentBase.cs.
Can we get visible Loader/Spinner  when action start and get unvisible Loader/Spinner  when action end
