### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by numanrauf** [abpframework/abp#5568]
While generating proxy gives error 
upgraded project from 2.9 to 3.1
also updated my solution accordingly:
https://docs.abp.io/en/abp/latest/UI/Angular/Service-Proxies

Error:
PS D:\Projects\Hadir\angular\angular> abp generate-proxy  
[14:36:09 INF] ABP CLI (https://abp.io)
[14:36:09 INF] Version 3.1.2 (Stable)
Maximum call stack size exceeded

**Comment by maliming** [comment]
Will be fixed in 3.2 https://github.com/abpframework/abp/pull/5295
