### ISSUE TITLE
Authorization failed! Given policy has not granted when use  await AuthorizationService.CheckAsync(policyName)

### ISSUE THREAD

**Issue by khinhvuphiduong** [abpframework/abp#5578]
Dear all,
I call API http://localhost:65115/api/permission-management/permissions?providername=R&providerkey=admin to get permission list. Below is the CheckProviderPolicy method in PermissionAppService Class, if I use await keyword, API will going error, but I use ConfigureAwait(false) API run correctly. I don't know why and how to fix it?

Thanks you for you support!

```
protected virtual async Task CheckProviderPolicy(string providerName)
        {
            var policyName = Options.ProviderPolicies.GetOrDefault(providerName);
            if (policyName.IsNullOrEmpty())
            {
                throw new AbpException($"No policy defined to get/set permissions for the provider {'policyName'}. Use {nameof(PermissionManagementOptions)} to map the policy.");
            }

            //OK
            //AuthorizationService.CheckAsync(policyName).ConfigureAwait(false);

            //Return ERR: Authorization failed! Given policy has not granted 
            await AuthorizationService.CheckAsync(policyName);
        }
```

**ERROR:**
`{
    "error": {
        "code": null,
        "message": "Authorization failed! Given policy has not granted.",
        "details": null,
        "validationErrors": null
    }
}`

**Comment by realLiangshiwei** [comment]
Actually `AuthorizationService.CheckAsync(policyName).ConfigureAwait(false);` will also get the exception. 

The code should be `await AuthorizationService.CheckAsync(policyName).ConfigureAwait(false);`.  actually the method is **not executed!**

The error message is **Authorization failed! Given policy has not granted**, you need to check your code, configuration, etc..

**Comment by khinhvuphiduong** [comment]
> Actually `AuthorizationService.CheckAsync(policyName).ConfigureAwait(false);` will also get the exception.
> 
> The code should be `await AuthorizationService.CheckAsync(policyName).ConfigureAwait(false);`. actually the method is **not executed!**
> 
> The error message is **Authorization failed! Given policy has not granted**, you need to check your code, configuration, etc..

Thanks Sir for your reply,

My problem may be i misktake when DI, I used **AbpPermissionManagementDomainIdentityServerModule** for **AbpPermissionManagementApplicationModule** in permission-management module, it is wrong, and **AbpPermissionManagementDomainIdentityModule** is what I should use.
