### ISSUE TITLE
why CurrentUser's username is null 

### ISSUE THREAD

**Issue by buxueke** [abpframework/abp#5596]
currentUser:
isAuthenticated: true
id: "946321ab-d89f-1b80-5941-39f78e88cdcf"
tenantId: null
userName: null
email: "admin@abp.io"
roles: ["admin"]

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by buxueke** [comment]
ABP Framework version: 3.1.0  MicroserviceDemo
in BackendAdminAppGateway.Host  ,These codes are added：
 app.Use(async (ctx, next) =>
            {
                var currentPrincipalAccessor = ctx.RequestServices.GetRequiredService<ICurrentPrincipalAccessor>();
                var map = new Dictionary<string, string>()
                {
                    { "sub", AbpClaimTypes.UserId },
                    { "role", AbpClaimTypes.Role },
                    { "email", AbpClaimTypes.Email },
                    { "name", AbpClaimTypes.UserName },
                    { "tenantid", AbpClaimTypes.TenantId }
                    //any other map
                };
                var mapClaims = currentPrincipalAccessor.Principal.Claims.Where(p => map.Keys.Contains(p.Type)).ToList();
                currentPrincipalAccessor.Principal.AddIdentity(new ClaimsIdentity(mapClaims.Select(p => new Claim(map[p.Type], p.Value, p.ValueType, p.Issuer))));
                await next();
            });
and in api/abp/application-configuration ,can get currentuser's username
but in  ProductAppService  still can't get currentuser's username
