### ISSUE TITLE
Widgets: depended JS not loaded in popups

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#5605]
* **ABP Framework version**:  3.1.2
* **User Interface**: MVC

I created a widget with a depended js.
When I render it in "Index.cshtml", the js is loaded as expected.
But when I use the widget in a popup modal, the JS file is not loaded.

To reproduce this issue, I modified the `DashboardDemo`. [here](https://github.com/wakuflair/WidgetInPopups) is the repo.

### Reproduce steps
1. launch the DashboardDemo.Web project
1. Navigate to `Dashboard Demo`
1. Click the `Show MyModal` button at the bottom
    ![image](https://user-images.githubusercontent.com/3471718/94236301-94a3b280-ff3f-11ea-9a06-9ee02fb91d29.png)
1. In the popup, the data of the `NewUserStatistic` widget cannot be displayed.
     ![image](https://user-images.githubusercontent.com/3471718/94236454-d6345d80-ff3f-11ea-9519-56b8160ba687.png)

**Comment by maliming** [comment]
Script and style will only be loaded on the layout page.
https://github.com/abpframework/abp/blob/41f8d03605632c5e36a017405536ec974c412bc9/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Application.cshtml#L77

**Comment by wakuflair** [comment]
> Script and style will only be loaded on the layout page.

Does this mean that Widgets with JS cannot be used in pop-up modals?
This greatly limits the use of Widgets.

After all I cannot enforce users to include a JS file of a widget defined in my module.
