### ISSUE TITLE
Remove the SessionState in the @abp/ng.core package

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#5606]
Use `SessionStateService` instead of the `SessionState`.

# Breaking Changes

* `SessionState` has been removed.
* `SessionState` actions (SetLanguage, SetTenant, ModifyOpenedTabCount, SetRemember) have been removed.
* `@ngxs/storage-plugin` package has been removed.
* `languageChange` getter of `LocalizationService` has been removed. Use `languageChange$` getter instead.
* `ngxsStoragePluginOptions` property of ` forRoot` of `CoreModule` has been removed.
* Some (getSessionDetail, dispatchSetTenant, dispatchSetLanguage, dispatchSetTenant, dispatchSetRemember, dispatchModifyOpenedTabCount ) of `SessionStateService` methods have been removed.

**Comment by EmileVerbunt** [comment]
Please update the 'nav-items' part as SessionState and SetLanguage have been deprecated.

https://docs.abp.io/en/abp/latest/UI/Angular/Component-Replacement
