### ISSUE TITLE
Project startup template(ASP.NET Core Mvc Module) content is incorrect.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#561]
Project startup template(ASP.NET Core Mvc Module) content is incorrect when `ProjectName` does not have `CompanyName`

MyCompanyName is not replaced. (ProjectName: QA)

![ASP.NET Core Mvc Module](https://user-images.githubusercontent.com/6908465/47417612-ed460000-d7aa-11e8-9ece-6ad5c3158bdc.png)

**Comment by hikalkan** [comment]
Thank you @maliming for reporting. We will work on that if there is anything can be done with current design.

**Comment by hikalkan** [comment]
I have already removed MyCompanyName folders from the startup template.
