### ISSUE TITLE
mergeStrategy property to remoteEnv configuration problem [BUG]

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#5610]
@mehmet-erim 

Hi.

I'm using ABP Version 3.1.1 and running webAPI without HTTPS.
My remoteEnv appsetings.json file is something like this:

```
{
  "production": true,
  "application": {
    "baseUrl": "http://domain.si/admin",
    "name": "Admin"
  },
  "oAuthConfig": {
    "issuer": "http://domain.si/cws",
    "redirectUri": "http://domain.si/admin",
    "clientId": "CIS_App",
    "responseType": "code",
    "scope": "offline_access CIS",
    "requireHttps": false
  },
  "apis": {
    "default": {
      "url": "http://domain.si/cws",
      "rootNamespace": "Sebit.CIS"
    }
  }
}
```

part of environment.ts file is:

```
remoteEnv: {
    url: '/assets/appsettings.json',
    mergeStrategy: "deepmerge",
    method: 'GET',
    headers: {}
  }
```

If configuration for requireHttps is put into quotes 

`    "requireHttps": "false"
`
i cannot login. I mean: There is nothing in console and client is not calling authority uri when i click on "Login" button.

How to reproduce ? 
Just take startup project, run web api without https, set requireHttps to false - in guotes !

Please advice, becouse this issuse breaks my CI/DI.

Regards.

**Comment by mehmet-erim** [comment]
Hi @sebitsi 

This scenario as it should be. Because `"false"` is not falsy value. You should not pass `"false"`. The `requireHttps` property is directly passed to `angular-oauth2-oidc`package as a configuration.

I want to draw attention to this:

```ts
if (false) { 
console.log('first')
}

if("false") {
console.log('second')
}
```

The "second" is logged, not "first".

**Comment by sebitsi** [comment]
@mehmet-erim  Thanks for your fast response.

Of course you are right. I forgot to think linke javascript programer. By bad.
