### ISSUE TITLE
Client reference host.api There was a problem when calling!? findactionasync

### ISSUE THREAD

**Issue by bestvcboy** [abpframework/abp#5617]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

ABP VNETX 3.2

namespace WXWorkApp
{
    public interface IMyService : ITransientDependency
    {
        public Task<GetDepartmentListResult> DoIt();
    }
}

namespace WXWorkApp
{
    public class MyService : ITransientDependency, IMyService
    {
        private readonly IMailListService _MailService;

        public MyService(IMailListService MailService)
        {
            _MailService = MailService;
        }

        public async Task<GetDepartmentListResult> DoIt()
        {
            return  await _MailService.GetAllDepartmentListAsync();

        }
    }
}

Here is the process:
      public async Task<ActionApiDescriptionModel> FindActionAsync(HttpClient client, string baseUrl, Type serviceType, MethodInfo method)
        {
            var apiDescription = await GetApiDescriptionAsync(client, baseUrl);

            //TODO: Cache finding?

            var methodParameters = method.GetParameters().ToArray();

            foreach (var module in apiDescription.Modules.Values)
            {
                foreach (var controller in module.Controllers.Values)
                {
                    if (!controller.Implements(serviceType))
                    {
                        continue;
                    }
Here “ServiceType” is Imaillistservice。 Here "controller" is maillistservice。As a result, the interface cannot be found.

**Comment by niufwshd** [comment]
@bestvcboy ,hello,I meet the same issue, Have you solve it ?.
