### ISSUE TITLE
Features Data Seeder Exapmle

### ISSUE THREAD

**Issue by khinhvuphiduong** [abpframework/abp#5621]
Dear all,
I create some Features [(https://docs.abp.io/en/abp/latest/Features),](https://docs.abp.io/en/abp/latest/Features) but I don't know how to insert to database? I try search but can't find any example. Please help?

Thanks you!

**Comment by maliming** [comment]
You can see the document first 
https://docs.abp.io/en/abp/latest/Features

**Comment by khinhvuphiduong** [comment]
> You can see the document first
> https://docs.abp.io/en/abp/latest/Features

Thanks you for your reply, I defined features step by step following the document, but I don't know how to seeder it to Database.

**Comment by khinhvuphiduong** [comment]
Dear all,
It's my mistake, IFeautureProvider is loaded on runtime, not load from database. Sorry!
