### ISSUE TITLE
How to integrate the DevExpress Blazor components with the ABP Blazor UI?

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5625]
Some people want to use DevExpress Blazor components with the ABP Blazor UI. It would be good if we write an article.

It is appreciated if anyone can take this? Otherwise, we will work on it. Thanks :)

**Comment by myomyinthan** [comment]
HI @hikalkan ,
Any plan for Telerik Blazor components with ABP Blazor UI  article?

**Comment by hikalkan** [comment]
@myomyinthan I created an issue for that: https://github.com/abpframework/abp/issues/5651

**Comment by geffzhang** [comment]
I've tested using DevExpress Blazor components with ABP Blazor UI, just refer to devexpress blazor nuget package
