### ISSUE TITLE
SettingManagementStore don`t read settings in 3.1 version

### ISSUE THREAD

**Issue by EugeniZaplatin** [abpframework/abp#5629]
When I used version 2.6, whith ISettingManagementStore I can Set()/Get() settings from Db.
But, when go to version 3.1, ISettingManagementStore only execute Set() correctly, but don`t Get()
Insted of it, I have to use ISettingRepository.

Who can explain this situation?

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by EugeniZaplatin** [comment]
1. Inject ISettingManagementStore
2. SetAsync() any setting
3. Try GetAsync()  it

My experience - GetAsync() return NULL

**Comment by realLiangshiwei** [comment]
It works fine.
![image](https://user-images.githubusercontent.com/16813853/94503085-383edc80-0238-11eb-86eb-69bc0683c284.png)

**Comment by EugeniZaplatin** [comment]
![image](https://user-images.githubusercontent.com/11317749/94509808-607e0980-023f-11eb-9f0e-4b363ea6a287.png)
my real experience don`t good

**Comment by realLiangshiwei** [comment]
Please use the startup template to reproduce this problem.

**Comment by EugeniZaplatin** [comment]
What do you mean by "startup template"

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/Startup-Templates/Application

**Comment by obassullu** [comment]
Hi @EugeniZaplatin I have had same issue . I defined default setting value in custom definition provider class as below . then i called SetAsync method in ISettingManagementStore and changed default setting value. After this process i called GetOrNullAsync method and read value as below 

![setting](https://user-images.githubusercontent.com/1825965/94617428-36196400-02b2-11eb-9a91-1b85a3868a0f.PNG)

![result](https://user-images.githubusercontent.com/1825965/94619263-3c5d0f80-02b5-11eb-9dea-770e36bf7112.PNG)

**Comment by realLiangshiwei** [comment]
@obassullu 
I can't see the problem in your code, `unchecked` is the expected value

![image](https://user-images.githubusercontent.com/16813853/94650480-63edbf80-0329-11eb-9b5e-9e89af3ef56a.png)

**Comment by obassullu** [comment]
hi @realLiangshiwei  
If there is no custom definition provider class such as NotificationSettingDefinitionProvider, the result is null. abp version 3.1.2

![settingresult](https://user-images.githubusercontent.com/1825965/94737431-7d692880-0376-11eb-8b95-f87978dd759c.PNG)

![settingdb](https://user-images.githubusercontent.com/1825965/94737509-98d43380-0376-11eb-91cd-43a0e70f844b.PNG)

no problem in abp version 2.9.0

**Comment by realLiangshiwei** [comment]
Please use the startup template to reproduce this problem.
