### ISSUE TITLE
multi tab with abp-dynamic-form

### ISSUE THREAD

**Issue by onurcanyilmaz** [abpframework/abp#5630]
Hello,

i want to use multi tabs in the abp dynamic form 
In this way I will take sub collection entitydto properties

```csharp
  <abp-dynamic-form> 
          <abp-tabs>
               <abp-tab>

               </abp-tab>
           </abp-tabs>
  </abp-dynamic-form>
``` 
Can I do this?
I dont found any example
Your taghelper tabs example link: https://bootstrap-taghelpers.abp.io/Components/Tabs

Thanks.

**Comment by yekalkan** [comment]
Yes, you can.  

Also, `Form Content Placement` example may be helpful for you:  https://bootstrap-taghelpers.abp.io/Components/Tabs

**Comment by onurcanyilmaz** [comment]
@yekalkan ,

How can I parse PersonDto with two tabs?
More than one model  can be added ?

in that;

```csharp
<abp-dynamic-form abp-model="PersonDto" asp-page="/Person/CreateModal">
    <abp-modal>
        <abp-modal-header title="@L["NewPerson"].Value"></abp-modal-header>
        <abp-modal-body>

<abp-tabs>
    <abp-tab title="PersonModel">
            <abp-form-content title="Person"/>
    </abp-tab>

    <abp-tab title="PersonCommunicationModel">
    </abp-tab>
</abp-tabs>

        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</abp-dynamic-form>
``` 
![image](https://user-images.githubusercontent.com/33642676/94543402-b3ad8780-0252-11eb-8d67-4802abcb3da2.png)
![image](https://user-images.githubusercontent.com/33642676/94543474-cb850b80-0252-11eb-9adf-074245c07bf2.png)

thanks for help.

**Comment by yekalkan** [comment]
`abp-dynamic-form` is good for basic forms. If you want to divide form into tabs, It would be better to use `abp-input`: https://bootstrap-taghelpers.abp.io/Components/FormElements
