### ISSUE TITLE
Blazor UI: Tenancy Management 

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5633]
There are possibly 2 small bugs in the dev branch:

1. the `Tenant management` menu item is not clickable
2. in order to get around above one can use the `tab` key however when the menu item is activated it navigates to the wrong url as show below:

https://localhost:44307/~/tenant-management/tenants

### To reproduce this error 
run the blazor template from the dev branch as explained in the comment here:
https://github.com/abpframework/abp/issues/394#issuecomment-678915157

**Comment by cotur** [comment]
We are currently working on it, it will be fixed soon. Thanks @274188A

**Comment by cotur** [comment]
Menu item will be clickable after this issue is finished. https://github.com/abpframework/abp/issues/5529
