### ISSUE TITLE
Test the DexExtreme Angular article

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5641]
* Related PR: https://github.com/abpframework/abp/pull/5640
* Article: https://github.com/abpframework/abp/blob/docs/devextreme-angular-blogpost/docs/en/Community-Articles/2020-09-28-Using-DevExtremeAngularComponents-With-The-ABP-Framework/Using-DevExtremeAngularComponents-With-The-ABP-Framework.md

@bnymncoskuner currently working on. @bnymncoskuner please write after you finalize it, so @realLiangshiwei can test it.

@realLiangshiwei I intentionally wanted to assign this to you. I want a non-angular-expert developer can follow the article. Please take not for the parts you can't do by following the tutorial.

**Comment by hikalkan** [comment]
The article has been published: https://community.abp.io/articles/using-devextreme-angular-components-with-the-abp-framework-x5nyvj3i

**Comment by hikalkan** [comment]
Assigned to @yekalkan

**Comment by yekalkan** [comment]
I've easily followed the steps.
