### ISSUE TITLE
Logout does not redirect to Angular site

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#5644]
3.1.2 on Angular

![image](https://user-images.githubusercontent.com/6149843/94575125-92619100-027c-11eb-96bf-90cabba727b9.png)

JS error: **Uncaught TypeError: Cannot read property 'getAttribute' of null**
Source:

```
document.addEventListener("DOMContentLoaded", function(event) {
	setTimeout(function () {
        window.location = document.getElementById("redirectButton").getAttribute("href");
    }, 3000)
});
```

None of condition is true and there is really no such button in markup in our case:

```
  <abp-card>
    <abp-card-body>
        <abp-card-title>@L["LoggedOutTitle"]</abp-card-title>
        <abp-card-text>@L["LoggedOutText"]</abp-card-text>
        @if (Model.PostLogoutRedirectUri != null)
        {
            <a abp-button="Primary" id="redirectButton" href="@Model.PostLogoutRedirectUri">@L["ReturnToText", Model.ClientName]</a>
        }
        @if (Model.SignOutIframeUrl != null)
        {
            <iframe class="signout logoutiframe" src="@Model.SignOutIframeUrl"></iframe>
        }
    </abp-card-body>
  </abp-card>
```

What do we need to set up to make it work? We do not set PostLogoutRedirectUri anywhere. Why do we need it? Can't we just use JSON settings instead (where we set up Angular front-end URL)?

**Comment by alexandis** [comment]
Found this in the notes:

> Add `http://localhost:4200` to `IdentityServerClientRedirectUris` and `IdentityServerClientPostLogoutRedirectUris` tables for the same client.

Sorry. Closing.

**Comment by journey191** [comment]
@alexandis Hi,
I got the same error 
![image](https://user-images.githubusercontent.com/11626700/122375732-1340f400-cf96-11eb-83e7-5f88a08061e9.png)

But I had added `RedirectUris ` and `PostLogoutRedirectUris`:
![image](https://user-images.githubusercontent.com/11626700/122375617-f99fac80-cf95-11eb-8345-625be4f0dda2.png)

what was wrong?

**Comment by alexandis** [comment]
Hi, i don't remember now - has been a while ago... And now - different version of ABP. Probably, the endpoint addresses are not fully correct? In my case, I am having just a host name (e.g. https://localhost:4200 - we use Angular app) in both cases.

**Comment by journey191** [comment]
> Hi, i don't remember now - has been a while ago... And now - different version of ABP. Probably, the endpoint addresses are not fully correct? In my case, I am having just a host name (e.g. https://localhost:4200 - we use Angular app) in both cases.

I find the answer from here:https://stackoverflow.com/questions/44684664/identityserver4-postlogoutredirecturi-null
Still Thanks
