### ISSUE TITLE
Abp generate-proxy problem with KeyValuePair<Guid, string> - Generic Classes

### ISSUE THREAD

**Issue by miguelcanot** [abpframework/abp#5645]
Version-3.1.2.
Angular
Cannot read property 'children' of null
abp generate-proxy

When a use the command **abp generate-proxy**, the console throws the error: **Cannot read property 'children' of null**

This happen when i have service  that return: **List<KeyValuePair<Guid, string>>**

```
public async Task<List<KeyValuePair<Guid, string>>> GetKeyValueAsync(CancellationToken cancellationToken = default)
{
   -----code
}
```

The problem appears to be the generic values because if i use a Dto that have defined the types like this work fine:

```
public class KeyValueDto
{
    public Guid Key { get; set; }
    public string Value { get; set; }

    public KeyValueDto(Guid key, string value)
    {
        Key = key;
        Value = value;
    }
}

public async Task<List<KeyValueDto>> GetKeyValueAsync(CancellationToken cancellationToken = default)
{
   -----code
}


```

**Comment by maliming** [comment]
So it is recommended that you use DTO. : )

**Comment by serridavide** [comment]
hello, i have the same issue.

**Comment by ebicoglu** [comment]
use DTO ! don't use the generic types `KeyValuePair<Guid, string>`

**Comment by miguelcanot** [comment]
So I close the issue because we need to use DTO instead of generics?

**Comment by maliming** [comment]
@miguelcanot  Yes, https://docs.abp.io/en/abp/latest/Data-Transfer-Objects
