### ISSUE TITLE
Blazor UI Template - Compile Error - RZ9992

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5647]
...\abp\templates\app\aspnet-core\src\MyCompanyName.MyProjectName.Blazor\Pages\Index.razor

line `123`

>Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ9992	Script tags should not be placed inside components because they cannot be updated dynamically. To fix this, move the script tag to the 'index.html' file or another static location. For more information see https://go.microsoft.com/fwlink/?linkid=872131		..\abp\templates\app\aspnet-core\src\MyCompanyName.MyProjectName.Blazor\Pages\Index.razor	123	

![image](https://user-images.githubusercontent.com/40014477/94632935-74d50b80-02fe-11eb-8dcc-f42ce1208efd.png)

>using Microsoft Visual Studio Enterprise 2019 Preview Version 16.8.0 Preview 3.2

### java script isolation

https://www.meziantou.net/javascript-isolation-in-blazor-components.htm

**Comment by 274188A** [comment]
i have a feeling java script isolation will be available for .net 5.0 on wards.

https://www.meziantou.net/javascript-isolation-in-blazor-components.htm

**Comment by realLiangshiwei** [comment]
@cotur 
Can you check this?

**Comment by cotur** [comment]
I've fixed it. Thanks.
