### ISSUE TITLE
connectionstring-coustom connection string name

### ISSUE THREAD

**Issue by Qlimax2009** [abpframework/abp#5648]
Hello,
I follow the document to switch to MySQL.
[https://docs.abp.io/en/abp/3.1/Entity-Framework-Core-MySQL]
I ran the .DbMigrator project successfully.
But when I defined a custom connection string name in appsettings.json,and I replaced the  connection string name in .efcore and .efcore.dbmigrations project ,it ran error.
What I will do can you please guide me?
Thanks In advance.
![20200930_101653](https://user-images.githubusercontent.com/48152443/94635849-34798b80-0306-11eb-8482-4e19b541050b.png)
![20200930_101706](https://user-images.githubusercontent.com/48152443/94635864-3cd1c680-0306-11eb-889d-5124107ad14d.png)
![20200930_101712](https://user-images.githubusercontent.com/48152443/94635871-3fccb700-0306-11eb-869b-663e07a4684d.png)
![20200930_101003](https://user-images.githubusercontent.com/48152443/94635434-37c04780-0305-11eb-88a0-907363882b59.png)
![20200930_100850](https://user-images.githubusercontent.com/48152443/94635467-49a1ea80-0305-11eb-85ba-9c6c3eb50e7b.png)
![20200930_100938](https://user-images.githubusercontent.com/48152443/94635471-4c9cdb00-0305-11eb-842e-7c2c24441c18.png)

**Comment by realLiangshiwei** [comment]
Try:

```csharp
Configure<AbpDbConnectionOptions>(options =>
{
      options.ConnectionStrings.Default = configuration.GetConnectionString("MysqlDefault");
});
```

**Comment by Qlimax2009** [comment]
It works when ran the .DbMigrator project .
But it was still error when ran the host.
So must I use the default connection string name -”Default”？Or must be assigned to “options.ConnectionStrings.Default”？
![20200930_112901](https://user-images.githubusercontent.com/48152443/94640168-77d8f780-0310-11eb-94f8-e77e5eeb1287.png)

**Comment by realLiangshiwei** [comment]
Put the code to the `domain` module class.

**Comment by Qlimax2009** [comment]
It works.
thank you very much!
