### ISSUE TITLE
Remove the Angular Account Module UI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5652]
For the Angular UI (and the new Blazor UI) we are using the MVC UI for login, register, manage profile... etc. This is because we are using code authorication flow to make the user login.

So, we can drop the Angular account module UI completely. We should discuss that.

**Comment by aelhadi** [comment]
Hi,
how to customize (or override) the MCV UI login page? 

regards

**Comment by maliming** [comment]
> how to customize (or override) the MCV UI login page?

See https://support.abp.io/QA/Questions/160/How-to-customize-an-ABP-project
