### ISSUE TITLE
Upgrade HtmlAgilityPack package

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#5653]
[HtmlAgilityPack.NetCore](https://github.com/zulfahmi93/HtmlAgilityPack.NetCore)  repository has been archived, we can use the latest [HtmlAgilityPack](https://github.com/zzzprojects/html-agility-pack).

By the way, We don’t seem to use any features of HtmlAgilityPack in `Volo.Abp.Cli.Core`, maybe we can remove the package reference.

https://github.com/abpframework/abp/blob/0efbf56976662b5cf7b959f9cbf1c5fc364bf86b/framework/src/Volo.Abp.Cli.Core/Volo.Abp.Cli.Core.csproj#L17

**Comment by hikalkan** [comment]
If we don't use it anywhere, we can remove it. Otherwise, you can change it.

**Comment by NiceLisan** [comment]
yes, i aslo founded the package HtmlAgilityPack  wan't used anywhere in the Volo.Abp.Cli.Core.csproj since the verision V3.1.
