### ISSUE TITLE
Blazor UI Basic Theme menu enhancement

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5655]
I haven't implemented this logic for the Blazor UI: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/wwwroot/themes/basic/layout.js#L2-L15

Currently it works but has a small bug: If you click a submenu which has a submenu, it remains opened when you hover another submenu.

Example:

![basic-theme-menu-problem](https://user-images.githubusercontent.com/1210527/94700424-20ed1580-0344-11eb-8fe0-6d4facb91b0b.gif)

**Comment by 274188A** [comment]
There have been other projects targeting menu features that may provide some inspiration:

- https://github.com/stavroskasidis/BlazorContextMenu (225 likes)
- https://github.com/Blazored/Menu (99 likes)

both still active

HTH

**Comment by 274188A** [comment]
tested this - looking good and able to click menu items

**Comment by hikalkan** [comment]
Cancelling this. It is same in the MVC UI too and it look like the normal behaviour.
