### ISSUE TITLE
Community Article: the core goal of abp vNext

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#5657]
The core goal of abp is to quickly build a microservice framework or a complete application framework?

I think the core goal of abp is a framework to quickly build a microservice architecture.

If it is to build microservices quickly, the focus of abp should be the continuous development of microservice-related modules, examples, etc.

For example, in the cloud native development framework, the current module functions are relatively poor.

**Comment by hikalkan** [comment]
I think this is not a community article idea. The goals of the ABP Framework includes both. However, it is pretty new (compared to the original AspNet Boilerplate) and we are continously adding documents and samples. Microservice samples, documentes and even tooling are in our road map.
