### ISSUE TITLE
Grammar on main apb.io page

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5664]
https://abp.io/#section-2

![image](https://user-images.githubusercontent.com/40014477/94786206-3c6b2580-0403-11eb-91ca-458add04c778.png)

**Comment by maliming** [comment]
hi @274188A 

You can change the text if you like. : )

https://github.com/abpframework/abp/blob/e505ef2931e0f85813530db702c99f767431e913/abp_io/AbpIoLocalization/AbpIoLocalization/Www/Localization/Resources/en.json#L48

**Comment by 274188A** [comment]
done
