### ISSUE TITLE
Distributed Entity Cache base class

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5668]
ASP.NET Boilerplate has a base class to easily implement caching for entities:
https://aspnetboilerplate.com/Pages/Documents/Caching#entity-caching

We can implement a similar base class for the ABP Framework too. Something like that (can be different, it is a pseudo code):

````csharp
public class PersonCache : EntityCache<Person, PersonCacheItem, TKey>, ITransientDependency
{
    public PersonCache(IDistributedCache<PersonCacheItem> cache, IRepository<Person, TKey> repository)
        : base(cache, repository)
    {

    }
}
````

`Volo.Abp.Ddd.Domain` package seems fine for this implementation, you think on.

**Comment by zhjmao** [comment]
any plans for this?

**Comment by hikalkan** [comment]
Resolved by https://github.com/abpframework/abp/pull/14055
