### ISSUE TITLE
Problem with paths on the site published to Azure (IIS hosting)

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#5671]
3.1.2 on Angular.

The problems with paths for a published site are not resolved till now:

1) assets path for Angular site is calculated relative to host root, not custom www subpath:

![image](https://user-images.githubusercontent.com/6149843/94862994-6f80d980-0442-11eb-87e5-889040dff818.png)

Needs to be .azure.com/centraltools/assets... instead

![image](https://user-images.githubusercontent.com/6149843/94863806-b3c0a980-0443-11eb-834a-62258dca73ed.png)

2) Identity server also has issues with some resources:

![image](https://user-images.githubusercontent.com/6149843/94863187-bcfd4680-0442-11eb-9b6d-364e95270ba8.png)
![image](https://user-images.githubusercontent.com/6149843/94863239-cf778000-0442-11eb-8277-956166790627.png)

What about correct paths for **PostBack** and **Return** _URLs_? Do I need to create separate **client ID** for a local site (that is run as http://localhost:4200) and remote site (https://....azure.com/centraltools)? It was not needed in previous versions. In short: what do I need to change in my settings, DB tables to successfully login from published Angular site to published IdentityServer?

**Comment by realLiangshiwei** [comment]
1. It has nothing to do with ABP.
Check: http://codebuckets.com/2018/05/26/hosting-angular-in-iis-under-an-existing-website/
2. You need to change the `appsettings` and angular env configuration

**Comment by alexandis** [comment]
> 1. It has nothing to do with ABP.
>    Check: http://codebuckets.com/2018/05/26/hosting-angular-in-iis-under-an-existing-website/
> 2. You need to change the `appsettings` and angular env configuration

Probably I should have been more verbose. We aleady have had everything up and running on ABP 2.9.0. But this has been broken in version 3.1.2, when you have changed a lot of things, including login. Please, be more specific and provide the example of **appsettings.json** (with CORS, other things, like client section set up) and **environment.ts** files for such deployed scenanio, because what we have now set up does not work when being deployed (works for localhost only). The structure of deployed to IIS projects is already shown in first post. Also I'm not sure the problem with path to _assets_ is related to _IIS_ settings.

Thank you.

**Comment by alexandis** [comment]
Please let me know if it's an **ABP** bug (if so - when are you planning to fix it) or path settings issue. We keep getting the path issues. Now it's:

![image](https://user-images.githubusercontent.com/6149843/95237717-3add9b00-0811-11eb-9fbd-e601a5d99e41.png)

Looks like path is incorrect - it supposes the path is root instead of /IdentityServer (relative path) somewhere inside of ABP script guts:

`var tenantSwitchModal = new abp.ModalManager(abp.appPath + 'Abp/MultiTenancy/TenantSwitchModal');`

Temporarily fixed this remotely by making:

`abp.appPath = abp.appPath || '/IdentityServer/';`

But of course the path needs to be dependent on appsetings (selfUrl?) Not sure how to use it right...

And another issues with paths indicated in the first post still exist in final version 3.2. Do I need to use resourcemapping? Please, provide the instruction then.

**Comment by abou-emish** [comment]
For apps hosted in IIS / Virtual application  How to set abp.appPath from Server, for example appsetings App:SelfUrl ?
We can't set it manually every time we deploy, as we are using CI/CI
