### ISSUE TITLE
How can i quickly generate angular Npm feature libraries

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#5673]
I see many package  module in path `/npm/ng-packs/packages` , I found that they used some unified packages. 
My quesiton: How do I quickly generate these Npm packages. Now for each package I need to copy and paste the common reference section. 

thanks.

![image](https://user-images.githubusercontent.com/7290992/94882036-7555d980-0499-11eb-92e6-2fb39f8c73cd.png)

**Comment by realLiangshiwei** [comment]
I don't understand what you mean

**Comment by Loongle** [comment]
> I don't understand what you mean

@realLiangshiwei How can I quickly make an NPM package like @abp/ng.identity.  Because I look at them as clean like code generated

**Comment by Loongle** [comment]
Are these Npm packages of ABP built by manual, not by generative tools?

**Comment by maliming** [comment]
We use some scripts to do these repetitive work, but these scripts cannot be shared.
