### ISSUE TITLE
Specific permission to new tenant admin when create new tenant.

### ISSUE THREAD

**Issue by khinhvuphiduong** [abpframework/abp#5674]
Dear all, to my knowledge, when I create new tenant, dataseeder method will find all class inherit  PermissionDefinitionProvider class (in dependencies modules) insert to database. My question is: How I can ignore some PermissionDefinitionProvider class when create new tenant.

Thank you,
Best regard!

**Comment by maliming** [comment]
>  dataseeder method will find all class inherit PermissionDefinitionProvider class (in dependencies modules) insert to database. 

It doesn't work like this. see https://docs.abp.io/en/abp/latest/Authorization#permission-system


> How I can ignore some PermissionDefinitionProvider class when create new tenant.

This is by design, of course, you can customize the built-in code. https://support.abp.io/QA/Questions/160/How-to-customize-an-ABP-project

**Comment by khinhvuphiduong** [comment]
> > dataseeder method will find all class inherit PermissionDefinitionProvider class (in dependencies modules) insert to database.
> 
> It doesn't work like this. see https://docs.abp.io/en/abp/latest/Authorization#permission-system
> 
> > How I can ignore some PermissionDefinitionProvider class when create new tenant.
> 
> This is by design, of course, you can customize the built-in code. https://support.abp.io/QA/Questions/160/How-to-customize-an-ABP-project

I got it, thank you so much, lots of new knowledge when research ABP Framework.
