### ISSUE TITLE
DependencyResolutionException error after add app.UseIdentityServer();

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#5675]
I added a new template width angular and identityserver separated, after added app.UseIdentityServer(); into HttpApiHostModule.cs, there is error in the below, where is the problem? thanks in advance

An unhandled exception occurred while processing the request.
DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Volo.Abp.IdentityServer.AspNetIdentity.AbpResourceOwnerPasswordValidator' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.AspNetCore.Identity.SignInManager`1[Volo.Abp.Identity.IdentityUser] signInManager' of constructor 'Void .ctor(Microsoft.AspNetCore.Identity.UserManager`1[Volo.Abp.Identity.IdentityUser], Microsoft.AspNetCore.Identity.SignInManager`1[Volo.Abp.Identity.IdentityUser], Volo.Abp.Identity.IdentitySecurityLogManager, IdentityServer4.Services.IEventService, Microsoft.Extensions.Logging.ILogger`1[IdentityServer4.AspNetIdentity.ResourceOwnerPasswordValidator`1[Volo.Abp.Identity.IdentityUser]], Microsoft.Extensions.Localization.IStringLocalizer`1[Volo.Abp.IdentityServer.Localization.AbpIdentityServerResource], Microsoft.Extensions.Options.IOptions`1[Volo.Abp.Identity.AbpIdentityOptions], Volo.Abp.DependencyInjection.IHybridServiceScopeFactory)'.
Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(ConstructorInfo[] availableConstructors, IComponentContext context, IEnumerable<Parameter> parameters)

DependencyResolutionException: An exception was thrown while activating IdentityServer4.Endpoints.DiscoveryEndpoint -> IdentityServer4.ResponseHandling.DiscoveryResponseGenerator -> Volo.Abp.IdentityServer.AspNetIdentity.AbpResourceOwnerPasswordValidator.
Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable<Parameter> parameters)

![image](https://user-images.githubusercontent.com/4489940/94883205-a08df800-049c-11eb-9ae4-8352ac60c7b6.png)

**Comment by realLiangshiwei** [comment]
Please use the startup template to reproduce.

**Comment by ruby0602** [comment]
> Please use the startup template to reproduce.

I reproduced the template, it had the same error

**Comment by realLiangshiwei** [comment]
Can you upload the project to Github and write the repository address in here

**Comment by ruby0602** [comment]
@realLiangshiwei https://github.com/ruby0602/httpapihost，code had been uploaded

**Comment by ruby0602** [comment]
@realLiangshiwei link with error is https://localhost:44387/.well-known/openid-configuration

**Comment by realLiangshiwei** [comment]
The project you uploaded is not full

**Comment by ruby0602** [comment]
@realLiangshiwei you call me to upload the solution or project？

**Comment by ruby0602** [comment]
@realLiangshiwei thanks,I found the problem is the separate identityServer mode, integrated mode is fine.
