### ISSUE TITLE
BusinessException: Tenant not found!

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#5682]
ABP Framework version 3.2
UI Blazor

BusinessException: Tenant not found!

Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass5_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension+<>c__DisplayClass0_0+<<UseJwtTokenMiddleware>b__0>d.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass5_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass5_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by aelhadi** [comment]
I think the Tenant Seed prodecure is measing ....

**Comment by cotur** [comment]
Hi @aelhadi,

How do you get this error, can you explain more? So I can try to reproduce.

**Comment by 274188A** [comment]
I raise similar #5691

**Comment by aelhadi** [comment]
Exactly as described in #5691.

**Comment by aelhadi** [comment]
Clearing browser cache will solve the problem.

**Comment by muzoaydo** [comment]
Same as here clearing the cache solved it but when i use ABP i encounter so many cache bugs. Do you have any suggestions to prevent these kinda bugs ?

**Comment by maliming** [comment]
>  i encounter so many cache bugs.

Can you give us an example?
