### ISSUE TITLE
--separate-identity-server mode have a error

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#5693]
I use intergated identityServer compared with the separate mode，the separate mode have a big error in angular-oauth2-oidc.js:
error loading discovery document

**Comment by maliming** [comment]
hi

* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by leonkosak** [comment]
Do you have Redis and configured properly in appsettings.json files?

**Comment by ruby0602** [comment]
> Do you have Redis and configured properly in appsettings.json files?

you are right I haven't installed Redis, thanks
