### ISSUE TITLE
Tenant not found! When host API in TenantManagerService.Host

### ISSUE THREAD

**Issue by khinhvuphiduong** [abpframework/abp#5698]
Dear all,
I've a API, when I host in TenantManagerService.Host, and used a access token with tenantid to test the API but it's always throws T**enant not found!**  error. If I used a access token without tenantid API run correctly. 

When I host the API on another host, everything is ok, whether or not tenanid. I compared Start class, there's no middle-ware different.

It's not cookie problems.

Sorry for my English, it's difficult to express, I hope everybody can understand what I mean.
Thanks so much.

**Comment by khinhvuphiduong** [comment]
Dear all, API work if I comment below code.
 `app.UseAuthentication();`
or
 `
 if (MsConsts.IsMultiTenancyEnabled)
            {
                app.UseMultiTenancy();
            }
`
It's so confused when app.UseAuthentication() and   app.UseMultiTenancy() work together in a microservice.

**Comment by xyfy** [comment]
I got the same err in the microservice

**Comment by xyfy** [comment]
the api works fine call api in modules ,but when cross other module's appservice

**Comment by khinhvuphiduong** [comment]
> the api works fine call api in modules ,but when cross other module's appservice

I got the same when cross API over Internal Gateway, but work when I call directly to destination micro-service.

**Comment by xyfy** [comment]
#3842

**Comment by xyfy** [comment]
this will be helper full

**Comment by khinhvuphiduong** [comment]
> this will be helper full

Yes, thank you. I have just find by add  AbpTenantManagementApplicationContractsModule and AbpTenantManagementEntityFrameworkCoreModule in any host or service use Multi Tenant.
