### ISSUE TITLE
Blazor UI: When AD is Integrated - How to Customize Login Page?

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5699]
In the scenario where we are using AD (like [this](https://community.abp.io/articles/how-to-setup-azure-active-directory-and-integrate-abp-angular-application-lyk87w5l) ), we need a sample project to demonstrate how to customize the Login Page (similar to [this sample](https://community.abp.io/articles/how-to-customize-the-login-page-for-mvc-razor-page-applications-9a40f3cd))

**Comment by berkansasmaz** [comment]
See https://github.com/abpframework/abp/issues/5601#issuecomment-698954580

**Comment by 274188A** [comment]
ah - ok, guess I can handle this in the actual module as a last resort
