### ISSUE TITLE
**abp** Widget StyleTypes not being called, ScriptTypes are

### ISSUE THREAD

**Issue by melfahn** [abpframework/abp#5704]
version 3.2
 MVC

 when using the below code the script bundle works as expected, the style bundle never gets called

    [Widget(StyleTypes = new[]
    {
        typeof(SearchWidgetStyleBundleContributor)
    }, ScriptTypes = new[]
    {
        typeof(SearchWidgetScriptBundleContributor)
    })]

    internal class SearchWidgetStyleBundleContributor : BundleContributor
    {
        public override void ConfigureBundle(BundleConfigurationContext context)
        {
            context.Files.AddIfNotContains("/themes/keystone/css/search.css");
            context.Files.AddIfNotContains("/libs/jquery-ui-dist/jquery-ui.min.css");
        }
    }

    internal class SearchWidgetScriptBundleContributor : BundleContributor
    {
        public override void ConfigureBundle(BundleConfigurationContext context)
        {
            context.Files.AddIfNotContains("/themes/keystone/js/search.js");
            context.Files.AddIfNotContains("/libs/jquery-ui-dist/jquery-ui.min.js");
        }
    }

**Comment by maliming** [comment]
hi @melfahn

Can you share a project to reproduce this problem?
