### ISSUE TITLE
Identity Server spend 2.4 min on loading ApplicationConfigurationScript

### ISSUE THREAD

**Issue by csabc** [abpframework/abp#5708]
I created a project from abp.io  with  blazor  template and separate IdentityServer. when i open identityserver url,open chrome devtool,i find  it spend 2.4 min on loading "ApplicationConfigurationScript". abp ver is 3.2. click the login button  also  spend a long time,then chrome  exit.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/2764#issuecomment-582690562

**Comment by csabc** [comment]
if you don't use redis ,please comment the AbpCachingStackExchangeRedisModule

`        //typeof(AbpCachingStackExchangeRedisModule),
`

**Comment by csabc** [comment]
> See [#2764 (comment)](https://github.com/abpframework/abp/issues/2764#issuecomment-582690562)

Thanks!
