### ISSUE TITLE
Dynamic form and Audit Fields

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#571]
I am using a dynamic form that uses a Dto that implements AuditedEntityDto.  When the form shows, it shows all the audit fields for input.  Are those hideable?  It seems that they should auto populate behind the scenes on save.  Is this not how that works?  Is that feature not available yet?

**Comment by hikalkan** [comment]
You should then separate your DTOs for "show data" and "save data".
I mean you can create a DTO that is not derived from AuditedEntityDto and use it for the creation form.

**Comment by djlaney3** [comment]
I changed my create/update dto to inherit from EntityDto and the dynamic form only shows my custom fields.   But, on saving, the audit fields do not get updated.  Should they?  It seems like the framework does this automatically but I can't get it to work.    So my underlying entity inherits from AuditedEntity, but the create/update dto inherits from AuditedEntityDto.  Should this the audit fields auto populate?

**Comment by hikalkan** [comment]
Create/edit/update DTOs should not derive from audited DTOs. Auditing properties of the entity are automatically managed by the framework. Create properties set on creation, modification properties are set on update. Doesn't that work?

**Comment by djlaney3** [comment]
It does seems to work for updates.  For creates, my key is a bigint that auto increments.  It appears the create dynamic form wants me to put in a value, but of course, the db won't accept it because it is the identity field.  How do I set that up properly?

**Comment by djlaney3** [comment]
Maybe I am mis understanding what you are saying.  Here are my objects:
CreateUpdateCareerDto.cs
`[AutoMapTo(typeof(Career))]
    [AutoMapFrom(typeof(CareerDto))]
    public class CreateUpdateCareerDto : EntityDto<long>
    {
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(int.MaxValue)]
        public string Note { get; set; }
    }`
Career.cs --entity
` public class Career : AuditedEntity<long>
    {        
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(int.MaxValue)]
        public string Note { get; set; }
    }`
The Id field shows up on both create and update.

**Comment by djlaney3** [comment]
CareerDto
`[AutoMapFrom(typeof(Career))]
    public class CareerDto : EntityDto<long>
    {
        public string Name { get; set; }

        public string Note { get; set; }
    }`

**Comment by acjh** [comment]
Please format code like this:
<pre>
```c#
// Your code
```
</pre>

**Comment by acjh** [comment]
`CreateUpdateCareerDto` should not inherit `EntityDto`.

**Comment by djlaney3** [comment]
Ok.. Made that change.  Create works fine now.  But update is not saving the LastModificationTime or LastModifierId columns.  What am I doing wrong there?

Also, CareerDto should inherit from EntityDto<long>?

**Comment by acjh** [comment]
- `LastModificationTime` should be set — check properly.
- `LastModifierId` is set if the user is in the same tenant. If multi-tenancy is on, `Career` should inherit `IMustHaveTenant` or `IMayHaveTenant`. If it inherits `IMayHaveTenant`, the `TenantId` must be set explicitly.

**Comment by djlaney3** [comment]
LastModificationTime ->  other than looking at the db field, how do I check properly?

**Comment by acjh** [comment]
Show code for updating.

**Comment by djlaney3** [comment]
It is a dynamic form, the framework should handle it, shouldn't it?

**Comment by yekalkan** [comment]
[HiddentInput] attribute will hide the Id input box while you are editing the entity. See [that example](https://github.com/abpframework/abp/blob/master/modules/blogging/src/Volo.Blogging.Web/Pages/Blog/Posts/Edit.cshtml.cs#L71).

Other fields (CreationTime, LastModificatioTime etc.) shouldn't be there anyway.

**Comment by djlaney3** [comment]
I'm not seeing how your comment is relevant to my issue.  The audit fields are not present and shouldn't be on the edit forms.  However, the LastModificationTime isn't being populated under any circumstance, and from what has been shown in this thread, it should be.

**Comment by yekalkan** [comment]
> I am using a dynamic form that uses a Dto that implements AuditedEntityDto. When the form shows, it shows all the audit fields for input. Are those hideable?

And i just mentioned that dynamic-form will hide the fields that has [HiddentInput] attribute, if you're wondering.

**Comment by djlaney3** [comment]
I did another test using the BookStore sample app.  It has the same issue.  LastModificationTime does not populate on update.

**Comment by hikalkan** [comment]
@djlaney3 can you create an issue for "LastModificationTime does not populate on update".

**Comment by djlaney3** [comment]
Opened new issue, #579.  Closing this one.
