### ISSUE TITLE
Blazor UI Project: FullAuditedEntity not saving some Audit Fields 

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#5716]
Example:
Entity is defined as:

```
 public class Gender : FullAuditedEntity<Guid>
    {
       //<snipped/>
    }
```

However when an Entity is created, modified, or deleted, the columns associated with the user remain `NULL`

Example: `CreatorId`, `LastModifier` and `DeleterId` are not being persisted as expected.

![image](https://user-images.githubusercontent.com/40014477/95205096-809d6200-0817-11eb-93f3-89ae1c4774f7.png)

**Comment by cotur** [comment]
Hi @274188A 

This is not related for Blazor UI,

But I've tested it on Blazor and couldn't see any problem. And I see the the `LastModificationTime` is recorded. 

![image](https://user-images.githubusercontent.com/20099739/95449273-34643600-096d-11eb-81f6-84a991861c15.png)

Is there any login issue for your case, did you check it?

**Comment by 274188A** [comment]
Agree nor related to Blazor - i'm sorry for that mistake.

There are no login issues.  I'm still trying to pass the id back to the AppService inside the dto but no luck so far.

I'm still checking/investigating...

**Comment by 274188A** [comment]
Just checked the Sample for [BlazorUI](https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore) and it has the same problem...

**Comment by cotur** [comment]
I could not reproduce it on BookStore-Blazor-EfCore sample application. It works as expected. (I've created new book and edited that book entity)

![image](https://user-images.githubusercontent.com/20099739/95473421-c3347b00-098c-11eb-8744-bc27fac8a2ed.png)

**Comment by 274188A** [comment]
Yes - i agree with your findings - must be some error in my code - I'm not using AuditedAggregateRoot though...

**Comment by 274188A** [comment]
I have found something interesting.  Yes it works with `AuditedAggregateRoot<T>`  bu not with `FullAuditedEntity<T>`.

Can you please check if you also have same results?

**Comment by 274188A** [comment]
Found my error - thanks for your time - all good
