### ISSUE TITLE
Create a Rebus integration sample

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5718]
Merge https://github.com/abpframework/abp/pull/5637 then create a sample application with a real MQ server integrated, like RabbitMQ.

Also, do you want to create a [community article](https://community.abp.io/articles) to explain the sample (how you built it and how to run)?

**Comment by maliming** [comment]
Rebus is not very popular, and the code of the example is very simple. I think it is not worth creating an article.
But you can decide whether to create an article. : )
