### ISSUE TITLE
generate proxy error : "Backend module "app" does not exist in API definition."

### ISSUE THREAD

**Issue by YoussefSalameh** [abpframework/abp#5725]
@hikalkan @mehmet-erim @maliming 

Hello Everyone, 

I'm using abp framework 3.1.2 with  angular 10  as UI .
I'm trying to use abp generate-proxy instead of ng swagger gen but  when generating an error occurred :

Backend module "app" does not exist in API definition.

Noting that I'm using versioning  so calls will be like ( /api/v1/getCars ) and I've set my environment  like below 
{
      url: 'https://localhost:44391',
      rootNamespace: "MyCompanyName.MyProjectName",
}

Please can you specify what do you mean in this error  and how can I solve it.

Best Regards,

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by YoussefSalameh** [comment]
Hi, 
I found that  api/abp/api-definition call will retrieve all modules that I need to use in abp generate-proxy -m  module name.
