### ISSUE TITLE
Allow streaming from application services

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#5727]
reported at https://support.abp.io/QA/Questions/463/Blob-storage-support-for-large-files-with-no-overhead

**Comment by alexandru-bagu** [comment]
just made this pull request to with support for blob storage #5733 
I am not sure about naming conventions so I am fine with whatever names you decide to use
additionally there's an example of usage here https://github.com/alexandru-bagu/abp-remote-stream-test
