### ISSUE TITLE
In The Future of IdentityServer will be payed software 

### ISSUE THREAD

**Issue by badre429** [abpframework/abp#5735]
[The Future of IdentityServer](https://github.com/dotnet/aspnetcore/issues/26489)
since IdentityServer most likely will become payed software at the end of 2021 abp.io must look for other alternative

**Comment by hikalkan** [comment]
We are closely following the happenings, no worry :)

**Comment by fileman** [comment]
This version can be enough? 
https://blog.duendesoftware.com/posts/20201210_community_edition/

**Comment by maliming** [comment]
I think the community edition is enough.

**Comment by realLiangshiwei** [comment]
Move to https://github.com/abpframework/abp/issues/7221
