### ISSUE TITLE
Remove some duplicate claims

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#5748]
We added some duplicate claims, should remove.

![image](https://user-images.githubusercontent.com/16813853/95541835-ea3f8b00-0a26-11eb-856b-7ba27f53a5f3.png)

**Comment by maliming** [comment]
IdentityServer4 behavior.
https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L27
https://github.com/IdentityServer/IdentityServer4/blob/main/src/AspNetIdentity/src/UserClaimsFactory.cs#L26
