### ISSUE TITLE
Document how to run microservice template

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#575]

**Comment by brunobertechini** [comment]
@hikalkan please check #875 . I intend to update the documentation on how to run the template using 03 different scenarios:

1. Outside development environment: by using command line docker-compose up
2. Inside development environment: by using all requirements (redis, elastic etc) in the developer's machine and running manual in VisualStudio
3. Inside development environment: by using VisualStudio Docker Tools with the change in #875 .

Perhaps I can remove the documentation task from #875 and use this issue instead.

**Comment by hikalkan** [comment]
Already done: https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo
