### ISSUE TITLE
FormTenantResolveContributor causes Ocelot gateway routing and forwarding failure

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#5758]
ocelot use ABP framwork, enable multi-tenancy,  the form content cannot be forwarded
 
Repeat the implementation steps:
https://github.com/abpframework/abp-samples/tree/master/MicroserviceDemo 
Update the version of the gateway used by the Demo to the latest ABP version,  
 

Create downstream service controller: 
```
[HttpPost]
public Task CreateAsync(IFormFile file)
{
  // The file variable always is null.
  return _invoiceAppService.CreateAsync(file);
}
```

The problem was caused by the addition of the following function:
 ```
FormTenantResolveContributor.cs

protected override string GetTenantIdOrNameFromHttpContextOrNull(ITenantResolveContext context, HttpContext httpContext)
{
  if (httpContext.Request == null || !httpContext.Request.HasFormContentType || !httpContext.Request.Form.Any())
  {
    return null;
  }
  return httpContext.Request.Form[context.GetAbpAspNetCoreMultiTenancyOptions().TenantKey];
}
```

✔Temporary solution：
If your gateway does not have multi-tenancy requirements, cancel the `app.UseMultiTenancy();`

If your gateway has multi-tenancy requirements, you can only rolly back the ABP version.

😉 Good luck with that.

**Comment by realLiangshiwei** [comment]
Thanks for your report. I will check it out.

**Comment by realLiangshiwei** [comment]
I think it has nothing to do with ABP. I reproduced this problem using the native ASP.NET Core API project. so I think this is Ocelot’s problem

![image](https://user-images.githubusercontent.com/16813853/95843093-e2ab1980-0d79-11eb-907f-5d930696dd6f.png)

**Comment by Loongle** [comment]
@realLiangshiwei  i cancel the `app.UseMultiTenancy();`  , it is working. but i enable `app.UseMultiTenancy();`, it is not working. maybe your post form-data have issue

**Comment by Loongle** [comment]
you can upgrade gateway of  `abp-sample/MicroserviceDemo` project, and then run your custom api project

**Comment by xyfy** [comment]
@Loongle I got similar error,and I change the position

![image](https://user-images.githubusercontent.com/7838147/116202203-e843dc00-a76c-11eb-8825-bb9ff847e830.png)

**Comment by xyfy** [comment]
@Loongle 
I got similar error ,and I changed the position ,it works !

![image](https://user-images.githubusercontent.com/7838147/116203280-1b3a9f80-a76e-11eb-8d9a-f4342d2b213d.png)

**Comment by Loongle** [comment]
maybe. but now i remove `app.UseMultiTenancy`, it works. i don't think gateway need to use multitenancy @Y2zz
