### ISSUE TITLE
Angular error when calling: abp generate-proxy command "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by eng-mohammed-emam** [abpframework/abp#5762]
Hello,
I'm facing an error when using the command: abp generate-proxy

I'm sure that no recursion in my Dto classes.
In addition, how can I fix the warning: Couldn't determinate version of "@abp/ng.schematics" package.

* ABP Framework version: Version 3.2.1 (Stable).
* User Interface: Angular.
* Exception message: Maximum call stack size exceeded.
* Steps needed to **reproduce** the problem: Executing the command `abp generate-proxy`

[WRN] Couldn't determinate version of "@abp/ng.schematics" package.
[Error] Maximum call stack size exceeded

**Comment by maliming** [comment]
hi @eng-mohammed-emam 

Please try to upgrade abp cli to the latest.

```ps
dotnet tool install --global Volo.Abp.Cli --version 3.2.1
```

https://www.nuget.org/packages/Volo.Abp.Cli/

**Comment by eng-mohammed-emam** [comment]
Hello @maliming,

I'm using the latest version already of ABP 3.2.1.

**Comment by goodyear-incaricotech** [comment]
Hi, i've the same issue. The problem is related to recursive Dtos. Like in this sample.

```
public class FatherDto
    {
        public int Id { get; set; }
        public Collection<ChildDto> Children { get; set; }
    }

    public class ChildDto
    {
        public int Id { get; set; }
        public FatherDto Father {get;set;}
    }

    public class FatherAppService : ApplicationService
    {
        public Task<FatherDto> GetAsync() =>
            null;
    }

    public class ChildAppService : ApplicationService
    {
        public Task<ChildDto> GetAsync() =>
            null;
    }
```

If you try to generate proxy with this services it returns "Maximum call stack size exceeded".
This error doesn't show if you try to remove the recursion on line 4 OR 10.
Can you fix it please?

**Comment by maliming** [comment]
@armanozak What do you think?

**Comment by armanozak** [comment]
Recursion is the only reason I can think of, but we do have a termination condition. Apparently, this escapes it. I need to check what the JSON looks like before I can tell.

**Comment by desmored** [comment]
It could be related to System.Text.Json serializer

**Comment by eng-mohammed-emam** [comment]
@armanozak How you can check this? Send you the project?

**Comment by armanozak** [comment]
No @eng-mohammed-emam, we are planning to reproduce what @goodyear-incaricotech has shared.

**Comment by eng-mohammed-emam** [comment]
@desmored 
How can I set the tree level to 2 of Json serializer to avoid the nested tree?

**Comment by ebicoglu** [comment]
How about creating a new FatherDto to avoid the loop

**Comment by goodyear-incaricotech** [comment]
@ebicoglu duplicate ChildDto one for Father and another for ChildService should resolve it, but i have duplicate the Dto(s) and my hierarchy have 5 levels, and then objects will be different and eventually they'll not match.
I think that recursion in programming should not be a problem.

Maybe if you use newtonsoft serializer with [this setting](https://www.newtonsoft.com/json/help/html/ReferenceLoopHandlingIgnore.htm) can be solved?

**Comment by ebicoglu** [comment]
yeah, I know how to prevent the loop. we are on it!

https://www.newtonsoft.com/json/help/html/ReferenceLoopHandlingIgnore.htm
