### ISSUE TITLE
Email Settings - Password Encryption

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#5769]
`Abp.Mailing.Smtp.Password` must be an encrypted value. How can we define it encrypted in the appsettings.json file?

**Comment by maliming** [comment]
hi

> If you use the appsettings.json to store the password, you should manually inject the ISettingEncryptionService and use its Encrypt method to obtain an encrypted value. This can be done by creating a simple code in your application. Then you can delete the code. As better, you can create a UI in your application to configure the email settings. In this case, you can directly use the ISettingManager without worrying the encryption.

https://docs.abp.io/en/abp/latest/Emailing#encrypt-the-smtp-password

**Comment by LeiYangGH** [comment]
> hi
> 
> > If you use the appsettings.json to store the password, you should manually inject the ISettingEncryptionService and use its Encrypt method to obtain an encrypted value. This can be done by creating a simple code in your application. Then you can delete the code. As better, you can create a UI in your application to configure the email settings. In this case, you can directly use the ISettingManager without worrying the encryption.
> 
> https://docs.abp.io/en/abp/latest/Emailing#encrypt-the-smtp-password

I got this error:
Autofac.Core.Activators.Reflection.NoConstructorsFoundException: No accessible constructors were found for the type 'Volo.Abp.Settings.ISettingEncryptionService'.

**Comment by hikalkan** [comment]
With the version 4.3, there will be an email settings page on the UI.
