### ISSUE TITLE
Identity server Login page is very slow

### ISSUE THREAD

**Issue by mohammed-hussein** [abpframework/abp#5773]
I'm using an Identity server with Abp but when I try to login using the below link it takes a lot of time 'more than 10 mins' to open the login page

https://localhost:40952/account/login

I used this cli to generate a new project to can reproduce this issue
`abp new Acme.BookStore -u angular --separate-identity-server
`

ABP Framework version: 3.0.2

**Comment by maliming** [comment]
hi

Please check your redis configuration.
https://github.com/abpframework/abp/issues/2764

**Comment by leonkosak** [comment]
I can confirm that this is basically always the case.

**Comment by mohammed-hussein** [comment]
it's working now but when I enable windows authentication on the identity server, it's redirecting to an external provide URL and prompt windows login but never generate asp.Identity cookie and authentication fail,

this my configuration I did on BookStoreIdentityServerModule.cs
` Configure<IISServerOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });`

enable Windows authentication in launchSettings.json
`"windowsAuthentication": true,
"anonymousAuthentication": true,`
