### ISSUE TITLE
How to add newly added property in User Entity to corresponding Dto in abp

### ISSUE THREAD

**Issue by QaziTanzeel** [abpframework/abp#5776]
I am extending the User Entity of Abp Framework, My project name is **Testing**. I have added and mapped the new field in the file **TestingEfCoreEntityExtensionMappings** using the following code.

```
ObjectExtensionManager.Instance.MapEfCoreProperty<IdentityUser, UserType>(
                "UserType",
                    (entityBuilder, propertyBuilder) =>
                    {
                        propertyBuilder.IsRequired();
                        propertyBuilder.HasDefaultValue(UserType.EndUser);
                    }
                );
```

This is the enum of the User Type
```
 public enum UserType
    {
        ServiceUser,
        StoreUser,
        EndUser 
    }
```
The field has been added to database

![image](https://user-images.githubusercontent.com/9509984/95807607-0d6a8300-0d24-11eb-9c54-739a8aa0ecfd.png)

Now I am unable to add the newly added property to the corresponding Dtos, I tried the following code but it doesn't work.

![image](https://user-images.githubusercontent.com/9509984/95807852-9aadd780-0d24-11eb-9f1b-dafee00e38c7.png)

After doing all the above stuff, when I checked in swagger, I didn't find the property in IdentityUserDto. Following is swagger dto screenshot.
![image](https://user-images.githubusercontent.com/9509984/95808410-d1d0b880-0d25-11eb-8739-d51b0361937e.png)

Kindly guide

I am using 
Abp 3.2.1
Angular front end

**Comment by realLiangshiwei** [comment]
It is in the `extraProperties` property

**Comment by QaziTanzeel** [comment]
> It is in the `extraProperties` property

If you see the screenshot from the swagger, you will see that I have expanded that property too, but there is nothing in there. it is empty.
@realLiangshiwei  Kindly open the ticket again, I need some more info regarding this.

**Comment by maliming** [comment]
@QaziTanzeel 

https://community.abp.io/articles/how-to-add-custom-property-to-the-user-entity-6ggxiddr

**Comment by realLiangshiwei** [comment]
Please try to get the API result.
The `extraProperties` is a  `dictionary`, so you can't see the property definition. This is expected

**Comment by QaziTanzeel** [comment]
> @QaziTanzeel
> 
> https://community.abp.io/articles/how-to-add-custom-property-to-the-user-entity-6ggxiddr

I have already read this article, the issue is I am not seeing any corresponding property for the UserType in the Dto.

**Comment by QaziTanzeel** [comment]
> Please try to get the API result.
> The `extraProperties` is a `dictionary`, so you can't see the property definition. This is expected

Thank you @realLiangshiwei , I will check and update
