### ISSUE TITLE
How to disable "HTTPS only" on HttpApi.Host?

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#5783]
An Android third-party client must call the API of the HttpApi.Host project of my ABP 3.2.1 Blazor solution. In development environment, I have no choice but using HTTP, not HTTPS, because Android app fails to call my HttpApi.Host API if a self-signed certificate is involved.

I remember a time, with ASP.NET Boilerplate, where http://localhost:500X and https://localhost:500X where both served by Kestrel at run. 

I see also `app.UseHttpsRedirection();` explicitly in `templates\module\aspnet-core\host\MyCompanyName.MyProjectName.HttpApi.Host\MyProjectNameHttpApiHostModule.cs` but not in `templates\app\aspnet-core\src\MyCompanyName.MyProjectName.HttpApi.Host\MyProjectNameHttpApiHostModule.cs`. I don't understand why.

How can I run my HttpApi.Host project in HTTP on my dev env, but in HTTPS in production?

**Comment by Stirda** [comment]
Ok. I finally figured it out myself. 

From https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1#new-behavior :
> In ASP.NET Core 3.0, the IIS HTTPS scenario was enhanced. With the enhancement, an app could discover the server's HTTPS ports and make UseHttpsRedirection work by default.

Then I made the following changes:
  - Set `options.RequireHttpsMetadata` to `!context.Services.GetHostingEnvironment().IsDevelopment()` (I know that this setting will be settable in appsettings.json soon).
  - Edited `https://` into `http://` in `src\MyCompanyName.MyProjectName.HttpApi.Host\appsettings.json`
  - Edited `https://` into `http://` in `src\MyCompanyName.MyProjectName.HttpApi.Host\Properties\launchSettings.json`
  - Edited value of `sslPort` into `0` in `src\MyCompanyName.MyProjectName.HttpApi.Host\Properties\launchSettings.json` (not working if line removed - I assume this set to default non-zero value) 

Nothing else to do. ASP.NET Core 3 understood what I want now: full ugly HTTP on localhost. Don't be afraid: I plan to work with HTTPS in production. TLS certificate is on the way...

BTW I suppose that `UseHttpsRedirection` calls are now useless in some `templates\module\**\*Module.cs`?

**Comment by ghost** [comment]
All I did was modify src\MyCompanyName.MyProjectName.HttpApi.Host\Properties\launchSettings.json file ("MyProject.HttpApi.Host" block in json file) and it worked for me:
before:
   "applicationUrl": "http://localhost:44313",
after:
   "applicationUrl": "http://localhost:44313",
   "sslPort": 0
