### ISSUE TITLE
Tenant roles base on Host roles

### ISSUE THREAD

**Issue by khinhvuphiduong** [abpframework/abp#5787]
Dear all,
I want to create some role from host side then assign to tenant admin user when I create a new tenant, then tenant can create theirs role base on assigned roles. My solution is **when assign role for tenant admin user, I can create a same role name then seeder permission (of host's role is assigned to new tenant) to this role, but it's so difficult when I update role from host side, and also update tenant admin role**. 

Thanks and Best regard!

**Comment by maliming** [comment]
hi

You can check the change event of the entity.
https://docs.abp.io/en/abp/latest/Local-Event-Bus#pre-built-events

**Comment by khinhvuphiduong** [comment]
> hi
> 
> You can check the change event of the entity.
> https://docs.abp.io/en/abp/latest/Local-Event-Bus#pre-built-events

Thank for your reply, Cache, Local Event  Bus and Distributed Event Bus are fantastic built in  function, thanks to ABP Team. But my approach above is not flexible and difficult to modified late. I solved by  use Role Extra Properties to store host roles  and get roles permission by recursively.

Best regard!
