### ISSUE TITLE
Microservices demo using MySQL Server not working

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#5793]
We are trying to change the Microservices sample to use MySQL instead of SQL Server but are having a few problems. The migrations are not running through Docker and the Auth login page is not displaying anything.

The steps we used to change the code to use MySQL were:

- Replace all occurrences of UseSqlServer with UseMySql
- Replace all occurrences of SqlServerValueGenerationStrategy with MySqlValueGenerationStrategy
- Uninstall the Volo.Abp.EntityFrameworkCore.SqlServer NuGet package from each project
- Install the Volo.Abp.EntityFrameworkCore.MySqlServer NuGet package into each project 
- Replace all instances of AbpEntityFrameworkCoreSqlServerModule with  AbpEntityFrameworkCoreMySQLModule
- Replace all instances of Volo.Abp.EntityFrameworkCore.SqlServer with Volo.Abp.EntityFrameworkCore.MySQL
- Update connection strings
- Updated docker-compose yml files to use MySql 5.7 image
- deleted Migration folders and ran add-migrate "initial"

Any help would be much appreciated.

**Comment by charleszh-dev** [comment]
In the last step, you added migration, but did you update the database?

**Comment by DonVliet** [comment]
@realZhangChi it was my fault I didn't update all MySQL code in modules
