### ISSUE TITLE
EnvironmentVariablesPrefix option has no effect in Startup.ConfigureServices

### ISSUE THREAD

**Issue by RayMMond** [abpframework/abp#5794]
* **ABP Framework version**: 3.2.1.
* Steps needed to **reproduce** the problem: 
In IdentityServer project's startup.cs file, add following lines:

```
services.AddApplication<XXXIdentityServerModule>(options =>
{
    options.Configuration.EnvironmentVariablesPrefix = "Some_Prefix";
});
```

I managed to locate following lines in abp application creation process:

https://github.com/abpframework/abp/blob/81ce88ee203ae5d9b03842206d3d57caa1fef626/framework/src/Volo.Abp.Core/Volo/Abp/Internal/InternalServiceCollectionExtensions.cs#L26-L33

Should we check whether IConfiguration is added into service collection before replace it?

**Comment by maliming** [comment]
hi
I will check it.

**Comment by RayMMond** [comment]
For anyone who had the same issue, I found a way:
```
            Host.CreateDefaultBuilder(args)                
                // in abp 3.2.1 add prefix in startup.cs has no effect
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddEnvironmentVariables("some_prefix");
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseAutofac()
                .UseSerilog();
```

**Comment by maliming** [comment]
hi @RayMMond 

As you can see, the `Configuration` of `AbpApplicationCreationOptions` is only applicable when `IConfiguration` is not registered in DI.

Use the `ConfigureAppConfiguration` method to change the configuration of asp net core .

**Comment by RayMMond** [comment]
Thanks for your reply @maliming .
Maybe we should add some docs or xml comments about it? 
Because whether `IConfiguration` is registered in DI is not that obvious for developers.

**Comment by maliming** [comment]
I will add some comments on the property.
