### ISSUE TITLE
MicroserviceDemo, get "Optimistic concurrency failure, object has been modified" error when edit userinfo

### ISSUE THREAD

**Issue by DingL0312** [abpframework/abp#5802]
postman tested

http://localhost:44315/api/identity/users/84a2d0b3-94ab-1213-c29b-39f8372d73f8

body: `{
    "userName": "admin2",
    "name": "jack",
    "surname": null,
    "email": "admin2@abp.io",
    "phoneNumber": null,
    "lockoutEnabled": true,
    "twoFactorEnabled": false,
    "id": "84a2d0b3-94ab-1213-c29b-39f8372d73f8"
}`

status: 403Forbidden

error:`{
    "error": {
        "code": "Identity.ConcurrencyFailure",
        "message": "Optimistic concurrency failure, object has been modified.",
        "details": null,
        "validationErrors": null
    }
}`

`Volo.Abp.Identity.AbpIdentityResultException: Optimistic concurrency failure, object has been modified.
   at Microsoft.AspNetCore.Identity.AbpIdentityResultExtensions.CheckErrors(IdentityResult identityResult)
   at Volo.Abp.Identity.IdentityUserAppService.UpdateAsync(Guid id, IdentityUserUpdateDto input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()`

**Comment by begandroide** [comment]
@DingL0312 hi! how do you solved this issue? I'm facing the same issue in PUT request

**Comment by jifeilong9** [comment]
> @DingL0312你好！你是怎么解决这个问题的？我在PUT请求中也遇到了同样的问题

hi! how do you solved this issue? I'm facing the same issue in PUT request

**Comment by jifeilong9** [comment]
> @begandroide  hi! how do you solved this issue? I'm facing the same issue in PUT request

**Comment by begandroide** [comment]
@jifeilong9 hi! My issue was that in the GET method of the user identity, I made some changes over the entity, so dB thought that someone was modified the registry, so the concurrencyTimestamp changes and the put method has concurrency failure. So, check your get method and make sure that you are not modifying the entity.

Hope's that help you, regards.

**Comment by jifeilong9** [comment]
Thank you. It's settled
