### ISSUE TITLE
Add XSRF-TOKEN to Swagger UI Requests

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#5803]
Related https://github.com/abpframework/abp/pull/5728

We have added Auto Validate AntiForgery Token for HTTP API Requests, We also need to add XSRF-TOKEN to Swagger UI Requests. Like we did in aspnetboilerplate

**Comment by hikalkan** [comment]
Closed by https://github.com/abpframework/abp/pull/5864

**Comment by xyfy** [comment]
It need some config for api host Project ，Like `gateway` or `servicehost` in `microservicesample` .
in default ,it cannot load js  `/libs/abp/core/abp.js` @realLiangshiwei

**Comment by realLiangshiwei** [comment]
@xyfy See https://github.com/abpframework/abp/pull/6124

**Comment by xyfy** [comment]
> @xyfy See #6124

does it mean after the #6124   the module  do not need `/libs/abp/core/abp.js` anymore?

It will release in v4.0?
