### ISSUE TITLE
connect/token 500 error.

### ISSUE THREAD

**Issue by murongqingsi** [abpframework/abp#5804]
connect/token  这个接口我们创建项目也没有看到这个接口的源码，改动不了
麻烦大神能给指点下源码位置，我们去查看下
_Originally posted by @murongqingsi in https://github.com/abpframework/abp/issue_comments/708999310_

**Comment by maliming** [comment]
`connect/token` belong https://github.com/IdentityServer/IdentityServer4/

Please **write in English**.
