### ISSUE TITLE
Why cant't synchronized AbpUsers table 

### ISSUE THREAD

**Issue by buxueke** [abpframework/abp#5805]
in my custom module,I create  "taskuser" table ,I want synchronized AbpUsers table,but UserLookupService.FindByIdAsync() is always null when the abpuser update
this is my code(I copy the blogUser):

public class TaskUserSynchronizer: IDistributedEventHandler<EntityUpdatedEto<UserEto>>,
        ITransientDependency
    {
        protected ITaskUserRepository UserRepository { get; }
        protected ITaskUserLookupService UserLookupService { get; }

        protected ICurrentTenant _currentTenant;

        public TaskUserSynchronizer(
            ITaskUserRepository userRepository,
            ITaskUserLookupService userLookupService,
            ICurrentTenant currentTenant)
        {
            UserRepository = userRepository;
            UserLookupService = userLookupService;
            _currentTenant = currentTenant;
        }

        public async Task HandleEventAsync(EntityUpdatedEto<UserEto> eventData)
        {
            using (_currentTenant.Change(eventData.Entity.TenantId))
            {
                var user = await UserRepository.FindAsync(eventData.Entity.Id);
                if (user == null)
                {
                    user = await UserLookupService.FindByIdAsync(eventData.Entity.Id);
                    if (user == null)
                    {
                        return;
                    }
                }

                if (user.Update(eventData.Entity))
                {
                    await UserRepository.UpdateAsync(user);
                }
            }
           
        }

public class TaskUserLookupService : UserLookupService<TaskUser, ITaskUserRepository>, ITaskUserLookupService
    {
        public TaskUserLookupService(
          ITaskUserRepository userRepository,
          IUnitOfWorkManager unitOfWorkManager)
          : base(
              userRepository,
              unitOfWorkManager)
        {
        }

        protected override TaskUser CreateUser(IUserData externalUser)
        {
            return new TaskUser(externalUser);
        }
    }
Volo.Abp.Users UserLookupService:
 public async Task<TUser> FindByIdAsync(Guid id, CancellationToken cancellationToken = default)
        {
            var localUser = await _userRepository.FindAsync(id, cancellationToken: cancellationToken);

            if (ExternalUserLookupServiceProvider == null)
            {
                return localUser;
            }

            if (SkipExternalLookupIfLocalUserExists && localUser != null)
            {
                return localUser;
            }

            IUserData externalUser;

            try
            {
                externalUser = await ExternalUserLookupServiceProvider.FindByIdAsync(id, cancellationToken);
                if (externalUser == null)
                {
                    if (localUser != null)
                    {
                        //TODO: Instead of deleting, should be make it inactive or something like that?
                        await WithNewUowAsync(() => _userRepository.DeleteAsync(localUser, cancellationToken: cancellationToken));
                    }

                    return null;
                }
            }
            catch (Exception ex)
            {
                Logger.LogException(ex);
                return localUser;
            }

            if (localUser == null)
            {
                await WithNewUowAsync(() => _userRepository.InsertAsync(CreateUser(externalUser), cancellationToken: cancellationToken));
                return await _userRepository.FindAsync(id, cancellationToken: cancellationToken);
            }

            if (localUser is IUpdateUserData && ((IUpdateUserData)localUser).Update(externalUser))
            {
                await WithNewUowAsync(() => _userRepository.UpdateAsync(localUser, cancellationToken: cancellationToken));
            }
            else
            {
                return localUser;
            }

            return await _userRepository.FindAsync(id, cancellationToken: cancellationToken);
        }

I'm not sure  when the the taskuser(or bloguser) was created，It's in  UserLookupService.FindByIdAsync() ？
but when I'm debugging user = await UserLookupService.FindByIdAsync(eventData.Entity.Id) is always null

**Comment by zsyy94** [comment]
Hello, I encountered the same problem, how did you deal with it @
