### ISSUE TITLE
How to handle components that do not match .NET 5.0

### ISSUE THREAD

**Issue by geffzhang** [abpframework/abp#5807]
4.0 has been upgraded to 5.0 RC2, This is a good attempt, but one problem is that some components are not ready for .NET 5, such as Volo.Abp.EntityFrameworkCore.Oracle, which is not ready and 5.0 is a good fit, how to handle this situation is better, can support both .NET Core 3.1 and 5.0, similar to Microsoft's https://github.com/microsoft/reverse-proxy,  After all, .NET Core 3.1 is the LTS version.

**Comment by maliming** [comment]
We use NET Standard as much as possible. We cannot solve the Oracle problem.
