### ISSUE TITLE
[MongoDb&Uow] Standalone servers do not support transactions.

### ISSUE THREAD

**Issue by sheng-jie** [abpframework/abp#5809]
ABP Framework version: 3.2.1.

MongoDB cannot support transaction in standalone server. So if only have one standalone server ready in development environment, we will get an error "Standalone servers do not support transactions" when transaction enabled in Uow.  

You know, developers perhaps not have a MongoDB cluster with multiple server in local, so it's not friendly with developer. I think it will be good to add one option for developer to specify if current cluster support transaction or not when register MongoDB context. Then update the `UnitOfWorkMongoDbContextProvider` to decide whether create a dbcontext with transaction according to the option. Just like below:

```
private TMongoDbContext CreateDbContext(IUnitOfWork unitOfWork, MongoUrl mongoUrl, string databaseName)
{
    var client = new MongoClient(mongoUrl);
    var database = client.GetDatabase(databaseName);
    if (mongoDbOptions.IsTransactionEnabled
        && unitOfWork.Options.IsTransactional.HasValue
        && unitOfWork.Options.IsTransactional.Value)
    {
        return CreateDbContextWithTransaction(unitOfWork, mongoUrl, client, database);
    }
```

Thanks.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/5468

We disable MongoDB transactions by default, if anyone needs, they can be enabled manually

**Comment by sheng-jie** [comment]
OK, I got it.

**Comment by chenqilscy** [comment]
> OK, I got it.

怎么写的？

**Comment by Mallankur** [comment]
hii i have facing with same issue "Standalone server do not support transaction" . i don't know how fix it plese anyone know then let me know
