### ISSUE TITLE
Reconsider & test performance of using SplitQuery()

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5810]
Here, the usages: https://github.com/abpframework/abp/search?q=AsSplitQuery
I think we should not use it by default.

**Comment by maliming** [comment]
Test program:
https://github.com/abpframework/abp/commit/ea99a020ffc00d6dbbe202ee07970b91d1aebba4

50 users, every user has 10 roles,  10 tokens,  10 claims, 10 logins.
```
AsSplitQuery: 30ms avg 
AsSingleQuery: 6000ms avg
```

![image](https://user-images.githubusercontent.com/6908465/96669827-9c187900-1390-11eb-8ac8-6c24729f84cf.png)

**Comment by hikalkan** [comment]
I am closing since the split query seems faster as opposite to my feelings :)
