### ISSUE TITLE
Use authorization as a standalone addition to ASP.NET Core project

### ISSUE THREAD

**Issue by szilardd** [abpframework/abp#5812]
I like how the authentication is implemented and that it extends on ASP.NET Core Identity.

I have an existing project and would like to integrate only the custom `Authorize` attribute and permission system from Abp as described [here](https://docs.abp.io/en/abp/latest/Authorization) without having to use the entire Abp framework.

I see that there is a separate NuGet package related only to authentication [Volo.Abp.Authorization](https://abp.io/package-detail/Volo.Abp.Authorization) 

Is this possible somehow?
Thanks

**Comment by realLiangshiwei** [comment]
You can minimize the use of ABP framework: https://docs.abp.io/en/abp/latest/Getting-Started-AspNetCore-Application

**Comment by szilardd** [comment]
Thanks, will check it out.

I can also probably implement permissions similarly to Abp using this approach

http://alexandrubucur.com/blog/2019/dynamic-policy-claims-in-asp.net-core-using-jwt-tokens-and-role-claims/
