### ISSUE TITLE
 Identityclients user is the current user, not the configuration?

### ISSUE THREAD

**Issue by qiang999** [abpframework/abp#5816]
hello,

I want the identityclients user to get the current user, not through configuration. Do you have a solution？

Thanks!

**Comment by maliming** [comment]
Can't understand.

**Comment by qiang999** [comment]
I use HttpClient to Remote Service.
When I access an api ,and this api needs to access another remote service. At this time, can I use the current token to access, instead of configuring IdentityClients in appsettings.json.
