### ISSUE TITLE
[Angular] abp-ng.core.js:1305 Cannot find the en locale file. 

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#5817]
**Angular & Non-Seperated Identity Server & EF Core - preview 3.3.0**

`abp new Angular.NonSeperatedEfCore -t app -u angular --mobile none  --database-provider ef -csf --preview`

The browser console get an error when change language.

**app pro template project does not have this error**

![image](https://user-images.githubusercontent.com/6908465/96204866-ed42fa00-0f97-11eb-82c7-76f15818f3a6.png)

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/96951184-8c2e9f80-151e-11eb-8f00-88b0d26303a4.png)

![image](https://user-images.githubusercontent.com/6908465/96951202-918bea00-151e-11eb-9df4-86c5c7f350f8.png)

**Comment by bnymncoskuner** [comment]
Merged into rel-3.3
