### ISSUE TITLE
Bazor UI: The current page number should be active

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#5818]
![image](https://user-images.githubusercontent.com/16813853/96206868-6d6b5e80-0f9c-11eb-86ee-1c3d29435542.png)

Should be 

![image](https://user-images.githubusercontent.com/16813853/96206827-56c50780-0f9c-11eb-9461-49eccbcd05c6.png)

Same issue with pro template

**Comment by stsrki** [comment]
Tested and it's working as expected. Active class is applied properly, and disabled class is applied because there is no need to be able to click on the same page item if it's already active.
