### ISSUE TITLE
in blog module , When will the abpuser  be synchronized to bloguser

### ISSUE THREAD

**Issue by buxueke** [abpframework/abp#5821]
just when the abpuser  is updated?

**Comment by buxueke** [comment]
when  the bloguser create

**Comment by maliming** [comment]
The `BlogUserLookupService` will create the `bloguser` entity.

There is no documentation about `UserLookupService` yet, you can check the source code for details

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUserLookupService.cs#L6

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUserLookupService.cs#L20

https://github.com/abpframework/abp/blob/de4c1b26c558c77580f74bee660491f9ebd71143/modules/users/src/Volo.Abp.Users.Domain/Volo/Abp/Users/UserLookupService.cs#L13

**Comment by buxueke** [comment]
how to use `HttpClientExternalUserLookupServiceProvider`
