### ISSUE TITLE
Adding new layouts to Angular application

### ISSUE THREAD

**Issue by mtozlu** [abpframework/abp#5832]
`DynamicLayoutComponent` of abp.ng.core package has hard coded map of three layouts.
https://github.com/abpframework/abp/blob/5b04ddfc0fcfef4cd763df3aa2e784d9b9e2ce75/npm/ng-packs/packages/core/src/lib/components/dynamic-layout.component.ts#L27-L32

Even though we can replace the component mapped to a specific layout, there may be need to add additonal layouts in complex applications with multiple areas. 

Please consider making layouts expandable.
For example;
```typescript
// configureLayouts factory in LayoutProvider
layouts.add(['admin', 'MyNameSpace.Layouts.AdminLayoutComponent'])

// route provider
routes.add([
{
  ...,
  name: 'Admin',
  layout: 'admin',
}]
```

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/UI/Angular/Component-Replacement#how-to-replace-a-layout

**Comment by mtozlu** [comment]
> Even though we can replace the component mapped to a specific layout, there may be need to add additonal layouts in complex applications with multiple areas.

Thanks, @realLiangshiwei. 
My issue is about adding new layouts.

**Comment by bnymncoskuner** [comment]
Hello @mtozlu 

Could you explain your use case a little further? What is it that you want to do but not be able to do with the current of the framework? A detailed example is much appreciated. It would help us understand the need better.

Thank you

**Comment by yinchang0626** [comment]
@bnymncoskuner 
In Route, layout property is enum type ,we can define just three kinds of layout,
If let it be a string or array,we can add other custom name of layouts by self,
 `DynamicLayoutComponent` will be more flexibility
```typescript
 export interface Route {
    children?: Route[];
    invisible?: boolean;
    layout?: eLayoutType//| string;
    name: string;
    order?: number;
    parentName?: string;
    path: string;
    requiredPolicy?: string;
    iconClass?: string;
  }
export const enum eLayoutType {
  account = 'account',
  application = 'application',
  empty = 'empty',
}
```

**Comment by mtozlu** [comment]
@bnymncoskuner 

Thanks, currently there are only three hardcoded layouts to choose from.
In more complex applications with many detailed usage scenarios, there may be need to add more layouts.
For example, i need three different layouts;
- AdminLayout; There will be a side menu, top menu and content area just like a generic admin layout.
- CustomerLayout; There will be a top menu and content area (just like current Angular UI template) for authenticated users.
- PublicLayout; No side menu or top menu with a generic landing page

Now i know, i can use "ApplicationLayout" and just show hide nav areas depending on the users role or authentication. However i want to use completely different html layouts and designs.
For example, current Angular UI template's ApplicationLayout uses `<div class="container"></div>` as the main content container. I want to use class `container` in some areas and `container-fluid` (bootstrap container classes) in some areas. So i need to have two different layouts. In this case i can't replace ApplicationLayout, AccountLayout or EmptyLayout because they are already being used by other areas.

**Comment by bnymncoskuner** [comment]
Hello,

We are evaluating this within our team and may implement a solution in the upcoming versions. 
Meanwhile, I've put together a sample project which I think is close enough to what you want to achieve. You can check it out [here](https://github.com/bnymncoskuner/abpframework-custom-layout-example) 

What I did was to create a custom layout (let's call it `admin-layout`) and use it within my components and I just chose `eLayoutType.empty`. 

https://github.com/bnymncoskuner/abpframework-custom-layout-example/blob/master/angular/src/app/users/users.component.html

https://github.com/bnymncoskuner/abpframework-custom-layout-example/blob/master/angular/src/app/layouts/admin/admin.component.html

Would something like this meet your need?

**Comment by mtozlu** [comment]
Yes, i implemented a similar solution with currently available structure. It is enough for now.
Thank you for your time and effort.

**Comment by bnymncoskuner** [comment]
Thank you for your input, I'll create another issue and put it into the backlog. Closing this for now.

**Comment by shershak** [comment]
Hi! I have a situation where I need to use `eLayoutType.application` when the root route has no parameter `'/'` and `eLayoutType.empty` when the root route has a parameter `'/:id'`.

How can I use these routes with different layouts? Maybe some example code?
Thanks
