### ISSUE TITLE
EF query filters not working with EF TPH inheritence

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#5840]
Abp v3.1.0

My application terminates with the following error:

> An error occurred during the initialize Volo.Abp.Modularity.OnPostApplicationInitializationModuleLifecycleContributor phase of the module MyProject.MyModule, MyProject.MyModule, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null: The filter expression 'Param_0 => ((Not(value(MyProject.EntityFrameworkCore.MyProjectDbContext).IsSoftDeleteFilterEnabled) OrElse Not(Property(Param_0, \"IsDeleted\"))) AndAlso (Not(value(MyProject.EntityFrameworkCore.MyProjectDbContext).IsMultiTenantFilterEnabled) OrElse (Convert(Property(Param_0, \"TenantId\"), Nullable`1) == value(MyProject.EntityFrameworkCore.MyProjectDbContext).CurrentTenantId)))' cannot be specified for entity type 'MyEntityOne'. 
A filter may only be applied to the root entity type in a hierarchy.. 
See the inner exception for details.

My base `AbstractEntity` class has the `abstract` modifier, and in my `ModelCreatingExtensions` class I have:
```csharp

builder.Entity<AbstractEntity>(b =>
{
    b.ToTable("MyEntity", MyProjectConsts.DbSchema);
    
    b.HasIndex(x => x.ActionId);
    b.ConfigureByConvention();
    
    // etc...
});

builder.Entity<MyEntityOne>(b =>
{
    b.HasBaseType<AbstractEntity>();
});

builder.Entity<MyEntityTwo>(b =>
{
    b.HasBaseType<AbstractEntity>();
});
```

It seems that Abp is applying filters to all entities and not checking for TPH inheritance? Is there a workaround/fix for this?

**Comment by maliming** [comment]
> Filters can only be defined for the root Entity Type of an inheritance hierarchy.

https://docs.microsoft.com/en-us/ef/core/querying/filters#limitations

**Comment by olicooper** [comment]
I have not applied any filters to any entities though. I only use `ConfigureByConvention()` on the base entity but it appears that abp is applying `IMultiTenant` and `IDeleted` filters to all entities in the hierarchy.

**Comment by olicooper** [comment]
For the benefit of other people in the future..
My problem was that I didn't want the base `AbstractEntity` to be included so I didn't add a DbSet for it and marked it as `abstract`. Unfortunately, EF inheritance is not the same as standard inheritance so you have to include the base entity as a DbSet for the `BaseType` property (see below) to be populated and query filters to be skipped.
https://github.com/abpframework/abp/blob/0160f6907df77207a0d938d4cdae4d5476c5bfd6/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L546-L557

I found a hack that works by removing the query filters applied by the code in the snippet above:

```csharp
builder.Entity<MyEntityOne>(b =>
{
    b.HasBaseType<AbstractEntity>();

    // Add this line below...
    b.HasQueryFilter(null);
});
```

I'd like a better solution because the only alternative is to add a DbSet for the base entity but this works okay too.

**Comment by devperson12345** [comment]
As a person from the future, I'd like to reopen this issue. Using ABP 9.x this is still an issue.

The hack to remove query filters is potentially dangerous for those relying on ABPs multitenancy. This is stripping out the multitenancy filter (as well as the soft delete filter) and might lead to PII data leaks.

It seems to me that the global query filters are being applied to the base entity and all derived entities by the ABP framework. Surely this is a bug?

**Comment by olicooper** [comment]
A long while ago I also wrote a whole project that went nowhere which might help you in some way https://github.com/abpframework/abp/issues/7690
