### ISSUE TITLE
Define abp.features API for the ASP.NET Core MVC / Razor Pages UI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5841]
Currently, we can use `abp.features.values["Identity.TwoFactor"]` to get the value of the feature `Identity.TwoFactor` in the client side. We need to following functions:

* `abp.features.isEnabled(name)` returns true if the feature value is `true` or `True`.
* `abp.features.get(name)` returns the feature's value or `null` if not defined.

Should be done in https://github.com/abpframework/abp/blob/dev/npm/packs/core/src/abp.js
It is similar to the `abp.setting` API

**Comment by hikalkan** [comment]
Please also document it here: https://github.com/abpframework/abp/blob/dev/docs/en/UI/AspNetCore/JavaScript-API/Features.md (in the DEV branch)

**Comment by realLiangshiwei** [comment]
* `abp.features.get(name)` If the feature does not exist, it will return `undefined`. same as `abp.setting.get(name)`.
