### ISSUE TITLE
Simplify namespaces for module & service templates.

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#585]
Hi,

![image](https://user-images.githubusercontent.com/4738140/48194721-ea016580-e3a1-11e8-8200-b8daf252b723.png)

So I want it named AccountingCart.ControlPlane as I will have AccountingCart.FrontEnd, AccountingCart.BackEnd etc.

However I end up with a structure that is per the image. Why do we repeat the AccountingCart.ControlPlane (ie the pink bits) again at the end of the folder structure. Seems redundant when I have a folder named AccountingCart.ControlPlane.Application (etc.) already.

Any chance of moving all the actual source up two levels when generating the template so that the source is actually found in `...\src\AccountingCart.ControlPlane.Application` instead of `...\src\AccountingCart.ControlPlane.Application\AccountingCart\ControlPlane`?

**Comment by hikalkan** [comment]
The idea is that:

We make the default namespace as empty. So, folder hierarchy exactly maps to the namespace for a class.
Why? Because we think that we may add classes to another namespace in the project.
Example: https://github.com/abpframework/abp/tree/master/modules/identity/src/Volo.Abp.Identity.Domain/Microsoft
Volo.Abp.Identity.Domain project adds classes to Microsoft.* namespaces in this way and it becomes consistent with the folder usage.
I know many projects will not need that, however we are trying to build modules with some strict rules.

**Comment by natiki** [comment]
Hmmmm.... I see what you are saying but it seems like overkill.... Consider the following:

![image](https://user-images.githubusercontent.com/4738140/48406090-c2d2db80-e787-11e8-9ed6-8d89ee9dac7c.png)

The **AccountingCart.ControlPlane.Application.cproj** has its namespace set as AccountingCart.ControlPlane.Application as that matches the folder it is in. Less nesting and you still achieve the same result namely that anything in the folder structure:

AccountingCart.ControlPlane.Application\Framework

will still end up in the namespace:

AccountingCart.ControlPlane.Application.Framework

It reduces the depth of things considerably and makes navigation on disk and in the solution so much easier without all the additional nesting:

![image](https://user-images.githubusercontent.com/4738140/48406405-776cfd00-e788-11e8-9c57-a3988a0cf2d4.png)

and if I wanted to add other modules I could still do so as:

src\Foo.Bar.Application with the namespace of Foo.Bar.Application

without compromising anything.

All done. ;-)

**Comment by natiki** [comment]
![image](https://user-images.githubusercontent.com/4738140/48406837-94ee9680-e789-11e8-9e7e-df147bbf613a.png)


And for what it is worth I would consider also adding all the boilerplate code that goes with each project into a Framework folder as all the code in most of the solutions is pretty standard and will comprise:

- At least a module class
- Probably an automapper profile class
- etc.

Keeps things nice and tidy and for people coming "fresh" to ABP they can see what code classes are needed for this "particular style of" project. For instance the Application has a settings class and a settings definition class while say the Domain.Shared has error codes and so on.

Furthermore putting all the Localization into each own folder also cleans things up. Means that what is left in each of the projects is ready to have code added as the user needs. So in my case I put all my services in a Services folder etc. and I am off and coding.

**Comment by hikalkan** [comment]
I am working on this. Will remove MyCompanyName and MyProjectName folders to keep it simpler. If we need to add a class to an external namespace, we make an exception for it.

**Comment by hikalkan** [comment]
Done.
