### ISSUE TITLE
AWS S3 client side encryption

### ISSUE THREAD

**Issue by c4jose** [abpframework/abp#5857]
Having a AWS S3 client-side encryption feature will be a great addition in ABP.

**Comment by realLiangshiwei** [comment]
Hi,

There is currently no such plan, you can implement it yourself via custom [`AwsBlobProvider`](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BlobStoring.Aws/Volo/Abp/BlobStoring/Aws/AwsBlobProvider.cs)

**Comment by realLiangshiwei** [comment]
`IBlobContainer `is abstract, you can override or replace services to do more features.
https://github.com/abpframework/abp/issues/4989#issuecomment-670577121
