### ISSUE TITLE
It seems got memory leak in scop inject

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#5858]
* Your **ABP Framework version**.
3.2.1
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

My progream is simple.
I use a middleware for websocket to process data.
when data come in, after websocket received full data i use the code flow:
`                    using(var scope = this.serviceScopeFactory.CreateScope())
                    {
                        var erpRepox = scope.ServiceProvider.GetRequiredService<IRepository<Domains.ERPBrand>>();
                        var rrrr = erpRepox.ToList();  //retrieve all the data from pgdatabase. about 40 rows
                    }`

but the memory grows up never stoped.

<img width="512" alt="02" src="https://user-images.githubusercontent.com/1214546/96440280-53e74280-123a-11eb-9cf3-f902125870ab.png">
<img width="1286" alt="03" src="https://user-images.githubusercontent.com/1214546/96440284-55186f80-123a-11eb-810d-e387d2a30860.png">
<img width="1286" alt="04" src="https://user-images.githubusercontent.com/1214546/96440288-56e23300-123a-11eb-8a23-d26c8aa8ffc2.png">
<img width="1286" alt="05" src="https://user-images.githubusercontent.com/1214546/96440366-72e5d480-123a-11eb-84d8-9c4f96619bf6.png">
<img width="1286" alt="07" src="https://user-images.githubusercontent.com/1214546/96440394-7da06980-123a-11eb-894c-6de385d5c737.png">

dotmemory file is here https://github.com/CAH-FlyChen/memoryleak
code is here 
https://github.com/CAH-FlyChen/memoryleakapp

need help 
thank you

**Comment by maliming** [comment]
> My progream is simple.

I don't think so, Can you make your example more simple and clean?

**Comment by CAH-FlyChen** [comment]
@maliming thanks for reply

demo has changed with new clean abp created by cli。
I modifyed：
1. change database to pg
2. add one domain erpbrand
![image](https://user-images.githubusercontent.com/1214546/96534478-64430000-12c2-11eb-9364-c80e48d20aa4.png)

3. add one application erpbrandapplication
![image](https://user-images.githubusercontent.com/1214546/96534496-6d33d180-12c2-11eb-9bac-066d57332ebb.png)

4. add one middle and one handler
![image](https://user-images.githubusercontent.com/1214546/96534522-7cb31a80-12c2-11eb-995a-5691e3cd4f06.png)

5. add one console project to send socket 
![image](https://user-images.githubusercontent.com/1214546/96534568-95233500-12c2-11eb-8545-9118e862b384.png)

debug step:
start multi project (host and testconsole)
when the host stared success，press anykey in testconsole begin to send data。
the host project can be run by default dbconnection in config（no need to change）

**Comment by maliming** [comment]
You can try use `context.RequestServices` instead of `IServiceScopeFactory` first.

**Comment by CAH-FlyChen** [comment]
@maliming still got problem
it looks the same in https://github.com/abpframework/abp/issues/3778

change code to
```cs
using (var scope = context.RequestServices.CreateScope())
{
	var erpRepox = scope.ServiceProvider.GetRequiredService<IRepository<Domains.ERPBrand>>();
	var rrrr = erpRepox.ToList();
}

if (total == 100)
{
	GC.Collect();
	total = 0;
	Console.WriteLine("************************************************");
}
else
{
	total += 1;
}
```
![image](https://user-images.githubusercontent.com/1214546/96544840-e7bc1b80-12d9-11eb-8319-2b4a362271df.png)
![image](https://user-images.githubusercontent.com/1214546/96544985-28b43000-12da-11eb-879f-5121265cfaab.png)

![image](https://user-images.githubusercontent.com/1214546/96545566-3918da80-12db-11eb-8ba0-a884e057c2b4.png)

**Comment by maliming** [comment]
You can test in plain asp net core + autofac, I think it has nothing to do with abp.

**Comment by CAH-FlyChen** [comment]
i chaged the demo to minimal
only one middlware inject repository or my ITransientDependency service.
test result: inject repository leaks,but my custom service is not.
if disable my middlewear, still got memory grows up slowly when log show "background select ".
![image](https://user-images.githubusercontent.com/1214546/96682386-54ebb180-13ab-11eb-85c4-77477b6d9cf1.png)

![image](https://user-images.githubusercontent.com/1214546/96680664-84e58580-13a8-11eb-9c78-6ab422771261.png)

**Comment by CAH-FlyChen** [comment]
when change the entity to use large memory,the memory graph can grows fast.
![image](https://user-images.githubusercontent.com/1214546/96688536-de06e680-13b3-11eb-89f5-5cf426e891e2.png)
when use myservice with the same large memory property,got graph can gc.
![image](https://user-images.githubusercontent.com/1214546/96689037-756c3980-13b4-11eb-8c50-6a4f25003117.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/5882
