### ISSUE TITLE
IHost not disposed in AbpAspNetCoreIntegratedTestBase

### ISSUE THREAD

**Issue by pwestern** [abpframework/abp#5860]
`IHost` is created in `AbpAspNetCoreIntegratedTestBase` constructor but is never disposed. When running tests with latest ReSharper test runner 2020.2.4 the following warning is displayed.

![image](https://user-images.githubusercontent.com/16342062/96462694-c39b0480-121d-11eb-952f-0e04c1ab3625.png)

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/96469002-4db78d00-125f-11eb-97eb-18a76a7f67cc.png)

**Comment by pwestern** [comment]
I'm aware of this feature - and it does fix the warning - but surely the underlying issue is that a process is not disposed correctly at the end of a test run?
