### ISSUE TITLE
Disposed DbContext in WorkerService project integrated in abp.io

### ISSUE THREAD

**Issue by nymeron** [abpframework/abp#5867]
Background: 
I'm using abp.io platform version 3.2.1
I'd like to integrate windows service project in abp platform using worker service template. 

I'm having issue accessing DbContext. Since it's disposed prior to use.
In Program I have configured CreateHostBuilder like that:

` public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseAutofac()
                .UseSerilog()
                .ConfigureAppConfiguration((context, config) =>
                { 
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddApplication<AlarmingServiceAppModule>();
                });`

The AlarmingServiceAppModule depends on AbpAutofacModule, ApplicationContractsModule, DomainModule and EntityFrameworkCoreModule. Also I have configured the connection string from appsettings.json file.
` var configuration = context.Services.GetConfiguration();
            Configure<AbpDbConnectionOptions>(options =>
            {
                options.ConnectionStrings.Default = configuration.GetConnectionString("Default"); 
            });
            context.Services.AddHostedService<AlarmingServiceAppStart>();   `

The AlarmingServiceAppStart is injecting IAbpApplicationWithExternalServiceProvider application,  IServiceProvider serviceProvider for application intiliaziation. 

And if I use  _application.ServiceProvider.GetRequiredService<>() to get a servcie from Domain and try to access one of the enttities it says the DbConext is disposed. 

I'm probably missing something, so any help is much appriciated!

**Comment by maliming** [comment]
Please answer the questions in the template.

**Comment by nymeron** [comment]
> Please answer the questions in the template.

I misclicked and saved before editing the whole response.

**Comment by maliming** [comment]
hi @nymeron 

Can you share a project to reproduce your problem? You can create a repo in Github.

**Comment by nymeron** [comment]
I created new abp application to which I added WorkerService project.

GitRepo: https://github.com/nymeron/abpWorkerServiceDemo.git

As you will see I managed to access the DB entity via EF core using IRepository interface. 

Question is, is this the right way to do a long-time running service? ANd how to go about runing multiple Background jobs that can independetly access the Domain level,

**Comment by maliming** [comment]
Do you still get any errors now?

**Comment by nymeron** [comment]
I don't ger errors and I managed to get data access. 

Now I'm just wondering if my approach is "the right way"? 
So is it ok to create scope and get required service every time I need data access? And, am I using the right abp components to achive this?

` var scope = _serviceScopeFactory.CreateScope();`
`var main = scope.ServiceProvider.GetRequiredService<MainProgram>();`
`await main.MainProcess();`

**Comment by nymeron** [comment]
I'm reopening this issue since I found out that: 

- calling GetListAsync() successfully returns list of entities
- calling AsyncExecuter.FirstOrDefaultAsync() throws exception: Cannot access a disposed object.

But if I call the same query from Host api project it works, calling it from Worker service throws this exception. 

I updated demo app in my gitrepo (see previous post for link). 
Check the 2 methods in Domain project in DemoService.cs that are call from Application service DemoAppService (everything works) and from WorkerService project Worker class (method GetListAsync works, but FirstOrDefaultAsync doesn't).

Any help is much appreciated!

**Comment by nymeron** [comment]
> Do you still get any errors now?

Could you please look at the issue? I'm kinda stuck :|

**Comment by maliming** [comment]
@nymeron 
You can try to make application services or domain services method **virtual** or create a unit of work manual.

`public virtual  async Task `

https://docs.abp.io/en/abp/latest/Unit-Of-Work

**Comment by nymeron** [comment]
> @nymeron
> You can try to make application services or domain services method **virtual** or create a unit of work manual.
> 
> `public virtual async Task `
> 
> https://docs.abp.io/en/abp/latest/Unit-Of-Work

Adding virtual and [UnitOfWork] attribute to the method made the difference. 

@maliming thank you very much for your help!
