### ISSUE TITLE
Blaozr UI: User menu dropdown is partially invisible in some resolutions

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5873]
I've justed worked on the header and now it is opening as shown below:

![image](https://user-images.githubusercontent.com/1210527/96631154-a0a44980-131e-11eb-9905-5853953f9fad.png)

I don't know if DropdownMenu has an option to open to the left side.

It is currently same for the Lepton theme:

![image](https://user-images.githubusercontent.com/1210527/96632745-d4806e80-1320-11eb-9df2-130c63608f59.png)

**Comment by stsrki** [comment]
Just set RightAligned like this `<BarDropdownMenu RightAligned="true">`

**Comment by hikalkan** [comment]
So, it seems we should use `Bar` component that means a re-write needed 😄 

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme/Themes/Basic/MainLayout.razor#L4
