### ISSUE TITLE
Why Volo.Abp.Ldap.ILdapManager only has one function?

### ISSUE THREAD

**Issue by ycc3000** [abpframework/abp#5880]
Why Volo.Abp.Ldap.ILdapManager only has one function?

* Your **ABP Framework version**.
3.1.2
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
MVC
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
1. add nuget package Volo.Abp.Ldap
2. inject Volo.Abp.Ldap.ILdapManager
3. it only has one function named 'Authenticate'
![1](https://user-images.githubusercontent.com/22928461/96699438-d863cd80-13c0-11eb-9ff0-a3d15da52c14.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/4984#issue-464385010
