### ISSUE TITLE
ABP Service Api 500 Internal Server Error

### ISSUE THREAD

**Issue by genceraziz** [abpframework/abp#5881]
Hello,

I published a .net core application I made with ABP to a remote server.

I am getting a 500 error while fetching a list from the service and I could not find the cause of the error. Can you please help.

`var _appService = bDH.services.producer;`
`ajax: abp.libs.datatables.createAjax(_appService.getProducers)`
`public PagedResultDto<ProducerDto> GetProducers(ProducerListPageDto input)`

Error :  https://domain/api/app/producer/producers?sorting=name%20asc&skipCount=0&maxResultCount=10 500 (Internal Server Error)

I am not having a problem with my local machine.

Thanks.

**Comment by realLiangshiwei** [comment]
I think it has nothing to do with abp. you should check the application logs.

**Comment by genceraziz** [comment]
> I think it has nothing to do with abp. you should check the application logs.

There is nothing about this error in the application logs. I also looked at the logs from Event Viewer, nothing there either.
