### ISSUE TITLE
Abp Generate-Proxy Command throw [Invalid API Definition] The provided API definition is invalid.

### ISSUE THREAD

**Issue by muhammedshaaban7** [abpframework/abp#5885]
my swagger up and running and Run the following command in the angular folder:
abp generate-proxy
[14:27:48 INF] ABP CLI (https://abp.io)
[14:27:49 INF] Version 3.2.1 (Stable)
[14:27:50 WRN] Couldn't determinate version of "@abp/ng.schematics" package.
**[Invalid API Definition] The provided API definition is invalid.**

I can't generate proxy and i don't know what the issue ? any help?

**Comment by amsaighi** [comment]
Verify ur version @abp/ng-scematics :"~3.2.1" 
and try to give a source of ur API by following this : 
[generate-proxy](https://docs.abp.io/en/abp/latest/CLI#options-5)

**Comment by muhammedshaaban7** [comment]
@amSaighi actualy version @abp/ng-scematics :"~3.2.1" and i tried to give a source , the result is the same.
**[Invalid API Definition] The provided API definition is invalid.**

any suggestions

**Comment by amsaighi** [comment]
Did you verify the baseUrl of API in envirenement.ts ?

**Comment by muhammedshaaban7** [comment]
this is a enviroment.ts as following 
import { Config } from '@abp/ng.core';

const baseUrl = 'http://localhost:4200';

export const environment = {
  production: false,
  application: {
    baseUrl,
    name: 'Demo',
    logoUrl: '',
  },
  oAuthConfig: {
    issuer: 'https://localhost:44358',
    redirectUri: baseUrl,
    clientId: 'Demo_App',
    responseType: 'code',
    scope: 'offline_access Demo',
  },
  apis: {
    default: {
      url: 'http://localhost:44330',
      rootNamespace: 'Demo',
    },
  },
} as Config.Environment;

**Comment by amsaighi** [comment]
Can you push ur project on the cloud ( github ) ?

**Comment by muhammedshaaban7** [comment]
basic startup template from direct download with following :-
project type --- application
ui framework --- angular 
Database provider ---ef core
when downloaded it , run app and error shown.

thanks @amSaighi appreciate your feedback

**Comment by amsaighi** [comment]
It should work, 
I suggest you to follow this steps : 
- Create project using ABP Cli ' abp new Acme.BookStore -u angular --separate-identity-server '
- Run the both of project ( httpApi.host and IdentityServer ).
- Generete proxy ( when the project in runing )

try to use and run this abp repo " [sample ABP-Angular ](https://github.com/amSaighi/ABP-Angular) "
ping @muhammedshaaban7

**Comment by muhammedshaaban7** [comment]
![image](https://user-images.githubusercontent.com/64292395/97114134-b7241980-16ff-11eb-8f77-5d4075b61cb9.png)

the same @amSaighi ,, i downloaded sample ABP-Angular and i followed steps but not working

**Comment by amsaighi** [comment]
![abpppp](https://user-images.githubusercontent.com/3142753/97120061-cbbedc80-1714-11eb-9d9c-084445611f73.PNG)
look, I downloaded it and generate the proxy, and it work perfectly. 

Are you sure that you get the result from http host ? ( swagger of course )

![swager](https://user-images.githubusercontent.com/3142753/97120475-7a641c80-1717-11eb-898f-5c25fc61e62b.PNG)

**Comment by aididhaiqal** [comment]
Having the same issue,

Project generated initially using abp new Acme.BookStore -t app-pro -u angular -d mongodb.

Tried a brand new project without any modification, same issue as well

**Comment by aididhaiqal** [comment]
My problem resolved by reinstalling node js and updating it to latest version

**Comment by brunobertechini** [comment]
I am having a similar problem, but the error is 
`[Invalid Module] Backend module "app" does not exist in API definition.`

Simple oob application created with:
abp new MyProject -u angular --separate-identity-server

Node Version: v14.15.0

**Comment by idreeshaddad** [comment]
Just created a fresh Abp v4 project. Everything works fine, swagger shows the endpoints just fine, DB created just fine, admin user logged in just fine, but I got the same error:
`[Invalid Module] Backend module "app" does not exist in API definition.`

Node: v14.15.1
NPM: v6.14.9
Angular CLI: 11.0.3
OS: win32 x64
@abp/ng.schematics: ~4.0.0

What have you tried to solve it?

**Comment by idreeshaddad** [comment]
For what it's worth: If you create a brand new solution and haven't added any custom Application Services yet; then there will be no "app" module to generate proxy from.

More information is added to stackoverflow answer:
https://stackoverflow.com/a/65279561/655605


And this begs the question: Where is this `"app"` module defined, and can I modify it?

**Comment by thanhtai9606** [comment]
I have found issue in the angular project
`  apis: {
    default: {
      url: 'https://localhost:4437,
      rootNamespace: 'Becamex.ArchiveCenter',
    },
    ArchiveCenter: {
      url: 'https://localhost:44377',
      rootNamespace: 'Becamex.ArchiveCenter',
    },
  },
` in environment.ts
in default apis have to reference in default in api, but not auth api. I have much a lot of time for this

**Comment by vedatermis** [comment]
try this command:
abp generate-proxy -t ng --url https://localhost:44310

**Comment by SamirC554** [comment]
I uninstalled  and downgrade volo.abp.cli from 5.2.2 to 5.1.1 and it worked.
 dotnet tool uninstall -g volo.abp.cli
 dotnet tool install -g volo.abp.cli --version 5.1.1

**Comment by YaoaY** [comment]
Considering your host uses something like AutoWrapper..
🤣
