### ISSUE TITLE
Remote service returns Unauthorized error

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#5888]
When I call an `[Authorize]`-ed method of an application service of my remote service, I get this:

```
[16:17:53 WRN] Could not find IdentityClientConfiguration for . Either define a configuration for  or set a default configuration.
[16:17:53 INF] Start processing HTTP request GET https://localhost:44378/api/ErpService/sample/authorized?api-version=1.0
[16:17:53 INF] Sending HTTP request GET https://localhost:44378/api/ErpService/sample/authorized?api-version=1.0
[16:17:53 INF] Received HTTP response after 57.1512ms - Unauthorized
[16:17:53 INF] End processing HTTP request after 58.3798ms - Unauthorized
[16:17:54 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "Une erreur interne s'est produite lors de votre demande!",
  "details": null,
  "data": {},
  "validationErrors": null
}
[16:17:54 ERR] Remote service returns error! HttpStatusCode: Unauthorized, ReasonPhrase: Unauthorized
Volo.Abp.AbpException: Remote service returns error! HttpStatusCode: Unauthorized, ReasonPhrase: Unauthorized
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.MakeRequestAsync(IAbpMethodInvocation invocation)
...
```

What I try to achieve is this:
- Blazor frontend.
- Classic ASP.NET Core backend. Include IdentityServer.
- Remote service for specific business work. Called by backend. Uses backend for auth. No anonymous access allowed. `ICurrentUser` being the one from backend would be very appreciated.

Here is my repro steps:

1. `abp new MyCompany.MyProject -u blazor`
1. `abp new MyCompany.MyProject.MyRemote -t module --no-ui`
1. Deleted `MyCompany.MyProject.MyRemote.HttpApi.Host/EntityFrameworkCore` directory, because my remote service no needs neither its own database nor its own IdentityServer.
1. Deleted `MyCompany.MyProject.MyRemote.HttpApi.Host/Migrations` directory.
1. Deleted related project referencies, using's, modules dependencies, for build to succeed.
1. Deleted `options.UseSqlServer();`.
1. `MyCompany.MyProject.MyRemote.HttpApi.Host/appsettings.json`: set `"Authority" to backend's URL.
1. `MyCompany.MyProject.MyRemote.HttpApi.Host/appsettings.json`: add `"ClientId": "MyProject.MyRemote"`.
1. `MyCompany.MyProject.MyRemote.HttpApi.Host/appsettings.json`: set `"CorsOrigins" to backend's URL.
1. `MyCompany.MyProject.HttpApi.Host/appsettings.json`: set `"CorsOrigins" to remote's URL.
1. `MyCompany.MyProject.HttpApi.Host/appsettings.json`: add
```
"RemoteServices": {
  "Default": {
    "BaseUrl": "{remote's URL}"
  }
}
```
1. `DbMigrator/appsettings.json`, in "Clients" region:
```
"MyProject_MyRemote": {
	"ClientId": "MyProject_MyRemote",
	"RootUrl": "{remote's URL}"
}
```
1. `IdentityServerDataSeedContributor.cs`: add
```
var myRemoteClientId = configurationSection["MyProject_MyRemote:ClientId"];
if (!myRemoteClientId.IsNullOrWhiteSpace())
{
	await CreateClientAsync(
		name: myRemoteClientId,
		scopes: commonScopes,
		grantTypes: new[] { "password", "client_credentials", "authorization_code" },
		secret: configurationSection["MyProject_MyRemote:ClientSecret"]?.Sha256(),
		requireClientSecret: false
	);
}
```
1. `MyRemoteHttpApiHostModule.cs`: add
```
options.Audience = "{MyProject}";
```
1. Added `Volo.Abp.Http.Client.IdentityModel` NuGet package to `MyCompany.MyProject.Domain.csproj` package references.
1. Added `MyCompany.MyProject.MyRemote.HttpApi.csproj` project reference too.
1. Added corresponding modules dependencies in `MyProjectDomainModule`.
1. Added an endpoint to my `MyCompany.MyProject.HttpApi.Host` by adding this to `MyCompany.MyProject.Application`:
```
using System.Threading.Tasks;
using MyCompany.MyProject.MyRemote.Samples;

namespace MyCompany.MyProject
{
    public class SampleCallerAppService: MyProjectAppService
    {
        private readonly ISampleAppService _sampleAppService;

        public SampleCallerAppService(
            ISampleAppService sampleAppService)
        {
            _sampleAppService = sampleAppService;
        }

        public Task<SampleDto> GetAsync()
        {
            return _sampleAppService.GetAsync();
        }
        
        public Task<SampleDto> GetAuthorizedAsync()
        {
            return _sampleAppService.GetAuthorizedAsync();
        }
    }
}
```
1. Install Memurai (https://www.memurai.com/get-memurai).
1. Run `DbMigrator`.
1. Run `HttpApi.Host`.
1. Run `MyRemote.HttpApi.Host`.
1. Navigate to `HttpApi.Host`'s Swagger.
1. Call `SampleCallerAppService.GetAsync`: 200 (OK).
1. Call `SampleCallerAppService.GetAuthorizedAsync`: 500 (Internal server error (see above for error details)).

I tried to add this to `MyRemote.HttpApi.Host/appsettings.json` with no luck:
```
  "IdentityClients": {
    "Default": {
      "GrantType": "password",
      "ClientId": "MyProject_MyRemote",
      "ClientSecret": "1q2w3e*",
      "UserName": "admin",
      "UserPassword": "1q2w3E*",
      "Authority": "{backend URL}",
      "Scope": "MyProject"
    }
  }
```

I also tried to add `Volo.Abp.Http.Client.IdentityModel.Web` NuGet package and `[DependsOn]` `AbpHttpClientIdentityModelWebModule` to `HttpApi.Host` (from https://github.com/abpframework/abp/issues/4888), but with no luck too.

Is `[16:17:53 WRN] Could not find IdentityClientConfiguration for . Either define a configuration for  or set a default configuration.` related? What is lacking?

I am aware of https://github.com/abpframework/abp/issues/2811 but author closed before explaining anything.

I am aware too of https://github.com/abpframework/abp/issues/3423 but, again, no explanation.

I am aware too of https://github.com/abpframework/abp/issues/3527 but became inactive.

I am aware too of https://github.com/abpframework/abp/issues/1437 but last two posts are in non-english language. 

https://github.com/abpframework/abp/issues/1452 is inactive now too.

BTW (1), why ABP module template expose its sample application service with explicit controller? Is it good practice?
BTW (2), is it possible to get back auto IRemoteService implementations exposure via dynamic controllers?

Thank you in advance for any help.

**Comment by Stirda** [comment]
With latest ABP (3.2.1).

**Comment by maliming** [comment]
hi @Stirda

The steps you provided are very complicated. Can you try to reproduce this problem with simple codes and steps?

Abp's template project can be tiered, maybe you can try that.

**Comment by Stirda** [comment]
Hi @maliming 

Thank you for your answer. 

Sorry but I think that my steps are already the simplest to achieve the goal. Communication between backend and remote service needs a few .json configuration files, because of remote services calls and authentication leaded by backend. I already make my steps easier and lighter that my actual solution.

I believe that @EngincanV thumb-up is for your tiered suggestion. But I don't get the point. Tiered solution means one extra layer/application: the IdentityServer one. Right? So my architecture will be even one step more complicated?

All of this was just following the @hikalkan module architecture documentation (https://docs.abp.io/en/abp/3.2/Best-Practices/Module-Architecture#layers-packages) were "D)" approach gives hope of a simple way to ask ABP CLI to add a remote service to an existing ABP application, as I described above.

**Comment by Stirda** [comment]
@maliming At least, what are you thoughts about:
```
[16:17:53 WRN] Could not find IdentityClientConfiguration for .
Either define a configuration for  or set a default configuration.
```
Is this a sign of misconfiguration? How to solve?

I accept to even simplify more by asking the following: 

What to add to a remote service (module) ABP solution and to an application ABP solution, for the second one to be able to call the first one with authentication? Even if we cannot solve the sent of the bearer token (authenticating current user) between the two, can you give at least a basic global authentication way? I don't want my ABP remote service to be full anonymous access ...

**Comment by sturlath** [comment]
@Stirda did you ever figure this one out?

**Comment by viewtance** [comment]
@Stirda  did you figure out how to deal with this issue? I encountered this too.

**Comment by Stirda** [comment]
No. I didn’t work on this. No news from Volosoft.

**Comment by hatami57** [comment]
You need to do these two steps:

1. Add `Volo.Abp.Http.Client.IdentityModel` nuget package to the remote service client project
2. Add `typeof(AbpHttpClientIdentityModelModule)` in the remote service client module dependencies

for more information, see this document about [configuring auto-discovery endpoint](https://docs.abp.io/en/commercial/latest/startup-templates/microservice/synchronous-interservice-communication#configuring-auto-discovery-endpoint).
