### ISSUE TITLE
Unauthorized in Swagger with tiered application

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#5896]
1. `abp new Acme.BookStore -u blazor --separate-identity-server`
1. `dotnet build`
1. DbMigrator> `dotnet run`
1. IdentityServer> `dotnet run`
1. HttpApi.Host> `dotnet run`
1. Browse IdentityServer> Login as `admin`
1. Browse HttpApi.Host URL (swagger)> Call `/api/identity/users` > `401 Unauthorized`

With ABP 3.2.1.

**Comment by maliming** [comment]
We do not implement any authentication methods in swagger by default. You can do it yourself. : )

**Comment by Stirda** [comment]
Closed this issue because duplicate of https://github.com/abpframework/abp/issues/1874 and solutions were given there.
