### ISSUE TITLE
How do I use ZH-Hans by default when a project starts

### ISSUE THREAD

**Issue by CaiJinHao** [abpframework/abp#5898]
How to use ZH-Hans by default when the project starts? I start en every time, and it can only work by changing Cookies to ZH-Hans.I want my project to start with ZH-Hans by default.Settings like the following do not work, the default is en
Configure<AbpLocalizationOptions>(options =>
            {
                options.Resources
                    .Add<YourProjectNameResource>("zh-Hans")
                    .AddBaseTypes(typeof(AbpValidationResource))
                    .AddVirtualJson("/Localization/YourProjectName");
            });

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/5219

**Comment by CaiJinHao** [comment]
thank you @realLiangshiwei
