### ISSUE TITLE
Move MyProjectPermissions.cs from under project Application.Contracts to project Domain.Shared

### ISSUE THREAD

**Issue by talhazengin** [abpframework/abp#5900]
Hi,
This is a suggestion.
I wrote a DataSeedContributor recently. But it was hard, because i couldn't find permission definitions under Domain Layer.

**Comment by maliming** [comment]
Permission should exist in the application service layer。

**Comment by talhazengin** [comment]
Please read again my edited entry message. I created the issue with miss click.

**Comment by talhazengin** [comment]
So, can i get an explanation why is this must be in the application layer?

**Comment by mtozlu** [comment]
There is an undocumented feature to achieve what you want.
You can use `WithProperty` method of `PermissionDefinition` to pass an information along with definition. When seeding permissions, you can get the information from `Properties` key of the definition.

Here is an example;
PermissionDefinitionProvider file in Application.Contracts layer:
```csharp
 group.AddPermission("ManageUsers", L("Permission:ManageUsers"))
    .WithProperty("DefaultRole", "CustomerAdmin");
```

DataSeeder file in Domain layer:
```csharp
// Get all permissions
var permissions = PermissionDefinitionManager.GetPermissions()
    .Where(p => p.MultiTenancySide.HasFlag(MultiTenancySides.Both))
    .Where(p => !p.Providers.Any() || p.Providers.Contains(RolePermissionValueProvider.ProviderName))
    .ToList();

foreach (var permission in permissions)
{
    var prop = permission.Properties.GetOrDefault("DefaultRole");
    if (prop != null && prop is string propString)
    {
        // You have "CustomerAdmin" as the value of "propString" here.
    }
}
```
