### ISSUE TITLE
Können Sie uns helfen, ABP ins Deutsche zu übersetzen?

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#5912]
Hi we are trying to translate the ABP localizations into German language.
Is there anybody who can help us.
I'll send you the translation files.

**Comment by tntwist** [comment]
Hi. I would like to help with this. I also would like to help translating ABP Commercial localizations into German.

**Comment by AlexanderPilhar** [comment]
I would like to help you with this, too.

**Comment by ebicoglu** [comment]
Hi guys,

Thanks for accepting my request.
Here are the 2 translation files that needs to be translated.
You just fill the `Target` fields. Then make that a Zip file and attach the file under this issue.

1. [abp-translation.volo.de-DE.zip](https://github.com/abpframework/abp/files/5434832/abp-translation.volo.de-DE.zip) - **@tntwist**
2. [abp-translation.abp.de-DE.zip](https://github.com/abpframework/abp/files/5434833/abp-translation.abp.de-DE.zip) - **@AlexanderPilhar**

**Comment by tntwist** [comment]
Hi @ebicoglu,
I just finished the translation. Here are my results:

[abp-translation.volo.de-DE.json.zip](https://github.com/abpframework/abp/files/5470930/abp-translation.volo.de-DE.json.zip)

**Comment by ebicoglu** [comment]
@tntwist you're great! I've merged your translation. If you write your name I can add you to the greetings list.

**Comment by ebicoglu** [comment]
@AlexanderPilhar did you have a chance to start the translation?

**Comment by AlexanderPilhar** [comment]
Yes, here you go!

[abp-translation.abp.de-DE.zip](https://github.com/abpframework/abp/files/5471621/abp-translation.abp.de-DE.zip)

**Comment by tntwist** [comment]
@ebicoglu Here is my name: Nico Lachmuth

If you need updates for the translations in the future, just mention me and I`ll help updating them.

**Comment by ebicoglu** [comment]
@AlexanderPilhar  thanks for your contribution. German language will be available in the next version.
