### ISSUE TITLE
A second operation started on this context before a previous operation completed

### ISSUE THREAD

**Issue by vnc4567** [abpframework/abp#5916]
Hi, I have an issue on this code :  

```
private void InsertAndUpdateAlertesAsync(AlerteJobContainer container)
        {
            var listeTaskUpdate = new List<Task>();

             foreach (var alerteUpdated in container.BulkToBeUpdated)
            {
                listeTaskUpdate.Add(_operationAlerteRepository.UpdateAsync(alerteUpdated,autosave: true));
            }

            Task.WaitAll(listeTaskUpdate.ToArray());
        }
```
I get this error : 

**A second operation started on this context
before a previous operation completed. This is usually caused by different
threads using the same instance of DbContext. For more information on how to avoid
threading issues with DbContext**

If I change my code to this : 

```
private void InsertAndUpdateAlertesAsync(AlerteJobContainer container)
        {
            var listeTaskUpdate = new List<Task>();

             foreach (var alerteUpdated in container.BulkToBeUpdated)
            {
                listeTaskUpdate.Add(_operationAlerteRepository.UpdateAsync(alerteUpdated));
            }

            Task.WaitAll(listeTaskUpdate.ToArray());
        }
```

The error is gone when I remove **autosave:true**

I know in this case I don't need the autosave but I want to understand the issue.
Is there a problem with my implementation of asynchrone and task ?

Do you think, performance-wise, it is better to use a foreach with await like this : 

```
private void InsertAndUpdateAlertesAsync(AlerteJobContainer container)
        {
             foreach (var alerteUpdated in container.BulkToBeUpdated)
            {
                await _operationAlerteRepository.UpdateAsync(alerteUpdated));
            }
        }
```

Thanks.

Best regards

**Comment by maliming** [comment]
1. Never use **void** as an async method return type.
2. EF Core doesn't support multiple parallel operations being run on the same context instance. You should always wait for an operation to complete before beginning the next operation. This is typically done by using the await keyword on each async operation.

**Comment by vnc4567** [comment]
Thank you for your reply,
I understand your point but I don't understand why without autosave : true it works ?

How does "autosave: true" work ? I don't quite get this part

Maybe it comes from the transaction without autosave nothing is commit to DB until the end of the function

**Comment by maliming** [comment]
Please check the document:
https://docs.abp.io/en/abp/latest/Unit-Of-Work
https://docs.abp.io/en/abp/latest/
