### ISSUE TITLE
[Angular UI] ListService - server side filtering

### ISSUE THREAD

**Issue by nymeron** [abpframework/abp#5919]
This is more of a question related to use of ListService in Angular UI than bug/issue. 

Is there a way to implement server side filtering with ListService? I know I can use an input search, but I'd like to filter data on server side based on some property that'd send. 

Example on get data that have property X equal to 1.

Also I asked the question on SO https://stackoverflow.com/questions/64453564/abp-io-angular-ui-listservice-with-custom-property-filter

Any help is much appreciated!

**Comment by bnymncoskuner** [comment]
Hello,

I've posted an answer to your question. It should work for you. If it doesn't, you can add a comment to my answer and I'll reply. Thank you.
