### ISSUE TITLE
Single-Spa : The javascript metaframework

### ISSUE THREAD

**Issue by guilmori** [abpframework/abp#592]
I came across this framework:
https://github.com/CanopyTax/single-spa

Havn't tried it out myself, but read very good reviews, and I really like the idea, so I wanted to share.

Maybe ABP could make use of this so the end developer can decide on his spa framework of choice. So ABP doesn't have to commit on a few selected spas.

The community could develop ABP modules for each spa.

This also would make upgrading spa frameworks much more easier by allowing to gradually upgrade to a new version or even a new spa.

**Comment by hikalkan** [comment]
Thank you. I didn't know it. I will definitely check, it seems very good.

**Comment by rmsryu** [comment]
Hi @hikalkan,

I've been looking to the documentation and I couldn't find any related to UI Composition or Micro-frontend. Is still in the roadmap of abp.io to implement UI Composition as originally announced https://blog.abp.io/abp/Abp-vNext-Announcement? 

I've recently tested https://github.com/single-spa/single-spa framework and looks a good candidate to start with Micro-frontends and UI Composition.

Regards

**Comment by hikalkan** [comment]
>UI Composition is one of the main goals. For this purpose, theme system will provide menus, toolbars and other extensible areas to allow other modules to contribute.

When you start a new project from the application startup template, you will see user management and tenant management pages. They are defined/implemented in different solutions and deployed as different NuGet packages. That's was the goal, and yes it is currently possible.

**Comment by rmsryu** [comment]
I see @hikalkan 
I'll play a little bit more with that. I think you are referring to modules https://docs.abp.io/en/abp/latest/Startup-Templates/Module

`abp new Acme.IssueManagement -t module -ui angular`

Thanks.
