### ISSUE TITLE
Generate-proxy:How to configure the service api 

### ISSUE THREAD

**Issue by Qlimax2009** [abpframework/abp#5921]
I use the abp3.2.1 with angular .
I use abp generate-proxy to cerate services.
abp generate code:
` checkBeamByBeamId = (beamId: number) =>
    this.restService.request<any, boolean>({
      method: 'POST',
      url: `/api/app/beam/checkBeam/${beamId}`,
    },
    { apiName: this.apiName });`

The api in C# code:
`public Task<bool> CheckBeam(long beamId)`

But I wish the api code
`checkBeam = (beamId: number) =>...`

I want to keep the name of the API the same as the backend，How can I configure this？
Thanks in advance

**Comment by maliming** [comment]
Is `CheckBeam` an application service method or a controller method ?

**Comment by maliming** [comment]
Maybe we should allow developers to customize method names, etc. @hikalkan What do you think?

https://github.com/abpframework/abp/blob/207df569b6990e5cbdd61d8a8c1dec8cf730566c/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AspNetCoreApiDescriptionModelProvider.cs#L137

**Comment by Qlimax2009** [comment]
> Maybe we should allow developers to customize method names, etc. @hikalkan What do you think?
> 
> https://github.com/abpframework/abp/blob/207df569b6990e5cbdd61d8a8c1dec8cf730566c/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AspNetCoreApiDescriptionModelProvider.cs#L137

I looked up the source code and modified it the provider，and then injected it，it works.
As a user, I hope to be able to customize method names or several styles to choose.
Thank you.
