### ISSUE TITLE
Can I customizing the input dto of modules?

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#5927]
My project need register by phone number instead of username or email.
So I want to append the `PhoneNumber` property into `RegisterDto` of `AccountModule` ([/api/account/register](https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Application/Volo/Abp/Account/AccountAppService.cs#L32-L44)).

How can I customize it?
Do I have to disable the default AccountModule and rewrite the whole module?

**Comment by realLiangshiwei** [comment]
All DTOs are extensible:
https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#extending-data-transfer-objects

**Comment by PMExtra** [comment]
Thanks, I've read this document before I send this issue. But I thought it can only extend output dto, otherwise I don't know how to access the extended field. But I may miss something about `extraProperties`, I will read the document again and try it later.
On the other hand, how about if I want to drop some unused field from the current DTO in module?
Can I just disable specified API from module? Then I can make another API that with different method signature to alternative it.

**Comment by realLiangshiwei** [comment]
Object extension system can expand input & output.

Example input : 

````json
{
   "userName": "...",
    .....
    "extraProperties": {
        "phoneNumber": "...."
   }
}
````

**Comment by PMExtra** [comment]
I still don't know how to read the extra properties in C#, the DTO does not inherit from `IHasExtraProperties`

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/4427#issuecomment-650603470
