### ISSUE TITLE
Authorize with multiple permission (one of them)

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#5928]
In old boilerplate, We have `[AbpAuthorize("Permission1", "Permission2", RequireAllPermissions = false)]` that can specify multiple permissions with one API.

Now, we migrated from `AbpAuthorizeAttribute` to `Microsoft.AspNetCore.Authorization.AuthorizeAttribute`, multiple `AuthorizeAttribute` will be evaluated with AND logic, the same as `RequireAllPermissions = true`.

I cannot find a simple way to implement the behavior I want, the only way I found is implemented a custom Authorize. Shall we consider to get `AbpAuthorizeAttribute` back or make something other to deal this case?

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/latest/Authorization#overriding-a-permission-by-a-custom-policy

**Comment by PMExtra** [comment]
@maliming It's not what I want. I know I can customize authorization to implement that, but it may take too much code. My requirement is very simple and general, just combine several abp permissions (Such as somebody can get all entities, some other can get only recent. They can both access `GetAll` but I will append a `Where` condition to limit result if the current user does not have GetAllPermission)
In older ASP.NET boilerplate I just need one attribute, it's enough.

**Comment by PMExtra** [comment]
Another use case:
Admin can get all entities, user can get only entities created by himself. So I defined two permissions: `GetAll` and `GetMine`.
They can both access `GetAll` API but I will append a `Where` condition to filter the result for `GetMine` permission.
