### ISSUE TITLE
Need help for es translation - Ayuda con la traducción al español

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#5931]
Hi @miguelgimenez  and @wocar, I found you from this issue https://github.com/abpframework/abp/issues/1413
Can you help me to translate ABP into Spanish language?
I know there's an existing Spanish translation but we are missing many texts now in Spanish.

These are the localization files to be translated into es-MX.
There are 2 files. It would be very appreciated, if you or anybody can help on this. Just fill the `Target` fields and attach the file as Zip under this issue.

Update: Excluded unnecessary resources from the translations (like tests, samples etc.)

---

1. [abp-translation.abp.es-MX.zip](https://github.com/abpframework/abp/files/5473574/abp-translation.abp.es-MX.zip)
2. [abp-translation.volo.es-MX.zip](https://github.com/abpframework/abp/files/5473575/abp-translation.volo.es-MX.zip)

**Comment by washyn** [comment]
You can add spanish lang with  command "abp add-languaje es" or typing "abp help", or contactme, luck

**Comment by ebicoglu** [comment]
@washyn, actually I know how to add a new language but I need help to translate to Spanish for ABP

**Comment by washyn** [comment]
You can write me to shin321654987@gmail.com , and i Help you. Puedes escribirme al email para echarte una mano.

**Comment by jmglezgz** [comment]
I’m able to translate abp Framework to es-ES but not the local culture MX. Anyway, Let me know how can I help you translating abp framework.

Thanks,

**Comment by ebicoglu** [comment]
@washyn you can translate https://github.com/abpframework/abp/files/5473575/abp-translation.volo.es-MX.zip

---

@jmglezgz you can translate https://github.com/abpframework/abp/files/5473574/abp-translation.abp.es-MX.zip

I will add your names to the greeting list

**Comment by ebicoglu** [comment]
@jmglezgz you translate to es-ES then if there's any local change for MX, we'll update

**Comment by jmglezgz** [comment]
> @jmglezgz you translate to es-ES then if there's any local change for MX, we'll update

Perfect es-ES sounds good for me, I'm working on it. 50% in progress. Hope ready tomorrow.

**Comment by ebicoglu** [comment]
also can you share your names

**Comment by jmglezgz** [comment]
Jose Manuel Gonzalez

**Comment by jmglezgz** [comment]
Hi @ebicoglu, I have finished **es-ES translation**. Focus on framework and modules. Let me know how do you want to receive the file.

**Comment by ebicoglu** [comment]
you can make it zip and attach it here

**Comment by jmglezgz** [comment]
> you can make it zip and attach it here

Upsss! I didn't realize that I can drag and drop
[abp-translation.abp.es-ES.zip](https://github.com/abpframework/abp/files/5538446/abp-translation.abp.es-ES.zip)

abp.io section in progress, I'll finish as soon as possible.

**Comment by washyn** [comment]
the translation of volo is at 90% you can add the missing parts or make a comparison with what you have. In this repo https://github.com/washyn/abp_volo_es-mx_translate

**Comment by ebicoglu** [comment]
Guys, are there any big differences in es-ES and es-MX?

**Comment by jmglezgz** [comment]
Nop really, we perfectly understand both.  Some words could be sound weird because is not common to use in Spain or Mexico, but nothing to be worried. I would say that we can use "es" only without culture if its possible.

**Comment by ebicoglu** [comment]
thank you.
