### ISSUE TITLE
IFeatureChecker.GetOrNullAsync throws an AbpException if not found

### ISSUE THREAD

**Issue by dmytroshchotkin** [abpframework/abp#5933]
Please check Volo.Abp.Features.IFeatureChecker.GetOrNullAsync(string name) method.
It throws an exception if the name is not found. And it's expected to get null instead.

**Comment by maliming** [comment]
hi

**FeatureChecker** does not seem to throw an exception.

https://github.com/abpframework/abp/blob/1a622bc50fbd9b554f61078d5eeafa9def3216e3/framework/src/Volo.Abp.Features/Volo/Abp/Features/FeatureChecker.cs#L39-L66

* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
