### ISSUE TITLE
Server-side PreRendering with Blazor WebAssembly

### ISSUE THREAD

**Issue by geffzhang** [abpframework/abp#5936]
.NET 5 Blazor  WebAssembly  has support Server-side PreRendering,  https://github.com/dotnet/aspnetcore/issues/21514

**Comment by Stirda** [comment]
@hikalkan Possible duplicate of https://github.com/abpframework/abp/issues/5519 ?

**Comment by geffzhang** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0&pivots=webassembly

**Comment by maliming** [comment]
Duplicate of #5517
