### ISSUE TITLE
Could not retrieve the OpenId Connect discovery document! ErrorType: PolicyViolation. Error: Endpoint does not use HTTPS

### ISSUE THREAD

**Issue by OrxanMusayev** [abpframework/abp#5948]
when i login with abp cli command (abp login "username" -p "password") I get this error
![Screenshot 2020-10-26 175058](https://user-images.githubusercontent.com/33355338/97180854-07f54a00-17b4-11eb-93e3-c71dafa50853.png)

**Comment by realLiangshiwei** [comment]
@erolarkat 
It looks like we are losing some configuration.  https://github.com/abpframework/abp/blob/dev/docs/en/Migration-Guides/Abp-4_0.md#migrating-the-database
Could you check this?

**Comment by realLiangshiwei** [comment]
Related https://github.com/abpframework/abp/issues/5950

**Comment by realLiangshiwei** [comment]
It works now, please try to login again.
