### ISSUE TITLE
Add an explicit exception throw when calling synchronous remote method with C# API client proxy

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#5951]
- Synchronous remote method returning `T1<T2>`.
- Call from remote Swagger: OK.
- Call from an ABP C# API client proxy: an exception is thrown:

```
Unable to cast object of type 'T2' to type 'T1`1[T2]'.
```

Maybe it seems that `Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor.InterceptAsync` takes from granted that remote return type is always a `Task<T>` by looking into `GenericTypeArguments[0]` and calling `GetGenericArguments()[0]`.

I know that synchronous ASP.NET Core development is bad pratice, but developers would find quickly their mistake if `Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor.InterceptAsync` would throw an explicit exception if `invocation.Method.ReturnType` is not a `Task<T>`?

I spent a long time figuring that the reason of my C# API Client Proxies weird behavior were only because of that.

ABP latest (3.2.1).

**Comment by Stirda** [comment]
I wonder if inheriting from `ApplicationService` is also a requirement. I got some `Unable to resolve service` if just implementing `IApplicationService`.

**Comment by maliming** [comment]
hi
Could you share some code to reproduce this?

**Comment by Stirda** [comment]
@maliming Thank you for your support. There is no specific code to use. Reproduction is as easy as:

**Step 1.** Code any application service method returning anything but `Task` or `Task<T>`. You can do it in any ABP application. It will serve as the "remote service" application.
**Step 2.** Enable ABP Auto API Controller system in this "remote service" application to expose method coded in step 1.
**Step 3.** Call method from any another ABP application (the "client" application) using ABP Dynamic C# API Client Proxy system.

**Comment by maliming** [comment]
Can you share a project to repro this?
