### ISSUE TITLE
Upgrade all samples to 4.0 & test

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5960]
- [x] BookStore-*, BasicAspNetCoreApplication, PostgeSqlDemo / @maliming  https://github.com/abpframework/abp-samples/pull/48
- [x] DashboardDemo, ClientSimulationDemo, SignalRDemo, SignalRTieredDemo / @yekalkan 
- [x] Authentication-Customization, OrganizationUnitSample / @gterdem https://github.com/abpframework/abp-samples/pull/50
- [x] DevExtreme-MVC, TextTemplateDemo / @cotur https://github.com/abpframework/abp-samples/pull/52
- [x] DevExtreme-Angular / @cotur & @bnymncoskuner
- [x] DocumentationSamples, EfCoreMigrationDemo, GrpcDemo, KafkaEventBus, RabbitMqEventBus, RebusEventBus / @realLiangshiwei  https://github.com/abpframework/abp-samples/pull/49
- [x] EventOrganizer / @cotur -> moved to https://github.com/abpframework/abp/issues/6612
- [x] PasswordlessAuthentication, StoredProcedureDemo / @ebicoglu

**Comment by maliming** [comment]
I will fix the Github ci problem when everyone finishes the upgrade.

https://github.com/abpframework/abp-samples/actions

**Comment by Rwing** [comment]
not MicroserviceDemo?

**Comment by hikalkan** [comment]
@Rwing we are considering to re-write it.

**Comment by hikalkan** [comment]
Moved remaining work to https://github.com/abpframework/abp/issues/6612 and closing this.

**Comment by maliming** [comment]
Github CI is working.  
https://github.com/abpframework/abp-samples/actions

@gterdem @bnymncoskuner @yekalkan @ebicoglu @cotur 
Please upgrade the unit tests in the sample next time. : )

**Comment by xyfy** [comment]
> @Rwing we are considering to re-write it.

Are there any plans?  when will do it ?
