### ISSUE TITLE
User & Role Manager

### ISSUE THREAD

**Issue by Brahimhz** [abpframework/abp#5963]
I'm new in #abpFramework , I followed all the tutorial and Documentation in https://www.abp.io/ , but I still blocked in User and Role Manger.
I would custom register , role and user AppService , by adding default roles in creation of DB .
And in Register and creation of users , I would assign for them a specific role .
Then with another Endpoint , I want to add for them Other Roles , and have the possibility to remove this roles .

I need Solution soon So Please Help Me .
Thanks

**Comment by khinhvuphiduong** [comment]
I don't understand what you mean? When you create user, you can add user to specific role by ` "roleNames": [
    "string"
  ]`

**Comment by Brahimhz** [comment]
> I don't understand what you mean? When you create user, you can add user to specific role by ` "roleNames": [ "string" ]`

Like I said I'm New in Abp Framework and Identity Server So tried many time to use IdentityUserManager but I had many problem , so if you can help to use IdentityUSerManger Of abp Framework I will be thankful :)

**Comment by khinhvuphiduong** [comment]
> > I don't understand what you mean? When you create user, you can add user to specific role by ` "roleNames": [ "string" ]`
> 
> Like I said I'm New in Abp Framework and Identity Server So tried many time to use IdentityUserManager but I had many problem , so if you can help to use IdentityUSerManger Of abp Framework I will be thankful :)

I think your problem is first data seeder to initial role and permission. Please start from MicroserviceDemo application and step by step ABP Team's instruction, Ii's very clear.

**Comment by Brahimhz** [comment]
> > > I don't understand what you mean? When you create user, you can add user to specific role by ` "roleNames": [ "string" ]`
> > 
> > 
> > Like I said I'm New in Abp Framework and Identity Server So tried many time to use IdentityUserManager but I had many problem , so if you can help to use IdentityUSerManger Of abp Framework I will be thankful :)
> 
> I think your problem is first data seeder to initial role and permission. Please start from MicroserviceDemo application and step by step ABP Team's instruction, Ii's very clear.

Ok I Will do thanks for the advise

**Comment by rygar08** [comment]
khinhvuphiduong, you say .... `Please start from MicroserviceDemo application and step by step ABP Team's instruction, Ii's very clear.`
I don't see any readme files, no instructions. I would suggest that maybe some ABP documentation would make it 'clear' because currently it is not.
