### ISSUE TITLE
Creating a new UI theme by copying the Basic Theme (for MVC UI)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5965]
I am currently writing the MVC theming document and I see such a sample would be good.
We can create a new solution, copy the Basic Theme into the solution, change NuGet package references to local project references and customize the theme a bit to demonstrate it.

**Comment by nadeemkhoury** [comment]
Hi Guys, 
any update on this article? 
I tried a lot but didn't succeed.

**Comment by hikalkan** [comment]
Resolved by https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-mvc-ui-yt9b18io

Thanks to @ebubekirdinc :)
