### ISSUE TITLE
data seed error when using multi database.

### ISSUE THREAD

**Issue by SohyunKing** [abpframework/abp#5968]
I have 2 connect strings as follow:  
"ConnectionStrings": {
    "Default": "Server=localhost;Database=TaekwondoLocalTestMainDb;Uid=root;Pwd=admin123;",
    "AbpIdentityServer": "Server=localhost;Database=TaekwondoLocalTestIdsDb;Uid=root;Pwd=admin123;"
  },
and I have 2 migration project:
![image](https://user-images.githubusercontent.com/30038389/97386753-7dc1f880-190f-11eb-971d-50a3f0d60460.png)
migrate well but seed data report bug:
![image](https://user-images.githubusercontent.com/30038389/97386800-9df1b780-190f-11eb-9ec9-3b6f8de235d4.png)
The table "abpusers" should be "taekwondolocaltestidsdb.abpusers".
The "DbMigrationsForIds" project DbContext as follow:
![image](https://user-images.githubusercontent.com/30038389/97386972-02147b80-1910-11eb-9047-f2690370fa4a.png)

The database is MySql.Why this happen?What did I miss?

**Comment by maliming** [comment]
Have you read this document?

https://docs.abp.io/en/abp/latest/Entity-Framework-Core

**Comment by SohyunKing** [comment]
> Have you read this document?
> 
> https://docs.abp.io/en/abp/latest/Entity-Framework-Core

Yes,I had.

**Comment by SohyunKing** [comment]
> Have you read this document?
> 
> https://docs.abp.io/en/abp/latest/Entity-Framework-Core

I refers this document: https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations and this: https://docs.abp.io/en/abp/latest/Connection-Strings

**Comment by maliming** [comment]
We also have a demo for the document. You can check them both.

https://github.com/abpframework/abp-samples/tree/master/EfCoreMigrationDemo

**Comment by SohyunKing** [comment]
> We also have a demo for the document. You can check them both.
> 
> https://github.com/abpframework/abp-samples/tree/master/EfCoreMigrationDemo

Ok, thanks. I will view the demo first.

**Comment by SohyunKing** [comment]
I know the reason. I changed database struct, but forget to regenerate the migration. Ths.
