### ISSUE TITLE
Use NoTracking for readonly repositories for EF core

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#597]

**Comment by natiki** [comment]
- Will also improve performance

**Comment by solev** [comment]
@hikalkan @natiki 
I would like to implement this feature, if nobody else has started

**Comment by hikalkan** [comment]
I didn't started.

Currently, IReadOnlyRepository is just an interface and EfCoreRepository implements it in addition to other repository interfaces. So, the implementation is single. I'm not sure how to understand the client is using IReadOnlyRepository interface. We should think on that.

Before fully implementing it, it would be better to share your design idea so I can comment on it.

Thanks for your contribution :)

**Comment by solev** [comment]
From quickly looking at the code, I guess it needs to have a separate implementation, since it uses the default repository implementation right now.

**Comment by solev** [comment]
@hikalkan 
My initial idea is to create a separate implementation for readonly repositories. For example:

- Create **ReadonlyRepositoryBase** class in the **Domain**
- Create **EfCoreReadonlyRepository** that extends the class above in **EfCore**.

A simple diagram that I made: https://drive.google.com/open?id=1Lq_H9Vxsg2B0hVX1V1-kmwpo0nFdRyIU

The point here is that these classes will implement only Readonly funcionalities with **.AsNoTracking()** 
Here is an example of the implementation for Count only: https://prnt.sc/lr0ypw
I think you will get the idea for the rest of the functions.

Then we register the Readonly repositories with this implementations instead of the default ones.

This is just the initial idea, don't know if this will break something or if it will be a pain to implement. 
What do you think of this?

**Comment by hikalkan** [comment]
It's not a big problem for default repositories. It makes the registration progress complicated however it may be acceptable.

The problem is:

When you create a custom repository, you can replace default repositories with your implementation. If you override a base method and change it, it will be valid even if you inject IRepository (instead of IPersonRepository). That's a good advantage and provides consistency between repository interfaces. In fact, there will be a single implementation which exposes multiple interfaces (read only, basic... etc.).

If we separate implementations and want to prevent this behavior, then we need to create 2 implementation for our custom repository which is not good. 

The magic implementation may understand the client code is using read only interface and add .AsNoTracking() only in that case. This prevents duplication of implementation to just add a single statement. This magic may be implemented using dynamic proxying/decorator which only applied when dependency is resolved via a readonly interface. And current repository implementation may work in both ways. In this way, we may provide a way of using NoTracking manually even we inject a writable repository interface.

Alternative: All repository get/read methods may have an optional "noTracking" parameter (false by default).

Anyway, I am looking for an elegant solution that is easy to use, compatible with current features :)

**Comment by bbakermmc** [comment]
You can do it at the context level.  Might not make sense for everyone, but for us since we run SQL and can have a RO instance, we can send all the RO to that server, and all the CRUD to the primary.  

Note: for our example we need the other context so we can pass over another param in connection string "ApplicationIntent=ReadOnly"

```
using (var context = new ApplicationDbContext())
{
   context.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
   var students = context.Students.ToList();
   var course = context.Courses.FirstOrDefault();
}
```

**Comment by nev-21** [comment]
> > Alternative: All repository get/read methods may have an optional "noTracking" parameter (false by default).
> 
> This would get my vote or even extending the AbpRepositoryBase to have additional ReadOnly methods. I don't think there needs to be any magic. Practically the caller would know when they want to get a read only version and they as a side effect would get something that is faster.

Agree with @natiki, 

But IMHO,
if someone inject IReadOnlyRepository, its "get methods" must work with AsNoTracking by default. In the other hand, if some inject IRepository, its "get methods" must not have AsNoTracking by default.

If the "get methods" have the same name in both Interfaces, you should put a parameter to control NoTracking. In this case the default behaviour is lost, we can't put true as default in IReadOnlyRepository methods, and false as default in IRepository methods. A way to make this work, would be if someHow we could determinate if the dependency was resolved by a ReadOnly interface as @hikalkan said, then the parameter is not necessary.

> This magic may be implemented using dynamic proxying/decorator which only applied when dependency is resolved via a readonly interface.

If the "get methods" have different names, the default implementation will have the double quantity of get methods, some of them with ReadOnly prefix or postfix, when the developers inject IReadOnlyRepo, they only will use get readonly methods, and when they inject IRepository, they could use simple get methods or readonly methods, the explicity here is an advantage to read the code.

Also, the GetQueryableAsync and WithDetailsAsync must have readonly methods, which return IQueryable with AsNoTracking.

My conclusions:

- The use of the parameter does not make so much sense for developers when they use Repositories, why I must indicate a parameter if I'm already selecting an Interface?.
- (*)The use of different methods for each interface, will enforce explicitness (which is an advantage for code reading), and avoid the use of reflection or something to know how the dependency was resolved
- There should be only one implementation to be able to make a custom default implementation easy.

I Vote for the (*) solution.

Thanks for this great framework

**Comment by hikalkan** [comment]
I have solution offer. It doesn't add any parameter and doesn't change usage of repositories. Let me explain it:

### Background information

Current repository interfaces

* `IReadOnlyBasicRepository `
* `IReadOnlyRepository` (inherits `IReadOnlyBasicRepository`)
* `IBasicRepository` (inherits `IReadOnlyBasicRepository`)
* `IRepository` (inherits `IReadOnlyRepository` and `IBasicRepository`)

So, we have two readonly repository interfaces:

* `IReadOnlyRepository`
* `IReadOnlyBasicRepository`

### Implementation

#### (1) Introduce IRepository.IsReadOnly property

Define `IRepository.IsReadOnly` property, which is `false` by default.

#### (2) Register readonly repositories with factory method

In the `ServiceCollectionRepositoryExtensions.RegisterService` method, register **readonly repositories** with a factory method with the following logic;

If the given `implementationType` implements `IRepository`, and the currently registering `serviceType` is `IReadOnlyRepository`, then register with a factory method that internally resolves the service with `IRepository` then sets `IRepository.IsReadOnly` to `true`.

I will show an example to give you an idea:

````csharp
services.TryAddTransient(typeof(IReadOnlyRepository<User, Guid>), serviceProvider =>
{
    var repositoryObject = serviceProvider.GetRequiredService<IRepository<User, Guid>>();
    repositoryObject.IsReadOnly = true;
    return repositoryObject;
});
````

This example assumes that `IRepository<User, Guid>` was registered. No problem, because it is already registered by `ServiceCollectionRepositoryExtensions.AddDefaultRepository` method. Also, I wrote the example with concrete types, but you will implement it with a lot of reflection code.

#### (3) Use `IsReadOnly` in `EfCoreRepository` class 

Call `AsNoTracking()` while querying from database if `IsReadOnly` is `true`. Also, it will be good to introduce and throw `RepositoryIsReadOnlyException` if write method are called on a readonly repository.

**Comment by hikalkan** [comment]
@maliming check my proposal and implement this is it doesn't break anything.
