### ISSUE TITLE
Creating a base class to inherit from AbpController routing is invalid

### ISSUE THREAD

**Issue by l494422810** [abpframework/abp#5972]
Use version 3.2.1 to customize a base class ApiBaseController to inherit from AbpController, define Route [Route(" API /[Controller]/[Action]")],Controller inherits ApiBaseController to be directly accessible, not after upgrading to 3.3.0, error code 404

[ApiController]
[Route("api/[controller]/[action]")]
public class ApiBaseController : AbpController

**Comment by maliming** [comment]
hi

* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by hikalkan** [comment]
Make your `ApiBaseController` `abstract`. It is probably related to https://github.com/abpframework/abp/issues/5964
