### ISSUE TITLE
[Question] Why AbpDbContext default service lifetime is Transient?

### ISSUE THREAD

**Issue by h82258652** [abpframework/abp#5976]
Hello, I'm updating my old asp.net core with abp.

I have some code like this:
```C#
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }
}

public class TestService
{
    public TestService(AppDbContext context)
    {
        DbContext = context;
    }

    public AppDbContext DbContext { get; }
}

public class TestController : ControllerBase
{
    private readonly AppDbContext _context;
    private readonly TestService _testService;

    public TestController(AppDbContext context, TestService testService)
    {
        _context = context;
        _testService = testService;
    }

   [HttpGet]
   public void Get()
   {
       bool b = object.ReferenceEquals(_context, _testService.DbContext);
       Debugger.Break();
   }
}
```
The variable ```b``` is ```true``` means they are the same instance.
But while I change:
```diff
- AppDbContext : DbContext
+ AppDbContext : AbpDbContext<AppDbContext>
```
and in ```Startup```
```diff
- service.AddDbContext<AppDbContext>(/* ... */);
+ service.AddAbpDbContext<AppDbContext>(/* ... */);
```
I found the variable ```b``` is ```false```.
I search the abp source code and found AbpDbContext implemented ```ITransientDependency``` interface. [link](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L35)

Now I add ```DependencyAttribute``` to solve this problem.
```C#
[Dependency(ServiceLifetime.Scoped, ReplaceServices = true)]
public class AppDbContext : AbpDbContext<AppDbContext>
```

I have checked the document but did not found anything about why the lifetime of ```AbpDbContext``` is transient.

**ABP Framework version**: v3.2.1.

**Comment by realLiangshiwei** [comment]
You should not directly inject the database context, it is controlled by the unit of work : https://docs.abp.io/en/abp/latest/Unit-Of-Work

**Comment by h82258652** [comment]
@realLiangshiwei Thanks for the answer, got it. It means the database context will be maintained by the UoW. By the way, are there any documents for integrating abp with the original asp.net core? I'm worried about there are lots of break changes after I update my old asp.net core project.

**Comment by realLiangshiwei** [comment]
No such document yet, you just need to use repository instead of the database context
