### ISSUE TITLE
[Question] How to generation/ add a new module in  "Microservice-Demo" sample with abp CLI

### ISSUE THREAD

**Issue by LearnGrowAndShare** [abpframework/abp#5977]
Hi, 

Thanks for providing such an extensive documentation for the microservices implementation with ABP  module system.

I went through the documentation at 
1) https://docs.abp.io/en/abp/latest/Samples/Index
2)  https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo
3) https://docs.abp.io/en/abp/latest/CLI#add-module

Lets say I have to add a new module  "Order Mangement" to "Microservice-Demo" sample,  how to acheive it without manually copying the product sample and renaming it :( 

I tried - 
```
1)  abp new OrderManagement -csf false -m --no-ui 
2)  abp add-module OrderMangement -- this will not work because there is not module exist with name OrderMangement 
```

Any suggestion would be appreciated.

**Comment by realLiangshiwei** [comment]
`add-module` only applies to official modules, but the CLI is open source, you can fork and change it.
