### ISSUE TITLE
Changing existing module Primary key to composite key

### ISSUE THREAD

**Issue by rlavaud** [abpframework/abp#5978]
Hi All
I know that I can add new field to existing module using OneTimeRunner.Run but is there a way to override/change the primary key and force it to be composite key?
For example the PK for AbpIdentity user is ID, is there a way to change it without creating a new module to be (ID, TenantID)?

**Comment by realLiangshiwei** [comment]
Changing the primary key type is a big change. The module is still using the old primary key type. anyway, you need to change the module source code.

**Comment by rlavaud** [comment]
So best thing to do is to copy the module and make the changes there correct?
