### ISSUE TITLE
ABP Commercial Getting Started documentation for Blazor possibly incorrect?

### ISSUE THREAD

**Issue by 20bc** [abpframework/abp#5981]
Dear all,

I'm new to ABP.IO (just bought the licence yesterday night) and GitHub (just created an account to post this!). Please accept my apologies in advance for any gaffes.

I have spent a significant time trying to get the ABP Commercial Blazor EF Core Non-tiered version 3.3 to work, but with no luck. I've also tried to follow the ABP Opensource steps for Blazor. I strongly suspect that there is some issue with either the generated code or the last part of page 1 (Run the application) of the [documentation](https://docs.abp.io/en/commercial/latest/getting-started?UI=Blazor&DB=EF&Tiered=No). I executed the Razor-EF-Non-tiered without any problem.

'Running the HTTP API Host (Server Side)' part works correctly, and it opens the Swagger UI. However, this is immediately followed by 'Running the Blazor Application (Client Side)' which keeps failing. **There seems to be a step/instruction missing here.** So far I have tried:
- Opening two distinct VS instances. Execute .HttpApi.Host with one and .Blazor with the other.
- Different combinations of trying to run these two projects simultaneously, or one after another.

Mostly it goes into an infinite "loading..." screen. At times I can see the landing page (when I've logged into Swagger UI as admin) but nothing after that. I hope it is something simple that I am (or the documentation is) missing. I did appreciate someone looking at the documentation and guiding me. If the documentation and ABP Suite code generation is alright, then I can provide the exact steps and the details of exceptions and errors on chrome-console.

On another note, the solution is for Blazor WebAssembly. Any plans for this to work for Blazor Server? I'm so excited about Blazor, but the load time etc. seems daunting. Javascript etc. isn't my cup of tea.

Many thanks,
B

**Comment by realLiangshiwei** [comment]
Hi, please create a question on the commercial support website: https://support.abp.io/QA/Questions : )

**Comment by 20bc** [comment]
Hi @realLiangshiwei 

I realised that several issues/errors/exceptions that I am facing boils down to one thing - the Blazor WebAssembly template is **dead slow**. I'm sure this must be a known issue. If yes, is there WIP on it and when do you expect to fix it? Most importantly, is there a plan to provide an option for **Blazor Server**-side soon? Can you kindly clarify?

I love what you have created. It will be heartbreaking if the ABP Blazor UI doesn't catch up with its Razor counterpart soon.

Kind regards,
B

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/5517
