### ISSUE TITLE
VoloDocs Migrate failure

### ISSUE THREAD

**Issue by Amber-Wish** [abpframework/abp#5985]
After I configured the database link string, I ran Migrate.bat. The following error occurred.
![image](https://user-images.githubusercontent.com/55867470/97537811-5d229d00-19fa-11eb-93d6-58aa5e6c4c1e.png)
![image](https://user-images.githubusercontent.com/55867470/97537925-88a58780-19fa-11eb-9cdf-c7888e36bd2f.png)

**Comment by maliming** [comment]
The error message is very clear.
![image](https://user-images.githubusercontent.com/6908465/97538072-c86c6f00-19fa-11eb-84e2-0d83bae1834c.png)

**Comment by Amber-Wish** [comment]
![image](https://user-images.githubusercontent.com/55867470/97539080-5dbc3300-19fc-11eb-812d-409211ac658b.png)
![image](https://user-images.githubusercontent.com/55867470/97539122-690f5e80-19fc-11eb-84bf-2d923e9123f0.png)
Is this parameter not supported? If so, how to configure the port number?

**Comment by DonVliet** [comment]
Try using:

Server=myServerAddress, 3306; Database=myDatabase, User=myUsername; Password=myPassword;

where 3306 is the port number (MySQL default)

**Comment by maliming** [comment]
You're using `Sql Server`.

![image](https://user-images.githubusercontent.com/6908465/97576282-ebae1300-1a28-11eb-945d-8d46ba6cb844.png)

**Comment by DonVliet** [comment]
If you want to use MySQL as your database there are a few changes you will need to do, including deleting and recreating the Migrations to support MySQL.

https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL
