### ISSUE TITLE
Volo.Abp.EventBus.Rebus not mapping EventName to RoutingKey in RabbitMQ

### ISSUE THREAD

**Issue by volethanh** [abpframework/abp#5992]
Hi,

I've downloaded the sample Abp Rebus, I've got a problemt that the `EventName` defined in the class Eto not mapping to RoutingKey in RabbitMq

![image](https://user-images.githubusercontent.com/46510130/97674666-7e4dc100-1ac0-11eb-8fc3-a507ad61a70b.png)

**Comment by realLiangshiwei** [comment]
Hi, this is the design of rebus.
