### ISSUE TITLE
Creating a new UI theme by copying the Basic Theme (for Blazor)

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#5993]
Would it be possibly to have an article similar to the one for MVC theming document? A sample and community article would also be good i.e. create a new solution, copy the Basic Theme into the solution, change NuGet package references to local project references and customize the theme a bit to demonstrate it

**Comment by hikalkan** [comment]
Thanks you for the suggestion. However, I had already opened that before: https://github.com/abpframework/abp/issues/5965 :)

**Comment by hikalkan** [comment]
Oh, I see this is blazor, sorry :)

**Comment by hikalkan** [comment]
Why did you close this? I think it is still useful to write such an article.

**Comment by nadeemkhoury** [comment]
Hi Guys, 
any update on that article ? 
I spent all day without any success to make it work.

**Comment by Mijalski** [comment]
Please do :) I am waiting on the edge of my seat. As of now I can't even change the bootstrap blazorise provider to other ones.

**Comment by ebubekirdinc** [comment]
Check [this](https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b) article at ABP community.

**Comment by maliming** [comment]
https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b
