### ISSUE TITLE
CurrentUser is treated as authenticated after logging out in custom nav-items.component

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#6002]
3.2 / Angular

After logging out, `CurrentUser` is still treated as `IsAuthenticated` in custom `nav-items.component`. As a result, the method which is supposed to be triggered for authenticated user only, triggered (returning 401 error):

  ```
ngAfterViewInit() {
    ...
    this.currentUser$
      .pipe(take(1))
      .subscribe((currentUser: ApplicationConfiguration.CurrentUser) => {
        // TODO: even after logging out the user is considered authenticated!
        if (currentUser?.isAuthenticated) {
          console.log('user is still alive');
          this.store.dispatch(new GetTenantsForCurrentUser());
        }
      });
  }

  logout() {
    console.log('initiate logout');
    this.authService.logout().subscribe(() => {
      console.log('logout complete');
      this.router.navigate(['/'], { state: { redirectUrl: this.router.url } });
      this.store.dispatch(new StateReset(TenantsState));
    });
  }
```
![image](https://user-images.githubusercontent.com/6149843/97783648-e1fbeb00-1ba1-11eb-9c78-1c9dc76caaf1.png)

**Comment by bnymncoskuner** [comment]
Hello @alexandis,

I have not been able to reproduce the problem with our app template (and custom nav-items). Could it be related to your custom actions? Also, if you can provide us a simple repo that reproduces the issue, we will fix it.

**Comment by alexandis** [comment]
> Hello @alexandis,
> 
> I have not been able to reproduce the problem with our app template (and custom nav-items). Could it be related to your custom actions? Also, if you can provide us a simple repo that reproduces the issue, we will fix it.

Hi. It's a bit tricky to provide a whole working example, since it's a part of a large project. Probably, something is wrong with my implementation of **nav-items.component.ts**? Attached below is whole src (just in case), but please have a look at **nav-items.component.ts** inside:

[Angular.src.zip](https://github.com/abpframework/abp/files/5546074/Angular.src.zip)

**Comment by alexandis** [comment]
Hi, any progress on it?

**Comment by bnymncoskuner** [comment]
Hello @alexandis,

Sorry for late response. Do you use password flow or code flow as authentication method? 

If so, password flow is deprecated in v3 and removed in v4. We've published a blog post couple of months ago about this topic. You can find it [here](https://blog.abp.io/abp/ABP-Framework-v3.1-RC-Has-Been-Released)

**Comment by alexandis** [comment]
Hi. We use code flow. What about the source code i've attached? Does everything look right in **nav-items.component.ts** implementation from tenant reading prospective? Please note: the reported error takes place after pressing "Logout", but before a user is redirected back to login form. In our case, the error can be seen if "Preserve log" is turned on in the browser to see all requests between logging off and redirecting to login page.

**Comment by bnymncoskuner** [comment]
Hello again,

I've downloaded your code and tried to run it with our template but your code is too complex and missing the proper backend APIs. So, it is really hard for me to make any sense of it. If you could provide a minimal repo (with angular and backend) that reproduces your problem, I'd check it out.
