### ISSUE TITLE
How to integrate GraphQL (HotChocolate.AspNetCore) into abp framework application

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#6007]
Hi, I'm attempting to add GraphQl to abp framework 3.30 but I'm getting the error below.  I'm using HotChoclate (GraphQL server implementation) pure code first implementation. 

**I'm looking for advice on how to implement graphql with abp framework, below is just to show what I have tried.**

In the startup --HttpApiHostModule.cs I've added this to the ConfigureServices method
 
`

      context.Services.AddGraphQL(
                SchemaBuilder.New()
                    .AddQueryType<Query>()
                    .Create(),
                new QueryExecutionOptions { ForceSerialExecution = true });

`
 

and this below app.UserRouting() in the OnApplicationInitialization method;

`    

     app.UseGraphQL();
         app.UsePlayground();

`
 
These is the Query class...

`    

    public class Query {
        [UsePaging]
        [UseSelection]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Student> GetTravelClasses([Service] IRepository<Student> studentR) {
            return studentR;
        }
    }

`

**ERROR** when I run the application
HotChocolate.SchemaException: Unable to resolve type reference Output: System.Object[]. - Type: Student

I referenced this tutorial using graphql (hotchocolate) in a standard .net core application. [https://dev.to/michaelstaib/get-started-with-hot-chocolate-and-entity-framework-e9i]

**Comment by rygar08** [comment]
I've discovered that when my Student class inherits Volo.Abp.Domain.Entities.Entity<int> I get this error... 'HotChocolate.SchemaException' in HotChocolate.Types.dll.  If I remove the Entity<int> inheritance everything works fine. However, I need my Entities to inherit from Volo.Abp.Domain.Entities.Entity so the can be used with the IRepository<> interface.

**Comment by rygar08** [comment]
Hotchocolate had an issue with the GetKeys() function in the inherited Volo.Abp.Domain.Entities.Entity class. I got it working my configuring the schema to ignore the GetKeys() function.

` 

    public class Query {
         
        [UseSelection]
        public IQueryable<Students.Student> GetStudents([Service] IRepository<Students.Student> studentR) { 
            // var rrr = studentR.ToList();
            return studentR;
        }
    }

    public class StudentType : ObjectType<Students.Student> {
        protected override void Configure(IObjectTypeDescriptor<Students.Student> descriptor) {
            descriptor.Field(f => f.GetKeys()).Ignore();
        }
    }
 
`

Add the BindClrType on startup. 
`

     public override void ConfigureServices(ServiceConfigurationContext context) {
           
            context.Services.AddGraphQL(
                SchemaBuilder.New() 
                    .AddQueryType<Query>()
                    .BindClrType<Student, StudentType>() 
                    .Create(),
                new QueryExecutionOptions { ForceSerialExecution = true });

        }


`

**Comment by Damon-cxl** [comment]
@rygar08 ,Hi, when used Abp IRepository , I got a exception like this:

- Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.

Looking forward for you help!

**Comment by rygar08** [comment]
@Damon-cxl , I also came across this issue on abp version 4. Abp version 3.2.1 works fine. Unfortunately I had to roll my application back to abp 3.2.1 which is a concern because the abp framework community does not appear to have any priority for graphql integration. I wish they would.

**Comment by gdlcf88** [comment]
Please see: https://github.com/abpframework/abp/issues/86#issuecomment-1001041045
