### ISSUE TITLE
RemoteLocalizationContributor is using ICachedApplicationConfigurationClient that will be released.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#6011]
`RemoteLocalizationContributor `gets the `ICachedApplicationConfigurationClient `service through `context.ServiceProvider`, but `context.ServiceProvider` is scoped.

There will be a problem here if the service dependent in `ICachedApplicationConfigurationClient` uses `IServiceProvider or IServiceScopeFactory`.

https://github.com/abpframework/abp/blob/b8216daeb5693837b8c8fbec0b4c2b85df66d89c/framework/src/Volo.Abp.Localization/Volo/Abp/Localization/AbpStringLocalizerFactory.cs#L61-L69

https://github.com/abpframework/abp/blob/11a3903968cdae378eeed24848346b94521951a5/framework/src/Volo.Abp.AspNetCore.Mvc.Client.Common/Volo/Abp/AspNetCore/Mvc/Client/RemoteLocalizationContributor.cs#L16-L22

**Comment by hikalkan** [comment]
I removed the scope. This doesn't cause memory leak since the string localizers are already cached.
