### ISSUE TITLE
Initial Loading animation for the Blazor UI Basic Theme

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6019]
Insted of [the "Loading..." text](https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Blazor/wwwroot/index.html#L21), can we make a better loading animation for the initial page load (only for the first time, not for every page switch)?

**Comment by stsrki** [comment]
Yes, it's an easy thing to do. I have the same thing on Blazorise demo pages.

**Comment by stsrki** [comment]
@hikalkan  Would any of this animation be good? https://tobiasahlin.com/spinkit/
