### ISSUE TITLE
Link problem for docs module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#602]
```
[Xamarin (mobile)](Xamarin.md)
```
link is not properly working. It goes to Xamarin.md URL. Not removing .md extension on the URL. Probably because the "mobile" text is inside parentheses.

**Comment by ebicoglu** [comment]
Provide the link please...
![image](https://user-images.githubusercontent.com/9526587/49715795-88fbd480-fc62-11e8-8b26-e03ffdb31d21.png)

**Comment by hikalkan** [comment]
I changed to make it working. Try a link like
````
[Xamarin (mobile)](Xamarin.md)
````
and it was not working.
