### ISSUE TITLE
Better design for Blazor UI message/confirm dialogs

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6027]
Current design should be improved.

![image](https://user-images.githubusercontent.com/1210527/97962361-0df7b600-1dc6-11eb-8278-726aef5c46ee.png)

**Comment by hikalkan** [comment]
@stsrki we think the following design changes would be better:

* Centralize the icon and text
* Move Cancel button to the right side (near to Yes)

**Comment by hikalkan** [comment]
Can you also add screenshots of the different message types (error, warn...), so @armgnunlu can see the icons/design.

**Comment by stsrki** [comment]
@armgnunlu 

![image](https://user-images.githubusercontent.com/900302/98098552-cbe67700-1e8e-11eb-96bc-1809e757e26d.png)

![image](https://user-images.githubusercontent.com/900302/98098576-d274ee80-1e8e-11eb-9e11-3012e2b61b00.png)

![image](https://user-images.githubusercontent.com/900302/98098598-d739a280-1e8e-11eb-864c-a8312938146c.png)

![image](https://user-images.githubusercontent.com/900302/98098617-dd2f8380-1e8e-11eb-84e5-74db6edd2ae1.png)

![image](https://user-images.githubusercontent.com/900302/98098630-e1f43780-1e8e-11eb-81b2-8834aca421c3.png)
