### ISSUE TITLE
Blazor UI: Improvements for the UI notifications

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6028]
![notification](https://user-images.githubusercontent.com/1210527/97895273-a0f00c00-1d44-11eb-8711-35ad921d1d34.png)

* Toast message should have a "x" icon to dismiss the notification
* Should not dismiss the notification on click. I think clicking on it even may cause to show the message a longer time.

**Comment by stsrki** [comment]
https://github.com/stsrki/Blazorise/issues/1482
