### ISSUE TITLE
Blazor: Message/Confirm dialogs should not close on click outside of the modal

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6029]
Should not close the dialog when we click outside of the modal. Otherwise, user may accidently click without reading an important message.

![message-box](https://user-images.githubusercontent.com/1210527/97895174-8027b680-1d44-11eb-8aeb-290b2808c0ed.png)

**Comment by stsrki** [comment]
@hikalkan Can you please explain why closing a modal is wrong? For me, this feels like a perfectly good approach from a UX perspective. When you press the ESC key or click on backdrop it is basically the same as you click the **Cancel** button. The user cannot confirm any operation by doing that. He just cancels it.

**Comment by wakuflair** [comment]
Is this already fixed?
In ABP 4.0 final I still can close the modal by clicking outside it.

**Comment by wakuflair** [comment]
Oh the commit only fixed the message/confirm dialogs.
But other modal dialogs(create or edit, etc) should also have this behaviour, otherwise users may lost their data accidentally.

**Comment by stsrki** [comment]
@wakuflair We can create a new specialized modal, maybe `CrudModal` that has this kind of behavior.

@hikalkan Can you create a new ticket for this? This `CrudModal` can also later be used as part of a milestone to create forms dynamically.
