### ISSUE TITLE
Blazor UI: DataGrid Row selections should be lighter

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6031]
Currently, it makes the text unreablable in some cases.

![table-selections](https://user-images.githubusercontent.com/1210527/97895685-2a9fd980-1d45-11eb-9c01-ac3ddf637f72.png)

Also, there is no way to remove highlighting once we click on a row. I think a second click can remove the higlighting. You can consider this as an improvement point on blazorize.

**Comment by stsrki** [comment]
https://github.com/stsrki/Blazorise/pull/1461
