### ISSUE TITLE
Provide configurable settings to MongoClient

### ISSUE THREAD

**Issue by mtozlu** [abpframework/abp#6036]
`MongoClient` takes url or `MongoClientSettings` object on initialization. Currently abp initializes `MongoClient` with url. 
Can we add functionality to initialize with `MongoClientSettings` object with the ability to configure it in our abp module initialization?

This will allow low level customization of mongo connection with many options such as cluster configuration, eventing, monitoring, logging, etc. Details can be found here:
https://mongodb.github.io/mongo-csharp-driver/2.11/reference/driver/connecting/#mongo-client

This issue is also related to #4886

**Comment by maliming** [comment]
hi @mtozlu  I will check it.
