### ISSUE TITLE
Swagger exception when overriding Controller class

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#6037]
3.2 / Angular

I have followed your guide to override AccountController. 
Probably it's a normal behavior to have the following error - 

> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Conflicting method/path combination "POST api/account/reset-password" for actions - Volo.Abp.Account.AccountController.ResetPasswordAsync (Volo.Abp.Account.Pro.Public.HttpApi),AbxEps.CentralTools.Controllers.CentralToolsAccountController.ResetPasswordAsync (AbxEps.CentralTools.HttpApi). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround

 - I just wonder why Swagger can't see I override the Controller - so this class needs to be taken into consideration when checking endpoints, not overriden class?

    ```
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(AccountController))]
    public class CentralToolsAccountController : AccountController
    {
        private readonly IAbxUserAppService _abxUserAppService;

        public CentralToolsAccountController(
            IAccountAppService accountAppService,
            IVirtualFileProvider virtualFileProvider,
            IAbxUserAppService abxUserAppService)

            : base(accountAppService, virtualFileProvider)
        {
            _abxUserAppService = abxUserAppService;
        }

        public override async Task ResetPasswordAsync(ResetPasswordDto input)
        {
            await _abxUserAppService.UpdatePasswordAsync(
                input.UserId, new IdentityUserUpdatePasswordInput { NewPassword = input.Password });

            await base.ResetPasswordAsync(input);
        }
    }


So do I really need to use `ConflictingActionsResolver` here?

**Comment by realLiangshiwei** [comment]
Hi, see https://github.com/abpframework/abp/issues/5269

This feature was completed in v3.3. I think you need to upgrade your project.

**Comment by alexandis** [comment]
Is there some temporary solution to make it work till we upgrade? Upgrade takes time and we're not ready to it - we've just updated to 3.2 lately.

**Comment by realLiangshiwei** [comment]
You can manually copy [the code](https://github.com/abpframework/abp/commit/71b1384598128b7432491422f1b64837c7fb97af) into your project

**Comment by alexandis** [comment]
I have tried that (3 custom files), but in result getting this exception when submitting e-mail in "Forgot password" (type is null here). Any thoughts?

![image](https://user-images.githubusercontent.com/6149843/98013020-78c6e280-1e02-11eb-8a7a-6498ab9dfc20.png)

**Comment by alexandis** [comment]
Probably, those 3 files to override are not enough? I can see you are using `AbpController` constructor with one parameter, however in 3.2 we have this:

`public AccountController(IAccountAppService accountAppService, IVirtualFileProvider virtualFileProvider);`

Looking at new `AccountController`, I realize there are too many changes (affected files - i.e. changing `AccountController` signature will require yet another changes / break something in current 3.2 solution, etc.) to be done to fix this little thing... I am close to give up :(

UPDATE: as a last resort, I've tried to override `AccountAppService`, but for some reason it does not work either (looks like override does not happen), I've tried both approaches to replace a service described in ABP guide - via `AddTransient ` and _attributes_:

    [Authorize]
    public class CentralToolsAccountAppService : AccountAppService
    {
        private readonly IAbxUserAppService _abxUserAppService;

        public CentralToolsAccountAppService
        (
            IdentityUserManager userManager,
            IAccountEmailer accountEmailer,
            IAccountPhoneService phoneService,
            IIdentityRoleRepository roleRepository,
            IdentitySecurityLogManager identitySecurityLogManager,
            IBlobContainer<AccountProfilePictureContainer> accountProfilePictureContainer,
            ISettingManager settingManager,
            IAbxUserAppService abxUserAppService
        )
            : base(
                userManager,
                accountEmailer,
                phoneService,
                roleRepository,
                identitySecurityLogManager,
                accountProfilePictureContainer,
                settingManager
            )
        {
            _abxUserAppService = abxUserAppService;
        }

        public override async Task ResetPasswordAsync(ResetPasswordDto input)
        {
            await _abxUserAppService.UpdatePasswordAsync(
                input.UserId, new IdentityUserUpdatePasswordInput { NewPassword = input.Password });

            await base.ResetPasswordAsync(input);
        }
    }

**Comment by realLiangshiwei** [comment]
I suggest you upgrade to version 3.3 or you can compare the difference between the 3.3 and 3.2 versions and manually replace the implementation
