### ISSUE TITLE
Use AbpSwaggerUi for all modules and templates

### ISSUE THREAD

**Issue by mtozlu** [abpframework/abp#6040]
With #5728 and #5864 `UseAbpSwaggerUi` is used by some of the templates however some modules and `HttpApi.Host` project in app template is not updated so using swagger for operations that needs CSRF token causes error in those projects.
Here is the list that is not updated;
![image](https://user-images.githubusercontent.com/2939330/97997352-c92d4880-1de0-11eb-9c96-307fa06e9e22.png)

**Comment by realLiangshiwei** [comment]
Hi, this is intentional. You can directly use the client's(`Web`) swagger page.

**Comment by mtozlu** [comment]
If you use app template with angular ui, the solution does not contain any `Web` project (`MyCompanyName.MyProjectName.HttpApi.HostWithIds` template). Even if it did, using swagger to do some operation that needs a CSRF token, the api gives error:
> The required antiforgery header value "RequestVerificationToken" is not present.

**Comment by realLiangshiwei** [comment]
Related https://github.com/abpframework/abp/pull/6124
