### ISSUE TITLE
I hope Volo.Abp.Http.Client remove  Volo.Abp.MultiTenancy related references

### ISSUE THREAD

**Issue by rocleegithub** [abpframework/abp#6042]
Because I don't need tenant functionality for some projects，From a design point of view, the tenant function is redundant here。

**Comment by realLiangshiwei** [comment]
Hi,

https://github.com/abpframework/abp/blob/6a04461ddbce181f64ff16aa8c3bf9344bba815f/framework/src/Volo.Abp.Http.Client/Volo/Abp/Http/Client/DynamicProxying/DynamicHttpProxyInterceptor.cs#L220

It will add the tenant to the request header, which is essential for multi-tenant applications

ABP is a multi-tenant framework. It needs to consider multi-tenancy globally. So I think it cannot be removed. If you don't need multi-tenancy, just disable it.

**Comment by rocleegithub** [comment]
> Hi,
> 
> ABP is a multi-tenant framework. It needs to consider multi-tenancy globally. So I think it cannot be removed. If you don't need multi-tenancy, just disable it.

Multi-tenancy refers to the entire framework, but this component alone may not be needed;
I tracked the existing project application and found the Volo.abp.Settings,
Volo.Abp.Settings can split the other one  Volo.Abp.Settings.MultiTenancy

DynamicHttpProxyInterceptor.cs can add a virtual method custom supplement；Then put it into the new component Volo.Abp.Http.Client.MultiTenancy
