### ISSUE TITLE
Can you integrate GRPC communication between microservices?

### ISSUE THREAD

**Issue by mingyangzhu** [abpframework/abp#605]

**Comment by natiki** [comment]
What are your requirements? Ultimately there is a distributed message bus https://github.com/abpframework/abp/blob/master/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/Distributed/IDistributedEventBus.cs which you would use for this kind of thing.

**Comment by mingyangzhu** [comment]
Thank you for your reply, the event-driven approach is also an implementation. I will take the liberty to ask, will you integrate a communication framework like grpc later?

**Comment by natiki** [comment]
@mingyangzhu What pattern are you referring to with grpc? Have you got a URL we can read more about it?

**Comment by mingyangzhu** [comment]
Functional modules like this: https://github.com/GameBelial/Abp.Grpc.

**Comment by hikalkan** [comment]
Hi,

We are developing dynamic C# proxies to call REST APIs of other microservices. Didn't know the Abp.Grpc project. Will take a look. Thanks.

**Comment by mingyangzhu** [comment]
Ok，Thanks for your reply。

**Comment by mingyangzhu** [comment]
https://github.com/reactiveui/refit   The automatic type-safe REST library for .NET Core, Xamarin and .NET

**Comment by brunobertechini** [comment]
I would consider not using consul / Grpc due to several reasons, but most important: Both concepts are assuming one microservice can "talk" to another microservice.

This is a design flaw that creates runtime coupling. There are several threads discussing how this can harm a distributed system.

**Comment by geffzhang** [comment]
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

**Comment by LGinC** [comment]
1.1 or 1.2 will support gRPC?

**Comment by hikalkan** [comment]
Didn't have a plan for 1.1 or 1.2, so can't promise. But it has high priority among the backlog items.
Our first priority is to complete documents, because adding more feature without documentation has no meaning.

**Comment by leonkosak** [comment]
Any "dev documentation" for Distributed Event Bus?

**Comment by LGinC** [comment]
> Any "dev documentation" for Distributed Event Bus?

https://github.com/abpframework/abp/tree/dev/samples/RabbitMqEventBus

**Comment by leonkosak** [comment]
Thanks.
Is this useful also for inter-**module** communication?

**Comment by LGinC** [comment]
> Thanks.
> Is this useful also for inter-**module** communication?

Yes,I had tried it

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/2882
