### ISSUE TITLE
Separate design for login page for each Tenant

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#6055]
We need to be able to design a different login page for each Tenant. Is this possible?

**Comment by maliming** [comment]
This is possible. You can override the default login page code and change it according to the current tenant Id.

https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface

**Comment by DonVliet** [comment]
Thanks, but I was thinking about a completely different design for each Tenant so that each customer can have their own branded login page.

**Comment by maliming** [comment]
You can also refer to this https://github.com/abpframework/abp/issues/1092
