### ISSUE TITLE
ABP authentication failing cross framework - dotnet core vs .net framework

### ISSUE THREAD

**Issue by AnkitSource** [abpframework/abp#6057]
I want to reuse users (AbpUsers) records that have been created using ABP dotnet core solution but in .net framework based ABP solution, login is failing because password is not matching.

Is there a difference in the Hashing mechanism in dotnet core vs .net framework?

**Comment by maliming** [comment]
Try setting the Identity Core's password mode to V2?
```
services.Configure<PasswordHasherOptions>(options =>
{
	options.CompatibilityMode = PasswordHasherCompatibilityMode.IdentityV2;
});
```

**Comment by AnkitSource** [comment]
Thanks for your input @maliming !!
Can I have reverse of it help. I meant my original solution is in core (asp.net identity v3) and I need those hashed passwords to be reused in .net framework (asp.net identity v2.2.1) based solution.
Sample password looks like AQAAAAEAACcQAAAAExxxxxxxx

**Comment by maliming** [comment]
I think you can replace the `passwordhasher`, please refer to the relevant documents or check the source code of Identity, which has nothing to do with ABP.

https://andrewlock.net/exploring-the-asp-net-core-identity-passwordhasher/
https://andrewlock.net/migrating-passwords-in-asp-net-core-identity-with-a-custom-passwordhasher/

**Comment by AnkitSource** [comment]
Hi @maliming 
I understand the hashing formats better now, Thanks for sharing those links. I am now verifying the passwords (PasswordHasher.VerifyHashedPassword) using Microsoft.AspNetCore.Identity instead of Microsoft.AspNet.Identity and it is working fine, It was a great help!! Thank you again 👍

**Comment by maliming** [comment]
You are welcome.
