### ISSUE TITLE
Change AuditLog ApplicationName on the go

### ISSUE THREAD

**Issue by nishadebrahim** [abpframework/abp#6063]
Hi, As per the Abp.io document, the following code is written in ApiHttpApiHostModule.cs

private void ConfigureAuditLogs()
        {
            Configure<AbpAuditingOptions>(options =>
            {
                options.IsEnabledForGetRequests = true;
                options.ApplicationName = _appConfiguration["Properties:LegoBlockId"];
                options.EntityHistorySelectors.AddAllEntities();
            });
        } 

But i need to change the ApplicationName later as i am getting this from the header in a later time. Is there any way to change it from other class down the line.

Abp.io version 2.9.

 **abp**

**Comment by maliming** [comment]
You can try to rewrite the IAuditingHelper to use the dynamic `ApplicationName` instead of `option.ApplicationName `

https://github.com/abpframework/abp/blob/1da901ee156d82ade03ecc9aa984a85da884d5dc/framework/src/Volo.Abp.Auditing/Volo/Abp/Auditing/AuditingHelper.cs#L132
