### ISSUE TITLE
What's the difference between ABP's modularization and class library

### ISSUE THREAD

**Issue by zfeihong** [abpframework/abp#6064]
### Dear ABP：
What's the difference between ABP's modularization and class library，Like projects or DLLs? Since ABP's reference has been added, why do you need to depend on it? Is it a little redundant?
——Thank you for reading

**Comment by maliming** [comment]
> Since ABP's reference has been added, why do you need to depend on it? Is it a little redundant?

If we don't use `DependsOn`, do you think we have to scan all assemblies?

What if I just want to use assembly constants instead of depends on this module?

How can I check the dependent modules of a module? ......

https://docs.abp.io/en/abp/latest/Module-Development-Basics
