### ISSUE TITLE
CurrentUser parsing failed from verssion 3.3.x

### ISSUE THREAD

**Issue by aizhule** [abpframework/abp#6068]
The access_token obtained using password authorization passed the [Authorize] verification, but the attributes of ICurrentUser were not resolved.
as the picture shows:
![image](https://user-images.githubusercontent.com/38711506/98212322-61146900-1f7e-11eb-9d6d-5cd3de0135a0.png)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.
