### ISSUE TITLE
Using MyProject.HttpApi

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#6073]
Hi,

I want to use MyProject.HttpApi for my extra API.
i've created à controller inside the project, but when i lunch the App, i don't find my API (Controller) in Swagger.

Any help (use case exemple for  MyProject.HttpApi)? any doc how to integrate my costum controller in swagger ?

Best Regards

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by aelhadi** [comment]
thanks for your response ....

i solved the issue....

my controller class was abstract ....  it should not...

every thing is Ok.....
