### ISSUE TITLE
Learn abp Framework

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#6080]
Very excited to be working on the new set of courses for @abpframework to be launched on 1 Dec 2020. If you want to be on the launch list please head over to [http://learnabpframework.com](http://learnabpframework.com) and subscribe to get a special launch discount and peak at the courses we are working on.

**Comment by vnetonline** [comment]
First I would like to thank you for registering and watching the two courses regarding the ABP Framework at https://amazingsolutions.teachable.com namely being:

> Setting up your development environment for ABP
> Lets Build the BookStore Application with ABP vNext Framework

Today I would like let you know that I have decided to move and develop new courses for the ABP Framework at https://LearnABPFramework.com. I would like to invite you to join our Launch List by visiting and registering your name and email at https://LearnABPFramework.com. I’m so excited to share with you scripted courses which will help you learn the ABP Framework fast.

If you’re a developer and trying to use the ABP Framework to build Application or Modules. You are going to want to join us for the launch on 1 Dec 2020. The best news is, if you join the Launch List now you will be a founder member when you sign up for the membership when it is launched.

Being a Founder Member you will get sneak peeks on what we are working on and a special discounted price for the membership. Check out https://LearnABPFramework.com now, to find out more and become a founder member by ensuring you are on the Launch List!

If you have any questions at all about what https://LearnABPFramework.com is all about or have suggestions on courses or tutorials you would like to see me develop for you. Please reply to this email and let me know.

Hope to see you on the Launch List!

Vineet Belani
https://LearnABPFramework.com

**Comment by CestrianImaging** [comment]
Hi Vineet,

I will be looking to develop an application based around APB using Blazor in the new year. Would this be something you are interested in working on as a developer?

If so, what is your hourly or daily rate?

Kind Regards,
Kevin Farrow

**Comment by vnetonline** [comment]
Dear Kevin

Thanks for reaching out, let's take this conversation private. I would like to learn more about your development project.

Your email gives me an Idea for an "Add-On" community service on LearnABPFramework.com to connect people with ideas with developer with talent to build Applications and Modules using the ABP Framework. I plan on have a Job Board where Business Entrepreneur's can connect with developers to build out their ideas.

I would be happy to help you through your development journey. Look forward to hearing more about your project.

Thanks and Kind Regards

Vineet Belani
+61 402 263 321

________________________________

**Comment by vnetonline** [comment]
The doors to LearnABPFramework.com  are now open and I’m so excited to start helping you Learn, Build, Deploy and Monetise applications and modules built using the ABP Framework.

I have completed screen casting the first free course using ABP Framework 4.0 based on .Net 5.0.

Become a Free Member

**Comment by vnetonline** [comment]
Have you been worndering what is inside when you join http://LearnABPFramework.com then check this out!

https://learnabpframework.com/#whats-inside
