### ISSUE TITLE
Optimal usage of StringEncryptionService (Volo.Abp.Security.Encryption)

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#6084]
**Use case**
There should be username and password in database which is used to authenticate to other API.
Password should be saved encrypted in database and should be decrypted "standalone inside backend logic" (without additional parameters from web application (user input parameters)).

So, my following questions are:

1) Is StringEncryptionService (Volo.Abp.Security.Encryption) the the most appropriate service for such scenario?
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Security/Volo/Abp/Security/Encryption/StringEncryptionService.cs
(If not - which is more suitable.)

2) https://docs.abp.io/api-docs/abp/3.1/api/Volo.Abp.Security.Encryption.AbpStringEncryptionOptions.html#Volo_Abp_Security_Encryption_AbpStringEncryptionOptions_DefaultPassPhrase
There is recommendation to replace default passPhrase ("gsKnGZ041HLL4IM8"). Where is the most suitable location to store this string? Directly inside code (like this default one)?

3) What about salt?
https://docs.abp.io/api-docs/abp/3.1/api/Volo.Abp.Security.Encryption.AbpStringEncryptionOptions.html#Volo_Abp_Security_Encryption_AbpStringEncryptionOptions_DefaultSalt
There is no information if it is recommended to replace default salt (Encoding.ASCII.GetBytes("hgt!16kl")).
If it is recommended also to replace default salt - where is the most suitable location to store this secret? Directly inside code (like this default one)?

Thank you for explanations.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/5800

**Comment by leonkosak** [comment]
So there is no need to define and store custom passPhrase and salt in Encrypt method? :)

**Comment by maliming** [comment]
We use random values in the `appsettings.json` file. You can store `AbpStringEncryptionOptions` in the database or other places if needed.

**Comment by leonkosak** [comment]
I saw when I generated new project. :) Thank you.

**Comment by leonkosak** [comment]
@maliming, what happens if you change StringEncryption:DefaultPassPhrase in appsettings.json after installation is done, but you haven't use StringEncryptionService in custom (tour own) code?

When you create new host database or tenant database and default admin is created - id StringEncryption:DefaultPassPhrase from appsettings.json used for password encryption?

**Comment by maliming** [comment]
>  what happens if you change StringEncryption:DefaultPassPhrase in appsettings.json after installation is done, but you haven't use StringEncryptionService in custom (tour own) code?

IStringEncryptionService will be used to encrypt settings and some configurations, etc., it will not be able to decrypt correctly after the change, 

> StringEncryption:DefaultPassPhrase from appsettings.json used for password encryption?

No,
