### ISSUE TITLE
Define an option to add extension properties for the user to the claims (auth ticket)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6089]

**Comment by PMExtra** [comment]
I want add a new interface:
```csharp
interface IUserClaimProvider<TUser>
{
    Task<IEnumerable<Claim>> GetClaimsAsync(TUser user);
}
```

Then inject `IEnumerable<IUserClaimProvider<IdentityUser>> _userClaimProviders` in [`AbpUserClaimsPrincipalFactory`](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs)

It will call the each of providers in [`AbpUserClaimsPrincipalFactory.CreateAsync`](https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L35-L40):
```csharp
foreach (var provider in _userClaimProviders)
foreach (var claim in await provider.GetClaimsAsync(user))
{
    identity.AddIfNotContains(claim);
}
```

Would it solve this issue? I can make the pull request if you accept this solution.

**Comment by maliming** [comment]
This feature already implemented. I will add the document to explain.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Security/Volo/Abp/Security/Claims/AbpClaimsPrincipalFactory.cs

https://github.com/abpframework/abp/blob/dev/framework/test/Volo.Abp.Security.Tests/Volo/Abp/Security/Claims/AbpClaimsPrincipalFactory_Test.cs

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory.cs#L73
https://github.com/abpframework/abp/blob/dev/modules/identity/test/Volo.Abp.Identity.Domain.Tests/Volo/Abp/Identity/AbpUserClaimsPrincipalFactory_Tests.cs
