### ISSUE TITLE
Add JsonStringEnumConverter to JsonSerializerOptions

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6092]
Otherwise, it can't convert enum strings to enum members on deserialization.

**Comment by hikalkan** [comment]
I tried to add

````csharp
options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
````

to the `AbpJsonOptionsSetup` but I got error on the setting management page (app-pro):

JsonException: The JSON value could not be converted to Volo.Abp.Identity.Features.IdentityTwoFactorBehaviour. Path: $.twoFactorBehaviour | LineNumber: 0 | BytePositionInLine: 32.

**Comment by maliming** [comment]
I'll handle this. 👍
