### ISSUE TITLE
[Question] List of Angular UI compatible modules

### ISSUE THREAD

**Issue by mathro** [abpframework/abp#6094]
Hello, 

Is there a list of Angular supported modules or a comparison table of UI frameworks vs the modules they support?

Thanks!

**Comment by NecatiMeral** [comment]
Hi,

you can see a list of angular modules [here](https://github.com/abpframework/abp/tree/dev/npm/ng-packs/packages).
For the blazor list, you have to check the modules individually (afaik) [here](https://github.com/abpframework/abp/tree/dev/modules).

**Comment by mathro** [comment]
Thanks Necati! This helps but I'd expect a comparison table in the website.
