### ISSUE TITLE
Can we enable to set non-public properties on System.Text.Json

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6095]
System.Text.Json doesn't set non-public properties by default on deserialization.
Is there an option to enable to set them (https://github.com/dotnet/runtime/issues/29743 ?)? If so, it is better to enable it.

**Comment by mehmetuken** [comment]
Every non-public setter field marking with [JsonInclude] attribute.

Test file: https://github.com/dotnet/runtime/blob/d54791648ee99bb36ac86d83568e155f19a67486/src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.NonPublicAccessors.cs#L45-L81

https://github.com/dotnet/runtime/pull/34675

**Comment by maliming** [comment]
Using attribute is not a good solution. : )

**Comment by mehmetuken** [comment]
> Using attribute is not a good solution. : )


I think so :D But this is the approved solution now :(

**Comment by maliming** [comment]
There is currently no good solution, move to **4.1** .

**Comment by mehmetuken** [comment]
https://github.com/dotnet/runtime/issues/42399 maybe help this.

**Comment by maliming** [comment]
We need wait for https://github.com/dotnet/runtime/issues/36785

**Comment by maliming** [comment]
**.NET 7.0**  https://github.com/dotnet/runtime/issues/31511

**Comment by maliming** [comment]
https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-6/#json-contract-customization
