### ISSUE TITLE
[Suggestion] Resharper and Coding Standards...

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#610]
Hi @hikalkan,

As I know you guys use R# internally would you mind including in the root of the src tree a settings file that contains the coding standards (code formatting) you are using? That way using the auto discover plugin for R#:

![image](https://user-images.githubusercontent.com/4738140/49046816-86908800-f229-11e8-8e72-f7985a2e52fc.png)

This can automatically be sucked in and contributors can configure [code clean up](https://www.jetbrains.com/help/resharper/Code_Cleanup__Index.html) to use this which means the PR's will automatically be formatted as you want them.

**Comment by hikalkan** [comment]
Thanks for the suggestion. Will check this.
