### ISSUE TITLE
The Book List Page error on chrome acme is not defined

### ISSUE THREAD

**Issue by pekeramazan** [abpframework/abp#6109]
Hi Im testing tutorial but I have problem,
1-) I cant run this code on chrome

acme.bookStore.books.book.getList({}).done(function (result) { console.log(result); });

2-) I cant see book list

![problem](https://user-images.githubusercontent.com/56788476/98449877-bdc37f80-2148-11eb-960f-cbd60c540f65.JPG)

**Comment by realLiangshiwei** [comment]
Hi

You can refer to the sample source code: https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore

**Comment by pekeramazan** [comment]
> Hi
> 
> You can refer to the sample source code: https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore

It's works! thanks.but why is it samples different from the project(abp.io) I downloaded

**Comment by realLiangshiwei** [comment]
May your project has some problems.  however, you can compare with the sample source code.

**Comment by pekeramazan** [comment]
> May your project has some problems. however, you can compare with the sample source code.

I found problem: Problem is "tiered project" ,
I download not tiered and works fine

**Comment by wen676395159** [comment]
The problem remains. Any project created through ABP cli 4.0 will report this.

**Comment by wen676395159** [comment]
so   why  sample source code is successy but  created through ABP cli 4.0 is error? ABP cli 4.0  need update?

**Comment by philiplai** [comment]
I downloaded the latest package and following the tutorial part 2 and had same problem as @pekeramazan.   Any ideas?

**Comment by philiplai** [comment]
I downloaded the latest package and following the tutorial part 2 and had same problem as @pekeramazan. Any ideas?

**Comment by beefsteak** [comment]
The solution is here "https://github.com/abpframework/abp/issues/2823"

> 那么为什么示例源代码是成功的，但是通过ABP cli 4.0创建的却是错误的呢？ABP cli 4.0是否需要更新？

**Comment by beefsteak** [comment]
> so why sample source code is successy but created through ABP cli 4.0 is error? ABP cli 4.0 need update?

The solution is here "https://github.com/abpframework/abp/issues/2823"

**Comment by beefsteak** [comment]
> refer t
The solution is here "https://github.com/abpframework/abp/issues/2823",I think the tutorial documentation is missing these descriptions.

**Comment by beefsteak** [comment]
> Hi
> 
> You can refer to the sample source code: https://github.com/abpframework/abp-samples/tree/master/BookStore-Mvc-EfCore

The solution is here "https://github.com/abpframework/abp/issues/2823",I think the tutorial documentation is missing these descriptions.

**Comment by Zardw** [comment]
I have fully understood why,
Because the previous content changes according to your own project name and file name, the entire method name is the hump name of the complete namespace of the 'XXXService.cs', and the example in the tutorial is only applicable to the same naming method as 'Acme.BookStore .Books.BookAppService'.

![1](https://github.com/abpframework/abp/assets/117419340/58c9ab35-2d04-4152-a53a-5d9a3e918330)

**Comment by dailinzi** [comment]
I download not tiered and works fine

**Comment by Ramiii0** [comment]
any solution ?
