### ISSUE TITLE
when I am overriding IdentityUserManager, it happened error

### ISSUE THREAD

**Issue by guolianyu** [abpframework/abp#6127]
![image](https://user-images.githubusercontent.com/29138525/98637647-a0b6c880-2363-11eb-87a9-abb2f7c480c8.png)

[14:45:55 ERR] An unhandled exception has occurred while executing the request.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.Account.Web.Pages.Account.LoginModelNew -> FuYu.Accounts.Common.LoginCommon.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'FuYu.Accounts.Common.LoginCommon' can be invoked with the available services and parameters:
Cannot resolve parameter 'FuYu.Accounts.Services.FuYuIdentityUserManager userManager' of constructor 'Void .ctor(FuYu.Accounts.Services.FuYuIdentityUserManager)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(ConstructorInfo[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)

--------------------------------------------------------------

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by guolianyu** [comment]
I have already solved it,  this document's part is wrong in [https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-domain-service](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-domain-service)

we should expose "MyIdentityUserManager " not  "IdentityUserManager"
[ExposeServices(typeof(MyIdentityUserManager))]
