### ISSUE TITLE
A New Theme Alternative to the Basic Theme

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6132]
Basic Theme is good since it provides a minimal theme with Bootstrap's defaults. In this way, you can built your application specific theme based on.

We are planning to introduce a second official theme that is also minimalist but this time with more stylish and production ready. It will be probably a lite version of the [Lepton Theme](https://commercial.abp.io/themes).

We recently [documented theming](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Theming) for the MVC UI and will write theming documents for the other UI types, so we expect from community to create new themes or integrate some popular open source themes. There are already some theme integrations for the MVC UI (like [AdminLTE](https://community.abp.io/articles/using-the-adminlte-theme-with-the-abp-framework-mvc-razor-pages-ui-gssbhb7m) integration).

**Comment by ahmed007boss** [comment]
Could we use other base framework instead of bootstrap to create theme like [Fomantic UI (FUI) ](https://fomantic-ui.com/)

**Comment by hikalkan** [comment]
See https://volosoft.com/blog/introducing-the-lepton-theme-next-generation
We've built and we will release a new theme soon, which will have a "lite" version as free and can be used alternative to the current basic theme.

**Comment by radrad** [comment]
What about tailwind css. It is a great utility framework. It can create not bootstrapy look and feel. 
If I purchase this ui kit: https://tailwinduikit.com/templates
how easy is to incorporate these example templates into ABP.IO. 
Will I be constrained that some built-in components that needs to be rendered on the page must look in certain way or I can assume everything can look like what tailwind designer present.

**Comment by hikalkan** [comment]
I am closing this, because this project will continue out of this repository. The new theme will be independently versioned and deployed. Once it is released, we will announce it on the abp blog.

**Comment by hillin** [comment]
Do we have an estimation on when this will be released? We are really looking forward to it and were deferring some of our decision makings when it was announced.

**Comment by hikalkan** [comment]
I suppose it will take a few more weeks.

**Comment by radrad** [comment]
@hikalkan
If  tailwind css will be used instead of boostrap, could you provide some recommendation how to achieve non-bootstrappy look and feel. Tailwind is a utility type of css framework with more typing and more control over look and feel.
I we want to have a full control over our layout and component look and feel what else needs to be done when using tailwind?

I know you  have bootstrap tag helpers for razor pages. How easy is to re-do these tag helpers? 

How will the new light lepton theme accommodate different css frameworks?

Thanks

**Comment by yellow-dragon-cloud** [comment]
> I am closing this, because this project will continue out of this repository. The new theme will be independently versioned and deployed. Once it is released, we will announce it on the abp blog.

I think theme version should be consistent with framework's version, otherwise it may be confusing.

**Comment by yellow-dragon-cloud** [comment]
> I am closing this, because this project will continue out of this repository. The new theme will be independently versioned and deployed. Once it is released, we will announce it on the abp blog.

@hikalkan, I think theme version should be consistent with framework's version, otherwise it may be confusing.

**Comment by yellow-dragon-cloud** [comment]
According to [Introducing the Lepton Theme Next Generation!](https://volosoft.com/blog/introducing-the-lepton-theme-next-generation) blog post:
> ...we will release an alpha version of the LeptonX-lite package and the free ABP-based Angular package soon to start collecting feedback...

May we hope Blazor theme will be available (at least as prerelease) soon? Like in a month or so maybe?

**Comment by kfrancis** [comment]
> I suppose it will take a few more weeks.

Happy to test asap. We're in the process of completely rewriting most of cab.md based on abp-pro so we're heavily investing and looking forward to it.

**Comment by cbogner85** [comment]
Since it has been released recently, but only for Angular: Is there a demo page available, similar as for [Lepton Theme](https://leptontheme.com/)?  I'd love to see it in action, but couldn't get it to work with a fresh angular project (I use MVC regularly so it may be related to my little angular skills ;-))

**Comment by cbogner85** [comment]
Tried again and now got it to work. Looks promising :-)
Hope it will be available for MVC soon. :)
