### ISSUE TITLE
Dependancy injection not working properly with Remote and Ocelot

### ISSUE THREAD

**Issue by goodyear-incaricotech** [abpframework/abp#6136]
I would like to create a backend with a microservices approach where a microservice "Host" can use the existing other microservices that implements a well know interface.

I hosted my test code here: https://github.com/goodyear-incaricotech/abp.test-ocelot .

I have a common library that have the common module inteface *IModuleAppService*:
  - abp.test-ocelot/srcModuleCommons/ModuleCommons.Application.Contracts
  - abp.test-ocelot/srcModuleCommons/ModuleCommons.HttpApi.Client

I have a Module1 and a Module2: they are independent application, and both of them have a service that implements the *IModuleAppService*
  - abp.test-ocelot/srcModule1
  - abp.test-ocelot/srcModule2

I have a Ocelot application that know the existence of all microservices and it act like a proxy for everywhere.
  - abp.test-ocelot/AbpOcelot

I have a host application that doesn't know the existence of Module1 and Module2, but it would like to use the Ocelot application in order to reach the services that implements the interface *IModuleAppService* (Module1 and Module2).
  - abp.test-ocelot/srcApp

My goal is to have and host that is independent of the existing microservices, so i have the flexibility to add or remove microservices with only the change of the Ocelot application.

With this configuration it doesn't work properly because when i call the API
https://localhost:44347/api/app/app/values -> The AppAppService that resolve an IEnumerable<IModuleAppService>

It resolve only one of the 2 Module, not both of them.

1. If in the OcelotGatewayHostModule i leave both of the module dependencies (Module1HttpApiModule and Module2HttpApiModule), then the AppAppService will resolve only Module1.
2. If in the OcelotGatewayHostModule i have as module dependency only the Module2HttpApiModule, then the AppAppService will resolve correctly Module2.

The error is that in first case I would have expected that it would resolve both Module1 and Module2.

* ABP Framework version: 3.3.1.
* User Interface: none
* Exception message: none
* Steps needed to reproduce the problem: Run the 4 application and try to call https://localhost:44347/api/app/app/values, it will print `|Module1;` instead of `|Module1;Module2;`

**Comment by goodyear-incaricotech** [comment]
Sorry for the first text of the description issue.
I accidentally pressed the enter key before I finished writing the text.

Please tell me if the error is not clear.

**Comment by goodyear-incaricotech** [comment]
Maybe I haven't explained the error very well, is that so?

**Comment by xyfy** [comment]
you should define the re-routes rules 
make sure the rules is asuite for you real api  url.     you can add swaggerui to check it
and depands on the **http.api** in the `gateway` module class

**Comment by goodyear-incaricotech** [comment]
Ocelot seems to work perfectly, have you try to run it? https://github.com/goodyear-incaricotech/abp.test-ocelot
Also the api-definition is ok.
The real problem is that it is not possible to resolve an _IEnumerable_ of something that is a _IRemoteService_ in another microservice.
Maybe the **FindActionAsync** method in class **Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder** finds every time only the first one.

**Comment by maliming** [comment]
hi @goodyear-incaricotech 

If the problem is not related to Ocelot, you should use a simple project to reproduce the problem.
