### ISSUE TITLE
Update Upgrading document for EF Core migrations

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6138]
It would be good if we write what to do with EF Core migrations after upgrading the framework for an existing solution.

**Comment by leonkosak** [comment]
- Generate new migration (and delete it if Up and Down methods are empty)
- Run DbMigrator application if there is non-empty migration

Anything missing? :)

**Comment by NecatiMeral** [comment]
A best practices guide for breaking changes in the migrations would be great also.

**Comment by hikalkan** [comment]
>Anything missing? :)

No 😄

**Comment by hikalkan** [comment]
Closed by https://github.com/abpframework/abp/commit/e999c37947f81333e1d0be6db0ac1e43c36f4ea5
