### ISSUE TITLE
Mvc route generation error

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#614]
https://github.com/abpframework/abp/blob/7b2503aa5946aae3b0820ef4f6394239b0289a9a/modules/identity/src/Volo.Abp.Identity.HttpApi/Volo/Abp/Identity/IdentityRoleController.cs#L23-L31

https://github.com/abpframework/abp/blob/7b2503aa5946aae3b0820ef4f6394239b0289a9a/framework/src/Volo.Abp.Http/Volo/Abp/Http/HttpMethodHelper.cs#L13-L20

Because getAll and get, getList are all deleted , resulting in the use of nswag generate typescript code error, can you consider only deleting Get

**Comment by Nokecy** [comment]
![qq 20181129181340](https://user-images.githubusercontent.com/12318131/49214897-8c8d9100-f402-11e8-8930-f2544ee3efb7.jpg)


Generated two methods with the same name

**Comment by hikalkan** [comment]
What tool you are using to generate the typescript proxies?

**Comment by Nokecy** [comment]
@hikalkan  NSwag and NSwagStudio

**Comment by Nokecy** [comment]
`            services.AddSwaggerGen(
                options =>
                {
                    options.SwaggerDoc("v1", new Info { Title = "Test API", Version = "v1" });
                    options.DocInclusionPredicate((docName, description) => true);
                    options.CustomOperationIds((apiDesc) =>
                    {
                        return apiDesc.ActionDescriptor.RouteValues["controller"] + "_" + (apiDesc.TryGetMethodInfo(out MethodInfo methodInfo) ? methodInfo.Name : null);
                    });
                });`

Fixed using the CustomOperationIds method
