### ISSUE TITLE
IdentityUserRole

### ISSUE THREAD

**Issue by journey191** [abpframework/abp#6140]
ABP Identity module can only assign roles to user,if I create a new role and I want to assign this role to many users,or if I want to remove a role from many users assigned,it is a hard work.
I tryed injecting the IRepository&lt;IdentityUserRole&gt; in my applicationservice,but I got a exception:
```
Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'OntallCore.Organization.IdentityManage.CustomRoleAppService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`1[Volo.Abp.Identity.IdentityUserRole] repository' of constructor 'Void .ctor(Volo.Abp.Domain.Repositories.IRepository`1[Volo.Abp.Identity.IdentityUserRole])'.
```
I found that the constructor of class IdentityUserRole is protected.
How can I modify the data of AbpUserRoles datatable directly in my applicationservice?
Is there a better way to assign/unassign a role for users？

**Comment by xyfy** [comment]
please take a look  at method   `SetRolesAsync` in class  `Volo.Abp.Identity.IdentityUserManager`  of nuget package `volo.abp.identity.domain`

and if you want to inject  `IRepository`,take a look at  [Repositories](https://docs.abp.io/zh-Hans/abp/latest/Repositories)
