### ISSUE TITLE
Dynamic Form with Dropdown?

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#617]
Is it possible to have a dynamic form with a dropdown? If so, how do you specify it?

**Comment by yekalkan** [comment]
You just have to add a "SelectItems" attribute and select options as parameter.

see https://github.com/abpframework/abp/blob/master/framework/test/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.Demo/Pages/Components/DynamicForms.cshtml.cs#L70

**Comment by djlaney3** [comment]
Does this work with a look up table also, not just enums?

**Comment by yekalkan** [comment]
Yes, the example that i have mentioned above does that. Select options are provided by Countries list that is defined at line 17. You can define it or add new values in OnGet method.

For enum, you don't have to do anything special. Dynamic-form determinates the enum properties. As you may notice, " public Cities City { get; set; }" doesn't have a SelectItems attribute but dynamic-form generates a dropdown for it.

Examples will be more clear when we write a documentation for tag helpers.

**Comment by djlaney3** [comment]
I"m not following you here.  Can you give me a code sample?  I have a database table and matching entity, with and ID and NAME field, then in another table, I have the typeId field.  How does my entity need to look to make that a dropdown on a dynamic form?

**Comment by djlaney3** [comment]
I see.  I have it working now.  Thanks for the detail.

**Comment by dicksonkimeu** [comment]
Hello,

Am getting this error, which namespace / library am i missing ?

**Comment by maliming** [comment]
hi @dicksonkimeu 
Does your application service have this method(`GetAllListAsync`)?

**Comment by dicksonkimeu** [comment]
Have added this,

See below and still doesn't work.

Could the issue be ApplicationAutoMapperProfile ? how can i implement nested mapping ?

      public async Task<List<LeaveTypeDto>> GetAllListAsync()
        {
            List<LeaveType> leaveTypeDtos = await Repository.GetListAsync();
            return ObjectMapper.Map<List<LeaveType>, List<LeaveTypeDto>>(leaveTypeDtos);
        }

public **LeaveTypeDto** LeaveType { get; set; } -- create update dto

public **LeaveTypeDto** LeaveType { get; set; } -- entityDto

public **LeaveType** LeaveType { get; set; } -- entity

Auto Mapper
-    CreateMap<LeaveEntry, LeaveEntryDto>();
-    CreateMap<LeaveType, LeaveTypeDto>();
-    CreateMap<CreateUpdateLeaveEntryDto, LeaveEntry>();
-    CreateMap<CreateUpdateLeaveTypeDto, LeaveType>();

**Comment by zHaytam** [comment]
What if the model is in `Application.Contracts` ?

**Comment by yekalkan** [comment]
@zHaytam It may not work properly.
