### ISSUE TITLE
AppName, AppUrlOptions

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#6178]
When registering new user (/api/account/register), required parameter is also appName (string).

When appName is not predefined, the following error appears in Logs.txt:
[ERR] Url, named 'Abp.Account.EmailConfirmation', for the application 'MyBusinessApp' was not configured. Use AppUrlOptions to configure it!

After some research, I found this: https://docs.abp.io/api-docs/abp/3.1/api/Volo.Abp.UI.Navigation.Urls.AppUrlOptions.html

After searching code, there are:

xxxIdentityServerModule.cs
![image](https://user-images.githubusercontent.com/39346964/98938349-0469fe80-24e8-11eb-833d-3fa057b88df0.png)

xxxHttpApiHostModule.cs
![image](https://user-images.githubusercontent.com/39346964/98938411-1f3c7300-24e8-11eb-801b-fa27a2d1ac48.png)

So, there are only these two hardcoded values ("MVC" and "Angular") and this basically means that nothing is configurable?

I noticed that Blazor UI should also send "MVC" in appName parameter.

What is point of appName parameter which should be send when registering new user?

**Comment by melfahn** [comment]
I second this question

**Comment by maliming** [comment]
> What is point of appName parameter which should be send when registering new user?

It cooperates with [`AppUrlProvider`](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.UI.Navigation/Volo/Abp/Ui/Navigation/Urls/AppUrlProvider.cs#L30).
