### ISSUE TITLE
DbMigrator warning installing pre-release version (4.0.0-rc.1)

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#6179]
Uses latest pre-release version (4.0.0-rc.1)

Downloaded the latest release (Blazor, Not Tiered) and ran the DbMigrator on an empty database but get the following message:

**The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results**

![image](https://user-images.githubusercontent.com/69393775/98968198-46556d80-2505-11eb-8d4b-e98a0d8ca789.png)

**Comment by maliming** [comment]
Thanks for feedback I will fix it.
