### ISSUE TITLE
How long can use v1.0？

### ISSUE THREAD

**Issue by marjezhang** [abpframework/abp#618]
HI contributor！
I like this version of abp.  I have used the abp in producing.  
And i am changing it for distributed, with eventflow framework, i think  eventflow framework is best cqrs+es framework.  so I found this version of abp.io is the same idear with my mind.   
How long would you publish v1.0 for producing.

Thank you!

**Comment by hikalkan** [comment]
I can not say a date yet. Probably in Q2 of 2019, however it's subject to change. We will make announcement when it gets more mature.
