### ISSUE TITLE
CORS request for path: /.well-known/openid-configuration from origin: https://localhost{port}->System.NullReferenceException

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#6183]
after resolving #6180, and trying to run from the standard templated project, i see there is another problem:

part of my log file:

>[DBG] CORS request made for path: /.well-known/openid-configuration from origin: https://localhost:44307
>2020-11-13 13:39:12.311 +08:00 [ERR] An unhandled exception has occurred while executing the request.
>System.NullReferenceException: Object reference not set to an instance of an object.

the `/.well-known/openid-configuration` path seems to be the problem

**Comment by 274188A** [comment]
host appsettings.json - to show: 44307 is registered as an origin allowable..

>{
  "App": {
    "SelfUrl": "https://localhost:44353",
    "CorsOrigins": "https://*.Gp.com,http://localhost:4200,https://localhost:44307"
  },
  "ConnectionStrings": {
    "Default": "Server=(LocalDb)\\MSSQLLocalDB;Database=Gp;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "AuthServer": {
    "Authority": "https://localhost:44353",
    "RequireHttpsMetadata": "false"
  },
  "StringEncryption": {
    "DefaultPassPhrase": "XWMSm8stJAjrfwaS"
  },
  "Settings": {
    "Abp.Mailing.Smtp.Host": "127.0.0.1",
    "Abp.Mailing.Smtp.Port": "25",
    "Abp.Mailing.Smtp.UserName": "",
    "Abp.Mailing.Smtp.Password": "",
    "Abp.Mailing.Smtp.Domain": "",
    "Abp.Mailing.Smtp.EnableSsl": "false",
    "Abp.Mailing.Smtp.UseDefaultCredentials": "true",
    "Abp.Mailing.DefaultFromAddress": "noreply@abp.io",
    "Abp.Mailing.DefaultFromDisplayName": "ABP application"
  }
}

**Comment by 274188A** [comment]
running the app without debugging manages to open the first page and displays the login.  Clicking login produces err:500 - 

>[DBG] CORS request made for path: /.well-known/openid-configuration from origin: https://localhost:44307
2020-11-13 13:39:12.311 +08:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.

the `/.well-known/openid-configuration` path seems to be the problem

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/6180

**Comment by 274188A** [comment]
no - different

**Comment by 274188A** [comment]
this is not the same as #6180

**Comment by maliming** [comment]
You can wait for 4.0.0-rc2 and try again.

**Comment by 274188A** [comment]
Ok
