### ISSUE TITLE
Abp cli Update

### ISSUE THREAD

**Issue by OldKing-lion** [abpframework/abp#6184]
My current version is 3.3.0,I want to update to 4.0.0_rc1 perview version to use Net5，But It has some error when it excuted the update command ,like the content in picture below.
![image](https://user-images.githubusercontent.com/13028615/99039771-e6250100-25c2-11eb-87a1-2ec4c48f045a.png)

**Comment by OldKing-lion** [comment]
when i roll back the nuget package version to 3.3.1 
![image](https://user-images.githubusercontent.com/13028615/99039963-46b43e00-25c3-11eb-8d53-3d14cea800cc.png)

It always showes error and I can not find the reason:
![image](https://user-images.githubusercontent.com/13028615/99040116-8418cb80-25c3-11eb-9458-1ddacb6d385b.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/6180
