### ISSUE TITLE
Blob Module MongoDb System.FormatException: Size 119275719 is larger than MaxDocumentSize 16777216

### ISSUE THREAD

**Issue by redcatH** [abpframework/abp#6187]
I am using the blob module, and the upload file is larger than 16MB to report an error
Blob module MongoDb System.FormatException: Size 119275719 is greater than MaxDocumentSize 16777216

Does abp mongodb support GridFS?
or
Does the Blob module support uploading functions larger than 16MB
![QQ图片20201113194611](https://user-images.githubusercontent.com/30196697/99069255-f7810400-25e8-11eb-943b-b041eec34b56.png)

**Comment by mtozlu** [comment]
This is not about Blob Storing module of abp. It is about MongoDB max document size. I encourage you to read about enabling GridFS.
Abp's BlobStoring.Database.MongoDB package does not support GridFS currently. Maybe you can implement your own BlobContainer to use with GridFS and create a pull request to include it in abp.
