### ISSUE TITLE
[Bug] Text Templating: Model property names with more than one word aren't rendered

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#6188]
`await _templateRenderer.RenderAsync(AbpIoEmailTemplates.ArticleNotifyNew, new
            {
                Title = article.Title
            })`

Rendered as expected in template file with `{{ model.title }}`.

`await _templateRenderer.RenderAsync(AbpIoEmailTemplates.ArticleNotifyNew, new
            {
                ArticleTitle = article.Title
            })`

isn't rendered in template file with any "case" combination. What i've tried: `{{ model.ArticleTitle }}`, `{{ model.articleTitle }}`,`{{ model.articletitle }}`. 

You can reproduce this on [Hello Demo](https://github.com/abpframework/abp-samples/tree/master/TextTemplateDemo).

**Comment by colinin** [comment]
I also met this situation, in **TemplateRenderer.RenderAsync** , all model attributes must be lowercase,
For example: 
```c#
await _templateRenderer.RenderAsync(AbpIoEmailTemplates.ArticleNotifyNew, new { articletitle = article.Title });
```
also must be the same in a .tpl: {{ model.**articletitle** }}

**Comment by mehmetuken** [comment]
Scriban default property and methods naming kebab-case. Using ArticleTitle  `atricle_title`. It's not bug. 

> **NOTICE**
> By default, Properties and methods of .NET objects are automatically exposed with lowercase and `_` names. It means that a property like `MyMethodIsNice` will be exposed as `my_method_is_nice`. This is the default convention, originally to match the behavior of liquid templates.
> If you want to change this behavior, you need to use a [`MemberRenamer`](/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer) delegate

**Comment by gdeswardt** [comment]
This is not a bug, but the documentation should be updated to as it states that **camelCase** is the default

https://github.com/abpframework/abp/blob/dev/docs/en/Text-Templating.md#pascalcase-vs-camelcase

> **PascalCase vs camelCase**
> PascalCase property names (like UserName) is used as camelCase (like userName) in the templates.

and instead, it is using the **snake case** as the default member renamer as specified in scriban documentation

https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer
