### ISSUE TITLE
Can we make distributed events transactional on local eventbus

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#619]
Distributed event bus works as local by default (unless you explicitly add one of the implementations, like redis). Thus, when you develop a module which exposes distributed events, this module will be also usable in a monolithic application. If we are developing a monolithic app, we want these events to be transactional if possible (to provide data consistency without complicating the infrastructure).

In current design, distributed events are triggered out of current UOW. That means if you throws exception in your distributed event handler, it can not rollback the transaction of the event. And also it can not guarantee that event is delivered to the distributed event bus in a microservice scenario. We should work on that.

**Comment by brunobertechini** [comment]
Hello @hikalkan the best approach I've ever seen for this case is the one based on endpoint implementations. For example, if you have a Endpoint A with 3 handlers for the same event, they should run in the same UoW (Transaction). 

I have implemented similar scenario for monolith. The dispatch (trigger/enqueue) of the events should be considered as part of the transaction. However, this will heavily depend on the transport used. If this is not possible (which is true for most of the cases), the UoW for monolith should be aware that is running in a monolith app and be part of the trasnsaction.

Let me know if you have any doc or consideration about this (any test case, reproduction etc), i can help with this as well

**Comment by hikalkan** [comment]
Thanks @brunobertechini :)
Will work on this in the next weeks. I will ask you if I need.

**Comment by Goxiaoy** [comment]
Events should be defined as distributed or not in design time. Distributed events usually mean the producer have done his job.
Instead,  the consumer should apply retry policy to avoid data inconsistency or trigger another distributed event to revert.

**Comment by gentledepp** [comment]
I just went through your documentation and got a bit curious how your "localevents" and "domainevents" are implemented.
I found, that you are using the "publish events **before** committing the current transaction" approach.
[The deferred approach to raise and dispatch events](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation#the-deferred-approach-to-raise-and-dispatch-events)

Note: I *guess* that my feedback can add value to this issue. If I am mistaken, please let me know and I'll open another one!

So.. there are multiple issues I see with the current implementation:

As you have not committed the transaction when publishing the events 
  1. if committing fails, you will end up with events being created and handled multiple times (i.e. the next time you try to commit)
     This may not be too much of an issue, as most event buses only support the "at least once" guarantee for messages. So receivers *should* discard events once they are received the second time.
     However: [I do not see any `Guid EventId` on your `ProductStockCountChangedEto`](https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo#distributed-event-bus)
     so how should any receivers discard those messages?

 2. even worse, as the local transaction is still *active*, 
    - any local event handlers will run within the same transaction. Isn't that unwanted?
    - if any external system is accessed (e.g. some message queue supported by `System.Transactions`), couldn't that lead to the fact that the current transaction is elevated to a **distributed transaction**? That would be horrible!

So what I was *hoping* to see, is that abp implemented this using the [outbox pattern](http://www.kamilgrzybek.com/design/the-outbox-pattern/) 
That way, all local events could be written to the database into some `Outbox` table. That way all data would be stored within the same transaction.
And then, a local polling consumer could detect any messages that were not handled yet and consume them from the table.

Your thoughts? :-)

**Comment by gentledepp** [comment]
AWESOME! 😲😲😲😲😲
