### ISSUE TITLE
An error occurred while updating user profile

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#6191]
Steps:

1. Use the CLI To a project: `abp new QaBlazor-t app -u blazor --mobile none  --database-provider ef -csf --preview`
2. Run`.DbMigrator` , `.HttpApi.Host` and `.Blazor`  project
3. Navigate to the manage profile page and select the `personal info` tab.
4. Click the save button
    

![image](https://user-images.githubusercontent.com/16813853/99072374-dcb18e00-25ee-11eb-88ec-196c08ee11ae.png)

**Comment by maliming** [comment]
Include Angular.

**Comment by EngincanV** [comment]
The same error occurred in the "/identity/organization-units" route in the Angular project. ( It occurs when I try to edit organization-unit)

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/pull/6196
