### ISSUE TITLE
angular error about ApplicationInfo and EnvironmentService after using abp update

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#6199]
![image](https://user-images.githubusercontent.com/4489940/99147532-c8d45d80-26bc-11eb-9242-c41087c42fa7.png)
version is 4.0.0-rc.2

**Comment by maliming** [comment]
hi 

* Steps needed to **reproduce** the problem.

**Comment by ruby0602** [comment]
@maliming the app is fine before using abp update, I just finished the abp update

**Comment by maliming** [comment]
You can temporarily refer to this document.

https://github.com/abpframework/abp/blob/docs/6185/docs/en/Migration-Guides/Abp-4_0-Angular.md

**Comment by ruby0602** [comment]
@maliming 
![image](https://user-images.githubusercontent.com/4489940/99147921-9a0bb680-26bf-11eb-92f4-28010eab577d.png)
![image](https://user-images.githubusercontent.com/4489940/99147952-d2ab9000-26bf-11eb-8459-a6d70818b4e6.png)
first image show the time before abp update
second image show the time after abp update

**Comment by ruby0602** [comment]
@maliming OK, thanks a lot
