### ISSUE TITLE
Can't find login page

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#620]
Hi,

I looked everywhere both generic created project and https://github.com/abpframework/abp/tree/master/framework/src all projects. Yet i couldn't figure out where is the Login Page.

I did clone Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic and i am editing its Application layout as my own. Can't figure out many things, yet trying my hard to make something

**Comment by ugurozturk** [comment]
Perhaps, it is in AbpAccountWebModule ? yet it is not in the abp/tree/master

**Comment by hikalkan** [comment]
https://github.com/abpframework/abp/tree/master/modules/account/src/Volo.Abp.Account.Web/Pages/Account
