### ISSUE TITLE
Username text is smaller than the same texts in the header

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6201]
The Basic Theme for the Blazor UI:

![image](https://user-images.githubusercontent.com/1210527/99152750-c0782480-26b4-11eb-851a-7de745ac64bd.png)

**Comment by cotur** [comment]
![image](https://user-images.githubusercontent.com/20099739/99220549-f110a900-27ef-11eb-866d-fd978174bfb5.png)

Could not reproduce at `rel-4.0` branch.
