### ISSUE TITLE
Rabbitmq message error for Version-4.0.RC2

### ISSUE THREAD

**Issue by qqzhw** [abpframework/abp#6204]
The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=541, text="Unexpected Exception", classId=0, methodId=0, cause=System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接

**Comment by maliming** [comment]
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by qqzhw** [comment]
Thank you ! It's ok now.
