### ISSUE TITLE
Cannot find package Volo.Abp.EntityFrameworkCore.MySQL with version (>= 4.0.0-rc.2)

### ISSUE THREAD

**Issue by OldKing-lion** [abpframework/abp#6211]
Error NU1102 Cannot find package Volo.Abp.EntityFrameworkCore.MySQL with version (>= 4.0.0-rc.2)
   -Found 67 versions in Package source [Closest version: 3.3.1]
   -Found 0 versions in Microsoft Visual Studio Offline Packages

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/5700

But now `Pomelo.EntityFrameworkCore.MySql` has been released [v5.0.0-alpha.2](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.0-alpha.2). We will add this package in the 4.0 final version.
