### ISSUE TITLE
Blazor UI documents (Part I)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6214]
- [x] Global Scripts & Style (including bundling&minification) / @ilkayilknur #6259
- [X] Message / @ilkayilknur #6194
- [X] Notification / @ilkayilknur #6238

Please write them in the `rel-4.0` branch.

**Comment by SuriyaArul** [comment]
How to add VIEW option in per-defined Admin user (Action Button) in Blazor UI
