### ISSUE TITLE
login remove from AuthService in @abp/ng.core

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#6223]
error TS2339: Property 'login' does not exist on type 'AuthService'

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by ruby0602** [comment]
@maliming abp is 4.0.0-rc.3,ui is angular,code is fine in abp 3.3.1

**Comment by maliming** [comment]
You can refer to this PR.

https://github.com/abpframework/abp/pull/6189

**Comment by ruby0602** [comment]
@maliming but the version of my angular is 11

**Comment by bnymncoskuner** [comment]
@ruby0602 Please refer to [this document](https://docs.abp.io/en/abp/4.0/Migration-Guides/Abp-4_0-Angular)

Password flow is no longer available with v4.x. That's why `login` method is removed from `AuthService`.
