### ISSUE TITLE
Module template not using net 5.0

### ISSUE THREAD

**Issue by aididhaiqal** [abpframework/abp#6225]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version** : 4.0.0-rc.3.Please **write in English**.

Hi there,

It came to my attention that the module template haven't been updated to net 5.0, most of the project such as application is still referencing netstandard 2.0

**Comment by maliming** [comment]
.NET framework, xamarin, mono.. applications can't support NET 5.
they should still rely on .netstandard2.0 and .netstandard2.1.
We should follow the Microsoft way: They make Extensions.* libraries .netstandard2.0
Our common packages are actually conceptually similar to those extensions libraries and we want to cover more platforms

`Microsoft.EntityFrameworkCore` is `.NETStandard 2.1`. https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.0
