### ISSUE TITLE
Angular generate-proxy maximum call stack size exceeded 

### ISSUE THREAD

**Issue by serridavide** [abpframework/abp#6243]
### Version info

Abp version: 3.3.1 (stable)
Angular version: 10.0.7

### Steps to reproduce

Abp project located in this repository will generate the issue:

https://github.com/serridavide/ABP-Example

Create a generic angular application and run the generate-proxy command. 

I used this exact line in my example

`abp generate-proxy --api-name local`

with

```
apis: {
    local: {
      url: "https://localhost:44334",
      rootNamespace: "stackTest",
    }
  }
```

in my environment.ts file.

### Maximum call stack size exceeded

When running the generate-proxy command, this error message will appear, failing the execution.

![abp-error](https://user-images.githubusercontent.com/72458567/99401460-7bd4cf00-28e8-11eb-9d1e-29e19490588b.PNG)

### Recursive classes

```
public class Child : AuditedAggregateRoot<Guid>
    {

       public Child(Guid id, string name)
        {
            Id = id;
            Name = name;
        }

        public  string Name { get; set; }

        public  Father Father { get; set; }
   }

```
```
public class Father : AuditedAggregateRoot<Guid>
    {
        public Father(Guid id, string name)
        {
            Id = id;
            Name = name;
        }

        public  string Name { get; set; }

        public  Collection<Child> Children { get; set; }

    }

```

This two classes are responsible for the generated error.
This problem was marked as fixed in the latest Abp release, this issue recreate exactly how to generate the error so it can be studied in depth

**Comment by maliming** [comment]
hi

You can try to remove **Father** from **ChildDto**.

https://github.com/serridavide/ABP-Example/blob/f495764255/src/stackTest.Application.Contracts/Entities/Childs/ChildDto.cs#L19

**Comment by serridavide** [comment]
Hi, thanks for your response. I don't think removing Father is a correct way to approach this. More than a couple times I had to use references like that in my backend and having 200+ entities it really seems a bad idea to temporarily remove every single one of them to generate the proxy and add them back after the generation. And even if I do so after I add another entity I have to do it all over again. 

This binding of objects is in the official microsoft documentation

https://docs.microsoft.com/it-it/ef/ef6/modeling/code-first/workflows/new-database

I would suggest to stay aligned with the official documentation and actually update the framework so it can work with the intended way of using database models.

**possible solution**

As you suggested we could try to remove Father from ChildDto, but what if instead that is handled automatically from the generate-proxy? Ignoring those references in the script should solve the issue and still make them usable

**Comment by goodyear-incaricotech** [comment]
Maybe with a [JsonIngore] or similar?

**Comment by bnymncoskuner** [comment]
Hello @serridavide,

Your repo does not have angular code so I just created an empty project with the latest version (4.0.0-rc.3) of `abp-cli` and copy-pasted the files from your repo into mine. When I ran `abp generate-proxy`, everything worked smoothly and the files are created as follows.

```shell
CREATE src/app/proxy/generate-proxy.json (171911 bytes)
CREATE src/app/proxy/README.md (1000 bytes)
CREATE src/app/proxy/stack-test/entities/fathers/father.service.ts (1461 bytes)
CREATE src/app/proxy/stack-test/entities/childs/child.service.ts (1447 bytes)
CREATE src/app/proxy/stack-test/entities/childs/models.ts (287 bytes)
CREATE src/app/proxy/stack-test/entities/fathers/models.ts (293 bytes)
CREATE src/app/proxy/stack-test/entities/fathers/index.ts (60 bytes)
CREATE src/app/proxy/stack-test/entities/childs/index.ts (59 bytes)
CREATE src/app/proxy/stack-test/entities/index.ts (74 bytes)
CREATE src/app/proxy/stack-test/index.ts (40 bytes)
CREATE src/app/proxy/index.ts (43 bytes)
```


`childs/models.ts`

```typescript
import type { AuditedEntityDto } from '@abp/ng.core';
import type { FatherDto } from '../fathers/models';

export interface ChildDto extends AuditedEntityDto<string> {
  name: string;
  father: FatherDto;
}

export interface CreateUpdateChildDto {
  name: string;
  father: FatherDto;
}
```

`fathers/models.ts`

```typescript
import type { ChildDto } from '../childs/models';
import type { AuditedEntityDto } from '@abp/ng.core';

export interface CreateUpdateFatherDto {
  name: string;
  children: ChildDto[];
}

export interface FatherDto extends AuditedEntityDto<string> {
  name: string;
  children: ChildDto[];
}
```

Could you try it with `4.0.0-rc.3` if possible?

**Comment by serridavide** [comment]
I haven't tried the 4.0.0 release yet, but since it has some major changes (.NET 5.0) I won't be able to test it immediately. I'll keep you updated as soon as I upgrade everything needed.
