### ISSUE TITLE
System.IO.DirectoryNotFoundException : '/MyApp.Domain.Shared/' with Docker

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#6244]
Hello,

Version 3.3.1
Tierd App
Blazor
Docker
Windows 10 

MyApp.IdentityServer exception when using Docker at : 

Configure<AbpVirtualFileSystemOptions>(options =>
                {
                    options.FileSets.ReplaceEmbeddedByPhysical<MyAppDomainSharedModule>(Path.Combine(hostingEnvironment.ContentRootPath, $"..{Path.DirectorySeparatorChar}MyApp.Domain.Shared"));
                    options.FileSets.ReplaceEmbeddedByPhysical<MyAppDomainModule>(Path.Combine(hostingEnvironment.ContentRootPath, $"..{Path.DirectorySeparatorChar}MyApp.Domain"));
                });

Error Message : 

System.IO.DirectoryNotFoundException : '/MyApp.Domain.Shared/'

**Comment by maliming** [comment]
hi

**ReplaceEmbeddedByPhysical** is useful during development.

If you deploy to docker, you should configure it according to the environment.

https://docs.abp.io/en/abp/latest/Virtual-File-System#dealing-with-embedded-files-during-development
