### ISSUE TITLE
Blazor UI: Should not truncate the notification message

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6245]
The developers may trim it if they need. We should not truncate the message. Obviously it is a problem even with such a small message:

![image](https://user-images.githubusercontent.com/1210527/99427892-02a0a080-2917-11eb-95e0-6f370bb55587.png)

The button text (`CUSTOMOK` here) can be below the text line. But actually I believe we don't need to such a text button. Instead, a simple close icon is better:

![image](https://user-images.githubusercontent.com/1210527/99428308-85c1f680-2917-11eb-92ff-23abeb8fa471.png)

This screenshot has been taken from the [toastr library](https://codeseven.github.io/toastr/demo.html).

**Comment by stsrki** [comment]
@hikalkan This is already working. `Multiline` attribute needs to be set to true.
