### ISSUE TITLE
After restarted IdentityServer ,the JWT token can not validate

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#6247]
* Your **ABP Framework version**  v3.3.1.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
I am using the abp module  `identityserver` 

when I got a access token `A`  from `identityserver`, 
use the token `A` to call api is ok;

and then restart the `identityserver`  .
use the token `A` to call api will got an error.
```
2020-11-18 10:15:26.349 +08:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
kid: 'NGT6ysunU83gLouosAzsSA'.
Exceptions caught:
 ''.
token: '{"alg":"RS256","kid":"NGT6ysunU83gLouosAzsSA","typ":"at+jwt"}.{"nbf":1605665446,"exp":1605708646,"iss":"http://120.25.77.26:51511","aud":["BusinessDomainService","CommonService","IdentityService","Intern
alGateway","ProductDomainService","PublicWebSiteGateway","SynergyService"],"client_id":"normalclient","sub":"449e0d05-af78-cf93-7001-39f77963d5f0","auth_time":1605665446,"idp":"local","role":"admin","phone_numbe
r_verified":"False","email":"xcladmin@yungc.com","email_verified":["False",false],"name":"xcladmin","scope":["BusinessDomainService","CommonService","IdentityService","InternalGateway","ProductDomainService","Pu
blicWebSiteGateway","SynergyService"],"amr":["pwd"]}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2020-11-18 10:15:26.364 +08:00 [INF] BearerIdentityServerAuthenticationJwt was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match key:
kid: 'NGT6ysunU83gLouosAzsSA'.
Exceptions caught:
 ''.
token: '{"alg":"RS256","kid":"NGT6ysunU83gLouosAzsSA","typ":"at+jwt"}.{"nbf":1605665446,"exp":1605708646,"iss":"http://120.25.77.26:51511","aud":["BusinessDomainService","CommonService","IdentityService","Intern
alGateway","ProductDomainService","PublicWebSiteGateway","SynergyService"],"client_id":"normalclient","sub":"449e0d05-af78-cf93-7001-39f77963d5f0","auth_time":1605665446,"idp":"local","role":"admin","phone_numbe
r_verified":"False","email":"xcladmin@yungc.com","email_verified":["False",false],"name":"xcladmin","scope":["BusinessDomainService","CommonService","IdentityService","InternalGateway","ProductDomainService","Pu
blicWebSiteGateway","SynergyService"],"amr":["pwd"]}'.
2020-11-18 10:15:26.365 +08:00 [INF] Bearer was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match key:
kid: 'NGT6ysunU83gLouosAzsSA'.
Exceptions caught:
 ''.
token: '{"alg":"RS256","kid":"NGT6ysunU83gLouosAzsSA","typ":"at+jwt"}.{"nbf":1605665446,"exp":1605708646,"iss":"http://120.25.77.26:51511","aud":["BusinessDomainService","CommonService","IdentityService","Intern
alGateway","ProductDomainService","PublicWebSiteGateway","SynergyService"],"client_id":"normalclient","sub":"449e0d05-af78-cf93-7001-39f77963d5f0","auth_time":1605665446,"idp":"local","role":"admin","phone_numbe
r_verified":"False","email":"xcladmin@yungc.com","email_verified":["False",false],"name":"xcladmin","scope":["BusinessDomainService","CommonService","IdentityService","InternalGateway","ProductDomainService","Pu
blicWebSiteGateway","SynergyService"],"amr":["pwd"]}'.
```

**Comment by xyfy** [comment]
Is there any more config I need to do ?

**Comment by xyfy** [comment]
I think it would the identityServer cached some infomation  in memeroy-cache  which is used to check the sign,

but I can not find a way to set it using redis?

**Comment by xyfy** [comment]
can anyone know the reason?

**Comment by aelhadi** [comment]
Hello,

I think you need to clear your browser cache...

**Comment by xyfy** [comment]
I don't want to re-login after the identity-server rebooted , if there is something cache in memory,I want to save it in the redis.

but I had not found the reason that why the token is invalid after restart the identity-server

**Comment by xyfy** [comment]
watched

**Comment by CliffordSpainhour** [comment]
Looks like for production you have to set AddDeveloperSigningCredentials to false on the IdentityServer.

Then add your own signing credential.

It can be configured in the IdentityServerModule.

Something like this:

```
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            var hostingEnvironment = context.Services.GetHostingEnvironment();
            var configuration = context.Services.GetConfiguration();

            if (hostingEnvironment.IsDevelopment())
            {
                PreConfigure<AbpIdentityServerBuilderOptions>(options =>
                {
                    options.AddDeveloperSigningCredential = true;
                });
            }
            else
            {
                PreConfigure<AbpIdentityServerBuilderOptions>(options =>
                {
                    options.AddDeveloperSigningCredential = false;
                });

                string password = configuration["Jwt:Secret"];
                Debug.Assert(!String.IsNullOrEmpty(password), "Jwt:Secret is missing from appsettings");
                string certificate = Path.Combine(hostingEnvironment.ContentRootPath, "cert.pfx");

                var cert = new X509Certificate2(certificate, password);

                PreConfigure<IIdentityServerBuilder>(identityServerBuilder =>
                {
                    identityServerBuilder.AddSigningCredential(cert);
                });
            }
        }
```

Here is some documentation on what AddSigningCredential, AddDeveloperSigningCredential , and what AddValidationKey are: http://docs.identityserver.io/en/release/topics/startup.html#refstartupkeymaterial

This https://brockallen.com/2019/08/09/identityserver-and-signing-key-rotation/ also seems like good advice. Rotating out the signing key every so often. 

I was able to use this test code on start up of my api server to check if my KeyId changed on restart

```
var authAuthority = configuration["AuthServer:Authority"];

IConfigurationManager<OpenIdConnectConfiguration> configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>($"{authAuthority}/.well-known/openid-configuration", new OpenIdConnectConfigurationRetriever());
OpenIdConnectConfiguration openIdConfig = configurationManager.GetConfigurationAsync(CancellationToken.None).Result;

var test = openIdConfig.SigningKeys;
```

**Comment by xyfy** [comment]
@CliffordSpainhour hi,I used **Http** not **https**  ，`https` is used for the reverse proxy server **nginx**

**Comment by xyfy** [comment]
I cannot understand the following paragraph and code
what's the `SigningKeys` used for?
> 
> I was able to use this test code on start up of my api server to check if my KeyId changed on restart
> 
> ```
> var authAuthority = configuration["AuthServer:Authority"];
> 
> IConfigurationManager<OpenIdConnectConfiguration> configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>($"{authAuthority}/.well-known/openid-configuration", new OpenIdConnectConfigurationRetriever());
> OpenIdConnectConfiguration openIdConfig = configurationManager.GetConfigurationAsync(CancellationToken.None).Result;
> 
> var test = openIdConfig.SigningKeys;
> ```

**Comment by xyfy** [comment]
In the doc  [key-material](http://docs.identityserver.io/en/release/topics/startup.html#key-material),it says the **AddDeveloperSigningCredential** **The generated key will be persisted to the file system so it stays stable between server restarts**.   but I can not found the path of the generated key

**Comment by xyfy** [comment]
I check the **jwks** of `xxx/.well-known/openid-configuration/jwks` the key id will changed after recreated the docker container.

if only used `docker stop` 、`docker start` will not cause the key id changed.

So to solve my problem is to deal with the problem that the **keyid** will change

**Comment by xyfy** [comment]
So to solve my problem now is to deal with the problem that the **keyid** will change

**Comment by xyfy** [comment]
I found the key stored in a file ,which named ' tempkey.rsa' and locate in the webroot directory.

**Comment by CliffordSpainhour** [comment]
> I cannot understand the following paragraph and code
> what's the `SigningKeys` used for?
> 
> > I was able to use this test code on start up of my api server to check if my KeyId changed on restart
> > ```
> > var authAuthority = configuration["AuthServer:Authority"];
> > 
> > IConfigurationManager<OpenIdConnectConfiguration> configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>($"{authAuthority}/.well-known/openid-configuration", new OpenIdConnectConfigurationRetriever());
> > OpenIdConnectConfiguration openIdConfig = configurationManager.GetConfigurationAsync(CancellationToken.None).Result;
> > 
> > var test = openIdConfig.SigningKeys;
> > ```

This is just debug code to see if if the signing keys change on restart, not really  used for anything.

**Comment by xyfy** [comment]
I guess it may relation to the `tempkey.jwk` file
