### ISSUE TITLE
Add custom property to user entity Angular

### ISSUE THREAD

**Issue by gcarrot** [abpframework/abp#6252]
ABP Framework version: 3.2.1
User Interface: Angular

I went by this community tutorial https://community.abp.io/articles/how-to-add-custom-property-to-the-user-entity-6ggxiddr

But on UI site I cannot see this properties. Is there other possibility or we need to create custom component? For our case we need to have one select list for this property.

**Comment by bnymncoskuner** [comment]
Hello @gcarrot, 

Object extensions for `@abp/ng.identity` package is available starting from version `4.1.0-rc.1`. I just applied everything in the article with the newest version. I didn't have to do anything on the frontend. The table got rendered with the two extra columns as follows:

![image](https://user-images.githubusercontent.com/1609114/102787739-9cde8300-43b2-11eb-82a7-4f33ec892241.png)

If possible, could you update your `ABP` packages to the latest version and try it again?
