### ISSUE TITLE
Could not find a menu item with given name : Abp.Application.Main.Administration

### ISSUE THREAD

**Issue by minitoma** [abpframework/abp#6253]
Hi guys, 

I'm working with abp and blazor and i'm trying to add a custom item to the Administration Menu.
I had it working but since update 3.3.1, i can't manage to make it work again.
Could you guys maybe help me find the problem so i can solve this ?

here is the issue :
![image](https://user-images.githubusercontent.com/18395682/99509066-98731480-2985-11eb-89b0-407bff268c19.png)

and here is the source code causing troubles from my ConfigureMainMenuAsync(MenuConfigurationContext context) in the MenuContributor file.

```
if (await context.IsGrantedAsync(AppAffaireSpePermissions.Administration))
            {
                context.Menu.GetAdministration().AddItem(
                    new ApplicationMenuItem(
                        "AppAffaireSpe.Administration.Constructeurs",
                        l["Menu:Administration:Constructeurs"],
                        url: "/Administration/Constructeurs",
                        icon: "fa fa-truck-loading")
                    );
            }
```

Thanks in advance.

Keep doing this great job on ABP.

**Comment by maliming** [comment]
Maybe you can refer to https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services
