### ISSUE TITLE
Blazor UI Basic Theme: Wrap pre-built module pages into a card for a better visual

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6256]
Current UI:

![image](https://user-images.githubusercontent.com/1210527/99521618-b2bcea80-29a5-11eb-9c97-3afa4df5eeb3.png)

I think it is better to be in a card just like we do in [the tutorial](https://docs.abp.io/en/abp/4.0/Tutorials/Part-9?UI=Blazor&DB=EF):

![image](https://user-images.githubusercontent.com/1210527/99521830-f31c6880-29a5-11eb-94ed-012b941fc1c1.png)

Apply for identity & tenant management modules.

**Comment by SuriyaArul** [comment]
How to add custom View option in User UI (Action button) in abp.io Blazor UI

**Comment by cotur** [comment]
![image](https://user-images.githubusercontent.com/20099739/99878941-fd469d00-2c19-11eb-8f48-5abd5845d1b2.png)

**Comment by SuriyaArul** [comment]
Hi @cotur thanks for you reply, but I need to add customize View option in red mark of below screenshot in User Blazor UI
![Users](https://user-images.githubusercontent.com/68591063/99897672-806efe00-2cc1-11eb-9b04-6ea298f47948.png)

**Comment by SuriyaArul** [comment]
Hi @cotur thanks for your reply, but I need to add customize View options after Delete in red mark of below screenshot for my purpose in User Blazor UI.
![UsersList](https://user-images.githubusercontent.com/68591063/99897900-7bab4980-2cc3-11eb-8c93-5b56547ec0c5.png)
