### ISSUE TITLE
Layout Hooks for the Blazor UI

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6261]
We can create a layout hooks system for the Blazor UI as similar to the [MVC UI Layout Hooks](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Layout-Hooks).
This is not so essential since the `index.html` is already in the application side.

**Comment by kbowma** [comment]
When integrating Kendo UI for Blazor, without the layout hooks and access to the MainLayout.razor where do we put this code
```
@inherits LayoutComponentBase

<TelerikRootComponent>
    @Body
</TelerikRootComponent>
```
