### ISSUE TITLE
Use environment variables to configure Angular without rebuild

### ISSUE THREAD

**Issue by jogoertzen-stantec** [abpframework/abp#6264]
Right now it seems a new ABP Framework application template project uses [the default "build time" approach to configure an Angular application for multiple environments](https://angular.io/guide/build) (ie. one build per environment).

Are there any plans to add support for dynamic "run time" configuration of Angular applications based on environment variables to ABP Framework?

See the links below for more information on this concept.

[How to use environment variables to configure your Angular application without a rebuild](https://www.jvandemo.com/how-to-use-environment-variables-to-configure-your-angular-application-without-a-rebuild/)
[Handling Angular environments in continuous delivery](https://medium.com/angular-in-depth/handling-angular-environments-in-continuous-delivery-eeaee96f0aae)

**Comment by bnymncoskuner** [comment]
ABP already supports this out of the box. You can find more information about how to achieve this [here](https://docs.abp.io/en/abp/latest/UI/Angular/Environment#remoteenvironment)
