### ISSUE TITLE
How to show a setup screen if ConnectionString is not provided?

### ISSUE THREAD

**Issue by kishoresahas** [abpframework/abp#6265]
### Documentation

https://docs.abp.io/en/abp/latest/Connection-Strings

### Feature requests

* **ABP Framework version v3.3**.
* **User Interface** N/A
* Exception message N/A
* Steps needed to **reproduce** the problem. N/A

How to add a check before the application start? 
If the connection string is not present and Redirect to a Setup Screen.

**Comment by hikalkan** [comment]
I think this is a common asp.net core development question and you can ask on stackoverflow.
To be a hint: You can write an aspnet core middleware that checks the connection string and provides an alternative pipeline if so. See also https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware for middleware branching.
