### ISSUE TITLE
WPF template 

### ISSUE THREAD

**Issue by mbaddi** [abpframework/abp#6266]
#abp #4.0.0 r3 #wpf 

hello , 
I can't create new project with wpf template .
![image](https://user-images.githubusercontent.com/34626951/99586055-790cd380-29e7-11eb-8ea3-cdd532866637.png)

**Comment by maliming** [comment]
hi @mbaddi  We will fix this, thanks.

**Comment by hikalkan** [comment]
Fixed. You can try this:

````bash
abp new MyProject -t wpf --preview
````

Use preview until 4.0 final release.
