### ISSUE TITLE
Doco: BlazorUI- Toolbars.md

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#6267]
### Implementing the IToolbarContributor interface

https://github.com/abpframework/abp/edit/dev/docs/en/UI/Blazor/Toolbars.md

Sample code refers to type `Notification` - I search the entire framework - cannot find it...

![image](https://user-images.githubusercontent.com/40014477/99610137-316c6300-2a4c-11eb-9712-c4e05f8c2762.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/blob/dev/docs/en/UI/Blazor/Toolbars.md#example-add-a-notification-icon

![image](https://user-images.githubusercontent.com/6908465/99610588-177f5000-2a4d-11eb-9093-11eefda8fb10.png)

**Comment by 274188A** [comment]
aha - got it
