### ISSUE TITLE
Blazor webassemble not usable. Can it be redone as Blazor ServerrSide?

### ISSUE THREAD

**Issue by rsatter** [abpframework/abp#6269]
I took the Blazor template to build a site. The results are horrible. To bring up the index page was fast from the site but 20-30 seconds depending on a browser (Safari, Chrome, and Edge) for Blazor to render the index.razor page. All I did was create the solution and hit run. This kind of performance is unacceptable, and I am using a 6 core MacBook.

I actually was surprised it was a web assembly app. I was expecting the template to be a Blazor serverside example. Blazor client is really not ready for production given the incredibly slow performance.

**Comment by NecatiMeral** [comment]
Do you have Redis up and running?

If I remember correctly, they're using Redis by default. So if your redis isn't launched, the application will run into a timeout before rendering anything.

This issue should be logged in your console.

**Comment by hikalkan** [comment]
Hi rsatter,

The performance is related to the Blazor, not because of the ABP Framework in general. However, it is much faster for me. At most 3-4 seconds to initialize the application.

Redis in not needed if you didn't create your solution with separate identityserver.

Server side blazor support [in the plan](https://github.com/abpframework/abp/issues/5517). However, Blazor is pretty new and I believe Blazor WebAssembly is the future.

I am closing this issue since we can't repeat 20-30 seconds initialization time.

**Comment by Stirda** [comment]
@NecatiMeral I experience same slowness with my Firefox 83: about 30 seconds to load fully index page (even with ABP 4.0.0-rc.4). But, still with ABP 4.0.0-rc.4, if I load with my Chrome 87, it takes only 7 seconds. Yes: 4x faster.

**Comment by leonkosak** [comment]
Well, I made "production" deployment to Docker environment (abp Commercial v4.0.2, Tiered (separated Identity Server), Blazor).

Loading first page (when browser has nothing in cache) takes 37-75 seconds - mostly 37-40 seconds). Login process takes 7-8 seconds.

After browser has application in cache, it takes aprox 8 seconds to load first page and another 7-8 seconds login process.

There are no warnings and error in log files (.IdentityServer and .HttpApi.Host projects), just INF and DBG.

@hikalkan, @stsrki - If we will need to "convert" Blazor WASM app to Server-Side and included [DevExpress components](https://community.abp.io/articles/using-devexpress-blazor-ui-components-with-the-abp-framework-wrpoa8rw), how much work is approximately needed to do such task.
If duration (loading) times which are listed above cannot be improved, Blazor WASM is currently not usable and Server-Side option is needed.

**Comment by stsrki** [comment]
@leonkosak The work on Blazor server-side is already on-way https://github.com/abpframework/abp/issues/5517

It's a larger change, and it requires a change in ABP core projects so it will probably be a breaking change. Hopefully a minimal change.
