### ISSUE TITLE
Consider replacing dots with dashes in setting names

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#6272]
As reported here https://support.abp.io/QA/Questions/557/Please-stop-using-periods--in-setting-names
Azure doesn't accept dots in setting names.

**Comment by maliming** [comment]
I think he can resolve the problem by replace the 'ConfigurationSettingValueProvider'.

I will reply to him.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Settings/Volo/Abp/Settings/ConfigurationSettingValueProvider.cs

**Comment by maliming** [comment]
https://support.abp.io/QA/Questions/557/Please-stop-using-periods--in-setting-names#answer-e14c5e7d-2a90-6568-32ba-39f8f572b110

**Comment by millsaj** [comment]
Any chance we could reconsider implementing the suggested solution by default? Environment variables that include a dot are [invalid](https://unix.stackexchange.com/questions/93532/exporting-a-variable-with-dot-in-it) environment variables in bash. 

For now I can use the solution you suggest in the support thread but it seems like this would be a fairly common problem for people hosting in a linux environment and would be worth supporting officially.

If not maybe we could add a link to this page to the documentation for [settings](https://docs.abp.io/en/abp/latest/Settings).

**Comment by maliming** [comment]
hi @millsaj  We do not plan to change it.
