### ISSUE TITLE
Language select

### ISSUE THREAD

**Issue by d-oit** [abpframework/abp#6282]
Misspelling in the latest pre-release version (4.0.0-rc.3) blazor template: "Deutsche" -> "Deutsch"

Suggestion: Create an string array of used culture code and display the nativeName.

var allCultures = System.Globalization.CultureInfo.GetCultures(System.Globalization.CultureTypes.AllCultures);
string cultureCode = "de";
string langname = allCultures.FirstOrDefault(c => c.Name == cultureCode).NativeName;

**Comment by hikalkan** [comment]
Thanks. I think that's not needed, but we will fix it. Thanks.
