### ISSUE TITLE
Getting error after generating proxy  "You may need an additional loader to handle the result of these loaders"

### ISSUE THREAD

**Issue by kunalpgithub** [abpframework/abp#6283]
I started getting below error after generating proxy.

```
ERROR in ./src/app/proxy/index.ts 1:9
File was processed with these loaders:
 * ./node_modules/@ngtools/webpack/src/index.js
You may need an additional loader to handle the result of these loaders.                                              hese loaders.
> export * as Matches from './matches';
| export * from './match.service';

```

Following are details of  framework and UI, I am using currently.

- ABP Framework Version 3.3.1 (stable)
- User Interface: Angular
- Exception Message.

**I may have created project with older version of ABP Cli framework, and then updated ABP ClI. That couldn't be possible. 

But I don't now how can I update my existing project to latest template.**

**Comment by bnymncoskuner** [comment]
This is a known issue of webpack. You can find the related issue [here](https://github.com/webpack/webpack/issues/10460)

You could upgrade your angular version to 11 which allows you to enable (opt-in) webpack v5.

**Comment by kunalpgithub** [comment]
I tried abp update command but it didn't update my angular version, Do I have to do it manually and update package.json.

Also I get this warning while generating proxy.

abp generate-proxy
[20:24:44 INF] ABP CLI (https://abp.io)
[20:24:44 INF] Version 3.3.1 (Stable)
[20:24:46 WRN] Couldn't determinate version of "@abp/ng.schematics" package.

**Comment by bnymncoskuner** [comment]
Abp-cli does not update angular versions. You should update ng packages yourself. You can follow the official [guideline](https://update.angular.io/)
You don't have to update package.json manually, the `ng update` command does it for you.

You can ignore that warning. It does not cause any errors.

**Comment by kunalpgithub** [comment]
@bnymncoskuner thanks for help. Updating angular 11 and opt in for web pack 5 worked for me.

Need run yarn after opt-in for webpack 5 worked for me.
🤗🤗🤗

**Comment by kunalpgithub** [comment]
solution provided by @bnymncoskuner  worked for me, hence closing issue.
