### ISSUE TITLE
Replacing controller is not possible [BUG ?}

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#6288]
@hikalkan Hi.

I'm using ABP Commercial 3.3.1 with angular.
I have integrated DevExpress reporting into ABP. 
After upgrading to 3.3.1 replacing controllers is not working any more.

After some research i noticed that you commit some changes with RemoveDuplicateController method in AbpServiceConvention.

This RemoveDuplicateController  method removes my controller (message in log):

> Removing the controller Sebit.Web.Reports.EdvinController, Sebit.Web.Reports, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from the application model since it replaces the controller(s): DevExpress.AspNetCore.Reporting.WebDocumentViewer.WebDocumentViewerController, DevExpress.AspNetCore.Reporting.v20.2, Version=20.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a

My controller is derived like this:

```
public class EdvinController : WebDocumentViewerController

public class WebDocumentViewerController : ControllerBase

public abstract class ControllerBase : Controller

```
As you can see GetBaseClasses extended method will allways return more than one bases and my controller will be allways removed.

This is braking change for me, because WebDocumentViewerController is Devexepress class and i can't make it abstract.

Please advice.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/5269

**Comment by sebitsi** [comment]
@realLiangshiwei Thanks for link. But this is not my problem.

I have updated issue. (i have posted it to fast by mistake :(  )

**Comment by hikalkan** [comment]
Should be related to https://github.com/abpframework/abp/issues/5964#issuecomment-717459399

I understand that you can't make it abstract (I don't know why they didn't do it so).

As a workaround, you can replace `AbpServiceConvention` with your own implementation and override `RemoveDuplicateControllers` to skip the logic for the `WebDocumentViewerController`.

I think we can make an exception list or improve the code to not remove classes that hasn't an `[ExposeServices(...)]` attrbibute. I created an issue: https://github.com/abpframework/abp/issues/6297

**Comment by sebitsi** [comment]
@hikalkan Thanks.

I have already done it as you suggested.
Improvements will be fine.
