### ISSUE TITLE
Improve the logic of removing derived controllers from the model

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6297]
see https://github.com/abpframework/abp/issues/6288#issuecomment-731242396

**Comment by hikalkan** [comment]
Resolved by https://github.com/abpframework/abp/commit/be29aece0727bb3c50aa244ef778ebd0626d3531

Now, if the controller doesn't have `ExposeServicesAttribute`, it is not removed.

Also, if you don't want to remove a controller (even with that attribute), you can add the controller type to the `AbpAspNetCoreMvcOptions.IgnoredControllersOnModelExclusion` in the `ConfigureServices` method of your module.

````csharp
Configure<AbpAspNetCoreMvcOptions>(options =>
{
    options.IgnoredControllersOnModelExclusion.Add(typeof(MyController));
});
````

**Comment by sebitsi** [comment]
@hikalkan Great work. Thanks.

Did you update documentation?

**Comment by hikalkan** [comment]
@maliming was that documented & where? I don't remember it?

**Comment by sebitsi** [comment]
@hikalkan I think you can add it into https://docs.abp.io/en/abp/latest/Dependency-Injection
There is all about expose service attribute.

**Comment by maliming** [comment]
I will handle this.

https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller

**Comment by sebitsi** [comment]
@maliming In documentation about dependency injection (https://docs.abp.io/en/abp/latest/Dependency-Injection) there is also section about replacing service. This section is very short. 
Would you be so nice to add link into  this section to "guide overriding services".

**Comment by maliming** [comment]
hi @sebitsi 

Replacing services in dependency injection has nothing to do with removing controllers from the model.

**Comment by sebitsi** [comment]
@maliming Yes you are right. Removing controllers is not related. 

I was not precise enough.
All guide "Overriding services" is related to DI.
