### ISSUE TITLE
Using CSRF/XSRF & Anti Forgery System in IIS

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#6299]
Hi.

I have updated ABP Commercial to latest stable version (3.3.1). After that only get methods work. POST and PUT don't.

Let explain my scenario. 

1. Create new angular project (abp new demo -t app-pro -u angular)
2. Configure and build server side and deploy it to IIS server under (https://demo.test.com/ws)
3. Configure, build as static js files and deploy angular client to IIS server under (https://demo.test.com/admin)

Those steps are nothing special. Pure ABP templates. Configured to work together.

Both server and client are properly configured and work perfect in 3.2.x version. After upgrade to 3.3.1 post and put not working 
anymore. Antiforgery token validation system is blocking post and put execution. 

I read [document](https://docs.abp.io/en/abp/latest/CSRF-Anti-Forgery) twice. :)
I have noticed angular client doesn't set RequestVerificationToken  in header when sending post or put request.
Why ? Is possible reason fact disscussed in this [conversation](https://github.com/angular/angular/issues/36254)

What additional configuration i should make to work multiple apps at one domain / under subfolders ?

If i disable Anti Forgery System everything works again like in 3.2.x version.

**Comment by maliming** [comment]
hi @sebitsi 

Can you share the error log? Include angular and backend.

**Comment by sebitsi** [comment]
Hi @maliming.

I send you 2 pictures of request (user update). 
As you can see server responds with redirection to login page.

![Request1](https://user-images.githubusercontent.com/2194876/99881588-e5bbe400-2c1a-11eb-9067-4a446675bb3f.png)

![Request2](https://user-images.githubusercontent.com/2194876/99881589-e6ed1100-2c1a-11eb-8e72-4867461ccb3e.png)

On server side there is nothing special:

```
2020-11-21 16:46:16.893 +01:00 [INF] Request starting HTTP/1.1 PUT https://demo.xxxxx.xx/cws/api/identity/users/e72b2287-282d-a45d-4da1-39f8ca711757 application/json 349
2020-11-21 16:46:16.895 +01:00 [INF] CORS policy execution successful.
2020-11-21 16:46:16.920 +01:00 [INF] No CORS policy found for the specified request.
2020-11-21 16:46:16.921 +01:00 [INF] Executing endpoint 'Volo.Abp.Identity.IdentityUserController.UpdateAsync (Volo.Abp.Identity.Pro.HttpApi)'
2020-11-21 16:46:16.926 +01:00 [INF] Route matched with {controller = "User", area = "identity", action = "Update", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Identity.IdentityUserDto] UpdateAsync(System.Guid, Volo.Abp.Identity.IdentityUserUpdateDto) on controller Volo.Abp.Identity.IdentityUserController (Volo.Abp.Identity.Pro.HttpApi).
2020-11-21 16:46:16.927 +01:00 [ERR] The required antiforgery header value "RequestVerificationToken" is not present.
2020-11-21 16:46:16.928 +01:00 [INF] Authorization failed for the request at filter 'Volo.Abp.AspNetCore.Mvc.AntiForgery.AbpAutoValidateAntiforgeryTokenAuthorizationFilter'.
2020-11-21 16:46:16.931 +01:00 [INF] Executing HttpStatusCodeResult, setting HTTP status code 400
2020-11-21 16:46:16.931 +01:00 [INF] Executed action Volo.Abp.Identity.IdentityUserController.UpdateAsync (Volo.Abp.Identity.Pro.HttpApi) in 4.5272ms
2020-11-21 16:46:16.931 +01:00 [INF] Executed endpoint 'Volo.Abp.Identity.IdentityUserController.UpdateAsync (Volo.Abp.Identity.Pro.HttpApi)'

```

AutoValidateAntiforgeryTokenAuthorizationFilter failed as expected. But why ? Why client doesn't send token ?
There is no issue on my developement machine. Only on staging server.

**Comment by qiang999** [comment]
I think 4.0 maybe fix this bug.
3.3.1 have a solution.
ConfigureServices add Configure.
Configure<AbpAntiForgeryOptions>(options =>
            {
                options.TokenCookie.Expiration = TimeSpan.FromDays(365);
                options.AutoValidateIgnoredHttpMethods.Add("GET");
                options.AutoValidateIgnoredHttpMethods.Add("DELETE");
                options.AutoValidateIgnoredHttpMethods.Add("PUT");
                options.AutoValidateIgnoredHttpMethods.Add("POST");
                options.AutoValidateFilter =
                    type => !type.Namespace.StartsWith("BPM.HttpApi");
            });
POST and PUT don't,should retun 400.
Get methods work,because AutoValidateIgnoredHttpMethods default contains get.
or Controller action add [IgnoreAntiforgeryToken]
eg:
[HttpPost]
[IgnoreAntiforgeryToken]

**Comment by sebitsi** [comment]
@qiang999 Hi. Thanks for your response.

Disabling auto validation is not solution for me.
Why do you think 4.0 may fix this ? And how do you know this is a bug ?

**Comment by qiang999** [comment]
I I found a change at 4.0.
context.Services.AddAbpSwaggerGenWithOAuth(
                configuration["AuthServer:Authority"],
                new Dictionary<string, string>
                {
                    {"test", "test API"}
                },
                options =>
                {
                    options.SwaggerDoc("v1", new OpenApiInfo {Title = "test API", Version = "v1"});
                    options.DocInclusionPredicate((docName, description) => true);
                    options.CustomSchemaIds(type => type.FullName);
                });
I think 4.0 maybe fix this bug.

**Comment by qiang999** [comment]
> I I found a change at 4.0.
> context.Services.AddAbpSwaggerGenWithOAuth(
> configuration["AuthServer:Authority"],
> new Dictionary<string, string>
> {
> {"test", "test API"}
> },
> options =>
> {
> options.SwaggerDoc("v1", new OpenApiInfo {Title = "test API", Version = "v1"});
> options.DocInclusionPredicate((docName, description) => true);
> options.CustomSchemaIds(type => type.FullName);
> });
> I think 4.0 maybe fix this bug.

https://github.com/abpframework/abp/issues/5803

**Comment by sebitsi** [comment]
@qiang999 Thanks for sharing ideas.
But this is not related with my issue.

Commit you found is for swaggerUI client. It needs to send token if user wants to execute  method in swagger UI.

As i said. My problem is pure ABP template deployed to ISS. This client doesn't send anti forgery token when deploy to IIS 
in subfolder.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/blob/dev/docs/en/CSRF-Anti-Forgery.md#angular-ui

**Comment by sebitsi** [comment]
@realLiangshiwei 

I'm sorry.

What should i look at ?
I'm aware of HttpClientXsrfModule. 
I'm using official template from Volosoft and it is included in CodeModule by default.
Client works on local machine but not in scenario i mentioned.

**Comment by maliming** [comment]
hi @bnymncoskuner

Do you have any idea?

**Comment by f-belhocine** [comment]
Hi all,
I have exactly the same issue after upgrading to *Abp 3.3.1*.
Get actions work correctly but POST,PUT and DELETE return 400 HttpStatus.
In the Logs file i get :
2020-11-24 13:04:26.326 +01:00 [ERR] The required antiforgery header value "RequestVerificationToken" is not present.
2020-11-24 13:04:26.328 +01:00 [INF] Authorization failed for the request at filter 'Volo.Abp.AspNetCore.Mvc.AntiForgery.AbpAutoValidateAntiforgeryTokenAuthorizationFilter'.

**Comment by f-belhocine** [comment]
Doing that for REST API controllers resolved the issue.

Configure<AbpAntiForgeryOptions>(options =>
            {
                options.AutoValidate = false;
            });

**Comment by f-belhocine** [comment]
Hi all,
I resolved the issue by disabling AutoValidateAntiForgeryToken in the REST API module.

`Configure<AbpAntiForgeryOptions>(options =>
            {
                options.AutoValidate = false;
            });`

**Comment by sebitsi** [comment]
Hi @f-belhocine 

This is not solution. It's workaround.
The problem is in HttpClientXsrfModule. It has limitations. 
Look at this [stackoverflow](https://stackoverflow.com/questions/50510998/angular-6-does-not-add-x-xsrf-token-header-to-http-request). 

I have tried to use url without http or https in front. Then  AutoValidateForgeryToken works again.

We will see what guys in Volosoft will say about this.

**Comment by bnymncoskuner** [comment]
Hello all,

I have seen that there is some confusion about how this token works. First, I'll give you the solution and then talk about the details.

The solution is simple. If you serve both your angular application and APIs from the same domain, you don't give the full path of APIs in `environment.ts`, instead, you give a relative path. 
Let's look at the example given in the post; 

Your APIs is hosted at `https://demo.test.com/ws`
Your angular application is hosted at `https://demo.test.com/admin`

So if your API request should look like this `https://demo.test.com/ws/api/identity/users`

your `environment.prod.ts` has to be as follows:

```typescript
export const environment = {
  production: true,
  // ....
  apis: {
    default: {
      url: '/ws', // <- just use the context root here
     // ...
    },
  },
} as Config.Environment;
```

Let's talk about why.

First, take a look at [Angular's code](https://github.com/angular/angular/blob/master/packages/common/http/src/xsrf.ts#L81)

It does not intercept any request that starts with `http://` or `https://`. There is a good reason for that. Any cross-site request does not need this token for security. This verification is only valid if the request is made to the same domain from which the web page is served. So, simply put, if you serve everything from a single domain, you just use a relative path.

I'll update the docs for this particular case. I have seen some other people were having a problem with this as well and it should be addressed in the docs.

**Comment by sebitsi** [comment]
@bnymncoskuner Thanks for your good explanation.

Everything is logical now to me.

Yes please update docs. This should be fine.

I will left this issue open. Close it  freely when documents will be updated.

**Comment by bnymncoskuner** [comment]
Just updated the docs, it should be available soon. Closing this issue. Thanks for the input

**Comment by rocky-upadhaya** [comment]
> Hello all,
> 
> I have seen that there is some confusion about how this token works. First, I'll give you the solution and then talk about the details.
> 
> The solution is simple. If you serve both your angular application and APIs from the same domain, you don't give the full path of APIs in `environment.ts`, instead, you give a relative path. Let's look at the example given in the post;
> 
> Your APIs is hosted at `https://demo.test.com/ws` Your angular application is hosted at `https://demo.test.com/admin`
> 
> So if your API request should look like this `https://demo.test.com/ws/api/identity/users`
> 
> your `environment.prod.ts` has to be as follows:
> 
> ```ts
> export const environment = {
>   production: true,
>   // ....
>   apis: {
>     default: {
>       url: '/ws', // <- just use the context root here
>      // ...
>     },
>   },
> } as Config.Environment;
> ```
> 
> Let's talk about why.
> 
> First, take a look at [Angular's code](https://github.com/angular/angular/blob/master/packages/common/http/src/xsrf.ts#L81)
> 
> It does not intercept any request that starts with `http://` or `https://`. There is a good reason for that. Any cross-site request does not need this token for security. This verification is only valid if the request is made to the same domain from which the web page is served. So, simply put, if you serve everything from a single domain, you just use a relative path.
> 
> I'll update the docs for this particular case. I have seen some other people were having a problem with this as well and it should be addressed in the docs.

**This should be documented and be in top of the page when anyone googles Hosting ABP and Angular in the same URL. This solved my issue as well. Thank you**
