### ISSUE TITLE
Blob store abstraction

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#63]
- [ ] Blob store abstraction.
- [ ] File system implementation.
- [ ] Database implementation.
- [ ] Azure Blob storage implementation.

Note: We may have named stores and different stores can be implemented by a different provider (providers are configurable per store).

**Comment by hitaspdotnet** [comment]
@hikalkan Hi,
I'm working on a File System provider and Amazon, Blob, local storage.
Here is the [My initial Project](https://github.com/HitaspSolutions/Storage/tree/master/src)
Please, I have two newbie questions:
1. How to get Webroot content from framework layer
2. How to create PreIntiliaze configuration for configuring requirement at the Application layer? I think appSettings.json is the easy way for this. [This is my tried](https://github.com/HitaspSolutions/Storage/blob/master/src/Hitasp.Storage.AzureBlob/Hitasp/Storage/AzureBlob/AzureStorageManager.cs)

**Comment by hikalkan** [comment]
Hi,

1. Inject IHostingEnvironment and get WebRoot path/fileprovider.
2. Use Microsoft.Extensions.Configuration style Options pattern instead of directly getting from the IConfigurationRoot. You can read MS document: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1
We are using this pattern in all modules of the framework.

**Comment by hikalkan** [comment]
Closed for https://github.com/abpframework/abp/issues/4092
