### ISSUE TITLE
[Question] How can I add my parameters while getting list of entities dto

### ISSUE THREAD

**Issue by eng-mohammed-emam** [abpframework/abp#6300]
Hello,

I'm using version 3.3.1

How can I send my additional parameters to the `query` parameter?
I already inhert from PagedAndSortedResultRequestDto.

const bookStreamCreator = (query) => this.bookService.getList(query);

export interface BooksSearchParamsDto extends PagedAndSortedResultRequestDto {
  isbn: string;
  name: string;
}

**Comment by maliming** [comment]
hi

Maybe you can refer to https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services

**Comment by eng-mohammed-emam** [comment]
Hello,
According to the latest document of ABP Framework version 3.3.1,

https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=NG&DB=EF#bookcomponent

In this document, I want to search by `isbn` and `bookName` instead of getting all books from the database.

How can I pass these additional search criteria to the `query` variable in the following statement:

    ngOnInit() {
        const bookStreamCreator = (query) => this.bookService.getList(query);

        this.list.hookToQuery(bookStreamCreator).subscribe((response) => {
          this.book = response;
        });

**Comment by maliming** [comment]
> How can I pass these additional search criteria to the query variable in the following statement:

@mehmet-erim Can you help?

**Comment by mehmet-erim** [comment]
Hello @eng-mohammed-emam

You can extend the `query` parameter of the `ListService`'s `hookToQuery` method. 

Firstly you should pass your own type to ListService as shown below:

```ts
constructor(public readonly list: ListService<BooksSearchParamsDto>) { }
```

Then update the `bookStreamCreator` constant like following:

```ts
const bookStreamCreator = (query) => this.bookService.getList({...query, name: 'name here', isbn: 'isbn here'});
```

You can also create your params object.

Define a variable like this:

```ts
booksSearchParams = {} as BooksSearchParamsDto;
```

Update the `bookStreamCreator` constant:

```ts
const bookStreamCreator = (query) => this.bookService.getList({...query, ...this.booksSearchParams});
```

Then you can place inputs to the HTML:

```html
<div class="form-group">
  <input
    class="form control"
    placeholder="Isbn"
    (keyup.enter)="list.get()"
    [(ngModel)]="booksSearchParams.isbn"
  />
  <input
    class="form control"
    placeholder="Name"
    (keyup.enter)="list.get()"
    [(ngModel)]="booksSearchParams.name"
  />
</div>
```

`ListService` emits the `hookToQuery` stream when you call the `this.list.get()` method.

**Comment by eng-mohammed-emam** [comment]
Dear @mehmet-erim

Thanks for your solution. It solves my problem.

I faced a new problem and hope you help. 
Is there any way to reset the selected page in the paginator UI to 1 every time a new search is done?

For example,
If the selected page in the paginator is 20 and the new search result is 3 pages, I want sometimes to tell UI to select page # 1.

When I set the property `skipCount = 0;`, it doesn't work.

**Comment by mehmet-erim** [comment]
To achieve this, add `offset` input to the `ngx-datatable` tag like this:

```html
    <ngx-datatable
      ...
      [offset]="list.page"
    >
```

You can change the page value as below:

```ts
// your component

this.list.page = 0;
```

**Comment by eng-mohammed-emam** [comment]
Dear @mehmet-erim,

Thanks again.

I hope to mention the solution of adding additional parameters to search criteria in the ABP documentation even as a note.

**Comment by joernz** [comment]
Hi @mehmet-erim

Can we also have it added to the bookstore tutorial someday please? (I see it's already in the ListService documentation.) 

My question:
Does the `GetListAsync` method of `CrudAppService` still need to be overridden after and get the `BooksSearchParamsDto` passed to as input for the filtering?

Thanks

**Comment by maliming** [comment]
> Does the GetListAsync method of CrudAppService still need to be overridden after and get the BooksSearchParamsDto passed to as input for the filtering?

Yes, You need to filter your parameters manually.
