### ISSUE TITLE
Blazor UI: Mange Profile Page - No Menu Visible

### ISSUE THREAD

**Issue by kbowma** [abpframework/abp#6303]
There is no menu visible and now way to return to the previous page when on the Mange Profile page.

AbpFramework Versions: 4.0.0-rc.3 (commercial)

![image](https://user-images.githubusercontent.com/4893279/99883897-10884700-2bdf-11eb-801f-52157751647a.png)

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io/QA/Questions/New Thanks.

**Comment by realLiangshiwei** [comment]
Hi,

See https://github.com/abpframework/abp/pull/6778. We have fixed this problem.
