### ISSUE TITLE
Guide: Implementing Domain Driven Design

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6304]
I had a talk on Implementing Domain Driven Design in the last year. This is the YouTube video record of the talk: https://www.youtube.com/watch?v=Yx3Y3-GC9EE

I decided to create a guide based on this talk & presentation in the ABP documentation. Also, in each step I will introduce the infrastructure provided by the ABP Framework and discuss best practices, pros and cons of different ways.

I think this will be a integrative document that will be helpful everyone to learn the DDD and how to implement it with the ABP Framework.

You can track the progress here: https://docs.abp.io/en/abp/4.0/Domain-Driven-Design-Implementation-Guide

**Comment by xyfy** [comment]
grreet job!

**Comment by hikalkan** [comment]
Just started: https://github.com/abpframework/abp/blob/rel-4.0/docs/en/Domain-Driven-Design-Implementation-Guide.md

**Comment by hikalkan** [comment]
I have some notes to improve the guide, but it is initially done: https://docs.abp.io/en/abp/4.0/Domain-Driven-Design-Implementation-Guide
