### ISSUE TITLE
ABP framework es-ES translation

### ISSUE THREAD

**Issue by jmglezgz** [abpframework/abp#6305]
The abp-translation.abp.es-ES translation has been updated with missing parts and now is 100% completed.

[abp-translation.abp.es-ES.zip](https://github.com/abpframework/abp/files/5578208/abp-translation.abp.es-ES.zip)

If you have any other documents to translate, only let me know.

**Comment by realLiangshiwei** [comment]
Hi, You can send a PR to this repo.

**Comment by jmglezgz** [comment]
Sure, np... However, I don't know how to convert the json structure that @ebicoglu sent me (zip file attached to this issue) to the json structure needed on Localization/Resources folder.

Any help?

Thanks

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/CLI#translate

Or I can help you send the PR
