### ISSUE TITLE
Abp suite "save and generate" disabled after choosing to add a navigation property and then cancelling the dialog

### ISSUE THREAD

**Issue by michaelsudnik** [abpframework/abp#6306]
4.0.0-rc.3
MVC
MongoDB

After defining a new entity for an existing solution with the above configuration, I have defined some properties (so I am now allowed to generate). If I then click the "Add navigation property" button, but change my mind and cancel the dialog, the "Save and generate" is no longer enabled, and there does not appear to be any way to enable it again. I am forced to refresh the page and start defining my entity again.

**Comment by maliming** [comment]
hi @michaelsudnik 

You get help on [support.abp.io](https://support.abp.io/QA/Questions/New), Thanks.

**Comment by michaelsudnik** [comment]
I understand that, but I was confident that this was a bug - so thought I would raise it here directly. I'll put everything on the support site moving forward.
