### ISSUE TITLE
is there React UI Template, we can expect in future.

### ISSUE THREAD

**Issue by kunalpgithub** [abpframework/abp#6312]
Just wanted to check if team is planning to build UI template for react as well. 

React is becoming first choice for front end development now days compared to angular. Although for mobile you have react-native template, but I was wondering why you don't have UI template for react.

Also want to know why you prefer Angular or React.

**Comment by realLiangshiwei** [comment]
It's in a backlog, no plans yet
See https://github.com/abpframework/abp/issues/1638
