### ISSUE TITLE
Customize Blazor user UI in abp.io

### ISSUE THREAD

**Issue by SuriyaArul** [abpframework/abp#6313]
Hi, I need to add customize View options after Delete in red mark of below image for my purpose in Blazor UI.
( Abpframework : 3.3.0-rc.1, Blazor UI/Razor pages )
![UsersList](https://user-images.githubusercontent.com/68591063/99934468-10757c00-2d84-11eb-9210-5b08cdc3744d.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/6647
