### ISSUE TITLE
Nuget Packages Separate Versioning

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#632]
Hi,

The nuges packages of Volo.Asp.* has the same version. I think it is not as should be. I mean it doesn't show of which has changed nor which should needed update or retest. It is an idea after all, what do you thinking for it ?

https://www.nuget.org/packages?q=Volo.abp

**Comment by hikalkan** [comment]
Packages depends on each other and not possible to separately version them except some hot fix / patch releases.
Microsoft also does like that. This makes easy to develop, test, version, deploy and use.
If we need to know what's changed, "change logs" is for that :)
