### ISSUE TITLE
Json parse boolean value error cause exception in feature management modal saving

### ISSUE THREAD

**Issue by Coolioyang** [abpframework/abp#6321]
**ABP Framework version. 4.0.0-RC3**
**UI: Angular**
Exception message and stack trace if available (check the logs). 

> 
> 2020-11-24 13:05:07.499 +08:00 [INF] Executing endpoint 'Volo.Abp.FeatureManagement.FeaturesController.UpdateAsync (Volo.Abp.FeatureManagement.HttpApi)'
> 2020-11-24 13:05:07.500 +08:00 [INF] Route matched with {area = "featureManagement", action = "Update", controller = "Features", page = ""}. Executing controller action with signature System.Threading.Tasks.Task UpdateAsync(System.String, System.String, Volo.Abp.FeatureManagement.UpdateFeaturesDto) on controller Volo.Abp.FeatureManagement.FeaturesController (Volo.Abp.FeatureManagement.HttpApi).
> 2020-11-24 13:05:07.507 +08:00 [WRN] ---------- RemoteServiceErrorInfo ----------
> {
>   "code": null,
>   "message": "\u4F60\u7684\u8BF7\u6C42\u65E0\u6548!",
>   "details": "\u9A8C\u8BC1\u65F6\u53D1\u73B0\u4EE5\u4E0B\u9519\u8BEF.\r\n - The JSON value could not be converted to System.String. Path: $.features[0].value | LineNumber: 0 | BytePositionInLine: 54.\r\n",
>   "data": {},
>   "validationErrors": [
>     {
>       "message": "The JSON value could not be converted to System.String. Path: $.features[0].value | LineNumber: 0 | BytePositionInLine: 54.",
>       "members": [
>         "$.features[0].value"
>       ]
>     }
>   ]
> }
> 

**Steps to reproduce.**
1. use CLI create new project:  ` abp new Boyo.CRM -t app --ui angular --separate-identity-server --preview`
2. add custom feature definition provider.
3. build and execute.

- Json convert faild on feature value true/false;

![image](https://user-images.githubusercontent.com/27847846/100054706-8bf72c00-2e5d-11eb-929f-7cf80b550411.png)

- i use powser shell script test again, change true to "true": 

![image](https://user-images.githubusercontent.com/27847846/100054740-9e716580-2e5d-11eb-9617-f9ef5d799834.png)
![image](https://user-images.githubusercontent.com/27847846/100054834-d11b5e00-2e5d-11eb-98c3-7218d4fe0f8b.png)
Exceuted successfully.

so , it looks like FeatureAppService.UpdateAsync parameter UpdateFeatureDto cannot  been parse correctly.

**Comment by maliming** [comment]
hi
It is already solved, Please try when RC4 is available, Maybe today.

https://github.com/abpframework/abp/pull/6236
