### ISSUE TITLE
Generic API Controllers removed after upgrading to Abp 3.3.1

### ISSUE THREAD

**Issue by f-belhocine** [abpframework/abp#6327]
Hi all,
I have created generic controllers in the HttpApi project module and registred them as intended by AspNetCore based on ControllerNamingConvention.
All worked correctly when using Abp version 3.0.1.
yesterday i upgrared my modules to the latest stable version 3.3.1 and all noticed that all my generic API conttrollers were not visible in the swagger page; after refining I found in the logs lines that indicated that the controllers were removed.

**Abp version**.
3.3.1
* Exception message and **stack trace** if available (check the logs).
No exception but logs contain these lines :
2020-11-23 15:15:27.980 +01:00 [INF] Removing the controller Itcomp.ReferenceData.Localities.LocalityController`7[
2020-11-23 15:15:27.982 +01:00 [INF] Removing the controller Itcomp.ReferenceData.Localities.LocalityLookupController`5

* Steps needed to **reproduce** the problem.
Generic controllers created
LocalityController<,,,,,,>
LocalityLookupController<,,,,>

**Comment by f-belhocine** [comment]
I found the source of the issue, it's from the class
Volo.Abp.AspNetCore.Mvc.Conventions.AbpServiceConvention
the method RemoveDuplicateControllers.
And in my case the LocalityController<,,,,,,> inherits from CodableReferenceDataController<,,,,,,> and both are not abstract controller classes because the LocalityController add features to the base controller and it is as designed.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/6288 https://github.com/abpframework/abp/issues/6297

**Comment by f-belhocine** [comment]
Thank you @maliming 
so before upgrading to Abp 4.0 the only way is to override AbpServiceConvention.

**Comment by maliming** [comment]
Right.
