### ISSUE TITLE
Real Time Notification System

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#633]
#37

**Comment by ugurozturk** [comment]
@Nokecy 

https://github.com/abpframework/abp/issues/40

**Comment by Nokecy** [comment]
any plan? @hikalkan

**Comment by hikalkan** [comment]
It is in plan, but not started to work on yet.

**Comment by Nokecy** [comment]
Is it included in version 1.0?

**Comment by hikalkan** [comment]
Yes. Planned to be in v1.0.

**Comment by chenxinyong** [comment]
what time?

**Comment by chenxinyong** [comment]
> Yes. Planned to be in v1.0.

what time?

**Comment by ismcagdas** [comment]
See roadmap section in https://blog.abp.io/abp/ABP-v0-19-Release-With-New-Angular-UI

**Comment by yekalkan** [comment]
> So, you can expect ABP v1.0 to be released in the first half of the October. We are very excited and working hard on it.

see https://blog.abp.io/abp/ABP-v0-19-Release-With-New-Angular-UI

**Comment by Nokecy** [comment]
any update?

**Comment by carloszan** [comment]
is there any prediction? if not, i could help it

**Comment by hikalkan** [comment]
No time prediction.
See the road map: https://docs.abp.io/en/abp/latest/Road-Map (almost ordered by priority)

This is not a core framework feature. I suggest you to create in your own application if you need to it in the short term.

**Comment by tinonetic** [comment]
> is there any prediction? if not, i could help it

Hi @carloszan, have you worked on this?

We may have a requirement for it.

If you are up for it, we can create a repository and invite contributors

**Comment by danghung-dev** [comment]
I see that this issue is label with high priority. 
Any update on this issue?
Do you have plan for this feature? @hikalkan

**Comment by hikalkan** [comment]
Hi,

As a said before, actually, this is not a core framework feature, but is an application feature. We will consider to implement as a module, but probably it will be an ABP Commercial module (with some abstractions in a framework package).
I am closing this since we are not clear about this feature. Once we clear, we re-open it.

If you need such a feature, it is much more easier to develop for your own application.
