### ISSUE TITLE
CurrentUser not changed when user is updated

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#6335]
Hi

I am having issues with [CurrentUser](https://docs.abp.io/en/abp/latest/CurrentUser#current-user) not being updated when the current user is modified. If I for example use the UI to change email of the user the email in ICurrentUser is not refreshed, same issue when setting the users email to confirmed.

Is this by design or is it a bug?

**ABP Framework version** : 3.3.1

**Comment by maliming** [comment]
You can reissue claims according to your authentication scheme. Or you can always get email and other info through the user id,

**Comment by martenw** [comment]
Ok, so it is by design? But if ICurrentUser cannot be trusted to have correct data in the default setup does that not limit its use a lot? 

If I should modify claims, can I monitor some event or flag to know when ICurrentUser need to be refreshed?

**Comment by gdlcf88** [comment]
CurrentUser is a shortcut to get claims.

**Comment by martenw** [comment]
That is a better description I guess, I have changed my app now to get user by Id instead of using CurrentUser when I need user information, I guess adjusting this description in docs could help others to not make my mistake:

> ICurrentUser is the main service to get info about the current active user.
