### ISSUE TITLE
ORA-12899: value too large for column "ABDEV"."ABPAUDITLOGS"."EXCEPTIONS" (actual: 4000, maximum: 2000) 

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#6341]
3.2.0 / angular.

Sometimes this error:

> ORA-12899: value too large for column "ABDEV"."ABPAUDITLOGS"."EXCEPTIONS" (actual: 4000, maximum: 2000) 

Is it possible to configure for avoiding (truncate exception text, etc.)?

**Comment by maliming** [comment]
hi @alexandis 

You can try to change the `MaxExceptionsLengthValue ` then add new migrations.

https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/modules/audit-logging/src/Volo.Abp.AuditLogging.Domain.Shared/Volo/Abp/AuditLogging/AuditLogConsts.cs#L41

**Comment by alexandis** [comment]
How am I supposed to fix this now? The mentioned constant is not present anymore (ABP version 5.1.2).
