### ISSUE TITLE
Regarding the number of failed login attempts to unlock the user domain service account

### ISSUE THREAD

**Issue by git102347501** [abpframework/abp#6346]
GitHub Issues

ABP Version: 3.2
Type: Angular

I need to write an application service that unlocks frozen accounts. I used the following method to set the lock date to null to achieve the purpose of unlocking.
`IdentityUserManager.SetLockoutEndDateAsync(user, null);`

But I found that just clearing the lock date is problematic.

For example, I set the system to freeze login after three incorrect passwords.
First, user A turned off the account freeze function, and then logged in 6 times and failed to freeze, which is in line with normal logic.
Then user A turned on the account freeze, and after another wrong input, the account was immediately frozen, which did not meet the correctness of the number of errors set by me.
This issue causes users who have entered incorrectly more than the set number of times and the account freeze function is not enabled. After the account freeze function is turned on, any password input error will be frozen immediately.

The reason is probably because ABP’s user domain service did not clear the account at the same time when unlocking the account. AccessFailedCount.

Then I wanted to clear it myself, but found that the attribute is protected and cannot be changed.
`public virtual int AccessFailedCount {get; protected internal set;}`

Ask, is this consistent with the basic logical correctness of the error lock account function?

**Comment by git102347501** [comment]
I emptied the AccessFailedCount later and found that the problem still occurs. The reason may be because the LockoutEnabled of the account was not judged when the SetLockoutEndDateAsync was operated.
```
/// <summary>
/// Locks out a user until the specified end date has passed. Setting a end date in the past immediately unlocks a user.
 /// </summary>
/// <param name="user">The user whose lockout date should be set.</param>
/// <param name="lockoutEnd">The <see cref="DateTimeOffset"/> after which the <paramref name="user"/>'s lockout should end.</param>
/// <param name="cancellationToken">The <see cref="CancellationToken"/> used to propagate notifications that the operation should be canceled.</param>
/// <returns>The <see cref="Task"/> that represents the asynchronous operation.</returns>
public virtual Task SetLockoutEndDateAsync([NotNull] IdentityUser user, DateTimeOffset? lockoutEnd, CancellationToken cancellationToken = default)
{
      cancellationToken.ThrowIfCancellationRequested();

      Check.NotNull(user, nameof(user));

      user.LockoutEnd = lockoutEnd;

       return Task.CompletedTask;
}
```
This error causes that if the user turns off the login freeze, the setting of the lock end time will still be triggered after the specified number of times, but the actual user does not turn on the login freeze.

Then, after the user turns on freezing, it will be frozen immediately.

**Comment by maliming** [comment]
This is related to identity not abp.
