### ISSUE TITLE
[RemoteService(IsMetadataEnabled = false)] ignored for controllers with api versioning

### ISSUE THREAD

**Issue by fk-inspirit-tech** [abpframework/abp#6362]
Version 3.3.1
MVC
GitHub repo: https://github.com/FrancoisKr/APIExplorerPb

Steps to reproduce:
- add a MVC controller
- configure API versioning in ConfigureServices
- configure controller attributes:
[RemoteService(IsMetadataEnabled = false)]
[ApiVersion("3.0")]
[Route("v{version:apiVersion}/test/[action]")]
[ApiController]

The API Explorer still exposes the controller (although incorrectly).

Any other way to specify that a controller should be completely ignored by Swagger?

**Comment by aelhadi** [comment]
Hello,

You can use swagger schema filter.
That's what I'm using 

Regards

**Comment by fk-inspirit-tech** [comment]
This works:
[ApiExplorerSettings(IgnoreApi = true)]
