### ISSUE TITLE
IHttpContextAccessor   _httpContextAccessor

### ISSUE THREAD

**Issue by vijay2358** [abpframework/abp#6363]
I am getting the issue passing the session key between the module and application host.
IHttpContextAccessor   _httpContextAccessor

do you have sample how inject the session that can be access all modules and application host

1. I have created module 
2. set the key at host level 
3. when i access the module the session giving empty
Please help here.

**Comment by maliming** [comment]
hi

Your question seems to have nothing to do with abp, can you explain it in detail?
