### ISSUE TITLE
Having issues when consuming Nuget packages functionality in main solution

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#6366]
3.3.1 / angular

Hi, I've moved some base part (entities, constants, etc.) into Nuget packages and add them as a reference in my main solution:

    [Dependency(ReplaceServices = true)]
    public class LogAuditPropertySetter : IAuditPropertySetter, ITransientDependency

It used to work automatically when it was a part of one solution. Now seems like it does not.
Do I need to register this IAuditPropertySetter implementation manually, if I have it in a separate package? How to do that? Is it like that in Domain Module?

        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddTransient<IAuditPropertySetter, LogAuditPropertySetter>();
        }

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Dependency-Injection
https://docs.abp.io/en/abp/latest/Module-Development-Basics#module-dependencies
