### ISSUE TITLE
Background workers documentation

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#637]

**Comment by leonkosak** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.BackgroundJobs/Volo/Abp/BackgroundJobs/BackgroundJobWorker.cs

These BackgroundWorkers are not designed for use in web farms (clusters) yet (race conditions when deployed on many instances in cluster environment)?

**Comment by hikalkan** [comment]
>These BackgroundWorkers are not designed for use in web farms

For cluster environments, disable background jobs for all instances, except one.
Or use Hangfire integration which has such a concurrency feature.

**Comment by hikalkan** [comment]
I actually has written about background jobs (for hangfire integration). Background workers are just threads ABP knows nothing about what they are performing.

**Comment by hikalkan** [comment]
Already done.
