### ISSUE TITLE
Authorization failed sending email.

### ISSUE THREAD

**Issue by td48260** [abpframework/abp#6371]
**ABP Framework version** 3.3.1
**User Interface** type MVC

I have verified that the Abp.Mailing.Smtp settings in the appsettings.json file are correct. The password is encrypted. However, sending emails in code or through the ForgotPassword page does not work. "Authorization failed" appears in the log file.

* Steps needed to **reproduce** the problem.
Create a new project.
Create the Database.
Enter Abp.Mailing.Smtp settings in the appsettings.json file
Run the Application.
Create a new user.
Navigate to the Account/ForgotPassword page.
Enter the email address of the new user.
Click the Submit button.

Thanks

**Comment by maliming** [comment]
> "Authorization failed"

It seems this not related to mail but authorization.

What's the details error message?

**Comment by td48260** [comment]
Sorry, my mistake. This is not a bug. I just did not understand how the framework was working.
