### ISSUE TITLE
Localize Make the PermissionAppService.GetAsync method slow

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#6373]
https://github.com/abpframework/abp/blob/810949f995c01d7df0c5173d184f93f0c6430cce/modules/permission-management/src/Volo.Abp.PermissionManagement.Application/Volo/Abp/PermissionManagement/PermissionAppService.cs#L73

1500 permission items：
remove Localize  before--10s+
remove Localize  after 300ms+

**Comment by Nokecy** [comment]
https://github.com/abpframework/abp/blob/810949f995c01d7df0c5173d184f93f0c6430cce/modules/identity/src/Volo.Abp.PermissionManagement.Domain.Identity/Volo/Abp/PermissionManagement/Identity/RolePermissionManagementProvider.cs#L34

https://github.com/abpframework/abp/blob/810949f995c01d7df0c5173d184f93f0c6430cce/modules/identity/src/Volo.Abp.PermissionManagement.Domain.Identity/Volo/Abp/PermissionManagement/Identity/RolePermissionManagementProvider.cs#L46

Maybe PermissionStore.IsGrantedAsync should be used

**Comment by maliming** [comment]
Thanks for the feedback, I will check.

**Comment by maliming** [comment]
hi @Nokecy I didn't find any performance issues. We used caching. Can you share a project?

**Comment by Nokecy** [comment]
I did some more tests, when too many localized resources do not exist, the speed is too slow。

**Comment by Nokecy** [comment]
In addition, replacing Permission Grant Repository with PermissionStore can improve 2-3s @maliming

**Comment by maliming** [comment]
> too many localized resources do not exist, the speed is too slow。

I'll test, but why is there a `not exist` situation? What is your use case?

> replacing Permission Grant Repository with PermissionStore can improve 2-3s 

The **PermissionStore** is using cache but **PermissionGrantRepository** is not.

**Comment by Nokecy** [comment]
I will change my project and add missing items

> https://github.com/abpframework/abp/blob/810949f995c01d7df0c5173d184f93f0c6430cce/modules/identity/src/Volo.Abp.PermissionManagement.Domain.Identity/Volo/Abp/PermissionManagement/Identity/RolePermissionManagementProvider.cs#L34
> 
> https://github.com/abpframework/abp/blob/810949f995c01d7df0c5173d184f93f0c6430cce/modules/identity/src/Volo.Abp.PermissionManagement.Domain.Identity/Volo/Abp/PermissionManagement/Identity/RolePermissionManagementProvider.cs#L46
> 
> Maybe PermissionStore.IsGrantedAsync should be used

Does it need to be changed here? I can PR

**Comment by maliming** [comment]
Welcome to contribute. It's will be a breaking change.

https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionManagementProvider.cs#L11

**Comment by maliming** [comment]
I did the PR.https://github.com/abpframework/abp/pull/6480

**Comment by hikalkan** [comment]
Actually, PermissionManagementProvider is only used when you manage permission (change permission of a user/role on UI) and it may be a bit slow. It bypasses cache to be able to work with the actual data source. However, using cache for reads seems no problem. I will accept the PR.
