### ISSUE TITLE
Docs module - General enhancements

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#6375]
Hi,

I've examined the docs module and must say, that I really like it.
Here are some ideas I would like to discuss / contribute:

1. Make the `share on` options configurable (either fully enable / disable or customize individual items)
2. Read the `DocsElasticSearchOptions` from configuration by default. This makes different CI / CD deployments easier
3. Add a option to `DocsUiOptions` to enable / disable the `Edit` feature
4. ~~Add a option to include custom css globally~~ (can be implemented easily by creating a own `BundleContributor`)

I can contribute code to implement this changes.

**Comment by enisn** [comment]
We can consider about it. Thanks for you feedback.

Also PR is always welcome :)

**Comment by NecatiMeral** [comment]
Currently I don't have much spare time, but I'll definetly work on this.
