### ISSUE TITLE
how to contribute locale text( zh-Hant) for commercial module

### ISSUE THREAD

**Issue by ChangYinShung** [abpframework/abp#6376]
* Your **ABP Framework version** : 3.3.1
* Your **User Interface** : angular
 this is file-management module , i want to translate those text  into  traditional chinese.
![image](https://user-images.githubusercontent.com/2546026/100427917-25c51000-30ce-11eb-956f-03dd92d68a42.png)

how to contribute locale text( zh-Hant) for pro module (such as chat,saas,audit log,text templates...)  ?

**Comment by maliming** [comment]
hi @ChangYinShung  
Thanks, I will send the  `abp-translation.json` file to your Gmail.

https://docs.abp.io/en/abp/latest/CLI#translate

![image](https://user-images.githubusercontent.com/6908465/100430804-3aa3a280-30d2-11eb-8071-5c07b94a2578.png)
