### ISSUE TITLE
How to have login page as default landing page

### ISSUE THREAD

**Issue by kbowma** [abpframework/abp#6382]
What is the best approach in Abp to have the login page as the default landing page when the application starts? Currently, I am brute forcing it with `@attribute [Microsoft.AspNetCore.Authorization.Authorize]` in the _Imports.razor page but this still loads the main form and then redirects which causes the user to see the main form for a second.

License: Abp Commercial - Teams Edition
Language: Blazor Startup Template
Version: 4.0 preview

**Comment by tarikogut** [comment]
add index.cstml authorize attribute

**Comment by roupijiaojiaobao** [comment]
@if (!CurrentUser.IsAuthenticated)
{
    Response.Redirect("/Account/Login");
}

**Comment by kbowma** [comment]
Thank you both for your response, but I am struggling where to put (which file) either approach to keep the main form from displaying on load. Putting it in the Index.razor is too late in the loading sequence.

**Comment by xyfy** [comment]
@kbowma what about in the Conroller Action?

**Comment by numanrauf** [comment]
Same happening in angular application, page is visible for a while and then redirects user to login page if he is unauthorize. Any suggestions please?
