### ISSUE TITLE
How to customize datatable ajax callback

### ISSUE THREAD

**Issue by trgiangvp3** [abpframework/abp#6383]
I saw the code in this file [datatable-extension.js](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js)
At the end of `datatables.createAjax` function, from [Line 360](https://github.com/abpframework/abp/blob/8f99538d06ff9ea0a5c55f5e88740b5030315c46/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L360) to Line 368 is where the ajax request is sent.

```js
if (callback) {
  serverMethod(input).then(function (result) {
    callback({
      recordsTotal: result.totalCount,
      recordsFiltered: result.totalCount,
      data: result.items
      });
    });
}
```

**I have 2 questions as below**
1. If I want to customize the `callback` function which is called at [Line 362](https://github.com/abpframework/abp/blob/8f99538d06ff9ea0a5c55f5e88740b5030315c46/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L362), what should I do?
2. How can I pass the whole `result` from the response to the `callback` function at [Line 362](https://github.com/abpframework/abp/blob/8f99538d06ff9ea0a5c55f5e88740b5030315c46/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/datatables/datatables-extensions.js#L362)

**I could write my own code to achieve above but I wonder if there is any configuration related (if there is then what I have to do will much more simple)**

**ABP Framework version**
> 3.3.1 (Stable)

**User Interface:**
> MVC

**Comment by maliming** [comment]
The `callback `function is belongs datatables.

https://datatables.net/reference/option/ajax

**Comment by trgiangvp3** [comment]
> The `callback `function is belongs datatables.
> 
> https://datatables.net/reference/option/ajax

It would be nice if ABP could provide a customizable calback like below
```javascript
    createAjax: function (serverMethod, inputAction, responseCallback) {
      return function (requestData, callback, settings) {

        // same old code

        if (callback) {
          serverMethod(input).then(result => {
            callback({
              recordsTotal: result.totalCount,
              recordsFiltered: result.totalCount,
              data: result.items
            });
            if (responseCallback)
              responseCallback(result);
          });
        }
      };

```

**Comment by maliming** [comment]
ok, I will give it a try.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/6482/files

**Comment by trgiangvp3** [comment]
> See https://github.com/abpframework/abp/pull/6482/files

Thank you. That's exactly what I want
