### ISSUE TITLE
Incorrect proxy generated for file upload API

### ISSUE THREAD

**Issue by kunalpgithub** [abpframework/abp#6384]
I created service in application which expect file input.

`      public async Task<IEnumerable<ScheduleDto>> CreateAsync(IFormFile File)`

I am able to see API generated correctly from swagger and tested it its working fine.

![image](https://user-images.githubusercontent.com/17749200/100541821-69558080-326c-11eb-9720-9b75eb52306e.png)

However when I generated client side proxy using abp generate-proxy. it generated this and doesn't upload file correctly. its not usingIFormFile object, not sending as formdata object or not as post parameter. 

```
import type { ScheduleDto } from './models';
import { RestService } from '@abp/ng.core';
import { Injectable } from '@angular/core';
import type { IFormFile } from '../microsoft/asp-net-core/http/models';

@Injectable({
  providedIn: 'root',
})
export class ScheduleService {
  apiName = 'Default';

  create = (File: IFormFile) =>
    this.restService.request<any, ScheduleDto[]>({
      method: 'POST',
      url: `/api/app/schedule`,
    },
    { apiName: this.apiName });

  constructor(private restService: RestService) {}
}

```

Do I need to manually upload file using Http serivce instead of built in rest service?

**Comment by bnymncoskuner** [comment]
Hello,

You can use the built-in `RestService` however you need to call it as follows. The one generated by `generate-proxy` is not aware of file uploading yet. We plan to introduce a feature that would automatically detect file uploading and create services accordingly. 

I suggest you create a new service. Do not edit the generated one because it will be updated when you run `abp generate-proxy` again. You can call your service as follows:

```typescript

create = (file: File) => this.restService
      .request<any, any>(
        {
          method: 'POST',
          url: `/api/app/schedule`,
          params: { id: someId }, // additional path params
          body: this.generateFormData(file),
        },
        { apiName: this.apiName }
      );

  private generateFormData(file: File) {
    const formData = new FormData();
    formData.append('file', file.data, filet.meta.name);
    return formData;
  }
```

**Comment by snowchenlei** [comment]
There was an error with my 'IFromFile.ts'.
```
ERROR in src/app/proxy/microsoft/asp-net-core/http/models.ts:5:27 - error TS2304: Cannot find name 'StringValues'.
headers: Record<string, StringValues>;
```
![image](https://user-images.githubusercontent.com/26211283/102297711-b5056b00-3f8a-11eb-9de9-0f4d078d3528.png)

**Comment by HyperionLi** [comment]
> There was an error with my 'IFromFile.ts'.
> 
> ```
> ERROR in src/app/proxy/microsoft/asp-net-core/http/models.ts:5:27 - error TS2304: Cannot find name 'StringValues'.
> headers: Record<string, StringValues>;
> ```
> 
> ![image](https://user-images.githubusercontent.com/26211283/102297711-b5056b00-3f8a-11eb-9de9-0f4d078d3528.png)

Have you found something on this?

**Comment by Henkpuik** [comment]
Is there a solution for with generate-proxy or do we need de work arround?

**Comment by TIMPICKLE** [comment]
I also meet this issue，so there is an alternative solutions. when you upload a file, don't use "IFromFile" type. try to create another Dto, and one of its properties is " public string fileContent{ get;set; }". like this
```
public class ReportsUploadDto
    {
        public string Name
        {
            get;
            set;    
        }

        public string FileType
        {
            get;
            set;
        }

        public string LinkedCourseId
        {
            get;
            set;
        }

        public string FileContent
        {
            get;
            set;
        }
    }
```
so in frontend(i use angular).  generate a proxy base on ABP, than follow the "ReportsUploadDto" type. After that, the string obtained from Base64  should be converted into byte and stored in minio.

**Comment by abdulqadermohamed** [comment]
i add service inbackEnd but when generate  proxy still issue in IRemoteStreamContent not can find it ?
  savingExcelFileBySaveingFileExeclDtoAndFileData = (saveingFileExeclDto: SaveingFileExeclDto, FileData: IRemoteStreamContent) =>
    this.restService.request<any, BulkResponseDto>({
      method: 'POST',
      url: '/api/app/customer/saving-excel-file',
      params: { pocktId: saveingFileExeclDto.pocktId, propertSelected: saveingFileExeclDto.propertSelected, propertSelectedValue: saveingFileExeclDto.propertSelectedValue, companyId: saveingFileExeclDto.companyId, checkAssignUsersOrGeneralCode: saveingFileExeclDto.checkAssignUsersOrGeneralCode, assignUsersOrGeneralCode: saveingFileExeclDto.assignUsersOrGeneralCode, assignUsersOrNormalCustomer: saveingFileExeclDto.assignUsersOrNormalCustomer, checkAssignUsersRandomly: saveingFileExeclDto.checkAssignUsersRandomly, assigningUsers: saveingFileExeclDto.assigningUsers },
      body: FileData,
    },
    { apiName: this.apiName });
