### ISSUE TITLE
How to use multiple event bus of rabbitmq in one project?

### ISSUE THREAD

**Issue by fmpfmp** [abpframework/abp#6388]
How to use multiple event bus of rabbitmq in one project?

**Comment by OldKing-lion** [comment]
I also want to know this .. I just use multi queues but I do not know how to use multi exchanges

**Comment by qqzhw** [comment]
+1

**Comment by wanghaiyang5241** [comment]
+1

**Comment by fmpfmp** [comment]
+1

**Comment by rafaelgfirmino** [comment]
+1

**Comment by maliming** [comment]
You can replace the built-in services to achieve your special needs.

**Comment by johnwanzhi** [comment]
+1

**Comment by happtim** [comment]
+1
