### ISSUE TITLE
Cli get-source command must support angular-only modules

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#6416]
There are few situations that we need this.

**Comment by ebicoglu** [comment]
also can you write the usage of this command to this support ticket https://support.abp.io/QA/Questions/632/How-can-I-download-the-framework-and-source-code-for-pro-modules

**Comment by yinchang0626** [comment]
@yekalkan @ebicoglu  @maliming :
Hi , thank your explanation how to get souce code for business license,
but I can't find source code of `@volo/abp.commercial.ng.ui`  package after I downloaded all modules of [list](https://support.abp.io/QA/Questions/632/How-can-I-download-the-framework-and-source-code-for-pro-modules).
So,my question is how to get `@volo/abp.commercial.ng.ui`  source code or can I get it   ? Thanks

**Comment by maliming** [comment]
@mehmet-erim Any advice?

**Comment by mehmet-erim** [comment]
The `@volo/abp.commercial.ng.ui` package in the `volo/abp/npm/ng-packs/packages/commercial-ui` folder can be downloaded in the same way as other Angular packages. For Suite and CLI, we need to make it available for download. Please let me know if you encounter any problems on the Angular side

**Comment by yinchang0626** [comment]
@mehmet-erim 
As I know,
If I want to get source code,I must do it by Suite or CLI.
Is possible get the source code in  `volo/abp/npm/ng-packs/packages/commercial-ui` folder?
Are you mean I can access source code by git or other way(business license)?
If `CLI` is not only way to get source code,please tell me how to.

Abp Angular project is also a great framework.
so,I just need to know more about all of `/ng-packs/packages`.  Thanks.

**Comment by yekalkan** [comment]
@yinchang0626 Have you seen my answer at https://support.abp.io/QA/Questions/44/How-to-access-non-open-source-UI-codes#answer-34fc32c6-8394-8af0-d2d0-39f92f619fdb?

**Comment by yinchang0626** [comment]
@yekalkan 
Yes I saw,and then send email to `info@abp.io`,
but i didn't recieve `@volo/abp.commercial.ng.ui` source code but get a [link](https://support.abp.io/QA/Questions/624/How-can-I-download-a-NPM-package-source-code#answer-81233244-ce5b-59d7-0a5a-39f935f5700b) and [this](https://support.abp.io/QA/Questions/632/How-can-I-download-the-framework-and-source-code-for-pro-modules#answer-70bbbda7-c0a0-6b02-f782-39f93f11167d) for how to download by `Suite`.
Now ,as @mehmet-erim  say .
(For Suite and CLI, we need to make it available for download.)
so, my question is be solved if `Suite` can download `@volo/abp.commercial.ng.ui` source code in the future

**Comment by yekalkan** [comment]
@yinchang0626 see https://support.abp.io/QA/Questions/673/How-can-I-download-voloabpcommercialngui-Angular-package

**Comment by yinchang0626** [comment]
@yekalkan : I get it ! Thank You .
