### ISSUE TITLE
Quick Support :: Could not load type 'Volo.Abp.Domain.Entities.EntityNotFoundException' from assembly 'Volo.Abp.Ddd.Domain, Version=3.3.1.0

### ISSUE THREAD

**Issue by muhammedshaaban7** [abpframework/abp#6426]
Kindly quick support, when I post any API in swagger, this error is shown as below 

![image](https://user-images.githubusercontent.com/64292395/100751302-32ac7100-33f8-11eb-97bc-f8ecf6fcd4af.png)

abp version => 5.14.0
thank you

**Comment by realLiangshiwei** [comment]
> abp version => 5.14.0

The latest stable version of ABP vNext is 3.3.1, are you talking about aspnetboilerplate?
