### ISSUE TITLE
Embedded file return 404

### ISSUE THREAD

**Issue by fengyeju** [abpframework/abp#6427]
abp 3.3.1
I visit a embedded file(such as 'test1-abp.min.js'), it can not be found.
I create a file to Volo.Abp.AspNetCore.Tests/wwwroot/SampleFiles/test1-abp.min.js, then use this code, it not pass.
```
        [Fact]
        public async Task Get_Virtual_File()
        {
            var result = await GetResponseAsStringAsync(
                "/SampleFiles/test1-abp.min.js"
            );

            result.ShouldBe("test1.js-content");
        }
```
![20201201225813](https://user-images.githubusercontent.com/3335682/100756933-bb430580-3428-11eb-8c63-f81dfe1e70d4.jpg)

**Comment by maliming** [comment]
Change your project file.

```cs
<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>

<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="your package version" />
```
