### ISSUE TITLE
Volo.Abp.HangFire.csproj update Hangfire nuget package reference to latest version

### ISSUE THREAD

**Issue by d-oit** [abpframework/abp#6428]
Any reason why not using the latest 1.7.* nuget version? 

` <PackageReference Include="Hangfire.AspNetCore" Version="1.7.*" />`

current reference:

```
<ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.11" />
  </ItemGroup>
```

**Comment by maliming** [comment]
Related https://github.com/abpframework/abp/issues/6364
