### ISSUE TITLE
How to integrate the syncfusion Blazor components with the ABP Blazor UI?

### ISSUE THREAD

**Issue by ghd258** [abpframework/abp#6435]
How to integrate the syncfusion Blazor components with the ABP Blazor UI?

**Comment by stsrki** [comment]
Hi @ghd258 

The easiest way to integrate any Blazor component library into the ABP framework is almost the same for all libraries. Just follow some of our guides and modify accordingly to Syncfusion. Look at these for reference:

- https://community.abp.io/articles/using-matblazor-components-with-the-abp-framework-blazor-ui-xsvs7gq1
- https://community.abp.io/articles/using-devexpress-blazor-ui-components-with-the-abp-framework-wrpoa8rw

**Comment by hikalkan** [comment]
We can take this as an article request for anyone wants to write.

**Comment by stsrki** [comment]
@hikalkan I can do it.

**Comment by hikalkan** [comment]
Perfect. We can schedule for the next milestone, 4.4.
