### ISSUE TITLE
Ng serve stop working after abp generate-proxy

### ISSUE THREAD

**Issue by synps** [abpframework/abp#6442]
Hi,

I was testing ABP Framework 4.0.0-RC5 with Angular UI. I created very simple domain objects and DTO's. When I use abp generate-proxy in the root folder, ng serve throws following error. 

```
Error: ./src/app/proxy/books/index.ts 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ./node_modules/@ngtools/webpack/src/index.js
You may need an additional loader to handle the result of these loaders.
> export * as Dtos from './dtos';
| export * from './models';
| export * from './book-status.enum';
```

src/app/proxy/books/index.ts
```
export * as Dtos from './dtos';
export * from './models';
export * from './book-status.enum';
export * from './book.service';
```

Possibly related with https://github.com/angular/angular-cli/issues/17231
and with https://github.com/TypeStrong/ts-loader/issues/1121

**Comment by maliming** [comment]
hi

Please share you backend code.

**Comment by maliming** [comment]
hi

Please share your backend code.

**Comment by synps** [comment]
As far as I can see removing `as Dtos` part from the first line of src/app/proxy/books/index.ts solves the problem. Why do you require backend code, is not it a bug between Angular and Webpack? You can reproduce `as Dtos` part by using following directory structure;

```
-Acme.BookStore.Domain.Shared
--Books
---DTOs
----BookDto.cs
----CreateUpdateBookDto.cs
```

**Comment by mehmet-erim** [comment]
Hello @synps 

Can you run the following command and generate the proxies again:

```bash
yarn add @abp/ng.schematics@4.0.0-rc.5 --dev --tilde
```

**Comment by synps** [comment]
> Hello @synps
> 
> Can you run the following command and generate the proxies again:
> 
> ```shell
> yarn add @abp/ng.schematics@4.0.0-rc.5 --dev --tilde
> ```

Thank you for the new ng.schematics package. That solved the problem. 

By the way now I receive a warning during proxy generation as follows. Does not affect functionality and does not bother me neither but wanted to let you know.

```
abp generate-proxy
[20:47:21 INF] ABP CLI (https://abp.io)
[20:47:22 INF] Version 4.0.0-rc.5 (Prerelease)
[20:47:23 WRN] Couldn't determinate version of "@abp/ng.schematics" package.
```

**Comment by mehmet-erim** [comment]
Thanks for the information. 
I am closing the issue. If you have faced any issue about that, feel free to open the issue.
