### ISSUE TITLE
Antiforgery, cookies, http and react native problems.

### ISSUE THREAD

**Issue by pvaz** [abpframework/abp#6447]
ABP Framework version: v4.0.5-RC
UI type: MVC
Tiered (MVC) or Identity Server Seperated (Angular): yes
Exception message and stack trace: 

The cookie 'XSRF-TOKEN' has set 'SameSite=None' and must also set 'Secure'

Steps to reproduce the issue:

Using the app-pro template, setting https and localhost urls to http and fixed ip, to be able to use react native project, identityserver is unable to login and creating the cookies that are necessary to work with anything.

the AntiForgery seems to work well under https but when using http, it's not working at all.

Since it's demanded on react-native project to use http for development and on local server, how can this be solved ?

Thanks

**Comment by realLiangshiwei** [comment]
See https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n

**Comment by pvaz** [comment]
This problem is not related with chrome and this solution does not work.

the problem happens when using app-pro template.

**Comment by realLiangshiwei** [comment]
I see your question on the support website, I will reply to you on it

**Comment by leonkosak** [comment]
@realLiangshiwei in which projects exactly should Step-1 be applied when we have tiered Blazor application? There is no .Web project. Just .HttpApi.Host and .IdentityServer.
Thank you.

**Comment by realLiangshiwei** [comment]
@leonkosak  Please open a new issue.
