### ISSUE TITLE
Timeout Expired while saving records

### ISSUE THREAD

**Issue by anaya-upadhyay** [abpframework/abp#6454]
I am getting a Timeout Expired while saving records.

I have a transaction which adds records into multiple (5 to be exact) tables with more than 2000 records. When I debug the application in Visual Studio it takes almost 121.8 seconds to complete the entire transaction. But after deployment, it says Timeout.

My project is using these versions of ABP and ASPNet Core:
ABP Framework - 2.3.0
ASPNet Core - 3.1

This is the entire procedure:
1. Getting the required data as the input parameter.
2. Fetching AbpUserIds for required users. (Count = 500)
3. Inserting data into the parent table. (Count = 1)
4. Inserting data into the immediate child table. (Count = 3 - 5)
4. Using InsertAsync with true as the AutoSave parameter looping through the users.
    a. Inserting data into the user-specific tables (2 tables with 1 record on the parent table and 3 - 5 records on the child table).
    b. Return the id of parent table from the user-specific table (4a).
    c. Finally, inserting data into the last table (Count = 500) with foreign key from main table (3) and the key from the parent of user-specific table (4a) along with the abpuserid for the user.

How can I get rid of this Timeout?

**Comment by realLiangshiwei** [comment]
I think it nothing todo with ABP. You should optimize your code, Just suggest:

 1. Do not set `AutoSave` to  true
 2. Try bulk insert
 3. Upgrade ABP to the latest version (We did a lot of optimization)

**Comment by anaya-upadhyay** [comment]
@realLiangshiwei Thank you for the suggestion.

But how do I perform Bulk Insert?
I don't see AddRange() method in the repository.

**Comment by realLiangshiwei** [comment]
You can custom repository or use EF Core API in appservices.

See https://docs.abp.io/en/abp/latest/Entity-Framework-Core#access-to-the-ef-core-api

**Comment by anaya-upadhyay** [comment]
@realLiangshiwei I get this error when I set `AutoSave` to false:

The instance of entity type 'tablename' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

Can I do anything regarding this? 

Maybe I can use a `DbContext` in this Service. For using `DbContext`, I need to reference `EntityFrameworkCore` to the `Application Layer.` Is that a good choice?

**Comment by realLiangshiwei** [comment]
As a best practice, you should customize the repository, but ABP does not limit you
