### ISSUE TITLE
abp 4.0 web project hang up when starting

### ISSUE THREAD

**Issue by niufwshd** [abpframework/abp#6470]
- abp version 4.0  .net version 5.0
 - issue
   
![image](https://user-images.githubusercontent.com/12984401/101051664-b749eb80-35c0-11eb-8d8a-785a21cceda6.png) 
the web project hang up here.
my web project haven't new business logic,same as template.
domain.csproj and contract.proj project has 789 of  POCO class files,and entityframeworkcore.csproj has 789 of respository class files too!
when I exclue 788 of files out of the project(just left one repository file),the web project can run  succesfully!,but when I include them, the web project was  like the above picture.I didn't read the source code,and have no idea about it,
![image](https://user-images.githubusercontent.com/12984401/101052322-6f779400-35c1-11eb-9001-e6e8ff4860a0.png) just loading...

can anyone give me any suggestions and forgive my poor english.
thanks first!

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by niufwshd** [comment]
@maliming，thank you for your fast reply. I have created the [FarVisonMes repository](https://github.com/niufwshd/FarVision-Mes) , you can check it out. In my computer,I have added migration and updated database, perhaps you may change the connectionstring. I think  the project has too many files to resolve during starting and it need much time. I have tried it again,and it started successfully after ten minutes! 
![image](https://user-images.githubusercontent.com/12984401/101126729-0af71c00-3637-11eb-8ec0-520ce24d1e87.png)

**Comment by maliming** [comment]
I can't understand your repository in a short time.
Can you use the abp template project and provide detailed steps?

**Comment by niufwshd** [comment]
@maliming , My steps as follows:

1. Explor the api.io [site](https://abp.io/get-started),and enter "FarVision-Mes" as the 
 solution name,press the "create" button,then  the zip file will be downloaded.
2. Open FarVision.Mes.sln in vs2019,switch to the FarVision.Mes.DbMigrator project ,open appsettings.json ,change the default connectstring's to "Server=.;Database=Mes;Trusted_Connection=True;MultipleActiveResultSets=true" and save.
3. Swicth to FarVision.Mes.Web project,,open appsettings.json ,change the default connectstring's to "Server=.;Database=Mes;Trusted_Connection=True;MultipleActiveResultSets=true" and save.
4. Set FarVision.Mes.DbMigrator as startup project and run it to create default tables
5. Swicth to FarVision.Mes.Domain and copy domain files from other solution to this project.those are POCOs.
6. Switch to FarVision.Mes.EntityFrameworkCore project,copy custom efrepository and IRepository files from other solution to this project. then Open MesDbContext.cs file,add DBSet<T> properties, open MesDbContextModelCreatingExtensions.cs file, add ModelBuilder fluent api code, and save all. 
![image](https://user-images.githubusercontent.com/12984401/101238781-71566a00-371d-11eb-9335-29ef8869be4d.png)


7. set  FarVision.Mes.Web as startup project,and open powershell pannel,select the FarVision.Mes.EntityFrameworkCore.DbMigrations from combox, and type "add-migration createdb",then wait for it to complete,then type "update-database" to generate the business schema.
8. compile the whole solution.If it haven't any errors ,then run it and open a browser to explore https://localhost:44361, and it became very slow.

I have created annother [repository](https://github.com/niufwshd/Mes-Test) and have test it. the repository has almost same order steps as above.
thanks.

**Comment by maliming** [comment]
Add those code to your `MesEntityFrameworkCoreModule's ConfigureServices` method.  Always use your **repository interface** instead of implementation.

```cs
context.Services.RemoveAll(descriptor =>
{
	if (descriptor.ImplementationType != null && descriptor.ImplementationType.FullName != null)
	{
		if (descriptor.ImplementationType.FullName.StartsWith("FarVision.Mes") &&
			descriptor.ImplementationType.FullName.EndsWith("Repository"))
		{
			return true;
		}
	}

	return false;
});
```

**Comment by niufwshd** [comment]
@maliming ,Thank you very much!. It works nicely.I realize that My own Repository  files are  redundant!. Your Framework is very convenient to Inject my own IEfcoreRepository ImplementationType   by using  context.Services.AddTransient<Ixxx, xxxRepository>() too！Thank you again!
