### ISSUE TITLE
Generate Proxy doesn't allow underscores in name

### ISSUE THREAD

**Issue by dhehir** [abpframework/abp#6471]
ABP Version: 3.3.0
UI: Angular

Issue:
When defining a DTO with a property name with an underscore, the abp generate-proxy step will strip the underscore.
The api will serialize the underscore but the typescript generated code will not have the underscore - causing underfined errors:
C#:
![image](https://user-images.githubusercontent.com/48895661/101098668-687b7080-3617-11eb-94b7-3a3df01ba8e3.png)

typescript vs debug:
![image](https://user-images.githubusercontent.com/48895661/101098766-9791e200-3617-11eb-967d-11e2c67afaa1.png)

**Comment by armanozak** [comment]
Hi @dhehir,

I have just tried this with v3.3.0 and the property name was generated as `changeFromReference_percent: number;`.

What is your ABP CLI version? Thanks.

**Comment by dhehir** [comment]
Running with 3.3.0. I'll see if I can make a simple test case for you.
![image](https://user-images.githubusercontent.com/48895661/101333642-f59a2000-38ca-11eb-976b-642874653083.png)

**Comment by hikalkan** [comment]
@armanozak couldn't repeat it. @maliming can you try please?

**Comment by maliming** [comment]
I also can't reproduce this.
