### ISSUE TITLE
I am using the new 4.0.0 just tired to install the Blogging Module and there seems to be error with tui-editor

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#6473]
I am using the new 4.0.0 and having the same issues with the same error message ..... there seems to be some conflict with the outdated jQuery.

![image](https://user-images.githubusercontent.com/15242923/101106672-af239780-3624-11eb-8626-32565bca74c3.png)

_Originally posted by @vnetonline in https://github.com/abpframework/abp/issues/4829#issuecomment-738471268_

**Comment by realLiangshiwei** [comment]
Clear node_modules and run `npm install & gulp` to restore packages.

**Comment by vnetonline** [comment]
okay that worked ... but can't upload the Cover image .... do I need to create a folder for files? ..... if so where ?

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Blob-Storing

**Comment by snowchenlei** [comment]
> Clear node_modules and run `npm install & gulp` to restore packages.

sorry.I can't solve the error in abp v4.2.1

**Comment by sanpiseth** [comment]
Hello all,

Please help me. I get the error:

AbpException: Could not find the bundle file '/libs/tui-editor/tui-editor.min.css' for the bundle

Please kindly help me
