### ISSUE TITLE
Add Huawei cloud support to Blob Storing

### ISSUE THREAD

**Issue by charleszh-dev** [abpframework/abp#6474]
Are there plans for the Blob Storing to support Huawei Cloud?

Huawei Cloud OBS
https://www.huaweicloud.com/en-us/product/obs.html

If no one else does this feature, can I do it? I already have some code that I am using myself.

**Comment by maliming** [comment]
We always welcome developers to contribute code.

**Comment by charleszh-dev** [comment]
I will continue to complete the development of this feature on [#6501](https://github.com/abpframework/abp/pull/6501).
