### ISSUE TITLE
BundleContributor - Enhancement Request for remote sources

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#6475]
Using v 4.0.0

The [BundleContributor](https://docs.abp.io/en/abp/latest/UI/Blazor/Global-Scripts-Styles) could be enhanced to allow the  developer to add references to remote source addresses (non-cached) scripts and stylesheets.

For example - in this case a ref to Google Maps API (which is not downloadable)

![image](https://user-images.githubusercontent.com/40014477/101108482-8e047c00-360f-11eb-8a13-083e0108a5d6.png)

When the CLI command `abp bundle` is run, the reference is currently ignored and not added.

**Comment by 274188A** [comment]
I think there should also be an option to have scripts.styles placed in the `<head>` or `<body>`

**Comment by maliming** [comment]
@ilkayilknur What do you think?

**Comment by realLiangshiwei** [comment]
You can use the  `excludeFromBundle`  parameter:

```csharp
public void AddScripts(BundleContext context)
{
     context.Add("googleApi....", excludeFromBundle:true);
}
```

**Comment by realLiangshiwei** [comment]
> You can use the `excludeFromBundle` parameter:
> 
> ```cs
> public void AddScripts(BundleContext context)
> {
>      context.Add("googleApi....", excludeFromBundle:true);
> }
> ```
