### ISSUE TITLE
/connect/token return "invalid_scope"

### ISSUE THREAD

**Issue by OldKing-lion** [abpframework/abp#6476]
I updated to 4.0 success,but gettoken error:/connect/token return "invalid_scope"
![image](https://user-images.githubusercontent.com/13028615/101125481-51974700-3634-11eb-9632-b9b56e147d21.png)

**Comment by charleszh-dev** [comment]
try exclude scope from the request body.

**Comment by OldKing-lion** [comment]
> try exclude scope from the request body.
No affect
![image](https://user-images.githubusercontent.com/13028615/101126443-7987aa00-3636-11eb-95ff-957728a47c46.png)

**Comment by sweetyguazi** [comment]
I encountered the same problem as you. Have you solved it? Can you share how to solve it

**Comment by OldKing-lion** [comment]
> I encountered the same problem as you. Have you solved it? Can you share how to solve it

是的，我解决了，他们升级文档写的有问题，你可以去创建一个模板项目，Identity的种子数据里多了一个方法，我和他们说了其他人也会遇到这种情况，但是他们没有说明这个情况
