### ISSUE TITLE
the property 'isAuthenticated' of the currentUser is false

### ISSUE THREAD

**Issue by OldKing-lion** [abpframework/abp#6477]
I got the token and use it to request 'api/abp/application-configuration' in headers ,but the property 'isAuthenticated' of the currentUser is false

![image](https://user-images.githubusercontent.com/13028615/101129509-a8a11a00-363c-11eb-8f98-6fb3183ef5cc.png)

**Comment by OldKing-lion** [comment]
![image](https://user-images.githubusercontent.com/13028615/101134113-dbe7a700-3644-11eb-90a1-48f26a3d8fe3.png)
Scope does not contains my scope..

**Comment by OldKing-lion** [comment]
the data in table 'identityserveridentityresources',I migrated it before:
![image](https://user-images.githubusercontent.com/13028615/101134607-9d9eb780-3645-11eb-963d-cae34d87fdf0.png)

the data in table 'identityserveridentityresources':
![image](https://user-images.githubusercontent.com/13028615/101134682-ba3aef80-3645-11eb-9bfc-1efbbba09e37.png)

**Comment by OldKing-lion** [comment]
I guess the reason is there is no data in table Ids4 apiscope

**Comment by OldKing-lion** [comment]
I created a new project use abp cli 4.0 and find the initial  apiscope method,it's not in my project that migrate from 3.3.2
I think it should be add in migration docs

**Comment by amin168** [comment]
@OldKing-lion Change `IdentityServerApiScopes` table's `Enabled` field from `fasle` to `true`

**Comment by maliming** [comment]
The migration documentation has explained the changes in the Identity Server.

You should check the code of the 4.0 template project instead of sharing many screenshots, it will not help.

https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#upgraded-to-identity-server-4-1-1

**Comment by OldKing-lion** [comment]
> The migration documentation has explained the changes in the Identity Server.
> 
> You should check the code of the 4.0 template project instead of sharing many screenshots, it will not help.
> 
> https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#upgraded-to-identity-server-4-1-1
I know what you mean. I also checked the code of the template project and found that it was different. However, your upgrade document didn't explain it. I just pointed out that I think other people should encounter the same upgrade problem as me, right？
I appreciate your work
