### ISSUE TITLE
Can not find the package (>=0.9.3-preivew2) Blazorize

### ISSUE THREAD

**Issue by OldKing-lion** [abpframework/abp#6479]
![image](https://user-images.githubusercontent.com/13028615/101132071-4e568800-3641-11eb-9846-4718d3725510.png)

**Comment by rqx110** [comment]
add this:
https://github.com/abpframework/abp/blob/ed1edd381289f6d1d9e11037f1ee016054f30f76/templates/app/aspnet-core/NuGet.Config#L4

**Comment by OldKing-lion** [comment]
use the package Volo.Abp.BlazoriseUI,it is ok
