### ISSUE TITLE
Idea: RFC 7807 - Problem Details for HTTP APIs

### ISSUE THREAD

**Issue by gentledepp** [abpframework/abp#6485]
Abp out of the box returns a very rich set of validation errors in the API responses.

I was wondering, however, if it would be possible to plug-in a different response formatter for error messages.
E.g. by default, Abp uses an (e.g.) AbpValidationResponseFormatter which returns an error message, details, etc.

We could, then, implement our own Rfc7807ValidationResponseFormatter to comply with the standard: https://tools.ietf.org/html/rfc7807

That would have the benefit of having the validation responses automatically be supported by some rest client frameworks like REFIT.
https://github.com/reactiveui/refit#handling-exceptions

To give you an idea, here are two samples from the RFC

> ```
> HTTP/1.1 403 Forbidden
>    Content-Type: application/problem+json
>    Content-Language: en
> 
>    {
>     "type": "https://example.com/probs/out-of-credit",
>     "title": "You do not have enough credit.",
>     "detail": "Your current balance is 30, but that costs 50.",
>     "instance": "/account/12345/msgs/abc",
>     "balance": 30,
>     "accounts": ["/account/12345",
>                  "/account/67890"]
>    }
> 
> ```
>  Here, the out-of-credit problem (identified by its type URI)
>    indicates the reason for the 403 in "title", gives a reference for
>    the specific problem occurrence with "instance", gives occurrence-
>    specific details in "detail", and adds two extensions; "balance"
>    conveys the account's balance, and "accounts" gives links where the
>    account can be topped up.
> 
>    The ability to convey problem-specific extensions allows more than
>    one problem to be conveyed.  For example:
> 
> ```
>    HTTP/1.1 400 Bad Request
>    Content-Type: application/problem+json
>    Content-Language: en
> 
>    {
>    "type": "https://example.net/validation-error",
>    "title": "Your request parameters didn't validate.",
>    "invalid-params": [ {
>                          "name": "age",
>                          "reason": "must be a positive integer"
>                        },
>                        {
>                          "name": "color",
>                          "reason": "must be 'green', 'red' or 'blue'"}
>                      ]
>    }
> ```
>    Note that this requires each of the subproblems to be similar enough
>    to use the same HTTP status code.  If they do not, the 207 (Multi-
>    Status) [RFC4918] code could be used to encapsulate multiple status
>    messages.

Would this make sense to you?
And if so, do you think it could be feasible to implement such an extensibility point - or does it already exist? 😁

**Comment by maliming** [comment]
hi 

Abp uses NET Core middleware and mvc filters to implement a custom format response. You can customize it freely.
