### ISSUE TITLE
A little trick to extend filters to PagedAndSortedResultRequestDto, and keep the auto-API clean in swagger docs.

### ISSUE THREAD

**Issue by ghost** [abpframework/abp#6487]
There is no filter in **PagedAndSortedResultRequestDto** of method GetListAsync in **CrudAppService** application service by default, you have to create a new class that inherits from PagedAndSortedResultRequestDto to extend filter.

```c#
    public class GetSchemeListDto : PagedAndSortedResultRequestDto
    {
        public string Filter { get; set; }

        public string Others { get; set; }
    }

```

And write a new method

```c#
        public async Task<PagedResultDto<SchemeDto>> GetListFilterAsync(GetSchemeListDto input)
        {
           //....
        }

```

You can't override the base.GetListAsync because the type of GetSchemeListDto, the Auto-API generates two APIs in swagger docs.

`

GET ​/api​/app​/schemes
GET ​/api​/app​/schemes/filter
`

And now you have to explain the differents of its to the guys who call this APIs. For them, this two APIs did the same things, they shold be one, sholdn't be splited just because add a filter to the request.
Therefore, merge the two into one. A simple way to do this, firstly hide the **base.GetListAsync**  and then rename the action name to the new method **GetListFilterAsync**

```c#
        [ApiExplorerSettings(IgnoreApi = true)]
        [RemoteService(IsMetadataEnabled = false)]
        [NonAction]
        public override Task<PagedResultDto<SchemeDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            return base.GetListAsync(input);
        }


        [ActionName(nameof(GetListAsync))]
        public async Task<PagedResultDto<SchemeDto>> GetListAsync(GetSchemeListDto input)
        {
       //...
         }

```

 That's it. Hope it helps.

**Comment by trgiangvp3** [comment]
What is this for?
I don't understand why we should create another input DTO?

**Comment by MAlshehri** [comment]
> 
> 
> What is this for?
> I don't understand why we should create another input DTO?

If you want to support input.Filter for example
