### ISSUE TITLE
/Identity/Users/CreateModal and EditModal not showing up

### ISSUE THREAD

**Issue by maxrizwork** [abpframework/abp#6489]
* Your **ABP Framework version**.
ver3.2 ( but I noticed it also on ver3.0) 
I'm using it with all the source code with **no changes** for debugging pourpose. No nuget packages. 
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
ASP.NET MVC
* Exception message and **stack trace** if available (check the logs).
This is strange because I do NOT have any errors both on server side and client-side (javascript/jquery)
* Steps to reproduce the problem:
Login with an admin role ( in order to see Administration menu).
Go under Administration>IdentityManagement>Users
Click on New User or Edit an existing user.
![Edituser](https://user-images.githubusercontent.com/10518283/101158464-0c6f1700-362c-11eb-83b1-6dbe52baf8ba.PNG)

First of all I have this strange behaviour only for Users/CreateModal and Users/EditModal,
no problems with similar modals for Tenants and Roles.
When I click on on "Add new user" nothing happen.
Looking Chrome > Network I understood the the browser is getting the modal view regularly with HTTP 200 but the content is this:

```
<form method="post" action="/Identity/Users/CreateModal">
<abp-modal>
<abp-modal-header title="New user"></abp-modal-header>
<abp-modal-body>
<abp-tabs name="create-user-modal-tabs">
<abp-tab title="User information">
<abp-input asp-for="UserInfo.UserName" />
<abp-input asp-for="UserInfo.Name" />
<abp-input asp-for="UserInfo.Surname" />
<abp-input asp-for="UserInfo.Password" />
<abp-input asp-for="UserInfo.Email" />
<abp-input asp-for="UserInfo.PhoneNumber" />
</abp-tab>
<abp-tab title="Roles">
<abp-input label="admin" />
<input type="hidden" data-val="true" data-val-required="The Name field is required." id="Roles_0__Name" name="Roles[0].Name" value="admin" />
</abp-tab>
</abp-tabs>
</abp-modal-body>
<abp-modal-footer buttons="Save, Cancel"></abp-modal-footer>
</abp-modal>
<input name="__RequestVerificationToken" type="hidden" value="CfDJ8GcKrjhtiCVGtUcR0HC8qFE679VachsDySoxKeaLJb92dII_nCBPVobLCs5Uy2HnDu7MoqUc84Jl57CDqCw5dkJiuMFhJFvpCimdd0qpfvXE4TUfkDbXtbSfvaVkS5mkBqRwOKJ95J1q1U5ivbuDVd8dLzvLqMg6-mvrfXPGxVCvUWzTE_wn7g1ap3qdSX8cog" /></form>

```

This is obviously the server side view code.

If I edit or add for example a Role I see instead a regular html page:

```
<form action="/Identity/Roles/CreateModal" method="post">
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" >
<div class="modal-dialog" role="document">
<div class="modal-content">

<div class="modal-header"> <h5 class="modal-title">New role</h5>
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span aria-hidden="true">×</span>
</button>
</div>
<div class="modal-body">
<div class="form-group"><label for="Role_Name">Role name</label><span> * </span><input type="text" data-val="true" data-val-length="The field Role name must be a string with a maximum length of 256." data-val-length-max="256" data-val-required="The Role name field is required." id="Role_Name" maxlength="256" name="Role.Name" value="" class="form-control " /><span class="text-danger field-validation-valid" data-valmsg-for="Role.Name" data-valmsg-replace="true"></span></div>

<div class="custom-checkbox custom-control mb-2"><input type="checkbox" data-val="true" data-val-required="The Default field is required." id="Role_IsDefault" name="Role.IsDefault" value="true" class="custom-control-input " /><label class="custom-control-label" for="Role_IsDefault">Default</label></div>

<div class="custom-checkbox custom-control mb-2"><input type="checkbox" data-val="true" data-val-required="The Public field is required." id="Role_IsPublic" name="Role.IsPublic" value="true" class="custom-control-input " /><label class="custom-control-label" for="Role_IsPublic">Public</label></div>

</div>
<div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
<button type="submit" class="btn btn-primary" data-busy-text="Saving..."><i class="fa fa-check"></i> <span>Save</span></button>
</div>
</div>
</div>
</div>
```

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by maxrizwork** [comment]
I find a way to debug (Volo.Abp.Identity.Web project) and I found out that I regularly execute (no errors) the get method:
`public virtual async Task<IActionResult> OnGetAsync(Guid id)`
but, this is the problem, if I put a breakpoint inside the razor page EditModal.cshtml it is NOT stopping. It's not passing from there.

If I do the same for example with \Roles\EditModal I have exactly the same behaviour except... it's passing and rendering the EditModal.cshtml page. If I put a breakpoint I can stop inside the razor page.

**Comment by maxrizwork** [comment]
No news?

Thanks

**Comment by maliming** [comment]
**Steps needed to reproduce the problem.**

**Comment by maxrizwork** [comment]
My fault sorry.
I forgot that I had a customization in place for these two pages:
MyWebProject.Web\Pages\Identity\Users\CreateModal.cshtml
MyWebProject.Web\Pages\Identity\Users\EditModal.cshtml

Now I just merged your changes with mine and it's working!

Sorry about that.
