### ISSUE TITLE
Is it possible replace base UI framework while creating a theme ?

### ISSUE THREAD

**Issue by ahmed007boss** [abpframework/abp#6494]
Is it possible replace base bootstrap  while creating a new theme ?
 for example I want to  use some other UI framework like  [foundation](https://get.foundation/) or [Fomantic ](https://fomantic-ui.com/)

**Comment by realLiangshiwei** [comment]
Hi,

The core framework is designed as UI independent and can work with any type of UI system, while there are multiple pre-built and integrated options are provided out of the box.

You can create your own theme, And someone is already doing it: https://github.com/realLiangshiwei/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla,  https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE

**Comment by 274188A** [comment]
Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla is not .net5.0 compatible right now...

**Comment by realLiangshiwei** [comment]
> Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla is not .net5.0 compatible right now...

https://github.com/realLiangshiwei/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/4eb03f5a642baeacc46c1bf54aa2cc420368590e
