### ISSUE TITLE
 error when  calling:abp generate-proxy

### ISSUE THREAD

**Issue by slm-w** [abpframework/abp#6496]
Hello,
I'm facing an error when using the command: abp generate-proxy
ABP Framework version: Version 4.0.0 (Stable).
User Interface: Angular.
Steps needed to reproduce the problem: Executing the command abp generate-proxy
Exception message:please double chek  the URL in the source project environment and make sure you application is up and running
In addition, how can I fix the warning: Couldn't determinate version of "@abp/ng.schematics" package.
[WRN] Couldn't determinate version of "@abp/ng.schematics" package.
[Error] [API NOT AVAILABLE]please double chek  the URL in the source project environment and make sure you application is up and running

**Comment by ahmetpekbas** [comment]
Seconded. I have the exact same issue on a fresh cli installation of the preview version.

**Comment by slm-w** [comment]
@atpekbas did you fix it?

**Comment by slm-w** [comment]
@maliming

**Comment by maliming** [comment]
@slm-w Have you run the `API.Host`?

**Comment by slm-w** [comment]
@maliming  yes,using F5 in visual studio,

**Comment by maliming** [comment]
Is your project is brand new template project?

**Comment by slm-w** [comment]
@maliming  yes

**Comment by maliming** [comment]
@mehmet-erim What do you think?

**Comment by ebicoglu** [comment]
I would like to mention that if you're running the host project via Visual Studio and the client is making requests from another computer (not from localhost) then your host will not accept requests! this is a limitation of Visual Studio. When VS starts a web app it's not publicly available. You can use `dotnet run` and check the URL from the client's computer.

**Comment by slm-w** [comment]
@ebicoglu i got the same error,how can i check if my API is up or down?thank you

**Comment by ahmetpekbas** [comment]
@slm-w If you running in visual studio, your default browser should pop up with the swagger ui, similar URL to the following, but with a different port.
https://localhost:44342/swagger/index.html

If it doesn't open by itself, check the properties of your **HttpApi.Host** properties -> ASP.NET Core -> App URL.
Looks like this: https://localhost:44342

This is the exact URL which has to be in your angular/src/environments/environment.ts should be set as your api.default.url

**Comment by DivVishal** [comment]
> @slm-w If you running in visual studio, your default browser should pop up with the swagger ui, similar URL to the following, but with a different port.
> https://localhost:44342/swagger/index.html
> 
> If it doesn't open by itself, check the properties of your **HttpApi.Host** properties -> ASP.NET Core -> App URL.
> Looks like this: https://localhost:44342
> 
> This is the exact URL which has to be in your angular/src/environments/environment.ts should be set as your api.default.url

@atpekbas Even though the urls are same in both UI and core code. I am facing issue for generate proxy.

**Comment by mtozlu** [comment]
For future reference you can solve it like this;
`abp generate-proxy -t ng -u https://localhost:44339`

Thanks to @mustafaekicics
https://github.com/abpframework/abp/issues/12664#issuecomment-1132397107
