### ISSUE TITLE
"npm install" unable to resolve dependency tree for angular/common (using ABP CLI default project)

### ISSUE THREAD

**Issue by ahmetpekbas** [abpframework/abp#6502]
ABP Framework version: 4.0 Stable
UI: Angular 11

Installing npm packages fails on the default angular project fails.
The dependencies don't seem to be fully updated to Angular 11 yet.

Reproduction:
1. Create a new project using the ABP CLI with Angular as a UI
2. navigate to the "angular" folder and perform "npm install"

**Error:**

> ******@****** angular % npm install              
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: AT@0.0.0
> npm ERR! Found: @angular/common@11.0.3
> npm ERR! node_modules/@angular/common
> npm ERR!   @angular/common@"~11.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"^10.0.0" from @ng-bootstrap/ng-bootstrap@8.0.0
> npm ERR! node_modules/@ng-bootstrap/ng-bootstrap
> npm ERR!   peer @ng-bootstrap/ng-bootstrap@">=6.0.0" from @abp/ng.components@4.0.0
> npm ERR!   node_modules/@abp/ng.components
> npm ERR!     @abp/ng.components@"~4.0.0" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /Users/********/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/********/.npm/_logs/2020-12-05T20_17_00_688Z-debug.log

**Comment by maliming** [comment]
Have you tried run yarn command to restore the packages?

**Comment by ahmetpekbas** [comment]
> Have you tried run yarn command to restore the packages?

I just tried it and "yarn install" seems to be working.
Nonetheless, the issue still stands that npm is recognizing the dependency issue and thus not working.

**Comment by maliming** [comment]
@mehmet-erim What do you think?

**Comment by mehmet-erim** [comment]
`npm install` command works, we have tested. Please check your node version @atpekbas. See my installed node and npm versions: 

![image](https://user-images.githubusercontent.com/34455572/101320155-4894b880-3874-11eb-8995-5b163d2070aa.png)

**Comment by ahmetpekbas** [comment]
It seems to have been a version problem with npm.

Fails with:
> npm version: 7.0.8
> node version: v12.17.0

Succeeds with:
> npm version: 6.14.9
> node version: v12.17.0

From my perspective, it is not an issue with abp anymore, as I was able to run it successfully with npm.

Ticket can be closed.

**Comment by lemchen** [comment]
still have problem with npm 8.5.3 & node v16.14.0

**Comment by jeremylcarter** [comment]
Use legacy peer dependencies.
`npm install --legacy-peer-deps` or `npm install --force`

**Comment by L1uXO330B7** [comment]
I use legacy peer dependencies,still not work  for npm 8.1.2 & node v16.13.12

**Comment by kai98k** [comment]
I used legacy peer dependencies, it still doesn't work.
Maybe the solution is that make npm -> 6.14.0, node -> v12.17.0 ?
