### ISSUE TITLE
Why does my ITransientDependency not work?

### ISSUE THREAD

**Issue by aceiling** [abpframework/abp#6504]
Mongo Migrator
I hava a MongodbContextMigrator,when i run DbMigrator program,In DbMigrationService program, the _dbSchemaMigrators can't get my custom MongodbContextMigrator,I wonder what's wrong with it.
Source Code is
<img width="955" alt="1" src="https://user-images.githubusercontent.com/20451024/101271184-8e417a80-37bb-11eb-97e8-af33f1853e1e.png">
<img width="1232" alt="2" src="https://user-images.githubusercontent.com/20451024/101271188-939ec500-37bb-11eb-8759-ea7faf7b4459.png">
<img width="1200" alt="3" src="https://user-images.githubusercontent.com/20451024/101271190-97324c00-37bb-11eb-9479-c0b125ad180e.png">
<img width="796" alt="4" src="https://user-images.githubusercontent.com/20451024/101271192-9d282d00-37bb-11eb-8e85-e72d8043411b.png">

Help me , please ...

**Comment by maliming** [comment]
Please share the code and steps.

**Comment by hikalkan** [comment]
Your class name should be `MongoDbDataDictionaryDbSchemaMigrator`

**Comment by aceiling** [comment]
@hikalkan tks,it works. why does class name affect dependency injection?

**Comment by gdlcf88** [comment]
You can find it in the ABP framework documentation: https://docs.abp.io/en/abp/latest/Dependency-Injection#exposed-services-by-convention

**Comment by aceiling** [comment]
@gdlcf88 tks.
