### ISSUE TITLE
ABP CLI update the specified version not work

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#6506]
My ABP CLI Version: 4.0.0.
My project ABP version: 3.0.5
When I used the "abp update -v 3.3.2" command to update the ABP version, the console message show update to the "4.0.0" not my expected version "3.3.2".
![image](https://user-images.githubusercontent.com/74571567/101300112-74616f80-386f-11eb-8abe-ce94ff54476f.png)

I have tried to downgrade my ABP CLI version to 3.3.2, it still not work.
![image](https://user-images.githubusercontent.com/74571567/101301384-a248b300-3873-11eb-8682-98c6a4febc4e.png)

Anyone have this issue? Thanks so much. 

BTW, the update failed.
![image](https://user-images.githubusercontent.com/74571567/101300229-d9b56080-386f-11eb-9b6f-24f0ebdf38f1.png)

Sometimes the specified update version would be important for the real environment.

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/CLI#update

Currently only supports updating to the latest version

**Comment by jack-gaojz** [comment]
> See https://docs.abp.io/en/abp/latest/CLI#update
> 
> Currently only supports updating to the latest version

ok, thanks so much. :)

**Comment by realLiangshiwei** [comment]
We can add this feature in 4.1

**Comment by stormlex4all** [comment]
Try "abp update --v (desiredVersion)" instead
