### ISSUE TITLE
Volo.Abp.EntityFrameworkCore.Oracle missing in Abp 4.0

### ISSUE THREAD

**Issue by DanzigGLT** [abpframework/abp#6513]
The new Net5 / Efc5 compliant driver was released on 16th of November. Any specific reason why the Oracle-Package is missing in the final of ABP framework 4.0?

**Comment by maliming** [comment]
> e new Net5 / Efc5 compliant driver was released on 16th of November

Can you share a link?

**Comment by realLiangshiwei** [comment]
> .NET 5 support is imminent. It could be today. When that happens, I'll have an EF Core 5 update too. The short version is that we're still on track for a December/January Oracle EF Core 5 release.

https://github.com/oracle/dotnet-db-samples/issues/81#issuecomment-728258466

**Comment by DanzigGLT** [comment]
Oracle.ManagedDataAccess.Core 2.19.100 @ nuget.org

that was said to be one!?

**Comment by maliming** [comment]
We are using https://www.nuget.org/packages/Oracle.EntityFrameworkCore/ , It's not support EF Core 5.0 yet.

**Comment by DanzigGLT** [comment]
> We are using https://www.nuget.org/packages/Oracle.EntityFrameworkCore/ , It's not support EF Core 5.0 yet.

Ah, my bad, tomatoes on my eyes. sorry...
