### ISSUE TITLE
issuse with using System.Text.Json in abp v4.0.0

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#6517]
if I set using **Json.Net** like below,it works fine
``` C#
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PreConfigure<Volo.Abp.Json.AbpJsonOptions>(options =>
            {
                options.UseHybridSerializer = false;
            });
        }
```
but when using **System.Text.Json**
the nullable value , such as DateTime?  Guid? , will can not work when it received an empty string value.

**Comment by maliming** [comment]
An empty string is not a valid JSON value. Please check Microsoft's documentation.

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to
