### ISSUE TITLE
Blazor documents (Part III)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6519]
- [ ] Page Header (https://github.com/abpframework/abp/blob/rel-4.0/docs/en/UI/Blazor/Page-Header.md)

**Comment by ilkayilknur** [comment]
Moving this 4.2 preview. We will add the `PageHeader` component to the open-source side with blazor UI extensions work.

**Comment by ilkayilknur** [comment]
I'm changing the milestone to 4.3 preview since we don't use the page header component on the open-source side. We will add the component with the UI extensions implementation.

**Comment by ilkayilknur** [comment]
Done.
