### ISSUE TITLE
url path changed when upgrade to 4.0

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#6521]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**.
4.0.0

when i upgrade to 4.0 the url changed
![image](https://user-images.githubusercontent.com/1214546/101368119-bcb97580-38e1-11eb-8e20-fb6d32d2cff0.png)
how to chang to old format
/api/app/sysdictitem/bytypecode

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/blob/dev/docs/en/Migration-Guides/Abp-4_0.md#use-the-v3x-style-urls
