### ISSUE TITLE
Multiple Contents Localization -> Volo.Abp.AbpException: Could not find a file/folder at the location: /Emailing/WelcomeEmail/Templates

### ISSUE THREAD

**Issue by bartvanhoey** [abpframework/abp#6523]
When following the documentation Text Templating - Multiple Contents Localization I receive the exception below. The application cannot find the language templates in the /Emailing/WelcomeEmail/Templates although they have been added as  an embedded resource in the Domain.csproj file

*  **ABP Framework version 4.0 - .NET5.0**.

* Exception message and **stack trace** if available (check the logs).

[19:51:27 ERR] Could not find a file/folder at the location: /Emailing/WelcomeEmail/Templates
Volo.Abp.AbpException: Could not find a file/folder at the location: /Emailing/WelcomeEmail/Templates
   at Volo.Abp.TextTemplating.VirtualFiles.LocalizedTemplateContentReaderFactory.CreateInternalAsync(TemplateDefinition templateDefinition)
   at Volo.Abp.TextTemplating.VirtualFiles.LocalizedTemplateContentReaderFactory.CreateAsync(TemplateDefinition templateDefinition)
   at Volo.Abp.TextTemplating.VirtualFiles.VirtualFileTemplateContentContributor.GetOrNullAsync(TemplateContentContributorContext context)
   at Volo.Abp.TextTemplating.TemplateContentProvider.GetContentOrNullAsync(ITemplateContentContributor[] contributors, TemplateContentContributorContext context)
   at Volo.Abp.TextTemplating.TemplateContentProvider.GetContentOrNullAsync(TemplateDefinition templateDefinition, String cultureName, Boolean tryDefaults, Boolean useCurrentCultureIfCultureNameIsNull)
   at Volo.Abp.TextTemplating.TemplateRenderer.RenderSingleTemplateAsync(TemplateDefinition templateDefinition, Dictionary`2 globalContext, Object model)
   at Volo.Abp.TextTemplating.TemplateRenderer.RenderInternalAsync(String templateName, Dictionary`2 globalContext, Object model)

**Comment by maliming** [comment]
hi

Can you share a project?

**Comment by bartvanhoey** [comment]
https://github.com/bartvanhoey/AbpTemplateReplaceRepo

**Comment by maliming** [comment]
What are the steps?

**Comment by bartvanhoey** [comment]
I run both the HttpApi.Host project and Blazor project and when I click on the Send Welcome Email button the method SendWelcomeEmail gets called. 

In the SendWelcomeEmail method  the statement  await _templateRenderer.RenderAsync("WelcomeEmail", cultureName: culture); throws the error because it does not find the template for the english culture

**Comment by bartvanhoey** [comment]
I run both the HttpApi.Host project and Blazor project and when I click on the Send Welcome Email button the method SendWelcomeEmail **of the EmailService** gets called.

In the SendWelcomeEmail method the statement await _templateRenderer.RenderAsync("WelcomeEmail", cultureName: culture); throws the error because it does not find the template for the english culture

**Comment by maliming** [comment]
It seems your project miss `appsettings.json` file.

**Comment by bartvanhoey** [comment]
Correct. It's not on github as it contained my gmail password. This is the appsettings file without my credentials

{
  "App": {
      "SelfUrl": "https://localhost:44336",
      "CorsOrigins": "https://*.TemplateReplace.com,http://localhost:4200,https://localhost:44307"
  },
  "ConnectionStrings": {
      "Default": "Server=(LocalDb)\\MSSQLLocalDB;Database=TemplateReplace;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "AuthServer": {
      "Authority": "https://localhost:44336",
      "RequireHttpsMetadata": "false"
  },
  "StringEncryption": {
      "DefaultPassPhrase": "YDjhiBCBwGwKVDbG"
  },
  "Settings": {
      "Abp.Mailing.Smtp.Host": "smtp.gmail.com",
      "Abp.Mailing.Smtp.Port": "587",
      "Abp.Mailing.Smtp.UserName": "your-gmail-emailaddress",
      "Abp.Mailing.Smtp.Password": "your-password",
      "Abp.Mailing.Smtp.Domain": "",
      "Abp.Mailing.Smtp.EnableSsl": "true",
      "Abp.Mailing.Smtp.UseDefaultCredentials": "false",
      "Abp.Mailing.DefaultFromAddress": "bartvanhoey@gmail.com",
      "Abp.Mailing.DefaultFromDisplayName": "ABP application"
  }
}

**Comment by maliming** [comment]
I will fix this problem. You can comment out this line for now. https://github.com/bartvanhoey/AbpTemplateReplaceRepo/blob/gh-pages/src/TemplateReplace.HttpApi.Host/TemplateReplaceHttpApiHostModule.cs#L59

**Comment by parasdaryanani** [comment]
I'm facing a similar issue with ABP v4.4 on .NET 5.0 where email rendering works during development, but when deployed to production in a docker container I get this error: 

`AbpException: Could not find a file/folder at the location: Email/Templates/ConfirmEmail.liquid`

- I followed the steps to setup text template rendering with the Scriban engine. During dev with both debug and release, email template rendering works fine and emails are sent.

- I have inspected the running docker container and the template files are physically present in the specified directory. I have also followed the instructions to make the EmbeddedResource is selected and the files are always copied over.

- I tried changing the path to the absolute path inside the container (/app/Email/Templates/ConfirmEmail.liquid), with no luck. Can you think of any reason this is happening?

- Dev environment: JetBrains Rider on macos
- Live environment Ubuntu 20.04 with dotnet 5.0 installed and running inside a docker container.

Exception and stack trace:
AbpException: Could not find a file/folder at the location: Email/Templates/ConfirmEmail.liquid

STACK TRACE:    at Volo.Abp.TextTemplating.VirtualFiles.LocalizedTemplateContentReaderFactory.CreateInternalAsync(TemplateDefinition templateDefinition)\n   at Volo.Abp.TextTemplating.VirtualFiles.LocalizedTemplateContentReaderFactory.CreateAsync(TemplateDefinition templateDefinition)\n   at Volo.Abp.TextTemplating.VirtualFiles.VirtualFileTemplateContentContributor.GetOrNullAsync(TemplateContentContributorContext context)\n   at Volo.Abp.TextTemplating.TemplateContentProvider.GetContentOrNullAsync(ITemplateContentContributor[] contributors, TemplateContentContributorContext context)\n   at Volo.Abp.TextTemplating.TemplateContentProvider.GetContentOrNullAsync(TemplateDefinition templateDefinition, String cultureName, Boolean tryDefaults, Boolean useCurrentCultureIfCultureNameIsNull)\n   at Volo.Abp.TextTemplating.TemplateRenderingEngineBase.GetContentOrNullAsync(TemplateDefinition templateDefinition)\n   at Volo.Abp.TextTemplating.Scriban.ScribanTemplateRenderingEngine.RenderSingleTemplateAsync(TemplateDefinition templateDefinition, Dictionary`2 globalContext, Object model)\n   at Volo.Abp.TextTemplating.Scriban.ScribanTemplateRenderingEngine.RenderInternalAsync(String templateName, Dictionary`2 globalContext, Object model)\n   at Volo.Abp.TextTemplating.Scriban.ScribanTemplateRenderingEngine.RenderAsync(String templateName, Object model, String cultureName, Dictionary`2 globalContext)\n   at Volo.Abp.TextTemplating.AbpTemplateRenderer.RenderAsync(String templateName, Object model, String cultureName, Dictionary`2 globalContext)\n   at TexpertAI.Services.Email.EmailService.SendAsync(String recipient, String subject, String templateName, Object model) in /app/src/TexpertAI.Application/Services/Email/EmailService.cs:line 33\n   at TexpertAI.Account.AccountService.SendTestEmail() in /app/src/TexpertAI.Application/Services/Account/AccountService.cs:line 169\n   at lambda_method1592(Closure , Object )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n

**Comment by amirhossein92** [comment]
> 

I had the same problem and resolved it by adding the `<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>`
as described in [abp virtual file documentation](https://docs.abp.io/en/abp/latest/Virtual-File-System#embedding-the-files)
