### ISSUE TITLE
netstandard2.0 in Application.Contracts

### ISSUE THREAD

**Issue by profitp** [abpframework/abp#6524]
templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Application.Contracts/MyCompanyName.MyProjectName.Application.Contracts.csproj

<TargetFramework>netstandard2.0</TargetFramework> - why?

**Comment by realLiangshiwei** [comment]
netstandard2.0 can be helpful if we share application contracts or domain shared with an application that has no .net5 support.

**Comment by xyfy** [comment]
I saw many project has updated to netstandard2.1 in abp v4.0.0

does we need change the netstandard2.0 to netstandard2.1?

![微信图片_20201202174117](https://user-images.githubusercontent.com/7838147/101425916-f1a3e780-3936-11eb-8625-a3e5ec710140.jpg)


> netstandard2.0 can be helpful if we share application contracts or domain shared with an application that has no .net5 support.
