### ISSUE TITLE
Slow debugging

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#6526]
* Your **ABP Framework version**. 3.0.2
* **OS**: MacOS
* **IDE**: Happens with VS for Mac and with Jetbrains Rider. 
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI: 
Blazor and Razor Pages

Am I the only one with performance problems when debugging? Since I start debugging till the website is available it takes around 50 seconds.

I'm almost certain that it is because of the interceptors.  On the debug output I have the following message, sometimes it takes around 15 seconds. 

```
Loaded Assembly '<unknown>'
Loading module DynamicProxyGenAssembly2 in application domain 1:clrhost
Pdb file for assembly DynamicProxyGenAssembly2 was not found or failed to read
```

The catch is that if I run it without the debugger attached, it takes 3 seconds to boot. Anyone experiencing the same issue?
Related to: https://youtrack.jetbrains.com/issue/RIDER-51041

**Comment by maliming** [comment]
No one has reported such a problem. I think it has something to do with your environment. : )

**Comment by wocar** [comment]
Yes, its a possibility. Any clues on what to do. 1min to start debugging is a big pain

**Comment by maliming** [comment]
Maybe you can try it on another computer.

**Comment by wocar** [comment]
Thank you for the support given. For anyone else wondering what might it be, I'm using Rider + MacOS disabled this feature:

![image](https://user-images.githubusercontent.com/9215073/102158265-b62d7f80-3e46-11eb-8ba4-1fe000d7e456.png)

And now instead of 30+ secs its like 8 secs. Thank you once again.
