### ISSUE TITLE
The Book List Page error on chrome acme is not defined #6109 is remains

### ISSUE THREAD

**Issue by wen676395159** [abpframework/abp#6527]
hi，The problem remains. Any project created through ABP cli 4.0 will report this.
![image](https://user-images.githubusercontent.com/3404283/101432213-6846e200-3943-11eb-8c7d-837993d27797.png)

**Comment by maliming** [comment]
Duplicate of #6109

**Comment by philiplai** [comment]
I can still duplicate this issue, @maliming .  I used mvc mongodb options, not tiered.  Is there a plan to fix this issue?  You can not do anything with this issue there.
