### ISSUE TITLE
Blazor Project not running in VS Studio in debug mode

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#6528]
* Your **ABP Framework version** - 4.0.0
* Your **User Interface** - Blazor
* Exception message and **stack trace** if available (check the logs).

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://localhost:44307/_framework/System.Threading.ThreadPool.dll' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.
localhost/:1 Unknown error occurred while trying to verify integrity.
blazor.webassembly.js:1 Error: Failed to start platform. Reason: TypeError: Failed to fetch
    at blazor.webassembly.js:1
    at blazor.webassembly.js:1
    at Object.throw (blazor.webassembly.js:1)
    at s (blazor.webassembly.js:1)
```

* Steps needed to **reproduce** the problem.
1. Run the Host project via cmd using DOtnet Run and then
2. Run the Blazor app from VS Studio via IIS Express

Vineet
LearnABPFramework.com

**Comment by cotur** [comment]
Did you follow all steps of the  article (given below)?

https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio

**Comment by ilkayilknur** [comment]
I'm not able to reproduce this on my end. 
- Step 1
![image](https://user-images.githubusercontent.com/5785927/102351193-17746080-3fb7-11eb-8675-4f5fa5bdffa1.png)

- Step 2
![image](https://user-images.githubusercontent.com/5785927/102351231-29ee9a00-3fb7-11eb-8a80-253dc6c37e79.png)

The blazor app works as expected. Honestly, I'm getting these kinds of errors while working on blazor apps. Most of the time, rebuilding projects or reloading the page Ctrl+F5 fixes these issues. Feel free to reopen this issue if you find anything further.
