### ISSUE TITLE
Why did hangfire start two servsers?

### ISSUE THREAD

**Issue by OldKing-lion** [abpframework/abp#6531]
![image](https://user-images.githubusercontent.com/13028615/101462094-bcb78500-3976-11eb-96a9-89f65580747f.png)
![image](https://user-images.githubusercontent.com/13028615/101462128-c93bdd80-3976-11eb-9499-330a526f4c4c.png)

**Comment by realLiangshiwei** [comment]
Do not call `UseHangfireServer`. We handle it internally.

https://github.com/abpframework/abp/blob/f107600e277276bff5c4e56c570e9bfa1573b652/framework/src/Volo.Abp.HangFire/Volo/Abp/Hangfire/AbpHangfireModule.cs#L23

**Comment by OldKing-lion** [comment]
good
