### ISSUE TITLE
Lookup extra properties is not working

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6543]
Just try the example given in https://github.com/abpframework/abp/issues/6308

Exception message is:

````
System.Collections.Generic.KeyNotFoundException: The given key 'PrimaryRoleId' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AspNetCore.Pages_Identity_Users_EditModal.<ExecuteAsync>b__20_6() in D:\Github\abp\modules\identity\src\Volo.Abp.Identity.Web\Pages\Identity\Users\EditModal.cshtml:line 42
````

Related code:

https://github.com/abpframework/abp/blob/c9d4d97cd3fac451e9d11e3b7f72745069b1e3e0/modules/identity/src/Volo.Abp.Identity.Web/Pages/Identity/Users/EditModal.cshtml#L41-L42

We should not use dictionary indexer (`@Model.UserInfo.ExtraProperties[propertyInfo.Name]`) because it throws exception if given key is not present. Instead, use `@Model.UserInfo.GetProperty(propertyInfo.Name)` ([see the document](https://docs.abp.io/en/abp/latest/Entities#getproperty-setproperty-extension-methods))

(fix it in rel-4.0 branch please)

Additional notes;

* Don't change `asp-for="UserInfo.ExtraProperties[propertyInfo.Name]"` since it provided the model expression.
* Also change here: https://github.com/abpframework/abp/blob/c9d4d97cd3fac451e9d11e3b7f72745069b1e3e0/modules/identity/src/Volo.Abp.Identity.Web/Pages/Identity/Users/EditModal.cshtml#L54
* We can remove the comment: https://github.com/abpframework/abp/blob/c9d4d97cd3fac451e9d11e3b7f72745069b1e3e0/modules/identity/src/Volo.Abp.Identity.Web/Pages/Identity/Users/EditModal.cshtml#L21

**Comment by ilkayilknur** [comment]
I tested this feature multiple times before the stable release. In my tests, I was using the same DB and the same page. Probably, that's why I couldn't catch this before. I'm working on it.
