### ISSUE TITLE
An exception was thrown while deserializing the token. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.

### ISSUE THREAD

**Issue by eng-mohammed-emam** [abpframework/abp#6547]
Hello, 
I'm using Abp framework version 3.3.1
I'm facing the below error:

Steps:
1 - Hosing the 3 projects Angular, Host, and Identity on Local IIS.
2- Click on the "Login" button on the Angular website.
3- See the message "Error 500" on the browser and see the below exception in the log file.

    [ERR] An exception was thrown while deserializing the token.
    Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
     ---> System.Security.Cryptography.CryptographicException: The key {c511fba1-85b7-40f5-a2c0-3ff08285f7b7} was not found in the key ring.
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
       at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
       --- End of inner exception stack trace ---
       at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
           at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

Any help is appreciated.
Thanks.

**Comment by maliming** [comment]
Does it work without `Local IIS`?

**Comment by eng-mohammed-emam** [comment]
Yep. The project works while developing on port 4200 (http://loaclhost:4200).

**Comment by maliming** [comment]
Hi
Does the template created by CLI project have the same problem?
You can also try the clear the redis data.

**Comment by eng-mohammed-emam** [comment]
Hi,
I suspect in Redis because it isn't installed on my machine.
I want to disable Redis completely. Can I? or Abp Framework must depend on Redis?

If Redis is a must, is there good documentation for installing it on Windows 10?

Thanks.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/3487

**Comment by eng-mohammed-emam** [comment]
Hi @maliming,

The above problem fixed after installing Redis.

I hope you help me one more time.
When I click on the "Login" button in the Angular web application, I see an error of 500.

I checked the log file and found that this error:

    [ERR] Invalid redirect_uri: https://192.168.100.175:7070
     {"ClientId":"Amanat_App","ClientName":"Amanat_App","RedirectUri":null,"AllowedRedirectUris":["http://localhost:4200"]

Where the IP and port I set in Local IIS.

The problem why still I see the allowed AllowedRedirectUris is http://localhost:4200? although `appSettings.json` of Identity server like this:

    {
      "App": {
        "SelfUrl": "https://192.168.100.175:7072",
        "CorsOrigins": "https://192.168.100.175:7070"
     },
    ...
    }

Is there any place in the database that has the URL of http://localhost:4200 I should change?

**Comment by maliming** [comment]
You need to change the DbMigrator settings.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.DbMigrator/appsettings.json#L15

**Comment by eng-mohammed-emam** [comment]
Dear @maliming,

Should I change the values of keys  "MyProjectName_Web", "MyProjectName_Swagger"?

If yes, "MyProjectName_Swagger": is the Host Service but "MyProjectName_Web" is for what?

**Comment by eng-mohammed-emam** [comment]
I'm facing Angular error in the console although the Identity server and Host server settings seem valid.

    Access to XMLHttpRequest at 'https://192.168.100.175:7071/api/abp/application-configuration' from origin 'https://192.168.100.175:7070' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Identity server appsettings.json like:

    {
      "App": {
        "SelfUrl": "https://192.168.100.175:7072",
        "CorsOrigins": "https://192.168.100.175:7070"
      }
    }

Host server appsettings.json like:
    
    {
      "App": {
       "CorsOrigins": "https://192.168.100.175:7070"
      }
    }

I appreciate your support.
Thanks.

**Comment by maliming** [comment]
hi @eng-mohammed-emam 

You can check the application log. Or the application environment. Maybe the configuration is wrong.
