### ISSUE TITLE
how to add a action to identityUserController

### ISSUE THREAD

**Issue by ThreeLambs** [abpframework/abp#6549]
**I want to create a api like:``api/identity/users/{id}/organization-units``,what should i do?**
I try to do that：
 ```
 public interface IMyIdentityUserAppService : Volo.Abp.Identity.IIdentityUserAppService 
    {
        Task<List<OrganizationUnitDto>> GetOrganizationUnitsAsync(Guid id);
    } 
```
```
 [Authorize(IdentityPermissions.Users.Default)]
    public class MyIdentityUserAppService: IdentityUserAppService,  IMyIdentityUserAppService
    {
       
        public MyIdentityUserAppService(IdentityUserManager userManager, 
            IIdentityUserRepository userRepository, 
            IIdentityRoleRepository roleRepository):base(userManager, userRepository, roleRepository)
        {

        }

        [Authorize(IdentityPermissions.Users.Default)]
        public virtual async Task<List<OrganizationUnitDto>> GetOrganizationUnitsAsync(Guid id)
        {
            List<OrganizationUnit> organizationUnits = await UserRepository.GetOrganizationUnitsAsync(id);
            return new List<OrganizationUnitDto>(ObjectMapper.Map<List<OrganizationUnit>, List<OrganizationUnitDto>>(organizationUnits));
        }
```
```
 [RemoteService(Name = IdentityRemoteServiceConsts.RemoteServiceName)]
    [Area("identity")]
    [ControllerName("User")]
    [Route("api/identity/users")]
    public class MyIdentityUserController : IdentityUserController, IMyIdentityUserAppService
    {
        private readonly IMyIdentityUserAppService _myIdentityUserAppService;

        public MyIdentityUserController(IMyIdentityUserAppService myIdentityUserAppService) : base(myIdentityUserAppService)
        {
            _myIdentityUserAppService = myIdentityUserAppService;
        }

        [HttpGet]
        [Route("{id}/organization-units")]
        public async Task<List<OrganizationUnitDto>> GetOrganizationUnitsAsync(Guid id)
        {
            return await _myIdentityUserAppService.GetOrganizationUnitsAsync(id);
        }
    }
```
it doesn't work，I need help

**Comment by xyfy** [comment]
if you want override the pre-defined service ,have a look at https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services

**Comment by ThreeLambs** [comment]
> if you want override the pre-defined service ,have a look at https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services

ok

**Comment by ThreeLambs** [comment]
> if you want override the pre-defined service ,have a look at https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services

I Try to Override Identity Modules,but failed.
1. I use ``abp get-source Volo.Identity`` to create a project A, then add ``GetOrganizationUnitsAsync(Guid id)``  to IIdentityUserAppService (Volo.Abp.Identity.Application.Contracts) ... 
2. I create demo project refrence A.
run the demo,i don't fond then api GetOrganizationUnitsAsync from swagger page.
because of some other nuget package refrence Volo.Abp.Identity.Application ..., 
``Volo.Abp.Identity.Application.Contracts.dll , Volo.Abp.Identity.Application.dll ... `` it always old ,it is not from A.
What should I Do?

**Comment by abdumostafa** [comment]
@ThreeLambs I have the same issue , How could you manage to add an action to Identity user service?

**Comment by jakeuj** [comment]
> @ThreeLambs I have the same issue , How could you manage to add an action to Identity user service?

See [Overriding an Application Service](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-an-application-service)

Module will call your MyIdentityUserAppService, but swagger still has MyIdentityUser and IdentityUser API at the same time.
