### ISSUE TITLE
How to create new Role (by code) during the Tenant creation process from UI

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#6550]
ABP.IO V.4 / Angular

I am trying to add the creation of roles while I create a new Tenant from the UI on ABP.IO Framework version 4.

From ABP.IO documentation, I found that by using the existing class SaasDataSeedContributor I can "seed" some datas while I am creating a new Tenant.

My issue is that from this class, I do not have permission to use IIdentityRoleAppService.CreateAsync method (Given policy has not granted). So I tried to go through an AppService and use IdentityRoleManager or even IIdentityRoleRepository,but it is not possible to create IdentityRole object as the constructor is inaccessible due to his protection level.

Any thought about it? Is there any way to do it? 

Thanks for your help

**Comment by cbaille** [comment]
I actually found the constructor:
IdentityRole(Guid Id, string Name, [Guid? tenantId = null])
which is not protected, so I use IdentityRoleManager directly on SaasDataSeedContributor class and all works well now.

**Comment by brunobertechini** [comment]
@cbaille where are you adding permissions to your role?

**Comment by cbaille** [comment]
I added it on the same class, just after i create my roles.

I have my list of permission where for each I do:

permissionManager.SetForRoleAsync(...)

**Comment by element-dlapointe** [comment]
Is there a way to create roles on Tenant creation? As the seed only works when running the DbMigrator but what if we want to dynamically adds roles / perms whenever a new tenant is created using the UI?

Seems like we cant override the TenantAppService as it doesnt allow calling the DB as there is already a call open (i dont know what tough?!) 
![image](https://user-images.githubusercontent.com/63807551/191107792-7bc65fe3-b2ca-4643-8f7e-79c45593aaee.png)

Thank you
