### ISSUE TITLE
Repository pattern and IQueryable

### ISSUE THREAD

**Issue by vnc4567** [abpframework/abp#6554]
Hello, I've been using ABP.IO for 6 month.

During those 6 months I found myself confused about some code snippets made by experiecied ABP.IO users; in their code, they are using IQueryable AND repository pattern at the same time. Like this :

Example 1 (IQueryable in AppService) :

```
1.	public async Task LoadPrecommandeForm(LoadPrecommandeFormRequestDto request)  
2.	        {  
3.	              var operation = await _operationRepository  
4.	                .Where(o => o.numerooperation == request.NumeroOperation && o.IsActive)  
5.	                .Include(o => o.id_competenceNavigation)  
6.	                .SingleOrDefaultAsync();  
7.	   
8.	             //do smth  
9.	  
10.	}
```  
As you can see in this example, we are directly attacking the database by using .Where() on the operationRepository. I find it wrong, here is why

**Pros :**

- Faster to dev

**Cons :**

- leaking database concerns to the application logic
- LSP violation (Liskov Subtitution Principle)
- Application coupled with EntityFramework

 

In my opinion, it is more clean to do something like this (separating the usage of Iqueryable and Repository Pattern
Example 2 (Use of method in repository)

```
1.	public async Task LoadPrecommandeForm(LoadPrecommandeFormRequestDto request)  
2.	        {  
3.	              var operation = await _operationRepository.GetActiveOperation(request.NumeroOperation);  
4.	  
5.	   
6.	             //do smth  
7.	  
8.	}  
```

As you can see in this example, we would attack the database inside GetActiveOperation(). Here are the advantages

**Pros :**

- Better separation of concern
- Naming method give us some readability
- ORM agnostic

**Cons :**

- We have to create method 

I, myself, don't see any advantage about using repository pattern with the use of IQueryable (example 1).

**Could you tell me what are the advantages and why using it? Why not use DbSet directly ?**

I check several articles and courses about the IQueryable returned from Repositories :
Source :
https://enterprisecraftsmanship.com/posts/specification-pattern-c-implementation/
https://app.pluralsight.com/course-player?clipId=62d82703-9e4c-436d-ade4-2de309e4de5d 

![image](https://user-images.githubusercontent.com/19264566/101622193-08217000-3a17-11eb-8089-fa737ad402bb.png)

**Comment by Stirda** [comment]
Hi @vnc4567,

I understand why you are asking this because I did it to myself too.

> As you can see in this example, we would attack the database inside GetActiveOperation().
> ...
>   - leaking database concerns to the application logic

In my opinion, your query does not "attack" your database. It calls the repository. I agree that your example does not call a repository method, but LINQ helps to abstract what is behind the data source (what is behind the repository). I mean, you are not exposing database oriented concepts in your query.

> LSP violation (Liskov Subtitution Principle)

I don't see where.

> Application coupled with EntityFramework

Not by using ABP's [IAsyncQueryableExecuter](https://docs.abp.io/en/abp/latest/Repositories#option-3-iasyncqueryableexecuter).

I believe that you have to create a repository method when your call cannot be done without knowing the internals of your data source (often database) or if internals knowledge can produce a performance boost.

**Comment by Stirda** [comment]
I visited your two links at the end of your post. They talk about the Specification pattern, which is [now implemented in ABP](https://docs.abp.io/en/abp/latest/Specifications).

**Comment by vnc4567** [comment]
Thank you for your reply @Stirda :) ,

In the two links they talk about the Specification pattern, and explain why use it.  They also talk about the using of IQueryable :
They explain better than me :)

Returning IQueryable<T> from a repository
A question that is somewhat related to the specification pattern is: can repositories just return an IQueryable<T>? Wouldn’t it be easier to allow clients to query data from the backing store the way they want? For example, we could add a method to the repository like this:

// Repository
```
public IQueryable<T> Find()
{
    return session.Query<T>();
}
```
And then use it in a controller specifying the actual criteria ad hoc:

```
// Controller
public void SomeMethod()
{
    List<Movie> movies = _repository.Find()
        .Where(movie => movie.MpaaRating == MpaaRating.G)
        .ToList();
}
```
This approach has essentially the same drawback as our initial specification pattern implementation: it encourages us to violate the DRY principle by duplicating the domain knowledge. This technique doesn’t offer us anything in terms of consolidating it in a single place.

The second drawback here is that we are getting database notions leaking out of repositories. The implementation of IQueryable<T> highly depends on what LINQ provider is used behind the scene, so the client code should be aware that there potentially are queries which can’t be compiled into SQL.

And finally, we are also getting a potential LSP violation. IQueryables are evaluated lazily, so we need to keep the underlying connection opened during the whole business transaction. Otherwise, the method will blow up with an exception. By the way, an implementation with IEnumerables have essentially the same problem, so the best way to overcome this issue is to return IReadOnlyList or IReadOnlyCollection interfaces.

And if you have plurasight he explains in details in module 3 :
![image](https://user-images.githubusercontent.com/19264566/101656723-53517800-3a43-11eb-9d3e-72d4940dfbfd.png)

**Comment by vnc4567** [comment]
In my project. I have a reference to the ORM in my domain project because we use IQueryable.

![image](https://user-images.githubusercontent.com/19264566/101657380-1c2f9680-3a44-11eb-929a-13ad51dec0bf.png)
![image](https://user-images.githubusercontent.com/19264566/101657428-2a7db280-3a44-11eb-8210-e99c3efa7abd.png)

If I use IAsyncQueryableExecuter. as you mentioned, May I remove this reference ?

**Comment by Stirda** [comment]
> In the two links they talk about the Specification pattern, and explain why use it. They also talk about the using of IQueryable :
They explain better than me :)

Sorry but I didn't want to register so I didn't watch.

> This approach has essentially the same drawback as our initial specification pattern implementation: it encourages us to violate the DRY principle by duplicating the domain knowledge. This technique doesn’t offer us anything in terms of consolidating it in a single place.

ABP Specification pattern implementation solves this. No ?

> The second drawback here is that we are getting database notions leaking out of repositories. The implementation of IQueryable highly depends on what LINQ provider is used behind the scene, so the client code should be aware that there potentially are queries which can’t be compiled into SQL.

You got a point. Client of domain layer should be aware of Linq-To-Entities limitations in .NET support.

> And finally, we are also getting a potential LSP violation. IQueryables are evaluated lazily, so we need to keep the underlying connection opened during the whole business transaction. Otherwise, the method will blow up with an exception.

Again I thought that LSP violation implies inheritance. I don't see inheritance here.

About keeping the transaction open, I don't see the point. AFAIK IQueryable instantiation does not open a database connection. I think that this is a `ToList` call, for example, that does it. BTW ABP uses UnitOfWork, that guarantees connection disposal at the good moment. No ? 

> If I use IAsyncQueryableExecuter. as you mentioned, May I remove this reference ?

This is its purpose. So I think so. I would be happy if you can get rid of this dependency in your domain project 😃

**Comment by vnc4567** [comment]
Thank you @Stirda, 

I will continue to create method in Repository because of the first and second drawback. But I will use the Specification pattern in some case 

But I understand the use of the  IQueryable, in small project it will be faster to use it. 

I'll try to use IAsyncQueryableExecuter and try to remove this dependency from my domain :)

Thank you :)
