### ISSUE TITLE
How to see server validation text in Angular application

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#6556]
3.3.1 / Angular

When I use server validation for my DTOs - what I get in Angular client in case of validation error, is:

> System.Exception: ModelState is not valid! See ValidationErrors for details.
>    at Volo.Abp.AspNetCore.Mvc.Validation.ModelStateValidator.Validate(ModelStateDictionary modelState)

and so on.

What I want is to see correct validation text from server, like standard error dialog or toaster with "**Max length of [...] is ...**" text.

How to achieve this? From what I saw in documentation, I had impression it had to be handled automatically via `AbpValidationException`...

In some cases, I used _mapping of error codes to some inner codes_ to be used for `UserFriendlyException` throwing with custom error message. In this case it worked properly.
Do I need to do the same thing here? If so - how to catch `AbpValidationException` and transform it to `UserFriendlyException` in one place of the back-end application instead of spreading it in ton of calls?

**Comment by maliming** [comment]
Can you share some code?

**Comment by alexandis** [comment]
It's pretty straightforward and based on ABP template. For instance, I have this call in app service:

```
        [Authorize(CentralToolsPermissions.Applications.Modify)]
        public async Task<ApplicationDto> CreateAsync(ApplicationCreateDto input)
        {
            try
            {
                var application = ObjectMapper.Map<ApplicationCreateDto, Application>(input);
                var newApplication = await _applicationRepository.InsertAsync(application);
                await CurrentUnitOfWork.SaveChangesAsync();
                return ObjectMapper.Map<Application, ApplicationDto>(newApplication);
            }
            catch (DbUpdateException dbExtension) when (dbExtension.IsAlreadyExistsException())
            {
                throw new BusinessException(CentralToolsDomainErrorCodes.AlreadyExists, _stringLocalizer.GetString("Applications:ApplicationAlreadyExists"));
            }
        }
```

And here is DTO object:

```
    public class ApplicationCreateDto
    {
        [Required]
        public string Id { get; set; }

        [NoDangerousInput]
        [StringLength(CentralToolsCommonDbConsts.ShortNameMaxLength)]
        public string ShortName { get; set; }

        [StringLength(CentralToolsCommonDbConsts.FullNameMaxLength)]
        public string FullName { get; set; }

        [StringLength(CentralToolsCommonDbConsts.CommentMaxLength)]
        public string Comment { get; set; }
    }
```

where `NoDangerousInput` is custom validation attribute:

```
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter | AttributeTargets.Field, AllowMultiple = false)]
    public class NoDangerousInputAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            return new RegularExpressionAttribute("^[^&<>]+$").IsValid(Convert.ToString(value).Trim());
        }

        public override string FormatErrorMessage(string name)
        {
            return $"The field {name} contains dangerous characters (<, >, &).";
        }
    }
```

When I use some "dangerous" characters in my form:

![image](https://user-images.githubusercontent.com/6149843/101633397-d668d300-3a2f-11eb-9711-519f159b72e0.png)

I am getting the following error from server - no information with specific error text:

> {"Application":"ABRAPOL1","Tenant":-1,"ModuleId":"Test Module1","ErrorId":"3608a5a8-932d-4644-9a61-0c7eba5ec906","User":null,"Timestamp":"2020-12-09T15:04:00.7156359+02:00","MessageCode":"Backend:Error","MessageText":"ModelState is not valid! See ValidationErrors for details."}

**Comment by alexandis** [comment]
I've added the following to HttpApiHost and now the message is returned. Is it a way to go? Please confirm:

```
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IModelStateValidator))]
    public class AbxModelStateValidator : ModelStateValidator
    {
        public override void Validate(ModelStateDictionary modelState)
        {
            var validationResult = new AbpValidationResult();

            base.AddErrors(validationResult, modelState);

            if (validationResult.Errors.Any())
            {
                throw new BusinessException(
                    CentralToolsDomainErrorCodes.InvalidInput,
                    validationResult.Errors.Select(x => x.ErrorMessage).Aggregate((prev, next) => $"{prev}, {next}"));
            }
        }
    }
```

**Comment by olicooper** [comment]
I think there is some error handling missing for the `AbpValidationException`. I have noticed the same error when attempting to reset forgot password (/Account/ResetPassword) on the basic template created via the ABP CLI. If you type mismatching passwords in the `Password` and `Confirm password` fields, we get a 500 error instead of a 400 error or 'passwords do not match' alert. According to the [ABP docs](https://docs.abp.io/en/abp/latest/Exception-Handling#http-status-code-mapping) `AbpValidationException` should be a 400 error.
See also: https://github.com/abpframework/abp/issues/7119
