### ISSUE TITLE
Guid Foreign Key Navigation returns null

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#656]
I know it is not directly related to ABP, yet it is not working. However i try, it doesn't sets the object. Perhaps the problem is related to "guid". 

```
[Table("TBLBanner")]
public class TBLBanner : AuditedAggregateRoot<Guid>
{
  public byte Order { get; set; }

  [ForeignKey("TBLImages")]
  public Guid TBLImagesID { get; set; }

  public virtual TBLImages TBLImages { get; set; } 
}

[Table("TBLImages")]
public class TBLImages : AuditedAggregateRoot<Guid>
{
  public TBLImages()
  {
    TBLBanners = new HashSet<TBLBanner>();
  }
  public virtual ICollection<TBLBanner> TBLBanners { get; set; }
}

```

**Comment by ugurozturk** [comment]
Perhaps lazyloading is disabled ?

**Comment by ugurozturk** [comment]
Well even tried in modelbuilder
```
modelBuilder.Entity<TBLBanner>().HasOne(a => a.TBLImages).WithMany(b => b.TBLBanners).HasForeignKey(c => c.TBLImagesId);
modelBuilder.Entity<TBLImages>().HasMany(a => a.TBLBanners).WithOne(b => b.TBLImages);
```

**Comment by hitaspdotnet** [comment]
[ABP.io](https://abp.io/documents/abp/latest/Entities#aggregateroot-class)
An aggregate root can be referenced by it's Id. Do not reference it by it's navigation property.

**Comment by hikalkan** [comment]
Lazy loading is disabled in EF Core by default (not related to ABP). Refer to Microsoft's documentation to enable it.

> An aggregate root can be referenced by it's Id. Do not reference it by it's navigation property.

Yes, as a best practice.

**Comment by ugurozturk** [comment]
@hikalkan actually i did enable lazy loading, yet i couldn't add-migration. Because DbContext of EntityChange gave error. It says it needs "virtual".

**Comment by ugurozturk** [comment]
i figure out. Thanks
