### ISSUE TITLE
Problem creating a new modules using the "abp add-module Acme.BookStore.Books --new --add-to-solution-file"

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#6564]
* Your **ABP Framework version** - 4.0.0

* Your **User Interface** type (Angular/MVC/React... etc.) - Blazor

* Exception message and **stack trace** if available (check the logs).

* Steps needed to **reproduce** the problem.
- Create a standard web application template using `abp new Acme.BookStore -u blazor -csf`
- Navigate to Acme.BookStore\aspnet-core
- Run the command `abp add-module Acme.BookStore.Books--new --add-to-solution-file`
- Open Solution and try and build the solution and you will see all sorts of errors for example 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Acme' does not exist in the namespace 'Acme.BookStore.Books' (are you missing an assembly reference?)	Acme.BookStore.Domain.Shared	C:\Amazing\Projects\4-0-0\Acme.BookStore\aspnet-core\src\Acme.BookStore.Domain.Shared\BookStoreDomainSharedModule.cs	15	Active

is `YourCompany.Product.ModuleName` no longer allowed?

Trying to make quick-win for LearnAbpFramework.com to show developers how to use this command!

Please help!

Vineet
LearnABPFramework.com

**Comment by yekalkan** [comment]
Hi,

this is resolved by https://github.com/abpframework/abp/commit/452949e879b7098b0123ea4a27f8e925590e2179

Waiting for v4.0.1
