### ISSUE TITLE
The CurrentUser.Name is null ,How do I set it?

### ISSUE THREAD

**Issue by hexianggui** [abpframework/abp#6571]
I get 'CurrentUser' through AbpApplicationConfigurationService,but the 'CurrentUser.Name' is null 
result:
```
......
currentUser:{
email: "bst101370@mobest.com"
emailVerified: false
id: "75451fe0-0b4c-4b4a-9e23-081f65657126"
isAuthenticated: true
name: null
phoneNumber: null
phoneNumberVerified: false
roles: ["admin"]
surName: null
tenantId: null
userName: "101370"
}
......
```
How do I set it?Can you help me

**Comment by xyfy** [comment]
the table `abpuser` has fields named  `name`、`surName`

**Comment by hexianggui** [comment]
> the table abpuser has fields named name、surName

Yes,The 'name' has a value in the database,But by 'AbpApplicationConfiguration' API access to an empty value

**Comment by xyfy** [comment]
https://docs.abp.io/en/abp/latest/CurrentUser

add claims to may help you ~

 #4388

**Comment by xyfy** [comment]
![Dingtalk_20201219143137](https://user-images.githubusercontent.com/7838147/102682774-01f57580-4207-11eb-8c89-8c7b2bf6e06f.jpg)
check that, the claims map you added

**Comment by laosandegudai** [comment]
yes ,i met the same problem.I dont find it in  the service and api.
i custom `IAuditPropertySetter`  and add  `Creator`,but i found  ` CurrentUser.Name` is null.
![image](https://user-images.githubusercontent.com/17979159/104335615-80a3b100-552e-11eb-88ec-4c68c7c54305.png)

**Comment by mtozlu** [comment]
Check that name and surname scopes are added to IdentityServerApiResources table in database.
If they don't exist under UserClaims of an ApiResource, you can add these claims to seed class and seed your db.
Go to `CreateApiResourcesAsync` method of Identity server data seed class. Add these;
```csharp
private async Task CreateApiResourcesAsync()
{
	var commonApiUserClaims = new[]
	{
		AbpClaimTypes.UserName,
		AbpClaimTypes.Name,
		AbpClaimTypes.SurName,
		AbpClaimTypes.Email,
		AbpClaimTypes.EmailVerified,
		AbpClaimTypes.PhoneNumber,
		AbpClaimTypes.PhoneNumberVerified,
		AbpClaimTypes.Role,
...
```

**Comment by hexianggui** [comment]
@mtozlu Yes, you are right!Thank you very much!
![2021-02-26_085010](https://user-images.githubusercontent.com/30622318/109239205-e5ca1200-780f-11eb-99fb-0e520e42e5c9.png)

```
   private async Task CreateApiResourcesAsync()
        {
            var commonApiUserClaims = new[]
            {
                "email",
                "email_verified",
                "name",
                "phone_number",
                "phone_number_verified",
                "role",
                AbpClaimTypes.Name,
                AbpClaimTypes.SurName
            ..........
```
Add the code above,  I found 2 more rows of data in db table [IdentityServerApiResourceClaims].
![2021-02-26_084901](https://user-images.githubusercontent.com/30622318/109239227-f1b5d400-780f-11eb-8fc0-cf7780e8143f.png)
If not, use SQL to add data
```
  INSERT INTO [dbo].[IdentityServerApiResourceClaims] 
  SELECT 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname', ApiResourceId FROM [dbo].[IdentityServerApiResourceClaims]
  GROUP BY ApiResourceId
  UNION 
  SELECT 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname', ApiResourceId FROM [dbo].[IdentityServerApiResourceClaims]
  GROUP BY ApiResourceId
```
