### ISSUE TITLE
Blazor tenant management creates tenant even if new admin user validation fails

### ISSUE THREAD

**Issue by Xeevis** [abpframework/abp#6576]
ABP 4.0.0, Blazor template

![tenantissue](https://user-images.githubusercontent.com/5835044/101780355-bf40e880-3af6-11eb-9408-2664496d4d86.gif)

**Comment by maliming** [comment]
Unable to reproduce.

**Comment by Xeevis** [comment]
Here are the exact repro steps:
**Windows 10 20H2** & **.NET 5.0.1** & **Edge (Chromium)**

Setup server & client (PowerShell 7 one-liner):
```powershell
abp new Acme.SocksStore -u blazor -d mongodb -o Acme.SocksStore -v 4.0.0 --no-random-port &&
cd Acme.SocksStore\aspnet-core\src\Acme.SocksStore.DbMigrator && 
dotnet run &&
Start-Process -FilePath "dotnet" -ArgumentList "run" -WorkingDirectory "../Acme.SocksStore.HttpApi.Host" &&
Start-Sleep -Seconds 10 &&
Start-Process -FilePath "dotnet" -ArgumentList "run" -WorkingDirectory "../Acme.SocksStore.Blazor" &&
Start-Sleep -Seconds 5 &&
Start-Process -FilePath "https://localhost:44307/tenant-management/tenants"
```

1. Login with `admin` & `1q2w3E*`
2. Attempt to create new tenant with short admin password > Ok > Cancel
> New tenant is created without admin user and without update to the page state.
3. Reload page (CTRL + R) or check database

**Comment by maliming** [comment]
> MongoDB supports multi-document transactions starting from the version 4.0 and the ABP Framework supports it. However, the startup template disables transactions by default. If your MongoDB server supports transactions, you can enable the it in the YourProjectMongoDbModule class:

https://docs.abp.io/en/abp/latest/MongoDB#transactions

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.MongoDB/MongoDb/MyProjectNameMongoDbModule.cs#L37

**Comment by Xeevis** [comment]
Lesson learned not to use transactionless standalone MongoDB even for development. To solve this had to convert MongoDB to rudimentary 1-node replica set. Steps are as follow:

1. Edit _C:\Program Files\MongoDB\Server\4.4\bin\mongod.cfg_ as administrator and replace
```yaml
#replication:
```
with
```yaml
replication:
   oplogSizeMB: 128
   replSetName: rs0
   enableMajorityReadConcern: true
```
2.   Restart the MongoDB service 
```powershell
net stop mongodb && net start mongodb
```
3. Run `mongo.exe` shell and type command
```bash
rs.initiate()
```
4. Enable transactions for MongoDB module by changing the behavior from `Disabled` to `Auto`
```csharp
Configure<AbpUnitOfWorkDefaultOptions>(options =>
{
    options.TransactionBehavior = UnitOfWorkTransactionBehavior.Auto;
});
```

Hope someone finds this information useful.
