### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#6577]
Hello,

As a juggestion, it would be better to add "related links" to some documentation section.
sometimes we open issues because we are locking to the wrong section, knowing that the answer already exists at the documentation level.

For Example :

https://docs.abp.io/en/abp/latest/Startup-Templates/Application#default-structure
could be related to : 
https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients
and vis versa.

Best Regards

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Startup-Templates/Application#httpapi-client-project

![image](https://user-images.githubusercontent.com/6908465/101852015-ab998e80-3b97-11eb-82b9-8279be06a071.png)

**Comment by aelhadi** [comment]
I m talking about adding section 
Related articles, at the bottom like microsoft do....
