### ISSUE TITLE
EfCoreRepository has inconsistent behavior of IGuidGenerator

### ISSUE THREAD

**Issue by hubo0831** [abpframework/abp#6586]
![image](https://user-images.githubusercontent.com/10137315/101874495-f03b1f00-3bc3-11eb-9548-b6a1783a9525.png)
it is a bug?

**Comment by maliming** [comment]
Can you explain in detail?

**Comment by hubo0831** [comment]
AbpDbContext has ‘public IGuidGenerator GuidGenerator ’, it is property injected;
ApplicationService has ‘public IGuidGenerator GuidGenerator ’, it is property injected too;
Entity'Id value come from  AbpDbContext, EfCoreRepository,ApplicationService, but EfCoreRepository has inconsistent behavior.
