### ISSUE TITLE
The IApplicationService has been implemented but is not registered with the container

### ISSUE THREAD

**Issue by cwwcwwcww** [abpframework/abp#6598]
* Your **ABP Framework version**:4.0
* Exception message and **stack trace** if available (check the logs):
Autofac.Core.Registration.ComponentNotRegisteredException:“The requested service 'Acme.BookStore.Books.BookAppService' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.”
* Steps needed to **reproduce** the problem.：Create a new service and implement it from IApplicationService. If you inherit from ApplicationService, there is no problem

**Comment by maliming** [comment]
You need to implement the `ITransientDependency` on `BookAppService`.

**Comment by cwwcwwcww** [comment]
> 您需要实现`ITransientDependency`on `BookAppService`。

But the documentation tells me that I can implement IApplicationService as well. My BookAppService implements iBookAppService, which inherits from IApplicationService

**Comment by TheUnknowName** [comment]
the new document content: Application services (inherit ApplicationService class or its subclasses) are registered as transient.
So, wo dotn't use the IApplicationService go to auto register. 
Why ApplicationService can do, because it implement the ITransitionDenpendency interface.

**Comment by TheUnknowName** [comment]
At begining of I'm reading the chinese docuemtn, the content is "应用程序服务（实现IApplicationService接口或继承ApplicationService类）注册为transient.",,,but the description is error.
