### ISSUE TITLE
Permission modal should show User name instead of User Id

### ISSUE THREAD

**Issue by ilkayilknur** [abpframework/abp#6603]
![image](https://user-images.githubusercontent.com/5785927/101911953-27b0c800-3bd2-11eb-98e5-8fd24cd5a477.png)

**Comment by hikalkan** [comment]
I think you mean "user id", not "role id". This is user management page.
This is not a bug. It is currently implemented like that.
However, I think we can send the username (actually, displayname for the related entity) while opening the dialog. The modal can take display name (it is username in this case) to show on the title. Currently, it only gets the entity id (userid in this case) and shows it. It is same for MVC.
