### ISSUE TITLE
Customize ICrudAllAppService cannot generate the JS API script

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#6606]
APB Framework version: 3.3.2

I created my "ICrudAllAppService" interface inherits from the "ICrudAppService", the codes just as bleow:
```
public interface ICrudAllAppService<TEntityDto, in TKey, in TGetListInput, in TCreateInput, in TUpdateInput>
        : ICrudAppService<TEntityDto, TKey, TGetListInput, TCreateInput, TUpdateInput>, IApplicationService
    {
        Task<IEnumerable<TEntityDto>> GetAllObjectsAsync();
    }
```
And added the "CrudAllAppService" to implement.
```
 public class CrudAllAppService<TEntity, TEntityDto, TKey, TGetListInput, TCreateInput, TUpdateInput>
        : CrudAppService<TEntity, TEntityDto, TKey, TGetListInput, TCreateInput, TUpdateInput>,
        ICrudAllAppService<TEntityDto, TKey, TGetListInput, TCreateInput, TUpdateInput>
        where TEntity : class, IEntity<TKey>
        where TEntityDto : IEntityDto<TKey>
    {
        public CrudAllAppService(IRepository<TEntity, TKey> repository)
            : base(repository)
        {
        }

        public async Task<IEnumerable<TEntityDto>> GetAllObjectsAsync()
        {
            var entityList = await this.Repository.GetListAsync();
            return entityList.Select(a => MapToGetListOutputDto(a)).ToList();
        }
    }
```

At the business level, I create the services which inherit the "ICrudAllAppService" and run the application.
At the frontend, the JS throws the error message and indicates the JS object not generated, if I change to ICrudAppService, it works fine again.
But it works fine in the ABP 3.0.5 version. I guess the ICrudAppService changed some logic or the JS API object generate logic changed.
But not sure the root cause.

Anyone can help me? Thanks so much.
It's very easy to reproduce, just copy my codes in your project and inherit it. Run the application, the issue will be reproduced.

**Comment by jack-gaojz** [comment]
Anyone can help take a look at this issue？ Thanks so much.

**Comment by realLiangshiwei** [comment]
Hi,

Make your `CrudAllAppService` class `abstract`

**Comment by jack-gaojz** [comment]
> Hi,
> 
> Make your `CrudAllAppService` class `abstract`

Thanks so much, it works fine for me now. This restriction may be added to the document as well. Thanks so much again. :)
