### ISSUE TITLE
Is ABP CLI is down?

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#6610]
* Your **ABP Framework version** - 4.0.0.
* Your **User Interface** - All
* Exception message and **stack trace** if available (check the logs).

```
C:\Amazing\LearnABPFramework.com\Projects\4-0-0\Blazor>abp new Acme.BookStore -u blazor -csf
[14:56:51 INF] ABP CLI (https://abp.io)
[14:56:51 INF] Version 4.0.0 (Stable)
[14:56:52 INF] Creating your project...
[14:56:52 INF] Project name: Acme.BookStore
[14:56:52 INF] UI Framework: Blazor
[14:56:52 INF] Output folder: C:\Amazing\LearnABPFramework.com\Projects\4-0-0\Blazor\Acme.BookStore
Error occured while getting the latest version from https://abp.io/api/download/template/get-version/ : '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[14:58:33 WRN] The remote service is currently unavailable, please specify the version.
[14:58:33 WRN]
[14:58:33 WRN] Find the following template in your cache directory:
[14:58:33 WRN]  Template Name   Version
[14:58:33 WRN]
[14:58:33 WRN] Use command: abp new Acme.BookStore -v version

C:\Amazing\LearnABPFramework.com\Projects\4-0-0\Blazor>
```

* Steps needed to **reproduce** the problem.
1. install ABP CLI "dotnet tool install -g Volo.Abp.Cli"
2. run command "abp new Acme.BookStore -u blazor -csf "

I think the ABP CLI is down and is not able to connect to  https://abp.io/api/download/template/get-version/

**Comment by wlsoftware** [comment]
I also faced this problem

**Comment by ThreeLambs** [comment]
use local resource 
**abp new demo -u mvc --local-framework-ref --abp-path E:\abp-4.0.0**

**Comment by vnetonline** [comment]
I am trying to record the Blazor video for LearnABPFramework.com and can't progress because the CLI is down 

![image](https://user-images.githubusercontent.com/15242923/101976894-d1a95680-3c9d-11eb-93d6-845d71ff33d8.png)

Even clicking on the get started on the main homepage doesn't work

**Comment by vnetonline** [comment]
> abp new demo -u mvc --local-framework-ref --abp-path E:\abp-4.0.0

that doesn't work you must have a E drive where you have previously downloaded the mvc template locally available

**Comment by wlsoftware** [comment]
use local resource, it doesn‘t work, another error occurs , not able to connect to https://abp.io/api/download/template/

**Comment by wlsoftware** [comment]
I think the api is down , https://abp.io/api/

**Comment by wlsoftware** [comment]
https://aspnetboilerplate.com/Templates

**Comment by vnetonline** [comment]
Yes looks like abp.io api is down 

![image](https://user-images.githubusercontent.com/15242923/101978301-ed195f00-3ca7-11eb-930b-94df80022e96.png)

**Comment by vnetonline** [comment]
okay seems to be working now 

![image](https://user-images.githubusercontent.com/15242923/101979600-80f02880-3cb2-11eb-83cf-322c371882f4.png)

**Comment by maliming** [comment]
It works now.
