### ISSUE TITLE
AngularUI: Single Sign On (SSO)

### ISSUE THREAD

**Issue by TuyenDinh1205** [abpframework/abp#6611]
ABP Framework version: v3.3.0
UI type: Angular
Tiered (MVC) or Identity Server Seperated (Angular): yes
Hi All
I have seperate module with differrent link and i want to use single sign on to login. I used angular-oauth2-oidc and call function loadDiscoveryDocumentAndLogin to skip the Login Form but it return to error page like This
![error](https://user-images.githubusercontent.com/34994601/101975872-8cbbfa80-3c72-11eb-80f4-28c8ba3ec681.PNG)
Please help me how to solve it

**Comment by maliming** [comment]
hi

Please create a question on https://support.abp.io/ and share the application log. Thanks.

![image](https://user-images.githubusercontent.com/6908465/102001608-f699da00-3d2e-11eb-9bc6-7c2f7fc906e3.png)
