### ISSUE TITLE
ABP Community -  Comment Error

### ISSUE THREAD

**Issue by atak946** [abpframework/abp#6613]
Hi,

I get such an error while trying to post a comment because I don't know where to forward this situation, I wrote it here.

My goal is to support you to improve.

good work.

[Image with lightshot](https://prnt.sc/w14vfs)

**Comment by realLiangshiwei** [comment]
Thanks for your reporting. We will fix it.

**Comment by atak946** [comment]
your wellcome, 
good work.

**Comment by EngincanV** [comment]
It's fixed: #6557
