### ISSUE TITLE
Add BulkWrite to MongoDbRepository

### ISSUE THREAD

**Issue by ChEhrhard** [abpframework/abp#6614]
It could be useful to fully implement the **Collection.Bulkwrite()** fonction from Mongo Client in yout MongoDbRepository.

This can be much faster than a loop of Update or Insert. In addition the **IsUpsert** option avoid the need of specificaly call Update or Insert.

[Link to officiel doc](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/) .

**Comment by maliming** [comment]
You can implement it in a custom repository method. : )

**Comment by ChEhrhard** [comment]
That's what i've done . 

However, it means reusing all the logic you've implemented in your Insert and Update functions ( ID check, audits, events, etc ... ) . I can of course reproduce your logic but i have to take care about all coming evolutions to stay as compliant and integrated as possible to your repository logic.

**Comment by hikalkan** [comment]
Thanks @ChEhrhard for your suggestion. We will consider to add it.

**Comment by enisn** [comment]
Planned and scheduled, can be followed at issue #6654
