### ISSUE TITLE
RegularExpression validation is incorrectly performed on client side (javascript)

### ISSUE THREAD

**Issue by trgiangvp3** [abpframework/abp#6634]
I create a Modal to create an entity which contains IP field and then use `System.ComponentModel.DataAnnotations.RegularExpression` to decorate the IP field in my Dto.
This works well if I call the service from RESTApi but it's always fail when I try to create new record from Create Modal.

I found the reason is Regex format in C# and javascript is different, but when generate HTML script for the `CreateModal`, ABP framework leave the RegularExpression as it is for C# and this regular expression is then processed at client side by the javascript (maybe jQuery validation).
The screen shot at `Step 3` below will clarify what I said.

**1. ABP Framework version**
> 3.3.1 (Stable)

**2. User Interface:**
> MVC

**3. Exception message (as showing at the bottom of input field)**
>       The field LocalIP does not match the requested format.
>   
>  ![image](https://user-images.githubusercontent.com/48433917/102075964-99d71600-3e39-11eb-804b-f6f2b8b6709c.png)

**4. Steps needed to reproduce the problem**

4.1. Create the CreateUpdateEntityDto like below
```csharp
    public class CreateUpdateEntityDto 
    {
        [Required]
        [StringLength(15)]
        [RegularExpression("\\A(?:((?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))(?:\\.|\\b)){4}\\z")]
        public string LocalIP { get; set; }

        [Required]
        [StringLength(15)]
        [RegularExpression("\\A(?:((?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))(?:\\.|\\b)){4}\\z")]
        public string PublicIP { get; set; }
    }
```

4.2. Create `CreateModal` as per this tutorial https://docs.abp.io/en/abp/3.1/Tutorials/Part-3?UI=MVC&DB=EF
4.3. Try to open CreateModal and create a new record

**Comment by maliming** [comment]
hi

I think this is the behavior of asp net core.
https://github.com/dotnet/runtime/issues/31445#issuecomment-554089026

**Comment by trgiangvp3** [comment]
> hi
> 
> I think this is the behavior of asp net core.
> [dotnet/runtime#31445 (comment)](https://github.com/dotnet/runtime/issues/31445#issuecomment-554089026)

Thank you. I see it now.
I'll close this issue.
