### ISSUE TITLE
Abp TagHelper support string value for "asp-for"

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#6640]
Is there any way to use `asp-for` in loops?
```csharp
@foreach (var item in Model.Items)
{
    var multiple = item.IsMultiple ? "multiple" : "";
    var name = "Item." + item.Name;
    var apiUrl = "/api/app/item-groups/by-type?itemTypeId=" + item.Id;
    <abp-select asp-for=@name
                autocomplete-api-url=@apiUrl
                autocomplete-filter-param-name="filterText"
                autocomplete-display-property-name="id"
                autocomplete-value-property-name="id"
                autocomplete-items-property-name="items"
                multiple=@multiple>
    </abp-select>
}
```
[stackoverflow](https://stackoverflow.com/questions/34282640/how-can-i-pass-string-value-for-asp-for-in-asp-net-5)

**Comment by hikalkan** [comment]
I suppose you need to create for loop (instead of foreach) and write `asp-for="Model.Items[i]"`. However, this is not related to the ABP Framework. `asp-for` is a standard attribute of ASP.NET Core.

**Comment by hitaspdotnet** [comment]
@hikalkan This is a suggestion and is useful with Abp Dynamic Forms where we have to design the forms from the UI. I'm looking for a way to resolve it.
However thanks for reply.
