### ISSUE TITLE
Tenant is null and header has error on parse

### ISSUE THREAD

**Issue by begandroide** [abpframework/abp#6653]
Hi! im reporting a problem with upgrading **abp from 3.0 to 4.0** (specifically with httpheaders and ___tenant null)

**Environment:**

* **ABP 4.0.0.**
* Angular 11
* Console error: `main.ts:13 TypeError: Cannot read property 'length' of null` (httpHeaders.applyUpdate)
* Steps to reproduce: Recently I upgraded abp from 3.0 to 4.0.

Im working with angular, abp 4.0 and .net core 5 (without reverse proxy, only ng serve of Angular Live Development Server), and the request's are with problems at parse headers:

![image](https://user-images.githubusercontent.com/22018004/102215968-37bdf580-3eb9-11eb-85c7-6d372108193c.png)

I has read on [https://docs.abp.io/en/abp/latest/Multi-Tenancy](https://docs.abp.io/en/abp/latest/Multi-Tenancy) and i noted that has a disclaimer for nginx and underscores on headers, but i dont use nginx, only angular live development server.

I supossed that is a only frontend error because i remember that the tenant in the versión 3.0 is nullable in header at initialice, and this not causes problems.

Regards, and thanks for abp framework ❤️

**Comment by realLiangshiwei** [comment]
Thanks for your reporting. we have fixed the problem: https://github.com/abpframework/abp/pull/6644

**Comment by begandroide** [comment]
@realLiangshiwei thanks you! this was so quickly, waiting for v4.1.

**Comment by davidzwa** [comment]
https://support.abp.io/QA/Questions/678#answer-0c965758-2a20-a382-8274-39f9778d361f

Fix in `package.json` and `yarn.lock` provided in this support ticket:
```
  "resolutions": {
    "@abp/ng.core": "4.0.0"
  }
```
or download version `"@abp/ng.core": "^4.1.0-rc.1"` which is available as we speak.
https://www.npmjs.com/package/@abp/ng.core

**Comment by begandroide** [comment]
@davidzwa thank you! i was stucked with this issue and i need upgrade my packages...
