### ISSUE TITLE
Environment in DbMigrator

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#6656]
I want my `DbMigrator` app to not seeding some (not all) datas in Production environment.
I tried the following with no luck:
  - [**Preferred way**] Add `appsettings.{env}.json` files and running `DbMigrator` with `dotnet run --environment "myEnv"`: even if `Host` class seems to load `appsettings.{env}.json`, if I inject `IConfiguration` inside `IDataSeedContributor` implementation, it says that it used as provider: `appsettings.json` and environment variables. `appsettings.{env}.json` mysteriously disappeared.
  - Injecting `IHostingEnvironment` in `IDataSeedContributor` implementation: IoC says nope.
  - Calling `Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")`: works but ugly. Not an option, because hardcoded.
  - `DataSeedContext.WithProperty` like pointed by @maliming [here](https://github.com/abpframework/abp/issues/3597#issuecomment-613308376): I don't see the point. My injection problems would be the same in the caller: DbMigrationService. No?

I am on ABP 4.0.0.

**Comment by davidzwa** [comment]
Do make sure to add DOTNET_ENVIRONMENT environment variable or launchSetting env variable for console applications like a `.DbMigrator` console runner.
I'm not sure from your description if you did this, also because you mentioned `ASPNETCORE_ENVIRONMENT`.

This would not be related to ABP but to .NET Console Host configuration vs ASP.NET configuration.
Read this below for more info on Host vs Web template projects:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#default-host-configuration

Also note:
- `IHostingEnvironment` is ASP.NET only and is deprecated over `IWebHostEnvironment` in ASP.NET
- `IHostEnvironment` exists for Host/Console apps which explains the deprecation of `IHostingEnvironment`, to avoid naming confusion.

Concluding: set DOTNET_ENVIRONMENT and use IHostEnvironment instead.

**Comment by Stirda** [comment]
Very interesting. Thanks @davidzwa 

But I wonder: if I have to inject `IHostEnvironment` in implementation of `IDataSeedContributor` when my implementation of `IDataSeedContributor` is called from `DbMigrator`, but `IWebHostEnvironment` when it is from my web app (since seeders can also be called from application service for example), how to do? 

This is why I ask here an ABP design to handle this. It would be great to have `IConfiguration` injectable in any implementation of `IDataSeedContributor`, with `IConfiguration` being a concatenation of all `appsettings*.json` involved, no matter it comes from `DbMigrator` or web app. Or, at least, knowing environment name.

**Comment by davidzwa** [comment]
I realise `IHostEnvironment` doesnt resolve in the scope of `AbpApplicationFactory.Create(options=>...){...}`. That needs to be fixed and then the problem goes away. I also added 2 other options which dont fix the problem but avoid it.

### Best option - re-register IHostEnvironment
The best option without drawbacks is to re-register the IHostEnvironment within the AbpApplicationFactory's scope by injecting `IHostEnvironment` in the `DbMigratorService`. Use the options action after that: `options.Services.AddSingleton<IHostEnvironment>(hostEnvironment)`.
The resulting hosted service then looks like:
```  
public class DbMigratorHostedService : IHostedService
{
        private readonly IHostApplicationLifetime _hostApplicationLifetime;
        private readonly IHostEnvironment hostEnvironment;

        public DbMigratorHostedService(
            IHostApplicationLifetime hostApplicationLifetime,
            IHostEnvironment hostEnvironment
        )
        {
            _hostApplicationLifetime = hostApplicationLifetime;
            this.hostEnvironment = hostEnvironment;
        }
        public async Task StartAsync(CancellationToken cancellationToken)
        {
            using (var application = AbpApplicationFactory.Create<DbMigratorModule>(options =>
            {
                options.UseAutofac();
                options.Services.AddSingleton<IHostEnvironment>(hostEnvironment);
                options.Services.AddLogging(c => c.AddSerilog());
            }))
            {
                application.Initialize();

                // Test that the service does resolve (!= null)
                var service = application.Services.GetRequiredServiceLazy<IHostEnvironment>().Value;

                await application
                    .ServiceProvider
                    .GetRequiredService<TeamsiteDbMigrationService>()
                    .MigrateAndSeedAsync();

                application.Shutdown();

                _hostApplicationLifetime.StopApplication();
            }
        }

        public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
    }
```

### Option - use Environment static with its global methods
I would suggest `Environment` is the best option here by using `Environment.IsDevelopment()`, `Environment.IsProduction` or your own extension methods to simplify common environments. This could be satisfactory for your problem in DbMigrator called DataSeedContributors as well as any DataSeedContributor as it does not depend on DI, but it will correctly pick up the environment.

### Option - ignore IHostEnvironment is null
I realize I had this problem during the summer (ABP v3): I went for the following to add nullability on IHostEnvironment. Not the best DI practice, but avoids some issues.

```
public class ApplicationDataSeedContributor
        : IDataSeedContributor, ITransientDependency
    {
        // ...
        private readonly IHostEnvironment _hostEnvironment;
        // ...

        public ApplicationDataSeedContributor(
            // ...
            IServiceProvider services,
        )
        {
            // ...
            this._hostEnvironment = services.GetService<IHostEnvironment>();
            // ...
        }    
```

I dont agree that this should go through `IConfiguration` as there is already `Environment` and `IHostEnvironment`. Using `IConfiguration` is not meant for environment except for any additive configuration variables, which is not `ASPNETCORE_ENVIRONMENT` nor `DOTNET_ENVIRONMENT`.

**Comment by NecatiMeral** [comment]
Why don't just enhance the `IConfiguration` setup by handling the environment variables?
In this case, you won't need to implement more logic just for parsing your configuration but use the regular `IConfuguration` framework instead.

**Comment by davidzwa** [comment]
Because an existing mechanism exists which makes it compatible with existing code.

**Comment by Stirda** [comment]
I got a working solution, thanks to @davidzwa :

Added a `Properties\launchSettings.json` in my `DbMigrator` project to define the environment during development

```json
{
  "profiles": {
    "DbMigrator": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
}
```

Next changed the start of `DbMigratorHostedService.StartAsync` with the following to register `IHostEnvironment` and be informed of the good environment detection:

```cs
public async Task StartAsync(CancellationToken cancellationToken)
{
    using (var application = AbpApplicationFactory
        .Create<AppPickingDbMigratorModule>(options =>
    {
        options.UseAutofac();
        options.Services.AddSingleton(_hostEnvironment);
        options.Services.AddLogging(c => c.AddSerilog());
    }))
    {
        application.Initialize();

        Log.Information(
            "Host environment: {0}",
            _hostEnvironment.EnvironmentName);
```

Finally started my `MyBusinessFakeDataSeedContributor.SeedAsync` with:

```cs
public async Task SeedAsync(DataSeedContext context)
{
    const string production = "Production";
    
    if (_hostEnvironment.EnvironmentName == null)
    {
        _logger.LogWarning("DOTNET_ENVIRONMENT environment variable not defined.");
        _logger.LogWarning("Production environment inferred.");
        _hostEnvironment.EnvironmentName = production;
    }
    if (_hostEnvironment.EnvironmentName == production)
    {
        _logger.LogInformation("Fake data seeding disabled in production.");
        return;
    }

    _logger.LogInformation("Seeding fake data...");
```

I can even force environment on my dev machine by running:

```cmd
set DOTNET_ENVIRONMENT=Production
dotnet run --no-launch-profile
```

Here is an example of an execution of my dev machine ("Seeding de données factices désactivé en production." is my french translation of "Fake data seeding disabled in production."):

![image](https://user-images.githubusercontent.com/32323613/103898728-aa577500-50f5-11eb-9755-1516eca133b9.png)

In my Azure DevOps Release Pipeline, I set `DOTNET_ENVIRONMENT` in my Powershell task which runs DbMigrator. This products the following result (here I set `Test` as `DOTNET_ENVIRONMENT`):

![image](https://user-images.githubusercontent.com/32323613/103898810-cbb86100-50f5-11eb-9a5e-459826bee193.png)

@hikalkan What do you think? Is this the good approach?

**Comment by Stirda** [comment]
Note that I suppose that my solution would fail if my seed contributor is ran on `HttpApi.Host`. Maybe a `_hostEnvironment ?? _hostingEnvironment` would do the job?

**Comment by davidzwa** [comment]
I encourage you to **avoid defining hardcoded "Production" and "Development" environment strings** etc.
Use static extensions to extend the already existing methods IsProduction(), IsDevelopment() like f.e. IsTest().

Also, why would it fail? `IHostEnvironment` is correctly available for Dependency Injection in any correctly registered service/controller/singleton/transient... both in a Web/API and console host. It's just the slightly unequipped AbpApplicationFactory which needs it to be re-injected, as you confirmed.
`IWebHostEnvironment` is not always available on the contrary, which I explained before.

Let me give you what I think is best way to make stuff generic (also for Docker environments). See how I added Test and CI, without redefining Production, Development etc (in our case we have many different Development, Stag
```
    public static class EnvironmentExtension
    {
        const string TestEnvironment = "Test";
        const string CIEnvironment = "CI";

        public static bool IsDockerEnvironment()
        {
            return Environment.GetEnvironmentVariable("DOTNET_RUNNING_IN_CONTAINER") == "true";
        }

        public static bool IsDevelopmentOverall(this IHostEnvironment env)
        {
            return env.IsDevelopment(); // Add custom environments if you so require
        }

        public static bool IsProductionOverall(this IHostEnvironment env)
        {
            return env.IsProduction(); // Add custom environments if you so require
        }

        // The name staging is the same as the build Configuration.
        // Decided to fallback to 'Test' so we have clear distinction between build Configuration and runtime Environment.
        public static bool IsTest(this IHostEnvironment env)
        {
            return env.IsEnvironment(TestEnvironment);
        }

        public static bool IsCI(this IHostEnvironment env)
        {
            return env.IsEnvironment(CIEnvironment);
        }
    }
```

You see? Very little code, very effective. Just make sure to place it in the right namespace or project.

**Comment by davidzwa** [comment]
@Stirda please close if resolved.
