### ISSUE TITLE
Angular - disabling oAuth2/oidc still attempts loading well-known openid-document

### ISSUE THREAD

**Issue by davidzwa** [abpframework/abp#6658]
* Your **ABP Framework version** 
3.x/4.x
* Your **User Interface** 
Angular
* Exception message and **stack trace** if available (check the logs).
`issuer  must use HTTPS (with TLS), or config value…t be set to 'false' and allow HTTP (without TLS).`
angular oauth2 tries to load the well-known document, but for this project oidc authentication is not used (we work with plain old JWT's).

* Steps needed to **reproduce** the problem.
Run Angular with `environment.ts` being partially:
```
...
oAuthConfig: {
    oidc: false
},
...
```

Instead of the Rest service error mentioned above, we'd expect no attempt to load the document at all as in this case we state we are not using OpenID authentication.

**Comment by davidzwa** [comment]
My proposal: 
Either - add a separate setting to determine whether oAuth is used or not. 

Or - allow leaving out oAuthConfig:
I cannot leave out `oAuthConfig` as undefined because then the whole app doesnt start (`Cannot read property 'responseType' of undefined` in abp/ng.core)

**Comment by tsupakit** [comment]
I got "error loading discovery document TypeError: Cannot read property 'length' of null" in angular-oauth2-oidc.js:1330 
I did create new angular template freshly.
Run aspnet-core migrator project, start swagger and yarn start the angular

cli version 4.0.1

**Comment by lykiao** [comment]
@tsupakit abp+angular, the same version, the same issue, 3 js errors when login, can anyone give same advice?
![image](https://user-images.githubusercontent.com/54703532/102476471-182ff400-4096-11eb-9de6-7c487319426e.png)

**Comment by maliming** [comment]
@tsupakit  @lykiao https://github.com/abpframework/abp/issues/6657

**Comment by lykiao** [comment]
@maliming thank you very much! resolved in your way.
by the way, i used this way below but the issue is still exist. you saved my time~
https://support.abp.io/QA/Questions/684/Angular-SSO-issue

**Comment by davidzwa** [comment]
Back to the original issue: disabling oAuth within or without `oAuthConfig`.

ID4 or OpenID authentication are optional, so angular-oAuth firing off should be as well.

**Comment by maliming** [comment]
@lykiao  Please follow https://support.abp.io/QA/Questions/684/Angular-SSO-issue

**Comment by lykiao** [comment]
@maliming yesterday maybe forgot to clear the localStorage finally, now it was ok, thank you for your kindly response~

**Comment by davidzwa** [comment]
@maliming I am eager to hear whether disabling oAuth with a boolean flag is something you're willing to add. It is 99% impossible for me to do this right now (I even tried recreating my own CoreModule, but that gave import path errors).

Should not be very hard I belief, if oAuth is kept on by default so it is not a breaking change.

Justification: our application is not ready for oAuth or IDS4, so we're really suppressing the RestService error now.

**Comment by mehmet-erim** [comment]
Hello @davidzwa 

The `@abp/ng.core` is dependent on the `angular-ouath2-oidc` package and the core use many methods of the `OAuthService`. So it cannot be disabled with a boolean option.

But you can override the `OAuthService` by adding a provider. 
I'm explaining to you how to do this but **the solution below is totally workaround and I don't recommend it.**

You can override a service by adding a provider to the `AppModule` like this:

```ts
//app.module.ts


//...


@NgModule({
  //...
  providers: [
    //...,
    {
      provide: OAuthService,
      useValue: {
        hasValidAccessToken: () => true, // return token status
        configure: () => {},
        loadDiscoveryDocument: () => Promise.resolve(),
        tryLogin: () => {},
        setupAutomaticSilentRefresh: () => {},
        getAccessToken: () => '', // return access token
      },
    },
  ],
})
export class AppModule {}
```

...or create a custom service and use `useClass` property like below:


```ts
//app.module.ts

//...

@NgModule({
  //...
  providers: [
    //...,
    {
      provide: OAuthService,
      useClass: FakeOAuthService
    },
  ],
})
export class AppModule {}
```

**Comment by davidzwa** [comment]
Much appreciated and I fully agree that this is not recommended due to breaking changes!
In future I will work towards oAuth, just not there yet.
