### ISSUE TITLE
How can I run abpvnext application in docker?

### ISSUE THREAD

**Issue by OldKing-lion** [abpframework/abp#6661]
How can I run abpvnext application in docker?

**Comment by realLiangshiwei** [comment]
I think it has nothing to do with ABP. see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/?view=aspnetcore-5.0

**Comment by OldKing-lion** [comment]
都是中国人就不说英语了，以前用abp的时候就是要修改很多配置才能用docker,但是abpvnext没有查到相关资料，不知道和.netcore基础程序部署的方法是不是一样，我试试

**Comment by OldKing-lion** [comment]
> I think it has nothing to do with ABP. see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/?view=aspnetcore-5.0

都是中国人就不说英语了，以前用abp的时候就是要修改很多配置才能用docker,但是abpvnext没有查到相关资料，不知道和.netcore基础程序部署的方法是不是一样，我试试

**Comment by davidzwa** [comment]
Please speak in English.
