### ISSUE TITLE
how to config redis only use specific dbindex? eg.db5

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#6662]
![image](https://user-images.githubusercontent.com/1214546/102324017-33c6cc00-3fbc-11eb-8652-5f5db624660e.png)

**Comment by realLiangshiwei** [comment]
Change your connection string, like:  `127.0.0.1;defaultDatabase=5`

See https://stackexchange.github.io/StackExchange.Redis/Configuration.html#configuration-options
