### ISSUE TITLE
 angular app project was broken in v4.0.1

### ISSUE THREAD

**Issue by yinchang0626** [abpframework/abp#6664]
* Your **ABP Framework version**.
`4.0.1`
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
`angular`
* Exception message and **stack trace** if available (check the logs).

![image](https://user-images.githubusercontent.com/16490084/102329515-793ac780-3fc3-11eb-85e2-eb6019411993.png)

* Steps  to **reproduce** the problem.
1. abp new FS -t app -u angular
2. run FS.DbMigrator at  `aspnet-core`
3. run FS.HttpApi.Host at `aspnet-core`
4. run start.ps1 at angular
5. after Login admin(host) will see above error

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/6644
