### ISSUE TITLE
Blazor UI: Consider to apply bundling&minification to the startup template

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6673]

**Comment by ilkayilknur** [comment]
We need your feedback! When you create a new project using the `abp new` command, do you want to see the client-side resources individually or bundled inside the `index.html`?

**Comment by d-oit** [comment]
For isolated component css / js i prefer bundled. The component should handle all. 

I would like to override my customization in a custom.js,ts / variable.css, application.css (scss)

**Comment by Xeevis** [comment]
I may be late to the conversation, but I don't see any benefit to bundling, if anything it makes everything worse. WebAssembly's greatest performance asset is **caching**. Thanks to **HTTP/2 HTTP/3** protocols all assets are downloaded in parallel and blazor.boot.json keeps track of SHA hashes of all downloaded assets to make sure only what has changed is redownloaded on update. And this is further reinforced by linker that slims everything to bare minimum and deterministic compilation that outputs exact same DLLs when there are no changes to the given assembly code. This leads to tiny downloads when new app version is published as most of it is reused from existing cache.

Bundling mashes everything into single file and then even tiniest of changes busts large chunks of cache unnecessarily. Goal should be the opposite, divide everything into smallest pieces possible according to separation of concern.

When consuming javascript/css libraries like jQuery, Bootstrap, Alpinejs and what not, use CDNs like [JSDeliver](https://www.jsdelivr.com/) for production with fallback, CDNs are faster, bust cache automatically and if user downloaded them with other websites, another copy doesn't need to be downloaded again, further speeding up loading of our own app.
