### ISSUE TITLE
Support EF Core Owned Entity Types

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#668]
[https://github.com/abpframework/abp/blob/edbbec9294cb625968f1be9b6df3d984ad78cc5f/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/Distributed/EntityToEtoMapper.cs#L31](https://github.com/abpframework/abp/blob/edbbec9294cb625968f1be9b6df3d984ad78cc5f/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Events/Distributed/EntityToEtoMapper.cs#L31)

Because the entity has no primary key

**Comment by Nokecy** [comment]
ef core doc [https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)

**Comment by hikalkan** [comment]
It's possible to create an entity without Id. Inherit from `Entity` instead of `Entity<TKey>`.

**Comment by Nokecy** [comment]
Is a ValueObject，I implemented the IEntity interface and fixed it. Thank you！ @hikalkan
