### ISSUE TITLE
Reset password page can not switch to tenant in the querystring

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#6688]
Using MVC razor pages. 

When a user clicks the password reset link if user belongs to/uses two or more tenants he/she may get "Current tenant is different than the given tenant." 

[In the code](https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/modules/account/src/Volo.Abp.Account.Web/Pages/Account/ResetPassword.cshtml.cs#L61), there is a comment about this. 

If we implement a new AppAccountEmailer and in SendPasswordResetLinkAsync add a new querystring parameter __tenant=TenantName to URL it works. Is this a proper solution? Or is there better solutions for this?

**Comment by maliming** [comment]
> if user belongs to/uses two or more tenants

Our design does not support this situation by default.  I think there is no problem with using a unique tenant name.

**Comment by espindl** [comment]
Thank you. 
This may also be needed when you want to create a user and send them an email that is forcing them to set their passwords before logging in. Because they have never logged in, tenant should be resolved/set by the system automatically. I know this is not a very standard way but resolving tenant in this scenario would be great.
