### ISSUE TITLE
After logging in, keep turning around

### ISSUE THREAD

**Issue by sheepx258** [abpframework/abp#6689]
api test success
![image](https://user-images.githubusercontent.com/45529787/102468380-663ffa00-408c-11eb-8236-3f5f274d8a16.png)
angular test fail.(After logging in, keep turning around)
![image](https://user-images.githubusercontent.com/45529787/102468227-38f34c00-408c-11eb-8542-c055c5f85e20.png)
why!?

**Comment by maliming** [comment]
Duplicate of https://github.com/abpframework/abp/issues/6657
