### ISSUE TITLE
Can you create a small example or document that extends IdentityUser?

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#669]

**Comment by hitaspdotnet** [comment]
extend Volo.Abp.Identity module or learn [EF Core Table Per Hierarchy](https://www.learnentityframeworkcore.com/inheritance/table-per-hierarchy)

**Comment by hitaspdotnet** [comment]
Add your customs or create your new powerful identity module and use it in your app. I recommended you to view the full source code of Users module and Identity module. Then if you can't find your needs so you should develop them

**Comment by Nokecy** [comment]
thank you for your reply! @hitaspdotnet
