### ISSUE TITLE
Navigations property sometimes is plular, sometimes is singular

### ISSUE THREAD

**Issue by profitp** [abpframework/abp#6695]
ABP Framework version: 4.0.1
User Interface: MVC, ABP Suite
Database provider: EF Core

Correct URL from swagger: https://localhost:44338/api/app/entity02/entity01Lookup
Wrong URL from Navigations property request: https://localhost:44338/api/app/entity02s/entity01-lookup?maxResultCount=50

Problem: entity02 sometimes is plular, sometimes is singular

**Comment by maliming** [comment]
hi @profitp 

We are trying to fix this.

**Comment by maliming** [comment]
Fixed.
