### ISSUE TITLE
Angular Startup template same as AspNetBoilerplate (Question)

### ISSUE THREAD

**Issue by rcenamsi** [abpframework/abp#6698]
Good day dev's,

Is there a way to change the startup or basic template same aspnetboilerplate? 
The navigation is on the left part of the page.

Regards.

**Comment by realLiangshiwei** [comment]
You need to change the basic theme source code.

Or you can use the theme of the community:
 https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-mvc-ui-yt9b18io
https://github.com/realLiangshiwei/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla
https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE

**Comment by rcenamsi** [comment]
@realLiangshiwei Thanks.

**Comment by rcenamsi** [comment]
@realLiangshiwei where to change the basic theme source code for AngularUI? there is no document for it.

**Comment by realLiangshiwei** [comment]
Someone has already done this: https://github.com/yinchang0626/abp.ng

**Comment by rcenamsi** [comment]
@realLiangshiwei , Thank you. I will look into it.
