### ISSUE TITLE
Overriding logoUrl in DefaultBrandingProvider always rendring null string

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#6704]
Hello,
I'm trying  to override LogoUrl in my OrgAEBrandingProvider : DefaultBrandingProvider as bellow : 
``` CSharp
[Dependency(ReplaceServices = true)]
    public class OrgAEBrandingProvider : DefaultBrandingProvider
    {
        public override string AppName => "OrgAE Admin";
        public override string LogoUrl => "/logo.png";
    }
```
my logo file is in wwwroot folder (Always copied)

to be sure i also added : 
``` CSharp
Configure<AbpBundlingOptions>(options =>
            {
                options.StyleBundles.Configure(
                    BasicThemeBundles.Styles.Global,
                    bundle =>
                    {
                        bundle.AddFiles("/global-styles.css");
                        bundle.AddFiles("/logo.png");
                    }
                );
            });
```

the AppName take effect but LogoUrl not, in the rendered html the href is as : 
```
<a class="navbar-brand" href="/">OrgAE Admin</a>'
``
Abp  v4.0.1


Regards.

**Comment by aelhadi** [comment]
after looking to source code  : 

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Components/Brand/Default.cshtml

should be updated ....

**Comment by maliming** [comment]
hi @aelhadi 

I think we should use the logo on the layout page instead of the brand component, I will try to implement it.
