### ISSUE TITLE
Invalid sorting in MongoAuditLogRepository 

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#6706]
In the `GetEntityChangeListAsync `method sorting is done after the database fetch operation. It should be called before the query execution.

https://github.com/abpframework/abp/blob/dev/modules/audit-logging/src/Volo.Abp.AuditLogging.MongoDB/Volo/Abp/AuditLogging/MongoDB/MongoAuditLogRepository.cs#L179

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/6729
