### ISSUE TITLE
Blazor Basic Theme - Script error 

### ISSUE THREAD

**Issue by d-oit** [abpframework/abp#6707]
If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**.
**4.1.0-rc.1** / Blazor Book Store Sample
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Blazor -> calls the mvc page "/Account/Manage" 
* Your database provider(EF Core/MongoDB)
EF core
* Exception message and **stack trace** if available (check the logs).

1. error in script:

luxon.min.js?_v=637433771215148737:1 Uncaught SyntaxError: Unexpected token ')'
abp.luxon.js?_v=637424261640000000:4 Uncaught ReferenceError: luxon is not defined
    at abp.luxon.js?_v=637424261640000000:4
    at abp.luxon.js?_v=637424261640000000:46

2. you are on the abp mvc module / website. No WASM Menu avaible and the Home Button link the home button link is on the server and show's swagger. 

![image](https://user-images.githubusercontent.com/6849456/102602428-d3519f00-4121-11eb-8546-a3690f97a2a2.png)

No prio for me - i use my own razor page.

**Comment by realLiangshiwei** [comment]
How to reproduce this problem? can you provide steps?

**Comment by d-oit** [comment]
Reproduce with any current blazor template 4.1.0-rc.1 or your Blazor Book Store Sample 
https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore


Open Browser Developement Tools (Edge / Chrome) -> then you see the script error.
Login with any user (admin or your own user)
![image](https://user-images.githubusercontent.com/6849456/102761151-d6919880-4376-11eb-8f3b-d040f4fa5a0f.png)


2. You are now on the server side - no wasm menu. Click on the Book Store opens swagger
![image](https://user-images.githubusercontent.com/6849456/102761521-4ef85980-4377-11eb-8ba4-83d53faf6117.png)

3. User has to use browser Back to come back to the wasm application.

**Comment by realLiangshiwei** [comment]
Can't reproduce your problem.

![image](https://user-images.githubusercontent.com/16813853/102767531-b1267e00-43ba-11eb-8edb-c0e1d86ff1d3.png)

2. Server side is HttpApi and Auth server.  there is no problem.
3. It will back to the Blazor application after you login.

**Comment by d-oit** [comment]
Oh there is a new abp version on nuget - i think you tested with 4.1.0-rc.2 
With this version the script error is gone.

2. If you click on "BookStore" (see the image red circle) the user opnes the swagger page (on the server) instead of the blazor menues. 
He can't go back (only with browser back to the wasm app).

![image](https://user-images.githubusercontent.com/6849456/102782074-018ce400-4399-11eb-8941-2c80b47c139d.png)

**Comment by d-oit** [comment]
With the current template version the mvc abp account personal info is loaded.

Possible fix:

Add to Blazor project:
  <PackageReference Include="Volo.Abp.Identity.Blazor" Version="4.1.0-rc.X" />

    typeof(AbpAccountBlazorModule)

remove else 

![image](https://user-images.githubusercontent.com/6849456/102785027-8ed23780-439d-11eb-80e3-f184033ed85c.png)

I could create a PR with the changes.

**Comment by realLiangshiwei** [comment]
Hi,

This is by design, I will try to fix the problem.
