### ISSUE TITLE
Build errors after importing ABP Blazor basic theme

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#6708]
I want to be able to switch `container` to `container-fluid` in some of my Blazor pages, as in MVC template, so I followed [your guide "Implementing a Theme - The Easy Way"](https://docs.abp.io/en/abp/latest/UI/Blazor/Theming#the-easy-way):

1. I cloned the `Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme` project from the ABP `/dev` branch today (so [here](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme)).
1. I added an empty C# library project in my solution.
1. I copied ABP project content (except Fody stuff) into my new empty project folder.
1. I added `<RootNamespace>` in `.csproj` to ABP project's one.
1. I replaced `ProjectReference` `Volo.Abp.AspNetCore.Components.WebAssembly.Theming` to a `PackageReference` to `4.0.1` NuGet package.

Here is my final `.csproj`:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <RootNamespace>Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly.Theming" Version="4.0.1" />
    </ItemGroup>

</Project>
```

But I get the following errors when I build the project:
```
MainLayout.razor.cs(13,33): Error CS0115 : 'MainLayout.OnInitialized()': no suitable method found to override
FirstLevelNavMenuItem.razor.cs(17,33): Error CS0115 : 'FirstLevelNavMenuItem.OnInitialized()': no suitable method found to override
NavMenu.razor.cs(14,39): Error CS0115 : 'NavMenu.OnInitializedAsync()': no suitable method found to override
LoginDisplay.razor.cs(16,39): Error CS0115 : 'LoginDisplay.OnInitializedAsync()': no suitable method found to override
NavToolbar.razor.cs(15,39): Error CS0115 : 'NavToolbar.OnInitializedAsync()': no suitable method found to override
SecondLevelNavMenuItem.razor.cs(17,33): Error CS0115 : 'SecondLevelNavMenuItem.OnInitialized()': no suitable method found to override
```

What did I miss?

ABP 4.0.1

**Comment by KevinFarrow** [comment]
Make sure you uninstall the existing **Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme** Nuget package

**Comment by d-oit** [comment]
Also the Volo.Abp.AspNetCore.Components.WebAssembly is needed:

```
 <ItemGroup>
  <PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly" Version="4.1.0-rc.1" />
  <PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly.Theming" Version="4.1.0-rc.1" />
</ItemGroup>
```


No reference  
`<PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly" Version="4.1.0-rc.1" />`
needed if you add SupportedPlatform to your project file. 

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-5.0&tabs=visual-studio#browser-compatibility-analyzer-for-blazor-webassembly

Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Razor">


  <ItemGroup>
    **<SupportedPlatform Include="browser" />**
  </ItemGroup>
```

**Comment by Stirda** [comment]
Ok. I figured it out. The problem was modifying project namespace. I wanted to change folder name and project file name, but I can live with staying with ABP namespace.

@KevinFarrow Thank you. I already done it. This was not the problem.

@do-it-ger Thank you too. I didn't need to add Volo.Abp.AspNetCore.Components.WebAssembly package referencies. Maybe I will encounter this need when I will update to ABP 4.1. In such case, your addition will be very useful.
