### ISSUE TITLE
Add a hook at the end of body (force to next modals containers)

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#6715]
* Your **ABP Framework version** = 4.0.1.
* Your **User Interface** type (Angular/MVC/React... etc.) MVC Commercial (Lepton)

![image](https://user-images.githubusercontent.com/23167047/102678494-27aa5c80-41be-11eb-931d-7d496147c515.png)
That `<script></script>` must be after modal container right before body end. 
Maybe I need to convert all modals to page 😞

**Comment by maliming** [comment]
hi @hitaspdotnet 

Please create a question at https://support.abp.io/QA/Questions/New

**Comment by hitaspdotnet** [comment]
This issue is related to the framework UI hooks system and its not a support needs question

**Comment by maliming** [comment]
Sorry about that, I thought it was related to Lepton.

Can you explain why the problem you mentioned happened?

![image](https://user-images.githubusercontent.com/6908465/102733785-240f0500-4379-11eb-8da8-2b38bbc29001.png)

**Comment by hitaspdotnet** [comment]
I have created a component then I configured the AbpLayoutHookOptions in my app web module
```csharp
    Configure<AbpLayoutHookOptions>(options =>
    {       
        options.Add(
            LayoutHooks.Body.Last,
            typeof(ScriptTagViewComponent),
            layout: StandardLayouts.Application
        );
    });
```
but as you can see in attached image after opening modal the modal related elements comes after my script tag so the script not running for modals.

**Comment by hitaspdotnet** [comment]
After replace the Lepton Application Layout issue not solved, its related to abp modal manager
https://github.com/abpframework/abp/blob/fe3b286058571fabff124f8a40fa80a014bd996e/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L58

**Comment by maliming** [comment]
hi @hitaspdotnet 
Can you share the code of `ScriptTagViewComponent`? that I can reproduce your problem.

**Comment by hitaspdotnet** [comment]
**TagViewComponent.cs**
```csharp
    public class TagViewComponent : AbpViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("/Components/Tag/Default.cshtml");
        }
    }
```
**Default.cshtml**
```cshtml
<hitasp-scripts></hitasp-scripts> //a tag helper for loading scripts by form's elements
```
MyWebModule
```csharp
        private void ConfigureHooks()
        {
            Configure<AbpLayoutHookOptions>(options =>  // a component for loading related scripts at the head
            {
                options.Add(
                    LayoutHooks.Head.Last,
                    typeof(JsViewComponent),
                    layout: StandardLayouts.Application
                );
                
                options.Add(
                    LayoutHooks.Body.Last,
                    typeof(TagViewComponent),
                    layout: StandardLayouts.Application
                );
            });
        }
```
Everything works fine in pages, not modals

**Comment by maliming** [comment]
hi @hitaspdotnet 

Can you share a simple project?  
I can't get `<hitasp-scripts></hitasp-scripts>`.

Thanks.

**Comment by hitaspdotnet** [comment]
1. Create a view component with whatever you want `<h4>Hello maliming</h4>`
2. Add the created component to Abp Layout Hook at LayoutHooks.Body.Last 
```csharp
            Configure<AbpLayoutHookOptions>(options =>
            {               
                options.Add(
                    LayoutHooks.Body.Last,
                    typeof(MalimingViewComponent),
                    layout: StandardLayouts.Application
                );
            });
```
3. Run the app and check the page source `<h4>Hello maliming</h4>` is right there at the end of body
4. open a modal and check page source again, the `<h4>Hello maliming</h4>` state is not `LayoutHooks.Body.Last`

What's not clear after 8 comments?
It's related to abp modal manager 
https://github.com/abpframework/abp/blob/f771eb4bba6622ce7106965f21fe340d3881aa0c/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L58

**Comment by maliming** [comment]
hi @hitaspdotnet 

I understand what you mean. I just don't think this is a problem.

Can you share the code of your script? Why does it require the position of elements? Maybe you can change your script to solve the problem. : )

**Comment by hitaspdotnet** [comment]
Its a 3rd party script and the reader end point is related tagged element. 
My script is not problem, its a challenge for abp hooks system, where the `LayoutHooks.Body.Last` must be last of body. Your solution is to clear the problem instead of solving it.

**Comment by ebicoglu** [comment]
https://faqs.skillcrush.com/article/176-where-should-js-script-tags-be-linked-in-html-documents

**Comment by maliming** [comment]
ok, I will update the bootstrap/modal-manager.js file.
