### ISSUE TITLE
Referencing HttpApi.Client project

### ISSUE THREAD

**Issue by f-belhocine** [abpframework/abp#6719]
Hi all,
I want just to confirm architectural concept with the abp framework.
If I have a modular application and want to deploy some modules in separate containers (as microservice).
Is it correct to reference Module1.HttpApi.Client.csproj project from Module2.Application.csproj to consume Module1 from Module2 using HttpProxy Client?
using this architcture to get dtos objects referenced just by their ids (DDD referencing between aggragtes).
Thanks in advance.

**Comment by KevinFarrow** [comment]
There's a Microservices demo that might answer your question:

https://github.com/abpframework/abp-samples/tree/master/MicroserviceDemo

**Comment by f-belhocine** [comment]
Thank you for the response.
I saw this sample. But the question is about architectural perspective when referencing Module1 from Module 2 of the same application and application modules are deployed as microsoervices. 
Here how I do it

**1. Module1**
- Module1.Web
- Module1.Application
- Module1.Application.Contracts
- Module1.HttpApi.Client

**2. Module2**
- **Module2.Web --> references Module1.HttpApi.Client** which registers Module1.Application.Contracts interfaces as client proxies.
- **Module2.Application --> references Module1.Application.Contracts** to get Dtos of Module1 entities referenced only by their Ids in Module2.
- Module2.Application.Contracts
- Module2.HttpApi.Client
