### ISSUE TITLE
HttpApi.Host HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#6720]
I just upgrade the abp to 4.1.0-rc.2 from 4.0.1, HttpApi.Host can't launch with error below
![image](https://user-images.githubusercontent.com/4489940/102703364-c90ddd00-42a8-11eb-94b5-d84bec07e7fd.png)

**Comment by maliming** [comment]
Can you check the `UsersAuthNController`?

![image](https://user-images.githubusercontent.com/6908465/102703966-df1f9b80-42b0-11eb-8d16-2b5b135ff6e5.png)

**Comment by ruby0602** [comment]
I solved the problem, thanks

**Comment by ShifanilaSenthil** [comment]
hi @ruby0602 ,
it would be very useful if you could share us how you have resolved this issue
Thanks in advance
