### ISSUE TITLE
How to change Default login view url from MVC to Angular

### ISSUE THREAD

**Issue by begandroide** [abpframework/abp#6739]
Hi, recently i upgrade from abp 3.x to 4.0.2, and i has problems with OAuth and abp:

* **ABP 4.0.2**.
* **Angular 11** 
* EF core & mongoDB
* Hasn´t logs on console or log http.host.

I use ABP framework on front and backend, in front-end i not use abp/theme-shared or abpt/theme-basic; I made a front-end with Angular material and a theme. 
With **ABP 3.x** i used the auth code flow from the AuthService of ABP, passing username and password. In ABP 4.0 the method `login(username, password)` was changed and for that i decided not use AuthService, and use OAuthService with his method `fetchTokenUsingPasswordFlow`, here i need deal with redirection, history, etc. (all fine to this point).

Now, if im not logged in and I navigate to route that has AuthGuard, so im being redirected to localhost:44313 (api home): with error route: 
![image](https://user-images.githubusercontent.com/22018004/102786217-e8c30500-437d-11eb-8d42-5603d66226b9.png)

As you can see, the issue is clear: invalid redirect_uri, but i has changed the configuration on:
1. appsettings.json (dbmigrator), i added to a client scope APP de "RootUrl" (http://localhost:4200)
2. envirnoment.ts: OauthConfig is like that:
```typescript
  oAuthConfig: {
    issuer: 'https://localhost:44313',
    redirectUri: baseUrl,
    clientId: 'MyProjectName_App',
    scope: 'offline_access MyProjectName',
    responseType: 'code',
  },
```

thanks in advance

**Comment by begandroide** [comment]
I add some configuration like that ABP team mentioned in the release 3.1 post:

![image](https://user-images.githubusercontent.com/22018004/102800186-46614c80-4392-11eb-86cf-c5f4af1641ee.png)

And now im being redirected to account/login, but of backend host:port.

![image](https://user-images.githubusercontent.com/22018004/102797799-f339ca80-438e-11eb-8041-d1732e3817de.png)

**So, how can i change the account/login host?** because i want to be redirected to login page of angular, not MVC or net core.

pd: In DB, table `[IdentityServerClientRedirectUris]` has three RedirectUri (api signin-oidc, host angular and Swagger)

**Comment by begandroide** [comment]
I was thinking about this and to avoid redirect to api login i need to customize the AuthGuard (because im still using it), and implement the old behaviour.

If this is the solution, please close the issue or give me some feedback. 
Regards

**Comment by numanrauf** [comment]
Same here, Migrated to 4.0, was using before custom Login page for authentication in angular, now I have upgraded and have no idea how to customize the new MVC page, kind support is appreciated thanks.

**Comment by davidzwa** [comment]
Maybe a related bug-report:
https://support.abp.io/QA/Questions/711/Authentication-flow-redirects-not-working-as-expected-out-of-the-box

PR:
https://github.com/abpframework/abp/pull/6734

Do note that this bug was reported for the commercial modules. I cant be absolutely sure that it is also applicable here, but it does suggest to be so.

**Comment by begandroide** [comment]
Thank you @davidzwa I readed the bug-report on support page of ABP, i will see if is related issue. 

I dont close the issue until i can resolve and provide some solution.

Regards!

**Comment by begandroide** [comment]
Just in my case (i has all custom modules in my app) just implement old behaviour on a custom AuthGuard like versions older than v.3.1.

Old behaviour is in this file:
 [https://github.com/abpframework/abp/blob/rel-3.0/npm/ng-packs/packages/core/src/lib/guards/auth.guard.ts](https://github.com/abpframework/abp/blob/rel-3.0/npm/ng-packs/packages/core/src/lib/guards/auth.guard.ts)

And works.

**Comment by davidzwa** [comment]
@begandroide please close the issue if its resolved.
