### ISSUE TITLE
Sendemail  Cryptography.CryptographicException: The input data is not a complete block.

### ISSUE THREAD

**Issue by ThreeLambs** [abpframework/abp#6745]
```
  public class EmailSendingJob : AsyncBackgroundJob<EmailSendingArgs>, ITransientDependency
    {

        private readonly ISmtpEmailSender _emailSender;

        public EmailSendingJob(ISmtpEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        public override async Task ExecuteAsync(EmailSendingArgs args)
        { 
            await _emailSender.SendAsync(new System.Net.Mail.MailMessage("yangqun@qq.com",
                args.EmailAddress,
                args.Subject,
                args.Body));
        }
    } 

[10:47:30 ERR] The input data is not a complete block.
System.Security.Cryptography.CryptographicException: The input data is not a complete block.
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
```
    
![Snipaste_2020-12-22_11-10-43](https://user-images.githubusercontent.com/23123048/102844534-a0bbe500-4446-11eb-90a2-662bb99251a5.png)

**Comment by zhangzunke** [comment]
@ThreeLambs, I met the same issues, how do you fix it, thanks.

**Comment by Keay5** [comment]
> @ThreeLambs, I met the same issues, how do you fix it, thanks.

https://docs.abp.io/en/abp/latest/Emailing

Encrypt the SMTP Password
**Abp.Mailing.Smtp.Password must be an encrypted value**. If you use the ISettingManager to set the password, you don't have to worry. It internally encrypts the values on set and decrypts on get.

**If you use the appsettings.json to store the password, you should manually inject the ISettingEncryptionService and use its Encrypt method to obtain an encrypted value**. This can be done by creating a simple code in your application. Then you can delete the code. As better, you can create a UI in your application to configure the email settings. In this case, you can directly use the ISettingManager without worrying the encryption.

```
using Volo.Abp.Emailing;
using Volo.Abp.Settings;

namespace AbpManaul.Application.Settings;

public class SettingService
{
    private readonly ISettingEncryptionService _settingEncryptionService;
    private readonly ISettingDefinitionManager _settingDefinitionManager;

    public SettingService(
            ISettingEncryptionService settingEncryptionService,
            ISettingDefinitionManager settingDefinitionManager)
    {
        _settingEncryptionService = settingEncryptionService;
        _settingDefinitionManager = settingDefinitionManager;
    }

    public string EncryptMailingSmtpPassword(string passsword)
    {

        var setting = _settingDefinitionManager.Get(EmailSettingNames.Smtp.Password);
        var encryptPassword = _settingEncryptionService.Encrypt(setting, passsword);

        return encryptPassword;
    }
}


```
for example:

call `EncryptMailingSmtpPassword(123)` return "3zil2vJ325s+uboMEiKCDA=="
then set `Abp.Mailing.Smtp.Password` in the  appsettings.json as following:

```
  "Settings": {
    ...
    "Abp.Mailing.Smtp.Password": "3zil2vJ325s+uboMEiKCDA==",
    ...
  },

```
