### ISSUE TITLE
Account emails do not use resource files

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#6757]
Using MVC Razor pages startup template.

Account emails (like password reset) do not use resource files. Although there are "PasswordResetInfoInEmail", "PasswordReset" and "ResetMyPassword" resources in en.json file incoming mails are not converted according to resources.

Is there an extra step to ensure this behaviour?

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by espindl** [comment]
ABP Framework version : 4.0.0

- Create a multi tenant application (default) by using startup template ASP.NET Core MVC UI with Razor Pages.
- Set up email sending by using the settings on appsettings.json 
- Start the app and click forgot password.
- User receives email that did not use localization. Containing the resource names like PasswordReset and PasswordResetInfoInEmail

**Comment by espindl** [comment]
Thank you for your fast response. 🎉  I saw that they are added to the account module's resource files.  But I thought that if I write those resources to my own, those will be used. Maybe making the localization to look for the resource files all the level up. (I did not look at the code, maybe it is impossible but at first sight, I think a solution like this.) 

**And also, is there a solution for this before it gets into the release?**

**Comment by maliming** [comment]
hi @espindl 

See https://docs.abp.io/en/abp/latest/Localization#extending-existing-resource

**Comment by espindl** [comment]
Hi @maliming thank you. 
Because documentation is not that detailed I wanted to share my steps to extend Account module's resources. 

1. Add "Volo.Abp.Account.Application.Contracts" nuget package to your project that contains your resources (eg Domain.Shared)
2. Add a DependsOn over the module > `typeof(AbpAccountApplicationContractsModule)`
3. Add this line to ConfigureServices > `Configure<AbpLocalizationOptions>(options => `
                 `options.Resources.Get<AccountResource>().AddVirtualJson("/Localization/Account");`
4. Location that is inside the AddVirtualJson paranthesis is where you will put your extension (or overriding resource)
5. This will Get the AccountResource and extend/override its resources.

Hope this helps...
