### ISSUE TITLE
Test scenario: compare abp based application with plain aspnetcore + efcore application

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6768]
Each thread does this flow:

* Create a book (with random name and price), get its id
* Get the same book with the id
* Update the same book (change the name, for example) with the id
* Get the list of books
* Delete the book with the id

We want to see the difference between the "with abp" and "without abp" versions of the application.

I already created the applications and prepared initial jMeter scenarios ([see](https://github.com/abpframework/abp/tree/dev/test/AbpPerfTest)). You will mostly play with jMeter, no code change should be needed.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/102963284-a63b2d00-4523-11eb-84ee-09a51cf1d201.png)
