### ISSUE TITLE
Cannot localize submit button in dynamic form

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#6769]
Using razor pages version 4.0

Would be great if submit buttons of dynamic forms supported localized texts
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Tag-Helpers/Dynamic-Forms#submit-button

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/32402a99b07ea994efe1880e0655eff3c73e2166/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Bootstrap/TagHelpers/Form/AbpDynamicformTagHelperService.cs#L194
