### ISSUE TITLE
The required antiforgery cookie ".AspNetCore.Antiforgery.el0QpAqipuo" is not present

### ISSUE THREAD

**Issue by journey191** [abpframework/abp#6785]
* Your **ABP Framework version**.
* 3.3.1
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Vue

Err Log:
```
[ERR] The required antiforgery cookie ".AspNetCore.Antiforgery.el0QpAqipuo" is not present.
[INF] Authorization failed for the request at filter 'Volo.Abp.AspNetCore.Mvc.AntiForgery.AbpAutoValidateAntiforgeryTokenAuthorizationFilter'.
```

Request Headers:
![image](https://user-images.githubusercontent.com/11626700/103007432-62214a00-456e-11eb-8ade-01fed04c1fe2.png)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

You can also check the `anti-request-forgery` document.

https://docs.abp.io/en/abp/latest/CSRF-Anti-Forgery
https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-5.0
