### ISSUE TITLE
Implement BeatPlus HealthCheck as a Module with own configuration

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#679]
Hi. 
HealthChecks packages include health checks for:

- Sql Server
- RabbitMQ
- Redis 
- System: Disk Storage, Private Memory, Virtual Memory
- Azure Storage: Blob, Queue and Table
- Amazon S3
- Network: Ftp, SFtp, Dns, Tcp port, Smtp, Imap
- MongoDB
- Identity Server
- Uri: single uri and uri groups

Can I have PR for this?
#336 
Related 
#664

**Comment by hikalkan** [comment]
Can you write your plan first. How many projects (nuget packages) will be and what will they do?
Thanks.

**Comment by hitaspdotnet** [comment]
@hikalkan In fact, I want to rewrite the [Xabaril/AspNetCore.Diagnostics.HealthChecks](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks) for compatibility with the ABP. 
Given that each service dependencies are unique, each package must be provided separately. So, we can have a package **Volo.Abp.HealthChecks** at ABP which contains abstractions and configurations, then I want create a module **Volo.HealthChecks.**{_ServiceName_} which contains BeatPlus SPA UI and diagnostic services as separately packages.

**Comment by hitaspdotnet** [comment]
related #664
