### ISSUE TITLE
Virtual File System Explorer Support ManifestDirectoryInfo&ManifestFileInfo

### ISSUE THREAD

**Issue by jortygu** [abpframework/abp#6799]
* Your **ABP Framework version**.
  v3.1.0
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
  MVC
* Your database provider(EF Core/MongoDB)
  EF Core
* Exception message and **stack trace** if available (check the logs).
  @realLiangshiwei ,can Virtual File System Explorer add  Support for ```Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestDirectoryInfo``` and ```Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestFileInfo``` ?
  current only support FileInfoTypes like below
  ``` c#
  public static class VirtualFileExplorerConsts
  {
      public static string[] AllowFileInfoTypes = new[] {"VirtualDirectoryFileInfo", "EmbeddedResourceFileInfo"};
  }
  ```

**Comment by realLiangshiwei** [comment]
Hi,

Virtual File System Explorer only applies to virtual file systems and you can add embedded files to the virtual file system.

**Comment by jortygu** [comment]
@realLiangshiwei i know,i follow below configuration([Use GenerateEmbeddedFilesManifest option for the projects with embedded files](https://github.com/abpframework/abp/issues/4541)), then i can't see embedded files in Virtual File System Explorer.
by debug,i found the Embedded files's FileIntoType is ```Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestDirectoryInfo``` and ```Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestFileInfo``` ,they are not support by Virtual File System Explorer.
```
1.Add <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest> to the property group of the .csproj file.
2.Add Microsoft.Extensions.FileProviders.Embedded package to the .csproj file (<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="3.1.5" />)
3.Remove namespace parameter while using the options.FileSets.AddEmbedded.
Configure<AbpVirtualFileSystemOptions>(options =>
{
    options.FileSets.AddEmbedded<TieredDemoDomainSharedModule>("");
});
```
when i removed ```<GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>``` and ```<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="3.1.5" />``` and configure VitrualFileSystem like below,i can see embedded files in Virtual File System Explorer. 
``` C#
Configure<AbpVirtualFileSystemOptions>(options =>
{
    options.FileSets.AddEmbedded<TieredDemoDomainSharedModule>("MyComponly.MyProjectName");
});
```
