### ISSUE TITLE
Whats the difference between the Blg.Users and AbpUsers tables in BlogDemoApp migrations

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#681]
2 table with same contents. Is it normal?

**Comment by hikalkan** [comment]
Yes, it's normal. Blog module has it's own Users table which is synchronized with the AbpUsers table with events. AbpUsers is a part of Identity module.
In this way, Blog module become independent from the Identity module.
This is needed for modularity and microservice architecture.

**Comment by Nokecy** [comment]
Can Blg.Users have its own properties? @hikalkan

**Comment by hitaspdotnet** [comment]
@Nokecy 

> Blog module has it's own Users table which is synchronized with the AbpUsers table with events

So, Yes.
