### ISSUE TITLE
Audit log for Razor pages does not store to database

### ISSUE THREAD

**Issue by souselesslove** [abpframework/abp#6811]
### Abp Version
4.0.2
### database provider
EF Core
### exception
no exception, logs just show in console window
### other
1.use cli create an app: abp new Company --tiered --separate-identity-server
2.run **Company.DbMigrator**
3.run **Company.HttpApi.Host**, **Company.IdentityServer**, **Company.Web**
4.**Company.HttpApi.Host** audit log saved to database
5.**Company.IdentityServer** audit log saved to database
6.**Company.Web** audit log just show in console window
7.they have same audit configuration:
```
Configure<AbpAuditingOptions>(options =>
            {
                options.IsEnabledForGetRequests = true;
                options.IsEnabledForAnonymousUsers = true;
                options.ApplicationName = configuration["App:Name"];
            });
```

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by souselesslove** [comment]
> * Your **ABP Framework version**.
> * Your database provider(EF Core/MongoDB)
> * Exception message and **stack trace** if available (check the logs).
> * Steps needed to **reproduce** the problem.

[detail](https://github.com/abpframework/abp/issues/6811#issue-774515820)

**Comment by maliming** [comment]
> 6.Company.Web audit log just show in console window

Yes,  `Company.Web` is just a UI project. There is no business and database code.

https://docs.abp.io/en/abp/latest/Startup-Templates/Application#web-project-1
