### ISSUE TITLE
TimeZone

### ISSUE THREAD

**Issue by ThreeLambs** [abpframework/abp#6817]
``After setting the time zone, the datatables language translation don't work`` 
```
Time Zones
This section covers the ABP Framework infrastructure related to managing time zones.

TimeZone Setting
ABP Framework defines a setting, named Abp.Timing.Timezone, that can be used to set and get the time zone for a user, tenant or globally for the application. The default value is UTC.

See the setting documentation to learn more about the setting system.
```
![Snipaste_2020-12-25_16-52-06](https://user-images.githubusercontent.com/23123048/103128830-bbee5500-46d1-11eb-8a9f-e4164165ebdf.png)
![Snipaste_2020-12-25_16-52-30](https://user-images.githubusercontent.com/23123048/103128840-bee94580-46d1-11eb-9953-d52d88a638c9.png)

I set timezone from utc to UTC8 or Local ,the datatables language translation don't work

**Comment by realLiangshiwei** [comment]
It looks like you're using a third-party theme, It has nothing to do with ABP.

**Comment by ThreeLambs** [comment]
> It looks like you're using a third-party theme, It has nothing to do with ABP.
it still not work 
 can't get  <script src="/Abp/ApplicationConfigurationScript"></script>
 
![Snipaste_2020-12-28_11-43-08](https://user-images.githubusercontent.com/23123048/103188443-64cfc680-4903-11eb-87c8-c548a3606b21.png)

![Snipaste_2020-12-28_11-48-59](https://user-images.githubusercontent.com/23123048/103188447-68fbe400-4903-11eb-949f-b286692595b0.png)
```
Request URL: https://localhost:44380/Abp/ApplicationConfigurationScript
Request Method: GET
Status Code: 500 
Remote Address: [::1]:44380
Referrer Policy: strict-origin-when-cross-origin
```

Id | Name | Value | ProviderName | ProviderKey
-- | -- | -- | -- | --
4891f172-23c2-4983-b8dc-78b65f6ff966 | Abp.Timing.TimeZone | UTC8 | T |

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by ThreeLambs** [comment]
> * Your **ABP Framework version**.
> * Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
> * Your database provider(EF Core/MongoDB)
> * Exception message and **stack trace** if available (check the logs).
> * Steps needed to **reproduce** the problem.

v4.0.2 Mvc 
1. create a mvc demo 
2. change timezone
```
 INSERT INTO  Demo.dbo.AbpSettings
(Id, [Name], [Value], ProviderName, ProviderKey) 
VALUES (newid(), N'Abp.Timing.TimeZone', N'UTC8', 'T', NULL)
```

**Comment by realLiangshiwei** [comment]
UTC8 is an invalid windows timezone ID. see https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones
