### ISSUE TITLE
DbMigrator running occurred warning in 4.1.0-rc.2

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#6819]
Abp version 4.1.0-rc.2
User Interface: MVC
Database provider: EF Core

How to reproduce:
1. Run cmd "abp new Acme.BookStore --preview"
2. Run Acme.BookStore.DbMigrator and warning occurred

I changed the MultipleActiveResultSets in Default connection from true to false, then the warning disappeared.
 "Default": "Server=(LocalDb)\\MSSQLLocalDB;Database=BookStore;Trusted_Connection=True;MultipleActiveResultSets=true"
I also tried the  v3.3.2 and v4.0.2 start templates, there's no this warning even MultipleActiveResultSets value is true.

Below is the detail info, I would like to know why this happened, Thank you.

[18:03:50 WRN] Savepoints are disabled because Multiple Active Result Sets (MARS) is enabled. If 'SaveChanges' fails, then the transaction cannot be automatically rolled back to a known clean state. Instead, the transaction should be rolled back by the application before retrying 'SaveChanges'. See https://go.microsoft.com/fwlink/?linkid=2149338 for more information. To identify the code which triggers this warning, call 'ConfigureWarnings(w => w.Throw(RelationalEventId.SavepointsDisabledBecauseOfMARS))'.

![image](https://user-images.githubusercontent.com/6952917/103131436-b6960800-46db-11eb-9111-e2e4c25207fa.png)

**Comment by real-zony** [comment]
Hi @GerryGe, This warning was introduced in EF Core 5.0.1.(abp 4.1.x) For details, please refer to 

- https://github.com/dotnet/efcore/releases/tag/v5.0.1
- https://github.com/dotnet/efcore/pull/23305/files#diff-8b3dd7645d9d7ac7e65062c2db7948e3553cb149750e5b76ff6e338ffa359e2d

**Comment by maliming** [comment]
@GameBelial Should we remove `MultipleActiveResultSets=true` in `ConnectionStrings`?

**Comment by real-zony** [comment]
@maliming This problem is caused by the introduction of the SavePoint feature in EF Core 5.0.1, which is the default behavior in EF Core 5.0.1. I think in our default template, `MultipleActiveResultSets=true` should be removed (for SQL Server).
If you need to disable the SavePoint feature, you can refer to this Issue (https://github.com/dotnet/efcore/issues/23269).
