### ISSUE TITLE
Async application initialization methods on the abpmodule class

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6828]
I had closed this before: https://github.com/abpframework/abp/issues/5382
I am opening again and adding to backlog for next major versions.

Also, see https://github.com/maliming/AbpAsyncApplicationLifecycle

**Comment by puschie286** [comment]
hey, we needed this feature and implemented it directly in Volo.Abp.Core.

if someone is interested in this: https://github.com/puschie286/abp/tree/async-init-shutdown
note: not fully tested yet

**Comment by maliming** [comment]
I realized that through the Minimal API, our module methods can be initialized completely asynchronously.

![image](https://user-images.githubusercontent.com/6908465/146483689-57c96871-1b38-4db9-bc9a-47ad0cc058ef.png)

**Comment by hikalkan** [comment]
Yes, that's good. We can create `InitializeApplicationAsync()` with backward-compability support (like all module initialization methods will have async versions and they call the sync version internally by default).

**Comment by maliming** [comment]
So far so good.

https://github.com/abpframework/abp/pull/10928/commits/8c5e3cd30aeb34eff42a3c292a9f1a4d4b19355e
