### ISSUE TITLE
Navigation extension property table header should be localized

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#6834]
Prop definition:

````csharp
ObjectExtensionManager.Instance.Modules()
    .ConfigureIdentity(identity =>
    {
        identity.ConfigureUser(user =>
        {
            user.AddOrUpdateProperty<Guid>(
                "PrimaryRoleId",
                property =>
                {
                    property.UI.Lookup.Url = "/api/identity/roles";
                    property.UI.Lookup.DisplayPropertyName = "name";
                }
            );
        });
    });
````

Localization:

````xml
"DisplayName:PrimaryRoleId": "Primary Role"
````

Create/Edit modal:

![image](https://user-images.githubusercontent.com/1210527/103176657-9fdee500-4884-11eb-8bc1-c6f0ea2084de.png)

Properly localized.

UI Table:

![image](https://user-images.githubusercontent.com/1210527/103176653-95bce680-4884-11eb-8f36-0cd9fa97f79b.png)

Not localized. It should be localized with the same rules.

**Comment by ilkayilknur** [comment]
This is the fix for the issue. https://github.com/abpframework/abp/issues/6834 This change could break the Angular side, or the issue may exist on the Angular side as well. I will talk to @armanozak tomorrow.

**Comment by ilkayilknur** [comment]
Fixed https://github.com/abpframework/abp/pull/6859
