### ISSUE TITLE
Blazor: clicking on Brand opens Swagger page

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#6837]
* Your **ABP Framework version - **4.1.0-rc.2**
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI - **Blazor**
* Your database provider(EF Core/MongoDB) - **EF Core**
* Steps needed to **reproduce** the problem:
1. Create new solution:
- UI Framework: Blazor
- Separate Identity Server: No
- Use latest pre-release version (4.1.0-rc.2): Yes

2. Run DbMigrator package to create database and initial seed data

3. Run Host and Blazor projects
 
4. Login

5. Click on the Brand (top left) - redirects to Swagger page

https://user-images.githubusercontent.com/69393775/103181916-6024f700-489e-11eb-9fa8-5aee3bae7706.mp4

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/6707
