### ISSUE TITLE
Blazor: "Home" and "Administration" menu items disappear

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#6838]
Your **ABP Framework version - 4.1.0-rc.2
Your User Interface type (Angular/MVC/React... etc.) if the issue is related to a specific UI - Blazor
Your database provider(EF Core/MongoDB) - EF Core
Steps needed to reproduce the problem:
1. Create new solution:
- UI Framework: Blazor
- Separate Identity Server: No
- Use latest pre-release version (4.1.0-rc.2): Yes

2. Run DbMigrator package to create database and initial seed data

3. Run Host and Blazor projects

4. Login

When I select **"Manage your profile"** from the admin menu (top right) the **Home** and **Administration** menu items disappear from the top main menu

![image](https://user-images.githubusercontent.com/69393775/103182226-ba738700-48a1-11eb-953b-12ae7cf18ca4.png)

![image](https://user-images.githubusercontent.com/69393775/103182230-c2cbc200-48a1-11eb-9c88-86a1e79b162a.png)

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/6707#issuecomment-748901676
