### ISSUE TITLE
CMS Kit - Complete Unit Tests For The Content and Tag System

### ISSUE THREAD

**Issue by ilkayilknur** [abpframework/abp#6842]
We need to complete unit tests for the content and tag system.

**Comment by cotur** [comment]
Content, tag repositories tests and tag manager test are created.

**Comment by ilkayilknur** [comment]
How are we going to review the unit tests without a PR?

**Comment by cotur** [comment]
You can follow this [PR,](https://github.com/abpframework/abp/pull/6756) it's still `draft` and under development.
