### ISSUE TITLE
CMS Kit-Add DBMigrator Project

### ISSUE THREAD

**Issue by ilkayilknur** [abpframework/abp#6845]
We can add the `DbMigrator` project to the solution so that devs can run the `DbMigrator` project to generator tables or collections.

**Comment by enisn** [comment]
As we discussed on this issue with @cotur, a migrator application isn't necessary to seed database. Creating a seeder class which implements `IDataSeedContributor`  is enough. So I'm closing this issue.

Feel free to re-open if think differently.
