### ISSUE TITLE
CreateUpdateDto with Many to Many

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#685]
Is there a sample for using the CreateUpdateDto with a many to many relationship?  I can't seem to figure out how to get this to work.

**Comment by hitaspdotnet** [comment]
EF core doesn't support MTM relations without join table. https://www.learnentityframeworkcore.com/configuration/many-to-many-relationship-configuration

For MTM navigations in DDD with DTOs you can take a look at [IdentityUser.cs](https://github.com/abpframework/abp/blob/master/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUser.cs). You can create domain services for each related data. It's just a suggestion and you not force for this.

**Comment by djlaney3** [comment]
Right, I understand that.  I guess my confusion comes in with how ABP suggests using the CreateUpdate dtos.  Since those aren't the actual table entities, how do they need to be configured?

**Comment by djlaney3** [comment]
Looking at that sample, in the .Web project, I see this code: 
`var input = ObjectMapper.Map<UserInfoViewModel, IdentityUserCreateDto>(UserInfo);`
`input.RoleNames = Roles.Where(r => r.IsAssigned).Select(r => r.Name).ToArray();`
`await _identityUserAppService.CreateAsync(input);`

That just calls the CreateAsync, but does that then call the AddRoles and AddClaims individually?  I'm not finding that.

**Comment by hitaspdotnet** [comment]
Your problem isn't related to ABP, it's about knowledge around Data-Transfer-Objects.
I just push my tonight works to branch [hit-commerce](https://github.com/hitaspdotnet/abp/tree/hit-commerce/modules/hit-commerce) for helping you. Unfortunately, App Services isn't ready. I'm sure you can get good ideas from Dtos and service interfaces.

There is another sample from ABP named [EventCloud](https://github.com/aspnetboilerplate/eventcloud/tree/master/aspnet-core-angular/aspnet-core/src) with MTM relationship between [Event](https://github.com/aspnetboilerplate/eventcloud/blob/master/aspnet-core-angular/aspnet-core/src/EventCloud.Core/Events/Event.cs) & [User](https://github.com/aspnetboilerplate/eventcloud/blob/master/aspnet-core-angular/aspnet-core/src/EventCloud.Core/Authorization/Users/User.cs) called [EventRegistrations](https://github.com/aspnetboilerplate/eventcloud/blob/master/aspnet-core-angular/aspnet-core/src/EventCloud.Core/Events/EventRegistration.cs)

For more info, please ask your questions in https://stackoverflow.com.

**Comment by Nongzhsh** [comment]
@hitaspdotnet Maybe I can help you in your e-commerce module.

**Comment by hitaspdotnet** [comment]
@Nongzhsh It's great. Please use my Gmail and send your contact info, Telegram, Skype or FB messenger

**Comment by djlaney3** [comment]
Thanks for the info.  With your samples, I was able to narrow down the root issue.  The missing logic for me was that my Join Table (for the M2M) entity needed to Implement "Volo.Abp.Domain.Entities.Entity".
