### ISSUE TITLE
Getting Started for Blazor Server ( not WASM )

### ISSUE THREAD

**Issue by ChEhrhard** [abpframework/abp#6880]
Hi

I try to use your framework with a Blazor Server Template. I followed the "Getting Started for Empty Web Project" Documentation but my code fails when i add  .UseAutoFac(). 

i have the followinf error : 

![image](https://user-images.githubusercontent.com/8005999/103304220-55867100-4a08-11eb-88df-218f6fee64ca.png)

what am i doing wrong ? 

thanks

**Comment by 274188A** [comment]
'Server Side Blazor' is not supported at the moment - only WASM

**Comment by ChEhrhard** [comment]
thanks for the clarification. 

is Server Side Blazor support on your roadmap ? any timing ? is there any workaround for the problem i'm facing to ?

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/5517
