### ISSUE TITLE
EF5 breaks the minimum compatibility of .netStandard 2.0

### ISSUE THREAD

**Issue by keithtoop** [abpframework/abp#6883]
Can we consider not upgrade to EF5 as it only supports .netStandard 2.1?
This is the trouble making package that force everything to be .netStandard 2.1, making traditional framework apps lost the upgrade to latest instantly.

I can't see any needs to upgrade EF5 in current Abp implementation. So can we please stay in EF3.1.10?

**Comment by maliming** [comment]
> Can we consider not upgrade to EF5 as it only supports .netStandard 2.1?

Yes. https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms

We have upgraded to NET 5.
