### ISSUE TITLE
remove role did not remove permissions

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#6895]
I use the module **identity** 

when I rename a role ,it send a event ,the  **Volo.Abp.PermissionManagement.Domain.Identity**  will handle it to change the permission provider key

but if I remove a role ,it did not remove the  permissions of the role.

if I add a role ,then renamed the role to old one name,   it will get the **old role name**'s permission

**Comment by realLiangshiwei** [comment]
Hi,

Thanks for your reporting. this is a problem, we will fix it.

![image](https://user-images.githubusercontent.com/16813853/103401719-fe59db00-4b84-11eb-9de1-80ce691df938.png)
