### ISSUE TITLE
`Email` localization problem of `Volo.Abp.Identity.Web` module.

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#690]
There's a localization problem of the `Email` field.
This can be reproduced from the Startup Template:

![snipaste_2018-12-26_10-41-58](https://user-images.githubusercontent.com/3471718/50429883-b5b71980-08fb-11e9-806e-eabef0239e86.png)

Not only the Chinese, but also all other languages.
It's because the localization key is defined incorrectly:

Related sources:

https://github.com/abpframework/abp/blob/ba72ba757ee26d3aa1f3cde99c9d68ac9849c4e5/modules/identity/src/Volo.Abp.Identity.Web/Localization/Resources/AbpIdentity/zh-Hans.json#L25

https://github.com/abpframework/abp/blob/ba72ba757ee26d3aa1f3cde99c9d68ac9849c4e5/modules/identity/src/Volo.Abp.Identity.Web/Pages/Identity/Users/CreateModal.cshtml.cs#L73

The localization key `DisplayName:EmailAddress` should be changed to `DisplayName:Email`.

**Comment by maliming** [comment]
I think you can open PR.   : )

**Comment by wakuflair** [comment]
Yeah, I'm on my way.

**Comment by wakuflair** [comment]
PR: #691
