### ISSUE TITLE
The EF Core Repositories found in the Blogging Module are not registered

### ISSUE THREAD

**Issue by send2vinnie** [abpframework/abp#6906]
By checking the EF Core module class found in the Blogging Module, those custom repositories reside in the same project are not registered to replace the generic repositories. The registration of those custom repositories should go here: [BloggingEntityFrameworkCoreModule](https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.EntityFrameworkCore/Volo/Blogging/EntityFrameworkCore/BloggingEntityFrameworkCoreModule.cs)

**Comment by realLiangshiwei** [comment]
Thanks @send2vinnie
