### ISSUE TITLE
ABP Suite modules problems 

### ISSUE THREAD

**Issue by amsaighi** [abpframework/abp#6908]
Hello everyone, 

I would like to know what the problem with **Abp Suite** it's loading since few days, No error message, nothing 
![image](https://user-images.githubusercontent.com/3142753/103365240-e9674400-4abf-11eb-809a-c3420139fe44.png)

Thank you

**Comment by maliming** [comment]
hi @amSaighi

Can you check the browser's console? or cmd logs?

**Comment by amsaighi** [comment]
Hi @maliming 

I had have no error, 
When I created a new project, it gives me opportunity to check all modules .

Thank you .

**Comment by ebicoglu** [comment]
hi i just checked and it works with 4.0.2

![](https://user-images.githubusercontent.com/9526587/103612135-ceb82380-4f34-11eb-9a8c-6b19aa712fc7.png)

I checked with 4.1.0-rc.2 and it works

![](https://user-images.githubusercontent.com/9526587/103612254-150d8280-4f35-11eb-8828-7b356a24a9f2.png)

what's your version and is there any error on the CMD window?

the logs folder is `%UserProfile%\.abp\suite\logs` you can send the logs.
