### ISSUE TITLE
Hangfire server hosted in IIS stopped because of some ABP activity

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#6910]
3.3.2 / Angular

Suddenly I have noticed in Hangfire dashboard, that there is no active servers. I took a look at log file and here is what I can see there:

> 2020-12-30 23:06:37.737 +00:00 [DBG] Stopped background worker: Volo.Abp.IdentityServer.Tokens.TokenCleanupBackgroundWorker
> 2020-12-30 23:06:37.737 +00:00 [INF] Application is shutting down...
> 2020-12-30 23:06:37.739 +00:00 [DBG] Hangfire Server is stopping...

What is supposed to mean and how to avoid this? I don't want Hangfire server to stop his work while IIS is running. Or if it is stopped I want it to restart...

**Comment by maliming** [comment]
> 2020-12-30 23:06:37.737 +00:00 [INF] Application is shutting down...

Your application is shutting down...

**Comment by alexandis** [comment]
Sorry. I thought it was somehow related. I can't see why application was shut down and why it did not restore - nothing about it in the log. Also not clear why it did not run again considering website containing all the apps is online.

**Comment by alexandis** [comment]
Sorry. I thought these two things were somewhat related. I can't see why application was shut down and why it did not restore - nothing about it in the log. Also not clear why it did not run again considering website containing all the apps is online. But so I need to close this, since not related directly to ABP.
