### ISSUE TITLE
Add UserID foreignkey to domain entity (EF) and seed appuser

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#6911]
### How to create a foreign key relationship to the AppUser / IdentityUser?
I need the Account entity below to have a reference to the user that will be managing the account.

    
    public class Account : Entity<int> { 
            public string Name { get; set; }
            // removed for brevity 
            public Guid ManagerId { get; set; }   
    }

 

### How to seed the user (appUser/IdentityUser) and set it the foreign key. 
Below is the part of the DataSeederContributor in the Domain application. 
How do you create an AppUser /IdenityUser, I just want to create a User and assign it to an entity.
      
       private readonly IGuidGenerator guidGenerator;
       private readonly IdentityUserManager userManager;
       private readonly IRepository<Account, int> accountRepo;
       
       // removed for brevity 
        // seeding the user and account.
        var user = new IdentityUser(guidGenerator.Create(), "MyUserName", "manager@demo.com", context.TenantId);
        await userManager.CreateAsync(user, "1q2w3E*");
        account = await accountRepo.InsertAsync(new Account {
                      Name = "Account Name",  
                      ManagerId = user.Id
                  }, true);

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp-samples/tree/master/DocumentationSamples/CustomApplicationModules

**Comment by rygar08** [comment]
Thank you, I've seen that example, but my requirements are to add a  UserID (in this case named 'ManagerId') onto my entity called accounts, and also to seed a new user and set the 'ManagerId' on a newly seeded account.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/7105#issuecomment-757641838
