### ISSUE TITLE
Bug in Volo.Abp.Cli command line argument

### ISSUE THREAD

**Issue by RayMMond** [abpframework/abp#6922]
According to  abp's command line help text:
https://github.com/abpframework/abp/blob/9a78e91a00d18c0b964c96e200cadf2af17c570d/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/AddModuleCommand.cs#L84

You should use `--new-template` to create new module template, but
https://github.com/abpframework/abp/blob/9a78e91a00d18c0b964c96e200cadf2af17c570d/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/AddModuleCommand.cs#L40

and 

https://github.com/abpframework/abp/blob/9a78e91a00d18c0b964c96e200cadf2af17c570d/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/AddModuleCommand.cs#L181-L184

https://github.com/abpframework/abp/blob/9a78e91a00d18c0b964c96e200cadf2af17c570d/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/AddModuleCommand.cs#L98-L99

tell the different. So which is correct `--new` or `--new-template` ?

**Comment by maliming** [comment]
hi
The help info is out of date, I will update it.

`--new` is the correct one.
