### ISSUE TITLE
HardDeleteAsync with predicate

### ISSUE THREAD

**Issue by willignicolas** [abpframework/abp#6925]
Hello,

We just migrate from asp.net boilerplate to abp and cannot found any HardDeleteAsync method wih a predicate.

So now we must obtain our entities with a request then iterate each entity and finally launch an hard delete on each entity.

I can see in the history of extension method of EfCoreRepository that the method existed but was deleted.

Is there any reason behind this delete?

Thanks.

**Comment by maliming** [comment]
You can query these entities first and then call `HardDeleteAsync` for each one. I will add a similar method.
