### ISSUE TITLE
abp Blazor (4.0.2) and redirecting after login

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#6928]
abp v4.0.2
Tiered
Blazor

Login works normally in Firefox. In Chrome (and I also tried in Vivaldi) there is no redirection after successful login. It stays on login page (and username and password textboxs are empty).

There are no errors in Chrome DevTools console.

P.S.: This is Docker deployment.

Any suggestions what could be wrong?
Thank you.

**Comment by leonkosak** [comment]
![image](https://user-images.githubusercontent.com/39346964/103460669-7a385c80-4d18-11eb-878b-0bd84d529222.png)
![image](https://user-images.githubusercontent.com/39346964/103460704-d4d1b880-4d18-11eb-9548-49a283afe6de.png)
![image](https://user-images.githubusercontent.com/39346964/103460742-19f5ea80-4d19-11eb-9d50-576e6f133854.png)
![image](https://user-images.githubusercontent.com/39346964/103460769-4d387980-4d19-11eb-8c0d-061f9fb55266.png)
![image](https://user-images.githubusercontent.com/39346964/103460795-8ffa5180-4d19-11eb-8aac-cc124fb1e1ba.png)
![image](https://user-images.githubusercontent.com/39346964/103460832-be782c80-4d19-11eb-8314-8cbc53d788aa.png)
![image](https://user-images.githubusercontent.com/39346964/103460854-ee273480-4d19-11eb-8633-fafe64f3b2d3.png)
![image](https://user-images.githubusercontent.com/39346964/103460877-26c70e00-4d1a-11eb-9eed-798fddf37687.png)
![image](https://user-images.githubusercontent.com/39346964/103460948-dd2af300-4d1a-11eb-8545-96237b64993b.png)

FF Incognito mode:
Blazor application load takes about 22 seconds.
Login process takes about 20 seconds.

Loading in application is then fast and UI responsive as it should be.

**Comment by leonkosak** [comment]
Redis server is working. I made a shutdown and application did not work (after enabling Redis server, application starts working).
Currently only warnings are about SameSite and I will apply this patch. But I am sure that this warning does not result in such long loading and login times (22+20 seconds).
@hikalkan do you have any suggestions?

**Comment by maliming** [comment]
@leonkosak
Can you share your docker file? I want to try to reproduce it in chrome.

**Comment by leonkosak** [comment]
I'll send you whole configuration (including for docker) with sensitive data.
Please tell me your email. Thank you.

**Comment by maliming** [comment]
hi

This will complicate the problem, we need a simple project to reproduce the problem. ：）

**Comment by leonkosak** [comment]
I won't send you concrete project, because it's almost "empty" abp.
Docker configuration (overrides) for appsettings.json and "translating" from docker internal urls to external (internet) urls.
Therefore I want to send you privately.

**Comment by maliming** [comment]
ok, liming.ma@volosoft.com

**Comment by maliming** [comment]
liming.ma@volosoft.com

**Comment by leonkosak** [comment]
Resolved after updated code for extensions: https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n

P.S.: @ebicoglu please add updated date info. Thank you.
