### ISSUE TITLE
Add en-GB language json files - English (UK)

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#6933]
I've created en-GB json files (English (UK)) for all modules/packages etc. using your recommended method i.e.

Clone the ABP repository from Github.
Install the ABP CLI if you haven't installed before.
Run abp translate -c <culture-name> command for your language in the root folder of the abp repository. For example, use abp translate -c fr for French. Check this document to find the culture code for your language.
This command creates a file in the same folder, named abp-translation.json. Open this file in your favorite editor and fill the missing text values.
Once you done the translation, use abp translate -a command to apply changes to the related files.
Send a pull request on GitHub.

The problem is that when I try and push and create pull request I get an access denied message- BTW I'm using GitKraken

**Comment by maliming** [comment]
hi @DonVliet 

You need fork abp repository.
