### ISSUE TITLE
Component Replacement and Page Toolbar Extensions causes error in Angular

### ISSUE THREAD

**Issue by mtozlu** [abpframework/abp#6940]
In 4.1.0-rc2, using extended object in Angular, causes errors if a component is replaced following the [component replacement](https://docs.abp.io/en/abp/4.1/UI/Angular/Component-Replacement#how-to-replace-a-component) docs.

For example, after replacing the `UsersComponent` and clicking "New User" button in the UI causes error because [default toolbar actions](https://github.com/abpframework/abp/blob/cbe58e3ef379d468248fb1279c7df3a45b954d63/npm/ng-packs/packages/identity/src/lib/defaults/default-users-toolbar-actions.ts#L9) get injected `UsersComponent` of identity package which is not registered in DI (as it is replaced). So one has to manually modify toolbar actions like so;

```typescript
export function appIdentityToolbarActionsContributor(actionList: ToolbarActionList<IdentityUserDto[]>) {
  // remove default action
  actionList.dropByValue(
    'AbpIdentity::NewUser',
    (value: ToolbarAction<IdentityUserDto[]>, text) => value.text === text,
  );

  // add action with replaced component
  const action = ToolbarAction.createMany<IdentityUserDto[]>([
    {
      text: 'AbpIdentity::NewUser',
      action: data => {
        const component = data.getInjected(ReplacedUsersComponent);
        component.add();
      },
      permission: 'AbpIdentity.Users.Create',
      icon: 'fa fa-plus',
    },
  ]);
  actionList.addManyTail(action);
}
```
Same thing goes for entity action extensions (edit, delete) too. 

So either the component replacement documentation should be updated to include this information or default actions should find a way to get replaced component by default.

**Comment by hemaltandel1** [comment]
@mtozlu i also stuck on same issue with tenant management component. 

Also having similar issue with "abp-extensible-form" control but not able to resolve it yet. It's throwing below error and i have replaced "TenantManagement.TenantsComponent" it with new control and trying to use "abp-extensible-form" for "#tenantModalTemplate" same as it's being used on original "TenantComponent".

![image](https://user-images.githubusercontent.com/22088585/108603160-4e2e7480-7374-11eb-96ba-c6b902c7df3b.png)


@hikalkan Is there is way to replace default action items with new component?

**Comment by mehmet-erim** [comment]
Hi
Sorry for the late response.

We have created a document titled [How Replaceable Components Work with Extensions](https://docs.abp.io/en/abp/latest/UI/Angular/How-Replaceable-Components-Work-with-Extensions). You can find the solution in this document.
