### ISSUE TITLE
EF Core Eager loading related entities with default generic repository does not work.

### ISSUE THREAD

**Issue by tsupakit** [abpframework/abp#6954]
Hi abp team, 
I was trying to follow the documentation of Entity Framework Core [Eager Loading / Load With Details](https://docs.abp.io/en/abp/latest/Entity-Framework-Core#eager-loading-load-with-details).
Unfortunately, it seems did not work at all.
My entities were designed and configured almost the same as in the [example](https://docs.abp.io/en/abp/latest/Entity-Framework-Core#loading-related-entities)
As it states in the documentation that

> GetAsync and FindAsync gets includeDetails with default value is true.

The result that I got from both methods was not include my related entity.
I even tried explicitly pass parameter `includeDetails: true` also did not work.
My workaround was to create a custom repository and use the Include() of entity framework.

ABP CLI : 4.0.2
Database Provider : EF Core

**Comment by realLiangshiwei** [comment]
Do create a IncludeDetails extension method for the IQueryable<TEntity> for each aggregate root which has sub collections

See https://docs.abp.io/en/abp/latest/Best-Practices/Entity-Framework-Core-Integration#repository-implementation

**Comment by tsupakit** [comment]
@realLiangshiwei Thanks for a suggestion.
Does this mean to use this feature of the default generic repository we also need to implement extension method explicitly?

**Comment by realLiangshiwei** [comment]
Yes. All modules of ABP do this. https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.EntityFrameworkCore/Volo/Abp/Identity/EntityFrameworkCore/IdentityDbContextModelBuilderExtensions.cs
