### ISSUE TITLE
Angular :  configState.getOne$('currentUser') return null values for Name and surName

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#6956]
Hello,

Abp v4.0.2 ( tiered arch).

i'm trying to get the user surName and  name with : 

```
 configState.getOne$('currentUser') 
```
knowing that i updated the user profile, the getOne$('currentUser') always return null for  surName and  Name, phoneNumber works fine.

![image](https://user-images.githubusercontent.com/5918026/103455793-624ce280-4cf0-11eb-8083-0aee2d337864.png)

![image](https://user-images.githubusercontent.com/5918026/103455826-b9eb4e00-4cf0-11eb-8905-70bb7ffbc44c.png)

Any help please.

**Comment by hexianggui** [comment]
How do you solve it?I have the same problem

**Comment by aelhadi** [comment]
> How do you solve it?I have the same problem

ngOnInit(): void
    {
        this.currentUser$.subscribe( data =>this.userid = data.id);
        this.userIdentity = this._identityService.get(this.userid);

        this.userIdentity
            .pipe(takeUntil(this._unsubscribeAll))
            .subscribe(data => {
                console.log(data.name);
                console.log(data.extraProperties);
            });
    }


don't forget  : 
import {IdentityUserService, IdentityUserDto} from '@abp/ng.identity';

declare =====>
userIdentity: Observable<IdentityUserDto>;


and in the constructor : 

private _identityService: IdentityUserService,
