### ISSUE TITLE
How to use Localization in Component view

### ISSUE THREAD

**Issue by ugurozturk** [abpframework/abp#697]
Hi,

I can't use L["blabla"] in the Component view because can't implement it on the component.

Example Senario : 

There is alot of List objects. And a lot of them using foreach. 

https://github.com/abpframework/abp/blob/master/modules/blogging/src/Volo.Blogging.Web/Pages/Blog/Posts/Detail.cshtml

I did make components each of them. Yet can't implement the Localization. Needs like this : https://github.com/abpframework/abp/blob/master/modules/blogging/src/Volo.Blogging.Web/Pages/Blog/Posts/Detail.cshtml#L147

**Comment by hikalkan** [comment]
Inject `IHtmlLocalizer<T>` or `IStringLocalizer<T>` for your resource.

**Comment by ugurozturk** [comment]
Thank you
