### ISSUE TITLE
Article Request:  DevExpress Reporting and Dashboard Integrations into Abp.io

### ISSUE THREAD

**Issue by davidcateduclarity** [abpframework/abp#6977]
Greetings;
Thank you so much for your existing articles.  They are a vast improvement over previous frameworks.

Could you please provide documentation on integrating devexpress reporting and dashboards into the abp.io framework.

**Reporting:**
ASPNetCore: [AspNet Core Docuemtation](https://docs.devexpress.com/XtraReports/119717/web-reporting/aspnet-core-reporting)
Angular: [Angular Documentation](https://docs.devexpress.com/XtraReports/401914/web-reporting/javascript-reporting/angular)

**Dashboards:**

ASPNetCore:  [AspNet Core Documentation](https://docs.devexpress.com/XtraReports/119717/web-reporting/aspnet-core-reporting)
Angular:  [Angular Documentation](https://docs.devexpress.com/XtraReports/401914/web-reporting/javascript-reporting/angular)

Many thanks,

--Dave

**Comment by leonkosak** [comment]
**Reporting:**
Blazor: [Blazor Documentation](https://docs.devexpress.com/XtraReports/401676/web-reporting/blazor-reporting)

**Comment by hikalkan** [comment]
Thanks @davidcateduclarity for your article request 👍

**Comment by AnthonyHuang** [comment]
I am craving for this article too. Thank you for submitting the request.

**Comment by BarisGurbuz** [comment]
Yes please

**Comment by steves-bits** [comment]
+1

**Comment by leonkosak** [comment]
@hikalkan what about DevExpress Dashboard?
