### ISSUE TITLE
Build error [Module BackgroundJobs]

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#698]
> DemoAppHangfireModule.cs(21,33): error CS0104: 'ConfigurationHelper' is an ambiguous reference between 'Microsoft.Extensions.Configuration.ConfigurationHelper' and 'Volo.
> Abp.BackgroundJobs.DemoApp.Shared.ConfigurationHelper'

http://ci.volosoft.com:5480/blue/organizations/jenkins/abp/detail/abp/591/pipeline#step-19-log-593

**Comment by hikalkan** [comment]
We should change the naming. Thanks @hitaspdotnet
