### ISSUE TITLE
Can't create custom repository

### ISSUE THREAD

**Issue by velikayikci** [abpframework/abp#6983]
Hello,
can not create custom repository width custom entity, here is my code, what is the wrong ?

### IWorkflowRepository

    public interface IWorkflowRepository<TEntity> : IRepository<TEntity>
        where TEntity : class, IEntity
    {
    }

    public interface IWorkflowRepository<TEntity, TKey> : IRepository<TEntity, TKey>
        where TEntity : class, IEntity<TKey>
    { 
    }

### WorkflowRepository

    public class WorkflowRepository<TEntity> : EfCoreRepository<VekaDbContext, TEntity>, IWorkflowRepository<TEntity>
      where TEntity : class, IEntity
    {
        public WorkflowRepository(IDbContextProvider<VekaDbContext> dbContextProvider)
            : base(dbContextProvider)
        {
        }
    }

    public class WorkflowRepository<TEntity, TKey> : EfCoreRepository<VekaDbContext, TEntity, TKey>, IWorkflowRepository<TEntity, TKey>
        where TEntity : class, IEntity<TKey>
    {
        public WorkflowRepository(IDbContextProvider<VekaDbContext> dbContextProvider)
            : base(dbContextProvider)
        {
        }
    }

### WorkflowEntity
    [Serializable]
    public abstract class WorkflowEntity : AuditedAggregateRoot
    {
        public virtual Guid WorkflowProcessId { get; set; }
    }

    [Serializable]
    public abstract class WorkflowEntity<TKey> : AuditedAggregateRoot<TKey>
    {
        protected WorkflowEntity()
        {
        }

        protected WorkflowEntity(TKey id)
            : base(id)
        {
        }

        public virtual Guid WorkflowProcessId { get; set; }
    }

### VekaDbContext 
    public class VekaDbContext : AbpDbContext<VekaDbContext>
    {
        public DbSet<AppUser> Users { get; set; }
        public DbSet<CustomerDefinition> CustomerDefinitions { get; set; }
   

### VekaApplicationAutoMapperProfile
    public class VekaApplicationAutoMapperProfile : Profile
    {
        public VekaApplicationAutoMapperProfile()
        {
            CreateMap<CustomerDefinition, CustomerDefinitionModel>();
            CreateMap<CustomerDefinitionModel, CustomerDefinition>();
        }
    }

### CustomerDefinition
    public class CustomerDefinition : WorkflowEntity<Int32>
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Age { get; set; }
    }

### CustomerDefinitionService 
    public class CustomerDefinitionService : ApplicationService
    {
        public readonly IWorkflowRepository<CustomerDefinition, Int32> CustomerDefinitionRepository;

        public CustomerDefinitionService(IWorkflowRepository<CustomerDefinition, Int32> customerDefinitionRepository)
        {
            CustomerDefinitionRepository = customerDefinitionRepository;
        }

        public async Task<List<CustomerDefinitionModel>> GetAllAsync()
        {
            List<CustomerDefinition> items = await CustomerDefinitionRepository.GetListAsync();
            return ObjectMapper.Map<List<CustomerDefinition>, List<CustomerDefinitionModel>>(items);
        }
    }

<img width="1060" alt="repository" src="https://user-images.githubusercontent.com/25893525/103489698-4566fb00-4e27-11eb-8716-a3dff14aab31.PNG">

**Comment by maliming** [comment]
I think you should manually register the generic interface `IWorkflowRepository` into the DI container.

**Comment by velikayikci** [comment]
> I think you should manually register the generic interface `IWorkflowRepository` into the DI container.

Thank you for your answer.
How can do it ? is there any example code ?

**Comment by maliming** [comment]
You can try to add below to your module's `ConfigureServices` method:

```cs
context.Services.AddTransient(typeof(IWorkflowRepository<>), typeof(WorkflowRepository<>));
context.Services.AddTransient(typeof(IWorkflowRepository<,>), typeof(WorkflowRepository<,>));
```

**Comment by velikayikci** [comment]
You are the best. It's works.
Thank you very much.
