### ISSUE TITLE
Creating a new user via the API does not save the name and surname when using MongoDB

### ISSUE THREAD

**Issue by michaelsudnik** [abpframework/abp#7000]
Missing

`(await UserManager.UpdateAsync(user)).CheckErrors();`

after MapExtraPropertiesTo call

https://github.com/abpframework/abp/blob/45ac9e8a2ece2a281ae4acf888137ff9c213ce9b/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L87

I have seen (and reported) this kind of explicit "update" call missed in other places, so it might be a good idea to do a quick check for similar problems.

**Comment by michaelsudnik** [comment]
Previously reported examples:
https://support.abp.io/QA/Questions/696/Custom-role-claims-not-saving
https://support.abp.io/QA/Questions/628/Moving-an-Organization-Unit-to-a-different-parent-by-drag-drop-does-not-work

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/7004
