### ISSUE TITLE
SameSite issue (http) for tiered solution

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#7012]
https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n

In which projects exactly should Step-1 be applied when we have tiered Blazor application? There is no .Web project. Just .HttpApi.Host and .IdentityServer.
Thank you.

**Comment by maliming** [comment]
Did you get the same problem with your blazor app?

**Comment by leonkosak** [comment]
Yes. I have abp with Blazor IU and tiered backend.

**Comment by maliming** [comment]
I will check it, I thought only mvc have this problem.
