### ISSUE TITLE
Display TimeSpan type Data in typescript

### ISSUE THREAD

**Issue by slm-w** [abpframework/abp#7015]
Trying to show time in table but it shows me time in this format `{ "ticks": 690680000000, "days": 0, "hours": 19, "milliseconds": 0, "minutes": 11, "seconds": 8, "totalDays": 0.7993981481481481, "totalHours": 19.185555555555556, "totalMilliseconds": 69068000, "totalMinutes": 1151.1333333333334, "totalSeconds": 69068 }` while i want it to be displayed in this format `10:15:30` 

i use abp framework angular for frontend asp.net core for  backend 

HTML
```
<ng-container matColumnDef="debutJour">
    <th mat-header-cell *matHeaderCellDef mat-sort-header>
      {{'::DebutJour' | abpLocalization}}
    </th>
    <td mat-cell *matCellDef="let element">
      {{ element.debutJour|json }}
    </td>
  </ng-container>
  <ng-container matColumnDef="duree">
    <th mat-header-cell *matHeaderCellDef mat-sort-header>
      {{'::Duree' | abpLocalization}}
    </th>
    <td mat-cell *matCellDef="let element">
      {{ element.duree|json }}
    </td>
  </ng-container>
```

**Comment by maliming** [comment]
https://stackoverflow.com/questions/65569529/display-timespan-type-data-in-typescript
