### ISSUE TITLE
Culture-specific number formats with Volo.Abp.TextTemplating

### ISSUE THREAD

**Issue by axunonb** [abpframework/abp#7025]
### Issue

Rendering a decimal number (e.g. 123,45) with the culture name "de", the text should be ```123,45``` (with decimal comma), but it is ```123.45``` (with decimal point).

### Reproduce

Use the abp-samples/TextTemplateDemo/Demos/Hello/, update package to v4.0.2 and modify
* **Hello.tpl** to ```Hello {{model.name}} {{model.amount}}```
* **HelloModel.cs** to
```
public class HelloModel
{
    public string Name { get; set; }
    public decimal Amount { get; set; }
}
```
* **HelloDemo.cs** with
```
public async Task RunAsync()
{
    var result = await _templateRenderer.RenderAsync(
        "Hello", //the template name
        new HelloModel
        {
            Name = "John",
            Amount = 12.34M
        }, "de"
    );
    Console.WriteLine(result);
}
```
### Proposed solution:
In [TemplateRenderer](https://github.com/abpframework/abp/blob/6a228483aef667d4590eea00a57bff5a0f30a9ef/framework/src/Volo.Abp.TextTemplating/Volo/Abp/TextTemplating/TemplateRenderer.cs#L124).CreateScribanTemplateContext add
```context.PushCulture(CultureInfo.CurrentCulture);```
in order to reflect the culture previously set before [rendering the template with Scriban](https://github.com/abpframework/abp/blob/6a228483aef667d4590eea00a57bff5a0f30a9ef/framework/src/Volo.Abp.TextTemplating/Volo/Abp/TextTemplating/TemplateRenderer.cs#L107).

Would you accept a PR with this solution?

**Comment by maliming** [comment]
hi

We welcome you to contribute code.  https://docs.abp.io/en/abp/latest/Contribution/Index
