### ISSUE TITLE
Build error [Tenant Management]

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#704]
https://github.com/abpframework/abp/commit/947de079e265785064a116276c87128a1de16bf6

> Error	CS1061	'IMemberConfigurationExpression<Tenant, TenantInfo, object>' does not contain a definition for 'ResolveUsing' and no accessible extension method 'ResolveUsing' accepting a first argument of type 'IMemberConfigurationExpression<Tenant, TenantInfo, object>' could be found (are you missing a using directive or an assembly reference?)
>

**Comment by hitaspdotnet** [comment]
http://docs.automapper.org/en/stable/8.0-Upgrade-Guide.html

**Comment by hikalkan** [comment]
Thanks @hitaspdotnet for reporting and providing the fix.

**Comment by hitaspdotnet** [comment]
@hikalkan your welcome. It is an honor. But I could not understand the reason for not accepting PR. :eyes:

**Comment by hikalkan** [comment]
I haven't seen your PR. Can you send a link?

**Comment by hitaspdotnet** [comment]
It's ok. I thought that I was doing something wrong and wanted to correct it in the future.
https://github.com/abpframework/abp/pull/705
