### ISSUE TITLE
How can i show my *AppService, DTO's XML comments in swagger?

### ISSUE THREAD

**Issue by fermanquliyev** [abpframework/abp#7048]
How can I show my *AppService, DTO's XML comments in swagger?
I have written XML comments above my app service methods (which will be converted to the controllers) but it doesn't show itself on UI.
```
var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                options.IncludeXmlComments(xmlPath);
```

**Comment by maliming** [comment]
I think this has nothing to do with abp? Do your controller coments works?

**Comment by fermanquliyev** [comment]
No. Neither controller's, nor service's XML comments are visible on swagger UI.
```
/// summary
        /// Get attachment by id
        /// summary
        /// param name="id">Id of attachment<param
        [Route("api/[controller]/[action]")]
        [HttpGet]
        [DisableAuditing]
        public async Task<ActionResult> GetAttachment(Guid id)
        {
        }
```
![image](https://user-images.githubusercontent.com/33841624/103752688-76ac1a80-5023-11eb-95b4-858929ceb16d.png)

**Comment by maliming** [comment]
So this has nothing to do with abp.
