### ISSUE TITLE
Identity Role Property "IsPublic" mean?

### ISSUE THREAD

**Issue by LFDCC** [abpframework/abp#7060]
I've removed "IsPublic" from the role, but other users can still see the role, and when you create a new user, you can assign the newly created role, so what does "IsPublic" mean?

**Comment by maliming** [comment]
It seems that `IsPublic` feature has not yet been implemented.

**Comment by realLiangshiwei** [comment]
See https://support.abp.io/QA/Questions/599/Admin-Role-Public#answer-44d1d7c1-84d6-1a0b-8dbd-39f9160fcafb
