### ISSUE TITLE
ApiController HttpGet with a named action parameter auto set value

### ISSUE THREAD

**Issue by LFeYls** [abpframework/abp#7061]
I implement the IdentitySecurityLog api refer to the official case 

public class IdentitySecurityLogController : AbpController , ISecurityLogAppService
    {
        
        protected ISecurityLogAppService SecurityLogAppService { get; }
        
        public IdentitySecurityLogController(ISecurityLogAppService securityLogAppService)
        {
              SecurityLogAppService = securityLogAppService;
        }

        [HttpGet]
        [Route("")]
        public virtual Task<PagedResultDto<IdentitySecurityLogDto>> GetListAsync(GetIdentitySecurityLogInput input)
        {
            return SecurityLogAppService .GetListAsync(input);
        }

   ==== input  parameter ====
    public class GetIdentitySecurityLogInput : PagedAndSortedResultRequestDto
    {
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public string ApplicationName { get; set; }
        public string Identity { get; set; }

        //this property will auto set to "GetList"
        public string Action { get; set; } 

        public Guid? UserId { get; set; }
        public string UserName { get; set; }
        public string ClientId { get; set; }
        public string CorrelationId { get; set; }
    }

No matter what value I set, this property is automatically assigned to "GetList" .
but official case is normal , how to solve the problem

**Comment by realLiangshiwei** [comment]
Try:

```csharp
[HttpGet]
[Route("")]
public virtual Task<PagedResultDto<IdentitySecurityLogDto>> GetListAsync([FromQuery]GetIdentitySecurityLogInput input)
{
    return SecurityLogAppService .GetListAsync(input);
}
```

**Comment by LFeYls** [comment]
@realLiangshiwei thanks, it's worked.
