### ISSUE TITLE
building a configuration center

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#7065]
Will you consider building a configuration center?
Configuration center like [apolloConfigurationSystem](https://github.com/ctripcorp/apollo)
There are too many services now, causing trouble to maintain appsetting.json

**Comment by real-zony** [comment]
Hi xewn,
You can easily use [Com.Ctrip.Framework.Apollo.Configuration](https://www.nuget.org/packages/Com.Ctrip.Framework.Apollo.Configuration/) to integrate apollo configuration center, as far as I know, currently abp does not have this plan.
