### ISSUE TITLE
How to add a identityUser foreign key to an entity

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#7099]
Simple question, how do you add a  identityUser foreign key relationship to a custom entity (database table). 
**_Note: this is not a question about extending the user properties._**      
      
      Public Class MyTable : Entity<int> {
          public Guid UserID {get; set;}  // this is a foreign key to the identityUser table
      }

**Comment by NecatiMeral** [comment]
I think this isn't related to ABP but EntityFramework (core).

You should add the foreign key by using the following convention (not tested):
```csharp
modelBuilder.Entity<MyTable>()
     .HasOne<IdentityUser>()
     .WithMany()
     .HasForeignKey(myTable => myTable.UserID);
```

**Comment by rygar08** [comment]
Thank you. The correct answer for my issue was to use Volo.Abp.Identity.IdentityUser not Microsoft.AspNetCore.Identity

modelBuilder.Entity<MyTable>()
     .HasOne<**Volo.Abp.Identity.IdentityUser**>()
     .WithMany()
     .HasForeignKey(myTable => myTable.UserID);

**Comment by rygar08** [comment]
After adding the above foreignKey relationship I now get this error when inserting the entity. 


      The entity type 'IdentityUserLogin' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()



So it looks like you can't add Volo.Abp.Identity.IdentityUser foreignKey relationship. ABP this is fundamental stuff, your documentation needs improvement.
