### ISSUE TITLE
How to add a IdentityUser foreign key to an entity?

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#7105]
How do you add a identityUser foreign key relationship to a custom entity (database table)? I have a 'MyTable' Entity with a foreign key relationship to Volo.Abp.Identity.IdentityUser (the AbpUsers database table)

    Public Class MyTable : Entity<int> {
        public Guid UserID {get; set;}  // this is a foreign key to the identityUser table
    }

In the EntityframeworkCore project in the ...ModelCreatingExtensions.cs

    builder.Entity<MyTable>(b =>
            {
                b.ToTable("MyTable", DbSchema);
                b.ConfigureByConvention();  

                b.HasOne<Volo.Abp.Identity.IdentityUser>().WithMany().HasForeignKey(m=> m.UserID);
            });

When I try to seed the 'MyTable' entity I get an error.

     var user = new IdentityUser(guidGenerator.Create(), "user", "user@demo.com", context.TenantId);
     await userManager.CreateAsync(user, "1q2w3E*"); 
     await myTableRepo.InsertAsync(new MyTable { UserId = user.Id }, true);

I get this error

    System.InvalidOperationException: 'The entity type 'IdentityUserLogin' requires a primary key to be defined. If you intended to use a keyless entity type call 'HasNoKey()'.'

**Comment by realLiangshiwei** [comment]
Try:

Entity:

```csharp
public class MyEntity : Entity<Guid>
{
    public Guid UserId { get; set; }

    public string Title { get; set; }
}
```

DbContextModelCreatingExtensions:

```csharp
builder.Entity<MyEntity>(b =>
{
    b.ConfigureByConvention();
});
```

MyProjectNameDbContext:

```csharp
builder.Entity<MyEntity>(b =>
{
    b.HasOne<AppUser>().WithMany().HasForeignKey(x => x.UserId);
});
```

MyProjectNameMigrationsDbContext:

```csharp
builder.Entity<MyEntity>(b =>
{
    b.HasOne<IdentityUser>().WithMany().HasForeignKey(x => x.UserId);
});
```

**Comment by rygar08** [comment]
Thanks, this worked with a few modifications. Why do you need to add the foreignKey relationship in the DBContext and MigrationsDbContext?

MyProjectNameDbContextModelCreatingExtensions:
  
    builder.Entity<MyEntity>(b =>
    {
        b.ConfigureByConvention();
        b.HasOne<Volo.Abp.Identity.IdentityUser>().WithMany().HasForeignKey(x => x.UserId);
    });

MyProjectNameMigrationsDbContext:

      builder.Entity<MyEntity>(b =>
      {
          b.HasOne<Volo.Abp.Identity.IdentityUser>().WithMany().HasForeignKey(x => x.UserId);
      });

**Comment by ktngoykalolo** [comment]
Hi,
tried your approach but getting the below error when trying to generate the migration:


The property 'AppUser.ExtraProperties' could not be mapped because it is of type 'ExtraPropertyDictionary', which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

**Comment by ktngoykalolo** [comment]
hi,
tried this code snippets and it worked.

**Comment by OldKing-lion** [comment]
It does not work for me

> Try:
> 
> Entity:
> 
> ```cs
> public class MyEntity : Entity<Guid>
> {
>     public Guid UserId { get; set; }
> 
>     public string Title { get; set; }
> }
> ```
> 
> DbContextModelCreatingExtensions:
> 
> ```cs
> builder.Entity<MyEntity>(b =>
> {
>     b.ConfigureByConvention();
> });
> ```
> 
> MyProjectNameDbContext:
> 
> ```cs
> builder.Entity<MyEntity>(b =>
> {
>     b.HasOne<AppUser>().WithMany().HasForeignKey(x => x.UserId);
> });
> ```
> 
> MyProjectNameMigrationsDbContext:
> 
> ```cs
> builder.Entity<MyEntity>(b =>
> {
>     b.HasOne<IdentityUser>().WithMany().HasForeignKey(x => x.UserId);
> });
> ```
