### ISSUE TITLE
Wrong UseAbpSwaggerUI implementation

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#7107]
* Your **ABP Framework version** 4.1

If i deploy ABP project under IIS subfolder like (https://demo.domain.si/test) swagger UI is not working.

I think AbpSwaggerUIBuilderExtensions.UseAbpSwaggerUI is wrong:

```
return app.UseSwaggerUI(options =>
            {
                options.InjectJavascript("/swagger/ui/abp.js");
                options.InjectJavascript("/swagger/ui/abp.swagger.js");
                options.IndexStream = () => resolver.Resolver();

                setupAction?.Invoke(options);
            });

```

Right implementation should be 

```
                options.InjectJavascript("../swagger/ui/abp.js");
                options.InjectJavascript("../swagger/ui/abp.swagger.js");

```
or better

```
                options.InjectJavascript("ui/abp.js");
                options.InjectJavascript("ui/abp.swagger.js");

```
Look at  [HTML definitions](https://www.w3schools.com/html/html_filepaths.asp). js files should be pointed relatively to folder not current page.

**Comment by realLiangshiwei** [comment]
Thanks @sebitsi
