### ISSUE TITLE
mysql update-database error

### ISSUE THREAD

**Issue by birdlll** [abpframework/abp#711]
use mysql database update-database error:
### The 'MySQLBinaryTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.
_MySql.Data.EntityFrameworkCore_ is not support value conversions in EF Core

**Comment by maliming** [comment]
@birdlll 
Have you deleted all the migrations and added them again?

**Comment by birdlll** [comment]
@maliming again ,can not yet
