### ISSUE TITLE
 'Keyword not supported: trusted_connection (Parameter 'keyword')'

### ISSUE THREAD

**Issue by tayfunuyar** [abpframework/abp#7111]
I get this error when I use Postgresql.
can you help me ? 
![image](https://user-images.githubusercontent.com/27923376/104111343-cb84b500-52f1-11eb-87e9-666d720fa529.png)

**Comment by maliming** [comment]
You may need to change the default connection string.
https://github.com/abpframework/abp/blob/20a13d8f9b/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/appsettings.json#L6
https://github.com/abpframework/abp/blob/20a13d8f9b/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.DbMigrator/appsettings.json#L3

**Comment by tayfunuyar** [comment]
Thank you @maliming I solve problem.
