### ISSUE TITLE
is possible seperated  tenant with schema  in postgresql ?

### ISSUE THREAD

**Issue by tayfunuyar** [abpframework/abp#7112]

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)

**Comment by tayfunuyar** [comment]
I use EF Core. I want to share tenant with schema.  Same database multiple schema for every tenant . 
![image](https://user-images.githubusercontent.com/27923376/104155966-45539600-53f9-11eb-88ae-1d04245d0b5c.png)

**Comment by maliming** [comment]
If EF Core's DbContext supports to change the scheme at runtime, it may achieve your needs.

**Comment by tayfunuyar** [comment]
Thank you I will try. @maliming
