### ISSUE TITLE
mongodb project template

### ISSUE THREAD

**Issue by dolphinsd** [abpframework/abp#713]
When using https://abp.io/Templates to create mongodb based project, the project created with no mongodb database objects defined and does not run.

**Comment by hikalkan** [comment]
I've just tested and it's working properly. Are you trying the "application template", right?

**Comment by hitaspdotnet** [comment]
@hikalkan I thinks he's problem is about Test projects. They have referencing to EntityFramework which isn't existed. 
https://github.com/abpframework/abp/blob/49901a76397308e7acbdc9819cd63e33f18b3b4a/templates/mvc/test/MyCompanyName.MyProjectName.Application.Tests/MyCompanyName.MyProjectName.Application.Tests.csproj#L10

**Comment by hikalkan** [comment]
Actually, the downloaded solution has no reference to these projects:

![image](https://user-images.githubusercontent.com/1210527/50774134-b78dbf00-12a3-11e9-983e-a39c42490569.png)

test folder is empty if you select mongodb. It's included in the zip file by mistake.  Anyway, I created an issue to make tests working for mongodb too: https://github.com/abpframework/abp/issues/718

**Comment by dolphinsd** [comment]
@hikalkan I used https://abp.io/Templates to create a project. I just did again.
See images attached and project, mvc version has object mappings.
![d6b0bc4032a3a85a4b71c762fd7ac767](https://user-images.githubusercontent.com/3460517/51281034-1f27c680-1996-11e9-88f8-4c4a5029e8e3.png)
[Test.zip](https://github.com/abpframework/abp/files/2766215/Test.zip)
![9906986325011f53008df33cf2eb7e12](https://user-images.githubusercontent.com/3460517/51281035-1fc05d00-1996-11e9-8a2e-fa13dfd0ef4d.png)

**Comment by yekalkan** [comment]
hi @dolphinsd 

![image](https://user-images.githubusercontent.com/5793291/51473270-fedc7b00-1d8c-11e9-80c6-4ce83f6d495e.png)

I've built your project. There is no warning or error. Am i missing something?

**Comment by hikalkan** [comment]
Could not reproduce

**Comment by dolphinsd** [comment]
@hikalkan , i did not see any mongo objects definitions, even it compiles, it does nothing as no objects are defined.

**Comment by hikalkan** [comment]
>i did not see any mongo objects definitions
Didn't understand. What mongo objects? When you start the application, a seed data inserted to the database related to users, roles and permissions. Can't you see it (you can check with MongoDB Compass)?

**Comment by devjaw** [comment]
@hikalkan i just start the application and then tried to login with admin user but it's not working. i also checked the MongoDB Compass but there are no data. However, i registered as a new user in the application and it is working fine but without any roles.

**Comment by yekalkan** [comment]
@devjaw have you run *.DbMigrator project?

**Comment by devjaw** [comment]
@yekalkan it works now !
thank you

**Comment by pascalfossouo** [comment]
Hi, I have this error when running the .DBMigrator

Unhandled exception. Autofac.Core.DependencyResolutionException: An exception was thrown while activating Volo.Abp.Identity.IdentityDataSeedContributor -> Volo.Abp.Identity.IdentityDataSeeder -> Castle.Proxies.IdentityUserManagerProxy.

"ConnectionStrings": {
"Default": "mongodb://localhost:27017/BookStore"
},
