### ISSUE TITLE
Issues with Hangfire after 4.1.0

### ISSUE THREAD

**Issue by lukebooroo** [abpframework/abp#7147]
Volo.Abp.BackgroundJobs.HangFire

Since updating to 4.1.0 from 4.0.2. I'm getting an issue where there seems to be no scope and there's no access to injected dependencies.

![image](https://user-images.githubusercontent.com/3911526/104219367-ea8c5f80-5435-11eb-8390-583861bdb2fc.png)

**Comment by maliming** [comment]
Do not use `async void`, You can consider using `AsyncBackgroundJob`.

![image](https://user-images.githubusercontent.com/6908465/104256141-9628c480-54b5-11eb-84b3-0fa81f2d0d0e.png)

**Comment by lukebooroo** [comment]
Thanks for that, seems to have done the trick!
