### ISSUE TITLE
Feature - Consul integration for remote services

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#7149]
Hi,

I would like to discuss the idea behind a consul integration to retreive remote services configuration from consul.
The idea behind this is a more flexible system for the `Volo.Abp.Http.Client` library to get remote service configuration on runtime.

My first thoughts are:
- Create a `Volo.Abp.AspNetCore.Mvc.Consul` package (registering services to consul)
- Create a `Volo.Abp.Http.Client.Consul` package (or `Volo.Abp.Http.Client.ServiceDiscovery.Consul`) (retreive services from consul)
- Use local configuration (as now) when consul integration isn't enabled / ready
- Retreive remote services configuration from consul and apply when requesting remote service interfaces

If this feature makes sense to you, I'll contribute code to implement the changes.
The PR will include changes in `Volo.Abp.Http.Client` and the fresh consul integration package.

EDIT: A alternative would be the use of Ocelot and using it's dynamic routes feature, which already utilizes Consul. This seems like a pretty straight-forward approach without any required changes. I'll investigate this further.

**Comment by slarkerino** [comment]
I think this would help! Currently there is no way to do service discovery for remote services. In my scenarios, if I have multiple internal gateways, I can not do service discovery but only write url in the configuration file.
