### ISSUE TITLE
How to add application an application module when targeting Angular UI

### ISSUE THREAD

**Issue by mfaulcon** [abpframework/abp#7156]
A start-to-finish example of adding a module (i.e. the Docs module) to an ABP solution that targets Angular for the UI, including the steps to integrate the npm packages and any other configuration on that side that needs to be done would be great. Even better would be some form of chart or list of which modules have an available Angular UI component.

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/UI/Angular/Feature-Libraries

**Comment by mfaulcon** [comment]
> See https://docs.abp.io/en/abp/latest/UI/Angular/Feature-Libraries

I tried the instructions on this page with two different modules (docs and blogging). Unfortunately, steps 2 and 3 do not work with these modules.

**Comment by realLiangshiwei** [comment]
Docs and Blogging module does not support angular UI yet. only MVC UI.

**Comment by mfaulcon** [comment]
Is there a list somewhere showing which modules have an angular ui?

 

Mark

**Comment by realLiangshiwei** [comment]
See https://commercial.abp.io/modules
