### ISSUE TITLE
Tenant Setting  Issue

### ISSUE THREAD

**Issue by sailucheng** [abpframework/abp#716]
https://github.com/abpframework/abp/blob/19e745e7623d2239a6a79888425c2092d3435fb5/framework/src/Volo.Abp.MultiTenancy.Abstractions/Volo/Abp/Settings/TenantSettingManagerExtensions.cs#L38

First, sorry for my broken English.
Is there a bug here? We pass null value as current setting provider key , in TenantSettingValueProvider.cs ,It's  directly add  null value to setting store. So we can't distinguish setting in different tenant .no matter current tenant is, it will pass a null value as providerKey.

**Comment by hikalkan** [comment]
You are absolutely right.
