### ISSUE TITLE
AbpUsers open new account same mail.

### ISSUE THREAD

**Issue by tayfunuyar** [abpframework/abp#7173]
Hi, 

I can open more than one user to the AbpUsers table with the same mail.How to disabled it ? 

![image](https://user-images.githubusercontent.com/27923376/104321944-57b2fa00-54f5-11eb-90b1-1dd4ed9d8eca.png)

**Comment by maliming** [comment]
I guess they`TenantId` is different.

**Comment by tayfunuyar** [comment]
Yes but I disabled multitenancy selection.  After disabled multitenancy selection can't login system.

**Comment by maliming** [comment]
This is by design, you should process data after you disable/enable multi-tenancy.
