### ISSUE TITLE
Migrations is missing in EntityFrameworkCore.DbMigrations

### ISSUE THREAD

**Issue by ZouZou** [abpframework/abp#7174]
Hello,

I am downloading a new application 
* ABP version 4.1.
* User Interface is Angular
* EF Core

In order to reproduce the error, all you need to do is install a new project
Run the project dbMigrator and you will get that there is an error, the table "AbpSettings" is missing
in previous projects, there was a folder called Migrations under the project EntityFrameworkCore.DbMigrations; however, in the new solution this folder does not exist which is why we are getting this error

Can you please provide us with a solution?

**Comment by nebula2** [comment]
Same here. Worked around it by simply creating a migration myself by calling
`Add-Migration "chilli_vanilli"` inside the Package Manager Console (Visual Studio)

**Comment by tayfunuyar** [comment]
Your problem with about prefix.
Did you change the prefixes?  @ZouZou

**Comment by ZouZou** [comment]
@tayfunuyar  Can you please be more specific what do you mean by prefix?
Because @maliming deemed this as an issue

**Comment by maliming** [comment]
HI @ZouZou 

You can create the project via CLI for now.

https://abp.io/get-started

![image](https://user-images.githubusercontent.com/6908465/104416233-6c9f9400-55ae-11eb-9a58-e26c9813ead9.png)

**Comment by ZouZou** [comment]
Thank you @maliming

**Comment by yekalkan** [comment]
Hi everyone,

This problem on abp.io/get-started will be fixed in several days. Thanks you for reporting.
