### ISSUE TITLE
Failed to login to swagger as tenant 

### ISSUE THREAD

**Issue by EslamElmadny** [abpframework/abp#7176]
Hello,

I'm using **abpio** version 3.2.1 .net core with angular and ef core (without identity server module).

I'm trying to login to swagger as tenant using `/api/account/login` but it doesn't accept tenantid or name as previous version of abp ..

![image](https://user-images.githubusercontent.com/38657564/104354129-6b6c5980-5511-11eb-8423-6e7330c95151.png)

I've tried to simulate request which taking place when login from ui `/connect/token` with **_tenant** in header (same as request) but the response always is 'Invalid username or password!'

below is postman tries 
![image](https://user-images.githubusercontent.com/38657564/104354324-b5553f80-5511-11eb-8d36-febf8ae9eacb.png)

![image](https://user-images.githubusercontent.com/38657564/104353763-f3059880-5510-11eb-956b-c4250b17d2bd.png)

Please help me to test end points as tenant user :) 

Thanks in advance,
Eslam Adel

**Comment by abdumostafa** [comment]
I have the same issue

**Comment by maliming** [comment]
You can try the latest template project.

**Comment by EslamElmadny** [comment]
Hello, 
I installed latest version which targets .net 5 and I had the same issue ,, there's **no tenant id or name in login api** to login as tenant user from swagger 

For your support please .. 

![image](https://user-images.githubusercontent.com/38657564/105088216-42653f00-5aa4-11eb-91f3-0cb02140f739.png)

**Comment by maliming** [comment]
You need to manually set the **tenant id**

See https://docs.abp.io/en/abp/latest/Multi-Tenancy#determining-the-current-tenant
