### ISSUE TITLE
Remove EF warning logs 'The query uses a row limiting operator'

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#7188]
Since .NET 5, Microsoft has un-obsoleted the [CoreEventId.FirstWithoutOrderByAndFilterWarning](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.coreeventid.firstwithoutorderbyandfilterwarning?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.Diagnostics.CoreEventId.FirstWithoutOrderByAndFilterWarning);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-5.0) and [CoreEventId.RowLimitingOperationWithoutOrderByWarning](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.coreeventid.rowlimitingoperationwithoutorderbywarning?view=efcore-5.0)

I get warning logs like this when using methods like the default `IReadOnlyAppService.GetAsync` method and queries with 
> [WRN][54][Microsoft.EntityFrameworkCore.Query] The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results.

_Note: The log above appears for FirstOrDefault() calls as well as ToList() even though the `CoreEventId.FirstWithoutOrderByAndFilterWarning` warning should be written. I'm not sure why this happens but its probably a bug with EF._

Is there a way to apply something like the  `AbstractKeyReadOnlyAppService.ApplyDefaultSorting` method to the EfCoreRepository for FindAsync calls (and default back to sorting by Entity.Id if CreationTime doesn't exist) or change it to `SingleOrDefaultAsync`?
https://github.com/abpframework/abp/blob/158158e0aba708768657a97490a610aaf46d87d8/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/Domain/Repositories/EntityFrameworkCore/EfCoreRepository.cs#L412

**Comment by realLiangshiwei** [comment]
Thanks, I will check it out.

**Comment by olicooper** [comment]
I've just done some testing and `SingleOrDefault` doesn't change anything, but changing the query to 
`(await WithDetailsAsync()).OrderBy(x => x.Id).FirstOrDefaultAsync` stops the warning appearing. 
~It would be nicer if we could order by `CreationTIme` when possible like `.OrderBy(x => ((Volo.Abp.Auditing.IHasCreationTime)x).CreationTime)`~ ... Actually if we are just searching for a single record by Id then it is probably pointless.

Thanks for looking 👍

**Comment by davidzwa** [comment]
I posted this issue with the same topic. It was closed, but it would be nice to see why.
https://github.com/abpframework/abp/issues/6981

**Comment by maliming** [comment]
hi @davidzwa 

We plan to enhance **GetAsync** to eliminate EF warnings

**Comment by olicooper** [comment]
Sorry @davidzwa I missed that issue! This change should fix the issue when getting a single record from the database via the `EfCoreRepository`, but there will probably be edge cases when getting lists of items that can't be sorted by` Id` or `CreationTime`, so you would have to add the `OrderBy` statement yourself or override the `ApplyDefaultSorting` method shown below.
https://github.com/abpframework/abp/blob/3789b0d2e5fa70aa881fa73e644330baa1968fc8/framework/src/Volo.Abp.Ddd.Application/Volo/Abp/Application/Services/AbstractKeyReadOnlyAppService.cs#L123-L131

**Comment by davidzwa** [comment]
If I understand correctly the best advice is to not use IRepository<TEntity, TKey> directly and fix the OrderBy on application level? So far I was using the repo for seeding.

I can wait for the preview, np ;)

**Comment by olicooper** [comment]
You can override most functionality in the system simply by inheriting the class you want to override, then using `[Dependency(ReplaceServices = true)]` above the class and override the particular function (such as `IRepository.GetAsync`), but you shouldn't need to after this preview release which will probably be released later today. If you do need to though, take a look at this: https://docs.abp.io/en/abp/latest/Dependency-Injection#replace-a-service
