### ISSUE TITLE
Quartz Background Job not serializing Job Args

### ISSUE THREAD

**Issue by angelcalvasp** [abpframework/abp#7189]
### ABP Version

3.3.1

I am using Quartz.net for background jobs management

I am queing a new job like so

``` csharp

await _backgroundJobManager.EnqueueAsync(
                new EcuadorEInvoicingEmailSendingArgs
                {
                    ComprobanteElectronicoId = comprobanteElectronico.Id,
                    TenantId = CurrentTenant.Id.Value
                }
            );

```

but I am getting the following error

Couldn't store job: JobDataMap values must be strings when the 'useProperties' property is set.  Key of offending value: TArgs
Quartz.JobPersistenceException: Couldn't store job: JobDataMap values must be strings when the 'useProperties' property is set.  Key of offending value: TArgs
 ---> System.IO.IOException: JobDataMap values must be strings when the 'useProperties' property is set.  Key of offending value: TArgs

configuration is as follows

``` csharp
PreConfigure<AbpQuartzOptions>(options =>
            {
                options.Configurator = configure =>
                {
                    configure.UsePersistentStore(storeOptions =>
                    {
                        storeOptions.UseProperties = true;
                        storeOptions.UseSqlServer(configuration.GetConnectionString("Default"));
                        storeOptions.UseClustering(c =>
                        {
                            c.CheckinMisfireThreshold = TimeSpan.FromSeconds(20);
                            c.CheckinInterval = TimeSpan.FromSeconds(10);
                        });
                        storeOptions.UseJsonSerializer();
                    });
                };
            });
```

The argument itself is:

``` csharp
    [BackgroundJobName("eInvoicingEcuadoremails")]
    public class EcuadorEInvoicingEmailSendingArgs
    {
        public Guid ComprobanteElectronicoId { get; set; }
        public Guid TenantId { get; set; }
    }
```

I am following what is on the docs, but I seem to be missing something, am I configuring wrong the module? should the argument be annotated with something so that it gets serialized correctly?

**Comment by realLiangshiwei** [comment]
I will check it out

**Comment by realLiangshiwei** [comment]
We have fixed this problem, for now, you can `UseProperties` value to false.
