### ISSUE TITLE
Can format or resolution of datetime typed input in dynamic form be changed? 

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#7196]
ABP Framework version : 4.0.0. 
MVC

Datatype.Datetime input in dynamic form shows seconds and milliseconds. Can we changed this behaviour? Maybe only hour and minutes?

```
[DataType(DataType.DateTime)]
public DateTime FromDate { get; set; } 
```

![date](https://user-images.githubusercontent.com/2400925/104494144-fad74280-55cd-11eb-8e4c-fd0ca8954ef5.png)

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by espindl** [comment]
There is not a lot of details about this, it is only a DateTime field in a dynamic form, but let me try. 
And I did not mean this is a bug, only I cannot find how to achieve a less detailed time in the input.

**Steps:**
1. Create a Razor page and include a dynamic form like 
`<abp-dynamic-form abp-model="MyModel" asp-page="/MyPage/Index" submit-button="true"/>`
2. Add a datetime property to model in the code behind like
`public class ModelX` 
`{`
`[DisplayName("FromDate")]`
`[DataType(DataType.DateTime)]`
`public DateTime FromDate { get; set; } = DateTime.Now.AddDays(-5);`
`}`
3. Define bind property with this ModelX like
`[BindProperty]`
`public ModelX MyModel { get; set; }`
4. Run the application and visit page, click the date input

**Comment by yekalkan** [comment]
Use `[DataType(DataType.Date)]` instead of `[DataType(DataType.DateTime)]`.

**Comment by espindl** [comment]
> Use `[DataType(DataType.Date)]` instead of `[DataType(DataType.DateTime)]`.

Is this for the current version or for 4.3-preview. Because for the current if I do this I only see the date, but I want to see hh:mm also (without sec and milisec)

**Comment by yekalkan** [comment]
This is not related to Abp Framework. But i guess you are looking for:

````
            [DataType(DataType.DateTime)]
            [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd:hh-mm}")]
````
