### ISSUE TITLE
Can't Create  a New Solution

### ISSUE THREAD

**Issue by roupijiaojiaobao** [abpframework/abp#7200]
Hi guys, I'm having trouble creating a project in version 4.1.1。
Downloading either directly or by command will result in an error
![微信截图_20210113173552](https://user-images.githubusercontent.com/64553587/104518704-1b030380-55c6-11eb-8df1-5b9ab62b8db3.png)
![微信截图_20210113173515](https://user-images.githubusercontent.com/64553587/104518706-1b9b9a00-55c6-11eb-9b4d-66eef948e52c.png)

**Comment by roupijiaojiaobao** [comment]
Downloading either directly or by command will result in an error

**Comment by KennyMuffins** [comment]
Same issue faced in 4.1.0, both direct download and cli seems to be having issues at the moment

**Comment by Gitvazonline** [comment]
Also getting this issue

**Comment by maliming** [comment]
We will fix it as soon as possible.

**Comment by roupijiaojiaobao** [comment]
> We will fix it as soon as possible.

Thank you!Have a good day ☕️☕️
