### ISSUE TITLE
Failed download the source code?? https://abp.io/api/download/samples/easy-crm

### ISSUE THREAD

**Issue by 0andy** [abpframework/abp#7201]
![image](https://user-images.githubusercontent.com/3870326/104529315-0e36dd80-55cf-11eb-880d-ef18edcf2b06.png)

**Comment by Gitvazonline** [comment]
Also getting this issue

**Comment by maliming** [comment]
We will fix it as soon as possible。

**Comment by maliming** [comment]
We will fix it as soon as possible.

**Comment by Yomi218** [comment]
I'm waiting...

**Comment by maliming** [comment]
It works now.

**Comment by hiendaoit** [comment]
403

**Comment by EngincanV** [comment]
> 403

You should log in to the website and also have a commercial license.
