### ISSUE TITLE
Blazor Exception

### ISSUE THREAD

**Issue by zfeihong** [abpframework/abp#7204]
my god
![111](https://user-images.githubusercontent.com/20945947/104537608-3ff28780-5655-11eb-9f6b-ccac680cf733.png)

**Comment by realLiangshiwei** [comment]
Can't reproduce this problem

![image](https://user-images.githubusercontent.com/16813853/104538505-f6a33780-5656-11eb-9cb5-5b8bcb8b329a.png)
