### ISSUE TITLE
KafkaMessageConsumer.CreateTopicAsync() is error

### ISSUE THREAD

**Issue by Aprite** [abpframework/abp#7206]
Abp vNext 4.1.1
![微信截图_20210114150835](https://user-images.githubusercontent.com/19543920/104556774-1d736500-567b-11eb-8b38-7247be1dedd9.png)

the reason had changed,maybe~

@realLiangshiwei

**Comment by Aprite** [comment]
e.Error.Reason is
An error occurred creating topics: [{TopicName}]: [Broker: Topic already exists].

**Comment by realLiangshiwei** [comment]
Can't reproduce the problem, can you provide steps to reproduce it?
