### ISSUE TITLE
How to handle Account/AccessDenied?ReturnUrl=%2Ftasks%2Fcreate-task when a user doesn't have access to page

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#7207]
* Your **ABP Framework version** - 4.0.2.
* Your **User Interface** type (Angular/MVC/React... etc.) - MVC
* Your database provider(EF Core/MongoDB) - EF Core
* Steps needed to **reproduce** the problem.

When a user doesn't have permission to create, edit or delete pages the user is redirected to Account/AccessDenied?ReturnUrl=%2Ftasks%2Fcreate-task

How to handle this exception so the user doesn't get a 404 not found page?

![image](https://user-images.githubusercontent.com/15242923/104557255-10636f80-5695-11eb-84f3-6ccfdfadaf66.png)

**Comment by vnetonline** [comment]
@maliming 

Can you explain is this is a bug or not implemented ?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/7215

**Comment by ivanagui2** [comment]
Hi @maliming. I have created a new solution with ABP Framework 4.2.2 and this problem still exists.

**Comment by maliming** [comment]
@ivanagui2  Please create a new issue.
