### ISSUE TITLE
Not Getting container instance and not Global signal instance about IocMainer in AutoFac

### ISSUE THREAD

**Issue by marjezhang** [abpframework/abp#721]
There are not some functions about getting container instance And not Global Signal instance about IocMainer in AutoFac Module.
Or Are there some Global Signal instance about AbpApplication?
Cause  some dll or helper  developed by a third party are needed to set container to their internel for their DI like NServiceBus. Cause It create IHandlerMessage instance by theirself, but i need to use abp in Ihandlemessage
Ortherwise i need to use Global Signal instance IocMainer to get IserviceProvider , but vNext version don't have it like old abp's IocMainer.Instance

**Comment by hikalkan** [comment]
I didn't understand it well, sorry. Could you explain it with more details (and with code samples if possible).
Does IocMainer should be IocManager?

**Comment by marjezhang** [comment]
Yes  It's my words wrong.

**Comment by marjezhang** [comment]
`using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using EventCmdAllData;
using NServiceBus;
using Volo.Abp.DependencyInjection;

namespace OrderAggregate.subscription
{
    public class PlaceOrderCmdHandler : IHandleMessages<PlaceOrderCmd>
    {
        public Task Handle(PlaceOrderCmd message, IMessageHandlerContext context)
        {
            Console.WriteLine("收到下单的PlaceOrderCmd的命令 orderid:" +
                              message.OrderID);

            Console.WriteLine("执行本地订单写入");
            Console.WriteLine("2.发布OrderCreate事件");

            var vEventData = new OrderCreateEventData()
            {
                OrderId = message.OrderID,
                Descript = message.Descript,
                OrderCreateUserName = "quarrier"
            };

            return context.Publish(vEventData);
        }
    }
}`

Like that codes, IHandleMessages is NServiceBus's interface about Subscribe.
But It's instanced by NServiceBus internel option , not be by netCore.
How can I injection IRepository?

**Comment by hikalkan** [comment]
Hi,

We completely rely on Microsoft's Dependeny Injection framework and it does not provide a global IServiceProvider instance. However, you can do it yourself.

1. Create a class like that:

````csharp
public static class GlobalServiceScopeFactory
{
    public static IServiceScopeFactory Instance { get; set; }
}
````

Override `OnApplicationInitialization` in your module:

````csharp
public override void OnApplicationInitialization(ApplicationInitializationContext context)
{
    GlobalServiceScopeFactory.Instance = context.ServiceProvider.GetRequiredService<IServiceScopeFactory>();
}
````

Then, whenever you need to resolve a dependency, use this pattern:

using (var scope = GlobalServiceScopeFactory.Instance.CreateScope())
{
    var repository = scope.ServiceProvider.GetRequiredService<IRepository<Person, int>>();
    //...use repository safely here
}

**Comment by Nokecy** [comment]
@hikalkan use GlobalServiceScopeFactory 
throw  System.ObjectDisposedException : Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.

> Hi,
> 
> We completely rely on Microsoft's Dependeny Injection framework and it does not provide a global IServiceProvider instance. However, you can do it yourself.
> 
> 1. Create a class like that:
> 
> ```cs
> public static class GlobalServiceScopeFactory
> {
>     public static IServiceScopeFactory Instance { get; set; }
> }
> ```
> 
> Override `OnApplicationInitialization` in your module:
> 
> ```cs
> public override void OnApplicationInitialization(ApplicationInitializationContext context)
> {
>     GlobalServiceScopeFactory.Instance = context.ServiceProvider.GetRequiredService<IServiceScopeFactory>();
> }
> ```
> 
> Then, whenever you need to resolve a dependency, use this pattern:
> 
> ```cs
> using (var scope = GlobalServiceScopeFactory.Instance.CreateScope())
> {
>     var repository = scope.ServiceProvider.GetRequiredService<IRepository<Person, int>>();
>     //...use repository safely here
> }
> ```

**Comment by maliming** [comment]
The `IServiceProvider `in `ApplicationInitializationContext `is scope.

https://github.com/abpframework/abp/blob/fe375f299545d31eb6b8789e752d86e6a57094c2/framework/src/Volo.Abp.Core/Volo/Abp/AbpApplicationBase.cs#L70-L78

Try get **IServiceScopeFactory** in **Startup**

![image](https://user-images.githubusercontent.com/6908465/98912494-26bc4600-2501-11eb-8e67-299ab79b6602.png)
