### ISSUE TITLE
Angular test identityUserService/tenantManagementService/... `TypeError: Cannot read property 'AbpIdentity'/'AbpTenantManagement' of undefined`

### ISSUE THREAD

**Issue by davidzwa** [abpframework/abp#7222]
* Volo.ABP 4.1.1
* Angular (with 4.1.1 package ng.core/ng.identity/ng.tenant-management)
* EFCore
* Exception (using `identityUserService`) : `TypeError: Cannot read property 'AbpIdentity' of undefined`
* Other similar exception(s) (using `tenantManagementService`): `TypeError: Cannot read property 'AbpTenantManagement' of undefined`
* Run default angular (karma) test on any component, make sure to import CoreTestingModule, IdentityConfigModule and TenantManagementConfigModule. Also add NgxsModule.forRoot([IdentityState, TenantManagementState]) as we cannot easily load lazyloaded modules for testing.

Example code to cause AbpIdentity error during spec-test:
```
export class UsersComponent implements OnInit {
    constructor(
        private identityUserService: IdentityUserService
    ) {
    }

    ngOnInit(): void {
        const input: GetIdentityUsersInput = {
            filter: '',
            maxResultCount: this.pageSize
        };
        this.identityUserService.getList(input).subscribe(result => {
             console.log(result);
        });
    }
```

The spec-test:
```
import {TeamsiteCoreTestingModule} from '@app/modules/teamsite-core/teamsite-core-testing.module';

describe('UsersComponent', () => {
    let component: UsersComponent;
    let fixture: ComponentFixture<UsersComponent>;

    beforeEach(async () => {
        await TestBed.configureTestingModule({
            declarations: [UsersComponent],
            imports: [
                TeamsiteCoreTestingModule.withConfig()
            ]
        })
            .compileComponents();
    });

    beforeEach(() => {
        fixture = TestBed.createComponent(UsersComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
    });

    it('should create', () => {
        expect(component).toBeTruthy();
    });
});
```
The teamsite-core-testing-module for easier testing:
```
@NgModule({
    providers: [],
    imports: [
        HttpClientTestingModule,
        NgxsModule.forRoot([AuthState, IdentityState, TenantManagementState]),
        CoreTestingModule.withConfig(),
        IdentityConfigModule.forRoot(),
        TenantManagementConfigModule.forRoot()
    ],
    exports: [
        HttpClientTestingModule,
        NgxsModule,
        CoreTestingModule,
        IdentityConfigModule,
        TenantManagementConfigModule
    ]
})
export class TeamsiteCoreTestingModule {
       static withConfig(): ModuleWithProviders<TeamsiteCoreTestingModule> {
        return {
            ngModule: TeamsiteCoreTestingModule,
            providers: [
// Other private data
            }
       }
}

```
Karma output:
```
TypeError: Cannot read property 'AbpIdentity' of undefined
    at EnvironmentService.getApiUrl (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:278:1)
    at MockRestService.getApiFromStore (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:300:1)
    at MockRestService.request (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.core/__ivy_ngcc__/fesm2015/abp-ng.core.js:309:1)
    at IdentityUserService.getList (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@abp/ng.identity/__ivy_ngcc__/fesm2015/abp-ng.identity.js:336:1)
    at UsersComponent.ngOnInit (http://localhost:9876/_karma_webpack_/webpack:/src/app/modules/management/components/users/users.component.ts:49:34)
    at callHook (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:2486:1)
    at callHooks (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:2457:1)
    at executeInitAndCheckHooks (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:2408:1)
    at refreshView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9207:1)
    at renderComponentOrTemplate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9306:1)
```

Maybe we need to have a IdentityTestingModule, Permission/Tenant/SettingManagementTestingModule as well?
Please advise.

**Comment by armanozak** [comment]
Hi,

Yes, we would need those, but why do you want to test built-in ABP modules?

**Comment by davidzwa** [comment]
I understand your question. We dont have the luxury of using the themes and cant integrate the bootstrap based layout, therefore we cannot use the components.
As I do want to use the states, services, etc we've chosen to rewrite the components, also because we need to shape the role/user/tenant/settings very differently and with such new components come our own specs.

So we're not testing the modules themselves, we're using the provided services in components which are spec-tested. That maybe makes more sense and to me sounds like something that can happen at any point in any application - regardless of whether they use the non-core modules as it was meant to be used, or as in our case only partially and spread over the SPA/PWA.
I mean I could try to mock them, but the exception provided above did not show me what to mock exactly.

**Comment by armanozak** [comment]
There is an `apiName` property on the `IdentityUserService`, which is passed to the `RestService` when calling the `request` method. However, the `EnvironmentService` where this will be checked has no state.

- You may use `setState` method of `EnvironmentService` to set a state before tests.
- You may mock the `EnvironmentService`.
- You may mock the `RestService`.

I hope this answers your question.

**Comment by davidzwa** [comment]
Very nice! Much obliged.

**Comment by davidzwa** [comment]
```
class MockEnvService {
    getApiUrl(key?: string): string {
        return key;
    }

    setState(environment: Environment): void {
    }
}
```

This worked a treat!

```
    beforeEach(async () => {
        await TestBed.configureTestingModule({
            declarations: [UsersComponent],
            providers: [
                {provide: EnvironmentService, useClass: MockEnvService}
            ],
            imports: [
                TeamsiteCoreTestingModule.withConfig()
            ]
        })
            .compileComponents();
    });
```

**Comment by armanozak** [comment]
I recommend using [Angular Testing Library](https://testing-library.com/docs/angular-testing-library/intro/) for component tests.

https://docs.abp.io/en/abp/4.2/UI/Angular/Testing

Have a nice day.

**Comment by davidzwa** [comment]
The tip you gave on this library was vital, again much obliged! The fact that it can span not only Angular makes it even more valuable all around
