### ISSUE TITLE
Swashbuckle.AspNetCore > v5.5.1 issue

### ISSUE THREAD

**Issue by v2codes** [abpframework/abp#7224]
Is there anyway to downgrade Swashbuckle.AspNetCore to v5.5.1 ?

Volo.Abp.Swashbuckle v4.1 upgrade Swashbuckle.AspNetCore from v5.5.1 to v5.6.3.
There is a issue in  v5.6.3, see [Exception within method GetHostOrNullFromRequest in SwaggerMiddleware](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1836)

And  Swashbuckle no release plan for the near future 

**ABP Framework version**. v4.1.0

**Comment by maliming** [comment]
You can try to get a workaround form **Swashbuckle**
