### ISSUE TITLE
How to set the default language？

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#723]

**Comment by maliming** [comment]
My current practice:
```c#
var defaultLanguage = app.ApplicationServices.GetService<ISettingDefinitionManager>().Get(LocalizationSettingNames.DefaultLanguage);
app.ApplicationServices.GetService<DefaultValueSettingValueProvider>().SetAsync(defaultLanguage, "zh-Hans", null);
```

**Comment by Nokecy** [comment]
@maliming  谢谢

**Comment by maliming** [comment]
For the 0.14.0 version you can use a code similar to the following to modify.
`app.ApplicationServices.GetService<ISettingDefinitionManager>().
Get(LocalizationSettingNames.DefaultLanguage).DefaultValue = "zh-Hans";`

**Comment by wakuflair** [comment]
Note: do not forget to clear cookie after setting default language.

**Comment by yimogit** [comment]
Get master branch(0.15.0) samples/Acme. BookStore and set the default language to zh-Hans. I didn't find the right way.
Now should be how to set up?
I hope I can get help.
