### ISSUE TITLE
When creating a project  if selecting version "4.2.0-rc.1" will results in an error

### ISSUE THREAD

**Issue by roupijiaojiaobao** [abpframework/abp#7230]
When creating a project on the "Direct Download" page, selecting Preview results in a code "500" error.

![微信截图_20210114084145](https://user-images.githubusercontent.com/64553587/104598358-7c69b780-5644-11eb-9c65-358cdfdd9f64.png)

**Comment by ismcagdas** [comment]
@paragpkulkarni should we working now, could you try again ?

**Comment by roupijiaojiaobao** [comment]
> @paragpkulkarni should we working now, could you try again ?

Available!
Thank you very much!
