### ISSUE TITLE
After logon tenant name not appear anywhere 

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#7231]
* **3.3.1**.
*  **Angular** 
* **EF Core**
* **No Exception**

After logon we cannot see tenant name in anywhere. For ex.: we will create users for call center per tenant, so it's useful that call center operator do not wrong operations. Tenant name can be under profile name(or in a place which will be shown always)

![image](https://user-images.githubusercontent.com/13360669/104601647-8662d900-568b-11eb-8c1c-6946de9b87ac.png)

**Comment by maliming** [comment]
hi @AdemAygun 

Are you using the abp commercial?

**Comment by AdemAygun** [comment]
yes, but I think this will be a useful feature for both open source and commercial

**Comment by maliming** [comment]
I can't reproduce your problem.
