### ISSUE TITLE
4.2 RC1 and CMS Kit

### ISSUE THREAD

**Issue by pvaz** [abpframework/abp#7233]
ABP 4.2 RC1

Hi,

anxiously waiting for the release of the cms kit module, today trying to see it live and test it, cannot simply find it.

I've created the project using abp suite and cli and suite are both pointed to RC1 version.

ABP CLI (https://abp.io)
Version 4.2.0-rc.1 (Prerelease)
Starting Suite v4.2.0-rc.1 ...
Opening http://localhost:3000

When I choose to create new solution I can see the options Public Web Site and PreviewVersion, but nothing related with CMS Kit ?

And how to add and use the CMS Kit ?

Thanks,
Paulo

**Comment by ilkayilknur** [comment]
Hello Paulo,
The CMS-Kit first preview is slated for 4.3 release. Our intention was to release the first preview with version 4.2. There were still some works to be done before the first preview. So we decided to skip 4.2 and focus on stability and some new functionalities. The team is excited and working hard to release the first preview of the CMS-Kit. 

Thanks for your interest.

**Comment by myomyinthan** [comment]
Hi ilkayilknur,

Can we choose angular or blazor for CMS-Kit ? 

Thanks
