### ISSUE TITLE
DbMigrator could not create the initial migration

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#7241]
Steps:
   1. `abp new Acme.BlazorEfCore -t app -u blazor --mobile none  --database-provider ef -csf --preview`
   2. Run the `.DbMigrator` application

![image](https://user-images.githubusercontent.com/16813853/104674303-603a4900-571e-11eb-990b-e11dabd4fbc3.png)

**Comment by yekalkan** [comment]
If anyone else having this issue: Please use `dotnet run` to run **DbMigrator** project (or Visual Studio).
