### ISSUE TITLE
Proxy Generation How do I generate comments

### ISSUE THREAD

**Issue by tang-butian** [abpframework/abp#7246]
For example, service comments, DTOs comments

**Comment by ilkayilknur** [comment]
@2693252993 can you elaborate on the question, please?

**Comment by tang-butian** [comment]
@ilkayilknur 
sorry.
I want to use ABP Generate-Proxy to generate comments for DTO in server code into Angular applications.
The server code
![image](https://user-images.githubusercontent.com/27254047/104975691-54a89400-5a36-11eb-8f01-3971adf41f9d.png)
The code I want to generate for an Angular app looks like this
![image](https://user-images.githubusercontent.com/27254047/104975828-b8cb5800-5a36-11eb-9cd5-b9c43e61cd22.png)

**Comment by ilkayilknur** [comment]
@armanozak , Can you take a look at this, please?

**Comment by armanozak** [comment]
You cannot generate comments.
