### ISSUE TITLE
Excuse me, we have completed the payment, but we cannot find this page. Can you provide support?

### ISSUE THREAD

**Issue by mason-hz** [abpframework/abp#7254]
Dear ABP team,

Excuse me, we have completed the payment, but we cannot find this page. Can you provide support?
![image](https://user-images.githubusercontent.com/66669985/104709214-9a750c00-5759-11eb-9fe8-faed5c252f4a.png)

**Comment by ebicoglu** [comment]
you have sent an email to [info@abp.io](mailto:info@abp.io) and the team is checking your issue.

no need to create an issue in the open-source repository
