### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by ghost** [abpframework/abp#7261]
ABP version: 4.2.0-rc.1
UI: Razor page
DB provider: EF Core
VS community 16.8.4
OS Win 10
Chrome  87.0.4280.141 
dotnet --version 5.0.200-preview.20601.7

I think I hit the strange errors.

### 1. Invalid username or password

Steps to reproduce:

1). Create a new application **TestCsrf** and download from abp.io, unzip and open in Visual Studio Community 2019.

Following the documents of abp, after running DbMigrator, then run debug on **TestCsrf.Web**, login successful in Chrome, everything works fine.

2). In Visual Studio. Right click on **TestCsrf.Web** and Publish to folder. 
`Run CMD` and cd to publish folder, run `dotnet TestCsrf.Web.dll`.  Back to Chrome, login failed with error msg: `Invalid username or password.`

There are two warnings in logs. 

```
[18:31:13 WRN] Invalid password for user.
[18:31:13 WRN] User failed to provide the correct password.
```

3).  Open the database `(LocalDb)\\MSSQLLocalDB`,  edit data rows in table `AbpUsers`,  update the `SecurityStamp` and `PasswordHash`  with `new-values` of user `admin`.

NOTE, the `new-values` is copied from another project which was based on abp , and I'm sure it's correct 100%.

Back to Chrome and login,  No errors, but it was redirect to home page `http://localhost:5000/`, the status of website now is not login.

Check the logs, no warnings of `Invalid password for user`, but another warning shows up, only one,

```
[19:20:14 WRN] The cookie 'XSRF-TOKEN' has set 'SameSite=None' and must also set 'Secure'.
```

 
### 2. XSRF-TOKEN

According to the abp docs,  a default cookie name `XSRF-TOKEN` should be stored in Chrome. but now in my Chrome, no `XSRF-TOKEN`. 

![1](https://user-images.githubusercontent.com/4242075/104723099-b41e4f80-5769-11eb-8d2e-ecd4af0ab286.png)

----

Exit and close the `CMD` window, then debug in Visual Studio.

Open Chrome and login, failed of course, we need to update the password of `admin` in database firstly.  

Restore the value of `SecurityStamp` and `PasswordHash` , then login.

there is a cookie name `XSRF-TOKEN` in Chrome. And no cross-site warning in the logs.

![2](https://user-images.githubusercontent.com/4242075/104724268-6b679600-576b-11eb-94c0-4a2817cd6175.png)

**Comment by ghost** [comment]
Update:

I've figured out the problem of `XSRF-TOKEN` after couple hours of reading the docs about `SameSite` property of cookie.

The SSL was enabled by default in Visual Studio when debuging in Chrome. 

After published to folder and run `dotnet TestCsrf.Web.dll`, I access to website by http `not` https, it will cause this issue.

If you want to access website by http with no issue, configure the `SameSite`  mode to `Lax` or `Strict`

```c#
            Configure<AbpAntiForgeryOptions>(options =>
            {
                options.TokenCookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.Lax;
            });

```

**Comment by espindl** [comment]
This is not a login issue only. If you are using MVC Razor and calling appservices from javascript (abp ajax) on Chrome it is an issue. We were not having login issues but having issues calling services from js. And we added @scymen 's options code. Now it is working without an issue. Btw it was not an issue on Firefox. Maybe it should be in the frw code.
