### ISSUE TITLE
Can't get localization for 'is' or 'is-IS' to work without <?>

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#7272]
Hi

For some reason, **I can´t get my special Icelandic letters to show up correctly**. I have tried a lot of things and read all there is [about localization on your docks](https://docs.abp.io/en/abp/latest/Localization).

I have tried to use both 'is' and 'is-IS' as a culture name but without any change.

![image](https://user-images.githubusercontent.com/2386572/104748861-12d3d100-574a-11eb-9689-d43fc4f54d2e.png)

My **is.json** (or even **is-IS**.json) file

```json
{
  "culture": "is",
  "texts": {
    "Menu:Home": "All special icelandic letters only showing ? -> íþð",
    "Welcome": "Welcome",
    "LongWelcomeMessage": "Welcome to the application. This is a startup project based on the ABP framework. For more information, visit abp.io."
  }
}
```
and the **HttpApiHostModule.cs** file

```csharp
        private void ConfigureLocalization()
        {
            Configure<AbpLocalizationOptions>(options =>
            {
                options.Languages.Add(new LanguageInfo("is", "is", "Íslenska"));
                options.Languages.Add(new LanguageInfo("en", "en", "English"));
                options.Languages.Add(new LanguageInfo("cs", "cs", "Čeština"));            
            });
        }
```

The strange thing is that the Čeština translation contains some of these letters (like 'í') and seems to work.

I must be missing something really trivial but I just can't spot it. Hope you can point me in the right direction.

I ran `abp new Acme.BookStore -u blazor` and I'm on Abp version 4.1.1
I created a [test project for this localization.](https://github.com/sturlath/ABP_Localization/tree/master)

**Comment by maliming** [comment]
Maybe related to https://github.com/abpframework/abp/issues/2180#issuecomment-554852256

**Comment by sturlath** [comment]
That was it! Thank you... I´ll close this
