### ISSUE TITLE
Blazor UI - overwrite tenant management ui

### ISSUE THREAD

**Issue by nebula2** [abpframework/abp#7279]
Hello,

I wanted to add two properties to the tenant. 
**4.1 - Blazor UI - EF Core - not tiered**
According to the object extensions documentation found [here](https://docs.abp.io/en/abp/latest/Object-Extensions) I added the following code.

**Domain.Shared.#ModuleExtensionConfigurator.cs**

```c#
private static void ConfigureExtraProperties()
{
            ObjectExtensionManager.Instance.Modules()
               .ConfigureTenantManagement(x =>
               {
                   x.ConfigureTenant(t =>
                   {
                       t.AddOrUpdateProperty<string>(
                           "ClanId",
                           property =>
                           {
                               property.Attributes.Add(new RequiredAttribute());
                               property.Attributes.Add(new StringLengthAttribute(20) { MinimumLength = 4 });
                           }
                       ).AddOrUpdateProperty<string>(
                           "ClanName",
                           property =>
                           {
                               property.Attributes.Add(new RequiredAttribute());
                               property.Attributes.Add(new StringLengthAttribute(30) { MinimumLength = 1 });
                           }
                       );
                   });
               });
}
```
**EntityFrameworkCore.#EfCoreEntityExtensionMappings.cs**
```c#
public static void Configure()
 {
            TT2MasterzGlobalFeatureConfigurator.Configure();
            TT2MasterzModuleExtensionConfigurator.Configure();

            OneTimeRunner.Run(() =>
            {
                ObjectExtensionManager.Instance
                    .MapEfCoreProperty<Tenant, string>(
                        "ClanId",
                        (entityBuilder, propertyBuilder) =>
                        {
                            propertyBuilder.HasMaxLength(20);
                        }
                    ).MapEfCoreProperty<Tenant, string>(
                        "ClanName",
                        (entityBuilder, propertyBuilder) =>
                        {
                            propertyBuilder.HasMaxLength(20);
                        }
                    );
            });
}
```
Now I want to make those properties visible on the tenant management ui when i create or update an entity.
On my search on how to do this I landed [here](https://docs.abp.io/en/abp/4.1/UI/AspNetCore/Customization-User-Interface#overriding-a-razor-page-cshtml).
I went to **.HttpApi.Host**, added a Folder called Pages and inserted [this](https://github.com/abpframework/abp/blob/dev/modules/tenant-management/src/Volo.Abp.TenantManagement.Blazor/Pages/TenantManagement/TenantManagement.razor) file.
The documentation said I need to copy the .cshtml file which I could not find.

Now I get some error messages which I think come from missing references:
Here is a little cut out
![image](https://user-images.githubusercontent.com/5841525/104812897-bdf59080-5805-11eb-9c42-b8d190d0a4da.png)
![image](https://user-images.githubusercontent.com/5841525/104812922-f4cba680-5805-11eb-895d-afc96533e47d.png)

I think that I am doing something wrong. Can anyone guide me in the right direction?

**Comment by tntwist** [comment]
Hi,
try adding the required usings to the _Imports.razor located in your blazor project
```
...
@using Blazorise
@using Blazorise.DataGrid
@using Blazorise.Components
@using Volo.Abp.BlazoriseUI
@using Volo.Abp.BlazoriseUI.Components
...
```

**Comment by nebula2** [comment]
> Hi,
> try adding the required usings to the _Imports.razor located in your blazor project
> 
> ```
> ...
> @using Blazorise
> @using Blazorise.DataGrid
> @using Blazorise.Components
> @using Volo.Abp.BlazoriseUI
> @using Volo.Abp.BlazoriseUI.Components
> ...
> ```

Well, I made the mistake to put the page inside the host project instead of the blazor project. Changed that but I still get a lot of errors. the usings are already defined inside the _imports.razor file.
![image](https://user-images.githubusercontent.com/5841525/104816749-564b3f80-581d-11eb-92b4-c98481cc0cf9.png)
![image](https://user-images.githubusercontent.com/5841525/104816784-7975ef00-581d-11eb-80b6-ecb3f0ca1a47.png)

**UPDATE**:
After adding `@using Volo.Abp.TenantManagement` to the page the errors got reduced. Now the issue seems to be that my TenantManagement.razor does not know of the partial class and it's properties.
![image](https://user-images.githubusercontent.com/5841525/104817809-f2784500-5823-11eb-9f7e-a40164e05860.png)
![image](https://user-images.githubusercontent.com/5841525/104817837-22bfe380-5824-11eb-8c8d-2b3116bbaa6b.png)

**Comment by tntwist** [comment]
TenantManagement stuff should be in the namespace ``Volo.Abp.TenantManagement``.

So try adding ``@using Volo.Abp.TenantManagement`` to your TenantManagment.razor
Or you can move the page to the correct namespace with ``@namespace Volo.Abp.TenantManagement``

**Comment by nebula2** [comment]
Luckily I was able to solve this. The main issue was that I used the wrong documentation.

The correct documentation is [this](https://docs.abp.io/en/abp/latest/UI/Blazor/Customization-Overriding-Components) one.

The main difference is that my custom page needs to inherit from the default page. I also need to define attributes (everything like documented).
But there is one thing I want do add (for dummies like me). You need to remove the `@page "/tenant-management/tenants"`

In addition to that I renamed my page to "MyTenantManagement.razor". The usings etc. look like this:
```
using Volo.Abp.DependencyInjection
@using Microsoft.AspNetCore.Authorization
@using Volo.Abp.FeatureManagement.Blazor.Components
@using Volo.Abp.TenantManagement.Localization
@using Volo.Abp.TenantManagement

@*@page "/tenant-management/tenants"*@
@inherits Volo.Abp.TenantManagement.Blazor.Pages.TenantManagement.TenantManagement

@attribute [Authorize(TenantManagementPermissions.Tenants.Default)]
@attribute [ExposeServices(typeof(Volo.Abp.TenantManagement.Blazor.Pages.TenantManagement.TenantManagement))]
@attribute [Dependency(ReplaceServices = true)]

@inject AbpBlazorMessageLocalizerHelper<AbpTenantManagementResource> LH
```

I added this right after:
```html
<h2>This is my custom tenant managemant page</h2>
```

![image](https://user-images.githubusercontent.com/5841525/104844570-468d3300-58d1-11eb-807c-4549c4fa8102.png)
