### ISSUE TITLE
How to localize Login/Logout text in menu (or the login window there after)?

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#7280]
I have read the [localization docs](https://docs.abp.io/en/abp/latest/Localization) (and the [extending resources](https://docs.abp.io/en/abp/latest/Localization#extending-existing-resource)) in/out and I can't figure out how I can override the default English translations that I have not set, like "Log in" etc. 

It must be possible to override it even though the system doesn't currently come with Icelandic, right?

I just can't change the text **Login** to "Innskrá"!
 
![image](https://user-images.githubusercontent.com/2386572/104814982-bcc66280-5809-11eb-8d60-440a914c08f2.png)

I have tried to add all thinkable resources (they are [quite a few](https://github.com/abpframework/abp/search?p=1&q=%5BLocalizationResourceName%28))

[See my code](https://github.com/sturlath/ABP_Localization/blob/af8e444bfb4f86fc6674cc3fc8b581ad5ade534e/src/test.test.Domain.Shared/testDomainSharedModule.cs#L56) 
```csharp
Configure<AbpLocalizationOptions>(options =>
            {
                options.Resources
                    .Add<testResource>("is")
                    .AddBaseTypes(typeof(AbpValidationResource))
                    .AddBaseTypes(typeof(AbpIdentityServerResource))
                    .AddBaseTypes(typeof(IdentityResource))
                    .AddBaseTypes(typeof(AbpTenantManagementResource))
                    .AddBaseTypes(typeof(AbpLocalizationResource))
                    // name space Account not available here!
                    //.AddBaseTypes(typeof(Volo.Abp.Account.Localization.AccountResource)) 
                    .AddVirtualJson("/Localization/test");
                    
                   options.DefaultResourceType = typeof(testResource);
            });
```
**Now** that I'm writing this, I'm thinking that the lack of Volo.Abp.Account.Localization.AccountResource **might be the problem**. The project doesn't have access to it? 

I have even tried all kinds of "overrides" in the [is.json](https://github.com/sturlath/ABP_Localization/blob/master/src/test.test.Domain.Shared/Localization/test/is.json) file

```json
{
  "culture": "is",
  "texts": {
    "Menu:Home": "All special icelandic letters only showing ? -> íþð ",
    "Welcome": "Welcome",
    "LongWelcomeMessage": "Welcome to the application. This is a startup project based on the ABP framework. For more information, visit abp.io.",
    "Login": "Innskrá",
    "Logout": "Útskrá",
    "Authentication:Login": "Innskrá",
    "Authentication:Logout": "Útskrá",
    "Volo.Abp.Account:Login": "Innskrá",
    "Volo.Abp.Account:Logout": "Útskrá",
    "Login:Volo.Abp.Account.Login": "Innskrá",
    "Logout:Volo.Abp.Account.Logout": "Útskrá",
    "Default:Login": "Innskrá",
    "Default:Logout": "Útskrá",
    "Account:Login": "Innskrá",
    "Account:Logout": "Útskrá",
    "Account::Login": "Innskrá",
    "Account::Logout": "Útskrá",
    "Account:Login:Login": "Innskrá",
    "Account:Login:Logout": "Útskrá",
    "AbpAccount:Login": "Innskrá",
    "AbpAccount:Logout": "Útskrá",
    "AbpUi:Login": "Innskrá",
    "AbpUi:Logout": "Útskrá"
  }
}
```

I have searched open/cloes issues and found few similar but they did'nt help. See [this](https://github.com/abpframework/abp/issues/4722), [this ](https://github.com/abpframework/abp/issues/3417) and [this one ](https://github.com/abpframework/abp/issues/2397) 

**Version and code**
Running apb.io version 4.1.1 and Blazor
I have created a [test project](https://github.com/sturlath/ABP_Localization) with this code if you like to try it out

**Comment by d-oit** [comment]
Login / Logout is not a localizable string: https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme/Themes/Basic/LoginDisplay.razor

You could override the component:
https://docs.abp.io/en/abp/latest/UI/Blazor/Customization-Overriding-Components

Or customize the basic theme:
https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b

**Comment by sturlath** [comment]
Is there something stopping me from trying to create a PR for that? Is there some reason the strings are not localized there?

**But how about** the page after pressing the Login button? This [Login.cshtml](https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml)

![image](https://user-images.githubusercontent.com/2386572/104837501-da98d380-58ac-11eb-90e1-6f34e88e1e95.png)

[There](https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml) we have @L["AreYouANewUser"] but with my code above and this added to the json file it doesn't take..
```json
    "AreYouANewUser": "Ertu nýr notandi?",
    "Authentication:AreYouANewUser": "Ertu nýr notandi?",
    "Volo.Abp.Account:AreYouANewUser": "Ertu nýr notandi?",
    "Login:Volo.Abp.Account.AreYouANewUser": "Ertu nýr notandi?",
    "Default:AreYouANewUser": "Ertu nýr notandi?",
    "Account:AreYouANewUser": "Ertu nýr notandi?",
    "Account::AreYouANewUser": "Ertu nýr notandi?",
    "Account:Login:AreYouANewUser": "Ertu nýr notandi?",
    "AbpAccount:AreYouANewUser": "Ertu nýr notandi?",
    "AbpUi:AreYouANewUser": "Ertu nýr notandi?"
```
That might be because of ```Volo.Abp.Account``` **namespace not being available in the Domain.Shared project**?
The  ```Volo.Abp.Account.Web.IdentityServer``` package can´t be installed into the project... 

So..?

**Btw** thank you @d-oit  for your other suggestions. I´ll try them out for the Login text..

**Comment by olicooper** [comment]
### UPDATE 
The localization overriding is working fine with the changes below. It was a bug specifically in Identity localization: https://github.com/abpframework/abp/commit/cc1c1d3cd1dc19bf66701d12ebc02acc58b559b6#diff-64394e2c990c78aa48c6d551c9e82a16ed963b96d17bdf1a9adbcf3029d6c642

==========

I precisely followed the abp docs and it isn't working for me either.

I want to change this localized string:
https://github.com/abpframework/abp/blob/badad8d59f02bb0ccba433b49a7fc24ee7bf3b5a/modules/identity/src/Volo.Abp.Identity.Domain.Shared/Volo/Abp/Identity/Localization/en.json#L47

In the `ConfigureServices` of my Domain.Shared module:
```csharp
[DependsOn(
    //...
    typeof(AbpIdentityDomainSharedModule),
    //...
)]
public class MyProjectDomainSharedModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        Configure<AbpLocalizationOptions>(options =>
        {
            options.Resources
                .Get<Volo.Abp.Identity.Localization.IdentityResource>()
                .AddVirtualJson("/Localization/Resources/Identity/Extensions");
        });
    }
}
```
My csproj project file includes the embedded resource
```xml
  <ItemGroup>
    <EmbeddedResource Include="Localization\**\*.json" />
    <Content Remove="Localization\**\*.json" />
  </ItemGroup>
```

File structure:
![image](https://user-images.githubusercontent.com/22296715/105072356-9d377000-5a7d-11eb-92ab-2381b693401d.png)

The text is not overridden. I have also added this to the HttpApi.Host module and used `PostConfigure` with no success either.

**Comment by maliming** [comment]
hi @olicooper

Can you share a project to show the problem?

**Comment by olicooper** [comment]
@maliming I don't think the problem I mention above is a localization issue, it is due to the bug [I mention here](https://github.com/abpframework/abp/commit/cc1c1d3cd1dc19bf66701d12ebc02acc58b559b6#commitcomment-46124823).

I can create a project to show the `Identity.Default` issue I have if that is what you need? The configuration is what I describe in my comment above - where I override the `IdentityResource` to replace `Volo.Abp.Identity:InvalidToken` with "Invalid token, please try again."

**Comment by maliming** [comment]
Please share it, thanks.

**Comment by olicooper** [comment]
Here is a sample that should work. Go to appsettings.json and update TestUserId with the host admin Id in your database.
[IdentityResourceTest.zip](https://github.com/abpframework/abp/files/5842170/IdentityResourceTest.zip)
When you submit the form, it should say "Invalid token, please try again." but it just says "Invalid token."

**Update**
@maliming I'm sorry, I should have mentioned that `Identity.Default` will only happen after your update https://github.com/abpframework/abp/commit/cc1c1d3cd1dc19bf66701d12ebc02acc58b559b6
The version in the first sample (IdentityResourceTest.zip) is 4.2.0-rc.2 which doesn't include the update yet, but it still doesn't localize the text as expected.
Here is a new version with manually applied changes: [IdentityResourceTest-v2.zip](https://github.com/abpframework/abp/files/5842347/IdentityResourceTest-v2.zip)

**Comment by maliming** [comment]
Thanks @olicooper 

`AbpIdentityResultExtensions` needs refactoring, I am working on it.

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/7362

**Comment by olicooper** [comment]
@sturlath Sorry for hijacking your issue! I have tested the `AreYouANewUser` localization issue for you...
The `AccountResource` is located in the `Application.Contracts` of the [account module](https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/AccountResource.cs), so you need to place your localization overrides in your `Application.Contracts` module or a module that depends on it such as the `Web` module...
```csharp
public class MyProjectApplicationContractsModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        Configure<AbpLocalizationOptions>(options =>
        {
            options.Resources
                .Get<Volo.Abp.Account.Localization.AccountResource>()
                .AddVirtualJson("/Localization/AbpAccount");
        });
    }
}
```
I have left my localization *.json files in my `Domain.Shared` module, but I can't guarantee that it will work properly for you.
![image](https://user-images.githubusercontent.com/22296715/105197623-b64f2800-5b34-11eb-8561-dd137947b966.png)

You shouldn't need to use `.AddBaseTypes(typeof(xyzResource))` because this just includes external resources in your own resource namespace `testResource`.

> Is there something stopping me from trying to create a PR for that? Is there some reason the strings are not localized there?

I would say yes to creating a PR for the login text here, because a 'Login' localization [already exists](https://github.com/abpframework/abp/blob/a21687277953f7ff579446a0bc1161112cec4fce/modules/account/src/Volo.Abp.Account.Application.Contracts/Volo/Abp/Account/Localization/Resources/en.json#L15) but it isn't being used in the menu bar for blazor apps. you can see all the places it is used [here](https://github.com/search?q=login+repo%3Aabpframework%2Fabp+extension%3Acshtml+extension%3Arazor&type=Code&ref=advsearch&l=&l=).

@maliming After looking at the issues created about localization, I wonder if the localization docs might need to be expanded to explain which module to place the override configuration in along with an example of overriding a built-in resource like `AccountResource`?

**Comment by maliming** [comment]
An example to explain how to extend localization resource.
https://github.com/abpframework/abp-samples/tree/master/DocumentationSamples/ExtendLocalizationResource
