### ISSUE TITLE
Article: How to login and consume backend API using Xamarin

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#7289]

**Comment by nicksoftware** [comment]
[Bart Van Hoey](https://community.abp.io/members/bartvanhoey) has created a demo for this. 👌👌👌

[How to consume ABP api from xamarin.form ](https://community.abp.io/articles/abp-framework-api-consumed-by-xamarin.forms-application-rkdfzz66)

**Comment by maliming** [comment]
https://community.abp.io/articles/abp-framework-api-consumed-by-xamarin.forms-application-rkdfzz66
