### ISSUE TITLE
Create a sample microservice solution

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#729]
After creating the sample, I will document it to be understood. I know everybody waiting for this, but it will get some time as you can guess :)

See https://github.com/abpframework/abp/blob/master/samples/MicroserviceDemo/docs/design/Overall.md

**Comment by maliming** [comment]
That’s awesome! 🎉🎉🎉

**Comment by liangshiw** [comment]
That's cool! 🎉🎉🎉

**Comment by marcelo-maciel** [comment]
Very nice! 🥇 🥇 🥇

**Comment by hitaspdotnet** [comment]
Thanks in advance for this sample. For your precious time. 🎉🎉🎉

**Comment by jackingod** [comment]
That's cool! 🎉🎉🎉

**Comment by myomyinthan** [comment]
That so cool

**Comment by geffzhang** [comment]
sample should be run on kubernetes

**Comment by abhishekbdutta** [comment]
That is an awesome news have been waiting this for almost 2 years now.

On Jan 12, 2019 14:20, geffzhang <notifications@github.com> wrote:

sample should be run on kubernetes

**Comment by hikalkan** [comment]
I'm glad to get such a huge attraction for this :)

**Comment by myomyinthan** [comment]
Hi hikalkan,
Is it multi tenant on microservice?😁

**Comment by hikalkan** [comment]
In the first, probably no. But will make it multi-tenant eventually.

**Comment by edison1105** [comment]
I can't wait for that. 👍

**Comment by letmego9go** [comment]
Good Job！

**Comment by hikalkan** [comment]
For who want to test right now:

* Clone abp repository and [build all](https://github.com/abpframework/abp/blob/master/build-all.ps1).
* Restore [databases].(https://github.com/abpframework/abp/tree/master/samples/MicroserviceDemo/databases).
* Install and run RabbitMQ.
* Install and run Redis server.
* Open the [solution](https://github.com/abpframework/abp/blob/master/samples/MicroserviceDemo/MicroserviceDemo.sln).
* Run AuthServer.Host project.
* Run all microservices.
* Run all gateways.
* Run any application you want (to a simple test, run ConsoleClientDemo).

I hope it works :) BTW, I'm working to create a docker-compose configuration to make all working. Just wait a bit more.

**Comment by hitaspdotnet** [comment]
I succeeded. Thanks. You are wonderful.

**Comment by hitaspdotnet** [comment]
@hikalkan Sir, today i got time for learning more around your amazing microservice sample.
I can't login|register. `admin` was created in DB by data seeding from `AuthServer.Host` but login with `admin` user and `1q2w3E` password fails. Am I missing something? Product list in PublicWebsite worked well.

**Comment by hitaspdotnet** [comment]
For additional info I'm try to running using VS multiple startup project. Here is my startup project map (based on your [coment](https://github.com/abpframework/abp/issues/729#issuecomment-456371982)):
1- AuthServer.Host
2- IdentityService.Host
3- BloggingService.Host
4- InternalGetway.Host
5- BackedndAdminAppGetway.Host
6- PublicWebSiteGetway.Host
7- PublicWebSite.Host
8- BackedndAdminApp.Host

**Comment by hikalkan** [comment]
For who want to try: https://abp.io/documents/abp/latest/Samples/Microservice-Demo#how-to-run

docker-compose is working as we've tested:
https://abp.io/documents/abp/latest/Samples/Microservice-Demo#using-the-docker-containers

Kubernetes is coming soon: https://github.com/abpframework/abp/issues/811

**Comment by hikalkan** [comment]
I'm closing this issue since it is basically done.
There are some improvements but they will be done separately.

See the documentation of this sample: https://abp.io/documents/abp/latest/Samples/Microservice-Demo
