### ISSUE TITLE
AbpCrudPageBase.cs 

### ISSUE THREAD

**Issue by d-oit** [abpframework/abp#7291]
` protected virtual async Task CreateEntityAsync()`
... 
move 
>> CreateModal.Hide();

```
       protected virtual Task OnCreatedEntityAsync()
        {
             CreateModal.Hide();
            return Task.CompletedTask;
        }
```

use case: Modal "Create dialog" with Button "Save & New" to create records in one go

**Comment by stsrki** [comment]
@d-oit Can you please explain better what is the problem? Do I need to remove `CreateModal.Hide();`?

**Comment by stsrki** [comment]
Ignore, I see what you meant now :)

**Comment by d-oit** [comment]
@stsrki Think about the end user. In the current implentation you have to enter the record values ->
Save and click on the "new" button again - not real user friendly. For my apps I implement - "Save & New" and "Save & Close" Buttons or with a bool switch for close or not close the modal dialog. 
 
I already create a new class (derived from AbpCrudBase) for myself and fix the problem for me already. 
I could PR the changes if you like. 

```
 protected virtual async Task CreateEntityAsync()
        {
            if (CreateValidationsRef?.ValidateAll() ?? true)
            {
                await OnCreatingEntityAsync();

                await CheckCreatePolicyAsync();
                var createInput = MapToCreateInput(NewEntity);
                await AppService.CreateAsync(createInput);

                await OnCreatedEntityAsync();
            }
        }
```

Now you only need to override OnCreatedEntityAsync with customize code:

 ```
 protected override async Task OnCreatedEntityAsync()
        {
            if (ShowNotify)
            {
                await Notify.Success(L["SaveSuccessful"]);
            }
            if (!CreateAndNew)
            {
                CreateModal.Hide();
                await GetEntitiesAsync();
            }
        }

```

**Comment by d-oit** [comment]
@stsrki :-)
