### ISSUE TITLE
Trying to build a video to demo the Blazor animations in V4.1

### ISSUE THREAD

**Issue by learnabpframework** [abpframework/abp#7292]
I can't seem so see any animations which are mentioned in the Blog and release notes for version 4.1

```
Other Blazor UI highlights
Implemented some animations (like opening/closing modals and dropdowns).
Automatically focus to the first input when you open a modal form.
```

**Comment by ilkayilknur** [comment]
@stsrki Any ideas on how did we implement the animations?

**Comment by stsrki** [comment]
@learnabpframework @ilkayilknur 

Opening animations are done automatically for modals and dropdowns. It's more of a fade-in effect. 

Regarding the autofocus, it works for input fields by setting the `Autofocus` parameter. eg. `<TextEdit Autofocus="true" />`.

In case the effects are not working, try refreshing the app with CTRL+F5 or clear the cache manually. Sometimes Blazor tends to leave the older version of javascripts.

**Comment by learnabpframework** [comment]
I have tried clearing the browser cache  ... doesn't seem to have any effect. Hard to demonstrate the animations if it is only a subtle change. is there a way to slow down the fade effect to show that it is animated.

**Comment by stsrki** [comment]
You can adjust animation CSS. Here is the source

```css
.modal.show {
    animation-duration: 0.25s;
    animation-fill-mode: both;
    animation-name: fadeIn;
}
```
