### ISSUE TITLE
Weird layout on build-in pages like Homepage and Dashboard

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#7306]
3.3.2 / Angular

For some reason, 'built-in' pages, like Home page or Dashboard now look weird - they have `abp-application-layout` inside another `abp-application-layout`. Our own pages look normal.

![image](https://user-images.githubusercontent.com/6149843/104904160-8c0d3700-5989-11eb-9097-d3eb20793a17.png)

![image](https://user-images.githubusercontent.com/6149843/104904323-b6f78b00-5989-11eb-8fc2-1a61ecf9e6b3.png)

**Comment by ilkayilknur** [comment]
@bnymncoskuner can you take a look into that, please?

**Comment by mehmet-erim** [comment]
Hello @alexandis

Can you compare the following files with your own files:

https://github.com/abpframework/abp/blob/dev/templates/app/angular/src/app/route.provider.ts
https://github.com/abpframework/abp/blob/dev/templates/app/angular/src/app/home/home-routing.module.ts

If you see any differences, please update the content of your files.

**Comment by alexandis** [comment]
Allright now on Home page, what about Dashboard page - what is to be changed in the related component and stuff?

**Comment by mehmet-erim** [comment]
`DashboardRoutingModule` file should not contain `ApplicationLayoutComponent`. Please check the below content with yours.

```ts
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { ApplicationLayoutComponent } from '@volo/abp.ng.theme.lepton';
import { DashboardComponent } from './dashboard.component';

const routes: Routes = [{ path: '', component: DashboardComponent }];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class DashboardRoutingModule {}
```

`route.provider.ts`:

```ts
import { RoutesService, eLayoutType } from '@abp/ng.core';
import { APP_INITIALIZER } from '@angular/core';

export const APP_ROUTE_PROVIDER = [
  { provide: APP_INITIALIZER, useFactory: configureRoutes, deps: [RoutesService], multi: true },
];

function configureRoutes(routes: RoutesService) {
  return () => {
    routes.add([
      {
        path: '/',
        name: '::Menu:Home',
        iconClass: 'fas fa-home',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/dashboard',
        name: '::Menu:Dashboard',
        iconClass: 'fas fa-chart-line',
        order: 2,
        layout: eLayoutType.application, // you can specify a layout for the component like this line
        requiredPolicy: 'MyProjectName.Dashboard.Host || MyProjectName.Dashboard.Tenant',
      },
    ]);
  };
}
```

**Comment by alexandis** [comment]
Thank you, the problem with nested tags is now gone. But I have last question: previously, Dashboard built-in page displayed some charts (probably some nice-to-have info, did not dig in into details yet). And now it just says "Add your Tenant related charts/widgets to this page !"... Why?

**Comment by mehmet-erim** [comment]
Charts are only visible for the host tenant.  You can see the charts you mentioned in the `host-dashboard.component.html`

**Comment by alexandis** [comment]
@mehmet-erim Ahh, ok. Thanks for clarification. I will close the issue now - thank a lot for your help.
