### ISSUE TITLE
Password validation strings are not localized

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#7319]
![image](https://user-images.githubusercontent.com/1492596/104954780-30fb3480-59c9-11eb-9efe-902adbcee393.png)

Tested in a clean 4.1.1 Razor pages setup

- Select any language but English and go to the registration page
- Write a single letter in the password field to display the validation errors
- These are showing in English and not in selected language

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/7321

**Comment by martenw** [comment]
Impressed by how fast you fix reported issues!

Many thanks!
