### ISSUE TITLE
Exception injecting `IRepository<MyEntity,Guid>` in an ABP console app

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#7320]
Hi,

I am using ABP version 4.1

I am trying to write a utility console app that has MySQL database access. 

I used the documented method to create a console app: https://docs.abp.io/en/abp/latest/Startup-Templates/Console#how-to-start-with

I created the entities and successfully ran the migrator. The DB and all tables were created successfully

I have previously used `IRepository` successfully in production code that's running (ABPv 3.x)

**The problem I am having is that it is not injecting my `IRepository<MyEntity, Guid>`**

It is failing with an exception: 

`Autofac.Core.DependencyResolutionException: An exception was thrown while activating ?:Microsoft.Extensions.Hosting.IHostedService[] -> MyApp.Console.ConsoleHostedService -> MyApp.Console.ConsoleService.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Volo.Abp.Autofac.AbpAutofacConstructorFinder' on type 'MyApp.Console.ConsoleService' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[MyApp.MyEntity,System.Guid] myEntityRepository' of constructor 'Void .ctor(Volo.Abp.Domain.Repositories.IRepository`2[MyApp.MyEntity,System.Guid])'.`

What I have tried:

1. I followed the documentation by trying to add the `IRepository<MyEntity, Guid>` to the console app  https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-default-repositories 
2. I tried the solution found here: https://github.com/abpframework/abp/issues/5390
3. I tried creating a domain service which had a method calling  `IRepository<MyEntity, Guid>` , but had a similar exception
4. I made sure `options.AddDefaultRepositories(includeAllEntities: true);` was added in the registration
5. As a last option, I tried a custom repository, and still had a similar exception (https://docs.abp.io/en/abp/latest/Repositories#custom-repositories)
6. I also played around with adding dependencies to the DomainModule and the EFCore Module, but it didn't work

``` c#
[DependsOn(
        typeof(MyAppDomainModule),
        typeof(AbpEntityFrameworkCoreModule),
        typeof(AbpAutofacModule)
    )]
```

**How do  I get a console app to use the Default Repository? 
Where could I be getting it wrong?**

**Comment by maliming** [comment]
Can you share some code?

**Comment by pualfu** [comment]
the "xxxDbContext" must  had   `public DbSet<MyEntity> MyEntity{ get; set; }` code    .check it

**Comment by tinonetic** [comment]
Hi @maliming 

Apologies for the late reply. Please see the code here: https://github.com/tinonetic/abp_efcore_console_app

This may or may not have influenced the issue, but I created the solution as follows:

1. created an ABP app using  `abp new MyApp -t app`
2. created a console app using `abp new MyApp.Console -t console`
3. Integrated the two
4. Followed instructions from: https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL

@pualfu Already tried that. Refer to my post

**Comment by maliming** [comment]
Add `typeof(MyAppEntityFrameworkCoreModule)` to https://github.com/tinonetic/abp_efcore_console_app/blob/main/src/MyApp.Console/ConsoleModule.cs#L11

**Comment by tinonetic** [comment]
Thank-you @maliming!

I thought I had tried it, but realised I **had added the wrong dependency**: `AbpEntityFrameworkCoreModule`
