### ISSUE TITLE
[SQLite DBMS] .DbMigrator won't create migration files. 

### ISSUE THREAD

**Issue by kayagultekin** [abpframework/abp#7337]
Abp 4.1 and 4.2.0-rc.2 > EF Core & MVC

Running the '.DbMigrator' won't create migration files which results in the need for the developer to create migrations manually..

Reproduction steps: 

- in 4.1 the problem occured while following the [directions in the documentation](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-SQLite).

- in 4.2.0-rc.2  the problem occured while following the [directions in the blog post](https://blog.abp.io/abp/ABP-IO-Platform-v4-2-RC-Has-Been-Released).

**Comment by maliming** [comment]
> Running the '.DbMigrator' won't create migration files 

Are you using the `JetBrains Rider`?

**Comment by kayagultekin** [comment]
I have `JetBrains Rider` installed on my machine but I have the same issue on `Microsoft Visual Studio Community 2019 Version 16.8.4` 
![resim](https://user-images.githubusercontent.com/10141771/105147742-a45c8d80-5b12-11eb-8c0d-069390663226.png)
and there still is neither a `Migrations` folder under `.EntityframeworkCore.DbMigrations`  nor a `.db` file in sight.

**Comment by yekalkan** [comment]
@kayagultekin I guess it is related to some setting in your Visual studio.

try `dotnet run` to run *.DbMigrator project.

**Comment by kayagultekin** [comment]
Actually I have tried that but it hangs at this point.. Even after I uninstalled and installed abp tool again... Any pointers?

![resim](https://user-images.githubusercontent.com/10141771/105174509-b7338a00-5b33-11eb-9ef9-332500914476.png)

**Comment by kayagultekin** [comment]
> @kayagultekin I guess it is related to some setting in your Visual studio.

After I upgraded CLI to 4.2.1 it warned me clearly that dotnet-ef would be missing and the issue solved after I installed [`dotnet-ef`](https://www.nuget.org/packages/dotnet-ef/). Thank you for your time.

**Comment by X-Lucifer** [comment]
> > @kayagultekin I guess it is related to some setting in your Visual studio.
> 
> After I upgraded CLI to 4.2.1 it warned me clearly that dotnet-ef would be missing and the issue solved after I installed [`dotnet-ef`](https://www.nuget.org/packages/dotnet-ef/). Thank you for your time.

### It worked and solved my problem!
