### ISSUE TITLE
[SQLite DBMS] .DbMigrator and .Web connectionString creates multiple SQLite db files.

### ISSUE THREAD

**Issue by kayagultekin** [abpframework/abp#7338]
Abp 4.1 > EF Core & MVC

And '.DbMigrator' applies the migrations on the db file created in .DbMigrator project. I believe this is because ofthe relative Filename in [Change the Connection Strings in Switch to EF Core SQLite Provider](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-SQLite#change-the-connection-strings) `"Default": "Filename=./MySQLiteDBFile.sqlite"` Which seems to be solved in 4.2.0-rc.2 (But I'll be adding new issues on that too soon.)

Reproduction steps: 

- in 4.1 the problem occured while following the [directions in the documentation](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-SQLite).

**Comment by maliming** [comment]
> Which seems to be solved in 4.2.0-rc.2

Yes. https://github.com/abpframework/abp/pull/6855
