### ISSUE TITLE
[SQLite DBMS] in 4.2.0-rc.2 JSON issues in ConnectionStrings

### ISSUE THREAD

**Issue by kayagultekin** [abpframework/abp#7339]
Abp 4.2.0-rc.2 > EF Core & MVC

- System.FormatException: Could not parse the JSON file. ... The string should be correctly escaped ... (I believe this is because the single - unescaped backslahes in the resulted connection string) After escaping those, the new problem is: 
- ArgumentException: Connection string keyword 'version' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181. After removing the version argument.  The issues are face that I stated in #7337 

Reproduction steps: 

- in 4.2.0-rc.2  the problem occured while following the [directions in the blog post](https://blog.abp.io/abp/ABP-IO-Platform-v4-2-RC-Has-Been-Released).

**Comment by maliming** [comment]
```json
  "ConnectionStrings": {
    "Default": "Data Source=C:\Users\Desktop\database\BookStore.db;Version=3;"
  },
```

The connection needs to be escaped. `C:\\Users\\Desktop\\`

**Comment by maliming** [comment]
```ps1
C:\Users\Desktop\src\BookStore.DbMigrator>[INF] ABP CLI (https://abp.io)
[INF] Version 4.2.0-rc.2 (Prerelease)
[INF] Started database migrations...       
[INF] Migrating schema for host database...
Unhandled exception. System.ArgumentException: Connection string keyword 'version' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.
   at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder.GetIndex(String keyword)
```

https://github.com/aspnet/Microsoft.Data.Sqlite/issues/406#issuecomment-324689331
