### ISSUE TITLE
IdentityServer.EntityFrameworkCore MySQL Error

### ISSUE THREAD

**Issue by Goxy-cl** [abpframework/abp#734]
I notice that the entity ClientPostLogoutRedirectUri configured to use ClientId and PostLogoutRedirectUri as primary key, but property of PostLogoutRedirectUri configured to 2000 maxlength. Then we got an error of 'Specified key was too long; max key length is 3072 bytes' when we try to update the database. 

It's really not a good idea to use such a long key in database actually.

**Comment by Goxy-cl** [comment]
Add it also happens in entity ClientRedirectUri

**Comment by hikalkan** [comment]
Thank you @Goxy-cl for reporting that.
