### ISSUE TITLE
How to indicate the current tenant on an angular page?

### ISSUE THREAD

**Issue by andre-artus** [abpframework/abp#7346]
I wish to show the name of the current tenant on my angular pages.  I've looked at injecting MultiTenancyService and AbpTenantService, but those do not seem to work.

e.g.

```
  constructor(
    private oAuthService: OAuthService,
    private authService: AuthService,
    private tenantService: MultiTenancyService
  ) {}

  ngOnInit(): void {
  // returns HOST
    this.tenantName = this.tenantService?.domainTenant?.name ?? 'HOST';
  }
```

**Comment by davidzwa** [comment]
SessionStateService and getTenant() and the result's name property should give you what you need.

**Comment by andre-artus** [comment]
@davidzwa ,

Thank you. That works.

`this.tenantName = this.sessionStateService.getTenant().name ?? 'HOST';`

Can getTenant() return null?

**Comment by davidzwa** [comment]
That could very well be, but only if the application was either:
- not configured at start (`skipGetAppConfiguration` boolean flag in your AppModule or other module `CoreModule.forRoot()` call)
- failed to set session state default (check abpSession's tenant in localStorage to see what I mean; quite unlikely this ever fails)

So, as you might notice: quite unlikely, but possible in worst case. I'd be more careful with checking if the tenant name/id are valid, as I ran into that problem 15 minutes ago when switching from environments ;)

**Comment by armanozak** [comment]
Thank you @davidzwa.

Hi @andre-artus, I'm guessing your question is answered already. Can we close the issue?

**Comment by ilkayilknur** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.
