### ISSUE TITLE
How to inject (use) IOptions<SomeConfig> into ConfigureService ?

### ISSUE THREAD

**Issue by sebitsi** [abpframework/abp#7347]
Hi, 

is it possible to inject IOptions<> or any other dependent object inside ConfigureService method ?

I'm trying to implement swagger DocInclusionPredicate in  services.AddSwaggerGen registration.
This predicate need some configuration data i defined in some other module in PreConfigureService ?

If not is there any option to solve this ? Other than global static class ?

Thanks

**Comment by ilkayilknur** [comment]
Yes, you can get the options from the `IServiceCollection` instance. Let's say that you need to access the `AbpNavigationOptions`. 
```csharp
services.BuildServiceProvider();
var navigationOptions = services.GetRequiredServiceLazy<IOptions<AbpNavigationOptions>>();
```

**Comment by sebitsi** [comment]
@ilkayilknur Thanks for your response.

GetRequiredServiceLazy<T> returns null. I replaced it with GetReuiredService<T> and it works.

What is are diferences between each other ? What is purpose of lazy method ?. I mean how it works ?

Is there any documentation about this features ? I didn't find it in module's section.

Thanks

**Comment by sebitsi** [comment]
@ilkayilknur Just another subquestion:

What is difference between this two:

```
var p = context.Services.BuildServiceProvider();
var z = context.Services.GetRequiredServiceLazy<IOptions<AbpNavigationOptions>>().Value;
var a = p.GetRequiredService<IOptions<AbpNavigationOptions>>();
```

both works.
