### ISSUE TITLE
DebugLoggerFactoryExtensions.AddDebug(ILoggerFactory)' is obsolete

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#735]
StartUp.cs in Project Template may need updating:

Warning	CS0618	'DebugLoggerFactoryExtensions.AddDebug(ILoggerFactory)' is obsolete: 'This method is obsolete and will be removed in a future version. The recommended alternative is AddDebug(this ILoggingBuilder builder).'	Gp.Web	C:\Users\274188a\source\repos\Gp\src\Gp.Web\Startup.cs	24	Active

**Comment by hikalkan** [comment]
Already done
