### ISSUE TITLE
[BloBStoring] How to control the ACL of AWS S3 when saving?

### ISSUE THREAD

**Issue by Rwing** [abpframework/abp#7353]
I wanna set S3CannedACL.PublicRead when saving file, but it doesn't look like it supports doing that.
```
IBlobContainer.SaveAsync(string name, byte[] bytes, bool overrideExisting)
```

**Comment by maliming** [comment]
`IBlobContainer `is abstract, you can override or replace services to do more features.
https://github.com/abpframework/abp/issues/4989#issuecomment-670577121

**Comment by escobar5** [comment]
I'm struggling to add more features to IBlobContainer, any suggestion? do I have to use ReplaceServices?
