### ISSUE TITLE
ABP CLI: Unable to download old version of template

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#7356]
Ensure that there is no template cache locally

`abp new BookStore -t app -v 4.0.0`

![image](https://user-images.githubusercontent.com/16813853/105122989-3b751580-5b12-11eb-9076-4698d6d77e7d.png)

**Comment by maliming** [comment]
@ismcagdas  The download problem still exists.

**Comment by ismcagdas** [comment]
Fixed for v4.0 and v4.02. Waiting for abp.io websites to update.
