### ISSUE TITLE
Converting Initial Boilerplate to MySQL Entity Framework not working

### ISSUE THREAD

**Issue by ricxsar** [abpframework/abp#7366]
I'm trying to convert the Initial Boilerplate to use MySQL instead of MS SQL by following the [docs](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-MySQL). 

However, the **AlphaSys.Internal.EntityFrameworkCore.DbMigrations** project throws an error about **UseMySQL** method:
![image](https://user-images.githubusercontent.com/8968902/105271942-62475080-5bd3-11eb-8929-38c4cb8df55e.png)

Everything checks out except this project. Could you investigate this and confirm that this works?

If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version: 4.1.2**.
* Your database provider (EF Core)
* Exception message and **stack trace** if available (check the logs).
```
AlphaSys.Internal.EntityFrameworkCore.DbMigrations\EntityFrameworkCore\InternalMigrationsDbContextFactory.cs(20,18): error CS1501: No overload for method 'UseMySQL' takes 
2 arguments
```

**Comment by maliming** [comment]
hi 

Check the below link to get more information about `UseMysql `and `ServerVersion`

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1233

**Comment by realLiangshiwei** [comment]
`UseMySql`  instead of `UseMySQL`

![image](https://user-images.githubusercontent.com/16813853/105273600-9c662180-5bd6-11eb-8f18-3920557da541.png)

**Comment by ricxsar** [comment]
Ahh. Thanks for pointing it out. It's not obvious at first glance. Maybe put a better emphasis on the docs.
