### ISSUE TITLE
Using AssemblyLoadContext (.NET Core 5.0) to Implement Module hot loading

### ISSUE THREAD

**Issue by tanyo520** [abpframework/abp#7370]
Using AssemblyLoadContext (.NET Core 5.0) to Implement Module hot loading

**Comment by tanyo520** [comment]
I wrote a demo, but it seems that I can't clean up the services in the services when I uninstall it. As a result, when I install it again, the service is the same as the previous module。
[https://github.com/tanyo520/Volo.Abp.Hot](https://github.com/tanyo520/Volo.Abp.Hot)

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/PlugIn-Modules

**Comment by tanyo520** [comment]
> See https://docs.abp.io/en/abp/latest/PlugIn-Modules
Thank you very much for your reply. I haven't seen this function before.

**Can this support uninstall?**
