### ISSUE TITLE
Login Page in __________.HttpApi.Host with seperate identity server 

### ISSUE THREAD

**Issue by muhammedshaaban7** [abpframework/abp#7371]
Kindly i want to make a login page (razor view not razor page) in Abp in a layer (__.**HttpApi.Host**) where there is **HomeController**
contain : 
        **public ActionResult Index()
        {
            return Redirect("~/swagger");
        }**
so i want to make razor view to login in swagger or hangfire like ASP.NET Zero but i had no luck .
Any Example or reference applies this login page using Abp..
Note : i cannot login from this layer or use SignInManager to login.

kindly check attached image.
![image](https://user-images.githubusercontent.com/64292395/105328337-fec41f80-5be0-11eb-9085-1b3399864531.png)

 Thank You

**Comment by ilkayilknur** [comment]
@maliming Can you take a look at this, please?

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* **Tiered (MVC) or Identity Server Seperated (Angular)**:  yes / no

**Comment by muhammedshaaban7** [comment]
Thanks for your response @maliming 

ABP Version: **3.2**.
**Identity server separated(angular)** yes.

UI Framework: Angular with Identity Server Separated like below attached
![image](https://user-images.githubusercontent.com/64292395/105633513-1235eb80-5e6a-11eb-8c32-9ef6c2819bc7.png)

**Comment by muhammedshaaban7** [comment]
Any update you may have would be greatly appreciated

**Comment by muhammedshaaban7** [comment]
Kindly any updates

**Comment by muhammedshaaban7** [comment]
@maliming any updates

**Comment by muhammedshaaban7** [comment]
Any updates

**Comment by muhammedshaaban7** [comment]
Kindly your support @ilkayilknur

**Comment by muhammedshaaban7** [comment]
Any Updates, So I can say that there is no solution to this issue

**Comment by muhammedshaaban7** [comment]
Kindly Any Updates

**Comment by maliming** [comment]
hi @muhammedshaaban7  Please create a new issue.
