### ISSUE TITLE
DbMigrator error

### ISSUE THREAD

**Issue by tanghaojie** [abpframework/abp#7372]
i just change default database to postgres, follow [https://docs.abp.io/en/abp/latest/Entity-Framework-Core-PostgreSQL](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-PostgreSQL)

when run *.DbMigrator, cause error

![image](https://user-images.githubusercontent.com/14171892/105330781-a5beb080-5c0d-11eb-9c1a-eebf78d9a815.png)

**Comment by yekalkan** [comment]
If you downloaded a project with `--preview` argument, you need to upgrade CLI to preview version.

`dotnet tool update -g Volo.Abp.Cli --version 4.2.0-rc.2`

**Comment by tanghaojie** [comment]
not have warn, but nothing happen.
![image](https://user-images.githubusercontent.com/14171892/105358418-1a571680-5c31-11eb-83f2-84901f136996.png)

**Comment by yekalkan** [comment]
Use `dotnet run` to run *DbMigrator project.

**Comment by tanghaojie** [comment]
Nothing happend, too
![image](https://user-images.githubusercontent.com/14171892/105367579-8b9bc700-5c3b-11eb-81ec-790b7725f4fd.png)

**Comment by cristiandmonda** [comment]
I've had the same problem in a new project with EF and MSSQL. It looks like the DbMigrator is not creating the initial migration, I added it using the Package Manager Console.

**Comment by evrame** [comment]
Having the same issue on Ubuntu 22.04.
Here is what happens when I ```dotnet run``` :
![Screenshot from 2022-06-24 01-14-58](https://user-images.githubusercontent.com/66332895/175430394-8227b5e3-75fe-443b-bf20-e9aa9599212e.png)

.net 6 SDK and Abp Cli version 5.3.0

**Comment by realLiangshiwei** [comment]
@evrame 
Please create a new issue, thanks

**Comment by evrame** [comment]
@realLiangshiwei no need, it magically worked without changing anything, cannot reproduce it.

Thanks
