### ISSUE TITLE
Add mapping for IdentityServer module ApiResourceProperty

### ISSUE THREAD

**Issue by dazsco** [abpframework/abp#7373]
The Properties type of IdentityServer4.Models.ApiResource is IDictionary<string, string>

**Comment by ilkayilknur** [comment]
Could you elaborate on the question, please?

**Comment by dazsco** [comment]
@ilkayilknur  it should add in IdentityServerAutoMapperProfile class 
       method CreateApiResourceMap():
   `  CreateMap<ApiResourceProperty, KeyValuePair<string, string>>()
                .ReverseMap();`
just like CreateClientMap()

**Comment by dazsco** [comment]
@maliming  I think it should be released in 4.2. If ApiResourceProperty is set in the abp official demo, it will report an error.

**Comment by maliming** [comment]
You are right. I will handle it.
