### ISSUE TITLE
Will it support unloading and reloading in the future?

### ISSUE THREAD

**Issue by tanyo520** [abpframework/abp#7375]
[PlugIn-Modules  ](https://docs.abp.io/en/abp/latest/PlugIn-Modules)
Will it support unloading and reloading in the future？

**Comment by hikalkan** [comment]
We don't have a plan for that. It may be technically not possible, because AspNet Core investigates controllers at the application startup. Also, Dependency Injection registration is only done on the application startup. So, if a module is loaded on runtime, I don't know how it can work.
