### ISSUE TITLE
Article/Tutorial Login without tenant option and loaded with a predefined tenant

### ISSUE THREAD

**Issue by pvaz** [abpframework/abp#7379]
How to use login without tenant selection option and to be able to call the login with a specific tenant pre-selected.

What I mean is to have the way to call the login with a predefined tenant name when calling it and to hide the tenanat selection option.

Thanks,
Paulo

**Comment by maliming** [comment]
You can override the default razor page to hide `tenant selection`.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Account.cshtml#L59-L85
