### ISSUE TITLE
Logout Angular web app

### ISSUE THREAD

**Issue by abdulhakim1976** [abpframework/abp#7390]
* Your **ABP Framework version**.:4.0.2
* Your **User Interface** : Angular
* Your database provider : EF Core

----------------------------------------------------------
If I logged out, I can't login again
To login, I have to login using api via swagger, and this enable me to login as host only
after logged in as Host, If I logged out I got the following error

I tried alot of clearing cookies with no success to login again

![image](https://user-images.githubusercontent.com/7611929/105380497-9e4fd500-5c16-11eb-9fcf-84bf367b8a01.png)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by abdulhakim1976** [comment]
Steps:
- I dropped my sql server database
- I ran the migrator to build & create the database again
- I seeded the system with a tenant & tenant admin user (tenant: wnt, user: admin, pass:1q2w3E*)
- I'm tried to login as Host with "admin" & "1q2w3E*" as usual, but I can't
- I'm tried using Account/login api provided by Swagger to login as Tenant admin, I got success message
-  When I went to login page and clicked the login button, I logged in  automatically as Host admin not tenant admin
- Once I click the logout button, I got the error as per attached

**Comment by maliming** [comment]
Can you check your application logs?
