### ISSUE TITLE
Row Level Authorization

### ISSUE THREAD

**Issue by gdirikgil** [abpframework/abp#7392]
Will Abp supports row level authorization in the future?
I mean I want to restrict access to the rows of one or more entities based on the rights or the role of the current user.

**Comment by realLiangshiwei** [comment]
Duplicate of https://github.com/abpframework/abp/issues/236

**Comment by gdirikgil** [comment]
Could you give me the of link of duplicated issue?

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/236
