### ISSUE TITLE
Refresh menu navigation after permissions are changed

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#741]
Is there a proper way to refresh the menu navigation after permissions are changed?  I am using the abp standard user and roles with menu items that have visibility controlled by the permissions.  Currently I have to manually refresh the page.

**Comment by hikalkan** [comment]
Hi,

It's hard to understand a permission change effects the menu elements and tell the client to refresh it. If you change your own permissions, then you can refresh the page. If you change another user's permission and the user is actively using the application, he/she will see the effect after the next page change. If he/she clicks a menu item that's permission is revoked then an authorization exception is thrown. Then he/she clicks the back button and the related menu element disappears :)

**Comment by djlaney3** [comment]
You bring up some good points.  In my case, I was strictly thinking about a user changing their own permissions.  Simple enough to refresh the page.

**Comment by alexandis** [comment]
I use this method to switch between Tenants:

```
  switch(tenant: Models.Common.Lookup<string>) {
    this.oAuthService.configure(this.environment.oAuthConfig);
    let loadingToasterId = Number(this.toaster.info('::Tenants:PleaseWait', '::Tenants:Switching', { ...this.toasterOptions && { sticky: true } }));
    return from(this.oAuthService.loadDiscoveryDocument())
      .pipe
      (
        switchMap(() => from(this.oAuthService.fetchTokenUsingGrant('switch_tenant', { token: this.oAuthService.getAccessToken(), tenant: tenant.id }))),
        take(1)
      )
      .subscribe({
        complete: () => {
          this.toaster.remove(loadingToasterId);
          this.toaster.success('::Tenants:SwitchingSucceeded', '::Tenants:Switching', { ...this.toasterOptions && { life: 2000 } });
          this.sessionStateService.setTenant({ id: tenant.id, name: tenant.displayName, isAvailable: true } as CurrentTenantDto);
          this.configStateService.refreshAppState().subscribe(x => {
            this.router.navigate(['/'], { skipLocationChange: false, onSameUrlNavigation: 'reload' }).then(ready => {
              if (ready) {
                window.location.reload();
              }
            });
          });
        },
        error: () => {
          this.toaster.remove(loadingToasterId);
          this.toaster.error('::Tenants:SwitchingFailed', '::Tenants:Switching', { ...this.toasterOptions && { life: 2000 } });
        }
      });
  }
```

I have to use `window.location.reload()` to refresh the menu according to permissions of the current tenant, otherwise the menu is not displayed correctly after switching, it is missing the child items which have to be visible in fact...

I don't know how to avoid `window.location.reload()`, because it looks ugly (not like SPA), but force menu reloading...
