### ISSUE TITLE
Abp cli new module folder structure feature request

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#7411]
When use abp cli to create a new module, the generated project doesn't have the folder structure.
Could you please support the folder structure, like "\Volo\Abp\Identity\\*.cs".
Detail please see the screenshot(the 1st is the abp cli new result, and the 2st is the expected result)
Thanks in advance if you can support this feature.

Example : abp new Volo.Abp.Identity -t module --preview
![image](https://user-images.githubusercontent.com/6952917/105476469-9f970580-5cdb-11eb-8169-0631fa68cfb2.png)

![image](https://user-images.githubusercontent.com/6952917/105476520-b3db0280-5cdb-11eb-89b0-a91e4d815cc6.png)

**Comment by hikalkan** [comment]
It was just like that before. But we then removed the unnecessary folder hierarch (see https://github.com/abpframework/abp/issues/585) by setting the root namespaces.
For most of the people this is simpler and enough.
We manually re-arrange folders when we want to create a new official module. It also takes time for us.
We can't support both approaches with a single template. So, we don't want to implement your suggestion, sorry.
