### ISSUE TITLE
AbpAspNetCoreMvcModule Version4.1.2, I don’t want to use System.Text.Json, what should I do

### ISSUE THREAD

**Issue by foxeveral** [abpframework/abp#7412]
System.Text.Json and Newtonsoft.Json use simultaneously has completely messed up my project，
Web page json can no longer deviate from the Newtonsoft.Json serialization format

**Comment by ilkayilknur** [comment]
You can use Newtonsoft.Json by disabling `HybridSerializer`. See https://docs.abp.io/en/abp/4.1/Migration-Guides/Abp-4_0#always-use-the-newtonsoft-json
