### ISSUE TITLE
How to user IRemoteStreamContent with BLOB Storing Azure Provider

### ISSUE THREAD

**Issue by kishoresahas** [abpframework/abp#7418]
### Documentation
https://docs.abp.io/en/abp/latest/Blob-Storing-Azure
https://docs.abp.io/en/abp/latest/Application-Services#working-with-streams

## Issue 
Return empty response

Note - But works with FileSteam

## Steps needed to **reproduce** the problem.
* **ABP Framework version** 3.3.2.
```
public async Task<IRemoteStreamContent> DownloadAsync(string path)
{
    if (path == null) return await Task.FromResult(
        (IRemoteStreamContent)new RemoteStreamContent(new MemoryStream()));

    var fs = await blobContainer.GetAsync(path);

    var result = new RemoteStreamContent(fs)
    {
        ContentType = "application/octet-stream"
    };

    return await Task.FromResult(result);
}
```

**Comment by maliming** [comment]
hi
Can you confirm that stream has any data?
```
var fs = await blobContainer.GetAsync(path);
```

**Comment by kishoresahas** [comment]
> hi
> Can you confirm that stream has any data?
> 
> ```
> var fs = await blobContainer.GetAsync(path);
> ```

Yes, Confirmed!

**Comment by maliming** [comment]
Try this:
```cs
var fs = await blobContainer.GetAsync(path);
fs.Position = 0;
var result = new RemoteStreamContent(fs)
{
    ContentType = "application/octet-stream"
};
```
