### ISSUE TITLE
Dataseed is not working

### ISSUE THREAD

**Issue by MuhammadRashed** [abpframework/abp#7424]
* ABP Framework version 4.1
* User Interface: All
* database provider(EF Core)
* Steps needed to **reproduce** the problem:

After following steps: https://docs.abp.io/en/abp/latest/Data-Seeding 
I added the IDataSeedContributor implementation on application project, Data seed was not migrated to database,

**Comment by maliming** [comment]
Have you run the `DbMigrator`?

**Comment by MuhammadRashed** [comment]
Yes sure, I ran it but did not work
I knew the solution it was because it was located Application project not domain project (that was not clear in documentation)

background:
I was trying to migrate some roles and permissions, I had to do it on application level because permission constants were not in domain shared
