### ISSUE TITLE
ngx-datatable virtualization with abp ListService

### ISSUE THREAD

**Issue by joernz** [abpframework/abp#7427]
* Your **ABP Framework version**. **4.1**
* Your **User Interface** type **Angular**
* Your database provider **EF Core**

The Input `virtualization` of ngx-datatable is always [set by default as `true`](https://swimlane.gitbook.io/ngx-datatable/api/table/inputs#virtualization). But it appears not compatible with Abp ListService. 
I'm currently leaning the BookStore tutorials using the [row-detail table](http://swimlane.github.io/ngx-datatable/#row-details). I tried to leave out `[list]="list" default` and some other things like the card class, which I don't want to, and then it worked. But still, ListService has the `maxResultCount` set as a limit, this limit can be of course changed, but it is blocking the virtual scroll whenever the scroll hits the limit, if the database has more entities, they will not be rendered.

Btw, in this table I also can't get the [filter with ListService](https://docs.abp.io/en/abp/4.1/UI/Angular/List-Service#how-to-implement-server-side-search-in-a-table) working. Maybe didn't understand it correctly and it takes more than just this one line of code to get to it, so a sample/tutorial would be much appreciate. 

Thanks a lot for the help in advance. I'm just get started with abp, and highly amazed by you guys' work.

**Comment by mehmet-erim** [comment]
Hello @joernz 

The `NgxDatatableDefaultDirective` and the `NgxDatatableListDirective` directives are created to facilitate the use of `ngx-datatable`. The directives set values to some inputs of the table to be able to use the table quickly.
So you are free to not use these directives.

See some content of the `NgxDatatableDefaultDirective`:

```ts
  @Input() class = 'material bordered';

  @HostBinding('class')
  get classes(): string {
    return `ngx-datatable ${this.class}`;
  }

  constructor(private table: DatatableComponent, @Inject(DOCUMENT) private document: MockDocument) {
    this.table.columnMode = ColumnMode.force;
    this.table.footerHeight = 50;
    this.table.headerHeight = 50;
    this.table.rowHeight = 'auto';
    this.table.scrollbarH = true;
    this.table.virtualization = false;
  }
```

If you would not use the directive, you can set the input values shown above manually.

Take a look at the variables of the table set by the `NgxDatatableListDirective`:

```ts
    this.table.externalPaging = true;
    this.table.externalSorting = true;
    this.table.messages = {
      emptyMessage: this.localizationService.localizeSync(
        'AbpUi',
        'NoDataAvailableInDatatable',
        'No data available',
      ),
      totalMessage: this.localizationService.localizeSync('AbpUi', 'Total', 'total'),
      selectedMessage: this.localizationService.localizeSync('AbpUi', 'Selected', 'selected'),
    };

    this.table.limit = maxResultCount;
    this.table.offset = page;
```

If you do not use the `NgxDatatableListDirective`, you have to manage the table inputs shown above manually.

---

You can change the `maxResultCount` by using the `ListService`, to achieve this, see the documentation:
https://docs.abp.io/en/abp/latest/UI/Angular/List-Service

---

The default values of the `NgxDatatableDefaultDirective` can be overridden.
For example, set virtualization input to true and set a custom class like this:

```html
<ngx-datatable
      class="custom-class-name"
      [rows]="data$ | async"
      [count]="totalCount$ | async"
      [list]="list"
      default
      [virtualization]="true"
    >
```

**Comment by joernz** [comment]
hi @mehmet-erim thanks a lot, it's very helpful. I just tested it in my app, `[virtualization]="true"` did the work overriding the `NgxDatatableDefaultDirective`. However, the virtual scroll is still not working properly, 

I looked into this [demo table](http://swimlane.github.io/ngx-datatable/#row-details), when paged.
They are not setting a limit (undefined) and not even counting, see the screenshot. 
Could we do this with `ListService` as well? please advise. I need my table to work exactly like this demo table.

![image](https://user-images.githubusercontent.com/75144099/105819374-65b64f80-5fb8-11eb-970a-0439be2914bd.png)

**Comment by mehmet-erim** [comment]
`ListService` is created for easy pagination. You don't have to use the ListService.
To help you better, please explain in detail what exactly you want to do.
