### ISSUE TITLE
Link SOCIAL not working

### ISSUE THREAD

**Issue by bartvanhoey** [abpframework/abp#7429]
![social_link_not_working](https://user-images.githubusercontent.com/2319374/105575667-9ce4f080-5d6d-11eb-9174-fefa8b4ff45d.JPG)

When you click on the Author (bartvanhoey) of a community article,   You arrive on the overview page of member Bart Van Hoey. 

Clicking on the SOCIAL (OctoCat icon) in that page doesn't bring the user  to the  GitHub repository of Bart Van Hoey,
instead of seeing the correct GitHub repository, the user lands on a 404 page.

Can this please be fixed? thanks.

**Comment by berkansasmaz** [comment]
Hello, thank you for your feedback. However, I don't think it's a problem.

It looks like you have entered your Github name, but Github finds and redirects users with their username. Can you enter "BartVanHoey" in the Github Username field?

Finally, thank you for your support to the community.

**Comment by berkansasmaz** [comment]
Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Comment by bartvanhoey** [comment]
Hello, Thank you for the quick response. My github name was indeed with spaces ...

**Comment by bartvanhoey** [comment]
Maybe prevent the user entering spaces in name ... issue will happen again :-)
