### ISSUE TITLE
Failed to load API definition.

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#743]
> [ERR] An unhandled exception has occurred while executing the request.
> System.InvalidOperationException: Conflicting schemaIds: Identical schemaIds detected for types Volo.Docs.Admin.Projects.ProjectDto and Volo.Docs.Projects.ProjectDto. See config settings - "CustomSchemaIds" for a workaround
>    at Swashbuckle.AspNetCore.SwaggerGen.SchemaIdManager.IdFor(Type type)

**Comment by hikalkan** [comment]
I suppose the swagger can't handle same DTO type even in different namespaces. We may rename it or use `Swashbuckle.AspNetCore.SwaggerGen.SchemaIdManager.IdFor` option. Thanks for reporting this.
