### ISSUE TITLE
Add Exist() to IDistributedCache interface

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#7436]
I tried to store null value into redis and I checked redis and found the data hash field to be null which worked as expected. However, because the lack of exist(TKey key) function, I have to visit database everytime even I store the null value for the specific key in the redis.
![image](https://user-images.githubusercontent.com/7014849/105624536-4c4cc080-5e5d-11eb-9f76-73e96308fb92.png)

**Comment by maliming** [comment]
The microsoft implementation doesn't have a similar method.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.idistributedcache

**Comment by davidzwa** [comment]
Can we track which keys are in the cache with an extra cache? Sounds redundant, but it could be very nice for debugging.

**Comment by slarkerino** [comment]
![image](https://user-images.githubusercontent.com/7014849/106125743-75d85580-6197-11eb-9413-7674c3855c09.png)

I have checked how abp store value in cache, it actually encapsulate the value into hash. So it is possible to store null value in cache. I just felt we lack a way to check if a certain key is exist or to get the key(have no idea how abp serialize the key when use the injected cache service) and implement the check logic using some other framework(like stachexchange redis).
