### ISSUE TITLE
Angular app shows Unknown Error on Nginx

### ISSUE THREAD

**Issue by andre-artus** [abpframework/abp#7437]
I have an ABP app generated with the Angular template. I'm trying to get it to work with Nginx on Ubuntu, but I keep getting an "unknown" error:

**An error has occurred!**
Http failure response for https://api.[domain]/api/abp/application-configuration: 0 Unknown Error

But when I open the url I do get a json file with amongst other things some localization info.

I have Nginx set up to direct api.[domain] to the ASP.Net Core app listening at port 5000. It is also set up to send [domain] to /var/www/[apname] where the Angular portion resides.

I can open the Swagger UI from https://api.[domain], I can also log in via https://api.[domain]/Account/Login, so I'm comfortable that that is working.

I can open static HTML pages from  https://[domain].

Attached is a copy of my [logs.txt](https://github.com/abpframework/abp/files/5861848/logs.txt).

Looking at the browser/debug logs I see:

```
null: error loading discovery document HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: 'Unknown Error', url: 'https://api.[DOMAIN]/.well-known/openid-configuration', ok: false, …}
```
and
```
null: ERROR HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: 'Unknown Error', url: 'https://api.[DOMAIN]/api/abp/application-configuration', ok: false, …}
```

But copying and opening either of those URLs in a browser or Postman will return data.

I'm not sure I've modified al the necessary ABP configuraton points, or maybe I misunderstood what their values should be, so I'll list them here:

### Angular
[environment.ts]
```
const baseUrl = 'https://[DOMAIN]';

export const environment = {
  production: true,
  application: {
    baseUrl,
    name: '[APPNAME]',
    logoUrl: '',
  },
  oAuthConfig: {
    issuer: 'https://api.[DOMAIN]',
    redirectUri: baseUrl,
    clientId: '[APPNAME]_App',
    responseType: 'code',
    scope: 'offline_access [APPNAME]',
  },
  apis: {
    default: {
      url: 'https://api.[DOMAIN]',
      rootNamespace: '[APPNAME]',
    },
  },
} as Environment;

```

### ASP.Net Core
[appsettings.json]
```
  "App": {
    "SelfUrl": "https://[DOMAIN]",
    "CorsOrigins": "https://*.[DOMAIN],http://localhost:4200,https://localhost:44307"
  },
  "AuthServer": {
    "Authority": "https://[DOMAIN]",
    "RequireHttpsMetadata": "false"
  },
```

**Comment by mtozlu** [comment]
Hi,
I'm sorry if it's not relevant, please check this documentation:
https://docs.abp.io/en/abp/latest/Multi-Tenancy#problems-with-the-nginx

**Comment by andre-artus** [comment]
Thank you very much @mtozlu, 

I read that but did not think it relevant because I was not trying to access a tenant yet, but it was.

I changed the Nginx configuration (`nginx.conf'`) by adding `underscores_in_headers on;` and the home page can now load.

Perhaps additional information can be written into the docs, for example that the Nginx issue would show up as an "Unknown Error".

It did however reveal a new set of problems:

`Access to XMLHttpRequest at 'https://api.[DOMAIN]/.well-known/openid-configuration' from origin 'https://[DOMAIN]' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://[DOMAIN], https://[DOMAIN]', but only one is allowed.`

But when I remove the add_header line from my API's `server` config then I get this:

`Access to XMLHttpRequest at 'https://api.[DOMAIN]/api/abp/application-configuration' from origin 'https://[DOMAIN]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

It's either too hot or too cold, Goldilocks is not happy.

**Comment by mtozlu** [comment]
`openid-configuration` comes from identityserver. `application-configuration` comes from your api project.
So add your client's url to appsettings file (App:CorsOrigins setting) for both projects (http.host project and identityserver project if you use separate identity server) and it should work.

**Comment by andre-artus** [comment]
Thanks @mtozlu . I had to change it to '*.[DOMAIN' and it worked.

I've got more issues arising, but I try to deal with them myself. 

Once again a heartfelt thank you, I was pulling my hair out.

**Comment by mtozlu** [comment]
Walked in the same boots :) 
That's why i'm trying to help.

**Comment by andre-artus** [comment]
I would like t
