### ISSUE TITLE
How to remove entity from a collection of aggregate with EF Core ?

### ISSUE THREAD

**Issue by tsupakit** [abpframework/abp#7451]
Hi,

I am looking for a way to remove an entity from a collection of aggregate in a proper DDD + ORM way.
I knew that removing entity from collection of aggregate and UpdateAsync (SaveChanges by EF Core) would not work.

I could not find this in the documentation.

Thanks,

**Comment by enisn** [comment]
Do you want to remove permanently? If yes, make it that collection just another aggregate root. If you don't use them together that means they're not same aggregate.

Or, are you asking about ignoring for a single operation?

**Comment by tsupakit** [comment]
Yes, I want to remove it permanently.

It's not suppose to be an aggregate. for instance, I want to delete order detail from order.

**Comment by enisn** [comment]
Have you checked [the example domain](https://docs.abp.io/en/abp/latest/Domain-Driven-Design-Implementation-Guide#the-example-domain) document. 

Your case is similar with that case. Issue is a part of a repository but it's another **AggregateRoot**. In your case, **OrderDetail** looks just another **AggregateRoot** and has it's own aggregate tree such as for example buyer, shipping info, payment method etc.

Let me know if it makes more clear or not @tsupakit  👍

**Comment by tsupakit** [comment]
Regarding the example, what about if we want to remove comment from the issue. How could we do that ?
Just wondering the case of remove entity in a collection in aggregate particularly, regardless of the business and design.

I don't think making entity of the collection to be another aggregate is the right answer.
