### ISSUE TITLE
Migration to abp 4 : Client.AbpRemoteCallException : 'Unauthorized'

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#7452]
I'm trying to migrate from ABP 3.3 to 4.0 but I got an error and currently have no idea of the root cause.

Here is my code:

```
bool isAuthenticated = await _authenticationVerifier.IsAuthenticatedAsync();
if (isAuthenticated)
    User = await _userAppService.GetCurrentUserAsync();

// https://gunnarpeipman.com/client-side-blazor-authorizeview/
// https://github.com/dotnet/aspnetcore/blob/master/src/Components/Authorization/src/AuthorizeViewCore.cs
// https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1#implement-a-custom-authenticationstateprovider
private AuthenticationStateProvider _provider;
public async Task<bool> IsAuthenticatedAsync()
{
    var authState = await _provider.GetAuthenticationStateAsync();
    if (authState == null)
        return false;
    return authState.User.Identity.IsAuthenticated;
}
```

I got the following exception when calling 'GetCurrentUserAsync':

`Client.AbpRemoteCallException : 'Unauthorized'`

What is strange is that this code was working before attempting the migration to abp 4, and also the isAuhtenticated is true.

Do you have any idea? Even to debug such issue?

**Comment by maliming** [comment]
Please check the logs when you got an error.

**Comment by vd3d** [comment]
I have, but there is no log created, ie. no error is reported in the log :-(

To be accurate, it is a 3 tiers, so:
- identity server: no log
- API server: no log
- web : log, but with the same error and no more information

**Comment by vd3d** [comment]
Is there a way to increase the log level? I have no log and no exception on the API & Identity side... only on the web app side.

**Comment by vd3d** [comment]
I have been able to get more logs... here is what I got on the APi side:
2021-01-27 21:58:09.841 +01:00 [INF] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key: 
kid: 'ac0d2edf3c04d13cd95cc41b9b33ab03'.
Exceptions caught:
 ''. 
token: '{"alg":"RS256","kid":"ac0d2edf3c04d13cd95cc41b9b33ab03","typ":"at+jwt"}.{"nbf":1611487951,"exp":1643023951,"iss":"https://localhost:44385","aud":"SoCloze","client_id":"SoCloze_Web","sub":"8e6548d5-f35f-0275-bdc1-39f99db988d0","auth_time":1611487950,"idp":"Facebook","name":"christophe_demez","phone_number_verified":"False","email":"demez.christophe@gmail.com","email_verified":"True","scope":["openid","profile","email","phone","role","SoCloze"],"amr":["external"]}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2021-01-27 21:58:09.841 +01:00 [INF] BearerIdentityServerAuthenticationJwt was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match key: 
kid: 'ac0d2edf3c04d13cd95cc41b9b33ab03'.
Exceptions caught:
 ''. 
token: '{"alg":"RS256","kid":"ac0d2edf3c04d13cd95cc41b9b33ab03","typ":"at+jwt"}.{"nbf":1611487951,"exp":1643023951,"iss":"https://localhost:44385","aud":"SoCloze","client_id":"SoCloze_Web","sub":"8e6548d5-f35f-0275-bdc1-39f99db988d0","auth_time":1611487950,"idp":"Facebook","name":"christophe_demez","phone_number_verified":"False","email":"demez.christophe@gmail.com","email_verified":"True","scope":["openid","profile","email","phone","role","SoCloze"],"amr":["external"]}'.
2021-01-27 21:58:09.842 +01:00 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.

On the Identity side, I see the user is logged in.

Have you changed something for ABP 4.0.0 ?

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0

**Comment by vd3d** [comment]
Thanks, I have already check (again and again the migration guide) and do the changes on the database to support the new identity server, but no way... I can't find what is wrong / breaked

**Comment by maliming** [comment]
> BearerIdentityServerAuthenticationJwt was not authenticated. Failure message: IDX10501: Signature validation failed. Unable to match key:
kid: 'ac0d2edf3c04d13cd95cc41b9b33ab03'.

You should troubleshoot the problem based on this error message.

**Comment by vd3d** [comment]
Thanks @maliming,

I have noticed that since the migration to abp 4.0.0, a file name "tempkey.jwk" is generated!
I still have the previous "tempkey.rsa" ...

But what is generating this file ? and why is it generated ?

PS: the error I have looks to be related to this, not sure yet.

**Comment by maliming** [comment]
This more related to Identity Server, not abp.
