### ISSUE TITLE
abp.io not working - 502 bad gateway

### ISSUE THREAD

**Issue by brunobertechini** [abpframework/abp#7455]
https://abp.io is down. Public and commercial web sites not available and not able to restore any nuget packages using commercial.

![image](https://user-images.githubusercontent.com/5166528/105780415-82588480-5fc4-11eb-8a60-f8e335bdd75d.png)

**Comment by maliming** [comment]
Working on it. Thanks.

**Comment by learnabpframework** [comment]
abp.io still not working 

![image](https://user-images.githubusercontent.com/77593897/105793209-d5d6cc80-5fdc-11eb-9372-c865ac6abaf8.png)

**Comment by xdmushui** [comment]
![image](https://user-images.githubusercontent.com/3242057/105804611-306f2900-5fdb-11eb-981d-ffeca26635c3.png)

**Comment by haroldrandom** [comment]
While creating module, this also block me 

```Shell
[12:58:41 INF] ABP CLI (https://abp.io)
[12:58:42 INF] Version 4.1.2 (Stable)
[12:58:43 INF] Creating your project...
[12:58:43 INF] Project name: xxxxxxxx
[12:58:43 INF] Template: module
[12:58:43 INF] Create Solution Folder: no
[12:58:43 INF] Output folder: C:\xxxxxxxxxx
Error occured while getting the latest version from https://abp.io/api/download/template/get-version/ : '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[12:58:46 WRN] The remote service is currently unavailable, please specify the version.
[12:58:46 WRN] 
[12:58:46 WRN] Find the following template in your cache directory: 
[12:58:46 WRN]  Template Name   Version
[12:58:46 WRN] 
[12:58:46 WRN] Use command: abp new Acme.BookStore -v version
```

**Comment by ThreeLambs** [comment]
> While creating module, this also block me
> 
> ```shell
> [12:58:41 INF] ABP CLI (https://abp.io)
> [12:58:42 INF] Version 4.1.2 (Stable)
> [12:58:43 INF] Creating your project...
> [12:58:43 INF] Project name: xxxxxxxx
> [12:58:43 INF] Template: module
> [12:58:43 INF] Create Solution Folder: no
> [12:58:43 INF] Output folder: C:\xxxxxxxxxx
> Error occured while getting the latest version from https://abp.io/api/download/template/get-version/ : '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
> [12:58:46 WRN] The remote service is currently unavailable, please specify the version.
> [12:58:46 WRN] 
> [12:58:46 WRN] Find the following template in your cache directory: 
> [12:58:46 WRN]  Template Name   Version
> [12:58:46 WRN] 
> [12:58:46 WRN] Use command: abp new Acme.BookStore -v version
> ```

  you can use local source code
- download `abp.zip ` source code from github repository and use the command 
```
abp new demo -u mvc --local-framework-ref --abp-path E:\00\abp
```

**Comment by maliming** [comment]
Fixed.

**Comment by brunobertechini** [comment]
@maliming can you explain the problem? This was really a blocker during  *almost* the whole day.

**Comment by brunobertechini** [comment]
Do you have an RCA or incident analysis ?
