### ISSUE TITLE
How do I define a delegate in an application service that always throws an exception

### ISSUE THREAD

**Issue by CaiJinHao** [abpframework/abp#7457]
### Always throw exceptions:

Property accessor 'DeclaringMethod' on object 'System.RuntimeType' threw the following exception:'Method may only be called on a Type for which Type.IsGenericParameter is true.'

### my use
myAppService.UpdateEntityAction = () => { };
public class MyAppService:IMyAppService,ICrudAppService<...>
{
     public Action MyAction { get ; set ; }
     ...
}

### My question
How to Use Delegates in AppService

**Comment by maliming** [comment]
This seems to have nothing to do with abp.

**Comment by CaiJinHao** [comment]
thank you
