### ISSUE TITLE
Angular - Chart.js big include with CommonJS warning

### ISSUE THREAD

**Issue by davidzwa** [abpframework/abp#7472]
* Abp 4.2-rc2
* Angular v11 with respective @abp/ng.core, identity and tenant-management package
* Exception message 
```
Warning: PROJECT_PATH\angular\node_modules\@abp\ng.theme.shared\__ivy_ngcc__\fesm2015\abp-ng.theme.shared.js depends on 'chart.js'. CommonJS or AMD dependencies can cause 
optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
* Use any Angular ABP package which depends on the Theme Shared package.

### CommonJS warning
It's generally known that common Javascript packages cause this warning, and it's not a big deal especially since it is separated in a bundle. Still after a bundle analysis, `Chart.js` is a big increase in size (checked with `sourcemap-explorer`). Please consider finding a typing package or provide our own to have better optimization.

**Comment by mehmet-erim** [comment]
Hi @davidzwa 

It is already optimized by loading lazy. Please refer to [configuring commonjs dependencies doc](https://angular.io/guide/build#configuring-commonjs-dependencies) to disable the warning message.

**Comment by davidzwa** [comment]
I know that it is lazy-loaded and I am aware of the method of ignoring the warning. That does not mean we should not act on it. It's generally something which is postponed, and I get it.

It's important for projects **which do use it** which is most of the use cases. Bundle size optimization, lazy-loaded or not, is something we should always be ready to do i.m.o.

**Comment by davidzwa** [comment]
@mehmet-erim this is not a question as it is about optimization effort ;)

**Comment by mehmet-erim** [comment]
Try adding the provider below to your `app.module.ts` like this:

```ts
import { ..., THEME_SHARED_APPEND_CONTENT } from '@abp/ng.theme.shared';

@NgModule({
  // ...
  providers: [
    ...,
    { provide: THEME_SHARED_APPEND_CONTENT, useValue: {} },
  ],
})
export class AppModule {}
```

The `chart.js` will not be loaded after overriding the `THEME_SHARED_APPEND_CONTENT` injection token.

We will discuss about the optimization.

**Comment by davidzwa** [comment]
Feel free to close the issue whenever your triage has completed.

**Comment by mehmet-erim** [comment]
Please follow this issue @davidzwa. `THEME_SHARED_APPEND_CONTENT` may be removed or changed in v5.0. Because we might be removed the `chart.js` dependency from the @abp/ng.theme.shared in the future

**Comment by mehmet-erim** [comment]
Hi,

You don't need to override the `THEME_SHARED_APPEND_CONTENT` injection token as of v5.0.
Please take a look at [this PR](https://github.com/abpframework/abp/pull/10082) to see changes made about usage of the chart.js.

**Comment by davidzwa** [comment]
Awesome!
