### ISSUE TITLE
RabbitMqMessageConsumer can not trigger HandleIncomingMessageAsync 

### ISSUE THREAD

**Issue by iswing** [abpframework/abp#7476]
I try to upgrade abp version 3.3.1 to 4.1.2，IDistributedEventHandler<EntityUpdatedEto<MyEntityDto>>.HandleEventAsync can not be triggered and there are no exceptions，My rabbitMq admin UI  show all message Unacked (that means  message was read in memory but not ack),

when i rollback version  to 3.3.1,eventing is ok.

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#event-transfer-object

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#configuration
