### ISSUE TITLE
Separate Identity Server 

### ISSUE THREAD

**Issue by amsaighi** [abpframework/abp#7485]
### Separate Identity Server Issues

* My **ABP Framework version** : 3.1.2
* My **User Interface** Angular
* My database provider(EF Core)

I created a module ABP Framework with separate Identity Server using ( **ABP CLI** )
 , When i tried to connect with Identity Server, although I connected, I lost the all the information.

It can't local storage information.
![image](https://user-images.githubusercontent.com/3142753/106019889-6daee600-60c3-11eb-9b9e-e0084b2d9fc7.png)
![image](https://user-images.githubusercontent.com/3142753/106019976-861f0080-60c3-11eb-9568-a49e727b2a21.png)

Why !!

thank you

**Comment by maliming** [comment]
hi

I can't understand the problem.

**Comment by leonkosak** [comment]
Do you think that you login successfully and then there is no logged-in user in the top-right corner?
Do you have Redis installed and properly configured in appsettings.json?

**Comment by amsaighi** [comment]
Hi 
@maliming  When i click login, the method redirect my to Identity server, I authentifie, after this it redirect me to my angular application I lost all information us the image show.

@leonkosak Yes, I login successfully When I try to inspect information about my authentification, I lost all information.
Yes, I launched Redis a lot of time, and all my configuration are right.

**Comment by leonkosak** [comment]
Check Logs.txt for .HttpApi.Host and .IdentityServer projects. There must be something, believe me.

**Comment by davidzwa** [comment]
The fact that you have a Bearer token tells me that the LocalStorage is not empty. Please check on another browser as well, as a simple filter could also hide data.

Also please confirm that the LocalStorage was not empty before and send a screenshot. It's very hard to even reproduce right now.

**Comment by amsaighi** [comment]
@davidzwa I got the bearer token, and I'm sure that the local Storage is empty, 
I tried this exercice with all browser ( Chrome, Mozilla, Brave, Edge) the same result

**Comment by amsaighi** [comment]
@leonkosak no Error in both of them (log.txt)

**Comment by davidzwa** [comment]
Checked SessionStorage and Cookies? I did not have this behaviour in the default template with split IDS4 and Angular, so you have to provide us reproduction.

Also I dont know JWKS, maybe try and find how that scheme works.

**Comment by amsaighi** [comment]
@davidzwa

Cookies : 
![image](https://user-images.githubusercontent.com/3142753/106128773-f8452300-615f-11eb-9b1e-62207648739d.png)

SessionStorage : 
![image](https://user-images.githubusercontent.com/3142753/106128837-05faa880-6160-11eb-8a63-693754544ccd.png)

JWKS : 
![image](https://user-images.githubusercontent.com/3142753/106129114-43f7cc80-6160-11eb-9ff0-12ac791fc208.png)

I Have this behaviour when I work with separeted identity Server 

![image](https://user-images.githubusercontent.com/3142753/106129329-71dd1100-6160-11eb-9bb2-54c12d8146a1.png)

**Comment by davidzwa** [comment]
You stated "I lost the all the information.". What was in the localstorage before? Was it non-empty?

**Comment by amsaighi** [comment]
@davidzwa 
I shared a picture with empty LocalStorage in the first description, and I still get the same result

**Comment by davidzwa** [comment]
I'm sorry @amSaighi I have no clue how to even get to the problem you have. Do you have a public repository to share?
Otherwise, I can only advise to start with the ABP CLI and regenerate the project, if there really is a problem here.

**Comment by amsaighi** [comment]
Finally we got the problem, and we found the solution 
The certificate SSL does not correspond to the domain name.

Thank you everyone
