### ISSUE TITLE
Using snowflake algorithm to generate long as id as an option to GUID

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#7486]
GUID is not very human readable, can we using twitter snowflake to generate id for aggregate root/ entites in abp as a replacement  for Guid. As I have gone through the docs, GUID is requried for aggregate root. But sometimes in reality we have to display things like orderid to customer, guid is not so "good looking"

**Comment by realLiangshiwei** [comment]
You can do it yourself.
See https://github.com/abpframework/abp/issues/469#issuecomment-425720097
