### ISSUE TITLE
About feature and setting

### ISSUE THREAD

**Issue by LFeYls** [abpframework/abp#7488]
I was confused the dependence of  featureModule and settingModule , why the two module is depended by  AbpDddApplicationModule but not AbpDddApplicationContractsModule.
In microservice entrance, like backend host module,we will get the auth,features,settings,localization from  api/abp/application-configuration, but this module only need to  depend on  httpApiModule and httpClientModule of custom service, but not care the service logic,
if the two module  is depended by AbpDddApplicationModule, it means we should define featue and setting in applicationModule , then the entrance module need to depend on AbpDddApplicationModule , if  do it like this , the entrance module will get the service logic. 
of course, we can introduce FeatureModule and SettingModule into ApplicationContractsModule and then define feature or setting in it. but i think it is not the best way.
@maliming if can not understand what i say , please allow i say it in chinese

**Comment by maliming** [comment]
I don't understand what you mean, even in Chinese.

Maybe you can say a specific use case.
