### ISSUE TITLE
[abp] User reach swagger if go to register view before login to the system

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#7493]
**ABP Framework version** 4.1.2
**User Interface** Angular
**database provider** EF Core

Steps needed to **reproduce** the problem.

1- Run the solution about reaching the home page
2- Press the login button
3- Press Register
4- Press Login
5- Provide credential to login and login

**Result**: We reach the Swagger API view

**Expected:** We should reach the home page

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/6734

**Comment by cbaille** [comment]
After updating to the version 4.2.1, I still have this issue. Any action need to be done beside of the update?

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/pull/6734/files#diff-1d41d82816a2db4e0e083fb2e9dcbe56ca5ab8892195a4da8664a8c07d059967R5

**Comment by cbaille** [comment]
Thanks, I just made this changes, but my code structure is a bit different, see below the changes I did.
But then I still get the same issue

![image](https://user-images.githubusercontent.com/27866600/109271747-86392a00-7842-11eb-8fc4-0ad2344d0694.png)

![image](https://user-images.githubusercontent.com/27866600/109272416-6ce4ad80-7843-11eb-8b3d-f8c112682186.png)
