### ISSUE TITLE
default login page‘s switch tanent ui elements  dispeared after configure AbpTenantResolveOptions

### ISSUE THREAD

**Issue by niufwshd** [abpframework/abp#7497]
- abp 4.1.2  netframework 5.0
- issue
      the default login page should let me to choose tanent before login,but when I  add `            Configure<AbpTenantResolveOptions>(options =>
            {
                options.AddDomainTenantResolver("{0}.farvision.com");
            });`
in ConfigureServices function and browser the login page it dispeared!
- reproduce steps
    1.  create new sln frome abp.io and enter solution name as "farvision.mes" and keep others options as default. Click the "Create Now" button and download source code.
    2.  open the sln in vs2019,change the connectionstring in my local db and run the dbmigrator to update the db succefully.
    3.  Set the FarVision.Mes.Web project as startup project, Open MesWebModule.cs file, Append` Configure<AbpTenantResolveOptions>(options =>
            {
                options.AddDomainTenantResolver("{0}.farvision.com");
            });`   to the ConfigureServices function and run the web project successfuly.
   4. Browser the https://localhost:44383/Account/Login and the page  as below:
      
![image](https://user-images.githubusercontent.com/12984401/106126845-dd42d500-6198-11eb-98ae-fe36fcecfc65.png)
 but when I comment above code and browser the login page again. I can see the tanent swich button
![image](https://user-images.githubusercontent.com/12984401/106127351-707c0a80-6199-11eb-97d0-7e37d2e02812.png)

I want to realize   multitanent  subdomain function and it block my head. I  know it related to this https://github.com/abpframework/abp/blob/41f8d03605632c5e36a017405536ec974c412bc9/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Layouts/Account.cshtml
but still have no idea. Can someone help me ,thanks a lot!

**Comment by davidzwa** [comment]
Don't pin me down on this, but I think a sub/domain resolver **should** logically lock the tenant and it makes sense to me that the button dissappears! (I havent looked at the MVC page internally, nor do I claim to fully know it)

You gotta decide:
- Do I want to be able to choose tenants before I enter the login form 
- Or during the form? 

First option means you basically redirect to a new subdomain and change the tenant that way.
Second option means you need to resolve the tenant by customizing the login form.
Third options? Anybody?

Question in general: how does localhost resolve for subdomains? Null? Might be nice to figure that out.

**Comment by niufwshd** [comment]
@davidzwa ，thank you for you reply.Yes, I almost agree with you. It locked the tanent after Add configure code and the UI disapear. and the localhost of subdomain is NULL too. I append the "127.0.0.1 farvision.com" to os hosts to simulate real dns, and change launch url to "farvision.com:44383" in the launchsetting.json and  browser https://farvision.com:44383/Account/Login.  My inital Idea is   I first select a tanent on the login page and when login I redirect the sub/domain url like 'xxx.farvision.com:44383' . and the sub/domain resolver can get the tanent info. but when I  https://farvision.com:44383/Account/Login. I can't select tanent now. what confuse me is that it locked the system before I select a tanent. if so,I must have to  custom the login page. just follow your second option.

**Comment by niufwshd** [comment]
@davidzwa I change the config code to `  Configure<AbpTenantResolveOptions>(options =>
            {
                options.TenantResolvers.Add(new DomainTenantResolveContributor("{0}.farvision.com"));
            });
and It solve my problem.`

**Comment by davidzwa** [comment]
Hmm does not sound to me like the best solution: I would've changed the login-form to select and reload the page, personal preference. But good to hear anyway!
