### ISSUE TITLE
Discussion - UI Technologies

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#750]
Just wondering if anyone has had the time to use this ABP in conjunction with other UI technologies like WPF or Blazor?

#If I was to make a start on a Blazor sample would the framework be ready?
#Would I use the ASP.CORE API Module (without UI)?

Thanks

**Comment by hikalkan** [comment]
Hi,

Didn't try with blazor yet. However, this ABP should work in any type of application. BTW, It will definitely work with WPF. You can take the console application sample as a starting point.

**Comment by 274188A** [comment]
I will try out Blazor first (head first!). 

I was thinking i would download the template for MVC Application with EF Core, then remove the web project. 

Then add in a new asp.net server-side components (blazor-server-side) project. 

The the Blazor server proj would ref to the abp.Application

Should work in theory

**Comment by hikalkan** [comment]
I would be great if you can share your experiences. Thanks.

**Comment by hikalkan** [comment]
Closing this since there is https://github.com/abpframework/abp/issues/394
