### ISSUE TITLE
Data Migration Issue When created a solution with blazor as UI using CLI

### ISSUE THREAD

**Issue by crazygeek69** [abpframework/abp#7506]
ABP Framework Version : 4.2
User Interface: Blazor
Database Provider: Entity Framework
Steps To Reproduce
1) Create the solution using the following command
          abp new Acme.BookStore -u blazor -csf
2) Then try run the Migrations using the DBMigrator getting the following error
3) When download the ABP samples [BookStore-Blazor-EfCore] and it works fine.
4) Also noticed that BookStoreDbMigrationService.cs file is a lot different in both the projects (Created using CLI and Download from Github)

Issue in cmd window

> [12:52:11 INF] Creating initial migration...
> [12:52:12 INF] ABP CLI (https://abp.io)
> [12:52:12 INF] Version 4.2.0 (Stable)
> [12:52:13 ERR] Migrations failed: Could not execute because the specified command or file was not found.
> Possible reasons for this include:
>   * You misspelled a built-in dotnet command.
>   * You intended to execute a .NET program, but dotnet-ef does not exist.
>   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
> System.Exception: Migrations failed: Could not execute because the specified command or file was not found.
> Possible reasons for this include:
>   * You misspelled a built-in dotnet command.
>   * You intended to execute a .NET program, but dotnet-ef does not exist.
>   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
>    at Volo.Abp.Cli.Commands.CreateMigrationAndRunMigrator.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\CreateMigrationAndRunMigrator.cs:line 37
>    at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59
> 
> C:\Users\sivas\Acme.BookStore\src\Acme.BookStore.DbMigrator\bin\Debug\net5.0\Acme.BookStore.DbMigrator.exe (process 34312) exited with code 0.
> To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
> Press any key to close this window . . .

**Comment by maliming** [comment]
> Then try run the Migrations using the DBMigrator getting the following error

Can you try to run `DBMigrator ` via `dotnet run`.

**Comment by sturlath** [comment]
I´m also getting this... 

![image](https://user-images.githubusercontent.com/2386572/106290482-6c57f780-6242-11eb-8fed-2a4168172628.png)

and if I try to downgrade the CLI I get this and it doesn´t create any migrations. 

![image](https://user-images.githubusercontent.com/2386572/106294082-a3300c80-6246-11eb-8a58-ac1115a75e33.png)

So stuck.. bad stuff..

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/106345175-45083580-62e9-11eb-8929-631a978dbbdd.png)


`dotnet tool install --global dotnet-ef --version 5.0.2`

**Comment by crazygeek69** [comment]
It worked, After I ran the **dotnet tool install --global dotnet-ef --version 5.0.2**

**Comment by rafaelmohedano** [comment]
> ![image](https://user-images.githubusercontent.com/6908465/106345175-45083580-62e9-11eb-8929-631a978dbbdd.png)
> 
> `dotnet tool install --global dotnet-ef --version 5.0.2`

Great, it worked. It would be nice to put a note  in the setup documentation at: https://docs.abp.io/en/abp/latest/Getting-Started-Setup-Environment?UI=NG&DB=EF&Tiered=No#setup-your-development-environment
