### ISSUE TITLE
Published App gets Stuck On Loading...

### ISSUE THREAD

**Issue by Digisaman** [abpframework/abp#7507]
### Documentation
I'm running APB ( Latest Version)
Please check the official documentation before asking questions: https://docs.abp.io
* Your **ABP Framework version**.

UI : Blazor
DB Provider : EF CoreWhen running the Solution in IIS Express Everything works fine
But when running the published version (either in local IIS or published to AWS Container )
It gets stuck on loading page and never redirects to the home page

![ABPLoading](https://user-images.githubusercontent.com/12669884/106186321-5c480580-61b9-11eb-9d09-5fd8fa494d43.PNG)

**Comment by maliming** [comment]
Please check the application logs and browser console.

**Comment by Xan1203** [comment]
Helo,
i have exactly the same problem. New project generated for Blazor. No application log is generated. Console looks like this:
![image](https://user-images.githubusercontent.com/16512995/106358588-785cbb80-630d-11eb-9bd1-803d48702b91.png)

Tried MVC project variant also, it works normally.

**Comment by Digisaman** [comment]
I think I Figured it out, The HttpApi.Host needs to be hosted separately so that it ca be accessed to download modules....
I did that but then encountered a CORS error which I haven't been able to resolve...

**Comment by Xan1203** [comment]
You are right, HttpApi.Host has to be started before starting GUI part - it was not clear from "getting started" document for me. Now for me works as expected - thank you.
