### ISSUE TITLE
4.2.0  Migrations failed

### ISSUE THREAD

**Issue by roupijiaojiaobao** [abpframework/abp#7536]
![微信图片_20210129100232](https://user-images.githubusercontent.com/64553587/106291025-1d499c80-6219-11eb-9a1a-7798985e8314.png)
Hi everyone, after creating a new project on the official website by Direct Download, I encountered this problem during Migrations

**Comment by maliming** [comment]
Try to install ef tool: `dotnet tool install --global dotnet-ef --version 5.0.2`

**Comment by olicooper** [comment]
Would it be possible to have `CmdHelper.RunCmdAndGetOutput` install the tool if the dotnet SDK exists? 
Or test if the `dotnet-ef` tool exists and throw an exception that helps the developer understand the problem more clearly?
