### ISSUE TITLE
Add Arabic Language Resource Translation

### ISSUE THREAD

**Issue by makhalaf** [abpframework/abp#754]
Add Arabic language resource translation to all framework modules

**Comment by hikalkan** [comment]
a PR would be good since we don't know Arabic :)

**Comment by hikalkan** [comment]
See "Resource Localization" section here: https://abp.io/documents/abp/latest/Contribution/Index#resource-localization

**Comment by hitaspdotnet** [comment]
We have problems with RTL languages in UI. 
RTL Markdown contents is another (big one) problem. I have tried for FA (Persian) but ... 😞

**Comment by hikalkan** [comment]
Bootstrap doesn't support RTL I suppose. We also haven't worked on RTL yet. The framework is still preview :)

**Comment by kgamalseif** [comment]
Hi @hikalkan, Are there any plans to support RTL on UI(Arabic for example)?

**Comment by hikalkan** [comment]
We haven't a plan yet. However, we use standard bootstrap and you can do it like you are doing in any boorstrap based UI. It would be appreciated if you contribute.

I am adding this to backlog and consider to implement in the future.

**Comment by kgamalseif** [comment]
Ok, I will contribute, just assign it to me. Thanks.

**Comment by kgamalseif** [comment]
Sent pull request.
RTL language support & added arabic localization resources #3754
