### ISSUE TITLE
Depoloyment Problem

### ISSUE THREAD

**Issue by Digisaman** [abpframework/abp#7540]
APB Framework Version 4.2
UI : Blazor
DB Provider EFCore

I've Published the framework on a Windows Server 2019 with IIS
Created 2 IIS websites : 
1 . Hosting the Blazor Project on Port 443 for SLL
2. Hosting  the HttpApi.Host Project on another Port
(Is this the correct way ? do I need 2 websites? should they both be on the same server?)

Both Websites are  running correctly.
But when I browse the first website, and click the Login Button, I get this Error
404 not found 
and here's the BrowserConsole Log :
 GET https://172.31.30.120/Error?httpStatusCode=404 404
DevTools failed to load SourceMap: Could not load content for https://172.31.30.120/__bundles/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://172.31.30.120/__bundles/toastr.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by maliming** [comment]
@stsrki Do you have any advice?

**Comment by stsrki** [comment]
@maliming As far as I know, they should be separated. That's why HttpApi.Host exists. To be able to connect to any client or app.

@Digisaman It's hard to tell what can be wrong from your description without access to the system. Check that you are connecting to **HTTPS** and no **HTTP**. Also, check your firewall settings.

**Comment by Digisaman** [comment]
Hi @stsrki 
I've checked my connection it's HTTPS
and I've published the HTTPApi.Host and Blazor projects to two separate AWS servers (Both Accessing the same Database Server)
Both are running on HTTPS with valid domain names and certificates. I still don't know what the problem is, Everything is OK on my local machine But when I Publish the APP on AWS I have this issue
The HomePage is browsed correctly but when try to login and it redirects to HTTPApi.Host, I Get this Error:

[500] Error!
invalid_request

![ABPHomePage](https://user-images.githubusercontent.com/12669884/106432240-af54dd80-6483-11eb-8f8c-a20c94a786cf.PNG)

![ABPLogin1](https://user-images.githubusercontent.com/12669884/106432071-6c930580-6483-11eb-9604-38700487964e.PNG)
![ABPLogin2](https://user-images.githubusercontent.com/12669884/106432520-17a3bf00-6484-11eb-9d43-df32417d68e0.PNG)


Any Ideas on how to resolve the issue?

**Comment by ilkayilknur** [comment]
@Digisaman It is hard to tell what's wrong with the system. You need to check application logs to find the problem. The problem could be a connectivity issue between the API and DB.

When you deploy two different websites, you need to configure `CorsOrigins` and `RedirectAllowedUrls` configs. You can get reference from https://github.com/abpframework/abp/discussions/7416#discussioncomment-318368

**Comment by Digisaman** [comment]
Tanx @ilkayilknur  following the link you provided. Solved the Login Issue. (Section 10) 
I just changed the Root URL in DbMigrator project config To the Blazor App's URL and Run the Migrator
