### ISSUE TITLE
Remove Bootstrap dependencies

### ISSUE THREAD

**Issue by XuJin186** [abpframework/abp#7546]
APB Framework Version 4.2
UI : Blazor
DB Provider EFCore

Whether can cancel Volo.Abp.AspNetCore.Com ponents. WebAssembly. Theming the bootstrap dependencies, such as to prevent it to a template, because we want to replace the theme in the process of development But found that the bootstrap some style which affected our themes, and become a large CSS file

**Comment by XuJin186** [comment]
Now is the use of this method to remove, whether there is a better way

```
public void AddStyles(BundleContext context)
        {
            context.BundleDefinitions.RemoveAt(1);
            context.BundleDefinitions.RemoveAt(0);
            context.Add("main.css", true);
        }
```

**Comment by realLiangshiwei** [comment]
Yes, Using `IBundleContributor` is the recommended way

**Comment by XuJin186** [comment]
thank you@realLiangshiwei
