### ISSUE TITLE
Documentation about ABP Introduction Module

### ISSUE THREAD

**Issue by sgalcheung** [abpframework/abp#7547]
### Module
I recently (12/23/2020) learned ABP, starting from version 4.0, when I saw the documentation related to the module, I was very confused, I don’t know what the module specifically represents.
until today, I saw an ABP explaining the module In the video, I found that he explained very clearly, how to change from an aspnetcore template project to the use of abp. I see that the abp package applied in the video is version 3.0, so I turned the document to version 3.0. Until I found the information under Getting Started -> From Empty Project, I understood at once. 
This understanding is the knowledge that must be obtained from an aspnetcore to abp, and I also understand what the module in ABP is about.
so I suggest this The document can be kept in the latest document, etc., I found that there is this part in the latest document, but can the location of his document be related to the module Or put it first under getting started?

**Comment by realLiangshiwei** [comment]
I don't get your point

**Comment by sgalcheung** [comment]
If you are an abp newcomer, with the basic knowledge of aspnetcore, Empty Web Project can just connect aspnetcore and abp, but the name Empty Web Project, I don’t know it is a good name, just use Start AspNetCore and put it in Getting Started Next item.
