### ISSUE TITLE
Warning when trying to create Tenants using Tenant manager in my DataseedContributor

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#7548]
* Your **ABP Framework version** - v4.2.0
* Your **User Interface** type (Angular/MVC/React... etc.) -MVC
* Your database provider(EF Core/MongoDB) - EF Core
* Exception message and **stack trace** if available (check the logs).

`[23:34:43 WRN] The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results`

* Steps needed to **reproduce** the problem.

I am using the following code in my DataSeedContributor to create default Tenant with Specific edition for testing purposes in my dev environment and get the above warning can you please let me know if this is a bug or it is fine ??

```
private async Task CreateTenantWithEditionAsync(string tenantName, string adminEmail, string adminPassword, Guid editionId)
{
    var tenant = await _tenantManager.CreateAsync(tenantName, editionId);
    
    Tenants.Add(await _tenantRepository.InsertAsync(tenant, true));
    
     using (_currentTenant.Change(tenant.Id, tenant.Name))
    {
       await _dataSeeder.SeedAsync(
            new DataSeedContext(tenant.Id)
                .WithProperty("AdminEmail", adminEmail)
                .WithProperty("AdminPassword", adminPassword)
                );
    }
    }
}
```

**Comment by maliming** [comment]
You can change the output level of the log to find the query that has warnings.

**Comment by vnetonline** [comment]
Can you please tell me how I do this?

**Comment by maliming** [comment]
Change 
`.MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Warning)`
 to
 `.MinimumLevel.Override("Microsoft.EntityFrameworkCore", LogEventLevel.Information)`

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/Program.cs#L20

**Comment by vnetonline** [comment]
also can you let me know where will I find the log file ??

**Comment by maliming** [comment]
`Logs/logs.txt` or application console.
