### ISSUE TITLE
Hope to add business name to eventbus .

### ISSUE THREAD

**Issue by dazsco** [abpframework/abp#7549]
Using ETO full name or EventName is a great idea, but I ran into such a problem.
I am developing a workflow system, which will run in different microservices. I used DistributedEventBus for message delivery. Now I have encountered a thorny problem. A workflow may cooperate in multiple businesses. But processes such as "rejection" and "approval" should be an Eto. The current solution is that I pass in a business name through ETO and judge when the microservice is subscribed or sent, so that I can get the desired result . But I don't want all subscriptions to take effect, because different businesses should not deal with businesses that have nothing to do with them. The workflow configuration uses JSON. If I create an ETO for each such business, I think it is unnecessary. This will destroy the flexibility of my workflow and always need to republish the service.
I hope that the business name can be customized in EventBus, and this name can be set in the EventHandler of the subscription time, so that this Eto can be shared.
I don't know if I describe it clearly, but I am very grateful to all the contributors of Abp.

**Comment by slarkerino** [comment]
Maybe rabbitmq topics would help. But currently abp built in distributed event bus has not support for that yet. I think we should integrate masstransit into abp
