### ISSUE TITLE
Base property of appservice and domainservice are not mockable for true unit test

### ISSUE THREAD

**Issue by willignicolas** [abpframework/abp#7550]
Hello,

We write unit tests for our appservices and domainervices. 
In this context, we must mock basic properties such as IguidGenerator or ICurrentTenant or ILogger, which are used when inserting an entity. But these properties all have a private setter. And so we cannot mock them. It is a shame to have to put a dependency in the constructor, we will lose the advantage of the direct accessibility of these properties.

Thank you in advance for your help.

Best regards,
Nicolas

**Comment by maliming** [comment]
hi

There are `protected`  Maybe you can create a subclass.  

How to mock services in unit tests has nothing to do with abp.

**Comment by willignicolas** [comment]
Thanks for your reply, I will make subclass.

**Comment by tinonetic** [comment]
Hi, could someone explain to me how this would be done?

**Comment by tinonetic** [comment]
@willignicolas , @maliming ... would appreciate a bit of insight on how and what would be subclassed?

I do know, and apologise that mocking the services isn't ABP-related
