### ISSUE TITLE
Question: Dynamic C# Client Authorization

### ISSUE THREAD

**Issue by baskan** [abpframework/abp#7551]
I am trying to use Dynamic C# Client on a WinForms application, I did managed to port my WinForms application to support Microsoft Dependency Injection but I couldn't figure out how to make use of `IdentityModelRemoteServiceHttpClientAuthenticator`that I have found in the source code (there is no documentation on how to do so)

currenly what I do is;

```csharp
[DependsOn(
    typeof(HudutGecisHttpApiClientModule),
    typeof(AbpHttpClientIdentityModelModule)
    )]
    public class WinFormsApiClientModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.Configure<AbpRemoteServiceOptions>(options =>
            {
                options.RemoteServices.Default = new RemoteServiceConfiguration("https://localhost:44382");
                
            });
            PreConfigure<AbpHttpClientBuilderOptions>(options =>
            {
                options.ProxyClientActions.Add((a, s, h) =>
                {
                    var myuglysingleton = s.GetService<MyCustomHttpAuthorizationHandlerSingleton>();
                    if(myuglysingleton.IsLoggedIn())
                        h.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", myuglysingleton.GetCurrentBearer());
                });
            });
        }
    }

    public class MyCustomHttpAuthorizationHandlerSingleton : ISingletonDependency
    {
        // holds the data if user logged in.. and returns the bearer.
    }

```

My question is;

How can I call `connect/token` URI and make the dyanmic proxy handler to save the token and intercept and use the token header on future calls? 

As I can see in the source code there is a handler for this, but how can I make use of it? :

https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/framework/src/Volo.Abp.Http.Client.IdentityModel/Volo/Abp/Http/Client/IdentityModel/IdentityModelRemoteServiceHttpClientAuthenticator.cs

If this is possible I can provide a PR to the docs with an how to. (I can also share the win forms example if someone is interested)

**Comment by maliming** [comment]
hi

Microsoft Dependency Injection cannot implement interceptor features. You need to integrate autofac.

https://docs.abp.io/en/abp/latest/Autofac-Integration

**Comment by baskan** [comment]
> hi
> 
> Microsoft Dependency Injection cannot implement interceptor features. You need to integrate autofac.
> 
> https://docs.abp.io/en/abp/latest/Autofac-Integration

thank you for your answer. I guess under the hood, Volo.Abp.Http.Client uses Castle's DynamicProxies so I dont think Autofac is strictly needed. 

As you can see here, the Http.Client's itself is just a DyanmicProxy  (Interface without target to be exact)

https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/framework/src/Volo.Abp.Http.Client/Microsoft/Extensions/DependencyInjection/ServiceCollectionDynamicHttpClientProxyExtensions.cs

I'm just curious what's the recommended way to do this.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/framework/src/Volo.Abp.Http.Client/Microsoft/Extensions/DependencyInjection/ServiceCollectionDynamicHttpClientProxyExtensions.cs#L110

**Comment by baskan** [comment]
thank you @maliming  I finally figured it out. closing the issue.
