### ISSUE TITLE
Creating a custom AuthenticationStateProvider for Blazor web assembly

### ISSUE THREAD

**Issue by liorbalmas** [abpframework/abp#7554]
Hello, 
I'm trying to use  and authentication method other then provided by the template on client side - Blazor WebAssembly.
For that, I have a implemented a custom AuthenticationStateProvider.
But that seems not enough as the framework expects implementation of more services such as IAccessTokenProvider and SignOutSessionStateManager which I could not figure how and where to implement.
It seems there's no one place where all the authentication/authorization services are created..
Thanks for any help on that.

_Originally posted by @liorbalmas in https://github.com/abpframework/abp/discussions/7545_

**Comment by maliming** [comment]
hi

Can you explain this in detail?

**Comment by liorbalmas** [comment]
The users are being authenticated in Firebase. They provide user and password to FIrebase and recieve a JWT on suceessful authentication.
This JWT is being validated in my abp api, and if validated, the api sets the context's user by fetching the IdentityUser by matching the validated username came from Firebase with identityuser.  
I think server side is covered pretty well. However, I'd like to use the blazor wasm client, but here, I couldn't understand how to setup the identity. As a result, all UI components that depend on current user and it's permissions are not available. Additionally, application layer services are returning 401 when being accessed from client proxy.

Hope that explains it.
Thanks

**Comment by maliming** [comment]
@stsrki Do you have any ideas?
