### ISSUE TITLE
[Volo.Abp.Http.Client.IdentityModel] when used in blazor wasm app 

### ISSUE THREAD

**Issue by gainorloss** [abpframework/abp#7559]
I *requested* idenity server (AuthServer.Host), got exception as below.

![image](https://user-images.githubusercontent.com/26458238/106456712-de417280-64c8-11eb-9dd0-3b6a6b6e594c.png)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Please **write in English**.

**Comment by gainorloss** [comment]
## Program.cs
`  public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            var application = builder.AddApplication<BlazorWebAssemblyModule>(opt =>
            {
                opt.UseAutofac();
            });

            var host = builder.Build();
            await application.InitializeAsync(host.Services);
            await host.RunAsync();
        }
`

## Packages

`<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.2" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
    <PackageReference Include="Volo.Abp.Autofac.WebAssembly" Version="4.2.0" />
    <PackageReference Include="volo.abp.http.client.identitymodel" Version="4.2.0" />
  </ItemGroup>
`

## Module.cs

`[DependsOn(
        typeof(AbpAutofacWebAssemblyModule),
        typeof(ProductHttpApiClientModule),
        typeof(BlazorWebAssemblyPagesModule),
        typeof(AbpHttpClientIdentityModelModule))]
    public class BlazorWebAssemblyModule : AbpModule
    {
        /// <inheritdoc/>
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            var env = context.Services.GetSingletonInstance<IWebAssemblyHostEnvironment>();
            var builder = context.Services.GetHostBuilder();

            builder.RootComponents.Add<App>("#app");
            builder.PhoenixInitialize(builder.Configuration);

            builder.Services.AddScoped<RefreshTokenHandler>();
            builder.Services.AddHttpClient(PWAHostConsts.Services.ServerAPI, client =>
            {
                client.BaseAddress = new Uri(builder.Configuration["IdentityClients:Default:Authority"]);
            }).AddHttpMessageHandler<RefreshTokenHandler>();

            builder.Services.AddScoped<AuthenticationStateProvider, AccountAuthenticationStateProvider>();
        }
    }
`

## appsettings.json

`{
  "RemoteServices": {
    "Default": {
      "BaseUrl": "[gateway url]"
    },
    "Product": {
      "BaseUrl": "[gateway url]"
    }
  },
  "IdentityClients": {
    "Default": {
      "Authority": "[gateway url]",
      "ClientId": "erp_web",
      "ClientSecret": "1q2w3e*",
      "GrantType": "client_credentials"
    }
  }
}
`

**Comment by gainorloss** [comment]
> * Your **ABP Framework version**.
> * Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
> * Your database provider(EF Core/MongoDB)
> * Exception message and **stack trace** if available (check the logs).
> * Steps needed to **reproduce** the problem.

*  Package version :4.2.0
*  UI:Blzor wasm
*  DatabaseProvider :EF Core
* Wasm console:
`blazor.webassembly.js:1 System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform.
blazor.webassembly.js:1    at System.Security.Cryptography.MD5.Create()
blazor.webassembly.js:1    at System.AbpStringExtensions.ToMd5(String str)
blazor.webassembly.js:1    at Volo.Abp.IdentityModel.IdentityModelTokenCacheItem.CalculateCacheKey(IdentityClientConfiguration configuration)
blazor.webassembly.js:1    at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.CalculateTokenCacheKey(IdentityClientConfiguration configuration)
blazor.webassembly.js:1    at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.GetAccessTokenAsync(IdentityClientConfiguration configuration)
blazor.webassembly.js:1    at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.GetAccessTokenOrNullAsync(String identityClientName)
blazor.webassembly.js:1    at Volo.Abp.IdentityModel.IdentityModelAuthenticationService.TryAuthenticateAsync(HttpClient client, String identityClientName)
blazor.webassembly.js:1    at Volo.Abp.Http.Client.IdentityModel.IdentityModelRemoteServiceHttpClientAuthenticator.Authenticate(RemoteServiceHttpClientAuthenticateContext
blazor.webassembly.js:1    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<MakeRequestAsync>d__42[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
blazor.webassembly.js:1    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<MakeRequestAndGetResultAsync>d__41`1[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=4.2.0.0, Culture=neutral, 			PublicKeyToken=null],[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.ApplicationConfigurationDto, Volo.Abp.AspNetCore.Mvc.Contracts, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
blazor.webassembly.js:1    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<GetResultAsync>d__40[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
blazor.webassembly.js:1    at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.<InterceptAsync>d__39[[Volo.Abp.AspNetCore.Mvc.ApplicationConfigurations.IAbpApplicationConfigurationAppService, Volo.Abp.AspNetCore.Mvc.Contracts, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()`

**Comment by maliming** [comment]
Related: https://github.com/dotnet/runtime/issues/40074

**Comment by maliming** [comment]
You can try to override that method that uses MD5.

https://github.com/abpframework/abp/blob/3fcdeeeb05810b7a2e162f212ef435b81d412aa5/framework/src/Volo.Abp.IdentityModel/Volo/Abp/IdentityModel/IdentityModelAuthenticationService.cs#L258

**Comment by gainorloss** [comment]
I will have a try.
