### ISSUE TITLE
how can i create template using oracle

### ISSUE THREAD

**Issue by andyaicao** [abpframework/abp#756]
how can i create template using oracle?
in WebModule
Configure<AbpDbContextOptions>(options =>
            {
                options.UseSqlServer();
            });
there is no UseOracle

**Comment by hikalkan** [comment]
It requires an additional package and it's related to EF Core rather than ABP.
See https://docs.microsoft.com/en-us/ef/core/providers/

**Comment by Karthigeyan73** [comment]
Oracle supported entity framework core. Please look in to below link.
https://www.nuget.org/packages/Oracle.EntityFrameworkCore/

Will oracle support included in future?

**Comment by maliming** [comment]
@Karthigeyan73 

I think it doesn't support ef core 3.1 yet.

![image](https://user-images.githubusercontent.com/6908465/71701910-8937b680-2e07-11ea-995c-f826eb4e6fd8.png)

**Comment by jack-gaojz** [comment]
Bad news, I would plan to use the Oracle. :(

**Comment by ismcagdas** [comment]
https://www.devart.com/dotconnect/oracle/ supports .NET Core 3.1 but it is a paid product.
