### ISSUE TITLE
Register my DbContext as Transient

### ISSUE THREAD

**Issue by Brahimhz** [abpframework/abp#7560]
In project , I had method that had to make many call to database depending on item's value of a list.
before I used a normal "foreach" but it take a long time. so I want to separate this call using "List<T>.ForEach".

The probleme that I had is : 
"System.InvalidOperationException: 'A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.'"

After many search , I found that I need to register my DbContext as Transient.
I found this in StackOverFlow 
https://stackoverflow.com/questions/48767910/entity-framework-core-a-second-operation-started-on-this-context-before-a-previ

I put this code in my **ConfigureServices** :
`context.Services.AddTransient<MyDbContext>();` 

But it didn't work.
Any Solution ??

**Comment by maliming** [comment]
This will [complicate the problem](https://xyproblem.info/). 

You can share your specific use case and some code. This way we can discuss.

**Comment by Brahimhz** [comment]
> This will [complicate the problem](https://xyproblem.info/).
> 
> You can share your specific use case and some code. This way we can discuss.


```
entities.ForEach(async item =>
{
    {

        if (item.Discriminator.Equals("ProductsSection"))
        {
            switch (item.Type)
            {
                case HomeSectionType.TopNewest:
                    item.Products = await _productsRepository.NewestProduct(item.NbrItems, clientUserId, item.StoreType);
                    break;

                case HomeSectionType.TopViewed:
                    item.Products = await _productsRepository.TopViewedProduct(item.NbrItems, clientUserId, item.StoreType);
                    break;

                case HomeSectionType.Dynamic:
                    item.Products = await _productsRepository.GetByQuery(item.NbrItems, item.OrderBy, item.Filters, clientUserId, item.StoreType);
                    break;

                case HomeSectionType.Static:
                    item.Products = await _productSectionProductsRepository.GetProducts(item.Id);
                    break;
            }

            item.Products = item.Products.Take(resultCount).ToList();
        }

        if (item.Discriminator.Equals("StoresSection"))
        {
            switch (item.Type)
            {
                case HomeSectionType.TopNewest:
                    item.Stores = await _storesRepository.NewestStore(item.NbrItems, clientUserId, item.StoreType);
                    break;

                case HomeSectionType.TopViewed:
                    item.Stores = await _storesRepository.TopViewedStore(item.NbrItems, clientUserId, item.StoreType);
                    break;

                case HomeSectionType.Dynamic:
                    item.Stores = await _storesRepository.GetByQuery(item.NbrItems, item.OrderBy, item.Filters, clientUserId, item.StoreType);
                    break;

                case HomeSectionType.Static:
                    item.Stores = await _storeSectionStoresRepository.GetStores(item.Id);
                    break;
            }

            item.Stores = item.Stores.Take(resultCount).ToList();
        } 
}
}
```
                        
                        
So as you can see in this loop of list of entities ,  different database call can be depend on the "Discriminator" value .

**Comment by maliming** [comment]
You can try to create a non-transactional unit of work in **foreach**, so the **DbContext** will be different.

https://docs.abp.io/en/abp/latest/Unit-Of-Work#begin-a-new-unit-of-work

**Comment by Brahimhz** [comment]
> You can try to create a non-transactional unit of work in **foreach**, so the **DbContext** will be different.
> 
> https://docs.abp.io/en/abp/latest/Unit-Of-Work#begin-a-new-unit-of-work

So I Tried your solution , when I run it many exceptions appear like this :

`System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
` 
then the application go on break mode and stop .

**Comment by maliming** [comment]
Can you share your code?

**Comment by Brahimhz** [comment]
> Can you share your code?

```
public async Task<List<Product>> TopViewedProduct(int nbrItems, int? clientUserId, StoreTypes storeType)
{
    var products = new List<Product>();
    using (var uow = _unitOfWorkManager.Begin(requiresNew: true, isTransactional: false))
    {


        var entities = await DbSet
                    .Include(p => p.Productitems)
                    .Include(p => p.Brand)
                    .Include(p => p.Store)
                        .ThenInclude(s => s.Owner)
                    .ToListAsync();

        if (!entities.IsNullOrEmpty())
        {
            products.AddRange(entities);

            await TopViewedLast30Days(products);

            products = products.OrderByDescending(p => p.CalculatedViewCount).ToList();

            products = EliminateProductWithZeroQty(products, clientUserId);

            if (nbrItems != 0)
                products = products.Take(nbrItems).ToList();
            //foreach (var product in products)
            products.ForEach(async product =>
            {
                await ApplyPromo(product);
                if (clientUserId.HasValue)
                    product.Liked = IfLiked(product.Id, clientUserId);
            });
            products = FilterByStoreType(products, storeType);
        }


        await uow.CompleteAsync();
    }
    return products;
}
```

**Comment by maliming** [comment]
Which line causes the error?

**Comment by Brahimhz** [comment]
> Which line causes the error?

The call of each method contain this solution .

` entities.ForEach(async item =>
                {


                    if (item.Discriminator.Equals("ProductsSection"))
                    {
                        switch (item.Type)
                        {
                            case HomeSectionType.TopNewest:
                                item.Products = await _productsRepository.NewestProduct(item.NbrItems, clientUserId, item.StoreType);
                                break;

                            case HomeSectionType.TopViewed:
                                item.Products = await _productsRepository.TopViewedProduct(item.NbrItems, clientUserId, item.StoreType);
                                break;

                            case HomeSectionType.Dynamic:
                                item.Products = await _productsRepository.GetByQuery(item.NbrItems, item.OrderBy, item.Filters, clientUserId, item.StoreType);
                                break; `

**Comment by real-zony** [comment]
Hi Brahimhz,
Do you consider replacing the `ForEach()` method with a `foreach` statement? ForEach() itself does not wait. I think this exception is caused by the unit of work being disposed of in advance.

**Comment by realLiangshiwei** [comment]
`ForEach` does not support an async delegate since it takes an Action<T>. That reduces your method to un-awaitable async void. ForEach was never intended for a Func<Task> or any other async variant.

ABP uses unit of work to create dbcontext instead of dependency injection.   **Long story short: use `foreach` instead of `ForEach`**.

**Comment by Brahimhz** [comment]
Thanks for your remarks , that helped me in reviewing my code and finding that if I use ForEach() I don't need to make the methods async.

Thanks again for your help.
