### ISSUE TITLE
DateTime Bug

### ISSUE THREAD

**Issue by wzfeilongge** [abpframework/abp#7570]
Version 3.0.5

public override void ConfigureServices(ServiceConfigurationContext context)
{

        context.Services.AddControllers(o => o.Filters.Add(typeof(JucherLog))).AddNewtonsoftJson(options =>
        {
            // 忽略循环引用
            options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            //设置时间格式
            options.SerializerSettings.DateFormatString = "yyyy-MM-dd HH:mm:ss";
            //使用驼峰样式的key
            options.SerializerSettings.ContractResolver = new DefaultContractResolver();         
        });

        Configure<AbpClockOptions>(options => options.Kind = DateTimeKind.Utc);
        Configure<AbpJsonOptions>(options => options.DefaultDateTimeFormat = "yyyy-MM-dd HH:mm:ss");
}
The global configuration time format has been configured

var testtimes = DateTime.Now; // 2/2/2021 12:25: PM
var startstr = testtimes.ToString("yyyy-MM-dd HH:mm:ss"); //2021-02-02 12:25:32
var result = DateTime.Parse(endstr); //2/2/2021 12:25: PM

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Please **write in English**.

**Comment by wzfeilongge** [comment]
ABP Version 3.0.5

**Comment by wzfeilongge** [comment]
> * ABP Version 3.0.5  dotnet core 3.1
> * UI  MVC --tiered
> * EF Core
> * No exception
> HTTP get request method receives an object with start time and end time. Swagger test receives the time parameter like this. Sorry, I'm poor in English. It's all translated

**Comment by wzfeilongge** [comment]
![QQ图片20210203081902](https://user-images.githubusercontent.com/48375655/106679944-9a4d8b00-65f8-11eb-935a-b43913de0058.png)

**Comment by wzfeilongge** [comment]
![QQ图片20210203081902](https://user-images.githubusercontent.com/48375655/106680064-d7198200-65f8-11eb-95d6-f88ac6a1abda.png)

**Comment by wzfeilongge** [comment]
image 
![QQ图片20210203081902](https://user-images.githubusercontent.com/48375655/106680090-ea2c5200-65f8-11eb-8a2a-65fa2c589c7d.png)

**Comment by wzfeilongge** [comment]
image
(https://user-images.githubusercontent.com/48375655/106680153-10ea8880-65f9-11eb-9780-1947c5c6259b.png)

**Comment by wzfeilongge** [comment]
app.ApplicationServices.GetService<ISettingDefinitionManager>().Get(LocalizationSettingNames.DefaultLanguage).DefaultValue = "zh-Hans";
