### ISSUE TITLE
Should Audited work on Get methods although IsEnabledForGetRequests is not true?

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#7573]
ABP Framework version : 4.0.0.
MVC

We do not set IsEnabledForGetRequests to true. Because we do not want all the GETs to be audit logged. But in order to selectively audit log some of the GET methods, we added [Audited] above them. As I understand IsEnabledForGetRequests dominates Audited attribute.

Am I right? If so, should it be? 

Maybe [Audited] should dominate all other options.

**Comment by maliming** [comment]
Audit info can't be saved for **Get** request when **IsEnabledForGetRequests** is **false**,  even if you use the **Audited attribute**.

**Comment by espindl** [comment]
Maybe adding that detail in the docs helps people...
