### ISSUE TITLE
Integrate masstransit in abp

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#7579]
Maybe Integrating popular masstransit is a good idea? Currently distributed event bus does not support some more advanced features for MQ. Such as rabbitmq topics or SAGA. Masstransit can integrate well with abp and it is open source!

**Comment by real-zony** [comment]
Hi slarkerino,
Masstransit currently works well with Abp, you just need to import it. As far as I know, there are currently no plans to package Masstransit as a separate module.

**Comment by genoher** [comment]
Maybe this is useful to somebody.
https://github.com/cocosip/sharp-abp
