### ISSUE TITLE
ABP model-manager.js should mask the page before the modal dialog open

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#7581]
ABP Version: 4.2
If the modal open needs a little long time, we should mask the page to avoid the user click the button multiple times. 
We can add the block UI logic once the modal open event trigger. After the modal dialog opened, we can unmask the block UI.

![image](https://user-images.githubusercontent.com/74571567/106679625-0c71a000-65f8-11eb-873d-4fbd00126943.png)
 
I think it is a very useful feature. Thanks.

**Comment by realLiangshiwei** [comment]
This is the default behavior of the modal,  You can use the busy API manually: https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Block-Busy
