### ISSUE TITLE
[framework][Volo.Abp.BlobStoring]:SaveAsync return file oss path.

### ISSUE THREAD

**Issue by gainorloss** [abpframework/abp#7584]
### Documentation

Should we return the file oss path when we use *SaveAsync*(current:*void*)

### GitHub Issues

* Your **ABP Framework version**.(4.2.0)

**Comment by realLiangshiwei** [comment]
`IBlobContainer `is abstract, you can override or replace services to do more features.
https://github.com/abpframework/abp/issues/4989#issuecomment-670577121
