### ISSUE TITLE
Angular Service Proxies (abp generate-proxy) support for AbpHub

### ISSUE THREAD

**Issue by kishoresahas** [abpframework/abp#7591]
### Documentatio
https://docs.abp.io/en/abp/latest/SignalR-Integration
https://docs.abp.io/en/abp/4.2/UI/Angular/Service-Proxies

does abp generate proxy support for AbpHub?

**Comment by maliming** [comment]
`generate-proxy` only for `controller`.

**Comment by kishoresahas** [comment]
This can be a great addition to ABP Framework.
