### ISSUE TITLE
Identity server dbcontext not created, when use dbmigrator

### ISSUE THREAD

**Issue by tanghaojie** [abpframework/abp#7594]
* Your **ABP Framework version**.     v4.2
* Your database provider                     EF Core

I download latest version abp vnext with Angular, EF-core, PostgreSQL, Separate Identity Server Option.
then, edit ConnectionString in  appsettings.json of  *.HttpApi.Host / *.IdentityServer / *.DBMigrator .
ctrl+F5, run *.DBMigrator project, cause error.
Abp db table created, but identity server db table not found. 
any more config needs?
![image](https://user-images.githubusercontent.com/14171892/106853374-94d56b00-66f4-11eb-8bd1-6c4242cf6d41.png)

**Comment by realLiangshiwei** [comment]
Cannot reproduce your problem.

![image](https://user-images.githubusercontent.com/16813853/106857186-a6ba0c80-66fa-11eb-89e7-f8c06c96ea86.png)

**Comment by tanghaojie** [comment]
> Cannot reproduce your problem.
> 
> ![image](https://user-images.githubusercontent.com/16813853/106857186-a6ba0c80-66fa-11eb-89e7-f8c06c96ea86.png)

Can you share your connectString and your postgresql environment? 
my connectstring is `User ID=postgres;Password=postgres;Host=192.168.0.1;Port=5432;Database=IdentityServer;Pooling=true;`
postgresql in docker `PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit`

**Comment by tanghaojie** [comment]
Found out that if project name contain `IdentityServer` or `*.IdentityServer`, will cause this error. may be keyword matter?
![image](https://user-images.githubusercontent.com/14171892/106986118-aaef3400-67a5-11eb-9edc-269369e78472.png)
