### ISSUE TITLE
How to get all AbpUsers records

### ISSUE THREAD

**Issue by yorytang** [abpframework/abp#7601]
I want to get all AbpUsers table record in application layer, but when i using 'IRepository<AppUser, Guid>' repository ,it always throw object null reference exception, pls advice.

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by yorytang** [comment]
1.Abp 4.0 version
2.Blazor Application layer
3.my sql

IRepository<AppUser, Guid> _appUserRepository

when excute code "var result = await _appUserRepository.GetListAsync()"  it throw exception "MySqlConnector.MySqlException (0x80004005): Table 'esubmission-db.appuser' doesn't exist"

**Comment by realLiangshiwei** [comment]
**Table 'esubmission-db.appuser' doesn't exist"** Please check your database.

**Comment by yorytang** [comment]
So what does this code mean in the abp Domain, are the AppUser same as AbpUsers?

/* This entity shares the same table/collection ("AbpUsers" by default) with the
     * IdentityUser entity of the Identity module.
     *
     * - You can define your custom properties into this class.
     * - You never create or delete this entity, because it is Identity module's job.
     * - You can query users from database with this entity.
     * - You can update values of your custom properties.
     */
    public class AppUser : FullAuditedAggregateRoot<Guid>, IUser
    {
        #region Base properties

        /* These properties are shared with the IdentityUser entity of the Identity module.
         * Do not change these properties through this class. Instead, use Identity module
         * services (like IdentityUserManager) to change them.
         * So, this properties are designed as read only!
         */
