### ISSUE TITLE
Using AddPooledDbContextFactory in ABP 4 with Entity Framework core

### ISSUE THREAD

**Issue by rygar08** [abpframework/abp#7603]
I'm migrating from ABP 3 to 4. I have existing graphql schema using Hotchocolate (nuget) which works fine in ABP v3. I get this error when executing a query in abp v4.

     Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application

In the Hotchocolate docs the recommend way for adding dbcontext is with services.AddPooledDbContextFactory. Is this possible in ABP?  

I seems to be related to this snippet from the hotchocolate docs...
`https://chillicream.com/docs/hotchocolate/integrations/entity-framework/`
The execution engine needs more than one database context. You should **register the database context in a pool rather than transient**. During execution database contexts are taken from this pool and returned once the resolver is completed. This has a smaller memory impact, as creating a new context for each resolver.

**Comment by maliming** [comment]
> In the Hotchocolate docs the recommend way for adding dbcontext is with services.AddPooledDbContextFactory. Is this possible in ABP?

No. Abp's dbcontext  does't support `AddPooledDbContextFactory` right now.

**Comment by rygar08** [comment]
Any Idea what changed in abp version 4 that caused it to fail? AddPooledDbContextFactory  wasn't used in abp version 3 either but Hotchocolate worked ok.

**Comment by maliming** [comment]
> Any Idea what changed in abp version 4 that caused it to fail?

No idea, but you can check https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0

**Comment by rygar08** [comment]
You know GraphQL is quite popular. I really like it. :)
