### ISSUE TITLE
[Blazor UI]: Stable 4.2.0 includes 'Preview' versions of Blazorise

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#7604]
**ABP Framework version** : v4.2.0
**User Interface** Blazor

Was it intentional to include **Preview** versions of **Blazorise** in the **Stable** channel (4.2.0)?

![image](https://user-images.githubusercontent.com/40014477/106983993-c2c4b900-67a1-11eb-8a9a-7184819bd456.png)

If so it does not make it easy for dev ops & nuget packaging sources.  would be preferable to make 4.2.0 stable across the board.

**Comment by maliming** [comment]
> Was it intentional to include Preview versions of Blazorise in the Stable channel (4.2.0)?

Yes.

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/NuGet.Config#L4
