### ISSUE TITLE
permission is not updated in cache

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#7608]
After I updated a role's permission, the cache for permission is not immediately updated. I manually checked redis and have to delete the corresponding cache to make the permission reload. Is there a way to immediately make permission take effect? I am using PermissionManagement Module to update permission in a microservice environment.

**Comment by gterdem** [comment]
Yes, it should be set to 5 mins or so for cache to update. 
Invalidating cache in distributed environment has some tricky points that we are still working on.
