### ISSUE TITLE
Stuck in the login Page after Changing Launch Settings from localhost to my ip

### ISSUE THREAD

**Issue by YoussefSalameh** [abpframework/abp#7610]
* ABP Framework version : 4.1.2.
* User Interface : Angular
* Database provider : EF Core

Hello everyone ,
when changing launch setting in my identity server module to be my ip address like below :
{
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://myipaddress",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
}

when trying to login it will be stuck in the login page and will not login but when I return it to localhost it will work properly.

Can you please provide us with a solution?

**Comment by YoussefSalameh** [comment]
@ZouZou

**Comment by maliming** [comment]
You also need to changes these IP. And re-migrator.
 
https://github.com/abpframework/abp/blob/dev/templates/app/angular/src/environments/environment.ts#L3
https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.HostWithIds/appsettings.json#L3
https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.HttpApi.HostWithIds/appsettings.json#L11
https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.DbMigrator/appsettings.json#L10

**Comment by YoussefSalameh** [comment]
Dear @maliming ,

I've tried what did you tell me to try but it didn't work properly , still stuck in the login page after login.
Note That I'm using Module template version 4.1.2

Can you please provide us with a solution?

**Comment by ZouZou** [comment]
Dear @maliming 

We are trying to run the IdentityServer using an IP without https
We get to the login page, we enter the username and password they authenticate correctly however when the browser redirects
it does not show me the user info; rather it shows me the login page again

![IdenityServer_Capture](https://user-images.githubusercontent.com/1358776/108983717-cf994600-7697-11eb-907a-3775ef5ca21c.PNG)

When we use the https with the ip, we get to the desired page (knowing that we fixed all the https mentions in our appsettings and in our db)
![IdenityServer_https_Capture](https://user-images.githubusercontent.com/1358776/108984099-3ae31800-7698-11eb-972d-b8678edcb782.PNG)
