### ISSUE TITLE
Identity Server - Manage Profile - Change Password Issue

### ISSUE THREAD

**Issue by sjagannathan** [abpframework/abp#7617]
Hi,

Issue Details: 
While trying to change default password for admin; I come across credentials being sent thru url query parameters as plain text. 
Not sure is it because I'm running instances on IISExpress. Also, password change was not successful evenafter multiple attempts.

Details below:
ABP Framework Version : 4.2.0
Interface Used : Blazor UI
Database Provider : EF Core (with SQL Server)
Solution Option : Application Solution with seperate Identity Server instance.
Instance : IISExpress (as part VS Run mode).

For your note: It works fine if I didn't seperate out Identity server.

Steps needed to reproduce  the problem. kindly refer attachment for steps.

Application Hosting Mode:
 
![image](https://user-images.githubusercontent.com/6908465/107107331-60d08600-686b-11eb-8fb3-06153a883771.png)

Select Manage Profile :
Change Password option: 
Provide default Password then provide inputs for New & Confirm Password.
 
![image](https://user-images.githubusercontent.com/6908465/107107335-64640d00-686b-11eb-885d-596ae7e744d8.png)

On submit: 
 

 
![image](https://user-images.githubusercontent.com/6908465/107107336-66c66700-686b-11eb-8f2d-b549975f7d2d.png)

![image](https://user-images.githubusercontent.com/6908465/107107337-6928c100-686b-11eb-9d17-521e799b6e2a.png)

Regards,
Jagan S.

**Comment by maliming** [comment]
Application Hosting Mode:
 
![image](https://user-images.githubusercontent.com/6908465/107107331-60d08600-686b-11eb-8fb3-06153a883771.png)


Select Manage Profile :
Change Password option: 
Provide default Password then provide inputs for New & Confirm Password.
 
![image](https://user-images.githubusercontent.com/6908465/107107335-64640d00-686b-11eb-885d-596ae7e744d8.png)


On submit: 
 

 
![image](https://user-images.githubusercontent.com/6908465/107107336-66c66700-686b-11eb-8f2d-b549975f7d2d.png)

![image](https://user-images.githubusercontent.com/6908465/107107337-6928c100-686b-11eb-9d17-521e799b6e2a.png)

**Comment by hikalkan** [comment]
Can you check if you see any error on browser console before submitting the form.

**Comment by realLiangshiwei** [comment]
Can not reproduce your problem.
