### ISSUE TITLE
Abp v 4.2 : The required antiforgery cookie ".AspNetCore.Antiforgery.cdo22mJC4Ec" is not present.

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#7620]
Abp version 4.2  tiered app.

* Steps needed to **reproduce** the problem : 
create a  : 

```csharp

    [Authorize("Test.Test")]

    public class myTestAppService : TestAppService, ITestAppService
    {

        public string GetTestAsync (string input)
        {
            return input;
        }

        public string TestAsync(string input)
        {
            return input;
        }


    }
```

when a call GetTestAsync from Swagger interface it work fine.

the problem occured when i call TestAsync , i get  The required antiforgery cookie ".AspNetCore.Antiforgery.cdo22mJC4Ec" is not present..

i know that Abpframework has auto validation for anti forgery token  as default configuration.

Any help please... it's urgent...

Best Regards.

**Comment by aelhadi** [comment]
![image](https://user-images.githubusercontent.com/5918026/107086605-896c6780-67fa-11eb-960d-ff9e6f0328af.png)


it also happen with your BookStore Demo

**Comment by aelhadi** [comment]
BookStore-Mvc-EfCore from samples, also generate the same error i tested in two defrente machines

**Comment by aelhadi** [comment]
the solution to make Post works from swagger :

```csharp
            Configure<AbpAntiForgeryOptions>(options =>
            {
                options.TokenCookie.Expiration = TimeSpan.FromDays(365);
                options.AutoValidateIgnoredHttpMethods.Add("POST");
 
            });
```

**Comment by maliming** [comment]
I can't repro.
