### ISSUE TITLE
spend too much time when loading

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#7621]
I just update to v4.2, it use 39 seconds
![image](https://user-images.githubusercontent.com/4489940/107118857-95b9f880-68be-11eb-858c-55604cbc9b4d.png)

**Comment by maliming** [comment]
Please check the application logs.

**Comment by ruby0602** [comment]
@maliming I never change the code

**Comment by ruby0602** [comment]
@maliming there is no error in the logs of IdentityServer and HttpApi.Host

**Comment by ruby0602** [comment]
I reinstall the redis to solve the problem
