### ISSUE TITLE
spend too much time when loading

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#7622]
I update to v4.2 without changing my code, it use too much seconds
![image](https://user-images.githubusercontent.com/4489940/107119271-84262000-68c1-11eb-84c9-57eb2146c59f.png)

**Comment by maliming** [comment]
Duplicate of #7621

**Comment by ruby0602** [comment]
@maliming there is no error in the logs of IdentityServer and HttpApi.Host, if it has some message in the logs, I maybe can sovle it by myselft.
