### ISSUE TITLE
Question about RouteTenantResolveContributor

### ISSUE THREAD

**Issue by SoftcaseDelmer** [abpframework/abp#7624]
Project configurations:
* ABP version: 4.2.0
* UI type: MVC
* db provider: EF Core

I don't know if I'm misunderstanding something, but when I try to use the tenant on route (something like **www.foo.com/tenant**) I get error 404.

I searched on docs, but I couldn't found any example about it.

**Comment by maliming** [comment]
> **RouteTenantResolveContributor**: Tries to find current tenant id from route (URL path). The variable name is __tenant by default. If you defined a route with this variable, then it can determine the current tenant from the route.

**Comment by SoftcaseDelmer** [comment]
Ok, but how the route (URL path) are supposed to be? ... Because when I try **www.foo.com/<tenant_name>** I get error 404 ... 

I have to specify on route like **www.foo.com/__tenant/<tenant_name>** or there is something else I have to do on the code?

**Comment by slarkerino** [comment]
@SoftcaseDelmer I think if you are trying to use a tenant url resolver, you have to pass _tenant as a variable. Eg: www.foo.com?_tenant=xxxx-xxx-xxxxxxxxx-xxx

**Comment by SoftcaseDelmer** [comment]
@slarkerino the way you are talking is the QueryString Resolve, I've already tried this resolve and it worked very weel, but what I need is to resolve the tenant on route ... And it's supposed to be a default resolve type.
