### ISSUE TITLE
I have a problem , It's about being a tenant

### ISSUE THREAD

**Issue by yerz** [abpframework/abp#7626]
My environment:
- abp 4.2
- No UI
- Tiered IdentityServer

Multi-tenancy is enabled by default , I use api**/api/multi-tenancy/tenants** create a tenant  . but failed, why?

![image](https://user-images.githubusercontent.com/30039842/107141770-05cf8980-6966-11eb-8f76-771a7eae3dfa.png)

![image](https://user-images.githubusercontent.com/30039842/107141787-167fff80-6966-11eb-9e5f-2a6e3d0e4dfd.png)

but i call api **/api/multi-tenancy/tenants** is successful !

![image](https://user-images.githubusercontent.com/30039842/107141958-e08f4b00-6966-11eb-8dc9-85e3e5c0e7d6.png)

I need to solve this problem

thanks

**Comment by aelhadi** [comment]
Hello 

That's what I m talking about in #7620 

We can't execute POST verb from swagger. 

Update your abp antiforgory options  as I did.

```csharp
Configure<AbpAntiForgeryOptions>(options =>
            {
                options.TokenCookie.Expiration = TimeSpan.FromDays(365);
                options.AutoValidateIgnoredHttpMethods.Add("POST");
 
            });
```

**Comment by yerz** [comment]
> Hello
> 
> That's what I m talking about in #7620
> 
> We can't execute POST verb from swagger.
> 
> Update your abp antiforgory options as I did.
> 
> ```cs
> Configure<AbpAntiForgeryOptions>(options =>
>             {
>                 options.TokenCookie.Expiration = TimeSpan.FromDays(365);
>                 options.AutoValidateIgnoredHttpMethods.Add("POST");
>  
>             });
> ```

thank you ,This is a bug in ABP?

**Comment by realLiangshiwei** [comment]
Can not reproduce your problem

**Comment by yerz** [comment]
> Can not reproduce your problem

I upgraded to 4.2 using only ABP CLI

Then run swagger ,Use **/API /multi-tenancy/tenant** API  in swagger POST 

400 errors occurred

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/pull/6818/files#diff-e444ffb8b030fd83c966c559c105bd9b5418f26563e6ea8c7ece47b257f92210R132-R228
