### ISSUE TITLE
Autofac integration issue - Ambiguous invocation

### ISSUE THREAD

**Issue by linch90** [abpframework/abp#7627]
* ABP version: 4.2.0.

When I upgrade Abp version to 4.2.0, the AddAutofac extension method display CS0121 error: ambiguous between the "AddAutofac" in the Volo.Abp.Autofac and Autofac.Extensions.DependencyInjection 6.0.0.0

And I also create a brand new project in Abp version 4.2.0, and this problem is still exists.

![image](https://user-images.githubusercontent.com/1113475/107144591-2c49f080-6977-11eb-8a3d-5c6b64b0931c.png)

This issue seems cause by PR #6463 which Add Autofac.Extensions.DependencyInjection package to the Volo.Abp.Autofac module

**Comment by maliming** [comment]
I can't reproduce this problem.

**Comment by linch90** [comment]
Just add package Volo.Abp.Autofac 4.2.0, in your module, add codes:
```csharp
public override void ConfigureServices(ServiceConfigurationContext context)
{
    context.Services.AddAutofac(builder =>
    {

    });
}
```
the  AddAutofac will display ambiguous problem.
This problem only show in Volo.Abp.Autofac 4.2.0, It's ok in Volo.Abp.Autofac 4.1.2 or before

**Comment by linch90** [comment]
I download a new abp project from https://abp.io/get-started. 
1. Install Volo.Abp.Autofac 4.2.0 to {projectName}.Domain
2. add below codes to {projectName}DomainModule.cs
```csharp
public override void ConfigureServices(ServiceConfigurationContext context)
{
    context.Services.AddAutofac(builder =>
    {

    });
}
```
![image](https://user-images.githubusercontent.com/1113475/107145584-9b2a4800-697d-11eb-9672-b4398391ff42.png)

* The problem is still exists.
I don't know if this is a computer environmental related issue, I will try it in another computer to see if the problem is still exists.
@maliming

**Comment by maliming** [comment]
You can temporarily resolve it via:
```cs
services.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(new AutofacServiceProviderFactory(builder =>
{

}));
```
