### ISSUE TITLE
JSON Api support

### ISSUE THREAD

**Issue by ludydoo** [abpframework/abp#763]
I would like to see abp.io introduce the json api specification support.

I failed to plug https://github.com/json-api-dotnet/JsonApiDotNetCore into aspnet core boilerplate.

It would be very useful if abp.io could out of the box support resources, relationships, links, includes, filtering, pagination etc. as defined per the json api specification.

Also, as a bonus, it would be even better if it could generate the Swagger / OpenApi specification from those resource definitions, enabling client generation (NSwag, etc.)

**Comment by tranthebao** [comment]
Can you are integration JSONAPI into module core abp
I see core base module json basic and json newtonsoft
