### ISSUE TITLE
BookStore Tutorial Blazor Project Stuck in login page

### ISSUE THREAD

**Issue by barbarosyurttagul** [abpframework/abp#7634]
Hi, I downloaded the BookStore Project, did the steps in the tutorial until I stuck in Blazor project. My database is created, swagger page runs however Blazor project doesn't. I added the screenshot of the browser displaying the errors. Could anyone help?

* My ABP Framework version: 4.2.0.
* My User Interface type: (Blazor)
* My database provider(EF Core)

![Capture](https://user-images.githubusercontent.com/10248633/107155413-28ff3680-6970-11eb-8614-3303051d2bf5.PNG)

**Comment by realLiangshiwei** [comment]
Make sure `localhost:44354` is running

**Comment by LeiYangGH** [comment]
where are the database scripts?

**Comment by barbarosyurttagul** [comment]
> `44354`

How can I be sure that localhost:44354 is running? I just follow the tutorial, and click start. FYI, the angular template works fine but this template, I mean Blazor doesn't.

**Comment by barbarosyurttagul** [comment]
> Make sure `localhost:44354` is running

Yeah you are right. First, I have to keep the Http.Api.Host project (opens the swagger web browser) running and then run the Blazor project. If I close the swagger web browser, then Blazor doesn't work.

**Comment by LeiYangGH** [comment]
cd to web api host, `dotnet run`, 
then start blazor project

**Comment by msh2050** [comment]
this should be added to getting start instructions
