### ISSUE TITLE
Module '"../proxy/books"' has no exported member 'BookDto'.

### ISSUE THREAD

**Issue by ChongZhiCZ** [abpframework/abp#7641]
### Documentation

> https://docs.abp.io/en/abp/latest/Tutorials/Part-2?UI=NG&DB=EF#bookcomponent

### Environment
- ABP version:4.2
- UI:Angular
- database provider:EF Core

### Previous step
I followed the document step by step, the following is the previous step of the problem
`abp generate-proxy`
`[11:40:48 INF] ABP CLI (https://abp.io)`
`[11:40:49 INF] Version 4.2.0 (Stable)`
`[11:40:49 WRN] Couldn't determinate version of "@abp/ng.schematics" package.`
`CREATE src/app/proxy/generate-proxy.json (162715 bytes)`
`CREATE src/app/proxy/README.md (1000 bytes)`
`CREATE src/app/proxy/books/book.service.ts (1466 bytes)`
`CREATE src/app/proxy/books/models.ts (166 bytes)`
`CREATE src/app/proxy/models.ts (249 bytes)`
`CREATE src/app/proxy/books/book-type.enum.ts (284 bytes)`
`CREATE src/app/proxy/books/index.ts (92 bytes)`
`CREATE src/app/proxy/index.ts (78 bytes)`

### Issues
Hi
After replacing the content according to the first step of the document
Module '"../proxy/books"' has no exported member 'BookDto'.
![Code](https://user-images.githubusercontent.com/74161482/107176353-18030380-6a0a-11eb-95ff-1ba0d412a723.png)
![Structure](https://user-images.githubusercontent.com/74161482/107176355-19343080-6a0a-11eb-86bd-d8b5a6f9c943.png)

**Comment by maliming** [comment]
If you're creating a bug/problem report, please include followings:

* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by ChongZhiCZ** [comment]
Sorry, I edited it again

**Comment by armanozak** [comment]
Hi @zico209,

Could you please check if `src/app/proxy/books/models.ts` file has `BookDto` in it?
