### ISSUE TITLE
RabbitMQ rapidly re-delivers the messages

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#7657]
When we have an exception while processing a distributed event (integrated to RabbitMQ), we send a NACK message to the server, so it is re-queued. However, RabbitMQ immediately re-sends the message, and probably we get the error again. It would be better to stop sending messages to this application for a while.
I don't know if RabbitMQ has such a configuration. If anyone knows, please write here, otherwise we will look for it.
Otherwise, how can we solve that problem?

**Comment by fmpfmp** [comment]
https://www.rabbitmq.com/dlx.html

**Comment by realLiangshiwei** [comment]
We can consider abstract error handling (dead letter queue) and implement it for each provider

**Comment by fmpfmp** [comment]
@realLiangshiwei   and retry policy

**Comment by hikalkan** [comment]
I moved this to backlog. @realLiangshiwei if you find a good way, please write to me, so we decide to add a proper milestone.

**Comment by slarkerino** [comment]
@hikalkan I have faced this issue when I am using Rabbitmq. My Application keep try and throw exceptions :(
