### ISSUE TITLE
SettingValueProviderManager

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#7664]
Hello,
when i research, Volo.Abp.Settings framework code i confused because

SettingValueProviderManager is ISingletonDependency and its contain ISettingValueProvider list
but SettingValueProvider is ITransientDependency

so when we resolve ISettingValueProviderManager for once SettingValueProviders will initialize for once right?

then UserSettingValueProvider how will work right for get currentuser?

**Comment by real-zony** [comment]
Hi muratyuceer,
The Providers in `SettingValueProviderManager` are initialized only once when the constructor is executed, which is no problem. It has nothing to do with `ICurrentUser`. The data of `ICurrentUser` is obtained from `IHttpContextAccessor`, the JWT Token for each request.

**Comment by muratyuceer** [comment]
thanks for the explanation
