### ISSUE TITLE
datatables datetime formats

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#767]
Is there a recommended way to format the datetime fields being returned in the table population javascript of any of the samples?  Datatables.net recommends using moment.js, but that isn't bundled with ABP.

**Comment by djlaney3** [comment]
I understand that, but what I was asking if they Abp a recommended way.  If I include moment myself, how do I get the datatables functions to work: `$.fn.dataTable.render.moment( 'MMM YYYYY' )`   I feel like I missing how to grab Abps bundled dataTable to do this.

**Comment by djlaney3** [comment]
I was able to solve this by changing my column def to
`{`
`                "data": 4, "title": "Created",`
`                "render": function (data, type, full, meta) {`
`                    return moment(data).format('YYYY-MM-DD');`
`                }`
`            }`

**Comment by ismcagdas** [comment]
@djlaney3 probably we will create a npm package for moment like we did for other popular javascript libraries.
