### ISSUE TITLE
Access to IdentityServerBuilder

### ISSUE THREAD

**Issue by Ultre00** [abpframework/abp#7678]
I would like to call some functions on the IdentityServerBuilder like AddCustomTokenRequestValidator and AddResourceOwnerValidator. Maybe it is enough if I could override the AbpResourceOwnerPasswordValidator but it doesn't seem to be possible either.

So my question would be if you could add the IdentityServerBuilder :https://github.com/abpframework/abp/blob/2b18e14dee35651be5a628b512fcd24458da00f7/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AbpIdentityServerDomainModule.cs#L65

The same way as the IdentityBuilder is added over here:

https://github.com/abpframework/abp/blob/a53aaef0cd5eec73b8999d48cabb9be8c10c7667/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/AbpIdentityDomainModule.cs#L50

This so I could call this object in the ConfigureServices of my Module

``` c#
context.Services
.GetObject<IdentityServerBuilder>()
.AddCustomTokenRequestValidator<CustomValidator>()
```

**Comment by real-zony** [comment]
@maliming What do you think, I think this is very useful in the actual development process.

**Comment by maliming** [comment]
We can use `PreConfigure` method.

```cs
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<IIdentityServerBuilder>(identityServerBuilder =>
    {
        identityServerBuilder.AddCustomTokenRequestValidator<CustomValidator>();
    });
}
```
