### ISSUE TITLE
Logo replacement documentation seems to be outdated

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#7679]
3.3.2 / Angular

Following your doc, I can see you suggest to use `AddReplaceableComponent` for logo replacement. At the same time, you say `AddReplaceableComponent` is outdated and `ReplaceableComponentsService` needs to be used instead. When I put `ReplaceableComponentsService` in [dep] instead of `Store` - I still cannot run the example, getting "No provider for AccountLayoutComponent!" error.

**Comment by alexandis** [comment]
Looks like works with the following adjustment:

```
export const APP_LOGO_PROVIDER = [ AccountLayoutComponent,
  { provide: APP_INITIALIZER, useFactory: switchLogos, multi: true, deps: [ReplaceableComponentsService] },
];
```

**Comment by alexandis** [comment]
I suspect it is not possible to make working for external authentication app (i.e. `IdentityServer` in my case), since it's a different (not _Angular_) app. So what is described in the doc is the case for _Login box_ residing in _Angular_ app, here the logo cannot be changed:

![image](https://user-images.githubusercontent.com/6149843/107400310-5da6f580-6b0a-11eb-8657-144f3aa5051c.png)

**Comment by maliming** [comment]
You should check the MVC document.

https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface
https://community.abp.io/articles/how-to-customize-the-login-page-for-mvc-razor-page-applications-9a40f3cd

**Comment by alexandis** [comment]
Ok - will consider this. Thank you. Please, update Angular documentation anyway to make it up-to-date.
