### ISSUE TITLE
What is the name of Application.Contracts in other domain driven architecture?

### ISSUE THREAD

**Issue by mehdihadeli** [abpframework/abp#768]
Hi,
In other domain driven design except for abp, what is the name of application contract where you used in abp? can you give me some article for that?

**Comment by hitaspdotnet** [comment]
Application.Contract (or Application.Shared in previous ABP) is a shared library between business methods and other usages. Which contains interfaces and DTOs and works well in generic scenarios, The jobs of this libraries (Application/Application.Contracts) are isolating Domain from other layers. You can merge the application layers safely but is recommended in Onion Architecture. 

GL.
