### ISSUE TITLE
CLI generate-proxy, specifying api and module errors

### ISSUE THREAD

**Issue by Jasonkingsmill** [abpframework/abp#7681]
Using ABP 3.2.1 in a microservices architecture with Angular front-end.

We have several microservices (lets call them Accounting, Customer and Order), each with a controller with an Area attribute(module name) and RemoteService named as per the microservice name. Using the Abp CLI, we are attempting to generate proxies for each of these services individually.
A snippet of our environment.ts file:

  ```
apis: {
      default: {
        rootNamespace: "Example",
        url: 'https://localhost:5000',
      },
      Accounting: {
        rootNamespace: "Example",
        url: 'https://localhost:5010',
      },
      Customer: {
        rootNamespace: "Example",
        url: 'https://localhost:5011',
      },
      Order: {
        rootNamespace: "Example",
        url: 'http://localhost:5012',
      }
```
When running generate-proxy for the first time, it works fine. E.g `abp generate-proxy --module order --api-name Order`.
However when running this for the second time against a different API (E.g, `abp generate-proxy --module accounting --api-name Accounting`, it fails with an error saying:
`[Invalid Module] Backend module "order" does not exist in API definition` - however when this errors we are actually attempting to target the "accounting" module.
The behavior here seems to be that it's expecting any previously generated modules to exist in all target API's.

This was also posted on SO, but the more I think about it the more it seems like a legitimate bug?

**Comment by gterdem** [comment]
Probably you are having this issue because of using single frontend with many backends. Proxy generating is designed for moduler approach and it generates per backend. 
So, for microservice approach; BFF pattern should be suitable for proxy generator.

**Comment by Jasonkingsmill** [comment]
> Probably you are having this issue because of using single frontend with many backends. Proxy generating is designed for moduler approach and it generates per backend.
> So, for microservice approach; BFF pattern should be suitable for proxy generator.

I’m not sure I understand what purpose having separate API url configuration per remote service is if the proxies must be generated from a single backend?
