### ISSUE TITLE
EmailConfirmed set to false when updating name

### ISSUE THREAD

**Issue by martenw** [abpframework/abp#7684]
Creating a new issue since I was unable to re-open #7430

The problem can still be reproduced in a clean 4.2.1 version, from what I can see that issue was tagged with 4.2-final milestone and should have been resolved in current release?

Steps to reproduce: https://github.com/abpframework/abp/issues/7430#issuecomment-766616859

**Comment by gterdem** [comment]
@maliming can you check please?

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/pull/7741
