### ISSUE TITLE
Talking about requirement for IdentityServer Module in Docs

### ISSUE THREAD

**Issue by amsaighi** [abpframework/abp#7687]
Finally we got the problem, and we found the solution 
The certificate SSL does not correspond to the domain name.

Thank you everyone

_Originally posted by @amSaighi in https://github.com/abpframework/abp/issues/7485#issuecomment-776685259_

**Comment by gterdem** [comment]
Nice to hear your problem solved.

Though, this is not related with abp nor identityserver. This is a common [ssl name mismatch error](https://www.globalsign.com/en/blog/what-is-common-name-mismatch-error#:~:text=A%20common%20name%20mismatch%20error,the%20SAN%20of%20the%20certificate.) when setting up https for **any** application. So it is not related with abp docs.

**Comment by amsaighi** [comment]
> Nice to hear your problem solved.
> 
> Though, this is not related with abp nor identityserver. This is a common [ssl name mismatch error](https://www.globalsign.com/en/blog/what-is-common-name-mismatch-error#:~:text=A%20common%20name%20mismatch%20error,the%20SAN%20of%20the%20certificate.) when setting up https for **any** application. So it is not related with abp docs.

I do agree with you, it's related with abp and identity server, but it took me time to identify it. therefore it's why I suggest to talk about it in documentation.

Thank you
