### ISSUE TITLE
The name 'Initial' is used by an existing migration.

### ISSUE THREAD

**Issue by michelveloso** [abpframework/abp#7688]
ABP Framework: **4.2.1**
User Interface: **MVC**
Database Provider: **EF Core / PostgreSQL**
Exception: **The name 'Initial' is used by an existing migration.**

Hi!
When I start a new project, and run the command **dotnet run** in DbMigrator I got the error: **The name 'Initial' is used by an existing migration.**

![Screenshot_20210210_105510](https://user-images.githubusercontent.com/346317/107519122-a0aaac80-6b8e-11eb-93c7-b4192808acc9.png)

In the migrations folder, I only found one **Initial** file, but if I try to remove the migrations and run again, I got the same error

![Screenshot_20210210_105715](https://user-images.githubusercontent.com/346317/107519303-e1a2c100-6b8e-11eb-80cf-19533485352d.png)

**Comment by olicooper** [comment]
This is probably because your `__EFMigrationHistory` database table has an 'Initial' record in it. Delete the database and try again.

**Comment by michelveloso** [comment]
@olicooper , this process is taking place even before the database was created

**Comment by michelveloso** [comment]
@olicooper , when I start a new template like bellow, the run the command **dotnet run** in **DbMigrator** I got the same error.

https://abp.io/get-started

![Screenshot_20210210_185500](https://user-images.githubusercontent.com/346317/107577830-af668300-6bd1-11eb-84e6-c21b87d7067f.png)

**Comment by gterdem** [comment]
> The startup template uses Entity Framework Core's Code First Migrations. EF Core Migrations depend on the selected DBMS provider. So, changing the DBMS provider will cause the migration fails.
> 
> Delete the Migrations folder under the .EntityFrameworkCore.DbMigrations project and re-build the solution.
> Run Add-Migration "Initial" on the Package Manager Console (select the .DbMigrator (or .Web) project as the startup project in the Solution Explorer and select the .EntityFrameworkCore.DbMigrations project as the default project in the Package Manager Console).
> This will create a database migration with all database objects (tables) configured.
> 
> Run the .DbMigrator project to create the database and seed the initial data.

From docs [here](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-PostgreSQL#re-generate-the-migrations).

**Comment by michelveloso** [comment]
@gterdem @olicooper I created a video to illustrate my problem.

but in summary, I did not change the dbms, I kept the project default, however the error occurs anyway

https://youtu.be/Vk3d_d4yFRs

**Comment by olicooper** [comment]
I used your example https://github.com/abpframework/abp/issues/7688#issuecomment-777063407 to create a solution with a SQLite database and it works fine for me using `dotnet run` in the `src/*NewTest01.DbMigrator` folder. 

Once it has run for the first time it creates a new database: 
_"src/NewTest01.**DbMigrator**/NewTest01.db"_ 
... and if this isn't deleted when you regenerate the migrations, you will get the error "initial migration already exists". This is what I think is happening for you. Maybe the file is hidden on your OS? You can run `ls -a` (linux) or `dir -Force` (windows) in the _DbMigrator_ folder?

**Comment by michelveloso** [comment]
@olicooper I found the problem, but not the solution.

When I execute the command "**abp create-migration-and-run-migrator...**", he is calling it twice ... This problem is only occurring in **Ubuntu**, in **Windows** it works correctly.

![Screenshot_20210213_091503](https://user-images.githubusercontent.com/346317/107849758-2ff8cf80-6ddc-11eb-8fb5-e67919094b62.png)

**Comment by olicooper** [comment]
This is interesting, thanks for pointing that out! I have looked at the source code and I think you are correct, but I think the way you are running the project might be wrong (I'm not sure because I develop with Windows). Normally to migrate the database you would build the project which creates the dll files, then run the built `DbMigrator.exe` file (on Linux I think you run the `dll` file instead). So I maybe you are meant to do something like `dotnet DbMigrator.dll`? Could you test this and see if it works?

You can see in the source code a call to 'dotnet run', so your effectively running it twice: https://github.com/abpframework/abp/blob/58997b362e56daab22fecd370fb2ee1e1f5dd60b/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/CreateMigrationAndRunMigrator.cs#L31-L34

**Comment by olicooper** [comment]
Hey @michelveloso did the suggestion above fix your issue? If everything is okay now make sure to close the issue 👍

**Comment by baraayouzbashi** [comment]
@olicooper  i had the same problem and i solved it based on the idea you mentioned,
here is a workaround:
after building the project successfully with `dotnet build`, i navigated to the project `<ProjectName>EntityFrameworkCore.DbMigrations` and then ran the commands :
`dotnet ef migrations add initial` 
then
`dotnet ef database update` 
and everything worked perfectly
for the record i'm using ABP version 4.2.2 
i hope this saves someone's time :)

**Comment by supernovalx** [comment]
Things work fine on Windows. However, I had the same problem when running it on Ubuntu 18.04. This is very discouraging since I just get started 😫
