### ISSUE TITLE
Many-To-Many relationship with AppUser

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#7689]
We have Entity called Branched as below
```
public class Branch : FullAuditedEntity<int>, IMultiTenant
    {
        public string Name { get; set; }
        public Guid? TenantId { get; set; }
    }
```
and need to extend AppUser entity to contain list of assignedBranches, is there any implemented way to do this?

**Comment by olicooper** [comment]
The basic template describes adding properties to the AppUser model: https://github.com/abpframework/abp/blob/1ccf95f161372353e2ee6027d983739e6b9fb12b/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Users/AppUser.cs#L43-L56

You should be able to modify your `MyProjectModelCreatingExtensions`. I can't remember the syntax properly but something like this:
```csharp
// Link table - which you could access directly to get either end of the relationship
builder.Entity<BranchUsers>(b =>
{
    b.HasOne(x => x.User).WithMany().HasForeignKey(x => x.UserId);
    b.HasOne(x => x.Branch).WithMany().HasForeignKey(x => x.BranchId);
    b.HasKey(x => new { x.UserId, x.BranchId });
});

// .. and optionally add properties to the other entities
builder.Entity<Branch>(b =>
{
    b.HasMany(x => x.BranchUsers).WithOne(x => x.Branch);
});

builder.Entity<Users.AppUser>(b =>
{
    b.HasMany(x => x.BranchUsers).WithOne(x => x.User);
});
```

Also, take a look at [object extensions](https://docs.abp.io/en/abp/latest/Object-Extensions).

**Comment by gterdem** [comment]
[IdentityUser](https://github.com/abpframework/abp/tree/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity) already has many to many [OrganizationUnit](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/OrganizationUnit.cs) if it works for you.
If not, you can implement it just like OrganizationUnit.
