### ISSUE TITLE
415 unsupported Media Type

### ISSUE THREAD

**Issue by rafaelgfirmino** [abpframework/abp#7691]
I have followed [this](https://volosoft.com/Blog/File-Upload-Download-with-BLOB-Storage-in-ASP.NET-Core-and-ABP) tutorial
 ```cs
 
  public class SaveBlobInputDto
    {
        public byte[] Content { get; set; }

        [Required]
        public string Name { get; set; }
    }
   
```

```cs
public async Task SaveBlobAsync(SaveBlobInputDto input)
        {
            await _fileContainer.SaveAsync(input.Name, input.Content, true);
        }
```

But i can't upload file using insomnia or postman
The error returned:  ***415 unsupported Media Type***

In my postman or insominia I set the Content-Type with multipart/form-data;

**Comment by berkansasmaz** [comment]
The `Content` property in `SaveBlobInputDto` is of the type byte array, so the `Content-Type` may be wrong. `File` property with the `IFormFile` type in the "Creating User Interface" header of the tutorial is already being converted to a byte array.

**Comment by rafaelgfirmino** [comment]
Thanks @berkansasmaz, helped alot. 

I found this tutorial  explaining how do upload files in aspnet, works fine for me.
https://www.youtube.com/watch?v=EuWO0bDgVgc
