### ISSUE TITLE
Best practice to integrate CosmosDB

### ISSUE THREAD

**Issue by evenlee** [abpframework/abp#7692]
I searched the issue histories an features, most of the case is in 2019 or early 2020, and I saw there are feature tags for both doc and cosmos integration, but still open, could you help to show some guide or sample code of the best way to integrate ComsmosDB, thanks.

**Comment by gterdem** [comment]
I think you can either use [Ef Core Azure Cosmos DB Driver](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli) or [Mongo DB Api](https://docs.microsoft.com/en-us/azure/cosmos-db/create-mongodb-dotnet). It is in our backlog and eventually we will integrate after proper research.

**Comment by evenlee** [comment]
Thanks, I found https://github.com/IEvangelist/azure-cosmos-dotnet-repository, which works good for me now.

**Comment by buaziz** [comment]
can documentation be added to ABP docs to show how to utilize Azure Cosmos as a datasource. 

Thanks
