### ISSUE TITLE
Error Reference Number Feature

### ISSUE THREAD

**Issue by Moustafa20** [abpframework/abp#7693]
Hello

It would be very useful if user got an error reference number when something wrong occurred while using the application as he can just forward that reference number to the technical support of the application so they can help help 

I'm not talking here about general exceptions only but also the logic exception and that is the point 

admin or developer should have the ability to configure the prefix of the error reference number according to the exception type

hope that clear and willing to see that feature developed in both abp & Zero very soon

Regards

**Comment by gterdem** [comment]
> I'm not talking here about general exceptions only but also the logic exception and that is the point

I think you mean bussiness logic exceptions. 

Abp has infrastructure for this. You can add your own error codes to **MyProjectErrorCodes** under MyProject.Domain.Shared project and throw them accordingly to your business rules.

**Comment by Moustafa20** [comment]
I think you mean custome status code which I can add them as you mention.. Is that true?

I meant identity key for the errors like primary key which can be used as reference number for the errors

When client report an error faced him in the app he just need to provide me with the reference number

Hope that clear enough

Thanks

**Comment by Moustafa20** [comment]
Any ideas or updates?
