### ISSUE TITLE
Bundling, NUglify Exception

### ISSUE THREAD

**Issue by mrs01dev** [abpframework/abp#7700]
Dear ABP Dev's.
How to bypass or disable NUglify  ?
The issue is :
Volo.Abp.Minify.NUglify produces too many exceptions for java script code -Vue JS code-
like :
Implicit property name must be identifier: data()

The issue is the same as
https://github.com/abpframework/abp/issues/7667
https://github.com/abpframework/abp/issues/2767

Thanks

**Comment by gterdem** [comment]
You can configure **AbpBundlingOptions** under _ConfigureServices_ as you desire. Default is **Auto**.

```
Configure<AbpBundlingOptions>(opt =>
{
       opt.Mode = BundlingMode.None;
});
```

**Comment by mrs01dev** [comment]
Thanks Galip Tolga Erdem.
