### ISSUE TITLE
How to properly remove all abp-related tables from migration

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#7709]
How to properly remove all abp sql tables when new abp application is created?
I tried removing builder.Configurexxx() inside xxxMigrationsDbContext.cs (.DbMigrations\EntityFrameworkCore project), create new migration (successfully) and when DbMigrator is launched, this error happened:

![image](https://user-images.githubusercontent.com/39346964/107786793-9505e400-6d4e-11eb-8ff2-53e5e4ee1a4c.png)

It's important for us that some new abp applications DO NOT generate abp-related tables in database.
Thank you.

**Comment by leonkosak** [comment]
Anyone?

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

Do you just want to seed data when running **DbMigrator**?

**Comment by leonkosak** [comment]
abp v4.2.1

In xxxMigrationsDbContext.cs file, the following builder entries was deleted (commented-out):
![image](https://user-images.githubusercontent.com/39346964/108019999-b3ecca80-701b-11eb-8679-b35d35adfe5c.png)

Seeding data is required when modules are installed, otherwise not.

**Comment by maliming** [comment]
**MyProjectNameDbMigrationService** will use **IDataSeeder**, if you delete the table, you should also remove the dependency on the module. eg **Identity module.**

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain/Data/MyProjectNameDbMigrationService.cs

**Comment by leonkosak** [comment]
@maliming, sorry for long waiting. Yes, I would still like to seed data in my specific tables, but not in Abp-related tables.
I deleted IDataSeedContributor from all places in abp application, but this not solves issue.
Thank you.

I removed also abp-related module on Domain project in DependsOn.

**Comment by leonkosak** [comment]
@maliming, is there a way how to remove abp-related (for abp tables) dataseeding?
Our scenario:
We have **module** (with dataseeder logic for some of our tables) and this module is "wrapped" in abp **application**, but this application is only "dedicated" DbMigrator app, which has connection string to existing database. For this existing database, we have separated migrator application and therefore, other dedicated migrator applications should not adding/changing anything.

We would like to remove abp-related dataseeding to prevent damage and execution errors.
Thank you.

**Comment by leonkosak** [comment]
@hikalkan, do you have any suggestions?

**Comment by maliming** [comment]
hi @leonkosak 

Can you share a project?

**Comment by aligoren** [comment]
Is there any progress?
