### ISSUE TITLE
Remove email settings from the appsettings.json files

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#7711]
Remove from the startup templates (including volo repo).
Because we've added emailing setting management to the application UI.
Please also test if emailing setting management properly works in all templates and all UI types (tiered, separate ids... etc).

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/107898471-c103ae00-6f76-11eb-9884-086354b33c33.png)
