### ISSUE TITLE
ExtraProperties Can Not be updated

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#772]
EF Core ConfigureExtraProperties  use Value Conversions to convert Dictionary to string colum. But if we directly set key-value in entity.ExtraProperties, ef cannot detect property change during update

**Comment by hikalkan** [comment]
Hmmm.. didn't know that. Should be tested. Thank you for informing.

**Comment by hikalkan** [comment]
I added integration tests (works with inmemory SQLite) and it seems working: https://github.com/abpframework/abp/commit/d07a689cb11cb78865c5d5ab27aafc0dff6cfd74#diff-19dff7480171145bae8f3387b91a5059

Did you try it yourself? If so, we will also try with a real application.

**Comment by Goxiaoy** [comment]
I have tested with MySQL and failed.

For temporary solution, I have to added code below in every extra entity to fix that.

```
        public void UpdateExtra(string key, object value)
        {
            var newDic = new Dictionary<string, object>(ExtraProperties);
            newDic[key] = value;
            ExtraProperties = newDic;
        }
``` 

And I can not write an extension function for IHasExtraProperties cause ExtraProperties have no setter

**Comment by acjh** [comment]
> ***One important thing** I have noticed, however, is that when updating the entity and changing items in the dictionary, the EF change tracking does not pick up on the fact that the dictionary was updated, so you will need to explicitly call the `Update` method ... to set the entity to modified in the change tracker.*

— https://www.jerriepelser.com/blog/store-dictionary-as-json-using-ef-core-21/

**Comment by hikalkan** [comment]
Good point @acjh that means repository.Update (or UpdateAsync) method should always be called. Actually, this is a best practice that we suggest with this ABP framework. All the pre-built modules do it.

Creating a new dictionary for each change is not efficient and seems bad to me.
