### ISSUE TITLE
FeatureManagementModal.chtml

### ISSUE THREAD

**Issue by datarebel** [abpframework/abp#7722]
It's missing this line!

**id="FeaturesGroups[@i].Features[@j].BoolValue"**
```
@if (feature.ValueType is ToggleStringValueType)
{
    <abp-input asp-for="@feature.Value"
               type="checkbox"
               **id="FeaturesGroups[@i].Features[@j].BoolValue"**
               name="FeatureGroups[@i].Features[@j].BoolValue"
               label="@feature.DisplayName"
               disabled="@disabled"
               group-data-feature-name="@feature.Name"
               group-data-parent-name="@(feature.ParentName ?? "")"
               group-style="margin-left: @(feature.Depth * 20)px" />

}
```

**Comment by maliming** [comment]
What is your purpose for **id="FeaturesGroups[@i].Features[@j].BoolValue"**?

**Comment by datarebel** [comment]
It allows multiple features with checkboxes to be clickable. Without you can only check/uncheck the topmost feature, no matter what checkbox you click.

**Comment by maliming** [comment]
hi @datarebel 
You can resolve it via replacing `FeatureManagementModal.cshtml` for now.

**Comment by datarebel** [comment]
Yes, I already did this for the time being.  Thanks for acknowledging the issue so quickly!

Cheers...
