### ISSUE TITLE
The Correct Process to provide CSRF to Third Party API client 

### ISSUE THREAD

**Issue by wgodfrey-pernix** [abpframework/abp#7724]
*    ABP Framework version: v4.2.0
*    UI type: MVC
*   DB provider: EF Core

Hi ABP,

What is the process to remove an external API client from CSRF validation. At the moment we have to disable CSRF tokens as there is no clear method in the documentation on how to filter specific by external API client etc. I've currently got the Autovalidation disabled at the HTTP API module but I'm concerned this also impacts our Web Layer.
```
Configure<AbpAntiForgeryOptions>(options =>
{
      options.AutoValidate = false;
});
```
Kind Regards,
William Godfrey

**Comment by maliming** [comment]
hi 

What's kind of your  **external API clien**?

**Comment by wgodfrey-pernix** [comment]
it's a Mobile API client in the form of an Apple APP

**Comment by maliming** [comment]
For clients that do not use cookies, it will automatically pass.

> Server side validates the antiforgery token only for same and cross site requests made by the browser. It bypasses the validation for non-browser clients.

**Comment by gerryge** [comment]
I have the same issue, my abp version is 4.2.2.
When I use **react.js**(react antd pro v5) to call put api will occur error.
![image](https://user-images.githubusercontent.com/6952917/111429449-f8ab7480-8733-11eb-9fe5-68125aedb62b.png)

How can I fix this issue?

The strange thing is that in my mac book is good but it is occur error in my two windows 10 pc.
