### ISSUE TITLE
Linking to AbpUsers from CreatorId

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#773]
Is there a recommended framework way to link back to the AbpUsers table to get username or email from an Audited entity?  I have a need to show the creator's username and email, but obviously my Audited entity only holds id.   I can think of a few ways to solve it, but I wasn't sure if the framework had some way of easily doing this.

**Comment by hitaspdotnet** [comment]
From where? 
From a module checkout blogging module post writer. 
From a application use `IUserLookupService.GetByIdAsync(Guid userId)`

GL.

**Comment by hitaspdotnet** [comment]
If you are using AsyncCrudApplicationService you need to override GetListAsync method.
Then in overrider method body insert this lines
```C#
{
    var outputs = await base.GetListAsync(yourGetListInput);
    foreach (var output in outputs)
    {
        var user = await _userLookupService.GetByIdAsync(output.CreatorId);
        output.UserEmail = user.EmailAddress;
    }
    return output;
}
```

**Comment by djlaney3** [comment]
@hitaspdotnet - that is a great solution.  I wasn't thinking in a row by row mindset.  I was trying to solve this in batch (hopefully in some type of table join in ef) to avoid the many sql query hits.  However, this will work just fine for my dataset, which will probably only have 5 or 10 shown on the screen at a time.  I will give this a go in the next day or two.

**Comment by hitaspdotnet** [comment]
@djlaney3 There is 2 tables and you cant have User entity shadow in your entity. User data comes from deferent module. So you need to use API to getting User data. If user data is important in your architecture checkout Blogging module. Blogging module has own user data. Which is same with Identity module (both tables was update by event triggers).

**Comment by hikalkan** [comment]
Hi guys,

This is a good discussion. One of the main goal of the new ABP framework is to create microservice-compatible modules. Auditing database, in practice, can be different than the identity database, hence we can not add a foreign key relation and can not easily join AbpUsers table and audit log tables. 

However, in microservice/distributed world, it's acceptable to duplicate data, especially the data rarely changing. So, we can consider to add UserName, Email & FullName fields to the Audit log table. This will duplicate data, but will make querying easier.

**Comment by hitaspdotnet** [comment]
I think Email is not generic and maybe not useful. For Email address we can have new request where we need that. In @djlaney3 scenario, we can having a request for all details for just a row of table. Email address in dataTable out of User manager Is not popular.

**Comment by Trojaner** [comment]
```cs
public static void ConfigureForeignKeys<TEntity>(this EntityTypeBuilder<TEntity> ent) where TEntity : class, IEntity
{
    // the check was a bit different to ensure CreatorUser property actually exists
    if (typeof(FullAuditAggregateRoot<TKey>).IsAssignableFrom(typeof(TEntity))) 
    {
        var userType = isMigrationDb ? typeof(IdentityUser) : typeof(AppUser);
        ent.Property(userType, "CreatorUser");

        // Repeat for LastModifierUser, DeleterUser...
    }
}
```

I tried to fix foreign keys like this, however EF Core still checks if the given property type actually matches the one defined in the model. This is depressing, as I can not use foreign keys to users anywhere.

It seems like I need to use conditional compiling, e.g.
```cs
#if MIGRATION
public virtual IdentityUser CreatorUser { get; set; }
#else
public virtual AppUser CreatorUser { get; set; }
#endif
```

This does not look fun or possible in a way that does not need manual switching the condition.

**Comment by hikalkan** [comment]
@Trojaner we don't declare foreign keys between modules, because of [the reason I declared](https://github.com/abpframework/abp/issues/773#issuecomment-460386971).

With the latest startup template, we added a separated project & DbContext for migrations: https://github.com/abpframework/abp/tree/master/templates/mvc/src/MyCompanyName.MyProjectName.EntityFrameworkCore.DbMigrations

Each module has its own DbContext on runtime. This migration DbContext is like a union of all dbcontextes to maintain a single database schema.
Normally, in this migration dbcontext, you should be able to declare your foreign key relations. Is there a problem on that?
If so, I will try to accomplish that myself to see the problem better.

BTW, we never use navigation properties to other aggregate roots, because it is a rule of DDD: You can only refer other aggregates by Id. However, since EF Core supports is, we should not prevent it.

**Comment by Trojaner** [comment]
If I got this correct, model builders can not declare foreign keys without navigation properties. As IdentityUser does not expose the required Navigation Properties such foreign keys can not be declared.

The only option in such a case would be manually editing created migrations to add foreign keys in Up() and to drop them in Down().
