### ISSUE TITLE
Feature request: Swagger - add description option

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#7732]
Like this: https://swagger.lab.fiware.org/?url=https://raw.githubusercontent.com/Fiware/specifications/master/OpenAPI/ngsiv2/ngsiv2-openapi.json

**Comment by maliming** [comment]
@realLiangshiwei What do you think?

**Comment by leonkosak** [comment]
https://stackoverflow.com/a/52958904

This should be still viable.

**Comment by realLiangshiwei** [comment]
You can do it easily.  I think we don't need to add it.

![image](https://user-images.githubusercontent.com/16813853/108675826-46acce00-7522-11eb-9e92-c911bb13ab8d.png)

![image](https://user-images.githubusercontent.com/16813853/108675852-50363600-7522-11eb-8b38-7bf79fe4d6ab.png)

![image](https://user-images.githubusercontent.com/16813853/108675901-5e845200-7522-11eb-9792-e6c53c99c84c.png)
