### ISSUE TITLE
Auto select all scopes by default on swagger authorization

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#7734]
When we have many scopes, it will be tedious to select the scopes manually. Instead, can we make all selected by default?

![image](https://user-images.githubusercontent.com/1210527/107952143-6e43e980-6faa-11eb-8761-d54c944b9e37.png)

**Comment by maliming** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/c6bf9a266cc31140f4af2c786e92185eee16029a
