### ISSUE TITLE
Apply Multi-Tenancy for special service

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#776]
Is it possible? If we try to configure a service host (e.x ProductManager service) as multi-tenant then whats happen to our user authorization?

Is there any plan for implanting OrganizationUnit?

**Comment by hitaspdotnet** [comment]
@kharazian dorud bar shoma. Man daram ruye ye project kar mikonam ke ye bakhshesh nopCommerce hastesh. Dust dari kenar ham kar konim? Age moshtagh hasti ye pm tu telegram behem bede. Be hamin ID @hitaspdotnet

**Comment by hikalkan** [comment]
>Is it possible? If we try to configure a service host (e.x ProductManager service) as multi-tenant then whats happen to our user authorization?

Identity module supports multi-tenancy. Any service can implement multi-tenancy. Once user authenticates, the authentication ticket (access_code) will contain the TenantId and the multi-tenancy compatible service can get the tenantid from claims.

[MicroserviceDemo](https://github.com/abpframework/abp/tree/master/samples/MicroserviceDemo) example will include multi-tenancy, but not finished yet.

>Is there any plan for implanting OrganizationUnit?

Will be implemented eventually but it has a low priority. If it is essential for you, I suggest you to implement it for your own solution.
