### ISSUE TITLE
api with 404 error

### ISSUE THREAD

**Issue by ruby0602** [abpframework/abp#7762]
route had been added in controller of http.api, http.host and identityserver loaded successfully, but still have 404 error

    [RemoteService]
    [Route("userLogin/secret")]
    public abstract class UsersAuthNController : AbpController, ICMSApiUserService
    {
        
        private readonly ICMSApiUserService _CMSApiUserService;

        public UsersAuthNController(ICMSApiUserService CMSApiUserService)
        {
            _CMSApiUserService = CMSApiUserService;
        }

        [HttpGet]
        [AbpValidateAntiForgeryToken]
        public Task<ListResultDto<UserDto>> GetListAsync()
        {
            return _CMSApiUserService.GetListAsync();
        }
    }

GET https://localhost:44397/api/userLogin/secret 404

**Comment by enisn** [comment]
Hi @ruby0602 

I'm trying reproduce now,
By the way, do you see anything in your logs? It might help to find problem. 

> By default, you can find it under `/Logs` folder

**Comment by ruby0602** [comment]
hi @enisn, this is message in the log of identityserver
2021-02-18 18:02:13.527 +08:00 [DBG] CORS request made for path: /api/userLogin/secret from origin: http://localhost:4200 but was ignored because path was not for an allowed IdentityServer CORS endpoint
2021-02-18 18:02:13.527 +08:00 [INF] No CORS policy found for the specified request.

**Comment by xsoutline** [comment]
I have the same problem.How to solve that?
