### ISSUE TITLE
Update jQuery version to 3.5.1

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#7765]
Vulnerable JS Library.
Security alert on jQuery version.
![image](https://user-images.githubusercontent.com/9526587/108238567-21067a00-715a-11eb-8a64-1356902ef6be.png)
https://jquery.com/download/

this may effect the TuiEditor markdown editor. First solve the issues with TuiEditor then update jQuery.

**Comment by maliming** [comment]
jQuery 3.5.x+ breaks tui-editor. https://github.com/volosoft/volo/pull/1859

**Comment by enisn** [comment]
And https://github.com/volosoft/volo/issues/4964

**Comment by enisn** [comment]
It's not blocked anymore with #7954 

fyi @ebicoglu , @maliming

**Comment by leonkosak** [comment]
v3.6.0?

**Comment by ebicoglu** [comment]
yes, we can update it to `v3.6.0`
