### ISSUE TITLE
Dynamic API Client Authentication

### ISSUE THREAD

**Issue by mkacal** [abpframework/abp#777]
I looked at the BookStore example. But there was no authorization in the ConsoleApiClient. How do I authorize the user with ApiClient?

**Comment by hikalkan** [comment]
https://github.com/abpframework/abp/tree/master/samples/MicroserviceDemo demonstrates it, however not documented yet.

**Comment by hikalkan** [comment]
Documentation is in progress - https://abp.io/documents/abp/latest/Samples/Microservice-Demo
