### ISSUE TITLE
Feature - Docs - Create a "Recent changes" Page

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#7770]
Hi,

the "Upd" indication on the navigation is great, but in large documentations a dedicated page with a timeline of changes would be great for end-users. I am thinking about something like Wikipedias [`Recent changes`-site](https://en.wikipedia.org/wiki/Special:RecentChanges).

If you like this feature, I could contribute a PR to implement this feature.

**Comment by ebicoglu** [comment]
for GitHub integration that works but if "File-System" is being used as a source it will not work as there's no history.
I think it'd be a good feature. 
here's where this UPD comes https://github.com/abpframework/abp/blob/dev/modules/docs/src/Volo.Docs.Web/Areas/Documents/TagHelpers/TreeTagHelper.cs#L138

you also need to add "NEW" docs to the recent changes.
I don't think we keep track the DELETED ones. 

Awaiting your PR

**Comment by NecatiMeral** [comment]
Hi,

for the GitHub integration, the regular git history could be used.
For a project which is using the File-System-Source, the File-System's timestamps could be used (even if they're unaccurate on Linux environments).
