### ISSUE TITLE
Multiple GUI options for applications and modules

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#7774]
Would be possible to select (specify) multiple GUI options for application and module template.

Example:
Having MVC and Blazor projects as side-by-side projects in solutions would speed-up transition from one gui technology to another (because there is mo copy/paste backend code to new VS solution wiht different GUI project).

**Comment by ebicoglu** [comment]
I don't think it's a usual use-case.
But for your case, create 2 solutions with the same name.
Then copy one UI to another solution.
