### ISSUE TITLE
RepositoryAsyncExtensions Cannot access a disposed context instance

### ISSUE THREAD

**Issue by 2501272126** [abpframework/abp#7775]
abp 4.2.1; .net 5.0; ef core; mysql
my code like this:

        [UnitOfWork]
        public async Task HandleEventAsync(EntityCreatedEventData<MyObject> eventData) {
            var count1 = await _terminalRepository.GetCountAsync();
            var count = await _terminalRepository.CountAsync();
        }

when i use ILocalEventHandler<EntityCreatedEventData<MyObject>>
the GetCountAsync() from IReadOnlyBasicRepository<TEntity> is successful execute,
but the CountAsync() from RepositoryAsyncExtensions throw a exception the context disposed
i test all method of RepositoryAsyncExtensions in here, all throw the exception, the base method is ok;
and the IAsyncQueryableExecuter method also have this problem.
where am i wrong?

**Comment by maliming** [comment]
Try to make method **virtual**.
```cs
[UnitOfWork]
public virtual async Task HandleEventAsync(EntityCreatedEventData<MyObject> eventData) {
    var count1 = await _terminalRepository.GetCountAsync();
    var count = await _terminalRepository.CountAsync();
}
```

**Comment by 2501272126** [comment]
thank you!!!
my negligence.

If you perform database operations and use the repositories inside the event handler, you may need to create a unit of work, because some repository methods need to work inside an active unit of work. Make the handle method virtual and add a [UnitOfWork] attribute for the method, or manually use the IUnitOfWorkManager to create a unit of work scope.
