### ISSUE TITLE
Localize text in project "BasicTheme"

### ISSUE THREAD

**Issue by pointlevel** [abpframework/abp#7782]
Hello!

I have downloaded and included the project "Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme" as described here: https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b

Inside the file Themes/Basic/LoginDisplay.Razor there is a few texts that is not localized. How can i achieve that. Really tried to find answers but cant find anything. This closed issue starts with the same problem, but i could not find a solution? #7280

**Comment by realLiangshiwei** [comment]
Please read [locallization](https://docs.abp.io/en/abp/latest/Localization) document first.

Try

```csharp
........
@inject IStringLocalizer<AbpUiResource> L
....

<NotAuthorized>
     <a class="nav-link" href="authentication/login">@L["Login"]</a>
</NotAuthorized>
```
