### ISSUE TITLE
ABP Framework API consumed by a WinForm application

### ISSUE THREAD

**Issue by wzhijiew** [abpframework/abp#7785]
### Problem

Since our old ERP solution contains so many WinForm applications for import data from and export data to other platforms, when we planned to migrate the old solution to new one using ABP framework, we have make sure the new WinForm work properly with the new ABP Framework API.

### Request

How to create a Dependency Injection WinForm to directly reference and use *.HttpApi.Client project, rather than manually write new code to *.HttpApi.Host

**Comment by ebicoglu** [comment]
create a new ABP solution and you'll see that there's a WFP project 
this is a sample to show you how to use ABP libs in a 3rd party client.
https://github.com/abpframework/abp/tree/dev/templates/wpf


you can also check out the ConsoleTestApp which uses WebAPIs from a console application
https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/test/MyCompanyName.MyProjectName.HttpApi.Client.ConsoleTestApp
