### ISSUE TITLE
AbpException: No policy defined to get/set permissions for the provider ''. Use PermissionManagementOptions to map the policy.

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#779]
This error gets thrown when trying to bring up the roles permissions in version .13.  It worked in version .12.
`AbpException: No policy defined to get/set permissions for the provider ''. Use PermissionManagementOptions to map the policy.`

**Comment by djlaney3** [comment]
I was able to solve this by adding a reference to nuget package Volo.Abp.PermissionManagement.Domain.Identity.  And then adding the `DependsOn(typeof(AbpPermissionManagementDomainIdentityModule))` to my main module.

**Comment by xyfy** [comment]
I got the same error ,but I had the module dependson already 

can you let me know what is your  `main module`?
