### ISSUE TITLE
How can I add  menu item  in ProfileManagement

### ISSUE THREAD

**Issue by roupijiaojiaobao** [abpframework/abp#7792]
Hi everyone!
I would like to add another new module here please, how do I do that?
![微信截图_20210221015822](https://user-images.githubusercontent.com/64553587/108618366-82914780-73eb-11eb-9004-e6cdc73ad766.png)

**Comment by maliming** [comment]
Please check the source code.

https://github.com/abpframework/abp/tree/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Components/ProfileManagementGroup
