### ISSUE TITLE
Component Replacement and ABP From Extensions causes NullInjectorError in abp in Angular

### ISSUE THREAD

**Issue by hemaltandel1** [abpframework/abp#7794]
ABP Version 4.2
Angular

![image](https://user-images.githubusercontent.com/22088585/108622541-7ca95f80-7407-11eb-9d2b-278fbce65630.png)

Replaced "TenantManagement.TenantsComponent" it with new control by following https://docs.abp.io/en/abp/latest/UI/Angular/Component-Replacement and use "abp-extensible-form" for "#tenantModalTemplate" same as it's being used on original "TenantComponent". When click on Create "New Tenant"  throws above error. 

I have also had error with Page Toolbar Extension but able to resolved as suggested at #6940

**Comment by maliming** [comment]
Maybe duplicate with #7786

**Comment by mehmet-erim** [comment]
Hi @johnmay1 

See the below document to learn how to use extension components with a replaceable component:
https://docs.abp.io/en/abp/latest/UI/Angular/How-Replaceable-Components-Work-with-Extensions

**Comment by hemaltandel1** [comment]
> Hi @johnmay1
> 
> See the below document to learn how to use extension components with a replaceable component:
> https://docs.abp.io/en/abp/latest/UI/Angular/How-Replaceable-Components-Work-with-Extensions

@mehmet-erim yes, it's resolved the issue. Thank you.
