### ISSUE TITLE
How can I use Newtonsoft for default serialization?

### ISSUE THREAD

**Issue by cinaradem** [abpframework/abp#7795]
How can I use newtonsoft for default serialization?
the methods below do not work.
  services.AddControllers (). AddNewtonsoftJson (options =>
                 options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);
             services.AddMvc ()
                 .AddNewtonsoftJson (
                     options =>
                     {
                         options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                     });

**Comment by maliming** [comment]
See https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0#always-use-the-newtonsoft-json
