### ISSUE TITLE
CMS Kit - GetBySlugAsync method inconsistent behaviors

### ISSUE THREAD

**Issue by ilkayilknur** [abpframework/abp#7803]
There is a `GetBySlugAsync` method inside `BlogPost` repositories. In the EF Core implementation, this method throws an exception if the record is not found. However, the Mongo DB implementation does not throw. Throwing an exception shouldn't be the job of the repositories. We need to move the checking and exception throwing mechanism to the domain layer.

**Comment by enisn** [comment]
It's already fixed while refactoring
