### ISSUE TITLE
Is there documentation for SignalR with Angular?

### ISSUE THREAD

**Issue by idreeshaddad** [abpframework/abp#7809]
Hello there,

I've read [Real-Time Messaging In A Distributed Architecture Using ABP, SignalR & RabbitMQ](https://volosoft.com/blog/RealTime-Messaging-Distributed-Architecture-Abp-SingalR-RabbitMQ) and was wondering if there is documentation for when the client app is Angular?

I'm a little bit confused with where to put what and that soft of things.

**Comment by kishoresahas** [comment]
https://docs.abp.io/en/abp/latest/SignalR-Integration

**Comment by idreeshaddad** [comment]
Thank you @kishoresahas 
Yes I've seen it. But it's not near clear enough. I suggest writing a thorough blog post or a YouTube video, and an Angular Demo app just like you've done https://github.com/abpframework/abp-samples/tree/master/SignalRDemo

Thank you again :)

**Comment by idreeshaddad** [comment]
I'm sorry for saying this, but having gone through the [SignalRDemo](https://github.com/abpframework/abp-samples/tree/master/SignalRDemo); it's very primitive and it explains so little.

Don't get me wrong Abp is really great; but the promotional material (be it documentation, blogging, and videos) IMO doesn't do it justice.

Maybe do more social exposure, do more technical evangelism of sorts?

**Comment by kishoresahas** [comment]
Related #7591
