### ISSUE TITLE
how to configure a ssl certificate in production(like that nginx uses)?

### ISSUE THREAD

**Issue by LeiYangGH** [abpframework/abp#7820]
Didn't see anywhere in docs or samples. is it possible to specify in appsettings.json?

**Comment by realLiangshiwei** [comment]
It has nothing to do with ABP, you should check the web server(like Nginx, IIS) document.

**Comment by LeiYangGH** [comment]
I'm not using nginx(or reverse proxy) to serve abp application, i mean i want to configure ssl certificate(which nginx uses in the same centos server, and maybe convert to some file format that asp.net core supports).

by default abp only configures localhost cert, and it is invalid in production environment.

**Comment by LeiYangGH** [comment]
@realLiangshiwei  can you check my comments again? you close so fast.
