### ISSUE TITLE
default mvc template reports 'PasswordResetLinkSent' but no mail is received

### ISSUE THREAD

**Issue by LeiYangGH** [abpframework/abp#7839]
Steps:
1. install vbp cli
2. create new project using default options
3. uploaded to my test server(https://leiyang.icu:5001) and register a user using my mail 675686066@qq.com(put here only if that matters)
4. Try reset password function and it reports reset link sent to mail(https://leiyang.icu:5001/Account/PasswordResetLinkSent).
5. Check mail, no new mail. repeat several times but same issue.

Expected behaviour:
Either report send fail because invalid email configuration(most probably), or actually send a mail.

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp-samples/tree/master/EmailSendDemo and https://docs.abp.io/en/abp/latest/Emailing#nullemailsender
