### ISSUE TITLE
abp suite solution Waiting for localhost 

### ISSUE THREAD

**Issue by profitp** [abpframework/abp#7853]
ver: 4.2.1
User Interface MVC
EF Core MSSQL
* Steps needed to **reproduce** the problem.
1. Run abp suite
2. Create a new solution
3. Check Public web site
4. Add Entity (save, generate, etc)
5. Open VS
6. Start debug
7. Waiting for localhost over 10 minutes <========== IT's PROBLEM

**Comment by Moustafa20** [comment]
i have the same problem

**Comment by maliming** [comment]
hi @profitp  @Moustafa20  

Please discuss it on https://support.abp.io/QA/Questions/807/Bugs--Issues-v42X.
