### ISSUE TITLE
Error occurred on DB migration step: MSBUILD

### ISSUE THREAD

**Issue by Domitnator** [abpframework/abp#7863]
ABP version: 4.2.1

Steps to reproduce:

1. abp new CustomerX -t app-pro --create-solution-folder --preview --output-folder p:\development\
2. abp new CustomerX.APIY -t module-pro --preview --create-solution-folder --output-folder p:\development\CustomerX
modules --no-ui

I then added the "CustomerX.ApiY" projects necessary to the solution. Because the API has no dependency on a database (it is used to query a thirdparty api) I removed everything which is related to databases (removed the nuget packages, and all the code related).

So this gives me this solution:

![image](https://user-images.githubusercontent.com/13468638/109181082-d5705380-778b-11eb-8732-23d9b88736be.png)

And this is the HostModule for the (httpApi.Host) module:

![image](https://user-images.githubusercontent.com/13468638/109187581-52063080-7792-11eb-9046-9353ea3d4e9b.png)

I then run the Suite to add an entity but it gives me this error when i click : Save and Generate:

![image](https://user-images.githubusercontent.com/13468638/109181368-22542a00-778c-11eb-99e0-1e419762e5eb.png)

"Error occurred on DB migration step: MSBUILD : error MSB1009: Project file does not exist. Switch: ../CustomerX.HttpApi.Host Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option."

I think it is still trying the run the migrations for the CustomerX.ApiY module?

Is there a way to fix this?

**Comment by ebicoglu** [comment]
I'm sorry but this repository for open-source ABP Framework issues. This question is related to ABP Suite which is not related to this repository. I'm closing this. You can ask it on https://support.abp.io or on https://stackoverflow.com/questions/tagged/abp

**Comment by Domitnator** [comment]
@ebicoglu Thanks for pointing this out! I opened an issue on support.abp.io.
