### ISSUE TITLE
Clean Host Project When is using Angular

### ISSUE THREAD

**Issue by jaider** [abpframework/abp#7878]
### Issue

After download a ABP Angular solution, I see there are so many useless "frontend" libraries in the Host project (see screenshot). This Host project should be entirely backend and I do not understand why need those libraries.

* **ABP Framework version**: 4.2.1
* **User Interface** Angular

* Screenshot:
![image](https://user-images.githubusercontent.com/1471688/109438894-d817b680-79e0-11eb-82f1-a83a7ad9939f.png)

**Comment by maliming** [comment]
The Host project has some razor pages(`account web` & `identity server web` modules). so It needs these libraries.
