### ISSUE TITLE
abp cli automate add module dependencies

### ISSUE THREAD

**Issue by LFDCC** [abpframework/abp#7901]
I have a module project that has already been developed locally
It is too cumbersome to add these module dependencies manually
How to automate adding a dependency to a solution, such as [dependsOn (...)]
I tried using this command "abp add-module ProductManagement --new --add-to-solution-file", which automatically adds dependencies, but creates a new module project that does not include the host project,This is not what I want because my module project already exists

**Comment by maliming** [comment]
The `add-module` command only supports modules of abp.
