### ISSUE TITLE
Link Accounts like in aspnetzero

### ISSUE THREAD

**Issue by tvddev** [abpframework/abp#7902]
v4.2.1
Blazor
EF Core

Like in ASPNetzero create an ability to link accounts so a tenant user can log into their account eg an Advisor working with multiple clients), and then jump to another account (their clients account) that they have been given permission to access/linked to.

**Comment by maliming** [comment]
This feature available on the Pro module.

![image](https://user-images.githubusercontent.com/6908465/109582109-85e9a900-7b38-11eb-8f9e-a4050979a014.png)

https://docs.abp.io/en/commercial/latest/abp-framework-vs-abp-commercial

**Comment by tvddev** [comment]
https://support.abp.io/QA/Questions/852/Account-Linking-issue - this should be updated too.

**Comment by diennttlu** [comment]
I'm using the Commercial version. How can I disable: Account Linking, Two Factor Authentication, User Profile Picture??

**Comment by maliming** [comment]
@diennttlu Please discuss Commercial  on https://support.abp.io/

**Comment by diennttlu** [comment]
@maliming  https://support.abp.io/QA/Questions/3033/How-to-disable-some-features-of-the-Account-Module
