### ISSUE TITLE
Unique username to link to Tenant at login

### ISSUE THREAD

**Issue by tvddev** [abpframework/abp#7903]
v4.2.1
Blazor
EF Core

Can we have a setting "Use Login Name to set Tenant".

- This would be system wide so the username must be unique across all tenants and host, eg email address as username.
- There would be appropriate "username must be unique" warning if someone tries to setup a user with the same username.
- When the user logs in they would automatically login to their tenant.
- The tenant details would be set for this session as if the user had selected their tenant at login.
-

**Comment by maliming** [comment]
hi

I think you can implement it yourself, but this requires querying in all tenant databases when tenants use an independent database.

**Comment by tvddev** [comment]
We only have a single multi-tenant database, so that part is easy.

What do we then need to do to set the tenant so all other tenant specific functions work?

**Comment by dinhduongha** [comment]
Similar this feature: https://docs.aspnetzero.com/en/aspnet-core-angular/latest/Core-Angular-Sign-In-Without-Specifying-Tenant

**Comment by tvddev** [comment]
@dinhduongha - Yes except we are using Blazor and ABP framework is completely different. 

It is a basic SaaS feature requirement, so would be much better having this option available as part of the base template.

@maliming - OK, we can manage the unique user side, but can you tell us the best process for then setting the Tenant?

**Comment by mtozlu** [comment]
You can disable `IMultiTenant` filter either in your appservice or your custom repository to look for all users regardless of TenantId column.

Check here:
https://docs.abp.io/en/abp/latest/Data-Filtering#idatafilter-service-enable-disable-data-filters

**Comment by justinpenguin45** [comment]
Why was this closed?
