### ISSUE TITLE
Support for language resources to be saved to a database

### ISSUE THREAD

**Issue by yerz** [abpframework/abp#7909]
Language resources need to be saved to the database. When reading a resource, it is also read in DB or Redis. 
how should I do it?  Not locally

![image](https://user-images.githubusercontent.com/30039842/109623890-9588e200-7b78-11eb-83fb-f9be107cac56.png)

 
Can you give me your opinion? There is no extended description about resources in the official document!

thanks;

**Comment by realLiangshiwei** [comment]
You can implement the [`ILocalizationResourceContributor`](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Localization/Volo/Abp/Localization/ILocalizationResourceContributor.cs) interface to read localized values from anywhere
