### ISSUE TITLE
Feature Request - Nullable User profile picture ID | URL in shared UserData 

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#792]
@hikalkan Hi,
Sir, If ProfilePicture is not a part of IUserData/ICurrentUser/IdentityUserAgr where we can implement this as best practice or whats your suggestion for us?

**Comment by hikalkan** [comment]
In your application, you may need much more properties for users. In ABP's modular design, we suggest you to create your own `AppUser` entity with the properties you need. If you want to create a monolithic application with a single database, you can map your entity to the same table of of the Identity module (AbpUsers) and add your additional properties (as nullable). You will also have your own dbcontext.
If you are creating a microservice solution where you have a different db for the identity service, you will register to events to update your db when a user has been updated ([example](https://github.com/abpframework/abp/blob/master/modules/blogging/src/Volo.Blogging.Domain/Volo/Blogging/Users/BlogUserSynchronizer.cs#L10)).

In your application, you use your own entity, don't use IdentityUser entity.

**Comment by hitaspdotnet** [comment]
@hikalkan Thanks for fast reply!
Sir you absolutely right. I haven't application yet. I'm working or popular modules for ABP. Forums, Catalog, HelpDesk, Themes, and more.
I'm working on Material Kit theme which we had in original ABP.
I want to add user profile picture in navbar. In this scenario and other like this where we develop our services with shadows some properties are important. Can you hint me on this please?

**Comment by hitaspdotnet** [comment]
I hate to cleaning problem instead finding solution. But, I try to use empty or sample image for now and looking for future with right solution 😄
