### ISSUE TITLE
ABP return 500 instead of 401 status code (Swagger/Postman)

### ISSUE THREAD

**Issue by muhammedshaaban7** [abpframework/abp#7924]
ABP Version: 3.2.

when calling API in postman or swagger return 500 instead of 401 and log in DB as 401 in the test, pre, and production environment but in localhost working fine, any support appreciated.

Thanks

**Comment by real-zony** [comment]
Hi @muhammedshaaban7 ,
Is this issue related to https://github.com/abpframework/abp/issues/4560? Can you provide a demo project?

**Comment by muhammedshaaban7** [comment]
Really i don't know, but in general this happens in staging environment not in localhost unfortunately no demo available now. Any method with authorize attribute return 500 instead of 401 and in abpauditlogs throw 401

**Comment by maliming** [comment]
> when calling API in postman or swagger return 500 

Please check your application logs.

**Comment by muhammedshaaban7** [comment]
@maliming I checked app logs with status code 401 in DB but a response in swagger or  postman 500 instead of 401

**Comment by maliming** [comment]
@muhammedshaaban7 

* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
