### ISSUE TITLE
Log is not work with wpf after ui displayed

### ISSUE THREAD

**Issue by seayxu** [abpframework/abp#7925]
In my wpf app,log is not work.

abp version: 3.3.2

sample code is [here](https://github.com/seayxu/AbpWpfSample).

**Comment by realLiangshiwei** [comment]
We have WPF template :　https://github.com/abpframework/abp/tree/dev/templates/wpf

**Comment by seayxu** [comment]
my app is from this template. @realLiangshiwei

**Comment by realLiangshiwei** [comment]
![image](https://user-images.githubusercontent.com/16813853/109813802-c8120800-7c68-11eb-9f6b-cd89b1b04735.png)

**Comment by seayxu** [comment]
After ui display,log not work,you can run my [demo](https://github.com/seayxu/AbpWpfSample) .

**Comment by seayxu** [comment]
@realLiangshiwei logging nothing after ui displayed.

**Comment by rqx110** [comment]
@realLiangshiwei Have tried code from https://github.com/abpframework/abp/tree/dev/templates/wpf

found:

![image](https://user-images.githubusercontent.com/1829209/109905900-7dc96f00-7cda-11eb-8aae-43d095b6241e.png)

**Comment by seayxu** [comment]
> @realLiangshiwei Have tried code from https://github.com/abpframework/abp/tree/dev/templates/wpf
> 
> found:
> 
> ![image](https://user-images.githubusercontent.com/1829209/109905900-7dc96f00-7cda-11eb-8aae-43d095b6241e.png)

yeah,this is my problem @realLiangshiwei

**Comment by realLiangshiwei** [comment]
I will check it out, thanks for reporting @seayxu
