### ISSUE TITLE
Host side, login as a tenant/user

### ISSUE THREAD

**Issue by tvddev** [abpframework/abp#7928]
V4.2.1
Blazor

In ASPNetZero when you log in on the Host side, you can select an option from the tenant list action button to "login as this tenant" and then select the user you want to emulate.

This is hugely beneficial for support and understanding user perspective.

**Comment by maliming** [comment]
hi

This may only be available for the abp commercial. It is already in the roadmap. : )

**Comment by tvddev** [comment]
@maliming - That's fine we have paid for commercial. Where is it on the roadmap?

**Comment by maliming** [comment]
I will info you when it's available, Please follow this,

https://docs.abp.io/en/commercial/latest/road-map
https://docs.abp.io/en/commercial/latest/release-notes

**Comment by tvddev** [comment]
@maliming - That "roadmap" hasn't been updated for months... The Github release schedule is perfect, but are you now saying it's not accurate?

**Comment by maliming** [comment]
hi @tvddev 

We will update the roadmap. Thanks.

**Comment by tvddev** [comment]
@maliming can you also confirm if github version 4.2 patch has been released and is v4.2.1?

**Comment by maliming** [comment]
Yes. the latest version is **4.2.1**.

https://github.com/abpframework/abp/releases
https://www.nuget.org/packages/Volo.Abp.Core/
