### ISSUE TITLE
Abp Suite Generated Datatable Row Action Menu Problem

### ISSUE THREAD

**Issue by wzhijiew** [abpframework/abp#7929]
### My environment:

* **Abp framework version:** 4.2.1
* **Abp suite version:** 4.2.1
* **User Interface type:** Blazor
* **Database provider:** EF Core, SQL Server

### Problem

**This is normal action menu**
![Fine](https://user-images.githubusercontent.com/39178962/109898693-9e3ffc00-7ccf-11eb-9530-6708844fc5a0.jpg)

**This is the problem action menu**
bottom part of the menu is blocked and the scollbar appears, I have to scroll down to see and click the bottom action button 
![Problem](https://user-images.githubusercontent.com/39178962/109898712-a5670a00-7ccf-11eb-8d24-b3bef5312515.jpg)
![Problem2](https://user-images.githubusercontent.com/39178962/109900132-d0525d80-7cd1-11eb-8d7a-66db2bf0c8d2.jpg)

**Comment by maliming** [comment]
Please discuss abp commercial in support website.
https://support.abp.io/QA/Questions/972/Blazor-UI-Action-menu-not-showed-all
