### ISSUE TITLE
Introduce ISettingProvider to separate setting management from obtaining setting values

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#793]
ISettingManager will be moved to the setting-management module.

`SettingManager` properties in the base classes (like ApplicationService) will be replaced by `SettingProvider`. This can be a breaking change for existing applications.

**Comment by hitaspdotnet** [comment]
@yekalkan Hi sir,
Account module build failed.

**Comment by yekalkan** [comment]
@hitaspdotnet thanks you.

**Comment by jee-a** [comment]
@maliming : ISettingManager  do not sync method but AbpIdentityOptionsFactory use sync method-> when i run jmeter to stress test -> the system is error. How to add sync method.

![image](https://user-images.githubusercontent.com/87168297/156113879-cb156c17-8d18-40b2-8118-a4a7a3835ed4.png)

**Comment by maliming** [comment]
Please create a new issue.
