### ISSUE TITLE
Minor Bug Report - ABP suite generation Issue

### ISSUE THREAD

**Issue by wgodfrey-pernix** [abpframework/abp#7951]
### Bug Report

**Version:** ABP Suite 4.2.1
**User Interface:** MVC
**Database Version:** EF Core
**Javascript Alert:** DataTables warning: table id= ******Table - Requested unknown parameter '******.uOM' for row 0, column 5. For more information about this error, please see http://datatables.net/tn/4
**Steps needed to reproduce the problem**
1. Create an entity that has a property the has all capital letters (UOM for unit of measure)
2. Generate the Entity including the MVC UI
3. Start a debug instance
4. Click on the tab that contains the new entity
5. This alert should pop up

The reason this occurs is that the variable in the datatable gets generated as "******.uOM" whereas the actual value in the object is "******.uom". To fix you simply change the variable in the dataTable to  "******.uom"

Not a neck breaking bug but ever so slightly annoying

**Comment by maliming** [comment]
hi

Please follow this question on the support website.

https://support.abp.io/QA/Questions/1000/Minor-Bug-Report---ABP-suite-generation-Issue
