### ISSUE TITLE
Stuck in The Login Page

### ISSUE THREAD

**Issue by YoussefSalameh** [abpframework/abp#7959]
Dear @maliming 

We are trying to run the IdentityServer using an IP without https
We get to the login page, we enter the username and password they authenticate correctly however when the browser redirects
it does not show me the user info; rather it shows me the login page again

![IdenityServer_Capture](https://user-images.githubusercontent.com/1358776/108983717-cf994600-7697-11eb-907a-3775ef5ca21c.PNG)

When we use the https with the ip, we get to the desired page (knowing that we fixed all the https mentions in our appsettings and in our db)
![IdenityServer_https_Capture](https://user-images.githubusercontent.com/1358776/108984099-3ae31800-7698-11eb-972d-b8678edcb782.PNG)

_Originally posted by @ZouZou in https://github.com/abpframework/abp/issues/7610#issuecomment-784959802_

**Comment by realLiangshiwei** [comment]
![image](https://user-images.githubusercontent.com/16813853/110094112-6cfe2380-7dd6-11eb-93de-e829172e16f0.png)

https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n
