### ISSUE TITLE
Datatable order fails when column name is Uri.

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#796]
I have an entity that has a property of Uri.  This column is in a datatable as the first column.  If you try to order by it in the datatable setup, it fails.   The log shows:
`[ERR] {`
`  "code": null,`
`  "message": "An internal error occurred during your request!",`
`  "details": null,`
`  "validationErrors": null`
`}`
`[ERR] '.' or '(' or string literal expected`
`'.' or '(' or string literal expected (at index 4)`
`[INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.`
The datatable order code is:
`order: [[1, "asc"]],`
and the column def is:
`{ data: "uri" }`

**Comment by hikalkan** [comment]
Interesting. Do you have an idea about the reason? Is it related to datatables library or somehow related to ABP. Also, did you see server side logs?

**Comment by djlaney3** [comment]
My previous comment has the log data.   My only thought is that datatables library, maybe uri is a reserved keyword.  I was thinking the columns might have to be escaped?  I can probably test more with datatables independent of ABP if you want.

**Comment by hikalkan** [comment]
It seems not related to ABP framework. It would be good if you have time to test separated from ABP.

**Comment by djlaney3** [comment]
I did some more testing, and I can eliminate datatables being the problem.  If I run this through swagger, passing in `uri asc` as the sort, it errors.  This must be inside the ApplySorting function.  How can I isolate that to test?  My querystring params look like this: `?SkipCount=0&MaxResultCount=10&Sorting=uri%20desc`

**Comment by djlaney3** [comment]
For a quick test, add a new column called Uri to Book entity and related dto, and the table in the Bookstore sample.  Add a book, then sort by the Uri column.

**Comment by djlaney3** [comment]
I narrowed this down to an issue in the `System.Linq.Dynamic.Core.DynamicQueryableExtensions` class.  It would be great if someone could verify this.

**Comment by LorenzoTuri** [comment]
Sorry, was there a solution for this problem? 

It's probably not something strictly related to abp, but is something that happens really lot's of times. For example also using "string" as order fails, and it's probably going to be the same with almost all reserved keywords.
Also, my case ("string") was something really easy to reproduce, and happens almost every time you create a POST route with swagger. In my case I wanted an additional POST endpoint with the same results of the GetListAsync, but with post body to have the possibility to have more complex filters and inputs... and the default value of the swagger interface is "string", so the swagger default parameters failed without even being able to return the true error... 

Maybe this solved issues can help, teoretically it's (maybe) just the parser of Linq that fails to escape reserved keywords...
https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/283

I'm not sure if you need it, but this is the part of the stacktrace relative to the last call to abp code (all the successive calls are to Linq, so you could probably escape the value before that call, or wrap it in a more understandable Exception).
![immagine](https://user-images.githubusercontent.com/9315506/161636805-823a505c-4049-4afd-be28-b63e73f79770.png)
