### ISSUE TITLE
How to resolve OrganizationUnit Filter

### ISSUE THREAD

**Issue by sgalcheung** [abpframework/abp#7966]
I have a requirement to filter data through organization structure, When I refer to the implementation of multi-tenancy, CurrentUser does not hava an organizationUnitId, and then I found that the IdentityUserOrganzationUnit has a user-organization relationship, so should I create a CurrentUserOrganizationUnit? Is there a recommended way to implement id?

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/discussions/7967
