### ISSUE TITLE
DomainTenantResolveContributor will affect other TenantResolveContributor

### ISSUE THREAD

**Issue by colinin** [abpframework/abp#7968]
ABP Framework version: 4.2.1

## When a user DomainTenantResolveContributor failed to match the tenant, may not be able to continue to perform other TenantResolveContributor

When **extractResult.isMatch = false**, TenantResolver will still conclude that the tenantIdOrName has been matched and exit the loop, thus assuming that the current request is from the host

https://github.com/abpframework/abp/blob/12d92700a0396367a7e749d662e92c167b7f260d/framework/src/Volo.Abp.AspNetCore.MultiTenancy/Volo/Abp/AspNetCore/MultiTenancy/DomainTenantResolveContributor.cs#L26-L39

https://github.com/abpframework/abp/blob/12d92700a0396367a7e749d662e92c167b7f260d/framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/TenantResolveContext.cs#L13-L16

https://github.com/abpframework/abp/blob/12d92700a0396367a7e749d662e92c167b7f260d/framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/TenantResolver.cs#L20-L44

**Comment by maliming** [comment]
I think when you use `DomainTenantResolveContributor`, it means that it can always get tenant or host from the domain.
It is second only to `CurrentUserTenantResolveContributor`. 

This is by design. of course, You can change this behavior if you need.

**Comment by colinin** [comment]
OK, I will change the behavior in application, thank you for your explanation
