### ISSUE TITLE
Feature request - Resilience and Transient fault handling

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#797]
Try/Retry or DoSomethingElse on fault is a important part of applications with remote services.

We need a handler for when a transient service was fault. It's very useful for MicroService architecture and  background jobs in monolithic apps where we need set retry forever | at fault.

The [Polly](https://github.com/App-vNext/Polly) is my suggestion which produced by .NET Foundation: 
> _Polly is a .NET resilience and transient-fault-handling library that allows developers to express policies such as Retry, Circuit Breaker, Timeout, Bulkhead Isolation, and Fallback in a fluent and thread-safe manner._

```C#
    
    if(thisTransientMethodfailed)
    {
         var retry = Polly.Policy.Handle<EmailException>()
             .WaitAndRetry(new TimeSpan[]
             {
                TimeSpan.FromSeconds(10),
                TimeSpan.FromSeconds(15),
                TimeSpan.FromSeconds(20),
             });

        retry.Execute(() => SendEmail(emailTemplate));
    }
```

**Comment by hikalkan** [comment]
Hi,

I know Polly, and yes, will use it in some points. First, we will use it for dynamic C# client proxies to call remote services.

**Comment by hikalkan** [comment]
I'm closing this issue since it is too general. We can create separated issues for particular implementations. 
See https://github.com/abpframework/abp/issues/806 for example.
