### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by willignicolas** [abpframework/abp#7971]
Hello, 

We want to move towards the commercial version. We have seen that "the Subscription and payment system for the SaaS module" is present in the roadmap. The arrival of this feature will define our transition to the commercial version. 

So we would like to have a little more details on this feature and also a delay, even approximate? 

Thank you

**Comment by ismcagdas** [comment]
Hi @willignicolas 

The subscription feature we are planning probably will be available in 2-3 months. Its base functionality will be allowing users to match their external payment system plans with ABP Commercial's Editions and will handle expiration and renewal of subscriptions. For example, when using Stripe (probably this will be the our first integration), when a user subscribes to a plan, ABP will assign that plan's edition to a user. When a subscription is paid on Stripe, ABP will extend Tenant's edition subscription locally. If subscription expires on stripe somehow, ABP will un-assign Edition from tenant.

**Comment by willignicolas** [comment]
Thanks for all this informations.
