### ISSUE TITLE
An error on IdentityOptions.SetAsync when IdentityUser is extended

### ISSUE THREAD

**Issue by ahmadalmunajjed** [abpframework/abp#7975]
* **ABP Framework version** 4.2.2
* **database provider** EF Core
* **Steps needed to reproduce**

1. Downloaded new Angular UI and Entity framework ORM not tiered project
2. Extended IdentityUser by adding EfCoreEntityExtensionMappings
3. I tried to add a new user but I got an error.
4. I replaced IdentityUserAppService with the same code locally to debug it and I found that it throws an exception on this line 
`await IdentityOptions.SetAsync();`
The exception message is: Options must be derived from the Volo.Abp.Options.AbpDynamicOptionsManager`1!

Any idea how to solve it?

Thanks in advance.

**Comment by maliming** [comment]
Is your project depends on `AbpIdentityDomainModule`?

**Comment by ahmadalmunajjed** [comment]
Yes, it's in DomainModule and I'm using the startup project. I only extended IdentityUser

Thanks

**Comment by maliming** [comment]
Can you share a project?

**Comment by ahmadalmunajjed** [comment]
Sure, here you go. 

https://github.com/AhmadAlMunajjed/abp-customization

**Comment by maliming** [comment]
The project you shared and the steps you provided don't seem to be the same.

**Comment by ahmadalmunajjed** [comment]
No @maliming , it's the same. I will mention what I did in detailed steps 
Also, I had to bring the source code of UsersAppService to my project to be able to debug it

In general, what I'm trying to do is adding new props to IdentityUser and customizing IdentityUserAppService

**Comment by ahmadalmunajjed** [comment]
**Detailed steps needed to reproduce**

- Download a new project from https://abp.io/get-started, Project type: Application, UI Framework: Angular and Database provider: Entity Framework Core, Database management system: SQLServer, Tired: false
- Add UserType enum
- Add Type property to AppUser: datatype is UserType
- Add TypeId property to AppUser: datatype is Guid?
- Add TypeId property to AppName: datatype is string
- Update EfCoreEntityExtensionMappings to add the new EF properties using ObjectExtensionManager
- Add Migration
- Update DtoExtensions


@maliming did I miss anything or this can be fixed in the next version, 

Thanks

**Comment by trickyrat** [comment]
Hi, @AhmadAlMunajjed  
I meet the same issue, did you solve this problem?

**Comment by ahmadalmunajjed** [comment]
Hi, @trickyrat Not yet. 
A new version was released a couple of days ago, don't know if the issue is fixed or not, didn't try to upgrade yet

Are you using the latest version?

**Comment by trickyrat** [comment]
Hi, @AhmadAlMunajjed 
I tried the new version, but the issue still exists.
I think the `IdentityUserCreateDto.MapExtraPropertiesTo(user)`  method does not work.

**Comment by ahmadalmunajjed** [comment]
Befoe calling MapExtraPropertiesTo, it throws an exception when calling IdentityOptions.SetAsync()

@maliming what do you think the reason?

**Comment by maliming** [comment]
> **Detailed steps needed to reproduce**
> 
> * Download a new project from https://abp.io/get-started, Project type: Application, UI Framework: Angular and Database provider: Entity Framework Core, Database management system: SQLServer, Tired: false
> * Add UserType enum
> * Add Type property to AppUser: datatype is UserType
> * Add TypeId property to AppUser: datatype is Guid?
> * Add TypeId property to AppName: datatype is string
> * Update EfCoreEntityExtensionMappings to add the new EF properties using ObjectExtensionManager
> * Add Migration
> * Update DtoExtensions
> 
> @maliming did I miss anything or this can be fixed in the next version,
> 
> Thanks

Can you share a project that applies these steps above?

**Comment by trickyrat** [comment]
@maliming here is a same project
Abp version 4.2.2
Angular UI 
App template
EF core
[sample](https://github.com/trickyrat/ngdemo)
I added extra properties in abpuser, and extended identityusercreatedto etc. When I request the /api/app/identity/users post api
, it throws `isCompany and CompantId` is required.

**Comment by trickyrat** [comment]
Reproduce steps:
1. Add extra properties in AbpUser.cs
![image](https://user-images.githubusercontent.com/19605145/114276027-71fa6680-9a57-11eb-81ea-ac62c2182419.png)

2. Add AbpUser mapping in ngdemoDbContext.cs
![image](https://user-images.githubusercontent.com/19605145/114276009-63ac4a80-9a57-11eb-8115-88ef8c5c97f9.png)

3. Add EFCore mapping in ngdemoEfCoreEntityExtensionMappings.cs
![image](https://user-images.githubusercontent.com/19605145/114276050-8fc7cb80-9a57-11eb-9fb2-604199f0c084.png)

4. Add extraproperties mapping in ngdemoDtoExtensions.cs
![image](https://user-images.githubusercontent.com/19605145/114276076-ac640380-9a57-11eb-8ce5-655b2bc5f2dc.png)
5. Migrate database
6. Call /api/app/identity/users post api with extraproperties
![image](https://user-images.githubusercontent.com/19605145/114276329-bd614480-9a58-11eb-8ee9-57758cc14e61.png)
![image](https://user-images.githubusercontent.com/19605145/114276341-cfdb7e00-9a58-11eb-9f64-27a3a5b1ec62.png)
throw same exception.
7. Exception
![image](https://user-images.githubusercontent.com/19605145/114276229-4f1c8200-9a58-11eb-979e-dcac9257396a.png)

**Comment by trickyrat** [comment]
@maliming 
Did you reproduce this issue following my steps?
