### ISSUE TITLE
How to implement phone number login

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#7978]
How to implement phone number login function to identity server in abp? Please help.

**Comment by xyfy** [comment]
implement the interface `IdentityServer4.Validation.IExtensionGrantValidator`   will be helpful

**Comment by xyfy** [comment]
And it not relation to abp,only is4

**Comment by 0andy** [comment]
I think it is related with Identity. Ids4 also call identity.
For my understand, should be:
but not test yet.

any below should be work. But need double check and verify.

1, Override OnPostAsync inherit AccountPageModel
2, Override AbpSignInManager.PasswordSignInAsync()
3, Override inherit IdentityUserManager to override PasswordSignInAsync()
4, Override IdentityUserStore.FindByNameAsync()

**Comment by xyfy** [comment]
if you want to use *cellphone&password* to login， you can  just find the user by phone ,then use the username to login

if you want to use *cellphone&validatecode* for app login,you could implement the interface `IdentityServer4.Validation.IExtensionGrantValidator`,it should be helpful when you used webapi which is stateless
