### ISSUE TITLE
Abp.cli add-module with source destroys .sln-file 

### ISSUE THREAD

**Issue by pointlevel** [abpframework/abp#7979]
Hi!

I have created a new Blazor-solution. Built it. Then i open the powershell-window in the solution folder. 
Running the command: `abp add-module Volo.TenantManagement --with-source-code --add-to-solution-file --skip-db-migrations`

After successful completion, the solution-file is corrupt with message "The selected file is not a valid solution file" in VS2019.

**Comment by yekalkan** [comment]
Hi @pointlevel 

I've run the following commands:
`abp new AdMod56372Test -u blazor`
`abp add-module Volo.TenantManagement --with-source-code --add-to-solution-file --skip-db-migrations`

and solution file is fine.

![image](https://user-images.githubusercontent.com/5793291/110450553-5c022a80-80d4-11eb-8f89-9435fbe88655.png)

If you can provide any other steps to reproduce the problem, re-open this issue.

**Comment by Wiblox** [comment]
I have the same bug. With add a new module.

**Comment by yekalkan** [comment]
@Wiblox Can you provide detailed steps to reproduce this issue?
