### ISSUE TITLE
Retrieve child entities from CrudAppService 

### ISSUE THREAD

**Issue by jcreek** [abpframework/abp#7980]
I'm using the latest version of ABP from abp.io and have two entities with a many-many relationship. These are: 

```cs
public class GroupDto : AuditedEntityDto<Guid>
    {
        public GroupDto()
        {
            this.Students = new HashSet<Students.StudentDto>();
        }

        public string Name { get; set; }
        public bool IsActive { get; set; } 
        public virtual ICollection<Students.StudentDto> Students { get; set; }
    }
```
and

```cs
public class StudentDto : AuditedEntityDto<Guid>
    {
        public StudentDto()
        {
            this.Groups = new HashSet<Groups.GroupDto>();
        }

        public string Name { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<Groups.GroupDto> Groups { get; set; }
    }
```
I set up the following test to check that I am retrieving the related entities, and unfortunately the `Students` property is always empty. 

```cs
public async Task Should_Get_List_Of_Groups()
        {
            //Act
            var result = await _groupAppService.GetListAsync(
                new PagedAndSortedResultRequestDto()
            );

            //Assert
            result.TotalCount.ShouldBeGreaterThan(0);
            result.Items.ShouldContain(g => g.Name == "13Ck" && g.Students.Any(s => s.Name == "Michael Studentman"));
        }
```
The same is true of the equivalent test for a `List` of `Student`s, the `Groups` property is always empty.

I found one single related answer for abp.io (which is not the same as ABP, it's a newer/different framework) https://stackoverflow.com/a/62913782/7801941 but unfortunately when I add an equivalent to my `StudentAppService` I get the error `CS1061	'IRepository<Student, Guid>' does not contain a definition for 'Include' and no accessible extension method 'Include' accepting a first argument of type 'IRepository<Student, Guid>' could be found (are you missing a using directive or an assembly reference?)`

The code for this is below, and the error is being thrown on the line that begins `.Include`

```cs
public class StudentAppService :
        CrudAppService<
            Student, //The Student entity
            StudentDto, //Used to show students
            Guid, //Primary key of the student entity
            PagedAndSortedResultRequestDto, //Used for paging/sorting
            CreateUpdateStudentDto>, //Used to create/update a student
        IStudentAppService //implement the IStudentAppService
    {
        private readonly IRepository<Students.Student, Guid> _studentRepository;

        public StudentAppService(IRepository<Student, Guid> repository)
            : base(repository)
        {
            _studentRepository = repository;
        }

        protected override IQueryable<Student> CreateFilteredQuery(PagedAndSortedResultRequestDto input)
        {
            return _studentRepository
                 .Include(s => s.Groups);
        }
    }
```

This implements this interface

```cs
public interface IStudentAppService :
        ICrudAppService< // Defines CRUD methods
            StudentDto, // Used to show students
            Guid, // Primary key of the student entity
            PagedAndSortedResultRequestDto, // Used for paging/sorting
            CreateUpdateStudentDto> // Used to create/update a student
    {
    }
```

Can anyone shed any light on how I should be accessing the related entities using the AppServices?

**Comment by yinchang0626** [comment]
Hi:
 hope it can help you: [Entity-Framework-Core-Integration](https://docs.abp.io/en/abp/latest/Best-Practices/Entity-Framework-Core-Integration#repository-implementation)


Do override `WithDetails` method of the repository for aggregates root which have sub collections. Example:
``` csharp
public override async Task<IQueryable<IdentityUser>> WithDetailsAsync()
{
    // Uses the extension method defined above
    return (await GetQueryableAsync()).IncludeDetails();
}
```

**Comment by jcreek** [comment]
Hi @yinchang0626, 

Thank you for your reply. I'm afraid I am not sure where to put that as there is no repository defined here, as shown in my code above I only utilise the `IRepository` and pass in my class and guid. There does not seem to be anywhere within my code that I can override this, only within the abp NuGet packages I suspect. 

Are you able to provide any more specific guidance based on my implementation? 

Thanks, 

jcreek

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Entity-Framework-Core#loading-related-entities

**Comment by jcreek** [comment]
That link doesn't help - there's no mention on that page of `AppService` at all. It is apparent from that link how to access the linked entities directly via the repository, but as it is the app service that is used in the default abp.io that's what I'm looking for assistance with.

**Comment by yinchang0626** [comment]
@jcreek  Hi:
I created a repository to show about [this](https://github.com/yinchang0626/Abp-7980)
In my sample is simple one-many in `Group` and `Student` and they are `AuditedAggregateRoot`
And I create two way to do it :
`Option1` ( in master branch):   with `Custom Repository`(`IGroupRepository`,`IStudentRepository`)
```csharp
EFCore
    public partial class EfCoreGroupRepository : 
        EfCoreRepository<YC.EntityFrameworkCore.IYCDbContext,YC.Students.Group,Guid>,
        IGroupRepository
    {
        public EfCoreGroupRepository(IDbContextProvider<YC.EntityFrameworkCore.IYCDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override async Task<IQueryable<YC.Students.Group>> WithDetailsAsync()
        {
            return (await GetQueryableAsync()).IncludeDetails();
        }
    }
    public partial class EfCoreStudentRepository : 
        EfCoreRepository<YC.EntityFrameworkCore.IYCDbContext,YC.Students.Student,Guid>,
        IStudentRepository
    {
        public EfCoreStudentRepository(IDbContextProvider<YC.EntityFrameworkCore.IYCDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override async Task<IQueryable<YC.Students.Student>> WithDetailsAsync()
        {
            return (await GetQueryableAsync()).IncludeDetails();
        }
    }
 public static class StudentsQueryableExtensions //auto-generated
    {
        public static IQueryable<Student> IncludeDetails(this IQueryable<Student> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.Group);
        }
        public static IQueryable<Group> IncludeDetails(this IQueryable<Group> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
            return queryable
                .Include(x => x.Students);
        }
    }
CrudAppService:
 public partial class StudentCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<YC.Students.Student, YC.Students.Dtos.StudentWithDetailsDto, Guid, YC.Students.Dtos.StudentGetListDto, YC.Students.Dtos.StudentCreateDto, YC.Students.Dtos.StudentUpdateDto>,
        IStudentCrudAppService
    {
        private readonly IStudentRepository _repository;

        public StudentCrudAppService(IStudentRepository repository) : base(repository)
        {
            this._repository = repository;
        }

        protected override async Task<IQueryable<Student>> CreateFilteredQueryAsync(StudentGetListDto input)
        {
            return await Repository.WithDetailsAsync();           
        }
    }
```
Option2: Without Custom Repository(in branch feature/without-custom-repository)
I should add `DefaultWithDetailsFunc` for `Student` and `Group` `AuditedAggregateRoot`
```csharp
public class YCEntityFrameworkCoreModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            YCEfCoreEntityExtensionMappings.Configure();
        }

        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<YCDbContext>(options =>
            {
                /* Remove "includeAllEntities: true" to create
                 * default repositories only for aggregate roots */
                options.AddDefaultRepositories(includeAllEntities: true);

                options.Entity<Students.Student>(o => o.DefaultWithDetailsFunc = e => e.Include(x => x.Group));
                options.Entity<Students.Group>(o => o.DefaultWithDetailsFunc = e => e.Include(x => x.Students));
            });

            Configure<AbpDbContextOptions>(options =>
            {
                /* The main point to change your DBMS.
                 * See also YCMigrationsDbContextFactory for EF Core tooling. */
                options.UseSqlServer();
            });
        }
    }
```
and both option1 and option2  result are:
![image](https://user-images.githubusercontent.com/16490084/110323370-7cd46c80-804f-11eb-800f-f60c83770af4.png)
![image](https://user-images.githubusercontent.com/16490084/110323441-94abf080-804f-11eb-8d1c-eb16bdf115bb.png)

**Comment by jcreek** [comment]
Hi @yinchang0626 thank you so much for taking the time to put this together, I really appreciate it. I have spent my free time over the last two days going through this and trying everything I can to get it to work with a many-many relationship, and accessible via the AppService, rather than through a repository, as it is the AppService I'm actually using to access my data. 

I could not possibly ask more of you than you have so generously done already, but if you felt so inclined I would greatly appreciate any further guidance you can give me on how to get many-many entities accessible through the AppService. 

I have uploaded my entire source code [here](https://www.dropbox.com/s/f7hmqmf6l7cbxn5/assess.zip?dl=1), which contains several other things I've tried to get this working. In an ideal world I am trying to get the `Should_Get_List_Of_Students` and `Should_Get_List_Of_Groups` tests passing, with the Groups and Students properties on each (many to many relationship) automatically being populated with all the related entities.
