### ISSUE TITLE
How to pass __tenant as query param or header param through angular UI login button click?

### ISSUE THREAD

**Issue by mathro** [abpframework/abp#7982]
ABP Framework version: 4.2.0
User Interface: Angular
Separate identity server: yes.

I'm capable of resolving the tenant on my UI - {0}.mydomain.com then all the requests have a __tenant param, but when I click the login button of my Angular UI, the app is redirected to the endpoint identityserver.mydomain.com/Account/Login and the __tenant param on the header isn't present anymore. My need is to pass the __tenant param to identify the tenant on the identity server.

How can this be achieved? Is it through the UI? Is there another way to identify the tenant on the identity server?

**Comment by mathro** [comment]
Any ideas?

**Comment by maliming** [comment]
Move to https://support.abp.io/QA/Questions/1052/How-to-pass-tenant-as-query-param-or-header-param-through-angular-UI-login-button-click
