### ISSUE TITLE
How to use Async Operations in IIdentityUserRepository?

### ISSUE THREAD

**Issue by NetChenQian** [abpframework/abp#7987]
I want to use Async Operations to get all users whose IDs are in the specified collection from IIdentityUserRepository, but ABP does not implement the asynchronous LINQ method. What should I do？
[IAsyncQueryableExecuter](https://docs.abp.io/en/abp/latest/Repositories#option-3-iasyncqueryableexecuter) is also unavailable because IIdentityUserRepository does not provide the GetQueryableAsync method.
![image](https://user-images.githubusercontent.com/29855154/110305522-bb5e2d00-8037-11eb-84a0-2d89a30ecd15.png)

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/7402

**Comment by NetChenQian** [comment]
> See #7402

Thanks.

Can you give me an example of what you mean?

IIdentityUserRepository is not a custom IRepository,is defined in Volo.Abp.Identity module.

IIdentityUserRepository does not implement IQueryable<TEntity>, also does not provide the GetQueryableAsync method,the following method cannot be used:
```
public async Task DoItInNewWayAsync(List<Guid> userIds)
{
    //Invalid, GetQueryableAsync is not defined
    //Use GetQueryableAsync to obtain the IIdentityUserRepository first
    var queryable = await userRepository.GetQueryableAsync();

    //Then apply any standard LINQ extension method
    var query = queryable
        .Where(x => userIds.Contains(x.Id))
        .OrderBy(x => x.UserName);

    //Finally, execute the query asynchronously
    var users = await AsyncExecuter.ToListAsync(query);
}
```

**Comment by maliming** [comment]
You can inherit the `EfCoreIdentityUserRepository` class to add more methods.

**Comment by NetChenQian** [comment]
> You can inherit the `EfCoreIdentityUserRepository` class to add more methods.

Thanks, Is there any other solution?

**Comment by maliming** [comment]
This by design.

**Comment by NetChenQian** [comment]
> This by design.

Ok, thanks.
