### ISSUE TITLE
Support RTL in Blazor Project

### ISSUE THREAD

**Issue by buaziz** [abpframework/abp#8000]

**Comment by stsrki** [comment]
How would this even work? Blazor projects are using Blazorise and it is not well suited for RTL. At least in the current state. For example, let's say we take one basic example with `enum TextAlignment` which has `Left` and `Right`. By default, everything on a page is left aligned. And when we set some paragraph alignment to `TextAlignment.Right` then that one element would move to the right.

Now, what if we switch everything and enable RTL. Do we just switch left and right. That would mean our previous example would make `TextAlignment.Right` to go to the left. While it saying it is on the right. I don't think it is the right way to work like that.

I propose to rename everything from `Left` and `Right` to something like `Near` and `Far`. It makes more sense in LTR and RTL modes. But it would be a breaking change and would need to change a lot of stuff.

@hikalkan What do you think?

**Comment by stsrki** [comment]
It also seems Bootstrap RTL is only available with v5 while v4 needs external dependency to work. Bulma provider supports it from v0.9.

https://dev.to/hus_hmd/rtl-support-lands-in-bootrstrap-and-bulma-3hom

**Comment by buaziz** [comment]
@stsrki  will this be planned as currently there is no label?

having this feature or not will result in our decision to go ahead with Blazor or do the UI on Angular.

**Comment by stsrki** [comment]
Yes, I believe it will be ready. The ticket with the label is here https://github.com/abpframework/abp/issues/5517

**Comment by stsrki** [comment]
Sorry I answered the wrong ticket with the last message 😅

Now back to your question. Unfortunately, I still have no open ticket or label for RTL support. This is the first time it was requested to tell you the truth.
