### ISSUE TITLE
Help:How do I call connect/token in my application layer to get the token and return it to the client through the API

### ISSUE THREAD

**Issue by litiansky** [abpframework/abp#8003]
* **ABP Framework version** 4.2.2

I saw this #7551, should be similar to what I asked for? But I don't know how to implement it. My server project is host, so how can I call connect/token API and return it to the client?

**Comment by maliming** [comment]
>  so how can I call connect/token API and return it to the client?

You can take look at **IdentityModel**.

https://identitymodel.readthedocs.io/en/latest/client/token.html
