### ISSUE TITLE
Virtual File Middleware should be compatible with IWebHostEnvironment.WebRootFileProvider

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8006]
Instead of using a separate file provider to support the virtual file system, we will set the standard `IWebHostEnvironment.WebRootFileProvider` to support the virtual file system.

With this change, `app.UseVirtualFiles()` has been marked as `Obsolete`. Use the standard `app.UseStaticFiles()` instead.

This change makes better align with Blazor server side usage.

**Comment by xyfy** [comment]
What's the change to use `UseStaticFiles`.I got some unexcepted exception after changed it
