### ISSUE TITLE
Search in MongoDb using a extra property

### ISSUE THREAD

**Issue by douglasrg1** [abpframework/abp#8009]
I added the Cpf extra property to the IdentityUser and now I need to do a search by Cpf in MongoDb
how to do this using the IRepository<IdentityUser, Guid> _identityUserRepository.
``` c#
wait _identityUserRepository.FirstOrDefaultAsync(x => x.Cpf == input.Cpf);
```

**Comment by maliming** [comment]
> For MongoDB, it is stored as a regular field, since MongoDB naturally supports this kind of extra elements system.

You can try to customize the repository method and use the MongoDB API.

https://docs.abp.io/en/abp/latest/Entities#how-is-it-stored
