### ISSUE TITLE
Basic Theme Layout 

### ISSUE THREAD

**Issue by ThreeLambs** [abpframework/abp#8011]
The Layout of Application.cshtml 

``div#AbpContentToolbar > div. mb-2``
I have no  section ``content_toolbar`` , but  it  has height  ``mb-2`` . 
``` 
  ...
    <div class="@containerClass">
        @(await Component.InvokeAsync<PageAlertsViewComponent>())
        <div id="AbpContentToolbar">
            <div class="text-right mb-2">
                @RenderSection("content_toolbar", false)
            </div>
        </div>
      ...
    </div>
```
``` 
<div id="AbpContentToolbar">
   <div class="text-right mb-2">
   </div>
  </div> 
```

**Comment by realLiangshiwei** [comment]
I can't get your point.

**Comment by ThreeLambs** [comment]
> I can't get your point.

it has no content_toolbar content ,but occupy mb-2 height  of page. it's not good, I think.

**Comment by realLiangshiwei** [comment]
You can custom the layout page if you need. https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#layouts
