### ISSUE TITLE
Blazor Module Development, Nested Layout Usage

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#8016]
Hello,

I created project with module template blazor ui. 
Part of my app i needed to use nested layout page.

Nested layout page example

@inherits LayoutComponentBase
@layout ThemeLayout
some html
@Body

Problem is how can i define @layout ThemeLayout, because in module we can't reach root themelayout (normally)
If i not specify parent layout in nested layout its act like root layout

Do you have any advice?

**Comment by muratyuceer** [comment]
Hi @stsrki, do you have idea about that

**Comment by stsrki** [comment]
If you want to use a different layout you can just define it at the beginning of the page. 

**Example**

```
@layout UserLayout
@page "/my-account"
```

Or for example you can have multiple pages using the same layout. In that case, create a folder where all the pages will be located and add `_Imports.razor` file, and add:

```
@layout UserLayout
```

![image](https://user-images.githubusercontent.com/900302/110911827-78d87100-8313-11eb-80fb-f261041b1fc6.png)

Those are all basic Blazor rules for layouts.

**Comment by muratyuceer** [comment]
Thanks for answer,

My problem is about modules

Let's assume that you want to create UserLayout.razor in module project (its nested layout, parent layout have to be root theme layout)

```
@inherits LayoutComponentBase
@layout **What will you write here for indicate theme root layout**
@Body
```

By the way _Imports.razor not effect to nested layouts

**Comment by stsrki** [comment]
You would also write a MainLayout

That is how I always used it.

**UserLayout.razor**

```
@layout MainLayout
@inherits LayoutComponentBase

@Body
```

**Comment by muratyuceer** [comment]
But i cant accsess MainLayout from module project. Module project havent depend on root theme project.

**Comment by stsrki** [comment]
Are you sure you don't have the way to the core module? Even if you don't have it directly as a project reference, you still have it from the module of a module (etc.).

For example in my current branch it's on `Volo.Abp.AspNetCore.Components.Web.BasicTheme.Themes.Basic.MainLayout`(refactored for Blazor server).

Yours will be at `Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme.Themes.Basic.MainLayout`.

**Comment by muratyuceer** [comment]
No, i couldnt find Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme.Themes.Basic namespace in module project.
By nature module must not depend theme project its normal.

The main problem _Imports.razor (@layout) not effect to components that inherit it LayoutComponentBase. Because of that on host project i cant set it.

I have to do some somersaults like module in module just for set that.

I thought to create shared interface like IMenuContributor, IMainLayoutContributor and set it on host project (module will use it too). 

Before that i want to ask you to find out if there is an easy method of this
