### ISSUE TITLE
Blazor Application Size & Performance

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#8018]
Hello,

I publish my blazor app but first load very slowly.
For simulate i open private tab and disabled cache from network
Its download 50mb resource as seen in picture. Am i pushlish wrong? Just i use "dotnet publish" release mode
I saw in csproj file some lines
```
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
    <PublishTrimmed>false</PublishTrimmed>
```
But if i set enable them, publish not work.

![image](https://user-images.githubusercontent.com/25631692/110746887-8f68c480-824e-11eb-9fef-c7823543ad31.png)

After first load its download 730kb but 9 seconds (slow)

![image](https://user-images.githubusercontent.com/25631692/110747541-98a66100-824f-11eb-9843-f0d0d59e5158.png)

When I examined a little bit i saw 
abp/api-definition (586kb) I guess this endpoint retrieve metadata for dynamic client system. But my app growing and in future size what will be i am worried.

**To improve performance can we generate that on build time static file or embeded resource?**

same think abp/application-configuration?api-version=1.0

If there are not contain user specific data leastways can we cache them on browser insted of fetch until change?

**Comment by leonkosak** [comment]
I discussed these issues privately with Volo team (@hikalkan, @ebicoglu) in January. They know that and currently these are the limitations of wasm and Blazor wasm technology.
There is Blazor Server-Side GUI option planned for abp v4.3 release.

**Comment by muratyuceer** [comment]
> I discussed these issues privately with Volo team (@hikalkan, @ebicoglu) in January. They know that and currently these are the limitations of wasm and Blazor wasm technology.
> There is Blazor Server-Side GUI option planned for abp v4.3 release.

Okay then we will upgrade to server-side for fix problem for now.
I opened the subject to inform people and follow the developments.

But still i think for abp/api-definition and some system endpoints can make performance improvements like browser cache etc..

**Comment by stsrki** [comment]
Yes, unfortunately, little can be done for WebAssebly Blazor at this time. It's just that there is a lot of stuff to load and because of that, it is slow.

The Server-side is coming nice and it will be ready soon.

**Comment by realLiangshiwei** [comment]
follow https://github.com/abpframework/abp/issues/5517
