### ISSUE TITLE
Error on migrating database with an entity which has a navigation property to tenants

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#8019]
**Related:** 
https://support.abp.io/QA/Questions/996
https://support.abp.io/QA/Questions/1003

The following code solves the problem:
`builder.Entity<TenantConnectionString>().HasKey(lc => new {lc.TenantId, lc.Name});`

However, the auto-generated migration files are the same whether I add this code or not. You can look at the pictures below for comparison:

![image](https://user-images.githubusercontent.com/31216880/110753089-26397f00-8257-11eb-9d97-f0376b771139.png)

![image](https://user-images.githubusercontent.com/31216880/110753098-29346f80-8257-11eb-87f2-2a369f799dfa.png)

The reproduced version of the issue is below. To repeat the error, all you have to do is run DbMigrator.

[test.zip](https://github.com/abpframework/abp/files/6121317/test.zip)

**Comment by maliming** [comment]
**MigrationsDbContext** is only used for database migration.

You have created a relationship with the **Tenant** in the **Book** entity, but the **Book** entity belongs to the **DbContext**. It is used at runtime. **ConfigureSaas** is called by **MigrationsDbContext** but **DbContext** does not.

This is why `builder.Entity<TenantConnectionString>().HasKey(lc => new (lc.TenantId, lc.Name));` can solve the problem.

![image](https://user-images.githubusercontent.com/6908465/110802119-da1f2680-82b8-11eb-99a9-5567ecdbe3ce.png)
