### ISSUE TITLE
Localization problem when publish to IIS

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#802]
IIS:
![image](https://user-images.githubusercontent.com/1214546/52699537-ec7ee700-2fb0-11e9-9d25-7c31b70cbd7e.png)

LocalRun:Works fine

![image](https://user-images.githubusercontent.com/1214546/52699600-16d0a480-2fb1-11e9-8945-90b981a90a6b.png)

**Comment by maliming** [comment]
What is the version you are using?

What happens if you execute `dotnet yourApplication.dll` in the iis website directory?

**Comment by CAH-FlyChen** [comment]
I was only create from the online starter template.

**Comment by CAH-FlyChen** [comment]
the code was published by visual studio.
![image](https://user-images.githubusercontent.com/1214546/52700604-54cec800-2fb3-11e9-8840-94179ab6306c.png)

**Comment by CAH-FlyChen** [comment]
is dotnet 2.2 bug?

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/52702740-bee96c00-2fb7-11e9-9671-a218133a4ed1.png)

It seems that the localization of the current project is not working after the publish.
Not related to IIS.

**Comment by CAH-FlyChen** [comment]
i agree.

**Comment by hikalkan** [comment]
Will try that. Thanks for reporting.
