### ISSUE TITLE
Article Request : Setting up ABP without Identity server.

### ISSUE THREAD

**Issue by antosubash** [abpframework/abp#8023]
Based on this #5343 and this #7759 it should be possible but there is no guide on how to do it. it will be great if there is a community article about this.

**Comment by antosubash** [comment]
Create a youtube video on how to do this. 

Here is the video: https://www.youtube.com/watch?v=6By_lKDyTGg&ab_channel=AntoSubash

Repo: https://github.com/antosubash/AuthChange

**Comment by realLiangshiwei** [comment]
Great, we welcome your article contribution

**Comment by Uchiha-Peng** [comment]
> Create a youtube video on how to do this.
> 
> Here is the video: https://www.youtube.com/watch?v=6By_lKDyTGg&ab_channel=AntoSubash
> 
> Repo: https://github.com/antosubash/AuthChange

Thank you very much, your suggestion is effective, IdentityServer can be successfully removed, but I also want to remove multi-tenancy, what should I do?

**Comment by antosubash** [comment]
@Uchiha-Peng you don't have to remove multi-tenancy just disable it. check the docs here https://docs.abp.io/en/abp/latest/Multi-Tenancy

**Comment by Uchiha-Peng** [comment]
@antosubash  I know how to disable it, but I still don’t want to generate a database table structure related to multi-tenancy

**Comment by antosubash** [comment]
@Uchiha-Peng ok then you have to remove the `Tenant Management Module`.  but I have not done that before and I'm not sure about the implication with that. I would suggest you create a new issue or request a community article.

**Comment by antosubash** [comment]
this article is published https://community.abp.io/articles/replacing-identityserver4-with-identity-in-abp-arh0jxe1

**Comment by wallee85** [comment]
thank you for your effort,hope there will be a offical solution with this issue.

**Comment by antosubash** [comment]
@pangjianxin this is not official but works for now. https://community.abp.io/articles/replacing-identityserver4-with-identity-in-abp-arh0jxe1
