### ISSUE TITLE
Error in  Replace NavItemsComponent After Update

### ISSUE THREAD

**Issue by YoussefSalameh** [abpframework/abp#8041]
* ABP Framework version : 4.1.2
* User Interface : Angular
* Database provider : EF Core

Dear Sirs , 

After Upgrading to 4.1.2 Version I  wasn't able to replace **Nav-Items** Component like it is in the documentation noting that it was working on version 3.1.0.

languages$: Observable<ApplicationConfiguration.Language[]>;  Language is deprecated use instead LanguageInfo.
currentUser$: Observable<ApplicationConfiguration.CurrentUser>; CurrentUser is deprecated use instead CurrentUserDto.

both languages$ , currentUser$ are undefined after replacing them as above.

SetLanguage give me this error **Module '"../../../node_modules/@abp/ng.core/abp-ng.core"' has no exported member 'SetLanguage'.ts(2305)**

Please can anyone provide us with a solution ?

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0

**Comment by YoussefSalameh** [comment]
Dear @realLiangshiwei ,

Thanks for your reply I'm using the ConfigStateService now and everything is fine now.

**Comment by Ximena-con** [comment]
Hi @YoussefSalameh,

I have the same question with you **Module '"../../../node_modules/@abp/ng.core/abp-ng.core"' has no exported member 'SetLanguage'.ts** , and I tried the **ConfigStateService** you mentioned above, but I just get the language information, I want to set the language in angular, could you tell me which method you‘re going to replace the **SetLanguage**? thank you very much~

**Comment by YoussefSalameh** [comment]
Dear @Ximena-con ,

Please Follow the below Steps :
1- import { SessionStateService } from '@abp/ng.core';
2- constructor( private sessionState: SessionStateService ) { }
3- onChangeLang will be as below :
     onChangeLang(cultureName: string) {
        this.sessionState.setLanguage(cultureName);
      }

**Comment by Ximena-con** [comment]
Thanks for the detailed steps! @YoussefSalameh , it works now ！^_^
