### ISSUE TITLE
AngularUI + ABP Application deploy problems

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#8042]
ABP CLI VERSION:4.2.2
Command : 
> abp new project -t app -u angular  

update database connectionstring in migrator and api.host projects
ran datamigrator project
publish solution
host angular static files with Nginx
open browser and go localhost:4200, I got the error page

Error
![image](https://user-images.githubusercontent.com/19605145/110912668-2cab2200-834f-11eb-84f6-9a750cb5e74e.png)

angular environment config file
![image](https://user-images.githubusercontent.com/19605145/110912245-ad1d5300-834e-11eb-98dc-b927919240d5.png)

 nginx config
![image](https://user-images.githubusercontent.com/19605145/110912254-af7fad00-834e-11eb-818e-c337b4b8b6f9.png)

appsettings.json
![image](https://user-images.githubusercontent.com/19605145/110912260-b1497080-834e-11eb-8712-fd423541a66f.png)

**Comment by maliming** [comment]
hi

Please check your application logs and network requests in the browser.

**Comment by trickyrat** [comment]
network is well, and there's no any error logs. It seems like app can't get identityserver api because of https? @maliming

**Comment by maliming** [comment]
Do you check the browser's console panel?

**Comment by trickyrat** [comment]
browser's console errors
 
![image](https://user-images.githubusercontent.com/19605145/111092931-79bb0e00-8572-11eb-8df3-559122ac9150.png)

@maliming

**Comment by maliming** [comment]
Please check this endpoint and its logs.

![image](https://user-images.githubusercontent.com/6908465/111093303-85f39b00-8573-11eb-931d-870fbb30db6e.png)

**Comment by trickyrat** [comment]
this is browser's console error. it seems like a cors problem, but I configured cors settings.
![image](https://user-images.githubusercontent.com/19605145/111095659-e76a3880-8578-11eb-996b-17c4d9d35aaa.png)
![image](https://user-images.githubusercontent.com/19605145/111095665-ea652900-8578-11eb-811e-054d737b7d7a.png)
![image](https://user-images.githubusercontent.com/19605145/111095669-ec2eec80-8578-11eb-8d1e-4e7cee5d3d0a.png)
![image](https://user-images.githubusercontent.com/19605145/111095674-ee914680-8578-11eb-928c-49e9bdc51e45.png)
@maliming

**Comment by maliming** [comment]
**Please check its logs.**

**Comment by amsaighi** [comment]
I suggested to you two options : 
- Reboot Redis, 
- Accept HTTPS certification in your broswer go ( console=> network ( click in => application-configuration, and accept the certification) or ( url/api/abp/application-configuration ).

**Comment by trickyrat** [comment]
After publishing project , the `appsetting.json` will convert the port from 44378 to 5000(I can't find the 5000 port setting). So I reconfigure angular's configuration , it works.

**Comment by trickyrat** [comment]
After publishing project , the `appsetting.json` will convert the port from 44378 to 5000(I can't find the 5000 port setting). So I reconfigure angular's configuration , it works. 
thanks for your advices. @amSaighi @maliming

**Comment by huytnd** [comment]
> After publishing project , the `appsetting.json` will convert the port from 44378 to 5000(I can't find the 5000 port setting). So I reconfigure angular's configuration , it works. thanks for your advices. @amSaighi @maliming

Hi @trickyrat I got the same issue today with the latest 6.0.1 version. Where did you change on your angular app to make it work?
