### ISSUE TITLE
Auth code flow redirect_uri

### ISSUE THREAD

**Issue by duard-sf** [abpframework/abp#8045]
* ABP Framework version:
3.3.2
* User Interface type:
Angular

I am trying to set the `redirect_uri` for IdentityServer, but it seems like [getRedirectUri](https://github.com/abpframework/abp/blob/85bc35a78da8e7123686f62057d85181dad90f9a/npm/ng-packs/packages/account/src/lib/utils/auth-utils.ts#L5) is setting it to our app's root URL automatically. This prevents us from being able to navigate to a deep route from outside the app.

Therefore, I need to be able to set the `redirect_uri` to the initial requested URL so that the auth flow can properly redirect me after login or challenge.

**Comment by mehmet-erim** [comment]
Hi @duard-sf

Which auth flow (authorization code flow or resource owner password flow) are you using on your app?

Can you explain with examples what you would like to do so that I can help you better?

**Comment by duard-sf** [comment]
We're using authorization code flow.

Here's an example:

From a deep route in the app, like `/users/123`, you click a link that opens `/users/create` in a new tab. But instead of arriving at `/users/create` after your credentials are challenged, you land on the app home page.

After requesting a deep route from outside of the app (like navigating to `/users/create` from a fresh browser), I notice that a request is sent to `/connect/authorize` with a `redirect_uri` = the app root (`http://localhost:4200`).

I am aware that I can specify query parameters when using the [OAuthService](https://github.com/manfredsteyer/angular-oauth2-oidc) directly, like:
```javascript
oAuthService.initCodeFlow(null, {
  redirect_uri: location.href
});
```
And I can then see the `redirect_uri` being added to the `/connect/authorize` request. But it doesn't overwrite the original `redirect_uri` that ABP adds automatically. So there just ends up being two, and mine is ignored.

So I need to to be able to tell ABP to give the correct `redirect_uri`, i.e. `/users/create` in my example, rather than having ABP always set it to the app's root URL.

**Comment by mehmet-erim** [comment]
Actually, the `angular-oauth2-oidc` library adds the `redirect_uri` when creating the login URL. You can see this:
https://github.com/manfredsteyer/angular-oauth2-oidc/blob/master/projects/lib/src/oauth-service.ts#L1426

`@abp/ng.core` package sets the OAuth configuration in the `environment.ts` files as the library's configuration. So the library uses the `environment.oAuthConfig.redirectUri` value as `redirect_uri` parameter. If you change the `redirectUri` value, you will be faced an issue. The `redirectUri` must equal the Angular app URL. The same redirect URI is stored in the `IdentityServerClientRedirectUris` table in DB.

I found a similar issue on StackOverflow:
https://stackoverflow.com/questions/59803219/angular-deep-link-navigation-with-oidc

I think you can build your own solution by adding the `redirectUri` to the local storage while redirecting to the login. When logged in successfully, you can get the `redirectUri` from local storage and navigate the user to this URI. Then you can remove the `redirectUri` from local storage.

**Comment by duard-sf** [comment]
Thanks for your help! I followed your advice and added the `redirect_uri` to `SessionStorage` from an auth guard, and handled redirecting in the `AppComponent`. Would've liked to avoid the extra redirect, though.
