### ISSUE TITLE
Multi tenancy add to module

### ISSUE THREAD

**Issue by madschristiansen** [abpframework/abp#805]
Hi guys,

I have downloaded the sample for .net core, but I fail to add multi tenancy. 

When looking through the docs I can see it has to be added to the module. But which module?, I find module files for web, domain, application etc.

I hope someone can point me in the right directions with steps to remember to make it succeed.

Thank you

Mads

**Comment by hikalkan** [comment]
Multi-tenancy part is not documented yet. You should add `Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy` to the web layer. Then you can add [tenant-management](https://github.com/abpframework/abp/tree/master/modules/tenant-management) module to your application. I suggest you to wait for multi-tenancy a bit more, it is also not well tested yet. I will document it soon.
