### ISSUE TITLE
Hungarian culture breaks the DataTable decimal inputs

### ISSUE THREAD

**Issue by speter9701** [abpframework/abp#8050]
ABP Framework version: 4.2
User Interface type: MVC, Razor
Database provider: MongoDB

The initial seed (double) number is shown correctly by the DataTable with dot characters as decimals in both English and Hungarian language settings.
![image](https://user-images.githubusercontent.com/47381974/111051513-d96ec780-8453-11eb-86e2-2997b336aa7b.png)

When I click on the "Edit" button with Hungarian settings, the dot characters are replaced with commas as decimals in the editing window:
![image](https://user-images.githubusercontent.com/47381974/111051561-4aae7a80-8454-11eb-9c13-80984ba31e9d.png)

When I try to save without any modifications, I get the following error:
![image](https://user-images.githubusercontent.com/47381974/111051574-61ed6800-8454-11eb-9162-9ace8d987ae5.png)

I need to change the decimal character to a dot character in order to save the item:
![image](https://user-images.githubusercontent.com/47381974/111051596-81849080-8454-11eb-9646-993c139c1811.png)

But after saving, the value is lost and the saved number is zero:
![image](https://user-images.githubusercontent.com/47381974/111051612-a7aa3080-8454-11eb-83f9-0663481f91cd.png)

I have tried to add language settings to the normalizeConfiguration but it does not have any effect.
![image](https://user-images.githubusercontent.com/47381974/111051658-230be200-8455-11eb-9339-22ecd3720de2.png)

How can I fix this issue?

**Comment by maliming** [comment]
You can check this http://blog.rebuildall.net/2011/03/02/jQuery_validate_and_the_comma_decimal_separator

**Comment by totpero** [comment]
Probably the same issue https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5916

**Comment by speter9701** [comment]
I have included the following code in the first line of the Index.js and now it works. Thanks! 

`$.validator.methods.range = function (value, element, param) {
    var globalizedValue = value.replace(",", ".");
    return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
}

$.validator.methods.number = function (value, element) {
    return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
}`

Can you include this in the documentation? Seems like it's a common issue for the eastern and northern European languages.

**Comment by maliming** [comment]
This is related to NET Core https://github.com/dotnet/aspnetcore/issues/6566
