### ISSUE TITLE
How to injection http request info in ILocalEventHandler implement

### ISSUE THREAD

**Issue by xsoutline** [abpframework/abp#8054]
I need to injection http request info in ILocalEventHandler implement.

I read the source code [/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/IocEventHandlerFactory.cs](https://github.com/abpframework/abp/blob/3fcdeeeb05/framework/src/Volo.Abp.EventBus/Volo/Abp/EventBus/IocEventHandlerFactory.cs) is to create a new scope,and then can't get the  http request info from http request.It is not the same scope with http request scope?

How to do?

**Comment by maliming** [comment]
what is `http request info `?

Can you share some code to explains?

**Comment by xsoutline** [comment]
> what is `http request info `?
> 
> Can you share some code to explains?

Custom HTTP Header values.

Such as:Header key is 'ConnInfo'
`ConnInfo: RGF0YSBTb3VyY2U9LDE0MzM7SW5pdGlhbCBDYXRhbG9nPTtVc2VyIElEPTtQYXNzd29yZD0=`
I need to get the header value in ILocalEventHandler.

**Comment by maliming** [comment]
Add `ConnInfo` to the Event parameter class instead of using `http request info` .

**Comment by xsoutline** [comment]
> Add `ConnInfo` to the Event parameter class instead of using `http request info` .

I had solved by implementing custom event bus class.
