### ISSUE TITLE
Include source code of the basic theme in the startup template (MVC UI)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8055]
We see that many people want to completely customize the basic theme for their applications. This is what we expect since the basic theme is designed to be "basic", so you build your own theme based on it.

There are some (see for [mvc](https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-mvc-ui-yt9b18io) & [blazor](https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b)) community articles to demonstrate how to copy its source into your application code and freely change the basic theme. However, it still requires some additional work after project creation.

We think it will be good if we include the theme code inside the downloaded application startup template, so anyone can directly change the theme. We don't make changes frequently in the basic theme, so most of times you won't need to upgrade it.

We will add the theme code in a separate project, so it will be separated from the application code. In this way, you may reuse the theme in different applications or switch to another theme in the future easily.

If anyone still wants to use the basic theme as a package, we will continue to deploy it as a NuGet package. They can remove the project in the solution and add the basic theme package.

We may consider to make this optional if community wants it in the future.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/8057#issuecomment-803643499
