### ISSUE TITLE
Include source code of the basic theme in the startup template (Blazor UI)

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8060]
Similar to https://github.com/abpframework/abp/issues/8055 for Blazor UI

Blazor UI has two options: Server side & Webassembly, so we will have two packages in the project.

**Comment by leonkosak** [comment]
Can we expect documentation how to make transition from WebAssembly to Server-Side and vice-versa?

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/8057#issuecomment-803643499
