### ISSUE TITLE
Angular UI: Set "Manage Your Profile" URL dynamically

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#8062]
Angular UI account module will be available in v4.3. You can see the [PR](https://github.com/abpframework/abp/pull/7861).
If you add the account module to your Angular project, the "Manage Your Profile" link in the current user dropdown on the top bar will navigate to a page account module in the Angular UI account module instead of redirecting to the MVC.

**Comment by amLabib** [comment]
Hi @mehmet-erim , is there any documenation about this? how to "add account module to your Angular project"

**Comment by mehmet-erim** [comment]
Hi @amLabib,

> is there any documentation about this?

See the [account module document](https://docs.abp.io/en/abp/latest/UI/Angular/Account-Module).
