### ISSUE TITLE
SqlException: Invalid object name 'AbpSettings'

### ISSUE THREAD

**Issue by kuochaoyi** [abpframework/abp#8069]
Env: ABP framework 4.2.2, SQL Server 2019(docker) on MacOS 10.15.7

I suffer from a problem, i put detail on StackOverFlow,
[SqlException: Invalid object name 'AbpSettings'](https://stackoverflow.com/questions/66641248/sqlexception-invalid-object-name-abpsettings)  

plz, how to fixed the problem. thanks

**Comment by realLiangshiwei** [comment]
`Invalid object name 'AbpSettings'`

Please check your database. it has nothing to do with ABP.

**Comment by ugurozturk** [comment]
fixed by clean/re create migration/ build fixed my problem
https://github.com/abpframework/abp/issues/7282
