### ISSUE TITLE
How can i use AbpSettingManagementWebModule?

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#807]
[DependsOn(
        typeof(EVApplicationModule),
        typeof(EVEntityFrameworkCoreModule),
        typeof(AbpAutofacModule),
        typeof(AbpIdentityWebModule),
        typeof(AbpAccountWebModule),
        typeof(AbpSettingManagementWebModule),============
        typeof(AbpAspNetCoreMvcUiBasicThemeModule)
        )]
    public class EVWebModule : AbpModule
Only add ===== line？
web ui not show。

**Comment by acjh** [comment]
What do you mean by web ui?

**Comment by CAH-FlyChen** [comment]
![image](https://user-images.githubusercontent.com/1214546/52758484-5e077580-3043-11e9-8aec-8e8b5ec22031.png)
menu not show

**Comment by CAH-FlyChen** [comment]
After read code。I got something. Settings module need to inject other module‘s menu contributers to show the menu?
