### ISSUE TITLE
CurrentUser add claim cannot work(cannot go to my CreateAsync function breakpoints at all) and document request

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#8073]
* Your **ABP Framework version**
v4.2.2
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
MVC
* Your database provider(EF Core/MongoDB)
EF Core

Description:
I want to add custom claim to CurrentUser And I do as recommendation in bellow link:
https://github.com/abpframework/abp/issues/42#issuecomment-576025862

* Steps needed to **reproduce** the problem.
1. abp new Acme.BookStore --tiered
2. Add MyUserClaimsPrincipalFactory(detail see below code) class in Acme.BookStore.Domain project
3. Replace the AbpUserClaimsPrincipalFactory with MyUserClaimsPrincipalFactory by pre-configuring the IdentityBuilder in the PreConfigureServices of BookStoreDomainModule.cs module
4. Start the Acme.BookStore.IdentityServer project and login in admin/1q2w3E*
5. Check the Claims and cannot find my custom claim(mpa_app)

```C#
namespace Acme.BookStore
{
    public class MyUserClaimsPrincipalFactory : AbpUserClaimsPrincipalFactory, ITransientDependency
    {
        public MyUserClaimsPrincipalFactory(UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IOptions<IdentityOptions> options,
            ICurrentPrincipalAccessor currentPrincipalAccessor,
            IAbpClaimsPrincipalFactory abpClaimsPrincipalFactory) :
            base(userManager, roleManager, options, currentPrincipalAccessor, abpClaimsPrincipalFactory)
        {
        }

        [UnitOfWork]
        public override async Task<ClaimsPrincipal> CreateAsync(IdentityUser user)
        {
            var principal = await base.CreateAsync(user);
            var identity = principal.Identities.First();
            // add custom claim
            identity.AddClaim(new Claim("mpa_app", "app1"));
            identity.AddClaim(new Claim("mpa_app", "app2"));
            identity.AddClaim(new Claim("mpa_app", "app3"));

            return principal;
        }
    }
}
```

In BookStoreDomainModule.cs 
```C#
public override void PreConfigureServices(ServiceConfigurationContext context)
{
        PreConfigure<IdentityBuilder>(builder =>
        {
            builder.AddClaimsPrincipalFactory<MyUserClaimsPrincipalFactory>();
        });
 }
```

[bookstore-tiered.zip](https://github.com/abpframework/abp/files/6145817/bookstore-tiered.zip)

I have uploaded my test demo, I hope you can help me find the problem or what I have missed.
As time goes, does we have another way to extend user claims?
I search all the ticket about the claims, and I found it was very confusing and lots of them should be out-of-date.
If you have documentation that explains how to extend the user claim, how to map them will prefer good.

I am very confusing as below way, which one recommended, and what's difference, and each one for what scenario?
https://github.com/abpframework/abp/pull/7165#issue-553392247
https://github.com/abpframework/abp/pull/7998#issue-587498154
https://github.com/abpframework/abp/issues/7973#issuecomment-792400888

Thank you!
Have a nice day.

**Comment by realLiangshiwei** [comment]
For now, 

```csharp
public class MyAbpClaimsPrincipalContributor : IAbpClaimsPrincipalContributor, ITransientDependency
{
    public Task ContributeAsync(AbpClaimsPrincipalContributorContext context)
    {
        var claimsIdentity = new ClaimsIdentity();
        claimsIdentity.AddIfNotContains(new Claim("Organization", "OrganizationValue"));
        context.ClaimsPrincipal.AddIdentity(claimsIdentity);

        return Task.CompletedTask;
    }
}

public class MyAbpClaimsService : AbpClaimsService
{
    public MyAbpClaimsService(IProfileService profile, ILogger<DefaultClaimsService> logger) : base(profile, logger)
    {
    }

    protected override IEnumerable<string> FilterRequestedClaimTypes(IEnumerable<string> claimTypes)
    {
        return base.FilterRequestedClaimTypes(claimTypes)
            .Union(new []{
                AbpClaimTypes.TenantId,
                AbpClaimTypes.EditionId,
                "Organization"
            });
    }
}


context.Services.Replace(ServiceDescriptor.Transient<IClaimsService, MyAbpClaimsService>());
```

After version 4.3, there is an easier way: https://github.com/abpframework/abp/pull/7998

**Comment by gerryge** [comment]
var claimsIdentity = new ClaimsIdentity();  ???

why not use 
var claimsIdentity = context.ClaimsPrincipal.Identities.FirstOrDefault();

@hikalkan
Can you help to clarify?
Best regards.
