### ISSUE TITLE
Audit for one-to-many/many-to-many relationships

### ISSUE THREAD

**Issue by evavsun** [abpframework/abp#8085]
Hello, team! We have followed all steps to set up Audit Entities changes (https://docs.abp.io/en/abp/latest/Audit-Logging), but for one-to-many/many-to-many relationships it does not work. Could you please answer, how to solve this problem or it does not work at all?
I would really appreciate, if you can assist us to get this issue resolved at the earliest. Awaiting your response.

EF Core 5.0
MS SQL Server

**Comment by chrismorison-wt** [comment]
@evavsun Did you find a solution to this?

When I create a user I can see the `AbpPropertyChanges` for the new `User` fields, but how can I audit the changes to `AbpUserRoles` so I can see any changes to assigned roles for the user?
