### ISSUE TITLE
app.InitializeApplication()  error tips  IApplicationBuilder has been registered.

### ISSUE THREAD

**Issue by xiatiandegaga** [abpframework/abp#8090]
version-4.2.2
Volo.Abp.Core：4.2.2
Volo.Abp.AspNetCore：4.2.2
Com.Ctrip.Framework.Apollo.Configuration：2.4.1

Hi, team, i use apollo to  replace default configuration,the  main method like this

public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostBuilderContext, configurationBuilder) =>
                {
                    configurationBuilder.AddApollo(configurationBuilder.Build().GetSection("apollo"));
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseSerilog();

when run  app.InitializeApplication(),   it's error and tips No service for type 'Volo.Abp.DependencyInjection.ObjectAccessor`1[Microsoft.AspNetCore.Builder.IApplicationBuilder]' has been registered.
![image](https://user-images.githubusercontent.com/47713355/111564159-3eb81500-87d4-11eb-883c-dfeff047cbbd.png)

**Comment by xiatiandegaga** [comment]
sorry，my network is error，so repeat post，the code format is bad

public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostBuilderContext, configurationBuilder) =>
                {
                    configurationBuilder.AddApollo(configurationBuilder.Build().GetSection("apollo"));
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseSerilog();


public class CloudApolloModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            var config = ConfigurationHelper.BuildConfiguration(builderAction: builder =>
             {
                 builder.AddApollo(builder.Build().GetSection("apollo"));
             });
            context.Services.ReplaceConfiguration(config);
            var configuration = context.Services.GetConfiguration();
        }
    }

**Comment by hillin** [comment]
To any future tourists who encounters this problem: it means you somehow didn't have the `AbpAspNetCoreModule` loaded. It's typically loaded through the `AbpAspNetCoreMvcModule` which should be depended by your application layer or HTTP API layer.
