### ISSUE TITLE
[Question] Account navigate another entity.

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#8093]
Hi team!
I have a scenario that  I want to generate an account for this enterprise, When I create an enterprise.
enterprise model is one to one account model 
I tryed IAccountAppService.RegisterAsync method, but AppUser.Id is readonly.
![2021-03-17 160303](https://user-images.githubusercontent.com/19605145/111434235-46c37680-873a-11eb-9d2f-e00c595bcc6e.png)
so what should I do, or there's a better way?
Thanks!

**Comment by ilkayilknur** [comment]
Can you look into that @maliming, please?

**Comment by maliming** [comment]
@trickyrat Please create an entity manually.

https://github.com/abpframework/abp/blob/91b34466dd239dfcb10293dec87dcb118cd70434/modules/docs/src/Volo.Docs.Admin.Application/Volo/Docs/Admin/Projects/ProjectAdminAppService.cs#L66-L74
