### ISSUE TITLE
Problems with abp cli

### ISSUE THREAD

**Issue by Gosha24** [abpframework/abp#8095]
I run command abp update in Command prompt (run as administrator.) 
I get error: Access to the path 'C:\Windows\system32\LogFiles\WMI\RtBackup' is denied. To
To overcome this issue i run command 
dotnet tool update -g Volo.Abp.Cli
This updated version from 4.2.1 to 4.2.2 successfully.

**Comment by ilkayilknur** [comment]
@yekalkan Can you look into that, please? Is this a known issue?

**Comment by yekalkan** [comment]
> @Gosha24 I run command abp update in Command prompt

To update cli?

**Comment by Gosha24** [comment]
Yes

**Comment by yekalkan** [comment]
`abp update` doesn't have such a function.

See related docs https://docs.abp.io/en/abp/latest/CLI#update
