### ISSUE TITLE
When Microsoft.EntityFrameworkCore.DbUpdateException occurs, Swagger still return 200 

### ISSUE THREAD

**Issue by hanpan1935** [abpframework/abp#8103]
![image](https://user-images.githubusercontent.com/16703552/111456767-5c449a80-8752-11eb-83f3-0910f01f55fd.png)

below is my code
![image](https://user-images.githubusercontent.com/16703552/111457197-df65f080-8752-11eb-85dd-a46651d37735.png)

**Comment by ilkayilknur** [comment]
Can you provide more info like ABP version, etc.. and reproductions steps, please?

**Comment by amsaighi** [comment]
Hello, 
I guess you have conflict in FK (productId) ( products and PurchaseOrderDetails)
