### ISSUE TITLE
Upgrade to Bootstrap 4.6

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8125]
We should consider to upgrade to bootstrap 4.6 in ABP v4.3.

- [x] MVC UI / @maliming 
- [x] Angular UI / @mehmet-erim 
- [x] Blazor UI / @maliming, cc: @stsrki

**Comment by stsrki** [comment]
Blazorise is already 4.6 compatible so I would guess for ABP we only need to update bundle files?
