### ISSUE TITLE
SequentialGuidGenerator by default

### ISSUE THREAD

**Issue by Ice2burn** [abpframework/abp#8127]
As states in [ABP documentation](https://docs.abp.io/en/abp/latest/Guid-Generation#guid-generation):

> IGuidGenerator service creates sequential GUIDs (implemented by the SequentialGuidGenerator by default)

However in many places of the framework `SimpleGuidGenerator` is used as default, for example in [DomainService.cs](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Services/DomainService.cs):
`protected IGuidGenerator GuidGenerator => LazyServiceProvider.LazyGetService<IGuidGenerator>(SimpleGuidGenerator.Instance);`

![image](https://user-images.githubusercontent.com/6002280/111650720-9e371480-8816-11eb-8566-4cbdf78d97a0.png)

I can't find any mentions to inject it manually
`services.AddTransient<IGuidGenerator, SequentialGuidGenerator>();`

So, is this by design or is this a documentation inaccuracy?

**Comment by maliming** [comment]
hi

* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.


The `SequentialGuidGenerator` inherit `ITransientDependency` by default.

**Comment by Ice2burn** [comment]
Abp 4.2.2. Tested in console startup template. Inherit HelloWorldService from DomainService.
[Example: MyCompanyName.MyProjectName.zip](https://github.com/abpframework/abp/files/6169921/MyCompanyName.MyProjectName.zip)

**Comment by maliming** [comment]
```cs
[DependsOn(
    typeof(AbpAutofacModule),
    typeof(AbpGuidsModule)
)]
public class MyProjectNameModule : AbpModule
```

**Comment by gdlcf88** [comment]
`SimpleGuidGenerator` is enough for a console app.
