### ISSUE TITLE
TenantId and Auditfields not populating

### ISSUE THREAD

**Issue by zaktecs** [abpframework/abp#8129]
Hi,

I was wondering if someone can help me.

When I use this  **var response = await _employeeRepository.InsertAsync(entity, true);** to submit data the TenantId and all the Audit trail data is not adding to the tables BUT using the following does

var entity = await _employeeAppService.CreateAsync(entity1);

I would like to use the former to set my fields in the appService as I'm not using automapper.

Many thanks
Zak

**Comment by maliming** [comment]
hi zaktecs 

* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)

**Comment by zaktecs** [comment]
Hi @maliming,

Thanks for your response.

Your ABP Framework version. = 4.2
Your database provider(EF Core/MongoDB) = EF Core

Kind Regards,
Zak

**Comment by maliming** [comment]
hi 

Can you share the full code to reproduce the problem?

**Comment by zaktecs** [comment]
Hi @maliming,
The code is part of a large project, but this is what I found  if I Use

======================== Option 2
**private readonly IRepository<Employee, Guid> _employeeRepository;** (I have to pass the tenantId manually) BUT if I use
var result = await _employeeRepository.InsertAsync(employeeEntity, true);

======================== Option 2
**private readonly IEmployeeAppService _employeeAppService;** (ABP takes care of the TenantId, I don't have to manually set it)
var entity = await _employeeAppService.CreateAsync(entity1);

Many thanks

Zak

**Comment by d-oit** [comment]
Had the same issue. With the aspnetboilerplate implentation IMustHaveTenant it was a clear NON null setter for the TenantId. Now it could by null and devs have to carry about it. 
 
Check out the CrudAppService. In InsertAsync 
**TryToSetTenantId**
is called for the entity (but not for related data!). 

To secure and not change the abp logic i check the TenantId setter for null or Guid.Empty and throw an error if the it is ONLY for tenants storage.


Another way is to use the ef core interceptors - savechanges:
https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/events

I this way i wouldn't use the Audit abp implentation.
