### ISSUE TITLE
Change master layout

### ISSUE THREAD

**Issue by madschristiansen** [abpframework/abp#813]
Hi, 
Sorry for my probably simple question.
I can’t find master layout or any shared folder for changing theme anywhere?

Do I need to add something?

Br Mads

**Comment by hitaspdotnet** [comment]
Layout comes from theme [Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic](https://github.com/abpframework/abp/tree/master/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic). Theming document isn't ready yet. You can create your own Layout as you did before.

**Comment by madschristiansen** [comment]
I will look into that. How do I implement it so I get the files available inside the project?

**Comment by hitaspdotnet** [comment]
1. Clone the repository
2. Make a copy from basic theme into your solution with new naming
3. Change ABP local references to NuGet references in YourTheme.csproj
4. Start developing
5. Add your new theme dependency to your web module
6. Set your new theme as default theme in your web module
7. Enjoy

**Comment by madschristiansen** [comment]
This is awesome, thank you very much!!

**Comment by hitaspdotnet** [comment]
OR: (_my suggest_)
1. Create new layout at your web project
2. Set basic theme empty layout as Layout of your custom layout
_myLayout.cshtml:
```cshtml
@using Volo.Abp.AspNetCore.Mvc.UI.Theming
@inject IThemeManager ThemeManager
@{
    Layout = ThemeManager.CurrentTheme.GetEmptyLayout()
}
///your awesome master layout codes
```
Then in your pages
Index.cshtml:
```cshtml
@{
    Layout = _myLayout.cshtml 
}

**Comment by vnetonline** [comment]
> * Clone the repository
> * Make a copy from basic theme into your solution with new naming
> * Change ABP local references to NuGet references in YourTheme.csproj
> * Start developing
> * Add your new theme dependency to your web module
> * Set your new theme as default theme in your web module
> * Enjoy

@hitaspdotnet where in the webmodule should I set my thermal ?
