### ISSUE TITLE
Q: Deploying host project

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#8130]
https://docs.abp.io/en/abp/latest/Startup-Templates/Module#host-projects

If you just want to make webservice (with Swagger) without UI, is recommended or not to deploy .HttpApi.Host project from MODULE project solution (**in host folder**) in production environment?

Thank you.

**Comment by maliming** [comment]
This project is used to test the module.  You can refer to these host projects.

https://github.com/abpframework/abp/tree/dev/templates/app/aspnet-core/src

**Comment by leonkosak** [comment]
@maliming, I know that, but we have all logic inside **abp MODULE** and therefore if we want just deploy module as microservice (with Swagger UI) we have "wrap" this module with **abp APPLICATION** and deploy .HttpApi.Host from abp **application**?
What are benefits of this approach? The downside is that we have two "full blown" abp solutions (one application and one module) which have to be maintained, upgraded,....

Why deploy .HttpApi.Host from host folder (in module Visual Studio solution) is not production ready project (especially if this is only API microservice application - REST application API)?

**Comment by sebitsi** [comment]
Če na hitro pogledaš sta oba template-a skoraj identična.
Ne vem zakaj host od modula nebi bil production ready.

Me zanima njegov odgovor.
