### ISSUE TITLE
The "-dbms" for module template is not working

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#8134]
![image](https://user-images.githubusercontent.com/30018771/111739730-80bd8580-88be-11eb-914e-b61599dba05a.png)

![image](https://user-images.githubusercontent.com/30018771/111739339-d7768f80-88bd-11eb-902c-39662e8b72b2.png)

"-dbms" is a common option but the **DatabaseManagementSystemChangeStep** is only used by app creation:
https://github.com/abpframework/abp/blob/3a48122997abe1a0b650f9156890382aa6821344/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/Building/TemplateProjectBuildPipelineBuilder.cs#L29-L33

**Comment by EugeniZaplatin** [comment]
This issure not resolved in 4.3 preview

**Comment by jflaga** [comment]
This issue is still not resolved in version 7.4.0

But switching databases is well documented. For example, if you want to switch from SQL Server to PostgreSQL, use this guide: ["Switch to EF Core PostgreSQL Provider"](https://docs.abp.io/en/abp/latest/Entity-Framework-Core-PostgreSQL)

**Comment by maliming** [comment]
This will be supported on 8.0.

https://github.com/abpframework/abp/pull/17856
