### ISSUE TITLE
Main Website returning 502: Bad Gatewar

### ISSUE THREAD

**Issue by ocodista** [abpframework/abp#8147]
Main website is down.

![image](https://user-images.githubusercontent.com/19851187/111820489-566cc780-88c0-11eb-84c7-bc73bbba1f42.png)

**Comment by hamuryen** [comment]
nuget.abp.io also doesn't work

**Comment by willignicolas** [comment]
Same for the use of commercial abp suite. We can't modify our project...

**Comment by maliming** [comment]
It works now.

**Comment by hamuryen** [comment]
![abp](https://user-images.githubusercontent.com/14908017/111865472-38629e00-8978-11eb-81cb-c6766c2c11cb.PNG)

Are you sure?

**Comment by willignicolas** [comment]
Still down. Error 502 on abp.io and suite not usable.

![image](https://user-images.githubusercontent.com/8667398/111866909-fe41ce00-8970-11eb-9f8e-9b571ccb5955.png)

We are in France.

**Comment by EngincanV** [comment]
It works now, thanks for the information.

**Comment by jimmidier** [comment]
![image](https://user-images.githubusercontent.com/16027480/111934450-6375fa80-8afc-11eb-860c-e0e926d9556a.png)

It happens again
