### ISSUE TITLE
How to protect my API - ensure calls are coming from my apps

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#8148]
Hi,

I wish to give an example, I have an API that allow to add images, or even delete image.

Because of this, it is not to difficult to add or even delete some images.

Is there a way to ensure that the calls are coming from my applications  (web site, mobile, etc...).

I'm thinking to a token... that I can use with each call.

My understanding is that Identity token are only to identify users, not applications ?

**Comment by maliming** [comment]
This is not related to abp.

**Comment by muratyuceer** [comment]
If you configure the token-issuing application to issue tokens to certain applications, other applications will not be able to receive tokens, so they cannot come to your services.
