### ISSUE TITLE
Why not just use Orleans?

### ISSUE THREAD

**Issue by xewn** [abpframework/abp#815]
Why not just use Orleans?

**Comment by hikalkan** [comment]
For what?

**Comment by xewn** [comment]
yes

**Comment by maliming** [comment]
@xewn What problem do you want to solve with Orleans?

**Comment by natiki** [comment]
Or [MicroDot](https://github.com/gigya/microdot) or.... or..... There are heaps of projects out there that do the same thing or parts of the same thing eg https://github.com/abpframework/abp/issues/738 and so on.

So if you want to use another framework then do so, or if you want to suggest functionality or integration with ABP then lets hear what you are after.
