### ISSUE TITLE
Article Request : Tiered MVC Project with Docker Compose and NGINX

### ISSUE THREAD

**Issue by ImranHugo** [abpframework/abp#8165]
Would be great to get a best practice guide for configuring a full docker stack for a tiered MVC solution sitting behind an NGINX reverse proxy.  Things to include in the guide:

- best practice dockerfile for each tier (identity  / API Host / Web UI)
- multi VM setup (clustering API over multiple machines to handle load)
- config for NGINX to load balance API

**Comment by BarisGurbuz** [comment]
Yes, would be great

**Comment by beriniwlew** [comment]
Can I add my support to this as well?   I think it's important that we have docker support that is documented like this!

**Comment by antosubash** [comment]
I have created a blog post about this. I think it will be good starting point to deploy in docker. 

Blog post: https://blog.antosubash.com/posts/abp-deploy-with-docker

Youtube Video: https://www.youtube.com/watch?v=L2GeLy_VWRQ
