### ISSUE TITLE
Document how to add basic theme's source code into the application's solution

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8169]
Update the following documentation to suggest to use ABP CLI instead of manually copy the basic theme source code.

- [x] MVC: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Basic-Theme#copy-customize
- [x] Blazor: https://docs.abp.io/en/abp/latest/UI/Blazor/Basic-Theme#copy-customize (blazor wasm + server)
- [x] Angular: https://docs.abp.io/en/abp/latest/UI/Angular/Basic-Theme#copy-customize

**Comment by radrad** [comment]
Can I pick a random tailwind CSS based admin template and incorporate it into an abp.io solution (let's say either mvc or angular) 
and have the same appearance as designer wanted or I will get some abp.io rendering that is pre-determined (maybe to use boostrap)  and hard to align with other design element from tailwind css framework?

**Comment by yekalkan** [comment]
https://github.com/abpframework/abp/pull/9307
