### ISSUE TITLE
C# Dynamic Proxy empty parameters on a GET request

### ISSUE THREAD

**Issue by Alexbits** [abpframework/abp#8174]
I have an issue with Dynamic Poxy using the custom interface below for my application service. The Get request to GetListAsync works fine from the Swagger UI, but when it's done from the client (Blazor), SummaryRequestDto parameters are not included in the GET request (I see this in browser dev tools) and every property in SummaryRequestDto is null.

```C#
 public class PagedResultRequestDto : LimitedResultRequestDto
    {
        public string? ContinuationToken { get; set; }
    }

   public class SummaryRequestDto : PagedResultRequestDto
    {
        public DateTimeOffset? Start { get; set; }
        public DateTimeOffset? End { get; set; }
        public Guid? UserId { get; set; }
    }

 public class SummaryDto : IEntityDto<string>
    {
        public string Id { get; set; }

        public Guid UserId { get; set; }

        public List<SummaryDetailsDto>? Summary { get; set; }

    }

  public interface IReadOnlyListAppService<TGetListOutputDto, in TGetListInput> : IApplicationService
  {
          Task<PagedResultDto<TGetListOutputDto>> GetListAsync(TGetListInput input);
  }

   public interface ISummaryAppService : IReadOnlyListAppService<SummaryDto, SummaryRequestDto>
  {
  }
  
  public class SummaryAppService : MyAppService, ISummaryAppService
   { 
          [Authorize(MyAppPermissions.Summary.Default)]
          public async Task<PagedResultDto<SummaryDto>> GetListAsync(SummaryRequestDto resultRequestDto)
          {
          }
}
```

It works fine when I use IApplicationService  instead of IReadOnlyListAppService<SummaryDto, SummaryRequestDto> for ISummaryAppService. So it looks like the generics affect how the get request is built?

* ABP 4.2.2
* Blazor WASM
* EF Core/Cosmos DB

**Comment by maliming** [comment]
Can you share a simple project?

**Comment by Alexbits** [comment]
Hi @maliming. Yes, check the attached sample. Thanks.
[TestAppService.zip](https://github.com/abpframework/abp/files/6195517/TestAppService.zip)

**Comment by maliming** [comment]
```cs
- public async Task<PagedResultDto<SummaryDto>> GetListAsync(SummaryRequestDto resultRequestDto)
+ public async Task<PagedResultDto<SummaryDto>> GetListAsync(SummaryRequestDto input)
```

**Comment by Alexbits** [comment]
Thank you @maliming! That was not obvious.

**Comment by Stirda** [comment]
I agree @Alexbits . I encountered the same problem (not the same parameter name in service interface vs service class). Solution build but call from client set parameter to null silently. @maliming Could [documentation page](https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients) say a little about that tricky behavior. I know it is the dev fault, not ABP one. But it would be kind to set the developer to the solution path.
