### ISSUE TITLE
Modal - Allow add customizable beforeSubmit callback

### ISSUE THREAD

**Issue by trgiangvp3** [abpframework/abp#8177]
I'm creating an input form in a modal and now I want to run a validation process on client side before the request is made (when user click on Save button)

![image](https://user-images.githubusercontent.com/48433917/112246453-402a8700-8c85-11eb-888f-1cf816cd8b4a.png)

I saw the code in [modal-manager.js](https://github.com/abpframework/abp/blob/1d650f8bf79570e890e648fcf845fcfc5ffa89de/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js) line [73](https://github.com/abpframework/abp/blob/1d650f8bf79570e890e648fcf845fcfc5ffa89de/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/bootstrap/modal-manager.js#L73)
As the function abpAjaxForm is called with no parameters passed in, I can't set the [beforeSubmit](https://github.com/abpframework/abp/blob/1d650f8bf79570e890e648fcf845fcfc5ffa89de/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery-form/jquery-form-extensions.js#L19) callback.

I wonder if there is any other way to set the beforeSubmit callback now?
If there is not, can I wait for this feature in the next release of abp?

* **ABP Framework version**
> 4.2.2 (Stable)
* **User Interface**
> MVC/Razor
* **Database provider**
> Entity Framework

**Comment by maliming** [comment]
@trgiangvp3 

You can try to make form `data-ajaxForm="false"` then call `abpAjaxForm` method manually.

**Comment by trgiangvp3** [comment]
> @trgiangvp3
> 
> You can try to make form `data-ajaxForm="false"` then call `abpAjaxForm` method manually.

Thank you!
This did the trick.
But I believe that allowing [`abpAjaxForm`'s `userOptions`](https://github.com/abpframework/abp/blob/1d650f8bf79570e890e648fcf845fcfc5ffa89de/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/wwwroot/libs/abp/aspnetcore-mvc-ui-theme-shared/jquery-form/jquery-form-extensions.js#L6) to be set on modal opening is a more elegant way to achieve this.

**Comment by maliming** [comment]
hi

I will give it a try.

**Comment by maliming** [comment]
No need to change it.

**Comment by espindl** [comment]
> @trgiangvp3
> 
> You can try to make form `data-ajaxForm="false"` then call `abpAjaxForm` method manually.

How is this done? Can you give a little bit more detail?

**Comment by trgiangvp3** [comment]
> How is this done? Can you give a little bit more detail?

Your modal's cshtml
```
<form id="myModal" data-ajaxform="false" ....>
    <!-- Modal definition code -->
</form>

```

Your javascript (where you open the modal)
```
createModal.onOpen(() => {
    $('form#addWalletForm').abpAjaxForm({
      beforeSubmit: beforeSubmitFormCallback
    });
  });
```

**Comment by espindl** [comment]
Thank you @trgiangvp3
