### ISSUE TITLE
Add new properties to AbpSession

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#8190]
Hi,

I need to get more information related to logged in user in client side (angular), and these info will be retrieved frequently and across different ui modules.
is there any way to store these info in "AbpSession" or in user token?
**ASP.NET Core + Angular**

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/42

**Comment by amLabib** [comment]
Hi @maliming,
thanks for your reply, I followed [this](https://github.com/abpframework/abp/issues/42#issuecomment-576025862) answer from hikalkan, but it doesn't seem working.
I found this solution [#7165](https://github.com/abpframework/abp/pull/7165), and it's working, is this a recommended solution?

**Comment by maliming** [comment]
hi

I recommend using `AbpClaimsPrincipalFactory`.
