### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by dafeifei0218** [abpframework/abp#8194]
ABP Framework version：4.2.2
New project created with get started
Project type：Application
UI Framework: Angular
Database provider: Entity Framework Core
Database management system: MySQL
Mobile：None
Separate Identity Server: Check
After restoring the database, the certificate error occurs when running the project.
![certificate error](https://user-images.githubusercontent.com/10148878/112409625-cfeb3680-8d54-11eb-9e5b-eefabe56d0c2.png)

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/112410013-75060f00-8d55-11eb-87b9-0a430348c0d3.png)

**Comment by dafeifei0218** [comment]
It works. It doesn't work

**Comment by dafeifei0218** [comment]
Execute "dotnet dev certs HTTPS -- trust", but it doesn't work

**Comment by maliming** [comment]
This error irrelevant ABP but Kesrel.
