### ISSUE TITLE
4.3-RC.1 version release time

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#8205]
Based on [latest blog post](https://blog.abp.io/abp/ABP.IO-Platform-4-2-Final-Has-Been-Released) 

> The next feature version will be 4.3. It is planned to release the 4.3 RC (Release Candidate) on March 11 and the final version on March 25, 2021.

and based on community home page the preview version release time was 25 march.
We understand the difficulty. Please, if the schedule is to be changed, it should be announced before the date and not on the promised day.

**Comment by richfuns** [comment]
Awesome job.
