### ISSUE TITLE
User is redirected to Account/AccessDenied?ReturnUrl=%2FBooks, result in error 404

### ISSUE THREAD

**Issue by ivanagui2** [abpframework/abp#8206]
* Your **ABP Framework version** - 4.2.2
* Your **User Interface** type (Angular/MVC/React... etc.) - MVC
* Your database provider(EF Core/MongoDB) - EF Core
* Steps needed to **reproduce** the problem.

When a user doesn't have permission to list, create, edit or delete pages the user is redirected to Account/AccessDenied?ReturnUrl=%2FBooks. This problem should have already been fixed in #7207.

![image](https://user-images.githubusercontent.com/23294213/112504326-f6789400-8d8b-11eb-99a8-71d0ae6b72b8.png)

**Comment by maliming** [comment]
hi

This PR merged in `dev` branch. You can copy the code to your project. We will release v4.3 soon.
 
https://github.com/abpframework/abp/pull/7215

![image](https://user-images.githubusercontent.com/6908465/112562515-6598cb80-8e12-11eb-9bbd-a6fa7ca1f877.png)

**Comment by ivanagui2** [comment]
Okay, @maliming . I already did it yesterday. Thank you very much.
