### ISSUE TITLE
Can't define a property as Guid from dropdown in abp Suite

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#8207]
Shouldn't it be possible to select Guid from the dropdown or am I missing something?

I tried to update the JSON file manually but the UI then of course doesn´t pick it up. 

I can get around this by generating everything and then undoing everything in git except the JSON file and then recreate it again in Suite. 

![image](https://user-images.githubusercontent.com/2386572/112521304-45c2c280-8d94-11eb-82d8-1836908812a3.png)

* Your **ABP Framework version**. 4.2.2
* Your database provider(EF Core/MongoDB) EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by ebicoglu** [comment]
Blazorise components doesn't support Guid input 

https://support.abp.io/QA/Questions/998/Bug-in-422---Guid-not-available-as-a-Property-Type-on-Add-Property

**Comment by sturlath** [comment]
So a UI component dictates the database structure? Wouldn't it be better to allow Guid and then do a ToString() conversion for the UI?

Guid == uniqueidentifier so with a column as a string the uniqueness is not guaranteed. I'm no expert on this but doesn´t this affect things like indexing?

I'll probably go through the hoops of using a Guid and converting it to a string in the UI. I´ll let you know if for some reason that doesn't work...
