### ISSUE TITLE
Can we use WebHost.CreateDefaultBuilder() with Autofac?

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#821]
Currently, we should manually build the host:

````csharp
 public static IWebHost BuildWebHostInternal(string[] args) => 
     new WebHostBuilder() 
         .UseKestrel() 
         .UseContentRoot(Directory.GetCurrentDirectory()) 
         .UseIISIntegration() 
         .UseStartup<Startup>() 
         .UseSerilog() 
         .Build();
````

Based on this discussion: https://github.com/abpframework/abp/issues/715

**Comment by mehmetuken** [comment]
https://github.com/abpframework/abp/commit/b856b1dcbf2da9c037d1750c16dc7bad4f215f24 did this solve the issue?

**Comment by hikalkan** [comment]
Yes, this issue has been solved. For example, startup template now uses Host.CreateDefaultBuilder https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Web/Program.cs#L42

So, we can close this. Thanks for notifying :)
