### ISSUE TITLE
Oracle OPD.NET provider bug: "An error occurred using a transaction." (ORA-00900)

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#8210]
We  use [Oracle.EntityFrameworkCore  v5.21.1](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/) package. This is the latest version. But there's a bug on this version.
Insert/update/delete transactions (which returns affected rows count) write the following log:
```
[ERR] An error occurred using a transaction.
```
In the error trace, we see `ORA-00900` error... It just writes this log and keeps working (doesn't stop the application).
Oracle's bug doesn't block you. 
Oracle eventually fixed it in their development branch.
And next upcoming release it'll be fixed.
We'll watch this new version and whenever they release we'll update on our side too.

You can check out the related issue from Oracle repo:
https://github.com/oracle/dotnet-db-samples/issues/146

**==>> WAITING FOR THE NEXT RELEASE of Oracle.EntityFrameworkCore - ODP.NET<==**

**Comment by NepPure** [comment]
https://github.com/oracle/dotnet-db-samples/issues/167

Because there is no detailed error message, this problem has been investigated for a long time.

**Comment by crashsol** [comment]
mark , the same problem,

**Comment by hikalkan** [comment]
@ebicoglu I see the new version has been published. Did you try with it?

**Comment by NepPure** [comment]
Solved

**Comment by hikalkan** [comment]
Thanks @NepPure for the information :)

**Comment by hikalkan** [comment]
@ebicoglu then we can upgrade the Oracle dependency (https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore.Oracle/Volo.Abp.EntityFrameworkCore.Oracle.csproj#L22) and close this issue.

**Comment by ebicoglu** [comment]
Updated to the latest _(5.21.3)_ but now the Oracle has another problem. It doesn't work on .NET6
See https://github.com/oracle/dotnet-db-samples/issues/201

Read [Oracle Support for .NET 6 and Entity Framework Core 6: Statement of Direction](https://medium.com/oracledevs/oracle-support-for-net-6-and-entity-framework-core-6-statement-of-direction-cfa5d1c59ff8)

**Comment by hikalkan** [comment]
@ebicoglu is that solved?

**Comment by NepPure** [comment]
Solved

**Comment by ebicoglu** [comment]
tested against the latest version `v6.21.5` and no problem!
closing the issue.
