### ISSUE TITLE
Can't create an entity called Language because of ambiguous reference error

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#8219]
Hi

I'm trying to create a language table (unrelated to translations) using Suite and it throws me the following error. 

`C:\Dev\Test\aspnet-core\src\Test.EntityFrameworkCore\EntityFrameworkCore\TestEntityFrameworkCoreModule.cs(55,49): error CS0104: 'EfCoreLanguageRepository' is an ambiguous reference between 'Test.Languages.EfCoreLanguageRepository' and 'Volo.Abp.LanguageManagement.EntityFrameworkCore.EfCoreLanguageRepository' [C:\Dev\Test\aspnet-core\src\Test.EntityFrameworkCore\Test.EntityFrameworkCore.csproj]
 `

For now, I´ll call it "OurLanguages" (or something.. naming is hard) but I would prefer it just being Language and the DB table AppLanguage.

* Your **ABP Framework version**. 4.2.2
* Your database provider: EF Core

**Comment by ebicoglu** [comment]
since this is not related to the ABP Open Source Framework, sorry I'm closing this issue. Please create an issue on support.abp.io
