### ISSUE TITLE
Dos the module project support generic IRepository<MyEntity, Guid> repository ？

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#822]
got error
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`2[EV.Domain.WeiXins.WXMenu,System.Guid] repository' of constructor 'Void .ctor(Volo.Abp.Domain.Repositories.IRepository`2[EV.Domain.WeiXins.WXMenu,System.Guid])'.

**Comment by hikalkan** [comment]
Have you used .AddDefaultRepositories() option? https://github.com/abpframework/abp/blob/master/docs/en/Entity-Framework-Core.md#add-default-repositories

**Comment by CAH-FlyChen** [comment]
i forgot thanks
