### ISSUE TITLE
How do I get the abp nightly build?

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#8229]

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/CLI#switch-to-nightly

**Comment by vnetonline** [comment]
I have tried this it doesn't work

**Comment by realLiangshiwei** [comment]
![image](https://user-images.githubusercontent.com/16813853/112723443-75ff9200-8f49-11eb-98ad-91d91f764095.png)
