### ISSUE TITLE
UserFriendlyException localization issue

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#8233]
Version : Latest
UI: MVC

I'm trying to send an exception like below from an appservice which is derived from CrudAppService. 

`throw new UserFriendlyException(L["TestMessage"]);`

But localization is not working. I already added the localization text like below in en.json.
`"TestMessage": "Test message!",`

And yes i have selected english as language.

I already read [exception handling doc](https://docs.abp.io/en/abp/latest/Exception-Handling#exception-localization).
Can any one help me?

**Comment by colinin** [comment]
You should specify the name of the localized resource in the ApplicationService constructor, LocalizationResource = typeof(YouLocalizationResource)

**Comment by muhlisatac** [comment]
Thank you so much. It works now. 
But why its not set as deafult in CrudAppService or at least not mentioned in the documents?

**Comment by maliming** [comment]
https://docs.abp.io/en/abp/latest/Localization#special-base-classes
