### ISSUE TITLE
How to modified property ICurrentUser Abp framework

### ISSUE THREAD

**Issue by ngaothetieutu** [abpframework/abp#8234]
Hi there,

I have a request to modified  propertys CurrentUser.
Default property CurrentUser Abp : 
        IsAuthenticated 
        Id 
        UserName 
        PhoneNumber 
        PhoneNumberVerified 
        Email 
        EmailVerified 
        TenantId 
        Roles 
        Claim FindClaim(claimType);
        Claim[] FindClaims(claimType);
        Claim[] GetAllClaims();
        IsInRole(roleName);
 Now how can i addproperty Address to CurrentUser

Thanks.

**Comment by yekalkan** [comment]
see https://github.com/abpframework/abp/issues/2930#issuecomment-591756387

**Comment by ngaothetieutu** [comment]
> see [#2930 (comment)](https://github.com/abpframework/abp/issues/2930#issuecomment-591756387)

Thanks, but i don't understand how to add property??? Can you describe in more detail??thanks

**Comment by yekalkan** [comment]
That comment doesn't suggest you to `add property`. Create a `CurrentUser.GetAddress() extension method` and a related Claim.

**Comment by ngaothetieutu** [comment]
> That comment doesn't suggest you to `add property`. Create a `CurrentUser.GetAddress() extension method` and a related Claim.

![image](https://user-images.githubusercontent.com/49577020/112879495-691ea200-90f3-11eb-9ae8-c259aefec8a1.png)
hum!~ I have followed the instructions and used GetAllClaim or FindClaim but there is no claim I have added
