### ISSUE TITLE
New packages from settings module doesn't exists in abp-nightly

### ISSUE THREAD

**Issue by ldias91** [abpframework/abp#8244]
Hi,

I tried preview versions from abp-nightly, but some packages from settings module doesn't exists.

I tried the following packages:

- Volo.Abp.SettingManagement.Application
- Volo.Abp.SettingManagement.HttpApi

The references are missing here: https://github.com/abpframework/abp/blob/137526011b288526820184cff9708e2ad1edf95d/nupkg/common.ps1#L262

**Comment by realLiangshiwei** [comment]
I will add them. thanks.
