### ISSUE TITLE
Reading appsettings.json in an ApplicationModule

### ISSUE THREAD

**Issue by bartengine27** [abpframework/abp#8248]
Dear,

  Is the following approach to read the appsettings.json config parameters in an ApplicationModule correct?

`
        public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            ConfigurationRoot config = context.ServiceProvider.GetService(typeof(IConfiguration)) as ConfigurationRoot;
            if (config != null)
            {
                var host = ((ConfigurationRoot) config).GetSection("Settings:Abp.Mailing.Smtp.Host").Value;
            }
        }
`

Thanks,
Bart

**Comment by realLiangshiwei** [comment]
`context.GetConfiguration`
https://github.com/abpframework/abp/blob/5d986892b32437de779bb09ad3e8017cd7bb6750/framework/src/Volo.Abp.AspNetCore/Volo/Abp/ApplicationInitializationContextExtensions.cs#L29
