### ISSUE TITLE
Resource file "lodash.min.js" mapping failed.

### ISSUE THREAD

**Issue by Nongzhsh** [abpframework/abp#825]
@yekalkan "lodash.min.js" is missing after running "gulp" task. Its local path is 
"…\node_modules\lodash\dist\lodash.min.js", doesn't match with [LodashScriptContributor.cs](https://github.com/abpframework/abp/blob/master/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Packages/Volo/Abp/AspNetCore/Mvc/UI/Packages/Lodash/LodashScriptContributor.cs).

**Comment by hikalkan** [comment]
Did you started with MVC startup application template? How can we repeat this?

**Comment by hikalkan** [comment]
Local path is not `node_modules\lodash\dist\lodash.min.js` in the latest lodash. It is `node_modules\lodash\lodash.min.js` in v4.17.10 and above.
What is the lodash version you're using?

Startup template uses "@abp/aspnetcore.mvc.ui.theme.basic": "^0.4.9":
https://github.com/abpframework/abp/blob/master/templates/mvc/src/MyCompanyName.MyProjectName.Web/package.json#L6

Use this version, run `yarn` and `gulp` again to align your libs folder with the framework.
