### ISSUE TITLE
ABP organizationunit adds discriminator?

### ISSUE THREAD

**Issue by MrChuJiu** [abpframework/abp#8251]
builder.Entity<OrganizationUnit>().HasDiscriminator()
Business development needs to add a discriminator to ABP organizationunit.
A strange error occurs when invoking the repository

The entity type 'OrganizationUnitRole' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
System.InvalidOperationException: The entity type 'OrganizationUnitRole' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943

```
builder.Entity <OrganizationUnit>().HasDiscriminator()
 .HasValue<AreaOrganizationUnit>(nameof(AreaOrganizationUnit))

private readonly IRepository<AreaOrganizationUnit, Guid> _organizationRepository;

```

**Comment by zhjmao** [comment]
> System.InvalidOperationException: The entity type 'OrganizationUnitRole' requires a primary key to be defined.

Identity using a different DbContext，try add
`            
            Volo.Abp.Identity.EntityFrameworkCore.
                IdentityDbContextModelBuilderExtensions.
                ConfigureIdentity(builder);`

in your DbContextModelCreatingExtensions

**Comment by MrChuJiu** [comment]
> > System.InvalidOperationException: The entity type 'OrganizationUnitRole' requires a primary key to be defined.
> 
> Identity using a different DbContext，try add
> ` Volo.Abp.Identity.EntityFrameworkCore. IdentityDbContextModelBuilderExtensions. ConfigureIdentity(builder);`
> 
> in your DbContextModelCreatingExtensions

Thank you for your reply to solve my problem

Are you Chinese?

Is it convenient to add a contact information

**Comment by zhjmao** [comment]
> > > System.InvalidOperationException: The entity type 'OrganizationUnitRole' requires a primary key to be defined.
> > 
> > 
> > Identity using a different DbContext，try add
> > ` Volo.Abp.Identity.EntityFrameworkCore. IdentityDbContextModelBuilderExtensions. ConfigureIdentity(builder);`
> > in your DbContextModelCreatingExtensions
> 
> Thank you for your reply to solve my problem
> 
> Are you Chinese?
> 
> Is it convenient to add a contact information



> > > System.InvalidOperationException: The entity type 'OrganizationUnitRole' requires a primary key to be defined.
> > 
> > 
> > Identity using a different DbContext，try add
> > ` Volo.Abp.Identity.EntityFrameworkCore. IdentityDbContextModelBuilderExtensions. ConfigureIdentity(builder);`
> > in your DbContextModelCreatingExtensions
> 
> Thank you for your reply to solve my problem
> 
> Are you Chinese?
> 
> Is it convenient to add a contact information

wechat: zhjmao
