### ISSUE TITLE
InitilizeDatabase would raise `System.InvalidOperationException: MongoClientSettings is frozen` error when I try to update MongoDB client configuration

### ISSUE THREAD

**Issue by haroldrandom** [abpframework/abp#8267]
Configure like this in `MyDbContext`
```
public override void InitializeDatabase(IMongoDatabase database, IMongoClient client, IClientSessionHandle sessionHandle)
{
    client.Settings.ClusterConfigurator += cb =>
    {
        cb.Subscribe<global::MongoDB.Driver.Core.Events.CommandStartedEvent>(e => {
            System.Console.WriteLine(new string('=', 100));
            System.Console.WriteLine($"{e.CommandName} - {e.Command.ToString()}");
        });
    };

    base.InitializeDatabase(database, client, sessionHandle);
}

```

would raise `System.InvalidOperationException: MongoClientSettings is frozen` error.

Is is a good place to Initialize?
https://github.com/abpframework/abp/blob/0c6ef9c7e25022ddb3757460b6bfe648bc8b9298/framework/src/Volo.Abp.MongoDB/Volo/Abp/Uow/MongoDB/UnitOfWorkMongoDbContextProvider.cs#L136

No matter what ways the MongoDB server starts as and try it in MongoDB 4.2, ABP 4.1.2

**Comment by haroldrandom** [comment]
why mark it as stale?

**Comment by haroldrandom** [comment]
Is ABP dead? No one here tack issue for open-source user?

**Comment by realLiangshiwei** [comment]
I will check it out.

**Comment by realLiangshiwei** [comment]
Move to https://github.com/abpframework/abp/issues/9773
