### ISSUE TITLE
Auto login (Windows Login) with LDAP

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8289]
Windows Authentication for automatic login with ABP is being asked many times.
Create an LDAP environment using docker or any other tech. Try to implement this and write an article

https://github.com/abpframework/abp/issues/5169
https://github.com/abpframework/abp/issues/3638
https://github.com/abpframework/abp/issues/1189

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/8419
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio

**Comment by jprodriguez-nbs** [comment]
Version 6.0.1 integrates openiddict. Could you please provide an example or documentation on how to modify a Volo Abp solution using OpenIdDict to use Auto Login (Windows Login) with LDAP?

**Comment by talal3000** [comment]
bump. seconding @jprodriguez-nbs question. can this work with OpenIdDict?
If a user is logged in already with Windows AD then use the current user otherwise log using a form?
