### ISSUE TITLE
Disable PropertyChangeAuditLogging when Creating/Deleting

### ISSUE THREAD

**Issue by joernz** [abpframework/abp#8295]
* Your **ABP Framework version** **4.2**
* Your database provider(EF Core/MongoDB) **EFCore**

Do we have a way to disable the PropertyChangeAuditLogging when the `EntityChangeType` is `Created`(0) or `Deleted` (2), and enable logging only for `Updated` (2)?
Creating and Deleting are just setting values from null to something or from something to null. Saving all of those requires a lot space and is kind of meaningless, especially when there is a huge amount of properties (in my case more than 200 columns). 

The EntityChangeInfo Loggings alone are sufficient while creating and deleting.

**Comment by maliming** [comment]
hi

I think we can allow disabling some audits.

**Comment by maliming** [comment]
hi

You can add a `AuditLogContributor` to remove some `EntityChangeInfo` from `AuditLogInfo`.
https://docs.abp.io/en/abp/latest/Audit-Logging#audit-log-contributors

**Comment by joernz** [comment]
hi @maliming 

I wrote an audit log contributor as you suggested. But this way it will remove `EntiyChanges` from `AuditLogInfo` entirely. 

```csharp
public class MyAuditLogContributor : AuditLogContributor
    {
        public override void PostContribute(AuditLogContributionContext context)
        {
            var entityChanges = context.AuditInfo.EntityChanges
                .Where(e => e.ChangeType == EntityChangeType.Created || e.ChangeType == EntityChangeType.Deleted)
                .ToList();

            context.AuditInfo.EntityChanges.RemoveAll(entityChanges);
         }
    }
```
I want to remove the `PropertyChanges` only, if `ChangeType` = `Created` or `Deleted`, and the rest of `EntityChanges` should remain. Can you please help? Thanks
I thougt about setting `EntityChanges` new without `PropertyChanges`, but it doesnt have setter, (`public List<EntityChangeInfo> EntityChanges { get; }`)

-------------------------------------------
BTW, the `null`s (from the Angular FormBuilder,  I figure, for example `bio: [this.selectedAuthor.bio || null]`) are saved as string in the property change log:

![image](https://user-images.githubusercontent.com/75144099/116569492-bb78fb80-a909-11eb-9722-2b005b38a534.png)

Is this something that needs to be fixed, or just me doing it wrong somehow? 

Thanks

**Comment by maliming** [comment]
You can try something like below, I think the `NULL` is a valid value.
```cs
foreach (var auditInfoEntityChange in context.AuditInfo.EntityChanges)
{
    if (auditInfoEntityChange.ChangeType == EntityChangeType.Created ||
        auditInfoEntityChange.ChangeType == EntityChangeType.Deleted)
    {
        auditInfoEntityChange.PropertyChanges.Clear();
    }

}

```
