### ISSUE TITLE
Component Not Registered Exception

### ISSUE THREAD

**Issue by mudasir-alp77** [abpframework/abp#8301]
Hi
i am making the theme by using the base of "Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Themes". When i make i all changes in my customise themes. and then i link to with my asp.net core ui in abp framework and run the project its thoroughgoing me this exception . kindly help me how i do this.
thanks

ComponentNotRegisteredException: The requested service 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Themes.Basic.Components.MainNavbar.MainNavbarViewComponent' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

![image](https://user-images.githubusercontent.com/81565733/113243293-2f54c380-92cc-11eb-8b19-58fa1b154a36.png)

**Comment by maliming** [comment]
hi

You can check this pr https://github.com/abpframework/abp/pull/8057
