### ISSUE TITLE
Permission Management By Permission

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#8309]
Hello,

For example us project structure look like

X Application (have 3 child module) => have admin role
-- Employee Management Module have **Employe Management Admin** role
-- Student Management Module have **Student Management Admin** role
-- Event Management Module have **Event Management Admin** role

admin role can manage all permissions for all application and modules no problem

but i need module level admin role and it must just control own module permissions

I thinked seprate permission-management module for all modules but identity module depended that

Do you have idea for provide that scenario?

**Comment by NecatiMeral** [comment]
Hi,
I think you can create a data seeder that seeds a role per module with admin permissions for each module.

**Comment by muratyuceer** [comment]
Yes but problem is when Module Admin open permission management page he will show all module permissions and can manipulate other modules permissions i need to prevent that just must show/change own module permissions

**Comment by cristiandmonda** [comment]
I was also wondering what would be the correct/optimal approach for this. What did you end up doing @muratyuceer ?
