### ISSUE TITLE
How to use NewtonsoftJson in the Abp.SignalR

### ISSUE THREAD

**Issue by PasuWzx** [abpframework/abp#8326]
* Your **ABP Framework version**. v4.2
* Your **User Interface** type MVC
* Your database provider(EF Core/MongoDB) EfCore

` PreConfigure<ISignalRBuilder>(options =>
            {
                options.AddNewtonsoftJsonProtocol();
            });`

 I use it as above, but it's not work

**Comment by maliming** [comment]
Can you try this?

`context.Services.AddSignalR().AddNewtonsoftJsonProtocol();`
