### ISSUE TITLE
Just installed 4.3rc1 commercial can’t navigate to page

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#8328]
Just installed 4.3rc1 commercial 
and tried to create a page and navigate to it not working page cannot be found CMS module

**Comment by realLiangshiwei** [comment]
Hi,

Are you talking about the open source CMS module?

**Comment by vnetonline** [comment]
> Hi,
> 
> 
> 
> Are you talking about the open source CMS module?

No I am talking about the commercial module under the CMS menu item when I go in there I create a pages test and try and navigate to /pages/test and it goes no where page not found

**Comment by realLiangshiwei** [comment]
We are not discussing the commercial version here.  please create a question on the support website: https://support.abp.io/QA/Questions.
If this is a problem, we will return your ticket. thanks.
