### ISSUE TITLE
Can't add Basic Theme to Solution (Blazor Server)

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#8330]
ABP Framework version 4.3.0-rc.1
Blazor Server
EF Core

Steps: 

* `abp new Qa -u blazor-server --mobile none --database-provider ef-csf --preview -t app`
* `abp add-package Volo.Abp.AspNetCore.Components.Web.BasicTheme --with-source-code --add-to-solution`

Trying to add the Basic Theme's source code into my solution. The following code ran fine, created a new folder called **packages** and installed the source code

abp add-package Volo.Abp.AspNetCore.Components.Server.BasicTheme --with-source-code --add-to-solution

I then ran the following 

abp add-package Volo.Abp.AspNetCore.Components.Web.BasicTheme --with-source-code --add-to-solution

but this gave the following error: **couldn't find any project/solution**

![image](https://user-images.githubusercontent.com/69393775/113323101-7a42fb00-930d-11eb-9902-e8798ffbefd9.png)

**Comment by yekalkan** [comment]
Hi @DonVliet 

Try running the same command in Blazor project directory.

**Comment by DonVliet** [comment]
@yekalkan

If I run in the Blazor directory I get the following error:

$ abp add-package Volo.Abp.AspNetCore.Components.Web.BasicTheme --with-source-code --add-to-solution
[11:31:06 INF] ABP CLI (https://abp.io)
[11:31:07 INF] Version 4.3.0-rc.1 (Prerelease)
[11:31:08 INF] Installing 'Volo.Abp.AspNetCore.Components.Web.BasicTheme' package to the project 'TESTING.Blazor'...

[11:31:20 ERR] appsettings file could not be found. Path:C:\Projects\TESTING\src\TESTING.Blazor\wwwroot\appsettings.json
System.IO.FileNotFoundException: appsettings file could not be found. Path:C:\Projects\TESTING\src\TESTING.Blazor\wwwroot\appsettings.json

**Comment by DonVliet** [comment]
@yekalkan @realLiangshiwei

ok that worked when the project name was TESTING but if I call the project MYCOMPANY.TESTING I get another error:

**ERR] appsettings file could not be found. Path:C:\Projects\TESTING\src\MYCOMPANY.TESTING.Blazor\wwwroot\appsettings.json**

![image](https://user-images.githubusercontent.com/69393775/113566570-d905be80-9604-11eb-93ae-212a19778800.png)

**Comment by yekalkan** [comment]
@DonVliet

You can run it again. It throws error on first time but works on the second.

This is a known issue and will be fixed in 4.3.0-rc.2 version.

**Comment by DonVliet** [comment]
@yekalkan

It worked on the second attempt but now I get compile errors:

![image](https://user-images.githubusercontent.com/69393775/113626892-9ff83900-965a-11eb-960b-c1cbdd5b7df3.png)

I think I'll wait until all the problems are fixed - hopefully in rc.2 - thanks for your help.
