### ISSUE TITLE
ASP.NET Core 3.0？

### ISSUE THREAD

**Issue by AlseinX** [abpframework/abp#834]
ASP.NET Core 3.0 uses GenericWebHostBuilder and completely different Startup resolving.
Is there any support for it?

**Comment by maliming** [comment]
As far as I know, ASP.NET Core 3.0 has not been officially released yet.

**Comment by AlseinX** [comment]
But this framework is not officially released as well is'nt it
As long as the API and configuration is basically what it is, I do think it necessary to consider about it.

**Comment by hikalkan** [comment]
We hadn't time to work on ASP.NET Core 3.0 changes yet. I think we have time :)

**Comment by xyfy** [comment]
core 3.0 is coming soon.
https://www.dotnetconf.net/?utm_source=dotnet&utm_medium=banner&utm_campaign=savedate
Are you ready? 
I have a greet interested in the ABP next using core 3.0
Hahaha~~~

**Comment by hikalkan** [comment]
We are getting ready :) ABP v1.0 will be based on ASP.NET Core 3.0.
