### ISSUE TITLE
UserLookupService gets different results using MongoDB or EntityFrameworkCore implementations on the first call

### ISSUE THREAD

**Issue by WWMLee** [abpframework/abp#8343]
* abp Framework version 4.2.2

**First Call** 
MongoDb implementations is null
EntityFrameworkCore implementations is right

two lines may have caused the problem
https://github.com/abpframework/abp/blob/710d9e0182a163b88fab53881310fc5964e67fbb/modules/users/src/Volo.Abp.Users.Domain/Volo/Abp/Users/UserLookupService.cs#L73
https://github.com/abpframework/abp/blob/710d9e0182a163b88fab53881310fc5964e67fbb/modules/users/src/Volo.Abp.Users.Domain/Volo/Abp/Users/UserLookupService.cs#L74

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by WWMLee** [comment]
The "MnsUser" is implemented in the same way as "CmsUser".
If "MnsUserrepository" is implemented  using "Volo.Abp.Users.MongoDB", when there is no user with given id in "MnsUser" table
Call "UserLookupService.GetByIdAsync" Method will throw "EntityNotFoundException" in "Applicationservice".
A user data is inserted into the "MnsUser" table.
If "MnsUserrepository" is implemented using "Volo.Abp.Users.EntityFrameworkCore" will get right results.
A user data is also inserted into the "MnsUser" table.

> The given user id exists in the "IdentityUser" table.
> "IExternalUserLookupServiceProvider.FindByIdAsync" method executed successfully, using the implementation of "HttpClientExternalUserLookupServiceProvider". (call remote HTTP services)

Similar call:
https://github.com/abpframework/abp/blob/3c35bce82e5b646cc3f59fb74882a31803e4c37c/modules/cms-kit/src/Volo.CmsKit.Admin.Application/Volo/CmsKit/Admin/Blogs/BlogPostAdminAppService.cs#L39
