### ISSUE TITLE
Configure Single Sign Out for the MicroService demo

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#835]

**Comment by brunobertechini** [comment]
@hikalkan regarding this issue, do you intend to implement the sign-out callback and federated signout of IdentityServer? 

- Federated Signout: http://docs.identityserver.io/en/latest/topics/signout_federated.html
- SignOut Async: http://docs.identityserver.io/en/latest/topics/signout.html

If you have more details I can help you with that

Bruno

**Comment by hikalkan** [comment]
Thanks @brunobertechini I request for help if needed :)

**Comment by hikalkan** [comment]
Hi @brunobertechini it would be appreciated if you can help more on that :) You can send a PR or write some details of implementation here. Thanks a lot.

**Comment by brunobertechini** [comment]
@hikalkan I will have a look on current implementation in the MS Demo and get back to you

**Comment by danghung-dev** [comment]
@hikalkan @brunobertechini Do we have any update for this ? Thanks

**Comment by brunobertechini** [comment]
Hi there, I didn't have chance to continue with this at that time. So many personal things going on :)

I can refresh my knowledge with current implementation and try to see if I can help.

But @hikalkan will be your best shot :)
