### ISSUE TITLE
Blazor Project missing when generating new Blazor Server Application

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#8365]
* Your **ABP Framework version** - 4.3.0-rc.1
* Your **User Interface** type (Angular/MVC/React... etc.) Blazor Server
* Your database provider(EF Core/MongoDB) - EFCore

Tried to create a new **Blazor Server** application using following parameters:

![image](https://user-images.githubusercontent.com/69393775/113454587-8491f180-9400-11eb-9a8a-e4b38154f910.png)

When I opened the zip, there's no Blazor project in the solution (this was working yesterday).

![image](https://user-images.githubusercontent.com/69393775/113454686-b1de9f80-9400-11eb-9d81-1671a1fc4cc8.png)

**Comment by maliming** [comment]
Thanks, We will fix that.

**Comment by DonVliet** [comment]
Hi @maliming - you say "added this to the 4.3-final milestone" Does that mean we can't create Blazor Server projects until 4.3 final is released?

I tried using the cli but that doesn't work either:

**abp new TESTING -u blazor-server**

**Comment by yekalkan** [comment]
@DonVliet 

`abp new TESTING -u blazor-server --preview` should work.

We're fixing `abp.io/get-started` in a few hours.

**Comment by DonVliet** [comment]
> @DonVliet
> 
> `abp new TESTING -u blazor-server --preview` should work.
> 
> We're fixing `abp.io/get-started` in a few hours.

@yekalkan  Thank you very much 🥇
