### ISSUE TITLE
Separate blog admin application and public application

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#837]
Create separated application & web layers those share the same domain. Similar separation was implemented for the docs module.

**Comment by leonkosak** [comment]
Is "public page" in your development pipeline?

**Comment by hikalkan** [comment]
If you are asking for the startup template, not planned yet, but probably will be in the road map. However, you can do it yourself, it will be an almost empty web application.

**Comment by leonkosak** [comment]
It sounds logical. So something similar functionality as Public Web Site for ANZ (https://docs.aspnetzero.com/en/aspnet-core-angular/latest/Public-Website)?
