### ISSUE TITLE
Redis Config dosen't work correctly

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#8372]
You can check 'IsEnabled' parameter. 

 "Redis": {
    "IsEnabled": "false"
  },

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by recruitans** [comment]
v4.2.2, MVC, EF

you can check like this : 
1. Create project with abp suite. 
2. publish on azure app service
3. Go to site . dosen't work
4. Add "IsEnabled": "false" on prod appsettings file.
5. Again step 2.
6. Go to site . dosen't work. 
7. remove (or comment) 'ConfigureRedis(context, configuration, hostingEnvironment);' in xxxWebModule.cs
8. Again step 2.
9. Go to site . App is work.

**Comment by realLiangshiwei** [comment]
Can't reproduce
