### ISSUE TITLE
Revisit the microservice demo solution

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8385]
We will work on the [microservice demo solution](https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo) to apply the experience we've gained while building the [microservice starter template](https://docs.abp.io/en/commercial/latest/startup-templates/microservice/index) for the ABP Commercial.
It will probably a re-write the solution and the related documentation.
We are considering to create a solution like *eShopOnAbp* :)

**Comment by volethanh** [comment]
Waiting for this re-work on 4.4

**Comment by volethanh** [comment]
> We will work on the [microservice demo solution](https://docs.abp.io/en/abp/latest/Samples/Microservice-Demo) to apply the experience we've gained while building the [microservice starter template](https://docs.abp.io/en/commercial/latest/startup-templates/microservice/index) for the ABP Commercial.
> It will probably a re-write the solution and the related documentation.
> We are considering to create a solution like _eShopOnAbp_ (smiley)

I've tried the microservice for ABP Commercial. Because the Shared project is referenced to each microservice. And I use AWS CodeCommit + CodeBuild to build to ECR and load to ECS. It means that the aws codecommit is the repository for storing sourcecode, I want to separate each service to different repository and I've stuck when add shared project. Is there any solution for that ?

**Comment by hitaspdotnet** [comment]
@volethanh Create your repositories with child repositories

**Comment by mooresway** [comment]
eShopOnAbp (or something similar) sounds great!

Would make great reference on practical real world usage for many topics...

**Comment by radrad** [comment]
Is there a github project where this is being developed?

**Comment by hikalkan** [comment]
@volethanh just duplicate the code in shared projects. Shared projects are used to re-use some configuration code. Just copy the code (including dependencies) into the related microservice to make it independent from the shared projects.

**Comment by mooresway** [comment]
Excited to see eShopOnAbp is happening!
https://blog.abp.io/abp/Introducing-the-eShopOnAbp-Project
https://github.com/abpframework/eShopOnAbp

Thanks @enisn, @hikalkan, @gterdem... looking forward to seeing this come to life and learning from it. No doubt it will help bring more developers to Abp as well.

**Comment by hitaspdotnet** [comment]
@hikalkan What about renaming projects by namespaces, 
```
CompanyName.ProjectName.Services.ServiceName
CompanyName.ProjectName.Gateways.GatewayName
CompanyName.ProjectName.Apps.AppName
```
Microservice template's tye needs more code review to be clean code same as other ABP objects

**Comment by gterdem** [comment]
> @hikalkan What about renaming projects by namespaces,
> 
> ```
> CompanyName.ProjectName.Services.ServiceName
> CompanyName.ProjectName.Gateways.GatewayName
> CompanyName.ProjectName.Apps.AppName
> ```
> 
> Microservice template's tye needs more code review to be clean code same as other ABP objects

If I remember correctly, we had to trim because of windows line limit (or something like that, I forgot the exact error); had so long folders and file names that failed to build.

**Comment by hikalkan** [comment]
We will go with individual issues.
