### ISSUE TITLE
[Question]How to disable background job sql log?

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#8387]
I set EntityframeworkCore Log level to Debug, but the background job log also shows. I only want to show business sql log , so what I should do?
![屏幕截图 2021-04-05 133819](https://user-images.githubusercontent.com/19605145/113541377-ab287600-9614-11eb-83c6-8fdfa4719370.png)
![屏幕截图 2021-04-05 134010](https://user-images.githubusercontent.com/19605145/113541379-ad8ad000-9614-11eb-9d96-0382bf00f172.png)

**Comment by gterdem** [comment]
We're using default [.Net Core Logging system](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0). 

If you want to separate the hangfire logs, can you try checking [configure hangfire logging](https://docs.hangfire.io/en/latest/configuration/configuring-logging.html)?
