### ISSUE TITLE
Documentation updates on various topics

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8414]
I've planned a cumulative documentation update and writing here as a todo list;

- [x] `Databases` collection of `AbpDbConnectionOptions`
- [x] DBMS configuration (like options.UseSqlServer()) can be explained in the EF Core main document too.
- [x] Data annotation validation localization for Mvc / Blazor UI (especially regex and custom attributes)
- [x] Update [here](https://docs.abp.io/en/abp/4.0/Customizing-Application-Modules-Extending-Entities#subscribing-to-distributed-events) since now all modules have ETOs.
- [x] How to override a repository, in the customization document
- [x] DI multiple service registration & resolution
- [x] https://docs.abp.io/en/abp/4.3/Entity-Framework-Core-Other-DBMS (we have -dbms option, but didn't mention it here)
- [x] How to query from dbcontext and use UOW in integration tests (we can also add some example to the startup template)

**Comment by sturlath** [comment]
Just checking on this "Update here since now **all** modules have ETOs." 

> This feature is on the road map and will be available in a short term (follow this issue). Once it is implemented, you will be able to subscribe to individual entity types. 

I just tried the 4.4-rc1 version and cant find `IdentityUserEto` anywhere. Will it not be included/published?

**Comment by realLiangshiwei** [comment]
@sturlath 

Use `UserEto`. see https://github.com/abpframework/abp/pull/3210

**Comment by sturlath** [comment]
I will then need to map between `UserEto` and `Identity`, correct?
![image](https://user-images.githubusercontent.com/2386572/124459057-4698c680-dd7d-11eb-9f66-37b07589fb7e.png)

Something like this? Is there a better way?

```csharp
public async Task HandleEventAsync(EntityCreatedEto<UserEto> eventData)
{

        var identityUser = new IdentityUser(eventData.Entity.Id,eventData.Entity.Email,eventData.Entity.TenantId.GetValueOrDefault().ToString());
        identityUser.Name = eventData.Entity.Name;
        //etc

        await identityUserManager.AddToRoleAsync(identityUser, "OrdinaryClientRole");
}
```
