### ISSUE TITLE
Features and permissions

### ISSUE THREAD

**Issue by erojasd** [abpframework/abp#8415]
Hello,
Would it be feasible to enable certain permissions only if a feature is enabled?
I have read the documentation and have not found anything clear about whether this is feasible

Thanks a lot

**Comment by gterdem** [comment]
The permissions of that feature should already be non-visible if the feature is disabled and visible if the feature is enabled. Did you experience otherwise?

Can you give more details about your case?

**Comment by erojasd** [comment]
How do i associate permissions to a feature?
My problem is that I can't find a way to associate permissions with features.

Thanks: D

**Comment by muratyuceer** [comment]
look #8309 and #8518
