### ISSUE TITLE
After adding two extraproperties to abpuser. the createuser api throws wired exception

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#8417]
Hi there, I meet a wired issue.
ABP Framework version 4.2.2
EF Core
 api route:
> /api/identity/users/  

Request arguments
![image](https://user-images.githubusercontent.com/19605145/113663109-083b2f00-96dc-11eb-964f-9c37bb5364de.png)
AbpUser extension
![image](https://user-images.githubusercontent.com/19605145/113663126-11c49700-96dc-11eb-84c2-7d140935d6d9.png)
DtoExtension
![image](https://user-images.githubusercontent.com/19605145/113663128-1426f100-96dc-11eb-8d26-4f20c709d44c.png)
EFCore Map
![image](https://user-images.githubusercontent.com/19605145/113663132-16894b00-96dc-11eb-8af6-01055e4e6460.png)
Database table
![image](https://user-images.githubusercontent.com/19605145/113663624-f1490c80-96dc-11eb-9fda-7726b146c959.png)
these two fields have been added to the table.
Exceptions
![image](https://user-images.githubusercontent.com/19605145/113663706-15a4e900-96dd-11eb-952f-5a75221cf9a5.png)
When I request this api, It throws 'The CompanyId field is required.' exception. But I have already added companyId field in request arguments. It's so wired.

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/issues/5927

**Comment by trickyrat** [comment]
Hi, @realLiangshiwei 
I followed your suggestions, but it still throws same exception.

![image](https://user-images.githubusercontent.com/19605145/113665374-f491c780-96df-11eb-8139-026992b21b64.png)

**Comment by trickyrat** [comment]
Hi, @realLiangshiwei 
I followed your suggestions, but it still throws same exception.

![image](https://user-images.githubusercontent.com/19605145/113665374-f491c780-96df-11eb-8139-026992b21b64.png)

**Comment by trickyrat** [comment]
Hi, @realLiangshiwei 
I followed your suggestions, but it still throws same exception.

![image](https://user-images.githubusercontent.com/19605145/113665374-f491c780-96df-11eb-8139-026992b21b64.png)

**Comment by realLiangshiwei** [comment]
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem. (share code, please.)

**Comment by trickyrat** [comment]
@realLiangshiwei 
[demo](https://github.com/trickyrat/ngdemo)
