### ISSUE TITLE
Publish Failed! Self-contained deploy - "It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier"

### ISSUE THREAD

**Issue by marcelo-maciel** [abpframework/abp#842]
When i tried to publish a self contained app (default 0.14 download) i got these messages:

![image](https://user-images.githubusercontent.com/4993482/53313240-3b712a00-3897-11e9-9b14-f5af9b64467d.png)

> Severity	Code	Description	Project	File	Line	Suppression State
Error		It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false.	Acme.BookStore.Web	C:\Program Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets	116	

Log:

> 25/02/2019 00:48:44
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

My settings:
![image](https://user-images.githubusercontent.com/4993482/53313344-bfc3ad00-3897-11e9-8bfe-1d92e241ada5.png)

![image](https://user-images.githubusercontent.com/4993482/53313460-36f94100-3898-11e9-827c-85763f9efff8.png)

**Comment by hikalkan** [comment]
Are you sure that this is related to ABP framework? Normally, publishing should not be related to it.

**Comment by marcelo-maciel** [comment]
I'm using the last SDK 2.2.104

**Comment by hikalkan** [comment]
I haven't tried. For you, the same setup works for a project without ABP?

**Comment by marcelo-maciel** [comment]
Yes, a new project works, but I've found some differences. I'll test some more.

**Comment by marcelo-maciel** [comment]
You can try?

**Comment by yekalkan** [comment]
When i try, i am getting the same error. To prevent this error, "MvcRazorCompileOnPublish" should be set to false in csproj file.

However, i created an empty project on visual studio and get the same error when i set `<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>` configration. So i don't think this is related to ABP.

![image](https://user-images.githubusercontent.com/5793291/53338142-035bfc80-3914-11e9-9dda-a1268ea06c45.png)

**Comment by marcelo-maciel** [comment]
@yekalkan you are using SDK 2.2.104 right?
I readed on docs link above that MvcRazorCompileOnPublish will be depreated on 3.0
[https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.2](url)

> The precompilation tool will be removed in ASP.NET Core 3.0. We recommend migrating to Razor Sdk.

> For instance, setting the .csproj file's MvcRazorCompileOnPublish property to **true** disables the Razor SDK.

Then i think that MvcRazorCompileOnPublish **false** is the correct way right?
