### ISSUE TITLE
Forgot password email link misses domain part

### ISSUE THREAD

**Issue by williamiwell** [abpframework/abp#8437]
* ABP version: 4.3-rc1 commercial
* UI: Angular/MVC
* Database provider: MongoDB
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

1. open login page
2. click forgot password
3. enter email and submit
4. email contains link without domain part: http://account/ResetPassword?userId=xx&tenantId=&resetToken=xx&returnUrl=https://xx.azurewebsites.net

**Comment by maliming** [comment]
Does your app have the below code?
```
Configure<AppUrlOptions>(options =>
{
    options.Applications["MVC"].RootUrl = configuration["App:SelfUrl"];
});
```

**Comment by williamiwell** [comment]
thanks for the quick reply. Yes, the app has that configuration code. However it was not set, so it make sense that it was not working. I've added that to the appsettings and now it's working as expected. It was part of the initial appsettings.json of the abp template, but I must have overlooked it.
