### ISSUE TITLE
EmailSender.SendAsync hangs/times out when secure connection is used

### ISSUE THREAD

**Issue by williamiwell** [abpframework/abp#8438]
ABP version: 4.3-rc1 commercial
UI: Angular/MVC
Database provider: MongoDB

Email Configuration: 
    "Abp.Mailing.Smtp.Host": "smtp.sendgrid.net",
    "Abp.Mailing.Smtp.Port": "465",
    "Abp.Mailing.Smtp.UserName": "apikey",
    "Abp.Mailing.Smtp.Password": "encrypted password",
    "Abp.Mailing.Smtp.Domain": "",
    "Abp.Mailing.Smtp.EnableSsl": "true",
    "Abp.Mailing.Smtp.UseDefaultCredentials": "false",

Steps needed to reproduce the problem.
1. open login page
2. click forgot password
3. enter email and submit
4. browser hangs and times out after x minutes. Via debugger I see that its waiting for EmailSender.SendAsync
5. changing Abp.Mailing.Smtp.Port to 587 and Abp.Mailing.Smtp.EnableSsl to false
6. sending email works

**Comment by maliming** [comment]
hi

I think it is a problem of **SmtpClient** , You can try to use [MailKit](https://docs.abp.io/en/abp/latest/MailKit).

https://stackoverflow.com/questions/53747987/smtpclient-send-gets-stuck?answertab=active#tab-top
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/Smtp/SmtpEmailSender.cs#L74

**Comment by williamiwell** [comment]
Using mailkit resolves this issue indeed.
