### ISSUE TITLE
How to scan assemblies for AutoMapper profiles?

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#844]
Hi,

I realise it is possible to add profiles by hand:

```c#
Configure<AbpAutoMapperOptions>(options =>
{
   options.AddProfile<AgentApiApplicationAutoMapperProfile>();
});
```

However is it possible to do the assembly scanning approach http://docs.automapper.org/en/stable/Configuration.html#assembly-scanning-for-auto-configuration

**Comment by hikalkan** [comment]
I will consider this. Thank you for your offer.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/1705
