### ISSUE TITLE
How to use Volo.Abp.Identity with JwtBearer

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#845]
I want to use both JwtBearer and cookie auth in my abp web application.
I can't add [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]  because it is a abp module, not mine.
What can i do?

            var vv =
            context.Services
            .AddAuthentication(o =>
            {
               o.DefaultScheme = IdentityConstants.ApplicationScheme;
                o.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                //o.DefaultScheme = IdentityConstants.ApplicationScheme;
                //o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
            })
            .AddJwtBearer(o =>
            {
                ......
            }
           vv.AddApplicationCookie();

**Comment by gdlcf88** [comment]
Thanks a lot for your solution. 👍

**Comment by gdlcf88** [comment]
It works in my local PC development env(returns 401 if I have no authorization), but when I publish it to linux production env, apis still return 302 and redirect to an error page. Do you know what makes the difference? @yekalkan 

By the way, I cannot set `.AddAuthentication("Bearer")` in mvc template, or login will be broken just like https://github.com/abpframework/abp/issues/2536 (returns to home page with no authorization)

**Comment by abdumostafa** [comment]
> It works in my local PC development env(returns 401 if I have no authorization), but when I publish it to linux production env, apis still return 302 and redirect to an error page. Do you know what makes the difference? @yekalkan
> 
> By the way, I cannot set `.AddAuthentication("Bearer")` in mvc template, or login page will be broken just like #2536 (returns to home page with no authorization)

@gdlcf88  Did you manage to solve this issue in production with linux?
