### ISSUE TITLE
Docs preview 4.3 Blazor/EFCore : IAuthorRepository does not contain a definition for CountAsync()

### ISSUE THREAD

**Issue by bartvanhoey** [abpframework/abp#8450]
Tutorial, Part 8: Authors: Application Layer -> method GetListAsync

IAuthorRepository' does not contain a definition for 'CountAsync' and no accessible extension method 'CountAsync' accepting a first argument of type 'IAuthorRepository' could be found (are you missing a using directive or an assembly reference?) 

public async Task<PagedResultDto<AuthorDto>> GetListAsync(GetAuthorListDto input)
{
   // other code here ...

    var totalCount = input.Filter == null
        ? await _authorRepository.CountAsync()
        : await _authorRepository.CountAsync(
            author => author.Name.Contains(input.Filter));
}

**abp**

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Repositories/RepositoryAsyncExtensions.cs#L62
