### ISSUE TITLE
Repository WithDetails() function need ThenInclude() function

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#846]
Repository WithDetails() function need ThenInclude() function in "many to many" scene

**Comment by hikalkan** [comment]
WithDetails is implemented per entity, so you can use ThenInclude for your entity. Can you explain a bit more?

**Comment by Goxiaoy** [comment]
@hikalkan ThenInclude function is useful in many-to-many entity. Considering for user and role, if i want to query user repository with all of their role name.
```

IRepository<User> userRepository...
userRepository.WithDetail(p=>p.User2Role).ThenWithDetail(p=>p.Role)

```

**Comment by hikalkan** [comment]
Will document WithDetails's usage. Then we see if we need to support additional scenarios.

**Comment by Rwing** [comment]
So what's the conclusion? Otherwise we need reference the EntityFrameworkCore in application layer.

**Comment by hikalkan** [comment]
For now, go with referencing the Volo.Abp.EntityFrameworkCore package to your application layer since at first look it doesn't fit to a generic repository interface. If we implement it later, you replace your code if you like.

**Comment by carsonlaw** [comment]
referencing the Volo.Abp.EntityFrameworkCore package to application layer and then how to do that?

**Comment by Goxiaoy** [comment]
> referencing the Volo.Abp.EntityFrameworkCore package to application layer and then how to do that?

Use Include in EF Core to load navigation property

```
IRepository<User> userRepository...
userRepository.Include(p=>p.User2Role).ThenInclude(p=>p.Role)
```

**Comment by bigsergoya** [comment]
Any updates?

**Comment by cloud0259** [comment]
@hikalkan Is it now possible to use WithDetailsAsync without referencing EntityFrameworkCore in the application layer?

**Comment by hikalkan** [comment]
https://docs.abp.io/en/abp/7.3/Entity-Framework-Core#defaultwithdetailsfunc
