### ISSUE TITLE
How get json string from application services 

### ISSUE THREAD

**Issue by mansai** [abpframework/abp#8465]
abp vnext4.3
![image](https://user-images.githubusercontent.com/3213405/113835494-97207800-97be-11eb-8854-52ad27047f03.png)

`string json = string.Empty;
            using (StreamReader sr = new StreamReader(_httpContext.HttpContext.Request.Body))
            {
                json = sr.ReadToEnd();
            }`
![image](https://user-images.githubusercontent.com/3213405/113836356-65f47780-97bf-11eb-8173-e2df966056ed.png)
![image](https://user-images.githubusercontent.com/3213405/113836599-9b996080-97bf-11eb-8ee6-db3e34b676ef.png)

**Comment by gterdem** [comment]
HttpContext is related to Web layer, not application service layer. You can always pass de-serialized object to application layer though.

I suppose you can also add **Microsoft.AspNetCore.Http** package to Application layer if you have to. So that you can inject `IHttpContextAccessor`.

**Comment by mansai** [comment]
Inject IHttpContextAccessor
![image](https://user-images.githubusercontent.com/3213405/114861296-a4251300-9e1f-11eb-9b37-8bede4b73290.png)
![image](https://user-images.githubusercontent.com/3213405/114861350-b8691000-9e1f-11eb-9a79-41ed47842140.png)
![image](https://user-images.githubusercontent.com/3213405/114861408-d171c100-9e1f-11eb-905e-51dd6456cfa8.png)

It's still empty

**Comment by gterdem** [comment]
It is because you are sending parameter in the **query** and trying to read from **body**.

Postman request:
![request](https://user-images.githubusercontent.com/25867/114872417-ff94d800-9e02-11eb-97ea-27439826d95f.png)

App service:
![result](https://user-images.githubusercontent.com/25867/114872516-189d8900-9e03-11eb-9b7a-e05fc95fa782.png)

**Comment by mansai** [comment]
![image](https://user-images.githubusercontent.com/3213405/114993452-6af7ac00-9ece-11eb-849f-92f187df5921.png)

![image](https://user-images.githubusercontent.com/3213405/114992400-4a7b2200-9ecd-11eb-93e5-03b8fdfea0bd.png)
The problem is that the input parameter is Dto,How to solve it?
