### ISSUE TITLE
extending services

### ISSUE THREAD

**Issue by baobeiboboda** [abpframework/abp#8512]
after reading the document about extending DTO and override Services(https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services)
I still have some questions about How to extending a Services Class,such as User ,I can override it,but  how to extend it.

**Comment by gterdem** [comment]
You can check [Object Extensions Documentation](https://docs.abp.io/en/abp/latest/Object-Extensions) to see how to extend objects in general. Sample is IdentityUser.

**Comment by baobeiboboda** [comment]
> You can check [Object Extensions Documentation](https://docs.abp.io/en/abp/latest/Object-Extensions) to see how to extend objects in general. Sample is IdentityUser.

thank you, I Know how to extend Dto such as AppUser 
I'd like to know how to extend a Service Class For example api/identity/users/findbyemail I want add a function in User Api

**Comment by gterdem** [comment]
> > You can check [Object Extensions Documentation](https://docs.abp.io/en/abp/latest/Object-Extensions) to see how to extend objects in general. Sample is IdentityUser.
> 
> thank you, I Know how to extend Dto such as AppUser
> I'd like to know how to extend a Service Class For example api/identity/users/findbyemail I want add a function in User Api

Is this what you are looking for https://github.com/abpframework/abp/issues/7721?

**Comment by baobeiboboda** [comment]
> > > You can check [Object Extensions Documentation](https://docs.abp.io/en/abp/latest/Object-Extensions) to see how to extend objects in general. Sample is IdentityUser.
> > 
> > 
> > thank you, I Know how to extend Dto such as AppUser
> > I'd like to know how to extend a Service Class For example api/identity/users/findbyemail I want add a function in User Api
> 
> Is this what you are looking for #7721?

after reading 
Duplicate of #7721 , I found #7766 ,I added IncludeSelf = true in ExposeServices, but I still can't find the extend function
![无标题](https://user-images.githubusercontent.com/12625368/114067132-0d140480-98cf-11eb-944f-91432c346323.png)

**Comment by gterdem** [comment]
You can extend the interface first:
                
    public interface IMyIdentityUserAppService: IIdentityUserAppService
        


Then inherit from interface and extend the class:
                
    public class MyIdentityUserAppService: IdentityUserAppService, IMyIdentityUserAppService
        
And expose the services:

    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(IMyIdentityUserAppService),typeof(IIdentityUserAppService), typeof(IdentityUserAppService), typeof(MyIdentityUserAppService))]      
    public class MyIdentityUserAppService: IdentityUserAppService, IMyIdentityUserAppService

**Comment by baobeiboboda** [comment]
> You can extend the interface first:
> 
> ```
> public interface IMyIdentityUserAppService: IIdentityUserAppService
> ```
> 
> Then inherit from interface and extend the class:
> 
> ```
> public class MyIdentityUserAppService: IdentityUserAppService, IMyIdentityUserAppService
> ```
> 
> And expose the services:
> 
> ```
> [Dependency(ReplaceServices = true)]
> [ExposeServices(typeof(IMyIdentityUserAppService),typeof(IIdentityUserAppService), typeof(IdentityUserAppService), typeof(MyIdentityUserAppService))]      
> public class MyIdentityUserAppService: IdentityUserAppService, IMyIdentityUserAppService
> ```
Thx
I tried it 

 But it doesn't work
![无标题](https://user-images.githubusercontent.com/12625368/114149856-f19c0e80-994d-11eb-926e-5d624e96f52f.png)
![无标题1](https://user-images.githubusercontent.com/12625368/114149892-fb257680-994d-11eb-90f7-1fd9a70732a0.png)

**Comment by gterdem** [comment]
Did you extend ApiController aswell?

**Comment by baobeiboboda** [comment]
> extend ApiController

sorry I didn't, I've search the Issue and the document,But I don't know how to extend ApiController

**Comment by baobeiboboda** [comment]
> Did you extend ApiController aswell?

sorry I didn't, I've search the Issue and the document,But I don't know how to extend ApiController

**Comment by gterdem** [comment]
Like:

        [Dependency(ReplaceServices = true)]
        [ExposeServices(typeof(IdentityUserController))]
        public class MyIdentityUserController : IdentityUserController, IMyIdentityUserAppService
        {
        public MyIdentityUserController(IMyIdentityUserAppService userAppService) : base(userAppService)
        {
        }

Also docs about [Overriding Controller](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller).

**Comment by baobeiboboda** [comment]
> Like:
> 
> ```
>     [Dependency(ReplaceServices = true)]
>     [ExposeServices(typeof(IdentityUserController))]
>     public class MyIdentityUserController : IdentityUserController, IMyIdentityUserAppService
>     {
>     public MyIdentityUserController(IMyIdentityUserAppService userAppService) : base(userAppService)
>     {
>     }
> ```
> 
> Also docs about [Overriding Controller](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller).

I tried it but it doesn't work

![无标题](https://user-images.githubusercontent.com/12625368/114507289-83b15900-9c65-11eb-8e52-08d72f3250bd.png)

**Comment by baobeiboboda** [comment]
> Like:
> 
> ```
>     [Dependency(ReplaceServices = true)]
>     [ExposeServices(typeof(IdentityUserController))]
>     public class MyIdentityUserController : IdentityUserController, IMyIdentityUserAppService
>     {
>     public MyIdentityUserController(IMyIdentityUserAppService userAppService) : base(userAppService)
>     {
>     }
> ```
> 
> Also docs about [Overriding Controller](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller).

I tried it but it doesn't work

**Comment by baobeiboboda** [comment]
> Like:
> 
> ```
>     [Dependency(ReplaceServices = true)]
>     [ExposeServices(typeof(IdentityUserController))]
>     public class MyIdentityUserController : IdentityUserController, IMyIdentityUserAppService
>     {
>     public MyIdentityUserController(IMyIdentityUserAppService userAppService) : base(userAppService)
>     {
>     }
> ```
> 
> Also docs about [Overriding Controller](https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Overriding-Services#example-overriding-a-controller).

i tried it but it doesn't work
