### ISSUE TITLE
Add restriction to permissions

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8518]
Add `FeatureName` and `GlobalFeatureName` properties to `PermissionDefinition`.

* Check feature name from `IFeatureChecker`. If it returns false, `PermissionChecker` should return false when we check IsGranted for this permission. Also, `PermissionAppService.GetAsync` should not return this permission in the returning list.
* Check the global feature name from `GlobalFeatureManager`. If it returns false, `PermissionChecker` should return false when we check IsGranted for this permission. Also, `PermissionAppService.GetAsync` should not return this permission in the returning list.

You should also care this on PermissionManager.

Hint: Find usages of `PermissionDefinition.IsEnabled`. You typically mostly changes is same places for checking.

**Comment by maliming** [comment]
What if I want to add other checks in the future? Add more properties to the **PermissionDefinition**?

We can abstract it, and developers can customize a service to deciding whether this **permission** is enabled.


**Feature-management** provides a check service, and **GlobalFeatures** also provides it.


Use case:
Users with the **manager** role can only manage some permissions but not all. I can disable some permissions based on the current user role.

**Comment by NecatiMeral** [comment]
The use case @maliming is describing is kinda equal to #8309.

**Comment by hikalkan** [comment]
@maliming `PermissionDefinition` has a `Properties` dictionary as an extension point. Instead of adding `string RequiredFeature ` property to the `PermissionDefinition`, we can create an extension point like `PermissionDefinition.RequireFeature(string featureName)` which internally adds the feature name to the `Properties` dictionary.

Then you can define an interface, like `IPermissionFilterProvider`* that has a `bool FilterAsync(PermissionDefinition permission)` method. We can then implement RequireFeaturePermissionFilterProvider that gets the feature name from the `Properties` dictionary and returns `false` if current tenant has no feature.
We accept multiple `IPermissionFilterProvider` implementations, like other contribution systems.

What about such a design?

*name should be thought again :)

**Comment by maliming** [comment]
I will give it a try.

**Comment by muratyuceer** [comment]
@hikalkan also if you add CanManageFeature property to User/Roles (for decide which users/roles can modify which feature permissions) in this way i guess there may be a solution about that problem #8309 
Or maybe you may have a different approach

--Update--
Or maybe you can add admin/manager property to Feature object (feature based admin)
Now admin is like god mood we need to separate that
