### ISSUE TITLE
abp update cmd no responding

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#8520]
I need upgrade my abp from v4.2.2 to v4.3.0-rc.1
But when I run abp update -p, there 's no responding and no error.

![image](https://user-images.githubusercontent.com/6952917/113993168-ba165f00-9886-11eb-8114-420aa012cdce.png)

**Comment by gterdem** [comment]
Do you still get the same behaviour? It may be a temporary issue when the new packages are being published. Can you confirm it still persists?

**Comment by gerryge** [comment]
@gterdem Now it works, thanks.
