### ISSUE TITLE
Consider to remove the libs folder from the startup templates

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8528]
Optionally, also from source control.

**Comment by ebicoglu** [comment]
**open-source template:**

![](https://user-images.githubusercontent.com/9526587/114013809-a102b380-9870-11eb-81e4-b802ff6af946.png)

---

**commercial:**

![](https://user-images.githubusercontent.com/9526587/114013421-2e91d380-9870-11eb-8505-85f4b7904534.png)

**Comment by mtozlu** [comment]
Related #8369

**Comment by hikalkan** [comment]
@maliming we can remove the `libs` folders from the solution and add `/libs` into `.gitignore` in the startup templates.
After that change, after creating a new ABP solution, we will need to run `abp install-libs` in the MVC and Blazor Server UI projects. We can automate that as much as possible with the following improvements:

1. Add ability to run the `abp install-libs` command in the solution level. This will make it easier when we have more than one blazor server or mvc UI projects in the same solution. This requires to understand if the project is MVC or Blazor Server, I think that should be easy. Do this optimized (for example: ignore node_modules folder contents)
2. `abp install-libs` command should run `yarn` (or `npm install` if `yarn` was not installed) before copying the libraries (I am not sure, maybe it is already done).
3. When we run `abp install-libs` command in solution level, it can also restore npm packages for angular UI. Actually, when I say "solution level", I don't mean "in a folder containing a .sln file". I mean a folder contains subfolders where these subfolders may contain .net and angular projects.
4. ABP CLI's new command automatically calls `abp install-libs` command after creating a new solution.

After this change, when we create a new solution from https://abp.io/get-started page, we should manually execute `install-libs`. I suppose no way to automate that. So, we should include that information in the necessary places of the documentation.

Please also consider the ABP Commercial side. Send PRs to @realLiangshiwei and @yekalkan
