### ISSUE TITLE
Identifier name is too long

### ISSUE THREAD

**Issue by lszabados** [abpframework/abp#853]
In many places the names are too long for the MySQL database.
Example IdentityServer IdentityServerApiClaims table : FK_IdentityServerApiClaims_IdentityServerApiResources_ApiResourceId
or AuditLogging index name: IX_AbpAuditLogActions_TenantId_ServiceName_MethodName_ExecutionTime

These are just examples. Where the name is longer than 64 characters, there is an error.

Did I set something wrong?

Alternatively, you can use the HasName or HasConstraintName functions in the xxxDbContextModelBuilderExtensions classes instead of auto-naming where appropriate.

**Comment by Y2zz** [comment]
![image](https://user-images.githubusercontent.com/252604/53691035-08f09100-3db1-11e9-8f65-acbccc7cf6c2.png)

I also found this problem.

**Comment by Y2zz** [comment]
@lszabados  Waiting for 0.15.0 release

**Comment by yekalkan** [comment]
I'm closing the issue since it is solved via https://github.com/abpframework/abp/pull/855

If not, re-open.
