### ISSUE TITLE
SaaS: From host side, select tenant and impersonate a tenant user (same as aspnetzero).

### ISSUE THREAD

**Issue by tvddev** [abpframework/abp#8533]
* Your **ABP Framework version**. v4.3
* Your **User Interface** Blazor
* Your database provider EF Core
* Exception message and **stack trace** if available (check the logs). N/A
* Steps needed to **reproduce** the problem. N/A

For a multi-tenant SaaS system like in aspnetzero.

1. Login as host users, view tenants etc from Host side area.
2. Then select a Tenant, and impersonate a tenant user logging into the tenant system.
3. See what the tenant user sees and can do. 

This is key to being able to run a full SaaS system. ASPnetzero has this functionality and it is used every day by support staff.

**Comment by DonVliet** [comment]
I think this is the same as https://github.com/abpframework/abp/issues/1082
