### ISSUE TITLE
Nested Permission Group

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#8545]
We need to create nested permission groups to organize permissions.. In this way we could more easily manageable permissions

For example i need to create nested group "Tanımlar" and move sub permissions to there so i could select all "Tanımlar" permissions with one click
![image](https://user-images.githubusercontent.com/25631692/114058504-2d769b80-989c-11eb-981d-cb9ff3d84562.png)

**Comment by maliming** [comment]
> Changing Permission Definitions

https://docs.abp.io/en/abp/latest/Authorization#changing-permission-definitions-of-a-depended-module

**Comment by muratyuceer** [comment]
When i research source code i saw that comment https://github.com/abpframework/abp/blob/9dcf335b096e530e8c409c6f08e05d066d0ed928/framework/src/Volo.Abp.Authorization/Volo/Abp/Authorization/Permissions/PermissionGroupDefinition.cs#L9  and i wanted to remind

**Comment by mtozlu** [comment]
I don't know if this will work but did you try this;
```csharp
var adminGroup = context.AddGroup(..., ...);
var definitionsPermission = adminGroup.AddPermission(..., ...);
var level1DefinitionsPermission = definitionsPermission.AddChild(..., ...);
var level2DefinitionsPermission = level1DefinitionsPermission.AddChild(..., ...);
var level3DefinitionsPermission = level2DefinitionsPermission.AddChild(..., ...);
```

**Comment by davidzwa** [comment]
@mtozlu is right. This is perfectly doable with the result being a dot-syntax:

`Application.Module.PermissionGroup.PermissionName`
`Module.PermissionGroup.PermissionName`
or
`PermissionGroup.PermissionName`

etc is perfectly doable with the .AddChild(...) and .AddGroup(...) commands. It ends up as the strings I mention above, so your question is easily answered. Please close this issue if that is the case.

**Comment by muratyuceer** [comment]
@mtozlu thanks the solution was useful but suite permission setting screen did not show as expected, actually this issue about commercial i will create ticket there. My goal was to categorize the permissions.
