### ISSUE TITLE
[Help] Editons features not working as expected

### ISSUE THREAD

**Issue by ldias91** [abpframework/abp#8556]
Hi,

I implemented editions on my application, so far so good.

Changing the identity features Two factor behaviour to forced for a edition and associate a user to edition, when i try login with user does not redirect to the two factor page, because the value of the feature is null.

I created a IAbpClaimsPrincipalContributor:
```csharp
  var currentTenant = context.ServiceProvider.GetRequiredService<ICurrentTenant>();
  if (currentTenant.Id.HasValue)
  {
      var tenantRepository = context.ServiceProvider.GetRequiredService<ITenantRepository>();
      var tenant = await tenantRepository.FindAsync(currentTenant.Id.Value);
      var claimsIdentity = new ClaimsIdentity();
      claimsIdentity.AddIfNotContains(new Claim(AbpClaimTypes.EditionId, tenant.EditionId.ToString()));
      context.ClaimsPrincipal.AddIdentity(claimsIdentity);
  }
```
Maybe the contributor is executed after `GetTwoFactorEnabledAsync`?

What's missing?

**Comment by maliming** [comment]
**The Two-factor behavior features** not implemented in the open-source modules but commercial.

https://docs.abp.io/en/commercial/latest/modules/identity/two-factor-authentication
