### ISSUE TITLE
Where can I submit feature suggestions?

### ISSUE THREAD

**Issue by jeffward01** [abpframework/abp#8566]
Is there a feature suggestion area of ABP? 

I did not see one.

I did not see a label for it either.

Thanks!

**Comment by mtozlu** [comment]
You can submit a github [issue](https://docs.abp.io/en/abp/latest/Contribution/Index#feature-requests).

**Comment by gterdem** [comment]
A feature suggestion that suggests _being able to make a feature suggestion_. Kinda sounds like _suggestception_ :)

Edit: You can always use fancy attributes like [FeatureRequest] on issue question title.
