### ISSUE TITLE
Add custom claims to CurrentUser in abp v4.3.0-rc2 issue

### ISSUE THREAD

**Issue by gerryge** [abpframework/abp#8568]
Your ABP Framework version
v4.3.0-rc2
Your User Interface type (Angular/MVC/React... etc.) if the issue is related to a specific UI
MVC
Your database provider(EF Core/MongoDB)
EF Core

Description:
I want to add custom claim to CurrentUser And I do as recommendation in bellow link:
https://github.com/abpframework/abp/issues/8073#issuecomment-799999030
But when login error occurred:
An unhandled exception occurred while processing the request.
InvalidOperationException: only a single identity supported
IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal)

![image](https://user-images.githubusercontent.com/6952917/114295062-6d749300-9ad5-11eb-974b-54026a711e51.png)

Steps needed to reproduce the problem.
1. abp new Acme.BookStore --preview
2. Add MyClaimsPrincipalContributor(detail see below code) class in Acme.BookStore.Domain project
```
public class MyClaimsPrincipalContributor : IAbpClaimsPrincipalContributor, ITransientDependency
    {
        public Task ContributeAsync(AbpClaimsPrincipalContributorContext context)
        {
            var claimsIdentity = new ClaimsIdentity();
            claimsIdentity.AddIfNotContains(new Claim("Organization", "OrganizationValue"));
            context.ClaimsPrincipal.AddIdentity(claimsIdentity);

            return Task.CompletedTask;
        }
    }
```
3. In BookStoreDomainModule.cs module add below code in ConfigureServices:
```
      Configure<AbpClaimsServiceOptions>(options =>
      {
          options.RequestedClaims.Add("Organization");
      });
```
4. Start the Acme.BookStore.Web project and login in admin/1q2w3E*, then the error occurred.

My demo project(I have changed the Index.cshtml to show the claims):
[Acme.BookStore.zip](https://github.com/abpframework/abp/files/6291305/Acme.BookStore.zip)

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/issues/8115
https://github.com/abpframework/abp/blob/dev/framework/test/Volo.Abp.Security.Tests/Volo/Abp/Security/Claims/AbpClaimsPrincipalFactory_Test.cs
