### ISSUE TITLE
Entities implementing interface ISoftDelete dont trigger ILocalEventHandler<EntityDeletingEventData<...>>

### ISSUE THREAD

**Issue by davidzwa** [abpframework/abp#8579]
- Question
- ABP 4.2.2
- UI irrelevant
- EF Core
- No exception
- Implement any entity named `MyEntity` with ISoftDelete and handle/trigger `ILocalEventHandler<EntityDeletedEventData<MyEntity>>` on said entity.
- I couldnt find relevant StackOverflow, docs, examples or github issues.
- Problem description: I'd like the domain event to trigger my handler. Could it be that ISoftDelete prevents this because no row is being actually deleted?
- Concession: I can live with this fact and fix it on my own. Just have to be sure, that Im not making a mistake somewhere.

Repro:
```
public class EventDeletionEventHandler : ILocalEventHandler<EntityDeletedEventData<MyEntity>>
{
       // ... irrelevant dependencies

    public EventDeletionEventHandler(
       // ... irrelevant dependencies
    )
    {
       // ... irrelevant dependencies
    }

    public async Task HandleEventAsync(EntityDeletedEventData<MyEntity> eventData)
    {
        // ... handling the soft-deleted entity deletion here (cache-related)
        // !! ==> This is not being triggered
    }
}
```

And the entity (heavily simplified)
```
[Audited]
public class MyEntity : FullAuditedEntity<Guid>
{
  // Irrelevant constructors properties and navigation properties
  
  public static void OnModelCreating(EntityTypeBuilder<Event> entity)
  {
       // Silence database-generated default warning
       entity
            .Property(u => u.IsDeleted)
            .HasDefaultValue(false);

       // Only foreign key setup here to many2many and many2one with and without ISoftDelete
   }
}
```

Correlated:
https://github.com/abpframework/abp/issues/7161
Here you can see how my distributed cache for the `AbpUserRole` entity without ISoftDelete in ABP works just fine. So my understanding of IDistributedCache<...> with local events is good enough.

**Comment by davidzwa** [comment]
~Issue is on hold~ Issue still valid

**Comment by maliming** [comment]
Maybe add `EntitySoftDeletingEventData` and `EntitySoftDeletedEventData`  will be better.

**Comment by davidzwa** [comment]
Thx. Tried `EntitySoftDeletingEventData` as well before, without success. 
Will try again just to be sure with both in the same handler class and report back.

**Comment by davidzwa** [comment]
Does not trigger as well. Just for your information I am using the method DeleteAsync from interface IDeleteAppService (service derived from CrudAppService, and called by injecting interface implementing ICrudAppService.... basic stuff)

**Comment by maliming** [comment]
hi @davidzwa 

Can you share a simple project?

**Comment by davidzwa** [comment]
Ah sure, I will.

**Comment by davidzwa** [comment]
Due to time constraints, a reproduction from my side will have to wait. My apologies. I planned it for this Friday (TZ UTC +2)

**Comment by davidzwa** [comment]
I am sad to inform you that I wont have the time to reproduce this. Focusing on releasing our app, and making it FOSS soon. That will take a while, so I will come back to this during 4.4 release previews (or somebody else can step in).
