### ISSUE TITLE
Auto register setting and permission definition providers

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#858]
When a module defines permissions, it creates a class derived from the `PermissionDefinitionProvider`, defines permissions and registers the class to the `PermissionOptions` like that:

````csharp
Configure<PermissionOptions>(options =>
{
    options.DefinitionProviders.Add<MyModulePermissionDefinitionProvider>();
});
````

From now, no need to explicitly use DefinitionProviders.Add since ABP automatically discovers and adds definition providers to that list.

It is similar for the setting definition providers.

So, we need to edit templates to not use explicit DefinitionProviders.Add configurations.

**Comment by khinhvuphiduong** [comment]
Perfectly to centralize permission definition. Thanks you!
