### ISSUE TITLE
extend tenant property failed for enum property

### ISSUE THREAD

**Issue by 0andy** [abpframework/abp#8590]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
 
 4.2.2
 Angular
 Mysql

When Create new tenant: String extend property works. but enum does not work.
UI datatable list works: getlist from db also works and show in the UI. Check image below.

error: 
Invalid cast from 'System.Int64' to 'xxx.TenantType'.
System.InvalidCastException: Invalid cast from 'System.Int64' to 'xxx.TenantType'.

![image](https://user-images.githubusercontent.com/3870326/114492455-41910480-9bde-11eb-8a50-6c81288372d1.png)

![image](https://user-images.githubusercontent.com/3870326/114492696-ae0c0380-9bde-11eb-9239-637dd8ced1f0.png)

![image](https://user-images.githubusercontent.com/3870326/114492489-5077b700-9bde-11eb-89d7-b1f565ea19d2.png)

Use **abp** tag in your questions.

**Comment by realLiangshiwei** [comment]
Steps needed to reproduce the problem.

**Comment by 0andy** [comment]
@realLiangshiwei 

Is is OK with the detail I updated?

**Comment by 0andy** [comment]
1, use the abp suite to create new solution
2, aspnet-core (server): -> cmd-> dotnet restore, then dotnet build
3, use VS to open aspnet-core, then make xxx.DbMigrator as startup project, --> run
4, after created the DB,
5, run id4 and project, make sure all works

6, create   ObjectExtensionManager.Instance
![image](https://user-images.githubusercontent.com/3870326/114493176-aa2cb100-9bdf-11eb-817c-b4d250a1b06d.png)

7, create    ObjectExtensionManager.Instance.Modules()
![image](https://user-images.githubusercontent.com/3870326/114493232-cc263380-9bdf-11eb-85c5-ad11c4871fbd.png)

8, add-migration "xxxx"
9, update-database

10, run id4, host api and angular ui again

**Comment by maliming** [comment]
https://support.abp.io/QA/Questions/1181/Extend-tenant-property-failed-for-enum-property
