### ISSUE TITLE
blazor start can't  get CurrentUser, CurrentUser is null

### ISSUE THREAD

**Issue by guolianyu** [abpframework/abp#8593]
![image](https://user-images.githubusercontent.com/29138525/114527997-2aecbb00-9c7b-11eb-9be6-ceb6ee03662d.png)

**Comment by guolianyu** [comment]
when I reloaded page,currentUser is not null; 
version:4.2.1 or 4.3.0-rc.2  has problem

**Comment by maliming** [comment]
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by realLiangshiwei** [comment]
Duplicate of https://github.com/abpframework/abp/issues/8240
