### ISSUE TITLE
How to extend IRepository interface and repository dependency injection

### ISSUE THREAD

**Issue by yuzhigang** [abpframework/abp#8603]
### Target

IRepository have not method which update  entities by where clause, so I want to extend the interface, and add interface as follows. 
```CSharp
    public interface IEfCorePlusRepository<TEntity> : IRepository<TEntity>
        where TEntity : class, IEntity
    {
        Task<int> UpdateAsync(Expression<Func<TEntity, bool>> predicate, object updateValues, bool autoSave = false, List<string> updateColumns = null, CancellationToken cancellationToken = default);
    }

    public interface IEfCorePlusRepository<TEntity, TKey> : IEfCorePlusRepository<TEntity>, IRepository<TEntity, TKey>
        where TEntity : class, IEntity<TKey>
    {
    }
```

### Question

I place the file in Domain project and have an implementation in EntityFrameCore project. While  planing to inject the IEfCorePlusRepository to my domain services,  I find that it's imposible.

```
options.SetDefaultRepositoryClasses(
        typeof(EfCorePlusRepository<,>),
        typeof(EfCorePlusRepository<>)
    );
```
I set default repository class, the method inject IRepository but not IEfCorePlusRepository . so howto extend IRepository interface and repository dependency injection? I have to register repository of every entity type to the ServiceCollection. Is there a better way? 

Thanks.

**Comment by maliming** [comment]
Please check the official documentation before asking questions: https://docs.abp.io/en/abp/latest/Repositories#custom-repositories

**Comment by yuzhigang** [comment]
> Please check the official documentation before asking questions: https://docs.abp.io/en/abp/latest/Repositories#custom-repositories

I read the document, It can't resolve my question.  IEfCorePlusRepository is a generic interface.
