### ISSUE TITLE
DB Queries behave deferent in Tests from Application

### ISSUE THREAD

**Issue by javeez** [abpframework/abp#8611]
When run unit tests, the queries return related data without adding includes but the same AppService don't return them when running the application itself.

Is their a way to configure it and to make the test run the AppService the same as the application?

**Comment by maliming** [comment]
hi

Can you explain this in detail?

**Comment by javeez** [comment]
We have two entities as below:
`
public class Order 
 {
	public Order()
	{
		OrderDetails = new List<OrderDetails>();
	}
	[Key]
	public int OrderId { get; set; }
	public int OrderTypeId { get; set; }
	public bool IsUrgentOrder { get; set; }
	public string OrderReason { get; set; }

	public List<OrderDetails> OrderDetails { get; set; }
	public List<OrderLog> OrderLogs { get; set; }
}

public class OrderDetails 
{
	[Key]
	public int ID { get; set; }
	public int OrderId { get; set; }
	[Column(TypeName = "datetime2")]
	public DateTime FromDate { get; set; }
	[Column(TypeName = "datetime2")]
	public DateTime ToDate { get; set; }
	[ForeignKey(nameof(OrderId))]
	public virtual Order Order { get; set; }
}
`

When we call the below method we have two deferent behavior:

`
public async Task<Order> GetMasterOrderById(int orderId)
{
    return await _context.Orders.Where(a => a.OrderId == orderId).FirstOrDefaultAsync();
}
`

1- When called during the runtime (debug) of the web app, the resulting "Order" object has "OrderDetails" as an embty list.

2- When called during unit testing debug, the resulting "Order" object has loaded "OrderDetails" related data.

This happened while using Sqlite and SqlServer, and the query is called for the same data record in database

*tiered application

**Comment by maliming** [comment]
Can you share the steps and codes to reproduce this?

**Comment by javeez** [comment]
It seems the issue appeared in Unit test cause we create and read at the same time, but from the web it is two seperate calls.

Right now, when we created two unit tests (similar to the web), it is working fine

Thanks
