### ISSUE TITLE
abp：Source code of SQL condition generated by imultitenant data filtering

### ISSUE THREAD

**Issue by humanww** [abpframework/abp#8614]
SELECT `a`.`Id`, `a`.`Name`, `a`.`ProviderKey`, `a`.`ProviderName`, `a`.`TenantId`
FROM `AbpPermissionGrants` AS `a`
WHERE (false OR `a`.`TenantId` IS NULL) AND ((`a`.`ProviderName` = 'R') AND (`a`.`ProviderKey` = 'E'))

I want to know how this SQL is generated  

framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Repositories/RepositoryBase.cs
I found this part of the code, but it doesn't seem that he will produce the above situation

can you help me, thinks

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L626-L643
