### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by wocar** [abpframework/abp#862]
When I create a new migration the following is added

````csharp
  migrationBuilder.RenameIndex(
                name: "IX_AbpAuditLogActions_TenantId_ServiceName_MethodName_Execution~",
                table: "AbpAuditLogActions",
                newName: "IX_AbpAuditLogActions_TenantId_ServiceName_MethodName_ExecutionTime");
````

and throws the following error

MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INDEX `IX_AbpAuditLogActions_TenantId_ServiceName_MethodName_Execution~` TO `IX_' at line 1

im using mysql, just to let you know.

**Comment by akinix** [comment]
same issue
https://github.com/abpframework/abp/issues/853
