### ISSUE TITLE
Set the claims of the current identity dynamically.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#8620]
We store a lot of user info in claims currently, such as **id**, **username**, **email** , **roles**, **tenantid**, **phone numbe**r, etc. They are serialized into jwt or cookies.

These claims are used for permission/feature checks.

The problem with claims is that they will not change unless they expire or are reissued(`re-login`). Once the user's info is changed, there will be problems.

We can consider storing only constant user info in claims, such as **UserId**.
Other claims will be set dynamically, and they may come from the database, cache, or user-defined services, **even remote api**.

```cs
app.UseAuthentication();
app.UseJwtTokenMiddleware();

app.UseDynamicClaimsMiddleware();

app.UseAuthorization();
```

This feature does not participate in authentication and authorization, so it won't break anything.

**Comment by maliming** [comment]
I will continue to study its feasibility, especially Identity Server.

**Comment by maliming** [comment]
The test code https://github.com/abpframework/abp/commit/599c1d4ebb95765b65e56302e68504d43d1ff6cd

**access_token** of password grant.
```json
{
  "nbf": 1618664278,
  "exp": 1650200278,
  "iss": "https://localhost:44301",
  "aud": "MyProjectName",
  "client_id": "MyProjectName_App",
  "sub": "7bcac909-9741-fd24-1359-39fbf1ce6458",
  "auth_time": 1618664264,
  "idp": "local",
  "tenantid": "d0f760eb-a15f-56cd-4ef9-39fbf1ce630a",
  "iat": 1618664278,
  "scope": [
    "address",
    "email",
    "MyProjectName",
    "openid",
    "phone",
    "profile",
    "role",
    "Tenant",
    "offline_access"
  ],
  "amr": [
    "pwd"
  ]
}
```

**access_token** of openid.
```json
{
  "nbf": 1618664362,
  "exp": 1650200362,
  "iss": "https://localhost:44301",
  "aud": "MyProjectName",
  "client_id": "MyProjectName_Web",
  "sub": "7bcac909-9741-fd24-1359-39fbf1ce6458",
  "auth_time": 1618664361,
  "idp": "local",
  "tenantid": "d0f760eb-a15f-56cd-4ef9-39fbf1ce630a",
  "sid": "7891EA034014D0036B7E676D7D710FE7",
  "iat": 1618664362,
  "scope": [
    "openid",
    "profile",
    "Tenant",
    "role",
    "email",
    "phone",
    "MyProjectName"
  ],
  "amr": [
    "pwd"
  ]
}
```

**id_token** of openid.
```json
{
  "nbf": 1618664362,
  "exp": 1618664662,
  "iss": "https://localhost:44301",
  "aud": "MyProjectName_Web",
  "nonce": "637542611551626052.MmI1ODk4NTEtNzVkNC00NDEzLTk5YmQtMzkyNjMzNTdjZDJmNmRmMDE1M2ItMDkwNC00ZWY4LThiYjItMDU2OTcwNWQ4Yjc0",
  "iat": 1618664362,
  "at_hash": "0trPakU3QEZGBJlxsmpONw",
  "s_hash": "8m2MRXtADdFdgB-YfPIuwg",
  "sid": "7891EA034014D0036B7E676D7D710FE7",
  "sub": "7bcac909-9741-fd24-1359-39fbf1ce6458",
  "auth_time": 1618664361,
  "idp": "local",
  "tenantid": "d0f760eb-a15f-56cd-4ef9-39fbf1ce630a",
  "role": "admin",
  "phone_number_verified": "False",
  "email": "test@abp.io",
  "email_verified": "False",
  "preferred_username": "admin",
  "name": "admin",
  "given_name": "admin",
  "amr": [
    "pwd"
  ]
}
```

**connect/userinfo**
```json
{
    "sub": "7bcac909-9741-fd24-1359-39fbf1ce6458",
    "tenantid": "d0f760eb-a15f-56cd-4ef9-39fbf1ce630a",
    "role": "admin",
    "phone_number_verified": "False",
    "email": "test@abp.io",
    "email_verified": "False",
    "preferred_username": "admin",
    "name": "admin",
    "given_name": "admin"
}
```

**Comment by gerryge** [comment]
Any updates?

**Comment by alexandis** [comment]
Issue: ABP app admin of app1 changes the permissions of role in app2 (app1 has nuget reference to app2 projects Application.Contracts and Domain.Shared thus having access to permission names for app2). I need to refresh permission cache in app2 so any user there would see the menu according to the permissions after relogin or page refresh. I implemented it via overriding `PermissionAppService` where RabbitMq sends message to another app with role update info from app1 to app2 and app2 gets the message and refresh permission cache. It does not work anymore after ABP update: `PermissionAppService` override is not triggered... Can't figure out what is wrong now.

**Comment by alexandis** [comment]
I have custom **Roles** / **Permissions** _management_ page. I assign just created custom permission to a role in app **A** for app **A**, **B**, **C**. For this, I use _API_ call to app **A** page from the required app. And use **RabbitMQ** to refresh **ABP** _permission cache_ in each of these once I assigned the permissions: so all apps _permission caches_ are in-sync. However, the assigned _permission_ is not applied until I restart app **A**. As I understand, this is happening because my custom _Permission Definition Provider_ does not see the new _permission_ yet. Can I avoid app restart and kind of hot-reload my custom _Permission Definition Provider_? BTW - I am not going to redesign my custom solution and implement _dynamic permissions_, because it does not fully suit me, it needs some serious reconsideration.

**Comment by hikalkan** [comment]
@maliming I am currently trying to make a design for that (https://github.com/abpframework/abp/tree/dynamic-claims-middleware)
The design should work efficiently in any scenario (monolith and distributed/microservice, JWT, cookie or OIDC authentication). I will write my design when it becomes more clear.

**Comment by hikalkan** [comment]
Moved to https://github.com/abpframework/abp/issues/18060
