### ISSUE TITLE
Handle null values on Datatables `Date` data formats

### ISSUE THREAD

**Issue by cotur** [abpframework/abp#8638]
![image](https://user-images.githubusercontent.com/16813853/114874995-71831680-9e2f-11eb-85a1-c4060d3fdffb.png)

**Comment by jonny-xhl** [comment]
Will only consider time format? Is there a case where there is an object attribute?

**E.g:blog.writer.name?** If the Writer here is null?

**Comment by cotur** [comment]
Hi @jonny-xhl 

We made this update for `date` & `datetime` datetable format extensions for abp.

Example:
```js
{
                title: l("LastModificationTime"),
                orderable: true,
                data: 'lastModificationTime',
                dataFormat: "datetime"
            }
```

In your case, you can use `render` option to handle different scenarios for your object.

Example:
```js
{
                title: "MyTitle",
                data: "myProperty",
                render: function(myProperty){

                if(!myProperty) { return "not-exist"; }
                
                return myProperty;
                }
            }
```
