### ISSUE TITLE
different Commercial level has diff Tenant class? And Phone registration

### ISSUE THREAD

**Issue by 0andy** [abpframework/abp#8647]
Question 1:

The class tenant does not have Navigation property: public virtual Edition Edition { get; set; }
So this is the limitation for the different commercial level? Thanks

but default could get edition navigation property.

![image](https://user-images.githubusercontent.com/3870326/114887279-eaea1d00-9dcd-11eb-9cf7-8004c134367b.png)

Question 2:
I see the sendtoken and confirm for the phone login.

But commercial do not have phone registration. Right? So we have to implement by ourself. Right?

thx

Use **abp** tag in your questions.

**Comment by ebicoglu** [comment]
sorry, @[**0andy**](https://github.com/0andy) **we accept only open-source questions here.**
