### ISSUE TITLE
What's the relationship between ABP and Asp.net Boilerplate?

### ISSUE THREAD

**Issue by b-js** [abpframework/abp#865]
This web  https://aspnetboilerplate.com/ , The project  of  Asp.Net Boilerplate,
What's the relationship between them?

**Comment by ismcagdas** [comment]
You can think ABP (abp.io) as the next generation of AspNet Boilerplate.

**Comment by hikalkan** [comment]
see also https://abp.io/blog/abp/Abp-vNext-Announcement
