### ISSUE TITLE
The package @abp/ng.core won't compile in Angular strict mode.

### ISSUE THREAD

**Issue by xixixixixiao** [abpframework/abp#8654]
### ABP Framework version
4.2.2

### User Interface
Angular 11.2.8

### Database provider
EF Core

### Steps to reproduce

1. Use `ng new [project-name] --strict` command to generate the Angular project.
2. Use `yarn add @abp/ng.core` command to add the package `@abp/ng.core`.
3. Import some type from the package:
```ts
import { PagedResultDto } from '@abp/ng.core';
```
4. `yarn start` to run project.

These are some of the errors I'm getting (I left out the ones with long traces):

```shell
Error: node_modules/@abp/ng.core/lib/services/environment.service.d.ts:10:17 - error TS2411: Property 'url' of type 'string | undefined' is not assignable to string index type 'string'.

10                 url?: string;
                   ~~~

Error: node_modules/@abp/ng.core/lib/services/environment.service.d.ts:11:17 - error TS2411: Property 'rootNamespace' of type 'string | undefined' is not assignable to string index type 'string'.

11                 rootNamespace?: string;
                   ~~~~~~~~~~~~~

Error: node_modules/@abp/ng.core/lib/services/environment.service.d.ts:13:13 - error TS2411: Property 'default' of type '{ [x: string]: string; url?: string | undefined; rootNamespace?: string | undefined; } | undefined' is not assignable to string index type '{ [x: string]: string; url?: string | undefined; rootNamespace?: string | undefined; }'.

13             default?: {
               ~~~~~~~

Error: node_modules/@abp/ng.core/lib/services/environment.service.d.ts:15:17 - error TS2411: Property 'url' of type 'string | undefined' is not assignable to string index type 'string'.

15                 url?: string;
   91m                ~~~

Error: node_modules/@abp/ng.core/lib/services/environment.service.d.ts:16:17 - error TS2411: Property 'rootNamespace' of type 'string | undefined' is not assignable to string index type 'string'.

16                 rootNamespace?: string;
                   ~~~~~~~~~~~~~
```

### What is expected
There should not to be any compiler errors.

**Comment by xixixixixiao** [comment]
My current solution to this problem is to temporarily disable Angular's strict mode. Modify the TypeScript configuration file `tsconfig.json` from:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

to:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false
  }
}
```

**Comment by ebicoglu** [comment]
@mehmet-erim what do you think?

**Comment by mehmet-erim** [comment]
Hi @xixixixixiao

We will fix the problems, thanks for the reporting.

Try adding the prop below to `tsconfig.json` as a workaround:

```
"skipLibCheck": true
```

With this, compiling errors will be ignored.

**Comment by begandroide** [comment]
Hi! Recently I created a new ABP project and I want to use `strictTemplates` in angular, and I configure `tsconfig.json` with `skipLibCheck: true` and I has an issue with `autofocus` directive: what can be missing?

<img width="1395" alt="Captura de Pantalla 2021-09-13 a la(s) 18 21 11" src="https://user-images.githubusercontent.com/22018004/133158017-2e2cc2cd-8f81-4112-88a7-5c211a63e756.png">
 
Regards.

**Comment by mehmet-erim** [comment]
Hi,

Autofocus directive exposed by `@abp/ng.core`. Did you import the `CoreModule` to your module?

**Comment by begandroide** [comment]
Yes, I did it and not working with strictTemplates because a type error in directive.

**Comment by mehmet-erim** [comment]
The problem with autofocus directive has been fixed.  The fix will be available in v5.0-rc.1.
@begandroide, As a workaround, can you try to use the autofocus as shown below:

``` 
<input [autofocus]="0" />
```

That may be fixed the error.

**Comment by begandroide** [comment]
Thanks you @mehmet-erim i will try it.

**Comment by badly-drawn-wizards** [comment]
Similar errors occur in a fresh ABP 10.0.0 angular template.

Relevant unannotated method here:
https://github.com/abpframework/abp/blob/7411c5481e58cc3734d74a714a02f5433e962bcc/npm/ng-packs/packages/core/src/lib/services/environment.service.ts#L21

When enabling strict type checking (tsconfig.json compilerOptions.strict) on a freshly generated ABP 10.0 template with angular, I get the errors around `node_modules/@abp/ng.core/index.d.ts:1446:16`.

If I explicitly change the definition to:
```
get createOnUpdateStream(): <Slice>(selector: (state: DeepPartial<Environment>) => Slice, filterFn?: (x: Slice) => boolean) => Observable<Slice>;
```

It typechecks fine.

This is probably a bug in typescript `*.d.ts` generation, but it might be prudent to add the type annotation to the `createOnUpdateStream` in the meantime.
