### ISSUE TITLE
abp-samples , (BookStore-Modular), Does not have  Author  class, comparing to (BookStore-Mvc-EfCore)

### ISSUE THREAD

**Issue by mrs01dev** [abpframework/abp#8656]
The  abp-samples ,in application  ( BookStore-Modular) , Domain project does not have Authors
While in application (BookStore-Mvc-EfCore), Domain project does have Authors.

Could you please make the two applications [ ( BookStore-Modular) , (BookStore-Mvc-EfCore)] equals in functionality ?

**Comment by cotur** [comment]
Hi @mrs01dev 

Would you like to contribute that? :)

Like most of other issues, this issue is also open for everyone. Waiting your contributions. :)

**Comment by panna-ahmed** [comment]
@cotur Added a pull request for this on abp-samples

**Comment by EngincanV** [comment]
https://github.com/abpframework/abp-samples/pull/104
