### ISSUE TITLE
Package (Volo.Abp.IdentityServer.EntityFrameworkCore 4.3.0-rc.2) is not compatible with netstandard2.1 

### ISSUE THREAD

**Issue by mrs01dev** [abpframework/abp#8665]
When i try to add 
Package (Volo.Abp.IdentityServer.EntityFrameworkCore 4.3.0-rc.2)
to a module
(project-name).EntityFrameworkCore
An error appear :
[
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Volo.Abp.IdentityServer.EntityFrameworkCore 4.3.0-rc.2 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Volo.Abp.IdentityServer.EntityFrameworkCore 4.3.0-rc.2 supports: net5.0 (.NETCoreApp,Version=v5.0)
]

**Comment by ebicoglu** [comment]
where are you adding this package?
this must be added to `YourModule.EntityFrameworkCore.csproj`

**Comment by maliming** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/3665#issuecomment-535910580
