### ISSUE TITLE
abp audit entity properties change serialization issues

### ISSUE THREAD

**Issue by yangfan-zz** [abpframework/abp#8668]
![image](https://user-images.githubusercontent.com/59385737/115108734-a2d12300-9fa4-11eb-91ea-485101bc461f.png)
![image](https://user-images.githubusercontent.com/59385737/115108889-67832400-9fa5-11eb-8b58-16c636783d27.png)
If the attribute type is a string type, whether it is not serialized.
String type should not be serialized as string type.

**Comment by maliming** [comment]
This is a JSON string. It's by design.
