### ISSUE TITLE
Confusing access level of auditing properties in entity.

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#8669]
We have many auditing entity classes, there is a list of them: [src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing](https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing)

In most of them, the auditing properties are full public (`{ get; set; }`).
But I noticed that a part of them with protected setter (`{ get; protected set; }`), such as `CreatorId`, `CreationTime`, `Creator`.

This is the first confusion, why do we only use the protected setter with properties that about creation?

Then, there is another confusion, the `CreationAuditedAggregateRoot` has protected setter, but `CreationAuditedAggregateRoot<TKey>` not.

https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing/CreationAuditedAggregateRoot.cs#L10-L16

https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.Ddd.Domain/Volo/Abp/Domain/Entities/Auditing/CreationAuditedAggregateRoot.cs#L24-L30

**Comment by ebicoglu** [comment]
The framework sets these fields automatically before EF Core saving changes 
the others can be manually set by developer

**Comment by PMExtra** [comment]
@ebicoglu It doesn't answer my question. The framework will set all auditing properties, but it only protect properties that about creation in `CreationAuditedAggregateRoot` without primary key.
I think it's a oversight, although it won't make big trouble.
