### ISSUE TITLE
blazor server project. Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#8671]
* 4.3-rc2. Blazor server
* database provider : EF Core

the app running well when I use VS.  But something wrong when publish it.  there's no user name showing after login, and no permissions for the menus.
the error occurs when I open the page, for example the Roles page.

AbpAuthorizationException: Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown. STACK TRACE: at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy) at Volo.Abp.Authorization.MethodInvocationAuthorizationService.CheckAsync(MethodInvocationAuthorizationContext context) at Volo.Abp.Authorization.AuthorizationInterceptor.AuthorizeAsync(IAbpMethodInvocation invocation) at Volo.Abp.Authorization.AuthorizationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo) at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope) at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper) at Volo.Abp.Auditing.AuditingInterceptor.ProcessWithNewAuditingScopeAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, ICurrentUser currentUser, IAuditingManager auditingManager, IAuditingHelper auditingHelper) at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation) at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo) at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation) at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo) at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync() at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed) at Volo.Abp.BlazoriseUI.AbpCrudPageBase`10.GetEntitiesAsync()

**Comment by juchunwei** [comment]
Hi @stsrki , 

I tried to create a custom principalAccessor like this, and it working now.  no more permissions issue and I can see all the menus now.  Maybe this also related to the CurrentUser issue? the CurrentUser is empty when publish the app.

```
 [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(ICurrentPrincipalAccessor), typeof(HttpContextCurrentPrincipalAccessor), typeof(CurrentPrincipalAccessor))]
    public class CurrentPrincipalAccessor : HttpContextCurrentPrincipalAccessor
    {
        public CurrentPrincipalAccessor(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
        {
        }

        protected override ClaimsPrincipal GetClaimsPrincipal()
        {
            return claimsPrincipal;
        }
        private ClaimsPrincipal claimsPrincipal;

        public override IDisposable Change(ClaimsPrincipal principal)
        {
            return SetCurrent(principal);
        }

        private IDisposable SetCurrent(ClaimsPrincipal principal)
        {
            return new DisposeAction(() =>
            {
                claimsPrincipal = principal;
            });
        }
    }```

**Comment by Alexbits** [comment]
> Hi @stsrki ,
> 
> I tried to create a custom principalAccessor like this, and it working now. no more permissions issue and I can see all the menus now. Maybe this also related to the CurrentUser issue? the CurrentUser is empty when publish the app.
> 
> ```
>  [Dependency(ReplaceServices = true)]
>     [ExposeServices(typeof(ICurrentPrincipalAccessor), typeof(HttpContextCurrentPrincipalAccessor), typeof(CurrentPrincipalAccessor))]
>     public class CurrentPrincipalAccessor : HttpContextCurrentPrincipalAccessor
>     {
>         public CurrentPrincipalAccessor(IHttpContextAccessor httpContextAccessor) : base(httpContextAccessor)
>         {
>         }
> 
>         protected override ClaimsPrincipal GetClaimsPrincipal()
>         {
>             return claimsPrincipal;
>         }
>         private ClaimsPrincipal claimsPrincipal;
> 
>         public override IDisposable Change(ClaimsPrincipal principal)
>         {
>             return SetCurrent(principal);
>         }
> 
>         private IDisposable SetCurrent(ClaimsPrincipal principal)
>         {
>             return new DisposeAction(() =>
>             {
>                 claimsPrincipal = principal;
>             });
>         }
>     }```
> ```

This helped me as well with the same issue in Blazor Server. But I do not fully understand what's causing this behavior.  I have the app running ok on the one domain and I get "Authorization was successful" followed by the "Authorization failed. These requirements were not met: DenyAnonymousAuthorizationRequirement: Requires an authenticated user." after successful user login when publishing it to the other app on a different domain.🙄🤔
