### ISSUE TITLE
ISettingPageContributor is not implemented

### ISSUE THREAD

**Issue by 491134648** [abpframework/abp#8672]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* V4.2.2**.
* MVC UI
* EF Core

ISettingPageContributor is not implemented,How do I manage my configuration information, SettingManagement's Index.cshtml is dataless

![image](https://user-images.githubusercontent.com/9816794/115134552-c303ef00-a043-11eb-8c2b-9a9cda9477e0.png)

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Web/Settings/EmailingPageContributor.cs
