### ISSUE TITLE
Can't find Swagger endpoint in Blazor Server Solution

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#8695]
* Your **ABP Framework version** **4.3.0-rc.2**
* Your **User Interface** type (Angular/MVC/React... etc.) **Blazor Server**
* Your database provider(EF Core/MongoDB) **EF Core**

I see that Swagger/Swashbuckle is included in the {AppName}BlazorModule.cs file in the Blazor Project but there doesn't appear to be a Swagger endpoint available.

```
    [DependsOn(
        typeof(AbpSwashbuckleModule),

```

**Comment by ebicoglu** [comment]
@DonVliet I've created an issue for this development. Closing this issue. You can track from https://github.com/abpframework/abp/issues/8697

**Comment by DonVliet** [comment]
@ebicoglu Thank you!
