### ISSUE TITLE
Blazor server, RedirectToLogin redirect to authentication/login, but no address

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#8700]
* 4.3-rc2 Balzor server.
database provider : EF Core

for the authorize view, if user not login, it redirect to authentication/login, and the error says : 

Sorry, there's nothing at this address.

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
