### ISSUE TITLE
Is it possible to provide a project template that does not depend on any modules?

### ISSUE THREAD

**Issue by wulaiwei** [abpframework/abp#871]
Hi!
I want to know if I can provide a project template that does not depend on any modules?
![image](https://user-images.githubusercontent.com/16910820/54258483-bc216d00-459d-11e9-98bb-2601c4da87cc.png)
Because we already have these features in our project, we don't want to introduce these modules.
Forced removal after generation can cause a lot of trouble
We want to generate a very pure project from the template, relying only on the functionality of the ABP core.
---------------------------------------------------------
I think so  new WebHostBuilder() Switch to WebHost.CreateDefaultBuilder(args)
![image](https://user-images.githubusercontent.com/16910820/54267644-90f64800-45b4-11e9-85b4-eb9c2d543c14.png)
![image](https://user-images.githubusercontent.com/16910820/54267741-b8e5ab80-45b4-11e9-93b6-f058db142821.png)
execution succeed
![image](https://user-images.githubusercontent.com/16910820/54267835-e7638680-45b4-11e9-8bd6-9a80d6553c7e.png)
![image](https://user-images.githubusercontent.com/16910820/54267827-e16da580-45b4-11e9-9adb-156762ebd34b.png)
Execution failed

Because of the need for some of our plugins WebHost.CreateDefaultBuilder(args)

**Comment by hikalkan** [comment]
You can start from empty projects: https://abp.io/documents/abp/latest/Getting-Started-AspNetCore-Application

**Comment by wulaiwei** [comment]
@hikalkan thank you very much  
Here we also generated the ASP.NET Core Mvc Application type project from https://abp.io/Templates
We choose a more stupid way，Manually removed unwanted modules，Now he has satisfied the function we want

but ，There are still two problems
First：
new WebHostBuilder()  change to WebHost.CreateDefaultBuilder(args)  Will produce the problem described in the image above，Because some of our projects depend on the need to use ConfigurationBuilder，
So we used this way to deal with this problem
 new WebHostBuilder()
               .UseContentRoot(Directory.GetCurrentDirectory())
                 .ConfigureAppConfiguration((hostingContext, webBuilder) =>
                 {
                     var config = new ConfigurationBuilder()
                         .SetBasePath(Directory.GetCurrentDirectory())
                         .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);

                     webBuilder
                         .AddApollo(config.Build().GetSection("apollo"))
                         .AddDefault();
                 })
                .UseKestrel()
                .UseIISIntegration()
                .UseStartup<Startup>()
                .ConfigureKestrel((context, options) =>
                {
                    // Set properties and call methods on options
                })
                .UseSerilog()
                .Build();
 
Two：
We integrated single sign-on within the company  but  ClaimTypes.NameIdentifier  The returned type is long
![image](https://user-images.githubusercontent.com/16910820/54402157-f148cf00-4705-11e9-8338-0479cb86f661.png)
![image](https://user-images.githubusercontent.com/16910820/54402172-045b9f00-4706-11e9-9fef-0b45f21cc4da.png)
ICurrentUser.Id  Cast to Guid Caused a program error

  So we used this way to deal with this problem
        private void ProcessLoginCallbackForNameIdentifier(AuthenticateResult externalResult, List<Claim> localClaims, AuthenticationProperties localSignInProps)
        {
            var sid = externalResult.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
            if (sid == null) return;

            localClaims.Add(new Claim(JwellClaimTypeExtensions.SsoNameIdentifier, sid.Value));
            var nameIdentifier = _ssoGuidGenerator.Create(sid.Value).ToString();
            if (!string.IsNullOrEmpty(nameIdentifier))
            {
                localClaims.Add(new Claim(ClaimTypes.NameIdentifier, nameIdentifier));
            }
        } 
This kind of solution is feasible,But this is cast to Guid is it right or not? Is it possible to use string?

Thank you very much for your reply. I am sorry that my English is very general. Some descriptions may not be very accurate.

**Comment by hikalkan** [comment]
Sorry, I am closing this issue. Can you create a new issue with a well formatted issue text.
Thanks.
