### ISSUE TITLE
Add Development Tenant Connection String to Tenant Module

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#8724]
Currently, I enjoyed using multi-tenant module to support my clients to visit their individual cloud database(each tenant has different cloud sqlserver database). However, when it comes to changing database structure, it is very painful that we have to update the connection strings of all the clients because we are using private intranet IP addresses of sqlservers on production environment but using public IP addresses of sqlserver on the local development machine to migrate the changes(using abp .migrator). Also, it becomes more time consuming when the number of our microservices(modules) and databases grows in number.

**Comment by ebicoglu** [comment]
this is a bit out of the framework. it's a network architecture challenge. you may want to make a VPN among your database servers and make DbMigrator accessible to all your servers. Otherwise we cannot solve this problem
