### ISSUE TITLE
Replace Razor Pages not work.

### ISSUE THREAD

**Issue by Nongzhsh** [abpframework/abp#873]
In Volo.Abp.Identity.Web (0.14 version) package  'PersonalSettingsModal.cshtml' references the invalid 'ISettingManager' (it should be reference 'SettingProvider').
Follow the 'Virtual-File-System' documentation, I have created new 'PersonalSettingsModal.cshtml'  and placed it under the virtual folder of the project. But it doesn't work. Can anyone help me?

**Comment by ismcagdas** [comment]
@Nongzhsh it is fixed in https://github.com/abpframework/abp/commit/6ee3a94b310c39d15b1ed0a86a39667e2fb88ed0.

How are you using your new file ?

**Comment by Nongzhsh** [comment]
thank you for your reply.
> @Nongzhsh it is fixed in [6ee3a94](https://github.com/abpframework/abp/commit/6ee3a94b310c39d15b1ed0a86a39667e2fb88ed0).

Yes, but it hasn't been packaged and released yet.

> How are you using your new file ?

I created a same name page and put it under the virtual folder of my web project.
like：

![image](https://user-images.githubusercontent.com/7017193/54379138-c50c5e80-46c3-11e9-8706-920287c02315.png)

**Comment by ismcagdas** [comment]
Have you tried making it as embedded resource ?

**Comment by Nongzhsh** [comment]
@ismcagdas yeah，i have set it as embedded resource.

**Comment by hikalkan** [comment]
Putting it to a folder is not enough. You should also register it to the virtual file system. See the document: https://abp.io/documents/abp/latest/Virtual-File-System

**Comment by hikalkan** [comment]
BTW, we will release v0.15 in this Friday or Monday.

**Comment by hikalkan** [comment]
We are also working to release nightly builds.
