### ISSUE TITLE
Looking for typescript based react-native template.

### ISSUE THREAD

**Issue by kunalpgithub** [abpframework/abp#8735]
Hi,

I have  created application using abp cli. 

I got to know about react-native template and started with it. But it was using Javascript based on expo.

I tried to migrate to typescript using expo documentation, but there are lot of abp component and its lot of work to rename all js file to typescript file. Even after doing that is it still missing type defination for some of component and also types not defined for model as well.

Is there a way to create react-native project with typescript using abp command line.?

**Comment by mehmet-erim** [comment]
Hi @kunalpgithub

Unfortunately, there is no way to create a TS based React Native project with CLI. You should migrate the project manually. However, you can change TS configurations in tsconfig.json for migrating easily. For example; set the `noImplicitAnyForClassMembers` prop as `false`

**Comment by kunalpgithub** [comment]
Thanks for your response. Unfortunately setting noImplicitAnyForClassMembers  as false, will undo purpose of using type script. May be I can try other things for type check and continue with javascript.
