### ISSUE TITLE
How do I configure abp.ajax global interception?

### ISSUE THREAD

**Issue by beefsteak** [abpframework/abp#8739]
Like this:
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        // Do something with 'element' and 'event'...
    }
});

**Comment by maliming** [comment]
You can change the `abp.ajax.defaultOpts`.

https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Ajax#default-ajax-options
