### ISSUE TITLE
BackgroundJob(Hangfire) and UnitOfWork

### ISSUE THREAD

**Issue by AdemAygun** [abpframework/abp#8747]
* Your **ABP Framework version** : 4.1.2
**Angular**
**EF Core**

productApi  calls a webapi method. Product inserts to DB even productapi throws exception. If I add ```UnitOfWork``` , after getting exception  transaction is being rolled back. But in AppService layer without adding ```UnitOfWork```  methods works as expected (Db operation is being rolled back when ```productapi.update``` throws exception)

```
    public class MyJob : AsyncBackgroundJob<GowihReturnArgs>, ITransientDependency
    {
        public override Task ExecuteAsync(GowihReturnArgs args)
        {
            productRepository.Insert(args.product);
            productApi.Update(args.product);
        }
    }

```

**Comment by ebicoglu** [comment]
`AsyncBackgroundJob` doesn't automatically work in `UnitWork`scope.

```

    public class MyJob : AsyncBackgroundJob<GowihReturnArgs>, ITransientDependency
    {
        public override Task ExecuteAsync(GowihReturnArgs args)
        {
            await DoWorkAsync(args);
        }

        [UnitOfWork]
        public virtual Task DoWorkAsync(GowihReturnArgs args)
        {
            await productRepository.InsertAsync(args.product);
            await productApi.UpdateAsync(args.product);
        }
    }
```

**Comment by jonny-xhl** [comment]
I think it can also refer to [Event bus Transaction & Exception Behavior](https://docs.abp.io/en/abp/latest/Local-Event-Bus#transaction-exception-behavior).
