### ISSUE TITLE
Add Docker support when using VisualStudio

### ISSUE THREAD

**Issue by brunobertechini** [abpframework/abp#875]
Hello,

It would be great if we add docker support within Visual Studio 2017 using the best of the two worlds.

I can work on this task and submit PR.

This way we can build, debug and work with containers from inside VS2017. This will require only small changes and will make the solution more easy for new adopters.

Here is the list I am working on:

- [ ] Upgrade docker-compose files from 3.0 to 3.4
- [ ] Move Dockerfile image from 2.2-aspnetcore-runtime-alpine to 2.2-aspnetcore-runtime
- [ ] Modify .dockerignore (root level) to exclude .vs and .vscode recursively
- [ ] Modify .dockerignore to exclude non-sourcecode folders from build context (docs, templates, etc)
- [ ] Remove unnecessary sqlserver service in docker-compose-migrations.yml
- [ ] Add docker-compose project (.dcproj) to solution and configure to run migrations upon build
- [ ] Fix container published (host) port for all services in docker-compose-override.yaml to avoid dynamic ports to be added by Visual Studio 
- [ ] Add an exception to build-all.ps1 to specify fixed solution name when we have more than one sln/proj
- [ ] Add docker support for individual projects to be able to debug with right click -> debug -> new instance on containers
- [ ] Update documentation to new approach: split Microservices sample in different sections. (After PR #879  is reviewed)

Cheers

Bruno

**Comment by brunobertechini** [comment]
I can see that most of the build contexts for the Microservices Demo points to two directories above the folder. Is it because the project has local references to Volo.Abp.* packages and we need those sources inside build context ?

**Comment by brunobertechini** [comment]
Task list updated on first comment.

@hikalkan do you agree with such a list ? 

I am already working on it. Please let me know if you have any concern.

Bruno

**Comment by hikalkan** [comment]
Thanks a lot @brunobertechini for your work. I have no much experience on that, but I will check & try it in 1-2 days.

**Comment by zolrath** [comment]
When exploring the MicroservicesDemo sample this was my biggest pain point.
Being able to press Start in Visual Studio and have it use the docker-compose file to boot up all of the containers while still letting me debug and set breakpoints would be great!

**Comment by brunobertechini** [comment]
I will come back to this implementation. I will need to start from scratch cause a lot of things changed in one year :)
