### ISSUE TITLE
How to combine Hangfire Authorization with ABP ICurrentUser Permissions?

### ISSUE THREAD

**Issue by yerz** [abpframework/abp#8756]
My environment:

* ABP4.2
* No UI
* MySQL DB
* Web API project
---

**OnApplicationInitialization**
![image](https://user-images.githubusercontent.com/30039842/115813105-26679580-a425-11eb-9e49-46f6b0167776.png)

**HangfireAuthorizationFilter** 
```
 public class HangfireAuthorizationFilter : ApplicationService, IDashboardAuthorizationFilter
    {
        private readonly ICurrentUser _currentUser;

        public HangfireAuthorizationFilter(ICurrentUser currentUser)
        {
            _currentUser = currentUser;
        }

        public bool Authorize([NotNull] DashboardContext context)
        {
            _currentUser.FindClaim(CMSPermissions.HangFire.Dashboard);

            throw new NotImplementedException();
        }
    }
```

I want to use Permissions in ABP ICurrentUser for Authorization in UseHangFireDashboard to determine if there is permission to access it. What should I do?

It seems I can't in OnApplicationInitialization ICurrentUser injection.

Maybe I'm just too stupid. 😢 

thank you

**Comment by maliming** [comment]
You should ask Hangfire how to use DI in **IDashboardAuthorizationFilter** or get **HTTP context**.
Then you can use permissions check of abp.

**Comment by yerz** [comment]
> You should ask Hangfire how to use DI in **IDashboardAuthorizationFilter** or get **HTTP context**.
> Then you can use permissions check of abp.

my project  Identity Server Seperated (Angular): yes 

I have modified it according to your suggestion **Authorize**
```
public bool Authorize([NotNull] DashboardContext context)
        {
            var permissionChecker = context.GetHttpContext().RequestServices.GetRequiredService<IPermissionChecker>();
            return AsyncHelper.RunSync(() => permissionChecker.IsGrantedAsync("CMS.Dashboard"));
        }

```
but  As a result, I still can't get any information about all permissions of authorized users.

What should I do ? 😢
