### ISSUE TITLE
The document of cms kit module.

### ISSUE THREAD

**Issue by Qianzujin** [abpframework/abp#8757]
![image](https://user-images.githubusercontent.com/49854479/115829667-d4813880-a441-11eb-9f79-6288cbf0c9db.png)

**Comment by maliming** [comment]
We'll gradually add these documents.

**Comment by mgochmuradov** [comment]
I was able to add and enable CmsKit for an MVC application.
Steps I took:

- Add CmsKit Module: `abp add-module Volo.CmsKit`
- Install dependencies in the Web project, run: `yarn` and then `gulp`
- Enable CmsKit, add the following in the ApplicationContractsModule:
```cs
        private static readonly OneTimeRunner OneTimeRunner = new OneTimeRunner();
        
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PortalDtoExtensions.Configure();

            OneTimeRunner.Run(() =>
            {
                GlobalFeatureManager.Instance.Enable<PagesFeature>();
                GlobalFeatureManager.Instance.Enable<CmsUserFeature>();
                GlobalFeatureManager.Instance.Enable<MediaFeature>();
                GlobalFeatureManager.Instance.Enable<BlogsFeature>();
                GlobalFeatureManager.Instance.Enable<CommentsFeature>();
                GlobalFeatureManager.Instance.Enable<TagsFeature>();
            });
        }
```
- Add migration and then run DbMigrator project
Then run the application and you will get the Cms menu
![Screenshot (116)](https://user-images.githubusercontent.com/17276537/115948016-026b8900-a4e5-11eb-8713-4ea754deba03.png)



You can access pages by going to `/pages/{page-slug}`
And access Blogs at `/blogs/{blog-slug}/{blog-post-slug}`

**Comment by mgochmuradov** [comment]
You will also have to [add `AbpBlobStoringFileSystemModule` in the domain project](https://docs.abp.io/en/abp/latest/Blob-Storing-File-System), to enable file attachments.

**PS: Do not use the BlobStoring Database module, as that seems to be breaking CMS module.**

**Comment by Qianzujin** [comment]
> You will also have to [add `AbpBlobStoringFileSystemModule` in the domain project](https://docs.abp.io/en/abp/latest/Blob-Storing-File-System), to enable file attachments.
> 
> **PS: Do not use the BlobStoring Database module, as that seems to be breaking CMS module.**

Thank you very much!

**Comment by Qianzujin** [comment]
> You will also have to [add `AbpBlobStoringFileSystemModule` in the domain project](https://docs.abp.io/en/abp/latest/Blob-Storing-File-System), to enable file attachments.
> 
> **PS: Do not use the BlobStoring Database module, as that seems to be breaking CMS module.**

![image](https://user-images.githubusercontent.com/49854479/115979207-30210280-a5b7-11eb-95a2-f255e1797e79.png)
Thank you very much for your reply. I have created the code according to the steps, but there are still mistakes. Do you have the demo code for reference?

**Comment by Qianzujin** [comment]
Add-migration does not work, the corresponding CMS table is not seen in the database...Don't know why

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/115981838-6798aa80-a5c9-11eb-8888-4338ea3db334.png)
Migration parameters are configured

**Comment by xxvolvo** [comment]
u can learn from abp/modules/cms-kit/host/

**Comment by xxvolvo** [comment]
> ![image](https://user-images.githubusercontent.com/49854479/115981838-6798aa80-a5c9-11eb-8888-4338ea3db334.png)
> Migration parameters are configured

abp/modules/cms-kit/host/Volo.CmsKit.Host.Shared/FeatureConfigurer.cs /

**Comment by ilkayilknur** [comment]
@xxvolvo 
Open the `GlobalFeatureConfigurator` class in the `Domain.Shared` project and add the following codes to the `Configure` method.
```csharp
GlobalFeatureManager.Instance.Modules.CmsKit(cmsKit =>
{
    cmsKit.EnableAll();
});
```
After enabling the features, you can create and apply dbmigrations for the CMS-Kit.

**Comment by Qianzujin** [comment]
> @xxvolvo
> Open the `GlobalFeatureConfigurator` class in the `Domain.Shared` project and add the following codes to the `Configure` method.
> 
> ```cs
> GlobalFeatureManager.Instance.Modules.CmsKit(cmsKit =>
> {
>     cmsKit.EnableAll();
> });
> ```
> 
> After enabling the features, you can create and apply dbmigrations for the CMS-Kit.

Thank you very much !!! ^-^

**Comment by Qianzujin** [comment]
> > ![image](https://user-images.githubusercontent.com/49854479/115981838-6798aa80-a5c9-11eb-8888-4338ea3db334.png)
> > Migration parameters are configured
> 
> abp/modules/cms-kit/host/Volo.CmsKit.Host.Shared/FeatureConfigurer.cs /

Thank you very much !!! ^-^

**Comment by ilkayilknur** [comment]
I'm closing the issue. We're preparing the CMS Kit documents. Please follow docs.abp.io for updates.
