### ISSUE TITLE
AJAX extension for datatables support router parameter

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#8762]
I have a url: api/author/' + authorId + '/book
DataTables how to load?
abp.libs.datatables.createAjax not support router parameter

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by snowchenlei** [comment]
ABP Framework version:4.2.1
User Interface:MVC
database provider:EF Core
[AJAX DataTable Filter - Best practice in ABP.IO](https://github.com/abpframework/abp/issues/775#issuecomment-459672720)
how to support router parameter And Dto Filter with datatable.net ajax

``` javascript
// config datatable
 var _dataTable = _$table.DataTable(
                abp.libs.datatables.normalizeConfiguration({
                    serverSide: true,
                    paging: true,
                    order: [[1, "asc"]],
                    searching: true,
                    scrollX: true,
                    ajax: abp.libs.datatables.createAjax(_emergencyContactAppService.getList),
})
)
// ServiceProxyScript
snow.hcm.controllers.employees.emergencyContact.getList = function(employeeId, input, ajaxParams) {
      return abp.ajax($.extend(true, {
        url: abp.appPath + 'api/employee/' + employeeId + '/emergency-contact' + abp.utils.buildQueryString([{ name: 'employeeId', value: input.employeeId }, { name: 'sorting', value: input.sorting }, { name: 'skipCount', value: input.skipCount }, { name: 'maxResultCount', value: input.maxResultCount }]) + '',
        type: 'GET'
      }, ajaxParams));
    };
```
error: `input is undefined`

**Comment by maliming** [comment]
```js
ajax: abp.libs.datatables.createAjax(function () {
    return _emergencyContactAppService.getList(employeeId, input);
}),
```
