### ISSUE TITLE
The type or namespace name AbpBlazorMessageLocalizerHelper<> could not be found

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#8766]
* Your **ABP Framework version**.  **4.3.0**
* Your **User Interface** type (Angular/MVC/React... etc.): **Blazor (Server and WebAssembly)**
* Your database provider(EF Core/MongoDB) **EFCore**

Steps to reproduce:

- Create new application using Blazor Server
- Follow BookStore tutorial 

When creating the Books page the code includes (head of page):

**@inject AbpBlazorMessageLocalizerHelper&lt;BookStoreResource> LH**

But I get a warning that **"The type or namespace name AbpBlazorMessageLocalizerHelper<> could not be found"**

![image](https://user-images.githubusercontent.com/69393775/115902924-e3c0b000-a45a-11eb-8e39-1726d3af72bc.png)

If I download the Blazor WebAssembly version from the **abp-examples**, compile and run it, it works ok, but if I run **abp update** on the project to update it to 4.3.0, then try to compile it again, the project won't compile and I get the same problem.

**Comment by maliming** [comment]
hi 

The namespce has been changed.

`using Volo.Abp.AspNetCore.Components.Web;`
