### ISSUE TITLE
When create new form

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#8773]
ABP Framework version: v4.3
UI type: MVC
DB provider: EF Core
Tiered (MVC) or Identity Server Separated (Angular): no

![image](https://user-images.githubusercontent.com/28866278/115953500-8c6f1e00-a4f4-11eb-8198-c574aa1e4929.png)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by recruitans** [comment]
https://support.abp.io/QA/Questions/1126/Bugs--Issues-v43X#answer-6f63d20f-995b-ad4f-5c47-39fc15535636

**Comment by maliming** [comment]
Let's discuss this on the support website.

**Comment by recruitans** [comment]
i didn't see your reponse on support website ?
