### ISSUE TITLE
Proxy Scripts not generated.

### ISSUE THREAD

**Issue by dangminhbk** [abpframework/abp#8778]
**ABP Framework version** : 4.3.0 .
**User Interface** type:  MVC.

My namespace was `MDH.EASYPOS.Sales` , 
My Application Service is 
`public class SaleAppService : CrudAppService<Sale, SaleDto, Guid, PagedAndSortedResultRequestDto, CreateSaleDto, UpdateSaleDto>`, 
I Run Applications and cannot see my api proxy script generated. Doesn't it supposed to be : `mDH.eASYPOS.sales.sale` ? I check in Abp/ServiceProxyScript and see only some default proxy from abp ( tenant, user, etc)

**Comment by maliming** [comment]
* Steps needed to **reproduce** the problem.

**Comment by dangminhbk** [comment]
> * Steps needed to **reproduce** the problem.

Create Abp project ( UI type MVC), naming it with upper case ( ABC.XYZ) , create a simple model

**Comment by dangminhbk** [comment]
@maliming
Create interface ISomethingAppService that implement ICrudAppService ( there is no method in there)
`namespace MDH.EASYPOS.Sales
{
    public interface ISaleAppService :
        ICrudAppService< 
            SaleDto, 
            Guid, 
            PagedAndSortedResultRequestDto,
            CreateSaleDto,
            UpdateSaleDto>
    {
    }
}`

**Comment by maliming** [comment]
hi

Please share the Full and detailed steps.

**Comment by dangminhbk** [comment]
@maliming https://github.com/dangminhbk/Sale/tree/master/src here is the full project, proxy code was generated, but cannot access it from js.

**Comment by dangminhbk** [comment]
@maliming is there different between .Web proxy script and .HttpApi.Host one. I notice that .Web scripts not include api from AppService.

**Comment by davidzwa** [comment]
Would be nice to share `/api/abp/api-definition/` output and see if your controllers/services appear there (or not)
You mention that you cannot access the proxy services from JS. What do you mean with that?

Please provide more details steps from the get-go next time as this is very hard for authors to respond to.
- Definition API output
- Exact controller or remote service you are looking to call
- How are you trying to access the service in MVC (file)
- What is the exception or error?
- Does calling the service in the HttpApi Console Client work or the test variant of it

**Comment by dangminhbk** [comment]
@davidzwa my services appear there `/api/abp/api-definition/` .  I read this document 
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Dynamic-JavaScript-Proxies , It said proxy code will be generated in Abp/ServiceProxyScript, but it not included my service's .

**Comment by davidzwa** [comment]
Are you getting an error in Razor when you call `ISaleAppService`?

**Comment by davidzwa** [comment]
Also try to run `abp generate-proxy`. This is how we do it for Angular. Not sure if this is required for MVC as well.

**Comment by dangminhbk** [comment]
#1469 @maliming . I've found this issues. It not the problem so I closed it for now.
