### ISSUE TITLE
Module projects build error

### ISSUE THREAD

**Issue by GerryGe** [abpframework/abp#878]
I open one of the module projects, such as users, when I build the project ,there 're many errors, like 
"Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to find project information for 'D:\Projects\Github\abp\framework\src\Volo.Abp.MultiTenancy.Abstractions\Volo.Abp.MultiTenancy.Abstractions.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	Volo.Abp.Users.Abstractions	D:\Projects\Github\abp\modules\users\src\Volo.Abp.Users.Abstractions\Volo.Abp.Users.Abstractions.csproj	1	
"

I do as the introduction of the abp, I disabled "Automatically check for missing packages during build in Visual Studio" in the Visual Studio options. and restore Nuget before open the projects, but this still doesn't work .  I would like to know do you have any advice for this issues?

**Comment by akinix** [comment]
First run `dotnet restore` from the command line inside the `modules\users` folder.
Then build the solution in Visual Studio

**Comment by GerryGe** [comment]
Yes, of course, I first run dotnet restore command, it's ok, but I opened the module project in Visual Studio 2018 (v15.9.9), then built, there were many errors. Should I add these referenced projects in the module project Solution?

**Comment by GerryGe** [comment]
> First run `dotnet restore` from the command line inside the `modules\users` folder.
> Then build the solution in Visual Studio

Yes, of course, I first run dotnet restore command, it's ok, but I opened the module project in Visual Studio 2018 (v15.9.9), then built, there were many errors. Should I add these referenced projects in the module project Solution?

**Comment by akinix** [comment]
Can you build successfully from the command line?
I just tested it is OK.
![image](https://user-images.githubusercontent.com/16933380/54413990-97aac980-4732-11e9-91b1-80e441a212e1.png)

**Comment by GerryGe** [comment]
> Can you build successfully from the command line?
> I just tested it is OK.
> ![image](https://user-images.githubusercontent.com/16933380/54413990-97aac980-4732-11e9-91b1-80e441a212e1.png)

Thanks @akinix I've found the reason. I should first open the project in Visual Studio, then run the restore command. If I reverse them, then I'll encounter many errors.
