### ISSUE TITLE
Article is Missing !

### ISSUE THREAD

**Issue by behiunforgiven** [abpframework/abp#8780]
This article is missing and redirects to main page:

[Using the AdminLTE Theme with the ABP Framework MVC / Razor Pages UI
](https://community.abp.io/articles/using-the-adminlte-theme-with-the-abp-framework-mvc-razor-pages-ui-gssbhb7m
)

**Comment by EngincanV** [comment]
Hi @behiunforgiven, can you check your community profile for the article is approved or not? After you submitted your article, it's should be approved for displaying by everyone.

* For navigates to your community profile, you can click the top-right dropdown and after click the profile button.

![community-profile](https://user-images.githubusercontent.com/43685404/115996848-a2aad600-a5e9-11eb-93e5-01eb612224ba.jpg)

* You can view all your articles with their status (Approved - Waiting - Rejected) on your profile page.

**Comment by berkansasmaz** [comment]
Hello, @EngincanV I see the article is approved. 

Thank you for the information. It will be fixed as soon as possible.

**Comment by berkansasmaz** [comment]
We fixed the problem, so I am closing this problem. We will be updating the [community.abp.io](http://community.abp.io/) site soon.

Until then, if you want to access the source of the article, you can look [here](https://github.com/mucahiddanis/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/blob/main/COMMUNTIY-ARTICLE.MD).

Thank you for your understanding and support.
