### ISSUE TITLE
Abp provide Field selection?

### ISSUE THREAD

**Issue by rafaelgfirmino** [abpframework/abp#8785]
["Mobile clients display just a few attributes in a list. They don’t need all attributes of a resource. Give the API consumer the ability to choose returned fields. This will also reduce the network traffic and speed up the usage of the API.
GET /cars?fields=manufacturer,model,id,color"](https://medium.com/@mwaysolutions/10-best-practices-for-better-restful-api-33a25a4e92c1)

Abp provide this ?

**Comment by maliming** [comment]
No. You need to implement it yourself.
