### ISSUE TITLE
Custom HangfireDashboard Authorization

### ISSUE THREAD

**Issue by yerz** [abpframework/abp#8789]
My environment:

- ABP4.2
- No UI
- MySQL DB
- Web API project
- Split identityserver 
---

I need to add authorization for HangfireDashboard. So I added the following code

**HangfireAuthorizationFilter.cs**
``` 
public class HangfireAuthorizationFilter : ApplicationService,IDashboardAuthorizationFilter
    {

        public bool Authorize([NotNull] DashboardContext context)
        {
            var permissionChecker = context.GetHttpContext().RequestServices.GetRequiredService<IPermissionChecker>();
            return AsyncHelper.RunSync(() => permissionChecker.IsGrantedAsync("CMS.Dashboard"));
        }
    }
```

**HttpApiHostModule.cs   - OnApplicationInitialization**
``` 
//HangfireDashboard
            app.UseHangfireDashboard(options: new DashboardOptions
            {
                Authorization = new[] { new HangfireAuthorizationFilter() },
                DashboardTitle = "HangFire Dashboard"
            });
```

I'm through : ` http://my domain/Hangfire ` access

System normally into HangfireAuthorizationFilter method, but it doesn't get any information about the current authorized user;

Is that why I split IdentityServer ? 

I Tried **IPermissionChecker 、ICurrentUser**  I didn't get any useful information

How do I achieve this， thank you .

**Comment by yerz** [comment]
please help me 😢

**Comment by jonechenug** [comment]
It may order by  middleware.The `app.UseHangfireDashboard` may be  used to left after `app.UseAuthentication()`  and ` app.UseAuthorization()`

**Comment by yerz** [comment]
![image](https://user-images.githubusercontent.com/30039842/116951580-d86f4f00-acba-11eb-8e6a-8a5fbfae9542.png)


@jonechenug  hi~ Thank you for your answer. 

but . My order is this  it doesn't work . 

`http://my domain/Hangfire`  After entering HangfireAuthorizationFilter unable to obtain information for the current user permissions


Why is that? thank you 😭
