### ISSUE TITLE
Need to support develop Mobile App with Flutter

### ISSUE THREAD

**Issue by RobersonLuo** [abpframework/abp#8793]
I see the document, it has a React-Native project template, Why not supply a Flutter project template?
please..
Thansk very much!

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/8723

**Comment by XuJin186** [comment]
> I see the document, it has a React-Native project template, Why not supply a Flutter project template? please.. Thansk very much!
Have you thought about generating a Flutter (DIO) proxy via the API-Definition interface

**Comment by RobersonLuo** [comment]
I have not research it. you can try it...

**Comment by XuJin186** [comment]
There's nothing I can do about it
