### ISSUE TITLE
Add widgets to CMS Module

### ISSUE THREAD

**Issue by mgochmuradov** [abpframework/abp#8796]
It would be good if we could create **reusable Widgets** in the CMS module, and use them **in Pages**

Usage in pages could be something like:
```
[widgetName poperty="value"]
```

It would be even better if we could also use MVC widgets this way.

**Comment by enisn** [comment]
Hi @mgochmuradov,

Most of the features have components such as [CommentingViewComponent](https://github.com/abpframework/abp/blob/dev/modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/CmsKit/Shared/Components/Commenting/CommentingViewComponent.cs), [RatingViewComponent](https://github.com/abpframework/abp/blob/dev/modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/CmsKit/Shared/Components/Rating/RatingViewComponent.cs) and others...

Visit [Components Folder](https://github.com/abpframework/abp/tree/dev/modules/cms-kit/src/Volo.CmsKit.Public.Web/Pages/CmsKit/Shared/Components)
