### ISSUE TITLE
abp-modal is broken in 4.3 Angular

### ISSUE THREAD

**Issue by gregbrant2** [abpframework/abp#8804]
* Your **4.3**.
* Your **User Interface** type Angular
* Your database provider: EF
* Exception message and **stack trace** if available (check the logs). N/A
* Steps needed to **reproduce** the problem. 

As per this issue https://github.com/abpframework/abp/issues/8110#issuecomment-826942649

The abp-modal is now broken in new and different ways.

I've upgraded the repro to 4.3:
https://github.com/gregbrant2/abp-nested-modals/tree/master

Now if you checkout and run that solution, clicking "Open Modal" in ABP Modal card shows the modal, but there is no modal-open class added to the body, so you can't scroll that modal. Clicking the "Open Inner Modal" button does add the modal-open and you can scroll that second modal. Closing that modal removes the modal-open class again, and you can't scroll the outer modal.

**Comment by bnymncoskuner** [comment]
We use ng-bootstrap modal within `abp-modal`. I've just checked your repo and found out that you defined your inner modal as a child of the outer one as follows

```html
<abp-modal [(visible)]="isModalOpen">
   <!-- ... -->
      <abp-modal [(visible)]="isModalOpen2">
          <!-- ... --> 
      </abp-modal>
</abp-modal>
```

Simply move inner `modal` to the outside of first `modal` as follows:

```html
<abp-modal [(visible)]="isModalOpen">
    <!-- ... -->
</abp-modal>

<abp-modal [(visible)]="isModalOpen2">
     <!-- ... --> 
</abp-modal>
```

I've tested this with your code and scrolling works as intended.
