### ISSUE TITLE
How do I wrap WebAPI Like Abp Boilerplate

### ISSUE THREAD

**Issue by lament0** [abpframework/abp#8805]
When I write an WebApi with ABP.VNEXT, it returns a variety of values, and I find that the ABP BoilerPlate has the **[ WarpResult ]**  Or **[DontWrapResult]** Attribute to control whether to wrap the return value,Like Switch.

This is ABP BoilerPlate AjaxResponseBase
{
  result: null,
  "targetUrl": null,
  "success": true,
  "error": null,
  "unAuthorizedRequest": false,
  "__abp": true
}
![image](https://user-images.githubusercontent.com/25712599/116119658-40d59380-a6f1-11eb-8f35-5a35d41dbe92.png)
![image](https://user-images.githubusercontent.com/25712599/116119702-49c66500-a6f1-11eb-8835-c78ab3359b2a.png)
![image](https://user-images.githubusercontent.com/25712599/116119865-78444000-a6f1-11eb-9e7c-0775ca479543.png)

I want something like **[ WarpResult ]** Attribute    to control my webAPI in volo.Abp

**Comment by maliming** [comment]
You can implement it yourself.

https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.AspNetCore/AspNetCore/Mvc/Results/AbpResultFilter.cs#L10
