### ISSUE TITLE
Microservices Demo - Null input.Sorting at ProductAppService

### ISSUE THREAD

**Issue by brunobertechini** [abpframework/abp#881]
When running the latest version, in the backend admin app, when you list products we've got an exception. By looking at the logs, the input.Sorting parameter that goes to GetListPagedAsync is null. Also, the unit test is failing.

I have added a default property for sorting in the ProductAppService.

[ProductAppService.cs#L31](https://github.com/abpframework/abp/blob/8ce2bf8eef0d3bfec99c454cbbcfbc5be399bf74/samples/MicroserviceDemo/modules/product/src/ProductManagement.Application/ProductManagement/ProductAppService.cs#L31)

`.OrderBy(input.Sorting")` -- original
`.OrderBy(input.Sorting ?? "Name")` -- modified

Final method:

```c#
public async Task<PagedResultDto<ProductDto>> GetListPagedAsync(PagedAndSortedResultRequestDto input)
        {
            await NormalizeMaxResultCountAsync(input);

            var products = await _productRepository
                .OrderBy(input.Sorting ?? "Name")
                .Skip(input.SkipCount)
                .Take(input.MaxResultCount)
                .ToListAsync();

            var totalCount = await _productRepository.GetCountAsync();

            var dtos = ObjectMapper.Map<List<Product>, List<ProductDto>>(products);

            return new PagedResultDto<ProductDto>(totalCount, dtos);
        }
```

I am submitting PR for this fix.

**Comment by dejancg** [comment]
Might be a better idea to modify the OrderBy method to check for null input? Since we don't know if every entity out there would contain the property "Name".

**Comment by brunobertechini** [comment]
It would be good but this is external library (Dynamic linq if I am not wrong)
