### ISSUE TITLE
Service to abp service authentication

### ISSUE THREAD

**Issue by Gangadhar-champs** [abpframework/abp#8812]
If you're creating a bug/problem report, please include followings:

* Your ABP Framework version 4.2.2
* Your **User Interface** type Angular
How to implement external service to abp service 
authentication. We have an api application created via angularUi wizard. Since all application services are decorated with Authorize, these cannot be called from any external service or azure function. What approach needs to be followed to achieve above scenario to connect to abo service

**Comment by maliming** [comment]
ABP is using authentication that provides by Microsoft.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-5.0
https://docs.abp.io/en/abp/latest/Authorization
