### ISSUE TITLE
Redirection after click on the logo of the login page navbar

### ISSUE THREAD

**Issue by joernz** [abpframework/abp#8816]
* Your **ABP Framework version**. 4.3
* Your **User Interface** type Angular
* Your database provider EF Core

with the start template:

through the login button on the app homepage or the url `localhost:4200\account\login`,
I will be redirected to `localhost:44355/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3...`

then, when I click on the logo on the navbar, it will end up with Swagger UI page `localhost:44355/swagger/index.html`, instead of `localhost:4200` where the app homepage is and I intended to go back to. How can I prevent this?

and with this redirection of login page from `localhost:4200\account\login` to `localhost:44355/Account/Login?ReturnUrl=%2...` the `ReplaceableComponentsService` is not working for `eAccountComponents.Login`.
Other Replacements are working fine, since they are all on `localhost:4200\` I guess.
If possible, how to make the login component like other account components stay with `localhost:4200\account\xxx`?

thanks for the help

**Comment by mehmet-erim** [comment]
Hi @joernz

ABP Angular UI uses the authorization code flow by default. Learn more about the authorization in Angular UI:
https://docs.abp.io/en/abp/latest/UI/Angular/Authorization

According to the authorization code flow, the user is redirected to an external login page which is built with MVC. So, if you need to customize the login page, please follow [this community article](https://community.abp.io/articles/how-to-customize-the-login-page-for-mvc-razor-page-applications-9a40f3cd).

If you want to navigate the login page in Angular UI (/account/login), you should use the resource owner password flow. See this doc to learn how to switch your authentication flow:

https://docs.abp.io/en/abp/latest/UI/Angular/Account-Module
