### ISSUE TITLE
how to display setting items(value) in setting manager ui?

### ISSUE THREAD

**Issue by ericzzhou** [abpframework/abp#8830]
how to display setting items(value) in setting manager ui?

**Comment by ericzzhou** [comment]
abp vnext 4.3

**Comment by realLiangshiwei** [comment]
* Angular: https://docs.abp.io/en/abp/latest/UI/Angular/Custom-Setting-Page
* MVC: https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Web/Pages/SettingManagement/Components/EmailSettingGroup/EmailSettingGroupViewComponent.cs
* Blazor: https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Blazor/Pages/SettingManagement/EmailSettingGroup/EmailSettingGroupViewComponent.razor.cs

**Comment by ericzzhou** [comment]
> * Angular: https://docs.abp.io/en/abp/latest/UI/Angular/Custom-Setting-Page
> * MVC: https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Web/Pages/SettingManagement/Components/EmailSettingGroup/EmailSettingGroupViewComponent.cs
> * Blazor: https://github.com/abpframework/abp/blob/dev/modules/setting-management/src/Volo.Abp.SettingManagement.Blazor/Pages/SettingManagement/EmailSettingGroup/EmailSettingGroupViewComponent.razor.cs

I want to custom some settings and show in setting UI.

**Comment by realLiangshiwei** [comment]
Please check the links I provided: https://github.com/abpframework/abp/issues/8830#issuecomment-828425874

It would be easy if we provide documentation.

I will add documentation in 4.4:  https://github.com/abpframework/abp/issues/2187
