### ISSUE TITLE
defaultResourceName is ignored after upgrading Angular project to ABP 4.3.0

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#8832]
> 4.3.0
> Angular
> EF Core

Indicating `defaultResourceName` in `environment` object used to work properly in **ABP 3.3.2**. After upgrading all solutions to the newest **4.3.0** this parameter seems to be ignored:

```
localization: {
    defaultResourceName: 'CentralTools'
}
```

Accordingly, resources are not extracted and I am getting these warnings in Debug console:

> Localization source name is not specified and the defaultResourceName was not defined!

Setup in **shared.module.ts**, **app.module.ts** is exactly the same as in the autogenerated Angular project, i.e.:

```
    CoreModule.forRoot({
      environment,
      registerLocaleFn: registerLocale(),
    }),
```

Importing / exporting module is also set up in the same way as in autogenerated Angular project.

**Comment by EngincanV** [comment]
Hi @alexandis, `defaultResourceName` not need to be specified. Therefore you can delete the `localization` section from your **environment.ts** (and **environment.prod.ts**) file.

After that, you can configure localization options in your ***.HttpApi.Host** module as below.

```cs
public override void ConfigureServices(ServiceConfigurationContext context)
{
     //other configurations...

     Configure<AbpLocalizationOptions>(options =>
     {
           options.Languages.Add(new LanguageInfo("cs", "cs", "Čeština"));
           options.Languages.Add(new LanguageInfo("en", "en", "English"));
           options.Languages.Add(new LanguageInfo("sl", "sl", "Slovenščina"));
           options.Languages.Add(new LanguageInfo("tr", "tr", "Türkçe"));
           options.Languages.Add(new LanguageInfo("zh-Hans", "zh-Hans", "简体中文"));
           options.Languages.Add(new LanguageInfo("de-DE", "de-DE", "Deutsche", "de"));
           options.Languages.Add(new LanguageInfo("es", "es", "Español", "es"));
     });
}
```

After those configurations, your application should be working properly.
