### ISSUE TITLE
After adding the lepton source code to the project - Could not load file or assembly 'Volo.Abp.LeptonTheme.Management.Domain.Shared

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#8835]
v4.3.0, MVC, EF

![image](https://user-images.githubusercontent.com/28866278/116451351-068d0300-a865-11eb-9481-f654f3952092.png)

![image](https://user-images.githubusercontent.com/28866278/116451359-0ab92080-a865-11eb-864a-b5eec91ff933.png)

**Comment by maliming** [comment]
Please get help on the support website.
https://support.abp.io
