### ISSUE TITLE
Blazor webassembly Localization problem after deployment

### ISSUE THREAD

**Issue by LuisPignataro** [abpframework/abp#8837]
Using the framework version 4.2 and 4.3, with the Blazor Webassembly client, localized texts are not displayed in the hosted application.
In debug it works perfect, but not in hosting.
Both the api and the client are hosted in two azure webapp.
There are no errors on the client side, nor on the server.

I am using the template from version 4.2, which I later migrated to 4.3. In both cases the same problem occurs. EntityFramework and sqlserver are used, but the texts are in the .json resource.

I inserted the following code to investigate the problem, and I get error **No manifests exist for the current culture.** in the call to GetAllStrings ()

```
try
            {
                Console.WriteLine("-----------------------------------------------");
                var lang = await LanguageProvider.GetLanguagesAsync();

                Console.WriteLine(CultureInfo.CurrentCulture.Name);

                var AbpLocalizationOptions = abpLocalizationOptions.Value;

                Type resourceType = typeof(ContabilidadResource);
                var resource = AbpLocalizationOptions.Resources.GetOrDefault(resourceType);

                Console.WriteLine((resource == null).ToString(), resource);

                var Localizer = InnerFactory.Create(resourceType);

                Console.WriteLine((Localizer == null).ToString(), Localizer);

                Console.WriteLine(Localizer.GetString("LongWelcomeMessage"));

                var all = Localizer.GetAllStrings();
                Console.WriteLine($"{all.Count()} {all.First().Name}", all);

                Console.WriteLine($"Contributors : {resource.Contributors.Count}");

                Console.WriteLine("-----------------------------------------------");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message, ex);
            }
```
I already appreciate any guidance to find the problem. I checked the source code of the framework and other issues but I can't find the solution.

**Comment by maliming** [comment]
> localized texts are not displayed in the hosted application.

Can you try to publish the app locally via `dotnet publish` command then run it?

**Comment by LuisPignataro** [comment]
Hello @maliming , thanks for your reply.
I did test publishing with `dotnet publish` and run in webapp hosting and in iisexpress and same results.
Maybe I didn't understand the test you want me to do correctly.
In which hosting you want it to run. Directly from the filesystem? Using dotnet run?
I think the only result would be for it to be published in debug.
I had already tried that and it doesn't work.
What other information can I provide to identify the problem?

**Comment by maliming** [comment]
hi

Can you provide a project and steps? I can download and check it.

**Comment by LuisPignataro** [comment]
Hi, yes, this repo contains a minimal project with the problem https://github.com/LuisPignataro/abpissue

Example image showing the problem.

![image](https://user-images.githubusercontent.com/9435347/116704784-2a099800-a9a2-11eb-9b08-3204bdcdb8cc.png)

**Comment by maliming** [comment]
Add `Microsoft.Extensions.FileProviders.Embedded` package to your DomainShared project.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="5.0.*" />
  </ItemGroup>

```

https://github.com/abpframework/abp/blob/dev/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Domain.Shared/MyCompanyName.MyProjectName.Domain.Shared.csproj#L28

**Comment by LuisPignataro** [comment]
Thank you very much, that was it!
