### ISSUE TITLE
api-definition cannot find API endpoints with multiple RouteAttribute

### ISSUE THREAD

**Issue by colinin** [abpframework/abp#8839]
ABP Framework version: 4.3.0

Repetition of the repository: https://github.com/colinin/ApiDefintionTest

Problem of repetition:

Define Dto:

```c#

public class GetValueInput
{
    [Required]
    public string Id { get; set; }

    public string Optional1 { get; set; }

    public string Optional2 { get; set; }

    [Required]
    public string Required { get; set; }
}

public class ValueOuputDto
{
    public string Value { get; set; }
}

```

Define Controller:

```c#

[RemoteService(Name = "ApiDefintionTest")]
[Route("api/app/values")]
public class ValuesController : AbpController
{
    [HttpGet]
    [Route("{Id}/{Required}")]
    [Route("{Id}/{Required}/{Optional1}")]
    [Route("{Id}/{Required}/{Optional2}")]
    [Route("{Id}/{Required}/{Optional1}/{Optional2}")]
    public virtual Task<ValueOuputDto> GetAsync(GetValueInput input, [FromServices] IJsonSerializer jsonSerializer)
    {
        var dto = new ValueOuputDto
        {
            Value = jsonSerializer.Serialize(input)
        };

        return Task.FromResult(dto);
    }
}

```

This is normal in swagger, where two endpoints are found

![Swagger endpoints](https://github.com/colinin/ApiDefintionTest/blob/main/Images/WeChat_20210429100931.png)

But api/abp/api-definition only has

![api definition endpoints](https://github.com/colinin/ApiDefintionTest/blob/main/Images/WeChat_20210429101037.png)

**Comment by colinin** [comment]
I think it has to do with the naming of the defined API:

https://github.com/abpframework/abp/blob/675ddecc5f74b8163b803e08a7ac29663cc3faf6/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AspNetCoreApiDescriptionModelProvider.cs#L69-L122

https://github.com/abpframework/abp/blob/675ddecc5f74b8163b803e08a7ac29663cc3faf6/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/AspNetCoreApiDescriptionModelProviderOptions.cs#L38-L59

**Comment by maliming** [comment]
Dynamic API calls will be very troublesome when an API has multiple routes because you need to match it based on parameters.
The generated angular proxy script may also have problems. I'm not sure,

**Comment by colinin** [comment]
Through **ApiParameterDescription.IsRequired** judgment can generate multiple proxy endpoint,  (javascript will be simpler than c # dynamic HTTP client)

**Comment by maliming** [comment]
You can give it a try, any PR is welcome.

**Comment by colinin** [comment]
I'll give it a try
