### ISSUE TITLE
blazor server UserManagement.razor how to add Name column to the page?

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#8840]
* **ABP Framework version**:  3.3-final .
* Blazor Server
* Database provider: EF Core
* 

I just want add the name column to the users page, is there a way to add a column to the page instead a custom page?

I saw the code : 
` UserManagementTableColumns.AddRange(GetExtensionTableColumns(IdentityModuleExtensionConsts.ModuleName,
                IdentityModuleExtensionConsts.EntityNames.User));`
how can I set the columns?

Thanks!

**Comment by maliming** [comment]
I think this available when the version >= 4.3

https://github.com/abpframework/abp/pull/6647

**Comment by juchunwei** [comment]
@maliming 
Thank you!  It's easier if the UserManagementTableColumns can be protected not private.

**Comment by maliming** [comment]
Please check https://github.com/abpframework/abp/pull/6647#issue-540066788
