### ISSUE TITLE
The CMS-Kit public page controller not registered, cannot visit a page by slug from public site.

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#8841]
* Your **ABP Framework version**. Ver 4.3.0
* Your **User Interface** type : MVC
* Your database provider(EF Core/MongoDB): EF Core
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
* 
When visit a page by slug from the public site, the page cannot be opened.

With 4.3.0, the CMS-Kit public page controller not registered, cannot visit a page by slug from public site.

The error logs as below: 2021-04-10 15:30:18.186 +08:00 [INF] Executing endpoint 'Volo.CmsKit.Public.Pages.PagesPublicController.FindBySlugAsync (Volo.CmsKit.Public.HttpApi)' 2021-04-10 15:30:18.201 +08:00 [INF] Route matched with {area = "cms-kit", action = "FindBySlug", controller = "PagesPublic", page = ""}. Executing controller action with signature System.Threading.Tasks.Task1[Volo.CmsKit.Public.Pages.PageDto] FindBySlugAsync(System.String) on controller Volo.CmsKit.Public.Pages.PagesPublicController (Volo.CmsKit.Public.HttpApi). 2021-04-10 15:30:18.264 +08:00 [ERR] ---------- RemoteServiceErrorInfo ---------- { "code": null, "message": "An internal error occurred during your request!", "details": null, "data": {}, "validationErrors": null }

2021-04-10 15:30:18.265 +08:00 [ERR] The requested service 'Volo.CmsKit.Public.Pages.PagesPublicController' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency. Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Volo.CmsKit.Public.Pages.PagesPublicController' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.`

**Comment by enisn** [comment]
Hi @viewtance 

_It looks like there are some dependency issues_

Can I ask how did you add CmsKit? Via CLI or Manually?

**Comment by viewtance** [comment]
@enisn I added cms-kit via cli template come from 4.3.0-rc.2, I have fixed this issue by update the PagesPublicController code as below:
`[RequiresGlobalFeature(typeof(PagesFeature))]
    [RemoteService(Name = CmsKitPublicRemoteServiceConsts.RemoteServiceName)]
    [Area("cms-kit")]
    [Route("api/cms-kit-public/pages")]
    public class PagesPublicController : **CmsKitPublicControllerBase**, IPagePublicAppService
    {
        protected IPagePublicAppService PageAppService { get; }

        public PagesPublicController(IPagePublicAppService pageAppService)
        {
            PageAppService = pageAppService;
        }

        [HttpGet]
        [Route("{slug}")]
        public virtual Task<PageDto> FindBySlugAsync(string slug)
        {
            return PageAppService.FindBySlugAsync(slug);
        }
    }`
The bolded code was missed.
