### ISSUE TITLE
\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared\wwwroot\libs\abp\aspnetcore-mvc-ui-theme-shared\datatables\datatables-extensions.js

### ISSUE THREAD

**Issue by ercanciftci** [abpframework/abp#8843]
Abp 4.3

\abp\framework\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared\wwwroot\libs\abp\aspnetcore-mvc-ui-theme-shared\datatables\datatables-extensions.js  on Line 134

if (field.text) {
       $dropdownButton.append(htmlEncode(fieldItem.text));
} else {
       $dropdownButton.append(htmlEncode(localize("DatatableActionDropdownDefaultText")));
}

![image](https://user-images.githubusercontent.com/83379389/116537422-e0ac4080-a8ee-11eb-9a0c-b839517a2c07.png)

fieldItem is undefined. 

You must change fieldItem variable as field variable.

@ebicoglu  @hikalkan @cotur

**Comment by okutbay** [comment]
We are also having the same problem on our project. Thanks for the ticket @ercanciftci

**Comment by cotur** [comment]
If you wonder how to get latest code for your `4.3` version application before new patch release.

https://github.com/abpframework/abp/pull/8854#issuecomment-829971415
