### ISSUE TITLE
Is there any way, we could customise UserEto. Like add "usertype" property in UserEto.

### ISSUE THREAD

**Issue by 0andy** [abpframework/abp#8850]
public virtual async Task HandleEventAsync(EntityUpdatedEto<UserEto> eventData)

Example: 
I have two services: cmskit and supportkit.

The UserType enum:
enum UserType
{
    None,
    CmsUser,
    SupportUser
}

CmsUser only register in CmsKit service.
SupportUser only register in Supportkit.

----
You know, I want to use the usertype to filter the event.
So Is it any possible to customise UserEto? Or any suggestions?

Appreciated!
Thanks

**Comment by realLiangshiwei** [comment]
No.
You should publish your own events.

https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#idistributedeventbus
