### ISSUE TITLE
Order/timing of menu contributor in Blazor WASM

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#8851]
* **ABP Framework version** 4.3
* **User Interface** Blazor WASM
* Your database provider(EF Core/MongoDB) EF Core
* Exception message and **stack trace** if available (check the logs). None found

* Steps needed to **reproduce** the problem.
I've created several modules within my application. Each currently has a menu contributor defined and adds one item to the main menu, which links to the index page of the module. 
Basically all functionality in the application requires an authenticated user, so in addition to setting Authorize tags I wrapped the addition of the menu items in the contributors in an if statement checking the value of currentUser.IsAuthenticated (using the Account.Manage item from the application's menu contributor as an example)

![Notification_Center](https://user-images.githubusercontent.com/17837172/116586924-cfebd280-a8ce-11eb-9129-62ca96b0360b.png)

This works, but after login the items do not show up. A refresh is required for the menu items to populate:
![RefreshForAuthenticated-Module](https://user-images.githubusercontent.com/17837172/116587100-fc9fea00-a8ce-11eb-87f1-e42843ff8f53.gif)

I thought it might be an issue with adding the items from the menu contributors in the modules, so I tried adding one the same way (checking to see if the user is authenticated) from the menu contributor in the application itself, and the behavior was basically the same (note the "FromPortal" item, which is added in the menu contributor of the application, does not show up until after a refresh either)

![RefreshForAuthenticated-Portal](https://user-images.githubusercontent.com/17837172/116587194-1b05e580-a8cf-11eb-957b-8fc4fa7fe288.gif)

I left the same "FromPortal" item in place but removed the surrounding check for currentUser.IsAuthenticated and the item shows up correctly immediately when the page is rendered. 

![FromPortalNoAuth](https://user-images.githubusercontent.com/17837172/116587738-97002d80-a8cf-11eb-9480-6f793d01d40f.gif)

 
I thought perhaps I could add a call to StateHasChanged() after the addition of the menu items, but I am not clear if I can do this from a menu contributor (haven't been able to figure out how to so far).

Any thoughts would be appreciated!

**Comment by maliming** [comment]
The **AuthenticationStateChanged** event is not executed immediately, the menu system will execute it first, and then we will receive the event.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Components.Web/Volo/Abp/AspNetCore/Components/Web/Security/AbpComponentsClaimsCache.cs#L27

**Comment by jhulbertpmn** [comment]
Thanks for the explanation and it looks like a change for that is planned for a 4.3 patch/4.4 release? I can work around it for now

**Comment by emilsjog** [comment]
I'm facing the same issue and are running blazor-server on 4.3.3 and there are actually no plans on migrating to 5.0. 
Is this not fixed in the new 4.4.1 release?

**Comment by maliming** [comment]
Due to the limit of Blazor itself, we are still looking for a solution.

**Comment by emilsjog** [comment]
@maliming Ok I see.. I noticed this first when we hade the site setup as "Always running" on the IIS application pool. Have not seen this at all during development when we always restarts the site. Could it be that the cache is invalid?
