### ISSUE TITLE
Is it possible only use Phone Number to register and "Create new User"?

### ISSUE THREAD

**Issue by 0andy** [abpframework/abp#8852]
I see that MS ask email as require.
So we cannot register or "New User" without email?

Is it right?

Any ways we could register and "new user" with only Phone Number.

Thanks.

**Comment by xyfy** [comment]
I set the email as  `phone+@+domain.com`
when change phone ,will also change the default email which user not changed

**Comment by 0andy** [comment]
Yes, this works. Thx
But we want the customer to register with phone at the first time and later if they like they could bind their email.
So, I think should use your similar way.
