### ISSUE TITLE
Object Extension: Property order is unstable

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#8858]
Reported at https://support.abp.io/QA/Questions/1234/Extra-Properties-order-and-validation#answer-6b0eb63a-ff39-48e7-1b23-39fc2c719128

It is probably related with ConcurrentDictionary usage.

**Comment by leonardotvd** [comment]
It doesn't work. The change was only to create an alphabetic order based on the field name. It makes no sense. I need to group my fields and show them in an order that makes sense for the user and subject. It doesn't work for me. I need one more property in to define the field order.

**Comment by maliming** [comment]
hi @leonardotvd Please create a new issue and explain it in detail.
