### ISSUE TITLE
Move Identity & Tenant Management menu items under the new Administration menu item

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#886]
see https://github.com/abpframework/abp/issues/885
This will also test 2 level deep top menu for the basic theme.

**Comment by yekalkan** [comment]
> This will also test 2 level deep top menu for the basic theme.

![image](https://user-images.githubusercontent.com/5793291/54603357-254d2880-4a55-11e9-82fc-c75c241998e3.png)
