### ISSUE TITLE
Allow to customize EF Core mapping of an entity of an existing module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8862]
![image](https://user-images.githubusercontent.com/1210527/116768095-dac47580-aa3c-11eb-983e-c79e9df93902.png)

Then the configuration is auto applied in [EfCoreObjectExtensionManagerExtensions.ConfigureEfCoreEntity](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/ObjectExtending/EfCoreObjectExtensionManagerExtensions.cs#L116). In this way, no change required in existing modules.

**Comment by realLiangshiwei** [comment]
We need to call the `ConfigureByConvention` method at the end. if not, we cannot customize some entity mappings, e.g: changing the maximum field length, it is always overridden by the module mapping.

![image](https://user-images.githubusercontent.com/16813853/117797314-70a0a180-b282-11eb-89e6-f5c510b759eb.png)

**Comment by hikalkan** [comment]
In that case, I suggest to create another extension method, like `b.ApplyObjectExtensionMappings()` and not do it in the ConfigureByConvention method. We call ApplyObjectExtensionMappings() at the end.

**Comment by realLiangshiwei** [comment]
ok.
