### ISSUE TITLE
Allow to customize configuration of a dbcontext via object extension manager

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8863]
As an improvement similar to #8862

![image](https://user-images.githubusercontent.com/1210527/116768191-6b9b5100-aa3d-11eb-85e0-f7fcbc31908c.png)

Here, I am trying to customize IdentityDbContext mappings in a static context (customized IdentityUser and also mapped a new entity). To make this work, IdentityDbContextModelBuilderExtensions.ConfigureIdentity method should make such a call:

![image](https://user-images.githubusercontent.com/1210527/116768252-e49aa880-aa3d-11eb-9f92-f9a0ba056c41.png)

Please make such calls in all modules (including volo)

**Comment by realLiangshiwei** [comment]
But the `dbContext` is not an extensible object, should we make `AbpDbContext` implement the `IHasExtraProperties` interface?

https://github.com/abpframework/abp/blob/1153bb3cd783b65f894d9a17eb22b4b834d98a34/framework/src/Volo.Abp.ObjectExtending/Volo/Abp/ObjectExtending/ObjectExtensionManager.cs#L53

**Comment by hikalkan** [comment]
Implementing `IHasExtraProperties` for `AbpDbContext` is not a good idea, and I think we don't get/set extra properties on this object.
However, I see `ObjectExtensionManager.AddOrUpdate` forces us to implement it, so you're right, I didn't think about it. We have two options;

1. Remove `where TObject : IHasExtraProperties` restrictions, so any object can be extensible.
2. Create another system to configure and apply the mapping.

I believe we can go with the option 1. An object should not have to implement IHasExtraProperties when we just want to make some configuration on the type, rather than adding new properties. In this way, we can reuse the system. However, API will be open to misusages.

What do you think @realLiangshiwei & @maliming is that reasonable?

**Comment by maliming** [comment]
> Remove where TObject : IHasExtraProperties restrictions, so any object can be extensible.

I agree with this.

**Comment by realLiangshiwei** [comment]
I agree with options 1

We need remove all `IHasExtraProperties` restrictions of `ObjectExtensionManager` and `ObjectExtensionInfo` classes.

https://github.com/abpframework/abp/blob/1153bb3cd783b65f894d9a17eb22b4b834d98a34/framework/src/Volo.Abp.ObjectExtending/Volo/Abp/ObjectExtending/ObjectExtensionManager.cs#L53

https://github.com/abpframework/abp/blob/1153bb3cd783b65f894d9a17eb22b4b834d98a34/framework/src/Volo.Abp.ObjectExtending/Volo/Abp/ObjectExtending/ObjectExtensionInfo.cs#L26

But should we change the class name? e.g: `ObjectConfigurationExtensionManager`. @hikalkan  what do you think

**Comment by hikalkan** [comment]
Which class name? Renaming `ObjectExtensionManager` to `ObjectConfigurationExtensionManager`? That's an impossible breaking change :)
