### ISSUE TITLE
The permission change did not take effect immediately

### ISSUE THREAD

**Issue by K-Artisan** [abpframework/abp#8864]
The permission change did not take effect immediately

Scenario: User A modifies user B's permissions, and user B's permissions do not take effect immediately

Replay steps:

1. Create the solution with the following command (abp version:4.3) :

```
abp new Acme.BookStore -t app -ui mvc -d ef -dbms SqlServer --tiered
```

2. Use account : "admin" to login.

​    Open the page: https://localhost:44323/Identity/Users, Create a new  accounts: TestUser 

3. Login with account: "TestUser". This account does not currently  have 'Role management` permissions

4.   User  "admin"  add the "Role Management" permissions to user "TestUser"

5. The “TestUser” user  refreshes the page or login again and finds that he has not obtained the  'Role management` permissions 

   

 Save permission source code :[PermissionManagementModal](https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/modules/permission-management/src/Volo.Abp.PermissionManagement.Web/Pages/AbpPermissionManagement/PermissionManagementModal.cshtml.cs)

```C#
 public class PermissionManagementModal : AbpPageModel
 {
        public virtual async Task<IActionResult> OnPostAsync()
        {

            //......
            await PermissionAppService.UpdateAsync(
                ProviderName,
                ProviderKey,
                new UpdatePermissionsDto
                {
                    Permissions = updatePermissionDtos
                }
            );

            await LocalEventBus.PublishAsync(
                new CurrentApplicationConfigurationCacheResetEventData()
            );
            
            return NoContent();
        }
 }
```

Event handler is:[ MvcCurrentApplicationConfigurationCacheResetEventHandler  ](https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.AspNetCore.Mvc.Client/Volo/Abp/AspNetCore/Mvc/Client/MvcCurrentApplicationConfigurationCacheResetEventHandler.cs)

But this event ( [CurrentApplicationConfigurationCacheResetEventData](https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.AspNetCore.Mvc.Contracts/Volo/Abp/AspNetCore/Mvc/ApplicationConfigurations/CurrentApplicationConfigurationCacheResetEventData.cs)) is used to invalidate **current user's** cached configuration. 

 Is there any soloution to  above problems？Like this ?: [Overriding a Page Model (C#)](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface)

Thanks.

**Comment by clinically-au** [comment]
Yes, see #8620
