### ISSUE TITLE
Can't find Volo.Abp.SettingManagement.HttpApi.Client v 4.2.0 on nuget package manager 

### ISSUE THREAD

**Issue by abdumostafa** [abpframework/abp#8866]
I'm trying to resolve a dependency problem on my solution but I can't find Volo.Abp.SettingManagement.HttpApi.Client v 4.2.0 anymore !
just the new 4.3.x found, I think this issue might be on other Abp packages too

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/7669

Because `Volo.Abp.SettingManagement.HttpApi.Client` is a new package of 4.3 milestone
