### ISSUE TITLE
ICurrentUser add Change method（like ICurrentTenant）

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#887]

**Comment by hikalkan** [comment]
I hesitated to add this, but we can consider it. Do you give a sample use case of that?

**Comment by hikalkan** [comment]
You can use this: https://github.com/abpframework/abp/blob/dev/docs/en/CurrentUser.md#changing-the-current-principle

**Comment by xuanhe168** [comment]
I need to actually change the value in CurrentUser instead of short-term mocking how to do it?
