### ISSUE TITLE
get abp localization currentCulture object values

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#8871]
abp v4.3

`abp.localization.currentCulture` is not undefined.
However, how to access currentCulture properties (name, twoLetterIsoLanguageName,...) from this object?
I always get undefined from currentCulture.xxxx in javascript.
Thank you.

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Localization

**Comment by maliming** [comment]
> abp.localization.currentCulture is not undefined.

* Steps needed to **reproduce** the problem. 

 The page needs to load **abp.js**, Can you check?

https://github.com/abpframework/abp/blob/dev/npm/packs/core/src/abp.js#L74

**Comment by leonkosak** [comment]
@maliming, my mistake.  `abp` object is present.
`abp.localization.currentCulture` **also has a value** (json object).

https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Localization#abp-localization-currentculture

The following properties have undefined value:
`abp.localization.currentCulture.name`
`abp.localization.currentCulture.cultureName`
`abp.localization.currentCulture.twoLetterIsoLanguageName`
all other `abp.localization.currentCulture.xxxx` properties

I am using abp v4.3, MVC UI.

**Comment by maliming** [comment]
hi 

Steps needed to reproduce the problem.

**Comment by leonkosak** [comment]
I upgraded from v4.2.2 to v4.3 - compared all files (.csproj,...).
Open any .cshtml and add:

```
<script>
console.log(abp.localization.currentCulture.xxxx)
</script>
```

**Comment by maliming** [comment]
Add it to `scripts ` section.

```cs
@section scripts {
    <script>
    console.log(abp.localization.currentCulture)
    </script>
}
```

**Comment by leonkosak** [comment]
`abp.localization.currentCulture` is not a problem (has value). abp.localization.currentCulture.**XXXX** (accessing sub-properties) are all undefined.

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/116974494-cdcfac80-acf0-11eb-9525-50995f65aa37.png)

![image](https://user-images.githubusercontent.com/6908465/116974476-c90af880-acf0-11eb-9409-4e0f2654fbaa.png)

**Comment by leonkosak** [comment]
```
<script>
    $(function () {
...
    });
</script>
```

Adding console.log around $(function () {}); solved issue.
Thank you.
