### ISSUE TITLE
AbpAspNetCoreMvcModule should expose unified System  API resource

### ISSUE THREAD

**Issue by crashsol** [abpframework/abp#888]
![1](https://user-images.githubusercontent.com/17925647/54584071-372ccc80-4a51-11e9-832c-8b7ccfc0fdfd.png)
![2](https://user-images.githubusercontent.com/17925647/54584072-37c56300-4a51-11e9-8a97-1a20de8df7b7.png)
![3](https://user-images.githubusercontent.com/17925647/54584320-f97c7380-4a51-11e9-9c84-941c98cba4ba.png)

The resources of these systems should have a unified style , because when I use NSwag, it will generate duplicate Client to me, resulting in errors

**Comment by hikalkan** [comment]
Current design is intentionally done like that. But I haven't tried with Nswag. What would you suggest?

**Comment by crashsol** [comment]
I solve this problem by setting nswag generation Operation Generation Model (MuliteClientsFromOperationId)。
But I suggest the system api need Unified Style

**Comment by hikalkan** [comment]
URLs starting with '/api/abp/' are REST APIs which returns JSON result.
URLs starting with `/Abp/` are not APIs actually. They are regular actions intended to be used in MVC applications.
So, I wanted to separate APIs from other actions.

**Comment by crashsol** [comment]
ok，thanks for you reply！
