### ISSUE TITLE
Is it possible to create/register/new user without email?

### ISSUE THREAD

**Issue by 0andy** [abpframework/abp#8892]
I see here is Required. Is it possible we can remove/disable Required for email?

Thanks,

    public abstract class IdentityUserCreateOrUpdateDtoBase : ExtensibleObject
    {
        [Required]
        [EmailAddress]
        [DynamicStringLength(typeof(IdentityUserConsts), nameof(IdentityUserConsts.MaxEmailLength))]
        public string Email { get; set; }

**Comment by maliming** [comment]
You can create your own services and DTOs to create/register/new users without email.

These modules are open-source.
