### ISSUE TITLE
Entity Class inject fail

### ISSUE THREAD

**Issue by sofm13** [abpframework/abp#8896]
Entity Class inject autofac fail,when Entities are derived from the Entity<TKey>,this Entities  Repository haven't inject 

ABP Framework version is 4.3

**Comment by maliming** [comment]
Can you explain it in detail?

* Steps needed to **reproduce** the problem.

**Comment by sofm13** [comment]
i have three Entity,Product and Category derived the FullAuditedAggregateRoot<Guid>,like this
![image](https://user-images.githubusercontent.com/52565295/117108916-7267f200-adb6-11eb-867a-b8e148f11a45.png)
![image](https://user-images.githubusercontent.com/52565295/117108942-7d228700-adb6-11eb-9894-e8d970f880ac.png)

but ProductCategory derived the Entity<Guid>
![image](https://user-images.githubusercontent.com/52565295/117109036-9e837300-adb6-11eb-9b86-a59c1ea11324.png)

then ProductCategoryRepository  has inject fail,
![image](https://user-images.githubusercontent.com/52565295/117109171-d5598900-adb6-11eb-8cd7-ca546d1ca741.png)

but if ProductCategory  derived the FullAuditedAggregateRoot<Guid>,inject  is success

**Comment by maliming** [comment]
You need set **includeAllEntities**.
```cs
services.AddAbpDbContext<MyDbContext>(options =>
{
    options.AddDefaultRepositories(includeAllEntities: true);
});
```


https://docs.abp.io/en/abp/latest/Entity-Framework-Core#add-default-repositories
