### ISSUE TITLE
4.3.0 iasyncbackgroundjob-can-not-be-invoked

### ISSUE THREAD

**Issue by vicenteyu** [abpframework/abp#8901]
`
public class TestJobArgs
    {
        public string ArgA { get; set; }
        public string ArgB { get; set; }
    }

    public class TestJob : AsyncBackgroundJob<TestJobArgs>, ITransientDependency
    {
        private readonly ISettingProvider _setting;
        public TestJob(ISettingProvider setting)
        {
            _setting = setting;
        }
        public override async Task ExecuteAsync(TestJobArgs args)
        {
            JsonConvert.DeserializeXmlNode(JsonConvert.SerializeObject(args), "doc")
                .Save(System.IO.Path.Combine(await _setting.GetOrNullAsync("TestJob.Path"), $"{DateTime.Now:yyyyMMddHHmmssfffff}.xml"));
        }
    }
`

` await _backgroundJobManager.EnqueueAsync(new TestJobArgs { ArgA = "", ArgB = "" });`

Error Message:

Volo.Abp.AbpException: Undefined background job for the job args type: TestJobArgs

**Comment by maliming** [comment]
Can you share the full steps needed to **reproduce** the problem?

**Comment by vicenteyu** [comment]
Sorry, My fault. The code runs well.

**Comment by vicenteyu** [comment]
The problem reproduce when i moved class file to a new project. 

Step 1: 
Create a solution "BookStore"

Step 2:
Add a new project "NewClass"

Step 3:
Add a new file "TestJobArgs.cs" to  "NewClass", Paste the code:
```csharp 
   public class TestJobArgs
    {
        public string ArgsA { get; set; }

    }

    public class TestJob : AsyncBackgroundJob<TestJobArgs>, ITransientDependency
    {
        public override async Task ExecuteAsync(TestJobArgs args)
        {
            await Task.Run(() =>
            {
                JsonConvert.DeserializeXmlNode(JsonConvert.SerializeObject(args), "doc")
                    .Save(System.IO.Path.Combine(@"D:\", $"{DateTime.Now:yyyyMMddHHmmssfffff}.xml"));
            });
        }
    }
```
Add  a dependency project "BookStore.Domain"

Step 4:
"BookStore.Web/Pages/Index.cshtml.cs" replace "IndexModel" :
```csharp
     public class IndexModel : BookStorePageModel
    {
        private readonly IBackgroundJobManager _backgroundJobManager;
        public IndexModel(IBackgroundJobManager backgroundJobManager)
        {
            _backgroundJobManager = backgroundJobManager;
        }
        public async Task OnGet()
        {
            await _backgroundJobManager.EnqueueAsync(new TestJobArgs { ArgsA = "a Arga" });
        }
    }
```

Build and run. 

Error Message:
Volo.Abp.AbpException: Undefined background job for the job name: BookStore.NewClass.TestJobArgs

**Comment by realLiangshiwei** [comment]
You need make `NewClass` project to be abp module
