### ISSUE TITLE
Blazor Solution corrupt after adding theme source

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#8902]
ABP Framework version 4.3.0
User Interface** type (Angular/MVC/React... etc.) : Blazor WebAssembly
* Steps needed to **reproduce** the problem.

1. Create new Blazor WebAssembly solution
2. Navigate to Blazor project folder
3. Run the following:

- abp add-package Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme --with-source-code --add-to-solution-file
- abp add-package Volo.Abp.AspNetCore.Components.Web.BasicTheme --with-source-code --add-to-solution-file

If I try and open the solution I get the following message:

![image](https://user-images.githubusercontent.com/1365851/117208772-6a777480-aded-11eb-9cca-2d7c1cc75372.png)

If I then open the solution file I can see that the Project references have been added at the beginning of the file instead of with the other projects.

![image](https://user-images.githubusercontent.com/1365851/117209097-cfcb6580-aded-11eb-992c-8ef2ccb22c24.png)

If I then move the references the project opens ok 

![image](https://user-images.githubusercontent.com/1365851/117209457-436d7280-adee-11eb-9981-31bd8b589056.png)

**Comment by yekalkan** [comment]
Hi,

> * Steps needed to **reproduce** the problem.
> 
> 1. Create new Blazor WebAssembly solution
> 2. Navigate to Blazor project folder
> 3. Run the following:
> 
> * abp add-package Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme --with-source-code --add-to-solution-file
> * abp add-package Volo.Abp.AspNetCore.Components.Web.BasicTheme --with-source-code --add-to-solution-file

I exactly followed these steps but couldn't reproduce the issue. Projects are added correctly.

Also, i checked the cli code that handles this operation, and i see that it shouldn't fail unless the solution is empty.

https://github.com/abpframework/abp/blob/baa6acc9a2ad59488a2e85ae7634659dea5dc1db/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectModification/SolutionFileModifier.cs#L51

**Comment by KevinFarrow** [comment]
@yekalkan Thanks for your help. I'll close this as I have fixed the problem in my project.
