### ISSUE TITLE
Blazor Server _ViewImports Warning

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#8903]
ABP Framework version: 4.3.0
User Interface** type (Angular/MVC/React... etc.) Blazor Server

When compiling a Blazor Server solution the following warning appears:

_**15>C:\Projects\TESTING\src\TESTING.Blazor\obj\Debug\net5.0\Razor\Pages\_ViewImports.cshtml.g.cs(4,100,4,118): warning CS0436: The type 'Pages__ViewImports' in 'C:\Projects\TESTING\src\TESTING.Blazor\obj\Debug\net5.0\Razor\Pages\_ViewImports.cshtml.g.cs' conflicts with the imported type 'Pages__ViewImports' in 'Volo.Abp.Account.Web.IdentityServer.Views, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Projects\TESTING\src\TESTING.Blazor\obj\Debug\net5.0\Razor\Pages\_ViewImports.cshtml.g.cs'**_

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/8838

Try to add `common.props` to blazor project

**Comment by KevinFarrow** [comment]
@realLiangshiwei Thanks for your help. That removed the warning.
