### ISSUE TITLE
add internal distinguishing lines in dropdown menu rowAction of datatables

### ISSUE THREAD

**Issue by nguyenquanghuyit** [abpframework/abp#8913]
![image](https://user-images.githubusercontent.com/52340160/117390388-45335500-af18-11eb-967f-364601ebea8c.png)

**Comment by nguyenquanghuyit** [comment]
How to add a line between two items in dropdown menu of rowAction datatables

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Guide

**Comment by nguyenquanghuyit** [comment]
> See https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Guide

Sorry, I've seen it, but only support add more text option. Not support html tag in RowAction. Can you help me, thanks!
Example: columnDefs: [
                {
                    title: "Action",
                    rowAction: {
                        items:
                            [
                                {
                                    text: "Details",
                                    visible: true
                                },
                                {
                                   // add line here: I mean user <hr> tag
                                },
                                {
                                    text: "Remove",
                                    visible: true                                   
                                }
                            ]
                    }
                },

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Entity-Action-Extensions#add-the-file-to-the-user-management-page

You can use js to add dom element.
