### ISSUE TITLE
Update to the feature documentation is needed

### ISSUE THREAD

**Issue by send2vinnie** [abpframework/abp#8915]
It's obvious that the documentation for the feature system was written based on the permission system documentation so there got some permission related terminologies remaining unedited over the following documentation:

https://docs.abp.io/en/abp/latest/Features

**Comment by realLiangshiwei** [comment]
I can't get your point., can you explain in detail?

**Comment by send2vinnie** [comment]
By searching the keyword "permission" throughout the document and the problematic paragraphs come up.

> ### FeatureDefinitionProvider
> Create a class inheriting the FeatureDefinitionProvider to define _permissions_.
> Example: Defining  #_permissions_

> A class deriving from the FeatureDefinitionProvider (just like the example above) can also get the existing _permission_ definitions (defined by the depended modules) and change their definitions.

All the "permission" appear above should be corrected to "feature".

**Comment by realLiangshiwei** [comment]
Got it, I will update it, thanks a lot
