### ISSUE TITLE
Upgrading to Bootstrap 5.0

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8922]
[Bootstrap 5 has officially released](https://blog.getbootstrap.com/2021/05/05/bootstrap-5/).

I want to inform the community about upgrading ABP to BS 5.0.

We are planning to upgrade ABP Framework to BS 5.0 with ABP 5.0 since it is a major breaking change. ABP 5.0 is planned for end of this year, based on .NET 6.0.

We think ABP's UI library dependencies will be compatible to BS 5.0 until that time, so we are expecting an easier migration. BS 5.0 is pretty new, we were already following alphas and betas. From now we will investigate it deeper and prepare a migration plan.

BTW, with this change, we will try to remove JQuery dependency from the MVC UI

**Comment by stsrki** [comment]
Also planned to start soon https://github.com/stsrki/Blazorise/issues/1103#issuecomment-833352184

**Comment by bnymncoskuner** [comment]
Bs5 branch is merged into the dev branch by #9877
