### ISSUE TITLE
Cannot make abp-modal draggable

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#8924]
4.3.0 / Angular

I can make an ordinary `NgbModal` draggable using the following markup:

```
<ng-template #companyLicencesContent let-modal let-c="close" let-d="dismiss">
  <div cdkDrag class="draggable" cdkDragRootElement=".modal-content">
    <abp-loading [hidden]="!licencesLoading"></abp-loading>
    <div class="modal-header">...</div>
    <div class="modal-body">...</div>
  </div>
</ng-template>
```

However, when I try to figure out how to drag `<abp-modal/>` - I have no idea. Please advise.

**Comment by bnymncoskuner** [comment]
Hello,

You can simply inject `cdkDrag` anywhere in `abp-modal` and set `cdkDragRootElement` as you have done. I suggest you do it between `<ng-template #abpBody> </ng-template>`

E.g.

```html
<abp-modal [(visible)]="modalVisible">
  <ng-template #abpHeader>
    <h5 class="modal-title">
      ...
    </h5>
  </ng-template>
  <ng-template #abpBody>
     <div cdkDrag cdkDragRootElement=".modal-content">
         ...
     </div>
  </ng-template>
  <ng-template #abpFooter>
    ...
  </ng-template>
</abp-modal>

```

**Comment by alexandis** [comment]
Perfect. So easy... Thank you!

**Comment by alexandis** [comment]
I am trying to use `cdkDragHandle` to use header for dragging and prevent text selection dragging in the modal body. But it does not work - i still can drag whole modal dialog by using mouse anywhere. Any idea why?
What is interesting - test example here is working: https://material.angular.io/cdk/drag-drop/overview

```
<abp-modal
  size="xl"
  [busy]="modalBusy"
>
  <ng-template #abpHeader>
    <div cdkDragHandle>
      <h3>Header</h3>
    </div>
  </ng-template>
  <ng-template #abpBody>
    <div cdkDrag cdkDragRootElement=".modal-content">Body Body Body</div>
  </ng-template>
</abp-modal>
```

**Comment by alexandis** [comment]
UPDATE: I've moved `<div cdkDrag cdkDragRootElement=".modal-content">` and element with `cdkDragHandle` into `abpHeader` area. Seems like this did the trick, but I am not closing the issue so far... :) Let's see if no more suprises to come :)

**Comment by alexandis** [comment]
Well, I've found another issues with that. We have custom **Department** page, which is built on top of **ABP** _OrgUnits_. Also it calls services to raise some **ABP** _popups_ - like **Roles**, **Members**. And I cannot make them draggable, since I do not have access to the markup.. What do I do here?

![image](https://user-images.githubusercontent.com/6149843/119879196-a35dc180-bf33-11eb-9777-81692ffd9010.png)
