### ISSUE TITLE
Many to Many question: Modify the name of the intermediate table

### ISSUE THREAD

**Issue by sgalcheung** [abpframework/abp#8927]
The generated intermediate table does not add the module name, can ef allow pre-processing one by one

**Comment by hikalkan** [comment]
I think this is unrelated to the ABP Framework. You configure your model using EF Core. Maybe I didn't understand the question well.

**Comment by sgalcheung** [comment]
When ef core deals with the many-to-many relationship, the intermediate table is automatically generated. The [official website](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many) introduces
Yes, he may not be related to abp, but is there a chance to deal with it in EntityTypeConfiguration

**Comment by realLiangshiwei** [comment]
See https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#join-entity-type-configuration
