### ISSUE TITLE
The Blazorise modal backdrop doesn't work well in ABP v4.3.0

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#8928]
![image](https://user-images.githubusercontent.com/30018771/117536630-aa796a00-b02e-11eb-90f8-4d5cc4063895.png)
As you can see, after upgrading to ABP v4.3.0, some elements are not covered by the modal backdrop.

Maybe it is related to https://github.com/abpframework/abp/issues/7997#issuecomment-793534862?

**Comment by tntwist** [comment]
Hi, 
the modal backdrop element was removed in blazorized 0.9.3: See here : https://blazorise.com/docs/components/modal/

**Comment by maliming** [comment]
hi @stsrki Can you check this?

**Comment by stsrki** [comment]
This is in fact the expected behavior. Nested modals are not supported by the bootstrap, see here https://getbootstrap.com/docs/4.6/components/modal/

> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

In the previous version of Blazorise, the modal backdrop was placed **inside** of the modal element and while it was working for the most part, it was messing with the page overflow and it was affecting some other z-order rules. There was no way around it, except for following the Bootstrap rules, and placing the backdrop **after** the modal element.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/117775009-a76bbd00-b26c-11eb-8c64-69c101d705ec.png)
![image](https://user-images.githubusercontent.com/30018771/117774947-915dfc80-b26c-11eb-91cb-e604a37d6f83.png)

Hi @stsrki, are these elements actually modals?

**Comment by stsrki** [comment]
No, the elements you marked are regular tabs.

Based on your first message screenshot it looked to me like it was a modal dialog and on top of it a popup of an error(also modal dialog). Now when you sent me a new screenshot, I might have being wrong.

---

The reason why modal backdrop doesn't work is that some element `z-order` is larger that of `.modal-backdrop`. Can you inspect in dev tools?

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/117793056-71cfcf80-b27e-11eb-898a-7ef64db87283.png)
![image](https://user-images.githubusercontent.com/30018771/117793285-a8a5e580-b27e-11eb-9f44-ba7c61af5840.png)

My project was changed to using Blazor-Server template, it can not be reproduced now.

It seems that this problem only occurs in Blazor WASM template, If I have time, I will try to reproduce it again, thanks @stsrki.
