### ISSUE TITLE
Docs module nav menu text size improvements

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8930]
We use smaller font-sizes in sub menus that makes it hard to read after 3. level:

![image](https://user-images.githubusercontent.com/1210527/117551795-a8280780-b050-11eb-871e-cfa2a81c0209.png)

I suggest two improvements;

- [x] Use larger fonts for sub menus. _Entities & Aggregate Roots_ can be same as _Domain Layer_ in this screen shot, for example.
- [x] Use larger width for the navigation area, like Microsoft's documentation I am adding a screenshot below:

![image](https://user-images.githubusercontent.com/1210527/117551886-0c4acb80-b051-11eb-91b0-5e4a4c12b8f0.png)

**Comment by yekalkan** [comment]
@armgnunlu ask me if you need help
