### ISSUE TITLE
Blazorise DataGrid Localizer

### ISSUE THREAD

**Issue by mehmetuken** [abpframework/abp#8931]
How localize in abp Blazorise components?

**Comment by maliming** [comment]
You can check the localization of Blazor.

https://docs.abp.io/en/abp/latest/UI/Blazor/Localization

**Comment by mehmetuken** [comment]
Blazorise datagrid not affect localization.

**Comment by ilkayilknur** [comment]
Can you please share the reproduction steps, sample code with us?

**Comment by mehmetuken** [comment]
I just want blazorise datagrid component add turkish translations globaly from direct my domanin shared module resource.

**Comment by mehmetuken** [comment]
I add “Next” key my tr json file but not affect.

**Comment by ilkayilknur** [comment]
I think you need to use the `Localizer` attribute on the DataGrid control.  See https://blazorise.com/docs/extensions/datagrid/ 

Do you have any suggestions @stsrki?

**Comment by stsrki** [comment]
Using `Localizers` parameter on a DataGrid is one way to do it. But it is on a per-grid basis so it is maybe not the most convenient.

The other is to make use of Blazorise localization https://blazorise.com/docs/helpers/localization/ and add Turkish localization.

**Comment by mehmetuken** [comment]
Thanks.
