### ISSUE TITLE
abp-select TagHelper.AspFor always null

### ISSUE THREAD

**Issue by qzwzqty** [abpframework/abp#8938]
I use abp-select like this in razor page
````
<abp-select id="id" asp-items="@Model.List" name="id" label="xxx" />
````
![Snipaste_2021-05-10_11-13-28](https://user-images.githubusercontent.com/23160268/117601675-87130400-b181-11eb-9175-2052906ef983.jpg)

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/UI/AspNetCore/Tag-Helpers/Form-elements#abp-select

**Comment by qzwzqty** [comment]
@realLiangshiwei 
I mean I don't need to set asp-for, so it will report an error here

**Comment by realLiangshiwei** [comment]
`abp-select` is a form element, `asp-for` option is required, you can use `@Html.DropDownList()` instead of `abp-select`.

**Comment by qzwzqty** [comment]
@realLiangshiwei  ok, thx
