### ISSUE TITLE
Need More Info on this

### ISSUE THREAD

**Issue by pmobin** [abpframework/abp#8941]
@maliming  hi. I am a newbie at sqlite but not sql itself. I want to do what you suggested but don't know where the file is to insert or modify as you suggested. How do I do this config change?

Many thanks.

Try completely disable the database transactions for sqlite.

Configure<AbpUnitOfWorkDefaultOptions>(options =>
{
    options.TransactionBehavior = UnitOfWorkTransactionBehavior.Disabled;
});
```

_Originally posted by @maliming in https://github.com/abpframework/abp/issues/5661#issuecomment-706803921_

**Comment by ilkayilknur** [comment]
You can place them in the EF Core module or web module. 

```csharp
public override void ConfigureServices(ServiceConfigurationContext context)
{
    Configure<AbpUnitOfWorkDefaultOptions>(options =>
    {
        options.TransactionBehavior = UnitOfWorkTransactionBehavior.Disabled;
    });
}
```

**Comment by pmobin** [comment]
Thanks for the reply.

 

I am using sqlite locally. I don’t seem to find these files. Are they part of the compilation process of sqlite? I just have sqlite3 downloaded and it has an .exe a .def and a .db file. Also is sqlite notoriously slow? I am doing 20 row selects and it is taking a second or so.

**Comment by ilkayilknur** [comment]
Did you check this document? https://docs.abp.io/en/abp/latest/Entity-Framework-Core-SQLite
