### ISSUE TITLE
Cannot use table 'AbpUsers' for entity type 'IdentityUser' 

### ISSUE THREAD

**Issue by leunghoary** [abpframework/abp#8950]
Abp version：4.3.0
MVC
database provider：EF Core
Exception：InvalidOperationException: Cannot use table 'AbpUsers' for entity type 'IdentityUser' since it is being used for entity type 'AppUser' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'IdentityUser' on the primary key properties and pointing to the primary key on another entity typed mapped to 'AbpUsers'.

Steps：1、 
```cs
ObjectExtensionManager.Instance
                   .MapEfCoreProperty<IdentityUser, string>(
                       nameof(AppUser.Avatar),
                       (entityBuilder, propertyBuilder) =>
                       {
                           propertyBuilder.HasMaxLength(200);
                       });
```
2、 

```cs
context.Services.AddAbpDbContext<MyDbContext>(options =>
            {
                /* Remove "includeAllEntities: true" to create
                 * default repositories only for aggregate roots */
                options.AddDefaultRepositories(includeAllEntities: true);
                options.ReplaceDbContext<IIdentityDbContext>();
            });
```
3、  
```cs
[ConnectionStringName("Default")]
public class TestDbContext : AbpDbContext<TestDbContext>, IIdentityDbContext
{
    public DbSet<AppUser> AppUsers { get; set; }

    public DbSet<IdentityUser> Users { get; }

    public DbSet<IdentityRole> Roles { get; set; }

    public DbSet<IdentityClaimType> ClaimTypes { get; }

    public DbSet<OrganizationUnit> OrganizationUnits  {get; }

public DbSet<IdentitySecurityLog> SecurityLogs { get; }

    public DbSet<IdentityLinkUser> LinkUsers { get; }

    /* Add DbSet properties for your Aggregate Roots / Entities here.
     * Also map them inside TestDbContextModelCreatingExtensions.ConfigureTest
     */

    public TestDbContext(DbContextOptions<TestDbContext> options)
        : base(options)
    {

    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        /* Configure the shared tables (with included modules) here */

        builder.Entity<AppUser>(b =>
        {
            b.ToTable(AbpIdentityDbProperties.DbTablePrefix + "Users"); //Sharing the same table "AbpUsers" with the IdentityUser
            
            b.ConfigureByConvention();
            b.ConfigureAbpUser();

            /* Configure mappings for your additional properties
             * Also see the TestEfCoreEntityExtensionMappings class
             */

            b.Property(x => x.Avatar).IsRequired(false).HasMaxLength(200).HasColumnName(nameof(AppUser.Avatar));
        });

        /* Configure your own tables/entities inside the ConfigureTest method */


        builder.ConfigureIdentity();
        builder.ConfigureTest();
    }
}
```
 I want to  single DbContext on runtime.

**Comment by maliming** [comment]
Please provide the full steps from the template project.

**Comment by leunghoary** [comment]
1. Update DbContext.OnModelCreating to configure the mapping for your new property
                            2. Update EfCoreEntityExtensionMappings to extend the IdentityUser entity and add "Avatar" to the migration.
                            3.  implements  IIdentityDbContext  interfaces of DbContext                            
                            4. Use the Add-Migration to add a new database migration.
                            5. Run the .DbMigrator project (or use the Update-Database command) to apply
                            6. An exception occurred while logging in

**Comment by maliming** [comment]
Your steps are not clear.

**Comment by leunghoary** [comment]
I added an "Avatar" property in appuser according to the official steps. I didn't want to have multiple dbcontext in the project, so I replaced iidentitydbcontext and implemented iidentitydbcontext in my dbcontext
https://docs.abp.io/en/abp/latest/Customizing-Application-Modules-Extending-Entities

**Comment by imxiongstu** [comment]
hello,from china enginer,me too issue, i trying to add extension entity,but exception:

Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.

**Comment by leunghoary** [comment]
> hello,from china enginer,me too issue, i trying to add extension entity,but exception:
> 
> Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.

hello, I've solved this problem, and I need to add a mapping

>           builder.Entity<AppUser>(b =>
>             {
>                 b.ToTable("AbpUsers");
>                 b.ConfigureByConvention();
>                 b.ConfigureAbpUser();
>                 b.Property(x => x.UserType).HasColumnName(nameof(AppUser.UserType));
>                 b.HasOne<IdentityUser>().WithOne().HasForeignKey<AppUser>(x => x.Id);
>             });

**Comment by imxiongstu** [comment]
> > hello,from china enginer,me too issue, i trying to add extension entity,but exception:
> > Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.
> 
> hello, I've solved this problem, and I need to add a mapping
> 
> > ```
> >       builder.Entity<AppUser>(b =>
> >         {
> >             b.ToTable("AbpUsers");
> >             b.ConfigureByConvention();
> >             b.ConfigureAbpUser();
> >             b.Property(x => x.UserType).HasColumnName(nameof(AppUser.UserType));
> >             b.HasOne<IdentityUser>().WithOne().HasForeignKey<AppUser>(x => x.Id);
> >         });
> > ```

Hi,Thanks,The perfect solution，but why that do?but why need that do?

**Comment by leunghoary** [comment]
> > > hello,from china enginer,me too issue, i trying to add extension entity,but exception:
> > > Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.
> > 
> > 
> > hello, I've solved this problem, and I need to add a mapping
> > > ```
> > >       builder.Entity<AppUser>(b =>
> > >         {
> > >             b.ToTable("AbpUsers");
> > >             b.ConfigureByConvention();
> > >             b.ConfigureAbpUser();
> > >             b.Property(x => x.UserType).HasColumnName(nameof(AppUser.UserType));
> > >             b.HasOne<IdentityUser>().WithOne().HasForeignKey<AppUser>(x => x.Id);
> > >         });
> > > ```
> 
> Hi,Thanks,The perfect solution，but why that do?but why need that do?

I read the document below, but did not delve into it.
https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

**Comment by imxiongstu** [comment]
> > > > hello,from china enginer,me too issue, i trying to add extension entity,but exception:
> > > > Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.
> > > 
> > > 
> > > hello, I've solved this problem, and I need to add a mapping
> > > > ```
> > > >       builder.Entity<AppUser>(b =>
> > > >         {
> > > >             b.ToTable("AbpUsers");
> > > >             b.ConfigureByConvention();
> > > >             b.ConfigureAbpUser();
> > > >             b.Property(x => x.UserType).HasColumnName(nameof(AppUser.UserType));
> > > >             b.HasOne<IdentityUser>().WithOne().HasForeignKey<AppUser>(x => x.Id);
> > > >         });
> > > > ```
> > 
> > 
> > Hi,Thanks,The perfect solution，but why that do?but why need that do?
> 
> I read the document below, but did not delve into it. https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

Ok,Thanks,Have a good time.

**Comment by imxiongstu** [comment]
> > > > hello,from china enginer,me too issue, i trying to add extension entity,but exception:
> > > > Cannot use table 'AbpRoles' for entity type 'AppRole' since it is being used for entity type 'IdentityRole' and potentially other entity types, but there is no linking relationship. Add a foreign key to 'AppRole' on the primary key properties and pointing to the primary key on another entity type mapped to 'AbpRoles'.
> > > 
> > > 
> > > hello, I've solved this problem, and I need to add a mapping
> > > > ```
> > > >       builder.Entity<AppUser>(b =>
> > > >         {
> > > >             b.ToTable("AbpUsers");
> > > >             b.ConfigureByConvention();
> > > >             b.ConfigureAbpUser();
> > > >             b.Property(x => x.UserType).HasColumnName(nameof(AppUser.UserType));
> > > >             b.HasOne<IdentityUser>().WithOne().HasForeignKey<AppUser>(x => x.Id);
> > > >         });
> > > > ```
> > 
> > 
> > Hi,Thanks,The perfect solution，but why that do?but why need that do?
> 
> I read the document below, but did not delve into it. https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

Hello,excuse me,
     I want to expand this IdentityUser,How do you map back to local?

`    public class AppRoleService : ApplicationService
    {
        private readonly IRepository<AppRole, Guid> _appRoleRepository;

        public AppRoleService(IRepository<AppRole, Guid> appRoleRepository)
        {
            _appRoleRepository = appRoleRepository;
        }

        public async Task<object> TestTestAsync()
        {
            var data = await _appRoleRepository.ToListAsync();
            return data;
        }
    }`

I want fetch IdentityUser and AppUser common data
