### ISSUE TITLE
docs.abp.io search return emtpy page result 

### ISSUE THREAD

**Issue by fileman** [abpframework/abp#8962]
docs.abp.io search return emtpy page result 
![image](https://user-images.githubusercontent.com/17230763/117666041-bc304e00-b1a3-11eb-9b86-7bbe87617a28.png)

**Comment by ilkayilknur** [comment]
Thanks for letting us know, @fileman. The team is working on that. I'll let you know when we fix the problem.

**Comment by fileman** [comment]
yesterday search was ok, if can help to solve

**Comment by ilkayilknur** [comment]
Hi @fileman, the problem has been resolved. Search is working right now. Thanks again for reaching out to us.

**Comment by ebicoglu** [comment]
this is because the Elastic Search service is unavailable, we are working on it.
