### ISSUE TITLE
Identity Server "/connect/introspect" not reachable

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#8971]
Hello,

i'm able to get token for à thirdpart app (angular) by querring : https://myIdp/connect/token (work fine)
and i need to also validate my token by using introspection on https://myIdp/connect/introspect  ....

the probleme is i can reache it, i'm getting 404, i 'also used Postman without success...

Any help please 

* ABP Framework version** : 4.3
* User Interface** type (Angular)
* Your database provider(EF Core)
* Tiered Architecture (separate IDP).
*

Best regards

**Comment by maliming** [comment]
Please check the IDS document: https://identityserver4.readthedocs.io/en/latest/endpoints/introspection.html
