### ISSUE TITLE
Howto use camelCase with MVC ?

### ISSUE THREAD

**Issue by barnybadzoo** [abpframework/abp#8973]
ABP: 4.3.0
UI: MVC / DevExtreme
Database: EF Core

I couldnt find any info in your documentation about the right approach.
I am using the App Template and DevExtreme for my UI and need to convert the response from GetListAsync()  to camelCase, because it returns all Fields in PascalCase. 

So i tried to adding this to ConfigureServices in the SampleApplicationModule.cs:

            Configure<AbpSystemTextJsonSerializerOptions>(options =>
            {
                options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            });
            PreConfigure<AbpJsonOptions>(options =>
            {
                options.UseHybridSerializer = false;
                
            });
            context.Services.PreConfigure<IMvcBuilder>(mvcBuilder => {
                mvcBuilder.AddNewtonsoftJson(
                 options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());
            });
            context.Services.PostConfigure<MvcNewtonsoftJsonOptions>(options => {
                options.SerializerSettings.ContractResolver = new DefaultContractResolver()
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                };
                options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
            });

I did also add  the tagging to the dto object fields with JsonProperty, but none of the above worked.
The service is implemented in Application Layer and i did add the configuration there instead of web application. . Is this the right place ? 
Or can this be done with the Automapper, somehow ?

**Comment by maliming** [comment]
Please refer to https://community.abp.io/articles/using-devextreme-components-with-the-abp-framework-zb8z7yqv

**Comment by barnybadzoo** [comment]
I did already follow this guide, some of the statements above are from there.. 
see here : If you change the Property in this DevExtreme Example likes that:
![image](https://user-images.githubusercontent.com/47523870/117780013-82148a00-b23f-11eb-909c-0d986a013a53.png)
 you wont see any change, because GetOrdersAsync only retrieves a prepared List<Order> without interacting with a appservice behind.. also its based on strings.. there is no real serialization/deserialization

I ended up using a devextreme datagrid with this for the columns:

```
.Columns(columns =>
{
..
 columns.Add().DataField(nameof(SampleItemDto.MyProperty).ToCamelCase());
..
}
```
This works and it didn't need to change the DefaultContractResolver..which didn't work with the code above like expected

**Comment by maliming** [comment]
hi

The `camelCase` is the default, Are you want to change it to `Pascalcase`?

**Comment by barnybadzoo** [comment]
Yes, sorry for the confusion.. I actually wanted to change to PascalCase because adding columns with 

`columns.AddFor( x=> x.Property)` was not possible due Datafields are camelCase
`columns.Add().DataField("property");` this is what i use  now ..

**Comment by maliming** [comment]
```cs
PostConfigure<Microsoft.AspNetCore.Mvc.JsonOptions>(options =>
{
    options.JsonSerializerOptions.PropertyNamingPolicy = null;
});
```

![image](https://user-images.githubusercontent.com/6908465/117951141-7495f780-b346-11eb-9a8f-3def58ea560b.png)
