### ISSUE TITLE
Article: How to Customize the Login Page

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#8977]
MVC: https://community.abp.io/articles/how-to-customize-the-login-page-for-mvc-razor-page-applications-9a40f3cd
Blazor: https://community.abp.io/articles/how-to-customize-the-login-page-of-an-abp-blazor-application-by4o9yms

Maybe add information if abp has tiered architecture (separated Identity Server), what are differences. What do you think?

**Comment by realLiangshiwei** [comment]
You just need to do the same thing in `.IdentityServer` project.

**Comment by sturlath** [comment]
FYI, better wording for @realLiangshiwei answer would be

> "You implement these same changes in the IdentityServer project instead"
