### ISSUE TITLE
Complete theme replacement

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#8978]
Based on this articles:
https://community.abp.io/articles/replace-basic-bootstrap-theme-with-custom-bootstrap-theme-in-abp-blazor-applications.-n3548bgl
https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b
https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-mvc-ui-yt9b18io

is somehow possible to make custom implementation (by copying this project and apply custom style) of Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic and then make own NuGet package?

The goal is to integrate DX layout and style design: https://js.devexpress.com/Documentation/Guide/Angular_Components/Application_Template/

I would like to keep existing implemented features in abp (user management,...), even that are based on Basic Theme.
The main goal is to replace topbar, menu and footer with DX components and style (like on this [live preview](https://devexpress.github.io/devextreme-angular-template/#/home)).
If language selection dropdown is curently based on Basic Theme is also fine.

I would like to achieve this only for MVC and Blazor UI (and not Angular).

Thank you for explanations.

**Comment by Znow** [comment]
@leonkosak The 2 first mentioned articles are outdated and does not work - I just tried them, with using alot of time on investigating things that aren't mentioned in the articles.

**Comment by Znow** [comment]
@hikalkan https://docs.abp.io/en/abp/latest/UI/Blazor/Theming -> https://docs.abp.io/en/abp/latest/UI/Blazor/Theming#the-easy-way "Basic Theme Source Code" gives 404...

**Comment by maliming** [comment]
Basic Theme Source Code: https://github.com/abpframework/abp/tree/dev/modules/basic-theme

https://github.com/abpframework/abp/pull/9352
