### ISSUE TITLE
Using Autofac directly

### ISSUE THREAD

**Issue by piotr07da** [abpframework/abp#8981]
Hi

I know from the documentation that Abp uses Autofac under the hood. Is there any way to use Autofac container directly?
I would like to use features of Autofac. Microsoft DI doesn't support nice registration by convention and generally has not much features.

I have some reusable modules and I do not want them to be dependent on Abp. I have some registration (by convention) code already written for Castle.Windsor but I can add version for Autofac - both are nice and have features I need, which are: registration by naming convention, automatic factory methods / delegate factories, interceptors to name a few.

How can I accomplish that, is it possible?

**Comment by maliming** [comment]
You can configure it in the **Startup** class.

https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html
```cs
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddApplication<MyProjectNameWebModule>();
    }

    public void Configure(IApplicationBuilder app)
    {
        var autofacContainer = app.ApplicationServices.GetAutofacRoot();

        app.InitializeApplication();
    }

    public void ConfigureContainer(ContainerBuilder builder)
    {

    }
}

```
