### ISSUE TITLE
ABP CLI: new command: install-libs

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#8984]
This is for **MVC / Razor Pages** and **Blazor Server** UI types. For other UI types, just write a warning and exit. It should work in the csproj file's folder.

`abp install-libs` command internally;

1. Uses `npm install` to install packages (warns if npm was not installed)*
2. Copies css/js/... resources to the libs folder. This is a replacement of [copy-resources.js](https://github.com/abpframework/abp/blob/dev/npm/packs/aspnetcore.mvc.ui/gulp/copy-resources.js). That means we no longer depend on gulp for that.

*discussion: should we prefer yarn if available, then fallback to npm install? what do you think @armanozak?

Note: Please also update the docs.

**Comment by armanozak** [comment]
If the user has yarn v1.20+ installed, yes we (still) should.
