### ISSUE TITLE
IsettingManager cannot save setting to DB

### ISSUE THREAD

**Issue by yel-best** [abpframework/abp#8990]
My project version environment :
*  ABP4.3
*  No UI
* Tiered IdentityServer
* Independent deployment IdentityServer

---

I also have an API
```

 private readonly ISettingManager _settingManager;

.....

public async Task SetGlobalSettingAsync(string settingName, string value)
        {
            await _settingManager.SetGlobalAsync(settingName, value);
        }

```

I thought I could use IsettingManager to save the Key Value to DB , But it didn't;

An error occurred after the request.

![image](https://user-images.githubusercontent.com/82205638/117924817-ec552980-b328-11eb-92db-b533363daa16.png)

It seems that the Set method checks to see if the Key exists and then modifies it, If you don't have this Key you will get an error

But I would like to configure some information and save it in the **AbpSettings** table of DB, such as saving some configuration files (whether to send Verification code, whether to open mail service, mail configuration information, etc.)

Hope to get help, thank you 😄

**Comment by maliming** [comment]
> A setting must be defined before its use. 

https://docs.abp.io/en/abp/latest/Settings

**Comment by yel-best** [comment]
@maliming Thank you for your answer.

OK, I can understand this, but I'm curious why Redis does not store my Settings in the AbpSettings table in DB.
![image](https://user-images.githubusercontent.com/82205638/117927032-35f34380-b32c-11eb-9c7d-dd13f2880175.png)

**In my CMSSettingDefinitionProvider defines some Settings, run after the findings don't enter the DB, but only exist in the redis, I want to know the configuration is not save in the DB AbpSettings table?**

Can you tell me what the AbpSettings table does.

![image](https://user-images.githubusercontent.com/82205638/117927159-663ae200-b32c-11eb-9288-e92e58a3c742.png)

I don't know if this problem has a demo ?

Hope to get help😃
