### ISSUE TITLE
KafkaDistributedEventBus - Subscribe Multiple Topics

### ISSUE THREAD

**Issue by RLindsa** [abpframework/abp#8994]
Please, can you explain how a single application can subscribe to multiple topics when using KafkaDistributedEventBus.

When looking at the code and the provided example, I've got the impression as if it is possible to subscribe to only one single topic within an application. 

Thanks in advance.

**Comment by realLiangshiwei** [comment]
Hi,

Yes, It can only subscribe to one topic. this is the current design.

**Comment by RLindsa** [comment]
Thx for the prompt feedback.

**Comment by pradipbaria** [comment]
@realLiangshiwei 
Can you explain the reason for choose approach to subscribe to only one topic?
