### ISSUE TITLE
Use LazyThreadSafetyMode.PublicationOnly to avoid caching exception when creating rabbitmq connection

### ISSUE THREAD

**Issue by RayMMond** [abpframework/abp#8998]
### Problem

https://github.com/abpframework/abp/blob/6b3297437be93df3989f6fda370ec87fac63e66a/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/ConnectionPool.cs#L28-L37

If connection factory failed and throw a exception (timeout...), `Lazy<IConnection>` will cache exception and rethrow it everytime when you access it's `Value` Property.

### Solution

According to this [link](https://theburningmonk.com/2013/04/be-lazy-but-be-ware-of-initialization-exception/):

> In PublicationOnly thread safety mode, multiple threads can invoke the initialization logic but the first thread to complete the initialization successfully sets the value of the Lazy<T> instance.

Maybe we should add `LazyThreadSafetyMode.PublicationOnly` to `Lazy<T>`'s ctor ?

```
 return Connections.GetOrAdd( 
     connectionName, () => new Lazy<IConnection>(() => 
     { 
         var connection = Options.Connections.GetOrDefault(connectionName); 
         var hostnames = connection.HostName.TrimEnd(';').Split(';'); 
         // Handle Rabbit MQ Cluster. 
         return hostnames.Length == 1 ? connection.CreateConnection() : connection.CreateConnection(hostnames); 
  
     }, LazyThreadSafetyMode.PublicationOnly) 
 ).Value; 
```

**Comment by RayMMond** [comment]
And this is another approach:
```
            connectionName ??= RabbitMqConnections.DefaultConnectionName;

            var lazyConnection = Connections.GetOrAdd(connectionName, () =>
                new Lazy<IConnection>(() =>
                {
                    var connection = Options.Connections.GetOrDefault(connectionName);
                    var hostnames = connection.HostName.TrimEnd(';').Split(';');
                    // Handle Rabbit MQ Cluster.
                    return hostnames.Length == 1
                        ? connection.CreateConnection()
                        : connection.CreateConnection(hostnames);
                }));

            if (!lazyConnection.IsValueCreated)
            {
                Connections.TryRemove(connectionName, out _);
            }

            return lazyConnection.Value;
```

**Comment by realLiangshiwei** [comment]
We can't use  `LazyThreadSafetyMode.PublicationOnly`, because it allows all threads to execute `valueFactory`, It will open a lot of connections.

I will try find a better way.

**Comment by realLiangshiwei** [comment]
> And this is another approach:
> 
> ```
>             connectionName ??= RabbitMqConnections.DefaultConnectionName;
> 
>             var lazyConnection = Connections.GetOrAdd(connectionName, () =>
>                 new Lazy<IConnection>(() =>
>                 {
>                     var connection = Options.Connections.GetOrDefault(connectionName);
>                     var hostnames = connection.HostName.TrimEnd(';').Split(';');
>                     // Handle Rabbit MQ Cluster.
>                     return hostnames.Length == 1
>                         ? connection.CreateConnection()
>                         : connection.CreateConnection(hostnames);
>                 }));
> 
>             if (!lazyConnection.IsValueCreated)
>             {
>                 Connections.TryRemove(connectionName, out _);
>             }
> 
>             return lazyConnection.Value;
> ```

This way has a problem,  `Valuefactory` will be executed directly only when calling `lazyConnection.Value;`, `IsValueCreated` is always `false`.
`
