### ISSUE TITLE
How do I publish a custom event after the current UoW transaction is successfully completed?

### ISSUE THREAD

**Issue by dimitrov9** [abpframework/abp#9000]
There are predefined events like **EntityCreatedEventData** which are published after the transaction is successfully committed. I would like to publish a custom Event after the transaction is successfully committed. Is that possible with the current api?

**Comment by maliming** [comment]
Please refer to https://docs.abp.io/en/abp/latest/Unit-Of-Work#other-iunitofwork-properties-methods

**Comment by dimitrov9** [comment]
Thank you @maliming
