### ISSUE TITLE
ReferenceLoopHandling

### ISSUE THREAD

**Issue by ArneCools** [abpframework/abp#9001]
How do I configure the ReferenceLoopHandling in abp.
I tried 
`[JsonProperty(ReferenceLoopHandling = ReferenceLoopHandling.Ignore)]`
and
```
context.Services.PreConfigure<IMvcBuilder>(mvcBuilder => {
                mvcBuilder.AddNewtonsoftJson(
                    options => options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);
            });
```
in PreConfigureServices

None of which work, I still get the error:
`Newtonsoft.Json.JsonSerializationException: Self referencing loop detected`

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
