### ISSUE TITLE
Upgrading to .NET 6.0

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#9004]
I opened this issue to track this work and discuss about it if neded.

**Comment by maliming** [comment]
Related links:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/plan

https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-2/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-2/
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-3/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-5/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-5/
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-6/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-6/
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-7/
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-7/

https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-1/
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-2/
https://github.com/dotnet/efcore/releases/tag/v6.0.0-preview.3.21201.2
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-4/
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-5/
https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-6-0-preview-6/

Problems:
https://github.com/dotnet/runtime/pull/51739

**Comment by maliming** [comment]
Current problems to be solved:
https://github.com/dotnet/runtime/issues/51685
