### ISSUE TITLE
How to replace AbpClaimsPrincipalFactory 

### ISSUE THREAD

**Issue by Nokecy** [abpframework/abp#901]

**Comment by maliming** [comment]
Have you tried using `services.AddClaimsPrincipalFactory<YourUserClaimsPrincipalFactory>()` in `ConfigureServices`?

**Comment by Nokecy** [comment]
context.Services.Replace(ServiceDescriptor.Transient<IUserClaimsPrincipalFactory<IdentityUser>, CustomerUserClaimsPrincipalFactory>());
