### ISSUE TITLE
Missing Italian in startup template

### ISSUE THREAD

**Issue by fileman** [abpframework/abp#9019]
Hi,
although it exists in source repository, the italian language is missing in startup template.

I have tried to add "options.Languages.Add(new LanguageInfo("it", "it", "Italiano"));" but doesn't solve the issue.

Also there are some translation errors, have you used an automatic translator?
I can take a look and submit a PR.
thanks

**Comment by realLiangshiwei** [comment]
Hi,

We always welcome contribution

**Comment by berkansasmaz** [comment]
Hi, 

Thanks for your contribution request.
We already did(#8999) an Italiano translation with an online translation system for the next version.
I can share this translation with you.
Just revise all the texts and if any incorrect translation fix it and send it info@abp.io or upload to Google Drive etc. and share the link.

[Italiano.zip](https://github.com/abpframework/abp/files/6476068/Italiano.zip)

**Comment by fileman** [comment]
email sent, you can reply to that if you need something.

**Comment by ebicoglu** [comment]
hi @fileman we got your email. thanks. we'll merge it.

**Comment by fileman** [comment]
for the future, I have to revise all texts or you can send me only new localized string ?

**Comment by berkansasmaz** [comment]
Since we have written our infrastructure according to this situation, we can only send new localized strings in the future.

Before each final version, we will add the missing localizations, we will update them with our automatic translation tool, and then we can send them to you for checking and correcting mistakes?

**Comment by fileman** [comment]
yes, I'm available, especially if I don't have to reread all the thousands of lines :-) 
but give me a few days

**Comment by berkansasmaz** [comment]
Ok, thanks, I'll contact you before the final versions :)
