### ISSUE TITLE
DBUpdateException are not logged in AuditLog

### ISSUE THREAD

**Issue by willignicolas** [abpframework/abp#9025]
abp 4.3
MVC
EF Core

I noticed that all the DBUpdateException errors (unique index, constraint...) sent by Entity Framework to the front are not traced in the auditlogs.
They are however traced in the log file (logs.txt)

Thank you for your reply.

Nicolas.

**Comment by maliming** [comment]
Can you try to remove `app.UseUnitOfWork()` from the ASP.NET Core pipeline?

**Comment by willignicolas** [comment]
Yes now it works after commented app.UseUnitOfWork().

Is there a long term solution? We need the use of UnitOfWork, is this modification disable UnitOfWork?

Thank you for your reply.

**Comment by maliming** [comment]
Please follow https://github.com/abpframework/abp/issues/8740
