### ISSUE TITLE
Navigation Menu (MVC) - customData

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#9026]
https://docs.abp.io/en/abp/latest/UI/AspNetCore/Navigation-Menu

![image](https://user-images.githubusercontent.com/39346964/118246944-e6835380-b4a2-11eb-8605-f46f5b7c93dc.png)

Is there any examples how to use customData attribute?

**Comment by maliming** [comment]
hi 

When you set `customData` of a menu item you also should change the component that render the menus.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Components/Menu/MainNavbarMenuViewComponent.cs
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Components/Menu/Default.cshtml
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic/Themes/Basic/Components/Menu/_MenuItem.cshtml#L2

**Comment by leonkosak** [comment]
Is somehow with customData similar menu layout?
![image](https://user-images.githubusercontent.com/39346964/118249233-79bd8880-b4a5-11eb-856e-6330663558b1.png)

**Comment by maliming** [comment]
Your menu is also a standard tree structure, you can set their `customData `for `ORGANIZATION`, `FINACCE `and `COMMUNICATION`, then use special HTML when rendering these items.
