### ISSUE TITLE
How to config and use multi partitions in a kafka topic

### ISSUE THREAD

**Issue by buitanlan** [abpframework/abp#9027]
Hi Abp team, I want  to config and use multi partitions in a kafka topic for 2 different purposes. Can you give some code demo  please

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/issues/8994

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Distributed-Event-Bus-Kafka-Integration#the-options-classes

```csharp
Configure<AbpKafkaOptions>(options =>
{
    options.ConfigureTopic = specification =>
    {
        specification.ReplicationFactor = 3;
        specification.NumPartitions = 3;
    };
});
```

**Comment by buitanlan** [comment]
Hi @realLiangshiwei your code is about  a specific  partition in a topic, @maliming #8994 is about multiple kafka's topics but I want to use multiple partitions in a kafka topic
