### ISSUE TITLE
Issues running dbcontext queries in linqpad.

### ISSUE THREAD

**Issue by oakuraape** [abpframework/abp#9031]
Hi there,

I found an example as per below code snippet, which allows linqPad to connect to an ABP DbContext, but when you run a query in linqPad you get the following error.

![image](https://user-images.githubusercontent.com/10067303/118381639-f6d13500-b640-11eb-8a6f-0b14149dcacb.png)

It would seem there is configuration steps that are missing as datafilter object is not instantiated. 

#if DEBUG
        private string _connectionString;

        /// <summary>
        /// For LINQPad
        /// </summary>
        public MyAppDbContext(string connectionString) : base(new DbContextOptions<MyAppDbContext>())
        {
            _connectionString = connectionString;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (_connectionString == null)
            {
                base.OnConfiguring(optionsBuilder); // Normal operation
                return;
            }

            // We have a connection string
            var dbContextOptionsBuilder = new DbContextOptionsBuilder();
            optionsBuilder.UseSqlServer(_connectionString);
            
            base.OnConfiguring(optionsBuilder);
        }
#endif

Any tips would be appreciated.

Thanks,
Scott

**Comment by maliming** [comment]
hi

The DbContext needs to use dependency injection. include property inject.
