### ISSUE TITLE
How to upload bytes array to BlobContainer? 

### ISSUE THREAD

**Issue by idreeshaddad** [abpframework/abp#9040]
Hello guys,

It is obvious from the documentation how to setup the BLOB storing file system provider, for example here is the upload post action:

![image](https://user-images.githubusercontent.com/2285974/118407813-12f9c400-b68b-11eb-83f4-895308724e06.png)

However; what is not clear to me (and I looked for it on SOF with no avail), how to get the (bytes: number[]) from the UI to send it through the REST service:

![image](https://user-images.githubusercontent.com/2285974/118409864-2a3daf00-b695-11eb-8c87-f02ff5d93a6b.png)

**Comment by maliming** [comment]
You can use `IRemoteStreamContent `.

https://docs.abp.io/en/abp/4.3/Application-Services#working-with-streams

**Comment by idreeshaddad** [comment]
> You can use `IRemoteStreamContent `.
> 
> https://docs.abp.io/en/abp/4.3/Application-Services#working-with-streams

I'm using [Blob Storing](https://docs.abp.io/en/abp/latest/Blob-Storing), I want to send the file as an array of bytes.
How do I convert the file into (`byte[] bytes`)?

**Comment by yinchang0626** [comment]
@idreeshaddad  Hi
 this is my way to upload `IRemoteStreamContent` in angular:
In `cms-kit` module ,
We has a api to upload `Media` by `inputStream`
```csharp
 public virtual async Task<MediaDescriptorDto> CreateAsync(string entityType, CreateMediaInputWithStream inputStream)
 {
...
 }
namespace Volo.CmsKit.Admin.MediaDescriptors
{
    public class CreateMediaInputWithStream
    {
        [Required]
        [DynamicStringLength(typeof(MediaDescriptorConsts), nameof(MediaDescriptorConsts.MaxNameLength))]
        public string Name { get; set; }

        public IRemoteStreamContent File { get; set; }
    }
}
```
 i am using angular app ,  now(4.3.0) `proxy` code that  `abp cli` generated is not work fine,so I created new one myself:
```typescript
  createByEntityTypeAndInputStream = (
    entityType: string,
    file:NzUploadFile//==File
  ) => {
    var formdata = new FormData();
    formdata.append('inputStream.name', file.name);
    formdata.append('inputStream.file', file as any, file.name);

    return this.restService.request<
      any,
      Volo.CmsKit.Admin.MediaDescriptors.MediaDescriptorDto
    >(
      {
        method: 'POST',
        url: `/api/cms-kit-admin/media/${entityType}`,
        body: formdata,
      },
      { apiName: 'CmsKitAdmin' }
    );
  };
```
I hope it is helpful

**Comment by idreeshaddad** [comment]
Sorry, but no it was not.
My concern is not `IRemoteStreamContent`, it is the `BlobContainer ` please open this page https://docs.abp.io/en/abp/latest/Blob-Storing 
Does it work? Am I missing something? 
Something doesn't make sense, it's confusing, maybe you need to update the documentations? Need a better content writer? More hours taking instructions from the leads? 
I don't know what the matter is, but it sure is very confusing.

**Comment by clinically-au** [comment]
BlobContainer works fine.

Converting files to byte[] is not really something specific to ABP. 

I'm sure if you are more specific with your problem, you will get some help round here. Where exactly are you running into a problem? Uploading the file from the UI or receiving the file on the server side?

**Comment by yinchang0626** [comment]
Sorry , I am not a content writer,
But I think that below code of  `CmsKit`  is very clear to show how to do:
1.When browser `post` a `FormData` with a file `body`,`IRemoteStreamContent` will be handled  by `AbpRemoteStreamContentModelBinder` 
2.Get `Stream` by `IRemoteStreamContent`
3.Save binary data by `IBlobContainer<TMediaContainer>.SaveAsync("id",stream)` .

```csharp

 [RequiresGlobalFeature(typeof(MediaFeature))]
    public class MediaDescriptorAdminAppService : CmsKitAdminAppServiceBase, IMediaDescriptorAdminAppService
    {
        protected IBlobContainer<MediaContainer> MediaContainer { get; }
        protected IMediaDescriptorRepository MediaDescriptorRepository { get; }
        protected MediaDescriptorManager MediaDescriptorManager { get; }
        protected IMediaDescriptorDefinitionStore MediaDescriptorDefinitionStore { get; }

        public MediaDescriptorAdminAppService(
            IBlobContainer<MediaContainer> mediaContainer,
            IMediaDescriptorRepository mediaDescriptorRepository,
            MediaDescriptorManager mediaDescriptorManager, 
            IMediaDescriptorDefinitionStore mediaDescriptorDefinitionStore)
        {
            MediaContainer = mediaContainer;
            MediaDescriptorRepository = mediaDescriptorRepository;
            MediaDescriptorManager = mediaDescriptorManager;
            MediaDescriptorDefinitionStore = mediaDescriptorDefinitionStore;
        }

        public virtual async Task<MediaDescriptorDto> CreateAsync(string entityType, CreateMediaInputWithStream inputStream)
        {
            var definition = await MediaDescriptorDefinitionStore.GetAsync(entityType);

            /* TODO: Shouldn't CreatePolicies be a dictionary and we check for inputStream.EntityType? */
            await CheckAnyOfPoliciesAsync(definition.CreatePolicies);

            using (var stream = inputStream.File.GetStream())
            {
                var newEntity = await MediaDescriptorManager.CreateAsync(entityType, inputStream.Name, inputStream.File.ContentType, inputStream.File.ContentLength ?? 0);

                await MediaContainer.SaveAsync(newEntity.Id.ToString(), stream);
                await MediaDescriptorRepository.InsertAsync(newEntity);

                return ObjectMapper.Map<MediaDescriptor, MediaDescriptorDto>(newEntity);
            }
        }
}
```
