### ISSUE TITLE
Upgrade samples to 4.3.2

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#9045]

**Comment by GotzeWong** [comment]
In ABP, Pkce is disabled by default. If you need to enable Pkce, I could show the steps to open it.

**Comment by GotzeWong** [comment]
Below are steps to upgrades the Microservices Demo from 3.2.0 to 4.3.0.

1. Upgrades TargetFramework of **applications/AuthServer.Host**  to .net 5.0
![image](https://user-images.githubusercontent.com/7664030/118754142-00ed7080-b899-11eb-9425-ff004eac5114.png)


2. Upgrads all packages to lastest version
![image](https://user-images.githubusercontent.com/7664030/118754273-47db6600-b899-11eb-803e-d39f8863c9d0.png)

3. Rebuild **applications/AuthServer.Host** project and fix errors

![image](https://user-images.githubusercontent.com/7664030/118759233-36975700-b8a3-11eb-8f41-98a8fdbb59f2.png)

**Fix error 1**
![image](https://user-images.githubusercontent.com/7664030/118759214-3008df80-b8a3-11eb-8515-86f88cd7c554.png)

```
//using Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Components;
using Volo.Abp.Ui.Branding;
using Volo.Abp.DependencyInjection;

namespace AuthServer.Host
{
    public class BrandingProvider : DefaultBrandingProvider, ISingletonDependency
    {
        public override string AppName => "Authentication Server";
    }
}
```

**Fix error2**

![image](https://user-images.githubusercontent.com/7664030/118759493-bae9da00-b8a3-11eb-84c5-4a40700bcf2c.png)
`FindByCliendIdAsync `=>`FindByClientIdAsync `

4. Update Ids Database
`dotnet ef migrations add Upgraded_To_Abp_4_3_0`
![image](https://user-images.githubusercontent.com/7664030/118754565-ed8ed500-b899-11eb-8b4d-bfec97a90281.png)

If it return "No project was found. Change the current working directory or use the --project option."
You should locate the **applications/AuthServer.Host** project  with `cd .\applications\AuthServer.Host` first and try add migration again.


```
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AuthServer.Host.Migrations
{
    public partial class Upgraded_To_Abp_4_3_0 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_IdentityServerApiClaims_IdentityServerApiResources_ApiResourceId",
                table: "IdentityServerApiClaims");

            migrationBuilder.DropForeignKey(
                name: "FK_IdentityServerApiScopeClaims_IdentityServerApiScopes_ApiResourceId_Name",
                table: "IdentityServerApiScopeClaims");

            migrationBuilder.DropForeignKey(
                name: "FK_IdentityServerApiScopes_IdentityServerApiResources_ApiResourceId",
                table: "IdentityServerApiScopes");

            migrationBuilder.DropTable(
                name: "IdentityServerApiSecrets");
              ... ...
```

`dotnet ef database update`

```
PM> dotnet ef migrations add Upgraded_To_Abp_4_3_0
Build started...
Build succeeded.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
Done. To undo this action, use 'ef migrations remove'
PM> dotnet ef database update
Build started...
Build succeeded.
Applying migration '20210519051256_Upgraded_To_Abp_4_3_0'.
Done.
PM> 
```


By now, you already updated the database. Next need to change the client configuration to run the demo.

**Comment by GotzeWong** [comment]
If run directly, we will get _[500] invalid_scope_ in **applications/BackendAdminApp.Host**.

![image](https://user-images.githubusercontent.com/7664030/118760299-24b6b380-b8a5-11eb-8d21-1d860c8fab39.png)



**Step 1 Upgraded all projects' frameworks and packages.**

**Step 2 Fix 404 error**
After upgrading the version of Ocelot in **BackendAdminAppGateway.Host/InternalGateway.Host/PublicWebSiteGateway.Host**, we should rename all _ReRoute_ to _Route_ in `appsettings.json` according to [#1239](https://github.com/ThreeMammals/Ocelot/pull/1239#issue-422318909).



**Step 3 Clear [dbo].[IdentityServerApiScopes]**

Rebuild and run with the orders.

Now, you can enjoy ABP Microservices with Ids 4.

![image](https://user-images.githubusercontent.com/7664030/118917380-58581300-b963-11eb-9741-1c6a5b7566e9.png)
