### ISSUE TITLE
Please extend the CLI to allow non-essential options such as multi-tenancy and Identity Server to be excluded when creating a project

### ISSUE THREAD

**Issue by Uchiha-Peng** [abpframework/abp#9060]
The abp framework is excellent and convenient. Its functions are very comprehensive, but my project is relatively simple. I want to create a project that excludes multi-tenancy and Identity Server. What should I do? There are too many data tables generated, which are very different from my business. I want to define my own menu management and authority management. Please extend the CLI to allow some non-essential options to be excluded when creating a project, thank you.

**Comment by leonkosak** [comment]
https://github.com/abpframework/abp/issues/8023
