### ISSUE TITLE
CLI add-package: source code option is error

### ISSUE THREAD

**Issue by BeiMeng** [abpframework/abp#9061]
ABP Framework version 4.3.
ABP CLi version 4.3.
Consloe Poroject，issue  is
![1621321292(1)](https://user-images.githubusercontent.com/6823869/118606431-fcb64a00-b7e9-11eb-9cf9-43acf5973352.png)

**Comment by yekalkan** [comment]
As it says in logs, this package is not downloadable.

**Comment by BeiMeng** [comment]
@yekalkan Can you tell me the possible reason why I can't download it, thank you

**Comment by yekalkan** [comment]
For now, only UI theme packages are downloadable.

You can download this repository and extract any package you want.

**Comment by BeiMeng** [comment]
ok，I see，thank you again
