### ISSUE TITLE
 ProfileAppService don't return extraProperties

### ISSUE THREAD

**Issue by aelhadi** [abpframework/abp#9062]
Hello,

I extended AppUser with some properties. eveything works fine.

IdentityUserAppService  return User with the extraProperties. but ProfileAppService don't.

am i missing something in my ef core module extension class? if so how to achive this? or it' s normal and i have to override the ProfileAppService ?

Regards

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by aelhadi** [comment]
Step 01 : 

Add a property to the AppUser

Step 02 : 

Update the xxxEfCoreEntityExtensionMappings 

......
```
ObjectExtensionManager.Instance
                .MapEfCoreProperty<IdentityUser, string>(
                    nameof(AppUser.Title),
                    (entityBuilder, propertyBuilder) =>
                    {
                        propertyBuilder.HasDefaultValue("");
                        propertyBuilder.HasMaxLength(UserConsts.MaxTitleLength);
                    }
.....
```` 
Step 03 : 

Apply migration

Step 04 : 

update xxxxoduleExtensionConfigurator

```
identity.ConfigureUser(user =>
        {
            user.AddOrUpdateProperty<string>(
                UserConsts.TitlePropertyName,
                options =>
                {
                    options.Attributes.Add(new RequiredAttribute());
                    options.Attributes.Add(
                        new StringLengthAttribute(UserConsts.MaxTitleLength)
                    );
                }
            );
```


Start project, call /api/identity/users/by-email/{email} or (other) : 

it returns the new properties 

![image](https://user-images.githubusercontent.com/5918026/118777464-633e7500-b889-11eb-8ca1-28ff7c017a47.png)


Now Call  api/identity/my-profile  : 


![image](https://user-images.githubusercontent.com/5918026/118777694-a26cc600-b889-11eb-94c2-8a6d3d832f4e.png)


After investigating the source code of the two services, the IdentityAppService returns IdentityUserDto but ProfileAppService returns a ProfileDto and the extraProperties are not filled.

**Comment by realLiangshiwei** [comment]
try

```csharp
public class <YourProjectName>ApplicationContractsModule : AbpModule
{
    private static readonly OneTimeRunner OneTimeRunner = new OneTimeRunner();

    public override void PostConfigureServices(ServiceConfigurationContext context)
    {
        OneTimeRunner.Run(() =>
        {
            ModuleExtensionConfigurationHelper.ApplyEntityConfigurationToApi(
                IdentityModuleExtensionConsts.ModuleName,
                IdentityModuleExtensionConsts.EntityNames.Role,
                getApiTypes: new[] { typeof(IdentityRoleDto), typeof(ProfileDto) },
                createApiTypes: new[] { typeof(IdentityRoleCreateDto) },
                updateApiTypes: new[] { typeof(IdentityRoleUpdateDto) }
            );
        });
    }
}
```

**Comment by aelhadi** [comment]
Replacing IdentityRole... by IdentityUser  works fine 👍 

```
public override void PostConfigureServices(ServiceConfigurationContext context)
        {
            OneTimeRunner.Run(() =>
            {
                ModuleExtensionConfigurationHelper.ApplyEntityConfigurationToApi(
                    IdentityModuleExtensionConsts.ModuleName,
                    IdentityModuleExtensionConsts.EntityNames.User,
                    getApiTypes: new[] { typeof(IdentityUserDto), typeof(ProfileDto) },
                    createApiTypes: new[] { typeof(IdentityUserCreateDto) },
                    updateApiTypes: new[] { typeof(IdentityUserUpdateDto) }
                );
            });
        }
```

Should be added to documention.... ;-)

**Comment by hmphu** [comment]
> try
> 
> ```cs
> public class <YourProjectName>ApplicationContractsModule : AbpModule
> {
>     private static readonly OneTimeRunner OneTimeRunner = new OneTimeRunner();
> 
>     public override void PostConfigureServices(ServiceConfigurationContext context)
>     {
>         OneTimeRunner.Run(() =>
>         {
>             ModuleExtensionConfigurationHelper.ApplyEntityConfigurationToApi(
>                 IdentityModuleExtensionConsts.ModuleName,
>                 IdentityModuleExtensionConsts.EntityNames.Role,
>                 getApiTypes: new[] { typeof(IdentityRoleDto), typeof(ProfileDto) },
>                 createApiTypes: new[] { typeof(IdentityRoleCreateDto) },
>                 updateApiTypes: new[] { typeof(IdentityRoleUpdateDto) }
>             );
>         });
>     }
> }
> ```

You save my life, this works fine. It should be added to document
