### ISSUE TITLE
No roles in CurrentUser after upgrading the abp framework 3.0.4 to 4.3.0

### ISSUE THREAD

**Issue by akshaybheda** [abpframework/abp#9066]
I have followed the steps for migrating the framework https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0. 

After being done with the steps, I am not getting any roles in the CurrentUser?

Anything apart from the migration step that needs to be done?

**Comment by akshaybheda** [comment]
Also I am using IdentityServerAuthentication and Getting **Audience validation failed. Audiences: 'empty'.** Error

```
 context.Services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.RequireHttpsMetadata = false;
                    options.ApiName = configuration["AuthServer:ApiName"];
                });
```

**Comment by maliming** [comment]
You can create a new project that using the latest version. then compare the code.

**Comment by akshaybheda** [comment]
The configuration is similar, Can you explain how the roles are mapped to CurrentUser.Roles ? I can check that workflow then

**Comment by maliming** [comment]
It base on your current claims.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Security/Volo/Abp/Users/CurrentUser.cs#L34

**Comment by akshaybheda** [comment]
Can you provide some pointer as to why there are no claims for current user? What I can check ?

**Comment by maliming** [comment]
Please check your authenticate scheme and claims.

**Comment by akshaybheda** [comment]
after implementing that, and updating all packages from angular side. The application-configuration call returns all the expected values, but the same information is not sent from angular side back to c#. 

Only few properties of CurrentUser are set while all information is being sentfrom the application-configuration

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/9066#issuecomment-843662579

**Comment by akshaybheda** [comment]
@maliming , The bearer token has all the details about claims now but the CurrentUser is only setting few of those properties and rest of them are null

**Comment by akshaybheda** [comment]
Also @maliming , After upgrading we are getting Npgsql.PostgresException (0x80004005): 42P01: relation "xx" does not exist

After running update-database, No migrations were applied. The database is already up to date.

Any pointers?

**Comment by maliming** [comment]
No ideas.

**Comment by akshaybheda** [comment]
@maliming  the eAccountComponents is missing Account in latest package. How do I replace full account component, which we had earlier
