### ISSUE TITLE
How to hide parent menu item, if all childs are invisible due to absent permissions?

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#9067]
4.3.0 / Angular

```
  {
    path: 'audit-log',
    component: ApplicationLayoutComponent,
    loadChildren: () => import('@abxeps/abxeps-ct-audit-log').then(m => m.AbxEpsCtAuditLogRoutingModule),
    canActivate: [AuthGuard, PermissionGuard],
    data: {
      layout: eLayoutType.application,
      routes: {
        path: '',
        order: 11,
        iconClass: 'fa fa-cog',
        name: '::Menu:ErrorsCategory',
        children: [
          {
            path: 'audit-log/abx-common-errors',
            name: 'AuditLog::Menu:CommonErrors',
            requiredPolicy: 'AuditLog.CommonErrors'
          },
          {
            path: 'audit-log/abx-user-errors',
            name: 'AuditLog::Menu:UserErrors',
            requiredPolicy: 'AuditLog.UserErrors'
          },
          ...
          {
            path: 'audit-log/abx-superduper-errors',
            name: 'AuditLog::Menu:SuperDuperErrors',
            requiredPolicy: 'AuditLog.SuperDuperErrors'
          }
        ]
      },
    },
  },

```
I would like to have '::Menu:ErrorsCategory' invisible if ALL child items are invisible. If I have dozen of child items - how do I do that easily?

![image](https://user-images.githubusercontent.com/6149843/118683763-50d12680-b80a-11eb-8230-948c87252c21.png)

**Comment by mehmet-erim** [comment]
Hi @alexandis,

I've created a PR:
https://github.com/abpframework/abp/pull/9291

The problem will be fixed with the PR. But I suggest you define your routes in a `RouteProvider`. See an example:
https://github.com/abpframework/abp/blob/c5cc41cda3db6e1561afdbcd54c0f1b7a4019e54/npm/ng-packs/packages/identity/config/src/providers/route.provider.ts

Then, you should add this to `app.module.ts`'s providers like this:
https://github.com/abpframework/abp/blob/dev/templates/app/angular/src/app/app.module.ts#L36

Please note that your parent route's path should be undefined:

```
path: undefined, // change empty string as undefined
order: 11,
iconClass: 'fa fa-cog',
name: '::Menu:ErrorsCategory',
```

**Comment by alexandis** [comment]
I am now totally confused with this.
1) If I am defining route in `route.provider.ts` - what's the point of having route definition in `app-routing.module.ts`? Do i need to split the definitions and have part of it in one file and part - in another? If so, it's pretty confusing...
I've tried to relocate ALL route definitions from second file to the first, but I can see the route objects used there are different...
2) I have bunch of `XXX-routing.module.ts` files. It looks confusing also: if I describe all the routes within `app-routing.module.ts` like this:

```
  {
    data: { moduleId: 'CTComp' },
    path: 'companies',
    loadChildren: () => import('./companies/companies.module').then(m => m.CompaniesModule),
    canActivate: [AbxModuleGuard]
  },
```

what's the point of having those, where routing information is duplicated:

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { CompaniesComponent } from './companies/companies.component';

const routes: Routes = [
  {
    path: 'companies',
    component: CompaniesComponent,
    data: { requiredPolicy: 'CentralTools.Companies' },
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})

export class CompaniesRoutingModule { }
```

3) Actually I'm experiencing the issue with using `undefined`: it is treated as string "undefined". As result, I'm getting routes like this:
**https://localhost:4200/undefined** - for a folder, **https://localhost:4200/undefined/batch-histories** - for its child...
Probably it's because of `string` instead of `string | undefined` or something like that??

```
    path: '',
    component: ApplicationLayoutComponent,
    loadChildren: () => import('@abxeps/abxeps-ct-batch').then(m => m.AbxEpsCtBatchModule),
    canActivate: [AbxModuleGuard],
    data: {
      routes: {
        path: undefined,
        iconClass: 'fa fa-cog',
        name: 'Batch Management',
        children: [
          {
            path: 'batch-mng/batch',
            name: '::Menu:Batches'
          },
          {
            path: 'batch-mng/batch-history',
            name: '::Menu:BatchHistories'
          }
        ]
      }
    }
```

```
    interface Route extends Nav {
        path: string;
        layout?: eLayoutType;
        iconClass?: string;
    }
```

![image](https://user-images.githubusercontent.com/6149843/122220658-347fe280-ceb9-11eb-8e3d-d26d7d2d5d34.png)

We are using custom menu, but it's based on **ABP.Nav**, **ABP.Route**...

We need to have a working solution now, not after updating to the next **ABP Framework** version...

P.S. So far I've managed to resolve the issue. But it looks rather like a kludge: I check for '/undefined' path and treat is as `undefined`, making substring replacement, etc.

**Comment by mehmet-erim** [comment]
Hi @alexandis

Route definitions in `app-routing.module.ts` have deprecated. You only need to define all routes in the `route.provider.ts` file. For more information, see [modifying the menu document](https://docs.abp.io/en/abp/latest/UI/Angular/Modifying-the-Menu#how-to-add-a-navigation-element).

Your all issues will probably be resolved when you define routes with a provider. Please let me know if you will face any problem with using `route.provider`

**Comment by alexandis** [comment]
I have read the document. But I still cannot figure out, how to sort everything out.
If I define the routes solely in `route.provider.ts` like this:

```
function configureRoutes(routes: RoutesService) {
  return () => {
    routes.add([
      {
        path: '/',
        name: '::Menu:Home',
        iconClass: 'fas fa-home',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/dashboard',
        name: '::Menu:Dashboard',
        iconClass: 'fas fa-chart-line',
        order: 101,
        layout: eLayoutType.application,
        requiredPolicy: 'Fines.Dashboard.Host || AbpAccount.SettingManagement',
      },
      {
        path: '/account',
        name: eAccountRouteNames.Account,
        iconClass: 'fas fa-chart-line',
        order: 102,
        layout: eLayoutType.account
      },
      {
        path: '/identity',
        name: eIdentityRouteNames.IdentityManagement,
        parentName: eThemeSharedRouteNames.Administration,
        order: 103,
        layout: eLayoutType.application,
        iconClass: 'fa fa-id-card-o',
        requiredPolicy: eIdentityPolicyNames.IdentityManagement,
      },
      {
        name: eLanguageManagementRouteNames.LanguageManagement,
        path: '/language-management',
        layout: eLayoutType.application,
        parentName: eThemeSharedRouteNames.Administration,
        iconClass: 'fa fa-globe',
        order: 104,
        requiredPolicy: eLanguageManagementPolicyNames.LanguageManagement,
      },
      {
        path: '/saas',
        name: eSaasRouteNames.Saas,
        order: 105,
        layout: eLayoutType.application,
        iconClass: 'fa fa-users',
        requiredPolicy: eSaasPolicyNames.Saas,
      },
      {
        name: eAuditLoggingRouteNames.AuditLogging,
        path: '/audit-logs',
        parentName: eThemeSharedRouteNames.Administration,
        layout: eLayoutType.application,
        iconClass: 'fa fa-file-text',
        order: 106,
        requiredPolicy: eAuditLoggingPolicyNames.AuditLogging,
      },
      {
        name: eIdentityServerRouteNames.IdentityServer,
        path: '/identity-server',
        parentName: eThemeSharedRouteNames.Administration,
        layout: eLayoutType.application,
        iconClass: 'fa fa-id-card-o',
        order: 107,
        requiredPolicy: eIdentityServerPolicyNames.IdentityServer,
      },
      {
        name: eTextTemplateManagementRouteNames.TextTemplates,
        path: '/text-template-management/text-templates',
        parentName: eThemeSharedRouteNames.Administration,
        order: 108,
        layout: eLayoutType.application,
        requiredPolicy: eTextTemplateManagementPolicyNames.TextTemplates,
        iconClass: 'fas fa-envelope-open-text',
      },
      {
        name: eSettingManagementRouteNames.Settings,
        path: '/setting-management',
        parentName: eThemeSharedRouteNames.Administration,
        layout: eLayoutType.application,
        order: 109,
        iconClass: 'fa fa-cog',
      },
    ]);
  };
}
```

and leave `app-routing.module.ts` free of _route_ definition:

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

@NgModule({
  imports: [RouterModule.forRoot([], { relativeLinkResolution: 'legacy' })],
  exports: [RouterModule],
})
export class AppRoutingModule {}
```

the menu does not look right and in fact does not work:

![image](https://user-images.githubusercontent.com/6149843/124126446-59608200-da83-11eb-9ba6-c2c8f8a20aa6.png)

**Comment by alexandis** [comment]
Hi @mehmet-erim
I have defined my routes in the route provider. But now I have noticed another issue: `PermissionGuard` does not work properly.
For instance, I have this route fragment:
```
      {
        path: 'parameters/categories',
        name: '::Menu:ParametersCategories',
        requiredPolicy: 'CentralTools.Paraameters',
        parentName: '::Menu:Parameters',
        order: 1
      },
```
I have intentionally put wrong `requiredPolicy` name - "Paraameters". As expected, the corresponding menu item is hidden from the menu:

![image](https://user-images.githubusercontent.com/6149843/124169240-b160ae00-daae-11eb-967c-3ab7efa2ef32.png)

However, when I try to access it directly - it is shown, because the route is not determined correctly:

![image](https://user-images.githubusercontent.com/6149843/124169324-cb01f580-daae-11eb-8f7d-52a598739071.png)

![image](https://user-images.githubusercontent.com/6149843/124169037-6ba3e580-daae-11eb-8291-0f0dd4849039.png)

![image](https://user-images.githubusercontent.com/6149843/124169184-99892a00-daae-11eb-959c-d8be4fa11dcd.png)

Because of this issue I had to create a custom PermissionGuard where the route is manually checked. Which is not a good way...

**Comment by alexandis** [comment]
Looks like now it's ok, thank you. However, probably it worth saying that child route needs to start from '/', otherwise `findRoute` does not work properly...

**Comment by alexandis** [comment]
I have one more issue here: I have Permission checker which causes error 403, if user tries to access the specific page he has no access to. So when he tries to call such page via some link - he naturally receives page with error 403.

But the issue is in this case _function_ `configureRoutes` is not invoked and the button "Go to the homepage" does not work (click does not work):

![image](https://user-images.githubusercontent.com/6149843/124494595-b92a9600-ddbf-11eb-8056-436e633a3480.png)

If he tries to access the inaccessible page via browser URL - he gets the same error page, but in this case `configureRoutes` is invoked and the button works as expected.

**Comment by mehmet-erim** [comment]
The problem has been fixed.
Thanks!

**Comment by alexandis** [comment]
> The problem has been fixed.

Hi - what do you mean "has been fixed"? What about the situation with _function_ `configureRoutes` not invoked after getting error 403 and other errors from your `HttpErrorComponent` so "**Go to the homepage**" _button_ does not work? It happens when I try to navigate to inaccessible page via link on the site. Probably `configureRoutes` is not related to this issue. Please confirm this then and let me know if I need to create another issue?

**Comment by mehmet-erim** [comment]
You can download `v4.4.0-rc.2` template and test. If you encounter any problem, please report it by creating a new issue.
@alexandis
