### ISSUE TITLE
Create a sample project with Elsa Workflow (open-source)

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#9068]
WRITE A COMMUNITY ARTICLE

Elsa is a popular framework as a workflow library.
This sample will be helpful to developers who need to use workflow in their project.
See the repository -> https://github.com/elsa-workflows/elsa-core

Add the UI of the Elsa:
![image](https://raw.githubusercontent.com/elsa-workflows/elsa-core/master/doc/elsa-2-hello-world-http.gif)

**Comment by mrs01dev** [comment]
There  are three projects on GitHub:
https://github.com/AbpApp/volo.abp.elsa
https://github.com/realLiangshiwei/Lsw.Abp.WorkFlow.Management
https://github.com/zrkcode/Elsa-Workflow-Issue

**Comment by EngincanV** [comment]
**Article:** https://community.abp.io/articles/using-elsa-workflow-with-the-abp-framework-773siqi9

**Comment by khanhtranchi** [comment]
Hi @EngincanV,

Thanks for your guide. I download your sample project to deploy but when I edit the workflow and click publish it throw the exception "An error occurred: Request failed with status code 500".
Could you try and guide us how to fix this error ?

Thanks.

**Comment by maliming** [comment]
hi @khanhtranchi 

Please create a new issue.
