### ISSUE TITLE
foreign key in entity extension (lookup.url) 

### ISSUE THREAD

**Issue by mohamed-moaz-ibrahim** [abpframework/abp#9069]
### Documentation
I followed the [Documentation](https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#navigation-properties-foreign-keys) it was very helpful however, in the angular it shows the foreign key as an input instead of select component. when I inspect it I found an autocomplete set to off when I change it to on it partially worked.

![error](https://user-images.githubusercontent.com/81626296/118700552-79ade780-b81b-11eb-8daf-716554c7d5db.PNG)

any help please

**Comment by armanozak** [comment]
Hi @mmoazibrahim,

Sorry, but the question is not clear.

What was the expected behavior? What didn't work?

**Comment by mohamed-moaz-ibrahim** [comment]
I'm trying to extend the identity user entity, I have a property that is a foreign key to another table which should be displayed as  select component in the angular ui. 

I did the steps exactly the same as explained [here](https://docs.abp.io/en/abp/latest/Module-Entity-Extensions#navigation-properties-foreign-keys) but it didn't shows as expected

**Comment by armanozak** [comment]
Hi @mmoazibrahim,

Sorry for the late response.

What you see is not an ordinary `<input>`. It is a typeahead component and it will make requests and display some options when you start typing in it. This is the default behavior of the extensions module and provides a better UX in most cases. The `autocomplete` attribute is set as `off` to avoid any automated assistance from the browser.
