### ISSUE TITLE
Set Default Language to zh-Hans ,IdentityServer Register Passwords Error Message is en

### ISSUE THREAD

**Issue by happygb21-jc** [abpframework/abp#9074]
![image](https://user-images.githubusercontent.com/55523727/118767867-e0311500-b8b0-11eb-9660-8f621679a50a.png)

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI

**Comment by happygb21-jc** [comment]
Sorry, Use ABP Framework 4.2.2 , User Interface type is Angular , Login jump identityServer account/login page

**Comment by maliming** [comment]
Can you try this in the latest version(4.3)?

**Comment by happygb21-jc** [comment]
OK，upgrade 4.3 try it

**Comment by happygb21-jc** [comment]
After upgrading, it works normally。Thanks
