### ISSUE TITLE
Join with ABP users entity ( 2 diferent databases)

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#9075]
I have 2 different modules , with 2 sepereated databases, 
in the second module (the one which not have identity module entities), I have entity "A",
I need to make a join with AppUser entity to get the username for creator or modifier of entity "A".

Is there any available soultion for this scenario? 
I thought I can add a duplicate entity for users in the second moduleو with just (ID & username)? is there any way to add new users data to this duplicate entity?

**Comment by amLabib** [comment]
any updates ??

**Comment by mrs01dev** [comment]
you could try to use IExternalUserLookupServiceProvider , as in 

https://github.com/EasyAbp/ReviewManagement/blob/4852d077ca523a9d49cd75bb7b881778bb5699f8/src/EasyAbp.ReviewManagement.Application/EasyAbp/ReviewManagement/Reviews/ReviewAppService.cs
