### ISSUE TITLE
Migrate JetBrains.Annotations to Nullable reference types

### ISSUE THREAD

**Issue by pengweiqhca** [abpframework/abp#9083]
JetBrains.Annotations need Resharper or Rider support, NRT is dotnet native support.

[NotNull]=> Empty
[MaybeNull] => nullable

**Comment by maliming** [comment]
Please explain your idea in detail.

**Comment by 274188A** [comment]
i think what he is saying is that the source code has a dependency on `JetBrains.Annoations` which is kind of 3rd party - not native
