### ISSUE TITLE
How to make a report in mvc razor page?

### ISSUE THREAD

**Issue by nguyenquanghuyit** [abpframework/abp#9084]

**Comment by maliming** [comment]
Please explain your issue in detail.

**Comment by nguyenquanghuyit** [comment]
In Dev Express , I see many sample about report template. But I do not know how to make report by abp.io mvc/razor pages
for example: Master-Detail Reports
https://docs.devexpress.com/XtraReports/5152/create-reports

**Comment by maliming** [comment]
We have an article about using Dev Express in Abp. You can take a look.

https://community.abp.io/articles/using-devextreme-components-with-the-abp-framework-zb8z7yqv

**Comment by leonkosak** [comment]
For DX localization (**Intl**), where:

```
<script>
    DevExpress.localization.locale("de");
</script>
```

should be placed in abp project?
Thank you.

https://docs.devexpress.com/AspNetCore/400577/devextreme-based-controls/concepts/localization#intl

**Comment by maliming** [comment]
@cotur 

Do you have any advice of `DevExpress.localization.locale("de");`?

**Comment by cotur** [comment]
If the `DevExpress Localization` scripts requires to be located at `<head>..</head>`, 
You should use the [Layout Hooks](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Layout-Hooks).

**Comment by leonkosak** [comment]
I think that this is not required. Where do you suggest that should this part of code be located (for setting DX localization) @cotur?
