### ISSUE TITLE
how to make relational migration?

### ISSUE THREAD

**Issue by muratcabuk** [abpframework/abp#909]
Do you have any plan to relational migration in the future? 
I can not see kind of following example. Migration doesn't create any foreign key physically in database.

````csharp
public class Product
{
   public int ProductId {get; set;}
   public string ProductName {get; set;}
   public virtual Category Category {get; set;}
}

product class Category
{
   public int CategoryId {get; set;}
   public string CategoryName {get; set;}
   public virtual ICollection<Product> Products {get; set;}
}
````

**Comment by hikalkan** [comment]
We are using EF Core migrations. There is nothing special for ABP. EF Core supports foreign keys when you configure it. See EF Core migrations document for more: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/
