### ISSUE TITLE
Basic Template Blazor Server: RedirectToLogin wrong uri

### ISSUE THREAD

**Issue by d-oit** [abpframework/abp#9104]
* Your **ABP Framework version**.
*** 4.3**
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
*** Blazor Server**
* Your database provider(EF Core/MongoDB)
* Ef Core
* Exception message and **stack trace** if available (check the logs).
wrong url / not found: authentication/login
* Steps needed to **reproduce** the problem.
add index page:
@page "/"
@attribute [Authorize]

Possible fix for RedirectToLogin.razor

```
@inject NavigationManager Navigation
@inject IJSRuntime JsRuntime

@code { protected override void OnInitialized()
    {
        bool isWebAssembly = JsRuntime is IJSInProcessRuntime;
        if (isWebAssembly)
        {
            Navigation.NavigateTo($"authentication/login?returnUrl={Uri.EscapeDataString(Navigation.Uri)}");
        }
        else
        {
            Navigation.NavigateTo($"account/login?returnUrl={Uri.EscapeDataString(Navigation.Uri)}");
        }
    } }
```

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0#role-based-and-policy-based-authorization -> scroll up. not a nice handling at the moment from ms in the standard template(s).

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/9148
