### ISSUE TITLE
Oracle Provider map class to Table,  Can add   className  before the table  pkId?

### ISSUE THREAD

**Issue by crashsol** [abpframework/abp#9105]
when use offical  modules  such as  Volo.Abp.Identity ,Volo.Abp.Audting modules  with Oracle Provider ,oracle table need the table pkId  like  TableNameId,  can add IdPrefixWithClassName setting  to options ?  so the class IdentityUser key colunm Id map to  IdentityUserId,    thank you
` builder.ConfigureIdentity(optjons => {

                optjons.Schema = "Cement";
                optjons.TablePrefix = "Abp";
                optjons.IdPrefixWithClassName = true;

  })
`

**Comment by maliming** [comment]
hi

Our modules not only for Oracle. :)

**Comment by crashsol** [comment]
谢谢马哥，那我通过fluentApi来设置一下。
