### ISSUE TITLE
Auditing: EntityHistoryHelper ExtraProperties field compare question

### ISSUE THREAD

**Issue by JadynWong** [abpframework/abp#9113]
v4.3.0 / MVC

https://github.com/abpframework/abp/blob/cb086c9bd6fada3564f59b4afce29905026b4308/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs#L223-L256

For the `ExtraProperties` field the default `Equals` is currently used for comparison. This will always be true.
I think we should use a custom `IEqualityComparer' when the field is `ExtraProperties'.

**Comment by maliming** [comment]
> FThis will always be true.

Can you explain why?

**Comment by JadynWong** [comment]
`ExtraProperties` as reference types directly and compare ever different.
EntityFrameworkCore uses `ExtraPropertyDictionaryValueComparer` to audit in a similar way.

```c#
[Fact]
public virtual async Task Should_Write_AuditLog_Without_ExtraPropertyDictionary_For_Entity_Update_That_Meet_Selectors()
{
    var entityId = Guid.NewGuid();
    var repository = ServiceProvider.GetRequiredService<IBasicRepository<AppEntityWithSelector, Guid>>();
    await repository.InsertAsync(new AppEntityWithSelector(entityId, "test name"));

    using (var scope = _auditingManager.BeginScope())
    {
        using (var uow = _unitOfWorkManager.Begin())
        {
            var entity = await repository.GetAsync(entityId);
            entity.Name = "new name1";

            await repository.UpdateAsync(entity);

            await uow.CompleteAsync();
        }

        await scope.SaveAsync();
    }

#pragma warning disable 4014
    _auditingStore.Received().SaveAsync(Arg.Is<AuditLogInfo>(x =>
        x.EntityChanges.Count == 1 && x.EntityChanges[0].PropertyChanges.Count == 1 &&
        !x.EntityChanges[0].PropertyChanges.Any(x => x.PropertyName == nameof(AppEntityWithSelector.ExtraProperties))));
#pragma warning restore 4014
}
```

![image](https://user-images.githubusercontent.com/13699353/119070711-1d191b00-ba1b-11eb-9e20-69c933a19a62.png)

![code](https://user-images.githubusercontent.com/13699353/119070782-3cb04380-ba1b-11eb-8912-1c7d10eaf3ef.gif)

**Comment by JadynWong** [comment]
Hi @maliming，
Can you make `ShouldSavePropertyHistory`,`IsBaseAuditProperty` methods to protected virtual? 
For some reason, we need to record the change information of the entity's `LastModifierId`. If these methods were virtual, it would be easier to rewrite our own logic.
Thanks.

**Comment by maliming** [comment]
hi

Move to https://github.com/abpframework/abp/pull/9116 https://github.com/abpframework/abp/commit/987e154fedfe0e6dc5d9e3a0fb8561b3e994e26a
