### ISSUE TITLE
extract upload module for cmskit

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#9153]
now we need upload.
This function is available in cmskit(MediaDescriptor).
Can extract it into a separate module?

**Comment by cotur** [comment]
Hi @snowchenlei 

For file uploading & downloading process, there are many of different cases. And a reusable module needs to cover most of them. 
The best case is for now, you can create your own module for your upload/download requirements.

For CMS-Kit, we have just basic upload & download action.

Also, we may consider to create a reusable module for file Uploading & Downloading for next milestones. 

Need to be discuss on it. :) 
Thanks.
