### ISSUE TITLE
How to add log4net

### ISSUE THREAD

**Issue by sortjiajun** [abpframework/abp#916]

**Comment by maliming** [comment]
Abp actually uses the asp net core log component.
You can look at this: https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore

**Comment by sortjiajun** [comment]
> Abp实际上使用asp net core log组件。
> 你可以看一下：[https](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore)：[//github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore)

Thank you, it worked.
