### ISSUE TITLE
Synchronous interceptor fails if an invocation is not proceeded

### ISSUE THREAD

**Issue by pecanw** [abpframework/abp#9165]
If an Abp interceptor intercepts a synchronous call and does not call `invocation.ProceedAsync()` (e.g. if used for caching and returning a value from a cache) the call fails with a `System.InvalidOperationException: Interceptors failed to set a return value, or swallowed the exception thrown by the target`.

**Comment by pecanw** [comment]
Please find my proposed solution in #9164.

**Comment by pecanw** [comment]
Maybe, we can also omit the assignment `ReturnValue = await Proceed(Invocation, ProceedInfo);` in  `CastleAbpMethodInvocationAdapterWithReturnValue` and just call `await Proceed(Invocation, ProceedInfo);`.

Or even have just one `CastleAbpMethodInvocationAdapter` istead of the `CastleAbpMethodInvocationAdapterBase`, `CastleAbpMethodInvocationAdapter` and `CastleAbpMethodInvocationAdapterWithReturnValue`...

**Comment by maliming** [comment]
See discuss in https://github.com/abpframework/abp/pull/9164
