### ISSUE TITLE
SetModificationAuditProperties fires even when only generated properties were changed.

### ISSUE THREAD

**Issue by AelithBlanchett** [abpframework/abp#9166]
- **ABP Framework version**: 4.3
- **Database Provider**: EF Core + MySQL

On entities inheriting from AuditedEntity<T> with a property annotated as `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]`, SetModificationAuditProperties in AbpDbContext fires even when only generated properties were changed.

To reproduce:

- Run one of the sample projects: https://github.com/abpframework/abp-samples/tree/master/BookStore-Blazor-EfCore
- In `src/Acme.BookStore.Domain/Books/Book.cs`, add the following property:
```
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public int RandomNumber
{
    get
    {
        return new Random().Next();
    }
    protected set { }
}
```
- Call BookAppService.GetListAsync()

Even though `RandomNumber` was the only property that's been changed due to the Next() call, which was marked as generated, the LastModifiedDate will then also be updated which will by itself mark the entity as dirty and the changes are saved in the database even when just loading the entity.

Proposed fix in AbpDbContext.cs ( https://github.com/abpframework/abp/blob/536584edb5c66513434ee1c7b1c1a9a4344ed40b/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L520 ):

```
protected virtual void SetModificationAuditProperties(EntityEntry entry)
{
    if (entry.State == EntityState.Modified 
        && !entry.Properties.Where(x => x.IsModified).All(x => x.Metadata.GetBeforeSaveBehavior() == Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore))
    {
        AuditPropertySetter?.SetModificationProperties(entry.Entity);
    }
}
```

**Comment by AelithBlanchett** [comment]
This bug is also directly related to https://github.com/abpframework/abp/issues/8740 since this error pops up in a GET method.

**Comment by maliming** [comment]
HI @AelithBlanchett 

I think this also works.

```
if (entry.Properties.Any(x => x.IsModified && x.Metadata.ValueGenerated == ValueGenerated.Never))
{
   AuditPropertySetter?.SetModificationProperties(entry.Entity);
}
```
