### ISSUE TITLE
Tenant is not changed in switch of login box after logout (when he has been switched to inside Angular app)

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#9167]
4.3.0 / Angular.

We use custom functionality to switch between tenants inside Angular app. And it works perfect. However, after upgrading from version 3.3.2 we came up with the issue: the tenant which has been switched to IS NOT DISPLAYED as a current tenant in Login: instead, old tenant is displayed. I took a look at your source code and cannot figure out why:

```
  switch(tenant: Models.Common.Lookup<string>) {
    this.oAuthService.configure(
      this.environment.oAuthConfig,
    );
    const loadingToaster: any =
      this.toaster.info('::Tenants:PleaseWait', '::Tenants:Switching', { ...this.toasterOptions && { sticky: true } });

    return from(this.oAuthService.loadDiscoveryDocument())
      .pipe(
        switchMap(() =>
          from(
            this.oAuthService.fetchTokenUsingGrant(
              'switch_tenant',
              { token: this.oAuthService.getAccessToken(), tenant: tenant.id }
            )
          ),
        ),
        take(1)
      )
      .subscribe(
        () => {
          this.toaster.remove(loadingToaster);
          this.toaster.success(
            '::Tenants:SwitchingSucceeded',
            '::Tenants:Switching',
            { ...this.toasterOptions && { life: 2000 } });
          this.sessionStateService.setTenant({ id: tenant.id, name: tenant.displayName } as CurrentTenantDto);
          this.appConfigService.get().subscribe(result => {
            this.configStateService.setState(result);
            const newTenant = this.sessionStateService.getTenant(); // HERE EVERYTHING IS OK!!!
            this.setReloadRouteSettings();
            this.router.navigate(['/']).then(ready => {
              if (ready) {
                this.restoreDefaultRouteSettings();
              }
            });
          });
        },
        () => {
          this.toaster.remove(loadingToaster);
          this.toaster.error(
            '::Tenants:SwitchingFailed',
            '::Tenants:Switching',
            { ...this.toasterOptions && { life: 2000 } });
        }
      );
  }
```

![image](https://user-images.githubusercontent.com/6149843/119737178-879ce180-be87-11eb-8f9d-9414c8bf7965.png)

OLD TENANT name is still displayed below after logout:

![image](https://user-images.githubusercontent.com/6149843/119736934-2aa12b80-be87-11eb-84a6-6712831beec5.png)

**Comment by alexandis** [comment]
UPDATE: I've already found out that '__tenant' cookie keeps old tenant's value. Seems like this is the reason of the problem. But why it is not replaced with new tenant's id when switching a tenant in my case?? I follow the tenant switch box logic...

**Comment by alexandis** [comment]
Sorry, any progress? It has been a while...

**Comment by mehmet-erim** [comment]
Hi @alexandis,

I can't reproduce that. Can you provide a small repository? Please note that create a new repo with app (-t app) template, not app pro.

**Comment by alexandis** [comment]
Uhm, it's hardly feasible - Tenant Switching functionality is a tightly bound to backend, DB structure...
I hoped that the client-side code above could bring some questions - probably is not fully correct from ABP 4.3.0 prospective.

**Comment by mehmet-erim** [comment]
Changing the tenant affects the whole app, did you try to hard refresh ( `location.href = '/';`)

**Comment by alexandis** [comment]
@mehmet-erim makes no difference. Could you please explain why after successful switching to another tenant and logging off I still have my 'old' tenant's cookie? If I manually delete this one in the browser and reload login page - switch box displays no tenant name selected. So there's dependency between this fact and my issue, I suppose: if there was new tenant's entry there - it would be in switch box instead.

This is what I have after logout, when previously I switched to another tenant in my UI:

![image](https://user-images.githubusercontent.com/6149843/122618192-6d28e300-d096-11eb-80ec-505812c3e8d2.png)

**Comment by maliming** [comment]
>  Could you please explain why after successful switching to another tenant and logging off I still have my 'old' tenant's cookie?

Hi

How to repro this?

**Comment by alexandis** [comment]
> How to repro this?

Hi, I cannot share our solution - switching tenant from within **Angular** app is our custom functionality. But the idea is pretty simple - and I think you can repro it in your test app using basically `IExtensionGrantValidator` overriding (see below) and front-end piece using the code above. Probably `IExtensionGrantValidator` needs to rewrite **_tenant** cookie? But in previous ABP version our functionality worked as is...

```
    public class SwitchToTenantGrantValidator : IExtensionGrantValidator
    {
        private readonly ITokenValidator     _validator;
        private readonly ICurrentTenant      _currentTenant;
        private readonly IdentityUserManager _userManager;

        public SwitchToTenantGrantValidator
        (
            ITokenValidator validator,
            ICurrentTenant  currentTenant,
            IdentityUserManager userManager
        )
        {
            _validator      = validator;
            _currentTenant  = currentTenant;
            _userManager    = userManager; 
        }

        public string GrantType => "switch_tenant";

        public async Task ValidateAsync(ExtensionGrantValidationContext context)
        {
            var userToken = context.Request.Raw.Get("token");

            if (string.IsNullOrEmpty(userToken))
            {
                context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant);
                return;
            }

            var strTenantId      = context.Request.Raw.Get("tenant");
            var tenantIdToSwitch = strTenantId?.ToGuid();

            if(!string.IsNullOrWhiteSpace(strTenantId) && tenantIdToSwitch == Guid.Empty)
            {
                context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant);
                return;
            }

            var result = await _validator.ValidateAccessTokenAsync(userToken);
            if (result.IsError)
            {
                context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant);
                return;
            }

            // get user's identity
            var userId   = result.Claims.FirstOrDefault(c => c.Type == "sub")?.Value;
            var tenantId = result.Claims.FirstOrDefault(c => c.Type == "tenantid")?.Value?.ToGuid();

            // Getting user name in current tenant
            string username = null;
            using (_currentTenant.Change(tenantId))
            {
                var abpUser = await _userManager.FindByIdAsync(userId);
                if(abpUser == null)
                {
                    context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant);
                    return;
                }
                username = abpUser.UserName;
            }

            // Getting user Id from tenant, where user will be switched
            using (_currentTenant.Change(tenantIdToSwitch))
            {
                var abpUser = await _userManager.FindByNameAsync(username);
                if (abpUser == null)
                {
                    context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant);
                    return;
                }
                if (abpUser.LockoutEnd?.DateTime > DateTime.Now)
                {
                    context.Result = new GrantValidationResult(TokenRequestErrors.InvalidTarget);
                    return;
                }

                userId = abpUser.Id.ToString();
            }

            context.Result = new GrantValidationResult(userId, GrantType, tenantIdToSwitch == null ? null : new List<Claim> 
            {
                new Claim("tenantid", tenantIdToSwitch?.ToString()) 
            });

            return;
        }
    }
```

**Comment by maliming** [comment]
The `IExtensionGrantValidator` should not control cookies. You can manually change cookies after this endpoint is successfully called.

**Comment by alexandis** [comment]
Ok. The question is "is _tenant - ABP Cookies"? I think it is. Where exact file and place I need to replace this cookie? Please show the relevant suitable code fragment. I may try then to do what you say, bit if this doesn't work, I would kindly ask you to repro the issue.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy/Pages/Abp/MultiTenancy/TenantSwitchModal.cshtml.cs#L61-L69

**Comment by alexandis** [comment]
> https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy/Pages/Abp/MultiTenancy/TenantSwitchModal.cshtml.cs#L61-L69

Thank you. Yeap, this is the code I would need to use when switching tenants within **Angular** app. You now have the only place, where tenant switch is done manually by user on login page. However, in our case this needs to be done on back-end after successful tenant switching. Though, as we can see, `SwitchToTenantGrantValidator` just has `Task ValidateAsync` call, afterwards we get back to **Angular** app and calling `this.sessionStateService.setTenant` in subscription. Don't have idea for the moment, where should I put the code with current tenant's cookie replacement? Saying

> You can manually change cookies after this endpoint is successfully called.

did you mean to intercept the code below with _Request middleware_ or there's a better way? I've actually tried to intercept request and change the cookie, but the cookie has never been replaced...

![image](https://user-images.githubusercontent.com/6149843/123777829-3eeaa500-d8d9-11eb-893e-105134269d9d.png)

I've tried the following _Identity Server_ _middleware_, but it does not work - the cookie is not replaced:

```
    public class TenantSwitchMiddleware
    {
        private readonly RequestDelegate _next;

        public TenantSwitchMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task InvokeAsync(HttpContext httpContext, IAbxRequestContext requestContext, IdentityUserManager userManager)
        {
            if (httpContext.Request.Path.Value == "/connect/token"
                && httpContext.Request.Form.TryGetValue("grant_type", out StringValues grantType)
                && httpContext.Request.Form.TryGetValue("tenant", out StringValues tenant))
            {
                if (grantType.ToString() == "switch_tenant")
                {
                    httpContext.Response.Cookies.Append(
                           "__tenant", //Options.TenantKey,
                           tenant.ToString(), //tenant.Id.ToString(),
                           new CookieOptions
                           {
                               Path = "/",
                               HttpOnly = false,
                               Expires = DateTimeOffset.Now.AddYears(10),
                               SameSite = SameSiteMode.Strict,
                               IsEssential = true,
                               Secure = true
                           }
                       );
                }
            }
            await _next(httpContext);
        }
    }
```

**Comment by maliming** [comment]
hi

Is ` httpContext.Response.Cookies.Append` executed?

You can also try ` httpContext.Response.OnStarting`
```cs
 httpContext.Response.OnStarting(
          () =>
          {
              httpContext.Response.Cookies.Append(
                           "__tenant", //Options.TenantKey,
                           tenant.ToString(), //tenant.Id.ToString(),
                           new CookieOptions
                           {
                               Path = "/",
                               HttpOnly = false,
                               Expires = DateTimeOffset.Now.AddYears(10),
                               SameSite = SameSiteMode.Strict,
                               IsEssential = true,
                               Secure = true
                           }
                       );

              return Task.CompletedTask;
          });
```

**Comment by alexandis** [comment]
> Is ` httpContext.Response.Cookies.Append` executed?
> 
> You can also try ` httpContext.Response.OnStarting`

Yes, it is called and cookie is appended to the response:

![image](https://user-images.githubusercontent.com/6149843/123931414-26da5a80-d999-11eb-8821-7c364e9c8f45.png)

However, eventually the __tenant cookie is not replaced with the new value:

![image](https://user-images.githubusercontent.com/6149843/123931495-3c4f8480-d999-11eb-84a0-8a87f7395728.png)

What am I doing wrong?

**Comment by maliming** [comment]
hi

The `__tenant` cookie belongs to the Angular website. 

You can directly change the tenant's cookies in Angular.

**Comment by alexandis** [comment]
> You can directly change the tenant's cookies in Angular.

Hmm.. Not sure it's a good idea to set cookie on client-side. We have not done this so far... I took a look ABP source code and could not find you set cookie on client-side somewhere either...

BTW, you say `_tenant` cookie belongs to the **Angular** website. But the site this cookie is used is actually **Identity Server** site:

![image](https://user-images.githubusercontent.com/6149843/123936973-5cce0d80-d99e-11eb-9db1-9e156d45f409.png)

And I can see its cookie:

![image](https://user-images.githubusercontent.com/6149843/123937081-7b340900-d99e-11eb-82cb-95a0f3f70b2a.png)

Even if it is the same cookie shared by **IdentityServer** and **Angular** app (_localhost_ cookie) - I cannot get why it is not replaced in the middleware code above.

**Comment by alexandis** [comment]
UPDATE: the problem is resolved. I just needed to add `withCredentials: true` to my **Angular** `HttpClient` post request to let the cookie be saved.
