### ISSUE TITLE
use swagger-ui, http post、put 、delete 400 bad request

### ISSUE THREAD

**Issue by ldwstyle** [abpframework/abp#917]
when I user swagger-ui, http get request  is success,but  post 、put、delete is 400 bad request!

code 
![TIM图片20190326114521](https://user-images.githubusercontent.com/30330931/54970314-9db76a80-4fbc-11e9-9dc2-90365769d32b.png)

error
![TIM图片20190326114542](https://user-images.githubusercontent.com/30330931/54970317-a14af180-4fbc-11e9-8834-0ebbcaaee95d.png)

**Comment by maliming** [comment]
Is this aspnetboilerplate?
Please check the log, what is the stack information of the http(400) error?

**Comment by ldwstyle** [comment]
> Is this aspnetboilerplate?
> Please check the log, what is the stack information of the http(400) error?

yes,I use the abp templates ( https://aspnetboilerplate.com/Templates),and reference the url (https://aspnetboilerplate.com/Pages/Documents/Swagger-UI-Integration) to install the swagger-ui

here is the log :


![TIM图片20190326125131](https://user-images.githubusercontent.com/30330931/54972260-cc860e80-4fc5-11e9-9f7f-8dfaef2fc889.png)

**Comment by ismcagdas** [comment]
Are you using https://github.com/aspnetboilerplate/module-zero-core-template ? Or Did you add swagger-ui by yourself ?

**Comment by ldwstyle** [comment]
> Are you using https://github.com/aspnetboilerplate/module-zero-core-template ? Or Did you add swagger-ui by yourself ?

,I use the abp templates ( https://aspnetboilerplate.com/Templates), and reference the url (https://aspnetboilerplate.com/Pages/Documents/Swagger-UI-Integration) to install the swagger-ui

**Comment by ismcagdas** [comment]
Could you try to use it like https://github.com/aspnetboilerplate/module-zero-core-template/tree/master/aspnet-core/src/AbpCompanyName.AbpProjectName.Web.Host/wwwroot/swagger/ui ?

We should review the documents, I will create an issue about it on https://github.com/aspnetboilerplate/aspnetboilerplate/ repository.

**Comment by ldwstyle** [comment]
I have solved the problem!
reference the url  (https://aspnetboilerplate.com/Pages/Documents/XSRF-CSRF-Protection)
Thank you for your help!
