### ISSUE TITLE
Redis not works

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#9175]
I followed [official doc](https://docs.abp.io/en/abp/latest/Redis-Cache)
I configured redis, in `appsettings.json` like 
`
"Redis": {
        "IsEnabled": "true",
        "Configuration": "server ip,password=*******"
    }
`
and add nuget package Volo.Abp.Caching.StackExchangeRedis into my module.
I use IDistributedCache interface to set/get value from redis, but I get null.(I can ensure that the key value is stored in redis )
Is IDistributedCache only local cache, if I want to use redis what interface I should use?

**Comment by trickyrat** [comment]
abp user role data store in redis
![image](https://user-images.githubusercontent.com/19605145/119843398-19fdbd80-bf3a-11eb-8563-cbbf2f00704c.png)
so I connect redis successfully
I use IDistributedCache.GetAsync method to get value. The value is a json string, I tried GetAsync<string> and GetAsync<RedisUser>(),(RedisUser is the json object class), the both ways return null.
![image](https://user-images.githubusercontent.com/19605145/119843235-ef136980-bf39-11eb-93f6-c5adf81d56c8.png)
![image](https://user-images.githubusercontent.com/19605145/119843249-f0dd2d00-bf39-11eb-8f6a-3cff60f86dd2.png)
This is the key I want to get in redis.
![image](https://user-images.githubusercontent.com/19605145/119844119-c049c300-bf3a-11eb-93a6-90880010cadf.png)

**Comment by ArcherTrister** [comment]
@trickyrat how did you solve it?

**Comment by trickyrat** [comment]
you need to add import AbpCachingStackExchangeRedisModule into your module

**Comment by ArcherTrister** [comment]
> 

I have done this but it still doesn't work，like this
![1111](https://user-images.githubusercontent.com/35516482/160730135-8c03cd2e-f5b4-4ae3-8928-341f72999e31.png)
