### ISSUE TITLE
How to catch this exception,An internal error occurred during your request

### ISSUE THREAD

**Issue by sortjiajun** [abpframework/abp#918]
![image](https://user-images.githubusercontent.com/16735741/54971029-9180dc80-4fbf-11e9-91b0-9429c59c77e3.png)
![image](https://user-images.githubusercontent.com/16735741/54971193-4adfb200-4fc0-11e9-8cd6-dc6f20701711.png)
![image](https://user-images.githubusercontent.com/16735741/54971211-54691a00-4fc0-11e9-99b7-f32617bfa926.png)

**Comment by maliming** [comment]
Please check the log, what is the error message and stack information of the internal error?

**Comment by sortjiajun** [comment]
> 信息

I can not find the log

**Comment by maliming** [comment]
The template project log exists in the `Logs/logs.txt` file.

**Comment by sortjiajun** [comment]
![image](https://user-images.githubusercontent.com/16735741/54976846-87b6a380-4fd6-11e9-9342-16a80ec15728.png)
@maliming 
I could not find the error.

**Comment by sortjiajun** [comment]
[OneCode.Shop.zip](https://github.com/abpframework/abp/files/3007053/OneCode.Shop.zip)
This is my project.
