### ISSUE TITLE
[Question]How to set/get custom key in IDsitributedCache's GetAsync/SetAsync method?

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#9187]
I read source code.There is a DistributedCacheKeyNormalizer class and it has a NormalizeKey method.All cache keys formatted like `var normalizedKey = $"c:{args.CacheName},k:{DistributedCacheOptions.KeyPrefix}{args.Key}";`. But if I want to set custom format key or get custom format key, what I should do?

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Caching#idistributedcachekeynormalizer
