### ISSUE TITLE
dependency injection occur  "Cannot access a disposed object"

### ISSUE THREAD

**Issue by sesamefly** [abpframework/abp#919]
It  occur  when use B appService class at A appService. Help Me !Thx!

System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances

**Comment by maliming** [comment]
please show you code.

**Comment by sesamefly** [comment]
OK, It like this
Class A 
`
 public class BabyPropAppService : BsmpApplicationServiceBase<BabyProp, int, BabyPropEditDto, BabyPropEditDto, GetBabyPropsInput, BabyPropListDto>, IBabyPropAppService
    {
        private readonly IRepository<BabyProp, int> _entityRepository;
      
        private readonly IBabyPropTermApplicationService _babyPropBuyTermApplicationService;
        /// <summary>
        /// 构造函数 
        ///</summary>
        public BabyPropAppService(
        IRepository<BabyProp, int> entityRepository
      
         , IBabyPropTermApplicationService babyPropBuyTermApplicationService
        ) : base(entityRepository)
        {
            _entityRepository = entityRepository;

            _babyPropBuyTermApplicationService = babyPropBuyTermApplicationService;
        }

        public  async Task<ICollection<GetFamilyPropBuyInfoOutputPropTerm>> GetPropBuyTerms(PropStaffBuyTermInput input)
        {
            //var buyTermTypes = await _babyPropBuyTermTypeRepository.GetAllListAsync();
            var itemTerms = new List<GetFamilyPropBuyInfoOutputPropTerm>();
            input.BabyProp.BabyPropTerms.ToList().ForEach(async d =>
            {
                // 条件类型
                //var termType = buyTermTypes.FirstOrDefault(o => o.Id == d.BabyPropBuyTermId);
                // 获取条件
                    var termStaff = await **_babyPropBuyTermApplicationService.ValideBabyPropTermSatisfyHandle**(new BabyPropBuyTermIsSatisfyInput() { FamilyId = input.FamilyId, Term = d, BabyId = input.BabyId, BabyProp = input.BabyProp, BabyPropBuyTermType = null });
                    var term = new GetFamilyPropBuyInfoOutputPropTerm() { Id = d.Id, IsSatisfy = termStaff, Title = null};
                    itemTerms.Add(term);
            });
            return itemTerms;
        }
    }
`
Class B :
`
 public class BabyPropTermApplicationService : IBabyPropTermApplicationService
    {
        private readonly IRepository<Baby, int> _babyRepository;
        private readonly IRepository<PlayerProfession, int> _playerProfessionRepository;

        public BabyPropTermApplicationService(
            IRepository<Baby, int> babyRepository
            , IRepository<PlayerProfession, int> playerProfessionRepository
            )
        {
            _babyRepository = babyRepository;
            _playerProfessionRepository = playerProfessionRepository;
        }

        public async Task<bool> ValideBabyPropTermSatisfyHandle(BabyPropBuyTermIsSatisfyInput input)
        {
            var res = false;
            switch (input.BabyPropBuyTermType.Name)
            {
              
                case "MotherProfessionLevel":
                    res = await ProfessionLevelTermValidate(input, "mom");
                    break;
            }
            return res;
        }
   
        private async Task<bool> ProfessionLevelTermValidate(BabyPropBuyTermIsSatisfyInput input, string parentName)
        {
            **var baby = await _babyRepository.GetAllIncluding(s => s.Family).AsNoTracking()
                .FirstOrDefaultAsync(s => s.Id == input.BabyId && s.FamilyId == input.FamilyId);**
            var profession = await _playerProfessionRepository.GetAllIncluding()
                     .WhereIf(parentName == "mom", s => s.PlayerId == baby.Family.MotherId)
                     .WhereIf(parentName == "dad", s => s.PlayerId == baby.Family.FatherId)
                     .FirstOrDefaultAsync(s => s.IsCurrent && s.FamilyId == input.FamilyId);
            return profession.Level >= input.Term?.MinValue && profession.Level <= input.Term?.MaxValue;

        }
      }
`

**Comment by maliming** [comment]
Are you using the framework [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate)?

**Comment by sesamefly** [comment]
> Are you using the framework [aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate)?

yes

**Comment by maliming** [comment]
move: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4393
