### ISSUE TITLE
abp MVC - how to get token

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#9190]
abp v4.3 (for instance)
tiered solution
MVC gui

For some reason, I have to make a call with HttpClient (C#) from javascript (or cshtml, cshtml.cs) to Authorized method on API.
How to properly set http header in HttpClient with token?

abp.auth.getToken() returns null.

There are a lot of entries in cookies:
![image](https://user-images.githubusercontent.com/39346964/120109753-1e5ced00-c16b-11eb-8a5a-64039a1514eb.png)

Thank you.

**Comment by maliming** [comment]
hi @leonkosak 

You can't get the token in `javascript `, only available in the backend.

**Comment by leonkosak** [comment]
So the recommended was is to use [abp.ajax](https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Ajax)?

**Comment by maliming** [comment]
No. You can only get/request token in the backend.

**Comment by leonkosak** [comment]
Of course, but abp.ajax can call authorized backend API method?

**Comment by maliming** [comment]
I think so, You can give it a try.

**Comment by leonkosak** [comment]
I have no success.
When you wrote "in the backend" - is this possible with ICurrentUser (code behind, controller inside .Web project)?
I really need jwt to call API side from MVC solution (from deployed .Web project to deployed .HttpApi.Host).

**Comment by maliming** [comment]
You can use application services directly on the web, why not do this?

**Comment by leonkosak** [comment]
Yes? Where can I find example for this?

**Comment by leonkosak** [comment]
Aghhh! My stupidity. :)

**Comment by leonkosak** [comment]
@maliming, I still need to get jwt token value on Controller (because on controller is HttpClient call on other microservice/app, which is connected to the same identity server).

**Comment by maliming** [comment]
See 
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Http.Client.IdentityModel.Web/Volo/Abp/Http/Client/IdentityModel/Web/HttpContextIdentityModelRemoteServiceHttpClientAuthenticator.cs#L37
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.IdentityModel/Volo/Abp/IdentityModel/IdentityModelAuthenticationService.cs#L57
