### ISSUE TITLE
IdentityServer4 need a paid license in ASP.NET Core 6

### ISSUE THREAD

**Issue by jiangzhengqun** [abpframework/abp#9201]
* ABP Framework version：4.2.2.
* Database Provider: EF Core + MySQL
* IdentityServer4 need a paid license in ASP.NET Core 6，
https://devblogs.microsoft.com/aspnet/asp-net-core-6-and-authentication-servers/，
I suggest use openiddict
https://github.com/openiddict/openiddict-core

**Comment by maliming** [comment]
Duplicate of #7221
