### ISSUE TITLE
AuthServer didn't redirect to user info as except when login success

### ISSUE THREAD

**Issue by GotzeWong** [abpframework/abp#9204]
### GitHub Issues

* **ABP 4.3.0**.
* **Microservices\applications\AuthServer.Host**
* **Server: Alin Cloud Web+ (Linux  x64)**

* **Description**
I deployed AuthServer on Ali cloud. Then the **AuthServer.Host** didn't redirect to user info when login success but return the init page again.
![image](https://user-images.githubusercontent.com/7664030/120284057-6eb08800-c2ee-11eb-842e-33b9222fc829.png)

Checked the log below
![image](https://user-images.githubusercontent.com/7664030/120327492-67a06e80-c31c-11eb-8268-094e6b336aea.png)

When I tried on localhost, it works well.

![image](https://user-images.githubusercontent.com/7664030/120327561-77b84e00-c31c-11eb-8fa9-a122adb71362.png)

**Why these two ids are different?**

@maliming, please help..
Any suggestions are welcome. Thks!

**Comment by realLiangshiwei** [comment]
Use https.

Or see https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n

**Comment by GotzeWong** [comment]
Thanks,  @realLiangshiwei, it works!
