### ISSUE TITLE
Dynamic client proxy at Blazor webassembly always call authorize but the target api doesn't require

### ISSUE THREAD

**Issue by khanhtranchi** [abpframework/abp#9205]
* Your **ABP Framework version**: 4.3.2
* Your **User Interface** type: Blazor webassembly
* Your database provider: MongoDB

I have create app service is ILeadChannelAppService  and inject it into Blazor webassembly. If I don't login and call to the api through HttpApi.Client module - the client proxy always calls to the identity server for authorizing but It will be failed and take time before call my target api:

![image](https://user-images.githubusercontent.com/10261012/120287362-6275fc00-c2e9-11eb-8553-825c3aec975e.png)

Here is the code at razor file:
@inject ILeadChannelAppService _leadChannelAppService
leadChannel = await _leadChannelAppService.GetAsync(new Guid("01dccee1-2dbb-92dc-f997-39fcbe188e9e"));

But if user login success, the client proxy don't call authorize any more and call the target api immediately.

I don't know this is a bug or not. 

Thanks.

**Comment by maliming** [comment]
>  the client proxy always calls to the identity server for authorizing but It will be failed and take time before call my target API:

What's the error?

> But if user login success, the client proxy don't call authorize any more and call the target api immediately.

This is by design because we have the user's token right now.

**Comment by khanhtranchi** [comment]
What's the error?

When user doesn't login, if I make a service call like this:
await _leadChannelAppService.GetAsync(new Guid("01dccee1-2dbb-92dc-f997-39fcbe188e9e"));

Instead of call the rest api, it always make call to this link first:
https://localhost:44307/_framework/blazor.boot.json
![image](https://user-images.githubusercontent.com/10261012/120409590-7407e400-c37b-11eb-85d0-6b729b01173d.png)
As you can see in the above image at Request Initiator Chain area, it call to identity server (but this rest api function doesn't authorize)

after that it call the rest api function.

Thanks.

**Comment by maliming** [comment]
hi
Can you share a project?

**Comment by khanhtranchi** [comment]
I create this project by using module template. For sure, I have created new test project from module template, but still face this problem as image below:
![error](https://user-images.githubusercontent.com/10261012/120449239-7426d480-c3b9-11eb-9e9c-c73db5e934a1.jpg)


I have uploaded it:
[https://drive.google.com/file/d/1OyJA0DfIPnafnAxK-JutggOeHcapZ2uw/view?usp=sharing](url)

Please change the redis and mongodb setting at:
- Test.HttpApi.Host
- Test.IdentityServer
- And Test.Blazor.Host, press F12 and choose the Network Tab, Press the Test link on the Top Navigation bar.

Thanks.

**Comment by maliming** [comment]
> Please change the redis and mongodb setting at:

I think this has nothing to do with mongodb , Please use ef in your project.

**Comment by khanhtranchi** [comment]
> > Please change the redis and mongodb setting at:
> 
> I think this has nothing to do with mongodb , Please use ef in your project.

I mean you change the mongodb and redis configurations at appsettings.json to your local or your development enviroment.
Did you run the Test.Blazor.Host ?

**Comment by maliming** [comment]
@khanhtranchi I don't have mongodb. Can you use Localdb?

**Comment by khanhtranchi** [comment]
I created another project using Localdb, and testing again but client proxy class still calls to https://localhost:44307/_framework/blazor.boot.json if we don't login before and later call the rest api. 
It should call the rest api and if need authorization just throw the exception.
![image](https://user-images.githubusercontent.com/10261012/120621284-f382d980-c487-11eb-8bcf-8f5522d281af.png)

You can download new project at:
https://drive.google.com/file/d/1y7pJfiIcJkwsaLEx7D9OUhwUIfdrE751/view?usp=sharing
