### ISSUE TITLE
abp-table tag helper issue on custom theme.

### ISSUE THREAD

**Issue by muhlisatac** [abpframework/abp#9206]
Hi!
I have a mvc ui project version abp 4.3.2.
I have used [AdminLTE](https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE ) theme.

Problem is footer and page scripts are rendering in wrong locations. Details are in [this issue](https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/issues/32)

But it seems issue is about abp-table tag-helper. Can any one investigate it please?

**Comment by maliming** [comment]
hi 

You should continue to discuss this on https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE

If you find a problem please provide the info below:

* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by muhlisatac** [comment]
I already wrote ABP Framework version. But it is 4.3.2
Its not an exception so there is no stack trace or log.

Steps are 
1. Download a new application project (mvc, efcore, sql server, not tiered).
2. Install-Package Abp.AspNetCore.Mvc.UI.Theme.AdminLTE
3. In Web project
```
[DependsOn(
    ...
    // typeof(AbpAspNetCoreMvcUiBasicThemeModule),
    typeof(AbpAspNetCoreMvcUiAdminLTEThemeModule),
    ...
]
public class YourWebModule : AbpModule
{
    ...
}
```

In pages if i use

`<table class="table" id="pppTable"></table>`

![2](https://user-images.githubusercontent.com/8949037/120312046-ebd50080-c2e0-11eb-8347-0ef7192b0712.png)

instead of

`<abp-table id="pppTable" />`

![1](https://user-images.githubusercontent.com/8949037/120312052-ec6d9700-c2e0-11eb-97d6-734ce8b4c270.png)

then it seems ok.

With abp-table tag helper application layout is rendering in wrong places.

**Comment by maliming** [comment]
hi

I think this is related to `Abp.AspNetCore.Mvc.UI.Theme.AdminLTE` instead of Abp.

**Comment by muhlisatac** [comment]
I have downloaded a new project. (Latest Mvc, Efcore, Sql server, not tiered.)
Added a test page and its appservices etc. Nothing else.
This is the result.

![image](https://user-images.githubusercontent.com/8949037/120448414-38c5df00-c394-11eb-9c10-3b503ed31688.png)

as you can see scripts randered in wrong place.

**Comment by maliming** [comment]
Can you share your project?

**Comment by muhlisatac** [comment]
[sure](https://github.com/abpframework/abp/files/6583151/test2.zip)
