### ISSUE TITLE
I get an error when I want to manage Tenant's features in Blazor template

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#9207]
Command: `abp new Test_App -t app -u blazor --database-provider ef`
Version: `4.3.2`

![Kapture 2021-06-01 at 11 43 53](https://user-images.githubusercontent.com/31216880/120295011-6b59d400-c2cf-11eb-8079-ac0baa258bcd.gif)

<img width="1440" alt="Screen Shot 2021-06-01 at 11 45 06 AM" src="https://user-images.githubusercontent.com/31216880/120295025-6e54c480-c2cf-11eb-9e6f-96b3e85fa91b.png">

<img width="1440" alt="Screen Shot 2021-06-01 at 11 45 30 AM" src="https://user-images.githubusercontent.com/31216880/120295035-70b71e80-c2cf-11eb-8e3c-9a28762956ae.png">

**Comment by cotur** [comment]
Yes, there is a bug.

Problem:
This bug occurs if there is no defined any feature for application.

If you have at least one feature for your application, you will not get error. 

But we need to handle that, it will be handled in 4.4.

**Comment by cotur** [comment]
It's fixed in 4.3 patch milestone.
