### ISSUE TITLE
[Suggestion] keycloak

### ISSUE THREAD

**Issue by afernandes** [abpframework/abp#921]
Suggestion: module for authentication and authorization of users using the keycloak
https://www.keycloak.org/

**Comment by dejancg** [comment]
@afernandes keycloak uses openid connect protocol, right?

**Comment by hikalkan** [comment]
We are using IdentityServer4. So, in short time, we don't want to spend time on that. However, it can be a good feature request for backlog.
Thanks.

**Comment by dejancg** [comment]
@hikalkan keycloak doesn't respect the protocol 100% as IdentityServer4 does, but the difference is minor and it wouldn't be a lot of job to implement it. However, the required changes need to be made in IdentityModel library, so I guess it would require forking IdentityModel and modifying it slightly to make it compatible with both keycloak and IdentityServer4.

**Comment by afernandes** [comment]
I still have not delved into the subject, so forgive me if I say nonsense.

But, the administrative part of IdentityServer4 is paid and Keycloak is Open Source.

In the way the project is today, is it possible to implement Single Sign-On and with an administrative area in an easy way?

**Comment by MedAnd** [comment]
Also interested in this feature for a large e-commerce project... any updates on the interoperability and libraries since this was originally raised... been over a year since the last comment?

**Comment by nicocomumu** [comment]
Now that Identity Server has become a commercial product, the discussion is back on the agenda.
It would be interesting to have other options such as keyclock or openiddict.

**Comment by evenlee** [comment]
same situation, keyclock is the only choice at the moment, it would be great if we support  keyclock and openiddict.

**Comment by abdumostafa** [comment]
I think a good support for Keycloak would be great, as many companies already have Keycloak working for their identity and access management needs.

**Comment by hikalkan** [comment]
Nowadays, we are working on Keycloak integration possibilities in parallel to the OpenIddict integration reseach.

**Comment by khoavn** [comment]
> Nowadays, we are working on Keycloak integration possibilities in parallel to the OpenIddict integration reseach.

May I ask if it's available now?

**Comment by hikalkan** [comment]
We've integrated Keycloak to this project: https://github.com/abpframework/eShopOnAbp
Currently, we are not planning any specific integration. You can use this example as a reference.
