### ISSUE TITLE
Volo.Authorization:010001 when using access token against backend services

### ISSUE THREAD

**Issue by Walk4Muscle** [abpframework/abp#9214]
Hi Team,

I am working on a project built on microservice demo project with independent identity services 4 as the auth server. 
When I followed OAuth 2 flow to acquire the access token,  and leverage this token to the backed service in moicrserives, I always got the following **401** error:

```
"error": {
        "code": "Volo.Authorization:010001",
        "message": "Authorization failed! Given policy has not granted.",
        "details": null,
        "data": {},
        "validationErrors": null
    }
```

![image](https://user-images.githubusercontent.com/14989270/120411137-df0ae800-c386-11eb-8828-2b31fc776b8e.png)

the payload of the access token is:
```
{
  "nbf": 1622597454,
  "exp": 1654133454,
  "iss": "https://localhost:44399",
  "aud": "IdentityService",
  "client_id": "backend-admin-app-client",
  "sub": "39fc96e3-d971-bf52-8183-824294393369",
  "auth_time": 1622597451,
  "idp": "local",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "admin",
  "preferred_username": "admin",
  "given_name": "admin",
  "role": "admin",
  "phone_number_verified": "False",
  "email": "admin@abp.io",
  "email_verified": "False",
  "name": "admin",
  "sid": "21F23A978925B7E8FCB517EE10A0A966",
  "iat": 1622597454,
  "scope": [
    "openid",
    "IdentityService"
  ],
  "amr": [
    "pwd"
  ]
}
```

the `AuthServer` configuration in the called backed service is :
```
 "AuthServer": {
    "Authority": "https://localhost:44399",
    "ApiName": "IdentityService"
  },
```

**Comment by Walk4Muscle** [comment]
don't know why, restart the backed service several times, it works now.

**Comment by GotzeWong** [comment]
@Walk4Muscle  How could I get access token value as u did？ Below is my token
![image](https://user-images.githubusercontent.com/7664030/126072866-b2cf1cfc-7716-4064-8399-09205e5ca2d9.png)
