### ISSUE TITLE
External IDaaS providers

### ISSUE THREAD

**Issue by dmeagor** [abpframework/abp#9222]
Feature request;

I see from other threads that IS is being made optional which is good.  It would be great if support for external identity providers  such as Azure B2C or firebase auth could be added though.

I don't think that passwords are something the majority of companies should be managing themselves and the larger IDaaS platforms have much better feature support passwordless/2fa tech such as security keys, windows hello, SAML and so on.

**Comment by dmeagor** [comment]
BTW. I went to post this on your commercial support site but it's down (503)

**Comment by maliming** [comment]
hi 

> I see from other threads that IS is being made optional which is good.

The IdentityServer is not optional for now.

>  It would be great if support for external identity providers such as Azure B2C or firebase auth could be added though.

We use the ASP NET Core standard authentication method, you can use Identity, Google, Twitter, etc. https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-5.0&tabs=visual-studio

In addition, we also support external authentication. https://github.com/abpframework/abp/issues/4977

**Comment by gterdem** [comment]
Hello @dmeagor,
IS can not be optional for abp angular apps since it is the STS. 

I agree your words on password management. 

Can you point out which abp application template you are using and want this behaviour?
