### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by realmingliang** [abpframework/abp#9228]
When I use business exception and define code and message at the same time, if the error code is not found in the localization file, the message  will be invalid at this time. Is this normal? Thank you
### For Example

```
public class MyException : BusinessException,
{
    public MyException():base("code","message"){
    }
}
```

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
