### ISSUE TITLE
Is the validation framework in already?

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#923]
Hi,

Was just wondering if the validation framework for DTO's similair to the old framework available? I see there is something to document it #487

**Comment by hikalkan** [comment]
It is similar and yes, working :)
See some samples here: https://github.com/abpframework/abp/blob/master/framework/test/Volo.Abp.Validation.Tests/Volo/Abp/Validation/ApplicationService_Validation_Tests.cs

**Comment by natiki** [comment]
FluentValidation still to come?

**Comment by hikalkan** [comment]
No plan for it yet. However, you can create a feature request to be added to the backlog.
