### ISSUE TITLE
Document: Allow to customize EF Core mapping of entity and dbContext of an existing module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#9234]
Documentation update for https://github.com/abpframework/abp/pull/8898

**Comment by realLiangshiwei** [comment]
We can also add some comment to the `MyProjectNameEfCoreEntityExtensionMappings`

https://github.com/abpframework/abp/blob/2a22ebdd343cdeff094968c6e554086a5b602d65/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.EntityFrameworkCore/EntityFrameworkCore/MyProjectNameEfCoreEntityExtensionMappings.cs#L19
