### ISSUE TITLE
Proper sample to filter on CreatorId filed using CurrentUser?

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#9235]
Using version 4.3, what is the proper way to filter on CreatorId of an AuditedEntity?  Does a sample exist for a class using implementing CrudAppService?

**Comment by mrs01dev** [comment]
for CrudAppService ,  filter on CreatorId ,check (GetListAsync and CreateFilteredQueryAsync ) in
https://github.com/EasyAbp/ReviewManagement/blob/main/src/EasyAbp.ReviewManagement.Application/EasyAbp/ReviewManagement/Reviews/ReviewAppService.cs

**Comment by djlaney3** [comment]
I understand now, thank you.  I was unaware that this ReviewManagment project existed.  Is that in the docs somewhere?
