### ISSUE TITLE
LastModificationTime is not updated populated when updating a value object property

### ISSUE THREAD

**Issue by newacc12** [abpframework/abp#9236]
ABP Version: 4.3.2
Database provider: EF

Description: LastModificationTime is not updated when updating a value object on the main entity. Possibly other audit properties as well.

Steps to reproduce:

1 - Create two classes as below:

```csharp
public class Person : FullAuditedEntity<Guid>
{
    public virtual FirstName FirstName { get; set; }

    private Person() { }

    public Person(FirstName name)
    {
        FirstName = name;
    }
}

public class FirstName : ValueObject
{
    public virtual string Name { get; }

    private FirstName() { }

    private FirstName(string name)
    {
        Name = name;
    }

    public static FirstName Create(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("name is null", nameof(name));

        return new FirstName(name);
    }

    protected override IEnumerable<object> GetAtomicValues()
    {
        yield return Name;
    }
}
```
2 - Configure Mapping:
```csharp
builder.Entity<Person>(b =>
{
    b.ToTable("People");

    //Configure the base properties
    b.ConfigureByConvention();

    b.OwnsOne(o => o.FirstName).Property(t => t.Name).IsRequired().HasMaxLength(50);
});
```
3 - Create App Service:
```csharp
public class PersonAppService : BookStoreAppService
{
    public PersonAppService(IRepository<Person> personRepository)
    {
        PersonRepository = personRepository;
    }

    public IRepository<Person> PersonRepository { get; }

    public async Task Create()
    {
        var person = new Person(FirstName.Create("test1"));
        await PersonRepository.InsertAsync(person);
    }

    public async Task Update()
    {
        var person = await PersonRepository.FirstAsync();
        person.FirstName = FirstName.Create("test2");
    }
}
```
4 - Open Swagger and call the create endpoint. Everything looks good and the CreationTime is populated correctly.
5 - Call the update endpoint. The name is update correctly but the LastModificationTime remains null.

Note: Adding another primitive type property to the class and updating it makes the LastModificationTime be populated correctly.

**Comment by newacc12** [comment]
I think this is due how ABP track the changes. The EF Change tracker will return 3 changes in this scenario:
1- One FirstName entity was deleted.
2 - Another FirstName entity was created.
3 - Person entity unchanged.

The solution might be to check if there are references that are OwnedTypes and check if they have been changed.

More info: https://stackoverflow.com/questions/51416721/ef-core-owned-property-state-propagation-to-parent-entity

Hope that helps

**Comment by maliming** [comment]
hi @newacc12 

We recommend always call `Repository.UpdateAsync(entity)` after the entity changed.

**Comment by newacc12** [comment]
Hey @maliming 

Thanks! That seemed to work. I think last time I worked with ABP it was not required to call the `UpdateAsync ` method since it should be called automatically at the end of a application service method. I will always call this from now on since it is the recommended way.

**Comment by maliming** [comment]
The reason is that your repository may be MongoDB, which has no entity tracking and must be manually called.
