### ISSUE TITLE
using dapper executes sql lock table

### ISSUE THREAD

**Issue by GOTOTHEWORLD** [abpframework/abp#9240]
ABP Framework version：v3.3.2
User Interface:None, just API internal error
database provider：EF Core
database:sql server 2016
---------------------------------
Hi,Team

When I use dapper to execute multiple SQLs, there is a table lock situation. As long as there is a selelct+update syntax in one of my SQLs, then my update table must be locked by the transaction. What method should I use after execution Unlock？

Code:
`var sql = @"SELECT  ID FROM  T_vip ORDER BY ID; UPDATE T_vipDetail SET status=1 WHERE ID=@ID";
var result = DbConnection.Query<VipUpgradeInfoRecord>(sql, new { ID = ID }, DbTransaction);`

the DbConnection uses the DapperRepository property in Volo.Abp.Dapper
In this case, the T_vipDetail table will be locked
![image](https://user-images.githubusercontent.com/19928040/120757739-859be800-c543-11eb-8995-6b6aa5b29c24.png)

Can I only check sql and then split select and update syntax to execute separately? Or do I have other ways to handle the unlocking of the transaction?

Thanks,
Ron

**Comment by maliming** [comment]
hi

Have you tried to execute this code in a separate unit of work?

https://docs.abp.io/en/abp/latest/Unit-Of-Work#begin-a-new-unit-of-work

**Comment by GOTOTHEWORLD** [comment]
> hi
> 
> Have you tried to execute this code in a separate unit of work?
> 
> https://docs.abp.io/en/abp/latest/Unit-Of-Work#begin-a-new-unit-of-work

Great, solved my problem perfectly,Thanks!
