### ISSUE TITLE
Can we use abp framework with Grpc based microservice and React as frontend, Any sample code Available for ref? #abp

### ISSUE THREAD

**Issue by manishkgupta02** [abpframework/abp#9249]
Can we use abp framework with Grpc based microservice and React as frontend, Any sample code Available for ref?
#abp
Use **abp** tag in your questions.

**Comment by mrs01dev** [comment]
For react , check
https://github.com/potatoabp/abp-vnext-react

**Comment by gterdem** [comment]
Hello @manishkgupta02,

There is no default configuration for Grpc communication between microservices at the time being. But it is on our backlog and we plan to entegrate it.
