### ISSUE TITLE
Native DLL loading for plugin modules

### ISSUE THREAD

**Issue by hillin** [abpframework/abp#9251]
Is there a guideline on how to handle native DLL loading for plugin modules?
In our project, plugin modules are loaded like this:

```c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddApplication<LocalAppBlazorModule>(options =>
        {
            var modulesDirectory = Path.GetFullPath("Modules");
            if (Directory.Exists(modulesDirectory))
            {
                options.PlugInSources.AddFolder(modulesDirectory);
            }
        });
    }
}
```

However if a plugin module directly or indirectly uses a native DLL, say, it uses SkiaSharp which needs libSkiaSharp.dll which is output to `Modules\runtimes\win-x64\native\libSkiaSharp.dll`, the native dll cannot be load correctly:

> System.DllNotFoundException: 'Unable to load DLL 'libSkiaSharp.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)'

**Comment by maliming** [comment]
Have you tried copy `Modules\runtimes\win-x64\native\libSkiaSharp.dll` to the `Modules` directory?

**Comment by hillin** [comment]
> Have you tried copy `Modules\runtimes\win-x64\native\libSkiaSharp.dll` to the `Modules` directory?

The outcome depends on the folder structure of the native files.

If the native DLL is placed in a subfolder under `Modules\runtimes\win-x64\native\`, copying the entire subfolder to `Modules` works, however I'd argue if this is the best practice except for debugging purpose;

If the native DLL is a single file located directly under the `Modules\runtimes\win-x64\native\` folder, copying it to the `Modules` folder will result abp trying to load it as a module, which fails with a `BadImageFormatException` and crashes the service (which by itself is another issue I guess, because it might not be a good idea to forbid native dlls being placed in the plugin folder):

> System.BadImageFormatException: Bad IL format. The format of the file 'Modules\libSkiaSharp.dll' is invalid.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)

**Comment by maliming** [comment]
hi

I think you can create a custom `FolderPlugInSource` to handle your case.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/Volo/Abp/Modularity/PlugIns/FolderPlugInSource.cs

**Comment by hillin** [comment]
Thanks.

By modifying the `FolderPlugInSource` to handle the `BadImageFormatException`, I can get the `libSkiaSharp` case working, *if* I copy the native files to the `Modules` folder. Then again, I still don't feel it's a proper way for production. We need a way to let the .net runtime to find assemblies from the `Modules\runtimes\{rid}\(tfm}|native` folder (probing assemblies from the `runtimes\{rid}\(tfm}|native` folder works just file out-of-the-box).

**Comment by maliming** [comment]
>  We need a way to let the .net runtime to find assemblies from the Modules\runtimes\{rid}\(tfm}|native folder (probing assemblies from the runtimes\{rid}\(tfm}|native folder works just file out-of-the-box).

This is the responsibility of .NET, please see: 
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.loadfromassemblypath?view=net-5.0
https://www.google.com/search?q=loadfromassemblypath+dependencies

Or maybe you need `yourdll.deps.json` file.

**Comment by hillin** [comment]
> This is the responsibility of .NET, please see:
> https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.loadfromassemblypath?view=net-5.0
> https://www.google.com/search?q=loadfromassemblypath+dependencies

Thanks, I'll definitely look into it later.

> Or maybe you need `yourdll.deps.json` file.

The `.deps.json` file is in the `Modules` folder.


For now as a workaround, we can use the `NativeLibrary` class to intercept the DLL import resolver and provide a custom resolving method:

```c#
internal static class SkiaSharpNativeAssembly
{
    private static bool _isDllImportResolverSet;

    public static void PrepareDllImportResolver()
    {
        if (_isDllImportResolverSet)
        {
            return;
        }

        NativeLibrary.SetDllImportResolver(typeof(SKBitmap).Assembly, NativeLibraryResolver);
        _isDllImportResolverSet = true;
    }

    private static IntPtr NativeLibraryResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
    {
        searchPath = searchPath | DllImportSearchPath.AssemblyDirectory ?? DllImportSearchPath.AssemblyDirectory;

        var runtimeLibraryName = Path.Combine("runtimes", "win-x64", "native", libraryName);
        if (NativeLibrary.TryLoad(runtimeLibraryName, assembly, searchPath, out handle))
        {
            return handle;
        }
        
        return IntPtr.Zero;
    }
}


// and call SkiaSharpNativeAssembly.PrepareDllImportResolver before SkiaSharp is used
```
