### ISSUE TITLE
EventBus bug,can not subscriber EntityCreatedEventData in DistributeEventBus

### ISSUE THREAD

**Issue by SarcoZ** [abpframework/abp#9254]
if i configure AbpDistributedEntityEventOptions like below, i have an entity named MyEntity,when it created,will auto publish a domain event to distribute event bus
```
Configure<AbpDistributedEntityEventOptions>(options =>
            {
                options.AutoEventSelectors.AddAll();     
            });
```
i  defined an event handler
```
public class MyEventHandler : IDistributedEventHandler<EntityCreatedEventData<MyEntity>>, ITransientDependency
{
       public async Task HandleEventAsync(EntityCreatedEventData<MyEntity> eventData)
       {
            
       }
}
```
I use AbpEventBusKafkaModule
when app started,create an entity,an distribute event will published,this worked ok, but my event handler can not get any message
I trace  Volo.Abp.EventBus.Kafka code in KafkaDistributedEventBus.cs,   and find 

 ```
private List<IEventHandlerFactory> GetOrCreateHandlerFactories(Type eventType)
        {
            return HandlerFactories.GetOrAdd(
                eventType,
                type =>
                {
                    //this method get  event name error,if i change it with 
                    var eventName = EventNameAttribute.GetNameOrDefault(type);
                   //var eventName = "Volo.Abp.Domain.Entities.Events.Distributed.EntityEto.Created";
                    EventTypes[eventName] = type;
                    return new List<IEventHandlerFactory>();
                }
            );
        }
```

I find that eventName get error,if use "Volo.Abp.Domain.Entities.Events.Distributed.EntityEto.Created", that worked correct,because EntityCreatedEventData<MyEntity> is an generic, EventNameAttribute.GetNameOrDefault(type) worked uncorrect, i think this is an bug

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#pre-defined-events
