### ISSUE TITLE
extending IdentityUserDto has no effect on swagger generation

### ISSUE THREAD

**Issue by lgadola** [abpframework/abp#9257]
**abp** 4.3.2
Angular
EF Core

I extended IdentityUser with a custom property. This shows automatically in the UI.
But extending IdentityUserDto seems to have no effect on the swagger definition (it still appears under extraProperties)

`   public static class ResODtoExtensions
    {
        private static readonly OneTimeRunner OneTimeRunner = new OneTimeRunner();

        public static void Configure()
        {
            OneTimeRunner.Run(() =>
            {
                ObjectExtensionManager.Instance
                   .AddOrUpdateProperty<IdentityUserDto, string>("SocialSecurityNumber");
            });
        }
    }`

**Comment by maliming** [comment]
hi 

Because they are dynamic, so it will not affect swagger.
