### ISSUE TITLE
Misbehaviours and security issues related to Volo.Abp.Account

### ISSUE THREAD

**Issue by mikando** [abpframework/abp#9263]
### GitHub Issues

ABP Framework Version: 4.3.2
ABP UI : Core MVC
Database provider : EF Core

Hi guys.

  I've just created blank MVC project and did some user testing in profile editing page. I'm able to change my username with another existing user's name and be able to change it to an invalid format. Here I've recorded a video for reproduce a problem.

https://user-images.githubusercontent.com/6908465/121288849-99b26180-c916-11eb-87de-e5df3d46a7dd.mp4

**Comment by maliming** [comment]
hi 

https://github.com/abpframework/abp/issues/8740#issuecomment-825637586
