### ISSUE TITLE
add-migration in DbMigrations do not create table when i add entity in EntityFrameworkCore

### ISSUE THREAD

**Issue by AchaInChina** [abpframework/abp#927]
- 1 create project with ASP.NET Core Mvc Application

- 2 add a entity driver from AuditedAggregateRoot like this 

- `[Table("TaskInfo")]

    public class JobInfo: AuditedAggregateRoot<int>
    {
        [Required, StringLength(128), Display(Name="任务组")]
        public string JobGourp { get; set; }
        [Required, StringLength(64), Display(Name = "任务描述")]
        public string JobDescription { get; set; }
        [Required, StringLength(64), Display(Name = "任务名")]
        public string JobName { get; set; }
        [Required, StringLength(64),Display(Name = "Cron表达式")]
        public string CronExpress { get; set; }
        [Display(Name = "开始时间")]
        public DateTime StarTime { get; set; }
        [Display(Name = "结束时间")]
        public DateTime EndTime { get; set; }
        [Display(Name = "下次运行时间")]
        public DateTime NextTime { get; set; }
    }`

- 3 add DbSet int EntityFrameworkCore XXXDbContext like this 

- `public DbSet<JobInfo> JobInfos { get; set; }`

- 4 open powershell and run command : add-migration,under the DbMigrations  

i follow the doc as above, but i can not find the table which name 'TaskInfo' when check the migration file.

- 5 so i have add a factory in EntityFrameworkCore driver from IDesignTimeDbContextFactory,
open powershell and run command : add-migration,under the EntityFrameworkCore ,this time can see the table 'TaskInfo'

why? is there something wrong with what i do?

**Comment by maliming** [comment]
@AchaInChina 
Configure your own tables/entities inside here:
`YourDbContextModelCreatingExtensions `class `ConfigureYour(this ModelBuilder builder) `method.

**Comment by AchaInChina** [comment]
> @AchaInChina
> Configure your own tables/entities inside here:
> `YourDbContextModelCreatingExtensions `class `ConfigureYour(this ModelBuilder builder) `method.

i have add the code like this 

- builder.Entity<JobInfo>(b =>
            {
                b.ToTable(PlatformConsts.DbTablePrefix + "JobInfo", PlatformConsts.DbSchema);
            });

but it is wrong when i run the command Add-Migration, log is :  The property 'JobInfo.ExtraProperties' could not be mapped, because it is of type 'Dictionary<string, object>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

**Comment by maliming** [comment]
Add `b.ConfigureExtraProperties();`

**Comment by AchaInChina** [comment]
> Add `b.ConfigureExtraProperties();`

it work well, thanks.
熊蝶，厉害呀。
