### ISSUE TITLE
How to implement OrganizationUnit MultiTenant

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#9278]
![image](https://user-images.githubusercontent.com/24971860/121328087-9cc54600-c946-11eb-8701-b753544d6049.png)

i saw this info from document, however it looks does not work for `OrganizationUnitManager.CreateAsync( ... )`

Do i have to use `TryToSetTenantId(organizationUnit)` in `OrganizationUnitAppService`?

![image](https://user-images.githubusercontent.com/24971860/121329073-73f18080-c947-11eb-95dd-6bf7e518badb.png)

**Comment by maliming** [comment]
You can new the **OrganizationUnit** entity manually. 

https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/OrganizationUnit.cs#L56
