### ISSUE TITLE
ABP return 500 instead of 401 status code

### ISSUE THREAD

**Issue by sachindratomer** [abpframework/abp#9283]
I am also facing the same issues - https://github.com/abpframework/abp/issues/7924, this issue is coming when you are running applications out of the development environment.  The Issue is reproducible in Debugging mode also if you change ASPNETCORE_ENVIRONMENT environment variable to something else in place of development.  Its not coming with .Net Core webapi.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/issues/7924#issuecomment-790196262
https://github.com/abpframework/abp/issues/7924#issuecomment-797203135

**Comment by Loongle** [comment]
i think you remove ` app.UseErrorPage();`, and then it's noraml 😂
