### ISSUE TITLE
Forms module feature

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#9285]
There may be forms that are constantly used. It would be nice if there was a feature to 'save the form as a template' (for later use).

**Comment by maliming** [comment]
We have a pro module of forms.

https://commercial.abp.io/modules/Volo.Forms

**Comment by ebicoglu** [comment]
this is already implemented in a paid module..

**Comment by recruitans** [comment]
I said it as a feature that can be added to the Volo.Forms module.
