### ISSUE TITLE
Elsa Workflow problem with versioned api explorer

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#9298]
I've created an demo app with the Elsa workflow, which basically works. However, when I enable versioned api explorer, our own APIs disappear (you can see /swagger).

https://github.com/abpframework/abp-samples/blob/9ad8d9998f7d09af678491aff5e44eb07eaba4b9/ElsaDemo/src/ElsaDemo.Web/ElsaDemoWebModule.cs#L152-L156

`AddElsaApiEndpoints` method is a copy of  `services.AddElsaApiEndpoints();` extension method. I copied it to explore the problem.

Can you work on that to understand the root problem and what we can do about that.

Branch: https://github.com/abpframework/abp-samples/tree/elsa-demo

**Comment by maliming** [comment]
`UseApiBehavior = false` will resolve this.
https://github.com/microsoft/aspnet-api-versioning/wiki/API-Versioning-Options#use-api-behavior
https://github.com/abpframework/abp-samples/commit/bdf5e6e2a43587118277e08aa263933e98a64ac9
