### ISSUE TITLE
After finishing language text editing, the grid is reloading at page 1

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#9313]
4.3.0 / Angular

Let's say I have a lot of localizations and edit something at page 6 (UserName):

![image](https://user-images.githubusercontent.com/6149843/121941749-52820180-cd58-11eb-9a36-1db032487249.png)

After editing is done, the grid is reloading to page 1, which is not very user-friendly: I'd prefer to stay at the same page and see the record I've just edited. Or sort the records by modification date in descending order - this way my record will be at the top of the grid and I won't need to look for it.

**Comment by ebicoglu** [comment]
thanks @alexandis this might be annoying

**Comment by ebicoglu** [comment]
closing this issue since this is related to commercial version

**Comment by alexandis** [comment]
Ok then - moved the question to [Bugs & Issues v4.3.X](https://support.abp.io/QA/Questions/1126/Bugs--Issues-v43X#answer-1c1f1c18-b1c3-6d35-fcd4-39fd20e3c84c)
Otherwise please inform where I can report commercial ABP bugs like that.
