### ISSUE TITLE
Some language texts are not saved (if previously absent)

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#9314]
4.3.0 / Angular

Please have a look - how to reproduce.

Step 1 - Put filters:

![image](https://user-images.githubusercontent.com/6149843/121949706-71d15c80-cd61-11eb-9725-1950a621693e.png)

Step 2 - Try to add translation to French:

![image](https://user-images.githubusercontent.com/6149843/121949765-87468680-cd61-11eb-9d66-572d8748c378.png)

Press "Save":

![image](https://user-images.githubusercontent.com/6149843/121949995-d096d600-cd61-11eb-9407-1468dae00731.png)

Step 3 - After the grid is reloaded, you can see the translation has not been added:

![image](https://user-images.githubusercontent.com/6149843/121950074-e2787900-cd61-11eb-8216-d419f8e9a18d.png)

**Comment by mehmet-erim** [comment]
Hi @alexandis 

It is related to a commercial module. I created an internal issue, closing this one.
We'll fix the problem, thanks for the reporting.
