### ISSUE TITLE
Validation localization issue.

### ISSUE THREAD

**Issue by dangminhbk** [abpframework/abp#9318]
* Abp version: 4.3.0
* UI: MVC

How can I localization field name in validation's message? It seems that I have to put localized text in the .json file, with the key match the field name. The problem is, if the field name is duplicate in many entities, we cannot distinguish between them to localize these text. The problem is not present in form's label, since we can specify `label` attribute of `abp-input`.

**Comment by ebicoglu** [comment]
Localization Resource is used for that purpose. You can create multiple localization resources (in your modules) and you can get the text from a Localization Resource.
See these docs:
* https://docs.abp.io/en/abp/latest/Localization
* https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Localization

**Comment by dangminhbk** [comment]
> Localization Resource is used for that purpose. You can create multiple localization resources (in your modules) and you can get the text from a Localization Resource.
> See these docs:
> 
> * https://docs.abp.io/en/abp/latest/Localization
> * https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Localization

@ebicoglu according to this document, https://docs.abp.io/en/abp/latest/UI/AspNetCore/Tag-Helpers/Form-elements#label-localization-1 , have to use [DisplayName] attribute to archive localize error message.
