### ISSUE TITLE
logout error code 204

### ISSUE THREAD

**Issue by holyrong** [abpframework/abp#9320]
*  **ABP Framework version**：4.3.2  
*  **User Interface** type (Vue) 
* Your database provider(EF Core)

when call "/api/account/logout"，I've encountered the error:"204 No Content" twice。And then I used the old token , it still got data from proteced apis。

![image](https://user-images.githubusercontent.com/8318475/122021722-857bd200-cdf8-11eb-8ce4-f4d4e1a665fc.png)

**Comment by maliming** [comment]
This` /api/account/logout` endpoint it not related to `token`

**Comment by ebicoglu** [comment]
account/logout is for MVC , normally you don't need to call logout, just delete the token stored in the browser cache.
see how it logs out in the demo website (angular) https://commercial.abp.io/demo

**Comment by gdlcf88** [comment]
Code 204 means success with no content return.

**Comment by holyrong** [comment]
@maliming how can i logout the token?which endpoint can we call for this requirement?
we've tried many ways(oidc-client with implicit，password flow),but the token always be effective for calling protected apis.
if not resolve the token ,the sso application can't work normally.

**Comment by holyrong** [comment]
@gdlcf88 
 even so, the token is still works。I think this is real problem。
We only received 204 from "api/account/logout",or received 302 from "account/logout",**but the old token still works**。
**It means wen can't logout from IDS application**。

**Comment by holyrong** [comment]
@gdlcf88 
We only received 204 from "api/account/logout",or received 302 from "account/logout",
 even so, **the token is still works**。I think this is real problem。
**It means wen can't logout from IDS application**。

**Comment by liquehuo** [comment]
> @gdlcf88 We only received 204 from "api/account/logout",or received 302 from "account/logout", even so, **the token is still works**。I think this is real problem。 **It means wen can't logout from IDS application**。
Did you solve it?
