### ISSUE TITLE
Implement a new user(tenant-admin) registration endpoint

### ISSUE THREAD

**Issue by mugambiwarwema** [abpframework/abp#9329]
I have downloaded the abp.io start-up template with no-tier.

I wish to implement an endpoint that allows a new user to register as a new tenant(admin) to the system.

However, the only implementation I see is through the end-point below

> POST ​/api​/multi-tenancy​/tenants

Also, this endpoint is protected by the permissions highlighted below at class level and method level respectively.

> TenantManagementPermissions.Tenants.Default and TenantManagementPermissions.Tenants.Create

I have tried disabling these permissions via 

`

        public override void Define(IPermissionDefinitionContext context)
        {
            var myGroup = context.AddGroup(XXXXPermissions.GroupName);

            context
                .GetPermissionOrNull(TenantManagementPermissions.Tenants.Default)
                .IsEnabled = false;
            context
                .GetPermissionOrNull(TenantManagementPermissions.Tenants.Create)
                .IsEnabled = false;
        }

`

When I send a post request to the endpoint below, I an Unauthorized exception is thrown. 

Q1: Is this the right way to go about it?
Q2: If so how can I get to disable the Authorization. If not how can I go about implementing this.

**Comment by maliming** [comment]
hi

You should implement some new APIs and application services. 
`POST ​/api​/multi-tenancy​/tenants` belong to the tenant module.
