### ISSUE TITLE
[Question] How to save redis string/list type rather than redis hash type data with IDistributedCache?

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#9333]
ABP version 
4.3.2
Hi, community!
I want to set string type value to redis like `cachekey: '{'helll':'123'} '` (just string not hash)
Just serialize my object to json and save json  without default object like `absexp: xx,sldexp: xx, data: xxx` .
Like `StackExchangeRedis` 's `SetString()`method
So what I should do? 
I can't find any infos from abp docs.

**Comment by ebicoglu** [comment]
There's this `IDistributedCache<TCacheItem, TCacheKey>`
You can inject `IDistributedCache<YourObject, string>` which has string value type

**Comment by trickyrat** [comment]
@ebicoglu thanks for your advices, but I want to save my object to redis string type not redis hash. I followed your advice, and it's same value. `IDistributedCache<CacheItem, string>` just set cache key to string type, not obejct to redis string.
![image](https://user-images.githubusercontent.com/19605145/122181281-cee12580-cebb-11eb-9d7a-489075eae69f.png)
![image](https://user-images.githubusercontent.com/19605145/122181319-d7d1f700-cebb-11eb-9b94-06f168bb038a.png)

![image](https://user-images.githubusercontent.com/19605145/122181084-9c372d00-cebb-11eb-9fe3-88d837dfaba5.png)
I want like
![image](https://user-images.githubusercontent.com/19605145/122181677-297a8180-cebc-11eb-858d-c0911a74f0a7.png)

**Comment by AlexMethod** [comment]
Im struggling with the same problem. What was the solution? I didn't catch it.
