### ISSUE TITLE
iOS (Apple devices) Login Problems - Missing Permissions - Blazor WebAssembly, Tiered ABP Project

### ISSUE THREAD

**Issue by dmtuan** [abpframework/abp#9334]
* **ABP Framework version**: 4.3.2
* Your **User Interface** type: Blazor WebAssembly
* Your database provider: SQL, EF Core

Hello, I have a **Tiered Blazor WA project** deployed on Azure. It works in Chrome and Edge browser. It **doesn't work on iOS (Apple) devices**. I tested it on iPhone and iPad (updated to latest) - when I log in, I see myself logged -> username is visible in top right corner, but **I don't have any permissions of the logged user**. In my case, I hide navigation items and only show them to users with permissions.

I searched around and thought it might be related to the **samesite=none** problem:
[https://community.abp.io/articles/patch-for-chrome-login-issue-identityserver4-samesite-cookie-problem-weypwp3n](url)
This didn't fix the problem. I applied the changes to Api.Host project and IdentityServer project, but no change.

After reaching to @leonkosak, he mentioned it might be a problem related to **ValidIssuers**:
[https://github.com/abpframework/abp/issues/5589](url)
I applied these changes to Api.Host project and it didn't help either.

This is a screenshot from Chrome browser, where I can see the **JWT token is present**:
![screen1](https://user-images.githubusercontent.com/7838796/122172180-cd463c00-ce80-11eb-8fe3-b6646c70e879.png)

And this is a screenshot from Safari browser, where I can see the **JWT token is not there**:
![screen2](https://user-images.githubusercontent.com/7838796/122172307-ec44ce00-ce80-11eb-817a-3ab35dbd1b77.png)

A curious thing is that if the Blazor client didn't receive the JWT token, how can the user be logged in (I can still see the username top right, it's just that the logged user doesn't have any permissions he should have. I also tried to go to the pages hidden behind permissions and the user cannot access them either).

### List of browsers where it was tested
Windows
- Google Chrome - yes
- Microsoft Edge (Chromium) - yes
- Mozilla Firefox - yes
- Brave browser (Chromium) - no

Android
- Google Chrome - yes
- Microsoft Edge (Chromium) - yes
- Mozilla Firefox - yes

iPadOS / iOS
- Safari - no
- Google Chrome - no
- Microsoft Edge - no
- Mozilla Firefox - no

Have anyone else experienced the same problem and knows how to deal with this problem, please? Or does anyone know what to do? Any help would be greatly appreciated. Thank you in advance.

**Comment by maliming** [comment]
> Brave browser (Chromium) - no

What's the version? I can test it.

**Comment by dmtuan** [comment]
@maliming thank you for getting back to me. 

I have tested it on Brave browser, version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)

Here's a tester account:
Login: tester1
Password: P@ssword789

When you login in Brave, you will only have Home in navigation. If you login in Chrome, you will have other menu items.

**Comment by maliming** [comment]
What's your website url?

**Comment by dmtuan** [comment]
Sorry ^^.. silly me.

https://uniparking.azurewebsites.net/

**Comment by dmtuan** [comment]
@maliming I also notice that currentUser in application-configuration request is not set right:
![image](https://user-images.githubusercontent.com/7838796/122188687-7cd6da80-ce90-11eb-9c8f-e58b5433ff25.png)

Anyway, this all comes back to the main problem - blazor client is **not processing or not saving JWT token after logging in**. And subsequently there is no auth token to attach to application-configuration request.

**Comment by maliming** [comment]
hi

The Brave browser blocks third-party cookies by default.

![image](https://user-images.githubusercontent.com/6908465/122190170-2b484300-cec4-11eb-804b-f34083dea32c.png)

**Comment by maliming** [comment]
> iPadOS / iOS

I don't know how to debug it. There is no problem with your cookies.

**Comment by dmtuan** [comment]
It works!

I tried unblocking third-party cookies in iPadOS and iOS and it finally works. Thank you for your answer which lead me to the resolution. (For example following this guide: https://akohubteam.medium.com/how-to-enable-third-party-cookies-on-your-browsers-f9a8143b8cc5). It's important to **uncheck both Prevent Cross-Site Tracking and Block All Cookies** (Block All Cookies will be uncheck by default thoug).

However, I am wondering if there's a way to make it work even if users have Prevent Cross-Site Tracking checked. I don't know if I can force half the users go into Settings and change their Safari settings.

**Comment by maliming** [comment]
>  if there's a way to make it work even if users have Prevent Cross-Site Tracking checked

If someone can do it, Apple will reward him with a million dollars. 😉
