### ISSUE TITLE
External login claims

### ISSUE THREAD

**Issue by ArneCools** [abpframework/abp#9345]
* 4.3
* Blazor server
* Sql Server

When logging in with an external service. How do I add custom claims to the user logging in. 
My external login provides:
- http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname & 
- http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname 
But they are not saved to the database. How do I make sure abp Identity recognizes these claims?

**Comment by gterdem** [comment]
You need to request these claims at openid connect configuration in your module startup and map these claims. 

If you want to persist these claims in your database, then you need to override user creation to add these new claims. https://github.com/abpframework/abp/blob/b2324175cace5fb0f1385e49414f339931f8918f/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L269

**Comment by ArneCools** [comment]
Hi, thank you for responding.

I'm using saml2 adfs with sustainsys for my external login. 
When I call
`await _signInManager.GetExternalLoginInfoAsync();`
my claims are present. Do I still need to map these claims? and how exactly?

How do I override the Login.cshtml.cs class? Do I have to copy the entire "account module" and change references to that project instead of the NuGet package? Or is there are more elegant way?

**Comment by gterdem** [comment]
> When I call
> await _signInManager.GetExternalLoginInfoAsync();
> my claims are present. Do I still need to map these claims? and how exactly?

It seems they are already mapped. If you are using openid connect, claim mapping should look like:
https://github.com/abpframework/abp-samples/blob/b24f9a46f48a9e8bfdf5a275b93a6521e534c433/Authentication-Customization/src/Acme.BookStore.Web/BookStoreWebModule.cs#L134
Mapping `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` to `sub` claim.

> How do I override the Login.cshtml.cs class? Do I have to copy the entire "account module" and change references to that project instead of the NuGet package? Or is there are more elegant way?

Here is a community article about [how to customize login page for mvc/razor applications](https://community.abp.io/articles/how-to-customize-the-login-page-for-mvc-razor-page-applications-9a40f3cd). You can find a link to sample application related with it.

**Comment by ArneCools** [comment]
Thanks so much. That solved my problem!
