### ISSUE TITLE
Blazor "Refused to load the script" error

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#9348]
After  updating Visual Studio (v 16.10.2 and on the preview version 16.11.0 preview 2.0) I noticed the following error in the browser console. This error **might be older and unrelated** to the update but its around the time I noticed it first.

> Refused to load the script 'https://localhost:44366/_framework/aspnetcore-browser-refresh.js'
because it violates the following Content Security Policy directive: "script-src 'sha256-fa5rxHhZ799izGRP38+h4ud5QXNT0SFaFlh4eqDumBI='". 
Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

It doesn´t seem to be affecting anything but I´m reporting it anyways since nobody has reported it and because I found some suggested [`<meta` ](https://javascript-help.li/google-chrome-refused-to-load-the-script-error-in-angular-application/) adds (though they did not work for me).

So maybe something needs to be added to index.html? I tried to add the file as suggested [here](https://github.com/dotnet/runtime/issues/51126#issuecomment-817134047) but that didn't change anything.

This [seems to be connected to hot reload](https://stackoverflow.com/a/67717809/1187583) but I don´t know how that relates to me since I´m not trying to use it. 

When first running up the app and not being logged in I get
![image](https://user-images.githubusercontent.com/2386572/122233399-8e79ab80-ceab-11eb-8ad9-d5a2a5a7a63b.png)

And then after logging in I get this

![image](https://user-images.githubusercontent.com/2386572/122232928-27f48d80-ceab-11eb-80f2-294e85532740.png)

This error is shown both in MS Edge and Firefox so not just a Chrome error.

**If** this is not related to updating VS then **I have no idea** what might have caused this or when it started so all suggestions appreciated.

There is some time since 

- Your **ABP Framework version**: 4.3.2
- Your **User Interface** type: Blazor
- Your database provider: EF Core

**Comment by sturlath** [comment]
This is still happening in version 4.4.0 and I still have no idea what might be causing it. I have tried all the the VS versions (2019,2019 prev, 2022 v3) and still seeing it.

It only happens after I log in if that is something...

**Comment by maliming** [comment]
How to reproduce this using the template project?

**Comment by sturlath** [comment]
Ok I managed to get more information on this error by reading the [docks ](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-5.0#blazor-webassembly-1) again where it says "... the following browser tools console error **reports** the hash for a **required script** not covered by the policy:" 

Now (after adding the meta tag) I get the following errors in the console

![image](https://user-images.githubusercontent.com/2386572/129210018-cb58b2b9-219c-4845-8f66-26f6e6851f5a.png)

and

![image](https://user-images.githubusercontent.com/2386572/129210117-113b58da-7af9-4c0b-90fb-6962b8fda062.png)

Anything you can gather from this extra info @maliming?

**Here for searchability** 

1.
```Refused to connect to 'https://localhost:44366/.well-known/openid-configuration' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.```

2.
```
Refused to load the script 'https://cdn.jsdelivr.net/npm/chart.js@2.8.0' because it violates the following 
Content Security Policy directive: "script-src https://stackpath.bootstrapcdn.com/
 'self'
 'sha256-v8v3RKRPmN4odZ1CWM5gw80QKPCCWMcpNeOmimNL2AA='
'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.```
```

3.
```
dotnet.5.0.9.js:1 Refused to connect to 'https://localhost:44353/api/abp/api-definition' because it violates the following
 Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by maliming** [comment]
How to reproduce this using the template project?

What are the steps?

**Comment by sturlath** [comment]
Sorry no steps... there is no way to replicate this at the moment in another project. 

I´ll update this when I have figured something out. I was hoping the errors would give somebody hints on what might be causing this.

**Comment by sifaqes** [comment]
I have the same problem, when I implemented identity security in my Blazor WebAssembly .Net7 app. This message appears when I enter any route except index.razor

![image](https://github.com/abpframework/abp/assets/64240372/ac3d5a59-5d75-433d-9f1a-6574b36c0b60)

**Comment by EngincanV** [comment]
> I have the same problem, when I implemented identity security in my Blazor WebAssembly .Net7 app. This message appears when I enter any route except index.razor
> 
> ![image](https://private-user-images.githubusercontent.com/64240372/308350694-ac3d5a59-5d75-433d-9f1a-6574b36c0b60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDUyMjEsIm5iZiI6MTcwOTEwNDkyMSwicGF0aCI6Ii82NDI0MDM3Mi8zMDgzNTA2OTQtYWMzZDVhNTktNWQ3NS00MzNkLTlmMWEtNjU3NGIzNmMwYjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA3MjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OTEyMDY0NGIwN2MzMmY0OTQzMzI1MzQxNzkzYzc0MzU4MTAwOGY5OTY0OTY1MTllZTY3NmYzMDMxOWU5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4KY4j7njA_XSCwS0WT9X3o8cpDX3vtGIOnus54YK3R0)

It seems you did not register the related services for radzen components and therefore it throws "InvalidOperationException: ... **There is no registered service of type 'Radzen.DialogService'**". 

So, please ensure you have registered the services by calling the `AddRadzenComponents` in the module class (or Program.cs):

```csharp
builder.Services.AddRadzenComponents();
```

It's not related to ABP Framework, please refer to https://blazor.radzen.com/get-started
