### ISSUE TITLE
How to extending IdentityUser entity with custom properties in a module template

### ISSUE THREAD

**Issue by luochaorobert** [abpframework/abp#9355]
* **ABP Framework version 4.3.2**.
* User Interface type: MVC
* database provider: EF Core

At present, the examples in the official document are all implemented in the application template. I can implement them in my own project according to the document operation, but I don't know how to implement them in the module template. 
Unlike the application template, there is no `DbMigrations` project and `DbMigrator` project in the module template, and migration can only be carried out in the host project.
Referring to the practice in the application template, I add-migration in the `HttpApi.Host` project in my module project, but the migration file is empty:

```
using Microsoft.EntityFrameworkCore.Migrations;

namespace xxxx.xxxx.Migrations
{
    public partial class Added_UnionId_To_Users : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
```

Please help me, thank you very much!

**Comment by maliming** [comment]
You can do this in these projects.  Migrations in `HttpApi.Host` that only for your module. 

![image](https://user-images.githubusercontent.com/6908465/122359824-79bf1580-cf88-11eb-8e06-82f458eec370.png)

**Comment by luochaorobert** [comment]
> You can do this in these projects. Migrations in `HttpApi.Host` that only for your module.
> 
> ![image](https://user-images.githubusercontent.com/6908465/122359824-79bf1580-cf88-11eb-8e06-82f458eec370.png)

You mean I should only migrate in these projects that you have framed ？
