### ISSUE TITLE
API parameter default value null cannot work

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#9359]
ABP: 3.3.2
User Interface: MVC
Database: EF core

* Steps needed to **reproduce** the problem.

I created an interface service with a default value parameter as below:
![image](https://user-images.githubusercontent.com/74571567/122380666-b09e2700-cf9a-11eb-92f8-c56eb8a8ecc7.png)

Then I call this API from the javascript level:
![image](https://user-images.githubusercontent.com/74571567/122380901-ecd18780-cf9a-11eb-92cf-533e4ffe5be2.png)

If the parameter is null, it will throw an exception error:
![image](https://user-images.githubusercontent.com/74571567/122381055-14c0eb00-cf9b-11eb-96cd-f4325fa1c2cb.png)

I have checked the generated javascript API content:
![image](https://user-images.githubusercontent.com/74571567/122381194-3b7f2180-cf9b-11eb-9fca-82dfc925dc5f.png)

How we can support the default value design?
Thanks.

**Comment by maliming** [comment]
> How we can support the default value design?

You can try to use input class.

```cs
public class MyMethodInput
{
     public Guid? ParentId { get; set; }
}
```

**Comment by jack-gaojz** [comment]
> > How we can support the default value design?
> 
> You can try to use input class.
> 
> ```cs
> public class MyMethodInput
> {
>      public Guid? ParentId { get; set; }
> }
> ```

Thanks so much. This solution works fine.
