### ISSUE TITLE
How to handle tenantId from query parameters on landing pages

### ISSUE THREAD

**Issue by bnymncoskuner** [abpframework/abp#9360]
When a user enters the application with a link containing `tenantId` (like a reset-password link, email-confirmation link or any other deeplink), we should change the current tenant to the given `tenantId` to provide a continuous user experience. Now, when a user clicks on a reset-password link with `tenantId`, they change their password and navigate to the login page. If they want to login to that specific tenant, they have to choose it again from tenant-box. However, they started their journey off with a given tenant. They should not be forced to choose it again.

**Comment by hikalkan** [comment]
The page gets and processes the querystring must set the cookie (typically for MVC apps). For angular, it should set the local storage and send that tenantId in the header for next requests.

So, [here](https://github.com/abpframework/abp/blob/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account/ResetPassword.cshtml.cs#L64), we should set the tenant cookie first. Please also check if there are other places like that.
