### ISSUE TITLE
Abp-Cli: Console-Template fails with Http Status 500 "'<' is an invalid start of a value."

### ISSUE THREAD

**Issue by DanzigGLT** [abpframework/abp#9365]
Version: ABP-Cli 4.3.3 (actual stable) 

`abp new testproject -t console` gives Http 500

Exception-Message:
[error_abp_4_3_3_cli_console.txt](https://github.com/abpframework/abp/files/6671203/error_abp_4_3_3_cli_console.txt)

**Comment by maliming** [comment]
We are checking.

**Comment by maliming** [comment]
See #9368
