### ISSUE TITLE
Cascading entities are not deleted when they have composite keys.

### ISSUE THREAD

**Issue by evictorel** [abpframework/abp#9366]
* .NET 5.*
* ABP Framework **4.3.2**.
* EF Core
* PostgreSQL
* I have three entities, A, B, C with the following structure:

```
public class A : Entity<Guid>,
        IHasDeletionTime
{
        public ICollection<B> As { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletionTime { get; set; }
}
```

```
public class B : Entity,
    IHasDeletionTime
{
    public DateTime Date { get; set; }
    public Guid Id { get; set; }
    public Guid? AId { get; set; }
    [CanBeNull] public A A { get; set; }
    public IList<C> Cs { get; set; }
    public bool IsDeleted { get; set; }
    public DateTime? DeletionTime { get; set; }

    protected B()
    {
    }

    public B(DateTime date, Guid id)
    {
        Date = date;
        Id = id;
    }

    public override object[] GetKeys()
    {
        return new object[] {Date, Id};
    }
}
```

```
public class C : Entity,
    IHasDeletionTime
{
    public DateTime BDate { get; set; }
    public Guid BId { get; set; }
    public long Id { get; set; }
    public B B { get; set; }
    public bool IsDeleted { get; set; }
    public DateTime? DeletionTime { get; set; }

    public override object[] GetKeys()
    {
        return new object[] {BDate, BId, Id};
    }
}
```

```
builder.Entity<A>(b =>
{
    b.ToTable(options.TablePrefix + "A", options.Schema);
    b.ConfigureByConvention();
    b.HasMany(m => m.Bs)
        .WithOne(m => m.A)
        .HasForeignKey(m => m.AId)
        .OnDelete(DeleteBehavior.Cascade);
});
builder.Entity<B>(b =>
{
    b.ToTable(options.TablePrefix + "B", options.Schema);
    b.ConfigureByConvention();
    b.HasKey(m => new
    {
        m.Date,
        m.Id
    });
});
builder.Entity<C>(b =>
{
    b.ToTable(options.TablePrefix + "C", options.Schema);
    b.ConfigureByConvention();
    b.HasKey(m => new
    {
        m.BDate,
        m.BId,
        m.Id
    });
    b.HasOne(m => m.B)
        .WithMany(m => m.Cs)
        .HasForeignKey(m => new
        {
            m.BDate,
            m.BId
        }).OnDelete(DeleteBehavior.Cascade);
});

```

If i run the following, the cascading delete works fine, marking all three entities as IsDeleted.

```
var a = ..
Repository.DeleteAsync(a)

```

On the other hand, in the other case, if I remove B, this is IsDeleted, but not C. AId is null, so there are no problems with the constraints between A and B.

```
var b = ...
Repository.DeleteAsync(b)

```

At first I thought it was a configuration issue, but if I remove the IHasDeletionTime interface from entities, cascade delete works fine. Could it be for .NET 5?

I will try to create a project to simulate this, but first I wanted to see if someone had the same problem.

Thanks.

**Comment by youssefDawood** [comment]
Me too, I have the same problem exactly after they did the last update.

**Comment by maliming** [comment]
> I will try to create a project to simulate this

Please provide a project.

**Comment by evictorel** [comment]
> > I will try to create a project to simulate this
> 
> Please provide a project.

[Example](https://github.com/evictorel/Volo.Abp.SoftDelete)

At first I thought it was a problem to use composite keys, but then with entity D the same problem arises.

And I don't know if it is correct to use "UsingDbContext" to test these cases (AAppService_Tests).

Thanks

**Comment by maliming** [comment]
hi @evictorel 
You can try to manually delete the associated entities. And cancel the cascade delete for the soft delete entities.

![image](https://user-images.githubusercontent.com/6908465/123563559-028b4c00-d7e8-11eb-8849-0bbd66a15fba.png)

**Comment by youssefDawood** [comment]
I'm also having the same problem, I'm used to 'cascade' to delete when deleting the related asset.

**Comment by evictorel** [comment]
> hi @evictorel
> You can try to manually delete the associated entities. And cancel the cascade delete for the soft delete entities.
> 
> ![image](https://user-images.githubusercontent.com/6908465/123563559-028b4c00-d7e8-11eb-8849-0bbd66a15fba.png)

Sorry for the delay. Yes, I currently do this for all sub-entities.

Taking a closer look at the [AbpDbContext](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs) code, and another issue you mentioned (I can't remember it at the moment) I think it is a current limitation of the framework. Correct?

Anything, I can override AbpDbContext so that it also removes child entities based on ICollection, IList, etc.

**Comment by maliming** [comment]
We can think of this as a conflict between EF Core and soft delete design.
