### ISSUE TITLE
ABP project don't run in first time using

### ISSUE THREAD

**Issue by birdy89** [abpframework/abp#9374]
I created a new project by ABP CLI. When I received the project, I changed connection string and add a new migration to create database for fisrt time using. After, I run the project but it didn't run and here is the thing that I recevied 
![Screenshot (1)](https://user-images.githubusercontent.com/82010847/122635587-0267be00-d10f-11eb-8bd5-b59da7bff2bf.png)
Can you help me? Thank.

**Comment by realLiangshiwei** [comment]
I think there is no relation to ABP. please read the document: https://docs.abp.io/en/abp/latest/Getting-Started
