### ISSUE TITLE
Return Blazor client from HttpApi.Host

### ISSUE THREAD

**Issue by dmtuan** [abpframework/abp#9375]
* **ABP Framework version**: 4.3.2
* **User Interface**: Blazor WebAssembly
* Your database provider : EF Core

Currently there is no option when you create a new ABP framework project to have a **Blazor WA client to be returned by HttpApi.Host project**. The Blazor client is returned in a standalone project. This configuration doesn't make sense to me for small projects, where I'd like to have all running in 1 project. 

Basically, what I want to have is the exact same configuration when you create a Blazor WebAssembly project in Visual Studio and you check ASP.NET Core Hosted:
![image](https://user-images.githubusercontent.com/7838796/122635691-afc5dc00-d0e5-11eb-8bec-8e2fd4ee7ceb.png)

You end up with a WebApp.Client project, which holds the Blazor client, and WebApp.Server project which holds the API and also returns the Blazor client.

I think you could consider adding this configuration be one of the Blazor WebAssembly starting ABP templates. Thanks.

**Comment by realLiangshiwei** [comment]
Thanks, but we don't have a plan to do this.
