### ISSUE TITLE
Nuget version error

### ISSUE THREAD

**Issue by Jesn** [abpframework/abp#938]
from abp.io create new project ,the nuget package version is 0.16  ,but nuget.org  latest version: 0.15.0

**Comment by hikalkan** [comment]
Thanks for reporting. Will check & fix this immediately.

**Comment by maliming** [comment]
related: https://github.com/abpframework/abp/commit/3d042733991cea2016eb3b49508fcd5421d10092#commitcomment-32981276

**Comment by hikalkan** [comment]
Temporarily fixed.

**Comment by hikalkan** [comment]
It is getting the version from master, but must get from the latest release.

**Comment by Jesn** [comment]
thx, ti's alright now

**Comment by hikalkan** [comment]
I reopened because this was a temporary fix. @yekalkan will fix it.
