### ISSUE TITLE
How to get a entity from another module in solution project

### ISSUE THREAD

**Issue by nguyenquanghuyit** [abpframework/abp#9386]
In my solution, there're 3 module project: A, B and C.

I used linq cmd to get an entity from B module project into A module project, but could not. Please show me how to get:

In my code: 
(await GetDbContextAsync()).xxxx
xxxx: is an entity that I want to get

**Comment by realLiangshiwei** [comment]
You can reference module B in A and then inject the repository. just like the `Account` and `Identity` module https://github.com/abpframework/abp/blob/0033873178b3bc4e6ea9dcaae119d2492e28ca58/modules/account/src/Volo.Abp.Account.Application/Volo.Abp.Account.Application.csproj#L22
