### ISSUE TITLE
DatabaseApiFactory Create IDatabaseApi

### ISSUE THREAD

**Issue by XuJin186** [abpframework/abp#9387]
* Your **ABP Framework version**. 
* 4.3.2
* Your **User Interface** type (Angular/MVC/React... etc.)  
* none
* Your database provider(EF Core/MongoDB)  
* EF Core
* Exception message and **stack trace** if available (check the logs).
* none
* Steps needed to **reproduce** the problem.
* none

The Volo. Abp. EntityFrameworkCore package UnitOfWorkDbContextProvider class is instantiated directly EfCoreDatabaseApi, whether can provide a "IDatabaseApiFactory" to support https://entityframework-extensions.net/batch-savechanges

**Comment by XuJin186** [comment]
Overriding the saveChanges method of DbContext is not the best choice

**Comment by realLiangshiwei** [comment]
https://entityframework-extensions.net/batch-savechanges#what-is-supported

EF Core and more provider support is under development

**Comment by XuJin186** [comment]
https://entityframework-extensions.net/bulk-savechanges  
It does support EF CORE

**Comment by realLiangshiwei** [comment]
You can do it yourself. because it is not a standard ef core feature.
