### ISSUE TITLE
The main website is slow to surf

### ISSUE THREAD

**Issue by seventychi** [abpframework/abp#9390]
Hi, Abp.io is a compelling framework, but when I surf on the main site to get detailed information, the site is slightly slow. For now, I download the DDD e-book but still want to get the complete document reading on the website.
Thanks a lot!

**Comment by realLiangshiwei** [comment]
Thanks, we will check it.

**Comment by antosubash** [comment]
@realLiangshiwei docs website is slow as well. came here to post an issue but saw this so commenting here.

**Comment by ebicoglu** [comment]
we have addressed the slowness issue.
will be fixed in next week.

**Comment by seventychi** [comment]
> we have addressed the slowness issue.
> will be fixed in next week.

So happy to hear that!!

**Comment by berkansasmaz** [comment]
Problem solved on [docs.abp.io](https://docs.abp.io/en/abp/latest).

We found the main problem so, I think it will speed up on our other sites soon :)
