### ISSUE TITLE
Make standalone application for the docs module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#940]
Docs is an independent module and can be used inside an ABP application. In addition to that, we want to create a standalone application for this module. With that, anyone can install the docs module to a server and use it as an application.

TODO:

- [x] Create standalone applications by adding docs module.
- [x] Make it downloadable & installable easily.
- [x] Create a page (or web site) that shows how to download & install, reference to the source code... etc.

**Comment by ebicoglu** [comment]
* Project name: ... (temp name: VoloDocs)
* Solution name: ...   (temp name: Volo.Docs)
[ ] Make setup wizard/page (set app title, create database, navigate to create project page)

**Comment by ebicoglu** [comment]
https://volosoft.com/Products/VoloDocs
