### ISSUE TITLE
Web Test For Razor Pages In Tired Project

### ISSUE THREAD

**Issue by mostafa1790** [abpframework/abp#9400]
Hi,

I am using the latest version of abp framework **Tired** and I tried to test razor web pages there is no response from GetResponseAsStringAsync method

**Comment by realLiangshiwei** [comment]
`Tiered` project does not provide `Web.Tests` project

**Comment by realLiangshiwei** [comment]
Discuss in https://github.com/abpframework/abp/discussions/9398
