### ISSUE TITLE
Questions for connection string of multitenant - CurrentTenant changed to null forcely

### ISSUE THREAD

**Issue by catwarrior** [abpframework/abp#9401]
in latest abp 4.x.x

when perform db interaction, CurrentTenant changed to null forcely if Entity do not implement IMultiTenant interface, and these is no configuration to control this behavior.

Is it possible to make this one configurable? Otherwise for for auto implemented generic repositories we can not control the tenant.

and In abp 3.x.x, there is no tenant switch here.

`
public class EfCoreRepository<TDbContext, TEntity>

        protected virtual Task<TDbContext> GetDbContextAsync()
        {
            // Multi-tenancy unaware entities should always use the host connection string
            if (!EntityHelper.IsMultiTenant<TEntity>())
            {
                using (CurrentTenant.Change(null))
                {
                    return _dbContextProvider.GetDbContextAsync();
                }
            }

            return _dbContextProvider.GetDbContextAsync();
        }

`

**Comment by realLiangshiwei** [comment]
Hi,

This is by design, but the method is `virtual`, you can override it.
