### ISSUE TITLE
Can i rewrite DynamicApi action?

### ISSUE THREAD

**Issue by sofm13** [abpframework/abp#9402]
Can i rewrite DynamicApi action? like xx/getConfig To xx/get-Config,I want have the '-'

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers#route

> Normalization can be customized by setting the UrlActionNameNormalizer option. It's an action delegate that is called for every method.

Yes, you can do it.

**Comment by sofm13** [comment]
thanks
