### ISSUE TITLE
Provide a way to merge multiple api-definitions in a single point

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#9405]
Dynamic client proxies ([c#](https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients) and [js](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Dynamic-JavaScript-Proxies)) relies on an endpoint on the server that is provided by the ABP Framework: [api/abp/api-definition](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ApiExploring/AbpApiDefinitionController.cs#L8).
That endpoint returns a model of HTTP APIs provided from the server application. In this way, dynamic client proxies can understand how to call them.

Another great ABP feature is [Auto API Controllers](https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers), which exposes your application services as HTTP APIs.

These two system works great normally, but it can't work for MVC-tiered applications. Consider that scenario:

JS client ---> MVC website application ---> Backend HTTP API application

In this case, MVC website application's `api/abp/api-definition` endpoint can not return APIs provided by the Backend HTTP API application, because these APIs are not available in the process of the MVC website application. To make that possible, we currently should define proxy controllers ([example](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.HttpApi/Volo/Abp/Identity/IdentityUserController.cs)). In this way, MVC website application can have these APIs and `api/abp/api-definition` returns all the APIs. In practical, application services are hosted in the Backend HTTP API application, so the controllers actually injects dynamic c# proxies of the target app services. Finally, the Backend HTTP API application has the real implementation of the app services.

With this issue, I want to create a way of returning Backend HTTP API endpoint from the `api/abp/api-definition` endpoint of the MVC websites application (by somehow getting the api definition of the backend and merging with its own api-definitions). This even makes possible to create simple API gateways. In this case, we still need to a redirection of requests to the backend API, maybe using a middleware or API gateway library like Ocelot. One drawback is when we open Swagger UI in the MVC app, we can't see the APIs of the backend app, but this is already like that if we don't use the ABP Framework.

**Comment by xyfy** [comment]
With [Atuo-API](https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers),How can I set the document in the swagger?

the `GenerateDocumentationFile` property in `*.HttpAPi.csproj`  and `*.Application.Contracts.csproj`  has set to `True`

`*.HttpAPi.csproj` generate xml ,but contains none comments.

that caught I can only see the dto's XmlComments,not the api method.

How can I resolve this problem?

```
                    // 为 Swagger JSON and UI设置xml文档注释路径
                    var directory = System.IO.Directory.GetFiles(AppContext.BaseDirectory, "*.xml");
                    foreach (var xmlPath in directory)
                    {
                        options.IncludeXmlComments(xmlPath);
                    }
```

![微信图片_20210906110537](https://user-images.githubusercontent.com/7838147/132155060-c8ae163e-6916-4512-9ac2-136f78cf692b.png)

**Comment by hikalkan** [comment]
We won't make this since https://github.com/abpframework/abp/pull/9905 solves the main problems.
