### ISSUE TITLE
FileManagement Module Source Code

### ISSUE THREAD

**Issue by sachindratomer** [abpframework/abp#9412]
Hi There,

MY account has a commercial license and I want to utilize the file management module. The requirement to enhance the File Management module like adding thumbnail for images etc. for major changes in source code, modification is suggested but I am unable to download code and getting below error message.

An error occurred while getting the latest version from https://abp.io/api/download/module/get-version/ : Remote server returns '403-Forbidden'. Message: You need to upgrade your license to download source codes!

Please do suggest

**Comment by realLiangshiwei** [comment]
Hi,

Maybe your license does not include the source code, and we don't discuss commercials in the community. you can send an email to `info.abp.io`
