### ISSUE TITLE
Login Page Not Redirect

### ISSUE THREAD

**Issue by muratyuceer** [abpframework/abp#9416]
* 4.3.3
* Blazor Server (Not Tired)
* MongoDB

Hello
I created new project from zero. Problem is for example click login page and click login you will redirect to main page successfully. But after enter login page link to your browser manually it will open login page and will ask username & password , Even though I'm logged in.

Its should redriect to main page if user login.

**Comment by realLiangshiwei** [comment]
* Steps needed to **reproduce** the problem.

**Comment by mugambiwarwema** [comment]
Download a fresh project, build the front end and backend, 

Click login button, not redirecting to login page from home page.

Happened to me with the Angular version

**Comment by realLiangshiwei** [comment]
Thanks, I will check it

**Comment by realLiangshiwei** [comment]
I can't reproduce your problem.

![ng](https://user-images.githubusercontent.com/16813853/123290910-37777480-d544-11eb-9230-63989a953050.gif)

**Comment by realLiangshiwei** [comment]
>But after enter login page link to your browser manually it will open login page and will ask username & password , Even though I'm logged in.

Auth server is an independent website. There is no problem.

**Comment by muratyuceer** [comment]
> > But after enter login page link to your browser manually it will open login page and will ask username & password , Even though I'm logged in.
> 
> Auth server is an independent website. There is no problem.

Problem is returnurl not work, for example enter gmail login page, if you login before it will redirect you but abp not. RedirectUrl query key is redirecturl right?

**Comment by realLiangshiwei** [comment]
@muratyuceer 

How I reproduce it?

**Comment by muratyuceer** [comment]
> @muratyuceer
> 
> How I reproduce it?

For example, if i have login before when i go https://localhost:44313/Account/Login?returnurl=http://localhost:44313/ it should redirect https://localhost:44313 but its not redirect.

(If returnurl right query key)

**Comment by realLiangshiwei** [comment]
It will redirect when you login success
