### ISSUE TITLE
Volo.Abp.Dapper  can not change connectionstring 

### ISSUE THREAD

**Issue by yuyuguo1707** [abpframework/abp#9418]
### Documentation
I hava demands   I need dynamic changedatabase connection  when the application run, when I us
 await  GetDbConnectionAsync() ,the dbconnection  state is **Open** , So  i can not change the ConnectionString ;  When I 
Close then Connection , can change it ,But  GetDbTransactionAsync()  Is Null  , The function  need  a  transcation .
So How Can  get a  tranction 
`          
           var db = await GetDbConnectionAsync();
            if (db.State == ConnectionState.Open)
            {
                db.Close(); 
            }
            db.ConnectionString = connection;
            var trans = await GetDbTransactionAsync();`

**Comment by realLiangshiwei** [comment]
Hi,

You don't need to close the connection. EF Core support changed a DbConnection or connection string can now be changed on an already-initialized DbContext.

Example:

```csharp
var db = await GetDbConnectionAsync(); 
db.ConnectionString = connection; 
```

**Comment by yuyuguo1707** [comment]
@realLiangshiwei   sorry  the demo is efcore ，i use dapper ；Because I need  switch multiple databases with “SQL”， Worry about performance ，so I select dapper

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/Dapper#dapper-integration

> ABP does not encapsulate many functions for Dapper. ABP Dapper library provides a DapperRepository<TDbContext> base class based on ABP **EntityFrameworkCore module**, which provides the IDbConnection and IDbTransaction properties required by Dapper.
