### ISSUE TITLE
Separating Host & Tenant Database Schemas don't work

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#9420]
https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#separating-host-tenant-database-schemas
referenced document

abp version: 4.3.3

### Repeat steps
1. download my project
[aspnet-core.zip](https://github.com/abpframework/abp/files/6706702/aspnet-core.zip)

2. change to your connection string
![image](https://user-images.githubusercontent.com/7290992/123211786-80084100-d4f6-11eb-8a06-2f9b2d822f1a.png)

3. run Acme.BookStore.DbMigrator

### Result
1.  Host Database have table `AbpLinkUsers`
2.  Tenant Database have table `AbpLinkUsers`

normal result shoud be tenant database dont' have  `AbpLinkUsers`
because i see the `Volo.Abp.Identity.EntityFrameworkCore`
![image](https://user-images.githubusercontent.com/7290992/123212407-54d22180-d4f7-11eb-9b2b-d204163fc803.png)

Is my understanding wrong? 😅

**Comment by realLiangshiwei** [comment]
You need to create the tenant DB context

![image](https://user-images.githubusercontent.com/16813853/123215146-aa5bfd80-d4fa-11eb-83a5-66d54d1f186b.png)

**Comment by Loongle** [comment]
How can I refer to my tenant db context?

**Comment by Loongle** [comment]
![image](https://user-images.githubusercontent.com/7290992/123367591-c8823600-d5ac-11eb-980c-cd4f664fc399.png)

It doesn't work

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Entity-Framework-Core-Migrations#create-the-second-dbmigrationdbcontext

**Comment by Loongle** [comment]
Sorry, I have been trying to implement the document steps, but can not achieve the purpose.Can you provide a demo for reference? @realLiangshiwei
