### ISSUE TITLE
abp.ajax fails silently when jqXHR.status === 0

### ISSUE THREAD

**Issue by hillin** [abpframework/abp#9432]
If I understand correctly, [`abp.ajax` fails silently and leaves a hanging promise when `jqXHR.status === 0`](https://github.com/abpframework/abp/blob/1efc962aa1e15da6938ff2a3b6110ce869a0ed90/npm/packs/jquery/src/abp.jquery.js#L109). According to the comment in the abovementioned code, it is expected that the request is aborted in such case. However,
- `jqXHR.status === 0` can occur in other situations, such as the host is down, or CORS preflight has been rejected. The caller is entitled to know this;
- It's generally not a good idea to make a promise hanging.

Is it the code was supposed to be like this (which is still not good enough IMO as it still hangs the promise in certain scenarios)?
```javascript
if(jqXHR.status === 0 && jqXHR.statusText === 'abort')
//                    ↑ && instead of ||
```

**Comment by realLiangshiwei** [comment]
I think there is no problem because you can see the error in the console tab. This is consistent with the default behavior

![image](https://user-images.githubusercontent.com/16813853/123369634-adb1c080-d5b0-11eb-86f8-9f573fe0eae0.png)

**Comment by hillin** [comment]
But it doesn't give the caller a chance to handle the error

**Comment by realLiangshiwei** [comment]
You are right, we should consider allowing the developer to handle the error.
