### ISSUE TITLE
Remote service 'AbpFeatureManagement' was not found and there is no default configuration

### ISSUE THREAD

**Issue by GotzeWong** [abpframework/abp#9439]
Version=ABP 4.3.3 

When click ![image](https://user-images.githubusercontent.com/7664030/123504635-3aca4780-d68d-11eb-81d0-8303b06a0579.png), it returns 500 error.

![image](https://user-images.githubusercontent.com/7664030/123504606-0e163000-d68d-11eb-8248-5d92f136077d.png)

The log shows below
`Volo.Abp.AbpException: Remote service 'AbpFeatureManagement' was not found and there is no default configuration.`

Before 
The dialog could show up before even there are no values here.

And I'm also working on understanding the latest document of `Feature Management Module`.

**Comment by realLiangshiwei** [comment]
Can't reproduce the problem.

**Comment by GotzeWong** [comment]
That's my fault. I didn't include **AbpFeatureManagementEntityFrameworkCoreModule** when using the latest framework.
