### ISSUE TITLE
 integrated event library CAP ( https://github.com/dotnetcore/CAP)

### ISSUE THREAD

**Issue by geffzhang** [abpframework/abp#944]
eShopOnContainers integrated event library CAP https://github.com/dotnet-architecture/eShopOnContainers/issues/753  on  lastest PR https://github.com/dotnet-architecture/eShopOnContainers/pull/975
CAP is  EventBus available in the officially recommended production environment

**Comment by hikalkan** [comment]
I will check this. Thanks for offering.

**Comment by ThaiHM** [comment]
I have the same issue. I can not use CAP with ABP.

**Comment by xewn** [comment]
@ThaiHM    Can not use CAP without inheriting applictionservice

**Comment by Goxiaoy** [comment]
I created a project to integrate CAP and Abp. 

https://github.com/Goxiaoy/DoteNetCore.CAP.Abp

It's quite easy. You just need to replace the CAP [ConsumerServiceSelector](https://github.com/Goxiaoy/DoteNetCore.CAP.Abp/blob/master/src/DotNetCore.CAP.Abp/ConsumerServiceSelector.cs) and add [CapDistributedEventBus](https://github.com/Goxiaoy/DoteNetCore.CAP.Abp/blob/master/src/DotNetCore.CAP.Abp/EventBus/CapDistributedEventBus.cs) to publish message with `ICapPublisher`

There are some reasons why I do that,

- It provides a solution for #619 

- Kafka implementation

**Comment by geffzhang** [comment]
https://github.com/EasyAbp/Yhd.Abp.EventBus.CAP

**Comment by hikalkan** [comment]
See https://github.com/abpframework/abp/issues/2878
