### ISSUE TITLE
Getting granted-policies and roles without tenancy in application-configuration isn't working properly.

### ISSUE THREAD

**Issue by muscankaraoglu** [abpframework/abp#9441]
We are working on abp framework 4.3 EF Core, Angular project with multi-tenancy. 

We have tenancy independent roles and permission records on db. 
Roles:
![image](https://user-images.githubusercontent.com/57826345/123559499-06e24580-d7a5-11eb-8094-8bc3d1c3921a.png)
Example Permissions: 
![image](https://user-images.githubusercontent.com/57826345/123559533-3db85b80-d7a5-11eb-9271-c27f69a1dcf2.png)
UserRoles: 
![image](https://user-images.githubusercontent.com/57826345/123559561-69d3dc80-d7a5-11eb-97a6-2871870740cb.png)

Images are shared as examples. I did not share real records. Accurate recordings are available in the real environment.

We have 2 users in this case: 
![image](https://user-images.githubusercontent.com/57826345/123559899-9852b700-d7a7-11eb-9592-696dc7eaa869.png)
_As Host and tenant user_

When we have logged in with "admin(host)" user, we are getting granted-policies items correctly. But when logged in with tenant user we couldn't get granted-policies correctly **although the roles are assigned correctly**. 

**Admin User application-configuration response**:
![image](https://user-images.githubusercontent.com/57826345/123559924-cc2ddc80-d7a7-11eb-9114-7413a2c56fad.png)
![image](https://user-images.githubusercontent.com/57826345/123559974-04351f80-d7a8-11eb-83a4-5941903b6387.png)
Admin has role.

**Tenant User application-configuration response**:
![image](https://user-images.githubusercontent.com/57826345/123559840-342ff300-d7a7-11eb-9511-41e0b2e2ba13.png)
![image](https://user-images.githubusercontent.com/57826345/123559853-4742c300-d7a7-11eb-9e28-4876cb43170c.png)
User has no role.

But if we manually provide tenantId in permission and role record, it works fine. Should we manually create records for each tenant, role and permission record? This is an unacceptable problem in a system that will accommodate thousands of tenants. 

We do not want our system to manage user roles and privileges under tenants. How can we ensure that the role and permission structure in our system works truly independent of the tenant system?

**Comment by maliming** [comment]
hi

Please share some steps so that we can use the code to reproduce the problem. Thanks.

**Comment by asmaaalamir** [comment]
I have the same problem, what is the solution please?
