### ISSUE TITLE
Where is the Blob stored when using the Databse?

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#9445]
Hi,

My environment is

ABP 4.3
Client: Postman
DB Provider: EF Core
DB: PostgreSQL

I have used Blob storage for local file storage and for Azure Blob storage without issue. But I do not see where the blob data is stored when using a database provider.

I followed the tutorial from https://docs.abp.io/en/abp/latest/Blob-Storing-Database on Blob storage.

I am using a database storage provider [as shown in the documentation](https://docs.abp.io/en/abp/latest/Blob-Storing-Database#configuring-the-containers):

```C#
Configure<AbpBlobStoringOptions>(options =>
{
    options.Containers.ConfigureDefault(container =>
    {
        container.UseDatabase();
    });
});
```

I ran the solution and uploaded without issues (get back an HTTP 200 with no exception in logs), **but I do not see where the blob is** in the database. **Which table is it supposed to be in?**

The [additional information on databases](https://docs.abp.io/en/abp/latest/Blob-Storing-Database#additional-information) isn't very clear how to apply blob storage. There is no example

Would appreciate your help or a sample I can look at

**Comment by maliming** [comment]
hi

The blob is store in the `DatabaseBlob` entity/table.

https://github.com/abpframework/abp/blob/dev/modules/blob-storing-database/src/Volo.Abp.BlobStoring.Database.Domain/Volo/Abp/BlobStoring/Database/DatabaseBlob.cs#L18

https://docs.abp.io/en/abp/latest/Blob-Storing-Database#entities

**Comment by tinonetic** [comment]
Thank-you, @maliming 

Turns out that it wasn't actually working. 

The correct generated tables are actually  `AbpBlobs` and `AbpBlobContainers`

Now running fine
