### ISSUE TITLE
Sample project with Elsa Workflow can not edit workflow created with designer

### ISSUE THREAD

**Issue by khanhtranchi** [abpframework/abp#9446]
I downloaded the sample project at https://github.com/abpframework/abp-samples/tree/master/ElsaDemo to try. But when create and edit the workflow from designer and click publish it throw the exception "An error occurred: Request failed with status code 500".
I created the clean new project and followed the steps from Elsa's article, it works normally.
Elsa and ABP are 2 great frameworks, and it would be great if we can combine them.

The steps to reproduce:
1. Download the project
2. Run DbMigrator solution to migrate data
3. Ctrl - F5 to run the project
4. Create new http workflow from designer
5. Edit the workflow created at step 4

Thanks.

**Comment by maliming** [comment]
> An error occurred: Request failed with status code 500

Can you share the logs?

**Comment by khanhtranchi** [comment]
Here is your requested log.
[logs.txt](https://github.com/abpframework/abp/files/6731462/logs.txt)

**Comment by maliming** [comment]
hi

Have you tried the same steps without abp framework?

**Comment by khanhtranchi** [comment]
I followed this guide https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints
After setup, I can create and edit workflows normally. I double checked the data submit to Elsa API Server in 2 frameworks, it the same but abp throw the exceptions.

**Comment by maliming** [comment]
> After setup, I can create and edit workflows normally

Can you share this project?

**Comment by khanhtranchi** [comment]
Here is demo project created by following guide from elsa workflow article
[ElsaQuickstarts.Server.DashboardAndServer.zip](https://github.com/abpframework/abp/files/6737929/ElsaQuickstarts.Server.DashboardAndServer.zip)

**Comment by maliming** [comment]
hi @khanhtranchi See https://github.com/abpframework/abp-samples/commit/90ff663a03fe5103d90e45d39a319a3af44a839d
