### ISSUE TITLE
Error: No items provided for select attribute

### ISSUE THREAD

**Issue by luochaorobert** [abpframework/abp#9447]
* **ABP Framework version 4.3.2**
* User Interface type: MVC
* database provider: EF Core

I extended a property of a enum type to IdentityUser:
```
public enum UserType
    {
        Regular,
        Dispatch,
        Administrator,
        Guest
    }

ObjectExtensionManager.Instance
    .MapEfCoreProperty<IdentityUser, UserType>(
        "Type",
        (entityBuilder, propertyBuilder) =>
        {
            propertyBuilder.HasDefaultValue(UserType.Guest);
        }
    );

ObjectExtensionManager.Instance.Modules()
      .ConfigureIdentity(identity =>
      {
          identity.ConfigureUser(user =>
          {
              user.AddOrUpdateProperty<UserType>(
                  "Type",
                  property =>
                  {
                      property.Attributes.Add(new RequiredAttribute());
                      property.DefaultValue = UserType.Guest;
                  }
              );
          });
      });
```

When I start the web page, I can open the form of create users and add users normally, but when I click edit users, I will get 500 errors. I checked the console log, see error: `No items provided for select attribute.`
```
at Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form.AbpSelectTagHelperService.GetSelectItems(TagHelperContext context, TagHelperOutput output)`
```
By querying the source code, I find the `getselectitems()` method from `abpselecttaghelperservice` report this errors: `throw new exception ("no items provided for select attribute.") `

I can't solve it, ask for help, thank you very much!

**Comment by maliming** [comment]
Can you try your code in the template project and share it?

**Comment by luochaorobert** [comment]
> Can you try your code in the template project and share it?

This is a new template I have created: https://github.com/luochaorobert/UserTypeTest
Please have a look. Thank you for your help!

**Comment by maliming** [comment]
HI

* Steps needed to **reproduce** the problem.

**Comment by luochaorobert** [comment]
> HI
> 
> * Steps needed to **reproduce** the problem.

1. `update-database` in the project `UserTypeTest.IdentityServer`
2. Start the three projects in sequence: `UserTypeTest.IdentityServer`, `UserTypeTest.HttpApi.Host`, `UserTypeTest.Web.Host`
3. Enter the user management page（`https://localhost:44383/Identity/Users`）
4. Select a user and click Edit

And then the error occurred.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/9454

**Comment by luochaorobert** [comment]
I updated the latest version 4.4 and found that the “no items provided for select attribute” error no longer exists, but there are new problems. When creating or editing a user on the Web.Host, the custom extension field will only change in "ExtraProperties", but the separate field value will not change.

![image](https://user-images.githubusercontent.com/58897116/127955199-04dee3ae-b8b6-4ad9-a1bf-e92c3114cef3.png)




> #9454

**Comment by maliming** [comment]
@luochaorobert Please create a new issue.
