### ISSUE TITLE
Do I have to use Autofac if I want to implement an AOP interceptor?

### ISSUE THREAD

**Issue by LFDCC** [abpframework/abp#9448]
I clone the source code of ABP vnext and find that only Volo. Abp.Autofac uses the IABPInterceptor

If I don't use Autofac as the IOC container, how can I implement AOP interception? 

I have implemented it in my own source code.  I would like to see how ABP VNext is implemented!!!

**Comment by maliming** [comment]
The `DynamicProxy` is abstract.  It uses [Castle](https://github.com/castleproject/Windsor).

https://github.com/abpframework/abp/tree/dev/framework/src/Volo.Abp.Core/Volo/Abp/DynamicProxy
https://github.com/abpframework/abp/tree/48c52625f4/framework/src/Volo.Abp.Castle.Core/Volo/Abp/Castle/DynamicProxy
