### ISSUE TITLE
Error 500 creating new pre-release project

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#9450]
Create new project form the Getting Started page

**Project name:** Testing
**Project type:** Application
**UI Framework:** Blazor Server
**Database Provider:** Entity Framework Core
**Database management system:** SQL Server

Select "Uses latest pre-release version (4.4.0-rc.1)."

![image](https://user-images.githubusercontent.com/69393775/123758569-f5895e00-d8b6-11eb-8e75-6c3d8b6f32b4.png)

**Comment by realLiangshiwei** [comment]
Worked now, can you try again?

**Comment by DonVliet** [comment]
> Worked now, can you try again?

Cheers, that's working now :-)
