### ISSUE TITLE
Update tenent Id in models

### ISSUE THREAD

**Issue by dmeagor** [abpframework/abp#9455]
Since TenantId has no setter it doesn't appear possible to merge tenants together.  

![image](https://user-images.githubusercontent.com/714902/123787601-ee704900-d8d2-11eb-960c-ec527d0adfd5.png)

**Possible solutions**

- Add MergeTenant method that loops through all entities with IMultiTenant and changes the TenantID.  Similar to the image above.
- Add SetTenantId method
- Just add a setter to the model.

**Comment by maliming** [comment]
> Add SetTenantId method

This is recommended way. and your image is not clear

**Comment by dmeagor** [comment]
![image](https://user-images.githubusercontent.com/714902/123789475-1a8cc980-d8d5-11eb-8004-e92c310ffd8e.png)

**Comment by maliming** [comment]
I think you can add an interface and implement a `SetTenantId` method,
