### ISSUE TITLE
How to export excel

### ISSUE THREAD

**Issue by nguyenquanghuyit** [abpframework/abp#9457]
Please guide to me how to export to excel using Mvc-EfCore

**Comment by berkansasmaz** [comment]
Hi @nguyenquanghuyit,

We already have a [sample application](https://github.com/abpframework/abp-samples/blob/master/ExcelIO/src/ExcelIO.Web/Pages/Index.cshtml.cs) developed for this topic.

So, I am closing this issue, but feel free to write if you have a problem :)

**Comment by nguyenquanghuyit** [comment]
Dear!
Thanks for your help. I do not know why has a message
![image](https://user-images.githubusercontent.com/52340160/123894367-3ef5ae00-d988-11eb-99d4-b865bc2a612d.png)

**Comment by berkansasmaz** [comment]
Can you try to login?

/Account/Login

**Comment by nguyenquanghuyit** [comment]
I downloaded abpsample, then selected ExcelIO sample.
I also initialized the database. However, when I run it, it always gives me that error and I can't go to the list to choose
![image](https://user-images.githubusercontent.com/52340160/123937389-4f297f80-d9c0-11eb-9ed8-ace390fcc65a.png)

**Comment by berkansasmaz** [comment]
I just tried it but I didn't get any errors. Here are my steps:

1. Check **Connection Strings** and run `ExcelIO.DbMigrator` project.
2. Run `ExcelIO.Web `project
3. Go to `https://localhost:44360/Account/Login`
4. Enter username and password (`admin`, `1q2w3E*`)

<img width="1437" alt="Ekran Resmi 2021-06-30 13 48 50" src="https://user-images.githubusercontent.com/31216880/123949991-e3d5b280-d9ab-11eb-8a1c-ba44b22fe14e.png">

If there is still an error after trying these steps, can you send the log file(`ExcelIO.Web/Logs/logs.txt`)?

**Comment by nguyenquanghuyit** [comment]
Dear!
With your guide, I've done it. Thank you so much!
But I do not understand about that I use "https://localhost:44360/Account/Login" that run, else use "https://localhost:44360/"  that could not.

**Comment by nguyenquanghuyit** [comment]
Dear! Can you help me? How to setup paper size, font size?

**Comment by berkansasmaz** [comment]
Because the `GetListAsync` method of `IdentityUserAppService` is [used for the information shown on this page](https://github.com/abpframework/abp-samples/blob/55fe43bdda07c1ae6fc7afb6a065860075bae461/ExcelIO/src/ExcelIO.Web/Pages/Index.cshtml.cs#L23), and this method has the authorize attribute.

https://github.com/abpframework/abp/blob/573b6a78e3ced99b8e709d87047fed9b1fa66e9d/modules/identity/src/Volo.Abp.Identity.Application/Volo/Abp/Identity/IdentityUserAppService.cs#L40

**Comment by nguyenquanghuyit** [comment]
Dear sir!

Let me ask him a question? How to specify column width in cm or mm in worksheet?
For example: 
worksheet.Column(1).Width = 81; 
But I do not known 81 for pixel or inch or cm, mm;
Thank you!

**Comment by berkansasmaz** [comment]
This question does not seem to be related to ABP and I see that you have already opened another issue on the ClosedXML repository. I hope you can find what you are looking for as soon as possible :)

**Comment by nguyenquanghuyit** [comment]
Thank u so much!
