### ISSUE TITLE
Ocelot's Kubernetes integration module is ready

### ISSUE THREAD

**Issue by geffzhang** [abpframework/abp#946]
Ocelot's Kubernetes integration module is ready, and ABP can consider closer integration with k8s to enable k8s load balancing in the gateway，Document See also: https://ocelot.readthedocs.io/en/latest/features/kubernetes.html

**Comment by hikalkan** [comment]
Thanks for informing. We will consider it.

**Comment by tomfanara** [comment]
Can somebody tell me more about how to create the ServiceDiscoveryProvider? The documentation kind of leaves you hanging!

**Comment by hikalkan** [comment]
We won't use Ocelot anymore. We prefer YARP.
