### ISSUE TITLE
Basic console app - add module with database

### ISSUE THREAD

**Issue by leonkosak** [abpframework/abp#9465]
Console app template docs: https://docs.abp.io/en/abp/latest/Startup-Templates/Console

How to include in such console app another module, which has:
- database access
- xxxAppService methods (in .Application layer) and xxxManager methods (in .Domain layer)

I want to call methods inside .Application and .Domain layers from other module inside console application.
How to properly configure console application (ConfigureServices, appsettings.json,...) for such scenarios?
Thank you for explanations.

**Comment by maliming** [comment]
hi
The app and module template both have a `HttpApi.Client.ConsoleTestApp`. Have you checked it?

**Comment by leonkosak** [comment]
Yes, it helped. Thank you.
However, I have some additional questions regarding authentication. I'll send you sample project via email.
