### ISSUE TITLE
dbMigrator gets exponentially slower as tenants increase

### ISSUE THREAD

**Issue by dmeagor** [abpframework/abp#9467]
* Your ABP Framework version **4.3 Commercial**
* Your database provider **EF Core**

dbmigrator works ok for the first few hundred tenants but starts halving in speed every 300 or so.  After a couple of thousand it barely manages one per second.  I gave up so I don't know how slow it gets or if it crashed entirely.  Our SaaS company has over 50,000 tenants (mostly free/trial users as its a freemium model) so we're a bit stuck at the moment.

- mssql profiler shows n+1 issue with [AbpPermissionGrants] and [AbpClaimTypes].  50k tenants' generates 3 million+ queries to these tables.
- we have identified _dataSeeder.SeedAsync() is the slow call. 
- removing all seedcontribuiter classes (identity server and saas)  or the schema migrations didn't seem to make a lot of difference to the performance.
- It doesn't matter if there are no changes or no data to seed.  Its reads not writes causing slowdown.

![image](https://user-images.githubusercontent.com/714902/123943677-4cb13080-d994-11eb-9198-07c1316b053b.png)

I think maybe all of these queries is causing issued with efcore object creation.  I ran dotprofiler but the bulk of the time is shown in hidden compiled methods. Is there any reason the abp permissions/claims etc, cannot be queried in bulk, 2 queries/tenant or 2/database even?

**Comment by leonkosak** [comment]
I am sure, that this is EF context limitation, which could not run in parallel. db context is single-threaded.

**Comment by dmeagor** [comment]
> I am sure, that this is EF context limitation, which could not run in parallel. db context is single-threaded.

I noticed it appeared to be using a single core.  Which is worrying as I'm using a modern Ryzen 3800x for dev, the web server is much lower clocked.  

Clearly something isn't right as it gets slower over time though, from 10 tenants/second to barely 1/sec after a couple of thousand.

This means that ABP doesn't currently scale and is only usable for smaller B2B projects.

**Comment by NecatiMeral** [comment]
I assume that the slow-down comes from the growing unit-of-work, but I'm not an expert in this topic.

**Comment by dmeagor** [comment]
> I assume that the slow-down comes from the growing unit-of-work, but I'm not an expert in this topic.

As far as I can tell its all selects, no inserts in the profiler so I would have thought UoW was empty (I'm no expert on any of this though.)

I did a bit of googling here and apparently this is a known issue of EFCore and long iterations

Solutions. 

- Don't do long iterations.  Pull out permissions etc. in one query.  Looking at PermissionDataSeeder.cs this seems like a quick change.
- Recreate the dbContext object inside of the loop for each iteration ( each tenant )
- Turn off change tracking for the dbContext instance or specific queries.

This is the rather unhelpful profiler report.
![image](https://user-images.githubusercontent.com/714902/123970326-ef77a800-d9b0-11eb-847c-48738bfb1f19.png)
