### ISSUE TITLE
Customize toolbar in blazor server app with started template does not work.

### ISSUE THREAD

**Issue by javietanh** [abpframework/abp#9469]
Hi folks, 

Could you guys please help me out of this problem. I can't get this code execute, what's wrong with it? using started template then build and run, while debug I found the breakpoint from this function does not execute.

```

public class ChatToolbarContributor : IToolbarContributor
{
    public async Task ConfigureToolbarAsync(IToolbarConfigurationContext context)
    {
        if (context.Toolbar.Name == StandardToolbars.Main)
        {
            var authorizationService = context.ServiceProvider.GetRequiredService<IAuthorizationService>()

            if (await authorizationService.IsGrantedAsync(ChatPermissions.Messaging))
            {
                context.Toolbar.Items.Insert(0, new ToolbarItem(typeof(MessagesToolbarItemViewComponent)));
            }
        }
    }
}

```

**Comment by javietanh** [comment]
After a few hours debug, I realized that if I inherited from 

`
using Volo.Abp.AspNetCore.Components.Web.Theming.Toolbars;
`

then the breakpoint is hit but from 
`
using Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared.Toolbars;
`
it will not be hit. 

For the blazor server app, what should I use?

**Comment by maliming** [comment]
hi

MVC:
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared/Toolbars/IToolbarContributor.cs

Blazor WASM & Server:
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Components.Web.Theming/Toolbars/IToolbarContributor.cs
