### ISSUE TITLE
Replace Blazorise components with "free for non-commercial use" components

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#9470]
I assume most developers, like myself, use abp.io as the basis of their projects to write programs either for their clients, or in-house for the company they work for, i.e. in a commercial environment.

Unfortunately for us Blazor developers, it looks like Blazorise is now a commercial project and we are required to pay a minimum yearly license fee of $499 (per year, per company) if we want to continue to use the components in commercial projects. As it states on the front page of the Blazorise website it is only "Free to use in a Non-Commercial-Manner, under the Apache License."

It would therefore be better if the Blazorise components were replaced by a less restrictive set of components, for example Radzen components which are "...open source and free for commercial use."

BTW You could also consider using the Syncfusion components as they are free for commercial use for companies with less than $1million turnover.

Your thoughts are most welcome, Don

**Comment by maliming** [comment]
hi

> Blazorise will stay free just as before, but it will move under the Apache 2.0 license instead of being under the MIT license. For regular users, and smaller companies (under $1 million annual revenue), Blazorise will stay and be completely free just as it is now. But for companies that have annual revenue of over $1 million, a new commercial license will need to be issued.

https://blazorise.com/news/changes-to-blazorise-license/#:~:text=Blazorise%20will%20stay,to%20be%20issued.

**Comment by dmeagor** [comment]
Replacing blazorize sounds like a lot of work for very little gain.  $500 for a $1m+ company is nothing and it helps them to develop the product.

Side note, we used syncfusion (angular wrapper) quite extensively on a large project but would never recommend it and have now stripped it out for angular material.   Maybe the blazor version is better but the angular wrapper was very badly thought out and docs are maddening.

Their support is amazing though, ABP commercial would do well to replicate!
