### ISSUE TITLE
How to disable auto api without [RemoteService(false)]

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#9473]
We can use `[RemoteService(false)]` to disable auto api seen from doc:

![image](https://user-images.githubusercontent.com/24971860/124062596-9026a000-da63-11eb-850f-021e7c06195c.png)

However, when i read source code from Identity module, I never saw [RemoteService(false)] in `IdentityRoleAppService.cs`.
But, it does implement disable the auto api. So, how did it works?

![image](https://user-images.githubusercontent.com/24971860/124062864-22c73f00-da64-11eb-985d-8f36598b82aa.png)

**Comment by maliming** [comment]
The module doesn't use `Auto API Controllers`. It has the HTTP API layer.
