### ISSUE TITLE
Blazorise -  Manual Validation is not working because of array value used to bind the text. Example: @bind-Text="address[iteration]"

### ISSUE THREAD

**Issue by DurgaSanthi** [abpframework/abp#9476]
Blazorise - Manual Validation is not working because of array value used to bind the text. Example: @bind-Text="address[iteration]" 

This works for auto validation but not for manual validation

<Validations @ref="validations" Mode="ValidationMode.Manual">

Created TextEdit components in loop. For example there are 10 elements and Element Id = addressid[0], addressid[1] etc.
And the @bind-Text="address[0]" etc

Below is the exception am getting.

Exception message:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The provided expression contains a InstanceMethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.
System.ArgumentException: The provided expression contains a InstanceMethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.ParseAccessor[String](Expression`1 accessor, Object& model, String& fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[String](Expression`1 accessor)
   at Blazorise.Validation.InitializeInputExpression[String](Expression`1 expression)
   at Blazorise.TextEdit.SetParametersAsync(ParameterView parameters)
 
Can someone help

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by DurgaSanthi** [comment]
updated the Issue description

**Comment by maliming** [comment]
hi @DurgaSanthi 

It seems this is not related to abp but Blazorise.
You can try to get help at https://github.com/Megabit/Blazorise

**Comment by DurgaSanthi** [comment]
> hi @DurgaSanthi
> 
> It seems this is not related to abp but Blazorise.
> You can try to get help at https://github.com/Megabit/Blazorise

Thank you. sure.
