### ISSUE TITLE
How to automatically convert audited DateTime properties (CreatedDate, LastModificationTime and DeletetionTime) from DateTime.Now to UTC-0

### ISSUE THREAD

**Issue by onurcanyilmaz** [abpframework/abp#9487]
Hello.

We have to have Audited DateTime properties (CreatedDate, LastModificationTime and DeletetionTime) need to be automatically converted a UTC-0 (Greenwich time)

Can you help me pls?
thanks.

**Comment by maliming** [comment]
hi

Maybe you can take a look at https://docs.abp.io/en/abp/latest/Timing
