### ISSUE TITLE
Gulp 

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#9490]
4.4.0-rc1
mvc-ef

![image](https://user-images.githubusercontent.com/28866278/124382384-d718cd80-dccf-11eb-8e37-98345d7f96e3.png)

**Comment by maliming** [comment]
You can try `abp install-libs` command.

https://blog.abp.io/abp/ABP-Platform-4-4-RC-Has-Been-Released#:~:text=place%20that%20code.-,New%20ABP%20CLI%20Commands,-There%20are%20new

**Comment by recruitans** [comment]
I ran it. there was no change. else ?

**Comment by maliming** [comment]
![image](https://user-images.githubusercontent.com/6908465/124432435-3516e500-dda4-11eb-8eb0-0410e6963d1d.png)

**Comment by recruitans** [comment]
it's ok. same screen. but run the application please. and you try create blog post. 

![image](https://user-images.githubusercontent.com/28866278/124498262-b9796000-ddc4-11eb-9e8a-21ecfc188ea3.png)

**Comment by maliming** [comment]
hi
I will check this.

**Comment by maliming** [comment]
You can wait for RC2. https://github.com/abpframework/abp/pull/9481

**Comment by recruitans** [comment]
> You can wait for RC2. #9481

![image](https://user-images.githubusercontent.com/28866278/124742184-23108000-df25-11eb-9715-a6cc5908b6d6.png)

**Comment by maliming** [comment]
You need to upgrade your nuget&npm package to rc2.
