### ISSUE TITLE
Is it possible to use a Index.cshtml (Razor page) as the home page in a Blazor server project?

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#9491]
* Your **ABP Framework version**. 4.4.0-rc1
* Your **User Interface** type Blazor Server
* Your database provider(EF Core)

I want to build a website and use the razor page as frontend, the blazor component in the backend. Is it possible?

Thanks!

**Comment by maliming** [comment]
I think this is possible in the Blazor server.

**Comment by juchunwei** [comment]
@maliming , Thanks.  I tried add a Index.cshtml file but get this error message when run the app.  It works if the name not index.cshtml, can open it with another name.  Appreciate it for your help!


An unhandled exception occurred while processing the request.
AmbiguousMatchException: The request matched multiple endpoints. Matches:

/_Host
/Index
/_Host
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)

AmbiguousMatchException: The request matched multiple endpoints. Matches: /_Host /Index /_Host
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by maliming** [comment]
You can try this in Blazor Server without abp first.

**Comment by NicolasEhrhard** [comment]
Hello, any update on this ? I've got the same error with Blazor Server .Net 6. This error came when i Depend On AbpAspNetCoreMvcModule
