### ISSUE TITLE
User Interface Maturity/Adoption

### ISSUE THREAD

**Issue by sel-carlitos** [abpframework/abp#9494]
Hi all, 
I just found this incredible development framework that makes my dreams come true for my next project. I would like to ask the developers and community about User Interface adoption? Is Angular the top choice? Is Angular the most mature user interface? 

Thanks in advance for your replies. 

Carlos

**Comment by EngincanV** [comment]
Hi @izotecarlitos, ABP Framework has 4 UI options (officially supported) which are MVC (Razor Pages), Angular, Blazor WASM and Blazor Server. Blazor Wasm and Blazor Server are relatively recently added user interfaces. For this reason, it may be better to go with MVC or Angular.
