### ISSUE TITLE
Update VoloDocs standalone deployments

### ISSUE THREAD

**Issue by joernz** [abpframework/abp#9516]
Could you please update the standalone deployments (zip downloads) on [the documents page](https://docs.abp.io/en/abp/latest/Apps/VoloDocs#download) of VoloDocs?
Thanks!

The package.json file of the current downloads:
```json
"version": "0.1.0",
  "name": "volo.docstestapp",
  "private": true,
  "dependencies": {
    "@abp/aspnetcore.mvc.ui.theme.basic": "^0.4.9",
    "@abp/docs": "^0.5.1"
  }
```

**Comment by ebicoglu** [comment]
hi 

these are self-contained production-ready deployment files.

but we didn't update them for a long time.

@EngincanV will update them.

1- Update zip files here [https://docs.abp.io/en/abp/latest/Apps/VoloDocs#download](https://docs.abp.io/en/abp/latest/Apps/VoloDocs#download)

2- Update this document to be aligned with the latest version

**Comment by EngincanV** [comment]
Hi @joernz, we've updated the download links to version `4.4.0-rc.2`. You can download it from [here](https://docs.abp.io/en/abp/latest/Apps/VoloDocs#download).

**Comment by joernz** [comment]
@EngincanV thanks for the updates.
how can I create a new project with local FileSystem?
Edit: find the answer (https://docs.abp.io/en/abp/latest/Modules/Docs#sample-project-record-for-filesystem) :)

How do we change the tab title now? It shows always `VoloDocs` no matter which name we have in the database for the project.
![image](https://user-images.githubusercontent.com/75144099/125285683-32c00800-e31b-11eb-9b9b-ea00b938dae9.png)
