### ISSUE TITLE
Logo on login page redirects to 

### ISSUE THREAD

**Issue by eneskoroglu** [abpframework/abp#9517]
* Your **ABP Framework version**: 4.3.3
* Your **User Interface** type: (Angular) 
* Your database provider(EF Core)

I see there is a related [issue](https://github.com/abpframework/abp/pull/6734) about this problem. Although I set **RedirectAllowedUrls** and tried with a new created project, click on LOGO in login page redirects to API. Below screen shot is belongs to new created test project. My web site logo also redirects to https://test-app.mydomain.com/ address. How can i redirect logo to my frontend (https://test-services.mydomain.com)

```
"App": {
	"SelfUrl": "https://test-app.mydomain.com",
	"AngularUrl": "https://test-services.mydomain.com",
	"CorsOrigins": "http://localhost:4200,https://*.ekol.com,https://*.mydomain.com",
	"RedirectAllowedUrls": "https://test-services.mydomain.com"
}
```

![image](https://user-images.githubusercontent.com/7870434/124622234-9a8dd300-de83-11eb-8e77-dd62fb7c5bd9.png)

**Comment by maliming** [comment]
hi
Let's discuss the commercial at https://support.abp.io Thanks.
