### ISSUE TITLE
Social logins don't work for existing accounts.

### ISSUE THREAD

**Issue by dmeagor** [abpframework/abp#9519]
* Your **ABP Framework version**.  4.3 commercial
* Your database provider EF Core
Steps to reproduce

- Go to register page and create new user.
- Go to login page and click social login

Instead of attaching the social login to the matching account the user is taken to the register page.
If for some reason they try to register again it will error (account already exists)

The only way to get social to work is to register the account from the social link on the login page?!

Social login should auto login or register as is standard for this type of authentication.

**Comment by maliming** [comment]
> Instead of attaching the social login to the matching account the user is taken to the register page.

I guess they emails are the same, right?

**Comment by dmeagor** [comment]
> I guess they emails are the same, right?

There are no emails as its not possible to register (from the social option.)

Put simply, there is no way for a user to use a social login if they have already registered.  If they try they will be prompted to create another account with a different email address.

This is the same on your own ABP site

**Comment by dmeagor** [comment]
> I guess they emails are the same, right?

Yes, they are identical.

**Comment by dmeagor** [comment]
A temporary fix (adding a new row to UserLogin) is below.  I a call to this method directly to the OnGetExternalLoginCallbackAsync method but it should work as an override.

Note: I've used the standard `await UserManager.AddLoginAsync(user, newUserLoginInfo);`  instead of the ABP  `user.AddLogin` as that fails in this case with a null reference. I'm not sure why or what the AddLogin function does (it's mostly just cut and pasted from Register)

I'm not sure how this would work with the tenant linking functionality.  I haven't looked at that yet.

```
        protected virtual async Task<IdentityUser> AddExternalLoginAsync(ExternalLoginInfo externalLoginInfo)
        {
            await IdentityOptions.SetAsync();
            var emailAddress = externalLoginInfo.Principal.FindFirstValue(ClaimTypes.Email);

            var user = await UserManager.FindByEmailAsync(emailAddress);
            if (user is null)
            {
                return null;
            }
                
            var userLoginAlreadyExists = user.Logins?.Any(x =>
                x.TenantId == user.TenantId &&
                x.LoginProvider == externalLoginInfo.LoginProvider &&
                x.ProviderKey == externalLoginInfo.ProviderKey) ?? false;

            if (!userLoginAlreadyExists)
            {
                var newUserLoginInfo = new UserLoginInfo(                    
                    externalLoginInfo.LoginProvider,
                    externalLoginInfo.ProviderKey,
                    externalLoginInfo.ProviderDisplayName);
 
                await UserManager.AddLoginAsync(user, newUserLoginInfo);
                (await UserManager.UpdateAsync(user)).CheckErrors();
            }

            return user;
        }
```

**Comment by ebicoglu** [comment]
**workaround:**

Create a custom login page model under **Pages/Account** named Cutom**LoginModel.cs (**[CustomLoginModel.cs (github.com)](https://gist.github.com/gterdem/d5d1841094d6818755e80aa5a2d4a5ed))

![](https://user-images.githubusercontent.com/9526587/125040531-71965980-e0a0-11eb-8d3e-3a8a18570852.png)

Create a new .cshtml named **Login.cshtml** under same directory ([LoginPage.cshtml (github.com)](https://gist.github.com/gterdem/9f39f556e24fcc1ff296e06b7524f79b))

Test and modify as you see fit.
