### ISSUE TITLE
Still needs to provide separated dbcontext migrations for start template

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#9520]
* Your **ABP Framework version**. ver 4.4.0-rc.1
* Your database provider(EF Core/MongoDB) : EF Core

The 4.4.0-rc.1 introduced a change to the start template "Removed EntityFrameworkCore.DbMigrations Project", but some developers still feel separated dbcontext for migrations is a good options for large projects, could you provide an option to generate the start template with the separated dbcontext migrations?

**Comment by maliming** [comment]
There is no plan to do this. It is difficult to maintain such a template, you can implement it yourself based on the old template.
