### ISSUE TITLE
DB Changed directly in UOW even if exception occurs

### ISSUE THREAD

**Issue by Sooian** [abpframework/abp#9521]
ABP Framework version: 4.3.2
 User Interface: Vue
 Database provider:(EF Core)
 DB: pgsql

I follow the tutorials from https://docs.abp.io/ to create my application

I create my applicationServer.

```
public class AppOrganizationAppService : ApplicationService, IAppOrganizationAppService
    {
        private readonly IOrganizationUnitRepository _ouRepository;
        private readonly OrganizationUnitManager _ouManager;

        public AppOrganizationAppService(
            IOrganizationUnitRepository ouRepository,
            OrganizationUnitManager ouManager
            )
        {
            _ouRepository = ouRepository;
            _ouManager = ouManager;
        }

        [UnitOfWork]
        public virtual async Task<GeneralRequstResult<OrganizationUnitDto>> UpdateAppOrgAsync(Guid id, OrganizationUnitUpdateDto input)
        {
            var ou = await _ouRepository.GetAsync(id);
            ou.DisplayName = input.DisplayName; // the line was updated to db, even if exception occurs

            throw new Exception("new exception");

            var ou1 = await _ouRepository.GetAsync(new Guid("39fd8c53-51e4-e2dc-388e-bde5ed98dee5"));
            ou1.DisplayName = input.DisplayName+"test test";

            return GeneralRequstResult<OrganizationUnitDto>.GoSuccess(null);
        }
}
```
I did not call await CurrentUnitOfWork.SaveChangesAsync(); but changes go into db.
What's even stranger is that even if an exception occurs, The data before the exception was also updated to the database, and no rollback occurred.

Did i made something wrong?

**Comment by maliming** [comment]
Can you try to remove `app.UseUnitOfWork()` from the ASP.NET Core pipeline?

**Comment by Sooian** [comment]
> Can you try to remove `app.UseUnitOfWork()` from the ASP.NET Core pipeline?

after i remove app.UseUnitOfWork(), the uow works as expect when exception occurs.
what app.UseUnitOfWork() is used for? This seems to be a necessary configuration, when do I need it?
and, the other problem is why the data go into db without savechanges? did i miss some configuration ?

**Comment by maliming** [comment]
See #8740

**Comment by Sooian** [comment]
> See #8740
thanks!!!
Do i need to call CurrentUnitOfWork.SaveChangesAsync(); after i change the entity?

**Comment by maliming** [comment]
> Do i need to call CurrentUnitOfWork.SaveChangesAsync(); after i change the entity?

Please follow the document. https://docs.abp.io/en/abp/latest/Unit-Of-Work
