### ISSUE TITLE
How to display in Chinese in the "BackendAdminApp.Host" project of "MicroserviceDemo" abp-samples?

### ISSUE THREAD

**Issue by luochaorobert** [abpframework/abp#9529]
* **ABP Framework version 4.3.3**.
* User Interface type: MVC
* database provider: EF Core

I developed on the basis of the "MicroserviceDemo" sample, but the built-in module always can't switch to display Chinese, such as identity management. It seems that can't get localization resources, while the custom module can switch between Chinese and English normally, as shown in the figure below.

![image](https://user-images.githubusercontent.com/58897116/124783963-0ea9a300-df78-11eb-83fd-c661e42015ac.png)

 I've tried all kinds of ways, but I still can't solve it. Ask for help, thank you very much!

I found some related issues, like [#2469](https://github.com/abpframework/abp/issues/2469). Although it gave me some inspiration, it still failed to solve my problems.

**Comment by maliming** [comment]
How about other languages?

**Comment by luochaorobert** [comment]
> How about other languages?

When choosing other languages like Français,  the built-in module still display English, the custom module still display Chinese.

**Comment by luochaorobert** [comment]
About how to configure the localization in the microservice architecture, can the development team give a feature article, such as how to separately configure in the module layer, service layer, gateway layer and application layer? Different layers and modules seem to be prone to conflict. Referring to the existing documents, there are always various bugs. I spent a lot of time, but I still can't solve them well. 

Thanks a lot for your hard work!

**Comment by maliming** [comment]
You can debug your application to check the localization, maybe it uses the wrong **resources**.

**Comment by GotzeWong** [comment]
Add this line to Configure() in Startup.cs 
`            app.ApplicationServices.GetService<ISettingDefinitionManager>().Get(LocalizationSettingNames.DefaultLanguage).DefaultValue = "zh-Hans";`

![image](https://user-images.githubusercontent.com/7664030/125226662-106ec000-e304-11eb-9ab1-a223f85645c7.png)
