### ISSUE TITLE
Add support for Fluent Validation....

### ISSUE THREAD

**Issue by natiki** [abpframework/abp#953]
- Basically https://www.nuget.org/packages/Abp.FluentValidation as described [here](https://aspnetboilerplate.com/Pages/Documents/Validating-Data-Transfer-Objects?searchKey=validation#fluent-validation)

**Comment by hikalkan** [comment]
Sure, add it to backlog. Thanks.

**Comment by maliming** [comment]
@natiki I will check it out.
