### ISSUE TITLE
ISettingManager vs ISettingProvider in custom providers 

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#9530]
Hi,
we are trying to implement custom setting provider in our project, but I'm facing hard time to understand difference between ISettingManager and ISettingProvider and thier GetOrNullAsync() methods 

To understand requirement more:
we need to implement custom setting provider for "Country" (to save and get setting values per Country ), where providerKey is the countryId

Creating "CountrySettingValueProvider : **SettingValueProvider**" doesn't give us the ability to passing a parameter "providerKey" to GetOrNullAsync() method 

but by creating "CountrySettingProvider : **SettingManagementProvider**", we can add extension methods to get country Value
same as _settingManager.GetOrNullForCurrentTenantAsync()

the question is : Are there any future issue we will face if we used ISettingManager to get setting values from AppServices?

**Comment by maliming** [comment]
Please check the document of **Setting**.

https://docs.abp.io/en/abp/latest/Settings#reading-the-setting-values
https://docs.abp.io/en/abp/latest/Modules/Setting-Management#setting-management-providers
