### ISSUE TITLE
Volo.Authorization:010001: Authorization failed! Given policy has not granted.

### ISSUE THREAD

**Issue by GotzeWong** [abpframework/abp#9532]
How could I get valid AccessToken under Password GrantType?

When I request AccessToken directly via `/connect/token`, it does return access token 
![image](https://user-images.githubusercontent.com/7664030/124839088-b3e56b00-dfba-11eb-9b41-14cdf6232325.png)

The content of AccessToken is shown below.
![image](https://user-images.githubusercontent.com/7664030/124839226-f7d87000-dfba-11eb-9052-55b52223ad43.png)

But the token cannot access resources from IdentityService and return **401**.

![image](https://user-images.githubusercontent.com/7664030/124839357-3b32de80-dfbb-11eb-888b-0f15c463bac3.png)

Are there any methods or API helping me get the AccessToken to request the resources in user's permissions?

**Comment by maliming** [comment]
You can debug it to see the user of the access token and its permissions.

**Comment by GotzeWong** [comment]
Already fixed with UseJwtTokenMiddleware.
