### ISSUE TITLE
Why is BackgroundJob  designed to one JobArgs to one BackgroundJob Type？

### ISSUE THREAD

**Issue by yuzhigang** [abpframework/abp#9535]
The following examples are in the documentation：
```csharp
public class EmailSendingJob  : AsyncBackgroundJob<EmailSendingArgs>, ITransientDependency
{
   //...
}
```
If I have two jobs with EmailSendingArgs,  only one job is executed:
```csharp
public class AnotherEmailSendingJob  : AsyncBackgroundJob<EmailSendingArgs>, ITransientDependency
{
   //...
}
```
I checked the source code,  the key lines in AbpBackgroundJobOptions.cs:
```csharp
 public void AddJob(BackgroundJobConfiguration jobConfiguration)
        {
            _jobConfigurationsByArgsType[jobConfiguration.ArgsType] = jobConfiguration;
            _jobConfigurationsByName[jobConfiguration.JobName] = jobConfiguration;
        }
```
I think BackgroundJob was designed to one JobArgs to one BackgroundJob Type. Of course I can define two JobArgs, but args 
 construct is the same. Or I can combine Background Jobs logic, but I want to jobs are excuted in different threads. This is  inconvenient to apply in practice on actual projects.

**Comment by maliming** [comment]
hi

This is the current design, I don't think it is necessary to change it yet.
