### ISSUE TITLE
Can not map from given object

### ISSUE THREAD

**Issue by sortjiajun** [abpframework/abp#954]
![image](https://user-images.githubusercontent.com/16735741/55475531-c687d180-5646-11e9-9835-fd42f4f3534d.png)
![image](https://user-images.githubusercontent.com/16735741/55475555-d43d5700-5646-11e9-847d-456df4b79a02.png)
![image](https://user-images.githubusercontent.com/16735741/55475571-e15a4600-5646-11e9-8ca3-1f8f587189e2.png)
![image](https://user-images.githubusercontent.com/16735741/55475650-136ba800-5647-11e9-8162-94f2dba27b33.png)

I have no way to do this.

**Comment by maliming** [comment]
try `[DependsOn(typeof(AbpAutoMapperModule))]`

**Comment by sortjiajun** [comment]
> 尝试 `[DependsOn(typeof(AbpAutoMapperModule))]`


Thank you, it is working.

**Comment by zeroJackytao** [comment]
我也遇到了这个问题，但是用上面的方法没能解决
