### ISSUE TITLE
Blazor server sub-application can' t login

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#9546]
* Your **ABP Framework version**. **4.4.0-rc2**
* Your **User Interface** type **Blazor Server**
* Your database provider(EF Core)

I publish the app as a sub application in IIS, but can't login. I can open the login page, and  no errors when login but not show the username and no permissions for the pages.  

What I need to change for the code if I want publish as a sub application?

Thanks!

**Comment by realLiangshiwei** [comment]
Sorry, I don't know anything about your project.  please provide more information, steps to reproduce.

**Comment by juchunwei** [comment]
@realLiangshiwei 

1. I just download the startup template and publish it.  
2. Add a new application under an exists IIS website. 
3. I can open the home page of the sub-applicaiton and can open the login page,  and no errors after login, but still shows the login button on the homepage not the username.

**Comment by realLiangshiwei** [comment]
Check the document first: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-5.0&tabs=visual-studio#app-base-path

**Comment by juchunwei** [comment]
@realLiangshiwei 

I have tried it before. 

I added the code `app.UsePathBase("/cn");` in StartUp.cs

then tried ` <base href="~/cn/" />`  ` <base href="/cn/" />` and ` <base href="~/" />` but none of them working. still can not login.

the  ` <base href="~/cn/" />` will change the href to /cn/cn/ in the page source code.

**Comment by maliming** [comment]
You can try to publish the Blazor server without abp to sub-application.

**Comment by KevinBassaDevelopment** [comment]
Hi, we have the same issue, with a standard ABP blazor server application.
Version: 4.3.2

We migrated our ABP application from Blazor WASM to Server.

With visual studio, everything works perfectly fine.

Once published to IIS, after (successful) login, you get redirected to the application but have 0 permissions.

**Comment by juchunwei** [comment]
@maliming 

seems the standard Blazor server has the same issue.  Not sure I did anything wrong or it's a bug. :(

**Comment by maliming** [comment]
You can get help from the ASP NET Core team.
https://github.com/dotnet/aspnetcore
