### ISSUE TITLE
DisplayName in Localization

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#9551]
**How do I distinguish between the same properties in a localized configuration？**

I have 2 model as follow:

```csharp
class Foo{
    public string Name { get; set; }
}

class Bar{
   public string Name{get; set;}
}
```

And i only set one message in localization file as bellow:

```json
{
    "DisplayName:Name": "name"
}
```

But they are not the same. I want to set Foo.Name as 'FooName' and 'Bar.Name' as 'BarName' .

How should i do?

**Comment by maliming** [comment]
Maybe we can add some localization conventions.
