### ISSUE TITLE
External auth only

### ISSUE THREAD

**Issue by jhulbertpmn** [abpframework/abp#9558]
### Documentation

Please check the official documentation before asking questions: https://docs.abp.io

### GitHub Issues

GitHub issues are for bug reports, feature requests and other discussions about the framework.

If you're creating a bug/problem report, please include followings:

* ABP Framework version: 4.3
* UI: Blazor WASM
* Your database provider EFCore 

I’m starting a new project with abp using blazor wasm. I’m using CosmosDB for the database and this works well with efcore for everything except identity. 
I’d like to basically remove identity from the project and use Azure AD b2c exclusively for authentication so my application doesn’t have to store credentials at all. I’ve followed the Microsoft samples on setting up b2c for blazor wasm and that works fine, but I’m not quite clear on the best approach to remove identity and replace it with the b2c functionality in abp. I’d like to maintain things like audit logging but would like to redirect to the b2c login page instead of using the local login page, for example. Azure AD B2C handles this with user flows https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow 

Do you have recommendations on the best way to handle this in abp? I suppose the same concept would apply if I was using auth0 or Amazon Web Services cognito as additional examples

**Comment by JadynWong** [comment]
Set `Abp.Account.EnableLocalLogin` value `False`

https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L93

https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L44-L45

https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web.IdentityServer/Pages/Account/IdentityServerSupportedLoginModel.cs#L96-L101

**Comment by jhulbertpmn** [comment]
> Set `Abp.Account.EnableLocalLogin` value `False`
> 
> https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L93
> 
> https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L44-L45
> 
> https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web.IdentityServer/Pages/Account/IdentityServerSupportedLoginModel.cs#L96-L101

Thanks - glad to know about this setting!
I set this to false and confirmed it is applying after trying to login locally and receiving: 
UserFriendlyException: Local login is disabled for this application.

I followed the OpenIdConnect option at the bottom of the login page and was able to login with a user I had registered in Azure AD B2C. A couple additional questions (I may just not fully understand how this is supposed to behave):
1) When I start the app and click login I am still presented with the local login page and have to click the openid connect button. Is this expected, or should it see that I have local login disabled, one external provider setup and take me directly to that login?
2) I still have to have a user registered locally in the AbpUsers table - is it possible to completely outsource this to B2C (or another external provider) so I no longer need the AbpUsers table? Part of the challenge is that the identity related schema does not work correctly in Cosmos DB so I would like to be able to exclude it if I can get Azure AD B2C handling that functionality.

Thanks!

**Comment by JadynWong** [comment]
Hi

1.
It requires you to have only one external login provider.

https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L44-L45

2.
It seems not feasible, unless you do not use abp existing modules such as  `Identity`, ` Permission` and etc.  The permission system of abp depends on AbpUsers.

But if your external supplier claims include `email  claim`, the user will be automatically registered.

If your system does not need email, you can rewrite here.

https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L233-L266

**Comment by jhulbertpmn** [comment]
> Hi
> 
> 
> It requires you to have only one external login provider.
> 
> https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L44-L45
> 
> 
> It seems not feasible, unless you do not use abp existing modules such as `Identity`, ` Permission` and etc. The permission system of abp depends on AbpUsers.
> 
> But if your external supplier claims include `email claim`, the user will be automatically registered.
> 
> If your system does not need email, you can rewrite here.
> 
> https://github.com/abpframework/abp/blob/bc7c9819d86c3a6b231119910d9db5eec955c7e9/modules/account/src/Volo.Abp.Account.Web/Pages/Account/Login.cshtml.cs#L233-L266

Thanks again for the great info. I do just have the single external auth provider setup but I will work with that a little more to see if i can get it to behave like I want.
That makes sense regarding the abpusers table. I'll make sure to at least setup the external authentication to include the email claim so the registration happens automatically.
Thanks for pointing me in the right direction.

**Comment by jhulbertpmn** [comment]
After a lot of experimenting I finally resolved myself to needing to define the identity model separately to make it work in Cosmos - I just kept running into issue after issue with the concurrency token, navigation/relationships between entities and so on. 
However, I seemed to hit more issues when i started making changes to the model. For example, the Microsoft EF article on Cosmos at https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli describes setting up owned entities mapped to a json property. I was getting errors regarding IdentityUserOrganizationUnit not being owned, thus the navigation defined for it on IdentityUser is not valid. I followed the example from the MS article but then received "The type 'IdentityUserOrganizationUnit' cannot be marked as owned because a non-owned entity type with the same name already exists". I pulled the projects for abp identity and identityserver locally and added them to my solution, switched my references over to those projects instead of the nuget packages and changed the model code directly in Volo.Abp.Identity.EntityFrameworkCore. I commented out everything in the ConfigureIdentity method of IdentityDbContextModelBuilderExtensions to narrow down where IdentityUserOrganizationUnit is being added as non-owned and I still receive the error. I cannot find any other spot in the Abp solution where this is being added to the model - I assume it must be picked up be convention somewhere, but where? And what would be the correct approach to override it in a case like this?

**Comment by JadynWong** [comment]
Hi @jhulbertpmn 

Although I haven't used cosmos db in company projects. But as far as I know, it provides mongodb compatible api. Have you tried to use mongodb project as persistence?

**Comment by jhulbertpmn** [comment]
> Hi @jhulbertpmn
> 
> Although I haven't used cosmos db in company projects. But as far as I know, it provides mongodb compatible api. Have you tried to use mongodb project as persistence?

I did actually try that and had some success, unfortunately the rest of our projects use CosmosDB with the SQL API and that is what I need to use on this project too, although it was a good exercise to narrow down the other issues. It seems to be primarily an issue with the way the ef core model is built vs what the ef core cosmos provider will accept. In general we've had very good results using ef core with Cosmos, just not identity. I'm trying a different approach now using a custom storage provider for identity which does not involve ef core (https://github.com/Mobsites/Cosmos.Identity). That would be an acceptable solution if it works

**Comment by Raltagoon** [comment]
Is it available to set `Abp.Account.EnableLocalLogin` value  to `False` without adding source code of Account module?

**Comment by joernz** [comment]
> I do just have the single external auth provider setup but I will work with that a little more to see if i can get it to behave like I want. 

hi @jhulbertpmn,
how did you solve this? I also have only one external auth and `"Abp.Account.EnableLocalLogin": "False"` but get the exact same as you did. Thanks.

**Comment by lommez** [comment]
Hi @joernz  and @jhulbertpmn..
Did you both got any success to work only with on external login? Like Azure AD B2C?
