### ISSUE TITLE
Implement multitenancy on microservice demo

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#956]

**Comment by drony** [comment]
we have been waiting for this demo a long time. we need to make sure it works to start with abp

**Comment by hikalkan** [comment]
it will work :) No problem on the infrastructure, but this is a complicated case. Need to test all possible flows and probably work on it a bit.

**Comment by drony** [comment]
To start new projects with this framework, I have to prove my boss that micro service and multi-tenant architecture are working flawlesly and unfortunately I don't have time to learn it, if it works this demo, I'll start without wasting time and start learning. I'm pretty sure a lot of people are waiting for this scenario:)

Best Regards

**Comment by hikalkan** [comment]
>I'm pretty sure a lot of people are waiting for this scenario

I can agree on that, but can not drop currently prioritized works and immediately start to work on that, sorry :( I you don't have time, I can't provide a solution in a very short time.

**Comment by drony** [comment]
actually we don't expect a demo instantly. just put things right order. we'll wait :) thanks

**Comment by juicycleff** [comment]
I'm had some success doing this in my project, sorry I cant share the source code as its private. Maybe I can answer some questions. I'm not an expert in DotNet anymore, not programmed in it for 5 years plus, but I can share some insight

**Comment by drony** [comment]
i'm very sad right now:( postponed this feature to v0.20

**Comment by hikalkan** [comment]
Multenancy with microservice is complex. I don't say it is not important. It is hard and ABP will add a huge value on it. But we don't want to wait fundamental features and v1.0 release because of it. I hope this will be tested and stabilized before v1.0 release. If not, it will be a vert high priority issue after v1.0.

**Comment by la-digital** [comment]
Read https://github.com/ThreeMammals/Ocelot/issues/1001#issuecomment-539648158 and was wondering if we might get multi-tenancy on the microservice demo by then :)?

**Comment by hikalkan** [comment]
Hi all,

I am not able to continue to work on this. We should wait for Ocelot to support asp.net core 3.0. I hope it will be available in the next week, before we release ABP v1.0.

**Comment by la-digital** [comment]
Will we get this soon now that ocelot supports asp.net core 3.0?

**Comment by lockcd** [comment]
ocelot supports asp.net core 3.0
[ocelot 13.8.0](https://github.com/ThreeMammals/Ocelot/releases/tag/13.8.0)

**Comment by maliming** [comment]
@lockcd  The abp microservices example has been upgraded ocelot 13.8.0

**Comment by pranavpatil19** [comment]
again it module move to next road map... hopefully done come in 1.2 roadmap

**Comment by hikalkan** [comment]
I will work on this just after v1.1 release, but I didn't want to delay the v1.1 release of the framework because of a sample application.

**Comment by pranavpatil19** [comment]
again it module move to next road map

**Comment by hikalkan** [comment]
Yes, it moved again, sorry for it. But there was more significiant problems and you see that we needed to release an early 2.0 to fix the problems with some important changes.

This is a free and open source project. If this is important for you, please consider to send a PR. It would be appreciated.

**Comment by Tim1104** [comment]
I'm looking forward to this demo

**Comment by hikalkan** [comment]
@pranavpatil19 I want to write before you: yes, it is moved again to the next milestone since we will release 2.1 tomorrow and didn't have time to work on this yet, sorry.

**Comment by pranavpatil19** [comment]
No issue @hikalkan. Take your time .

**Comment by hikalkan** [comment]
I am actively working on this on that branch: https://github.com/abpframework/abp/tree/ms-demo-multi-tenant

Changing milestone to 2.3, but milestone has no meaning with this sample, since it is not something released. I will continue to work on.

**Comment by alan-albuquerque** [comment]
Why are you guys talking like that if it's an open source project? These things takes time and if you really need it, go ahead and do it by yourself, then submit a pull request with it. 

Anyway, thanks a lot @hikalkan for your work on it. It's a great framework that I'm really thinking to use in my project.
