### ISSUE TITLE
[Question]High memory usage with initial project template

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#9571]
ABP version
4.3.3
create project with `abp new TestDemo -t app -u angular -o TestDemo` by abp.cli
profile this project with dotmemory
![屏幕截图 2021-07-12 160736](https://user-images.githubusercontent.com/19605145/125253234-cb5e8400-e32b-11eb-83a2-c571f629359f.png)
 366MB memory used!!!! Is this a normal situation?

**Comment by realLiangshiwei** [comment]
An empty MVC application memory used is `120MB`.

![image](https://user-images.githubusercontent.com/16813853/125273221-47ae9280-e33f-11eb-8654-e87e1a8f2e51.png)


ABP has a lot of [features](https://abp.io/features). so `366MB` memory used is reasonable
