### ISSUE TITLE
Permissions in a distributed ecosystem

### ISSUE THREAD

**Issue by NecatiMeral** [abpframework/abp#9578]
Hi everyone,

I am thinking about how to handle multiple independant applications and managing permissions.

Let's take the following scenario of two independant applications (NG-UI, HttpApi and a dedicated database).

![Untitled-1](https://user-images.githubusercontent.com/7882753/125339904-1c816e80-e352-11eb-939a-d6ab1584ee79.png)

**Goals:**
- The environment should be scalable, so we can add and deploy more applications or replace applications.
- The applications should be independant from another. If a application requires another, it should be acessed through a internal gateway; I've omitted this feature for the sake of simplicity.
- Updating one application shouldn't require a update of another service (except breaking changes in inter-process communication)

**Questions:**
- Q: How should one implement the permissions system?
  - Should every application maintain it's own permissions? Is there a way to make the permission managenent in a centralized fashion?

**Comment by enisn** [comment]
Hi @NecatiMeral That is a good case to think about it.

We're currently working on a Micro-Service demo similar to your example and the project is [eShopOnAbp](https://github.com/abpframework/eShopOnAbp). 

As you ask `Should every application maintain its own permissions?`, you can see the answer is **YES** but managing can be centralized. 

You can run the demo app by following [this article](https://blog.abp.io/abp/Introducing-the-eShopOnAbp-Project). This is a demo about what we do in that case

**Comment by NecatiMeral** [comment]
Hi @enisn,

thanks for your answer. I just saw your article about the solution but haven't much spare time to evaluate. But I definetly will check it out!

Am I right by suspecting the following? 

To have a centralized identity and permission management, the changes about users, roles and permissions must be synchronized by using a distributed event bus or dedicated synchronizers from the upstream (identity-server-admin-backend) to the separate applications?
