### ISSUE TITLE
How to remove all or parts of the  Administration Menu in Blazor?

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#9579]
I´m trying to remove the [Administration Menu](https://docs.abp.io/en/abp/latest/UI/Blazor/Navigation-Menu#the-administration-menu). 

[My requirement](https://support.abp.io/QA/Questions/1084/Architectural-question-on-whether-to-choose-Multi-Tenancy-or-not#answer-0e463253-14d5-486e-ffa5-39fd6ae413ac) is that certain users (not host or tenants) are not supposed to have access to parts/all of it.

It shows up even though I completely remove the `ConfigureMainMenuAsync` method in my MenuContributor or try using `context.Menu.TryRemoveMenuItem("Administration");`

So any ideas?

![image](https://user-images.githubusercontent.com/2386572/125353273-d9bf9680-e351-11eb-9510-1f6ff43fe3da.png)

* Your **ABP Framework version**:  4.3.2
* Your **User Interface** type: Blazor
* Your database provider: EF Core

**Comment by maliming** [comment]
Can you try this?

```cs
var administration = context.Menu.GetAdministration();
context.Menu.Items.Remove(administration);
```

**Comment by sturlath** [comment]
It worked (removed the whole Admin menu). I can work with that for now.

But is it all or nothing or can I remove (and access controlled) the submenus? Maybe that doesn´t make sense that the user has access to e.g. Audit Logs or Settings and nothing else?
