### ISSUE TITLE
Remove gulpfile from the MVC UI projects

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#9584]
Since we now have the `abp install-libs` command. Also, check the documentation to offer the new usage instead of `yarn && gulp`.

**Comment by NecatiMeral** [comment]
This change requires our CI agents to have the ABP CLI installed. I personally feel like the more native way of `yarn && gulp` is more suitable for CI/CD scenarios. 

Will the old behavior still be supported?

**Comment by hikalkan** [comment]
We won't maintain the old gulp file, but not remove it from the npm package. However, removing it from new startup templates beginning from v5.0 (end of this year).
