### ISSUE TITLE
Menu items overlap when I download the docs module to the application with suite

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/abp#9589]
Related https://support.abp.io/QA/Questions/1567/Docs-Menu-Formatting

- ABP Framework version: 4.4.0-rc.2
- UI type: Blazor Server
- DB provider: EF Core
- Docs location: GitHub

<img width="1920" alt="Screen Shot 2021-07-14 at 10 17 44" src="https://user-images.githubusercontent.com/31216880/125585412-28fe5fe4-2e0b-4801-87ac-8f07328e24a5.png">

**Comment by yekalkan** [comment]
dupicate of https://github.com/volosoft/volo/issues/7206
