### ISSUE TITLE
Use the configs from AbpKafkaOptions 

### ISSUE THREAD

**Issue by tarikdevapp** [abpframework/abp#9598]
**latest version**.
**MVC** 
**Database provider(EF Core)**
This code here doesn't work because...
`var config = options.Value.ConfigureConsumer;
 using (var consumer = new ConsumerBuilder<Ignore, string>(config).Build())
{
//Consume messages
}`
The config needs to be of type ConsumerConfig while the one from the AbpKafkaOption is of type action<ConsumerConfig>. 
 
#abp #kafka

**Comment by realLiangshiwei** [comment]
See https://docs.abp.io/en/abp/latest/Distributed-Event-Bus-Kafka-Integration#the-options-classes

**Comment by tarikdevapp** [comment]
That's not what I am looking for.

**Comment by realLiangshiwei** [comment]
`ConfigureConsumer` just a delegate method and that allows you to customize `ConsumerConfig`.

I can't get your point, but however, you can create your own `ConsumerConfig`.

**Comment by tarikdevapp** [comment]
Thank you for the response, however, I'm neither trying to customize nor trying to create my own ConsumerConfig. 
I want to use your AbpKafkaOptions to produce and consume messages, but I don't want to use "distrubited event bus kafka".   
I've looked through your docs and kafka samples with no result.  
I'm currently using this 
`  var config = new ConsumerConfig
            {
                Acks = Acks.All,
                BootstrapServers = "localhost:9092",
                AutoOffsetReset = AutoOffsetReset.Earliest,
                GroupId = "KafkaGroup"
            };`
How can I use AbpKafkaOptions configs instead of the code above?
