### ISSUE TITLE
Tiered project Host module enable Cookie authentication

### ISSUE THREAD

**Issue by ArneCools** [abpframework/abp#9599]
* Version 4.3.0
* Blazor server Tiered project
* EF Core

I'm trying to open a controller page from the Host module with the [Autorized] attribute. But I always get a 401, even though I'm logged in and the cookies are present
```
[Authorize]
    public class TestController : AbpController
    {
        [HttpGet("test")]
        public IActionResult Test()
        {
            return Ok("test");
        }
    }
```
This is what my ConfigureAuthentication() looks like:
```
context.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.RequireHttpsMetadata = Convert.ToBoolean(configuration["AuthServer:RequireHttpsMetadata"]);
                    options.Audience = "CrsContact";
                });
```

I tried replacing it with:
```
context.Services.AddAuthentication(options =>
            {
                //options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
                .AddJwtBearer(options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.RequireHttpsMetadata = Convert.ToBoolean(configuration["AuthServer:RequireHttpsMetadata"]);
                    options.Audience = "CrsContact";
                })
                .AddCookie("Cookies", options =>
                {
                    options.ExpireTimeSpan = TimeSpan.FromDays(365);
                }).AddAbpOpenIdConnect("oidc", options =>
                {
                    options.Authority = configuration["AuthServer:Authority"];
                    options.RequireHttpsMetadata = Convert.ToBoolean(configuration["AuthServer:RequireHttpsMetadata"]);
                    options.ResponseType = OpenIdConnectResponseType.CodeIdToken;

                    options.ClientId = configuration["AuthServer:ClientId"];
                    options.ClientSecret = configuration["AuthServer:ClientSecret"];

                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;

                    options.Scope.Add("role");
                    options.Scope.Add("email");
                    options.Scope.Add("phone");
                    options.Scope.Add("CrsContact");
                });
```

But then my Blazor server front-end throws an error.

So my question is:
How do I enable both Cookie & Jwt authentication.

**Comment by maliming** [comment]
hi 

* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by ArneCools** [comment]
- Exception message and stack trace if available (check the logs).
[12:54:10 INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
[12:54:10 INF] AuthenticationScheme: Bearer was challenged.

- Steps needed to reproduce the problem.

1. Create new Blazor server tiered project
2. Create controller class TestController.cs in HttpApi module
[Authorize]
    public class TestController : AbpController
    {
        [HttpGet("test")]
        public IActionResult Test()
        {
            return Ok("test");
        }
    }
3. go to localhost:[portHttpAPIHostProject]/test
4. You get a 401 instead of a redirect to login


The reason I want to host certain pages on the HttpApi.Host port instead of Blazor Server port is because I have a Quartz manager running to running to manage my cron jobs

**Comment by maliming** [comment]
You should continue to use `JwtBearerDefaults.AuthenticationScheme` as the `DefaultScheme`, and use the cookies scheme in your controller, or customize the policy.

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-5.0#selecting-the-scheme-with-policies
