### ISSUE TITLE
AbstractKeyCrudAppService - UpdateAsync

### ISSUE THREAD

**Issue by d-oit** [abpframework/abp#9601]
* Your **ABP Framework version**. -> **4.3.3**

* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI -> **Blazor**
* Your database provider(EF Core/MongoDB) -> **EfCore**

Why do you get a existing record with includeDetails = true ? Usually you map the id or map a navigation property. 
Any reason for that? 

 public virtual async Task<TGetOutputDto> UpdateAsync(TKey id, TUpdateInput input)
        {
            await CheckUpdatePolicyAsync();

            var entity = await GetEntityByIdAsync(id); -> _**var entity = await Repository.GetAsync(id, false);**_
            //TODO: Check if input has id different than given id and normalize if it's default value, throw ex otherwise
            await MapToEntityAsync(input, entity);
            await Repository.UpdateAsync(entity, autoSave: true);

            return await MapToGetOutputDtoAsync(entity);
        }

**Comment by maliming** [comment]
`includeDetails = false` won't load the navigation properties of the entiiy.

**Comment by d-oit** [comment]
When do you need navigation properties for update? 
You override with automapper if available or update the ForeignKey (Id). 

Do you have any use case for the current logic? I try to understand what's the reason for the current implementation.

**Comment by enisn** [comment]
Hi @d-oit 

> *"Aggregate is a pattern in Domain-Driven Design. A DDD aggregate is a cluster of domain objects that can be treated as a single unit..."*

So AggregateRoots has to be treated as a single unit, that means you have to Read, Create and Update AggregateRoot with its related entities(Naviagation Properties at your situation.)

I highly recommend to you to read the [Aggregate Root Documentation](https://docs.abp.io/en/abp/latest/Entities#aggregateroot-class) for more.

**Comment by d-oit** [comment]
@enisn Thanks for your reply. I asking about this line:

` var entity = await GetEntityByIdAsync(id);`

the current abp code get - ef core - ALL defined include from the database. 

Then map with
 `await MapToEntityAsync(input, entity);` 
**input** has id (foreignkey) or the navigation property class with changes. 

so why do you need to get all include from the database first and assign afterwards -> MapToEntity
Was search for possible perform problem and found this logic. I changed it already for my case. 

You could close the issue if it's no problem for abp or other user. 

Haven't found anything about DDD and get all entity (with include) before update with ef core:
https://www.thereformedprogrammer.net/creating-domain-driven-design-entity-classes-with-entity-framework-core/


https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model#encapsulate-data-in-the-domain-entities
