### ISSUE TITLE
Get datas of soft deleted!

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#9604]
I have a entity which not set `DbSet<?>` Property in DbContext. Then when i use `Repository.GetAsync(id)`, i get the deleted item!

```csharp
public class Foo : FullAuditedAggregateRoot<Guid>
{
    // ...
}

public class BasicSettingDbContext : AbpDbContext<BasicSettingDbContext>
{
    // without this line.
    public DbSet<Foo> Fooes { get; set; }
}
```

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by weiwxg** [comment]
- ABP Framework version 4.3.3
- No User Interface
- EF Core

**Comment by maliming** [comment]
Full steps are needed to reproduce the problem.

**Comment by weiwxg** [comment]
```csharp
// entity
public class Foo : FullAuditedAggregateRoot<Guid>
{
    
}
// dbcontext
public class BasicSettingDbContext : AbpDbContext<BasicSettingDbContext>
{
    // without this line.
    // public DbSet<Foo> Fooes { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        
        builder.Entity<Foo>(b =>
        {
            b.ToTable(BasicSettingConsts.DbTablePrefix + "Fooes", BasicSettingConsts.DbSchema);
            b.ConfigureByConvention();

        });
    }
}

// appservice
public class FooAppService : IFooAppService
{
    public async Task DeleteAsync(Guid id)
    {
        return repository.DeleteAsync(id);
    }

    public async Task<FooDto> GetAsync(Guid id)
    {
        return ObjectMapper.Map<Foo, FooDto>(await repository.GetAsync(id));
    }
}
```

Firstly, i call `HttpGet` `localhost:5201/api/foos`, return 1 items:
```json
{
   "id": "39fdbee9-14b5-365b-69a0-360cf23ba326",
   "isDeleted": 0,
   "DeleterId": null,
   "DeletionTime": null
}
```

Then, i call `HttpDelete` `localhost:5201/api/foos/39fdbee9-14b5-365b-69a0-360cf23ba326`, return 204.

Obviously, the data is deleted. 

However, when I call the `HttpGet` `localhost:5201/api/foos` again, I can find the deleted data

```json
{
   "id": "39fdbee9-14b5-365b-69a0-360cf23ba326",
   "isDeleted": 1,
   "DeleterId": "39fd76e0-8e06-6ced-8a88-8f605975b625",
   "DeletionTime": "2021-07-16 11:44:40.000"
}
```

**Comment by maliming** [comment]
Abp will get `EntityTypes` by `DbSet<>`, so you have to add it to `AbpDbContextAbpDbContext`

https://github.com/abpframework/abp/blob/63417727af1322f5e4e3756fd004b11225ca5f34/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/DbContextHelper.cs#L13
