### ISSUE TITLE
How to configure the default format of guid for entities' id

### ISSUE THREAD

**Issue by EZevan** [abpframework/abp#9611]
### How to configure the default format of guid for entities' id

* I just wonder that if it is possible to change the default format  of guid for entities'/tables' id. For instance, the default guid is **39fc4539-21bf-a90c-1fe1-13973c285a6f**, but i hope it can be **39fc453921bfa90c1fe113973c285a6f** by some specified configuration.

Hope hear from you soon,thanks a lot!

**Comment by maliming** [comment]
For an entity, its primary key type is GUID. There is no concept of format.
For database tables you can refer to https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations
