### ISSUE TITLE
BasicAggregateRoot<TKey> extends Entity<TKey>: Type 'Entity' is not generic!

### ISSUE THREAD

**Issue by idreeshaddad** [abpframework/abp#9613]
ABP CLI: v4.3.3 (Stable)
Angular: v11.2.10.
After generate-proxy and serving the Angular code I've started getting this error: 

![image](https://user-images.githubusercontent.com/2285974/126045789-ed567f26-e747-4e0e-a755-aa308f70803a.png)

**Comment by maliming** [comment]
hi

* Steps needed to **reproduce** the problem.

**Comment by idreeshaddad** [comment]
Text book code:
Domain:
![1](https://user-images.githubusercontent.com/2285974/126068102-73a8a20e-7598-43a4-891d-336ef793e5a6.png)
Application Service:
![2](https://user-images.githubusercontent.com/2285974/126068109-6ddec757-f26d-413a-a28d-ea95075c3bfb.png)
Dto:
![3](https://user-images.githubusercontent.com/2285974/126068113-d8404349-b944-4677-b3b9-9beb7ae7f1ed.png)

Then after generating the proxies and running the Angular app I get those errors:

 
![4](https://user-images.githubusercontent.com/2285974/126068209-3302042c-8cf3-42d2-ab7e-bbba944e70a4.png)
and:
![5](https://user-images.githubusercontent.com/2285974/126068221-630eb44e-0285-4bf1-947a-3ceec286acac.png)

**Comment by maliming** [comment]
hi @mehmet-erim  Can you help to check?

**Comment by mehmet-erim** [comment]
Hi @idreeshaddad,

Please share the `generate-proxy.json` so that we can find the source of the problem.

**Comment by idreeshaddad** [comment]
> generate-proxy.json

Hello @mehmet-erim,
Yes sure. Can you provide me with an email to send it to? I don't want to post all that information in public.

**Comment by mehmet-erim** [comment]
You can email info@abp.io. Please mention me and add the issue link to the email.

BTW, you can modify the Entity interface as a workaround to fix the error:

```
export interface Entity<TKey> { }
```

Actually, you do not need these interfaces. You can import the interfaces which you need from `@abp/ng.core`.

**Comment by idreeshaddad** [comment]
> BTW, you can modify the Entity interface as a workaround to fix the error:
> 
> ```
> export interface Entity<TKey> { }
> ```

I thought it would, but it didn't work:
![image](https://user-images.githubusercontent.com/2285974/127162735-7e5fa04f-b574-468b-9212-8c81bf3f96b6.png)

It seems to me that Domains are being leaked from an application service?

I sent you the `generate-proxy.json` file to the info email.
Thank you in advance brother.

**Comment by idreeshaddad** [comment]
I've just found the problem.
So there was an endpoint returning a Domain instead of a Dto after all.
I've replaced it with the Dto, and now it is working just fine.
