### ISSUE TITLE
Is Volo.Abp.BlazoriseUI compatible with server side blazor?

### ISSUE THREAD

**Issue by medbour** [abpframework/abp#9617]
### Discussed in https://github.com/abpframework/abp/discussions/7442

<div type='discussions-op-text'>

<sup>Originally posted by **wocar** January 25, 2021</sup>
Hello I see that 

`Volo.Abp.BlazoriseUI`

has a dependency on:

`Volo.Abp.AspNetCore.Components.WebAssembly`

Is the Abp.BlazoriseUI package compatible with server side blazor?

Thank you! 
</div>

**Comment by realLiangshiwei** [comment]
https://github.com/abpframework/abp/blob/c15c2210142281fabdad7877b8225e5ea3081b54/framework/src/Volo.Abp.BlazoriseUI/AbpBlazoriseModule.cs#L11

`Volo.Abp.AspNetCore.Components.Web` instead of `Volo.Abp.AspNetCore.Components.WebAssembly`

Yes, it is compatible with server-side blazor
