### ISSUE TITLE
How to implement token-based Authentication in ABP? Or How to use

### ISSUE THREAD

**Issue by GotzeWong** [abpframework/abp#9618]
I'm sorry to post the silly question maybe but stuck for a few days.

Does ABP support token-based authentication for the Vue front-end by default?

If so, how could I request a valid access token in the right way?
If not, are there any steps to support token-based authentication?

I tried to request tokens via '/connect/token' and only got the standard payload without user or role info.
I found ASP.NET ZERO supports to request toke via `/api/TokenAuth/Authenticate`. 

Really appreciate any suggestions.

**Comment by realLiangshiwei** [comment]
Angular UI  also uses `/connect/token` endpoint, you can check it.

**Comment by GotzeWong** [comment]
Fixed with UseJwtTokenMiddleware.
