### ISSUE TITLE
Owned Entity Not Updated After Update Repository

### ISSUE THREAD

**Issue by slarkerino** [abpframework/abp#9620]
Owned properties update properly when using appservice. However, when I try to update an owned entity using repository, it resulted in success but the location property is not updated. I have tried to update other properties that is not an owned property and it works.
![image](https://user-images.githubusercontent.com/7014849/126291044-587a68cf-d6d0-40e3-b1c7-b7cc5d13b440.png)
![image](https://user-images.githubusercontent.com/7014849/126291174-426b7f32-ff52-4844-9324-31f103bd955c.png)
![image](https://user-images.githubusercontent.com/7014849/126291286-745a91c6-231c-4690-98b9-ee101f63b94c.png)

**Comment by maliming** [comment]
You can try to use EF Core without abp first.
