### ISSUE TITLE
How I fixed "No theme registered! Use AbpThemingOptions to register themes" ?

### ISSUE THREAD

**Issue by rwecho** [abpframework/abp#9624]
#6627
#2679
like other's posts, when I publish the HttpApi.Host, I got the “No theme registered exception” when access 401 API.

final I solved with remove code :
``` csharp
        if (!env.IsDevelopment())
        {
            app.UseErrorPage();
        }
```

![image](https://user-images.githubusercontent.com/8048753/126458765-967e9281-c558-4acf-8691-a795827cf73a.png)

Must the error page need a theme?

To reproduce it, you can create a tiered solution then access /error router of httpapi

**Comment by realLiangshiwei** [comment]
I will check it out

**Comment by realLiangshiwei** [comment]
I think `app.UseErrorPage();`  is unnecessary for `HttpApi.Host`. we can remove it.
