### ISSUE TITLE
**abp**  exception on suite generated UI

### ISSUE THREAD

**Issue by melfahn** [abpframework/abp#9627]

**Comment by melfahn** [comment]
-- 4.3.3
-- MVC
-- EF  CORE

Getting an exception using any entity UI.  this comes up immediately on the initial grid

![Screenshot 2021-07-21 124735](https://user-images.githubusercontent.com/5402008/126527435-b3156da8-c14a-47e2-8875-c58c96cf9a61.png)

**Comment by maliming** [comment]
hi @melfahn 

Please get help on support website.
https://support.abp.io/QA/Questions/New

**Comment by melfahn** [comment]
I would if I could. Seems like I should be able to report a bug without a current commercial license
![Screenshot 2021-07-21 204435](https://user-images.githubusercontent.com/5402008/126576773-5ad84291-31d8-4b10-bd36-4ce73f508e55.png)

**Comment by maliming** [comment]
hi @melfahn 

Is your commercial license expired?
