### ISSUE TITLE
A console app can't use multi different types database， like sql server & PostgreSQL

### ISSUE THREAD

**Issue by muzizongheng** [abpframework/abp#9629]
ABP Framework version： 4.3.3，
> Volo.Abp.EntityFrameworkCore.PostgreSql,  Volo.Abp.EntityFrameworkCore.SqlServer

User Interface： Console
Your database provider：EFCore

Steps to reproduce the problem:
1. use abp cli to create console, 
> abp new Acme.MyConsoleApp -t console
2. add **sqlserver** for the **first AbpModule** , according to https://docs.abp.io/zh-Hans/abp/latest/Entity-Framework-Core
> add dependson & UseSqlServer()
3.  add new DbConext and set connectionStringName
4. test the first Dbconext to local Sql server, it's ok.
5. create a new AbpModule , the **second AbpModule**  used **Postgresql**. According to https://docs.abp.io/zh-Hans/abp/latest/Entity-Framework-Core-PostgreSQL
6.  config Program.cs: 
services.AddApplication\<SecondAbpModule\>();
7. run program, and it is failed.
8. **Log**: System.ArgumentException: Keyword not supported: data source (Parameter 'keyword')
> root cause: the first AbpModule  used  postgresql's connection string rather than sql server.

**Comment by maliming** [comment]
Only one database provider can be used in a project. Microservices support different database providers

**Comment by maliming** [comment]
HI

You can try to configure the `dbcontext` separately.

```cs
Configure<AbpDbContextOptions>(options =>
{
    options.UseSqlServer<SQLDbConext>();
    options.UsePostgreSql<PostgreSQLDbConext>();
});
```

https://docs.abp.io/en/abp/latest/Connection-Strings

**Comment by muzizongheng** [comment]
> HI
> 
> You can try to configure the `dbcontext` separately.
> 
> ```cs
> Configure<AbpDbContextOptions>(options =>
> {
>     options.UseSqlServer<SQLDbConext>();
>     options.UsePostgreSql<PostgreSQLDbConext>();
> });
> ```
> 
> https://docs.abp.io/en/abp/latest/Connection-Strings

it works fine!  thank you!

last solution:
pass dbcontext class to UseSqlServer template in different abpmodule.
FirstAbpModule.cs
```CSharp

            Configure<AbpDbContextOptions>(options =>
            {
                options.UseSqlServer<SqlServerDbContext>();
            });
```

SecondAbpModule.cs
```CSharp

            Configure<AbpDbContextOptions>(options =>
            {
                options.UseNpgsql<PgSqlDbContext>();
            });
```
