### ISSUE TITLE
Missing Package "Microsoft.EntityFrameworkCore.Design" in Acme.BookStore Sample

### ISSUE THREAD

**Issue by barbarosyurttagul** [abpframework/abp#963]
When you try to execute the Add-Migration "Created_Book_Entity" through Package Manager Console in Acme.BookStore tutorial sample project, it gives the error "**Microsoft.EntityFrameworkCore.Design**" package is needed. To prevent this, you must ensure that "Acme.BookStore.EntityFrameworkCore.DbMigrations" project comes with "**Microsoft.EntityFrameworkCore.Design**" package. The tutorial's link is below:

[https://github.com/abpframework/abp/blob/master/docs/en/Tutorials/AspNetCore-Mvc/Part-I.md](url)

**Comment by maliming** [comment]
If you use **dotnet ef** cli you need to install it manually.

**Comment by barbarosyurttagul** [comment]
After I created Database with "Update Database" command, it worked.
