### ISSUE TITLE
abp4.3   angular  remove or hidden claims dropdownitem

### ISSUE THREAD

**Issue by zhangxd-1222** [abpframework/abp#9632]
hi，abp commercial
![image](https://user-images.githubusercontent.com/6479812/126601579-b2c95f4f-d3a3-4912-9244-c8243a88a651.png)
I want to hide the dropdown button,so what should i do
thank you!

**Comment by maliming** [comment]
hi

Please get help on the support website.
https://support.abp.io/QA/Questions/New
