### ISSUE TITLE
Web Project to Host project API CALL from Controller (Web Project controller to API controller method call)

### ISSUE THREAD

**Issue by prajapati-ritesh** [abpframework/abp#9639]
Hi,

Can anyone please suggest the flow to call Host Project Controller Method from Web Project Controller?
If possible attach the solution as well.
Thanks & regards,
Ritesh Prajapati.

**Comment by maliming** [comment]
This seems to have nothing to do with abp.

If they are controllers of application services, you can check https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients
