### ISSUE TITLE
.Net 5.0 Restore issue on Linux 

### ISSUE THREAD

**Issue by radwan-badr** [abpframework/abp#9640]
Package Volo.Abp.IdentityServer.Domain 4.3.3 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package Volo.Abp.IdentityServer.Domain 4.3.3 supports: net50 (.NETFramework,Version=v5.0)

**this issue happen when trying to restore ABP project in Linux environment**

**Comment by maliming** [comment]
Please install the SDK or runtime of net 5.0 https://dotnet.microsoft.com/download/dotnet/5.0
