### ISSUE TITLE
Change default admin role when seeding data

### ISSUE THREAD

**Issue by Vayth** [abpframework/abp#9641]
Is there a way to rename the default `admin` role to something else, e.g. `system admin` or `super admin` ? In some contexts , admin may refer to task administrator or maybe other administrator and some people might use that for something else.

Seems like the [data seeder](https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionDataSeedContributor.cs) is hardcoded to `admin`.
```
        public virtual Task SeedAsync(DataSeedContext context)
        {
            var multiTenancySide = CurrentTenant.GetMultiTenancySide();
            var permissionNames = PermissionDefinitionManager
                .GetPermissions()
                .Where(p => p.MultiTenancySide.HasFlag(multiTenancySide))
                .Where(p => !p.Providers.Any() || p.Providers.Contains(RolePermissionValueProvider.ProviderName))
                .Select(p => p.Name)
                .ToArray();

            return PermissionDataSeeder.SeedAsync(
                RolePermissionValueProvider.ProviderName,
                "admin",
                permissionNames,
                context?.TenantId
            );
        }
```
Would it be possible to make it optional like seeding default admin name and default admin password via seeding context?

This question was submitted on [stackoverflow](https://stackoverflow.com/questions/68489892/rename-default-admin-role-in-abp-framework) before since I thought it was more of a usage question, but after a second thought, I think it's more about the framework

**Comment by fileman** [comment]
As I [replied](https://stackoverflow.com/questions/68489892/rename-default-admin-role-in-abp-framework/68508429#68508429) on stackoverflow, since is virtual, have you tried to override it?
