### ISSUE TITLE
Multi-threaded safety

### ISSUE THREAD

**Issue by tangdf** [abpframework/abp#9644]
https://github.com/abpframework/abp/blob/5879885deedfe4aadc529cf9c29aa95aec13e342/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/RabbitMqMessageConsumer.cs#L132-L139

https://github.com/abpframework/abp/blob/5879885deedfe4aadc529cf9c29aa95aec13e342/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/RabbitMqMessageConsumer.cs#L134

Whether thread safety needs to be considered here？

**Comment by maliming** [comment]
See https://github.com/abpframework/abp/blob/5879885dee/framework/src/Volo.Abp.Threading/Volo/Abp/Threading/AbpAsyncTimer.cs#L87

**Comment by tangdf** [comment]
Multiple threads access the property _Channel_:
- Which is not thread-safe
- The property _IsOpen_ of _Channel_, which is not thread-safe.
