### ISSUE TITLE
Consider adding a parameter that indicates whether or not to trace in the GetQueryableAsync method.

### ISSUE THREAD

**Issue by evictorel** [abpframework/abp#9652]
Related to #1848, and #6962, it would be very good if the GetQueryableAsync / WithDetailsAsync method has a parameter that indicates the tracking of entities to improve performance.

Now that in the next versions IRepository does not inherit from IQueryable, could it be viable?

In this way, the implementations of CreateFilteredQueryAsync in the CrudAppService, and others could also be updated.

**Comment by maliming** [comment]
hi

This is a unique feature of EF Core. Maybe it shouldn't exist in the abstract Repository.

**Comment by evictorel** [comment]
> hi
> 
> This is a unique feature of EF Core. Maybe it shouldn't exist in the abstract Repository.

Yes, with DDD there is a way to extend the behavior of the EntityFrameworkCore project?, And that the domain uses it.

I am currently overwritten the most important repositories, to decrease the response time (in my case it doubles with tracking) with:

`options.AddRepository<Question, EfCoreQuestionRepository>();`

Thanks

**Comment by maliming** [comment]
> I am currently overwritten the most important repositories,

Can you share your code?

**Comment by evictorel** [comment]
> > I am currently overwritten the most important repositories,
> 
> Can you share your code?

Sorry, it was a bit confusing. These repositories are the most important thing for the project, and as most are similar, we are overwritten WithDetailsAsync, which is the only method we plan to use for reading only:

```
public override async Task<IQueryable<T>> WithDetailsAsync()
{
    return (await GetQueryableAsync()).AsNoTracking().IncludeDetails();
}
```

**Comment by maliming** [comment]
I did not find a suitable place to add non-tracking parameters.

**Comment by evictorel** [comment]
> I did not find a suitable place to add non-tracking parameters.

No problem! We will see if in the future we can implement another Repository (If possible), with non-tracking methods, it may be an anti-pattern, but we only use EFCore.

For the moment, we find [this possibility](https://docs.abp.io/en/abp/latest/Entity-Framework-Core#set-default-repository-classes) today, to avoid overwriting one by one..

Thanks

**Comment by muratyuceer** [comment]
@maliming maybe you can abstract it like this
define IRepositoryProviderQueryOptions
store options as key value which implement class can take them from ctor and pass to repo methods. Check if asnotracking key value exist apply it to ef core repo etc..
