### ISSUE TITLE
how to save after response

### ISSUE THREAD

**Issue by wingqing1314** [abpframework/abp#9661]
`public void CreateLoginRecord(LoginRecord info)
        {
            Task.Factory.StartNew(async () =>
            {
                using (var uow = _unitOfWorkManager.Begin(requiresNew: true, isTransactional: false))
                {
                    try
                    {
                        if (info.TerminalNo.IsNullOrWhiteSpace()) info.SetTerminalNo("0");
                        var data = await _loginRep.FindAsync(p => p.LoginNo.Equals(info.LoginNo) && p.TerminalNo.Equals(info.TerminalNo));
                        if (data == null)
                        {
                            info.SetLoginTime();
                            await _loginRep.InsertAsync(info);
                        }
                        else
                        {
                            data.SetLoginTime();
                            await _loginRep.UpdateAsync(data);
                        }
                        await uow.SaveChangesAsync();
                        await uow.CompleteAsync();
                    }
                    catch (Exception ex)
                    {
                        await uow.RollbackAsync();
                    }
                }
            });
        }`
throw a exception :Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

**Comment by berkansasmaz** [comment]
Duplicate: #9660
