### ISSUE TITLE
For microservice-to-microservice communications is there any need to write client code to request the token?

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#9662]
For **microservice-to-microservice communications**, where t**hey share the same Auth/Identity server,** is there any need to write client code to request the token? Or everything will be handled by Identity Server?

Is there a config-driven approach?

**The following works well** when **microservice 1** requests an access token from a **common Idenity Server** to allow it to call **microservice 2**

I just don't know if it is the right approach or if this can be configured through claims, scopes etc

``` C#
//... some using statements
using IdentityModel.Client;

//.. some static class

       public static async Task<string> GetAccessToken()
        {
            var client = new HttpClient();
            client.DefaultRequestHeaders.Add("TestHeader", "1");
           
            var request new IdentityModel.Client.ClientCredentialsTokenRequest
                {
                    Address = "The-Identity-Server-Url",
                    ClientId = "The-Client-Id",
                    ClientSecret = "The-Client-Secret",
                    GrantType = "The-Grant-Type",
                    Scope = "The-Scope"
                };

            var response= await client.RequestClientCredentialsTokenAsync(request);

            if (response.IsError)
            {
               Console.WriteLine($"Error requesting client token: {response.Error}");
                return null;
            }

            // return access token
            return tokenResponse.AccessToken;
       }
```

Using the ABP architecture diagram as an example, do I need client code above for 1 to communicate with 2, or is there an `appsettings` config or ABP DB config or app start-up config? :

![image](https://user-images.githubusercontent.com/8109147/127143155-6e45f312-78c8-47ea-bfc5-2a305ec5b61e.png)

ABP 4.3
Database provider EF Core

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/eShopOnAbp

![image](https://user-images.githubusercontent.com/16813853/127148099-ae4edaeb-66ff-4ba0-a1a4-81dfbe5d953d.png)

https://docs.abp.io/en/commercial/latest/startup-templates/microservice/gateways#internal-gateway
