### ISSUE TITLE
How can I log  login?

### ISSUE THREAD

**Issue by laosandegudai** [abpframework/abp#9674]
abp vnext 4.4.0-rc.2

I want to record the login information, I set the request information record setting of audit log, but can not see the login information, that is, connect/token request

`      Configure<AbpAuditingOptions>(options =>
            {
                options.IsEnabledForGetRequests = true;
            });`

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp/pull/4675

Login info already recorded in the security log

**Comment by laosandegudai** [comment]
> See #4675
> 
> Login info already recorded in the security log

Thank you.
