### ISSUE TITLE
High Severity : Vulnerabilities : System.NET.Http 4.3.0

### ISSUE THREAD

**Issue by ShaunDanielz** [abpframework/abp#9681]
I ran a S**nyk Open Source scan** and it found vulnerabilities in System.Net.Http version 4.3.0.  ABP Template version : 4.3.3

**Remediation** : Upgrade System.Net.Http to v4.3.4 or higher

**ABP libraries affected:**
1.  Volo.Abp.Castle.Core
2.  Volo.Abp.Autofac

![image](https://user-images.githubusercontent.com/1783233/127319919-7aad705b-5d0e-41cd-9654-bae9aeb890a3.png)

![image](https://user-images.githubusercontent.com/1783233/127320097-11f8079e-e5e9-4e4a-9c45-269e7cb2f0f5.png)

![image](https://user-images.githubusercontent.com/1783233/127320314-2f500043-7b10-4808-be37-782331e0cd74.png)

![image](https://user-images.githubusercontent.com/1783233/127320434-2bf16e3b-3f30-437b-88da-4668f26d8ffb.png)

**Comment by maliming** [comment]
Duplicate of #9244
