### ISSUE TITLE
High Vulnerabilities : System.Text.RegularExpressions v4.3.0

### ISSUE THREAD

**Issue by ShaunDanielz** [abpframework/abp#9683]
I ran a **Snyk Open Source** scan and it found vulnerabilities in System.Text.RegularExpressions version 4.3.0. 

**ABP Template version :** 4.3.3

**Remediation :** Upgrade System.Text.RegularExpressions to v4.3.1 or higher

**ABP libraries affected:**
1.  Volo.Abp.Castle.Core

![image](https://user-images.githubusercontent.com/1783233/127324801-f6ce2d4c-a3e9-4938-bfdc-f9ac6f63dc90.png)

**Comment by maliming** [comment]
Duplicate of #9244
