### ISSUE TITLE
I want to remove identity server from ABP angular app

### ISSUE THREAD

**Issue by mnaveedtkxel** [abpframework/abp#9685]
ABP 4.3.3 , Angular, EF Core, SQL Server
ABP angular app redirect me for login on identity server which is not required. i want to keep user on my angular app with my own login page, register page. i want to use just simple identity tables which is full fill my requirements.
1- I complete the removal from server side ABP framework with the help of this [https://community.abp.io/articles/replacing-identityserver4-with-identity-in-abp-arh0jxe1.](url). 
2- I want to remove identity server from ABP angular app,
3- I required custom login form on abp angular with simple identity controller token authentication.

**Comment by antosubash** [comment]
@mnaveedtkxel I'm not sure what you want. You want to remove Identity Server but need a token auth? 

Identity server is the recommended way of doing token auth and abp uses `angular-oauth2-oidc` package for it in Angular. There is no identity server in angular app. it uses openid and oauth to do the authentication.

if you want to know more about password flow take a look here

https://github.com/manfredsteyer/angular-oauth2-oidc/blob/master/docs-src/password-flow.md

Authenication using username and password is a really bad idea for SPA. 

And also keep the below text in mind before using Password Flow. This is from the `angular-oauth2-oidc`  documentation.

Please note that from an OAuth2/OIDC perspective, the code flow is better suited for logging into a SPA and the flow described here should only be used, when a) there is a strong trust relations ship between the client and the auth server and when b) other flows are not possible.

Please also note that with OAuth 2.1, password flow will be deprecated.

**Comment by MeryemeBaddaz** [comment]
@antosubash  hi ! I am currently working on a client management project with .net core ef abp framworke and angular , how can i add profile image ?
i watched your tutorial "dotnet file upload with ABP Blob store and Minio " and i applied it , but  encountered some problems  in class AppService cannot have more than one base class , help me plz

**Comment by mnaveedtkxel** [comment]
Thanks for your reply.
angular app link: http://localhost:4200
ABP Api  link: http://localhost:44382
Complete requirement:
When I click on the login button on the home page, the angular app
redirects me on http://localhost:44382/account/login
<http://localhost:44382/account/ogin> this redirect is not required. i
want to retain my domain name (http://localhost:4200)  login page to send
the username and password to API and get the token from identityserver (
http://localhost:44382).

can i send the username & password to the identity server from angular app
rather than redirect to identity server?

**Comment by antosubash** [comment]
@MeryemeBaddaz it is better to use `Disscussion` tab or Stackoverflow for question or add a comment to the blog post. this issue is about identity server. Check this repo https://github.com/antosubash/FileUpload this has a sample.

**Comment by antosubash** [comment]
@mnaveedtkxel yes you can send username and password to the identity server instead of redirect. That is called the `Password Flow` that is what I have shared in the above. keep in mind that is not a recommended way. 

if you want a sample. Look at this.

https://github.com/manfredsteyer/angular-oauth2-oidc/blob/master/projects/sample/src/app/password-flow-login/password-flow-login.component.ts

**Comment by mnaveedtkxel** [comment]
Thanks i use the password flow. it work for me
