### ISSUE TITLE
Validation message for textbox is wrong (array data type mentioned)

### ISSUE THREAD

**Issue by alexandis** [abpframework/abp#9687]
4.3.0 / Angular

I have string textbox with maxlength indicated. When I exceed the length, I am getting wrong message:

![image](https://user-images.githubusercontent.com/6149843/127388824-7fa01e78-d3d2-410f-a545-a97e0acae7f0.png)

But _string_ textbox has nothing to do with _array_. Probably there is a way to indicate _data type_??

I have found this - so proper constant is available somewhere (wavy red underline):

![image](https://user-images.githubusercontent.com/6149843/127388755-af4a0d43-24e6-48b0-9380-9677db243f9f.png)

**Comment by hikalkan** [comment]
Try to use `[StringLength]` instead of `[MaxLength]` for your DTO validation attribute.
