### ISSUE TITLE
profile image with abp framework

### ISSUE THREAD

**Issue by MeryemeBaddaz** [abpframework/abp#9693]
I am currently working on a client management project with .net core ef abp framworke  and angular , how can i add profile image ? 
any one help me !!

**Comment by gterdem** [comment]
If you are asking about the endpoint, its on authserver(identityserver) _account/profile-picture_ endpoint.
![image](https://user-images.githubusercontent.com/25867/127481046-286f79f8-ebf5-462c-8eac-3d132a2fe9a2.png)

If you are asking about UX that where to upload profile image, from the dropdown where your logged in user name appears;
![image](https://user-images.githubusercontent.com/25867/127481768-bf2815ab-ee5e-4bc9-bd47-6fedb1dfd398.png)
Then My account:
![image](https://user-images.githubusercontent.com/25867/127481863-fe4b14af-017b-466c-8a5f-2d19f85fb8cd.png)

or http://localhost:4200/account/manage for short.

**Comment by MeryemeBaddaz** [comment]
@gterdem 
![hub](https://user-images.githubusercontent.com/83915032/127483763-787380ba-465b-4bc3-8494-99b96b080048.png)
Thank you sir for your answer  , i wana just add profile image here

**Comment by MeryemeBaddaz** [comment]
@antosubash  i applied your tutorial "dotnet file upload with ABP Blob store and Minio "
![Uploading app.png…]()
, but encountered some problems in class AppService cannot have more than one base class

**Comment by MeryemeBaddaz** [comment]
@antosubash i applied your tutorial "dotnet file upload with ABP Blob store and Minio "
![app](https://user-images.githubusercontent.com/83915032/127484704-9ad25895-f98c-42cf-bb44-eaab1b56c851.png)
, but encountered some problems in class AppService cannot have more than one base class

**Comment by cotur** [comment]
Hi @MeryemeBaddaz 

You need to implement profile picture feature to your application by yourself.

There are some infrastructural features that ABP offers, but the rest of them is your bussiness. 

1. Use [BLOB Storing](https://docs.abp.io/en/abp/latest/Blob-Storing) system to store files.
2. Use [`IRemoteStreamContent`](https://docs.abp.io/en/abp/latest/Application-Services#working-with-streams) to upload & download files.

**Comment by antosubash** [comment]
@MeryemeBaddaz Remove TestGClientAppService from the TGGclientAppService class. In C# you cannot inherit from multiple classes.

**Comment by MeryemeBaddaz** [comment]
@antosubash when i remove it , i got this
![errorapi](https://user-images.githubusercontent.com/83915032/127536129-6b1c1735-7f80-4e02-a82d-fa8528f956a9.png)

**Comment by antosubash** [comment]
@MeryemeBaddaz  that is because of the `Get` method. the `CrudAppService` already has a `Get` so that creates a conflict. change the `Get` to `GetFile` or something else.
