### ISSUE TITLE
Should the EntityHistoryHelper logic happen after applying the AbpConcepts for EntityFramework Core?

### ISSUE THREAD

**Issue by alexandrejobin** [abpframework/abp#9698]
When you use the EntityHistory feature, the entity change infos are build before the AbpConcepts. I wonder if it should be placed after applying the AdbConcepts instead. Here's the actual code

https://github.com/abpframework/abp/blob/e5bd7cd25f7201a7b03d65aaabcafc33bcd476e8/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/AbpDbContext.cs#L157

The problem I see is if you have an entity decorated with `IHasDeletionTime `or `ISoftDelete`. Because the AbpConcepts is not applied yet, the entity change infos will consider the entity as hard deleted instead of soft deleted. So the following function in the `EntityHistoryHelper` class is probably useless because you will never have a soft deleted entity to test:

https://github.com/abpframework/abp/blob/e5bd7cd25f7201a7b03d65aaabcafc33bcd476e8/framework/src/Volo.Abp.EntityFrameworkCore/Volo/Abp/EntityFrameworkCore/EntityHistory/EntityHistoryHelper.cs#L189

Any thought? Or maybe I'm totally wrong.

**Comment by maliming** [comment]
Did you find any problem about it in your project?
If so, please share the steps and code. Thanks.

**Comment by alexandrejobin** [comment]
If you take one of your `BookStore-Mvc-EfCore` sample and modify it that way, you will have the Books have history and it will convert deleted book in soft deleted book:
* add IHasDeletionTime on the Book class
* add DeletionTime and IsDeleted columns on the dbo.AppBooks table
* add this code in the BookStoreWebModule.cs file
```
Configure<AbpAuditingOptions>(options =>
{
   options.EntityHistorySelectors.AddAllEntities();
});
```

Now if you delete a book, you get this in the `AbpEntityPropertyChanges` table :

![image](https://user-images.githubusercontent.com/865002/127698870-3fb3f8d9-403c-407b-86f9-d41e9237ead2.png)

You can see that all book's properties are listed as if they were changed and replaced by nothing (NewValue = null) but in fact, nothing have changed at all. The only thing that have changed is the IsDeleted and DeletionTime column that now have a value instead of null.

It all depends of how you see this but on my side, my understanding is that the `AbpEntityPropertyChanges` table contains only what have been changed on an entity. If you hard delete a row, I expect to have all the properties listed here. If you soft delete a row, I don't expect anything here since that nothing have changed except the IsDeleted and DeletionTime values.

**Comment by maliming** [comment]
Thanks, I will check this.
