### ISSUE TITLE
Using ef core table splitting throw exception

### ISSUE THREAD

**Issue by Loongle** [abpframework/abp#9711]
ef core document: https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting

An exception occurs when I create a model using this pattern and it does not work

exception content: ` System.InvalidOperationException : The property 'OrderTaskMetric.TenantId' cannot be assigned a value generated by the database. Store-generated values can only be assigned to properties configured to use store-generated values.`

I can reproduce this problem by uploading my demo case

just run `OrderTaskAppService_Tests` unit test

[issue-demo.zip](https://github.com/abpframework/abp/files/6914080/issue-demo.zip)

**Comment by realLiangshiwei** [comment]
Hi,

Did you try it without ABP? this has actually nothing to do with ABP. If three entities have a same name property, this problem will occur.

![image](https://user-images.githubusercontent.com/16813853/127800245-82d113c8-5465-48d9-af54-d58f0a20bf90.png)

You can specify other column name
