### ISSUE TITLE
Logout Issues with Abp Commercial 4.2.0

### ISSUE THREAD

**Issue by kbalasha** [abpframework/abp#9718]
Abp version: 4.2.0 Commercial
User Interface: Angular
Database provider: EF Core
Template: Microservice

Issue (s):

1. Intermittent issue where clicking on logout link on portal simply returns to home page and need to logout second time to be logged out and redirected to login page.
2. Opened the portal in two tabs. Logged out from one tab- I was able to log out successfully. The second tab however shows the following for a long time
![image](https://user-images.githubusercontent.com/25907669/127934674-560efbe7-f016-4b5b-a8cb-ec270bde35a6.png)

**Comment by maliming** [comment]
hi

Please get help on https://support.abp.io
Thanks.
