### ISSUE TITLE
Missing IDataSeeder

### ISSUE THREAD

**Issue by VentsislavDinev** [abpframework/abp#972]
Hello, I try to use on my microservice project and when build from source code or download nuget package "Volo.Abp.Data" IDataSeeder is missing, how to fix this?

**Comment by lanpin** [comment]
@hikalkan Can you release v0.16.1 as soon as possible? Known issues have been fixed.

**Comment by hikalkan** [comment]
We started to publish nightly builds to myget. It will be documented today: https://github.com/abpframework/abp/issues/973

v16.0 will be released at the end of this week (I hope :)).

**Comment by hikalkan** [comment]
See https://abp.io/documents/abp/latest/Nightly-Builds

Note that you should use `v0.15.0-prerelease-20180408`. v16.0-prerelease was a wrong publish (you can see from the date). It will be fixed in the next days.
