### ISSUE TITLE
How to use the StringIncrement method of redis in abp

### ISSUE THREAD

**Issue by yang524433** [abpframework/abp#9720]

**Comment by maliming** [comment]
ABP is using `StackExchange.Redis`, you can directly use its API to call more methods.

**Comment by phuduc88** [comment]
> ABP is using `StackExchange.Redis`, you can directly use its API to call more methods.

Hi,
Please help me, I can't call it.
can you share code samplae ?
Thank you for support

**Comment by maliming** [comment]
hi

```cs
using StackExchange.Redis;
...
ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(configuration["Redis:Configuration"]);
```

https://stackexchange.github.io/StackExchange.Redis/
