### ISSUE TITLE
Article Request : [Blazor]Replace the default blazorise with antblazor

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#9727]
Replace all.include layout、identity module...

**Comment by realLiangshiwei** [comment]
We have no plan to do this, but you can refer https://community.abp.io/articles/using-syncfusion-components-with-the-abp-framework-5ccvi8kc and https://github.com/abpframework/abp/pull/7376.

You can also ask the antblazor team: https://github.com/ant-design-blazor/ant-design-blazor/issues

**Comment by snowchenlei** [comment]
this is Article Request.No implementation is required
