### ISSUE TITLE
Angular tenant resolve  broken when update to version 4.4.0

### ISSUE THREAD

**Issue by duanzlin** [abpframework/abp#9728]
After update abp packages to 4.4.0, i found tenant resolve not work on the domain server.  Then i run the abp sample project DomainTenantResolver,  it works fine with default version 4.3.2，when i update to latest version 4.4.0, the tenant resolve with error also.
![qq20210803184821](https://user-images.githubusercontent.com/47842996/128003478-1f92d1ef-9c0c-48d2-8df9-823495072d47.png)

**Comment by maliming** [comment]
Regression: https://github.com/abpframework/abp/issues/8231 https://github.com/abpframework/abp/pull/8246

**Comment by bnymncoskuner** [comment]
Hello,

Could you share your `environment.ts` and `environment.prod.ts`?

**Comment by maliming** [comment]
hi @bnymncoskuner 

https://github.com/abpframework/abp-samples/tree/maliming-patch-domain/DomainTenantResolver/NG/angular/src/environments

You can get the demo project at https://github.com/abpframework/abp-samples/pull/98

**Comment by bnymncoskuner** [comment]
Hello all,

I've found the issue and sent a PR to fix it. It'll be released in the patch version.

**Comment by maliming** [comment]
It works on 4.4.1!

https://github.com/abpframework/abp-samples/pull/98
