### ISSUE TITLE
Doument how to use nightly builds

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#973]

**Comment by hikalkan** [comment]
Done with https://github.com/abpframework/abp/pull/975

**Comment by lanpin** [comment]
@atakanozceviz  how to use myget in docker? can you upload nuget.config and update Dockerfile?

**Comment by atakanozceviz** [comment]
@lanpin MyGet, nightly builds feed is not enabled by default. To use MyGet in docker you have to configure it yourself.

NuGet.config example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="MyGet" value="https://www.myget.org/F/abp-nightly/api/v3/index.json" />
        <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
</configuration>
```

Or in Dockerfile:

```dockerfile
RUN dotnet restore -s https://www.myget.org/F/abp-nightly/api/v3/index.json -s https://api.nuget.org/v3/index.json
```

You may want to check these out:

- [dotnet restore --source <SOURCE>](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x#options)
- [nuget.config reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources)
