### ISSUE TITLE
Customizing Login/Register Pages & APIs for Angular UI.

### ISSUE THREAD

**Issue by omaghd** [abpframework/abp#9730]
- ABP Version: 4.3
- UI: **Angular**
- Database provider: EF Core
- Identity Server: NOT separated 

Kindly, I'm stuck in this issue for months, I don't know how to change the default Login/Register pages in Angular UI.

Is there away to customize the login/register APIs? 
So I can send my data from Angular to the services. And still can manage the oauth/token?
Or just customizing the pages somewhere on backend?

In recap, that's what I want to produce:
- [ ] Login using a unique Identifier (that I will generate) + Password
- [ ] Register using a wizard form (stepper)

**NOTE**: I already added the extra properties I will need, in AppUser

An example of the register wizard form:
<img src="https://www.omaghd.com/example.jpg">

### **Sorry if my question is basic for you**, I'm still learning this RICH framework!

**Comment by cotur** [comment]
Hi @omaghd 

Whether you use Angular or not, (by default) the login/register pages are normal MVC pages from your backend application.

If you did not change the default usage, you need to override the `MVC razor pages` to customize the login screens. 
Here is the detailed documentation about it: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#overriding-a-razor-page-cshtml

If you read and follow the documentation, you will able to override the pages. And it makes easier to achieve your second task also: "Register using a wizard form (stepper)"

ABP Framework provides full infrastructure, but you need to implement that kind of feature by yourself.

**Comment by omaghd** [comment]
> Hi @omaghd
> 
> Whether you use Angular or not, (by default) the login/register pages are normal MVC pages from your backend application.
> 
> If you did not change the default usage, you need to override the `MVC razor pages` to customize the login screens.
> Here is the detailed documentation about it: https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#overriding-a-razor-page-cshtml
> 
> If you read and follow the documentation, you will able to override the pages. And it makes easier to achieve your second task also: "Register using a wizard form (stepper)"
> 
> ABP Framework provides full infrastructure, but you need to implement that kind of feature by yourself.

Hi @cotur 
I appreciate your answer!
