### ISSUE TITLE
Can't Resolve Service from IServiceProvider

### ISSUE THREAD

**Issue by sofm13** [abpframework/abp#9736]
abp 4.3.2
i have a class like this
![image](https://user-images.githubusercontent.com/52565295/128135624-5064591b-f7cc-47e9-a4de-9775a3492f74.png)

but when i want Resolve Service from IServiceProvider,i Unable to get this service
![image](https://user-images.githubusercontent.com/52565295/128135890-7b2566f8-6f1f-4428-8293-3499cc2fa11c.png)

**Comment by maliming** [comment]
Please check the official documentation before asking questions: 
https://docs.abp.io
https://docs.abp.io/en/abp/latest/Dependency-Injection

**Comment by sofm13** [comment]
but when i
