### ISSUE TITLE
`abp add-module Volo.BasicTheme --with-source-code --add-to-solution-file` not working.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#9747]
**Version: 4.4.0**

```cs
> abp new QA -t app
> abp add-module Volo.BasicTheme --with-source-code --add-to-solution-file
```

https://support.abp.io/QA/Questions/1543#answer-d4cec38b-528c-c633-e711-39fe27970af2

**Comment by recruitans** [comment]
I was expecting it to be fixed in version 4.4. When will 4.4-patch be released?

**Comment by yekalkan** [comment]
You can remove/delete the projects under `Volo.BasicTheme.Tests` folder from your solution to fix it for now.

**Comment by maliming** [comment]
https://github.com/abpframework/abp/pull/9750
