### ISSUE TITLE
Upload file with form on a modal takes too long before onResult

### ISSUE THREAD

**Issue by espindl** [abpframework/abp#9767]
* **ABP Framework version** : 4.0.0
* **User Interface** type : MVC
* Database provider: EF Core

We are uploading a file from a form on a modal. Calling an app service from OnPostAsync of modal's cs file. App service returns, modal's OnPostAsync also returns but modal.onResult() is called long after. Time increases if the content of the file is bigger. We guess: ABP is calling app service through jquery ajax form and that it is async, waits 'success' (But we can see that app service really finishes the work). But maybe something happens after the app service returns, because calling parameters include file content as byte[]. 

Is there anything that we should take into account in this process?

**Comment by maliming** [comment]
Please share your code. Are you using the [IRemoteStreamContent](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Core/Volo/Abp/Content/IRemoteStreamContent.cs) ?

**Comment by espindl** [comment]
We were not using IRemoteStreamContent, but after your response converted to use it. But the problem continues. 

The simplified code is below.

(A - appservice) returns, (B - razor cs onpost) returns but after that modal freezes before (C - onResult). In between OnPostAsync and onResult framework's code is doing something but we could not find it in the framework codes. If the file is bigger (so the appservice repository processes become more and time consuming) the freeze is longer. 

**In MainPage.js**

```
const uploadModal = new abp.ModalManager(abp.appPath + 'MainPage/UploadModal');

$('#UploadFile').on('click', function () {
        uploadModal.open({hedeId: $('#HedeId').val(), hedeName:$('#HedeName').val() });
    });

uploadModal.onResult(function (obj, event) {
    console.log(event.xhr.responseJSON.hedeType) // **C**
});
```

**In UploadModal.cshtml**

```
<form asp-antiforgery="true" asp-page="/MainPage/UploadModal" enctype="multipart/form-data" method="post">
    <abp-modal>
        <abp-modal-body>
            <abp-input asp-for="HedeId"/>
            <div class="custom-file mt-4 mb-4">
                <input type="file" class="custom-file-input" id="hedeFile" asp-for="FileUpload.FormFile" required>
                <label class="custom-file-label" id="fileLabel" for="hedeFile">@L["UploadFileLabel"]</label>
            </div>
            <button type="submit" id="submitButton" disabled class="btn btn-primary">@L["Start"]</button>
            <button type="button" class="btn" data-dismiss="modal">@L["Cancel"]</button>
        </abp-modal-body>
    </abp-modal>
</form>
```

**In UploadModal.cshtml.cs**

```
public async Task<IActionResult> OnPostAsync()
{
    if (!ModelState.IsValid)
    {
        throw new UserFriendlyException("Not a valid file",
            details:"You can upload only valid csv files.", logLevel:LogLevel.Warning);
    }

    var remoteStreamContent = new RemoteStreamContent(FileUpload.FormFile.OpenReadStream());
    var hedeFile = new HedeFileDto {HedeId =HedeId, Content = remoteStreamContent};

    var result = await _hedeAppService.UploadFileAsync(hedeFile);

    return new ObjectResult(result);  // **B**
}
```

**In HedeFileDto.cs**

```
public class HedeFileDto 
{
    public Guid HedeId { get; set; }
    public IRemoteStreamContent Content { get; set; }
}
```

**In HedeAppService.cs**

```
public async Task<UploadHedeResultDto> UploadFileAsync(HedeFileDto input)
{
    .....

    byte[] content;
    await using (MemoryStream ms = new MemoryStream())
    {
        await input.Content.GetStream().CopyToAsync(ms);
        content = ms.ToArray();
    }

    var file = new HedeFile { HedeId = input.HedeId, Content = content};
    
    .... // here we have awaited repository codes that use contents of the file 

    return new UploadHedeResultDto(){ HedeName = hede.Name, HedeType = hede.SlotType}; // **A**
}
```

**Comment by maliming** [comment]
hi espindl 

Can you share a minimum project, the code looks no problem.

**Comment by espindl** [comment]
I will try to create a minimum project. But in the meantime I want to add something. 

When I look at the Chrome Developer Tools - Network tab, I see that “Content Download” takes too long. Although appService code returns client/page is waiting "an end". What should the appService return? Is there a special thing to return to make the page understand the response ended?

**Comment by maliming** [comment]
I'm not sure, waiting for your project.

**Comment by espindl** [comment]
I could not create the same behaviour simply because we are doing some stuff with the uploaded file contents, like creating new entities from every line in the file, comparing them with existing entites and inserting them. The time increases as the line count increase. So it is waiting for the app service operation to end really. 

The only thing that bothered me, while debugging although you see that the app service and razor "cshtml.cs" file returns, onResult (success) occurs after some time. I wrote my own $.ajax call and it behaved the same way. So, it is not specific to ABP javascript code. 

Anyway, thank you.
