### ISSUE TITLE
[Question] Lose css after overriding a razor page 

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#9772]
ABP version: 4.3.3
Hi, communities!
I followed [this tutorial](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Customization-User-Interface#overriding-a-razor-page-cshtml) to replace `Login.cshtml` , and I just comment register button

![屏幕截图 2021-08-09 101426](https://user-images.githubusercontent.com/19605145/128654146-e7cdd054-ed92-4c02-9f54-057889e65eb4.png)

When I visit /Account/Login , the page lose some css theme
![屏幕截图 2021-08-09 101642](https://user-images.githubusercontent.com/19605145/128654379-85997b45-24e3-4661-9374-28a56c72bbf2.png)
What I should do? Can someone help?

**Comment by realLiangshiwei** [comment]
See https://github.com/abpframework/abp-samples/tree/master/DocumentationSamples/CustomApplicationModules

**Comment by trickyrat** [comment]
@realLiangshiwei hi, I followed that doc, I just copy `Login.cshtml` code, and commented `register` button. 
![微信图片_20210809105846](https://user-images.githubusercontent.com/19605145/128656304-df405e08-1dc8-4dd5-9647-aeb7c0bf9a34.png)
I didn't copy `Login.cshtml.cs` , So I need add some css reference to `Login.cshtml` or `Login.cshtml.cs`?

**Comment by JadynWong** [comment]
It seems that your `TagHelper` is not working, check `/Pages/_ViewImports.cshtml`

```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Volo.Abp.AspNetCore.Mvc.UI
@addTagHelper *, Volo.Abp.AspNetCore.Mvc.UI.Bootstrap
@addTagHelper *, Volo.Abp.AspNetCore.Mvc.UI.Bundling
```

**Comment by trickyrat** [comment]
@JadynWong
 It works
Thanks for your help and patience @JadynWong @realLiangshiwei
