### ISSUE TITLE
Can‘t recognize ApplicationService in Volo.Abp.Application.Services namespace after upgrading from 4.3.3 to 4.4.0

### ISSUE THREAD

**Issue by trickyrat** [abpframework/abp#9788]
Visual Studio 2022 preview 2.1
![微信图片_20210810172908](https://user-images.githubusercontent.com/19605145/128955729-cc8be2b6-f524-4be6-882c-da756c25dea9.png)
I tried to delete bin/obj folders and clean/rebuild solution, but the bug still existed.

**Comment by realLiangshiwei** [comment]
I don't think this is a bug. please check your solution
