### ISSUE TITLE
when the current user has logged in,cant‘t  find current tenant id from HTTP headers

### ISSUE THREAD

**Issue by sofm13** [abpframework/abp#9795]
abp4.3.2
when the current user has logged in，i cant‘t  find current tenant id from HTTP headers，how do i do?

**Comment by realLiangshiwei** [comment]
https://docs.abp.io/en/abp/latest/Multi-Tenancy#tenant-resolvers

> Gets the tenant id from claims of the current user, if the current user has logged in. This should always be the first contributor for the security

This is by design

**Comment by sofm13** [comment]
So I if I'm logged in, I can't set tenant in the header?
