### ISSUE TITLE
DbMigrator may not need to reference Application.Contracts

### ISSUE THREAD

**Issue by Stirda** [abpframework/abp#9796]
`DbMigrator` may not need to reference `Application.Contracts`.

Only referencing `EntityFrameworkCore` project gives a reference to `Domain` too, which contains `*DbMigrationService` class. Besides, `DbMigrator` is not a client of the backend.

What do you think about it?

ABP 4.4

**Comment by Stirda** [comment]
I tested build and run. Everything seems to work fine without neither `Application.Contract` dependency nor `*ApplicationContractsModule` loading.

**Comment by realLiangshiwei** [comment]
Sorry, after my check, we need to reference `Application.Contracts.`

Because the permission definition needs to be loaded when seeding data.

**Comment by Stirda** [comment]
@realLiangshiwei You mean that the `AbpPermissionGrants` table would not be filled?

**Comment by realLiangshiwei** [comment]
@Stirda 

Yes.
