### ISSUE TITLE
Rich Text Editor feature request

### ISSUE THREAD

**Issue by davidcateduclarity** [abpframework/abp#9810]
Greetings;

There seem to be no Rich Text Editor, an editor which allows you to make text bold, italics, lists, add images(possibly).

I am requested that this feature be added to the Lepton theme and to abp.io.

Many thanks,

--Dave

**Comment by realLiangshiwei** [comment]
Actually, we use [tui-editor](https://nhn.github.io/tui.editor/latest/) as Rich Text Editor.

You can see we use it in blogging module: 
https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.Web/Pages/Blogs/Posts/New.cshtml#L63

we have an npm package [@abp/tui-editor](https://www.npmjs.com/package/@abp/tui-editor), You can use it immediately and benefit from it.
