### ISSUE TITLE
Devexpress Blazor Report integration error

### ISSUE THREAD

**Issue by akilliadam** [abpframework/abp#9820]
Hi,
I'm developing a simple experimental blazor application using AbpFramework. 
I have prepared some reports in the project and I am using the [Report Viewer (Native)](https://demos.devexpress.com/blazor/ReportViewer) component that Devexpress announced with version 21.1.3 to preview these reports. With this component, I can preview my reports without any problems. However, after logging in using the `/Account/Login` page of AbpFramework, I get the following errors on the print preview screen and console screen of the browser that opens when I preview the report and click the Print button on the preview screen.
If I do not login or I logout, I can view and print my report on the browser's print preview screen without any problems. I guess I need to make some definitions somewhere.
However, I couldn't find where and how to define it. I guess it is a problem with permissions of `DXReportViewerNativeDownload` route since this problem occurs after login. This is how [this route is used](https://docs.devexpress.com/XtraReports/DevExpress.Blazor.Reporting.Controllers.DownloadExportResultController#inheritance). However, I couldn't solve the problem.

Thank you for your answers.

![Hata2](https://user-images.githubusercontent.com/80377964/129451327-3867709d-7ddb-4bff-909b-2e42435beae0.PNG)

**Comment by JadynWong** [comment]
Use English to describe it better.

Maybe this is the reason for CSRF.
[https://docs.abp.io/en/abp/4.4/CSRF-Anti-Forgery#configuration-customization](https://docs.abp.io/en/abp/4.4/CSRF-Anti-Forgery#configuration-customization)

**Comment by akilliadam** [comment]
I applied the structure in the link you sent, but I still could not solve the problem. I am getting the same error again.

**Comment by JadynWong** [comment]
If your apply is similar to this, it could be other reason.

```csharp
Configure<AbpAntiForgeryOptions>(options =>
{
    options.AutoValidateFilter = type => !type.FullName.StartsWith(typeof(DownloadExportResultController).FullName);
});
```

**Comment by akilliadam** [comment]
I solved my problem with the method you suggested. Thank you so much.
