### ISSUE TITLE
React Native Mobile project

### ISSUE THREAD

**Issue by iamsaleeb** [abpframework/abp#9823]
Just wondering if there are any plans on migrating the react native project to typescript in the future?

Thanks!

**Comment by mehmet-erim** [comment]
Hi @iamsaleeb,

We don't have a plan for this. You can add TypeScript to your project easily. Please refer to [Adding TypeScript to an Existing Project](https://reactnative.dev/docs/typescript#adding-typescript-to-an-existing-project) document.
