### ISSUE TITLE
Include/embedd modules source-code into main solution

### ISSUE THREAD

**Issue by pointlevel** [abpframework/abp#9824]
Hi

Is there an easy way or documentation on how to embedd modules sourcecode into the mainsolution without including it as a new project?
I want to have all pages to be within the .Blazor-project for easier maintaining and dont want to have separate projects for every module. 
I need every Razor-page that comes with the template to be editable.

**Comment by maliming** [comment]
HI

You can use `add-module` command with `--with-source-code` options.

https://docs.abp.io/en/abp/latest/CLI#add-module

**Comment by pointlevel** [comment]
@maliming I did try to use `add-module Volo.TenantManagement` with both `--with-source-code` and also `--add-to-solution-file`, but when i reloaded the solution, i get an error saying "**The selected file is not a valid solution file**" and i cannot start the solution anymore.
The solution is newly downloaded and clean.

Any tips?

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Steps needed to **reproduce** the problem.

**Comment by pointlevel** [comment]
@maliming please check below:

> * Your **ABP Framework version**. 
4.4.0
> * Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
Blazor server
> * Your database provider(EF Core/MongoDB)
EF Core
> * Steps needed to **reproduce** the problem.
Download a new solution, build the application and run the DBMigrator (Application works ok here)
Run `abp add-module Volo.TenantManagement --with-source-code --add-to-solution-file` from within solution folder.
Reload the solution and the error occur, solution can not be started.

**Comment by maliming** [comment]
Can't reproduce the problem with your steps.
