### ISSUE TITLE
Unable to login to sample app after setup in GKE

### ISSUE THREAD

**Issue by 23kbps** [abpframework/abp#9825]
I followed the ABP Microservice sample here https://github.com/abpframework/abp-samples/tree/master/MicroserviceDemo/k8s and decided to setup it in GKE (k8s in GCP) with following items:
- RabbitMQ in standalone VM
- GKE cluster (1.20+)
- Redis inside GKE
- CloudSQL SQL Server 2019 Express

After few issues with Database initialization and RabbitMQ default user/pass, I could made all the pods running. I exposed admin, web, auth-server to internet with nginx ingress controller successfully.

When I load website, blog, products,... it can display successfully. 

However when I try to register new user, it throwed 500 without any further message, also there is no any stderr in logs of auth-server pod
![image](https://user-images.githubusercontent.com/86248851/129482500-08ebb6f0-d09f-4c1e-9f51-08e3ef6c07f9.png)

I tried to create an environment for logging and set it to Debug level, then delete the pod and tried again, but there is no any log messages displayed

![image](https://user-images.githubusercontent.com/86248851/129482530-1a1a9259-0c15-4e8f-9ae6-753a2ed01e8c.png)

Another issue with login is I tried to open admin page, I got it redirected to another URI and then returned 500, again I can't find any logs in stderr of pod

![image](https://user-images.githubusercontent.com/86248851/129482582-81513e1b-ed71-4491-8e14-01ee35171212.png)

My questions:
1. What is default admin credentials to access the login page?
2. How can I enable debug logging for all service deployment?
3. How can I set the username/password/exchange/... in rabbitmq, because it's using `guest` account right now
4. In this sample app is Redis only for caching, or does it also serve the persistent storage somewhere?

Thanks

**Comment by maliming** [comment]
> What is default admin credentials to access the login page?

admin
1q2w3E*

> In this sample app is Redis only for caching, or does it also serve the persistent storage somewhere?

ABP uses it for cache,  Other components may use it to store other info. eg `ASP.NET Core Data Protection`

>How can I enable debug logging for all service deployment?

You can refer to Microsoft's documentation.

>How can I set the username/password/exchange/... in rabbitmq, because it's using guest account right now

https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/AbpRabbitMqModule.cs#L17

http://rabbitmq.github.io/rabbitmq-dotnet-client/api/RabbitMQ.Client.ConnectionFactory.html#RabbitMQ_Client_ConnectionFactory_UserName
