### ISSUE TITLE
favicon.ico is missing in MVC solution

### ISSUE THREAD

**Issue by DonVliet** [abpframework/abp#9826]
ABP Framework version: 4.4.0
User Interface: MVC
Steps needed to **reproduce** the problem: Create and run 4.4.0 MVC solution

favicon.ico is missing

![image](https://user-images.githubusercontent.com/69393775/129538911-b78b7a80-8c89-40ba-97c9-bc45b53faf32.png)

**Comment by maliming** [comment]
hi 

This is chrome behavior. You can add your app favicon to **wwwroot** folder.
