### ISSUE TITLE
Response is null or message can't be deserialized as HealthChecks.UI.Core.UIHealthReport when running in Azure not locally

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#9827]
Ok I know that this **might not** be abp.io related but this is in the framework/templates and I can´t find any information/docs on configuring the endpoints so if this is not a bug it would be great to have some more information on what needs to be done to make it work outside of localhost.

So the problem is that I get status  **Unhealthy** hitting the endpoints below when in azure. I have not changed anything for them.

[https://[myUrl]/health-**status**](https://[myUrl]/health-**status**) seems to work.. the message at least tells me it "could connect to databse and get record"
```{"status":"Healthy","totalDuration":"00:00:00.0973968","entries":{"MyDbContext Check":{"data":{},"description":"Could connect to database and get record.","duration":"00:00:00.0954897","status":"Healthy","tags":["database"]}}}```

but [https://[myUrl]/health-**ui**](https://[myUrl]/health-**ui**) gives me the following error with health **Unhealthy**
`Response is null or message can't be deserialized as HealthChecks.UI.Core.UIHealthReport.`

![image](https://user-images.githubusercontent.com/2386572/129551069-b30b718e-9719-451e-afe0-bb488597949b.png)

same with [https://[myUrl]/health-**api**](https://[myUrl]/health-**api**)
`{"id":1,"name":"Endpoint","status":"Unhealthy","description":"Response is null or message can't be deserialized as HealthChecks.UI.Core.UIHealthReport.","duration":"00:00:00","tags":null}],"history":[]}`

* Your **ABP Framework version**. 4.4.0
* Your **User Interface** type Blazor
* Your database provider EF Core

**Comment by maliming** [comment]
You can try set `UseHybridSerializer` to `false`. In addition, I don't think it has anything to do with abp.

https://docs.abp.io/en/abp/latest/JSON#abpjsonoptions

**Comment by sturlath** [comment]
yeah sorry about that... 

I tried your approach and it didn't work

I added the following code to MyHttpApiHostModule.cs without change. 

```csharp
public override void PreConfigureServices(ServiceConfigurationContext context)
{
    PreConfigure<AbpJsonOptions>(options =>
    {
        options.UseHybridSerializer = false;
    });
}
```

I'll take a look at it later if/when I want to use this feature.

**Sorry for wasting your time!**
