### ISSUE TITLE
ignoring [ignoremultitenancy] on settingdbcontext 

### ISSUE THREAD

**Issue by cem1835** [abpframework/abp#9828]
Hello , 

how to ignore  [ignoremultitenancy] on settingdbcontext ? 

https://github.com/abpframework/abp/blob/6d9fd72d3ff0be64cd4c0007c27c24661467da1f/modules/setting-management/src/Volo.Abp.SettingManagement.EntityFrameworkCore/Volo/Abp/SettingManagement/EntityFrameworkCore/SettingManagementDbContext.cs#L8

**Comment by maliming** [comment]
This is by design, You can't do this.

**Comment by cem1835** [comment]
Before version 4.0, we were storing tenant settings in tenant database.Can't we do this anymore ?

**Comment by maliming** [comment]
See
https://github.com/abpframework/abp/pull/7509
https://docs.abp.io/en/abp/latest/Entity-Framework-Core#controlling-the-multi-tenancy

**Comment by cem1835** [comment]
can i fix this using "replacedbcontext" ?

https://docs.abp.io/en/abp/latest/Entity-Framework-Core#Replace-Other-DbContextes

**Comment by maliming** [comment]
I don't think so.
