### ISSUE TITLE
How to use IdentityServerClientCorsOrigins?

### ISSUE THREAD

**Issue by luy710** [abpframework/abp#9832]
Currently the cors origins are configured in the appsettings however I am not able to configure in way that it gets the origins from the SQL Server database.

I have commented out that withOrigins sections however I have it already configured in the database but it gets rejected

**Comment by maliming** [comment]
This is related to the Identity Server.

http://docs.identityserver.io/en/latest/topics/cors.html
https://github.com/abpframework/abp/blob/b96ddcbe4a63cdbdbf60b04b0ff3e97b13e8c2f1/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AbpCorsPolicyService.cs#L62
