### ISSUE TITLE
How to get 'configuration' in AppService?

### ISSUE THREAD

**Issue by sortjiajun** [abpframework/abp#984]
![image](https://user-images.githubusercontent.com/16735741/55791232-9e89e980-5af0-11e9-9a88-ea63a2225149.png)
Like This.

**Comment by maliming** [comment]
injection [IConfigurationAccessor](https://github.com/abpframework/abp/blob/f62ed01ac24433dcdc0faf02400fc871caa65dbe/framework/src/Volo.Abp.Core/Volo/Abp/Configuration/IConfigurationAccessor.cs)
