### ISSUE TITLE
How to set the datetime format for the extra properties?

### ISSUE THREAD

**Issue by xuyae573** [abpframework/abp#9848]
- Abp 4.4.0
- Razor Pages 
- EF Core
-  

I have added 2 DateTime into extra properties for the IdentityUser 

 `ObjectExtensionManager.Instance.Modules()
                .ConfigureIdentity(identity =>
                {
                    identity.ConfigureUser(user =>
                    {
                        user.AddOrUpdateProperty<DateTime>( //property type: string
                            "MemberStartDate", //property name
                            property =>
                            {
                                property.Attributes.Add(new DisplayFormatAttribute() { DataFormatString = "{0:yyyy/MM/dd/}" });
                                property.DefaultValueFactory = () => "";
                        
                                //validation rules
                                property.Validators.Add(context =>
                                {
                                    if (context.Value != null)
                                    {
                                        var startDate = (DateTime) context.Value;
                                        var endDate =
                                            context.ValidatingObject.GetProperty<DateTime>("MemberEndDate");

                                        if (endDate < startDate)
                                        {
                                            var message = LocalizableString.Create<LMSResource>("InvalidStartDate").Name;
                                            context.ValidationErrors.Add(
                                                new ValidationResult(
                                                    message,
                                                    new[] { "extraProperties.MemberStartDate" }
                                                )
                                            );
                                        }
                                    }
                                });
                    }
                        );
                        user.AddOrUpdateProperty<DateTime>( //property type: string
                            "MemberEndDate", //property name
                            property =>
                            {
                                property.DefaultValueFactory = () => "";
                                //validation rules
                                property.Attributes.Add(new DisplayFormatAttribute() { DataFormatString = "{0:yyyy/MM/dd/}" });
                            }
                        );
                    });
                });`

 

And I have added the display format attribute for these 2 DateTime properties as well, but seems it does not work in UI part?

![image](https://user-images.githubusercontent.com/1418798/129925104-d541cf34-fbe8-4e33-8b09-ac8c976265f2.png)

**Comment by JadynWong** [comment]
https://github.com/abpframework/abp/blob/HEAD/framework/src/Volo.Abp.AspNetCore.Mvc.UI/Volo/Abp/ObjectExtending/MvcUiObjectExtensionPropertyInfoExtensions.cs

You can try add `new DataTypeAttribute(DataType.Date)`.

Current version does not seem to support `DisplayFormatAttribute`
