### ISSUE TITLE
Allow project names to contain but not equal to Blazor.

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#9853]
https://support.abp.io/QA/Questions/1706#answer-c97fe651-d6f4-32f4-9f81-39fe6e6a1df3

https://github.com/abpframework/abp/blob/d21fe36074c79e1e02a9a85bb2aa1299aab909af/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Utils/ProjectNameValidator.cs#L22

**Comment by ebicoglu** [comment]
I refactored this. 
We don't allow Blazor keyword because, Suite replaces Blazor keyword and project doesn't compile.
