### ISSUE TITLE
HttpClientProxy Return Null

### ISSUE THREAD

**Issue by jieke-wang** [abpframework/abp#9856]
ABP vNext Version: 4.4
Database: no database

Ecommerce.Order.Application\Ecommerce.Order.Application.csproj
![image](https://user-images.githubusercontent.com/12584587/130054055-61ff5214-8224-4533-843b-032d4a427ddc.png)

Ecommerce.Order.Application\EcommerceOrderApplicationModule.cs
`
[DependsOn(
        typeof(AbpHttpClientModule),
        typeof(AbpAutoMapperModule),
        typeof(AbpDddApplicationModule),
        typeof(EcommerceOrderApplicationContractsModule)
    //typeof (EcommerceProductApplicationContractsModule)
    )]
    public class EcommerceOrderApplicationModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAutoMapperObjectMapper<EcommerceOrderApplicationModule>();

            Configure<AbpAutoMapperOptions>(options =>
            {
                //Add all mappings defined in the assembly of the MyModule class
                options.AddMaps<EcommerceOrderApplicationModule>();
                options.AddProfile<EcommerceOrderApplicationProfile>(true);
            });

            Configure<AbpRemoteServiceOptions>(options =>
            {
                //options.RemoteServices.Default =
                //    new RemoteServiceConfiguration("http://localhost:53929/");
            });

            context.Services.AddHttpClientProxies(typeof(EcommerceProductApplicationContractsModule).Assembly, remoteServiceConfigurationName: "product-service");

            //base.ConfigureServices(context);
        }
    }
`

Ecommerce.Order.Application\OrderAppService.cs
`
 public class OrderAppService : ApplicationService, IOrderAppService
    {
        private readonly IProductAppService _productAppService;
        private readonly IHttpClientProxy<IProductAppService> _httpClientProxy;

        public OrderAppService(IProductAppService productAppService, IHttpClientProxy<IProductAppService> httpClientProxy)
        {
            _productAppService = productAppService;
            _httpClientProxy = httpClientProxy;
        }

        public OrderDto Get(int id)
        {
            OrderDto order = new OrderDto
            {
                Id = id,
                Ref = Guid.NewGuid().ToString("n")
            };

            //var product = _productAppService.Get (new Random ().Next ());
            var product = _httpClientProxy.Service.Get(100);
            order.SetProduct(ObjectMapper.Map<Product.Application.Contracts.DTO.ProductDto, ProductDto>(product));

            return order;
        }
    }
`

When I execute _productAppService.Get (new Random ().Next ()) or  _httpClientProxy.Service.Get(100), always return null for product;
When using Fiddler to grab requests, requests for product app service are normal.

The swagger screenshot is as follows:

http://localhost:5000/swagger/index.html
![image](https://user-images.githubusercontent.com/12584587/130052518-d741ba3b-435d-4e51-b90f-ab6802b60344.png)

http://localhost:5001/swagger/index.html
![image](https://user-images.githubusercontent.com/12584587/130052615-8d2ade04-1b2a-4a36-9b67-e930b677815f.png)

The fiddler screenshot is as follows:
![image](https://user-images.githubusercontent.com/12584587/130052888-1d96127e-741f-46ab-8ce6-411cf2ff9af9.png)
![image](https://user-images.githubusercontent.com/12584587/130053079-a25ef85c-34e1-4114-b26d-c3f82bb34ced.png)

**Comment by maliming** [comment]
Please debug your application service and check the logs first.

**Comment by jieke-wang** [comment]
The request log:
![image](https://user-images.githubusercontent.com/12584587/130060866-893e70a8-0209-4528-8638-66a1e50188d8.png)

Thank you for your attention!

My sample project are as follows:
https://1drv.ms/u/s!Al2-1_xOkT_ClVRtljz8i2hWB__J?e=NXxeiM

**Comment by realLiangshiwei** [comment]
The logs you provided don't have any error, and I think this is not related to ABP, you should double-check your code.

**Comment by jieke-wang** [comment]
Ok, I found the issue, the return type of API must be task<T>, 
thanks again!
