### ISSUE TITLE
Add PreferExactMatches attribute on the Router component

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#9860]
according https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/blazor-routing-logic-changed, should we add PreferExactMatches attribute on https://github.com/abpframework/abp/blob/9fc5adc2652fb38cd406d1eb281e7c5fb08f7fc2/modules/basic-theme/src/Volo.Abp.AspNetCore.Components.Web.BasicTheme/Themes/Basic/App.razor and https://github.com/abpframework/abp/blob/9fc5adc2652fb38cd406d1eb281e7c5fb08f7fc2/modules/basic-theme/src/Volo.Abp.AspNetCore.Components.Web.BasicTheme/Themes/Basic/AppWithoutAuth.razor ?

**Comment by maliming** [comment]
**If upgrading from previous versions of Blazor to 5.x**, use the PreferExactMatches attribute on the Router component.

We don't need this I guess.

**Comment by rqx110** [comment]
it is the default setting if we create a fresh Blazor project from vs or cli
