### ISSUE TITLE
Some fields of the entity are stored in Redis, but are null when retrieved

### ISSUE THREAD

**Issue by sofm13** [abpframework/abp#9863]
abp 4.3.2
Some fields of the entity are stored in Redis, but are null when retrieved。
redis:
![image](https://user-images.githubusercontent.com/52565295/130194493-8a1f71f8-5f42-4895-9df1-abf1552c0f38.png)
project
![image](https://user-images.githubusercontent.com/52565295/130194599-f8ba52dd-7986-413e-9621-6468ca138c6d.png)

**Comment by realLiangshiwei** [comment]
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Your database provider(EF Core/MongoDB)
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
