### ISSUE TITLE
Map an extra property in IdentityUser entity as a foreign key

### ISSUE THREAD

**Issue by omaghd** [abpframework/abp#9868]
* Version 4.4
* EF Core

I need to map an extra property from Identity User entity as a foreign key, that I already defined in both **ModuleExtensionConfigurator** and **EfCoreEntityExtensionMappings** classes.

Here is what I did in **OnModelCreating** method in DbContext:
```
builder.Entity<IdentityUser>(b =>
{
    b.HasOne<Example>().WithMany().HasForeignKey(x => x.ExtraProperties["ExampleId"]);
});
```

And I get this error:
`The expression 'x => x.ExtraProperties.get_Item("ExampleId")' is not a valid member access expression. The expression should represent a simple property or field access: 't => t.MyProperty'. When specifying multiple properties or fields, use an anonymous type: 't => new { t.MyProperty, t.MyField }'. (Parameter 'memberAccessExpression')`

Please, is this way correct or is there a better way to do it?

**Comment by realLiangshiwei** [comment]
Try: 

```csharp
builder.Entity<IdentityUser>(b =>
{
    b.HasOne<Example>().WithMany().HasForeignKey(“propertyName”);
});
```
