### ISSUE TITLE
.cshtml to .razor

### ISSUE THREAD

**Issue by akilliadam** [abpframework/abp#9869]
Do you plan to redesign the .cshtml pages in this [link](https://github.com/abpframework/abp/tree/dev/modules/account/src/Volo.Abp.Account.Web/Pages/Account) in the account module as .razor specific to blazor? If you think, when will you do it?
@hikalkan

**Comment by maliming** [comment]
hi

**SignInManager<TUser> and UserManager<TUser> aren't supported in Razor components**

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0
