### ISSUE TITLE
Call AppService from one module to another

### ISSUE THREAD

**Issue by weiwxg** [abpframework/abp#9879]
I have a project which is divided into two independent modules, as follows

![image](https://user-images.githubusercontent.com/24971860/130575044-c34b0f88-464f-4801-9b48-b96ac71bbeab.png)

Acme.Foo.Application.Contracts defines an interface IFooAppService, and Acme.Bar.Application.Contracts defines an interface IBarAppService. If I want to call the service method in Acme.Foo in the Acme.Bar module (do not want to be referenced by the project), what should I do?

**Comment by maliming** [comment]
Please check https://docs.abp.io/en/abp/latest/API/Dynamic-CSharp-API-Clients

**Comment by weiwxg** [comment]
你好，关于Dynamic-CSharp-API-Clients的相关内容我是阅读过了的，只是我没有太能看得明白
![image](https://user-images.githubusercontent.com/24971860/130711343-66537ad1-3985-4dbe-a9b1-dd2f12f856fb.png)

我感觉HttpApi.Client似乎是被Web层引用的，但是我的项目中前后端是分离的，前端没有办法直接引用HttpApi.Client层，我不清楚如何使用这个功能。麻烦能给我指引下思路，非常感谢。
