### ISSUE TITLE
How to disable auto generate api url style like '​/api​/app​/book/{id}' ?

### ISSUE THREAD

**Issue by tsdyy** [abpframework/abp#9882]
I would like to use the following style to replace it.
'/api/app/book?id={id}'

In other words, I don't want the id existed in the url path but in the query

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.

**Comment by tsdyy** [comment]
thanks for your quickly reply.
from document:

| Service Method Name                                   | HTTP Method | Route                      |
| ----------------------------------------------------- | ----------- | -------------------------- |
| GetAsync(Guid id)                                     | GET         | /api/app/book/{id}         |
| GetListAsync()                                        | GET         | /api/app/book              |
| CreateAsync(CreateBookDto input)                      | POST        | /api/app/book              |
| UpdateAsync(Guid id, UpdateBookDto input)             | PUT         | /api/app/book/{id}         |
| DeleteAsync(Guid id)                                  | DELETE      | /api/app/book/{id}         |
| GetEditorsAsync(Guid id)                              | GET         | /api/app/book/{id}/editors |
| CreateEditorAsync(Guid id, BookEditorCreateDto input) | POST        | /api/app/book/{id}/editor  |

https://docs.abp.io/en/abp/latest/API/Auto-API-Controllers#examples

the default api style is like above, but I don't want {id} in the url path.
for example, I wanna use '/api/app/book/editor?id={id}' not '/api/app/book/{id}/editor'
I wanna use '/api/app/book?id={id}' not '/api/app/book/{id}'

Is there a option to controll the 2 styles?

**Comment by maliming** [comment]
You can custom the **ConventionalRouteBuilder**.

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/Conventions/ConventionalRouteBuilder.cs#L13
