### ISSUE TITLE
Sending emails using Gmail SMTP (including "forgot password") with attachements

### ISSUE THREAD

**Issue by omaghd** [abpframework/abp#9884]
- Version 4.4
- Angular UI
- EF Core

Hello y'all ..
I need to send an email inside a service.
And also make the "forgot password" work.

I'm using angular so in the "setting-management" I set the settings there as follow:
- host: smtp.gmail.com
- username: myemail@gmail.com
- password: mypassword
- port: 465 / 587 (I tried both)
- ssl: true

**I already authorized less secure apps from https://myaccount.google.com/lesssecureapps** 

Using **IEmailSender**, I can't receive any emails, neither the "forgot password" page nor my service :
```
public async Task DoItAsync()
{
    await _emailSender.SendAsync(
        "another_email@gmail.com", // target email address
        "Email subject", // subject
        "This is email body..." // email body
    );
}
```
There's no error prompted, but nothing is received.

I also tried to add the settings from **MyProjectSettingDefinitionProvider** class
```
public override void Define(ISettingDefinitionContext context)
{
    context.Add(
        new SettingDefinition("Abp.Mailing.Smtp.Host", "smtp.gmail.com"),
        new SettingDefinition("Abp.Mailing.Smtp.Port", "587"),
        new SettingDefinition("Abp.Mailing.Smtp.UserName", "myemail@gmail.com"),
        new SettingDefinition("Abp.Mailing.Smtp.Password", "mypassword", isEncrypted: false),
        new SettingDefinition("Abp.Mailing.Smtp.EnableSsl", "true")
    );
}
```
I can see changes made in the Angular settings page, but nothing's working..

I tried to install MailKit package to include attachements, but I didn't know how to use it.

Any help please..

**Comment by JadynWong** [comment]
Are you using it in debug mode?

Check `ProjectNameDomainModule`,remove `NullEmailSender` line.

[Emailing](https://docs.abp.io/en/abp/latest/Emailing#nullemailsender)

**Comment by omaghd** [comment]
> Are you using it in debug mode?
> 
> Check `ProjectNameDomainModule`,remove `NullEmailSender` line.
> 
> [Emailing](https://docs.abp.io/en/abp/latest/Emailing#nullemailsender)

@JadynWong No bro, I'm starting the project without debugging

UPDATE:
After I removed this code
```
#if DEBUG
            context.Services.Replace(ServiceDescriptor.Singleton<IEmailSender, NullEmailSender>());
#endif
```
It prompts an internal error (without details) as response in Swagger.

**Comment by JadynWong** [comment]
Check your application log  at `ProjectName/logs/log.txt`.

`Volo.Abp.Emailing` use `System.Net.SmtpClient` as default mail sender.
`System.Net.SmtpClient` does not support Implicit SSL.
You can try to switch the port to 587 or install `Volo.Abp.MailKit`.

[https://stackoverflow.com/questions/1011245/how-can-i-send-emails-through-ssl-smtp-with-the-net-framework](https://stackoverflow.com/questions/1011245/how-can-i-send-emails-through-ssl-smtp-with-the-net-framework)

**Comment by maliming** [comment]
You can also check this demo.
https://github.com/abpframework/abp-samples/tree/master/EmailSendDemo
