### ISSUE TITLE
Custom UserClaimsPrincipalFactory no work

### ISSUE THREAD

**Issue by ArcherTrister** [abpframework/abp#9886]
- ABP Framework Version: 4.3.3
- Database Provider: EF Core

When I create the code, the class no work and breakpoints .Could you help me?
the code like this:
1. PreConfigureServices

``` csharp
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            PreConfigure<IdentityBuilder>(builder =>
            {
                builder.AddClaimsPrincipalFactory<CustomUserClaimsPrincipalFactory>();
            });
            PreConfigure<IIdentityServerBuilder>(builder =>
            {
                builder.AddProfileService<CustomProfileService>();
            });
        }
```

2. override CustomUserClaimsPrincipalFactory

``` csharp

public class CustomUserClaimsPrincipalFactory : UserClaimsPrincipalFactory<IdentityUser, IdentityRole>, ITransientDependency
{
        public CustomUserClaimsPrincipalFactory(
            IRepository<IdentityUser, Guid> identityUsers,
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IOptions<IdentityOptions> options)
            : base(
                  userManager,
                  roleManager,
                  options)
        {

        }

        [UnitOfWork]
        public async override Task<ClaimsPrincipal> CreateAsync(IdentityUser user)
        {
            var principal = await base.CreateAsync(user);
            ...
            return principal;
        }
}
```

**However, I still get *AbpClaimsPrincipalFactory* instance in the constructor**

![3](https://user-images.githubusercontent.com/35516482/130712588-c30b5af7-7bef-4fd5-8bd6-ebd958849fc3.png)

**Comment by maliming** [comment]
https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AbpIdentityServerDomainModule.cs#L86-L88

https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/modules/identityserver/src/Volo.Abp.IdentityServer.Domain/Volo/Abp/IdentityServer/AbpIdentityServerBuilderExtensions.cs#L41
