### ISSUE TITLE
[Request] Move permission name constants from Application.Contracts to Domain.Shared.

### ISSUE THREAD

**Issue by PMExtra** [abpframework/abp#9889]
For example, there is the [`IdentityPermissions`](https://github.com/abpframework/abp/blob/4.4.0/modules/identity/src/Volo.Abp.Identity.Application.Contracts/Volo/Abp/Identity/IdentityPermissions.cs) class in `Volo.Abp.Identity.Application.Contracts`

In my project, I want to make a `DataSeed` to initialize the preset roles with permissions, then I need to reference the `IdentityPermissions`.

In general, the `DataSeed` should be put in `MyProject.Domain` project. But this project shouldn't reference any `*.Application.Contracts`.

**Comment by maliming** [comment]
**In general,** the **Domain** does not participate in the business logic related to **permissions**. The permissions should be in the application service layer.

You can seed the permissions in other projects/layer.

**Comment by PMExtra** [comment]
@maliming So, shall we reference Application layer in DbMigrator project?
