### ISSUE TITLE
ABP Suite - adding "Public website" to solution gives errors

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#9892]
Creating a new solution in ABP Suite (latest version) for Angular gives a lot of these errors when you select to add a public website (regardless of if you have included CMS Tools). Do the same without adding the Public Website option and all is fine. 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1576	The line number specified for #line directive is missing or invalid	Acme.BookStore.Web.Public	M:\Projects\ASP.NET\ABP\src\Acme.BookStore\aspnet-core\src\Acme.BookStore.Web.Public\obj\Debug\net5.0\Razor\Components\Toolbar\LoginLink\Default.cshtml.g.cs	63	Active
```

This can easilly be reproduced in latest VS2019 and VS2019 Preview. 

**Now, this seem to be a Visual Studio / .NET bug rather than a ABP one but perhaps some adjustments are needed in ABP as well, if not, feel free to close this. Thanks.** 

https://stackoverflow.com/questions/68768704/visual-studio-2019-version-16-11-0-error-cs1576-the-line-number-specified-for

**Comment by maliming** [comment]
hi

I think this is not an error of ABP.
