### ISSUE TITLE
Publish events while unit of work is being completed, in the same unit of work

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#9896]
### Current Situation

ABP auto-publishes create, update and delete events for the entities:

* Local events ([documentation](https://docs.abp.io/en/abp/latest/Local-Event-Bus#pre-built-events))
  * `EntityCreatingEventData<T>`
  * `EntityCreatedEventData<T>`
  * `EntityUpdatingEventData<T>`
  * `EntityUpdatedEventData<T>`
  * `EntityDeletingEventData<T>`
  * `EntityDeletedEventData<T>`
  * `EntityChangingEventData<T>`
  * `EntityChangedEventData<T>`
* Distributed events ([documentation](https://docs.abp.io/en/abp/latest/Distributed-Event-Bus#pre-defined-events))
  * `EntityCreatedEto<T>`
  * `EntityUpdatedEto<T>`
  * `EntityDeletedEto<T>`

These events are published on DbContext.SaveChangesAsync for EF Core, and in repository's create/update/delete methods for MongoDB. So, for EF Core, they are published when we manually call Unit Of Work's SaveChangesAsync, or the UOW is completed. However, for MongoDB, they are immediately published when we call repository's create/update/delete methods. Publishing means `PublishAsync` method of `ILocalEventBus` or `IDistributedEventBus` is called. `ILocalEventBus.PublishAsync` immediately execute the handlers and `IDistributedEventBus.PublishAsync` immediately sends event to the message broker (e.g. RabbitMQ). Remember that IDistributedEventBus is actually in-process and delivers events to the local event bus if we don't explicitly install one of the message broker integrations, like RabbitMQ.

We can also publish events using `ILocalEventBus` and `IDistributedEventBus` and these events are immediately published.

Also, past-tense events (like `EntityCreatedEventData<T>`, `EntityUpdatedEventData<T>`, `EntityCreatedEto<T>` and `EntityUpdatedEto<T>`) are published after the current unit of work. That means, if an event handler throws an exception, it can not rollback the transaction that the event was published in. Continuous tense events (like `EntityCreatingEventData<T>`) are still published in the UOW, so the handler can rollback the transaction.

### New approach

Beginning with ABP v5.0, auto-published create, update and delete events for the entities will be always published at the end of the unit of work (when `IUnitOfWork.CompleteAsync` is called) and included in the current transaction. In this way, a handler can throw exception and can rollback the transaction.

If you manually call `PublishAsync` method of an event bus, the published event is stored in the current unit of work and actually published at the end of the unit of work and included in the current transaction.

With the new approach;

* All the event handlers are executed in the current unit of work, so the whole process becomes transactional. This is very useful and simple model for non-distributed systems.
* Event publish system is being compatible between EF Core and MongoDB and it will be more consistent.
* Since we publish all events at the end of the unit of work, we can ensure the events are published in the right order. Previously, manually published events were being published before pre-built entity create/update/delete events for EF Core since entity events were being published at the end of the UOW (or when we call SaveChanges manually).

**Comment by leonkosak** [comment]
@hikalkan, will this approach solve [this issue](https://github.com/abpframework/abp/issues/6126#issuecomment-843348740)?
