### ISSUE TITLE
Incorrect title in documentation. "Razor Integration" instead of "Scriban Integration"

### ISSUE THREAD

**Issue by OriginalArye** [abpframework/abp#9898]
On this page: [https://docs.abp.io/en/abp/latest/Text-Templating-Scriban](https://docs.abp.io/en/abp/latest/Text-Templating-Scriban)
An incorrect title appears.
It should be "Scriban Integration".

**Comment by realLiangshiwei** [comment]
Thanks @OriginalArye , we will fix it.
