### ISSUE TITLE
Problem with Admin menu for Public website feature

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#9903]
There seem to be a problem with the Admin menu when adding a Public website to an ABP Project (Angular in our case but don't think it matters as the project is in MVC/Razor regardless). 

The menu expands ok but when you try to use it and move the mouse cursor down, the "Contact us" seem to have higher priority making the admin menu disappear as soon as cursor is above the "Contact us" section.

**Comment by improwise** [comment]
![image](https://user-images.githubusercontent.com/2812422/130998811-9eecfd60-517d-4177-8a9c-5a469fd2be73.png)

(Ignore the broken image icon which seems to be a temporary problem)

**Comment by improwise** [comment]
Can add that the language menu does not have this problem and work as it should.

**Comment by maliming** [comment]
This will be resolve in 4.4.3.
