### ISSUE TITLE
Faulty path in Angular module generated by ABP Suite

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#9904]
There seem to be a problem in the latest version of ABP Suite when generating Angular modules, probably in a template. The import statement is generated as:

`import { AuthorService } from '../../../proxy/controllers/authors/author.service';`

When it should be 

`import { AuthorService } from '../../../proxy/authors/author.service';`

Without the controller part. 

Changing it manually will remove errors and the generated module works fine.

**Comment by improwise** [comment]
I believe this is where the error originates:

Frontend.Angular.__name@kebab__.component.ts.template

`import { <%= name %>Service } from '<%= relativePathFromComponentToService(scope, namespace, name) %>';
`

Not sure if that is something we can change ourselved.

**Comment by yekalkan** [comment]
Hi @improwise,

This problem will be fixed in suite v4.4.1, planned to be released on next monday.

Please use https://support.abp.io/QA/Questions for issues related with Suite.
