### ISSUE TITLE
Abp.io Document Incorrect Sample `Acme.BookStore.EntityFrameworkCore.DbMigrations`

### ISSUE THREAD

**Issue by vchy1997** [abpframework/abp#9906]
doc version : 4.4
doc lang ： zh

The Migration Project use the `Acme.BookStore.EntityFrameworkCore` project directory
But zh Doc Use `Acme.BookStore.EntityFrameworkCore.DbMigrations`

Correct Doc：https://github.com/abpframework/abp/blame/rel-4.4/docs/en/Tutorials/Part-1.md#L190
InCorrect Doc : https://github.com/abpframework/abp/blame/rel-4.4/docs/zh-Hans/Tutorials/Part-1.md#L190

**Comment by maliming** [comment]
Please use English as the standard, and the documents in other languages will be updated gradually.
