### ISSUE TITLE
Admin password mismatch between startup templates

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#9911]
Not sure if this is deliberate but just noticed the startup templates have slightly different default admin password. Angular one uses "1q2w3e*" while the MVC one use "1q2w3E*". The MVC one use "1q2w3e" for Identity Server, Swagger etc. though.

**Comment by maliming** [comment]
`1q2w3E*` is the password of the admin user.
`1q2w3e*` is the client secret of the Identity Client.  https://docs.identityserver.io/en/release/topics/secrets.html#creating-a-shared-secret
