### ISSUE TITLE
about IdentityUser and AbpUsers   in abp4.4

### ISSUE THREAD

**Issue by 312977** [abpframework/abp#9912]
### in abpvnext4.4  
the dbcontext  has DbSet<IdentityUser> , no dbset abpuser.  but  when database created,there was tow tables about user→AbpUsers  and IdentityUser

i have an entity  TenantInfo like this 

`public class TenantInfo : FullAuditedEntity<int>, IMultiTenant
    {
        public DateTime DaoQiShiJian { get; set; }
        .......
        public virtual IdentityUser User { get; set; }
        public virtual Guid UserId { get; set; }
    }`

 i created some TenantInfo data to database ,successed

but when i query about it use:

`var dbContext = await GetDbContextAsync();
            var a = await dbContext.Set<TenantInfo>().Include(c => c.Tenant).Include(c => c.User).Select(c => new
            {
                Name = c.Tenant.Name,
                UserName = c.User.UserName,
            }).ToListAsync();
`
but  UserName   is null
and  another question:  c. User  has no filed Name...why?  
in database ,table   AbpUsers   has filed Name,  IdentityUser table has no name filed,
when i wannt include table AbpUsers    ,how to fix it?  

I must solve this problem as soon as possible,please!!!!!please!!!!!please!!!!!please!!!!!please!!!!!please!!!!!please!!!!!please!!!!!

**Comment by JadynWong** [comment]
See the article [Unifying DbContexts for EF Core / Removing the EF Core Migrations Project](https://community.abp.io/articles/unifying-dbcontexts-for-ef-core-removing-the-ef-core-migrations-project-nsyhrtna
).

If you could provide a sample project to reproduce the problem, perhaps the problem would be more easily solved.

**Comment by realLiangshiwei** [comment]
I don't think this is related to ABP,  but as JadynWong said,  https://community.abp.io/articles/unifying-dbcontexts-for-ef-core-removing-the-ef-core-migrations-project-nsyhrtna will help you. it will make it easier to create navigation properties with the module table
