### ISSUE TITLE
logoUrl not working in Angular template

### ISSUE THREAD

**Issue by improwise** [abpframework/abp#9916]
Can't seem to get the logoUrl of the Angular application to work. When having something like this:

```
export const environment = {
  production: false,
  application: {
    baseUrl,
    name: 'BookStore222',
    logoUrl: 'assets/images/logo/logo-light.png'

  },
```

the name attribute is reflected on the page when changed but the logo displayed don't change regardless of what we enter as logoUrl. Even if we enter a broken logoUrl, the default logotype is still displayed. 

Since name changes are applied, there should be no question about the correct environment file being used etc.

**Comment by improwise** [comment]
This is with the Lepton Theme in ABP Commercial, not sure if that changes things.

**Comment by maliming** [comment]
hi

Please discuss the commercial on https://support.abp.io/ 
Thanks.
