### ISSUE TITLE
[Discuss] How to update the list of Chinese document directories?

### ISSUE THREAD

**Issue by Gsonovb** [abpframework/abp#9918]
Hello everyone. 
Recently, in learning ABP, I found that the navigation of Chinese documents is much worse than that of English. Some documents have been translated, but they have not appeared. 
So do you have any requirements for navigation updates? 
Thank you.

----

大家好

最近在学习ABP，我发现中文文档导航与英文差了好多，有些文档已经翻译了，但是并没有出现。

所以问一下对于导航更新有什么要求吗？谢谢

**Comment by realLiangshiwei** [comment]
English documents are always new,  It is better to read English documents to learn.

See https://docs.abp.io/en/abp/latest/Contribution/Index#document-translation

We always welcome contributions
