### ISSUE TITLE
How can i use EntityFrameworkCore module map data view?

### ISSUE THREAD

**Issue by mentianyi** [abpframework/abp#9919]
`            builder.Entity<MyView>(b =>
            {
                b.ToView("vw_MyView", options.Schema);
            });`

1.Can i use like this?
2.Myview is a Entity? where class is it's parent class?
3. Do I need use migrationBuilder to support migration these view definetions?

**Comment by maliming** [comment]
This is related to EF Core, which you can try.

https://github.com/abpframework/abp/blob/5ab37c78e4e976c2be51e52f7791c5468a958211/framework/test/Volo.Abp.EntityFrameworkCore.Tests/Volo/Abp/TestApp/EntityFrameworkCore/TestAppDbContext.cs#L21
https://github.com/abpframework/abp/blob/5ab37c78e4e976c2be51e52f7791c5468a958211/framework/test/Volo.Abp.EntityFrameworkCore.Tests/Volo/Abp/TestApp/EntityFrameworkCore/TestAppDbContext.cs#L59

**Comment by mentianyi** [comment]
Thank you, issue is solved.
