### ISSUE TITLE
Volo.Abp.Features , how to check value of feature In Mvc Web project ?

### ISSUE THREAD

**Issue by mrs01dev** [abpframework/abp#9922]
Regarding Features: 
https://docs.abp.io/en/abp/latest/Features
and 
https://docs.abp.io/en/abp/latest/UI/AspNetCore/JavaScript-API/Features
For Razor Pages UI , kindly , please :
specify How to check value of  Features  in Razor Pages UI?
- as per documentation
 private readonly IFeatureChecker _featureChecker;

    public ProductController(IFeatureChecker featureChecker)
    {
        _featureChecker = featureChecker;
    } 
var maxProductCountLimit = await _featureChecker.GetAsync<int>("MyApp.MaxProductCount");
-
specify How  to check value of  Features  in menu -IMenuContributor- page?

my environment is:
ABP Framework version: 4.3.
User Interface :MVC
Database provider :EF Core

Thanks.

**Comment by EngincanV** [comment]
Hi @mrs01dev, you can get the `IFeatureChecker` interface by using `MenuConfigurationContext`'s **ServiceProvider** property.

```csharp
public async Task ConfigureMenuAsync(MenuConfigurationContext context)
{
   //..

  var featureChecker = (IFeatureChecker) context.ServiceProvider.GetRequiredService(typeof(IFeatureChecker));
  var myFeature = await featureChecker.GetAsync<bool>("MyApp.MyPermission");

   if(myFeature) 
   {
       context.Menu.Items.Insert(0, new ApplicationMenuItem("name", "displayName"));
   }
}
```

**Comment by mrs01dev** [comment]
Hi @EngincanV 
Thank you very much.
