### ISSUE TITLE
Multiple database migration issues in DBMigrationService

### ISSUE THREAD

**Issue by olicooper** [abpframework/abp#9936]
ABP Framework version: 4.4.0
Database provider: EF Core

I was upgrading from 4.3.0 to 4.4.0 when I spotted a few possible issues for people using multiple databases. In summary I don't think the Domain module `DbMigrationService` that is included with all startup projects will work for multiple databases now that abp has moved away from having a separate `DbMigrations` project for each database. I have used the BookStore demo for reference. Here are a few potential issues I have spotted (there could be more):

1. The [DbMigrationService.cs](https://github.com/abpframework/abp-samples/blob/567e1583668b52f8b0202cc67958a9dc0fd7ca4f/EfCoreMigrationDemo/src/BookStore.Domain/Data/BookStoreDbMigrationService.cs#L153) only checks if a single "Migrations" folder exists, but there could be many (see [the EntityFrameworkCore folder](https://github.com/abpframework/abp-samples/tree/master/EfCoreMigrationDemo/src/BookStore.EntityFrameworkCore)).
2. The command `abp create-migration-and-run-migrator` [used here](https://github.com/abpframework/abp-samples/blob/567e1583668b52f8b0202cc67958a9dc0fd7ca4f/EfCoreMigrationDemo/src/BookStore.Domain/Data/BookStoreDbMigrationService.cs#L175) doesn't seem to account for multiple 'Migrations' directories in the `--output-dir` argument when running `AddMigrationAndGetOutput`. https://github.com/abpframework/abp/blob/2eafeaddb29f6a950168ce68b13503681d37e9d2/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/Commands/CreateMigrationAndRunMigratorCommand.cs#L101-L111

My project structure looks similar to the image below. I'd love to keep migrations organised inside a folder for each DbContext..
![image](https://user-images.githubusercontent.com/22296715/131534183-1a1cc493-451b-4b61-ae4c-a3f3d31f60e3.png)

Could this be included as part of a 4.4-patch?

**Comment by maliming** [comment]
hi

I suggest you manually execute the migration and other commands. **CLI** is only designed for template projects, it can't handle the complex projects.

**Comment by mugambiwarwema** [comment]
@maliming 

I just installed v4.4 with Postgresql and the initial migration fails.

```
Creating initial migration...
'abp' is not recognized as an internal or external command,
operable program or batch file.

```

I have updated my connection string accordingly in .Host and .DbMigrator projects yet it fails.

**Comment by maliming** [comment]
> 'abp' is not recognized as an internal or external command,

You need to install the CLI.
`dotnet tool install --global Volo.Abp.Cli --version 4.4.0`

**Comment by olicooper** [comment]
> CLI is only designed for template projects

This isn't me using the CLI, this is part of all startup projects (see the `BookStoreDbMigrationService` in the Domain module). Abp just uses the CLI as part of the process.

**Comment by maliming** [comment]
In the same way, you can also change the `BookStoreDbMigrationService` to be compatible with your new structure.
