### ISSUE TITLE
Hope support for Cassandra

### ISSUE THREAD

**Issue by SarcoZ** [abpframework/abp#995]
I hope a package called Volo.Abp.Cassandra, cassandra has a c# driver called CassandraCSharpDriver which is both support for cassandra and scyllaDb,can encapsulation with it,build a package Volo.Abp.Cassandra

**Comment by maliming** [comment]
I guess what you said is: https://github.com/datastax/csharp-driver, I have never seen anyone mention it in ASP.NET Boilerplate.

If this is what you need, you can use it directly in your project. If this is a very popular library, maybe abp will integrate it in the future.

**Comment by SarcoZ** [comment]
@maliming:  In iot and low-latency or big data scenarios,this will performance well, if there is no plan support it,I will encapsulation is by myself

**Comment by bdieaq** [comment]
Hi @SarcoZ 
Did you supported Cassnadra with ABP?
Regards
