### ISSUE TITLE
Angular UI: Remove NGXS dependency & states

### ISSUE THREAD

**Issue by mehmet-erim** [abpframework/abp#9952]
We decided to remove NGXS from ABP packages. We thought we could achieve the same experience with Angular services instead of using an external store package. So we will replace the NGXS states with data services.

If you use the NGXS, you should install the package to your project to prevent errors.
You can run the following command to install the NGXS:
```
npm install @ngxs/store
```

### Breaking Change

The following NGXS states and namespaces will be removed:

States:
* ConfigState
* ProfileState
* IdentityState
* TenantManagementState
* SettingManagementState
* PermissionManagementState

Namespaces:
* Config
* Profile
* Identity
* TenantManagement
* SettingManagement
* PermissionManagement

> A migration guide will be prepared about that.

**Comment by Moustafa20** [comment]
could you please mention the reson why doing this ? is there any problems with NGXS ? what about NGRX ?

**Comment by bnymncoskuner** [comment]
Hello @Moustafa20,

We aim to make the ABP Framework free of any state-management solutions. Our users should be able to use the ABP Framework with any library/framework of their choice. In the current state of the framework, it comes as integrated with NGXS, and it does not make sense to use any other solutions. Thus, with v5.0 we will leave this choice to you.
