### ISSUE TITLE
Dynamic Api Authorization

### ISSUE THREAD

**Issue by amLabib** [abpframework/abp#9956]
Hi, 
We are developing a multi module applications (.Net Core & Angular), currently the application is monolithic, but we are planning to separate each module in the future, So in order to modules  to communicate with each other, we created some Dynamic APIs.

Let Say we have BookAppService and BookApi
BookApi have a method called "GetAllBooks()", which calls "GetAll()" method in BookAppService.

The problem is: if GetAll() method in BookAppService has a "Authorize" attribute, it will throw an exception as user not authorized.

Note: issue only happen if we use **IHttpClientProxy<IBookApi>**, but works fine if we use IBookApi Direct, but in future we must use IHttpClientProxy, since the module will not contain implementation for this interface

`context.Services.AddHttpClientProxies(
                typeof(IBookApi).Assembly,
                remoteServiceConfigurationName: RemoteServiceName,
                asDefaultServices: false
            );`

and by removing the authorize attribute it will work fine, but notice that "currentUser" object is null.
Note: CurrentTenant Object is not null
so is there any missing steps needed to be done in order to enable user authorization and authentication??

**Comment by maliming** [comment]
hi

You shouldn't use `IHttpClientProxy` in a monolithic project, You can refer to tiered or microservice projects to check how to use dynamic API proxy.

https://github.com/abpframework/eShopOnAbp
