### ISSUE TITLE
Edit Permission for user shows the Guid of the user and not the name

### ISSUE THREAD

**Issue by rlavaud** [abpframework/abp#9962]
*V4.4.1 **ABP Framework version**.
*Blazor **User Interface** 
* EFCore MySQL 

* Steps needed to **reproduce** the problem.
* Create New Blazor App
* Login
* Edit User Permission
The GUID of the users shows up and not the name of the user.

![image](https://user-images.githubusercontent.com/11966443/131941504-153babdc-2c5d-46b8-a43b-05018dbf9a8d.png)

The Same steps for roles seems to work correctly.

**Comment by maliming** [comment]
I think we can enhance the UI by adding a `DisplayName` paramter.

**Comment by begandroide** [comment]
hi! i has the same issue on Angular UI (ABP 4.4.2). I can see that solution is for ABP 5.0, some workaround for the moment?

<img width="1788" alt="Captura de Pantalla 2021-09-18 a la(s) 19 38 24" src="https://user-images.githubusercontent.com/22018004/133910697-5797ad05-bb7c-4000-8076-1574ce9da004.png">
