### ISSUE TITLE
Volo.Abp.FluentValidation - Add ErrorCode field to ValidationResult class

### ISSUE THREAD

**Issue by khanhtranchi** [abpframework/abp#9964]
Because the FluentValidation support ErrorCode, it will be easier to write unit test if we can use the ErrorCode instead of the ErrorMessage. In case we use the FluentValidation, we should set ErrorCode from FluentValidation  to AbpValidationResult (this is new class, extended from ValidationResult class)

Thanks.

**Comment by maliming** [comment]
hi

Can you share some code to explain it?

**Comment by khanhtranchi** [comment]
At the AddErrors method of FluentObjectValidationContributor class, Could we add the ErrorCode returned by FluentValidation ? For example:
if (!result.IsValid)
            {
                context.Errors.AddRange(
                    result.Errors.Select(
                        error =>
                            new ValidationResult(error.ErrorMessage, **error.ErrorCode**, new[] { error.PropertyName })
                    )
                );
            }

**Comment by maliming** [comment]
I think you can custom the `FluentObjectValidationContributor `

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.FluentValidation/Volo/Abp/FluentValidation/FluentObjectValidationContributor.cs#L37
