### ISSUE TITLE
Mongo2go doesn't run Dispose when testing finish

### ISSUE THREAD

**Issue by khanhtranchi** [abpframework/abp#9969]
I'm using Module Startup Template (abp version 4.3.2), and found that if we run test\Volo.CmsKit.MongoDB.Tests, after finish testing the method Dispose in MongoDbFixture class is run to cleanup temp folder generated by Mongo2go.

But if we run another test projects like test\Volo.CmsKit.Domain.Tests, that depended on the test\xx.xx.MongoDB.Tests:
namespace Volo.CmsKit
{
    [DependsOn(
        typeof(**CmsKitMongoDbTestModule**)
        )]
    public class CmsKitDomainTestModule : AbpModule
    {
    }
}

After finish testing, the method Disopose doesn't run that lead to full of hdd.

Steps to reproduce:
- Clone Volo.CmsKit projecct
- Change test\Volo.CmsKit.Domain.Tests depended to CmsKitMongoDbTestModule instead of entity framework
- View hdd capacity and mark debug at 2 methods MongoDbFixture and Dispose in MongoDbFixture class.
- Right click project test\Volo.CmsKit.Domain.Tests and run Debug Test
- We can see that we jump into MongoDbFixture  method for initializing the MongDb2Go, but when finish testing we don't run Dispose method, and the hdd volumn doesn't release the capacity used.

Thanks.

**Comment by realLiangshiwei** [comment]
Add `[Collection(MongoTestCollection.Name)]` to unit tests class

**Comment by khanhtranchi** [comment]
have tried, it doesn't work

**Comment by realLiangshiwei** [comment]
You can create a template  `abp new Qa -d mongodb`, and check its `domain.tests` project

**Comment by khanhtranchi** [comment]
hi @realLiangshiwei ,

I found that this issue happen in this startup template:
abp new QA -t module -d mongodb -u blazor --separate-identity-server 

I add the attribute [Collection(MongoTestCollection.Name)] to unit tests class of Domain test project. But it doesn't work. By the way, although specific database is mongodb but project still use entity framework, we need to configure a lot of related projects back to mongodb repository.

The other template work properly.

Thanks.

**Comment by khanhtranchi** [comment]
Hi @realLiangshiwei ,

Did you verify this case ? Or I need to open another issue.

Thanks.

**Comment by realLiangshiwei** [comment]
Can you share a project to reproduce? thanks

**Comment by khanhtranchi** [comment]
@realLiangshiwei , you can use this project.
https://drive.google.com/file/d/1vLKgCPI6oUN21tSZ4CxJXTPKHyHnUjGm/view?usp=sharing

**Comment by realLiangshiwei** [comment]
I don't think this is a problem, as I said you can create a new project to compare. : )

![image](https://user-images.githubusercontent.com/16813853/132609784-681e5c0c-2e05-4954-a49b-1942130a4ae1.png)
