### ISSUE TITLE
How to call a stored procedure using ABP framework in a multitenant environment ?

### ISSUE THREAD

**Issue by monami-work** [abpframework/abp#9974]
* Your **ABP Framework version**. : 4.3
* Your database provider(EF Core/MongoDB)  :EF Core
* Exception message and **stack trace** if available (check the logs). NA
 
Hi , I am not able to call stored procedure appropriately in a multi tenant environment.

```
string sql = 'EXEC SP_GetProducts @lastUpdated, @ProductName";
    
List<SqlParameter> params = new List<SqlParameter>{ new SqlParameter { ParameterName = "@lastUpdated",  Value = ....},  new SqlParameter { ParameterName = "@ProductName",  Value = ....} }
    ......
    
    context.products.FromSqlRaw<Product>(sql, params.ToArray()).ToListAsync();
```
I am using the ABP framework in my webapi and implemented multi tenancy. 
I have followed the following link for the same -
docs.abp.io/en/abp/4.4/Multi-Tenancy

Every other database calls are working fine except the stored procedure call. Sometimes ( Not Always)  it is fetching data from wrong tenant. Weird thing is context.Database.GetConnectionString() confirms that context is referring to correct tenant database.

To test certain scenarios I am logging out and logging in from one tenant to another tenant or host. And under these circumstances what I notice is that, sometimes, the stored procedure is fetching data from a different tenant database than the currently logged in tenant. 

The problem does not seem to be related to stored procedure definition. I even tried with a simple definition -
```
 CREATE PROCEDURE SP_GetProducts @lastUpdated datetime2, @ProductName varchar2 
AS SELECT * FROM Product
GO;

```

This stored procedure is called as a part of SignalR call.

Please suggest what may be I am doing wrong.

**Comment by maliming** [comment]
hi

We need more info.

* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.
