### ISSUE TITLE
Create a many to many relationship example with ABP and EF Core

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#9975]
Users are having issue when trying to create a basic many-to-many EF Core relationship. 
Make a simple sample with ABP (open-source) and write a step by step document.
reported at https://support.abp.io/QA/Questions/1805/Many-to-many-realtionship-returning-null

**Comment by EngincanV** [comment]
Article: https://community.abp.io/articles/many-to-many-relationship-with-abp-and-ef-core-g7rm2qut
