### ISSUE TITLE
CLI - local framework ref generate wrong path

### ISSUE THREAD

**Issue by hitaspdotnet** [abpframework/abp#9981]
Because of non-classified module's references CLI not working. 
Steps:
1. `abp get-source AnyModuleName --local-framework-ref --abp-path "D:\Github\abp"` OR `abp new AnyModuleName -t module-pro --local-framework-ref --abp-path "D:\Github\abp"`
2. check the source there is some reference 
`D:\Github\abp\framework\abp\framework`
`D:\Github\abp\framework\modules\identity`
`D:\Github\abp\framework\setting-management`

The biggest problem is when you need to generate any type of Pro templates with local framework, where there is not any integration

**Comment by yekalkan** [comment]
Hi @hitaspdotnet

There is also `--volo-path` parameter that is available to enter the path of commercial packages/projects. Example:

`--local-framework-ref --abp-path "D:\Github\abp" --volo-path "D:\Github\volo"`

Since customers don't have access to commercial Volo repository for obvious reasons, we didn't document this parameter. But we use it internally.

If you like, you can download source codes of modules to "D:\Github\volo\abp\{module_name}" and then use `--volo-path` parameter. You will need a minimum manual work this way.

**Comment by hitaspdotnet** [comment]
@yekalkan What about licensing packages? When the customers haven't access to that packages I think you should skip that packages `Commercial.SuiteTemplate`, `Commercial.Core` and the UI packages used by lepton

**Comment by yekalkan** [comment]
> You will need a minimum manual work this way.

**Comment by hitaspdotnet** [comment]
I think classified references can reduce manual working:
1. Use solution names as directory in module folder `Volo.Abp.Identity` instead of `identity`. When users downloading modules they haven't idea about Volo naming rules
2. Use standard hit paths in all csproj files: 
2.1. Convert all framework references to `"..\..\..\..\framework\src\...."` and `"..\..\..\..\abp\framework\src\...."` for commercial
2.2. Convert all modules references to `"..\..\..\..\modules\{solutionName}\src\...."` and `"..\..\..\..\abp\modules\{solutionName}\\src\...."` for commercial

**Comment by yekalkan** [comment]
We don't have plans for this feature.

**Comment by hitaspdotnet** [comment]
This isn't feature, This is problem, where we have `identity`, `identityserver`, `account`, `audit-logging` directories in free side and same name in commercial. You should try to create a App with pro template and local framework reference as customer, who not access to volo repository and name of module direcotires to be able to touch the problem
Thanks for answers.

**Comment by hitaspdotnet** [comment]
`--volo-path` works just for licensing packages not any pro modules
```powershell
PS D:\> abp get-source Volo.CmsKit.Pro -o "D:\Github\hitasp\volo\cms-kit" --local-framework-ref --abp-path "D:\Github\hitasp\abp" --volo-path "D:\Github\hitasp\volo"
[19:30:21 INF] ABP CLI (https://abp.io)
[19:30:21 INF] Version 4.4.2 (Stable)
[19:30:23 INF] Output folder: D:\Github\hitasp\volo\Volo.CmsKit.Pro
[19:30:23 INF] GitHub Abp Local Repository Path: D:\Github\hitasp\abp
[19:30:23 INF] GitHub Volo Local Repository Path: D:\Github\hitasp\volo
[19:30:23 INF] Downloading source code of Volo.CmsKit.Pro
[19:30:23 INF] Version:
[19:30:23 INF] Output folder: D:\Github\hitasp\volo\cms-kit
[19:30:24 INF] Using cached module: Volo.CmsKit.Pro, version: 4.4.2
[19:30:26 INF] Check out the documents at https://docs.abp.io/en/commercial/latest/modules/cms-kit/index
[19:30:27 INF] 'Volo.CmsKit.Pro' has been successfully downloaded to 'D:\Github\hitasp\volo\cms-kit'
PS D:\>
```
And the result:
```csproj
  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Hosting" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(MicrosoftPackageVersion)" />
    <ProjectReference Include="D:\Github\hitasp\abp\framework\src\Volo.Abp.Autofac\Volo.Abp.Autofac.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\lepton-theme\src\Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton\Volo.Abp.AspNetCore.Mvc.UI.Theme.Lepton.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\lepton-theme\src\Volo.Abp.LeptonTheme.Management.Web\Volo.Abp.LeptonTheme.Management.Web.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\lepton-theme\src\Volo.Abp.LeptonTheme.Management.Application\Volo.Abp.LeptonTheme.Management.Application.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\lepton-theme\src\Volo.Abp.LeptonTheme.Management.Domain\Volo.Abp.LeptonTheme.Management.Domain.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\framework\src\Volo.Abp.EntityFrameworkCore.SqlServer\Volo.Abp.EntityFrameworkCore.SqlServer.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\audit-logging\src\Volo.Abp.AuditLogging.EntityFrameworkCore\Volo.Abp.AuditLogging.EntityFrameworkCore.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\account\src\Volo.Abp.Account.Pro.Public.Web\Volo.Abp.Account.Pro.Public.Web.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\account\src\Volo.Abp.Account.Pro.Public.Application\Volo.Abp.Account.Pro.Public.Application.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\setting-management\src\Volo.Abp.SettingManagement.EntityFrameworkCore\Volo.Abp.SettingManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\setting-management\src\Volo.Abp.SettingManagement.Application\Volo.Abp.SettingManagement.Application.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\permission-management\src\Volo.Abp.PermissionManagement.Application\Volo.Abp.PermissionManagement.Application.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\permission-management\src\Volo.Abp.PermissionManagement.EntityFrameworkCore\Volo.Abp.PermissionManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\identity-pro\src\Volo.Abp.Identity.Pro.Application\Volo.Abp.Identity.Pro.Application.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\identity-pro\src\Volo.Abp.Identity.Pro.Web\Volo.Abp.Identity.Pro.Web.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\identity-pro\src\Volo.Abp.Identity.Pro.EntityFrameworkCore\Volo.Abp.Identity.Pro.EntityFrameworkCore.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\identity\src\Volo.Abp.PermissionManagement.Domain.Identity\Volo.Abp.PermissionManagement.Domain.Identity.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\saas\src\Volo.Saas.Host.Web\Volo.Saas.Host.Web.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\saas\src\Volo.Saas.Host.Application\Volo.Saas.Host.Application.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\saas\src\Volo.Saas.EntityFrameworkCore\Volo.Saas.EntityFrameworkCore.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\blob-storing-database\src\Volo.Abp.BlobStoring.Database.EntityFrameworkCore\Volo.Abp.BlobStoring.Database.EntityFrameworkCore.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\feature-management\src\Volo.Abp.FeatureManagement.Application\Volo.Abp.FeatureManagement.Application.csproj" />
    <ProjectReference Include="D:\Github\hitasp\abp\modules\feature-management\src\Volo.Abp.FeatureManagement.EntityFrameworkCore\Volo.Abp.FeatureManagement.EntityFrameworkCore.csproj" />
  </ItemGroup>
```

**Comment by hitaspdotnet** [comment]
The original template is clear, Based on the original Volo has an `abp` instead of `modules` directory that contains pro modules, and the problem is CLI uses `abp\` as replace marker.
For who has same problem, use CLI bug to solve CLI bug, let abp-path empty and use volo-path project generate without any touch in replace package references step.
`abp get-source Volo.CmsKit.Pro -o "D:\Github\hitasp\volo\cms-kit" --local-framework-ref --abp-path --volo-path "D:\Github\hitasp\volo"`
