### ISSUE TITLE
Add enable/disable user account

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#9985]
Just like Windows User Accounts, a new field named `IsDisabled` can be added to the `User` entity.
And this field should be checked when logging in.
![image](https://user-images.githubusercontent.com/9526587/132486031-e9b15b98-ce5d-4818-865f-c0a25b88b0f3.png)

Also show this field in user list ( disabled accounts can be gray -text muted- )

**Comment by maliming** [comment]
Use `IsActive` will be better. Just like: https://github.com/abpframework/abp/pull/8814
