### ISSUE TITLE
Multi Tenant : Single Deployment with Multi Database

### ISSUE THREAD

**Issue by M-Abdelmoniam** [abpframework/abp#9986]
I want an example project that provide :

* database for each tenant
* configure subdomain to detect the selected tenant

**Comment by maliming** [comment]
There is no such example. I suggest you start from the document.

https://docs.abp.io/en/abp/latest/
https://github.com/abpframework/abp-samples/tree/master/DomainTenantResolver

**Comment by johnwanzhi** [comment]
I think there should be such a sample project, because so far, there is no such sample project

**Comment by evenlee** [comment]
I used data seeder to init tenants,migrator will create database accordingly, you can create many in the seeder too, the seeder located in Domain project.

namespace MyTenant.API.MultiTenancy
{
    public class TenantDataSeedContributor : IDataSeedContributor, ITransientDependency
    {
        private TenantManager _tenantManager;
        private ITenantRepository _tenantRepository;
        private readonly string DefaultTenantName = "Tenant1";
        public TenantDataSeedContributor(
            TenantManager tenantManager,
            ITenantRepository tenantRepository)
        {
            _tenantManager = tenantManager;
            _tenantRepository = tenantRepository;
        }

        public async Task SeedAsync(DataSeedContext context)
        {
            if (context.TenantId != null)
            {
                //only seed in host db
                return;
            }
          
            var name =  DefaultTenantName;
            var connectionString = " Server=.;Database=MyTenant1;Trusted_Connection=True";
            var entity = await _tenantRepository.FindByNameAsync(name,true);
            if (entity == null)
            {
                entity = await _tenantManager.CreateAsync(name);
                entity.SetDefaultConnectionString(connectionString);
                await _tenantRepository.InsertAsync(entity);
            }

            if (string.IsNullOrEmpty(entity.FindDefaultConnectionString()))
            {
                entity.SetDefaultConnectionString(connectionString);
                await _tenantRepository.UpdateAsync(entity);
            }
        }
    }
}
