### ISSUE TITLE
how to customer dynamic permission

### ISSUE THREAD

**Issue by snowchenlei** [abpframework/abp#9992]
Hello:
The permissions are now defined in code!
But for now:
I have a category table,User's permission need to be associated with this dynamic category

`category table`
| id     | name |
| ----------- | ----------- |
| 1     | bug       |
| 2   | suggestion  |

May I ask how this function can be implemented.
Thank you for your help

**Comment by maliming** [comment]
You can check the document of abp and net core.
https://docs.abp.io/en/abp/latest/Authorization#permission-value-providers
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-5.0

**Comment by snowchenlei** [comment]
Thank you for your reply!

I read the above document,The parameters are static. but the categoryId is dynamic,and I don't know what the values will be
CategoryId is included in the request parameters
Now,I extended the `AbpPermissionGrants` table to add CategoryId,And do the following query to determine whether permissions are included.
```
.AnyAsync(p =>
                    p.CategoryId == categoryId
                    && p.PermissionName == permissionName
                    && providerNames.Contains(p.ProviderName)
                    && p.ProviderKey == providerKey);
```
Barely met the demand,But this method is not beautiful on the html page.
It would be great if there was a better way!

**Comment by maliming** [comment]
This is nothing to do with abp.

**Comment by puschie286** [comment]
@snowchenlei hey we had a similar problem - our solution was to allow [dynamic permission](https://github.com/puschie286/abp/tree/dynamic-permissions) changes. with this you can make the category id part of the permission name - a good point for initilization is OnPostApplicationInitialization ( ApplicationModule ).

hope this will help

**Comment by snowchenlei** [comment]
> @snowchenlei hey we had a similar problem - our solution was to allow [dynamic permission](https://github.com/puschie286/abp/tree/dynamic-permissions) changes. with this you can make the category id part of the permission name - a good point for initilization is OnPostApplicationInitialization ( ApplicationModule ).
> 
> hope this will help

That's a good idea,Thanks
But I want to know how to know policy in AuthorizeAttribute

**Comment by puschie286** [comment]
> That's a good idea,Thanks
> But I want to know how to know policy in AuthorizeAttribute

to use the authorize attribute for dynamic informations you need to create your own implementation / version. you can check [here](https://stackoverflow.com/questions/18891997/how-to-change-authorize-attributes-parameter-at-runtime) and [here ](https://stackoverflow.com/questions/30099613/dynamically-add-roles-to-authorize-attribute-for-controller) for further informations or google for it.
