### ISSUE TITLE
Cannot retrieve client IP address

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#9996]
When I check the audit logs table, I seet that the `ClientIpAddress` field is not correct.
I guess, AuditLog module cannot retrieve IP address correctly.
Investigate the problem and find a proper way to retrieve the correct client IP address.
![image](https://user-images.githubusercontent.com/9526587/132649439-f9d8359f-0e5e-4b26-aff0-74110e083050.png)

**Comment by maliming** [comment]
We can custom the `IWebClientInfoProvider`

https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/WebClientInfo/HttpContextWebClientInfoProvider.cs#L8
