### ISSUE TITLE
swagger error

### ISSUE THREAD

**Issue by 312977** [abpframework/abp#9999]
context.Services.AddAuthentication(c =>
            {
                c.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                c.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            context.Services.AddAuthentication().AddJwtBearer(options =>
            {
                options.Authority = configuration["AuthServer:Authority"];
                options.RequireHttpsMetadata = Convert.ToBoolean(configuration["AuthServer:RequireHttpsMetadata"]);
                options.Audience = "Test";
                options.BackchannelHttpHandler = new HttpClientHandler
                {
                    ServerCertificateCustomValidationCallback =
                        HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
                };
            });
when i set  c.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                c.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

the swagger aauthorize  get error:
`NullReferenceException: Object reference not set to an instance of an object.
IdentityServer4.Extensions.StringExtensions.AddQueryString(string url, string query)
IdentityServer4.Extensions.StringExtensions.AddQueryString(string url, string name, string value)
IdentityServer4.Endpoints.Results.LoginPageResult.ExecuteAsync(HttpContext context)
IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.ApplicationBuilderAbpJwtTokenMiddlewareExtension+<>c__DisplayClass0_0+<<UseJwtTokenMiddleware>b__0>d.MoveNext()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

  i  want to return 401 json ,is not return 200 html, how to fix it?

in my application service ,  my api code like below，how to fix it?

**Comment by 312977** [comment]
`[Authorize]
[Route("PlatformAdmin/[Controller]/[Action]")]
public class TenantsAppService : ApplicationService
{
    [HttpGet]
    [Authorize("AbpTenantManagement.Tenants")]
    public async Task<TenantsListVm> GetAsync(int id)
    {
        using (_dataFilter.Disable<IMultiTenant>())
        {
            var query = await _queryableRepository.TenantInfo_Tenant_AppUser();
            return query.Where(c => c.Id == id).Select(c => new TenantsListVm
            {
                Id = c.Id,
                DaoQiShiJian = c.DaoQiShiJian,
                FeiYong = c.FeiYong,
                FeiYongBeiZhu = c.FeiYongBeiZhu,
                Balance = c.Balance,
                KeTiXianJinE = c.KeTiXianJinE,
                JiFeiFangShi = c.JiFeiFangShi,
                Name = c.Tenant.Name,
                CustomerName = c.User.GetUserField("Name"),
                Phone = c.User.UserName,
                LastModificationTime = c.LastModificationTime,
                IsDeleted = c.IsDeleted
            }).FirstOrDefault();
        }
    }
}`

**Comment by 312977** [comment]
[Authorize]
[Route("PlatformAdmin/[Controller]/[Action]")]
public class TenantsAppService : ApplicationService
{
    [HttpGet]
    [Authorize("AbpTenantManagement.Tenants")]
    public async Task<TenantsListVm> GetAsync(int id)
    {
        using (_dataFilter.Disable<IMultiTenant>())
        {
            var query = await _queryableRepository.TenantInfo_Tenant_AppUser();
            return query.Where(c => c.Id == id).Select(c => new TenantsListVm
            {
                Id = c.Id,
                DaoQiShiJian = c.DaoQiShiJian,
                FeiYong = c.FeiYong,
                FeiYongBeiZhu = c.FeiYongBeiZhu,
                Balance = c.Balance,
                KeTiXianJinE = c.KeTiXianJinE,
                JiFeiFangShi = c.JiFeiFangShi,
                Name = c.Tenant.Name,
                CustomerName = c.User.GetUserField("Name"),
                Phone = c.User.UserName,
                LastModificationTime = c.LastModificationTime,
                IsDeleted = c.IsDeleted
            }).FirstOrDefault();
        }
    }
}

**Comment by maliming** [comment]
* Your **ABP Framework version**.
* Steps needed to **reproduce** the problem.
